### ISSUE TITLE
Bidirectional_dynamic_rnn in while_loop results in: AttributeError: 'GradLoopState' object has no attribute 'forward_ctxt'

### ISSUE THREAD

**Issue by msevrens** [tensorflow/tensorflow#3738]
I'm attempting to recreate this [model](https://github.com/bplank/bilstm-aux) in TensorFlow but I can not seem to get anywhere close to the speed of the original code. On average the TensorFlow implementation is taking 60 ms per document on a GPU, while the pycnn is taking 12 ms per document on a CPU.

What appears to be the issue is that _rnn_step will call the LSTM cell on every time step regardless of whether the input at that position is padding or not and then simply fill those values with zeros after the fact using sequence_length. This seems like a lot of unnecessary calculations. 

Processing the tokens sequentially in multiple session.run calls with one token per batch in a similar performance to the original code but the embeddings do not update as the flow is broken.

Current working (but slow) code is below.

```
def char_encoding(config, graph, doc_len):
	"""Create graph nodes for character encoding"""

	c2i = config["c2i"]
	max_tokens = config["max_tokens"]

	with graph.as_default():

		# Character Embedding
		word_lengths = tf.placeholder(tf.int64, [None], name="word_lengths")
		word_lengths = tf.gather(word_lengths, tf.range(tf.to_int32(doc_len)))
		char_inputs = tf.placeholder(tf.int32, [None, max_tokens], name="char_inputs")
		cembed_matrix = tf.Variable(tf.random_uniform([len(c2i.keys()), config["ce_dim"]], -0.25, 0.25), name="cembeds")
		
		char_inputs = tf.transpose(char_inputs, perm=[1,0])
		cembeds = tf.nn.embedding_lookup(cembed_matrix, char_inputs, name="ce_lookup")
		cembeds = tf.gather(cembeds, tf.range(tf.to_int32(doc_len)))
		cembeds = tf.transpose(cembeds, perm=[1,0,2])

		# Create LSTM for Character Encoding
		fw_lstm = tf.nn.rnn_cell.BasicLSTMCell(config["ce_dim"], state_is_tuple=True)
		bw_lstm = tf.nn.rnn_cell.BasicLSTMCell(config["ce_dim"], state_is_tuple=True)

		# Encode Characters with LSTM
		options = {
			"dtype": tf.float32,
			"sequence_length": word_lengths,
			"time_major": True
		}

		(output_fw, output_bw), output_states = tf.nn.bidirectional_dynamic_rnn(fw_lstm, bw_lstm, cembeds, **options)
		output_fw = tf.transpose(output_fw, perm=[1,0,2])
		output_bw = tf.transpose(output_bw, perm=[1,0,2])

		return output_fw, output_bw, word_lengths

```

An alternate approach where I loop through the tokens in the graph itself seems like it should be faster but is throwing an odd error: 

Code:

```
def char_encoding(config, graph, doc_len):
	"""Create graph nodes for character encoding"""

	c2i = config["c2i"]
	max_tokens = config["max_tokens"]

	with graph.as_default():

		# Character Embedding
		word_lengths = tf.placeholder(tf.int64, [None], name="word_lengths")
		word_lengths = tf.gather(word_lengths, tf.range(tf.to_int32(doc_len)))
		char_inputs = tf.placeholder(tf.int32, [None, max_tokens], name="char_inputs")
		char_inputs = tf.transpose(char_inputs, perm=[1, 0])
		cembed_matrix = tf.Variable(tf.random_uniform([len(c2i.keys()), config["ce_dim"]], -0.25, 0.25), name="cembeds")

		# Create LSTM for Character Encoding
		fw_lstm = tf.nn.rnn_cell.BasicLSTMCell(config["ce_dim"], state_is_tuple=True)
		bw_lstm = tf.nn.rnn_cell.BasicLSTMCell(config["ce_dim"], state_is_tuple=True)

		def one_pass(i, o_fw, o_bw):

			int_i = tf.to_int32(i)

			options = {
				"dtype": tf.float32,
				"sequence_length": tf.expand_dims(tf.gather(word_lengths, int_i), 0),
				"time_major": True
			}

			cembeds_invert = tf.nn.embedding_lookup(cembed_matrix, tf.gather(char_inputs, int_i))
			cembeds_invert = tf.transpose(tf.expand_dims(cembeds_invert, 0), perm=[1,0,2])

			(output_fw, output_bw), output_states = tf.nn.bidirectional_dynamic_rnn(fw_lstm, bw_lstm, cembeds_invert, **options)

			# Get Last Relevant
			output_fw = tf.gather(output_fw, tf.gather(word_lengths, int_i) - 1)
			output_bw = tf.gather(output_bw, tf.gather(word_lengths, int_i) - 1)

			# Append to Previous Token Encodings
			o_fw = o_fw.write(int_i, tf.squeeze(output_fw))
			o_bw = o_bw.write(int_i, tf.squeeze(output_bw))

			return tf.add(i, 1), o_fw, o_bw

		# Build Loop in Graph
		i = tf.constant(0.0)
		float_doc_len = tf.to_float(doc_len)
		o_fw = tensor_array_ops.TensorArray(dtype=tf.float32, size=tf.to_int32(doc_len))
		o_bw = tensor_array_ops.TensorArray(dtype=tf.float32, size=tf.to_int32(doc_len))
		cond = lambda i, *_: tf.less(i, float_doc_len)
		i, char_embeds, rev_char_embeds = tf.while_loop(cond, one_pass, [i, o_fw, o_bw])

		return char_embeds.pack(), rev_char_embeds.pack()
```

Error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/git/Meerkat/meerkat/longtail/bilstm_tagger.py", line 445, in <module>
    run_from_command_line()
  File "/home/ubuntu/git/Meerkat/meerkat/longtail/bilstm_tagger.py", line 441, in run_from_command_line
    graph, saver = build_graph(config)
  File "/home/ubuntu/git/Meerkat/meerkat/longtail/bilstm_tagger.py", line 311, in build_graph
    optimizer = tf.train.GradientDescentOptimizer(config["learning_rate"]).minimize(loss, name="optimizer")
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/optimizer.py", line 196, in minimize
    grad_loss=grad_loss)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/optimizer.py", line 253, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gradients.py", line 478, in gradients
    in_grads = _AsList(grad_fn(op, *out_grads))
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/control_flow_grad.py", line 202, in _EnterGrad
    result = grad_ctxt.AddBackPropAccumulator(op, grad)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1646, in AddBackPropAccumulator
    forward_ctxt = self.grad_state.forward_ctxt
AttributeError: 'GradLoopState' object has no attribute 'forward_ctxt'
```

Let me know if seeing the full graph will help at all. Right now that higher level LSTM isn't causing issues because I can just run one document at a time.

**Comment by msevrens** [comment]
This seems related but it doesn't seem it was ever resolved:

https://github.com/tensorflow/tensorflow/issues/511

**Comment by msevrens** [comment]
Whats most frustrating is that if one token is 50 characters long and 10 other tokens in that batch are 3 characters long it essentially takes the same time to process as if every token was 50 characters long. There must be a better way to approach this.

**Comment by girving** [comment]
Yes, the RNN code always runs up to the maximum length.  This is usually solved at a higher level by bucketing by input size.

**Comment by msevrens** [comment]
@girving

I don't think bucketing by input size works in this case. A sub-LSTM is encoding each token in the each sentence. There's only a limited number of tokens in each document. At each step a LSTM encoding of each token is concatenated with work a word embedding before fed into a higher level LSTM for tagging. 

I've attempted to not call the cell at ever step like this

```
flat_state = nest.flatten(state)
	flat_zero_output = nest.flatten(zero_output)

	def select_relevant_state(state, mask):
		c = tf.boolean_mask(state[0], mask)
		h = tf.boolean_mask(state[1], mask)
		return (c, h)

	# Function to Perform at Each Time Step
	def time_step(time, output_ta, state):

		mask = (time < sequence_length)
		indices = tf.squeeze(tf.to_int32(tf.where(mask)))
		invert_indices = tf.squeeze(tf.to_int32(tf.where(invert_mask)))
		invert_indices = tf.to_int32(tf.where(invert_mask))
		input_t = tuple(ta.read(time) for ta in input_ta)

		# Restore Shape Information
		for input_, shape in zip(input_t, inputs_got_shape):
			input_.set_shape(shape[1:])

		input_t = nest.pack_sequence_as(structure=inputs, flat_sequence=input_t)
		
		# Select Only Relevant at This Time Step
		input_t = tf.boolean_mask(input_t, mask)
		state = select_relevant_state(state, mask)
		call_cell = lambda: cell(input_t, state)

		# Call Cell
		(output, new_state) = call_cell()

		# Fill Unprocessed Steps
		filler_output = tf.boolean_mask(zero_output, invert_mask)
		filler_state = select_relevant_state(state, invert_mask)

		output = tf.dynamic_stitch([indices, invert_indices], [output, filler_output])
		new_state_c = tf.dynamic_stitch([indices, invert_indices], [new_state[0], filler_state[0]])
		new_state_h = tf.dynamic_stitch([indices, invert_indices], [new_state[1], filler_state[1]])
		new_state = tf.pack([new_state_c, new_state_h], axis=0)

		# Pack State if Using State Tuples
		output = nest.flatten(output)

		output_ta = tuple(ta.write(time, out) for ta, out in zip(output_ta, output))

		return (time + 1, output_ta, new_state)
```

But this seems to make no difference. It appears that the majority of time is being taken up by back propagation. Is there a means to intervene at this level?

Is there no way to use the same approach as pycnn and get the same performance? The difference is huge.

**Comment by girving** [comment]
You mention that pycnn does something better.  Can you describe the approach?

**Comment by msevrens** [comment]
Pycnn isn't documented as well, but the original code at https://github.com/bplank/bilstm-aux simply iterates through each token and then concats the output to the word embeddings. 

```
class RNNSequencePredictor(SequencePredictor):
	def __init__(self, rnn_builder):
		"""
		rnn_builder: a LSTMBuilder or SimpleRNNBuilder object.
		"""
		self.builder = rnn_builder
		
	def predict_sequence(self, inputs):
		s_init = self.builder.initial_state()
		return [x.output() for x in s_init.add_inputs(inputs)] #quicker version
```

```
for chars_of_token in char_indices:
            # use last state as word representation
            last_state = self.char_rnn.predict_sequence([self.cembeds[c] for c in chars_of_token])[-1]
            rev_last_state = self.char_rnn.predict_sequence([self.cembeds[c] for c in reversed(chars_of_token)])[-1]
            char_emb.append(last_state)
            rev_char_emb.append(rev_last_state)
            
        wfeatures = [self.wembeds[w] for w in word_indices]
        features = [pycnn.concatenate([w,c,rev_c]) for w,c,rev_c in zip(wfeatures,char_emb,reversed(rev_char_emb))]
```

I posted a similar approach in TensorFlow above but got the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/git/Meerkat/meerkat/longtail/bilstm_tagger.py", line 445, in <module>
    run_from_command_line()
  File "/home/ubuntu/git/Meerkat/meerkat/longtail/bilstm_tagger.py", line 441, in run_from_command_line
    graph, saver = build_graph(config)
  File "/home/ubuntu/git/Meerkat/meerkat/longtail/bilstm_tagger.py", line 311, in build_graph
    optimizer = tf.train.GradientDescentOptimizer(config["learning_rate"]).minimize(loss, name="optimizer")
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/optimizer.py", line 196, in minimize
    grad_loss=grad_loss)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/optimizer.py", line 253, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gradients.py", line 478, in gradients
    in_grads = _AsList(grad_fn(op, *out_grads))
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/control_flow_grad.py", line 202, in _EnterGrad
    result = grad_ctxt.AddBackPropAccumulator(op, grad)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1646, in AddBackPropAccumulator
    forward_ctxt = self.grad_state.forward_ctxt
AttributeError: 'GradLoopState' object has no attribute 'forward_ctxt'
```

I've solved on how to run the RNN while only calling the cell on the relevant characters (can post code if necessary) but the issue persists so it seems the fundamental issue is the time that back propagation takes rather than the time it takes to do the forward pass.

**Comment by msevrens** [comment]
Are there any details on how back prop flows through tensorArrays?

**Comment by girving** [comment]
@yuanbyu He's trying to do a two dimensional while loop, and the code looks reasonable to me at first glance.  Could you take a look?

**Comment by girving** [comment]
@msevrens I somewhat doubt we have good documentation for while loop differentiation, but @yuanbyu can correct me if we have it.

**Comment by therne** [comment]
Same issue here. I've implemented 2d RNN using `tf.while` but got only `AttributeError: 'GradLoopState' object has no attribute 'forward_ctxt'` error. 😞

**Comment by msevrens** [comment]
This seems relevant: https://github.com/tensorflow/tensorflow/issues/593

**Comment by girving** [comment]
@msevrens I forgot to verify: what version of TensorFlow are you using?

**Comment by msevrens** [comment]
@girving 
0.9.0

**Comment by yuanbyu** [comment]
Could you provide a complete running program that can reproduce the problem?

**Comment by msevrens** [comment]
@girving: I've confirmed that the issue still exists on 0.10.0rc0

@yuanbyu: I've attached a stripped down version that isolates the issue.
[bilstm_tagger.txt](https://github.com/tensorflow/tensorflow/files/414650/bilstm_tagger.txt)

**Comment by therne** [comment]
I think GradLoopState error is occured by this [commit](https://github.com/tensorflow/tensorflow/commit/0ab76c2cf2b3a34f4cb985875512830aadea9afd) by @yuanbyu . This code makes no sense - because i think this code has a lot of syntax error (ex: `forward_ctxt` is nowhere (did you meant `forward_context`?), `grad_state` and `outer_grad_state` is not defined.)

Can you confirm it?

**Comment by msevrens** [comment]
@therne

Perhaps you could provide @yuanbyu another sample of code that results in this error such that it's easier for him to debug?

**Comment by therne** [comment]
@msevrens Unfortunately I can't share my code because it has too many local dependency 😢 Instead, i'm trying to reproduce the error using simpler code.

**Comment by ebrevdo** [comment]
@girving Please keep in mind, if your max sequence_length is less than the total number of inputs to `rnn`, then the calculation is exited early (however, anything past the max sequence length *must* be filled with zeros because TensorFlow requires all outputs to be filled by *something*).

If your minibatch sizes vary from iteration to iteration, you could try using `tf.nn.dynamic_rnn`, and make sure that for your LSTM inputs (now tensors of shape `batch_size, max_time_per_batch, depth`) have a `max_time_per_batch` which is exactly equal to the maximum number of frames for that minibatch (and no larger).

**Comment by ebrevdo** [comment]
(when i say minibatch sizes, i mean minibatch maximum time step counts)

**Comment by msevrens** [comment]
@ebrevdo I think maybe you should take a little more time reading through the previous posts

**Comment by msevrens** [comment]
@ebrevdo 
In reality if you look at _dynamic_rnn_loop all values at each time step are passed to the LSTM cell. The forward pass is then applied to everything regardless of the sequence_length provided.

```
input_t = tuple(ta.read(time) for ta in input_ta)
call_cell = lambda: cell(input_t, state)
```

Therefore, a max_time_step of 100 with all documents having 100 length with take the same amount of time as a max_time_step of 100 with all documents having a length of 20. The only thing sequence_length is used for is to copy in filler zeros AFTER calculation has already occurred.

Seeing as pycnn does the same task on the CPU five times faster than TF does on the GPU shows there's definitely room from improvement here. And I would imagine actually having the "computation exit early" would be the first step. Though as I showed above, simply not calling the cell at every step during the forward pass does little to help. The gradient calculation and application is still a bit spaghetti to me so I can't comment on that yet.

**Comment by msevrens** [comment]
@girving @yuanbyu 

So I've discovered that training on the CPU only and clocked at 70ms per training step versus 180ms per training step.

Is this expected behavior? Are LSTMs inherently faster on a CPU?

Note that the GradLoopState is still an issue and this is still half the speed that pycnn trains the same model.

**Comment by ebrevdo** [comment]
Matt: how large are your hidden states and inputs and batch sizes?  The
larger each of these parameters is, the faster that GPU training will be
relative to CPU training.

Are you using the sequence_lengths input parameter?  How fast does training
become if you don't use it?

**Comment by girving** [comment]
@ebrevdo Those comments are helpful, but someone should also investigate why his attempt to make it faster throws an obscure error.

**Comment by msevrens** [comment]
@ebrevdo 

The primary speed drain is the inner LSTM which does character encoding. Both the batch size and the max_sequence_length of this inner LSTM are variable. This helps speed it up quite a bit.

Outer LSTM doesn't use batching, same as original paper.

Removing sequence lengths throws an error. Hidden dims are 100. Running on CPU is fine though as long as long as it matches the speed of pycnn code. As of now on CPU it's about half the speed.

I'm mainly interested now in the nested loop issue as this would seem to solve the fundamental problem of unnecessary calculation. In pycnn time scales relative to number of characters in the sentence. In TensorFlow time scales to `max_token_length * num_tokens`. As token length can be extremely variable in my dataset, until that issue is solved everything seems negligible.

@girving 
I'm working on a more stripped down bare bones version of the issue to help debugging.

**Comment by ebrevdo** [comment]
With a batch size of 1 and 100 dims, you generally don't get enough data
going through to saturate the GPU's matmul powers; and copying data to/from
the GPU becomes the bottleneck.

dynamic_rnn accepts a tensor with a shape of max_time_for_this_minibatch
and does not perform early stopping for two reasons:
1. you can provide an inputs tensor where max_time_for_this_minibatch is
truly the maximum time *for this minibatch*
2. having a bunch of cond ops (which must run on CPU) will add additional
slowdown to the computation, especially if most of the computation is on a
GPU.  and because of #1 it's unnecessary since the length of the
computation can be variable and is determined by the input tensor
dimensions.  if you are using placeholders, simply use
placeholder(shape=(batch_size, None, input_depth), dtype=...) and feed in
properly sized inputs.

In contrast, with tf.nn.rnn, you always have a fixed graph and using cond()
to reduce the number of calls to the LSTM cell (especially the matmuls) is
extremely important.  In this case, sequence_lengths is used to replace
this computation past max(sequence_lengths) with just symbolically copying
some zero values through (this is essentially free).

**Comment by msevrens** [comment]
@ebrevdo 
I don't think this really solves my fundamental issue. If one token in the batch to the inner LSTM has a length of 100 and the rest have a length of 3 there will always be a huge performance deficit if they are batched. Either the tokens are batched together, or they're looped over. The output of this is fed into a higher LSTM which only has a batch size of 1.

The batching approach is unreasonably slow when one token is far longer than the rest, the nested loop approach is throwing an obscure error.

**Comment by alquraishi** [comment]
@ebrevdo, regarding #1, would it make sense to include convenience functionality in dynamic_rnn that trims the input tensor to the max_time_for_this_minibatch based on `sequence_length`? I _think_ this is easy to do, no?

**Comment by ebrevdo** [comment]
@alquraishi since this is equivalent to doing a simple `slice` or `gather`, and would bloat the already bloated interface of `dynamic_rnn`, i'd prefer not to do it there.

**Comment by ebrevdo** [comment]
@msevrens now you are really at the fundamental core of how to deal with RNNs and minibatches.  unfortunately this is out of the hands of e.g. `dynamic_rnn` and has to be handled by the preprocessing technique.

there are two ways to solve this problem.  one is called truncated back propagation through time, and works on models where you have a loss at every time step (e.g. cross entropy loss).  for this we just added a contrib method called `tf.contrib.training.batch_sequence_with_states`.  You will have to look at truncated BPTT literature and the documentation for that algorithm in depth to understand what it's doing.

The other approach is called bucketing, and the idea there is, when you read your examples in, group them according to similar lengths and put them in the appropriate queue.  The training step reads off the next available queue and processes the minibatch accordingly.  Each minibatch will contain sequences of approximately the same length.  I plan to make something like this available in contrib very soon.  Keep in mind this approach breaks the `independent` part of `i.i.d.` when training SGD minibatches; but in practice it works pretty well!

**Comment by ebrevdo** [comment]
My understanding of this bug is that you are running into several issues; one of which is that your batch sizes are too small to effectively take advantage of GPU; and when they do grow large you have too large a variance in the sequence lengths to properly avoid unnecessary unrolls.  I've proposed two solutions above to do this (one already in, one called bucketing which is coming soon).  I'll keep this issue open until bucketing is available in contrib.

**Comment by ebrevdo** [comment]
I'm also renaming the issue to better reflect the true problem.

**Comment by girving** [comment]
@ebrevdo The new title ignores the while-loop related obscure error, though I suppose the other one does to.  I think @msevrens understands the issues involved, and believes he has a fix except for the obscure error.  It might be better to rename the issue to reflect that error, and then debug it.

**Comment by msevrens** [comment]
@ebrevdo 
The original paper is not using truncated back propagation through time. The final outputs from the forward and backward passes of the inner LSTM on each token are concatenated to a word embedding and fed into the higher level LSTM. There is no loss at every step as the loss comes from the higher level LSTM. 

We also discussed bucketing above and that will not work either as the mini batch itself is the sentence input. Both the inner and outer LSTM are optimized together using the loss from the higher level LSTM. So the batch for the inner LSTM will always be the tokens from the sentence being tagged. 

This architecture seems pretty tied to what is causing the performance issue. At this point, barring a major change to how LSTM's are handled by TensorFlow I believe the best solution is this while loop approach. 

@girving 
I agree, I'm going to change the title

**Comment by ebrevdo** [comment]
One way to handle this might be to combine multiple shorter examples into a
single long example, with state reset indicators in between, and minibatch
these longer examples. This kind of bookkeeping is not impossible in a Tf
graph, but it's also not easy. I've never seen it done.

**Comment by girving** [comment]
@ebrevdo That's a wonderful idea!  It would reduce the slowdown to at most a factor of 2 (or maybe 3?).  If some tricky bookkeeping is required, maybe an organizational C++ op is worth it?

**Comment by msevrens** [comment]
@girving @ebrevdo @yuanbyu 

I've put together a much shorter and simpler code sample that replicates the bug. Hopefully this will be helpful in debugging:

```
import tensorflow as tf
import numpy as np

from tensorflow.python.ops import tensor_array_ops

# Prepare Input

tokens = ["the", "fox", "jumps", "over", "the", "erroneous", "dog"]
tags = ["other", "noun", "other", "other", "other", "other", "noun"]

tag_map = {
	"noun": 0,
	"other": 1
}

tags = np.array([int(tag_map[tag]) for tag in tags])
encoded_tags = (np.arange(len(tag_map)) == tags[:, None]).astype(np.float32)

alphabet = "abcdefghijklmnopqrstuvwxyz0"
c2i = {a : i for i, a in enumerate(alphabet)}

char_inputs = []
token_lengths = [len(t) for t in tokens]
max_token_length = max(token_lengths)
num_tokens = len(tokens)

for token in tokens:
	char_ind = [c2i[token[c]] if c < len(token) else c2i["0"] for c in range(max_token_length)]
	char_inputs.append(char_ind)

# Build Graph

graph = tf.Graph()

with graph.as_default():

	# Character Embeddings
	character_indices = tf.placeholder(tf.int32, [len(tokens), max_token_length])
	word_lengths = tf.placeholder(tf.int32, [None])

	cembed_matrix = tf.Variable(tf.random_uniform([len(c2i), 100]))
	inner_lstm = tf.nn.rnn_cell.BasicLSTMCell(100, state_is_tuple=True)

	# Outer Loop Body
	def outer_body(i, s_out):

		token_input = tf.nn.embedding_lookup(cembed_matrix, tf.gather(character_indices, i))
		token_input = tf.expand_dims(token_input, 0)
		token_input = tf.transpose(token_input, perm=[1,0,2])

		options = {
            "dtype": tf.float32,
			"sequence_length": tf.expand_dims(tf.gather(word_lengths, i), 0),
			"time_major": True,
			"scope": "inner"
        }

		output, state = tf.nn.dynamic_rnn(inner_lstm, token_input, **options)
		last_output = tf.gather(output, tf.gather(word_lengths - 1, i))
		s_out = s_out.write(i, tf.squeeze(last_output))

		return tf.add(i, 1), s_out

	# Build Loop in Graph
	i = tf.constant(0)
	sentence_output = tensor_array_ops.TensorArray(dtype=tf.float32, size=num_tokens)
	outer_cond = lambda i, *_: tf.less(i, num_tokens)
	_, encoded_chars = tf.while_loop(outer_cond, outer_body, [i, sentence_output])
	encoded_chars = encoded_chars.pack()

	# Outer LSTM
	outer_lstm = tf.nn.rnn_cell.BasicLSTMCell(100, state_is_tuple=True)
	weight = tf.Variable(tf.random_uniform([100, len(tag_map)]))
	batched_input = tf.expand_dims(encoded_chars, 0)

	options = {
		"dtype": tf.float32,
		"sequence_length": tf.expand_dims(num_tokens, 0),
		"scope": "outer"
	}

	output, state = tf.nn.dynamic_rnn(outer_lstm, batched_input, **options)
	prediction = tf.log(tf.nn.softmax(tf.matmul(tf.gather(output, num_tokens), weight)))

	# Calculate Loss and Optimize
	labels = tf.placeholder(tf.float32, shape=[None, len(tag_map)])
	loss = tf.neg(tf.reduce_sum(prediction * labels))
	optimizer = tf.train.GradientDescentOptimizer(0.1).minimize(loss)

# Run Session

with tf.Session(graph=graph) as sess:

	tf.initialize_all_variables().run()

	feed_dict = {
		character_indices : char_inputs,
		word_lengths : token_lengths,
		labels: encoded_tags
	}

	sess.run(optimizer, feed_dict=feed_dict)
```

**Comment by msevrens** [comment]
@ebrevdo

That's a pretty good idea. I'll take a shot at it.

In the meantime can you take a look at the code I posted at https://github.com/tensorflow/tensorflow/issues/3738#issuecomment-241531134 and let me know if can see any issue with this looping approach?

I'm really interested in debugging this error, but at this point the TensorFlow internals are still a bit confusing to me.

**Comment by msevrens** [comment]
@yuanbyu 

I got the most recent version of tensorFlow with your fix to a related nested looping issue here: https://github.com/tensorflow/tensorflow/commit/096069687c52e16eaa18c1db6e7bbf2737639257  however the GradLoopState issue persists. Any thoughts?

**Comment by msevrens** [comment]
@girving @yuanbyu @ebrevdo 

Is this dead? Is there any progress on this? Do I just need to give up on nested looping? I still would like to see this fixed.

**Comment by yuanbyu** [comment]
It was fixed on our side, and should be in HEAD very soon.

**Comment by msevrens** [comment]
@yuanbyu 
Awesome, looking forward to testing it out.

**Comment by msevrens** [comment]
@yuanbyu 
The current code in github actually does fix the simpler nested loop example I provided above. Unfortunately, the same error appears when I run the more complex version of the nested loop I'm using for the tagger. I'm not sure what the key difference is.

Example here: 
[nested_loop.txt](https://github.com/tensorflow/tensorflow/files/464999/nested_loop.txt)

I'm not sure whether the full fix is in git yet or if what's in currently is a partial fix.

**Comment by yuanbyu** [comment]
Running your code gave the following error:

File "/usr/local/google/_blaze_yuanbyu/4e574b920d97309ebaf8003010ddff1b/execroot/google3/blaze-out/gcc-4.X.Y-crosstool-v18-hybrid-grtev4-k8-opt/bin/experimental/users/yuanbyu/python/dynamic_rnn1.runfiles/google3/experimental/users/yuanbyu/python/dynamic_rnn1.py", line 284, in train_model
    optimizer_out, loss = sess.run([get_op(graph, "optimizer"), get_tensor(graph, "loss:0")], feed_dict=feed_dict)
  File "/usr/local/google/_blaze_yuanbyu/4e574b920d97309ebaf8003010ddff1b/execroot/google3/blaze-out/gcc-4.X.Y-crosstool-v18-hybrid-grtev4-k8-opt/bin/experimental/users/yuanbyu/python/dynamic_rnn1.runfiles/google3/experimental/users/yuanbyu/python/dynamic_rnn1.py", line 54, in get_op
    return graph.get_operation_by_name(name)
  File "/usr/local/google/_blaze_yuanbyu/4e574b920d97309ebaf8003010ddff1b/execroot/google3/blaze-out/gcc-4.X.Y-crosstool-v18-hybrid-grtev4-k8-opt/bin/experimental/users/yuanbyu/python/dynamic_rnn1.runfiles/google3/third_party/tensorflow/python/framework/ops.py", line 2579, in get_operation_by_name
    return self.as_graph_element(name, allow_tensor=False, allow_operation=True)
  File "/usr/local/google/_blaze_yuanbyu/4e574b920d97309ebaf8003010ddff1b/execroot/google3/blaze-out/gcc-4.X.Y-crosstool-v18-hybrid-grtev4-k8-opt/bin/experimental/users/yuanbyu/python/dynamic_rnn1.runfiles/google3/third_party/tensorflow/python/framework/ops.py", line 2451, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/local/google/_blaze_yuanbyu/4e574b920d97309ebaf8003010ddff1b/execroot/google3/blaze-out/gcc-4.X.Y-crosstool-v18-hybrid-grtev4-k8-opt/bin/experimental/users/yuanbyu/python/dynamic_rnn1.runfiles/google3/third_party/tensorflow/python/framework/ops.py", line 2511, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'optimizer' refers to an Operation not in the graph."

**Comment by yuanbyu** [comment]
By the way, if you got exactly the same error as before:

```
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/control_flow_grad.py", line 202, in _EnterGrad
    result = grad_ctxt.AddBackPropAccumulator(op, grad)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1646, in AddBackPropAccumulator
    forward_ctxt = self.grad_state.forward_ctxt
AttributeError: 'GradLoopState' object has no attribute 'forward_ctxt'
```

It is very likely that you were using an older version that doesn't include the fix.

**Comment by msevrens** [comment]
The GradLoopState error should occur before the error you're seeing so it appears to be solved on your system.

Unfortunately I no longer seem to be able to build from scratch using the most recent code so I'll need to debug that before I can confirm.

**Comment by msevrens** [comment]
@yuanbyu 

So I got TF to build and it appears the issue with nested looping is solved. Thanks for your effort on this.

Unfortunately the looping approach I was attempting did not speed up the training or execution of the model I'm working with but as far as this issue goes it can be closed.
