### ISSUE TITLE
More elaborate logging implementation (implementing TFLogSink s, etc.)

### ISSUE THREAD

**Issue by csachs** [tensorflow/tensorflow#37390]
**System information**
- TensorFlow version: master
- Are you willing to contribute it: Yes

**Describe the feature and the current behavior/state.**
Currently, logging seems to directly write to `stderr`, if the log messages level fits the current log level.
https://github.com/tensorflow/tensorflow/blob/efff893c709b585da9771cb3a2997321efef36ae/tensorflow/core/platform/default/logging.cc#L259
This is a pity, since the message is lost for other code (I'm currently going thru some hoops to fetch them from `stderr` but the solution is problematic), and in particular, it does not adhere to unified logging approaches, with Python users probably expecting their log message to end up in Python's logging infrastructure. Furthermore, many people seem to search for ways to suppress them, and setting the log level via env vars seems to be not the least confusing approach for many (cf. https://github.com/tensorflow/tensorflow/issues/1258 https://github.com/tensorflow/tensorflow/issues/566).

Taking a look at the source, it seems that conceptionally, more logging infrastructure is planned, but  has not yet been implemented:
https://github.com/tensorflow/tensorflow/blob/47df0000dc3af299cef581811c2ad58f3eda700b/tensorflow/core/platform/default/logging.cc#L40

Therefore the steps seem to be: Implement and use the `TFLogSink` infrastructure, by default adding a logger writing to `stderr`. Implementing a `TFLogSink` which can pass log messages to Python, loaded and added by the Python code, replacing the `stderr` logging. Adding API to to enumerate current log sinks.

Is anyone working on this? In some comments it seems that Google-internal TF might use more elaborate logging infrastructure, is any of this due to be added to open source TF? What are the opinions of the TF team on the issue?

**Will this change the current api? How?**
No. It will add additional possibilities, but not break existing code.
**Who will benefit with this feature?**
People who want finer grained control of logging.
**Any Other info.**
–

**Comment by rohan100jain** [comment]
We're not actively working on this right now but would love it if you could contribute a PR here. Will be more than happy to review / support.

**Comment by csachs** [comment]
I'm currently somewhat busy with other projects, but I'll try to take a look in this. (Which shouldn't prevent anyone from doing the same!) I'm not very familiar with TensorFlow's inner C++ structure hence I'll need to do some exploring first. I think this issue should definitely be left open so others can track the progress.

**Comment by mihaimaruseac** [comment]
Solved by #41733
