### ISSUE TITLE
FasterRCNN_resnet101 .tflite conversion

### ISSUE THREAD

**Issue by pushkalkatara** [tensorflow/tensorflow#37401]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): pip install tf-nightly

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_saved_model("/content/trained_m2_data_38000steps_resnet101/saved_model")

converter.experimental_new_converter = True  # Add this line

tflite_model = converter.convert()
```

**The output from the converter invocation**

```
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
---------------------------------------------------------------------------
ConverterError                            Traceback (most recent call last)
<ipython-input-9-4edb7ba34fed> in <module>()
      4 converter.experimental_new_converter = True  # Add this line
      5 
----> 6 tflite_model = converter.convert()
      7 
      8 '''

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    225       stdout = _try_convert_to_unicode(stdout)
    226       stderr = _try_convert_to_unicode(stderr)
--> 227       raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
    228   finally:
    229     # Must manually cleanup files.

ConverterError: See console for info.
2020-03-06 20:56:59.840264: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:305] Ignored output_format.
2020-03-06 20:56:59.840346: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:308] Ignored drop_control_dependency.
2020-03-06 20:57:00.599028: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
loc("FirstStageFeatureExtractor/resnet_v1_101/resnet_v1_101/Pad"): error: 'tfl.pad' op failed to verify that operand 0's rank equals operand 1's size
Traceback (most recent call last):
  File "/usr/local/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: <unknown>:0: error: loc("FirstStageFeatureExtractor/resnet_v1_101/resnet_v1_101/Pad"): 'tfl.pad' op failed to verify that operand 0's rank equals operand 1's size
```

**Also, please include a link to the saved model or GraphDef**

```
https://gist.github.com/dkurt/1fe03728dcb51955c89d30dfe6c11a3d
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by pushkalkatara** [comment]
Is Padding layer not supported yet?

**Comment by john5216c** [comment]
Has there been any progress made on this issue ? Thanks!

**Comment by limsijie93** [comment]
I'm also facing the same issue when I'm converting the mask rcnn model from TF object detection API (mask_rcnn_resnet50_coco_2018_01_28) trained on custom dataset.

Reference: [(https://github.com/tensorflow/tensorflow/issues/34845)]

Code:
```
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter.experimental_new_converter = True
tflite_model = converter.convert()
```

Output:
```
ConverterError: See console for info.
2020-03-12 02:41:16.739086: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:305] Ignored output_format.
2020-03-12 02:41:16.739166: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:308] Ignored drop_control_dependency.
2020-03-12 02:41:17.295677: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
loc("FirstStageFeatureExtractor/resnet_v1_50/resnet_v1_50/Pad"): error: 'tfl.pad' op failed to verify that operand 0's rank equals operand 1's size
Traceback (most recent call last):
  File "/usr/local/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: <unknown>:0: error: loc("FirstStageFeatureExtractor/resnet_v1_50/resnet_v1_50/Pad"): 'tfl.pad' op failed to verify that operand 0's rank equals operand 1's size

```

**Comment by Namburger** [comment]
@haozha111 do you have any updates on this issue?

**Comment by haozha111** [comment]
Have you ever tried the new MLIR based TF Lite converter?

It's already enabled by default in TF 2.2 or TF nightly.

**Comment by pushkalkatara** [comment]
@haozha111 Yes I tried with tf-nightly with MLIR enabled in TF Lite converter. Still facing this issue.

were you able to run this successfully?

**Comment by srjoglekar246** [comment]
@pushkalkatara @Namburger Take a look at the comments on [this issue](https://github.com/tensorflow/tensorflow/issues/34845#issuecomment-573156336).

There is a way to convert these MaskRCNN models from the TF object detection repository, but with static shapes & without the segmentation outputs. The simple reason is that these models are too large for mobile inference, so they usually cause memory/latency issues on typical devices.

The linked bug has a method for converting the model by modifying `pipeline.config` & using a script to export the inference graph. But its not the best way, mainly because we don't have a great mobile-friendly version of MaskRCNN, atleast in the TF model zoo.

The newer SSD MobileNetv3 have pretty good performance for bounding-box detection, and DeepLabv3 might be better suited for segmentation (but in a semantic way).

**Comment by john5216c** [comment]
What about Resnet 50 or 101 from the Object Detection framework (Model Zoo) to find bounding boxes (not segmentation) ? It uses FasterRCNN architecture.  

Also can you provide the steps to do the pipeline.config mod to export the model with TFLite ? The specific work around for this error ?

Thanks!

**Comment by srjoglekar246** [comment]
The models should convert with the same changes as mentioned in that issue. You might have to change a couple of commands based on input size etc, which will be given in pipeline.config. Not sure about coral dev board.

TBH, the new SSD MobileNet v3 (large) gives as good a COCO mAP as some of the FasterRCNN architectures, so you could see if that works for your use-case.

**Comment by pushkalkatara** [comment]
@srjoglekar246 I think there would be a good difference in accuracy due to number of deep layers in the models - mobilenet-v3 vs resnet101. 
Currently, FasterRCNN with Resnet101 is generally used for high accuracy and SSD-Mobilenet is used for higher inference speeds. But SSD conversion is supported by TFLite but not FasterRCNN (post says but the error above comes). What are the chances of optimization being successful if we train ssd with backbone resnet101 and achieve comparable accuracy as FasterRCNN-resnet101.

**Comment by srjoglekar246** [comment]
That could be a good idea. (though you will need to start training from scratch).
SSD's post-processing & proposal generation is weaker than FasterRCNN, but having more layers in the back-bone should definitely improve accuracy.

**Comment by pushkalkatara** [comment]
Training a model like resnet101 from scratch is far out of scope. :sweat_smile: . It is better to wait TFLite with FasterRCNN implementation i think.

**Comment by sushreebarsa** [comment]
@pushkalkatara Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!

**Comment by srjoglekar246** [comment]
Hey @pushkalkatara , if this is still an issue, feel free to look at the `SSD ResNet50 V1 FPN 640x640 (RetinaNet50)` model from the [TF2 Detection Zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md). It converts well to TFLite using [these instructions](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md), and should provide better accuracy (at cost of slower speed) than the MobileNet version.

**Comment by sushreebarsa** [comment]
@pushkalkatara Could you please update as per the above [comment](https://github.com/tensorflow/tensorflow/issues/37401#issuecomment-879286909) and let us know if this is still an issue ? Thanks!

**Comment by pushkalkatara** [comment]
It has been a long time since I worked on this project. Guessing it's supported now, so closing the issue. Thanks!
