### ISSUE TITLE
Tensorflow2.0 is not supporting this code

### ISSUE THREAD

**Issue by frytry** [tensorflow/tensorflow#37415]
Tensorflow2.0 is not supporting this `tf.contrib.training.bucket_by_sequence_length` and what can I use instead of this

**Comment by av8ramit** [comment]
Perhaps [`tf.data.experimental.bucket_by_sequence_length`](tf.data.experimental.bucket_by_sequence_length) can help? It might require some modification to use [`tf.data.Dataset`](https://www.tensorflow.org/api_docs/python/tf/data/Dataset).

**Comment by Saduf2019** [comment]
@frytry 
please let us know if the above comment helps.

**Comment by Saduf2019** [comment]
@frytry 
could you please respond to the above comment

**Comment by frytry** [comment]
No it will not work. Both are different... Please check the documentation.

**Comment by Saduf2019** [comment]
@frytry 
please share a simple stand alone code for us to replicate the issue faced.

you could also check [link1](https://github.com/wcarvalho/jupyter_notebooks/blob/ebe762436e2eea1dff34bbd034898b64e4465fe4/tf.bucket_by_sequence_length/bucketing%20practice.ipynb) for reference

**Comment by Saduf2019** [comment]
@frytry
please update on above comment

**Comment by Saduf2019** [comment]
@frytry
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
