### ISSUE TITLE
ValueError: No gradients provided for any variable: ['dense_26/kernel:0', 'dense_26/bias:0']

### ISSUE THREAD

**Issue by beardwolf** [tensorflow/tensorflow#37414]
**System information** 
- OS Platform and Distribution: Windows 10

- TensorFlow installed from Anaconda 1.9.12. Channel: default.
Tensorflow Version: 2.1.0

- Python version: 3.7.6

- CUDA/cuDNN version:
cudatoolkit: 10.1.243
cuDNN: 7.6.5

- GPU: NVidia GeForce GTX 1060, 6 GB

**Describe the current behavior**
I've been developing a Relativistic Style GAN, but when I try to train the discriminator, I keep getting ValueError: No gradients provided for any variable. I replaced the generator and discriminator with empty dummies in order to figure out what was causing the problem, but I still got the error.

I suspect the loss function for while but then I recalled a simple functional non-style version of the RaGAN script used to work fine and without errors during training and produced blurry but recognizable results. When I tried that script again, I got this gradient error as well.

I'm stumped at what could be causing this error.

**Standalone code to reproduce the issue** 
I'm new to GitHub and couldn't manage to past the code in a coherent way so here's
a link to the Jupyter Notebook that replicates the problem:
[MyBuggyRelStyle](https://github.com/beardwolf/beardwolf/blob/master/MyBuggyRelStyle.ipynb)

**Other info / logs** Include any logs or source code that would be helpful to
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-55-39aabbcfc7eb> in <module>
     20         z = np.random.normal(scale=.25, size=(batch_size, dl_size))
     21         z2 = np.random.normal(scale=.25, size=(batch_size, dl_size))
---> 22         disc_loss.append(disc_train.train_on_batch([data, z, z2], dummy_y))
     23 
     24         gen.trainable = True

~\Anaconda3\envs\deep-learning-gpu\lib\site-packages\tensorflow_core\python\keras\engine\training.py in train_on_batch(self, x, y, sample_weight, class_weight, reset_metrics)
   1076           self, x, y=y, sample_weight=sample_weight,
   1077           class_weight=class_weight, reset_metrics=reset_metrics,
-> 1078           standalone=True)
   1079       outputs = (outputs['total_loss'] + outputs['output_losses'] +
   1080                  outputs['metrics'])

~\Anaconda3\envs\deep-learning-gpu\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py in train_on_batch(model, x, y, sample_weight, class_weight, reset_metrics, standalone)
    431       y,
    432       sample_weights=sample_weights,
--> 433       output_loss_metrics=model._output_loss_metrics)
    434 
    435   if reset_metrics:

~\Anaconda3\envs\deep-learning-gpu\lib\site-packages\tensorflow_core\python\eager\def_function.py in __call__(self, *args, **kwds)
    566         xla_context.Exit()
    567     else:
--> 568       result = self._call(*args, **kwds)
    569 
    570     if tracing_count == self._get_tracing_count():

~\Anaconda3\envs\deep-learning-gpu\lib\site-packages\tensorflow_core\python\eager\def_function.py in _call(self, *args, **kwds)
    604       # In this case we have not created variables on the first call. So we can
    605       # run the first trace but we should fail if variables are created.
--> 606       results = self._stateful_fn(*args, **kwds)
    607       if self._created_variables:
    608         raise ValueError("Creating variables on a non-first call to a function"

~\Anaconda3\envs\deep-learning-gpu\lib\site-packages\tensorflow_core\python\eager\function.py in __call__(self, *args, **kwargs)
   2360     """Calls a graph function specialized to the inputs."""
   2361     with self._lock:
-> 2362       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
   2363     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2364 

~\Anaconda3\envs\deep-learning-gpu\lib\site-packages\tensorflow_core\python\eager\function.py in _maybe_define_function(self, args, kwargs)
   2698           and self.input_signature is None
   2699           and call_context_key in self._function_cache.missed):
-> 2700         return self._define_function_with_shape_relaxation(args, kwargs)
   2701 
   2702       self._function_cache.missed.add(call_context_key)

~\Anaconda3\envs\deep-learning-gpu\lib\site-packages\tensorflow_core\python\eager\function.py in _define_function_with_shape_relaxation(self, args, kwargs)
   2630         relaxed_arg_shapes)
   2631     graph_function = self._create_graph_function(
-> 2632         args, kwargs, override_flat_arg_shapes=relaxed_arg_shapes)
   2633     self._function_cache.arg_relaxed[rank_only_cache_key] = graph_function
   2634 

~\Anaconda3\envs\deep-learning-gpu\lib\site-packages\tensorflow_core\python\eager\function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   2591             arg_names=arg_names,
   2592             override_flat_arg_shapes=override_flat_arg_shapes,
-> 2593             capture_by_value=self._capture_by_value),
   2594         self._function_attributes,
   2595         # Tell the ConcreteFunction to clean up its graph once it goes out of

~\Anaconda3\envs\deep-learning-gpu\lib\site-packages\tensorflow_core\python\framework\func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    976                                           converted_func)
    977 
--> 978       func_outputs = python_func(*func_args, **func_kwargs)
    979 
    980       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

~\Anaconda3\envs\deep-learning-gpu\lib\site-packages\tensorflow_core\python\eager\def_function.py in wrapped_fn(*args, **kwds)
    437         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    438         # the function a weak reference to itself to avoid a reference cycle.
--> 439         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    440     weak_wrapped_fn = weakref.ref(wrapped_fn)
    441 

~\Anaconda3\envs\deep-learning-gpu\lib\site-packages\tensorflow_core\python\framework\func_graph.py in wrapper(*args, **kwargs)
    966           except Exception as e:  # pylint:disable=broad-except
    967             if hasattr(e, "ag_error_metadata"):
--> 968               raise e.ag_error_metadata.to_exception(e)
    969             else:
    970               raise

ValueError: in converted code:

    C:\Users\Hudson\Anaconda3\envs\deep-learning-gpu\lib\site-packages\tensorflow_core\python\keras\engine\training_eager.py:305 train_on_batch  *
        outs, total_loss, output_losses, masks = (
    C:\Users\Hudson\Anaconda3\envs\deep-learning-gpu\lib\site-packages\tensorflow_core\python\keras\engine\training_eager.py:273 _process_single_batch
        model.optimizer.apply_gradients(zip(grads, trainable_weights))
    C:\Users\Hudson\Anaconda3\envs\deep-learning-gpu\lib\site-packages\tensorflow_core\python\keras\optimizer_v2\optimizer_v2.py:426 apply_gradients
        grads_and_vars = _filter_grads(grads_and_vars)
    C:\Users\Hudson\Anaconda3\envs\deep-learning-gpu\lib\site-packages\tensorflow_core\python\keras\optimizer_v2\optimizer_v2.py:1039 _filter_grads
        ([v.name for _, v in grads_and_vars],))

    ValueError: No gradients provided for any variable: ['dense_26/kernel:0', 'dense_26/bias:0'].
0
1
Python 3 | Idle
MyBuggyRelStyle.ipynb
Ln 22, Col 1
`

**Comment by ravikyram** [comment]
@beardwolf 

Will it be possible to share the sample data , it helps us to reproduce the issue in our environment.Thanks!

**Comment by beardwolf** [comment]
Sure. I've uploaded some data to my repository. In the script just change the directory variable to the directory where you put the data. Sorry about the double zip extension in the filename. I'm new to GitHub. It's a normal zip file, not double zipped. Thanks!

[data.zip.zip](https://github.com/tensorflow/tensorflow/files/4307523/data.zip.zip)

**Comment by ravikyram** [comment]
@beardwolf 

I have tried on cloab with TF version 2.1.0 . Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/b2393f340fec1b5344e2f99bfb238ca9/untitled727.ipynb). Is this the expected behavior. Thanks!

**Comment by beardwolf** [comment]
Sorry, but no. The gist has an OpenCV error thrown from the data generator that I didn't get when I ran it on my computer. The error I got was thrown from train_on_batch.

**Comment by gowthamkpr** [comment]
@beardwolf this is an user generated error, not a bug. Please post this question in stackoverflow as there is a wider community to respond. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 3 weeks. Please add additional comments for us to open this issue again. Thanks!
