### ISSUE TITLE
How to gray images in Android?

### ISSUE THREAD

**Issue by yeyupiaoling** [tensorflow/tensorflow#37418]
I want to identify the MNIST image on an Android device. How do I modify the following preprocessing code. How to grayscale the image

https://github.com/tensorflow/examples/blob/f812d2c36469823c8784e387f690f43ad9d17683/lite/examples/image_classification/android/app/src/main/java/org/tensorflow/lite/examples/classification/tflite/Classifier.java#L307
```java
    ImageProcessor imageProcessor =
        new ImageProcessor.Builder()
            .add(new ResizeWithCropOrPadOp(cropSize, cropSize))
            .add(new ResizeOp(imageSizeX, imageSizeY, ResizeMethod.NEAREST_NEIGHBOR))
            .add(new Rot90Op(numRoration))
            .add(getPreprocessNormalizeOp())
            .build();
    return imageProcessor.process(inputImageBuffer);
```

**Comment by lu-wang-g** [comment]
You'll first need a model that can recognize a grayscale image. The image classification example app provided by tflite takes a RGB image instead. 

If you do have a custom model that can recognize grayscale images, you then need to convert the image into ByteBuffer with proper preprocessing, such as resizing and cropping, and then pass it into tflite.interpreter. Unfortunately, TFLite Support library does not support gray scale at this moment.

**Comment by shreyassks** [comment]
> You'll first need a model that can recognize a grayscale image. The image classification example app provided by tflite takes a RGB image instead.
> 
> If you do have a custom model that can recognize grayscale images, you then need to convert the image into ByteBuffer with proper preprocessing, such as resizing and cropping, and then pass it into tflite.interpreter. Unfortunately, TFLite Support library does not support gray scale at this moment.

Does TFLite support library include the RGB to Gray scale conversion in TF-Fall 2020 update??

**Comment by lu-wang-g** [comment]
TFLite Support Library doesn't supporting the conversion from RGB to Grayscale. however, there are many related StackOverflow questions that you can refer to, such as [this one](https://stackoverflow.com/questions/8381514/android-converting-color-image-to-grayscale)

**Comment by MaxSchunck** [comment]
> TFLite Support Library doesn't supporting the conversion from RGB to Grayscale. however, there are many related StackOverflow questions that you can refer to, such as [this one](https://stackoverflow.com/questions/8381514/android-converting-color-image-to-grayscale)

A model which requests a grayscale image as input, requires only one channel/feature per pixel. These methods unfortunately all keep the rgb channels.

**Comment by Alfyu07** [comment]
sorry for asking, does tensorflow support library already support conversion from rgb to grayscale now?

**Comment by lu-wang-g** [comment]
@Alfyu07 Yes, please see my answer [here](https://github.com/tensorflow/tensorflow/issues/35211#issuecomment-871618298).
