### ISSUE TITLE
tf.Graph.get_tensor_by_name does not work as expected in TF2

### ISSUE THREAD

**Issue by stephenhermes** [tensorflow/tensorflow#37428]
**System information** 
- Have I written custom code: yes
- OS Platform and Distribution: Max OSX 10.15.3 (Catalina) 
- Mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: v2.1.0-rc2-17-ge5bf8de410 2.1.0
- Python version: 3.7.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):  N/A
- CUDA/cuDNN version: - GPU model and memory: N/A

**Describe the current behavior**
`tf.Graph.get_tensor_by_name` returns 'resource' dtype tensors, which do not evaluate as expected in a session. For example, the code below will return something like:

```
array([( 10,), ( 44,), ( 47,), (106,), (111,), ( 98,), ( 58,), (108,),
       (111,), ( 99,), ( 97,), (108,), (104,), (111,), (115,), (116,),
       ( 47,), (114,), (101,), (112,), (108,), (105,), ( 99,), ( 97,),
       ( 58,), ( 48,), ( 47,), (116,), ( 97,), (115,), (107,), ( 58,),
       ( 48,), ( 47,), (100,), (101,), (118,), (105,), ( 99,), (101,),
       ( 58,), ( 67,), ( 80,), ( 85,), ( 58,), ( 48,), ( 18,), (  9,),
       (108,), (111,), ( 99,), ( 97,), (108,), (104,), (111,), (115,),
       (116,), ( 26,), (  1,), (120,), ( 32,), (224,), (167,), (192,),
       (135,), ( 18,), ( 42,), ( 18,), ( 78,), ( 49,), ( 48,), (116,),
       (101,), (110,), (115,), (111,), (114,), (102,), (108,), (111,),
       (119,), ( 51,), ( 86,), ( 97,), (114,), ( 69,), ( 50,), (  4,),
       (  8,), (  3,), ( 18,), (  0,)], dtype=[('resource', 'u1')])
```

**Describe the expected behavior**
Expect v1 compatible code to work as it does in TF1.X. In particular, the code below should return `3`.

**Standalone code to reproduce the issue** 
```python
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
x = tf.Variable(3, name='x')
y = tf.get_default_graph().get_tensor_by_name('x:0')
with tf.Session() as sess:
  sess.run(y)
```

**Other info / logs** 
- When instantiating a `tf.Variable`:
 ```
WARNING:tensorflow:From /Users/shermes/Projects/tensorflow/venv2/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1635: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
```
- From `sess.run` block: 
```
/Users/shermes/Projects/tensorflow/venv2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py:1445: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
```
(This error shows up when using numpy 1.16 as well as 1.17 and 1.18.)

**Comment by gadagashwini** [comment]
@stephenhermes, I tried replicating the issue but getting different error .
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/eda9478397bd2186c904344a8f9b93e1/untitled430.ipynb?authuser=2) and provide more information to replicating the reported issue. Thanks!

**Comment by stephenhermes** [comment]
The issue reported is with TensorFlow version 2.1.0 (not 1.15.0).

**Comment by gadagashwini** [comment]
@stephenhermes, The code is compatible to Tf 1.x version. Please confirm.
Thanks

**Comment by stephenhermes** [comment]
The code requires `tf.global_variables_initializer()` to run in TF 1.15; including it does not fix the issue in TF2.1:

```python
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
x = tf.Variable(3, name='x')
y = tf.get_default_graph().get_tensor_by_name('x:0')
init = tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init)
  sess.run(y)
```

**Comment by gadagashwini** [comment]
I could replicate the issue with Tf 2.1.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/ebc5400e9789fdc4a185ab4ac88eeeaf/untitled439.ipynb). Thanks!

**Comment by gowthamkpr** [comment]
@stephenhermes Correct me if I am wrong but I don't see any difference in 1.x and 2.x please find my gist [here](https://colab.research.google.com/gist/gowthamkpr/c6cc5083b4021931ba8d18ae68929aef/untitled3.ipynb?authuser=2)

**Comment by stephenhermes** [comment]
@gowthamkpr the issue is between 1.x and  tf.compat.v1 in 2.x. Please find the gist [here](https://colab.research.google.com/gist/stephenhermes/d609c5fd43246d4cff5c0b3246f83dff/untitled3.ipynb?authuser=2).

**Comment by gowthamkpr** [comment]
@stephenhermes I get it now. Thanks. I do see the difference between 1.x and tf.compat.v1 in 2.x.

**Comment by donglinjy** [comment]
Is there any work around of this issue, like instead of get_tensor_by_name to return 'resource' dtype tensors, any other ways to get the same dtype tensors as tf1?

**Comment by qipengh** [comment]
Is there any solution? the same issue when I run freeze_graph.py convert ckpt to pb with TF 2.1

**Comment by rwolst** [comment]
I would also like a solution for this as am getting the same error.

**Comment by pks** [comment]
Try
```
tf.compat.v1.disable_v2_behavior()
tf.compat.v1.disable_eager_execution()
```

**Comment by qipengh** [comment]
but I try, and error as follow:
file".../tensorflow_core/python/ops/variables.py",line 1663, in __init__

   self.distribute_strategy = distribute_strategy


NameError:global name 'distribute_strategy' is not defined


How can i solve this question? thank you 










在 2020-05-18 23:56:23，"pks" <notifications@github.com> 写道：

Try

tf.compat.v1.disable_v2_behavior()
tf.compat.v1.disable_eager_execution()

**Comment by zhjunqin** [comment]
You can refer to https://stackoverflow.com/questions/35678883/tensorflow-getting-variable-by-name

```
var = [v for v in tf.global_variables() if v.name == "xxx_name"][0]
sess.run(var)
```

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210524, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/ba9357303fec1748876ad6d45069da26/untitled7.ipynb). Thanks!

**Comment by Saduf2019** [comment]
The issue is [reproducible](https://colab.research.google.com/gist/Saduf2019/fee018f83d3d4fce82b44612972f55d7/untitled638.ipynb) in tf nightly 2.7 as well.

**Comment by YouSenRong** [comment]
Have you solve this problem? I also meet this problem on tensorflow 2.8.2.

**Comment by YouSenRong** [comment]
I try on Tensorflow 2.8.2 with the code follows, and can get the correct return 3.

```python
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
x = tf.Variable(3, name='x')
y = tf.get_default_graph().get_tensor_by_name('x:0')
init = tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init)
  print(sess.run(y))
```

**Comment by sushreebarsa** [comment]
@stephenhermes Could you please refer to the [gist](https://colab.research.google.com/gist/sushreebarsa/1f911b0b5817f3f082f7f59036a551e1/37428.ipynb) of TF v2.11 and let us know if it helps?
Thank you!
