### ISSUE TITLE
Add logging to intermediate layers in TFLite

### ISSUE THREAD

**Issue by chiraag** [tensorflow/tensorflow#37427]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.15
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Currently tflite reuses memory for intermediate to limit its memory footprint on resource constrained devices as discussed [here](https://stackoverflow.com/questions/56885007/visualize-tflite-graph-and-get-intermediate-values-of-a-particular-node). This makes it hard to debug to what is happening at the intermediate layers on the final hardware (especially when using a delegate). The proposal is to add logging functionality to enable visibility into these intermediate layers.

**Will this change the current api? How?**
A candidate proposal is to add an api function to mark all/selected operation outputs as model outputs and then allow them to be inspected in the python interpreter.

**Who will benefit with this feature?**
Any developer trying to debug what is happening on an embedded tflite implementation

**Any Other info.**

**Comment by jdduke** [comment]
@suharshs didn't we add this functionality recently?

**Comment by suharshs** [comment]
No not yet. There is a pending change to enable this.

**Comment by chiraag** [comment]
Is there WIP in progress branch that I can look at? Also is the approach/API similar to what I described? If this is coming out soon then I can just wait if not I can help contribute this change.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
