### ISSUE TITLE
NotFoundError: No registered 'Identity' OpKernel for 'TPU' devices compatible with node

### ISSUE THREAD

**Issue by crmh** [tensorflow/tensorflow#37426]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Google Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): 
- TensorFlow version (use command below): 2.1.0
- Python version: - Bazel
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Throws error "No registered 'Identity' OpKernel for 'TPU' devices compatible with node".
Script uses efficientnet.tfkeras from efficientnet python package 1.1.0 (pip install efficientnet).

**Describe the expected behavior**
Script should start training on TPU.

**Standalone code to reproduce the issue** 
Google Colab:
https://drive.google.com/open?id=1QALjqGEX4z5vTBjRBUbyn5WmElYzMJzR

Public access to GCS bucket is granted.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
efficientnet-b0 (Model)      (None, 1280)              4049564   
_________________________________________________________________
dense (Dense)                (None, 120)               153720    
_________________________________________________________________
dense_1 (Dense)              (None, 120)               14520     
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 242       
=================================================================
Total params: 4,218,046
Trainable params: 4,176,030
Non-trainable params: 42,016
_________________________________________________________________
WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of samples seen.
WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of samples seen.
[INFO] Modelul este salvat pe disc dupa fiecare epoca in formatul: nume_model_weights-epoca-training_set_accuracy-validation_set_accuracy.hdf5
Train for 17.0 steps, validate for 4.0 steps
Epoch 1/25
 0/17 [..............................] - ETA: 0s
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-1-35a575cce5e2> in <module>()
    165     validation_data=valdataset,
    166     validation_steps=np.ceil(totalVal / BS),
--> 167     epochs=NUM_EPOCHS,
    168     #callbacks=[checkpointer],
    169 )

13 frames
/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

NotFoundError: No registered 'Identity' OpKernel for 'TPU' devices compatible with node {{node Identity}}
	 (OpKernel was found, but attributes didn't match) Requested Attributes: T=DT_UINT8
	.  Registered:  device='XLA_GPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, ..., DT_HALF, DT_UINT32, DT_UINT64, DT_RESOURCE, DT_VARIANT]
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, ..., DT_HALF, DT_UINT32, DT_UINT64, DT_RESOURCE, DT_VARIANT]
  device='XLA_TPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_COMPLEX64, DT_INT64, DT_BOOL, DT_BFLOAT16, DT_UINT32, DT_UINT64, DT_RESOURCE, DT_VARIANT]
  device='XLA_CPU'; T in [DT_UINT8, DT_QUINT8, DT_UINT16, DT_INT8, DT_QINT8, ..., DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128, DT_BOOL, DT_BFLOAT16]
  device='TPU'; T in [DT_INT32, DT_UINT32, DT_BFLOAT16, DT_FLOAT, DT_DOUBLE, DT_BOOL, DT_COMPLEX64, DT_INT64, DT_UINT64]
  device='TPU_SYSTEM'
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_BFLOAT16]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_UINT16]
  device='GPU'; T in [DT_INT16]
  device='GPU'; T in [DT_UINT8]
  device='GPU'; T in [DT_INT8]
  device='GPU'; T in [DT_COMPLEX64]
  device='GPU'; T in [DT_COMPLEX128]
  device='GPU'; T in [DT_VARIANT]
  device='DEFAULT'; T in [DT_STRING]
  device='DEFAULT'; T in [DT_VARIANT]
  device='DEFAULT'; T in [DT_RESOURCE]
  device='CPU'

	 [[Identity]] [Op:MakeIterator]

**Comment by Saduf2019** [comment]
I am able to replicate the issue, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/c31e0255179d513782e50bbf20609726/37426.ipynb).

**Comment by lamba92** [comment]
Having same issue [here](https://drive.google.com/open?id=1LCeeTcdJuXGXoddfSPAQAqDgigSdqQTl), although the model seems to work when using the GPU. I believe it may be related to the override of the Keras ImageGenerator but I have not enough knowledge to be sure.

**Comment by acmilannesta** [comment]
I have the same issue here. For training in TPU, do we have to use the tfrecord or we could use our customized data generator?

**Comment by jhseu** [comment]
The error message indicates you're using uint8, which isn't supported on TPU. You can cast to uint32.

**Comment by lamba92** [comment]
> The error message indicates you're using uint8, which isn't supported on TPU. You can cast to uint32.

Could you show how to do that when using a `kera.utils.Sequence`? Should you override it with a class?

**Comment by crmh** [comment]
Jhseu, for me it is working now, per your suggestion.

I am converting the uint8 image resulted from tf.io.decode_jpeg to float32 using:
`image = tf.image.decode_jpeg("image.jpg", channels=3)`
`image = tf.cast(image, tf.float32)`

If I want to also cast all values between 0 and 1 I use: 
`image = tf.cast(image, tf.float32)/255.0    # convert image to floats in [0, 1] range`

Also, I found using TFRecords to be very important, using just tf.data.Dataset is impossibly slow.

Thank you. I will close the issue.

**Comment by prudhvirajboddu** [comment]
> I have the same issue here. For training in TPU, do we have to use the tfrecord or we could use our customized data generator?

We can use both data but the data should be in cloud storage for tpu training . Also for visualizing the logs to Tensorboard we should train the model only in Cloud TPU . I tried to run the model running in  Colab TPU having the storage bucket but it won't work like that .
