### ISSUE TITLE
Wrong Error Massage, when passing wrong datatype to tf.TensorArray

### ISSUE THREAD

**Issue by bela127** [tensorflow/tensorflow#37429]
Hi, 
I hope i picked the right issue type, not sure if documentation or implementation was the right category

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): No
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Linux Mint 19.3 (ubuntu)
- TensorFlow installed from (source or
binary): binatry
- TensorFlow version (use command below): both tf-nightly and tf-2.1
- Python version: 3.8 and 3.6

**Describe the current behavior**
tf.TensorArray(dtype=tf.float32, size=tf.cast(5, dtype = tf.float32), dynamic_size=False)

Error: Unreachable

**Describe the expected behavior**
Error: Expected dtype int32 not dtype float32 for size argument

**Standalone code to reproduce the issue** 
'''
tf.TensorArray(dtype=tf.float32, size=tf.cast(5, dtype = tf.float32), dynamic_size=False)
'''

**Comment by amahendrakar** [comment]
@bela127,
I tried running the above code with TF 2.1 and TF-nightly and got the error `TypeError: 'numpy.float32' object cannot be interpreted as an integer`. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/d041d143a9d6c97d6ed2024bf7c3b0cd/37429.ipynb). Thanks!

**Comment by bela127** [comment]
interesting...
i just checked again and now its working with:
tf.TensorArray(dtype=tf.float32, size=tf.cast(5, dtype = tf.float32), dynamic_size=False)
i try to reproduce the original bug and create test code...

**Comment by bela127** [comment]
Cant reproduce it, and already changed the code that original produced the error, so i have no way to find it again.

Closing for now...

i will reopen the issue if im successful
