### ISSUE TITLE
Encountered unresolved custom op: BatchMatMulV2.

### ISSUE THREAD

**Issue by GyanendroKh** [tensorflow/tensorflow#37432]
**System information**
- OS Platform and Distribution (Pop!_OS 19.10):
- TensorFlow installed from (source or binary):python3 -m pip install
- TensorFlow version - 2.2.0-dev20200308
- TensorFlowLite version [0.0.0-nightly](https://bintray.com/google/tensorflow/tensorflow-lite/0.0.0-nightly#)

I was trying to convert a Transformer model to TfLite. It converted successfully with Python using the `converter.experimental_new_converter = True` and `converter.allow_custom_ops = True` but can't run it on android.

**Provide the text output from tflite_convert**

```
java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: Encountered unresolved custom op: BatchMatMulV2.
2020-03-09 12:09:21.727 6025-6025/com.meiteimayek.transformertest W/System.err: Node number 31 (BatchMatMulV2) failed to prepare.
2020-03-09 12:09:21.727 6025-6025/com.meiteimayek.transformertest W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
2020-03-09 12:09:21.727 6025-6025/com.meiteimayek.transformertest W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:152)
2020-03-09 12:09:21.727 6025-6025/com.meiteimayek.transformertest W/System.err:     at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:296)
```

**Standalone code to reproduce the issue** 
```java

import android.app.Activity;
import android.content.res.AssetFileDescriptor;
import android.util.ArrayMap;
import android.util.Log;

import org.tensorflow.lite.Interpreter;

import java.io.FileInputStream;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.MappedByteBuffer;
import java.nio.channels.FileChannel;
import java.util.Arrays;
import java.util.Map;

public class Model {
  
  private Interpreter mInterpreter;
  
  public Model(Activity activity) throws IOException {
    float[] inp = {4, 25,  7, 25, 14, 15, 18, 20,  7,  5,  0,  0,  0,  0,  0,  0,  0,
      0,  0,  0,  0,  0,  0,  0};
    
    String name = "model.tflite";
    ByteBuffer input = ByteBuffer.allocate(4 * 24);
    ByteBuffer oInput = ByteBuffer.allocate(4 * 23);
    
    input.order(ByteOrder.nativeOrder());
    oInput.order(ByteOrder.nativeOrder());
    
  
    for(float v : inp) {
      input.putFloat(v);
    }
    float[] predicted = new float[1];
    
    oInput.putFloat(1);
    for(int i = 1; i < 23; i++) {
      oInput.putFloat(0);
    }
    Interpreter.Options op = new Interpreter.Options();
    
    mInterpreter = new Interpreter(getModel(activity, name), op);

    Map<Integer, Object> result = new ArrayMap<>();
    result.put(0, predicted);
    mInterpreter.runForMultipleInputsOutputs(new ByteBuffer[]{input, oInput}, result);
    Log.d("TAG", "Model: Output " + Arrays.toString((float[])result.get(0)));
  }
  
  private MappedByteBuffer getModel(Activity activity, String name) throws IOException {
    AssetFileDescriptor f = activity.getAssets().openFd(name);
    return new FileInputStream(f.getFileDescriptor())
      .getChannel()
      .map(FileChannel.MapMode.READ_ONLY, f.getStartOffset(), f.getDeclaredLength());
  }
}

```

TFlite Model Link - https://drive.google.com/open?id=1URF3USAEkOFaKCCOB7ctl_b2FxTVDWPx

**Comment by jdduke** [comment]
We plan on adding support for BatchMatMul in the TF 2.3 release.

**Comment by GyanendroKh** [comment]
So, when can we expect TF 2.3 release.

**Comment by jdduke** [comment]
> So, when can we expect TF 2.3 release.

Mid Q2. We'll post here when it's available in the nightly builds.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Comment by sushreebarsa** [comment]
@GyanendroKh Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!

**Comment by miaout17** [comment]
I believe we supported BatchMatMul in TensorFlow Lite natively long time ago. 
This should be already resolved closing.
