### ISSUE TITLE
TypeError: '_UserObject' object is not callable,  why tf.saved_model.load() failed?

### ISSUE THREAD

**Issue by xiaoyangnihao** [tensorflow/tensorflow#37439]
**System information** 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 2.1.0
- Python version: 3.7.4

**Describe the current behavior**
```
Traceback (most recent call last):
  File "C:/Pyfile/tensorflow2.X/load_model.py", line 12, in <module>
    print(model(tf.random.normal((1, 3))))
TypeError: '_UserObject' object is not callable
```
**Describe the expected behavior**

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```
import os
import tensorflow as tf

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

class Model(tf.keras.Model):
    def __init__(self):
        super(Model, self).__init__()
        self.d = tf.keras.layers.Dense(2)

    def call(self, x, training=True, mask=None):
        return self.d(x)

model = Model()

# high-level api
# model.predict(tf.random.normal((2, 3)))
# model.save("save/high", save_format="tf")

# low-level api
tf.saved_model.save(model, 'save/low')

---------------------------------------------

import os
import tensorflow as tf

# high-level api
# model = tf.keras.models.load_model('save/high')

# low-level api
model = tf.saved_model.load('save/low')

print(model(tf.random.normal((1, 3))))   #  error!!!
```
If I user the high-level api to save and load, it runs successfully. If I use tf.saved_mode.save()，it can save successfully with warning
'''
WARNING:tensorflow:Skipping full serialization of Keras model <__main__.Model object at 0x0000028C0515F6D8>, because its inputs are not defined.
2020-03-09 18:20:37.304479: W tensorflow/python/util/util.cc:319] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
WARNING:tensorflow:Skipping full serialization of Keras layer <tensorflow.python.keras.layers.core.Dense object at 0x0000028C1CB87CC0>, because it is not built.
''' 
then load failed, So what does  '_UserObject' object is not callable mean?  How can I fix this, thanks for any help

**Comment by amahendrakar** [comment]
@xiaoyangnihao,
On running the above code, I got an error stating `NameError: name 'model' is not defined`. Please find the gist of it [here](https://colab.sandbox.google.com/gist/amahendrakar/0e172b1fa3c2202b97ea6978ec78a304/37439.ipynb).

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by xiaoyangnihao** [comment]
> @xiaoyangnihao,
> On running the above code, I got an error stating `NameError: name 'model' is not defined`. Please find the gist of it [here](https://colab.sandbox.google.com/gist/amahendrakar/0e172b1fa3c2202b97ea6978ec78a304/37439.ipynb).
> 
> In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

Sorry for missing some codes. I update the description above, so you can reproduce the issue, thanks

**Comment by SmileTM** [comment]
The tensorflow2.0 use dynamic graphs. 
the model can auto infer the input shape by your input. 
But in your "low-level api" code, the Dense layer has not been inputed, so it can't auto infer the shape of input to build model. So, you need input some data like  your ''high-level api" code, then save model.

I suggest you  follow the code behind like keras, to let the model know the  shape of your inputs.
```
import os
import tensorflow as tf

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

class Model(tf.keras.Model):
    def __init__(self):
        super(Model, self).__init__()
        self.d = tf.keras.layers.Dense(2)

    def call(self, x, training=True, mask=None):
        return self.d(x)


mymodel = Model()
input = tf.keras.layers.Input(shape=(3,))
out = mymodel(input)
model=tf.keras.models.Model(inputs=input, outputs=out)
```

**Comment by xiaoyangnihao** [comment]
> The tensorflow2.0 use dynamic graphs.
> the model can auto infer the input shape by your input.
> But in your "low-level api" code, the Dense layer has not been inputed, so it can't auto infer the shape of input to build model. So, you need input some data like your ''high-level api" code, then save model.
> 
> I suggest you follow the code behind like keras, to let the model know the shape of your inputs.
> 
> ```
> import os
> import tensorflow as tf
> 
> os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
> 
> class Model(tf.keras.Model):
>     def __init__(self):
>         super(Model, self).__init__()
>         self.d = tf.keras.layers.Dense(2)
> 
>     def call(self, x, training=True, mask=None):
>         return self.d(x)
> 
> 
> mymodel = Model()
> input = tf.keras.layers.Input(shape=(3,))
> out = mymodel(input)
> model=tf.keras.models.Model(inputs=input, outputs=out)
> ```

Yeah, this does work. 
But In my real project, I use tf.saved_model.save() to save the model in checkpoint_interval, I think **after running serveral bath_sizes, the input_shape should be configured**, but when I use tf.saved_model.load() to load the model and call the input, TypeError: '_UserObject' object is not callable arises. I wonder why ?

**Comment by SmileTM** [comment]
```
import os
import tensorflow as tf

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

class Model(tf.keras.Model):
    def __init__(self):
        super(Model, self).__init__()
        self.d = tf.keras.layers.Dense(1)

    def call(self, x, training=True, mask=None):
        return self.d(x)

model = Model()

optimizer = tf.keras.optimizers.SGD()
with tf.GradientTape() as tape:
    out = model(tf.random.normal((2, 3)))
    grads = tape.gradient(out, model.trainable_weights)
    optimizer.apply_gradients(zip(grads,model.trainable_weights))

tf.saved_model.save(model, 'save/low')

model_load= tf.saved_model.load('save/low')
print(model_load(tf.random.normal((2, 3))))

```
yeah, in this way ,it really have  TypeError: '_UserObject' object is not callable arises. 

According my understand , a keras model need input_layer.  If you have not input_layer, you  saved model that is not really model .it is just a layer .

I also want to know how you  explain this issue.  @amahendrakar

**Comment by xiaoyangnihao** [comment]
@amahendrakar any suggestions?

**Comment by SmileTM** [comment]
# build model
```
import os
import tensorflow as tf

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'


class Model(tf.keras.Model):
    def __init__(self, **kwargs):
        super(Model, self).__init__(**kwargs)
        self.d = tf.keras.layers.Dense(1, kernel_initializer=tf.keras.initializers.ones())

    def call(self, x, training=True, mask=None):
        return self.d(x)

model = Model()
optimizer = tf.keras.optimizers.SGD()
with tf.GradientTape() as tape:
    out = model(tf.ones((2, 3)))
    grads = tape.gradient(out, model.trainable_weights)
    optimizer.apply_gradients(zip(grads, model.trainable_weights))

print(model(tf.ones((2, 3))))
```
# save and load model
## Approach 1
https://www.tensorflow.org/guide/keras/save_and_serialize#approach_1

```
model.save_weights('save/')
model_load = Model()
model_load.load_weights('save/')
print(model_load(tf.ones((2, 3))))
```
**It works well**.


## Approach2
https://www.tensorflow.org/guide/keras/save_and_serialize#approach_2

```
model.save('save')
model_load = tf.keras.models.load_model('save/')
print(model_load(tf.ones((2, 3))))
```
**ValueError**: Model <__main__.Model object at 0x4441057d0> cannot be saved because the input shapes have not been set. Usually, input shapes are automatically determined from calling .fit() or .predict(). To manually set the shapes, call ### model._set_inputs(inputs).

## Approach3
https://www.tensorflow.org/guide/keras/save_and_serialize#approach_3
```
tf.saved_model.save(model,'save')
model_load = tf.keras.models.load_model('save')
print(model_load(tf.ones((2, 3))))
```
**AttributeError**: '_UserObject' object has no attribute 'call_and_return_conditional_losses'


In the eager mode, just **Approach 1** `save_weights` can work well.  But if model is trained  by using model.fit(), These methods all work well .
I think this might be  a bug.  But if not，I think these methods of saving and loading models should be distinguished in the docs.  @amahendrakar

**Comment by xiaoyangnihao** [comment]
> # build model
> ```
> import os
> import tensorflow as tf
> 
> os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
> 
> 
> class Model(tf.keras.Model):
>     def __init__(self, **kwargs):
>         super(Model, self).__init__(**kwargs)
>         self.d = tf.keras.layers.Dense(1, kernel_initializer=tf.keras.initializers.ones())
> 
>     def call(self, x, training=True, mask=None):
>         return self.d(x)
> 
> model = Model()
> optimizer = tf.keras.optimizers.SGD()
> with tf.GradientTape() as tape:
>     out = model(tf.ones((2, 3)))
>     grads = tape.gradient(out, model.trainable_weights)
>     optimizer.apply_gradients(zip(grads, model.trainable_weights))
> 
> print(model(tf.ones((2, 3))))
> ```
> 
> # save and load model
> ## Approach 1
> https://www.tensorflow.org/guide/keras/save_and_serialize#approach_1
> 
> ```
> model.save_weights('save/')
> model_load = Model()
> model_load.load_weights('save/')
> print(model_load(tf.ones((2, 3))))
> ```
> 
> **It works well**.
> 
> ## Approach2
> https://www.tensorflow.org/guide/keras/save_and_serialize#approach_2
> 
> ```
> model.save('save')
> model_load = tf.keras.models.load_model('save/')
> print(model_load(tf.ones((2, 3))))
> ```
> 
> **ValueError**: Model <**main**.Model object at 0x4441057d0> cannot be saved because the input shapes have not been set. Usually, input shapes are automatically determined from calling .fit() or .predict(). To manually set the shapes, call ### model._set_inputs(inputs).
> 
> ## Approach3
> https://www.tensorflow.org/guide/keras/save_and_serialize#approach_3
> 
> ```
> tf.saved_model.save(model,'save')
> model_load = tf.keras.models.load_model('save')
> print(model_load(tf.ones((2, 3))))
> ```
> 
> **AttributeError**: '_UserObject' object has no attribute 'call_and_return_conditional_losses'
> 
> In the eager mode, just **Approach 1** `save_weights` can work well. But if model is trained by using model.fit(), These methods all work well .
> I think this might be a bug. But if not，I think these methods of saving and loading models should be distinguished in the docs. @amahendrakar

@SmileTM  The following method will be OK, 
```
import os
import tensorflow as tf

print(tf.__version__)
print(tf.executing_eagerly())

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'


class Model(tf.keras.Model):
    def __init__(self):
        super(Model, self).__init__()
        self.d = tf.keras.layers.Dense(64)

    def call(self, x, training=True, mask=None):
        return self.d(x)


@tf.function
def train(inputs, targets, model, optimizer, loss_fn):
    with tf.GradientTape() as tape:
        predicts = model(inputs)
        loss = loss_fn(targets, predicts)
    
    grads = tape.gradient(loss, model.trainable_weights)
    optimizer.apply_gradients(zip(grads, model.trainable_weights))


def inference(tests):
    model = tf.saved_model.load('save/demo-1')
    print(model(tests))


if __name__ == "__main__":
    model = Model()
    optimizer = tf.optimizers.Adam()
    loss_fn = tf.losses.MeanSquaredError()

    inputs = tf.random.normal((8, 10, 16))
    targets = tf.random.normal((8, 10, 1))

    train(inputs, targets, model, optimizer, loss_fn)
    tf.saved_model.save(model, 'save/demo-1')

    tests = tf.random.normal((1, 10, 16))
    inference(tests)

```

**Comment by jjedele** [comment]
@xiaoyangnihao That's actually a rather easy fix which is more related to Python than to TF:

The method in `Model` must be named `__call__` rather than `call` for the model to be callable (i.e. you can do `model(x)`). As it is right now you would have to do `model.call(x)`.

Apparently this was wrong in the documentation at some point because we also had this problem in some places. It's correct now though.

**Comment by xiaoyangnihao** [comment]
> @xiaoyangnihao That's actually a rather easy fix which is more related to Python than to TF:
> 
> The method in `Model` must be named `__call__` rather than `call` for the model to be callable (i.e. you can do `model(x)`). As it is right now you would have to do `model.call(x)`.
> 
> Apparently this was wrong in the documentation at some point because we also had this problem in some places. It's correct now though.

@jjedele  My current version is tf2.1, does I need to update lasted version ?  Can you give some examples or codes about above questions? I don't think it is solved.

```
!pip uninstall tensorflow
!pip install tf-nightly

import os
import tensorflow as tf
print(tf.__version__)

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

class Model(tf.keras.Model):
    def __init__(self):
        super(Model, self).__init__()
        self.d = tf.keras.layers.Dense(2)

    def __call__(self, x, training=True, mask=None):
        return self.d(x)

model = Model()

# low-level api
tf.saved_model.save(model, 'save/low')

# low-level api
model = tf.saved_model.load('save/low')
print(model.call(tf.random.normal((1, 3))))   #  error!!!
```

```
2.2.0-dev20200312
WARNING:tensorflow:Skipping full serialization of Keras layer <__main__.Model object at 0x7f0cbc971080>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <tensorflow.python.keras.layers.core.Dense object at 0x7f0c1c8f6978>, because it is not built.
INFO:tensorflow:Assets written to: save/low/assets
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-451ee428c4e1> in <module>()
     30 model = tf.saved_model.load('save/low')
     31 
---> 32 print(model.call(tf.random.normal((1, 3))))   #  error!!!

AttributeError: '_UserObject' object has no attribute 'call'
```

**Comment by jjedele** [comment]
@xiaoyangnihao Sorry, I was squeezing too much information into my answer. Now you fixed the one part and broke the other 😄

Do the following:

```
class Model(tf.keras.Model):
    def __init__(self):
        super(Model, self).__init__()
        self.d = tf.keras.layers.Dense(2)

    def __call__(self, x, training=True, mask=None):
        return self.d(x)

...

model(tf.random.normal((1, 3))) # no explicit .call here
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue. Please find the Gist [here](https://colab.research.google.com/gist/amahendrakar/f89c323afb0b7e10e26a8f17a39c0508/37439.ipynb). Thanks!

**Comment by allenlavoie** [comment]
We intentionally don't deal with Keras types in tf.saved_model.save/tf.saved_model.load so the libraries are layered.

But @k-w-w has added SavedModel APIs which do save and restore Keras types: https://www.tensorflow.org/versions/r2.2/api_docs/python/tf/keras/Model#save (tf.keras.model.save(..., save_format='tf'))

**Comment by BePasquet** [comment]
if it helps i fix it by calling the model before saving (data here is tf.data.Dataset)
after you have trained it with model.fit

```
for xs, _ in data.take(1):
      model(xs)
tf.saved_model.save(model, model_path)
model = tf.saved_model.load(model_path)
```
[reference](https://discuss.tensorflow.org/t/saving-and-loading-recommenders-models/11134)
