### ISSUE TITLE
undefined reference error while building Lite for ESP32 "person_detection" example

### ISSUE THREAD

**Issue by Hazeline2018** [tensorflow/tensorflow#37431]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win7
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): Latest version
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): ESP32

**Describe the problem**
I git the whole latest tensorflow branch on my WIN7 PC. I intended to use "Tensorflow Lite for Micro". I wanted to try the included examples "Person Detection" first to make sure everything works out of box. So I followed the readme instruction by running "make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_person_detection_esp_project". According to the Makefile, five 3rd party downloads should be downloaded first. However, I got the MD5 mismatch error for each and every single one of them. So I had to 'hack' the Makefile to disable the MD5 checksum checking and manually downloaded those required 5 downloads and installed in the 'C:\Projects\tensorflow\tensorflow\lite\micro\tools\make\downloads' folder. 
Then the make seemed to run for a few minutes, the stopped at the following error:
[888/894] Building CXX object esp-idf/...core/api/flatbuffer_conversions.cc.obj
cc1plus.exe: warning: command line option '-std=c11' is valid for C/ObjC but not
 for C++
[893/894] Linking CXX executable person_detection.elf
FAILED: person_detection.elf
cmd.exe /C "cd . && C:\Users\Tianhao\.espressif\tools\xtensa-esp32-elf\esp-2019r
2-8.2.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-g++.exe  -mlongcalls -Wno-frame-ad
dress  -nostdlib @CMakeFiles\person_detection.elf.rsp  -o person_detection.elf
&& cd ."
c:/users/tianhao/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32
-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.e
xe: esp-idf/main/libmain.a(main_functions.cc.obj):(.literal.loop+0x14): undefine
d reference to `RespondToDetection(tflite::ErrorReporter*, unsigned char, unsign
ed char)'
c:/users/tianhao/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32
-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.e
xe: esp-idf/main/libmain.a(main_functions.cc.obj): in function `loop':
c:\projects\tensorflow\tensorflow\lite\micro\tools\make\gen\esp_xtensa-esp32\prj
\person_detection\esp-idf\build/../main/main_functions.cc:111: undefined referen
ce to `RespondToDetection(tflite::ErrorReporter*, unsigned char, unsigned char)'

collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

I also attached full log file for reference. Please show me how to fix this problem and get at least the example built and running. Thanks!

[build_log.txt](https://github.com/tensorflow/tensorflow/files/4304902/build_log.txt)

**Please provide the exact sequence of commands/steps when you ran into the problem**

**Comment by Saduf2019** [comment]
@Hazeline2018 
Could you please refer to existing old issues related to this topic.
please let us know if [this helps](https://github.com/tensorflow/tensorflow/issues/28105#issuecomment-490139562)

**Comment by Hazeline2018** [comment]
@Saduf2019 
thanks for your prompt response. However, I read through the post you suggested but did not see anywhere could help with my own issue. I'm trying to make for ESP32 mcu on WIN7 machine. But the link you suggested was for Android build. Please help pointing to the right direction. Thanks!

**Comment by Hazeline2018** [comment]
**Edit:** 
To correct my original problem description: the make step was successful after I ''hacked" the MD5 checksum and manually downloaded those 5 3rd party downloads. 

But this **'undefined reference to `RespondToDetection(tflite::ErrorReporter*, unsigned char, unsigned char)'** error came when I tried to build the example prj using "**idf.py build**" cmd.

Just as a reference, I also tried building 'hello_world' example with same procedure, that went successfully. So I guess there might be something missing in the 'person_detection' example.

Hope that clear things up. Thanks!

**Comment by Hazeline2018** [comment]
Can anyone please help with this problem? I'm stuck here for a couple of days and I've exhausted almost the whole build link but couldn't see any problem. This 'undefined reference' error seems to be missing a file which I couldn't figure out

Any suggestion or advise would be greatly appreciated!

**Comment by Hazeline2018** [comment]
Update: I've figured out. This can be closed.

**Comment by mhuang74** [comment]
Ran into same problem. Turned out, for some reason *detection_responder.cc* was an empty file. Re-gen example project fixed it.
```
-rw-rw-r-- 1 mhuang mhuang       0 Aug 19 17:42 detection_responder.cc
```
