### ISSUE TITLE
Resource temporarily unavailable, ENOMEM on CPU with memory rlimit

### ISSUE THREAD

**Issue by jploski** [tensorflow/tensorflow#37449]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): yes, trivial example
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Debian buster
- TensorFlow installed from (source or
binary): source
- TensorFlow version (use command below): 2.1.0
- Python version: 3.73
- Bazel version (if compiling from source): ?
- GCC/Compiler version (if compiling from source): 8.3.0
- CUDA/cuDNN version: - GPU model and memory: not relevant

**Describe the current behavior**

The system has 12 GB total physical memory, with /etc/security/limits.conf set to limt per-process max memory to 10 GB as follows:

```
* hard rss 10485760
* hard as 10485760
```
A trivial code example runs out of memory. The last failling syscall obtained with strace is

mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = -1 ENOMEM (Cannot allocate memory)

Looking at mmap invocations from strace confirms that it is indeed allocating close to 10 GB memory before fail. This does not happen when the resource limits are removed. I suspect that it's ignoring the rlimit and trying to allocate all physical memory.

**Describe the expected behavior**

The library should respect the current max memory rlimit (or better yet, not try to allocate all system memory?) or provide some configuration parameter to limit memory (I found none for the CPU-based version).

**Standalone code to reproduce the issue** 

```
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf
import numpy as np

tf.config.set_visible_devices([], 'GPU')
model = tf.keras.Sequential([ tf.keras.layers.Dense(units=1, input_shape=[1]) ])
model.compile(optimizer='sgd', loss='mean_squared_error')

xs = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
ys = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=float)

model.fit(xs, ys, epochs=1)
```

**Other info / logs**

Strace output:

```
...
write(1, "Train on 6 samples\n", 19Train on 6 samples
)    = 19
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
sched_getaffinity(0, 128, [0, 1, 2, 3, 4, 5, 6, 7]) = 64
sysinfo({uptime=8660, loads=[12896, 10528, 13536], totalram=12518699008, freeram=2526597120, sharedram=950390784, bufferram=1171718144, totalswap=4898942976, freeswap=3857969152, procs=741, totalhigh=0, freehigh=0, mem_unit=1}) = 0
mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = -1 ENOMEM (Cannot allocate memory)
futex(0x7f5ca3c481a0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
write(2, "terminate called after throwing "..., 48terminate called after throwing an instance of ') = 48
write(2, "std::system_error", 17std::system_error)       = 17
write(2, "'\n", 2'
)                      = 2
write(2, "  what():  ", 11  what():  )             = 11
write(2, "Resource temporarily unavailable", 32Resource temporarily unavailable) = 32
write(2, "\n", 1
)                       = 1
```

**Comment by amahendrakar** [comment]
@jploski,
I was able to run the code without any issues and did not observe any memory issues. Please find the gist of it [here](https://colab.sandbox.google.com/gist/amahendrakar/2ee4ab61d311029962a3fecb4e969f33/37449.ipynb). Thanks!

**Comment by jploski** [comment]
@amahendrakar What does "ulimit -m" and "ulimit -v" report in your test environment? Did you set a memory limit in /etc/security/limits.conf (and logged in again to make it effective)? This code sample only crashes for me if there is a configured memory limit, and it works otherwise (sorry if that was not clear from the original bug report).

**Comment by amahendrakar** [comment]
@jploski,
The output of both `ulimit -m` and `ulimit -v` is `unlimited`. Please check the gist of it [here](https://colab.research.google.com/gist/amahendrakar/2bf653011ac8556161be9848d73949f0/37449.ipynb). 

Unfortunately, I am unable to set the memory limit in the `limits.conf` file. Thanks!

**Comment by jploski** [comment]
@amahendrakar I just checked that I can also use set the rlimit in shell without without changing limits.conf:
```
ulimit -v 10485760
ulimit -m 10485760
python3 example.py
```
(The value should be something below the total available memory in kB.)

**Comment by amahendrakar** [comment]
@jploski,
I've tried running the above commands and reset the runtime. Didn't observe any changes, got the same output as before.

**Comment by mihaimaruseac** [comment]
TensorFlow does not detect the amount of memory available via rlimits. Crashing when allocating memory above these limits is working as intended. This happens with most programs:

```c
#include <stdio.h>
#include <stdlib.h>

int main () {
        char *a = malloc(SZ);
        printf("Allocated %u bytes to %p\n", SZ, a);
        *a = '0';
        printf("Set the start of %p to 0\n", a);
        return 0;
}
```

```
root@7b8dce9800a9:/work# ulimit -v 4504; ./a.out
Allocated 10000 bytes to 0x55890a43e260
Set the start of 0x55890a43e260 to 0
root@7b8dce9800a9:/work# ulimit -v 4503; ./a.out
Allocated 10000 bytes to (nil)
Segmentation fault (core dumped)
```

Although there exist calls to detect available memory limits and trim allocation, this would have to happen before every allocation and would still be vulnerable to TOCTOU. Plus, it is not portable, thus not something we would prioritize.

Furthermore, there is a [`tf.config.experimental.set_memory_growth`](https://www.tensorflow.org/api_docs/python/tf/config/experimental/set_memory_growth?hl=en) API point.

**Comment by jploski** [comment]
Of course, the issue here is not that a crash occurs when you allocate memory above limit. The issue is that you attempt to allocate more memory than is available, which most programs don't do.

Not fixing this issue means that the non-GPU version is unusable in presence of a rlimit. Not sure how it behaves with other kinds of limits (e.g. cgroup limits imposed by Docker containers), but I predict it would fall on its face as well. (A similar issue existed for a time in Java VM and got fixed to make it behave properly.)

If you can't handle it so as to allocate only the amount of memory actually available to the process, I suggest that you at least display some warning if a memory limit is detected.

**Comment by mihaimaruseac** [comment]
I'm going to add it to the security list of issues for further prioritization.

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
