### ISSUE TITLE
Increase BiasGrad size:  "BiasGrad requires tensor size <= int32 max"

### ISSUE THREAD

**Issue by tonyreina** [tensorflow/tensorflow#37448]
**System information**
- TensorFlow version (you are using): 2.1.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

We've using 3D U-Net on large images (e.g. 512x512x256x4) and have found that when the input size increases above a certain size we get the error:  

```
tensorflow.python.framework.errors_impl.InvalidArgumentError:  BiasGrad requires tensor size <= int32 max
	 [[node BiasAddGrad_3 (defined at testing.py:640) ]] [Op:__inference_distributed_function_2785]
```

I'm pretty sure that this is because the BiasGrad function is using an INT32 datatype and we're declaring more than the datatype can represent as INT32. 

I'd like to request that the datatype be change to something larger-- possible INT64 or at least an unsigned INT32. On CPU we can easily use 100s of GB of RAM for the TensorFlow graph so these are now valid workloads for TF to support.

**Will this change the current api? How?**

No. Other than to change the datatype for BiasGrad to something larger.

**Who will benefit with this feature?**

We've got customers now using 3D networks with very large images (512x512x256x4) and moderately large batch sizes (2-16). The memory footprint for these TF models can fit into CPU memory (~ 1.5 TB) if the datatype is extended to larger integers. 

**Any Other info.**

**Comment by Saduf2019** [comment]
@tonyreina 
Would you please refer to[ this link](https://stackoverflow.com/questions/60414562/how-to-solve-the-biasgrad-requires-tensor-size-int32-max-invalidargumenterr) and let us know if it helps

**Comment by Saduf2019** [comment]
@tonyreina
please update as per above comment

**Comment by tonyreina** [comment]
Yes. That link confirms the issue. The problem is that we are seeing customers with networks (e.g. 3D U-Net with large batches) that use this many elements. On CPU we are able to handle TB of RAM and in particular with high resolution images we are seeing the need for larger networks. So we're requesting that the int32 be increased to handle the new use cases.

**Comment by tonyreina** [comment]
I wanted to circle back on this one. We're starting to get use cases where this is important on medical imaging. Would it be possible to make things at least uint32 to get some extra headroom?

**Comment by rmothukuru** [comment]
@tonyreina,
Sorry for the delayed response. Can you please refer the latest [documentation of BiasAddGrad](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/bias-add-grad) and let us know if the issue still persists? Thanks!
