### ISSUE TITLE
Cross-compile instructions for TFLite XNNPACK delegate on ARM

### ISSUE THREAD

**Issue by WillNichols726** [tensorflow/tensorflow#37447]
Are there any instructions on how to cross-compile the XNNPACK delegate for ARM?

I've tried the following:
export CC=arm-linux-armeabief-gcc
export CPP=arm-linux-armeabief-g++
bazel-2.1.0 build //tensorflow/lite/delegates/xnnpack:xnnpack_delegate

ERROR: /home/andy/.cache/bazel/_bazel_andy/ff7061ef3fb000e53210886b26774f34/external/XNNPACK/BUILD.bazel:1654:1: C++ compilation of rule '@XNNPACK//:sse2_ukernels' failed (Exit 1)
arm-linux-gnueabihf-gcc: error: unrecognized command line option '-msse2'
Target //tensorflow/lite/delegates/xnnpack:xnnpack_delegate failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 26.516s, Critical Path: 14.13s
INFO: 28 processes: 28 local.
FAILED: Build did NOT complete successfully

Ubuntu 14.04 
Bazel 2.1.0
GNU 4.9.3
Targeting Raspberry Pi 3B / Compute Module 3

**Comment by Saduf2019** [comment]
@WillNichols726 
Could you please refer to [this link](https://www.tensorflow.org/lite/guide/build_arm64) and let us know if it helps.

**Comment by WillNichols726** [comment]
Tensorflow 2.1.0

I was able to use the like below to successfully cross-compile libtensorflow_lite.a
https://www.tensorflow.org/lite/guide/build_rpi

Do these instructions also compile the XNNPACK delegate? From what I could see rooting around in the Makefile at tensorflow/lite/tools/make, it didn't look like the XNNPACK delegate was included in the build, nor were there any options to include it.

**Comment by terryheo** [comment]
We don't have XNNPACK support with ./tensorflow/lite/tools/make/build_rpi_lib.sh script yet.
We need to update tensorflow/lite/tools/make/Makefile to build XNNPACK.

**Comment by terryheo** [comment]
I've just checked in ARM crossbuild toolchains (https://github.com/tensorflow/tensorflow/commit/4961f18733ca3967198393abf419e14476b4a85c)  for Bazel build.

You can build armhf, aarch64 targets (include XNNPACK) with the following commands. 

```sh
$ bazel build --config=elinux_armhf  //tensorflow/lite/tools/benchmark:benchmark_model 
$ bazel build --config=elinux_aarch64  //tensorflow/lite/tools/benchmark:benchmark_model 
```
