### ISSUE TITLE
how to extract tflite_hexagon_nn_skel_v1.14.run

### ISSUE THREAD

**Issue by arrow53** [tensorflow/tensorflow#37458]
**System information**
- OS Platform and Distribution - Debian based but tried on Ubuntu 18.04 too

Per the instructions here

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/performance/hexagon_delegate.md#step-2-add-hexagon-libraries-to-your-android-app

when I try to run the extractor I'm presented with a colon. I've tried 'yes', 'accept', but nothing works. It just says "Aborting extraction" and bails.
```
root@linaro-alip:~/hexagon# ./tflite_hexagon_nn_skel_v1.14.run
Creating directory hexagon_nn_skel_v1.14
Verifying archive integrity...  100%   All good.
Uncompressing Hexagon NN Shared Libs  100%  

:
Aborting extraction.. Done
root@linaro-alip:~/hexagon# 
```
Is there some trick to extracting the files?

**Comment by freedomtan** [comment]
`I ACCEPT`

**Comment by freedomtan** [comment]
@karimnosseir it seems, on some Linux platform, no message is displayed just like what @arrow53 showed. It's a bit confusing.

**Comment by karimnosseir** [comment]
Looking

**Comment by karimnosseir** [comment]
@arrow53 I just tried it on a debian based Linux and the license agreement shows and ask you to use "I ACCEPT"

"
....
Type "I ACCEPT" if you agree to the terms of the license:
You didn't accept the license. Extraction aborted.
"

Can you provide more information on the environment you used ?
@freedomtan Can you also share some information

Thanks

**Comment by karimnosseir** [comment]
@arrow53 does it happen also on the v 1.10.3 or only on v1.14

Thanks

**Comment by freedomtan** [comment]
@karimnosseir I tested it on Ubuntu 18.04 LTS. I figured out why. It's dash's problem (on Ubuntu /bin/sh is a symbolic link to dash, which is a sh clone). `rm /bin/sh; ln -s /bin/bash /bin/sh`  then it works.

**Comment by karimnosseir** [comment]
Thanks @freedomtan. @arrow53 Can you try what @freedomtan suggested.

Thanks

**Comment by arrow53** [comment]
@freedomtan thank you so much!!!
@karimnosseir yep works great.

I'm going to close this issue as the solution can be searched now. I'm not sure why the license agreement didn't pop up for me on Ubuntu 18.04. But, maybe just something wrong with my system.

**Comment by arrow53** [comment]
> @arrow53 does it happen also on the v 1.10.3 or only on v1.14
> 
> Thanks

@karimnosseir yes, I see the same on both versions on Ubuntu 18.04 and my embedded Debian system (Dragonboard 820c).
