### ISSUE TITLE
Ops with SparseTensor on GPU gives result in CPU.

### ISSUE THREAD

**Issue by italo-goncalves** [tensorflow/tensorflow#37456]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  custom code
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04):  Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): binary (conda)
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: CUDA 10.1
- GPU model and memory: NVIDIA GTX 1060 6 GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When executing operations on sparse tensors in the GPU (within a `tf.device` block), the result is stored in the CPU. This is causing a huge slowdown in my program, as the data is being copied around between GPU and GPU multiple times.

I have verified that this occurs with the functions `tf.sparse.sparse_dense_matmul` and `tf.sparse.reduce_sum`. It may also occur with others. Is this the intended behavior? I am missing something?

**Describe the expected behavior**
The result of an operation on a sparse tensor with the GPU should stay in the GPU.

**Standalone code to reproduce the issue** 
See [this Colab notebook](https://colab.research.google.com/drive/1BpG8P8dEzDDmtMBIGgSA2wOMzEm4bCzL).

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Thanks in advance.

**Comment by gadagashwini** [comment]
Was able to replicate the issue with Tf 2.1.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/71a5af89e786fbc5a935c1b53dc87576/untitled435.ipynb). Thanks!

**Comment by vlasenkoalexey** [comment]
Unfortunately this is by design, SparseReduceSum OP is not implemented for GPU, see declaration:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/sparse_reduce_op.cc

Very few sparse ops are supported on GPU.

**Comment by vlasenkoalexey** [comment]
See #24404

**Comment by italo-goncalves** [comment]
Thanks for the update. In this case I'm closing the issue.
