### ISSUE TITLE
Installation for Python 3.8.1?

### ISSUE THREAD

**Issue by ali-chaudhry8** [tensorflow/tensorflow#37461]
Hey , just wanted to confirm if you now have the support for Python 3.8.1? If not, I want to use tensorflow 1.15, which python version works best with it?

**Comment by pingsutw** [comment]
@ali-chaudhry8 As I know, TensorFlow 1.15 doesn't support Python 3.8, you could use Python 3.7 ot work with it
related to #33374

**Comment by mihaimaruseac** [comment]
We don't back-release old releases on newer versions of python.
