### ISSUE TITLE
Custom rnn migration to tensorflow 2.x

### ISSUE THREAD

**Issue by np000** [tensorflow/tensorflow#37462]
I want to migrate tensorflow 1.x code to 2.x. I have tried migration script and refererd migration guide. But still its unclear that how to migrate 
1.place holder with shape such as [x,None,y] . 
2. Convert tf_get_variable with xavier initialization
Please find the stackoverflow post link (not answered)

https://stackoverflow.com/questions/60601770/custom-rnn-migration-to-tensorflow-2-0

**Comment by npv0** [comment]
@dynamicwebpaige

**Comment by ayushmankumar7** [comment]
@npv0 did you try compat.v1 ?

**Comment by RobinBaumann** [comment]
> I want to migrate tensorflow 1.x code to 2.x. I have tried migration script and refererd migration guide. But still its unclear that how to migrate
> 1.place holder with shape such as [x,None,y] .

In idiomatic TF2 code, you should convert any `tf.Placeholder` objects to function arguments to a `@tf.function` that replaces your `tf.compat.v1.Session()`. 

> 2. Convert tf_get_variable with xavier initialization

As stated in the [Migration Guide](https://www.tensorflow.org/guide/migrate), replace all `tf.get_variable()` calls with `tf.Variable()` and the `tf.variable_scope`s should be wrapped in python objects like [`tf.keras.layers.Layer`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer). Where you can also specify which initializer you want to use. 

If you don't want to build a layer, you can also use `tf.Module`, which is more general than a layer. 

    class MyModel(tf.Module):
      def __init__(self, ins, outs):
       initializer = tf.initializers.GlorotNormal() # Xavier initialization
       self.W = tf.Variable(initializer([ins, outs]))
       self.B = tf.Variable(tf.zeros([outs], dtype = tf.float32))

**Comment by amahendrakar** [comment]
@npv0,
Could you please check @RobinBaumann's comment and let us know if it works? Thanks!

**Comment by amahendrakar** [comment]
Any updates regarding this issue? Thanks!

**Comment by npv0** [comment]
@RobinBaumann @ayushmankumar7 Thanks a lot for the suggestions. I am trying both methods. 
@amahendrakar sorry I took some time to provide an update here as I was travelling from my city to hometown.
I will post my detailed update this week.

**Comment by np000** [comment]
Please find the below 1.x code and my attempt to convert it to 2.x using tf.Module.
The 2.x code is still under development and the implementation of recurrence part is not working as of now.
tf 1.x code:  https://gist.github.com/np000/a9123dcc64fdf1f4f13b1c1e56ee4e6e
and my conversion attempt : https://gist.github.com/np000/76fe78dda00b900c938a066177df628a

**Comment by np000** [comment]
can anyone please check my gist file and share me a feedback.
Thanks

**Comment by np000** [comment]
@ayushmankumar7 I have tried tf.compat.v1, this worked. My goal is to make a custom tf.module or tf.keras model and train using autograd or model.fit

**Comment by np000** [comment]
i see now the issue got assigned to @gowthamkpr , just following up now. any feedback
thanks

**Comment by gowthamkpr** [comment]
@np000 Is your issue resolved or are you still facing the same issue? Thanks!

**Comment by npvit** [comment]
@gowthamkpr not resolved

**Comment by np000** [comment]
@gowthamkpr still facing the same issue!

**Comment by MarkDaoust** [comment]
>  the implementation of recurrence part is not working as of now.

Hi @np000, 

I think you just need to practice reading your error messages. When I copy-paste your code into colab it says you're passing an unexpected argument to the constructor. "Training" is an argument for when you run a layer or model not when you build it. Keep working at it, I think these are errors you can handle yourself.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-263240bbee7e> in <module>()
----> 1 main()

<ipython-input-1-56c6ddde70bd> in main()
     75 
     76     model = Rnn(features=features, n_hid=n_hid, init_state=init_state, training=training,
---> 77                        n_out=n_out)
     78     logits = model.get_logits()
     79     final_logits = model.get_final_logits()

TypeError: __init__() got an unexpected keyword argument 'training'
```
