### ISSUE TITLE
Configurable attribute "srcs" doesn't match this configuration

### ISSUE THREAD

**Issue by WeiHao97** [tensorflow/tensorflow#37472]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-38-generic aarch64)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0
- Python version: 2.7
- Installed using virtualenv? pip? conda?: N
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): 9.1.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
Bazel build failed when I am trying to build the tflite benchmark

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel build -c opt tensorflow/lite/tools/benchmark:benchmark_model

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=133
INFO: Reading rc options for 'build' from /users/Wei_Hao/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /users/Wei_Hao/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Found applicable config definition build:v2 in file /users/Wei_Hao/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /users/Wei_Hao/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /users/Wei_Hao/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
ERROR: /users/Wei_Hao/.cache/bazel/_bazel_Wei_Hao/fcdad47d36a19e877fa240235b3a74d1/external/cpuinfo/BUILD.bazel:101:1: Configurable attribute "srcs" doesn't match this configuration (would a default condition help?).
Conditions checked:
 @cpuinfo//:linux_x86_64
 @cpuinfo//:macos_x86_64
 @cpuinfo//:android_armv7
 @cpuinfo//:android_arm64
 @cpuinfo//:android_x86
 @cpuinfo//:android_x86_64
 @cpuinfo//:ios_x86_64
 @cpuinfo//:ios_x86
 @cpuinfo//:ios_armv7
 @cpuinfo//:ios_arm64
 @cpuinfo//:ios_arm64e
 @cpuinfo//:watchos_x86_64
 @cpuinfo//:watchos_x86
 @cpuinfo//:watchos_armv7k
 @cpuinfo//:watchos_arm64_32
 @cpuinfo//:emscripten_wasm
ERROR: Analysis of target '//tensorflow/lite/tools/benchmark:benchmark_model' failed; build aborted:

/users/Wei_Hao/.cache/bazel/_bazel_Wei_Hao/fcdad47d36a19e877fa240235b3a74d1/external/cpuinfo/BUILD.bazel:101:1: Configurable attribute "srcs" doesn't match this configuration (would a default condition help?).
Conditions checked:
 @cpuinfo//:linux_x86_64
 @cpuinfo//:macos_x86_64
 @cpuinfo//:android_armv7
 @cpuinfo//:android_arm64
 @cpuinfo//:android_x86
 @cpuinfo//:android_x86_64
 @cpuinfo//:ios_x86_64
 @cpuinfo//:ios_x86
 @cpuinfo//:ios_armv7
 @cpuinfo//:ios_arm64
 @cpuinfo//:ios_arm64e
 @cpuinfo//:watchos_x86_64
 @cpuinfo//:watchos_x86
 @cpuinfo//:watchos_armv7k
 @cpuinfo//:watchos_arm64_32
 @cpuinfo//:emscripten_wasm
INFO: Elapsed time: 1.036s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 17 targets configured)

**Comment by Saduf2019** [comment]
@WeiHao97 
Can you please check this [link](https://stackoverflow.com/questions/57014559/how-to-use-select-to-specify-src-config-of-a-lower-level-library-dependency) and let us know if it helps

**Comment by WeiHao97** [comment]
> @WeiHao97
> Can you please check this [link](https://stackoverflow.com/questions/57014559/how-to-use-select-to-specify-src-config-of-a-lower-level-library-dependency) and let us know if it helps

Hi, I tried --cpu=arm and get the same error, I am wondering if tflite can be build on ubuntu with arm64 architecture since this config does not appear in the select() options.

**Comment by WeiHao97** [comment]
@Saduf2019
 tflite can be build on ubuntu with arm64: architecturehttps://www.tensorflow.org/lite/guide/build_arm64

But my goal is to run the benchmark with bazel. I am not sure how to make this done. Please help

**Comment by tilakrayal** [comment]
@WeiHao97 ,
Is this still an issue?
Could you please update TensorFlow to the latest stable version v.2.7 and let us know if you are facing the same error. Thanks!
