### ISSUE TITLE
TFLite allocate tensors fails: (CONCATENATION) failed to prepare

### ISSUE THREAD

**Issue by moberweger** [tensorflow/tensorflow#37471]
**System information** 
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 18.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **v2.1.0-rc2-17-ge5bf8de 2.1.0**
- Python version: **3.6.9**
- Bazel version (if compiling from source): **N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **N/A**
- GPU model and memory: **N/A**

**Describe the current behavior**

Creating a `tf.keras` model and exporting it to `tflite` causes an error when trying to allocate the tensors for inference. The error is:

> RuntimeError: tensorflow/lite/kernels/concatenation.cc:68 t->dims->size != t0->dims->size (0 != 4)Node number 3 (CONCATENATION) failed to prepare.

**Describe the expected behavior**

The exported model should load without error.

**Standalone code to reproduce the issue** 

Colab gist reproducing the error can be found [here](https://colab.research.google.com/gist/moberweger/9dca6edfdabf996a57dab42ffe044666/untitled0.ipynb#scrollTo=2-Tz7Z1KnVZk)

```
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, Conv2D, Concatenate, Add
from tensorflow.keras.models import Model

if __name__ == '__main__':
    print(tf.version.GIT_VERSION, tf.version.VERSION)
    test_images = np.random.randn(8, 388, 420, 1)

    # model
    m_input = Input(shape=test_images.shape[1:])
    d1 = Conv2D(8, 3, dilation_rate=1, padding='same', use_bias=False)(m_input)
    d2 = Conv2D(8, 3, dilation_rate=2, padding='same', use_bias=False)(m_input)
    d16 = Conv2D(8, 3, dilation_rate=16, padding='same', use_bias=False)(m_input)
    add1 = Add()([d2, d16])
    m_output = Concatenate()([d1, d2, add1])

    model = Model(inputs=m_input, outputs=m_output)
    model.summary()
    model.compile(optimizer='rmsprop', loss='mse')
    pred = model.predict(test_images)
    print(pred.shape)

    # conversion
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    tflite_model = converter.convert()
    with open("model.tflite", "wb") as fp:
        fp.write(tflite_model)

    # inference
    interpreter = tf.lite.Interpreter(model_path="model.tflite")
    input_details = interpreter.get_input_details()
    interpreter.allocate_tensors()
    print("DONE")
```

**Other info / logs**
```
RuntimeError                              Traceback (most recent call last)

<ipython-input-3-4adc506bd32d> in <module>()
     31     interpreter = tf.lite.Interpreter(model_path="model.tflite")
     32     input_details = interpreter.get_input_details()
---> 33     interpreter.allocate_tensors()
     34     print("DONE")

/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/interpreter.py in allocate_tensors(self)
    245   def allocate_tensors(self):
    246     self._ensure_safe()
--> 247     return self._interpreter.AllocateTensors()
    248 
    249   def _safe_to_run(self):

/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py in AllocateTensors(self)
    108 
    109     def AllocateTensors(self):
--> 110         return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
    111 
    112     def Invoke(self):

RuntimeError: tensorflow/lite/kernels/concatenation.cc:68 t->dims->size != t0->dims->size (0 != 4)Node number 3 (CONCATENATION) failed to prepare.
```

**Comment by Saduf2019** [comment]
@moberweger 
Running your code on nightly does not throw any error,please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/05700439ae5c12ea117a518f7a434d3a/37471.ipynb)
Would you please check this [link](https://github.com/tensorflow/tensorflow/issues/34345) for reference

**Comment by moberweger** [comment]
Thanks @Saduf2019  works with nightly, so I am closing this one.
