### ISSUE TITLE
Building bazel on OpenSuSE Leap 15.1 fails due to unrecognized option.

### ISSUE THREAD

**Issue by jlturriff** [tensorflow/tensorflow#37474]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
```
- OS Platform and Distribution:    OpenSuSE Leap 15.1 (x86_64)
- Mobile device                              N/A
- TensorFlow installed from         source
- TensorFlow version:                   0.22.0 (bazel-0.22.0-lp151.2.1.x86_64.rpm, provided in the OpenSuSE repositories)
- Python version:                           2.7.14
- Installed using:                            virtualenv? pip? conda?: Unknown (python is a foreign language for me)
- GPU model and memory:           Intel Corporation HD Graphics 630 (rev 04) (prog-if 00 [VGA controller])
```

**Describe the problem**
Installation fails with the following message:
```
ERROR: Unrecognized option: --experimental_repo_remote_exec
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
- zypper install bazel
- ./configure
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

[BazelInstall.log](https://github.com/tensorflow/tensorflow/files/4311797/BazelInstall.log)

**Comment by Leslie-Fang** [comment]
please use bazel-2.0
refer to this PR: https://github.com/tensorflow/tensorflow/pull/36913

**Comment by amahendrakar** [comment]
@jlturriff,
Could you please check @Leslie-Fang's comment and let us know if it works? Thanks!

**Comment by amahendrakar** [comment]
Any updates regarding this issue? Thanks!

**Comment by venky-intel** [comment]
Hi, I have tried this above suggestion of upgrading to Bazel 2.0. I don't see the `ERROR: Unrecognized option: --experimental_repo_remote_exec` anymore  but upgrading to Bazel 2.0 is resulting in a different error with the Bazel build itself, please see this and the comments for this commit: https://github.com/tensorflow/serving/commit/162f72949c6ecbe9e610182c923dec0aa5924cf2

**Comment by amahendrakar** [comment]
> Any updates regarding this issue? Thanks!

Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by moeiscool** [comment]
looks like the error has returned
```
root@jetson:/home/tensorflow# bazel build --config=opt --config=monolithic //tensorflow/tools/lib_package:libtensorflow
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=248
INFO: Reading rc options for 'build' from /home/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
ERROR: Unrecognized option: --experimental_repo_remote_exec
INFO: Invocation ID: 51e33f1d-1cff-49a1-be8a-db6386079866
```

**Comment by amahendrakar** [comment]
> looks like the error has returned

@moeiscool,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the issue template, so that we can track the issue there. Thanks!
