### ISSUE TITLE
Segmentation fault when importing TensorFlow

### ISSUE THREAD

**Issue by bardeli** [tensorflow/tensorflow#3747]
After installing TensorFlow 0.10.0rc0 with pip in a virtualenv
import tensorflow as tf
results in 
Segmentation fault (core dumped)

Importing numpy before tensorflow results in the same segfault

OS: RedHat 6, 64-bit
(Installed glibc 2.1.4 from source)
Python Version 3.4.5

pip packages (cpu versions):
tensorflow-0.10.0rc0-cp34-cp34m-linux_x86_64.whl
protobuf-3.0.0b2.post2-cp34-none-linux_x86_64.whl
six-1.10.0-py2.py3-none-any.whl
numpy-1.11.1-cp34-cp34m-manylinux1_x86_64.whl
(same problem with numpy-1.8.2-cp34-cp34m-manylinux1_x86_64.whl)

Debugger Output:
gdb python
run tf.py
(tf.py contains: import tensorflow as tf)

[Thread debugging using libthread_db enabled]
Missing separate debuginfo for /home/rolf/tfenv3/lib/python3.4/site-packages/numpy/core/../.libs/libgfortran-ed201abd.so.3.0.0
[New Thread 0x7ffff352a700 (LWP 2920)]
[New Thread 0x7ffff2b29700 (LWP 2921)]
[New Thread 0x7ffff0128700 (LWP 2922)]
[New Thread 0x7fffed727700 (LWP 2923)]
[New Thread 0x7fffead26700 (LWP 2924)]
[New Thread 0x7fffe8325700 (LWP 2925)]
[New Thread 0x7fffe5924700 (LWP 2926)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff793878b in init_one_static_tls (map=0x0) at allocatestack.c:1171
1171      void *dest = (char *) curp - map->l_tls_offset;
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.5-7.el6_0.x86_64 glibc-2.12-1.192.el6.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-57.el6.x86_64 libcom_err-1.41.12-22.el6.x86_64 libselinux-2.0.94-7.el6.x86_64 openssl-1.0.1e-48.el6_8.1.x86_64 zlib-1.2.3-29.el6.x86_64

**Comment by girving** [comment]
I think this kind of error is caused by dueling versions of glibc.  Something linked with TensorFlow is using the wrong version, and two separate versions of glibc in the same process is bad.

**Comment by bardeli** [comment]
This seems to have been the case.
I have replaced six and numpy with the source versions and reinstalled tensorflow with pip.
This removed the segfault but left me with the problem that libstdc++ was too old.
Finally, the following way of setting up a local glibc/libstdc++ environment solved my problem:
http://stackoverflow.com/questions/33655731/error-while-importing-tensorflow-in-python2-7-in-ubuntu-12-04-glibc-2-17-not-f/34897674#34897674

**Comment by girving** [comment]
@bardeli Glad you found away around it!

**Comment by Picbdandan** [comment]
I meet this question,too. then how to get the correct version of glibc?
