### ISSUE TITLE
Benchmark tool

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#37482]
Is there available "benchmarking tool" for TensorFlow Lite for Microcontrollers?

**Comment by wangtz** [comment]
@njeffrie Do you want to take this?

**Comment by njeffrie** [comment]
Definitely - currently we have a very basic benchmark utility under tensorflow/lite/micro/testing/micro_benchmark.h.  Currently, you can only benchmark entire methods, and this is done by running the benchmark like a test.  Work is underway to bring up a better end-to-end solution with a specific benchmark runner.

In the near future, I will be submitting few instructions for creating and running benchmarks under the new directory tensorflow/lite/micro/benchmarks.
