### ISSUE TITLE
AssertionError on using model.fit() in tf.distribute.MirroredStrategy

### ISSUE THREAD

**Issue by fionapatriciamoss** [tensorflow/tensorflow#37485]
**System information**
- OS Platform and Distribution: Ubuntu 18.04.4 LTS
- TensorFlow installed from (source or binary):
- TensorFlow version: 2.2.0-dev20200308
- Python version: 3.7.6
- Installed using virtualenv? pip? conda?: pip

**AssertionError on using model.fit() in tf.distribute.MirroredStrategy**

I'm trying to build an LSTM Autoencoder model to make time series prediction on a large dataset(~30 million rows in train data, 16 million rows each in valid and test data). I've followed the [tutorial](https://www.tensorflow.org/tutorials/distribute/keras) in the Tensorflow documentation to distribute my model across available GPUs using MirroredStrategy with HierarchicalCopyAllReduce as follows:

```
with strategy.scope():
    model = tf.keras.Sequential([
        tf.keras.layers.LSTM(32, activation = 'relu', input_shape = (timesteps, features), return_sequences = True),
        tf.keras.layers.LSTM(16, activation = 'relu', return_sequences = False),
        tf.keras.layers.RepeatVector(timesteps),
        tf.keras.layers.LSTM(16, activation = 'relu', return_sequences = True),
        tf.keras.layers.LSTM(32, activation = 'relu', return_sequences = True),
        tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(num_classes, activation = 'softmax'))
    ])

    model.compile(loss = tf.keras.losses.CategoricalCrossentropy(),
                  optimizer = tf.keras.optimizers.Adam(),
                  metrics = ['accuracy'])
```
When I try to fit the model using the following code, I get the following assertion error:

```
model.fit(X_train_tf, y_train_tf, epochs = 12, validation_data = (X_valid_tf, y_valid_tf), verbose = 1, callbacks=callbacks)

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-17-96b3da4e4eff> in <module>
----> 1 model.fit(X_train_tf, y_train_tf, epochs = 12, validation_data = (X_valid_tf, y_valid_tf), verbose = 1, callbacks=callbacks)

~/.conda/envs/user/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_v1.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    783         max_queue_size=max_queue_size,
    784         workers=workers,
--> 785         use_multiprocessing=use_multiprocessing)
    786 
    787   def evaluate(self,

~/.conda/envs/user/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_distributed.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, **kwargs)
    617         validation_split=validation_split,
    618         shuffle=shuffle,
--> 619         epochs=epochs)
    620     if not dist_utils.is_distributing_by_cloning(model):
    621       with model._distribution_strategy.scope():

~/.conda/envs/user/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_v1.py in _distribution_standardize_user_data(self, x, y, sample_weight, class_weight, batch_size, validation_split, shuffle, epochs, allow_partial_batch)
   2165         x = ds.batch(batch_size, drop_remainder=drop_remainder)
   2166       else:
-> 2167         assert isinstance(x, dataset_ops.DatasetV2)
   2168         training_utils.validate_dataset_input(x, y, sample_weight,
   2169                                               validation_split)

AssertionError:
```
How should I resolve this error? My train, test and validation data are of tensor type.

Thanks in advance!

**Comment by gadagashwini** [comment]
@fionapatriciamoss,
Please share the complete standalone code to reproduce the issue. Thanks!

**Comment by fionapatriciamoss** [comment]
Please find the code below:

[link to code](https://colab.research.google.com/drive/1bFuQzoPi160uOaoY3C6lkE0xj9KFyqS5)

**Comment by ErvisTusha** [comment]
Im getting same error // TPU 
https://colab.research.google.com/drive/1AO7Lz5G1gTOAV6FOR3H2azTOZzBHZwYt

https://github.com/tensorflow/tensorflow/issues/34346

**Comment by jvishnuvardhan** [comment]
I can reproduce the issue with the above colab that uses recent `tf-nightly`. Thanks!

**Comment by karmel** [comment]
It seems like you are disabling eager and using a mix of v1 and v2 APIs here. Can you try with the normal v2 stack (no Session, no disable eager)?

**Comment by ErvisTusha** [comment]
@karmel are you talking about my Code ?
Anyone is taking care about this bug ?

**Comment by JoanaGodinho** [comment]
@fionapatriciamoss have you found a solution for this issue? 
I'am having the same problem using tensorflow v1.15 and tf.keras.utils.Sequence as my input data.

**Comment by Saduf2019** [comment]
@fionapatriciamoss  
Can you please verify with tf-nightky if the issue still exist.

**Comment by goldiegadde** [comment]
@fionapatriciamoss @ErvisTusha  as mentioned above,  the colab link referred to in this issue, is mixing v1 and v2 apis. Can you run your code again without disabling eager execution and let us know if you run into any issues.

**Comment by geetachavan1** [comment]
@fionapatriciamoss and @ErvisTusha did you get a chance to implement the suggestion given on 10/12? Please note that  on 11/19 I will close the issue due to inactivity..
Thanks

**Comment by shirecoding** [comment]
> @fionapatriciamoss have you found a solution for this issue?
> I'am having the same problem using tensorflow v1.15 and tf.keras.utils.Sequence as my input data.

same here
