### ISSUE TITLE
Confusing behavior of GRUCell

### ISSUE THREAD

**Issue by xlnwel** [tensorflow/tensorflow#37497]
```python
cell = layers.GRUCell(4)
x = tf.random.normal((2, 2, 3))
print(cell.get_initial_state(x)) # returns a single tensor
cell(x[:, 0], [cell.get_initial_state(x)]) # requires and returns a list of tensors
```
Why would `GRUCell.get_initial_state` return a Tensor, while calling `GRUCell` requires a list of Tensor as input? Is this a desired behavior? (code tested in TF2.1)

Furthermore, while `Cell` returns output and state separately, RNN returns the output and states together in a single list.

```python
cell = layers.LSTMCell(4)
x = tf.random.normal((2, 2, 3))
s = cell.get_initial_state(x)
cell_output, state = cell(inputs=x[:, 1], states=s)# works fine
print(cell_output)
print(state)
rnn = layers.RNN(cell, return_state=True, return_sequences=True)
rnn_output, state = rnn(x, initial_state=s)# error: rnn returns the output and states in a single list
```

I'm wondering why `rnn` and `cell` behave differently?

**Comment by ravikyram** [comment]
@xlnwel 
I have tried on colab with TF version 2.1.0 and and i am seeing the below error `ValueError: too many values to unpack (expected 2)`. Is this the expected behavior?. It will be helpful if you provide a colab link to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by Susmit-A** [comment]
A `Cell` processes a single time step, while a `RNN` processes all time steps. Setting `return_sequences = True` in RNN returns three values, of shapes `[batch_size, time steps, output_shape], [batch_size, output_shape], [batch_size, output_shape]`.

Check [the example on the TF LSTM page](https://www.tensorflow.org/api_docs/python/tf/keras/layers/LSTM)

**Comment by xlnwel** [comment]
@ravikyram Yeah, the code provided by me will raise error `ValueError: too many values to unpack (expected 2)` at the last line. Here's the [colab link](https://colab.research.google.com/drive/1z58JoPdMDszfXV-rHBAOM6HUDd-W2yVb) I use for test. I humbly think that it will be easier to use if 

1. `cell.get_initial_state(x)` returns a list of tensor, where `cell` could be any RNN cell, including GRUCell, whose state is a single tensor.
2. when RNN is parameterized by `return_state=True`, rnn(x) returns the output and RNN state, where RNN state is a list of tensors. That means for LSTM, `rnn(x)` returns `[output, [h, c]]`, and for GRU, `rnn(x)` returns `[output, [state]]`

That's my personal suggestion. But I believe you team designed the behavior for a reason, I'd like to hear that.

**Comment by xlnwel** [comment]
@Susmit-A, thanks for point out the different behavior of `Cell` and `RNN`, although I've already known them before. Please check this [colab link](https://colab.research.google.com/drive/1z58JoPdMDszfXV-rHBAOM6HUDd-W2yVb) and the comment above.

**Comment by gowthamkpr** [comment]
@xlnwel GRU is a recurrent layer. GRUCell is an object (which happens to be a layer too) used by the GRU layer that contains the calculation logic for one step.
A recurrent layer contains a cell object. The cell contains the core code for the calculations of each step, while the recurrent layer commands the cell and performs the actual recurrent calculations.

As this is not a bug, please post this issue in stackoverflow where there is a broader community to help. Thanks!

**Comment by xlnwel** [comment]
Hi, @gowthamkpr. Thanks for your explanation. I know the difference between GRU and GRUCell, and I was not saying this is a bug. I just found their different styles of outputs are confusing and hard to use. Therefore, I'm wondering why you decided to adopt different behaviors for them? Please check my [colab link](https://colab.research.google.com/drive/1z58JoPdMDszfXV-rHBAOM6HUDd-W2yVb).
