### ISSUE TITLE
tf.linalg.diag doesn't use "k" value

### ISSUE THREAD

**Issue by jacksonloper** [tensorflow/tensorflow#37492]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): no
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): ubuntu 16.04
- TensorFlow installed from (source or
binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6
- CUDA/cuDNN version: N/A cpu
- GPU model and memory: N/A cpu

**Describe the current behavior**
```
import tensorflow as tf
import numpy as np
diagonal = np.array([[1, 2, 3],  
                     [4, 5, 6]])
tf.linalg.diag(diagonal, k = 1)
```

responds with

```
<tf.Tensor: shape=(2, 3, 3), dtype=int64, numpy=
array([[[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]],

       [[4, 0, 0],
        [0, 5, 0],
        [0, 0, 6]]])>
```

**Describe the expected behavior**

According to the docs, it should give me

```
[[[0, 1, 0, 0],  # Output shape: (2, 4, 4)
        [0, 0, 2, 0],
        [0, 0, 0, 3],
        [0, 0, 0, 0]],
       [[0, 4, 0, 0],
        [0, 0, 5, 0],
        [0, 0, 0, 6],
        [0, 0, 0, 0]]]
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

https://colab.research.google.com/drive/1Hj6Sks-m_V0gqw6SK9eowpRpIhOlHYXk

This notebook shows that, in fact, the `k` argument appears to be ignored completely.  

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@jacksonloper 
The code is running as expected in nightly version,please find the [gist](https://colab.sandbox.google.com/gist/Saduf2019/85ba436b4ff63317503a1380b30798b8/37492.ipynb) for the same

**Comment by Saduf2019** [comment]
@jacksonloper
could you please update on the above comment
