### ISSUE TITLE
C-API timeline for TensorFlow 2

### ISSUE THREAD

**Issue by nio1814** [tensorflow/tensorflow#37496]
On the Install TensorFlow for C page, it notes that 
 "There is no libtensorflow support for TensorFlow 2 yet. It is expected in a future release."

Is there any update on when we can expect the c api for TF2?

**Comment by GatGit12** [comment]
I would be interested in it as well.

**Comment by katmatus** [comment]
Is **C api for TF2** coming soon?

**Comment by mihaimaruseac** [comment]
@av8ramit and @bmzhao are working on it

**Comment by av8ramit** [comment]
[Here](https://storage.googleapis.com/libtensorflow-nightly) is a link in the meantime to a directory listing of builds we've uploaded recently.

**Comment by katmatus** [comment]
Thank you for quick reply. How can I see tensorflow version of these builds?

**Comment by mihaimaruseac** [comment]
They are all build from master, so they closely match tf-nightly

**Comment by joaquimvila** [comment]
Is C api for TF2 to be included on next release (2.3)?

**Comment by av8ramit** [comment]
Yes we are planning to have libtensorflow releases for the 2.3 release.

**Comment by joaquimvila** [comment]
This is very good news. Thanks for the fast response.

**Comment by nio1814** [comment]
Doesn't look like the [Install TensorFlow for C](https://www.tensorflow.org/install/lang_c) webpage has been updated yet. Is there a link to get the official 2.3 libraries?

**Comment by CarlPoirier** [comment]
It is now!
