### ISSUE TITLE
error: can't copy 'tensorflow/python/ops/gen_sparse_ops.py': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by gclouding** [tensorflow/tensorflow#3749]
After I compiled the source code of TF0.10 (the latest version) using command "bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package", I tried to generate the .whl package using the following command:
"bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg"
However, errors occured:
Thu Aug 11 20:10:14 EDT 2016 : === Using tmpdir: /tmp/tmp.r1OX0vuucW
/tmp/tmp.r1OX0vuucW ~/bxl/tf1.0
Thu Aug 11 20:10:14 EDT 2016 : === Building wheel
error: can't copy 'tensorflow/python/ops/gen_sparse_ops.py': doesn't exist or not a regular file

Anyone knows how to solve this? Thx

**Comment by tomrunia** [comment]
I had the same error, but for me there was already an error during the build process. Check if you have the same problem (missing `/usr/local/cuda/` dependencies) and then fix the problem by adding a line to the file `third_party/gpus/crosstool/CROSSTOOL`, see here: https://github.com/tensorflow/tensorflow/issues/3589#issuecomment-236430359

This fix works for me using both CUDA Toolkit version 7.5 and 8.0 RC.

**Comment by gclouding** [comment]
No, I don't have the cuda error. 
Is there any idea to solve the problem in generating whl package?

**Comment by girving** [comment]
Can you show us the full output of all your build commands?

**Comment by gclouding** [comment]
I found that the build is not successful and has the following error: @girving 

ERROR: /home/dl/bxl/tf-0815/tensorflow/contrib/rnn/BUILD:46:1: undeclared inclusion(s) in rule '//tensorflow/contrib/rnn:python/ops/_lstm_ops_gpu':
this rule is missing dependency declarations for the following files included by 'tensorflow/contrib/rnn/kernels/lstm_ops_gpu.cu.cc':
  '/usr/local/cuda-7.5/include/cuda_runtime.h'
  '/usr/local/cuda-7.5/include/host_config.h'
  '/usr/local/cuda-7.5/include/builtin_types.h'
  '/usr/local/cuda-7.5/include/device_types.h'
  '/usr/local/cuda-7.5/include/host_defines.h'
  '/usr/local/cuda-7.5/include/driver_types.h'
  '/usr/local/cuda-7.5/include/surface_types.h'
  '/usr/local/cuda-7.5/include/texture_types.h'
  '/usr/local/cuda-7.5/include/vector_types.h'
  '/usr/local/cuda-7.5/include/channel_descriptor.h'
  '/usr/local/cuda-7.5/include/cuda_runtime_api.h'
  '/usr/local/cuda-7.5/include/cuda_device_runtime_api.h'
  '/usr/local/cuda-7.5/include/driver_functions.h'
  '/usr/local/cuda-7.5/include/vector_functions.h'
  '/usr/local/cuda-7.5/include/vector_functions.hpp'
  '/usr/local/cuda-7.5/include/common_functions.h'
  '/usr/local/cuda-7.5/include/math_functions.h'
  '/usr/local/cuda-7.5/include/math_functions.hpp'
  '/usr/local/cuda-7.5/include/math_functions_dbl_ptx3.h'
  '/usr/local/cuda-7.5/include/math_functions_dbl_ptx3.hpp'
  '/usr/local/cuda-7.5/include/cuda_surface_types.h'
  '/usr/local/cuda-7.5/include/cuda_texture_types.h'
  '/usr/local/cuda-7.5/include/device_functions.h'
  '/usr/local/cuda-7.5/include/device_functions.hpp'
  '/usr/local/cuda-7.5/include/device_atomic_functions.h'
  '/usr/local/cuda-7.5/include/device_atomic_functions.hpp'
  '/usr/local/cuda-7.5/include/device_double_functions.h'
  '/usr/local/cuda-7.5/include/device_double_functions.hpp'
  '/usr/local/cuda-7.5/include/sm_20_atomic_functions.h'
  '/usr/local/cuda-7.5/include/sm_20_atomic_functions.hpp'
  '/usr/local/cuda-7.5/include/sm_32_atomic_functions.h'
  '/usr/local/cuda-7.5/include/sm_32_atomic_functions.hpp'
  '/usr/local/cuda-7.5/include/sm_35_atomic_functions.h'
  '/usr/local/cuda-7.5/include/sm_20_intrinsics.h'
  '/usr/local/cuda-7.5/include/sm_20_intrinsics.hpp'
  '/usr/local/cuda-7.5/include/sm_30_intrinsics.h'
  '/usr/local/cuda-7.5/include/sm_30_intrinsics.hpp'
  '/usr/local/cuda-7.5/include/sm_32_intrinsics.h'
  '/usr/local/cuda-7.5/include/sm_32_intrinsics.hpp'
  '/usr/local/cuda-7.5/include/sm_35_intrinsics.h'
  '/usr/local/cuda-7.5/include/surface_functions.h'
  '/usr/local/cuda-7.5/include/surface_functions.hpp'
  '/usr/local/cuda-7.5/include/texture_fetch_functions.h'
  '/usr/local/cuda-7.5/include/texture_fetch_functions.hpp'
  '/usr/local/cuda-7.5/include/texture_indirect_functions.h'
  '/usr/local/cuda-7.5/include/texture_indirect_functions.hpp'
  '/usr/local/cuda-7.5/include/surface_indirect_functions.h'
  '/usr/local/cuda-7.5/include/surface_indirect_functions.hpp'
  '/usr/local/cuda-7.5/include/device_launch_parameters.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/Core'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/util/DisableStupidWarnings.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/util/Macros.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/util/MKL_support.h'
  '/usr/local/cuda-7.5/include/cuda_fp16.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/util/Constants.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/util/Meta.h'
  '/usr/local/cuda-7.5/include/math_constants.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/util/ForwardDeclarations.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/util/StaticAssert.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/util/XprHelper.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/util/Memory.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/NumTraits.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/MathFunctions.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/GenericPacketMath.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/arch/CUDA/Half.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/arch/CUDA/PacketMathHalf.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/arch/CUDA/TypeCasting.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/arch/CUDA/PacketMath.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/arch/CUDA/MathFunctions.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/arch/Default/Settings.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/functors/TernaryFunctors.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/functors/BinaryFunctors.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/functors/UnaryFunctors.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/functors/NullaryFunctors.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/functors/StlFunctors.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/functors/AssignmentFunctors.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/DenseCoeffsBase.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/DenseBase.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/plugins/BlockMethods.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/MatrixBase.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/plugins/CommonCwiseUnaryOps.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/plugins/CommonCwiseBinaryOps.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/plugins/MatrixCwiseUnaryOps.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/plugins/MatrixCwiseBinaryOps.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/EigenBase.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Product.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/CoreEvaluators.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/AssignEvaluator.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Assign.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/ArrayBase.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/plugins/ArrayCwiseUnaryOps.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/plugins/ArrayCwiseBinaryOps.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/util/BlasUtil.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/DenseStorage.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/NestByValue.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/ReturnByValue.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/NoAlias.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/PlainObjectBase.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Matrix.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Array.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/CwiseTernaryOp.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/CwiseBinaryOp.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/CwiseUnaryOp.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/CwiseNullaryOp.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/CwiseUnaryView.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/SelfCwiseBinaryOp.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Dot.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/StableNorm.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Stride.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/MapBase.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Map.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Ref.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Block.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/VectorBlock.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Transpose.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/DiagonalMatrix.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Diagonal.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/DiagonalProduct.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Redux.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Visitor.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Fuzzy.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/IO.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Swap.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/CommaInitializer.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/GeneralProduct.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Solve.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Inverse.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/SolverBase.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/PermutationMatrix.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Transpositions.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/TriangularMatrix.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/SelfAdjointView.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/products/GeneralBlockPanelKernel.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/products/Parallelizer.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/ProductEvaluators.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/products/GeneralMatrixVector.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/products/GeneralMatrixMatrix.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/SolveTriangular.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/products/SelfadjointMatrixVector.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/products/SelfadjointMatrixMatrix.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/products/SelfadjointProduct.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/products/SelfadjointRank2Update.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/products/TriangularMatrixVector.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/products/TriangularMatrixMatrix.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/products/TriangularSolverMatrix.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/products/TriangularSolverVector.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/BandMatrix.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/CoreIterators.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/ConditionEstimator.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/BooleanRedux.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Select.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/VectorwiseOp.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Random.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Replicate.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/Reverse.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/ArrayWrapper.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/GlobalFunctions.h'
  '/home/dl/bxl/fix-0815/eigen-eigen-6f952374ef2b/Eigen/src/Core/util/ReenableStupidWarnings.h'
  '/usr/local/cuda-7.5/include/curand_kernel.h'
  '/usr/local/cuda-7.5/include/curand.h'
  '/usr/local/cuda-7.5/include/curand_discrete.h'
  '/usr/local/cuda-7.5/include/curand_precalc.h'
  '/usr/local/cuda-7.5/include/curand_mrg32k3a.h'
  '/usr/local/cuda-7.5/include/curand_mtgp32_kernel.h'
  '/usr/local/cuda-7.5/include/cuda.h'
  '/usr/local/cuda-7.5/include/curand_mtgp32.h'
  '/usr/local/cuda-7.5/include/curand_philox4x32_x.h'
  '/usr/local/cuda-7.5/include/curand_globals.h'
  '/usr/local/cuda-7.5/include/curand_uniform.h'
  '/usr/local/cuda-7.5/include/curand_normal.h'
  '/usr/local/cuda-7.5/include/curand_normal_static.h'
  '/usr/local/cuda-7.5/include/curand_lognormal.h'
  '/usr/local/cuda-7.5/include/curand_poisson.h'
  '/usr/local/cuda-7.5/include/curand_discrete2.h'.
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 103.576s, Critical Path: 94.31s

**Comment by girving** [comment]
@martinwicke Another undeclared inclusion; do you know if this is fixed?  @gclouding Can you try with the latest source to see if it's different?

**Comment by gclouding** [comment]
The problem was finally solved by adding the library path of cuda and eigen in the cxx_builtin_include_directory in the file  ./third_party/gpus/crosstool/CROSSTOOL @girving

**Comment by prb12** [comment]
This issue looks like it is now solved?  Please reopen if the problem is still present.
