### ISSUE TITLE
[TF2.0] How to save model just keep recent 5 models by using keras?

### ISSUE THREAD

**Issue by SmileTM** [tensorflow/tensorflow#37508]
in eager mode, we can use `CheckpointManager` to save recent 5 models.
```
manager = tf.train.CheckpointManager(checkpoint, directory='./save', checkpoint_name='model.ckpt', max_to_keep=5)
```
but how to save model just keep recent 5 models by using kears? 
( model.complie() , model.fit(), callbacks )

**Comment by amahendrakar** [comment]
@SmileTM,
Could you please look into keras [ModelCheckpoint](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/ModelCheckpoint) and let us know if it helps? Thanks!

**Comment by SmileTM** [comment]
> @SmileTM,
> Could you please look into keras [ModelCheckpoint](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/ModelCheckpoint) and let us know if it helps? Thanks!

ModelCheckpoint can't achieve this function. I hope it can achieve this function `max_to_keep` in the future .

But I can achieve this function by Overriding `Clallback`.  
 
```
class Save_Callbacks(tf.keras.callbacks.Callback):
    def __init__(self, checkpoint_manager):
        self.checkpoint_manager = checkpoint_manager

    def on_train_batch_end(self, batch, logs=None):
        super().on_train_batch_end(batch, logs)
        self.checkpoint_manager.save()

checkpoint = tf.train.Checkpoint(model=model, optimizer=model.optimizer)
checkpoint_manager = tf.train.CheckpointManager(checkpoint, 'save', max_to_keep=5)
save_callbacks=  Save_Callbacks(checkpoint_manager )
```
