### ISSUE TITLE
tf.config.experimental.list_physical_devices('GPU') stopped listing my gpu after update from 2.0.1 to 2.1.0

### ISSUE THREAD

**Issue by guischmitd** [tensorflow/tensorflow#37510]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): 
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 
- Python version: - Bazel
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I'm using the following lines to set allow growth on TF 2.0 like I used to with tf.config and sessions on TF1:
```python
physical_devices = tf.config.experimental.list_physical_devices('GPU')
assert len(physical_devices) > 0, "Not enough GPU hardware devices available"
tf.config.experimental.set_memory_growth(physical_devices[0], True)
```
I've updated from 2.0.1 to 2.1.0 (via `pip install`) and suddenly `tf.config.experimental.list_physical_devices('GPU')` stopped listing my GPU as an available device.

**Describe the expected behavior**
When downgrading to 2.0.1 (again via `pip install`) everything works again.

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
import tensorflow as tf

physical_devices = tf.config.experimental.list_physical_devices('GPU')
assert len(physical_devices) > 0, "Not enough GPU hardware devices available"
tf.config.experimental.set_memory_growth(physical_devices[0], True)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by RobinBaumann** [comment]
Could you please provide information about your system configuration? Which cuda/cuDNN versions have you installed? You can find tested configurations at https://www.tensorflow.org/install/source#tested_build_configurations.

**Comment by guischmitd** [comment]
Ok, from your link I have to assume it's a CUDA version issue. I'm currently on Ubuntu 18.04 with CUDA 10.0 + cuDNN 7.6.5
Unfortunately I cannot test this right now, I'll close the issue and comment again with results once I find the time.

**Comment by Divyam10** [comment]
Tensorflow 2.1 is not compatible with CUDA 10.0. You will have install CUDA 10.1 along with 10.0 or make new conda environment and with tensorflow-gpu=2.1.0. Conda will install Cuda 10.1 for that environment.
`conda install anaconda tensorflow-gpu=2.1.0
`
