### ISSUE TITLE
Posenet Android Example. TestActivity crashes. Incorrect sample image size. comp:lite type: support

### ISSUE THREAD

**Issue by amitDaMan** [tensorflow/tensorflow#37516]
**Describe the current behavior**
TestActivity Crashes. input image is wrong size. 

**Describe the expected behavior**

Line 209: Posenet.kt
getInterpreter().runForMultipleInputsOutputs(inputArray, outputMap)

inputArray has a direct byte buffer of size 1088659, 
Interpreter/model expects a TensorFlowLite buffer of 792588 bytes

The bitmap being used for this TestActivity is 560X353, while the size of the bitmap during the execution of CameraActivity is 257 x 257, which does correspond to the correct buffer size.   

Exception message:
Cannot convert between a TensorFlowLite buffer with 792588 bytes and a ByteBuffer with 1088652 bytes.

**Solution:**
choose a different sample image matching the constraint of producing a buffer of 792588 bytes, and change TestActivity:drawableToBitmap accordingly

For example, I know an image of 257 x 257 works (via CameraActivity), and then I change
Line 33 in TestActivity:drawableToBitmap to    
val bitmap = Bitmap.createBitmap(257, 257, Bitmap.Config.ARGB_8888)

Even better would be maintaining the ratio of the input image (rather than hardcoding 257 x 257) and fulfilling the constraint of proper number of bytes for the model. Then any image could be tested, while avoiding unappealing stretching and skewing.

**Comment by amitDaMan** [comment]
Would it be easier if I created pull requests instead of opening issues, if I have a solution to a bug.

**Comment by ymodak** [comment]
@amitDaMan Please go ahead and raise a PR. Also reference this issue thread in the request. Thanks!

**Comment by lintian06** [comment]
In general, this [TestActivitiy](https://github.com/tensorflow/examples/blob/master/lite/examples/posenet/android/app/src/main/java/org/tensorflow/lite/examples/posenet/TestActivity.kt) is not used in the app but only kept for reference. 

Please go ahead and raise a PR to fix this. Thank you!

**Comment by amitDaMan** [comment]
@lintian06  I have raised a PR for this minor change, it uses Tensorflow lite support library to resize the resource image to fit the requisite input size for the posenet model, thank you.
