### ISSUE TITLE
Add concatenated_categorical_column in feature column api.

### ISSUE THREAD

**Issue by brightcoder01** [tensorflow/tensorflow#37521]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): TF 2.1
- Are you willing to contribute it (Yes/No): Yes. And the code change is ready.

**Describe the feature and the current behavior/state.**
*Feature:*
Add a new feature column api *concatenated_categorical_column* to concatenate SparseTensors from multiple categorical columns into one SparseTensor.
The id range of each categorical column is [0, num_buckets_0], [0, num_buckets_1] ... [0, num_buckets_n]. The ids will be conflict in the combined sparse id tensor because they all start from 0. In this api, we will add offset in sparse id tensor from each categorical column to avoid this conflict. After concatenation, the id range of the concatenated column is [0, num_bucket_0 + num_bucket_1 + ... + num_bucket_n].
The api definition is as follows
```python
tf.feature_column.concatenated_categorical_column(categorical_columns)

Args:
    categorical_columns: List of categorical columns created by a categorical_column_with_* function.
```

*Current Behavior:*
There is no feature column api to concatenate multiple categorical columns. Users cannot do this transformation with feature column.

*Why we need this api:*
A dataset sometimes contains many categorical features. If we map each categorical feature to an embedding vector separately, we need to create many variables for the embedding tables, one for each categorical feature. Besides the embedding table weights, there is additional overhead to create a variable. **As a result, the size of the model will be very huge if we create many embedding variables even though the size of each embedding table is small, and the performance of embedding lookup may be inefficient.**
![image](https://user-images.githubusercontent.com/18071380/74301254-795bac80-4d8d-11ea-98e3-2632e47df669.png)

In order to reduce the number of variables for the embedding table, we can concatenate the sparse id tensors from multiple categorical feature into a big sparse tensor, and also merge the embedding tables for each categorical feature into one table. However, the id of each categorical feature start from 0. And the same IDs will map to the same embedding vectors by looking up in the merged embedding table. In the following figure, we can see that embedding vectors of "marital-status" are the same as "education".
![image](https://user-images.githubusercontent.com/18071380/74301128-00f4eb80-4d8d-11ea-97eb-7db2e798ffb2.png)

So, we need to add an offset into IDs of "marital-status" so that the "martial-status" feature can get its embedding vectors by looking up in the merged embedding table. 
![image](https://user-images.githubusercontent.com/18071380/74301135-06eacc80-4d8d-11ea-9f2b-2a577ed52b0f.png)

**Will this change the current api? How?**
No, we won't change the existed Api. 
We will add a new feature column api *concatenated_categorical_column*.

**Who will benefit with this feature?**
The TensorFlow users who will develop the model with many categorical features and want to map these feature to embedding vectors.

**Any Other info.**

**Comment by tanzhenyu** [comment]
Hi @brightcoder01 we're no longer supporting new features for feature columns and planning to deprecate them from 2.2 and forward.
This feature sounds reasonable, but it should be achievable through keras natively, i.e., we're exporting a preprocessing layer called index_lookup to convert categorical inputs to integers, and you can add the offset manual before passing to embedding layer.
For more info, check this [RFC](https://github.com/tensorflow/community/pull/188)

**Comment by brightcoder01** [comment]
Hi, @tanzhenyu , Thanks for your reply.
From the API spec for TF2.2rc, the proposed layers is not included in tf.keras.preprocessing package. Will these layers be released TF2.2 or later?
What's more, will the API in tf.feature_column be removed in TF2.2 or later version?

**Comment by DachuanZhao** [comment]
How can we use ```tf.estimator.LinearClassifier``` since there is a arg ```feature_columns``` if  tf.feature_column is removed ?
