### ISSUE TITLE
Using @tf.function will turn the EagerTensor into Tensor

### ISSUE THREAD

**Issue by DracarysLu** [tensorflow/tensorflow#37522]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by ravikyram** [comment]
@DracarysLu 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

Please, provide the simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster.Please, fill the [issue templete](https://github.com/tensorflow/tensorflow/issues/new/choose).Thanks!

**Comment by pandrey-fr** [comment]
> Using @tf.function will turn the EagerTensor into Tensor
Yes, that is the point. Please [read the docs](https://www.tensorflow.org/guide/eager#work_with_functions).

**Comment by DracarysLu** [comment]
> @DracarysLu
> 
> Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
> 
> Please, provide the simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster.Please, fill the [issue templete](https://github.com/tensorflow/tensorflow/issues/new/choose).Thanks!


The environment is Tensorflow 2.1, no matter with the OS (Both in Linux and Windows).

When I add the "@tf.function" before the train_step function and print  the result of loss, it goes wrong. 
`@tf.function
def train_step(train_batch, labels):
    with tf.GradientTape() as tape:
        outputs = model(train_batch, training=True)
        loss = loss_obj(labels, outputs)
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    
    train_loss(loss)
    print(loss.numpy())
    train_accuracy(labels, outputs)
`

> AttributeError: in converted code:

    <ipython-input-6-a47c909007ec>:10 train_step  *
        print(loss.numpy())

    AttributeError: 'Tensor' object has no attribute 'numpy'.

But when I remove the "@tf.function", it works well.

> epoch: 1
   2.4107723
   2.4120736
   1.7468656
   1.4507847
   1.3938136
   1.2365413
   0.9930383
   0.93578833
   0.81582385
   0.8927727
   0.7690362

**Comment by pandrey-fr** [comment]
Again, this is expected behaviour. The `.numpy()` call only works on `EagerTensor` objects, i.e. when running in Eager mode. The whole point of `tf.function` decoration is to run a function in graph mode to optimize runtimes, which results in tensors not having a `.numpy` method.
You may however try to use `tf.print`.

**Comment by DracarysLu** [comment]
> Again, this is expected behaviour. The `.numpy()` call only works on `EagerTensor` objects, i.e. when running in Eager mode. The whole point of `tf.function` decoration is to run a function in graph mode to optimize runtimes, which results in tensors not having a `.numpy` method.
> You may however try to use `tf.print`.

Thanks!

**Comment by ravikyram** [comment]
@DracarysLu 

 Please close this thread if it solves your question. Thanks!
