### ISSUE TITLE
problem load saved model using tensorflow java 

### ISSUE THREAD

**Issue by jaydone78** [tensorflow/tensorflow#37540]
Hello,

I was using keras to build a simple MLP model, and want to use it for online prediction. Our online system is written in java, so I want to use tensorflow-java lib to load the model in savedmodel format. I saved the keras model using following scripts:
`  model = tf.keras.models.load_model(path)
  tf.saved_model.save(model, 'savedmodel/v1')
`

and write some simple test code to check all the opration nodes:
`   SavedModelBundle b = SavedModelBundle.load("/Users/jaydone/v1", "serve");
    Iterator<Operation> ops = b.graph().operations();
    Session sess = b.session();
    List<String> opNames = new ArrayList<>();
    while (ops.hasNext()) {
      Operation next = ops.next();
      System.out.println(next.name());
    }`

after running the code above, I get the output 
embedding_1/embeddings
embedding_1/embeddings/Read/ReadVariableOp
dense_1/kernel
dense_1/kernel/Read/ReadVariableOp
dense_1/bias
dense_1/bias/Read/ReadVariableOp
dense_2/kernel
dense_2/kernel/Read/ReadVariableOp
dense_2/bias
dense_2/bias/Read/ReadVariableOp
relevance_output/kernel
relevance_output/kernel/Read/ReadVariableOp
relevance_output/bias
relevance_output/bias/Read/ReadVariableOp
training/SGD/iter
training/SGD/iter/Read/ReadVariableOp
training/SGD/decay
training/SGD/decay/Read/ReadVariableOp
training/SGD/learning_rate
training/SGD/learning_rate/Read/ReadVariableOp
training/SGD/momentum
training/SGD/momentum/Read/ReadVariableOp
total
total/Read/ReadVariableOp
count
count/Read/ReadVariableOp
NoOp
Const
serving_default_albumid_embedding
serving_default_dense_input
serving_default_userid_embedding
StatefulPartitionedCall
saver_filename
StatefulPartitionedCall_1
StatefulPartitionedCall_2

none of them seems to be the output node. 

So how can I identify the output node, maybe I should add some parameters to specify it when saving the model like this ? 
`  tf.saved_model.save(model, 'savedmodel/v1', output=['relevance_output'])
`
Can anyone help me, thanks very much.

**Comment by Eshan-Agarwal** [comment]
Hey @jaydone78  `model = tf.keras.models.load_model(path)` is used for loading model which is saved using `tf.keras.models.save_model` refer (this)[https://www.tensorflow.org/api_docs/python/tf/keras/models/load_model] for loading model and (this)[https://www.tensorflow.org/api_docs/python/tf/keras/models/save_model] for saving.

Or you can just do as for saving and loading model :

`model.save("model.h5")`
`New_Model` = tf.keras.models.load_model("model.h5")
`New_Model.summary()`

**Comment by jaydone78** [comment]
> Hey @jaydone78 `model = tf.keras.models.load_model(path)` is used for loading model which is saved using `tf.keras.models.save_model` refer [this](https://www.tensorflow.org/api_docs/python/tf/keras/models/load_model) for loading model and [this](https://www.tensorflow.org/api_docs/python/tf/keras/models/save_model) for saving.
> 
> Or you can just do as for saving and loading model :
> 
> `model.save("model.h5")`
> `New_Model` = tf.keras.models.load_model("model.h5")
> `New_Model.summary()`
I want to use the model in 'saved_model' format, which can be used in c++, java.

**Comment by Eshan-Agarwal** [comment]
Can you please provide code for model also which you are saving ?

**Comment by jaydone78** [comment]
I finally use following command 
`saved_model_cli show --dir v1 --tag_set serve --signature_def serving_default `

and get the input, output node name like this:

`The given SavedModel SignatureDef contains the following input(s):
  inputs['albumid_embedding'] tensor_info:
      dtype: DT_INT32
      shape: (-1, 1)
      name: serving_default_albumid_embedding:0
  inputs['dense_input'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 10)
      name: serving_default_dense_input:0
  inputs['userid_embedding'] tensor_info:
      dtype: DT_INT32
      shape: (-1, 7)
      name: serving_default_userid_embedding:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['relevance_output'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 1)
      name: StatefulPartitionedCall:0
Method name is: tensorflow/serving/predict`
problem solved.
