### ISSUE TITLE
Concat op not quantized 

### ISSUE THREAD

**Issue by ppatrikg** [tensorflow/tensorflow#37544]
This issue is related to the concat implementation used for TFlite and TFlite micro.
For uint8 there are no restrictions on having the same scaling/zeropoint in the Input/Output.

But the implementation is not quantized
in concatenation.cc:
// TODO(prabhumk): This is the same as the optimized implementation.
// TODO(prabhumk): The quantized implementation of concatentation isn't fully
// quantized as it takes scale as a floating point value. This should be fixed
// when optimizng this routine further.
inline void ConcatenationWithScaling(const ConcatenationParams& params,
                                     const RuntimeShape* const* input_shapes,
                                     const uint8* const* input_data,
                                     const RuntimeShape& output_shape,
                                     uint8* output_data) {
...
      if (input_zeropoint[i] == output_zeropoint &&
          input_scale[i] == output_scale) {
        memcpy(output_ptr, input_ptr, copy_size);
      } else {
        const float scale = input_scale[i] * inverse_output_scale;
        const float bias = -input_zeropoint[i] * scale;
        for (int j = 0; j < copy_size; ++j) {
          const int32_t value =
              static_cast<int32_t>(std::round(input_ptr[j] * scale + bias)) +
              output_zeropoint;
          output_ptr[j] = static_cast<uint8_t>(
              std::max<int32_t>(std::min<int32_t>(255, value), 0));
        }
      }

**Standalone code to reproduce the issue** 
I have attached a tflite file that includes a concat op with different scaling/zeropoint in the Input/Output.

[concat_1x1x1x2048_requantize_6.zip](https://github.com/tensorflow/tensorflow/files/4325464/concat_1x1x1x2048_requantize_6.zip)

**Comment by suharshs** [comment]
This is a known issue with the uint8 kernel. The int8 version of this op (the tflite recommend official quantized kernel) does not have the rescale in the op, and is purely integer. 

What is your use case where the rescaling concatenation is causing an issue with the uint8 kernel. (note we are working on making all conversion of quantization-aware-training also output only the int8 kernels, so that may resolve your issue).

**Comment by liufengdb** [comment]
I changed the op spec of concat, so the uint8 scheme doesn't require same input/ouput scales anymore. Please check it again.

**Comment by yisongsong** [comment]
I'm wondering how to keep the same scaling/zeropoint in the Input/Output for int8.

**Comment by sushreebarsa** [comment]
@ppatrikg It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? Thanks!

**Comment by PINTO0309** [comment]
I'm still getting the same issue with v2.6.0-rc1.

**Comment by lolz0r** [comment]
I see it, too. On tfnightly==2.8.0-dev20211001

**Comment by wanghaoshuang** [comment]
@yisongsong 

>I'm wondering how to keep the same scaling/zeropoint in the Input/Output for int8.

Have you got the solution?

**Comment by yisongsong** [comment]
> @yisongsong
> 
> > I'm wondering how to keep the same scaling/zeropoint in the Input/Output for int8.
> 
> Have you got the solution?

You can refer to this [link](https://github.com/tensorflow/tensorflow/blob/d65ffd105c438ab6693e84243c6ab7b849bb3af8/tensorflow/lite/tools/optimize/quantize_model_test.cc#L425). It will check min/max for all inputs, and insert Quantize node for some inputs or all. 
```
// There are two inputs for concat, "input0" and "input1". "input0" has [0, 5]
// as min/max and "input1" has [0, 10] as min/max. The output "output" for
// concat has [0, 10] as min/max.
// After applyging QuantizeModel(), "input0" will have a requant op added, along
// with a tensor "input0_reqaunt" that has [0, 10] as min/max. So the topology
// becomes:
// input0 -> requant -> input0_requant \
//                                       concat - output
//                              input1 /
```

Also, tflite provide `HardcodeMinMaxForConcatenation()` to change min/max.
```
# Usage for this flag is --change_concat_input_ranges=true or
# --change_concat_input_ranges=false in order to make it clear what the flag
# is set to. This keeps the usage consistent with other usages of the flag
# where the default is different. The default value here is False.
parser.add_argument(
"--change_concat_input_ranges",
type=str.upper,
choices=["TRUE", "FALSE"],
help=("Boolean to change behavior of min/max ranges for inputs and "
     "outputs of the concat operator for quantized models. Changes the "
     "ranges of concat operator overlap when true. (default False)"))
```

**Comment by mohantym** [comment]
Hi @ppatrikg! 
We are checking to see whether you still need help in this issue . Did above [comment](https://github.com/tensorflow/tensorflow/issues/37544#issuecomment-971326816) work for you?
