### ISSUE TITLE
TF_FORCE_GPU_ALLOW_GROWTH=false Triggers cuDNN Error

### ISSUE THREAD

**Issue by michaelmyc** [tensorflow/tensorflow#37559]
**System information** 
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No, using tutorial classification example**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Manjaro (kernel 5.4.18)**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
- TensorFlow installed from (source or binary): **conda binary**
- TensorFlow version (use command below): **2.1.0**
- Python version: **3.7.6**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: **CUDA 10.1 / cuDNN 7.6.5**
- GPU model and memory: **RTX 2070, 8GB**

**Describe the current behavior**

Classification fail to train if `TF_FORCE_GPU_ALLOW_GROWTH` not set to true. It raises: 

`tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.`

I suspect cuDNN is asking for more memory after Tensorflow has already allocated all available memory. An easy but hacky fix is to set `TF_FORCE_GPU_ALLOW_GROWTH` to true by default and asking users to set it to false when they need max performance. It makes sense to ensure that the model would always run rather than ensuring that it would run with max efficiency. However, we should address this issue from the core. 

**Describe the expected behavior**

Model would train like when `TF_FORCE_GPU_ALLOW_GROWTH` is set to true. 

**Standalone code to reproduce the issue**

Run classification.ipynb on [the tutorial](https://www.tensorflow.org/tutorials/images/classification) without setting `TF_FORCE_GPU_ALLOW_GROWTH`. 

**Other info / logs** Include any logs or source code that would be helpful to

[error_log.txt](https://github.com/tensorflow/tensorflow/files/4328031/log.txt)

**Comment by 6etacat** [comment]
https://github.com/tensorflow/tensorflow/issues/9489#issuecomment-562394257
https://github.com/tensorflow/tensorflow/issues/24496#issuecomment-598145988

**Comment by Saduf2019** [comment]
@6etacat 
Could you please share the tensorflow version in which the error is faced.

**Comment by 6etacat** [comment]
@Saduf2019 Updated.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Comment by sanjoy** [comment]
Does setting the env var `TF_DEVICE_MIN_SYS_MEMORY_IN_MB` to to a high value (say 1000) fix the issue?  If yes, can you try finding the smallest value for this env var that works?  Once you have that figure, we can incorporate it into TensorFlow.

CC @nluehr
