### ISSUE TITLE
Two errors were raised when using mirrored strategy.

### ISSUE THREAD

**Issue by Crispy13** [tensorflow/tensorflow#37571]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): 
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): using conda
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: 10.1.243 / 7.6.5
- GPU model and memory: Tesla T4 16GB

```
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: Dec_VAE_VDraw_Var/Identity:0

During handling of the above exception, another exception occurred:
...
_SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'Dec_VAE_VDraw_Var/Identity:0' shape=(None, 128) dtype=float32>, <tf.Tensor 'Dec_VAE_VDraw_Mean/Identity:0' shape=(None, 128) dtype=float32>]

```
reproducible notebook files:
https://drive.google.com/file/d/1DzES68HT3-7dlrpH6oo13Q9MgybdjcGm/view?usp=sharing

When i didn't use mirrored strategy and added experimental_tf_function = False as an argument to model.compile, the errors were not raised.

It would be glad if you would help me to solve this errors.

**Comment by ccrusius** [comment]
Would it be possible to create a small Colab notebook that reproduces the issue?

**Comment by Crispy13** [comment]
> Would it be possible to create a small Colab notebook that reproduces the issue?

I know that google colab does not support multiple gpu. Does mirrored strategy work on one gpu?

**Comment by nikitamaia** [comment]
Hi @Crispy13, yes you can run MirroredStrategy with one GPU in colab and for this scenario I think we should be able to reproduce the error. If you are still facing this issue, please provide a colab notebook so we can help troubleshoot.
