### ISSUE TITLE
Keras model fit with class_weight fails on TPU but not on GPU

### ISSUE THREAD

**Issue by chris-clem** [tensorflow/tensorflow#37575]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04):  Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: Colab
- TensorFlow installed from (source or
binary): Colab
- TensorFlow version (use command below): 2.x in Colab
- Python version: Colab
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: Colab
- GPU model and memory: Colab

**Describe the current behavior**
If I use the `class_weight` argument during model.fit(...) with a TPU, I get the following error:
![image](https://user-images.githubusercontent.com/36116534/76622564-07b08300-6532-11ea-81a3-2027161014dc.png)

If I change the runtime type to GPU, the model fits fine.  

**Describe the expected behavior**
Defining  `class_weight` on TPU should not fail if it works on the GPU.

**Comment by Saduf2019** [comment]
@chris-clem 

Could you please share a simple stand alone code for us to replicate the issue faced by you.

Also please refer to these [link1](https://github.com/tensorflow/tpu/issues/236) and [link2](https://stackoverflow.com/questions/52906186/keras-tpu-compilation-failure-detected-unsupported-operations) if it helps you resolve the issue as per the error shared.

**Comment by chris-clem** [comment]
Yes, there you go: https://colab.research.google.com/drive/1beNMk03qGfGpcXwpHVLTnuGBTKQVREyV. It runs with GPU backend, but not with TPU.

**Comment by Saduf2019** [comment]
@chris-clem 
We will not be able to replicate the issue unless all dependencies are shared, please find  [the gist](https://colab.sandbox.google.com/gist/Saduf2019/50d630ae9c408686b9aafc0a3873ff44/untitled95.ipynb) of error faced by us.

**Comment by chris-clem** [comment]
The error in your gist comes from using Tensorflow version 1.15.0, right? I use 2.1.0. 
I created to gists:
- one with GPU backend: [keras-class-weight-gpu.ipynb](https://colab.research.google.com/gist/chris-clem/e6bf2a9b2b0da56a903b598eda80275c/keras-class-weight-gpu.ipynb)
- one with TPU backend: [keras-class-weight-tpu.ipynb](https://colab.research.google.com/gist/chris-clem/0c6644195fee5d944e80f04a3fd1b428/keras-class-weight-tpu.ipynb)

The GPU notebook runs in Colab, the TPU one throws this error:
![image](https://user-images.githubusercontent.com/36116534/76951693-5aac8080-690c-11ea-9b92-9597e08f2c0d.png)

**Comment by chris-clem** [comment]
Is there any update on this?

**Comment by armenabnousi** [comment]
I think this problem occurs only if class weight is input is a dictionary. If it's input as list it runs.

**Comment by jvishnuvardhan** [comment]
@chris-clem This was resolved with `tf-nightly` even for TPU. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/93e24a5043b797e0f47b641b5ead2723/keras-class-weight-tpu.ipynb). Thanks

Please verify it and close the issue if this was resolved for you. Thanks!

**Comment by jvishnuvardhan** [comment]
@chris-clem Can you please verify once and close the issue if this was resolved for you. Thanks!

**Comment by chris-clem** [comment]
Sorry for the delay. Yes it works, thank you!

Am 08.04.2020 um 03:01 schrieb Vishnuvardhan Janapati <notifications@github.com>:

﻿

@chris-clem<https://github.com/chris-clem> Can you please verify once and close the issue if this was resolved for you. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing this issue as this was resolved. Thanks!
