### ISSUE TITLE
tf.data.experimental.ignore_errors unintuitive behavior

### ISSUE THREAD

**Issue by Andreas5739738** [tensorflow/tensorflow#37573]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Mac OS 10.14
- TensorFlow installed from (source or
binary): pip install tensorflow
- TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de410 2.1.0
- Python version: 3.7.4

**Describe the current behavior**

When applying tf.data.experimental.ignore_errors() to a dataset which has been limited by take(), the error ignoring is applied before the take(). I.e., dataset.map(potential_error_source).take(N).apply(ignore_errors) always returns N elements. This is unintuitive, because according to the documentation "produce a dataset that contains the same elements as the input, but silently drops any elements that caused an error."

**Describe the expected behavior**

Expected behavior would be that dataset.map(potential_error_source).take(N).apply(ignore_errors) takes N elements, and then skips those that caused the error, i.e., resulting in <N elements in case there were errors. If that is not intended or cannot be implemented, at least the documentation should be updated to reflect that ignore_errors takes effect already at the point where the errors are raised.

**Standalone code to reproduce the issue** 

```
def generate():
         for i in range(1000):
             yield i

def map_fn(x):
    # raise assertion error for uneven numbers
    with tf.control_dependencies([tf.debugging.assert_equal(x % 2, 0)]):
         return x

dataset = tf.data.Dataset.from_generator(generate,output_types=tf.dtypes.int32).take(100)
len(list(iter(dataset)))
len(list(iter(dataset)))
# returns 100
dataset = tf.data.Dataset.from_generator(generate,output_types=tf.dtypes.int32).map(map_fn).take(100).apply(tf.data.experimental.ignore_errors())
len(list(iter(dataset)))
# returns 100
```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.1.0 ,2.2.0-dev20200316 and was able to reproduce the issue.Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/364ee68cbbcfd90658d7d06514c5d64b/untitled730.ipynb) Thanks!

**Comment by jsimsa** [comment]
This is working as intended, errors do not [count towards cardinality](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/take_dataset_op.cc#L117-L136).

**Comment by Andreas5739738** [comment]
If this is intended behavior, could this be clarified in the documentation? Thanks!

**Comment by Saduf2019** [comment]
@Andreas5739738 
As many updates have been made in latest version can you please check in the latest tf version and let us know.

**Comment by Andreas5739738** [comment]
Running the gist shared above (https://colab.sandbox.google.com/gist/ravikyram/364ee68cbbcfd90658d7d06514c5d64b/untitled730.ipynb) with TF 2.7 shows that the behavior of ignore_errors has not changed. The documentation (https://www.tensorflow.org/api_docs/python/tf/data/experimental/ignore_errors) has also not been updated to explain the observed behavior.

**Comment by SuryanarayanaY** [comment]
Hi @Andreas5739738 ,
I have some observations on the issue.

Your code: `tf.data.Dataset.from_generator(generate,output_types=tf.dtypes.int32).map(map_fn).take(100).apply(tf.data.experimental.ignore_errors())` returns 100 even elements as range(1000).Same code will return only 50 elements if range(100).

Instead if you change the `take(100)` like below with range(1000): `tf.data.Dataset.from_generator(generate,output_types=tf.dtypes.int32).take(100).map(map_fn).apply(tf.data.experimental.ignore_errors())` it will return 50 elements only. Please find the [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/5f4d8a7756f5b7318facd2af025d6bfc/37573.ipynb) here.

Also just to inform you the API [tf.data.experimental.ignore_errors()](https://www.tensorflow.org/api_docs/python/tf/data/experimental/ignore_errors) is deprecated.Use [tf.data.Dataset.ignore_errors](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#ignore_errors) instead in Future.
