### ISSUE TITLE
tf.train.FloatList() on a tensor takes too long

### ISSUE THREAD

**Issue by kpe** [tensorflow/tensorflow#37580]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: any
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 2.1.x, 1.5.x
- **Python version**: 3.7
- **Bazel version (if compiling from source)**: any
- **GCC/Compiler version (if compiling from source)**: any
- **CUDA/cuDNN version**: any
- **GPU model and memory**: any
- **Exact command to reproduce**: `tf.train.FloatList(value=tf.zeros(int(1e6)))`

### Describe the problem

Compare the execution time of those two lines:
```
feature = tf.train.FloatList(value=tf.zeros(int(1e6)).numpy())
```
```
feature = tf.train.FloatList(value=tf.zeros(int(1e6)))
```

The first one runs as it should, the second one takes ages to complete. (I guess something tries iterating over the tensor in the second case)

N.B. this is not specific to `FloatList` - its rather numpy vs Tensor value, evaluation something (I don't quite grasp the internals).

**Comment by Eshan-Agarwal** [comment]
I think numpy() `vectorizing`  it so it runs fast as compare of `tf.train.FloatList(value=tf.zeros(int(1e6)))`

**Comment by gowthamkpr** [comment]
I notice the difference in execution time between input being a numpy array and a tensor.

**Comment by sachinprasadhs** [comment]
I still see significant different with `numpy` array and `tensor` as input in `Tensorflow 2.6`, please find the [Gist](https://colab.research.google.com/gist/sachinprasadhs/f1c6c1f411cd6fe8d10abaefafff30ce/37580.ipynb) for reference.

**Comment by gowthamkpr** [comment]
This still persists in tensorflow 2.8.0

**Comment by mohantym** [comment]
@kpe !

I could replicate this issue in [2.9](https://colab.sandbox.google.com/gist/mohantym/9b7cd1432e4840ed3f2b04b9d5c01d9e/git_37580.ipynb#scrollTo=AE4uUz0AoJqD), [2.10](https://colab.sandbox.google.com/gist/mohantym/89387a3c699ce3804f3693c70f938357/git_37580.ipynb#scrollTo=YDqmyxfOmd1y) and [2.11](https://colab.sandbox.google.com/gist/mohantym/ae2a4e0b11714e58f65ba81f2bfb5a7c/git_37580.ipynb#scrollTo=LtPliQ0Pwbxy). 
Timing is slow even with Tensorflow.experimental.numpy api 
(50 % slower though when compared with tensors which are approx 4 times slow )

Thank you!
