### ISSUE TITLE
bug in C++ API "AddSymbolicGradients"

### ISSUE THREAD

**Issue by buaasun** [tensorflow/tensorflow#37593]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes 
- OS Platform and Distribution: CentOS Linux 7.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: Unknown
- TensorFlow installed from (source or binary):source 
- TensorFlow version (use command below): TF 2.0
- Python version:3.7 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 8.3
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the current behavior**
I build a graph, then call `AddSymbolicGradients` to generate gradients, but I found the order of generated gradients does not match inputs. My inputs are `[a,b]`, but the generated gradients are `[b_grad, a_grad]`
**Describe the expected behavior**
gradients order match inputs. Gradients of inputs `[a,b]` should be `[a_grad, b_grad]`

**My work to solve the problem** 
I checked the code in tensorflow/cc/framework/gradients.cc [L532](https://github.com/tensorflow/tensorflow/blob/07112a5c7e233989652ecac3184f0dd640e1462b/tensorflow/cc/framework/gradients.cc#L532) 
```c++
    size_t dx_index = 0;
    for (const Edge* e : n->in_edges()) {
      if (e->IsControlEdge()) continue;
      if (dx_index == dx.size()) {
        return errors::Internal(
            "Invalid gradient output index: ", dx_index, " size: ", dx.size());
      }
      TF_RETURN_IF_ERROR(
          BackpropAlongEdge(dx[dx_index++], {e->src(), e->src_output()}));
    }
```
I think `dx_index` in code should be `e->dst_input()`, because `in_edges() `returns a `unordered_set` which order is not match `dx`, the input index of edge is `dst_input()`.The right code may be:
```c++
for (const Edge* e : n->in_edges()) {
      if (e->IsControlEdge()) continue;
      int dx_index = e->dst_input();
      if (dx_index >= dx.size()) {
        return errors::Internal("Invalid gradient output index: ", dx_index, " size: ", dx.size());
      }
      TF_RETURN_IF_ERROR(BackpropAlongEdge(dx[dx_index], {e->src(), e->src_output()}));
    }
```

After I modified the code, my program seems works fine.

**Comment by Saduf2019** [comment]
@buaasun 
could you please provide us with simple stand alone code for us to replicate the issue faced by you.

**Comment by buaasun** [comment]
@Saduf2019 @gowthamkpr 
This error occurs with a low probability. `n->in_edges()` returns EdgeSet which contains `std::set<Edge*>`, so `in_edges` are ordered by the pointer of Edge. In most cases, pointers are allocated sequentially, so it works. But when executed many times, the error occurs randomly.

I write a simple unit test as below.
```c++

#include "tensorflow/cc/client/client_session.h"
#include "tensorflow/cc/framework/grad_op_registry.h"
#include "tensorflow/cc/framework/gradients.h"
#include "tensorflow/cc/framework/testutil.h"
#include "tensorflow/cc/ops/standard_ops.h"
#include "tensorflow/core/framework/graph.pb.h"
#include "tensorflow/core/framework/node_def_util.h"
#include "tensorflow/core/framework/tensor_testutil.h"
#include "tensorflow/core/lib/core/status_test_util.h"
#include "tensorflow/core/platform/test.h"

namespace tensorflow {
namespace {
using namespace ops;

class GradientsTest : public ::testing::Test {
 protected:
  GradientsTest() {}

  void TestSingle(const Scope& scope) {
    int N = 5 + rand() % 10;
    // Construct forward graph.
    OutputList inputs;
    for (int i = 0; i < N; ++i) {
      auto a = Const(scope, i, {1});
      inputs.push_back(a);
    }

    auto pack = Stack(scope, inputs);
    TF_ASSERT_OK(scope.status());

    // Construct grad inputs.
    OutputList output_grads;
    Tensor ts(DT_INT32, {N, 1});
    auto v = ts.matrix<int32>();
    for (int i = 0; i < N; ++i) {
      v(i, 0) = i;
    }
    auto dy = Const(scope, ts);
    output_grads.push_back(dy);
    // Call AddSymbolicGradients.
    std::vector<Output> grad_outputs;
    TF_ASSERT_OK(AddSymbolicGradients(scope, {pack.output}, inputs, output_grads, &grad_outputs));
    ClientSession session((scope));
    std::vector<Tensor> in_grad;
    TF_ASSERT_OK(session.Run(grad_outputs, &in_grad));
    for (int i = 0; i < N; ++i) {
      test::ExpectTensorEqual<int>(in_grad[i], test::AsTensor<int>({i}, {1}));
    }
  }
};
TEST_F(GradientsTest, SubScopeTest) {
  Scope scope = Scope::NewRootScope();
  for (int cnt = 0; cnt < 1000; ++cnt) {
    LOG(INFO) << cnt;
    TestSingle(scope.NewSubScope(std::to_string(cnt)));
  }
}

}  // namespace
}  // namespace tensorflow
```
As in code, the test run 1000 cnts, above 5 of them failed.

**Comment by skye** [comment]
I don't work on TF anymore, sorry!

**Comment by saxenasaurabh** [comment]
Thanks for debugging this! Your proposal looks good. Would you like to send a PR for the fix?
