### ISSUE TITLE
2.2.0-rc1 aarch64 crosscompile build failed

### ISSUE THREAD

**Issue by openedev** [tensorflow/tensorflow#37598]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: ARM64 development board
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.2.0-rc1
- Python version: 3.8
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): buildroot
- CUDA/cuDNN version: none
- GPU model and memory: none

**Describe the problem**

Build failing due to missing value for mandatory attribute 'toolchain_config' in 'cc_toolchain' rule.

Followed the instructurons from [tensorflow-aarch64-crossbuild](https://github.com/xifengcun/tensorflow-aarch64-crossbuild) and update the changes as [tensorflow-2.2.0-rc1-aarch64-crossbuild](https://gist.github.com/openedev/7f7cb16af644d09f11fc49f42cbc2de9)

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Below is my sample makefile

PYTHON_TENSORFLOW_CONF_ENV += \
        PYTHON_BIN_PATH=$(HOST_DIR)/bin/python3 \
        PYTHON_LIB_PATH=$(HOST_DIR)/lib/python3.8/site-packages \
        TF_NEED_OPENCL_SYCL=y \
        HOST_CXX_COMPILER=$(HOST_DIR)/bin/aarch64-buildroot-linux-gnu-g++ \
        HOST_C_COMPILER=$(HOST_DIR)/bin/aarch64-buildroot-linux-gnu-gcc \
        TF_NEED_COMPUTECPP=N \
        TF_NEED_OPENCL_SYCL=N \
        TF_NEED_ROCM=N \
        TF_NEED_CUDA=N \
        TF_DOWNLOAD_CLANG=N \
        CC_OPT_FLAGS="-march=armv8-a" \
        TF_SET_ANDROID_WORKSPACE=N

define PYTHON_TENSORFLOW_CONFIGURE_CMDS
        (cd $(@D); \
                export PATH=$(HOST_DIR)/bin:$(PATH); \
                $(PYTHON_TENSORFLOW_CONF_ENV) \
                $(SHELL) ./configure \
        )
endef

define PYTHON_TENSORFLOW_BUILD_CMDS
        (cd $(@D); \
                $(HOST_DIR)/bin/bazel build --crosstool_top=//aarch64-compiler:toolchain --cpu=aarch64 --config=opt //tensorflow/tools/pip_package:build_pip_package \
        )
endef

**Any other info / logs**

(cd /mnt/br/output/build/python-tensorflow-2.2.0-rc0; /mnt/br/output/host/bin/bazel build --crosstool_top=//aarch64-compiler:toolchain --cpu=aarch64 --config=opt //tensorflow/tools/pip_package:build_pip_package )
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=91
INFO: Reading rc options for 'build' from /mnt/br/output/build/python-tensorflow-2.2.0-rc0/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /mnt/br/output/build/python-tensorflow-2.2.0-rc0/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from /mnt/br/output/build/python-tensorflow-2.2.0-rc0/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/mnt/br/output/host/bin/python3 --action_env PYTHON_LIB_PATH=/mnt/br/output/host/lib/python3.8/site-packages --python_path=/mnt/br/output/host/bin/python3 --config=xla --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file /mnt/br/output/build/python-tensorflow-2.2.0-rc0/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /mnt/br/output/build/python-tensorflow-2.2.0-rc0/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:opt in file /mnt/br/output/build/python-tensorflow-2.2.0-rc0/.tf_configure.bazelrc: --copt=-march=armv8-a --host_copt=-march=native --define with_default_optimizations=true
INFO: Found applicable config definition build:linux in file /mnt/br/output/build/python-tensorflow-2.2.0-rc0/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /mnt/br/output/build/python-tensorflow-2.2.0-rc0/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
ERROR: /mnt/br/output/build/python-tensorflow-2.2.0-rc0/aarch64-compiler/BUILD:15:1: //aarch64-compiler:cc-compiler-aarch64: missing value for mandatory attribute 'toolchain_config' in 'cc_toolchain' rule
INFO: Call stack for the definition of repository 'lmdb' which is a tf_http_archive (rule definition at /mnt/br/output/build/python-tensorflow-2.2.0-rc0/third_party/repo.bzl:134:19):
 - /mnt/br/output/build/python-tensorflow-2.2.0-rc0/tensorflow/workspace.bzl:618:5
 - /mnt/br/output/build/python-tensorflow-2.2.0-rc0/WORKSPACE:19:1
ERROR: /mnt/br/output/build/python-tensorflow-2.2.0-rc0/aarch64-compiler/BUILD:15:1: Target '//aarch64-compiler:aarch64_linux_all_files' contains an error and its package is in error and referenced by '//aarch64-compiler:cc-compiler-aarch64'
ERROR: /mnt/br/output/build/python-tensorflow-2.2.0-rc0/aarch64-compiler/BUILD:15:1: Target '//aarch64-compiler:empty' contains an error and its package is in error and referenced by '//aarch64-compiler:cc-compiler-aarch64'
ERROR: /mnt/br/output/build/python-tensorflow-2.2.0-rc0/aarch64-compiler/BUILD:3:1: Target '//aarch64-compiler:cc-compiler-aarch64' contains an error and its package is in error and referenced by '//aarch64-compiler:toolchain'
ERROR: /root/.cache/bazel/_bazel_root/e6c5c285cc2a992859afbeeed0c80f12/external/bazel_tools/src/tools/launcher/BUILD:9:1: every rule of type cc_binary implicitly depends upon the target '//aarch64-compiler:toolchain', but this target could not be found because of: Target '//aarch64-compiler:toolchain' contains an error and its package is in error
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.151s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)

**Comment by angerson** [comment]
We don't provide official support for cross-compiling like this, sorry. If you can replicate this on master without cross-compiling, please file a new issue.
