### ISSUE TITLE
ERROR: C:/tensorflow/tensorflow/core/kernels/BUILD:7897:1: C++ compilation of rule '//tensorflow/core/kernels:mkl_conv_op' failed (Exit 2)

### ISSUE THREAD

**Issue by Expert73** [tensorflow/tensorflow#37594]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): git
- TensorFlow version: r 2.2
- Python version: 3.7
- Installed using virtualenv? pip? conda?: conda intel 3.7
- Bazel version (if compiling from source): 2.0
- GCC/Compiler version (if compiling from source): VS 2019
- CUDA/cuDNN version: 10.2
- GPU model and memory: Nvidia 1070 ti

**Describe the problem**
build error
**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel --output_base=c:/bazel/output_dir/ build --config=mkl --config=opt --config=cuda -- //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
ERROR: C:/tensorflow/tensorflow/core/kernels/BUILD:7897:1: C++ compilation of rule '//tensorflow/core/kernels:mkl_conv_op' failed (Exit 2)
.\tensorflow/core/util/mkl_util.h(1263): error C2131: expression did not evaluate to a constant
.\tensorflow/core/util/mkl_util.h(1262): note: failure was caused by a read of a variable outside its lifetime
.\tensorflow/core/util/mkl_util.h(1262): note: see usage of 'dim'
.\tensorflow/core/util/mkl_util.h(1264): error C2131: expression did not evaluate to a constant
.\tensorflow/core/util/mkl_util.h(1262): note: failure was caused by a read of a variable outside its lifetime
.\tensorflow/core/util/mkl_util.h(1262): note: see usage of 'dim'
.\tensorflow/core/util/mkl_util.h(1266): error C3863: array type 'dnnl_dim_t [kNumDims]' is not assignable
.\tensorflow/core/util/mkl_util.h(1267): error C3863: array type 'dnnl_dim_t [kNumDims]' is not assignable
.\tensorflow/core/kernels/mkl_conv_ops.h(157): error C2679: binary '=': no operator found which takes a right-hand operand of type 'std::vector<long,std::allocator<long>>' (or there is no acceptable conversion)
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(1176): note: could be 'std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>>::operator =(std::initializer_list<_Ty>)'
        with
        [
            _Ty=dnnl::memory::dim
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(1168): note: or       'std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>>::operator =(const std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &)'
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(665): note: or       'std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>>::operator =(std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &&) noexcept(<expr>)'
.\tensorflow/core/kernels/mkl_conv_ops.h(157): note: while trying to match the argument list '(dnnl::memory::dims, std::vector<long,std::allocator<long>>)'
.\tensorflow/core/kernels/mkl_conv_ops.h(182): error C2679: binary '=': no operator found which takes a right-hand operand of type 'std::vector<long,std::allocator<long>>' (or there is no acceptable conversion)
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(1176): note: could be 'std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>>::operator =(std::initializer_list<_Ty>)'
        with
        [
            _Ty=dnnl::memory::dim
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(1168): note: or       'std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>>::operator =(const std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &)'
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(665): note: or       'std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>>::operator =(std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &&) noexcept(<expr>)'
.\tensorflow/core/kernels/mkl_conv_ops.h(182): note: while trying to match the argument list '(dnnl::memory::dims, std::vector<long,std::allocator<long>>)'
.\tensorflow/core/kernels/mkl_conv_ops.h(246): error C2679: binary '=': no operator found which takes a right-hand operand of type 'std::vector<long,std::allocator<long>>' (or there is no acceptable conversion)
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(1176): note: could be 'std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>>::operator =(std::initializer_list<_Ty>)'
        with
        [
            _Ty=dnnl::memory::dim
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(1168): note: or       'std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>>::operator =(const std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &)'
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(665): note: or       'std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>>::operator =(std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &&) noexcept(<expr>)'
.\tensorflow/core/kernels/mkl_conv_ops.h(246): note: while trying to match the argument list '(dnnl::memory::dims, std::vector<long,std::allocator<long>>)'
.\tensorflow/core/kernels/mkl_conv_ops.h(254): error C2679: binary '=': no operator found which takes a right-hand operand of type 'std::vector<long,std::allocator<long>>' (or there is no acceptable conversion)
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(1176): note: could be 'std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>>::operator =(std::initializer_list<_Ty>)'
        with
        [
            _Ty=dnnl::memory::dim
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(1168): note: or       'std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>>::operator =(const std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &)'
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(665): note: or       'std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>>::operator =(std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &&) noexcept(<expr>)'
.\tensorflow/core/kernels/mkl_conv_ops.h(254): note: while trying to match the argument list '(dnnl::memory::dims, std::vector<long,std::allocator<long>>)'
.\tensorflow/core/kernels/mkl_conv_ops.h(283): error C2679: binary '=': no operator found which takes a right-hand operand of type 'std::vector<long,std::allocator<long>>' (or there is no acceptable conversion)
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(1176): note: could be 'std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>>::operator =(std::initializer_list<_Ty>)'
        with
        [
            _Ty=dnnl::memory::dim
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(1168): note: or       'std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>>::operator =(const std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &)'
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(665): note: or       'std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>>::operator =(std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &&) noexcept(<expr>)'
.\tensorflow/core/kernels/mkl_conv_ops.h(283): note: while trying to match the argument list '(dnnl::memory::dims, std::vector<long,std::allocator<long>>)'
.\tensorflow/core/kernels/mkl_conv_ops.h(474): error C2679: binary '=': no operator found which takes a right-hand operand of type 'std::vector<long,std::allocator<long>>' (or there is no acceptable conversion)
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(1176): note: could be 'std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>>::operator =(std::initializer_list<_Ty>)'
        with
        [
            _Ty=dnnl::memory::dim
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(1168): note: or       'std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>>::operator =(const std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &)'
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(665): note: or       'std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>>::operator =(std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &&) noexcept'
.\tensorflow/core/kernels/mkl_conv_ops.h(474): note: while trying to match the argument list '(dnnl::memory::dims, std::vector<long,std::allocator<long>>)'
.\tensorflow/core/kernels/mkl_conv_ops.h(482): error C2679: binary '=': no operator found which takes a right-hand operand of type 'std::vector<long,std::allocator<long>>' (or there is no acceptable conversion)
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(1176): note: could be 'std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>>::operator =(std::initializer_list<_Ty>)'
        with
        [
            _Ty=dnnl::memory::dim
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(1168): note: or       'std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>>::operator =(const std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &)'
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\vector(665): note: or       'std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>>::operator =(std::vector<dnnl::memory::dim,std::allocator<dnnl::memory::dim>> &&) noexcept'
.\tensorflow/core/kernels/mkl_conv_ops.h(482): note: while trying to match the argument list '(dnnl::memory::dims, std::vector<long,std::allocator<long>>)'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 2360.878s, Critical Path: 182.60s
INFO: 3346 processes: 3346 local.
FAILED: Build did NOT complete successfully

**Comment by ya-mouse** [comment]
I have the same issue on v2.2.0-rc2, was it fixed?

**Comment by Expert73** [comment]
Антон, пошаговое решение тут
https://github.com/tensorflow/tensorflow/issues/37430
