### ISSUE TITLE
TF Lite OpenCL Input Tensors Same Address

### ISSUE THREAD

**Issue by guydavid** [tensorflow/tensorflow#37597]
This is already fixed in master (https://github.com/tensorflow/tensorflow/commit/8685cf97d568855f3e7cf194d7e370bb71c51c73#diff-49796db7c3f71b9c25c7837d9ee16abf), however I thought it's appropriate to report it nonetheless if anyone else encounters it.

Before the fix, the inputs of a model with three or more inputs were not copied correctly because some of them shared the same memory address in the context of OpenCL.

**Comment by jvishnuvardhan** [comment]
@guydavid Is there anything you want to update in the docs so that others will get benefited. If there is no further action related to this issue, then please close the issue as the issue got fixed in `master`. Thanks!
