### ISSUE TITLE
LSTMFusedCell ops only running on CPU

### ISSUE THREAD

**Issue by mschonwe** [tensorflow/tensorflow#3759]
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN: 8.0.27 and v5
394472 Jul 26 13:26 /usr/local/cuda/lib64/libcudart.so.8.0.27
78065952 Jul 26 13:33 /usr/local/cuda/lib64/libcudnn.so.5.0.5

1. TF commit : c5f94b10bbb30e525fa3ca313e7ccb173040c90a
2. bazel version :  0.3.0

We switched over a working Seq2Seq model to use the LSTMFusedCell (previously GRUCell).  The graph build is a lot faster, but the step times are slower.

By profiling the ops (using timeline to generate a chrome trace file) we discovered that most of the processing was occurring on the GPU, as specified, but the LSTMFusedCell ops were all running on the CPU.

There may be a known issue, as referenced by @wchan in #2002  - however that PR is closed.

**Comment by girving** [comment]
@ebrevdo Is there a plan for GPU `LSTMFusedCell`?

**Comment by ebrevdo** [comment]
This should be fixed as of ~1 week ago (it always supported GPU, but due to a weird bug we were not compiling it for nvcc).  And today/tomorrow this cell is being renamed to LSTMBlockCell.  Please let us know if it still does not work with GPU for you.

**Comment by ebrevdo** [comment]
If this is fixed for you, please close the bug.

**Comment by ebrevdo** [comment]
(please use the tensorflow nightly to ensure you're using a fixed version of this Cell)

**Comment by ebrevdo** [comment]
The TF commit you're using is ~4 commits too early!  This was fixed in [this commit](https://github.com/tensorflow/tensorflow/commit/c5b3ea14c0fc93032a8d31afa4546d7add1ed25e).

**Comment by mschonwe** [comment]
Yes, it is fixed with the new code!  I was looking for a mention of LSTMFused in the commits and didn't realize that commit addressed this issue.  Very nice to have a compact graph and faster step times. Thank you very much!

**Comment by ebrevdo** [comment]
FYI we're renaming them to LSTMBlockCell.
