### ISSUE TITLE
undefined symbol: clock_gettime with tensorflow on ubuntu14.04

### ISSUE THREAD

**Issue by longhf** [tensorflow/tensorflow#376]
I have posted my problem on stackoverflow.
http://stackoverflow.com/questions/33980109/undefined-symbol-clock-gettime-with-tensorflow-on-ubuntu14-04

**Comment by markusdr** [comment]
See also this issue, incl. fix: https://github.com/tensorflow/tensorflow/issues/121

**Comment by vrv** [comment]
Let us know if @markusdr's fix doesn't work -- otherwise feel free to reopen #121

**Comment by longhf** [comment]
Sorry to reply so late.My laptop is very slow in building and it lasts for a very long time.Fortunately,now I can import tensorflow.@markusdr's fix works.Thanks a lot.
