### ISSUE TITLE
need custom implementations: NonMaxSuppressionV5

### ISSUE THREAD

**Issue by HLearning** [tensorflow/tensorflow#37608]
**System information**
- Linux Ubuntu 18.04
- TensorFlow installed from binary
- TensorFlow 2.1

**Provide the text output from tflite_convert**

```
Here is a list of operators for which you will need custom implementations: NonMaxSuppressionV5.
```

**Comment by amahendrakar** [comment]
@HLearning,
Could you please check [this](https://github.com/tensorflow/tensorflow/issues/35449#issuecomment-570318723) comment from a similar issue and let us know if it works? Thanks!

**Comment by amahendrakar** [comment]
Any updates regarding this issue? Thanks!

**Comment by HLearning** [comment]
thanks, solved
