### ISSUE TITLE
Lots of links are Broken.

### ISSUE THREAD

**Issue by abhinavsp0730** [tensorflow/tensorflow#37607]
## URL(s) with the issue:  
https://github.com/tensorflow/docs/blob/r2.0/site/en/api_docs/python/index.md
## Description of the issue (what needs changing):
There are lots of links are broken, some of them are:
https://github.com/tensorflow/docs/blob/r2.0/site/en/api_docs/python/tf/dtypes/DType
https://github.com/tensorflow/docs/blob/r2.0/site/en/api_docs/python/tf/data/experimental/get_structure
https://github.com/tensorflow/docs/blob/r2.0/site/en/api_docs/python/tf/debugging/assert_same_float_dtype
https://github.com/tensorflow/docs/blob/r2.0/site/en/api_docs/python/tf/estimator/ModeKeys
https://github.com/tensorflow/docs/blob/r2.0/site/en/api_docs/python/tf/fill

### Clear description
There are lots of the link is broken in r2.0/site/en/api_docs/python/index.md. when someone clicks on these links it's showing 404 ERROR.

## Solution 
When I checked  https://www.tensorflow.org/versions/r2.0/api_docs/python . I found out every links
are correct. For example
* tf.DType link is broken in Github but working fine in TensorFlow website
As the numbers of broken links are big. I'll suggest adding a message like
" Our TensorFlow 2.0 RC docs is moved to https://www.tensorflow.org/versions/r2.0/api_docs/python. Kindly checkout there"
I have seen this type of message in some of the TensorFlow docs.
## Pull Request
Hey, @dynamicwebpaige , @lamberta, @MarkDaoust  . Please assign me for doing this. I'll love to address this issue.

**Comment by Eshan-Agarwal** [comment]
@abhinavsp0730  Yes there are lot of broken links, because they removed API GitHub. Maybe you can remove all links. As members add  links automatically when the website documentation gets generated.

**Comment by saahiluppal** [comment]
As major migration occurs from one version to another. Lots of links get broken. They soon will be deleted or replaced ones documentation gets updated.

**Comment by abhinavsp0730** [comment]
Hey, @MarkDaoust any updates on this?

**Comment by MarkDaoust** [comment]
I'm going to have to add the snap-shot for TF2.1 when TF2.2 goes up. 'll take a look then.

**Comment by abhinavsp0730** [comment]
Okay,
thanks, so can I now close this issue?

**Comment by jvishnuvardhan** [comment]
@abhinavsp0730 All the links are working in the current page https://github.com/tensorflow/docs/blob/r2.0/site/en/api_docs/python/index.md

Please verify once and close the issue if this was resolved for you. Thanks!
