### ISSUE TITLE
Mixed Precision with tf.distribute

### ISSUE THREAD

**Issue by lminer** [tensorflow/tensorflow#37602]
It doesn't appear that mixed precision currently works with tf.distribute. Are there plans to add this soon?

**Comment by reedwm** [comment]
Can you clarify and give an example to reproduce? The Keras mixed precision API should work with tf.distribute, as well as doing mixed precision with manual casts.

**Comment by lminer** [comment]
@reedwm I'll investigate more. Does it matter what order mixed precision and tf.distribute are run in? right now I'm doing:
```python
strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
    policy = tf.keras.mixed_precision.experimental.Policy('mixed_float16')
    tf.keras.mixed_precision.experimental.set_policy(policy)
    build model, fit, etc.
```

**Comment by reedwm** [comment]
It doesn't matter. All that matters is that you set the policy before building the model.

**Comment by reedwm** [comment]
Closing for now since mixed precision should work with MirroredStrategy. Please reopen or file a new issue if you still have an issue.
