### ISSUE TITLE
Output 0 of type variant does not match declared output type int64 for node node IteratorGetNext

### ISSUE THREAD

**Issue by tordsae** [tensorflow/tensorflow#37600]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Standard setup for gcp kubeflow and notebook as in https://www.tensorflow.org/tfx/tutorials/tfx/cloud-ai-platform-pipelines

Trying a pipeline with keras model to estimator method. Similar to the one in https://github.com/tensorflow/tfx/blob/r0.21/tfx/examples/iris/iris_utils.py, but for a simple autoencoder for 1 feature.

**Current behavior**
When the pipeline tries to save checkpoint I get the error:
https://github.com/tensorflow/tfx/blob/r0.21/tfx/examples/iris/iris_utils.py

Output 0 of type variant does not match declared output type int64 for node node IteratorGetNext

**Comment by gadagashwini** [comment]
@tordsae, This issue is more related to TFX, can you raise this issue in [TFX](https://github.com/tensorflow/tfx/issues) repository. Thanks!
