### ISSUE TITLE
Not able to import tensorflow 

### ISSUE THREAD

**Issue by Rakesh096** [tensorflow/tensorflow#37612]
**System information**
(tensorflow_cpu) C:\Users\Rakes>conda list
# packages in environment at C:\Users\Rakes\.conda\envs\tensorflow_cpu:
#
# Name                    Version                   Build  Channel
absl-py                   0.9.0                    pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
blas                      1.0                         mkl
ca-certificates           2020.1.1                      0
cachetools                4.0.0                    pypi_0    pypi
certifi                   2019.11.28               pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
gast                      0.2.2                    pypi_0    pypi
google-auth               1.11.3                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.27.2                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
icc_rt                    2019.0.0             h0cc432a_1
idna                      2.9                      pypi_0    pypi
intel-openmp              2020.0                      166
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
markdown                  3.2.1                    pypi_0    pypi
mkl                       2020.0                      166
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.0.15           py37h14836fe_0
mkl_random                1.1.0            py37h675688f_0
numpy                     1.18.1                   pypi_0    pypi
numpy-base                1.18.1           py37hc3f5095_1
oauthlib                  3.1.0                    pypi_0    pypi
openssl                   1.1.1d               he774522_4
opt-einsum                3.2.0                    pypi_0    pypi
pip                       20.0.2                   py37_1
protobuf                  3.11.3                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
python                    3.7.6                h60c2a47_2
requests                  2.23.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.0                      pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
setuptools                46.0.0                   pypi_0    pypi
six                       1.14.0                   py37_0
sqlite                    3.31.1               he774522_0
tensorboard               2.1.1                    pypi_0    pypi
tensorflow                2.1.0                    pypi_0    pypi
tensorflow-cpu            2.1.0                    pypi_0    pypi
tensorflow-estimator      2.1.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
urllib3                   1.25.8                   pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
werkzeug                  1.0.0                    pypi_0    pypi
wheel                     0.34.2                   pypi_0    pypi
wincertstore              0.2                      py37_0
wrapt                     1.12.1                   pypi_0    pypi

(tensorflow_cpu) C:\Users\Rakes>conda info

     active environment : tensorflow_cpu
    active env location : C:\Users\Rakes\.conda\envs\tensorflow_cpu
            shell level : 2
       user config file : C:\Users\Rakes\.condarc
 populated config files : C:\Users\Rakes\.condarc
          conda version : 4.8.2
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       virtual packages :
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\Rakes\.conda\pkgs
                          C:\Users\Rakes\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Rakes\.conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\Rakes\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

Commands used to install tensorflow pip install --upgrade tensorflow

### **Import TensorFlow not working **

`(tensorflow_cpu) C:\Users\Rakes>python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
Traceback (most recent call last):
  File "C:\Users\Rakes\.conda\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Rakes\.conda\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Rakes\.conda\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Rakes\.conda\envs\tensorflow_cpu\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Rakes\.conda\envs\tensorflow_cpu\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Rakes\.conda\envs\tensorflow_cpu\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\Rakes\.conda\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Rakes\.conda\envs\tensorflow_cpu\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\Rakes\.conda\envs\tensorflow_cpu\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\Rakes\.conda\envs\tensorflow_cpu\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Rakes\.conda\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Rakes\.conda\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Rakes\.conda\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Rakes\.conda\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Rakes\.conda\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Rakes\.conda\envs\tensorflow_cpu\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Rakes\.conda\envs\tensorflow_cpu\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.`

**Comment by mihaimaruseac** [comment]
Closing as duplicate. Please do some work in the future on these issues (formatting of error/code blocks, search for similar issues)

https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
