### ISSUE TITLE
No documentation on how to convert Session.run calls to tf.function calls

### ISSUE THREAD

**Issue by nhubbard** [tensorflow/tensorflow#37617]
## URL(s) with the issue:

* https://www.tensorflow.org/guide/migrate#1_replace_v1sessionrun_calls

## Description of issue (what needs changing):

There is no information provided to the end-user on how to convert simple `Session.run` calls into `tf.function` calls for TensorFlow 2. For people who are only interested in running saved models and not building their own architectures, the lack of information makes it difficult to fully migrate away from TensorFlow 1.x.

### Clear description

If I am doing a SavedModel-based system with TensorFlow 1.x (I was provided the model, I did not make the model), there should be a direct explanation of how to convert `Session.run` calls into more modern `tf.function` calls. Here is an example of the code I'm trying to convert to TensorFlow 2, but I can't complete the conversion because of a lack of documentation for this use case:

```python
with tf.Session(graph=tf.Graph()) as sess:
    tf.saved_model.loader.load(sess, ["serve"], path_to_model)
    cap = cv2.VideoCapture(camera_id)
    ret, frame = cap.read()
    ret, encoded = cv2.imencode(".jpg", frame)
    inferred = sess.run(["detection_scores:0", "detection_boxes:0"], feed_dict={
        "encoded_image_string_tensor:0": [encoded.tobytes(),]
    })
```

Essentially, I'm looking for a piece of documentation with code equivalency for these sort of examples.

### Correct links

***Not applicable***

### Parameters defined

***Not applicable***

### Returns defined

***Not applicable***

### Raises listed and defined

***Not applicable***

### Usage example

***Not applicable***

### Request visuals, if applicable

***Not applicable***

### Submit a pull request?

I can't submit a pull request because of the lack of documentation on the issue at hand. I could, however, submit a pull request to resolve the problem once I know how to resolve the problem.

**Comment by nikitamaia** [comment]
Closing this issue as the examples were updated in https://github.com/tensorflow/docs/commit/705f63013e7f26ba6052e90ea3836153a47406c6
