### ISSUE TITLE
[tflite][java] has_rank_one_input_condition error when use runForMultipleInputsOutputs()

### ISSUE THREAD

**Issue by aruno14** [tensorflow/tensorflow#37626]
I obtain an error when use two inputs in runForMultipleInputsOutputs().

**System information** 
- Custom code
- Android API 29
- Android simulator
- Used libraries:
-- org.tensorflow:tensorflow-lite:2.1.0
-- org.tensorflow:tensorflow-lite-gpu:2.1.0
-- org.tensorflow:tensorflow-lite-support:0.0.0-nightly

- Used model information
[The model tolite file](https://github.com/tensorflow/tensorflow/files/4336843/classifier_lstm2.tflite.zip)

[{'name': 'input_1', 'index': 0, 'shape': array([ 1, 10], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}, {'name': 'input_2', 'index': 1, 'shape': array([1, 2], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]

```
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            [(None, 10)]         0                                            
__________________________________________________________________________________________________
embedding_1 (Embedding)         (None, 10, 256)      15616       input_1[0][0]                    
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, 2)]          0                                            
__________________________________________________________________________________________________
lstm_1 (LSTM)                   (None, 256)          525312      embedding_1[0][0]                
__________________________________________________________________________________________________
concatenate (Concatenate)       (None, 258)          0           input_2[0][0]                    
                                                                 lstm_1[0][0]                     
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 61)           15799       concatenate[0][0]                
==================================================================================================
```

**The error**
```
java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: tensorflow/lite/kernels/select.cc:80 data->has_rank_one_input_condition was not true.
Node number 23 (SELECT) failed to prepare.
Node number 19 (WHILE) failed to invoke.
```

**The code**

```
MappedByteBuffer tfliteModelCaption = FileUtil.loadMappedFile(activity, "classifier_caption.tflite");
Interpreter.Options options = new Interpreter.Options();
Interpreter tflite = new Interpreter(tfliteModelCaption, options);
float[][] inputString = new float[1][10];
inputString[0][9] = 4;
float[][] inputData = new float[1][2];
inputData[0][0] = 0;
inputData[0][1] = 1;
Object[] inputArray = {inputString, inputData};
Map<Integer, Object> outputMap = new HashMap<>();
outputMap.put(0, new float[1][61]);
tflite.runForMultipleInputsOutputs(inputArray, outputMap);
tflite.close();
float[] result = ((float[][]) outputMap.get(0))[0];
textViewAge.setText("Test: " + Arrays.toString(result));
```

The error seems to means the shape of the inputs does not fit the model input, but I checked it many time and for me it looks the same. I create a similar model with only one input (no input_2)  and I can use it without error.

**Comment by Saduf2019** [comment]
@aruno14 
could you please share a simple stand alone code for us to replicate the error faced in our local, if possible please share a colab gist of the same.

**Comment by aruno14** [comment]
@Saduf2019 Thank you for your response.
I created a simple project and put it on GitHub.
https://github.com/aruno14/TensorflowLiteTest

**Comment by Saduf2019** [comment]
@aruno14 
we will not be able to replicate issue, with this project. please share a simple stand alone code or if possible colab gist for us to analyse the issue faced.

**Comment by jvishnuvardhan** [comment]
@aruno14 few questions.
1.Are you using two different models? 
2. Can you please describe the steps you followed before noticing this error? 
3. Did you build a model with single input, converted to `tf-lite` format and then tested the model. Then, the same procedure was followed in developing model with two inputs. Is this what you followed? 
Thanks!

**Comment by aruno14** [comment]
@jvishnuvardhan Thank you for your reply.
- 1.Are you using two different models?
In the code I shared I use only one model. In order to check the code, I created an other similar model with only one input, (the input_1). Then, I used the same code, I used runForMultipleInputsOutputs with one input and it executes without error.
- 2.Can you please describe the steps you followed before noticing this error?
I have an android application using tflite. It uses several models for sex and age recognition using one image as input. The code works well.
Then I create a model to generate image description using LSTM. In this model there are two inputs, the image (image representation) and the previous words. I can use it in local (in python) but when I tried to used it in android I got an error. Then I tried the below models to find the error:
- - a simple LSTM model -> no error
- - a model with LSTM and two simple inputs: 
- - - vector representing the string
- - - a vector [0, 1] or [1, 0]
- - -> error
- - a model with two inputs of same shape -> error
- 3.what commands you used to converter your model to tf_lite model?
I used the below code with the version 2.1.0 of tensorflow.
```
converter = tf.lite.TFLiteConverter.from_saved_model("<model_folder>")
converter.experimental_new_converter = True
tfmodel = converter.convert()
open(args.output , "wb").write(tfmodel)
interpreter= tf.lite.Interpreter("<tflite_model_name>")
print(interpreter.get_input_details())
```
I cannot convert the model using experimental_new_converter = False
- 4.Did you build a model with single input, converted to tf-lite format and then tested the model.
Yes, I did.
- Then, the same procedure was followed in developing model with two inputs. Is this what you followed?
Yes.

**Comment by jdduke** [comment]
> float[][] inputData = new float[1][2];

The model is expecting an input of shape [1, 10], but you've provided a shape of [1, 2].

**Comment by aruno14** [comment]
I am sorry, on the GitHub repository the code was not correct. I corrected it.
But I get the same error with [1, 10] or [1, 2].
In order to be sure of the model inputs I added the below output:
```
"Test: " + tflite.getInputTensorCount()
   + " - " + tflite.getInputTensor(0).name() + ":" + Arrays.toString(tflite.getInputTensor(0).shape()) + ":" + tflite.getInputTensor(0).dataType()
   + " - " + tflite.getInputTensor(1).name() + ":" + Arrays.toString(tflite.getInputTensor(1).shape()) + ":" + tflite.getInputTensor(1).dataType()
```
The result is bellow:
`Test: 2 - input_1:[1, 10]:FLOAT32 - input_2:[1, 2]:FLOAT32`

In addition, I tried the new model below with two inputs and I could execute it without error.
```
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            [(None, 2)]          0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, 2)]          0                                            
__________________________________________________________________________________________________
concatenate (Concatenate)       (None, 4)            0           input_1[0][0]                    
                                                                 input_2[0][0]                    
__________________________________________________________________________________________________
dense (Dense)                   (None, 4)            20          concatenate[0][0]                
==================================================================================================
```

There error seems to be related to LSTM model.

**Comment by jdduke** [comment]
@renjie-liu can you take a look?

**Comment by renjie-liu** [comment]
Hi,

Can you share the tf snippet about how you build the lstm?

thanks!

**Comment by aruno14** [comment]
I put the code I used to build the model below:
```
import tensorflow
from tensorflow.keras.models import Model
from tensorflow.keras.layers import LSTM, Embedding
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.layers import concatenate

vocab_size = 10
max_length = 10
def create_model():
    input_str = Input(shape=(max_length,))
    x = Embedding(vocab_size, 256, mask_zero=True)(input_str)
    x = LSTM(256)(x)
    input_int = Input(shape=(2))
    y = input_int
    z = concatenate([y, x])
    outputs = Dense(vocab_size, activation='softmax')(z)
    return Model([input_int, input_str], outputs, name='lstm')

model = create_model()
model.summary()
model.save("model_lstm2")
```

**Comment by renjie-liu** [comment]
seems export is fine, to failed at control flow (select & while)

Hi Haoliang, any idea?

thanks

**Comment by aruno14** [comment]
Thank you to all to look at my problem.
I would like to know if it is a tensorflow bug, or if I have to change my code.
If it is a tensorflow bug, I can only wait for a new version, right ?

Thanks.

**Comment by jdduke** [comment]
Looping in @miaout17 for troubleshooting.

**Comment by vikramambrose** [comment]
I'm seeing this error too with an NMT model I converted from Keras. 

  ```
  java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: tensorflow/lite/kernels/select.cc:80 data->has_rank_one_input_condition was not true.
    Node number 24 (SELECT) failed to prepare.
    
    Node number 19 (WHILE) failed to invoke.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:154)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:311)
        ...
```

Here is the Keras model creation code; https://github.com/prateekjoshi565/machine_translation/blob/master/german_to_english.ipynb

Here is the tflie conversion script;
```
tflite_convert \
     --keras_model_file model.h1.24_jan_19 \
     --output_file translate.tflite \
    --experimental_new_converter

```

**Host config**
Keras 2.3.1       
Keras-Applications 1.0.8       
Keras-Preprocessing 1.1.0      
tensorflow 2.1.0       
python 3.7.4

**Target config**
implementation 'org.tensorflow:tensorflow-lite:2.1.0'
implementation 'org.tensorflow:tensorflow-lite-gpu:2.1.0'

Here is a link to the model file binaries; https://gofile.io/?c=9TzxiC

**Comment by jvishnuvardhan** [comment]
@vikramambrose Can you please open a new issue so that it will be easy for the users to follow. You can tag me in the new issue. Thanks!

**Comment by jvishnuvardhan** [comment]
@vikramambrose One suggestion for you is to import keras from tensorflow. If we mix different components with different versions, then we might face compatibility issue. Thanks!

**Comment by thaink** [comment]
> I put the code I used to build the model below:
> 
> ```
> import tensorflow
> from tensorflow.keras.models import Model
> from tensorflow.keras.layers import LSTM, Embedding
> from tensorflow.keras.layers import Input, Dense
> from tensorflow.keras.layers import concatenate
> 
> vocab_size = 10
> max_length = 10
> def create_model():
>     input_str = Input(shape=(max_length,))
>     x = Embedding(vocab_size, 256, mask_zero=True)(input_str)
>     x = LSTM(256)(x)
>     input_int = Input(shape=(2))
>     y = input_int
>     z = concatenate([y, x])
>     outputs = Dense(vocab_size, activation='softmax')(z)
>     return Model([input_int, input_str], outputs, name='lstm')
> 
> model = create_model()
> model.summary()
> model.save("model_lstm2")
> ```

I tested this code but the output model is running OK. Could you try it again with the latest nightly?

**Comment by aruno14** [comment]
@thaink Thank you for your comment.
I tested your code but I got the same error as before. Maybe, I do not use the latest nightly.
I used the below code in the Gradle of my android project:

`implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'`
`implementation 'org.tensorflow:tensorflow-lite-support:0.0.0-nightly'`

How can I get the latest nightly version ?

**Comment by abattery** [comment]
@aruno14 could you create the model file again with the recent TF version and then try TFLite conversion?

**Comment by aruno14** [comment]
@abattery I updated my tensorflow (`pip install tensorflow`) and now it works! :)
I will create the real model I wanted to use and check if it works too. Thank you.

I also tried with the latest `tf-nightly` but I could not convert the model in TFLite.
I got the below output:
`  %cst_15 = "std.constant"() {value = dense<0> : tensor<1xi32>} : () -> tensor<1xi32>
  %cst_16 = "std.constant"() {value = dense<1> : tensor<1xi32>} : () -> tensor<1xi32>
  %cst_17 = "std.constant"() {value = dense<[0, -1, 0]> : tensor<3xi32>} : () -> tensor<3xi32>
  %cst_18 = "std.constant"() {value = dense<0> : tensor<3xi32>} : () -> tensor<3xi32>
  %cst_19 = "std.constant"() {value = dense<1> : tensor<3xi32>} : () -> tensor<3xi32>
  %0 = "tfl.cast"(%arg1) : (tensor<?x10xf32>) -> tensor<?x10xi32>
  %1 = "tfl.gather"(%cst, %0) {axis = 0 : i32} : (tensor<10x256xf32>, tensor<?x10xi32>) -> tensor<?x10x256xf32>
  %2 = "tfl.shape"(%1) : (tensor<?x10x256xf32>) -> tensor<3xi32>
  %3 = "tfl.strided_slice"(%2, %cst_15, %cst_16, %cst_16) {begin_mask = 0 : i32, ellipsis_mask = 0 : i32, end_mask = 0 : i32, new_axis_mask = 0 : i32, shrink_axis_mask = 1 : i32} : (tensor<3xi32>, tensor<1xi32>, tensor<1xi32>, tensor<1xi32>) -> tensor<i32>
  %4 = "tfl.pack"(%3, %cst_2) {axis = 0 : i32, values_count = 2 : i32} : (tensor<i32>, tensor<i32>) -> tensor<2xi32>
  %5 = "tfl.fill"(%4, %cst_1) : (tensor<2xi32>, tensor<f32>) -> tensor<?x256xf32>
  %6 = "tfl.unidirectional_sequence_lstm"(%1, %cst_10, %cst_11, %cst_12, %cst_13, %cst_4, %cst_5, %cst_6, %cst_7, %cst_3, %cst_3, %cst_3, %cst_8, %cst_9, %cst_8, %cst_8, %cst_3, %cst_3, %5, %5, %cst_3, %cst_3, %cst_3, %cst_3) {cell_clip = 1.000000e+01 : f32, fused_activation_function = "TANH", proj_clip = 0.000000e+00 : f32, time_major = false} : (tensor<?x10x256xf32>, tensor<256x256xf32>, tensor<256x256xf32>, tensor<256x256xf32>, tensor<256x256xf32>, tensor<256x256xf32>, tensor<256x256xf32>, tensor<256x256xf32>, tensor<256x256xf32>, none, none, none, tensor<256xf32>, tensor<256xf32>, tensor<256xf32>, tensor<256xf32>, none, none, tensor<?x256xf32>, tensor<?x256xf32>, none, none, none, none) -> tensor<?x10x256xf32>
  %7 = "tfl.strided_slice"(%6, %cst_17, %cst_18, %cst_19) {begin_mask = 5 : i32, ellipsis_mask = 0 : i32, end_mask = 5 : i32, new_axis_mask = 0 : i32, shrink_axis_mask = 2 : i32} : (tensor<?x10x256xf32>, tensor<3xi32>, tensor<3xi32>, tensor<3xi32>) -> tensor<?x256xf32>
  %8 = "tfl.concatenation"(%arg0, %7) {axis = 1 : i32, fused_activation_function = "NONE"} : (tensor<?x2xf32>, tensor<?x256xf32>) -> tensor<?x258xf32>
  %9 = "tfl.fully_connected"(%8, %cst_14, %cst_0) {fused_activation_function = "NONE", keep_num_dims = false, weights_format = "DEFAULT"} : (tensor<?x258xf32>, tensor<10x258xf32>, tensor<10xf32>) -> tensor<?x10xf32>
  %10 = "tfl.softmax"(%9) {beta = 1.000000e+00 : f32} : (tensor<?x10xf32>) -> tensor<?x10xf32>
  "std.return"(%10) : (tensor<?x10xf32>) -> ()
}) {arg0 = {tf_saved_model.index_path = ["input_2"]}, arg1 = {tf_saved_model.index_path = ["input_1"]}, result0 = {tf_saved_model.index_path = ["dense"]}, sym_name = "serving_default", tf.entry_function = {control_outputs = "", inputs = "serving_default_input_2:0,serving_default_input_1:0", outputs = "StatefulPartitionedCall:0"}, tf_saved_model.exported_names = ["serving_default"], type = (tensor<?x2xf32>, tensor<?x10xf32>) -> tensor<?x10xf32>} : () -> ()`

**Comment by abattery** [comment]
Could you share the full output of the error?

**Comment by aruno14** [comment]
@abattery I joined a file with the complete output because it is very long:
[tflite-nightly.txt](https://github.com/tensorflow/tensorflow/files/4685875/tflite-nightly.txt)

I also find the error message:
`error: Failed to duplicate values for the stateful op`

**Comment by abattery** [comment]
@aruno14 are you using the stateful RNN op in the model?

**Comment by aruno14** [comment]
@abattery I used the script given by @thaink to generate the model. So It only contains `LSTM ` and `Embedding`.

**Comment by renjie-liu** [comment]
@aruno14 the error is because the batch size is not set, can you fix the batch size when export to tflite?

thanks!

**Comment by aruno14** [comment]
@renjie-liu Sorry, I don't know how to set the batch size...

**Comment by renjie-liu** [comment]
@aruno14 can you try the codelab here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/Keras_LSTM_fusion_Codelab.ipynb

specially see the using concre function part to set the shape

thanks!

**Comment by aruno14** [comment]
@renjie-liu Thank you for your link. It was a little too complicated for me.
Finally, I found how to setup batch size on input and it works fine. I used below code:
```
import tensorflow
from tensorflow.keras.models import Model
from tensorflow.keras.layers import LSTM, Embedding
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.layers import concatenate
vocab_size = 10
max_length = 10
def create_model():
    input_str = Input(shape=(max_length), batch_size=1)
    x = Embedding(vocab_size, 256, mask_zero=True)(input_str)
    x = LSTM(256)(x)
    input_int = Input(shape=(2), batch_size=1)
    y = input_int
    z = concatenate([y, x])
    outputs = Dense(vocab_size, activation='softmax')(z)
    return Model([input_int, input_str], outputs, name='lstm')

model = create_model()
model.summary()
model.save("model_lstm2")
```

I could convert it to tflite model and used it in an Android app.

I also tried to use concre function, but I don't know how to set it correctly (shape and 2 inputs).
I used below code inserted after the above code:

```
run_model = tf.function(lambda x: model(x))
BATCH_SIZE = 1
STEPS = 1
INPUT_SIZE = 2
concrete_func = run_model.get_concrete_function(tf.TensorSpec([BATCH_SIZE, STEPS, INPUT_SIZE], model.inputs[0].dtype))
model.save("model_lstm2", save_format="tf", signatures=concrete_func)
```

And got below error:

```
WARNING:tensorflow:Model was constructed with shape (1, 2) for input Tensor("input_2:0", shape=(1, 2), dtype=float32), but it was called on an input with incompatible shape (1, 1, 2).
Traceback (most recent call last):
  File "analyse-lstm-github.py", line 42, in <module>
    concrete_func = run_model.get_concrete_function(tf.TensorSpec([BATCH_SIZE, STEPS, INPUT_SIZE], model.inputs[0].dtype))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 1153, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 1059, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 688, in _initialize
    *args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2838, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3195, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3057, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 595, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AssertionError: in user code:

    analyse-lstm-github.py:38 None  *
        run_model = tf.function(lambda x: model(x))
    /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py:950 __call__  **
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/functional.py:383 call
        inputs, training=training, mask=mask)
    /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/keras/engine/functional.py:514 _run_internal_graph
        assert x_id in tensor_dict, 'Could not compute output ' + str(x)

    AssertionError: Could not compute output Tensor("dense/Identity:0", shape=(1, 10), dtype=float32)
```

**Comment by renjie-liu** [comment]
sorry for your trouble and glad you found a way to make it work :)

I think the error message says

```
Model was constructed with shape (1, 2) for input Tensor("input_2:0", shape=(1, 2), dtype=float32), but it was called on an input with incompatible shape (1, 1, 2).
```
for the first input, it should be 2-d, and you have two inputs, you would need to construct two separate `tf.TensorSpec`s.

**Comment by aruno14** [comment]
Finally, I found how to use `concrete_func`, I put the code below maybe it can help someone.

```
import tensorflow
from tensorflow.keras.models import Model
from tensorflow.keras.layers import LSTM, Embedding
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.layers import concatenate
import tensorflow.compat.v2 as tf
tf.enable_v2_behavior()

vocab_size = 10
max_length = 10
def create_model():
    input_str = Input(shape=(max_length,))
    x = Embedding(vocab_size, 256, mask_zero=True)(input_str)
    x = LSTM(256)(x)
    input_int = Input(shape=(2))
    y = input_int
    z = concatenate([y, x])
    outputs = Dense(vocab_size, activation='softmax')(z)
    return Model([input_int, input_str], outputs, name='lstm')

model = create_model()
model.summary()
model.save("model_lstm2")
run_model = tf.function(lambda x, y: model([x, y]))
BATCH_SIZE = 1
STEPS = 1
INPUT_SIZE = 2
concrete_func = run_model.get_concrete_function(tf.TensorSpec((BATCH_SIZE, 2), model.inputs[0].dtype),tf.TensorSpec((BATCH_SIZE, 10), model.inputs[0].dtype))
model.save("model_lstm2", save_format="tf", signatures=concrete_func)
```

**Comment by renjie-liu** [comment]
great! thanks a lot! :D

**Comment by aruno14** [comment]
I check the error with my real model (to generate caption of image). I had no error in tflite conversation and `has_rank_one_input_condition` error disappear. So it seems to be fixed.

However, now I have a `Cannot copy between a TensorFlowLite tensor with shape [0, 6441] and a Java object with shape [1, 6441]` error when I execute `runForMultipleInputsOutputs`.
I checked the model I load with `tfliteModel.getOutputTensor(0).shape()` it outputs `[1, 6441]`.
What is a shape with a `0` size ?
Do I have to open a new issue for this problem?

**Comment by renjie-liu** [comment]
do you mind attaching your model and the code you invoke the model?

thanks

**Comment by aruno14** [comment]
The model file (it is a zip archive containing a bz2 archive, I had to do that to be under 10MB):
[classifier_caption.tflite.bz2.zip](https://github.com/tensorflow/tensorflow/files/4693741/classifier_caption.tflite.bz2.zip)

The code invoking the model:
```
Interpreter tflite = new Interpreter(FileUtil.loadMappedFile(activity, "classifier_caption.tflite"), new Interpreter.Options());
final short lenght = 10;
final short outputSize = 6441;
float[][] inputString = new float[1][lenght];
float[][] inputImage = new float[1][5120];

int[] outputString = new int[lenght];
Object[] inputArray = new Object[2];
inputArray[1] = inputString;
inputArray[0] = inputImage;
Map<Integer, Object> outputMap = new HashMap<>();
outputMap.put(0, new float[1][outputSize]);
tflite.runForMultipleInputsOutputs(inputArray, outputMap);
```

**Comment by renjie-liu** [comment]
@xunkai55, Hi Xunkai, can you help with the java api?

thanks a lot!

**Comment by xunkai55** [comment]
Will take a look.

**Comment by ne-bo** [comment]
@aruno14 Thanks a ton! You saved me so much time!

**Comment by aruno14** [comment]
I checked with version 2.3.0 of TensorFlow Lite, but I got a similar error:
`Cannot copy from a TensorFlowLite tensor (StatefulPartitionedCall:0) with shape [0, 6441] to a Java object with shape [1, 6441]`

**Comment by sushreebarsa** [comment]
@aruno14 Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!

**Comment by aruno14** [comment]
@sushreebarsa I did not work on this project for a long time, so I don't remember well. But, I rebuild my android app with the last  dependencies (org.tensorflow:tensorflow-lite:2.3.0) and the error seems to have disappeared. I did not recreate the model with tf 2.5 or 2.4.1.

**Comment by aruno14** [comment]
I checked with my full model. All seems to work well now.
Thank you.
