### ISSUE TITLE
ESP32 tensor allocation in PSRAM

### ISSUE THREAD

**Issue by tomtobback** [tensorflow/tensorflow#37628]
I'm using the Arduino TensorFlowLite library with an ESP32, and after testing some simple models successfully, i'm trying to load '[Optimized models for common mobile and edge use cases](https://www.tensorflow.org/lite/models)'. 
Model size is limited by the ESP32's standard 4MB FLASH, and tensor allocation by its default 520KB RAM. However, the maximum tensor pool size that can be allocated seems to be around 95*1024B; hitting the limit of ESP.getMaxAllocHeap()
Now, many dev boards (e.g. ESP32-CAM) have 4-8MB external PSRAM. As far as i can see, this is only available via dedicated allocation functions. Can the TensorFlowLite library be expanded to allow tensor allocation in PSRAM? Espressif has an example of how to handle this in the [esp32-camera](https://github.com/espressif/esp32-camera/blob/9f99b1b03ccfbd1937c3aee96f563af9df1e0ba6/driver/camera.c#L253) repo. Thanks for considering this.

**Comment by fredrec** [comment]
Hi,

As you mentioned it, the Tensorflow Micro interpreter should be given a pointer to an allocated pool of memory (tensor arena) where the tensors will live. [Example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/hello_world/main_functions.cc#L36).

How this pool is allocated is not the responsibility of Tensorflow and can be platform specific. 
It must be available during the entire lifetime of the Tensorflow interpreter. But it does not matter whether it is statically or dynamically allocated, nor if resides on the same die or an external SPI RAM chip.

Therefore, for ESP32, you can use the method of your choice mentioned in [Support for external RAM](https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/external-ram.html) to allocate the pool on PSRAM.

As an example, with the correct ESP-IDF `skdconfig` options, you should be able to allocate a 1MiB tensor arena like so:
```
constexpr int kTensorArenaSize = 1 * 1024 * 1024;
EXT_RAM_ATTR uint8_t tensor_arena[kTensorArenaSize];
```

**Comment by tomtobback** [comment]
Thanks for pointing out it should and can be done outside TensorFlowLite. I'm using the Arduino IDE so i can't change `skdconfig` options, and using `EXT_RAM_ATTR` does not compile. However, this seems to work (inspired by the esp32-camera code), i can indeed allocate 1MB.
```  uint8_t * tensor_pool;
  tensor_pool = (uint8_t*) heap_caps_calloc(tensor_pool_size, 1, MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT);
```
