### ISSUE TITLE
source code about the libhexagon_interface.so

### ISSUE THREAD

**Issue by huanyingjun** [tensorflow/tensorflow#37625]
Hello, 
TFlite heagon delegate is based on Hexagon nn.
I have got the hexagon nn SDK from Qualcomm, but I can not build the "libhexagon_interface.so".
Google add 4 fucntions in libhexagon_interface:
```
void hexagon_nn_global_teardown(void);
void hexagon_nn_global_init(void);
bool hexagon_nn_is_device_supported();
int hexagon_nn_hexagon_interface_version(void);
```

Could you please share the source code of the foure functions  and the "android.min" for building libhexagon_interface.so ?

**Comment by karimnosseir** [comment]
See https://github.com/tensorflow/tensorflow/issues/35506
