### ISSUE TITLE
Build TF 2.1.0 with RHEL6/RHEL7

### ISSUE THREAD

**Issue by npandey2385** [tensorflow/tensorflow#37629]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (Linux Redhat 6):
- TensorFlow installed from (source ):
- TensorFlow version:  2.1.0
- Python version:   3.7.2
- Bazel version (if compiling from source):   0.28.1
- GCC/Compiler version (if compiling from source):    7.4.0

**Describe the problem**
Not able to build TF 2.1.0 on RHEL6 and RHEL7

**Provide the exact sequence of commands / steps that you executed before running into the problem**

./configure
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**

ERROR: /servers/scratch03/niraj/tf-2.1/tensorflow-2.1.0/tensorflow/compiler/tf2tensorrt/BUILD:524:1: SWIGing tensorflow/compiler/tf2tensorrt/utils/py_utils.i failed (Exit 1)
/home/niraj/.cache/bazel/_bazel_niraj/install/efb644d4834d79efdfe4de9f85220414/_embedded_binaries/process-wrapper: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/niraj/.cache/bazel/_bazel_niraj/install/efb644d4834d79efdfe4de9f85220414/_embedded_binaries/process-wrapper)
/home/niraj/.cache/bazel/_bazel_niraj/install/efb644d4834d79efdfe4de9f85220414/_embedded_binaries/process-wrapper: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /home/niraj/.cache/bazel/_bazel_niraj/install/efb644d4834d79efdfe4de9f85220414/_embedded_binaries/process-wrapper)

**Comment by ravikyram** [comment]
@npandey2385 
Can you please check with [tested builded configurations](https://www.tensorflow.org/install/source#tested_build_configurations) and see if the issue still persists.Thanks!

**Comment by npandey2385** [comment]
Yes I am using the bazel > 0.27.1 , gcc > 7.3.1.
I read in following article that currently TF 2.1.0 supported only Ubuntu (18.04) for Linux .

https://github.com/tensorflow/tensorflow/issues/35754


I am not sure will it work for RHEL6/7 as well

**Comment by ravikyram** [comment]
@npandey2385 

Can you please share complete error log. Thanks!

**Comment by npandey2385** [comment]
These are the msg I am getting on terminal.

INFO: From ProtoCompile tensorflow/compiler/xla/xla_data.pb.h:                                                                
bazel-out/k8-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.                                     
INFO: From Compiling tensorflow/compiler/tf2xla/ops/xla_ops.cc:                                                               
tensorflow/compiler/tf2xla/ops/xla_ops.cc: In static member function 'static tensorflow::Status tensorflow::{anonymous}::<lambda(tensorflow::shape_inference::InferenceContext*)>::_FUN(tensorflow::shape_inference::InferenceContext*)':                   
tensorflow/compiler/tf2xla/ops/xla_ops.cc:245:74: warning: 'rhs_batch_dimension_or_constant.tensorflow::shape_inference::DimensionOrConstant::val' may be used uninitialized in this function [-Wmaybe-uninitialized]                                       
               lhs_batch_dimension_size, " and ", rhs_batch_dimension_size);                                                  
                                                                          ^                                                   
tensorflow/compiler/tf2xla/ops/xla_ops.cc:245:74: warning: 'lhs_batch_dimension_or_constant.tensorflow::shape_inference::DimensionOrConstant::val' may be used uninitialized in this function [-Wmaybe-uninitialized]                                       
tensorflow/compiler/tf2xla/ops/xla_ops.cc:214:45: warning: 'rhs_contracting_dimension_or_constant.tensorflow::shape_inference::DimensionOrConstant::val' may be used uninitialized in this function [-Wmaybe-uninitialized]                                 
               rhs_contracting_dimension_size);                                                                               
                                             ^                                                                                
tensorflow/compiler/tf2xla/ops/xla_ops.cc:214:45: warning: 'lhs_contracting_dimension_or_constant.tensorflow::shape_inference::DimensionOrConstant::val' may be used uninitialized in this function [-Wmaybe-uninitialized]                                 
ERROR: /servers/scratch03/niraj/tf-2.1/tensorflow-2.1.0/tensorflow/compiler/tf2tensorrt/BUILD:524:1: SWIGing tensorflow/compiler/tf2tensorrt/utils/py_utils.i failed (Exit 1)                                                                               
/home/niraj/.cache/bazel/_bazel_niraj/install/efb644d4834d79efdfe4de9f85220414/_embedded_binaries/process-wrapper: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/niraj/.cache/bazel/_bazel_niraj/install/efb644d4834d79efdfe4de9f85220414/_embedded_binaries/process-wrapper)                                                                          
/home/niraj/.cache/bazel/_bazel_niraj/install/efb644d4834d79efdfe4de9f85220414/_embedded_binaries/process-wrapper: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /home/niraj/.cache/bazel/_bazel_niraj/install/efb644d4834d79efdfe4de9f85220414/_embedded_binaries/process-wrapper)                                                                          
Target //tensorflow/tools/pip_package:build_pip_package failed to build                                                       
Use --verbose_failures to see the command lines of failed build steps.                                                        
INFO: Elapsed time: 11996.296s, Critical Path: 85.38s                                                                         
INFO: 5136 processes: 5136 local.                                                                                             
FAILED: Build did NOT complete successfully

**Comment by npandey2385** [comment]
Hi, Any update on this ?

**Comment by jeffheaton** [comment]
Also, note TF 2.2 has now been released some time ago.

**Comment by amahendrakar** [comment]
@npandey2385,
Is this still an issue?

Could you please follow [this guide](https://www.tensorflow.org/install/source) and check if you are facing the same error with TF v2.4.1 as well? Thanks!
