### ISSUE TITLE
grpc+verbs fail with tensorflow/core/common_runtime/process_state.cc:128] Check failed: 0 == cpu_allocators_.size() (0 vs. 1)

### ISSUE THREAD

**Issue by moshevolo** [tensorflow/tensorflow#37622]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): 
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04):  centos 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below):  r1.15 from source
- Python version: - Bazel
version (if compiling from source): python 3.6.8, bazel 0.26.1
- GCC/Compiler version (if compiling from
source):  gcc version 7.3.1
- CUDA/cuDNN version: - GPU model and memory: CPU only

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Using grpc+verbs and getting the following error:
2020-03-15 21:08:10.425600: F tensorflow/core/common_runtime/process_state.cc:128] Check failed: 0 == cpu_allocators_.size() (0 vs. 1)AddCPUAllocVisitor must be called prior to first call to ProcessState::GetCPUAllocator
Aborted

**Describe the expected behavior**
Should run without errors
**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@moshevolo,
Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks

**Comment by moshevolo** [comment]
This is the script I used:
======================= Python Program ============================
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow_datasets as tfds
import tensorflow as tf
tfds.disable_progress_bar()

BUFFER_SIZE = 60000
BATCH_SIZE = 64

def make_datasets_unbatched():
  # Scaling MNIST data from (0, 255] to (0., 1.]
  def scale(image, label):
    image = tf.cast(image, tf.float32)
    image /= 255
    return image, label

  datasets, info = tfds.load(name='mnist',
                            with_info=True,
                            as_supervised=True)

  return datasets['train'].map(scale).cache().shuffle(BUFFER_SIZE)

def build_and_compile_cnn_model():
  model = tf.keras.Sequential([
      tf.keras.layers.Conv2D(32, 3, activation='relu', input_shape=(28, 28, 1)),
      tf.keras.layers.MaxPooling2D(),
      tf.keras.layers.Flatten(),
      tf.keras.layers.Dense(64, activation='relu'),
      tf.keras.layers.Dense(10)
  ])
  model.compile(
      loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
      optimizer=tf.keras.optimizers.SGD(learning_rate=0.001),
      metrics=['accuracy'])
  return model

import json
import os

def main (argv):
    # Single worker
    # ==============
    if len(argv) < 2:
        print("Must provide argument\n\ts for single worker, 0 or 1 for 2 workers")
        exit()
    elif argv[1] == 's':
        train_datasets = make_datasets_unbatched().batch(BATCH_SIZE)
        single_worker_model = build_and_compile_cnn_model()
        # steps_per_epoch specify how many batches are declared as epoch, if not specified
        # then the whole data set
        single_worker_model.fit(x=train_datasets, epochs=3) #, steps_per_epoch=5)
        exit()


    # Multi worker
    # ============

    os.environ['TF_CONFIG'] = json.dumps({
        'cluster': {
            'worker': ["10.59.68.123:222", "10.59.68.124:222"]
        },
        'task': {'type': 'worker', 'index': int(argv[1])},
        'rpc_layer':'grpc+verbs'
        #'rpc_layer':'grpc'
    })

    strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()

    NUM_WORKERS = 2
    # Here the batch size scales up by number of workers since
    # `tf.data.Dataset.batch` expects the global batch size. Previously we used 64,
    # and now this becomes 128.
    GLOBAL_BATCH_SIZE = BATCH_SIZE * NUM_WORKERS

    # Creation of dataset needs to be after MultiWorkerMirroredStrategy object
    # is instantiated.
    train_datasets = make_datasets_unbatched().batch(GLOBAL_BATCH_SIZE)
    with strategy.scope():
        print("building model")
        # Model building/compiling need to be within `strategy.scope()`.
        multi_worker_model = build_and_compile_cnn_model()

        # Keras' `model.fit()` trains the model with specified number of epochs and
        # number of steps per epoch. Note that the numbers here are for demonstration
        # purposes only and may not sufficiently produce a model with good quality.
        # steps_per_epoch specify how many batches are declared as epoch, if not specified
        # then the whole data set
        print("training")
        multi_worker_model.fit(x=train_datasets, epochs=3) #, steps_per_epoch=5)


if __name__ == "__main__":
    import sys
    main(sys.argv)

================== End Python program ===============================
Command line:
The argument 0 is the task index
> python mnist+keras.py 0

**Comment by moshevolo** [comment]
Typo in last reply in file name, the command line is:
python mnist_keras.py 0

**Comment by moshevolo** [comment]
Is there any progress on this issue?
Or can you refer me to a known tf version and script that is known to work with grpc+verbs
I can work from there

Thanks

**Comment by ymodak** [comment]
Does it fail when executing on single worker or multiworker strategy?

**Comment by moshevolo** [comment]
On multi worker strategy

I also tried on tf 2.0 and it fails
Also tried with google tensorflow API as follow:
cloned the models api
Used bazelisk to build tf2
ran 
bazel build --config=opt --config=verbs //tensorflow/tools/pip_package:build_pip_package
Then:
./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
Then ip installed it
Created a file named export multi_host_cfg0.txt
The file content is:
{
        "task": {
            "type": "worker",
            "index": 1
        },
        "cluster": {
            "worker": ["10.59.68.123:222","10.59.68.124:222"]
        },
        "rpc_layer":"grpc+verbs"
}
Ran:
export TF_CONFIG=$(cat multi_host_cfg0.txt)
Then ran the program which you can see in:
https://github.com/tensorflow/models/blob/master/official/vision/image_classification/mnist_main.py

Like this:
python models/official/vision/image_classification/mnist_main.py --num_gpus=0 --train_epochs=5 \
            --distribution_strategy=multi_worker_mirrored --model_dir=./tf2src_model



I got the following output:

2020-03-18 14:59:05.767217: E tensorflow/c/c_api_experimental.cc:772] No server factory registered for the given ServerDef: cluster {
  job {
    name: "worker"
    tasks {
      key: 0
      value: "10.59.68.123:222"
    }
    tasks {
      key: 1
      value: "10.59.68.124:222"
    }
  }
}
job_name: "worker"
task_index: 1
default_session_config {
  device_filters: "/job:worker/task:1"
  graph_options {
    rewrite_options {
      scoped_allocator_optimization: ON
      scoped_allocator_opts {
        enable_op: "CollectiveReduce"
      }
    }
  }
  experimental {
    collective_group_leader: "/job:worker/replica:0/task:0"
  }
}
protocol: "grpc+verbs"

The available server factories are: [ GRPC_SERVER ]
Traceback (most recent call last):
  File "models/official/vision/image_classification/mnist_main.py", line 171, in <module>
    app.run(main)
  File "/root/.virtualenvs/tf2src/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/root/.virtualenvs/tf2src/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "models/official/vision/image_classification/mnist_main.py", line 164, in main
    stats = run(flags.FLAGS)
  File "models/official/vision/image_classification/mnist_main.py", line 87, in run
    tpu_address=flags_obj.tpu)
  File "/root/tf_models/models/official/utils/misc/distribution_utils.py", line 132, in get_distribution_strategy
    communication=_collective_communication(all_reduce_alg))
  File "/root/.virtualenvs/tf2src/lib64/python3.6/site-packages/tensorflow_core/python/distribute/collective_all_reduce_strategy.py", line 90, in __init__
    communication=communication))
  File "/root/.virtualenvs/tf2src/lib64/python3.6/site-packages/tensorflow_core/python/distribute/collective_all_reduce_strategy.py", line 144, in __init__
    self._initialize_strategy(cluster_resolver)
  File "/root/.virtualenvs/tf2src/lib64/python3.6/site-packages/tensorflow_core/python/distribute/collective_all_reduce_strategy.py", line 150, in _initialize_strategy
    self._initialize_multi_worker(cluster_resolver)
  File "/root/.virtualenvs/tf2src/lib64/python3.6/site-packages/tensorflow_core/python/distribute/collective_all_reduce_strategy.py", line 266, in _initialize_multi_worker
    context.context().ensure_initialized()
  File "/root/.virtualenvs/tf2src/lib64/python3.6/site-packages/tensorflow_core/python/eager/context.py", line 505, in ensure_initialized
    server_def_str)
tensorflow.python.framework.errors_impl.NotFoundError: No server factory registered for the given ServerDef: cluster {
  job {
    name: "worker"
    tasks {
      key: 0
      value: "10.59.68.123:222"
    }
    tasks {
      key: 1
      value: "10.59.68.124:222"
    }
  }
}
job_name: "worker"
task_index: 1
default_session_config {
  device_filters: "/job:worker/task:1"
  graph_options {
    rewrite_options {
      scoped_allocator_optimization: ON
      scoped_allocator_opts {
        enable_op: "CollectiveReduce"
      }
    }
  }
  experimental {
    collective_group_leader: "/job:worker/replica:0/task:0"
  }
}
protocol: "grpc+verbs"

The available server factories are: [ GRPC_SERVER ]
(tf2src) [root@NARCH-R2-13 tf_models]# more multi_host_cfg1.txt
{
        "task": {
            "type": "worker",
            "index": 1
        },
        "cluster": {
            "worker": ["10.59.68.123:222","10.59.68.124:222"]
        },
        "rpc_layer":"grpc+verbs"
}

**Comment by moshevolo** [comment]
Sorry,

Had to pip uninstall the previous trial build and then reinstall the new build (it had the same name).
Once I did than, grpc_verbs works, but I get the same error as in the original bug:

2020-03-18 15:21:53.628933: F tensorflow/core/common_runtime/process_state.cc:128] Check failed: 0 == cpu_allocators_.size() (0 vs. 1)AddCPUAllocVisitor must be called prior to first call to ProcessState::GetCPUAllocator
Fatal Python error: Aborted

Current thread 0x00007f72b0644740 (most recent call first):
  File "/root/.virtualenvs/tf2src/lib64/python3.6/site-packages/tensorflow_core/python/eager/context.py", line 505 in ensure_initialized
  File "/root/.virtualenvs/tf2src/lib64/python3.6/site-packages/tensorflow_core/python/distribute/collective_all_reduce_strategy.py", line 266 in _initialize_multi_worker
  File "/root/.virtualenvs/tf2src/lib64/python3.6/site-packages/tensorflow_core/python/distribute/collective_all_reduce_strategy.py", line 150 in _initialize_strategy
  File "/root/.virtualenvs/tf2src/lib64/python3.6/site-packages/tensorflow_core/python/distribute/collective_all_reduce_strategy.py", line 144 in __init__
  File "/root/.virtualenvs/tf2src/lib64/python3.6/site-packages/tensorflow_core/python/distribute/collective_all_reduce_strategy.py", line 90 in __init__
  File "/root/tf_models/models/official/utils/misc/distribution_utils.py", line 132 in get_distribution_strategy
  File "models/official/vision/image_classification/mnist_main.py", line 87 in run
  File "models/official/vision/image_classification/mnist_main.py", line 164 in main
  File "/root/.virtualenvs/tf2src/lib/python3.6/site-packages/absl/app.py", line 250 in _run_main
  File "/root/.virtualenvs/tf2src/lib/python3.6/site-packages/absl/app.py", line 299 in run
  File "models/official/vision/image_classification/mnist_main.py", line 171 in <module>
Aborted

**Comment by moshevolo** [comment]
Hello,

Asking again...
If there is no solution yet for the above 2 versions please let me know if there ANY tf versions that is known to work with RDMA (grpc+verbs).

Thanks

**Comment by moshevolo** [comment]
??????????

**Comment by lalalapotter** [comment]
Same problem in GDR

**Comment by Keepmoving-ZXY** [comment]
This reason is that GPU is initialized before initialize verbs.

**Comment by PangHua** [comment]
I am encountering the same error, have you fixed this problem? @Keepmoving-ZXY

**Comment by PangHua** [comment]
@yanivbl6 @byronyi Could you take a look at this issue? A lot of people are still facing it, just checked with Bug [24250](https://github.com/tensorflow/tensorflow/pull/24250) , the issue mentioned by  CheukNgai[https://github.com/tensorflow/tensorflow/pull/24250#issuecomment-447768924](url) still exists with verbs.

**Comment by clustar-zxy** [comment]
I fix this problem  by letting verbs server start before all device initialize.

**Comment by PangHua** [comment]
@clustar-zxy Could yo u elaborate how to do that? I am using estimator ParameterServer, and the PS server start failed in the beginning, no workers started yet, thanks.

**Comment by sushreebarsa** [comment]
@moshevolo It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? Thanks!
