### ISSUE TITLE
[Proposal] use numpy.asarray_chkfinite in tf.keras.backend.cast_to_floatx

### ISSUE THREAD

**Issue by howl-anderson** [tensorflow/tensorflow#37627]
Maybe we can use `numpy.asarray_chkfinite` instead of `numpy.asarray` in `tf.keras.backend.cast_to_floatx`?

```python
@keras_export('keras.backend.cast_to_floatx')
def cast_to_floatx(x):
  if isinstance(x, (ops.Tensor,
                    variables_module.Variable,
                    sparse_tensor.SparseTensor)):
    return math_ops.cast(x, dtype=floatx())
  return np.asarray(x, dtype=floatx())
```

It can help prevent user pass value which contains None, `inf`, `np.nan` or `np.inf` as input.

related to issue #37196

**Comment by gadagashwini** [comment]
@howl-anderson, Can you raise the Pull request to fix this issue?

**Comment by howl-anderson** [comment]
@gadagashwini Yes, I will submit a PR for this later!

**Comment by qlzh727** [comment]
Replied on #37196. See https://github.com/tensorflow/tensorflow/pull/37634#issuecomment-635080461 for more details.
