### ISSUE TITLE
set_shape is not loaded from saved model

### ISSUE THREAD

**Issue by StefReck** [tensorflow/tensorflow#37633]
**System information** 
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6.10

**Describe the current behavior**
When loading a saved keras model that contains .set_shape on a tensor, this is not loaded.

``` python
import tensorflow as tf

inp = tf.keras.Input((None, 3))
inp.set_shape((None, 2, 3))
x = tf.keras.layers.Dense(3)(inp)

model = tf.keras.Model(inp, x)
model.summary()

model.save("test.h5")
loaded = tf.keras.models.load_model("test.h5")
loaded.summary()
```

model.summary():
```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, None, 3)]         0         
_________________________________________________________________
dense (Dense)                (None, 2, 3)              12        
=================================================================
```

loaded.summary():

```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, None, 3)]         0         
_________________________________________________________________
dense (Dense)                (None, None, 3)           12        
=================================================================
```
--> Shape is not identical!

**Comment by gadagashwini** [comment]
Was able to reproduce the reported issue with Tf 2.1 and Tf-nightly==2.2.0.dev20200316..
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/9f42b6c399fc75f3d58a36ae8243d9b3/untitled460.ipynb). Thanks!

**Comment by k-w-w** [comment]
Why not just set the correct shape in `tf.keras.Input`? I understand that this is a toy example, but is there a valid use case for this?

**Comment by StefReck** [comment]
In my case, I'm using some operations which end up leaving the last dimension of the output tensor as a '?', even though I actually know the shape. So I set it manually in order to feed it into a dense layer (which requires the last dimension to be known).

In fact, I found out which operation left the dimension unknown: It's tf.shape, which is apparently also not properly loaded from a saved model:
``` python
import tensorflow as tf

inp = tf.keras.Input((2, 3))
x = tf.zeros(tf.shape(inp)[:2])

model = tf.keras.models.Model(inp, x)
model.summary()
model.save("test.h5")
loaded = tf.keras.models.load_model("test.h5")
loaded.summary()
```

model.summary():
```
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         [(None, 2, 3)]            0
_________________________________________________________________
tf_op_layer_Shape (TensorFlo [(3,)]                    0
_________________________________________________________________
tf_op_layer_strided_slice (T [(2,)]                    0
_________________________________________________________________
tf_op_layer_zeros (TensorFlo [(None, 2)]               0
=================================================================
```

loaded.summary():
```
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         [(None, 2, 3)]            0
_________________________________________________________________
tf_op_layer_Shape (TensorFlo (3,)                      0
_________________________________________________________________
tf_op_layer_strided_slice (T (2,)                      0
_________________________________________________________________
tf_op_layer_zeros (TensorFlo (None, None)              0
=================================================================
```
As you can see, the output has an unknown shape after loading the model.

**Comment by Dynmi** [comment]
> Why not just set the correct shape in `tf.keras.Input`? I understand that this is a toy example, but is there a valid use case for this?

I strongly support this view. it's not advisable to freewheeling like such model building idea.

**Comment by StefReck** [comment]
> 
> 
> 
> I strongly support this view. it's not advisable to freewheeling like such model building idea.

set_shape (and tf.shape apparently) are public, documented functions, and saving + loading is a very basic use case, so I don't see what you mean by 'freewheeling'.

**Comment by Dynmi** [comment]
> > I strongly support this view. it's not advisable to freewheeling like such model building idea.
> 
> set_shape (and tf.shape apparently) are public, documented functions, and saving + loading is a very basic use case, so I don't see what you mean by 'freewheeling'.

Sorry, I didn't mean to offend. My opinion is that "just set the correct shape in tf.keras.Input" already works well, while it's uncommon that you define _inp_ first and then _inp.set_shape()_.

**Comment by StefReck** [comment]
> 
> 
> > > I strongly support this view. it's not advisable to freewheeling like such model building idea.
> > 
> > 
> > set_shape (and tf.shape apparently) are public, documented functions, and saving + loading is a very basic use case, so I don't see what you mean by 'freewheeling'.
> 
> Sorry, I didn't mean to offend. My opinion is that "just set the correct shape in tf.keras.Input" already works well, while it's uncommon that you define _inp_ first and then _inp.set_shape()_.

Ah I see, sorry for the confusion. I just broke it down to a minium example for this issue. In my actual use case, I do define the input fully, but there are many layers and operations in between the input and set_shape which result in unknown dimensions, something like this:
``` python
inp = tf.keras.Input((3, 4))
x = ...  # many layers, output shape is (None, None, None)
x.set_shape((None, 2, 3))
x = tf.keras.layers.Dense(3)(x)
```

**Comment by k-w-w** [comment]
set_shape doesn't actually produce any ops, so it can't be saved in the SavedModel. You could create a custom layer that runs set_shape, and pass the layer as a custom object when loading.
