### ISSUE TITLE
[2.x] SparseTensor shape becomes <unknown> after some operations if using tf.function

### ISSUE THREAD

**Issue by llan-ml** [tensorflow/tensorflow#37638]
With tf.function, if an argument `x` of a function is a 2-d `tf.SparseTensor`, its shape is `(None, None)`. However, after some operations such as `tf.sparse.transpose` and `tf.sparse.reduce_sum`, the shapes of the resulting tensors become `<unknown>`.

Please refer to this [script](https://colab.research.google.com/drive/17DqrrFVZePJlJsfymrRCXNGBMNPNKeqd) for reproduction.

**Comment by Saduf2019** [comment]
@llan-ml 
could you please share the tensorflow version and simple stand alone code for us to replicate the issue faced.

**Comment by llan-ml** [comment]
@Saduf2019 I tested on `2.1` and `nightly`. The code is as follows:
```python
import tensorflow as tf

def foo(t):
  print(t.shape)
  print(tf.shape(t))
  print("=====")
  t1 = tf.sparse.transpose(t)
  print(t1.shape)
  print(tf.shape(t1))
  print("=====")
  t2 = tf.sparse.reduce_sum(t, axis=1)
  print(t2.shape)
  print(tf.shape(t2))
  print("=====")

t = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1., 2], dense_shape=[3, 4])
tf.function(foo)(t)
```

BTW, can't you access the colab link in my original post?

**Comment by Saduf2019** [comment]
i am able to replicate this issue, please find gist [here](https://colab.sandbox.google.com/gist/Saduf2019/06ff7c15f1bd9b04f65bbb140019224c/untitled96.ipynb)

**Comment by mdanatg** [comment]
It looks like [sparse_transpose](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/sparse_ops.py#L2597) defaults to an unknown rank for all but the fully-defined shapes, which is too strict.

So a workaround would be this:
```
def foo(t):
  print(t.shape)
  print(tf.shape(t))
  t = tf.SparseTensor(values=t.values, indices=t.indices, dense_shape=[3, 4])
  ...
```

It should be straightforward to add an extra check so that a known rank is preserved.

**Comment by yongtang** [comment]
@mdanatg @llan-ml I added a PR #38142 to address the `sparse.transpose` issue. For the other issue `sparse.reduce_sum`, it is inference from the C++ `SparseReduceSumSparse` ops which
will output unknown shape anyway. So it may not be easily fixable. I leave the `sparse.reduce_sum`.

Please take a look at PR #38142 for shape of `sparse.transpose`
