### ISSUE TITLE
contrib.learn.LinearClassifier steps not working as tutorial instructs

### ISSUE THREAD

**Issue by fogelton** [tensorflow/tensorflow#3763]
In tutorial it is written

classifier.fit(x=x_train, y=y_train, steps=200)
The state of the model is preserved in the classifier, which means you can train iteratively if you like. For example, the above is equivalent to the following:
classifier.fit(x=x_train, y=y_train, steps=100)
classifier.fit(x=x_train, y=y_train, steps=100)

But whne I try on my own, the same step parameter and evaluate the model, the results are all the time the same, only when I increase the parameter, the accuracy changes. Based on the behavior I believe the steps are rememebered and only new steps are fitted/performed.
So the equivalent is
classifier.fit(x=x_train, y=y_train, steps=100)
classifier.fit(x=x_train, y=y_train, steps=200)

Can anybody check this?

**Comment by girving** [comment]
@ilblackdragon The docstrings don't seem clear on which behavior is correct.  Can you comment?

**Comment by drpngx** [comment]
We've revamped the docs. I'm not sure that the tutorial is still there. I haven't seen an new issue filed on this. Feel free to open a new github issue if the problem still persists in recent versions.
