### ISSUE TITLE
TFLite build - missing interpreter_wrapper.i

### ISSUE THREAD

**Issue by philmassie** [tensorflow/tensorflow#37639]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): amazonlinux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:NA
- TensorFlow installed from (source or binary):binary
- TensorFlow version:2.1.0
- Python version:3.6.9
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):2.0.0
- GCC/Compiler version (if compiling from source):7.2.1
- CUDA/cuDNN version:NA
- GPU model and memory:NA

**Describe the problem**
Running sh ./tensorflow/lite/tools/pip_package/build_pip_package.sh results in:
...
swig -python -c++ -I/root/tensorflow/tensorflow/lite/tools/pip_package/../../../.. -module interpreter_wrapper -outdir tflite_runtime -o interpreter_wrapper/interpreter_wrapper_wrap.cpp interpreter_wrapper/interpreter_wrapper.i
Unable to find file 'interpreter_wrapper/interpreter_wrapper.i'.
error: command 'swig' failed with exit status 1

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Trying to build Tensorflow lite for AWS Lambda in amazonlinux.
Dockerfile:
FROM amazonlinux

WORKDIR /tflite

RUN yum groupinstall -y development
RUN yum install -y python3.7
RUN yum install -y python3-devel
RUN pip3 install numpy wheel
RUN git clone https://github.com/tensorflow/tensorflow.git
RUN sh ./tensorflow/tensorflow/lite/tools/pip_package/build_pip_package.sh

**Any other info / logs**
I am a total newb at compiling, so I apologise in advance for missing obvious info/logs.
The issue happens when `setup.py bdist bdist_wheel` is executed. I am afraid I cant figure out why the .i file is not there, or is not getting generated.
Do I need to generate them separately?

Thanks

**Comment by freedomtan** [comment]
in  e638577, `interpreter_wrapper/interpreter_wrapper.i` was removed because now interpreter_wrapper functions are exported from C++ to Python with pybind11 instead of swig. It seems corresponding changes were not made in the shell script and related files.

**Comment by teijeong** [comment]
reference to the interpreter_wrapper.i has removed, but other issue is still blocking normal execution of tflite_runtime pip package.
https://github.com/tensorflow/tensorflow/issues/38033

**Comment by Leslie-Fang** [comment]
Thanks for the reply, how to fix his issue now? Is this BKM still valid https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package
