### ISSUE TITLE
iOS: No OpKernel was registered to support Op 'RandomShuffleQueue' with these attrs

### ISSUE THREAD

**Issue by sahil912** [tensorflow/tensorflow#3764]
I am trying to load the simple trained model, but I am facing the following issue:

    No OpKernel was registered to support Op 'RandomShuffleQueue' with these attrs
    
    [[Node: shuffle_batch_1/random_shuffle_queue = RandomShuffleQueue[capacity=1003, 
    component_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], container="", min_after_dequeue=1000,
    seed=0, seed2=0, shapes=[[227,227,3], [10], [18]], shared_name=""]()]]

Thanks,

**Comment by girving** [comment]
The Android bit strips out a bunch of ops that are typically used only for training, in order to reduce code size.  @petewarden Is there a way to turn the stripping off?

**Comment by petewarden** [comment]
The list of supported ops is in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/makefile/tf_op_files.txt. 

If you add the right cc files for the RandomShuffleQueue op there and rebuild, hopefully you'll get past that problem. We need to document the limits on the ops on mobile more clearly too.
