### ISSUE TITLE
Error importing tensorflow

### ISSUE THREAD

**Issue by John-Wheater** [tensorflow/tensorflow#37642]
Everything seemed to install OK,   MacOS Catalina 10.15.3, Python 3.7.6, but the code failed  on its first line :
       import tensorflow as tf
 with error message:
ModuleNotFoundError: No module named 'tensorflow.python.tools' 

tensorflow version 2.1.0 installed today with pip3 version 20.0.2, details in attached file

[junk.txt](https://github.com/tensorflow/tensorflow/files/4339257/junk.txt)

**Comment by abhinavsp0730** [comment]
Hey, @John-Wheater please see  #34722 your problem is similar to this thread. Tell if the solution describe in this thread works for you or not. If it works then kindly close this issue.

**Comment by ravikyram** [comment]
@John-Wheater 

Just to verify did you follow instructions from [Tensorflow website](https://www.tensorflow.org/install/source). 

Try uninstalling and reinstalling:
pip uninstall tensorflow
then reinstall:
pip intall tensorflow==2.1.0
After you uninstall, in the python shell, run:

help('modules')
Tensorflow should not be there in that list. Only then proceed to install it.
Also see #34722 and see if it helps you.Thanks!

**Comment by John-Wheater** [comment]
I did the things advised by ravikyram, but the error is still there.  See attached file.   I notice frequent pip messages saying that a 'cached' version has been used.  Is that OK?  Or should I try and find out in MacOS how to clear its caches?

Finally, mine does seem to be the same problem as #34722, so should I close it, or add my experience to it?  Sorry, I'm quite new to all this.

[github-mar-17.txt](https://github.com/tensorflow/tensorflow/files/4342336/github-mar-17.txt)

**Comment by John-Wheater** [comment]
OK, I tried editing my PYTHONPATH, and the problem went away.  So I'll close this.

**Comment by abhinavsp0730** [comment]
@John-Wheater no need to say sorry. All of us were beginner in the beginning of learning any new technology. Feel free to ask about any issues. And Tensorflow community is always there to help you.
