### ISSUE TITLE
Don't know if tensorflow supports this type of restoring a model.

### ISSUE THREAD

**Issue by chrisrn** [tensorflow/tensorflow#3765]
I am new here so I have a basic question. I want to train a cnn for 20000 steps. In the 100th step I want to save all variables and after that I want to re-run my code restoring model and starting from the 101- step. I am trying to make it work with tensorflow documentation: https://www.tensorflow.org/versions/r0.10/how_tos/variables/index.html
but I don't know if I am right. When I re-run my code I don't initialize again variables because I run saver.restore and according to my accuracy it works. I achieve big accuracy from the beginning so I think model is restored. Although, I would like to start the loop from the 101 - step. So:
1st question: Am I saving and restoring in the right way?
2nd question: How can I start from the 101-step when re-running?

**Comment by Hvass-Labs** [comment]
Perhaps you want something like this?

https://www.youtube.com/watch?v=Lx8JUJROkh0

https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/04_Save_Restore.ipynb

I found the TensorFlow API and doc very confusing when trying to save and restore the whole model instead of just its variables.

**Comment by chrisrn** [comment]
I think that's not what I need. All I need is to split my training because I am gonna use a big dataset in my final project and I won't be able to train my network for a lot of hours continuously. I would possibly need to train for 2 hours, save my model and after a while restore it to continue training. I can't find a tutorial like this which explains this problem exactly as I want.

**Comment by girving** [comment]
Please ask questions like this on StackOverflow.  Github issues are for bug reports and feature requests.

**Comment by chrisrn** [comment]
I asked this question as feature request because I haven't seen anything like this yet. Maybe I miss something. Thank you.

**Comment by girving** [comment]
Everything you've described is within the normal saving / restoring functionality of TensorFlow.  If you're unsure how to use that functionality, please ask a StackOverflow question.
