### ISSUE TITLE
Stateful Keras RNN Conversion

### ISSUE THREAD

**Issue by Abhipray** [tensorflow/tensorflow#37659]
**System information**
- Mac OSX
- 2.2.0.dev20200316

**Command used to run the converter or code if you’re using the Python API**
https://colab.research.google.com/drive/1H7EWTn9lQZ18R6DDBWJtJUxxX3XIVd2K

**The output from the converter invocation**

```
ValueError: Input 0 of node sequential_3/gru_3/AssignVariableOp was passed float from sequential_3/gru_3/Read/ReadVariableOp/resource:0 incompatible with expected resource.
```

**Any other info / logs**
I am trying to make predictions using an RNN model that maintains state across forward pass of batches of unit size and consecutive time samples.

**Comment by Saduf2019** [comment]
we are able to replicate [this](https://colab.sandbox.google.com/gist/Saduf2019/b7497474ab06b670b57fb365e6461b13/untitled93.ipynb) issue

**Comment by Abhipray** [comment]
Any updates on this bug or clues on how to fix it, even if temporarily?

**Comment by abattery** [comment]
Could you try using TFLiteConverter.from_saved_model via converting keras model to saved model?

**Comment by Abhipray** [comment]
@abattery I tried that by calling
```
model.save('saved_model')
converter = tf.lite.TFLiteConverter.from_saved_model('saved_model')
```

I get the following errors:
```
---------------------------------------------------------------------------
ConverterError                            Traceback (most recent call last)
<ipython-input-10-cb973e0e0655> in <module>()
      6 converter.target_spec.supported_types = [tf.float16]
      7 
----> 8 tflite_fp16_model = converter.convert()

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    239       stdout = _try_convert_to_unicode(stdout)
    240       stderr = _try_convert_to_unicode(stderr)
--> 241       raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
    242   finally:
    243     # Must manually cleanup files.

ConverterError: See console for info.
2020-04-15 07:05:33.401098: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:307] Ignored output_format.
2020-04-15 07:05:33.401146: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:310] Ignored drop_control_dependency.
2020-04-15 07:05:33.428922: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
loc("gru_2/Variable"): error: is not immutable
Traceback (most recent call last):
  File "/usr/local/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: <unknown>:0: error: loc("gru_2/Variable"): is not immutable
<unknown>:0: note: loc("gru_2/Variable"): see current operation: "tf_saved_model.global_tensor"() {is_mutable, sym_name = "gru_2/Variable", type = tensor<1x20xf32>, value = dense<0.000000e+00> : tensor<1x20xf32>} : () -> ()
```

**Comment by Abhipray** [comment]
As a temporary workaround, I use `tf.compat.v1.lite.TFLiteConverter.from_sess()` after disabling eager execution and using the streaming layers in https://github.com/google-research/google-research/tree/master/kws_streaming.

**Comment by limuyiju** [comment]
any update?

**Comment by mimxrt** [comment]
I have the same issue with an LSTM saved model (Keras model -> saved model).

Can someone shed some light on why this is not implemented in the first place? In my understanding _stateless_ RNNs need the whole input sequence at once to perform meaningful inference. Yet, in embedded environments (where tflite converted models come into play), one usually

1. does not have enough memory to record/store the entire input sequence and
2. wants to have step-by-step inference results for each input vector instead of the complete sequence.

So, it seems to make no sense to use _stateless_ RNNs in an embedded environment&mdash;yet it is the only available option. What is the error in my assumption?

@Abhipray Do you have a minimal example for your https://github.com/tensorflow/tensorflow/issues/37659#issuecomment-614194122? I would really appreciate it if it's not too much effort.

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF 2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/3a6f737f45f4bb71ba4165365dabaf88/untitled93.ipynb#scrollTo=2g6eBG_Pb2gB) ..Thanks!

**Comment by abattery** [comment]
Mutable variable support is available in the nightly when converting from SavedModel only (Other types are coming soon).
Builtin ops are available now for VarHandleOp, ReadVariable, AssignVariable in the nightly also

Only thing needed is to set this flag during conversion:
converter.experimental_enable_resource_variables = True

Please let us know if you're having any issues.

Thanks

**Comment by Jerry-Ge** [comment]
> Mutable variable support is available in the nightly when converting from SavedModel only (Other types are coming soon). Builtin ops are available now for VarHandleOp, ReadVariable, AssignVariable in the nightly also
> 
> Only thing needed is to set this flag during conversion: converter.experimental_enable_resource_variables = True
> 
> Please let us know if you're having any issues.
> 
> Thanks

Hi Jae Sung, any updates from google that this converter for stateful LSTM can be supported in official releases? Tks!

**Comment by ywshin-github** [comment]
In the "tensorflow/org/lite/models/convert/rnn", it says sateful Keras LSTM conversion is future work, currently there is support only for converting stateless Keras LSTM.

Does that known issues/limitations still exist?
When I see the closing comment of abattery (june 29, 2021) , the known issues/limitation from the " tensorflow/org/lite/models/convert/rnn" is NOT issues anymore.
Am I right?

Thanks
