### ISSUE TITLE
Predict API does not work with VarLenFeature when batch inputs from different size

### ISSUE THREAD

**Issue by FelixHo** [tensorflow/tensorflow#37652]
_I thought this [issue](https://github.com/tensorflow/serving/issues/1574)  was related to tensorflow / serving repo , but they told me it belongs to this repo, and hoped that put it here to discuss, so I created this issue_

-------------

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): No
- OS Platform and Distribution (e.g.,Linux Ubuntu 16.04):  MacOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 2.7.13
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling fromsource): 
- CUDA/cuDNN version: 
- GPU model and memory: 

**Describe the current behavior**

Predict API is not compatible with batch variable length inputs. Everything is ok when the input is just one instance, or multiple instances with the same length of a var length feature.

ps: Classify API works pretty good in this case.

I tried to generate the exact same model through Estimator, and tested the above situation through the Classify API, everything was perfect. But since TensorFlow 2.0, Predict API is the default and only signature of keras model. I really want to solve this problem, instead of switching back to using Estimator or custom signature. This problem has troubled me for a while, thank you very much for your help :)

**Describe the expected behavior**

Predict API should be as compatible with variable length input features as Classify API

### Source code / logs

Here is a simple code to reproduce this, which will output a model and serving from it.

[code]
```python
import tensorflow as tf

# generate dummy dataset 
def serialize_example(val, label):
    features = {
      'color': tf.train.Feature(bytes_list=tf.train.BytesList(value=val)),
      'label': tf.train.Feature(int64_list=tf.train.Int64List(value=[label]))
    }
    example_proto = tf.train.Example(features=tf.train.Features(feature=features))
    return example_proto.SerializeToString()

tfrecord_writer = tf.io.TFRecordWriter('./color.tfrecord')
for val, label in [([b'G', b'R'], 1), ([b'B'], 1), ([b'B', b'G'], 0), ([b'R'], 1)]:
    tfrecord_writer.write(serialize_example(val, label))
tfrecord_writer.close()

# load the data generate above
def parse(example_proto):
    feature_description = {
        'color': tf.io.VarLenFeature(tf.string) ,           # ** VarLenFeature **
        'label': tf.io.FixedLenFeature([], tf.int64)        
    }
    parsed_features = tf.io.parse_single_example(example_proto, feature_description)
    labels = parsed_features.pop('label')
    return parsed_features, labels
    
dataset = tf.data.TFRecordDataset('./color.tfrecord').map(parse).repeat(5).batch(2)

# feature column & inputs.
color_cat = tf.feature_column.categorical_column_with_vocabulary_list(
                    key='color', vocabulary_list=["R", "G", "B"])    

color_emb = tf.feature_column.embedding_column(color_cat, dimension=4, combiner='mean')

inputs = {
    'color': tf.keras.layers.Input(name='color', shape=(None, ), sparse=True, dtype=tf.string)    
}

# build model
deep = tf.keras.layers.DenseFeatures([color_emb, ])(inputs)
output = tf.keras.layers.Dense(1, activation='sigmoid', name='output')(deep)
model = tf.keras.Model(inputs, output)
model.compile(optimizer='adam', loss='binary_crossentropy')

model.summary()

model.fit(dataset, epochs=5)
model.save('./dummy_model', save_format='tf')
```

[output log]
```
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
color (InputLayer)           [(None, None)]            0         
_________________________________________________________________
dense_features (DenseFeature (None, 4)                 12        
_________________________________________________________________
output (Dense)               (None, 1)                 5         
=================================================================
Total params: 17
Trainable params: 17
Non-trainable params: 0
_________________________________________________________________
Epoch 1/5
10/10 [==============================] - 1s 119ms/step - loss: 0.7157
Epoch 2/5
10/10 [==============================] - 0s 4ms/step - loss: 0.7045
Epoch 3/5
10/10 [==============================] - 0s 4ms/step - loss: 0.6977
Epoch 4/5
10/10 [==============================] - 0s 5ms/step - loss: 0.6911
Epoch 5/5
10/10 [==============================] - 0s 5ms/step - loss: 0.6847
WARNING:tensorflow:From /Users/felix/Envs/tf2/lib/python2.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1781: calling __init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: ./dummy_model/assets
```

[saved_model signature]
```
$ saved_model_cli show --dir ./ --all
--------------------------------------------------------------------------
MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is:

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['color'] tensor_info:
        dtype: DT_STRING
        shape: (-1, -1)
        name: serving_default_color:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 1)
        name: StatefulPartitionedCall_8:0
  Method name is: tensorflow/serving/predict
```
### Exact Steps to Reproduce
1. let me say there are two examples with the same shape , these work pretty good
```
curl -XPOST 0.0.0.0:8501/v1/models/dummy_model:predict -d '
{
  "inputs": {
    "color": [
      ["R"],
      ["G"]
    ]
  }
}'
----- response ----
{
    "outputs": [
        [
            0.370285
        ],
        [
            0.49326694
        ]
    ]
}

====================================================
curl -XPOST 0.0.0.0:8501/v1/models/dummy_model:predict -d '
{
  "inputs": {
    "color": [
      ["R", "G"],
      ["G", "B"]
    ]
  }
}'
------- response ---------
{
    "outputs": [
        [
            0.430707693
        ],
        [
            0.558493555
        ]
    ]
}
```
2. batch examples with different shape , does not work as expected
```
curl -XPOST 0.0.0.0:8501/v1/models/dummy_model:predict -d '
{
  "inputs": {
    "color": [
      ["R"],
      ["G", "B"]
    ]
  }
}'
-------- response -------

{ "error": "Encountered list at unexpected size: 2 at level: 1 expected size: 1" }

```
3.  "instances" key also not works

```
curl -XPOST 0.0.0.0:8501/v1/models/dummy_model:predict -d '
{
  "instances": [
    {"color": ["R"]},
    {"color": ["G", "B"]}
  ]
}'

--------- response -----------
{ "error": "Failed to process element: 1 key: color of \'instances\' list. Error: Invalid argument: Expecting tensor size: 1 but got: 2" }

```

**Comment by FelixHo** [comment]
@gowthamkpr

**Comment by DmitriyBaykov** [comment]
Hi, guys. Any update on this? I'm also interested in seeing this issue resolved. Facing the save behaviour. Let me know if you need more details to fix it. Thanks in advance!

**Comment by zhangmingnine** [comment]
Is the problem solved, can you share the result?

**Comment by yearsss** [comment]
i'm looking forward to the answer.

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/ea60a328461f46184c8580250a3c6234/untitled259.ipynb) ..Thanks!

**Comment by rabintang** [comment]
in estimator it can work, but in keras it doesn't.
https://colab.research.google.com/gist/sushreebarsa/828257b5977439dea95ee3d48bcab242/untitled105.ipynb#scrollTo=45EerngFwltz

**Comment by kumariko** [comment]
Was able to replicate the issue with TF v2.7, please find the gist [here](https://colab.research.google.com/gist/kumariko/2aec36644ad00433f93d649557748d61/untitled259.ipynb#scrollTo=PBEgk3qwH9rc) ..Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!

**Comment by cpy18727** [comment]
Is the problem solved?  :(

**Comment by nithish08** [comment]
Hi @FelixHo, were you able to solve this problem?
