### ISSUE TITLE
Inconsistently sized samples with TimeseriesGenerator

### ISSUE THREAD

**Issue by adamw96** [tensorflow/tensorflow#37667]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): **Win 10**
- TensorFlow installed from (source or
binary): **Binary** 
- TensorFlow version (use command below): **v2.1.0**
- Python version: **3.6.10**

**Describe the current behavior**
`tensorflow.keras.preprocessing.sequence.TimeseriesGenerator` generates inconsistently sized samples depending on parameters passed to `length, batch_size`. Ends up throwing input shape errors when passed into a model such as LSTM.

**Describe the expected behavior**
Each sample should be of size `(batch_size, length, n_features), (batch_size,)`.

**Standalone code to reproduce the issue** 
```
import numpy as np
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator

def GenerateData(TIMESTEPS, BATCHSIZE, N_FEATURES, N_SAMPLES):
    """
    Generates batches of one-step forward samples (x_1,...,x_n), (y_n+1)
    Args: TIMESTEPS (int) Number of past observations
          BATCHSIZE (int) Number of samples in each batch
          N_FEATURES (int) Number of features in dataset
          N_SAMPLES (int) Length of dataset

    Each generated sample should be shape (BATCHSIZE, TIMESTEPS, N_FEATURES), (BATCHSIZE,)
    """
    # Dummy multivariate series
    dummy_x = np.random.rand(N_SAMPLES, N_FEATURES)
    dummy_y = np.array([x[0] for x in dummy_x]) # Predict future values of first column
    print(f'Data X Shape: {dummy_x.shape}, Data Y Shape: {dummy_y.shape}')

    generator = TimeseriesGenerator(data=dummy_x, targets=dummy_y,
                                    length=TIMESTEPS,
                                    batch_size=BATCHSIZE,
                                    sampling_rate=1,
                                    stride=1
                                   )

    # Check whether each sample is shaped correctly
    for n in range(len(generator)):
        x,y = generator[n]
        if x.shape != (BATCHSIZE, TIMESTEPS, N_FEATURES):
            print(f'Check index {n}.')
```

**Tests:**
```
[In]
GenerateData(TIMESTEPS=5, BATCHSIZE=2, N_FEATURES=5, N_SAMPLES=1000)
[Out]
Data X Shape: (1000, 5), Data Y Shape: (1000,)
Check index 497.
Index 497 shapes: (1, 5, 5), (1,)

[In]
GenerateData(TIMESTEPS=5, BATCHSIZE=2, N_FEATURES=5, N_SAMPLES=1001)
[Out]
Data X Shape: (1001, 5), Data Y Shape: (1001,)

[In]
GenerateData(TIMESTEPS=6, BATCHSIZE=2, N_FEATURES=5, N_SAMPLES=1001)
[Out]
Data X Shape: (1001, 5), Data Y Shape: (1001,)
Check index 497.
Index 497 shapes: (1, 6, 5), (1,)

[In]
GenerateData(TIMESTEPS=6, BATCHSIZE=32, N_FEATURES=5, N_SAMPLES=1001)
[Out]
Data X Shape: (1001, 5), Data Y Shape: (1001,)
Check index 31.
Index 31 shapes: (3, 6, 5), (3,)
```

**Comment by adamw96** [comment]
In the tests above, only the parameters `length=2, batch_size=2, n_samples=1001` generates consistently sized samples.

**Comment by Dynmi** [comment]
Oh, This problem also occurs on my machine.

#### System information

- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes

- OS Platform and Distribution:Ubuntu18.04 LTS
- TensorFlow installed from (source or
binary): pip
- TensorFlow version (use command below): v2.1.0
- Python version: 3.6.10

**Comment by adamw96** [comment]
Something that might be helpful information: If `N_SAMPLE % BATCH_SIZE == TIMESTEPS`, samples are consistently shaped. The converse is generally not true.

**Comment by gadagashwini** [comment]
@adamw96, I tried to replicate this issue on colab with Tf 2.1 but I am not seeing any output. 
Please find the colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/074aaff597159ed7ed42e116fb9da7da/untitled465.ipynb) and provide more information to replicate the issue. Thanks!

**Comment by adamw96** [comment]
@gadagashwini Added some tests to the code. I think it'll be helpful if `TimeseriesGenerator` discards the first `length + k` values where `k` is chosen such that the remaining data can be divided into evenly sized samples. Otherwise with inconsistent batch shapes, if fed into a model (say, LSTM) this throws an input shape error.

**Comment by gadagashwini** [comment]
I could reproduce the issue with Tf 2.1.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/6cb9012e4d81c2f02c28d983dde22444/untitled474.ipynb). Thanks!

**Comment by ravikyram** [comment]
I could reproduce the issue with Tf 2.2-rc3.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/31cbd02f23b9fd9bcedbdf1e0ba01bab/untitled843.ipynb).Thanks!

**Comment by karmel** [comment]
@adamw96 , the TimeseriesGenerator has been replaced with an updated utility that works directly with TF datasets: https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/timeseries_dataset_from_array

That is available in the nightlies now; does that work for your use-case?

**Comment by ravikyram** [comment]
@adamw96 

Can you please try with TF nightly versions and see if the problem still persists.Thanks!
