### ISSUE TITLE
Scatter nd add has legacy docstrings from scatter nd

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/tensorflow#37669]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/tensor_scatter_nd_add

## Description of issue (what needs changing):
These sentences: 
> `indices` is an integer tensor containing indices into a new tensor of shape `shape`. The last dimension of `indices` can be at most the rank of `shape`:

Seem to be direct copy-paste from the docs of [`scatter_nd`](https://www.tensorflow.org/api_docs/python/tf/scatter_nd). However, there is no `shape` args in `scatter_nd_add`.

### Clear description

The docs should instead refer to `tensor.shape`.

### Correct links

Is the link to the source code correct? There is no link (that's another issue though I guess), only to the tf v1

### Parameters defined

Are all parameters defined and formatted correctly? Yes 

### Returns defined

Are return values defined? Yes

### Raises listed and defined

Are the errors defined? No errors raised apparently

### Usage example

Is there a usage example? Yes

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content? No, but there are some in `scatter_nd`, I guess it's enough

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

Not right now

**Comment by ashutosh1919** [comment]
@zaccharieramzi , can you explain the issue using example and elaborate it ? The given description is not enough to clearly understand the issue. Thanks!

**Comment by zaccharieramzi** [comment]
Well it's a doc issue so it's not really fit for an example. I just meant that the docs for `tensor_scatter_nd_add` should not mention a `shape` argument that is not part of the arguments of `tensor_scatter_nd_add`.

**Comment by ashutosh1919** [comment]
Thanks for the quick reply @zaccharieramzi . Are you able to locate the file where `tensor_scatter_nd_add` is implemented? If Yes, then please also provide the link. I am not able to locate the method.

**Comment by zaccharieramzi** [comment]
Like I pointed in the issue there is no link to the source code in the docs (that's another problem I guess). I think it's because it's a C++ op.
However, I don't understand why you would need it to understand this particular issue.
Anyway, I think the function is implemented here: https://github.com/tensorflow/tensorflow/blob/5214758e1f9335008a788be554633d974f569cf1/tensorflow/compiler/tf2xla/kernels/scatter_nd_op.cc#L172

**Comment by ashutosh1919** [comment]
@zaccharieramzi , I have found the code with the doc [here](https://github.com/tensorflow/java/blob/master/tensorflow-core/tensorflow-core-api/src/gen/java/org/tensorflow/op/core/TensorScatterNdAdd.java).

**Comment by zaccharieramzi** [comment]
Oh you meant the docstring code, right.

**Comment by ashutosh1919** [comment]
@zaccharieramzi and @mihaimaruseac , I have raised PR [#35](https://github.com/tensorflow/java/pull/35) to resolve this issue. Please review.

**Comment by ashutosh1919** [comment]
@mihaimaruseac , sorry for wrong PR. review #37832 for this issue.
