### ISSUE TITLE
use tf_trt to optimize model, but cost too much time and too much memory consumed 

### ISSUE THREAD

**Issue by chennuo0125-HIT** [tensorflow/tensorflow#37661]
I use:
OS: ubuntu 18.04
cuda: 10.0
cudnn: 7.6.3
python:3.6
tensorflow-gpu:1.15
GPU: nvidia jetson xavier kit
memory: 32G

source code line is [https://github.com/YunYang1994/tensorflow-yolov3/blob/eb02b0731dfb1c2614e216c619ac7b22db57d994/core/utils.py#L126](url)
and changed as follows : 
```
    converter = trt.TrtGraphConverter(input_graph_def=frozen_graph_def,\
            nodes_blacklist=return_elements,\
            is_dynamic_op=True,\
            precision_mode=trt.TrtPrecisionMode.FP16,\
            max_workspace_size_bytes=1*10**9,\
            max_batch_size=10
            )
    trt_graph = converter.convert()
    with graph.as_default():
        return_elements = tf.import_graph_def(trt_graph,
                                              return_elements=return_elements)
```
the result fps is ok, detection fps improve from 5 to 15, but which cost too much time and memory. usually i need to wait for 15 minutes to get the model loaded, besides memory cost too much and just 1G surplus (total 32G), sometimes no enough memory to run the program and program  is killed itself.
then i saved converted model as follows:
```
    # save optimized graph
    with tf.gfile.GFile("/home/xavier/python_ws/models/optimized_yolov3_f16.pb", "wb") as f:
        f.write(trt_graph.SerializeToString())
```
and load the optimized model as follows : 
```
    with tf.gfile.FastGFile(pb_file, 'rb') as f:
        frozen_graph_def = tf.GraphDef()
        frozen_graph_def.ParseFromString(f.read())

    with graph.as_default():
        return_elements = tf.import_graph_def(frozen_graph_def,
                                              return_elements=return_elements)
```
but the result is as previous, and the problem dont get improved, how can i to solve the problem ?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
