### ISSUE TITLE
Encoding images as TF_STRING Tensor in the C API

### ISSUE THREAD

**Issue by DhavalNiphade** [tensorflow/tensorflow#37671]
TF Version : 1.15.0
OS : Windows 10 64-bit
Compiler : MSVC 2017

I'm attempting to load a TF SavedModel and run inference on it using the [C API](https://www.tensorflow.org/install/lang_c) for TF version 1.15.0.

**Essential outlay**:
Input Tensor(s) : 'encoded_image_string_tensor:0'
Output Tensor(s) [_not exhaustive_] : ['detection_boxes:0' , 'detection_scores:0', 'detection_classes:0']

While there's some documentation in the API header that describes how TF_Tensors of type TF_STRING are encoded, I can't seem to find any concrete examples/illustrations which is probably why I keep running into an error when attempting to encode an image.

I picked up some parts from [this](https://stackoverflow.com/questions/41138822/how-to-create-a-string-type-tensor-in-tensorflow-c-api) unchecked answer on StackOverflow to get started:
```
// char* image (contains a pointer to the image)
// const unsigned int imageSize (contains the size of the image)

std::vector<int64_t> inputDims = { static_cast<int64_t>(TF_DataTypeSize(TF_UINT64)) + static_cast<int64_t>(imageSize) };
size_t encodedSize = TF_StringEncodedSize(imageSize);
size_t totalSize = TF_DataTypeSize(TF_UINT64) + encodedSize;
char* encodedInput = new char[totalSize];
for (size_t i = 0; i < TF_DataTypeSize(TF_UINT64); i++)
  encodedInput[i] = 0;

TF_StringEncode((const char*)image.data, imageSize, encodedInput + 8, encodedSize, status);
if (TF_GetCode(status) == TF_OK) {
  std::cerr << "Failed to encode image\n"; // The code enters this block and TF_Message(status) returns nothing to the output stream
  std::cerr << TF_Message(status) << std::endl;
  return false;
}
	
TF_Tensor* input = TF_NewTensor(TF_STRING, inputDims.data(), inputDims.size(), encodedInput, totalSize, NULL, 0);

```
Is there any guide on how to encode images as TF_STRING type tensors?

Thanks!

Please use [Netron](https://lutzroeder.github.io/netron/) to view the model if necessary
[saved_model.zip](https://github.com/tensorflow/tensorflow/files/4344883/saved_model.zip)

**Comment by alextp** [comment]
Your code says "failed to encode" if the TF status is OK, which is supposed to mean success.

**Comment by DhavalNiphade** [comment]
(facepalm)
Sorry about that. I should have been more careful.

I now receive an error when I run the session with the input tensor formed from the code above.

`Malformed TF_STRING tensor; element 0 out of range`

It appears that the model expects a TF_String tensor of shape (1, ). I still don't understand how the encoding process works. Could you briefly explain it? 

I know I'm asking a lot, but I'd really appreciate the help.

**Comment by alextp** [comment]
@gharibian can you help here?

**Comment by mihaimaruseac** [comment]
Is the same behaviour happening in 2.2.0-rc1/nightly/master?

**Comment by DhavalNiphade** [comment]
> Is the same behaviour happening in 2.2.0-rc1/nightly/master?

I'm not sure if there's libtensorflow support for TensorFlow 2 yet. This [page](https://www.tensorflow.org/install/lang_c) claims so.

I understand that the C API isn't meant for inference, but, quite unfortunately, that's my restriction right now.

**Comment by mihaimaruseac** [comment]
Oh, you're right. So we can exclude the `tstring` new API from being the root cause of this

**Comment by DhavalNiphade** [comment]
I'm fairly certain at this point that the problem is in the way I'm building the Tensor. Hence, my request for some illustration/example on how to build a TF_String Tensor from a 3-channel RGB image.

**Comment by DhavalNiphade** [comment]
Figured out the issue. Nothing wrong with the encoding, but with the dimensions.
 Here's the corrected code:


```
size_t encoded_size = TF_StringEncodedSize(imageCharSize);
size_t total_size = 8 + encoded_size;
char* input_encoded = new char[total_size];
for (size_t i = 0; i < 8; i++)
	input_encoded[i] = 0;

TF_StringEncode((const char*)imageChar, imageCharSize, input_encoded + 8, encoded_size, status);
if (TF_GetCode(status) != TF_OK) {
	std::cerr << "Failed to encode image\n";
	std::cerr << TF_Message(status) << std::endl;
	return false;
}

	
std::vector<std::int64_t> inputDims = { 1 };
TF_Tensor* input = TF_NewTensor(TF_STRING, inputDims.data(), inputDims.size(), input_encoded, total_size, NULL, 0);
```
