### ISSUE TITLE
TFRecord dataset reader causes excessive page faults

### ISSUE THREAD

**Issue by guoshimin** [tensorflow/tensorflow#37675]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  Yes
- OS Platform and Distribution (e.g.,Linux Ubuntu 16.04): Ubuntu 14.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.0.0
- Python version: 2.7
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): 7
- CUDA/cuDNN version: 10.0/7.5
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
tf.data.TFRecordDataset causes excessive page faults, especially when compression is used. We were able to tame the page faults in other parts of the graph by setting `TF_CPU_ALLOCATOR_USE_BFC=1`, but tf.data.TFRecordDataset doesn't seem to honor the allocator.

**Describe the expected behavior**
I expect, after setting `TF_CPU_ALLOCATOR_USE_BFC=1`, CPU memory allocations to be handled by the bfc allocator. There should not be large amounts of page faults because the tensorflow runtime manages memory allocation itself.

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

We have an input_fn that's essentially:
```
train_dataset = tf.data.TFRecordDataset(
    filenames,
    compression_type="ZLIB",
    buffer_size=100 * 1024 * 1024,
    num_parallel_reads=16)
train_dataset = train_dataset.map(
    map_func=lambda x: (tf.io.parse_single_example(x, features), {}), 
    num_parallel_calls=num_parallel_calls)
train_dataset = train_dataset.batch(4)
train_dataset = train_dataset.prefetch(1)
```
Each record is about 8MB compressed, and 250MB decompressed.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Flamegraph: https://drive.google.com/file/d/15LqZBBDov9Sikr9yt6OjMrVcw9IsebRk/view?usp=sharing

It's clear from the flamegraph that `tensorflow::io::ZlibInputStream::ReadBytesFromCache` and `tensorflow::io::BufferedInputStream::ReadNBytes` are dominated by page faults. `tensorflow::example::FastParseSingleExample` was also dominated by page faults when `TF_CPU_ALLOCATOR_USE_BFC=1` was not specified (not shown here,) but not when `TF_CPU_ALLOCATOR_USE_BFC=1` is specified (shown here.)

One source of page faults seems to be this line: https://github.com/tensorflow/tensorflow/blob/v2.0.0/tensorflow/core/lib/io/zlib_inputstream.cc#L175, according to the flamegraph.

**Comment by amahendrakar** [comment]
@guoshimin,
On running the above code, I got an error stating `NameError: name 'num_parallel_calls' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/83a90744a8855ce803098df0b8df9b6f/37675.ipynb).

Could you please share the complete code to reproduce the issue reported here and also the supporting files you are using. Thanks!

**Comment by guoshimin** [comment]
@amahendrakar The code sample was meant to give you a general idea. You can put whatever as num_parallel_calls. It's inconsequential. You would also need input files and a training loop to actually run it.

**Comment by amahendrakar** [comment]
@guoshimin,
In order to expedite the trouble-shooting process, could you please provide a minimal working example to reproduce the issue. Thanks!

**Comment by MinasTyuru** [comment]
Hi @amahendrakar, here is a minimal working example that reproduces the issue.
```from __future__ import absolute_import, division, print_function, unicode_literals
import os
import shutil
import time
import zlib
import numpy as np
import tensorflow as tf
from multiprocessing import Process
assert tf.__version__[0] == '2'

DATASET_DIR = '/tmp/pagefaults'
THREADS = 16
ZLIB_FILES = [os.path.join(DATASET_DIR, 'zlib_{}.tfrecord'.format(i)) for i in range(THREADS)]
TRIALS = 1024

def zero_bytes():
    zeros = np.zeros((250 * 10**6,), dtype=np.int8)
    return zeros.tobytes()

def create_zlib_dataset():
    for filepath in ZLIB_FILES:
        writer = tf.io.TFRecordWriter(filepath, options="ZLIB")
        writer.write(zero_bytes())
        writer.close()
    print("Created ZLIB dataset")

def read_zlib_dataset():
    total = 0
    start = time.time()
    dataset = tf.data.TFRecordDataset(ZLIB_FILES,
                                      compression_type="ZLIB",
                                      num_parallel_reads=THREADS)
    dataset = dataset.repeat().prefetch(THREADS)
    for sample in dataset:
        if total >= TRIALS:
            break
        total += 1
    elapsed = time.time() - start
    print("ZLIB read TFRecord: {:.5f} s per sample".format(elapsed / TRIALS))

def decompress_process(compressed):
    for _ in range(TRIALS // THREADS):
        zlib.decompress(compressed)

def decompress_only():
    compressed = zlib.compress(zero_bytes())
    start = time.time()
    processes = []
    for _ in range(THREADS):
        p = Process(target=decompress_process, args=(compressed,))
        p.start()
        processes.append(p)
    for p in processes:
        p.join()
    elapsed = time.time() - start
    print("Decompress only: {:.5f} s per sample".format(elapsed / TRIALS))

if __name__ == "__main__":
    os.environ['TF_CPU_ALLOCATOR_USE_BFC'] = "1"
    if not os.path.exists(DATASET_DIR):
        os.mkdir(DATASET_DIR)
    print("Starting")
    create_zlib_dataset()
    read_zlib_dataset()
    decompress_only()
```
If we read a ZLIB-compressed TFRecord using `read_zlib_dataset` and look at the flamegraph, a substantial amount of the runtime consists of page faults. In contrast, if we only decompress the files in memory using `decompress_only`, it is about twice as fast and almost all of the runtime is in the decompression algorithm itself. The results might be slightly different depending on machine, but if you generate a flamegraph you should see that a lot of time is being wasted on pagefaults.

Let me know if you need any more information from us, thank you!

**Comment by tilakrayal** [comment]
@guoshimin ,
Is this still an issue?
Could you please update TensorFlow to the latest stable version v.2.7 and let us know if you are facing the same error. Thanks!
