### ISSUE TITLE
Cannot create feature_column from sparse tensor of feature counts

### ISSUE THREAD

**Issue by tddevlin** [tensorflow/tensorflow#37678]
A common modeling pattern is to use sparse tensors to represent feature counts. For example, in a bag-of-words model, the input is a document represented by a tensor of token counts — the indices are token IDs and the values are their corresponding counts in the document.

Tensorflow's premade Estimators consume data via [feature_columns](https://www.tensorflow.org/api_docs/python/tf/feature_column). Currently, however, there is no way to create a feature_column directly from a sparse tensor.

**System information**
- TensorFlow version: all
- Are you willing to contribute it (Yes/No): maybe

**Will this change the current api? How?**
Yes, this change will add support to construct a feature_column directly from a sparse tensor.

**Who will benefit with this feature?**
Anyone who wants to use premade Estimators with feature data in sparse tensor form.

**Comment by tanzhenyu** [comment]
we have this [RFC](https://github.com/tensorflow/community/pull/188) where you can use CategoricalEncoding layer, however you will need to use sparse tensor to represent feature counts not by its indices, but by its values. Not sure if that would suffice your request

**Comment by rmothukuru** [comment]
@tddevlin,
Sorry for the delayed response. Can you please let us know if [this PR](https://github.com/tensorflow/community/pull/188) followed by [this RFC PR](https://github.com/tensorflow/community/pull/209) has implemented the **`Feature`** that you are looking for? Thanks!
