### ISSUE TITLE
Guided Backprop Gradcam with TF 2.0 for Transfer Learning

### ISSUE THREAD

**Issue by jdlamstein** [tensorflow/tensorflow#37680]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  
Yes

- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): 
Centos 7

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 
Tensorflow 2.0 from source

- Python version: - Bazel
version (if compiling from source):
Python 3.6

- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory:
Cuda 10.0, Titan V 12gb

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I am trying to do gradient visualization using gradcam with guided backpropagation. I can do it on VGG16, but when I add layers to VGG16, I get an error that the layer is not found. 

**Describe the expected behavior**
I want to visualize activation layers using gradcam with guided guided backprop. 

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Here's the Colab code with both the working example using just VGG16 and the broken example using VGG16 with added layers. 

https://colab.research.google.com/drive/1098Hp2icvleIQelkaLmPoIqAKuahs7JH

I'm attaching an image of a cat which is needed to run the colab. 

![cat 3](https://user-images.githubusercontent.com/36546688/76920921-ef21cf00-6889-11ea-8465-9b061a8f44c7.jpg)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Here's the traceback:
```

Tensor("block5_conv3_6/Identity:0", shape=(None, 14, 14, 512), dtype=float32)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-7-511b9293dd65> in <module>()
     60 # Get the score for target class
     61 with tf.GradientTape() as tape:
---> 62     conv_outputs, predictions = grad_model(np.array([img]))
     63     loss = predictions[:, 1]
     64 print('Prediction shape:', predictions.get_shape())

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    889           with base_layer_utils.autocast_context_manager(
    890               self._compute_dtype):
--> 891             outputs = self.call(cast_inputs, *args, **kwargs)
    892           self._handle_activity_regularization(inputs, outputs)
    893           self._set_mask_metadata(inputs, outputs, input_masks)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py in call(self, inputs, training, mask)
    706     return self._run_internal_graph(
    707         inputs, training=training, mask=mask,
--> 708         convert_kwargs_to_constants=base_layer_utils.call_context().saving)
    709 
    710   def compute_output_shape(self, input_shape):

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py in _run_internal_graph(self, inputs, training, mask, convert_kwargs_to_constants)
    868     output_shapes = []
    869     for x in self.outputs:
--> 870       assert str(id(x)) in tensor_dict, 'Could not compute output ' + str(x)
    871       tensor = tensor_dict[str(id(x))]
    872       output_shapes.append(x.shape)

AssertionError: Could not compute output Tensor("block5_conv3_6/Identity:0", shape=(None, 14, 14, 512), dtype=float32)

```

**Comment by captain-pool** [comment]
Can you please share the colab notebook via github? Since permission is getting denied.
Also, one main reason can be because you are passing a Numpy array to the model during graph mode execution. One thing you can do is either pass a Tensor of image, or execute it in Eager mode.(May be removing the `@tf.function` decorator from the training step?)

**Comment by gadagashwini** [comment]
@jdlamstein,Please provide the access to view the colab notebook. and also check the @captain-pool's workaround and let us know how it progresses. Thanks

**Comment by jdlamstein** [comment]
Thanks @gadagashwini  @captain-pool , I added the sharable link for colab. I tried @captain-pool 's suggestion to change the input from numpy array to tensor, but I got the same error.

**Comment by gadagashwini** [comment]
I was able to replicate the issue issue.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/d05a2511db244ed3e39103ed7c5e049d/untitled468.ipynb). Thanks!

**Comment by jdlamstein** [comment]
Hey, I think I found a workaround. If you append layers directly to the base model rather than insert the base model as a layer into your new model, it's easier to grab the layers. 

When setting up the model, I had to set the input_tensor when initializing the Model.

```
inp = layers.Input(shape=(imsize[0], imsize[1], imsize[2]))
base_model = tf.keras.applications.VGG16(include_top=False, weights='imagenet', input_tensor=inp,
                                          input_shape=(imsize[0], imsize[1], imsize[2]))
```

I set up the vgg16 base model and grabbed the output of the pooling layer from block5. 

```
base_model = tf.keras.applications.VGG16(include_top=False, weights='imagenet', input_tensor=inp,
                                          input_shape=(imsize[0], imsize[1], imsize[2]))
block5_pool = base_model.get_layer('block5_pool')
x = global_average_layer(block5_pool.output)
x = fc1(x)
# x = fc2(x)
x = prediction(x)

model = tf.keras.models.Model(inputs = inp, outputs = x)
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
```

Then I created a new model to output both the prediction and layer I want to visualize. 

```
# Create a graph that outputs target convolution and output
grad_model = tf.keras.models.Model(inputs = [model.input], 
                                   outputs=[model.output, model.get_layer(LAYER_NAME).output])

print(model.get_layer(LAYER_NAME).output)
# Get the score for target class

# Get the score for target class
with tf.GradientTape() as tape:
    predictions, conv_outputs = grad_model(img)
    loss = predictions[:, 1]
print('Prediction shape:', predictions.get_shape())
# Extract filters and gradients
output = conv_outputs[0]
grads = tape.gradient(loss, conv_outputs)[0]
```

I edited the colab and it worked. I added a fully connected layer, which is untrained so visualization will look at little random, but I did it a few times and it still seems to preserve the gist of it. 
https://colab.research.google.com/drive/1098Hp2icvleIQelkaLmPoIqAKuahs7JH

**Comment by Barba515** [comment]
how about in the case of 1D a trained CNN I would like to see which part of inputs are most related to output through the model that I have not a picture any help is appreciated
