### ISSUE TITLE
Getting std::bad_alloc in Android - StyleTransfer

### ISSUE THREAD

**Issue by ikasapoglu** [tensorflow/tensorflow#37681]
Hello, I've followed the examples/styletransfer repository. When I build&run the example everything worked with no errors. After that I changed the code a little bit to run my custom model. The model has these values;

custommodel.tflite {
input [1, 320, 320, 3] float32
output [1, 320, 320, 3] float32
} 

When I run it everything works well, too. The result of trained model is showing up in a imageview in about 75~100 ms. But quality did not satisfied me. So I tried to run with model 640x640, here its values;

custommodel_two.tflite {
input [1, 640, 640, 3] float32
output [1, 640, 640, 3] float32
}

When I run the application, it crashed with errors;

using NNAPI:
	`Conv size is too large, not enough memory`

using CPU/GPU:
	`A/libc: /usr/local/google/buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type std::bad_alloc: std::bad_alloc" failed`

`A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 27666 (AsyncTask #1), pid 27614 (.astyletransfer)`

And here is the call stack of methods that getting crash: 
`-NativeInterpreterWrapper.java`
`--(line 156) run(this.interpreterHandle, this.errorHandle);`
`---private static native void run(long var0, long var2);`

I tried with LG-G6, Samsung S7, Nexus5, Pixel (Emulator) both x86&x64 architectures. Also changed thread numbers: 1 - 4 - 7 - 12 but no luck.

Using these versions:

`implementation 'org.tensorflow:tensorflow-lite:2.1.0'`
`implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly'`
`implementation 'org.tensorflow:tensorflow-lite-support:0.0.0-nightly'`

So I wonder, what could be wrong with this ? 

Thanks.

**Comment by lintian06** [comment]
It seems that the built-in model works, while your custom model fails. From the context, it seems that your own model took up so much memory that it cannot allocate.

Can you provide more details of your custom model? Thanks!

**Comment by ikasapoglu** [comment]
Thanks for your reply. Yes, one of my custom models fails but my other model works (320x320). I leave two links there which contains screenshots from netron output. By the way, what kind of data do you expect me to share ? Because I do not know how can I give you a convenient explanation about the model. 

1: https://icoupstudios.com/tflite/1.png
2: https://icoupstudios.com/tflite/2.png

Thanks!

**Comment by lintian06** [comment]
Hi Amit, can you try a smaller Conv2D kernel? (Maybe, from size 9x9 to 3x3, which is more commonly used)

Maybe, because of the size is too large, it runs out of GPU memory.

**Comment by ikasapoglu** [comment]
Hello @lintian06 , thank you for your reply.

The Conv2d params are the same as IOS model. So I think Android should run it, because as you know; less conv2D value is less quality. We don't want to lose the quality.

I share a repository below for unterstand that
how I run inference of the model.

https://github.com/ikasapoglu/StyleTransferExample

Also, I upload a model file [here](https://drive.google.com/open?id=198K1WFEOvq0L9JRSW19_GBx01qBVBurL). The model size is 640x480. The strange case is this model that I can run it only once! Yes, the model running pretty well in first time, but when I run it again the result is the same as others; 

"Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 19685 (.astyletransfer), pid 19685 (.astyletransfer)" 

It is very weird

I'm waiting your review and reply, thank you.

**Comment by mohantym** [comment]
Hi @ikasapoglu !

We are checking to see whether you still need help in this issue . 
I am able to run this app after upgrading the Android Studio and Android Plugin version (Sync the gradle , Upgrade the plugin as Android studio suggests)

Could you let us know from your end.

Thank you!
