### ISSUE TITLE
The Problem with Distributed inference on multi-GPUs with tf.distribute.MirroredStrategy() strategy

### ISSUE THREAD

**Issue by thamquocdung** [tensorflow/tensorflow#37686]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): binary (install from pip) 
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6.8
 - Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: Cuda Toolkit 10.1 / cuDNN 7.6.4
- GPU model and memory: 2 Titan V

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I have tried to custom distributed inference on multi-GPUs (i.e 2 GPUs) follow the tutorial on page https://www.tensorflow.org/tutorials/distribute/save_and_load by using my model and `tf.distribute.MirroredStrategy()` strategy. In particular when I ran my bellow code
```
# Here is my code

DEFAULT_FUNCTION_KEY = "serving_default"
data = tf.data.Dataset.from_tensor_slices(np.random.rand(32*100, 416, 416, 3).astype('float32')).batch(32)

# load model and do inference on 1 GPU
loaded = tf.saved_model.load('./model')
inference_func = loaded.signatures[DEFAULT_FUNCTION_KEY]

total_time = 0.0
for batch in data:
    begin = time.time()
    inference_func(batch)
    total_time += time.time() - begin
print('Total time on 1 GPU: ', total_time)

# load model and do inference in a distributed manner
mirrored_strategy = tf.distribute.MirroredStrategy()
with mirrored_strategy.scope():
    model = tf.saved_model.load('./model')
    inference_func = model.signatures[DEFAULT_FUNCTION_KEY]

    dist_predict_dataset = mirrored_strategy.experimental_distribute_dataset(data)

    total_time = 0.0
    for batch in dist_predict_dataset:
        begin = time.time()
        mirrored_strategy.run(inference_func, args=(batch,))
        total_time += time.time() - begin
    print('Total time on 2 GPUs: ', total_time)
```
*_Note: The above code is customed from your bellow sample code in the tutorial_
```
# Here is your sample code in the tutorial

DEFAULT_FUNCTION_KEY = "serving_default"
loaded = tf.saved_model.load(saved_model_path)
inference_func = loaded.signatures[DEFAULT_FUNCTION_KEY]

predict_dataset = eval_dataset.map(lambda image, label: image)
for batch in predict_dataset.take(1):
  print(inference_func(batch))

another_strategy = tf.distribute.MirroredStrategy()
with another_strategy.scope():
  loaded = tf.saved_model.load(saved_model_path)
  inference_func = loaded.signatures[DEFAULT_FUNCTION_KEY]

  dist_predict_dataset = another_strategy.experimental_distribute_dataset(
      predict_dataset)

  # Calling the function in a distributed manner
  for batch in dist_predict_dataset:
    another_strategy.run(inference_func,args=(batch,))
```
and compared the total inference time of the model between 1 GPU and 2 GPUs with the same inputs. Unfortunately, I realized that the performance on 2 GPUs is **not** faster than on 1 GPU (about total time as well as the time of an iterator). It seems that the inference process executed on 2 GPUs **sequentially** (**not** **parallel as I expected**).

**Describe the expected behavior**
Please let me know if there are any problems here and show me how to modify the code in order to run **distributed inference on multi-GPUs parallel** with the best performance. Thanks so much for your help

**Standalone code to reproduce the issue** 
Files to reproduce the test case in [example.zip](https://github.com/tensorflow/tensorflow/files/4348380/example.zip)

**Other info / logs**

**Comment by thamquocdung** [comment]
@ymodak  I've read your code at https://github.com/tensorflow/tensorflow/blob/e5bf8de410005de06a7ff5393fafdf832ef1d4ad/tensorflow/python/distribute/mirrored_strategy.py#L92 and see run_concurrently = False (It means threads is running sequentially)

**Comment by ckkuang** [comment]
It is true that the inference_func is running on each GPU sequentially in eager mode, and you should be able to see a warning like [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/distribute/mirrored_strategy.py#L755).

To get things running in parallel, you can put the `strategy.run()` method inside a tf.function, so that graph building is sequential, but execution is parallel. See this [tutorial](https://www.tensorflow.org/tutorials/distribute/custom_training) for an example.

**Comment by jxtps** [comment]
@ckkuang I tried following your tutorial and came to the following rough recipe: 
```python
# https://github.com/tensorflow/tensorflow/issues/37686
# https://www.tensorflow.org/tutorials/distribute/custom_training
def compute_and_write_ious_multi_gpu(path: str, filename_csv: str, include_sampled: bool):
    strategy = tf.distribute.MirroredStrategy()
    util.log('Number of devices: {}'.format(strategy.num_replicas_in_sync))
    (ds, s, n) = dataset(path, shuffle=False, repeat=False, mask_as_input=True)
    dist_ds = strategy.experimental_distribute_dataset(ds)

    def predict_step(inputs):
        images, labels = inputs
        return model(images, training=False)

    @tf.function
    def distributed_predict_step(dataset_inputs):
        per_replica_losses = strategy.run(predict_step, args=(dataset_inputs,))
        return per_replica_losses  # unwrap!?

    # https://stackoverflow.com/questions/57549448/how-to-convert-perreplica-to-tensor
    def unwrap(per_replica):  # -> list of numpy arrays
        if strategy.num_replicas_in_sync > 1:
            out = per_replica.values
        else:
            out = (per_replica,)
        return list(map(lambda x: x.numpy(), out))

    with strategy.scope():
        model = wrap_model()

    util.log(f'Starting distributed prediction for {filename_csv}')
    ious = [unwrap(distributed_predict_step(x)) for x in dist_ds]
    t = ious
    ious = [item for sublist in t for item in
            sublist]  # https://stackoverflow.com/questions/952914/how-to-make-a-flat-list-out-of-list-of-lists
    util.log(f'Distributed prediction done for {filename_csv}')
    ious = np.concatenate(ious).ravel().tolist()
    ious = round_ious(ious)
    ious = list(zip(ious, ds.all_image_paths))
    ious.sort()
    write_ious(ious, filename_csv, include_sampled)
```
This does distribute the load across the GPUs, but unfortunately makes very poor use of them - in my particular case the corresponding single-GPU code runs in ~12 hours, and this runs in 7.7 hours, so not even a 2x speedup despite have 8x the number of GPUs.

`nvidia-smi` confirms that multi-GPU load bobs between 0 and 100%, whereas single-GPU load is almost pegged at 100%. 

I think it's mostly a data feeding issue due to the code structure. **Any suggestions for how to speed it up?**

The underlying dataset is created in the same way for both scenarios, and also for training where it's able to peg 8 GPUs at 100%, so it shouldn't be the dataset creation itself. 

(Ubuntu 16.04, tf 2.3.1, tf.keras 2.4.0, python 3.7.6, AWS p4d.24xlarge running on AWS Deep Learning AMI (Ubuntu 16.04) v38.0)
