### ISSUE TITLE
TF_OperationOpType

### ISSUE THREAD

**Issue by IvanUkhov** [tensorflow/tensorflow#3768]
Hi,

`TF_Node` [has been renamed](https://github.com/tensorflow/tensorflow/commit/b2c21f7e15cb61d2b1b2ca4154b1da45662f4747) to `TF_Operation`, which involved changing the names of a lot of functions. In particular, `TF_NodeOpType` has been changed to `TF_OperationOpType`. Before it’s been released, I just want to confirm that `Op` in `TF_OperationOpType` is not redundant. Thanks!

Regards,
Ivan

**Comment by girving** [comment]
@josh11b Is `TF_OperationOpType` right?

**Comment by josh11b** [comment]
I can see what the issue is, but I think we are going to leave it as is.  I try to consistently use the word "Op" to talk about the type of nodes/operations.  So Node/Operation : Op as Object : Class.  We renamed "Node" -> "Operation" in the C and C++ APIs to be consistent with the Python API, though I think "Node" is a bit less confusing for this very reason.  Note that I am also trying only abbreviate "operation"  using "oper", never "op".

**Comment by IvanUkhov** [comment]
@josh11b, I don’t quite get it: all your changes have been reverted in [this pull request](https://github.com/tensorflow/tensorflow/pull/3781). Does it mean that you have changed your mind, and it’s going to stay `TF_Node` in the next release?

**Comment by IvanUkhov** [comment]
@girving, I’m sorry for bothering, but maybe you could shed some light on the above question about the name to be used in the next release. The reason I ask is that I’d like to be a bit more proactive and get my code ready for version 0.10 already now. Thank you.

**Comment by girving** [comment]
@IvanUkhov Looks like it's `TF_OperationOpType` still.

**Comment by IvanUkhov** [comment]
@girving, I was referring to my last question about @josh11b’s changes that
have been reverted.

**Comment by girving** [comment]
Please check again.

**Comment by IvanUkhov** [comment]
@girving, I think we’re looking at different branches. I was assuming that the [r0.10](https://github.com/tensorflow/tensorflow/commits/r0.10) branch was representing to what would go into the 0.10 release, and that branch no longer contain the changes. But probably that branch is just an auxiliary one, and one should be looking at master instead.

**Comment by girving** [comment]
@IvanUkhov Ah.  I'm not sure what's going into 0.10.  @gunan Do you know if 0.10 will have `TF_Node` or `TF_Operation`?

**Comment by gunan** [comment]
Ah, this was not supposed to happen. Looks like there has been a mistake.
Looks like there was a misunderstanding.
I will revert my PR to r0.10 to reinstate Josh's changes.
