### ISSUE TITLE
Tensorflow lite inference crashes in Android development

### ISSUE THREAD

**Issue by momo1986** [tensorflow/tensorflow#37688]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution ：Linux
- TensorFlow installed from (source or binary):
- Tensorflow version: 1.12
- Target platform: Arm64 with Android kernel 3.18

**Describe the problem**
This problems happens when using teilte in Android APP platform. My input is 4D tensors with 3 RGB images. 

I convert the bitmap arrays for the byte buffer arrays.

**Please provide the exact sequence of commands/steps when you ran into the problem**

```
    private void convertBitmapToByteBuffer(ArrayList<Bitmap> bitmaps) {
        //System.out.println(bitmaps.size());
        for (int i = 0; i < 3; i++) {
            ByteBuffer imgData = ByteBuffer.allocateDirect(1
                    * getImageSizeX()
                    * getImageSizeY()
                    * 3
                    * getNumBytesPerChannel())
                    .order(ByteOrder.nativeOrder());
            bitmaps.get(i).getPixels(intValues, 0, bitmaps.get(i).getWidth(), 0, 0, bitmaps.get(i).getWidth(), bitmaps.get(i).getHeight());
            // Convert the image to floating point.
            //System.out.println(intValues.length);
            int pixel = 0;
            for (int j = 0; j < getImageSizeX(); j++) {
                for (int k = 0; k < getImageSizeY(); k++) {
                    final int val = intValues[pixel];
                    pixel++;
                    addPixelValueByData(val, imgData);

                }
            }
            imgDatas.add(imgData);

        }
    }
```

Then run the inference based on TensorFlow lite interpreter:
```
   public float[] runMultipleScaleInference(ArrayList<Bitmap> bitmaps) {
        convertBitmapToByteBuffer(bitmaps);
        //System.out.println(imgDatas.size());
        //Object[] inputs = new Object[]{imgDatas, pitchArray};

        //Object[] inputs = new Object[]{imgDatas};
        
        int size = imgDatas.size(); //It is 3 frames currently, imgDatas is the byte-buffer array to store the bitmap
        Object[][] inputsArray = new Object[size][];
        for (int i = 0; i < imgDatas.size(); i ++) {
            Object[] inputs = new Object[]{imgDatas.get(i)};
            inputsArray[i] = inputs;
        }
        Map<Integer, Object> outputs = new HashMap();
        outputs.put(0, probArray);

        tflite.runForMultipleInputsOutputs(inputsArray, outputs);
        return getNormalizedProbability();


    }
```

it crashes in "tflite.runForMultipleInputsOutputs(inputsArray, outputs)" with the stack trace log:

> E/AndroidRuntime: FATAL EXCEPTION: pool-1-multi_scale-fingering-1
>     Process: cn.findpiano.piano.ai.demo, PID: 4566
>     java.lang.NullPointerException: Attempt to invoke virtual method 'void org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(java.lang.Object[], java.util.Map)' on a null object reference
>         at cn.findpiano.piano.ai.recognizer.MultiScaleFingeringRecognizer.runMultipleScaleInference(MultiScaleFingeringRecognizer.java:198)
>         at cn.findpiano.recognizer.core.VoteRecognitionJob$Task.run(VoteRecognitionJob.java:76)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
>         at java.lang.Thread.run(Thread.java:764)

I file this bug issue to know what is the correct pose to inference the 4D-tensors with bitmap arrays in tensorflow-lite in Android?

Thanks & Regards!

**Comment by lintian06** [comment]
As per the error message, 

> java.lang.NullPointerException: Attempt to invoke virtual method 'void org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(java.lang.Object[], java.util.Map)' on a null object reference

It seems the bug is in your code, `tflite == null` in
```
   tflite.runForMultipleInputsOutputs(inputsArray, outputs);
```

**Comment by momo1986** [comment]
Hello, Thanks.

I have fixed the problem.

Maybe this issue can be closed.

Thanks for reply and help.

**Comment by vandics** [comment]
hello, could you provide a solution for this issue? I got this issues too

**Comment by jdduke** [comment]
@vandics please file a separate bug, but in general this is indicative of an issue with client code having a null value for the Interpreter.

**Comment by vandics** [comment]
Sorry for not open a new issue because my problem is the same as this one, maybe you could give me an advice. Below is my code. I just want to run tflite object detection with a custom dataset on an android device

private ArrayList<Classifier.Recognition> getDetectionsForTiny(ByteBuffer byteBuffer, Bitmap bitmap) {
        ArrayList<Classifier.Recognition> detections = new ArrayList<Classifier.Recognition>();
        Map<Integer, Object> outputMap = new HashMap<>();
        outputMap.put(0, new float[1][OUTPUT_WIDTH_TINY[0]][4]);
        outputMap.put(1, new float[1][OUTPUT_WIDTH_TINY[1]][labels.size()]);
        Object[] inputArray = {byteBuffer};
        tfLite.runForMultipleInputsOutputs(inputArray, outputMap);


        int gridWidth = OUTPUT_WIDTH_TINY[0];
        float[][][] bboxes = (float [][][]) outputMap.get(0);
        float[][][] out_score = (float[][][]) outputMap.get(1);

        for (int i = 0; i < gridWidth;i++){
            float maxClass = 0;
            int detectedClass = -1;
            final float[] classes = new float[labels.size()];
            for (int c = 0;c< labels.size();c++){
                classes [c] = out_score[0][i][c];
            }
            for (int c = 0;c<labels.size();++c){
                if (classes[c] > maxClass){
                    detectedClass = c;
                    maxClass = classes[c];
                }
            }
            final float score = maxClass;
            if (score > getObjThresh()){
                final float xPos = bboxes[0][i][0];
                final float yPos = bboxes[0][i][1];
                final float w = bboxes[0][i][2];
                final float h = bboxes[0][i][3];
                final RectF rectF = new RectF(
                        Math.max(0, xPos - w / 2),
                        Math.max(0, yPos - h / 2),
                        Math.min(bitmap.getWidth() - 1, xPos + w / 2),
                        Math.min(bitmap.getHeight() - 1, yPos + h / 2));
                detections.add(new Classifier.Recognition("" + i, labels.get(detectedClass),score,rectF,detectedClass ));
            }
        }
        return detections;
    }
and below is my error

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.padi_eko, PID: 28056
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2, result=-1, data=Intent { dat=content://media/external/images/media/578977 flg=0x1 }} to activity {com.example.padi_eko/com.example.padi_eko.camera}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(java.lang.Object[], java.util.Map)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4626)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4670)
        at android.app.ActivityThread.-wrap19(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1829)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:7055)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(java.lang.Object[], java.util.Map)' on a null object reference
        at com.example.padi_eko.camera.getDetectionsForTiny(camera.java:492)
        at com.example.padi_eko.camera.onActivityResult(camera.java:288)
        at android.app.Activity.dispatchActivityResult(Activity.java:7634)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4622)

**Comment by jdduke** [comment]
Your `tfLite` Interpreter object is null. Either creation failed, or it wasn't created in the first place.

**Comment by vandics** [comment]
I have created it with private Interpreter tfLite, also I have print the object interpreter and none of them are null. If I run object detection example from tensorflow, it is working correctly but when I run it on my app it will send an error like above.
