### ISSUE TITLE
Can subjoin one keras.layers operation?

### ISSUE THREAD

**Issue by LuuHu** [tensorflow/tensorflow#37685]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): v2.1.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
    I meet problem when i trying to spilt one layer, i need something like r**everse operation of  Concatenate**, that can **spilt  shape  [b,w,h,C]   to  [b,w,c,A]and[b,w,h,B]**, which C==A+B

**Will this change the current api? How?**
  It won't have any inpact influence on current api.

**Who will benefit with this feature?**
    Since that Tensorflow2.0 become easy to hand on, it will be more popular in acedemia if more easy and comfortable api are provided. 

**Any Other info.**

**Comment by Saduf2019** [comment]
@LuuHu
could you please share a simple stand alone code for us to replicate the issue faced, along with the error logs.

**Comment by LuuHu** [comment]
Sorry ,i mean it's not a error but suggest to add a **keras.layers function** that **spilt tensor** 
```
import tensorflow as tf
inpt = tf.keras.Input(input_shape=(16,28,28,3))
x = Conv2D(128,3)(inpt)  #(16,28,28,128)
A,B = THE_SPILT_FUNCTION(axis=20)(x)  # A=(16,28,28,20) B=(16,28,28,108)
model = tf.keras.Model(inputs=inpt, outputs=[A,B])
```
and it like reverse operation like tf.keras.layers.Concatenate
![image](https://user-images.githubusercontent.com/41143797/76949587-b6dec700-6943-11ea-9119-f385a7b63845.png)
such as 
np.spilt operte one array 
```
A = np.ones((100,32,32,50))
print(A.shape)
A,B = np.split(A,(20,),axis=-1)
print(A.shape)
print(B.shape)
```

Thanks

**Comment by tanzhenyu** [comment]
Why not use tf.split with keras lambda layer?
i.e.,:
```python
outputs = tf.keras.layers.Lambda(lambda x : tf.split(x, [size_A, size_B], axis=-1)
```

**Comment by LuuHu** [comment]
Wow, Thanks a lot.

**Comment by tanzhenyu** [comment]
> Wow, Thanks a lot.

Np!
