### ISSUE TITLE
2.1.0 build error due to pybind11

### ISSUE THREAD

**Issue by bu-bgregor** [tensorflow/tensorflow#37695]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux CentOS 7.7.1908
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.1.0
- Python version: 3.7.5
- Installed using virtualenv? pip? conda?:  
- Bazel version (if compiling from source): 0.27.1
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: none (CPU only build)
- GPU model and memory:

Building tensorflow 2.1.0 results in compile errors due to pybind11.  This is a build for CPU-only use without any dependency on CUDA libraries.  Example error (out of ~630):
```
bazel-out/host/bin/external/local_config_python/python_include/pybind11/detail/common.h:302:12: error: multiple definition of 'enum class pybind11::return_value_policy'
 enum class return_value_policy : uint8_t {
            ^~~~~~~~~~~~~~~~~~~
In file included from external/pybind11/include/pybind11/pytypes.h:12:0,
                 from external/pybind11/include/pybind11/cast.h:13,
                 from external/pybind11/include/pybind11/attr.h:13,
                 from external/pybind11/include/pybind11/pybind11.h:49,
                 from tensorflow/python/framework/op_def_registry.cc:16:
external/pybind11/include/pybind11/detail/common.h:302:12: note: previous definition here
 enum class return_value_policy : uint8_t {
            ^~~~~~~~~~~~~~~~~~~
```
Build steps:

```
python3  -m venv py37-env
source py37-env/bin/activate
pip install -I --no-cache-dir "numpy==1.17.2"
pip install -I --no-cache-dir "pybind11==2.3.0"
pip install -I --no-cache-dir six wheel setuptools mock 'future>=0.17.1'
pip install -I --no-cache-dir keras_applications --no-deps
pip install -I --no-cache-dir keras_preprocessing --no-deps

# Run to try and keep bazel from using the wrong python
export PYTHON_BIN_PATH=`which python3`
export PYTHON_LIB_PATH=`python -c "import sys ; print(sys.path[-1])"`
export PYTHONPATH=$PYTHON_LIB_PATH
export TF_NEED_OPENCL_SYCL=0 
export TF_NEED_COMPUTECPP=0 
export TF_NEED_OPENCL=0 
export TF_CUDA_CLANG=0
export TF_DOWNLOAD_CLANG=0
export CC_OPT_FLAGS="-march=sandybridge -mtune=intel  -Wno-sign-compare"
export TF_NEED_CUDA=0
export TF_NEED_TENSORRT=0
export TF_NEED_ROCM=0
export TF_SET_ANDROID_WORKSPACE=0
export TF_ENABLE_XLA=0
export USE_DEFAULT_PYTHON_LIB_PATH=1

./configure

time bazel build  --verbose_failures  \
  --config=opt \
  --config=mkl \
  --config=numa \
  --config=v2 \
  --linkopt="-Wl,-rpath=/share/pkg.7/gcc/7.4.0/install/lib64" \
  --linkopt="-L/share/pkg.7/gcc/7.4.0/install/lib64"   \
  --host_linkopt="-Wl,-rpath=/share/pkg.7/gcc/7.4.0/install/lib64" \
  --host_linkopt="-L/share/pkg.7/gcc/7.4.0/install/lib64"  \
  //tensorflow/tools/pip_package:build_pip_package   
```

[bazel37.zip](https://github.com/tensorflow/tensorflow/files/4350233/bazel37.zip)

**Comment by mihaimaruseac** [comment]
Since you are building from source, can you try building from master?

**Comment by bu-bgregor** [comment]
> 
> 
> Since you are building from source, can you try building from master?

I did a git checkout from master, switched to Bazel 2.0.0, and used the same build process.  It built without any problems.

`Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package
INFO: Elapsed time: 1545.899s, Critical Path: 214.52s
INFO: 17016 processes: 17016 local.
INFO: Build completed successfully, 18417 total actions
INFO: Build completed successfully, 18417 total actions
`

**Comment by mihaimaruseac** [comment]
Interesting. Thank you for the check.

Do you want to build on 2.1 or master/2.2 is ok?

**Comment by bu-bgregor** [comment]
The build from master also succeeded for Python 3.6.9.  I'd prefer to have an identical CPU-only v2.1.0 to match the tensorflow 2.1.0 install via pip for GPU usage.  However I can live with this for now so this is low priority for me.  On our cluster all the "real" tensorflow work is done on GPUs but we also use the CPU-only build for development, testing, and some classroom usage.

**Comment by mihaimaruseac** [comment]
If you want a CPU-only tensorflow you can also try using the `tensorflow-cpu` pip package

Regarding the pybind error, we had some segfaults due to ODR violations at the time, so this could be related. We fixed them in master (and 2.2)

**Comment by jameszow2** [comment]
Use tensorflow version 2.0 only puthon3.7x

**Comment by mihaimaruseac** [comment]
@jameszow2 please don't provide bad advice. TF 2.0 is not a long term release and will soon no longer receive any updates/support. Plus, the issue here is in C++, not in Python.

**Comment by bu-bgregor** [comment]
@mihaimaruseac - oops, just trying to clarify my statements.  The tensorflow-cpu pip pakage for 2.1.0 works great, but the issue for us is that it uses AVX instructions and our cluster has a decent amount of Nehalem architecture CPUs that don't support AVX.  The CPU-only source code build is to support up to SSE4.2 so that tensorflow 2.1.0 code will run on the Nehalem CPUs.   Jobs that run on newer CPUs will load the code from the tensorflow-cpu pip package, and if there's a GPU installed it'll load the regular tensorflow pip package.

**Comment by mihaimaruseac** [comment]
That makes sense now. Thanks for explaining. I can dedicate some time to investigate the build failure in this case, but won't be able to do this until mid of April unfortunately :(

**Comment by mihaimaruseac** [comment]
Unfortunately we cannot patch old branches except for security reasons. Can you try with newer versions of TF?

**Comment by Saduf2019** [comment]
@bu-bgregor 
As we have the latest stable version 2.6.0, Can you try building TF 2.6.0 or any later 2.x version and let us know if the issue still persists?
