### ISSUE TITLE
Pre trained Resnet model with batch size 1

### ISSUE THREAD

**Issue by raina0990** [tensorflow/tensorflow#37700]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Atomic Pi
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.5
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: 2GB RAM, 16GB eMMC

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

II want to use pretrained ResNet model for image classification. The model I used  requires batch size of 64. Using a batch size of 64 has made Atomic Pi go out of memory.

The model used is from this git repoistory:

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
 Error Log:
https://github.com/tensorflow/models/tree/master/official/r1/resnet
Killed
makefile:2: recipe for target 'default' failed
make: *** [default] Error 137

**Comment by Saduf2019** [comment]
@raina0990 
Is there any specific reason to be using tensorflow 1.15, could you please upgrade tensorflow and use with later versions, please let us know if that helps resolve your issue.

[please try the following commands and let us know if it works.
python3 -m pip install --upgrade pip or pip install --upgrade pip]
