### ISSUE TITLE
Building TF 2.2.0-rc0 with Bazel 1.2.1 fails 

### ISSUE THREAD

**Issue by feranick** [tensorflow/tensorflow#37702]
Summary: According to the release notes, TF 2.2.0-rc0 can be compiled with bazel 1.2.1 (the MIN version). However, when attempting this, it fails. Compilation is successful with Bazel 2.0.0. Compiling with 2.0.1 fails as well (Max seems to be set at 2.0.0)

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04, MacOS
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 2.2rc0
- **Python version**: 3.6-3.7
- **Bazel version (if compiling from source)**: 1.2.1
- **Exact command to reproduce**:
1. Install bazel 1.2.1
2. GitClone TF and checkout 2.2.0-rc0
3. compile as indicated by the manual. compilation will fail immediately with bazel 1.2.1 (according to the release notes for TF 2.2.0-rc0, that is the minimum version required) but compiles successfully with bazel 2.0.0

**Comment by feranick** [comment]
This is the log when running `./configure` with bazel 1.2.1:


Extracting Bazel installation...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'version' from /home/nicola/Software/tensorflow-dir/cpu/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
ERROR: Unrecognized option: --experimental_repo_remote_exec
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Traceback (most recent call last):
  File "./configure.py", line 1551, in <module>
    main()
  File "./configure.py", line 1368, in main
    _TF_MAX_BAZEL_VERSION)
  File "./configure.py", line 483, in check_bazel_version
    ['bazel', '--batch', '--bazelrc=/dev/null', 'version'])
  File "./configure.py", line 159, in run_shell
    output = subprocess.check_output(cmd, stderr=stderr)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bazel', '--batch', '--bazelrc=/dev/null', 'version']' returned non-zero exit status 2

**Comment by feranick** [comment]
This is the log when running ./configure with bazel 2.0.1:

Traceback (most recent call last):
  File "./configure.py", line 1551, in <module>
    main()
  File "./configure.py", line 1368, in main
    _TF_MAX_BAZEL_VERSION)
  File "./configure.py", line 483, in check_bazel_version
    ['bazel', '--batch', '--bazelrc=/dev/null', 'version'])
  File "./configure.py", line 159, in run_shell
    output = subprocess.check_output(cmd, stderr=stderr)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bazel', '--batch', '--bazelrc=/dev/null', 'version']' returned non-zero exit status 1

**Comment by amahendrakar** [comment]
[Release notes](https://github.com/tensorflow/tensorflow/releases/tag/v2.2.0-rc0) mention `Increasing the minimum bazel version to build TF to 1.2.1 to use Bazel's cc_experimental_shared_library.`

However, [configure.py](https://github.com/tensorflow/tensorflow/blob/cf46f78c72bbcb86aff64d06e6fbbb54f2f31d8a/configure.py#L52) states both minimum and maximum bazel version as 2.0.0. Attached screenshot for reference.

![Screenshot 2020-03-19 at 2 25 40 PM](https://user-images.githubusercontent.com/57165142/77049172-9c612800-69ed-11ea-8598-692db0806a8b.png)

**Comment by feranick** [comment]
BTW, shouldn't the Max version of bazel be 2.0.1? It seems like a bug-fix-release of v.2.0.0....

**Comment by mihaimaruseac** [comment]
We are building with 2.0.0 and this error slipped our minds.

@bmzhao can you look and confirm what are the minimum and maximum bazel versions?

**Comment by bmzhao** [comment]
Yes, the current minimum and maximum bazel versions are **now Bazel 2.0.0**; unfortunately I forgot to add the that as a "Release Note" in commit [daec6e0af0dfe39aada697275a76570da7f04608](https://cs.opensource.google/tensorflow/tensorflow/+/daec6e0af0dfe39aada697275a76570da7f04608)

The rationale for the upgrade is related to changes to the implementation of cc_shared_library in bazel that only occurred in bazel 2.0 (and weren't backported to bazel 1.2.1).

Bazel 2.0.0 is also required now for RBE builds, as one of the experimental remote exec options is now set starting from commit [09fe958feebec0405ccac225c94fc130304fc2f4](https://cs.opensource.google/tensorflow/tensorflow/+/09fe958feebec0405ccac225c94fc130304fc2f4).

**Comment by feranick** [comment]
Version 2.2.0-rc1 still has the wrong minimum version listed in the Release notes.

**Comment by mihaimaruseac** [comment]
That is because we did the release before the fix. We will have fixed release notes for the next rc/final release

**Comment by mihaimaruseac** [comment]
TF 2.2.0-rc2 has been released and release notes now correctly mention that Bazel needs to be 2.0.0
