### ISSUE TITLE
Tensorflow documentation on Image Captioning has non existing methods.

### ISSUE THREAD

**Issue by Mahe-git2hub** [tensorflow/tensorflow#37709]
## URL(s) with the issue:
I was running Image captioning example given in tensorflow website as it is in Colab. I found out that the documentation made a mention about "**image_features_extract_model**" which was not defined anywhere earlier. Neither could I find any method related to that on Google.

The lines that caused the error is given below:

```
# Get unique images
encode_train = sorted(set(img_name_vector))

# Feel free to change batch_size according to your system configuration
image_dataset = tf.data.Dataset.from_tensor_slices(encode_train)
image_dataset = image_dataset.map(
  load_image, num_parallel_calls=tf.data.experimental.AUTOTUNE).batch(16)

for img, path in image_dataset:
  batch_features = image_features_extract_model(img)
  batch_features = tf.reshape(batch_features,
                              (batch_features.shape[0], -1, batch_features.shape[3]))

  for bf, p in zip(batch_features, path):
    path_of_feature = p.numpy().decode("utf-8")
    np.save(path_of_feature, bf.numpy())

```
The original documetation can be found at the following url:
[https://www.tensorflow.org/tutorials/text/image_captioning](url)

I was confused whether i should report this as a bug or documentation error. I went with the latter.

Is the link to the source code correct?
Yes
The original documetation can be found at the following url:
[https://www.tensorflow.org/tutorials/text/image_captioning](url)

**Comment by jaketae** [comment]
Hi, I think `image_features_extract_model` is defined in the notebook. See this line in the "Initialize InceptionV3 and load the pretrained Imagenet weights" section.

```python
image_model = tf.keras.applications.InceptionV3(include_top=False,
                                                weights='imagenet')
new_input = image_model.input
hidden_layer = image_model.layers[-1].output

image_features_extract_model = tf.keras.Model(new_input, hidden_layer)
```

I'm running the notebook in Colab. If I can reproduce your error, I will report back here.

**Comment by khimraj** [comment]
@Mahe-git2hub, As @jaketae  mentioned `image_features_extract_model` is already defined in notebook. I have successfully compiled above mentioned tutorial and there is no error. For your reference link of gist is [here](https://colab.research.google.com/gist/khimraj/59ad82815d6a17139685a608ef5dc20d/image_captioning.ipynb).
Hope it helps.

**Comment by vjuss** [comment]
Hi, I am new here so bear with me and let me know if I should make a new thread! I get a bit similar error from the same part of the same tutorial code:

`NameError                                 Traceback (most recent call last)
<ipython-input-5-c54eeda8599b> in <module>()
----> 1 encode_train = sorted(set(img_name_vector))
      2 
      3 # Feel free to change batch_size according to your system configuration
      4 image_dataset = tf.data.Dataset.from_tensor_slices(encode_train)
      5 image_dataset = image_dataset.map(

NameError: name 'img_name_vector' is not defined`

Have you others not had this or have you fixed it? img_name_vector seems to be defined in the tutorial so I really wonder what the problem is.
