### ISSUE TITLE
Compiling TF 2.2.0-rc0 with bazel 2.0.0 fails (MacOS)

### ISSUE THREAD

**Issue by feranick** [tensorflow/tensorflow#37703]
**System information** 

- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): MacOS 10.15
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.2.0-rc0
- Python version: python3 3.7.7
- Bazel 2.0.0
- GCC/Compiler version (if compiling from source): Xcode 11.3.1
- CUDA/cuDNN version: - GPU model and memory: None

**Describe the current behavior**
1. GitClone TF, checkout version 2.2.0-rc0
2. ./configure with standard/default options
3. run compilation as indicated by manual
Result: Compilation stops unsuccessful moments after it starts (log below)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=130
INFO: Reading rc options for 'build' from /Users/feranick/Desktop/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /Users/feranick/Desktop/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from /Users/feranick/Desktop/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/opt/local/bin/python3 --action_env PYTHON_LIB_PATH=/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages --python_path=/opt/local/bin/python3 --config=xla --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file /Users/feranick/Desktop/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /Users/feranick/Desktop/tensorflow/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:opt in file /Users/feranick/Desktop/tensorflow/.tf_configure.bazelrc: --copt=-march=native --copt=-Wno-sign-compare --host_copt=-march=native --define with_default_optimizations=true
INFO: Found applicable config definition build:v2 in file /Users/feranick/Desktop/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:macos in file /Users/feranick/Desktop/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
INFO: Call stack for the definition of repository 'io_bazel_rules_closure' which is a http_archive (rule definition at /private/var/tmp/_bazel_feranick/50b852099a3bf3aaa184abce166f8e34/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /Users/feranick/Desktop/tensorflow/WORKSPACE:5:1
ERROR: An error occurred during the fetch of repository 'io_bazel_rules_closure':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_feranick/50b852099a3bf3aaa184abce166f8e34/external/bazel_tools/tools/build_defs/repo/http.bzl", line 72
		_get_auth(ctx, all_urls)
	File "/private/var/tmp/_bazel_feranick/50b852099a3bf3aaa184abce166f8e34/external/bazel_tools/tools/build_defs/repo/http.bzl", line 52, in _get_auth
		read_netrc(ctx, netrcfile)
	File "/private/var/tmp/_bazel_feranick/50b852099a3bf3aaa184abce166f8e34/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 219, in read_netrc
		ctx.read(filename)
java.io.FileNotFoundException: /Users/feranick/.netrc (No such file or directory)
ERROR: no such package '@io_bazel_rules_closure//closure': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_feranick/50b852099a3bf3aaa184abce166f8e34/external/bazel_tools/tools/build_defs/repo/http.bzl", line 72
		_get_auth(ctx, all_urls)
	File "/private/var/tmp/_bazel_feranick/50b852099a3bf3aaa184abce166f8e34/external/bazel_tools/tools/build_defs/repo/http.bzl", line 52, in _get_auth
		read_netrc(ctx, netrcfile)
	File "/private/var/tmp/_bazel_feranick/50b852099a3bf3aaa184abce166f8e34/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 219, in read_netrc
		ctx.read(filename)
java.io.FileNotFoundException: /Users/feranick/.netrc (No such file or directory)
ERROR: no such package '@io_bazel_rules_closure//closure': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_feranick/50b852099a3bf3aaa184abce166f8e34/external/bazel_tools/tools/build_defs/repo/http.bzl", line 72
		_get_auth(ctx, all_urls)
	File "/private/var/tmp/_bazel_feranick/50b852099a3bf3aaa184abce166f8e34/external/bazel_tools/tools/build_defs/repo/http.bzl", line 52, in _get_auth
		read_netrc(ctx, netrcfile)
	File "/private/var/tmp/_bazel_feranick/50b852099a3bf3aaa184abce166f8e34/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 219, in read_netrc
		ctx.read(filename)
java.io.FileNotFoundException: /Users/feranick/.netrc (No such file or directory)
INFO: Elapsed time: 2.296s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by ravikyram** [comment]
@feranick 

Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by feranick** [comment]
`wget https://github.com/bazelbuild/bazel/releases/download/1.2.1/bazel_1.2.1-linux-x86_64.deb`
`sudo dpkg -i bazel_1.2.1-linux-x86_64.deb`
`git clone https://github.com/tensorflow/tensorflow`
`cd tensorflow`
`git checkout v2.2.0-rc0`
`./configure`


log:
Extracting Bazel installation...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'version' from /home/nicola/Software/tensorflow-dir/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
ERROR: Unrecognized option: --experimental_repo_remote_exec
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Traceback (most recent call last):
  File "./configure.py", line 1551, in <module>
    main()
  File "./configure.py", line 1368, in main
    _TF_MAX_BAZEL_VERSION)
  File "./configure.py", line 483, in check_bazel_version
    ['bazel', '--batch', '--bazelrc=/dev/null', 'version'])
  File "./configure.py", line 159, in run_shell
    output = subprocess.check_output(cmd, stderr=stderr)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bazel', '--batch', '--bazelrc=/dev/null', 'version']' returned non-zero exit status 2

**Comment by feranick** [comment]
`wget https://github.com/bazelbuild/bazel/releases/download/2.0.0/bazel-2.0.0-installer-darwin-x86_64.sh`
`chmod +x bazel-1.2.1-installer-darwin-x86_64.sh`
`sudo ./bazel-1.2.1-installer-darwin-x86_64.sh`
`git clone https://github.com/tensorflow/tensorflow`
`cd tensorflow`
`git checkout v2.2.0-rc0`
`./configure`
(default is selected for all options)
`bazel build --config=opt --config=v2 --verbose_failures //tensorflow/tools/pip_package:build_pip_package`

**Comment by feranick** [comment]
Compilation still not possible with TF 2.2.0-rc2. Is there any plan to fix this for 2.2?

**Comment by feranick** [comment]
Compilation is also not possible as the latest master in git.

**Comment by jchia** [comment]
What if you just create an empty /Users/feranick/.netrc file?

**Comment by feranick** [comment]
Compilation is successful, all seems to work. This can be closed.
