### ISSUE TITLE
applications.resnet.ResNet50 means ResNet50 or ResNet34

### ISSUE THREAD

**Issue by CNOCycle** [tensorflow/tensorflow#37708]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/keras/applications/ResNet50

https://www.tensorflow.org/api_docs/python/tf/keras/applications/ResNet50V2

## Description of issue (what needs changing):

TF provides two type of ResNet models. The first is ResNet50 which is implemented by the following code:

https://github.com/keras-team/keras-applications/blob/master/keras_applications/resnet_common.py#L423-L441

where, `stack1` is **basic** version of residual function:
https://github.com/keras-team/keras-applications/blob/master/keras_applications/resnet_common.py#L64-L127

And the second is ResNet50V2 which is implemented by the following code:

https://github.com/keras-team/keras-applications/blob/b34c10628a0ab436542e9160f98de72b49084bbe/keras_applications/resnet_common.py#L483-L501

where, `stack2` is **bottleneck** version of residual function:
https://github.com/keras-team/keras-applications/blob/master/keras_applications/resnet_common.py#L175-192

The original [paper](https://arxiv.org/pdf/1512.03385.pdf) lists different type of ResNet in Table 1.

By the original  definition, the `ResNet50` should be 34-layer ResNet in the Table 1.

From the implementation by `pytorch`: 

https://github.com/pytorch/vision/blob/cc43e0a98368055d7a661651a2b9dbf28a19e533/torchvision/models/resnet.py#L244-L266

They claim the first one is ResNet34.

So I suggest that the `ResNet50` should change its name.

**Comment by jaketae** [comment]
I'm not entirely sure if this is the case. 

https://github.com/keras-team/keras-applications/blob/b34c10628a0ab436542e9160f98de72b49084bbe/keras_applications/resnet_common.py#L101

Here, you see that the convolution layers follows the structure as presented in Table 1 of the original paper. Notice how the number of filter goes from `filters`, `filters`, to `4 * filters`, whereas the stride goes from `1`, `kernel_size`, and `1`. I believe this is the correct implementation.

If I'm missing something, please let me know!

**Comment by CNOCycle** [comment]
Sorry, My fault. Your right.
