### ISSUE TITLE
Please consolidate the builder API's

### ISSUE THREAD

**Issue by Hvass-Labs** [tensorflow/tensorflow#3771]
In my opinion, a simple builder API is essential to TensorFlow programming because the procedure of constructing Neural Networks is otherwise complicated, repetitive and error-prone. But there are at least 5 different builder API's being developed in parallel:

* tf.contrib.layers
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/layers

* tf.contrib.slim
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/slim

* tf.contrib.learn (aka. TF Learn)
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/learn/python/learn

* TF Learn (same name, but apparently different from the above):
https://github.com/tflearn/tflearn

* Pretty Tensor
https://github.com/google/prettytensor

All of these add-on packages seem to be more or less in the early stages of development and lacking good documentation. But the API's appear to be very similar. So why not consolidate them into a single builder API that can become an integrated part of TensorFlow? It is very confusing for new users the way it is done now, and the development would get much further if people would work on a single builder API rather than 5 almost identical ones. The builder API is how most people will use TensorFlow so it shouldn't be in limbo like this.

Furthermore, I'm trying to put together some tutorials on YouTube, but I'm concerned that the API I'm using (Pretty Tensor) might become deprecated at some point.

I hope that a consolidated and official builder API will receive more attention from the dev-team. 

Thanks!

**Comment by sherrym** [comment]
Thanks for the great summary. We are in fact in the process of consolidating. Martin will elaborate.

**Comment by martinwicke** [comment]
contrib/layers and contrib/learn are APIs at different levels of
abstraction. They will be moved to TensorFlow core and will be part of
TensorFlow and hence supported indefinitely. If you're worried about
support and alignment with TensorFlow, this is your best bet.

contrib/slim as well as PrettyTensor are actively maintained by
teams/people at Google. Both will likely not disappear.

I cannot speak to external projects' prospects. tflearn.org is an
unfortunate name collision, we have no involvement in the project.

**Comment by Hvass-Labs** [comment]
Thanks for the clarification.

Will there be a change in how contrib/layers and contrib/learn will be imported and used once they're moved to TensorFlow core? If so, when do you expect to move them to core, so I can wait doing my tutorials until then?

**Comment by martinwicke** [comment]
We will maintain stubs in contrib for a while so importing from the old
location should continue to work. However until the code is moved to core
it is not subject to stability guarantees so it's very possible that the
interfaces change (although I believe the largest changes are behind us).
