### ISSUE TITLE
Problem with documentation tutorial

### ISSUE THREAD

**Issue by oke-aditya** [tensorflow/tensorflow#37713]
Hello tf team. I was trying the embedding tutorial as mentioned on the tf docs webpage.
[https://www.tensorflow.org/tutorials/text/word_embeddings](https://www.tensorflow.org/tutorials/text/word_embeddings)

The below two lines do give me error while I am following the same documentation as mentioned in the webpage.

train_batches = train_data.shuffle(1000).padded_batch(10)
test_batches = test_data.shuffle(1000).padded_batch(10)

![image](https://user-images.githubusercontent.com/47158509/77058288-3e3b4180-69fb-11ea-932a-df913d43c385.png)

I have manually tried to fix the error by putting padded_shapes as [None] or [None, None] but both of them have thrown error.

**Comment by oke-aditya** [comment]
- The same does not work in RNN tutorial as well. The API change of padded shape seems to have broken both the tutorials.

**Comment by khimraj** [comment]
@oke-aditya, try with 
`train_batches = train_data.shuffle(1000).padded_batch(10, padded_shapes=([None], []))
test_batches = test_data.shuffle(1000).padded_batch(10, padded_shapes=([None], []))`
I have successfully compiled above mentioned tutorial. For your reference link of gist is [here](https://colab.research.google.com/gist/khimraj/5dce9e670e6502294ab52a911c3bf370/untitled8.ipynb).
Hope it helps you.

**Comment by oke-aditya** [comment]
Thank you @khimraj  
- Seems to be working fine. 
- I think they need this as edit in documentation

**Comment by oke-aditya** [comment]
Maybe we can issue a pull request to fix this up. This  exists in two of the tutorials :smile:

**Comment by oke-aditya** [comment]
- Any explanation why the ` padded shape = ([None], [])` is the parameter.

**Comment by khimraj** [comment]
@oke-aditya, please refer [this](https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/python/data/ops/dataset_ops.py#L1383-L1481)

**Comment by MarkDaoust** [comment]
I'll add a note to all of these to clarify.

**Comment by oke-aditya** [comment]
- Please fix in [https://www.tensorflow.org/tutorials/text/text_classification_rnn](https://www.tensorflow.org/tutorials/text/text_classification_rnn) as well. Just the simple change should. @khimraj

**Comment by oke-aditya** [comment]
I get the problem. In tf v2.1 API the argument was mandatory. Whereas in tf v 2.2rc API it is optional. This seems to confuse on the documentation page. The tutorial should mention this point. Then it would be clear.

**Comment by MarkDaoust** [comment]
@oke-aditya   that commit of mine (e449e964532654e11dc25ebe75d3e89c05266d51) clarifies this in all the tutorials that use `padded_batch`. This should be published to tensorflow.org within 24h.

Thanks for reporting.

**Comment by oke-aditya** [comment]
- Thank you for that fix. Really great work. Crystal clear in docs now :+1:
