### ISSUE TITLE
Draw boundary box after classification

### ISSUE THREAD

**Issue by AlturRang** [tensorflow/tensorflow#37718]
Hi, 
My problem is: I would to draw a boundary around the object was predicted by a neural network. Here I use a vgg16 model (you can see the code below, it's very simple). But after the last line of code, where I predict the classes of the object. I would to draw a box but I don't how I can do that.
Someone have a tutorial for me ?
Thanks
[pre_entrained_model_vgg_16.py.tar.gz](https://github.com/tensorflow/tensorflow/files/4355415/pre_entrained_model_vgg_16.py.tar.gz)

**Comment by maxkaustav** [comment]
try this one
`import tensorflow as tf`
`import matplotlib.pyplot as plt`
`import numpy as np`
`img = tf.zeros([1, 255, 255, 3])`
`img`
`plt.imshow(img[0])`
`box = np.array([0.1, 0.1, 0.78, 0.78
               ])`
`boxes`
`colors = np.array([[0.0, 1.0, 1.0]])`
`img2=tf.image.draw_bounding_boxes(img, boxes, colors)`
`plt.imshow(img2[0])`

**Comment by ravikyram** [comment]
@AlturRang 

Thanks for reporting the issue. As @maxkaustav code please define boxes as well in the code
```
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
img = tf.zeros([1, 255, 255, 3])
img
#boxes = tf.constant([[[0.05, 0.05, 0.9, 0.7], [0.3, 0.4, 0.5, 0.6]]])
boxes = tf.constant([[[0.05, 0.05, 0.9, 0.7]]])

plt.imshow(img[0])
box = np.array([0.1, 0.1, 0.78, 0.78 ])
boxes
colors = np.array([[0.0, 1.0, 1.0]])
img2=tf.image.draw_bounding_boxes(img, boxes, colors)
plt.imshow(img2[0])
```
Please, refer the[ link](https://www.tensorflow.org/api_docs/python/tf/image/draw_bounding_boxes) and see if it helps you. Thanks!

**Comment by AlturRang** [comment]
thank for your quick answer and for the help
