### ISSUE TITLE
Issue with calling tf.device

### ISSUE THREAD

**Issue by SwagJ** [tensorflow/tensorflow#37727]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Ubuntu19.10
- From pip
- TensorFlow version:2.1.0
- Python version:3.7.4
- Installed using virtualenv? pip? conda?:pip
- GCC/Compiler version (if compiling from source):7.3.0
- CUDA/cuDNN version:10.1
- GPU model and memory: RTX2060 Super 8G

**Describe the problem**

When calling with
                    tf.device(tf.compat.v1.train.replica_device_setter(
                    worker_device=worker, ps_device='/cpu:0', ps_tasks=1)):
It gives error of not supporting functions. 

**Any other info / logs**
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
  File "export_detections.py", line 38, in <module>
    with experiment._init_graph(config, with_dataset=True) as (net, dataset):
  File "/home/hashswan/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/hashswan/Desktop/SuperPoint/superpoint/experiment.py", line 73, in _init_graph
    n_gpus=n_gpus, **config['model'])
  File "/home/hashswan/Desktop/SuperPoint/superpoint/models/base_model.py", line 122, in __init__
    self._build_graph()
  File "/home/hashswan/Desktop/SuperPoint/superpoint/models/base_model.py", line 275, in _build_graph
    self._pred_graph(self.pred_in)
  File "/home/hashswan/Desktop/SuperPoint/superpoint/models/base_model.py", line 223, in _pred_graph
    pred_out = self._gpu_tower(data, Mode.PRED, self.config['pred_batch_size'])
  File "/home/hashswan/Desktop/SuperPoint/superpoint/models/base_model.py", line 157, in _gpu_tower
    worker_device=worker, ps_device='/cpu:0', ps_tasks=1)):
  File "/home/hashswan/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 5078, in device_v2
    raise RuntimeError("tf.device does not support functions.")
RuntimeError: tf.device does not support functions.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by amahendrakar** [comment]
@SwagJ,
Looks like the given code is incomplete. Please find the gist [here](https://colab.research.google.com/gist/amahendrakar/6b0b4f8af34c85e9652bffaa7e8f0ac6/37727.ipynb).

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by SwagJ** [comment]
@amahendrakar 
Hi, 

That was the code in my project. I revised it into this in colab: tf.device(tf.compat.v1.train.replica_device_setter(worker_device='/gpu:0',ps_device='/cpu:0', ps_tasks=1))

And the error message is the same. 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: tf.device does not support functions.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/393b1d62ef3db6dede9e491813bc6326/37727.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/d50d8540251b226a65c5c4c35462c6e6/tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by woj-i** [comment]
What is the follow-up? Is any ticket for this bug?

**Comment by cmal** [comment]
Same error when calling

```
with tf.device(tf.compat.v1.train.replica_device_setter(1, worker_device=worker_device)):
```

**Comment by amahendrakar** [comment]
@woj-i, @cmal,
Could y'all please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
