### ISSUE TITLE
Partial shapes for keras.InputLayer with sparse=True 

### ISSUE THREAD

**Issue by ngc92** [tensorflow/tensorflow#37721]
**System information**
- TensorFlow version (you are using): 2.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
It is currently not possible to use input `SparseTensor` into e.g. `keras.Sequential` with partially defined shapes. This is because `SparseTensors` need to be declared specifically, thus necessitating the use of `keras.InputLayer` as the fiirst layer in the model. 

If the shape of `keras.InputLayer` for sparse inputs is not fully defined (including the batch size), the
produced `SparseTensor` will have `dense_shape` where only the rank is defined.
This happens because unless the `dense_shape`is fully defined, a `placeholder` will be used for feeding in  the `dense_shape`, removing the partial shape information.

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
This will make models of the form
```
Sequenctial([
   InputLayer(shape=(num_features,), sparse=True), 
  Dense(num_units)
])
```
work, as they require partial shape for the input of the `Dense` layer.

**Comment by rmothukuru** [comment]
@ngc92,
Sorry for the delayed response. Since it is more than an year since this issue has been raised, can you please refer the [latest documentation of Sparse Tensor](https://www.tensorflow.org/api_docs/python/tf/sparse/SparseTensor) and let us know if this **`Feature`** is implemented? Thanks!

**Comment by ngc92** [comment]
It appears that this works now. It is also shown in the documentation here 
https://www.tensorflow.org/guide/sparse_tensor#tfkeras

**Comment by deepakagrawal** [comment]
This seems to be working only for 2d sparse inputs. I have a SparseTensor with partial shape `(batch_size, None, n_features)`, where `batch_size` and `n_features` are fixed. And I create a model as shown here https://www.tensorflow.org/guide/sparse_tensor#tfkeras

My code

```python
import tensorflow as tf
import numpy as np

x = tf.keras.Input(batch_shape=(6,None,4), sparse=True)
y = tf.keras.layers.Dense(4)(x)
model = tf.keras.Model(x, y)

a = np.random.random((6,10,4))
sparse_data = tf.sparse.from_dense(a)
model(sparse_data)
model.summary()
model.predict(sparse_data)
```

and I receive the following error 

```
Traceback (most recent call last):
  File "C:\Users\099391\OneDrive - American Airlines, Inc\Documents\Projects\NP_E-QSI\srcc\test.py", line 5, in <module>
    y = tf.keras.layers.Dense(4)(x)
  File "C:\Users\099391\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\099391\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 545, in make_tensor_proto
    raise TypeError(f"Failed to convert elements of {values} to Tensor. "
TypeError: Exception encountered when calling layer "dense" (type Dense).

Failed to convert elements of SparseTensor(indices=Tensor("Placeholder_1:0", shape=(None, 3), dtype=int64), values=Tensor("Placeholder:0", shape=(None,), dtype=float32), dense_shape=Tensor("PlaceholderWithDefault:0", shape=(3,), dtype=int64)) to Tensor. Consider casting elements to a supported type. See https://www.tensorflow.org/api_docs/python/tf/dtypes for supported TF dtypes.

Call arguments received:
  • inputs=<tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x000001F193E519A0>
```
