### ISSUE TITLE
I get completely Wrong Results/Prediction(No result or wrong predictions) when I use Tflite format.

### ISSUE THREAD

**Issue by omkardhawal21** [tensorflow/tensorflow#37728]
**System information**
- OS Platform and Distribution : Linux Ubuntu 18.04.4 LTS
- TensorFlow installed from (source or binary): pip3 install --user --upgrade tensorflow
- TensorFlow version (or github SHA if from source): 1.14.0

I get good results on frozen_inference_graph.pb but I get completely Wrong Results/Prediction(No result or wrong predictions) when I convert it to Tflite format.
I trained two models with different datasets(road signs and fruits) and got wrong results in both.

Initially I followed [this Blog](https://towardsdatascience.com/deeppicar-part-6-963334b2abe0) for road sign detection.
When I use my Tflite file in android app, it always returns 0 results . So I thought,Maybe there is something wrong with my App code. But then I created an under trained model on same data set(100 steps) and then used that in my App. This time,results were returned but obviously they were completely wrong. However,It helped me understand that there was something wrong with my Tflite file.
Note: I used Android app from official repo of Tensorflow object detection.

Then I followed [ this Medium Blog](https://medium.com/datadriveninvestor/how-to-train-your-own-custom-model-with-tensorflow-object-detection-api-and-deploy-it-into-android-aeacab7fa76f) for fruits detection.
Here also I got good results on frozen_inference_graph.pb but my tflite was giving completely wrong result by detecting any objects and background randomly. 
Here is the [notebook](https://colab.research.google.com/drive/1khXaKmKUb6OE7OAYgkj0KKM6lZ7DtaUG) for fruit detection.

I will be explaining steps I followed to generate Tflite file for road sign detection as per https://towardsdatascience.com/deeppicar-part-6-963334b2abe0

Please refer  [my Github Repo](https://github.com/omkardhawal21/my_tflite) for some essential files like my Mobilenet -SSD mOdel ,  model.ckpt-2000 , frozen_inference_graph.pb , tflite_graph.pb and sign.tflite files 

I have used a non-Quantized model for training on the same dataset and trained for 2000 steps.
My tensorflow version is 1.14

I follwed the below steps to obtained Tflite file

**1)Train Model**

python3 model_main.py \
--pipeline_config_path=/machine-learning/ssd_mobilenet_v2_coco_2018_03_29/pipeline.config \
--model_dir=/home/omkar/machine-learning/road_sign_detection/ \
--alsologtostderr \
--num_train_steps=2000 \
--num_eval_steps=50

**2) Export tflite_graph.pb using model.ckpt-2000 obtained after Training.** 

python3 export_tflite_ssd_graph.py \
--pipeline_config_path='/machine-learning/ssd_mobilenet_v2_coco_2018_03_29/pipeline.config' \
--trained_checkpoint_prefix='/machine-learning/road_sign_detection/model.ckpt-2000' \
--output_directory='/home/omkar/machine-learning/road_sign_detection/tflite' \
--add_postprocessing_op=true

**3) Generate Tflite file from tflite_graph.pb**

tflite_convert \
--output_file='/machine-learning/road_sign_detection/tflite/mysign.tflite' \
--graph_def_file='/machine-learning/road_sign_detection/tflite/tflite_graph.pb' \ --input_arrays='normalized_input_image_tensor' \
--inference_type=FLOAT \
--output_arrays='TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3' \
--mean_values=128 \
--std_dev_values=128 \
--input_shapes=1,300,300,3 \
--change_concat_input_ranges=false \
--allow_nudging_weights_to_use_fast_gemm_kernel=true 
--allow_custom_ops

Note: I've also tried using TOCO to convert to Tflite but achieved same results.

**Failure details**
 Tflite produces completely wrong Results .
On road sign detection model, there were no results/ zero predicted objects.
On fruit detection model there were too many wrong predictions/results.

Am I doing something wrong ? 
Is there something wrong with the process,commands ?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!

**Comment by ArefAz** [comment]
@omkardhawal21 

Hi, I know it is closed but I'm having the exact same problem as you did.

Could you find the solution?

Thanks.

**Comment by omkardhawal21** [comment]
@ArefAz 
When I used Google collab to convert the same model to tflite, I got the desired result. I think it was some version issue on my local PC.

Please refer my [notebook](https://colab.research.google.com/drive/1khXaKmKUb6OE7OAYgkj0KKM6lZ7DtaUG?usp=sharing)

Refer the **Exporting Tflite Graph** section and the sections ahead. 

Also please check if your data is good (has good variety in background). 
Thank you

**Comment by ArefAz** [comment]
I was able to fix this issue by using this command:

`tflite_convert --graph_def_file tflite_inference_graph/tflite_graph.pb --output_file=amin/amin_detect.tflite --output_format=TFLITE --input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'  --inference_type=QUANTIZED_UINT8 --mean_values=128 --std_dev_values=127 --change_concat_input_ranges=false --allow_custom_ops`

I was using toco which is deprecated. I wanted to use a quantized model so I trained **ssdlite_mobilenet_v2_coco_2018_05_09** and added graph_rewriter at the end of my config file.
