### ISSUE TITLE
kernel_concatenation_test fails with "Aborted (Core dumped)"

### ISSUE THREAD

**Issue by jenselofsson** [tensorflow/tensorflow#37739]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): 765ddddb22
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Linux x86_64

**Describe the problem**
Running
`$ make -f tensorflow/lite/micro/tools/make/Makefile test_kernel_concatenation_test`

results in the following output
`tensorflow/lite/micro/testing/test_linux_binary.sh: line 46:  4201 Aborted                 (core dumped) $1 > ${MICRO_LOG_FILENAME} 2>&1
tensorflow/lite/micro/tools/make/Makefile:321: recipe for target 'test_kernel_concatenation_test' failed
make: *** [test_kernel_concatenation_test] Error 134
`

**Please provide the exact sequence of commands/steps when you ran into the problem**
`$ make -f tensorflow/lite/micro/tools/make/Makefile test_kernel_concatenation_test`

**Comment by advaitjain** [comment]
Confirming that I see the test segfault, though I am able to build it. Because of the recent flatbuffer version upgrade, please try ```make clean clean_downloads``` and then try to run the test.

We will look into the test segfaulting.

```
$ make -f tensorflow/lite/micro/tools/make/Makefile test_kernel_concatenation_test
tensorflow/lite/micro/testing/test_linux_binary.sh tensorflow/lite/micro/tools/make/gen/linux_x86_64/bin/kernel_concatenation_test '~~~ALL TESTS PASSED~~~'
Segmentation fault
tensorflow/lite/micro/tools/make/gen/linux_x86_64/bin/kernel_concatenation_test: FAIL - '~~~ALL TESTS PASSED~~~' not found in logs.
Testing TwoInputsAllAxesCombinations
Segmentation fault
make: *** [tensorflow/lite/micro/tools/make/Makefile:321: test_kernel_concatenation_test] Error 1
```

**Comment by rockyrhodes** [comment]
I just tried this and it worked for me.  @jenselofsson can you confirm that this is now fixed for you as well?
