### ISSUE TITLE
TensorFlow Lite Error: tensorflow/lite/kernels/concatenation.cc:52 axis >= 0 was not true.

### ISSUE THREAD

**Issue by yuanlida** [tensorflow/tensorflow#37733]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):MACOS Catilina 10.15.3
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source):1.15.2

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.
git clone https://github.com/yuanlida/nc.git
Firstly run this file first and you can get saved_model in one minute.
https://github.com/yuanlida/nc/blob/master/bilstm_onefile/bi_lstm_mini_net.py
Then run this file and you can get a tflite file named bi-lstm.tflite in the path ../model/Bi-LSTM
https://github.com/yuanlida/nc/blob/master/tf_converter.py
The copy this files to the Xcode project, I can't allocateTensors.
```
# Copy and paste here the exact command
I found this problem is coused by this python method:

                _output = bidirectional_dynamic_rnn(
                    cell_fw, cell_bw, char_embeddings,
                    # sequence_length=word_lengths,
                    dtype=tf.float32,
                    time_major=True
                )

                _, ((_, output_fw), (_, output_bw)) = _output
                output = tf.concat([output_fw, output_bw], axis=-1)
The Swift code is :
      guard let modelPath = Bundle.main.path(forResource: "bi-lstm", ofType: "tflite") else {
            print("Failed to load the model file.")
            return
        }

        var options = Interpreter.Options()
        options.threadCount = 4
            let interpreter = try Interpreter(modelPath: modelPath, options: options)
            try interpreter.allocateTensors()
            print(interpreter.inputTensorCount)
```

**The output from the converter invocation**

```
2020-03-20 07:49:14.148393+0800 SignatureTextClassfication[25938:3910176] Initialized TensorFlow Lite runtime.
TensorFlow Lite Error: tensorflow/lite/kernels/concatenation.cc:52 axis >= 0 was not true.
TensorFlow Lite Error: Node number 1 (CONCATENATION) failed to prepare.

Failed to create the interpreter with error: Failed to allocate memory for input tensors.
```

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
[bi-lstm.tflite.zip](https://github.com/tensorflow/tensorflow/files/4357639/bi-lstm.tflite.zip)

```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by yuanlida** [comment]
== check python ===================================================
python version: 3.7.6
python branch: 
python build version: ('default', 'Jan  8 2020 13:42:34')
python compiler version: Clang 4.0.1 (tags/RELEASE_401/final)
python implementation: CPython


== check os platform ===============================================
os: Darwin
os kernel version: Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
os release version: 19.3.0
os platform: Darwin-19.3.0-x86_64-i386-64bit
linux distribution: ('', '', '')
linux os distribution: ('', '', '')
mac version: ('10.15.3', ('', '', ''), 'x86_64')
uname: uname_result(system='Darwin', node='lidayuandeMacBook-Pro.local', release='19.3.0', version='Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64', machine='x86_64', processor='i386')
architecture: ('64bit', '')
machine: x86_64


== are we in docker =============================================
No

== compiler =====================================================
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

== check pips ===================================================
numpy                1.18.1              
protobuf             3.11.3              
tensorflow           2.1.0               
tensorflow-estimator 2.1.0               

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.version.VERSION = 2.1.0
tf.version.GIT_VERSION = v2.1.0-rc2-17-ge5bf8de410
tf.version.COMPILER_VERSION = 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
evn.sh: line 145: nvidia-smi: command not found

== cuda libs  ===================================================

== tensorflow installed from info ==================
Name: tensorflow
Version: 2.1.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /Users/lidayuan/opt/anaconda3/envs/py37/lib/python3.7/site-packages
Required-by: 

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(3, 7, 6, 'final', 0)

== bazel version  ===============================================

**Comment by yuanlida** [comment]
When change the code to :
                output = tf.concat([output_fw, output_bw], axis=1)
It will cause this problem:
"""
2020-03-20 10:31:13.355855+0800 SignatureTextClassfication[60881:4131912] Initialized TensorFlow Lite runtime.
TensorFlow Lite Error: tensorflow/lite/kernels/concatenation.cc:53 axis < t0->dims->size was not true.
TensorFlow Lite Error: Node number 1 (CONCATENATION) failed to prepare.
"""

**Comment by yuanlida** [comment]
I can test it by python script now.
import tensorflow as tf

interpreter=tf.lite.Interpreter(model_path='./model/Bi-LSTM/bi-lstm.tflite')

interpreter.allocate_tensors()

**Comment by Saduf2019** [comment]
@yuanlida 
could you please let us know the python version used by you.
please refer to [this link](https://github.com/tensorflow/tensorflow/issues/34345), for reference.

**Comment by yuanlida** [comment]
System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): 1.15.2
Python version: 3.7.6

**Comment by yuanlida** [comment]
I test the program in TF 2.1 TF2.2 TF1.5 and python 3.6 python 3.7, I got the same error.

**Comment by yuanlida** [comment]
Why removed the label?

**Comment by yuanlida** [comment]
I am waiting...

**Comment by godweiyang** [comment]
I come across the same issue

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
