### ISSUE TITLE
STM32F746NG Hello World example fails in /tensorflow/lite/micro/kernels/cmsis-nn/conv.cc

### ISSUE THREAD

**Issue by tom-gall** [tensorflow/tensorflow#37730]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Pop!_OS 19.10"
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): 
commit bfafc1acef59ff5a7ba2bf2675350812e552d5ad
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):
arm mbed

mbed config --list
[mbed] Global config:
GCC_ARM_PATH=/opt/gcc-arm-none-eabi-9-2019-q4-major/bin/
ARM_PATH=/opt/gcc-arm-none-eabi-9-2019-q4-major/bin/arm-none-eabi-gcc

**Describe the problem**
when building tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4/prj/hello_world/mbed$
mbed compile -m DISCO_F746NG -t GCC_ARM

the following build time error is returned : 
Compile [ 79.9%]: conv.cc
[Error] arm_nnsupportfunctions.h@505,39: 'Q31_MIN' was not declared in this scope
[Error] arm_nnsupportfunctions.h@507,18: 'Q31_MAX' was not declared in this scope
[Error] arm_nnsupportfunctions.h@660,36: 'Q31_MAX' was not declared in this scope
[Error] arm_nnsupportfunctions.h@667,64: 'Q31_MAX' was not declared in this scope
[Error] arm_nnsupportfunctions.h@668,65: 'Q31_MIN' was not declared in this scope
[Error] arm_nnsupportfunctions.h@674,49: 'Q31_MAX' was not declared in this scope
[ERROR] '_queue.SimpleQueue' object has no attribute 'queue'

and with -v added 

Compile [ 74.9%]: conv.cc
Compile: /opt/gcc-arm-none-eabi-9-2019-q4-major/bin/arm-none-eabi-g++ -std=gnu++14 -fno-rtti -Wvla -c -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -ffunction-sections -fdata-sections -funsigned-char -MMD -fno-delete-null-pointer-checks -fomit-frame-pointer -Os -g -DMBED_TRAP_ERRORS_ENABLED=1 -mcpu=cortex-m7 -mthumb -mfpu=fpv5-sp-d16 -mfloat-abi=softfp -DMBED_ROM1_START=0x200000 -DMBED_ROM1_SIZE=0x100000 -DMBED_ROM_START=0x8000000 -DMBED_ROM_SIZE=0x100000 -DMBED_RAM_START=0x20010000 -DMBED_RAM_SIZE=0x40000 -DMBED_RAM1_START=0x20000000 -DMBED_RAM1_SIZE=0x10000 -D__MBED__=1 -DDEVICE_ANALOGOUT=1 -DDEVICE_STDIO_MESSAGES=1 -D__CMSIS_RTOS -DTARGET_NAME=DISCO_F746NG -DTARGET_RTOS_M4_M7 -DCOMPONENT_PSA_SRV_IMPL=1 -DARM_MATH_CM7 -DTARGET_M7 -DTARGET_STM32F7 -DDEVICE_CAN=1 -DTARGET_CORTEX -DDEVICE_PWMOUT=1 -DCOMPONENT_QSPIF=1 -D__FPU_PRESENT=1 -DTARGET_STM32F746 -D__MBED_CMSIS_RTOS_CM -DDEVICE_PORTOUT=1 -DMBED_TICKLESS -DDEVICE_ANALOGIN=1 -DDEVICE_I2C_ASYNCH=1 -DTARGET_STM -DDEVICE_CRC=1 -DTARGET_CORTEX_M -DUSE_HAL_DRIVER -DDEVICE_I2CSLAVE=1 -DDEVICE_SERIAL_FC=1 -DCOMPONENT_FLASHIAP=1 -DTARGET_STM32F746NG -DTARGET_LIKE_CORTEX_M7 -D__CORTEX_M7 -DDEVICE_USBDEVICE=1 -DTARGET_LIKE_MBED -DDEVICE_PORTIN=1 -DDEVICE_WATCHDOG=1 -DDEVICE_SERIAL_ASYNCH=1 -DDEVICE_PORTINOUT=1 -DDEVICE_SPI=1 -DTOOLCHAIN_GCC_ARM -DDEVICE_SLEEP=1 -DUSBHOST_OTHER -DDEVICE_TRNG=1 -DTARGET_FAMILY_STM32 -DDEVICE_LPTICKER=1 -DTARGET_FF_ARDUINO -DDEVICE_RTC=1 -DEXTRA_IDLE_STACK_REQUIRED -DTRANSACTION_QUEUE_SIZE_SPI=2 -DDEVICE_FLASH=1 -DDEVICE_SPI_ASYNCH=1 -DCOMPONENT_PSA_SRV_EMUL=1 -DDEVICE_INTERRUPTIN=1 -DUSE_FULL_LL_DRIVER -DDEVICE_USTICKER=1 -DTOOLCHAIN_GCC -DDEVICE_MPU=1 -DTARGET_STM_EMAC -DTARGET_RELEASE -DMBED_BUILD_TIMESTAMP=1584658515.2890425 -DTARGET_STM32F746xG -DDEVICE_RESET_REASON=1 -DDEVICE_EMAC=1 -DDEVICE_SERIAL=1 -DDEVICE_QSPI=1 -DUSB_STM_HAL -DCOMPONENT_NSPE=1 -DDEVICE_I2C=1 -DDEVICE_SPISLAVE=1 -DTARGET_DISCO_F746NG @./BUILD/DISCO_F746NG/GCC_ARM/.includes_12aa10db82ce4f9a526c01c2017b7c4b.txt -include ./BUILD/DISCO_F746NG/GCC_ARM/mbed_config.h -MD -MF BUILD/DISCO_F746NG/GCC_ARM/tensorflow/lite/micro/kernels/cmsis-nn/conv.d -o BUILD/DISCO_F746NG/GCC_ARM/tensorflow/lite/micro/kernels/cmsis-nn/conv.o ./tensorflow/lite/micro/kernels/cmsis-nn/conv.cc
[Error] arm_nnsupportfunctions.h@505,39: 'Q31_MIN' was not declared in this scope
[Error] arm_nnsupportfunctions.h@507,18: 'Q31_MAX' was not declared in this scope
[Error] arm_nnsupportfunctions.h@660,36: 'Q31_MAX' was not declared in this scope
[Error] arm_nnsupportfunctions.h@667,64: 'Q31_MAX' was not declared in this scope
[Error] arm_nnsupportfunctions.h@668,65: 'Q31_MIN' was not declared in this scope
[Error] arm_nnsupportfunctions.h@674,49: 'Q31_MAX' was not declared in this scope
[DEBUG] Return: 1
[DEBUG] Output: In file included from ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnfunctions.h:118,
[DEBUG] Output:                  from ./tensorflow/lite/micro/kernels/cmsis-nn/conv.cc:18:
[DEBUG] Output: ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h: In function 'q31_t arm_nn_sat_doubling_high_mult(q31_t, q31_t)':
[DEBUG] Output: ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h:505:39: error: 'Q31_MIN' was not declared in this scope
[DEBUG] Output:   505 |     if ((m1 == m2) && (m1 == (int32_t)Q31_MIN))
[DEBUG] Output:       |                                       ^~~~~~~
[DEBUG] Output: ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h:507:18: error: 'Q31_MAX' was not declared in this scope
[DEBUG] Output:   507 |         result = Q31_MAX;
[DEBUG] Output:       |                  ^~~~~~~
[DEBUG] Output: In file included from ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnfunctions.h:118,
[DEBUG] Output:                  from ./tensorflow/lite/micro/kernels/cmsis-nn/conv.cc:18:
[DEBUG] Output: ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h: In function 'int32_t arm_nn_exp_on_negative_values(int32_t)':
[DEBUG] Output: ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h:660:36: error: 'Q31_MAX' was not declared in this scope
[DEBUG] Output:   660 |     return SELECT_USING_MASK(mask, Q31_MAX, result);
[DEBUG] Output:       |                                    ^~~~~~~
[DEBUG] Output: ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h:45:50: note: in definition of macro 'SELECT_USING_MASK'
[DEBUG] Output:    45 | #define SELECT_USING_MASK(mask, a, b) ((mask) & (a)) ^ (~(mask) & (b))
[DEBUG] Output:       |                                                  ^
[DEBUG] Output: ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h: In function 'q31_t arm_nn_mult_by_power_of_two(int32_t, int32_t)':
[DEBUG] Output: ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h:667:64: error: 'Q31_MAX' was not declared in this scope
[DEBUG] Output:   667 |     result = SELECT_USING_MASK(MASK_IF_NON_ZERO(val > thresh), Q31_MAX, result);
[DEBUG] Output:       |                                                                ^~~~~~~
[DEBUG] Output: ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h:45:50: note: in definition of macro 'SELECT_USING_MASK'
[DEBUG] Output:    45 | #define SELECT_USING_MASK(mask, a, b) ((mask) & (a)) ^ (~(mask) & (b))
[DEBUG] Output:       |                                                  ^
[DEBUG] Output: ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h:668:65: error: 'Q31_MIN' was not declared in this scope
[DEBUG] Output:   668 |     result = SELECT_USING_MASK(MASK_IF_NON_ZERO(val < -thresh), Q31_MIN, result);
[DEBUG] Output:       |                                                                 ^~~~~~~
[DEBUG] Output: ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h:45:50: note: in definition of macro 'SELECT_USING_MASK'
[DEBUG] Output:    45 | #define SELECT_USING_MASK(mask, a, b) ((mask) & (a)) ^ (~(mask) & (b))
[DEBUG] Output:       |                                                  ^
[DEBUG] Output: In file included from ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnfunctions.h:118,
[DEBUG] Output:                  from ./tensorflow/lite/micro/kernels/cmsis-nn/conv.cc:18:
[DEBUG] Output: ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h: In function 'int32_t arm_nn_one_over_one_plus_x_for_x_in_0_1(int32_t)':
[DEBUG] Output: ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h:674:49: error: 'Q31_MAX' was not declared in this scope
[DEBUG] Output:   674 |     const int64_t sum = (int64_t)val + (int64_t)Q31_MAX;
[DEBUG] Output:       |                                                 ^~~~~~~
Traceback (most recent call last):
  File "/home/tgall/tinyml/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4/prj/hello_world/mbed/mbed-os/tools/toolchains/mbed_toolchain.py", line 555, in compile_queue
    res['command']
  File "/home/tgall/tinyml/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4/prj/hello_world/mbed/mbed-os/tools/toolchains/mbed_toolchain.py", line 682, in compile_output
    raise ToolException(stderr)
tools.utils.ToolException: In file included from ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnfunctions.h:118,
                 from ./tensorflow/lite/micro/kernels/cmsis-nn/conv.cc:18:
./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h: In function 'q31_t arm_nn_sat_doubling_high_mult(q31_t, q31_t)':
./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h:505:39: error: 'Q31_MIN' was not declared in this scope
  505 |     if ((m1 == m2) && (m1 == (int32_t)Q31_MIN))
      |                                       ^~~~~~~
./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h:507:18: error: 'Q31_MAX' was not declared in this scope
  507 |         result = Q31_MAX;
      |                  ^~~~~~~
In file included from ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnfunctions.h:118,
                 from ./tensorflow/lite/micro/kernels/cmsis-nn/conv.cc:18:
./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h: In function 'int32_t arm_nn_exp_on_negative_values(int32_t)':
./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h:660:36: error: 'Q31_MAX' was not declared in this scope
  660 |     return SELECT_USING_MASK(mask, Q31_MAX, result);
      |                                    ^~~~~~~
./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h:45:50: note: in definition of macro 'SELECT_USING_MASK'
   45 | #define SELECT_USING_MASK(mask, a, b) ((mask) & (a)) ^ (~(mask) & (b))
      |                                                  ^
./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h: In function 'q31_t arm_nn_mult_by_power_of_two(int32_t, int32_t)':
./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h:667:64: error: 'Q31_MAX' was not declared in this scope
  667 |     result = SELECT_USING_MASK(MASK_IF_NON_ZERO(val > thresh), Q31_MAX, result);
      |                                                                ^~~~~~~
./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h:45:50: note: in definition of macro 'SELECT_USING_MASK'
   45 | #define SELECT_USING_MASK(mask, a, b) ((mask) & (a)) ^ (~(mask) & (b))
      |                                                  ^
./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h:668:65: error: 'Q31_MIN' was not declared in this scope
  668 |     result = SELECT_USING_MASK(MASK_IF_NON_ZERO(val < -thresh), Q31_MIN, result);
      |                                                                 ^~~~~~~
./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h:45:50: note: in definition of macro 'SELECT_USING_MASK'
   45 | #define SELECT_USING_MASK(mask, a, b) ((mask) & (a)) ^ (~(mask) & (b))
      |                                                  ^
In file included from ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnfunctions.h:118,
                 from ./tensorflow/lite/micro/kernels/cmsis-nn/conv.cc:18:
./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h: In function 'int32_t arm_nn_one_over_one_plus_x_for_x_in_0_1(int32_t)':
./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Include/arm_nnsupportfunctions.h:674:49: error: 'Q31_MAX' was not declared in this scope
  674 |     const int64_t sum = (int64_t)val + (int64_t)Q31_MAX;
      |                                                 ^~~~~~~

Looking at it the declarations for Q31_MAX etc seem to be in arm_math.h which seems to be found in : 
tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4/prj/he
llo_world/mbed/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/DSP/Include

~/tinyml/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4/prj/he
llo_world/mbed/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/DSP/Include$ ls
arm_common_tables.h  arm_helium_utils.h  arm_mve_tables.h
arm_const_structs.h  arm_math.h          arm_vec_math.h

 

**Please provide the exact sequence of commands/steps when you ran into the problem**

**Comment by tom-gall** [comment]
A slight update: 

If you add the following to micro/tools/make/gen/mbed_cortex-m4/prj/hello_world/mbed/mbed-os/cmsis/TARGET_CORTEX_M/arm_math.h
math.h  the build will be successful : 

#define Q31_MAX   ((q31_t)(0x7FFFFFFFL))
#define Q15_MAX   ((q15_t)(0x7FFF))
#define Q7_MAX    ((q7_t)(0x7F))
#define Q31_MIN   ((q31_t)(0x80000000L))
#define Q15_MIN   ((q15_t)(0x8000))
#define Q7_MIN    ((q7_t)(0x80))

#define Q31_ABSMAX   ((q31_t)(0x7FFFFFFFL))
#define Q15_ABSMAX   ((q15_t)(0x7FFF))
#define Q7_ABSMAX    ((q7_t)(0x7F))
#define Q31_ABSMIN   ((q31_t)0)
#define Q15_ABSMIN   ((q15_t)0)
#define Q7_ABSMIN    ((q7_t)0)

Looking upstream to the mbed project there is this bit where they've entirely removed arm_math.h! 

https://github.com/ARMmbed/mbed-os/commit/5a985a7da5b93e7fb4be92e015f663d5619033ee

**Comment by freddan80** [comment]
Hi @tom-gall , I think we discussed this briefly in the TFLu SIG gitter forum, but I'll add some info here as well for visibility. There is a copy of the CMSIS arm_math.h in the mbed folder structure (`/mbed-os/cmsis/TARGET_CORTEX_M/arm_math.h` as you mention). It may conflict with the arm_math.h that is downloaded directly from the CMSIS repo via the TFLu CMSIS third party download mechanism. This version of arm_math.h is typically newer. Here's some more info on the topic for a sustainable solution: https://github.com/ARMmbed/mbed-os/issues/12568#issuecomment-611436173. Short term, I believe this can be fixed by replacing arm_math.h as described here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/kernels/cmsis-nn/README.md

**Comment by sushreebarsa** [comment]
@tom-gall Could you please update as per the above comment and let us know if the issue still persists? Thanks!

**Comment by EmbeddedSysDesign** [comment]
Hello, I am facing the same issue during the compilation of a project Hello Edge KWS using mbedOS. Please share the same files that you used in example. See my error details below;

Compile [ 98.4%]: arm_max_pool_s8.c
Compile [ 98.6%]: arm_svdf_s8.c
Compile [ 98.7%]: arm_softmax_s8.c
Compile [ 98.9%]: arm_softmax_s8_s16.c
Compile [ 99.0%]: arm_softmax_s16.c
Compile [ 99.2%]: arm_nn_softmax_common_s8.c
Compile [ 99.3%]: arm_softmax_u8.c
Compile [ 99.4%]: plot_utils.cpp
[Error] arm_nnsupportfunctions.h@681,54: '__SXTB16_RORn' was not declared in this scope
[ERROR] In file included from ../Source/local_NN/local_NN.h:1:0,
from ../Source/NN/DS_CNN/ds_cnn.h:24,
from ../Source/KWS/KWS_DS_CNN/kws_ds_cnn.h:23,
from ../Source/KWS_F746NG/kws_f746ng.h:23,
from ../Examples/realtime_test\plot_utils.h:19,
from ../Examples/realtime_test\plot_utils.cpp:19:
../CMSIS_5/CMSIS/NN/Include/arm_nnsupportfunctions.h: In function 'const int8_t* read_and_pad(const int8_t*, int32_t*, int32_t*)':
../CMSIS_5/CMSIS/NN/Include/arm_nnsupportfunctions.h:681:54: error: '__SXTB16_RORn' was not declared in this scope
int32_t inAbuf1 = __SXTB16_RORn((uint32_t)inA, 8U);
^

[mbed] ERROR: "C:\Python27\python.exe" returned error.
Code: 1
Path: "C:\prj_KWS\Deployment\ML-KWS-for-MCU\Deployment\kws_realtime_test"
Command: "C:\Python27\python.exe -u C:\prj_KWS\Deployment\ML-KWS-for-MCU\Deployment\kws_realtime_test\tools\make.py -t GCC_ARM -m DISCO_F746NG --profile ../release_O3.json --source . --source ../Source --source ../Examples/realtime_test --source ../CMSIS_5/CMSIS/NN/Include --source ../CMSIS_5/CMSIS/NN/Source --source ../CMSIS_5/CMSIS/DSP/Include --source ../CMSIS_5/CMSIS/DSP/PrivateInclude --source ../CMSIS_5/CMSIS/DSP/Source --source ../CMSIS_5/CMSIS/Core/Include --build .\BUILD\DISCO_F746NG\GCC_ARM-RELEASE_O3 -j 8"
Tip: You could retry the last command with "-v" flag for verbose output

**Comment by sushreebarsa** [comment]
@EmbeddedSysDesign The issue has been closed and it is difficult for us to follow up in a closed thread.
There is no standalone code provided in your comment above to replicate the issue reported.
Could you open a new ticket with all relevant details in which we can assist you?
Thank you!
