### ISSUE TITLE
Training Keras models with moving averages on Estimator

### ISSUE THREAD

**Issue by herberteuler** [tensorflow/tensorflow#37737]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): 
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 
- Python version: - Bazel
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I am using code snippets like this to define a Keras model with moving averages of its weights:

``` Python
model = ...
ema = tf.train.ExponentialMovingAverage(0.995)
model.add_update(ema.apply())
```

However, the update op is lost after the model is converted into an estimator:

``` Python
model.compile(...)
estimator = tf.keras.estimator.model_to_estimator(model)  # The above update op is lost here
```

Investigation shows that it is lost during the cloning of the model.

**Describe the expected behavior**

The update op should be kept as is, and an estimator should be able to train such a model.

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@herberteuler 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.

Please, share colab link or simple standalone code with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by herberteuler** [comment]
The TensorFlow I am using is version 1.14, but the behavior should be the same in newer versions. [Here](https://gist.github.com/herberteuler/7b2c9de3e35e635811e0caacd812f893) is a toy "model" to demonstrate the issue.

**Comment by ravikyram** [comment]
I have tried on colab with TF version 1.14, 1.15 and i am seeing 
`KeyError: "The name 'weight/kernel/ExponentialMovingAverage:0' refers to a Tensor which does not exist. The operation, 'weight/kernel/ExponentialMovingAverage', does not exist in the graph."`.Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/978ced381ec195b2a083c804e2023d14/untitled746.ipynb). Is this the expected behavior? Thanks!

**Comment by herberteuler** [comment]
No, the last exception is not expected.

I have added three notes in the output, shown in cyan, green, and red, respectively.

The first part trains a "raw" model, where the update ops are executed as the training processes, and as can be seen from there, the moving averages are updated.

The second part shows that by adding updates to a Keras model, the same set of update ops can be added to the graph.

If everything had gone well, the training of the Keras model should be the same as that of the raw model. But as the third part shows, it is not. This is because, during [the cloning of the model](https://github.com/tensorflow/tensorflow/blob/bd24a8316d62bb59b11d188110f01bfb8c9f3f55/tensorflow/python/keras/models.py#L385), only layers are recreated, the updates are not. So the update ops are not part of the execution plan, hence the absence of the moving average variables in the graph.

**Comment by gowthamkpr** [comment]
@herberteuler Are you running into the same error with Tensorflow 1.15 and Tensorflow 2.x? Thanks!

**Comment by herberteuler** [comment]
The code in question is not changed for these versions, so I only checked with TensorFlow 2.1.

Well in TF2.1, the `tf.layers` APIs are gone, so the expected behavior cannot be demonstrated anymore. But with a little change to the code, the same behavior can be observed from TF2.1.

The changed code can be found [here](https://gist.github.com/herberteuler/8c4350db197bd02892aaec9e5bbf3338).

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
