### ISSUE TITLE
Single-precision `tf.math.erf` with TF2 produces (slightly) different results to TF1 and scipy

### ISSUE THREAD

**Issue by charmasaur** [tensorflow/tensorflow#37731]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): macOS 10.15.2d and Colab
- TensorFlow installed from (source or
binary): binary
- TensorFlow version (use command below): v2.1.0-0-ge5bf8de410 2.1.0
- Python version: 3.7.3

**Describe the current behavior**
`tf.math.erf` with `float32` can produce slightly different results between TF1 and TF2 (scipy is consistent with TF1).

**Describe the expected behavior**
I wouldn't expect any difference between the two (although I confess I'm not sure this is actually a bug, maybe it's an expected side-effect of some other change).

**Standalone code to reproduce the issue** 
With TF2 (https://colab.research.google.com/drive/1K3QB6bmu1GmAVepPMpTNgLkIKXKKB7eX):
```
import tensorflow as tf
import scipy
import numpy as np
print(tf.math.erf(-1.0606601).numpy())
print(scipy.special.erf(np.array(-1.0606601, dtype=np.float32)))
```
produces
```
-0.86638564
-0.8663856
```

With TF1 (https://colab.research.google.com/drive/1dQZOXSX8t4Jy1ZIk9Xzs9gxpbUn8acws):
```
import tensorflow as tf
import scipy
import numpy as np
print(tf.Session().run(tf.math.erf(-1.0606601)))
print(scipy.special.erf(np.array(-1.0606601, dtype=np.float32)))
```
produces
```
-0.8663856
-0.8663856
```

With double precision the result is consistently
```
-0.8663855711671024
```

**Comment by amahendrakar** [comment]
Works without any issues with [TF 1.15](https://colab.research.google.com/gist/amahendrakar/1668c50f153d153f463d82a7789de5b9/37731-1-15.ipynb). Was able to reproduce the issue with [TF 2.1](https://colab.research.google.com/gist/amahendrakar/03f5d435f3447b70b139111d371e9d50/37731-2-1.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/b574d2f99ce8a58e26f05faa7849c597/37731-tf-nightly.ipynb). Thanks!

**Comment by ccrusius** [comment]
The results I get on my desktop are different, reproducible with TensorFlow 2.x (TF=TensorFlow result, SP=scipy result):

```
# <dtype: 'float16'>
# TF erf(-1.0606601) = -0.8662109375
# SP erf(-1.0606601) = -0.8663440942764282
#
# <dtype: 'float32'>
# TF erf(-1.0606601) = -0.8663856387138367
# SP erf(-1.0606601) = -0.8663855791091919
#
# <dtype: 'float64'>
# TF erf(-1.0606601) = -0.8663855711671024
# SP erf(-1.0606601) = -0.8663855711671024
```

**Comment by rmlarsen** [comment]
@charmasaur please do not rely on binary equality for floating point data. The math functions in the standard library typically only gives guarantees to be with a few ulps (units in the last place). Within that bound, libraries should be free to make different implementation choices to  make the best accuracy/speed trade-off for the underlying hardware.

**Comment by charmasaur** [comment]
Makes sense, thanks!
