### ISSUE TITLE
SavedModelEstimator not found in TF 2

### ISSUE THREAD

**Issue by junshi15** [tensorflow/tensorflow#37735]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): mac-os
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: n/a
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 2.1.0
- Python version: 3.7 - Bazel
version (if compiling from source): n/a
- GCC/Compiler version (if compiling from
source): n/a
- CUDA/cuDNN version: - GPU model and memory: n/a

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
tf.estimator.experimental.SavedModelEstimator not found
**Describe the expected behavior**
according to https://github.com/tensorflow/estimator/blob/r2.1/tensorflow_estimator/python/estimator/canned/saved_model_estimator.py#L112 it should be found at "tf.estimator.experimental.SavedModelEstimator"
**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

>>> import tensorflow as tf
>>> tf.estimator.experimental.SavedModelEstimator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow_estimator.python.estimator.api._v2.estimator.experimental' has no attribute 'SavedModelEstimator'

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
Was able to reproduce the issue with Tf 2.1.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/c0ae75aa3359ec40f6ea2c1df8a925db/untitled473.ipynb). Thanks

**Comment by junshi15** [comment]
Update: was able to get SavedModelEstimator from below: 
```
from tensorflow_estimator.python.estimator.canned import saved_model_estimator
saved_model_estimator.SavedModelEstimator
```
why not `tf.estimator.experimental.SavedModelEstimator`?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Comment by junshi15** [comment]
We are on TF2 now. No need to resolve it.
