### ISSUE TITLE
Predictions are not accurate after loading the saved model - Resume classification

### ISSUE THREAD

**Issue by ravikairam** [tensorflow/tensorflow#37743]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): 
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: NA
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 2.1.0
- Python version: - Bazel
version (if compiling from source):3.7
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
We have created a sample resume classification model and saved the model with morethan 95% accuracy on train and test data set.After we have loaded the model and trying to make the predictions by defining prediction_classes using tf.argmax and we have observed some ambuiguity in predictions(Not predicting the correct label)

**Describe the expected behavior**

The predictions should be accurate after loading the model

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

[Resume_classification_V_1_5.zip](https://github.com/tensorflow/tensorflow/files/4358924/Resume_classification_V_1_5.zip)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikairam** [comment]
You can find the data from the below link(New_Data.zip)

https://drive.google.com/corp/drive/folders/1IJjiaHUBt_Gq6XXV8NPazd0cWZ2LzkW_

**Comment by gadagashwini** [comment]
@ravikairam, Drive link is leading to 404 error. Please provide the proper link. Thanks!

**Comment by ravikyram** [comment]
@gadagashwini 

Can you please copy and paste the link in new  web browser and see if you are facing any issue. Thanks!

**Comment by gowthamkpr** [comment]
@ravikairam Are you still facing the issue?

**Comment by ravikairam** [comment]
@gowthamkpr 

Yes the issue still persists. Predictions are accurate on train and validation data before saving the model.After saving the model we loaded the model and tested on new unseen data where predictions are going wrong. I tried with saving different file formats(.h5,.pb formats) but still problem exists, Can you please help us to fix this issue . Thanks!

**Comment by gowthamkpr** [comment]
@ravikairam I am closing this issue as it has been resolved.
