### ISSUE TITLE
Build TensorFlow library iOS from source

### ISSUE THREAD

**Issue by SestoAle** [tensorflow/tensorflow#37746]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.15.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iOS
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: Conda
- Bazel version (if compiling from source): 0.26.1

**Describe the problem**
I need to build Tensorflow 2.0.0 from source for iOS devices, to get a library libtensorflow-core.a, I found this link https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/ios where I found another link that seems to have the answer, but it redirect me to a missing page.

Has anyone an idea or a simple guide on how I can build 2.0.0 library for iOS?

Thanks!

**Comment by Saduf2019** [comment]
@SestoAle 
please refer to [this link](https://www.tensorflow.org/lite/guide/build_ios) and let us know if it helps.

**Comment by Saduf2019** [comment]
@SestoAle
please update on above comment

**Comment by Saduf2019** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
