### ISSUE TITLE
load_model error when model has multiple inputs

### ISSUE THREAD

**Issue by kernelizd** [tensorflow/tensorflow#37741]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

This is the last bit of the error

> ValueError: Layer lstm expects 1 inputs, but it received 3 input tensors. Inputs received: [<tf.Tensor 'input_1_2:0' shape=(None, 368, 32) dtype=float32>, <tf.Tensor 'input_2_2:0' shape=(None, 72) dtype=float32>, <tf.Tensor 'input_3_2:0' shape=(None, 72) dtype=float32>]

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  no
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): W10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if 
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 
- Python version: - Bazel 3.7 for Python and latest 2.1 for TF-gpu
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory: 10.1 -- 7.6 -- TitanRTX

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Created a SIMPLE model with multiple inputs as shown below, saved it with model.save method but failed to load it.

**Describe the expected behavior**

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
def create_model():
    ip1 = tf.keras.layers.Input(shape=(seq_len, ip_size))
    ip2 = tf.keras.layers.Input(shape=(hidden_size,))
    ip3 = tf.keras.layers.Input(shape=(hidden_size,))
    y0 = tf.keras.layers.LSTM(units=hidden_size)(inputs=ip1, initial_state=[ip2, ip3])
    y1 = tf.keras.layers.Dense(units=num_points, activation=tf.keras.activations.tanh)(y0)
    y = tf.keras.layers.Dense(units=num_points)(y1)
    model = tf.keras.models.Model(inputs=[ip1, ip2, ip3], outputs=y, name='cheater_model')
    return model
```
model = create_model()
model.save(path)
model = tf.keras.models.load(path)

PS: fill up the variables with any numbers, it doesn't matter
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by khimraj** [comment]
@kernelizd, please share full code or colab link to reproduce the issue.

**Comment by kernelizd** [comment]
@khimraj Hi, after hard work, I reproduced the simplist **shortest** example of the problem on colab as you requested. Please have a look here:

https://colab.research.google.com/gist/kernelizd/c79941c4f919fbb441e8bf9998dc42f5/untitled6.ipynb

**Comment by ravikyram** [comment]
@kernelizd 

Can you please try with latest TF version(`!pip install tensorflow==2.2.0rc1`) . I am not seeing any issue with 2.2.0rc1 version. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/7272689f2e7769ff5da86ec3967de9d8/untitled744.ipynb). Thanks!

**Comment by kernelizd** [comment]
@ravikyram Hi. I installed 2.2 releae candidate, its working smoothly now.
Thank you.
