### ISSUE TITLE
TF 2.2.0 Windows Bazel 2.0.0 '@local_config_cuda//cuda'  (Python Path)

### ISSUE THREAD

**Issue by khaled-besrour** [tensorflow/tensorflow#37748]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Winndows 10
- TensorFlow installed from (source or binary): source 
- TensorFlow version: 2.2.0
- Python version: 3.7
- Bazel version (if compiling from source):  2.0.0
- GCC/Compiler version (if compiling from source):  Visual Studio 2019 14.25.28610
- CUDA/cuDNN version:  CUDA 10.2 cuDNN 7.5
- GPU model and memory: RTX 2060 6Go

the problem is a bazel error when, I start building with bazel
The problem comes from \tensorflow\third_party\gpus\cuda_configure.bzl in the line 608:
`return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])`

the real problem comes from the python_bin Path when it executes that line:
`system("C:/Program Files/Python37/python.exe script.py cuda cudnn")`
the space between Program and Files make an error in execution.

The current solution that i have found is to move the python folder too : 
`C:/Python37/python.exe`

That move resolves that problem for now.
I can't help more.
thanks

**Comment by amahendrakar** [comment]
@khaled-besrour,
Could you please provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by khaled-besrour** [comment]
python ./configure.py

CUDA enable
compute capability 7.35

 bazel build --config=opt --config=cuda --config=v2 --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package

**Comment by amahendrakar** [comment]
@khaled-besrour,
I see that you have mentioned the cuDNN version as 7.5. As per the official TensorFlow [software requirements](https://www.tensorflow.org/install/gpu#software_requirements) you need cuDNN SDK (>= 7.6). 

Could you please try upgrading the cuDNN version to 7.6 or above and let us know if it works? Thanks!

**Comment by khaled-besrour** [comment]
it's just a mistake i have a cuDNN 7.6 and a compute compatibility of 7.5.

but as said i resolve the problem by moving python it's not a DLL error, but python a script problem when the python path have space.

`system("C:/Program Files/Python37/python.exe script.py cuda cudnn")`

it said that `C:/Program` is not executable, i think it come from bazel

**Comment by gunan** [comment]
@khaled-besrour thank you for the analysis.
@meteorcloudy do you know how we can make sure paths with spaces are correctly handled here?
https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/cuda_configure.bzl#L609

**Comment by meteorcloudy** [comment]
As @khaled-besrour pointed out, the problem comes from:
https://github.com/tensorflow/tensorflow/blob/242129341e19afab300558df319a9e5e523b8092/third_party/gpus/cuda_configure.bzl#L606

We should quote the python_bin str in the command passed to `system` function.
`system('"%s" script.py %s');`

**Comment by Sahel-Eskandar** [comment]
Can you help me with this issue? I am new in this territory and need more explanation.
I run:
bazel build //tensorflow/tools/pip_package:build_pip_package
and I get these errors:

INFO: Call stack for the definition of repository 'local_config_cuda' which is a cuda_configure (rule definition at C:/users/asus/tensorflow/third_party/gpus/cuda_configure.bzl:1243:18):
 - <builtin>
 - C:/users/asus/tensorflow/tensorflow/workspace.bzl:90:5
 - C:/users/asus/tensorflow/WORKSPACE:19:1
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "C:/users/asus/tensorflow/third_party/gpus/cuda_configure.bzl", line 1213
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/users/asus/tensorflow/third_party/gpus/cuda_configure.bzl", line 1016, in _create_local_cuda_repository
                find_cc(repository_ctx)
        File "C:/users/asus/tensorflow/third_party/gpus/cuda_configure.bzl", line 217, in find_cc
                _get_msvc_compiler(<1 more arguments>)
        File "C:/users/asus/tensorflow/third_party/gpus/cuda_configure.bzl", line 135, in _get_msvc_compiler
                find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace
'NoneType' value has no field or method 'replace'
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/users/asus/tensorflow/third_party/gpus/cuda_configure.bzl", line 1213
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/users/asus/tensorflow/third_party/gpus/cuda_configure.bzl", line 1016, in _create_local_cuda_repository
                find_cc(repository_ctx)
        File "C:/users/asus/tensorflow/third_party/gpus/cuda_configure.bzl", line 217, in find_cc
                _get_msvc_compiler(<1 more arguments>)
        File "C:/users/asus/tensorflow/third_party/gpus/cuda_configure.bzl", line 135, in _get_msvc_compiler
                find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace
'NoneType' value has no field or method 'replace'
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "C:/users/asus/tensorflow/third_party/gpus/cuda_configure.bzl", line 1213
                _create_local_cuda_repository(<1 more arguments>)
        File "C:/users/asus/tensorflow/third_party/gpus/cuda_configure.bzl", line 1016, in _create_local_cuda_repository
                find_cc(repository_ctx)
        File "C:/users/asus/tensorflow/third_party/gpus/cuda_configure.bzl", line 217, in find_cc
                _get_msvc_compiler(<1 more arguments>)
        File "C:/users/asus/tensorflow/third_party/gpus/cuda_configure.bzl", line 135, in _get_msvc_compiler
                find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace
'NoneType' value has no field or method 'replace'
INFO: Elapsed time: 2.967s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package

C:\Users\asus\tensorflow>

**Comment by khaled-besrour** [comment]
Please open I new issue.

Anyway, I think that the problem come from the global environment, have you add the MVSC_tool to your path?

and if so check if you have the cl.exe file inside it

**Comment by ktybery** [comment]
I solved the issue through setting the BAZEL_SH environment variable, restarting the pc and running the cmd with Administrator rights.
