### ISSUE TITLE
run label_image at linux-armv7l wrong

### ISSUE THREAD

**Issue by Yooong-W** [tensorflow/tensorflow#37750]
i follow the [guide](https://www.tensorflow.org/lite/guide/build_rpi) to build `minimal` and `label_image` for linux-armv7l, but when i run `label_image`, i got this error:
`Illegal instruction (core dumped) `
i build it at ubuntu18.04 with arm-linux-gnueabihf-gcc-4.8, and the ARM is cortexe-A9 with linux12.04.
what should i do?

**Comment by freedomtan** [comment]
Could be either software (e.g., your environment doesn't not use HF) or hardware (e.g., Cortex-A9 has some hardware options, see ARM's [doc](https://developer.arm.com/docs/ddi0388/g/introduction/configurable-options)).

**Comment by Yooong-W** [comment]
> 可以是软件（例如，您的环境不使用HF）或硬件（例如，Cortex-A9有一些硬件选项，请参阅ARM的[文档](https://developer.arm.com/docs/ddi0388/g/introduction/configurable-options)）。

Hi, @freedomtan 
i run the `label_image` at cortex-A7 with linux version 4.1.15,and the gcc version is 4.9.3,it works well. but when i run it at coetex-A9 with linux version 3.0.15,and the gcc version is 4,4,1, it  give me the error back. so, maybe its because of the linux kernel's version or gcc's version ?

**Comment by freedomtan** [comment]
Well, mostly TFLite works in user space. It should has little to do with Linux kernel. Surely, your compiler (e.g., gcc version) could be a problem. But I think you should figure what kind of Cortex-A9 you have first.

**Comment by ravikyram** [comment]
@Yooong-W 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
