### ISSUE TITLE
TFLite - Experimental New Converter, incorrect model for Bidirectional GRU

### ISSUE THREAD

**Issue by TimCapes** [tensorflow/tensorflow#37757]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): 
Yes Provided Below.
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): 
Mac OS 10.12.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: Samsung Note9
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 
2.1.0
- Python version: - Bazel
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
TFLite produces a graph with 1 output of size 1(*4 bytes)
**Describe the expected behavior**
TFLite produces a graph with 1 output of size 64(*4 bytes)
**Standalone code to reproduce the issue** 
import tensorflow as tf
word = tf.keras.Input(shape=(1,), name='word', dtype=tf.int32)
embedding_output = tf.keras.layers.Embedding(8000,100,input_length=1)(word)
modified_embedding = tf.keras.layers.Bidirectional(tf.keras.layers.GRU(32))(embedding_output)
model = tf.keras.Model(inputs=[word], outputs=[modified_embedding])
model._make_predict_function()
model.summary()
model.save("testmodel")
converter = tf.lite.TFLiteConverter.from_saved_model("testmodel")
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,tf.lite.OpsSet.SELECT_TF_OPS]
converter.experimental_new_converter = True
tflite_model = converter.convert()
open("testmodel.tflite", "wb").write(tflite_model)

Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by jdduke** [comment]
Have you actually tried executing the graph in the TFLite interpreter? Shape inference during conversion isn't guaranteed to propagate to output nodes, especially when using SELECT_TF_OPS. It should be resolved at runtime when you run inference.

**Comment by TimCapes** [comment]
Good to know. It works on device with the correct size, closing.
