### ISSUE TITLE
There is a bug that strings are not displayed in iOS darkmode.

### ISSUE THREAD

**Issue by Nishikoh** [tensorflow/tensorflow#37763]
**System information** 

- Mobile device : iPhone 8 , iOS 13

**Describe the current behavior**
url : [image_classification/ios](https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/ios)
There is a bug that strings are not displayed in iOS darkmode.
<img src="https://user-images.githubusercontent.com/55723667/77207772-9da16a80-6b3d-11ea-8e27-b9e0593600e4.PNG" width="300"> 

There is not a bug in light mode.
<img src="https://user-images.githubusercontent.com/55723667/77211304-ead60a00-6b46-11ea-8a1b-0d049318db84.PNG" width="300"> 

**Other info / logs** 
The reason for this is that the background and text are the same color.

**Comment by Nishikoh** [comment]
I'm working on this bug.
https://github.com/tensorflow/examples/pull/177

**Comment by yyoon** [comment]
This is fixed by merging the PR. Thanks for the fix!
