### ISSUE TITLE
min_epsilon of fused_batch_norm is incorrect

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#37768]
**System information** 
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): n/a
- OS Platform and Distribution (e.g.,Linux Ubuntu 16.04): n/a
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source orbinary): n/a
- TensorFlow version (use command below):  n/a
- Python version: n/a
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

The source code in current master branch has this:
https://github.com/tensorflow/tensorflow/blob/0c853d6cadf055be10562cfec92a93776fafd555/tensorflow/python/ops/nn_impl.py#L1516-L1519

However, the statement in the comment is no longer correct, according to https://docs.nvidia.com/deeplearning/sdk/cudnn-release-notes/rel_750.html:
> the value of epsilon is required to be greater or equal to CUDNN_BN_MIN_EPSILON which was defined in the cudnn.h file to the value 1e-5. This threshold value is now lowered to 0.0 to allow a wider range of epsilon value.

If compatibility with earlier version of cudnn is needed, the minimum should be obtained by using the `CUDNN_BN_MIN_EPSILON` constant defined by `cudnn.h`. 
Or, maybe it's better to just throw an error when a wrong epsilon is provided by the user.  Personally I don't like my parameter to be silently changed -- this can cause issues like `nn.fused_batch_norm` and `nn.batch_normalization` producing different results.

**Comment by Saduf2019** [comment]
@ppwwyyxx 
could you please share simple stand alone code along with tensor flow version for us to replicate the issue faced

**Comment by ppwwyyxx** [comment]
The issue is clearly written in TensorFlow source code which I pasted above.

**Comment by mohantym** [comment]
Hi @ppwwyyxx! Could you cross check the pull request #53065 ?

**Comment by mohantym** [comment]
Ok @ppwwyyxx! This issue will be closed one Above PR is merged. Thanks!

**Comment by mohantym** [comment]
Hi @ppwwyyxx ! Internal tests are failing for above changes. Could you let us know the epsilon value in Cuda 8.1 for 2.8 version? Thanks!
