### ISSUE TITLE
Missing arguments when the inputs of concrete function contain list

### ISSUE THREAD

**Issue by BlueFisher** [tensorflow/tensorflow#37778]
**System information** 
- TensorFlow version: v2.1.0

**Describe the current behavior**
```python
@tf.function
def test(a, b, c):
    pass


c_test = test.get_concrete_function(a=[tf.TensorSpec((None, 1)),
                                       tf.TensorSpec((None, 1))],
                                    b=tf.TensorSpec((None, 2)),
                                    c=[tf.TensorSpec((None, 3)),
                                       tf.TensorSpec((None, 3))])

c_test(a=[tf.random.normal([2, 1]), tf.random.normal([2, 1])],
       b=tf.random.normal([2, 2]),
       c=[tf.random.normal([2, 3]), tf.random.normal([2, 3])])
```
The function `test` has `a` and `c`  two arguments that should be as the type list. I create a concrete function `c_test` from `test`. But when `c_test` is called like the code above, it will throw
```
Expected argument names ['a', 'a_1', 'b', 'c', 'c_1'] but got values for ['a', 'b', 'c']. Missing: ['c_1', 'a_1'].
```
It seems that the function only received the first element of the list arguments.

**Comment by khimraj** [comment]
@BlueFisher, I think you need to pass argument like this.
`c_test(a=tf.random.normal([2, 1]), 
       a_1 = tf.random.normal([2, 1]),
       b=tf.random.normal([2, 2]),
       c=tf.random.normal([2, 3]),
       c_1 = tf.random.normal([2, 3]))`.
I have checked this and there is no error.

**Comment by BlueFisher** [comment]
@khimraj , that works! Thank you so much. But it would be better if I could pass arguments like the way in my question.
