### ISSUE TITLE
It seems that Tensorflow needs a check for the unreasonable parameter `input_dim=0` in the layer `Embedding`.

### ISSUE THREAD

**Issue by shiningrain** [tensorflow/tensorflow#37777]
## System information

- Have I written custom code (as opposed to using example directory):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 & Linux Ubuntu 18.04
- Tensorflow version：2.1.0-cpu (using 'pip install TensorFlow' to download directly)
- Python version: 3.6.9
- CUDA/cuDNN version: -
- GPU model and memory: -

## Describe the current behavior
When I build the model with an illogical parameter `input_dim = 0`in the layer `Embedding`, **Tensorflow uses this unreasonably parameter to build and even save the model**. The detailed performance in building the model is shown in the following picture。

![image](https://user-images.githubusercontent.com/46860123/77224293-27355480-6b9f-11ea-9d96-df3e852ca4b3.png)

## Key insights
To sum up, `input_dim` or `output_dim = 0` are unreasonable corner cases. ** Tensorflow seems to lack in checking this corner case**. This may lead Tensorflow users to create and even save a wrong model, which will bring potential risks in the subsequent usage.

## Code to reproduce the issue

``` python
import numpy as np
import tensorflow.keras.layers as L 
from tensorflow.keras import Model, Input
import tensorflow
import os

print(tensorflow.__version__) 

kwargs = {
    'input_dim': 0, # you can also set input_dim to 0 to test
	'output_dim': 18,
	'mask_zero': True
}
input = (10 * np.random.random((32,10)))
layer = L.Embedding(**kwargs)
x = Input(batch_shape=input.shape)
y = layer(x)
bk_model = Model(x, y)
model_path = os.path.join('./', 'mode.h5')
bk_model.save(model_path, bk_model)
print('finish')
```

**Comment by maxkaustav** [comment]
The code you have written is not correct you are not passing any input to the model.TensorFlow creates a static graph and the checks for the correct dimension during execution
Write you code then at the end write`bk_model(input)` .You will see some error this is because the dimension of your tensor is (32,10) now change `'input_dim': 0` to `'input_dim': 10` and run again,it will work.

**Comment by Saduf2019** [comment]
@shiningrain 
Could you please update on the above comment

**Comment by shiningrain** [comment]
Hello, thank you for your reply!
I have tested the code with the change you said. And when I set the `inputdim=10` ,it did make a normal prediction.  But as I described above, **if I set `inputdim` to 0, I  can still build and save the model, although this model cannot be used for prediction.**
I saw on the TensorFlow document [here](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Embedding). On this page, it mentions that the inputdim should be greater than zero, but it seems that we can still build the model with `inputdim = 0`. 
I want to emphasize that **there seems to be a lack of simple parameter check**, thus the corner case like` inputdim = 0` can be used to build a model by TensorFlow and save a corresponding model----even if this model is just a static graph. This may confuse users.

Additionally, adding a check for the illogical parameter is not a difficult job. As shown [here](https://github.com/tensorflow/tensorflow/commit/1e102f63964365d82d7f22402b7ba21e0e0e64fe), Tensorflow has previously fixed a similar problem that people can build a model when using `conv2d (kernel_size = 0). `

**Comment by shiningrain** [comment]
> The code you have written is not correct you are not passing any input to the model.TensorFlow creates a static graph and the checks for the correct dimension during execution
> Write you code then at the end write`bk_model(input)` .You will see some error this is because the dimension of your tensor is (32,10) now change `'input_dim': 0` to `'input_dim': 10` and run again,it will work.

Hello! Thank you for your reply!
I have tested the code with the change you said. And when I set the `inputdim=10` ,it did make a normal prediction.  But as I described above, **if I set `inputdim` to 0, I  can still build and save the model, although this model cannot be used for prediction.**
I saw on the TensorFlow document [here](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Embedding). On this page, it mentions that the inputdim should be greater than zero, but it seems that we can still build the model with `inputdim = 0`. 
I want to emphasize that **there seems to be a lack of simple parameter check**, thus the corner case like` inputdim = 0` can be used to build a model by TensorFlow and save a corresponding model----even if this model is just a static graph. This may confuse users.

Additionally, adding a check for the illogical parameter is not a difficult job. As shown [here](https://github.com/tensorflow/tensorflow/commit/1e102f63964365d82d7f22402b7ba21e0e0e64fe), Tensorflow has previously fixed a similar problem that people can build a model when using `conv2d (kernel_size = 0). `

**Comment by tanzhenyu** [comment]
Closing this since it has been fixed [here](https://github.com/tensorflow/tensorflow/commit/1e102f63964365d82d7f22402b7ba21e0e0e64fe).

**Comment by shiningrain** [comment]
> Closing this since it has been fixed [here](https://github.com/tensorflow/tensorflow/commit/1e102f63964365d82d7f22402b7ba21e0e0e64fe).

Thank you for your reply! 
I wonder if you are using a wrong [link](https://github.com/tensorflow/tensorflow/commit/1e102f63964365d82d7f22402b7ba21e0e0e64fe)in your reply, because this link is the same as the one in my comments and it is related to the conv layer, not the Embedding.

**Comment by tanzhenyu** [comment]
> > Closing this since it has been fixed [here](https://github.com/tensorflow/tensorflow/commit/1e102f63964365d82d7f22402b7ba21e0e0e64fe).
> 
> Thank you for your reply!
> I wonder if you are using a wrong [link](https://github.com/tensorflow/tensorflow/commit/1e102f63964365d82d7f22402b7ba21e0e0e64fe)in your reply, because this link is the same as the one in my comments and it is related to the conv layer, not the Embedding.

Oh sorry, I meant to close another issue
