### ISSUE TITLE
Potential bug in Tensorflow 1 integration with Jupyter notebook

### ISSUE THREAD

**Issue by mdautrey** [tensorflow/tensorflow#37776]
When running the attached jupyter notebook example from [Manning book "Tensorflow in action"](https://www.manning.com/books/machine-learning-with-tensorflow) - I know there are some typos in the code but I correct them to make the code works - , I meet the following condition

- When I run all steps for the first time, everything works fine 

- When I run the tf placeholder declaration twice

Code[
alpha = tf.constant(0.05)
curr_value = tf.placeholder(tf.float32)
prev_avg = tf.Variable(0.)

update_avg = alpha * curr_value + (1 - alpha) * prev_avg
]

the session crashes with an error :

Code[
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    writer.add_graph(sess.graph)
    for i in range(len(raw_data)):
        summary_str, curr_avg = sess.run([merged, update_avg], feed_dict={curr_value: raw_data[i]})
        sess.run(tf.assign(prev_avg, curr_avg))
        print(raw_data[i], curr_avg)
        writer.add_summary(summary_str, i)
]

Error message[
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-13-81676f6fb632> in <module>()
      5     writer.add_graph(sess.graph)
      6     for i in range(len(raw_data)):
----> 7         summary_str, curr_avg = sess.run([merged, update_avg], feed_dict={curr_value: raw_data[i]})
      8         sess.run(tf.assign(prev_avg, curr_avg))
      9         print(raw_data[i], curr_avg)

/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    958     try:
    959       result = self._run(None, fetches, feed_dict, options_ptr,
--> 960                          run_metadata_ptr)
    961       if run_metadata:
    962         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1181     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1182       results = self._do_run(handle, final_targets, final_fetches,
-> 1183                              feed_dict_tensor, options, run_metadata)
   1184     else:
   1185       results = []
...]

**Workaround** : I have to restart kernel and clear all outputs to run the session again. 

**Possible cause** : either tensorflow or jupyter doesn't detect that placeholders have already been instantiated and instantiates them twice.

**Environment** : docker TF container tensorflow/tensorflow:latest-gpu-jupyter

[ch2Tensorboard.ipynb.txt](https://github.com/tensorflow/tensorflow/files/4362615/ch2Tensorboard.ipynb.txt)

**Comment by khimraj** [comment]
@mdautrey, can you please share the full code or link of colab file to reproduce mentioned issue.

**Comment by mdautrey** [comment]
I think that the full code is attached to my initial post https://github.com/tensorflow/tensorflow/files/4362615/ch2Tensorboard.ipynb.txt

**Comment by khimraj** [comment]
@mdautrey, I have checked this file by running on google colab and i found no issue. for your reference link of gist is [here](https://colab.research.google.com/gist/khimraj/cad75364418c3ea67c2193cca0544e06/ch2tensorboard.ipynb).

**Comment by mdautrey** [comment]
When you run the code twice, you get the attached error, even on google colab
![Capture du 2020-03-23 06-26-54](https://user-images.githubusercontent.com/6020351/77284667-81cdce00-6ccf-11ea-939d-49f5c2faa31a.png)

**Comment by ravikyram** [comment]
when we run the code twice in colab i am able to reproduce the issue. Thanks!

**Comment by ymodak** [comment]
Try adding `tf.reset_default_graph()` before creating graph. That should help. Thanks!
```python
tf.reset_default_graph()
alpha = tf.constant(0.05)
...
```

**Comment by mdautrey** [comment]
It works! Thank you
Should the documentation be updated accordingly ? (https://www.tensorflow.org/api_docs/python/tf/compat/v1/summary/FileWriter )
