### ISSUE TITLE
Broken link in community/forums.md

### ISSUE THREAD

**Issue by abhinavsp0730** [tensorflow/tensorflow#37782]
## URL(s) with the issue:
https://github.com/tensorflow/docs/blob/master/site/en/community/forums.md

## Description of the issue (what needs changing):
In forums.ms  [how to get help](https://github.com/tensorflow/docs/blob/master/community/#get_help) is broken and while clicking it's showing 404 error.

### submit a pull request
Hey, @MarkDaoust and @lamberta would you please assign me this issue and please provide details to fix this issue I'll love to fix this issue.

**Comment by mihaimaruseac** [comment]
I think you have to open a PR against https://github.com/tensorflow/docs

**Comment by abhinavsp0730** [comment]
Hey, @mihaimaruseac  thank you for your quick reply. I've searched through github repo to find the correct *how to get help* link but I'm unable to find it. So, my question is does *how to get help* exist or not, If not then we must have to change it for more help mail it to ```tensorflow.org``` or we will link Tensorflow google group link.

**Comment by mihaimaruseac** [comment]
Maybe this should be the link https://www.tensorflow.org/community ?

Letting @MarkDaoust / @lamberta add more details

**Comment by abhinavsp0730** [comment]
Hey, @MarkDaoust  / @lamberta kindly check the link provided by @mihaimaruseac  is the correct link for "how to get help" or not.

**Comment by abhinavsp0730** [comment]
Hey, @mihaimaruseac this one is offtopic, I've been participating this year GSOC. And I've completed
my 1st proposal, It'll be very helpful for me if you look at it once and give your feedbacks. So, that it'll come in a more good shape.
Thankyou

**Comment by MarkDaoust** [comment]
Hmmm ... It looks like the only relevant part is the github and SO links, which are already on the forums page.

I's just delete that sentence.

**Comment by abhinavsp0730** [comment]
Hey,  [#1520](https://github.com/tensorflow/docs/pull/1520) kindly see this PR.
