### ISSUE TITLE
Missing interpreter initialization code in the codelab

### ISSUE THREAD

**Issue by Egorand** [tensorflow/tensorflow#37780]
The codelab in question is [Build a handwritten digit classifier app with TensorFlow Lite
](https://codelabs.developers.google.com/codelabs/digit-classifier-tflite/index.html?index=..%2F..index#3).

Step 4.6 introduces the following snippet of code:

```kotlin
// Read input shape from model file
val inputShape = interpreter.getInputTensor(0).shape()
inputImageWidth = inputShape[1]
inputImageHeight = inputShape[2]
modelInputSize = FLOAT_TYPE_SIZE * inputImageWidth * inputImageHeight * PIXEL_SIZE

// Finish interpreter initialization
this.interpreter = interpreter
```

`interpreter` is a class field that has not been initialized in any previous code snippets and the code fails to compile.

Looking at the finalized code in the `finish` directory of the downloadable sample, 4.6 should've probably included this code snippet to initialize `interpreter`:

```kotlin
// Initialize TF Lite Interpreter with NNAPI enabled.
val options = Interpreter.Options()
options.setUseNNAPI(true)
val interpreter = Interpreter(model, options)
```

**Comment by ashutosh1919** [comment]
@Egorand and @jvishnuvardhan , Please close this issue since My PR [#178](https://github.com/tensorflow/examples/pull/178) is merged and the codelab will be updated soon.

**Comment by jvishnuvardhan** [comment]
@Egorand Thanks for the issue and Thanks to @ashutosh1919 for fixing it. Closing this issue as this was resolved. Thanks!
