### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by abhinavsp0730** [tensorflow/tensorflow#37783]
## URL(s) with the issue:
In this repo the ```tf.framework.Executor``` link is broken.
### Pull Request
Successfully merging of [#811](https://github.com/tensorflow/federated/pull/811) will close this issue.
Hey, @MarkDaoust , @lamberta, and @mihaimaruseac would you please review this pull request.

**Comment by jvishnuvardhan** [comment]
@abhinavsp0730 Thanks for the issue and PR to update the docs. Closing this issue as the corresponding https://github.com/tensorflow/federated/pull/811 was merged already. Thanks!

**Comment by MarkDaoust** [comment]
@abhinavsp0730 

One good trick is top put a `fixes: tensorflow/tensorflow#37783` in the PR description, that will auto-close the bug when the PR is merged.
