### ISSUE TITLE
Progress bar with tensorflow.keras.load_model

### ISSUE THREAD

**Issue by Sreerag-ibtl** [tensorflow/tensorflow#37799]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):1.15
- Are you willing to contribute it (Yes/No):Yes

**Describe the feature and the current behavior/state.**
When loading larger multiple models it is taking too much time. It will be better to have a progress bar to know current status of model loading.
**Will this change the current api? How?**
I do not know.
**Who will benefit with this feature?**
Those working with models trained using transfer learning or using very learge models on a CPU.
**Any Other info.**
I checked on progressbar2 and tqdm. But both requires an iterable to work with.

**Comment by ManishAradwad** [comment]
Hello, I would love to work on this issue! Can you plz give me some pointers so I can start working on it...

**Comment by Sreerag-ibtl** [comment]
Most of the current python libraries I checked works on an iterable. I don't know we have such an iterable in this case. If there's one, then a separate thread may be used to monitor this. This is my initial guess. May be wrong.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
