### ISSUE TITLE
GradientTape.jacobian works for batch shape 0 when `experimental_use_pfor=True` but not when `experimental_use_pfor=False`

### ISSUE THREAD

**Issue by hartikainen** [tensorflow/tensorflow#37795]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  No
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04):  `macOS Catalina 10.15.2 (19C57)`
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): `v2.2.0-rc0-43-gacf4951a2f 2.2.0-rc1 0.10.0-dev20200321`
- Python version: 3.7.6
- CUDA/cuDNN version: - GPU model and memory: n/a

**Describe the current behavior**
Using `experimental_use_pfor=False` in `GradientTape.jacobian` behaves otherwise similarly as using `experimental_use_pfor=True`, but when running with tensors of batch shape 0, the former fails due to a type error, whereas the latter one works fine.

**Describe the expected behavior**
I would expect the behavior to be the same in both cases when `experimental_use_pfor=False` and `experimental_use_pfor=True`.

**Standalone code to reproduce the issue**
```python
import tensorflow as tf


def main():
    variable = tf.Variable(1.0)
    inputs = (
        tf.constant(tf.random.uniform((0, 4))),
        tf.constant(tf.random.uniform((0, 3))),
    )

    with tf.GradientTape(persistent=True) as tape:
        outputs = variable * tf.pow(tf.concat(inputs, axis=-1), 2.0)

    jacobians_1 = tape.jacobian(
        outputs,
        variable,
        experimental_use_pfor=True,
    )
    print(jacobians_1)
    print("tape.jacobians(..., experimental_use_pfor=True) works!")

    try:
        jacobians_2 = tape.jacobian(
            outputs,
            variable,
            experimental_use_pfor=False,
        )
        print(jacobians_2)
        print("tape.jacobians(..., experimental_use_pfor=False) works!")
    except TypeError:
        print("tape.jacobians(..., experimental_use_pfor=False) doesn't work!")
        raise


if __name__ == '__main__':
    main()
```

**Other info / logs**
Originally posted here: https://github.com/tensorflow/tensorflow/issues/32460#issuecomment-572545864.

```
tape.jacobians(..., experimental_use_pfor=True) works!
tape.jacobians(..., experimental_use_pfor=False) doesn't work!
Traceback (most recent call last):
  File "./tests/test_tape_jacobian.py", line 36, in <module>
    main()
  File "./tests/test_tape_jacobian.py", line 26, in main
    experimental_use_pfor=False,
  File "/Users/hartikainen/conda/envs/softlearning-tf2/lib/python3.7/site-packages/tensorflow/python/eager/backprop.py", line 1151, in jacobian
    for i, out in enumerate(output):
TypeError: 'NoneType' object is not iterable
```

**Comment by Saduf2019** [comment]
i have replicated this issue on nightly, please [find gist](https://colab.sandbox.google.com/gist/Saduf2019/a1e2219397c3ce701988c32552a3df72/untitled104.ipynb) here

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210524, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/d09e4026b226e4b8007f096810c9fb1b/untitled7.ipynb). Thanks!

**Comment by kkimdev** [comment]
Thanks for reporting this!

**Comment by kumariko** [comment]
Was able to reproduce issue in Tf 2.7, please find the gist [here](https://colab.research.google.com/gist/kumariko/8a42c0c222e29898235da0b9a5ec87a1/untitled7.ipynb#scrollTo=fPzJ0Pz_8T8A). Thanks!

**Comment by tilakrayal** [comment]
@hartikainen,
The respective PR #59435 was merged and also I tried to execute the mentioned code on tf-nightly and it was executed without any issue/error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/b7f117b6d9aa04c3ab8cfe6c5776f4f8/untitled1090.ipynb). Thank you!
