### ISSUE TITLE
how to use tf.train.Checkpoint to restore only part of the model

### ISSUE THREAD

**Issue by james20141606** [tensorflow/tensorflow#37793]
https://github.com/tensorflow/tensorflow/blob/e5bf8de410005de06a7ff5393fafdf832ef1d4ad/tensorflow/python/training/tracking/util.py#L1692-L1989

I found it a little confusing when I use tf 2.x to restore part of the model (like decoder) to perform transfer learning. I found the code styles like this:
`checkpoint = tf.train.Checkpoint(model=autoencoder, optimizer=optimizer)`
if I want to use the pretrained decoder and write a new encoder different from the old_model, I know how to load the pretrained decoder's weights by explicitly using the decoder's name. But now it seems the restoration operation is through tf.train.Checkpoint. I don't know how to load part of the model's weight using tf.train.Checkpoint or change the model's encoder after restore the model. Is it correct to add a new line after `checkpoint = tf.train.Checkpoint(model=old_model, optimizer=optimizer)` like `autoencoder.encoder = new_encoder`?

**Comment by maxkaustav** [comment]
you can get access to each variable in checkpoint using
`inside_checkpoint=tf.train.list_variables(tf.train.latest_checkpoint('./tf_ckpts/'))`
and initialize the values(weights,kernel,etc) as an array to your model.
For more reference visit https://www.tensorflow.org/guide/checkpoint#manual_checkpointing

**Comment by james20141606** [comment]
thanks for the help! I use the `tf.train.list_variables` and I can get a list of variables. But I am not sure how to get all the values which includes 'decoder' in it:
![image](https://user-images.githubusercontent.com/14315324/77261820-cc1b6480-6c67-11ea-8a03-1ae1d762144c.png)
Can I get the weights of decoder here and feed it to my model.decoder?

**Comment by maxkaustav** [comment]
This can be done manually so suppose I have a layer whose weights are basically kernel and bias which could be set using kernel initializer and bias initializer by accessing the values using `tf.train.load_variable(tf.train.latest_checkpoint('./tf_ckpts/'),"net/l1/bias/.ATTRIBUTES/VARIABLE_VALUE")` and `tf.train.load_variable(tf.train.latest_checkpoint('./tf_ckpts/'),"net/l1/kernel/.ATTRIBUTES/VARIABLE_VALUE")` which will return a tensor of values of bais and kernel if you want optimizers you can go for it ex-`tf.train.load_variable(tf.train.latest_checkpoint('./tf_ckpts/'),"optimizer/beta_1/.ATTRIBUTES/VARIABLE_VALUE")`  if you are training the same model architecture only so in you case you can access the kenel and bias values of dense_out,f_stack and so on.

**Comment by maxkaustav** [comment]
if your problem is solved please reply or close this issue

**Comment by james20141606** [comment]
> This can be done manually so suppose I have a layer whose weights are basically kernel and bias which could be set using kernel initializer and bias initializer by accessing the values using `tf.train.load_variable(tf.train.latest_checkpoint('./tf_ckpts/'),"net/l1/bias/.ATTRIBUTES/VARIABLE_VALUE")` and `tf.train.load_variable(tf.train.latest_checkpoint('./tf_ckpts/'),"net/l1/kernel/.ATTRIBUTES/VARIABLE_VALUE")` which will return a tensor of values of bais and kernel if you want optimizers you can go for it ex-`tf.train.load_variable(tf.train.latest_checkpoint('./tf_ckpts/'),"optimizer/beta_1/.ATTRIBUTES/VARIABLE_VALUE")` if you are training the same model architecture only so in you case you can access the kenel and bias values of dense_out,f_stack and so on.

Hey, thanks for your answer! I am not sure if I understand you correctly, so in your answer I should load the submodules in my decoder one by one, is it right? So should I write some code like:
```
tf.train.load_variable(tf.train.latest_checkpoint('./tf_ckpts/'),"model/decoder/dense_out")
tf.train.load_variable(tf.train.latest_checkpoint('./tf_ckpts/'),"model/decoder/f_stack")
```
or maybe this it not enough, I should write something like:
```
tf.train.load_variable(tf.train.latest_checkpoint('./tf_ckpts/'),"model/decoder/dense_out/bias/.ATTRIBUTES/VARIABLE_VALUE")
......
```
If I should write like the second one, it means I should write a lot of codes to make sure I loaded everything in my decoder. I wonder could I write some simple code like `tf.train.load_variable(tf.train.latest_checkpoint('./tf_ckpts/'),"model/decoder/")` to load everything easily?

**Comment by allenlavoie** [comment]
See https://www.tensorflow.org/guide/checkpoint#loading_mechanics (example of only loading a bias variable from a larger checkpoint, but the same pattern works for "only" loading a whole model/layer)

**Comment by yourtheron** [comment]
@allenlavoie I have a further question. Given that there are multiple ckpts stored in a folder, how can I restore a specific model by using ckpt.restore(...). The doc seems unclear about it. Thanks

**Comment by allenlavoie** [comment]
Specify the prefix for the one you want to restore (the number is part of the prefix).

**Comment by yourtheron** [comment]
@allenlavoie Say I would like to restore ckpt-12 shown in the picture above, would you mind of giving me a line of example code? Sorry for any inconvenience caused.

**Comment by allenlavoie** [comment]
```
ckpt = tf.train.Checkpoint(...)
status = ckpt.restore('path/to/that/directory/ckpt-12')
# ... make sure the variables are created
status.assert_consumed()  # lets you know if anything wasn't restored
```

**Comment by yourtheron** [comment]
@allenlavoie Great, thanks a lot!

**Comment by NidhiRustagi** [comment]
@ james20141606  I am working on a very similar thread as you, so i have custom build encoder and decoder layers that are added together in a keras model object. I want to train or fine tune only the encode on a new dataset, so was wondering if you could share the mechanics of loading all encoder specific variables and weights easily in one shot

**Comment by NidhiRustagi** [comment]
@allenlavoie  I am working on a very similar thread as @ james20141606, so i have custom build transformer encoder and decoder layers that are added together in a keras model object. I want to train or fine tune only the encoder on a new dataset, so was wondering if you there is a simple straight forward way to load all encoder variables in a single shot.
I looked at the loading mechanics as described on https://www.tensorflow.org/guide/checkpoint page, but doing it for all the encoder layers with multiple attention heads with that mechanism requires extensive lines of code for each layer likee reconstructing the entire architecture.
Any suggestions or recommendations for a smarter work around

**Comment by thusinh1969** [comment]
> @allenlavoie I am working on a very similar thread as @ james20141606, so i have custom build transformer encoder and decoder layers that are added together in a keras model object. I want to train or fine tune only the encoder on a new dataset, so was wondering if you there is a simple straight forward way to load all encoder variables in a single shot.
> I looked at the loading mechanics as described on https://www.tensorflow.org/guide/checkpoint page, but doing it for all the encoder layers with multiple attention heads with that mechanism requires extensive lines of code for each layer likee reconstructing the entire architecture.
> Any suggestions or recommendations for a smarter work around

Exactly what lots of us needed. For Keras it was as simple as load the weight and "skip_name" to skip the mismatches as we have to replace the top layers for examples for different classification.

Thanks for your solution.
Steve

**Comment by Sdhir** [comment]
> you can get access to each variable in checkpoint using
> `inside_checkpoint=tf.train.list_variables(tf.train.latest_checkpoint('./tf_ckpts/'))`
> and initialize the values(weights,kernel,etc) as an array to your model.
> For more reference visit https://www.tensorflow.org/guide/checkpoint#manual_checkpointing

How can we initialize the values(weights,kernel,etc) as an array to the model? Sharing a code snippet will be helpful.

**Comment by ArtyomZemlyak** [comment]
Found a solution to this problem that worked in my case (load pretrained model weights except for the last Dense layer):

```python
checkpoint_directory = os.path.join(train_dir, "restore/")
checkpoint_prefix = os.path.join(checkpoint_directory, "ckpt")
# Use for save new checkpoints:
checkpoint = tf.train.Checkpoint(optimizer=optimizer, model=model)  # model - new model with +1 class

def get_variables_to_restore(variables, vars_to_exclude):
    variables_to_restore = []
    for v in variables:
        if v.name.split(":")[0] not in vars_to_exclude:
            print("Variables restored: %s" % v.name)
            variables_to_restore.append(v)
    return variables_to_restore

ckpt = tf.train.get_checkpoint_state(checkpoint_directory)
pretrained_model = ckpt.model_checkpoint_path

variables = tf.global_variables()
sess.run(tf.variables_initializer(variables, name="init"))

vars_to_exclude = set(["dense/bias", "dense/kernel"])
variable_to_restore = get_variables_to_restore(variables, vars_to_exclude)

restorer = tf.train.Saver(variable_to_restore)
restorer.restore(sess, pretrained_model)

# some train or finetune

checkpoint.save(file_prefix=checkpoint_prefix, session=sess)
```

Source: 
https://innerpeace-wu.github.io/2017/12/13/Tensorflow-Restore-partial-weights/

**Comment by rsandler00** [comment]
@ArtyomZemlyak works with TF1, but is there a solution for TF2? This seems like a common enough use case...

**Comment by rsandler00** [comment]
Hi, can this issue please be reopened. The solution @ArtyomZemlyak posted only works for TF1 (if you look at his source, it was posted in Posted on 2017-12-13, years before TF2 was released). Can we have a solution for TF2?

**Comment by roebel** [comment]
I had the same problem and used the following functions to load a selected part of a given model from a pretrained model with TF2.8. Note that for loading the model the path to the variables to be restored needs to be the same in the checkpoint instance you create for loading the selected model variables, and in the checkpoint instance you used to store the pretrained model. 
BTW, by means of mapping the attribute paths that is used to access the variable in the model you 
may also use similar functions when loading checkpoints after renaming the attributes in your model.

```python
import re
import tensorflow as tf
tf_load_checkpoint = tf.train.load_checkpoint

def assign_to_path(chkpoint_obj, path:str, value):
    """
    recursively follow a checkpoint path read fro a checkpoint and assign the variable in the appropriate leave
    """
    next_path = path[0]

    if next_path == ".ATTRIBUTES":
        chkpoint_obj.assign(value=value)
        return True
    elif next_path == ".OPTIMIZER_SLOT":
        raise NotImplementedError("assign_to_path::error::assignemnt of content of optimizer slots is not yet implemented.")
    elif next_path[0] in "0123456789":
        # path starting with a number is a list entry
        assign_to_path(chkpoint_obj=chkpoint_obj[int(next_path)], path=path[1:], value=value)
    elif hasattr(chkpoint_obj, next_path):
        assign_to_path(chkpoint_obj=getattr(chkpoint_obj, next_path), path=path[1:], value=value)
    else:
        raise RuntimeError(f"assign_to_path::error:: handling of path of form {next_path} with full path {path} not available")

def load_submodel_from_checkpoint(checkpoint_file_or_dir:str, chkpoint_obj:tf.train.Checkpoint, patterns: List[str]):
    """
    load all elements matching one of the patterns into the model
    """

    chkpoint_rdr = tf_load_checkpoint(checkpoint_file_or_dir)
    compiled_pats = [re.compile(pp) for pp in patterns]
    selected_path = []
    for path in chkpoint_rdr.get_variable_to_shape_map() :
        for cpat in compiled_pats:
            if cpat.match(path):
                selected_path.append(path)

    for selpath in selected_path:
        value = chkpoint_rdr.get_tensor(selpath)
        assign_to_path(chkpoint_obj=chkpoint_obj, path=selpath.split("/"), value=value)
```


Assuming you stored the checkpoint using a checkpoint as follows
```python
checkpoint_obj = tf.train.Checkpoint(optimizer=optimizer, model=pretrainedModel)
# ... store with tf.train.CheckpointManager or other means
```
  
The load_submodel_from_checkpoint function would be used as follows:

```python
print(f"try restoring partial model from {import_model_checkpoint_dir}", file=sys.stderr, flush=True)
# to be able to retrieve using checkpoint attributes we construct a temporary checkpoint that holds
# the model under the attribute used for checkpointing
checkpoint_obj = tf.train.Checkpoint(model=myModel)
load_submodel_from_checkpoint(checkpoint_file_or_dir=import_model_checkpoint_dir,
                                                      chkpoint_obj=checkpoint_obj, patterns=chkpoint_load_patterns)
```

**Comment by yjiangling** [comment]
any update? help is needed! a smart way is needed to load weights using checkpoint, and skip the layers which is related to the number of classification (because the shape of the weights is mismatch)
