### ISSUE TITLE
matmul gradients incorrect with complex64 tensors

### ISSUE THREAD

**Issue by mborgerding** [tensorflow/tensorflow#378]
The conjugation step was skipped.
See  https://tensorflow-review.googlesource.com/#/c/1154/ for unit tests and a fix

**Comment by vrv** [comment]
Thanks for the fix!  We'll try to get that reviewed and integrated soon.

**Comment by girving** [comment]
@vrv: Are you on this, or should I grab it?

**Comment by vrv** [comment]
Sorry, was supposed to assign this to @zffchen78

**Comment by vrv** [comment]
ZF: can you review https://tensorflow-review.googlesource.com/#/c/1154/ ?

**Comment by girving** [comment]
@vrv, @zffchen78: What happened to this?

**Comment by vrv** [comment]
It was submitted to gerrit, but it broke the build so we had to roll it back.  So I guess this is back to 'contributions welcome' :(

**Comment by girving** [comment]
For whoever looks at this next: I fixed `tf.test.compute_gradient_error` a while ago to handle `complex64` input, so it should be easy to test this change.

**Comment by ymodak** [comment]
@girving  Did you get a chance to test the fix? Can you please post your findings? This will help to resolve / update the status of this issue.

**Comment by girving** [comment]
@ymodak The fact that I fixed `tf.test.compute_gradient_error` means that others can easily test the fix.  I'm not going to do it myself.

**Comment by ymodak** [comment]
@mborgerding Can you please test the fix and post your findings? This will help to resolve / update the status of this issue.

**Comment by mborgerding** [comment]
Sigh ... almost three years after a issue was described, unit tests were provided and a fix was given.
Sorry, I don't have the time right now to go back and set my computer back up to verify this.  I seem to recall that it *has* been fixed, but I am only 95% sure of this, since it has been years.

**Comment by ymodak** [comment]
Closing this issue since the fix has been made.
