### ISSUE TITLE
Code improvements results from Cppcheck

### ISSUE THREAD

**Issue by jensdenbraber** [tensorflow/tensorflow#37808]
I ran [cppcheck](https://github.com/danmar/cppcheck) on the Tensorflow codebase which resulted in the some code improvements. 

Download the results here: [tensorflow_cppcheck.zip](https://github.com/tensorflow/tensorflow/files/4365647/tensorflow_cppcheck.zip)

**Comment by mihaimaruseac** [comment]
I should handle these by the weekend

**Comment by kevint324** [comment]
@jensdenbraber could you please share the config files (suppress, includes, etc.) for cppcheck to run properly?

Thanks a lot

**Comment by sushreebarsa** [comment]
@jensdenbraber Could you please refer to [this](https://github.com/tensorflow/tensorflow/issues/37808#issuecomment-725205323) comment above and update on the same ?
Thank you!
