### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by atul1234tiwari** [tensorflow/tensorflow#37809]
DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

Failed to load the native TensorFlow runtime.

**Comment by maxkaustav** [comment]
please use a perfect format or code to report

**Comment by mihaimaruseac** [comment]
Please fill in issue template on future issue reports. Also, please check for duplicates.

Closing as duplicate.

https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
