### ISSUE TITLE
Failed to load the native TensorFlow runtime

### ISSUE THREAD

**Issue by elyvision** [tensorflow/tensorflow#37804]
**System information**
- OS Platform and Distribution MAC version 10.10.5 
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0.1
- Python version: 3.7
- Installed using  conda :
- CUDA/cuDNN version: NVIDIA GeForce GT 330M 256 Mo
- GPU model and memory: mi-2010, 

**Describe the problem**

When i try to execut : import tensorflow as tf

i have :

ImportError: Traceback (most recent call last):
  File "/Users/Marot/miniconda3/envs/chatbot/lib/python3.5/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/Marot/miniconda3/envs/chatbot/lib/python3.5/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/Marot/miniconda3/envs/chatbot/lib/python3.5/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/Marot/miniconda3/envs/chatbot/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/Marot/miniconda3/envs/chatbot/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/Marot/miniconda3/envs/chatbot/lib/python3.5/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
  Referenced from: /Users/Marot/miniconda3/envs/chatbot/lib/python3.5/site-packages/tensorflow_core/python/../libtensorflow_framework.2.dylib
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Users/Marot/miniconda3/envs/chatbot/lib/python3.5/site-packages/tensorflow_core/python/../libtensorflow_framework.2.dylib

Failed to load the native TensorFlow runtime.

Can you help me.

please?

**Comment by elyvision** [comment]
Hey,
I instaled tensorflow with :

https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.8.0-py3-none-any.whl

After that a friend advised me to use this comand 

conda create -n tensorflow pip python=3

And now it work now,

Thank you very must for your answer

Have a good day

**Comment by amahendrakar** [comment]
@elyvision, 
Is this still an issue? Please feel free to close the issue if resolved. Thanks!
