### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by abhinavsp0730** [tensorflow/tensorflow#37807]
## URL(S) with issue:
https://github.com/tensorflow/federated/blob/master/docs/federated_core.md
In the above readme file [MapsReduce](https://research.google/pubs/pub62.pdf/)

### Pull Request
I've corrected the link and by successfully merging [#813](https://github.com/tensorflow/federated/pull/813) it'll resolve this issue.
Hey, @mihaimaruseac Kindly review it.

**Comment by jvishnuvardhan** [comment]
@abhinavsp0730 As mentioned by @MarkDaoust [here](https://github.com/tensorflow/tensorflow/issues/37783#issuecomment-602776176), please mention the following in the description of the PR

fixes: https://github.com/tensorflow/tensorflow/issues/37807 which closes this issue automatically when the corresponding PR gets merged. Thanks!

**Comment by abhinavsp0730** [comment]
Done

**Comment by jvishnuvardhan** [comment]
@abhinavsp0730 I see this issue of broken link was corrected already. Can you verify once and close the issue? thanks!

**Comment by abhinavsp0730** [comment]
Hey, @jvishnuvardhan I've linked a PR with this issue, Even though it's merged successfully but don't know why this issue hasn't been closed automatically. Would please give me some insight in this.
Nevertheless closing this issue.
