### ISSUE TITLE
Cannot build TensorFlow 2.2 branch on Windows 10

### ISSUE THREAD

**Issue by srogatch** [tensorflow/tensorflow#37802]
**System information**
- OS Platform and Distribution: Windows 10 Pro x64
- Mobile device: None
- TensorFlow installed from (source or binary): sources
- TensorFlow version: branch r2.2, commit acf4951a2f5fdc181ed14c163381c0cf135d9ee6
- Python version: 3.7.1
- Installed using virtualenv? pip? conda?: virtualenv with pip, without conda
- Bazel version (if compiling from source): the default version downloaded by Bazelisk
- GCC/Compiler version (if compiling from source): MSVS 2019 v16.5.0
- CUDA/cuDNN version: 10.2 / 7.6.5.32
- GPU model and memory: Geforce GTX 1080

**Describe the problem**

Compilation stops with the following error:
```
ERROR: D:/libs/ai_ml/tensorflow/tensorflow/lite/tools/optimize/BUILD:115:1: C++ compilation of rule '//tensorflow/lite/tools/optimize:operator_property' failed (Exit 2)
tensorflow/lite/tools/optimize/operator_property.cc(207): error C2679: binary '=': no operator found which takes a right-hand operand of type 'initializer list' (or there is no acceptable conversion)
.\tensorflow/lite/tools/optimize/operator_property.h(34): note: could be 'tflite::optimize::operator_property::DerivedScale &tflite::optimize::operator_property::DerivedScale::operator =(tflite::optimize::operator_property::DerivedScale &&) noexcept(<expr>)'
.\tensorflow/lite/tools/optimize/operator_property.h(34): note: or       'tflite::optimize::operator_property::DerivedScale &tflite::optimize::operator_property::DerivedScale::operator =(const tflite::optimize::operator_property::DerivedScale &)'
tensorflow/lite/tools/optimize/operator_property.cc(207): note: while trying to match the argument list '(tflite::optimize::operator_property::DerivedScale, initializer list)'
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
python ./configure.py
set path=C:\Programs\Build;C:\msys64\usr\bin;%PATH%
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
set BAZEL_VC="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC"
bazel build --copt=-nvcc_options=disable-warnings //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
None

**Comment by mihaimaruseac** [comment]
Can you build master instead? Trying to identify differences

**Comment by srogatch** [comment]
@mihaimaruseac , thanks for the suggestion - I'm trying this now, will keep you posted. Right from the beginning the problem with **master** branch is that `python ./configure.py` throws an exception in windows command line because the length of the command exceeds 32K characters. I workaround this by means of msys2. But I think it's better to reduce the command line so that `cmd.exe` can be used too.

**Comment by srogatch** [comment]
The master branch produces the following error for me:
```
ERROR: D:/libs/ai_ml/tensorflow/tensorflow/stream_executor/cuda/BUILD:425:1: C++ compilation of rule '//tensorflow/stream_executor/cuda:cusolver_stub' failed (Exit 2)
.\tensorflow/stream_executor/cuda/cusolver_dense_10_2.inc(204): error C2084: function 'cusolverStatus_t cusolverDnIRSInfosGetNiters(cusolverDnIRSParams_t,cusolverDnIRSInfos_t,cusolver_int_t *)' already has a body
.\tensorflow/stream_executor/cuda/cusolver_dense_10_2.inc(192): note: see previous definition of 'cusolverDnIRSInfosGetNiters'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

**Comment by srogatch** [comment]
On master branch the compilation hangs for more than 10 hours:
```
[4,094 / 5,097] 16 actions running
    Compiling tensorflow/core/kernels/cwise_op_sub.cc; 38326s local
    Compiling tensorflow/core/kernels/cwise_op_div.cc; 37932s local
    Compiling tensorflow/core/kernels/cwise_op_equal_to_1.cc; 37805s local
    Compiling tensorflow/core/kernels/cwise_op_igammas.cc; 24395s local
    Compiling tensorflow/core/kernels/cwise_op_left_shift.cc; 18171s local
    Compiling tensorflow/core/kernels/cwise_op_less.cc; 18112s local
    Compiling tensorflow/core/kernels/cwise_op_less_equal.cc; 15807s local
    Compiling tensorflow/core/kernels/cwise_op_greater_equal.cc; 14404s local ...
```

**Comment by gunan** [comment]
Unfortunately, they are not hanging. Some kernels do take that long to compile.
One way to make it faster is to add the `--define=override_eigen_strong_inline=true` flag to your bazel command.

For me, the builds have been healthy, but I will retry.

**Comment by srogatch** [comment]
After I let these compilations run longer, I'm getting the following error:
```
ERROR: D:/libs/ai_ml/tensorflow/tensorflow/core/kernels/BUILD:4084:1: C++ compilation of rule '//tensorflow/core/kernels:cwise_op' failed (Exit -1)
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 18869.605s, Critical Path: 18103.23s
INFO: 1730 processes: 1730 local.
FAILED: Build did NOT complete successfully
```
No details about any compilation error are provided above these lines.

**Comment by srogatch** [comment]
Finally, after updating to a later revision of master branch and disabling inlining in configure.py, I was able to build tensorflow, however, the following command then fails:
```
(BuildTF) D:\Libs\ai_ml\tensorflow>bazel-bin\tensorflow\tools\pip_package\build_pip_package D:/Libs/ai_ml/Built/tensorflow_pkg
Tue Mar 24 15:29:07 BST 2020 : === Preparing sources in dir: /tmp/tmp.IxVMcIFyRl
Unzipping simple_console_for_windows.zip to create runfiles tree...
[./bazel-bin/tensorflow/tools/pip_package/simple_console_for_windows.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ./bazel-bin/tensorflow/tools/pip_package/simple_console_for_windows.zip or
        ./bazel-bin/tensorflow/tools/pip_package/simple_console_for_windows.zip.zip, and cannot find ./bazel-bin/tensorflow/tools/pip_package/simple_console_for_windows.zip.ZIP, period.
```

**Comment by srogatch** [comment]
I managed to workaround the above issue with https://stackoverflow.com/questions/52394305/creating-pip-package-for-tensorflow-with-gpu-support-results-in-0-byte-simple-co . However, I had to delete a lot of `.zip` files from getting into `simple_console_for_windows.zip`. Can someone elaborate on the consequences of deleting those files?

**Comment by gunan** [comment]
yeah, the above issue you saw is also known.
The zip file gets larger than 2GB, and zip fails. Unfortunately, bazel does not report an actionable issue for us there.
for building the pip package, bazel team helped us create some flags where we can use only for building the pip package, which does not build some of those zip files. so as long as your pip package is working, you should be ok.

**Comment by ahtik** [comment]
@srogatch I have built TensorFlow 2.2 rc3 now successfully on Windows 10 with both Python 3.8 and 3.7, also CUDA 10.1 and CUDA 10.2. Without any tweaks to the source.

Posted some notes on building to https://github.com/tensorflow/tensorflow/issues/38174#issuecomment-613722488 that might help with your build speed.

Do you also get the 2GB zip issue with a no_tensorflow_py_deps flag?
`bazel build --config=opt --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package`

**Comment by srogatch** [comment]
@ahtik , thanks for following up. Unfortunately, currently, Tensorflow experiments are not relevant to me. You can close the issue. And the command you gave should be a good resolution.
