### ISSUE TITLE
typo in https://www.tensorflow.org/guide/upgrade

### ISSUE THREAD

**Issue by rushabh-v** [tensorflow/tensorflow#37800]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://www.tensorflow.org/guide/upgrade#recommended_upgrade_process

## Description of issue (what needs changing):
there is two consecutive "will" in the point `Run the upgrade script`. 

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? 
Yes. I'll be opening a PR soon.

**Comment by Saduf2019** [comment]
rushabh-v 
please confirm if we may close this issue as its been monitored in pr #1509
