### ISSUE TITLE
redefinition of cusolverStatus_t in tensorflow/stream_executor/cuda/cusolver_dense_10_2.inc at lines 192 and 202

### ISSUE THREAD

**Issue by ranavjk** [tensorflow/tensorflow#37812]
I tried building TF on my system (ubuntu x86_64, cuda 10.2). I came across this error after about 15 mins of compiling. 

<em>In file included from tensorflow/stream_executor/cuda/cusolver_stub.cc:61:0:
./tensorflow/stream_executor/cuda/cusolver_dense_10_2.inc: In function 'cusolverStatus_t cusolverDnIRSInfosGetNiters(cusolverDnIRSParams_t, cusolverDnIRSInfos_t, cusolver_int_t*)':
./tensorflow/stream_executor/cuda/cusolver_dense_10_2.inc:202:30: error: redefinition of 'cusolverStatus_t cusolverDnIRSInfosGetNiters(cusolverDnIRSParams_t, cusolverDnIRSInfos_t, cusolver_int_t*)'
 cusolverStatus_t CUSOLVERAPI cusolverDnIRSInfosGetNiters(
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
./tensorflow/stream_executor/cuda/cusolver_dense_10_2.inc:192:30: note: 'cusolverStatus_t cusolverDnIRSInfosGetNiters(cusolverDnIRSParams_t, cusolverDnIRSInfos_t, cusolver_int_t*)' previously defined here
 cusolverStatus_t CUSOLVERAPI cusolverDnIRSInfosGetNiters(
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
</em>
Two definitions are right one after the other. Both functions seem to be identical. I am going to delete one of the definitions, and restart the build. Keeping my fingers crossed.

**Comment by gadagashwini** [comment]
@ranavjk,
Please Provide the exact sequence of commands / steps that you executed before running into the problem and also provide the Tensorflow version which you are trying to build. Thanks!

**Comment by ranavjk** [comment]
1. set up config (./configure) -> all defaults except for cuda=yes and tensorRT=yes.
2. When asked for cuda paths: cuda path = /usr/local/cuda-10.2, cudnn path = /usr/include,/usr/lib, tensorRT path =/usr/local/tensorRT 
3. bazel build --config=cuda --verbose_failures //tensorflow/tools/lib_package:libtensorflow
4. As I pointed earlier, function `cusolverDnIRSInfosGetNiters(cusolverDnIRSParams_t, cusolverDnIRSInfos_t, cusolver_int_t*)` is defined twice on line#192 and 202 in the file `tensorflow/stream_executor/cuda/cusolver_dense_10_2.inc` . I deleted one of those functions and build went fine from there. I did get a linking error at the end. Will work on that today.
5. Tensorflow version: 2

**Comment by powderluv** [comment]
Can confirm this error.

**Comment by powderluv** [comment]
Fixed here: https://github.com/tensorflow/tensorflow/pull/37843

**Comment by powderluv** [comment]
Fix is merged in master. Feel free to close the issue.

**Comment by gadagashwini** [comment]
@ranavjk, Associated PR has been merged can you close this issue. Thanks!
