### ISSUE TITLE
GET returned 401 Unauthorized for  repository 'upb

### ISSUE THREAD

**Issue by etsangsplk** [tensorflow/tensorflow#37811]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
macox 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
source (github head)
- TensorFlow version:
master
- Python version:
2..7
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
2.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

```
INFO: Call stack for the definition of repository 'upb' which is a http_archive (rule definition at /private/var/tmp/_bazel_etsang/4c08b338ce3f5893c94fb26f4e062082/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /private/var/tmp/_bazel_etsang/4c08b338ce3f5893c94fb26f4e062082/external/com_github_grpc_grpc/bazel/grpc_deps.bzl:228:9
 - /Users/etsang/dev/src/github.com/tensorflow/tensorflow/WORKSPACE:121:1
WARNING: Download from https://github.com/protocolbuffers/upb/archive/9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 401 Unauthorized
ERROR: An error occurred during the fetch of repository 'upb':
   java.io.IOException: Error downloading [https://github.com/protocolbuffers/upb/archive/9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz] to /private/var/tmp/_bazel_etsang/4c08b338ce3f5893c94fb26f4e062082/external/upb/9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz: GET returned 401 Unauthorized
ERROR: no such package '@upb//bazel': java.io.IOException: Error downloading [https://github.com/protocolbuffers/upb/archive/9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz] to /private/var/tmp/_bazel_etsang/4c08b338ce3f5893c94fb26f4e062082/external/upb/9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz: GET returned 401 Unauthorized
ERROR: no such package '@upb//bazel': java.io.IOException: Error downloading [https://github.com/protocolbuffers/upb/archive/9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz] to /private/var/tmp/_bazel_etsang/4c08b338ce3f5893c94fb26f4e062082/external/upb/9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz: GET returned 401 Unauthorized
```
**Provide the exact sequence of commands / steps that you executed before running into the problem**
./configure
answer the questions interactively prompted form ./configure
bazel build (no target to see what happens)
Errorred out
I already have .netrc setup under my home folder with the correct credentials

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by etsangsplk** [comment]
full error. It turned out it is personal token. github remove login and password for rest request. So just edit .netrc to use personal token instead of login password works.

**Comment by mihaimaruseac** [comment]
In that case, can we close issue?

**Comment by etsangsplk** [comment]
yes please
