### ISSUE TITLE
import_pb_to_tensorboard.py OSError

### ISSUE THREAD

**Issue by LAWSSSS** [tensorflow/tensorflow#37814]
`python import_pb_to_tensorboard.py --model_dir C:/Users/LAWSSSS/Desktop/convert_pb_2_tflite/mnist_model_graph.pb --log_dir /tmp/tensorflow_logdir
OSError: SavedModel file does not exist at: C:/Users/LAWSSSS/Desktop/convert_pb_2_tflite/mnist_model_graph.pb`
But I'm pretty sure that I put it in this path, how can I solve this problem?

**Comment by howl-anderson** [comment]
If you are using TF 2.1, the `import_pb_to_tensorboard.py` expect `--model_dir` point to the location of SavedModel dir (not the `.pb` file).  The script will search `saved_model.pb` or `saved_model.pbtxt` in model dir. see #37529

**Comment by LAWSSSS** [comment]
> If you are using TF 2.1, the `import_pb_to_tensorboard.py` expect `--model_dir` point to the location of SavedModel dir (not the `.pb` file). The script will search `saved_model.pb` or `saved_model.pbtxt` in model dir. see #37529

Hi, I'm using TF 1.14 and I do as you said, but I still got the same OSerror:
`python import_pb_to_tensorboard.py --model_dir C:/Users/LAWSSSS/Desktop/convert_pb_2_tflite --log_dir /log
OSError: SavedModel file does not exist at: C:/Users/LAWSSSS/Desktop/convert_pb_2_tflite`
What am I doing wrong?

**Comment by howl-anderson** [comment]
@LAWSSSS I have read the code of TF 1.14, it's different from TF 2.0, you should pass the path of `.pb` file as `--model_dir`.

**Comment by LAWSSSS** [comment]
@howl-anderson I did as you said but the error still showed up:
`python import_pb_to_tensorboard.py --model_dir C:/Users/LAWSSSS/Desktop/convert_pb_2_tflite/mnist_model_graph.pb --log_dir /tmp/tensorflow_logdir`
`OSError: SavedModel file does not exist at: C:/Users/LAWSSSS/Desktop/convert_pb_2_tflite/mnist_model_graph.pb`
However, this code using the same model path works out just fine:
```
import os
from tensorflow.python.tools.import_pb_to_tensorboard import import_to_tensorboard
model_dir = r'C:\Users\LAWSSSS\Desktop\convert_pb_2_tflite'
model = os.path.join(model_dir, 'mnist_model_graph.pb')
print(model)

import_to_tensorboard(model_dir=model, log_dir='log_test/')
```
Since these two model paths are the same, I can't figure out what goes wrong in the first measure.

**Comment by howl-anderson** [comment]
@LAWSSSS The error msg `SavedModel file does not exist at ...` shows that your are NOT using tf 1.14, probably one of TF 2.x , please double check it.

**Comment by LAWSSSS** [comment]
@howl-anderson  Sorry for the late response and thanks for the pointer.  I've checked the TF version, and I'm sure that it's TF 1.14.0. Any insight on this problem?

**Comment by howl-anderson** [comment]
@LAWSSSS In your `python import_pb_to_tensorboard.py --model_dir C:/Users/LAWSSSS/Desktop/convert_pb_2_tflite/mnist_model_graph.pb --log_dir /tmp/tensorflow_logdir` where the file `import_pb_to_tensorboard.py` come from?

**Comment by LAWSSSS** [comment]
@howl-anderson Thanks a lot. Following your instruction, I finally solve my problem. The `import_pb_to_tensorboard.py` is from a blog, not my original installed tensorflow folder. After replacing it with my own installed tensorflow file, the problem is solved.
