### ISSUE TITLE
Tensorboard overlays the legend on top of curve, making it hard to see the curve itself

### ISSUE THREAD

**Issue by rohitgirdhar** [tensorflow/tensorflow#3782]
**Feature Request** (This is not super high-priority, but would be nice to have)
Tensorboard overlays the legend on top of the graph, sometimes making it hard to see parts of the graph. It would be better that the legend location can be at the top/bottom depending on the mouse position, so it does not overlap on the graph itself. Example:
![screen shot 2016-08-10 at 10 01 25 am](https://cloud.githubusercontent.com/assets/1893429/17637456/7b4db6ae-6098-11e6-9458-93a5beea19c8.png)

### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN: CUDA 7.5.18, cuDNN 5
If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`): 056db850614e0a06ce6f65b30f877c5789ab74f5
2. The output of `bazel version`: Build label: 0.3.0

**Comment by RenatoUtsch** [comment]
This has been fixed in master branch, now the tooltip is shown on the bottom of the chart to not overlap with the graph.
