### ISSUE TITLE
out of memory issue in running face-api.js

### ISSUE THREAD

**Issue by Rajeshwari210** [tensorflow/tensorflow#37824]
hii 
while running face-api.js node examples (node faceRecognition.js) am getting the OOM error while running 2 hour video face recognition. how can solve this issue.
 
2020-03-20 16:12:39.728434: W tensorflow/core/framework/op_kernel.cc:1651] OP_RE
QUIRES failed at cwise_ops_common.cc:82 : Resource exhausted: OOM when allocatin
g tensor with shape[1,32,32,512] and type float on /job:localhost/replica:0/task
:0/device:CPU:0 by allocator cpu
Exception code=0xc0000005 flags=0x0 at 0x00007FF957AEA277. Access violation - at
tempting to read data at address 0x0000000000000010

**Comment by gadagashwini** [comment]
@Rajeshwari210,
Please Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks

**Comment by Rajeshwari210** [comment]
$ tsc --skipLibCheck faceRecognition.ts
 node faceRecognition.js
am running these two commands and i'm uploading 1hr video as input which creates the frame(through ffmpeg extract frames) and compares with face-api module and print the confidence score. after 750 frames am getting **OMM** (out of memory) issue.

**Comment by gadagashwini** [comment]
@Rajeshwari210, This issue is not related to Tensorflow can you post this issue in relevant repo TFjs. Thanks

**Comment by gadagashwini** [comment]
@Rajeshwari210, Please update for the above comment. Thanks

**Comment by gadagashwini** [comment]
Closing this issue since its not related to Tensorflow. Please post this issue in TFJS repo.
Thanks
