### ISSUE TITLE
Op type not registered 'HashTableV2' in binary running on 5f00e250dfa5

### ISSUE THREAD

**Issue by tianhongbao** [tensorflow/tensorflow#37826]
when I load a model of CRNN,I find this peoblem.
ERROR: Creating graph in session failed...Not found: Op type not registered 'HashTableV2' in binary running on 5f00e250dfa5. Make sure the Op and Kernel are registered in the binary running in this process.

I use this code:
` 
#include <fstream>
#include <utility>
#include <vector>
#include <Eigen/Core>
#include <Eigen/Dense>

#include "tensorflow/core/framework/graph.pb.h"
#include "tensorflow/core/framework/tensor.h"
#include "tensorflow/core/graph/default_device.h"
#include "tensorflow/core/graph/graph_def_builder.h"
#include "tensorflow/core/lib/core/errors.h"
#include "tensorflow/core/lib/core/stringpiece.h"
#include "tensorflow/core/lib/core/threadpool.h"
#include "tensorflow/core/lib/io/path.h"
#include "tensorflow/core/lib/strings/stringprintf.h"
#include "tensorflow/core/platform/env.h"
#include "tensorflow/core/platform/init_main.h"
#include "tensorflow/core/platform/logging.h"
#include "tensorflow/core/platform/types.h"
#include "tensorflow/core/public/session.h"
#include "tensorflow/core/util/command_line_flags.h"

#include <iostream>

using namespace std;
using namespace tensorflow;

int main()
{
    Session* session;
    Status status = NewSession(SessionOptions(), &session);

    if (!status.ok()) {
        cout << status.ToString() << "\n";
        return 1;
    }
    cout << "Session successfully created.\n";
    string model_path="/tensorflow_cc/mnist/crnn_frozen_model.pb";
    GraphDef graphdef; //Graph Definition for current model

    Status status_load = ReadBinaryProto(Env::Default(), model_path, &graphdef); / 
    if (!status_load.ok()) {
        std::cout << "ERROR: Loading model failed..." << model_path << std::endl;
        std::cout << status_load.ToString() << "\n";
        return -1;
    }
    Status status_create = session->Create(graphdef);  
    if (!status_create.ok()) {
        std::cout << "ERROR: Creating graph in session failed..." << status_create.ToString() << std::endl;
        return -1;
    }
    cout << "Session successfully created."<< endl;
}
`

**Comment by ravikyram** [comment]
@tianhongbao 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Thanks!

**Comment by tianhongbao** [comment]
@ravikyram ubuntu,tensorflow c++ 1.13.0

**Comment by gowthamkpr** [comment]
@tianhongbao Can you please try with tensorflow versions >=1.14.0 and let me know if the issue still persists.

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 2 weeks. Please add additional comments for us to open this issue again. Thanks!
