### ISSUE TITLE
How to solve this problem？（c++ tensorflow+opencv ）

### ISSUE THREAD

**Issue by heartraeh** [tensorflow/tensorflow#37823]
/home/sy/tensorflow/bazel-genfiles/tensorflow/core/protobuf/config.pb.h:4350:30: note: suggested alternative: ‘GOOGLE_DLOG’
   operation_timeout_in_ms_ = GOOGLE_LONGLONG(0);
                              ^~~~~~~~~~~~~~~
                              GOOGLE_DLOG
/home/sy/tensorflow/bazel-genfiles/tensorflow/core/protobuf/config.pb.h: In member function ‘void tensorflow::RunOptions_Experimental::clear_collective_graph_key()’:
/home/sy/tensorflow/bazel-genfiles/tensorflow/core/protobuf/config.pb.h:4571:27: error: ‘GOOGLE_LONGLONG’ was not declared in this scope
   collective_graph_key_ = GOOGLE_LONGLONG(0);
                           ^~~~~~~~~~~~~~~
/home/sy/tensorflow/bazel-genfiles/tensorflow/core/protobuf/config.pb.h:4571:27: note: suggested alternative: ‘GOOGLE_DLOG’
   collective_graph_key_ = GOOGLE_LONGLONG(0);
                           ^~~~~~~~~~~~~~~
                           GOOGLE_DLOG
/home/sy/tensorflow/bazel-genfiles/tensorflow/core/protobuf/config.pb.h: In member function ‘void tensorflow::RunOptions::clear_timeout_in_ms()’:
/home/sy/tensorflow/bazel-genfiles/tensorflow/core/protobuf/config.pb.h:4617:20: error: ‘GOOGLE_LONGLONG’ was not declared in this scope
   timeout_in_ms_ = GOOGLE_LONGLONG(0);
                    ^~~~~~~~~~~~~~~
/home/sy/tensorflow/bazel-genfiles/tensorflow/core/protobuf/config.pb.h:4617:20: note: suggested alternative: ‘GOOGLE_DLOG’
   timeout_in_ms_ = GOOGLE_LONGLONG(0);
                    ^~~~~~~~~~~~~~~
                    GOOGLE_DLOG

**Comment by Saduf2019** [comment]
@heartraeh 
could you please share how you encountered this problem, a simple stand alone code for us to replicate the issue faced along with the tensor flow version.

**Comment by heartraeh** [comment]
#include <iostream&gt;
&nbsp;
#include "tensorflow/cc/ops/const_op.h"
#include "tensorflow/cc/ops/image_ops.h"
#include "tensorflow/cc/ops/standard_ops.h"
#include "tensorflow/core/framework/graph.pb.h"
#include "tensorflow/core/framework/tensor.h"
#include "tensorflow/core/graph/default_device.h"
#include "tensorflow/core/graph/graph_def_builder.h"
#include "tensorflow/core/lib/core/errors.h"
#include "tensorflow/core/lib/core/stringpiece.h"
#include "tensorflow/core/lib/core/threadpool.h"
#include "tensorflow/core/lib/io/path.h"
#include "tensorflow/core/lib/strings/stringprintf.h"
#include "tensorflow/core/platform/env.h"
#include "tensorflow/core/platform/init_main.h"
#include "tensorflow/core/platform/logging.h"
#include "tensorflow/core/platform/types.h"
#include "tensorflow/core/public/session.h"
#include "tensorflow/core/util/command_line_flags.h"
&nbsp;
#include <opencv2/opencv.hpp&gt;
#include <cv.h&gt;
#include <highgui.h&gt;
#include <Eigen/Core&gt;
#include <Eigen/Dense&gt;
&nbsp;
using namespace std;
using namespace cv;
using namespace tensorflow;
&nbsp;
&nbsp;
&nbsp;
// 定义一个函数讲OpenCV的Mat数据转化为tensor，python里面只要对cv2.read读进来的矩阵进行np.reshape之后，
// 数据类型就成了一个tensor，即tensor与矩阵一样，然后就可以输入到网络的入口了，但是C++版本，我们网络开放的入口
// 也需要将输入图片转化成一个tensor，所以如果用OpenCV读取图片的话，就是一个Mat，然后就要考虑怎么将Mat转化为
// Tensor了
void CVMat_to_Tensor(Mat img,Tensor* output_tensor,int input_rows,int input_cols)
{
&nbsp; &nbsp; //imshow("input image",img);
&nbsp; &nbsp; //图像进行resize处理
&nbsp; &nbsp; resize(img,img,cv::Size(input_cols,input_rows));
&nbsp; &nbsp; //imshow("resized image",img);
&nbsp;
&nbsp; &nbsp; //归一化
&nbsp; &nbsp; img.convertTo(img,CV_8UC3);&nbsp; // CV_32FC3
&nbsp; &nbsp; //img=1-img/255;
&nbsp;
&nbsp; &nbsp; //创建一个指向tensor的内容的指针
&nbsp; &nbsp; uint8 *p = output_tensor-&gt;flat<uint8&gt;().data();
&nbsp;
&nbsp; &nbsp; //创建一个Mat，与tensor的指针绑定,改变这个Mat的值，就相当于改变tensor的值
&nbsp; &nbsp; cv::Mat tempMat(input_rows, input_cols, CV_8UC3, p);
&nbsp; &nbsp; img.convertTo(tempMat,CV_8UC3);
&nbsp;
&nbsp;//&nbsp; &nbsp; waitKey(0);
&nbsp;
}
&nbsp;
int main()
{
&nbsp; &nbsp; /*--------------------------------配置关键信息------------------------------*/
&nbsp; &nbsp; string model_path="../model/coco.pb";
&nbsp; &nbsp; string image_path="../test.jpg";
&nbsp; &nbsp; int input_height = 1000;
&nbsp; &nbsp; int input_width = 1000;
&nbsp; &nbsp; string input_tensor_name="image_tensor";
&nbsp; &nbsp; vector<string&gt; out_put_nodes;&nbsp; //注意，在object detection中输出的三个节点名称为以下三个
&nbsp; &nbsp; out_put_nodes.push_back("detection_scores");&nbsp; //detection_scores&nbsp; detection_classes&nbsp; detection_boxes
&nbsp; &nbsp; out_put_nodes.push_back("detection_classes");
&nbsp; &nbsp; out_put_nodes.push_back("detection_boxes");
&nbsp;
&nbsp; &nbsp; /*--------------------------------创建session------------------------------*/
&nbsp; &nbsp; Session* session;
&nbsp; &nbsp; Status status = NewSession(SessionOptions(), &amp;session);//创建新会话Session
&nbsp;
&nbsp; &nbsp; /*--------------------------------从pb文件中读取模型--------------------------------*/
&nbsp; &nbsp; GraphDef graphdef; //Graph Definition for current model
&nbsp;
&nbsp; &nbsp; Status status_load = ReadBinaryProto(Env::Default(), model_path, &amp;graphdef); //从pb文件中读取图模型;
&nbsp; &nbsp; if (!status_load.ok()) {
&nbsp; &nbsp; &nbsp; &nbsp; cout << "ERROR: Loading model failed..." << model_path << std::endl;
&nbsp; &nbsp; &nbsp; &nbsp; cout << status_load.ToString() << "\n";
&nbsp; &nbsp; &nbsp; &nbsp; return -1;
&nbsp; &nbsp; }
&nbsp; &nbsp; Status status_create = session-&gt;Create(graphdef); //将模型导入会话Session中;
&nbsp; &nbsp; if (!status_create.ok()) {
&nbsp; &nbsp; &nbsp; &nbsp; cout << "ERROR: Creating graph in session failed..." << status_create.ToString() << std::endl;
&nbsp; &nbsp; &nbsp; &nbsp; return -1;
&nbsp; &nbsp; }
&nbsp; &nbsp; cout << "<----Successfully created session and load graph.-------&gt;"<< endl;
&nbsp;
&nbsp; &nbsp; /*---------------------------------载入测试图片-------------------------------------*/
&nbsp; &nbsp; cout<<endl<<"<------------loading test_image--------------&gt;"<<endl;
&nbsp; &nbsp; Mat img;
&nbsp; &nbsp; img = imread(image_path);
&nbsp; &nbsp; cvtColor(img, img, CV_BGR2RGB);
&nbsp; &nbsp; if(img.empty())
&nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; cout<<"can't open the image!!!!!!!"<<endl;
&nbsp; &nbsp; &nbsp; &nbsp; return -1;
&nbsp; &nbsp; }
&nbsp;
&nbsp; &nbsp; //创建一个tensor作为输入网络的接口
&nbsp; &nbsp; Tensor resized_tensor(DT_UINT8, TensorShape({1,input_height,input_width,3})); //DT_FLOAT
&nbsp;
&nbsp; &nbsp; //将Opencv的Mat格式的图片存入tensor
&nbsp; &nbsp; CVMat_to_Tensor(img,&amp;resized_tensor,input_height,input_width);
&nbsp;
&nbsp; &nbsp; cout << resized_tensor.DebugString()<<endl;
&nbsp;
&nbsp; &nbsp; /*-----------------------------------用网络进行测试-----------------------------------------*/
&nbsp; &nbsp; cout<<endl<<"<-------------Running the model with test_image---------------&gt;"<<endl;
&nbsp; &nbsp; //前向运行，输出结果一定是一个tensor的vector
&nbsp; &nbsp; vector<tensorflow::Tensor&gt; outputs;
&nbsp;
&nbsp; &nbsp; Status status_run = session-&gt;Run({{input_tensor_name, resized_tensor}}, {out_put_nodes}, {}, &amp;outputs);
&nbsp;
&nbsp; &nbsp; if (!status_run.ok()) {
&nbsp; &nbsp; &nbsp; &nbsp; cout << "ERROR: RUN failed..."&nbsp; << std::endl;
&nbsp; &nbsp; &nbsp; &nbsp; cout << status_run.ToString() << "\n";
&nbsp; &nbsp; &nbsp; &nbsp; return -1;
&nbsp; &nbsp; }
&nbsp;
&nbsp; &nbsp; //把输出值给提取出
&nbsp; &nbsp; cout << "Output tensor size:" << outputs.size() << std::endl;&nbsp; //3
&nbsp; &nbsp; for (int i = 0; i < outputs.size(); i++)
&nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; cout << outputs[i].DebugString()<<endl;&nbsp; &nbsp;// [1, 50], [1, 50], [1, 50, 4]
&nbsp; &nbsp; }
&nbsp;
&nbsp; &nbsp; cvtColor(img, img, CV_RGB2BGR);&nbsp; // opencv读入的是BGR格式输入网络前转为RGB
&nbsp; &nbsp; resize(img,img,cv::Size(1000,1000));&nbsp; // 模型输入图像大小
&nbsp; &nbsp; int pre_num = outputs[0].dim_size(1);&nbsp; // 50&nbsp; 模型预测的目标数量
&nbsp; &nbsp; auto tmap_pro = outputs[0].tensor<float, 2&gt;();&nbsp; //第一个是score输出shape为[1,50]
&nbsp; &nbsp; auto tmap_clas = outputs[1].tensor<float, 2&gt;();&nbsp; //第二个是class输出shape为[1,50]
&nbsp; &nbsp; auto tmap_coor = outputs[2].tensor<float, 3&gt;();&nbsp; //第三个是coordinate输出shape为[1,50,4]
&nbsp; &nbsp; float probability = 0.5;&nbsp; //自己设定的score阈值
&nbsp; &nbsp; for (int pre_i = 0; pre_i < pre_num; pre_i++)
&nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; if (tmap_pro(0, pre_i) < probability)
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; break;
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; cout << "Class ID: " << tmap_clas(0, pre_i) << endl;
&nbsp; &nbsp; &nbsp; &nbsp; cout << "Probability: " << tmap_pro(0, pre_i) << endl;
&nbsp; &nbsp; &nbsp; &nbsp; string id = to_string(int(tmap_clas(0, pre_i)));
&nbsp; &nbsp; &nbsp; &nbsp; int xmin = int(tmap_coor(0, pre_i, 1) * input_width);
&nbsp; &nbsp; &nbsp; &nbsp; int ymin = int(tmap_coor(0, pre_i, 0) * input_height);
&nbsp; &nbsp; &nbsp; &nbsp; int xmax = int(tmap_coor(0, pre_i, 3) * input_width);
&nbsp; &nbsp; &nbsp; &nbsp; int ymax = int(tmap_coor(0, pre_i, 2) * input_height);
&nbsp; &nbsp; &nbsp; &nbsp; cout << "Xmin is: " << xmin << endl;
&nbsp; &nbsp; &nbsp; &nbsp; cout << "Ymin is: " << ymin << endl;
&nbsp; &nbsp; &nbsp; &nbsp; cout << "Xmax is: " << xmax << endl;
&nbsp; &nbsp; &nbsp; &nbsp; cout << "Ymax is: " << ymax << endl;
&nbsp; &nbsp; &nbsp; &nbsp; rectangle(img, cvPoint(xmin, ymin), cvPoint(xmax, ymax), Scalar(255, 0, 0), 1, 1, 0);
&nbsp; &nbsp; &nbsp; &nbsp; putText(img, id, cvPoint(xmin, ymin), FONT_HERSHEY_COMPLEX, 1.0, Scalar(255,0,0), 1);
&nbsp; &nbsp; }
&nbsp; &nbsp; imshow("1", img);
&nbsp; &nbsp; cvWaitKey(0);
&nbsp;
&nbsp; &nbsp; return 0;
}



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Saduf2019"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月23日(星期一) 下午5:09
收件人:&nbsp;"tensorflow/tensorflow"<tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"武文博"<wuwenboxyz@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tensorflow/tensorflow] How to solve this problem？（c++ tensorflow+opencv ） (#37823)





 
@heartraeh
 could you please share how you encountered this problem, a simple stand alone code for us to replicate the issue faced along with the tensor flow version.

**Comment by Saduf2019** [comment]
@heartraeh 
please update tensorflow version

**Comment by Saduf2019** [comment]
@heartraeh
please update as per above comment

**Comment by Saduf2019** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
