### ISSUE TITLE
Replace VarHandleOp in Keras with VariableV2

### ISSUE THREAD

**Issue by summelon** [tensorflow/tensorflow#37830]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue: https://www.tensorflow.org/api_docs/python/tf/Variable

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/MyMethod

### Clear description

TF 1.13.1
I can't find anything detail about differences between VarHandlOp and VariableV2. 
As far as I know it seems that VarHandleOp implement in Keras and VariableV2 in TF 1.X. 
How can I convert VarHandleOp to VariableV2 in tf.keras?
I'm using some model processing tool that can only run under VariableV2 ops.

### Correct links

https://git.codingcafe.org/Mirrors/tensorflow/tensorflow/commit/e4a5c5356063d7f7b324a5771fe296bb199b532c
Somelink above is all I could find.

### Parameters defined

---

### Returns defined

---

### Raises listed and defined

---

### Usage example

Is this a usage example?
https://www.tensorflow.org/api_docs/python/tf/raw_ops/VariableV2?hl=pl
Is that a kind of example?

### Request visuals, if applicable

---

### Submit a pull request?
---

**Comment by ashutosh1919** [comment]
@summelon, Can you provide any keras doc link for VarHandleOp since I am not able to find it anywhere?

**Comment by summelon** [comment]
@ashutosh1919 Thanks for your reply.
I don't know where is it in keras doc. But it is something in TF doc like this https://www.tensorflow.org/api_docs/python/tf/raw_ops/VarHandleOp?hl=ko .
My empirical observation is that it's used in tf.keras defined model arch(VarHandleOp). 
On the other hand, VariableV2 in tensorflow defined model arch.
I can't figure out differences between these two.
And how to replace VarHandleOp with VariableV2?

I would be grateful for any help you are able to provide.

**Comment by ashutosh1919** [comment]
@summelon , Please checkout the PR #37855 .

**Comment by amahendrakar** [comment]
> @summelon , Please checkout the PR #37855 .

@summelon,
Could you please check @ashutosh1919's comment and let us know if it helps. Thanks!

**Comment by summelon** [comment]
@amahendrakar Oh! My bad. I missed the message you provided in "Files change".
Thanks for your example.
However it still got me confused because of components of these two.
When I running my prunning code, it led to different result(work VariableV2).
I can't figure out why or provide my source code.
It would be helpful if you guys can give me some hints.

Thank you!

**Comment by summelon** [comment]
By the way, My framework is under TF 1.13.1, which I think may be  different with TF 2.1.

**Comment by summelon** [comment]
Update: After recognizing VarHandleOp and VariableV2, I found the problem of my code is still the difference between Op type. In TF-slim defined model, the program identify prunable Ops by scope with "*/read" and their type are "Identify". while in Keras, it seems that Ops are turn into "*/ReadVariableOp" and their type are also "ReadVariableOp".
Would you like to tell me some helpful information about these two kinds of Ops?

**Comment by ashutosh1919** [comment]
cc @fchollet 

> Update: After recognizing VarHandleOp and VariableV2, I found the problem of my code is still the difference between Op type. In TF-slim defined model, the program identify prunable Ops by scope with "_/read" and their type are "Identify". while in Keras, it seems that Ops are turn into "_/ReadVariableOp" and their type are also "ReadVariableOp".
> Would you like to tell me some helpful information about these two kinds of Ops?

cc @fchollet

**Comment by summelon** [comment]
Update: It seems that "Identify" type ops(e.g. "resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/weights/read" in tf-slim) and ReadVariableOp type ops(e.g.  "res4f_branch2a/kernel/Read/ReadVariableOp" in Keras) have similar characteristic when I check their type or shape.

I tried to detect "ReadVariableOp" instead of "Identify" Ops. However now another problem occured. 

In TF-Slim, outputs of "*/weights" and "*/weights/read" are "<tf.Tensor 'resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/weights:0' shape=(1, 1, 64, 64) dtype=float32_ref>" and "<tf.Tensor 'resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/weights/read:0' shape=(1, 1, 64, 64) dtype=float32>" respectively.
On the other hand, in Keras, outputs of "*/kernel" and "*/kernel/Read/ReadVariableOp" are "<tf.Tensor 'res4f_branch2a/kernel:0' shape=() dtype=resource>" and "<tf.Tensor 'res4f_branch2a/kernel/Read/ReadVariableOp:0' shape=(1, 1, 1024, 256) dtype=float32>" respectively.

When I tried to use "tf.compat.v1.assign()" function on "*/weights" in TF-Slim, it worked. However in Keras it failed on "*/kernel".

Is there any mistake in my usage? Or I can Simply use "*/kernel/Read/ReadVariable" in Keras as both "*/weight" and "*/weight/read" in TF-Slim?

Thank you!

**Comment by amahendrakar** [comment]
@summelon,
Could you please provide a sample code to reproduce the issue you are facing? Thanks!

**Comment by summelon** [comment]
@amahendrakar I'm sorry, the code is not open source.
Instead, let me clarify and simplify my question.

In TF-1.13.1, there are differences between "VariableV2" and "VarHandleOp" indeed.
This is the part which you can reproduce.
After created a ResNet_v1_50 by TF-Slim and Keras, you can get the weight variable, "*/weights"(...V2) and "*/kernel"(...Op) respectively.
Then, applying tf.compat.v1.assign(ref=variable.outputs[0], ...), it works on VariableV2 but VarHandlOp failed.

I'm confuing about this.
I would appreciate if you can provide any helpful solution.

**Comment by manisci** [comment]
@summelon Hi. I'm facing the same problem and after many days of trying solutions here and there, I still cannot merge a keras model and a tensorflow1 model and then train the whole thing. I even manually changed VarHandleOp in the keras nodes to VariableV2, but I'm still getting immutable tensors without _ref at the end. As you said there's also "ReadVariableOp". I was wondering if you've found a workaround for this. Thank you :)

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
