### ISSUE TITLE
Calling tf.keras.model.save twice fails

### ISSUE THREAD

**Issue by zmjjmz** [tensorflow/tensorflow#37845]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Debian 9
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: n/a
- TensorFlow installed from (source or
binary): binary
- TensorFlow version (use command below): `v2.1.0-rc2-17-ge5bf8de 2.1.0`
- Python version: 3.5.3
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from
source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**

As demonstrated in this [gist](https://gist.github.com/zmjjmz/ade6ecb5eaf011788b1da62db4413cad), calling `tf.keras.Model.save` twice on a Model object fails on the second call.

**Describe the expected behavior**

It uh, would work.

**Standalone code to reproduce the issue** 

This [gist](https://gist.github.com/zmjjmz/ade6ecb5eaf011788b1da62db4413cad)

Related to (I'm fairly certain) [this issue](https://github.com/tensorflow/tensorflow/issues/33085).

**Comment by ravikyram** [comment]
@zmjjmz 

Can you try with latest TF version(`!pip install tensorflow==2.2.0rc1`). I am not seeing nay issue with TF 2.2.0rc1. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/ed616015607be729cae5eaf2eb306478/untitled745.ipynb). Thanks!

**Comment by zmjjmz** [comment]
My test works on TF 2.2.0rc1, thanks!

**Comment by brookisme** [comment]
Are there workarounds in TF2.1.  I'm trying to train on AI-Platform which doesn't offer 2.2?

**Comment by brookisme** [comment]
> Are there workarounds in TF2.1? I'm trying to train on AI-Platform which doesn't offer 2.2

This came up for me using a `ModelCheckpoint` callback.  I just realized setting `save_weights_only=True` fixes the problem. Not perfect but at least it works!
