### ISSUE TITLE
Cannot import Tensorflow on Ubuntu VPS

### ISSUE THREAD

**Issue by imandhillon** [tensorflow/tensorflow#37848]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): conda install -c conda-forge tensorflow=1.10.0
- TensorFlow version: 1.10.0
- Python version: 3.5.4
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
When I try to import tensorflow on my vps, I get an undefined symbol error. I have tried reinstalling it, but that did not help. I am not sure what else to try or do. Does it maybe have something to do with a wheel?

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```$ python app.py
Traceback (most recent call last):
  File "app.py", line 7, in <module>
    from tensorflow import * # pylint: disable=unused-import
  File "/home/me/anaconda3/envs/audiogen/lib/python3.5/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/me/anaconda3/envs/audiogen/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/me/anaconda3/envs/audiogen/lib/python3.5/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/me/anaconda3/envs/audiogen/lib/python3.5/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: /home/iman/anaconda3/envs/audiogen/lib/python3.5/site-packages/google/protobuf/pyext/_message.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf10TextFormat17FieldValuePrinter9PrintBoolEb```

**Comment by mihaimaruseac** [comment]
Please try to use 1.15, 2.1 or 2.2. 1.10 is too old and we don't support it anymore.

**Comment by amahendrakar** [comment]
> Please try to use 1.15, 2.1 or 2.2. 1.10 is too old and we don't support it anymore.

@imandhillon,
Could you please check @mihaimaruseac's comment and let know if you're still facing the same issue? Thanks!

**Comment by amahendrakar** [comment]
@imandhillon,
Any updates regarding this issue? Thanks!
