### ISSUE TITLE
iOS example projects don't build with Swift file and bridging header

### ISSUE THREAD

**Issue by tonytallman** [tensorflow/tensorflow#37841]
Problem description
The iOS example apps don't build if you add a single Swift file and bridging header to the project. The error is "error: 'vector' file not found" in tensorflow/examples/ios/camera/ios_image_load.h:18:10.

Steps to reproduce
1. Download the TensorFlow repo and follow instructions to set up any/all of the iOS example projects.
2. Run an example app on your phone or simulator to verify that it works.
3. Add a single empty Swift file, File.swift, to the project and include a bridging header.
4. #import "ios_image_load.h" in the bridging header.
5. Build and observe build error 'vector' file not found.

**System information**
- MacOS Mojave
- Xcode 11.3.1
- TensorFlow installed from latest on GitHub

This is similar to https://github.com/tensorflow/tensorflow/issues/22051 but that issue was closed with a solution that does not apply to the iOS example apps.

**Comment by gadagashwini** [comment]
@tonytallman, 
Please Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks

**Comment by tonytallman** [comment]
@gadagashwini 
The tensorflow repository has example iOS apps at tensorflow/examples/ios. If you add a Swift file to any of the example apps then the example app won't build. This demonstrates a general problem with mixing tensorflow c++ and Swift. Using one of tensorflow's example apps just makes it easier to demonstrate the problem.

1. Download or clone tensorflow repository.
2. Follow the instructions at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/ios/README.md to build and run one of the three example apps.
3. Add a single empty Swift file, File.swift, to the example app project and include a bridging header.
4. Add the line #import "ios_image_load.h" in the bridging header to expose tensorflow to Swift.
5. Build and observe build error 'vector' file not found.

**Comment by tonytallman** [comment]
@jvishnuvardhan 
I'm pretty sure that the answer is to create an Objective-C wrapper around ios_image_load.h and put that wrapper into the bridging header. If you give me a couple of days I can provide a more detailed answer and maybe even submit a pull-request with a Swift sample using tensorflow c++ code.

**Comment by tonytallman** [comment]
I have confirmed that the solution is to create an Objective-C++ wrapper class with a header file that contains no c++, and code file that imports ios_image_load.h. Put the wrapper class' header file in the bridging header file. Now you can call the wrapper class from Swift.

WrapperClass.h:
----------------
@interface WrapperClass : NSObject
- (void)loadImage;
@end

WrapperClass.mm:
------------------
#import "WrapperClass.h"
#import "ios_image_load.h" 
@implementation WrapperClass
- (void)loadImage {
    std::vector<tensorflow::uint8> image_data = LoadImageFromFile(
      [image_path UTF8String], &image_width, &image_height, &image_channels);
}
@end

tf_simple_example-Bridging-Header.h:
--------------------------------------
#import "ImageLoader.h"

ImageLoaderSwift.swift:
------------------------
class ImageLoaderSwift {
    init() {
        ImageLoader().loadImage()
    }
}
