### ISSUE TITLE
tf.function retracing even with input_signature

### ISSUE THREAD

**Issue by MarisJon** [tensorflow/tensorflow#37858]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04.3 LTS
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: No
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 2.1
- **Python version**: 3.7
- **Bazel version (if compiling from source)**: None
- **GCC/Compiler version (if compiling from source)**: None
- **CUDA/cuDNN version**: 9.2
- **GPU model and memory**: GTX 1080 Ti
- **Exact command to reproduce**: Run the attached script

### Describe the problem
I made & saved a Keras model 
But it brought tf.function retracing even with input_signature when it was loaded

### Source code / logs

* log
WARNING:tensorflow:5 out of the last 5 calls to <function recreate_function.<locals>.restored_function_body at 0x7ff01c64e950> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings is likely due to passing python objects instead of tensors. Also, tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. Please refer to https://www.tensorflow.org/beta/tutorials/eager/tf_function#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for more details.

* Source code
I removed the code one by one to narrow down the root-cause, still having the retracing issue
I think that this should work.
To reproduce the issue, we need to do 2 steps as follows

1) Save a model
```
import os
import numpy as np
import tensorflow as tf

@tf.function(input_signature=[
    tf.TensorSpec([None, 15, 15], tf.uint16, name='curr'),
    tf.TensorSpec([None, 2, 15, 15], tf.uint16, name='refs'),
    tf.TensorSpec([None, 15, 15], tf.uint8, name='grades_image'),
    tf.TensorSpec([None, 15, 15], tf.uint8, name='alarms_image'),
])
def all_attributes(curr, refs, grades_image, alarms_image):
    return tf.ones(tf.shape(curr)[0], tf.float32)

def create_layer(tf_func, name=None, trainable=False):
    Return keras layer instance for given tensorflow function"""
    if name is None:
        name = getattr(tf_func, '__name__', 'unnamed') + '_layer'
    class NewLayer(tf.keras.layers.Layer):
        def call(self, inputs):
            return tf_func(*inputs)
    NewLayer.__name__ = name  
    layer_instance = NewLayer()
    layer_instance.trainable = trainable
    return layer_instance

class TestModel:
    Class for Selfi model for production"""
    def build(self, name='unnamed_model'):
        curr = tf.keras.Input(shape=(15, 15), dtype=tf.uint16, name='curr')
        refs = tf.keras.Input(shape=(2, 15, 15), dtype=tf.uint16, name='refs')
        grades_image = tf.keras.Input(shape=(15, 15), dtype=tf.uint8, name='grades_image')
        alarms_image = tf.keras.Input(shape=(15, 15), dtype=tf.uint8, name='alarms_image')
        inputs = [curr, refs, grades_image, alarms_image]
        all_atts_stacked = create_layer(all_attributes)(inputs)
        outputs = [all_atts_stacked]        
        m = tf.keras.Model(inputs=inputs, outputs=outputs, name=name)
        self._keras_model = m
        return self
    def save(self, out_path):
        model = self._keras_model
        model.save(out_path)
        return self

if __name__ == "__main__":
    m = TestModel().build(name='Attribute_Model')
    save_root_dir = './Models'
    save_path = os.path.join(save_root_dir, m.name)
    m.save(save_path) 
```

2) Load & try the saved model. Here the retracing issue happens
```
import numpy as np
from numpy import ndarray
from typing import Tuple, List
import tensorflow as tf
import time

gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    print(e)

model_path = "./Models"

def copy_to_aligned_data(input_arr: ndarray, align: int) -> ndarray:
    pixels = input_arr.size
    alignment = align
    dtype = input_arr.dtype
    nbytes = pixels * dtype.itemsize
    buf = np.empty(nbytes + alignment, dtype=np.uint8)
    start_index = -buf.ctypes.data % alignment
    out_array = buf[start_index:start_index + nbytes].view(dtype).reshape(input_arr.shape)
    out_array[:] = input_arr[:]
    return out_array

def create_inputs_for_supervised_model(img_shape, refs_shape) -> List:
    curr = np.random.randint(max_value_14bit, size=img_shape, dtype=np.uint16)
    refs = np.random.randint(max_value_14bit, size=refs_shape, dtype=np.uint16)
    grades_image = np.random.randint(max_value_8bit, size=img_shape, dtype=np.uint8)
    alarms_image = np.random.randint(2, size=img_shape, dtype=np.uint8)
    curr_align = copy_to_aligned_data(curr, 64)
    refs_align = copy_to_aligned_data(refs, 64)
    grades_image_align = copy_to_aligned_data(grades_image, 64)
    alarms_image_align = copy_to_aligned_data(alarms_image, 64)
    curr_tf = tf.convert_to_tensor(curr_align, curr_align.dtype)
    refs_tf = tf.convert_to_tensor(refs_align, refs_align.dtype)
    grades_tf = tf.convert_to_tensor(grades_image_align, grades_image_align.dtype)
    alarms_tf = tf.convert_to_tensor(alarms_image_align, alarms_image_align.dtype)
    return [curr_tf, refs_tf, grades_tf, alarms_tf]

model_orig = tf.keras.models.load_model(model_path, compile=False)

max_value_14bit = np.iinfo(np.uint16).max // 4
max_value_8bit = np.iinfo(np.uint8).max

defects_count = 20
img_shapee = (defects_count, 15, 15)
refs_shapee = (defects_count, 2, 15, 15)
inputs = create_inputs_for_supervised_model(img_shapee, refs_shapee)
output = model_orig(inputs)

loop = 10
for i in range(loop):
    defects_count = 10000 + i*100
    img_shapee = (defects_count, 15, 15)
    refs_shapee = (defects_count, 2, 15, 15)
    inputs = create_inputs_for_supervised_model(img_shapee, refs_shapee)
    start = time.time()
    output = model_orig(inputs)
    output.numpy()
    duration_ms = (time.time() - start)*1000  # / loop
```

**Comment by amahendrakar** [comment]
@MarisJon,
I tried to reproduce the issue, but I'm facing an error stating `ModuleNotFoundError: No module named 'amatdeep'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/2ecc32da7cbb4e4c245a879a6bdbb317/37858.ipynb#scrollTo=5v3is8k8CSgH).

Looks like the given code is incomplete. In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. 

Also, please add ``` (3 backticks) before and after your code to preserve the formatting. Thanks!

**Comment by MarisJon** [comment]
Hello
Thank you for the reply. I am sorry for this inconvenience. Please let me add more details below

How to reproduce the issue
1) Please remove "import amatdeep; amatdeep.start_tf()". And then, you will have a save model
2) Load & try the saved model using following code

'''
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    # Currently, memory growth needs to be the same across GPUs
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Memory growth must be set before GPUs have been initialized
    print(e)

model_path = "./Models"


def copy_to_aligned_data(input_arr: ndarray, align: int) -> ndarray:
    pixels = input_arr.size
    alignment = align
    dtype = input_arr.dtype
    nbytes = pixels * dtype.itemsize
    buf = np.empty(nbytes + alignment, dtype=np.uint8)
    start_index = -buf.ctypes.data % alignment
    out_array = buf[start_index:start_index + nbytes].view(dtype).reshape(input_arr.shape)
    out_array[:] = input_arr[:]
    return out_array


def create_inputs_for_supervised_model(img_shape, refs_shape) -> List:
    curr = np.random.randint(max_value_14bit, size=img_shape, dtype=np.uint16)
    refs = np.random.randint(max_value_14bit, size=refs_shape, dtype=np.uint16)
    grades_image = np.random.randint(max_value_8bit, size=img_shape, dtype=np.uint8)
    alarms_image = np.random.randint(2, size=img_shape, dtype=np.uint8)

    curr_align = copy_to_aligned_data(curr, 64)
    refs_align = copy_to_aligned_data(refs, 64)
    grades_image_align = copy_to_aligned_data(grades_image, 64)
    alarms_image_align = copy_to_aligned_data(alarms_image, 64)

    curr_tf = tf.convert_to_tensor(curr_align, curr_align.dtype)
    refs_tf = tf.convert_to_tensor(refs_align, refs_align.dtype)
    grades_tf = tf.convert_to_tensor(grades_image_align, grades_image_align.dtype)
    alarms_tf = tf.convert_to_tensor(alarms_image_align, alarms_image_align.dtype)
    # return [curr_align, refs_align, grades_image_align, alarms_image_align]
    return [curr_tf, refs_tf, grades_tf, alarms_tf]


model_orig = tf.keras.models.load_model(model_path, compile=False)
# model_orig.compile(loss='binary_crossentropy')


max_value_14bit = np.iinfo(np.uint16).max // 4
max_value_8bit = np.iinfo(np.uint8).max


defects_count = 20
img_shapee = (defects_count, 15, 15)
refs_shapee = (defects_count, 2, 15, 15)
inputs = create_inputs_for_supervised_model(img_shapee, refs_shapee)
output = model_orig(inputs)


##### time_inside
loop = 10
for i in range(loop):
    defects_count = 10000 + i*100
    img_shapee = (defects_count, 15, 15)
    refs_shapee = (defects_count, 2, 15, 15)
    inputs = create_inputs_for_supervised_model(img_shapee, refs_shapee)
    start = time.time()
    output = model_orig(inputs)
    output.numpy()
    # tf.keras.backend.clear_session()
    duration_ms = (time.time() - start)*1000  # / loop

    print("took [ms]: ", duration_ms)

print("number of elements = ", len(output.numpy()))
'''

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/b7254a6f0f6c597612fa57f350b55f45/37858.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/8dfc5eb16936865e723b72b4e0adaae5/37858-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by kkimdev** [comment]
Hi, an easy workaround is applying @tf.function outside of the model.

```python
@tf.function(input_signature=[
    tf.TensorSpec([None, 15, 15], tf.uint16, name='curr'),
    tf.TensorSpec([None, 2, 15, 15], tf.uint16, name='refs'),
    tf.TensorSpec([None, 15, 15], tf.uint8, name='grades_image'),
    tf.TensorSpec([None, 15, 15], tf.uint8, name='alarms_image'),
])
def model_orig_run(*inputs):
  return model_orig(inputs)

#...

output = model_orig_run(*inputs)
```

**Comment by MarisJon** [comment]
> Hi, an easy workaround is applying @tf.function outside of the model.
> 
> ```python
> @tf.function(input_signature=[
>     tf.TensorSpec([None, 15, 15], tf.uint16, name='curr'),
>     tf.TensorSpec([None, 2, 15, 15], tf.uint16, name='refs'),
>     tf.TensorSpec([None, 15, 15], tf.uint8, name='grades_image'),
>     tf.TensorSpec([None, 15, 15], tf.uint8, name='alarms_image'),
> ])
> def model_orig_run(*inputs):
>   return model_orig(inputs)
> 
> #...
> 
> output = model_orig_run(*inputs)
> ```

@kkimdev 
I agree. input_signature must be added when a model is loaded?

**Comment by kkimdev** [comment]
@k-w-w

**Comment by sachinprasadhs** [comment]
Was able to run your code without any Warnings for retracing in Tensorflow GPU 2.5, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/5c4875489c923dde215eb17366c441cf/37858.ipynb). Thanks!
