### ISSUE TITLE
tf.keras.losses.SparseCategoricalCrossentropy  Documentation Issue

### ISSUE THREAD

**Issue by UesugiErii** [tensorflow/tensorflow#37859]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/keras/losses/SparseCategoricalCrossentropy

### Clear description

On the third line of the second code box, origin probability is [.9, .05, .05], [.5, .89, .6], [.05, .01, .94], it should be [.9, .05, .05], [.05, .89, .06], [.05, .01, .94].

**Comment by ashutosh1919** [comment]
@UesugiErii , The example is removed in the [nightly version](https://www.tensorflow.org/api_docs/python/tf/keras/losses/SparseCategoricalCrossentropy?version=nightly). I think this will solve your issue.
