### ISSUE TITLE
freezing tensorflow model

### ISSUE THREAD

**Issue by DucLong06** [tensorflow/tensorflow#37860]
The model I use is meta graph and win 10 ver 1903
My model clone :
https://github.com/ZJULearning/pixel_link

I am trying to freeze a flow pattern

In tenorflow, training from scratch is created after 4 files:

1. model.ckpt-38055.data-00000-of-00001
2. model.ckpt-38055.index
3. model.ckpt-38055.meta
4. checkpoint

I would like to convert them (or only the needed ones) into one file  graph.pb

I use src :

> `import tensorflow as tf
> 
> meta_path = 'model.ckpt-38055.meta'  # Your .meta file
> 
> 
> config = tf.ConfigProto()
> 
> 
> with tf.Session(config=config) as sess:
> 
>     with tf.device("/cpu:0"): 
> 
>     # Restore the graph
>         saver = tf.train.import_meta_graph(meta_path)
> 
>         # Load weights
>         saver.restore(sess, tf.train.latest_checkpoint('./'))
>         # saver.restore(sess, "model.ckpt-38055")
> 
>         output_node_names = [n.name for n in tf.get_default_graph().as_graph_def().node]
>         # output_node_names = "reconstruction_layer"
> 
>         # Freeze the graph
>         frozen_graph_def = tf.graph_util.convert_variables_to_constants(
>             sess,
>             sess.graph_def,
>             output_node_names)
> 
>         # Save the frozen graph
>         with open('output_graph.pb', 'wb') as f:
>             f.write(frozen_graph_def.SerializeToString())`

 I encountered an error :

> 2020-03-24 15:00:30.107728: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Traceback (most recent call last):
  File "freeze_graph.py", line 5, in <module>
    sess, sess.graph_def, ["out"])
  File "C:\Users\Lerror\Anaconda3\lib\site-packages\tensorflow\python\framework\graph_util_impl.py", line 227, in convert_variables_to_constants
    inference_graph = extract_sub_graph(input_graph_def, output_node_names)
  File "C:\Users\Lerror\Anaconda3\lib\site-packages\tensorflow\python\framework\graph_util_impl.py", line 171, in extract_sub_graph
    _assert_nodes_are_present(name_to_node, dest_nodes)
  File "C:\Users\Lerror\Anaconda3\lib\site-packages\tensorflow\python\framework\graph_util_impl.py", line 131, in _assert_nodes_are_present
    assert d in name_to_node, "%s is not in graph" % d
AssertionError: out is not in graph

Hope you can help me

thank you

**Comment by Saduf2019** [comment]
@DucLong06 
please update tensorflow version and simple stand alone code for us to replicate the issue faced.
As per error please refer to similar [issues](https://github.com/tensorflow/tensorflow/issues/19455), [link1](https://github.com/tensorflow/tensorflow/issues/15783) , [link2](https://github.com/tensorflow/tensorflow/issues/15426) [link3](https://github.com/tensorflow/tensorflow/issues/16293)

#37139 #35703

**Comment by DucLong06** [comment]
Hi @Saduf2019 
I think I have to downgrade tensorflow version ?
So can you tell me which version is appropriate ?

**Comment by Saduf2019** [comment]
@DucLong06
please update tensorflow version and simple stand alone code for us to replicate the issue faced.

**Comment by DucLong06** [comment]
I tried versions> 1.1 <1.8 and encountered the same error

**Comment by Saduf2019** [comment]
@DucLong06 
please confirm if you faced the error with 1.15, if you haven tried please try and let us know

**Comment by Saduf2019** [comment]
@DucLong06 
please update on the above comment

**Comment by Saduf2019** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
