### ISSUE TITLE
Build tensorflow for  c++

### ISSUE THREAD

**Issue by xav12358** [tensorflow/tensorflow#37869]
Hello,

I try to build tensorflow for cpp API. I use a docker to compile and generate a package.

Here is the docker : 
```
`
FROM tensorflow/tensorflow

RUN apt-get install -y git
RUN DEBIAN_FRONTEND=noninteractive  apt-get install -y tzdata 

# Install object detection api dependencies
RUN apt-get install -y protobuf-compiler python-pil python-lxml python-tk zip unzip && \
    pip install Cython && \
    pip install contextlib2 && \
    pip install jupyter && \
    pip install matplotlib 

# Get tensorflow source
RUN cd /home/xxxx && git clone https://github.com/tensorflow/tensorflow

# Install bazel
RUN apt install curl 
RUN curl https://bazel.build/bazel-release.pub.gpg | apt-key add -
RUN echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" |  tee /etc/apt/sources.list.d/bazel.list
RUN apt update && apt install -y  bazel && apt install -y  bazel-1.0.0
RUN apt install bazel-2.0.0
RUN pip install future

RUN cd /home/xxxx/tensorflow/ && /home/xxxx/tensorflow/ && bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both //tensorflow:libtensorflow_cc.so \
                //tensorflow:libtensorflow_framework.so \
                //tensorflow:install_headers

`

```
I try with and without HW optimisation:
Without:
```
bazel build -c opt //tensorflow:libtensorflow_cc.so \
                //tensorflow:libtensorflow_framework.so \
                //tensorflow:install_headers

```

With:
```
bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both //tensorflow:libtensorflow_cc.so \
                //tensorflow:libtensorflow_framework.so \
                //tensorflow:install_headers"
```

When I use the optimize or the standard package the execution time is the same. 
When I use the optimize version the following message dissapear:   

```
2020-03-24 `14:48:16.411418: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA

```
The message dissapears but the excecution time is equivalent ~200ms.

**Comment by mihaimaruseac** [comment]
That message is just an information log, not an error, does not have any effect.

**Comment by gadagashwini** [comment]
@xav12358, as @mihaimaruseac mentioned that message is just an information log its not an error. Can we close this issue. Thanks

**Comment by gadagashwini** [comment]
@xav12358, Please update for the above comment. Thanks

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by JaosonMa** [comment]
> That message is just an information log, not an error, does not have any effect.

c++  windows tensorflow.dll (1.8) 
it can run succ on release, but on debug model , it can not run succ
[https://github.com/fo40225/tensorflow-windows-wheel/issues/145](url)

can you tell me how to solve this when on debug model?
