### ISSUE TITLE
Migrate TF1 to TF2

### ISSUE THREAD

**Issue by Khanifsaleh** [tensorflow/tensorflow#37865]
Hi, Im newbie on tensorflow. 
How to use embedding_rnn_seq2seq on tensorflow v2? On tensorflow v1, it is in contrib.legacy_seq2seq class.

**Comment by gadagashwini** [comment]
@Khanifsaleh,
Follow the instructions mentioned in the [Tensorflow](https://www.tensorflow.org/guide/migrate) guide to migrate from tf1 to tf2

**Comment by Khanifsaleh** [comment]
Yes, I have read the documentation. I have tried implementing tf_upgrade_v2, but the tf.contrib.legcy_seq2seq.embedding_rnn_seq2seq has not changed. I also read [contrib_sunset](https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md) which states that legacy_seq2seq was replaced by seq2seq on the tensorflow_addons module. But that doesn't work, it works for the sequence_loss method which is in v1, that method is in the same module as embedding_rnn_seq2seq.

**Comment by ymodak** [comment]
See basic decoder and encoder [example](https://www.tensorflow.org/addons/api_docs/python/tfa/seq2seq) usages for TF1 and TF2
Also see [tfa.seq2seq](https://www.tensorflow.org/addons/api_docs/python/tfa/seq2seq) module.
You may also try this question on [tensorflow/addons](https://github.com/tensorflow/addons/issues) repo.  Thanks!

**Comment by ammeitzler** [comment]
was this figured out? I am stuck on same problem

**Comment by Khanifsaleh** [comment]
@ammeitzler not yet. I give up.

**Comment by ammeitzler** [comment]
lol ugh. im trying still
