### ISSUE TITLE
Learning Rate scheduler with custom training using "tf.GradientTape"

### ISSUE THREAD

**Issue by arjun-majumdar** [tensorflow/tensorflow#37862]
Hello, I am using a learning rate scheduler to reduce the learning rate which is defined in the function as follows:

```
def scheduler(epoch):
    learning_rate = 0.0012
    if epoch >= 9 and epoch == 19:
        return learning_rate / 10
    elif epoch > 19:
        return learning_rate / 100
    else:
        return learning_rate
```

How can I use this defined scheduler() function with custom training loop using "tf.GradientTape"?

The way I know is to use the scheduler as a callback:

```
callback = tf.keras.callbacks.LearningRateScheduler(scheduler)

model.fit(
	x = data, y = labels,
	epochs=100, callbacks=[callback],
	validation_data=(val_data, val_labels))

```

Thanks

**Comment by pandrey-fr** [comment]
Hi,

In TF 2.1, I would advise you to write your custom learning rate scheduler as a `tf.keras.optimizers.schedules.LearningRateSchedule` instance and pass it as `learning_rate` argument to your model's optimizer - this way you do not have to worry about it further.

In TF 2.2 (currently in RC1), this issue will be fixed by implementing a `tf.keras.Model` subclass and overriding its `train_step` method - this way you can still use `model.fit` and pass callbacks, although you are using a custom train step behaviour.

In your specific case, a hack can be to call `model.fit` multiple times, specifying both `epochs` and `initial_epoch` to ensure continuity, and changing manually the learning rate of `model.optimizer` in-between.

I hope this helps :)

**Comment by arjun-majumdar** [comment]
If I use the following code:

```
boundaries = [9, 19]
values = [0.1, 0.01, 0.001]

learning_rate_fn = tf.keras.optimizers.schedules.PiecewiseConstantDecay(boundaries, values)
optimizer = tf.keras.optimizers.SGD(learning_rate=learning_rate_fn)

```
And then during training using "tf.GradientTape", if I want to get the current learning rate being used by the optimizer, I am using the following code:

`optimizer.learning_rate.numpy()`

which throws the error:
AttributeError: 'PiecewiseConstantDecay' object has no attribute 'numpy'

How can I get the current learning rate used by the optimizer?

Thanks!

**Comment by pandrey-fr** [comment]
Here, `optimizer.learning_rate` it the `PiecewiseConstantDecay` you instantiated, thus to get its value at a given step, you should call it with the step number - _e.g._ to know the value at step 1000, `optimizer.learning_rate(1000)`. Note that you can gather the current step value from the optimizer itself: `optimizer.iterations`; thus you can run `optimizer.learning_rate(optimizer.iterations)`.

Note that this is only valid when the learning rate is indeed a Scheduler instance :)

**Comment by arjun-majumdar** [comment]
Thanks!

**Comment by pandrey-fr** [comment]
You are welcome!

**Comment by paolorota** [comment]
> tf.keras.optimizers.schedules.LearningRateSchedule

and how would I do that? The documentation is pretty empty:
https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/schedules/LearningRateSchedule

**Comment by AlbinDavid** [comment]
I'm trying to run this line optimizer.learning_rate(optimizer.iterations) but it is not  callable

**Comment by peachthiefmedia** [comment]
You can call `optimizer._decayed_lr(tf.float32)` which should return the current learning rate

**Comment by ziweiyang** [comment]
Hi there,
I have a question seems like related to this thread.

I have a custom model (not keras model) and a custom training loop. I wish to use self-defined lr-schedule function to manually change the `lr` based on the current step, and under the distribute strategy as well... I google everywhere and could not find answer. If some one has worked on similar situation before, much more than appreciated to listen how to deal with!
