### ISSUE TITLE
Debundled protobuf broken

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#37861]
**System information** 
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.0.0 but most likely all affected
- Bazel version (if compiling from source): 0.26.1

**Describe the current behavior**

Using TF_SYSTEM_LIBS=com_google_protobuf leads to 

> In file included from bazel-out/k8-opt/bin/tensorflow/compiler/xla/xla_data.pb.cc:4:
bazel-out/k8-opt/bin/tensorflow/compiler/xla/xla_data.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory
 #include <google/protobuf/port_def.inc>

Full compiler invocation:

> /sw/installed/OpenMPI/3.1.3-GCC-8.2.0-2.31.1/bin/mpicc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/tensorflow/compiler/xla/_objs/xla_data_proto/xla_data.pb.pic.d '-frandom-seed=bazel-out/k8-opt/bin/tensorflow/compiler/xla/_objs/xla_data_proto/xla_data.pb.pic.o' -fPIC -iquote . -iquote bazel-out/k8-opt/bin -iquote external/com_google_protobuf -iquote bazel-out/k8-opt/bin/external/com_google_protobuf -O2 -ftree-vectorize '-march=native' -fno-math-errno -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c bazel-out/k8-opt/bin/tensorflow/compiler/xla/xla_data.pb.cc -o bazel-out/k8-opt/bin/tensorflow/compiler/xla/_objs/xla_data_proto/xla_data.pb.pic.o

**Describe the expected behavior**

Using TF_SYSTEM_LIBS=com_google_protobuf works

**Standalone code to reproduce the issue** 
Configure with  TF_SYSTEM_LIBS=com_google_protobuf then build

**Other info / logs**
There are 2 issues with that:

1. E.g. for 2.0.0 the directory containing the symlinked headers is passed as `-iquote bazel-out/k8-opt/bin/external/com_google_protobuf` but incuded with ` #include <google/protobuf/port_def.inc>` which by definition of `-iquote` will not be found
2. After manually changing the `-iquote` to `-I` it shows that not all headers are copied. The list for 2.0.0 is at https://github.com/tensorflow/tensorflow/blob/v2.0.0/third_party/systemlibs/protobuf.BUILD#L15-L43 and is missing `port_undef.inc` hence the command fails with 
> In file included from bazel-out/k8-opt/bin/tensorflow/compiler/xla/xla_data.pb.cc:4:
bazel-out/k8-opt/bin/tensorflow/compiler/xla/xla_data.pb.h:22:10: fatal error: google/protobuf/port_undef.inc: No such file or directory
 #include <google/protobuf/port_undef.inc>

A possible solution was suggested in https://github.com/tensorflow/tensorflow/issues/37835: Allow usage of explicit prefixes and do NOT try to copy/symlink headers (or at least test that)

**Comment by mihaimaruseac** [comment]
Sorry for the accidental locking

**Comment by gunan** [comment]
@perfinion PTAL

**Comment by Flamefire** [comment]
@perfinion As you introduced that debundled protobuf in https://github.com/tensorflow/tensorflow/pull/24004:

Any reason for copying the headers at all? Could we simply not do that which avoids the problem of incomplete list of headers and include style.

**Comment by Flamefire** [comment]
FTR:
- Replacing `exec_tools` by  `tools` solves the include issue: #43156
- Symlinking the `*.proto` files only solves the include issue (most symlinked includes weren't used anyway): #43153

With those 2 PRs I can build TF with custom protobuf

**Comment by Saduf2019** [comment]
@Flamefire 
As we have the latest stable version 2.6.0, Can you try building TF 2.6.0 and let us know if the issue still persists?

**Comment by Flamefire** [comment]
Yes fixed after the mentioned PRs have been merged

**Comment by njzjz** [comment]
> > fatal error: google/protobuf/port_undef.inc: No such file or directory
> > #include <google/protobuf/port_undef.inc>
> 

I got this error again in v2.12.0.

**Comment by mihaimaruseac** [comment]
Please open a new issue, it seems some copybara rule has been mistaken. Please mention the file where the error shows up from.
