### ISSUE TITLE
tables_initializer

### ISSUE THREAD

**Issue by tianhongbao** [tensorflow/tensorflow#37867]
`sess_id.run(graph_id.get_operation_by_name("MyGraphID/init_all_tables")) `

I did not find a way to achieve this in C ++. what should I do？

**Comment by ravikyram** [comment]
@tianhongbao 

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by ravikyram** [comment]
I am closing the issue as this issue not related to bug/performance.Please, ask this question in StackOverflow. Thanks!
