### ISSUE TITLE
Issue installing.

### ISSUE THREAD

**Issue by chasep255** [tensorflow/tensorflow#3786]
I get the following error when I try to build the latest tensorflow from source.  I am on Ubuntu 16.04.  I am using GCC 5.4 with CUDA 8.0 RC (GCC 5.4 patch installed).

> external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/CUDA/PacketMathHalf.h(279): error: identifier "h2log1p" is undefined
> 
> 1 error detected in the compilation of "/tmp/tmpxft_00007e16_00000000-7_depthtospace_op_gpu.cu.cpp1.ii".
> Target //tensorflow/tools/pip_package:build_pip_package failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> INFO: Elapsed time: 270.294s, Critical Path: 152.97s

**Comment by Mazecreator** [comment]
I have been seeing the same problem with CUDA enabled on the latest build.  I have disabled CUDA to compile the latest code base.

**Comment by ashleyjsands** [comment]
I have the same problem except I'm using gcc 4.9 on Ubuntu 16.04 with CUDA 8.0 RC.

**Comment by fayeshine** [comment]
#3788 same here

**Comment by geoffreysteven** [comment]
I have the same problem, using cuDNN 5.1 and CUDA 8.0. The error is here:
Eigen/src/Core/arch/CUDA/PacketMathHalf.h(279)

**Comment by Brennan-VanderLaan** [comment]
Hitting the same issue on 16.04, using CUDA 8.0RC with the 5.4 patch installed. Using cuDNN 5.0
I'm trying to build against compute version 6.1

The header template looks like this:

`#if defined __CUDACC_VER__ && __CUDACC_VER__ >= 80000 && defined __CUDA_ARCH__ && __CUDA_ARCH__ >= 530

...

template<>  EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE
half2 plog1p<half2>(const half2& a) {
  return h2log1p(a);
}

...

`

On the previous versions it would default to

`
template<> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE half2 plog1p<half2>(const half2& a) {
  float a1 = __low2float(a);
  float a2 = __high2float(a);
  float r1 = log1pf(a1);
  float r2 = log1pf(a2);
  return __floats2half2_rn(r1, r2);
}

`

I was able to build against 5.2 without issue

**Comment by ast0414** [comment]
I have faced with the same error of:
`external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/CUDA/PacketMathHalf.h(279): error: identifier "h2log1p" is undefined`

GTX 1080 with NVIDIA Driver 367.35, CUDA 8.0rc, CuDNN 5.1 and the current master branch of TF.

**Comment by Brennan-VanderLaan** [comment]
@ast0414 What compute version are you building against? I had no issues with 5.2, but 6.1 isn't building for me.

**Comment by geoffreysteven** [comment]
FYI - I noticed on the MNIST model / convultional.py in tensorflow, if you run it on a Pascal chip set (ie 1080) and are using the v4 of cuDNN with the tensorflow GPU Linux binary, the resulting model is incorrect (90% testing error). Should be checked once the compile issue is resolved.

**Comment by Brennan-VanderLaan** [comment]
With v5 of cuDNN with a Titan X Pascal (compiled targeting compute version 5.2) I got the following on the MNIST model:

```
Run #1
Step 8500 (epoch 9.89), 4.1 ms
Minibatch loss: 1.604, learning rate: 0.006302
Minibatch error: 0.0%
Validation error: 0.9%
Test error: 0.8%

Run #2
Step 8500 (epoch 9.89), 4.2 ms
Minibatch loss: 1.595, learning rate: 0.006302
Minibatch error: 0.0%
Validation error: 0.8%
Test error: 0.8%
```

**Comment by wurrego** [comment]
Same error, same setup: Ubuntu 16.04, gcc 5.4, GTX 1080 - 367.35,  CUDA 8.0.27, CuDNN 5, and current master of TF.   capability v6.1

Searching for h2log1p reveals it isn't there ..
 grep -rnw /path/to/cuda/include -e "h2log1p"

but in /path/to/cuda/include/cuda_fp16.h you can find the declarations for h2log ... which is why the declare statement in PacketMathHalf.h was probably added 
#if defined __CUDACC_VER__ && __CUDACC_VER__ >= 80000 && defined __CUDA_ARCH__ && __CUDA_ARCH__ >= 530.

I tried the following with no success...
1. In my bazel cache of PacketMathHalf.h, I copied the implementation of half2 plog1p<half2>(const half2& a) from after the declare (#else)
2. comment out   return h2log1p(a);
3. paste in what you copied, which should be:
  float a1 = __low2float(a);
  float a2 = __high2float(a);
  float r1 = log1pf(a1);
  float r2 = log1pf(a2);
  return __floats2half2_rn(r1, r2);
4. rebuild
5. Everything compiled without error
6. but when i run python and import tensorflow it I can an import error from pywrap_tensorflow, which i believe it is attempting to link against cuda 7.5 :\

**Comment by ast0414** [comment]
@Brennan-VanderLaan Sorry for the late response. I set the computing capability as 6.1 and there was no error when I built on r0.10 branch while I failed to build on the master branch

**Comment by fayeshine** [comment]
@wurrego is it possible to make your workaround to a Pull Request on the master branch

**Comment by vrv** [comment]
@ibab @benoitsteiner can you guys look at this?

**Comment by ibab** [comment]
@vrv Seems like this one is my fault.
When I was testing the changes, that section was never compiled since I wasn't using CUDA 8.

The right solution is to take the function out of the if/else macro and use the fallback version.

**Comment by lerynth** [comment]
@wurrego thank you so much. After many days trying, tried your solution and it works like a charm.

**Comment by fayeshine** [comment]
@ibab ,thanks. If this has been fixed, please update me :smile:

**Comment by ibab** [comment]
@fayeshine 
The fix has now been merged into TensorFlow.
Can someone verify that the compile error is gone with the newest commit on `master`?

**Comment by el3ment** [comment]
I just tried it, and the error is still there, but h2log1p is not present in any PacketMathHalf.h files on my machine (i.e the result of `cat $(locate 'PacketMathHalf') | grep 'h2log1p'` is empty)

```
INFO: From Compiling tensorflow/core/kernels/batchtospace_op_gpu.cu.cc:
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/CUDA/PacketMathHalf.h(279): error: identifier "h2log1p" is undefined

1 error detected in the compilation of "/tmp/tmpxft_000046de_00000000-10_batchtospace_op_gpu.cu.compute_61.cpp1.ii".
ERROR: /mnt/pccfs/downloads/tensorflow/tensorflow/core/kernels/BUILD:1509:1: output 'tensorflow/core/kernels/_objs/batchtospace_op_gpu/tensorflow/core/kernels/batchtospace_op_gpu.cu.pic.o' was not created.
ERROR: /mnt/pccfs/downloads/tensorflow/tensorflow/core/kernels/BUILD:1509:1: not all outputs were created.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 89.445s, Critical Path: 33.07s
```

**Comment by ibab** [comment]
Can you try running `bazel clean --expunge` to get rid of the cached packages?

**Comment by Mazecreator** [comment]
This issue has been fixed for me at the latest head:
https://github.com/tensorflow/tensorflow/commit/39513573b40b61417ef859bdd8c6578d61e4312d

Versions installed:
CUDA 8.0
cuDNN 5.0
Ubuntu 16.04
GTX 1080
Nvidia Driver 367.35.0

**Comment by vrv** [comment]
Yay!

**Comment by fayeshine** [comment]
@ibab have you made the pull request

**Comment by suiyuan2009** [comment]
seems ok now.

**Comment by ibab** [comment]
@fayeshine: Yes, it's #3831.
