### ISSUE TITLE
Allow tf.image.random_crop to return multiple crops

### ISSUE THREAD

**Issue by lminer** [tensorflow/tensorflow#37874]
It would be nice if there was an option for `tf.image.random_crop` to return more than a single crop at a time.

It's possible to reproduce this logic through something like the code below, but I find that it is bottlenecking my tf.data pipeline, and I have to use `tf.image.extract_patches` instead.

```
@tf.function
def get_patches(image, num_patches=100, patch_size=16):
    patches = []
    for i in range(num_patches):
        patch = tf.image.random_crop(image, [patch_size, patch_size, 3])
        patches.append(patch)

    return tf.stack(patches)
```

**Comment by maxkaustav** [comment]
OK I WILL LOOK FOR THAT

**Comment by rmothukuru** [comment]
@lminer,
Sorry for the delayed response. As per [this comment](https://github.com/tensorflow/tensorflow/pull/37952#pullrequestreview-382996086), this functionality can be achieved by vectorizing **`tf.vectorized_map`**. Thanks!
