### ISSUE TITLE
After training the model using keras, tensorflow1.15 performs Post-training integer quantization, but the MCU prediction results are inconsistent with tflite output

### ISSUE THREAD

**Issue by Fengzhijjin** [tensorflow/tensorflow#37886]
@tensorflow/micro
**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary):  conda install tensorflow=1.15
- Tensorflow version (commit SHA if source): 1.15.0
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Arm-cortex M4

**Describe the problem**
My English level is not very good, thank you very much for your help.
I want to complete a voice wake-up MCU, after training the model using keras, tensorflow1.15 performs Post-training integer quantization, but the MCU prediction results are inconsistent with tflite output.
When I run tflite tests using tensorflow, the output is correct, but the MCU output is wrong.
Same model input, tflite goes through the first layer depth_wise output：
![41585108178_ pic](https://user-images.githubusercontent.com/27952292/77500064-e3886680-6e8e-11ea-8b75-72218b61b898.jpg)
Same model input, mcu goes through the first layer depth_wise output：
![51585108202_ pic](https://user-images.githubusercontent.com/27952292/77500142-221e2100-6e8f-11ea-8c65-e9685d505ec4.jpg)

**Please provide the exact sequence of commands/steps when you ran into the problem**
1. Convert to a TensorFlow Lite model
```
def conver_tflite_int8():
    converter = tf.lite.TFLiteConverter.from_keras_model_file("./dscnn_dense_model_depthwise/checkpoint-03e-loss_0.029.hdf5")
    converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    train_data = read_data()
    def representative_dataset_gen():
        for input_value in train_data:
            yield [input_value]
    converter.representative_dataset = tf.lite.RepresentativeDataset(representative_dataset_gen)
    tflite_model_quant = converter.convert()
    with open("./converted_model_float_dense_depthwise.tflite", "wb") as wb:
        wb.write(tflite_model_quant)
```
2. Load tflite prediction
```
def load_int_perlayer():
    txts = glob.glob("./first_test*.txt")

    interpreter_quant = tf.lite.Interpreter(model_path=str("./converted_model_int8_dense_depthwise.tflite"))
    interpreter_quant.allocate_tensors()
    tensor_list = interpreter_quant.get_tensor_details()
    for i in tensor_list:
        print(i)

    datas = []
    for i in txts:
        data = []
        with open(i, 'r') as tr:
            lines = tr.readlines()
            for j in lines:
                data.append([float(z) for z in j[:-1].split(' ')])
        datas.append(data)
    datas = np.array(datas)
    data_min = -248.
    data_max = 38.

    for i in tqdm(range(len(datas))):
        with open('./layer_out/mfcc_float.csv', 'w') as wc:
            for j in datas[i].reshape((74, 10)):
                wc.write(str(j) + '\n')
        data = (((datas[i].reshape((1, 74, 10, 1)) + 105) / 143) * 127.).astype(np.int8)
        with open('./layer_out/mfcc_int.csv', 'w') as wc:
            for j in data.reshape((74, 10)):
                wc.write(str(j) + '\n')

        input_index = interpreter_quant.get_input_details()[0]["index"]
        output_index = interpreter_quant.get_output_details()[0]["index"]
        interpreter_quant.set_tensor(input_index, data.reshape((1, 74, 10, 1)))
        interpreter_quant.invoke()
        predictions = interpreter_quant.get_tensor(output_index)
        print(predictions[0])
```
3. Convert to a C array
```
xxd -i ./converted_model_int8_dense_depthwise.tflite > model.cc
```
model.cc screenshot
![61585108480_ pic](https://user-images.githubusercontent.com/27952292/77500247-77f2c900-6e8f-11ea-8e53-185d971527b3.jpg)

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
