### ISSUE TITLE
tf.tpu.experimental.initialize_tpu_system raises GRPC error

### ISSUE THREAD

**Issue by fwatty-1218** [tensorflow/tensorflow#37881]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): No
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: NA
- TensorFlow installed from (source or
binary): using google colab
- TensorFlow version (use command below): 
- Python version: - Bazel
version (if compiling from source): 3.6

**Describe the current behavior**
When I try to setting TPU system in google colab in tensorflow 2.0.0, tf.tpu.experimental.initialize_tpu_system raises GRPC error. 
It worked normally until about 12 hours ago and I don't change any codes.
What I try to do to solve this problem?

**Standalone code to reproduce the issue** 
https://gist.github.com/fwatty-1218/48d4f1be7b66245321376c4e2af3352a

**Any other info / logs**
If I use tensorflow 2.1.0, it works fine, but I want to use tensorflow 2.0.0 because I want to use TPU.

**Comment by Saduf2019** [comment]
@fwatty-1218 
i have run the code shared in your gist on same version and tpu but face a different error,please find the gist [here](https://colab.sandbox.google.com/gist/Saduf2019/6f9a9a21af272bb3974dcb44a9592a0b/37881.ipynb)

**Comment by fwatty-1218** [comment]
Looking at the gist, the process leading up to the error is the same, so the cause of the error may be due to the assigned TPU device?

**Comment by jvishnuvardhan** [comment]
@fwatty-1218 I ran your code with `TF2.2rc2` version and I cannot reproduce the error. Can you please try `TF2.2rc2` version and let us know whether the issue resolved for you or not.

Please close the issue if the issue was resolved for you. Thanks!

**Comment by fwatty-1218** [comment]
Thanks for solving my problem!
