### ISSUE TITLE
tf.keras.layers.conv*d is slow compared to tf.nn.conv*d

### ISSUE THREAD

**Issue by KoykL** [tensorflow/tensorflow#37883]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes
- OS Platform and Distribution : Arch Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: N/A
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 
- Python version: - Bazel
version (if compiling from source): 3.8.0
- GCC/Compiler version (if compiling from
source): 9.3.0
- CUDA/cuDNN version: - GPU model and memory:
10.2/7.6.5

**Describe the current behavior**
I initially discovered this issue last year. I switched to pytorch as a solution for that project. However, it seems the issue still exists on the master branch of tensorflow as of today. I will try to remember as much detail as I can based on my investigation last year.

tf.keras.layers.conv\*d calls nn_ops.Convolution to perform the convolution. However, nn_ops.Convolution is inefficient for dilated convolution, since it uses _WithSpaceToBatch to handle dilation. space_to_batch allocates and copies the memory. (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/spacetobatch_functor.cc https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/spacetobatch_functor_gpu.cu.cc)  The performance issue is more severe for conv3d, since 3d volumes can be huge.  

After space_to_batch, nn_ops.Convolution then calls _NonAtrousConvolution, which calls gen_nn_ops.conv\*d for the actual convolution. Then batch_to_space is called to restore shape.

On the contrary, tf.nn.conv\*d directly calls gen_nn_ops.conv\*d for dilated convolution, which I guess calls the corresponding cudnn dilated convolution routines. It's efficient and fast.

**Describe the expected behavior**
nn_ops.Convolution should directly call gen_nn_ops.conv\*d for dilated convolution. It seems _WithSpaceToBatch is not necessary. cudnn supports dilated convolutions. Switching to gen_nn_ops.conv\*d can improve the performance with little efforts.

Maybe this change can also potentially fix #23101?

**Standalone code to reproduce the issue** 

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Thank you so much for the help!

**Comment by amahendrakar** [comment]
@KoykL,
In order to expedite the trouble-shooting process, could you please provide a minimal code sample to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by amahendrakar** [comment]
> @KoykL,
> In order to expedite the trouble-shooting process, could you please provide a minimal code sample to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

Any updates regarding this issue? Thanks!

**Comment by KoykL** [comment]
I don't have the environment to reproduce the issue with me. Closed for now. Sorry for that.
