### ISSUE TITLE
Converting unsupported operation: PyFunc

### ISSUE THREAD

**Issue by taoja12** [tensorflow/tensorflow#37892]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
pycharm
- TensorFlow version (or github SHA if from source):
tensorflow 1.15.0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.
This is my code.
import tensorflow as tf

path = 'vgg_freeze_model.pb'
inputs = ["Placeholder"]
input_shapes = {"Placeholder": [1, 224, 224, 3]}
outputs = ["vgg_16/cls_prob"]

converter = tf.lite.TFLiteConverter.from_frozen_graph(path, inputs, outputs, input_shapes=input_shapes)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
converter.post_training_quantize = True
tflite_model = converter.convert()
open("vgg16.tflite", "wb").write(tflite_model)

```
# Copy and paste here the exact command
```

**The output from the converter invocation**

```
# Copy and paste the output here.
```
This is my issue
2020-03-25 03:36:10.513606: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: PyFunc
2020-03-25 03:36:10.513648: F tensorflow/lite/toco/import_tensorflow.cc:114] Check failed: attr.value_case() == AttrValue::kType (1 vs. 6)

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@taoja12,
Could you please share the `vgg_freeze_model.pb` file you are using in the code? Thanks!

**Comment by taoja12** [comment]
@amahendrakar    https://pan.baidu.com/s/1UyqLfwA6TkUWXcB-69HupA    retrieve password: u6ay

**Comment by amahendrakar** [comment]
@taoja12,
I am unable to access the above link. Could you please upload the file in another alternate website? Thanks!

**Comment by amahendrakar** [comment]
> @taoja12,
> I am unable to access the above link. Could you please upload the file on another alternate website? Thanks!

Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by uchihaltachi** [comment]
Now I have the same problem. How did you solve it，please

**Comment by amahendrakar** [comment]
@uchihaltachi,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by Mayur28** [comment]
I have the same issues as well, any solution?
