### ISSUE TITLE
tflite | Build using Intel C++ compiler (Windows)

### ISSUE THREAD

**Issue by Lotte1990** [tensorflow/tensorflow#37899]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 2.2.0-rc1

Is it possible to build the TensorFlow Lite DLL for Windows 10 using the Intel C++ compiler? Would I need to create a new crosstool? Most info I found online is about Linux or building the pip wheel.

Linux: https://groups.google.com/forum/#!searchin/bazel-discuss/Use$20or$20support$20Intel$20compiler$20in$20Bazel/bazel-discuss/t-ruQRMis8A/gzF9PWY_AQAJ
Pip wheel: https://software.intel.com/en-us/articles/intel-optimization-for-tensorflow-installation-guide

It would be great if someone could point me in the right direction. Thanks!

**Comment by theadityasam** [comment]
Refer https://docs.bazel.build/versions/master/windows.html#using-bazel-on-windows-1
I guess a possible approach would be to set `BAZEL_VC` or `BAZEL_VS` environment variables to the location of the `icc` installation.

**Comment by ausk** [comment]
There is a script "lite\tools\make\build_lib.sh" to build on linux. I run it and redict the log into a file. Then analysis and write the dependencies of `libtensorflow-lite.a` into `CMakeLists.txt`， build using CMake。

**Comment by terryheo** [comment]
It seems that this is mostly answered.
https://www.tensorflow.org/install/source_windows is basic requirement for Windows build.
Once you have Bazel and compiler setup for your own, you can just build tflite with
```
bazel build //tensorflow/lite:libtensorflowlite.so
```

**Comment by Tomhouxin** [comment]
@ausk Hello! You are to write their own CmakeList?
