### ISSUE TITLE
ERROR: An error occurred during the fetch of repository 'com_google_protobuf' 

### ISSUE THREAD

**Issue by AshiakerWang** [tensorflow/tensorflow#37897]
**The following is my configuration:**

**System information** : Windows 10 Professional
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  No
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Windows 10 Professional
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: N/A
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below):  pip install tensorflow
- Python version:  N/A
- Bazel version (if compiling from source): 0.27.1
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version:  V10.0/v7.6.1
- GPU model and memory: GeForce 1050 Ti

While running the code cloneed from [URL](https://github.com/tensorflow/federated/tree/master/tensorflow_federated/python/research/gans/experiments/emnist) with 
`bazel run run_experiments`
, I encountered the following issue:

![image](https://user-images.githubusercontent.com/14258909/77538982-91b9fd80-6edb-11ea-8345-1ef2b5f91f1d.png)

The masked information is my user name.
Could yout please give me some adcvices?

**Comment by theadityasam** [comment]
Hey @AshiakerWang 
Do you have protoc installed? 
If not, try installing one of their precompiled binaries for your system-[link](https://github.com/protocolbuffers/protobuf/releases/)
Else, you can build it with vcpkg
```
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
.\bootstrap-vcpkg.bat
.\vcpkg integrate install 
vcpkg install protobuf protobuf:x64-windows
vcpkg install protobuf
```
Then try running your bazel script.

**Comment by AshiakerWang** [comment]
@theadityasam Thank for your reply !
The output of  `pip show protobuf` is 
`Name: protobuf
Version: 3.11.3
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
License: 3-Clause BSD License
Location: d:\conda\envs\tensorflow\lib\site-packages
Requires: setuptools, six
Required-by: tensorflow, tensorboard` 

I supposed the 'protobuf' package has already been installed.

BTW, I re-run the `bazel run run_experiments` just now, and found the problem still exists.

**Comment by gowthamkpr** [comment]
@AshiakerWang Please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/35414#issuecomment-601652629) and let me know if it helps.

**Comment by AshiakerWang** [comment]
@gowthamkpr Sorry for the late response and thank you for your reply. I have read the [comment](https://github.com/tensorflow/tensorflow/issues/35414#issuecomment-601652629) you provided with me, but unfortunately it seems that I have never installed  the 'Windows Subsystem for Linux' accord to [this](https://superuser.com/questions/1065569/how-to-remove-reset-windows-subsystem-for-linux-on-windows-insider-build-14316).

![image](https://user-images.githubusercontent.com/14258909/77851418-afed6980-720b-11ea-8633-dfcf2eedb252.png)

![image](https://user-images.githubusercontent.com/14258909/77851427-bbd92b80-720b-11ea-912e-bf53055f39f7.png)

**Comment by gowthamkpr** [comment]
@AshiakerWang Can you please share the series of steps that you followed to reproduce this issue? Thanks!

**Comment by gowthamkpr** [comment]
@AshiakerWang As mentioned in the comment The problem was the incompatibility of Bazel to bash on Windows as stated at https://docs.bazel.build/versions/master/windows.html.
Please use linux based system. Thanks!

**Comment by Vincent-bin** [comment]
@AshiakerWang I have the same issue here. Did you fix it?

**Comment by rani-pinchuk** [comment]
I have the same issue as well on Windows 10 - without 'Windows Subsystem for Linux', and when running bazel on CMD. Did anyone find any other reason for having this issue on Windows 10?

**Comment by KyleWiering** [comment]
This is more directly reported here:
https://github.com/bazelbuild/rules_docker/issues/1958
