### ISSUE TITLE
tf.keras.losses.cosine_similarity() is not a negative quantity

### ISSUE THREAD

**Issue by aikho** [tensorflow/tensorflow#37896]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/keras/losses/cosine_similarity

## Description of issue (what needs changing):
Documentation states that tf.keras.losses.cosine_similarity() "is a negative quantity between -1 and 0, where 0 indicates orthogonality and values closer to -1 indicate greater similarity."
But it is actually not true. tf.keras.losses.cosine_similarity() can return positive values.

### Usage example
```
>>> import tensorflow as tf
>>> tf.keras.losses.cosine_similarity([[1., 1.]], [[-1., -1.]])
<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.99999994], dtype=float32)>
```

**Comment by ManishAradwad** [comment]
I'll start working on this.

**Comment by mihaimaruseac** [comment]
Please tag me in PR fixing this
