### ISSUE TITLE
help me with tensorflow 2.0 installation

### ISSUE THREAD

**Issue by 0unstoppable** [tensorflow/tensorflow#37891]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows 10 64 bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version: 2.0
- Python version:3.7
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory: nvidia geforce gtx 1050ti

i tried a lots of tutorials to install tensorflow gpu but failed facing different issues mainly while running the object_detection_tutorial.ipynb is not ruuning..
![Screenshot (22)](https://user-images.githubusercontent.com/62600923/77514129-446a6b80-6e9c-11ea-9bed-f807ac43556d.png)
 
i already installed the tensorflow gpu but still it is again installing in jupyter notebook..
iam fully confused what to do...
please anyone help me out.

**Comment by ayushmankumar7** [comment]
Since you are working on your local computer ... go to command prompt and do "pip install tensorflow==2.0.0". Your work ll be done. Thank you.

**Comment by mihaimaruseac** [comment]
What is the error you are getting? It's not visible in the screenshot. Please post the error (using ` ``` ` proper markdown around it) instead of a screenshot

**Comment by 0unstoppable** [comment]
> What is the error you are getting? It's not visible in the screenshot. Please post the error (using `` ``` `` proper markdown around it) instead of a screenshot

![Screenshot (23)](https://user-images.githubusercontent.com/62600923/77628595-44d33700-6f6e-11ea-98c5-ddbc19d59fe9.png)
there is a bash error while executing ..

**Comment by gadagashwini** [comment]
@0unstoppable, 
Looks like issue is not related to Tenosrflow installation. To confirm Tensorflow installation, try 
```
import tensorflow as tf
tf.__version__
```
For bash error please refer this
https://stackoverflow.com/questions/37335201/jupyter-notebook-couldnt-find-program-bash .Thanks

**Comment by mihaimaruseac** [comment]
Issue not related to TensorFlow, closing.
