### ISSUE TITLE
incorrect app.flags.DEFINE_boolean behavior 

### ISSUE THREAD

**Issue by mborgerding** [tensorflow/tensorflow#379]
### demo python script
 test.py 
```
#!/usr/bin/python
import tensorflow as tf
tf.app.flags.DEFINE_boolean('tea',False,'Soggy Leaves')
cfg = tf.app.flags.FLAGS

if cfg.tea:
    print( "have some tea" )
else:
    print( "no tea" )
```

### Expected behavior
When the above test.py is run with any of {(no arguments), --notea, or --tea=True}, the script behaves as expected...

```
[markb@schur tmp]$ ./test.py
no tea
[markb@schur tmp]$ ./test.py --notea
no tea
[markb@schur tmp]$ ./test.py --tea=True
have some tea
```

### Weird stuff
Strangely `--tea=False` is *incorrectly* interpreted as True.  Having both tea and no tea is only possible in certain Infocom games.

```
[markb@schur tmp]$ ./test.py --tea=False
have some tea
```

Apparently, only those who *truly* want tea will get it.  

```
[markb@schur tmp]$ ./test.py --tea
usage: test.py [-h] [--tea TEA] [--notea]
test.py: error: argument --tea: expected one argument
```
C'mon. It's a boolean flag ! 
"Say something once.  Why say it again?"  -- *Talking Heads*

**Comment by vrv** [comment]
Looks like we're getting hit by: http://stackoverflow.com/questions/15008758/parsing-boolean-values-with-argparse

It's doing bool("False") --> True.

I'll try to get it to support:

--tea  --> tea is True
--tea=True -> tea is True
--tea=False -> tea is False
--notea --> tea is False

**Comment by gokul-uf** [comment]
@vrv 
this issue still persists as of TF 1.12.0
All the examples above work as expected
but  `./test.py --tea False` fails. Is this still expected behavior?

**Comment by gokul-uf** [comment]
Thanks, I will raise it there

**Comment by MartinPeris** [comment]
I know this has been closed for a long time and tf.app.flags are not really supported. But defining *tea* like this will give you the expected behavior:

`tf.app.flags.DEFINE_boolean('tea',None,'Soggy Leaves')`
