### ISSUE TITLE
Cannot get TensorFlow to work on Mac

### ISSUE THREAD

**Issue by CaedmonSwanson** [tensorflow/tensorflow#37902]
Hello everybody. I have done some programming in the past in C++, HTML, CSS and PHP but I wanted to get into AI. I had done a bit of python in the past (not very much though) and I thought that TensorFlow would be a good place to start. I am on a Mac (something I plan to change in the summer) and I was trying to follow this tutorial to get set up: https://www.youtube.com/watch?v=gWfVwnOyG78

To sum up, this is what I did:
1. I installed Anaconda-Navigator.
2. I made a new environment and added TensorFlow and Keras packages (I might need Keras in the future but it's not relevant for now).
3. I opened PyCharm (I already had it on my computer).

At this point I ran into issues. In the video linked above at 8:30 he makes a new project. However, my screen options are far different:

<img width="400" alt="Screen Shot 2020-03-25 at 7 05 21 PM" src="https://user-images.githubusercontent.com/47663532/77558085-98407900-6ecb-11ea-823b-c018b2b8ced8.png">
 
So, I setup the project as shown in the video above. The Project Interpreter is set up as so:
<img width="572" alt="Screen Shot 2020-03-25 at 7 08 04 PM" src="https://user-images.githubusercontent.com/47663532/77558481-06853b80-6ecc-11ea-8921-950c36b98c7d.png">

I added the TensorFlow packages:
<img width="600" alt="Screen Shot 2020-03-25 at 7 09 17 PM" src="https://user-images.githubusercontent.com/47663532/77558589-287ebe00-6ecc-11ea-8f39-2ea5367b4b87.png">

It said that the packages were installed:
<img width="374" alt="Screen Shot 2020-03-25 at 7 09 46 PM" src="https://user-images.githubusercontent.com/47663532/77558679-44825f80-6ecc-11ea-95c2-c5195c36f2b7.png">

Also, when I import TensorFlow it looks like it is recognized:
<img width="425" alt="Screen Shot 2020-03-25 at 7 12 37 PM" src="https://user-images.githubusercontent.com/47663532/77558937-9dea8e80-6ecc-11ea-9e0c-8fd2cf8e2ea6.png">

However, when I run the code I get this error:

<img width="616" alt="Screen Shot 2020-03-25 at 7 13 39 PM" src="https://user-images.githubusercontent.com/47663532/77559067-c2466b00-6ecc-11ea-8b17-f46fe498dbb2.png">

I can't seem to understand what I did wrong. I have spent hours at this point and I am so desperate that I would probably pay someone to help me set it up. I would appreciate any help more that you know. Thanks.

**Comment by mihaimaruseac** [comment]
There is no `session.run` in TF 2.0 and later

**Comment by nantha42** [comment]
You should use  parentheses for print()

**Comment by CaedmonSwanson** [comment]
Wow. Thanks guys. I didn't think I actually setup the project correctly. You were right about the code, it was for an older version. I tested some code for TF 2.0 and it worked! Thank you so much.
