### ISSUE TITLE
Direct feeding from GPU memory for Java

### ISSUE THREAD

**Issue by okdzhimiev** [tensorflow/tensorflow#37909]
**System information**
- TensorFlow version: 1.15.2
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Such feature is currently available in C++ API. It is mentioned as experimental but seems to be working. See [#5902](https://github.com/tensorflow/tensorflow/issues/5902) and particularly [direct session test](https://github.com/tensorflow/tensorflow/issues/5902#issuecomment-410792030).

This feature is for Java. It adds 2 things: 
* allocate tensor in GPU (GPUBFCAllocator)
* directly feed tensors allocated in GPU (makeCallable/runCallable with CallableOptions)

The use case is when one does pre-processing of the data (like image rectification and aberration correction) in GPU and then would like to feed the network without copying data back and forth. This might save quite some time for high resolution imagery.

**Will this change the current api? How?**
Add methods to Java API and new JNI calls.

**Who will benefit with this feature?**
One who uses Java API. This will increase performance of Java applications that employ data preprocessing before feeding graph.

**Any Other info.**
* My initial approach: https://github.com/okdzhimiev/tensorflow/tree/r1.15
* Small Java Maven project for testing: [tfhello](https://git.elphel.com/oleg/tfhello)

Intended use:
* Allocate Tensor in GPU memory
* Get the pointer to that memory
* Run a custom CUDA kernel, writing results to the Tensor memory (JCuda)
* Run inference

Currently doing testing.
As I don't casually do C++, please, have a look and let me know if I'm at least on the right track. Any advice will be greatly appreciated.
Thanks.

**Comment by sanjoy** [comment]
CC @gunan @sjamesr 

I've CC'ed folks who own the TF Java backend, but I suspect they don't have spare cycles to pre-review changes.  So I would suggest just creating a PR once you have something working.

**Comment by okdzhimiev** [comment]
It's working. What's the workflow for creating and running unit tests for TF Java? Are tests required for a PR?

**Comment by sanjoy** [comment]
> What's the workflow for creating and running unit tests for TF Java?

I'm not sure personally, but have you looked into the existing unit tests to see how they work?

> Are tests required for a PR?

Yes.

**Comment by okdzhimiev** [comment]
Ok.

Yes, I saw where the tests are. Was just wondering how to run them but it turned out to be straightforward:
```bazel test //tensorflow/java:ZerosTest```

Thanks for replies.
