### ISSUE TITLE
Performance of Tensorflow distributed training parameter server strategy is much slower for multi gpu multi worker environment

### ISSUE THREAD

**Issue by yaoyaowd** [tensorflow/tensorflow#37913]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): source
- TensorFlow version (use command below): 1.14 
- Python version: - Bazel
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: Cuda 10.1 cuDNN 7.6.5
- GPU model and memory: V100

**Describe the current behavior**
I'm doing a performance test on my object detection model on multiple workers, multiple gpus on each worker environment. I'm testing the parameter server strategy and mirror strategy.

strategy | workers | gpus per worker | time per 100 iters
-- | -- | -- | --
no distributed training | 1 | 1 | 53s
mirror strategy + NCCL | 1 | 8 | 78~79s
parameter server strategy | 8 | 1 | 65~70s per 800 iters
parameter server strategy | 8 | 8 | 260s per 800 iters

I noticed that the time spend on the 8 worker * 8 gpus per worker is much slower than the time spend on 8 worker * 1 gpus per worker + the overhead of 1 worker * 8 gpus per worker.

After I profile the code, I noticed that although we aggregate gradient on each worker and send to the parameter server. Each gpu is reading variable from the parameter server directly. Therefore, the parameter server is sending variables 8*8=64 times.

**Describe the expected behavior**

I'm wondering if there's a way to change the strategy so that the parameter server will send the variable to each worker and all gpus on the worker load variables from the worker local memory instead.

If possible, could you point me to a few code lines that I can modify.

**Comment by Saduf2019** [comment]
@yaoyaowd 
could you please share a simple stand alone code for us to replicate this issue on our local.
For performance issue please provide with xprof traces using [link.](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras#profiler_service)

**Comment by Saduf2019** [comment]
@yaoyaowd
could you please  update on the above comment

**Comment by Saduf2019** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
