### ISSUE TITLE
@tf.Module.with_name_scope AttributeError: __enter__

### ISSUE THREAD

**Issue by bela127** [tensorflow/tensorflow#37912]
**System information** 
Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): No
OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Linux Mint 19.3 (ubuntu)
TensorFlow installed from (source or
binary): binary
TensorFlow version (use command below): tf-nightly
Python version: 3.8 and 3.6

**Describe the current behavior**
Exeption is raised, when @tf.Module.with_name_scope is used. The context manager is not implemented proper.

**Describe the expected behavior**
work without error

**Standalone code to reproduce the issue** 
```
import tensorflow as tf

class DummyModel(tf.keras.layers.Layer):
    
    def __init__(self, name = "DummyModel", **kwargs):  
        super().__init__(name = name, **kwargs)

    @tf.Module.with_name_scope
    def build(self, inputs_shape):
        super().build(inputs_shape)
    
    @tf.Module.with_name_scope
    def call(self, inputs):
        return inputs
    
dm = DummyModel()


print(dm([1]))
```

**Other info / logs** 
```
AttributeErrorTraceback (most recent call last)
<ipython-input-7-2dd7f6e61139> in <module>
----> 1 import src.test_use_namescope

~tf/pose3D/src/test_use_namescope.py in <module>
     17 
     18 
---> 19 print(dm([1]))

~tf/pose3D/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    967         # Eager execution on data tensors.
    968         with backend.name_scope(self._name_scope()):
--> 969           self._maybe_build(inputs)
    970           cast_inputs = self._maybe_cast_inputs(inputs)
    971           with base_layer_utils.autocast_context_manager(

~tf/pose3D/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py in _maybe_build(self, inputs)
   2364         # operations.
   2365         with tf_utils.maybe_init_scope(self):
-> 2366           self.build(input_shapes)  # pylint:disable=not-callable
   2367       # We must set also ensure that the layer is marked as built, and the build
   2368       # shape is stored since user defined build functions may not be calling

~tf/pose3D/venv/lib/python3.6/site-packages/tensorflow/python/module/module.py in method_with_name_scope(self, *args, **kwargs)
    286     """
    287     def method_with_name_scope(self, *args, **kwargs):
--> 288       with self.name_scope:
    289         return method(self, *args, **kwargs)
    290 

AttributeError: __enter__
```

**Comment by bela127** [comment]
inspected the source code from tf.keras.layers.Layer.
it inherits from tf.Module but does not call supper().__init__ in __init__ so the needed code in Module is not executed:
```
if tf2.enabled():
      with ops.name_scope_v2(name) as scope_name:
        self._name_scope = ops.name_scope_v2(scope_name)
    else:
      with ops.name_scope(name, skip_on_eager=False) as scope_name:
        self._scope_name = scope_name
```
so i guess calling supper().__init__ can fix it.

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.2.0-rc1 ,Nightly and was able to reproduce the issue.Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/c06880409d0adbe4ef6424357a64ab7d/untitled747.ipynb) Thanks!

**Comment by karmel** [comment]
At this time, the tf.Module name scope decorator conflicts with Keras's own name scoping mechanisms. For this case, the `name` passed in the layer's constructor will already be used in namescoping the methods in question, so you don't need the additional name scope. If you want finer-grained control over name scopes, consider using tf.Module directly.
