### ISSUE TITLE
_pywrap_file_io.BufferedInputStream raises UnicodeDecodeError

### ISSUE THREAD

**Issue by Syaryoh** [tensorflow/tensorflow#37924]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): No
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Windows10 Home Edition
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary 
- TensorFlow version (use command below): 2.2.0rc1
- Python version: 3.7.7 
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source):  None
- CUDA/cuDNN version: 10.1/7.6.5
- GPU model and memory: GeForce GTX 980Ti 38845MB

**Describe the current behavior**
In jupyter notebook, I have tried TF Models tutorial(research/object_detection/object_detection_tutorial.ipynb) and got UnicodeDecodeError at following section.

List of the strings that is used to add correct label for each box.
PATH_TO_LABELS = 'models/research/object_detection/data/mscoco_label_map.pbtxt'
category_index = label_map_util.create_category_index_from_labelmap(PATH_TO_LABELS, use_display_name=True)

error log:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 90: invalid start byte

**Describe the expected behavior**
UnicodeDecodeError don't happen. 

**Standalone code to reproduce the issue** 
from tensorflow.python import _pywrap_file_io
_read_buf=_pywrap_file_io.BufferedInputStream('test', 1024*512)

**Other info / logs** 
My system language is Japanese and this may affect encode behavior.

**Comment by Saduf2019** [comment]
@Syaryoh
please refer to this [issue](https://stackoverflow.com/questions/22216076/unicodedecodeerror-utf8-codec-cant-decode-byte-0xa5-in-position-0-invalid-s)

[link1](https://www.edureka.co/community/51644/python-unicodedecodeerror-codec-decode-position-invalid) [link2](https://github.com/facebookresearch/VMZ/issues/62)  with similar error

**Comment by Syaryoh** [comment]
Thanks to reply.
I'm sorry to my misunderstanding.

This problem occurs when the target file do not exist.
In my reproduce code, I have made empty file 'test' and the error has disappeared.

It would be appreciated if you could add error message for us to recognize the file not exist.

**Comment by Saduf2019** [comment]
@Syaryoh 
Can you please share simple sample code for us to replicate the issue faced by you,

**Comment by Syaryoh** [comment]
In this python code:
from tensorflow.python import _pywrap_file_io
_read_buf=_pywrap_file_io.BufferedInputStream('test', 1024*512)

If a file named 'test' do not exist, it raises UnicodeDecodeError.


or this reproduces too:
Open the tutorial of TF Models(research/object_detection/object_detection_tutorial.ipynb) with Jupyter Notebook
and change value of PATH_TO_LABELS to 'test'(not exist file). Then it reproduce.

**Comment by Saduf2019** [comment]
@Syaryoh
can you please share that test file, so we can replicate the issue

**Comment by Saduf2019** [comment]
@Syaryoh
can you please update as per above comment

**Comment by Saduf2019** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by busedagidir** [comment]
> In this python code: from tensorflow.python import _pywrap_file_io _read_buf=_pywrap_file_io.BufferedInputStream('test', 1024*512)
> 
> If a file named 'test' do not exist, it raises UnicodeDecodeError.
> 
> or this reproduces too: Open the tutorial of TF Models(research/object_detection/object_detection_tutorial.ipynb) with Jupyter Notebook and change value of PATH_TO_LABELS to 'test'(not exist file). Then it reproduce.

thank you for the solution. I was trying to reach a directory full of photos but instead of photos directory I gave main directory path. e.g ; write `...--image_dir=D:\\AnacondaProjects\\tez\\Tensorflow\workspace\\training_demo\\images\\test`  instead of` ...--image_dir=D:\\AnacondaProjects\\tez\\Tensorflow\workspace\\training_demo\\images`
