### ISSUE TITLE
roadmap link broken

### ISSUE THREAD

**Issue by np000** [tensorflow/tensorflow#37934]
in [tensorflow.org](https://www.tensorflow.org/community) website the below roadmap link is  not working

**Comment by np000** [comment]
https://www.tensorflow.org/community/roadmap

**Comment by Rubix982** [comment]
Some information will be needed to solve this issue:

1): Where should it even point to, the `Product Roadmap` button?
2): Where is the code for the website where we can edit the href tag to a correct location?
3): Is this even the right place to make the issue?

Help from moderators I think will be more accurate.
Will it be a good idea to tag them here?

**Comment by np000** [comment]
https://www.tensorflow.org/community , this page has the roadmap button

**Comment by Rubix982** [comment]
No, I mean, should the `Roadmap` button at https://www.tensorflow.org/community even go to https://www.tensorflow.org/community/roadmap ? 
If yes, then the contents of https://www.tensorflow.org/community/roadmap should be updated.
If no, where else should it go? Is the 404 currently on purpose, a mistake, or a bug, or just a broken link?
I don't have any experience with how the website is built or its routes, but I would love to help given the right directions.

**Comment by MarkDaoust** [comment]
b/152751643

**Comment by lamberta** [comment]
Thanks. We'll fix the button since that page was out of date.

**Comment by np000** [comment]
closing as the roadmap link is not present in the community [webpage](https://www.tensorflow.org/community).

re-open if required.

**Comment by bhack** [comment]
Can we remove it also from https://github.com/tensorflow/tensorflow/blob/master/README.md#resources? 
See https://github.com/tensorflow/community/issues/206#issuecomment-593126257
