### ISSUE TITLE
will tensorflow support building and running model on tensorboard

### ISSUE THREAD

**Issue by suiyuan2009** [tensorflow/tensorflow#3793]
It may be too far ahead, but It'll be great to support building and running model on tensorboard directly. Writing code for deep learning tasks is interesting, but It costs much time even if you just need to copy and paste from other's code or modify on other's code. Since Deep learning programs share much similarity to each other, and tensorflow's internal mechanism is suitable for visual programming, it's not hard to do this. It'll benefit many kinds of users. Researchers and engineers don't need to spend a lot of time to code a model already exists or design a new model, a person not skilled at coding can do cool things just like a skilled programer.

**Comment by danmane** [comment]
We've discussed this a lot internally. At the moment, it is not on the roadmap. Of course, an open source contributor is welcome to develop it and send a pull request. :)
