### ISSUE TITLE
How can I get all tensor names in tflite model? Not only input_details and output_details

### ISSUE THREAD

**Issue by taoja12** [tensorflow/tensorflow#37931]

**Comment by theadityasam** [comment]
Hey @taoja12 
Please provide necessary details like the TF version, environment etc. for your issue.
As for what I gather from your query, you use **tf.lite.Interpreter** to parse the **tflite** model
```
interpreter = tf.lite.Interpreter(path="your_model.tflite")
interpreter.allocate_tensors()
interpreter.get_tensor_details()
```
Do refer to the docs - https://www.tensorflow.org/api_docs/python/tf/lite/Interpreter
