### ISSUE TITLE
Compile error on Windows

### ISSUE THREAD

**Issue by georgescortaru** [tensorflow/tensorflow#37935]
**System information** 
- OS Platform and Distribution: Windows 10
- TensorFlow installed from source
- TensorFlow version 2.1
- Python version: 3.7.1
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): Visual Studio 2019
- CUDA/cuDNN version: CUDA 10.1, cuDNN 7.6.5
- GPU model and memory: NVidia GForce GTX 1060 3GB

**Describe the current behavior**

I am trying to build a Windows DLL exporting custom code dependent on Tensorflow:

load("//tensorflow:tensorflow.bzl", "tf_cc_binary")

tf_cc_binary(
    name = "Inference_GPU.dll",
    linkshared = True,
    srcs = glob(["*.cpp", "*.h"]),
    defines	= ["_WINDOWS", "INFERENCE_NET_EXPORTS", "TF_GPU"],
    deps = [
	"//tensorflow/cc:cc_ops",
        "//tensorflow/cc:client_session",
        "//tensorflow/core:tensorflow",	
    ],
	copts = ["/O2", "/Gm-", "/Zi", "/FS"],
    linkopts = ["/DEBUG"]
)

Run the following bazel command:
bazel --output_base=F:\Bazel_cache build --config=opt --config=cuda --define=no_tensorflow_py_deps=true --copt=-nvcc_options=disable-warnings //tensorflow/cc/Inference:Inference_GPU.dll --jobs 2

Bazel stopped with the following error:

F:\bazel_cache\execroot\org_tensorflow\external\eigen_archive\unsupported\Eigen\CXX11\src/Tensor/TensorExecutor.h(381): error: identifier "std::conj<double> " is undefined in device code

4 errors detected in the compilation of "F:/bazel_temp/nvcc_inter_files_tmp_dir/tmpc6wr1kw5/cwise_op_gpu_conj.cu.compute_75.cpp1.ii".

Thank you,
George Scortaru

**Comment by gunan** [comment]
We never test with `/DEBUG` option, because binaries become too big for bazel to handle. That may be an issue in your case, too.

To me, this looks like some code meant for host ended up on a compilation unit for the device. @chsigg @sanjoy may have a better idea why would this happen.

**Comment by georgescortaru** [comment]
Thanks for looking into this.

I tried without /DEBUG option. It stopped with the same error. I will try to downgrade Tensorflow to version to 2.0.

**Comment by chsigg** [comment]
Could you try qualifying the `conj` in cwise_op_gpu_conj.cu.cc with `::tensorflow::functor::`?

**Comment by georgescortaru** [comment]
I modified the cwise_op_gpu_conj.cu.cc:

#if GOOGLE_CUDA || TENSORFLOW_USE_ROCM

#include "tensorflow/core/kernels/cwise_ops_gpu_common.cu.h"

namespace tensorflow {
namespace functor {
DEFINE_UNARY1(::tensorflow::functor::conj, complex64);
DEFINE_UNARY1(::tensorflow::functor::conj, complex128);
}  // namespace functor
}  // namespace tensorflow

#endif  // GOOGLE_CUDA || TENSORFLOW_USE_ROCM

Now I have the following error:

tensorflow/core/kernels/scatter_nd_op_gpu.cu.cc(102): error: identifier "std::operator -<double> " is undefined in device code

**Comment by Dave-Stein** [comment]
[Latest reasons](https://github.com/tensorflow/tensorflow/issues/39905#issuecomment-641588284) why nothing happens for last 6 months for Windows DLL for TF2.0, TF2.1 and TF2.2

**Comment by Dave-Stein** [comment]
We need to invite more discussion on the future of WINDOW support for tensorflow.  6 months with no progress but challenges. **Google needs to hire those WHO CLIAM HERE are able to address these challenges IMMEDIATELY.**

**Comment by Dave-Stein** [comment]
The latest commit to address this problem is to get more Windows developers to spend MORE TIME trying [new Bazel  (from 2.0 to 3.0)](https://github.com/tensorflow/tensorflow/commit/b4b83222d470afbf0b83d12b0824c0f056235655)

**Comment by Saduf2019** [comment]
@georgescortaru 
Could you pease try on the lastest stable version of tf 2.4.1 and let us know if this is still an issue.
