### ISSUE TITLE
Update vocabulary and add a new embeddings for the new token as you see them in training time

### ISSUE THREAD

**Issue by nitinmnsn** [tensorflow/tensorflow#37941]
I am aware i can use `x = tf.feature_column.categorical_column_with_vocabulary_list(cat_col_name,cat_col_unique_values)`. Where `cat_col_name` is the categorical column that i need to convert to consumable format by a dense layer `cat_col_unique_values` are the unique values present in this column. Then i use something like `feature_column.embedding_column(x, dimension=4)` to map each unique value in `cat_col_name` to an embedding of dimension 4. 

What if i have a really large dataset and it would not be feasable to know `cat_col_unique_values` beforehand. I mean to say, During training time:

1. keep reading batches and mapping the unique values seen to their corresponding embedding
2. In case a new value is seen in the columns cat_col_name, add another embedding to correspond to this newfound value

I dont suppose there is a way to do this currently, or is there?

**Comment by gadagashwini** [comment]
@nitinmnsn, Could you provide the standalone code and the Tensorflow version. Thanks

**Comment by nitinmnsn** [comment]
tnesorflow version : 2.1.0
standalone code for what? This is a feature request

**Comment by nitinmnsn** [comment]
any update on this?

**Comment by sachinprasadhs** [comment]
Hi, Could you please migrate from `feature column` to `keras preprocessing`, `feature column` will be deprecated going forward.
For more details refer [Migrate tf.feature_columns to Keras preprocessing layers](https://www.tensorflow.org/guide/migrate/migrating_feature_columns)
Also, refer the list of API's fate under feature column here https://www.tensorflow.org/api_docs/python/tf/feature_column?version=nightly.
The new keras [warsmart_embedding_matrix](https://www.tensorflow.org/api_docs/python/tf/keras/utils/warmstart_embedding_matrix) could of interest for you.
