### ISSUE TITLE
tensorflow v2  save and load model

### ISSUE THREAD

**Issue by wangweitong** [tensorflow/tensorflow#37945]
I got a problem for saving model with tensorflow 2.0 ,it's awful,I can not know how to save model with
that way,it wants me have a signatures for saving my model ,but I can not save my model like :

class Model(tf.keras.Model):

  @tf.function
  def call(self, x):
    ...

m = Model()
tf.saved_model.save(
    m, '/tmp/saved_model/',
    signatures=m.call.get_concrete_function(
        tf.TensorSpec(shape=[None, 3], dtype=tf.float32, name="inp")))

I don't know what "get_concrete_function" function is;
Somebody can help me?

**Comment by Saduf2019** [comment]
@wangweitong 
with reference to your question on"get_concrete_function", please refer to these [link](https://www.tensorflow.org/guide/concrete_function#using_get_concrete_function), [link-2](https://stackoverflow.com/questions/57542301/is-it-possible-to-train-a-concrete-function)

Can you share the problem faced and sample code for us to replicate the issue.

**Comment by wangweitong** [comment]
ok ,I will share the code tomorrow ,thank you for your help !!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Saduf2019"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 下午5:49
收件人:&nbsp;"tensorflow/tensorflow"<tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"2400"<1097828409@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tensorflow/tensorflow] tensorflow v2  save and load model (#37945)





 
@wangweitong
 with reference to your question on"get_concrete_function", please refer to these link, link-2
 
Can you share the problem faced and sample code for us to replicate the issue.

**Comment by wangweitong** [comment]
import os
import pickle

import tensorflow as tf

from util.train_model_util_TensorFlow import train_test_model_demo

os.environ["CUDA_VISIBLE_DEVICES"] = "2"

EPOCHS = 5
BATCH_SIZE = 2048
AID_DATA_DIR = '../data/Criteo/forOtherModels/'  # 辅助用途的文件路径


class DeepFM(tf.keras.Model):
    def __init__(self, num_feat, num_field, dropout_deep, dropout_fm,
                 reg_l1=0, reg_l2=0, layer_sizes=[400, 400, 400], embedding_size=10):
        super().__init__()
        self.reg_l1 = reg_l1
        self.reg_l2 = reg_l2  # L1/L2正则化并没有去使用
        self.num_feat = num_feat  # denote as M M是 有多少个特征列 14455 这的索引是用来embedding 的
        self.num_field = num_field  # denote as F f是特征有多少个特征字段 39个
        self.embedding_size = embedding_size  # denote as K k是embedding 的维度
        self.layer_sizes = layer_sizes

        self.dropout_deep = dropout_deep
        self.dropout_fm = dropout_fm

        # first order term parameters embedding
        self.first_weights = tf.keras.layers.Embedding(num_feat, 1, embeddings_initializer='uniform')  # None * M * 1

        # Feature Embedding
        self.feat_embeddings = tf.keras.layers.Embedding(num_feat, embedding_size,
                                                         embeddings_initializer='uniform')  # None * M * K

        # 神经网络方面的参数
        for i in range(len(layer_sizes)):
            setattr(self, 'dense_' + str(i), tf.keras.layers.Dense(layer_sizes[i]))
            setattr(self, 'batchNorm_' + str(i), tf.keras.layers.BatchNormalization())
            setattr(self, 'activation_' + str(i), tf.keras.layers.Activation('relu'))
            setattr(self, 'dropout_' + str(i), tf.keras.layers.Dropout(dropout_deep[i + 1]))

        # 最后一层全连接层
        self.fc = tf.keras.layers.Dense(1, activation="sigmoid", use_bias=True)

    # @tf.function(input_signature=[tf.TensorSpec(shape=[None], dtype=tf.string)])
    # def serve(self, serialized):
    #     print("a")

    def call(self, feat_data):
        feat_index, feat_value = feat_data
        feat_value = tf.expand_dims(feat_value, axis=-1)  # None * F * 1

        # Step1: 先计算一阶线性的部分 sum_square part
        first_weights = self.first_weights(feat_index)  # None * F * 1
        first_weight_value = tf.math.multiply(first_weights, feat_value)

        y_first_order = tf.math.reduce_sum(first_weight_value, axis=2)  # None * F
        y_first_order = tf.keras.layers.Dropout(self.dropout_fm[0])(y_first_order)  # None * F

        # Step2: 再计算二阶部分
        secd_feat_emb = self.feat_embeddings(feat_index)  # None * F * K
        feat_emd_value = tf.math.multiply(secd_feat_emb, feat_value)  # None * F * K(广播)

        # sum_square part
        summed_feat_emb = tf.math.reduce_sum(feat_emd_value, axis=1)  # None * K
        interaction_part1 = tf.math.pow(summed_feat_emb, 2)  # None * K

        # squared_sum part
        squared_feat_emd_value = tf.math.pow(feat_emd_value, 2)  # None * K
        interaction_part2 = tf.math.reduce_sum(squared_feat_emd_value, axis=1)  # None * K
        y_secd_order = 0.5 * tf.math.subtract(interaction_part1, interaction_part2)
        y_secd_order = tf.keras.layers.Dropout(self.dropout_fm[1])(y_secd_order)

        # Step3: Deep部分
        y_deep = tf.reshape(feat_emd_value, (-1, self.num_field * self.embedding_size))  # None * (F * K)
        y_deep = tf.keras.layers.Dropout(self.dropout_deep[0])(y_deep)

        for i in range(len(self.layer_sizes)):
            y_deep = getattr(self, 'dense_' + str(i))(y_deep)
            y_deep = getattr(self, 'batchNorm_' + str(i))(y_deep)
            y_deep = getattr(self, 'activation_' + str(i))(y_deep)
            y_deep = getattr(self, 'dropout_' + str(i))(y_deep)

        concat_input = tf.concat((y_first_order, y_secd_order, y_deep), axis=1)
        output = self.fc(concat_input)
        return output

  


if __name__ == '__main__':
    # 获取特征映射表
    feat_dict_ = pickle.load(open(AID_DATA_DIR + '/feat_dict_10.pkl2', 'rb'))
    print(len(feat_dict_))
    # 创建模型
    deepfm = DeepFM(num_feat=len(feat_dict_) + 1, num_field=18,
                    dropout_deep=[0.5, 0.5, 0.5, 0.5], dropout_fm=[0, 0],
                    layer_sizes=[400, 400, 400], embedding_size=10)
    train_label_path = AID_DATA_DIR + 'train_label'
    # 这里的索引是指的每个特征对应字典的索引
    train_idx_path = AID_DATA_DIR + 'train_idx'
    train_value_path = AID_DATA_DIR + 'train_value'

    test_label_path = AID_DATA_DIR + 'test_label'
    test_idx_path = AID_DATA_DIR + 'test_idx'
    test_value_path = AID_DATA_DIR + 'test_value'

    # 训练并预测
    train_test_model_demo(deepfm, train_label_path, train_idx_path, train_value_path, test_label_path, test_idx_path,
                          test_value_path)
    # deepfm.save_weights(filepath="./tfmodel.ckpt")

**Comment by wangweitong** [comment]
It's the code which I have trouble with

**Comment by Saduf2019** [comment]
@wangweitong 
i have tried to run the code shared by you on nightly, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/3c68f682d5ac697c927378f0a2c36cc5/37945.ipynb)
please share indented code so we could replicate the error faced by you.

**Comment by wangweitong** [comment]
https://github.com/wangweitong/tensorflow_demo/blob/master/Model/DeepFM_TensorFlow.py

It's the code ,you can clone it and run DeepFM_TensorFlow.py ,I don't know how to save the model,
somebody help me please

**Comment by Saduf2019** [comment]
@wangweitong 
please refer to this link for [save and load](https://www.tensorflow.org/tutorials/keras/save_and_load)

**Comment by wangweitong** [comment]
It's not working. It throws exception:
NotImplementedError: Saving the model to HDF5 format requires the model to be a Functional model or a Sequential model. It does not work for subclassed models, because such models are defined via the body of a Python method, which isn't safely serializable. Consider saving to the Tensorflow SavedModel format (by setting save_format="tf") or using `save_weights`.

I  want save the whole model not just weights

**Comment by ymodak** [comment]
Try Approach 2 from [Saving and Loading of Subclassed Models](https://www.tensorflow.org/guide/keras/save_and_serialize#approach_2) to save whole model.

**Comment by wangweitong** [comment]
git@github.com:wangweitong/recommend_system.git

Thanks but it's not working,maybe I use that with wrong way,the code in the repository,you can 
run it with tensorflow 2.1 ,the py's code name DeepFM_TensorFlow.py, data and code  are ready for
debugging,you can try it.

**Comment by wangweitong** [comment]
> Try Approach 2 from [Saving and Loading of Subclassed Models](https://www.tensorflow.org/guide/keras/save_and_serialize#approach_2) to save whole model.

git@github.com:wangweitong/recommend_system.git

Thanks but it's not working,maybe I use that with wrong way,the code in the repository,you can
run it with tensorflow 2.1 ,the py's code name DeepFM_TensorFlow.py, data and code are ready for
debugging,you can try it.

**Comment by wangweitong** [comment]
So，anyone solved this problem?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
