### ISSUE TITLE
Unable to connect jupyter notebook within tensorflow container in AWS

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/tensorflow#3795]
Currently we found that the [tensorflow/tensorflow](https://hub.docker.com/r/tensorflow/tensorflow/) does not work in AWS. I can access the port and open the jupyter website but could not `connect to the kernel`.

![image](https://cloud.githubusercontent.com/assets/2715000/17644038/a3160972-61ae-11e6-8ef6-1bbca7804cc2.png)

![image](https://cloud.githubusercontent.com/assets/2715000/17644040/a9745ed6-61ae-11e6-8cf0-c9b772cc9f0e.png)

The logs of that container look like these.

```
root# docker run -p 30100:8888 tensorflow/tensorflow
[I 15:09:48.070 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
/usr/local/lib/python2.7/dist-packages/widgetsnbextension/__init__.py:30: UserWarning: To use the jupyter-js-widgets nbextension, you'll need to update
    the Jupyter notebook to version 4.2 or later.
  the Jupyter notebook to version 4.2 or later.""")
[W 15:09:48.114 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 15:09:48.114 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 15:09:48.120 NotebookApp] Serving notebooks from local directory: /notebooks
[I 15:09:48.120 NotebookApp] 0 active kernels
[I 15:09:48.120 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/
[I 15:09:48.120 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 15:09:59.446 NotebookApp] 302 GET / (10.2.201.72) 0.79ms
[I 15:10:25.276 NotebookApp] Writing notebook-signing key to /root/.local/share/jupyter/notebook_secret
[W 15:10:25.283 NotebookApp] Notebook 3_mnist_from_scratch.ipynb is not trusted
[W 15:10:25.611 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20160813150948 (10.2.201.72) 7.44ms referer=http://10.69.1.246:30100/notebooks/3_mnist_from_scratch.ipynb
[I 15:10:28.037 NotebookApp] Kernel started: b2421ec2-2411-4b3a-9d49-83f4ec41a3ed
```

It doesn't work even if I try with `--net=host`. But it works for my local Linux server. The logs look like similar and I'm not sure if it is related to AWS's network or jupyter's configuration.

```
➜  sudo docker run -p 30100:8888 tensorflow/tensorflow
[I 15:16:47.063 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
/usr/local/lib/python2.7/dist-packages/widgetsnbextension/__init__.py:30: UserWarning: To use the jupyter-js-widgets nbextension, you'll need to update
    the Jupyter notebook to version 4.2 or later.
  the Jupyter notebook to version 4.2 or later.""")
[W 15:16:47.100 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 15:16:47.100 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 15:16:47.106 NotebookApp] Serving notebooks from local directory: /notebooks
[I 15:16:47.106 NotebookApp] 0 active kernels
[I 15:16:47.106 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/
[I 15:16:47.106 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 15:17:25.033 NotebookApp] 302 GET / (10.235.212.35) 1.53ms
[I 15:17:35.355 NotebookApp] Writing notebook-signing key to /root/.local/share/jupyter/notebook_secret
[W 15:17:35.361 NotebookApp] Notebook 3_mnist_from_scratch.ipynb is not trusted
[W 15:17:35.408 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20160813151647 (10.235.212.35) 5.66ms referer=http://tomi:30100/notebooks/3_mnist_from_scratch.ipynb
[I 15:17:37.307 NotebookApp] Kernel started: 952cac82-1a79-4446-b73e-728d5505d8a5
```

### Environment info
Operating System: AWS ubuntu 14.04

TensorFlow 0.9

### Steps to reproduce
1. `docker run -p 30100:8888 tensorflow/tensorflow` in AWS instances
2. Go to `$ip:30100` in the browser
3. Click any notebook

### What have you tried?
1. Trying in local Linux server rather than AWS instances should work.

**Comment by tobegit3hub** [comment]
Same problem even if I deploy `SkyDNS`.

![image](https://cloud.githubusercontent.com/assets/2715000/17655745/7c1f10e8-62e4-11e6-9a95-ecdc40014d19.png)

**Comment by yaroslavvb** [comment]
If you run it on your Linux local server, can you open it from another machine?

**Comment by tobegit3hub** [comment]
This may be the issue of [jupyter/notebook](https://github.com/jupyter/notebook) because I have the same issue when running pure notebook container in AWS.

I will start another issue to tract that.

**Comment by yaroslavvb** [comment]
By default, a notebook server runs locally at 127.0.0.1:8888 and is accessible only from localhost.
http://jupyter-notebook.readthedocs.io/en/latest/public_server.html

**Comment by tobegit3hub** [comment]
Thanks @yaroslavvb . I can access the container from other machine in my local server.

TensorFlow has customized the [jupyter configure file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/jupyter_notebook_config.py) and it should work for other clients. And I can access the index page which means the ip and port are correct.

Anyway, the pure jupyter notebook has the same issue so I will close this and please trace that in https://github.com/jupyter/notebook/issues/1681 if you're interested.
