### ISSUE TITLE
Can I get a output shape( or size) of each node from NodeDef ?

### ISSUE THREAD

**Issue by gangmuk** [tensorflow/tensorflow#37958]
TF version: 1.13.1 (so I am using not eager execution for my project.)

I want to know the output tensor shape or size of each node before actually executing graph.
(meaning, Graph building part in tensorflow before going into executor part.)

I guess I can do it by extracting proper information from NodeDef protobuf. There is "attr" and I guess it possibly contains the output tensor shape information. However, I don't see it. I printed "SummarizeAttrs(node_def)" which is returning "attr" in string format. But I can't find the output size info from it. 

There is some way to get the output shape in python api level. (ref: [)](https://stackoverflow.com/questions/46127471/how-to-get-weights-from-pb-model-in-tensorflow)

But I can't do the same in TF source code (c++ core part of tf) level.

I am pretty sure there is a way. Could anybody know how to do it?

Thank you in advance.

P.S I looked up other documents and articles, but couldn't find the answer.

**Comment by gangmuk** [comment]
this is a part of SummarizeAttr(node_def).

node name: MatMul,           Attr: T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"

no output shape info...

**Comment by zhuzilin** [comment]
The `NodeDef` is a protobuf message defined in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/node_def.proto

It does not contain output of the node and the inner implementation largely depends on this...

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
