### ISSUE TITLE
ImportError: cannot import name 'load_from_saved_model'

### ISSUE THREAD

**Issue by Sanqiang** [tensorflow/tensorflow#37959]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): na
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): colab/ubuntu
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): pip
- Python version: - Bazel
version (if compiling from source):1.4.0
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Error raised once "import tensorflow as tf"
from tensorflow.python.keras.saving.saved_model import load_from_saved_model
ImportError: cannot import name 'load_from_saved_model'

It seems like it happens today, which "import tensorflow" will raise this error once I "pip install tensorflow-gpu==1.14.0". 

**Describe the expected behavior**

Try to run "from tensorflow.python.keras.saving.saved_model import load_from_saved_model
"
It should import correctly without any error.

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Sanqiang** [comment]
BTW, this is the colab link: https://colab.research.google.com/drive/1Jr0j_I_npKQxcQ1ggJQFHTqoJHmt9Bqk

**Comment by maxkaustav** [comment]
try `tf.saved_model.load` or`tf.keras.models.load_model`

**Comment by gowthamkpr** [comment]
@Sanqiang I was able to import tensorflow using tensorflow 1.15. Can you please install tensorflow -gpu 1.15. Thanks!

**Comment by Sanqiang** [comment]
Close ticket.
It is because my origiinal TF2.0 is not removed cleanly.
