### ISSUE TITLE
Using experimental_new_converter generates opcode that is not found in kernel

### ISSUE THREAD

**Issue by seemakumar8** [tensorflow/tensorflow#37967]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installed from (source or binary): tf-nightly on colab
- Tensorflow version (commit SHA if source): Version 2.2
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): ARM Mbed OS (Cortex M K64F)

**Describe the problem**
I am trying the hello_world (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/hello_world).
Model : https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/keras_lstm.ipynb (with unroll set)

The model has operations SHAPE, GATHER, REDUCE_PROD etc which is not present in all_ops_resolver.cc. The Keras_lstm experimental example uses version tensorflowlite v2. I believe these operations are not supported in v1 . Any pointers on how to proceed. 

**Please provide the exact sequence of commands/steps when you ran into the problem**
Step 1: Model generation using https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/keras_lstm.ipynb with tf.keras.layers.LSTM(20, unroll=True). Without setting unroll, I get more than 1 subgraph error.

Step 2: Use the example https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/hello_world to generate binary for Cortex-M 
gives error "Didn't find op for builtin opcode 'SHAPE' version '1'"

My requirement is a working example of LSTM for Cortex-M (K64F).

**Comment by seemakumar8** [comment]
Hi,

After looking at the code, I realised the operations SHAPE, GATHER, REDUCE_PROD are not supported on Tensorflow Lite micro yet and is available only on Tensorflow Lite. 

Is there any alternative to run LSTM inference on Microcontrollers?

Regards,
Seema

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Comment by sushreebarsa** [comment]
@seemakumar8 This is a micro related issue,Please post this in [micro repository](https://github.com/tensorflow/tflite-micro/issues)  and move this issue to close status..Thanks!
