### ISSUE TITLE
Guide for Distributed TF with c++

### ISSUE THREAD

**Issue by ph0123** [tensorflow/tensorflow#37966]
I see the core here https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/distributed_runtime

But there is no instruction about how to run TF with distributed system (C++ language). 
Please share with us some documents about distributed TF c++.

Thanks,

**Comment by lip-realmax** [comment]
Same. Tensorflow states [supports for many others](https://www.tensorflow.org/api_docs) but could find an example or guide for using to in C++. Even [installation is on Python only](https://www.tensorflow.org/install).

**Comment by common-para-develop** [comment]
I try to  run TF with distributed system,but program core dump .No session factory registered for the given session options: {target: "grpc://127.0.0.1:2300" config: placement_period: 1 graph_options { optimizer_options { opt_level: L0 } }} Registered factories are {DIRECT_SESSION}.

**Comment by isra60** [comment]
Hi. Are there any updates about this?? Which is the best way to running inference with multiple GPUs on the same model with c++ API (Using SavedModel)

**Comment by tilakrayal** [comment]
@ph0123,
The visible_deivces_list is included in ConfigProto, it is a per-process setting. This is true of almost all options inside the [GPUOptions](https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/core/protobuf/config.proto#L123) protocol buffer.

The alternative work around is to have the models use the GPUs. You can trying work by explicitly constructing the models as  (using with tf.device('/gpu:0') when creating the graph in a Python program or editing the graph before creating the session. 
https://stackoverflow.com/questions/47799972/tensorflow-java-multi-gpu-inference/47915987#47915987

Reference: https://stackoverflow.com/questions/48422869/how-to-specify-which-device-to-use-for-saved-model

Thank you!
