### ISSUE TITLE
Broken link for tf.debugging.assert_same_float_dtype

### ISSUE THREAD

**Issue by theadityasam** [tensorflow/tensorflow#37971]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://github.com/tensorflow/docs/blob/r2.0/site/en/api_docs/python/index.md

## Description of issue (what needs changing):
The link for `tf.debugging.assert_same_float_dtype` is dead

### Clear description

The previous link leads to: https://github.com/tensorflow/docs/blob/r2.0/site/en/api_docs/python/tf/debugging/assert_same_float_dtype 
The new link must be:
https://github.com/tensorflow/docs/blob/r2.0/site/en/api_docs/python/tf/debugging/assert_same_float_dtype.md
(The .md file extension is missing in the link)

### Submit a pull request?

Yes, will be updating the issue soon enough

**Comment by Rubix982** [comment]
Hi, @theadityasam , I just checked https://github.com/tensorflow/docs/blob/r2.0/site/en/api_docs/python/index.md , let's call that [index](https://github.com/tensorflow/docs/blob/r2.0/site/en/api_docs/python/index.md), and none of the links work. It's not only for `assert_same_float_dtype`, they do however work when I append `'.md` at the end. I guess this means a complete modification of the contents of the file `/docs/index.md`.

Please update your title as well as per the issue.

**Comment by Rubix982** [comment]
Is it okay if I look into this instead? Should be pretty easy for me.

**Comment by theadityasam** [comment]
Hey @Rubix982 
Sure, work on the issue. I saw your PR, from what I gather, the index.md is generated by some script and I guess it's not as simple as adding .md to the url's(not really sure about that, need to ask the code owners once). Also, I believe the API docs were moved to the TF website and were deprecated in the previous versions.

**Comment by Saduf2019** [comment]
@theadityasam 
As there is a PR to monitor the issue, please confirm if we may move this to closed status.

**Comment by theadityasam** [comment]
Don't think it's right to close the issue until the PR is merged

**Comment by Rubix982** [comment]
@theadityasam PR successfully merged at https://github.com/tensorflow/docs/pull/1517 . This issue can be closed now.

**Comment by theadityasam** [comment]
Thanks
