### ISSUE TITLE
Graph Transform Tool remove_nodes is unable to remove Switch nodes but Identity nodes

### ISSUE THREAD

**Issue by tongvantruong** [tensorflow/tensorflow#37974]
I can remove all the Identity nodes from my .pb model with the commands:

```
bazel build tensorflow/tools/graph_transforms:transform_graph
bazel-bin/tensorflow/tools/graph_transforms/transform_graph --in_graph=../m.pb --out_graph=../new.pb --inputs='batch_size,phase_train' --outputs='label_batch,embeddings' --transforms='strip_unused_nodes(type=float, shape="1,299,299,3") remove_nodes(op=Identity) fold_old_batch_norms fold_constants(ignore_errors=true)'
```

However, I cannot do the same things if change Identity to Switch. It means the below command does not remove any nodes.

```
bazel-bin/tensorflow/tools/graph_transforms/transform_graph --in_graph=../m.pb --out_graph=../new.pb --inputs='batch_size,phase_train' --outputs='label_batch,embeddings' --transforms='strip_unused_nodes(type=float, shape="1,299,299,3") remove_nodes(op=Switch) fold_old_batch_norms fold_constants(ignore_errors=true)'
```

This is how I check the model nodes:

```
bazel-bin/tensorflow/tools/graph_transforms/summarize_graph --in_graph=../new.pb
```

**The result as below:**

Found 2 possible inputs: (name=phase_train, type=bool(10), shape=<unknown>) (name=batch_size, type=int32(3), shape=<unknown>) 
No variables spotted.
Found 2 possible outputs: (name=label_batch, op=Identity) (name=embeddings, op=Mul) 
Found 23512506 (23.51M) const parameters, 0 (0) variable parameters, and 676 control_edges
Op types used: 2019 Switch, 1105 Const, 566 Identity, 449 Merge, 448 Sub, 249 Mul, 224 FusedBatchNormV3, 132 Conv2D, 131 Relu, 23 ConcatV2, 21 BiasAdd, 21 AddV2, 3 Shape, 3 MaxPool, 3 Reshape, 2 Placeholder, 1 Maximum, 1 Pack, 1 MatMul, 1 QueueDequeueUpToV2, 1 RandomUniform, 1 GreaterEqual, 1 FIFOQueueV2, 1 Rsqrt, 1 AvgPool, 1 Square, 1 StridedSlice, 1 Cast, 1 Sum, 1 Add
To use with tensorflow/tools/benchmark:benchmark_model try these arguments:
bazel run tensorflow/tools/benchmark:benchmark_model -- --graph=../new.pb --show_flops --input_layer=phase_train,batch_size --input_layer_type=bool,int32 --input_layer_shape=: --output_layer=label_batch,embeddings

**My question is how can I remove the Switch nodes?**

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.
