### ISSUE TITLE
Tensorflow 2.x version is used in 1.x Tutorials

### ISSUE THREAD

**Issue by rakeshmothukuru1** [tensorflow/tensorflow#37972]
### Correct links

Is the link to the source code correct? : Yes

### Parameters defined

Are all parameters defined and formatted correctly? : N/A

### Returns defined

Are return values defined? : N/A

### Usage example

Is there a usage example? : No, usage example for Save and Restore is not present for Tensorflow 1.x version

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content? : N/A

### Submit a pull request?: No

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by ManishAradwad** [comment]
I'd like to work on this issue. But is this really a doc related issue?? Cause I think the changes involve migrating the code to tf-1.x from 2.x.

**Comment by Rubix982** [comment]
I cannot open the screenshot link. Can you upload the image on imgur instead? t is leading me to a Google Sign Page, and no matter how many times I open my account, it keeps looping back.

**Comment by Rubix982** [comment]
Should we create a new folder specifically for archives and examples for Tensorflow 2.x as well? Like we have docs/site/en/r1/ for TensorFlow 1.x?

I'm willing to open up a new issue for it.

**Comment by Rubix982** [comment]
@ManishAradwad I guess yes because that file which is mentioned is in [/docs/site/en/r1](https://github.com/tensorflow/docs/tree/master/site/en/r1) which basically has a README which says:

```
TensorFlow 1.x
This archive of the TensorFlow 1.x docs is in maintenance mode only.
```

**Comment by MarkDaoust** [comment]
Hi,  this is somewhat intentional. These run in tensorflow2's compatibility-mode. 

I'll add a note to all of them explaining.

**Comment by rakeshmothukuru1** [comment]
@MarkDaoust,
Thank you for your response. If I interpret your comment correctly, it means that the 1.x tutorials will be made 2.x compatible. Does it mean `Tensorflow Version 1.x` will be deprecated and there will be no Tutorials corresponding to `Tensorflow Version 1.x`, which uses `Sessions` inside the Code?

**Comment by MarkDaoust** [comment]
@rakeshmothukuru1

Yes we want to move away from TF1. But we're keeping this r1 snapshot as is for the foreseeable future.

They run with colab's tf2 installation, but if you use tf1 compatibility mode: 
 
```
import tf.compat.v1 as tf
tf.disable_v2_behavior()
```

It should make (almost) no difference whether you actually have tf1 or tf2 installed.

There are some `tf.Session` in these old tutorials. We hav e no plans to _delete_ them, we just discourage anyone from writing code this way.
