### ISSUE TITLE
Micro -- Crash in ErrorReporter::Report

### ISSUE THREAD

**Issue by andrewxcav** [tensorflow/tensorflow#37977]
**System information** 
TensorFlow Lite for Microcontrollers
running greedy_memory_planner_test from master
building with a Clang based compiler where va_list has the type void*

**Describe the current behavior**
Test crashes on 
`TF_LITE_REPORT_ERROR(error_reporter, "%s", line);`
Most likely because the string arg matches two prototypes in this configuration of Clang, and its picking the wrong one. Ultimately it tries do dereference the literal string leading to a crash.

**Describe the expected behavior**
No crash, print some ASCII art.

**Standalone code to reproduce the issue** 
If you have Docker up and running, then call this from the tensorflow folder:
`rm -rf tensorflow/lite/micro/tools/make/downloads/*`
`make -f tensorflow/lite/micro/tools/make/Makefile clean`
`docker run -it -v$(pwd):/home/builder:z --rm xcoreai/build-tools:latest make -f tensorflow/lite/micro/tools/make/Makefile TARGET="xcore" test_greedy_memory_planner_test`

**Other info / logs** Include any logs or source code that would be helpful to
PR #37976
Fixes the immediate issue in greedy_memory_planner by adding an explicit typecast:
`TF_LITE_REPORT_ERROR(error_reporter, "%s", (const char *)line);`

**Comment by ymodak** [comment]
Closing this issue since the associated PR has been merged. Thanks!
