### ISSUE TITLE
no detection on custom trained model

### ISSUE THREAD

**Issue by mhmedeng** [tensorflow/tensorflow#37984]
I have made a custom trained model using yolov2 and after 1500 iteration i tried to test it but no detection boxes the output image as the input any help please

**Comment by khimraj** [comment]
@mhmedeng, One of reason may be that your model is not learned significantly in 1500 iteration. You can try decreasing threshold value for probability predictions and see the output image to check for any box.

**Comment by mhmedeng** [comment]
> @mhmedeng, One of reason may be that your model is not learned significantly in 1500 iteration. You can try decreasing threshold value for probability predictions and see the output image to check for any box.

Thank you for your reply and now my trained model raised to 3200 iterations, I tested it and decreased threshold to 0.01 but nothing happened.

**Comment by Saduf2019** [comment]
@mhmedeng, 
please share tensorflow version and simple standalone code for us to replicate the issue

**Comment by mhmedeng** [comment]
> @mhmedeng,
> please share tensorflow version and simple standalone code for us to replicate the issue

thank you i solved the problem

**Comment by Saduf2019** [comment]
@mhmedeng,
moving this issue to closed status as its resolved
