### ISSUE TITLE
Kernel crashes with 'Check failed: work_element_count > 0 (0 vs. 0)' after first model has finished training.

### ISSUE THREAD

**Issue by nistrup** [tensorflow/tensorflow#37980]
**System information**  
- Have I written custom code (as opposed to using example directory):  No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10
- TensorFlow backend (yes / no):  Yes
- TensorFlow version:  2.1
- Keras version:  2.2.4-tf
- Python version:  3.7.6
- CUDA/cuDNN version:  CUDA 10.1, cuDNN: 7.5.6
- GPU model and memory:  Nvidia GTX1070, 8GB

**Describe the current behavior**  

I'm currently trying to train multiple permutations of the same model using the "Keras Tuner" with the following setup:

```
from kerastuner.tuners import BayesianOptimization
from kerastuner.engine.hyperparameters import HyperParameters

tuner = BayesianOptimization(build_model,
                             objective='val_loss',
                             max_trials=1000,
                             executions_per_trial=3,
                             directory=LOG_DIR)

tuner.search(train_data_single,
             verbose=0,
             epochs=EPOCHS,
             steps_per_epoch=EVALUATION_INTERVAL,
             validation_data=val_data_single,
             validation_steps=EVALUATION_INTERVAL // 4)
```

Where my dynamic model is defined as:

```
def build_model(hp):
    model = tf.keras.models.Sequential()

    model.add(tf.keras.layers.LSTM(units=hp.Int(f'LSTM_0_Units', min_value=8, max_value=128, step=8),
                                   dropout=hp.Float(f'LSTM_0_Dropout_Rate', min_value=0, max_value=0.5, step=0.1),
                                   batch_input_shape=(BATCH_SIZE, x_train_single.shape[1], x_train_single.shape[2]),
                                   return_sequences = True))

    for i in range(hp.Int('n_Extra_Layers', 0, 3)):
        model.add(tf.keras.layers.LSTM(units=hp.Int(f'LSTM_{i + 1}_Units', min_value=8, max_value=128, step=8),
                                       dropout=hp.Float(f'LSTM_{i + 1}_Dropout_Rate', min_value=0, max_value=0.5, step=0.1),
                                       return_sequences = True))
    
    model.add(tf.keras.layers.LSTM(units=hp.Int(f'LSTM_Closing_Units', min_value=8, max_value=128, step=8),
                                   dropout=hp.Float(f'LSTM_Closing_Dropout_Rate', min_value=0, max_value=0.5, step=0.1),
                                   return_sequences = False))
    
    if hp.Boolean("Extra_Dense"):
        model.add(tf.keras.layers.Dense(units=hp.Int(f'Extra_Dense_Units', min_value=8, max_value=128, step=8)))
    
    if hp.Boolean("Extra_Dropout"):
        model.add(tf.keras.layers.Dense(units=hp.Float(f'Extra_Dropout_Rate', min_value=0.1, max_value=0.5, step=0.1)))
    
    model.add(tf.keras.layers.Dense(1))

    model.compile(optimizer=tf.keras.optimizers.Adam(), 
                  loss='mae')
    
    return model
```

I'm faced with the following after the first successfully trained model:

```
2020-03-27 17:21:28.275596: F .\tensorflow/core/util/gpu_launch_config.h:129] Check failed: work_element_count > 0 (0 vs. 0)
[I 17:21:29.843 LabApp] KernelRestarter: restarting kernel (1/5), keep random ports
kernel 2bac517a-c195-47ca-952b-c25881cf0757 restarted
```

And the Jupyter Kernel crashes. Any ideas? :) 

**Describe the expected behavior**  

I would expect the session to NOT crash during hyperparameter optimization after the first model has completed since I would ideally want to train hundreds if not thousands of permutations.

**Other info**  
Prior to this issue I was faced with the following: https://github.com/tensorflow/tensorflow/issues/37932

**Comment by Saduf2019** [comment]
@nistrup 
please let us know if this issue still persist

**Comment by nistrup** [comment]
> @nistrup
> please let us know if this issue still persist

Sadly this is still an issue

**Comment by Saduf2019** [comment]
@nistrup 
i ran the code shared by you, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/aea68b462ac4c4be17f8a88d5cc4376c/your_version.ipynb) please find with comeplete code or a colab gist for us to analyse.

**Comment by Saduf2019** [comment]
@nistrup
Please update as per above comment

**Comment by nilskk** [comment]
@nistrup did you found a solution to your problem, because I'm having the same problem?

**Comment by JohanLj** [comment]
I am having the same problem.  Has anyone found a solution to this?
