### ISSUE TITLE
TFLite slower than Tensorflow on Desktop?

### ISSUE THREAD

**Issue by sclavel** [tensorflow/tensorflow#37989]
**System information** 
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Unbutu 18.04, Windows 10
- TensorFlow installed from (source or binary): binary (tf-nightly)
- TensorFlow version (use command below): v1.12.1-28195-g6609461732 2.2.0-dev20200327
- Python version: 3.6.9

**Describe the current behavior**
On desktop, TFLite infers 2x slower than the regular tensorflow in python (running on unbutu, installed from pip tf-nightly), and 5x slower in C (running on Windows10, with DLLs compiled from source)
I tested with the UNet model found here: https://github.com/deezer/spleeter/blob/master/spleeter/model/functions/unet.py
Without GPU enabled.

**Describe the expected behavior**
TFLite is supposed to be optimized to be more efficient for prediction-only, but with this model it's not the case.
Is this because TFLite is only optimized for mobile?
Or is it a specific operator in the model that slows down the current build of TFLite?

PS: I didn't have access to test on mobile, I only tested on desktop.
PS2: I did try to play with SetNumThread, but it didn't change the results.

**Standalone code to reproduce the issue** 
```
#!/usr/bin/env python
# coding: utf8

import time
import tensorflow as tf
import numpy as np

interpreter = tf.lite.Interpreter(model_path='model.tflite')
interpreter.allocate_tensors()
data = np.zeros((1, 512, 1024, 2), dtype=np.float32)
interpreter.set_tensor(0, data)
for i in range(1, 10):
    start = time.time()
    interpreter.invoke()
    end = time.time()
    print("tflite:", end-start)

loaded = tf.saved_model.load('saved_model')
infer = loaded.signatures["serving_default"]
input = tf.convert_to_tensor(data, np.float32)
for i in range(1, 10):
    start = time.time()
    infer(input)
    end = time.time()
    print("tensorflow:", end-start)
```

**Other info / logs**
```
> python3 profile.py
tflite: 3.574683427810669
tflite: 1.5097410678863525
tflite: 1.486119031906128
tflite: 1.5448968410491943
tflite: 1.4875497817993164
tflite: 1.4804818630218506
tflite: 1.543769121170044
tflite: 1.5214331150054932
tflite: 1.4932630062103271
tensorflow: 1.282404899597168
tensorflow: 0.6814086437225342
tensorflow: 0.7910218238830566
tensorflow: 0.6581625938415527
tensorflow: 0.620100736618042
tensorflow: 0.7165799140930176
tensorflow: 0.6456854343414307
tensorflow: 0.6069018840789795
```

**Comment by Saduf2019** [comment]
@sclavel 
please share exact sequence of steps before you encounter the issue

**Comment by Saduf2019** [comment]
@sclavel
please update as per above comment

**Comment by Saduf2019** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
