### ISSUE TITLE
[Bug] DLPack tensor seg faults when calling `tensor.device`

### ISSUE THREAD

**Issue by VoVAllen** [tensorflow/tensorflow#37986]
After https://github.com/tensorflow/tensorflow/pull/37944, the bug below happens. As I tested, if remove the added `TFE_DeleteContext(ctx);`, the codes below work fine. Do you have any idea what's the proper way to use TFE_Context here? @sanjoy @alextp 

```python
import tensorflow as tf
a = tf.constant([1])
dlpack_arr = tf.experimental.dlpack.to_dlpack(a)
tf_tensor = tf.experimental.dlpack.from_dlpack(dlpack_arr)
print(tf_tensor) # This works fine
print(tf_tensor.device) # Segment fault here. Works well without #37944 
```

**System information** 
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Ubuntu 16.04
- TF Version: latest nightly build or installed from source

**Comment by alextp** [comment]
Oh I completely misread the PR code. The code is broken.

Wh are we creating a new TFE_Context? We should pass the one from python in (so tf.experimental.dlpack.to_dlpack should capture context.context()._handle and pass it to the C++ function)

**Comment by VoVAllen** [comment]
Got it. I'm not familiar with tf codebases but just follows the code in unit tests when writing those functions. 😂
