### ISSUE TITLE
Unable to successfully build a devel-cpu.Dockerfile for arm32v7/arm64v8

### ISSUE THREAD

**Issue by settle** [tensorflow/tensorflow#37985]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04 and 19.10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Raspberry Pi 4 B (4 GB)
- TensorFlow installed from (source or binary): source
- TensorFlow version: r2.1
- Python version: 3.6 (Ubuntu 18.04) and 3.7 (Ubuntu 19.10)
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
There are no crossbuild compile instructions for Raspberry Pi 4 armhf or aarch64--the latter being of much more interest--so I figured I'd follow the devel-cpu.Dockerfile (in tensorflow/tools/dockerfiles/dockerfiles) and devel-cpu-ppc64le.Dockerfile (in tensorflow/tools/dockerfiles/dockerfiles/ppc64le), and attempt to create both a devel-cpu-arm32v7.Dockerfile and devel-cpu-arm32v7.Dockerfile.  However, both fail to build.  Specifically, they fail at the building Bazel step.  I have attempted this from docker on an amd64 host using qemu, as well as from docker on arm32v7 and arm64v8, and finally directly on arm32v7 and arm64v8 without docker.  I have tried installing potential dependancies, i.e., pip install zypper, but still have had no success.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

See attachment for devel-cpu-arm64v8.Dockerfile.  Simply replace "arm64v8" with "arm32v7" to create the devel-cpu-arm32v7.Dockerfile.
[devel-cpu-arm64v8.Dockerfile.txt](https://github.com/tensorflow/tensorflow/files/4395428/devel-cpu-arm64v8.Dockerfile.txt)

docker build --build-arg UBUNTU_VERSION=19.10 --build-arg CHECKOUT_TF_SRC=1 --build-arg USE_PYTHON_3_NOT_2=1 -f ./devel-cpu-arm32v7.Dockerfile -t arm32v7/tensorflow:latest-devel-py3 .
docker build --build-arg UBUNTU_VERSION=19.10 --build-arg CHECKOUT_TF_SRC=1 --build-arg USE_PYTHON_3_NOT_2=1 -f ./devel-cpu-arm64v8.Dockerfile -t arm64v8/tensorflow:latest-devel-py3 .

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

ERROR: /bazel/src/BUILD:105:1: PythonZipper src/create_embedded_tools.zip failed (Exit 255)
Target //src:bazel_nojdk failed to build
INFO: Elapsed time: 292.985s, Critical Path: 199.34s
INFO: 438 processes: 438 local.
FAILED: Build did NOT complete successfully

ERROR: Could not build Bazel
The command '/bin/sh -c cd /bazel &&     env BAZEL_JAVAC_OPTS="-J-Xmx2g -J-Xms200m" EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh' returned a non-zero code: 1

**Comment by settle** [comment]
FYI, in a way creating a working devel-cpu Dockerfile is a prerequisite of [#36672](https://github.com/tensorflow/tensorflow/issues/36672).

**Comment by settle** [comment]
I managed to successfully build a devel-cpu Dockerfile for aarch64 and submitted the necessary changes as PR #39695

**Comment by Saduf2019** [comment]
@settle 
As we have the latest stable version 2.6.0, Can you try building TF 2.6.0 and let us know if the issue still persists?
