### ISSUE TITLE
[tf.data.experimental.cardinality] not working on FlatMapDataset ? [2.2.0-rc1]

### ISSUE THREAD

**Issue by tarrade** [tensorflow/tensorflow#37998]
**System information** 
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.14.6 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.2.0-rc0-43-gacf4951a2f 2.2.0-rc1
- Python version: 3.7.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: - GPU model and memory: NA 

**Describe the current behavior**
I am making some test with 2.2.0-rc1. When using data from tensorflow dataset tf.data.experimental.cardinality is returning the number of even 

```
print(data['train'])
print(tf.data.experimental.cardinality(data['train'])) 
```

```
<DatasetV1Adapter shapes: {idx: (), label: (), sentence: ()}, types: {idx: tf.int32, label: tf.int64, sentence: tf.string}>
tf.Tensor(67349, shape=(), dtype=int64)
```
In such case I have a `DatasetV1Adapter`

Now when I am using Huggingface transformer that modify  the structure of the data:

```
train_dataset = glue_convert_examples_to_features(data['train'], 
                                                  tokenizer, 
                                                  max_length=128, 
                                                  task='sst-2')
```

```print(train_dataset)
print(tf.data.experimental.cardinality(train_dataset))
```

```
<FlatMapDataset shapes: ({input_ids: (None,), attention_mask: (None,), token_type_ids: (None,)}, ()), types: ({input_ids: tf.int32, attention_mask: tf.int32, token_type_ids: tf.int32}, tf.int64)>
tf.Tensor(-2, shape=(), dtype=int64)
```

In this case this is a `FlatMapDataset ` and tf.data.experimental.cardinality is not able tor eturn the number of event ? Is this expected ? In which case is tf.data.experimental.cardinality working ?

The documentation for TF 2.1.0 just said:
`dataset: A tf.data.Dataset for which to determine cardinality.`
 https://www.tensorflow.org/api_docs/python/tf/data/experimental/cardinality
For me (as a naive user) FlatMapDataset/DatasetV1Adapter are tf.data.Dataset 

The way the transformer is modifying the data is by using tf.data.Dataset.from_generator

**Describe the expected behavior**
Be able to return the total number of entry after the data being transformer using tf.data.Dataset.from_generator

**Standalone code to reproduce the issue** 

```
data, info = tensorflow_datasets.load(name='glue/sst2',
                                      data_dir=data_dir,
                                      with_info=True)
# recap input dataset
print(data['train'])
print(tf.data.experimental.cardinality(data['train']))
print(len(list(data['train']))

# Prepare data for BERT
train_dataset = glue_convert_examples_to_features(data['train'], 
                                                  tokenizer, 
                                                  max_length=128, 
                                                  task='sst-2')

print(train_dataset)
print(tf.data.experimental.cardinality(train_dataset))
print(len(list(train_dataset)))
```
A full notebook can be found here:
https://github.com/tarrade/proj_multilingual_text_classification/blob/master/notebook/00-Test/08_SST2_Huggingface_model.ipynb

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by jsimsa** [comment]
The answer is most likely that the `glue_convert_examples_to_features` method (for which I do not see source code) is doing something that prevents `tf.data.experimental.cardinality` from statically inferring the size of the output dataset.

Like shape inference, `tf.data.experimental.cardinality` will only produce a known answer if the answer can be determined by static analysis (i.e. without executing the input pipeline). When the input pipeline contains a `flat_map`, it is generally not possible to statically determine what will be the cardinality of the output from the cardinality from the input; for instance, the inputs to `flat_map` could be filenames that `flat_map` uses to create `TFRecordDataset` (that do not have statically known cardinality).

If you know the relationship between the input and output cardinality of your `flat_map`, you can provide it to the runtime using `tf.data.experimental.assert_cardinality`.

**Comment by tarrade** [comment]
Hi @jsimsa,

Thanks for the follow up. I will check with the Huggingface's team. The code is here:
https://github.com/huggingface/transformers/blob/master/src/transformers/data/processors/glue.py

Thanks
