### ISSUE TITLE
[tf.estimator] - `tf.estimator.Head` do not work with TPUs

### ISSUE THREAD

**Issue by nmatare** [tensorflow/tensorflow#37991]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): No
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Google Collab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: Nont issue
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): Google Collab
- Python version: - Bazel
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): None
- CUDA/cuDNN version: - GPU model and memory: None, TPU

**Describe the current behavior**

`tf.estimator.Heads` do not work with TPUs; they are scoped to the CPU, and are seen to belong to a different graph than the expected.

**Describe the expected behavior**

`tf.estimator.Heads` work across CPUs, GPUs, and TPUs.

**Standalone code to reproduce the issue** 

Please run the below Collab notebook. You will need to create, provide, and authenticate to a GCS bucket.

https://colab.research.google.com/gist/nmatare/3e08383751184bf10cc2a1ef0a922b97/untitled6.ipynb

**Comment by amahendrakar** [comment]
@nmatare,
I tried reproducing the issue but I'm facing an error stating `ValueError: Tensor("loss:0", shape=(), dtype=string) must be from the same graph as Tensor("loss:0", shape=(), dtype=string).`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/45c538419ae13eda80171f54d5a7d071/37991.ipynb).

Could you please confirm if this is the error you are expecting? Thanks!

**Comment by nmatare** [comment]
Yup, I can confirm that this is the same underlying error. The tensors have apparently been placed onto two distinct graphs.

**Comment by sushreebarsa** [comment]
I tried to run the code on Colab  with TF v2.5 and faced `ValueError` ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/74cd2a89776183f0dafa768232b48664/37991.ipynb#scrollTo=x9CcijYYBjE5) ..Thanks!

**Comment by sachinprasadhs** [comment]
TPU Estimator manages its own TensorFlow graph and session, so it is not compatible with TF2 behaviors.
We recommend that you migrate to the newer tf.distribute.TPUStrategy.
See the [TPU guide](https://www.tensorflow.org/guide/tpu) for details.

Could you please migrate from Estimator to Keras API which will enable you to perform the aforementioned tasks, such as [model building](https://www.tensorflow.org/guide/keras/custom_layers_and_models), gradient application, [training](https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit), evaluation, and prediction.
Refer Migration guide here https://www.tensorflow.org/guide/migrate/migrating_estimator for more details. Thanks!
