### ISSUE TITLE
wishlist: provide alternative build system

### ISSUE THREAD

**Issue by CDLuminate** [tensorflow/tensorflow#380]
The memory consumption for bootstraping bazel is very huge, according to my observation.
And I really have trouble building bazel on my machine because lacking of enough memory.

So could you please provide an alternative (traditional) build system (e.g. make, cmake) or setup.py, 
for users who insist on building software from source by themselves.

Thanks.

**Comment by rajasrijan** [comment]
+1

**Comment by hellf** [comment]
+1

**Comment by davidzchen** [comment]
I'm not necessarily opposed to this, but if you are observing Bazel using excessive amounts of memory, then it is a problem that we should fix.

I have opened bazelbuild/bazel#670 to track this issue. @CDLuminate Can you provide some details about the following:

1. How much memory does your machine have?
2. How much memory are you observing Bazel using to build itself?

Also, have you considered using the [Bazel binary installer](https://github.com/bazelbuild/bazel/releases)? If so, are you also observing huge memory usage while building TensorFlow?

**Comment by CDLuminate** [comment]
@davidzchen  Actually I'm not sure whether I've encountered a BUG when bootstraping bazel, but anyway I'll try to describe what I've seen while bootstraping bazel, in bazel issue 670.

**Comment by christopherowen** [comment]
+1

Bezel's java dependency is not preferable.

**Comment by davidzchen** [comment]
Looping back from bazelbuild/bazel#670: the memory consumption issue appears to be unrelated to Bazel. According to @CDLuminate, the issue went away after a kernel update.

**Comment by ageron** [comment]
It sounds like adding support for CMake builds would be helpful.  I'll give it a shot.

**Comment by hartsantler** [comment]
+1

**Comment by ageron** [comment]
I just submitted Pull Request https://github.com/tensorflow/tensorflow/pull/728 to add very basic CMake support to TensorFlow.  It builds the tutorial C++ training example (along with all dependencies).

Limitations: no GPU, no python, no tests, no install targets, tested only on MacOSX, and needs a bit of code cleanup. It's a first version to get the ball rolling.  I'll continue to work on it, your comments are more than welcome.

**Comment by bhack** [comment]
I like Cmake but we have experienced many misalignments problems in Caffe community maintaining two build systems. Every extension or contribution that involve the build system need to be double checked. And often developer don't have confidence with both build systems contributing code with partial coverage or different quality level. Android cmake support was not really maintained and never incorporated officially (see https://github.com/taka-no-me/android-cmake/issues/64)

**Comment by CDLuminate** [comment]
So that means the synchronization problem between multiple build systems should also be concerned.

**Comment by martinwicke** [comment]
We're aware of the issues surrounding having multiple build systems. We'd definitely prefer if bazel would just work for all platforms (in particular, #16, #17, #110), and we're pretty confident it will work for most people in the near future.

However, it's clear that for some platforms (especially embedded), that's a while off, and cmake seems like a good solution, especially if we can find a (semi-)automatic solution to generate the cmake. It would also solve the immediate packaging issues mentioned in #720.

**Comment by Sherif89** [comment]
+1.
I think CMake's the most viable choice. KDevelop and CLion support CMake projects. CMake also has a separate GUI program. It'd make development easier.
See [a link](https://www.kdevelop.org/news/first-beta-release-kdevelop-500-available).

**Comment by ageron** [comment]
Has anyone tried out the CMake files I contributed (Pull Request #728)?  I only tested them on MacOSX, so getting other's feedback on different platforms would be great.  Thanks!

**Comment by camaclean** [comment]
+1
I maintain the TensorFlow installation on Blue Waters and it's easier for me to build the entire Python stack except TensorFlow (which has over 500 packages) than it is to build TensorFlow. On supercomputers like Blue Waters, the toolchain and libraries usually aren't found in default locations. The Bazel build makes a lot of assumptions about paths and linker flags. It is also quite frustrating that it also tries to play the role of a package manager and ignores that its dependencies are already installed.

**Comment by martinwicke** [comment]
Since we maintain both a (partial) makefile build and a fairly complete cmake build (both in contrib) I will close this issue. Thanks for reminding me of its existence.

**Comment by camaclean** [comment]
From what I understand, the CMake build is broken for GPU right now and therefore can't be used to build a complete TensorFlow package. Is this outdated?

**Comment by martinwicke** [comment]
@mrry -- what's the latest?

**Comment by mrry** [comment]
Right now our CMake build only supports GPU on Windows, and we're not actively working on adding GPU support for other platforms (but would accept contributions).

**Comment by camaclean** [comment]
What exactly needs to be done to add GPU support for other platforms? Our users wish to use Tensorflow on the Cray XK7 nodes (which have Tesla K20s). It seems to be linking a lot of executables that don't seem to be built with the bazel build, like *_ops_gen_*.

**Comment by camaclean** [comment]
I am getting thousands of errors when grpc_tensorflow_server and a few example executables try to link.

**Comment by mrry** [comment]
@camaclean The other binaries are most likely part of the code generation for C++ and Python op wrappers - these are also built on Bazel, but they don't show up as prominently in your bin/ directory. From what I can tell, the GPU rules that are [conditionally executed on `WIN32`](https://github.com/tensorflow/tensorflow/blob/e297257e458654c7743c59c7f37154b7f6118c16/tensorflow/contrib/cmake/CMakeLists.txt#L147) should mostly work on Linux as well, but we haven't tested them.

Please feel free to open a new issue with details of the exact errors you're seeing.
