### ISSUE TITLE
Problems in Tensorflow Seq2Seq Tutorial

### ISSUE THREAD

**Issue by sahiliitm** [tensorflow/tensorflow#3800]
### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN: 
Cuda 7.5 and CuDNN v4
Output of ls -l /path/to/cuda/lib/cuda*:
```
-rwxrwxrwx 1 root root   322936 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root       19 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxrwxrwx 1 root root   383336 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart.so.7.5.18
-rwxrwxrwx 1 root root   720192 Aug 15  2015 /usr/local/cuda-7.5/lib64/libcudart_static.a
-rwxrwxrwx 1 root root 61272736 Jul 31 21:45 /usr/local/cuda-7.5/lib64/libcudnn.so
-rwxrwxrwx 1 root root 61272736 Jul 31 21:45 /usr/local/cuda-7.5/lib64/libcudnn.so.4
-rwxrwxrwx 1 root root 61272736 Jul 31 21:45 /usr/local/cuda-7.5/lib64/libcudnn.so.4.0.4
```

pip package installed from:
```
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl
```
The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
```
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
0.10.0rc0
```

The problem:
I'm trying out the seq2seq tutorial on natural language translation. 
The documentation of [seq2seq.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/seq2seq.py#L1086)
mentions that the output consists of per bucket output with each bucket containing tensors of shape 
"batch_size x num_decoder_symbols". This seems to be incorrect because when i print the tensorflow sizes inside the function, they turn out to be (?, 1024). In other words, (batch_size, layer_size). I think either the documentation or the code is wrong, and there is certainly a mismatch. I'm wondering which is the case?

### Steps to reproduce
1. Install Tensorflow
2. Clone this repo
3. edit "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/seq2seq.py"
to include the following print statement after [this line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/seq2seq.py#L1113)
```
print(bucket_outputs[0].get_shape())
```

### What have you tried?
1. Filed this bug.

**Comment by sahiliitm** [comment]
Another thing I've noticed is that this problem only arises when the `forward_only` parameter in the [constructor](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/translate/seq2seq_model.py#L58) of Seq2Seq_model is set. 
To verify this:
1) add the code
```
print(output_logits[0].shape)
```
after [this line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/translate/translate.py#L248) in translate.py

2) Next run the code as `python translate.py --decode` twice. 
2.1) In the first run, set the second argument in [this line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/translate/translate.py#L222) to `True` as in the original case. In this case the output of our print statemet is:
```
(1, 40000)
```
2.2 In the second run, set the second argument in [this line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/translate/translate.py#L222) to `False`. This mimics  training. In this case the output of our print statement is:
```
(1, 1024)
```

**Comment by lukaszkaiser** [comment]
This is a documentation problem being worked on in #3802 -- please look there, closing this issue.
