### ISSUE TITLE
Cleaning up old codes in colab notebooks.

### ISSUE THREAD

**Issue by abhinavsp0730** [tensorflow/tensorflow#38005]
## Cleaning up the codes in the colab notebooks.
From taking the reference from this [commit](https://github.com/tensorflow/examples/commit/5351bd4e1d4067e2a007b410495200c4bcf3fe61). I've see that there is celaning of codes going on.
* from __future__ import absolute_import, division, print_function, unicode_literals these lines are unnecessary. 
*   ``` 
         % try tensorflow 2.x
             except:
                     pass 
     ```
As now colab already supports tensorflow 2.x by default

# Pull Request
I'll love to address this issue. Kindly assign me this task.
## Repositories
1. Tensorflow/community

P.S :- I'll keep on adding repo in this list after discussing with the community.

**Comment by abhinavsp0730** [comment]
Hey, @MarkDaoust/ @lamberta  / @mihaimaruseac what are your thoughts in this?

**Comment by MarkDaoust** [comment]
I handled everything except `community/` in 036117caae91ede4783cb0797273128d203e56aa.

If you want to do that to `community/` too that would be great.

**Comment by MarkDaoust** [comment]
You're talking about [this directory](https://github.com/tensorflow/examples/tree/master/community/en) right?

**Comment by abhinavsp0730** [comment]
sorry, my bad i'm taking to tensorflow/example .

**Comment by abhinavsp0730** [comment]
> 
> 
> I handled everything except `community/` in 036117caae91ede4783cb0797273128d203e56aa.
> 
> If you want to do that to `community/` too that would be great.
Yah I'd love to do that in `community/` but I'm not getting what this means 036117caae91ede4783cb0797273128d203e56aa

**Comment by MarkDaoust** [comment]
Thanks for fixing this @abhinavsp0730.

(Reviewing/merging/email-notifications may have been a bit simpler if you had stacked the commits into a single PR, but NBD) 

>  I'm not getting what this means 036117caae91ede4...

I meant for it to be a link to the commit, but apparently that doesn't work across repositories.

https://github.com/tensorflow/examples/commit/036117caae91ede4783cb0797273128d203e56aa
