### ISSUE TITLE
Keras conversion works in python, but gives strange results in Anroid

### ISSUE THREAD

**Issue by nekapoor** [tensorflow/tensorflow#38009]
**System information**
- Platform (where I'm experiencing issues)
   android

**Command used to run the converter or code if you’re using the Python API**
```tflite_convert --keras_model_file=best-model-03-0.00.h5 --output_file=new_model.tflite```

**The output from the converter invocation**
```
2020-03-28 15:34:27.528903: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-28 15:34:27.562893: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fb8e8f21fd0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-28 15:34:27.562928: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-03-28 15:34:28.585694: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2020-03-28 15:34:28.590807: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-03-28 15:34:28.604941: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: graph_to_optimize
2020-03-28 15:34:28.604967: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0.238ms.
2020-03-28 15:34:28.604972: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-03-28 15:34:28.707516: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2020-03-28 15:34:28.707602: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-03-28 15:34:28.734064: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: graph_to_optimize
2020-03-28 15:34:28.734111: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 71 nodes (-32), 102 edges (-32), time = 15.415ms.
2020-03-28 15:34:28.734122: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 71 nodes (0), 102 edges (0), time = 3.223ms.```

**Also, please include a link to the saved model or GraphDef**

```
Here is the .h5 file: https://drive.google.com/file/d/1Zaj02NDmxG4A7_Mkl81W0puMXAekEEmR/view?usp=sharing

Here is the .tflite file: https://drive.google.com/file/d/1k_RJU7vm54gVtM_S_n7s4UAE3oekL51M/view?usp=sharing
```

**Failure details**
Using the command above and using the .h5 file linked above, I am able to successfully convert to a .tflite file and perform inference on that .tflite file in Python. 

However, when I use this tflite model file in my Android code, I always get outputs that like this: 
```
[{"label": "4", "prob": "0.9999292"}, {"label": "2", "prob": "5.891328E-5"}, {"label": "3", "prob": "9.082261E-6"}, {"label": "0", "prob": "2.7710482E-6"}, {"label": "1", "prob": "3.9977402E-10"}]
```

(this model has 5 outputs, 0-4)

No matter what image I pass, I get that "4" is the output with very similar (but not exactly the same) probabilities. These same images in Python are correctly analyzed and give probabilities that are more reasonable.  

**Any other info / logs**

- The input image is a grayscale image
- this is a float32 tflite model
- Here is the relevant android code: 

```
public class TensorFlowModule extends ReactContextBaseJavaModule {

  private static final int DIM_BATCH_SIZE = 1;
  private static final int DIM_PIXEL_SIZE = 1;
  static final int DIM_IMG_SIZE_X = 300;
  static final int DIM_IMG_SIZE_Y = 100;
  private static final int BYTE_SIZE_OF_FLOAT = 4;

  private final String TAG = this.getClass().getSimpleName();

  // THIS IS THE "JAVA BUFFER"
  protected ByteBuffer imgData = ByteBuffer.allocateDirect(BYTE_SIZE_OF_FLOAT * DIM_BATCH_SIZE * DIM_IMG_SIZE_X * DIM_IMG_SIZE_Y * DIM_PIXEL_SIZE);
  
  private Interpreter tflite;
  private List<String> labelList;
  private ByteBuffer inputBuffer = null;
  private float[][] labelProbArray = null;
  private static final int RESULTS_TO_SHOW = 5;
  private static final float IMAGE_MEAN = 0f;
  private static final float IMAGE_STD = 255f;

  private static final String MODEL_PATH = "best_model.tflite";
  private static final String LABEL_PATH = "best-model-03242020_dict.txt";
  private int[] intValues = new int[DIM_IMG_SIZE_X * DIM_IMG_SIZE_Y];

  public TensorFlowModule(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @Override
  public String getName() {
    return "TensorFlow";
  }

  @ReactMethod void predictFromExactAssayWindow(String base64Image, final Promise promise) {
    imgData.order(ByteOrder.nativeOrder());
    labelProbArray = new float[1][RESULTS_TO_SHOW];

    try {

      labelList = loadLabelList();
    } catch (Exception ex) {
      ex.printStackTrace();
    }

    byte[] decodedString = Base64.decode(base64Image, Base64.DEFAULT);
    Bitmap old_bitmap = BitmapFactory.decodeByteArray(decodedString, 0, decodedString.length);
    Bitmap bitmap = Bitmap.createScaledBitmap(old_bitmap, DIM_IMG_SIZE_X, DIM_IMG_SIZE_Y, true);

    convertBitmapToByteBuffer(bitmap);

      
    try {
      tflite = new Interpreter(loadModelFile());
    } catch (Exception ex) {
      Log.w("FIND_exception in loading tflite", "1");      
    }

    tflite.run(imgData, labelProbArray);
    promise.resolve(getResult());
    
  }

  private WritableNativeArray getResult() {
    WritableNativeArray result = new WritableNativeArray();

    //ArrayList<JSONObject> result = new ArrayList<JSONObject>();
    try {

      for (int i = 0; i < RESULTS_TO_SHOW; i++) {
          WritableNativeMap map = new WritableNativeMap();

          map.putString("label", labelList.get(i));
          float output = labelProbArray[0][i];
          map.putString("prob", String.valueOf(output));
          result.pushMap(map);

          Log.w("FIND_label ", labelList.get(i));
          Log.w("FIND_prob ", String.valueOf(labelProbArray[0][i]));
      }
    } catch (Exception ex) {
      ex.printStackTrace();
    }

    return result;
  }

  private List<String> loadLabelList() throws IOException {
    Activity activity = getCurrentActivity();
      List<String> labelList = new ArrayList<String>();
      BufferedReader reader =
              new BufferedReader(new InputStreamReader(activity.getAssets().open(LABEL_PATH)));
      String line;
      while ((line = reader.readLine()) != null) {
          labelList.add(line);
      }
      reader.close();
      return labelList;
  }

  private void convertBitmapToByteBuffer(Bitmap bitmap) {
      if (imgData == null) {
          return;
      }
      imgData.rewind();
      // Log.w("FIND_bitmap width ", String.valueOf(bitmap.getWidth()));
      // Log.w("FIND_bitmap height ", String.valueOf(bitmap.getHeight()));

      bitmap.getPixels(intValues, 0, bitmap.getWidth(), 0, 0, bitmap.getWidth(), bitmap.getHeight());
      // Convert the image to floating point.
      int pixel = 0;
      //long startTime = SystemClock.uptimeMillis();
      for (int i = 0; i < DIM_IMG_SIZE_X; ++i) {
          for (int j = 0; j < DIM_IMG_SIZE_Y; ++j) {
              final int val = intValues[pixel++];
              float rChannel = (val >> 16) & 0xFF;
              float gChannel = (val >> 8) & 0xFF;
              float bChannel = (val) & 0xFF;
              float gray = (rChannel * 0.299f + gChannel * 0.587f + bChannel * 0.114f);

              // float pixelValue = (rChannel + gChannel + bChannel) / 3 ;
              Log.w("FIND_pixelValue", "(" + i + ", " + j + ") - " + String.valueOf(gray));

              imgData.putFloat(gray);

          }
      }
  }

  private MappedByteBuffer loadModelFile() throws IOException {
    Activity activity = getCurrentActivity();
    AssetFileDescriptor fileDescriptor = activity.getAssets().openFd(MODEL_PATH);
    FileInputStream inputStream = new FileInputStream(fileDescriptor.getFileDescriptor());
    FileChannel fileChannel = inputStream.getChannel();
    long startOffset = fileDescriptor.getStartOffset();
    long declaredLength = fileDescriptor.getDeclaredLength();
    return fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength);
  }
}
```

Would love some insight into why my outputs are  always a "4" and the probabilities for everything except "4" are so, so small. Thanks ahead of time

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
 Thanks!
