### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'layers'

### ISSUE THREAD

**Issue by shanethomas1029** [tensorflow/tensorflow#38003]
model = tf.layers.Sequential([
        tf.keras.layers.Conv2D(64, (10, 10), activation = 'relu', input_shape = input_shape, kernel_initializer = initialize_weights(), kernel_regularizer = tf.keras.regularizers.l2(2e-4)),
        tf.keras.layers.MaxPool2D(),
        tf.keras.layers.Conv2D(128, (7, 7), activation='relu', kernel_initializer = initialize_weights(), bias_initializer = initialize_bias(), kernel_regularizer=tf.keras.regularizers.l2(2e-4)),
        tf.keras.layers.MaxPool2D(),
        tf.keras.layers.Conv2D(128, (4, 4), activation='relu', kernel_initializer= initialize_weights(), bias_initializer=initialize_bias(), kernel_regularizer=tf.keras.regularizers.l2(2e-4)),
        tf.keras.layers.MaxPooling2D(),
        tf.keras.layers.Conv2D(256, (4, 4), activation='relu', kernel_initializer=initialize_weights(), bias_initializer=initialize_bias(), kernel_regularizer=tf.keras.regularizers.l2(2e-4)),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(4096, activation='sigmoid',kernel_regularizer=l2(1e-3), kernel_initializer=initialize_weights(), bias_initializer=initialize_bias())

    ])

### **Error**
Traceback (most recent call last):
  File "C:\Users\shane\OneDrive\Desktop\Project new\signature_verification-master 3\core\model.py", line 61, in <module>
    model = get_model((105, 105, 1))
  File "C:\Users\shane\OneDrive\Desktop\Project new\signature_verification-master 3\core\model.py", line 28, in get_model
    model = tf.layers.Sequential([
AttributeError: module 'tensorflow' has no attribute 'layers'
>>>

**Comment by khimraj** [comment]
@shanethomas1029, Use `tf.keras.Sequential` instead of `tf.layers.Sequential`.

**Comment by Rubix982** [comment]
As per the documentation at https://www.tensorflow.org/api_docs/python/tf/keras/Sequential,

![image](https://user-images.githubusercontent.com/41635766/77829675-64708800-7145-11ea-8f35-6a14aee0c72d.png)

It is `tf.keras.Sequential`.
Please close this issue.

**Comment by gadagashwini** [comment]
@shanethomas1029, Did you try the @khimraj  and @Rubix982  solution. 
As mentioned in the [Tenosrflow doc](https://www.tensorflow.org/api_docs/python/tf/keras/Sequential?version=nightly), use `tf.keras.Sequential `instead of `tf.layers.Sequential`. Thanks

**Comment by gadagashwini** [comment]
@shanethomas1029, Is this still an issue?

**Comment by shanethomas1029** [comment]
Still working on it  Thank you !
