### ISSUE TITLE
Notebook problem while contributing

### ISSUE THREAD

**Issue by abhinavsp0730** [tensorflow/tensorflow#38011]
# issue
I'm contributing to Tensorflow/lucid notebooks. But while changing anything in the notebook I'm getting message in github " The diff is too large to display". And when I clicked to see the differences in the branch I'm seeing there are a lot of things is changed in the notebook automatically
# Problem
It's very hard for the reviewer to see what changes I've made.
* I've tried into vs code having python extension
* Also tried in jupyter notebook
But I'm getting the same problem in all these
## Example notebook
https://github.com/tensorflow/lucid/blob/master/notebooks/activation-atlas/activation-atlas-adversarial.ipynb

**Comment by abhinavsp0730** [comment]
Hey, @MarkDaoust  / @lamberta / @ravikyram / @mihaimaruseac . How you guys enconter this problem?

**Comment by abhinavsp0730** [comment]
I'm working in this issue https://github.com/tensorflow/lucid/issues/236

**Comment by ManishAradwad** [comment]
@abhinavsp0730 You can try making changes in Google colab. I personally use "Open in Colab" chrome extension to open any notebook in colab from github. Make sure you're opening the notebook from your fork(not from upstream repo). After you're done with changes use "Save a copy in Github" option in File menu.

**Comment by abhinavsp0730** [comment]
@ManishAradwad    thank you for your reply. I just only want to clear one thing after doing the changes, does it only reflects the changes I made in the notebook and solve my problem?

**Comment by ManishAradwad** [comment]
Yes, you can try it once. You'll see the difference.

**Comment by abhinavsp0730** [comment]
What it does it deleted the original file and created a file with the same name. Not updating the original file.

**Comment by abhinavsp0730** [comment]
@ManishAradwad please see https://github.com/tensorflow/lucid/pull/238 this pull request is it correct?

**Comment by ManishAradwad** [comment]
@abhinavsp0730 Something doesn't seem right. Can you tell me what steps are you actually doing to make a PR. See this [PR](https://github.com/tensorflow/examples/pull/141). Also make sure you're checking the changes in ReviewNB.

**Comment by abhinavsp0730** [comment]
Hey, @ManishAradwad here are my steps:
My steps that you've suggested:
1. I open the notebook in the colab from my forked repo.
2. I have done the changes and clicked on the option save a copy in github .
3. Then I've selected my forked repo directory where the .ipnyb file is present and clicked on save button.
4. But what has happened is the file was replaced with the new one having the same name as the original one.

**Comment by abhinavsp0730** [comment]
@ManishAradwad I've checked the PR also and find that you just changed the window size to 20 to 30.
But when I saw the changes in the file there are a lot of things has changed. Making the reviwer hard to find what exactly I've changed . 
![Screenshot (94)](https://user-images.githubusercontent.com/43638955/77851440-d359e980-71f6-11ea-9976-bce28e5bef9c.png)
![Screenshot (95)](https://user-images.githubusercontent.com/43638955/77851447-d523ad00-71f6-11ea-8c87-7f75ebb79dc7.png)

**Comment by ManishAradwad** [comment]
Check them on the review notebook app(see the comment in your PR). It is used to make it easy for reviewers to see the changes. Also I'm not sure why it is creating a new file in your PR rather than showing changes in original one. I think you should wait till others reply.

**Comment by MarkDaoust** [comment]
@ManishAradwad , thanks for your help.

Yes. 

One other trick we have on tensorflow/docs is this [nbfmt.py](https://github.com/tensorflow/docs/blob/master/tools/nbfmt.py), which you can use to standardize notebook formatting for situations like this. 

But it only helps if the repository is already solling that standard. 
And viewing the github diff directly will never work if there are inline images.
