### ISSUE TITLE
Adding correct version of tensorflow in udacity deep learning course

### ISSUE THREAD

**Issue by abhinavsp0730** [tensorflow/tensorflow#38015]
# issue
This https://github.com/tensorflow/examples/tree/master/courses/udacity_deep_learning repo
contains Udacity deep learning course having codes of tensorflow 1.x  . But now colab is having tensorflow 2.x by default.
# Pull Request
Hey, @MarkDaoust will you please tell me the right tensorflow version so that I'll update all the notebooks.

**Comment by MarkDaoust** [comment]
All of these should work in TensorFlow 2 as well. If anything specific doesn't let us know and we'll help get it working.
