### ISSUE TITLE
tf.sparse.reorder() produces fully-unknown shaped outputs from partially-unknown shaped placeholder inputs

### ISSUE THREAD

**Issue by ghost** [tensorflow/tensorflow#38023]
When reordering placeholder `SparseTensor`s with partially unknown shapes, the output shape is fully unknown. This prevents usage of the `tf.sparse.reorder()` function in keras models because an unknown batch size at model compile time prevents downstream layers from knowing their expected input shape.

**System information** 

- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): **Yes**

- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): **Linux CentOS 7**

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: **N/A**

- TensorFlow installed from (source or
binary): **Binary**

- TensorFlow version (use command below):  **2.2.0-dev20200327**

- Python version: **Python 3.7.6**

- Bazel version (if compiling from source): **N/A**

- GCC/Compiler version (if compiling from source):  **N/A**

- CUDA/cuDNN version: - GPU model and memory: **Unused**

**Describe the current behavior**
When calling `tf.sparse.reorder()` on a placeholder SparseTensor with a partially
unknown shape, the returned SparseTensor has a fully unknown shape

**Describe the expected behavior**
When calling `tf.sparse.reorder()` on a placeholder SparseTensor with a partially
unknown shape, the returned SparseTensor has the same partially-known shape
as the input tensor

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```python
placeholder = tf.keras.backend.placeholder(shape=(None, 32), dtype=tf.float32, sparse=True)
reordered = tf.sparse.reorder(sparse_placeholder)

print(placeholder.shape)
print(reordered.shape)

> (None, 32)
> (None, None)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@reesehyde-dst 
please share a simple standalone code for us to replicate the issue.

**Comment by reesehyde-dst** [comment]
Hi @Saduf2019 is the code sample in the original post sufficient? Copied below:

```python
placeholder = tf.keras.backend.placeholder(shape=(None, 32), dtype=tf.float32, sparse=True)
reordered = tf.sparse.reorder(sparse_placeholder)

print(placeholder.shape)
print(reordered.shape)

> (None, 32)
> (None, None)
```

**Comment by Saduf2019** [comment]
@reesehyde-dst 
Replicated code shared by you for analysis please find [gist](https://colab.sandbox.google.com/gist/Saduf2019/686b4428fd4f8d821768b2b5c60d9a60/38023.ipynb) of error faced, please share simple standalone code that can be used to replicate the issue faced.

**Comment by reesehyde-dst** [comment]
Sorry about that, the code sample was copied from a notebook and using the variable by a different name. Here it is fixed ([gist here](https://colab.research.google.com/gist/reesehyde-dst/3487cd382a7a4b199d117b38c74a8302/38023.ipynb)):

```python
placeholder = tf.keras.backend.placeholder(shape=(None, 32), dtype=tf.float32, sparse=True)
reordered = tf.sparse.reorder(placeholder)

print(placeholder.shape)
print(reordered.shape)

> (None, 32)
> (None, None)
```

**Comment by Saduf2019** [comment]
i have replicated the issue with shared gist, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/f68bd79eef90e8085b76c365b53fc766/untitled129.ipynb)

**Comment by chunduriv** [comment]
@ghost, Sorry for late response. 

To use ` tf.sparse.reorder()`  input must be `SparseTensor`. Please refer attached gist. Please check the [gist here](https://colab.sandbox.google.com/gist/chunduriv/34a5fe5af0167dc552cbd193c06ad27e/untitled66.ipynb). Thanks!
