### ISSUE TITLE
Unable to build micro_speech for Sparkfun Edge

### ISSUE THREAD

**Issue by dmanning23** [tensorflow/tensorflow#38024]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): 44400dfcde6e39aca68c4bc103c2e4e15b5379c5
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Sparkfun Edge

**Describe the problem**

I'm trying to build the micro_speech example for Sparkfun Edge from the `master` branch, but getting a few compile errors.

**Please provide the exact sequence of commands/steps when you ran into the problem**

I am following the steps at:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/micro_speech

The very first step,
`make -f tensorflow/lite/micro/tools/make/Makefile TARGET=sparkfun_edge TAGS="cmsis-nn" micro_speech_bin`
results in the following compile errors and warnings:

```
tensorflow/lite/micro/kernels/cmsis-nn/softmax.cc: In function 'void tflite::ops::micro::activations::SoftmaxQuantized(const TfLiteTensor*, TfLiteTensor*, const tflite::SoftmaxParams&)':
tensorflow/lite/micro/kernels/cmsis-nn/softmax.cc:97:30: error: 'input_shape' was not declared in this scope
     const int trailing_dim = input_shape.DimensionsCount() - 1;
                              ^~~~~~~~~~~
tensorflow/lite/micro/kernels/cmsis-nn/softmax.cc:97:30: note: suggested alternative: 'initstate'
     const int trailing_dim = input_shape.DimensionsCount() - 1;
                              ^~~~~~~~~~~
                              initstate
tensorflow/lite/micro/kernels/cmsis-nn/softmax.cc:99:60: error: 'output_shape' was not declared in this scope
         MatchingFlatSizeSkipDim(input_shape, trailing_dim, output_shape);
                                                            ^~~~~~~~~~~~
tensorflow/lite/micro/kernels/cmsis-nn/softmax.cc:99:60: note: suggested alternative: 'outer_size'
         MatchingFlatSizeSkipDim(input_shape, trailing_dim, output_shape);
                                                            ^~~~~~~~~~~~
                                                            outer_size
```

Any help is super appreciated. Cheers!

**Comment by freddan80** [comment]
@dmanning23 sorry for the late reply on this. Is this still an issue? I tried it on the latest baseline and it seem to work.

1. `make -f tensorflow/lite/micro/tools/make/Makefile TARGET=sparkfun_edge TAGS="cmsis-nn" clean clean_downloads`
2. `make -f tensorflow/lite/micro/tools/make/Makefile TARGET=sparkfun_edge TAGS="cmsis-nn" micro_speech_bin`
