### ISSUE TITLE
tflite_runtime pip package compiled from source does not run

### ISSUE THREAD

**Issue by nemo42** [tensorflow/tensorflow#38033]
**System information** 
- OS Platform and Distribution: 
Ubuntu 18.04 running in Windows 10 WSL
- TensorFlow installed from: 
Binary, however the tflite_runtime installed from source.
- TensorFlow version:  2.1.0
- Python version: 3.6
 - GCC/Compiler version: 7.4.0

**Describe the current behavior**
Compiled the tflite_runtime from master using:
`./tensorflow/lite/tools/pip_package/build_pip_package.sh`
and installed:
`pip install --upgrade tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/dist/tflite_runtime-2.1.0-cp36-cp36m-linux_x86_64.whl`
Trying to run load an tflite  file:
`python -c "from tflite_runtime.interpreter import Interpreter; Interpreter('foo.tflite')"`
gives the following error:
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/fresve01/.local/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 203, in __init__
    _interpreter_wrapper.CreateWrapperFromFile(
AttributeError: module 'tflite_runtime.interpreter_wrapper' has no attribute 'CreateWrapperFromFile'`

**Describe the expected behavior**
The tflite file should load without error.
Also the README.md file with build instructions should be updated since there is no swig dependency any more.

**Standalone code to reproduce the issue** 
`./tensorflow/lite/tools/pip_package/build_pip_package.sh`
`pip install --upgrade tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/dist/tflite_runtime-2.1.0-cp36-cp36m-linux_x86_64.whl`
`python -c "from tflite_runtime.interpreter import Interpreter; Interpreter('foo.tflite')"`

**Comment by teijeong** [comment]
Hi nemo42,

I'm working on this -- meanwhile, would you try changing following code pieces?

on `tensorflow/lite/tools/pip_package/setup.py`
```
diff --git a/tensorflow/lite/python/interpreter.py b/tensorflow/lite/python/interpreter.py
index e3d7d04be1..7015ffd670 100644
--- a/tensorflow/lite/python/interpreter.py
+++ b/tensorflow/lite/python/interpreter.py
@@ -35,15 +35,15 @@ if not __file__.endswith('tflite_runtime/interpreter.py'):
   # rule.
   # pylint: disable=g-inconsistent-quotes
   _interpreter_wrapper = LazyLoader(
      "_interpreter_wrapper", globals(),
      "tensorflow.lite.python.interpreter_wrapper."
      '_pywrap_tensorflow_interpreter_wrapper')
   # pylint: enable=g-inconsistent-quotes

   del LazyLoader
 else:
   # This file is part of tflite_runtime package.
-  from tflite_runtime import interpreter_wrapper as _interpreter_wrapper
+  from tflite_runtime import _pywrap_tensorflow_interpreter_wrapper as _interpreter_wrapper
```

on `tensorflow/lite/tools/pip_package/setup.py`
```
diff --git a/tensorflow/lite/tools/pip_package/setup.py b/tensorflow/lite/tools/pip_package/setup.py
index 0895e30255..5a7fa0bed8 100644
--- a/tensorflow/lite/tools/pip_package/setup.py
+++ b/tensorflow/lite/tools/pip_package/setup.py
@@ -160,7 +160,7 @@ LIB_TFLITE = 'tensorflow-lite'
 LIB_TFLITE_DIR = make_output('libdir')

 ext = Extension(
-    name='%s._interpreter_wrapper' % PACKAGE_NAME,
+    name='%s._pywrap_tensorflow_interpreter_wrapper' % PACKAGE_NAME,
```

**Comment by nemo42** [comment]
> Hi nemo42,
> 
> I'm working on this -- meanwhile, would you try changing following code pieces?

Hi teijeong,

Applying the patches above seems to have solved the issue, thanks!

**Comment by ravikyram** [comment]
@nemo42 

 Please close this thread if it solves your question. Thanks!

**Comment by teijeong** [comment]
Good to hear that! Closing this.

**Comment by teijeong** [comment]
Actually this change is not applied to the repo yet, please wait to close this issue until the change makes its way to the code.

**Comment by teijeong** [comment]
Fixed by https://github.com/tensorflow/tensorflow/commit/6a701314351845ecbc6641ecd2f68e21b582c3f8
