### ISSUE TITLE
Wrong usage of ```tf.keras.layers.Layer._maybe_build```

### ISSUE THREAD

**Issue by yoshihikoueno** [tensorflow/tensorflow#38030]
The function [```tf.keras.layers.Layer._maybe_build```](https://github.com/tensorflow/tensorflow/blob/1f98a556eb4a8981241a9ebd4257d8e95060462c/tensorflow/python/keras/engine/base_layer.py#L2357-L2394) is used inappropriately in some functions inside tensorflow implementation.

For example, [```tf.keras.layers.Layer.compute_output_shape```](https://github.com/tensorflow/tensorflow/blob/1f98a556eb4a8981241a9ebd4257d8e95060462c/tensorflow/python/keras/engine/base_layer.py#L663-L705) calls [```tf.keras.layers.Layer._maybe_build```](https://github.com/tensorflow/tensorflow/blob/1f98a556eb4a8981241a9ebd4257d8e95060462c/tensorflow/python/keras/engine/base_layer.py#L2357-L2394) with ```input_shapes``` argument([*1](https://github.com/tensorflow/tensorflow/blob/1f98a556eb4a8981241a9ebd4257d8e95060462c/tensorflow/python/keras/engine/base_layer.py#L687)), where it's supposed to be ```inputs```.

[```tf.keras.layers.Layer._maybe_build```](https://github.com/tensorflow/tensorflow/blob/1f98a556eb4a8981241a9ebd4257d8e95060462c/tensorflow/python/keras/engine/base_layer.py#L2357-L2394) tries to detect input shape by accessing ```inputs.shape``` attribute([*2](https://github.com/tensorflow/tensorflow/blob/1f98a556eb4a8981241a9ebd4257d8e95060462c/tensorflow/python/keras/engine/base_layer.py#L2371)), which doesn't exist because ```inputs``` is not a tensor but ```input_shape``` already, hence this function doesn't work as expected. This incident is eventually reported to a user as layer output shape inference failure and suggests overriding ```compute_output_shape``` function.

Although this error can be solved by overriding ```compute_output_shape``` as suggested by the error message, there're many cases where users don't need to do so if the functions are working properly.

Possible ways to solve this circumstance I can think of are

1. Add keyword argument ```input_shape``` to ```_maybe_build``` function so that they can receive either ```inputs``` or ```input_shapes```.

2. Create a dummy tensor inside ```compute_output_shape``` which can be used as an input argument to ```_maybe_build``` function.

I think either way won't take that much time to implement, so I hope this can be fixed soon.
If developers in the TensorFlow team are busy and can't spare time for this issue, I can work on this and issue a pull request. In that case, please give me some suggestions or opinions regarding the implementation or the modification, so that it can be approved and merged smoothly.

Thank you.

**Comment by yoshihikoueno** [comment]
Here is the sample code to demonstrate this issue.

```python
from tensorflow.keras.layers import Layer
from tensorflow.keras import layers
from tensorflow.keras import Model
import traceback


class CustomLayer(Layer):
    def __init__(self, units_base, *args, **kargs):
        super().__init__(self, *args, **kargs)
        self.units_base = units_base
        return

    def build(self, input_shapes):
        self.layer = layers.Dense(self.units_base + input_shapes[-1])
        self.built = True
        return

    def call(self, inputs, *args, **kargs):
        x = self.layer(inputs)
        return x


class CustomModel(Model):
    def __init__(self, *args, **kargs):
        super().__init__(self, *args, **kargs)
        return

    def build(self, input_shapes):
        self.l0 = CustomLayer(input_shapes[-1])
        self.l1 = CustomLayer(input_shapes[-1])
        self.built = True
        return

    def call(self, inputs, *args, **kargs):
        x = self.l0(inputs)
        x = self.l1(x)
        return x


if __name__ == '__main__':
    print('Case1: the model is built in prior to compute_output_shape')
    try:
        model = CustomModel()
        print('DEBUG: init bult:', model.built)
        outputshape = model.compute_output_shape([100, 50])
        print(outputshape)
    except Exception as e:
        print('Failed')
        traceback.print_exc()

    print('\nCase1: the model is built in prior to compute_output_shape')
    try:
        model = CustomModel()
        model.build([100, 50])
        print('DEBUG: init bult:', model.built)
        outputshape = model.compute_output_shape([100, 50])
        print(outputshape)
    except Exception as e:
        print('Failed')
        traceback.print_exc()
```

**Comment by gadagashwini** [comment]
@yoshihikoueno, I tried with Tf2.2 rc1, received `TypeError: 'NoneType' object is not subscriptable` . Please take a look at [gist](https://colab.sandbox.google.com/gist/gadagashwini/0ee73dfa03dce12f0bcebc2496bdf7ae/untitled486.ipynb) and confirm the expected behavior. Thanks

**Comment by yoshihikoueno** [comment]
@gadagashwini Yes, that behavior is not expected and it's caused by the bug I'm pointing out here. The root problem of this bug is that compute_output_shape function calls _maybe_build function with the wrong argument, which makes input_shapes to be None.

With my [pull request](https://github.com/tensorflow/tensorflow/pull/38031), it works as expected.

**Comment by yoshihikoueno** [comment]
@gadagashwini Here's the sample result.

With the current master branch,
```python
Case1: the model is not built in prior to compute_output_shape
DEBUG: init bult: False
Failed

Case2: the model is built in prior to compute_output_shape
DEBUG: init bult: True
Traceback (most recent call last):
  File "<ipython-input-2-041b5e76fb83>", line 45, in <module>
    outputshape = model.compute_output_shape([100, 50])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py", line 718, in compute_output_shape
    return super(Network, self).compute_output_shape(input_shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 681, in compute_output_shape
    self._maybe_build(input_shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 2416, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "<ipython-input-2-041b5e76fb83>", line 29, in build
    self.l0 = CustomLayer(input_shapes[-1])
TypeError: 'NoneType' object is not subscriptable
(100, 150)
```

With (the pull request)[https://github.com/tensorflow/tensorflow/pull/38031] applied:
```python
Case1: the model is not built in prior to compute_output_shape
DEBUG: init bult: False
(100, 150)

Case2: the model is built in prior to compute_output_shape
DEBUG: init bult: True
(100, 150)
```
