### ISSUE TITLE
Launch tensorboard in colab

### ISSUE THREAD

**Issue by lolpa1n** [tensorflow/tensorflow#38047]
i try launch tensorboard on colab, my code:

```
LOG_DIR = model_dir
get_ipython().system_raw(
    'tensorboard --logdir {} --host 0.0.0.0 --port 6060 &'
    .format(LOG_DIR)
)

get_ipython().system_raw('./ngrok http 6060 &')

! curl -s http://localhost:4040/api/tunnels | python3 -c \
    "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])"
```
two days ago everything worked, but now such an error:

[error](http://puu.sh/FqU8i/62b7eec918.jpg)

**Comment by gowthamkpr** [comment]
@lolpa1n Please share the entire code to reproduce this issue. Thanks!

**Comment by lolpa1n** [comment]
The code that I attached is entire code, the rest code for object detection

**Comment by lolpa1n** [comment]
> @lolpa1n Please share the entire code with data preferably as a gist to reproduce this issue. Thanks!

The code that I attached is entire code, the rest code for object detection

**Comment by gowthamkpr** [comment]
@lolpa1n Without using ngrok, is the local server running?

**Comment by lolpa1n** [comment]
> @lolpa1n Without using ngrok, is the local server running?

curl: (7) Failed to connect to localhost port 6006: Connection refused
![ss+(2020-04-05+at+04 05 49)](https://user-images.githubusercontent.com/47947340/78473119-8f676700-7757-11ea-8495-a9c66a3180f6.png)

**Comment by gowthamkpr** [comment]
@lolpa1n Please provide us the colab notebook(gist) for us to reproduce this issue. I am not able to reproduce it.
