### ISSUE TITLE
Distributed tensorflow：Does every worker also have all tf.Variable parameters?

### ISSUE THREAD

**Issue by Ljl-Jdsk** [tensorflow/tensorflow#38044]
Execute the following code on the two workers, and the printed values are different, indicating that each worker has parameters, so is ps sever only used to update parameters?
How should the parameters of the PS server be stored in the specified GPU?
# task0: 140340378338864 140340378339144 140340378449344
# task1: 140099479135792 140099479136072 140099479246272

worker_device = "/job:worker/task:{i}".format(i=FLAGS.task_index)
 with tf.device(tf.train.replica_device_setter(
            worker_device=worker_device,
            cluster=cluster
        )):
            x = tf.Variable([[1, 2, 3, 4]])
            w = tf.Variable([[2], [2], [2], [2]])
            mat = tf.matmul(x, w)
            print(id(x), id(w), id(mat))

**Comment by gadagashwini** [comment]
@Ljl-Jdsk, Please share the complete standalone to replicate the reported issue. Thanks!

**Comment by gadagashwini** [comment]
@Ljl-Jdsk, Please update for the above comment.

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
