### ISSUE TITLE
Unable to set top_k

### ISSUE THREAD

**Issue by fabian57fabian** [tensorflow/tensorflow#38045]
I downloaded this example file in order to execute detection using tensorflow lite as described in the [Coral edgetpu example](https://coral.ai/docs/edgetpu/tflite-python/#load-tensorflow-lite-and-run-an-inference).
I executed on a lots of image and i get **ALWAYS 10 detections** even if i lower the threshold to 0.
I want to upper this limit (during my research i found something like a top_k variable set somewhere in the modules).
How do i change it from python?

The example file is [here](https://github.com/tensorflow/tensorflow/blob/82ff6702ab409a88bfb070e5f3e8749e5865c303/tensorflow/lite/examples/python/label_image.py#L62)

**Comment by amahendrakar** [comment]
@fabian57fabian,
I was able to run the code from the example file without any issues. As per the given example, I got 5 outputs. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/b19ff297ca29cb334ed61d914af7cb3d/38045.ipynb). Thanks!

**Comment by fabian57fabian** [comment]
@amahendrakar i know that the example prints out 5 items.
Let's think that my problem is to detect the number of faces in a photo. I train my model, i run it with this script.

The pipeline in the script is:
- initialize the interpreter with model
- set tensor
- invoke
- get tensor
- filter 5 best results
- print results

So my problem is that the variable **result** after squeezing the output of the tensor contains only 10 values. Even when i have 50 people, the result is always 10.
How do i remove this limit of 10 results?
Would you like a modified script and the output to make my point?

**Comment by fabian57fabian** [comment]
SOLVED.
I retrained a model based on ssd_mobilenet_v1_quantized_300x300_coco14_sync.
Executing detection with ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite gives more than 10 results.
So the problem was the way i trained my model. It had 10 placeholders for 10 bboxes.
