### ISSUE TITLE
Also show "Available Since" for each API in tf docs

### ISSUE THREAD

**Issue by Nithanaroy** [tensorflow/tensorflow#38059]
It would be useful to show the lifecycle of an API in the docs. That is, show when say, `tf.data.Dataset.take` was added or when a certain is removed / renamed. It could be extended to arguments of each API as well. Or to put it in one line,
``` 
Expose version control information of APIs directly on tf docs
```
It would really help developers keep up with rapid development of TF even better.

**Comment by ManishAradwad** [comment]
I'd love to work on this one. But where should we add these docs?

**Comment by lamberta** [comment]
Discussed a bit previously, but not sure it's worth it.
Generally, the API is cumulative to maintain backward compatibility (aside from the major version jumps). We publish multiple versions on the site (and archive the rest in GitHub) so if you're stuck on an old version, you can browse that.

**Comment by Nithanaroy** [comment]
Yeah, looking at the older docs on Github, I realized it would be a useful
extension to use git's power to extract when an API or its attributes were
introduced or modified automatically, without any additional work from TF
developers. As you might know many other popular libraries like pandas,
sklearn and even Python itself use this approach. Many a times this
information prompted me to upgrade my libraries after I learned about their
recent additions which could heavily simplify my code. Also in the current
documentation I don't know of an easy way to search for 1.15 APIs, as the
default search works for the latest stable release only. If we add this
feature to docs, users need not worry about which version of TF they are
looking at and can actively keep up with changes made by TF's vibrant
community every day. This is just my two cents. Feel free to ignore :)

--
Nitin @ LinkedIn <http://bit.ly/nitinpasumarthy>

**Comment by mihaimaruseac** [comment]
The main issue is that the API surface of TensorFlow is extremely large at the moment, making documenting "Available Since" hard. While doable, we need to prioritize other work.

On the other work, modularization can help with this as every module could then start adding "available since" fields as needed.

**Comment by MarkDaoust** [comment]
It is possible to work out this information by diffing versions, but it's not high enough priority for us to automate. `git diff --stat` is your friend here.
