### ISSUE TITLE
Errors Building with Cuda 8 and CuDNN 5.1

### ISSUE THREAD

**Issue by drcrook1** [tensorflow/tensorflow#3805]
System:
Ubuntu 16.04
NVidia Driver Version: 367.35
Cuda 8.0
CuDNN 5.1.5

1.  Have to add into third_party/gpus/crosstool/CROSSTOOL an extra line to point to cuda-8.0 include
cxx_builtin_include_directory: "/usr/local/cuda-8.0/include"

2.  When building: 
 bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer

Explicit Error Received:
1 error detected in the compilation of "/tmp/tmpxft_00005521_00000000-7_depthtospace_op_gpu.cu.cpp1.ii".
ERROR: /home/drcrook/TensorFlow/tensorflow/tensorflow/core/kernels/BUILD:1529:1: output 'tensorflow/core/kernels/_objs/depth_space_ops_gpu/tensorflow/core/kernels/depthtospace_op_gpu.cu.pic.o' was not created.
ERROR: /home/drcrook/TensorFlow/tensorflow/tensorflow/core/kernels/BUILD:1529:1: not all outputs were created.
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by drcrook1** [comment]
Alright, so I resolved my issue by using a different branch...
git checkout r0.10
The default branch appears to just be broken every other day...

**Comment by yaroslavvb** [comment]
The continuous builds pass (ie depthtospace_op_test in here
http://ci.tensorflow.org/view/Nightly/job/nigntly-matrix-linux-gpu/TF_BUILD_CONTAINER_TYPE=GPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-linux/),
so I wonder what is it that makes a difference. CUDA 8.0 instead of
supported 7.5 maybe?

**Comment by drcrook1** [comment]
I would suspect its CUDA 8 or CuDNN 5.1.5 I'm not really familiar with either right now to make an educated assessment.

**Comment by yaroslavvb** [comment]
So not really a solution, but one thing to try is to try is CUDA 8 and
CuDNN 5.0
Last week I've been re-building with this configuration daily with no
problems

**Comment by drcrook1** [comment]
I was able to get a successful build against r0.10 using the latest of both, so I'm going to run with that for a while.  Not sure whats up with the default branch or why I would use that instead of the r0.10 branch.

**Comment by sherrym** [comment]
The head is under active development and could be unstable at times. Please continue to use the released branch. Thanks!
