### ISSUE TITLE
high thread count

### ISSUE THREAD

**Issue by stayprivate** [tensorflow/tensorflow#38053]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information** 
- Custom inference application written in Python.
- ubuntu 18.04.3, latest
- TensorFlow 1.14
- Python version:  3.7
- CUDA/cuDNN version:10.2
 - GPU. Nvidia 5 x T4 16G.

This is more of a question related to performance/effeciency  I'm in charge of setting up Ubuntu. I've been ask by a software developper to increase linux DefaultTaskMax to 20000.  The rationnal is that tensorflow create 2000 threads per GPU, there is about 20  models uploaded on 1 card. Yet 2000 seems like a totaly crazy number of threads.  My gut feeling tells me something must be wrong. That tensor flow is set up or used wrong.  I have been trying to find information about this with no luck. I also tried to find information on the effect of increasing DefaultTaskMax on kernel overhead.

Regards,
- Mario

**Comment by stayprivate** [comment]
I'm told using 
config.intra_op_parallelism_threads = 1
config.inter_op_parallelism_threads = 1

Brought down the number of threads from 11150 to 4568.

**Comment by stayprivate** [comment]
Seems like most threads are using around 580K of stacks. With 4000 threads, that means 2.3g of ram consumed just for stack. That seems like a waste of resource and not very cache friendly?  I'm real curious for the rational behind this.

**Comment by ezhulenev** [comment]
What are the names of these threads?

**Comment by stayprivate** [comment]
I did ps H -c python3 -o 'pid tid cmd comm' to get the threads name. ALL the threads are named python3.  I noticed something interesting. We start 5 instances of python3 with our program.  When I run the command ps command mentionned previously I would expect the output to show 5 different pid. Yet there are around 70 with each having around 65 threads.   That would imply some forking !?!

Can I infer from your question that this is indeed abnormal.   The author of the code tell me they reduce the program down to opening a tensor flow session and there was still lots of threads.  The fact that ALL threads are name python3 thread makes me doubt the operation I did, as again from your question, I assume some of those thread should have a tensor flow related name. Note that as I ran the ps command, the software had been just restarted and had yet to do anything of substance, I will confirme this with the developper tomorrow.

Thanks a lot !

**Comment by ezhulenev** [comment]
Thousands of threads is definitely abnormal. You probably see the name of the parent process... or something like that. Tensorflow has few thread pools, and they should have names (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/default/env.cc#L107-L110).

All (most?) threads should have some meaningful names, so it should be possible to tell if it's intra/inter op thread pool created multiple times, or something else.

**Comment by stayprivate** [comment]
Eugene,

I had doubt about the command I used, thus I checked it against some of our process/thread written in C++ in which we do set the thread name and it does show thread name and not parent/process name.

Looking at the code you linked to, I can't find anything that set the thread name at  the OS level. There's thread_name_registry to keep a map of thread_id and name. The fonction GetCurrentThreadName() will look in the map to get the name, if it can't find the thread name in that registry, it get the thread name from the OS. 

So the thread name Linux shows me seems to match the code you shown me ;-)

What I'm told by the python developper is that there are multiple models per GPU and multiple "connection", don't know what a connection is in tensorflow parlence.  From what i gather each of these connection create its own thread pool. I'm wondering if that make any kind of sense ;-)

**Comment by stayprivate** [comment]
Trying to find my way through tensorflow code ( ouf ) and looking at pid/tid/ppid here is my gut feeling:

I changed the command to display parrent pid ( ppid) and what I'm seing now it there are very view ppid. In fact I can find 5 parent pid that are matching the 5 python programs we start, one per GPU!!! These 5 "groups" have about 70 unique pids, and each pid has about 65 unique tids.

**Comment by stayprivates** [comment]
Ping?

**Comment by sanjoy** [comment]
> Looking at the code you linked to, I can't find anything that set the thread name at the OS level. There's thread_name_registry to keep a map of thread_id and name. The fonction GetCurrentThreadName() will look in the map to get the name, if it can't find the thread name in that registry, it get the thread name from the OS.
> 
> So the thread name Linux shows me seems to match the code you shown me ;-)

I suspect Eugene was proposing that you somehow get the names of the 2000 threads as specified in `GetThreadNameRegistry` to debug why there are so many.

However, it seems like you have multiple TF *processes* running and the problem is that there are a high total number of threads?  If so, that is expected: I don't think multiple TF processes collude to limit the total number of threads across processes.

**Comment by stayprivate** [comment]
> > Looking at the code you linked to, I can't find anything that set the thread name at the OS level. There's thread_name_registry to keep a map of thread_id and name. The fonction GetCurrentThreadName() will look in the map to get the name, if it can't find the thread name in that registry, it get the thread name from the OS.
> > So the thread name Linux shows me seems to match the code you shown me ;-)
> 
> I suspect Eugene was proposing that you somehow get the names of the 2000 threads as specified in `GetThreadNameRegistry` to debug why there are so many.
> 

Tensorflow 1.4 does not seems to set thread name at the OS level, as I describe in one of my post. I guess it could be possible to get them though tensorflow API, if that is what you mean?

> However, it seems like you have multiple TF _processes_ running and the problem is that there are a high total number of threads? If so, that is expected: I don't think multiple TF processes collude to limit the total number of threads across processes.

Yes we have 5 processes, but without setting 
  config.intra_op_parallelism_threads = 1
  config.inter_op_parallelism_threads = 1
We get 2200 threads per process. With the sop_parallelism_thread to 1,  it's down to ~820 which is still huge.

**Comment by ezhulenev** [comment]
Do you use regular TF or TF-MKL? (if I remember correctly TF-MKL is the default in Anaconda for example)

**Comment by stayprivates** [comment]
Regular TF.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
