### ISSUE TITLE
UnboundLocalError: local variable 'logs' referenced before assignment on training with little data

### ISSUE THREAD

**Issue by naripok** [tensorflow/tensorflow#38064]
I found an error caused by an attempt of coping training logs from a not yet assigned variable.
The error occurred on my machine (Arch linux, tensorflow v2.2rc2 compiled from source) and I managed to reproduce the error on colab, on a stock environment.
It only happens when the model.fit method is called with very little training / eval data.
The ```logs``` variable is assigned inside a ```for``` loop that never happens when there is no sufficient data. 

The code lives here:
https://github.com/tensorflow/tensorflow/blob/e6e5d6df2ab26620548f35bf2e652b19f6d06652/tensorflow/python/keras/engine/training.py#L793

The notebook gist link for reproducing the bug:
https://colab.research.google.com/gist/naripok/8ce09ec9c3e795b3635a6b1ac11ebd4b/tpu_transformer_model.ipynb

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.2.0-rc2. Please find the gist [here](https://colab.research.google.com/gist/amahendrakar/88f59bf9ab4c7cd27ef62a49e28162be/38064.ipynb). Thanks!

**Comment by Tuxius** [comment]
I have the same issue with TF v2.2.0-rc2

```
Epoch 19/20
18/18 [==============================] - 2s 125ms/step - loss: 0.0035 - accuracy: 1.0000
Epoch 20/20
18/18 [==============================] - 2s 126ms/step - loss: 0.0373 - accuracy: 0.9844

Traceback (most recent call last):
  File "run.py", line 155, in <module>
    main()
  File "run.py", line 120, in main
    accuracy, num_of_classes = train_Full_visible(unique_name)
  File "run.py", line 78, in train_Full_visible
    acc = neuro.train(picdb, train_ids, test_ids, "Full body visible")
  File "/ssd/200410 3rd Try/neuro.py", line 232, in train
    test_loss, test_acc = self.model.evaluate(test_generator, verbose=0)
  File "/home/frank/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/frank/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1028, in evaluate
    logs = tf_utils.to_numpy_or_python_type(logs)
UnboundLocalError: local variable 'logs' referenced before assignment
```

**Comment by PeterBrummer** [comment]
@Tuxius and others which stuck until this bug is fixed: 
I had the same issue  and I found that my validation data set had less samples as the batch_size.  Because I'm working with TFRecords-data-sets which have no meta data about how many records, i.e. samples, are in the data set I check now upfront whether the data set  contains at least batch_size records (samples). 

For that I use the following helper functions:

```
def doesDataSetContainsEnoughDataForBatch(dataset, batch_size):
    return len(list(dataset.take(batch_size).as_numpy_iterator())) == batch_size
  
def doesDataSetFileContainsEnoughDataForBatch(sampleFileName="", batch_size=100):
    dataset = tf.data.TFRecordDataset(sampleFileName)
    return doesDataSetContainsEnoughDataForBatch(dataset, batch_size=batch_size)

if __name__ == '__main__':
  dataSetFileName="./Samples/validation_data_123.tfrecord"
  if not doesDataSetFileContainsEnoughDataForBatch(dataSetFileName,batch_size=100):
    raise Exception(f"Data set file {dataSetFileName} doesn't contain enough data")
   
  # Now open the data set a second time knowing you have enough data 
  # and use it ....
  """
  trainDataset = tf.data.TFRecordDataset(dataSetFileName)
  
  model.fit ( trainDataset ... 
  
  """

```

Please keep in mind that by using the first helper function directly , 
i.e. doesDataSetContainsEnoughDataForBatch,  you already read batch_size samples from the data set. So you should recreate the data set after the check.

By using the second helper function  you just lose some execution time upfront.

If you don't use TFRecord data sets you might have a similar  issue. But then it is also a good idea to check upfront whether you have enough data for at least one batch.

**Comment by alimhanif** [comment]
> @Tuxius and others which stuck until this bug is fixed:
> I had the same issue and I found that my validation data set had less samples as the batch_size. Because I'm working with TFRecords-data-sets which have no meta data about how many records, i.e. samples, are in the data set I check now upfront whether the data set contains at least batch_size records (samples).
> 
> For that I use the following helper functions:
> 
> ```
> def doesDataSetContainsEnoughDataForBatch(dataset, batch_size):
>     return len(list(dataset.take(batch_size).as_numpy_iterator())) == batch_size
>   
> def doesDataSetFileContainsEnoughDataForBatch(sampleFileName="", batch_size=100):
>     dataset = tf.data.TFRecordDataset(sampleFileName)
>     return doesDataSetContainsEnoughDataForBatch(dataset, batch_size=batch_size)
> 
> if __name__ == '__main__':
>   dataSetFileName="./Samples/validation_data_123.tfrecord"
>   if not doesDataSetFileContainsEnoughDataForBatch(dataSetFileName,batch_size=100):
>     raise Exception(f"Data set file {dataSetFileName} doesn't contain enough data")
>    
>   # Now open the data set a second time knowing you have enough data 
>   # and use it ....
>   """
>   trainDataset = tf.data.TFRecordDataset(dataSetFileName)
>   
>   model.fit ( trainDataset ... 
>   
>   """
> ```
> 
> Please keep in mind that by using the first helper function directly ,
> i.e. doesDataSetContainsEnoughDataForBatch, you already read batch_size samples from the data set. So you should recreate the data set after the check.
> 
> By using the second helper function you just lose some execution time upfront.
> 
> If you don't use TFRecord data sets you might have a similar issue. But then it is also a good idea to check upfront whether you have enough data for at least one batch.

I added more data. It works well!
Thank you!

**Comment by tombelieber** [comment]
Hi there, I change the `batch_size` to smaller so that it could be more evenly divided during training. 
For example, when you have 300 training samples, do not use `batch_size=128`, try `batch_size =10` or `batch_size=20` something, it works for me.

**Comment by cassianocasagrande** [comment]
The issue is still reproducible with 2.2.0rc4, will test with 2.2.0 release.

**Comment by aliencaocao** [comment]
2.2 is still reproducible for me

**Comment by cassianocasagrande** [comment]
2.2 is still reproducible indeed

**Comment by F-Node-Karlsruhe** [comment]
Are there any other workarounds known yet? The batch size one did not work out for me.

**Comment by dominique-nshimyimana** [comment]
Same problem

**Comment by avitomar12** [comment]
same problem: Is there way ro fix the issue?

**Comment by AlmogDavid** [comment]
Same problem, the root cause for this issue is that the training cannot perform a single step because your dataset is not large enough to fill one training iteration.

Anyway, there is still a bug here, this is not the expected behavior.

**Comment by avitomar12** [comment]
> Same problem, the root cause for this issue is that the training cannot perform a single step because your dataset is not large enough to fill one training iteration.
> 
> Anyway, there is still a bug here, this is not the expected behavior.

Yes. You are right. When i increased training data the error doesnot occure.

**Comment by 20tamil20** [comment]
I have also same error arise , even increase the training dataset its not solved. Again i got the same error. kindly share me the solution if anyone knows about this.
Thank you

**Comment by avitomar12** [comment]
> I have also same error arise , even increase the training dataset its not solved. Again i got the same error. kindly share me the solution if anyone knows about this.
> Thank you

What is the size of the dataset you are using?

**Comment by 20tamil20** [comment]
512, 512 size and 247 images and masks

**Comment by maraujo** [comment]
I solved my particular issue setting the batch_size very small, in my case batch_size = 1. I confirm that this happens with small datasets.

**Comment by 20tamil20** [comment]
yes  sir, i have also reduced batchsize as 1, but i dont know the reason why the same error arise.

**Comment by mathpluscode** [comment]
I had the same error with using `model.fit` it turns out the `validation_steps` or `steps_per_epoch` was zero

**Comment by dbspace** [comment]
same problem also. is there a workaround?

**Comment by ducviet00** [comment]
same problem during training BiT. Batch size 128, Steps_per_epoch = 100

**Comment by mridoc** [comment]
Working with a small dataset 
changed batch_size = 64 - worked

**Comment by ChungNPH** [comment]
This error also raise when len(traindata) or len(validdata) is 0.

**Comment by BibhuDas123** [comment]
I found this error while running the training part of vgg16 model

def vgg16_model( num_classes=None):

    model = VGG16(weights='/kaggle/input/keras-pretrained-models/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5', include_top=False, input_shape=(224, 224, 3))
    x=Flatten()(model.output)
    output=Dense(num_classes,activation='softmax')(x)
    model=Model(model.input,output)
    return model

vgg_conv=vgg16_model(6)

def kappa_score(y_true, y_pred):
    
    y_true=tf.math.argmax(y_true)
    y_pred=tf.math.argmax(y_pred)
    return tf.compat.v1.py_func(cohen_kappa_score ,(y_true, y_pred),tf.double)

opt = SGD(lr=0.001)
vgg_conv.compile(loss='categorical_crossentropy',optimizer=opt,metrics=['accuracy',kappa_score])

nb_epochs = 3
batch_size = 16
nb_train_steps = train.shape[0]//batch_size
nb_val_steps=validation.shape[0]//batch_size

print("Number of training and validation steps: {} and {}".format(nb_train_steps,nb_val_steps))

check_point = ModelCheckpoint('./model.h5',monitor='val_loss',verbose=True, save_best_only=True, save_weights_only=True)

early_stop = EarlyStopping(monitor='val_loss',patience=25,verbose=True)

callbacks = [check_point,early_stop]

vgg_conv.fit_generator(
    train_generator,
    verbose=2,
    steps_per_epoch=nb_train_steps,
    epochs=nb_epochs,
    validation_data=validation_generator,
    validation_steps=nb_val_steps,
    callbacks=callbacks,
    use_multiprocessing=True)


Found 16 non-validated image filenames belonging to 6 classes.
Found 4 non-validated image filenames belonging to 2 classes.
Number of training and validation steps: 1 and 0
Epoch 1/3

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-47-721e3d1678a3> in <module>
     63     validation_steps=nb_val_steps,
     64     callbacks=callbacks,
---> 65     use_multiprocessing=True)

/opt/conda/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py in new_func(*args, **kwargs)
    322               'in a future version' if date is None else ('after %s' % date),
    323               instructions)
--> 324       return func(*args, **kwargs)
    325     return tf_decorator.make_decorator(
    326         func, new_func, 'deprecated',

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1477         use_multiprocessing=use_multiprocessing,
   1478         shuffle=shuffle,
-> 1479         initial_epoch=initial_epoch)
   1480 
   1481   @deprecation.deprecated(

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
     64   def _method_wrapper(self, *args, **kwargs):
     65     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
---> 66       return method(self, *args, **kwargs)
     67 
     68     # Running inside `run_distribute_coordinator` already.

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
    870               workers=workers,
    871               use_multiprocessing=use_multiprocessing,
--> 872               return_dict=True)
    873           val_logs = {'val_' + name: val for name, val in val_logs.items()}
    874           epoch_logs.update(val_logs)

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
     64   def _method_wrapper(self, *args, **kwargs):
     65     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
---> 66       return method(self, *args, **kwargs)
     67 
     68     # Running inside `run_distribute_coordinator` already.

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in evaluate(self, x, y, batch_size, verbose, sample_weight, steps, callbacks, max_queue_size, workers, use_multiprocessing, return_dict)
   1089       callbacks.on_test_end()
   1090 
-> 1091       logs = tf_utils.to_numpy_or_python_type(logs)
   1092       if return_dict:
   1093         return logs

UnboundLocalError: local variable 'logs' referenced before assignment

**Comment by cassianokc** [comment]
Can we add tag 2.3 for this issue?

**Comment by BibhuDas123** [comment]
> Can we add tag 2.3 for this issue?
I am using tensorflow 2.2.0

**Comment by bersbersbers** [comment]
I am surprised there is no self-contained code example reproducing this, so here is one:

```
import numpy as np
from tensorflow import keras
model = keras.models.Sequential([keras.layers.Dense(1, input_shape=(1,))])
model.compile(loss="mse", optimizer="adam")
model.fit(x=np.ones((1, 1)), y=np.ones((1, 1)), validation_split=0.5)
```

**Comment by uzi0espil** [comment]
This is reproducible in TF 2.3. I am using batch_size of 1 and no validation data.

**Comment by jdraines** [comment]
Encountered this error, myself, and thought I'd share my debugging in case others would benefit in some way.

Tracing the calls and returns, it seems that inside `fit`, a local variable `logs` is first defined inside a for loop iterating over DataHandler.steps(), which, in many cases, is a number dependent on the cardinality of the Dataset. If the Dataset cardinality is zero, then `logs` will never be created, resulting in the UnboundLocalError we're all getting.

The cardinality of my Dataset was being returned as 0 because I had created it from a `.take()` called on a `BatchDataset` -- which was an artifact of a previous iteration of my code.

After cleaning the code (in my case, calling `take` on a Dataset that had not been batched), my Dataset.cardinality() returned a nonzero value, and the error was resolved.

**Comment by rollingdeep** [comment]
when turn off validation_data, it works! tf.__version__ == '2.2.0'
```
logistic_regression.fit(train_dense_x, 
          train_label, epochs=100, batch_size=256,
#           validation_data=(val_dense_x, val_label),  
          callbacks=[tbCallBack])
```

**Comment by martianvenusian** [comment]
check number of your training data. It might equal to zero

**Comment by Nithanaroy** [comment]
Looks like this happens when size of the training data is <= batch size

**Comment by ianovski** [comment]
> check number of your training data. It might equal to zero

In my case, I read my tfrecords incorrectly but didn't get any warnings or errors. After reading the record, you can try printing its size as a sanity check.

**Comment by goldiegadde** [comment]
@naripok the original issue of "UnboundLocalError: local variable 'logs' referenced before assignment" is no longer with the latest tf-nightly. Can you please confirm and if so close the issue ?

**Comment by naripok** [comment]
Sorry for the delay,

Confirmed.

Thanks!

**Comment by hafiz031** [comment]
> had less samples as the batch_size

The same situation can occur if the train-set has less number of examples than the batch size. In my case my train-set's directory was wrongly given.

**Comment by khlevnov** [comment]
> check number of your training data. It might equal to zero

Thank you!
