### ISSUE TITLE
GAN Training Loop overriding Model.train_step()

### ISSUE THREAD

**Issue by ElPapi42** [tensorflow/tensorflow#38061]
Hello!

I was trying to wrap my head around how to make an Adversarial Training Loop for GANs using the recently feature of TF2.2.0, the ability to override Model.train_step(). Right now, i feel that is not possible because a GAN are two separate networks, but maybe there is some way of do this, that is cleaner than a Custom Training Loop.

My doubts come to my mind because right now im implementing a GAN for image Deblurring following the Paper of DeblurGANV2, and im feeling frustration because now the performance is poor and maybe i dont plan my implementation very good. I you wish to help me there, this is the repo: https://github.com/ElPapi42/deep-deblurring, im going crazy with this.

If this is a suitable way of creating such implementation, will be awesome to write docs about this.

**Comment by ravikyram** [comment]
@ElPapi42 

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps in localizing the issue faster.Thanks!

**Comment by ElPapi42** [comment]
Hello! maybe i dont explain my self very well, there is no issue @ravikyram , but im interested in know the viability of implement a GAN training loop overriding `Model.train_step`. Currently i cant find a tutorial about this specific situation in the docs, and the existing one, is implemented using Custom Training Loop and GradientTape.

**Comment by ElPapi42** [comment]
Update: Im doing my own advances on this topic, i have a solution, but there is a detail, for train a GAN two optimizers are required, i was checking how the training logic was implemented, and seems like Model can only accept a single Optimizer, not a tuple or list. This is stopping me from reaching the solution, because injecting the extra optimizer using other methods, like class args or something like that, will prevent the model from saving the extra optimizer state. Is there something im not seeing? Model.compile() accepts a tuple of optimizers?. im looking for a workaround.

**Comment by gabrieldemarmiesse** [comment]
This is a very unofficial answer, but I think you're looking for this: https://twitter.com/fchollet/status/1250622989541838848

**Comment by ElPapi42** [comment]
@gabrieldemarmiesse awesome link, in fact, I already implemented the GAN by myself this way, but there is some details this publication helps me to clarify, I will upload the cheat sheet here for future reference!

![EVsaz1hU4AEoLps](https://user-images.githubusercontent.com/17053461/80309585-f6e76400-87a3-11ea-8de2-daa0fe049784.jpg)
