### ISSUE TITLE
tflite converter build in ops not support: ResizeNearestNeighbor

### ISSUE THREAD

**Issue by mengjiexu** [tensorflow/tensorflow#38063]
when I convert the keras model to tflite, it is ok when :
     `convert.experimental_new_converter = False`
but when:
    `conver.experimental_new_converter=True`
it shows the error:
 

> <unknown>:0: error: failed while converting: 'main'
> Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag): ResizeNearestNeighbor.

I use code:
`converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
`
It is ok, but the resize nearest neighbor should be the buildin ops:
`kTfLiteBuiltinResizeNearestNeighbor = 97,
  kTfLiteBuiltinLeakyRelu = 98,
  kTfLiteBuiltinSquaredDifference = 99,
  kTfLiteBuiltinMirrorPad = 100,`

**Comment by jvishnuvardhan** [comment]
@mengjiexu Can you please share a standalone code to reproduce the issue? Thanks!
