### ISSUE TITLE
Failed to build the master branch

### ISSUE THREAD

**Issue by 372046933** [tensorflow/tensorflow#38065]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04 tensorflow/tensorflow:latest-devel-gpu-py3):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: master branch
- Python version:3.6.9
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):Build label: 2.0.0
- GCC/Compiler version (if compiling from source):gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
- CUDA/cuDNN version: 10.1
- GPU model and memory:

**Describe the problem**
Master branch build failed
**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
bazel build --jobs=4 --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```
**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
NFO: Call stack for the definition of repository 'llvm-project' which is a tf_http_archive (rule definition at /home/tx/Downloads/tensorflow/third_party/repo.bzl:134:19):
 - /home/tx/Downloads/tensorflow/tensorflow/workspace.bzl:598:5
 - /home/tx/Downloads/tensorflow/WORKSPACE:19:1
ERROR: /home/tx/Downloads/tensorflow/tensorflow/lite/toco/BUILD:439:1: Target '//tensorflow/lite/toco:toco' depends on toolchain '@local_config_cc//:cc-compiler-k8', which cannot be found: error loading package '@local_config_cc//': Unable to load file '@local_config_cc//:armeabi_cc_toolchain_config.bzl': file doesn't exist'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: error loading package '@local_config_cc//': Unable to load file '@local_config_cc//:armeabi_cc_toolchain_config.bzl': file doesn't exist
INFO: Elapsed time: 10.477s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (226 packages loaded, 3671 targets configured)
    currently loading: @com_github_grpc_grpc//src/compiler ... (2 packages)
    Fetching @com_google_absl; fetching 4s
```

**Comment by ravikyram** [comment]
Provide the exact sequence of commands / steps that you executed before running into the problem.Please provide details about what platform you are using (operating system, architecture).Thanks!

**Comment by 372046933** [comment]
@ravikyram . Steps 

1. `./configure` (all default)
2.  `bazel build --jobs=4 --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`
Then build fails. Operation system is the same as `tensorflow/tensorflow:latest-devel-gpu-py3` which is Ubuntu 18.04 64bit.

**Comment by mihaimaruseac** [comment]
Can you sync back to master and try again? Also, please post the commit hash at which you are trying to build.

Is this a regression? Was there a moment where you were able to build using these steps?

PS: You should not need `--config=cuda` if you set CUDA related things in `./configure`

**Comment by 372046933** [comment]
I have tried many times on latest master up to `566c03a749`. I built successfully once a long time ago. But I did `bazel clean` after that. Also tried removing `--config=cuda`, still failed with the same reason.

**Comment by amahendrakar** [comment]
@372046933,
Is this still an issue?

Could you please update TensorFlow to v2.4.1 and let us know if you are facing the same error. Thanks!

**Comment by 372046933** [comment]
Sorry, I cannot verify v2.4.1 due to insufficient disk space.

**Comment by amahendrakar** [comment]
@372046933,
Thank you for the update. 

Can we close this issue for now? Please feel free to re-open if you face the same error with TF v2.4.1 as well.

**Comment by 372046933** [comment]
Thanks
