### ISSUE TITLE
tf.data.experimental.ignore_errors: failed assertions are not logged

### ISSUE THREAD

**Issue by Andreas5739738** [tensorflow/tensorflow#38078]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Colab
- TensorFlow installed from (source or
binary): binary (colab)
- TensorFlow version (use command below): v2.2.0-rc1-0-gacf4951a2f 2.2.0-rc1
- Python version: 3.6.9

**Describe the current behavior**

No log output is emitted if an assertion fails in a dataset pipeline to which ignore_errors has been applied. While this technically matches the description of "silently" ignoring errors, this omission limits the usefulness of ignore_errors severely. It cannot be safely applied without the risk of hiding important errors.

**Describe the expected behavior**

Log output is emitted to stderr (visible in colab-jupyter.log).

**Standalone code to reproduce the issue** 

https://colab.research.google.com/gist/Andreas5739738/af7aec733d0190d41aac25c1a062fe1f/ignore_errors.ipynb#scrollTo=pve9Y2tPUDZT

**Other info / logs**
colab-jupyter.log shows no failed assertions:
```
Mar 31, 2020, 5:57:43 PM | WARNING | 2020-03-31 15:57:43.548945: I tensorflow/compiler/xla/service/service.cc:176] StreamExecutor device (0): Host, Default Version
-- | -- | --
Mar 31, 2020, 5:57:43 PM | WARNING | 2020-03-31 15:57:43.548902: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2371640 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
Mar 31, 2020, 5:57:43 PM | WARNING | 2020-03-31 15:57:43.548153: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2300000000 Hz
Mar 31, 2020, 5:57:43 PM | WARNING | 2020-03-31 15:57:43.497196: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ae332d19dc9b): /proc/driver/nvidia/version does not exist
Mar 31, 2020, 5:57:43 PM | WARNING | 2020-03-31 15:57:43.497116: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Mar 31, 2020, 5:57:43 PM | WARNING | 2020-03-31 15:57:43.450050: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
Mar 31, 2020, 5:57:41 PM | WARNING | 2020-03-31 15:57:41.766459: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Mar 31, 2020, 5:57:37 PM | INFO | Adapting to protocol v5.1 for kernel 4e9e6601-f865-41ac-ab32-8a4df7fd32b8
Mar 31, 2020, 5:57:35 PM | INFO | Kernel started: 4e9e6601-f865-41ac-ab32-8a4df7fd32b8
Mar 31, 2020, 5:33:10 PM | INFO | Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Mar 31, 2020, 5:33:10 PM | INFO | http://172.28.0.2:9000/
Mar 31, 2020, 5:33:10 PM | INFO | The Jupyter Notebook is running at:
Mar 31, 2020, 5:33:10 PM | INFO | 0 active kernels
Mar 31, 2020, 5:33:10 PM | INFO | Serving notebooks from local directory: /
Mar 31, 2020, 5:33:10 PM | INFO | google.colab serverextension initialized.
Mar 31, 2020, 5:33:10 PM | INFO | Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
Mar 31, 2020, 5:33:09 PM | WARNING | warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
Mar 31, 2020, 5:33:09 PM | WARNING | /usr/local/lib/python2.7/dist-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.```

**Comment by simmalik** [comment]
I can work on this with @shahshriya as well!

**Comment by Saduf2019** [comment]
i have replicated the issue, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/6de879c5a16c1a0b0a205074b395cd29/38078.ipynb#scrollTo=Qbupa8rr-OPh)

**Comment by jsimsa** [comment]
I think this works as intended. You either want to ignore errors (in which case you use this API) or you don't.

**Comment by jsimsa** [comment]
Can you please describe the use case where you want to use this API and at the same time you do not want to "ignore" the errors?

**Comment by Andreas5739738** [comment]
I think the common use case of ignore_errors is to be robust towards things like some examples not conforming to assumptions, or random data access errors/corruption occuring when loading from unreliable distributed storage systems. You don't want to kill training in such a case. But you also don't want to be oblivious of any such things occuring during training. Ideal would be to store metrics of failures. Logging to stderr would be a simple alternative that would already be very valuable.

I think a better name to reflect a useful error handling mechanism would be something like "skip_errors", instead of "ignore_errors". Silently ignoring errors is something that is rarely if ever useful (see the infamous "try: except: pass" antipattern in Python).

**Comment by jsimsa** [comment]
Logging the error makes sense. I would be happy to review a contribution that adds an option `log_warning` option for `ignore_errors` that controls whether the error is logged.
