### ISSUE TITLE
INT8 quantized model for TF Lite

### ISSUE THREAD

**Issue by noticebo** [tensorflow/tensorflow#38071]
Hi, I tried to run INT8 model on my device with TFLite but it seems its inference time is very slow and maybe it could only be run on CPU. While I run UINT8 model, it is very fast. How should I do so that it could be run normally for INT8 model? I noticed that there is an option for convert F16 to F32 by using "setAllowFp16PrecisionForFp32". is there any similar setting to convert INT8 to UINT8? thanks.

**Comment by gadagashwini** [comment]
@noticebo, Can you provide the standalone code to reproduce the issue. Thanks!

**Comment by gadagashwini** [comment]
@noticebo,Please provide the complete code to reproduce the issue. Thanks

**Comment by noticebo** [comment]
hi. due to company information limit, I could not provide the complete code.

**Comment by gadagashwini** [comment]
@noticebo, It will be difficult to trace the issue without code snippet. Can you create sample code and share with us.Thanks

**Comment by Saduf2019** [comment]
@noticebo,
please update on the above comment
