### ISSUE TITLE
/bin/sh: 1: python: not found error when generate projects

### ISSUE THREAD

**Issue by xiongyu0523** [tensorflow/tensorflow#38070]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., WSLv1 Ubuntu 18.04 ):
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source):  head
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): n/a

**Describe the problem**
**Please provide the exact sequence of commands/steps when you ran into the problem**

Python is 3.6.9

After clone a fresh repo, run command:
```make -f tensorflow/lite/micro/tools/make/Makefile TAGS=cmsis-nn generate_projects```

Reported error:
```/bin/sh: 1: python: not found
tensorflow/lite/micro/examples/person_detection_experimental/Makefile.inc:55: recipe for target 'tensorflow/lite/micro/
tools/make/gen/linux_x86_64/prj/person_detection_test_int8/keil/keil_project.uvprojx' failed
make: *** [tensorflow/lite/micro/tools/make/gen/linux_x86_64/prj/person_detection_test_int8/keil/keil_project.uvprojx]
Error 127```

**Comment by SunBeenMoon** [comment]
Hi @xiongyu0523 
I have the same issue. 
Did you fix it?

**Comment by Saduf2019** [comment]
@xiongyu0523 
As we have the latest stable version 2.6.0, Can you try building TF 2.6.0 or any latest 2.x version and let us know if this is still an issue.
