### ISSUE TITLE
Allow users to specify method name when using tf.saved_model.save

### ISSUE THREAD

**Issue by faustomorales** [tensorflow/tensorflow#38081]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.1.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Today, the `tf.saved_model.save` API does not allow users to specify a method name to use for a model signature. Instead, the method name is always `'tensorflow/serving/predict'`, because of the following line.

https://github.com/tensorflow/tensorflow/blob/e5bf8de410005de06a7ff5393fafdf832ef1d4ad/tensorflow/python/saved_model/save.py#L462

In my case, this is particularly troublesome because I wish to use the TensorFlow Serving `classify` API which returns arrays of the form `(batch_size, classes, 2)` where the first entry is always a class name (string) and the second entry is a score (float). TensorFlow Serving seems to require that method name be `'tensorflow/serving/classify'`.

**Will this change the current API? How?**

Yes, but I think it could be done without breaking existing functionality if we add another format option for the `signatures` argument to `tf.saved_model.save` that allows the user to supply a method name.

**Who will benefit with this feature?**

Anyone wanting to use something other than the `predict` API in TensorFlow serving.

**Any Other info.**

For now, I work around this issue with the following function, which implements a hack to get the desired method name saved.

```python
import typing

import tensorflow as tf
from tensorflow import python as tfp

def save_serving_model(export_dir: str, model: tf.keras.Model,
                       classes: typing.List[str]):
    """Obtain a TensorFlow Serving function that can be used with
    `tf.saved_models.save`

    Args:
        export_dir: The directory in which to export the saved model.
        model: A classification model
        classes: The list of classification labels
    """

    @tf.function(
        input_signature=[tf.TensorSpec(shape=[None], dtype=tf.string)])
    def serve(inputs):
        def map_fn(image):
            image = tf.io.decode_image(
                image['image'], channels=3, expand_animations=False)
            image = tf.cast(image, dtype=tf.float32)
            image = tf.compat.v1.image.resize_image_with_pad(
                image=image,
                target_height=model.input_shape[1],
                target_width=model.input_shape[2],
                align_corners=False,
                method=tf.image.ResizeMethod.BILINEAR)
            return image

        images = tf.io.parse_example(
            inputs,
            features={
                'image': tf.io.FixedLenFeature(shape=[], dtype=tf.string)
            },
            example_names=None,
            name=None)
        X = tf.map_fn(
            fn=map_fn, elems=images, back_prop=False, dtype=tf.float32)
        y = model.call(X)
        labels = tf.constant([classes])
        return {
            'scores': y,
            'classes': tf.repeat(
                labels, repeats=tf.shape(y)[0], axis=0, name=None)
        }

    # This is a super-ugly hack, but we have to do it because for
    # the API does not allow us to specify a method name. See:
    # https://github.com/tensorflow/tensorflow/blob/e5bf8de410005de06a7ff5393fafdf832ef1d4ad/tensorflow/python/saved_model/save.py#L462
    try:
        PREDICT_METHOD_NAME = tfp.saved_model.signature_constants.PREDICT_METHOD_NAME
        tfp.saved_model.signature_constants.PREDICT_METHOD_NAME = tf.saved_model.CLASSIFY_METHOD_NAME  # pylint: disable=line-too-long
        tf.saved_model.save(
            model,
            export_dir,
            signatures={
                tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY:
                serve.get_concrete_function()
            })
    finally:
        tfp.saved_model.signature_constants.PREDICT_METHOD_NAME = PREDICT_METHOD_NAME

```

One can use this function with a Keras model in the following manner.

```python
import tensorflow as tf

inputs = tf.keras.layers.Input((100, 100, 3))
x = tf.keras.layers.Conv2D(kernel_size=(2, 2), filters=3)(inputs)
x = tf.keras.layers.GlobalAveragePooling2D()(x)
outputs = tf.keras.layers.Activation('softmax')(x)
model = tf.keras.models.Model(inputs=inputs, outputs=outputs)

save_serving_model(export_dir='export', model=model, classes=['class1', 'class2', 'class3'])
```
I can run the model with TensorFlow Serving using:

```bash
docker run -it --rm -p 8501:8501 -v "$PWD/export:/models/testmodel/1" -e MODEL_NAME=testmodel tensorflow/serving
```

And I can make requests to the model using 

```python
import requests
import glob

with open('../tests/images/image1.jpg', 'rb') as f:
    examples = [{
        'image': {
            'b64': base64.b64encode(f.read()).decode('utf-8')
        }
    }]
response = requests.post(
    'http://host.docker.internal:8501/v1/models/testmodel:classify',
    json={
        'examples': examples
    }
).json()
print(response['results'])
```

This yields the following response:

```
[[['class1', 0.0], ['class2', 1.0], ['class3', 0.0]]]
```

*IMPORTANT:* If I'm mistaken on how this all works or is supposed to work, please do let me know. this is just what I was able to put together when transitioning to 2.x.

**Comment by simmalik** [comment]
I can also work on this issue!

**Comment by simmalik** [comment]
I can also work on this one with @shahshriya

**Comment by iainwo** [comment]
Thanks @faustomorales for opening the thread - it helped me a lot.

For others, that are using a higher version of TF (where tf.python is no longer exported) here is what I did to get around the limitation:

```python
   import tensorflow as tf

    # TFX Trainer or TF stuff to create model
    signatures = { ... }
    model.save(serving_model_dir, save_format="tf", signatures=signatures)

    # workaround
    import os
    import inspect
    import imp
    TFX_PATH = inspect.getsourcefile(tf).replace("__init__.py", "")
    SAVE_PATH = os.path.join(TFX_PATH, "python/saved_model/method_name_updater.py")
    tfp = imp.load_module("tfp", None, SAVE_PATH, ("", "", 5))
    mnp = tfp.MethodNameUpdater(serving_model_dir)

    # configure as many method names as you want
    mnp.replace_method_name("serving_default", tf.saved_model.CLASSIFY_METHOD_NAME)
    mnp.save()
```

Afterwards was able to call the rest classify endpoint and get a result.
