### ISSUE TITLE
Trying to convert: RuntTimeError: MetaGraphDef associated with tags {'serve'} could not be found in SavedModel.

### ISSUE THREAD

**Issue by csongornagy** [tensorflow/tensorflow#38080]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 
- TensorFlow installed from (source or binary): anaconda installation
- TensorFlow version (or github SHA if from source): 1.15

**The output from the converter invocation**

```
MetaGraphDef associated with tags {'serve'} could not be found in SavedModel.
```

**Also, please include a link to the saved model or GraphDef**

```
https://drive.google.com/open?id=1fI36hxl9vbIY9KL4Tjvv7HIIBJvYIfW5
```

**Any other info / logs**

When I try to convert this is the error I get, so I cannot successfully convert to Lite.

**Comment by gadagashwini** [comment]
@csongornagy, Can you please share a standalone code to reproduce the issue? Thanks!

**Comment by csongornagy** [comment]
> @csongornagy, Can you please share a standalone code to reproduce the issue? Thanks!
Yeah, so this is the code I am using, the official code from the tensorflow website:
https://www.tensorflow.org/lite/guide/get_started
(I have also tried the quntized version of the code, still the same error)

```
import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```

**Comment by raghavgurbaxani** [comment]
I am also getting the same error during TFlite conversion. Any update on this ?

**Comment by csongornagy** [comment]
@raghavgurbaxani No unfortunately I have not been able to resolve issue, and have not received any further updates from tensorflow either.
@jvishnuvardhan Any response?

**Comment by jvishnuvardhan** [comment]
@csongornagy Is this a frozen graph file? If it is frozen graph, then you need to provide 'input_arrays' and 'output_arrays'. Do you have access to model creation code? Can you provide 'input_arrays' and 'output_arrays'. Thanks!

**Comment by raghavgurbaxani** [comment]
@jvishnuvardhan 
using the frozen .pb file from here - https://github.com/argman/EAST/issues/296

but I get the following error. -
```
RuntimeError: MetaGraphDef associated with tags {'serve'} could not be found in SavedModel. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
available_tags: [set()]
```

looks like the tag set is empty.

**Comment by csongornagy** [comment]
> @csongornagy Is this a frozen graph file? If it is frozen graph, then you need to provide 'input_arrays' and 'output_arrays'. Do you have access to model creation code? Can you provide 'input_arrays' and 'output_arrays'. Thanks!

@jvishnuvardhan 
Thanks for the reply! Yes it is a frozen graph model! I don't know how I can acquire the input and output arrays as you said. Where could I get these from? or How? This the code use to export the model:
```
import re
import numpy as np

output_directory = './fine_tuned_model'

lst = os.listdir(model_dir)
lst = [l for l in lst if 'model.ckpt-' in l and '.meta' in l]
steps=np.array([int(re.findall('\d+', l)[0]) for l in lst])
last_model = lst[steps.argmax()].replace('.meta', '')

last_model_path = os.path.join(model_dir, last_model)
print(last_model_path)
!python /content/models/research/object_detection/export_inference_graph.py \
    --input_type=image_tensor \
    --pipeline_config_path={pipeline_fname} \
    --output_directory={output_directory} \
    --trained_checkpoint_prefix={last_model_path}
```

**Comment by giorgiomondauto** [comment]
Any updates on this issue?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
