### ISSUE TITLE
Linking tensorflow/python/_pywrap_tensorflow_internal.so failed on debug build on Windows

### ISSUE THREAD

**Issue by vnvo2409** [tensorflow/tensorflow#38084]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): source 
- TensorFlow version: r2.2
- Python version: 3.7
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 2.0
- GCC/Compiler version (if compiling from source): MSVC 19

**Describe the problem**
When build debug tensorflow on Windows. Bazel get stuck at linking tensorflow/python/_pywrap_tensorflow_internal.so. it generate a `_pywrap_tensorflow_internal.pdb` about 4,7 GB. After that, it throw an error [LNK1201](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1201?view=vs-2019) `error writing to program database 'filename'; check for insufficient disk space, invalid path, or insufficient privilege`. In addition, Microsoft Incremental Linker consume 87% of my 32 GB Ram

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I just run the command 
`bazel build --config=opt -c dbg --jobs=8 //tensorflow/tools/pip_package:build_pip_package`

**Any other info / logs**
In fact, I try to build a debug version of tensorflow to resolve an issue [here](https://github.com/tensorflow/tensorflow/issues/19297). I think I only need to build the infrastructure (file system) part of tensorflow and not the logical part. Is there anyways to reduce the overall size of tensorflow ( With me, I do not need the tensorflow::ops for example )

**Comment by mihaimaruseac** [comment]
I think we never tried to build with debug symbols on Windows

**Comment by vnvo2409** [comment]
Is there a way to build `py_binary` with debug symbols on Windows for bazel ?

**Comment by mihaimaruseac** [comment]
I think you can try building only that `py_binary`, instead of the entire pip package. But since we never ran debug builds on Python, that might also fail. In which case, TFDBG and printf-style debugging could be the only alternatives.

**Comment by Saduf2019** [comment]
@vnvo2409 
please update as per above comment

**Comment by vnvo2409** [comment]
I find a way to use printf in debug so I wil close this issue
