### ISSUE TITLE
Tensorboard does not show the curves

### ISSUE THREAD

**Issue by OrielResearchCure** [tensorflow/tensorflow#38086]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

Hello, 
I am using gcloud ai-platform jobs submit training to submit my training. parameters are:
```
gcloud ai-platform jobs submit training $JOB_NAME \
        --stream-logs \
        --runtime-version=2.1 \
        --job-dir=$JOB_DIR \
        --package-path=trainer \
        --module-name=trainer.task \
        --region=us-east1 \
        --python-version=3.5 \
        --scale-tier=basic
```

I am using tensorflow keras to build the model and compile it. adding the following metrics:
```
METRICS = [keras.metrics.TruePositives(name='tp'), \
           keras.metrics.FalsePositives(name='fp'), \
           keras.metrics.TrueNegatives(name='tn'), \
           keras.metrics.FalseNegatives(name='fn'), \
           keras.metrics.BinaryAccuracy(name='accuracy'), \
           keras.metrics.Precision(name='precision'), \
           keras.metrics.Recall(name='recall'), \
           keras.metrics.AUC(name='auc'), \
          ]
# this is the call in the task.py (ai-platform format)
executed_model = model.make_model(input_shape,METRICS,model_choice = 5)

The following code adds the tensorboard callbacks and LambdaCallbacks:
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=LOG_DIR, \
                                                        histogram_freq=1, \
                                                        write_graph=True, \
                                                        write_images=True, \
                                                        write_grads = True, \
                                                        update_freq='batch')
  # writer for each one of the CM
  file_writer_cm_train = tf.summary.create_file_writer(cm_dir_train)
  file_writer_cm_valid = tf.summary.create_file_writer(cm_dir_valid)
  file_writer_cm_test = tf.summary.create_file_writer(cm_dir_test)

def log_confusion_matrix_train(epoch,logs): 
    train_gen_bias.reset()
    train_predictions_bias = executed_model.predict_generator(train_gen_bias, verbose=1)
    for name, value in zip(executed_model.metrics_names, train_predictions_bias):
      print(name, ": ",value)
    print()
  
    save_model_param = dict(zip(executed_model.metrics_names, train_predictions_bias))
    dataset = timestr+"-train"
    saveModel(DISEASE_FOLDER,dataset,save_model_param,executed_model)

    p=0.5
    train_pred = [int(x>p) for x in train_predictions_bias]
    train_labels_int = [CLASSES.index(x) for x in  train_labels] # train_labels is a global parameter
    # Calculate the confusion matrix.
    cm = sklearn.metrics.confusion_matrix(train_labels_int,train_pred)
    print('cm for training is ',cm)
    # Log the confusion matrix as an image summary.
    figure = plot_confusion_matrix(cm, CLASSES)
    cm_image = plot_to_image(figure)
    # Log the confusion matrix as an image summary.
    with file_writer_cm_train.as_default():
      tf.summary.image("Confusion Matrix for training dataset", cm_image, step='epoch')

 # Define the per-epoch callback.
  cm_callback_train = keras.callbacks.LambdaCallback(on_epoch_end=log_confusion_matrix_train)
  cm_callback_valid = keras.callbacks.LambdaCallback(on_epoch_end=log_confusion_matrix_valid) # the same like log_confusion_matrix_valid, just different dataset
  cm_callback_test = keras.callbacks.LambdaCallback(on_epoch_end=log_confusion_matrix_test)
# Define the per-batch callback.
  batch_print_callback = keras.callbacks.LambdaCallback(on_batch_begin=lambda batch,logs: \
                                                        print('from callback, batch {} begins'.format(batch))) 

#fit model
 history_executed_mode = executed_model.fit(train_gen, \
                                             steps_per_epoch = STEPS_PER_EPOCH, \
                                             epochs = EPOCHS, \
                                             validation_data = validation_gen, \
                                             validation_steps = VALIDATION_STEPS, \
                                             class_weight=class_weight, \
                                             callbacks=[tensorboard_callback, \
                                                        cm_callback_train, \
                                                        cm_callback_valid, \
                                                        cm_callback_test, \
                                                        batch_print_callback])

```
The execution is completed successfuly. 
I can see that log_confusion_matrix_train is running and generating a file with the metrics that I was checking for the training, validation and test dataset. The only issue is that tensorboard is showing black boxes for the scalar metric (See attached - the tab is called events) while hovering on them, I see numbers and the image tab is empty 
![Screen Shot 2020-03-31 at 1 39 19 PM](https://user-images.githubusercontent.com/30246246/78058604-8db43280-7356-11ea-9a84-ec5bdc1f28ae.png)
![Screen Shot 2020-03-31 at 1 39 33 PM](https://user-images.githubusercontent.com/30246246/78058606-8e4cc900-7356-11ea-8d8c-40570a042971.png)
I run the tensorboard from the google shell.

My questions are:
what is wrong with the way I am producing the metrics?
Do I need three writer for the three confusion matrix?
why is the first tab called events and not scalars?

![Screen Shot 2020-03-31 at 1 52 16 PM](https://user-images.githubusercontent.com/30246246/78058840-e388da80-7356-11ea-94be-b6ce5a79af6b.png)

**Comment by OrielResearchCure** [comment]
Many thanks for any advice!
this tutorial was used for a guideline for the CM as well: https://www.tensorflow.org/tensorboard/image_summaries
Thanks!

**Comment by OrielResearchCure** [comment]
copying to datalab notebook with tensorboard 1.14, I was able to get the scalars but not the confusion matrix images. 
```
from tensorboard import version; print(version.VERSION)
1.14.0a20190603
```

code for confusion matrix is taken from https://www.tensorflow.org/tensorboard/image_summaries 

Will keep on trying and will let you know, Please let me know if you have any idea how to proceed.
Thanks,
eilalan

**Comment by nfelt** [comment]
If the first tab is called `Events` you are using a very old version of TensorBoard (several years old).  You'll want to ensure you are on a recent version of TensorBoard, ideally 1.15 or newer.

If you're still encountering an issue when using a newer version of TensorBoard, please open an issue in the TensorBoard repository at https://github.com/tensorflow/tensorboard/issues/new/choose and provide the requested diagnostic information.
