### ISSUE TITLE
when i use tf.contrib.lite.Interpreter(model_path="xxxx.lite") 

### ISSUE THREAD

**Issue by sibadakesi** [tensorflow/tensorflow#38098]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
tf.contrib.lite.Interpreter(model_path="XXXX.lite")
interpreter.allocate_tensors()
```

**The output from the converter invocation**

```
return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_InputIndices(self)
ValueError: Interpreter was not initialized.
```

**Failure details**
when i use ```converter.convert()``` without  ```converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE] ``` it works. But i use converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE],it appears the error.
this model is from torch‘s to tensorflow.May be related to this

**Comment by ravikyram** [comment]
@sibadakesi 

Can you please let us know which Tensorflow version you are using? .Also, request you to share simple standalone code with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by sibadakesi** [comment]
Thinks，i use the higher Tensorflow version(1.15.0) it works. I realized if i  quantizing this torch‘s models  i must use than or equal 1.15.0 version of Tensorflow.

**Comment by ravikyram** [comment]
@sibadakesi 

Glad to know that worked with Latest versions.Please close this thread if it solves your question. Thanks!.

**Comment by sibadakesi** [comment]
think you
