### ISSUE TITLE
How to create a custom distribution strategy on Tensorflow

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#38097]
I know this question should be asked on Stackoverflow. But it seems that no one has the courage to answer [this](https://stackoverflow.com/questions/57852705/how-to-create-a-custom-distribution-strategy-on-tensorflow) question for half an year. So I'm trying some luck on the github, hoping there are someone who has the expertise that could give some instructions on how to realize the model parallelism strategy, specifically the communication part among different jobs?

**Comment by amahendrakar** [comment]
@sjtusmartboy,
Could you please take a look at [this](https://www.tensorflow.org/guide/distributed_training) official TensorFlow guide for distributed training and the [overview](https://www.tensorflow.org/api_docs/python/tf/distribute) for tf.distribute and let us know it helps? Thanks!

**Comment by sjtusmartboy** [comment]
@amahendrakar Thank you for your materials. I've checked these materials and find they teach user how to use the distribution strategies, including MirroredStrategy, TPUStrategy ... Is there any docs showing the architecture of these strategies, and how they are implemented?

**Comment by amahendrakar** [comment]
@sjtusmartboy,
To know more about the architecture of these APIs you can check out their respective source code on GitHub.

Implementation details can be found [here](https://www.tensorflow.org/guide/distributed_training#examples_and_tutorials_2) under the 'Examples and Tutorials' section. 

Thanks!

**Comment by amahendrakar** [comment]
Is this still an issue? Please feel free to close the issue if resolved. Thanks!

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by stefan-falk** [comment]
Could be related to https://github.com/tensorflow/tensorflow/issues/52197
