### ISSUE TITLE
Information about Keras Tuner is missing in tensorflow.org website

### ISSUE THREAD

**Issue by rakeshmothukuru1** [tensorflow/tensorflow#38105]
## URL(s) with the issue: 
https://youtu.be/aNrqaOAt5P4?list=PLQY2H8rRoyvzuJw20FG82Lgm2SZjTdIXU&t=660

## Description of issue (what needs changing): 
In the [TF Dev Summit 2020](https://youtu.be/aNrqaOAt5P4?list=PLQY2H8rRoyvzuJw20FG82Lgm2SZjTdIXU&t=660
), Paige Bailey has talked about **Keras Tuner** and has shown its implementation. I liked the functionality but I couldn't information/documentation about it in [tensorflow.org site](https://www.tensorflow.org/).

### Clear description: 
This being a New Functionality, the documentation about that functionality in the Website would help the Community.

### Correct links

Is the link to the source code correct? : N/A

### Parameters defined

Are all parameters defined and formatted correctly?: N/A

### Returns defined

Are return values defined? : N/A

### Raises listed and defined

Are the errors defined? : N/A

### Usage example

Is there a usage example? N/A

**Comment by amahendrakar** [comment]
@rakeshmothukuru1,
[This TensorFlow Blog post](https://blog.tensorflow.org/2020/01/hyperparameter-tuning-with-keras-tuner.html) about Keras Tuner points to the official [GitHub repo](https://github.com/keras-team/keras-tuner), which has the link to the [Keras Tuner documentation](https://keras-team.github.io/keras-tuner/). 
Could you please check these link and let us know if it helps? Thanks!

**Comment by rakeshmothukuru1** [comment]
@amahendrakar ,
 In my opinion, it will be better to add the documentation in Tensorflow.org site because many people refer that site rather than many different sites. If this Functionality has to be used along with Tensorflow, then its documentation should be present in the Official Tensorflow Website.

**Comment by gowthamkpr** [comment]
@rakeshmothukuru1 Keras tuner is a separate package that is not integrated in tensorflow but we can use it by installing and importing it. So, that might be the reason why its not included in tensorflow.org

**Comment by MarkDaoust** [comment]
@anirudh161 is working on this.

**Comment by abhinavsp0730** [comment]
I've also submitted my GSOC proposal about making End-to-End example covering all the use cases of keras tuner , I don't know someone already is working in these. Nevertheless even if it'll not get selected, I'll try to make colab example and will contribute into tensorflow community example.

**Comment by MarkDaoust** [comment]
We have an example on the site now: https://www.tensorflow.org/tutorials/keras/keras_tuner
