### ISSUE TITLE
How to build op in tensorflow's static graph for unknown rank tensor

### ISSUE THREAD

**Issue by MachineJeff** [tensorflow/tensorflow#38101]
## Problem 1
```python
tensor a = [1,2,3,4]
```
I want to split it into:
```python
b1 = [1] 
b2 = [2] 
b3 = [3] 
b4 = [4]
```
However, if the tensor's shape is None, such as
```python
a = tf.placeholder(tf.float32, [1, None], "a")
```
How to build this **op** in tensorflow's static graph?

## Problem 2
In addition，
```python
tensor x = [1,2,3,4]
```
I want to build a series tensor based on `tensor x`:
```python
x1 = [1]
x2 = [1,1]
x3 = [1,1,1]
x4 = [1,1,1,1]
```
Just the same as the Problem 1, if the tensor's shape is None, how to build this *op* in tensorflow's static graph?

**Comment by amahendrakar** [comment]
@MachineJeff,
Could you please check out the [tf.split](https://www.tensorflow.org/api_docs/python/tf/split) function and let us know if it helps? 

Attached [gist](https://colab.research.google.com/gist/amahendrakar/605e97853dfa61458a334e75e4129ae8/38101.ipynb) for reference. Thanks!

**Comment by MachineJeff** [comment]
@amahendrakar,
**tf.split** No it does not work.

**Comment by MachineJeff** [comment]
@amahendrakar 
I have done it using tf.while_loop() 
Thanks.

**Comment by jiujiuxia** [comment]
@MachineJeff can you share how to deal with it?
thanks!!!

**Comment by MachineJeff** [comment]
@jiujiuxia You can check the usage of tf.while_loop(), it can solve both the two problems.
