### ISSUE TITLE
implicit conversion from 'int' to 'float' changes value from INT_MAX to INT_MAX+1

### ISSUE THREAD

**Issue by dauras** [tensorflow/tensorflow#38106]
Clang warns

```
tensorflow/lite/micro/micro_utils.cc:108:19: warning: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Wimplicit-int-float-conversion]
  if (quantized > INT_MAX) {
                ~ ^~~~~~~
```
about this code
https://github.com/tensorflow/tensorflow/blob/bda5ba03da606b0d41fa3282de0108c3e98cff8e/tensorflow/lite/micro/micro_utils.cc#L106-L115

So, if `round(value/scale)` ever happens to be INT_MAX+1, it is not saturated as intended, instead has undefined wrap-around behavior (overflow is undefined for signed int,).

**Comment by rthadur** [comment]
This specified file has been moved to tensorflow/tflite-micro, and also method you are referring has been moved/removed. Thank you
