### ISSUE TITLE
custom training logic in subclassing model not saved

### ISSUE THREAD

**Issue by quetil** [tensorflow/tensorflow#38103]
**System information** 
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g.,Linux Ubuntu 16.04): Google Colab (Windows/Linux as well)
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): TensorFlow 2.2.0RC2
- Python version: 3.7

**Describe the current behavior**
Hi all,
I'm using the 2.2 new feature: custom training logic with Model.fit by overriding Model.train_step. It's working well so far. I have the following issue (maybe it's not a feature, you'll tell me):
When I save my model (Model.save) with the custom training logic and then I want to load it, the custom training loop is not saved and when I apply a Model.fit for my loaded model, it comes back to the default one.

**Describe the expected behavior**
I'd expect to save as well the model.train_step (and also test_step and predict_step).

**Standalone code to reproduce the issue** 
[Gist](https://colab.research.google.com/gist/quetil/5e92fb9af7cc959f8fe62f1090ef31e7/custom-train_step-in-subclassing-model.ipynb)

**Others**
Can we expect in the future that the whole class will be saved? (Even variables declared in the `__init__` for instance).

Thank you in advance :-)

**Comment by Saduf2019** [comment]
@quetil 
I have executed the code shared by you and get different error please refer to [this gist](https://colab.sandbox.google.com/gist/Saduf2019/936ac77698c63786e9c563e07da7797e/untitled121.ipynb).

with respect to the error faced there is a similar resolved issue please refer to this [comment](https://github.com/tensorflow/tensorflow/issues/37141#issuecomment-592737155)  and let us know if it helps.
#27949 [link1](https://stackoverflow.com/questions/41689451/valueerror-no-gradients-provided-for-any-variable) [link2](https://en.dev4app.com/archives/51966406-no-gradients-provided-for-any-variable-check-your-graph-for-ops-that-do-not-support-gradients.html)

**Comment by quetil** [comment]
Hi @Saduf2019, thanks for the quick reply.

Please refer to [this new gist](https://colab.research.google.com/gist/quetil/5e92fb9af7cc959f8fe62f1090ef31e7/custom-train_step-in-subclassing-model.ipynb). I used the last tf-nigthly. The train_step is not saved and once loaded, it's using the default train_step.

Thanks

**Comment by Saduf2019** [comment]
i have replicated the issue reported as per gist shared above, please find the [gist here](https://colab.sandbox.google.com/drive/1K28D5mcVCiFrTwXXDopYU38ZJrEt6JNx#scrollTo=fliohxc90O-p)

**Comment by Saduf2019** [comment]
please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/37b047e54f8caa63fb8064e8f11b9f33/untitled122.ipynb)

**Comment by quetil** [comment]
Any news about such feature?
Planned in TF 2.4 ? :-)

**Comment by k-w-w** [comment]
Currently we do not plan to add this, if you want to retain the train_step function, decorate it with `@tf.function(input_signature=...)`

**Comment by jscant** [comment]
@k-w-w Decorating with `@tf.function(input_signature=...)` presents its own problems:

```import numpy as np
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.python.eager import backprop

class TestModel(tf.keras.models.Model):

    def __init__(self):
        super().__init__()
        self.x = layers.Input((10,))
        self.output_ = layers.Dense(1)

    def call(self, inputs):
        return self.output_(inputs)

    @tf.function(
        input_signature=[(tf.TensorSpec(shape=(None, 10), dtype=tf.float32),
                          tf.TensorSpec(shape=(None, 1), dtype=tf.int64))])
    def train_step(self, data):
        tf.print('Flag')
        x, y = data
        with backprop.GradientTape() as tape:
            y_pred = self(x, training=True)
            loss = self.compiled_loss(
                y, y_pred, regularization_losses=self.losses)
        self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
        self.compiled_metrics.update_state(y, y_pred)
        return {m.name: m.result() for m in self.metrics}

    def get_config(self):
        config = super().get_config()
        config.update({'train_step': self.train_step})
        return config

original_model = TestModel()
original_model.compile(loss='mse', optimizer='sgd')

for i in range(3):
    original_model.train_on_batch(np.random.rand(6, 10), np.arange(6))
    print('Completed train loop (original model)')

save_path = 'tmp'
original_model.save(save_path)

loaded_model = tf.keras.models.load_model(save_path)

for i in range(3):
    loaded_model.train_on_batch(np.random.rand(6, 10), np.arange(6))
    print('Completed train loop (loaded model)')```

Gives:

```import numpy as np
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.python.eager import backprop


class TestModel(tf.keras.models.Model):

    def __init__(self):
        super().__init__()
        self.x = layers.Input((10,))
        self.output_ = layers.Dense(1)

    def call(self, inputs):
        return self.output_(inputs)

    @tf.function(
        input_signature=[(tf.TensorSpec(shape=(None, 10), dtype=tf.float32),
                          tf.TensorSpec(shape=(None, 1), dtype=tf.int64))])
    def train_step(self, data):
        tf.print('Flag')
        x, y = data
        with backprop.GradientTape() as tape:
            y_pred = self(x, training=True)
            loss = self.compiled_loss(
                y, y_pred, regularization_losses=self.losses)
        self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
        self.compiled_metrics.update_state(y, y_pred)
        return {m.name: m.result() for m in self.metrics}

    def get_config(self):
        config = super().get_config()
        config.update({'train_step': self.train_step})
        return config


original_model = TestModel()
original_model.compile(loss='mse', optimizer='sgd')

for i in range(3):
    original_model.train_on_batch(np.random.rand(6, 10), np.arange(6))
    print('Completed train loop (original model)')

save_path = 'tmp'
original_model.save(save_path)

loaded_model = tf.keras.models.load_model(save_path)

for i in range(3):
    loaded_model.train_on_batch(np.random.rand(6, 10), np.arange(6))
    print('Completed train loop (loaded model)')```

If you take out the second part of the signature:

``` @tf.function(
        input_signature=[(tf.TensorSpec(shape=(None, 10), dtype=tf.float32),
                          tf.TensorSpec(shape=(None, 1), dtype=tf.int64))])```

to

``` @tf.function(
        input_signature=[tf.TensorSpec(shape=(None, 10), dtype=tf.float32),
                         tf.TensorSpec(shape=(None, 1), dtype=tf.int64)])```

(get rid of a pair of parenthesis), we get:

```
TypeError: tf__train_step() takes 2 positional arguments but 3 were given
```

If we only pass the shape of the inputs (x) values:

```
@tf.function(
        input_signature=[
            tf.TensorSpec(shape=(None, 10), dtype=tf.float32)])
```

we get

```
TypeError: tf__train_step() missing 1 required positional argument: 'data'
```

And if we do not decorate, ```train_step``` is not serialised and so loaded models revert to the ```train_step``` of the base class.

There is not a lot of documentation on how to modify train_step such that it can be serialised. Am I getting the wrong end of the stick here?

**Comment by jscant** [comment]
I can now successfully run and save a model with a `@tf.function(input_signature=...)` decoration, but the model either doesn't serialise the custom `train_step` or doesn't load it properly:

```
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.python.eager import backprop


class TestModel(tf.keras.models.Model):

    def __init__(self):
        super().__init__()
        self.x = layers.Input((10,))
        self.output_ = layers.Dense(1)

    def call(self, inputs):
        return self.output_(inputs)

    @tf.function(input_signature=[tuple(((
            [tf.TensorSpec((None, 10), tf.float32),
             tf.TensorSpec((None,), tf.int64)])))])
    def train_step(self, data):
        tf.print('Flag')
        x, y = data
        with backprop.GradientTape() as tape:
            y_pred = self(x, training=True)
            loss = self.compiled_loss(
                y, y_pred, regularization_losses=self.losses)
        self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
        self.compiled_metrics.update_state(y, y_pred)
        return {m.name: m.result() for m in self.metrics}

    def get_config(self):
        config = super().get_config()
        config.update({'train_step': tf.function(self.train_step)})
        return config

tf.keras.models.Model.conf
original_model = TestModel()
original_model.compile(loss='mse', optimizer='sgd')

for i in range(3):
    original_model.train_on_batch(
        np.random.rand(6, 10), np.arange(6))
    print('Completed train loop (original model)')

save_path = 'tmp'
original_model.save(save_path)

loaded_model = tf.keras.models.load_model(save_path, compile=False)
loaded_model.compile(loss='mse', optimizer='sgd')

for i in range(3):
    loaded_model.train_on_batch(np.random.rand(6, 10), np.arange(6))
    print('Completed train loop (loaded model)')
```

This gives:

```
Completed train loop (original model)
Flag
Completed train loop (original model)
Flag
Completed train loop (original model)
<(LOADING INFORMATION)>
Completed train loop (loaded model)
Completed train loop (loaded model)
Completed train loop (loaded model)
```

How can we properly serialise vital methods like this?

**Comment by igorgad** [comment]
Hi @jscant 
I'm having the same problem but with a model with two inputs and one output only on the test_step. How would you rephrase the above input_signature? Should something like this work? 

`input_signature=[tuple((([(tf.TensorSpec((None, 224, 224, 3), tf.float32), tf.TensorSpec((None, 224, 224, 3), tf.float32)), tf.TensorSpec((None,), tf.int64)])))])`

Thanks

**Comment by quetil** [comment]
May I reopen this issue to ask the following question:

Does the new feature inside TF2.4 (the `tf.keras.Model.save(..., save_traces=True)`, with the `save_trace=True` argument), can be used to save the custom training logic (modifying the `train_step()` function and train the model with a model.fit, see initial post) ? If yes, how ?

Thank you in advance,
