### ISSUE TITLE
tensorflow1.15,  Here is a list of operators for which you will need custom implementations: ReorderAxes.RandomStandardNormal

### ISSUE THREAD

**Issue by fcqfcq** [tensorflow/tensorflow#38102]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04)  : ubuntu18.04
- TensorFlow installed from (source or binary):   conda
- TensorFlow version (or github SHA if from source): 1.15

**Provide the text output from tflite_convert**

```
# Copy and paste here

```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by fcqfcq** [comment]
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONV_2D, FLOOR_DIV, FULLY_CONNECTED, GATHER, LEAKY_RELU, MEAN, MUL, PACK, PAD, RESHAPE, RSQRT, SHAPE, SQUARE, STRIDED_SLICE, SUB, SUM, TILE, TRANSPOSE, TRANSPOSE_CONV. Here is a list of operators for which you will need custom implementations: ReorderAxes.

**Comment by fcqfcq** [comment]
converter = tf.lite.TFLiteConverter.from_saved_model(PATH)
    print(dir(converter))
    #converter.experimental_new_converter = True  ####
    #converter.allow_custom_ops = True
    
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_types = [tf.float16]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                           tf.lite.OpsSet.SELECT_TF_OPS]
    tflite_model = converter.convert()

**Comment by fcqfcq** [comment]
PATH  = './savedmodel'
    converter = tf.lite.TFLiteConverter.from_saved_model(PATH)
    print(dir(converter))
    #converter.experimental_new_converter = True  ####量化
    #converter.allow_custom_ops = True
    
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_types = [tf.float16]
#     converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
#                                            tf.lite.OpsSet.SELECT_TF_OPS]
    tflite_model = converter.convert()
    open("./model/andriod/lite/pkl2pt_G_synthesis/converted_model3.tflite", "wb").write(tflite_model)
    
conver()    



Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONV_2D, FLOOR_DIV, FULLY_CONNECTED, GATHER, LEAKY_RELU, MEAN, MUL, PACK, PAD, RESHAPE, RSQRT, SHAPE, SQUARE, STRIDED_SLICE, SUB, SUM, TILE, TRANSPOSE, TRANSPOSE_CONV. Here is a list of operators for which you will need custom implementations: RandomStandardNormal.

**Comment by ymodak** [comment]
Can you try enabling the custom_ops flag ?
`converter.allow_custom_ops = True`

**Comment by ravikyram** [comment]
@fcqfcq 

Any update on this issue please. Thanks!
