### ISSUE TITLE
Semantic search BERT model to TFLITE

### ISSUE THREAD

**Issue by ali9653** [tensorflow/tensorflow#38110]
0

I have this code for semantic search engine built using the pre-trained bert model. I want to convert this model into tflite for deploying it to google mlkit. I want to know how to convert it. I want to know if its even possible to convert this into tflite. It might be because its mentioned on the official tensorflow site :https://www.tensorflow.org/lite/convert. But I dont know where to begin

code:
```python
from sentence_transformers import SentenceTransformer

# Load the BERT model. Various models trained on Natural Language Inference (NLI) https://github.com/UKPLab/sentence-transformers/blob/master/docs/pretrained-models/nli-models.md and 
# Semantic Textual Similarity are available https://github.com/UKPLab/sentence-transformers/blob/master/docs/pretrained-models/sts-models.md

model = SentenceTransformer('bert-base-nli-mean-tokens')

# A corpus is a list with documents split by sentences.

sentences = ['Absence of sanity', 
             'Lack of saneness',
             'A man is eating food.',
             'A man is eating a piece of bread.',
             'The girl is carrying a baby.',
             'A man is riding a horse.',
             'A woman is playing violin.',
             'Two men pushed carts through the woods.',
             'A man is riding a white horse on an enclosed ground.',
             'A monkey is playing drums.',
             'A cheetah is running behind its prey.']

# Each sentence is encoded as a 1-D vector with 78 columns
sentence_embeddings = model.encode(sentences)

print('Sample BERT embedding vector - length', len(sentence_embeddings[0]))

print('Sample BERT embedding vector - note includes negative values', sentence_embeddings[0])

#@title Sematic Search Form

# code adapted from https://github.com/UKPLab/sentence-transformers/blob/master/examples/application_semantic_search.py

query = 'Nobody has sane thoughts' #@param {type: 'string'}

queries = [query]
query_embeddings = model.encode(queries)

# Find the closest 3 sentences of the corpus for each query sentence based on cosine similarity
number_top_matches = 3 #@param {type: "number"}

print("Semantic Search Results")

for query, query_embedding in zip(queries, query_embeddings):
    distances = scipy.spatial.distance.cdist([query_embedding], sentence_embeddings, "cosine")[0]

    results = zip(range(len(distances)), distances)
    results = sorted(results, key=lambda x: x[1])

    print("\n\n======================\n\n")
    print("Query:", query)
    print("\nTop 5 most similar sentences in corpus:")

    for idx, distance in results[0:number_top_matches]:
        print(sentences[idx].strip(), "(Cosine Score: %.4f)" % (1-distance))
```

**Comment by amahendrakar** [comment]
@ali9653,
If you have saved your model to a file, then you can use the TFLite converter Python API to convert your model to TFLite. Please follow [this](https://www.tensorflow.org/lite/convert/python_api) official guide to convert your saved model. Thanks!

**Comment by ali9653** [comment]
> @ali9653,
> If you have saved your model to a file, then you can use the TFLite converter Python API to convert your model to TFLite. Please follow [this](https://www.tensorflow.org/lite/convert/python_api) official guide to convert your saved model. Thanks!
How can I save this model its a pre-trained model. The link does not have instructions of converting a bert model

**Comment by amahendrakar** [comment]
@ali9653,
You can select the BERT model of your choice from [this](https://tfhub.dev/s?q=bert) official TF Hub link and follow the user guide given. Thanks!

**Comment by ali9653** [comment]
> @ali9653,
> You can select the BERT model of your choice from [this](https://tfhub.dev/s?q=bert) official TF Hub link and follow the user guide given. Thanks!

I'm sorry but I think you are not understanding the question. I know how to import a model from tensorflow hub be it bert or universal sentence encoder. I want to convert it into TfLite is the question. There is no user guide for conversation

**Comment by amahendrakar** [comment]
@ali9653,
Please take a look at [this example](https://www.tensorflow.org/lite/convert/python_api#end-to-end_mobilenet_conversion_) for end to end model conversion.

**Comment by ali9653** [comment]
> @ali9653,
> Please take a look at [this example](https://www.tensorflow.org/lite/convert/python_api#end-to-end_mobilenet_conversion_) for end to end model conversion.

I'm sorry you are still not understanding. The model they have used Mobilenet_v2 is directly supported. Mine is imported from tensorflow hub and there is no documentation regarding that.

**Comment by ymodak** [comment]
Have you tried using pre-trained BERT models [Mobile Bert](https://www.tensorflow.org/lite/models/bert_qa/overview#performance_benchmarks), [Albert](https://tfhub.dev/tensorflow/albert_lite_base/1).

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
