### ISSUE TITLE
Convert 0d tensor into float value

### ISSUE THREAD

**Issue by johannafrost** [tensorflow/tensorflow#38126]
How can I convert a tensor of rank 0 and dtype float32 into a 'regular' float value? I am not running a session so tf.eval() does not work.

**Comment by abhinavsp0730** [comment]
Hy, @johannafrost  you can use 
``` 
tf.cast(
    x, dtype, name=None
)
```
for more info, kindly refer to this documentaiton: https://www.tensorflow.org/api_docs/python/tf/cast

**Comment by johannafrost** [comment]
Doesn't that still return a tensor? I would like to get a float value instead of a tensor, which I can append to a list (initiated by list = []) .

**Comment by abhinavsp0730** [comment]
Hey, @johannafrost 
suppose you are having a 0d tensor and you assign to a variable x.
```
a = x.numpy()
b = list(a)
type(b)
-> list
```
now "b" is a list and you can easily access the element of the list.

**Comment by johannafrost** [comment]
Thank a lot for the replies. Not sure how I can apply that to a 0d tensor though, since neither tensor.numpy() or list(tensor) works.

**Comment by abhinavsp0730** [comment]
Hey, @johannafrost it worked for me would you please provide your colab notebook?

**Comment by abhinavsp0730** [comment]
Whenever you're doing any typecasting then assign it to another variable.
```
tensor = tf.constant([1.0,2.0], dtype=float32) 
a = tensor.numpy()
b = list(a) 
type(b) 
—> list
```

**Comment by johannafrost** [comment]
> Hey, @johannafrost it worked for me would you please provide your colab notebook?
[LBFGS_MNIST.ipynb.zip]
It is the loss_value and the f.iter in the wrapper I am trying to add to a list, so they can be plotted. Thanks a lot.

**Comment by amahendrakar** [comment]
@johannafrost,
Please take a look at [this gist](https://colab.research.google.com/gist/amahendrakar/7dd236f2b3a93f549c196794426379ae/38126.ipynb) and let us know if it resolves your query. Thanks!

**Comment by amahendrakar** [comment]
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
