### ISSUE TITLE
TensorFlow-gpu for GV100 on SUSE 15

### ISSUE THREAD

**Issue by yskale** [tensorflow/tensorflow#38134]
- **OS Platform and Distribution: SUSE 15
- **TensorFlow installed from (source or binary)**: 2.1.0
- **Python version**: 3.6
- **GCC/Compiler version (if compiling from source)**: 7.5.0
- **CUDA/cuDNN version**: 10.5
- **GPU model and memory**: 100 GV 

![image](https://user-images.githubusercontent.com/14827177/78168197-8441cd80-741d-11ea-9308-35e8da02be49.png)

Wed Apr  1 10:35:13 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro GV100        Off  | 00000000:15:00.0 Off |                  Off |
| 36%   47C    P0    36W / 250W |      0MiB / 32508MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Quadro GV100        Off  | 00000000:2D:00.0 Off |                  Off |
| 40%   53C    P0    36W / 250W |      0MiB / 32500MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by gadagashwini** [comment]
@yskale, Please Provide the exact sequence of commands / steps that you executed before running into the problem and also full error log. Thanks!

**Comment by yskale** [comment]
Thanks @gadagashwini for reply. The details are

![image](https://user-images.githubusercontent.com/14827177/78253107-e227f100-74c1-11ea-9e91-cf5cd42a6e0c.png)

**Comment by gadagashwini** [comment]
@yskale, Can you share the full error log?

**Comment by yskale** [comment]
It is not able to detect the GPUs with the Tensorflow-gpu. I have shared all the log details. Can you share the couple of commands ...to test ...so that I can share the log based on that....

**Comment by gadagashwini** [comment]
@yskale, To know the available GPU devices, use this command
```
tf.test.is_gpu_available(
    cuda_only=False, min_cuda_compute_capability=None
)
```
For more refer [this](https://www.tensorflow.org/api_docs/python/tf/test/is_gpu_available). Thanks

**Comment by yskale** [comment]
![image](https://user-images.githubusercontent.com/14827177/78786423-bbacfe80-7976-11ea-90a0-094111f907ca.png)

**Comment by gadagashwini** [comment]
@yskale,
Make sure you have added CUDA and cuDNN path.Please follow the instructions mentioned [here](https://www.tensorflow.org/install/gpu#linux_setup). Thanks!

**Comment by yskale** [comment]
I followed the guidelines, but the still not able to see the GPU's in tensorflow
![image](https://user-images.githubusercontent.com/14827177/79144066-54cf8100-7d8c-11ea-898e-b2800aeceda9.png)

**Comment by jvishnuvardhan** [comment]
@yskale Can you please check the GPU compatibility [here](https://www.tensorflow.org/install/source#gpu). Did you build tensorflow from source or binary?

tensorflow-2.1.0 | 2.7, 3.5-3.7 | GCC 7.3.1 | Bazel 0.27.1 | 7.6 | 10.1
-- | -- | -- | -- | -- | --

In this issue, you mentioned `CUDA/cuDNN version: 10.5` but nvidia-smi showed `NVIDIA-SMI 440.33.01 Driver Version: 440.33.01 CUDA Version: 10.2 |`. Actually, if you had installed through pip binary, then Tensorflow looks for `cuda 10.1` related directories. If you had installed from source, then try to check the cuda paths are correctly referencing in the installed tensorflow. Thanks!

**Comment by yskale** [comment]
I have build the tensorflow from the pip binary.

**Comment by jvishnuvardhan** [comment]
@yskale your nvidia-smi shows that you have `CUDA Version: 10.2` where as cuda10.2 is not compatible with `TF2.1`. Can you please check the compatibility from my [previous response](https://github.com/tensorflow/tensorflow/issues/38134#issuecomment-615018196) and update your cuda version to 10.1. So, uninstall cuda10.2, restart and install cuda10.1 and related drivers. Once everything is done, install tensorflow2.1 and check it. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by yskale** [comment]
Hi,
These are details for the systems, we are still not able to detect the GPU's in torch or tensor flow.

![image](https://user-images.githubusercontent.com/14827177/87707762-a878ae80-c76f-11ea-85a3-1df925b08435.png)
