### ISSUE TITLE
AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by suu98** [tensorflow/tensorflow#38140]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Windows 10 
- TensorFlow installed from (source or
binary): pip
- TensorFlow version (use command below): tensorflow 2.1.0
- Python version: Python 3.7.7 
**Describe the current behavior**
when run the file : app.py , this error happens.
 for key, item in cls_config.items(): AttributeError: 'list' object has no attribute 'items'
how could i solve it ?

**Comment by ravikyram** [comment]
@suu98 

Please, provide colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster.Thanks!
