### ISSUE TITLE
`tf_http_archive` in RC breaks with Bazel 2.2.0

### ISSUE THREAD

**Issue by dmadisetti** [tensorflow/tensorflow#38147]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 18 (https://hub.docker.com/r/dmadisetti/nvidia-ibazel)
- TensorFlow installed from (source or binary): Source
- TensorFlow version: tensorflow-2.2.0-rc2
- Bazel version (if compiling from source): 2.2.0
- GCC/Compiler version (if compiling from source): clang-9
- CUDA/cuDNN version: 10.1

**Describe the problem**

Tensorflow will not compile as an external repositiory, as `tf_http_repository` fails on sourcing other libraries. I investigated a little but want to post here.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

In my WORKSPACE
```starlark
http_archive(
    name = "org_tensorflow",
    strip_prefix = "tensorflow-2.2.0-rc2",
    sha256 = "3e0cffc98ad3767dd16a09b7f25a99961e21d65cfcad67ed3a9b1a01318c7e94",
    urls = ["https://github.com/tensorflow/tensorflow/archive/v2.2.0-rc2.tar.gz"],
)
```

Attempting to run a test from my workspace, and no cache (or .bazelrc):
`bazel  test --experimental_repo_remote_exec repo/cc:all repo/python:all`

Yields:
```
Starting local Bazel server and connecting to it...
ERROR: /tmp/build_cache/_bazel_root/a08c2e4811c846650b733c6fc815a920/external/org_tensorflow/tensorflow/workspace.bzl:653:5: no such target '@org_tensorflow//third_party:zlib.BUILD': target 'zlib.BUILD' not declared in package 'third_party'; however, a source file of this name exists.  (Perhaps add 'exports_files(["zlib.BUILD"])' to third_party/BUILD?) defined by /tmp/build_cache/_bazel_root/a08c2e4811c846650b733c6fc815a920/external/org_tensorflow/third_party/BUILD and referenced by '//external:zlib'
ERROR: /tmp/build_cache/_bazel_root/a08c2e4811c846650b733c6fc815a920/external/org_tensorflow/tensorflow/workspace.bzl:653:5: no such target '@org_tensorflow//third_party/systemlibs:zlib.BUILD': target 'zlib.BUILD' not declared in package 'third_party/systemlibs'; however, a source file of this name exists.  (Perhaps add 'exports_files(["zlib.BUILD"])' to third_party/systemlibs/BUILD?) defined by /tmp/build_cache/_bazel_root/a08c2e4811c846650b733c6fc815a920/external/org_tensorflow/third_party/systemlibs/BUILD and referenced by '//external:zlib'
```

Cool, cool. So I added `export_files(glob(["*.BUILD"]))` to `third_party/systemlibs/BUILD` and `third_party/BUILD` which gives me:

```
Starting local Bazel server and connecting to it...
ERROR: /tmp/build_cache/_bazel_root/a08c2e4811c846650b733c6fc815a920/external/org_tensorflow/tensorflow/workspace.bzl:653:5: in build_file attribute of tf_http_archive rule //external:zlib: source file '@org_tensorflow//third_party:zlib.BUILD' is misplaced here (expected no files)
ERROR: /tmp/build_cache/_bazel_root/a08c2e4811c846650b733c6fc815a920/external/org_tensorflow/tensorflow/workspace.bzl:653:5: in system_build_file attribute of tf_http_archive rule //external:zlib: source file '@org_tensorflow//third_party/systemlibs:zlib.BUILD' is misplaced here (expected no files)
INFO: Call stack for the definition of repository 'remotejdk11_linux' which is a http_archive (rule definition at /tmp/build_cache/_bazel_root/a08c2e4811c846650b733c6fc815a920/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):
 - <builtin>
 - /tmp/build_cache/_bazel_root/a08c2e4811c846650b733c6fc815a920/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:9
 - /DEFAULT.WORKSPACE.SUFFIX:235:1
ERROR: Analysis of target '//repo/cc:cc_proto' failed; build aborted: Analysis of target '//external:zlib' failed; build aborted
```
Makes sense, `tf_http_archive` isn't set to allow source files. So I changed: `third_party/repo.bzl`, such that the attributes have the `allow_single_file` option.

```starlark
tf_http_archive = repository_rule(
    attrs = {
        "sha256": attr.string(mandatory = True),
        "urls": attr.string_list(
            mandatory = True,
            allow_empty = False,
        ),
        "strip_prefix": attr.string(),
        "type": attr.string(),
        "delete": attr.string_list(),
        "patch_file": attr.label(allow_single_file = True),
        "build_file": attr.label(allow_single_file = True),
        "system_build_file": attr.label(allow_single_file = True),
        "system_link_files": attr.string_dict(),
        "additional_build_files": attr.string_dict(),
    },
    environ = [
        "TF_SYSTEM_LIBS",
    ],
    implementation = _tf_http_archive,
)
```

But I guess not? This yields:
```
Starting local Bazel server and connecting to it...
ERROR: /tmp/build_cache/_bazel_root/a08c2e4811c846650b733c6fc815a920/external/org_tensorflow/tensorflow/workspace.bzl:653:5: in tf_http_archive rule //external:zlib: Found reference to a workspace rule in a context where a build rule was expected; probably a reference to a target in that external repository, properly specified as @reponame//path/to/package:target, should have been specified by the requesting rule.
ERROR: Analysis of target '//repo/python:repo' failed; build aborted: Analysis of target '//external:zlib' failed; build aborted
INFO: Elapsed time: 5.150s
INFO: 0 processes.
```

At this point I figure I'd just ask. tensorflow-2.1.0 works perfectly, except for a bug that I addressed here: https://github.com/tensorflow/tensorflow/pull/36830

**Any other info / logs**

Done in my docker container! So hopefully repeatable. Altered source in `bazel-workspace/external/org_tensorflow/` as a quick hack

**Comment by mihaimaruseac** [comment]
Afaik, we haven't yet tested if our code builds with this version of Bazel. We only test with versions specified in `./configure.py`

**Comment by dmadisetti** [comment]
This might be more of using "tensorflow as a bazel dep" than a bazel version problem. I just tried building my project with the following commands:

`env USE_BAZEL_VERSION=2.0.0 ~/go/bin/bazelisk test --experimental_repo_remote_exec repo/cc:all repo/python:all`
`env USE_BAZEL_VERSION=2.1.0 ~/go/bin/bazelisk test --experimental_repo_remote_exec repo/cc:all repo/python:all`

To the same result. I believe inclusion the way I laid out is the recommended way for creating custom tf ops, and tf is also commonly used like this throughout a variety of open-source google projects and beyond.

However, I just made a minimal example and it ran! It looks like there may be a conflict with my other deps and TF. Will investigate a bit more when I get some bandwidth, but the error still has me thinking it's still a TF problem. I'll publish the example and update here once I can reliably produce the bug.

**Comment by dmadisetti** [comment]
Cool! Finally had a chance to look at this. I have conflicting dependencies with zlib.

It looks like I'm using `zlib 1.2.11` across the board, so it makes me wonder if one of the build files diverged somewhere. I'm not sure why my setup worked with `2.1.0`, and I didn't go too far down the git blame rabbit hole.

I went over the bazel docs and tried using a `repo_mapping` [as described here](https://docs.bazel.build/versions/master/external.html) to no avail. It looks like this may be a bug in `tf_http_archive`. Quick and dirty solution was to combine using `repo_mapping` with a check for the dependency before adding it:

in `tensorflow/workspace.bzl`
```starlark
    if "zlib" not in native.existing_rules():
        tf_http_archive(
            name = "zlib",
            ...
        )
```

and in my WORKSPACE
```starlark
http_archive(
    name = "org_tensorflow",
    repo_mapping = {"@zlib": "@_zlib"},
)
```

I'll close this out once I can come up with a nice solution. Best case: TF should respect `repo_mapping`, Worst case: A more informative error should be provided.

This might be more the fault of whatever dep I have than tf. I'll see if I can track it down. I have a hunch that it's (rules_proto)[https://github.com/stackb/rules_proto/blob/master/deps.bzl#L136]

**Comment by mihaimaruseac** [comment]
This should be solved now, afaik

**Comment by mihaimaruseac** [comment]
This seems to have stalled and afaik it  has been solved. Closing this but please reopen if the issue still manifest with the latest Bazel and a latest commit.
