### ISSUE TITLE
Add a build target for a shared library that contains the c api symbols

### ISSUE THREAD

**Issue by LaurentMazare** [tensorflow/tensorflow#3814]
Since r0.10, the library created by build target tensorflow:libtensorflow.so does not contain the c api symbols anymore (whereas this was the case in previous releases). I imagine that this was caused by the c api moving from tensorflow/core to tensorflow/c. This is a little inconvenient for our [ocaml tensorflow bindings](https://github.com/LaurentMazare/tensorflow-ocaml) as they rely on these symbols.

Would it be possible to add back this dependency ? Something as simple as adding "//tensorflow/c:c_api" to the deps list worked for me.
If this dependency has been avoided on purpose for tensorflow:libtensorflow.so, could we add a different build target, e.g. libtensorflow_c.so, that would include it ?
I'm happy to write a pull request for either of these if this helps.

**Comment by josh11b** [comment]
Sorry @keveman , I probably broke this, but I don't know what the fix is.

**Comment by keveman** [comment]
@LaurentMazare what you suggest sounds good, please send a PR.

**Comment by LaurentMazare** [comment]
@keveman I've attached a PR with a new target that includes the C api symbol. Let me know if you think it would be better to include them directly into an existing target, e.g. libtensorflow.so.

**Comment by LaurentMazare** [comment]
@josh11b @keveman any thoughts on this ? If it's still time I would be very happy to have this fixed in the final 0.10 release so that we can have our ocaml wrapper working on this version.

**Comment by keveman** [comment]
@LaurentMazare I just started a jenkins test for PR #3830. I will merge that once tests are green.
