### ISSUE TITLE
TensorFlow Developer Certificate

### ISSUE THREAD

**Issue by Bstrum36** [tensorflow/tensorflow#38141]
Does the  TensorFlow exam include Keras?

Are there any sample tests available for review?

**Comment by ymodak** [comment]
The certificate program requires an understanding of building basic TensorFlow models using Computer Vision, Sequence modeling, and Natural Language Processing. So I think TF Keras is necessary. 
This course https://www.coursera.org/specializations/tensorflow-in-practice can be a good prep for the exam.
To know more see https://blog.tensorflow.org/2020/03/introducing-tensorflow-developer-certificate.html and [candidate handbook](https://www.tensorflow.org/site-assets/downloads/marketing/cert/TF_Certificate_Candidate_Handbook.pdf)

**Comment by Saduf2019** [comment]
@Bstrum36 
please update as per above comment

**Comment by Bstrum36** [comment]
Thank you for the information

**Comment by Saduf2019** [comment]
@Bstrum36 
please let us know if we may move this to closed status

**Comment by Bstrum36** [comment]
I really did not get an answer to my question.

Are there sample tests available?
Is Keras included in the scope of the exam?

real questions with yes or no answers.

**Comment by Saduf2019** [comment]
@Bstrum36 
please refer to [this link](https://www.infoq.com/news/2020/03/google-tensorflow-certification/) for tensorflow related certification

**Comment by Saduf2019** [comment]
@Bstrum36
please update as per above comment

**Comment by Bstrum36** [comment]
Thanks,
This still does not answer my basic question which is: are there any sample tests avaible for review?

**Comment by JosBecker** [comment]
Please see the checklist in the [Candidate Handbook](https://www.tensorflow.org/site-assets/downloads/marketing/cert/TF_Certificate_Candidate_Handbook.pdf) for the list of things you need to know before taking the TensorFlow Developer Certificate exam.

Please see the section "Don't feel ready to take the exam?" at [tensorflow.org/certificate ](tensorflow.org/certificate) for resources for learning.

During the exam you will need to define and train models using TensorFlow.

We do not have sample questions.

We regret we are not able to further discuss the contents of the exam.

Regards

TensorFlow Certificate team

**Comment by ymodak** [comment]
Closing this issue since it's been addressed. Thanks!

**Comment by gharshini** [comment]
Can we refer some resources like stackover flow(for any errors) or our noted material while taking the exam?

**Comment by ahtik** [comment]
@gharshini From the [TF Certificate Candidate Handbook](https://www.tensorflow.org/extras/cert/TF_Certificate_Candidate_Handbook.pdf), "Resources allowed during exam: You may use whatever learning resources you would normally use during your ML development work".

[Exam setup instructions](https://www.tensorflow.org/extras/cert/Setting_Up_TF_Developer_Certificate_Exam.pdf) has additional hints to avoid getting errors. Today it's Python 3.7 and TF 2.0. The exam env will be upgraded to TensorFlow 2.3 soon.

**Comment by Afvanjaffer** [comment]
https://github.com/Afvanjaffer/dlaicourse   

this is best for the exam
