### ISSUE TITLE
Test deterministic cuDNN CTC loss

### ISSUE THREAD

**Issue by duncanriach** [tensorflow/tensorflow#38151]
@sanjoy added deterministic cuDNN CTC loss, enabled via `TF_DETERMINISTIC_OPS`, with [this commit](https://github.com/tensorflow/tensorflow/commit/9e096debc4a0909deb69970f38bee7b77e5e5f7d). This issue is a reminder to add test for it in [tensorflow/python/kernel_tests/cudnn_deterministic_base.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/cudnn_deterministic_base.py).

This issue is a replacement for PR [38089](https://github.com/tensorflow/tensorflow/pull/38089).

**Comment by duncanriach** [comment]
Please will someone with the authority assign this issue to me?

**Comment by ravikyram** [comment]
@duncanriach 

Any update on this issue please. Thanks!

**Comment by duncanriach** [comment]
@ravikyram no update. I have not yet gotten to this.

**Comment by duncanriach** [comment]
Still on my radar. Please keep this open.

**Comment by duncanriach** [comment]
This issue is closed by PR [52227](https://github.com/tensorflow/tensorflow/pull/52227).
