### ISSUE TITLE
TF Lite build missing .lib

### ISSUE THREAD

**Issue by lip-realmax** [tensorflow/tensorflow#38157]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.1
- Python version: 3.6
- Installed using virtualenv? pip? conda?: NA
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): msvc 142 (vs2019)
- CUDA/cuDNN version: 10 / 7
- GPU model and memory: GTX 1080

**Describe the problem**
Trying to build Tensorflow ( lite only ) with bazel in windows using the provide rule
```c++
tflite_cc_shared_object(
    name = "tensorflowlite",
...
)
```
There are many outputs and the tensorflowlite.dll. Yet there aint the corresponding tensorflowlite.lib ? Where can I find it or special configuration is needed ? 

The partial output log for compilation

```cmd
INFO: From Linking tensorflow/lite/tensorflowlite.dll:
LINK : warning LNK4044: unrecognized option '/s'; ignored
   Creating library bazel-out/x64_windows-opt/bin/tensorflow/lite/libtensorflowlite.dll.ifso and object bazel-out/x64_windows-opt/bin/tensorflow/lite/libtensorflowlite.dll.exp
Target //tensorflow/lite:tensorflowlite up-to-date:
  bazel-bin/tensorflow/lite/tensorflowlite.dll
INFO: Elapsed time: 112.240s, Critical Path: 50.53s
INFO: 308 processes: 308 local.
INFO: Build completed successfully, 440 total actions

```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Since the missing .lib, simple code will give unresolved external symbol link error. E.g.
```c++
#include <c_api.h>
#include <iostream>

int main(int argc, char *argv[])
{
  std::cout << TfLiteVersion() << std::endl;
  return 0;
}
```
Which gives

``error LNK2019: unresolved external symbol __imp_TfLiteVersion``

-----------------------------------------------

**Any other info / logs**
--------------------------------------------
![image](https://user-images.githubusercontent.com/56542376/78237947-92234b80-750e-11ea-88fe-1f39af92b8d8.png)

**Comment by terryheo** [comment]
What's the compile command you used for the sample?

**Comment by Tomhouxin** [comment]
![image](https://user-images.githubusercontent.com/23637856/87774869-bf92cb80-c857-11ea-9f62-b1ee135688b2.png)
I got tensorflowlite.dll(17M), no lib file
