### ISSUE TITLE
TFLM: add run-time check that statically allocated buffers are sufficiently large

### ISSUE THREAD

**Issue by dauras** [tensorflow/tensorflow#38156]
It would be great to have a simple run-time check that the statically allocated buffer is sufficient.

This is as simple as adding one line:
```
TFLITE_DCHECK_LE(output_channels, kMaxChannels);
```
after this one:
https://github.com/tensorflow/tensorflow/blob/83e974b61c7b65ee8de87774addf1a0dc6b24c9a/tensorflow/lite/micro/kernels/conv.cc#L99

**Comment by rthadur** [comment]
There is no reference to above code in current version here https://github.com/tensorflow/tflite-micro ,I will be closing this issue as the tflite-mirco repo is now separate and further issues should be opened there. Thank you.
