### ISSUE TITLE
Unable to batch tensorflowLite object detection model

### ISSUE THREAD

**Issue by harshithdwivedi** [tensorflow/tensorflow#38158]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): MacOSX
- TensorFlow installed from (source or
binary): Binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7

**Describe the current behavior**
I'm using the TfLite object detection models in python and upon trying to resize the input to increase the batch size; I'm getting an error as follows: 

```
Traceback (most recent call last):
  File "test_cropped_face.py", line 70, in <module>
    interpreter.allocate_tensors()
  File "/Users/harshitdwivedi/Desktop/tf_env/lib/python3.7/site-packages/tensorflow/lite/python/interpreter.py", line 73, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/Users/harshitdwivedi/Desktop/tf_env/lib/python3.7/site-packages/tensorflow/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 106, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: tensorflow/lite/kernels/reshape.cc:58 num_input_elements != num_output_elements (3276800 != 65536)Node number 88 (RESHAPE) failed to prepare.
```

**Describe the expected behavior**
Setting a custom batch size for an image classification model works without any issues; so I expect the same thing to happen here as well.

**Standalone code to reproduce the issue** 
```
interpreter = tf.contrib.lite.Interpreter(model_path="cropped_face.tflite")

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# resize the input to run inference on more than 1 image at a time; the default size is [1,512,512,3]
interpreter.resize_tensor_input(input_details[0]['index'], [50, 512, 512, 3])
interpreter.allocate_tensors()

```
Here's the model I'm using. I have trained it via the GCP's Cloud Vision Dashboard.
https://drive.google.com/file/d/1teJ34GvWmd-1aZBqNLeqIy-owOj5_RDS/view?usp=sharing

**Comment by Saduf2019** [comment]
@harshithdwivedi 
please refer to this [comment](https://github.com/tensorflow/tensorflow/issues/16216#issuecomment-358685965) and issues with similar error for reference and let us know if it helps.


#25549 #22377 #23600  #23399

**Comment by harshithdwivedi** [comment]
Nope, doesn't help.
I've gone through these issues already and none of them has a solution to this problem. 

P. S. Do note that I'm trying to resize the input to increase the batch size and not the input image size.
Some answers outlined that the image size can't be changed for mobilenet on the fly so that's not what I'm trying to do anyways.

**Comment by harshithdwivedi** [comment]
Hi @Saduf2019 any update on this?

**Comment by harshithdwivedi** [comment]
cc: @jvishnuvardhan

**Comment by jvishnuvardhan** [comment]
@harshithdwivedi I suspect dynamic batching was not implemented in TF1.x. Can you please try `TF2.x`?. While converting the model, define the shape as `[None,512,512,3]` and convert the model to tflite model and test the converted model with interpreter. Check [this](https://github.com/tensorflow/tensorflow/issues/38036) issue which is similar to you. Thanks!

**Comment by harshithdwivedi** [comment]
Hey @jvishnuvardhan thanks for the reply.

I'm getting this model from Cloud AutoML object detection so it's already in tflite format.
I doubt if it's possible to reconvert a tflite model.

I tried TF2.0 but I keep getting the same error.
I also tried to set the shape as [None, 512, 512, 3] from python code but it fails to accept that as a valid size: 

```
Traceback (most recent call last):
  File "test_cropped_face.py", line 69, in <module>
    None, 512, 512, 3])
  File "/Users/harshitdwivedi/Desktop/tf_2.0/lib/python3.7/site-packages/tensorflow_core/lite/python/interpreter.py", line 402, in resize_tensor_input
    tensor_size = np.array(tensor_size, dtype=np.int32)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

My Python code: 

```py
interpreter = tf.lite.Interpreter(model_path="cropped_face.tflite")

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# resize the input to run inference on more than 1 image at a time; the default size is [1,512,512,3]
interpreter.resize_tensor_input(input_details[0]['index'], [None, 512, 512, 3])
interpreter.allocate_tensors()

```

**Comment by asimeonovMLPS** [comment]
Hi, I have the same problem. I trained the SSD MobileNet V2 FPNLite 320x320 model, converted it to tflite and after I try to give it a batch of images allocate_tensors() returns an error num_input_elements! = num_output_elements. From the above I understand that I need to re-convert my TF2 model to tflight and I need to set the dynamic shape during conversion. I use tf_nightley (version 2.5.0-dev20201107)for training and conversion, I think I can set the shape using concrete_func .inputs [0] .set_shape ([None, 320, 320, 3]). Here is my code for conversion:

```
import tensorflow as tf
import numpy as np

model = tf.saved_model.load("saved_model/")
concrete_func = model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
concrete_func.inputs[0].set_shape([None, 320, 320, 3])
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func]) 
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

with open('batch_q_model.tflite', 'wb') as f:
  f.write(tflite_model)
```
The conversion code is executed without error but in the end I get  464 byte tflite model. I think it's too little even for tflight. Where am I wrong? Thank you.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by Siddhijain16** [comment]
> Hi, I have the same problem. I trained the SSD MobileNet V2 FPNLite 320x320 model, converted it to tflite and after I try to give it a batch of images allocate_tensors() returns an error num_input_elements! = num_output_elements. From the above I understand that I need to re-convert my TF2 model to tflight and I need to set the dynamic shape during conversion. I use tf_nightley (version 2.5.0-dev20201107)for training and conversion, I think I can set the shape using concrete_func .inputs [0] .set_shape ([None, 320, 320, 3]). Here is my code for conversion:
> 
> ```
> import tensorflow as tf
> import numpy as np
> 
> model = tf.saved_model.load("saved_model/")
> concrete_func = model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
> concrete_func.inputs[0].set_shape([None, 320, 320, 3])
> converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func]) 
> converter.optimizations = [tf.lite.Optimize.DEFAULT]
> tflite_model = converter.convert()
> 
> with open('batch_q_model.tflite', 'wb') as f:
>   f.write(tflite_model)
> ```
> 
> The conversion code is executed without error but in the end I get 464 byte tflite model. I think it's too little even for tflight. Where am I wrong? Thank you.

Hi @asimeonovMLPS 
Is your model working well in mobile app?

**Comment by srjoglekar246** [comment]
@Siddhijain16 Just checking if you tried [this guide](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md) for converting SSD models?

**Comment by Siddhijain16** [comment]
Yes I tried the [notebook](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb) mention in that guide.

**Comment by srjoglekar246** [comment]
Do you want all the COCO classes, or have you retrained the model for your dataset?

**Comment by Siddhijain16** [comment]
I want to retrained the model for my own custom classes

**Comment by srjoglekar246** [comment]
I see. Did you get the trained model from the notebook? If yes, what error do you see when running it on Java/Android?

**Comment by Siddhijain16** [comment]
Just have a look 
https://github.com/tensorflow/models/issues/9694#issuecomment-770725095

**Comment by asimeonovMLPS** [comment]
Hi @Siddhijain16 , I never converted the model, once I found out that the SSD is not optimized for batch inference, I stopped trying to resize the input to increase the batch size.

**Comment by seboz123** [comment]
Is there any resoultion to get tensorflow lite working for batches > 1?
I got the same error when I resize the input tensor
