### ISSUE TITLE
tflite model crashes before loading .tflite file, with no error or exception

### ISSUE THREAD

**Issue by orangesomethingorange** [tensorflow/tensorflow#38161]
**System information** 
- Have I written custom code: 

Yes I have:

In Activity.java:

=======================================================================

```
gpuDelegate = new GpuDelegate();
Interpreter.Options tfliteOptions = (new Interpreter.Options()
          .addDelegate(gpuDelegate));
tfliteModel
        = FileUtil.loadMappedFile(myContext,
        "my_model.tflite");
tfliteInterpreter = new Interpreter(tfliteModel, tfliteOptions);
```
...

```
imageProcessor =
        new ImageProcessor.Builder()
                .add(new NormalizeOp(MY_MEAN, MY_STDDEV))
                .build();

inputImageBuffer.load(bitmap);
imageProcessor.process(inputImageBuffer);
```

...

`tfliteInterpreter.run(inputImageBuffer.getBuffer(), outputBuffer.getBuffer().rewind());`

=======================================================================

In build.gradle:

=======================================================================
```
implementation 'org.tensorflow:tensorflow-lite:+'
implementation 'org.tensorflow:tensorflow-lite-gpu:+'
implementation 'org.tensorflow:tensorflow-lite-support:+'
```
=======================================================================

- OS Platform and Distribution: 

Linux Ubuntu 16.04

- Mobile device: 

Samsung Galaxy S10

- TensorFlow installed:

From binary (pip)

- TensorFlow version: 

TensorFlow 2.0

- Python version:

Python 3.6

- GCC/Compiler version:

Wasn't compiled from source, but gcc 7.4.0

- CUDA/cuDNN version:

CUDA 10.0

- GPU model and memory:

GeForce RTX 2080 Ti
11GB

**Describe the current behavior**

Model input is a 1MP image.
I'm trying to run the model via CPU (tfliteOptions are default), GPU (GPU delegate) and NNAPI (NNAPI delegate).

1MP runs with the GPU delegate only - the other two options crash.
When crashing - the debug process is detached from Android.
There are no exceptions, errors or hints regarding what happened.

After that, I take the same exact model, and I only change the input size, from 1MP to 10MP (in python it's just changing the HxW of the input image). From the 10MP model I create a new .tflite file.
When trying to run the 10MP model - it doesn't even load.

Is it a memory issue? and if so - how can I check that? What can I do to reduce the impact?

**Describe the expected behavior**

Have some exceptions, error messages or any other hint as to what's going on.
Let's say it's a memory issue - how can I handle that? Which part fails exactly?

**Other info / logs**

- Debugging the 1MP model on CPU (the issue is that the app crashes):

Last debugger frames:

getRuntime:166, VMRuntime (dalvik.system)
<init>:69, DirectByteBuffer$MemoryRef (java.nio)
allocateDirect:258, ByteBuffer (java.nio)
allocateMemory:352, TensorBuffer (org.tensorflow.lite.support.tensorbuffer)
<init>:304, TensorBuffer (org.tensorflow.lite.support.tensorbuffer)
<init>:38, TensorBufferFloat (org.tensorflow.lite.support.tensorbuffer)
createDynamic:96, TensorBuffer (org.tensorflow.lite.support.tensorbuffer)
getTensorBuffer:297, TensorImage$ImageContainer (org.tensorflow.lite.support.image)
getTensorBuffer:213, TensorImage (org.tensorflow.lite.support.image)
apply:52, TensorOperatorWrapper (org.tensorflow.lite.support.image.ops)

Process is detached when calling ByteBuffer.allocateDirect (in allocateMemory function):
```
    private void allocateMemory(int[] shape) {
        SupportPreconditions.checkNotNull(shape, "TensorBuffer shape cannot be null.");
        SupportPreconditions.checkArgument(isShapeValid(shape), "Values in TensorBuffer shape should be non-negative.");
        int newFlatSize = computeFlatSize(shape);
        if (this.flatSize != newFlatSize) {
            this.flatSize = newFlatSize;
            this.shape = (int[])shape.clone();
            this.buffer = ByteBuffer.allocateDirect(this.flatSize * this.getTypeSize()); <<<< HERE <<<<
            this.buffer.order(ByteOrder.nativeOrder());
        }
    }
```

- Debugging the 1MP model on NNAPI (the issue is that the app crashes):

Process is detached when calling applyDelegate (in applyDelegates function, in NativeInterpreterWapper.class):
```
while(var6.hasNext()) {
                Delegate delegate = (Delegate)var6.next();
                applyDelegate(this.interpreterHandle, this.errorHandle, delegate.getNativeHandle()); <<<< HERE <<<<
                this.delegates.add(delegate);
            }
```

- Debugging the 10MP model on GPU (the issue is that the .tflite model doesn't even gets loaded):

I see that the Asset Manager gets closed.
Last debugger frames:

get:145, ClosedGuard (dalvik.system)
<init>:104, ParcelFileDescriptor (android.os)
<init>:184, ParcelFileDescriptor (android.os)
nativeOpenAssetFd:-1, AssetManager (android.content.res)
openFd:848, AssetManager (android.content.res)
loadMappedFile:154, FileUtil (org.tensorflow.lite.support.common)

**Comment by jvishnuvardhan** [comment]
@orangesomethingorange Can you please share the code to create model and converting it to tflite model? It is difficult to find root-cause of the issue without model. I will check the model and resolve the issue. Thanks!

**Comment by orangesomethingorange** [comment]
@jvishnuvardhan Thanks! I already changed the whole design since I couldn't get pass the memory issue. Now the Interpreter instance is running, but I have different issues regarding batch image processing and converting byte, float and int values. I'll open a new issue if I'll find a bug or post on stackoverflow :)

**Comment by WindowsDriver** [comment]
> @jvishnuvardhan Thanks! I already changed the whole design since I couldn't get pass the memory issue. Now the Interpreter instance is running, but I have different issues regarding batch image processing and converting byte, float and int values. I'll open a new issue if I'll find a bug or post on stackoverflow :)

hello,How did you solve your problem？I ran into the same problem

**Comment by WindowsDriver** [comment]
I would be very grateful if you could explain briefly

**Comment by jvishnuvardhan** [comment]
@WindowsDriver Please create a new issue with a standalone code to reproduce the error. Thanks!
