### ISSUE TITLE
tf.gather Converting sparse IndexedSlices warning

### ISSUE THREAD

**Issue by gasteigerjo** [tensorflow/tensorflow#38168]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from: binary (Anaconda)
- TensorFlow version: 2.1
- Python version: 3.7.7
- CUDA/cuDNN version: 10.1/7.6.5
- GPU model and memory: GeForce 1080 Ti

**Describe the current behavior**
Whenever `tf.gather` (or `tf.boolean_mask`) is called with `params` (`tensor`) being the output of another function, this throws the warning `UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.` This behavior seems to be [well known](https://stackoverflow.com/questions/35892412/tensorflow-dense-gradient-explanation) but largely ignored/accepted. Calling `tf.gather` on the output of another function is perfectly reasonable and should in my opinion *not* throw a warning.

**Describe the expected behavior**
The forward pass should infer the shape of the dense tensor required in the backward pass, if possible (issue with dynamic shapes?). No warning should be thrown or the user should be able to acknowledge/deactivate the warning (ideally a warning that is more specific than the current one).

**Standalone code to reproduce the issue** 
See e.g. https://github.com/klicperajo/dimenet/blob/master/train.ipynb

**Other info / logs**
https://stackoverflow.com/questions/35892412/tensorflow-dense-gradient-explanation
Related: https://github.com/tensorflow/tensorflow/issues/23566

**Comment by amahendrakar** [comment]
@klicperajo,
I tried to reproduce the issue, but I'm facing an error stating `KeyError: 'ceil'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/976ba78b3487a7f3e27dbe4f9876625d/38168.ipynb).

In order to expedite the trouble-shooting process, could you please provide a minimal code sample to reproduce the issue reported here. Thanks!

**Comment by klicperajo** [comment]
Thank you for looking into this!

That's because the runtime uses a completely outdated version of sympy. Just add a `!pip install --upgrade sympy` at the beginning and you're good to go.

The notebook also throws a deprecation warning from within tensorflow (`calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated`), so that should be worthwile to investigate as well.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/e05ae0768d95f2f9d34292f11ce3ec9d/38168.ipynb), however running the code with [TF-nightly](https://colab.research.google.com/gist/amahendrakar/37e1b2941bd4cd347a5677d87ebf8a84/38168-tf-nightly.ipynb) prints only a single warning. Please find the attached gist. Thanks!

**Comment by klicperajo** [comment]
Great! Throwing a single warning is certainly better than throwing 12. However, it does still throw a warning, so my criticism and thoughts from above still applies.

**Comment by Saduf2019** [comment]
@klicperajo,
Can you please try on the latest tf- version and let us know if this is still an issue.

**Comment by klicperajo** [comment]
As described earlier there is just 1 warning now. However, yes, in `tf-nightly-2.4.0.dev20201005` I still see the warning
```
.../lib/python3.7/site-packages/tensorflow/python/framework/indexed_slices.py:437: UserWarning: Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("gradient_tape/dimenet/interaction/Reshape_2:0", shape=(None,), dtype=int32), values=Tensor("gradient_tape/dimenet/interaction/Reshape_1:0", shape=(None, 64), dtype=float32), dense_shape=Tensor("gradient_tape/dimenet/interaction/Cast:0", shape=(2,), dtype=int32))) to a dense Tensor of unknown shape. This may consume a large amount of memory.
```

and in TensorFlow 2.3.1 it is
``
.../lib/python3.7/site-packages/tensorflow/python/framework/indexed_slices.py:433: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
```

**Comment by norabelrose** [comment]
I am also getting this warning, but in a somewhat different context. I am training a language model in which the input embedding weights matrix and the final, pre-softmax weights matrix are shared (as described [here](https://arxiv.org/abs/1608.05859) and as used in the famous _Attention is All You Need_ paper). Invariably, whether I use the Keras Embedding layer, or if I call tf.gather() or tf.nn.embedding_lookup() directly, I get this warning. As soon as I allow the pre-softmax weights matrix to be distinct from the input embedding matrix, the error goes away. Presumably this has something to do with TF having to sum up the gradients with respect to the embedding matrix from the pre-softmax matrix multiply and the tf.gather() operation— but I'm still relatively new to TensorFlow and ML more generally, so I may be misunderstanding something.

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/c6056e7ae6a66f4d93d91897a5b44c29/untitled261.ipynb) ..Thanks !
