### ISSUE TITLE
Tensor load wrong CUDNN

### ISSUE THREAD

**Issue by ijalalfrz** [tensorflow/tensorflow#38169]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.15
- Python version: 3.7.6
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 7.6.0
- GPU model and memory: 940mx 2GB

So i want to run some project from [this repo](https://github.com/wcwowwwww/Real-Time-Object-Detection-and-Tracking), but i'm having a problem, tensorflow showing error like this:

> E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.5.1 but source was compiled with: 7.6.0.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.

i have installed CUDNN 7.6.5, 7.6.0, 7.5.1 but the error still appears

**Comment by Saduf2019** [comment]
@ijalalfrz
Can you please check with cuda 10 and cudnn 7.4, and let us know if that helps resolve your issue.
is there any specific reason for using 1.15 version and not a later updated version of tensorflow

#35376 #23715

**Comment by ijalalfrz** [comment]
> @ijalalfrz
> Can you please check with cuda 10 and cudnn 7.4, and let us know if that helps resolve your issue.
> is there any specific reason for using 1.15 version and not a later updated version of tensorflow
> 
> #35376 #23715

because some code of the repo using tensorflow under 2.0 which is some codes are deprecated, i will try to install cudnn 7.4

**Comment by ijalalfrz** [comment]
@Saduf2019 
I'am still getting same error after install CUDNN 7.4.2

> E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.5.1 but source was compiled with: 7.6.0.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.

i don't know why tensor always pointing to cudnn 7.5.1, i just install single CUDA 10 in my drive, is there any step to check if there are 2 CUDAs

**Comment by Saduf2019** [comment]
@ijalalfrz
In that case you will have to uninstall what cudas you have, do a fresh installation of just the required.

or please refer to these links [link1](https://blog.kovalevskyi.com/multiple-version-of-cuda-libraries-on-the-same-machine-b9502d50ae77) , [link2](https://stackoverflow.com/questions/40517083/multiple-cuda-versions-on-machine-nvcc-v-confusion)

**Comment by ijalalfrz** [comment]
@Saduf2019 ok. i will try to reinstall it and post a progress after

**Comment by ijalalfrz** [comment]
@Saduf2019 still getting same error, i have installed cuda 10 and cudnn 7.6.5

**Comment by Saduf2019** [comment]
@ijalalfrz 
please add cudnn and cuda path. follow the instructions https://www.tensorflow.org/install/gpu#linux_setup

**Comment by Saduf2019** [comment]
@ijalalfrz
please update as per above comment

**Comment by Saduf2019** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
