### ISSUE TITLE
Provide a tensorflow maven package for AWS Lambda or lighter builds in general

### ISSUE THREAD

**Issue by wasserholz** [tensorflow/tensorflow#38162]
The current build size of tensorflow 1.14.0 makes it impossible to use the library on AWS Lambda without further steps to reduce the depedency size.

It would be great to have for example a tensorflow dependency for AWS Lambda specifically.

What would also work, would be a separate module for tensorflow without all native libraries and a module per native implementation. This way the overhead of the darwin and windows native code is gone and reduces the dependency significantly (~200MB).

**Comment by rthadur** [comment]
This request is not valid with latest versions , so closing this issue.
