### ISSUE TITLE
[REGRESSION] Bazel build failure 

### ISSUE THREAD

**Issue by nouiz** [tensorflow/tensorflow#38171]
commit 2082d706a5ed3bbe07706cfb694b431b2fe50f89 included 2 days ago in #34218 break bazel tests:

```
$bazel test --config=noaws --config=nogcp --config=nohdfs --verbose_failures -c dbg --copt -DNDEBUG  //tensorflow/compiler/xla/service/gpu:all

...
Execution platform: @local_config_platform//:host
gcc: error: missing argument to '-B'
```

I cannot just comment the offending line: `cuda_defines["%{linker_bin_path}"] = ""` as elsewhere it expect it to be present. But if I set the old value "host_compiler_prefix", it fix my problems.

Can we just revert this commit until a good version is available?

I tried with bazel 2.0.0 and 2.1.0 and 2.2.0. So bumping the bazel version doesn't fix this problem.

**Comment by sanjoy** [comment]
> commit 2082d70 included 2 days ago in #34218 break bazel tests:

I'm missing something, isn't the commit/PR back from Nov 2019?

CC @mihaimaruseac

**Comment by nouiz** [comment]
The commit is very old, but it got merged 2 days ago.

**Comment by sanjoy** [comment]
> The commit is very old, but it got merged 2 days ago.

I see.  Then we should probably revert this commit.

@mihaimaruseac @gunan WDYT?

**Comment by nouiz** [comment]
Here is a dockerfile that reproduce this in case it help identify the root cause:
```
FROM nvcr.io/nvidia/tensorflow:20.02-tf1-py3
RUN cd /workspace/ && git clone https://github.com/tensorflow/tensorflow.git && cd /opt/tensorflow && ./nvbuild.sh --python3.6 --configonly && cd /workspace/tensorflow && cp /opt/tensorflow/tensorflow-source/.tf_configure.bazelrc .
RUN cd /workspace && wget -q https://github.com/bazelbuild/bazel/releases/download/2.0.0/bazel-2.0.0-installer-linux-x86_64.sh && bash bazel-2.0.0-installer-linux-x86_64.sh
RUN cd /workspace/tensorflow && bazel test --config=noaws --config=nogcp --config=nohdfs --verbose_failures -c dbg --copt -DNDEBUG  //tensorflow/compiler/xla/service/gpu:all //tensorflow/compiler/xla/client/lib:arithmetic_test
```

**Comment by mihaimaruseac** [comment]
Agree to reverting the commit. Will do so at once

**Comment by mihaimaruseac** [comment]
Well, @gunan was faster

**Comment by nouiz** [comment]
Thanks this one is fixed, but there is another regression. I made a new issues for it.

https://github.com/tensorflow/tensorflow/issues/38205
