### ISSUE TITLE
bulid tensorflow failed 

### ISSUE THREAD

**Issue by whyseu** [tensorflow/tensorflow#38182]
I follow the instrctons in the "https://tensorflow.google.cn/federated/install".
(1)Install TensorFlow Federated using pip: When I run the command "python -c "import tensorflow_federated as tff; print(tff.federated_computation(lambda: 'Hello World')())"" , there is a SyntaxError: invalid syntax os
(2)Using Docker: When I run the command "docker build .  --tag tensorflow_federated", it always fails.
These two errors are shown in the shapshot.
<img width="771" alt="无标题11" src="https://user-images.githubusercontent.com/35478590/78322895-a0bb4280-75a2-11ea-9886-20e256eae28c.png">

**Comment by ymodak** [comment]
This issue more suitable on [TensorFlow Federated](https://github.com/tensorflow/federated/issues) repository. Thanks!

**Comment by mihaimaruseac** [comment]
Closing as not an issue of main TensorFlow. Please reopen on TensorFlow Federated
