### ISSUE TITLE
No module named 'tensorflow.keras'

### ISSUE THREAD

**Issue by DucLong06** [tensorflow/tensorflow#38187]
i use : 
win10 os
anaconda 3(python 3.6)
tensorflow 1.5.0
keras 2.1.6
i run 
import tensorflow as tf
from tensorflow.keras.layers import Conv2D, BatchNormalization, ReLU, SeparableConv2D
i have error :
    from tensorflow.keras.layers import Conv2D, BatchNormalization, ReLU, SeparableConv2D
ModuleNotFoundError: No module named 'tensorflow.keras'

**Comment by ravikyram** [comment]
@DucLong06 
TF 1.5.0 version is very old. Please, upgrade to latest TF versions `1.15,  2.X( 2.0, 2.1.0, 2.2rc1) `and you will not have any issues with these versions.Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
