### ISSUE TITLE
Error on confliction between custom op argument name and python builtin name

### ISSUE THREAD

**Issue by wrongtest** [tensorflow/tensorflow#38184]
**System information** 
- Have I written custom code: yes 
- OS Platform and Distribution: Linux 
- TensorFlow installed from: binary
- TensorFlow version: 1.13.1 
- Python version: 3.6

**Describe the current behavior**
If we define custom op as
```
REGISTER_OP("MyCustomOp")
    .Input("list: list({int32, float32})")
    .Attr("my_list_attr: list(int)")
    // other settings ...
```
And invoke in python as
```
lib = load_library.load_op_library('my_custom_op.so')
output = lib.my_custom_op(arguments)
```
The error raises `TypeError: isinstance() arg 2 must be a type or tuple of types`

**Other info / logs** 
Refer to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/python_op_gen.cc#L484
I find python side wrapper will be created as
`def my_custom_op(list, ...)` if we define input name as "list"

And for attribute "my_list_attr", check code is generated as
`if not isinstance(my_list_attr, (list, tuple)):`

But "list" do not refer to builtin type anymore :(, which results to python type errors. Can some name checking get conducted to avoid such kind of confusing errors?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
