### ISSUE TITLE
[PROPOSAL] Go back to cmake and drop support to bazel -- a real memory and time abusing toolkit for building medium size projects

### ISSUE THREAD

**Issue by yiakwy-enterprise-roborock** [tensorflow/tensorflow#38183]
## Motivation

If we build tensorflow using camke, I guess only 1~2 hours is enough for the first trial considering the current project size. However when we switch to bazel huge memory and time will be consumed.

Bazel by defaults will creates huge number of jobs (you can control by --jobs) and each job consumes nearly 10 GB memory. Besize, a lot of non-binary dependencies downloaded using "git", this breaks  philosophy of UNix design.  

Actually using "git" while building a large project is a not very good practice. Cmake by defaults does not support SSL and you have build it manually to support curl with ssl . Moreover,  instead of to clone a whole project, we only need to download released versions of that. Using `git clone` inside a complex installer will creates more problems that you can predict: proxy server, memory cache, fire wall, ...

Considering the fact that all-in-one installer should be friendly to a new machine, the bazel has been proved not good at that.

I suggest to use traditional ways to maintain binary dependencies by tracing different binary managers for different OS distribution.

## C++ dependencies

A product manager or project manager can easily figure out that many projects integrated a compiled tensorflow shared library with cmake projects like HDMap localization module. There are little people who really need bazel because it breaks philosophy of Unix design and solve a problem which does not really exist.

## Compiling details

1) config
By default we change jvm memory flags using "--host_jvm_args" upon bazel server boot up and refine jobs to a specific number with flags "--jobs" following `bazel build`

see discussion https://stackoverflow.com/questions/34382360/decrease-bazel-memory-usage

2) user specific installation may creates problems when `sudo` needed (checking cuda installation for example).
Since default installation of  bazel is user specific , a script executed by root user will no longer be able to detect ${HOME}/bin/bazel automatically. But meanwhile, searching and modifying thirdparty libraries (cuda, cudnn for examples) requires root privileges. The creates a dilemma.

3) The peak memory building tensorflow used by bazel as I observed  with htop:

Max: 13 G
Avg: 5 ~ 7 G

while bazel boot use more than 10GB and using Malloc utilities, we observed that some of memory became free but was not retrieved by the system.

**Comment by gunan** [comment]
Hi, thanks for raising this issue.
Unfortunately, internally google uses the BUILD files. Google's code base will not migrate off of these in any case for the foreseeable future. Therefore, TF has to support them.
When we tried to support cmake and Makefile it created a lot of burden to edit multiple build systems for developers. So we decided to drop first party support for these.

That said, we would be happy if our community decided to maintain cmake files for TF. WE cannot have them in the main repository, but we would be able to point users who would like to use cmake towards them. We did try to have our community take over our cmake files, but those discussions did not pan our at the time.

**Comment by planetmarshall** [comment]
@gunan I'm going to have a look at creating a project to build the C++ API only using CMake and Conan. I'm not sure how sustainable it will be in the long run but I'm not convinced of Bazel's utility in the C++ sphere, and I think there are enough pain points from a C++ developers perspective (particularly on Windows) to make it worth the effort.

I'll share with the community if I can get something workable.

**Comment by helmesjo** [comment]
@planetmarshall Any progress on this? :)

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
