### ISSUE TITLE
UnimplementedError: Cast string to float is not supported 	 [[{{node Cast_4}}]]

### ISSUE THREAD

**Issue by ninjakx** [tensorflow/tensorflow#38181]
I don't know why I am getting error for steps_per_epoch. I tried to give values in integer directly but still not working.

**Traceback:**

`---------------------------------------------------------------------------
UnimplementedError                        Traceback (most recent call last)
<ipython-input-57-941407f460bb> in <module>
      5     epochs=EPOCHS,
      6     callbacks=[lr_callback],
----> 7     steps_per_epoch=float(186.0),
      8     #validation_data=valid_dataset
      9 )

~/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    725         max_queue_size=max_queue_size,
    726         workers=workers,
--> 727         use_multiprocessing=use_multiprocessing)
    728 
    729   def evaluate(self,

~/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_distributed.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, **kwargs)
    683         validation_steps=validation_steps,
    684         validation_freq=validation_freq,
--> 685         steps_name='steps_per_epoch')
    686 
    687   def evaluate(self,

~/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py in model_iteration(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, initial_epoch, steps_per_epoch, validation_steps, validation_freq, mode, validation_in_fit, prepared_feed_values_from_dataset, steps_name, **kwargs)
    298           else:
    299             actual_inputs = ins()
--> 300           batch_outs = f(actual_inputs)
    301         except errors.OutOfRangeError:
    302           if is_dataset:

~/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py in __call__(self, inputs)
   3471         feed_symbols != self._feed_symbols or self.fetches != self._fetches or
   3472         session != self._session):
-> 3473       self._make_callable(feed_arrays, feed_symbols, symbol_vals, session)
   3474 
   3475     fetched = self._callable_fn(*array_vals,

~/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py in _make_callable(self, feed_arrays, feed_symbols, symbol_vals, session)
   3408       callable_opts.run_options.CopyFrom(self.run_options)
   3409     # Create callable.
-> 3410     callable_fn = session._make_callable_from_options(callable_opts)
   3411     # Cache parameters corresponding to the generated callable, so that
   3412     # we can detect future mismatches and refresh the callable.

~/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in _make_callable_from_options(self, callable_options)
   1503     """
   1504     self._extend_graph()
-> 1505     return BaseSession._Callable(self, callable_options)
   1506 
   1507 

~/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in __init__(self, session, callable_options)
   1458       try:
   1459         self._handle = tf_session.TF_SessionMakeCallable(
-> 1460             session._session, options_ptr)
   1461       finally:
   1462         tf_session.TF_DeleteBuffer(options_ptr)

UnimplementedError: Cast string to float is `

**Comment by amahendrakar** [comment]
@ninjakx,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by amahendrakar** [comment]
Any updates regarding this issue? Thanks!

**Comment by ninjakx** [comment]
I have lost the code. I was running a SO code.
