### ISSUE TITLE
example person_detection_test  can not make form source code of tensorflow

### ISSUE THREAD

**Issue by MrZoloft** [tensorflow/tensorflow#38180]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
third party's down shell file should update?
![image](https://user-images.githubusercontent.com/24219045/78319275-6600dc80-7599-11ea-8150-b05a7c33eb6e.png)

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@MrZoloft, Can you Provide the exact sequence of commands or standalone code that you executed before running into the problem and also share the Tensorflow version. Thanks

**Comment by MrZoloft** [comment]
> @MrZoloft, Can you Provide the exact sequence of commands or standalone code that you executed before running into the problem and also share the Tensorflow version. Than

**Comment by MrZoloft** [comment]
@gadagashwini  hello , i just git clone the latest tensorflow source code base on master branch 
Then  commad fellow：
make -f tensorflow/lite/micro/tools/make/Makefile
make -f tensorflow/lite/micro/tools/make/Makefile test_person_detection_test 
just like what has been written on tensorflow/lite/micro/person_detection -- READEME.MD .
my machine is ubuntu 16.04
whether should i install bazel firstly? or do other pre -jobs

**Comment by MrZoloft** [comment]
@ymodak Is there any solution for this issue?  i changed another new machine env to use above command, but still useness.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.
