### ISSUE TITLE
TF 2.1: inserting into MutableHashTable results into error

### ISSUE THREAD

**Issue by vladdders** [tensorflow/tensorflow#38198]
**System information** 
- Have written custom code
- OS Platform and Distribution: Linux Ubuntu 18.04: 
- TensorFlow installed from binary: `pip install tensorflow-gpu==2.1.0` 
- TensorFlow version: 2.1.0
- Python version: 3.6
- CUDA/cuDNN version: 10/7.0
- GPU model and memory: GTX1070 and 6GB

**Describe the current behavior**
I am trying to insert some key:value pairs into a MutableHashTable

**Describe the expected behavior**
Using the contrib equivalent of MutableHashTable does not produce this error.

**Standalone code to reproduce the issue** 
```import tensorflow as tf
tf.compat.v1.disable_eager_execution()

CHARMAP = ['', '', ''] + list('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ')

with tf.device('/gpu:0'):
    table = tf.raw_ops.MutableHashTable(
            key_dtype=tf.int64,
            value_dtype=tf.string,
    )

insert = table.insert(tf.constant(list(range(len(CHARMAP))), dtype=tf.int64),
                     tf.constant(CHARMAP)
                     )
```

**Other info / logs** 
Here is the output:

```Traceback (most recent call last):
 File "test.py", line 12, in <module>
    insert = table.insert(tf.constant(list(range(len(CHARMAP))), dtype=tf.int64),
AttributeError: 'Tensor' object has no attribute 'insert'
```

**Comment by gadagashwini** [comment]
Was able to reproduce the issue with Tf2.1.
Pleas find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/fddfec4fe89b58d863090f06a6e6691a/untitled490.ipynb). Thanks

**Comment by rohan100jain** [comment]
tf.raw_ops.MutableHashTable returns a tensor handle corresponding to the table that then needs to be used in an init_op / insert op etc.

I think what you want is tf.lookup.experimental.DenseHashTable https://www.tensorflow.org/api_docs/python/tf/lookup/experimental/DenseHashTable

import tensorflow as tf
tf.compat.v1.disable_eager_execution()

CHARMAP = ['', '', ''] + list('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ')

with tf.device('/gpu:0'):
    table = tf.lookup.experimental.DenseHashTable(
            key_dtype=tf.int64,
            value_dtype=tf.string,
            default_value='_',
            empty_key=0,
            deleted_key=-1,
    )

table.insert(tf.constant(list(range(len(CHARMAP))), dtype=tf.int64),
                     tf.constant(CHARMAP))

Please let me know if you have any issues.
