### ISSUE TITLE
TESLA T4 Graphics Card

### ISSUE THREAD

**Issue by SouradipBh** [tensorflow/tensorflow#38196]
I am planning to move to Nvidia Tesla T4 16gb from RTX 2080 8gb.
I am working on yolo model with tensorflow.
I am running around 8 parallel video detection simultaneously.
Currently,my present graphics card RTX 2080 8 gb supporting 8 parallel instances successfully.
So what through Tesla 12gb is supposed to give? How many parallel instances can be run on Tesla 12gb VRAM?

Please help me with this.

**Comment by ravikyram** [comment]
@SouradipBh 

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by SouradipBh** [comment]
OK. But can u tell me how many instances will work on this GPU?

**Comment by sanjoy** [comment]
> OK. But can u tell me how many instances will work on this GPU?

It is hard to know for sure, but usually these things do scale linearly with GPU memory as you'd expect (so you'd run 12 instances in parallel if you had 12G of memory).

**Comment by SouradipBh** [comment]
Is there any way to run minimum 30 instances in limited GPU Memory.
Basically i want to run  parallel real time object detection simultaneously.
Can u help me with this? I would be very grateful if you could help me.

**Comment by sanjoy** [comment]
> Can u help me with this? I would be very grateful if you could help me.

I personally cannot commit to giving one on one help on system design issues like this, and github issues are not a good forum for this either.  Please consider asking on StackOverflow or other such forums.

**Comment by SouradipBh** [comment]
Ok. Thanks
