### ISSUE TITLE
tf.data.Dataset should support attr classes instances as values

### ISSUE THREAD

**Issue by AdrienCorenflos** [tensorflow/tensorflow#38192]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.1.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Currently Datasets only support nested structures of tuples, named tuples, and dictionaries, however attr classes are also supported transparently by tf.function. Ideally, to be consistent, these should also be supported by datasets as they are the primary entry point for data in autographed functions.

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Anyone using structured data.

**Any Other info.**
- Code for attr support in tf.function:
https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/core/utils/computation_utils.py#L47

- Code for supported types in Dataset:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/util/structure.py#L407

- A usage example that should be legit but is not:

```python
import attr
from collections import namedtuple
import tensorflow as tf


@attr.s(frozen=True)
class DataContainer:
    data = attr.ib()
    
NamedDataContainer = namedtuple('NamedDataContainer', ['data'])
        
@tf.function
def f(x):
    return x

x = tf.constant(0.)
f(DataContainer(x)) # legit
f(NamedDataContainer(x)) # legit

dataset = tf.data.Dataset.from_tensor_slices([0., 1., 2., 3.])

dataset.map(NamedDataContainer) # legit
dataset.map(DataContainer) # not legit
```

**Comment by lsgrep** [comment]
Hi @jsimsa , Can I work on this?

**Comment by denismaxim0v** [comment]
Shouldn't this issue be closed? Or is it up for grabs still?
