### ISSUE TITLE
Chains of queues not working in 0.10.0 rc0

### ISSUE THREAD

**Issue by hannes-brt** [tensorflow/tensorflow#3819]
### Environment info
Operating System: Ubuntu 14.04, Mac OS X

Installed version of CUDA and cuDNN: None

If installed from binary pip package, provide: 
CPU only, Python 2.7 packages for 0.9.0 and 0.10.0 rc0

I am working with a scheme in which I feed several batch queues into a `batch_join` to multiplex them.

The following code works in 0.9.0 (prints several batches before encountering `OutOfRange`, but fails in 0.10.0 rc0 (first run of `sess.run(c)` produces `OutOfRange`).

```python
import tensorflow as tf
import numpy as np
import string

sess = tf.Session()

a = tf.train.batch([tf.train.input_producer(list(string.ascii_lowercase), shuffle=False, num_epochs=1).dequeue()], 10)
b = tf.train.batch([tf.train.input_producer(list(string.ascii_uppercase), shuffle=False, num_epochs=1).dequeue()], 10)

c = tf.squeeze(tf.train.batch_join([(a,), (b,)], 1, enqueue_many=False), [0])

sess.run(tf.initialize_all_variables())
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for _ in range(20):
    print sess.run(c)
```

### Steps to reproduce
1. Run in 0.9.0
2. Run in 0.10rc1

### What have you tried?
1. Noticed this behaviour in Mac OS X
2. Double checked by creating two Docker images having TF 0.9.0 and 0.10.0 rc0 respectively installed on top of Ubuntu 14.04.

### Logs or other output that would be helpful

TensorFlow 0.9.0 output
```
['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j']
['k' 'l' 'm' 'n' 'o' 'p' 'q' 'r' 's' 't']
['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J']
['K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S' 'T']
Traceback (most recent call last):
  File "/Untitled11.py", line 23, in <module>
    print sess.run(c)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 636, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 708, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 728, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.OutOfRangeError: PaddingFIFOQueue '_4_batch_join/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: batch_join = QueueDequeueMany[_class=["loc:@batch_join/padding_fifo_queue"], component_types=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch_join/padding_fifo_queue, batch_join/n)]]
Caused by op u'batch_join', defined at:
  File "/Untitled11.py", line 16, in <module>
    c = tf.squeeze(tf.train.batch_join([(a,), (b,)], 1, enqueue_many=False, dynamic_pad=True), [0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 682, in batch_join
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/data_flow_ops.py", line 434, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 465, in _queue_dequeue_many
    timeout_ms=timeout_ms, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 704, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2260, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1230, in __init__
    self._traceback = _extract_stack()
```

TensorFlow 0.10.0 rc0 Output:
```
E tensorflow/core/client/tensor_c_api.cc:485] Attempting to use uninitialized value input_producer/limit_epochs/epochs
	 [[Node: input_producer/limit_epochs/CountUpTo = CountUpTo[T=DT_INT64, _class=["loc:@input_producer/limit_epochs/epochs"], limit=1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer/limit_epochs/epochs)]]
E tensorflow/core/client/tensor_c_api.cc:485] PaddingFIFOQueue '_4_batch_join/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: batch_join = QueueDequeueMany[_class=["loc:@batch_join/padding_fifo_queue"], component_types=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch_join/padding_fifo_queue, batch_join/n)]]
Traceback (most recent call last):
  File "/Untitled11.py", line 23, in <module>
    print sess.run(c)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 655, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 723, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 743, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.OutOfRangeError: PaddingFIFOQueue '_4_batch_join/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: batch_join = QueueDequeueMany[_class=["loc:@batch_join/padding_fifo_queue"], component_types=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch_join/padding_fifo_queue, batch_join/n)]]
Caused by op u'batch_join', defined at:
  File "/Untitled11.py", line 16, in <module>
    c = tf.squeeze(tf.train.batch_join([(a,), (b,)], 1, enqueue_many=False, dynamic_pad=True), [0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 708, in batch_join
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/data_flow_ops.py", line 435, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 867, in _queue_dequeue_many
    timeout_ms=timeout_ms, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2310, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1232, in __init__
    self._traceback = _extract_stack()
```

**Comment by mrry** [comment]
Can you try adding the following line, before starting the queue runners:

```python
sess.run(tf.initialize_local_variables())`
```

(It looks like there was a breaking change between 0.9 and 0.10, which recast how the auxiliary variables inside functions like `tf.train.input_producer()` are initialized.)

**Comment by hannes-brt** [comment]
Thanks - it seems this solves it.


--Hannes

**Comment by alquraishi** [comment]
I had a similar problem and this fixes it for me too. I'm a bit puzzled though, as I had previously called `tf.initialize_all_variables().run(session=sess)` but that did not work on its own. I actually had to call `initialize_local_variables()` as well. Shouldn't the former subsume the latter?

**Comment by vrv** [comment]
For some terrible reason, local variables are not considered part of "all"
:(

We are in the process of renaming "all" to somethong else less confusing,
since models would break if we made "all" include local variables. It's a
mess.

**Comment by alquraishi** [comment]
Hmmm. Why would making "all" include "local" break things though? And if that's the case then is it even a good idea to invoke initialize "all" followed by "local"? Or is your point that they need to be done as separate steps, and so long as that's the case, then it's ok?

**Comment by vrv** [comment]
Because exactly when people call initialize_all vs. initialize_local matters ("all" happens once, typically, I believe "local" happens locally to workers whenever they restart).  I don't know the details, I actually proposed what you said and was told it would break things, and they have to be done as separate steps.  Fixing the naming will at least make it less confusing, at least, but I wish we weren't in this situation.

**Comment by mrry** [comment]
@vrv @alquraishi If I understand the [commit](https://github.com/tensorflow/tensorflow/commit/4c85a95925a68fec324f70cd0d7f3d4548f97a38) that broke this correctly, the problem was that `all_variables()` determined not just what was initialized when you do `tf.initialize_all_variables()` but **also** what variables are saved when you construct a `tf.train.Saver()` with no arguments. This particular variable would turn up in checkpoints and cause problems (e.g. you'd restore a model and try to use it for training, but the epoch limit in the input producer would already be reached, so you'd get OutOfRange as soon as you started).

Agreed that we should fix the naming, but possibly we should also separate out the notion of "all" (which seems useful and uncontroversial) from the notion of "things that get saved in checkpoints by default".

**Comment by alquraishi** [comment]
@mrry if I understand you correctly, the underlying distinction seems less to be about "global" vs. "local" and more of a "one-time initialization" vs some notion of what's included in the checkpoint. Perhaps "initialize" is not even the right prefix to describe the corresponding function then.

It sure is confusing as is now.

From a practical standpoint, is the fix to simply call both, in any given order?

**Comment by vrv** [comment]
Yes, the problem is that 'global' vs 'local' is conflated with 'saved' vs. 'not-saved', and we're trying to clean and clear that up.

Today, I think it makes sense to first call initialize_all_variables, then initialize_local_variables (I believe the Supervisor framework does this for you).  We will probably rename / deprecate _all_variables and replace it with something a bit more meaningful before 1.0.

**Comment by alquraishi** [comment]
@vrv ok thanks, that is what I'm currently doing and it seems to work fine. I started writing my TF code with 0.5 and so everything is very close to the metal, without any of the fancy new stuff like the Supervisor framework. Perhaps at some point I'll refactor, but so far I've gotten away with it! ;-)

**Comment by vrv** [comment]
Bare metal use is fine, we should have abstractions that work for everyone, with various degrees of control and ease :)
