### ISSUE TITLE
tf.py_function could return a dictionary of tensors

### ISSUE THREAD

**Issue by Ceceu** [tensorflow/tensorflow#38212]
Usually, a transformers tokenizer encodes an input as a dictionary.
```python
{"input_ids": tf.int32, "attention_mask": tf.int32, "token_type_ids": tf.int32}
```
And to archive better performance handling with a large dataset, is a good practice implement a pipeline which includes using [`Dataset.map`](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#map) to apply a tokenizer function to each element of an input dataset. Exactly the same as done in the Tensorflow tutorial: [Load text](https://www.tensorflow.org/tutorials/load_data/text#encode_examples). 

However, the [`tf.py_function`](https://www.tensorflow.org/api_docs/python/tf/py_function) (used to wrap the map python function) doesn't support returning a dictionary of tensors as shown above.

For instance, if the tokenizer (encoder) in the [Load text](https://www.tensorflow.org/tutorials/load_data/text#encode_examples) returns the following dictionary:

```python
{
    "input_ids": [ 101, 13366,  2131,  1035,  6819,  2094,  1035,  102 ],
    "attention_mask": [ 1, 1, 1, 1, 1, 1, 1, 1 ]
}
```
how can someone set the `Tout` parameter of the [`tf.py_function`](https://www.tensorflow.org/api_docs/python/tf/py_function) to get the desired dictionary of tensors:

```python
{
    'input_ids': <tf.Tensor: shape=(16,), dtype=int32, numpy = array(
    [ 101, 13366,  2131,  1035,  6819,  2094,  1035,  102 ], dtype=int32)>

    'attention_mask': <tf.Tensor: shape=(16,), dtype=int32, numpy=array(
     [ 1, 1, 1, 1, 1, 1, 1, 1 ], dtype=int32)>
}
```
?

**Comment by rohan100jain** [comment]
I think this would be a nice feature but I think you can work around this limitation by constructing your py_function appropriately as tf.data supports dictionaries

python```
import tensorflow as tf

def tokenizer(x):
  return { "input_ids": [ 101, 13366,  2131,  1035,  6819,  2094,  1035,  102 ], "attention_mask": [ 1, 1, 1, 1, 1, 1, 1, 1 ]}

def py_func(x):
  d = tokenizer(x)
  return list(d.values())

def ds_map_fn(x):
  flattened_output = tf.py_function(py_func, [x], [tf.int32, tf.int32])
  return {"input_ids": flattened_output[0], "attention_mask": flattened_output[1]}

ds = tf.data.Dataset.range(2)
ds = ds.map(ds_map_fn)

for value in ds:
  print(value)
```

**Comment by novog** [comment]
See also the related issue #27679, concerned with `py_function` accepting dictionaries of tensors. I would really like to see both features implemented in TensorFlow. In real-world problems, data with heterogeneous features is quite common, and managing such features is made unnecessarily complicated by poor support for feature dictionaries.

**Comment by Ceceu** [comment]
@rohan100jain,
Although the limitation of  ` tf.py_function` I could use it to encode my dataset. Thank you.

**Comment by Ceceu** [comment]
@novog, it would be great.

**Comment by s4sarath** [comment]
Absolutely. It is very useful.
