### ISSUE TITLE
[saved_model_cli] cannot import name 'saved_model_aot_compile' from 'tensorflow.python.tools'  [2.2.0-rc2]

### ISSUE THREAD

**Issue by tarrade** [tensorflow/tensorflow#38216]
**System information** 
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): yes
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): No
- TensorFlow version (use command below):  v2.2.0-rc1-34-ge6e5d6df2a 2.2.0-rc2
- Python version: 3.7.6
- Bazelversion (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: - GPU model and memory: NA

**Describe the current behavior**
`saved_model_cl`i
```
Traceback (most recent call last):
  File "/Users/tarrade/anaconda-release/conda-env/env_test/bin/saved_model_cli", line 5, in <module>
    from tensorflow.python.tools.saved_model_cli import main
  File "/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.7/site-packages/tensorflow/python/tools/saved_model_cli.py", line 51, in <module>
    from tensorflow.python.tools import saved_model_aot_compile
ImportError: cannot import name 'saved_model_aot_compile' from 'tensorflow.python.tools' (/Users/tarrade/anaconda-release/conda-env/env_test/lib/python3.7/site-packages/tensorflow/python/tools/__init__.py)
```

**Describe the expected behavior**
with TF 2.1:
`saved_model_cli`
```
usage: saved_model_cli [-h] [-v] {show,run,scan,convert} ...
saved_model_cli: error: too few arguments
```
and if we pass all needed argument then it is working as expected

**Standalone code to reproduce the issue** 
just use the command line:
`saved_model_cli`

**Comment by Saduf2019** [comment]
@tarrade 
This has been noted and it will be taken care in next release, please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/38042#issuecomment-608036111)

please confirm if we may move this to closed status as its already noted to be taken care.

**Comment by tarrade** [comment]
@Saduf2019 sorry, I tried to look at existing tickets and I missed the already existing one since it was already closed. It is a duplicate so you can close it. Thanks

**Comment by Saduf2019** [comment]
moving this to closed status with confirmation

**Comment by Adblu** [comment]
I have saved model using serving with TF version 1.14.0. 
I want to run: saved_model_cli.py and I have the same error. 
Any update ?
