### ISSUE TITLE
iterating over `tf.Tensor` is not allowed when using autograph

### ISSUE THREAD

**Issue by xqiangx1991** [tensorflow/tensorflow#38215]
I am using tf2.1.0, but when I use `tf.range` within a funtion decorated by `tf.function` it throw an error. My code is blow
```
for batch in tf.range(batch_size):
    pass
```
and here is the error message
```
OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did not convert this function. Try decorating it directly with @tf.function
```
It works for tf2.0.0

So, I wonder how to use `tf.range` when using **Autograph**.

**Comment by yongtang** [comment]
@xqiangx1991 Please be more specific and provide a minimal reproducible code snippet. The description you provided is not very clear to reproduce.

**Comment by saikumarchalla** [comment]
@xqiangx1991  Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment]
@xqiangx1991,
Could you please check [this comment](https://github.com/tensorflow/tensorflow/issues/33308#issuecomment-542565633) from a similar issue and let us know if it works? Thanks!
