### ISSUE TITLE
Tensorflow version downgrade 

### ISSUE THREAD

**Issue by Mahati04** [tensorflow/tensorflow#38219]
ModuleNotFoundError: No module named 'tensorflow.contrib' 
This is the error i keep getting when i try to load my video file for YOLO object detection using darkflow. I tried using pip to downgrade the tensorflow version but its not changing the output.

**Comment by abhinavsp0730** [comment]
Hey, @Mahati04  would you please provide your code so that we'll try to replicate the error in our machine?

**Comment by Saduf2019** [comment]
@Mahati04 
please share tensorflow version and simple stand alone code for us to replicate the issue faced.

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

As per error faced check these existing issues.
##37720 #36419 #30794 #36269  #36878 #32147 #35197 #31350 #34083 #27084 #32621

**Comment by mihaimaruseac** [comment]
You have to do `pip list`; identify all packages in the tensorfow ecosystem (estimator, tensorboard, tensorflow), `pip uninstall` each one of them and then install again those you need at 1.15.

`contrib` does not exist in 2.0 and later.

**Comment by Saduf2019** [comment]
@Mahati04
please update on above comments

**Comment by nihalb7** [comment]
> You have to do `pip list`; identify all packages in the tensorfow ecosystem (estimator, tensorboard, tensorflow), `pip uninstall` each one of them and then install again those you need at 1.15.
> 
> `contrib` does not exist in 2.0 and later.

I uninstalled everything that you say. i try to install tensorflow 1.15.0 but i got error. "couldnt find a version that satisfies the requirement tensorflow==1.15.0" 
what should i do ?

**Comment by Saduf2019** [comment]
@nihalb7 
please share your system information

**Comment by nihalb7** [comment]
[info.txt](https://github.com/tensorflow/tensorflow/files/4476885/info.txt)
 I have tf 1.14 im not try to downgrade, i try to upgrade to 1.15

**Comment by mihaimaruseac** [comment]
Please open a new issue since this is about a downgrade.

Please fill in **all questions** in the issue template

**Comment by Saduf2019** [comment]
@Mahati04
please update if this is still an issue

**Comment by Saduf2019** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
