### ISSUE TITLE
[XLA:GPU] Memory Leak in r1.15 due to defer host callbacks

### ISSUE THREAD

**Issue by zhuzilin** [tensorflow/tensorflow#38213]
**System information** 
- Have I written custom code: 
yes
- OS Platform and Distribution: 
centos
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 
`pip install tensorflow-gpu==1.15.0`
- Python version:
python3.6
- CUDA/cuDNN version: - GPU model and memory:
cuda 10.0

**Describe the current behavior**
There is memory leak observed in `ThenRunAfterNextBlockHostUntilDone` when XLA is turned on. The reason for the memory leak is that in tensorflow `BlockHostUntilDone()` is not called and large amount of defered callback was accumulated.

**Describe the expected behavior**
No memory leaking in the function mentioned above.

**Standalone code to reproduce the issue** 
Probably any code that use XLA in r1.15.

**Other info / logs** 
The memory leaking problem was solved in master branch in commit 80851c0ad. I wonder if I can help to cherry-pick it to r1.15? Because it would be inconvenient to upgrade tf in our environment.

**Comment by amahendrakar** [comment]
@zhuzilin,
In order to expedite the trouble-shooting process, could you please provide a minimal code sample to reproduce the issue reported here. Thanks!

**Comment by amahendrakar** [comment]
@zhuzilin,
Any updates regarding the reproducible code? Thanks!

**Comment by zhuzilin** [comment]
@amahendrakar I've submitted the pr for this bug in #38292. Please feel free to close this issue.

**Comment by amahendrakar** [comment]
Thank you for the update @zhuzilin. Marking this issue as closed.
