### ISSUE TITLE
Smart compose using tensorflow

### ISSUE THREAD

**Issue by swaroop23** [tensorflow/tensorflow#38218]
Hey I am trying to create a API which can smart compose. Anyone that can help me out ?

**Comment by rohanreddych** [comment]
Not the place.

**Comment by amahendrakar** [comment]
@swaroop23,

Could you please elaborate the issue you are facing? Thanks!

**Comment by mihaimaruseac** [comment]
This is not the place for this question. Please try StackOverflow.

Here we only accept issues strictly related to code of TF.
