### ISSUE TITLE
from .pyrfc import *

### ISSUE THREAD

**Issue by saberabdelhady** [tensorflow/tensorflow#38226]
i already install 
C:\Python37>pip3 install pyrfc
Collecting pyrfc
  Downloading pyrfc-0.1.2.tar.gz (3.5 kB)
Installing collected packages: pyrfc
    Running setup.py install for pyrfc ... done
Successfully installed pyrfc-0.1.2

but when import i see this issue 

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    from .pyrfc import *
ModuleNotFoundError: No module named '__main__.pyrfc'; '__main__' is not a package

**Comment by amahendrakar** [comment]
@saberabdelhady,
Could you please confirm if the issue is related to TensorFlow?

If is it, please provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by mihaimaruseac** [comment]
Not a TF issue
