### ISSUE TITLE
TF2.0 frozen ckpt model or h5 model to pb model appear wrong

### ISSUE THREAD

**Issue by hahadashi** [tensorflow/tensorflow#38223]
> freeze the graph reference from the below code
> 
> ```python
> from keras import backend as K
> import tensorflow as tf
> 
> def freeze_session(session, keep_var_names=None, output_names=None, clear_devices=True):
>     """
>     Freezes the state of a session into a pruned computation graph.
> 
>     Creates a new computation graph where variable nodes are replaced by
>     constants taking their current value in the session. The new graph will be
>     pruned so subgraphs that are not necessary to compute the requested
>     outputs are removed.
>     @param session The TensorFlow session to be frozen.
>     @param keep_var_names A list of variable names that should not be frozen,
>                           or None to freeze all the variables in the graph.
>     @param output_names Names of the relevant graph outputs.
>     @param clear_devices Remove the device directives from the graph for better portability.
>     @return The frozen graph definition.
>     """
>     from tensorflow.python.framework.graph_util import convert_variables_to_constants
>     graph = session.graph
>     with graph.as_default():
>         freeze_var_names = list(set(v.op.name for v in tf.global_variables()).difference(keep_var_names or []))
>         output_names = output_names or []
>         output_names += [v.op.name for v in tf.global_variables()]
>         # Graph -> GraphDef ProtoBuf
>         input_graph_def = graph.as_graph_def()
>         if clear_devices:
>             for node in input_graph_def.node:
>                 node.device = ""
>         frozen_graph = convert_variables_to_constants(session, input_graph_def,
>                                                       output_names, freeze_var_names)
>         return frozen_graph
> 
> 
> frozen_graph = freeze_session(K.get_session(),
>                               output_names=[out.op.name for out in model.outputs]
> 
> tf.train.write_graph(frozen_graph, "model", "tf_model.pb", as_text=False)
> ```

hi，i use your demo complete frozen the ckpt model(checkpoint = tf.train.Checkpoint(myAwesomeModel=me), checkpoint.restore(tf.train.latest_checkpoint('examples'    ))) or h5 model (model.load_weights('model_enc.h5'))to pb model。after i run ckpt model and pb model，i find their result is different。and the result of ckpt model  is right。i check the pb model parmas， and find some op variable parmas is initial value，like “bias” is vector contain zero，“layer normal beta”  is vector contain zero eg.  i think it is  wrong to restore model, hope your give me some advice,thx

**Comment by gadagashwini** [comment]
@hahadashi, I tried reproducing the issue with Tf 2.0 but received different error. 
Please take a look at the [gist](https://colab.sandbox.google.com/gist/gadagashwini/9b25d752b3d77347cc8d727c54e96d1a/untitled488.ipynb) and provide the more information to analyze the issue. Thanks

**Comment by hahadashi** [comment]
> @hahadashi, I tried reproducing the issue with Tf 2.0 but received different error.
> Please take a look at the [gist](https://colab.sandbox.google.com/gist/gadagashwini/9b25d752b3d77347cc8d727c54e96d1a/untitled488.ipynb) and provide the more information to analyze the issue. Thanks

thx your response。 i use this way，have sovled problem，may be it is because of when i rebuild the model and i made  a minor mistake

**Comment by hahadashi** [comment]
> @hahadashi, I tried reproducing the issue with Tf 2.0 but received different error.
> Please take a look at the [gist](https://colab.sandbox.google.com/gist/gadagashwini/9b25d752b3d77347cc8d727c54e96d1a/untitled488.ipynb) and provide the more information to analyze the issue. Thanks

but i meet  a new problem。if i use pb model by c++ env，i try to inference by batch。 i set the same inputs，but these outputs are difference。have you try inference by bctch？if i set batch is one，the result is right

**Comment by gadagashwini** [comment]
@hahadashi, Can you raise the new issue with all the information asked in Template. Thanks

**Comment by hahadashi** [comment]
> @hahadashi, Can you raise the new issue with all the information asked in Template. Thanks

OK，thx your response!
