### ISSUE TITLE
 Floating point calculation error

### ISSUE THREAD

**Issue by JanMCHEN** [tensorflow/tensorflow#38238]
tensorflow2.0 and python3.7 
when i wanto calculate 165 * 3.1 or 165 * 2.1, i got a fake answer.
Like this:
tf.cast(165, tf.float32) * 2.1
Out: <tf.Tensor: id=43186, shape=(), dtype=float32, numpy=346.49997>
tf.cast(165, tf.float32) * 3.1
Out: <tf.Tensor: id=43261, shape=(), dtype=float32, numpy=511.49997>

i make sure its a error, but i wanto know why.

**Comment by abhinavsp0730** [comment]
Hey, @JanMCHEN  you're getting this type of answer because you're multiplying a tensor with the floating number.
please see the gist for doing this: https://colab.research.google.com/drive/1HD7ScmyvOSuoXz7z7iGW7fLk-S95itGe#scrollTo=GkHs7h9l32un
And If it doesn't solve your query, then feel free to reach out to us.

**Comment by JanMCHEN** [comment]
> Hey, @JanMCHEN you're getting this type of answer because you're multiplying a tensor with the floating number.
> please see the gist for doing this: https://colab.research.google.com/drive/1HD7ScmyvOSuoXz7z7iGW7fLk-S95itGe#scrollTo=GkHs7h9l32un
> And If it doesn't solve your query, then feel free to reach out to us.

Thanks, i just hope to get a correct answer when i calculated 165 * 2.1,it should be 346.5. I solved it through 165 * 2 * 2.1 / 2, it worked but it is means that i will get a wrong answer sometimes when i calculated the float number as a common way.
我母语是汉语，可能表示的不是很清楚，我想说的是这是不是意味着我用tensorflow做浮点运算时我应该时刻注意它的输出，因为其有可能不是正确的答案，或者这背后涉及到数据类型转换，我对C Language 了解一点，但还是不明白这个浮点运算为什么会出错。谢谢解答

**Comment by JanMCHEN** [comment]
@abhinavsp0730 You multiplyied the tensor with the tensor, but it still not the right answer of calculating the two floating numbers.

**Comment by abhinavsp0730** [comment]
> @abhinavsp0730 You multiplyied the tensor with the tensor, but it still not the right answer of calculating the two floating numbers.

Would you please be more specific what you're referring for the right answer? 
I don't used tf.math.multiply because, i think you're dealing with scalar.

**Comment by JanMCHEN** [comment]
@abhinavsp0730 When i wanto get a images'shape, it is expressed in tensors.Now i want to calculate its shape after expanding scale times.Usually i can get the shape by calulating "img.shape * scale", but you see when the shape is like(165,    ),scale equals to 2.1, i will get a confused anwser. 
   165 times to 2.1 should be 346.5 but i got 346.4999,then i fall into a bug. I'm training a 
Super resolution network with a floating times， and i can't calulate it through scalar.
