### ISSUE TITLE
AttributeError: 'TFLiteConverterV2' object has no attribute 'experimental_new_quantizer' due to TensorFlow 2.2.0rc2  in colab.research.google.com 

### ISSUE THREAD

**Issue by MeghnaNatraj** [tensorflow/tensorflow#38232]
**Describe the problem**
In colab, the default TF version is not a stable version (2.2.0rc2)
You can check this by opening a new notebook in [colab.research.google.com](colab.research.google.com) and running:

```
pip list | grep tensorflow

tensorflow               2.2.0rc2    
.
.
   
```

**Solution: **
Change the tensorflow version from the unstable 2.2.0rc2 to stable 2.2.0

**Provide the exact sequence of commands / steps that you executed before running into the problem**

As a result of the default unstable version, if I try to convert a model to a full-integer quantized model it fails due to this error:
```
# Convert the model to the TensorFlow Lite format with quantization
converter = tf.lite.TFLiteConverter.from_keras_model(model)
def representative_dataset():
  for i in range(500):
    yield([x_train[i].reshape(1,1)])
converter.optimizations = [tf.lite.Optimize.DEFAULT] 
converter.representative_dataset = representative_dataset
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
model_tflite = converter.convert()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-f5d45cb6910e> in <module>()
     12 converter.representative_dataset = representative_dataset
     13 converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
---> 14 model_tflite = converter.convert()
     15 
     16 # Save the model to disk

1 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py in _calibrate_quantize_model(self, result, inference_input_type, inference_output_type)
    265       return calibrate_quantize.calibrate_and_quantize(
    266           self.representative_dataset.input_gen, inference_input_type,
--> 267           inference_output_type, allow_float, self.experimental_new_quantizer)
    268 
    269   def _is_unknown_shapes_allowed(self):

AttributeError: 'TFLiteConverterV2' object has no attribute 'experimental_new_quantizer'
```

Removing the `converter.representative_dataset = representative_dataset` line, seems to work fine but is not a valid workflow for my use case.

**Current workaround**
If I uninstall `tensorflow==2.2.0rc2` and  instead install `tensorflow==2.2.0`, it seems to work as well. I simply run the following, at the beginning of my colab:

`pip install tensorflow==2.2.0`

This seems to resolve the issue.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
@MeghnaNatraj Thanks for the issue. We haven't released TF 2.2.0 final version yet.
We have 2.2.0rc0, 2.2.0rc1, 2.2.0rc2 packages. 
As of today 2.2.0rc2 is latest package, Colab will be updated once we have stable 2.2.0 released shortly.

**Comment by MeghnaNatraj** [comment]
Is it possible to instead have a stable version on Colab at all times? eg: TF 2.1?

**Comment by sayakpaul** [comment]
So, this problem is going to persist?

**Comment by MeghnaNatraj** [comment]
@sayakpaul Could you link your github issue here? Or post more details as a comment? Ideally, this should not occur for any stable version of TensorFlow.

**Comment by sayakpaul** [comment]
I just replied via the Google Group discussion.

Sayak Paul | sayak.dev

**Comment by ymodak** [comment]
Closing this issue now that colab hosts stable version. Also opened an [issue](https://github.com/googlecolab/colabtools/issues/1132) on google colab repo to address such issue in future. Thanks!
