### ISSUE TITLE
Adding shape to _tensor_array_scatter

### ISSUE THREAD

**Issue by OriAlpha** [tensorflow/tensorflow#38239]
How can I add shape to tensor_array_scatter? 
I have tried with the following code but this doesn't work 
![Screenshot from 2020-04-05 15-43-33](https://user-images.githubusercontent.com/41699212/78499993-4530b680-7754-11ea-9fc0-88f3c1f5274d.png)
is there another way to add shapes for graph

**Comment by gadagashwini** [comment]
@OriAlpha, Please provide the complete standalone code replicate the issue and share the Tensorflow version that you are using. Thanks!

**Comment by OriAlpha** [comment]
Here you can find the details about the script and model in google [drive](https://drive.google.com/drive/folders/1aVAva4Q5bFGafpKBbvuBcFz0yaaW7jNB?usp=sharing)

**Comment by OriAlpha** [comment]
The final output of the script is at variable graph_def but this doesn't have a shape for the nodes in it, example **tensor_array_scatter node** doesn't have  a shape

**Comment by gadagashwini** [comment]
@OriAlpha, Please take a look at the colab [gist](https://colab.sandbox.google.com/gist/gadagashwini/2f24faa8095ab8ff630ec76dabb6651c/untitled497.ipynb) and confirm the issue reproduced or not. Thanks

**Comment by OriAlpha** [comment]
No this not the issue it seems to work fine for me. The bug Is tensor_array_scatter doesn't get a shape

**Comment by gadagashwini** [comment]
@OriAlpha, Can you share the colab gist or complete code to analyze issue.Thanks

**Comment by OriAlpha** [comment]
i think found the issue, thanks
