### ISSUE TITLE
TensorFlow hangs: 0% GPU, 1 CPU core @ 100% in cuModuleUnload

### ISSUE THREAD

**Issue by fxtentacle** [tensorflow/tensorflow#38230]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04):  Windows 10 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: No
- TensorFlow installed from (source or
binary): Both. Bug first appeared in TF2 python package, then was reproduced using TF2 compiled from source.
- TensorFlow version (use command below): Both 2.1 (from PyPI) and 2.0 (source) appear affected
- Python version: 3.6.6 x64
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from
source): Visual Studio Professional 2017
- CUDA/cuDNN version: 10.0 & 10.1
- GPU model and memory: 1080 & 1080 TI

**Describe the current behavior**

At a random time during training, TensorFlow just stops progressing. I've seen this happen both after 200 iterations = roughly 1 minute and after 3000 iterations. 

**Describe the expected behavior**

TensorFlow either continues training, or it crashes with an error message.

**Standalone code to reproduce the issue** 

This happens in a rather large and complex project with partially proprietary source code. That said, I do have a full dump of Python & TensorFlow in that state, which is 30 GB. 

**Other info / logs** 

Attached is a dump of the stack traces of all threads, created with VS2017 `Debug.ListCallStack /ShowLineOffset /AllThreads `

[tensorflow callstacks.txt](https://github.com/tensorflow/tensorflow/files/4432702/tensorflow.callstacks.txt)

**My Analysis** 

The Python main thread is stuck in tensorflow::KernelAndDeviceFunc::Run > nsync::nsync_cv_wait, which seems reasonable. The other threads are idle in openblas or Eigen::ThreadPoolTempl::WaitForWork, except for one suspicious thread.

The suspicious thread (ID 7020 in the attached dump) is looping around with 100% CPU usage inside cuModuleUnload, which was called by stream_executor::gpu::GpuDriver::UnloadModule from within stream_executor::KernelBase::~KernelBase inside tensorflow::CheckRedzones and apparently attempting to execute a tensorflow::Conv2DOp

```
Callstack for Thread 74 (Thread Id: 7020 (0x1b6c)):
 Index  Function
--------------------------------------------------------------------------------
 1      [External Code]  =  cuModuleUnload
*2      _pywrap_tensorflow_internal.pyd!stream_executor::gpu::GpuDriver::UnloadModule(stream_executor::gpu::GpuContext * context, CUmod_st * module) Line 762
 3      _pywrap_tensorflow_internal.pyd!stream_executor::gpu::GpuExecutor::UnloadGpuBinary(const void * gpu_binary) Line 339
 4      _pywrap_tensorflow_internal.pyd!stream_executor::gpu::GpuExecutor::UnloadKernel(const stream_executor::KernelBase * kernel) Line 357
 5      _pywrap_tensorflow_internal.pyd!stream_executor::KernelBase::~KernelBase() Line 79
 6      _pywrap_tensorflow_internal.pyd!stream_executor::cuda::RedzoneAllocator::CheckRedzones() Line 340
 7      _pywrap_tensorflow_internal.pyd!tensorflow::CheckRedzones(const stream_executor::cuda::RedzoneAllocator & rz_allocator, tensorflow::AutotuneResult * autotune_result) Line 618
 8      _pywrap_tensorflow_internal.pyd!tensorflow::LaunchConv2DOp<Eigen::GpuDevice,float>::operator()(tensorflow::OpKernelContext * ctx, bool use_cudnn, bool cudnn_use_autotune, const tensorflow::Tensor & input_param, const tensorflow::Tensor & filter, int row_dilation, int col_dilation, int row_stride, int col_stride, const tensorflow::Padding & padding, const std::vector<__int64,std::allocator<__int64> > & explicit_paddings, tensorflow::Tensor * output, tensorflow::TensorFormat data_format) Line 1062
 9      _pywrap_tensorflow_internal.pyd!tensorflow::Conv2DOp<Eigen::GpuDevice,float>::Compute(tensorflow::OpKernelContext * context) Line 546
 10     _pywrap_tensorflow_internal.pyd!tensorflow::BaseGPUDevice::Compute(tensorflow::OpKernel * op_kernel, tensorflow::OpKernelContext * context) Line 582
 11     _pywrap_tensorflow_internal.pyd!tensorflow::`anonymous namespace'::ExecutorState::Process(tensorflow::`anonymous-namespace'::ExecutorState::TaggedNode tagged_node, __int64 scheduled_nsec) Line 1844
 12     [External Code]
 13     _pywrap_tensorflow_internal.pyd!Eigen::ThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int thread_id) Line 326
 14     [External Code]
```

So there is a reasonable chance that this is a CUDA 10.1 bug, because both the PyPI TF 2.1 and my self-compiled TF 2.0 use CUDA 10.1 to avoid triggering https://github.com/tensorflow/tensorflow/issues/31166

This might be related to https://github.com/tensorflow/tensorflow/issues/37450 where others also report a CPU-spike upon training freezing with TF2.0 and TF2.1. That would imply the bug to be present in CUDA 10.0 and 10.1.

**Comment by amahendrakar** [comment]
@fxtentacle,
In order to expedite the trouble-shooting process, is it possible to provide a minimal code sample to reproduce the issue reported here. Thanks!

**Comment by liuxingbaoyu** [comment]
Maybe related https://github.com/tensorflow/tensorflow/issues/36072

**Comment by amahendrakar** [comment]
> @fxtentacle,
> In order to expedite the trouble-shooting process, is it possible to provide a minimal code sample to reproduce the issue reported here. Thanks!

Any updates regarding this issue? Thanks!

**Comment by fxtentacle** [comment]
http://colab.research.google.com/gist/fxtentacle/0c19dc1ce013f4f98ff57b1261d4b644/tf_hang.ipynb

Expected result: It prints "................................done".

Actual result: It freezes. Repeatedly clicking the Stop button produces "The executing code is not responding to interrupts."

FYI, the tf.py_function is necessary because tf.image.extract_patches cannot handle Tensor inputs for sizes. See `gen_array_ops.py:2350 extract_image_patches`.

**Comment by fxtentacle** [comment]
Actually, I believe I might be seeing two different bugs being triggered randomly, because while this example surely freezes the runtime, my stack trace caught it freezing inside a Conv2D Op, while the Python example here does not include any Conv2D ops.

**Comment by fxtentacle** [comment]
The above example freezes on:
- TF 2.0 recompiled with CUDA 10.1 on my machine
- '2.1.0' PyPI package on my machine
- '2.2.0-rc2' on Colab
- '2.2.0-dev20200415' on Colab

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.2.0rc3 and TF-nightly. Code runs indefinitely and freezes on interrupting. Please find the gist [here](https://colab.research.google.com/gist/amahendrakar/261286c6844c713a4ab93f32b706bc22/38230.ipynb). Thanks!

**Comment by sanjoy** [comment]
@amahendrakar I was not able to reproduce this on tf-nightly.  Are you still able to reproduce this?

**Comment by amahendrakar** [comment]
> @amahendrakar I was not able to reproduce this on tf-nightly. Are you still able to reproduce this?

@sanjoy,
Yes, I am able to reproduce the issue with the stable version of TF v2.2 and TF-nightly. 
Code runs forever and never reaches the print statement. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/225d6850361258566ff3cb325325e839/38230.ipynb). Thanks!

**Comment by sanjoy** [comment]
George, can you PTAL?  It looks like something is weird about how the red zone allocator loads and unloads CUDA modules.

**Comment by cheshire** [comment]
I'll take a look a bit later, but it uses exactly the same codepath XLA does.
For now, does setting the environment variable `TF_DISABLE_RZ_CHECK` to 1 help?

**Comment by mohantym** [comment]
Hi @fxtentacle! 
Hi ! we are  checking to see if you are still looking for assistance in this issue.
Could you please try on latest stable version TF 2.6  and let us know if this is still an issue.Thanks!
