### ISSUE TITLE
very slow training if recurrent_dropout above 0.0 in LSTM keras using GPU

### ISSUE THREAD

**Issue by kubapok** [tensorflow/tensorflow#38236]
**System information** 
- Have I written custom code: yes
- OS Platform and Distribution: Linux Mint 19
- TensorFlow installed from: pip ( `pip install tensorflow-gpu` )
- TensorFlow version: 2.1.0 (same issue in 2.0.0 though)

- CUDA/cuDNN version: 10.2
- GPU model and memory: RTX 2080 8GB (same issue on RTX 2080Ti 11GB )

Hi!

When I use LSTM `recurrent_dropout` not set to 0.0, training time is very long (~25 times longer compared to `recurrent_dropout` 0.0). I suppose it shouldn't slow down the training that much I have the same issue on two separate machines

For example

`model.add(layers.LSTM(128, recurrent_dropout=0.0))` training time ~40 sec
`model.add(layers.LSTM(128, recurrent_dropout=0.1))` training time is above ~17 min.

```
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers
import tensorflow
import os
os.environ["TF_FORCE_GPU_ALLOW_GROWTH"]="true"


model = tf.keras.Sequential()
model.add(layers.Embedding(input_dim=1000, output_dim=64))
model.add(layers.LSTM(128, recurrent_dropout=0.1))
model.add(layers.Dense(1))

model.compile('sgd', 'mse')
model.summary()

x = np.random.rand(100000, 1000)
y = np.random.randint(1, size = (100000,1))
model.fit(x,y,10)
```

**Comment by Saduf2019** [comment]
i have replicated the above mentioned issue, please find the gist here for [recurrent_dropout=0.0](https://colab.sandbox.google.com/gist/Saduf2019/901bc99480dfde6ac22aa608cf407a6d/untitled127.ipynb) and [recurrent_dropout=0.1](https://colab.sandbox.google.com/gist/Saduf2019/e5a231833e080661b48e11d83593336c/untitled126.ipynb)

**Comment by qlzh727** [comment]
This is expected since recurrent_dropout will force the LSTM to use generic kernel, rather than the performant cudnn kernel on GPU.

Please see the section of LSTM docstring about the restriction of cudnn kernel usage in https://www.tensorflow.org/api_docs/python/tf/keras/layers/LSTM

**Comment by biarne-a** [comment]
A trick that worked for me.
Replace usage tf.keras.layers.GRU with:
tf.keras.layers.RNN(keras.layers.GRUCell(hidden_size, recurrent_dropout=dropout_p_hidden)).
This increased a bit training time but only by a factor of 1.5 instead of 100.
