### ISSUE TITLE
Train a Simple Audio Recognition model for microcontroller use build issue

### ISSUE THREAD

**Issue by ms-ims** [tensorflow/tensorflow#38246]
I'm not able to install dependencies in Colab in this Train a Simple Audio Recognition model for microcontroller model.
Error shows:
1. Could not find a version that satisfies the requirement tf-nightly-gpu==1.15.0.dev20190729
2. No matching distribution found for tf-nightly-gpu==1.15.0.dev20190729

Can someone guide how to resolve it?

**Comment by gadagashwini** [comment]
@ms-ims, Currently, Tf-nightly-gpu version is 2.2.0.dev20200405, For more read [here](https://pypi.org/project/tf-nightly-gpu/). To install tf 1.15.
Try, pip install tensorflow==1.15. Thanks

**Comment by ms-ims** [comment]
@gadagashwini , Hi, I understood that current version of Tf-nightly-gpu version is 2.2.0.dev20200405 but if I install Tf-nightly-gpu version is 2.2.0.dev20200405 version the code present on colab for this model still create issue while building further.

**Comment by gadagashwini** [comment]
@ms-ims, Can you share the error log that you are facing. Thanks

**Comment by ms-ims** [comment]
Hi @gadagashwini Thanks for your support. That issue is resolved, script is updated by that content provider. So now its building properly.
