### ISSUE TITLE
TensorFlow Lite image_segmentation example for iOS doesn't build

### ISSUE THREAD

**Issue by robdeputter** [tensorflow/tensorflow#38241]
## URL(s) with the issue:
https://github.com/tensorflow/examples/tree/master/lite/examples/image_segmentation/ios
## Description of issue (what needs changing):

The README must be provided with an explanation of how to change the settings of the project. At the moment I have problems adjusting the development team ("**Signing**").
Error message: No profile for team 'Rob De Putter (Personal Team)' matching 'Wildcard' found: Xcode couldn't find any provisioning profiles matching 'GPC87JXMXD/Wildcard'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the Signing & Capabilities tab of the target editor.

<img width="1421" alt="Schermafbeelding 2020-04-05 om 14 54 09" src="https://user-images.githubusercontent.com/36565271/78500273-4f9b8200-774d-11ea-8b6a-4f214fa2fe81.png">
<img width="1154" alt="Schermafbeelding 2020-04-05 om 14 54 37" src="https://user-images.githubusercontent.com/36565271/78500283-6641d900-774d-11ea-9bca-6aec48736816.png">
<img width="1152" alt="Schermafbeelding 2020-04-05 om 14 54 30" src="https://user-images.githubusercontent.com/36565271/78500289-6cd05080-774d-11ea-984b-d6f3710d8f08.png">

**Comment by yyoon** [comment]
Could you check if the `Wildcard` provisioning profile that you're using contains your Development Team identity correctly? This article might help:
https://medium.com/ios-os-x-development/ios-code-signing-provisioning-in-a-nutshell-d5b247760bef
