### ISSUE TITLE
register keras serializables is module_objects

### ISSUE THREAD

**Issue by jackd-msft** [tensorflow/tensorflow#38245]
**System information**
- TensorFlow version (you are using): 2.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
I've been using keras serialization and while it mostly works well, I have two issues:
* there seems to be duplicated functionality in `get` and `deserialize` across `tf.keras` submodules, and inconsistent support (e.g. no `tf.keras.layers.get`).
* use with custom implementations via  `tf.keras.utils.register_keras_serializable` gives odd and potentially surprising results.

These are illustrated in the below examples:
```python
import tensorflow as tf

register = tf.keras.utils.register_keras_serializable('my_package.layers')

@register
class MyLayer(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

layer = MyLayer()
config = tf.keras.utils.serialize_keras_object(layer)

print(tf.keras.layers.deserialize(config))      # works - but why no layers.get?
print(tf.keras.optimizers.get(config))          # works - but should it?
```

Something like the following could reduce code duplication across different modules and make them extensible and more resilient to errors.

```python
class Serializer(object):
    def __init__(self, accepted_types=None, module_name=None):
        self._module_objects = {}
        self._module_name = module_name
        self._accepted_types = accepted_types
    
    def register(self, fn_or_class: Callable):
        assert callable(fn_or_class)
        name = fn_or_class.__name__
        if name in self._module_objects:
            raise ValueError(
                f'Could register {name} - already in {self._module_name} '
                'module_objects')
        self._module_objects[name] = fn_or_class
        return fn_or_class
    
    def deserialize(self, config, custom_objects=None):
        return tf.keras.utils.deserialize_keras_object(
            config, module_objects=self._module_objects,
            custom_objects=custom_objects,
            printable_module_name=self._module_name)
    
    def _get_fallback(self, identifier):
        raise ValueError(
            f'Could not interpret optimizer identifier: {identifier}')
    
    def get(self, identifier):
        if isinstance(identifier, self._accepted_types):
            return identifier
        elif isinstance(identifier, str):
            identifier = dict(class_name=identifier, config={})
        if isinstance(identifier, dict):
            return self.deserialize(identifier)
        else:
            return self._get_fallback(identifier)

# in layers.py
_serializer = Serializer(Layer, 'layers')
get = _serializer.get
deserialize = _serializer.deserialize
register = _serializer.register

# in optimizers.py
class OptimizerSerializer(Serializer):

    def __init__(self):
        self.__init__(Optimizer, 'optimizers')

    def _get_fallback(self, identifier):
        if isinstance(identifier, tf_optimizer_module.Optimizer):
            opt = TFOptimizer(identifier)
            K.track_tf_optimizer(opt)
            return opt
        else:
            return super()._get_fallback(identifier)

_serializer = OptimizerSerializer()
get = _serializer.get
deserialize = _serializer.deserialize
register = _serializer.register
```

**Will this change the current api? How?**
* Add `register` function to each of `tf.keras.[layers,optimizers,...]`
* Add `tf.keras.layers.get`

**Who will benefit with this feature?**
People who want to use keras serialization/deserialization with custom objects and retain error checking

**Any Other info.**
More than happy to put the PR together myself if the idea is likely to be accepted. Also happy to put in `package` support similar to `tf.keras.utils.register_keras_serializable`.

**Comment by tilakrayal** [comment]
@jackd-msft,
Could you please let us know where  the subsclassed model and the initializer is used in a custom layer there. Also there is an official doc reference available with **Making new Layers and Models via subclassing** on the similar line. 
Please have a look at the doc and let us know if it helps. 
https://www.tensorflow.org/guide/keras/custom_layers_and_models
Thank you!
