### ISSUE TITLE
How to deal with variable length weight category features in tensorflow?

### ISSUE THREAD

**Issue by mrchor** [tensorflow/tensorflow#38244]
How to deal with variable length weight category features in tensorflow?

For example:

 `vocabulary_list=['A','B','C']`

The original feature format is as follows:

`    [
    'A:1.5,B:0.3,C:0.8',
    'D:0.9,B:1.8',
    'A:1.2,B:3.2,E:1.5'
    ]`

After treatment, the results are as follows:

`    [
    [1.5,0.3,0.8,0.0],
    [0.0,1.8,0.0,0.9],
    [1.2,3.2,0.0,1.5]
    ]`

Please help me~~~

Thank you very much~~~

**Comment by saikumarchalla** [comment]
@mrchor Could  you please share a simple standalone code to reproduce the issue? Thanks!

**Comment by mrchor** [comment]
Sorry, this is not a tensorflow issue. I need a tensorflow code to solve the problem of handling the above features. To be honest, I don't know how to do the above feature processing now. Can you provide such a code? Thank you very much~

**Comment by mrchor** [comment]
That is to say, I need a code like the above feature handling process.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!

**Comment by mrchor** [comment]
。。。
