### ISSUE TITLE
gpu-jupyter.Dockerfile has bugs - docker build fails.

### ISSUE THREAD

**Issue by kunalvshah** [tensorflow/tensorflow#38247]
After yesterday's edit, few bugs surfaced in gpu-jupyter.Dockerfile
file url tensorflow/tools/dockerfiles/dockerfiles/gpu-jupyter.Dockerfile

1) line #81 should have \ 
python3 \
2) line #100 should be 
RUN python3 -m pip  install --no-cache-dir ${TF_PACKAGE}${TF_PACKAGE_VERSION:+==${TF_PACKAGE_VERSION}} 

without these changes, docker build fails.

**Comment by kunalvshah** [comment]
I think the file that needs to be changed is
tensorflow/tensorflow/tools/dockerfiles/partials/ubuntu/python.partial.Dockerfile

**Comment by angerson** [comment]
Thanks! I'm working on some changes to fix this right now.
