### ISSUE TITLE
Encountered error while reading extension file 'swift/repositories.bzl': no such package '@build_bazel_rules_swift//swift'

### ISSUE THREAD

**Issue by wadewangpower** [tensorflow/tensorflow#38240]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 18.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version:1.14.0(CPU)
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?:sudo pip3 tensorflow==1.14.0
- Bazel version (if compiling from source):0.24.1
- GCC/Compiler version (if compiling from source):NA
- CUDA/cuDNN version: 0
- GPU model and memory:GTX1660ti 6G

**Describe the problem**
I am follwing this [instruction](https://programmer.ink/think/tensorflow-android-side-compile-procedure-record.html#1Bazel_0241_18) to build so and jar file, but i got following error:
![Snipaste_2020-04-05_21-46-33](https://user-images.githubusercontent.com/43233772/78500087-1a138a80-7787-11ea-85be-64240302a05c.png)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
As shown in above image

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@wadewangpower 
is there any particular reason to be using 1.14 version, do you want to try on any later version?

please refer to this [link](https://www.tensorflow.org/install/source#setup_for_linux_and_macos)
please refer to these links and let us know if they help
#26553 #27352 #30111 #25644 #25747

**Comment by wadewangpower** [comment]
> @wadewangpower
> is there any particular reason to be using 1.14 version, do you want to try on any later version?
> 
> please refer to this [link](https://www.tensorflow.org/install/source#setup_for_linux_and_macos)
> please refer to these links and let us know if they help
> #26553 #27352 #30111 #25644 #25747

There is no particular reason that i have to use 1.14 version, just because i saw this [instruction](https://programmer.ink/think/tensorflow-android-side-compile-procedure-record.html#1Bazel_0241_18) which provide all other matched version, so i followed  it. If i don't use tf1.14, which version do you recommend ? and is there any tutorial with this tf version ? Thanks !

**Comment by Saduf2019** [comment]
@wadewangpower 
please  follow the link https://www.tensorflow.org/install/source and select the release branch 2.1

**Comment by wadewangpower** [comment]
> @wadewangpower
> please follow the link https://www.tensorflow.org/install/source and select the release branch 2.1

Afterwards, i found i temporarily don't need to build this .so file. If in the future i still need to build file with bazel in ubuntu os, i will try your advice~

**Comment by Saduf2019** [comment]
@wadewangpower
in that case please confirm if we may move this issue to closed status
