### ISSUE TITLE
tensorflow build from source issue on Window 10 (Taking too much time)

### ISSUE THREAD

**Issue by kumaradi08** [tensorflow/tensorflow#38254]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Window 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.1
- Python version: 3.6
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 0.27.2
- GCC/Compiler version (if compiling from source): VS2017
- CUDA/cuDNN version: NA
- GPU model and memory: NA

I am trying to build tensorflow from source on Window 10. I override the eigen strong inline to reduce the compile time. The build is stuck at:
[4,915 / 4,918] Compiling tensorflow/core/kernels/mkl_cwise_ops_common.cc; 72789s local

Any ideas why it is taking long time to compile this file?

I used the following command to start the build process:
bazel build --config=mkl -c opt --copt=/arch:AVX --copt=/arch:AVX2 --copt=/std:c++17 --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --define=override_eigen_strong_inline=true //tensorflow:tensorflow.dll

**Comment by mihaimaruseac** [comment]
The build unfortunately takes a long time. Furthermore, if the RAM usage is bigger than RAM available the build will crawl even slower as it needs to use swap.

**Comment by kumaradi08** [comment]
Is it normal to have one file taking that much long time to compile? It is still compiling and I don't see issue with the RAM usage.

[4,915 / 4,918] Compiling tensorflow/core/kernels/mkl_cwise_ops_common.cc; 176224s local

If I don't use MKL flag, the build compiles fine.

**Comment by mihaimaruseac** [comment]
Template expansion takes a lot of time during compiling, especially on Windows. If you want, you can open a bug against Visual Studio about this

**Comment by gadagashwini** [comment]
@kumaradi08, Please update for the @mihaimaruseac's comment.

**Comment by kumaradi08** [comment]
@mihaimaruseac, Okay I will follow up with them. As of now I will wait for it to get compiled as it is. Thanks.

**Comment by ya-mouse** [comment]
How much RAM does is require? I have 32GB of RAM, this file compiles for 3 hours already. The usage by CL doesn't exceed 6 GB. System has 14 GB free.

**Comment by kumaradi08** [comment]
I have 48 Gb RAM and I have to wait ~50 hours to get that one file compile.

**Comment by ya-mouse** [comment]
finally it was compiled, but has failed at linkage with concerns of multiple symbols definitions

**Comment by karllessard** [comment]
Hi, I'm suffering from that turbulence as well as I'm trying to release TensorFlow for Java, it's been compiling for 4 hours now and reading this thread made my want to cry. Is there any trick that can speed that up?

**Comment by saudet** [comment]
I wonder if it's related to issue #10521. Maybe `sed s/inline//g tensorflow/core/util/mkl_util.h` could work around this?

**Comment by karllessard** [comment]
Well I have some good new about this, after talking with SIG Build folks, it happens that with VS16.4+, you can add this option and it will drastically decrease the compile time of these functions: `--copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions`.

**Comment by saudet** [comment]
Maybe the build can succeed even with GitHub Actions now?

**Comment by karllessard** [comment]
@saudet : yes, I want to try this right after this release, let's hope!

**Comment by mihaimaruseac** [comment]
> Well I have some good new about this, after talking with SIG Build folks, it happens that with VS16.4+, you can add this option and it will drastically decrease the compile time of these functions: `--copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions`.

Perhaps we should add this to building from source on Windows page?

**Comment by karllessard** [comment]
@mihaimaruseac : These options [have been added](https://github.com/tensorflow/tensorflow/blob/3cbb50768909c585d33e99ba10172d1c44c04d6f/configure.py#L1205) in TensorFlow's configure script 11 months ago, I think standard users probably already saw the improvements without doing anything. It is just that in the case of TensorFlow for Java, we build TF with our own configuration in a CI workflow and this new flag was missing. Still, it might be worth mentioning that this makes a huge difference in case somebody else is trying to configure a CI build for TF.

Looking at the mention though, it says that this flag is not integral part of the `.bazelrc` because VS16.4 was not out at that time. Now that it is, I think it can safely be added in it without any condition.
