### ISSUE TITLE
problem of compling tensorflow due to installation

### ISSUE THREAD

**Issue by fatmafarah** [tensorflow/tensorflow#38252]
I have a problem with compling with tensorflow in jupyternotebook. This is the error message
Traceback (most recent call last):

```
File "c:\users\home\miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)

File "", line 1, in
import tensorflow as tf

File "c:\users\home\miniconda3\lib\site-packages\tensorflow_init_.py", line 22, in
from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import

File "c:\users\home\miniconda3\lib\site-packages\tensorflow\python_init_.py", line 49, in
from tensorflow.python import pywrap_tensorflow

File "c:\users\home\miniconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in
from tensorflow.python.pywrap_tensorflow_internal import *

File "c:\users\home\miniconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 114
def TFE_ContextOptionsSetAsync(arg1, async):
^
SyntaxError: invalid syntax
```

just to make it clearer, maybe it is an installation problem.
well pip install tensorflow didn't work at first, I had this messag error

```
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```

so I used this line that I found somewhere to install tensorflow

```
pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.0.0-py3-none-any.whl
```

and then I needed the version 1.10.0 of tensorflow so I wrote the same line above but with the different version

```
pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.10.0-py3-none-any.whl
```

that's it, then I tried to compile in jupyternotebook with tensorflow and it didn't work :(

**Comment by mihaimaruseac** [comment]
Please fill in issue template

**Comment by Saduf2019** [comment]
@fatmafarah 
please let us know the tensorflow version on which error is faced.
We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

As per error please refer to below issue if it helps
#31058

**Comment by Saduf2019** [comment]
@fatmafarah
please update as per above comment

**Comment by Saduf2019** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
