### ISSUE TITLE
Import error in tensorflow_datasets

### ISSUE THREAD

**Issue by AarshApple** [tensorflow/tensorflow#38253]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): MAC OS Catalina
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: NA
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): pip install tensorflow

**Describe the current behavior**

> ModuleNotFoundError: No module named 'tensorflow.compat'

I encountered this error after trying to import tensorflow datasets

**Describe the expected behavior**
No import error

**Standalone code to reproduce the issue** 
> import tensorflow_datasets as tfds

**Other info / logs** 

<img width="550" alt="Screen Shot 2020-04-05 at 17 55 04" src="https://user-images.githubusercontent.com/32034407/78510896-96e23c80-7766-11ea-8402-17708436becd.png">

**Comment by Saduf2019** [comment]
@AarshApple 
Could you please let us know the tensorflow version on which error is faced, share a simple stand alone code before which this error was faced for us to replicate it.

as per the error shared please refer to [this link](https://github.com/tensorflow/tensorflow/issues/26546) and let us know if that helps.
#106 [link](https://stackoverflow.com/questions/56920995/not-able-to-import-tensorflow-datasets-module-in-jupyter-notebook), [link2](https://www.heatonresearch.com/2019/09/03/tf-no-module-jupyter.html)

**Comment by Saduf2019** [comment]
@AarshApple
Could you please update as per above comment

**Comment by Saduf2019** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
