### ISSUE TITLE
tensorflow issue

### ISSUE THREAD

**Issue by fatmafarah** [tensorflow/tensorflow#38255]
Hey, I can't install tensorflow
If I write pip install tensorflow the error message is 
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
 please help
thank you

**Comment by mihaimaruseac** [comment]
Closing as no issue template being filled and as there are 2 other similar issues opened by the same user in the same time interval. Deduplicating to #38252
