### ISSUE TITLE
Incompatible shapes when loading model with TextVectorization and Embedding + Conv1D

### ISSUE THREAD

**Issue by swierchola** [tensorflow/tensorflow#38250]
There is **ValueError: Shapes incompatible** when trying to load_model with **TextVectorization** and **Embedding** + **Conv1D** (or **LSTM** or **GRU**).

It can be easily replicated using _TextVectorization layer examples_ from TF documentation. You just need to add _model save & load_ to _Using the TextVectorization layer in an Embedding + Conv1D model_ sample.
I created [copy of TextVectorization layer examples colab with these errors](https://colab.research.google.com/drive/1MavOxANGMkDGo8Ob4Lm3H43CY41dON7t). Code added to original example:
```python
model.save('my_model')
loaded_model = tf.keras.models.load_model('my_model')
```
Error from load_model execution:
```python
WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. 
Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.

Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.embeddings.Embedding object at 0x7f31fe4d8320> and <tensorflow.python.keras.saving.saved_model.load.TextVectorization object at 0x7f31fe4d8b70>).

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py in assert_is_compatible_with(self, other)
   1115     """
   1116     if not self.is_compatible_with(other):
-> 1117       raise ValueError("Shapes %s and %s are incompatible" % (self, other))
   1118 
   1119   def most_specific_compatible_shape(self, other):

ValueError: Shapes (128, 128) and (7, 128, 128) are incompatible
```
This error do NOT occur when trying to do _save & load_ in example: [_Using the TextVectorization layer in a bigram TF-IDF densely-connected model_](https://colab.research.google.com/drive/1RvCnR7h0_l4Ekn5vINWToI9TNJdpUZB3). This example contains only Dense and Dropout layers and do not contain Embedding and Conv1D.

I also found same problem for my custom models using LSTM and GRU.

Problem occurred for nightly TF version `2.2.0-dev20200405`

**Comment by gadagashwini** [comment]
Was able to reproduce the issue with Tf == 2.2.0-dev20200406,
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/854c310a2ebd436813b2fc61a112aef8/untitled489.ipynb). Thanks!

**Comment by imartinezl** [comment]
> Was able to reproduce the issue with Tf == 2.2.0-dev20200406,
> Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/854c310a2ebd436813b2fc61a112aef8/untitled489.ipynb). Thanks!

Hi @swierchola

I have loaded the model commented by @gadagashwini using tf-nightly==2.3.0-dev20200611, and it works without prompting any errors. The inference also works well. It would be great to know if you get the same results so that this issue can be closed.

**Comment by swierchola** [comment]
@imartinezl I confirm that problem is solved in latest tf-nightly. Probably commit [Fix dimensionality handling issues in TextVectorization](https://github.com/tensorflow/tensorflow/commit/a92ff929b818c7dbca2d0c2648ae17e8d6ae3a40#diff-14a0a5dcf758d55726b80920a2896a21) fixed it. Thanks.

**Comment by k-w-w** [comment]
This may be broken again with the latest changes. Please make sure that TextVectorization and the custom standardization layer are registered when loading. 
```
loaded_model = tf.keras.models.load_model(
    'my_model', 
    custom_objects={'TextVectorization':TextVectorization, 
                    'custom_standardization':custom_standardization})
```
