### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot assign a device for operation

### ISSUE THREAD

**Issue by bewithme** [tensorflow/tensorflow#38265]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): 

- Linux version : 3.10.0-862.el7.x86_64 
- TensorFlow installed from : binary
- TensorFlow version (use command below): tensorflow_gpu==1.14.0
- Python version: - 2.7.5

- CUDA/cuDNN version: NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1
- GPU model and memory:

**Describe the current behavior**
I convert a pre-trained tensorflow model to .pb file with python code as bellow

`
import tensorflow as tf
from argparse import ArgumentParser

def main():
    parser = ArgumentParser()
    parser.add_argument('--checkpoint', type=str,
                        dest='checkpoint',
                        help='dir or .ckpt file to load checkpoint from',
                        metavar='CHECKPOINT', required=True)
    parser.add_argument('--model', type=str,
                        dest='model',
                        help='.meta for your model',
                        metavar='MODEL', required=True)
    parser.add_argument('--out-path', type=str,
                        dest='out_path',
                        help='model output directory',
                        metavar='MODEL_OUT', required=True)
    opts = parser.parse_args()
    tf.reset_default_graph()
    saver = tf.train.import_meta_graph(opts.model)
    #builder = tf.saved_model.builder.SavedModelBuilder(opts.out_path)
    with tf.Session(config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=True)) as sess:
        # Restore variables from disk.
        saver.restore(sess, opts.checkpoint)
        print("Model restored.")
        #builder.add_meta_graph_and_variables(sess,['tfckpt2pb'],strip_default_attrs=False)
        #builder.save()
        constant_graph = tf.graph_util.convert_variables_to_constants(sess, sess.graph_def, ['Tower_0/parsing_fc/BiasAdd','Tower_0/parsing_rf_fc/BiasAdd','Tower_0/edge_rf_fc/BiasAdd'])

        with tf.gfile.FastGFile(opts.out_path, mode='wb') as f:
                f.write(constant_graph.SerializeToString())
                print("pb Model saved.")

if __name__ == '__main__':
    main()

   ` and I import the .pb model with java code as bellow
 `         //import model
              byte[] graphBytes = IOUtils.toByteArray(new FileInputStream(MODEL_PATH));

              graph.importGraphDef(graphBytes);

              //create session
              try(Session session = new Session(graph)){

                  ConfigProto config = ConfigProto.newBuilder()
                          .setGpuOptions(GPUOptions.newBuilder().setAllowGrowth(true))
                          .build();
                   //get the output
                  Tensor<?> output = session.runner()
                          .setOptions(config.toByteArray())
                          .feed("Tower_0/strided_slice", imageTensor)
                          .fetch("Tower_0/parsing_fc/BiasAdd").run().get(0);
                  System.out.println(output);
              }`

then error as bellow
`here are error message 2020-04-06 12:13:50.269556: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA 2020-04-06 12:13:50.281419: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2600000000 Hz 2020-04-06 12:13:50.288167: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f968ded1db0 initialized for platform Host (this does not guarantee that XLA will be used). Devices: 2020-04-06 12:13:50.288206: I tensorflow/compiler/xla/service/service.cc:176] StreamExecutor device (0): Host, Default Version java.lang.IllegalArgumentException: Cannot assign a device for operation Tower_0/strided_slice: {{node Tower_0/strided_slice}} was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device. The requested device appears to be a GPU, but CUDA is not enabled. [[Tower_0/strided_slice]] at org.tensorflow.Session.run(Native Method) at org.tensorflow.Session.access$100(Session.java:48) at org.tensorflow.Session$Runner.runHelper(Session.java:326) at org.tensorflow.Session$Runner.run(Session.java:276) at `

**Describe the expected behavior**
  it can correctly run up

**Comment by gadagashwini** [comment]
@bewithme, Can you provide the proper intended stand alone code to reproduce the issue.Thanks!

**Comment by gadagashwini** [comment]
@bewithme, Can you update for the above comment.

**Comment by Saduf2019** [comment]
@bewithme,
please update as per above comment

**Comment by bewithme** [comment]
> @bewithme, Can you provide the proper intended stand alone code to reproduce the issue.Thanks!

here are code and model https://gist.github.com/bewithme/82b588e2b7b86c8e211e02aff5ea573c

thank you so much

**Comment by Saduf2019** [comment]
@bewithme 
i ran the code shared, please find the error faced [here](https://colab.sandbox.google.com/gist/Saduf2019/2cac10919b20364aa0c7a89fbabe3283/untitled152.ipynb), please provide with simple stand alone code[indented] such that we could relpicate the issue faced
