### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Nipsa24** [tensorflow/tensorflow#38262]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows 10
- TensorFlow installed from (source or binary):
- TensorFlow version: 2.1
- Python version: 3.7.7
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
ImportError: Could not find the DLL(s) 'msvcp140.dll or msvcp140_1.dll'. TensorFlow requires that these DLLs be installed in a directory that is named in your %PATH% environment variable. You may install these DLLs by downloading "Microsoft C++ Redistributable for Visual Studio 2015, 2017 and 2019" for your platform from this URL: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads
**Provide the exact sequence of commands / steps that you executed before running into the problem**
Installed python 3.7.7 from python.org
installed Microsoft C++ Redistributable for Visual Studio 2015, 2017 and 2019 from the said platform.
Installed Tensorflow using powershell command "pip install tensorflow " .
Ran Powershell Command python -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))" to check if the installation was successfull.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@Nipsa24,
Could you please verify if you have installed the [vc_redist.x64.exe](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) file?

Also, please check [this comment](https://github.com/tensorflow/tensorflow/issues/27816#issuecomment-609096989) from a similar issue and let us know it is helps. Thanks!

**Comment by mihaimaruseac** [comment]
The error you have gives exactly the solution

```
ImportError: Could not find the DLL(s) 'msvcp140.dll or msvcp140_1.dll'. TensorFlow requires that these DLLs be installed in a directory that is named in your %PATH% environment variable. You may install these DLLs by downloading "Microsoft C++ Redistributable for Visual Studio 2015, 2017 and 2019" for your platform from this URL: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads
```

You need to download the MSVC redistributable and place it in a directory that is within the directories contained in `%PATH%`. 

As this is not a TF issue and is already duplicated in many places, closing.
