### ISSUE TITLE
Train simple audio recognition 

### ISSUE THREAD

**Issue by rajaniyadav** [tensorflow/tensorflow#38270]
@petewarden 
@tensorflow/micro

**System information**

- OS Platform and Distribution -Windows 8
- TensorFlow installed from (source or binary): - 
-TensorFlow version - 2.2.0.dev20200210
- Python version: - 3.6 version (if compiling from source):
- CUDA/cuDNN version: - GPU not supported in my system trying to train model in colab

###  Describe the current behavior
I am trying to train a simple audio recognition model as described in book "TinyML" . I am using colab to train the model. 
First I got the error while Install Dependencies "ERROR: Could not find a version that satisfies the requirement tf-nightly-gpu==1.15.0.dev20190729 (from versions: 2.2.0.dev20200210, 2.2.0.dev20200211, ...)
ERROR: No matching distribution found for tf-nightly-gpu==1.15.0.dev20190729"
As temsorflow version 1.5 is not supported is replaced the version by 2.2.0.dev20200210 , this error got resolved.

Again while "Begin Training" I got error "Traceback (most recent call last):
  File "tensorflow/tensorflow/examples/speech_commands/train.py", line 81, in <module>
    import input_data
  File "/content/tensorflow/tensorflow/examples/speech_commands/input_data.py", line 35, in <module>
    from tensorflow.contrib.framework.python.ops import audio_ops as contrib_audio
ModuleNotFoundError: No module named 'tensorflow.contrib"

Please provide the exact sequence of commands/steps to solve above problem and train the simple audio in colab.

**Comment by ravikyram** [comment]
@rajaniyadav 

tf.contrib no longer exists in post-2.0 world. It has been moved (partially) to TF Addons.

If you really want tf.contrib, you can use TF 1.15 for the next 3 years, but after that you will have to switch as there won't be a TF 1.16 or later.

Also,you check  whether you have 64-bit version of Python (32-bit will not support).Thanks!

**Comment by rajaniyadav** [comment]
Hi,
Is there any way that we can migrate this code to tensorflow 2.0 version?

**Comment by ravikyram** [comment]
@rajaniyadav 

can you please go through the [link ](https://www.tensorflow.org/guide/migrate?hl=en)and see if it helps you.Thanks!

**Comment by rthadur** [comment]
S

**Comment by ravikyram** [comment]
@rajaniyadav 

Any update on this issue please. Thanks!

**Comment by rajaniyadav** [comment]
Hi 
Thank you for responding. The above bug is recently fix by the owner of the model.

**Comment by ravikyram** [comment]
@rajaniyadav 

Glad to know the issue got fixed.Please close this thread, as the issue got resolved.. Thanks!

**Comment by rajaniyadav** [comment]
Issue resolved so closing it.
