### ISSUE TITLE
TPU Bug when using categorical_crossentropy

### ISSUE THREAD

**Issue by HarshitSheoran** [tensorflow/tensorflow#38272]
ResourceExhaustedError: {{function_node _inferencedistributedfunction153395}} Compilation failure: Ran out of memory in memory space vmem. It should not be possible to run out of vmem - please file a bug against XLA.

Largest program allocations in vmem:

XLA label: register allocator spill slots
Allocation type: scoped

XLA label: %fusion.11963 = f32[4,192,1024]{2,0,1:T(4,128)} fusion(f32[4,1,1024]{2,0,1:T(4,128)}, f32[4,1,1024]{2,0,1:T(4,128)}, f32[4,1,1024]{2,0,1:T(4,128)}, f32[4,1,1024]{2,0,1:T(4,128)}, …(+188)), kind=kLoop, calls=%fused_computation.10858
Allocation type: scoped

XLA label: %fusion.11963 = f32[4,192,1024]{2,0,1:T(4,128)} fusion(f32[4,1,1024]{2,0,1:T(4,128)}, f32[4,1,1024]{2,0,1:T(4,128)}, f32[4,1,1024]{2,0,1:T(4,128)}, f32[4,1,1024]{2,0,1:T(4,128)}, …(+188)), kind=kLoop, calls=%fused_computation.10858
Allocation type: scoped

XLA label: %fusion.11963 = f32[4,192,1024]{2,0,1:T(4,128)} fusion(f32[4,1,1024]{2,0,1:T(4,128)}, f32[4,1,1024]{2,0,1:T(4,128)}, f32[4,1,1024]{2,0,1:T(4,128)}, f32[4,1,1024]{2,0,1:T(4,128)}, …(+188)), kind=kLoop, calls=%fused_computation.10858
Allocation type: scoped

XLA label: %fusion.11963 = f32[4,192,1024]{2,0,1:T(4,128)} fusion(f32[4,1,1024]{2,0,1:T(4,128)}, f32[4,1,1024]{2,0,1:T(4,128)}, f32[4,1,1024]{2,0,1:T(4,128)}, f32[4,1,1024]{2,0,1:T(4,128)}, …(+188)), kind=kLoop, calls=%fused_computation.10858
Allocation type: scoped

TPU compilation failed
 [[{{node tpu_compile_succeeded_assert/_5292462253713114861/_5}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add reporttensorallocationsuponoom to RunOptions for current allocation info.

**Comment by gadagashwini** [comment]
@HarshitSheoran, Please provide the complete standalone code reproduce the issue and also share the Tensorflow version information. Thanks.

**Comment by HarshitSheoran** [comment]
`def build_model(transformer, max_len=512):
    """
    https://www.kaggle.com/xhlulu/jigsaw-tpu-distilbert-with-huggingface-and-keras
    """
    input_word_ids = Input(shape=(max_len,), dtype=tf.int32, name="input_word_ids")
    sequence_output = transformer(input_word_ids)[0]
    cls_token = sequence_output[:, 0, :]
    out = Dense(1, activation='sigmoid')(cls_token)
    
    model = Model(inputs=input_word_ids, outputs=out)
    model.compile(Adam(lr=1e-5), loss='categorical_crossentropy', metrics=['acc'])
    
    return model`

**Comment by HarshitSheoran** [comment]
you get the idea, sry I have some bugs in my browser to github comments, it does not let me put everything in code sometimes.

**Comment by HarshitSheoran** [comment]
Use any transformer from `import transformers`

**Comment by gadagashwini** [comment]
@HarshitSheoran, Can you share the modified complete code to analyze the issue. Thanks

**Comment by HarshitSheoran** [comment]
Actually, I did give enough code, also, I linked to kernel to get even more information to code, okay, so you can see it as, copy the whole kernel and just change the loss to "categorical_crossentropy", that should reproduce, sorry but I can not give exact code I use to achieve my highest score in a competition.

**Comment by Saduf2019** [comment]
@HarshitSheoran,
as requested for, could you please share the tensorflow version

**Comment by amahendrakar** [comment]
@HarshitSheoran,
I was able to run the code without any issues with TF v2.2.0rc2, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/2566909a1f654b17ef77e7b53ba1ec65/38272.ipynb). Thanks!

**Comment by amahendrakar** [comment]
@HarshitSheoran,
Any updates regarding this issue? Thanks!

**Comment by HarshitSheoran** [comment]
I guess the problem was there for some other reason, thank you!
