### ISSUE TITLE
TF2.2.0rc2: exception if shape of input to tf.linag.set_diag not fully specified 

### ISSUE THREAD

**Issue by pbecker93** [tensorflow/tensorflow#38280]
Hello, 

it's now possible to use tf.linalg.set_diag to set not only the diagonal of a matrix, but also bands (i.e a diagonal + sub- and superdiagonals) using the parameter "k". 

I would like to use this within a keras layer, yet when the model containing that layer is built, an exception (see below) is raised as long as the shape of the input parameter of tf.linalg.set_diag is not fully specified (i.e. the batch size should be dynamic, depending on the input at "runtime"). If I prespecify the axis size, everything seems to work fine
 
**Standalone code to reproduce the issue** 
```python 
import tensorflow as tf
import tensorflow.keras as k

def construct_band_mat(band):
    # Dynamic batch size does not work
    batch_size = tf.shape(band)[0]

    # hard coded batch size works
    #batch_size = 3

    base = tf.zeros([batch_size, 5, 5])
    return tf.linalg.set_diag(base, band, k=(-1, 1))

input = k.Input(shape=[3, 5])
output = k.layers.Lambda(construct_band_mat)(input)

model = k.models.Model(inputs=[input], outputs=[output])

band_in = tf.ones([3, 3, 5], dtype=tf.float32)
print(model(band_in))
```

**System information** 
- Have I written custom code:  yes 
- OS Platform and Distribution: Ubuntu 18.04 
- TensorFlow version: 2.2.0rc2
- TensorFlow installed from: pip
- Python version:  3.6.9 
- CUDA/cuDNN version: None, CPU only 

**Describe the current behavior**

If the shape of the "input" is fully specified when the model is build, the function acts as expected.
If the size of one axis (e.g. the batch axis) of "input" is unspecified during build, an exception is raised :

Traceback (most recent call last):
  File "/home/philipp/projects/rkn_venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1654, in _create_c_op
    c_op = pywrap_tf_session.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes must be equal rank, but are 3 and 4 for '{{node lambda/set_diag}} = MatrixSetDiagV3[T=DT_FLOAT, align="RIGHT_LEFT"](lambda/zeros, input_1, lambda/set_diag/k)' with input shapes: [?,5,5], [?,3,5], [2].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/philipp/projects/RKN_internal/banded_test.py", line 16, in <module>
    output = k.layers.Lambda(construct_band_mat)(input)
  File "/home/philipp/projects/rkn_venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 922, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/philipp/projects/rkn_venv/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py", line 888, in call
    result = self.function(inputs, **kwargs)
  File "/home/philipp/projects/RKN_internal/banded_test.py", line 13, in construct_band_mat
    return tf.linalg.set_diag(base, band, k=(-1, 1))
  File "/home/philipp/projects/rkn_venv/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2654, in matrix_set_diag
    input=input, diagonal=diagonal, k=k, align=align, name=name)
  File "/home/philipp/projects/rkn_venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5864, in matrix_set_diag_v3
    name=name)
  File "/home/philipp/projects/rkn_venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/home/philipp/projects/rkn_venv/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 595, in _create_op_internal
    compute_device)
  File "/home/philipp/projects/rkn_venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3327, in _create_op_internal
    op_def=op_def)
  File "/home/philipp/projects/rkn_venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1817, in __init__
    control_input_ops, op_def)
  File "/home/philipp/projects/rkn_venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1657, in _create_c_op
    raise ValueError(str(e))
ValueError: Shapes must be equal rank, but are 3 and 4 for '{{node lambda/set_diag}} = MatrixSetDiagV3[T=DT_FLOAT, align="RIGHT_LEFT"](lambda/zeros, input_1, lambda/set_diag/k)' with input shapes: [?,5,5], [?,3,5], [2].

Process finished with exit code 1

Note that it says "Shapes must be equal rank, but are 3 and 4 " but then " input shapes: [?,5,5], [?,3,5], [2]" i.e. two shapes of rank 3.

Also note that the first dimension of the diagonal argument is also unspecified, which seems to work fine.

**Describe the expected behavior**
tf.linalg.set_diag should be able to handle inputs whose size is not fully specified while the graph is build up. 
(If there is some fundamental reason why this is not possible, which I am currently not seeing, the documentation should be adapted and the exception should be more expressive. ) 

Best wishes,
Philipp

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.2.0-rc2, 2.2.0-dev20200406 and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/0b93db5b2ca687a79f4e32c3c50493b2/untitled17.ipynb). Thanks!

**Comment by Saduf2019** [comment]
I have tried on colab with TF version 2.5 and was able to reproduce the issue.Please, find the [gist here](https://colab.research.google.com/gist/Saduf2019/76ca3e3ada81b1fcb79675a745d23f37/untitled589.ipynb). Thanks!

**Comment by tilakrayal** [comment]
Was able to reproduce the issue in tf v2.7.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/97873d4db143ac0cc3fe2d58a0f7d787/untitled159.ipynb).

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
