### ISSUE TITLE
Estimator raises spurious error with dynamic_rnn model

### ISSUE THREAD

**Issue by kuza55** [tensorflow/tensorflow#3828]
I'm trying to train an RNN and I'm playing with the dynamic_rnn model inside an skflow Estimator and trying to traing it sequences of increasing length.

So I end up passing in data of the form [batch_size, seq_length, seq_entry_size]

Where seq_length varies, but is constant each time I call partial_fit.

I am constructing my dynamic_rnn model like so:

```
def rnn_model2(x, y):
  cell = tf.nn.rnn_cell.GRUCell(250)

  _, encoding = tf.nn.dynamic_rnn(cell, x, dtype=tf.float32)

  target = tf.one_hot(y, 2, 1, 0)

  prediction, loss = learn.models.logistic_regression(encoding, target)

  # Create a training op.
  train_op = tf.contrib.layers.optimize_loss(
      loss, tf.contrib.framework.get_global_step(),
      optimizer='Adam', learning_rate=0.01)

  return {'class': tf.argmax(prediction, 1), 'prob': prediction}, loss, train_op

classifier = learn.Estimator(model_fn=rnn_model2)
```

### Environment info
Operating System:
Ubuntu on Windows 10

If installed from binary pip package, provide:
0.10.rc0

### Steps to reproduce
1. Create an Estimator with a model_fn that uses a dynamic_rnn
2. Pass variable length data through partial_fit
3. Error

### What have you tried?
1. I commented out the checks in estimator.py and things work

### Logs or other output that would be helpful
WARNING:tensorflow:Given features: Tensor("input:0", shape=(?, 2, 3), dtype=float32), required signatures: TensorSignature(dtype=tf.float32, shape=TensorShape([Dimension(None), Dimension(1), Dimension(3)]), is_sparse=False).
Traceback (most recent call last):
  File "mouse.py", line 136, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "mouse.py", line 126, in main
    classifier.partial_fit(x_train, y_train, steps=3)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 262, in partial_fit
    batch_size=batch_size, monitors=monitors)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 219, in fit
    max_steps=max_steps)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 478, in _train_model
    self._check_inputs(features, targets)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 427, in _check_inputs
    (str(features), str(self._features_info)))
ValueError: Features are incompatible with given information. Given features: Tensor("input:0", shape=(?, 2, 3), dtype=float32), required signatures: TensorSignature(dtype=tf.float32, shape=TensorShape([Dimension(None), Dimension(1), Dimension(3)]), is_sparse=False).

**Comment by kuza55** [comment]
Hmmm, I might just be doing this wrong, commenting the checks out worked with a small test batch, but then failed with a slightly larger test batch...

**Comment by lzhuo** [comment]
Hi,
Do you find the solution for this problem in the end? I had the same problem as you posted
