### ISSUE TITLE
Unsupported Full-Integer TensorFlow Lite models in TF 2

### ISSUE THREAD

**Issue by MeghnaNatraj** [tensorflow/tensorflow#38285]
**Describe the issue**
**In TF2, the full-integer quantized models produced by the TFLite Converter can only have *float* input and output type. This is a blocker for users who require *int8* or *uint8* input and/or output type.**

**UPDATE**: We now support this workflow.

**End-to-End Tutorial**: https://colab.sandbox.google.com/github/google-coral/tutorials/blob/master/retrain_classification_ptq_tf2.ipynb

**Only TFLite Conversion: Convert TF Models to TFLite Full-Integer models**
You can refer to the code [here](https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only), also given below:

```
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
def representative_dataset_gen():
  for _ in range(num_calibration_steps):
    # Get sample input data as a numpy array in a method of your choosing.
    yield [input]
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8
tflite_model = converter.convert()
```

**Only TFLite Inference: Run inference on the TFLite model**
**Note** that the one caveat with integer-only models is this -- you need to manually map (aka quantize) the float inputs to integer inputs during inference. To understand how this can be done -- refer to the equation provided in [TensorFlow Lite 8-bit quantization specification](https://www.tensorflow.org/lite/performance/quantization_spec) document and it's equivalent code in python below:
```
import numpy as np
import tensorflow as tf

# Input to the TF model are float values in the range [0, 10] and of size (1, 100)
np.random.seed(0)
tf_input = np.random.uniform(low=0, high=10, size=(1, 100)).astype(np.float32)

# Output of the TF model.
tf_output = keras_model.predict(input)

# Output of the TFLite model.
interpreter = tf.lite.Interpreter(model_content=tflite_model) 
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()[0]
# Manually quantize the input from float to integer
scale, zero_point = input_details['quantization']
tflite_integer_input = tf_input / scale + zero_point
tflite_integer_input = tflite_integer_input.astype(input_details['dtype'])
interpreter.set_tensor(input_details['index'], tflite_integer_input)
interpreter.invoke()
output_details = interpreter.get_output_details()[0]
tflite_integer_output = interpreter.get_tensor(output_details['index'])
# Manually dequantize the output from integer to float
scale, zero_point = output_details['quantization']
tflite_output = tflite_integer_output.astype(np.float32)
tflite_output = (tflite_output - zero_point) * scale
 
# Verify that the TFLite model's output is approximately (expect some loss in 
# accuracy due to quantization) the same as the TF model's output
assert np.allclose(tflite_output, tf_output, atol=1e-04) == True
```

**Comment by rayeh5** [comment]
I am interested in this issue. When fix is available, please let me know. 
(I suppose I will get the notify when write message here, right?)

Ruey-An

**Comment by MeghnaNatraj** [comment]
@rayeh5 Yes. Whenever we post updates, you will receive emails.

**Comment by alanchiao** [comment]
@MeghnaNatraj: in the meanwhile, could you update https://www.tensorflow.org/lite/performance/post_training_quantization#full_integer_quantization_of_weights_and_activations and other documentation to reflect that the full-integer path (including inputs and outputs) is only available in TF 1.X and not TF 2.X?

**Comment by aa12356jm** [comment]
expecting

**Comment by mahdichtourou24051994** [comment]
Hello , 
Any updates about this issue ? Will v2 converter support input output Flags?

**Comment by MeghnaNatraj** [comment]
Yes, it is currently a work in progress. We will update this github issue
once it's completed.

**Comment by MarkoSagadin** [comment]
Just checking in, im also waiting for v2.

**Comment by AlmogDavid** [comment]
Also waiting for this issue to be resolved, thanks.

**Comment by Tony-Tseng** [comment]
waiting for this issue to be resolved, thanks.

**Comment by dreamPoet** [comment]
waiting too

**Comment by fnoorbin** [comment]
I am facing this issue in TF 1.15 and TF 2.

**Comment by dreamPoet** [comment]
By the way, can we use converter to create an uint8 inference tflite model rather than an int8 inference model?

**Comment by MeghnaNatraj** [comment]
**Note:** *The following discussion is not related to the current issue of supporting full integer tensorflow lite models, including input and output, in TF 2.0*

@dreamPoet No, this is not possible in TensorFlow 2. We cannot create a uint8 inference tflite model and only support int8 inference model. We've moved away from the uint8 quantization is because with int8, we're able to use asymmetrical quantization ranges without paying the same penalty. Refer to [https://www.tensorflow.org/lite/performance/quantization_spec](https://www.tensorflow.org/lite/performance/quantization_spec) for more information

For more details:
Youtube: https://www.youtube.com/watch?v=-jBmqY_aFwE
Slides used in the Youtube Video: https://docs.google.com/presentation/d/1zGm5bqGrkAepwJZ5PABiYjrIKq1pDnzafa8ZYeaFhXY/edit?usp=sharing

**Comment by dreamPoet** [comment]
@MeghnaNatraj  How about in tf1.x? I can only use toco and lite.converter without representative_dataset attributes to produce uint8 inference tflite model, while for int8 inference model, I can set representative_dataset to help quantize, is that right?

**Comment by MeghnaNatraj** [comment]
@dreamPoet Could you create a separate github issue describing your problem and assign it to me? I'd be glad to provide more information on the new issue.

**Comment by stefano555** [comment]
@MeghnaNatraj Hi, I am working on a benchmark for the Edge TPU and this is blocking me for using it, which is really frustrating. Are you aware of any workaround? Could you provide an estimation of when the converter would be ready? Since this issue wasn't mentioned anywhere I embarked on this project but now I've reached a point where there is nothing else to do but waiting.

**Comment by hahadashi** [comment]
@MeghnaNatraj @stefano555  Excuse me, do your test the speed of the quantified model? I found there was only a slight increase in speed.

**Comment by stefano555** [comment]
> @MeghnaNatraj @stefano555 Excuse me, do your test the speed of the quantified model? I found there was only a slight increase in speed.

I would test it, if tf lite allowed me to do that :-) since I cannot get the fully quantized model, I cannot do the benchmark

**Comment by MeghnaNatraj** [comment]
**Update**
We now support TensorFlow Lite Full-Integer models in TF 2.0, i.e, with integer (`tf.int8` and `tf.uint8` types) input and output.
*Exception: Support for [quantize-aware trained models](https://www.tensorflow.org/lite/performance/model_optimization) is still in progress* 

**TFLite Conversion: Convert TF Models to TFLite Full-Integer models**
You can refer to the code [here](https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only), also given below:


```
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
def representative_dataset_gen():
  for _ in range(num_calibration_steps):
    # Get sample input data as a numpy array in a method of your choosing.
    yield [input]
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8
tflite_model = converter.convert()
```

**TFLite Inference: Run inference on the TFLite model**
**Note** that the one caveat with integer-only models is this -- you need to manually map (aka quantize) the float inputs to integer inputs during inference. To understand how this can be done -- refer to the equation provided in [TensorFlow Lite 8-bit quantization specification](https://www.tensorflow.org/lite/performance/quantization_spec) document and it's equivalent code in python below:
```
import numpy as np
import tensorflow as tf

# Input to the TF model are float values in the range [0, 10] and of size (1, 100)
np.random.seed(0)
tf_input = np.random.uniform(low=0, high=10, size=(1, 100)).astype(np.float32)

# Output of the TF model.
tf_output = keras_model.predict(input)

# Output of the TFLite model.
interpreter = tf.lite.Interpreter(model_content=tflite_model) 
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()[0]
# Manually quantize the input from float to integer
scale, zero_point = input_details['quantization']
tflite_integer_input = tf_input / scale + zero_point
tflite_integer_input = tflite_integer_input.astype(input_details['dtype'])
interpreter.set_tensor(input_details['index'], tflite_integer_input)
interpreter.invoke()
output_details = interpreter.get_output_details()[0]
tflite_integer_output = interpreter.get_tensor(output_details['index'])
# Manually dequantize the output from integer to float
scale, zero_point = output_details['quantization']
tflite_output = tflite_integer_output.astype(np.float32)
tflite_output = (tflite_output - zero_point) * scale
 
# Verify that the TFLite model's output is approximately (expect some loss in 
# accuracy due to quantization) the same as the TF model's output
self.assertTrue(np.allclose(tflite_output, tf_output, atol=1e-04))
```

**Comment by scottamain** [comment]
FYI, you can try this TF2 API for full-integer post-training quantization here:
https://colab.sandbox.google.com/github/google-coral/tutorials/blob/master/retrain_classification_ptq_tf2.ipynb

**Comment by stefano555** [comment]
@scottamain @MeghnaNatraj Hi,
I've trained a resnet50v2 model. TensorFlow nightly 2.3.0-dev20200608. The model works fine and I tried some optimization such as "simple" tf lite, tf lite dynamic range, tf lite 16float, and they all work fine. 
I have updated today tf to use full-integer post-training quantization with uint8. I converted my model from SavedModel format with:

num_calibration_steps=100
def representative_dataset_gen():
    for i in range(num_calibration_steps):
        yield [x_train[i:i+1].astype(np.float32)]
converter = tf.lite.TFLiteConverter.from_saved_model('/path/to/my/saved_models')

# This enables quantization
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.int8]
# This ensures that if any ops can't be quantized, the converter throws an error
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
# These set the input and output tensors to uint8 (added in r2.3)
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
# And this sets the representative dataset so we can quantize the activations
converter.representative_dataset = representative_data_gen
tflite_model = converter.convert()

with open('mobilenet_v2_1.0_224_quant.tflite', 'wb') as f:
  f.write(tflite_model)

I then compiled the model for edge tpu. It works, in the sense that edge tpu allows me to run it without errors but results are gibberish. It predicts always the same value. I tried then on cpu with tf lite interpreter. Input/output tensor are correctly uint8, but again it predicts again the same value. On cpu wiht tf lite issue persists moving to int8.

Is anyone else experiencing the same issue?

**Comment by scottamain** [comment]
Hey @stefano555 
You said your input tensors are uint8, and that was my first concern. So I don't know what else it might be. But to be sure, can you verify that your results are accurate when you use float input/output (remove the inference_input_type/inference_output_type lines)?

**Comment by stefano555** [comment]
Hi @scottamain ,

please find here a link to a google folder containing the tf trained model (validation accuracy 64.15% on 2000 test images), the dataset, the google colab file to convert from tf to tf_lite, the converted tf lite model, and the google colab file to test the tf lite model on cpu.
I was able to replicate the issue. On a subset of 100 test images (using all the images would have taken hours since tf lite on cpu is extremely slow) I got 40% but only because it kept predicting the same value and that subset there were 40 pictures corresponding to that value but it is only gibberish.

https://drive.google.com/drive/folders/11XruNeJzdIm9DTn7FnuIWYaSalqg2F0B?usp=sharing

Many thanks for your help!

**Comment by stefano555** [comment]
Hi @MeghnaNatraj and @scottamain I have tested today DenseNet-169 and I got the identical issue with Full-Integer TensorFlow Lite.

**Comment by anferico** [comment]
> **Update**: We now support TensorFlow Lite Full-Integer models in TF 2.0, i.e, with integer (`tf.int8` and `tf.uint8` types) input and output.
> _Exception: Support for [quantize-aware trained models](https://www.tensorflow.org/lite/performance/model_optimization) is still in progress_
> 
> **End-to-End Tutorial**: https://colab.sandbox.google.com/github/google-coral/tutorials/blob/master/retrain_classification_ptq_tf2.ipynb
> 
> **Only TFLite Conversion: Convert TF Models to TFLite Full-Integer models**
> You can refer to the code [here](https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only), also given below:
> 
> ```
> import tensorflow as tf
> converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
> converter.optimizations = [tf.lite.Optimize.DEFAULT]
> def representative_dataset_gen():
>   for _ in range(num_calibration_steps):
>     # Get sample input data as a numpy array in a method of your choosing.
>     yield [input]
> converter.representative_dataset = representative_dataset_gen
> converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
> converter.inference_input_type = tf.int8  # or tf.uint8
> converter.inference_output_type = tf.int8  # or tf.uint8
> tflite_model = converter.convert()
> ```
> 
> **Only TFLite Inference: Run inference on the TFLite model**
> **Note** that the one caveat with integer-only models is this -- you need to manually map (aka quantize) the float inputs to integer inputs during inference. To understand how this can be done -- refer to the equation provided in [TensorFlow Lite 8-bit quantization specification](https://www.tensorflow.org/lite/performance/quantization_spec) document and it's equivalent code in python below:
> 
> ```
> import numpy as np
> import tensorflow as tf
> 
> # Input to the TF model are float values in the range [0, 10] and of size (1, 100)
> np.random.seed(0)
> tf_input = np.random.uniform(low=0, high=10, size=(1, 100)).astype(np.float32)
> 
> # Output of the TF model.
> tf_output = keras_model.predict(input)
> 
> # Output of the TFLite model.
> interpreter = tf.lite.Interpreter(model_content=tflite_model) 
> interpreter.allocate_tensors()
> input_details = interpreter.get_input_details()[0]
> # Manually quantize the input from float to integer
> scale, zero_point = input_details['quantization']
> tflite_integer_input = tf_input / scale + zero_point
> tflite_integer_input = tflite_integer_input.astype(input_details['dtype'])
> interpreter.set_tensor(input_details['index'], tflite_integer_input)
> interpreter.invoke()
> output_details = interpreter.get_output_details()[0]
> tflite_integer_output = interpreter.get_tensor(output_details['index'])
> # Manually dequantize the output from integer to float
> scale, zero_point = output_details['quantization']
> tflite_output = tflite_integer_output.astype(np.float32)
> tflite_output = (tflite_output - zero_point) * scale
>  
> # Verify that the TFLite model's output is approximately (expect some loss in 
> # accuracy due to quantization) the same as the TF model's output
> assert np.allclose(tflite_output, tf_output, atol=1e-04) == True
> ```

Is it possible to manually quantize/dequantize the inputs/outputs using the TFLite for Microcontrollers C++ library? Here you're just showing how to do that using the Python library..

**Comment by aa12356jm** [comment]
Quantization aware training can not convert to int8 or unint8 ?
this is my code ,thanks.
https://colab.research.google.com/drive/1qPD3Zd5qU5FpMxj_aCwIpjn7y_eR_Wxt?usp=sharing

**Comment by MeghnaNatraj** [comment]
@anferico Unfortunately, it looks like we don't have an example for TFLite Interpreter in C++ which uses the quantize/dequantize scale and zero-point to preprocess the image and process the result. We will be updating the TFLite micro examples, but until then, you can try the following suggestion:

The closest example is [micro/examples/person_detection_experimental](https://source.corp.google.com/piper///depot/google3/third_party/tensorflow/lite/micro/examples/person_detection_experimental/person_detection_test.cc?q=128&ss=piper%2FGoogle%2FPiper:google3%2Fthird_party%2Ftensorflow%2Flite%2Fmicro%2Fexamples%2Fperson_detection_experimental%2F) -- specifically refer to [this](https://source.corp.google.com/piper///depot/google3/third_party/tensorflow/lite/micro/examples/person_detection_experimental/person_detection_test.cc;l=87?q=128&ss=piper%2FGoogle%2FPiper:google3%2Fthird_party%2Ftensorflow%2Flite%2Fmicro%2Fexamples%2Fperson_detection_experimental%2F) -- a uint8 image input it converter to int8 by subtracting 128 and feeding it into the model. For this example, we noticed that the zero point is -128 and the scale is 1.0 so we directly just subtract 128 to keep the code simple. 

However you should be able to access `input->params->zero_point` and `input->params->scale` and write a C++ equivalent of the python TFLite Interpreter code that we have shared.

Hope this helps!

@aa12356jm  correct, we are still working on adding support for this feature.

**Comment by sayakpaul** [comment]
Following. Two of my blog posts would need to be changed when the int support for QAT models goes live.

**Comment by kalaluthien** [comment]
@MeghnaNatraj 
Can you check and mention this workaround (https://github.com/tensorflow/model-optimization/issues/431) for quantize input/output tensor when QAT is used?

**Comment by stefano555** [comment]
Hi @scottamain and @MeghnaNatraj I just wanted to know if there are any updates and if could reproduce my same issue.

**Comment by hahadashi** [comment]
@MeghnaNatraj @alanchiao   i train a quant model with dynamic fuction, input and output are float. i test two model (float 3.6M and int8 900k) in the android phone. there are no speed accelarate.

**Comment by sayakpaul** [comment]
@hahadashi could you confirm if you are using delegate when using the models from your Android phone?

**Comment by hahadashi** [comment]
> @hahadashi could you confirm if you are using delegate when using the models from your Android phone?
thxs your reply.
i just follow the tensorflow/lite/g3doc/guide/inference.md 
(```c++
// Load the model
std::unique_ptr<tflite::FlatBufferModel> model =
    tflite::FlatBufferModel::BuildFromFile(filename);

// Build the interpreter
tflite::ops::builtin::BuiltinOpResolver resolver;
std::unique_ptr<tflite::Interpreter> interpreter;
tflite::InterpreterBuilder(*model, resolver)(&interpreter);

// Resize input tensors, if desired.
interpreter->AllocateTensors();

float* input = interpreter->typed_input_tensor<float>(0);
// Fill `input`.

interpreter->Invoke();

float* output = interpreter->typed_output_tensor<float>(0);
```)

develop a inference code to run the tflite on the phone.  i need do more thing?

**Comment by sayakpaul** [comment]
You might want to follow this tutorial once: https://www.tensorflow.org/lite/performance/gpu.

**Comment by hahadashi** [comment]
> You might want to follow this tutorial once: https://www.tensorflow.org/lite/performance/gpu. Here's the demo code snippet:
> 
> ![image](https://user-images.githubusercontent.com/22957388/86256183-a17d6800-bbd5-11ea-9af4-924c5119796e.png)

thxs, i have a question. why we need use GPU delegate to accelerate speed by gpu. the arm cpu not support quant inference?

**Comment by akosb** [comment]
> https://www.youtube.com/watch?v=-jBmqY_aFwE

@MeghnaNatraj thanks for the great link to Pete Wardens screencast!

**Comment by MeghnaNatraj** [comment]
@stefano555 I am working on debugging your issue right now. Looks like https://drive.google.com/corp/drive/folders/11XruNeJzdIm9DTn7FnuIWYaSalqg2F0B has a ton of jupyter notebooks, and i'm not sure how to debug this. Please create a new github issue for "TFLite Converter", add me as the assignee and post detailed instructions on how I can reproduce your issue.

**Comment by rsunofbdti** [comment]
It looks like the issue has been solved in TF 2.4?

**Comment by robbysun** [comment]
It looks like the issue has been solved in TF 2.4? Could we get an official confirmation?

**Comment by sayakpaul** [comment]
@MeghnaNatraj is this solved in TF 2.4 (nightly)?

**Comment by MeghnaNatraj** [comment]
Hello, the issue is resolved now with TF 2.4 (nightly). Let us know if you face any issue.

**Comment by stefano555** [comment]
Dear @MeghnaNatraj, sorry for answering you only now. The issue has not been resolved. I will create a new GitHub issue and add you as an assignee.

**Comment by sayakpaul** [comment]
@MeghnaNatraj ran into: `RuntimeError: Quantization not yet supported for op: 'DEQUANTIZE'.` TensorFlow Version: `2.4.0-dev20200728`. Let me know if you'd want me to create a separate issue. 

Here's the [Colab Gist](https://colab.research.google.com/gist/sayakpaul/8c8a1d7c94beca26d93b67d92a90d3f0/qat-bad-accuracy.ipynb).

**Comment by stefano555** [comment]
@MeghnaNatraj I wasn't able to assign you to the new issue, you can find it here https://github.com/tensorflow/tensorflow/issues/41840#issue-667409532

**Comment by rayeh5** [comment]
sorry, I don't know if the question is appropriate to ask here:
it seems that the int8 quantization is a symmetric quantization one, will TF-Lite (or Micro vesion) has plan to support "symmetric quantization"?

thanks for all of your time

**Comment by MeghnaNatraj** [comment]
@sayakpaul Could you create a separate issue and tag me on it? I am looking into it. 
@stefano555 I am looking into #41840 right now.

@rayeh5  could you explain your question in detail? Currently we support int8 quantization by default.

**Comment by sayakpaul** [comment]
@MeghnaNatraj I don't think community members can assign someone to an issue (correct me if I am wrong). I referred to the following statement of yours and hence I decided to inform you about the issue here. 

> (This issue will remain open until we also fix all documentation, and resolve any issues that may arise in the next few days)

Please let me know if you'd still like me to open up a new issue.

**Comment by MeghnaNatraj** [comment]
@sayakpaul Yes, community members cannot assign an issue to a specific person. You can create a new issue, post the details about your issue (as in this [comment](https://github.com/tensorflow/tensorflow/issues/38285#issuecomment-665444152) and post a link to the issue here. I will continue the discussion on that thread.

**Comment by MeghnaNatraj** [comment]
@sayakpaul  I have created a separate issue here: https://github.com/tensorflow/tensorflow/issues/42082

**Comment by rayeh5** [comment]
> @sayakpaul Could you create a separate issue and tag me on it? I am looking into it.
> @stefano555 I am looking into #41840 right now.
> 
> @rayeh5 could you explain your question in detail? Currently we support int8 quantization by default.

As my understanding of the "TensorFlow Lite 8-bit quantization specification", Weights are symmetric, but the Activations are asymmetric. Is it possible to support both as symmetric quantization? 

Thanks for your time.

ruey-an

**Comment by MeghnaNatraj** [comment]
> > @sayakpaul Could you create a separate issue and tag me on it? I am looking into it.
> > @stefano555 I am looking into #41840 right now.
> > @rayeh5 could you explain your question in detail? Currently we support int8 quantization by default.
> 
> As my understanding of the "TensorFlow Lite 8-bit quantization specification", Weights are symmetric, but the Activations are asymmetric. Is it possible to support both as symmetric quantization?
> 
> Thanks for your time.
> 
> ruey-an

@suharshs could you respond to this question?

**Comment by aa12356jm** [comment]
@MeghnaNatraj  hi, i use post quantization as follows:
```
.........
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
```
 only input and output  of the quantization model  have the  datatype uint8,  the convolution of the middle layer is still int8.
how do I get  the model that  is  all uint8?  thanks

**Comment by MeghnaNatraj** [comment]
@aa12356jm This is currently unsupported, you can refer to this [comment](https://github.com/tensorflow/tensorflow/issues/38285#issuecomment-635533037) for more information.

**Comment by MeghnaNatraj** [comment]
Closing this issue as it has been resolved. The documentation for TensorFlow Lite has been updated. If you face an issue due to this change, either re-open this issue or create a new one and mention this issue (by adding #38285 in a comment)

**Comment by aa12356jm** [comment]
> Quantization aware training can not convert to int8 or unint8 ?
> this is my code ,thanks.
> https://colab.research.google.com/drive/1qPD3Zd5qU5FpMxj_aCwIpjn7y_eR_Wxt?usp=sharing

@MeghnaNatraj  now QAT can convert to int8 or unint8 ?  thanks

**Comment by MeghnaNatraj** [comment]
@aa12356jm We only support int8 quantization but the model input/output can be int8 or uint8. Use the latest TF version 
`pip install tensorflow` should install the latest stable version

**Comment by sayakpaul** [comment]
@MeghnaNatraj say `model` (it's a `tf.keras.Model` instance) is trained using QAT and now I would like to integer-quantize it, will the following be the right way to achieve that? I truly apologize if this is redundant: 

```python
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
tflite_model_quant = converter.convert()
```

No representative dataset is required since the model is already calibrated to adjust to the activation changes.

**Comment by MeghnaNatraj** [comment]
@sayakpaul yes this is perfectly right.

**Comment by sayakpaul** [comment]
@MeghnaNatraj I see a problem with the code snippet provided above. I get the following error:

```
ValueError: representative_dataset is required when specifying TFLITE_BUILTINS_INT8 or INT8 supported types.
```

Here's my [Colab Notebook](https://colab.research.google.com/gist/sayakpaul/d291add98e9d46eff820b405bde8e448/scratchpad.ipynb).

**Comment by sayakpaul** [comment]
@MeghnaNatraj with the above-mentioned code snippet I get the following error, though - 

```
ValueError: representative_dataset is required when specifying TFLITE_BUILTINS_INT8 or INT8 supported types.
```

Here's the [Colab Notebook](https://colab.research.google.com/gist/sayakpaul/1eafb47439c8045466c40de371c6635c/scratchpad.ipynb).

**Comment by MeghnaNatraj** [comment]
Remove the line 
``` converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]```
as for QAT you are assuming that the model can be fully quantized.

**Comment by sandeep22-v** [comment]
> **Update**: We now support TensorFlow Lite Full-Integer models in TF 2.0, i.e, with integer (`tf.int8` and `tf.uint8` types) input and output.
> _Exception: Support for [quantize-aware trained models](https://www.tensorflow.org/lite/performance/model_optimization) is still in progress_
> 
> **End-to-End Tutorial**: https://colab.sandbox.google.com/github/google-coral/tutorials/blob/master/retrain_classification_ptq_tf2.ipynb
> 
> **Only TFLite Conversion: Convert TF Models to TFLite Full-Integer models**
> You can refer to the code [here](https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only), also given below:
> 
> ```
> import tensorflow as tf
> converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
> converter.optimizations = [tf.lite.Optimize.DEFAULT]
> def representative_dataset_gen():
>   for _ in range(num_calibration_steps):
>     # Get sample input data as a numpy array in a method of your choosing.
>     yield [input]
> converter.representative_dataset = representative_dataset_gen
> converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
> converter.inference_input_type = tf.int8  # or tf.uint8
> converter.inference_output_type = tf.int8  # or tf.uint8
> tflite_model = converter.convert()
> ```
> 
> **Only TFLite Inference: Run inference on the TFLite model**
> **Note** that the one caveat with integer-only models is this -- you need to manually map (aka quantize) the float inputs to integer inputs during inference. To understand how this can be done -- refer to the equation provided in [TensorFlow Lite 8-bit quantization specification](https://www.tensorflow.org/lite/performance/quantization_spec) document and it's equivalent code in python below:
> 
> ```
> import numpy as np
> import tensorflow as tf
> 
> # Input to the TF model are float values in the range [0, 10] and of size (1, 100)
> np.random.seed(0)
> tf_input = np.random.uniform(low=0, high=10, size=(1, 100)).astype(np.float32)
> 
> # Output of the TF model.
> tf_output = keras_model.predict(input)
> 
> # Output of the TFLite model.
> interpreter = tf.lite.Interpreter(model_content=tflite_model) 
> interpreter.allocate_tensors()
> input_details = interpreter.get_input_details()[0]
> # Manually quantize the input from float to integer
> scale, zero_point = input_details['quantization']
> tflite_integer_input = tf_input / scale + zero_point
> tflite_integer_input = tflite_integer_input.astype(input_details['dtype'])
> interpreter.set_tensor(input_details['index'], tflite_integer_input)
> interpreter.invoke()
> output_details = interpreter.get_output_details()[0]
> tflite_integer_output = interpreter.get_tensor(output_details['index'])
> # Manually dequantize the output from integer to float
> scale, zero_point = output_details['quantization']
> tflite_output = tflite_integer_output.astype(np.float32)
> tflite_output = (tflite_output - zero_point) * scale
>  
> # Verify that the TFLite model's output is approximately (expect some loss in 
> # accuracy due to quantization) the same as the TF model's output
> assert np.allclose(tflite_output, tf_output, atol=1e-04) == True
> ```

Got the error
tensorflow.lite.python.convert.ConverterError: <unknown>:0: error: loc(callsite(callsite("Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/SortByField_1/Size@__inference___call___21591" at "StatefulPartitionedCall@__inference_signature_wrapper_23250") at "StatefulPartitionedCall")): 'tf.Size' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.Size {device = ""}

removed this error using 
**converter.target_spec.supported_ops=[tf.lite.OpsSet.SELECT_TF_OPS]**

But got another error with this : 
Traceback (most recent call last):
  File "abc.py", line 45, in <module>
    tflite_model = converter.convert()
  File "lite.py", line 742, in convert
    result = self._calibrate_quantize_model(result, **flags)
  File "lite.py", line 459, in _calibrate_quantize_model
    return calibrate_quantize.calibrate_and_quantize(
  File "calibrator.py", line 97, in calibrate_and_quantize
    self._calibrator.Prepare([list(s.shape) for s in sample])
  File "calibrator.py", line 97, in <listcomp>
    self._calibrator.Prepare([list(s.shape) for s in sample])
AttributeError: 'list' object has no attribute 'shape'

**Comment by mipsan** [comment]
@MeghnaNatraj 
This issue was resolved completely?
Even with TF 2.4.1, I still have this error:
`RuntimeError: Quantization not yet supported for op: 'CUSTOM'.`

Without QAT,
```
def representative_dataset_gen():
    for f_name in os.listdir(image_path):
       file_path = os.path.normpath(os.path.join(image_path, f_name))
        img = cv2.imread(file_path)
        img = cv2.resize(img, (320,320))
        img = img / 255.0
        img = np.reshape(img, (1, 320, 320, 3))
        image = img.astype(np.float32)
        yield [image]

converter = tf.lite.TFLiteConverter.from_saved_model(args.model)

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen

converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.target_spec.supported_types = [tf.int8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

#converter.allow_custom_ops = True
#converter.experimental_new_converter = False

tflite_model = converter.convert()
```
I cannot find out what's wrong at all.

**Comment by lheim** [comment]
> @MeghnaNatraj
> This issue was resolved completely?
> Even with **TF 2.4.1**, I still have this error:
> `RuntimeError: Quantization not yet supported for op: 'CUSTOM'.`
> 
> Without QAT,
> 
> ```
> def representative_dataset_gen():
>     for f_name in os.listdir(image_path):
>        file_path = os.path.normpath(os.path.join(image_path, f_name))
>         img = cv2.imread(file_path)
>         img = cv2.resize(img, (320,320))
>         img = img / 255.0
>         img = np.reshape(img, (1, 320, 320, 3))
>         image = img.astype(np.float32)
>         yield [image]
> 
> converter = tf.lite.TFLiteConverter.from_saved_model(args.model)
> 
> converter.optimizations = [tf.lite.Optimize.DEFAULT]
> converter.representative_dataset = representative_dataset_gen
> 
> converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
> converter.target_spec.supported_types = [tf.int8]
> converter.inference_input_type = tf.int8
> converter.inference_output_type = tf.int8
> 
> #converter.allow_custom_ops = True
> #converter.experimental_new_converter = False
> 
> tflite_model = converter.convert()
> ```
> 
> I cannot find out what's wrong at all.

As it says in the error, one of your operations called `'CUSTOM'` is not yet supported. Therefore, it's something with your original neural network (probably Keras).
You might want to check which operands are supported [here](https://www.tensorflow.org/lite/guide/ops_compatibility).

**Comment by mipsan** [comment]
@lheim Thanks,

I got a pb file from saved model, as this [link](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html).

The error message says 'CUSTOM' is not supported, but I cannot find where it is.

**Comment by ivlydp** [comment]
> Thank you and that worked. Here's my Colab Gist for anyone else that might run into a similar problem: https://colab.research.google.com/gist/sayakpaul/d209ac353d3bcea06287be5e91628f18/scratchpad.ipynb.
Thanks for your sharing. I meet the same problem and try your script, it doesn't work now. Is it still work for you ?
