### ISSUE TITLE
Tensorflow keras.callbacks.ModelCheckPoint with wrong path doesn't save anything instead of raising error

### ISSUE THREAD

**Issue by MakeCent** [tensorflow/tensorflow#38294]
**System information** 
- Have I written custom code: NO
- OS Platform and Distribution: Ubuntu 18.04
- Mobile device: N/A
- TensorFlow installed from: `pip install --upgrade tf-nightly`
- TensorFlow version: 2.2.0-dev20200403
- Python version: 3.7.7
- CUDA version: cuda 10.1
- GPU model and memory: NVIDIA 2080 and TITAN X

**Describe the current behavior**
```
model_checkpoint = tf.keras.callbacks.ModelCheckpoint('Output/task1/Model/Task1_ResNet50_ImageNet/Task1_ResNet50-{epoch:02d}-{val_loss:.2f}.h5', verbose=1, save_best_only=True)
```
**The path here in ModelCheckpoint is a wrong path since there is NO sub-folder named "Task1_ResNet50_ImageNet" in "Model" folder. While after 30 epochs training, there is no error raised, neither model saved.**

**Describe the expected behavior**
It was supposed to raise error since there is no such a directory to save modelcheckpoint. While after 3 days training, I got nothing saved! It wastes me lots of time.

**Standalone code to reproduce the issue** 
Since my own code is too complicated, I use the example code from [Keras.io](https://keras.io/getting-started/sequential-model-guide/#multilayer-perceptron-mlp-for-multi-class-softmax-classification) to explain this problem: [stand alone gist](https://colab.research.google.com/gist/MakeCent/5ac59661a91e1d5126b89e6b0026e1c0/38294.ipynb)

**Other info / logs**
During the training, it print save model information like below, which looks like working well:
`Epoch 00008: val_loss improved from 9.19709 to 8.58308, saving model to Output/task1/Model/Task1_ResNet50_ImageNet/Task1_ResNet50_ImageNet-08-8.58.h5`

**Comment by aniketmaurya** [comment]
I have also faced the same issue.

**Comment by Saduf2019** [comment]
@MakeCent 
please provide us with complete standalone code for us to replicate the issue faced.

**Comment by MakeCent** [comment]
> @MakeCent
> please provide us with complete standalone code for us to replicate the issue faced.

I have update standalone code based on an example code from [Keras.io ](https://keras.io/getting-started/sequential-model-guide/#multilayer-perceptron-mlp-for-multi-class-softmax-classification)

**Comment by Saduf2019** [comment]
@MakeCent
please share simple stand alone code for us to replicate the issue, if possible please share a colab gist of the code and issue faced.

**Comment by MakeCent** [comment]
@Saduf2019 But the stand alone code I had provided in this issue can already replicate the issue.

**Comment by Saduf2019** [comment]
@MakeCent 
i have made the required change in gist shared, now the code works fine, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/adf8644fb73b495d48c5bcfee2f9e070/38294.ipynb)

import tensorflow.keras instead import keras, please confirm if this resolves your issue.

**Comment by MakeCent** [comment]
@Saduf2019 
It seems it only appear in tf-nightly. Please check the [code](https://colab.research.google.com/gist/MakeCent/2dc3c07dbbad5fdd31eab04099e22e1f/38294.ipynb) here.

**Comment by ZimmerZheng** [comment]
**I want to save Model as XXX.ckpt. But when I set "save_weights_only=False":** 
_`cp_callback = tf.keras.callbacks.ModelCheckpoint(filepath=ckpt_models/test.ckpt,
                                                 save_weights_only=False,
                                                 verbose=0,mode='auto')
model.fit(x_train, y_train, epochs=5,callbacks=[cp_callback])`_
**It raise an error::**
`tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: ckpt_models/test.ckpt\variables; No such file or directory`

**Comment by Saduf2019** [comment]
please find the gist of the [issue here](https://colab.sandbox.google.com/gist/Saduf2019/f922b54fd9c5d41bcd4c5568216bb83a/untitled131.ipynb)

**Comment by MakeCent** [comment]
@ZimmerZheng  
[Gist](https://colab.research.google.com/gist/MakeCent/6b82f91978ced9b32a07b7401b7e355c/38294.ipynb) I test your code on tensorflow 2.1, but no error raised and every ckpt files saved  correctly. Maybe you need check if it's related to your tf version. By the way, if you want to save whole model in addition to weights, you'd better to use HDM5(.h5) or SaveModel(no extension).

**Comment by ZimmerZheng** [comment]
@Saduf2019 @MakeCent 
Thank everyone. I have solved problem. Error was caused by save path have both '/' and '\'. 
If I only use ‘\’ in path, the problem gone.

**Comment by Saduf2019** [comment]
@ZimmerZheng
please confirm if we may move this to closed status as it is resolved

**Comment by Saduf2019** [comment]
@MakeCent
Is this still an issue?
