### ISSUE TITLE
ERROR: Did not get operators, tensors, or buffers in subgraph 0.

### ISSUE THREAD

**Issue by shauryad15** [tensorflow/tensorflow#38298]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- Tensorflow version (commit SHA if source): 2.01
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Android

**Describe the problem**
While loading the interpreter from to read the detect.tflite file i'm getting the following error. The link to the model file is https://drive.google.com/open?id=1xxMLG1JLB_6ssCJ8xMOhtJGZo1P_dewc
**Please provide the exact sequence of commands/steps when you ran into the problem**
The detect.tflite file and the respective frozen graph is hereby i'm attaching. 
Also, the code to read the same is as follows:

#include <math.h>
#include <stdio.h>

#include <algorithm>
#include <chrono>
#include <fstream>
#include <memory>
#include <string>
#include <vector>

//#include <gflags/gflags.h>
#include <glog/logging.h>
#include <tensorflow/lite/delegates/gpu/gl_delegate.h>
#include <tensorflow/lite/kernels/register.h>
#include <tensorflow/lite/model.h>
#include <opencv2/core.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/imgproc.hpp>

//#include "test_video.hpp"
//#include "video_encoder.hpp"
#include "config_parser.h"
#include "lane_detection.h"

#define IMAGE_MEAN 128.0f
#define IMAGE_STD 128.0f

template <typename T>
T* TensorData(TfLiteTensor* tensor, int batch_index);

template <>
float* TensorData(TfLiteTensor* tensor, int batch_index) {
  int nelems = 1;
  for (int i = 1; i < tensor->dims->size; i++)
    nelems *= tensor->dims->data[i];
  switch (tensor->type) {
    case kTfLiteFloat32:
      return tensor->data.f + nelems * batch_index;
    default:
      LOG(FATAL) << "Should not reach here!";
  }
  return nullptr;
}

template <>
uint8_t* TensorData(TfLiteTensor* tensor, int batch_index) {
  int nelems = 1;
  for (int i = 1; i < tensor->dims->size; i++)
    nelems *= tensor->dims->data[i];
  switch (tensor->type) {
    case kTfLiteUInt8:
      return tensor->data.uint8 + nelems * batch_index;
    default:
      LOG(FATAL) << "Should not reach here!";
  }
  return nullptr;
}

bool LaneDetection::init(const ConfigParser& config, bool is_quantized) {
  using config_content = std::map<std::string, std::string>;
  config_content config_section;

  LOGI("LaneDetect: reading config");
  std::cout << "LaneDetect: reading config" << std::endl;
  try {
    config_section = config["LaneNet"];
  } catch (const std::out_of_range& e) {
    LOGE(e.what());
    LOGE(
        "Can not get LaneNet section content in config file, please "
        "check again");
    _m_successfully_initialized = false;
    return false;
  }

  if (config_section.find("dbscan_neighbor_radius") == config_section.end()) {
    LOGE("Can not find \"dbscan_neighbor_radius\" field in config section");
    _m_successfully_initialized = false;
    return false;
  } else {
    _m_dbscan_eps = std::stof(config_section["dbscan_neighbor_radius"]);
  }

  if (config_section.find("dbscan_core_object_min_pts") ==
      config_section.end()) {
    LOGE(
        "Can not find \"dbscan_core_object_min_pts\" field in config "
        "section");
    _m_successfully_initialized = false;
    return false;
  } else {
    _m_dbscan_min_pts =
        std::atoi(config_section["dbscan_core_object_min_pts"].c_str());
  }

  if (config_section.find("pix_embedding_feature_dims") ==
      config_section.end()) {
    LOGE(
        "Can not find \"pix_embedding_feature_dims\" field in config "
        "section");
    _m_successfully_initialized = false;
    return false;
  } else {
    _m_lanenet_pix_embedding_feature_dims =
        std::atoi(config_section["pix_embedding_feature_dims"].c_str());
  }

  if (config_section.find("model_file_path") == config_section.end()) {
    LOGE("Can not find \"model_file_path\" field in config section");
    _m_successfully_initialized = false;
    return false;
  } else {
    _m_lanenet_model_file_path = config_section["model_file_path"];
  }

  LOGI("LaneDetect: read config file");
  std::cout << "LaneDetect: read config file" << std::endl;

  ///////////////////////////////
  model_ = tflite::FlatBufferModel::BuildFromFile(
      _m_lanenet_model_file_path.c_str());
  if (!model_) {
    LOGI("LaneDetect: Failed to load model: %s",
         _m_lanenet_model_file_path.c_str());
    std::cout << "LaneDetect: Failed to load model: "
              << _m_lanenet_model_file_path << std::endl;
    return false;
  }

  // Create interpreter.
  tflite::ops::builtin::BuiltinOpResolver resolver;
  tflite::InterpreterBuilder(*model_, resolver)(&interpreter_);
  if (!interpreter_) {
    LOGI("LaneDetect: Failed to create interpreter!");
    std::cout << "LaneDetect: Failed to create interpreter!" << std::endl;
    return false;
  }
  /* if (interpreter_->AllocateTensors() != kTfLiteOk)
  {
      LOG(ERROR) << "Failed to allocate tensors!";
      return false;
  } */
  interpreter_->SetNumThreads(1);

  const TfLiteGpuDelegateOptions options = {
      .metadata = NULL,
      .compile_options =
          {
              .precision_loss_allowed = 1,  // FP16
              .preferred_gl_object_type = TFLITE_GL_OBJECT_TYPE_FASTEST,
              .dynamic_batch_enabled = 0,  // Not fully functional yet
          },
  };
  auto* delegate = TfLiteGpuDelegateCreate(&options);
  if (interpreter_->ModifyGraphWithDelegate(delegate) != kTfLiteOk) {
    interpreter_->UseNNAPI(true);
    LOGI("LaneDetect: gpu delegate failed ! adding nnAPI support");
    std::cout << "LaneDetect: gpu delegate failed ! adding nnAPI support"
              << std::endl;
  }

  // Find input tensors.
  if (interpreter_->inputs().size() != 1) {
    LOGI("LaneDetect: Graph needs to have 1 and only 1 input!");
    std::cout << "LaneDetect: Graph needs to have 1 and only 1 input!"
              << std::endl;
    return false;
  }
  input_tensor_ = interpreter_->tensor(interpreter_->inputs()[0]);
  if (is_quantized) {
    if (input_tensor_->type != kTfLiteUInt8) {
      LOGI("LaneDetect: Quantized graph's input should be kTfLiteUInt8!");
      std::cout << "LaneDetect: Quantized graph's input should be kTfLiteUInt8!"
                << std::endl;
      return false;
    }
  } else {
    if (input_tensor_->type != kTfLiteFloat32) {
      LOGI("LaneDetect: Quantized graph's input should be kTfLiteFloat32!");
      std::cout
          << "LaneDetect: Quantized graph's input should be kTfLiteFloat32!"
          << std::endl;
      return false;
    }
  }

  // Find output tensors.
  if (interpreter_->outputs().size() != 2) {
    LOGI(
        "LaneDetect: Graph needs to have 2 and only 2 outputs! It has %d "
        "outputs though!!!",
        interpreter_->outputs().size());
    std::cout << "LaneDetect: Graph needs to have 2 and only 2 outputs! It has "
              << interpreter_->outputs().size() << " outputs though!!!"
              << std::endl;
    return false;
  }
  output_binary_mask_ = interpreter_->tensor(interpreter_->outputs()[0]);
  output_instance_mask_ = interpreter_->tensor(interpreter_->outputs()[1]);

  _m_input_node_size_host.width = width();
  _m_input_node_size_host.height = height();

  return true;
}

void LaneDetection::preprocess(const cv::Mat& input_image,
                               cv::Mat& output_image) {
  if (input_image.type() != CV_32FC3) {
    input_image.convertTo(output_image, CV_32FC3);
  } else {
    input_image.copyTo(output_image);
  }
  // BGR2RGB
  cv::cvtColor(output_image, output_image, cv::COLOR_BGR2RGB);

  LOGI("LaneDetect: output image size : %d x %d  check size : %d x %d",
       output_image.size().width, output_image.size().height,
       _m_input_node_size_host.width, _m_input_node_size_host.height);

  // resizing to the input size of the model
  if (output_image.size() != _m_input_node_size_host) {
    cv::resize(output_image, output_image, _m_input_node_size_host);
  }

  // // making mean 0 and range 2
  // cv::divide(output_image, cv::Scalar(127.5, 127.5, 127.5), output_image);
  // cv::subtract(output_image, cv::Scalar(1.0, 1.0, 1.0), output_image);
  return;
}

void LaneDetection::FeedInMat(const cv::Mat& mat, int batch_index) {
  switch (input_tensor_->type) {
    case kTfLiteFloat32: {
      float* dst = TensorData<float>(input_tensor_, batch_index);
      const int row_elems = width() * input_channels();
      for (int row = 0; row < height(); row++) {
        const uchar* row_ptr = mat.ptr(row);
        for (int i = 0; i < row_elems; i++) {
          dst[i] = (row_ptr[i] - IMAGE_MEAN) / IMAGE_STD;
        }
        dst += row_elems;
      }
    } break;
    case kTfLiteUInt8: {
      uint8_t* dst = TensorData<uint8_t>(input_tensor_, batch_index);
      const int row_elems = width() * input_channels();
      for (int row = 0; row < height(); row++) {
        memcpy(dst, mat.ptr(row), row_elems);
        dst += row_elems;
      }
    } break;
    default:
      LOG(FATAL) << "Should not reach here!";
  }
}

void LaneDetection::detect(cv::Mat& image,
                           cv::Mat& binary_seg_result,
                           cv::Mat& instance_seg_result) {
  // preprocess
  cv::Mat input_image_copy;
  preprocess(image, input_image_copy);

  FeedInMat(input_image_copy, 0);
  if (interpreter_->Invoke() != kTfLiteOk) {
    LOGI("LaneDetect: Unable to invoke TfLite");
    return;
  }
  std::cout << "Lane detection ran successfully" << std::endl;
}

**Comment by shauryad15** [comment]
any solution?

**Comment by sushreebarsa** [comment]
@shauryad15 This is a micro related issue,Please post this in [micro repository](https://github.com/tensorflow/tflite-micro/issues)  we will get you the right help..Thanks!
