### ISSUE TITLE
Cant install tensorflow

### ISSUE THREAD

**Issue by generationzcode** [tensorflow/tensorflow#38297]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):Pip
- TensorFlow version:2.1.0
- Python version:3.7
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I cant install tensorflow. It says that an error occured and tensorflow isn't found. 
**Provide the exact sequence of commands / steps that you executed before running into the problem**
python pip install tensorflow

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@generationzcode 

Can you please go through instructions mentioned in [Tensorflow website](https://www.tensorflow.org/install/pip). You can install by `pip install tensorflow`. If you are still facing any issue please, share error log. Thanks!

**Comment by generationzcode** [comment]
I did that. I've done it like 5 or six times... I tried installing it from the URL for the wheel. It didn't work either

**Comment by generationzcode** [comment]
Ok
I'll share the error statement

**Comment by generationzcode** [comment]
`ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
`

**Comment by ravikyram** [comment]
@generationzcode 

Can you please go through the [link](https://stackoverflow.com/questions/38896424/tensorflow-not-found-using-pip) and see if it helps you. Thanks!

**Comment by generationzcode** [comment]
I've been struggling with this for a few weeks. Thanks @ravikyram  for your help. I figured it out. Anyone else looking at this issue, the answer is installing a 64 bit version of python. :)
