### ISSUE TITLE
tensorflow1.13 add an op which use mkldnn cannot build sucessfully

### ISSUE THREAD

**Issue by wangyunxiaa** [tensorflow/tensorflow#38295]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes, in tensorflow/core/user_ops addop
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: windows10
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:1.13
- **Python version**:3.6
- **Bazel version (if compiling from source)**:0.20.0
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:None
- **GPU model and memory**:None
- **Exact command to reproduce**:
I just add an matmul op which use a function in mkldnn,and I can build successfully with `bazel build  -c opt --copt=-msse4.1 --copt=-msse4.2  tensorflow:libtensorflow.so`  
But, when I build the target with `bazel build  -c opt --copt=-msse4.1 --copt=-msse4.2   //tensorflow/tools/pip_package:build_pip_package` , I got an error
`ERROR: D:/tf_install/tensorflow_addop/tensorflow/python/BUILD:4057:1: in cmd attribute of genrule rule //tensorflow/python:gen__pywrap_tensorflow_internal.pyd: variable '$<' : more than one input file. Since this rule was created by the macro 'tf_py_wrap_cc', the error might have been caused by the macro implementation in D:/tf_install/tensorflow_addop/tensorflow/tensorflow.bzl:1704:15
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis of target '//tensorflow/python:gen__pywrap_tensorflow_internal.pyd' failed; build aborted`

I just add some codes in `tensorflow/python/user_ops/user_ops.py`
`@tf_export(v1=['user_ops.own_dnnl_mul'])
def own_dnnl_mul(arg1, arg2):
  """Example of overriding the generated code for an Op."""
return _gen_user_ops.own_dnnl_mul(arg1, arg2)
`

**Comment by gadagashwini** [comment]
@wangyunxiaa, Could you provide the standalone code to analyze the issue. Thanks

**Comment by wangyunxiaa** [comment]
Thanks for your reply,

I just add some codes in "tensorflow/core/user_ops"
and changed the BUILD file in "tensorflow/core"
```
cc_library(
    name = "user_ops_op_lib",
    srcs = glob(["user_ops/**/*.cc", "user_ops/**/*.h", "user_ops/**/*.hpp"]),
    visibility = ["//visibility:public"],
    deps = [":framework", ":dnnl", "mkldnn", ":iomp5md"],
    copts = ["-fexceptions"],
    linkopts = ["-fopenmp"],
    alwayslink = 1,
    )
```
With above changes, I can build libtensorflow.so successfully.

But I want to build a whl to do a test,
I changed the file in "tensorflow/python/user_ops/user_ops.py"

```
@tf_export(v1=['user_ops.fsmn_forward'])
def fsmn_forward(arg1, arg2, arg3, arg4, arg5, arg6, arg7):
  """Example of overriding the generated code for an Op."""
  return _gen_user_ops.fsmn_forward(arg1, arg2, arg3, arg4, arg5, arg6, arg7)

@tf_export(v1=['user_ops.own_dnnl_mul'])
def own_dnnl_mul(arg1, arg2):
  """Example of overriding the generated code for an Op."""
  return _gen_user_ops.own_dnnl_mul(arg1, arg2)

```
I am confused that, the problem was  caused by mkldnn, because, when I add one op which is not dependences on mkl-dnn, I can build .so and .whl, when I add `deps = [":framework", ":dnnl", "mkldnn", ":iomp5md"],` I just can build .so but not .whl
the error is as floowings:
`ERROR: D:/tf_install/tensorflow_addop/tensorflow/python/BUILD:4057:1: in cmd attribute of genrule rule //tensorflow/python:gen__pywrap_tensorflow_internal.pyd: variable '$<' : more than one input file. Since this rule was created by the macro 'tf_py_wrap_cc', the error might have been caused by the macro implementation in D:/tf_install/tensorflow_addop/tensorflow/tensorflow.bzl:1704:15 ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis of target '//tensorflow/python:gen__pywrap_tensorflow_internal.pyd' failed; build aborted
`

**Comment by wangyunxiaa** [comment]
Sorry,
I have solved this problem by the following way.
At the beginning,I add the cc_import library as followings:
```
cc_import(
  name = "mylib",
  hdrs = ["mylib.h"],
  # mylib.lib is a import library for mylib.dll which will be passed to linker
  interface_library = "mylib.lib",
  # mylib.dll will be available for runtime
  shared_library = "mylib.dll",
)
```
I was always got the error metioned above.
However, I changed the  cc_import library to:
```
cc_import(
  name = "mylib",
  hdrs = ["mylib.h"],
  # mylib.lib is an import library for mylib.dll which will be passed to linker
  interface_library = "mylib.lib",
  # mylib.dll is provided by system environment, for example it can be found in PATH.
  # This indicates that Bazel is not responsible for making mylib.dll available.
  system_provided = 1,
)
```
Then, I could build the .whl successfully.
But I donnot know the difference between `Linking a shared library with interface library (Windows)` and  `Linking a shared library with system_provided=True (Windows)` 

Best Regards

**Comment by NeoZhangJianyu** [comment]
@wangyunxiaa Have the above solution resolved your issue? If yes, could you close it?

**Comment by NeoZhangJianyu** [comment]
@wangyunxiaa 

Could you feedback?

**Comment by NeoZhangJianyu** [comment]
@wangyunxiaa 

If your issue is fixed, could you close this issue?

**Comment by NeoZhangJianyu** [comment]
@wangyunxiaa 
Could you feedback?

Thank you!

**Comment by mihaimaruseac** [comment]
Closing as resolved
