### ISSUE TITLE
tf.train.saver.restore failed error

### ISSUE THREAD

**Issue by Honghe** [tensorflow/tensorflow#383]
Cause training a model is time consuming, So Save a Checkpoint on training, but error occurred when to restore.
The `saver.restore` says as follow:
```
Signature: saver.restore(sess, save_path)
Docstring:
Restores previously saved variables.

This method runs the ops added by the constructor for restoring variables.
It requires a session in which the graph was launched.  The variables to
restore do not have to have been initialized, as restoring is itself a way
to initialize variables.

The `save_path` argument is typically a value previously returned from a
`save()` call, or a call to `latest_checkpoint()`.

Args:
  sess: A Session to use to restore the parameters.
  save_path: Path where parameters were previously saved.
```

So I used it as following:
```
with tf.Graph().as_default():
    saver = tf.train.Saver()
    sess = tf.Session()
    Saver.restore(sess, "./MNIST_data/-1")
```
But got the following err:
```
ValueError                                Traceback (most recent call last)
<ipython-input-10-4c62153b8108> in <module>()
     31 
     32 with tf.Graph().as_default():
---> 33     saver = tf.train.Saver()
     34     sess = tf.Session()
     35     Saver.restore(sess, "./MNIST_data/-1")

/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.pyc in __init__(self, var_list, reshape, sharded, max_to_keep, keep_checkpoint_every_n_hours, name, restore_sequentially, saver_def, builder)
    678         var_list = variables.all_variables()
    679       if not var_list:
--> 680         raise ValueError("No variables to save")
    681       saver_def = builder.build(
    682           var_list,

ValueError: No variables to save
```

**Comment by vrv** [comment]
You haven't defined the graph yet: "It requires a session in which the graph was launched."

If you create your graph with all of the variables / ops that you want to restore, and then create the Saver, it should work.

**Comment by vrv** [comment]
(Feel free to reopen if creating/launching the graph doesn't solve the problem for you).

**Comment by HamedMP** [comment]
@vrv  I had same problem and headed here to see if it's a bug or not,

I have eval.py for calculating my CNN accuracy and used exactly same method to load ckpt file. I got this error but using tf.Graph() doesn't help. Instead creating a `dummy` variable solve the error.

> p.s just inform you that this code is not working and got stuck in the `sess.run(acc)`

```python
with tf.Graph().as_default():

    dummy = tf.Variable(0)  # dummy variable !!!
    init_op = tf.initialize_all_variables()

    with tf.Session() as sess:

      sess.run(init_op)

      saver = tf.train.Saver()
      # Start the queue runners.
      coord = tf.train.Coordinator()
      threads = tf.train.start_queue_runners(sess=sess, coord=coord)

      summary_op = tf.merge_all_summaries()

      summary_writer = tf.train.SummaryWriter(FLAGS.eval_dir,
                                              graph_def=sess.graph_def)


      ckpt = tf.train.get_checkpoint_state(checkpoint_dir=FLAGS.checkpoint_dir)
      print ckpt.model_checkpoint_path
      if ckpt and ckpt.model_checkpoint_path:
        saver.restore(sess, ckpt.model_checkpoint_path)
        print('Restored!')

      images, labels = my_input.inputs_val()

      # Build a Graph that computes the logits predictions from the
      # inference model.
      logits = my_cifar.inference(images)

      acc = my_cifar.evaluation(logits, labels)

      tf.scalar_summary('Acc', acc)

      try:
        while not coord.should_stop():
          print('Calculating Acc:')
          acc_r = sess.run(acc)
          print(acc_r)

          # Write results to TensorBoard
          summary_str = sess.run(summary_op)
          summary_writer.add_summary(summary_str)

      except tf.errors.OutOfRangeError:
        print ('Done training -- epoch limit reached')

      finally:
        # When done, ask the threads to stop.
        coord.request_stop()

      coord.join(threads)
```

**Comment by Vikramank** [comment]
Hi,
I am trying to restore a saved model . But it is returning me an error. Please help me out. 
**code to save the model : save_model.py** 

```
import tensorflow as tf
v1 = tf.Variable(1.32, name="v1")
v2 = tf.Variable(1.33, name="v2")

init = tf.initialize_all_variables()

saver = tf.train.Saver()

with tf.Session() as sess:
  sess.run(init)
  save_path = saver.save(sess, "model.ckpt")
```
 
**code to restore model : restore_model.py** 

```
import tensorflow as tf
v1 = tf.Variable(0, name="v1")
v2 = tf.Variable(0, name="v2")


saver = tf.train.Saver()

with tf.Session() as sess:
  saver.restore(sess, "model.ckpt")
  print("Model restored.")
```
I have saved both the files in the same directory.

**Comment by Vikramank** [comment]
I am able to restore models within the same Python script,  but I am unable to restore in a different script in the method stated above.

**Comment by genimarca** [comment]
Yes, I have so far the same problem.

**Comment by jrajagopal** [comment]
Same here.

**Comment by plooney** [comment]
Try using

saver.restore(sess, tf.train.latest_checkpoint('./') )

**Comment by gdelab** [comment]
I have the same problem when I try to restore a graph trained on a different machine, although it works on the same machine.
More precisely,  I get
`KeyError: 'VariableV2'`
on the tf.train.import_meta_graph

`    tf.reset_default_graph()
    with tf.Session() as sess:
        # Restore graph
        saver = tf.train.import_meta_graph(model_filename_path)
        saver.restore(sess, path_to_ckpt)
`

**Comment by ivan-san41** [comment]
I also had the KeyError: 'VariableV2' when restoring the graph from a checkpoint that was saved in another machine. It turned out that the tensorflow versions were different. Upgrading solved the problem

**Comment by qnkhuat** [comment]
add this should be solve

'from_detection_checkpoint: true'

**Comment by jakalaka** [comment]
modify the config file and add the 'from_detection_checkpoint: true' solve the problem

**Comment by 631068264** [comment]
@jakalaka where the config file?

**Comment by ColinWang1203** [comment]
from_detection_checkpoint: true is already in the config file

**Comment by yueyinlizun** [comment]
Here is a useful method.[https://blog.csdn.net/yueyinlizun/article/details/89057243](url)

**Comment by yueyinlizun** [comment]
Just update the tensorflow to a newer version.
