### ISSUE TITLE
tf.lookup.StaticHashTable: Cannot convert a Tensor of dtype resource to a NumPy array

### ISSUE THREAD

**Issue by jeanmn** [tensorflow/tensorflow#38305]
**System information** 

- Have I written custom code:  Yes
- OS Platform and Distribution: macOS 10.14.6
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):  v2.1.0-rc2-17-ge5bf8de410 2.1.0
- Python version: 3.7.4

**Describe the current behavior**
I have some input that I need to translate,
```
"Dog" -> 0
"Cat" -> 1
...
```
and then embed.

I tried to use the `tf.lookup.StaticHashTable` for this, but it works when the input is a `tf.Variable`, not when using `tf.keras.layers.Input`, see the following output: 

```
In [6]:
inputs1 = tf.Variable([[3]], dtype=tf.int64)
translate_and_embed(inputs1)
Out[6]:
<tf.Tensor: shape=(1, 1, 10), dtype=float32, numpy=
array([[[ 0.01451602,  0.04537327, -0.00232627,  0.00584463,
         -0.04128218, -0.03868868,  0.04147324, -0.02444596,
          0.03310961,  0.01144157]]], dtype=float32)>
In [7]:
inputs2 = tf.keras.layers.Input(shape=(1,), dtype=tf.int64)
translate_and_embed(inputs2)
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-10-b2c4cfd055e5> in <module>()
      1 inputs2 = tf.keras.layers.Input(shape=(1,), dtype=tf.int64)
----> 2 translate_and_embed(inputs2)

<ipython-input-8-340bf85dfb2f> in translate_and_embed(inputs)
     21         output_dim=10,
     22     )
---> 23     return embedder(translated)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    718     # framework.
    719     if build_graph and base_layer_utils.needs_keras_history(inputs):
--> 720       base_layer_utils.create_keras_history(inputs)
    721 
    722     # Clear eager losses on top level model call.

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer_utils.py in create_keras_history(tensors)
    185     keras_tensors: The Tensors found that came from a Keras Layer.
    186   """
--> 187   _, created_layers = _create_keras_history_helper(tensors, set(), [])
    188   return created_layers
    189 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer_utils.py in _create_keras_history_helper(tensors, processed_ops, created_layers)
    245           else:
    246             with ops.init_scope():
--> 247               constants[i] = backend.function([], op_input)([])
    248       processed_ops, created_layers = _create_keras_history_helper(
    249           layer_inputs, processed_ops, created_layers)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py in __call__(self, inputs)
   3733     return nest.pack_sequence_as(
   3734         self._outputs_structure,
-> 3735         [x._numpy() for x in outputs],  # pylint: disable=protected-access
   3736         expand_composites=True)
   3737 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py in <listcomp>(.0)
   3733     return nest.pack_sequence_as(
   3734         self._outputs_structure,
-> 3735         [x._numpy() for x in outputs],  # pylint: disable=protected-access
   3736         expand_composites=True)
   3737 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py in _numpy(self)
    908       return self._numpy_internal()
    909     except core._NotOkStatusException as e:
--> 910       six.raise_from(core._status_to_exception(e.code, e.message), None)
    911 
    912   @property

/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: Cannot convert a Tensor of dtype resource to a NumPy array.
```

**Describe the expected behavior**
I expect the second function call to return a symbolic tensor.

**Standalone code to reproduce the issue** 
- https://colab.research.google.com/gist/jeanmn/6d2821feaf4828f43524ada267db266f/tf-lookup-statichhashtable-cannot-convert-a-tensor-of-dtype-resource-to-a-numpy-array.ipynb
- https://gist.github.com/jeanmn/6d2821feaf4828f43524ada267db266f

**Other info / logs**
- Similar issue? https://github.com/tensorflow/tensorflow/issues/37441
- Related? #37844

**Comment by Saduf2019** [comment]
@jeanmn 
please refer to below issues and let us know if it helps:
#37844 #32999 #[link](https://stackoverflow.com/questions/59962509/valueerror-cannot-convert-a-tensor-of-dtype-resource-to-a-numpy-array)

**Comment by jeanmn** [comment]
> @jeanmn
> please refer to below issues and let us know if it helps:
> #37844 #32999 #[link](https://stackoverflow.com/questions/59962509/valueerror-cannot-convert-a-tensor-of-dtype-resource-to-a-numpy-array)

- #37844
This is the same issue that I was referring to. That issue seems to be related to TFlite conversion? My issue is happening without any TFlite conversion, which leads me to believe that there is some issue with the StaticHashMap itself.
[The suggested example](https://github.com/tensorflow/tensorflow/issues/37844#issuecomment-605336360) from @abattery looked promising, 
but as far as I can see `tf.initializers.tables_initializer`  raises an
```
AttributeError: module 'tensorflow_core.python.keras.api._v2.keras.initializers' has no attribute 'tables_initializer'
```
for tensorflow 2.1.0 (and later?). 

- #32999
This issue also seems to describe problems that happen during TFlite conversion. I'm not sure how it helps my case.

- [stackoverflow link](https://stackoverflow.com/questions/59962509/valueerror-cannot-convert-a-tensor-of-dtype-resource-to-a-numpy-array)
This is the other issue that I was referring to in my issue description. #37441
It is also unresolved, and appears similar to mine.

Please direct me to the correct answer suggestion if I have missed it.

Here is the function from my gist that I am trying to run, (the one that fails when feeding an Input layer):
```
import tensorflow as tf

def translate_and_embed(inputs):
    keys = [0,1,2,3]
    values = [0,10,20,30]

    initializer = tf.lookup.KeyValueTensorInitializer(
        keys=keys,
        values=values,
        key_dtype=tf.int64,
        value_dtype=tf.int64,
    )
    table = tf.lookup.StaticHashTable(
        initializer,
        default_value=-1,
    )
    translated = table.lookup(inputs)

    embedder = tf.keras.layers.Embedding(
        input_dim=max(values)+1,
        output_dim=10,
    )
    return embedder(translated)
```

**Comment by Saduf2019** [comment]
i am able to replicate this, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/295838ac302571e25c0d1c8c4a9c476d/38305.ipynb)

**Comment by jvishnuvardhan** [comment]
@jeanmn I guess `lookup` method in `tf.lookup.StaticHashTable1 is looking for a Eager Tensor where as you provided a Symbolic Tensor. Please check the source [here](https://www.tensorflow.org/api_docs/python/tf/lookup/StaticHashTable#lookup). Thanks!

**Comment by abattery** [comment]
Currently, Tensorflow Lite does not support Keras layer + hash table use cases yet. I am working on enabling this path. Will notify the updates in the thread later.

**Comment by jeanmn** [comment]
@jvishnuvardhan 
This is my use case: I am trying to construct and save a model architecture where the first layer should be a lookup operation. If I am forced to use an EagerTensor, does this mean that what I am trying to achieve with the StaticHashTable is impossible?

In [the link to the documentation you sent me](https://www.tensorflow.org/api_docs/python/tf/lookup/StaticHashTable#lookup) I don't see any indication that the lookup operation is supposed to **not** handle symbolic tensors:
> [keys: Keys to look up. May be either a SparseTensor or dense Tensor.](https://www.tensorflow.org/api_docs/python/tf/lookup/StaticHashTable#lookup)

What am I missing?

@abattery 
Are you saying that your work will possibly fix my issue also? Note that I am not working with Tensorflow Lite here.

**Comment by abattery** [comment]
`InvalidArgumentError: Cannot convert a Tensor of dtype resource to a NumPy array.`

@jeanmn Yes, this error is related to the same problem I mentioned in the above comment.

**Comment by wileeam** [comment]
This error also shows up with the TensorFlow version `2.2.0rc3`

**Comment by wsuchy** [comment]
Same issue here, when I try build Keras model based on my graph:
```
import tensorflow as tf

from tensorflow.keras.layers import  Input
from tensorflow.keras import Model
import numpy as np
tf.keras.backend.clear_session()

in3 = tf.keras.Input(shape=(1,), name="in3", dtype=tf.string)
keys_tensor = tf.constant(["A", "B"])
vals_tensor = tf.constant([9, 10])
table = tf.lookup.StaticHashTable(
    tf.lookup.KeyValueTensorInitializer(keys_tensor, vals_tensor)
    , -1)
out = table.lookup(in3)
model = Model(inputs=[in3], outputs=out)
model.summary()
```
It looks that the problem is with the Tensor: 
`Tensor("None_Lookup/LookupTableFindV2/table_handle:0", shape=(), dtype=resource)`
as it can't be simply converted to `numpy`

**Comment by jithinjees** [comment]
The following sample code worked in tensorflow 2.1 & 2.2 - 

Main point is to extend keras layer object & use lookup operation inside that.
Here's the sample code - https://gist.github.com/jithinjees/a99e57af3812be2c84bdc2ef84ad0de6 
In the link above i have listed lookup using 2 different classes, 1 is file based lookup & other one is an in-memory list based lookup.
For the file based lookup the input file used is a text file which contains one word per line

Here's a gist of that code - 

```python
class VocabLookup(tf.keras.layers.Layer):
    def __init__(self,vocab_path):
        super(VocabLookup, self).__init__(trainable=False,dtype=tf.int64)
        self.vocab_path = vocab_path
    def build(self,input_shape):
        table_init = tf.lookup.TextFileInitializer(self.vocab_path,tf.string,tf.lookup.TextFileIndex.WHOLE_LINE,
                              tf.int64,tf.lookup.TextFileIndex.LINE_NUMBER)
        self.table = tf.lookup.StaticHashTable(table_init,-1)
        self.built=True
        
    def call(self, input_text):
        splitted_text = tf.strings.split(input_text).to_tensor()
        word_ids = self.table.lookup(splitted_text)
        return word_ids
    
    def get_config(self):
        config = super(VocabLookup, self).get_config()
        config.update({'vocab_path': self.vocab_path})
        return config 
input_text = tf.keras.Input(shape=(),dtype=tf.string,name='input_text')
lookup_out = VocabLookup(vocab_path=vocab_path)(input_text)
model_lookup = tf.keras.Model(inputs={'input_text':input_text},outputs=lookup_out)

```

Hope this helps

**Comment by hanggun** [comment]
I had the same issue when i use TF2.0.0, here is my sample code
`keys_tensor = tf.constant(range(27), tf.int64)
vals_tensor = tf.constant([0]*11+[1]*9+[2]*6+[3], tf.int64)
table = tf.lookup.StaticHashTable(
    tf.lookup.KeyValueTensorInitializer(keys_tensor, vals_tensor), -1)

inputs = layers.Input(shape=(4))
inputs1 = layers.Input(shape=(4))
x = layers.Dense(4)(inputs)
model = keras.Model([inputs,inputs1], x)

key = tf.argmax(inputs1, axis=1)
matches = table.lookup((key))
matches = tf.one_hot(matches, depth=4)
loss = K.categorical_crossentropy(matches, inputs1)

model.add_loss(loss)
model.compile(optimizer=keras.optimizers.Adam(1e-3))

x_train = tf.ones(shape=[2,4])
y_train = tf.constant([[0,0,0,1],[0,0,1,0]])
model.fit([x_train, y_train])`

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210525, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/7f227fa8ae315a91e96a09ee83ce3a2e/untitled7.ipynb). Thanks!

**Comment by wangruinju** [comment]
@jithinjees were you able to use this to serve the model?

**Comment by jithinjees** [comment]
@wangruinju yes, not exactly the same one, but another model using the same approach of creating a tf.lookup.StaticHashTable
