### ISSUE TITLE
Master build failed with user local specific GCC

### ISSUE THREAD

**Issue by chuanqi129** [tensorflow/tensorflow#38300]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Both `CentsOS 7.3` and `Ubuntu 18.04` 
- TensorFlow installed from (source or binary): build from source
- TensorFlow version: master (f32548266f25890fc654342296dc112f26ad9bf6)
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): GCC 6.3

**Describe the problem**

**After the upgrade of protobuf, we can't use the user local GCC to build TF master branch**
I have already set the `env` for specified GCC as below
```
export PATH="/home/chuanqiw/lib/gcc-build-6.3.0/bin:$PATH"
export LD_LIBRARY_PATH="/home/chuanqiw/lib/gcc-build-6.3.0/lib64:$LD_LIBRARY_PATH"
```
Build command I used:
`bazel build --config=mkl --define=build_with_mkl_dnn_v1_only=true --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mavx512f --copt=-mavx512pf --copt=-mavx512cd --copt=-mavx512bw --copt=-mavx512dq --copt=-DENABLE_INTEL_MKL_BFLOAT16 -c opt //tensorflow/tools/pip_package:build_pip_package`

**Any other info / logs**
```
ERROR: /home/chuanqiw/tensorflow/gitlab/private-tensorflow/tensorflow/core/data/service/BUILD:308:1: Action tensorflow/core/data/service/worker.grpc.pb.h failed (Exit 1)
bazel-out/host/bin/external/com_google_protobuf/protoc: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by bazel-out/host/bin/external/com_google_protobuf/protoc)
bazel-out/host/bin/external/com_google_protobuf/protoc: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by bazel-out/host/bin/external/com_google_protobuf/protoc)
bazel-out/host/bin/external/com_google_protobuf/protoc: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by bazel-out/host/bin/external/com_google_protobuf/protoc)
bazel-out/host/bin/external/com_google_protobuf/protoc: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by bazel-out/host/bin/external/com_google_protobuf/protoc)
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/chuanqiw/tensorflow/gitlab/private-tensorflow/tensorflow/lite/toco/python/BUILD:77:1 Action tensorflow/core/data/service/worker.grpc.pb.h failed (Exit 1)
INFO: Elapsed time: 996.555s, Critical Path: 102.83s
INFO: 8409 processes: 8409 local.
FAILED: Build did NOT complete successfully
```

**Comment by chuanqi129** [comment]
Hi @gadagashwini, it isn't a MKL specific issue, this failure also appeared in Eigen build. Sorry for the misleading. 
You also can reproduce it with below build command
`bazel build --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mavx512f --copt=-mavx512pf --copt=-mavx512cd --copt=-mavx512bw --copt=-mavx512dq -c opt //tensorflow/tools/pip_package:build_pip_package`

**Comment by chuanqi129** [comment]
Hi @angerson and @gadagashwini , may I know the status of this issue?

**Comment by gyshi** [comment]
@chuanqi129  i also meet this error, have you resolved it?

**Comment by chuanqi129** [comment]
Hi @gyshi , can't resolve it, just upgrade the system native GCC version

**Comment by chuanqi129** [comment]
Hi @gadagashwini this is not only a centos issue, but also for ubuntu

**Comment by gyshi** [comment]
> Hi @gyshi , can't resolve it, just upgrade the system native GCC version

thx, i will try it

**Comment by jakublipinski** [comment]
@gyshi you can also try this instruction: https://gist.github.com/jakublipinski/40ba68994fe0092600a05b0060e7d445

**Comment by Saduf2019** [comment]
@chuanqi129 
As we have the latest stable version 2.6.0, Can you try building TF 2.6.0 and let us know if this is still an issue.
