### ISSUE TITLE
Waymo dataset:  module 'tensorflow' has no attribute 'enable_eager_execution'

### ISSUE THREAD

**Issue by Viki250893** [tensorflow/tensorflow#38307]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I am replicating the waymo dataset tutorial code for understanding and learning 
- Using Notebook of Google COLAB (as New user to Google Colab)
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below):  2.1.0 (as installed by default in Google Colab)

**This is the line of code: (sharing since it is available for public view as well by google in it's tutorial)**

!pip3 install waymo-open-dataset
import os
import tensorflow as tf
import math
import numpy as np
import itertools

tf.enable_eager_execution()

from waymo_open_dataset.utils import range_image_utils
from waymo_open_dataset.utils import transform_utils
from waymo_open_dataset.utils import frame_utils
from waymo_open_dataset import dataset_pb2 as open_dataset

**Describe the current behavior**
**Error I get upon executing the above lines of code**

AttributeError                            Traceback (most recent call last)
<ipython-input-8-8d310d062fcf> in <module>()
      6 import itertools
      7 
----> 8 tf.enable_eager_execution()
      9 
     10 from waymo_open_dataset.utils import range_image_utils

AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'

**Comment by amahendrakar** [comment]
@Viki250893,
The line `tf.enable_eager_execution()` is used only in TensorFlow 1.x to enable eager execution.
 
From TensorFlow 2.x eager mode is enabled by default so you can comment of that line. Thanks!

**Comment by Viki250893** [comment]
Thank you, but upon commenting the line.

!pip3 install waymo-open-dataset
import os
import tensorflow as tf
import math
import numpy as np
import itertools

**#tf.enable_eager_execution()**

from waymo_open_dataset.utils import range_image_utils
from waymo_open_dataset.utils import transform_utils
from waymo_open_dataset.utils import frame_utils
from waymo_open_dataset import dataset_pb2 as open_dataset

**I get the following error**

AttributeError                            Traceback (most recent call last)
<ipython-input-3-4a0693fecef3> in <module>()
      8 #tf.enable_eager_execution()
      9 
---> 10 from waymo_open_dataset.utils import range_image_utils
     11 from waymo_open_dataset.utils import transform_utils
     12 from waymo_open_dataset.utils import frame_utils

/usr/local/lib/python3.6/dist-packages/waymo_open_dataset/utils/range_image_utils.py in <module>()
     57                           value,
     58                           shape,
---> 59                           pool_method=tf.unsorted_segment_max):
     60   """Similar as tf.scatter_nd but allows custom pool method.
     61 

AttributeError: module 'tensorflow' has no attribute 'unsorted_segment_max'

**Comment by amahendrakar** [comment]
@Viki250893,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here.

Also, please add ``` (i.e. three backticks) before and after your code to preserve the indentation and formatting. Thanks!

**Comment by amahendrakar** [comment]
You can also provide the link to the tutorial you are following.

**Comment by Viki250893** [comment]
https://colab.research.google.com/drive/1DMt8gRU19fT5uPWBOdfRi5RsuXyRqeMO#scrollTo=Ipl_UEDWgLrB

**Comment by amahendrakar** [comment]
@Viki250893,
I am unable to open the link you have provided as I do not have access to it.

Please go to File -> Save a copy as a GitHub Gist and share the link of the new gist created with us. Thanks!

**Comment by Viki250893** [comment]
https://colab.research.google.com/gist/Viki250893/40008cf236a25736d1cdefc7e0e403ea/untitled1.ipynb

**Comment by Viki250893** [comment]
@amahendrakar Can you please reply with possible solution. Thank you.

**Comment by Viki250893** [comment]
No update from the team. So closing the issue and reporting again.

**Comment by amahendrakar** [comment]
@Viki250893,
Could you please check if the tutorial you are following is intended to use with TF 1.x?

I was able to reproduce the issue with TF 2.x, however I'm able to run the code without any issues with TF 1.15.2. Please find the gist [here](https://colab.research.google.com/gist/amahendrakar/f532cd92dba6789a6f5e11df73c85f60/38307.ipynb). Thanks!

**Comment by Viki250893** [comment]
Thank you for the reply.  I have  a check and update you.

**Comment by Viki250893** [comment]
WAYMO/Author whoever it is, has updated the tutorial script with
**Updated script has tensorflow.compat version1.**
``` 
import tensorflow.compat.v1 as tf  
```

**but, when I reported it, (Previously it was )**
```
import tensorflow as tf
```
https://colab.research.google.com/gist/Viki250893/40008cf236a25736d1cdefc7e0e403ea/untitled1.ipynb#scrollTo=3etKdSB4gIeR

I'm not sure what's happening. 

I would like to understand the difference of it being compatible with updated "compat.v1". This is on importing the library, not the eager enabler.


Right now, it's working fine. 
Maybe you can share some clarity and may close the issue.

Thank you

**Comment by amahendrakar** [comment]
@Viki250893,
For information regarding compatibility modules please check [this](https://www.tensorflow.org/guide/upgrade#compatibility_modules) TensorFlow guide. [This guide](https://www.tensorflow.org/guide/migrate) to migrate TF 1.x code to TF 2.x would also be helpful.

Please feel free to close the issue if resolved. Thanks!

**Comment by Viki250893** [comment]
Thank you very much!!! @amahendrakar
