### ISSUE TITLE
How to get libhexagon_interface.so for non Android OS (e.g. arm linux)?

### ISSUE THREAD

**Issue by cjluo-nuro** [tensorflow/tensorflow#38302]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): 2.2-rc2
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Qualcomm 845 SOC

**Describe the problem**
Try to get hexagon delegate working on qualcomm 845 soc with arm linux environment. The official supported hexagon delegate only works on Android and the provided libhexagon_interface.so links to Android libraries like liblog.so etc. Could you provide a libhexagon_interface.so that supports pure arm linux? Or could you provide documentation how to build libhexagon_interface.so if I have hexagon sdk from qualcomm downloaded?

Thanks!

**Please provide the exact sequence of commands/steps when you ran into the problem**

**Comment by karimnosseir** [comment]
Hi @cjluo-nuro, 

Can you provide what toolchain do you need for building the delegate, so we make sure the provided libhexagon_interface.so is the same.
a bazel command for building the delegate.

Long term, we are working with QC to make sure we can put the code, currently we can't because of licensing.

Thanks

**Comment by cjluo-nuro** [comment]
Hi, Karim, I use clang-8 with ubuntu arm environment (GCC 7.3) to build the delegate. ubuntu arm does not have android libraries. For example, the available libraries the delegate binary linked to are:

 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-aarch64.so.1]

**Comment by cjluo-nuro** [comment]
Friendly ping @karimnosseir ?

**Comment by karimnosseir** [comment]
@cjluo-nuro 
Sorry for the delay, was trying to find a way for testing (wasn't successful yet).
Do you mind reaching privately with details on the hardware used, if you don't mind i want to send you a version to try.

Thanks

**Comment by cjluo-nuro** [comment]
Thanks @karimnosseir. Is this your LDAP?

**Comment by karimnosseir** [comment]
Yes

**Comment by cjluo-nuro** [comment]
Thanks just shoot you an email

**Comment by cjluo-nuro** [comment]
Received the lib from @karimnosseir and it works on my dev board.
