### ISSUE TITLE
How to limit GPU memory usage in java?

### ISSUE THREAD

**Issue by payne4handsome** [tensorflow/tensorflow#38303]
Hello everyone,
    In python, I can use bellow strategy to limit GPU memory usage.
```
 tf.config.experimental.set_memory_growth(gpu, True)
 tf.config.experimental.per_process_gpu_memory_fraction = 0.5
```
But how can I do this in java?
I training my model with python, then convert model to pb format, last I load pb model in java.
so I want limit GPU memory usage in java . I can't find any document about this.
Any suggestions will help me, thanks.

**Comment by payne4handsome** [comment]
@sanjoy  please help me

**Comment by sanjoy** [comment]
@payne4handsome sorry for the delay, was on leave.  I'm not familiar with the TF Java bindings but have you looked [here](https://www.tensorflow.org/api_docs/java/reference/org/tensorflow/EagerSession.Options#config(byte[]))?

**Comment by jimfcarroll** [comment]
Did you ever get an answer to this?

**Comment by rnett** [comment]
You'll have more luck making Java issues on [tensorflow/java](https://github.com/tensorflow/java) directly.  What you're looking for are the [`Session`](https://www.tensorflow.org/jvm/api_docs/java/org/tensorflow/Session#Session(org.tensorflow.Graph,%20org.tensorflow.proto.framework.ConfigProto)) and [`EagerSession`](https://www.tensorflow.org/jvm/api_docs/java/org/tensorflow/EagerSession#options()) factories that let you pass in a `ConfigProto` object.

**Comment by tilakrayal** [comment]
@payne4handsome,
GPU memory is allocated when loading a model with "SavedModelBundle.load(.)". Hence the GPUOptions have to be set before doing that. One can do this by using the "loader" from the **SavedModelBundle**
https://www.tensorflow.org/jvm/api_docs/java/org/tensorflow/proto/framework/GPUOptions
```

 GPUOptions gpu = ConfigProto.getDefaultInstance().getGpuOptions().toBuilder() //
          .setPerProcessGpuMemoryFraction(0.8) //
          .setAllowGrowth(true) //
          .build(); //

      ConfigProto configProto = ConfigProto.newBuilder(ConfigProto.getDefaultInstance()) //
          .setLogDevicePlacement(true) //
          .mergeGpuOptions(gpu) //
          .build(); //

      SavedModelBundle model = SavedModelBundle.loader(tensorflowModelPath).withConfigProto(configProto).load();
```
Also please take a look at this [comment](https://github.com/tensorflow/java/issues/443#issuecomment-1094286906) from the contributor for the similar issue. Thank you!
