### ISSUE TITLE
Build manylinux whl from source

### ISSUE THREAD

**Issue by zhuzilin** [tensorflow/tensorflow#38306]
**System information**
- OS Platform and Distribution:
centos
- TensorFlow installed from (source or binary):
source
- TensorFlow version:
1.15.0
- Python version:
3.6
- Bazel version (if compiling from source):
0.26
- GCC/Compiler version (if compiling from source):
7.4
- CUDA/cuDNN version:
10.0
- GPU model and memory:

**Describe the problem**
Is it possible to build a manylinux package from source using some extra flags? I'm in a environment where it is much easier to build in one enviroment and test in another. It would be really nice if I can build a manylinux pip whl from source.

**Comment by mihaimaruseac** [comment]
Our build scripts are [in the repo](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/ci_build/release).

By default, compiling the pip package should build the manylinux pip.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by sspintel** [comment]
> By default, compiling the pip package should build the manylinux pip.

@mihaimaruseac Do you mean, compiling from within one of the tensorflow devel docker images?
