### ISSUE TITLE
Tensorflow 2.1.0 build issue 

### ISSUE THREAD

**Issue by npandey2385** [tensorflow/tensorflow#38308]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution : Linux , RHEL6
- TensorFlow installed from (source or binary):  Source
- TensorFlow version: 2.1.0
- Python version: 3.6.1
- Bazel version (if compiling from source): 0.28.1
- GCC/Compiler version (if compiling from source): 6.3.0

**Describe the problem**

/tensorflow/tensorflow/compiler/tf2xla/cc/BUILD:8:1: Linking of rule '//tensorflow/compiler/tf2xla/cc:ops/xla_ops_gen_cc' failed (Exit 1) bazel-out/host/bin/external/com_google_absl/absl/time/_objs/time/clock.o:clock.cc:function absl::GetCurrentTimeNanosSlowPath(): error: undefined reference to 'clock_gettime'
bazel-out/host/bin/tensorflow/core/platform/_objs/env_time_impl/env_time.o:env_time.cc:function tensorflow::(anonymous namespace)::PosixEnvTime::NowNanos() const: error: undefined reference to 'clock_gettime'
bazel-out/host/bin/external/com_google_absl/absl/base/_objs/base/sysinfo.o:sysinfo.cc:function absl::base_internal::ReadMonotonicClockNanos(): error: undefined reference to 'clock_gettime'
collect2: error: ld returned 1 exit status Target //tensorflow:libtensorflow_cc.so failed to build
INFO: Elapsed time: 5992.496s, Critical Path: 85.82s
INFO: 3149 processes: 3149 local.
FAILED: Build did NOT complete successfully

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel build --linkopt='-lrt' --verbose_failures --config=monolithic -c opt //tensorflow:libtensorflow_cc.so

**Comment by ravikyram** [comment]
@npandey2385 

Can you downgrade bazel version to 0.27.1 and check. Please, find the [tested builded configurations](https://www.tensorflow.org/install/source#cpu) from here.Also, refer #35623 and see if it helps you. Thanks!

**Comment by npandey2385** [comment]
I was able to build it with bazel 0.28.1 after apllying these two changes.

1- https://github.com/Flamefire/tensorflow/commit/1751e3c8de7a3e2a69dd22a6062aec7d2c7709ef
2-
Add -lrt as red line as follows:


        "//conditions:default": [
            "-z defs",
            "-s",
            "-Wl,--version-script",  #  This line must be directly followed by LINKER_VERSION_SCRIPT
            LINKER_VERSION_SCRIPT,
        ],
to
        "//conditions:default": [
            "-lrt",
            "-z defs",
            "-s",
            "-Wl,--version-script",  #  This line must be directly followed by LINKER_VERSION_SCRIPT
            LINKER_VERSION_SCRIPT,
        ],
in tensorflow/java/BUILD.

**Comment by ravikyram** [comment]
@npandey2385 

Glad to know it worked.Please close this thread if the issue was resolved. Thanks!
