### ISSUE TITLE
google colab  can not install TFX (taxi_pipeline_interactive.ipynb)

### ISSUE THREAD

**Issue by pradeepmishra11** [tensorflow/tensorflow#38310]
1.!pip install "tfx>=0.21.1,<0.22" "tensorflow>=2.1,<2.2" "tensorboard>=2.1,<2.2"
Install successfully
2.Restart run time
continuously shown busy
Please help me solved this problems

**Comment by gadagashwini** [comment]
@pradeepmishra11, Please provide the colab gist or Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks

**Comment by pradeepmishra11** [comment]
1,# TODO(ccy): remove "pyzmq==17.0.0" pin after bug in Colab is fixed.
!pip install -q "tfx>=0.21.1,<0.22" "tensorflow>=2.1,<2.2" "tensorboard>=2.1,<2.2" "pyzmq==17.0.0"
2.2.Restart run time
continuously shown busy
3.import os
import pprint
import tempfile
import urllib

import absl
import tensorflow as tf
import tensorflow_model_analysis as tfma
tf.get_logger().propagate = False
pp = pprint.PrettyPrinter()

import tfx
from tfx.components import CsvExampleGen
from tfx.components import Evaluator
from tfx.components import ExampleValidator
from tfx.components import Pusher
from tfx.components import ResolverNode
from tfx.components import SchemaGen
from tfx.components import StatisticsGen
from tfx.components import Trainer
from tfx.components import Transform
from tfx.dsl.experimental import latest_blessed_model_resolver
from tfx.orchestration import metadata
from tfx.orchestration import pipeline
from tfx.orchestration.experimental.interactive.interactive_context import InteractiveContext
from tfx.proto import pusher_pb2
from tfx.proto import trainer_pb2
from tfx.proto.evaluator_pb2 import SingleSlicingSpec
from tfx.utils.dsl_utils import external_input
from tfx.types import Channel
from tfx.types.standard_artifacts import Model
from tfx.types.standard_artifacts import ModelBlessing

%load_ext tfx.orchestration.experimental.interactive.notebook_extensions.skip

**Comment by gadagashwini** [comment]
@pradeepmishra11 , This issue is not related to Tensorflow. Can you raise this issue in TFX repository. Thanks

**Comment by Saduf2019** [comment]
@pradeepmishra11 ,
as updated above please create this issue in tfx
