### ISSUE TITLE
Keras model compiled with custom loss raises "object has no attribute '__name__'" error.

### ISSUE THREAD

**Issue by GPhilo** [tensorflow/tensorflow#38319]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device:
- TensorFlow installed from (source or
binary): binary
- TensorFlow version (use command below): v2.2.0-rc1-34-ge6e5d6df2a 2.2.0-rc2
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: 10.1, 7.6
- GPU model and memory: RTX 2080 Ti

**Describe the current behavior**
When trying to train a keras model compiled with a custom loss wrapped in a functools.partial, `model.fit` raises the following exception (full traceback is below):

```
/home/slr/anaconda3/envs/tf_rc/lib/python3.7/site-packages/tensorflow/python/keras/engine/compile_utils.py:261 _get_loss_object
        loss_name = loss.__name__

    AttributeError: 'functools.partial' object has no attribute '__name__'
```

If, on the other hand, the loss is passed as lambda, the function executes as expected.

**Standalone code to reproduce the issue** 

```
from tensorflow import keras
import tensorflow as tf
import numpy as np
from tensorflow.keras.datasets import mnist
from functools import partial

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train[...,None] / 255 - 1
x_test = x_test[...,None] / 255 - 1
y_train = keras.utils.to_categorical(y_train)
y_test = keras.utils.to_categorical(y_test)
model = keras.models.Sequential(
  [
    keras.layers.Conv2D(6, (3,3), activation='relu'),
    keras.layers.AveragePooling2D(),
    keras.layers.Conv2D(16, (3,3), activation='relu'),
    keras.layers.AveragePooling2D(),
    keras.layers.Flatten(),
    keras.layers.Dense(units=120, activation='relu'),
    keras.layers.Dense(units=84, activation='relu'),
    keras.layers.Dense(units=10, activation='softmax')
  ]
)

def dummy_loss(y,y2,a):
  return y+y2

model.compile(
  loss=partial(dummy_loss, a=2),
  #loss=lambda v1, v2 : dummy_loss(v1,v2,4),
  optimizer=keras.optimizers.Adam(), metrics={'output_1':'accuracy'})
model.train_on_batch(x_train[:2,...], y_train[:2,...]) # error here
```

**Other info / logs** 

The error seems to come from [this line](https://github.com/tensorflow/tensorflow/blob/33c47b42e04d11622a01ea279ad26e7c3c02a687/tensorflow/python/keras/engine/compile_utils.py#L261), which assumes the existence of an attribute `__name__` on any object passed by the user. The example with lambda works because lambdas have a default `__name__` value `<lambda>`, while `partial`s (and generic callables) do not.

Full traceback of the exception:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/slr/anaconda3/envs/tf_rc/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1285, in train_on_batch
    logs = train_function(iterator)
  File "/home/slr/anaconda3/envs/tf_rc/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/slr/anaconda3/envs/tf_rc/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 627, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/slr/anaconda3/envs/tf_rc/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 506, in _initialize
    *args, **kwds))
  File "/home/slr/anaconda3/envs/tf_rc/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/slr/anaconda3/envs/tf_rc/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/slr/anaconda3/envs/tf_rc/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/slr/anaconda3/envs/tf_rc/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/slr/anaconda3/envs/tf_rc/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/slr/anaconda3/envs/tf_rc/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    /home/slr/anaconda3/envs/tf_rc/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:505 train_function  *
        outputs = self.distribute_strategy.run(
    /home/slr/anaconda3/envs/tf_rc/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/slr/anaconda3/envs/tf_rc/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/slr/anaconda3/envs/tf_rc/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    /home/slr/anaconda3/envs/tf_rc/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:467 train_step  **
        y, y_pred, sample_weight, regularization_losses=self.losses)
    /home/slr/anaconda3/envs/tf_rc/lib/python3.7/site-packages/tensorflow/python/keras/engine/compile_utils.py:187 __call__
        self._build(y_pred)
    /home/slr/anaconda3/envs/tf_rc/lib/python3.7/site-packages/tensorflow/python/keras/engine/compile_utils.py:140 _build
        self._losses = nest.map_structure(self._get_loss_object, self._losses)
    /home/slr/anaconda3/envs/tf_rc/lib/python3.7/site-packages/tensorflow/python/util/nest.py:617 map_structure
        structure[0], [func(*x) for x in entries],
    /home/slr/anaconda3/envs/tf_rc/lib/python3.7/site-packages/tensorflow/python/util/nest.py:617 <listcomp>
        structure[0], [func(*x) for x in entries],
    /home/slr/anaconda3/envs/tf_rc/lib/python3.7/site-packages/tensorflow/python/keras/engine/compile_utils.py:261 _get_loss_object
        loss_name = loss.__name__

    AttributeError: 'functools.partial' object has no attribute '__name__'
```

**Comment by khimraj** [comment]
@GPhilo, I think you want to use custom loss with additional attribute. To define such type of loss you have to define loss function like this.
```
def dummy_loss(a=2):
    def lossFunction(y,y2):    
        return y+y2
    return lossFunction
```
Link of full code is [here](https://gist.github.com/khimraj/d4eced88749f5a51b67130e29ca37ecd).

**Comment by GPhilo** [comment]
@khimraj Thanks for the fast reply.
How is this different from using a `partial` or a functor object?

**Comment by gadagashwini** [comment]
Was able to replicate the issue with Tf 2.2.rc2.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/5e7b66ff475cc270ecacb0b73c79c3e3/untitled496.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment]
@GPhilo I have updated custom_loss function. After updating the custom_loss, code runs without any issue. Can you please check and let us know whether it resolved for you or not. [Here](https://colab.research.google.com/gist/jvishnuvardhan/790cd2b42ff6c2b2d9bc5c3ff4b52752/untitled68.ipynb) is the gist for you. Thanks!

**Comment by GPhilo** [comment]
@jvishnuvardhan The rewritten custom_loss indeed works, however according to the documentation of [`tf.keras.Model.compile`](https://www.tensorflow.org/api_docs/python/tf/keras/Model?version=nightly#compile) (both nightly and stable versions), `loss` should accept "any callable with the signature loss = fn(y_true, y_pred)". The line linked in the issue "other info" section effectively goes against the documentation, restricting valid values of the `loss` parameter to objects with a `__name__` attribute.

**Comment by madan-ram** [comment]
Hi, I am also facing a similar issue, below is my code 

code to reproduce the issue


    import numpy as np
    import matplotlib.pyplot as plt
    import tensorflow.keras.backend as K
    import tensorflow as tf
    from sklearn import metrics as skm
    import json
    from utils.training import focal_loss

    class FocalLoss(object):
        def __init__(self, num_class, num_sub_catg_class, batch_size, input_shape, lambda_conf=100.0, lambda_offsets=1.0, class_weights=1.0):
            self.batch_size = batch_size
            self.num_class = num_class
            self.num_sub_catg_class = num_sub_catg_class
            self.lambda_conf = lambda_conf
            self.lambda_offsets = lambda_offsets
            self.class_weights = class_weights
            self.num_rows, self.num_cols = input_shape[:2]

        def __call__(self, y_true, y_pred, sample_weight=None):
            
            num_rows, num_cols = self.num_rows, self.num_cols
            self.class_mask_tensor, self.class_sub_catg_mask_tensor = 1.0, 1.0
            if sample_weight is not None:
                print("Sample weight provided")
                sample_weight = K.cast(sample_weight, K.floatx())
                self.class_mask_tensor = sample_weight[:, :num_rows*num_cols]
                self.class_sub_catg_mask_tensor = sample_weight[:, num_rows*num_cols:2*num_rows*num_cols]

            class_y_true = y_true[:, :, :, :self.num_class]
            sub_catg_class_y_true = y_true[:, :, :, self.num_class:self.num_class+self.num_sub_catg_class]

            class_y_pred = y_pred[:, :, :, :self.num_class]
            sub_catg_class_y_pred = y_pred[:, :, :, self.num_class:self.num_class+self.num_sub_catg_class]

            class_y_true = tf.reshape(class_y_true, tf.stack([self.batch_size, num_rows*num_cols, self.num_class]))
            class_y_pred = tf.reshape(class_y_pred, tf.stack([self.batch_size, num_rows*num_cols, self.num_class]))
            class_loss = focal_loss(class_y_true, class_y_pred, mask=self.class_mask_tensor)

            sub_catg_class_y_true = tf.reshape(sub_catg_class_y_true, tf.stack([self.batch_size, num_rows*num_cols, self.num_sub_catg_class]))
            sub_catg_class_y_pred = tf.reshape(sub_catg_class_y_pred, tf.stack([self.batch_size, num_rows*num_cols, self.num_sub_catg_class]))
            sub_catg_class_loss = focal_loss(sub_catg_class_y_true, sub_catg_class_y_pred, mask=self.class_sub_catg_mask_tensor)

            class_loss = tf.reduce_mean(input_tensor=tf.squeeze(class_loss))
            sub_catg_class_loss = tf.reduce_mean(input_tensor=tf.squeeze(sub_catg_class_loss))
            total_loss = class_loss+sub_catg_class_loss
            
            return total_loss


my error:
```
/lib/python3.7/site-packages/tensorflow/python/keras/engine/compile_utils.py:266 _get_loss_object
        loss_name = loss.__name__

    AttributeError: 'FocalLoss' object has no attribute '__name__'
```

**Comment by csantosbh** [comment]
I can also reproduce this issue even when using a custom loss class that inherits from tf.Module.

The [documentation on custom losses](https://keras.io/api/losses/) state the following:

> Any callable with the signature loss_fn(y_true, y_pred) that returns an array of losses (one of sample in the input batch) can be passed to compile() as a loss

So perhaps it should be updated instead?

**Comment by AlexandreBourrieau** [comment]
Got hte same error

**Comment by jvishnuvardhan** [comment]
@GPhilo Looks like this was resolved. I have check with `tf-nightly` and I cannot reproduce the issue. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/a501e181c0dfea612d22b8ba71f0ed4d/untitled496.ipynb).

Can you verify once and close the issue if this was resolved for you. Thanks!

**Comment by jvishnuvardhan** [comment]
@AlexandreBourrieau Can you please open a new issue with a simple standalone code to reproduce the issue? Thanks!

**Comment by AlexandreBourrieau** [comment]
As mentionned by madan-ram, I use the solution he say : "My solution - adding and setting reduction, and name parameter worked. Inherit tf.keras.losses.Loss class." It works for me now.

**Comment by GPhilo** [comment]
@jvishnuvardhan Thanks, I believe this has indeed been fixed, I'll close this issue.
