### ISSUE TITLE
Loading a quantized TFlite model fails when allocating tensors

### ISSUE THREAD

**Issue by moberweger** [tensorflow/tensorflow#38311]
**System information** 
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 18.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **2.2.0-dev20200407**
- Python version: **3.6** / **3.8**
- Bazel version (if compiling from source): **N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **N/A**
- GPU model and memory: **N/A**

**Describe the current behavior**
Loading a `tf.keras` model to tflite causes an error when trying to allocate the tensors for inference. The error is:
`RuntimeError: tensorflow/lite/kernels/conv.cc:337 bias->type != kTfLiteInt32 (9 != 2)Node number 1 (CONV_2D) failed to prepare.`

**Describe the expected behavior**
The exported model should load without error. Inference with the same model in tensorflow is working.

**Standalone code to reproduce the issue** 
Colab gist reproducing the error can be found [here](https://colab.research.google.com/gist/moberweger/d75235cd637c0689e0984cfb3a388144/untitled0.ipynb) Slight modifications to the network structure (ie removing random layers) make the error go, but without any understandable scheme. 

**Other info / logs** 
```
RuntimeError                              Traceback (most recent call last)

<ipython-input-2-6b478363f7a3> in <module>()
     68     interpreter = tf.lite.Interpreter(model_path="model.tflite")
     69     input_details = interpreter.get_input_details()
---> 70     interpreter.allocate_tensors()
     71     print("DONE")

/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter.py in allocate_tensors(self)
    241   def allocate_tensors(self):
    242     self._ensure_safe()
--> 243     return self._interpreter.AllocateTensors()
    244 
    245   def _safe_to_run(self):

RuntimeError: tensorflow/lite/kernels/conv.cc:337 bias->type != kTfLiteInt32 (9 != 2)Node number 1 (CONV_2D) failed to prepare.
```

**Comment by amahendrakar** [comment]
@moberweger,
I am unable to open the Colab link you have provided as I do not have access to it.

Please go to File -> Save a copy as a GitHub Gist and share the link of the new gist created with us. Thanks!

**Comment by moberweger** [comment]
@amahendrakar Thanks for the notice. I updated the original issue with the new [link](https://colab.research.google.com/gist/moberweger/d75235cd637c0689e0984cfb3a388144/untitled0.ipynb)

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF-nightly](https://colab.research.google.com/gist/amahendrakar/594b38f7a23dc304debc2868a32b9d0a/38311-tf-nightly.ipynb) i.e. v2.2.0.dev20200410.

On running the above code with [TF v2.2.0rc2](https://colab.research.google.com/gist/amahendrakar/1353339ab5e6940f70a9697f418d614d/38311-2-2.ipynb#scrollTo=BfzADgjtSfGs), facing an error stating `AttributeError: 'TFLiteConverterV2' object has no attribute 'experimental_new_quantizer'`

Please find the attached gist. Thanks!

**Comment by rajansaini691** [comment]
Hello, and thank you so much for your time! Unfortunately, we are running into the exact same issue. Has there been a workaround/fix yet?

**Comment by ravikyram** [comment]
I have tried in colab with TF nightly version(`2.4.0-dev20200807`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/d9b9320804eb12c0e7ba55f9a1775e42/untitled229.ipynb).Thanks!

**Comment by tromedlov22** [comment]
Facing the same issue in both TF 2.3.0 and TF nightly version(tf-nightly-2.4.0.dev20200922) for my model involving Conv1D layers. Are Conv layers not yet supported for tflite or is it something else?

Is there a way to resolve this or do we need to wait till the next tf stable release (TF 2.4.0).
Please help.

**Comment by jvishnuvardhan** [comment]
@moberweger Looks like there was some in compatible `dtype` issue. The following is the error .

`RuntimeError: tensorflow/lite/kernels/conv.cc:350 bias->type != kTfLiteInt32 (INT8 != INT32)Node number 1 (CONV_2D) failed to prepare.`

When I remove `BatchNorm` layer, it worked without any error.  I remember there was some issue related to `BatchNorm` but it was long time back. Need to check that. Thanks!

**Comment by jvishnuvardhan** [comment]
@tromedlov22 Please share a simple standalone code to reproduce the issue. Thanks!
