### ISSUE TITLE
ABSL clock.h undeclared identifier when building from source

### ISSUE THREAD

**Issue by joelloo** [tensorflow/tensorflow#38316]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 2.x
- Python version: 3.6
- Installed using virtualenv? pip? conda?: chocolatey
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): LLVM
- CUDA/cuDNN version: 10, 7
- GPU model and memory: Quadro M5000M, 8192MB

**Describe the problem**
Unable to build because of an undeclared identifier in clock.h file from absl. This appears to be an issue with the dependencies for tensorflow.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
When running the configure script, errors appeared for versions of Bazel < 2.0.0 and also > 2.0.0. Hence Bazel 2.0.0 was installed. The configuration step contains the following output:

```
WARNING: Running Bazel server needs to be killed, because the startup options are different.
You have bazel 2.0.0 installed.
Please specify the location of python. [Default is C:\Python36\python.exe]:


Found possible Python library paths:
  C:\Python36\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Python36\lib\site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Found CUDA 10.0 in:
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/include
Found cuDNN 7 in:
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/include


Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 3.5,7.0]: 5.2


Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]: /arch:AVX2


Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: y
Eigen strong inline overridden.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v2             # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=nonccl         # Disable NVIDIA NCCL support.
```

Subsequently, build of the C++ API was attempted with `bazel build --config=opt --config=cuda //tensorflow:libtensorflow_cc.so`. However, this yielded the following error:

```
.\tensorflow/core/platform/env.h(368): warning: overloaded virtual function "tensorflow::Env::RegisterFileSystem" is only partially overridden in class "tensorflow::EnvWrapper"

external/com_google_absl\absl/types/optional.h(428): warning: expression has no effect
          detected during instantiation of "const T &absl::lts_2020_02_25::optional<T>::operator*() const & [with T=stream_executor::dnn::AlgorithmDesc]"
.\tensorflow/stream_executor/dnn.h(804): here

external/com_google_absl\absl/types/optional.h(428): warning: expression has no effect
          detected during instantiation of "const T &absl::lts_2020_02_25::optional<T>::operator*() const & [with T=size_t]"
.\tensorflow/stream_executor/dnn.h(858): here

external/com_google_absl\absl/time/clock.h(70): error C2065: 'Duration': undeclared identifier
external/com_google_absl\absl/time/clock.h(70): error C2146: syntax error: missing ')' before identifier 'duration'
external/com_google_absl\absl/time/clock.h(70): error C2143: syntax error: missing ';' before '{'
external/com_google_absl\absl/time/clock.h(70): error C2447: '{': missing function header (old-style formal list?)
Target //tensorflow:libtensorflow_cc.so failed to build
INFO: Elapsed time: 1231.090s, Critical Path: 124.55s
INFO: 1539 processes: 1539 local.
FAILED: Build did NOT complete successfully
```

Some suggestions from other posts have been to change the version of Bazel. However, based on the error messages received, it appears that only Bazel 2.0.0 is suitable. Are there any suggestions on how to address this issue?

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by joelloo** [comment]
Did not resolve this issue fully. I reverted to a previously tested build process, using TF 1.13.0 and building with Bazel 0.19.2. This build worked for me.

**Comment by KangolHsu** [comment]
same problem 
build tf2.3.0 in windows10

**Comment by amahendrakar** [comment]
> same problem
> build tf2.3.0 in windows10

@KangolHsu 
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
