### ISSUE TITLE
install_tensorflow() error: Collecting package metadata (current_repodata.json): ...working... failed

### ISSUE THREAD

**Issue by HongHe0123** [tensorflow/tensorflow#38315]
**System information**
- Windows 10 Pro:
- TensorFlow installed from (source or binary): use install_tensorflow() in r
- TensorFlow version:
- Python version: Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]:: Anaconda
- Installed using virtualenv? pip? conda?: in r version 3.6.0 
- GPU model and memory: 
Intel(R) HD Graphics 620, 
total available graphics memory: 8259 MB

**Describe the problem**
no able to successfully install tensorflow in r. Have tried various ways, it always shows error as below. We will have training tomorrow. 15 out 18 are not able to install and have the similar errors as me. Thanks for your help!

**Provide the exact sequence of commands / steps that you executed before running into the problem**
![Untitled](https://user-images.githubusercontent.com/46570223/78681144-f7ca5b80-78b1-11ea-8596-5598b13086b0.png)

**Comment by gadagashwini** [comment]
@HongHe0123, Follow the steps mentioned [here](https://tensorflow.rstudio.com/installation/). Thanks!

**Comment by HongHe0123** [comment]
The company blocked the website. Now the problem is solved. Thanks!

**Comment by mihaimaruseac** [comment]
Closing as resolved.
