### ISSUE TITLE
Performance issue with cross compiled benchmark_model and label_img

### ISSUE THREAD

**Issue by jlz3008** [tensorflow/tensorflow#38324]
**System information** 
- OS Platform and Distribution 
**Host** : Linux  4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
**Target**: Linux ubuntu 5.3.0-1019-raspberry4 #21-Ubuntu SMP Mon Feb 17 14:05:03 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

- Mobile device : Raspberry Pi 4
The performance issue happens on mobile device:   Raspberry Pi 4

- TensorFlow installed from: source, commit 9d2bdd0b244c759ca54c6f10f58c069ec2200452
follow the instructions in https://www.tensorflow.org/lite/guide/build_arm64 

- GCC/Compiler version 
**Host**: gcc version 7.5.0 (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) Target: aarch64-linux-gnu
**Target:** gcc version 9.2.1 20191008 (Ubuntu 9.2.1-9ubuntu2) 

**Describe the current behavior**

When I run the benchmark_model or label_img applications,the inference time is longer in cross compiled application than native compile applications.

Surprisingly, the time is greater in float point models. In quantized models there is not much difference.

Compiler issue ??

Benchmark | model | Native compiled | Cross compiled
-- | -- | -- | --
benchmark_model | mobilenet v1 | 161564 | 195817
benchmark_model | mobilenet v1 quant | 95125.1 | 99856.7
label_img | mobilenet v1 | 72.938 ms | 217.212 ms
label_img | mobilenet v1 quant | 30.668 ms | 31.723 ms

**Comment by jlz3008** [comment]
Using the docker devel image I get the same results as cross compiling in Host

**Comment by hajuho** [comment]
Do you have the same issue whent built with ./tensorflow/lite/tools/make/build_rpi_lib.sh as guided at https://www.tensorflow.org/lite/guide/build_rpi?

**Comment by hajuho** [comment]
Terry,
do you have any idea on this issue?

**Comment by jlz3008** [comment]
@hajuho Raspbian is a 32 bit platform.  https://www.tensorflow.org/lite/guide/build_rpi is a recipe to build over armv7/6 32 bit platform. I am using using Ubuntu 64 bits over armv8-a (aarch64) platform, Raspberry Pi 4. So, I am using https://www.tensorflow.org/lite/guide/build_arm64 recipe.

I am using the same recipe (https://www.tensorflow.org/lite/guide/build_arm64) to build natively in RP4 and cross compile in a x86_64 Host.

**Comment by terryheo** [comment]
This is interesting.
@jlz3008 which OS are you using for RPI4? I wonder which toolchain was used for native build.

**Comment by jlz3008** [comment]
@terryheo . The OS in RPI4 is a ubuntu 64 bits. Please, see the first comment.
I find that Tensorflow lite in 64 bits OS (ubuntu) have better preformance that 32 bits OS (raspbian)

**Comment by terryheo** [comment]
Did you use images from https://ubuntu.com/download/raspberry-pi ?

**Comment by jlz3008** [comment]
Yes. @terryheo  Exactly ubuntu-19.10.1-preinstalled-server-arm64+raspi3.img.xz
But the problem is not in the target OS. The problem is that generated code from crosscompile has worse performance than native compile. So, I guess the problem is in crosscompile flags or generated code, not in target OS or target native toolchain.

**Comment by terryheo** [comment]
Thanks for the confirmation. I'll check what caused the difference.

**Comment by kumariko** [comment]
@jlz3008 Could you please let us know if you still need help on this issue ?
