### ISSUE TITLE
TFLite Failed to build gpu delegate on Linux

### ISSUE THREAD

**Issue by matthewn4444** [tensorflow/tensorflow#38336]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):18.04 LTS
- TensorFlow installed from (source or binary): source
- TensorFlow version: v2.1
- Python version: 2.7
- Installed using virtualenv? pip? conda?: docker (linux env)
- Bazel version (if compiling from source): 0.29.1
- GCC/Compiler version (if compiling from source):clang version 7.0.0-3~ubuntu0.18.04.1

**Describe the problem**
I am trying to build tensorflow lite gpu delegate on linux (docker inside imac) but I cannot build using bazel when compiling the gl_delegate. This also happens on v2.2.0rc2 but using bazel 2.0.0 and modifying the configure file to prevent errors from running.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. clone tensorflow
2. checkout v2.1.0 branch
3. install all the python, pip dependenies
4. apt get install `mesa-common-dev libgl1-mesa-dev libgles2-mesa-dev ocl-icd-opencl-dev`
5. run ./configure, press enter to each (so use all default commands), python points to /usr/bin/python etc
6. install `bazel 0.29.1`
7. Run `bazel build tensorflow/lite/delegates/gpu:gl_delegate`

Then it fails with 

```
In file included from tensorflow/lite/delegates/gpu/gl/egl_context.cc:21:
./tensorflow/lite/delegates/gpu/gl/gl_call.h:60:29: error: no viable conversion from returned value of type 'tflite::gpu::Status' to function return type 'int'
    if (status.ok()) return OkStatus();
                            ^~~~~~~~~~
./tensorflow/lite/delegates/gpu/gl/gl_call.h:73:29: error: no viable conversion from returned value of type 'tflite::gpu::Status' to function return type 'int'
    if (status.ok()) return OkStatus();
                            ^~~~~~~~~~
tensorflow/lite/delegates/gpu/gl/egl_context.cc:33:3: error: member reference base type 'const int' is not a structure or union
  RETURN_IF_ERROR(GetOpenGlErrors());
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./tensorflow/lite/delegates/gpu/common/status.h:68:17: note: expanded from macro 'RETURN_IF_ERROR'
    if (!status2.ok()) return status2; \
         ~~~~~~~^~~
```
And a lot more of this. 
Not sure why it tries to convert the Status into an int. Maybe i am targeting the wrong build target?

**Comment by matthewn4444** [comment]
Have there been any updates on this?

**Comment by Namburger** [comment]
I'm getting the exact same thing :(
I mean from tensorflow's documentation, I guess it's just not supported yet since it's only for android, but it would be nice.

**Comment by zldrobit** [comment]
I have sucessfully built gpu delagate on linux using:
```
bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 tensorflow/lite/delegates/gpu:gl_delegate
```
https://github.com/tensorflow/tensorflow/issues/28830#issuecomment-619179751

**Comment by matthewn4444** [comment]
Can confirm that the command works. Thanks.

I also needed to install a few packages: 
libegl1-mesa-dev
libgles2-mesa-dev

**Comment by Saduf2019** [comment]
@matthewn4444 
please update if this is still an issue.

**Comment by matthewn4444** [comment]
I will take a look and answer soon

**Comment by matthewn4444** [comment]
I was able to build the delegate using the command before

`bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 tensorflow/lite/delegates/gpu:gl_delegate`

On ubuntu using tf 2.3

and was able to build the delegate with 

```
#include <tensorflow/lite/delegates/gpu/delegate.h>

auto  _gpuDelegate = tflite::Interpreter::TfLiteDelegatePtr(TfLiteGpuDelegateV2Create(nullptr),
                                                          &TfLiteGpuDelegateV2Delete);
    if (!_gpuDelegate) {
        return error
    }
    if (_interpreter->ModifyGraphWithDelegate(_gpuDelegate.get()) != kTfLiteOk) {
            return error
    }
return no_error

```

After running on GPU it fails to run because std was not included, I assume the delegate didn't build correctly?

**Comment by sanatmpa1** [comment]
@matthewn4444,

Can you try updating to latest stable version of tensorflow `2.6.0` and let us know if the issue still persists? Thanks!
