### ISSUE TITLE
mobilenet_v2_140_224/classification: Cannot copy between a TensorFlowLite tensor with shape [1, 120] and a Java object with shape [1, 10, 4]

### ISSUE THREAD

**Issue by wilerjrxd** [tensorflow/tensorflow#38337]
**System information** 
- Windows 10 10.0.18362 Build 18362
- TensorFlow 2.2.0 installed from pip 
- Python v3.8.2

**Describe the current behavior**
I used the make_image_classifier (https://github.com/tensorflow/hub/tree/master/tensorflow_hub/tools/make_image_classifier) to generate the TFLITE model based on images available on http://vision.stanford.edu/aditya86/ImageNetDogs/:
```
make_image_classifier --image_dir images \
--tfhub_module https://tfhub.dev/google/imagenet/mobilenet_v2_140_224/classification/2 \
--image_size 224 \
--saved_model_dir models \
--labels_output_file output/labels.txt \
--tflite_output_file output/retrained.tflite
```

Then I copied the .tflite file to my Android project assets folder and tried to execute the app, but it crashed with the following error:

 ```
Process: org.tensorflow.lite.examples.detection, PID: 9525
    java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 120] and a Java object with shape [1, 10, 4].
        at org.tensorflow.lite.Tensor.throwIfShapeIsIncompatible(Tensor.java:412)
        at org.tensorflow.lite.Tensor.throwIfDataIsIncompatible(Tensor.java:369)
        at org.tensorflow.lite.Tensor.copyTo(Tensor.java:247)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:166)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:314)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:195)
        at org.tensorflow.lite.examples.detection.DetectorActivity$2.run(DetectorActivity.java:181)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```
I looked into almost similar issues, but none of them had the TensorFlowLite with a shape based on two parameters (i.e. [1, 120]) while having the Java object with a shape based on three (i.e. [1, 10, 4]).
  
make_image_classifier: https://github.com/tensorflow/hub/tree/master/tensorflow_hub/tools/make_image_classifier

**Describe the expected behavior**
The app should start with no problems and detect/classify objects based on the provided TFLITE model.

**Standalone code to reproduce the issue** 
https://github.com/LavitzBr/object_detection

**Comment by xunkai55** [comment]
It looks like you're copying an image classification model to the object detection app, and that leads to the incompability issue.

**Comment by jvishnuvardhan** [comment]
@LavitzBr 1. Is this still an issue for you? 
2.Did you check @xunkai55 response? 
3.Can you please share a standalone code to reproduce the issue? Thanks!

**Comment by LavitzBr** [comment]
@xunkai55, I'm following the correct commands for the model to be compatible with the code that calls it in the app. Do you have a clue on why the model not being correctly generated?

**Comment by xunkai55** [comment]
@LavitzBr Based on the contents in the original post, it looks like you got an "Image Classification" model (mobilenet_v2_140_224) from TFHub. That model is used for predict the category of images. However, your app is the "Object Detection" app. An "image classification" model cannot be used for "object detection" without subtle modifications.

If you want an Image classification app, please check out https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android rather than the Object Detection app.

If you want an Object Detection app, you may want a "single-shot-detection" model, like "MobileNetV1-SSD" we used in the example app. https://tfhub.dev/tensorflow/lite-model/ssd_mobilenet_v1/1/default/1

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Comment by sushreebarsa** [comment]
@wilerjrxd Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!
