### ISSUE TITLE
tflite Interpreter causes iOS app to crash

### ISSUE THREAD

**Issue by ishaghodgaonkar** [tensorflow/tensorflow#38335]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  Following this tutorial for tflite with C++: https://www.tensorflow.org/lite/guide/inference

- OS Platform and Distribution: MacOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: iPhone XS Max
- TensorFlow installed from (binary): - TensorFlow version (use command below): 2.1.0
- Python version: - Bazel 
version (if compiling from source): bazel 1.1.0
- GCC/Compiler version (if compiling from
source): 4.2.1

**Describe the current behavior**

When using tflite with Mediapipe for hand tracking, building the interpreter causes the app to crash after being built and opened. 

**Steps to reproduce behavior**

1. Need to clone our project github repo: https://github.com/sne21star/mediapipe
2. Try building the iOS app from command line using this command: bazel build --config=ios_arm64 mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp
3. Download to iOS and try out app, will crash due to these lines in hand_gesture_recognition_calculator.cc

//  Build the interpreter
    tflite::ops::builtin::BuiltinOpResolver resolver;
    std::unique_ptr<tflite::Interpreter> interpreter;
    tflite::InterpreterBuilder(*model, resolver)(&interpreter);

Without these lines, app runs fine (same as their out of box hand-tracking example).

**Describe the expected behavior**

Building the desktop app runs fine and classifies the ASL letters, so expect it to work the same on iOS.

**Comment by yyoon** [comment]
Hi @ishaghodgaonkar.
Is this still on issue for you? I tried to follow your repro steps, but the `bazel build` command was failing on my side due to syntax errors in the `WORKSPACE` file in your repo. Looks like some merge conflicts were not correctly resolved in that file. Could you please take a look?
