### ISSUE TITLE
Update NCCL version to the latest release v2.6.4-1

### ISSUE THREAD

**Issue by artemry-nv** [tensorflow/tensorflow#38332]
**System information**
- TensorFlow version (you are using): master
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Could you please update NCCL used within TensorFlow building to the latest release v2.6.4-1: https://github.com/NVIDIA/nccl/releases/tag/v2.6.4-1

**Will this change the current api? How?** No

**Who will benefit with this feature?**
Needed to enable new NCCL features (in particular network collectives).

**Any Other info.**

**Comment by amahendrakar** [comment]
@artemry-nv,
Is this still an issue?

Please feel free to close the issue if resolved. Thanks!

**Comment by artemry-nv** [comment]
What is the current NCCL version used for TF building?
