### ISSUE TITLE
Cannot convert tf.math.conj Op in Keras model to tflite

### ISSUE THREAD

**Issue by JonathanDZiegler** [tensorflow/tensorflow#38348]
------------------------

### System information
- **OS Platform and Distribution**: Linux-4.19.0-8-amd64-x86_64-with-debian-10.3
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 2.2.0-dev20200406
- **Python version**: 3.7.6
- **CUDA/cuDNN version**: 10.0
- **GPU model and memory**: 4x GeForce RTX2080Ti, 12Gb

### Describe the problem
Unsupported Op tf.math.conj when converting keras model to tflite. Is there a workaround for this?

### Source code (MWE)
```python
import tensorflow as tf
from tensorflow.keras.layers import Input, Lambda
from tensorflow.keras.models import Model


if __name__ == '__main__':
    model_in = Input(shape=(128,1))


    fft = Lambda(lambda x: tf.signal.rfft(x), name='RFFT')
    sig_spec = fft(model_in)

    conjugate = Lambda(lambda x: tf.math.conj(x), name='conjugate')(sig_spec)
    correlation_spec = sig_spec * conjugate
    correlation = Lambda(lambda x: tf.signal.irfft(x), name='IRFFT')(correlation_spec)

    model = Model(inputs=model_in, outputs=correlation)

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.experimental_new_converter = True
    converter.target_spec.supported_ops = set([tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS])
    tflite_model = converter.convert()
```
### Error log
`<unknown>:0: error: failed while converting: 'main': Ops that need custom implementation (enabled via setting the -emit-custom-ops flag):
	tf.Conj {device = ""}
`

**Comment by amahendrakar** [comment]
@JonathanDZiegler,
Could you please try adding the below line to your code.
`converter.allow_custom_ops = True`

When I did, I was able to run the code without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/3dae3c7398f5f931814d1d47d45e7195/38348-2-2.ipynb#scrollTo=GOxQjNMrmnGv&line=11&uniqifier=1). Thanks!

**Comment by JonathanDZiegler** [comment]
@amahendrakar the error disappeared (in the minimal example above and also in the actual code), thank you very much! I was under the impression that setting `allow_custom_ops = True` required custom handlers to be written for the converter. I will test the converted model to see if the error disappeared or just the error message and report back asap.

**Comment by JonathanDZiegler** [comment]
As suspected, the issue is only displaced by this. Now the problem occurs when trying to use the model for inference. Tried writing a custom function for conj, but to no avail: the converter is unable to process `tf.complex`, `tf.math.real `and `tf.math.imag`.

**Comment by karimnosseir** [comment]
When you enable SELECT_TF_OPS the converter adds to the model the op as an a custom op to be consumed by TF(Select) delegate.
You will need to use the AAR that supports SELECT and it should work.
See instructions
https://www.tensorflow.org/lite/guide/ops_select
For running the converted model see this section https://www.tensorflow.org/lite/guide/ops_select#running_the_model

If you want to write a custom implementation for an existing TF op, then this is different than SELECT_TF
see https://www.tensorflow.org/lite/guide/ops_custom

**Comment by JonathanDZiegler** [comment]
Thank you for your reply. Sadly, the python implementation is still under active development. Hoping something will be available soon. Otherwise I will try the C++ implementation. If possible, I would leave this thread open and report back, as soon as any progress has been made?

**Comment by jvishnuvardhan** [comment]
@JonathanDZiegler Can you please check whether the issue was resolved in recent `tf-nightly`. I didn't see any error. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/30712fbf3caa8996fbc098455b4e184f/38348.ipynb). Thanks!

**Comment by JonathanDZiegler** [comment]
@jvishnuvardhan thanks for your reply! I tested it on the mwe and it seems to work. Interestingly, the base methods tf.complex, tf.math.real and tf.math.imag still don't work but tf.conj does. I'll get to testing the actual model next week and report back.

**Comment by jvishnuvardhan** [comment]
@JonathanDZiegler After verifying it, please close this issue. If there are any ops (not part of this model) that are not working, open a  new issue with a standalone code to reproduce the issue. Thanks!

**Comment by JonathanDZiegler** [comment]
@jvishnuvardhan I was able to convert the model without problems now, thank you very much! Running the converted model in python currently does not seem to be supported but that would be another issue.
