### ISSUE TITLE
Waymo dataset: module 'tensorflow' has no attribute 'enable_eager_execution'

### ISSUE THREAD

**Issue by Viki250893** [tensorflow/tensorflow#38347]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I am replicating the waymo dataset tutorial code for understanding and learning
- Using Notebook of Google COLAB (as New user to Google Colab)
- TensorFlow version (use command below): 2.1.0 (as installed by default in Google Colab)

**Describe the current behavior**

This is the line of code: (sharing since it is available for public view as well by google in it's tutorial)
``` 
!pip3 install waymo-open-dataset
import os
import tensorflow as tf
import math
import numpy as np
import itertools

tf.enable_eager_execution()

from waymo_open_dataset.utils import range_image_utils
from waymo_open_dataset.utils import transform_utils
from waymo_open_dataset.utils import frame_utils
from waymo_open_dataset import dataset_pb2 as open_dataset
```

**Error I get upon executing the above lines of code**
```
AttributeError Traceback (most recent call last)
in ()
6 import itertools
7
----> 8 tf.enable_eager_execution()
9
10 from waymo_open_dataset.utils import range_image_utils

AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'
```

Even Upon commenting the line " tf.enable_eager_execution()" - as tensor 2.x version doesn't need, a new error pops up.
```
!pip3 install waymo-open-dataset
import os
import tensorflow as tf
import math
import numpy as np
import itertools

#tf.enable_eager_execution()

from waymo_open_dataset.utils import range_image_utils
from waymo_open_dataset.utils import transform_utils
from waymo_open_dataset.utils import frame_utils
from waymo_open_dataset import dataset_pb2 as open_dataset

I get the following error

AttributeError Traceback (most recent call last)
in ()
8 #tf.enable_eager_execution()
9
---> 10 from waymo_open_dataset.utils import range_image_utils
11 from waymo_open_dataset.utils import transform_utils
12 from waymo_open_dataset.utils import frame_utils

/usr/local/lib/python3.6/dist-packages/waymo_open_dataset/utils/range_image_utils.py in ()
57 value,
58 shape,
---> 59 pool_method=tf.unsorted_segment_max):
60 """Similar as tf.scatter_nd but allows custom pool method.
61

AttributeError: module 'tensorflow' has no attribute 'unsorted_segment_max'

```

**Describe the expected behavior**
No error should be there.

**Standalone code to reproduce the issue**  
Link to Colab/Jupyter/any notebook.
https://colab.research.google.com/gist/Viki250893/40008cf236a25736d1cdefc7e0e403ea/untitled1.ipynb

**Comment by gadagashwini** [comment]
@Viki250893, 
In Tensorflow 2.1,use `tf.compat.v1.enable_eager_execution()` instead of `tf.enable_eager_execution()`. 
And this error AttributeError: module 'tensorflow' has no attribute 'unsorted_segment_max' is not related to Tensorflow. Thanks

**Comment by Viki250893** [comment]
I am not able to reproduce the error. I think it is a Bug. I tried running in a new Notebook without making change as per your comment. I request you to please check in backend.
Thank you.

**Comment by gadagashwini** [comment]
@Viki250893, Tensorflow 2.x has default eager enabled. To enable explicitly use `tf.compat.v1.enable_eager_execution()` which is same as 
import tensorflow.compat.v1 as tf  and tf.enable_eager_execution().

This error `AttributeError: module 'tensorflow' has no attribute 'unsorted_segment_max'` is outside the scope of Tensorflow. Thanks

**Comment by Viki250893** [comment]
Thank you very much for the support. !!
