### ISSUE TITLE
Generic opencl support by porting all cuda related parts to opencl

### ISSUE THREAD

**Issue by NKCSRzChen** [tensorflow/tensorflow#38342]
I wonder if it is possible to make **tensorflow support generic opencl devices (not just AMD Gpus) by porting cuda to opencl manually ?**
**What are the challenges here (besides the huge maintance costs)?** 
Can we use tensorflow without Eigen library (i.e. **all the kernels in Eigen are preproduced with opencl kernels**) so that it will overcome the fact that opencl doesn't support C++.
Maybe someone could help me figure them out, thanks :D

**Comment by sanjoy** [comment]
> What are the challenges here (besides the huge maintance costs)?

"Huge maintenance" costs" sounds like a pretty big challenge in itself. :)

All of what you're saying can be done, but we are unlikely to take such a large change to the TF repository unless it was very well motivated.

**Comment by sanjoy** [comment]
I don't see an action item for us here so closing the issue for now.
