### ISSUE TITLE
How to control the cpu core?

### ISSUE THREAD

**Issue by mingqizhang** [tensorflow/tensorflow#38340]
I use tf pipline to augment the training data then training the model, but it's useless to set the tf.ConfigProto(device_count={"CPU":10},
  inter_op_parallelism_threads=1,
  intra_op_parallelism_threads=1,), all cpu core work as follow;
![image](https://user-images.githubusercontent.com/28778038/78748612-0cd0e880-799f-11ea-8e61-02e30493d372.png)

I expect to limit the cpu core which can not influence other tasks.
work platform:
ubuntu 18.04
 tf-gpu-1.9
NVIDIA GTX1080ti

Anyone have the solution?

**Comment by saahiluppal** [comment]
Refer: <a href='https://github.com/tensorflow/tensorflow/issues/25446'>#25446</a>

**Comment by ravikyram** [comment]
@mingqizhang 
Any update on this issue please.Thanks!
