### ISSUE TITLE
cannot connect to https://www.tensorflow.org/

### ISSUE THREAD

**Issue by shartoo** [tensorflow/tensorflow#3834]
hi, i cannot connect to the home site of tensorflow for long. Can you fix this? My location is China, i can visit Google , tweet,facebook and so on,but no access to tensorflow ,Neither   can my friends do.

**Comment by tobegit3hub** [comment]
Not really an issue. I can access <https://www.tensorflow.org/> in China.

You should check your host file or configuration of proxy.

**Comment by shartoo** [comment]
When i ping www.tensorflow.org ,it responses like below
```
 Ping ghs-migration.l.google.com [74.125.203.214]
.....
losss 100%
```

**Comment by hholst80** [comment]
Sounds like a routing problem rather than an issue with *The Great Firewall*. Have you tried restarting both your computer and router?

**Comment by shartoo** [comment]
Yes, this problem last for about two months .during this period ,i have never gotten access to www.tensorflow.org.

**Comment by hholst80** [comment]
What is the result from a traceroute from your computer to www.tensorflow.org?

**Comment by shartoo** [comment]
Here is the output of my routing:

```
Tracing route to 11.1.0.1 over a maximum of 30 hops
   ---------------------------------------------------
1    12 ms    16 ms     1 ms  10.200.187.8
2    23 ms     5 ms     8 ms  101.81.0.1
3     5 ms     6 ms     7 ms  124.74.57.1
4     9 ms    22 ms     3 ms  101.95.41.129
5     9 ms     5 ms     7 ms  101.95.120.110
6     9 ms     7 ms    13 ms  202.97.35.154
7     *        *        *     request out of time。
8     *        *        *     request out of time。
9     *        *        *     request out of time。
0


```

**Comment by hholst80** [comment]
I am not an expert but it looks like your traffic is still left in mainland China (your Ping time should be much higher also as www.tensorflow.org is hosted in the USA). Contact either your ISP or CHINANET.

```
$ whois 202.97.35.154
% [whois.apnic.net]
% Whois data copyright terms    http://www.apnic.net/db/dbcopyright.html

% Information related to '202.97.32.0 - 202.97.63.255'

inetnum:        202.97.32.0 - 202.97.63.255
netname:        CHINANET-BB
descr:          CHINANET backbone network
descr:          Data Communication Division
descr:          China Telecom
country:        CN
admin-c:        CH93-AP
tech-c:         CH93-AP
mnt-by:         APNIC-HM
mnt-lower:      MAINT-CHINANET
status:         ALLOCATED PORTABLE
source:         APNIC
mnt-irt:        IRT-CHINANET-CN
changed:        hostmaster@ns.chinanet.cn.net 20000801
changed:        hm-changed@apnic.net 20041214

irt:            IRT-CHINANET-CN
address:        No.31 ,jingrong street,beijing
address:        100032
e-mail:         anti-spam@ns.chinanet.cn.net
abuse-mailbox:  anti-spam@ns.chinanet.cn.net
admin-c:        CH93-AP
tech-c:         CH93-AP
auth:           # Filtered
mnt-by:         MAINT-CHINANET
changed:        anti-spam@ns.chinanet.cn.net 20101115
source:         APNIC

person:         Chinanet Hostmaster
nic-hdl:        CH93-AP
e-mail:         anti-spam@ns.chinanet.cn.net
address:        No.31 ,jingrong street,beijing
address:        100032
phone:          +86-10-58501724
fax-no:         +86-10-58501724
country:        CN
changed:        dingsy@cndata.com 20070416
changed:        zhengzm@gsta.com 20140227
mnt-by:         MAINT-CHINANET
source:         APNIC

% This query was served by the APNIC Whois Service version 1.69.1-APNICv1r0 (UNDEFINED)

```

**Comment by zhudanhao** [comment]
it is caused by great firewall. however, It is not totally blocked and I can visit it occasionally. I suggest you to use vpn or proxy. 

发自我的 iPhone

**Comment by shartoo** [comment]
I don't understand why did it try to visit  ghs-migration.l.google.com first. To bypass  the GFW, i changed my hosts file,there are many name to ip map,but no item about tensorflow.

**Comment by hholst80** [comment]
Wait what? Tracing route to 11.1.0.1? That resolves to DoD.

**Comment by shartoo** [comment]
It's `ghs-migration.l.google.com [74.125.204.214] ` not `11.1.0.1` ,to transfer the content to english, i copy sth wrong from other site. 
All right ,it's not a bug of tensorflow, but sth annoying , some of my friends get the same problem.

**Comment by shartoo** [comment]
It seems `www.tensorflow.org`  had been blocked by GFW.  I can't understand the logic behind this!

**Comment by yaroslavvb** [comment]
I'm guessing the problem is that tensorflow.org resolves to "
ghs-migration.l.google.com" and google.com domains are blocked

**Comment by sherrym** [comment]
Unfortunately this might not be something we can easily resolve. Community contribution welcome. :)

**Comment by shartoo** [comment]
add this to the hosts file,can fixe this.

```
#TensorFlow start
64.233.188.121	www.tensorflow.org
#TensorFlow end
```

**Comment by eecrazy** [comment]
great, thanks to @shartoo

**Comment by Helloworld050664** [comment]
your IP address is on tensorflow's server blacklist go to

http://www.ipvoid.com

**Comment by youngxiao** [comment]
Thanks for your answer, @shartoo. It really works.

**Comment by chengshuyi** [comment]
@shartoo I type `64.233.188.121` in browser,but it cant be accessed.Does that way you supposed still could work or not?

**Comment by AlSnow** [comment]
thanks to @shartoo , it's worked.

**Comment by WangWenXuan940124** [comment]
that's really helpful, thanks to @shartoo

**Comment by fangpin** [comment]
It's worked. But it seems to be behind the official homepage which has the version 1.0

**Comment by Guitarja** [comment]
@chengshuyi Yes, it does.

**Comment by SiriusHsh** [comment]
@fangpin  Yes,I also found this question, how do you solve the problem？

**Comment by fangpin** [comment]
@SiriusHsh  I fount it's the VPN settings problem which cause this situation. For example, I use shadowsocks on mac, it will be all ok when I use the global mode instead of auto mode. So maybe it works for you too. By the way, I use shadowsocks and chrome with extension swithchyomega on ubuntu.

**Comment by gchen2101** [comment]
it works, thanks to @shartoo

**Comment by SiriusHsh** [comment]
amazing, when I use the global mode instead of auto mode, it shows the correct page.  I also use shadowsocks and Mac. thx, @fangpin

**Comment by iAInNet** [comment]
I think it's a proxy problem. You can export PAC file from some proxy tools such as SwitchyOmega. Then overwrite PAC file of shadowsocks.

**Comment by vaxin** [comment]
@fangpin @SiriusHsh 是的，那个PAC文件里只写了  ||tensorflow.org 加一个  .tensorflow.org 就好了

**Comment by dgl-prc** [comment]
when i add the host to my host file, i can get response when i ping www.tensorflow.org.
However, i still fail to access the web via browser.

`PING www.tensorflow.org (64.233.188.121): 56 data bytes
64 bytes from 64.233.188.121: icmp_seq=0 ttl=245 time=194.245 ms
64 bytes from 64.233.188.121: icmp_seq=1 ttl=245 time=198.178 ms`

**Comment by BirdeeChen** [comment]
I am using VPN, and can normally connect to google.com or youtube.com from China, but still can't connect to www.tensorflow.org from end May till now, don't know why

**Comment by codershangfeng** [comment]
@SiriusHsh it works! cool

**Comment by faxinwang** [comment]
> @SiriusHsh I fount it's the VPN settings problem which cause this situation. For example, I use shadowsocks on mac, it will be all ok when I use the global mode instead of auto mode. So maybe it works for you too. By the way, I use shadowsocks and chrome with extension swithchyomega on ubuntu.

that works for me too, on my old win7 desktop, thanks!!

**Comment by w1malik** [comment]
> @SiriusHsh I fount it's the VPN settings problem which cause this situation. For example, I use shadowsocks on mac, it will be all ok when I use the global mode instead of auto mode. So maybe it works for you too. By the way, I use shadowsocks and chrome with extension swithchyomega on ubuntu.

**Comment by w1malik** [comment]
@SiriusHsh Thanks dear same issue with me and I am also using shadowsocks on windows 10. By changing the configuration setting from PAC to Global, it solved my issue very thanks.

**Comment by hdliuyi** [comment]
> @SiriusHsh Thanks dear same issue with me and I am also using shadowsocks on windows 10. By changing the configuration setting from PAC to Global, it solved my issue very thanks.

Thank you! I get it!
