### ISSUE TITLE
The docker image provided to compile tensorflow custom ops is too big.

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [tensorflow/tensorflow#38352]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): no
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: None
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): TF 2.1.0 from pypi
- Python version: - Bazel 
version (if compiling from source): None
- GCC/Compiler version (if compiling from
source): None 
- CUDA/cuDNN version: - GPU model and memory: CUDA 10.1 CUDNN 7.6, no gpu, just compiling

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Follow-up on the SIG-build meeting of 07/04/2020.

In TF Addons, we use the docker image provided by tensorflow to build our "manylinux" wheels:

```
docker pull tensorflow/tensorflow:2.1.0-custom-op-gpu-ubuntu16
```

Uncompressed, this image is around 9.1GB. This poses several issues:
* Our disk quota of github-actions can't handle more than 14GB, we reached this limit multiple times and when we do, our CI build fails. We had to remove files from the docker image and squash it to make our CI work again.
* Downloading and decompressing the docker image takes a significant amount of time in the CI 2-3m. As a reference point, running the full build takes 12m.
* It makes it hard for developers to use the image locally because they need to download 4-5 GB of data (the docker image compressed is 4.24GB).

**Describe the expected behavior**

We should have multiple images depending on what python versions we want to use to compile. Those docker images should be around 3-4GB uncompressed.

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
docker pull tensorflow/tensorflow:2.1.0-custom-op-gpu-ubuntu16  && docker image ls
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

I digged into the docker image, see what was taking space, and I believe that I managed to find the biggest directories:

```
Total: 9.1G

1.7G    /usr/local/lib/python2.7
417M    /usr/local/lib/python3.6
157M    /usr/local/lib/python3.7
2.0G    /usr/local/cuda-10.1
2.0G    /usr/lib/x86_64-linux-gnu
591M    /root/.cache/pip
529M    /dt8  (devtoolset-8)
469M    /dt7  (devtoolset-9)

Those directories together take 7.8G, so 85% of the total size.
```

Possible actions:

-> Do not use the pip cache
-> Is there a need for the two devtoolset? Can one be enough?
-> Many pip installs are done in the Dockerfile for py2.7 (tf and other). 
   Those do not seem necessary as in TF Addons, we can build "manylinux" wheels with the py3.7
   which has nothing installed on it with pip (bare install).
-> Make a docker image for each python version, should save ~200MB per python version. e.g. 
`docker pull tensorflow/tensorflow:2.1.0-py3.6-custom-op-gpu-ubuntu16`

I would be nice to take care of this before the custom op docker image for tf 2.2.0 is released.

I was asked during the sig-build meeting to tag @yifeif .

Tagging @seanpmorgan  because he manages TF Addons.

**Comment by yifeif** [comment]
Thanks for the analysis @gabrieldemarmiesse! 
I'll look into if we can remove one of the devtoolset, and you are definitely right, we can remove python 2.7 related directory.

**Comment by bhack** [comment]
I think that generally the custom-ops `Dockerfile` receipts could not diverge so much from devel receipts. 
Seems that instead the receipt start `FROM` a scratch base image.
It is strange that devel and custom-ops don't have a common baseline.

**Comment by sachinprasadhs** [comment]
I'm able to see the smaller size of docker images of Tensorflow here https://hub.docker.com/r/tensorflow/tensorflow/tags/
Could you please close this issue, if your issue is resolved. Thanks!

**Comment by bhack** [comment]
> I'm able to see the smaller size of docker images of Tensorflow here https://hub.docker.com/r/tensorflow/tensorflow/tags/ Could you please close this issue, if your issue is resolved. Thanks!

Custom op images areunmaintained.
