### ISSUE TITLE
Add public API to get CUDA version and path, CUDNN version and path.

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [tensorflow/tensorflow#38351]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): TF 2.2.0rc2
- Are you willing to contribute it (Yes/No): no

**Describe the feature and the current behavior/state.**

Follow-up of the SIG build meeting of the 07/04/2020.

Currently TensorFlow is compiled against a specific CUDA and CUDNN version. When people want to build TensorFlow Addons from source, they have to specify manually the CUDA and CUDNN paths and version to use: https://github.com/tensorflow/addons/blob/master/configure.py#L159 

But it should not be needed to ask this information to the user. Because the user have to use the exact CUDA and CUDNN versions that TF was compiled against. Also TF is able to detect where are the CUDA and CUDNN directories on the user filesystem. If we could get this information out of TensorFlow, that would make the building of custom ops easier. We could also do some version checking at runtime and improve the user experience when there is a version mismatch.

**Will this change the current api? How?**

We would need 4 new functions/attributes (the names are examples or course):

* `tf.config.get_cuda_version_used_to_compile_tf()`
* `tf.config.get_cudnn_version_used_to_compile_tf()`
* `tf.get_cuda_path()`
* `tf.get_cudnn_path()`

**Who will benefit with this feature?**

People writing custom ops, as it makes the configuration easier for compilation, it also allows checking that people using the TF addons binaries have a compatible TF installed as the cuda and cudnn versions have to match.

**Any Other info.**

I was asked during the sig-build meeting to tag:
@perfinion @gunan @angerson @yifeif

@seanpmorgan as he manages TF Addons

**Comment by gunan** [comment]
@alextp for the proposed new APIs.

**Comment by alextp** [comment]
SGTM but I'd like the cuda_path and cudnn_path ones to also be in tf.config.

Maybe we should just have a tf.config.cuda_information() which returns a namedtuple of the information we want (versions, paths, and whatever else we need in the future)?

**Comment by gabrieldemarmiesse** [comment]
I don't have any preference regarding how it's named and under which namespace it's available.

**Comment by gunan** [comment]
I like the idea of having these under a separate namespace.

The cuda and cudnn paths are read from `LD_LIBRARY_PATH`.
So it is not known to us at build time. And we rely on OS shared object resolution, we just do `dlopen(libcuda...` Do you want us to replicate the OS so resolution in TF?

**Comment by gabrieldemarmiesse** [comment]
> So it is not known to us at build time.

Yes of course, since the path depends on the user system. I'm asking the path found at runtime. Since TF already knows at runtime where is the CUDA and CUDNN path, we'd like to grab that.

**Comment by gunan** [comment]
We actually do not know the paths. We simply load `libcuda.so` or `libcufft.so`.
The logic is here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/platform/default/dso_loader.cc#L42
The operating system checks `LD_LIBRARY_PATH`, and loads whatever it can. So it is all on the operating system.

**Comment by gunan** [comment]
Maybe we can extract the information using `dlinfo`:
http://man7.org/linux/man-pages/man3/dlinfo.3.html

**Comment by gabrieldemarmiesse** [comment]
Thanks @gunan for the explanation! We'll implement that then. We just need the two 

tf.config.get_cuda_version_used_to_compile_tf()
tf.config.get_cudnn_version_used_to_compile_tf()

then, or equivalent.

**Comment by gunan** [comment]
Agreed, let's definitely implement cuda/cudnn version queries.
They have no blockers. Then we can take our time to see if `dlinfo` tells us the path to the shared objects. If not, we can discuss about the paths again.

**Comment by angerson** [comment]
TensorFlow also has this mechanism:

```
from tensorflow.python.platform import build_info
```

Auto-generated during build time via https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/tools/build_info/gen_build_info.py and `tf_py_build_info_genrule` in https://osscs.corp.google.com/tensorflow/tensorflow/+/master:tensorflow/tensorflow.bzl. Right now it contains very little, but perhaps we could extend it with the information from https://cs.opensource.google/tensorflow/tensorflow/+/master:third_party/gpus/find_cuda_config.py that's used in `configure.py`?

**Comment by alextp** [comment]
+1 to extending build info over new apis

**Comment by perfinion** [comment]
https://www.tensorflow.org/api_docs/python/tf/sysconfig I've never heard its not public? Its been in the docs for ages and theres no indication its not to be relied on? There isnt much in it so its likely overlooked most of the time but its definitely listed publicly.

I know for sure custom-op uses it to make the build rules so it cant be removed either.

**Comment by gabrieldemarmiesse** [comment]
Thanks!

**Comment by angerson** [comment]
#38964 was reverted due to brittleness -- @r4nt gave some advice on improving it, so I'll work on re-enabling the functionality this week.

**Comment by angerson** [comment]
It took longer than I thought, but I have an internal change prepared for review that adds the same functionality in a different way.

**Comment by byronyi** [comment]
@angerson It seems that building tf-nightly now requires `opt_einsum` in host environment:

```
Mon Jun 8 13:08:20 UTC 2020 : === Building wheel
2020-06-08 13:08:21.249561: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    from tensorflow.python.platform import build_info
  File "/tmp/tmp.7oZofsqRJ1/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/tmp/tmp.7oZofsqRJ1/tensorflow/python/__init__.py", line 47, in <module>
    from tensorflow.python import keras
  File "/tmp/tmp.7oZofsqRJ1/tensorflow/python/keras/__init__.py", line 27, in <module>
    from tensorflow.python.keras import models
  File "/tmp/tmp.7oZofsqRJ1/tensorflow/python/keras/models.py", line 23, in <module>
    from tensorflow.python.keras import backend as K
  File "/tmp/tmp.7oZofsqRJ1/tensorflow/python/keras/backend.py", line 37, in <module>
    from tensorflow.python.distribute import distribute_coordinator as dc
  File "/tmp/tmp.7oZofsqRJ1/tensorflow/python/distribute/distribute_coordinator.py", line 33, in <module>
    from tensorflow.python.training import monitored_session
  File "/tmp/tmp.7oZofsqRJ1/tensorflow/python/training/monitored_session.py", line 45, in <module>
    from tensorflow.python.training.tracking import graph_view
  File "/tmp/tmp.7oZofsqRJ1/tensorflow/python/training/tracking/graph_view.py", line 27, in <module>
    from tensorflow.python.training import optimizer as optimizer_v1
  File "/tmp/tmp.7oZofsqRJ1/tensorflow/python/training/optimizer.py", line 36, in <module>
    from tensorflow.python.ops import gradients
  File "/tmp/tmp.7oZofsqRJ1/tensorflow/python/ops/gradients.py", line 27, in <module>
    from tensorflow.python.ops.gradients_impl import gradients
  File "/tmp/tmp.7oZofsqRJ1/tensorflow/python/ops/gradients_impl.py", line 30, in <module>
    from tensorflow.python.ops import linalg_grad  # pylint: disable=unused-import
  File "/tmp/tmp.7oZofsqRJ1/tensorflow/python/ops/linalg_grad.py", line 47, in <module>
    from tensorflow.python.ops.linalg import linalg_impl as _linalg
  File "/tmp/tmp.7oZofsqRJ1/tensorflow/python/ops/linalg/linalg_impl.py", line 34, in <module>
    from tensorflow.python.ops import special_math_ops
  File "/tmp/tmp.7oZofsqRJ1/tensorflow/python/ops/special_math_ops.py", line 30, in <module>
    import opt_einsum
ImportError: No module named 'opt_einsum'
```

which seems to [break tf-nightly on Linux](https://pypi.org/project/tf-nightly/2.3.0.dev20200606/#files) since your CL landed; not sure if it's going to be fixed in TF or the build environment.

**Comment by gunan** [comment]
That is an unrelated problem. Could you open a new issue?

**Comment by byronyi** [comment]
@gunan Just found out that it's been fixed by 67099d08529a00f48ee8a444f471067bedcc2f5b. So no need to open a new issue :)

**Comment by angerson** [comment]
Thanks for the fix, @gunan!

@gabrieldemarmiesse tf.sysconfig.get_build_info() is working in the latest tf-nightly (thanks to follow-up fixes from @chsigg and @gunan). Can you check it out?

**Comment by gabrieldemarmiesse** [comment]
Thanks everyone, I'll take a look :)

**Comment by sub-mod** [comment]
@angerson this is awesome! Thanks.
```
>>> import tensorflow as tf
W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/devtoolset-7/root/usr/lib64/dyninst:/opt/rh/devtoolset-7/root/usr/lib/dyninst:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/rh-python36/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/opt/rh/devtoolset-8/root/usr/lib64/dyninst:/opt/rh/devtoolset-8/root/usr/lib/dyninst:/usr/local/lib64:/usr/local/lib
I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
>>>
>>> tf.__version__
'2.4.0-dev20200706'
>>>
>>> tf.sysconfig.get_build_info()
{'cuda_version': '10.1', 'cudnn_version': '7', 'cuda_compute_capabilities': ['sm_35', 'sm_37', 'sm_52', 'sm_60', 'sm_61', 'compute_70'], 'cpu_compiler': '/usr/bin/gcc-5', 'is_rocm_build': False, 'is_cuda_build': True}
```
