### ISSUE TITLE
Marginal Probablities in CRF

### ISSUE THREAD

**Issue by FallakAsad** [tensorflow/tensorflow#38359]
After training a CRF model, I can get the best tag sequence y and its unormalized score for each test input sequence x through tf.contrib.crf.viterbi_decode() or tf.contrib.crf.crf_decode() but what changes might require in CRF implementation to get the marginal probabilities?

Tensorflow version: 1.15.0

**Comment by amahendrakar** [comment]
@FallakAsad,
If this is a bug, could you please provide the complete code to reproduce the issue reported here.

If the issue reported here is not a bug or a feature request, the question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) as there is a larger community that reads questions there. Thanks!

**Comment by amahendrakar** [comment]
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by sakusss** [comment]
I also want to know how to calculate the margin probability in CRF

**Comment by agarwalishan** [comment]
I also want the same.

**Comment by amahendrakar** [comment]
@sakusss, @agarwalishan,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
