### ISSUE TITLE
Some types of fetches in tf.Session.run are not supported and it behaves strange in container

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/tensorflow#3835]
There're two issues I have found when giving different type of fetches in `tf.Session.run()`.

The [doc](https://www.tensorflow.org/versions/master/api_docs/python/client.html) says that we can pass the nested list or tuple to `run()` but it doesn't work.

```
tf.Session.run(fetches, feed_dict=None, options=None, run_metadata=None)

Runs operations and evaluates tensors in fetches.

This method runs one "step" of TensorFlow computation, by running the necessary graph fragment to execute every Operation and evaluate every Tensor in fetches, substituting the values in feed_dict for the corresponding input values.

The fetches argument may be a single graph element, or an arbitrarily nested list, tuple, namedtuple, or dict containing graph elements at its leaves. A graph element can be one of the following types:
```

It's easy to test with this script.

```
import tensorflow as tf

a = tf.placeholder("float")
b = tf.placeholder("float")
add_op = tf.add(a, b)
mul_op = tf.mul(a, b)

output_array = [[add_op, mul_op]]

with tf.Session() as sess:
    output_array = sess.run(output_array, feed_dict={a: 1, b: 2})
    print(output_array)
```

And I found it works if I pass the `array` or `dict`. But what's strange is that the `dict` doesn't work in docker container which is also easy to reproduce by creating the tensorflow container to run the same script. You can find my test code and error log below.

![screen shot 2016-08-16 at 11 52 31](https://cloud.githubusercontent.com/assets/2715000/17687714/3e4a83a8-63aa-11e6-98be-e20a7099f77b.png)

### Environment info
Operating System: Ubuntu 16.04

If installed from binary pip package, provide:
TensorFlow 0.8

**Comment by vrv** [comment]
Try a newer version of tf

**Comment by tobegit3hub** [comment]
I run the `tensorflow/tensorflow:0.10.0rc0` and all `list`, `nested list`, `dict` and `tuple` work like a charm. The `dict` works because my local TensorFlow is `0.9.0` and the document seems really clear.

Thanks for your guide @vrv and this feature is really important for our inference services.

BTW, the `tensorflow/tensorflow:latest` is not "latest" at all.
