### ISSUE TITLE
2 different "no module" errors in two different versions

### ISSUE THREAD

**Issue by Tylersuard** [tensorflow/tensorflow#38361]
**System information** 
- I wrote custom code
- Google Colab
- TensorFlow installed from default, then I tried multiple versions using Pip 
- TensorFlow version (use command below): 
1.4, 1.9, 1.11, 2.0
- Python version: 3.6

**Describe the current behavior**
If I use a version of Tensorflow 1, I get the error "tensorflow.data has no attribute: experimental" and if I use tensorflow 2 I get: tensorflow has no atrribute: placeholder.

**Describe the expected behavior**
I was hoping for the script to work without errors.

**Standalone code to reproduce the issue** 
https://colab.research.google.com/drive/1N0CtpO6VZvcyE72r3eEkBQthQsUlm6Hf

**Comment by saahiluppal** [comment]
Tensorflow 1.x uses graph mode by default, and placeholders can only be run in sessions. But Tensorflow 2.x eagerly executes by default hence no need to manage sessions, so no need to manage placeholders. 
But still if you want to use placeholders and manage sessions. here you go
<a href='https://www.tensorflow.org/api_docs/python/tf/compat/v1/placeholder'>tensorflow.compat.v1.placeholder</a>

And that **experimental** attribute, that's constantly changing. The functions inside experimental that are frequently used by users, they are included in tensorflow. others are removed from there.
_as name suggests **experimental**_

**Comment by Tylersuard** [comment]
Thank you for your help!  I'm sorry for my ignorance, but how do I use the tensorflow.compat.v1.placeholder in the above colab notebook?

**Comment by saahiluppal** [comment]
Have a look at the documentation <a href='https://www.tensorflow.org/api_docs/python/tf/compat/v1/placeholder'>here<a>. And pick up the use case which suits your needs.
But it's highly reccomended to use Tensorflow 2.x
Have a look if you wanna migrate from Tensorflow 1.x to Tensorflow 2.x here <a href='https://www.tensorflow.org/guide/migrate'>here</a>

**Comment by ravikyram** [comment]
@Tylersuard 

Any update on this issue please. Please, close this thread if it solves your question.Thanks!
