### ISSUE TITLE
Memory Growth and Memory Limit incompatibility

### ISSUE THREAD

**Issue by FMalerba** [tensorflow/tensorflow#38367]
**System information** 
- Custom Code
- OS Platform and Distribution: Windows 10 Home 1909
- TensorFlow installed with pip
- TensorFlow version: v2.1.0-rc2-17-ge5bf8de410, 2.1.0
- Python version: 3.7.6
- CUDA/cuDNN version: CUDA 10.1, cuDNN 7.6.5
- GPU model and memory: NVIDIA GTX 1050 notebook, 4GB memory

**Describe the current behavior**
Tensorflow "forgets" about the setting on memory_growth once you create a vritual device to further limit maximum VRAM usage.

**Describe the expected behavior**
In practice I would like to be able to both limit maximum VRAM usage AND to tell TF to only use the VRAM that it needs with the memory_growth option. This is something that I was able to do in TF 1.x by passing an appropriate config to a Session, but it doesn't seem like it's possible in TF 2.x (without using 1.x code that is...)

**Standalone code to reproduce the issue** 
https://colab.research.google.com/drive/1MJgZiHernOjT_3vB57YMnjjTRJhgpspo

**Comment by gowthamkpr** [comment]
As mentioned [here](https://www.tensorflow.org/api_docs/python/tf/config/experimental/set_memory_growth#used-in-the-notebooks) If memory growth is enabled for a PhysicalDevice, the runtime initialization will not allocate all memory on the device. Memory growth cannot be configured on a PhysicalDevice with virtual devices configured.

**Comment by FMalerba** [comment]
I understand, but is it possible as it was before to both set memory growth and a hard limit on the maximum amount of memory that it can occupy

**Comment by gowthamkpr** [comment]
As per the documentation, it is not possible @FMalerba

**Comment by FMalerba** [comment]
Thank you very much for the info
