### ISSUE TITLE
AutoGraph Warning on Tensorflow-gpu==2.0.0b1

### ISSUE THREAD

**Issue by abpalaciot** [tensorflow/tensorflow#38365]
Running the Image Captioning tutorial (https://www.tensorflow.org/tutorials/text/image_captioning) on google colab with tensorflow-gpu==2.0.0b1 produces the next warning.

WARNING: Entity <function standard_gru at 0x7fa68b50b488> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function standard_gru at 0x7fa68b50b488>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <function cudnn_gru at 0x7fa68b50b730> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function cudnn_gru at 0x7fa68b50b730>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <function cudnn_gru at 0x7fa68b50b730> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function cudnn_gru at 0x7fa68b50b730>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7fa60d01b588>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7fa60d01b588>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7fa60d01b588>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7fa60d01b588>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7fa60d0772b0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7fa60d0772b0>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING: Entity <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7fa60d0772b0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7fa60d0772b0>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <function standard_gru at 0x7fa68b50b488> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function standard_gru at 0x7fa68b50b488>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <function standard_gru at 0x7fa68b50b488> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function standard_gru at 0x7fa68b50b488>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <function cudnn_gru at 0x7fa68b50b730> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function cudnn_gru at 0x7fa68b50b730>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <function cudnn_gru at 0x7fa68b50b730> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function cudnn_gru at 0x7fa68b50b730>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7fa60d01b588>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7fa60d01b588>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7fa60d01b588>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7fa60d01b588>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7fa60d0772b0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7fa60d0772b0>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING: Entity <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7fa60d0772b0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7fa60d0772b0>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <function standard_gru at 0x7fa68b50b488> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function standard_gru at 0x7fa68b50b488>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <function standard_gru at 0x7fa68b50b488> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function standard_gru at 0x7fa68b50b488>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <function cudnn_gru at 0x7fa68b50b730> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function cudnn_gru at 0x7fa68b50b730>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <function cudnn_gru at 0x7fa68b50b730> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function cudnn_gru at 0x7fa68b50b730>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7fa60d01b588>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7fa60d01b588>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7fa60d01b588>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method RNN_Decoder.call of <__main__.RNN_Decoder object at 0x7fa60d01b588>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7fa60d0772b0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7fa60d0772b0>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING: Entity <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7fa60d0772b0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BahdanauAttention.call of <__main__.BahdanauAttention object at 0x7fa60d0772b0>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <function standard_gru at 0x7fa68b50b488> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function standard_gru at 0x7fa68b50b488>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <function standard_gru at 0x7fa68b50b488> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function standard_gru at 0x7fa68b50b488>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <function cudnn_gru at 0x7fa68b50b730> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function cudnn_gru at 0x7fa68b50b730>: AttributeError: module 'gast' has no attribute 'Num'
WARNING: Entity <function cudnn_gru at 0x7fa68b50b730> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function cudnn_gru at 0x7fa68b50b730>: AttributeError: module 'gast' has no attribute 'Num'

**Comment by amahendrakar** [comment]
@abpalaciot,

Is there any specific reason you are using the beta version of TF v2.0? I'd suggest you to upgrade to the stable version of either TF v2.0 or TF v2.1. 

I was able to run the tutorial without any issues or warnings using the stable version of TF v2.0, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/b65d52b10c3a57056262c9aa059dce2e/38365.ipynb). Thanks!

**Comment by amahendrakar** [comment]
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
