### ISSUE TITLE
what's the difference between tensorflow functions and tensorflow.keras.backend functions?

### ISSUE THREAD

**Issue by saahiluppal** [tensorflow/tensorflow#38362]
I know this is not a Technical Issue, but i found no answers regarding this, hence i came here for support.

Many of the tensorflow functions overlap with the tensorflow.keras.backend functions.

For eg:
tensorflow.keras.backend have sum
tensorflow have reduced_sum

tensorflow.keras.backend have square
tensorflow have math.square

tensorflow.keras.backend have mean
tensorflow have reduced_mean

tensorflow.keras.backend have exp
tensorflow have exp

and many more functions overlap.

are these functions different in some perspective?

**Comment by Saduf2019** [comment]
@saahiluppal 
please refer to these links and let us know if it helps [link1](https://www.pyimagesearch.com/2019/10/21/keras-vs-tf-keras-whats-the-difference-in-tensorflow-2-0/) [link2](https://analyticsindiamag.com/tensorflow-vs-keras-which-one-should-you-choose/) [link3](https://stackoverflow.com/questions/60768547/what-is-the-difference-between-functions-from-keras-backend-and-tensorflow)

**Comment by saahiluppal** [comment]
It seems that both are same. Thanks
