### ISSUE TITLE
Strange behavior of ODE solving toy model

### ISSUE THREAD

**Issue by yarik1988** [tensorflow/tensorflow#38366]
**System information** 
- OS Platform and Distribution Windows 10
- TensorFlow installed from source TensorFlow 2.2.0 
- Python version: 3.8
- CUDA/cuDNN version: 10.1

```
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt

N = 1000
x = tf.convert_to_tensor(np.linspace(0, 1, num=N), dtype=tf.float32)

with tf.GradientTape() as t:
    x_inp = keras.Input(shape=(1,), name='indvar')
    t.watch(x_inp)
    dense = layers.Dense(100, activation='tanh')(x_inp)
    dense = layers.Dense(100, activation='tanh')(dense)
    dense = layers.Dense(100, activation='tanh')(dense)
    dense = layers.Dense(100, activation='tanh')(dense)
    dense = layers.Dense(100, activation='tanh')(dense)
    dense = layers.Dense(100, activation='tanh')(dense)
    dense = layers.Dense(100, activation='tanh')(dense)
    yhat = layers.Dense(1, name='y')(dense)
    dyhat = t.gradient(yhat, x_inp)
    model = keras.Model(inputs=x_inp, outputs=[yhat, dyhat])
    opt=tf.keras.optimizers.Adam()
    model.compile(optimizer=opt, loss='MSE')
    model.summary()
    model.fit(x=x, y=[x, np.sin(10*x)], epochs=10000, batch_size=N)
    y, dy = model(x)
    plt.plot(x, np.array(y))
    plt.plot(x, np.array(dy))
    plt.show()
```
I try to make model output y=x, while y'=sin(10*x). Surely this is impossible so the expected behavior of the model is NOT converge. However model converges and have both y=x and y'=sin(10*x) satisfied, however it is impossible.

**Comment by ravikyram** [comment]
@yarik1988 

I tried reproducing the issue but i am facing the below issue.Please,see in the screenshot. Is this the expected behavior

![error](https://user-images.githubusercontent.com/51902062/78864823-1703ed00-7a5a-11ea-84c4-674413a5bd6a.png)

**Comment by yarik1988** [comment]
No, in my PC it works well. I found even smaller toy example that shows the bug
```
N = 1000
x = np.linspace(0, 1, num=N)

with tf.GradientTape() as t:
    x_inp = keras.Input(shape=(1,), name='indvar')
    t.watch(x_inp)
    reg=tf.keras.regularizers.l2(l=0.01)
    dense = layers.Dense(100, activation='tanh', kernel_regularizer=reg)(x_inp)
    for i in range(2):
        dense = layers.Dense(100, activation='tanh', kernel_regularizer=reg)(dense)
    yhat = layers.Dense(1, name='y')(dense)
    dyhat = t.gradient(yhat, x_inp)
    model = keras.Model(inputs=x_inp, outputs=[yhat, dyhat])
    opt=tf.keras.optimizers.Adam()
    model.compile(optimizer=opt, loss=[lambda y, y_act: 0,'MSE'])
    model.summary()
    #model.fit(x=x, y=[x, x*x], epochs=1, batch_size=N)  #with this line,  numerical derivative will differ from analytical
    y, dy = model(x)
    dy_num = np.gradient(np.array(y).squeeze(), x)
    plt.plot(x, y)
    plt.plot(x, dy)
    plt.plot(x, dy_num)
    plt.legend(['y', 'dy', 'dynum'])
    plt.show()
```

**Comment by ravikyram** [comment]
@yarik1988 

I tried to reproduce the issue in colab .Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/bfe689e64e1026192a4b554929d0fb5a/untitled26.ipynb). Is this the expected behavior.Thanks!

**Comment by yarik1988** [comment]
> @yarik1988
> 
> I tried to reproduce the issue in colab .Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/bfe689e64e1026192a4b554929d0fb5a/untitled26.ipynb). Is this the expected behavior.Thanks!

From the mathematical point of view this behavior is not neither logical neither expected. I created gist of my another example that shows the problem
https://colab.research.google.com/gist/yarik1988/92890b0d9a690773f2c1204d348f8478/untitled0.ipynb#scrollTo=JOB6TP8OuLmw

**Comment by yarik1988** [comment]
However with this line commented
`model.fit(x=x, y=[x, x*x], epochs=1, batch_size=N)`
numerical derivative coincides with analytical one, which is logical.

**Comment by sachinprasadhs** [comment]
While trying to reproduce your issue in Tf Nightly faced some error, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/71d635e442d48d6fa41e37977975ea3f/38366.ipynb). Thanks!

**Comment by chunduriv** [comment]
I was able to reproduce your issue in `TF v2.7` and `tf-nightly (2.8.0-dev20211124)` faced some error, please find the [gist here](https://colab.research.google.com/gist/chunduriv/d8a0cf48da88aa06f47c2171dd6fd68a/38366.ipynb). Thanks!
