### ISSUE TITLE
Cannot convert between a TensorFlowLite buffer with 76800 bytes and a Java Buffer with 230400 bytes

### ISSUE THREAD

**Issue by lingjiekong** [tensorflow/tensorflow#38370]
I modify the image classification code https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android to run inference on a float type grayscale bitmap with size (1, 120, 160, 1). However, an exception is throw regarding "Cannot convert between a TensorFlowLite buffer with 76800 bytes and a Java Buffer with 230400 bytes". I checked the input tensor image shape which is indeed (1, 120, 160, 1).

Basically, java buffer is still assuming the input size is (1, 120, 160, 3). Therefore, what need be modified in order to run inference on grayscale image for image classification code? I feel like TensorImage class is somehow hard-coded for RBG image instead of grayscale one.

    Process: org.tensorflow.lite.examples.classification, PID: 20064
    java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 76800 bytes and a Java Buffer with 230400 bytes.
        at org.tensorflow.lite.Tensor.throwIfShapeIsIncompatible(Tensor.java:402)
        at org.tensorflow.lite.Tensor.throwIfDataIsIncompatible(Tensor.java:369)
        at org.tensorflow.lite.Tensor.setTo(Tensor.java:187)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:150)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:314)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:275)
        at org.tensorflow.lite.examples.classification.tflite.Classifier.recognizeImage(Classifier.java:266)
        at org.tensorflow.lite.examples.classification.ClassifierActivity$3.run(ClassifierActivity.java:98)
        at java.lang.Thread.run(Thread.java:919)

**Comment by xunkai55** [comment]
Sorry, but yes the TensorImage class only supports RGB image. It's on our radar now but may not be very soon.

**Comment by xunkai55** [comment]
Please let me know if you need further help, or you want to raise a general issue on grayscale support.

**Comment by lingjiekong** [comment]
Got it and thanks for the update! 

I just want to double check on the complexity of modifying the TensorImage source code to get grayscale image working to see whether it worths myself to spend time on that. Otherwise, I might simply raise a general issue on grayscale image to let you guys help resolve.

**Comment by xunkai55** [comment]
I don't think it's too hard. Let me try it tomorrow and will let you know.

**Comment by lingjiekong** [comment]
Thanks. I feel this is related to line 141 in TensorImage.class

int requiredFlatSize = this.bitmapImage.getWidth() * this.bitmapImage.getHeight() * 3;

However, it will be nice that you can help confirm and let me know if I missed something else.

Thanks!

**Comment by xunkai55** [comment]
That's one. Also the `TensorImage.load` methods, and the conversion code in `ImageConversions.java`.

It's not really difficult to modify to get it running, but design consistent interfaces might take longer.

For your usage, I'm curious about how you store a gray image in Android - or saying how you expect to convert the Bitmap to values. Are you just interested in one particular channel? Or you want to use formulas in https://en.wikipedia.org/wiki/Grayscale to compute the gray scale?

Thanks!

**Comment by lingjiekong** [comment]
Regarding `TensorImage.load`, I am loading a bitmap image. From what I see, https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/support/java/src/java/org/tensorflow/lite/support/image/TensorImage.java#L119, it should be fine. However, I see what you are saying that if I am going to load a int or float pixel array, I have to make an modification. https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/support/java/src/java/org/tensorflow/lite/support/image/TensorImage.java#L151

Regarding `ImageConversions.java`, I see I have to modify this method https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/support/java/src/java/org/tensorflow/lite/support/image/ImageConversions.java#L90 regarding couple place assuming that size is (w, h, 3).

I am actually using use formulas in https://en.wikipedia.org/wiki/Grayscale to compute the gray scale to store grayscale image because our Neural Network is trained on grayscale images. 

Also, one more question, is there a quick method to apply a patch on Gradle file because I never patch a Gradle file before.

**Comment by xunkai55** [comment]
Thanks for the info. We're considering the best way to support single channel images, so understanding usages are essential. That's really helpful.

What do you mean by "patching a gradle file"? If you're talking about adding a new class or modifying existing class in a gradle dependency, I googled a bit and seems there are several different ways to do that. You may need to take a look and choose what's the best one for you.

**Comment by lingjiekong** [comment]
Sorry about the confusion and I was talking about modifying gradle dependency. I was initially wondering that whether I can directly apply a patch during the build to modify the necessary files. However, it looks like the easiest way is to add as an external library and the modify.
https://stackoverflow.com/questions/16588064/how-do-i-add-a-library-project-to-android-studio/16639227#16639227
https://stackoverflow.com/questions/30344053/how-do-you-edit-a-dependency-external-library-in-android-studio

Take your time to figure out the best way to support multi/single channel images and thanks for the help!
