### ISSUE TITLE
Regarding Ear Landmark Dataset

### ISSUE THREAD

**Issue by Rutvik21** [tensorflow/tensorflow#38379]
I have made ear landmark dataset as shown below image.
![image](https://user-images.githubusercontent.com/29560869/78864360-1cad0300-7a59-11ea-96ad-d68f3be53bb3.png)
I want to make a model to predict the landmarks. So I want some advice on whether I should create my own model or should I use any pre-built model to train it with this dataset.
Thank you

**Comment by ravikyram** [comment]
This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by Rutvik21** [comment]
Okay, thanks for the reply. 
I will ask on StackOverflow and closing this issue.
