### ISSUE TITLE
Google Developers Certification

### ISSUE THREAD

**Issue by HarryPommier** [tensorflow/tensorflow#38382]
Google Developers Certification plugin is not available in PyCharm 2020.1 (it is needed to take the Tensorfow Certification exam):

![gdc](https://user-images.githubusercontent.com/50177956/78879616-69daa600-7a54-11ea-9ad4-1212c1e289bf.png)

**Comment by GodSaveTheDucks** [comment]
I faced the same issue. Downgraded PyCharm to pycharm-community-2019.3.4

**Comment by JosBecker** [comment]
Hello,

The Google Developers Certification plugin is now available in PyCharm 2020.
