### ISSUE TITLE
docker image to build manylinux, ubuntu16

### ISSUE THREAD

**Issue by wwwind** [tensorflow/tensorflow#38385]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04

**Describe the problem**
I am building tensorflow pip wheel from source and I would like to build it for Ubuntu 16.04.
I found the docker image with ubuntu16 and installed auditwheel that looks like a fit for my purpose:
tensorflow:custom-op-ubuntu16,
but it is very heavy - 6Gb.

Could you please recommend which tensorflow docker image should I use to build manylinux wheel ?
Is there an easy way to build tensorflow pip package for Ubuntu 16.04 from source ?

**Comment by Saduf2019** [comment]
@wwwind 
please share the tensorflow version

**Comment by wwwind** [comment]
nightly builds

**Comment by angerson** [comment]
You can use the `devel` image tags. See https://hub.docker.com/r/tensorflow/tensorflow/ for details.
