### ISSUE TITLE
Tensorflow: cannot install custom user_op for roi_pooling

### ISSUE THREAD

**Issue by alfonsolink** [tensorflow/tensorflow#3838]
I experimented with a user-op for ROI_pooling in this fork: https://github.com/yuxng/tensorflow/, 

I tried several ways to make it work:

Attempt 1:

1) uninstalled tensorflow
2) placed the roi_pooling files (roi_pooling_op.cc, roi_pooling_op_gpu.cu.cc, roi_pooling_op_gpu.h, roi_pooling_op_grad.py, roi_pooling_op_test.py) in //tensorflow/core/user_ops/ (without BUILD so that they get incorporated with the install)
3) reinstalled tensorflow using bazel with bazel build -c opt --config=cuda ...

I then get this error with attempt 1: 

ERROR: /home/fishdrop/tensorflow/tensorflow/cc/BUILD:116:1: Linking of rule '//tensorflow/cc:ops/user_ops_gen_cc' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -o bazel-out/host/bin/tensorflow/cc/ops/user_ops_gen_cc ... (remaining 41 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
bazel-out/host/bin/tensorflow/core/libuser_ops_op_lib.lo(roi_pooling_op.o): In function `RoiPoolGradOp<Eigen::GpuDevice, float>::Compute(tensorflow::OpKernelContext*)':
roi_pooling_op.cc:(.text._ZN13RoiPoolGradOpIN5Eigen9GpuDeviceEfE7ComputeEPN10tensorflow15OpKernelContextE[_ZN13RoiPoolGradOpIN5Eigen9GpuDeviceEfE7ComputeEPN10tensorflow15OpKernelContextE]+0x3ea): undefined reference to `ROIPoolBackwardLaucher(float const*, float, int, int, int, int, int, int, int, float const*, float*, int const*, Eigen::GpuDevice const&)'
bazel-out/host/bin/tensorflow/core/libuser_ops_op_lib.lo(roi_pooling_op.o): In function `RoiPoolOp<Eigen::GpuDevice, float>::Compute(tensorflow::OpKernelContext*)':
roi_pooling_op.cc:(.text._ZN9RoiPoolOpIN5Eigen9GpuDeviceEfE7ComputeEPN10tensorflow15OpKernelContextE[_ZN9RoiPoolOpIN5Eigen9GpuDeviceEfE7ComputeEPN10tensorflow15OpKernelContextE]+0x392): undefined reference to `ROIPoolForwardLaucher(float const*, float, int, int, int, int, int, int, float const*, float*, int*, Eigen::GpuDevice const&)'
collect2: error: ld returned 1 exit status
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/fishdrop/tensorflow/tensorflow/cc/BUILD:116:1 Linking of rule '//tensorflow/cc:ops/user_ops_gen_cc' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -o bazel-out/host/bin/tensorflow/cc/ops/user_ops_gen_cc ... (remaining 41 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.

Attempt 2:

1) re-install tensorflow
2) place files (with BUILD) in //tensorflow/core/user_ops/
3) use bazel build -c opt //tensorflow/core/user_ops:roi_pooling.so

This successfully built roi_pooling.so, but when I tried to load the module with tf.load_op_library, I get this error: 

tensorflow.python.framework.errors.NotFoundError: /home/fishdrop/tensorflow/bazel-bin/tensorflow/core/user_ops/roi_pooling.so: undefined symbol: _Z21ROIPoolForwardLaucherPKffiiiiiiS0_PfPiRKN5Eigen9GpuDeviceE

The error seems to be related with Eigen, but I read in this Link: http://stackoverflow.com/questions/38618960/tensorflow-how-to-insert-custom-input-to-existing-graph, that the user_op is supposed to work.. 

I am using Ubuntu 14.04 LTS, and I tried these procedures in both Tensorflow 0.10 and Tensorflow 0.08, and got the same errors.. Anyone who could help?

**Comment by sherrym** [comment]
In your roi_polling.cc file, all GPU related code must be encapsulated by #if GOOGLE_CUDA #endif.

To make debugging easier, would you please do the following:

1. Remove all GPU code, include removing them from the build file.
2. Build with -c opt only and see if you can load the .so successfully.

If that works, then add the GPU code.

Please following instructions here https://www.tensorflow.org/versions/r0.10/how_tos/adding_an_op/index.html
step by step.

Sherry

**Comment by alfonsolink** [comment]
thanks for the tip, i just found out that the error occured when I built the user_op without GPU support. 

I reinstalled tensorflow v 0.10, with GPU support, and placed all user_op files inside //tensorflow/core/user_ops. 

If I compile the user_op using bazel build -c opt --config=cuda //tensorflow/core/user_ops:roi_pooling.so (the addition of --config=cuda isn't in the tensorflow user_op documentation), the user_op now works
