### ISSUE TITLE
tflm vc compilation error and how to fix

### ISSUE THREAD

**Issue by yadonskov** [tensorflow/tensorflow#38390]
in file tensorflow\lite\micro\kernels\svdf.cc
there is __restrict__ keword, so it can't be compiled with VC.
I added 

```
#ifdef _MSC_VER
	#define RESTRICT __restrict
#else
	#define RESTRICT __restrict__
#endif
```

and replaced __restrict__  with RESTRICT  - now compiles without problems

**Comment by Saduf2019** [comment]
@yadonskov 
could you please let us know the tensorflor flow version for which you are facing this issue

**Comment by yadonskov** [comment]
@Saduf2019 
I used commit 920fefa2eeffddd491845d798836a6800668ded9.
I found this when I was compiling my TFLM app with cl.exe compiler.
It's not tensorflow build problem - it's problem of TFLM usage.

**Comment by Saduf2019** [comment]
@yadonskov 
can you please check [this link](https://github.com/tensorflow/tensorflow/pull/31847) and let us know if it would help

**Comment by yadonskov** [comment]
@Saduf2019 
it doesn't look like needed code. I just showed you compilation error with cl.exe. and a simple way to fix it. If you have better way to do it - just do it.
