### ISSUE TITLE
how to know the GPU's num and specify with tf ?

### ISSUE THREAD

**Issue by ucas010** [tensorflow/tensorflow#38394]
hi,dear
haven't seen the methed of tf codes,
So I just want to solve the problem.
Could you please help me ?

thx

**Comment by Saduf2019** [comment]
@ucas010 
please follow https://www.tensorflow.org/guide/gpu to know gpu's available

**Comment by Saduf2019** [comment]
@ucas010
please update as per above comment

**Comment by Saduf2019** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
