### ISSUE TITLE
Generalize cross compiling libtensorflow-lite.a for arm32

### ISSUE THREAD

**Issue by Namburger** [tensorflow/tensorflow#38395]
**System information**
- TensorFlow version (you are using):N/A
- Are you willing to contribute it (Yes/No): Yes (maybe if I can figure it out haha)

**Describe the feature and the current behavior/state.**
Right now cross compiling `libtensorflow-lite.a` will be either for [arm64](https://www.tensorflow.org/lite/guide/build_arm64) (which works great, thanks) and [rpi](https://www.tensorflow.org/lite/guide/build_rpi). I understand the build for rpi will mostly be for arm32 bits, why not make that more generalized for any arm32 system?
Also, with rpi4 in the market, we are running into issues where processor can support armv8 (64 bits) but the official OS is yet to support 64 bits. What happens when users start installing 64bits OS and realized that their rpi build isn't working?

**Will this change the current api? How?**
No changes to the api at all as far as I'm concern, the tutorial may just be more generalized as a user.

**Who will benefit with this feature?**
Anybody with a 32bits arm machine :)

Please correct me if I understand this incorrectly or if this issue has been raised before!
Thanks

**Comment by terryheo** [comment]
I've just checked in ARM crossbuild toolchains (https://github.com/tensorflow/tensorflow/commit/4961f18733ca3967198393abf419e14476b4a85c)  for Bazel build.

You can build armhf, aarch64 targets with the following commands.

```sh
$ bazel build --config=elinux_armhf  //tensorflow/lite/tools/benchmark:benchmark_model 
$ bazel build --config=elinux_aarch64  //tensorflow/lite/tools/benchmark:benchmark_model 
```

**Comment by Namburger** [comment]
@terryheo sorry, I didn't stated my full intention. The problem is that I'm trying to build tflite natively on different platform, without needing to first cross compile the `lib-tensorflowlite.a` first. The problem with this approach is that `bazel` doesn't support arm platform. So I'm working with cmake instead and I'm using your [makefile](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/make/Makefile) which leads to this `rpi_makefile.inc` from [this line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/make/Makefile#L244).
I see that the included makefile above has 'armv7l' and a `TARGET_ARCH`, so I guess my concerns is that why not make this a `arm32_makefile` instead of rpi_makefile?

Here is my specific use case:
Let say I wanted to add tflite as an ExternalProject in cmake:

```
ExternalProject_Add(tflite
    GIT_REPOSITORY https://github.com/tensorflow/tensorflow
    PREFIX "tensorflow"
    CONFIGURE_COMMAND ./tensorflow/lite/tools/make/download_dependencies.sh
    BUILD_IN_SOURCE 1
    BUILD_COMMAND ${TFLITE_BUILD_COMMAND}
${CMAKE_BINARY_DIR}/tensorflow/src/tf/tensorflow/lite/tools/make/gen/${TF_INSTALL_PREFIX}/lib/libtensorflow-lite.a ${CMAKE_BINARY_DIR}/
)
```
Then I need to set the `${TFLITE_BUILD_COMMAND}` variable, that's the variable that I'm talking about and here is how I'm setting it:

```
# GET CPU Architechture
if(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64")
    set(EDGE_ARCH "k8")
    set(TFLITE_BUILD_COMMAND make -j8 BUILD_WITH_NNAPI=false -C ${CMAKE_BINARY_DIR}/tensorflow/src/tf -f tensorflow/lite/tools/make/Makefile lib)
    set(TF_INSTALL_PREFIX "linux_x86_64")
elseif(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "aarch64")
    set(EDGE_ARCH "${CMAKE_SYSTEM_PROCESSOR}")
    set(TF_INSTALL_PREFIX "generic-aarch64_armv8-a")
    set(CROSS_PREFIX "aarch64-linux-gnu-")
    set(TFLITE_BUILD_COMMAND make -j4 TARGET=generic-aarch64 TARGET_ARCH=armv8-a -C ${CMAKE_BINARY_DIR}/tensorflow/src/tf -f tensorflow/lite/tools/make/Makefile CC=${CROSS_PREFIX}g++ CXX=${CROSS_PREFIX}g++ AR=${CROSS_PREFIX}ar CFLAGS=-fpermissive lib)
elseif(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "armv7l")
    message("We are going to assume that this build is for the rpi")
    set(EDGE_ARCH "${CMAKE_SYSTEM_PROCESSOR}")
    set(TF_INSTALL_PREFIX "rpi_armv7l")
    set(CROSS_PREFIX "arm-linux-gnueabihf-")
    set(TFLITE_BUILD_COMMAND make -j4 TARGET=rpi TARGET_ARCH=armv7l -C ${CMAKE_BINARY_DIR}/tensorflow/src/tf -f tensorflow/lite/tools/make/Makefile CC=${CROSS_PREFIX}g++ CXX=${CROSS_PREFIX}g++ AR=${CROSS_PREFIX}ar CFLAGS=-fpermissive lib)
else()
	message(FATAL_ERROR "Not implemented to build for: ${CMAKE_SYSTEM_PROCESSOR}")
endif()
```

**The only problem** is that in the case of "armv7l" arch, there is no way to just specify TARGET=arm32 because we don't have an arm32_makefile.inc file.

This is not a huge issue, and I image the rpi makefile should just works but why not generalizing it?

**Comment by NominBa** [comment]
@Namburger  do you have any solution for this problem?
