### ISSUE TITLE
Quantization give float32 weights(instead of int8)  on TF 2.2.0-rc2

### ISSUE THREAD

**Issue by gggekov** [tensorflow/tensorflow#38392]
**System information**
- Google colab
- TF version: 2.2.0-rc2

**Problem summary**
Running the `hello_world` application for TFLite for Microcontrolllers. A model is generated successfully. The model is supposed to be quantized but the weights of all layers are `float32` and not `int8`. I am unable to generate a truly quantized model with `int8` weights. 
Getting the same problem in TF 2.1.0

**Command used to run the converter or code if you’re using the Python API**

```
https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/hello_world/create_sine_model.ipynb
```

**Also, please include a link to the saved model or GraphDef**

```
http://s000.tinyupload.com/?file_id=25815880594812659996
```

**Failure details**
The mode is supposed to be quantized. However, the weights of the model are `float32`
How can I obtain a truly quantized model?

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.2.0rc2](https://colab.research.google.com/gist/amahendrakar/49d0957ae877a81a8b6feb0c40d95c76/38392.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/b5c2024a9ff99baa576a1ba97c583e04/38392-tf-nightly.ipynb). Please find the attached gist. Thanks!

![Screenshot 2020-04-13 at 11 55 51 AM](https://user-images.githubusercontent.com/57165142/79099033-dfaa7e80-7d80-11ea-80d6-ebd96549da9e.png)

**Comment by amahendrakar** [comment]
@gggekov,
Could you please check [this comment](https://github.com/tensorflow/tensorflow/issues/38104#issuecomment-607560564) from a similar issue and let us know if it works? Thanks!

**Comment by amahendrakar** [comment]
> @gggekov,
> Could you please check [this comment](https://github.com/tensorflow/tensorflow/issues/38104#issuecomment-607560564) from a similar issue and let us know if it works? Thanks!

Any updates regarding this issue? Thanks!

**Comment by gggekov** [comment]
@amahendrakar 
Apologies for the delayed reply. Yes, I confirm appling tensor bigger than 1024 solves the issue. 

Best,
George
