### ISSUE TITLE
Keras `model_from_json` ignores distribution strategy

### ISSUE THREAD

**Issue by dvbuntu** [tensorflow/tensorflow#38396]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): CentOS 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: N/A
- TensorFlow installed from (source or
binary): Binary
 - TensorFlow version (use command below): 
- Python version: 2.0.1
 - Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from
source):  N/A
- CUDA/cuDNN version: 10.0
- GPU model and memory: Tesla V100 (affects multiple sizes)

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

When loading a model using `tf.keras.models.model_from_json`, TensorFlow ignores the distribution strategy.  If you try to train or predict with such a loaded model with a `MirroredStrategy`, for example, it will still only use a single GPU.

**Describe the expected behavior**

`tf.keras.models.model_form_json` should use the provided strategy scope and distribute accordingly.

**Standalone code to reproduce the issue** 

First we'll make a silly model, here with a strategy and verify it uses it properly.  How we create it here, however, is irrelevant to the strategy under which we load it later.

```python
import tensorflow as tf
import numpy as np

## silly model of sufficient size to notice spike in memory
with tf.distribute.MirroredStrategy().scope():
    m = tf.keras.models.Sequential()
    m.add(tf.keras.layers.Conv2D(256,5, input_shape=(256,256,1)))
    m.add(tf.keras.layers.Conv2D(256,5))
    m.add(tf.keras.layers.Conv2D(256,5))
    m.add(tf.keras.layers.Conv2D(256,5))
    m.add(tf.keras.layers.Conv2D(256,5))
    m.add(tf.keras.layers.Conv2D(256,5))
    m.add(tf.keras.layers.Conv2D(256,5))
    m.compile(optimizer='sgd', loss='mse')

## save model to json
with open('foo_model.json','w') as f:
    print(m.to_json(), file=f)

## test that we're using multiple GPUs
data = np.random.random(size=(1024,256,256,1))
data = np.array(data,dtype=np.float32)

ans = m.predict(data) # observe multiple GPUs spike in memory and utilization
```

Now, we load the saved model, using MirroredStrategy, but we find that TensorFlow ignores this strategy.  It seems to load the models initially onto all available GPUs (taking up a nominal amount of memory), but then only does computations on a single GPU.  The data never makes it to multiple GPUs, slowing down computations and causing memory problems.

```python
import tensorflow as tf
import numpy as np

data = np.random.random(size=(1024,256,256,1))
data = np.array(data,dtype=np.float32)

with open('foo_model.json','r') as f:
    J = f.read()

# use a strategy, see it be ignored
with tf.distribute.MirroredStrategy().scope():
    m = tf.keras.models.model_from_json(J) # see modest spike in memory as seems to load onto multiple gpu

ans = m.predict(data) # only a single GPU receives data
```

I understand that loading from a TF-saved model is supposed to work.  Because of other TensorFlow bugs, however, I have to save my models in the portable JSON format.  I believe this more or less rebuilds the whole model and reloads weights.  That should mean that the strategy gets applied properly, but we see that's not the case.  Is `model_from_json` overwriting or otherwise ignoring the strategy somewhere?

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by k-w-w** [comment]
Hi Anjali, can you take a look? The model appears to have a distribution strategy (`m2._distribution_strategy` = mirrored stratetgy), and the variables are mirrored, so I'm not sure why the model isn't utilizing the GPU.

**Comment by dvbuntu** [comment]
@k-w-w I think `m2._distribution_strategy` *doesn't* get set correctly is the problem.  It's set fine in the initial model creation.  If you check after loading, however, it's `None`.

But you gave me an idea for a workaround that I think resolves this:

```python
strat = tf.distribute.MirroredStrategy()
with strat.scope():
    m = tf.keras.models.model_from_json(J)

if m._distribution_strategy is None:
    m._distribution_strategy = strat
    m._distributed_function_cache = {}
    m._distributed_model_cahce = {}
```

A quick test with this showed multiple GPUs being used.  This is fine for my purposes.

The underlying issue, I suspect, is the Keras deserialization isn't aware of distribution strategies.  I poked around in the code base but it wasn't clear the fix might need to go.  Maybe [here](https://github.com/tensorflow/tensorflow/blob/e5bf8de410005de06a7ff5393fafdf832ef1d4ad/tensorflow/python/keras/utils/generic_utils.py#L281)

**Comment by k-w-w** [comment]
Hmm, this might be a bug with an earlier version of Tensorflow. I tried running it in colab (which is currently on version 2.2.0-rc3), and the `_distribution_strategy` attribute is set correctly. Can you try updating and checking again?

**Comment by dvbuntu** [comment]
Unfortunately I don't have administrative privileges where I run TF, so I'm unable to try this with a different version.  Are you saying this is already fixed in 2.2.0?

**Comment by k-w-w** [comment]
I'm not able to test the GPU utilization but I believe it should be.

**Comment by nikitamaia** [comment]
Hi @dvbuntu, just ran a quick test and it seems the problem is fixed. Have you had a chance to try this out with a more recent version of TF?
