### ISSUE TITLE
TensorFlow works with python, Jupyter notebook, but not iPython

### ISSUE THREAD

**Issue by fjdu** [tensorflow/tensorflow#3839]
Operating System: OS X EL Capitan 10.11.5

I installed TensorFlow with Anaconda following https://www.tensorflow.org/versions/r0.10/get_started/index.html

Specifically, I created a `tensorflow` environment, and used `pip` to install the one with **GPU support**.

After activating the environment, I am able to use TensowFlow in `python` and `jupyter notebook` (actually, I have to _turn off the hard ware acceleration of the Chrome browser_ to run TensorFlow correctly), but not in `ipython`:

`which ipython`
~/anaconda/envs/tensorflow/bin/ipython

`ipython --version`
5.1.0

`ipython -c "import tensorflow; print(tensorflow.__version__)"`
...
ImportError: dlopen(~/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.7.5.dylib
  Referenced from: ~/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found

`ls -l /Developer/NVIDIA/CUDA-7.5/lib/libcud*`

-rw-r--r-- 1 root wheel 563K Apr 13 02:02 "/Developer/NVIDIA/CUDA-7.5/lib/libcudart_static.a"
lrwxr-xr-x 1 root wheel   19 Apr 13 02:02 "/Developer/NVIDIA/CUDA-7.5/lib/libcudart.dylib" -> "libcudart.7.5.dylib"
-rwxr-xr-x 1 root wheel 272K Apr 13 02:02 "/Developer/NVIDIA/CUDA-7.5/lib/libcudart.7.5.dylib"
-rw-r--r-- 1 root wheel 299K Apr 13 02:02 "/Developer/NVIDIA/CUDA-7.5/lib/libcudadevrt.a"

`ls -l /usr/local/cuda/lib/`
total 165M
-rwxr-xr-x 1 root wheel 8.1K Apr 13 02:02 "libcuda.dylib"
lrwxr-xr-x 1 root wheel   36 Apr 13 02:03 "stubs" -> "/Developer/NVIDIA/CUDA-7.5/lib/stubs"
...
-rw-r--r-- 1 root wheel  53M Aug 15 21:17 "libcudnn_static.a"
-rwxr-xr-x 1 root wheel  56M Aug 15 21:17 "libcudnn.dylib"
-rwxr-xr-x 1 root wheel  56M Aug 15 21:17 "libcudnn.5.dylib"
lrwxr-xr-x 1 root wheel   13 Aug 15 21:29 "libcuda.1.dylib" -> "libcuda.dylib"

`which python`
~/anaconda/envs/tensorflow/bin/python

`python -c "import tensorflow; print(tensorflow.__version__)"`

I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.1.dylib locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.dylib locally
0.10.0rc0

**Comment by hholst80** [comment]
Just to make sure, you're not starting `ipython` from within the TensorFlow source directory are you?

**Comment by fjdu** [comment]
I am starting `ipython` from the home directory, and changing the starting directory does not seem to matter.

**Comment by yaroslavvb** [comment]
http://stackoverflow.com/questions/38768620/installing-a-package-in-conda-environment-but-only-works-in-python-not-ipython/38771575#38771575

**Comment by fjdu** [comment]
That was the way I installed ipython; and the error is "image not found", not "there is no module tensorflow".

**Comment by yaroslavvb** [comment]
Oh right, my bad. Is your DYLD_LIBRARY_PATH/LD_LIBRARY_PATH and current directory the same for when you try in python vs ipython? The brute-force approach is to run under dtruss to see where it's looking for the file. Also there's a related issue of that image being not found due to System Integrity Protection in El Capitan, but there should be another message starting with `dyld: warning` in the logs

**Comment by fjdu** [comment]
`echo $DYLD_LIBRARY_PATH`
/usr/local/cuda/lib:/Developer/NVIDIA/CUDA-7.5/lib:
`echo $LD_LIBRARY_PATH`
/usr/local/cuda/lib:/Developer/NVIDIA/CUDA-7.5/lib:
(There may be some redundancy here in these PATHs.)

I do not see any `dyld: warning` when doing import tensorflow.

`dtruss` does not seem to work in my case due to a `codesign` problem (never used that before; does that require an apple developer membership?).

**Comment by aselle** [comment]
You can also set DYLD_PRINT_ENV and DYLD_PRINT_LIBRARIES env variables (see man dyld).  One thing to note is that on El Capitan DYLD_LIBRARY_PATH is not inherited for protected binaries. See e.g.
http://apple.stackexchange.com/questions/215030/el-capitan-make-check-dyld-library-path
So if you are in protected mode that might be causing it to be ignored.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen if further information becomes available.
