### ISSUE TITLE
32-bit architecture support?

### ISSUE THREAD

**Issue by vmayoral** [tensorflow/tensorflow#384]
There's some discussion [pointer](http://stackoverflow.com/questions/33752772/tensorflow-on-raspberry-pi) pointing out that TensorFlow only supports 64 bit architectures. Is this correct?

Can someone confirm, that given the right dependencies are met, TensorFlow could also run in 32-bit machines?

Thanks,

**Comment by maxcuda** [comment]
I have TensorFlow running on Arm 32bit ( Jetson TK1) and it seems to work fine.
You can see my instructions on how to build it at:
http://cudamusing.blogspot.com/2015/11/building-tensorflow-for-jetson-tk1.html

**Comment by vrv** [comment]
@maxcuda: thanks for doing that work!

Some of those changes (the ifdef ones) might be worth integrating into TensorFlow -- feel free to send us a change via Gerrit.  Not sure what to do about the nvcc failures though -- hopefully a newer version of nvcc might help.

**Comment by vmayoral** [comment]
Thanks for sharing @maxcuda. Pretty cool. I'm experiencing some issues while compiling bazel though (Java heap space). 

https://github.com/bazelbuild/bazel/issues/606#issuecomment-159749768

Did you see something similar?

**Comment by maxcuda** [comment]
No, I haven't seen the heap problem compiling Bazel.

**Comment by vmayoral** [comment]
Have succeeded. Thanks for the support.
