### ISSUE TITLE
Smart Reply AAR example for tensorflow lite won't build 

### ISSUE THREAD

**Issue by amitDaMan** [tensorflow/tensorflow#38402]
I have not changed any code, and followed the procedure as per: https://github.com/tensorflow/examples/blob/master/lite/examples/smart_reply/android/how-to-build.md

I tried to build on Windows, and Linux (16.04) and I get the following error from bazel: 
Linux: 
amsha@amsha-linux:/local/mnt/workspace/workspace/tensorflowliteExamples/smartReply/examples/lite/examples/smart_reply/android/app$ bazel build libs/cc:smartreply_runtime_aar
WARNING: Output base '/usr2/amsha/.cache/bazel/_bazel_amsha/09e97388c3884f6fff92e89b26f572b5' is on NFS. This may lead to surprising failures and undetermined behavior.
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/316e6133888bfc39fb860a4f1a31cfcbae485aef.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: /local/mnt/workspace/workspace/tensorflowliteExamples/smartReply/examples/lite/examples/smart_reply/android/app/libs/cc/BUILD:163:1: //libs/cc:smartreply_runtime_aar_dummy_app_for_so: no such attribute 'aapt_version' in 'android_binary' rule
ERROR: error loading package 'libs/cc': Package 'libs/cc' contains errors
INFO: Elapsed time: 0.401s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

Windows:
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/316e6133888bfc39fb860a4f1a31cfcbae485aef.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: C:/workspace/bazelbuilds/smart_reply/android/app/libs/cc/BUILD:163:1: //libs/cc:smartreply_runtime_aar_dummy_app_for_so: no such attribute 'aapt_version' in 'android_binary' rule
ERROR: error loading package 'libs/cc': Package 'libs/cc' contains errors
INFO: Elapsed time: 88.009s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)

**Comment by amitDaMan** [comment]
I am not too familiar with the bazel build system, however in:
https://github.com/tensorflow/examples/blob/master/lite/examples/smart_reply/android/app/WORKSPACE

the WORKSPACE file makes a reference to:
https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/316e6133888bfc39fb860a4f1a31cfcbae485aef.tar.gz

which gives a 404, rather then a tar.gz

**Comment by lintian06** [comment]
Hi Amit, 

Let me take a look at this and come back to you.

In general, if you just want to use gradle to build the app, you may download prebuilt AAR and forget about bazel (it is a [optional step](https://github.com/tensorflow/examples/blob/master/lite/examples/smart_reply/android/how-to-build.md#optional-how-to-build-aar-package-from-source-code)). That is done by gradle.

**Comment by lintian06** [comment]
Hi Amit,

The problem is from bazel, the build tool. The latest bazel remove this attributes "aapt_version". I guess you must be using bazel >= 2.0. 

As TensorFlow has a minimum version requirement of 0.19, it is [this](https://github.com/tensorflow/tensorflow/commit/c5dce1fd008d7e13ea8b735b80281867a38c9aef) causing the breaking change with the bazel, while our dependency didn't update it.

**A quick solution:** If you build custom ops with current C++ code, you can use bazel **1.x.x** (from [release(https://github.com/bazelbuild/bazel/releases), or https://bazel.build.

At the same time, we will figure out dependency update from our side. :-)

**Comment by amitDaMan** [comment]
Okay, I will try again with an old version of bazel. 

I have edited the C++ code so I can pass in which device to use (nnapi, gpu, cpu, number of threads, etc), and I have added a few instrumented tests. So, that would require me to rebuild the AAR.

I have some related questions.

In android studio the default build tool for jni/native apps is CMAKE, and android studio has tooling such that, I can step into the C++ code, use watchlists, etc.

What is the recommended (your own personal), work flow for making these types of native apps. 
Do you write the C++ in android studio, or VS Code, or something else. Are you building from commandline (using bazel)? How do you debug your native code in your workflow? Do you use a fully featured debugger?

There are a couple external dependencies in this project, tf lite, RE2, flatbuffers. I was in the middle of rebuilding this app in CMAKE. But then I realized the .a I made for RE2 was not made for arm64 devices. (I am a bit new to cmake and c++ in general)

Do you recommend using bazel for such tasks? I believe I will just bite the bullet and transition to bazel since its the build tool of tensorflow lite (and I see many other google/android github projects using it). Do you have a recommended environment for writing bazel code, or do you do it in a regular text editor and just check for errors by running it. 

Then on the topic of custom ops. 

There are two ways that I see of writing custom ops. You write the ops and then register them in your C++ code. Or, if you are doing everything in java/kotlin you can put your code in a specific file location and build a custom tflite .aar.

However, in this project, I am unsure how the custom ops are being registered. I understand "RegisterSelectedOps" is related, but I cant find the documentation for it. 

I see that "RegisterSelectedOps" should be overridden, but where is that happening? I suspect it has to do with the build system, and how the .aar is constructed. In that regard, I am sure I will figure it out as my bazel skills increase, but if you have any incite for me, that would be appreciated. 

Again, thank you for your time, and answering my questions, and any additional advice you have.

**Comment by amitDaMan** [comment]
Fresh projects with no code changes:

I used bazel 1.2.1 on windows, and I get some error related to com_google_protobuf.
Is this project supported on windows?

On ubuntu I had 3.0.0 installed, I then used "sudo apt-get --purge remove bazel" to uninstall.
Then followed:
https://docs.bazel.build/versions/master/install-ubuntu.html
to install bazel-1.0.0, and then I renamed it to bazel in usr/bin/ 
and got a error related to "'libs/cc/testdata': BUILD file not found in any of the following directories."
Which is true, there is no build file there, there is a build file located in the parent directory. 

I will learn bazel, to better debug these issues. Its a bit inconvenient dealing with an older version of bazel. 

Full error messages: 
On Windows:
C:\workspace\SmartReplyRebuild\CleanSmartReply\examples\lite\examples\smart_reply\android\app>bazel version
Build label: 1.2.1
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Nov 26 15:24:17 2019 (1574781857)
Build timestamp: 1574781857
Build timestamp as int: 1574781857

C:\workspace\SmartReplyRebuild\CleanSmartReply\examples\lite\examples\smart_reply\android\app>bazel build libs/cc:smartreply_runtime_aar
INFO: Call stack for the definition of repository 'com_google_protobuf' which is a tf_http_archive (rule definition at C:/users/amsha/_bazel_amsha/sqsdm6y6/external/org_tensorflow/third_party/repo.bzl:121:19):
 - C:/users/amsha/_bazel_amsha/sqsdm6y6/external/org_tensorflow/tensorflow/workspace.bzl:434:5
 - C:/workspace/smartreplyrebuild/cleansmartreply/examples/lite/examples/smart_reply/android/app/WORKSPACE:39:1
INFO: Repository 'com_google_protobuf' used the following cache hits instead of downloading the corresponding file.
 * Hash 'b9e92f9af8819bbbc514e2902aec860415b70209f31dfc8c4fa72515a5df9d59' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/protocolbuffers/protobuf/archive/310ba5ee72661c081129eb878c1bbcec936b20f0.tar.gz
If the definition of 'com_google_protobuf' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'com_google_protobuf':
   Traceback (most recent call last):
        File "C:/users/amsha/_bazel_amsha/sqsdm6y6/external/org_tensorflow/third_party/repo.bzl", line 101
                _apply_patch(ctx, <1 more arguments>)
        File "C:/users/amsha/_bazel_amsha/sqsdm6y6/external/org_tensorflow/third_party/repo.bzl", line 67, in _apply_patch
                _wrap_bash_cmd(ctx, <1 more arguments>)
        File "C:/users/amsha/_bazel_amsha/sqsdm6y6/external/org_tensorflow/third_party/repo.bzl", line 28, in _wrap_bash_cmd
                fail(<1 more arguments>)
BAZEL_SH environment variable is not set
INFO: Call stack for the definition of repository 'remotejdk11_win' which is a http_archive (rule definition at C:/users/amsha/_bazel_amsha/sqsdm6y6/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - C:/users/amsha/_bazel_amsha/sqsdm6y6/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:249:1
INFO: Call stack for the definition of repository 'remote_java_tools_windows' which is a http_archive (rule definition at C:/users/amsha/_bazel_amsha/sqsdm6y6/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - C:/users/amsha/_bazel_amsha/sqsdm6y6/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:270:1
INFO: Call stack for the definition of repository 'android_tools' which is a http_archive (rule definition at C:/users/amsha/_bazel_amsha/sqsdm6y6/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /DEFAULT.WORKSPACE.SUFFIX:343:1
ERROR: Analysis of target '//libs/cc:smartreply_runtime_aar' failed; build aborted: no such package '@com_google_protobuf//': Traceback (most recent call last):
        File "C:/users/amsha/_bazel_amsha/sqsdm6y6/external/org_tensorflow/third_party/repo.bzl", line 101
                _apply_patch(ctx, <1 more arguments>)
        File "C:/users/amsha/_bazel_amsha/sqsdm6y6/external/org_tensorflow/third_party/repo.bzl", line 67, in _apply_patch
                _wrap_bash_cmd(ctx, <1 more arguments>)
        File "C:/users/amsha/_bazel_amsha/sqsdm6y6/external/org_tensorflow/third_party/repo.bzl", line 28, in _wrap_bash_cmd
                fail(<1 more arguments>)
BAZEL_SH environment variable is not set
INFO: Elapsed time: 6.725s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: @org_tensorflow//tensorflow


on ubuntu:

amsha@amsha-linux:/local/mnt/workspace/workspace/tfliteExample/SmartReply/examples/lite/examples/smart_reply/android/app$ bazel build libs/cc:smartreply_runtime_aar
WARNING: Output base '/usr2/amsha/.cache/bazel/_bazel_amsha/a55405c8a948a2ec30cda52a5973c4a9' is on NFS. This may lead to surprising failures and undetermined behavior.
INFO: Writing tracer profile to '/usr2/amsha/.cache/bazel/_bazel_amsha/a55405c8a948a2ec30cda52a5973c4a9/command.profile.gz'
ERROR: /local/mnt/workspace/workspace/tfliteExample/SmartReply/examples/lite/examples/smart_reply/android/app/libs/cc/BUILD:17:1: no such package 'libs/cc/testdata': BUILD file not found in any of the following directories.
 - /local/mnt/workspace/workspace/tfliteExample/SmartReply/examples/lite/examples/smart_reply/android/app/libs/cc/testdata and referenced by '//libs/cc:smartreply_ops'
ERROR: Analysis of target '//libs/cc:smartreply_runtime_aar' failed; build aborted: no such package 'libs/cc/testdata': BUILD file not found in any of the following directories.
 - /local/mnt/workspace/workspace/tfliteExample/SmartReply/examples/lite/examples/smart_reply/android/app/libs/cc/testdata
INFO: Elapsed time: 0.333s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
    currently loading: @org_tensorflow//tensorflow/lite/schema
amsha@amsha-linux:/local/mnt/workspace/workspace/tfliteExample/SmartReply/examples/lite/examples/smart_reply/android/app$

**Comment by lintian06** [comment]
Hi Amit,

For your Ubuntu case, I also find this too: libs/cc/testdata/BUILD is mistakenly removed. Here is the content:
```# libs/cc/testdata/BUILD
package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],  # Apache 2.0
)

exports_files(glob(["*"]))

filegroup(
    name = "testdata",
    srcs = glob([
        "**/*",
    ])
)
```

(Requires [step 1](https://github.com/tensorflow/examples/blob/master/lite/examples/smart_reply/android/how-to-build.md#step-1-download-pre-built-aar-package-containing-custom-ops) to download smartreply.tflite to that testdata folder)

It fixes the problem from my side.

FYI, a patch is ongoing to fix this and also update dependencies for bazel. :-)

**Comment by amitDaMan** [comment]
Okay, I will add the missing project files... and see if that works...

Any further comments on my previous questions would be appreciated.

**Comment by lintian06** [comment]
Bazel is the open source build tool by Google, which supports cross platforms and language compilation. The BUILD of Bazel resolves external dependencies from other libraries. TensorFlow uses this, so if your changes need to depends on deep changes or customization related, it is recommended. (FYI, we are planning to provide more examples with other build system, in particular for those example applications in this repo.)

There is a tutorial [Building Android Apps with Bazel](https://codelabs.developers.google.com/codelabs/bazel-android-intro/index.html?index=..%2F..index#0). However, we provide gradle for the example apps is mainly because it is more common for Android development.

Tests guard the correctness of each component, so whatever text editor or IDEs should be fine. It is free for you to choose different tools for each part and put them together. My suggestion is that you may use Bazel to custom ops and lower-level interface to build AAR, and use gradle to create Android app. Our c/c++ interface contains the richest utilities for customization.

**Comment by amitDaMan** [comment]
Fresh Build:

On Ubuntu: works
On Windows: com_google_protobuf related error

full error:
C:\workspace\SmartReplyRebuild\CleanSmartReply\examples\lite\examples\smart_reply\android\app>bazel build libs/cc:smartreply_runtime_aar
INFO: Call stack for the definition of repository 'com_google_protobuf' which is a tf_http_archive (rule definition at C:/users/amsha/_bazel_amsha/sqsdm6y6/external/org_tensorflow/third_party/repo.bzl:121:19):
 - C:/users/amsha/_bazel_amsha/sqsdm6y6/external/org_tensorflow/tensorflow/workspace.bzl:434:5
 - C:/workspace/smartreplyrebuild/cleansmartreply/examples/lite/examples/smart_reply/android/app/WORKSPACE:39:1
INFO: Repository 'com_google_protobuf' used the following cache hits instead of downloading the corresponding file.
 * Hash 'b9e92f9af8819bbbc514e2902aec860415b70209f31dfc8c4fa72515a5df9d59' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/protocolbuffers/protobuf/archive/310ba5ee72661c081129eb878c1bbcec936b20f0.tar.gz
If the definition of 'com_google_protobuf' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'com_google_protobuf':
   Traceback (most recent call last):
        File "C:/users/amsha/_bazel_amsha/sqsdm6y6/external/org_tensorflow/third_party/repo.bzl", line 101
                _apply_patch(ctx, <1 more arguments>)
        File "C:/users/amsha/_bazel_amsha/sqsdm6y6/external/org_tensorflow/third_party/repo.bzl", line 67, in _apply_patch
                _wrap_bash_cmd(ctx, <1 more arguments>)
        File "C:/users/amsha/_bazel_amsha/sqsdm6y6/external/org_tensorflow/third_party/repo.bzl", line 28, in _wrap_bash_cmd
                fail(<1 more arguments>)
BAZEL_SH environment variable is not set
INFO: Call stack for the definition of repository 'remote_java_tools_windows' which is a http_archive (rule definition at C:/users/amsha/_bazel_amsha/sqsdm6y6/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - C:/users/amsha/_bazel_amsha/sqsdm6y6/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:270:1
INFO: Call stack for the definition of repository 'remotejdk11_win' which is a http_archive (rule definition at C:/users/amsha/_bazel_amsha/sqsdm6y6/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - C:/users/amsha/_bazel_amsha/sqsdm6y6/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:249:1
INFO: Call stack for the definition of repository 'android_tools' which is a http_archive (rule definition at C:/users/amsha/_bazel_amsha/sqsdm6y6/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /DEFAULT.WORKSPACE.SUFFIX:343:1
ERROR: Analysis of target '//libs/cc:smartreply_runtime_aar' failed; build aborted: no such package '@com_google_protobuf//': Traceback (most recent call last):
        File "C:/users/amsha/_bazel_amsha/sqsdm6y6/external/org_tensorflow/third_party/repo.bzl", line 101
                _apply_patch(ctx, <1 more arguments>)
        File "C:/users/amsha/_bazel_amsha/sqsdm6y6/external/org_tensorflow/third_party/repo.bzl", line 67, in _apply_patch
                _wrap_bash_cmd(ctx, <1 more arguments>)
        File "C:/users/amsha/_bazel_amsha/sqsdm6y6/external/org_tensorflow/third_party/repo.bzl", line 28, in _wrap_bash_cmd
                fail(<1 more arguments>)
BAZEL_SH environment variable is not set
INFO: Elapsed time: 6.728s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: @org_tensorflow//tensorflow

**Comment by amitDaMan** [comment]
In the readme, it should be noted that it doesn't work on windows, and that an old version of bazel is needed, presently.

Also, yes I have done the bazel tutorial on the getting started page... and I understand the concept of tests. Thanks for the advice...

And, I guess I will just have to read the codebase to figure out the rich C++ feature set...

**Comment by lintian06** [comment]
Hi Amit, 

We updated the custom ops AAR dependencies, and polished the [guidance](https://github.com/tensorflow/examples/blob/master/lite/examples/smart_reply/android/how-to-build.md#optional-how-to-build-aar-package-from-source-code). You may follow it to build your own AAR. Please let us know if you have any question. Thanks!

**Comment by amitDaMan** [comment]
Hi Tian,
Why is the .aar that I built twice the size of the default .aar (I have not included any of my additional code).

I also tried the '-c opt' option as specified:

"bazel build -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a cc:smartreply_runtime_aar"

which is also wrong, it should be:
bazel build -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a **libs/**cc:smartreply_runtime_aar

Thank you for the time.
