### ISSUE TITLE
[tf-2.2] XNNPack doesn't compile on AArch64

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#38400]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspberry Pi 4 or cross-compiling on Ubuntu 18.04 using #38399
- TensorFlow installed from (source or binary): source
- TensorFlow version: r2.2 branch 
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): Arm gcc 9.2.1

**Describe the problem**
Currently XNNPack on the TensorFlow 2.2 branch doesn't compile on AArch64. When trying to compile the TFLite benchmark binary for the Raspberry PI 4 64-bit, compilation fails with:
```
ERROR: /root/.cache/bazel/_bazel_root/ba9f8c20da37904a26a4b29ac8536dec/external/XNNPACK/BUILD.bazel:1643:1: C++ compilation of rule '@XNNPACK//:neonfp16arith_ukernels' failed (Exit 1)
external/XNNPACK/src/f16-spmm/gen/32x1-neonfp16arith-unroll2.c: In function 'xnn_f16_spmm_ukernel_32x1__neonfp16arith_unroll2':
external/XNNPACK/src/f16-spmm/gen/32x1-neonfp16arith-unroll2.c:219:59: error: incompatible type for argument 1 of 'vreinterpret_f32_f16'
  219 |             const float16x4_t va01 = vreinterpret_f32_f16(vld1_dup_f32(__builtin_assume_aligned(a, 1)));
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                           |
      |                                                           float32x2_t
In file included from external/XNNPACK/src/f16-spmm/gen/32x1-neonfp16arith-unroll2.c:12:
/root/.cache/bazel/_bazel_root/ba9f8c20da37904a26a4b29ac8536dec/external/aarch64_compiler/bin/../lib/gcc/aarch64-none-linux-gnu/9.2.1/include/arm_neon.h:4176:35: note: expected 'float16x4_t' but argument is of type 'float32x2_t'
 4176 | vreinterpret_f32_f16 (float16x4_t __a)
      |                       ~~~~~~~~~~~~^~~
external/XNNPACK/src/f16-spmm/gen/32x1-neonfp16arith-unroll2.c:227:76: error: incompatible type for argument 1 of 'vreinterpret_f16_f32'
  227 |         vst1_lane_f32(__builtin_assume_aligned(c, 1), vreinterpret_f16_f32(vout01), 0);
      |                                                                            ^~~~~~
      |                                                                            |
      |                                                                            float16x4_t
In file included from external/XNNPACK/src/f16-spmm/gen/32x1-neonfp16arith-unroll2.c:12:
/root/.cache/bazel/_bazel_root/ba9f8c20da37904a26a4b29ac8536dec/external/aarch64_compiler/bin/../lib/gcc/aarch64-none-linux-gnu/9.2.1/include/arm_neon.h:4022:35: note: expected 'float32x2_t' but argument is of type 'float16x4_t'
 4022 | vreinterpret_f16_f32 (float32x2_t __a)
      |                       ~~~~~~~~~~~~^~~
Target //tensorflow/lite/tools/benchmark:benchmark_model failed to build
```
I believe this problem was fixed in https://github.com/google/XNNPACK/commit/d21fdcb4af35a8764333c3bb24fa54c55bb5db52 and tensorflow master compiles without a problem.

Since AArch64 was supported in TF 2.1, @Maratyszcza do you think it would be possible to backport the fixes to the 2.2 release branch?

It probably will be enough to cherry-pick 06ca7fc73ca96d9a468d771273be377ed4cc6ed2 and cd59b293b5b7f9f337ba37becdb850e1278ac0c0 in order to upgrade XNNPack, but not sure if this would have any side effects.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

This can be reproduced on a normal linux system by using the cross-compile toolchain from PR #38399 and compiling the TFLite benchmark binary using:
```
bazelisk build -c opt tensorflow/lite/tools/benchmark:benchmark_model \
    --cpu=aarch64 --crosstool_top=@local_config_arm_compiler//:toolchain
```

**Comment by Maratyszcza** [comment]
Doesn't #38131 solve it already?

**Comment by Maratyszcza** [comment]
Generally, cherry-picking commits which update XNNPACK/pthreadpool/cpuinfo is safe. XNNPACK maintains backward-compatible API for TensorFlow Lite.

**Comment by lgeiger** [comment]
> Doesn't #38131 solve it already?

#38131 solved part of the problem, but unfortunately it still failed later in the compilation due to the gcc error mentioned above.

**Comment by Maratyszcza** [comment]
You may try to add `--copt=-flax-vector-conversions` to Bazel command

**Comment by lgeiger** [comment]
Thanks for the help

> You may try to add `--copt=-flax-vector-conversions` to Bazel command

Unfortunately this doesn't seem to help, I still get the same error.

**Comment by lgeiger** [comment]
#38436 Fixes the issues for us, though not sure if there is a more elegant solution.

**Comment by lgeiger** [comment]
#38436 has been merged, so this issue is resolved. Thanks for the help and the fast review.

**Comment by le8888e** [comment]
Hi @Maratyszcza ,

I installed tf-nightly 2.4 by pip. Would XNNPACK complied by default? How can I check it? 

Thank you
