### ISSUE TITLE
Tensorflow Datasets with string inputs do not preserve data type

### ISSUE THREAD

**Issue by desertnaut** [tensorflow/tensorflow#38409]
All **reproducible** code below is run at **Google Colab** with **TF 2.2.0-rc2**.

Adapting the simple example from the [documentation][1] for creating a dataset from a simple Python list:

    import numpy as np
    import tensorflow as tf
    tf.__version__
    # '2.2.0-rc2'
    np.version.version
    # '1.18.2'

    dataset1 = tf.data.Dataset.from_tensor_slices([1, 2, 3]) 
    for element in dataset1: 
      print(element) 
      print(type(element.numpy()))

we get the result

    tf.Tensor(1, shape=(), dtype=int32)
    <class 'numpy.int32'>
    tf.Tensor(2, shape=(), dtype=int32)
    <class 'numpy.int32'>
    tf.Tensor(3, shape=(), dtype=int32)
    <class 'numpy.int32'>

where all data types are `int32`, as expected.

But changing this simple example to feed a list of strings instead of integers:

    dataset2 = tf.data.Dataset.from_tensor_slices(['1', '2', '3']) 
    for element in dataset2: 
      print(element) 
      print(type(element.numpy()))

gives the result

    tf.Tensor(b'1', shape=(), dtype=string)
    <class 'bytes'>
    tf.Tensor(b'2', shape=(), dtype=string)
    <class 'bytes'>
    tf.Tensor(b'3', shape=(), dtype=string)
    <class 'bytes'>

where, surprisingly, and despite the tensors themselves being of `dtype=string`, their evaluations are of type `bytes`.

This behavior is not confined to the `.from_tensor_slices` method; here is the situation with [`.list_files`][2] (the following snippet runs straightforward in a fresh Colab notebook):

    disc_data = tf.data.Dataset.list_files('sample_data/*.csv') # 4 csv files
    for element in disc_data: 
      print(element) 
      print(type(element.numpy()))

the result being:

    tf.Tensor(b'sample_data/california_housing_test.csv', shape=(), dtype=string)
    <class 'bytes'>
    tf.Tensor(b'sample_data/mnist_train_small.csv', shape=(), dtype=string)
    <class 'bytes'>
    tf.Tensor(b'sample_data/california_housing_train.csv', shape=(), dtype=string)
    <class 'bytes'>
    tf.Tensor(b'sample_data/mnist_test.csv', shape=(), dtype=string)
    <class 'bytes'>

where again, the file names in the evaluated tensors are returned as `bytes`, instead of `string`, despite that the tensors themselves are of `dtype=string`.

Similar behavior is observed also with the `.from_generator` method (not shown here).

A final demonstration: as shown in the `.as_numpy_iterator` method [documentation][3], the following equality condition is evaluated as `True`:

    dataset3 = tf.data.Dataset.from_tensor_slices({'a': ([1, 2], [3, 4]), 
                                                   'b': [5, 6]}) 

    list(dataset3.as_numpy_iterator()) == [{'a': (1, 3), 'b': 5}, 
                                           {'a': (2, 4), 'b': 6}] 
    # True

but if we change the elements of `b` to be strings, the equality condition is now surprisingly evaluated as `False`!

    dataset4 = tf.data.Dataset.from_tensor_slices({'a': ([1, 2], [3, 4]), 
                                                   'b': ['5', '6']})   # change elements of b to strings
    
    list(dataset4.as_numpy_iterator()) == [{'a': (1, 3), 'b': '5'},   # here
                                           {'a': (2, 4), 'b': '6'}]   # also
    # False

probably due to the different data types, since the values themselves are evidently identical.

---

I didn't stumble upon this behavior by academic experimentation; I am trying to pass my data to TF Datasets using custom functions that read pairs of files from the disk of the form

    f = ['filename1', 'filename2']

which custom functions work perfectly well on their own, but mapped through TF Datasets give

    RuntimeError: not a string

which, after this digging, seems at least not unexplained, if the returned data types are indeed `bytes` and not `string`.

So, is this a bug (as it seems), or am I missing something here?

  [1]: https://www.tensorflow.org/api_docs/python/tf/data/Dataset
  [2]: https://www.tensorflow.org/api_docs/python/tf/data/Dataset#list_files
  [3]: https://www.tensorflow.org/api_docs/python/tf/data/Dataset#as_numpy_iterator

**Comment by gadagashwini** [comment]
I was able to reproduce the issue with Tf2.2.rc2.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/3168075f641b7f19800665001d58c01f/untitled499.ipynb). Thanks!

**Comment by ymodak** [comment]
This happens due to `numpy()` operations on string inputs. I made a toy example to show
```python
import tensorflow as tf
import numpy
print(tf.__version__)

string = tf.constant('My string!')
print(string)

num_string = s.numpy()
print(type(num_string))
```
output:
```python
2.2.0-rc2
tf.Tensor(b'My string!', shape=(), dtype=string)
<class 'bytes'>
```

**Comment by desertnaut** [comment]
Is there something more expected from my side?

**Comment by Ceceu** [comment]
I have the same issue. Tensorflow when dealing with texts generates string tensors that are stored as byte string:

```python
<tf.Tensor: shape=(2,), dtype=string, numpy=array(
     [b'Thê first utf-8 string of the batçh.',
      b'Thê secônd utf-8 string of the batçh.'], dtype=object)>
```

However, I didn't find an efficient way to decode this kind of tensor as a list of strings. It's even worse if the byte string containing a non-ascii character as point in the tensor above.

What I really need is one of these two options:

1. a tokenizer which is able to accept aforementioned byte string tensor as input to tokenize; or
2. a vectorized approach to transforming a byte string tensor into a string list.

**Comment by jsimsa** [comment]
As per @ymodak's response, this is not a specific to tf.data functionality but behavior of `numpy()` method:

```
import numpy as np
import tensorflow as tf

x = tf.constant("hello")
print(x)
print(type(x.numpy()))
```

Please assign to someone on the TF core team for triage.

**Comment by meggamind** [comment]
I would like to help with this. I can pick up and triage the issue. 
(If there is someone who can help me if I have doubts, that'll be awesome)

**Comment by pesekon2** [comment]
This is connected to the fact that the function unfortunately changes everything to `int32` (at least when it comes to int-based numpy arrays). See #49503.

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210525, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/8b18fc13e3b76c8387fa9cfa7590b677/38409.ipynb). Thanks!

**Comment by OpenWaygate** [comment]
Is there any progress on this problem? I have same problem with tf 2.4.1.

**Comment by tilakrayal** [comment]
Was able to reproduce your issue in Tf v2.7 and Nightly 2.9.0-dev20211223, please find the gist [here](https://colab.research.google.com/gist/tilakrayal/288353aace5456f285877bf18f175061/untitled158.ipynb). Thanks!

**Comment by Jorgvt** [comment]
Ran into this error as well and circumvented it doing a type check in my generator, just in case it helps anyone:

`path_to_file = path_to_file.decode('UTF-8') if isinstance(path_to_file, bytes) else path_to_file`

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
