### ISSUE TITLE
shape_invariants in tf.while_loop

### ISSUE THREAD

**Issue by 17patelumang** [tensorflow/tensorflow#38412]
**System information** 
OS Platform and Distribution : macOS Catalina 10.15.3

TensorFlow installed from : binary

TensorFlow version : 1.15.2

Python version: 3.7.3

So basically i have 
`matrix = tf.constant([[[16,15,16,15,87],[3,4,3,4,87]],[[ 3,4,3,41,87],[0,0,0,0,0]]]) `

`b = tf.constant([[[1],[2]],[[1],[1]]])`

I want to 

I want vector c such that

[ 16 15 16 15 87] is repeated [1] times ,
[ 3 4 3 4 87] is repeated [2] times ,
[ 3 4 14 95 87] is repeated [2] times,
[ 3 7 9 250 87] is repated [2] times and so on ............

I am writing following code 

`import tensorflow as tf`

`tf.enable_eager_execution()`

`def repeatOperation2(t1,t2):`
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`xShape = tf.shape(t1)[0]`
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`reshaped  = tf.reshape(t1, [1, xShape])`
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`repeat = tf.repeat(reshaped, repeats=t2, axis=0)`
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`ta = tf.TensorArray(dtype=tf.int32, size=1)`
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`ta.write(0, repeat)`
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`ta_final_result = ta.stack()`
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`return ta_final_result`

`def repeatOperation1(t1,t2):`
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`matrix_rows = tf.shape(t1)[0]`
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`ta = tf.TensorArray(dtype=tf.int32, size=10)`
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`i0 = tf.constant(0)`
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`init_state = (i0, ta)`
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`condition = lambda i, _: i < matrix_rows`
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`body = lambda i, ta: (i + 1, ta.write(i, repeatOperation2(t1[i,:],t2[i,:])))`
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`n, ta_final = tf.while_loop(condition, body,init_state,shape_invariants=[i0.get_shape(), tf.TensorShape((None,None,5))])`
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`ta_final_result = ta_final.stack()`
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`return ta_final_result`

`matrix = tf.constant([[[16,15,16,15,87],[3,4,3,4,87]],[[ 3,4,3,41,87],[0,0,0,0,0]]]) `
`b = tf.constant([[[1],[2]],[[1],[1]]])`

`matrix_rows = tf.shape(matrix)[0]`
`ta = tf.TensorArray(dtype=tf.int32, size=matrix_rows)`
`init_state = (0, ta)`
`condition = lambda i, _: i < matrix_rows`
`body = lambda i, ta: (i + 1, ta.write(i, repeatOperation1(matrix[i,:,:],b[i,:,:])))`
`n, ta_final = tf.while_loop(condition, body, init_state)`
`ta_final_result = ta_final.stack()`
`print(ta_final_result)`

basically for each iteration multiplication i am using `shape_invariants=[i0.get_shape(), tf.TensorShape((None,None,5))])` since repeating matrix tensor equal to b tensor the number in first two dimension changes  but i am getting below error 

Error:

Traceback (most recent call last):
  File "tf_2.py", line 52, in <module>
    n, ta_final = tf.while_loop(condition, body, init_state)
  File "<path>/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2714, in while_loop
    loop_vars = body(*loop_vars)
  File "tf_2.py", line 51, in <lambda>
    body = lambda i, ta: (i + 1, ta.write(i, repeatOperation1(matrix[i,:,:],b[i,:,:])))
  File "tf_2.py", line 37, in repeatOperation1
    n, ta_final = tf.while_loop(condition, body, init_state,shape_invariants=[i0.get_shape(), tf.TensorShape((None,None,5))])
  File "<path>/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2714, in while_loop
    loop_vars = body(*loop_vars)
  File "tf_2.py", line 36, in <lambda>
    body = lambda i, ta: (i + 1, ta.write(i, repeatOperation2(t1[i,:],t2[i,:])))
  File "<path>/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/tensor_array_ops.py", line 1084, in write
    return self._implementation.write(index, value, name=name)
  File "<path>/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/tensor_array_ops.py", line 815, in write
    self._write(index, value)
  File "<path>/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/tensor_array_ops.py", line 805, in _write
    (value.shape, self._element_shape))
ValueError: Incompatible shape for value ((1, 2, 5)), expected ((1, 1, 5))

**Comment by 17patelumang** [comment]
We can close this ticket , solved in https://github.com/tensorflow/tensorflow/issues/38375

**Comment by amahendrakar** [comment]
> We can close this ticket , solved in #38375

Closing the issue as per user's comment.
