### ISSUE TITLE
r2.1 windows libtensorflow build failed

### ISSUE THREAD

**Issue by JinZhuXing** [tensorflow/tensorflow#38413]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10 (1909) x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): Source
- TensorFlow version: r2.1
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.29.1
- GCC/Compiler version (if compiling from source): MSVC 2019 Build Tool
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the problem**

I can't build tensorflow r2.1 as libtensorflow.
When I build source code it always failed with ProtoCompile ERROR. (Exit -1073741795)

**Provide the exact sequence of commands / steps that you executed before running into the problem**

First, installed msys and MSVC 2019 build tool. (Described in https://tensorflow.google.cn/install/source_windows)

And then, run bazel with following command.
.\bazel.exe build --config=opt //tensorflow/tools/lib_package:libtensorflow

**Build Error**
ERROR: D:/work/tensorflow/source/tensorflow/tensorflow/core/BUILD:2045:1: ProtoCompile tensorflow/core/protobuf/autotuning.pb.h failed (Exit -1073741795)
Target //tensorflow/tools/lib_package:libtensorflow failed to build
INFO: Elapsed time: 6.115s, Critical Path: 3.44s
INFO: 2 processes: 2 local.
FAILED: Build did NOT complete successfully

**Comment by Dave-Stein** [comment]
[Latest reasons](https://github.com/tensorflow/tensorflow/issues/39905#issuecomment-641588284) why nothing happens for last 6 months for Windows DLL for TF2.0, TF2.1 and TF2.2

**Comment by JinZhuXing** [comment]
I have already finished build.
Thank you.
