### ISSUE TITLE
Tensorflow-gpu not interacting with gpu after fresh install

### ISSUE THREAD

**Issue by Scathos** [tensorflow/tensorflow#38411]
**System information**
- Windows 10
- pip install
- TensorFlow-gpu==1.15.2
-python 3.7.6
- using conda and trying to run through spyder and ubuntu for windows
- Bazel version (if compiling from source): idk
- GCC/Compiler version (if compiling from source): idk
- CUDA/cuDNN version: cuda 10.1 cuDNN 7.6.5 driver 436.3
- GPU model and memory: geforce 1660 ti

tensorflow can't see my gpu's I just need it to see it. I am trying to run magenta with gpu and I have been travelling in circles. I did have tensorflow working with gpu support and now I have messed with it too much that it must be broken. I have done a full uninstall of conda and then installed it all again. 
nvcc works and nvidia-smi works so I have it. But it isn't showing up in tensorflow-gpu. 

from running:
import tensorflow as tf
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
print(tf.test.is_gpu_available(
    cuda_only=False,
    min_cuda_compute_capability=None
))

import tensorflow as tf
print(tf.test.gpu_device_name())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 172585563774038155
]
False

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 436.30       Driver Version: 436.30       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 166... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   56C    P0    24W /  N/A |    614MiB /  6144MiB |      6%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by Scathos** [comment]
tf.test.is_built_with_cuda() returns true as well.

**Comment by gadagashwini** [comment]
@Scathos, 
Did you add CUDA and cuDNN path,Please follow the instructions mentioned in the [Tensorflow](https://www.tensorflow.org/install/gpu#windows_setup) website. Thanks

**Comment by Saduf2019** [comment]
@Scathos,
please update as per above comment
