### ISSUE TITLE
tf.python.keras.layers.preprocessing.index_lookup.IndexLookup cannot be saved and loaded

### ISSUE THREAD

**Issue by haifeng-jin** [tensorflow/tensorflow#38419]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
Please check this Colab using tf-nightly.
Also reproduced in 2.2.0rc2
https://colab.research.google.com/drive/1QFmqgiGLsHN3shnEuhakAWLrqjT0nD6B
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): 
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 
- Python version: - Bazel
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
After saving and loading the model the output of the layer is different.

**Describe the expected behavior**
The output should be the same

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
https://colab.research.google.com/drive/1QFmqgiGLsHN3shnEuhakAWLrqjT0nD6B

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue.Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/1192a5fd6c38d16bedfec6f2b7c91b54/untitled17.ipynb)

**Comment by haifeng-jin** [comment]
@saikumarchalla Thank you for the feedback!
AutoKeras is pending on this issue for the next release.
So it would be good to have an estimated timeline of resolving this issue,
so that our team can better coordinate to figure out a solution on our side.

**Comment by markomernick** [comment]
Hi @haifeng-jin - because IndexLookup isn't officially exported yet, we need to treat it as a custom symbol. Can you try adding custom_objects={"IndexLookup": preprocessing.index_lookup.IndexLookup} to your load_model call? This worked for me at head in nightly.

**Comment by haifeng-jin** [comment]
@markomernick @k-w-w 
It works! Thank you for the help.
I am closing this issue now.
