### ISSUE TITLE
can't deal with nii data using tensorflow 

### ISSUE THREAD

**Issue by wolfbill** [tensorflow/tensorflow#3842]
Hi all：
    I'd like to use tensorflow to resize nii data(This kind of data is using in medical for example ct fmri and so on).Any information is appreciate .

**Comment by hholst80** [comment]
* http://nifti.nimh.nih.gov/nifti-1
* https://www.tensorflow.org/versions/r0.10/how_tos/new_data_formats/index.html#custom-data-readers

**Comment by wolfbill** [comment]
@hholst80  I don't know if another way to replace it. Actually, I'd like to use other python library to resize nii data,not tensorflow. But I don't if it's ok.

**Comment by aselle** [comment]
Closing this, as this is not a feature request or enhancement request. Please ask this question on StackOverflow.
