### ISSUE TITLE
How to generate schema_generaed.h

### ISSUE THREAD

**Issue by lizhen2017** [tensorflow/tensorflow#38421]
I try to add a builtin op for tflite, could you please tell me how to generate tensorflow/lite/schema/schema_generated.h
Thanks for your  help!

**Comment by freedomtan** [comment]
most likely it's generated by running [`flatc`](https://google.github.io/flatbuffers/flatbuffers_guide_using_schema_compiler.html) of [`flatbuffer`](https://google.github.io/flatbuffers/)

just curious, why TFLite [custom op](https://www.tensorflow.org/lite/guide/ops_custom) is not enough?

**Comment by lizhen2017** [comment]
I've solved this proplem. 
```sh
bazel run \
  //tensorflow/lite/schema/builtin_ops_header:generate > \
  tensorflow/lite/builtin_ops.h
mv bazel-genfiles/tensorflow/lite/schema/schema_generated.h tensorflow/lite/schema/schema_generated.h
```
HashTableV2、LookupTableImportV2、LookupTableFindV2 are not supported right now. I just try to implement a vocab_list_lookup op. When convert a model with a LookupTableImportV2 op, it missed in the converted tflite model.

**Comment by amahendrakar** [comment]
> I've solved this proplem.

@lizhen2017,
Is this still an issue? Please feel free to close the issue if resolved. Thanks!

**Comment by rthadur** [comment]
s

**Comment by amahendrakar** [comment]
> @lizhen2017,
> Is this still an issue? Please feel free to close the issue if resolved. Thanks!

Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
