### ISSUE TITLE
predict result with SavedModel are not same in Python Api and Java Api

### ISSUE THREAD

**Issue by IamHimon** [tensorflow/tensorflow#38420]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- OS Platform and Distribution (windows 7): 
- TensorFlow installed from (binary): 
- TensorFlow version (cpu, 1.15.0): 
- Python version: - 3.6.3

**Describe the current behavior**
 I saved model with Estimator.export_saved_model()

**I load the model with Python:**

`
from tensorflow.contrib import predictor
self.model = predictor.from_saved_model(self.mode_dir)

\\# predict 
a_input_ids, a_input_mask, a_segment_ids = self._build_input(a_input)
output = self.model({'a_input_ids': [a_input_ids],
                             'a_input_mask': [a_input_mask],
                             'a_segment_ids': [a_segment_ids]})
 a_output = output['a_output_layer']
`
a_output = [[-0.05960074  0.03045687 -0.20487925  0.36802548  0.07898629 -0.35250664
   0.21251363 -0.23284832 -0.30972436 -0.20010747 -0.00487598  0.48967522
   0.1831991  -0.28579575  0.15075627  0.2821794  -0.02628851 -0.05371238
   0.06514908 -0.38573033 -0.34205046  0.3108538  -0.01758813  0.59596956
   0.5169708  -0.46524945 -0.6804516  -0.32393196  0.36948654 -0.46160206
  -0.15634336  0.44929808 -0.39321676 -0.18401513 -0.3726705   0.19476992
   0.33169916 -0.11876976 -0.36055735  0.19275247  0.12676252  0.10232886
   0.63154477 -0.07467962 -0.17044203 -0.47212833  0.26961723 -0.33468968
   0.22710937  0.05272907 -0.6149754  -0.02799183  0.10492884  0.23291017
  -0.20572647 -0.13610545 -0.05362191  0.44776174  0.4095006  -0.43816873
   0.22285426  0.33557323  0.31537503  0.07024186 -0.38216737 -0.12280162
  -0.27534372 -0.41657594 -0.05565406 -0.33100575 -0.29913923  0.00283101
   0.10702493 -0.31459734 -0.2403451   0.42180565 -0.03365724  0.3264306
   0.5190079   0.21016245 -0.3...

**I load the model with Java:**

`
SavedModelBundle bundle = SavedModelBundle.load(exportDir, "serve");
\\# predict :
ThreeTuple<long[][], long[][], long[][]> input = buildInput(sentenceList);

Tensor<?> aInputIdsTensor = Tensor.create(input.param1);
Tensor<?> aInputMaskTensor = Tensor.create(input.param2);
Tensor<?> aSegmentIdsTensor = Tensor.create(input.param3);
List<Tensor<?>> tensors = this.bundle.session().runner()
                .feed("a_input_ids", aInputIdsTensor)
                .feed("a_input_mask", aInputMaskTensor)
                .feed("a_segment_ids", aSegmentIdsTensor)
                .fetch("a_output").run();
Tensor<?> result = tensors.get(0);
float[][] outResult = new float[1][dim];
 result.copyTo(outResult);
float[] a_output = outResult[0]
`
a_output = [[-0.018384377, -0.06955972, 0.051764473, 0.015454082, 0.06722302, -0.07839473, 0.02793679, -0.072589695, -0.051289488, -0.039070662, 0.049129114, 0.11508791, 0.0076964055, -0.042025223, 0.05569571, 0.05739251, -0.04230939, -0.05749864, 0.10970076, -0.15183078, -0.08809995, 0.07375819, 0.08044808, 0.12184837, 0.043990605, -0.12923256, -0.056834757, 0.056434825, 0.033050016, -0.022836037, -0.09641873, 0.029169578, -0.0059487675, -0.084053494, -0.095500425, -0.009507669, 0.032067284, -0.026453126, -0.070464775, 0.058229186, 0.016397119, 0.0129444385, 0.07648615, -0.014742567, -0.01920672, -0.10167458, -0.040589973, -0.037671003, -0.02273454, ...

I use the same version of Tensorflow, same SavedModel, same vocab,same everything but the code language。Apparently, the two result above is not same.

**Describe the expected behavior**

expected same predict result.

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by k-w-w** [comment]
Hmm, it's hard to say from the results alone. Is there some randomization being applied in the signature (e.g. dropout)? Are you able to post code that produced the SavedModel?

**Comment by IamHimon** [comment]
> Hmm, it's hard to say from the results alone. Is there some randomization being applied in the signature (e.g. dropout)? Are you able to post code that produced the SavedModel?

There haven't any randomization , I post my simplified code below: 
1. first i set output in model_fn():

`  


    def model_fn():
       (a_output_layer) = create_model_a(albert_config, is_training, a_input_ids, a_input_mask,
                     a_segment_ids, use_one_hot_embeddings)
      output_spec = tf.contrib.tpu.TPUEstimatorSpec(mode=mode,predictions={"a_output_layer": a_output_layer}, scaffold_fn=scaffold_fn)

   return output_spc

`

2.  create placeholder for input, and build feather and receive_tensors:

` 

     def serving_input_receiver_fn():

                a_input_ids = tf.placeholder(dtype=tf.int64, shape=[None, FLAGS.max_seq_length], name='a_input_ids')
                a_input_mask = tf.placeholder(dtype=tf.int64, shape=[None, FLAGS.max_seq_length], name='a_input_mask')
                a_segment_ids = tf.placeholder(dtype=tf.int64, shape=[None, FLAGS.max_seq_length], name='a_segment_ids')
                receive_tensors = {'a_input_ids': a_input_ids, 'a_input_mask': a_input_mask, 'a_segment_ids': a_segment_ids}
                features = {'a_input_ids': a_input_ids, 'a_input_mask': a_input_mask, 'a_segment_ids': a_segment_ids}
       return tf.estimator.export.ServingInputReceiver(features, receive_tensors)
`

3. export SavedModel:

`
     estimator._export_to_tpu = False
     estimator.export_saved_model(Flags.export_dir, serving_input_receiver_fn)
`

4. than I got result as below:
-1585645721
--variables
-----variables.data-00000-of-00001
-----variables.index
--saved_model.pb

I think its normal and correct way to use SavedModel, but I don't knwon why I got different result with Python Api and Java Api when reload model and predict. Please help me.

**Comment by cslizhang** [comment]
Is the memory restict in jvm?

**Comment by zheng5yu9** [comment]
i also have the same question.
the same pb file,when load it by python,result is right; if load by java,result is wrong;
the java code of load pb is used by many model modules,so it is the right;
any one met the same question??

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
