### ISSUE TITLE
diag_part doesn't work for sub/super diagonals

### ISSUE THREAD

**Issue by gaebor** [tensorflow/tensorflow#38434]
**System information** 
- Have I written custom code: no, see https://www.tensorflow.org/api_docs/python/tf/linalg/diag_part
- OS Platform and Distribution: 
  - Windows 10, Anaconda Python 3.7.6, tensorflow 2.1.0
  - Debian GNU/Linux 8.11 (jessie), Anaconda Python 3.7.3, tensorflow 2.0.0

**Describe the current behavior**
If I ran the example code:
```python
import numpy as np
import tensorflow as tf
input = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 8, 7, 6]], [[5, 4, 3, 2], [1, 2, 3, 4], [5, 6, 7, 8]]])
print(tf.linalg.diag_part(input))
print(tf.linalg.diag_part(input, k=1))
```
***result***
```
[[1 6 7]
 [5 2 7]]
[[1 6 7]
 [5 2 7]]
```
***expected***
```
[[1 6 7]
 [5 2 7]]
[[2, 7, 6],
 [4, 3, 8]]
```
I think that the keyword arguments are just neglected.

**Comment by ravikyram** [comment]
@gaebor 

Can you please try with latest TF version 2.2.0-rc2 (`!pip install tensorflow==2.2-rc2`). I am not seeing any issue with 2.2.0-rc2 version. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/2e70592203a49059e84011a6358a4f77/untitled768.ipynb). Thanks!

**Comment by gaebor** [comment]
Yeah, it works with that!

**Comment by ravikyram** [comment]
@gaebor 

Please, close this thread as your issue got resolved. Thanks!
