### ISSUE TITLE
xla_build CMakeLists.txt - multi platforms

### ISSUE THREAD

**Issue by marcoadurno** [tensorflow/tensorflow#38437]
Hello,

0663149 added CMake support for the upcoming standalone XLA AOT build in TensorFlow 2.2.

However some of the compile options defined in there seem to be for Linux only. When using cmake to build the `xla_aot_runtime_src` from the installed pip package and with the default CMakeLists.txt, I get the following behaviour:
- Linux, everything works;
- MacOS, build succeeds but with a warning of an unknown option (-Wno-deprecated-copy)
- Windows with MSVC, it fails.

In all cases I have used tf-nightly, Python 3.7, pip, cpu only. Platform specific configs:
- MacOS: cmake 3.17.0, AppleClang 11.0.3.11030032
- Linux: cmake 3.10.2, GNU 7.5.0
- Windows:  cmake 3.16.5, MSVC 19.25.28612.0

Wouldn't be better to have something along those lines?
```
cmake_minimum_required(VERSION 3.4.3)

file(GLOB_RECURSE TF_RUNTIME_SRC "*.cc")
add_library(tf_xla_runtime_objects OBJECT
	${TF_RUNTIME_SRC}
)

target_include_directories(tf_xla_runtime_objects PRIVATE ../include)
target_compile_options(tf_xla_runtime_objects PRIVATE
  -ftemplate-backtrace-limit=0
  $<$<OR:$<CXX_COMPILER_ID:GNU>,$<CXX_COMPILER_ID:Clang>>:-Wno-ignored-attributes>  
  $<$<CXX_COMPILER_ID:GNU>:-Wno-deprecated-copy>  
  $<$<OR:$<CXX_COMPILER_ID:GNU>,$<CXX_COMPILER_ID:Clang>>:-Wno-cast-qual>  
  $<$<OR:$<CXX_COMPILER_ID:GNU>,$<CXX_COMPILER_ID:Clang>>:-Wno-sign-compare>  
)

add_library(tf_xla_runtime STATIC
  $<TARGET_OBJECTS:tf_xla_runtime_objects>
)
```

Also, apart from managing the warning flags, do you have any view on shipping predefined MSVC compiler options required to make the build succeed? The build does eventually work, but the list of flags is quite lengthy and it's certainly not something that I would have dreamt of (I copied it from bazel).

As a side note, on all three platforms I have tried building the bazel target `//tensorflow/compiler/tf2xla:xla_compiled_cpu_runtime_standalone` and thanks to the fact that all options are pre-configured and managed by bazel the experience has been much smoother.

Best Regards,

Marco

**Comment by sanatmpa1** [comment]
@marcoadurno,

Here is the [link](https://www.tensorflow.org/install/source_windows#tested_build_configurations) to find tested build configurations, which contains compatible version of MSVC and other tools while building Tensorflow from source on Windows.

Can you try updating to `TF 2.6.0` using this [guide](https://www.tensorflow.org/install/source_windows) and let us know if the issue persists in newer version. Thanks!

**Comment by battuzz** [comment]
Sorry to jump in, but I think that the issue was related to build just the xla_aot_runtime (so not the whole Tensorflow source) with CMake (and not Bazel) in a Windows environment.

And in this respect, I see that the CMakeLists.txt was not updated since this issue was created: https://github.com/tensorflow/tensorflow/blob/r2.4/tensorflow/tools/pip_package/xla_build/CMakeLists.txt

**Comment by sanatmpa1** [comment]
@battuzz,

Thanks for the clarification. We no longer support cmake builds and it is recommend to use bazel.
