### ISSUE TITLE
flow_from_dataframe() doesn't shuffle data properly when splitting in subsets

### ISSUE THREAD

**Issue by jgciudad** [tensorflow/tensorflow#38430]
**System information** 
- Google Colab
- Tensorflow 2.2.0-rc2

**Describe the current behavior**
When `validation_split` is set to some value in `ImageDataGenerator` in order to split the data in two subsets to train and validate, and then shuffle is set to true in `flow_from_dataframe`, the shuffling occurs after this division. This makes the two subsets have different distributions, with a big impact in training stats.

**Describe the expected behavior**
The data should be shuffled BEFORE the division in subsets instead of after.

**Standalone code to reproduce the issue** 
Full code is available here: https://colab.research.google.com/drive/1gpiRZMHpp09nftzl909OG-9JJgTrhkO3 

```
def check_iterator_distribution(iterator):
  # Checks category distribution in the given iterator

  iterator.reset()
  nCat=[0,0,0,0,0,0,0,0,0] # number of images in each category (there are 9 categories)

  step_size = iterator.n//iterator.batch_size

  for i in range(step_size):
    a,b = next(iterator)

    for f in range(iterator.batch_size):
      index = np.where(b[f]==1.)[0][0]

      if index==0:
        nCat[0]+=1
      elif index==1:
        nCat[1]+=1
      elif index==2:
        nCat[2]+=1
      elif index==3:
        nCat[3]+=1
      elif index==4:
        nCat[4]+=1
      elif index==5:
        nCat[5]+=1
      elif index==6:
        nCat[6]+=1
      elif index==7:
        nCat[7]+=1
      elif index==8:
        nCat[8]+=1

  distribution = [x/iterator.n for x in nCat]

  print('Number of images per category', nCat)
  print('Distribution:',distribution)

datagen_train = ImageDataGenerator(preprocessing_function = efn.preprocess_input,
                                   rotation_range = 40,
                                   zoom_range = 0.2,
                                   horizontal_flip = True,
                                   vertical_flip = True,
                                   validation_split=0.2
                                   )

train_iterator = datagen_train.flow_from_dataframe(
    dataframe = df_train,
    directory = path,
    x_col = "image",
    y_col = ['MEL','NV','BCC','AK','BKL','DF','VASC','SCC','UNK'],
    batch_size = 32,
    shuffle = True,
    class_mode = "raw",
    target_size = (224,224),
    subset = "training"
)

val_iterator = datagen_train.flow_from_dataframe(
    dataframe = df_train,
    directory = path,
    x_col = "image",
    y_col = ['MEL','NV','BCC','AK','BKL','DF','VASC','SCC','UNK'],
    batch_size = 32,
    shuffle = True,
    class_mode = "raw",
    target_size = (224,224),
    subset = "validation"
)

check_iterator_distribution(train_iterator)
check_iterator_distribution(val_iterator)
```
The distribution of both iterators is as follows:

- `train_iterator`: Number of images per category [3789, 9417, 3214, 839, 1995, 214, 216, 572, 0]
Distribution: [0.1869, 0.4646, 0.1585, 0.0414, 0.0984, 0.0105, 0.0106, 0.0282, 0.0]
- `val_iterator`: Number of images per category [731, 3445, 108, 27, 627, 25, 37, 56, 0]
Distribution: [0.1442, 0.6800, 0.0213, 0.0053, 0.1237, 0.0049, 0.0073, 0.0110, 0.0]

In contrast, when the dataframe is shuffled (through `df_train.sample(frac=1)`) before being passed to `flow_from_dataframe()`, the distribution is almost the same in both:

- `train iterator`: Number of images per category [3596, 10290, 2699, 711, 2064, 192, 210, 494, 0]
Distribution: [0.1774, 0.5077, 0.1331, 0.0350, 0.1018, 0.0094, 0.0103, 0.0243, 0.0]
- `val_iterator`: Number of images per category [925, 2574, 621, 155, 558, 47, 43, 133, 0]
Distribution: [0.1825, 0.5080, 0.1225, 0.0305, 0.1101, 0.0092, 0.0084, 0.0262, 0.0]

**Comment by amahendrakar** [comment]
@jgciudad,
There are a few undefined variables like `efn.preprocess_input` and `path` used in the given code.

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by jgciudad** [comment]
@amahendrakar 
Hi! I updated the code in Colab declaring `path` and `efn.preprocess_input`. I think I'm not allowed to share the dataset, but it's composed of 25331 images of 9 different categories. I've printed a sample of the dataframe in Colab so you can see its structure. All the images referred in the dataframe are in `path`. I hope is enough with that, thanks!

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
