### ISSUE TITLE
ValueError: Cannot infer num from shape (None, None) when unstacking dense tensor converted from sparse tensor

### ISSUE THREAD

**Issue by Victor-Almeida** [tensorflow/tensorflow#38448]
Hello,

Iam trying to create a Keras compatible model using Tensorflow to use the CTC loss and I just found a problem : after decoding the output of the neural network using ``tf.nn.ctc_greedy_decoder``, it returns an array with a sparse tensor, and in order to be able to use GPUs and TPUs to calculate the loss with ``tf.nn.ctc_loss`` we need to convert the sparse tensor to a dense tensor, so I used ``tf.sparse.to_dense``, but when I try to get the ``logit_length`` requested by the loss function using ``tf.unstack`` I get the following error : ``ValueError: Cannot infer num from shape (None, None)``. The thing is when I use ``tf.unstack`` on a dense tensor converted from a sparse tensor I don't have any issues.

Here is the part of code that raised this issue  (both ``batch_inputs`` and ``batch_targets`` are dense tensors): 

```
@tf.function
def train_step(self, batch_inputs, batch_targets):
    with tf.GradientTape(persistent = True) as tape:
        # Doing a manual prediction because calling Keras's predict method inside a tensorflow function is not supported
        X = batch_inputs
        for layer in self.neural_network.layers:
            X = layer(X)

        logits = tf.transpose(X, [1, 0, 2]) 
        logits_sequence_length = [logit.shape[0] for logit in tf.unstack(logits)] 
        decoded, neg_sum_logits = self.ctc_decoder(X, logits_sequence_length) 
        decoded_logits = decoded[0] 
        dense_decoded_logits = tf.sparse.to_dense(decoded_logits) 
        decoded_logits_sequence_length = [decoded_logit.shape[0] for decoded_logit in tf.unstack(dense_decoded_logits)]
        batch_target_sequence_length = [target.shape[0] for target in tf.unstack(batch_targets)] 
        batch_loss, average_batch_loss = self.calculate_loss(batch_targets, dense_decoded_logits, batch_target_sequence_length, decoded_logits_sequence_length) 
        with tape.stop_recording():
            gradients = tape.gradient(batch_loss, self.neural_network.trainable_variables) 
            self.optimizer.apply_gradients(zip(gradients, self.neural_network.trainable_variables)) 
            decoded_logits = tf.transpose(decoded_logits, [1, 0, 2]) 
            sparse_batch_targets = tf.math.dense_to_sparse(batch_targets, ignore_values = 0) 
            batch_ler, average_batch_ler = self.calculate_ler(sparse_batch_targets, decoded_logits) 
            return average_batch_loss.numpy(), average_batch_ler.numpy()
```

More specifically, this line :  `` decoded_logits_sequence_length = [decoded_logit.shape[0] for decoded_logit in tf.unstack(dense_decoded_logits)]``

And this is the full error : 
```
---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-44-88cbf7d06e0e> in <module>()
      5           val_inputs = dev_spectrograms,
      6           val_targets = dense_dev_targets,
----> 7           val_batch_size = 32)

10 frames

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    966           except Exception as e:  # pylint:disable=broad-except
    967             if hasattr(e, "ag_error_metadata"):
--> 968               raise e.ag_error_metadata.to_exception(e)
    969             else:
    970               raise

ValueError: in user code:

    <ipython-input-42-c1dfc702e50f>:173 train_step  *
        decoded_logits_sequence_length = [decoded_logit.shape[0] for decoded_logit in tf.unstack(dense_decoded_logits)]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py:1510 unstack  **
        raise ValueError("Cannot infer num from shape %s" % value_shape)

    ValueError: Cannot infer num from shape (None, None)
```

After trying a few things, I noticed that this works perfectly if I return ``dense_decoded_logits`` and unstack it outside the function, but for some reason it won't work inside.

I'm using Google Colab high-RAM runtime with GPU running Tensorflow version 2.2.0rc2

**Comment by ravikyram** [comment]
@Victor-Almeida 

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by Victor-Almeida** [comment]
[Here](https://colab.research.google.com/drive/1KPRWaSXnIVMYw6xZf5oqqdIU2QH4p3E-)

**Comment by ravikyram** [comment]
@Victor-Almeida 

Will it be possible to share dataset to reproduce the issue in our environment. Thanks!

**Comment by Victor-Almeida** [comment]
Sure. I shared [this](https://drive.google.com/drive/folders/1bgGte_wVyaYAycBntQA8uQWmVQZqhPYH?usp=sharing) folder from my Google Drive. You don't need to download it all, just the ones referenced in the notebook.

**Comment by ravikyram** [comment]
@Victor-Almeida 

I have tried on colab with TF version 2.2.0-rc2 and i am seeing different error message (`AttributeError: 'list' object has no attribute 'shape'`).Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/06c8135bfdd56551f130dd2607b55f52/untitled777.ipynb). Thanks!

**Comment by Victor-Almeida** [comment]
That error happened because I edited the notebook after sending the link and tried to print the shape of a list, but lists don't have shape.

I solved the problem by setting the shape of the tensor manually using ``tf.ensure_shape``, but it should be investigated why the sparse tensor outputted by ``ctc_loss`` has shape ``(None, None)`` when converted to a dense tensor.
