### ISSUE TITLE
Why does work_group_launch_order in TFLite Metal matter?

### ISSUE THREAD

**Issue by DreamChaserMXF** [tensorflow/tensorflow#38445]
https://github.com/tensorflow/tensorflow/blob/9a9a4bfec64cec8a12d31809404ece94a4f55771/tensorflow/lite/delegates/gpu/metal/kernels/conv.cc#L59

I'm a beginner of Metal and trying to understand the Metal implementation of convolution in TFLite. After having read this line of code and found all usages, I'm really confused that why the `work_group_launch_order` matters. How does this machenism work indeed? Is it related to the way GPU linearizes the 3D work group?

Thanks for your reply.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
 Thanks!
