### ISSUE TITLE
ValueError: Error when checking : expected input_1 to have shape (608, 608, 3) but got array with shape (416, 416, 3)

### ISSUE THREAD

**Issue by haideralimughal** [tensorflow/tensorflow#38449]
please give me suggestions ? how to solve this error

if __name__ == '__main__':
    yolo = YOLO(0.6, 0.5)
    file = 'data/coco_classes.txt'
    all_classes = get_classes(file)
 
    # detect images in test floder.
    for (root, dirs, files) in os.walk('images/test'):
        if files:

            for f in files:
                print(f)
                
                path = os.path.join(root, f)
                image = cv2.imread(path)
                image = np.array(image)
                image = detect_image(image, yolo, all_classes)
                cv2.imwrite('images/res/' + f, image)
                

def process_image(img):
    """Resize, reduce and expand image.

    # Argument:
        img: original image.

    # Returns
        image: ndarray(64, 64, 3), processed image.
    """
    
    image = cv2.resize(img, (416, 416),
                       interpolation=cv2.INTER_CUBIC)
    image = np.array(image, dtype='float32')
    image /= 255.
    image = np.expand_dims(image, axis=0)

    return image

ValueError: Error when checking : expected input_1 to have shape (608, 608, 3) but got array with shape (416, 416, 3)

**Comment by khimraj** [comment]
@haideralimughal,  During training, YOLO takes images of size 320×320, 352×352, … and 608×608 (with a step of 32). so you need to replace line 
`image = cv2.resize(img, (416, 416), interpolation=cv2.INTER_CUBIC)`
with
`image = cv2.resize(img, (608,608), interpolation=cv2.INTER_CUBIC)`.

**Comment by Saduf2019** [comment]
@haideralimughal 
please update as per above comment

**Comment by Saduf2019** [comment]
@haideralimughal
please update on the above comment

**Comment by Saduf2019** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
