### ISSUE TITLE
Incorrect zero recognition

### ISSUE THREAD

**Issue by Mostalk** [tensorflow/tensorflow#38446]
- Tensorflow 2.2.0rc2
- Windows 10
- Python 3.8.2

I have an image with zeros that tensorflow recognizes as eights, can this be fixed somehow?

Image:
![Screenshot_2](https://user-images.githubusercontent.com/9198186/79034675-b17e4080-7bc0-11ea-94fd-448af68fde28.png)
Result:
8,88
8,88

**Comment by khimraj** [comment]
@Mostalk, Which model you are using to predict these results. One possible reason can be that model is not trained on such type of zero(0 with a cross line) and trained on zero like 0.

**Comment by saikumarchalla** [comment]
@Mostalk In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
