### ISSUE TITLE
tf.train.Checkpoint complain that tf.train.ExponentialMovingAverage instance is not a trackable object

### ISSUE THREAD

**Issue by naturomics** [tensorflow/tensorflow#38452]
My tensorflow versiong is 2.1.0, I built a model in the standard way of keras subclassing and saved it with tf.train.Checkpoint. It works fine in the following code:
```
model = ... # a subclassing model instance
ckpt = tf.train.Checkpoint(model=model)
for epoch in range(total_epochs):
    ...   
    ckpt.save(path)
```
When add the code of moving average as following:
```
model = ... # a subclassing model instance
ema = tf.train.ExponentialMovingAverage(decay=0.999, zero_debias=True)
ckpt = tf.train.Checkpoint(model=model, ema=ema)
for epoch in range(total_epochs):
    ...   
    ckpt.save(path)
```
cause this error:
```
ValueError: `Checkpoint` was expecting a trackable object (an object derived from `TrackableBase`), 
got <tensorflow.python.training.moving_averages.ExponentialMovingAverage object at 0x7f63c8070a58>.
If you believe this object should be trackable (i.e. it is part of the TensorFlow Python API and manages state), please open an issue.
```

Is that `tf.train.ExponentialMovingAverage` incompatible with tf2? What's the best practice to do moving average in tf2?

**Comment by ravikyram** [comment]
@naturomics 

Can you please share colab  link or minimal standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by naturomics** [comment]
@ravikyram 
Please see this [gist](https://colab.research.google.com/drive/1IyWDGC1CFLkzlHdsBHteJxSdn-ShaX51).

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.1.0 , 2.2-rc2 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/6662f97163c2735f11707f9d4743af02/untitled769.ipynb). Thanks!

**Comment by naturomics** [comment]
Any update?

**Comment by AdamByerly** [comment]
I'm also interested in saving the EMA variables in a checkpoint.

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210525, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/3b8a3263138dc994455f20bdbe93883d/38452.ipynb). Thanks!

**Comment by mohantym** [comment]
Hi @naturomics ! As this [document](https://www.tensorflow.org/api_docs/python/tf/train/ExponentialMovingAverage) suggests although EMA objects are not directly trackable ,you can use average() to return the moving average variables for your model weights, which you can then checkpoint. Attaching Modified [Gist](https://colab.sandbox.google.com/gist/mohantym/f6c2f217efa72927625cee1be9ddf235/38452.ipynb#scrollTo=xmj4nHd5MKbz) for reference. Thanks!

![image](https://user-images.githubusercontent.com/86464649/145236036-65bacdcb-d5c2-4bad-8225-8c8bdcfe7377.png)

**Comment by ronshapiro** [comment]
Is there a reason they can't be trackable, or just no one has implemented it yet?

It seems natural to make them trackable, given that the documentation shows you how to do so. Trackability will also serialize the decay parameter, which would be nice.
