### ISSUE TITLE
Uncertain training and validation generators behaviour

### ISSUE THREAD

**Issue by korr4k** [tensorflow/tensorflow#38458]
**System information** 
- Have I written custom code: Yes
- OS Platform and Distribution: Windows 10 Home N 1909 
- TensorFlow installed from: Anaconda
- Python version: 3.7
- CUDA/cuDNN version: 10.0
- GPU model and memory: GeForce RTX 2060

**Describe the current behavior**

The generator function for images datasets that I'm using is as follow:

```python
def generator(batchsize, epochs, epoch_steps, train=False, val=False, test=False, shuffle=False):
    with tf.Session() as sess:      
        if (train):
            dataset = tf.data.Dataset.from_generator(lambda: image_gen(train_paths, train_scores),
                                                      output_types=(tf.float32, tf.float32))
        elif(val):
            dataset = tf.data.Dataset.from_generator(lambda: image_gen(val_paths, val_scores),
                                                      output_types=(tf.float32, tf.float32))
        else:
            dataset = tf.data.Dataset.from_generator(lambda: image_gen(test_paths),
                                                      output_types=(tf.float32))       

        if (shuffle and train):
            dataset = dataset.shuffle(buffer_size=dataset_size(train=True)) 
        elif (shuffle and val):
                dataset = dataset.shuffle(buffer_size=dataset_size(val=True)) 
        elif (shuffle and test):
                dataset = dataset.shuffle(buffer_size=dataset_size(test=True)) 
            
        dataset = dataset.batch(batchsize)
        dataset = dataset.map(pre_processing_image,
                              num_parallel_calls=tf.data.experimental.AUTOTUNE)
        dataset = dataset.prefetch(1)
        dataset = dataset.repeat(count = -1)
        
        iterable = tf.data.make_initializable_iterator(dataset)
        batch = iterable.get_next()
        sess.run(iterable.initializer)
        
        while True:
            try:
                data = sess.run(batch)
                yield data
            except:
                break
```

How the training script uses these generators is:

```python
training_steps = math.ceil(dataset_training_size / batchsize)
val_steps = math.ceil(dataset_val_size / batchsize)    
    
# Training and validation generator functions
train_generator = generator(batchsize=batchsize,
                            epochs = epochs_to_train,
                            epoch_steps = training_steps, 
                            train=True, 
                            shuffle=True)
val_generator = generator(batchsize=batchsize,
                          epochs = epochs_to_train,
                          epoch_steps = val_steps,
                          val=True)

model.fit_generator(generator=train_generator,
                    steps_per_epoch=training_steps,
                    epochs=epochs_to_train+loaded_epoch,
                    verbose=1,
                    callbacks=callBacks,
                    initial_epoch=loaded_epoch,
                    validation_data=val_generator,
                    validation_steps=val_steps)
```

Both training and validation datasets are very large while the batch size is a lot smaller, also the last step of each epoch has less images compared to the previous (dataset_size%batch_size != 0). What I want to accomplish during each epoch, for both generators, is to use all images one time only, possibly with randomness in their order during the training and not during the validation.
I made some tests with the following code and they the results are what I expect them to be

```python
a = []
b = []

try:
    for i in range(training_steps * epochs_to_train):
        a.append(next(train_generator))
except:
    pass

try:    
    for el in range(val_steps * epochs_to_train):
        b.append(next(val_generator))
except:
    pass
```

The current main problem with my code is that at the end of the last epoch I get this error:

```
IndexError: pop from empty list
Exception ignored in: <generator object generator at 0x00000226437494C8>
Traceback (most recent call last):
  File "...", line 448, in generator
    break
  File "...", line 1621, in __exit__
    self._default_graph_context_manager.__exit__(exec_type, exec_value, exec_tb)
  File "...\Anaconda3\envs\tensorflow\lib\contextlib.py", line 119, in __exit__
    next(self.gen)
  File "...\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\ops.py", line 5484, in get_controller
    context.context().context_switches.pop()
  File "...\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\context.py", line 237, in pop
    self.stack.pop()
IndexError: pop from empty list
```

This error is present for both generators but I think it isn't a complete issue, the training seems to end anyway and all models are correctly saved. I just don't know how to remove that exception and I don't want to publish the code with it.
I tried to mess with everything regarding mostly

```python
while True:
     try:
         data = sess.run(batch)
         yield data
     except:
         break
```

but I couldn't find a setup that ended the training without any exception.

The only similar issue that I could find online was https://stackoverflow.com/questions/52303130/keras-generator-with-tensorflow-dataset-api-indexerror-pop-from-empty-list/52304848 but the solution isn't working for me.

Also, during my various attempts I tried to change the generators as follow 

```python
#dataset = dataset.repeat(count = -1)
dataset = dataset.repeat(count = epochs)
```

```python
cnt = 0
#while True:
while cnt < epochs * epoch_steps
            try:
                data = sess.run(batch)
                cnt+=1
                yield data
            except:
                break
```
but in both cases I get the following error after some epochs:

```
  File "...\train_model.py", line 325, in <module>
    main()

  File "...\train_model.py", line 305, in main
    validation_steps=val_steps)

  File "...\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1296, in fit_generator
    steps_name='steps_per_epoch')

  File "...\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_generator.py", line 323, in model_iteration
    steps_name='validation_steps')

  File "...\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_generator.py", line 221, in model_iteration
    batch_data = _get_next_batch(generator)

  File "...\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_generator.py", line 363, in _get_next_batch
    generator_output = next(generator)

  File "...\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\utils\data_utils.py", line 922, in get
    six.reraise(*sys.exc_info())

  File "...\Anaconda3\envs\tensorflow\lib\site-packages\six.py", line 703, in reraise
    raise value

  File "...\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\utils\data_utils.py", line 898, in get
    inputs = self.queue.get(block=True).get()

  File "...\Anaconda3\envs\tensorflow\lib\multiprocessing\pool.py", line 657, in get
    raise self._value

  File "...\Anaconda3\envs\tensorflow\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))

  File "...\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\utils\data_utils.py", line 832, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])

  File "...", line 448, in generator
    break

  File "...\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\client\session.py", line 1621, in __exit__
    self._default_graph_context_manager.__exit__(exec_type, exec_value, exec_tb)

  File "...\Anaconda3\envs\tensorflow\lib\contextlib.py", line 119, in __exit__
    next(self.gen)

  File "...\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\ops.py", line 5484, in get_controller
    context.context().context_switches.pop()

  File "...\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\context.py", line 237, in pop
    self.stack.pop()

IndexError: pop from empty list

```

To my understanding if epochs and epoch_steps are set as the # of epochs and the steps for each epoch there shouldn't have been any problem..

I wrote here on GitHub because I'm not sure this is me not understanding what is wrong with my generators or if there is a bug. I didn't provide a complete code because it is very long and I think the important parts are present, if you need more informations I can provide them

**Comment by gadagashwini** [comment]
@korr4k, Thanks for reporting this issue,
Can you share the complete code to reproduce the issue. Thanks

**Comment by korr4k** [comment]
Ok, I attached an archive with a simplified version of my code that still results in "IndexError: pop from empty list".
The archive is complete and you just have to run the script **train.py**.
I clearly had to adjust the datasets to make them a lot smalled but it shouldn't matter: both training and evaluation datasets have only 5 images. Both batchsize and the epochs to train are **2**

[Tmp.zip](https://github.com/tensorflow/tensorflow/files/4469630/Tmp.zip)

**Comment by Saduf2019** [comment]
@korr4k 
The code provided is to large to replicate, can you please share a simple stand alone code or please share a colab gist so we can analyse the issue faced.

**Comment by korr4k** [comment]
@Saduf2019 let me know if this colab is ok with you

https://colab.research.google.com/drive/1TDK9UBdRR4OaCQUY81W5O7cpMDtGfIOy?usp=sharing

**Comment by Saduf2019** [comment]
@korr4k
I do not have access to the code shared.

**Comment by korr4k** [comment]
@Saduf2019 
This should work: https://colab.research.google.com/gist/korr4k/620c35e21b42e5c8af0ef1a4773519a6/test.ipynb#scrollTo=mLCo5X1cpReT

I suppose you can't run it unless you upload the required .npy files, if you need them they are all inside the zip I provided in my previous comment

**Comment by Saduf2019** [comment]
@korr4k 
I ran the above code  with all the files shared but do not face the error faced by you.
please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/6985174a391409e51703b7442e2b2ea5/untitled168.ipynb)

**Comment by korr4k** [comment]
@Saduf2019 the gist you provided hasn't even completed the training, why so? Mine does and it is at the end of it that the problem I reported occurs.
I see that you also haven't specified to use tf 1.x and not 2.x, which to my understanding is the default for Colab, as I did

**Comment by Saduf2019** [comment]
@korr4k 
I ran the code on nightly as well and the execution does not complete and same error is faced. please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/f4cb2129e1fc25b57fbae71ac60867c5/untitled171.ipynb)

**Comment by korr4k** [comment]
@Saduf2019 I guess I'll have to make it very clear, I'm not using Tensorflow 2. As you can see from my gist, the first cell is "%tensorflow_version 1.x" which forces Colab to use tf 1.x

**Comment by gowthamkpr** [comment]
@korr4k I was able to reproduce your issue. 
![image](https://user-images.githubusercontent.com/47574994/83806002-aa762a80-a665-11ea-9a3e-7585fc6c1e49.png)

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
