### ISSUE TITLE
The saved preview image is a green image (tensorflow lite object detection android demo)

### ISSUE THREAD

**Issue by wadewangpower** [tensorflow/tensorflow#38451]
I try to deploy the [tensorflow lite object detection android demo](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android) on streaming media rearview mirror,it is something like this:
![image](https://user-images.githubusercontent.com/43233772/79041066-72cba300-7c1f-11ea-983f-488ee4bdb7f8.png)
and it is android 5.1(API 22) OS, it use android.hardware.Camera API instead of Camera2 API.
The result is the app can preview, but doesn't show any prediction box. 
Afterwards, i set SAVE_PREVIEW_BITMAP = true, and found the cause is the input image is not correct, the saved preview bitmap is just a green image:
![croppedBitmap-300300-1586578626229](https://user-images.githubusercontent.com/43233772/79041173-3c425800-7c20-11ea-9a95-a881c5de2a1d.jpg)
So how to debug it ? thanks !

**Comment by lintian06** [comment]
Did you run it from the real device (like Android phones) or the emulator on laptop?

**Comment by wadewangpower** [comment]
> Did you run it from the real device (like Android phones) or the emulator on laptop?
> 
> I don't know the exact behavior of such a device you show. The thing I knew was for emulator, it gave fake images for testing.

Afterward, I knew that although Android 5.1 does not fully support camera2, it is still usable, so  i commented out `useCamera2API =
            (facing == CameraCharacteristics.LENS_FACING_EXTERNAL)
                || isHardwareLevelSupported(
                    characteristics, CameraCharacteristics.INFO_SUPPORTED_HARDWARE_LEVEL_FULL);` and I forced set `useCamera2API = true;` , the app's detection can finnaly works !

**Comment by wadewangpower** [comment]
> Did you run it from the real device (like Android phones) or the emulator on laptop?
> 
> I don't know the exact behavior of such a device you show. The thing I knew was for emulator, it gave fake images for testing.

One issue fixed, another one comes up, that is rgbFrameBitmap is left and right are reverse, below image is the part of the screenshot, we can see the text is symmetry reverse, so how to flip horizontally the rgbFrameBitmap ?

**Comment by lintian06** [comment]
Hi Weida, it might be commonly asked. You might want to check this [stackoverflow answer.](https://stackoverflow.com/questions/36493977/flip-a-bitmap-image-horizontally-or-vertically)

**Comment by wadewangpower** [comment]
> Hi Weida, it might be commonly asked. You might want to check this [stackoverflow answer.](https://stackoverflow.com/questions/36493977/flip-a-bitmap-image-horizontally-or-vertically)

I have just solved this problem, in **ImageUtils.java** 's  **convertYUV420ToARGB8888()**, modify `pUV + (i >> 1) * uvPixelStride`   to `pUV + (uvRowStride -1 - (i >> 1) * uvPixelStride)` AND modify `yData[pY + i]` to `yData[pY + (yRowStride-1-i)]` , everything workd well again ~
