### ISSUE TITLE
 AttributeError: module 'tensorflow' has no attribute 'variable_scope'

### ISSUE THREAD

**Issue by dcv10** [tensorflow/tensorflow#38461]
When I put this line of code in:

mlpr = ANNR([input], layers, batchSize = 256, maxIter = 20000, tol = 0.2, reg = 1e-4, verbose = True)

I get the following error:  AttributeError: module 'tensorflow' has no attribute 'variable_scope'

I am using tensorflow version 2.1

How do I fix this?

Thanks in advance.

**Comment by khimraj** [comment]
@dcv10, refer this [issue](https://github.com/datamllab/rlcard/issues/96).

**Comment by dcv10** [comment]
@khimraj I have but did not find it useful

**Comment by khimraj** [comment]
@dcv10, can you please share full code to reproduce issue.

**Comment by dcv10** [comment]
import numpy as np
import matplotlib.pyplot as mpl
from sklearn.preprocessing import scale
from TFANN import ANNR
from google.colab import files

#reads data from the file and ceates a matrix with only the dates and the prices 
stock_data = np.loadtxt('NSE-TATAGLOBAL12.csv', delimiter=";", skiprows=1, usecols=(1, 6))
print(stock_data)
#scales the data to smaller values
stock_data=scale(stock_data)
# #gets the price and dates from the matrix
prices = stock_data[:, 1].reshape(-1, 1)
dates = stock_data[:, 0].reshape(-1, 1)
#creates a plot of the data and then displays it
mpl.plot(dates[:, 0], prices[:, 0])
mpl.show()
#Number of neurons in the input, output, and hidden layers
input = 1
output = 1
hidden = 50
#array of layers, 3 hidden and 1 output, along with the tanh activation function 
layers = [('F', hidden), ('AF', 'tanh'), ('F', hidden), ('AF', 'tanh'), ('F', hidden), ('AF', 'tanh'), ('F', output)]
#construct the model and dictate params
mlpr = ANNR([input], layers, batchSize = 256, maxIter = 20000, tol = 0.2, reg = 1e-4, verbose = True)


@khimraj here is the code

**Comment by khimraj** [comment]
@dcv10, you need tensorflow version less than 2.0 and I have successfully compiled your code and faced no issue. For your reference link of gist is [here](https://colab.research.google.com/gist/khimraj/e80cf5df026026ba6e93b3dc8947b5e2/mean.ipynb#scrollTo=ldUyF5UJb75D).

**Comment by Saduf2019** [comment]
@dcv10 
please update as per above comment

**Comment by Jonasvantrap** [comment]
I am using Tensorflow version 2.0 and I have the same error. The issue remains when using tf.compat.v1
Any idea how to fix this without downgrading tensorflow?

**Comment by Saduf2019** [comment]
@dcv10
please please update if this is still an issue

**Comment by nopestack** [comment]
I'm experiencing the same issue while following the exact same tutorial

**Comment by hiedo003** [comment]
Same issue, can someone help

**Comment by iskandergaba** [comment]
Same issue here

**Comment by adityak1911** [comment]
same issue here also

**Comment by neodgeo** [comment]
same issue here, anyone found a way on tf2 ?

**Comment by ares5221** [comment]
same issue here, anyone found a way on tf2 ?

**Comment by Sammed98** [comment]
same issue here. Using TensorFlow 2 and don't wish to downgrade

**Comment by raj1003daksh** [comment]
Changing tf.variables_initializer to tf.compat.v1.variables_initializer worked for me. I am using Tensorflow 2.3.

**Comment by CaduceusInc** [comment]
> 
> 
> Changing tf.variables_initializer to tf.compat.v1.variables_initializer worked for me. I am using Tensorflow 2.3.

This worked for me, thank you.

**Comment by callzhang** [comment]
> Changing tf.variables_initializer to tf.compat.v1.variables_initializer worked for me. I am using Tensorflow 2.3.

where should I add this code? My original code is:
```
with tf.variable_scope(name_or_scope=name, reuse=reuse):
            ...
```

**Comment by QinHsiu** [comment]
I have the same problems.

**Comment by ares5221** [comment]
您好，您发送的邮件我已经收到。我将尽快给您回复。如紧急，请电联。This is an automatic reply, confirming that your email was received.I will reply as soon as possible.Thank you
