### ISSUE TITLE
 'module' object has no attribute 'sparse_column_with_keys'

### ISSUE THREAD

**Issue by jokisa** [tensorflow/tensorflow#3846]
i try to run the example  came with the linear model tutorial but i get the error below
 attributeerror :  'module' object has no attribute 'sparse_column_with_keys' in the
gender = tf.contrib.layers.sparse_column_with_keys(column_name="gender", keys=["female","male"])

my environmenent : i run tensorflow with docker on Windows 10

output when running:

Traceback (most recent call last):
  File "tensor3.py", line 54, in <module>
    gender = tf.contrib.layers.sparse_column_with_keys(column_name="gender", keys=["female", "male"])
AttributeError: 'module' object has no attribute 'sparse_column_with_keys'

**Comment by caisq** [comment]
@jokisa , can you let me know which TensorFlow docker image you are using?

**Comment by jokisa** [comment]
I use the grc.io/tensorflow/tensorflow :la test  image.

**Comment by caisq** [comment]
@jokisa The tag you are using is pointing to an older version. Can you try this image instead? b.gcr.io/tensorflow/tensorflow:r0.9

**Comment by jokisa** [comment]
hi,


sorry for my late response . I was in a vacation.
I have just try the image that you have suggested  .

things work fine now.

thank you for your help

2016-08-17 2:43 GMT+02:00 caisq <notifications@github.com>:
