### ISSUE TITLE
How can one apply an arbitrary function to a dataset?

### ISSUE THREAD

**Issue by laghaout** [tensorflow/tensorflow#38471]
Is there anything similar to pandas' `.apply()` or `.map()` that could apply arbitrary functions on TensorFlow datasets in an efficient (i.e., vectorized) manner? 

## Minimum working example

Consider the following code.

```
import tensorflow as tf

def compute_length(x): 
    return tf.strings.length(x)

def check_substring(x, substring):
    return substring in x

def compute_palindrome(x):
    return ''.join([x[-i] for i in range(-len(x)+1, 1)])
    
ds = tf.data.Dataset.from_tensor_slices(["Ottawa", "Stockholm", "Rabat"])

ds = ds.map(
    lambda city: (city, 
                  compute_length(city), 
#                  check_substring(city, "lm"),
#                  compute_palindrome(city),
                  ),
        )

num_elems = len(ds.element_spec)
for elem in ds:
    print(''.join([f"{elem[i]}" for i in range(num_elems)]))
```

## Issues

`compute_length()` works fine and returns
```
b'Ottawa'6
b'Stockholm'9
b'Rabat'5
```

However, commenting out `check_subsring()` returns 

> OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph is disabled in this function. Try decorating it directly with @tf.function.

and commenting out `compute_palindrome()` returns 

> TypeError: len is not well defined for symbolic Tensors. (args_0:0) Please call `x.shape` rather than `len(x)` for shape information.

Unlike a simple `apply()` or `map()` in pandas, there is clearly some extra steps needed to apply such operations on Tensors. The documentation for what those steps are isn't easy to find. 

PS: The use of TensorFlow's `map()` isn't required. Whatever does the job is welcome.

## URL(s) with the issue:

This pertains to either 
https://www.tensorflow.org/api_docs/python/tf/data/Dataset#map or
https://www.tensorflow.org/api_docs/python/tf/map_fn

**Comment by 17patelumang** [comment]
1. 

```
import tensorflow as tf

tf.enable_eager_execution()


def compute_length(x): 
    return tf.strings.length(x)

def check_substring(x, substring):
    return tf.strings.regex_full_match(x,substring)


def compute_palindrome(x):
    char = tf.string_split([x], delimiter="",result_type="RaggedTensor")
    reverse = tf.reverse(char.values,[0])
    join = tf.strings.reduce_join(reverse,separator="")
    return join 
    
ds = tf.data.Dataset.from_tensor_slices(["Ottawa", "Stockholm", "Rabat"])

ds = ds.map(
    lambda city: (city, 
                  compute_length(city), 
                  check_substring(city, ".*lm.*"),
                  compute_palindrome(city),
                  ),
        )

num_elems = len(ds.element_spec)
for elem in ds:
   print(''.join([f"{elem[i]}" for i in range(num_elems)]))
```
below is the working code , also the issue was you were using python functions not TF API to do the conversion. 

To do everything more vectorized without writing python function i would recommend using vector operations.

**Comment by 17patelumang** [comment]
@ravikyram  does my respond answer the question ? , Also is there any gist or doc i can write for this ?

**Comment by laghaout** [comment]
Thanks, I now see how one should use the TensorFlow API instead of plain Python code. That said, I'm afraid your code does not work _as is_ with TensorFlow 2.0.0 and Python 3.7.4. Below are the errors that came up

1. `AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'`
2. `AttributeError: module 'tensorflow' has no attribute 'string_split`
3. `TypeError: string_split_v2() got an unexpected keyword argument 'delimiter'`
4. `TypeError: string_split_v2() got an unexpected keyword argument 'result_type'`

and my attempts at solving them

1. comment out `tf.enable_eager_execution()`.
2. change `tf.string_split()` to `tf.strings.split()`
3. change `delimiter` to `sep` in `tf.strings.split()`
4. removed the `result_type` parameter in `tf.strings.split()`

After all these changes, the output is 

> WARNING:tensorflow:Entity <function <lambda> at 0x000001D531AF4318> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
> WARNING: Entity <function <lambda> at 0x000001D531AF4318> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 
> b'Ottawa'6Falseb'Ottawa'
> b'Stockholm'9Trueb'Stockholm'
> b'Rabat'5Falseb'Rabat'

where `compute_palindrome()` does not seem to have accomplished its goal.

**Comment by 17patelumang** [comment]
@laghaout i tried in tf 1.15.x since no version was mention in your ticket . Things are different in tf2.0 , eager execution is enabled by default. 

 Also based on your code `compute_palindrome` does reversing string . 

Below is code for TF 2.0 

```
import tensorflow as tf



def compute_length(x): 
    return tf.strings.length(x)

def check_substring(x, substring):
    return tf.strings.regex_full_match(x,substring)


def compute_palindrome(x):
    extra_split = tf.strings.bytes_split(x)
    reverse = tf.reverse(extra_split,[0])
    reversedStr = tf.strings.reduce_join([reverse])
    return reversedStr
    
ds = tf.data.Dataset.from_tensor_slices(["Ottawa", "Stockholm", "Rabat"])

ds = ds.map(
    lambda city: (city, 
                  #compute_length(city), 
                  #check_substring(city, ".*lm.*"),
                  compute_palindrome(city),
                  ),
        )

num_elems = len(ds.element_spec)
for elem in ds:
   print(''.join([f"{elem[i]}" for i in range(num_elems)]))
```
 
@gowthamkpr  please let me know is there any gist or doc i can write for this ?

**Comment by gowthamkpr** [comment]
@17patelumang You can make a colab gist of this [here](https://colab.sandbox.google.com/) and share the gist. Thanks!

**Comment by 17patelumang** [comment]
@gowthamkpr this is the gist - [gist](https://colab.research.google.com/drive/1gExuU2sCs6OeHtexI22srN7gAti9C9c4#scrollTo=8TvMWDmhlcSY)

**Comment by gowthamkpr** [comment]
Thanks @17patelumang 
@laghaout Please let me know if I can close the issue as the issue has been resolved.

**Comment by laghaout** [comment]
Yes, thank you.
