### ISSUE TITLE
tf.train.Server E0413...SO_REUSEPORT unavailable on compiling system

### ISSUE THREAD

**Issue by forhonourlx** [tensorflow/tensorflow#38475]
**System information** 
- OS Platform and Distribution:
Linux Ubuntu 18.04.3 LTS
Node0: Linux version 5.3.0-46-generic (buildd@lcy01-amd64-013) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04))
Node1:Linux version 5.6.3-050603-generic (kernel@kathleen) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu1))
- TensorFlow installed from (source or
binary): 2.1.0  installed from conda
- Python version: - Anaconda python 3.6.12
- CUDA/cuDNN version: 10.2 
- GPU model and memory: RTX 2080TI 11GB

**Standalone code to reproduce the issue** 
```
#Both Node0 & Node1:
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
cluster_def = {'worker':['192.168.1.5:4448','192.168.1.2:4449']}

#Node0-192.168.1.5:4448:
server = tf.train.Server(cluster_def, job_name='worker', task_index=0)

#Node1-192.168.1.2:4449:
server = tf.train.Server(cluster_def, job_name='worker', task_index=1)
```

**Describe the expected behavior**
On Node1-192.168.1.2:4449, return:
E0413 00:11:52.803623615    2266 socket_utils_common_posix.cc:198] check for SO_REUSEPORT: {"created":"@1586707912.803602543","description":"SO_REUSEPORT unavailable on compiling system","file":"external/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":166}

Could somebody give me a helping hand?
Thanks in advance.

**Comment by gowthamkpr** [comment]
@forhonourlx `tf.train.Server` doesn't exist in tensorflow 2.1 instead it is `tf.distribute.Server` as you can see [here](https://www.tensorflow.org/api_docs/python/tf/distribute/Server).

**Comment by forhonourlx** [comment]
Hi @gowthamkpr ,
I have already blocked with `tf.disable_v2_behavior()`
Even if I use V2 api`server = tf.distribute.Server(cluster_def, job_name='worker', task_index=1)`, I still get the same error on the later joined node:
```
E0414 09:10:05.285892363   10646 socket_utils_common_posix.cc:198] check for SO_REUSEPORT: {"created":"@1586826605.285873543","description":"SO_REUSEPORT unavailable on compiling system","file":"external/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":166}
```

**Comment by gowthamkpr** [comment]
Your system does not have support for `SO_REUSEPORT` and thats the reason for the error. Please take a look at the source of the error [here](https://github.com/grpc/grpc/blob/c923f952946d2586e87ffc91f7edaa9b248f413d/src/core/lib/iomgr/socket_utils_common_posix.cc#L189).

**Comment by forhonourlx** [comment]
Hi @gowthamkpr @amahendrakar ,
Thank you for your reply, and I need some further help.
It was said that Linux kernel >3.9 supports `SO_REUSEPORT` feature.
My testing system is:
```
Linux Ubuntu 18.04.3 LTS
Node0: Linux version 5.3.0-46-generic (buildd@lcy01-amd64-013) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04))
Node1:Linux version 5.6.3-050603-generic (kernel@kathleen) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu1))
```
And there is truely `#define SO_REUSEPORT 15` in `/usr/include/asm-generic/socket.h`

So what is the way to use `tf.distribute` on `Ubuntu`? (same error on `MultiWorkerMirroredStrategy`)
(Or is there any way to skip `check for SO_REUSEPORT`?)

Thanks in advance,
Simon

**Comment by gowthamkpr** [comment]
@forhonourlx Were you able to resolve this issue or are you still facing it?

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for a long time. Please add additional comments for us to open this issue again. Thanks!

**Comment by gronka** [comment]
I found this issue occurs after I edit xorg.conf. I'm on PopOS. 

I opened a bug at https://issuetracker.google.com/issues/164794508
