### ISSUE TITLE
[tflite] FlexAddV2

### ISSUE THREAD

**Issue by fcqfcq** [tensorflow/tensorflow#38478]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
# Copy and paste here
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by fcqfcq** [comment]
model_path ='converted_model_tf2.tflite'
interpreter = tf.lite.Interpreter(model_path=model_path)
interpreter.allocate_tensors()



      1 model_path ='converted_model_tf2.tflite'
      2 interpreter = tf.lite.Interpreter(model_path=model_path)
----> 3 interpreter.allocate_tensors()

/anaconda/envs/tf1.15/lib/python3.6/site-packages/tensorflow_core/lite/python/interpreter.py in allocate_tensors(self)
    242   def allocate_tensors(self):
    243     self._ensure_safe()
--> 244     return self._interpreter.AllocateTensors()
    245 
    246   def _safe_to_run(self):

/anaconda/envs/tf1.15/lib/python3.6/site-packages/tensorflow_core/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py in AllocateTensors(self)
    104 
    105     def AllocateTensors(self):
--> 106         return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
    107 
    108     def Invoke(self):

RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you invoke the Flex delegate before inference.Node number 2 (FlexAddV2) failed to prepare.

**Comment by ymodak** [comment]
How are you converting the mode to tf lite?
If using `target_spec.supported_ops` can you try to convert the model with `TFLITE_BUILTINS`?
```python
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS]
tflite_model = converter.convert()
```

**Comment by hajuho** [comment]
To run the model with select TF operators,  you can follow the method in https://www.tensorflow.org/lite/guide/ops_select#running_the_model.
Unfortunately, python package for select TF operators are not supported yet. You can run the model using Android or iOS  library.
