### ISSUE TITLE
tf.data.Dataset.map() uses only 1 cpu

### ISSUE THREAD

**Issue by netw0rkf10w** [tensorflow/tensorflow#38473]
**System information** 
- Have I written custom code: No
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from: binary
- TensorFlow version: v2.2.0-rc1-34-ge6e5d6df2a 2.2.0-rc2
- Python version: 3.7.5
- CUDA/cuDNN version: 10.1.1/7.6.5
- GPU model and memory: GTX 1080 Ti.

**Describe the current behavior**
When checking with the `top` command during training, only 1 CPU is used.

**Describe the expected behavior**
Multiple CPUs should be used.

**Standalone code to reproduce the issue** 

You can take the code from the [official TensorFlow tutorial on image segmentation](https://www.tensorflow.org/tutorials/images/segmentation).

For a more convincing experiment, replace the two lines:

```python
train = dataset['train'].map(load_image_train, num_parallel_calls=tf.data.experimental.AUTOTUNE)
test = dataset['test'].map(load_image_test)
```

with e.g.

```python
train = dataset['train'].map(load_image_train, num_parallel_calls=4)
test = dataset['test'].map(load_image_test, num_parallel_calls=4)
```

**Comment by jsimsa** [comment]
`tf.data.Dataset.map` with `num_parallel_calls` is known to execute computation in parallel and the instructions provided here are not sufficient to reproduce the issue. 

Please provide a minimal example that can be used to reproduce the issue. As a side note, instead of using `top`, I recommend using `sar` to measure CPU utilization.

**Comment by netw0rkf10w** [comment]
@jsimsa I can certainly provide a stand-alone script for that, but just to make sure I didn't get it right:

1. In TensorFlow: `top` shows only 1 process, but `htop` shows multiple threads.
2. In PyTorch, `top` shows multiple processes for the same training.

So, I guess `tf.data.Dataset.map` also does it in parallel, but by using threads instead of different processes? Sorry if the question is stupid, I am not so familiar with these things.

**Comment by jsimsa** [comment]
tf.data indeed uses multi-threading as it is has lower overhead compared to multi-processing.

**Comment by netw0rkf10w** [comment]
@jsimsa Thanks for the confirmation. Let me close this issue.
