### ISSUE TITLE
How to explain the result of tf.map_fn?

### ISSUE THREAD

**Issue by xueyuan1990** [tensorflow/tensorflow#38489]
```
item_map = {223368: 2, 227300: 3}
i =tf.reshape([223368,223368], [-1, ])
o1 = tf.map_fn(lambda x: item_map.get(x, 0),i)
o2 = tf.map_fn(lambda x: item_map.get(223368, 0), i)
o3 = tf.map_fn(lambda x:x, i)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(i.eval())  #输出[223368 223368]
    print(o1.eval()) #输出[0 0]
    print(o2.eval()) #输出[2 2]
    print(o3.eval()) #输出[223368 223368]
```
why o1 is [0,0]?

**Comment by Saduf2019** [comment]
@xueyuan1990 
the code shared is incomplete for us to replicate it, please share complete standalone code.

As your question is related to understanding tf.map_fn, please refer to [this link](https://stackoverflow.com/questions/45905601/how-does-tf-map-fn-work/46154051) and let us know if it helps.
[link2](https://stackoverflow.com/questions/46096767/how-to-explain-the-result-of-tf-map-fn) , 
[link3](https://blog.csdn.net/u012193416/article/details/86565633) ,
[link4](https://www.tensorflow.org/api_docs/python/tf/map_fn)

**Comment by Saduf2019** [comment]
@xueyuan1990
please update as per above comment

**Comment by Saduf2019** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
