### ISSUE TITLE
How to obtain the activation value of neural network in Tensorflow 2.0?

### ISSUE THREAD

**Issue by TeilyMa** [tensorflow/tensorflow#38485]
I used a simple data set mnist to train the neural network, but I want to get the activation value (output) of the last layer of the neural network, how should I do it?

The structure of my neural network is as follows
```
inputs = tf.keras.Input(shape=(28, 28), name='mnist_input')
h1 = tf.keras.layers.Flatten()(inputs)
h2 = tf.keras.layers.Dense(128, activation='relu')(h1)
h3 = tf.keras.layers.Dense(64, activation='relu')(h2)
outputs = tf.keras.layers.Dense(10, activation='softmax', name='outputs')(h3)
model = tf.keras.Model(inputs, outputs)
```

I try to use the callback function `on_epoch_end` to do this. Use `eval()` method on `model.outputs [0]` in the `on_epoch_end` method to get the activation value. But I got an error message: 
> {InvalidArgumentError} You must feed a value for placeholder tensor 'outputs/MatMul/ReadVariableOp/resource' with dtype resource

It seems that what is saved in model is only the framework of the neural network and does not fill in the data. How do I get the activation value after filling in the data?

**Comment by Saduf2019** [comment]
@TeilyMa 
please share the complete code for us to replicate the issue faced along with the tensorflow version.

**Comment by TeilyMa** [comment]
@Saduf2019 Thank you for your attention. I have solved the problem.
