### ISSUE TITLE
Coredump in tensorflow 1.12.0

### ISSUE THREAD

**Issue by zijiaozeng** [tensorflow/tensorflow#38494]
```
Corefile information as follow:
#0  0x00007fb46bf905f7 in raise () from /lib64/libc.so.6
#1  0x00007fb46bf91ce8 in abort () from /lib64/libc.so.6
#2  0x00007fb46bfd0317 in __libc_message () from /lib64/libc.so.6
#3  0x00007fb46bfd8023 in _int_free () from /lib64/libc.so.6
#4  0x00007fb3dd81616b in std::_Function_base::_Base_manager<std::_Bind<std::_Mem_fn<void (tensorflow::(anonymous namespace)::ExecutorState::*)(tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, long long)> (tensorflow::(anonymous namespace)::ExecutorState*, tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, long long)> >::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation) () from /opt/anaconda2/lib/python2.7/site-packages/tensorflow/python/../libtensorflow_framework.so
#5  0x00007fb3dd89254d in Eigen::NonBlockingThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int) () from /opt/anaconda2/lib/python2.7/site-packages/tensorflow/python/../libtensorflow_framework.so
#6  0x00007fb3dd891582 in std::_Function_handler<void (), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () from /opt/anaconda2/lib/python2.7/site-packages/tensorflow/python/../libtensorflow_framework.so
#7  0x00007fb3dcdaf220 in ?? () from /lib64/libstdc++.so.6
#8  0x00007fb46ca2cdc5 in start_thread () from /lib64/libpthread.so.0
#9  0x00007fb46c05129d in clone () from /lib64/libc.so.6
```

**System information** 
- Python 2.7
- CentOS 
- Tensorflow 1.12.0
- TensorFlow installed from: tensorflow-1.12.0-cp27-cp27mu-manylinux1_x86_64.whl
- GCC 4.8.5

Has anyone ever been faced with same issue?

**Comment by Saduf2019** [comment]
@zijiaozeng 
 can you please share the code and error log faced

**Comment by zijiaozeng** [comment]
I can't find any error log in my background inference processes,  it occurred by accident, there are a  core_python_xxx file which has 3 GB I can provide,

**Comment by zijiaozeng** [comment]
> @zijiaozeng
> can you please share the code and error log faced

I can't find any error log in my background inference processes, it occurred by accident (very rare), there are a core_python_xxx file which has 3 GB I can provide.

**Comment by Saduf2019** [comment]
@zijiaozeng
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by mihaimaruseac** [comment]
Recommend switching to 1.15 or later. If you need to use 1.12, please make sure you use the latest patch available, since we have fixed several security vulnerabilities that could produce core dumps.

**Comment by zijiaozeng** [comment]
> Recommend switching to 1.15 or later. If you need to use 1.12, please make sure you use the latest patch available, since we have fixed several security vulnerabilities that could produce core dumps.

Thank you very much.

**Comment by mihaimaruseac** [comment]
If switching has solved the issue, can we close this?

If it didn't, can't you post the new error log? Maybe even some code you're running so we can attempt to reproduce and fix?

**Comment by zijiaozeng** [comment]
Okay, I will try it in the next few days,  If it doesn't work, I'll post detail information include code snippet when located the specific scene where the problem occurs.  No exceptions thrown when the program crash.

**Comment by zijiaozeng** [comment]
> If switching has solved the issue, can we close this?
> 
> If it didn't, can't you post the new error log? Maybe even some code you're running so we can attempt to reproduce and fix?

Okay, I will try it in the next few days,  if it doesn't work, I'll post detail information include code snippet when located the specific scene where the problem occurs.  No exceptions thrown when the program crash.

**Comment by Saduf2019** [comment]
@ziliangpeng 
please confirm if we may move this to resolved status
