### ISSUE TITLE
ERROR: Config value download_clang is not defined in any .rc file

### ISSUE THREAD

**Issue by ac1991** [tensorflow/tensorflow#38491]
tensorflow：r2.2
bazel         ：2.0.0

ERROR: Config value download_clang is not defined in any .rc file

print info：
`bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so  --crosstool_top=//external:android/crosstool  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain  --cpu=armeabi-v7a
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'build' from /home/wushengqi/ai/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/wushengqi/ai/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from /home/wushengqi/ai/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/wushengqi/anaconda3/bin/python --action_env PYTHON_LIB_PATH=/home/wushengqi/anaconda3/lib/python3.7/site-packages --python_path=/home/wushengqi/anaconda3/bin/python --config=xla --config=rocm --config=download_clang --action_env ANDROID_NDK_HOME=/home/wushengqi/android/android-ndk-r14b --action_env ANDROID_NDK_API_LEVEL=19 --action_env ANDROID_BUILD_TOOLS_VERSION=29.0.2 --action_env ANDROID_SDK_API_LEVEL=29 --action_env ANDROID_SDK_HOME=/home/wushengqi/android/Sdk --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file /home/wushengqi/ai/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /home/wushengqi/ai/tensorflow/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:rocm in file /home/wushengqi/ai/tensorflow/.bazelrc: --crosstool_top=@local_config_rocm//crosstool:toolchain --define=using_rocm=true --define=using_rocm_hipcc=true --action_env TF_NEED_ROCM=1
ERROR: Config value download_clang is not defined in any .rc file
`

If I'm using a lower version of bazel（1.2.1）：
`bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so  --crosstool_top=//external:android/crosstool  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain  --cpu=armeabi-v7a
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'build' from /home/wushengqi/ai/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
ERROR: Unrecognized option: --experimental_repo_remote_exec
`

**Comment by ac1991** [comment]
I configured in./configure：
`Do you wish to download a fresh release of clang? (Experimental) [y/N]: N
Clang will not be downloaded.
`

The above errors will not be reported again.
I'm going to close this down

**Comment by daravi** [comment]
@jvishnuvardhan  Please re-open this issue. I want to try the experimental feature and download clang as part of the build process since using my local LLVM installation I am getting a build error. However selecting `y` to the question:
```
Do you wish to download a fresh release of clang? (Experimental) [y/N]: y
```
I am getting the error mentioned:
```
> bazel build --repo_env=CC=clang --config=monolithic -c opt //tensorflow/lite:libtensorflowlite.so --verbose_explanations --verbose_failures --explain=build.log
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=123
INFO: Reading rc options for 'build' from /home/puya/src/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/puya/src/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from /home/puya/src/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/puya/.pyenv/versions/core/bin/python3 --action_env PYTHON_LIB_PATH=/home/puya/.pyenv/versions/core/lib/python3.8/site-packages --python_path=/home/puya/.pyenv/versions/core/bin/python3 --config=xla --config=download_clang --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file /home/puya/src/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /home/puya/src/tensorflow/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
ERROR: Config value download_clang is not defined in any .rc file
```
I am trying to build TF 2.3.0 (`//tensorflow/lite:libtensorflowlite.so`) using Bazel 3.1.0 (I don't think this matters but I have also added flex:delegate to libtensorflowlite.so dependencies)

**Comment by terryheo** [comment]
@daravi, I've verified the following command works well with master branch. Could you try it?

```
bazel build --repo_env=CC=clang -c opt //tensorflow/lite:libtensorflowlite.so
```

**Comment by daravi** [comment]
@terryheo I cleared my bazel cache (`~/.cache/bazel`) then tried that and I am getting the same `Config value download_clang is not defined in any .rc file` error. More details:
```
$ ./configure 
You have bazel 3.1.0 installed.

Please specify the location of python. [Default is /home/user/.pyenv/versions/core/bin/python3]: 

Found possible Python library paths:
  /home/user/.pyenv/versions/core/lib/python3.8/site-packages
Please input the desired Python library path to use.  Default is [/home/user/.pyenv/versions/core/lib/python3.8/site-packages]

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: y
Clang will be downloaded and used to compile tensorflow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v2             # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=nonccl         # Disable NVIDIA NCCL support.
Configuration finished
```
I am on CentOS 8 and have a local LLVM 10.0.1 installation. Let me know if there is something else you would want me to try.

**Comment by terryheo** [comment]
@daravi, the option is for TF build.
If you want to use clang for TFLite build, please use "--repo_env=CC=clang" option.
It'll use /usr/bin/clang for your build. (You can check it with "-s" option of Bazel)

**Comment by chamikara1998** [comment]
in configuration, i select not to download clang. Then it worked for me
./configure

**Comment by soorajsunil** [comment]
> in configuration, i select not to download clang. Then it worked for me
> ./configure

this works! thanks.
