### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found. Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by e-lizaveta** [tensorflow/tensorflow#38505]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): pip install
- TensorFlow version: 2
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N?A
- CUDA/cuDNN version: CUDA 10.2,  cuDNN 7.6.5 
- GPU model and memory: Nvidia Quadro M1200, 16 GB RAM

I cannot import tensorflow
This is what I got:
Exception has occurred: ImportError
Traceback (most recent call last): File "C:\Users\khiteliv\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module> from tensorflow.python.pywrap_tensorflow_internal import * File "C:\Users\khiteliv\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module> _pywrap_tensorflow_internal = swig_import_helper() File "C:\Users\khiteliv\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description) File "C:\Users\khiteliv\AppData\Local\Continuum\anaconda3\lib\imp.py", line 242, in load_module return load_dynamic(name, filename, file) File "C:\Users\khiteliv\AppData\Local\Continuum\anaconda3\lib\imp.py", line 342, in load_dynamic return _load(spec) ImportError: DLL load failed: The specified module could not be found. Failed to load the native TensorFlow runtime. 

Thank you for your help!

**Comment by e-lizaveta** [comment]
> From the template it looks like you are installing **TensorFlow** (TF) prebuilt binaries:
> 
> * For TF-GPU - See point 1
> * For TF-CPU - See point 2
> 
> **1. Installing **TensorFlow-GPU** (TF) prebuilt binaries**
> 
> _TF Version >= 1.13 requires CUDA 10.0 and TF Version < 1.13 (till TF 1.5) requires CUDA 9.0._
> 
> * If you have above configuration and using _**Windows**_ platform -
>   
>   * Try adding the CUDA, CUPTI, and cuDNN installation directories to the %PATH% environment variable.
>   * Refer [windows setup guide](https://www.tensorflow.org/install/gpu#windows_setup).
> * If you have above configuration and using _**Ubuntu/Linux**_ platform -
>   
>   * Try adding the CUDA, CUPTI, and cuDNN installation directories to the $LD_LIBRARY_PATH environment variable.
>   * Refer [linux setup guide](https://www.tensorflow.org/install/gpu#linux_setup).
> * If error still persists then, apparently your CPU model does not support AVX instruction sets.
>   
>   * Refer [hardware requirements](https://www.tensorflow.org/install/pip#hardware-requirements).
> 
> **2. Installing **TensorFlow** (TF) CPU prebuilt binaries**
> 
> _TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets._
> 
> Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.
> Apparently, your CPU model does not support AVX instruction sets. You can still use TensorFlow with the alternatives given below:
> 
> * Try Google Colab to use TensorFlow.
>   
>   * The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true).You get pre-installed latest stable TF version. Also you can use`pip install` to install any other preferred TF version.
>   * It has an added advantage since you can you easily switch to different hardware accelerators (cpu, gpu, tpu) as per the task.
>   * All you need is a good internet connection and you are all set.
> * Try to build TF from sources by changing CPU optimization flags.
> 
> _Please let us know if this helps._

I updated my PATH variable - it didn't help.

**Comment by av8ramit** [comment]
Closing as duplicate.

https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
