### ISSUE TITLE
tf-trt converted deep models int8 inference crashes

### ISSUE THREAD

**Issue by prateekpatelsc** [tensorflow/tensorflow#38502]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  NO
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04):  
Version: tf-gpu.1-15.m45 (dlvm)
Based on: Debian GNU/Linux 9.12 (stretch) (GNU/Linux 4.9.0-12-amd64 x86_64\n)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below):  v1.15.2-1-g61ff2cb 1.15.2
- Python version: - Bazel
version (if compiling from source): n/a
- GCC/Compiler version (if compiling from
source): n/a
- CUDA/cuDNN version: - GPU model and memory:
Cuda compilation tools, release 10.0, V10.0.130
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 5

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I am using tf-trt to convert some of the models to different precision mode.
it works fine for fp32 and fp16  (gets converted and inference runs fine)
but int8  only get converted but on inference gives the following error
2020-04-12 10:20:31.123734: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:812] Starting calibration thread on device 0, Calibration Resource @ 0x7fd990004ea0
2020-04-12 10:20:31.123883: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.5
2020-04-12 10:20:31.124498: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.5
2020-04-12 10:20:58.770669: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:812] Starting calibration thread on device 0, Calibration Resource @ 0x7fd96c004e80
2020-04-12 10:21:20.543550: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-04-12 10:29:21.108202: F tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:349] Check failed: t.TotalBytes() == device_tensor->TotalBytes() (1832000 vs. 21467376)
Aborted

**Describe the expected behavior**
model should run faster with int8 ?

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
n/a

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
already attached

**Comment by amahendrakar** [comment]
@prateekpatelsc,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by prateekpatelsc** [comment]
@amahendrakar : unfortunately the code is confidential and private to snap . don't think would be able to share those.

**Comment by amahendrakar** [comment]
@prateekpatelsc,
Is it possible to share a minimal code sample to replicate the error you are facing? Thanks!

**Comment by prateekpatelsc** [comment]
```
from tensorflow.python.compiler.tensorrt import trt_convert as trt
converter = trt.TrtGraphConverter(
	input_graph_def=frozen_graph,
        precision_mode="INT8",
       max_batch_size=2,
	nodes_blacklist=['logits', 'classes'])
frozen_graph = converter.convert()
```

This is 4 lines of code that i use to take my original graph def and convert it to tf-trt optimized graph for precision mode int8 .
the conversion works fine. During inference it takes huge time and then the above stacktrace,
NOTE : if i use precision mode fp32 or fp16 , things work completely fine. 
i have been running this tesla t4 and v100 gpu

**Comment by amahendrakar** [comment]
@prateekpatelsc,
On running the above code, I'm facing an error stating `NameError: name 'frozen_graph' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/432e0c5cda019795e3fd8e2a1ca6eaf8/38502.ipynb). Thanks!

**Comment by prateekpatelsc** [comment]
@amahendrakar : can you please look at the code ,
i sent you a snippet of the code , not the full code right , you definitely need to provide frozen graph for some model

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
