### ISSUE TITLE
BatchNormalization with renorm=True doesn't work with TPU

### ISSUE THREAD

**Issue by vduarte** [tensorflow/tensorflow#38500]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Colab
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: Colab
- **TensorFlow version (use command below)**: Colab
- **Python version**: Colab
- **Bazel version (if compiling from source)**: Colab
- **GCC/Compiler version (if compiling from source)**: Colab
- **CUDA/cuDNN version**: Colab
- **GPU model and memory**: -
- **Exact command to reproduce**: See below

### Describe the problem
BatchNormalization with the argument renorm=True using TPUs in Colab produces an error. It seems to be a bug since the code below works with CPUs and GPUs.

### Source code / logs

# ----------------------- Full code to reproduce the error: -----------------------
import tensorflow as tf

# TPU stuff
tpu = tf.distribute.cluster_resolver.TPUClusterResolver()
tf.config.experimental_connect_to_cluster(tpu)
tf.tpu.experimental.initialize_tpu_system(tpu)
strategy = tf.distribute.experimental.TPUStrategy(tpu)

# Build the network
def build_model():
  from tensorflow.keras import Model
  from tensorflow.keras.layers import Dense, Input, BatchNormalization
  inputs = Input(1)
  x = inputs
  x = Dense(1)(x)
  x = BatchNormalization(renorm=True)(x)
  x = Dense(1, 'relu')(x)
  model = Model(inputs, x)
  return model

with strategy.scope():
  model = build_model()
  model.compile(loss='mse', optimizer='adam')

# --------------------------- Error log:
TypeError                                 Traceback (most recent call last)
<ipython-input-3-abb50f72a18a> in <module>()
     21 
     22 with strategy.scope():
---> 23   model = build_model()
     24   model.compile(loss='mse', optimizer='adam')

12 frames
<ipython-input-3-abb50f72a18a> in build_model()
     14   x = inputs
     15   x = Dense(1)(x)
---> 16   x = BatchNormalization(renorm=True)(x)
     17   x = Dense(1, 'relu')(x)
     18   model = Model(inputs, x)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    920                     not base_layer_utils.is_in_eager_or_tf_function()):
    921                   with auto_control_deps.AutomaticControlDependencies() as acd:
--> 922                     outputs = call_fn(cast_inputs, *args, **kwargs)
    923                     # Wrap Tensors in `outputs` in `tf.identity` to avoid
    924                     # circular dependencies.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/normalization.py in call(self, inputs, training)
    817       if self.renorm:
    818         r, d, new_mean, new_variance = self._renorm_correction_and_moments(
--> 819             new_mean, new_variance, training, inputs_size)
    820         # When training, the normalized values (say, x) will be transformed as
    821         # x * gamma + beta without renorm, and (x * r + d) * gamma + beta

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/normalization.py in _renorm_correction_and_moments(self, mean, variance, training, inputs_size)
    676     # TODO(yuefengz): colocate the operations
    677     update_new_mean = _update_renorm_variable(self.renorm_mean, mean,
--> 678                                               inputs_size)
    679     update_new_stddev = _update_renorm_variable(self.renorm_stddev, stddev,
    680                                                 inputs_size)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/normalization.py in _update_renorm_variable(var, value, inputs_size)
    672       def _fake_update():
    673         return array_ops.identity(var)
--> 674       return tf_utils.smart_cond(training, _do_update, _fake_update)
    675 
    676     # TODO(yuefengz): colocate the operations

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/tf_utils.py in smart_cond(pred, true_fn, false_fn, name)
     63         pred, true_fn=true_fn, false_fn=false_fn, name=name)
     64   return smart_module.smart_cond(
---> 65       pred, true_fn=true_fn, false_fn=false_fn, name=name)
     66 
     67 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/smart_cond.py in smart_cond(pred, true_fn, false_fn, name)
     57   else:
     58     return control_flow_ops.cond(pred, true_fn=true_fn, false_fn=false_fn,
---> 59                                  name=name)
     60 
     61 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py in new_func(*args, **kwargs)
    505                 'in a future version' if date is None else ('after %s' % date),
    506                 instructions)
--> 507       return func(*args, **kwargs)
    508 
    509     doc = _add_deprecated_arg_notice_to_docstring(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py in cond(pred, true_fn, false_fn, strict, name, fn1, fn2)
   1175   if (util.EnableControlFlowV2(ops.get_default_graph()) and
   1176       not context.executing_eagerly()):
-> 1177     return cond_v2.cond_v2(pred, true_fn, false_fn, name)
   1178 
   1179   # We needed to make true_fn/false_fn keyword arguments for

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/cond_v2.py in cond_v2(pred, true_fn, false_fn, name)
     99         false_graph.external_captures,
    100         building_gradient=False,
--> 101         name=scope)
    102 
    103 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/cond_v2.py in _build_cond(pred, true_graph, false_graph, true_inputs, false_inputs, building_gradient, name)
    219   """
    220   _make_indexed_slices_indices_types_match(_COND, [true_graph, false_graph])
--> 221   _check_same_outputs(_COND, [true_graph, false_graph])
    222 
    223   # Add inputs to true_graph and false_graph to make them match. Note that

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/cond_v2.py in _check_same_outputs(op_type, graphs)
    799     for b0_out, bn_out in zip(graphs[0].outputs, graphs[b].outputs):
    800       if b0_out.dtype != bn_out.dtype:
--> 801         error(b, "%s and %s have different types" % (b0_out, bn_out))
    802 
    803 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/cond_v2.py in error(branch_idx, error_detail)
    777             b0_out=graphs[0].structured_outputs,
    778             bn_out=graphs[branch_idx].structured_outputs,
--> 779             detail=error_detail))
    780 
    781   for b in range(1, len(graphs)):

TypeError: true_fn and false_fn arguments to tf.cond must have the same number, type, and overall structure of return values.

true_fn output: Tensor("Identity_1:0", dtype=bool)
false_fn output: Tensor("Identity_1:0", shape=(1,), dtype=float32)

Error details:
Tensor("Identity_1:0", dtype=bool) and Tensor("Identity_1:0", shape=(1,), dtype=float32) have different types

**Comment by Saduf2019** [comment]
@vduarte 
please share the tensor-flow version on which this issue was faced and simple stand alone code for us to replicate the  issue

**Comment by Saduf2019** [comment]
with reference to the error faced, please refer to[ link1](https://stackoverflow.com/questions/47537064/tensorflow-incompatible-return-types-from-tf-cond) [link2](https://github.com/tensorflow/tensor2tensor/issues/311) [link3](https://www.programcreek.com/python/example/90430/tensorflow.cond) , and let us know if it helps

**Comment by vduarte** [comment]
Thanks for the references, but they didn't actually help much.

Here is a link to a colab with sample code illustrating the problem:

https://colab.research.google.com/drive/1TsytWJiFwXZWoJQgZrLKXsRaO_S_u5mo

**Comment by Saduf2019** [comment]
i am able to replicate this issue, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/d6d16410402cc86f97b1c380dcbdd726/38500.ipynb)

**Comment by jhseu** [comment]
Yeah, this is a known issue and is likely will be fixed in TF 2.3.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
