### ISSUE TITLE
Tflite GPU Delegate for Jetson TK1 Platform 32bit K1 GPU

### ISSUE THREAD

**Issue by DOCgould** [tensorflow/tensorflow#38513]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):

v2.1.0

- Are you willing to contribute it (Yes/No):

yes, I'm barely looking into it, and would appreciate help, as the issues ( inevitably ) occur. 

**Describe the feature and the current behavior/state.**

Just getting started, and completely un-optimistic ( but worth a shot right? )

**Will this change the current api? How?**

Hardly,
Will merely require build instructions on how to get openGL ES 3.1 compiled with jetson tk1

**Who will benefit with this feature?**

Anyone who has a aging 32bit TK1 dev board or Nyan-Big Chromebook

**Any Other info.**

OpenGL ES support since Jetpack v1.2
https://developer.nvidia.com/jetson-tk1-development-pack-1_2

**Comment by ravikyram** [comment]
@DOCgould 

 Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!

**Comment by DOCgould** [comment]
Hi @ravikyram,

There are a few devices which use the tk1 processor,
Pulling from the elinux website:

Jetson TK1 development board,[86] Nvidia Shield Tablet,[87] Acer Chromebook 13,[88] HP Chromebook 14 G3,[89] Lenovo ThinkVision 28, Xiaomi MiPad,[90] Snail Games
OBox, UTStarcom MC8718, Google Project Tango tablet,[91] Apalis TK1 System on Module,[92] Fuze Tomahawk F1,[93] JXD Singularity S192[94]

The idea being utilizing the power of the tk1 GPU ( Cuda 6.5 ) alongside the quantized tensorflow application (tflite). 

Excuse me a few hours, I'm going to sleep. But I'll initiate a pull request sometime tomorrow for sure.

**Comment by DOCgould** [comment]
Hey Guys, 

after doing some poking into the repo

Here is my approach

1. Make a Cuda Compiled Interpreter of the ops supported by NNAPI
2. Create a Hook into the GPU Delegate
3. Deploy as Optional in GPU Delegate

Nothing to pull yet( and probably not for a little while either), but Ill keep you posted on my progress!!

**Comment by impjdi** [comment]
Hm, it can go two ways:

- I've seen people making this work on the desktop with linking into Mesa.  As long as your Nvidia GPU has OpenGL driver support, you should be able to make it to work.
- The other direction is ditching the TFLite GPU framework entirely and creating a CUDA delegate.  I've seen some interns going down this path too.

**Comment by impjdi** [comment]
> I think this is going to be really hard, because as of now, the android NDK/SDK appears to be a major component of this.

Yeah, you can't use `--config android_arm64` for desktop use case.  Once you drop that `--config` flag, you'll eventually hit a place that says missing header (or dependency... or something like that) related to OpenGL.  that's where you have to plug in Mesa dependencies.

**Comment by DOCgould** [comment]
Thanks for the input! Also CUDA is absolutely the right choice. This platform is landlocked to CUDA 6.5. I did have good sucess for my use case by Faking the Kernels with a wrapper though.

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
