### ISSUE TITLE
Keras Callbacks `params` API change

### ISSUE THREAD

**Issue by dfalbel** [tensorflow/tensorflow#38512]
In the current nightly there were changes to the `params` attribute in the Callbacks that is affecting custom callbacks code.

**System information** 
- Yes
- Colab

**Describe the current behavior**

The minimal example is:

```
import tensorflow as tf
model = tf.keras.Sequential([tf.keras.layers.Dense(1)])
model.compile(loss = "mse", optimizer = "sgd")
callback = tf.keras.callbacks.Callback()
model.fit(
    [1,2,3],
    [5,6,7],
    callbacks = [callback]
)
callback.params
```

With current 2.2-rc3 we see:

```
{'epochs': 1, 'steps': 1, 'verbose': 1}
```

**Describe the expected behavior**

The expected behavior is a dict with the following parameters:

```
{'batch_size': 32,
 'do_validation': False,
 'epochs': 1,
 'metrics': ['loss'],
 'samples': 3,
 'steps': 1,
 'verbose': 1}
```

Here are colab links for:

2.1: https://colab.research.google.com/drive/1D0o-1J9StBPqnrgnOBH5NuqbxoLHodN4
2.2-rc2: https://colab.research.google.com/drive/15c6gJSCL19xrx68fmgUtFsbXFDDYpg3_

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.2.0rc3](https://colab.research.google.com/gist/amahendrakar/c9d0d40e38c4c9f7adf7dcdd26af82ec/38512-2-2.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/e57fab07562fb0d93ca863af79d44ff1/38512-tf-nightly.ipynb). Works as expected with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/4d7d6b85c7f0614c9222770c910c0762/38512-2-1.ipynb). Please find the attached gist. Thanks!

**Comment by omalleyt12** [comment]
@dfalbel Thanks for the issue!

This change is intended, could you explain your use case and I can advise on how your code can be updated?

**Comment by dfalbel** [comment]
Hi @omalleyt12 ! Thanks for your answer.

In [Keras for R](https://github.com/rstudio/keras) we have a default callback that will display metrics nicely in the RStudio IDE, and write logs to a run tracker. 

This is implemented here (in R, but accessing the Callbacks python class) : https://github.com/rstudio/keras/blob/master/R/metrics-callback.R#L18-L41

We basically use the `params` dictionary to get the name of the metrics that we should track as well as the `do_validation` field.

**Comment by omalleyt12** [comment]
@dfalbel Got it, thanks! The best way to access the name of the Model's metrics in a Callback IMO is to use `self.model.metrics_names`. This should only be accessed after the first batch has completed, since metrics can be created the first time the Model is called on actual data

For `do_validation`, I think it's probably better to make use of the `Callback.on_test_begin` endpoint. If this hook is called, then validation will be performed

**Comment by dfalbel** [comment]
Thanks @omalleyt12, your suggestions were very helpful.

**Comment by tcapelle** [comment]
I am still searching for the API changes... where it the `batch_size` param?

**Comment by rchao** [comment]
`batch_size` is a parameter in `Model.fit`.
