### ISSUE TITLE
ClusterSpec propagation propagates "localhost" to remote

### ISSUE THREAD

**Issue by fesun** [tensorflow/tensorflow#38519]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): No
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): CentOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source orbinary): source
- TensorFlow version (use command below): latest master
- Python version: python3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): gcc8
- CUDA/cuDNN version: - GPU model and memory:

TensorFlow propagates "localhost" instead of real ip address to remote.

Demo code:
one is ps
```python
import tensorflow.compat.v1 as tf                                                                                                                                       
tf.disable_v2_behavior()
server = tf.distribute.Server(tf.train.ClusterSpec({"ps" : ["ps_ip_address:5333"]}), job_name="ps", task_index=0, protocol='grpc')                                          
print("start ps")
server.join() 
```

one worker
```python
import tensorflow.compat.v1 as tf
from tensorflow.core.protobuf import config_pb2
from tensorflow.python.training import server_lib
from tensorflow.core.protobuf import cluster_pb2
import time
tf.disable_v2_behavior()

with tf.device("/job:ps/replica:0/task:0"):
    a = tf.get_variable("param", [10], tf.float32, initializer=tf.zeros_initializer)

with tf.device("/job:worker/replica:0/task:0"):
    update = tf.get_variable("update", [10], tf.float32, initializer=tf.ones_initializer)
    add_op = a.assign_add(update)

init_op = tf.initialize_all_variables()

server = tf.distribute.Server({"localhost": ["worker_ip_address:0"]}, protocol="grpc")
cluster_def = cluster_pb2.ClusterDef()
worker_job = cluster_def.job.add()
worker_job.name = 'worker'
worker_job.tasks[0] = server.target[len('grpc://'):]
ps_job = cluster_def.job.add()
ps_job.name = "ps"
ps_job.tasks[0] = "ps_ip_address:5333"
config = config_pb2.ConfigProto(cluster_def=cluster_def, 
 experimental=config_pb2.ConfigProto.Experimental(share_session_state_in_clusterspec_propagation=True))

with tf.Session(server.target, config=config) as sess:
    sess.run(init_op)
    print(sess.run(add_op))

```
ps and server starts on different machines. The ps starts without worker device information and relies cluster spec propagation to propagates worker device information to ps.
However, from ps log, worker device is propagated as "localhost" to ps.
```console
2020-04-14 13:30:21.673766: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job ps -> {0 -> localhost:5333}
2020-04-14 13:30:21.676047: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:390] Started server with target: grpc://localhost:5333
start ps
2020-04-14 13:36:33.582439: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job worker -> {0 -> localhost:51798}
2020-04-14 13:36:33.582471: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:300] Initialize GrpcChannelCache for job ps -> {0 -> localhost:5333}
```
So ps server tries to create grpc channel to the wrong worker device `localhost:51798` and the session run hangs forever.

I tried to replace `worker_job.tasks[0] = server.target[len('grpc://'):]` with `worker_job.tasks[0] = server.target[len('grpc://'):].replace("localhost", "worker_ip_address")`, but TF failed to create session with following error:
```console
tensorflow.python.framework.errors_impl.InvalidArgumentError: The master (current machine) is not included in the provided cluster_def.  job {
  name: "worker"
  tasks {
    key: 0
    value: "worker_ip_address:43479"
  }
}
job {
  name: "ps"
  tasks {
    key: 0
    value: "ps_ip_address:5333"
  } 
}
```

I changed the code of https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/master_session.cc#L1355 and replaced all localhost with real ip address, it works. I'm not sure if this change will cause other issues.

Any idea how to fix this generally?

**Comment by byronyi** [comment]
Gently ping @guptapriya; Priya, mind to take a look here?

**Comment by byronyi** [comment]
cc @saeta who seems to implemented this feature in the first place.

**Comment by fesun** [comment]
Close this as the PR has been merged.
