### ISSUE TITLE
macosx py38 invalid wheel

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#38515]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macosx 10.15.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.2.0-rc.3 py38
- Python version: 3.8.1
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
invalid wheel for tensorflow 2.2.0-rc.3 for macosx python 3.8
**Provide the exact sequence of commands / steps that you executed before running into the problem**
pip install tensorflow-cpu

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
ERROR: tensorflow-cpu has an invalid wheel, .dist-info directory 'tensorflow-2.2.0rc3.dist-info' does not start with 'tensorflow-cpu'
```

**Comment by mihaimaruseac** [comment]
Apologies. We needed to release macos py38 on a different CI infrastructure and we had a bug in the renaming of the pip.

Fortunately, for mac both `tensorflow` and `tensorflow-cpu` pips are identical. Can you use `tensorflow` instead?

**Comment by alanpurple** [comment]
@mihaimaruseac I see, thx

**Comment by mihaimaruseac** [comment]
We will definitely fix this by the final release

**Comment by mihaimaruseac** [comment]
2.2-rc4 should have the issue solved. Can you check please?

**Comment by alanpurple** [comment]
solved, thx
