### ISSUE TITLE
https://www.tensorflow.org/api_docs/python/tf/saved_model/tag_constants is broken

### ISSUE THREAD

**Issue by rakeshmothukuru1** [tensorflow/tensorflow#38523]
## URL(s) with the issue: 
https://www.tensorflow.org/api_docs/python/tf/saved_model/tag_constants

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/tfx/serving/serving_basic#train_and_export_tensorflow_model

## Description of issue (what needs changing):
In the explanation corresponding to **`tags`** in [this link](https://www.tensorflow.org/tfx/serving/serving_basic#train_and_export_tensorflow_model), the Hyperlink corresponding to the Text, related [TensorFlow API documentation](https://www.tensorflow.org/api_docs/python/tf/saved_model/tag_constants) is broken.

### Clear description

This link is useful for the community to understand the purpose of different Tags used while Saving a Model.

### Parameters defined

Are all parameters defined and formatted correctly? : Yes

### Returns defined

Are return values defined? : N/A

**Comment by lamberta** [comment]
Thanks, for the report.
On page, search for "For more details, see tag_constants.py and related TensorFlow API documentation."
