### ISSUE TITLE
TFLite_Convertor cannot convert atrous_conv PB to tflite file

### ISSUE THREAD

**Issue by RunnerZhong** [tensorflow/tensorflow#38529]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): 
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Linux Redhat 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: Desktop
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below):  1.13.1
- Python version: - Bazel
version (if compiling from source): 3.6.5
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory: CPU

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
write a simple artous_conv model to convert like below:

input = tf.compat.v1.placeholder(tf.float32, shape=(1, 244, 244, 3))
    filter = [11, 11, 3, 64]

    filter_weight = tf.compat.v1.get_variable(
        "weights", filter,
        initializer=tf.truncated_normal_initializer(stddev=0.1)
    )
    tf.nn.atrous_conv2d(value=input, filters=filter_weight, rate=2,
                        padding='VALID')

Convert this PB to tflite by TFlite_convertor with below cmd:

tflite_convert --output_file=test.tflite --graph_def_file=frozen.pb --input_arrays=Placeholder --output_arrays=convolution/BatchToSpaceND

Error happened:

 "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2020-04-14 18:35:43.409903: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 5 operators, 11 arrays (0 quantized)
2020-04-14 18:35:43.410080: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 5 operators, 11 arrays (0 quantized)

**Describe the expected behavior**
Should be converted without error

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@RunnerZhong,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by RunnerZhong** [comment]
Hi, you can reproduce this issue with below code easily..

`
graph = tf.Graph()

with graph.as_default():
    input = tf.compat.v1.placeholder(tf.float32, shape=(1, 244, 244, 3))
    filter = [11, 11, 3, 64]

    filter_weight = tf.compat.v1.get_variable(
        "weights", filter,
        initializer=tf.compat.v1.truncated_normal_initializer(stddev=0.1)
    )
    tf.nn.atrous_conv2d(value=input, filters=filter_weight, rate=2,
                        padding='VALID')

with tf.compat.v1.Session(graph=graph) as sess:
    sess.run(tf.compat.v1.global_variables_initializer())
   
    frozen_graph_def = tf.compat.v1.graph_util.convert_variables_to_constants(sess, sess.graph_def, ["convolution/BatchToSpaceND"])

    with open("/home/runner/PycharmProjects/tf/frozen.pb", 'wb') as f:
        f.write(frozen_graph_def.SerializeToString())

converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph("/home/runner/PycharmProjects/tf/frozen.pb",
                                                      ["Placeholder"], ["convolution/BatchToSpaceND"])

tflite_model = converter.convert()
open("/home/runner/PycharmProjects/tf/test.tflite", "wb").write(tflite_model)`

**Comment by RunnerZhong** [comment]
Same issue existed in TF： 1.15

**Comment by karimnosseir** [comment]
@RunnerZhong can you please try TF 2.2 / nightly and let us know if it still exists.

Thanks

**Comment by RunnerZhong** [comment]
Issue cannot reproduce in tf_nightly ..

**Comment by RunnerZhong** [comment]
Closed as this issue disappeared in latest tf version
