### ISSUE TITLE
cifar10_eval.py Error

### ISSUE THREAD

**Issue by dansileshi** [tensorflow/tensorflow#3852]
python cifar10_eval.py
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:01:00.0
Total memory: 12.00GiB
Free memory: 281.36MiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:839] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:01:00.0)
W tensorflow/core/common_runtime/bfc_allocator.cc:213] Ran out of memory trying to allocate 68.02MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.

**Comment by sherrym** [comment]
281MB is probably not enough to run CIFAR10.

Could you please run nvidia-smi to see what other binaries might be using up memory?

Sherry

**Comment by dansileshi** [comment]
Thanks sherry. Here is what got 
+------------------------------------------------------+                       
| NVIDIA-SMI 352.63     Driver Version: 352.63         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 0000:01:00.0      On |                  N/A |
| 28%   68C    P2    79W / 250W |  11891MiB / 12284MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1189    G   /usr/bin/X                                     178MiB |
|    0      2090    G   compiz                                         123MiB |
|    0      2313    G   /usr/lib/firefox/firefox                         2MiB |
|    0      2586    C   python                                         111MiB |
|    0      2686    C   .../dan/anaconda2/envs/tensorflow/bin/python   111MiB |
|    0     18361    G   itksnap                                          8MiB |
|    0     26483    G   MATLAB                                          63MiB |
|    0     32609    C   python                                       11257MiB |
+-----------------------------------------------------------------------------+

**Comment by sherrym** [comment]
Maybe close a few of those applications before trying to run cifar?

**Comment by dansileshi** [comment]
after closing, some of the apps works fine but strange error

pciBusID 0000:01:00.0
Total memory: 12.00GiB
Free memory: 11.49GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:839] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:01:00.0)
2016-08-16 20:54:12.681518: precision @ 1 = 0.866
E tensorflow/core/client/tensor_c_api.cc:485] Enqueue operation was cancelled
	 [[Node: input_producer/input_producer_EnqueueMany = QueueEnqueueMany[Tcomponents=[DT_STRING], _class=["loc:@input_producer"], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer, input_producer/RandomShuffle)]]

**Comment by sherrym** [comment]
The observed message is expected when we close the queue. Is eval working for you?

**Comment by dansileshi** [comment]
Yes. Thank you
