### ISSUE TITLE
Installation on Android with armv8

### ISSUE THREAD

**Issue by B0yma** [tensorflow/tensorflow#38521]
**System information**
- Xiaomi Redmi 5 plus, Redmi Note 8 Pro, Samsung Galaxy A50

i m clone just now project from https://github.com/tensorflow/examples/tree/master/lite/examples/speech_commands/android
build and tried install to the phones and at the end of insall i m getting error - "App not Installed"

**Comment by jianlijianli** [comment]
Unassign myself as I am not the expert on this.

**Comment by B0yma** [comment]
so if tflite do not supported armv8 you may close it

**Comment by terryheo** [comment]
@B0yma could you share logcat output when you installed the app?

**Comment by B0yma** [comment]
in logs there is nothing...

guys i found problem, i get one of this devices...

so problem was that when i connect my telephone and install via studio app on my device it was installed correctly, but when i transfered apk from my telephone to other devices application wont started. The solution is to generate realese apk build and thats all
