### ISSUE TITLE
ERROR: C:/users/alex/_bazel_alex/xv6zejqw/external/flatbuffers/src/BUILD:40:1: C++ compilation of rule '@flatbuffers//src:flatc' failed (Exit -1).

### ISSUE THREAD

**Issue by marimomo00** [tensorflow/tensorflow#38525]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): source
- TensorFlow version: r2.1
- Python version: 3.6.0
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.29.1
- GCC/Compiler version (if compiling from source): VS2019
- CUDA/cuDNN version: n
- GPU model and memory: n

**Describe the problem**
I'm trying to compile tensorflow lite for android use. But I failed.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. setup environment according to
https://www.tensorflow.org/install/source_windows

2. git checkout r2.1 (I tried the master but same error)

3. configure
C:\tensorflow>configure
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
WARNING: Waiting for server process to terminate (waited 10 seconds, waiting at most 60)
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.29.1 installed.
Please specify the location of python. [Default is D:\Program Files\Python\Python36\python.exe]:

Found possible Python library paths:
  D:\Program Files\Python\Python36\lib\site-packages
Please input the desired Python library path to use.  Default is [D:\Program Files\Python\Python36\lib\site-packages]

Do you wish to build TensorFlow with XLA JIT support? [y/N]: n
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:

Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: y
Eigen strong inline overridden.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v2             # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=nonccl         # Disable NVIDIA NCCL support.
Configuration finished

4. Build with
bazel build -c opt --cxxopt=--std=c++11 --config=android_arm //tensorflow/lite/c:libtensorflowlite_c.so

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

C:\tensorflow>bazel build -c opt --cxxopt=--std=c++11 --config=android_arm //tensorflow/lite/c:libtensorflowlite_c.so
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Options provided by the client:
  'build' options: --python_path=D:/Program Files/Python/Python36/python.exe
INFO: Reading rc options for 'build' from c:\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --config=v2
INFO: Reading rc options for 'build' from c:\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=D:/Program Files/Python/Python36/python.exe --action_env PYTHON_LIB_PATH=D:/Program Files/Python/Python36/lib/site-packages --python_path=D:/Program Files/Python/Python36/python.exe --config monolithic --copt=-w --host_copt=-w --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=-D_USE_MATH_DEFINES --verbose_failures --distinct_host_configuration=false --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file c:\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:monolithic in file c:\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Found applicable config definition build:android_arm in file c:\tensorflow\.bazelrc: --config=android --cpu=armeabi-v7a --fat_apk_cpu=armeabi-v7a
INFO: Found applicable config definition build:android in file c:\tensorflow\.bazelrc: --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Call stack for the definition of repository 'io_bazel_rules_docker' which is a git_repository (rule definition at C:/users/alex/_bazel_alex/xv6zejqw/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - C:/users/alex/_bazel_alex/xv6zejqw/external/bazel_toolchains/repositories/repositories.bzl:37:9
 - C:/tensorflow/WORKSPACE:37:1
ERROR: Skipping '//tensorflow/lite/c:libtensorflowlite_c.so': no such target '//tensorflow/lite/c:libtensorflowlite_c.so': target 'libtensorflowlite_c.so' not declared in package 'tensorflow/lite/c' defined by C:/tensorflow/tensorflow/lite/c/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//tensorflow/lite/c:libtensorflowlite_c.so': target 'libtensorflowlite_c.so' not declared in package 'tensorflow/lite/c' defined by C:/tensorflow/tensorflow/lite/c/BUILD
INFO: Elapsed time: 13.103s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)

Thanks in advance.

**Comment by jdduke** [comment]
Can you try with TF 2.2? You should be able to build with:

```
bazel build -c opt --cxxopt=--std=c++14 --config=android_arm //tensorflow/lite/c:tensorflowlite_c
```

And it should produce a binary with the appropriate suffix.

**Comment by marimomo00** [comment]
I tried the TF r2.2 with bazel 2.0.0. This is the result.

`C:\tensorflow>bazel build -c opt --cxxopt=--std=c++14 --config=android_arm //tensorflow/lite/c:tensorflowlite_c
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'build' from c:\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=D:/Program Files/Python/Python36/python.exe
INFO: Reading rc options for 'build' from c:\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from c:\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=D:/Program Files/Python/Python36/python.exe --action_env PYTHON_LIB_PATH=D:/Program Files/Python/Python36/lib/site-packages --python_path=D:/Program Files/Python/Python36/python.exe --config=xla --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file c:\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file c:\tensorflow\.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:android_arm in file c:\tensorflow\.bazelrc: --config=android --cpu=armeabi-v7a --fat_apk_cpu=armeabi-v7a
INFO: Found applicable config definition build:android in file c:\tensorflow\.bazelrc: --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
INFO: Found applicable config definition build:windows in file c:\tensorflow\.bazelrc: --copt=/w --copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\tensorflow\.bazelrc: --define framework_shared_object=false
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Call stack for the definition of repository 'io_bazel_rules_docker' which is a git_repository (rule definition at C:/users/alex/_bazel_alex/xv6zejqw/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - C:/users/alex/_bazel_alex/xv6zejqw/external/bazel_toolchains/repositories/repositories.bzl:37:9
 - C:/tensorflow/WORKSPACE:37:1
INFO: Analyzed target //tensorflow/lite/c:tensorflowlite_c (58 packages loaded, 1345 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base C:/users/alex/_bazel_alex/xv6zejqw/sandbox
ERROR: C:/tensorflow/tensorflow/lite/kernels/internal/BUILD:666:1: C++ compilation of rule '//tensorflow/lite/kernels/internal:audio_utils' failed (Exit -1). Note: Remote connection/protocol failed with: execution failed
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("C:\users\alex\_bazel_alex\xv6zejqw\execroot\org_tensorflow\bin\false" -MD -MF bazel-out/armeabi-v7a-opt/bin/tensorflow/lite/kernels/internal/_objs/audio_utils/spectrogram.pic.d -frandom-seed=bazel-out/armeabi-v7a-opt/bin/tensorflow/lite/kernels/internal/_objs/audio_utils/spectrogram.pic.o -fPIC -iquote . -iquote bazel-out/armeabi-v7a-opt/bin -iquote external/fft2d -iquote bazel-out/armeabi-v7a-opt/bin/external/fft2d /w /D_USE_MATH_DEFINES -DWIN32_LEAN_AND_MEAN -DNOGDI /std:c++14 --std=c++1(...)): The system cannot find the file specified.
 (error: 2)
Target //tensorflow/lite/c:tensorflowlite_c failed to build
INFO: Elapsed time: 85.905s, Critical Path: 0.23s
INFO: 0 processes.
FAILED: Build did NOT complete successfully`

**Comment by marimomo00** [comment]
I built the TF r2.2 again. The error is different
```
C:\tensorflow>bazel build -c opt --cxxopt=--std=c++14 --config=android_arm //tensorflow/lite/c:tensorflowlite_c
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'build' from c:\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=D:/Program Files/Python/Python36/python.exe
INFO: Reading rc options for 'build' from c:\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from c:\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=D:/Program Files/Python/Python36/python.exe --action_env PYTHON_LIB_PATH=D:/Program Files/Python/Python36/lib/site-packages --python_path=D:/Program Files/Python/Python36/python.exe --config=xla --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file c:\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file c:\tensorflow\.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:android_arm in file c:\tensorflow\.bazelrc: --config=android --cpu=armeabi-v7a --fat_apk_cpu=armeabi-v7a
INFO: Found applicable config definition build:android in file c:\tensorflow\.bazelrc: --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
INFO: Found applicable config definition build:windows in file c:\tensorflow\.bazelrc: --copt=/w --copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Analyzed target //tensorflow/lite/c:tensorflowlite_c (58 packages loaded, 1345 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base C:/users/alex/_bazel_alex/xv6zejqw/sandbox
ERROR: C:/users/alex/_bazel_alex/xv6zejqw/external/flatbuffers/src/BUILD:8:1: C++ compilation of rule '@flatbuffers//src:flatbuffers' failed (Exit -1). Note: Remote connection/protocol failed with: execution failed
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("C:\users\alex\_bazel_alex\xv6zejqw\execroot\org_tensorflow\bin\false" -MD -MF bazel-out/armeabi-v7a-opt/bin/external/flatbuffers/src/_objs/flatbuffers/idl_parser.d -frandom-seed=bazel-out/armeabi-v7a-opt/bin/external/flatbuffers/src/_objs/flatbuffers/idl_parser.o -iquote external/flatbuffers -iquote bazel-out/armeabi-v7a-opt/bin/external/flatbuffers -Ibazel-out/armeabi-v7a-opt/bin/external/flatbuffers/src/_virtual_includes/flatbuffers /w /D_USE_MATH_DEFINES -DWIN32_LEAN_AND_MEAN -DNOGDI /s(...)): The system cannot find the file specified.
 (error: 2)
Target //tensorflow/lite/c:tensorflowlite_c failed to build
INFO: Elapsed time: 4.497s, Critical Path: 0.05s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by jdduke** [comment]
I think there may be something wrong in your config? Did you run `/.configure` from the root checkout directory and feed it the path to your Android SDK/NDK?

In particular, `-DWIN32_LEAN_AND_MEAN` should not be present in the build command when building with `--config=android_arm`. It's possible this is an issue with the flatbuffer build config, but let's confirm that your configuration is correct first. Can you attach the `.tf_configure_bazelrc` file which should be present in the root of your tensorflow source tree?

**Comment by marimomo00** [comment]
I did run the /.configure, but it didn't ask for path to android SDK/NDK.
There is the .tf_configure.bazelrc file.

[tf_configure.bazelrc.txt](https://github.com/tensorflow/tensorflow/files/4485225/tf_configure.bazelrc.txt)

**Comment by marimomo00** [comment]
Yes, now the configure ask me for path of android NDK.
Now, the error is

```
C:\tensorflow>bazel build -c opt --cxxopt=--std=c++11 --config=android_arm //tensorflow/lite/c:libtensorflowlite_c.so
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'build' from c:\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=D:/Program Files/Python/Python36/python.exe
INFO: Reading rc options for 'build' from c:\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from c:\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=D:/Program Files/Python/Python36/python.exe --action_env PYTHON_LIB_PATH=D:/Program Files/Python/Python36/lib/site-packages --python_path=D:/Program Files/Python/Python36/python.exe --config=xla --define=override_eigen_strong_inline=true --action_env ANDROID_NDK_HOME=D:/library/android_SDK/ndk/android-ndk-r19 --action_env ANDROID_NDK_API_LEVEL=21 --action_env ANDROID_BUILD_TOOLS_VERSION=29.0.3 --action_env ANDROID_SDK_API_LEVEL=29 --action_env ANDROID_SDK_HOME=D:libraryandroid_SDK --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file c:\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file c:\tensorflow\.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:android_arm in file c:\tensorflow\.bazelrc: --config=android --cpu=armeabi-v7a --fat_apk_cpu=armeabi-v7a
INFO: Found applicable config definition build:android in file c:\tensorflow\.bazelrc: --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
INFO: Found applicable config definition build:windows in file c:\tensorflow\.bazelrc: --copt=/w --copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Analyzed target //tensorflow/lite/c:libtensorflowlite_c.so (59 packages loaded, 7376 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base C:/users/alex/_bazel_alex/xv6zejqw/sandbox
ERROR: C:/users/alex/_bazel_alex/xv6zejqw/external/flatbuffers/src/BUILD:24:1: C++ compilation of rule '@flatbuffers//src:flatc_library' failed (Exit 1)
clang.exe: error: no such file or directory: '/w'
clang.exe: error: no such file or directory: '/D_USE_MATH_DEFINES'
clang.exe: error: no such file or directory: '/std:c++14'
Target //tensorflow/lite/c:libtensorflowlite_c.so failed to build
INFO: Elapsed time: 48.965s, Critical Path: 1.75s
INFO: 1 process: 1 local.
FAILED: Build did NOT complete successfully
```

**Comment by jdduke** [comment]
Interesting, looks like building for Android still pulls in some of the Windows build flags despite your setting `--config=android_arm`. I'll see if I can repro.

**Comment by jdduke** [comment]
Looks like this is caused by the following .bazelrc entry:
```
build --enable_platform_specific_config
```

Can you try building with that line commented out or removed in the `.bazelrc` file in your root checkout? If that works, I'll see how we can make the appropriate changes in the default build scripts.

**Comment by jdduke** [comment]
This *should* work now if you re-sync, run `/.configure` again and then build with
```
bazel build -c opt --config=android_arm //tensorflow/lite/c:libtensorflowlite_c.so
```

**Comment by marimomo00** [comment]
I checkout the  master, run configure and it got this

```
C:\tensorflow>bazel build -c opt --config=android_arm //tensorflow/lite/c:libtensorflowlite_c.so
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=118
INFO: Reading rc options for 'build' from c:\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=D:/Program Files/Python/Python36/python.exe
INFO: Reading rc options for 'build' from c:\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from c:\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=D:/Program Files/Python/Python36/python.exe --action_env PYTHON_LIB_PATH=D:/Program Files/Python/Python36/lib/site-packages --python_path=D:/Program Files/Python/Python36/python.exe --config=xla --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file c:\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file c:\tensorflow\.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:android_arm in file c:\tensorflow\.bazelrc: --config=android --cpu=armeabi-v7a --fat_apk_cpu=armeabi-v7a
INFO: Found applicable config definition build:android in file c:\tensorflow\.bazelrc: --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
INFO: Found applicable config definition build:windows in file c:\tensorflow\.bazelrc: --copt=/w --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Build options --copt, --cxxopt, --define, and 6 more have changed, discarding analysis cache.
INFO: Analyzed target //tensorflow/lite/c:libtensorflowlite_c.so (0 packages loaded, 1405 targets configured).
INFO: Found 1 target...
ERROR: C:/users/alex/_bazel_alex/xv6zejqw/external/flatbuffers/src/BUILD:24:1: C++ compilation of rule '@flatbuffers//src:flatc_library' failed (Exit -1). Note: Remote connection/protocol failed with: execution failed
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(199): CreateProcessW("C:\users\alex\_bazel_alex\xv6zejqw\execroot\org_tensorflow\bin\false" -MD -MF bazel-out/armeabi-v7a-opt/bin/external/flatbuffers/src/_objs/flatc_library/flatc.d -frandom-seed=bazel-out/armeabi-v7a-opt/bin/external/flatbuffers/src/_objs/flatc_library/flatc.o -iquote external/flatbuffers -iquote bazel-out/armeabi-v7a-opt/bin/external/flatbuffers -Ibazel-out/armeabi-v7a-opt/bin/external/flatbuffers/src/_virtual_includes/flatc_library -Ibazel-out/armeabi-v7a-opt/bin/external/flatbuffers/src/_v(...)): The system cannot find the file specified.
 (error: 2)
Target //tensorflow/lite/c:libtensorflowlite_c.so failed to build
INFO: Elapsed time: 0.796s, Critical Path: 0.05s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by marimomo00** [comment]
I commented out
build --enable_platform_specific_config
in .bazelrc

and run  configure, compile and got

...
C:\tensorflow>bazel build -c opt --config=android_arm //tensorflow/lite/c:libtensorflowlite_c.so
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=118
INFO: Reading rc options for 'build' from c:\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=D:/Program Files/Python/Python36/python.exe
INFO: Reading rc options for 'build' from c:\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --config=v2
INFO: Reading rc options for 'build' from c:\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=D:/Program Files/Python/Python36/python.exe --action_env PYTHON_LIB_PATH=D:/Program Files/Python/Python36/lib/site-packages --python_path=D:/Program Files/Python/Python36/python.exe --config=xla --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file c:\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file c:\tensorflow\.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:android_arm in file c:\tensorflow\.bazelrc: --config=android --cpu=armeabi-v7a --fat_apk_cpu=armeabi-v7a
INFO: Found applicable config definition build:android in file c:\tensorflow\.bazelrc: --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
INFO: Analyzed target //tensorflow/lite/c:libtensorflowlite_c.so (58 packages loaded, 1450 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base C:/users/alex/_bazel_alex/xv6zejqw/sandbox
ERROR: C:/users/alex/_bazel_alex/xv6zejqw/external/flatbuffers/src/BUILD:8:1: C++ compilation of rule '@flatbuffers//src:flatbuffers' failed (Exit 1)

The target you are compiling requires Visual C++ build tools.
Bazel couldn't find a valid Visual C++ build tools installation on your machine.

Visual C++ build tools seems to be installed at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC
But Bazel can't find the following tools:
    cl.exe, link.exe, lib.exe, ml64.exe

Please check your installation following https://docs.bazel.build/versions/master/windows.html#using

Target //tensorflow/lite/c:libtensorflowlite_c.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.621s, Critical Path: 0.14s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
...

**Comment by marimomo00** [comment]
The master still does not ask for my android sdk configuration when running ./configure.

**Comment by marimomo00** [comment]
For those who have problem on build under windows like me, you could try to build under linux. It works.

**Comment by jdduke** [comment]
> The target you are compiling requires Visual C++ build tools.
> Bazel couldn't find a valid Visual C++ build tools installation on your machine.

Does this build command work for you?
```
bazel build -c opt //tensorflow/lite/c:libtensorflowlite_c.so
```

It's possible that some of the intermediate build targets require some amount of host (MSVC) compilation, in which case you would need to configure bazel accordingly.

**Comment by marimomo00** [comment]
I would like to build for Android. Will this work?

**Comment by yeshwanthraj** [comment]
> 
> 
> Hmm, looks like the Android config option is disabled by default on Windows. Can you try removing [this line](https://github.com/tensorflow/tensorflow/blob/master/configure.py#L1386) and see if that lets you configure the paths properly for Android builds?


Currently the line you pointed to  refers to a statement which gets the current bazel version required to build. Can you specify exactly what is present in that line so it will be clear for any future references.
