### ISSUE TITLE
can not restore adagrad Variable

### ISSUE THREAD

**Issue by yanghzcc** [tensorflow/tensorflow#38537]
for fixed_size_partitioner trainningVariable, adagrad Variable in  tf.GraphKeys.GLOBAL_VARIABLES is：<tf.Variable 'title_rank/title_rank/concat_projection/part_2/Adagrad:0' shape=(15, 1) dtype=float32_ref>
but in saved checkpoint: 'title_rank/concat_projection/ion/part_0/Adagrad', [75, 1]
shape is not right and restore adagrad Variable failed

**Comment by ravikyram** [comment]
@yanghzcc 

Request you to fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
Request you to provide colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster.Thanks!

**Comment by yanghzcc** [comment]
thanks
https://stackoverflow.com/questions/56930685/pywrap-tensorflow-checkpoint-reader-fails-for-ftrl-states-of-partitioned-variabl
the same question

**Comment by ravikyram** [comment]
I have tried on colab with TF version 1.12, 1.15 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/5717d6bd77d0807da3a2c694df303d60/untitled791.ipynb).Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
