### ISSUE TITLE
TensorFlow Object Detection API with Keras model

### ISSUE THREAD

**Issue by SMatusik** [tensorflow/tensorflow#38532]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): partially
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device:  Desktop
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 1.15
- Python version: - Bazel
version (if compiling from source): 3.6.9
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: 10.0/7.6.5
- GPU model and memory: GTX970 4GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I feed custom trained model with a video stream. I would like to use output's bounding boxes to feed 6 different models trained in for example Keras. I use webcam tutorial from Object Detection API. Only way it works for now is to set session by Keras and load model from the beggining. It ruins the performance very much. 

**Describe the expected behavior**
I would like to have more than 1 fps with passing the detected objects to CNN Keras model.

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

[Google Colab code](https://colab.research.google.com/drive/1O-FkQg6PGJ6EtCYzBE4oZeMKS5gbJSsa)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@SMatusik 

I am not able to access the colab code. Request  you to provide access to colab link to reproduce the issue. Thanks!

**Comment by SMatusik** [comment]
It's accessable right now, sorry for mistake

**Comment by ravikyram** [comment]
@SMatusik 

I tried reproducing the issue and i am seeing the below error message `(ImportError: cannot import name 'string_int_label_map_pb2'`).Request you to help me with the reproducible code which helps me in localizing the issue. Thanks!

**Comment by ravikyram** [comment]
@SMatusik 

Any update on this issue please. Thanks!
