### ISSUE TITLE
installation issue-ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

### ISSUE THREAD

**Issue by abhisharma048** [tensorflow/tensorflow#38535]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:NO
- TensorFlow installed from (source or binary):source
- TensorFlow version:2.0
- Python version:3.8.2
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

ImportError: Traceback (most recent call last):
  File "C:\Users\Abhishek Sharma\anaconda3\envs\tfp3.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Abhishek Sharma\anaconda3\envs\tfp3.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Abhishek Sharma\anaconda3\envs\tfp3.8\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Abhishek Sharma\anaconda3\envs\tfp3.8\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Abhishek Sharma\anaconda3\envs\tfp3.8\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment]
@abhisharma048 ,

[#36167 (comment)](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156)

[#36167](https://github.com/tensorflow/tensorflow/issues/36167) [#36151](https://github.com/tensorflow/tensorflow/issues/36151) [#36138](https://github.com/tensorflow/tensorflow/issues/36138) [#36054](https://github.com/tensorflow/tensorflow/issues/36054) [#36045](https://github.com/tensorflow/tensorflow/issues/36045) [#36020](https://github.com/tensorflow/tensorflow/issues/36020) [#36003](https://github.com/tensorflow/tensorflow/issues/36003) [#35988](https://github.com/tensorflow/tensorflow/issues/35988) [#35903](https://github.com/tensorflow/tensorflow/issues/35903) [#35880](https://github.com/tensorflow/tensorflow/issues/35880) [#35865](https://github.com/tensorflow/tensorflow/issues/35865)

**Comment by alessandrodanesi** [comment]
I have the same problem using PyCharm.
TensorFlow version 2.2.0rc3
I tried reinstall new CUDA driver version and  adding the CUDA, CUPTI, and cuDNN installation directories to the %PATH% environment variable.
I have Python version 3.8.2., maybe I have to install the previous version (3.7)?

**Comment by Saduf2019** [comment]
@abhisharma048 
is this still an issue

**Comment by shazz** [comment]
I have the same issue with all version > 2.0.0 (not with 2.0.0) for the prebuilt CPU package, python 3.7 and 3.8.

**Comment by pcgeek86** [comment]
I have the same issue:

* Windows 10 1909
* Python 3.8.2
* Tensorflow-GPU 2.2.0
* NVIDIA CUDA Toolkit 10.2
* cuDNN 10.2 for Windows 10 x64 v7.6.5.32 (`cudnn64_7.dll`)

> ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.
