### ISSUE TITLE
Longer latency after both post quantization and aware-quantization training 

### ISSUE THREAD

**Issue by Sicongzai** [tensorflow/tensorflow#38534]
**System information**

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.4
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
TensorFlow installed from (source or binary): source
TensorFlow version: 1.15.2
Python version: 3.7.7
Installed using virtualenv? pip? conda?: pip
Bazel version (if compiling from source) : 0.26.1
GCC/Compiler version (if compiling from source): None
CUDA/cuDNN version: None
GPU model and memory: None
**Describe the problem

Provide the exact sequence of commands / steps that you executed before running into the problem**

I try to evaluate my TensorFlow Lite model using the tool in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/evaluation/tasks/coco_object_detection I evaluate 3 models: original model, model after full integer quantization and model after aware-quantization training. The model I use is SSD MobileNetV2 in object detection TensorFlow API and trained with another dataset. 

For the data I get, the original model has latency 151954, full interger quantized model's latency: 2970549, aware quantized model's: 945065

My code for running :
  -- \

  //tensorflow/lite/tools/evaluation/tasks/coco_object_detection:run_eval \

  --model_file=/home/sicong/Documents/model_zoo/ssd_mobilenet_v2_coco_2018_03_29/Udacity/Udacity_300_247705/full_integer_quantization_247705_200_dev01_with_input_inference.tflite \

  --ground_truth_images_path=/home/sicong/Documents/datasets/udacity/for_evaluation/images \

  --ground_truth_proto=/home/sicong/Documents/datasets/udacity/for_evaluation/ground_truth_change_id.pbtxt \

  --model_output_labels=/home/sicong/Documents/datasets/udacity/for_evaluation/udacity_label_map_edge_TPU.pbtxt \

  --output_file_path=/home/sicong/Documents/datasets/udacity/for_evaluation/full_integer_quantization_247705_200_dev01_with_input_inference.txt

Thank you for help!

**Comment by Saduf2019** [comment]
@Sicongzai 
please share simple stand alone code for us to replicate the issue faced.

**Comment by Sicongzai** [comment]
Hi, thank you for your response.

For aware-quantization training, I convert and quantize the model following with command line:
export CONFIG_FILE=/home/sicong/Documents/datasets/udacity/ssd_mobilenet_v2_300x300_udacity.config
export CHECKPOINT_PATH=/home/sicong/Documents/model_zoo/ssd_mobilenet_v2_coco_2018_03_29/Udacity/Udacity_300_315109_001/model.ckpt-27404
export OUTPUT_DIR=/home/sicong/Documents/model_zoo/ssd_mobilenet_v2_coco_2018_03_29/Udacity/Udacity_300_315109_001
python object_detection/export_tflite_ssd_graph.py \
--pipeline_config_path=$CONFIG_FILE \
--trained_checkpoint_prefix=$CHECKPOINT_PATH \
--output_directory=$OUTPUT_DIR \
--add_postprocessing_op=true

For full integer quantization, I use the code below:
converter.representative_dataset = representative_data_gen
converter.allow_custom_ops=True
converter.inference_input_type = tf.uint8
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_quant_model = converter.convert()

**Comment by liyunlu0618** [comment]
Did you run eval on a desktop? If so it's expected that the latency of the quantized model is larger than the float one. Currently we only have optimized kernel on mobile devices.
Can you follow the instructions and run eval on an android phone again?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
