### ISSUE TITLE
TimeDistributed fails with GlobalAveragePooling1D layer. 

### ISSUE THREAD

**Issue by nectario** [tensorflow/tensorflow#38547]
I am trying to use Bert to encode chunks of text. I get the 3D output from Bert, and trying to apply GlobalAveragePooling1D. I get list index out of range. Problem seems to be when applying timedistributed layer to globalaveragepooling1d layer. See below.

`   def bert_model(self, max_seq_len, number_of_labels=130, adapter_size=64, bert_config_file=None, bert_ckpt_file=None, bert_model_name=None):

        with tf.io.gfile.GFile(bert_config_file, "r") as reader:
            bc = StockBertConfig.from_json_string(reader.read())
            bert_params = map_stock_config_to_params(bc)
            bert_params.adapter_size = adapter_size
            bert = BertModelLayer.from_params(bert_params, name="bert")

        sentence_input = Input(shape=(max_seq_len,), dtype='float32', name="sentence_input_ids")
        subtitles_input = Input(shape=(self.max_shape[1], max_seq_len), dtype='int32', name="SubtitlesInput")

        bert_output = bert(sentence_input)
        bert_output = GlobalAveragePooling1D()(bert_output)

        self.bert_sentence_model = Model(sentence_input, bert_output)

        segment_time_distributed = TimeDistributed(self.bert_sentence_model, name="TimeDistributedSegment")
        segment_cnn = Conv1D(256, 2, padding="same", strides=1, activation="relu", name="Segment2Conv1D")
        segment_max_pool_2 = MaxPooling1D(pool_size=3, name="Segment2MaxPool1D")

        subtitles_timedistributed = segment_time_distributed(subtitles_input)
        subtitles_cnn = segment_cnn(subtitles_timedistributed)
        subtitles_maxpool = segment_max_pool_2(subtitles_cnn)

        subtitles_dropout = SpatialDropout1D(0.30, name="SubtitlesDropout")(subtitles_maxpool)
        subtitles_pre_attention_output = Dense(256, name="SubtitlesPreAttnOutput")(subtitles_dropout)

        attention_subtitles = Attention(name="SubtitlesAttention")([subtitles_pre_attention_output, subtitles_maxpool])

        subtitles_max_output = GlobalMaxPool1D(name="GlobalMaxPoolSubitles")(attention_subtitles)
        subtitles_avg_output = GlobalAveragePooling1D(name="GlobalAvgPoolSubitles")(attention_subtitles)

        concat_output = Concatenate(axis=-1, name="OutputConcatenate")([subtitles_max_output, subtitles_avg_output])
        dropput = Dropout(0.40)(concat_output)
        output = Dense(number_of_labels, activation="sigmoid", name="Output")(dropput)

        # model = keras.Model(inputs=[sentence_input_ids, token_type_ids], outputs=logits)
        # model.build(input_shape=[(None, max_seq_len), (None, max_seq_len)])
        self.model = Model(inputs=subtitles_input, outputs=output)
        #self.model.build(input_shape=(None, max_seq_len))

        # load the pre-trained model weights
        load_stock_weights(bert, bert_ckpt_file)

        # freeze weights if adapter-BERT is used
        if adapter_size is not None:
            self.freeze_bert_layers(bert)

        self.model.compile(optimizer="adam",
                      loss="binary_crossentropy")

        self.bert_sentence_model.summary()
        self.model.summary()`

Traceback (most recent call last):
  File "C:/Development/Projects/GenrePrediction/GenrePredictionModel.py", line 765, in <module>
    validation_labels=genre_prediction.validation_labels, epochs=1000, batch_size=1)
  File "C:/Development/Projects/GenrePrediction/GenrePredictionModel.py", line 468, in fit_bert
    self.sentence_model, self.model = self.bert_model(max_sentence_length, bert_ckpt_file="D:/Development/Projects/bert_models/"+self.bert_model_name+"/bert_model.ckpt", bert_config_file="D:/Development/Projects/bert_models/"+self.bert_model_name+"/bert_config.json", number_of_labels=len(self.genres))
  **File "C:/Development/Projects/GenrePrediction/GenrePredictionModel.py", line 336, in bert_model
    subtitles_timedistributed = segment_time_distributed(subtitles_input)**
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 773, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\keras\layers\wrappers.py", line 270, in call
    output_shape = self.compute_output_shape(input_shape).as_list()
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\keras\layers\wrappers.py", line 212, in compute_output_shape
    child_output_shape = self.layer.compute_output_shape(child_input_shape)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 768, in compute_output_shape
    layer_output_shapes = layer.compute_output_shape(layer_input_shapes)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\keras\layers\pooling.py", line 591, in compute_output_shape
    return tensor_shape.TensorShape([input_shape[0], input_shape[2]])
IndexError: list index out of range

<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): 
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 
- Python version: - Bazel
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory: 10.1, 7,65

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
Please, let us know TensorFlow version you are using?.Looks like code is incomplete. Request you to share colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by ravikyram** [comment]
@nectario 

Any update on this issue please. Thanks!

**Comment by nectario** [comment]
Issue has been resolved. The issue was fixed in the library bert-for-tf2.
