### ISSUE TITLE
FTRL maths displayed messy

### ISSUE THREAD

**Issue by dirknbr** [tensorflow/tensorflow#38546]
In this doc https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Ftrl the math is messed up

see https://snipboard.io/my0uSb.jpg

using chrome browser

**Comment by amahendrakar** [comment]
@dirknbr,
I have tried different browsers and did not observe any difference in the page. Could you please point out what needs to be corrected? Thanks!

**Comment by dirknbr** [comment]
as per the screenshot, the \abs bit is in red and not rendered correctly

**Comment by ManishAradwad** [comment]
This error is due to mistake in parentheses, it should be `abs(z_{i})` instead of `abs{z_{i}}`. I'd like to fix this but I can't get that file version correctly since it's on different tag. Could you plz tell how can I get the correct file version in my local repository.

**Comment by amahendrakar** [comment]
@dirknbr,
Closing this issue as it is resolved in the [nightly version](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Ftrl?version=nightly).

Please feel free to re-open if mistaken. Thanks!
