### ISSUE TITLE
Beam search for Transformer example

### ISSUE THREAD

**Issue by Crista23** [tensorflow/tensorflow#38548]
Hi! I have been following the Transformer tutorial here https://github.com/tensorflow/docs/blob/master/site/en/tutorials/text/transformer.ipynb and I am wondering how can beam search be implemented to work with the current code? Thanks!

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
