### ISSUE TITLE
Macro pollution (Is it called like this) on windows

### ISSUE THREAD

**Issue by yonghenghuanmie** [tensorflow/tensorflow#38542]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
windows 10 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
binary
- TensorFlow version:
2.1
- Python version:
3.7
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
0.27.1
- GCC/Compiler version (if compiling from source):
visual studio 2019
- CUDA/cuDNN version:
10.2/7
- GPU model and memory:
Turing

**Describe the problem**
Use compiled tensorflow to compile an empty project like this:
`#include <tensorflow/core/framework/tensor.h>

int main(int argc, char const* argv[])
{
    return 0;
}`
I got some errors like this:
warning C4003: not enough arguments for function-like macro invocation 'min'
error C2589: '(': illegal token on right side of '::'
error C2062: type 'unknown-type' unexpected
error C3805: 'type': unexpected token, expected either '}' or a ','.
Then I write `#undef max
#undef min`  on third_party\eigen3\unsupported\Eigen\CXX11\Tensor,it passed compile.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Compile tensorflow to get .dll .lib and header files.
Create an empty vs project,config and use those files.
Write "#include <tensorflow/core/framework/tensor.h>" and compile it.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@yonghenghuanmie Can you please provide more details on your issue? If this is not a bug, then please post this question in stackoverflow where there is a large community to support. If this is more of a bug, then please provide more details. Thanks!

**Comment by RightYou** [comment]
I solved a similar problem.
I got some errors like this: warning C4003: not enough arguments for function-like macro invocation 'min'. 
This is because the macro definition of min in windows.h requires two parameters, so there may be no problem with Linux. This is a namespace conflict, you can use
#undef min
#undef max
to close the macro definition in window.h.
May be useful

**Comment by sullivak-kyra** [comment]
@jvishnuvardhan This is a bug. The simplest possible project linking to tensorflow won't build without a manual workaround. @yonghenghuanmie provided sufficient details to replicate the issue, what more do you need?
