### ISSUE TITLE
Issues of Adam Optimizer on Complex domain

### ISSUE THREAD

**Issue by remifan** [tensorflow/tensorflow#38541]
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow):  Yes
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04):  Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): `conda install -c conda-forge tensorflow-gpu=2.1`
- TensorFlow version (use command below):  2.1.0
- Python version: - 3.7.7
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory: 10.1.243/7.6.5

**Describe the current behavior**

I'm building a custom model that does computation in Complex value domain, we find the performance in accuracy sense by using Adam is worse than that by translating the whole model into a real domain counterpart (2 times network parameters, real and imag parts ), and use same Adam optimizer.

I dig into the sources codes of [Adam](https://github.com/tensorflow/tensorflow/blob/f270180a6caa8693f2b2888ac7e6b8e69c4feaa8/tensorflow/core/kernels/training_ops_gpu.cu.cc#L57), line 57: 

`v_i += one_minus_beta2 * (g_i * g_i - v_i);`

for real numbers, it is correct as g_i * g_i standards for 2nd order moments, while g_i * g_i in the Complex domain is pseudo-variance. Andy M. Sarrof also discuss this behavior in his [thesis](https://andysarroff.com/papers/sarroff2018a.pdf) (page 35, equation 3.56)

However, it is expected that this behavior does not throw errors because it's valid operation.

**Describe the expected behavior**

I suppose in [line 57](https://github.com/tensorflow/tensorflow/blob/f270180a6caa8693f2b2888ac7e6b8e69c4feaa8/tensorflow/core/kernels/training_ops_gpu.cu.cc#L57),  `g_i * g_i` should be replace by `g_i * {conjugate function}(g_i)` as pointed out by Andy M. Sarrof in this thesis [https://andysarroff.com/papers/sarroff2018a.pdf] (page 35, equation 3.56)

**Comment by ravikyram** [comment]
@remifan 

Request you to share colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by ravikyram** [comment]
@remifan 

Any update on this issue please. Thanks!

**Comment by remifan** [comment]
@ravikyram Sorry for being inactive so long, I'm preparing a simple test case to reproduce the issue, I'll update soon, thanks!!

**Comment by remifan** [comment]
@ravikyram Sorry I cannot expose my domain-specific codes to reflect the issues but I've made a simple demo to illustrate the concept, please check the this [notebook](https://github.com/remifan/complex_adam/blob/master/complex_adam_example.ipynb)
`myadam.py` is my modified Adam using `g * conj(g)` as "variance".

In this simple demo, the learning trace of TF2's Adam is biased from the obviously optimal one. I suppose he 2nd-moment term in Adam is intended to regularize the step size in "intensity" sense for reasonable heuristics, rather than touching the direction of the gradient-based on g * g whose angle is not quite related to the variance meaning.

**Comment by ravikyram** [comment]
@remifan 

I tried in colab with TF-GPU 2.1.0 and i am seeing below error (`ModuleNotFoundError: No module named 'myadam'`).Request you to provide colab link or reproducible code in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by remifan** [comment]
@ravikyram I have updated that [notebook ](https://github.com/remifan/complex_adam/blob/master/complex_adam_example.ipynb)to be working inside Colab, or please check this [shared colab](https://colab.research.google.com/github/remifan/complex_adam/blob/master/complex_adam_example.ipynb) for your convenience, thanks!

**Comment by remifan** [comment]
@gowthamkpr @ravikyram Hey, any updates on this issue? Is this issue confirmed from your side?

**Comment by karmel** [comment]
Thank you for this feature request. Because we don't have widespread support for complex numbers in Keras, we can't fix this in one place and ignore the maintenance implications across the rest of the codebase. That said, an Adam Optimizer that handles complex numbers might be of interest to the TF Addons community repo, where special subclasses of Optimizers can live: https://github.com/tensorflow/addons
