### ISSUE TITLE
tf.image.extract_glimpse does not work as it should (tensorflow 2.1)

### ISSUE THREAD

**Issue by patriciacs1994** [tensorflow/tensorflow#38545]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 64 bit
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: No
- **TensorFlow installed from (source or binary)**: NVIDIA (https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes)
- **TensorFlow version (use command below)**: 2.1
- **Python version**: 3.6.9

### Describe the problem
Hello, I am trying to use tf.image.extract_glimpse and I realised that It does not work as it should.
The issue was the same than 4 year ago #7681 and it was solved. But It seems like that in the new version of tensorflow 2.1 it is not fixed.

### Source code / logs
You can try to reproduce this code:

BATCH_SIZE = 1
IMAGE_HEIGHT = 7
IMAGE_WIDTH = 7
CHANNELS = 1
GLIMPSE_SIZE = (3,3)

image = tf.reshape(tf.range(49, delta=1, dtype=tf.float32),
  shape=(BATCH_SIZE, IMAGE_HEIGHT, IMAGE_WIDTH, CHANNELS))

output1 = tf.image.extract_glimpse(image, size=GLIMPSE_SIZE,
  offsets=[[1,1]], centered=False, normalized=False)

output2 = tf.image.extract_glimpse(image, size=GLIMPSE_SIZE,
  offsets=[[2,2]], centered=False, normalized=False)

output1 = [[  0.   1.   2.]
                 [  5.   6.   7.]
                 [ 10.  11.  12.]]

output2 =  [[  0.   1.   2.]
                 [  5.   6.   7.]
                 [ 10.  11.  12.]]

The results are the same, that we got in issue #7681.

**Comment by yongtang** [comment]
@patriciacs1994 I think you are referring to PR #12829?

**Comment by patriciacs1994** [comment]
Yes, I am referring to that issue that was solved 4 years ago. But it seems like that for tf 2.1 the error still persist. Am I wrong?

**Comment by yongtang** [comment]
@patriciacs1994 The PR was merged but seems to have been reverted at one point. Just re-submitted the PR in #38549. It should fix the issue if merged.

**Comment by patriciacs1994** [comment]
Perfect. So, to solve this issue in my machine, how should I proceed? I installed tf through NVIDIA containers (https://ngc.nvidia.com/catalog/containers/nvidia:tensorflow/tags). Is this change applied automatically? Thank you.

**Comment by yongtang** [comment]
@patriciacs1994 After the PR is approved and merged, it will show up in tf-nightly automatically (and will show up in the next version of the release, likely TF 2.3.0+ as TF 2.2.0 release is already imminent).
