### ISSUE TITLE
Building a vocabulary from text data for classification

### ISSUE THREAD

**Issue by rishabhsahrawat** [tensorflow/tensorflow#38540]
I am following this [tutorial](https://www.tensorflow.org/tutorials/load_data/text) and [here](https://www.tensorflow.org/tutorials/load_data/text#build_vocabulary) the documentation says `There are a few ways to do this in both TensorFlow and Python.`. I am wondering what could be other ways of building a vocabulary. The way defined after this is slow for me since it is a loop and my dataset consists over 900,000 text docs.

**Comment by 17patelumang** [comment]
@rishabhkabra other method include as below 

https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/lookup

Sample code 

```
tableLookup= tf.contrib.lookup.index_table_from_file("<path_to_vobab_file>", num_oov_buckets=0, default_value=0)
index = tableLookup.lookup(<tensor_of_Strings>)
```
You can do the preprocessing in python once and store tokens in file and read tokens from that file using above or you can store it in .tFRecord  file for better perfomance

**Comment by amahendrakar** [comment]
@rishabhsahrawat,
Could you please check @17patelumang's comment and let us know if it helps? Thanks!

**Comment by rishabhsahrawat** [comment]
@17patelumang thanks for your suggestion. But how to get the vocab file ?

**Comment by 17patelumang** [comment]
@amahendrakar is there any way i can be assigned few tickets ?

**Comment by rishabhsahrawat** [comment]
@17patelumang thanks for suggestion. On your provided link they are also using a for loop to read each line of the data. 
````
 for i, line in enumerate(f):
        vocab.update(line.strip().split(' '))
````
and the approach mentioned in my question is following:

`````

for text_tensor, _ in all_labeled_data:
  some_tokens = tokenizer.tokenize(text_tensor.numpy())
  vocabulary_set.update(some_tokens)
`````

In my understanding they both will take the same time. Since my dataset has a lot of lines so it is very time taking and I want a solution that is faster.

Maybe @amahendrakar , you can help. 

Thanks:)

**Comment by rishabhsahrawat** [comment]
@17patelumang or do you think `set()` and `Counter()` can make speed differences between the two approaches?

**Comment by rishabhsahrawat** [comment]
Okay, so I tested both set() and Counter() and in my tests, set() is already faster than Counter().
So, my original question is still valid. @17patelumang @amahendrakar

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
 Thanks!

**Comment by rishabhsahrawat** [comment]
My question was about the alternative ways mentioned in the TF documenatation, but OK. 👍
