### ISSUE TITLE
Can not create control inputs with tf.control_dependencies 

### ISSUE THREAD

**Issue by zhao1157** [tensorflow/tensorflow#38556]
I was expecting to get some control inputs with `tf.control_dependencies()`, but the following test code did not give back what I expected.
    
    import tensorflow as tf

    a = tf.get_variable('a', shape = [2, 3])
    b = tf.get_variable('b', shape = [2, 3])
    c = tf.scalar_mul(2, a)
    d = tf.scalar_mul(3, b)

    with tf.control_dependencies([d, c]):
      f = d-c

    print (f.op.control_inputs)

It returned `[]`. If I did the other way

    f = d-c
    f.op._add_control_inputs([c.op, d.op])
    print (f.op.control_inputs)

I got `[<tf.Operation 'Mul' type=Mul>, <tf.Operation 'Mul_1' type=Mul>]`, which seems good. 

So does `tf.control_dependencies()` create control dependencies? Or does `op.control_inputs` reflect all the control inputs? Could this be a bug?

**Comment by gadagashwini** [comment]
Was able to reproduce the issue with Tf1.15.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/481a920d74fafb5e1ed971e1dfd34231/untitled510.ipynb#scrollTo=0NrsY94pUuqc). Thanks

**Comment by ymodak** [comment]
You have to use `tf.Variable` function instead of `tf.get_Variable`. I made a toy example to show `tf.control_dependecies` behavior. 
```python
import tensorflow as tf
tf.reset_default_graph()
a = tf.Variable(name='a', initial_value=2)
b = tf.Variable(name='b', initial_value=1) 
c = tf.multiply(2, a)
d = tf.multiply(3, b)

with tf.control_dependencies([c,d]):
  f = tf.subtract(a,b)

print(f.op.control_inputs)
```
output:
```python
[<tf.Operation 'Mul' type=Mul>, <tf.Operation 'Mul_1' type=Mul>]
```

**Comment by zhao1157** [comment]
@ymodak Thanks, it solved my problem. I know there are some differences between `tf.get_variable()` and `tf.Variable()` about variable sharing, but should control dependencies be one of them?

**Comment by zhao1157** [comment]
@ymodak I just found another problem with `control_flow_ops.with_dependencies`. 

    import tensorflow as tf
    from tensorflow.python.ops import control_flow_ops
    tf.reset_default_graph()
    a = tf.constant([2,3], dtype = tf.float32)
    b = tf.constant([4,5], dtype = tf.float32)
    c = tf.multiply(2., a)
    d = tf.multiply(3., b)

    f = tf.subtract(a, b)
    control_flow_ops.with_dependencies([c, d], f)

    print(f.op.control_inputs)

It returned `[]`.

**Comment by ymodak** [comment]
`control_flow_ops.with_dependencies` is deprecated long time ago. We recommend using  [`tf.control_dependencies`](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/Graph#control_dependencies) with the `with` keyword which does the same things. Thanks!
