### ISSUE TITLE
[SOLVED] How to save TensorForest Model?

### ISSUE THREAD

**Issue by bcordo** [tensorflow/tensorflow#3855]
Thanks for reading. 

I am trying to save a `TensorForestEstimatorModel` and am not sure how to do so. 

I run:

```python
import tensorflow as tf
import tensorflow.contrib.learn

hparams = tf.contrib.tensor_forest.python.tensor_forest.ForestHParams(
        num_trees=3, max_nodes=1000, num_classes=3, num_features=4)
classifier = tf.contrib.learn.TensorForestEstimator(hparams)

iris = tf.contrib.learn.datasets.load_iris()
data = iris.data.astype(np.float32)
target = iris.target.astype(np.float32)

classifier.fit(x=data, y=target, steps=100)
```

And everything works great but I see no method to save the model. That is if I run:

```python
classifier.save('/tmp/tf_examples/my_model_1/')
```

I get the error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-62-0079ac3a857d> in <module>()
----> 1 classifier.save('/tmp/tf_examples/my_model_1/')

AttributeError: 'TensorForestEstimator' object has no attribute 'save'
```

Thanks so much!

### Environment info
Operating System: OS X 10.11.6

If installed from binary pip package, provide:

1. Which pip package you installed.
sudo pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.10.0rc0-py2-none-any.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.10.0rc0

**Comment by sherrym** [comment]
It appears the old estimator has a save function. @martinwicke should know more about the plan.

**Comment by bcordo** [comment]
@sherrym thanks for the response. Is there a way to use a random forest classifier with the old estimator?

**Comment by bcordo** [comment]
Another update that solved my problem. Posting it here for posterity. 

If during the model definition I add the `model_dir` parameter, this loads the model and I can do inference

```python
import tensorflow as tf
import tensorflow.contrib.learn as skflow

hparams = tf.contrib.tensor_forest.python.tensor_forest.ForestHParams(
        num_trees=10, max_nodes=1000, num_classes=2, num_features=5)
classifier = skflow.TensorForestEstimator(hparams, model_dir='/var/folders/k7/x_ddt3gn57z7x452wglt9brh0000gn/T/tmpEJhoS9')

classifier.evaluate(x=X_test, y=y_test, steps=100)
```

And everything works as expected.

**Comment by ManSoSec** [comment]
Is it possible to load graph.pbtxt on the Android ? If no, how is it possible to convert .pbtxt to .pb because the android demo application uses .pb graph file as the model.

Thanks!

**Comment by xp1992slz** [comment]
Thanks for sharing.
