### ISSUE TITLE
TF 1.13 with TRT 6.0

### ISSUE THREAD

**Issue by rgc183** [tensorflow/tensorflow#38557]
Is it possible to modify tensorrt submodule from tensorflow 1.13 to support it with TRT 6.0? Can it support TRT 6.0?
I have seen performance drop for only tensorflow models from TF 1.13 to  TF 1.15. So I want to stick to 1.13 with TRT 6.0.

**Comment by rgc183** [comment]
@jvishnuvardhan @sanjoy Could you please update on this. Thanks.!

**Comment by mihaimaruseac** [comment]
We no longer support versions of TF below 1.15. As such, we no longer patch those versions.

You could try compiling from source, but we won't be able to provide guidance in case of compile errors either.

TF 2.2 which will be released this week/early next week (RC releases are already out) is performance focused and should have significant performance gains.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
