### ISSUE TITLE
error: 'arm_convolve_1_x_n_s8_get_buffer_size' was not declared in this scope

### ISSUE THREAD

**Issue by StephanIFX** [tensorflow/tensorflow#38563]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu18.04 under WSL
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source):  2ddbc3572cd10002cf4e74a9c7b4dbf3d5995d7b
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):   sparkfun_edge

when trying to build person detection app using the cmsis-nn libraries using this command:

`make -f tensorflow/lite/micro/tools/make/Makefile TAGS=cmsis-nn TARGET=sparkfun_edge person_detection_int8_bin`

I run into the following compile error:

`arm-none-eabi-g++ -std=c++11 -DTF_LITE_STATIC_MEMORY -O3 -DPART_apollo3 -DAM_PACKAGE_BGA -DAM_PART_APOLLO3 -DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK -DTF_LITE_STATIC_MEMORY -DNDEBUG -DTF_LITE_MCU_DEBUG_LOG -D __FPU_PRESENT=1 -DARM_MATH_CM4 -fno-rtti -fmessage-length=0 -fno-exceptions -fno-unwind-tables -fno-builtin -ffunction-sections -fdata-sections -funsigned-char -MMD -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -std=gnu++11 -Wvla -Wall -Wextra -Wsign-compare -Wdouble-promotion -Wunused-variable -Wshadow -Wmissing-field-initializers -Wno-unused-parameter -Wno-write-strings -fno-delete-null-pointer-checks -fno-threadsafe-statics -fomit-frame-pointer -fpermissive -fno-use-cxa-atexit -nostdlib -ggdb -O3 -I. -Itensorflow/lite/micro/tools/make/downloads/ -Itensorflow/lite/micro/tools/make/downloads/gemmlowp -Itensorflow/lite/micro/tools/make/downloads/flatbuffers/include -Itensorflow/lite/micro/tools/make/downloads/ruy -Itensorflow/lite/micro/tools/make/downloads/AmbiqSuite-Rel2.2.0/boards_sfe/common/third_party/hm01b0 -isystemtensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/Core/Include/ -isystemtensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/DSP/Include/ -Itensorflow/lite/micro/tools/make/downloads/gcc_embedded//arm-none-eabi/ -Itensorflow/lite/micro/tools/make/downloads/AmbiqSuite-Rel2.2.0/mcu/apollo3/ -Itensorflow/lite/micro/tools/make/downloads/AmbiqSuite-Rel2.2.0/CMSIS/AmbiqMicro/Include/ -Itensorflow/lite/micro/tools/make/downloads/AmbiqSuite-Rel2.2.0/boards_sfe/edge/bsp -Itensorflow/lite/micro/tools/make/downloads/AmbiqSuite-Rel2.2.0/devices/ -Itensorflow/lite/micro/tools/make/downloads/AmbiqSuite-Rel2.2.0/utils/ -Itensorflow/lite/micro/tools/make/downloads/cmsis//CMSIS/Core/Include -Itensorflow/lite/micro/tools/make/downloads/cmsis//CMSIS/NN/Include -Itensorflow/lite/micro/tools/make/downloads/cmsis//CMSIS/DSP/Include -Itensorflow/lite/micro/tools/make/downloads/kissfft -Itensorflow/lite/micro/tools/make/downloads/AmbiqSuite-Rel2.2.0/boards_sfe/common/third_party/lis2dh12/ -c tensorflow/lite/micro/kernels/cmsis-nn/conv.cc -o tensorflow/lite/micro/tools/make/gen/sparkfun_edge_cortex-m4/obj/tensorflow/lite/micro/kernels/cmsis-nn/conv.o
tensorflow/lite/micro/kernels/cmsis-nn/conv.cc: In function 'TfLiteStatus tflite::ops::micro::conv::EvalQuantizedPerChannel(TfLiteContext*, TfLiteNode*, TfLiteConvParams*, tflite::ops::micro::conv::OpData*, const TfLiteTensor*, const TfLiteTensor*, const TfLiteTensor*, TfLiteTensor*, TfLiteTensor*)':
tensorflow/lite/micro/kernels/cmsis-nn/conv.cc:269:30: error: 'arm_convolve_1_x_n_s8_get_buffer_size' was not declared in this scope
     const int32_t buf_size = arm_convolve_1_x_n_s8_get_buffer_size(
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tensorflow/lite/micro/kernels/cmsis-nn/conv.cc:269:30: note: suggested alternative: 'arm_convolve_s8_get_buffer_size'
     const int32_t buf_size = arm_convolve_1_x_n_s8_get_buffer_size(
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                              arm_convolve_s8_get_buffer_size
tensorflow/lite/micro/kernels/cmsis-nn/conv.cc:271:9: error: 'get_cmsis_scratch_buffer' was not declared in this scope
     if (get_cmsis_scratch_buffer(context, &buf, buf_size) != kTfLiteOk) {
         ^~~~~~~~~~~~~~~~~~~~~~~~
tensorflow/lite/micro/tools/make/Makefile:288: recipe for target 'tensorflow/lite/micro/tools/make/gen/sparkfun_edge_cortex-m4/obj/tensorflow/lite/micro/kernels/cmsis-nn/conv.o' failed
make: *** [tensorflow/lite/micro/tools/make/gen/sparkfun_edge_cortex-m4/obj/tensorflow/lite/micro/kernels/cmsis-nn/conv.o] Error 1`

without the TAGS=cmsis-nn flags, the code builds without trouble ...

Best Regards

**Comment by freddan80** [comment]
Hello,

Thanks for reporting this issue! It should be fixed by this PR: https://github.com/tensorflow/tensorflow/pull/38123 (got merged just recently). Remember to clean the downloads folder by typing:

`make -f tensorflow/lite/micro/tools/make/Makefile TAGS=cmsis-nn TARGET=sparkfun_edge clean_downloads`

Cheers!

**Comment by StephanIFX** [comment]
allready fixed indeed. 

Thanks for pointing out.
