### ISSUE TITLE
Memory leak when try to use Metal delegate with “TFLGpuDelegateWaitTypeAggressive” option

### ISSUE THREAD

**Issue by wangshuai-github** [tensorflow/tensorflow#38560]
**System information** 
- Mobile device ：iPhone XR
- OS version：13.3.1

**Describe the current behavior**
I encountered a memory leak problem when trying  to deploy metal delegate backend on iPhone.

**Describe the expected behavior**
There is no memory leak in tflite lib

**Standalone code to reproduce the issue** 
1)	Modify the source code in metal_delegate.mm as follows
At line 109, add “alarm_thread_ = 0; “ during the init of “alarm_thread_”;
### 
      device_ = [command_queue_ device];
      total_alarms_ = 1;
      alarm_thread_ = 0;
      NSString* error;

> Note:
This change is to allow the “alarm_thread” thread to run normally when metal delegate option is set to “TFLGpuDelegateWaitTypeAggressive”. 

2)	Recompile the modified source code, generate tflite framework lib and metal delegate library
3)	Use the IOS project located in lite/examples/ios/camera to test the new lib generated by step 2)
Modify the source code in CameraExampleViewController.mm as follows
> TFLGpuDelegateOptions options; 
  options.allow_precision_loss = true; 
  // options.wait_type = TFLGpuDelegateWaitTypeActive; 
  options.wait_type = TFLGpuDelegateWaitTypeAggressive; 
  delegate = TFLGpuDelegateCreate(&options); 
  interpreter->ModifyGraphWithDelegate(delegate);

4)	Use Xcode IDE to recompile the camera project, it can be seen that when the APP is running on iPhone, the memory keeps growing.

**Other info / logs** Include any logs or source code that would be helpful to

**Comment by windmaple** [comment]
Should have been fixed by 
https://github.com/tensorflow/tensorflow/commit/2a72ad4071b3b5612492f85ee6bd50e35c90128b

**Comment by sushreebarsa** [comment]
@wangshuai-github Could you please have a look at this[ commit ](https://github.com/tensorflow/tensorflow/commit/2a72ad4071b3b5612492f85ee6bd50e35c90128b) probably it is a fixed for this issue . Please let us know if it helps? Thank you!
