### ISSUE TITLE
Need Protobuf pip wheel package for Python 3.4, which is missing the setup doc

### ISSUE THREAD

**Issue by ye** [tensorflow/tensorflow#3856]
Current documentation only gives `protobuf-3.0.0b2.post2-cp35-none-any.whl` but nothing for `python 3.4`.

### Environment info
Operating System: Mac OS X El Capitan 10.11.6

Installed version of CUDA and cuDNN: None (Intel Iris Graphics 6100)

If installed from binary pip package, provide:
TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.10.0rc0-py3-none-any.whl

### Steps to reproduce
1. Follow the Mac [setup steps here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md)
2. Installation completed fine.  
3. Protobuf's package is the pure python one, which is VERY SLOW. The [setup guide](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#protobuf-library-related-issues) only gives a pip wheel package for Python 3.5

### What steps you have tried

```bash
$ pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/protobuf-3.0.0b2.post2-cp35-none-any.whl
protobuf-3.0.0b2.post2-cp35-none-any.whl is not a supported wheel on this platform.

$ pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/protobuf-3.0.0b2.post2-cp34-none-any.whl
Collecting protobuf==3.0.0b2.post2 from https://storage.googleapis.com/tensorflow/mac/protobuf-3.0.0b2.post2-cp34-none-any.whl
  HTTP error 404 while getting https://storage.googleapis.com/tensorflow/mac/protobuf-3.0.0b2.post2-cp34-none-any.whl
  Could not install requirement protobuf==3.0.0b2.post2 from https://storage.googleapis.com/tensorflow/mac/protobuf-3.0.0b2.post2-cp34-none-any.whl because of error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/mac/protobuf-3.0.0b2.post2-cp34-none-any.whl
Could not install requirement protobuf==3.0.0b2.post2 from https://storage.googleapis.com/tensorflow/mac/protobuf-3.0.0b2.post2-cp34-none-any.whl because of HTTP error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/mac/protobuf-3.0.0b2.post2-cp34-none-any.whl for URL https://storage.googleapis.com/tensorflow/mac/protobuf-3.0.0b2.post2-cp34-none-any.whl

```

**Comment by ye** [comment]
Ok, it seems that the same wheel package is compatible with python 3.4. Simply rename the wheel package `protobuf-3.0.0b2.post2-cp35-none-any.whl` to `protobuf-3.0.0b2.post2-cp34-none-any.whl` or `protobuf-3.0.0b2.post2-cp3-none-any.whl` would work. 

So can we update the docs to drop the extra **5** in the wheel package filename so that it would work for both python 3.4 and 3.5?

```bash
$ wget https://storage.googleapis.com/tensorflow/mac/protobuf-3.0.0b2.post2-cp35-none-any.whl
--2016-08-16 16:55:00--  https://storage.googleapis.com/tensorflow/mac/protobuf-3.0.0b2.post2-cp35-none-any.whl
Resolving storage.googleapis.com... 
173.194.68.128, 2607:f8b0:400d:c0c::80
Connecting to storage.googleapis.com|173.194.68.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 422170 (412K) [application/octet-stream]
Saving to: ‘protobuf-3.0.0b2.post2-cp35-none-any.whl’

protobuf-3.0.0b2.post2-cp35-none-any.whl                                                   100%

2016-08-16 16:55:05 (5.37 MB/s) - ‘protobuf-3.0.0b2.post2-cp35-none-any.whl’ saved [422170/422170]

$ mv protobuf-3.0.0b2.post2-cp3{5,4}-none-any.whl
$ pip install --upgrade protobuf-3.0.0b2.post2-cp34-none-any.whl 
Processing ./protobuf-3.0.0b2.post2-cp34-none-any.whl
Requirement already up-to-date: six>=1.9 in /Users/ye/.envs/ai/lib/python3.4/site-packages (from protobuf==3.0.0b2.post2)
Requirement already up-to-date: setuptools in /Users/ye/.envs/ai/lib/python3.4/site-packages (from protobuf==3.0.0b2.post2)
Installing collected packages: protobuf
  Found existing installation: protobuf 3.0.0b2
    Uninstalling protobuf-3.0.0b2:
      Successfully uninstalled protobuf-3.0.0b2
Successfully installed protobuf-3.0.0b2.post2
$ ipython
Python 3.4.3 (default, Jun 10 2015, 19:56:14) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from google import protobuf

In [2]: protobuf.__version__
Out[2]: '3.0.0b2.post2'
```

**Comment by yaroslavvb** [comment]
Except that Jenkins continuous build only tests things for a single Python
3 version, so there's no telling if some new change makes it incompatible
with 3.4

**Comment by ye** [comment]
@yaroslavvb so no love for python 3.4 folks?!

**Comment by martinwicke** [comment]
Have you tested with `protobuf-3.0.0b2.post2-cp3-none-any.whl`? If that works, I'd be happy to rename the file and adjust the docs.

**Comment by ye** [comment]
@martinwicke no I have not tried it yet. Can you tell me where to get it? (I've google'd, nothing came up relevant for `protobuf-3.0.0b2.post2-cp3-none-any.whl`)

**Comment by martinwicke** [comment]
I meant, rename `protobuf-3.0.0b2.post2-cp35-none-any.whl` to `protobuf-3.0.0b2.post2-cp3-none-any.whl` to see if that works.

**Comment by ye** [comment]
@martinwicke Oh ok. In that case, it worked, as I demo'd [15 days ago](#issuecomment-240239696).

**Comment by martinwicke** [comment]
@gunan when you rebuild the protobuf whl, can you rename it and adjust the docs accordingly?

**Comment by gunan** [comment]
New wheel files built, uploaded. PR #4271 will update the docs.

**Comment by hholst80** [comment]
How can you verify that you actually have a C++ version of the protobuf library installed?

```
python -c "from google.protobuf.internal import api_implementation; print(api_implementation._default_implementation_type)"
```

still says `python`

**Comment by ye** [comment]
@hholst80 good point and you are right, mine says `python` as well.

```bash
$ workon ai
(ai) $ pip freeze
appnope==0.1.0
cycler==0.10.0
decorator==4.0.10
ipython==5.1.0
ipython-genutils==0.1.0
matplotlib==1.5.1
numpy==1.11.1
pandas==0.18.1
pexpect==4.2.0
pickleshare==0.7.4
prompt-toolkit==1.0.6
protobuf==3.0.0b2.post2
ptyprocess==0.5.1
Pygments==2.1.3
pyparsing==2.1.8
python-dateutil==2.5.3
pytz==2016.6.1
requests==2.11.1
scikit-learn==0.17.1
scipy==0.18.0
simplegeneric==0.8.1
six==1.10.0
tensorflow==0.10.0rc0
Theano==0.8.2
traitlets==4.2.2
wcwidth==0.1.7
(ai) $ python -c "from google.protobuf.internal import api_implementation; print(api_implementation._default_implementation_type)"
python
(ai) $ python -V
Python 3.4.3
```

**Comment by keveman** [comment]
Unfortunately, just renaming the `.whl` file seems insufficient. You also have to rename `<venv_path>/lib/python3.4/site-packages/google/protobuf/internal/_api_implementation.cpython-35m-darwin.so` to `<venv_path>/lib/python3.4/site-packages/google/protobuf/internal/_api_implementation.so`.

**Comment by gunan** [comment]
Bonus, we found out that our proto packages were not optimized when building. Now we are.
I have built and uploaded all the following packages, this time with correct python versions:
https://storage.googleapis.com/tensorflow/mac/cpu/protobuf-3.0.0-cp35-cp35m-macosx_10_11_x86_64.whl
https://storage.googleapis.com/tensorflow/mac/cpu/protobuf-3.0.0-cp27-cp27m-macosx_10_11_x86_64.whl

https://storage.googleapis.com/tensorflow/linux/cpu/protobuf-3.0.0-cp27-none-linux_x86_64.whl
https://storage.googleapis.com/tensorflow/linux/cpu/protobuf-3.0.0-cp34-cp34m-linux_x86_64.whl
https://storage.googleapis.com/tensorflow/linux/cpu/protobuf-3.0.0-cp35-cp35m-linux_x86_64.whl

But there is a problem building the py3.4 version on mac. I am exploring what is going on.

In the meantime, could you try using the py3.5 version by renaming, and see if it works?

**Comment by ye** [comment]
Yes, will try 3.5 whl out again today. 

Re bonus: Nice! :)

**Comment by ye** [comment]
@gunan sorry for the delay. No go for me as I don't find any Python 3.4 compatible Mac OS X 10.11.6 wheel packages. Renaming the Python 3.5 wheel package will install okay but it's not using the optimized C++ version but rather the Python version, see below.

```bash
$ wget https://storage.googleapis.com/tensorflow/mac/cpu/protobuf-3.0.0-cp35-cp35m-macosx_10_11_x86_64.whl
--2016-09-19 17:44:31--  https://storage.googleapis.com/tensorflow/mac/cpu/protobuf-3.0.0-cp35-cp35m-macosx_10_11_x86_64.whl
Resolving storage.googleapis.com... 209.85.232.128, 2607:f8b0:400d:c0d::80
Connecting to storage.googleapis.com|209.85.232.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 952473 (930K) [application/octet-stream]
Saving to: ‘protobuf-3.0.0-cp35-cp35m-macosx_10_11_x86_64.whl’

protobuf-3.0.0-cp35-cp35m-macosx_10_11_x86_64.whl                                          100%[========================================================================================================================================================================================================================================>] 930.15K  4.52MB/s    in 0.2s    

2016-09-19 17:44:32 (4.52 MB/s) - ‘protobuf-3.0.0-cp35-cp35m-macosx_10_11_x86_64.whl’ saved [952473/952473]

$ pip install protobuf-3.0.0-cp35-cp35m-macosx_10_11_x86_64.whl
protobuf-3.0.0-cp35-cp35m-macosx_10_11_x86_64.whl is not a supported wheel on this platform.

$ mv protobuf-3.0.0-cp35-cp35m-macosx_10_11_x86_64.whl protobuf-3.0.0-cp34-cp34m-macosx_10_11_x86_64.whl
$ pip install ./protobuf-3.0.0-cp34-cp34m-macosx_10_11_x86_64.whl
Processing ./protobuf-3.0.0-cp34-cp34m-macosx_10_11_x86_64.whl
Requirement already satisfied (use --upgrade to upgrade): six>=1.9 in /Users/ye/.envs/ai/lib/python3.4/site-packages (from protobuf==3.0.0)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /Users/ye/.envs/ai/lib/python3.4/site-packages (from protobuf==3.0.0)
Installing collected packages: protobuf
Successfully installed protobuf-3.0.0

$ python -c "from google.protobuf.internal import api_implementation; print(api_implementation._default_implementation_type)"
python
```

**Comment by gunan** [comment]
I am trying, but I do not have access to a macosx machine with python34 installed.
Funny, I have no idea how to proceed.

**Comment by martinwicke** [comment]
Can we publish the instructions how to build the custom protobuf whl? Then
Ye (and anyone else) can rebuild it on whatever system they like.

**Comment by gunan** [comment]
That's a good idea :)
Let me share them here first:

All the instructions are in line with here, please see the page for all the prerequisites:
https://github.com/google/protobuf/blob/master/src/README.md

Then I tried to run the following commands:
git clone https://github.com/google/protobuf.git
cd protobuf
./autogen.sh
CXXFLAGS="-fPIC -g -O2" ./configure
make -j12
export PROTOC=$PWD/src/protoc
cd python
python3.4 setup.py bdist_wheel --cpp_implementation --compile_static_extension
cd dist

The wheel file will be in the "dist" directory.

**Comment by martinwicke** [comment]
Let's publish this, possibly inline in the os_setup.md document, to be
reorganized soon to be more friendly to beginners.

**Comment by ye** [comment]
@martinwicke @gunan great thanks. I will give the instruction a run today.

**Comment by ye** [comment]
Following @gunan 's guide step by step to build `protobuf-3.0.2-cp34-cp34m-macosx_10_10_x86_64.whl` wheel package locally on my Mac, and it works like a charm!

Thank you guys!

```bash
$ pip install protobuf-3.0.2-cp34-cp34m-macosx_10_10_x86_64.whl 
Processing ./protobuf-3.0.2-cp34-cp34m-macosx_10_10_x86_64.whl
Requirement already satisfied (use --upgrade to upgrade): six>=1.9 in /Users/ye/.envs/ai/lib/python3.4/site-packages (from protobuf==3.0.2)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /Users/ye/.envs/ai/lib/python3.4/site-packages (from protobuf==3.0.2)
Installing collected packages: protobuf
Successfully installed protobuf-3.0.2

$ pip freeze | grep protobuf
protobuf==3.0.2

$ python -c "from google.protobuf.internal import api_implementation; print(api_implementation._default_implementation_type)"
cpp
```

**Comment by gunan** [comment]
As the #4642 is merged, I am closing this issue.
