### ISSUE TITLE
Wrong function in example for tensor_diag

### ISSUE THREAD

**Issue by ngc92** [tensorflow/tensorflow#38564]
The examples in the documentations of `tf.linalg.tensor_diag_part` and `tf.linalg.tensor_diag`
are showing the non-tensor version of these functions, e.g.
```
# 'diagonal' is [1, 2, 3, 4]
tf.diag(diagonal) ==> [[1, 0, 0, 0]
                       [0, 2, 0, 0]
                       [0, 0, 3, 0]
                       [0, 0, 0, 4]]
```

See 
https://www.tensorflow.org/api_docs/python/tf/linalg/tensor_diag
https://www.tensorflow.org/api_docs/python/tf/linalg/tensor_diag_part

**Comment by ManishAradwad** [comment]
I'll start working on this, Thanks!

**Comment by tushar-dalal** [comment]
Is this issue not closed yet?

**Comment by rohan100jain** [comment]
I think the documentation seems to be fine and is indicating what the resulting Tensor would look like. Closing issue for now.

**Comment by ngc92** [comment]
sorry, but I have to disagree on this being resolved and the documentation being fine. The documentation shows an example which uses the `tf.diag_part` function, but is supposed to document usage of the `tf.tensor_diag_part` function (which is not an alias but another function). The choice of example seems also unfortunate in the sense that, in this particular case, both functions would give the same result, and as such the example does not help the reader to better understand the difference between the two.
