### ISSUE TITLE
Custom keras/tensorflow layer, output-shape error

### ISSUE THREAD

**Issue by paulhigazi** [tensorflow/tensorflow#38574]
I wrote my own keras/tensorflow layer. Passing images into it works fine, but using it in combination with other layers, givesan error. Somehow the output shape of my custom layer should be wrong, or some kind of "Nonetype".

I posted my question on Stackoverflow, to reduce redundance,  just follow the underlying link to the code.

https://stackoverflow.com/questions/61231081/custom-keras-tensorflow-layer-output-shape-error

**Comment by ravikyram** [comment]
@paulhigazi 

Can you please let us know which Tensorflow version you are using?.Request you to fill [issue template.](https://github.com/tensorflow/tensorflow/issues/new/choose).

Request you to share colab link or simple standalone code with proper indentation to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!
