### ISSUE TITLE
Add new hyperparameter k in tf.compat.v1.train.polynomial_decay and other decay fuction

### ISSUE THREAD

**Issue by atztao** [tensorflow/tensorflow#38570]
Hey, according to [this paper](https://arxiv.org/abs/2004.05909) should be adding new hyperparameter k in the API of tf.compat.v1.train.polynomial_decay and other decay functions to simply improve performance. Thank you very much.

**Comment by karmel** [comment]
We are not making ongoing changes to compat.v1 functions. You can consider making a contribution to TF Addons if you have related functionality you want to add for TF v2. https://github.com/tensorflow/addons
