### ISSUE TITLE
[TFLITE] Modelmaker for (multi-class) custom text classification.

### ISSUE THREAD

**Issue by dupree** [tensorflow/tensorflow#38576]
**System information**
- TensorFlow version (you are using):
Nightly version of TensorFlow (2.2.0-dev20200415)
- Are you willing to contribute it (Yes/No):
Yes

**Describe the feature and the current behavior/state.**
Ability to use custom train data for text classification.
Currently on providing custom data instead of **aclImdb** [http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz](url)

`text_classifier.create(train_data, model_spec=model_spec, epochs=5)` functionality breaks with the following error :
`UnboundLocalError                         Traceback (most recent call last)
<ipython-input-48-391f7527d048> in <module>
----> 1 model = text_classifier.create(train_data, model_spec=model_spec, epochs=20)

~/anaconda3/envs/py3/lib/python3.7/site-packages/tensorflow_examples/lite/model_maker/core/task/text_classifier.py in create(train_data, model_export_format, model_spec, shuffle, batch_size, epochs, validation_data)
     60 
     61   tf.compat.v1.logging.info('Retraining the models...')
---> 62   text_classifier.train(train_data, validation_data, epochs, batch_size)
     63 
     64   return text_classifier

~/anaconda3/envs/py3/lib/python3.7/site-packages/tensorflow_examples/lite/model_maker/core/task/text_classifier.py in train(self, train_data, validation_data, epochs, batch_size)
    126                                                 steps_per_epoch,
    127                                                 validation_steps,
--> 128                                                 self.num_classes)
    129 
    130     return self.model

~/anaconda3/envs/py3/lib/python3.7/site-packages/tensorflow_examples/lite/model_maker/core/task/model_spec.py in run_classifier(self, train_input_fn, validation_input_fn, epochs, steps_per_epoch, validation_steps, num_classes)
    222         steps_per_epoch=steps_per_epoch,
    223         validation_data=validation_ds,
--> 224         validation_steps=validation_steps)
    225 
    226     return model

~/anaconda3/envs/py3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
     69   def _method_wrapper(self, *args, **kwargs):
     70     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
---> 71       return method(self, *args, **kwargs)
     72 
     73     # Running inside `run_distribute_coordinator` already.

~/anaconda3/envs/py3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    917               end_step = step + data_handler.step_increment
    918               callbacks.on_train_batch_end(end_step, logs)
--> 919         epoch_logs = copy.copy(logs)
    920 
    921         # Run validation.

UnboundLocalError: local variable 'logs' referenced before assignment
`
**Will this change the current api? How?**
Not sure.
**Who will benefit with this feature?**
End users
**Any Other info.**
Custom (multi-class) text classification support.

**Comment by Saduf2019** [comment]
@dupree 
can you please share a simple standalone code for us to replicate the error faced.

**Comment by dupree** [comment]
@Saduf2019  Thanks for the response. I am following the example shared here :
[tf_example_url](https://github.com/tensorflow/examples/blob/master/tensorflow_examples/lite/model_maker/demo/text_classification.ipynb)

The only change I am doing is in the block of data parsing, as following :
```
print (data_path)

model_spec = AverageWordVecModelSpec()
train_data = TextClassifierDataLoader.from_folder(os.path.join(data_path, 'train'), 
                                                  model_spec=model_spec, 
                                                  class_labels=['accept', 'reject', 'no'])
test_data = TextClassifierDataLoader.from_folder(os.path.join(data_path, 'test'),
                                                 model_spec=model_spec, is_training=False, shuffle=False)
train_data, validation_data = train_data.split(0.9)
```

I am following the precise folder structure as followed by aclIMDB dataset. 
`class_labels=['accept', 'reject', 'no'])` point to folders named accept, reject and no respectively in train folder. The dat_path looks like this :
`data/`
while the path for accept and other labels looks like :
`data/train/accept`

I see the error when I create model via either this :
`model = text_classifier.create(train_data, model_spec=model_spec, epochs=8)`

or
`model = text_classifier.create(train_data, model_spec=model_spec, validatation_data=validation_data,  epochs=8)`

**Note :** In this setup each class data in `data/train/accept` (and reject, no)  contains around 4-5 `id.txt` files, where id ranges from 0..5 


After some trials and testing, I noticed this :

1. once I rename the individual train files from `id.txt` to `id_rating.txt`, where id = range(0..30) and id_rating = range(0..10). I am able to create/train a model via this :
 `model = text_classifier.create(train_data, model_spec=model_spec, epochs=8)`

But this fails again once I enable `validation_data` via this  :

`model = text_classifier.create(train_data, model_spec=model_spec, validatation_data=validation_data,  epochs=8)`

2. I am able to train/create a model this way but the model is highly susceptible to class imbalance. If one label has marginally higher data, model just learns to predict that for any sample. I tested with data samples for label `yes` 34 and `no` 40 and the model learns to predict no for every sample.

How and where can I see the internal working of `model_spec = AverageWordVecModelSpec()` and if I can customize it.

Thanks

**Comment by Saduf2019** [comment]
@dupree
can you please share colab gist of the code for us to analyse the error

**Comment by Saduf2019** [comment]
@dupree 
PLease update as per above comment

**Comment by dupree** [comment]
@Saduf2019 Unfortunately I am not using colab but my local jupyter notebook, I can share that if thats of any help ? But as I mentioned in my previous comment, I haven't changed much except adding my own data files. If the example expects data/data files in any specific `filename` format, please share.
Thanks

**Comment by jvishnuvardhan** [comment]
@dupree Looking at the error trace, i suspect some compatibility issue due to combining `TF1.x` and `TF2.x` functionality.
```
61 tf.compat.v1.logging.info('Retraining the models...')
---> 62 text_classifier.train(train_data, validation_data, epochs, batch_size)
....
.....
UnboundLocalError: local variable 'logs' referenced before assignment 
```

Can you please share a standalone code to reproduce the issue? Thanks!
