### ISSUE TITLE
Failed precondition: Error while reading resource variable block3a_se_expand/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/block3a_se_expand/bias/N10tensorflow3VarE does not exist. 	 [[{{node block3a_se_expand/BiasAdd/ReadVariableOp}}]] 	 [[dense_1/Softmax/_1903]]

### ISSUE THREAD

**Issue by Samjith888** [tensorflow/tensorflow#38571]
I have three trained models which is using in one script . First model (.h5) is loaded using following piece of code

```
from keras_retinanet import models
def get_session():
    config = tf.compat.v1.ConfigProto()
    config.gpu_options.allow_growth = True
    return tf.compat.v1.Session(config=config)
keras.backend.tensorflow_backend.set_session(get_session()) 
first_model = models.load_model(first_model_path, backbone_name='resnet50')
```
The first model loaded and predicted successfully. After first model operation,  second model (.hdf5) loaded using following code block

```
from tensorflow.keras.models import load_model
second_model =load_model(second_model_path)
```
Second model loaded successfully and but while prediction , getting the following error.

`2020-04-15 12:01:36.207346: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
2020-04-15 12:01:36.310985: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2020-04-15 12:01:43.026476: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10
Traceback (most recent call last):
  File "ppe_detection.py", line 105, in <module>
    predicted , x = predict_helmet(processed_roi,helmet_model)
  File "/samjith/project/safety-monitoring/classify/helmet/helmet_classy.py", line 17, in predict_helmet
    helmet_score = helmet_model.predict([x])[0][0]
  File "/home/samjith/anaconda3/envs/keras-retina/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1078, in predict
    callbacks=callbacks)
  File "/home/samjith/anaconda3/envs/keras-retina/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 363, in model_iteration
    batch_outs = f(ins_batch)
  File "/home/samjith/anaconda3/envs/keras-retina/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "/home/samjith/anaconda3/envs/keras-retina/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Error while reading resource variable block3b_expand_conv/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/block3b_expand_conv/kernel/N10tensorflow3VarE does not exist.
	 [[{{node block3b_expand_conv/Conv2D/ReadVariableOp}}]]
	 [[dense_1/Softmax/_1903]]
  (1) Failed precondition: Error while reading resource variable block3b_expand_conv/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/block3b_expand_conv/kernel/N10tensorflow3VarE does not exist.
	 [[{{node block3b_expand_conv/Conv2D/ReadVariableOp}}]]
0 successful operations.
0 derived errors ignored.
`
I have gone through [this github  link](https://github.com/tensorflow/tensorflow/issues/28287#issuecomment-495005162). But the error still remains.

**Comment by gadagashwini** [comment]
@Samjith888, Can you share complete standalone code and Tensorflow version. Thanks

**Comment by Samjith888** [comment]
> @Samjith888, Can you share complete standalone code and Tensorflow version. Thanks

Here i have three .py files.

```
*****main.py****

import efficientnet.tfkeras
from tensorflow.keras.models import load_model

from first_predict import first_prediction
from second_predict import second_prediction

first_model_path = 'first_model.h5'
second_model_path = 'second_model.hdf5'

output_img=first_prediction(image,first_model_path)

#second model loading
second_model = load_model(second_model_path)
second_prediction(output_img,second_model)

```
```
****first_predict.py *****

import keras
from keras_retinanet import models
import tensorflow as tf

def get_session():
    config = tf.compat.v1.ConfigProto()
    config.gpu_options.allow_growth = True
    return tf.compat.v1.Session(config=config)

def get_bbox(img, model_path):
        #Load model for detection     
        keras.backend.tensorflow_backend.set_session(get_session()) 
        model = models.load_model(model_path, backbone_name='resnet50')

        #preprocess the image for inference    
        ##some preprocess image codes

        boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))

       return marked_img

```

```
***second_predict.py*****
                                                   
import efficientnet.tfkeras
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image

def predict_helmet(image,second_model):
    ##some image  preprocessing code
    x= image
    probabilities =second_model.predict([x])

    return probabilities
```

I'm getting the error in `'probabilities =second_model.predict([x])'` in second_predict.py file

**Environment**
Python = 3.7
Tensorflow = 1.14.0
keras =2.3.1


Note : This error is not on the trained models, i have already tested successfully by executing these models individually.

**Comment by Samjith888** [comment]
@gadagashwini  Any update on this issue ?

**Comment by amahendrakar** [comment]
@Samjith888,
Sorry for the delayed response. On running the code, I am facing an error stating `ImportError: cannot import name 'first_prediction'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/d3a8b4bafc0fdeee3238eab50c100e65/38571.ipynb).

Looks like the code for `first_predict.py` file is incomplete. Could you please share the complete code to reproduce the issue reported here. Thanks!

**Comment by Samjith888** [comment]
> @Samjith888,
> Sorry for the delayed response. On running the code, I am facing an error stating `ImportError: cannot import name 'first_prediction'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/d3a8b4bafc0fdeee3238eab50c100e65/38571.ipynb).
> 
> Looks like the code for `first_predict.py` file is incomplete. Could you please share the complete code to reproduce the issue reported here. Thanks!

Please have try with the updated code. I have corrected the error which u mentioned above

**Comment by amahendrakar** [comment]
@Samjith888,
I am unable to reproduce the error because of the missing files `first_model.h5` and `second_model.hdf5`. 

Could you please share all the supporting files required to run the code. Thanks!

**Comment by Samjith888** [comment]
> @Samjith888,
> I am unable to reproduce the error because of the missing files `first_model.h5` and `second_model.hdf5`.
> 
> Could you please share all the supporting files required to run the code. Thanks!



> > @Samjith888, Can you share complete standalone code and Tensorflow version. Thanks
> 
> Here i have three .py files.
> 
> ```
> *****main.py****
> 
> import efficientnet.tfkeras
> from tensorflow.keras.models import load_model
> import cv2
> from first_predict import first_prediction
> from second_predict import second_prediction
> 
> image = cv2.imread('abc.jpg')
> 
> first_model_path = 'first_model.h5'
> second_model_path = 'second_model.hdf5'
> 
> first_prediction(image,first_model_path)
> 
> #second model loading
> second_model = load_model(second_model_path)
> second_prediction(image,second_model)
> 
> #second model loading
> second_model = load_model(second_model_path)
> second_prediction(output_img,second_model)
> ```
> 
> ```
> ****first_predict.py *****
> 
> import keras
> from keras_retinanet import models
> from keras_retinanet.utils.image import  preprocess_image, resize_image
> import tensorflow as tf
> 
> def get_session():
>     config = tf.compat.v1.ConfigProto()
>     config.gpu_options.allow_growth = True
>     return tf.compat.v1.Session(config=config)
> 
> def first_prediction(img, first_model_path):
>         #Load model for detection     
>         keras.backend.tensorflow_backend.set_session(get_session()) 
>         model = models.load_model(first_model_path, backbone_name='resnet50')
> 
>         #preprocess the image for inference    
>         image = preprocess_image(img)
>         image, scale = resize_image(image)
> 
>         boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
> ```
> 
> ```
> ***second_predict.py*****
>                                                    
> import efficientnet.tfkeras
> from tensorflow.keras.models import load_model
> from tensorflow.keras.preprocessing import image
> 
> def second_prediction(img,second_model):
>     ##some image  preprocessing code
>     x = image.img_to_array(img)
>     # Reshape
>     x = x.reshape((1,) + x.shape)
>     x /= 255.
>   
>     probabilities =second_model.predict([x])
> ```
> 
> download pretrained model and place the path in following fields
> 
> ```
> first_model_path = 'first_model.h5'
> second_model_path = 'second_model.hdf5'
> ```
> 
> I'm getting the error in `'probabilities =second_model.predict([x])'` in second_predict.py file
> 
> **Environment**
> Python = 3.7
> Tensorflow = 1.14.0
> keras =2.3.1
> 
> Note : This error is not on the trained models, i have already tested successfully by executing these models individually.



> @Samjith888,
> I am unable to reproduce the error because of the missing files `first_model.h5` and `second_model.hdf5`.
> 
> Could you please share all the supporting files required to run the code. Thanks!

Hello ,
 The custom trained weighst are very large and can't upload it here.  Now i have updated the code for downloading the second_model . 

Please download the weight of first model   [by clicking here ](https://github.com/fizyr/keras-retinanet/releases/download/0.5.1/resnet50_coco_best_v2.1.0.h5) and modify the below line in main.py by this model path

`first_model_path = 'first_model.h5'`

Also place the replace the path of second model once it downloaded 

`second_model_path = path to 'second_mdl'`

I couldn't simplify the code and this issue more than this 

Note : This is a common error, not depend on the trained weights which i generated. So please try to help me based on the pretrained weights which i have mentioned above

**Comment by ghost986** [comment]
Each model will have its own session and graph. The default session and graph within this context cannot load the new weights to the already-existing graph. This could be solved in TF 1 with session, but I don't see how to solve this is TF 2 yet without disabling eager execution.

Try:
```
config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True

first_graph = tf.Graph()
first_session = tf.compat.v1.Session(config=config)

second_graph = tf.Graph()
second_session = tf.compat.v1.Session(config=config)

first_model_path = 'first_model.h5'
second_model_path = 'second_model.hdf5'

with first_graph.as_default(), first_session.as_default():
    first_prediction(image,first_model_path)

#second model loading
with second_graph.as_default(), second_session.as_default():
    second_model = load_model(second_model_path)
    second_prediction(image,second_model)
```

**Comment by amahendrakar** [comment]
@Samjith888,
On running the `main.py` file I am facing a different error stating `AttributeError: 'NoneType' object has no attribute 'astype'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/580c32f3f0a31327709b363bd446474d/38571.ipynb). Thanks!

**Comment by egenc** [comment]
I have fixed this by changing the `load` function. If you are loading your model from `.h5` or `.pb`

change it from this:

` `   model = tf.saved_model.load(self.filename, [tf.saved_model.SERVING])`
`
to this:

```
    from tensorflow.python.keras.models import load_model
    model = load_model(self.filename)
```

**Comment by LeamonLee** [comment]
> Each model will have its own session and graph. The default session and graph within this context cannot load the new weights to the already-existing graph. This could be solved in TF 1 with session, but I don't see how to solve this in TF 2 yet without disabling eager execution.
> 
> Try:
> 
> ```
> config = tf.compat.v1.ConfigProto()
> config.gpu_options.allow_growth = True
> 
> first_graph = tf.Graph()
> first_session = tf.compat.v1.Session(config=config)
> 
> second_graph = tf.Graph()
> second_session = tf.compat.v1.Session(config=config)
> 
> first_model_path = 'first_model.h5'
> second_model_path = 'second_model.hdf5'
> 
> with first_graph.as_default(), first_session.as_default():
>     first_prediction(image,first_model_path)
> 
> #second model loading
> with second_graph.as_default(), second_session.as_default():
>     second_model = load_model(second_model_path)
>     second_prediction(image,second_model)
> ```

Hi, did you find the solution to this issue with tensorflow 2? If not, how did you disable the eager execution?
