### ISSUE TITLE
[TFLITE] Modelmaker and code generator for boundingRect/Cuboid + keypoints

### ISSUE THREAD

**Issue by bhack** [tensorflow/tensorflow#38572]
**System information**
- TensorFlow version (you are using):
Tensorflow-nightly
- Are you willing to contribute it (Yes/No):
No

**Describe the feature and the current behavior/state.**
In Tensorflow Hub at https://github.com/tensorflow/hub/issues/424 I've proposed to introduce one of the many single stage anchor-free models that adapt quite easily to keypoints tasks (face detection+ladmarks, people detection + pose, 3d cuboid + object keypoints etc.). 
It could be very useful if the new ModelMaker and the code generator could support generic object occupancy (2d/3d) + arbitrary target keypoints.

**Will this change the current api? How?**
Yes.
**Who will benefit with this feature?**
Many end2end task like face detection with landmakrs, people detection + pose, 3d object detection + specific object keypoints, hand detection + hand landmarks etc..)
**Any Other info.**

**Comment by pkgoogle** [comment]
Hi @bhack, is this feature request still valid? i.e. Is there a ModelMaker model now that serves what you need?

**Comment by bhack** [comment]
I don't know honestly after 3 years probably nobody cares anymore about this
