### ISSUE TITLE
TF API Feature transformation to saved model from checkpoint file 

### ISSUE THREAD

**Issue by 17patelumang** [tensorflow/tensorflow#38588]
OS Platform and Distribution : macOS Catalina 10.15.3

TensorFlow installed from : binary

TensorFlow version : 1.15.0

Python version: 3.7.3

**Describe the current behavior**

I have general question , i have checkpoint file which was converted to  .pb file  using https://stackoverflow.com/questions/56766639/how-to-convert-ckpt-to-pb , however is there any way in the code in this link we can port feature transformation into saved model ?

I already have code to convert feature transformation to TF API  ? 

Also can we get example of this - https://cloud.google.com/ai-platform/prediction/docs/exporting-savedmodel-for-prediction#create_serving_graph_separately_from_training , its not very clear from docs

I basically have checkpoint file and what to convert that into .pb file with feature transformation part of it . I already have code for converting to feature using TF API .

**Comment by 17patelumang** [comment]
@Saduf2019 thank you for reply , any update on this ticket since other one was closed ?

**Comment by 17patelumang** [comment]
any update on this ?

**Comment by Saduf2019** [comment]
@17patelumang 
please provide a simple standalone code for us to replicate the issue faced

**Comment by 17patelumang** [comment]
its general question , no standalone code

**Comment by ymodak** [comment]
Have you considered using [Graph Transform Tool](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md) in this case?

**Comment by 17patelumang** [comment]
@ymodak  thank you for reply however how can graph transform tool help here, esp to add enitre new feature transformation post training  ? , can you please share small example

**Comment by 17patelumang** [comment]
@ymodak  any update ?

**Comment by ymodak** [comment]
Something similar on the lines of  [Writing Your Own Transforms](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md#writing-your-own-transforms) section can help?
For the example of exporting model for prediction part you may want to open an issue on [GoogleCloudPlatform/cloudml-samples](https://github.com/GoogleCloudPlatform/cloudml-samples/issues) or report error on that web page since its handled by different teams.
Thanks!
