### ISSUE TITLE
C++ compilation of rule '//tensorflow/core/kernels:sparse_redu ce_op' failed (Exit 1)

### ISSUE THREAD

**Issue by riestiyazain** [tensorflow/tensorflow#38594]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian GNU/Linux 9 (stretch), kernel : Linux 4.9.0-12-amd64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14
- Python version: Python 3.5.3
- Installed using virtualenv? pip? conda?: n/a
- Bazel version (if compiling from source): tried with Bazel 0.24.1 and 2.0.0
- GCC/Compiler version (if compiling from source): gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**
I'm using jupyterlab from Google Cloud Platform to build the Tensorflow from source, intended to convert the Tensorflow model to flat buffer (tflite).  Bazel installed from binary (0.24.1) and from apt get, configured with all 'no' installation options in ./configure.  After hours of the building process, it came up with C++ compilation of rule '//tensorflow/core/kernels:sparse_redu
ce_op' failed (Exit 1).
**Provide the exact sequence of commands/steps that you executed before running into the problem**
bazel build --config=v1 //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
In file included from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:104:0,
                 from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from ./tensorflow/core/framework/numeric_types.h:20,
                 from ./tensorflow/core/framework/allocator.h:26,
                 from ./tensorflow/core/framework/op_kernel.h:24,
                 from tensorflow/core/kernels/sparse_reduce_op.cc:20:
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorReduction.h: In static member function 'static void std::_Function_handler<void(_ArgTypes ...), _Functor>::_M_invoke(const std::_Any_data&, _ArgTypes&& ...) [with _Functor = Eigen::internal::TensorExecutor<Expression, Eigen::ThreadPoolDevice, Vectorizable, Tiling>::run(const Expression&, const Eigen::ThreadPoolDevice&) [with Expression = const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::TensorFixedSize<std::complex<float>, Eigen::Sizes<>, 1, long int>, 16, Eigen::MakePointer>, const Eigen::TensorReductionOp<Eigen::internal::SumReducer<std::complex<float> >, const Eigen::DimensionList<long int, 1ul>, const Eigen::TensorMap<Eigen::Tensor<std::complex<float>, 1, 1, long int>, 0, Eigen::MakePointer>, Eigen::MakePointer> >; bool Vectorizable = true; Eigen::internal::TiledEvaluation Tiling = (Eigen::internal::TiledEvaluation)0u]::<lambda(Eigen::internal::TensorExecutor<const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::TensorFixedSize<std::complex<float>, Eigen::Sizes<>, 1, long int>, 16, Eigen::MakePointer>, const Eigen::TensorReductionOp<Eigen::internal::SumReducer<std::complex<float> >, const Eigen::DimensionList<long int, 1ul>, const Eigen::TensorMap<Eigen::Tensor<std::complex<float>, 1, 1, long int>, 0, Eigen::MakePointer>, Eigen::MakePointer> >, Eigen::ThreadPoolDevice, true, (Eigen::internal::TiledEvaluation)0u>::StorageIndex, Eigen::internal::TensorExecutor<const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::TensorFixedSize<std::complex<float>, Eigen::Sizes<>, 1, long int>, 16, Eigen::MakePointer>, const Eigen::TensorReductionOp<Eigen::internal::SumReducer<std::complex<float> >, const Eigen::DimensionList<long int, 1ul>, const Eigen::TensorMap<Eigen::Tensor<std::complex<float>, 1, 1, long int>, 0, Eigen::MakePointer>, Eigen::MakePointer> >, Eigen::ThreadPoolDevice, true, (Eigen::internal::TiledEvaluation)0u>::StorageIndex)>; _ArgTypes = {long int, long int}]':
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorReduction.h:806:9: internal compiler error: in emit_move_insn, at expr.c:3547
         values[i] = internal::InnerMostDimReducer<Self, Op>::reduce(*this, firstIndex + i * num_values_to_reduce,
         ^~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
Target //tensorflow/lite/python:tflite_convert failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 9462.045s, Critical Path: 223.49s
INFO: 7684 processes: 7684 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

** This is error log when building tflite_convert, similar error when building tensorflow

any advice is much appreciated

**Comment by teijeong** [comment]
Hi, I tried this with `gcc version 9.2.1 20200203 (Debian 9.2.1-28)` and works. fine. Can you try again with recent source? If problem persists, it might be a bug in `gcc` as mentioned in the log.
