### ISSUE TITLE
Create serving graph separately from training

### ISSUE THREAD

**Issue by 17patelumang** [tensorflow/tensorflow#38593]
OS Platform and Distribution : macOS Catalina 10.15.3

TensorFlow installed from : binary

TensorFlow version : 1.15.0

Python version: 3.7.3

Can we get example of this - https://cloud.google.com/ai-platform/prediction/docs/exporting-savedmodel-for-prediction#create_serving_graph_separately_from_training  , its not very clear from docs 

I basically have checkpoint file and what to convert that into .pb file with feature transformation part of it . I already have code for converting to feature using TF API .

**Comment by Saduf2019** [comment]
@17patelumang 
this issue is a duplicate of #38588, hence moving this to closed status as it would be traced in #38588
