### ISSUE TITLE
网络爬虫核心技术教程，点此获取☞

### ISSUE THREAD

**Issue by gnehsuy** [tensorflow/tensorflow#38595]
![c5896b844e918f67269114e6c3174ad](https://user-images.githubusercontent.com/13401581/79433137-594fa000-7fff-11ea-8fcd-24c4514acf7c.png)

**Comment by amahendrakar** [comment]
@gnehsuy,
Is this issue related to TensorFlow?

If it is, could you please edit the details and fill in the issue template? Thanks!

**Comment by zjw-swun** [comment]
if you want qia fan ,please get out

**Comment by BrettDong** [comment]
This is a spam

**Comment by mylesshie** [comment]
bitch

**Comment by al0ne** [comment]
bitch

**Comment by yeliex** [comment]
@amahendrakar this is an ad, please close it

**Comment by amahendrakar** [comment]
Not a TensorFlow issue, hence marking it as closed.

**Comment by liaow** [comment]
YELVERTON
