### ISSUE TITLE
Image segmentation model

### ISSUE THREAD

**Issue by didi789** [tensorflow/tensorflow#38599]
I'm trying to implement the image segmentation model in my android application, using tflite -

https://github.com/tensorflow/examples/tree/master/lite/examples/image_segmentation/android
https://www.tensorflow.org/lite/models/segmentation/overview

And I wonder if there is any other model that I can use instead of the deeplabv3_257_mv_gpu.tflite model, [I saw this project on GitHub ](https://github.com/dailystudio/ml/tree/master/deeplab#performance), and it seems that there is TF Mobile model with 513 x 513 inputs somewhere.

Thanks in advance,
Nirel.

**Comment by thaink** [comment]
The TF Mobile or TF Mini is a completely different project than TFLite and it has been deprecated. you can use its models for tflite.
if you want to try other model, you can try to convert it from https://github.com/tensorflow/models/tree/master/research/deeplab
