### ISSUE TITLE
After quantifying the model, the speed of model inference slows down

### ISSUE THREAD

**Issue by WhiteAzzan** [tensorflow/tensorflow#38608]
Today, I learned how to use tensorflow Lite to quantify the model. I ran the code in the example. I found that the model inference speed after quantification is 0.3 seconds slower than the original model. Is this normal? I firstly do it and who can answer, thank you~~~

**Comment by WhiteAzzan** [comment]
i use tensorflow-gpu-1.14 and quantify to int8 and float16

**Comment by WhiteAzzan** [comment]
I just got promoted. I found that their speed was almost the same. Is this because of the version? But there was no significant increase in speed.

**Comment by WhiteAzzan** [comment]
I just got promoted to tensorflow-gpu-1.15. I found that their speed was almost the same. Is this because of the version? But there was no significant increase in speed.

**Comment by ymodak** [comment]
[Quantization](https://www.tensorflow.org/lite/performance/post_training_quantization) procedures require TensorFlow 1.15 and above. Quantized models provide 2-3x speed up. Thanks!

**Comment by WhiteAzzan** [comment]
@ymodak，but，I used ‘from tensorflow.tools.graph_transforms import TransformGraph’  to it , and lite may be.not 1.15  is 1.14

**Comment by WhiteAzzan** [comment]
I found the reason because I quantified the model after pruning, the model itself was small, and the effect of reduction and acceleration was not obvious.
