### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by jeantil88** [tensorflow/tensorflow#38602]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7 Professional
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): SHA
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): STM32F746 discovery kit

**Describe the problem**
Error during compilation
**Please provide the exact sequence of commands/steps when you ran into the problem**
I downloaded source code as described in the manual and installed MBED CLI. I open cmd line and run command:
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mbed TAGS="CMSIS disco_f746ng" generate_micro_speech_mbed_project

I get following error messages:

C:\Users\anton.paus\voice\tensorflowmaster2>make -f tensorflow/lite/micro/tools/
make/Makefile TARGET=mbed TAGS="CMSIS disco_f746ng" generate_micro_speech_mbed_p
roject
process_begin: CreateProcess(NULL, uname -m, ...) failed.
make: tensorflow/lite/micro/tools/make/Makefile:28: pipe: No error
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://github.com/goo
gle/gemmlowp/archive/719139ce755a0f31cbf1c37f7f98adcc7fc9f425.zip" "7e8191b24853
d75de2af87622ad293ba" tensorflow/lite/micro/tools/make/downloads/gemmlowp
tensorflow/lite/micro/tools/make/download_and_extract.sh: line 110: syntax error
: bad for loop variable
tensorflow/lite/micro/tools/make/Makefile:271: recipe for target 'tensorflow/lit
e/micro/tools/make/downloads/gemmlowp' failed
make: *** [tensorflow/lite/micro/tools/make/downloads/gemmlowp] Error 2

I have no idea what could be wrong. During the installation of mbed CLI the installer could not instal serial drivers because it didnt recgnized the mbed enabled board.

**Comment by jeantil88** [comment]
hello, any comment or recommendations?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.
