### ISSUE TITLE
Inconsistent behaviour when passing arguments to experimental_run_v2 (strategy.run) between TPU and CPU

### ISSUE THREAD

**Issue by mathemakitten** [tensorflow/tensorflow#38606]
**System information**

Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes
OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Debian GNU/Linux 9.11
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: N/A
TensorFlow installed from (source or
binary): binary
TensorFlow version (use command below): 2.2.0.dev20200406
Python version: Python 3.7.6
Bazel version (if compiling from source): N/A
GCC/Compiler version (if compiling from
source): N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A

**Describe the current behavior**

The behaviour for passing arguments to `experimental_run_v2` (now `strategy.run`) is inconsistent between TPU and CPU. For code as below: 

`outputs = strategy.experimental_run_v2(loop, args=((context, mask), var))`

On TPU this gets correctly parsed as `loop((context, mask), var)`.

On CPU (which defaults to MirroredStrategy) this gets automatically unpacked as `loop(context, mask, var)`, which breaks the function signature.

**Describe the expected behavior**

On CPU the first argument should get passed as a tuple, not automatically unpacked, to be consistent with the TPU behaviour. Then CPU execution can be used for testing.

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@mathemakitten 

Request you to provide colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by ravikyram** [comment]
@mathemakitten 

Any update on this issue please. Thanks!
