### ISSUE TITLE
Symbol not found: ____chkstk_darwin

### ISSUE THREAD

**Issue by ranitomeya** [tensorflow/tensorflow#38601]
Hi!

I am trying to install TensorFlow on an older desktop Mac (no GPU or anything other fancy stuff). It's the first time I am doing that, so maybe I'm just being dense, but installation completed without error yet TensorFlow cannot be loaded (see below). I have no idea what may be wrong and would appreciate any type of help.

Frank

**System information**

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.13.6
- TensorFlow installed from (source or binary): via pip install --upgrade tensorflow (binary, I guess?)
- TensorFlow version: 2.2.0rc3
- Python version: 3.8.2
- Installed using virtualenv? pip? conda?: virtualenv & pip (following https://www.tensorflow.org/install/pip#virtualenv-install to the letter)
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the problem**

I followed the procedure described on https://www.tensorflow.org/install to install TensorFlow in a virtual environment using pip. Everything seems to have worked smoothly. In particular, 
pip install --upgrade tensorflow
terminated with a success message. However, the verification using
python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
fails to load the TensorFlow runtime, reporting
ImportError: dlopen(.../_pywrap_tensorflow_internal.so, 6): Symbol not found: ____chkstk_darwin.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

mkdir tensorflow
cd tensorflow/
virtualenv --system-site-packages -p python3 ./venv
source ./venv/bin/activate
pip install --upgrade pip
pip list
pip install --upgrade tensorflow
python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"

**Any other info / logs**

I attach both the messages the TensorFlow installation resulted in as well as the traceback. In case it's useful to know, `pip list` gives

absl-py                0.9.0      
astunparse             1.6.3      
cachetools             4.1.0      
certifi                2020.4.5.1 
chardet                3.0.4      
gast                   0.3.3      
google-auth            1.14.0     
google-auth-oauthlib   0.4.1      
google-pasta           0.2.0      
grpcio                 1.28.1     
h5py                   2.10.0     
idna                   2.9        
Keras-Preprocessing    1.1.0      
Markdown               3.2.1      
numpy                  1.18.2     
oauthlib               3.1.0      
opt-einsum             3.2.1      
pip                    20.0.2     
protobuf               3.11.3     
pyasn1                 0.4.8      
pyasn1-modules         0.2.8      
requests               2.23.0     
requests-oauthlib      1.3.0      
rsa                    4.0        
scipy                  1.4.1      
setuptools             46.1.3     
six                    1.14.0     
tensorboard            2.2.1      
tensorboard-plugin-wit 1.6.0.post3
tensorflow             2.2.0rc3   
tensorflow-estimator   2.2.0rc0   
termcolor              1.1.0      
urllib3                1.25.8     
Werkzeug               1.0.1      
wheel                  0.34.2     
wrapt                  1.12.1    

[tf_installation_messages.txt](https://github.com/tensorflow/tensorflow/files/4486772/tf_installation_messages.txt)
[traceback.txt](https://github.com/tensorflow/tensorflow/files/4486773/traceback.txt)

**Comment by ymodak** [comment]
TensorFlow Python 3.8 is not supported on macOS.
See [TF release note](https://github.com/tensorflow/tensorflow/releases/tag/v2.2.0-rc2)s known caveats section. Thanks!

**Comment by bm777** [comment]
You can downgrade python version or use python version to 3.6.
---

Le ven. 17 avr. 2020 à 22:59, Yasir Modak <notifications@github.com> a
écrit :

**Comment by ranitomeya** [comment]
Oh, thank you, I missed that. Sorry for the bother!
