### ISSUE TITLE
InvalidArgumentError: 2 root error(s) found.   (0) Invalid argument:  indices[39,107] = 85525 is not in [0, 85525) 	 [[node model_5/embedding_8/embedding_lookup (defined at <ipython-input-203-ee38e6490bb7>:2) ]] 	 [[model_5/embedding_8/embedding_lookup/_14]]   (1) Invalid argument:  indices[39,107] = 85525 is not in [0, 85525)  in  Colab . 

### ISSUE THREAD

**Issue by SangamSwadiK** [tensorflow/tensorflow#38619]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  indices[39,107] = 85525 is not in [0, 85525)
	 [[node model_5/embedding_8/embedding_lookup (defined at <ipython-input-203-ee38e6490bb7>:2) ]]
	 [[model_5/embedding_8/embedding_lookup/_14]]
  (1) Invalid argument:  indices[39,107] = 85525 is not in [0, 85525)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
**This is the Error message I got,** 
`nvalidArgumentError                      Traceback (most recent call last)
<ipython-input-203-ee38e6490bb7> in <module>()
      1 model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics= ['accuracy'])
----> 2 a = model.fit( train_padded, y_train ,epochs=15, validation_data=(  test_padded  , y_test  ) , callbacks = learningrate_callback,   batch_size=128   )

8 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  indices[39,107] = 85525 is not in [0, 85525)
	 [[node model_5/embedding_8/embedding_lookup (defined at <ipython-input-203-ee38e6490bb7>:2) ]]
	 [[model_5/embedding_8/embedding_lookup/_14]]
  (1) Invalid argument:  indices[39,107] = 85525 is not in [0, 85525)
	 [[node model_5/embedding_8/embedding_lookup (defined at <ipython-input-203-ee38e6490bb7>:2) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_10924]

Errors may have originated from an input operation.
Input Source operations connected to node model_5/embedding_8/embedding_lookup:
 model_5/embedding_8/embedding_lookup/10486 (defined at /usr/lib/python3.6/contextlib.py:81)

Input Source operations connected to node model_5/embedding_8/embedding_lookup:
 model_5/embedding_8/embedding_lookup/10486 (defined at /usr/lib/python3.6/contextlib.py:81)

Function call stack:
train_function -> train_function`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Here's a part of the source code ,** 
`
input_tensor = tf.keras.Input(  shape = ( maxlength , )  )

embedd = tf.keras.layers.Embedding( input_dim = vocab     , output_dim = 300 , embedding_initalizer=  tf.keras.initializers.Constant(embedding_matrix) ,  input_length = maxlength  ) (input_tensor)

conv1d_1 = tf.keras.layers.Conv1D (  filters = 16 , kernel_size = 3 , strides = 1 , padding = 'valid'  , activation = 'relu', kernel_initializer = 'he_uniform' ) (embedd)
conv1d_2 =tf.keras.layers.Conv1D (  filters = 16 , kernel_size = 3 , strides = 1 , padding = 'valid'  , activation = 'relu', kernel_initializer = 'he_uniform' ) (embedd)
conv1d_3 = tf.keras.layers.Conv1D (  filters = 16 , kernel_size = 3 , strides = 1 , padding = 'valid'  , activation = 'relu', kernel_initializer = 'he_uniform' ) (embedd)
concat_1 = tf.keras.layers.concatenate(   [conv1d_1, conv1d_2 , conv1d_3 ] ) 
`

here embedding_matrix has a shape of (85525, 300) (unknown token included while tokenizing)
I'm trying to replicate the  Example at https://keras.io/examples/pretrained_word_embeddings/
with a different structure.

**Comment by zoomself** [comment]
try this   tf.keras.layers.Embedding(input_dim = vocab+1,...)

input_dim: int > 0. Size of the vocabulary,
      i.e. maximum integer index + 1.

**Comment by SangamSwadiK** [comment]
@zoomself  Thanks for replying !!! I tried it , but still getting the error, Strangely the error disappears if I run it in tensorflow 2.1,
And I also went through similar issues, 
1) [https://github.com/tensorflow/tensorflow/issues/23698](url)
2) [https://stackoverflow.com/questions/59867929/invalidargumenterror-2-root-errors-found-incompatible-shapes-in-tensorflow-t](url)

**Comment by amahendrakar** [comment]
@SangamSwadiK,
I was able to run the example given on Keras without any issues. However, while running the sample code you have provided I'm facing an error stating `NameError: name 'vocab' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/a23b2ad04bb953e42c9534c68d8b22eb/38619.ipynb#scrollTo=n_cot3240tQl&line=4&uniqifier=1). 

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by SangamSwadiK** [comment]
Closing this as I resolved the issue, The solution was to define a function 
my_func (shape , dtype = None):
   Line 1 ------
   Line 2 ------

   return embedding_matrix

Embedding layer changes to 

embedd = tf.keras.layers.Embedding( input_dim = vocab , output_dim = 300 , embedding_initalizers = my_func , input_length = maxlength ) (input_tensor)

However, **tf.keras.initializers.Constant(embedding_matrix)** should have worked, 
but Since I cannot provide the full code as this is a part of an assignment. I'm closing this .

Thanks @amahendrakar , @zoomself  for replying.

**Comment by rishikeshF** [comment]
@SangamSwadiK Hello, could you please elaborate exactly how you did, am facing similar error and am not getting any clue to resolve it.

**Comment by nilay121** [comment]
It can be resolved by changing the input_dim to vocabulary+1

**Comment by bharathjatoth** [comment]
Yes as @nilay121 suggested changing the input_dim works for the error...
