### ISSUE TITLE
transformers.modeling_tf_utils  - loading weights file from cache at None (!)

### ISSUE THREAD

**Issue by almois** [tensorflow/tensorflow#38611]
Hi, desperately need your help! 
We are trying to run TF and transformers (bert-multilingual-base-uncased) in our docker environment. Starting the training, we are getting the following error:

`INFO     transformers.modeling_tf_utils  - loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-multilingual-uncased-tf_model.h5 from cache at None`

This happens, however, only with weights, config file and vocab are linked successfully.
For instance:
`transformers.configuration_utils  - loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-multilingual-uncased-config.json from cache at bert_cache/33b56ce0f312e47e4d77a57791a4fc6233ae4a560dd2bdd186107058294e58ab.c7892120c5a9b21e515abc904e398dbabddf9510b122f659063cbf361fe16868`

Any idea why this can happen?

Many thanks in advance for any feedback and help!

**Comment by Saduf2019** [comment]
@almois 
issue reported does not seem related tensorflow, please share steps executed/code before this error was faced.

**Comment by Saduf2019** [comment]
@almois
please update as per above comment
