### ISSUE TITLE
Autograph unrolling for loop

### ISSUE THREAD

**Issue by meowcat** [tensorflow/tensorflow#38628]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows, Linux on cluster
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de410 2.1.0
- Python version: 3.7
- CUDA/cuDNN version: reproducible on CPU or GPU
- GPU model and memory:

**Describe the current behavior**

In a function decorated by `@tf.function`, I use a `for` loop to run an RNN step-by-step for beam search. There is a reduced example in the gist below.

Executing the function for the first time takes a long time (10 seconds in this minimal example, 300 seconds for my true model) and creates a very large graph (traced with `tf.summary.trace_on`; 3.5MB in this minimal example, 30-50MB for my true model, and more or less crashing Tensorboard when I try to open it.) 

If I write the same loop as a `tf.while_loop`, first execution is nearly instant, and the resulting graph is healthy (180KB minimal example, 500KB for my true model.) `back_prop = True` or `False` makes almost no difference.

Later iterations perform more or less identically for both.

It looks like instead of converting the `for` loop to `tf.while_loop`, AutoGraph unrolls it completely.

Note that using `unroll=True` in the RNN (since it's only one step anyway) slashes AutoGraph tracing and graph size in half, perhaps not so surprisingly. 

**Describe the expected behavior**
I would expect AutoGraph to interpret the `for` loop as a `tf.while_loop`.

I understand there is always first execution overhead, but it seems very unnecessary here.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1aALb-2wQoHIomJ7S5sLwJYmcciX5kpoM
https://gist.github.com/meowcat/8b3b4b9c66264e685e339ff4e43af882

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@meowcat 

I tried to reproduce the issue in colab with TF 2.1.0.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/686c5a13c62ef638a6f7004d2781ac8b/untitled784.ipynb). Is this the expected behavior?.Thanks!

**Comment by meowcat** [comment]
Hi,

yes, your gist reproduces the bug correctly. Specifically, the first iteration of the `decode_beam_forloop` takes 14 seconds, and it produces an `events.out.tfevents.....v2` with 3.5MB file size.

**Comment by kkimdev** [comment]
Hi, please use tf.range() instead of range() https://www.tensorflow.org/api_docs/python/tf/range

**Comment by meowcat** [comment]
Hi,
thanks, that works, but isn't the point of Autograph / tf.function that I shouldn't have to do this?

**Comment by kkimdev** [comment]
We wanted to give users an option to create a graph with an unroll loop, and this is how users can control it.  Though yes, I agree that it's not too apparent and can be confusing.  We are discussing improving this but no decision at this point.
