### ISSUE TITLE
tf.keras h5 file to pb xx is not in graph

### ISSUE THREAD

**Issue by jetou** [tensorflow/tensorflow#38624]
my tensorflow version is 2.1, i want from tf.keras .h5 model transform to pb file. but i get follow  issues. 

```

def freeze_session(session, keep_var_names=None, output_names=None, clear_devices=True):

    graph = session.graph
    with graph.as_default():
        freeze_var_names = list(set(v.op.name for v in tf.compat.v1.global_variables()).difference(keep_var_names or []))
        output_names = output_names or []
        output_names += [v.op.name for v in tf.compat.v1.global_variables()]
        # Graph -> GraphDef ProtoBuf
        input_graph_def = graph.as_graph_def()
        if clear_devices:
            for node in input_graph_def.node:
                node.device = ""
        frozen_graph = tf.compat.v1.graph_util.convert_variables_to_constants(session, input_graph_def,
                                                      output_names, freeze_var_names)
        return frozen_graph
```

```
frozen_graph = freeze_session(tf.compat.v1.keras.backend.get_session(),
                              output_names=[out.op.name for out in model.outputs])

```
AssertionError                            Traceback (most recent call last)
<ipython-input-10-ec0ab52adbd4> in <module>
      3 
      4 frozen_graph = freeze_session(tf.compat.v1.keras.backend.get_session(),
----> 5                               output_names=[out.op.name for out in model.outputs])

<ipython-input-8-b5cce8f2cb8f> in freeze_session(session, keep_var_names, output_names, clear_devices)
     12                 node.device = ""
     13         frozen_graph = tf.compat.v1.graph_util.convert_variables_to_constants(session, input_graph_def,
---> 14                                                       output_names, freeze_var_names)
     15         return frozen_graph

~/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py in new_func(*args, **kwargs)
    322               'in a future version' if date is None else ('after %s' % date),
    323               instructions)
--> 324       return func(*args, **kwargs)
    325     return tf_decorator.make_decorator(
    326         func, new_func, 'deprecated',

~/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/framework/graph_util_impl.py in convert_variables_to_constants(sess, input_graph_def, output_node_names, variable_names_whitelist, variable_names_blacklist)
    275   # This graph only includes the nodes needed to evaluate the output nodes, and
    276   # removes unneeded nodes like those involved in saving and assignment.
--> 277   inference_graph = extract_sub_graph(input_graph_def, output_node_names)
    278 
    279   # Identify the ops in the graph.

~/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py in new_func(*args, **kwargs)
    322               'in a future version' if date is None else ('after %s' % date),
    323               instructions)
--> 324       return func(*args, **kwargs)
    325     return tf_decorator.make_decorator(
    326         func, new_func, 'deprecated',

~/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/framework/graph_util_impl.py in extract_sub_graph(graph_def, dest_nodes)
    195   name_to_input_name, name_to_node, name_to_seq_num = _extract_graph_summary(
    196       graph_def)
--> 197   _assert_nodes_are_present(name_to_node, dest_nodes)
    198 
    199   nodes_to_keep = _bfs_for_reachable_nodes(dest_nodes, name_to_input_name)

~/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/framework/graph_util_impl.py in _assert_nodes_are_present(name_to_node, nodes)
    150   """Assert that nodes are present in the graph."""
    151   for d in nodes:
--> 152     assert d in name_to_node, "%s is not in graph" % d
    153 
    154 

AssertionError: dense_5/Identity is not in graph

**Comment by ravikyram** [comment]
@jetou 

Looks like code is incomplete. Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by jetou** [comment]
https://drive.google.com/open?id=1F5qT5y_rG8sIyYOJNDpz-QsgRNACgPtf

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.1.0, 2.2.0-rc3 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/884adce46883d11342c8c4e14b887cbb/untitled785.ipynb). Thanks!

**Comment by gowthamkpr** [comment]
@jetou The freeze graph APIs - freeze_graph.py and converter_variables_to_constants - will not be supported in TensorFlow 2.0.
For more information you can refer to the following [question](https://stackoverflow.com/questions/55562078/tensorflow-2-0-frozen-graph-support)

**Comment by jetou** [comment]
I solve this problem in the tensorflow2.1 just use
```
from tensorflow.keras.models import Model, load_model
model = load_model(MODEL_FULLPATH)
model.save(MODEL_FULLPATH_MINUS_TERMINATION)
```
