### ISSUE TITLE
Does not have sufficient slices for partitioned tensor

### ISSUE THREAD

**Issue by yanghzcc** [tensorflow/tensorflow#38629]
https://stackoverflow.com/questions/56930685/pywrap-tensorflow-checkpoint-reader-fails-for-ftrl-states-of-partitioned-variabl
i meet the same problem, can anyone solve it? thanks

**Comment by Saduf2019** [comment]
@yanghzcc 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Also include your TensorFlow version. 


We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by Saduf2019** [comment]
@yanghzcc,
please update as per above comment
