### ISSUE TITLE
How does the "tensorflow/compiler/mlir/tensorflow/ir/tf_generated_ops.td" file generated?

### ISSUE THREAD

**Issue by ai-jit** [tensorflow/tensorflow#38633]
How does the "tensorflow/compiler/mlir/tensorflow/ir/tf_generated_ops.td" file generated?

**Comment by ai-jit** [comment]
@jpienaar Hi, is there any script in TF to generate the contents in "tensorflow/compiler/mlir/tensorflow/ir/tf_generated_ops.td" ?

**Comment by ravikyram** [comment]
This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by ai-jit** [comment]
OK. Thanks anyway.
