### ISSUE TITLE
Why there are serveral topkv2 ops

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/tensorflow#38637]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):ubuntu18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):tensorflow2.1
- Python version:3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
![Screenshot from 2020-04-17 18-27-35](https://user-images.githubusercontent.com/17592563/79559932-27ab0780-80d9-11ea-9472-f89f98a04ea8.png)
**Describe the expected behavior**
Only one topkV2
**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

https://github.com/google/automl/blob/028789605f1f140b00c045f77be2c4e13638d17c/efficientdet/det_model_fn.py#L313

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

[trace.json](https://drive.google.com/open?id=1lPiHuSDjdcBL9IoQg3kRHE3Ff2toyVwB)

**Comment by ymodak** [comment]
Can you please provide a reproducible code to validate the issue reported?
Thanks!

**Comment by fsx950223** [comment]
> Can you please provide a reproducible code to validate the issue reported?
> Thanks!

https://colab.research.google.com/drive/1duD_fPzP0cEVK-EmJEEDtagNnX3XjgJP

**Comment by alextp** [comment]
Why do you expect to see only one operation in the timeline? Estimator will run the graph in a loop and each execution will show up on the timeline.

**Comment by fsx950223** [comment]
I use the session directly without Estimator for inference.

**Comment by fsx950223** [comment]
Execute time seems 6 times slower than execute top_k directly with the same shape input test case.
