### ISSUE TITLE
How to Save Model with TF2.x Keras Multiworker Distributed Training?

### ISSUE THREAD

**Issue by AlexanderJLiu** [tensorflow/tensorflow#38635]
**Description:**

I've created a  `Keras` model, and trained it with `multiworker distributed strategy`.

Every worker uses the same python scripts for training. I uses `model.save` function for model saving with the same `hdfs path`.

After training, every worker would try to save model to the `path`, and it will cause race condition, because all of them want to handle the same `variables files`.

**Code snippets**

```python
tf_config = {
    "task": {
        "index": 0,
        "type": "worker"
    },
    "cluster": {
        "worker": ["localhost:21834", "localhost:27271"],
    }
}
os.environ["TF_CONFIG"] = json.dumps(tf_config)
print(json.loads(os.environ["TF_CONFIG"]))


def main(argv):
    del argv  # Unused
    BATCH_SIZE = 100
    SAMPLE_SIZE = 50000
    strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()
    with strategy.scope():
        model = tf.keras.Sequential([
            layers.Dense(64, activation='relu'),
            layers.Dense(32, activation='relu'),
            layers.Dense(1, activation='sigmoid')
        ])
        model.compile(optimizer=tf.keras.optimizers.Adam(),
                      loss=tf.keras.losses.BinaryCrossentropy(),
                      metrics=[tf.keras.metrics.AUC()])
    log_dir = FLAGS.logs
    tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir,
                                                          histogram_freq=1,
                                                          update_freq='epoch')
    train_dataset = tf.data.Dataset.from_tensor_slices(
        (np.random.randint(1000, size=(SAMPLE_SIZE, 31)),
         np.random.randint(2, size=(SAMPLE_SIZE, 1))))
    train_dataset = train_dataset.batch(BATCH_SIZE)
    validation_dataset = tf.data.Dataset.from_tensor_slices(
        (np.random.randint(1000, size=(SAMPLE_SIZE, 31)),
         np.random.randint(2, size=(SAMPLE_SIZE, 1))))
    validation_dataset = validation_dataset.batch(BATCH_SIZE)
    options = tf.data.Options()
    options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.DATA
    train_dataset = train_dataset.with_options(options)
    validation_dataset = validation_dataset.with_options(options)
    model.fit(train_dataset,
              epochs=5,
              steps_per_epoch=10,
              validation_data=validation_dataset,
              validation_steps=5)
    model_dir = FLAGS.logs + '/models'
    model.save(model_dir)

if __name__ == '__main__':
    app.run(main)
```

**Question:**

In my opinion, the save should only be done by the `chief worker` not all of them. So

1. Is there some problem with my `save` code?
2. Should I change the path for different workers? If so, which model is the final model for serving?
3. Is there a way that chief worker saves model only?

Thanks ~

**Comment by ymodak** [comment]
Did you get a chance to see [Multi-worker training with Keras](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras#multi-worker_configuration) example? That should help answer some of your questions. Thanks!

**Comment by ckkuang** [comment]
Ideally the save should only be done by the chief worker, but it is a bit unfortunate that currently all workers in `MultiworkerMirroredStrategy` will try to save the model, and because they run the same piece of code, they will save to the same location. AFAIK the main reason behind this is `model.save` is not and in principle should not be made to be aware of which worker is running it.

I heard there are plans to make it better. For now you can use different saving paths for different workers , and at the end delete the paths if the code is running on non-chief workers. The model saved by chief worker can be used for serving (in fact models saved by different workers are identical).

**Comment by AlexanderJLiu** [comment]
@ymodak Yes, I've read that before. But I don't  think it will help with my doubts about  **Model  Save**

**Comment by AlexanderJLiu** [comment]
@ckkuang Thanks very much~.  Really helpful to me.
