### ISSUE TITLE
Issue with Tensorshape and Datasets

### ISSUE THREAD

**Issue by jostheim** [tensorflow/tensorflow#38645]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):

Yes

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

Linux Ubuntu 18.04

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:

N/A

- TensorFlow installed from (source or binary):

binary (pip)

- TensorFlow version (use command below):

v2.1.0-rc2-17-ge5bf8de
2.1.0

- Python version:

3.7.7

- Bazel version (if compiling from source):

N/A

- GCC/Compiler version (if compiling from source):

N/A

- CUDA/cuDNN version:

10.1

- GPU model and memory:

GTX 1080 Ti, 11 GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I am trying to use tf.Dataset with generators, I am getting the following very strange error trying to build tf.TensorShape:

```
TypeError: in converted code:

    <ipython-input-86-05d6b5f23a20>:11 None  *
        ds = ds.interleave(lambda gen_idx: tf.data.Dataset.from_generator(gen_wrapper,
    /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py:744 from_generator
        output_types, tensor_shape.as_shape, output_shapes)
    /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/data/util/nest.py:471 map_structure_up_to
        results = [func(*tensors) for tensors in zip(*all_flattened_up_to)]
    /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/data/util/nest.py:471 <listcomp>
        results = [func(*tensors) for tensors in zip(*all_flattened_up_to)]
    /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py:1211 as_shape
        return TensorShape(shape)
    /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py:771 __init__
        self._dims = [as_dimension(d) for d in dims_iter]
    /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py:771 <listcomp>
        self._dims = [as_dimension(d) for d in dims_iter]
    /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py:716 as_dimension
        return Dimension(value)
    /home/jostheim/virtualenvs/data_science/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_shape.py:200 __init__
        None)
    <string>:3 raise_from
        

    TypeError: Dimension value must be integer or None or have an __index__ method, got TensorShape([1])
```

**Describe the expected behavior**

The ints I pass into TensorShape should be recognized as ints and not throw an error.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
def gen(): 
  for i in itertools.count(1): 
    yield (i, [1] * i) 
ds = tf.data.Dataset.from_tensor_slices(list(range(24)))
ds = ds.interleave(lambda gen_idx: tf.data.Dataset.from_generator(gen,
                                                                  output_types=(tf.float32),
                                                                  args=(gen_idx,),
                                                                  output_shapes=(tf.TensorShape([]), tf.TensorShape([None]))),
                   cycle_length=24,
                   block_length=1,
                   num_parallel_calls=24)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by jostheim** [comment]
Still not sure why this doesn't work, but I worked around it.

**Comment by timothyjlaurent** [comment]
@jostheim How did you work around the problem? I'm seeing the same thing in one (but not the other) of a dataset from generator

**Comment by jostheim** [comment]
@timothyjlaurent timothyjlaurent I made a callback where I run evaluate using a Sequence and manually stick the metrics into tensorboard

```
class ValidationCallback(keras.callbacks.Callback):

    def __init__(self, validation_gen, prefix, file_writer):
        super(ValidationCallback, self).__init__()
        config = get_config()
        self.config = config
        self.validation_gen = validation_gen
        self.prefix = prefix
        self.file_writer = file_writer
        self.classes = {0: 'spread', 1: 'ml', 2: 'over', 3: 'under'}

    def on_batch_end(self, batch, logs=None):
        if batch % 1000 == 0 and batch != 0:
            logger.info('')
            logger.info(f'learning_rate {keras.backend.eval(self.model.optimizer._decayed_lr(tf.float32))}')
            logger.info('')

    def on_epoch_end(self, epoch, logs=None):
        # with a Sequential model
        metrics = self.model.evaluate(self.validation_gen,
                                      verbose=1,
                                      use_multiprocessing=False if self.config['train'].as_bool('use_dataset') else True,
                                      workers=int(self.config['train']['num_workers']) if not self.config['train'].as_bool('use_dataset') else 1)
        with self.file_writer.as_default():
            for name, metric in zip(self.model.metrics_names, metrics):
                logger.info('metric name {} prefix {}'.format(name, self.prefix))
                tf.summary.scalar('{}_{}'.format(self.prefix, name), metric, step=epoch)
                logs['{}_{}'.format(self.prefix, name)] = metric
        logger.info('flushing file writer')
```

Some of that stuff is for my particular use case, but that is the basic gist. For file_writer

```
file_writer = tf.summary.create_file_writer(tensorboard_directory + "/metrics")
```
I hope this helps!
