### ISSUE TITLE
K.cast_to_floatx() will convert "None" to "Nan" and lead the ReLU to Nan output.

### ISSUE THREAD

**Issue by shiningrain** [tensorflow/tensorflow#38640]
**System information**  
- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):   Linux Ubuntu 18.04
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.14.0-cpu
- Python version:  3.6.9
- CUDA/cuDNN version:  -
- GPU model and memory:  -

**Describe the current behavior**  

I found that if I used `ReLU(threshold = None)` in `tensorflow.keras`, without any errors or warnings, Tensorflow will return a matrix with Nan.  (Detailed configuration and codes for reproduction can be found in the following part) .

For this reason, I did some investigations and found that when the parameters in `ReLU` are passed to `/tensorflow/python/keras/layers/advanced_activations.py line near line 311`, `K.cast_to_floatx()`  will incorrectly convert the "None" parameter to "Nan" and pass it to the backend for calculation (refer to Figure 1 and Figure 2).  

"Nan" and "None" should have different meanings, but `K.cast_to_floatx` did not distinguish between "Nan" and "None" during the calculation, which led to the usage of a "Nan" parameter in the tensorflow calculation. This further affects the final output result and makes the output with  "Nan". This operation may confuse the users.  

**Is there a difference in meaning between None and Nan in the implementation of `K.cast_to_floatx`?  Judging from the current results, their meanings are different.**   This issue n**ot only affect ReLU, but also affect ThresholdReLU, LeakyReLU and other operations using `K.cast_to_floatx()`** to convert the parameters.

## Code to reproduce the issue

```
import os
import numpy as np
import tensorflow as tf
import tensorflow.keras.layers as L
from tensorflow.keras.models import load_model


root_path = "./Your Path"
layer_name="ReLU"
kwargs={'max_value': 0.5761369157060329, 'negative_slope': 0.7845179761191806, 'threshold': None}
input= (10 * np.random.randn(1,32,32,16)).astype(np.float32)
from tensorflow.keras import Model, Input
layer_cls = getattr(L, layer_name)
layer = layer_cls(**kwargs)
x = Input(batch_shape=input.shape)
y = layer(x)
bk_model =Model(x, y)
model_path = os.path.join(root_path, 'model.h5')
bk_model.save(model_path, bk_model)
model = load_model(model_path)     
output = model.predict(input)
nanresult=np.isnan(output).any()
print(nanresult)
```

**Comment by Saduf2019** [comment]
@shiningrain 
i ran the code shared and face [this error](https://colab.sandbox.google.com/gist/Saduf2019/673d2c21fcf02091f8243c5ac51f72a9/38640.ipynb)

**Comment by shiningrain** [comment]
> @shiningrain
> i ran the code shared and face [this error](https://colab.sandbox.google.com/gist/Saduf2019/673d2c21fcf02091f8243c5ac51f72a9/38640.ipynb)

Hello! Thanks for your reply!
The "root path" in my code is "./ Your Path", this means that you can set any path you want to save the following model... You can also delete it and just save the model in the current dir. You can also use this code:
```
import os
import numpy as np
import tensorflow as tf
import tensorflow.keras.layers as L
from tensorflow.keras.models import load_model


layer_name="ReLU"
kwargs={'max_value': 0.5761369157060329, 'negative_slope': 0.7845179761191806, 'threshold': None}
input= (10 * np.random.randn(1,32,32,16)).astype(np.float32)
from tensorflow.keras import Model, Input
layer_cls = getattr(L, layer_name)
layer = layer_cls(**kwargs)
x = Input(batch_shape=input.shape)
y = layer(x)
bk_model =Model(x, y)
bk_model.save("model.h5", bk_model)
model = load_model("model.h5")     
output = model.predict(input)
nanresult=np.isnan(output).any()
print(nanresult)
```
As the following picture shown, the `nanresult` is True, which means there is nan in `output`

![image](https://user-images.githubusercontent.com/46860123/79586408-a452db80-8103-11ea-85f7-9b1e0310ef3f.png)

**Comment by shiningrain** [comment]
Hello, @Saduf2019  I can also reproduce this issue in Tensorflow 2.1.0-cpu version, shown in the following figure. You can use the code in my reply to reproduce it.
![image](https://user-images.githubusercontent.com/46860123/79631518-6ea60500-818c-11ea-9493-221ccd343132.png)

**Comment by Saduf2019** [comment]
i am able to replicate this issue, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/bd0e794e3005cee01640dca7926e946f/untitled141.ipynb)

**Comment by shiningrain** [comment]
> i am able to replicate this issue, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/bd0e794e3005cee01640dca7926e946f/untitled141.ipynb)

Thanks for your reply! That is exactly what I want to show. 
`K.cast_to_floatx()` will convert None to nan, which are not the same things. And then it leads to nan output.

**Comment by ymodak** [comment]
The documentation says `threshold: Float` . Perhaps we can add check to pass a float value to threshold argument. 
https://www.tensorflow.org/api_docs/python/tf/keras/layers/ReLU#arguments_2

**Comment by shiningrain** [comment]
> The `none` to `nan` conversion is due to numpy behavior.
> https://github.com/tensorflow/tensorflow/blob/e5bf8de410005de06a7ff5393fafdf832ef1d4ad/tensorflow/python/keras/backend.py#L183
> 
> ```python
> import numpy as np
> np.asarray(None, dtype=float)
> ```
> 
> output:
> 
> ```python
> array(nan)
> ```
> 
> However the documentation says `threshold: Float` . Perhaps we can add check to pass a float value to threshold argument.
> https://www.tensorflow.org/api_docs/python/tf/keras/layers/ReLU#arguments_2

That's a good idea! Thanks for your fix.
