### ISSUE TITLE
Cross-posting from Keras Memory leaks hang on GPU; no PID to kill (not sudo user so cannot install nvtop)

### ISSUE THREAD

**Issue by brethvoice** [tensorflow/tensorflow#38651]
https://github.com/keras-team/keras/issues/13975

**Comment by karmel** [comment]
For this use case, we would suggest that you write a custom Callback to handle the extra processing you want after each step or batch. You can read more about callbacks here: https://www.tensorflow.org/guide/keras/custom_callback
