### ISSUE TITLE
clip_by_value handles python float and numpy float differently

### ISSUE THREAD

**Issue by leeyeetonn** [tensorflow/tensorflow#38658]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 16.04 & macos10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): ubuntu 16.04: v2.1.0-rc2-17-ge5bf8de & macos: v2.1.0-rc2-17-ge5bf8de410
- Python version: 3.7.6
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
`clip_by_value(t, clip_value_min, clip_value_max)` treats python float and numpy float32/float64 differently for parameters `clip_value_min` and `clip_value_max`.

It throws exception when `t` is `int`, `clip_value_min` and `clip_value_max` are `float`, but it **doesn't** throw exception when `clip_value_min` and `clip_value_max` are numpy float. See the example below.

**Describe the expected behavior**
I expect the behavior should be consistent whether the passed in `clip_value_min` and `clip_value_max` are python `float` or numpy `float`. 

It shouldn't silently cast numpy `float` to `int` and report unexpected result.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```python
import tensorflow as tf
import numpy as np

# ok case
tf.clip_by_value([1,2,3], clip_value_min=0, clip_value_max=1) 

# exception when using python float
tf.clip_by_value([1,2,3], clip_value_min=0., clip_value_max=1.)

# no exception when using numpy float16/32/64
tf.clip_by_value([1,2,3], clip_value_min=np.float32(0.), clip_value_max=np.float32(1.))

# no exception; same output as above;
# 0.5 is silenlty casted to 0, and 1.2 is silently casted to 1
tf.clip_by_value([1,2,3], clip_value_min=np.float32(0.5), clip_value_max=np.float32(1.2))
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/38f5f93247775bd0ad7e1892a45c130c/38658-2-1.ipynb), [TFv2.2.0-rc3](https://colab.research.google.com/gist/amahendrakar/636509f9af81761c8a974c23fa36a906/38658-2-2.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/a4999bb2386d34dffed2909e6309fd63/38658-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by ymodak** [comment]
You have to cast your input `t` to float explicitly if using `clip_value` as float.
https://github.com/tensorflow/tensorflow/blob/6728f85d82d73c34ce9cb7cf03e311c9965f13f6/tensorflow/python/ops/clip_ops.py#L78
```python
# tf.cast the input to float first
tf.clip_by_value(tf.cast([1,2,3],dtype= 'float32'), clip_value_min=0., clip_value_max=1.)
```

**Comment by leeyeetonn** [comment]
@ymodak Yes, I understand that usage.

However, when I don't cast `t`,  it doesn't explain the inconsistent handling of numpy float and python float, where `clip_by_value` doesn't throw an exception when I use `clip_value_min=np.float(0.)`  and `clip_value_max=np.float(1.)`, but throws `TypeError` if they are python float.

Also, it's obvious there's silent casting in the fourth example code I provided. I believe that's inadequate handling of the input without warning the user.

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210525, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/442a37d03f6051ff30f40c989a7ed241/38658.ipynb). Thanks!

**Comment by tilakrayal** [comment]
Was able to reproduce the issue in tf v2.7.Please find the gist [here](https://colab.sandbox.google.com/gist/tilakrayal/0971cc14430b1f9ca5acf52833fe29ba/untitled155.ipynb).

**Comment by tilakrayal** [comment]
@leeyeetonn,
As per the documentation, whenever we are trying to use dtype=tf.int32 , it throws a **TypeError** if you try to clip an int to a float value ([tf.cast](https://www.tensorflow.org/api_docs/python/tf/cast) the input to float first) which was intended.

![image](https://user-images.githubusercontent.com/81610181/223092890-98ccf5a5-339b-4f38-add6-390d5ba267ce.png)

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/clip_ops.py

**Comment by tilakrayal** [comment]
Closing this as stale. Please reopen if this is still a valid request. Thank you!
