### ISSUE TITLE
Using variable value in tf.name_scope raises ValueError in graph mode

### ISSUE THREAD

**Issue by sumanthratna** [tensorflow/tensorflow#38661]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: macOS 10.15.5 Beta
- Mobile device: n/a
- TensorFlow installed from binary (`pip`)
- TensorFlow version: 
    - `tf.version.GIT_VERSION`: v2.1.0-rc2-17-ge5bf8de410
    - `tf.version.VERSION`: 2.1.0
- Python version: 3.6.8
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a (currently developing on CPU)

**Describe the current behavior**
Example code:
```python
import tensorflow as tf

class MyModule(tf.Module):
    def __init__(self, name):
        super(MyModule, self).__init__(name=name)

@tf.function
def graphcry():
    mod_inst1 = MyModule(name='inst1')
    mod_inst2 = MyModule(name='inst2')
    myscalar = tf.constant(83.2)
    with tf.name_scope('scalaragain'):
        tf.summary.scalar('scalaragain', data=myscalar)
    with tf.name_scope(mod_inst1.name + ' and ' + mod_inst2.name):
        tf.summary.scalar('myscalar', data=myscalar)

graphcry()
```
results in this error:
```
 with tf.name_scope(mod_inst1.name + ' and ' + mod_inst2.name):
    .../site-packages/tensorflow_core/python/framework/ops.py:6392 __enter__
        scope_name = scope.__enter__()
    /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py:81 __enter__
        return next(self.gen)
   .../site-packages/tensorflow_core/python/framework/ops.py:4024 name_scope
        raise ValueError("'%s' is not a valid scope name" % name)

    ValueError: 'inst1 and inst2' is not a valid scope name
```
I may be misunderstanding something about Graph mode, but at the very least, I think a better error should be shown (the docs say `ValueError` is raised when the argument to `tf.name_scope` is `None` or not a string). 

And excuse my poor variable naming and nonadherence to PEP 8—I wrote this in nano. 

**Describe the expected behavior**
The scalar should be logged to TensorBoard without any errors, and under the name scope `inst1` and `inst2`. 

**Standalone code to reproduce the issue**
A minimal reproducible example is in the current behavior section.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by sumanthratna** [comment]
Here's a smaller reproducible example:
```python
```

**Comment by Saduf2019** [comment]
@sumanthratna 
can you please refer to these lonks and let us know if it helps [link1](https://stackoverflow.com/questions/51876460/getting-tensorflow-s-is-not-valid-scope-name-error-while-i-am-trying-to-creat) [link2](https://github.com/oswaldoludwig/Seq2seq-Chatbot-for-Keras/issues/12)

**Comment by sumanthratna** [comment]
For the first link: the string `'inst1 and inst2'` should pass the regex test—it only contains alpha characters. 

I'm not using Keras, so the second link doesn't apply to my case.

**Comment by Saduf2019** [comment]
i ran the code shared, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/2542174318deb80fd957706d6ca4e24f/38661.ipynb)

**Comment by sumanthratna** [comment]
Interestingly, it looks like `tf.Module` isn't specifically the problem. The following returns the same error:
```python
import tensorflow as tf

@tf.function
def graphcry():
    inst1 = 'inst1'
    inst2 = 'inst2'
    myscalar = tf.constant(83.2)  # just a random number
    with tf.name_scope('scalaragain_scope'):
        tf.summary.scalar('scalaragain', data=myscalar)  # this works!
    with tf.name_scope(inst1 + ' and ' + inst2):
        tf.summary.scalar('myscalar', data=myscalar)  # this returns the error above

graphcry()
```

**Comment by sumanthratna** [comment]
And the following also fails:
```python
import tensorflow as tf


def graphcry():
    inst1 = 'inst1'
    inst2 = 'inst2'
    myscalar = tf.constant(83.2)  # just a random number
    with tf.name_scope('scalaragain_scope'):
        tf.summary.scalar('scalaragain', data=myscalar)  # this works!
    with tf.name_scope(inst1 + ' and ' + inst2):
        tf.summary.scalar('myscalar', data=myscalar)  # this returns the error above

tf.function(graphcry)()
```

**Comment by jvishnuvardhan** [comment]
@sumanthratna There are some constraints on the `name_scope`. If you remove the spaces in your name_scope as in the example below, then everything works as expected.

Replace this line
`tf.name_scope(mod_inst1.name + ' and ' + mod_inst2.name)`

with this line
`tf.name_scope(mod_inst1.name + '_and_' + mod_inst2.name)`

Check the [source here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L4149) and related stackoverflow [question here](https://stackoverflow.com/a/44664366/9936228). Thanks!

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by sumanthratna** [comment]
Thanks for your reply! You're correct, removing spaces does fix the issue. However, I still see this as a bug—in eager mode (without the `tf.function`), spaces are allowed. On the other hand, spaces aren't allowed with autograph. 

One would expect the `name_scope` constraints to be the same for both modes of execution.

**Comment by jvishnuvardhan** [comment]
@sumanthratna For the benefit of users, can you please close the issue and open a new issue mentioning this error happens with "eager" mode only. It will be easy for the users to follow the issue better. You can ping me in that issue. 

Please let us know what you think. Thanks!
