### ISSUE TITLE
In ModelCheckpoint, filepath is not accepting batch as formatting parameter.

### ISSUE THREAD

**Issue by ashutosh1919** [tensorflow/tensorflow#38668]
In `ModelCheckpoint` callback, there is a parameter given named `save_freq` to save model. If `save_freq` is set to `epoch`, it will save model at the end of every epoch. (This works perfectly fine). But when `save_freq` is set to an integer let's say `N`, then the callback should save the model after `N` batches in every epoch. But the problem here is the callback doesn't accept the filepath as `file.batch{batch:02d}epoch{epoch:02d}.h5` and raises error as `batch` is invalid key.  
The problem in the code that I have noticed is that the `_save_model` function has access to `epoch` but it doesn't have access to `batch`. And that's why `_get_file_path()` has access to `epoch` but not `batch`.  The functionality should be changed little bit. I am raising PR to add access to `batch` param in both `_save_model` and `_get_file_path` variable.
I noticed this error in tf code during the work on my PR [#1702](https://github.com/tensorflow/addons/pull/1702) in tensorflow/addons.  

cc @gabrieldemarmiesse.

**Comment by goldiegadde** [comment]
@ashutosh1919 would be willing to send a PR for this issue ?

**Comment by motionlife** [comment]
same problem here. It should support batch number formatting, especially when save_freq is not epoch but batch, only have epoch number would make previous weights files of same epoch been override.

**Comment by aningineer** [comment]
Same issue here. Is there actually no support for this yet?

**Comment by ashutosh1919** [comment]
@aningineer , I have raised PR #49376 to fix this issue and you can see that it is approved as well. Let it get merged and you will be able to use this issue in `tf-nightly`

**Comment by qlzh727** [comment]
The PR that fix this issue is merged to keras-team/keras as keras-team/keras@c567184. Closing this now.

**Comment by DharmendraGITHB** [comment]
next  PR
