### ISSUE TITLE
WARNING: 3 cannot be handled by this delegate. Only the first 0 ops will run on the GPU, and the remaining 17 on the CPU.

### ISSUE THREAD

**Issue by nazmulasha** [tensorflow/tensorflow#38664]
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10
    Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:Iphone XR
    TensorFlow installed from (source or binary):binary
    TensorFlow version: 1.14 (gpu)
    Python version:3.6
    Installed using virtualenv? pip? conda?:pip
    Bazel version (if compiling from source):
    GCC/Compiler version (if compiling from source):
    CUDA/cuDNN version: 10
    GPU model and memory: 1070Ti - 8GB

I have converted .h5 to .tflite. It's working perfectly with CPU but not with GPU. 
It's showing following error:
'WARNING: 3 cannot be handled by this delegate. Only the first 0 ops will run on the GPU, and the remaining 17 on the CPU.'
Here is my model: 
https://drive.google.com/file/d/1osGt-pr9hh9qvslrKY2TaxOLkwWsEA-2/view?usp=sharing

**Comment by ravikyram** [comment]
@nazmulasha 

Request you to share simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by nazmulasha** [comment]
@ravikyram 
I have changed the tensorflow version and now it's fine. But I got a new error now. I have used PRelu and it's giving me the following error.
'Dimensions are not BHWC'.

**Comment by jvishnuvardhan** [comment]
@nazmulasha Can you please give more details on the error or share full trace of the error. 
1) Are you testing any classification model?
2) What were the steps you followed before noticing this error?
3) Can you share labels.txt, so that I will try to check with an android device?

Please give as many details as possible to find root-cause of the issue. Thanks!

**Comment by nazmulasha** [comment]
@jvishnuvardhan I have already fixed it.

**Comment by jvishnuvardhan** [comment]
Closing this as this was resolved already. Thanks!
