### ISSUE TITLE
Unable To Find Relevant Documentation For Quantization from python/tf/dtype/DType 

### ISSUE THREAD

**Issue by Rubix982** [tensorflow/tensorflow#38673]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/dtypes/DType

## Description of issue (what needs changing):

The dtypes, such as, `tf.qint8`, `tf.quint8`, `tf.qint16`, `tf.quint16`, `tf.qint32`, are a bit unclear. What is `Quantized` suppose to mean? Where should a reader go to learn more about it? Clicking on the hyperlink of any of the dtypes of the above leads to [tf](https://www.tensorflow.org/api_docs/python/tf) which is just text. It does not give info about variable itself ( what is `quantization`? How and why is it an `int` ? )

### Clear description

No clear description about what `quantization` really means. 
Googling for `quantized tensorflow` leads us to,
1): [Post training quantization](https://www.tensorflow.org/lite/performance/post_training_quantization)
2): [TensorFlow Lite 8-bit quantization specification](https://www.tensorflow.org/lite/performance/quantization_spec)
3): [Converting Quantized Models](https://www.tensorflow.org/lite/convert/quantization)
4): [tf.quantization.quantize](https://www.tensorflow.org/api_docs/python/tf/quantization/quantize)
5): [Post-training dynamic range quantization](https://www.tensorflow.org/lite/performance/post_training_quant)

None of which give a quick definition into what `quantization` is and what it is in Tensorflow.

### Correct links

The link is correct, it is this https://www.tensorflow.org/api_docs/python/tf/dtypes/DType#tf.qint32 .

### Parameters defined

Not related to code.

### Returns defined

Not based on code.

### Raises listed and defined

Not related to code.

### Usage example

Not related to code.

### Request visuals, if applicable

Not really.

### Submit a pull request?

I do not plan to. Don't really have the time. 

This is similar to issue #15 , closed, at [here](https://github.com/tensorflow/tensorflow/issues/15) and #494, [here](https://github.com/tensorflow/tensorflow/issues/494).

Thank you! And have a nice day.

**Comment by oke-aditya** [comment]
Please have a look at [model_optimization](https://www.tensorflow.org/lite/performance/model_optimization)

Quantization refers to converting the floating-point weights into integer weights. 
Usually while training our weights are in float64 or float32. 
Quantization reduces them to integer data type in either `tf.qint8, tf.quint8, tf.qint16, tf.quint16, tf.qint32` data type.
This saves up space, latency and other factors as appropriately discussed in the above link.

**Comment by Rubix982** [comment]
Hi @oke-aditya !
Thanks! That was useful.
The [model_optimization](https://www.tensorflow.org/lite/performance/model_optimization) page contains a useful heading for `Quantization`. Can we add a link to the before mentioned page on the [dtype page](https://www.tensorflow.org/api_docs/python/tf/dtypes/DType) ? It could help to quickly look up what `Quantization` actually means and for what purpose it exists.

**Comment by oke-aditya** [comment]
> 
> 
> Hi @oke-aditya !
> Thanks! That was useful.
> The [model_optimization](https://www.tensorflow.org/lite/performance/model_optimization) page contains a useful heading for `Quantization`. Can we add a link to the before mentioned page on the [dtype page](https://www.tensorflow.org/api_docs/python/tf/dtypes/DType) ? It could help to quickly look up what `Quantization` actually means and for what purpose it exists.

I am unsure of this also I am unsure where to update in source code as well.

**Comment by Rubix982** [comment]
@ymodak  can you help us out here? Thank you.

**Comment by mohantym** [comment]
Hi @Rubix982 ! Quantization is part of model optimization (Reduce download size, storage size, memory usage). Definition can be found [here](https://www.tensorflow.org/lite/performance/model_optimization#quantization) . Details of different datatypes can be found [here ](https://www.tensorflow.org/api_docs/python/tf/dtypes). Thank you!

**Comment by mohantym** [comment]
Sure @Rubix982 ! Feel free to raise a PR. Thank you!

**Comment by mohantym** [comment]
Hi @Rubix982 !
Are you still looking for any assistance for PR ?

As I said mentioned earlier , Current Documentation includes Quantization's definition [here.](https://www.tensorflow.org/lite/performance/model_optimization#quantization). 

> [Quantization](https://www.tensorflow.org/model_optimization/guide/quantization/post_training) works by reducing the precision of the numbers used to represent a model's parameters, which by default are 32-bit floating point numbers. This results in a smaller model size and faster computation.

Thank you!

**Comment by Rubix982** [comment]
Hi, @mohantym! I would firstly apologize and forfeit ownership of this issue. I have not been able to manage my life and time as much as I had hoped, and would like to transfer the ownership of this bug to any other volunteer.

I'm really sorry for the wasted time.

Thanks again for catching up with me.

**Comment by mohantym** [comment]
@Rubix982 !
Can you tell the changes and edit locations to me here in this thread. I will  raise a PR from your behalf.
Thank you!

**Comment by Rubix982** [comment]
Maybe a possible location could be here, https://www.tensorflow.org/api_docs/python/tf/dtypes. I am not sure if this term is used across the docs very extensively (quick searching shows that that is the case), or maybe only meant to be here. Because docs should have only 1 source describing something in detail, it can be useful to have separate page that explains quantization, and then, the link above can have a link to the `quantized` page that explains in more detail.

**Comment by pkgoogle** [comment]
Hi @Rubix982, it seems like quantization is already defined in the docs as described above, as such I don't believe there are any open items left for this issue, please close as completed if you have no more open items regarding this issue.

**Comment by Rubix982** [comment]
Hey, @pkgoogle! I've forgotten about this for a long time. I can close this, yeah.
