### ISSUE TITLE
import tensorflow as tfimport tensorflow.contrib.layers as layers   File "<ipython-input-23-4e7964698c5b>", line 1     import tensorflow as tfimport tensorflow.contrib.layers as layer SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by geet2019** [tensorflow/tensorflow#38676]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by geet2019** [comment]
import tensorflow as tfimport tensorflow.contrib.layers as layers
  File "<ipython-input-23-4e7964698c5b>", line 1
    import tensorflow as tfimport tensorflow.contrib.layers as layers
                                           ^
SyntaxError: invalid syntax

Occurred while trying to execute https://github.com/aqlaboratory/rgn/blob/master/model/protling.py

**Comment by geet2019** [comment]
Occurred while trying to execute https://github.com/aqlaboratory/rgn/blob/master/model/protling.py
[ I am new to python . please help to resolve probelms ] 
class ZoneoutWrapper(RNNCell):
  File "<ipython-input-7-10a3c41e0928>", line 1
    class ZoneoutWrapper(RNNCell):
                                  ^
SyntaxError: unexpected EOF while parsing

def __init__(self, cell, memory_cell_keep_prob=1.0, hidden_state_keep_prob=1.0,seed=None, is_training=True):
  File "<ipython-input-8-b6fb9a5d8816>", line 1
    def __init__(self, cell, memory_cell_keep_prob=1.0, hidden_state_keep_prob=1.0,seed=None, is_training=True):
                                                                                                                ^
SyntaxError: unexpected EOF while parsing

if (isinstance(memory_cell_keep_prob, float) and not (memory_cell_keep_prob >= 0.0 and memory_cell_keep_prob <= 1.0)):
  File "<ipython-input-18-0aa3a28c5b66>", line 1
    if (isinstance(memory_cell_keep_prob, float) and not (memory_cell_keep_prob >= 0.0 and memory_cell_keep_prob <= 1.0)):
                                                                                                                          ^
SyntaxError: unexpected EOF while parsing

 raise ValueError("Parameter memory_cell_keep_prob must be between 0 and 1: %d"  % memory_cell_keep_prob)
Traceback (most recent call last):

  File "<ipython-input-20-f8fedb42395d>", line 1, in <module>
    raise ValueError("Parameter memory_cell_keep_prob must be between 0 and 1: %d"  % memory_cell_keep_prob)

NameError: name 'memory_cell_keep_prob' is not defined

self._memory_cell_keep_prob = memory_cell_keep_prob    
Traceback (most recent call last):

  File "<ipython-input-22-5feb2a45dc43>", line 1, in <module>
    self._memory_cell_keep_prob = memory_cell_keep_prob

NameError: name 'memory_cell_keep_prob' is not defined

**Comment by ravikyram** [comment]
@geet2019 

I believe you are using TF 1.x. .I believe you are using both lines of code in single line.Please, use the below code

```
import tensorflow as tf 
import tensorflow.contrib.layers as layers
```
If you are still facing the issue, request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by geet2019** [comment]
thank you  . I will try it out

I would like to execute this work .
https://github.com/aqlaboratory/rgn/blob/master/model/protling.p
