### ISSUE TITLE
How properly apply a tokenizer map function to a Tensorflow batched dataset?

### ISSUE THREAD

**Issue by Ceceu** [tensorflow/tensorflow#38672]
Considering the following `batched_dataset`:

```python3
samples =  ([{"query": "this is a query 1", "doc": "this is one relevant document regarding query 1"}, 
              {"query": "this is a query 2", "doc": "this is one relevant document regarding query 2"},
              {"query": "this is a query 3", "doc": "this is one relevant document regarding query 3"},
              {"query": "this is a query 4", "doc": "this is one relevant document regarding query 4"},
              ])
dataset = tf.data.Dataset.from_generator( 
    lambda: samples, {"query": tf.string, "doc": tf.string})

batched_dataset = dataset.batch(2)

#{
#'doc': <tf.Tensor: shape=(2,), dtype=string, numpy=array(
#     [b'this is one relevant document regarding query 1',
#      b'this is one relevant document regarding query 2'], dtype=object)>,
# 
#'query': <tf.Tensor: shape=(2,), dtype=string, numpy=array(
#     [b'this is a query 1', 
#      b'this is a query 2'], dtype=object)>
#}

```
and a map function to tokenize this `batched_dataset`:

```python3
def tokenize(sample):
    tokenized_query = tokenizer.batch_encode_plus(sample["query"].numpy().astype('str'), ...)
    tokenized_doc = tokenizer.batch_encode_plus(sample["doc"].numpy().astype('str'), ...)
    return (tokenized_query, tokenized_doc) 
```
I could tokenize the entire batched_dataset using a for-loop:

```python3
for batch in batched_dataset:
    tokenize(batch)
# (
# {'input_ids': <tf.Tensor: shape=(2, 8), dtype=int32, numpy=
#   array([[  101,  2023,  2003,  1037, 23032,  1015,   102,     0],
#          [  101,  2023,  2003,  1037, 23032,  1016,   102,     0]],
#      dtype=int32)>, 
#  'attention_mask': <tf.Tensor: shape=(2, 8), dtype=int32, numpy=
#   array([[1, 1, 1, 1, 1, 1, 1, 0],
#          [1, 1, 1, 1, 1, 1, 1, 0]], dtype=int32)>}, 

# {'input_ids': <tf.Tensor: shape=(2, 8), #dtype=int32, numpy=
#   array([[ 101, 2023, 2003, 2028, 7882, 6254, 4953,  102],
#          [ 101, 2023, 2003, 2028, 7882, 6254, 4953,  102]], dtype=int32)>, 
#  'attention_mask': <tf.Tensor: shape=(2, 8), dtype=int32, numpy=
#   array([[1, 1, 1, 1, 1, 1, 1, 1],
#          [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>})
#  ...
```
 
However, when using [`tf.data.Dataset.map`][1] the following error arises:
```python3
tokenized_dataset = batched_dataset.map(tokenize)
AttributeError: 'Tensor' object has no attribute 'numpy'
```

Then, how properly apply a tokenizer map function to a batched dataset?

**Note**: I published a working example on [`Google Colab`][2].

  [1]: https://www.tensorflow.org/api_docs/python/tf/data/Dataset?version=nightly#map
  [2]: https://colab.research.google.com/drive/1TUbWwEgbgPHwY1QjgRLIqLpjin310pdh

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.2.0-rc3 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/e8f7ac6644b4cf76e88410e3ce5a7856/untitled788.ipynb).Thanks!

**Comment by gowthamkpr** [comment]
@Ceceu Please take a look at similar issue [here](https://github.com/tensorflow/tensorflow/issues/36979) and [here](https://github.com/tensorflow/tensorflow/issues/30035) and let me know if it helps. Thanks!

**Comment by BoHui-arch** [comment]
I think [tf.numpy_function](https://www.tensorflow.org/api_docs/python/tf/numpy_function?version=nightly) works for you.

**Comment by gowthamkpr** [comment]
@Ceceu Can you please respond to the above comment to take this discussion further. Thanks!

**Comment by oja** [comment]
Hi everyone, see a related issue where this doesn't work on TPU here https://github.com/huggingface/transformers/issues/5066

**Comment by Ceceu** [comment]
@gowthamkpr,

Currently I ended up refactoring my code to [torchtext](https://pytorch.org/text/examples.html) because it is much simpler to create an efficient data pipeline when you are using text datasets.

Until the Tensorflow v2.3, [tf.py_fuction](https://www.tensorflow.org/api_docs/python/tf/py_function) wrapper did not yet support dictionaries.

**Comment by gowthamkpr** [comment]
@Ceceu  Can you o ahead and close the issue as it has been resolved. Thanks!
