### ISSUE TITLE
Could we have more helpful error messages?

### ISSUE THREAD

**Issue by Tylersuard** [tensorflow/tensorflow#38678]
## Description of issue (what needs changing):
Tensorflow gives many errors, and most of them aren't very helpful.  Something like "module tensorflow has no attribute reset_graph."  Can we change the error messages so they are more constructive?  In this situation, the issue was partially solved by downgrading to tensorflow 1.12.  It would be helpful if instead of the "reset_graph" error message, we could get a message more like: "this version of tensorflow is incompatible with the current project.  Please downgrade to tensorflow 1.12 using: pip install tensorflow==1.12

### Clear description

For example, why should someone use this method? How is it useful?
To keep from tearing their own hair out.

**Comment by MarkDaoust** [comment]
Hi @Tylersuard,

We understand that TensorFlow errors can be opaque at times. We are working on it, in general.

But this specific error is a hard one to fix. It's a python AttributeError, and there's no way to fix it without converting TensorFlow modules  to some custom class with different errors depending on which non-existent attribute the user looks up... which would be messy and slow. So I don't think we can fix this.

We've been advertising for over a year that TensorFlow 2 would not be compatible with TensorFlow 1 code. It's something users need to be aware of, but there's no good way to fix this.
