### ISSUE TITLE
Model with multiple outputs throws error about shape of output

### ISSUE THREAD

**Issue by milongo** [tensorflow/tensorflow#38674]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Yes
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de 2.1.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: RTX 2080, 12 GB

**Describe the current behavior**

I have an ensemble of MLP's, where each ensemble outputs two values, a `mean`, and a `variance`, as shown below:
```
    def call(self, inputs, training=None, mask=None):
        mean_predictions = []
        variance_predictions = []
        for idx in range(self.num_models):
            mean_predictions.append(self.mean[idx](inputs, training=training))
            variance_predictions.append(self.variance[idx](inputs, training=training))
        mean_stack = tf.stack(mean_predictions)
        variance_stack = tf.stack(variance_predictions)
        return mean_stack, variance_stack
```

Additionally, I have a custom loss function that takes these two values and outputs a loss. In particular, the loss is negative log-likelihood of the Gaussian distribution:
```
class GaussianNLL(Loss):

    def __init__(self):
        super(GaussianNLL, self).__init__()

    def call(self, y_true, y_pred):

        mean, variance = y_pred
        variance = y_pred + 0.0001
        nll = (tf.math.log(variance) / 2 + ((y_true - mean) ** 2) / (2 * variance))
        nll = tf.math.reduce_mean(nll)
        return nll
```
And calling
```
model.compile(optimizer='adam',
                  loss=loss_fn)
history = model.fit(x_train, y_train, y_train,
                        batch_size=2048,
                        epochs=10000,
                        verbose=1,
                        validation_data=(x_val, y_val))
```
I get the following error:  `tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.
`, 
which I fixed using a slight hack: instead of unpacking the outputs, I do
``` 
mean = y_pred[0]
variance = y_pred[1] + 0.0001
```
Which yields
```
Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), for inputs ['output_1', 'output_2'] but instead got the following list of 1 arrays:... 
```
**Describe the expected behavior**`

I expect to be able to define how handle my model's multiple outputs if I have custom loss functions. 

**Standalone code to reproduce the issue**
In the following colab, the code runs fine, but you can see that `fit` function outputs multiple losses, when it should really only be one. I don't know what all the other outputs are.
I just checked, and the reason it runs on colab and not my machine is tensorflow's version. But the above still stands.
https://colab.research.google.com/drive/1EnKOiGPmKIYt5f7QvcwN8VMBLniyuqhK
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```

**Comment by ravikyram** [comment]
@milongo 

Looks like code is incomplete. Can you please help us with the colab link or simple standalone code with the supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by milongo** [comment]
@ravikyram what is incomplete about it? The code runs in colab.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2.0-rc3 and i am not seeing any issue.Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/a52b4b4de3127ff07d54282a8a589706/untitled792.ipynb).It displays multiple losses instead of showing one.Thanks!

**Comment by milongo** [comment]
Yes, why does it display multiple losses? What does each one correspond to?

**Comment by gowthamkpr** [comment]
@milongo This is expected behaviour. Please take a look at this issue where the same issue has been discussed and there is a work around discussed as well.
