### ISSUE TITLE
Feed 1 frame to 2 models in tensorflow

### ISSUE THREAD

**Issue by bosssaurav** [tensorflow/tensorflow#38686]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubnutu 16.04
- TensorFlow version (use command below): tensorflow-gpu
- Python version: 35
- CUDA/cuDNN version: 9 
- GPU model and memory: Titan

Tf version " tensorflow-gpu=1.12)

I have two tensorflow models (A.pb , B.pb ). I have two written two python codes. Both of these take same frame Input and produce output. (Currently, I run both of them in different terminals.)

Since they take same image frame as inputs... Can I do something in tensorflow like...

In 1 single python file :

    Put the both codes in 1 single file.
    Open both A.pb and B.pb models.
    Feed the same input image frame two both A.pb and B.pb parallely
    Superimpose the output of A.pb & B.pb and produce 1 single output.

Kindly help me in this regard. :)

**Comment by Saduf2019** [comment]
@bosssaurav 
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by bosssaurav** [comment]
pk
