### ISSUE TITLE
Train simple audio recognition model

### ISSUE THREAD

**Issue by rajaniyadav** [tensorflow/tensorflow#38684]
@petewarden 
I trained this model in colab and it is working in arduino for "yes" and "no" command but when I tried for "on" and "off" I am not getting output in my arduino board( I have done the necessary changes in tensorflow example code "micro_speech" ).
 Can you please suggest how to get model working for "on" and "off".

**Comment by amahendrakar** [comment]
@rajaniyadav,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by amahendrakar** [comment]
You can also share the your Colab gist with us. Select 'File' -> 'Save a copy as Github Gist', and share the link of the new window. Thanks!

**Comment by rajaniyadav** [comment]
I have train the model in colab link https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/micro_speech/train_speech_model.ipynb

with modification -  os.environ["WANTED_WORDS"] = "on,off"
tensorflow version -1.15

github gist https://gist.github.com/rajaniyadav/d031321012472f41d993aa59822dfa47

**Comment by rajaniyadav** [comment]
Why the below link is no longer accessible...
https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/micro_speech/train_speech_model.ipynb

**Comment by MeghnaNatraj** [comment]
Here is the updated link! https://colab.sandbox.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/micro_speech/train/train_micro_speech_model.ipynb

Refer to the new training document here: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/micro_speech/train

**Comment by MeghnaNatraj** [comment]
Closing the issue due to inactivity. @rajaniyadav, you can re-open this issue if you're still blocked on this issue.
