### ISSUE TITLE
I've got an error for "Build a handwritten digit classifier app with TensorFlow Lite"

### ISSUE THREAD

**Issue by aslankims** [tensorflow/tensorflow#38688]
I have done all the same way, shown in the official website.

But, I have got an error message as below.

**_Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Tensor?_**

I could not find any solution through web surfing in github and others.

Could you help me, please?

Regards,

**Comment by Saduf2019** [comment]
@aslankims 
Please provide a code snippet to reproduce the issue reported here. 
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by aslankims** [comment]
Dear Saduf2019,

My platform is given as,
------------------------
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:  as described in "https://codelabs.developers.google.com/codelabs/digit-classifier-tflite/index.html?index=..%2F..index#3.". coding in Android Studio 3.6.3
The line encountered the error is " val inputShape = interpreter?.getInputTensor(0).shape() "

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Window10
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: Galaxy. But error occurs in "build: step in Android Studio
- **TensorFlow installed from (source or binary)**: The TFlite model was built in colab online
- **TensorFlow version (use command below)**: TF2.0 
- **Python version**: 3.7
.
.
- **Exact command to reproduce**: Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Tensor?

Thanks,

**Comment by Saduf2019** [comment]
@aslankims
Please provide a simple code snippet to reproduce the issue reported here.

**Comment by aslankims** [comment]
The code in Android Studio is,


  @Throws(IOException::class)
  private fun initializeInterpreter() {
    // TODO: Load the TF Lite model from file and initialize an interpreter.

    val assetManager = context.assets
    val model = loadModelFile(assetManager, "mnist.tflite")

    // TODO: Read the model input shape from model file.

    _val inputShape = interpreter?.getInputTensor(0).shape()_
    inputImageWidth = inputShape[1]
    inputImageHeight = inputShape[2]
    modelInputSize = FLOAT_TYPE_SIZE * inputImageWidth * inputImageHeight * PIXEL_SIZE

    // Finish interpreter initialization
    this.interpreter = interpreter

    isInitialized = true
    Log.d(TAG, "Initialized TFLite interpreter.")
  }

The error that,
"Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Tensor?"
occurs on the line of     _val inputShape = interpreter?.getInputTensor(0).shape()_

Thanks

**Comment by lintian06** [comment]
Hi @aslankims, please check the full version of demo: 

https://github.com/tensorflow/examples/blob/4d3a5d2b3a8fa9eeba9789544b10aaa1db3b71ac/lite/codelabs/digit_classifier/android/finish/app/src/main/java/org/tensorflow/lite/codelabs/digitclassifier/DigitClassifier.kt#L69

**Comment by lintian06** [comment]
As this app has been built and tested in our regular testing pipeline, the doc https://codelabs.developers.google.com/codelabs/digit-classifier-tflite/index.html?index=..%2F..index#3. is as same as the app, I'll close the bug.
