### ISSUE TITLE
NotImplementedError: 

### ISSUE THREAD

**Issue by mobassir94** [tensorflow/tensorflow#38683]
i am using the code below : 

```
def build_model(transformer, loss='binary_crossentropy', max_len=512):
    input_word_ids = Input(shape=(max_len,), dtype=tf.int32, name="input_word_ids")
    sequence_output = transformer(input_word_ids)[0]
    cls_token = sequence_output[:, 0, :]
    x = tf.keras.layers.Dropout(0.3)(cls_token)
    out = Dense(1, activation='sigmoid')(x)
    
    model = Model(inputs=input_word_ids, outputs=out)
    model.compile(Adam(lr=3e-5), loss=loss, metrics=[tf.keras.metrics.AUC()])
    
    return model


%%time
with strategy.scope():
    transformer_layer = transformers.TFXLMRobertaModel.from_pretrained(MODEL)
    model = build_model(transformer_layer,loss='binary_crossentropy', max_len=maxlen)
model.summary()


def build_lrfn(lr_start=0.000001, lr_max=0.000002, 
               lr_min=0.0000001, lr_rampup_epochs=7, 
               lr_sustain_epochs=0, lr_exp_decay=.87):
    lr_max = lr_max * strategy.num_replicas_in_sync

    def lrfn(epoch):
        if epoch < lr_rampup_epochs:
            lr = (lr_max - lr_start) / lr_rampup_epochs * epoch + lr_start
        elif epoch < lr_rampup_epochs + lr_sustain_epochs:
            lr = lr_max
        else:
            lr = (lr_max - lr_min) * lr_exp_decay**(epoch - lr_rampup_epochs - lr_sustain_epochs) + lr_min
        return lr
    
    return lrfn


model_path = 'jigsawMultilingual.hdf5'
model_path1 = '/kaggle/working/jigsawMultilingual.hdf5'


from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, LearningRateScheduler

checkpoint = ModelCheckpoint(model_path, monitor='val_loss', mode='min', save_best_only=True)
es = EarlyStopping(monitor='val_loss', mode='min', patience=2, 
                   restore_best_weights=True, verbose=1)
lr_callback = LearningRateScheduler(lrfn, verbose=1)

callback_list = [checkpoint, es, lr_callback]


%%time
N_STEPS = x_train.shape[0] // BATCH_SIZE
EPOCHS = 2
train_history = model.fit(
    train_dataset,
    steps_per_epoch=N_STEPS,
    validation_data=valid_dataset,
    callbacks=callback_list,
    epochs=EPOCHS
)
```

and i am getting NotImplementedError after 1st epoch,here is the notebook : https://www.kaggle.com/mobassir/understanding-cross-lingual-models?scriptVersionId=32280074

i am unable to save checkpoint, for me  monitor='val_loss' throwing me NotImplementedError
i tried monitor='val_acc'  and monitor='val_accuracy'  and none of them saving weights for me,where am i making mistakes?

**Comment by amahendrakar** [comment]
In order to expedite the trouble-shooting process, could you please provide a minimal code sample to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by mihaimaruseac** [comment]
Please fill in issue template and try to minimize the code

**Comment by mobassir94** [comment]
Full code here :
https://www.kaggle.com/mobassir/understanding-cross-lingual-models

From cell 8 till end of the jupyter notebook

**Comment by dimitreOliveira** [comment]
It seems that is not possible to save the complete transformer model, this might work if you add "save_weights_only=True", and save only the weights from the model.

**Comment by amahendrakar** [comment]
@mobassir94,
Could you please try sharing a minimal reproducible code, I am constantly facing out of memory error on running the code.

Also, please check @dimitreOliveira's comment and let us know if it helps? Thanks!

**Comment by mobassir94** [comment]
@amahendrakar i don't really understand what do you  mean by sharing minimal reproducible code? you have full code here : https://www.kaggle.com/mobassir/understanding-cross-lingual-models after 8th cell,till end
i am seeking answer for saving full weight in this issue.

maybe for minimal reproducible you only need this part? : 


from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, LearningRateScheduler

checkpoint = ModelCheckpoint(model_path, monitor='val_loss', mode='min', save_best_only=True)
es = EarlyStopping(monitor='val_loss', mode='min', patience=2, 
                   restore_best_weights=True, verbose=1)

callback_list = [checkpoint, es]

N_STEPS = x_train.shape[0] // BATCH_SIZE
EPOCHS = 2
train_history = model.fit(
    train_dataset,
    steps_per_epoch=N_STEPS,
    validation_data=valid_dataset,
    callbacks=callback_list,
    epochs=EPOCHS
)

**Comment by mihaimaruseac** [comment]
@mobassir94 Minimal reproducible code is code that can be run independently (i.e., does not require datasets, does not require running a jupyter notebook, etc.) and shows the error. No line can be removed anymore from that code while still showing the same error.

Compare

```python
def not_minimal(x, y):
  z = x + y
  t  = 2 * z
  if x < y:
    raise Exception("Bug here")

not_minimal(0, 42)
```

with

```
def minimal(x, y):
  if x < y:
    raise Exception("Bug here")

minimal(0, 42)
```

Of course, you don't edit TF's code, but the code you are running should be minimized.

Why do we ask for minimized code? So that we can use tooling to quickly factor in where the change comes from and to create regression test once issue is fixed to prevent it from happening again.

**Comment by mobassir94** [comment]
@mihaimaruseac  sorry i don't know how to minimize that code of mine without using dataset or without running at all,because the error i get is it comes after running on a dataset for exactly  1 epoch,error comes after 1 epoch and i am here asking to minimize the code that can run without data and notebook,thanks for your immense support and help

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
