### ISSUE TITLE
libcuda.so.1 is missing with conda env tf-gpu

### ISSUE THREAD

**Issue by Arktius** [tensorflow/tensorflow#38685]
I get the following errors:

```
2020-04-19 05:56:24.050072: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-04-19 05:56:24.050125: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-04-19 05:56:24.050149: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
2020-04-19 05:56:24.050476: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-04-19 05:56:24.066026: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2199900000 Hz
2020-04-19 05:56:24.068548: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x558e75a5b2c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-19 05:56:24.068591: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
```
when I execute
```
 trainds = tf.data.Dataset.from_tensor_slices((helper.trainx,helper.trainm,helper.trainy)).batch(setup['BatchSize'])
```
Tensorflow cannot find the file libcuda.so.1.

I get this error in a Docker Container which uses miniconda and the tensorflow-gpu environment.
```
FROM continuumio/miniconda3
RUN conda create -n tf-gpu tensorflow-gpu
```
I don't get the error on my local machine with the same code.

As far as I understood, conda should automatically install cuda and its libraries.

When I search for the missing file I get an empty line. `find -name "libcuda.so.1"`
Other versions of libcuda.so. can't be found either. Even `*cuda*` couldn't be found. It seems to be that cuda was entirely skipped during the installation. 

nvidia-smi returns this:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: N/A      |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-SXM2...  Off  | 00000000:89:00.0 Off |                    0 |
| N/A   30C    P0    31W / 300W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**System information**
```
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20)
[GCC 7.3.0] on linux
```
- TensorFlow version: 2.1.0
- Python version: 3.7.6
- GPU model and memory: P100 / 16 GB

Additional information:
```
print(tf.test.is_gpu_available())             # False
print(tf.config.list_physical_devices('GPU')) # []
```

**Comment by ravikyram** [comment]
This issue is more suitable for anaconda-issues repo. Please post it on anaconda-issues repo from [here.](https://github.com/ContinuumIO/anaconda-issues/issues).Thanks!

**Comment by Arktius** [comment]
https://github.com/ContinuumIO/anaconda-issues/issues/11743

**Comment by ravikyram** [comment]
@Arktius 

Can we track with that issue  in ContinuumIO/anaconda-issues#11743

and close this one. It will help us to follow easily. Please let us know. Thanks!

**Comment by Arktius** [comment]
I've solved the problem by setting system variables to recognize the GPU. The error was actually 
`2020-04-19 05:56:24.050125: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)` .

In the dockerfile:
`ENV NVIDIA_VISIBLE_DEVICES all`
`ENV NVIDIA_DRIVER_CAPABILITIES compute,utility`
[NVIDIA](https://github.com/NVIDIA/nvidia-docker/wiki/Usage)

**Comment by pjgoodall** [comment]
I am having a very similar problem on Ubuntu 20.04/conda/jupyter with Julia accessing the GPU.
I can access the library from the raw repl, but not from the IJUlia kernel within jupyter installed using conda.

see [gpu-workshop-notebook-could-not-load-library-libcuda-so-1](https://discourse.julialang.org/t/juliacon21-gpu-workshop-notebook-could-not-load-library-libcuda-so-1/65014/11?u=banksiaboy) on discourse.julia.lang.org
