### ISSUE TITLE
Tensorflow Lite iOS opengl delegate

### ISSUE THREAD

**Issue by brucechou1983** [tensorflow/tensorflow#38696]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.2.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Metal delegate works perfectly. But in some cases, I am forced to use opengles 3.0 as the render pipeline because of essential external libraries. It will then be great to have opengl delegate in iOS so users could bind SSBO to tensors.

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
iOS developers who can't use Metal render pipeline and want high inference performance.

**Any Other info.**

**Comment by yyoon** [comment]
Hi @brucechou1983, sorry for my late response.
To understand your question clearly, are you saying that when you are using OpenGL as the rendering pipeline in your app, you can't use Metal delegate in the same app?

**Comment by brucechou1983** [comment]
@yyoon Sorry that I didn't explain the question well. Using Metal delegate with OpenGL rendering pipeline works. The problem is we have to copy input and output data back and forth rather than exchanging the ownership of the data.

As you can see in MediaPipe [tflite inference calculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/tflite_inference_calculator.cc#L495), memcpy() is required in every single inference. When I opened this issue, I thought if the kernel is written is OpenGL I can just bind the buffers to tensors.

However, I realized that OpenGL kernels in TFLite are generated as the form of compute shaders, which are not supported in OpenGL ES 3.0. Since iOS devices generally have faster GPU, I could live with current solution.

**Comment by yyoon** [comment]
Thanks for the clarification!
