### ISSUE TITLE
Does `tf.constant()` waste memory? What is the alternative?

### ISSUE THREAD

**Issue by laghaout** [tensorflow/tensorflow#38693]
This is about [this tutorial](https://www.tensorflow.org/guide/data) on input pipelines, and in particular the following note under "Reading input data" > "Consuming NumPy arrays":

> Note: The above code snippet will embed the features and labels arrays in your TensorFlow graph as tf.constant() operations. This works well for a small dataset, but wastes memory---because the contents of the array will be copied multiple times---and can run into the 2GB limit for the tf.GraphDef protocol buffer.

Could we have a slightly more detailed justification for this note, namely as to why `tf.data.Dataset.from_tensor_slices()` is suboptimal in this case. In particular:

1. In which way are the contents of the array copied multiple times?
2. What is the alternative to that code if we don't want to run into the 2GB limit? What is the best practice in general?

**Comment by mihaimaruseac** [comment]
This is a question better suited for StackOverflow, since it is not about an implementation bug/feature request.

**Comment by laghaout** [comment]
This issue wasn't raised as a bug/feature request but rather as pertaining to the documentation, hence the `type:docs` label. It refers to a tutorial published by TensorFlow which fails to explain why `tf.constant()` wastes memory.

**Comment by mihaimaruseac** [comment]
Apologies. Reopening

**Comment by msmurgui** [comment]
Hi! Any news on this?

**Comment by tagomatech** [comment]
End of November 2023, Tensorflow documentation in the section [Reading input data](https://www.tensorflow.org/guide/data#reading_input_data) still reads the warning:

> Note: The above code snippet will embed the features and labels arrays in your TensorFlow graph as [tf.constant()](https://www.tensorflow.org/api_docs/python/tf/constant) operations. This works well for a small dataset, but wastes memory---because the contents of the array will be copied multiple times---and can run into the 2GB limit for the tf.GraphDef protocol buffer.

And, just like original poster back in early 2020, I would been keen to know more about that sub-optimality and what are other roads to go down.

Thank you
@tagomatech
