### ISSUE TITLE
Run "bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu", got "No such file or directory"

### ISSUE THREAD

**Issue by JohnnyY8** [tensorflow/tensorflow#3869]
Hi everyone:
### Environment info
Ubuntu 14.04 LTS

Installed version of CUDA and cuDNN: 
CUDA 7.5, cuDNN v5.1
![image](https://cloud.githubusercontent.com/assets/12611573/17721639/5e9f7f32-645e-11e6-8ba6-ec7f37b1e139.png)
I try to build tensorflow with CUDA 7.5, cuDNN v5.1 and bazel-0.3.1-installer-linux-x86_64.sh. When I run 'bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer', it seems good. But when I run 'bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu', I got the error 'No such file or directory'. So I find the tutorials_example_trainer in following path:
![image](https://cloud.githubusercontent.com/assets/12611573/17721729/13e19b5a-645f-11e6-91e7-73667ea0905d.png)
I tried to run '/home/caffe/.cache/bazel/_bazel_caffe/5954a53028453a61b395a19127f3e1cf/execroot/tensorflow/bazel-out/local_linux-opt/bin/tensorflow/cc/tutorials_example_trainer.runfiles/org_tensorflow/tensorflow/cc/tutorials_example_trainer --use_gpu' and got the result like following:
![image](https://cloud.githubusercontent.com/assets/12611573/17721744/349e1ba2-645f-11e6-80a8-9746ac31a43a.png)
It seems ok, but I do not know why cann't I run 'bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu'.
Can anyone help me ?
Thanks!

**Comment by suiyuan2009** [comment]
I can't reproduce, does this file `bazel-bin/tensorflow/cc/tutorials_example_trainer` exist in your tensorflow root directory?

**Comment by JohnnyY8** [comment]
@suiyuan2009 It does not exist. I do not know why. I am still checking out something I ignored.

**Comment by suiyuan2009** [comment]
@JohnnyY8 have you tried `bazel clean` and `./configure` then rebuilding?

**Comment by JohnnyY8** [comment]
@suiyuan2009 OK, I will try it now.

**Comment by JohnnyY8** [comment]
@suiyuan2009 
I got this:
![image](https://cloud.githubusercontent.com/assets/12611573/17729306/218e5004-6496-11e6-9291-01c65b46820f.png)
I think this is the problem, but when I use "sudo", I got "sudo: bazel: command not found". So if I can run bazel with sudo, it may works, right?

**Comment by suiyuan2009** [comment]
@JohnnyY8 run `which bazel`, and use full bazel bin file path instead `bazel`

**Comment by JohnnyY8** [comment]
@suiyuan2009 I change the authority of tensorflow file, and it works. Thanks for you help!
BTW, take the authority into account, do people usually git clone tensorflow under the $HOME path or somewhere?

**Comment by suiyuan2009** [comment]
why bazel need sudo authority?

**Comment by JohnnyY8** [comment]
@suiyuan2009 Maybe because I git clone the tensorflow under "/home/common/" path which is made by myself. This path belongs to root user.

**Comment by prb12** [comment]
This looks like a simple Unix permissions issue, and not a TensorFlow bug.  Please reopen if this is not the case.

**Comment by kushNumberTheory** [comment]
I am having the same issue. Steps i followed
1. bazel clean
2. ./configure on cpu
3. bazel build --config op gives t:
```
kush@kush-Lenovo-B40-80:~/machine_learning/deeplearning/tensorflow$ bazel build --config=op
Warning: ignoring LD_PRELOAD in environment.
WARNING: Config values are not defined in any .rc file: op
INFO: Found 0 targets...
INFO: Elapsed time: 2.365s, Critical Path: 0.03s

```
4. Now when i try to run 
`bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg`
```
kush@kush-Lenovo-B40-80:~/machine_learning/deeplearning/tensorflow$ bazel-bin/tensorflow/tools/pip_package/build_pip_package
bash: bazel-bin/tensorflow/tools/pip_package/build_pip_package: No such file or directory
```

But then i tried sudo it gives 
`sudo: bazel-bin/tensorflow/tools/pip_package/build_pip_package: command not found
`

bazel is installed in my system. i have checked it. 
Can anyone help me on this?
