### ISSUE TITLE
keras.layers.Add() uses 'tf_op_layer_add', which can not be renamed

### ISSUE THREAD

**Issue by CXYCarson** [tensorflow/tensorflow#38695]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): 
pip
- TensorFlow version (use command below): 
2.1
- Python version: 
3.6.9

**Describe the current behavior**

I currently have a trained model and I want to add the output of an intermediate layer with a numpy array that I have. I first converted the numpy array to a tensor using `tf.keras.backend.constant`, and then I used `tf.keras.layers.Add()` to sum them up. 

But I got the error: `The name "tf_op_layer_add" is used 2 times in the model. All layer names should be unique`. Because there exists another add operation in the model. So I tried to name this add layer, and I got this error: `Can't set the attribute "name", likely because it conflicts with an existing read-only @property of the object. Please choose a different name`.

Normally, `tf.keras.layers.Add()` should be of type `<tensorflow.python.keras.layers.merge.Add>`, but in my case, it became into `<tensorflow.python.keras.engine.base_layer.TensorFlowOpLayer>`, which does not allow me to change its name.

I simply want to change the name of that `tf.keras.layers.Add()` layer, is there a way I can do that or another way around? Thanks!

**Standalone code to reproduce the issue**

Here's a way to reproduce the error. You'll see that `tf.keras.layers.Add()` uses tensorflow operation layer which can not be named.

```
bias = np.ones((32, 32, 3))
bias = tf.keras.backend.constant(bias)
bias = keras.backend.reshape(bias, [-1,32,32,3])
               
inputs = tf.keras.Input(shape=(32, 32, 3))
x = tf.keras.layers.Conv2D(filters=3, kernel_size=(3, 3),padding = 'same')(inputs)
x = tf.keras.layers.Add(name = 'add_1')([x, bias])
model = tf.keras.Model(inputs, x)
model.summary()
add_layer = model.get_layer('tf_op_layer_add')
add_layer.name = 'add_1'
```

**Comment by Saduf2019** [comment]
@CXYCarson 
can you please refer to these links and let us know if it helps:
[link1](https://stackoverflow.com/questions/53596571/error-with-keras-inceptionv3-base-model-get-layercustom-valueerror-no-suc) [link2](https://www.tensorflow.org/guide/keras/custom_layers_and_models)

**Comment by CXYCarson** [comment]
Those two links helped, thanks a lot!
