### ISSUE TITLE
[1.14] get_graph_def_from_url_tarball more explicit exception when unfinished donwload.

### ISSUE THREAD

**Issue by hzlmn** [tensorflow/tensorflow#38700]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): -
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Catalin 10.15.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: - 
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6.5
- Bazel version (if compiling from source): - 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: - 
- GPU model and memory: - 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Hi, currently in version `1.14.0` using `contrib.gan` package. When using `get_graph_def_from_url_tarball` internally by default it fetch file from remote, however when such file name presented on disk or you stopped download in progress after you restart it you will get `EOFError: Compressed file ended before the end-of-stream marker was reached`. This is a bit confusion and may take some time to explore reason. It would be better if `get_graph_def_from_url_tarball` raised more verbose exception when it can find file with such name here 
https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/contrib/gan/python/eval/python/classifier_metrics_impl.py#L212-L223

If you consider it reasonable, i can work on PR.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
