### ISSUE TITLE
libstdc++.so.6: version `GLIBCXX_3.4.21' not found 

### ISSUE THREAD

**Issue by soporteCluster** [tensorflow/tensorflow#38718]
OS: Centos 6.2
Tensorflow installed from source
Tensorflow version: 2.1.0
Python version: 3.5
Bazel version: 0.28
GCC version: 6.3.0
GPU support: NO.

When i tried to compile tensorflow from source i get the following error:

COMMAND: bazel build //tensorflow/tools/pip_package:build_pip_package

ERROR: /tmp/tensor/tensorflow-2.1.0/tensorflow/lite/python/optimize/BUILD:29:1: SWIGing tensorflow/lite/python/optimize/calibration_wrapper.i failed (Exit 1)
/root/.cache/bazel/_bazel_root/install/aa7e5eb7da84c1e7540941e7c9d19262/_embedded_binaries/process-wrapper: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/.cache/bazel/_bazel_root/install/aa7e5eb7da84c1e7540941e7c9d19262/_embedded_binaries/process-wrapper)
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 58.251s, Critical Path: 14.93s
INFO: 231 processes: 231 local.
FAILED: Build did NOT complete successfully

I tried to add the path of the libraries to the LD_LIBRARY_PATH but it always try to find it in /usr/lib64. 

Also i tried with the following command:

BAZEL_LINKOPTS=-static-libstdc++ BAZEL_LINKLIBS=-l%:libstdc++.a bazel build //tensorflow/tools/pip_package:build_pip_package

But the issue is still there.

The directory where the library is installed is:  /share/apps/gcc-6.3.0/lib64/libstdc++.so.6

Thanks.

**Comment by Saduf2019** [comment]
@soporteCluster 
please refer tot his link and let us know if it helps: [link1](https://github.com/tensorflow/tensorflow/issues/20341) [link2](https://github.com/bazelbuild/bazel/issues/5348#issuecomment-397494217)

**Comment by soporteCluster** [comment]
Hi,
Thanks for the answer. I need a way to change the default path where the compilation is trying to find libstdc++.so.6. The version that i have in /usr/lib64/libstdc++.so.6 is too old so i have installed a new version in /share/apps/gcc-6.3.0/lib64/libstdc++.so.6.
Thanks.

**Comment by Saduf2019** [comment]
@soporteCluster 
please refer to these links and let me know if it helps:
[link1](https://github.com/mlapin/libsdca/issues/1) [link2](https://stackoverflow.com/questions/17177059/overriding-libstdc-search-path-at-runtime-on-linux) [link3](https://unix.stackexchange.com/questions/134266/how-to-specify-the-libstdc-so-6-to-use)

**Comment by soporteCluster** [comment]
I can't change the link of the library in /usr/lib64 because it is a cluster server and this could be worse than this problem. I have already set the LD_LIBRARY_PATH but bazel doesn't look around that variable when it compile.
I need a way to say to bazel to find that library in another different path than /usr/lib64.

**Comment by Saduf2019** [comment]
@soporteCluster 
Can you please refer to this link and let us kno if it helps:
[link1](https://github.com/bazelbuild/bazel/issues/590#issuecomment-165811380)
[link2](https://stackoverflow.com/questions/43220067/bazel-link-so-libraries-located-in-a-completely-different-very-remote-folder)
[link3](https://github.com/tensorflow/tensorflow/issues/33108)

**Comment by jakublipinski** [comment]
@soporteCluster did you manage to solve your issue? I'm facing exactly same problem while trying to compile Tensorflow on SLURM cluster.

**Comment by soporteCluster** [comment]
> @soporteCluster did you manage to solve your issue? I'm facing exactly same problem while trying to compile Tensorflow on SLURM cluster.

Hi,

I have tried with the following link:
https://github.com/bazelbuild/bazel/issues/4137#issuecomment-610518610
It appears to pass that issue but now i have another problem:

ERROR: /tmp/tensor/tensorflow-2.1.0/tensorflow/lite/experimental/microfrontend/BUILD:44:1: Linking of rule '//tensorflow/lite/experimental/microfrontend:python/ops/_audio_microfrontend_op.so' failed (Exit 1)
/usr/local/bin/ld: bazel-out/k8-py2-opt/bin/_solib_k8/_U_S_Stensorflow_Slite_Sexperimental_Smicrofrontend_Cpython_Sops_S_Uaudio_Umicrofrontend_Uop.so___Utensorflow/libtensorflow_framework.so.2: _edata: invalid version 21 (max 2)
/usr/local/bin/ld: bazel-out/k8-py2-opt/bin/_solib_k8/_U_S_Stensorflow_Slite_Sexperimental_Smicrofrontend_Cpython_Sops_S_Uaudio_Umicrofrontend_Uop.so___Utensorflow/libtensorflow_framework.so.2: error adding symbols: bad value
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 10663.568s, Critical Path: 412.81s
INFO: 18583 processes: 18583 local.
FAILED: Build did NOT complete successfully

And i don't know how to fix it.

**Comment by soporteCluster** [comment]
Hi,
I have already finished the installation. The error that I had written above I have resolved it by installing binutils-2.34.
So what you have to do is install bazel-0.28 and compile it bazel with:
env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" BAZEL_LINKOPTS=-static-libstdc++:-static-libgcc BAZEL_LINKLIBS=-l%:libstdc++.a:-lm  bash ./compile.sh
Install binutils-2.34.
Then run the configure from TensorFlow-2.1.0 inside it. 
Build it with:
env BAZEL_LINKOPTS=-static-libstdc++:-static-libgcc BAZEL_LINKLIBS=-l%:libstdc++.a:-lm BAZEL_CXXOPTS=-std=gnu++0x bazel build //tensorflow/tools/pip_package:build_pip_package

**Comment by Saduf2019** [comment]
@@soporteCluster 
As the issue raised is resolved , please confirm if we may move this to closed status, in case of any new issues please raise a new ticket.

**Comment by soporteCluster** [comment]
Yes,
I will close it.
Thanks
