### ISSUE TITLE
Online documentation missing python docs

### ISSUE THREAD

**Issue by phemmer** [tensorflow/tensorflow#38713]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/keras/experimental/CosineDecay
https://www.tensorflow.org/api_docs/python/tf/keras/experimental/CosineDecayRestarts
https://www.tensorflow.org/api_docs/python/tf/keras/experimental/LinearCosineDecay
https://www.tensorflow.org/api_docs/python/tf/keras/experimental/NoisyLinearCosineDecay
https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/schedules/ExponentialDecay
https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/schedules/InverseTimeDecay
https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/schedules/PiecewiseConstantDecay
https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/schedules/PolynomialDecay

May be present on others, but I'm not going to scour the web site looking.

## Description of issue (what needs changing):
The general documentation of these classes does not show up on the web site. This leads to confusion as many of them have argument documentation containing statements such as *"See the decay computation above"*, when there is no documented computation above.

Instead you have to open the source code to see the documentation that is mentioned.

Here's an example:
![image](https://user-images.githubusercontent.com/1826947/79771096-4f2dea00-82fc-11ea-8373-ec3572b00f3b.png)
And here's the missing documentation:
![image](https://user-images.githubusercontent.com/1826947/79771213-77b5e400-82fc-11ea-9d0d-2dc9efc02232.png)

**Comment by rohanreddych** [comment]
Check the nightly version, it has what you want.

**Comment by phemmer** [comment]
Ah, ok. Yeah, looks like this was fixed by a3d8081

Thanks. Will close
