### ISSUE TITLE
Training Loaded Models is MUCH slower

### ISSUE THREAD

**Issue by acegilz** [tensorflow/tensorflow#38710]
**System information**
Windows 7
Python 3.8
Tensorflow 2.1

**Describe the current behaviour**

When I create a model "from scratch" and train it, with some configs, and data. Each epoch takes around 3 minutes to terminate.

If I stop the training after the first epoch, and load the model to continue training (same data, same configs) instead of taking the 3 minutes, every epoch takes around 12 minutes (4x) to conclude.

This is how I am creating the model:

```python

model = Sequential()
model.add(LSTM(128, input_shape=(train_x.shape[1:]), return_sequences=True))
model.add(Dropout(0.3))
model.add(BatchNormalization())


model.add(LSTM(128, return_sequences=True))
model.add(Dropout(0.3))
model.add(BatchNormalization())

model.add(LSTM(128))
model.add(Dropout(0.2))
model.add(BatchNormalization())

model.add(Dense(32, activation='relu'))
model.add(Dropout(0.3))

model.add(Dense(2, activation='softmax'))


opt = tf.keras.optimizers.Adam(lr=0.001, decay=1e-6)

filepath = "tf/checkpoints/RNN_Final-{epoch:02d}-{val_accuracy:.3f}.hdf5"  # unique file name that will include the epoch and the validation acc for that epoch
checkpoint = tf.keras.callbacks.ModelCheckpoint(filepath, verbose=1, monitor='val_accuracy', save_best_only=True, mode='max') # saves only the best ones

history = model.fit(
    train_x, train_y,
    batch_size=BATCH_SIZE,
    epochs=EPOCHS,
    validation_data=(validation_x, validation_y),
    callbacks=[checkpoint,tensorboard],
)
```

After the first Epoch, I am running the code like this:

```python

model = load_model("mymodel_1EPOCH. hdf5")

history = model.fit(
    train_x, train_y,
    batch_size=BATCH_SIZE,
    epochs=EPOCHS,
    initial_epoch = 1,
    validation_data=(validation_x, validation_y),
    callbacks=[checkpoint,tensorboard],
)
```

**Describe the expected behaviour**
I was expecting the loaded model, to run at the same speed as the new model. I am saving the models in _.hdf5_. Should I use any other file type?

**Comment by ravikyram** [comment]
@acegilz 

Looks like code is incomplete. Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!
