### ISSUE TITLE
Kernel dies in Anaconda 

### ISSUE THREAD

**Issue by istvan1000** [tensorflow/tensorflow#38721]
Good morning
I'm still have the coronavirus in my set-up:

MacPro (older), HighSierra -> Anaconda (the last version) -> select a Python (3,7) code which on other Macs/Anaconda worked -> RUN -> Kernel dies with the first Import command.

I tried as here suggested:
- re-istalled NumPy, directly in Anaconda and also with pip, nothing
- hided NumPy some cells lower, nothing
- installed some libraries here suggested, nothing

I think it must be an Installation issue, but don't know where the problems could be, thanks for help

**Comment by amahendrakar** [comment]
@istvan1000,

Is this issue related to TensorFlow? 

If not please get in touch with Anaconda support team, they will be able to help you in this case. Thanks!

**Comment by istvan1000** [comment]
Well TensoFlow is in the list to import, but the notebook stops earlier.
Anyway, is here in Github an Anaconda support group?

**Comment by amahendrakar** [comment]
@istvan1000,
The Anaconda Community [support page](https://www.anaconda.com/anaconda-community/) points to the [conda Github repo](https://github.com/conda/conda). Please raise an issue in that repo, they should be able to help you in this case. Thanks!

**Comment by istvan1000** [comment]
Thank you
