### ISSUE TITLE
Casting a string tensor to a list of string

### ISSUE THREAD

**Issue by Ceceu** [tensorflow/tensorflow#38725]
I couldn't find an approach to casting a string tensor to a list of string. 
For instance, if someone has the following `sample_string_tensor`:

```python
import tensorflow as tf

batch_size = 4
sample_string_tensor = tf.convert_to_tensor(["sãmple utf-8 stríng - " + str(i) for i in range(n_strings)])
sample_string_tensor
# <tf.Tensor: shape=(4,), dtype=string, numpy=
# array([b's\xc3\xa3mple utf-8 str\xc3\xadng - 0',
#        b's\xc3\xa3mple utf-8 str\xc3\xadng - 1',
#        b's\xc3\xa3mple utf-8 str\xc3\xadng - 2',
#        b's\xc3\xa3mple utf-8 str\xc3\xadng - 3'], dtype=object)>
```
how to cast to list of string below?
```python
['sãmple utf-8 stríng - 0',
 'sãmple utf-8 stríng - 1',
 'sãmple utf-8 stríng - 2',
 'sãmple utf-8 stríng - 3']

```
Note there are some no `ascii` character.

**Comment by amahendrakar** [comment]
@Ceceu,
You can use `sample_string_tensor.numpy()` to extract the value from the tensor. Please check [this gist](https://colab.research.google.com/gist/amahendrakar/eacae34045839d34406beb71cb56ffaa/38725.ipynb) for reference.

Also, this question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is a larger community that reads questions there.

**Comment by Ceceu** [comment]
Thank you @amahendrakar, but that is not the answer. Note when you use `sample_string_tensor.numpy()` you actually have an array of byte strings `(b'example string')` which in turn, have to be decoded. A lot of tokenizers requires a string or a list of strings, that's the reason for my issue.

Therefore, I am looking for an approach to decode the array of byte strings from a tensor into a batch of strings. As I have a large dataset to tokenize, this must be done in a vectorized manner  through the [map function](https://www.tensorflow.org/api_docs/python/tf/data/Dataset?version=nightly#map).

I already submitted a question on StackOverflow, but as no one has been able to answer so far, I thought it best to ask for help directly from those who maintain the Tensorflow.

**Comment by ymodak** [comment]
May be you can use [`tf.compat.as_str_any()`](https://www.tensorflow.org/api_docs/python/tf/compat/as_str_any) function to this?
Take a look at a toy example:
```python
s = tf.convert_to_tensor('my_string')
print(type(s.numpy()))
print(type(tf.compat.as_str_any(s)))
```
output:
```python
<class 'bytes'>
<class 'str'>
```

**Comment by chrismaliszewski** [comment]
@ymodak, I don't know why your answer was downvoted since it's correct! It returns the value of a tensor as a string.

The answer to the preliminary question then is:
```
n_strings = 4
sample_string_tensor = tf.convert_to_tensor(["sãmple utf-8 stríng - " + str(i) for i in range(n_strings)])
sample_string_tensor
list_of_sample_strings = [tf.compat.as_str_any(tensor.numpy()) for tensor in sample_string_tensor] 
list_of_sample_strings
```

**Comment by chuanwen** [comment]
A simple way:

```
>>> list_of_sample_strings = [x.numpy().decode() for x in sample_string_tensor]

['sãmple utf-8 stríng - 0',
 'sãmple utf-8 stríng - 1',
 'sãmple utf-8 stríng - 2']

```
