### ISSUE TITLE
ModelCheckpoint results in Input 0 of layer is incompatible with the layer

### ISSUE THREAD

**Issue by david-wb** [tensorflow/tensorflow#38729]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.4
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.1
- GPU model and memory: NVIDIA GTX 970

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Saving a model using keras ModelCheckpoint callback results in the following error:
```
ValueError: Input 0 of layer cls_outputs is incompatible with the layer: its rank is undefined, but the layer requires a defined rank.
```
**Describe the expected behavior**
Should save the model without errors.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
https://colab.research.google.com/drive/1Bf6EhjmnjzsZQUoiGAi1XVxjrFOPa2Cp

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
The ModelCheckpoint callback works when using `save_weights_only=True`, but I need to save the whole model for deployment to AI platform.

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.1.0 , 2.2.0-rc3 and was able to reproduce the issue.Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/4802ad8f173bcc0eb3b0a2bc56523235/untitled794.ipynb)Thanks!

**Comment by ravikyram** [comment]
@david-wb 

I have tried in colab with TF nightly version(`2.4.0-dev20200916`) and i am not seeing any issue.Please, find the gist [here.](https://colab.research.google.com/gist/ravikyram/3a5b7a8ab828f6e845a207bccd69f73e/untitled373.ipynb).PLease, verify once and close the issue.Thanks!

**Comment by david-wb** [comment]
Verified thank you.
