### ISSUE TITLE
'bazel' --batch mode deprecated issue for Fedora

### ISSUE THREAD

**Issue by drezap** [tensorflow/tensorflow#38736]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Fedora 29
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version: v2.1.0-rc2-17-ge5bf8de
- Python version: 3.7.6
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 0.21.0 and the latest.
- GCC/Compiler version (if compiling from source): N/A, command?
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
Can't compile from source due to `bazel` issue. Tried switching to recommended version of bazel, still unsuccessful.

This happened when trying to modify the source and build for the patch suggested here:

`https://github.com/tensorflow/tensorflow/issues/31945`

**Provide the exact sequence of commands / steps that you executed before running into the problem**

from tensorflow directory:

`python configure.py`

**Any other info / logs**
`INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=190
INFO: Reading rc options for 'version' from /home/andre/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
ERROR: Unrecognized option: --experimental_repo_remote_exec
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: 0e4f21d3-187f-4d35-8f91-27a3ea88e768
Traceback (most recent call last):
  File "configure.py", line 1551, in <module>
    main()
  File "configure.py", line 1368, in main
    _TF_MAX_BAZEL_VERSION)
  File "configure.py", line 483, in check_bazel_version
    ['bazel', '--batch', '--bazelrc=/dev/null', 'version'])
  File "configure.py", line 159, in run_shell
    output = subprocess.check_output(cmd, stderr=stderr)
  File "/usr/lib64/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bazel', '--batch', '--bazelrc=/dev/null', 'version']' returned non-zero exit status 2.
`

**Comment by ymodak** [comment]
Can you try with newer bazel version like 2.0.0 or higher?
See,
https://github.com/tensorflow/tensorflow/blob/ced65fa9b07b8362fc716a7086bc7a9a25416262/configure.py#L52

**Comment by drezap** [comment]
I had to use bazel 3.0. configure file wasn't happy with 3.1. Nor earlier version. Thanks!

**Comment by drezap** [comment]
Just to be clear I did check out the config file after the build issues, and I did have a bazel version that fell within constants MAX and MIX bazel version, and it would still throw that issue. If I remembered, I would tell you.
