### ISSUE TITLE
Build Tensorflow with triSYCL?

### ISSUE THREAD

**Issue by jiapei100** [tensorflow/tensorflow#38737]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.4
- TensorFlow installed from (source or binary): build from source 
- TensorFlow version: 2.1.0
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 3.0.0 
- GCC/Compiler version (if compiling from source): gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
- CUDA/cuDNN version: [triSYCL](https://github.com/triSYCL/triSYCL)

**Describe the problem**

**Bazel 3.0.0** has been installed onto my **aarch64** successfully:

```console
$ bazel version
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Build label: 3.0.0- (@non-git)
Build target: bazel-out/aarch64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Apr 20 22:21:14 2020 (1587421274)
Build timestamp: 1587421274
Build timestamp as int: 1587421274
```

However, when I tried to build Tensorflow with SYCL enabled, I got the following error messages:

```console
ERROR: ~/.cache/bazel/_bazel_khadas/0de19da26a472240f23447517e34d888/external/local_config_sycl/crosstool/BUILD:12:1: Target '@local_config_sycl//crosstool:empty' contains an error and its package is in error and referenced by '@local_config_sycl//crosstool:cc-compiler-local'
ERROR: ~/.cache/bazel/_bazel_khadas/0de19da26a472240f23447517e34d888/external/local_config_sycl/crosstool/BUILD:5:1: Target '@local_config_sycl//crosstool:cc-compiler-local' contains an error and its package is in error and referenced by '@local_config_sycl//crosstool:toolchain'
ERROR: ~/.cache/bazel/_bazel_khadas/0de19da26a472240f23447517e34d888/external/bazel_tools/src/tools/launcher/BUILD:9:1: every rule of type cc_binary implicitly depends upon the target '@local_config_sycl//crosstool:toolchain', but this target could not be found because of: Target '@local_config_sycl//crosstool:toolchain' contains an error and its package is in error
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.724s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 3 targets configured)
```

It seems it's telling that **bazel DIDN'T successfully specify crosstool:toolchain** ?

Well, yes, I didn't specify the toolchain, but on my **aarch64 board**, the toolchain are **ALREADY** **symbolic linked** to things including: **gcc**, **g++**, etc. I believe **it does relate to triSYCL** ....

Cheers
Pei

**Comment by keryell** [comment]
I am unsure what is the current support for SYCL in the latest TensorFlow.
We have tried a few years ago but it was not an efficient way for FPGA, so we gave up this route...

**Comment by sanatmpa1** [comment]
@jiapei100,

As we have the latest stable version `2.6.0`, Can you try building `TF 2.6.0` from source, and let us know if the issue still persists? Thanks!
