### ISSUE TITLE
TFLite MaxPool2D GPU op seems to modify source tensor

### ISSUE THREAD

**Issue by ghop02** [tensorflow/tensorflow#38732]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac os x 10.15.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Pixel 4
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf-nightly==2.2.0.dev20200420, also using the nightly tflite (cpu and gpu) build on android.
- Python version: 3.6.10

**Describe the current behavior**
Here's a fun one.  When running the max pool operator on the gpu (only tested the CL delegate), the input tensor was modified.  When running the model on the cpu, it outputs the original tensor as expected.

I unfortunately don't have good code to repro on android, but the models produced in the snippet below should should the expected behavior when running on the cpu and then the gpu. 

**Describe the expected behavior**
The input tensor is not modified when running a max pool 2d on the source tensor.

**Standalone code to reproduce the issue**
```python
import tensorflow as tf
import pathlib
import numpy

def convert(model, name):
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    tflite_model = converter.convert()
    pathlib.Path(name).write_bytes(tflite_model)
    

inpt = tf.keras.layers.Input(shape=[256, 256, 3])
conv = tf.keras.layers.Conv2D(32, 1, padding="same")(inpt)

out = tf.keras.layers.Lambda(
    lambda x: tf.nn.max_pool2d(
        x, 16, strides=1, padding="SAME"
    )
)(conv)
model = tf.keras.Model(inpt, [conv, out])
convert(model, 'out_gpu.tflite')

# Now force this to the maxpool to run on the cpu
inpt = tf.keras.layers.Input(shape=[256, 256, 3])
conv = tf.keras.layers.Conv2D(32, 1, padding="same")(inpt)
# This op should force the tensor onto the cpu.
out = tf.where(tf.equal(conv, conv), conv, tf.zeros_like(conv))
out = tf.keras.layers.Lambda(
    lambda x: tf.nn.max_pool2d(
        x, 16, strides=1, padding="SAME"
    )
)(out)
model = tf.keras.Model(inpt, [conv, out])
convert(model, 'out_cpu.tflite')
```

**Other info / logs** 
Sample output of running `out_gpu.tflite` on the GPU.
```
// conv
Row 0: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
// out
Row 0: [0.0029296875, 0.0029296875, 0.0029296875, 0.0029296875, 0.0029296875, 0.0029296875, 0.0029296875, 0.0029296875, -0.0087890625]
```

Same model, but ran on cpu only:
```
// conv
Row 0: [-0.23471934, -0.25280565, -0.26997373, -0.27565137, -0.2950689, -0.3190521, -0.34115076, -0.346938]
// out:
Row 0: [0.0030363789, 0.0030363789, 0.0030363789, 0.0030363789, 0.0030363789, 0.0030363789, 0.0030363789, 0.0030363789, -0.0088257985]
```

**Comment by terryheo** [comment]
@jdduke @impjdi Could you confirm if this is expected or a bug?

**Comment by impjdi** [comment]
Yeah, this may be broken unless you use the old GL delegate.  The new GPU delegate has a bug with intermediate tensors being graph output tensors.  Someone is in the process of fixing this, but I don't have an ETA.

**Comment by ghop02** [comment]
Thanks for the response! 

Which delegate are you referring to when you say old GL delegate? using the current nightly build, 
I believe we saw this issue when using a phone that only had OpenGL.

Also, would you consider the tensor an output tensor if it is moving from GPU -> CPU? In the actual model we're using, the equivalent of `conv` is used further in the graph and gets corrupted at that step.

**Comment by impjdi** [comment]
Old delegate: //tf/lite/delegates/gpu/gl_delegate.cc
New delegate: //tf/lite/delegates/gpu/delegate.cc

I didn't fully get what you meant by "it is moving from GPU -> CPU".  did you mean that the next op is an op not supported by the GPU, and thus moves to CPU execution?

**Comment by ghop02** [comment]
Ah okay.  

Yes that's exactly it.  I think equals isn't support? the output of the select node is messed up

![image](https://user-images.githubusercontent.com/1422280/80225347-f1114780-8618-11ea-829c-6b39a1d88cc5.png)

**Comment by impjdi** [comment]
Equal isn't supported, but neither are ZerosLike, Select, TopkV2 and what not.  The graph should probably fall back to CPU around there, either cut off at Logistic or MaxPool2D.  Depends on the topological sort.

**Comment by ghop02** [comment]
Yup! From my digging it cuts off after the MaxPool2D, which causes the corruption of the maxpool's input tensor which is being passed to other tensors being ran on the cpu. (sorry having a hard time clearly putting this into words 😁)

Re your comment: "The new GPU delegate has a bug with intermediate tensors being graph output tensors."
The graph output tensor doesn't have to be the ultimate output returned to the user, correct? but can also be the output to a slice of the graph that is running on the cpu.

**Comment by impjdi** [comment]
That is correct, it's just about the input/output tensors of the subgraph that the GPU delegate will handle.

**Comment by sushreebarsa** [comment]
I tried to run the code with TF v2.5 on colab & getting warning message ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/5a0e0bc0a58776e30b32619e241c16fc/untitled334.ipynb)..Thanks
