### ISSUE TITLE
What version of gast is required?

### ISSUE THREAD

**Issue by liym27** [tensorflow/tensorflow#38734]
**System information**
- OS Platform and Distribution : MacOS 10.14.3 
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.1.0
- Python version: 3.5
- Installed using virtualenv? pip? conda?: pip

**Describe the problem**
In file [`setup.py`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py#L60), gast  is required to be version 0.3.3, but after I installed tensorflow version 2.1.0, gast was version 0.2.2. I want to use gast 0.3.3, but error
```Python
ERROR: tensorflow 2.1.0 has requirement gast==0.2.2, but you'll have gast 0.3.3 which is incompatible
```

**Comment by ravikyram** [comment]
@liym27 

Can you try downgrading from gast==0.3.3 to gast==0.2.2 should work.Please install by (`!pip install gast==0.2.2`).

Starting from TensorFlow 2.2.0, it will work with gast 0.3.x but NOT gast 0.2.x any more. For TF <= 2.1, gast 0.2.2 is needed.Thanks!

**Comment by liym27** [comment]
> @liym27
> 
> Can you try downgrading from gast==0.3.3 to gast==0.2.2 should work.Please install by (`!pip install gast==0.2.2`).
> 
> Starting from TensorFlow 2.2.0, it will work with gast 0.3.x but NOT gast 0.2.x any more. For TF <= 2.1, gast 0.2.2 is needed.Thanks!

Thanks! 
 Where can I download the installation package of tensorflow 2.2.0? I didn't find it. And `pip install tensorflow==2.2.0rc3` didn't work.
![image](https://user-images.githubusercontent.com/33742067/79836550-de153200-83e2-11ea-809d-4b489b789758.png)

**Comment by ravikyram** [comment]
@liym27 

Can you try downgrading from gast==0.3.3 to gast==0.2.2 (by installing (`!pip install gast==0.2.2`) should work.

By installing gast=0.2.2 it should work with TF 2.1.0.Thanks!

**Comment by liym27** [comment]
@ravikyram 
> 
> Can you try downgrading from gast==0.3.3 to gast==0.2.2 (by installing (`!pip install gast==0.2.2`) should work.
> 
> By installing gast=0.2.2 it should work with TF 2.1.0.Thanks!

Of course, this is a solution. Thanks!

But is there a way to download package of tensorflow 2.2.0?

**Comment by ravikyram** [comment]
@liym27 

It is not available yet in official TF website.But you can refer #38712 .Please, use https://drive.google.com/a/google.com/uc?id=1dpTFQcBl0AWMeo5zcCWv47tpeOegEeoB&export=download .
As original issue we have provided solution, please close this issue and raise new issue for any new queries by filling issue template.Thanks!

**Comment by liym27** [comment]
> It is not available yet in official TF website.But you can refer #38712 .Please, use https://drive.google.com/a/google.com/uc?id=1dpTFQcBl0AWMeo5zcCWv47tpeOegEeoB&export=download .

Thanks!
