### ISSUE TITLE
SVD not accepting complex matrices

### ISSUE THREAD

**Issue by AidanGG** [tensorflow/tensorflow#3874]
Just with a small test case on the Eigen BDCSVD which should work with complex matrices, I  get `TypeError: DataType complex128 for attr 'T' not in list of allowed values: float64, float32`. I know that TensorFlow SVD is very new, but where would I look to enable complex types?

Here was my test code:
```python
x = np.array([[0, -1j], [1j, 0]])
a = tf.placeholder(tf.complex128, [None, None])
s, u, v = tf.svd(a)
sess = tf.Session()
print(sess.run(u, feed_dict={a: x}))
```

**Comment by rmlarsen** [comment]
@AidanGG your PR was merged. Thanks for the contribution!
