### ISSUE TITLE
tf.experimental.tensorrt.Converter sample code not working in tf 2.1.0

### ISSUE THREAD

**Issue by akkiss** [tensorflow/tensorflow#38747]
Ubuntu 14
Python 3.5.2
Tensorflow-gpu 'v2.1.0-rc2-17-ge5bf8de'

The sample codes provided on page https://www.tensorflow.org/api_docs/python/tf/experimental/tensorrt/Converter do not work, raise exception:
> NameError: name 'DEFAULT_TRT_CONVERSION_PARAMS' is not defined

This fix worked for me:
> from tensorflow.python.compiler.tensorrt import trt_convert as trt
> params = trt.DEFAULT_TRT_CONVERSION_PARAMS._replace(
>     precision_mode='FP16')

**Comment by Saduf2019** [comment]
@akkiss 
could you please provide us with a simple standalone code so we could replicate your issue, if possible share a colab gist for us to analyse it.

please check to this [link](https://github.com/tensorflow/tensorflow/issues/33277) for reference
