### ISSUE TITLE
Generate  C++ code from TensorFlow Lite metadata

### ISSUE THREAD

**Issue by SunAriesCN** [tensorflow/tensorflow#38740]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):  Master branch.
- Are you willing to contribute it (Yes/No):  Yes

**Describe the feature and the current behavior/state.**
I was so excited to hear that we can generate Android Java code from TensorFlow Lite meta-data with some codegen tools in TFLite. However, in our cases, most of the AI implementations are preferred to be wrapped into C++ interfaces, which reduce lots of work to maintain different  AI codes on different platforms. So,  I think C++ wrappers code generator of TensorFlow Lite metadata would be more favorable on business sight, which always has apps on lots of platform e.g. Android, IOS, other OS on devices and so on, and without develop AI implementations redundantly.  

**Will this change the current api? How?**
Maybe not, just support some new tools to generate a class I guessed.

**Who will benefit with this feature?**
I think lots of CPU manufacturers, solutions developers, smart devices manufacturers would be happy to hear good news from C++ code generator, they always need to develop some AI SDKs for their customers and they hardly know which platforms will run their SDKs, so C/C++ interfaces is the best choices for them.

**Any Other info.**

**Comment by SunAriesCN** [comment]
@lu-wang-g

**Comment by lu-wang-g** [comment]
Thanks for the feedback, Sun! I'm glad that you like the idea of metadata + codegen. You're right that C++ is super attractive to many users, we find this trend in our product analysis as well, especially those who are looking for cross-platform solutions. C++ is definitely on our top priority list, and we are actively working on it, starting from building some C++ utils and blocks. Please stay tuned for more updates about TFLite Support.

**Comment by jdduke** [comment]
Over to @lu-wang-g for follow-up.
