### ISSUE TITLE
Issue installing tensor flow python

### ISSUE THREAD

**Issue by JosiasAurel** [tensorflow/tensorflow#38750]
Please I have issues installing tensorflow in python using pip. I tried
```shell
pip install tensorflow
```
And 
 
```shell
pip3 install tensorflow 
```

**System information**
- OS Platform Linux Ubuntu 18):
- Mobile device (Android (using termux) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version: 3
- Installed using virtualenv? No 
pip? Yes 
conda?: No
I am using android 

Log : 

> Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow

**Comment by ravikyram** [comment]
@JosiasAurel 

Request you to fill[ issue template ](https://github.com/tensorflow/tensorflow/issues/new/choose)

You are using 64-bit version of Python or 32 bit version.Please, refer [link1](https://stackoverflow.com/questions/38896424/tensorflow-not-found-using-pip).Also, let us know which version of Tensorflow you are using?.Please, follow instruction in[ Tensorfow website](https://www.tensorflow.org/install/pip).Thanks!

**Comment by capSAR273** [comment]
I ran into the same issue, I am using Python 3.7.4 (64 bit), and the latest pip 20.0.2

**Comment by ravikyram** [comment]
@JosiasAurel 

Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by JosiasAurel** [comment]
In termux I used 
```shell
pip install tensorflow
```
The error stated above occurred

Same when I used in Ubuntu
```shell
pip3 install tensorflow
```
Windows I used the same command 
```shell
pip install tensorflow
```

**Comment by ymodak** [comment]
@JosiasAurel  What is your pip version? and python version?
Try
```
pip show pip
```
TF requires pip version =>19.0

**Comment by JosiasAurel** [comment]
My version of pip is 20.0.2

**Comment by JosiasAurel** [comment]
when I type 
```shell
pip show pip
```
My output is 
```shell
pip show pip
Name: pip
Version: 20.0.2
Summary: The PyPA recommended tool for installing Python packages.
Home-page: https://pip.pypa.io/
Author: The pip developers
Author-email: pypa-dev@groups.google.com
License: MIT
Location: /data/data/com.termux/files/usr/lib/python3.8/site-packages
Requires:
Required-by:
```

**Comment by ymodak** [comment]
I see you are using python 3.8.  We added python 3.8 support with Tensorflow 2.2.0-rc1.
Can you try installing the latest tensorflow release candidate?
`pip install tensorflow==2.2.0-rc4`

**Comment by JosiasAurel** [comment]
I still get an error 
```shell
ERROR: Could not find a version that satisfies the requirement tensorflow==2.2.0-rc4 (from versions: none)
ERROR: No matching distribution found for tensorflow==2.2.0-rc4
```

**Comment by mihaimaruseac** [comment]
Is your Python 64 bits?

**Comment by Dimidrol112** [comment]
I faced same issue. Just chek Is your Python 64 bits with 
```
import platform
platform.architecture()
```
And if it 32bit just reinstall python to 64.

**Comment by JosiasAurel** [comment]
64 bit

**Comment by mihaimaruseac** [comment]
What is the output of `pip debug --verbose`?

**Comment by JosiasAurel** [comment]
There it is
``` shell
pip version: pip 20.1 from /data/data/com.termux/files/usr/lib/python3.8/site-packages/pip (python 3.8)
sys.version: 3.8.2 (default, Mar 20 2020, 08:09:52)
[Clang 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf6
sys.executable: /data/data/com.termux/files/usr/bin/python3
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: UTF-8
sys.platform: linux
sys.implementation:
  name: cpython
'cert' config value: Not specified
REQUESTS_CA_BUNDLE: None
CURL_CA_BUNDLE: None
pip._vendor.certifi.where(): /data/data/com.termux/files/usr/lib/python3.8/site-packages/pip/_vendor/certifi/cacert.pem
pip._vendor.DEBUNDLED: False
vendored library versions:
  appdirs==1.4.3
  CacheControl==0.12.6
  colorama==0.4.3
  contextlib2==0.6.0.post1 (Unable to locate actual module version, using vendor.txt specified version)
  distlib==0.3.0
  distro==1.5.0 (Unable to locate actual module version, using vendor.txt specified version)
  html5lib==1.0.1
  ipaddress==1.0.23
  msgpack==1.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  packaging==20.3
  pep517==0.8.2
  progress==1.5
  pyparsing==2.4.7
  requests==2.23.0
  certifi==2020.04.05.1
  chardet==3.0.4
  idna==2.9
  urllib3==1.25.8
  resolvelib==0.3.0
  retrying==1.3.3 (Unable to locate actual module version, using vendor.txt specified version)
  setuptools==44.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  six==1.14.0
  toml==0.10.0
  webencodings==0.5.1 (Unable to locate actual module version, using vendor.txt specified version)
Compatible tags: 30
  cp38-cp38-linux_aarch64
  cp38-abi3-linux_aarch64
  cp38-none-linux_aarch64
  cp37-abi3-linux_aarch64
  cp36-abi3-linux_aarch64
  cp35-abi3-linux_aarch64
  cp34-abi3-linux_aarch64
  cp33-abi3-linux_aarch64
  cp32-abi3-linux_aarch64
  py38-none-linux_aarch64
  py3-none-linux_aarch64
  py37-none-linux_aarch64
  py36-none-linux_aarch64
  py35-none-linux_aarch64
  py34-none-linux_aarch64
  py33-none-linux_aarch64
  py32-none-linux_aarch64
  py31-none-linux_aarch64
  py30-none-linux_aarch64
  cp38-none-any
  py38-none-any
  py3-none-any
  py37-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any

```

**Comment by mihaimaruseac** [comment]
```
Compatible tags: 30
  cp38-cp38-linux_aarch64
  cp38-abi3-linux_aarch64
  cp38-none-linux_aarch64
  cp37-abi3-linux_aarch64
  cp36-abi3-linux_aarch64
  cp35-abi3-linux_aarch64
  cp34-abi3-linux_aarch64
  cp33-abi3-linux_aarch64
  cp32-abi3-linux_aarch64
  py38-none-linux_aarch64
  py3-none-linux_aarch64
  py37-none-linux_aarch64
  py36-none-linux_aarch64
  py35-none-linux_aarch64
  py34-none-linux_aarch64
  py33-none-linux_aarch64
  py32-none-linux_aarch64
  py31-none-linux_aarch64
  py30-none-linux_aarch64
  cp38-none-any
  py38-none-any
  py3-none-any
  py37-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any
```

None of those tags match tags for [the released pips](https://pypi.org/project/tensorflow/#files)

I see you are using Android? Probably you want to use tflite instead of tensorflow, since we don't directly build for mobile platforms.

**Comment by JosiasAurel** [comment]
Okay thanks. I don't have a PC that's why I use termux. But Pydroid 3 supports it

**Comment by mihaimaruseac** [comment]
An alternative is to use Google Colab: Notebooks similar to jupyter notebooks but treated similar to other Google Drive files so you can access them from anywhere while they run on Google infra.

**Comment by ymodak** [comment]
Closing this issue now. Thanks!

**Comment by RobertNissan** [comment]
pip install sdcard/tflite-support_0.1.0-py3-none-any.whl
WARNING: Requirement 'sdcard/tflite-support_0.1.0-py3-none-any.whl' looks like a filename, but the file does not exist
Processing ./sdcard/tflite-support_0.1.0-py3-none-any.whl
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/data/data/com.termux/files/home/sdcard/tflite-support_0.1.0-py3-none-any.whl'
