### ISSUE TITLE
Matching Keras Backend functions

### ISSUE THREAD

**Issue by arose13** [tensorflow/tensorflow#38761]
`tensorflow.keras.backend` is missing a function `logsumexp`

I was orginally just going to add the function from `tf.math` but it turns out that `tensorflow.keras.backend` is machine-generated. When I go to `create_python_api.py` to see if I could add it I was hit with nontrivial code on how this file finds what should be included as imports for the keras backend.

Is there anything I could do to get a change like this added to the project or was this already considered?

**System information**
- TensorFlow version (you are using): 2.*
- Are you willing to contribute it (Yes/No): yes

**Comment by jvishnuvardhan** [comment]
@arose13 Sorry for the late response. `logsumexp` method was deprecated from `keras.backend`. Please use it the same function under TF. Please check [here]
(https://www.tensorflow.org/api_docs/python/tf/math/reduce_logsumexp) for more information. Thanks
