### ISSUE TITLE
Large overhead when calling custom pure python code in training loop 

### ISSUE THREAD

**Issue by ronan-keane** [tensorflow/tensorflow#38763]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 
- TensorFlow installed from (source or binary): binary 
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
I am training a deep RL agent using tensorflow on a custom environment and have noticed that calling the environment.step method in my training loop is much slower than just calling it outside. Specifically, if I time how long it takes to run the environment.step inside my agent.train method, it takes ~50 times longer than when I just run environment.step by itself. 

**Describe the expected behavior**
There shouldn't be any overheads running my custom environment.step method inside agent.train

**Standalone code to reproduce the issue**
download 
https://github.com/ronan-keane/havsim/tree/DL3 
navigate to folder, pip install havsim . 
run traintest.py in scripts/meng assignments/control 1/ folder 

**Other info / logs** 
I tested gym's cartpole environment and it doesn't have the issue. Since cartpole and my custom environment are both implemented in pure python it makes me think the issue is that the custom environment has attributes which are dictionaries.

**Comment by ravikyram** [comment]
@ronan-keane 

Will it be possible to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by ronan-keane** [comment]
The issue was that the output from the neural net which was inputted to the custom python code was being converted from a tensor to a tf.float32. This would then cause the python code to convert everything to tensor, and all the math operations in the pure python code would then be acting on the newly converted tensors. This added the huge overheads. Issue was fixed by just converting the output of the NN to a regular python float.
