### ISSUE TITLE
Problem with read and get batch from 2d array tfrecords dataset

### ISSUE THREAD

**Issue by kaen2891** [tensorflow/tensorflow#38760]
## URL(s) with the issue:
https://www.tensorflow.org/tutorials/load_data/tfrecord#tfrecord_files_using_tfdata

## Description of issue (what needs changing):
Problem with read and get batch from 2d array tfrecords dataset

### Clear description

Hello. I use Tensorflow 2.0 version. I have some problems with reading Tfrecords file when get batch.

First, this is my read_tfrecords.py file.

```
import tensorflow as tf
import os
from glob import glob
import numpy as np


def serialize_example(batch, list1, list2):
    filename = "./train_set.tfrecords"
    writer = tf.io.TFRecordWriter(filename)

    for i in range(batch):
        feature = {}
        feature1 = np.load(list1[i])
        feature2 = np.load(list2[i])
        print('feature1 shape {} feature2 shape {}'.format(feature1.shape, feature2.shape)) 
        feature['input'] = tf.train.Feature(float_list=tf.train.FloatList(value=feature1.flatten()))
        feature['target'] = tf.train.Feature(float_list=tf.train.FloatList(value=feature2.flatten()))

        features = tf.train.Features(feature=feature)
        example = tf.train.Example(features=features)
        serialized = example.SerializeToString()
        writer.write(serialized)
        print("{}th input {} target {} finished".format(i, list1[i], list2[i]))



list_inp = sorted(glob('./input/2d_magnitude/*'))
list_tar = sorted(glob('./target/2d_magnitude/*'))


print(len(list_inp))
serialize_example(len(list_inp), list_inp, list_tar)
```

My input and target shapes are 2d array (Material of dataset is spectrogram). Therefore, my **Tfrecords** file includes two features likes ```[number_of_dataset, x, y]```. About 100,000 dataset was successfully saved as **Tfrecords** file.

And I have problem when I read **Tfrecords** file to get batch. This is my code ```read_tfrecords.py```:

```
import tensorflow as tf
import os
import numpy as np

shuffle_buffer_size = 50000
batch_size = 10
record_file = '/data2/dataset/tfrecords/train_set.tfrecords'

raw_dataset = tf.data.TFRecordDataset(record_file)
print('raw_dataset', raw_dataset) # ==> raw_dataset <TFRecordDatasetV2 shapes: (), types: tf.string>

raw_dataset = raw_dataset.repeat()
print('repeat', raw_dataset) # ==> repeat <RepeatDataset shapes: (), types: tf.string>

raw_dataset = raw_dataset.shuffle(shuffle_buffer_size)
print('shuffle', raw_dataset) # ==> shuffle <ShuffleDataset shapes: (), types: tf.string>

raw_dataset = raw_dataset.batch(batch_size, drop_remainder=True)
print('batch', raw_dataset) # ==> batch <BatchDataset shapes: (10,), types: tf.string>

raw_example = next(iter(raw_dataset)) 

parsed = tf.train.Example.FromString(raw_example.numpy()) # ==> read_tfrecords.py:25: RuntimeWarning: Unexpected end-group tag: Not all data was converted

print('parsed', parsed) # ==> ''

input = parsed.features.feature['input'].float_list.value
print('input', input) # ==> []
target = parsed.features.feature['target'].float_list.value
print('target', target) # ==> []
```

Here are results from code:
```
raw_dataset <TFRecordDatasetV2 shapes: (), types: tf.string>
repeat <RepeatDataset shapes: (), types: tf.string>
shuffle <ShuffleDataset shapes: (), types: tf.string>
batch <BatchDataset shapes: (10,), types: tf.string>
read_tfrecords.py:25: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  parsed = tf.train.Example.FromString(raw_example.numpy())
parsed
input []
target []
```
As a result, I wonder how I get the batch from Tfrecords file to train. 
**read_tfrecords.py:25: RuntimeWarning: Unexpected end-group tag: Not all data was converted**
Could you give advice? Thank you very much.

### Usage example
Maybe...

```
raw_dataset = tf.data.TFRecordDataset(record_file)

raw_dataset = raw_dataset.repeat()

raw_dataset = raw_dataset.shuffle(shuffle_buffer_size)

raw_dataset = raw_dataset.batch(batch_size, drop_remainder=True)

raw_example = next(iter(raw_dataset)) 

parsed = tf.train.Example.FromString(raw_example.numpy())

input = parsed.features.feature['input'].float_list.value
target = parsed.features.feature['target'].float_list.value
```

**Comment by Saduf2019** [comment]
@kaen2891 
i ran the code shared by you and face [this error](https://colab.sandbox.google.com/gist/Saduf2019/d425510d88e6d4f7670e3d4e2f1e0969/untitled152.ipynb), if possible please share a colab gist of the error faced for us to analyse

**Comment by kaen2891** [comment]
@Saduf2019 

I uploaded the code [here](https://colab.research.google.com/gist/Saduf2019/d425510d88e6d4f7670e3d4e2f1e0969/untitled152.ipynb).

Could you give me an advice? Thanks.

**Comment by Saduf2019** [comment]
@kaen2891 
can you please share the file uploaded in the cell "from google colab import files
example_file = files.upload()" for me to replicate the issue in the latest version.

**Comment by kaen2891** [comment]
@Saduf2019 

I don't know how to share the file with you. Instead of, I will share the link via [GoogleDrive](https://drive.google.com/file/d/1zNLXaY1arqLyMVxVV8xdKbQQe_1gQRY_/view?usp=sharing).

Thanks a lot.

**Comment by Saduf2019** [comment]
@kaen2891 
I am unable to access the data shared, it says no data/preview available.

**Comment by kaen2891** [comment]
@Saduf2019 

Okay. I changed code and now you can load the Tfrecords file in [here](https://colab.research.google.com/gist/kaen2891/54b4a21ddfd2da4f69e3b6a22b2b6678/untitled152.ipynb)

**Comment by kaen2891** [comment]
@Saduf2019 

The **Tfrecords file** that I made as an example is a conversion of datasets in the form of ```inp``` (100, 201, 22) and ```tar``` (100,201,23). Actually, it's same shape and format of the speech dataset which I actually have. For convenience, it is created with ```np.random.uniform(0,1,(100,201, 22))```. Would you check it please?

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/af6025c35b94c42c0c08160619ac0feb/38760.ipynb). Thanks!

**Comment by kaen2891** [comment]
@Saduf2019 
I don't know what you mean. Because the shared colab code is not changing. So should I just wait for this problem?

**Comment by jsimsa** [comment]
@aaudiber can you please take a look? thanks

**Comment by aaudiber** [comment]
@kaen2891, `tf.train.Example.FromString` parses a single example, not a batch of examples. See https://www.tensorflow.org/tutorials/load_data/tfrecord#reading_a_tfrecord_file for how to read `TFRecord` files with tf.data

**Comment by kaen2891** [comment]
@aaudiber , Okay. Then how can I read ```TFrecord``` to get batch? It's pretty hard to find information when I read ```TFrecord``` to get batch. Could you change the colab [code](https://colab.research.google.com/gist/Saduf2019/af6025c35b94c42c0c08160619ac0feb/38760.ipynb)?

**Comment by aaudiber** [comment]
After parsing, you can call `Dataset.batch(batch_size)` to put the examples in batches. Did the link I shared above help?

**Comment by kaen2891** [comment]
@aaudiber, No. Not yet.
Could you explain in more detail and kindness? In the example, it is not possible to put a batch. And I can't understand your words. When I add your comment to my code, I get the following error:
```tensorflow.python.framework.errors_impl.InvalidArgumentError: Key: input. Can't parse serialized Example.```
I wrote code with this [reference](https://www.tensorflow.org/tutorials/load_data/tfrecord#read_the_tfrecord_file).

I'll share my code via [Colab.](https://colab.research.google.com/gist/kaen2891/54b4a21ddfd2da4f69e3b6a22b2b6678/untitled152.ipynb) Could you solve this? In fact, if the data is small, I can just use directly, but in my case it is over 700GB. So I must use ```TFrecord``` to run the model. Please help me.

**Comment by aaudiber** [comment]
Please read https://www.tensorflow.org/tutorials/load_data/tfrecord#reading_a_tfrecord_file to understand how to read TFRecords with tf.data. Is there something specific in there that doesn't make sense to you?

**Comment by kaen2891** [comment]
@aaudiber , when I followed your comment, it doesn't work. Same error message. Could you check error [message?](https://colab.research.google.com/gist/kaen2891/54b4a21ddfd2da4f69e3b6a22b2b6678/untitled152.ipynb)

**Comment by aaudiber** [comment]
It looks like you are using `FixedLenFeature` to parse your features, but the features are sequences not scalars, so you need to use `FixedLenSequenceFeature` instead.

**Comment by kaen2891** [comment]
@aaudiber,
Thanks to you, I solve my problem. It worked as you said using ```FixedLenSequenceFeature```. Thanks for your kindness.

On the other hand, is it possible to change ```complex ndarray``` to ```tfrecords``` file? If possible, what kinds of format do I use for change? tf.float32?

**Comment by aaudiber** [comment]
If your data is complex numbers, you can use the [tf.complex64](https://www.tensorflow.org/api_docs/python/tf#complex64) Tensorflow type
