### ISSUE TITLE
ConvRNN2D.build() - TypeError: can only concatenate list (not "tuple") to list

### ISSUE THREAD

**Issue by kevinkepp** [tensorflow/tensorflow#38767]
**System information**
- Have I written custom code: Yes, see code snippet below
- OS Platform and Distribution: `Ubuntu 19.10`
- TensorFlow installed from: `pip install tensorflow==2.1`
- TensorFlow version: `v2.1.0-rc2-17-ge5bf8de 2.1.0`
- Python version: `3.7.5`
- CUDA/cuDNN version: `CUDA 10.1`
- GPU model and memory: `GeForce GTX 1080 Ti 11GB`

**Describe the current behavior**
ConvRNN2D fails to build when restoring from config.

**Standalone code to reproduce the issue**
```
from tensorflow.python.keras.layers.convolutional_recurrent import (
    ConvRNN2D,
    ConvLSTM2DCell,
)

cell = ConvLSTM2DCell(filters=32, kernel_size=(3, 3))
rnn = ConvRNN2D(cell)
rnn = ConvRNN2D.from_config(rnn.get_config())
rnn.build(input_shape=(1, 10, 15, 15, 16))
```

**Other info / logs**
```
Traceback (most recent call last):
  File "/home/kevin/dev/tf_bug.py", line 9, in <module>
    rnn.build(input_shape=(1, 10, 15, 15, 16))
  File "/home/kevin/dev/.venv/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/tf_utils.py", line 306, in wrapper
    output_shape = fn(instance, input_shape)
  File "/home/kevin/dev/.venv/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/convolutional_recurrent.py", line 244, in build
    self.cell.build([step_input_shape] + constants_shape)
TypeError: can only concatenate list (not "tuple") to list
```

**Comment by kevinkepp** [comment]
It seems like `rnn._num_constants` is `0` during `rnn.build()` which is not handled properly. I presume `rnn._num_constants` is expected to be `None` or a value > 0.

`rnn._num_constants` being `0` might be due to the following:
`RNN.__init__()` sets `self._num_constants=0` and `ConvRNN2D.__init__()` then overwrites it with `self._num_constants=None`. However, `ConvRNN2D.from_config()` still defaults `self._num_constants` to `0` (like in `RNN.from_config()`) instead of defaulting to `None`.

**Comment by ravikyram** [comment]
Was able to reproduce the issue with TF nightly version(`2.4.0-dev20200805`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/ca6d33d2cd83437d12c4ca4e7034988e/untitled222.ipynb).Thanks!

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210526, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/a124252444a1118ac18b8e2996da2cef/38767.ipynb). Thanks!

**Comment by mohantym** [comment]
Hi @kevinkepp !
We are checking to see whether you still need help in this issue . Have you tried building your model using [RNN documentation ](https://www.tensorflow.org/api_docs/python/tf/keras/layers/RNN)from latest version (2.7) yet? Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
