### ISSUE TITLE
.NET Language Bindings

### ISSUE THREAD

**Issue by Cloudmersive** [tensorflow/tensorflow#38770]
.NET is one of the top languages and yet there are no Tensorflow language bindings.  This makes it hard to use in an Enterprise setting and is limiting the adoption of Tensorflow.  This is a huge lever as well to drive adoption deeper into traditional companies.

**Describe the feature and the current behavior/state.**

Currently there are Java and Python language bindings for Tensorflow, but no official .NET bindings.  There is a third party unofficial project but it only supports old versions of Tensorflow and is not officially maintained

**Will this change the current api? How?**

No

**Who will benefit with this feature?**

The entire .NET ecosystem, which is about the same size or larger than the Java ecosystem.  Visual Studio is the #1 IDE in the world.

**Any Other info.**

**Comment by mihaimaruseac** [comment]
Unfortunately we don't have anyone internally that can work on this at the moment. However, PRs are welcome, as well as community maintained repositories.
