### ISSUE TITLE
Considerations about micro_speech example

### ISSUE THREAD

**Issue by biagiom** [tensorflow/tensorflow#38778]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from: pip
- Tensorflow version: master branch
- Target platform: mbed, STM32F746

**Describe the problem**
I decided to open this issue because there are some others issues and pull requests related to the `micro_speech` example (like https://github.com/tensorflow/tensorflow/issues/35889),  and so I would like to take stock of the situation, describe the issues I found and how to solve them (see below).

**Please provide the exact sequence of commands/steps when you ran into the problem**
To build the `micro_speech` example I used the steps provided by the documentation related to the example in [README.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/micro_speech/README.md):

- `git clone https://github.com/tensorflow/tensorflow.git`
- `cd tensorflow`
- `make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mbed TAGS="CMSIS disco_f746ng" generate_micro_speech_mbed_project`

However, I obtained the following error:
`make: *** No rule to make target "tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4/prj/micro_speech/mbed/tensorflow/lite/micro/tools/make/downloads/CMSIS_ext/arm_cmplx_mag_squared_q10p6.c", needed by "generate_micro_speech_mbed_project".  Stop.`

So, as suggested in https://github.com/tensorflow/tensorflow/pull/36444, I removed `arm_cmplx_mag_squared_q10p6.c/h` from `tensorflow/lite/micro/examples/micro_speech/CMSIS/Makefile.inc`.
But when I launched again the build I obtained this other issue:
`make: *** No rule to make target "tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4/prj/micro_speech/mbed/third_party/CMSIS_ext/README.md", needed by "generate_micro_speech_mbed_project".  Stop.`
I managed to solve the new issue by removing `third_party/CMSIS_ext/README.md` line from `tensorflow/lite/micro/examples/micro_speech/CMSIS/Makefile.inc` since it is not a header file needed for the build.

At this point the project is created in `tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4/prj/micro_speech/mbed`, but when I launched the command `mbed compile -m DISCO_F746NG -t GCC_ARM` I got this other error:
`Compile [ 95.6%]: arm_mult_q15.c
[Error] arm_mult_q15.c@101,6: conflicting types for 'arm_mult_q15'
[ERROR] ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_q15.c:101:6: error: conflicting types for 'arm_mult_q15'
 void arm_mult_q15(
      ^~~~~~~~~~~~
In file included from ./tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_q15.c:29:0:
./mbed-os/cmsis/TARGET_CORTEX_M/arm_math.h:1924:8: note: previous declaration of 'arm_mult_q15' was here
   void arm_mult_q15(
        ^~~~~~~~~~~~`
But again I managed to fix it by simply upgrading Mbed to 6.0.0-alpha-3 version as suggested in https://github.com/tensorflow/tensorflow/pull/37930.

**I added all the 3 changes in the [micro_speech_fix branch](https://github.com/biagiom/tensorflow/tree/micro_speech_fix) of my tensorflow repo.**

**Moreover, another useful way to solve the build issues is to use the `cmsis-nn` TAG instead of `CMSIS` (see also https://github.com/tensorflow/tensorflow/issues/35889), that is:**
`make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mbed TAGS="cmsis-nn disco_f746ng" generate_micro_speech_mbed_project`.
This also has some "advantages":

- when adding `CMSIS` to `TAGS=,` the [CMSIS-NN optimized kernels](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/kernels/cmsis-nn) are not added to the example during the build instead of the `cmsis-nn` tag. Moreover, since the _tiny_conv_ model is based on a conv2D layer, we can benefit for the optimized implementation of the convolution.
- the source code in [`tensorflow/lite/micro/examples/micro_speech/CMSIS`](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/micro_speech/CMSIS) that will be  added to the build using the `CMSIS` TAG is not directly related to the `micro_speech` example but (as far as I know) it is mostly used for [testing purposes (simple_features_generator_test)](https://github.com/tensorflow/tensorflow/blob/2ced38fde44235e3684c91280572fe55707df1a1/tensorflow/lite/micro/examples/micro_speech/Makefile.inc#L249) and for the apollo3 board but not for mbed/stm32f7. In particular, I also noticed that also when building the `simple_features_generator_test` with the `CMSIS` tag, it generates an error which says that the `arm_cmplx_mag_squared_q10p6.c` is not found. This is because make tries to find that file in the CMSIS_ext directory in `tensorflow/lite/micro/tools/make/downloads` but this doesn't exists. Moreover there is no way to download the custom CMSIS (CMSIS_ext) because its url is not defined in [third_party_downloads.inc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/tools/make/third_party_downloads.inc). I also noticed that [mbed_makefile.inc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/tools/make/targets/mbed_makefile.inc) includes [this line](https://github.com/tensorflow/tensorflow/blob/b9edec000c94761fc52e2ce38efa6385fff45f42/tensorflow/lite/micro/tools/make/targets/mbed_makefile.inc#L5), but `CUST_CMSIS_URL` and `CUST_CMSIS_MD5` are never defined.

In conclusion, I would like to suggest the following changes:

1. Update the [README](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/micro_speech/README.md) related to the `micro_speech` example in order to use the `cmsis-nn` TAG instead of `CMSIS` (or use both if needed).
2. Remove `arm_cmplx_mag_squared_q10p6.c/h` from [`tensorflow/lite/micro/examples/micro_speech/CMSIS/Makefile.inc`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/micro_speech/CMSIS/Makefile.inc). Otherwise if the files are useful, I suggest to add them directly into [the `tensorflow/lite/micro/examples/micro_speech/CMSIS/` folder](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/micro_speech/CMSIS) and remove the dependency from CMSIS_ext. Also we need to update the [mbed_makefile.inc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/tools/make/targets/mbed_makefile.inc) file.
3. Update Mbed to 6.0.0-alpha-3 version (see https://github.com/tensorflow/tensorflow/pull/37930).
4. Remove [`third_party/CMSIS_ext/README.md` line](https://github.com/tensorflow/tensorflow/blob/b9f8df3930b34de2f461bb99813ade4b890e82c6/tensorflow/lite/micro/examples/micro_speech/CMSIS/Makefile.inc#L20) from `tensorflow/lite/micro/examples/micro_speech/CMSIS/Makefile.inc` since it is not a header file needed for the build.

I can contribute with some pull requests based on the above ideas if needed and I'm open to other suggestions/ideas in order to improve the `micro_speech` example and solve its issues.

Best regards,
Biagio.

**Comment by mohantym** [comment]
Hi @biagiom ! Could you post this on [tflite-micro](https://github.com/tensorflow/tflite-micro) repo . Thank you!
