### ISSUE TITLE
AttributeError: type object 'TFLiteConverter' has no attribute 'from_keras_model'

### ISSUE THREAD

**Issue by LINYOUWEI0804** [tensorflow/tensorflow#38786]
ubuntu18.04 use [jupyter notebook]
tensorflow (1.14.0)
tensorflow-estimator (1.14.0)
tensorflow-gpu (1.14.0)

I follow[https://www.tensorflow.org/lite/performance/post_training_integer_quant]   can do
but I follow [https://www.tensorflow.org/lite/convert/python_api]Converting a Keras model There is such an error ： 
（AttributeError: type object 'TFLiteConverter' has no attribute 'from_keras_model'）

**Comment by TCBocean** [comment]
I have the impression that from_keras_model is an API of 2.x, so it is recommended that you upgrade to tf2.x version, or use from_keras_model_file API

**Comment by oke-aditya** [comment]
Hello @LINYOUWEI0804 .
The notebook given in https://www.tensorflow.org/lite/performance/post_training_integer_quantl is running on tensorflow v2 API.

Please have a look at [compatibility](https://www.tensorflow.org/lite/convert/1x_compatibility) if you wished to work with 1.x API.

**Comment by amahendrakar** [comment]
@LINYOUWEI0804,
Could you please try running the code with TensorFlow 2.x. I was able to run the code without any issues, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/0fda9c42859c33b3c852105eabe5915c/38786.ipynb). Thanks!

**Comment by LINYOUWEI0804** [comment]
Thank ,I update tf to 2.0 and it will run

**Comment by amahendrakar** [comment]
> Thank ,I update tf to 2.0 and it will run

Please feel free to close the issue if resolved. Thanks!

**Comment by sinh123457** [comment]
làm ơn giúp tôi chuyển qua file TFlite
