### ISSUE TITLE
[TFlite dynamic range quantization]How can I disable dynamic quantization of activations? in inference?

### ISSUE THREAD

**Issue by lishasha233** [tensorflow/tensorflow#38781]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
-  Ubuntu 16.04:
- pip installed:
- TensorFlow version 2.1.0:

This document [https://tensorflow.google.cn/lite/performance/post_training_quantization](url)
said that we can use "Dynamic range quantization",which statically quantizes only the weights from floating point to 8-bits of precision.And "dynamic-range" operators will dynamically quantize activations based on their range to 8-bits and perform computations with 8-bit weights and activations.

But I want to quantize the weights to int8/uint8, and make sure all the operators are computed using only floating-point kernels at inference,which means no activations will be quantized.

So,how can I realize this?How can I avoid quantization of these "dynamic-range" operators?

**Comment by tilakrayal** [comment]
@lishasha233,
To ensure compatibility with integer only devices (such as 8-bit microcontrollers) and accelerators (such as the Coral Edge TPU), you can enforce full integer quantization for all ops including the input and output, by using the following steps:

```
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8
tflite_quant_model = converter.convert()
```

Also please take a look at the official [document](https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only_16-bit_activations_with_8-bit_weights_experimental) for reference. Thank you!

**Comment by tilakrayal** [comment]
Closing this as stale. Please reopen if this is still a valid request. Thank you!
