### ISSUE TITLE
 The _pywrap_tensorflow_internal.so files generated by the two compilations are different，why？

### ISSUE THREAD

**Issue by zxin-what** [tensorflow/tensorflow#38791]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from source :
- TensorFlow version:1.15.2
- Python version:3.7
- Installed using pip:
- Bazel version 0.25.0:
- GCC/Compiler version :7.3.0

**Comment by ravikyram** [comment]
@zxin-what 

Please provide details about what platform you are using (operating system, architecture).Please,provide the exact sequence of commands / steps that you executed before running into the problem.Please, share error log as well.Thanks!
