### ISSUE TITLE
Deploy Sequence to Sequence Model with Tensorflow Serving

### ISSUE THREAD

**Issue by psyfb2** [tensorflow/tensorflow#38794]
I have created a seq2seq model for question and answering by following the tensorflow tutorial here: https://www.tensorflow.org/tutorials/text/nmt_with_attention

The model works well and I want to deploy it with Tensorflow serving. it's not clear how I could do this efficiently because:
- The decoder can only make a prediction for the next word, by taking as input the last predicted word. Surely it's not efficient to send multiple inference requests word by word instead of generating the whole sentence server side?
- is there any way to do the preprocessing server side? (e.g. client only has to send the tensorflow serving text, instead of numpy arrays).

**Comment by amahendrakar** [comment]
@psyfb2,
Since this issue is related to TF Serving, could you please close this issue and create a new one in the Serving repo from [this link](https://github.com/tensorflow/serving/issues/new) so that we can track it there. Thanks!
