### ISSUE TITLE
tf.data.Dataset.from_tensor_slices: ValueError: Failed to convert a NumPy array to a Tensor (Unsupported␣ ,→object type list), worked on 2.0.0-beta1

### ISSUE THREAD

**Issue by NiBurhe** [tensorflow/tensorflow#38793]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10/Juniper lab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Notebook
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0-rc3
- Python version: 3.8.1
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: no idea
- GPU model and memory: Geforce GTX 960M

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I get an error when call tf.data.Dataset.from_tensor_slices with
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported␣
,→object type list), see attachment
[Answer.Tensorflow.pad.sequence.feature.column.DenseFeatures.pdf](https://github.com/tensorflow/tensorflow/files/4515932/Answer.Tensorflow.pad.sequence.feature.column.DenseFeatures.pdf)

**Describe the expected behavior**
I tried to use this example
https://github.com/EgorBEremeev/SoloLearnML/blob/master/stackoverflow/Answer.%20Tensorflow%20pad%20sequence%20feature%20column.%20DenseFeatures.ipynb

It looks like it was running on 2.0.0-beta1, but not more in the current version. You can use this notebook to reproduce the case.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
https://github.com/EgorBEremeev/SoloLearnML/blob/master/stackoverflow/Answer.%20Tensorflow%20pad%20sequence%20feature%20column.%20DenseFeatures.ipynb
You need to adapt the path the the csv file which will also be available in the repository.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.1, [TF v2.2.0-rc3](https://colab.research.google.com/gist/amahendrakar/1a8342379761f0312278f18c85d09e65/38793.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/ceb90694563d02400c5870b319001b68/38793-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by ymodak** [comment]
Can you please provide a small reproducible code to validate the behavior? This will help to troubleshoot faster. Thanks!

**Comment by NiBurhe** [comment]
Hello @ymodak,

example code can be found in amahendrakas comment. In general I have a pandas dataframe with one column as Bag of word list.

I tried to use an examplehttps://github.com/EgorBEremeev/SoloLearnML/blob/master/stackoverflow/Answer.%20Tensorflow%20pad%20sequence%20feature%20column.%20DenseFeatures.ipynb and he already give me an solution. He switched
`ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))`
to
`ds = tf.data.Dataset.from_tensor_slices((dataframe .to_dict(orient='list'), labels))`
and then it works.
So I'm not sure if this still is a bug in TF or not. Because in 2.0 beta it works and in 2.1 and following not.

Thanks

**Comment by jsimsa** [comment]
@aaudiber can you please take a look? thanks

**Comment by aaudiber** [comment]
The problem is that `from_tensor_slices` needs to convert its input into a Tensor, but the given input contains variable-length numpy lists, which cannot be converted into tensors (tensors must be rectangular). You can get the same error message by running

```
a = np.array([[1, 2, 3], [4, 5]], dtype=object)
print(tf.convert_to_tensor(a))
```

This error appears to occur even in tensorflow 2.0.0-beta1, so it doesn't look like a regression.

To make this work, you need to pad the dataframe's lists so that they are the same length.
