### ISSUE TITLE
tf.keras model.fit causes sytem reboot (cpu,centOS)

### ISSUE THREAD

**Issue by g2721** [tensorflow/tensorflow#38795]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):centos-release-7-7.1908.0.el7.centos.x86_64- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):2.1.0
- Python version:3.7
- GPU model and memory: running on cpu
- Ram: 64gb
- I'am using a VGG16 model(at least part of it)

**Describe the current behavior**
When using model.fit or model.fit_generator on models with large amounts of parameters my server reboots and I get a timeout on ssh. The log files don't show any errors, just the execution of my program and then the normal boot sequence. It seems like the issue starts when using over 60000 parameters. If I increase the amount of parameters this phenomena appears faster(earlier in the training process), when using around 200000 parameters it most times happens in the first epoch, but it's not consistent(I managed to train my model with 1million parameters for 10 epochs). Monitoring my Ram usage reveals that I' am just using fractions of what's available (6.5 gb out of 64gb). Furthermore in each epoch I'am getting this warning: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
My code (I reduced parameters by removing layers):
<img width="2210" alt="Bildschirmfoto 2020-04-22 um 15 26 47" src="https://user-images.githubusercontent.com/37218380/79987429-b17a1c80-84ad-11ea-8cee-f79140f573ad.png">

Same code works on Raspbian beside it not having enough RAM

**Describe the expected behavior**
Working without a problem or an error warning.  
Could it be a hardware problem?

**Other info / logs** No errors are visible in the log file.

**Comment by ravikyram** [comment]
@g2721 

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by g2721** [comment]
It seems like it's not a problem with TensorFlow. My code runs perfect on my iMac, probably it's a issue with python, CentOS or a hardware problem
