### ISSUE TITLE
Build Windows Library using Docker

### ISSUE THREAD

**Issue by JinZhuXing** [tensorflow/tensorflow#38799]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 (1909) x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version: v2.1
- Python version: v3.7
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): v0.29.1
- GCC/Compiler version (if compiling from source): VC2019
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

How can I build tensorflow windows library using Docker container?
I just built tensorflow linux library using dev Docker.
But I can't build windows library using dev Docker.
Please help me. Thank you.

**Comment by angerson** [comment]
Docker for Windows build support is unavailable. Please follow the [Build from Source on Windows](https://www.tensorflow.org/install/source_windows) instructions to build without Docker.
