### ISSUE TITLE
OSError:savedmodel file does not exist at .. path/savedmodel.pbtxt:saved model.pb

### ISSUE THREAD

**Issue by zero-coolz1** [tensorflow/tensorflow#38809]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution windows 8
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):pip
- TensorFlow version:2.2.0rc3
- Python version:3.7
- Installed using virtualenv? pip? conda?:yes
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory:nvdia gforce 940m

when i tried to run object detection model for first time in starting everything was going fine but at the end of the program i got this error 

<PIL.Image.Image image mode=RGB size=1352x900 at 0xF58A584A88>
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
G:\A!\compressed\models\research\object_detection\object_detection_tutorialasdf.
py in <module>
    270
    271 model_name = "mask_rcnn_inception_resnet_v2_atrous_coco_2018_01_28"
--> 272 masking_model = load_model("mask_rcnn_inception_resnet_v2_atrous_coco_20
18_01_28")
    273
    274

G:\A!\compressed\models\research\object_detection\object_detection_tutorialasdf.
py in load_model(model_name)
    132   model_dir = pathlib.Path(model_dir)/"saved_model"
    133
--> 134   model = tf.saved_model.load(str(model_dir))
    135   model = model.signatures['serving_default']
    136

~\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\saved_mod
el\load.py in load(export_dir, tags)
    526     ValueError: If `tags` don't match a MetaGraph in the SavedModel.
    527   """
--> 528   return load_internal(export_dir, tags)
    529
    530

~\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\saved_mod
el\load.py in load_internal(export_dir, tags, loader_cls)
    535     # sequences for nest.flatten, so we put those through as-is.
    536     tags = nest.flatten(tags)
--> 537   saved_model_proto = loader_impl.parse_saved_model(export_dir)
    538   if (len(saved_model_proto.meta_graphs) == 1
    539       and saved_model_proto.meta_graphs[0].HasField("object_graph_def"))
:

~\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\saved_mod
el\loader_impl.py in parse_saved_model(export_dir)
     81                   (export_dir,
     82                    constants.SAVED_MODEL_FILENAME_PBTXT,
---> 83                    constants.SAVED_MODEL_FILENAME_PB))
     84
     85

OSError: SavedModel file does not exist at: C:\Users\zerocoolz1\.keras\datasets\
mask_rcnn_inception_resnet_v2_atrous_coco_2018_01_28\saved_model/{saved_model.pb
txt|saved_model.pb}

and when i went to the directory i found these files
1: checkpoint
2:model.ckpt.data-00000-of-000001
3:model.ckpt.index
4:pipeline.config

**Comment by ravikyram** [comment]
@zero-coolz1 

Will it be possible to share simple standalone code to reproduce the issue here.It helps us in localizing the issue faster.Thanks!

**Comment by zero-coolz1** [comment]
i just ran the code extracted from object_detection_tutorial.pynb and converted that into file.py

**Comment by ravikyram** [comment]
@zero-coolz1 

 Please close this thread if your issue was resolved. Thanks!

**Comment by ravikyram** [comment]
@zero-coolz1 

Any update on this issue please.Thanks!
