### ISSUE TITLE
Docker Image tensorflow:latest-gpu contains 450 MB of pip cache under root directory

### ISSUE THREAD

**Issue by tarmath** [tensorflow/tensorflow#38815]
Docker Image tensorflow:latest-gpu contains 450+ MB of pip cache under root user's home directory.

Steps to reproduce:

    docker run --rm -it docker.apple.com/tensorflow/tensorflow:latest-gpu bash

then inside the container:

    root@9eae8825ebd9:/# cd 
    root@9eae8825ebd9:~# du -h -d 1
    458M	./.cache
    458M	.

I noticed this while pulling the tensorflow:2.1.0-gpu-py3 Image and then pulled latest to see if the issue had been fixed since...

Other images may be affected as well, I haven't verified.

**Comment by angerson** [comment]
Thanks for your report! The commit linked above should remove the extra space, unless the pip cache comes from something outside of our Dockerfiles. The change should apply today or tomorrow.

**Comment by tarmath** [comment]
Thanks for the very quick turnaround! 

Small question - not sure how to interpret the labels here (TF 2.1). 
Does it describe where the problem is, and/or where the fix will be applied?

In other words, am I to expect a new docker image for 2.1.0, or should I upgrade to latest to obtain the space savings?
