### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by fbordignon** [tensorflow/tensorflow#38818]
ksizes should be sizes on:
https://github.com/tensorflow/tensorflow/blob/e5bf8de410005de06a7ff5393fafdf832ef1d4ad/tensorflow/python/ops/array_ops.py#L4806

also on lines 4805 and 4835 the call needs updating to

`tf.image.extract_patches`

https://github.com/tensorflow/tensorflow/blob/e5bf8de410005de06a7ff5393fafdf832ef1d4ad/tensorflow/python/ops/array_ops.py#L4805

https://github.com/tensorflow/tensorflow/blob/e5bf8de410005de06a7ff5393fafdf832ef1d4ad/tensorflow/python/ops/array_ops.py#L4835

**Comment by yongtang** [comment]
@fbordignon Added a PR #38819 for the fix. Thanks for pointing out!

**Comment by fbordignon** [comment]
Great, thanks!
