### ISSUE TITLE
ImportError: No module named tools (missing __init__.py?)

### ISSUE THREAD

**Issue by cardshuffle** [tensorflow/tensorflow#3881]
### Environment info
Operating System: Ubuntu 14.04 LTS 64-bit

Installed version of CUDA and cuDNN: none

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`): fc9162975e52978d3af38549b570cc3cc5f0ab66
2. The output of `bazel version`:
```
Build label: 0.3.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 10 11:38:23 2016 (1465558703)
Build timestamp: 1465558703
Build timestamp as int: 1465558703
```

### Steps to reproduce
1. Create a new IPython Notebook
2. Run the following:
```
import tensorflow as tf
from tensorflow.python.tools import freeze_graph
```

### What have you tried?
It seems that the tools directory is missing an `__init__.py` (though there is one in the python directory), and so tools isn't being recognized as a module. However, this is a bit baffling, because [`freeze_graph_test.py`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph_test.py) uses these exact same import statements. Just to be sure, I tried copying in all the import statements in `freeze_graph_test.py`:
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os

import tensorflow as tf

from tensorflow.python.framework import test_util
from tensorflow.python.tools import freeze_graph
```
and sure enough, `freeze_graph` was the only one that gave an error.

`__init__.py` doesn't appear in the repository on GitHub as well. I noticed there's a Bazel BUILD file instead, but as far as I know, Bazel is only used to build the Android demo. Am I missing something?

### Logs or other output that would be helpful
```
ImportError                               Traceback (most recent call last)
<ipython-input-10-039cb956bb5c> in <module>()
      1 import tensorflow as tf
----> 2 from tensorflow.python.tools import freeze_graph

ImportError: No module named tools
```

**Comment by sherrym** [comment]
The tools are not part of the runtime.

**Comment by cardshuffle** [comment]
@sherrym in that case, how would I freeze a graph?

**Comment by yaroslavvb** [comment]
.py file has instructions:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py

An example of command-line usage is:
bazel build tensorflow/python/tools:freeze_graph && \
bazel-bin/tensorflow/python/tools/freeze_graph \
--input_graph=some_graph_def.pb \
--input_checkpoint=model.ckpt-8361242 \
--output_graph=/tmp/frozen_graph.pb --output_node_names=softmax

**Comment by kolesov93** [comment]
Am I right, that there is no way to use this script with pip install, and I need to install tensorflow from source?

**Comment by sherrym** [comment]
At the moment, that's correct.
