### ISSUE TITLE
Need to update nightly-devel and nightly-devel-gpu docker images

### ISSUE THREAD

**Issue by settle** [tensorflow/tensorflow#38811]
Currently (as expected):
$ docker run --rm -it tensorflow/tensorflow:nightly bash
\# python -c "import tensorflow as tf; print(tf.__version__)"
2.2.0-dev20200422

However:
$ docker run --rm -it tensorflow/tensorflow:nightly-devel bash
\# python -c "import tensorflow as tf; print(tf.__version__)"
1.12.0-rc0

Same goes for the nightly-devel-gpu docker image.

**Comment by angerson** [comment]
Thanks for your report. As noted in the Docker Hub pages, `-devel` tags are not for using TensorFlow, but for developing changes to TensorFlow:

>devel images come with Bazel and are ideal for developing changes to TensorFlow at master. /tensorflow_src includes the TensorFlow source tree at the latest nightly commit where the Pip package built successfully in the container. We no longer provide images for developing on top of older versions of TF (1.12.0 was the last release where this was the case).

Although TensorFlow being installed is indeed confusing, it is not a broken image.

**Comment by settle** [comment]
@angerson As I understand it, nightly tags have the most recent Pip package built from master, and together with -devel would includes the most up-to-date build environment.  My intention is to use nightly-devel for developing changes to TensorFlow (creating a new TensorFlow Lite delegate) and automate testing to catch when experimental features have changed and I need to change my code base to align with them.

**Comment by angerson** [comment]
Ah, my mistake, I didn't notice you were referring to `nightly-devel` specifically. `nightly-devel` was renamed to `devel`; `latest-devel` and `devel` are the same. Please use that instead.
