### ISSUE TITLE
Some similar Docker images don't have the same image ID

### ISSUE THREAD

**Issue by settle** [tensorflow/tensorflow#38812]
latest and 2.1.0 are the same image as expected, but that's not the case for latest-gpu and 2.1.0-gpu.

$ docker images
REPOSITORY | TAG | IMAGE ID | CREATED | SIZE
-|-|-|-|-
tensorflow/tensorflow | latest | 9bf93bf90865 | 3 months ago | 2.47GB
tensorflow/tensorflow | 2.1.0 | 9bf93bf90865 | 3 months ago | 2.47GB
tensorflow/tensorflow | latest-gpu | 3c0df9ad26cc | 3 months ago | 4.09GB
tensorflow/tensorflow | 2.1.0-gpu | cb908459d986 | 3 months ago | 4.09GB

**Comment by angerson** [comment]
Thanks for your report. Can you explain more about the problem here? Our Docker CI is flaky and can lead to this sort of thing, and although it's not ideal, I don't know of any urgent reasons we'd want to ensure the images are exactly mirrored at all times, as long as they work.

**Comment by angerson** [comment]
Moved from #31113:

>latest-devel and devel are the same image as expected, but that's not the case for latest-devel-gpu and devel-gpu.
>
>$ docker images
>REPOSITORY | TAG | IMAGE ID | CREATED | SIZE
>-|-|-|-|-
>tensorflow/tensorflow | latest-devel | 468b5e19fd6a | 6 hours ago | 1.97GB
>tensorflow/tensorflow | devel | 468b5e19fd6a | 6 hours ago | 1.97GB
>tensorflow/tensorflow | latest-devel-gpu | 08aacdcc1422 | 7 hours ago | 4.17GB
>tensorflow/tensorflow | devel-gpu | 72b4573fd1c4| 30 hours ago | 4.17GB

**Comment by settle** [comment]
@angerson I agree this probably isn't the more urgent of issues and is mostly to correct the ambiguity when automating testing so as not to repeat latest- with explicit versioned images.  Also allows someone before creating a docker container to know the explicit version of latest.

In the second case (devel- tags) it probably matters less so since non-latests versions have been dropped from devel images.  In which case, maybe remove one of the duplicate tag sets to simplify things, e.g., devel and devel-gpu?

**Comment by angerson** [comment]
For `devel`, we decided to publish both for a reason I don't recall; I think because `latest-devel` was probably in use by many users already, and Docker Hub does not have a convenient mechanism for deprecating tags. I've updated the Docker Hub page with an extra note to mention that they're the same, though.

**Comment by kumariko** [comment]
@settle Could you please check https://github.com/tensorflow/tensorflow/issues/38812#issuecomment-619171137 and let us know if you still need help on this ? if it is resolved then please feel free to move this issue to close status ? Thanks!
