### ISSUE TITLE
What is the minimum subset of cuda toolkit to install for tensorflow gpu to work?

### ISSUE THREAD

**Issue by lcdlyxrqy** [tensorflow/tensorflow#38824]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.1.0
- Python version: 3.7.7
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: Cuda 10.1 && cuDNN 7.6.5
- GPU model and memory: Nvidia Geforce GTX 950M 2G

**Describe the problem**
Actually, there is not much of a problem. I'm just wondering what are the necessary parts for tensorflow gpu to work. I guess a subset of CUDA runtime dynamic libraries, CUPTI, and cuDNN runtime dynamic library should suffice? However, I failed to find detailed information about this in the installation guide.

**Comment by Saduf2019** [comment]
@lcdlyxrqy 
could you please refer to these links for assistance:
[link1](https://www.tensorflow.org/install/gpu)
[link2](https://blog.quantinsti.com/install-tensorflow-gpu/)
please proceed with he installation and in case you face any issues you may create a issue/let us know on the same with all the details.

**Comment by lcdlyxrqy** [comment]
> @lcdlyxrqy
> could you please refer to these links for assistance:
> [link1](https://www.tensorflow.org/install/gpu)
> [link2](https://blog.quantinsti.com/install-tensorflow-gpu/)
> please proceed with he installation and in case you face any issues you may create a issue/let us know on the same with all the details.

Well, I'm not actually facing an installation issue. I just want to know which of CUDA toolkit components are necessary for tensorflow gpu to work. It could be useful when I'm trying to use tensorflow on some storage-limited machines since the CUDA and cuDNN dll libraries are quite large, even with the development tools, documentations, etc., already excluded. I've read through the installation guide already but no luck there. Are all those CUDA runtime libraries (.dll) really needed, or is there only a subset (say, only cudart64_XXX.dll) is needed?

**Comment by ozett** [comment]
answer to last question is still of great interest, as it is kind of nightmare to find working combinations of driver/cuda/cudnn for ubuntu 16/18/20 to run latest tensorflow 2.2

anybody of the dev know what minimal install packages of cuda are needed for tensorflow 2.2?
i assume the packages are already her in this repo to find:
https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/

thx, greatly appreciate some reaktion

**Comment by sanatmpa1** [comment]
@lcdlyxrqy,

Please take a look at this [link](https://www.tensorflow.org/install/gpu) which provides a detailed guide on installation with GPU support along with pre requisites, and [link](https://www.tensorflow.org/install/source#gpu) which provides the compatible version of CUDA and CUDNN version for each versions of `Tensorflow`. Let me know if it helps. Thanks!

**Comment by ozett** [comment]
One Year for that answer? really.
Anyway. Thanks. i will look it up.
