### ISSUE TITLE
dynamic_rnn time_major=False does not support rank>3 input

### ISSUE THREAD

**Issue by hhexiy** [tensorflow/tensorflow#3882]
https://github.com/tensorflow/tensorflow/blob/33b336ada58529d5e0398feea423785f1c3d57c1/tensorflow/python/ops/rnn.py#L782

```
flat_input = tuple(array_ops.transpose(input_, [1, 0, 2])
for input_ in flat_input)
```

Here seems we can only transpose matrix of size batch_size \* time_size \* input_size. It doesn't work if my input at each time step is a matrix.
In torch you can just specify the two dimensions (0 and 1 here) to be swapped instead of perm. Is there a similar functionality?

**Comment by ebrevdo** [comment]
It wouldn't be too hard to add support for a permutation of only the first two dimensions.  Are you interested in adding this?  If not, I'll try to work on it later this week.

**Comment by ankush-me** [comment]
Ran into this. The following fix works:

```
 flat_input = tuple(array_ops.transpose(input_, [1, 0] + [i for i in xrange(2,input_.get_shape().ndims)])
                       for input_ in flat_input)
```
and, similarly for [Line 843](https://github.com/tensorflow/tensorflow/blob/33b336ada58529d5e0398feea423785f1c3d57c1/tensorflow/python/ops/rnn.py#L843):
```
      flat_output = [array_ops.transpose(output, [1, 0] + [i for i in xrange(2,output.get_shape().ndims)])
                     for output in flat_output]
```

**Comment by ebrevdo** [comment]
Commented on the PR.
