### ISSUE TITLE
 'module' object has no attribute 'tf'

### ISSUE THREAD

**Issue by rezamansourian77** [tensorflow/tensorflow#38838]
its part of my code:

```
    def call(self, inputs):
        s = K.tf.gather(inputs[0], self.sel_inds[0], axis=1)
        p = K.tf.gather(inputs[1], self.sel_inds[1], axis=1)
        o = K.tf.gather(inputs[2], self.sel_inds[2], axis=1)
        return s*p*o
```

and then : 

```
  File "/content/VidVRD-helper-master/baseline/model.py", line 177, in call
    s = K.tf.gather(inputs[0], self.sel_inds[0], axis=1)
AttributeError: 'module' object has no attribute 'tf'
```

I use tensorflow=1.8.0 python=2.7
what should I do for fix it?

**Comment by mihaimaruseac** [comment]
TensorFlow 1.8 is too old. Please switch to 1.15, 2.0, 2.1 or the rc for 2.2.

If the problem still manifests, please fill in issue template and show output of `pip list`

When posting code, please use proper markdown formatting.

**Comment by mihaimaruseac** [comment]
You also seem to get TF from keras (`K`). This is no longer a pattern that's recommended.

**Comment by rezamansourian77** [comment]
> You also seem to get TF from keras (`K`). This is no longer a pattern that's recommended.

is it correct? 
`
    def call(self, inputs):
        s = tf.gather(inputs[0], self.sel_inds[0], axis=1)
        p = tf.gather(inputs[1], self.sel_inds[1], axis=1)
        o = tf.gather(inputs[2], self.sel_inds[2], axis=1)
        return s*p*o
`

**Comment by rezamansourian77** [comment]
> You also seem to get TF from keras (`K`). This is no longer a pattern that's recommended.

is it correct?

       def call(self, inputs):
        s = K.tf.gather(inputs[0], self.sel_inds[0], axis=1)
        p = K.tf.gather(inputs[1], self.sel_inds[1], axis=1)
        o = K.tf.gather(inputs[2], self.sel_inds[2], axis=1)
        return s*p*o

**Comment by rezamansourian77** [comment]
> You also seem to get TF from keras (`K`). This is no longer a pattern that's recommended.

is it correct?

       def call(self, inputs):
        s = tf.gather(inputs[0], self.sel_inds[0], axis=1)
        p = tf.gather(inputs[1], self.sel_inds[1], axis=1)
        o = tf.gather(inputs[2], self.sel_inds[2], axis=1)
        return s*p*o

**Comment by ravikyram** [comment]
@rezamansourian77 

Will it be possible to share simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!
