### ISSUE TITLE
NotFoundError: No registered 'AssignSubVariableOp' OpKernel for 'GPU' devices compatible with node {{node AssignSubVariableOp}}

### ISSUE THREAD

**Issue by hustarbor** [tensorflow/tensorflow#38841]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
`no`
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
`windows10 x64`
- TensorFlow installed from (source or binary):
`anaconda`
- TensorFlow version (use command below):
`2.1.0`
- Python version:
`3.7.7`
- CUDA/cuDNN version:
`10.1 update2`
- GPU model and memory:
`gtx1050ti 4GB`

import tensorflow as tf
print(tf.version.GIT_VERSION, tf.version.VERSION)"

result:unknown 2.1.0

**Describe the current behavior**
see the code 

**Describe the expected behavior**
see the error

**Standalone code to reproduce the issue**
cmd：
```
conda create -n tf2g python=3.7
conda activate tf2g
conda install tensorflow-gpu spyder
spyder
```
spyder:
```
import tensorflow as tf

epoch = 2

x = tf.Variable([[0. + 0.j]], tf.complex128)
y = tf.constant([[1. + 1.j]], tf.complex128)

#variables = [x]

for i in range(epoch):
    with tf.GradientTape() as tape:
        loss_value = (x - y)
    #print(loss_value)
    grad = tape.gradient(loss_value, x)
    #print(grad)
    x.assign_sub(0.1 * tf.math.conj(grad))

print(epoch)
```
debug:
```
runfile('E:/Projects/Python/tensorflow/temp/004/001.py', wdir='E:/Projects/Python/tensorflow/temp/004')
Traceback (most recent call last):

  File "E:\Projects\Python\tensorflow\temp\004\001.py", line 23, in <module>
    x.assign_sub(0.1 * tf.math.conj(grad))

  File "D:\ProgramData\Anaconda3\envs\tf2g\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py", line 762, in assign_sub
    name=name)

  File "D:\ProgramData\Anaconda3\envs\tf2g\lib\site-packages\tensorflow_core\python\ops\gen_resource_variable_ops.py", line 102, in assign_sub_variable_op
    _ops.raise_from_not_ok_status(e, name)

  File "D:\ProgramData\Anaconda3\envs\tf2g\lib\site-packages\tensorflow_core\python\framework\ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)

  File "<string>", line 3, in raise_from

NotFoundError: No registered 'AssignSubVariableOp' OpKernel for 'GPU' devices compatible with node {{node AssignSubVariableOp}}
	 (OpKernel was found, but attributes didn't match) Requested Attributes: dtype=DT_COMPLEX128
	.  Registered:  device='CPU'; dtype in [DT_INT64]
  device='CPU'; dtype in [DT_INT32]
  device='CPU'; dtype in [DT_UINT16]
  device='CPU'; dtype in [DT_INT16]
  device='CPU'; dtype in [DT_UINT8]
  device='CPU'; dtype in [DT_INT8]
  device='CPU'; dtype in [DT_HALF]
  device='CPU'; dtype in [DT_BFLOAT16]
  device='CPU'; dtype in [DT_FLOAT]
  device='CPU'; dtype in [DT_DOUBLE]
  device='CPU'; dtype in [DT_COMPLEX64]
  device='CPU'; dtype in [DT_COMPLEX128]
  device='GPU'; dtype in [DT_HALF]
  device='GPU'; dtype in [DT_FLOAT]
  device='GPU'; dtype in [DT_DOUBLE]
  device='GPU'; dtype in [DT_INT64]
 [Op:AssignSubVariableOp]
```

**Comment by hustarbor** [comment]
but the is no wrong with 
`conda install tensorflow spyder`

(not tensorflow-gpu)

**Comment by ravikyram** [comment]
@hustarbor 

Sorry, but we don't provide support for issues with the conda environment.This issue is more suitable for anaconda-issues repo. Please post it on anaconda-issues repo from [here](https://github.com/ContinuumIO/anaconda-issues/issues).Thanks!

**Comment by hustarbor** [comment]
> 
> 
> @hustarbor
> 
> Sorry, but we don't provide support for issues with the conda environment.This issue is more suitable for anaconda-issues repo. Please post it on anaconda-issues repo from [here](https://github.com/ContinuumIO/anaconda-issues/issues).Thanks!

Sorry, I think this may be the difference between A and B

**Comment by ravikyram** [comment]
I have tried in colab with TF 2.1 and was able to reproduce the issue. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/83f2cf35d7651673bb51c312e34676a8/untitled825.ipynb).Thanks!

**Comment by hustarbor** [comment]
> 
> 
> I have tried in colab with TF 2.1 and was able to reproduce the issue. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/83f2cf35d7651673bb51c312e34676a8/untitled825.ipynb).Thanks!

tf.Variable.assign_sub can't run on tensorflow-gpu

**Comment by gowthamkpr** [comment]
@hustarbor Yes thats the issue. In order to implement this op on your own on GPU please go through the following [doc](https://www.tensorflow.org/guide/create_op#gpu_kernels)

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 2 weeks. Please add additional comments for us to pen this issue again. Thanks!
