### ISSUE TITLE
ValueError: Could not interpret optimizer identifier (tf.keras) 

### ISSUE THREAD

**Issue by jayaBalaR** [tensorflow/tensorflow#38842]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- I have written a custom callback for learning_rate_scheduler in keras
- Code is running on Google Colaboratory:
- TensorFlow version (use command below): tensorflow 2.2.0-rc3.
I need to be able to set and get my learning_rate and other params in my optimizer,

 I need to be able to use the constructor of optimizer to set the parameters in it

Used the sample code in the keras documentation 
"Issue Reproducing steps"
1. Run this code in Google colab
from keras import optimizers

model = Sequential()
model.add(Dense(64, kernel_initializer='uniform', input_shape=(10,)))
model.add(Activation('softmax'))

sgd = optimizers.SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='mean_squared_error', optimizer=sgd)
2. Throws Deserialization error
3. Attaching the screenshot of the erro
4.Please help with a resolution/workaround for this issue, as i am working on a critical course assignment which I need to submit soon .
![error 2020-04-23 222914](https://user-images.githubusercontent.com/21074002/80129974-824ed280-85b5-11ea-9eac-5dd4791e8d6a.jpg)

Thanks

**Comment by oke-aditya** [comment]
I have tried the above and have got no error. Please have a look at this [link](https://colab.research.google.com/gist/oke-aditya/b6f1cc3c292e1703b4e878f8748282d4/test.ipynb)

**Comment by oke-aditya** [comment]
Maybe there is import issue or I have just changed the loss argument to "mse" (mean_squared_error).

**Comment by Saduf2019** [comment]
@jayaBalaR 
i ran the code shared in nightly and there are no errors, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/daa6959f58f5a3701e17c398077a56a8/38842-ipynbpip-install-tf_nightly.ipynb)
please confirm if the code provided is complete.

**Comment by jayaBalaR** [comment]
Hi @Saduf2019 , @oke-aditya 

Thank you for the quick resolution.
It was an import error. 
I am a novice programmer to Keras/Tensorflow . So I had to refer the Keras API documentation to code. 
After referring the documentation for optimizers section as detailed above, there was 
from keras import optimizers
and used the same import.

Could you please help to update documentation with the right import , so it could help other novice programmers not stuck with their development due to erroneous import .

Thank you for the resolution.

**Comment by oke-aditya** [comment]
Yes. Can you please provide link where it needs to be fixed?

**Comment by jayaBalaR** [comment]
Hi

This is the link https://keras.io/optimizers/
Refer the first section of code for optimizers.

Thanks once again.

**Comment by oke-aditya** [comment]
Tensorflow 2 uses Keras as high level API for model prototyping. Keras by itself is a different package. 

Keras API has their own documentation which is correct for their package. 

Tensorflow has its own documentation under tf.keras. Documentation issue of keras.io should be raised under Keras GitHub repository.

Please refer to tensorflow docs [docs link](https://www.tensorflow.org/overview)it would be easier to work with tensorflow. Mixing Keras docs with tensorflow while learning can lead confusion 😅. 

All the best. We all are new someday to Deep Learning. You will master it soon.

**Comment by jayaBalaR** [comment]
Okay thank you for the link  and for the clarification.

**Comment by Saduf2019** [comment]
@jayaBalaR 
please let us know if this is still an issue

**Comment by jayaBalaR** [comment]
@Saduf2019 . So far resolved. Thank you

**Comment by Saduf2019** [comment]
moving to resolved status with confirmation
