### ISSUE TITLE
Issues #2099 has become a problem again: using empty variables

### ISSUE THREAD

**Issue by liuyipei** [tensorflow/tensorflow#3885]
The code below fails with "Attempting to use uninitialized value Variable".  See #2099. I presume that this was fixed in the past but regressed subsequently. I understand that the past stance was that it is fine to use variables with shapes that contain a 0 in one of the dimensions.
```
sess = tf.InteractiveSession()
empty = np.zeros(shape=(0, 0) )
a = tf.Variable(empty)
sess.run(tf.initialize_all_variables())
sess.run(tf.reduce_sum(a))
```

**Comment by aselle** [comment]
@allenlavoie, didn't you look at this before?

**Comment by allenlavoie** [comment]
Yes, we tried to fix exactly this case, and it seems to still be working for me. Andrew has confirmed that your code also works in .10 RC0; can you try that version and see if you still have an issue?

**Comment by liuyipei** [comment]
Works in 0.10rc0. Thanks! fwiw, I was on 0.8.
