### ISSUE TITLE
Issues creating Frozen_graph for this model

### ISSUE THREAD

**Issue by alecda573** [tensorflow/tensorflow#38851]
I am using Windows 10
Tensorflow v 1.14

I am trying to create a frozen graph for the checkpoint data in the following gitrepo:
https://github.com/una-dinosauria/3d-pose-baseline 
using the code below:
`
with tf.Session() as sess:
    
    saver=tf.train.import_meta_graph(meta_path)
    
    saver.restore(sess,'C:\\Users\\alecd\\3d-pose-baseline\\checks\\checkpoint-4874200.meta')
    
    frozen_graph_def=tf.graph_util.convert_variables_to_constants(sess,sess.graph_def,output_node_names)
    
    with open('output_graph.pb', 'wb') as f:
        f.write(frozen_graph_def.SerializeToString())
    
`
Now, when I would try to serve the model in python I would get the following error: 

`
ValueError: Input 0 of node learning_rate/Assign was passed float from learning_rate:0 incompatible with expected float_ref.
`

I thought that one of the possible issues was that I was not passing a specific output node so I decided to try and visualize the graph inside tensorboard using:

`
tf.train.import_meta_graph("checkpoint-4874200.meta")
for n in tf.get_default_graph().as_graph_def().node:
   print(n)
with tf.Session() as sess:
  writer = tf.summary.FileWriter("./output/", sess.graph)
  writer.close()
`
but when I would run
`
tensorboard --logdir=data/ --host localhost --port 8088
`
I get a tensorboard page with no information which made me start to wonder whether or not the meta graph was corrupted or something else was going on. 

Just looking for general advice and or help here if anyone has any idea as to what is going on?

As a side note the frozen_graph I created can be found at 
https://github.com/alecda573/frozen_graph

**Comment by amahendrakar** [comment]
@alecda573,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by alecda573** [comment]
@amahendrakar  I did provide the full code more or less. To reiterate, I am trying to convert the following checkpoint data to a frozen graph: https://drive.google.com/file/d/0BxWzojlLp259MF9qSFpiVjl0cU0/view

The code I am using to freeze the graph is the following: 

`
trained_checkpoint_prefix='checkpoint-4874200'
export_dir=os.path.join('export_dir')
graph=tf.Graph()

with tf.Session(graph=graph) as sess:
    #Restore from checkpoint
    loader=tf.train.import_meta_graph(trained_checkpoint_prefix+'.meta')
    loader.restore(sess,trained_checkpoint_prefix)
    
    builder=tf.saved_model.builder.SavedModelBuilder(export_dir)
    builder.add_meta_graph_and_variables(sess,
                                         [tf.saved_model.SERVING],
                                         strip_default_attrs=True)
    
    
    builder.save()  
    builder.save(as_text=True)
    
    frozen_graph_def=tf.graph_util.convert_variables_to_constants(sess,sess.graph_def,[n.name for n in tf.get_default_graph().as_graph_def().node])
    
    output=[n.name for n in tf.get_default_graph().as_graph_def().node]
    print(len(output))
    print(output)
    with open('frozen_graph.pb','wb') as f:
        f.write(frozen_graph_def.SerializeToString())
        
`
If I try to serve this model in python I end up getting 

`
ValueError: Input 0 of node learning_rate/Assign was passed float from learning_rate:0 incompatible with expected float_ref.
`

Also, when I try to view the graph using tensorboard, by importing the meta graph no data is written to tensorboard. The code I am using to write to tensorboard is:
`
tf.train.import_meta_graph("checkpoint-4874200.meta") 
for n in tf.get_default_graph().as_graph_def().node: 
print(n) 
with tf.Session() as sess: 
writer = tf.summary.FileWriter("./output/", sess.graph) writer.close()
`
and then I call using the following command in my terminal:
`
tensorboard --logdir=data/ --host localhost --port 8088
`

If you want to see the frozen graph I generated (but cannot serve) it can be found at:
https://github.com/alecda573/frozen_graph

Thanks in advance for your help.

**Comment by alecda573** [comment]
@amahendrakar Then try to serve the model using: 

    import tensorflow as tf
    import sys
    from tensorflow.python.platform import gfile

    from tensorflow.core.protobuf import saved_model_pb2
    from tensorflow.python.util import compat
    with tf.Session() as persisted_sess:
         print("load graph")
         with gfile.FastGFile("frozen_graph.pb",'rb') as f:
            graph_def = tf.GraphDef()
            graph_def.ParseFromString(f.read())
            persisted_sess.graph.as_default()
    tf.import_graph_def(graph_def, name='')
    writer = tf.summary.FileWriter("./tf_summary", graph=persisted_sess.graph)
    # Print all operation names
    for op in persisted_sess.graph.get_operations():
      print(op)
    # next: do the following in bash:
    # tensorboard --logdir ./tf_summary/
