### ISSUE TITLE
Wrong description in Digit classifier : Tensorflow Lite examples

### ISSUE THREAD

**Issue by akash123mandal** [tensorflow/tensorflow#38859]
## Description of issue:
The digit classifier example card has the wrong description : 
"Generate reply suggestions to input conversational chat messages."

## Screenshot

![image](https://user-images.githubusercontent.com/23613193/80188049-4441c500-862e-11ea-998d-b66c246de3d2.png)

**Comment by lamberta** [comment]
Thanks. Filed an internal issue: b/154952252

**Comment by ymodak** [comment]
This has been fixed now. Thanks!
