### ISSUE TITLE
Tensorflow lite for unity

### ISSUE THREAD

**Issue by Pallav56** [tensorflow/tensorflow#38857]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.14
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 1.1.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: Tesla K80/ 12GB

**Describe the problem**
Not able to find libraries while building tensorflow lite for unity

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build -c opt --config android_arm64 --copt -Os --copt -DTFLITE_GPU_BINARY_RELEASE --copt -fvisibility=hidden --linkopt -s --strip always //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

ERROR: Skipping '//tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so': no such target '//tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so': target 'libtensorflowlite_gpu_delegate.so' not declared in package 'tensorflow/lite/delegates/gpu' defined by /home/ubuntu/tf_1.14/tensorflow/tensorflow/lite/delegates/gpu/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so': target 'libtensorflowlite_gpu_delegate.so' not declared in package 'tensorflow/lite/delegates/gpu' defined by /home/ubuntu/tf_1.14/tensorflow/tensorflow/lite/delegates/gpu/BUILD

**Comment by thaink** [comment]
You are using a too old version of tensorflow source code. The target you are trying to build is not there at that version.
Could you tried to use a recent version?

**Comment by Pallav56** [comment]
Thanks Thaink,

Request you to please specify to which version of TF you are referring to as i have used 1.14 version of TF.

**Comment by thaink** [comment]
Hi @Pallav56 
I would recommend to use our latest version 2.1.0

**Comment by thaink** [comment]
Hi @Pallav56
Can you close this issue if it is solved?
