### ISSUE TITLE
[CPU] Best CPU Build found with MKL config in bazel build BUT with MKL Disabled in script, especially on LSTM, can't undestand why

### ISSUE THREAD

**Issue by NicolasVidal** [tensorflow/tensorflow#38858]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): Build from source
- TensorFlow version (use command below): 2.1.0
- Python version: 3.8
- Bazel version (if compiling from source): 0.27.1
- GCC/Compiler version (if compiling from source): msvc2019
- CUDA/cuDNN version: -
- GPU model and memory: -

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Hello there, I'm trying to find one of the best possible build option config while build tensorflow from source on my computers.

First I thought (as my two coputers are using i7 CPUs) building with MKL was the best option. But tuning correctly intra and inter op thread is hard because it really depends on the model used and the size of data used.

I created a micro benchmark (not really great I admit) but I found some huge discrepencies between build config options AND between Defines while running the script. I'm only benchmarking inference.

All builds were using /arch:AVX2

Here are the results of the microbenchmark with each build config options and define pairs :

### Build Command (With MKL) :
```
bazel --output_base=output_dir build --define=no_tensorflow_py_deps=true --config=v2 --config=mkl --config=opt -c opt --copt="/Ob3" --copt="/fp:fast" --copt="/O2"  //tensorflow/tools/pip_package:build_pip_package
```
### Define Config (MKL Disabled)
```
os.environ['TF_DISABLE_MKL'] = '1'
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '1' 

tf.compat.v1.disable_eager_execution()
```
### Results
```
Big Dense pass 1 : it took 10.544710159301758 seconds
Big Dense pass 2 : it took 9.63374948501587 seconds
Big Dense pass 3 : it took 9.610066175460815 seconds
Xception pass 1 : it took 5.660003900527954 seconds
Xception pass 2 : it took 5.289057493209839 seconds
Xception pass 3 : it took 5.238063812255859 seconds
LSTM pass 1 : it took 10.222216606140137 seconds
LSTM pass 2 : it took 8.22239375114441 seconds
LSTM pass 3 : it took 8.210553884506226 seconds
LSTM unrolled pass 1 : it took 14.414194822311401 seconds
LSTM unrolled  pass 2 : it took 7.88745903968811 seconds
LSTM unrolled pass 3 : it took 8.34917140007019 seconds
Linear Model pass 1 : it took 1.0033559799194336 seconds
Linear Model pass 2 : it took 0.0069768428802490234 seconds
Linear Model pass 3 : it took 0.010947227478027344 seconds
Linear Model small data pass 1 : it took 1.0467493534088135 seconds
Linear Model small data pass 2 : it took 0.08178114891052246 seconds
Linear Model small data pass 3 : it took 0.15857625007629395 seconds
```

### Build Command (with MKL) :
```
bazel --output_base=output_dir build --define=no_tensorflow_py_deps=true --config=v2 --config=mkl --config=opt -c opt --copt="/Ob3" --copt="/fp:fast" --copt="/O2"  //tensorflow/tools/pip_package:build_pip_package
```
### Define Config (MKL Enabled)
```
#os.environ['TF_DISABLE_MKL'] = '1'
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '1' 

tf.compat.v1.disable_eager_execution()
```
### Results
```
Big Dense pass 1 : it took 13.546119928359985 seconds
Big Dense pass 2 : it took 12.425012588500977 seconds
Big Dense pass 3 : it took 12.265166759490967 seconds
Xception pass 1 : it took 16.793854475021362 seconds
Xception pass 2 : it took 15.786102056503296 seconds
Xception pass 3 : it took 15.787992000579834 seconds
LSTM pass 1 : it took 10.035675525665283 seconds
LSTM pass 2 : it took 8.080043315887451 seconds
LSTM pass 3 : it took 7.926990509033203 seconds
LSTM unrolled pass 1 : it took 20.55500102043152 seconds
LSTM unrolled  pass 2 : it took 7.7295191287994385 seconds
LSTM unrolled pass 3 : it took 7.706652879714966 seconds
Linear Model pass 1 : it took 1.0731301307678223 seconds
Linear Model pass 2 : it took 0.007978677749633789 seconds
Linear Model pass 3 : it took 0.01296544075012207 seconds
Linear Model small data pass 1 : it took 1.1389260292053223 seconds
Linear Model small data pass 2 : it took 0.07978606224060059 seconds
Linear Model small data pass 3 : it took 0.1665961742401123 seconds
```

### Build Command (Without MKL)
```
bazel --output_base=output_dir build --define=no_tensorflow_py_deps=true --config=v2 --config=opt -c opt --copt="/Ob3" --copt="/fp:fast" --copt="/O2"  //tensorflow/tools/pip_package:build_pip_package
```
### Define Config (MKL Disabled/Enabled should not matter as there it is not an MKL build)
```
os.environ['TF_DISABLE_MKL'] = '1'
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '1' 

tf.compat.v1.disable_eager_execution()
```
### Results
```
Big Dense pass 1 : it took 10.71854853630066 seconds
Big Dense pass 2 : it took 9.549690961837769 seconds
Big Dense pass 3 : it took 9.396085262298584 seconds
Xception pass 1 : it took 5.693288326263428 seconds
Xception pass 2 : it took 5.287402391433716 seconds
Xception pass 3 : it took 5.261985540390015 seconds
LSTM pass 1 : it took 22.114120721817017 seconds
LSTM pass 2 : it took 20.470056772232056 seconds
LSTM pass 3 : it took 20.77280902862549 seconds
LSTM unrolled pass 1 : it took 27.426076889038086 seconds
LSTM unrolled  pass 2 : it took 21.209628105163574 seconds
LSTM unrolled pass 3 : it took 21.19388747215271 seconds
Linear Model pass 1 : it took 1.0153882503509521 seconds
Linear Model pass 2 : it took 0.007978439331054688 seconds
Linear Model pass 3 : it took 0.010976552963256836 seconds
Linear Model small data pass 1 : it took 1.046147108078003 seconds
Linear Model small data pass 2 : it took 0.08078360557556152 seconds
Linear Model small data pass 3 : it took 0.1626284122467041 seconds
```

What we see is : 
- on XCeption model, MKL Enabled run is very slow, and any amount of intra/extra threads config didn't manage to put these numbers down
- without BUILDING with MKL, LSTM benches are very slow !

**Describe the expected behavior**

I can't undestand why the best results were obtained with building with MKL **enabled** in build and then **disabling** its usage via script.

By the way when installing tensorflow via pip, we observe the same behaviour (bad results on LSTM) and performance is a little bit worse on all other benchmarks (as it is not build with AVX2 and other optimisation flags I guess)

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

The benchmark naive code is attached below :
[bench.zip](https://github.com/tensorflow/tensorflow/files/4527325/bench.zip)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Naveen3Singh** [comment]
@NicolasVidal Do you have any update on this issue? I'm facing the same problem on intel. Official wheels with mkl enabled are very slow for LSTM networks.

**Comment by mohantym** [comment]
Hi @NicolasVidal , 
Could you please try on latest stable version TF 2.6  and let us know if this is still an issue.Thanks!
