### ISSUE TITLE
tf.ragged.stack may return tf.Tensor instead of tf.RaggedTensor

### ISSUE THREAD

**Issue by ngc92** [tensorflow/tensorflow#38862]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Mint
- TensorFlow installed from (source or binary): conda
- TensorFlow version (use command below): unknown 2.1.0
- Python version: 3.7

**Describe the current behavior**
A call like 
```
print(tf.ragged.stack([tf.constant(5)], axis=0))
>>> tf.Tensor([5], shape=(1,), dtype=int32)
```
returns a `tf.Tensor` instead of a `RaggedTensor`

**Describe the expected behavior**
According to the documentation, the result should be a `RaggedTensor`. One might consider this a documentation error, but I think the return type of this function should not change depending on the values that are stacked.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
import tensorflow as tf
print(tf.ragged.stack([tf.constant(5)], axis=0))
```

**Comment by Saduf2019** [comment]
@ngc92 
i ran the code shared by you, please find the gist of [error faced](https://colab.sandbox.google.com/gist/Saduf2019/b6be3b971405f38e3c4f7b689d4f6a81/untitled152.ipynb)

**Comment by ngc92** [comment]
maybe I'm blind, but doesn't the gist show exactly what I claimed it would, i.e. a return type which is not a `RaggedTensor`? I'm not sure which error you mean.

**Comment by edloper** [comment]
With the current ragged tensor implementation, there is no such thing as a 1D (or 0D) ragged tensor.  In particular, each RaggedTensor wraps a “values” tensor (which must be at least 1D) and a “row partitioning tensor” that describes how the outermost dimension of values should be partitioned into rows.

**Comment by edloper** [comment]
For more details see https://www.tensorflow.org/guide/ragged_tensor#raggedtensor_encoding. 

You said “ According to the documentation, the result should be a RaggedTensor.” which documentation are you referring to?

**Comment by ngc92** [comment]
https://www.tensorflow.org/api_docs/python/tf/ragged/stack
```
Returns: A RaggedTensor with rank R+1. result.ragged_rank=1+max(axis, max(rt.ragged_rank for rt in values])).
```

**Comment by rmothukuru** [comment]
@ngc92,
Sorry for the delayed response. The [Example Code](https://www.tensorflow.org/api_docs/python/tf/ragged/stack#examples) mentioned in documentation returns a **`Ragged Tensor`**, which is line with [the documentation](https://www.tensorflow.org/api_docs/python/tf/ragged/stack#returns) provided. 

Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/9a6a789d7adc9e746535129ba9f6e3e7/gh_38862.ipynb) of the working code. Thanks!
