### ISSUE TITLE
Error : tf.compat.v1.resource_loader.get_path_to_datafile

### ISSUE THREAD

**Issue by akshat-suwalka** [tensorflow/tensorflow#38865]
While implementing this code:
import tensorflow as tf

_flow_warp_ops = tf.load_op_library(
    tf.compat.v1.resource_loader.get_path_to_datafile("./lib/flow_warp.so"))

def flow_warp(image, flow):
    return _flow_warp_ops.flow_warp(image, flow)

@tf.RegisterGradient("FlowWarp")
def _flow_warp_grad(flow_warp_op, gradients):
    return _flow_warp_ops.flow_warp_grad(flow_warp_op.inputs[0],
                                         flow_warp_op.inputs[1],
                                         gradients)

I got the following error:

Traceback (most recent call last):

  File "/home/akshat_suwalka/Fully-Automatic-Video-Colorization-with-Self-Regularization-and-Diversity-master/flow_warp.py", line 4, in <module>
    tf.compat.v1.resource_loader.get_path_to_datafile("./lib/flow_warp.so"))

  File "/home/akshat_suwalka/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)

NotFoundError: libcudart.so.8.0: cannot open shared object file: No such file or directory

I am not able to deal with this error.
Can anyone help?

**Comment by ravikyram** [comment]
@akshat-suwalka 

Request you to fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.Request you to share colab link or simple standalone code with proper indentation to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!
