### ISSUE TITLE
A problem about "bazel workspace"

### ISSUE THREAD

**Issue by fourierer** [tensorflow/tensorflow#38860]
I want to use "tensorflow/tensorflow/lite/tools/evaluation/tasks/imagenet_image_classification/run_eval.cc" to evaluate a .tflite model. I run the command "bazel run -c opt ......", but returned "ERROR: The 'run' command is only supported from within a workspace". What does workspace mean?

**Comment by ravikyram** [comment]
@fourierer 

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
