### ISSUE TITLE
Distribution algorithm has limited performance on CPU

### ISSUE THREAD

**Issue by Zantares** [tensorflow/tensorflow#38868]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): (Red Hat 4.8.5-16)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source build
- TensorFlow version (use command below): 2.1 
- Python version: 3.7.6
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): 7.4.0 
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
Random generator uses specific philox_4x32_10 algorithm. It will generate 4 elements per [call](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/random/random_distributions.h#L114) in Distribution and do additional computation for these 4 elements. Is there any special consideration for this design? As you know, 4 elements are not very friendly for CPU AVX feature, especial for those low precision type(Half, Bfloat16) w/o native instructs support, because **conversion** overhead will become obvious if we can't fulfill vectorization register, that will make bad overall performance for the [result](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/random/random_distributions.h#L764).

**Describe the expected behavior**
Is it possible to handle the **conversion** and **computation** out of the Distribution? I mean handle them in the place where is needed. For example, `RandomUniform` op calls Distribution [here ](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/random_op_cpu.h#L95) many times and we may handle data out of the Distribution and loop. The fake code is somehow like this
```C
// https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/random/random_distributions.h
// Helper function to convert an 16-bit integer to a half between [1..2).
PHILOX_DEVICE_INLINE Eigen::half NewUint16ToHalf(uint16 x) {
  // IEEE754 halfs are formatted as follows (MSB first):
  //    sign(1) exponent(5) mantissa(10)
  // Conceptually construct the following:
  //    sign == 0
  //    exponent == 15  -- an excess 15 representation of a zero exponent
  //    mantissa == 10 random bits
  const uint16 man = x & 0x3ffu;  // 10 bit mantissa
  const uint16 exp = static_cast<uint16>(15);
  const uint16 val = (exp << 10) | man;

  Eigen::half result;
  result.x = val;
  /***********************************************
      do not do the conversion and minus here.
      return result - Eigen::half(1.0);
  ************************************************/
  return result;
}

...
    // https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/random_op_cpu.h#L95
    gen.Skip(start_group);
    int64 offset = start_group * kGroupSize;

    // First fill all the full-size groups
    int64 limit_group_full = std::min(limit_group, size / kGroupSize);
    for (int64 index = start_group; index < limit_group_full; ++index) {
      /********************************************************
        Use new Distribution without conversion and minus
        auto samples = dist(&gen);
      *********************************************************/
      auto samples = new_dist(&gen);
      std::copy(&samples[0], &samples[0] + kGroupSize, data + offset);
      offset += kGroupSize;
    }
    /****************************************************************************
      Do the vector conversion and minus out of loop to get CPU AVX feature
    *****************************************************************************/
    new_dist.vectorize(start, length);
```

Is this kind optimization reasonable?

**Standalone code to reproduce the issue**
I made some simple test, low precision Distribution are usually slower 10~30%  with current implementation.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@Zantares 

Will it be possible to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by Zantares** [comment]
> @Zantares
> 
> Will it be possible to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

Ofc, I would like to share a performance UT in TF once I finished it.
BTW, there's better solution to solve this performance issue like to optimize Generator algorithm, but I think it's more complex.

**Comment by Zantares** [comment]
Please check UT in attachment, I ran it with cmd:
```
```

and got :
```
Executing tests from //tensorflow/core/kernels:random_op_test
-----------------------------------------------------------------------------
Running main() from test_main.cc
Benchmark                                  Time(ns) Iterations
--------------------------------------------------------------
BM_cpu_RandomUniform_DT_FLOAT/1048576       1276092        687	 821.7M items/s
BM_cpu_RandomUniform_DT_FLOAT/2097152       2364219        320	 887.0M items/s
BM_cpu_RandomUniform_DT_FLOAT/8388608       9888000        100	 848.4M items/s
BM_cpu_RandomUniform_DT_HALF/1048576        1455563        565	 720.4M items/s
BM_cpu_RandomUniform_DT_HALF/2097152        2887788        222	 726.2M items/s
BM_cpu_RandomUniform_DT_HALF/8388608       11319790        100	 741.1M items/s
BM_cpu_RandomUniform_DT_BFLOAT16/1048576    1839554        480	 570.0M items/s
BM_cpu_RandomUniform_DT_BFLOAT16/2097152    3642229        223	 575.8M items/s
BM_cpu_RandomUniform_DT_BFLOAT16/8388608   13337270        100	 629.0M items/s
```

One of the bottleneck is that I mentioned, low precision type will cost more on conversion in `Helper Function` of Distribution.
[ut_diff.txt](https://github.com/tensorflow/tensorflow/files/4549767/ut_diff.txt)

**Comment by Zantares** [comment]
We have figured out a generic optimization for this issue and submitted it here: https://github.com/tensorflow/tensorflow/pull/39747.

**Comment by rmothukuru** [comment]
@Zantares,
Sorry for the delayed response. Can you please confirm if we can close this issue as the [associated PR](https://github.com/tensorflow/tensorflow/pull/39747) has been merged? Thanks!

**Comment by Zantares** [comment]
> @Zantares,
> Sorry for the delayed response. Can you please confirm if we can close this issue as the [associated PR](https://github.com/tensorflow/tensorflow/pull/39747) has been merged? Thanks!

Thanks, this issue can be closed now.
