### ISSUE TITLE
Fit an Use the Keras scikit-learn wrapper with Generator dataset

### ISSUE THREAD

**Issue by eaedk** [tensorflow/tensorflow#38866]
**System information**
- TensorFlow version (you are using) : tf  2.2.0-rc3

- Are you willing to contribute it (Yes/No) : Yes

**Describe the feature and the current behavior/state.**
With the Keras scikit-learn wrapper, I want that the fit using generator dataset and generator validation dataset will be available. Actually its requires X,y like-arrays.

**Will this change the current api? How?**
It will extend the  Keras scikit-learn wrapper functionalities by permiting to use data augmentation using ImageGenarator.

**Who will benefit with this feature?**
Every Keras users that use the wrapper for Computer Vision.

**Any Other info.**
It will be useful for memory efficiency usage also.

**Comment by gowthamkpr** [comment]
Keras scikit-learn is deprecated and we are no longer maintaining/bug fixing it. Please forward this issue to https://github.com/adriangb/scikeras.
