### ISSUE TITLE
K.in_train_phase() broken in eager mode when used outside of Lambda layer

### ISSUE THREAD

**Issue by sokrypton** [tensorflow/tensorflow#38877]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow version (use command below): 2.2.0-rc3 (v2.2.0-rc3-0-gaad398b5e9)
- Python version: 3.0

**Describe the current behavior**
K.in_train_phase(). It always returns the alternative option (both during model.fit() and model.predict() in keras).  But it does work when you disable eager mode or when you wrap it in a Lambda layer. This is unexpected because in TF1 and when eager is disabled the function works as expected.

**Describe the expected behavior**
I would expect K.in_train_phase() to work as described in the documentation.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1yaw-UhOgj7UyLC4NEtQPYiZRYvnxhz_G

**Comment by Saduf2019** [comment]
i am able to replicate the issue please find the[ gist here](https://colab.sandbox.google.com/gist/Saduf2019/e42e9f9409902a15edef04ef4eb9b3b2/38870.ipynb)

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue in TF 2.5 on colab. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/0014965a7a05fffd2b118708f0788233/untitled.ipynb).

**Comment by klanderson** [comment]
When you run the colab above (TF 2.11) it still is reproducing the issue
