### ISSUE TITLE
Creating multiple stacked variable within tf.map_fn  

### ISSUE THREAD

**Issue by ammarabbasali** [tensorflow/tensorflow#38876]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.10
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Currently, I am trying to create multiple variables within tf.map_fn but it just creates a single variable copied multiple times.

**Will this change the current api? How?**
Maybe

**Who will benefit with this feature?**
Projects related to multi-object tracking

**Any Other info.**

**Comment by ravikyram** [comment]
Do you have any use case that requires the feature you are interested in? .Please, share the related code.Thanks!

**Comment by ammarabbasali** [comment]
HI RaviKyram, 

Thank you for your response, I am trying to use RT-MDNet (Real-Time_Multi- Domain Network) to achieve multi-object tracking. for that, I am trying to create a higher rank weight matrix stacked over one another depending on the number of objects detected. Currently, I was able to create multiple variables outside the graph but now I am trying to stack them and pass it to the last fully connected layer:

```
for n_obj in range(pos_data.shape[0]):
        W6 = tf.get_variable("fc6/kernel-" + str(n_obj), shape=(1, 512, 1),
                             initializer=tf.contrib.layers.xavier_initializer())

prob, train_op, accuracy, loss, pred, initialize_vars, y, fc6 = build_branches(fc5, W6)

def build_branches(fc5, n_obj):
    y = tf.placeholder(tf.int64, [None, None])


    with tf.variable_scope("fc6", reuse=tf.AUTO_REUSE):
        b6 = tf.get_variable('bias', shape=(1, 1, 1), initializer=tf.zeros_initializer())

    fc6 = tf.add(tf.matmul(fc5, W6), b6)

    loss = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y,
                                                                         logits=fc6))

    train_vars = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, scope="fc6")

    with tf.variable_scope("",  reuse=tf.AUTO_REUSE):

        optimizer = tf.train.AdamOptimizer(learning_rate=0.001, name='adam')
        train_op = optimizer.minimize(loss, var_list=train_vars)


        initialize_vars = train_vars
        initialize_vars += [optimizer.get_slot(var, name)
                            for name in optimizer.get_slot_names()
                            for var in train_vars]
        if isinstance(optimizer, tf.train.AdamOptimizer):
            initialize_vars += optimizer._get_beta_accumulators()

    prob = tf.nn.softmax(fc6)
    pred = tf.argmax(prob, 2)
    correct_pred = tf.equal(pred, y)

    accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))

    return prob, train_op, accuracy, loss, pred, initialize_vars, y, fc6

```
I was able to create multiple branches but what I want is a single branch incorporating all the created variables stacked before the matmul operation on fc6 tensor.

![multi-task_kernel](https://user-images.githubusercontent.com/28593585/80916940-1d853c00-8d5c-11ea-9187-de659ad36f83.png)

**Comment by ammarabbasali** [comment]
here is an update to the issue, I was able to generate the multiple kernels outside the graph in a for loop and then giving it to the graph:

```
    w6 = []
    for n_obj in range(pos_data.shape[0]):
        w6.append(tf.get_variable("fc6/kernel-" + str(n_obj), shape=(512, 2),
                             initializer=tf.contrib.layers.xavier_initializer()))

    print("modeling fc6 branches...")
    prob, train_op, accuracy, loss, pred, initialize_vars, y, fc6 = build_branches(fc5, w6)

def build_branches(fc5, w6):
    y = tf.placeholder(tf.int64, [None, None])

    b6 = tf.get_variable('fc6/bias', shape=2, initializer=tf.zeros_initializer())

    fc6 = tf.add(tf.matmul(fc5, w6), b6)

    loss = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y,
                                                                         logits=fc6))

    train_vars = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, scope="fc6")

    with tf.variable_scope("",  reuse=tf.AUTO_REUSE):

        optimizer = tf.train.AdamOptimizer(learning_rate=0.001, name='adam')
        train_op = optimizer.minimize(loss, var_list=train_vars)

        initialize_vars = train_vars
        initialize_vars += [optimizer.get_slot(var, name)
                            for name in optimizer.get_slot_names()
                            for var in train_vars]
        if isinstance(optimizer, tf.train.AdamOptimizer):
            initialize_vars += optimizer._get_beta_accumulators()

    prob = tf.nn.softmax(fc6)
    pred = tf.argmax(prob, 2)
    correct_pred = tf.equal(pred, y)

    accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))

    return prob, train_op, accuracy, loss, pred, initialize_vars, y, fc6
```

![concatenated_kernel_multi-task](https://user-images.githubusercontent.com/28593585/80975139-001aa580-8e22-11ea-80e7-9b2fe19da13c.png)

Now I want to figure out a way to delete the kernels for the object that is lost during the tracking. I guess that is not possible after the graph generation.

**Comment by alextp** [comment]
Please ask this type of question on StackOverflow as it's not a TF bug.
