### ISSUE TITLE
tf.fill should accept dtype argument

### ISSUE THREAD

**Issue by rizar** [tensorflow/tensorflow#3887]
The signature of `tf.fill` is  `tf.fill(dims, value, name=None)`, which not does allow to configure the dtype of the result. As opposed to `tf.ones`, `tf.ones(shape, dtype=tf.float32, name=None)`.

Shouldn't `tf.fill` also accept a dtype argument?

**Comment by yaroslavvb** [comment]
What would be the behavior when dtype of value conflicts with explicit
dtype?

**Comment by vrv** [comment]
Yes, I think the dtype of 'value' determines the output type, so either make sure 'value' is the right dtype, or you can use tf.cast afterwards.
