### ISSUE TITLE
tf.compat.v1.resource_loader.get_path_to_datafile

### ISSUE THREAD

**Issue by akshat-suwalka** [tensorflow/tensorflow#38885]
I had implemented this code:

import tensorflow as tf

_flow_warp_ops = tf.load_op_library(
    tf.compat.v1.resource_loader.get_path_to_datafile("./lib/flow_warp.so"))

But it is showing error:

Traceback (most recent call last):

  File "<ipython-input-12-d0892143bf54>", line 2, in <module>
    tf.compat.v1.resource_loader.get_path_to_datafile("./lib/flow_warp.so"))

  File "/home/akshat_suwalka/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)

NotFoundError: libcudart.so.8.0: cannot open shared object file: No such file or directory

As you can see that file already i have in "lib/flow_warp.so"
![Screenshot from 2020-04-25 14-05-38](https://user-images.githubusercontent.com/35618437/80275290-e9779e80-86fd-11ea-94d4-00dfd3bd30a1.png)

**Comment by Saduf2019** [comment]
@akshat-suwalka 
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by akshat-suwalka** [comment]
I am using ubuntu 16.04 LTS
Tensorflow is the latest version as I had installed day before yesterday.

**Comment by akshat-suwalka** [comment]
In anaconda i had installed all the latest packages on that day including cudatoolkit, cudnn.
libcudart.so.8.0 is showing bcz i dont have cuda 8.0 version.
If it is show then i search here: https://repo.anaconda.com/pkgs/main/linux-64/
where all the packages are available for linux but here i didn't find cuda 8.0 version.

Is there any possibility to run that code in latest version of cuda??
Any suggestion what should i do to resolve this problem?

**Comment by gowthamkpr** [comment]
@akshat-suwalka What version of CUDA are you using?
