### ISSUE TITLE
Tensorflow.Contrib Not Found

### ISSUE THREAD

**Issue by dhruv-colosus** [tensorflow/tensorflow#38882]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Pip installed
- TensorFlow version:2.2.0
- Python version:3.8.2 64 Bit
- Installed using virtualenv? pip? conda?: Pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:No graphic Card
- GPU model and memory: ---

I am using Tflearn library which uses Tensorflow.contrib as a module. But It is showing error that it has no library as such
The stack code is here
2020-04-25 09:45:43.517997: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-04-25 09:45:43.525381: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on
your machine.
Traceback (most recent call last):
  File "f:/MACHINE LEARNING/chatbot/main.py", line 10, in <module>
    import tflearn
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\tflearn\__init__.py", line 4, in <module>
    from . import config
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\tflearn\config.py", line 5, in <module>
    from .variables import variable
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\tflearn\variables.py", line 7, in <module>
    from tensorflow.contrib.framework.python.ops import add_arg_scope as contrib_add_arg_scope
ModuleNotFoundError: No module named 'tensorflow.contrib'

I just imported Tflearn and Tensorflow and no code was written.

**Comment by himanivatyani** [comment]
Tensorflow.contrib is not present in Tensorflow v2.
Try downgrading your version to 1.4 or below.

**Comment by himanivatyani** [comment]
> **System information**
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
> * TensorFlow installed from (source or binary): Pip installed
> * TensorFlow version:2.2.0
> * Python version:3.8.2 64 Bit
> * Installed using virtualenv? pip? conda?: Pip
> * Bazel version (if compiling from source):
> * GCC/Compiler version (if compiling from source):
> * CUDA/cuDNN version:No graphic Card
> * GPU model and memory: ---
> 
> I am using Tflearn library which uses Tensorflow.contrib as a module. But It is showing error that it has no library as such
> The stack code is here
> 2020-04-25 09:45:43.517997: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
> 2020-04-25 09:45:43.525381: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on
> your machine.
> Traceback (most recent call last):
> File "f:/MACHINE LEARNING/chatbot/main.py", line 10, in
> import tflearn
> File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\tflearn__init__.py", line 4, in
> from . import config
> File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\tflearn\config.py", line 5, in
> from .variables import variable
> File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\tflearn\variables.py", line 7, in
> from tensorflow.contrib.framework.python.ops import add_arg_scope as contrib_add_arg_scope
> ModuleNotFoundError: No module named 'tensorflow.contrib'
> 
> I just imported Tflearn and Tensorflow and no code was written.

Tensorflow.contrib is not present in Tensorflow v2.
Try downgrading your version to 1.4 or below.

**Comment by Saduf2019** [comment]
@dhruv-colosus 
As you are using the version of tensorflow which does not have contrib please downgrade.

please refer to these links for more clarity: [link1](https://github.com/tensorflow/tensorflow/issues/36193#issuecomment-609923865) [link2](https://github.com/tensorflow/tensorflow/issues/31350#issuecomment-542827486) [link3](https://github.com/tensorflow/tensorflow/issues/32229)

**Comment by Saduf2019** [comment]
For more info see this [https://www.tensorflow.org/guide/migrate#a_note_on_slim_contriblayers](https://www.tensorflow.org/guide/migrate#a_note_on_slim_contriblayers)
Thanks!

**Comment by dhruv-colosus** [comment]
> For more info see this https://www.tensorflow.org/guide/migrate#a_note_on_slim_contriblayers
> Thanks!

Are there any disadvantage  of older version over this one. And when I try to downgrade this error occur
C:\Users\HP>pip install tensorflow==1.4
ERROR: Could not find a version that satisfies the requirement tensorflow==1.4 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3)
ERROR: No matching distribution found for tensorflow==1.4

**Comment by Saduf2019** [comment]
@dhruv-colosus 
Please note you are referring to incorrect tensorflow version, the tensorflow version should be 1.14 and not 1.4

**Comment by dhruv-colosus** [comment]
> @dhruv-colosus
> Please note you are referring to incorrect tensorflow version, the tensorflow version should be 1.14 and not 1.4


C:\Users\HP>pip install tensorflow==1.14
ERROR: Could not find a version that satisfies the requirement tensorflow==1.14 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3)
ERROR: No matching distribution found for tensorflow==1.14

Still getting error

**Comment by Saduf2019** [comment]
@dhruv-colosus 
Please  downgrade to python version 3.7 as per [this comment](https://github.com/tensorflow/tensorflow/issues/33838#issuecomment-566342226) there is no pip package for 3.8.
Can you please confirm if you used "python3 -m pip install tensorflow==1.14.0" else please do so and let us know.
Please follow [this issue](https://github.com/tensorflow/tensorflow/issues/33838), it will answer all queries related to this issue.

**Comment by mihaimaruseac** [comment]
@dhruv-colosus 1.4 is too old, please don't use it. 1.14 is also no longer supported (more than a year since release).

So, you can only use 1.15, 2.0, 2.1 and (soon) 2.2 if you want to use something that is still being supported (1.15 and 2.1 are supported for 3 years).

If `pip install` does not work, try upgrading pip and setuptools.

**Comment by dhruv-colosus** [comment]
> @dhruv-colosus 1.4 is too old, please don't use it. 1.14 is also no longer supported (more than a year since release).
> 
> So, you can only use 1.15, 2.0, 2.1 and (soon) 2.2 if you want to use something that is still being supported (1.15 and 2.1 are supported for 3 years).
> 
> If `pip install` does not work, try upgrading pip and setuptools.

I have fully updated version of pip and setuptools but still no version lower than 2.0 is allowed to be downloaded.

**Comment by dhruv-colosus** [comment]
> @dhruv-colosus
> Please downgrade to python version 3.7 as per [this comment](https://github.com/tensorflow/tensorflow/issues/33838#issuecomment-566342226) there is no pip package for 3.8.
> Can you please confirm if you used "python3 -m pip install tensorflow==1.14.0" else please do so and let us know.
> Please follow [this issue](https://github.com/tensorflow/tensorflow/issues/33838), it will answer all queries related to this issue.

I used pip with Python 3.6 also but still its not happening

**Comment by mihaimaruseac** [comment]
Can you post (attach) the full output of the following?

```
python -m pip install --upgrade pip setuptools
python -m pip debug --verbose
python -m pip install -vvv tensorflow=99.99.99   # for debugging, I know it does not exist
```

**Comment by dhruv-colosus** [comment]
Microsoft Windows [Version 10.0.17134.1425]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\HP>python -m pip install --upgrade pip setuptools
Collecting pip
  Downloading pip-20.1-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 409 kB/s
Collecting setuptools
  Downloading setuptools-46.1.3-py3-none-any.whl (582 kB)
     |████████████████████████████████| 582 kB 125 kB/s
Installing collected packages: pip, setuptools
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
  Attempting uninstall: setuptools
    Found existing installation: setuptools 41.2.0
    Uninstalling setuptools-41.2.0:
      Successfully uninstalled setuptools-41.2.0
Successfully installed pip-20.1 setuptools-46.1.3

C:\Users\HP>python -m pip debug --verbose
WARNING: This command is only meant for debugging. Do not use this with automation for parsing and getting these details, since the output and options of this command may change without notice.
pip version: pip 20.1 from C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\pip (python 3.8)
sys.version: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
sys.executable: C:\Users\HP\AppData\Local\Programs\Python\Python38\python.exe
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: cp1252
sys.platform: win32
sys.implementation:
  name: cpython
'cert' config value: Not specified
REQUESTS_CA_BUNDLE: None
CURL_CA_BUNDLE: None
pip._vendor.certifi.where(): C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_vendor\certifi\cacert.pem
pip._vendor.DEBUNDLED: False
vendored library versions:
  appdirs==1.4.3
  CacheControl==0.12.6
  colorama==0.4.3
  contextlib2==0.6.0.post1 (Unable to locate actual module version, using vendor.txt specified version)
  distlib==0.3.0
  distro==1.5.0 (Unable to locate actual module version, using vendor.txt specified version)
  html5lib==1.0.1
  ipaddress==1.0.23
  msgpack==1.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  packaging==20.3
  pep517==0.8.2
  progress==1.5
  pyparsing==2.4.7
  requests==2.23.0
  certifi==2020.04.05.1
  chardet==3.0.4
  idna==2.9
  urllib3==1.25.8
  resolvelib==0.3.0
  retrying==1.3.3 (Unable to locate actual module version, using vendor.txt specified version)
  setuptools==44.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  six==1.14.0
  toml==0.10.0
  webencodings==0.5.1 (Unable to locate actual module version, using vendor.txt specified version)
Compatible tags: 30
  cp38-cp38-win_amd64
  cp38-abi3-win_amd64
  cp38-none-win_amd64
  cp37-abi3-win_amd64
  cp36-abi3-win_amd64
  cp35-abi3-win_amd64
  cp34-abi3-win_amd64
  cp33-abi3-win_amd64
  cp32-abi3-win_amd64
  py38-none-win_amd64
  py3-none-win_amd64
  py37-none-win_amd64
  py36-none-win_amd64
  py35-none-win_amd64
  py34-none-win_amd64
  py33-none-win_amd64
  py32-none-win_amd64
  py31-none-win_amd64
  py30-none-win_amd64
  cp38-none-any
  py38-none-any
  py3-none-any
  py37-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any

C:\Users\HP>python -m pip install tensorflow==1.5
ERROR: Could not find a version that satisfies the requirement tensorflow==1.5 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0)
ERROR: No matching distribution found for tensorflow==1.5

C:\Users\HP>python -m pip install tensorflow==1.15
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0)
ERROR: No matching distribution found for tensorflow==1.15

C:\Users\HP>python -m pip install -vvv tensorflow=99.99.99   # for debugging, I know it does not exist
Non-user install because site-packages writeable
Created temporary directory: C:\Users\HP\AppData\Local\Temp\pip-ephem-wheel-cache-utpivz2z
Created temporary directory: C:\Users\HP\AppData\Local\Temp\pip-req-tracker-oevbpce7
Initialized build tracking at C:\Users\HP\AppData\Local\Temp\pip-req-tracker-oevbpce7
Created build tracker: C:\Users\HP\AppData\Local\Temp\pip-req-tracker-oevbpce7
Entered build tracker: C:\Users\HP\AppData\Local\Temp\pip-req-tracker-oevbpce7
Created temporary directory: C:\Users\HP\AppData\Local\Temp\pip-install-b_3tbgyk
ERROR: Invalid requirement: 'tensorflow=99.99.99'
Hint: = is not a valid operator. Did you mean == ?
Exception information:
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_vendor\packaging\requirements.py", line 98, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_vendor\pyparsing.py", line 1955, in parseString
    raise exc
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_vendor\pyparsing.py", line 3814, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd, found '='  (at char 10), (line:1, col:11)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_internal\req\constructors.py", line 358, in parse_req_from_line
    req = Requirement(req_as_string)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_vendor\packaging\requirements.py", line 100, in __init__
    raise InvalidRequirement(
pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "'=99.99.9'": Expected stringEnd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_internal\cli\base_command.py", line 188, in _main
    status = self.run(options, args)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_internal\cli\req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_internal\commands\install.py", line 300, in run
    reqs = self.get_requirements(
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_internal\cli\req_command.py", line 321, in get_requirements
    req_to_add = install_req_from_line(
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_internal\req\constructors.py", line 396, in install_req_from_line
    parts = parse_req_from_line(name, line_source)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\site-packages\pip\_internal\req\constructors.py", line 373, in parse_req_from_line
    raise InstallationError(msg)
pip._internal.exceptions.InstallationError: Invalid requirement: 'tensorflow=99.99.99'
Hint: = is not a valid operator. Did you mean == ?
Removed build tracker: 'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-req-tracker-oevbpce7'

**This is The Output**

**Comment by mihaimaruseac** [comment]
The relevant part of the output is likely this (note usage of ` ``` ` to make it more readable)

```
Compatible tags: 30
  cp38-cp38-win_amd64
  cp38-abi3-win_amd64
  cp38-none-win_amd64
  cp37-abi3-win_amd64
  cp36-abi3-win_amd64
  cp35-abi3-win_amd64
  cp34-abi3-win_amd64
  cp33-abi3-win_amd64
  cp32-abi3-win_amd64
  py38-none-win_amd64
  py3-none-win_amd64
  py37-none-win_amd64
  py36-none-win_amd64
  py35-none-win_amd64
  py34-none-win_amd64
  py33-none-win_amd64
  py32-none-win_amd64
  py31-none-win_amd64
  py30-none-win_amd64
  cp38-none-any
  py38-none-any
  py3-none-any
  py37-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any
```

Matching that list with the available pips it looks like you can install [2.2 with python3.8](https://pypi.org/project/tensorflow/2.2.0/#files) but no others.

For example, for 1.15, https://pypi.org/project/tensorflow/1.15.0/#files says that you should have one of the following tags to install via pip: `cp37-cp37m-win_amd64`, `cp36-cp36m-win_amd64` and `cp35-cp35m-win_amd64`.

How did you get Python on your machine? Maybe that is at fault?

**Comment by Saduf2019** [comment]
@dhruv-colosus
Please update as per above comment

**Comment by dhruv-colosus** [comment]
I downloaded it through the python.org site only. So is there no solution available??

**Comment by mihaimaruseac** [comment]
You will have to download Python3.7 from the python site to use 1.15, 2.0 or 2.1.

TF 2.2 is the only one working in Python3.8.

**Comment by dhruv-colosus** [comment]
> You will have to download Python3.7 from the python site to use 1.15, 2.0 or 2.1.
> 
> TF 2.2 is the only one working in Python3.8.

I already tried with 3.6 also, 3.7 is the only option so??

**Comment by mihaimaruseac** [comment]
The tags above signal an incompatibility between Pythons. https://github.com/pypa/pip/issues/6526
