### ISSUE TITLE
How use model(saved by tf1.14.0) in the tf1.5.0?

### ISSUE THREAD

**Issue by DunZhang** [tensorflow/tensorflow#38884]
Hi,  tensorflow team:
    I have a model saved by tensorflow-1.14.0. In my case, I must use this model in a tensorflow-1.5.0 environment. Is there any ways to convert the high-tensorflow-version model (pb file or ckpt) to a low-tensorflow-version model? 
                 Looking  forward to your repply

**Comment by ravikyram** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
