### ISSUE TITLE
Adding regularization losses with the `model.add_loss` method doesn't seem to do the intended thing

### ISSUE THREAD

**Issue by srihari-humbarwadi** [tensorflow/tensorflow#38891]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0-rc3
- Python version: 3.7

**Describe the current behavior**
I was trying to add regularization losses to models that are already build, for example `keras_applications` models. I did this using the `model.add_loss` method. After adding losses from all the layers, calling model.losses seems to return a list containing the same loss value for each of the layers, which seems weird.
```
inputs = tf.keras.Input(shape=[100])
x = tf.keras.layers.Dense(10)(inputs)
x = tf.keras.layers.Dense(15)(x)
x = tf.keras.layers.Dense(5)(x)
outputs = tf.keras.layers.Dense(5)(x)

model = tf.keras.Model(inputs, outputs)

assert model.losses == []

l2_regularizer = tf.keras.regularizers.l2(1e-4)
for i in range(len(model.layers)):
    layer = model.layers[i]
    if isinstance(layer, tf.keras.layers.Dense):
        model.add_loss(lambda: l2_regularizer(layer.kernel))
        
print(model.losses)
```
ouptut:
```
[<tf.Tensor: shape=(), dtype=float32, numpy=0.0004718543>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0004718543>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0004718543>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0004718543>]
```

Interesting thing to note is, if i add the losses without a loop, everything seems to work as intended
```
inputs = tf.keras.Input(shape=[100])
x = tf.keras.layers.Dense(10)(inputs)
x = tf.keras.layers.Dense(15)(x)
x = tf.keras.layers.Dense(5)(x)
outputs = tf.keras.layers.Dense(5)(x)

model = tf.keras.Model(inputs, outputs)

assert model.losses == []

l2_regularizer = tf.keras.regularizers.l2(1e-4)
model.add_loss(lambda: l2_regularizer(model.layers[1].kernel))
model.add_loss(lambda: l2_regularizer(model.layers[2].kernel))
model.add_loss(lambda: l2_regularizer(model.layers[3].kernel))
model.add_loss(lambda: l2_regularizer(model.layers[4].kernel))
        
print(model.losses)
```
output:
```
[<tf.Tensor: shape=(), dtype=float32, numpy=0.0018836524>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0012256705>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0007460108>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0004328331>]
```

I am aware that i can always set the `kernel_regularizer` in layer's arg while building the model, but in this case i wanted to add a regularization loss to the model that was already built.

**Comment by srihari-humbarwadi** [comment]
Update:
This seems to work for now, but is it the right way to do it?
```
inputs = tf.keras.Input(shape=[100])
x = tf.keras.layers.Dense(10)(inputs)
x = tf.keras.layers.Dense(15)(x)
x = tf.keras.layers.Dense(5)(x)
outputs = tf.keras.layers.Dense(5)(x)

model = tf.keras.Model(inputs, outputs)

assert model.losses == []

l2_regularizer = tf.keras.regularizers.l2(1e-4)

def add_l2_loss(layer):
    def _add_l2_loss():
        l2 = tf.keras.regularizers.l2(1e-4)
        return l2(layer.kernel)
    return _add_l2_loss

for i in range(len(model.layers)):
    layer = model.layers[i]
    if isinstance(layer, tf.keras.layers.Dense):
        model.add_loss(add_l2_loss(layer))

model.losses
```
output:
```
[<tf.Tensor: shape=(), dtype=float32, numpy=0.001901342>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0011366734>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.00079565955>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0005400869>]
```

**Comment by ravikyram** [comment]
@srihari-humbarwadi 

I am trying to reproduce the issue and i am seeing the below error`(NameError: name 'add_l2_loss' is not defined`) in the updated code.Can you please help me with the reproducible code. Thanks!

**Comment by srihari-humbarwadi** [comment]
@ravikyram I have updated the code snippet, please take a look

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.2.0-rc3 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/3b99b38929a3bc5c06eb1a2a8f8703d2/untitled831.ipynb).Thanks!

**Comment by srihari-humbarwadi** [comment]
@pavithrasv any updates?

**Comment by EZ4NO1** [comment]
i meet the same problem,why will bug happens in the code of the first version

**Comment by Svan70** [comment]
Had the same issue. The reason is quite tricky !
It is related to the way lambda handles variables defined in outer scope. It is explained here : 

https://docs.python.org/3/faq/programming.html#why-do-lambdas-defined-in-a-loop-with-different-values-all-return-the-same-result

So if we do that :         
`model.add_loss(lambda x=layer: l2_regularizer(x.kernel))`
instead of 
` model.add_loss(lambda: l2_regularizer(layer.kernel))`

it works ! :exploding_head: :joy:

**Comment by saikumarchalla** [comment]
Still an issue in TF 2.5 as well. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/9b0604c74ed8f45f8609445130873245/untitled.ipynb).

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
