### ISSUE TITLE
unique_with_counts is quite slow

### ISSUE THREAD

**Issue by liob** [tensorflow/tensorflow#38898]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: docker image nvcr.io/nvidia/tensorflow:20.03-tf2-py3 (Linux x86_64 Ubuntu 18.04.4 LTS)
- TensorFlow installed from: docker image
- TensorFlow version: 2.1.0
- Python version: 3.6.9
- CUDA/cuDNN version: 10.2 / 7.6
- GPU model and memory: Tesla V100-SXM2 32GB

**Describe the current behavior**
unique_with_counts is quite slow. In comparison pytorch is 50 - 100 times faster:

| framework   |   mean (ms) | dtype   |
| ----------- | ----------: | ------- |
| tensorflow  |   234.770   | int32   |
| tensorflow  |   231.738   | int16   |
| tensorflow  |   400.438   | float32 |
| tensorflow  |   307.234   | float16 |
| pytorch     |     5.372   | int32   |
| pytorch     |     4.086   | int16   |
| pytorch     |     5.080   | float32 |
| pytorch     |     3.511   | float16 |

The script to produce these results can be found here: https://github.com/liob/bugreport_tf_unique_with_counts

**Describe the expected behavior**
It is apparent that tf implements unique_with_counts as a single-threaded CPU routine. A GPU implementation, such as in pytorch, will most certainly speed up the operation dramatically.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1ye_wN-DkfIgz-AtQncbiM0h0zsVe7sKx

**Comment by Saduf2019** [comment]
@liob 
i ran the code shared by you and face a diffrent error on both 2.1 and nightly, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/2d707444f149ba2e6e60d76ff7512bfd/untitled154.ipynb)

**Comment by liob** [comment]
@Saduf2019 
the newly created notebook did not include the sample data. Here is a fixed version:
https://colab.research.google.com/gist/liob/778c1bc083600b1384c216b5169fd4ad/untitled154.ipynb

Thank you for taking a look at this issue.

**Comment by Saduf2019** [comment]
i am able to replicate this issue, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/e988e80bfb1b5e1dc3de10dc1dbd307d/38898.ipynb) . Thanks!

**Comment by ymodak** [comment]
Thanks for your issue. The performance stats have significantly improved with TF 2.6

dtype | framework | mean (ms)
-- | -- | --
int32 | tensorflow | 39.084363
int16 | tensorflow | 25.341967
float32 | tensorflow | 34.118117
float16 | tensorflow | 22.233753
int32 | pytorch | 32.295503
float32 | pytorch | 24.424627
