### ISSUE TITLE
[TFLite] TFlite failed to build the whl package

### ISSUE THREAD

**Issue by Leslie-Fang** [tensorflow/tensorflow#38903]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS7.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source 
- TensorFlow version: latest master branch [64c32cf5100fc8807fe6598bc5517c3456b68b97]
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 3.0.0
- GCC/Compiler version (if compiling from source): 8.3

**Describe the problem**
Following the BKM[https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package] to build tflite, failed with the error:

_interpreter_wrapper/interpreter_wrapper_pybind11.cc:16:10: fatal error: pybind11/pybind11.h: No such file or directory
 #include "pybind11/pybind11.h"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1_

I have install pybind11 and numpy through pip. and I have checked pybind11.h do exsit in the PATH. suspect the bug relates with the build file.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
sudo apt install swig libjpeg-dev zlib1g-dev python3-dev python3-numpy
pip install numpy pybind11
sh tensorflow/lite/tools/make/download_dependencies.sh
sh tensorflow/lite/tools/pip_package/build_pip_package.sh

```

**Comment by Leslie-Fang** [comment]
As in this issue https://github.com/tensorflow/tensorflow/issues/37639 mentions, swig has been removed and pybind11 would be used.

**Comment by Leslie-Fang** [comment]
@teijeong Hi, any comments on this issue

**Comment by teijeong** [comment]
Hi Leslie-Fang, sorry for the error :( we're working on getting pybind dependencies clean, meanwhile it's bit tricky to get proper include dir for pybind11. Current setup is configured to work on docker, but seems it's not stable in other environments.

If you can find location of headers for pybind11, try adding it on `setup.py` here:
https://github.com/tensorflow/tensorflow/blob/6a701314351845ecbc6641ecd2f68e21b582c3f8/tensorflow/lite/tools/pip_package/setup.py#L134

**Comment by Leslie-Fang** [comment]
@teijeong Thanks for the comments. I have made a PR(https://github.com/tensorflow/tensorflow/pull/38904) to fix this issue. Could you help to have a review.

**Comment by Saduf2019** [comment]
@Leslie-Fang 
Please confirm if we may move this to closed status.

**Comment by Leslie-Fang** [comment]
@Saduf2019  Thanks, Close and wait the PR got merged.
