### ISSUE TITLE
Run a GitHub project on google Colabratory

### ISSUE THREAD

**Issue by dantpy700** [tensorflow/tensorflow#38905]
I have a question, there is a GitHub project about text to speech with deep-learning but i can't neither run it on local machine nor google colaboratory,

can anyone help on how to run it? as i downloaded the files but it has many files i dont know how to run it.

it's git hub link==>

https://github.com/AlisterTA/Persian-text-to-speech
Thanks

**Comment by saikumarchalla** [comment]
@dantpy700 This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
