### ISSUE TITLE
Sampling uniforms is slow

### ISSUE THREAD

**Issue by AdrienCorenflos** [tensorflow/tensorflow#38909]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): True
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de410
- Python version: 3.7
- CUDA/cuDNN version: 10.1
- GPU model and memory: GTX 1080Ti

**Describe the current behavior**
Sampling uniforms is 100 times slower in tensorflow on GPU than in pytorch, it's 30 times slower on CPU. 

**Standalone code to reproduce the issue**
# TO BE RUN IN A NOTEBOOK
```python
import tensorflow as tf
import torch
# tf.config.set_visible_devices([], 'GPU') # if no GPU tensorflow is now 30 times slower
%timeit tf.random.uniform([], 0., 1.) # 310 µs ± 3.53 µs per loop
%timeit torch.rand([]) # 2.04 µs ± 38.7 ns per loop
```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.1.0., 2.2-rc3 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/2bcf67f312eb7e055462658a3129ac14/untitled829.ipynb).Thanks!

**Comment by AdrienCorenflos** [comment]
Hi,

As an FYI, this behaviour persists when asking for larger samples. This is a table of the log-time (log seconds) it took to sample a uniform of a certain log-size. For most practical purposes (<1M samples) tensorflow is severely underperforming. Note that this is not improved by decorating the call to random nor is by using stateless sampling. I tried using THREEFRY to see if the otherhead was coming from PHILOX, but it raises.

|   log-size |    torch |   tensorflow |
|-----------:|---------:|-------------:|
|    0       | -5.62487 |     -3.92051 |
|    1       | -5.59297 |     -3.92344 |
|    1.30103 | -5.57734 |     -3.92785 |
|    1.62325 | -5.52077 |     -3.9329  |
|    1.94448 | -5.51241 |     -3.91702 |
|    2.26245 | -5.43938 |     -3.92665 |
|    2.57864 | -5.29286 |     -3.92046 |
|    2.89432 | -5.12171 |     -3.85816 |
|    3.21032 | -4.90156 |     -3.8801  |
|    3.52621 | -4.64741 |     -3.80525 |
|    3.84205 | -4.35693 |     -3.75417 |
|    4.15788 | -4.04589 |     -3.64094 |
|    4.47368 | -3.7245  |     -3.37539 |
|    4.78947 | -3.41472 |     -3.21007 |
|    5.10526 | -3.08295 |     -2.8371  |
|    5.42105 | -2.70882 |     -2.63069 |
|    5.73684 | -2.43453 |     -2.39153 |
|    6.05263 | -2.13015 |     -2.09891 |
|    6.36842 | -1.8209  |     -1.799   |
|    6.68421 | -1.44797 |     -1.45077 |
|    7       | -1.14071 |     -1.10838 |

**Comment by Saduf2019** [comment]
@AdrienCorenflos 
please refer to [this gist](https://colab.research.google.com/gist/Saduf2019/2870c0a2de935e5d7a775dd9a155fbe9/untitled602.ipynb) and let us know if the latest tf version helps.
