### ISSUE TITLE
    TypeError: len is not well defined for symbolic Tensors. (transpose:0) Please call `x.shape` rather than `len(x)` for shape information.

### ISSUE THREAD

**Issue by menon92** [tensorflow/tensorflow#38908]
I'm try to make my `padd_spectrograms`  function execute faster. So I add `@tf.function` but when I add `@tf.function` decorator I'm getting ` TypeError: len is not well defined for symbolic Tensors. (transpose:0) Please call `x.shape` rather than `len(x)` for shape information.`

I'm using `colab tensorflow 2.x`

If I do not use `@tf.function` it works without any error

```python
@tf.function
def padd_spectrograms(spectogram, padd_len):
    t = tf.transpose(spectogram) # feature x timestep -> timestep x feature
    p = tf.keras.preprocessing.sequence.pad_sequences(
        t, maxlen=padd_len, dtype='float', padding='post', truncating='post')
    return tf.transpose(p) # back to feature x timestep
```
```python
TypeError: in user code:

    /content/utils/helper.py:83 padd_spectrograms  *
        p = tf.keras.preprocessing.sequence.pad_sequences(
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/preprocessing/sequence.py:158 pad_sequences  **
        padding=padding, truncating=truncating, value=value)
    /usr/local/lib/python3.6/dist-packages/keras_preprocessing/sequence.py:56 pad_sequences
        num_samples = len(sequences)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:754 __len__
        "shape information.".format(self.name))

    TypeError: len is not well defined for symbolic Tensors. (transpose:0) Please call `x.shape` rather than `len(x)` for shape information.
```

Thanks

**Comment by amahendrakar** [comment]
@menon92,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here.

You can also share your Colab gist with us. Select 'File' -> 'Save a copy as Github Gist', and share the link of the new window. Thanks!

**Comment by menonnsl** [comment]
@amahendrakar 
It's very hard to share a Colab gist because, I'm using an external script `helper.py` which contain `padd_spectrograms` method as a part of data generation

**Comment by menon92** [comment]
@amahendrakar 
It's very hard to share a Colab gist because, I'm using an external script helper.py which contain padd_spectrograms method as a part of data generation

**Comment by amahendrakar** [comment]
@menon92,
Is it possible for you to share a minimal standalone code to reproduce the error? Thanks!

**Comment by menon92** [comment]
@amahendrakar ,
Is it possible to apply `@tf.function` to `tf.keras.preprocessing.sequence.pad_sequences()` ? Thanks

**Comment by menon92** [comment]
@amahendrakar ,
I think there is an issue with `tf.keras.preprocessing.sequence.pad_sequences()` . I replace `.pad_sequences` with `tf.pad()` and it works without any error.

```python
@tf.function
def padd_spectrograms(spectogram, padd_len):
    t = tf.transpose(spectogram) # feature x timestep -> timestep x feature
    paddings = tf.constant([[0, 0,], [0, padd_len-t.shape[1]]])
    p = tf.pad(t, paddings, "CONSTANT")
    return tf.transpose(p) # back to feature x timestep
```
Could you please investigate graph mode with `tf.keras.preprocessing.sequence.pad_sequences()`

Thanks

**Comment by amahendrakar** [comment]
> Could you please investigate graph mode with `tf.keras.preprocessing.sequence.pad_sequences()`

@menon92,
I was able to apply `@tf.function` to `tf.keras.preprocessing.sequence.pad_sequences()` without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/75b69759473fd025668ac9ed048ed909/38908.ipynb). Thanks!

**Comment by menon92** [comment]
@amahendrakar,
I'm finally able to reproduce the issue please check the gist of it [here](https://gist.github.com/menon92/8458fbde8d10d9705c51e97c7ae9d228) . Thanks

**Comment by amahendrakar** [comment]
Was able to reproduce the error with [TF v2.2.0-rc4](https://colab.research.google.com/gist/amahendrakar/3551b5ad96a2c3f5d99e8e485cb57c0b/38908-2-2.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/cf2a8cd19b814b13d309165ffc9a405a/38908-tf-nightly.ipynb).

Whereas running the code with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/ea72f33f5d78cef814915d4001d76160/38908-2-1.ipynb) throws an error stating `    NotImplementedError: Cannot convert a symbolic Tensor (TensorArrayV2Read/TensorListGetItem:0) to a numpy array`. Please find the attached gist. Thanks!

**Comment by mdanatg** [comment]
`keras.preprocessing.pad_sequences` expects a list of lists, and doesn't work with tensor inputs, which is what gets produced by `tf.transpose`. Using `tf.pad` is the right workaround in this case.

**Comment by hi-im-ryanli** [comment]
Why is the issue closed? Is `tf.keras.preprocessing.sequence.pad_sequences()` not intended to be used in graph execution model? Having a padding function to use in `.map()` for time series models is quite nice.

**Comment by victorconan** [comment]
> 

it seems pad_sequences cannot do broadcasting in autograph. the following works in eager:

```
def pad_function(x):
    padded_inputs = tf.keras.preprocessing.sequence.pad_sequences(x,padding='post')
    return padded_inputs

pad_function([tf.constant([[1, 2, 3], [1, 2, 3]]), tf.constant([[1, 2, 3]])])

>> output:
array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [0, 0, 0]]], dtype=int32)
```

However, when having the `@tf.function` decorator, it does not work:

```
@tf.function
def pad_function(x):
    padded_inputs = tf.keras.preprocessing.sequence.pad_sequences(x,padding='post')
    return padded_inputs
```

Output:
```
ValueError: `sequences` must be a list of iterables. Found non-iterable: Tensor("x:0", shape=(2, 3), dtype=int32)
```
