### ISSUE TITLE
GPU Profiling: does the OP include the data transferring time from host to gpu device and gpu device to host?

### ISSUE THREAD

**Issue by AlvinChen13** [tensorflow/tensorflow#3890]
@prb12 
Hi Paul,
I just do the profiling following: https://github.com/tensorflow/tensorflow/issues/1824. And it works quite well. I detect that Conv2D costs a lot of time in my case, and it is run by nvidia GPU, does the timing for Conv2D include the H2D/D2H time or just the time run on GPU.

Thanks!

**Comment by prb12** [comment]
In future, please can you ask general questions like this on StackOverflow.  This is not a bug/issue.

The Conv2D timings shown in the Timeline do not include host/GPU transfers.  These always happen within Send/Recv ops.  They DMA timings will show up in the timelines labeled /gpu:0/memcpy (and also in the timeline for the stream which was used)
