### ISSUE TITLE
How to pass flags to nvcc when building tensorflow with bazel?

### ISSUE THREAD

**Issue by CptJack2** [tensorflow/tensorflow#38912]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
source
- TensorFlow version:
r1.14
- Python version:
3.6.9
- Installed using virtualenv? pip? conda?:
build on raw linux environment, with pip installed
- Bazel version (if compiling from source):
0.24.1
- GCC/Compiler version (if compiling from source):
4.8.5
- CUDA/cuDNN version:
CUDA 10.0 CUDNN 7.6.5
- GPU model and memory:
Nvidia GTX 1660Ti 6GB

**Describe the problem**
I want to pass some custom flags to nvcc during the build, like telling nvcc dynamically link the cuda runtime library with the flag --cudart=shared. On windows 10 with visual studio 2015, I could just use the following command line:
bazel build --config=opt --config=cuda --copt=-nvcc_options=cudart=shared //tensorflow/tools/pip_package:build_pip_package, and msvc will just pass the flag specified by the -nvcc_options to nvcc,  but on linux it doesn't work, with the following errors pop out:

ERROR: /root/.cache/bazel/_bazel_root/5ac94cf1f70fd575be3807b8a4a32ede/external/com_google_absl/absl/debugging/BUILD.bazel:190:1: C++ compilation of rule '@com_google_absl//absl/debugging:leak_check' failed (Exit 1)
gcc: error: unrecognized command line option '-nvcc_options=cudart=shared'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 152.342s, Critical Path: 48.24s
INFO: 1236 processes: 1236 local.
FAILED: Build did NOT complete successfully

**Provide the exact sequence of commands / steps that you executed before running into the problem**
just as the official build document said, build with command line:
bazel build --config=opt --config=cuda --copt=-nvcc_options=cudart=shared //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

ERROR: /root/.cache/bazel/_bazel_root/5ac94cf1f70fd575be3807b8a4a32ede/external/com_google_absl/absl/debugging/BUILD.bazel:190:1: C++ compilation of rule '@com_google_absl//absl/debugging:leak_check' failed (Exit 1)
gcc: error: unrecognized command line option '-nvcc_options=cudart=shared'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 152.342s, Critical Path: 48.24s
INFO: 1236 processes: 1236 local.
FAILED: Build did NOT complete successfully

**Comment by CptJack2** [comment]
passing nvcc flags through bazel still remain unsolved, but my first intenstion of building tensorflow that dynamic links to cuda library is solved, see https://github.com/tensorflow/tensorflow/issues/38941 for detail

**Comment by ymodak** [comment]
Is this still an issue?

**Comment by CptJack2** [comment]
> Is this still an issue?

Yes, still found no way to pass nvcc flags to bazel other than modifying the build file

**Comment by FindHao** [comment]
> > Is this still an issue?
> 
> Yes, still found no way to pass nvcc flags to bazel other than modifying the build file

Could you give an example about how to modify build file to pass nvcc flags?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by fingerblister** [comment]
bazelisk build --config=cuda --host_copt=-allow-unsupported-compiler //tensorflow/tools/pip_package:build_pip_package
