### ISSUE TITLE
Simple loop is slow

### ISSUE THREAD

**Issue by AdrienCorenflos** [tensorflow/tensorflow#38910]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): True
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de410
- Python version: 3.7
- CUDA/cuDNN version: 10.1
- GPU model and memory: GTX 1080Ti

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Trivial loop is 300 times slower than in pure python or pytorch, note that the ratio doesn't change with the size of the loop.
Note that I do get a speed up by implementing the loop using while_loop syntax, but it's far (still >250 times slower) from catching up.

**Standalone code to reproduce the issue**
# TO BE RUN IN A NOTEBOOK
```python
import tensorflow as tf

tf.config.set_visible_devices([], 'GPU')

@tf.function
def tf_loop(n_iter):
    val = 0.
    for i in tf.range(n_iter):
        val += 0.
    return val

def loop(n_iter):
    val = 0.
    for i in range(n_iter):
        val += 0.
    return val

n_iter = tf.constant(10000)
%timeit tf_loop(n_iter) # 92.3 ms ± 566 µs
%timeit loop(10000) # 288 µs ± 4.31 µs

```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
i am able to replicate the issue faced, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/f3b781e4b903c2cd935b46b5d748ffc9/untitled158.ipynb).

**Comment by mdanatg** [comment]
@AdrienCorenflos When you say trivial loop, do you mean a regular `for i in range` inside `tf.function`?

**Comment by mdanatg** [comment]
See #34500 for a  very similar discussion. The gist of the story is that the default TensorFlow runtime is not efficient for scalar computations. Enabling XLA compilation with `@tf.function(experimental_compile=True)` can greatly improve performance in cases like this. Note that the overhead of calling tf.function alone has a fixed cost of around 200 us.
