### ISSUE TITLE
How to use cudnn LSTMP

### ISSUE THREAD

**Issue by tu1258** [tensorflow/tensorflow#38913]
Firstly, I've posted this on [stackoverflow
](https://stackoverflow.com/questions/61438013/how-to-use-cudnn-lstmp) before. And I know this is not a bug or something so if there is an answer I'll delete this issue. Much appreciated!

Usually I use `tf.contrib.cudnn_rnn.CudnnLSTM` (tensorflow 1.15) and want to use LSTMP(LSTM projection) now. I know that `tf.contrib.rnn.LSTMCell` has LSTMP but that additional training time is too long for me. And I found that [nvidia support LSTMP](https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#features-of-rnn-functions). How to use it on tensorflow?

Thanks!

**Comment by ravikyram** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by tu1258** [comment]
Are you serious? I mean, could you just READ the question before answering. Nevermind I found that tensorflow.contrib has something like `num_proj`. Still appreciated for your reply tho.

**Comment by ymodak** [comment]
Closing this issue since you have found workaround. Feel free to comment/reopen the issue if necessary. Thanks!
