### ISSUE TITLE
Discrepancy of soname for libtensorflow_framework.[dylib|so] on macOS and Linux

### ISSUE THREAD

**Issue by yongtang** [tensorflow/tensorflow#38919]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 + macOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary (tf-nightly)
- TensorFlow version: tf-nightly-2.2.0.dev20200426
- Python version: 3.6 on Ubuntu 18.04 and 3.7 on macOS
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a
**Describe the problem**

While trying to link against `libtensorflow_framework.so` for custom ops, we noticed that the soname on macOS and Linux are different:
**[macOS]:**
```
ls -la /Library/Python/3.7/site-packages/tensorflow
total 169680
...
-rwxr-xr-x   1 root  wheel  28946620 Apr 26 08:42 libtensorflow_framework.2.2.0.dylib
-rwxr-xr-x   1 root  wheel  28946620 Apr 26 08:42 libtensorflow_framework.2.dylib
-rwxr-xr-x   1 root  wheel  28946620 Apr 26 08:42 libtensorflow_framework.dylib
...
```

**[Linux]:**
```
ls -la /usr/local/lib/python3.6/dist-packages/tensorflow
total 37000
...
-rwxr-xr-x  1 root staff 37806248 Apr 26 15:40 libtensorflow_framework.so.2
...
```

From the above, it looks like macOS ties the soname to 2.2.0 while Linux still stays with 2. Given the fact that libtensorflow_framework.so largely relies on C++ API which does not guarantee compatibility across different version, it would be desirable to apply the same of macOS [`2.2.0`] to Linux [`2`] as well. This will help downstream projects to better hand version compatibility issue I think. /cc @seanpmorgan @perfinion

**Comment by seanpmorgan** [comment]
Agree would be very helpful. Similar topic was discussed in this thread and agreed upon naming the framework so with minor version... not sure where that stands:
https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!msg/developers/gdnFNTJbJFM/8oL2PSMOBQAJ

**Comment by perfinion** [comment]
oh huh i didnt realize mac was the full version. but yeah lets change it, i'll find some time soon and prepare a patch. The lib version should be 2.2 only, it shouldnt have the patch in it i dont htink. normally tf-x.y.1 releases are only for security or similar issues so the ABI will be the same and would be a huge hassle to rebuild everything for patch changes

**Comment by sanatmpa1** [comment]
@yongtang,

Can you try updating to latest stable version i.e `2.6.0` and let us know if the discrepancy exists even in newer version? Thanks!
