### ISSUE TITLE
Can't seem to use mirrored strategy in graph mode using tf.function

### ISSUE THREAD

**Issue by tusharrain28** [tensorflow/tensorflow#38914]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.1
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA: 10.1 cudNN:7.6
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

My main objective is achieve parallelism during model training. I have been following the tutorial from the below: 
https://www.tensorflow.org/tutorials/distribute/custom_training

At first, I tried to use eager mode and did not use tf.function to decorate any of my functions. There is no runtime error but the GPUs were still being used sequentially and i as getting the warning that Mirrored Strategy has significant overhead in eager mode and to decorate my APIs with `@tf.function`.
So, I proceeded to do everything exactly like in the above link.

But, now I am getting the error that I cannot iterate over a `tf.tensor` in Graph Mode while iterating over the distributed batched dataset. I am unable to get past this issue. 

This is how i create my dataset. `list_ds` is list of lists , each sublist has 5 strings in it.
`dataset = tf.data.Dataset.from_tensor_slices(list_ds)`
`train_dataset` = dataset.batch(GLOBAL_BATCH_SIZE, drop_remainder=True)`
`train_data_dataset = strategy.experimental_distribute_dataset(train_dataset)`

Only the API where I call `strategy.experimental_run_v2` is decorated with tf.function.
`def train_step(input): `
    `.....`
`@tf.function`
`def distributed_train_step(dataset_inputs):`
    `strategy.experimental_run_v2(train_step, args=dataset_inputs)`
`for epoch in range(EPOCHS):`
    `for batch in train_dist_dataset:`
    `distributed_train_step(batch)`

Unfortunately, I will be unable to upload the exact code that I have written. That's why the indentations are wrong
**Describe the expected behavior**
 I should be able to iterate over my dataset in Graph mode as according to the tutorial it is possible.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@tusharrain28 
can you please provide simple standalone code to replicate the issue, along with the error log
