### ISSUE TITLE
Failed to load the native TensorFlow runtime. ImportError DLL load failed.

### ISSUE THREAD

**Issue by Lamm-a** [tensorflow/tensorflow#38916]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary (I think)
- TensorFlow version: 2.2.0rc3 CPU version
- Python version: 3.8.2
- Installed using virtualenv? pip? conda?: pip

**Describe the problem**
trying to run ascript that is importing tensorflow as follows:
```
import tensorflow as tf

ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

Failed to load the native TensorFlow runtime.

```
*the full trace back is below*

This `ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found` is evidently the issue but I am unsure how to fix it after having gone through your other responses to similar github issues.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
```
Traceback (most recent call last):
  File "C:\Users\wmn262\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\wmn262\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\wmn262\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\wmn262\Anaconda3\envs\tensorflow1\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\wmn262\Anaconda3\envs\tensorflow1\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wmn262\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\wmn262\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\wmn262\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\wmn262\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\wmn262\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\wmn262\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\wmn262\Anaconda3\envs\tensorflow1\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\wmn262\Anaconda3\envs\tensorflow1\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
```

**Comment by Lamm-a** [comment]
I have not guven my CPU model so not sure how the bot could know it does not support AVX. 

CPU model: Intel Core i7-8700 CPU @ 3.2GHz

**Comment by oke-aditya** [comment]
Hey @Lamm-a please have a look at Python 3.8 support #33374 I guess it is not supported yet :cry: so you may have to wait. It will come soon I guess for Python 3.8. It worked for Mac but may not work for windows as of now. So downgrading python maybe an option or use virtual environment for tensorflow with other versions of Python.

**Comment by Lamm-a** [comment]
I gave hat a go right after I posted this and it semi worked, I still got a similar error of DLL not found. Reverting back to Tensorflow 2.0 fixed that. It seems to be an issue with Microsoft visuals c++. I have it installed but it is not being regonised I think?

**Comment by oke-aditya** [comment]
Yes there can be a problem with MS Visual C++ as well. Maybe it is not in PATH or not recognized. Please check installation guide [here](https://www.tensorflow.org/install/pip#windows)

**Comment by saikumarchalla** [comment]
@Lamm-a 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the latest microsoft visual c++ redistributable from [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
).
Also, please follow the instructions from to install from Tensorflow [website](https://www.tensorflow.org/install/source_windows).

Also, refer similar issues.
#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
Thanks!

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 #38615 and see if it helps you.Thanks!

**Comment by ravikyram** [comment]
@Lamm-a 

I suspect problem with latest microsoft visual c++ redistributable .Please, follow instructions [here.](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).Thanks!

**Comment by Lamm-a** [comment]
@saikumarchalla I give the CPU model above :)

> 
> 
> CPU model: Intel Core i7-8700 CPU @ 3.2GHz
> 
> Which after googling does seem to support AVX

Thank you @ravikyram I will give that a look.

**Comment by tingxueronghua** [comment]
I have to mention that this problem only exist in 2.1.0 but not in 2.0.0.
So, my homework forces to use tensorflow, and I noticed that I suffered from the same problem described in this issue. If tensorflow-gpu==2.0.0 is also ok, maybe it is an alternative choice.

**Comment by mihaimaruseac** [comment]
> I have to mention that this problem only exist in 2.1.0 but not in 2.0.0.
> So, my homework forces to use tensorflow, and I noticed that I suffered from the same problem described in this issue. If tensorflow-gpu==2.0.0 is also ok, maybe it is an alternative choice.

Then this means you need the latest MSVC redistributable. If you tried installing it and it didn't work, please check that that is the one that gets accessed.

**Comment by tingxueronghua** [comment]
> 
> 
> > I have to mention that this problem only exist in 2.1.0 but not in 2.0.0.
> > So, my homework forces to use tensorflow, and I noticed that I suffered from the same problem described in this issue. If tensorflow-gpu==2.0.0 is also ok, maybe it is an alternative choice.
> 
> Then this means you need the latest MSVC redistributable. If you tried installing it and it didn't work, please check that that is the one that gets accessed.

Thanks for your help, and I will try it.
