### ISSUE TITLE
Propagate loss throw models

### ISSUE THREAD

**Issue by anhmeow** [tensorflow/tensorflow#38918]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0-rc3
- Python version: 3

**Describe the current behavior**
I have two models i want to run sequentially : a generator and a classifier.
The loss from the generator is depending from the classifier outputs.
In the code i provide, i can't manage to get the backpropagation working : 
ValueError: No gradients provided for any variable: ['dense_generator/kernel:0', 'dense_generator/bias:0']

No grad seems computed for the generator.

The code i wrote is strongly inspired from [dcgan tensorflow tutorial](https://www.tensorflow.org/tutorials/generative/dcgan)

**Describe the expected behavior**
I expect to be able to generate gradients for my generator based on a loss computed at my classifier level.

**Standalone code to reproduce the issue**
Copy paste the following code into a colab notebook and execute it : 

```
import tensorflow as tf
import numpy as np
print(tf.__version__)

def build_generator():
    in_data = tf.keras.layers.Input(shape=(1,), dtype=tf.int32, name="in")
    
    out = tf.keras.layers.Dense(10, name='dense_generator')(in_data)
    return tf.keras.Model(inputs=in_data, outputs=out)
    
def build_classifier():
    features = tf.keras.layers.Input(shape=(10,), dtype=tf.int32, name="features")
    out = tf.keras.layers.Dense(1, activation='sigmoid', dtype = tf.float32, name='dense_class')(features)

    return tf.keras.Model(inputs=features, outputs=out)

generator = build_generator()
classifier_toxic = build_classifier()

generator_optimizer = tf.keras.optimizers.Adam()
class_toxic_optimizer = tf.keras.optimizers.Adam() 

classifier_loss = lambda a,b: tf.keras.losses.binary_crossentropy(a, b, from_logits=True)

@tf.function
def train_step(inputs):
    with tf.GradientTape() as generator_tape:
        features = generator(inputs, training=True)
        preds = classifier_toxic(features)
        loss = classifier_loss(tf.zeros_like(preds), preds)
        # with this folowing loss that takes output from generator, it works but this is not what i want
        #loss = classifier_loss(tf.zeros_like(features), features)      
    # apply gradient on generator
    grads_generator = generator_tape.gradient(loss, generator.trainable_variables)
    generator_optimizer.apply_gradients(zip(grads_generator, generator.trainable_variables))

train_dataset = tf.data.Dataset.from_tensor_slices(np.arange(10)).batch(1)

for count, inputs in enumerate(train_dataset):
    # run training step
    train_step(inputs)
    print('done :', count)
```

**Comment by saikumarchalla** [comment]
I could able to replicate the issue. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/57593a78bdeeff9d167db69cdfff5b37/untitled32.ipynb).Thanks!.

**Comment by anhmeow** [comment]
Hello,

I found the issue : the dtype for the input of my classifier was incorrect : 
features = tf.keras.layers.Input(shape=(10,), dtype=**tf.int32**, name="features")

to be replaced by : 
features = tf.keras.layers.Input(shape=(10,), dtype=**tf.float32**, name="features")
