### ISSUE TITLE
Get grpc error when I use tensorflow java API to load model.

### ISSUE THREAD

**Issue by tywtyw** [tensorflow/tensorflow#38928]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.14.2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.15.0
- Python version: 3.7

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I run tensorflow java api to load model in flink cluster, it works fine the first time. But When I run the job the second time in cluster,  it turns out to be an error like below:

**[libprotobuf ERROR external/protobuf_archive/src/google/protobuf/descriptor_database.cc:58] File already exists in database: tensorflow/core/protobuf/eager_service.proto
[libprotobuf FATAL external/protobuf_archive/src/google/protobuf/descriptor.cc:1358] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):**
**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by tywtyw** [comment]
There is a similar bug issue link in grpc issues
https://github.com/grpc/grpc/issues/13249

**Comment by lindong28** [comment]
The root cause may be similar to https://github.com/tensorflow/tensorflow/issues/20561. Both issues cause error message "File already exists in database..". It likely that Flink and Tensorflow linked different versions of the same library (maybe protobuf) twice.

**Comment by tywtyw** [comment]
> The root cause may be similar to #20561. Both issues cause error message "File already exists in database..". It is possible that Flink and Tensorflow linked different versions of the same library (e.g. protobuf) twice.

**Comment by tywtyw** [comment]
Here is the github where I show how to reproduce the issue.   @lindong28  @sjamesr Thanks!
https://github.com/tywtyw/flink-tensorflow

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by kensinxie** [comment]
I encountered the same question, how did you fix it? @tywtyw
