### ISSUE TITLE
TFLite failed to run Transpose Conv2D on mobile.

### ISSUE THREAD

**Issue by dathudeptrai** [tensorflow/tensorflow#38926]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): N
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Virtual
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf-nightly
- Python version: 3.7.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
```
Internal error: Unexpected failure when preparing tensor allocations: tensorflow/lite/kernels/transpose_conv.cc:247 NumInputs(node) != 3 (4 != 3)
```

**Describe the expected behavior**
Python API run fine but when i run on mobile i get above error. Tflite 2.1.0 on mobile can avoid this bug but i will get "Didn't find op for builtin opcode 'SPACE_TO_BATCH_ND' version '3'" bug instead.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by thaink** [comment]
Hi @dathudeptrai,
Can you extend your input to SPACE_TO_BATCH_ND op to be 4D so you can use SPACE_TO_BATCH_ND version 1 or 2.
The 'SPACE_TO_BATCH_ND' version '3'" is not yet included in the TFlite 2.1.0.

**Comment by dathudeptrai** [comment]
hi @thaink ofc i can extend all input from 1D to fake 2D to avoid SPACE_TO_BATCH_ND bug, but tflite-nightly have more supported op than tf 2.1, let say bert-related ops. The real bug i want to report here is "tensorflow/lite/kernels/transpose_conv.cc:247 NumInputs(node) != 3 (4 != 3)" on tflite-nightly, tf 2.1.0 don't have this error.

**Comment by thaink** [comment]
@dathudeptrai Thanks for your explanation. 
https://bintray.com/google/tensorflow/tensorflow-lite/0.0.0-nightly is updated everyday so it should have the latest code. However, i don't think your error is occurred https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/transpose_conv.cc#L247

**Comment by dathudeptrai** [comment]
hi @thaink that is why i ask if there is a missmatch betweent tf-nightly and tflite-nightly. The line 247 of above code expaind why tf-nightly don't occur this error.

**Comment by thaink** [comment]
The problem i don't understand here is why tf 2.1.0 don't have this error. since it is much older and above code and tf-nightly is just recent. tf-nightly and tflite-nightly are triggered independently but they are both built overnight so should have roughly the same code.
Could you try to build the aar from source and check if the error occur?

**Comment by dathudeptrai** [comment]
ok let me check. Ofc i can trick the model to run correctly by fake 2D input. But the missmatch between Tf-nightly and tflite-nightly makes me quite curious :)).

**Comment by thaink** [comment]
"But the missmatch between Tf-nightly and tflite-nightly makes me quite curious"
@multiverse-tf do you have any clue about this?

**Comment by multiverse-tf** [comment]
Not sure. My wild guess is that there might be some bug introduced between tf-nightly and tflite-nightly as they were built separately and independently (i.e. not built against the same github head).

**Comment by dathudeptrai** [comment]
@multiverse-tf pls check, tflite nightly still have problem on Conv2DTranspose. ```java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: tensorflow/lite/kernels/transpose_conv.cc:247 NumInputs(node) != 3 (4 != 3)
    Node number 12 (TRANSPOSE_CONV) failed to prepare. ````

**Comment by multiverse-tf** [comment]
Hmm, are you using an old tflite-nightly build? The particular check as indicated by "transpose_conv.cc:247 NumInputs(node) != 3 (4 != 3)" was removed in https://github.com/tensorflow/tensorflow/commit/43b8f6e71001be7bacee4559e3021965ae67cf33#diff-84dcd410cd1816346c679396513fbcd2L247 on April 23, 2020.

**Comment by dathudeptrai** [comment]
@multiverse-tf that is why i ask if there is a missmatch between tf-nightly and tflite. What do u mean "an old tflite-nightly build" ?. i use ```implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'``` and sync project so android will re-download tflite-nightly ? am i right?

**Comment by thaink** [comment]
@dathudeptrai I am not familiar with Gradle but could you give "./gradlew build --refresh-dependencies" a try? Or delete the gradle cache $HOME/.gradle/caches/ to make sure it fetches the latest tflite-nightly?

**Comment by dathudeptrai** [comment]
@thaink @multiverse-tf ok the problem is cache :))). Seem if we want use tflite-nightly we need delete caches file :). I will close the issue, thank for ur help :D.
