### ISSUE TITLE
ValueError: Attempted to save a function b'__inference_GRU-Dense_layer_call_fn_29299' which references a symbolic Tensor Tensor("dropout/mul_1:0", shape=(?, 384), dtype=float32) that is not a simple constant. This is not supported.

### ISSUE THREAD

**Issue by xuyingjie521** [tensorflow/tensorflow#38934]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:2.1.0
- Python version:3.6
- Installed using virtualenv? pip? conda?:virtualenv
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(?, ?), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7f27ac4592b0>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(?, ?), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7f27ac465668>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(?, ?), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7f27ac4755f8>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(?, ?), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7f27ac3fe940>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(?, ?), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7f27ac465668>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(?, ?), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7f27ac4592b0>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(?, ?), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7f27ac4592b0>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(?, ?), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7f27ac3fe940>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(?, ?), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7f27ac4755f8>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(?, ?), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7f27ac4755f8>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(?, ?), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7f27ac4592b0>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(?, ?), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7f27ac465668>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(?, ?), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7f27ac4755f8>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(?, ?), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7f27ac3fe940>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(?, ?), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7f27ac465668>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(?, ?), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7f27ac4592b0>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(?, ?), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7f27ac4592b0>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(?, ?), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7f27ac3fe940>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(?, ?), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7f27ac4755f8>), {}).
INFO:tensorflow:Unsupported signature for serialization: ((TensorSpec(shape=(?, ?), dtype=tf.float32, name='inputs'), <tensorflow.python.framework.func_graph.UnknownArgument object at 0x7f27ac4755f8>), {}).
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-68ef369094e8> in <module>
      4 
      5 # set_gpu_ratio(ratio=0.65)
----> 6 train_model(train_csv_file, dict_path, model_file_path)

<ipython-input-4-872233fb1b6b> in train_model(train_csv_file, dict_path, model_file_path)
     56 #     model_file_path = '/data1/xuyingjie/project/zhihu_project2020Q1/user_feedback_algorithm_v2_py3/model/'
     57 #     tf.saved_model.save(model, 'model_file_path')
---> 58     tf.keras.models.save_model(model, 'model_file_path', save_format="tf")
     59 
     60     # 保存为pd模型的方式二：

~/.virtualenvs/py3venv/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py in save_model(model, filepath, overwrite, include_optimizer, save_format, signatures, options)
    113   else:
    114     saved_model_save.save(model, filepath, overwrite, include_optimizer,
--> 115                           signatures, options)
    116 
    117 

~/.virtualenvs/py3venv/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/save.py in save(model, filepath, overwrite, include_optimizer, signatures, options)
     76     # we use the default replica context here.
     77     with distribution_strategy_context._get_default_replica_context():  # pylint: disable=protected-access
---> 78       save_lib.save(model, filepath, signatures, options)
     79 
     80   if not include_optimizer:

~/.virtualenvs/py3venv/lib/python3.6/site-packages/tensorflow_core/python/saved_model/save.py in save(obj, export_dir, signatures, options)
    907   object_saver = util.TrackableSaver(checkpoint_graph_view)
    908   asset_info, exported_graph = _fill_meta_graph_def(
--> 909       meta_graph_def, saveable_view, signatures, options.namespace_whitelist)
    910   saved_model.saved_model_schema_version = (
    911       constants.SAVED_MODEL_SCHEMA_VERSION)

~/.virtualenvs/py3venv/lib/python3.6/site-packages/tensorflow_core/python/saved_model/save.py in _fill_meta_graph_def(meta_graph_def, saveable_view, signature_functions, namespace_whitelist)
    551   resource_initializer_ops = []
    552   with exported_graph.as_default():
--> 553     object_map, resource_map, asset_info = saveable_view.map_resources()
    554     for resource_initializer_function in resource_initializer_functions:
    555       asset_dependencies = []

~/.virtualenvs/py3venv/lib/python3.6/site-packages/tensorflow_core/python/saved_model/save.py in map_resources(self)
    283                 ("Attempted to save a function {} which references a symbolic "
    284                  "Tensor {} that is not a simple constant. This is not "
--> 285                  "supported.").format(concrete_function.name, capture))
    286           copied_tensor = constant_op.constant(capture_constant_value)
    287           node_id = len(self.nodes)

ValueError: Attempted to save a function b'__inference_GRU-Dense_layer_call_fn_29299' which references a symbolic Tensor Tensor("dropout/mul_1:0", shape=(?, 384), dtype=float32) that is not a simple constant. This is not supported.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@xuyingjie521,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by xuyingjie521** [comment]
gru_dense = GRU(units=384,
                    **dropout=0.2,
                    recurrent_dropout=0.15,**
                    return_sequences=True,
                    name='GRU-Dense'
                    )(transformed)

    ave_pooing = GlobalAveragePooling1D(name='GlobalAveragePooling1D')(gru_dense)

    x_out = Dense(label_num,
                  activation='softmax',
                  name='Out-Dense'
                  )(ave_pooing)
    MyModel = Model(inputs=xbert_model.model.input, outputs=x_out)
    MyModel.summary()

**Comment by amahendrakar** [comment]
@xuyingjie521,
I tried to reproduce the issue but I am facing an error stating `NameError: name 'transformed' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/8f5330e55fb2e9ee1c25e9bcb478a4fc/38934.ipynb).
Could you please share the complete code to reproduce the issue? Thanks!

**Comment by prabhatkgupta** [comment]
Again getting this issue in my service 

`{
    "class_name": "Model",
    "config": {
        "name": "model_1",
        "layers": [
            {
                "name": "input_12",
                "class_name": "InputLayer",
                "config": {
                    "batch_input_shape": [
                        null,
                        30
                    ],
                    "dtype": "float32",
                    "sparse": false,
                    "name": "input_12"
                },
                "inbound_nodes": []
            },
            {
                "name": "embedding",
                "class_name": "Embedding",
                "config": {
                    "name": "embedding",
                    "trainable": true,
                    "batch_input_shape": [
                        null,
                        null
                    ],
                    "dtype": "float32",
                    "input_dim": 50000,
                    "output_dim": 256,
                    "embeddings_initializer": {
                        "class_name": "VarianceScaling",
                        "config": {
                            "scale": 1,
                            "mode": "fan_avg",
                            "distribution": "uniform",
                            "seed": null
                        }
                    },
                    "embeddings_regularizer": {
                        "class_name": "L1L2",
                        "config": {
                            "l1": 0,
                            "l2": 0.0010000000474974513
                        }
                    },
                    "activity_regularizer": null,
                    "embeddings_constraint": null,
                    "mask_zero": false,
                    "input_length": null
                },
                "inbound_nodes": [
                    [
                        [
                            "input_12",
                            0,
                            0,
                            {}
                        ]
                    ]
                ]
            },
            {
                "name": "bidirectional_3",
                "class_name": "Bidirectional",
                "config": {
                    "name": "bidirectional_3",
                    "trainable": true,
                    "layer": {
                        "class_name": "LSTM",
                        "config": {
                            "name": "gru",
                            "trainable": true,
                            "return_sequences": false,
                            "return_state": false,
                            "go_backwards": false,
                            "stateful": false,
                            "unroll": false,
                            "units": 256,
                            "activation": "tanh",
                            "recurrent_activation": "hard_sigmoid",
                            "use_bias": true,
                            "kernel_initializer": {
                                "class_name": "VarianceScaling",
                                "config": {
                                    "scale": 1,
                                    "mode": "fan_avg",
                                    "distribution": "uniform",
                                    "seed": null
                                }
                            },
                            "recurrent_initializer": {
                                "class_name": "Orthogonal",
                                "config": {
                                    "gain": 1,
                                    "seed": null
                                }
                            },
                            "bias_initializer": {
                                "class_name": "Zeros",
                                "config": {}
                            },
                            "unit_forget_bias": true,
                            "kernel_regularizer": null,
                            "recurrent_regularizer": null,
                            "bias_regularizer": null,
                            "activity_regularizer": null,
                            "kernel_constraint": null,
                            "recurrent_constraint": null,
                            "bias_constraint": null,
                            "dropout": 0.2,
                            "recurrent_dropout": 0.2,
                            "implementation": 1
                        }
                    },
                    "merge_mode": "concat"
                },
                "inbound_nodes": [
                    [
                        [
                            "embedding",
                            0,
                            0,
                            {}
                        ]
                    ]
                ]
            },
            {
                "name": "dense",
                "class_name": "Dense",
                "config": {
                    "name": "dense",
                    "trainable": true,
                    "units": 64,
                    "activation": "linear",
                    "use_bias": true,
                    "kernel_initializer": {
                        "class_name": "VarianceScaling",
                        "config": {
                            "scale": 1,
                            "mode": "fan_avg",
                            "distribution": "uniform",
                            "seed": null
                        }
                    },
                    "bias_initializer": {
                        "class_name": "Zeros",
                        "config": {}
                    },
                    "kernel_regularizer": null,
                    "bias_regularizer": null,
                    "activity_regularizer": null,
                    "kernel_constraint": null,
                    "bias_constraint": null
                },
                "inbound_nodes": [
                    [
                        [
                            "bidirectional_3",
                            0,
                            0,
                            {}
                        ]
                    ]
                ]
            },
            {
                "name": "temperature",
                "class_name": "Lambda",
                "config": {
                    "name": "temperature",
                    "trainable": true,
                    "function": [
                        null,
                        null,
                        [
                            1
                        ]
                    ],
                    "function_type": "lambda",
                    "output_shape": null,
                    "output_shape_type": "raw",
                    "arguments": {}
                },
                "inbound_nodes": [
                    [
                        [
                            "dense",
                            0,
                            0,
                            {}
                        ]
                    ]
                ]
            },
            {
                "name": "softmax",
                "class_name": "Activation",
                "config": {
                    "name": "softmax",
                    "trainable": true,
                    "activation": "softmax"
                },
                "inbound_nodes": [
                    [
                        [
                            "temperature",
                            0,
                            0,
                            {}
                        ]
                    ]
                ]
            }
        ],
        "input_layers": [
            [
                "input_12",
                0,
                0
            ]
        ],
        "output_layers": [
            [
                "softmax",
                0,
                0
            ]
        ]
    },
    "keras_version": "2.2.4",
    "backend": "tensorflow"
}`

Above is the model architecture layers in json format
