### ISSUE TITLE
Tensorflow Lite Object Detection on mobile devices

### ISSUE THREAD

**Issue by amrit-das** [tensorflow/tensorflow#38931]
Suppose, say I have 30 interested objects on an image, is it possible to get all 30 box proposals on a single image without splitting the image, or the number of proposals on an image is limited to 10.
Thank you for the help!

**Comment by jvishnuvardhan** [comment]
@amrit-das It is a parameter in the model, so you will need to regenerate the model with different parameter as you wish. It is there in `TFLiteObjectDetectionAPIModel.java`. Thanks! 

Please close the issue if this was resolved for you. Thanks!

**Comment by amrit-das** [comment]
Thank You!
