### ISSUE TITLE
Build does not succeed and the error content changes every time

### ISSUE THREAD

**Issue by zenboooooon** [tensorflow/tensorflow#38930]
I want to install Tensorflow 1.8 gpu on macOS, but the build does not go through and the error content changes every time even if I try to refer to the following site. How can we make it work?

https://developpaper.com/tensorflow-1-8-with-gpu-on-macos-high-sierra-10-13-6/

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):High Sierra 10.13.6(17g65)
- TensorFlow installed from (source or binary):https://github.com/tensorflow/tensorflow -b r1.8
- TensorFlow version:1.8
- Python version:3.6.3
- Bazel version (if compiling from source):0.14.0
- CUDA/cuDNN version:9.2/7.2
- GPU model and memory:GTX GeForce 1080 ti
- Command Line Tool 8.2.1

`ERROR: /Users/zen/tensorflow/tensorflow/core/kernels/BUILD:1201:1: output 'tensorflow/core/kernels/_objs/gather_functor_gpu/tensorflow/core/kernels/gather_functor_gpu.cu.pic.o' was not created
ERROR: /Users/zen/tensorflow/tensorflow/core/kernels/BUILD:1201:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
`

`ERROR: /Users/zen/tensorflow/tensorflow/core/kernels/BUILD:3434:1: output 'tensorflow/core/kernels/_objs/histogram_op_gpu/tensorflow/core/kernels/histogram_op_gpu.cu.o' was not created
ERROR: /Users/zen/tensorflow/tensorflow/core/kernels/BUILD:3434:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
`

I'm getting all sorts of errors when I do the exact same situation

**Comment by Saduf2019** [comment]
@zenboooooon 
i see you are using a very old version of tensorflow could you please upgrade/install 1.15 o r2.x versions and let us know if you are facing any issues

**Comment by zenboooooon** [comment]
@Saduf2019 Thank you for your reply.
I was going to try it once, but the build method was completely different between 1.8 and 1.14, and the build didn't start, and there was no site that explained how to do it, so I gave it up. I searched and couldn't find anything describing a version newer than 1.8.

**Comment by Saduf2019** [comment]
@zenboooooon 
please follow [this link for installation](https://www.tensorflow.org/install/source) , [link1](https://www.lewuathe.com/how-to-build-tensorflow-on-macos.html), [link2](https://www.pyimagesearch.com/2019/12/09/how-to-install-tensorflow-2-0-on-macos/), [link3](https://techpolymath.com/2017/12/14/tensorflow-from-source-on-mac/) [link4](https://stackoverflow.com/questions/43364264/how-to-install-tensorflow-from-source-for-mac/44299779).

There are plenty resources online to refer, please let us know if the links shared help you resolve the issue faced.

**Comment by zenboooooon** [comment]
@Saduf2019 I'd like to use tensorflow which has GPU support, but the link you sent me was one that doesn't have GPU support.

**Comment by Saduf2019** [comment]
@zenboooooon 
please refer to [link1](https://medium.com/@saitejadommeti/building-tensorflow-gpu-from-source-for-rtx-2080-96fed102fcca) [link2](https://www.tensorflow.org/install/gpu) [link3](url)
