### ISSUE TITLE
New TFLiteConverter not working with tf.complex64

### ISSUE THREAD

**Issue by galah92** [tensorflow/tensorflow#38932]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab CPU
- TensorFlow version (use command below): 2.2.0-rc3

**Describe the current behavior**
New `TFLiteConverter` not working with `tf.complex64`
Disabling the new converter (`converter.experimental_new_converter = False`) works.

**Standalone code to reproduce the issue**

```python3
@tf.function
def foo(x, y):
    return x @ y


x = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.complex64)
y = tf.constant([[2, 3], [4, 5], [6, 7]], dtype=tf.complex64)

foo_concrete = foo.get_concrete_function(x, y)
converter = tf.lite.TFLiteConverter.from_concrete_functions([foo_concrete])
foo_tflite = converter.convert()
```

[colab example](https://colab.research.google.com/drive/1snYjxYYJaOYPQOeQ1ec2o0xPHQB0ILY2)

Thanks

**Comment by haozha111** [comment]
@karimnosseir ,could you take a look? thanks!

**Comment by galah92** [comment]
Any update on this?

**Comment by karimnosseir** [comment]
Sorry for the delay.
I have a fix that should get merged soon.

Note: that FullyConnected op in TFLite doesn't support complex, so you will need to enable TF_SELECT_OPS to run it.

**Comment by galah92** [comment]
@karimnosseir Thanks! Are there plans to support complex for FullyConnected op in TFLite?

**Comment by karimnosseir** [comment]
@galah92 Sorry for the delay.
No immediate plans.
