### ISSUE TITLE
how to dynamic link cuda library when building tensorflow?

### ISSUE THREAD

**Issue by CptJack2** [tensorflow/tensorflow#38941]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
source
TensorFlow version:
r1.14
Python version:
3.6.9
Installed using virtualenv? pip? conda?:
build on raw linux environment, with pip installed
Bazel version (if compiling from source):
0.24.1
GCC/Compiler version (if compiling from source):
4.8.5
CUDA/cuDNN version:
CUDA 10.0 CUDNN 7.6.5
GPU model and memory:
Nvidia GTX 1660Ti 6GB

Describe the problem
i want to build tensorflow  with gpu support, and it should dynamically link the cuda libraries(libcudart.so and so on). 
On windows, I tried bazel build --config=opt --config=cuda --copt=-nvcc_options=cudart=shared //tensorflow/tools/pip_package:libtensorflow. And I used dependency walker on the tensorflow.dll it built, it had cuda related dll in its dependencies, so it seemed work.
but on ubuntu,i tried with the same command line, but get error: gcc un recognized command line

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build --config=opt --config=cuda --copt=-nvcc_options=cudart=shared //tensorflow/tools/pip_package:libtensorflow

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
/root/.cache/bazel/_bazel_root/5ac94cf1f70fd575be3807b8a4a32ede/external/com_google_absl/absl/debugging/BUILD.bazel:190:1: C++ compilation of rule '@com_google_absl//absl/debugging:leak_check' failed (Exit 1)
gcc: error: unrecognized command line option '-nvcc_options=cudart=shared'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 152.342s, Critical Path: 48.24s
INFO: 1236 processes: 1236 local.
FAILED: Build did NOT complete successfully

**Comment by CptJack2** [comment]
dynamic links to cuda library when building tensorflow on linux can be done by passing --linkopt=-lcudart option to bazel, this option tells the linker to link the cuda functions from the shared library libcudart.so (static linking use libcudart_static.a, which is nvcc's default option)
my complete command line is:
bazel build --congif=opt --config=cuda --linkopt=-L/usr/local/cuda/lib64 --linkopt=-lcudart //tensorflow/tools/pip_package:build_pip_package

**Comment by CptJack2** [comment]
> dynamic links to cuda library when building tensorflow on linux can be done by passing --linkopt=-lcudart option to bazel, this option tells the linker to link the cuda functions from the shared library libcudart.so (static linking use libcudart_static.a, which is nvcc's default option)
> my complete command line is:
> bazel build --congif=opt --config=cuda --linkopt=-L/usr/local/cuda/lib64 --linkopt=-lcudart //tensorflow/tools/pip_package:build_pip_package

through this method, the pip package requires libcudart.so to run, but the cuda funciton calls in tensorflow still links to cuda library statically

**Comment by Zhaojp-Frank** [comment]
hit same problem starting from 1.14 (didn't happen on 1.13.1), any update on the problem? 
as the built out _pywrap_tensorflow_internal.so could dpends on cudart shared lib, but meanwhile has statically linked cudart API call, e.g, check by nm -s 
nm -s /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so |grep cudaGet
000000002e880e38 b _ZGVZ13cudaGetDeviceE8func_ptr
000000002e880e98 b _ZGVZ16cudaGetLastErrorE8func_ptr
000000002e880e78 b _ZGVZ18cudaGetErrorStringE8func_ptr
000000002e880e68 b _ZGVZ23cudaGetDevicePropertiesE8func_ptr
000000002e880e40 b _ZZ13cudaGetDeviceE8func_ptr
000000002e880ea0 b _ZZ16cudaGetLastErrorE8func_ptr
000000002e880e80 b _ZZ18cudaGetErrorStringE8func_ptr
000000002e880e70 b _ZZ23cudaGetDevicePropertiesE8func_ptr
00000000074cd860 t cudaGetDevice
00000000074cd520 t cudaGetDeviceProperties
00000000074cd480 t cudaGetErrorString
00000000074cd320 t cudaGetLastError

**Comment by CptJack2** [comment]
After digging into tensorflow's source code, i found this question quite meaningless. In file tensorflow/stream_executor/platform/default/dso_loader.cc, tensorflow implement a shared library loader, and in tensorflow/stream_executor/cuda/, there are a bunch of symbol declaration files such as cuda_10_0.inc, claiming every single symbol declared in cuda libraries. Tensorflow do this to avoid any kind of linking(dynamic, statically) to the actual cuda libraries during compilation. And during runtime, DsoLoader will open the shared object( using dlopen on Linux, other function on other platform)  on the system it runs on, and loads all the addresses of the symbols in that shared object into its own memory space, it's only up to this point, can Tensorflow actually call the cuda functions.
