### ISSUE TITLE
WARNING:tensorflow:AutoGraph could not transform <function affine at 0x0000021B750C1E58> and will run it as-is.

### ISSUE THREAD

**Issue by jfhawkin** [tensorflow/tensorflow#38947]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow version: 2.2.0-rc3
- TensorFlow-probability version: 0.10.0-rc0
- Python version: 3.7.6

**Describe the current behavior**
I am using Anaconda, TensorFlow, and Spyder. When I run my script, I get the following error message:
```
INFO:tensorflow:Converted call: <function affine at 0x0000021B778A51F8>
    args: (<tf.Tensor 'x:0' shape=(6768,) dtype=float32>, <tf.Tensor 'kernel_diag:0' shape=(1,) dtype=float32>, <tf.Tensor 'bias:0' shape=() dtype=float32>)
    kwargs: {}

Converted call: <function affine at 0x0000021B778A51F8>
    args: (<tf.Tensor 'x:0' shape=(6768,) dtype=float32>, <tf.Tensor 'kernel_diag:0' shape=(1,) dtype=float32>, <tf.Tensor 'bias:0' shape=() dtype=float32>)
    kwargs: {}

INFO:tensorflow:Cache hit for entity <function affine at 0x0000021B778A51F8> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x0000021B790D2188>, frozenset()): _ConvertedEntityFactoryInfo(tf__affine in tmpta8nc9zk)
Cache hit for entity <function affine at 0x0000021B778A51F8> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x0000021B790D2188>, frozenset()): _ConvertedEntityFactoryInfo(tf__affine in tmpta8nc9zk)
INFO:tensorflow:Error transforming entity <function affine at 0x0000021B778A51F8>
Traceback (most recent call last):
  File "C:\Users\jason\Anaconda3\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 538, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "C:\Users\jason\Anaconda3\lib\site-packages\tensorflow\python\autograph\impl\conversion.py", line 362, in convert
    return _instantiate(entity, converted_entity_info, free_nonglobal_var_names)
  File "C:\Users\jason\Anaconda3\lib\site-packages\tensorflow\python\autograph\impl\conversion.py", line 300, in _instantiate
    factory = converted_entity_info.get_factory()
  File "C:\Users\jason\Anaconda3\lib\site-packages\tensorflow\python\autograph\impl\conversion.py", line 94, in get_factory
    assert self.module_name in sys.modules
AssertionError
Error transforming entity <function affine at 0x0000021B778A51F8>
WARNING:tensorflow:AutoGraph could not transform <function affine at 0x0000021B778A51F8> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <function affine at 0x0000021B778A51F8> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
INFO:tensorflow:Converted call: <function affine at 0x0000021B778A51F8>
    args: (<tf.Tensor 'x:0' shape=(6768,) dtype=float32>, <tf.Tensor 'kernel_diag:0' shape=(6768,) dtype=float32>, <tf.Tensor 'bias:0' shape=(6768,) dtype=float32>)
    kwargs: {}

Converted call: <function affine at 0x0000021B778A51F8>
    args: (<tf.Tensor 'x:0' shape=(6768,) dtype=float32>, <tf.Tensor 'kernel_diag:0' shape=(6768,) dtype=float32>, <tf.Tensor 'bias:0' shape=(6768,) dtype=float32>)
    kwargs: {}

INFO:tensorflow:Whitelisted <function affine at 0x0000021B778A51F8>: from cache
Whitelisted <function affine at 0x0000021B778A51F8>: from cache
Traceback (most recent call last):
  File "C:\Users\jason\Anaconda3\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 538, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "C:\Users\jason\Anaconda3\lib\site-packages\tensorflow\python\autograph\impl\conversion.py", line 362, in convert
    return _instantiate(entity, converted_entity_info, free_nonglobal_var_names)
  File "C:\Users\jason\Anaconda3\lib\site-packages\tensorflow\python\autograph\impl\conversion.py", line 300, in _instantiate
    factory = converted_entity_info.get_factory()
  File "C:\Users\jason\Anaconda3\lib\site-packages\tensorflow\python\autograph\impl\conversion.py", line 94, in get_factory
    assert self.module_name in sys.modules
AssertionError
```
**Standalone code to reproduce the issue**
```
import pandas as pd
import tensorflow as tf
# tf.autograph.set_verbosity(10,True)
import tensorflow_probability as tfp
from tensorflow_probability import distributions as tfd
# Read the data
df = pd.read_csv("https://raw.githubusercontent.com/jfhawkin/bayes_discrete_choice/master/swissmetro.dat",sep='\t')

"""Basic data and model setup"""

# Removing some observations can be done directly using pandas.
remove = (((df.PURPOSE != 1) & (df.PURPOSE != 3)) | (df.CHOICE == 0))
df.drop(df[remove].index,inplace=True)

# Definition of new variables: as tensorflow vectors
df.reset_index(inplace=True)
IDX = tf.expand_dims(tf.convert_to_tensor(df.index),1)
TRAIN_TT_SCALED = tf.expand_dims(tf.convert_to_tensor(df.TRAIN_TT / 100, dtype=tf.float32),1)
TRAIN_COST_SCALED = tf.expand_dims(tf.convert_to_tensor(df.TRAIN_CO / 100, dtype=tf.float32),1)
SM_TT_SCALED = tf.expand_dims(tf.convert_to_tensor(df.SM_TT / 100, dtype=tf.float32),1)
SM_COST_SCALED = tf.expand_dims(tf.convert_to_tensor(df.SM_CO / 100, dtype=tf.float32),1)
CAR_TT_SCALED = tf.expand_dims(tf.convert_to_tensor(df.CAR_TT / 100, dtype=tf.float32),1)
CAR_CO_SCALED = tf.expand_dims(tf.convert_to_tensor(df.CAR_CO / 100, dtype=tf.float32),1)

DATA = tf.concat([TRAIN_TT_SCALED,TRAIN_COST_SCALED,SM_TT_SCALED,SM_COST_SCALED,CAR_TT_SCALED,CAR_CO_SCALED], axis=1)

# Definition of new variables for availability, etc.: as tensorflow vectors
CHOICE = tf.convert_to_tensor(pd.get_dummies(df.CHOICE), dtype=tf.float32)
CAR_AV_SP =  tf.expand_dims(tf.convert_to_tensor(df.CAR_AV, dtype=tf.float32),1)
TRAIN_AV_SP =  tf.expand_dims(tf.convert_to_tensor(df.TRAIN_AV, dtype=tf.float32),1)
SM_AV_SP =  tf.expand_dims(tf.convert_to_tensor(df.SM_AV, dtype=tf.float32),1)

AV = tf.concat([TRAIN_AV_SP, SM_AV_SP, CAR_AV_SP], axis=1)

num_idx = df.shape[0]

"""Define the model as a partial pooling hierarchical model with varying slope for the time parameter"""

@tf.function
def affine(x, kernel_diag, bias=tf.zeros([])):
  """`kernel_diag * x + bias` with broadcasting."""
  kernel_diag = tf.ones_like(x) * kernel_diag
  bias = tf.ones_like(x) * bias
  return x * kernel_diag + bias

def mmnl_func():
    adj_AV_train = (tf.ones(num_idx) - AV[:,0]) * -9999
    adj_AV_SM = (tf.ones(num_idx) - AV[:,1]) * -9999
    adj_AV_car = (tf.ones(num_idx) - AV[:,2]) * -9999

    return tfd.JointDistributionSequential([
        tfd.Normal(loc=0., scale=1e5),  # mu_b_time
        tfd.HalfCauchy(loc=0., scale=5),  # sigma_b_time
        lambda sigma_b_time,mu_b_time: tfd.MultivariateNormalDiag(  # b_time
        loc=affine(tf.ones([num_idx]), mu_b_time[..., tf.newaxis]),
        scale_identity_multiplier=sigma_b_time),
        tfd.Normal(loc=0, scale=1e5), # a_train
        tfd.Normal(loc=0, scale=1e5), # a_car
        tfd.Normal(loc=0, scale=1e5), # b_cost
        lambda b_cost,a_car,a_train,b_time: tfd.Independent(tfd.Multinomial(
          total_count=1,
          logits=tf.stack([
              affine(DATA[:,0], tf.gather(b_time, IDX[:,0], axis=-1), (a_train + b_cost * DATA[:,1] + adj_AV_train)),
              affine(DATA[:,2], tf.gather(b_time, IDX[:,0], axis=-1), (b_cost * DATA[:,3] + adj_AV_SM)),
              affine(DATA[:,4], tf.gather(b_time, IDX[:,0], axis=-1), (a_car + b_cost * DATA[:,5] + adj_AV_car))
          ], axis=1)
        ),reinterpreted_batch_ndims=1)
    ])

mmnl_func().sample()
```

Full code on colab:
https://drive.google.com/file/d/10OBeDVNC4tN4c8Ro2SuYhw5YfGzpXnx4/view?usp=sharing

**Other info / logs**
Full tracebook is attached. Full code implements a sampler. Final error from full code is:
`ValueError: Dimensions must be equal, but are 6768 and 3 for '{{node JointDistributionSequential_1/log_prob/JointDistributionSequential_1_log_prob_IndependentJointDistributionSequential_1_log_prob_Multinomial/log_prob/JointDistributionSequential_1_log_prob_Multinomial/log_prob/mul}} = Mul[T=DT_FLOAT](value, JointDistributionSequential_1/log_prob/JointDistributionSequential_1_log_prob_IndependentJointDistributionSequential_1_log_prob_Multinomial/log_prob/JointDistributionSequential_1_log_prob_Multinomial/log_prob/LogSoftmax)' with input shapes: [6768,3], [1,3,6768].`
[output.txt](https://github.com/tensorflow/tensorflow/files/4540276/output.txt)

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.2.0-rc3](https://colab.research.google.com/gist/amahendrakar/8e8e4748b3664326e80821a4691db4ab/38947-2-2.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/cccb69088135ccf2469cec53108eb1ab/38947-tf-nightly.ipynb#scrollTo=5LR8sgPoHgGS). Please find the attached gist. Thanks!

**Comment by amahendrakar** [comment]
@jfhawkin,
Could you please check [this StackOverflow comment](https://stackoverflow.com/a/44956689) from a similar issue and let us know if it helps. Thanks!

**Comment by jfhawkin** [comment]
@amahendrakar,

I looked at the StackOverflow comment. They are building up neural network
layers from the data, so each of l2 and l3 builds on l1 (which is based on
the input data).

In my case, I have three independent calls to affine() based on the input
data. I ran the code through the debugger and it looks to me like on each
call the inputs (x, kernel_diag, and bias) are being passed as
python.framework.ops.Tensor. It then gives me the warning "AutoGraph could
not transform...". I can then run the code in the function through the
debugger and the return type is also a tensor. When I run my full code,
this warning appears to lead to an AssertionError and the ultimate
ValueError with dimension mismatch.

**Comment by jfhawkin** [comment]
I found a few responses to similar issues and the solution was downgrading gast to 0.2.2. However, this appears to be changed in recent updates to tensorflow. Many people were getting: `AssertionError: Bad argument number for Name: 3, expecting 4` with gast 0.3.X and I get the opposite when downgrading from 0.3.3 to 0.2.2 (i.e., `AssertionError: Bad argument number for Name: 4, expecting 3`).

**Comment by mdanatg** [comment]
This looks like the same issue as #38691 - it's a known issue with Spyder.

@jfhawkin could you try with tf-nightly (leave the gast version that it installs - it should be 0.3.3).

**Comment by jfhawkin** [comment]
I reran in Spyder and the prompt using tf-nightly. I get a similar set of warnings/errors. It now gives three potential reasons: (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. The first case doesn't apply and I tried the second by setting experimental_relax_shapes=True (no change to warnings). This suggests to me that it is the third case but, as I said before, it looks to me like I am passing tensors (could be wrong). I get the same result in colab.

**Comment by jfhawkin** [comment]
It appears that the warning I listed in the issue header may be solved. I ran it with tf.autograph.set_verbosity(3,True) and it says it transformed affine(). The first warning is: `WARNING:tensorflow:5 out of the last 9 calls to <function affine at 0x0000017AA8F08C18> triggered tf.function retracing.` but this appears to also be an issue with passing python rather than tensorflow objects.

**Comment by mdanatg** [comment]
Thank you. Yes, that is a different warning emitted by tf.function. https://github.com/tensorflow/tensorflow/commit/2eb9e7c2b68123002acab835711da90d35bebca3 should remove those warnings once it's included in tf-nightly. But if those continue to appear afterwards, please ping this thread or open up a new issue and we'll have a closer look.
