### ISSUE TITLE
Tensor Manipulation and Slicing Feature supported by Auto Gradient

### ISSUE THREAD

**Issue by amifunny** [tensorflow/tensorflow#38948]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):2.1.0
- Are you willing to contribute it (Yes/No):Yes

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**Yes, tf.Variable support slicing but assigning to it , it hinders the auto grad.

**Who will benefit with this feature?**Every One Who want to do more custom work and want more control over tensors

**Any Other info.**

**Comment by ravikyram** [comment]
@hksrathore 

Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!
