### ISSUE TITLE
UnrecognizedFlagError when using tf.vectorized_map() with lbfgs_minimize()

### ISSUE THREAD

**Issue by loipf** [tensorflow/tensorflow#38944]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.2
- Mobile device (e.g. iPhone UnrecognizedFlagErrortf8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.1.0   (v2.1.0-rc2-17-ge5bf8de)
- Python version: 3.7.6
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**
when trying to access the `tfp.optimizer.lbfgs_minimize()` - object parameters during a `tf.vectorized_map()` operation, it throws the error: `UnrecognizedFlagError: Unknown command line flag 'f'` as well as `ERROR:tensorflow:Got error while pfor was converting op name: "loop_body/PartitionedCall"`

**Describe the expected behavior**
you can simply extract the position of this object during the loop

**Standalone code to reproduce the issue**
the issue was originally created with following code on my laptop (with above mentioned versions) but can also be reproduced in this colab: 
https://colab.research.google.com/drive/1gOF9qTqzdjYmlbbugIYxzXlH7MpBsEbl

**Other info / logs** 
the large error traceback file is appended

[tf_vectorized_map_traceback.txt](https://github.com/tensorflow/tensorflow/files/4540178/tf_vectorized_map_traceback.txt)

**Comment by amahendrakar** [comment]
@loipf,
I was able to reproduce the error with [TF v2.2.0-rc3](https://colab.research.google.com/gist/amahendrakar/5007574fec22eea48ebad42bd700761f/38944-2-2.ipynb#scrollTo=wL6gGpxhkeA0). However, the issue seems to be fixed with the latest [TF-nightly](https://colab.research.google.com/gist/amahendrakar/b59a88f5e0254e2cf2099675385ccccc/38944-tf-nightly.ipynb) as I was able to run the code without any errors. Please find the attached gist. Thanks!

**Comment by loipf** [comment]
great! I can confirm that the tf-nighly build in combination with tfp-nightly fixes this problem
thanks a lot. this can be closed.
