### ISSUE TITLE
Failure to build tensorflow on centos 5.7 with gcc 4.8.5

### ISSUE THREAD

**Issue by jungle-cat** [tensorflow/tensorflow#3894]
### Environment info

Operating System:
CENTOS 5.7 with gcc 4.8.5

Bazel 0.1.3 without namespace-sandbox
### Problems:

When I build tensorflow using 

> bazel build -c opt --verbose_failures //tensorflow/tools/pip_package:build_pip_package

The error occurs :

> .............
> Unhandled exception thrown during build; message: namespace-sandbox not in [embedded_tools/WORKSPACE, embedded_tools/src/tools/android/java/com/google/devtools/build/android/README, embedded_tools/src/tools/android/java/com/google/devtools/build/android/AndroidResourceProcessor.java, embedded_tools/src/tools/android/java/com/google/devtools/build/android/MergedAndroidData.java, embedded_tools/src/tools/android/java/com/google/devtools/build/android/Converters.java, embedded_tools/src/tools/android/java/com/google/devtools/build/androi

It seems that the problems is due to disabling namespace-sandbox of bazel, anyone can help me with this?

**Comment by aselle** [comment]
Generally speaking tensorflow and bazel is not supported before CentOS 7. I am aware that people have gotten tensorflow built on CentOS 6, and so it may be possible to also do on CentOS 5, but it will probably require some ddebugging effort on your part. You should also post the entire build log (as an attachment).

**Comment by gunan** [comment]
Closing this issue, as building TensorFlow with any bazel version older than 0.4.1 is not possible anymore.
For a possible workaround for building tensorflow on RHEL, and possibly centos, you can check https://github.com/tensorflow/tensorflow/issues/7118
