### ISSUE TITLE
Memory leak on TF2.1 model.fit with validation_split

### ISSUE THREAD

**Issue by dannyfriar** [tensorflow/tensorflow#38945]
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.5
- GPU model and memory: No GPU

**Describe the current behavior**
Fitting a simple LSTM model causes memory leak

**Standalone code to reproduce the issue**
```
import os
import psutil

import numpy as np
from tensorflow.keras.layers import (
    LSTM,
    Bidirectional,
    Dense,
    Input,
)
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam


def dummy_model(n_classes, n_features, seq_length):
    input = Input(shape=(seq_length, n_features))
    main = Bidirectional(LSTM(128, return_sequences=False))(input)

    prediction = Dense(n_classes, activation="softmax")(main)
    optimiser = Adam(lr=1e-3)
    model = Model(inputs=[input], outputs=prediction)
    model.compile(optimiser, "categorical_crossentropy", metrics=["accuracy"])
    return model


def fit_model():
    x_train = np.random.random_sample((1000, 50, 100))
    x_train = x_train.astype(np.float32)
    y_train = np.zeros((1000, 10), dtype=np.float32)
    model = dummy_model(n_classes=10, n_features=100, seq_length=50)
    model.fit(
        x_train, y_train, epochs=1,
        validation_split=0.1, batch_size=64,
        verbose=0
    )


if __name__ == "__main__":
    process = psutil.Process(os.getpid())
    n = 20

    for i in range(n):
        fit_model()
        print(f"#--- Run {i + 1} of {n} memory used (MB): {process.memory_info().rss / 1e6}")
```

**Other info / logs** 
```
#--- Run 1 of 20 memory used (MB): 731.81184
#--- Run 2 of 20 memory used (MB): 991.137792
#--- Run 3 of 20 memory used (MB): 1027.985408
#--- Run 4 of 20 memory used (MB): 1089.724416
#--- Run 5 of 20 memory used (MB): 1127.616512
#--- Run 6 of 20 memory used (MB): 1165.471744
#--- Run 7 of 20 memory used (MB): 1211.96544
#--- Run 8 of 20 memory used (MB): 1247.653888
#--- Run 9 of 20 memory used (MB): 1272.410112
#--- Run 10 of 20 memory used (MB): 1289.478144
#--- Run 11 of 20 memory used (MB): 1298.57536
#--- Run 12 of 20 memory used (MB): 1317.429248
#--- Run 13 of 20 memory used (MB): 1346.781184
#--- Run 14 of 20 memory used (MB): 1369.145344
#--- Run 15 of 20 memory used (MB): 1402.55232
#--- Run 16 of 20 memory used (MB): 1409.634304
#--- Run 17 of 20 memory used (MB): 1413.599232
#--- Run 18 of 20 memory used (MB): 1419.091968
#--- Run 19 of 20 memory used (MB): 1450.14784
#--- Run 20 of 20 memory used (MB): 1468.604416
```

Issue also appears to occur with `2.2.0rc3`

Explicitly setting the following (as was recommended in this blog post - http://gregoryzynda.com/python/tensorflow/memory/leak/rnn/lstm/2019/10/17/lstm-memory-leak.html) appears to help mitigate this (although memory still increases):
```
tf.config.threading.set_intra_op_parallelism_threads(2)
tf.config.threading.set_inter_op_parallelism_threads(5)
```

As does explicitly running garbage collection `gc.collect()` after each iteration.

**Comment by ravikyram** [comment]
I was able to reproduce the issue in colab with TF 2.1.0 , 2.2.0rc3 . Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/b1726888ddd44b18ceb0174eeafd9779/untitled833.ipynb).Thanks!

**Comment by alimhanif** [comment]
Sorry, is it related with this? or not?
https://github.com/tensorflow/tensorflow/issues/38617

**Comment by dannyfriar** [comment]
@alimhanif I think #38617 is a different (that is specific to 2.2rc3 and related to distributed gpu training). This issue seems like it is due to the LSTM layer, I do not see the same memory increase without it

**Comment by qlzh727** [comment]
Thanks for reporting the issue. I did following experiments with latest tf-nightly 2.2.0.dev20200503, and it seems that it might be a issue for TF runtime.

1. I change to create model and data only once (move them from fit_model to be above the for loop before training), and the increasing of the memory usage still occurs.

2. I change the model structure to remove the LSTM and Bidirectional wrapper, and only use the Dense layer, and increasing of the memory usage still occurs.

With this observation, I will send this to someone of TF core team for further investigation.

**Comment by qlzh727** [comment]
Did one more test, it seems that the memory increase was greatly reduced with validation_split is not used. This indicates that keras model might have some leak when creating the validation dataset under the hood.

**Comment by dannyfriar** [comment]
Thanks @qlzh727 
I tried removing the validation_split (both creating the split manually and turning off validation altogether) using TF `2.2.0rc3` and the memory still increases in a similar way to the notebook shared by @ravikyram above.

I also tried changing the model structure to remove the LSTM and can confirm what you reported above, the memory usage still increases.

Please see the following [colab notebook](https://colab.research.google.com/drive/1s76eoH9lE21BiUFOESJVX2XeT1ACLCoy#scrollTo=_xyylnfl2W6G).

**Comment by kkimdev** [comment]
Could you try calling `tf.keras.backend.clear_session()` on every iteration?

**Comment by dannyfriar** [comment]
@kkimdev Yes, calling `tf.keras.backend.clear_session()` does not appear to help

**Comment by dannyfriar** [comment]
@qlzh727 I just tried this again with TF 2.2.0 on Ubuntu 18.04.3. I used the same script as in the original post but create the training/validation data once outside of the loop and use this instead of validation_split (same as the final cell of this [notebook](https://colab.research.google.com/drive/1s76eoH9lE21BiUFOESJVX2XeT1ACLCoy#scrollTo=_Blz6Tj01MTO). There still appears to be an increase in memory which I do not see if I run in a colab notebook.

**Comment by qlzh727** [comment]
@dannyfriar. Thanks for the update. 

I updated your code to also create the model outside of the for loop, which is the more standard behavior. With that there isn't much memory leak.

Having said that, the memory leak still appears when validation_split is used. I will focus on that.

/Users/scottzhu/tf-2.2/bin/python /Users/scottzhu/Library/Preferences/PyCharmCE2018.1/scratches/scratch_17.py
2020-06-01 20:50:38.363168: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-06-01 20:50:38.385048: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x13b428490 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-01 20:50:38.385063: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
#--- Run 1 of 20 memory used (MB): 424.79616
#--- Run 2 of 20 memory used (MB): 431.009792
#--- Run 3 of 20 memory used (MB): 433.84832
#--- Run 4 of 20 memory used (MB): 434.60608
#--- Run 5 of 20 memory used (MB): 435.093504
#--- Run 6 of 20 memory used (MB): 436.195328
#--- Run 7 of 20 memory used (MB): 437.420032
#--- Run 8 of 20 memory used (MB): 437.837824
#--- Run 9 of 20 memory used (MB): 438.714368
#--- Run 10 of 20 memory used (MB): 439.410688
#--- Run 11 of 20 memory used (MB): 440.037376
#--- Run 12 of 20 memory used (MB): 440.000512
#--- Run 13 of 20 memory used (MB): 440.000512
#--- Run 14 of 20 memory used (MB): 439.865344
#--- Run 15 of 20 memory used (MB): 440.037376
#--- Run 16 of 20 memory used (MB): 441.430016
#--- Run 17 of 20 memory used (MB): 441.430016
#--- Run 18 of 20 memory used (MB): 441.28256
#--- Run 19 of 20 memory used (MB): 441.704448
#--- Run 20 of 20 memory used (MB): 441.704448

Process finished with exit code 0

**Comment by qlzh727** [comment]
With fix in https://github.com/tensorflow/tensorflow/commit/ce2f9824eee904d60fdc0444ac8a82b217ea9149, the memory usage for validation_split is reduced.

Please note that I update the snippet to defined the model only once, and fit within the for loop. This is more aligned to normal workflow by user.

If you need to define multiple model in a loop, you might want to use keras.backend.clear_session() to remove unused the models in the keras global graph.

**Comment by qlzh727** [comment]
Memory log before change:
#--- Run 1 of 20 memory used (MB): 420.94592
#--- Run 2 of 20 memory used (MB): 455.458816
#--- Run 3 of 20 memory used (MB): 480.89088
#--- Run 4 of 20 memory used (MB): 504.799232
#--- Run 5 of 20 memory used (MB): 465.563648
#--- Run 6 of 20 memory used (MB): 485.797888
#--- Run 7 of 20 memory used (MB): 506.544128
#--- Run 8 of 20 memory used (MB): 526.76608
#--- Run 9 of 20 memory used (MB): 547.782656
#--- Run 10 of 20 memory used (MB): 487.981056
#--- Run 11 of 20 memory used (MB): 508.862464
#--- Run 12 of 20 memory used (MB): 528.904192
#--- Run 13 of 20 memory used (MB): 549.933056
#--- Run 14 of 20 memory used (MB): 570.032128
#--- Run 15 of 20 memory used (MB): 510.455808
#--- Run 16 of 20 memory used (MB): 530.501632
#--- Run 17 of 20 memory used (MB): 551.559168
#--- Run 18 of 20 memory used (MB): 571.408384
#--- Run 19 of 20 memory used (MB): 529.518592
#--- Run 20 of 20 memory used (MB): 549.376

Memory log after change:
#--- Run 1 of 20 memory used (MB): 441.933824
#--- Run 2 of 20 memory used (MB): 463.753216
#--- Run 3 of 20 memory used (MB): 465.801216
#--- Run 4 of 20 memory used (MB): 466.366464
#--- Run 5 of 20 memory used (MB): 467.0464
#--- Run 6 of 20 memory used (MB): 467.709952
#--- Run 7 of 20 memory used (MB): 468.668416
#--- Run 8 of 20 memory used (MB): 468.62336
#--- Run 9 of 20 memory used (MB): 474.35776
#--- Run 10 of 20 memory used (MB): 474.353664
#--- Run 11 of 20 memory used (MB): 474.472448
#--- Run 12 of 20 memory used (MB): 474.648576
#--- Run 13 of 20 memory used (MB): 474.697728
#--- Run 14 of 20 memory used (MB): 474.750976
#--- Run 15 of 20 memory used (MB): 474.804224
#--- Run 16 of 20 memory used (MB): 474.800128
#--- Run 17 of 20 memory used (MB): 474.857472
#--- Run 18 of 20 memory used (MB): 474.918912
#--- Run 19 of 20 memory used (MB): 475.086848
#--- Run 20 of 20 memory used (MB): 475.348992
