### ISSUE TITLE
TF 2.x release for CPU only

### ISSUE THREAD

**Issue by jetjodh** [tensorflow/tensorflow#38949]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.1

**Describe the feature and the current behavior/state.**
The current TF 2.x install size is very large and is not suitable for small size deployments due to many restrictions. A CPU only release would be very helpful in this case due to its smaller size than the GPU or combined release. 

A CPU only release will provide more flexibility to the user in terms of deployment options.

**Comment by freedomtan** [comment]
There are CPU-only version from some platforms already. Please check https://github.com/tensorflow/tensorflow/blob/master/README.md

**Comment by Saduf2019** [comment]
@jetjodh 
Could you please update as per above comment

**Comment by jetjodh** [comment]
Yes, I tried the link provided by @freedomtan and it worked. But this information about the cpu version is not mentioned here https://www.tensorflow.org/install/pip.
