### ISSUE TITLE
Impossible to create a simple LSTM layer with tensorflow > 2.1 version

### ISSUE THREAD

**Issue by q-55555** [tensorflow/tensorflow#38942]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Trying to follow these instructions : https://www.tensorflow.org/guide/keras/rnn

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
 
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tested on tf-nightly 2.2.0.dev20200422, tensorflow 2.2.0rc3, tensorflow 2.2.0rc2, tensorflow 2.2.0rc1, tensorflow 2.2.0rc0
- Python version: 3.7

- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:  10.1
- GPU model and memory: 

The following instructions is working with tensorflow 2.1 but do not work on tensorflow version > 2.1 in my environment. 

```
import collections
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers

model = tf.keras.Sequential()
model.add(layers.Embedding(input_dim=1000, output_dim=64))
model.add(layers.LSTM(128))
```

I get the following error in building LSTM layer:

`ValueError: Shape must be at least rank 3 but is rank 2 for '{{node BiasAdd}} = BiasAdd[T=DT_FLOAT, data_format="NCHW"](add, bias)' with input shapes: [?,512], [512].`

This is working correctly with tensorflow 2.1 and in google colab: https://colab.research.google.com/drive/1evEbvAtAElZqx3cqD4wCPJxC5OUmJeSp). 

It seems that tensorflow is using cached parameters (512 might be a batch size used in previous tests...)

**Comment by ravikyram** [comment]
@q-55555 

I have tried in colab with TF 2.1.0 and 2.2.0-rc3 and i am not seeing any issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/c3b61bdf9c6afbc099162ea820eef91a/untitled832.ipynb).Thanks!

**Comment by q-55555** [comment]
Thank you @ravikyram  

I have found the problem : for an unknown reason, in my environment %USERPROFILE%/.keras/keras.json had "image_data_format": "channels_first"... Changing to "image_data_format": "channels_last" fixed the problem.

**Comment by fthielke** [comment]
Although the issue was resolved, the bug mentioned here still persists: it is impossible to instantiate a Keras LSTM layer if the data_format was set to channels_first.

Are there plans to fix this regression?
