### ISSUE TITLE
Docs:  multi_worker_with_keras.ipynb shows init() instead of __init__()

### ISSUE THREAD

**Issue by robertlugg** [tensorflow/tensorflow#38946]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://github.com/tensorflow/docs/edit/master/site/en/tutorials/distribute/multi_worker_with_keras.ipynb

## Description of issue (what needs changing):
When rendered, the literal \_\_init\_\_ is replaced with init
### Clear description
\_\_init\_\_ is a "built-in" python function for classes.  In the ipynb source code it is correct.  However, when rendered at: https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras , it is incorrect.

For example, why should someone use this method? How is it useful?

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example?

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?
Yes, please see the notebook in the docs.  The text is:
```
Note: TF_CONFIG is parsed and TensorFlow's GRPC servers are started at the time MultiWorkerMirroredStrategy.init() is called, so TF_CONFIG environment variable must be set before a tf.distribute.Strategy instance is created.
```
vs
```
Note: TF_CONFIG is parsed and TensorFlow's GRPC servers are started at the time MultiWorkerMirroredStrategy.__init__() is called, so TF_CONFIG environment variable must be set before a tf.distribute.Strategy instance is created.
```
Notice that .init() is shown when .\_\_init\_\_() should be shown.

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style
No:  I didn't know how to escape the underscores, but I believe it is as in this report using a backslash before each underscore.

**Comment by dojafrat** [comment]
I'm new here, so potentially dumb question/observation....When I forked the repo and run the multi_worker_with_keras notebook I see the output to be fixed. Should this issue be marked as closed?

**Comment by ymodak** [comment]
Closing as this fixed and PR has merged. Thanks!
