### ISSUE TITLE
Random uniform is inconsistent given same seed values

### ISSUE THREAD

**Issue by deil87** [tensorflow/tensorflow#38954]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
  _I was trying to use one of example usages from tensorflow docs and wanted to make results reproducible. After investigation it looks to me that `gen_random_ops.random_uniform` is inconsistent given seeds. That is why I have written a test ( custom code)_
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
   _Darwin-18.0.0-x86_64-i386-64bit_
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: _No_
- TensorFlow installed from : _pip install tensorflow_
- TensorFlow version : _v2.1.0-rc2-17-ge5bf8de410 2.1.0_
- Python version: python version: _3.7.6_
- Bazel version (if compiling from source): _brew installation_
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**
`gen_random_ops.random_uniform` return different values even with same seeds
**Describe the expected behavior**
consistent behaviour is expected give same seeds

**Standalone code to reproduce the issue**
```
shape = (8,12)
dtype = 'float32'
seed = 5
seed2 = 1234
tf.random.set_seed(seed)
rnd = gen_random_ops.random_uniform(shape, dtype, seed=seed, seed2=seed2)
rnd2 = gen_random_ops.random_uniform(shape, dtype, seed=seed, seed2=seed2)
# rnd and rnd2 will be different
```

**Other info / logs** 
code does not throw exceptions. Just expected behaviour is different from results.

From `random_seed.py` I can see that probably it is expected behaviour but I don't understand why is that. This counter that keeps changing seed  by default is a way to avoid generation of same values? But usually for tests we need reproducibility. Does it mean that It should be done through re-setting of the `tf.random.set_seed(1234)`?

**Comment by Saduf2019** [comment]
@deil87 
Code provided seems incomplete please provide complete stand alone code for us to replicate the issue faced.

**Comment by deil87** [comment]
@Saduf2019 I have realised that this is probably not a bug but a feature. It is just a bit unexpected behaviour -  usually you don't need to re-run script or set seed one more time to get consistency. But `random_seed.py` explains that this is how it is done in tensorflow. I'm going to close this one.

**Comment by alextp** [comment]
Yes this is an undesirable property of the legacy stateful random uniform ops. Use either the generator API or the stateless random ops for sane behavior.
