### ISSUE TITLE
hlo_algorithm_blacklist.cc compilation fails

### ISSUE THREAD

**Issue by ericqu** [tensorflow/tensorflow#38951]
**System information**
- OS Platform and Distribution: Windows 10 (10.0.18363 N/A Build 18363)
- Mobile device if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): Source
- TensorFlow version: r.2.1
- Python version: 3.6.10
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.29.1
- GCC/Compiler version (if compiling from source): VS2019
- CUDA/cuDNN version: 10.1, 7.6.5
- GPU model and memory: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.607GHz coreCount: 28 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 451.17GiB/s

**Describe the problem**

I git cloned the tensorflow, followed the build instructions for a windows build...
the output from the configure script is:
```
build --action_env PYTHON_BIN_PATH="C:/Users/Eric/anaconda3/envs/compileTF/python.exe"
build --action_env PYTHON_LIB_PATH="C:/Users/Eric/anaconda3/envs/compileTF/lib/site-packages"
build --python_path="C:/Users/Eric/anaconda3/envs/compileTF/python.exe"
build:xla --define with_xla_support=true
build --config=xla
build --action_env CUDA_TOOLKIT_PATH="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="6.1"
build --config=cuda
build:opt --copt=/arch:AVX
build:opt --define with_default_optimizations=true
build --config monolithic
build --copt=-w --host_copt=-w
build --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=-D_USE_MATH_DEFINES
build --verbose_failures
build --distinct_host_configuration=false
build --define=override_eigen_strong_inline=true
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test --test_tag_filters=-benchmark-test,-no_oss,-oss_serial
test --build_tag_filters=-benchmark-test,-no_oss
test --test_tag_filters=-no_windows,-gpu
test --build_tag_filters=-no_windows,-gpu
build --action_env TF_CONFIGURE_IOS="0"
```

then I started the compilation with: 
`bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`

the error message is the following:
```
cl : Command line warning D9002 : ignoring unknown option '-std=c++14'
tensorflow/compiler/xla/service/gpu/hlo_algorithm_blacklist.cc(28): error C2131: expression did not evaluate to a constant
external/com_google_absl\absl/strings/string_view.h(186): note: a non-constant (sub-)expression was encountered
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

**Any other info / logs**
the code surrounding the error:
```c++
// MSVC requires the extra const. Without, it reports an
// "error C2131: expression did not evaluate to a constant".
constexpr const absl::string_view kDefaultBlacklist = R"pb(
)pb";
```
appears to indicate that such issue was already encounter before.

This issue appears in the context of trying to resolve issue #38867 .
This issue appears very close to issue #35796 .

**Comment by ericqu** [comment]
@ravikyram and @angerson , 

I am not a specialist in c++ however as I was stuck I changed the line with the error from:

```c++
constexpr const absl::string_view kDefaultBlacklist = R"pb(
)pb";

```
to 
`c++
constexpr absl::string_view kDefaultBlacklist = absl::string_view((const char *)"\n", (size_t) 1);
`

and was able to successfully compile. I am not sure that this is the right way of doing it though.

**Comment by amahendrakar** [comment]
@ericqu,
Thank you for the update.

Closing this issue as it is resolved. Please feel free to re-open if necessary.
