### ISSUE TITLE
How to convert TenorFlow model with functional ops to graph definition with no Tensorflow version installed?

### ISSUE THREAD

**Issue by gitgetcode** [tensorflow/tensorflow#38966]
In TensorFlow V2, functional control ops such if/while/for/case are introduced, if the model contains such functional control ops, how to convert them to graph definition?
In TensorFlow, there are some methods to transmit original node names correctly in file.
InstantiateFunction - AddDefaultAttrs
                                - helper.BuildNodeOutputIndex
				- helper.InstantiateNode
But in some other circustances if there is no TensorFlow installed, how to convert TenorFlow model with functional ops to graph definition?

**Comment by alextp** [comment]
It's a fairly complicated graph lowering step, and we currently don't have a standalone tool to do that.
