### ISSUE TITLE
Pip could not find version under 2.2 on Windows

### ISSUE THREAD

**Issue by CalePlut** [tensorflow/tensorflow#38962]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Pip
- TensorFlow version: 1.15
- Python version: 3.8
- Installed using virtualenv? pip? conda?: pip
- GPU model and memory:NVIDIA GeForce GTX1070, 8GB

*Describe the problem*
When attempting to install tensorflow 1.15 with pip on Windows 10, I receive an error that only various versions of 2.2 are available.

> C:\>pip3 install tensorflow==1.15
> ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3)
> ERROR: No matching distribution found for tensorflow==1.15

Problem also exists when trying to install another package with tensorflow<2.2 as a dependency - pip install magenta stops and gives the same error:

> ERROR: Could not find a version that satisfies the requirement tensorflow<2.0.0,>=1.15.0 (from magenta) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3)
> ERROR: No matching distribution found for tensorflow<2.0.0,>=1.15.0 (from magenta)

**Comment by ravikyram** [comment]
@CalePlut 

Please upgrade pip and try.
`python -m pip install --upgrade pip setuptools`.

 PIP install TF 1.15 is available.
Please see the gist [here](https://colab.sandbox.google.com/gist/ravikyram/b10a5760a72ec20d5dd793c91d4523bd/untitled835.ipynb). 
Can you downgrade python to 3.6 and see if it works.Thanks!

**Comment by CalePlut** [comment]
Downgrading to Python 3.6 worked, thanks.
