### ISSUE TITLE
EdgeTPU compiler creates a model with different behaviour

### ISSUE THREAD

**Issue by ianholing** [tensorflow/tensorflow#38961]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): Docker image latest-gpu-py3-jupyter
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 10.1
- GPU model and memory: Nvidia RTX 2080TI / 12 GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When I try to compile fot edgeTPU a full-quatized and fully working model it just shows a different not expected output

**Describe the expected behavior**
Same output for same input in both models: full quantized and compiled for EdgeTPU from the previous full quantized.

**Standalone code to reproduce the issue**
You can see the problem here
https://gist.github.com/ianholing/cbda145cfeb03124d6a286c619302aa6

And here there are anything you need to reproduce the notebook:
https://drive.google.com/open?id=1u9fH3PVmfmR4xXIJnXOPlx789eyKhVOS

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ziyeqinghan** [comment]
This should due to currently the input & output is float32 for full-quantization for tf.compat.v2.lite.TFLiteConverter in TF 2.1 even setting:
```
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
```
TFLite team will add this feature soon. 

The current workaround is to modify the type of input & output [here](https://github.com/tensorflow/tensorflow/blob/a07ca66517313dc0ed0f20c074f762e9d3129112/tensorflow/lite/tools/optimize/python/modify_model_interface.py)

**Comment by ianholing** [comment]
I tried in some TF versions even nightly and always same error, I don't know where this package is:
ModuleNotFoundError: No module named 'tensorflow.lite.tools'

**Comment by sushreebarsa** [comment]
@ianholing It looks like you are using an older Version of Tensorflow . Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? Thanks!

**Comment by ianholing** [comment]
Hi @sushreebarsa, you can close this issue if you want, this was more than one year ago.. at that time i tried all the latest versions but nowadays I don't keep the code to try again sorry.
