### ISSUE TITLE
tensorflow 

### ISSUE THREAD

**Issue by DeepVasoya08** [tensorflow/tensorflow#38967]
![error](https://user-images.githubusercontent.com/60228576/80450122-7446dc00-893e-11ea-8520-6ad83835c874.png)

**Comment by eualin** [comment]
@DeepVasoya08 -

I bet you have installed TF version 2.x and not 1.x. Can you please confirm? Try this: `tf.version.VERSION`.

If so, then, you simply have to refactor your code as follows:

```
import tensorflow as tf

foo = tf.constant(90.0)
bar = tf.constant(9.0)

@tf.function
def multiply(x, y):
    return x * y

print(multiply(x=foo, y=bar))
```

As you can see [here](https://www.tensorflow.org/guide/effective_tf2#functions_not_sessions), session are just functions in TF 2.x.

Hope this helps.

**Comment by mihaimaruseac** [comment]
Not a code issue but a user using TF1.x API in TF2.x code. Closing
