### ISSUE TITLE
Adam optimizing performance issue

### ISSUE THREAD

**Issue by christopher5106** [tensorflow/tensorflow#38972]
Hi,
Using tensorflow 2.2.0-rc3 on Ubuntu 18.04 and Python 3.8.2, I've converted my code for both compat.v1 and v2 which was required by tf2onnx.
There is a huge difference in speed between v1 and v2 and I was wondering how to solve this.
My v2 implementation is:
```python
	built_model = tf.keras.Model(inputs=model.inputs, outputs=model.outputs)
	model.load_weights()

	@tf.function
	def train_fn(inputs, targets):
		with tf.GradientTape() as tape:
			outputs = built_model(inputs)
			loss, metrics, _ = dataset.loss(outputs, targets)

		gradients = tape.gradient(loss, built_model.trainable_variables)
		optimizer.apply_gradients(zip(gradients, built_model.trainable_variables))
		return loss, metrics, learning_rate, global_step
```

while my v1 is:

```python
	session = tf.compat.v1.Session()
	tf.compat.v1.keras.backend.set_session(session)
	model.load_weights(session=session)

	loss, metrics, targets_pl = dataset.loss(model.outputs)
	tvars = tf.compat.v1.trainable_variables()
	gvs = optimizer.get_gradients(loss, tvars)
	train_op = optimizer.apply_gradients(zip(gvs, tvars))

	def train_fn(inputs, targets):
		loss_, _, global_step_, metrics_, lr_ = session.run([loss, train_op, global_step, metrics, learning_rate], feed_dict=dict(zip(model.inputs+targets_pl, inputs+targets)))
		return loss_, metrics_, lr_, global_step_
```

I also have a predict function that is as fast. It looks like the derivative is slow. 
I would like to migrate everything to v2.
Thank you for your help.

**Comment by Saduf2019** [comment]
@christopher5106
code shared is not indented and incomplete to replicate, can you please provide complete code for us to replicate or if possible please share a colab gist for us to analyse. Thanks!

**Comment by christopher5106** [comment]
Here it is: https://colab.research.google.com/drive/1GscwkqrH5KqP3hBD9o2A2DYqQuG4rQzK
Just set eager=True to use API v2, otherwise it will use compat.v1 runs.

Running this code on our server with compat.v1 gives a duration of 21 s per epoch:

T. 100/100 - il 9.25     - lr 0.001epoch duration 26.57380199432373

Epoch 2/10
T. 100/100 - il 9.55     - lr 0.001epoch duration 21.644425630569458

Epoch 3/10
T. 100/100 - il 9.15     - lr 0.001epoch duration 21.62645936012268

while using it locally gives 

T. 100/100 - il 9.3      - lr 0.001epoch duration 49.872514486312866

Epoch 2/10
T. 100/100 - il 9.32     - lr 0.001epoch duration 38.29377722740173

Epoch 3/10
T. 100/100 - il 9.28     - lr 0.001epoch duration 38.43030595779419

**Comment by Saduf2019** [comment]
@christopher5106 
I am unable to access the shared code due to denied permission.

**Comment by christopher5106** [comment]
I changed permissions

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/e5ca930415d270d760186e8277f76d52/38972ipynb.ipynb)

**Comment by gowthamkpr** [comment]
@christopher5106 Can you please take a look at this [issue](https://stackoverflow.com/questions/58441514/why-is-tensorflow-2-much-slower-than-tensorflow-1) and let me know if it helps.

**Comment by christopher5106** [comment]
I'm not sure what you mean by that. Of course, I'm using the TF2 @function as you can see in the code.

**Comment by rohan100jain** [comment]
I was able to identify and debug the issue - the problem was that we were forcing all the embedding layer variables onto the CPU and that was slowing down the model. https://github.com/tensorflow/tensorflow/commit/46f7108d78c6a3c0854fe66ce1cd92e5ebb3d6e2?diff=split should fix the issue and from some preliminary testing its probably even 5-10% faster than before (not rigorously tested though)

**Comment by christopher5106** [comment]
I confirm it is faster by  about 5% now. Thank you!
