### ISSUE TITLE
How to check if a tensor is empty in TensorFlow

### ISSUE THREAD

**Issue by Dee-Ma** [tensorflow/tensorflow#38976]
Hi there,

I am just using TensorFlow to train a CNN model. I used a command:

    t_iteration = tf.placeholder('int32', [], name='t_iteration') to initialize a tensor with shape of (0,).

I would want to know how to judge if the tensor t_iteration is empty? I have tried to use

    x = tf.constant(3)
    y = tf.constant(5)
     idx0 = tf.shape(t_iteration)
            A = tf.cond(tf.cast(idx0 == 0, tf.bool),
                                        lambda: tf.multiply(x, 17),
                                        lambda: tf.add(y, 23))
But I found that this method didn't work-as the `idx0' always equals to 0 even the tensor has not been assigned any value.

How to solve this tricky issue?

Thanks!

**Comment by Dee-Ma** [comment]
Hi there,

I am just using TensorFlow to train a CNN model. I used a command:

    t_iteration = tf.placeholder('int32', [], name='t_iteration') to initialize a tensor with shape of (0,).

I would want to know how to judge if the tensor t_iteration is empty? I have tried to use

    x = tf.constant(3)
    y = tf.constant(5)
     idx0 = tf.shape(t_iteration)
            A = tf.cond(tf.cast(idx0 == 0, tf.bool),
                                        lambda: tf.multiply(x, 17),
                                        lambda: tf.add(y, 23))
But I found that this method didn't work-as the `idx0' always equals to 0 even the tensor has not been assigned any value.

How to solve this tricky issue?

Thanks!

**Comment by saahiluppal** [comment]
Refer to stackoverflow here:
https://stackoverflow.com/questions/50529309/how-to-check-if-a-tensor-is-empty-in-tensorflow

Quick Note:
placeholder is a tf1.x module.  if you are using tf2.x, you have to use tf v1 compatibility, refer to doc here:
https://www.tensorflow.org/api_docs/python/tf/compat/v1/placeholder

**Comment by Saduf2019** [comment]
@Dee-Ma 

This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.


please check to [link](https://stackoverflow.com/questions/50529309/how-to-check-if-a-tensor-is-empty-in-tensorflow) for reference

**Comment by baxterai** [comment]
Tensorflow requires a function to check if a tensor is empty
