### ISSUE TITLE
Error of installation

### ISSUE THREAD

**Issue by Sim0xx001** [tensorflow/tensorflow#38973]
**System information**
- Windows 10 Pro
- Python version: 3.8.2
- GPU model and memory: 
   -GeForce GTX 1080 Ti
   - 19281 MB

**Describe the problem**

Hi everyone, I had a problem on installing Tensorflow 2.1.0 via pip on Windows; as soon as i use this command i get this error:
    pip install tensorflow
    ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
    ERROR: No matching distribution found for tensorflow
How can I fix this problem?

**Comment by amahendrakar** [comment]
@Sim0xx001,
TensorFlow 2.1 does not support Python 3.8. Instead could you please try installing TensorFlow v2.2.0rc3 using the following command.

`pip install tensorflow==2.2.0rc3`

Thanks!

**Comment by Sim0xx001** [comment]
Sure, I will try. Thank you so much!

**Comment by Sim0xx001** [comment]
It doesn't work, it returns the same error. Could it be the version of pip? I've installed pip 20.0.2

**Comment by oke-aditya** [comment]
You need MS Visual C++ redistributable as well. Please have a look at this issue as well #38916

**Comment by Sim0xx001** [comment]
So if I install MS Visual C++ I will be able to execute pip install tensorflow? If I need to wait until it will be supported for python 3.8 it is not a problem because at the moment it is only a school project and I'm using Google Colab, that works perfectly. Anyway thanks you all for your help!

**Comment by oke-aditya** [comment]
> 
> 
> So if I install MS Visual C++ I will be able to execute pip install tensorflow? If I need to wait until it will be supported for python 3.8 it is not a problem because at the moment it is only a school project and I'm using Google Colab, that works perfectly. Anyway thanks you all for your help!

No see the complete installation steps [here](https://www.tensorflow.org/install/pip#windows)

You need Visual C++ as well. And supported python version 3.8 is not supported as of now. So supported python version with proper visual C++ installation is required. Then a `pip install tensorflow` will be fine.

**Comment by Sim0xx001** [comment]
Ok, so I will install it; thank you so much!

**Comment by amahendrakar** [comment]
@Sim0xx001,
Is this still an issue? Please feel free to close the issue if resolved. Thanks!

**Comment by Sim0xx001** [comment]
Yes, it is. But it's all about time, I will wait!
