### ISSUE TITLE
mismatching quantization parameters(scale and zero point)

### ISSUE THREAD

**Issue by Eashwar93** [tensorflow/tensorflow#38978]
**System information**
- Linux Ubuntu 18.04  x86-CPU
- TensorFlow installed from binary
- TensorFlow version 1.15 - GPU

**Command used to run the converter or code if you’re using the Python API**

`import tensorflow as tf
import numpy as np

def representative_dataset_gen():
  for _ in range(100):
    fake_image = np.random.random((1,432,368,3)).astype(np.float32)
    yield [fake_image]

graph_pb = 'graph_freeze.pb'
inp = ['image']
out = ['Openpose/concat_stage7']
converter=tf.lite.TFLiteConverter.from_frozen_graph(
        graph_pb, inp, out,input_shapes={"image":[1,432,368,3]})
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
tflite_model = converter.convert()

f = open("tflite_model/mobilenet_thin_openpose_opt_fullint_tf1.tflite", "wb")
f.write(tflite_model)

f.close()

print("conversion complete")
`
**GraphDef used for conversion**
https://drive.google.com/file/d/1uMdkXXklwDNczD5ZGQR73Rkg9MFEax82/view?usp=sharing

**converted model**
https://drive.google.com/file/d/1BZ0gVX00Vnqhthx_wxmMXQAbkisSAftN/view?usp=sharing

**Failure details**
I'm currently trying to convert a graghdef file into a fully quantized tflite model. I want to use Coral Edge TPU for inference for which the converted TFLite model needs to be passed through EdgeTPU Compiler. Unfortunately the converted TFlite model is rejected by the compiler. Upon Investigation with a person from Coral Team he pointed me out to this "There is a layer name Openpose/MConv_Stage3_concat with 2 preceeded layers that has mismatching quantization parameters(scale and zero point)"  

You can also take a look at the discussion in the issues thread pertaining to the Coral EdgeTPU Implementation. #https://github.com/google-coral/edgetpu/issues/100#issue-604992155
Would be nice if I could fix the issue.

Thanks

**Comment by amahendrakar** [comment]
Was able to reproduce the issue. Please find the gist [here](https://colab.research.google.com/gist/amahendrakar/6a2647d6e1e42f6e91e77f547480460c/38978.ipynb). Thanks!

**Comment by Eashwar93** [comment]
@jvishnuvardhan Is the issue fixed by any chance?

**Comment by OmriTreidel** [comment]
Does this issue occurs on TF nightly?

**Comment by Eashwar93** [comment]
I actually converted the model using a stable 1.x version of tf, haven't tried with tf-nightly

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
