### ISSUE TITLE
[TF2.2rc3] dict of tensors as an input of a keras layer

### ISSUE THREAD

**Issue by tanguycdls** [tensorflow/tensorflow#38983]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary pip
- TensorFlow version (use command below): 2.2rc3
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
When we create a keras layer which takes a dict as input the behavior of the layer is not always consistent: 
we create a custom layer such as : 

```
class EmbeddingMerger(tf.keras.layers.Layer):
  def __init__(self, list_features, **kwargs):
    super().__init__(**kwargs)
    self.embeddings = {feature: Embedding(10, 3) for feature in list_features}
  def call(self, inputs):
    tensors = [self.embeddings[col](inputs[col]) for col in inputs]
    return Add()(tensors)
```

We can create a model from it:

```
list_features = ['feature_1', 'feature_2']
feature_1 = tf.constant([0, 1, 3])
feature_2 = tf.constant([1, 2, 4])
f = {'feature_1': feature_1,
     'feature_2': feature_2}
f_inputs = {'feature_1': Input(shape=(), name='feature_1'),
            'feature_2': Input(shape=(), name='feature_2')}
out = EmbeddingMerger(list_features)(f_inputs)
model = Model(f_inputs, out)
```

If we pass to the model:
- the dict with the two features with the correct names **it works as expected.** (called truth) ({'feature_1'; feature_1, 'feature_12: feature_2})`
- the dict with the two features but dict inserted in the wrong order : **gives same result as above** `({'feature_2'; feature_2, 'feature_1': feature_1})`
- the dict with only one feature  breaks with an assertion error because ** it cannot compute such result its the good behavior ** `({'feature_1': feature_1})`
- the dict with the two features and one additional key of name 'test' : **same result as truth which is the correct behavior ( ignoring the feature not used by the layer.)** `({'feature_1': feature_1, 'feature_2': feature_2, 'test': feature_2})`
- a dict with key feature_1 but not feature_2 and one additional key 'test' of value feature_2 : **it gives a result which is not the same as the truth...** `({'feature_1': feature_1, 'test': feature_2})`
> That one should not be calculable since we did not pass 'feature_2'

The same behavior happens with 3, 4 etc... keys I think i can extrapolate that if the correct keys are available everything is fine and the calculation is correct. However if one feature is missing it will take another feature in the dict and use it as it is. 

**Describe the expected behavior**
If the keys needed to run are not available always break with an assertion error. 

**Standalone code to reproduce the issue**
https://colab.research.google.com/gist/tanguycdls/552d6c5f02d8aff0b03fe1ad93825b52/untitled5.ipynb 
Code to do the experiments above. ping me for more use cases.

**Comment by ymodak** [comment]
This behavior is not seen in TF 2.1.0 version. See [GitHub gist](https://colab.research.google.com/gist/ymodak/ec2d0015292fc6b433881fd28bb74439/untitled9.ipynb)

**Comment by goldiegadde** [comment]
@tanguycdls With the latest tf-nightly this issue has been fixed. Am closing this issue, but please reopen if thats not the case for you.
