### ISSUE TITLE
model.save raise ValueError: If specifying TensorSpec names for nested structures, either zero or all names have to be specified.

### ISSUE THREAD

**Issue by neilteng** [tensorflow/tensorflow#38985]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
I am using colab to reproduce the issue and the ipynb is attached below.

You can collect some of this information using our environment capture
tf.version.GIT_VERSION: v1.12.1-30689-g428cdeda09
tf.version.VERSION: 2.2.0-dev20200428

**Describe the current behavior**
cannot save the keras model with tft layer for serving.

**Describe the expected behavior**
successifully save the model and serve it like this example: https://github.com/tensorflow/transform/blob/master/examples/census_example_v2_test.py

**Standalone code to reproduce the issue**
https://drive.google.com/open?id=1h2QIX_QZetIzSuG0J6lNWkHoSa2nnIyS

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

error is show in the last cell of the colab notebook.

**Comment by neilteng** [comment]
There is a similar issue I found here: https://github.com/tensorflow/tensorflow/issues/38465. But I am not using the graphics api and I cannot find a solution from that ticket neither.

**Comment by Saduf2019** [comment]
@neilteng 
I ran the code shared, and do not face the same error faced by you. Please find [the gist ](https://colab.sandbox.google.com/gist/Saduf2019/c87c26439e009db172c8408a38d2f5ee/untitled162.ipynb)for the same.

**Comment by neilteng** [comment]
Sorry for the inconvenience, the old one rely on some files in the directory. I have delete unnecessary code. And here is the new version:

https://drive.google.com/open?id=1h2QIX_QZetIzSuG0J6lNWkHoSa2nnIyS

**Comment by neilteng** [comment]
I guess it is related to tf.feature_column?

**Comment by Saduf2019** [comment]
@neilteng 
I ran the code shared and face a different error, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/e2a7ae5200a3a1868013c56feff09cc7/untitled165.ipynb). Thanks!
