### ISSUE TITLE
Does not compile on windows not even close why bother

### ISSUE THREAD

**Issue by sr99622** [tensorflow/tensorflow#38999]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@sr99622 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in the [Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Thanks!

**Comment by sr99622** [comment]
**ENVIRONMENT**

Windows 10
bazel 2.0.0
MSVC 2019
Python 3.6.8
Tensorflow r2.2

**BUILD COMMAND**

bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package

*ERROR MESSAGE**

C:/users/sr996/tensorflow/tensorflow/core/lib/monitoring/BUILD:176:1: C++ compilation of rule '//tensorflow/core/lib/monitoring:percentile_sampler' failed (Exit 2)
tensorflow/core/lib/monitoring/percentile_sampler.cc(32): error C2679: binary '=': no operator found which takes a right-hand operand of type 'initializer list' (or there is no acceptable conversion)
.\tensorflow/core/lib/monitoring/percentile_sampler.h(71): note: could be 'tensorflow::monitoring::PercentileSamplerCell::Sample &tensorflow::monitoring::PercentileSamplerCell::Sample::operator =(tensorflow::monitoring::PercentileSamplerCell::Sample &&)'
.\tensorflow/core/lib/monitoring/percentile_sampler.h(71): note: or       'tensorflow::monitoring::PercentileSamplerCell::Sample &tensorflow::monitoring::PercentileSamplerCell::Sample::operator =(const tensorflow::monitoring::PercentileSamplerCell::Sample &)'
.\tensorflow/core/lib/monitoring/percentile_sampler.h(68): note: or       'bool tensorflow::monitoring::PercentileSamplerCell::Sample::operator =(void *) const'
tensorflow/core/lib/monitoring/percentile_sampler.cc(32): note: while trying to match the argument list '(tensorflow::monitoring::PercentileSamplerCell::Sample, initializer list)'
tensorflow/core/lib/monitoring/percentile_sampler.cc(76): error C2440: 'initializing': cannot convert from 'initializer list' to 'tensorflow::monitoring::PercentilePoint'
tensorflow/core/lib/monitoring/percentile_sampler.cc(76): note: No constructor could take the source type, or constructor overload resolution was ambiguous

**Comment by sr99622** [comment]
This error can be removed by

  struct Sample sample;
  sample.nstime = nstime;
  sample.sample = sample;
  //samples_[next_position_] = {nstime, sample};
  sample_[next_position_] = sample;

However this is just a single problem

**NEXT ERROR**
ERROR: C:/users/sr996/tensorflow/tensorflow/core/BUILD:2307:1: C++ compilation of rule '//tensorflow/core:framework_internal_impl' failed (Exit 2)
.\tensorflow/core/util/bcast.h(131): error C2988: unrecognizable template declaration/definition
.\tensorflow/core/util/bcast.h(131): error C2059: syntax error: '('
tensorflow/core/util/bcast.cc(21): error C2653: 'BCast': is not a class or namespace name
tensorflow/core/util/bcast.cc(21): error C2146: syntax error: missing ';' before identifier 'FromShape'
tensorflow/core/util/bcast.cc(21): error C2143: syntax error: missing ';' before '{'
tensorflow/core/util/bcast.cc(21): error C2447: '{': missing function header (old-style formal list?)
tensorflow/core/util/bcast.cc(30): error C2653: 'BCast': is not a class or namespace name

**Comment by sr99622** [comment]
And then there's this, and yes I set the BAZEL_VC environment variable

ERROR: C:/users/sr996/_bazel_sr996/g37aiu74/external/llvm-project/llvm/BUILD:3980:1: C++ compilation of rule '@llvm-project//llvm:text_api' failed (Exit 2)
external/llvm-project/llvm/include\llvm/Support/Compiler.h(88): fatal error C1189: #error:  LLVM requires at least MSVC 2017.

**Comment by gunan** [comment]
Our CI has been able to build TF just fine both at master and 2.2 branches, so I am not sure what issues you are running into.

There is still a lot of information missing.
Did you run `./configure`?
I see that you added `--config=cuda` but you do not include which CUDA version you are trying to build with.
Which commit on r2.2 branch are you synced to?
Please include as much information as possible if you need help.

**Comment by sr99622** [comment]
It would appear that the root cause of the problem lies with how bazel generates the BUILD file.  My theory is that bazel generates the BUILD file on the initial run, then uses that for parameter initialization, ignoring the environment variable settings after that.  This situation would arise if you have multiple MSVC installations and inadvertently used the wrong one on the first run.  Subsequent changes to the BAZEL_VC variable seem to be ignored.  The solution seems to be to delete entirely the _bazel_%USERNAME% folder in your home directory, thus forcing bazel to re-build it from scratch and incorporate the current environment variable.

**Comment by sr99622** [comment]
Thank you so much for your help, it is greatly appreciated

**Comment by gunan** [comment]
Yes, if anything changes in your environment, you definitely need to clear your bazel cache. You can do that manually, or you can run `bazel clean --expunge`

Were you able to successfully build?

**Comment by sr99622** [comment]
Yes I was able to compile successfully, thank you :)
