### ISSUE TITLE
Speech Command Recognition example crashes with GPUDelegate

### ISSUE THREAD

**Issue by amitDaMan** [tensorflow/tensorflow#38991]
Tensorflow lite issue:

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes:

In SpeechActivity when the interpreter is created:
(https://github.com/tensorflow/examples/blob/master/lite/examples/speech_commands/android/app/src/main/java/org/tensorflow/lite/examples/speech/SpeechActivity.java line: 182)

(deprecated)
tfLite = new Interpreter(loadModelFile(getAssets(), actualModelFilename));

I change to:
      Interpreter.Options options = new Interpreter.Options();
      options.addDelegate(new GpuDelegate());
      options.setNumThreads(1);
      tfLite = new Interpreter(loadModelFile(getAssets(), actualModelFilename), options);

**Standalone code to reproduce the issue**
I have an instrumented test that reproduces the bug, I will attach it

**Crashes with GpuDelegate, does not crash with NnapiDelegate**

(Change to .java for use, also include the proper dependencies in gradle, and create the proper directories for gradle to find and build out test: androidtest->java-> etc)
[SpeechTest.txt](https://github.com/tensorflow/tensorflow/files/4547752/SpeechTest.txt)

**Comment by impjdi** [comment]
can you attach the tflite model?

**Comment by amitDaMan** [comment]
There are two ways of obtaining the model as described on the readme page. Through the download_model.gradle, or manually downloading it via the link.
https://github.com/tensorflow/examples/tree/master/lite/examples/speech_commands/android

But just for clarity I will zip the one specifically in my project

[conv_actions_frozen.zip](https://github.com/tensorflow/tensorflow/files/4561286/conv_actions_frozen.zip)

**Comment by amitDaMan** [comment]
bump

**Comment by impjdi** [comment]
Thank you for the attached model.  `AudioSpectrogram` & `Mfcc` is not an op that exists in the GPU delegate.  What's puzzling to me is that the tensor dimensions not matching.  Currently, most of the input/output tensors of each op are scalar without tensor dimensions.  For TFLite GPU, tensor shapes need to be well-defined.

**Comment by amitDaMan** [comment]
Hi @impjdi,
Thanks for the reply. I have some questions regarding this information. 
1) How do you know which operations are supported by GPU delegate, is there a list?
2) How do you obtain information regarding each op in the graph. aka, its shape/dimensions?

**Comment by impjdi** [comment]
1. `//tensorflow/lite/delegates/gpu/common/model_builder.cc` has the information you're looking for.

2. We don't obtain it from the graph but from the tensor.  If you look at the definition of `struct TfLiteTensor`, that information is embedded there.  If that information is missing, it's considered a scalar (which is incorrect).  I am not familiar with the CPU execution and how it determines the shapes; GPU requires them to be set in advance.

**Comment by amitDaMan** [comment]
Thanks for the info, I appreciate it.

When creating an interpreter with the Gpudelegate option with a model the gpu delegate doesnt support, would it be possible to throw an exception, instead of crashing the process and generating a tombstone... then that exception can be caught, and an interpreter can be created on the cpu, or NnapiDelegate.
  
Something like "OperationNotSupportedException"

**Comment by impjdi** [comment]
Absolutely.  It's not supposed to crash, and if it does, it's a bug on our end.

**Comment by impjdi** [comment]
@srjoglekar246 

Can you assign this to the Java API owner to take a look so that it doesn't crash, but rather throws an exception?

**Comment by srjoglekar246** [comment]
@amitDaMan The Interpreter shouldn't crash if the delegate does not support one or more ops. It just delegates as many ops as it can, and runs the rest on CPU. Can you provide details of what error you see? Or where it is originating?

Throwing an exception for unsupported ops is a little tricky, since many models (like the SSD) do contain some ops that should be run on CPU - while the rest are handled by GPU (which is expected).

**Comment by amitDaMan** [comment]
Hi @srjoglekar246,

To reiterate above, the issue is regarding the Speech Commands example app:
https://github.com/tensorflow/examples/blob/master/lite/examples/speech_commands/android/README.md

The model in question takes in two inputs:
float[][] floatInputBuffer = new float[RECORDING_LENGTH][1]; //recording length is 16000
int[] sampleRateList = new int[] {SAMPLE_RATE}; //Sample Rate is 16000

and according to @impjdi: 
includes AudioSpectrogram & Mfcc which are unsupported by the Gpudelegate

In the app SpeechActivity:182:
https://github.com/tensorflow/examples/blob/master/lite/examples/speech_commands/android/app/src/main/java/org/tensorflow/lite/examples/speech/SpeechActivity.java

`tfLite = new Interpreter(loadModelFile(getAssets(), actualModelFilename));
`
I replace that line with:

```
Interpreter.Options opts = new Interpreter.Options();
opts.addDelegate(new GpuDelegate());
opts.setNumThreads(1);
tfLite = new Interpreter(loadModelFile(getAssets(), actualModelFilename), opts);
```
And it crashes.

Note that it will work for NNAPI:
```
Interpreter.Options opts = new Interpreter.Options();
opts.addDelegate(new NnApiDelegate());
opts.setNumThreads(1);
tfLite = new Interpreter(loadModelFile(getAssets(), actualModelFilename), opts);
```

As well as specifying no delegate:
```
Interpreter.Options opts = new Interpreter.Options();
opts.setNumThreads(1);
tfLite = new Interpreter(loadModelFile(getAssets(), actualModelFilename), opts);
```
As for the crash:
when it gets to:
`tfLite = new Interpreter(loadModelFile(getAssets(), actualModelFilename), opts);`

logcat will begin to output:
--------- beginning of crash
09-25 12:10:16.722 21335 21335 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x30 in tid 21335 (examples.speech), pid 21335 (examples.speech)
09-25 12:10:16.984 21410 21410 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
09-25 12:10:16.986  1300  1300 I /system/bin/tombstoned: received crash request for pid 21335
09-25 12:10:16.988 21410 21410 I crash_dump64: performing dump of process 21335 (target tid = 21335)
09-25 12:10:17.018 21410 21410 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-25 12:10:17.018 21410 21410 F DEBUG   : Build fingerprint: 'qti/kona/kona:10/QKQ1.190918.001/eng.lnxbui.20190924.230323:userdebug/test-keys'
09-25 12:10:17.018 21410 21410 F DEBUG   : Revision: '0'
09-25 12:10:17.018 21410 21410 F DEBUG   : ABI: 'arm64'
09-25 12:10:17.020 21410 21410 F DEBUG   : Timestamp: 2019-09-25 12:10:17+0000
09-25 12:10:17.020 21410 21410 F DEBUG   : pid: 21335, tid: 21335, name: examples.speech  >>> org.tensorflow.lite.examples.speech <<<
09-25 12:10:17.020 21410 21410 F DEBUG   : uid: 10206
09-25 12:10:17.020 21410 21410 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x30
09-25 12:10:17.020 21410 21410 F DEBUG   : Cause: null pointer dereference
09-25 12:10:17.020 21410 21410 F DEBUG   :     x0  00000077d889b950  x1  00000078c7e62a0c  x2  0000000000000000  x3  0000007fd42cb9d0
09-25 12:10:17.020 21410 21410 F DEBUG   :     x4  0000000000000003  x5  0000000000000000  x6  0000000000000000  x7  0000000000000000
09-25 12:10:17.020 21410 21410 F DEBUG   :     x8  0000007fd42cb938  x9  0000000000000030  x10 0000007831a23d68  x11 00000000ffffffff
09-25 12:10:17.021 21410 21410 F DEBUG   :     x12 0000000000000000  x13 fffffffffc000000  x14 0000000000000010  x15 0000000400000000
09-25 12:10:17.021 21410 21410 F DEBUG   :     x16 00000078c3b138f0  x17 00000078c3b05070  x18 0000000000000000  x19 0000007fd42cb938
09-25 12:10:17.021 21410 21410 F DEBUG   :     x20 0000000000000003  x21 0000000000000000  x22 0000007fd42cb698  x23 00000078c7e62a00
09-25 12:10:17.021 21410 21410 F DEBUG   :     x24 00000078c7fc2020  x25 00000077d889b950  x26 0000000000000003  x27 00000078c7fc2020
09-25 12:10:17.021 21410 21410 F DEBUG   :     x28 0000000000000070  x29 0000007fd42cb4a0
09-25 12:10:17.021 21410 21410 F DEBUG   :     sp  0000007fd42cb3c0  lr  00000077d750ca64  pc  00000077d750e804
09-25 12:10:17.150 21410 21410 F DEBUG   :
09-25 12:10:17.150 21410 21410 F DEBUG   : backtrace:
09-25 12:10:17.150 21410 21410 F DEBUG   :       #00 pc 00000000000e8804  /data/app/org.tensorflow.lite.examples.speech-w2DgG080sdMY8xFF-l2Xbg==/lib/arm64/libtensorflowlite_gpu_jni.so
09-25 12:10:17.150 21410 21410 F DEBUG   :       #01 pc 00000000000e6a60  /data/app/org.tensorflow.lite.examples.speech-w2DgG080sdMY8xFF-l2Xbg==/lib/arm64/libtensorflowlite_gpu_jni.so
09-25 12:10:17.150 21410 21410 F DEBUG   :       #02 pc 00000000000d8a88  /data/app/org.tensorflow.lite.examples.speech-w2DgG080sdMY8xFF-l2Xbg==/lib/arm64/libtensorflowlite_gpu_jni.so
09-25 12:10:17.150 21410 21410 F DEBUG   :       #03 pc 00000000000d960c  /data/app/org.tensorflow.lite.examples.speech-w2DgG080sdMY8xFF-l2Xbg==/lib/arm64/libtensorflowlite_gpu_jni.so
09-25 12:10:17.150 21410 21410 F DEBUG   :       #04 pc 000000000001d8cc  /data/app/org.tensorflow.lite.examples.speech-w2DgG080sdMY8xFF-l2Xbg==/lib/arm64/libtensorflowlite_gpu_jni.so
09-25 12:10:17.151 21410 21410 F DEBUG   :       #05 pc 000000000001cfb0  /data/app/org.tensorflow.lite.examples.speech-w2DgG080sdMY8xFF-l2Xbg==/lib/arm64/libtensorflowlite_gpu_jni.so
09-25 12:10:17.151 21410 21410 F DEBUG   :       #06 pc 0000000000147bf0  /data/app/org.tensorflow.lite.examples.speech-w2DgG080sdMY8xFF-l2Xbg==/lib/arm64/libtensorflowlite_jni.so
09-25 12:10:17.151 21410 21410 F DEBUG   :       #07 pc 0000000000147854  /data/app/org.tensorflow.lite.examples.speech-w2DgG080sdMY8xFF-l2Xbg==/lib/arm64/libtensorflowlite_jni.so
09-25 12:10:17.151 21410 21410 F DEBUG   :       #08 pc 0000000000147598  /data/app/org.tensorflow.lite.examples.speech-w2DgG080sdMY8xFF-l2Xbg==/lib/arm64/libtensorflowlite_jni.so
09-25 12:10:17.151 21410 21410 F DEBUG   :       #09 pc 000000000001ce94  /data/app/org.tensorflow.lite.examples.speech-w2DgG080sdMY8xFF-l2Xbg==/lib/arm64/libtensorflowlite_gpu_jni.so
09-25 12:10:17.151 21410 21410 F DEBUG   :       #10 pc 00000000001497c0  /data/app/org.tensorflow.lite.examples.speech-w2DgG080sdMY8xFF-l2Xbg==/lib/arm64/libtensorflowlite_jni.so
09-25 12:10:17.151 21410 21410 F DEBUG   :       #11 pc 000000000014cc40  /data/app/org.tensorflow.lite.examples.speech-w2DgG080sdMY8xFF-l2Xbg==/lib/arm64/libtensorflowlite_jni.so
09-25 12:10:17.151 21410 21410 F DEBUG   :       #12 pc 000000000000f6ec  /data/app/org.tensorflow.lite.examples.speech-w2DgG080sdMY8xFF-l2Xbg==/lib/arm64/libtensorflowlite_jni.so (Java_org_tensorflow_lite_NativeInterpreterWrapper_applyDelegate+40)
09-25 12:10:17.151 21410 21410 F DEBUG   :       #13 pc 000000000013f350  /apex/com.android.runtime/lib64/libart.so (art_quick_generic_jni_trampoline+144) (BuildId: 41b9f73e55dd3e009e7d2d5c956d40fe)
09-25 12:10:17.151 21410 21410 F DEBUG   :       #14 pc 000000000013f65c  /apex/com.android.runtime/lib64/libart.so (art_quick_instrumentation_entry+252) (BuildId: 41b9f73e55dd3e009e7d2d5c956d40fe)
09-25 12:10:17.151 21410 21410 F DEBUG   :       #15 pc 00000000007f700c  [stack]
09-25 12:10:17.555   893 21417 W ActivityTaskManager:   Force finishing activity org.tensorflow.lite.examples.speech/.SpeechActivity
09-25 12:10:17.558  1300  1300 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_26
0

**Comment by amitDaMan** [comment]
Also, if it's not suppose to crash, and suppose to split the graph and continue to work as intended, that is fine.
Some debugging messages might be nice, for example, if I could set a property:
adb shell setprop debug.gpu on

And then in the logcat it would tell me which ops are not being supported on the gpu

and when the property is set to off it won't display anything.

**Comment by srjoglekar246** [comment]
@lintian06 Tian could you take a look? The model in the README works on GPU with the benchmark tool, but the app is crashing.

**Comment by amitDaMan** [comment]
bump

**Comment by amitDaMan** [comment]
@lintian06  any sort of progress/input?

**Comment by amitDaMan** [comment]
and another ping, just for good measure
