### ISSUE TITLE
checkpoint conversion to tf2.0 question

### ISSUE THREAD

**Issue by SwagJ** [tensorflow/tensorflow#38997]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
ubuntu19.10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
source
- TensorFlow version (use command below):
tf2.1.0
- Python version:
python 3.7.4
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
GCC 7.3.0
- CUDA/cuDNN version:
10.1/7.6.5
- GPU model and memory:
RTX2060S 8GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Hi, 
This is just a general question
I have a model which is written in tf1.x and the model is like this: 
https://github.com/CR-Ko/MegaDepth_Tensorflow/blob/master/hourglass_mega_tf_resize_bilinear_tflayer_prepost.py
It has checkpoint as well in tf1.x style. However, I have to rewrite it in TF2.1. For the rewrited 2.1 model, can I still use the TF1.X checkpoint? Or do I need use converter for the checkpoint?
https://github.com/tensorflow/estimator/blob/master/tensorflow_estimator/python/estimator/tools/checkpoint_converter.py
Also, about naming layers in rewrited 2.1 model, how should I do it to make sure correspondance between pretrain TF1.X checkpoint and rewrited TF2.1 model?

**Comment by allenlavoie** [comment]
There's a mention at the end of tf.train.Checkpoint.restore's docstring: https://www.tensorflow.org/api_docs/python/tf/train/Checkpoint#restore

Checkpoints that came from Saver are matched using names, so you need to make sure Variable.name matches when loading one of those. It can be tricky to do, so the recommendation is to do it once and then save with Checkpoint.save so you get object-based matching in the future.

For more see the guide: https://www.tensorflow.org/guide/checkpoint
