### ISSUE TITLE
TFLMicro mul kernel input shapes broadcasting

### ISSUE THREAD

**Issue by Abhipray** [tensorflow/tensorflow#38992]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.2 (master)
- Python version: 3.7

**Describe the current behavior**
tensorflow/lite/kernels/mul.cc kernel does not appear to be working with inputs that need broadcasting. An example pair of input shapes is (1, 1, 13) and (13,). Here is a test case that fails:

```
TF_LITE_MICRO_TEST(FloatBroadcast2) {
  float output_data[6];
  tflite::testing::TestMulFloat(
      {2, 1, 6},                      // input1 shape
      {-2.0, 0.2, 0.7, 0.8, 1.1, 2.0},      // input1 data
      {1, 6},                               // input2 shape
      {0.1,0.1,0.1,0.1,0.1,0.1},                                // input2 data
      {2, 1, 6},                      // output shape
      {-0.2, 0.02, 0.07, 0.08, 0.11, 0.2},  // expected output data
      output_data, kTfLiteActNone);
}
```

```
> make -f tensorflow/lite/micro/tools/make/Makefile test_kernel_mul_test
tensorflow/lite/micro/tools/make/Makefile:280: warning: overriding recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_grayscale'
tensorflow/lite/micro/tools/make/Makefile:280: warning: ignoring old recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_grayscale'
tensorflow/lite/micro/testing/test_linux_binary.sh tensorflow/lite/micro/tools/make/gen/osx_x86_64/bin/kernel_mul_test '~~~ALL TESTS PASSED~~~'
tensorflow/lite/micro/testing/test_linux_binary.sh: line 46: 22443 Abort trap: 6           $1 > ${MICRO_LOG_FILENAME} 2>&1
make: *** [tensorflow/lite/micro/tools/make/Makefile:340: test_kernel_mul_test] Error 134
```
**Describe the expected behavior**
The kernel is supposed to broadcast inputs if necessary. 

**Other info / logs** 
It appears that the problem is in `ProcessBroadcastShapes()`. If in `EvalFloat()` in mul.cc, I force broadcast using `TF_LITE_MUL(BroadcastMul4DSlow)`, I get correct results.

**Comment by mohantym** [comment]
Hi @Abhipray ! 
We are checking to see whether you still need help in this issue . Have you checked in latest TF versions yet(TF 2.6/2.7) yet . Thanks!
