### ISSUE TITLE
parse_example can be _much_ faster than parse_single_example

### ISSUE THREAD

**Issue by skearnes** [tensorflow/tensorflow#390]
FYI I am working with Example protos for model input, and I am learning that use `tf.parse_example` to parse a (shuffled) batch of serialized examples is _much_ faster than using `tf.parse_single_example` prior to batching. For my particular dataset, using parse_single_example allows me to create `feed_dict`s with batch size 128 at about 100/min; batching the serialized Example protos and then using parse_example is running at around 3000/min.

You may want to update the [documentation](http://www.tensorflow.org/how_tos/reading_data/index.html#file-formats) to suggest using `tf.parse_example` everywhere, as is suggested when using [sparse input data](http://www.tensorflow.org/how_tos/reading_data/index.html#sparse-input-data).

**Comment by vrv** [comment]
Want to send us a PR to fix?

**Comment by hkxIron** [comment]
I think parse_example is much faster than parse_single_example. in my case , speed change from 25000 sample/second to 32000 sample/second
