### ISSUE TITLE
Thread hang for Stage/MapStage op when setting inter_op_parallelism_threads=1

### ISSUE THREAD

**Issue by GHGmc2** [tensorflow/tensorflow#39006]
**System information**

 - OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
 - TensorFlow version (use command below): tf-nightly
 - Python version: 3.6.8

**Describe the current behavior**

Thread will hang if setting `inter_op_parallelism_threads=1`.

**Standalone code to reproduce the issue**

```python
from six.moves import queue as Queue
import threading

import tensorflow as tf
from tensorflow.python.framework import dtypes
from tensorflow.python.framework import ops
from tensorflow.python.framework.ops import disable_eager_execution
from tensorflow.python.ops import array_ops
from tensorflow.python.ops import data_flow_ops
from tensorflow.python.platform import test

disable_eager_execution()
tf.config.threading.set_inter_op_parallelism_threads(num_threads=1)  # pass if set 2


class ThreadHangTest(test.TestCase):
    """test Stage/MapStage"""

    def testStage(self):
        capacity = 3
        with ops.device(test.gpu_device_name()):
            x = array_ops.placeholder(dtypes.int32, name='x')
            stager = data_flow_ops.StagingArea([dtypes.int32, ], capacity=capacity, shapes=[[]])

        queue = Queue.Queue()
        with self.session() as sess:
            def thread_run():
                for i in range(capacity + 1):
                    sess.run(stager.put([x]), feed_dict={x: i})
                    queue.put(0)

            t = threading.Thread(target=thread_run)
            t.daemon = True
            t.start()

            try:
                for i in range(capacity + 1):
                    queue.get(timeout=1)
            except Queue.Empty:
                pass

            for i in range(capacity):
                sess.run(stager.get())

    def testMapStage(self):
        capacity = 3
        with ops.device(test.gpu_device_name()):
            x = array_ops.placeholder(dtypes.int32, name='x')
            pi = array_ops.placeholder(dtypes.int64, name='pi')
            map_stager = data_flow_ops.MapStagingArea([dtypes.int32, ], capacity=capacity, shapes=[[]])

        queue = Queue.Queue()
        with self.session() as sess:
            def thread_run():
                for i in range(capacity + 1):
                    sess.run(map_stager.put(pi, [x], [0]), feed_dict={x: i, pi: i})
                    queue.put(0)

            t = threading.Thread(target=thread_run)
            t.daemon = True
            t.start()

            try:
                for i in range(capacity + 1):
                    queue.get(timeout=1)
            except Queue.Empty:
                pass

            for i in range(capacity):
                sess.run(map_stager.get())


if __name__ == '__main__':
    test.main()

```

**Comment by ravikyram** [comment]
@GHGmc2 

I have tried in colab with TF version 2.2.0-rc3 and i am seeing the below error.(
`UnrecognizedFlagError: Unknown command line flag 'f'`).Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/b0aba773e091d8866d5e18b1739ac88b/untitled837.ipynb).Thanks!

**Comment by GHGmc2** [comment]
> @GHGmc2
> 
> I have tried in colab with TF version 2.2.0-rc3 and i am seeing the below error.(
> `UnrecognizedFlagError: Unknown command line flag 'f'`).Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/b0aba773e091d8866d5e18b1739ac88b/untitled837.ipynb).Thanks!

This may be the problem of colab, check [here](https://github.com/tensorflow/tensorflow/issues/17702#issuecomment-387335646)

**Comment by gowthamkpr** [comment]
@GHGmc2 Are you encountering the same problem with Tensorflow 2.1, 2.2rc2, 2.2rc3 ?

**Comment by GHGmc2** [comment]
> @GHGmc2 Are you encountering the same problem with Tensorflow 2.1, 2.2rc2, 2.2rc3 ?

Yes.
For some reason, we need to set inter_op_parallelism_threads=1, and found that the thread is hanging, the code snippet is from [stage_op_test.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/stage_op_test.py#L168) and [map_stage_op_test.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/map_stage_op_test.py#L186), I just make it cleaner.

**Comment by rohan100jain** [comment]
I think this is working as intended. The issue is that the StagingArea.put() operation is blocked because you're pushing in one more than capacity. That occupies a thread. 

That means that the StagingArea.get() operation, which is supposed to get an element and unblock the put() can't really proceed because it has no threads to run on.
