### ISSUE TITLE
translate.py not found in tensorflow libs on osx

### ISSUE THREAD

**Issue by astromme** [tensorflow/tensorflow#3900]
OSX 10.11.6 (15G31)
Tensorflow: 0.10.0rc0
Python 3.5

I'm following https://www.tensorflow.org/versions/r0.10/tutorials/seq2seq/index.html but translate.py is not in the tensorflow/models/rnn/translate directory.

```
cd tensorflow/models/rnn/translate
python translate.py --data_dir [your_data_directory]
```

When I ls in "/usr/local/lib/python3.5/site-packages/tensorflow/models/rnn/translate", I see the following files:
`__init__.py        __pycache__     data_utils.py       seq2seq_model.py
`
Is my installation broken somehow? I installed tensorflow with this code:

```
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.10.0rc0-py3-none-any.whl
sudo pip3 install --upgrade $TF_BINARY_URL
```

**Comment by astromme** [comment]
Actually, more files seem to be missing. Looking at https://www.tensorflow.org/versions/r0.10/tutorials/recurrent/index.html it references `models/rnn/ptb/ptb_word_lm.py` but I can't find that either. In that directory I see

`__init__.py	__pycache__	reader.py
`

**Comment by chenwangliangguo** [comment]
I have the same question.
see http://stackoverflow.com/questions/39683085/translate-py-cant-found-in-rnn-translate-folder

**Comment by MichaelBarz** [comment]
Is this related to issue #4574 (which was already closed)? Seems they excluded the example files from the pip packages, but didn't update the tutorials... I guess cloning https://github.com/tensorflow/models/tree/master/tutorials will provide all necessary tutorial files.

**Comment by drpngx** [comment]
Right, we moved the example files into models/tutorials if memory serves. Is this still current?

**Comment by drpngx** [comment]
Feel free to file again if you still have the problem. Closing this to clean up.
