### ISSUE TITLE
Custom Constraint not working

### ISSUE THREAD

**Issue by prameth** [tensorflow/tensorflow#39009]
I created a custom constraint using [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/constraints.py) which forces the sum of the elements to have sum(axis=1) to be one and be NonNeg at the same time, 
```
class SumConstraint(Constraint):
    def __init__(self, axis):
        super(SumConstraint, self).__init__()
        self.axis = axis
    def __call__(self, w):
        w = w * K.cast(K.greater_equal(w, 0.), K.floatx())
        s = K.sum(w, axis = self.axis)
        s = s.numpy()
        for i in range(6):
            w[i]/=s[i]
        return w
    def get_config(self):
        return {'axis': self.axis}
```
But when I give, ```x = Dense(3, kernel_initializer = SumConstraint(axis = 1))```

I get, **``` ValueError: Unknown constraint: SumConstraint ```**

**Comment by prameth** [comment]
Surprising to know that they work fine in TF1.

**Comment by ravikyram** [comment]
@prameth 

Please, let is know Is this still an issue?. If the issue still persists please let us know Tensorflow version you are using,operating system.Also, provide colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by prameth** [comment]
@ravikyram it’s still an issue as I didn’t closed it yet :)

I’ve shared everything I can. I used Colab, can’t share it as its private. 
But, when I use the built-in NonNeg() constraint as,

` Dense(3, kernel_initializer = NonNeg())`, it works perfectly fine.
You can help me with a simple template how to implement custom constraints in TF2 Keras.

**Comment by prameth** [comment]
> @prameth
> 
> Please, let is know Is this still an issue?. If the issue still persists please let us know Tensorflow version you are using,operating system.Also, provide colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

The issue’s in TF2.

**Comment by prameth** [comment]
@pavithrasv, can you please help me on this.

**Comment by ymodak** [comment]
I tried your example with TF 2.2-rc4 version. The example executes successfully.
Please take a look at the [gist](https://colab.research.google.com/gist/ymodak/45c89a50cf3f7bc927c8e87aa061ca7c/untitled10.ipynb). Thanks!

**Comment by prameth** [comment]
Thank you @ymodak, please edit the gist to `kernel_constraint`, instead of kernel_initialzer. 
I'm still facing an issue when I apply WeightNormalisation to the Dense Layer. The one without norm, was working previously too.
<img width="1476" alt="Screenshot 2020-05-03 at 4 24 45 PM" src="https://user-images.githubusercontent.com/38836379/80912459-a4391980-8d5a-11ea-83aa-6df1c8cdf3a4.png">


* If I use `kernel_constraint = NonNeg()`, it works perfectly fine with WeightNorm. 
* Also, custom `kernel_initializer` doesn't work when WeightNorm is applied.

**Comment by ymodak** [comment]
I tested with tf 2.2 and made the change as you mentioned.
The code works successfully. See the [gist](https://colab.research.google.com/gist/ymodak/7f9ab9f46b94d38a47004e43bfccdd04/untitled10.ipynb)
I notice you are importing tf addons module where as my example relies on tf core.

**Comment by prameth** [comment]
I saw the code you shared, it doesn't noticeably resolve 
The problem I had was with the WeightNorm applied using the CustomConstraints using the add-ons module.
It would be great if you fix that. 
<img width="1097" alt="Screenshot 2020-05-14 at 3 24 30 PM" src="https://user-images.githubusercontent.com/38836379/81920733-3c56be80-95f7-11ea-9c8e-8c8fbd117ca6.png">

**Comment by prameth** [comment]
@ymodak, I've fixed it.
For anyone, trying to figure this out, https://github.com/tensorflow/addons/issues/1839#issuecomment-629194916

**Comment by OnlyBelter** [comment]
If I use custom constraint as `kernel_constraint` when I create a model:

    model = keras.Sequential([keras.layers.Dense(y.shape[1], activation='softplus',
                                                 kernel_constraint=SumConstraint(axis=0),
                                                 # kernel_constraint=keras.constraints.MinMaxNorm(),
                                                 bias_constraint=keras.constraints.MinMaxNorm(min_value=-100,
                                                                                              max_value=100),
                                                 input_shape=[x.shape[1]])])

I always got this `ValueError: Unknown constraint: SumConstraint`.

Even if I use the same class as @ymodak showed or use the example in document https://keras.io/api/layers/constraints/.

I use TF 2.2.0
