### ISSUE TITLE
tf-nightly-cpu couldn't trace any graph with subclass models.

### ISSUE THREAD

**Issue by AlexanderJLiu** [tensorflow/tensorflow#39008]
**System information**
- Have I written custom code: Yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 10.
- TensorFlow installed from (source or binary): pip intall tf-nightly-cpu.
- TensorFlow version (use command below):  2.2.0-dev20200426.
- Python version: 3.7.7
- Tensorboard version: 2.3.0a20200412 or 2.1.1

**Describe the current behavior**

I've created a `subclass model`, and trained it with tensorboard callback. Then I start tensorboard and select `Graphs dashboard`, but it shows error messages that `Graph visualization failed` as the picture shows：

![image](https://user-images.githubusercontent.com/15494997/80565099-3d49f680-8a22-11ea-994d-ddc55ba4ee10.png)

I've checked the issue [1961](https://github.com/tensorflow/tensorboard/issues/1961) here but didn't get any help.

By the way, `Sequential Model` could trace the graph.

**Describe the expected behavior**

Things works well when I use `tensorflow 2.1.0` with both `tensorboard 2.3.0a20200412` and `2.1.1`.
So I think `tf-nightly-cpu` should work as well.

**Standalone code to reproduce the issue**

```python
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np


class ThreeLayerMLP(keras.Model):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.dense_1 = layers.Dense(64, activation='relu', name='dense_1')
        self.dense_2 = layers.Dense(64, activation='relu', name='dense_2')
        self.pred_layer = layers.Dense(10, name='predictions')

    def call(self, inputs):
        x = self.dense_1(inputs)
        x = self.dense_2(x)
        return self.pred_layer(x)


model = ThreeLayerMLP(name='3_layer_mlp')

x_train, y_train = (np.random.random(
    (60000, 784)), np.random.randint(10, size=(60000, 1)))
x_test, y_test = (np.random.random(
    (10000, 784)), np.random.randint(10, size=(10000, 1)))

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.RMSprop())

callback = tf.keras.callbacks.TensorBoard(
    'subclass_logs',
    update_freq=2,
)
history = model.fit(x_train,
                    y_train,
                    batch_size=64,
                    epochs=10,
                    callbacks=[callback])

```

**Comment by gowthamkpr** [comment]
@AlexanderJLiu This is very similar to the [issue](https://github.com/tensorflow/tensorboard/issues/1961). Please take a look at it and let me know if it helps.

**Comment by AlexanderJLiu** [comment]
@gowthamkpr I've read this issue several times. And  I've tried some solutions recommended.

![image](https://user-images.githubusercontent.com/15494997/80668383-590dd500-8ad4-11ea-8b96-a1ca9126291c.png)

I tried add `run_eagerly` to `compile`, and it didn't work.

![image](https://user-images.githubusercontent.com/15494997/80668516-abe78c80-8ad4-11ea-844a-6291f1abf4a7.png)

I've also tried customized `get_cofing` method of subclass model  or layers, and it didn't work too.

I think this issue is outdated, and couldn't get any useful infomation.

The most important things is `tf2.1` can trace subclass model's graph, why can't `tf-nightly-cpu` or the `tf2.2` coming soon?

Looking forward to your reply. Thanks~

**Comment by gowthamkpr** [comment]
@AlexanderJLiu Can you please share a colab notebook reproducing the issue with tensorflow 2.1 and tf-nightly. Thanks!

**Comment by AlexanderJLiu** [comment]
@gowthamkpr 

This [colab](https://colab.research.google.com/drive/1Uc9trzbx5ObYhUahLf2t6vWGKigsJT45) is related to tf-nightly.
And this [colab](https://colab.research.google.com/drive/1C3FwT7h1j7qnK1QNoOSOpb355RpFX44F) is related to tf-2.1.

Thanks~

**Comment by AlexanderJLiu** [comment]
It's seemed that problem still exists according to [colab here](https://colab.research.google.com/drive/12sUyrURdybadYmi-jjayB52LLhWTDcvv?usp=sharing) with tf-nightly-2.3.0-dev20200614.

Any reply will be greatly appreciated. Thanks~

**Comment by stephanwlee** [comment]
@omalleyt12 Alexander here has a Keras subclass model and of course, it returns False for `model._is_graph_network`. Can you remind us in what condition Keras constructs a graph? Does all subclass model have no graph at all?

**Comment by pavanchhatpar** [comment]
https://github.com/tensorflow/tensorflow/blob/89df3ddcd5451aefe52c7deb684f220b0520a6b1/tensorflow/python/keras/utils/layer_utils.py#L133-L135

I believe this is an indicator that all subclassed models will return is_graph_network as False

**Comment by tgaddair** [comment]
Hey @omalleyt12, any update on this?  As far as I can tell, there's no way to visualize the graph of a Keras model subclass in TF 2.2.  Is that correct?

cc @w4nderlust

**Comment by tgaddair** [comment]
@reedwm, do you know what the current state of graph tracing in TensorFlow 2.2 with Keras model subclasses is?

**Comment by reedwm** [comment]
I'm not sure. /CC @fchollet @manivaradarajan can you take a look or triage?

**Comment by tgaddair** [comment]
@manivaradarajan any thoughts on this?  Seems this is still broken in TF 2.3.

**Comment by tomerk** [comment]
Does this work in the nightlies?

**Comment by AlexanderJLiu** [comment]
@tgaddair @tomerk  It seems to be working with  tf-nightly-2.4.0-dev20200811. Please see this [colab](https://colab.research.google.com/drive/1ZR3u993vmuLAjm6vMg5OHuw0jRap3Fop?usp=sharing)

**Comment by tomerk** [comment]
Excellent! I'll go ahead and close this issue then.
