### ISSUE TITLE
TFLiteConverter doesn't support int8 quantization of PReLU

### ISSUE THREAD

**Issue by Kevinpsk** [tensorflow/tensorflow#39014]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): from binary
- TensorFlow version (or github SHA if from source): 2.1

**Problem description**
TFLiteConverter doesn't support int8 quantization of PReLU. Since the PReLU is implemented as two ReLU operations, it seems that the real blocker is the negation operation as shown in the network graph picture and TFLiteConverter runtime error. Could someone check if there would be a quick fix for this problem? Thanks a lot for your help.
Cheers

**Provide the text output from tflite_convert**

```
RuntimeError: Quantization not yet supported for op: NEG
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
import numpy as np
import tensorflow as tf
from tensorflow.keras import Model, Input
from tensorflow.keras.layers import Conv2D, PReLU, MaxPooling2D

# define dummy network
def network():
    input_shape = (600, 800, 3)
    input_tensor = Input(input_shape, name='model_input')
    x = Conv2D(10, kernel_size=(3, 3), strides=(1, 1), padding="valid")(input_tensor)
    x = PReLU(alpha_initializer='ones',shared_axes=[1, 2])(x)
    x = MaxPooling2D(pool_size=(2, 2), strides=(2, 2), padding="same")(x)
    
    x = Conv2D(16, kernel_size=(3, 3), strides=(1, 1), padding="valid")(x)
    x = PReLU(shared_axes=[1, 2], alpha_initializer='ones')(x)
    
    x = Conv2D(32, kernel_size=(3, 3), strides=(1, 1), padding="valid")(x)
    x = PReLU(shared_axes=[1, 2], alpha_initializer='ones')(x)
    
    return Model(input_tensor, x)

model = network()
dummy_input = tf.random.uniform((1,600,800,3))
dummy_output = model.predict(dummy_input)

def dataset_gen():
    for i in range(100):
        img_input = 2*np.random.rand(1,600,800,3)-1
        yield [img_input.astype(np.float32)]

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = dataset_gen
tflite_quant_model = converter.convert()

with open('dummy_model_int8.tflite', 'wb') as file:
    file.write(tflite_quant_model)
```
<img width="274" alt="prelu3" src="https://user-images.githubusercontent.com/9253234/80573217-7d47b400-89f7-11ea-9b21-de8da0ca0475.PNG">

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by IvanJuraga** [comment]
I'm also having the same problem. Do you know is there any workaround until the problem is resolved?

**Comment by jvishnuvardhan** [comment]
I could reproduce the error with `tf-nightly`. I am posting full error trace here for our reference. [Here](https://colab.research.google.com/gist/jvishnuvardhan/a540fc1de3b749564ffe643b690d7c22/untitled150.ipynb) is a gist for our reference. Thanks!

```
--------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-fb190dc2a1ef> in <module>()
     36 converter.optimizations = [tf.lite.Optimize.DEFAULT]
     37 converter.representative_dataset = dataset_gen
---> 38 tflite_quant_model = converter.convert()
     39 
     40 with open('dummy_model_int8.tflite', 'wb') as file:

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/optimize/calibrator.py in calibrate_and_quantize(self, dataset_gen, input_type, output_type, allow_float, resize_input)
     91     return self._calibrator.QuantizeModel(
     92         np.dtype(input_type.as_numpy_dtype()).num,
---> 93         np.dtype(output_type.as_numpy_dtype()).num, allow_float)
     94 
     95   def calibrate_and_quantize_single(self,

RuntimeError: Quantization not yet supported for op: PRELU
```

**Comment by akarmi** [comment]
@Kevinpsk , can you please re-test using tf-nightly, the [recent commit](https://github.com/tensorflow/tensorflow/commit/fe40ddcc5e8dd3425d55b7d44fbdba3d83ea8108) may have resolved the problem.

**Comment by jvishnuvardhan** [comment]
@Kevinpsk Agree with @akarmi . This looks like resolved in `tf-nightly`. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/b476c5f0c719cc494ca05f6058608020/untitled150.ipynb).

Can you please verify once and close the issue? Thanks!

**Comment by Kevinpsk** [comment]
Hi @akarmi and @jvishnuvardhan, thanks a lot for reminding me. Yes this bug has been fixed, and I am closing down this ticket now.
Cheers
