### ISSUE TITLE
Increase consitency of tensorShape

### ISSUE THREAD

**Issue by cmarlin** [tensorflow/tensorflow#39016]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version : 2.2.0rc3 python API
- Are you willing to contribute it : No (not enough experience of tensorflow architecture)

**Describe the feature and the current behavior/state.**
Using `where` I met an unexpecting behaviour on tensor shape testing, behaviour with tensorshape differs to tensor.

`r = tf.random.uniform([2,3,4], 0, 4, dtype=tf.int32)`
`print(tf.where(r==0, 0, 1).shape)` # (2,3,4) => ok
`print(tf.where(r.shape==3, 0, 1).shape)` **() => expecting (3,)**

**Will this change the current api? How?**
Sure, but consistency will increase. Tensorshape could be considered as a kind of tensor itself

**Who will benefit with this feature?**

1. community: code will be clearer to read, the concept is the same for tensorshape & tensor
2. optimisation ?: tensorshape could be processed by tensor graph instead of python object evaluation

**Comment by alextp** [comment]
r.shape is not a tensor, it's a python object, so when you do r.shape==3 you get a python boolean back, which in turns gets turned into a scalar by tf.where.

**Comment by alextp** [comment]
(tf.shape(r) is always a tensor, and then your code would work)

**Comment by cmarlin** [comment]
Thank you.
Here is the graph I got from the python script:

```
@tf.function
def test_where(a):
  r = tf.zeros([2,2])
  acc = tf.concat([r,a], axis=1)
  return tf.where(tf.shape(acc)==3, 0, 1)

```

![image](https://user-images.githubusercontent.com/9859675/80835381-ecd5c300-8bf2-11ea-9ce2-945692e0c8a0.png)

So the link was lost between concat and where test, but that's ok for my need
