### ISSUE TITLE
Buggy behaviour of dataset API

### ISSUE THREAD

**Issue by csxeba** [tensorflow/tensorflow#39021]
**System information**
- Have I written custom code: yes, see [https://colab.research.google.com/drive/1AeVRilpcGp8zb0hZijTIxGWdL9GkzfN_](https://colab.research.google.com/drive/1AeVRilpcGp8zb0hZijTIxGWdL9GkzfN_)
- OS Platform and Distribution: Google Colab (Ubuntu 18.04.3 LTS)
- TensorFlow installed from (source or binary): provided by Colab
- TensorFlow version (use command below): 2.2.0-rc3
- Python version: 3.6.9

**Describe the current behavior**
At Dataset graph branching points, the node, which is the root of the branching is resampled for each branch during one round of execution. With non-randomized inputs to the Dataset, this does not cause any problems. If the root node is after a .shuffle() call, the branches will receive different inputs in the same computation round. 

**Describe the expected behavior**
Downstream branches should receive the same data even if shuffle() is applied.

**Standalone code to reproduce the issue**
[https://colab.research.google.com/drive/1AeVRilpcGp8zb0hZijTIxGWdL9GkzfN_](https://colab.research.google.com/drive/1AeVRilpcGp8zb0hZijTIxGWdL9GkzfN_)

**More info**:

This behaviour is also present if the dataset is created from a generator, which handles the shuffling implicitly.

Edit: fixed the links here as well

**Comment by Saduf2019** [comment]
@csxeba 
The code shared required access permission to view it, please provide with simple standalone code to replicate issue faced.

**Comment by csxeba** [comment]
[Right link](https://colab.research.google.com/drive/1AeVRilpcGp8zb0hZijTIxGWdL9GkzfN_)

**Comment by Saduf2019** [comment]
i am able to replicate this, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/6b32a8396582948eed6285215435b7af/untitled164.ipynb)

**Comment by csxeba** [comment]
It is also affecting TF 2.0 if that matters.

**Comment by jsimsa** [comment]
@aaudiber could you please take a look? thanks

**Comment by aaudiber** [comment]
Hi @csxeba,

This is working as intended. Datasets can be much larger than the memory of a single machine, so Dataset objects act like blueprints for how to produce data (instead of trying to hold the entire dataset at once). Datasets provide a streaming API for consuming data through an iterator. If you want each iterator created on a shuffled dataset to produce elements in the same order, use the `reshuffle_each_iteration` argument to `Datasest.shuffle`:

```
index = index.shuffle(buffer_size=len(self.index), reshuffle_each_iteration=False)
```

**Comment by csxeba** [comment]
Hi Audiber, thank you for the clarification!
