### ISSUE TITLE
Micro kernel elementwise math ops issues (abs, sin, cos, log, sqrt, tanh)

### ISSUE THREAD

**Issue by pingdynasty** [tensorflow/tensorflow#39020]
@tensorflow/micro

The math ops in [elementwise.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/kernels/elementwise.cc) seem a little askew.

Firstly AbsEval, which calls `std::abs`
```
TfLiteStatus AbsEval(TfLiteContext* context, TfLiteNode* node) {
  return EvalNumeric(context, node, std::abs);
}
```
The math.h `int abs(int j)` is an integer function, what is probably intended is `fabs`, or better still `float fabsf(float x)` : return the absolute value of the floating-point number x.

The other float operations are actually referencing the double valued functions, e.g.
```
TfLiteStatus SinEval(TfLiteContext* context, TfLiteNode* node) {
  return EvalNumeric(context, node, std::sin);
}
```
would be better referencing `std::sinf`, which is the float-valued counterpart. Same for `cosf`, `logf`, and `sqrtf`.

Unfortunately changing e.g. `std::cos` to `std::cosf` will not compile on gcc, due to [an issue](https://stackoverflow.com/questions/55458487/stdexpf-and-stdlogf-not-recognized-by-gcc-7-2-0) in the `<cmath>` header. So to make it compile with gcc-based compilers the include should be changed to `#include <math.h>` and the functions referenced without `std::` prefix.

I will make a PR that also includes the TANH op.

**Comment by sushreebarsa** [comment]
@pingdynasty This is a micro related issue,Please post this in [micro repository](https://github.com/tensorflow/tflite-micro/issues)  ..Thanks!
