### ISSUE TITLE
Linker errors in individual TensorFlow Lite OpenGL delegate op tests for android_arm64

### ISSUE THREAD

**Issue by user-vm** [tensorflow/tensorflow#39025]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Mojave 10.14.06
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: OnePlus 6 (Android 10, OxygenOS 10.3.2)
- TensorFlow installed from (source or binary): using source
- TensorFlow version:  master, commit 277fa1bbd1ffa0a54b9a4fba51fb951033ce0eca
- Python version: 2.7.16
- Installed using virtualenv? pip? conda?: not installed
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): Apple clang version 11.0.0 (clang-1100.0.33.12)
- CUDA/cuDNN version: none
- GPU model and memory: AMD Radeon R9 M370X 2 GB

**Describe the problem**
I cannot seem to build any of the *_test targets in tensorflow/lite/delegates/gpu/gl/kernels for Android arm64. It results in the errors shown in the long log at the bottom of this post.
I have tried adding `linkopts = ["-ldl", "-lm"]` to the target (resize_test), which results in a successful build, but attempting to run it on a device results in this error:
`adb shell /data/local/tmp/resize_test
WARNING: linker: Warning: unable to normalize "$EXEC_ORIGIN/../../../../../../_solib_arm64-v8a/" (ignoring)
WARNING: linker: Warning: unable to normalize "$EXEC_ORIGIN/../../../../../../_solib___Caarch64-linux-android-clang7.0.2-libcpp/" (ignoring)
WARNING: linker: Warning: unable to normalize "$EXEC_ORIGIN/_solib___Caarch64-linux-android-clang7.0.2-libcpp/" (ignoring)
CANNOT LINK EXECUTABLE "/data/local/tmp/resize_test": library "libtensorflow_Slite_Sdelegates_Sgpu_Sgl_Skernels_Slibresize.so" not found`

Trying to build for android_arm (32-bit) builds successfully without the linkopts change, but it results in a similar CANNOT LINK EXECUTABLE error:

`adb shell /data/local/tmp/resize_test_
WARNING: linker: Warning: unable to normalize "$EXEC_ORIGIN/../../../../../../_solib_armeabi-v7a/" (ignoring)
WARNING: linker: Warning: unable to normalize "$EXEC_ORIGIN/../../../../../../_solib___Carm-linux-androideabi-clang7.0.2-v7a-libcpp/" (ignoring)
WARNING: linker: Warning: unable to normalize "$EXEC_ORIGIN/_solib___Carm-linux-androideabi-clang7.0.2-v7a-libcpp/" (ignoring)
CANNOT LINK EXECUTABLE "/data/local/tmp/resize_test_": library "libtensorflow_Slite_Sdelegates_Sgpu_Sgl_Skernels_Slibresize.so" not found`

I am trying to add custom gpu ops, and need to be able to run similar tests for debugging.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

`bazel build -s -c opt --config=android_arm64 tensorflow/lite/delegates/gpu/gl/kernels:resize_test`

**Any other info / logs**
`bazel build -s -c opt --config=android_arm64 tensorflow/lite/delegates/gpu/gl/kernels:resize_test
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=272
INFO: Reading rc options for 'build' from /Users/valentinmiu/2019/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /Users/valentinmiu/2019/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from /Users/valentinmiu/2019/tensorflow/.tf_configure.bazelrc:
  'build' options: --host_force_python=PY2 --action_env PYTHON_BIN_PATH=/usr/bin/python --action_env PYTHON_LIB_PATH=/Library/Python/2.7/site-packages --python_path=/usr/bin/python --config=xla --action_env ANDROID_NDK_HOME=/Users/valentinmiu/Downloads/android-ndk-r18b --action_env ANDROID_NDK_API_LEVEL=21 --action_env ANDROID_BUILD_TOOLS_VERSION=28.0.3 --action_env ANDROID_SDK_API_LEVEL=28 --action_env ANDROID_SDK_HOME=/Users/valentinmiu/library/Android/Sdk --action_env TF_CONFIGURE_IOS=1
INFO: Found applicable config definition build:v2 in file /Users/valentinmiu/2019/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /Users/valentinmiu/2019/tensorflow/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:android_arm64 in file /Users/valentinmiu/2019/tensorflow/.bazelrc: --config=android --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a
INFO: Found applicable config definition build:android in file /Users/valentinmiu/2019/tensorflow/.bazelrc: --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
INFO: Found applicable config definition build:macos in file /Users/valentinmiu/2019/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
INFO: Analyzed target //tensorflow/lite/delegates/gpu/gl/kernels:resize_test (1 packages loaded, 92 targets configured).
INFO: Found 1 target...
SUBCOMMAND: # //tensorflow/lite/delegates/gpu/gl/kernels:resize_test [action 'Linking tensorflow/lite/delegates/gpu/gl/kernels/resize_test', configuration: 44182232d54477a9f9dc3ac6d26e592e936a6eb23e121761b47c234d0221e035]
(cd /private/var/tmp/_bazel_valentinmiu/94cd6c8db58787268db4435bda1fd58c/execroot/org_tensorflow && \
  exec env - \
    ANDROID_BUILD_TOOLS_VERSION=28.0.3 \
    ANDROID_NDK_API_LEVEL=21 \
    ANDROID_NDK_HOME=/Users/valentinmiu/Downloads/android-ndk-r18b \
    ANDROID_SDK_API_LEVEL=28 \
    ANDROID_SDK_HOME=/Users/valentinmiu/library/Android/Sdk \
    PATH=/usr/local/opt/qt/bin:/usr/local/opt/qt/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Users/valentinmiu/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/valentinmiu/Library/Android/sdk/tools:/Users/valentinmiu/Library/Android/sdk/platform-tools \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python \
    PYTHON_LIB_PATH=/Library/Python/2.7/site-packages \
    TF2_BEHAVIOR=1 \
    TF_CONFIGURE_IOS=1 \
    TF_ENABLE_XLA=1 \
  external/androidndk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -o bazel-out/arm64-v8a-opt/bin/tensorflow/lite/delegates/gpu/gl/kernels/resize_test '-Wl,-rpath,$EXEC_ORIGIN/../../../../../../_solib_arm64-v8a/' '-Wl,-rpath,$EXEC_ORIGIN/../../../../../../_solib___Caarch64-linux-android-clang7.0.2-libcpp/' '-Wl,-rpath,$EXEC_ORIGIN/_solib___Caarch64-linux-android-clang7.0.2-libcpp/' -Lbazel-out/arm64-v8a-opt/bin/_solib_arm64-v8a -Lbazel-out/arm64-v8a-opt/bin/_solib___Caarch64-linux-android-clang7.0.2-libcpp bazel-out/arm64-v8a-opt/bin/tensorflow/lite/delegates/gpu/gl/kernels/_objs/resize_test/resize_test.o -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Skernels_Slibresize -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Skernels_Slibtest_Uutil -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Slibapi -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Slibcompiler -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Slibfloat16_Uconversions -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Scompiler_Slibfuse_Uauto_Uinput -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Scompiler_Slibfuse_Uinline -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Scompiler_Slibfuse_Uinplace -ltensorflow_Slite_Sdelegates_Sgpu_Scommon_Slibmodel_Utransformer -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Scompiler_Slibshader_Ucodegen -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Scompiler_Slibcompiled_Unode -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Scompiler_Slibrename -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Scompiler_Slibobject_Uaccessor -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Scompiler_Slibvariable_Uaccessor -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Scompiler_Slibpreprocessor -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Slibruntime -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Slibcommand_Uqueue -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Slibgl_Usync -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Slibgl_Uprogram -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Slibgl_Ushader -ltensorflow_Slite_Sdelegates_Sgpu_Scommon_Slibmemory_Umanagement -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Scontainer_Slibraw_Uhash_Uset -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Scontainer_Slibhashtablez_Usampler -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Sbase_Slibexponential_Ubiased -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Ssynchronization_Slibsynchronization -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Ssynchronization_Slibgraphcycles_Uinternal -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Stime_Slibtime -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Stime_Sinternal_Scctz_Slibtime_Uzone -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Stime_Sinternal_Scctz_Slibcivil_Utime -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Slibserialization -lexternal_Sflatbuffers_Ssrc_Slibflatbuffers -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Slibegl_Uenvironment -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Slibegl_Ucontext -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Slibegl_Usurface -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Slibobject_Umanager -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Slibgl_Ubuffer -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Slibgl_Utexture -ltensorflow_Slite_Sdelegates_Sgpu_Scommon_Slibconvert -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Slibrequest_Ugpu_Uinfo -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Slibgl_Uerrors -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Sworkgroups_Slibdefault_Ucalculator -ltensorflow_Slite_Sdelegates_Sgpu_Sgl_Sworkgroups_Slibcalculator -ltensorflow_Slite_Sdelegates_Sgpu_Scommon_Slibgpu_Uinfo -lexternal_Scom_Ugoogle_Ugoogletest_Slibgtest_Umain -ltensorflow_Slite_Sdelegates_Sgpu_Scommon_Sliboperations -ltensorflow_Slite_Sdelegates_Sgpu_Scommon_Slibmodel -ltensorflow_Slite_Sdelegates_Sgpu_Scommon_Slibdata_Utype -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Stypes_Slibbad_Uany_Ucast_Uimpl -ltensorflow_Slite_Sdelegates_Sgpu_Scommon_Slibshape -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Shash_Slibhash -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Shash_Slibcity -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Sstatus_Slibstatus -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Sdebugging_Slibstacktrace -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Sdebugging_Slibsymbolize -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Sdebugging_Slibdebugging_Uinternal -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Sdebugging_Slibdemangle_Uinternal -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Sbase_Slibmalloc_Uinternal -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Sstrings_Slibcord -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Sstrings_Slibstr_Uformat_Uinternal -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Sstrings_Slibstrings -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Sstrings_Slibinternal -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Sbase_Slibbase -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Sbase_Slibdynamic_Uannotations -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Sbase_Slibspinlock_Uwait -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Snumeric_Slibint128 -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Sbase_Slibthrow_Udelegate -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Stypes_Slibbad_Uoptional_Uaccess -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Stypes_Slibbad_Uvariant_Uaccess -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Sbase_Slibraw_Ulogging_Uinternal -lexternal_Scom_Ugoogle_Uabsl_Sabsl_Sbase_Sliblog_Useverity -lexternal_Scom_Ugoogle_Ugoogletest_Slibgtest -lc++_shared -lEGL -lGLESv3 -pthread -pthread -pthread -pthread -static-libgcc -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64 -target aarch64-none-linux-android -no-canonical-prefixes -Lexternal/androidndk/ndk/sources/cxx-stl/llvm-libc++/libs/arm64-v8a '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm64')
ERROR: /Users/valentinmiu/2019/tensorflow/tensorflow/lite/delegates/gpu/gl/kernels/BUILD:712:1: Linking of rule '//tensorflow/lite/delegates/gpu/gl/kernels:resize_test' failed (Exit 1)
bazel-out/arm64-v8a-opt/bin/_solib_arm64-v8a/libexternal_Scom_Ugoogle_Uabsl_Sabsl_Sstrings_Slibstrings.so: undefined reference to `nan'
bazel-out/arm64-v8a-opt/bin/_solib_arm64-v8a/libexternal_Scom_Ugoogle_Uabsl_Sabsl_Sbase_Slibexponential_Ubiased.so: undefined reference to `log2'
bazel-out/arm64-v8a-opt/bin/_solib_arm64-v8a/libexternal_Scom_Ugoogle_Uabsl_Sabsl_Sstrings_Slibstr_Uformat_Uinternal.so: undefined reference to `frexpf'
bazel-out/arm64-v8a-opt/bin/_solib_arm64-v8a/libexternal_Scom_Ugoogle_Uabsl_Sabsl_Sstrings_Slibstr_Uformat_Uinternal.so: undefined reference to `frexpl'
bazel-out/arm64-v8a-opt/bin/_solib_arm64-v8a/libexternal_Scom_Ugoogle_Uabsl_Sabsl_Stime_Slibtime.so: undefined reference to `modf'
bazel-out/arm64-v8a-opt/bin/_solib_arm64-v8a/libexternal_Scom_Ugoogle_Uabsl_Sabsl_Sstrings_Slibstr_Uformat_Uinternal.so: undefined reference to `frexp'
bazel-out/arm64-v8a-opt/bin/_solib_arm64-v8a/libexternal_Sflatbuffers_Ssrc_Slibflatbuffers.so: undefined reference to `acos'
bazel-out/arm64-v8a-opt/bin/_solib_arm64-v8a/libexternal_Sflatbuffers_Ssrc_Slibflatbuffers.so: undefined reference to `sin'
bazel-out/arm64-v8a-opt/bin/_solib_arm64-v8a/libexternal_Scom_Ugoogle_Uabsl_Sabsl_Sstrings_Slibstrings.so: undefined reference to `nanf'
bazel-out/arm64-v8a-opt/bin/_solib_arm64-v8a/libexternal_Sflatbuffers_Ssrc_Slibflatbuffers.so: undefined reference to `atan'
bazel-out/arm64-v8a-opt/bin/_solib_arm64-v8a/libexternal_Sflatbuffers_Ssrc_Slibflatbuffers.so: undefined reference to `asin'
bazel-out/arm64-v8a-opt/bin/_solib_arm64-v8a/libexternal_Sflatbuffers_Ssrc_Slibflatbuffers.so: undefined reference to `tan'
bazel-out/arm64-v8a-opt/bin/_solib_arm64-v8a/libexternal_Sflatbuffers_Ssrc_Slibflatbuffers.so: undefined reference to `cos'
bazel-out/arm64-v8a-opt/bin/_solib_arm64-v8a/libexternal_Scom_Ugoogle_Uabsl_Sabsl_Snumeric_Slibint128.so: undefined reference to `truncl'
bazel-out/arm64-v8a-opt/bin/_solib_arm64-v8a/libexternal_Scom_Ugoogle_Uabsl_Sabsl_Sstrings_Slibstr_Uformat_Uinternal.so: undefined reference to `ldexpl'
bazel-out/arm64-v8a-opt/bin/_solib_arm64-v8a/libexternal_Scom_Ugoogle_Uabsl_Sabsl_Sstrings_Slibstr_Uformat_Uinternal.so: undefined reference to `ldexpf'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //tensorflow/lite/delegates/gpu/gl/kernels:resize_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.722s, Critical Path: 0.28s
INFO: 0 processes.
FAILED: Build did NOT complete successfully`

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by user-vm** [comment]
It seems to work if I force static linking in addition to linkopts (even though the binary size jumps from 1.2 MB to >30 MB).

`cc_test(
    name = "resize_test",
    srcs = ["resize_test.cc"],
    tags = tf_gpu_tests_tags() + [
        "notap",
        "tflite_not_portable_ios",
    ],
    deps = [
        ":resize",
        ":test_util",
        "//tensorflow/lite/delegates/gpu/common:operations",
        "@com_google_googletest//:gtest",
    ],
    linkopts = [
        "-ldl",
        "-lm",
    ],
    linkstatic = 1,
)`

**Comment by impjdi** [comment]
QQ: what does bazel build -s do?

**Comment by terryheo** [comment]
It shows full build commands Bazel is using.

**Comment by terryheo** [comment]
PR was merged. Thanks!
