### ISSUE TITLE
[TFLite] Failed to create Hexagon delegate on Pixel 3

### ISSUE THREAD

**Issue by thkim-cochl** [tensorflow/tensorflow#39024]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.
#
* Device information
```
$ adb shell getprop ro.product.device
blueline
$ adb shell getprop ro.board.platform
sdm845
```
* ($APP_ROOT)/app/src/main/jniLibs
```
.
├── arm64-v8a
│   ├── libhexagon_nn_skel.so
│   ├── libhexagon_nn_skel_v65.so
│   └── libhexagon_nn_skel_v66.so
└── armeabi-v7a
    ├── libhexagon_nn_skel.so
    ├── libhexagon_nn_skel_v65.so
    └── libhexagon_nn_skel_v66.so
```

* ($APP_ROOT)/app/build.gradle
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "org.tensorflow.lite.examples.classification"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    aaptOptions {
        noCompress "tflite"
    }
    compileOptions {
        sourceCompatibility = '1.8'
        targetCompatibility = '1.8'
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
}

// Download default models; if you wish to use your own models then
// place them in the "assets" directory and comment out this line.
apply from:'download.gradle'

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'

    // Build off of nightly TensorFlow Lite
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
    implementation 'org.tensorflow:tensorflow-lite-hexagon:0.0.0-nightly'
}
```

I followed the [TensorFlow Lite Hexagon delegate](https://www.tensorflow.org/lite/performance/hexagon_delegate) guide on Pixel 3. Tensorflow Lite was failed to create Hexagon delegate.

* Log
```
W/inference: type=1400 audit(0.0:127864): avc: denied { search } for name="soc0" dev="sysfs" ino=66478 scontext=u:r:untrusted_app_27:s0:c190,c256,c512,c768 tcontext=u:object_r:sysfs_soc:s0 tclass=dir permissive=0
D/org.tensorflow.lite.examples.classification: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1615: Error: Device node open failed for domain 3 (errno Permission denied)
D/org.tensorflow.lite.examples.classification: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1916: Error 0x57: apps_dev_init failed for domain 3, errno Permission denied
D/org.tensorflow.lite.examples.classification: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:2009: Error 0x57: open_dev (-1) failed for domain 3
D/org.tensorflow.lite.examples.classification: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1179: Error 0x3b: remote_handle_control_domain failed for request ID 1 on domain 3
D/org.tensorflow.lite.examples.classification: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1190: Error 0x3b: remote_handle_control failed for request ID 1
W/tflite: Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.
I/tflite: Hexagon Delegate is not supported.
W/System.err: java.lang.UnsupportedOperationException: This Device doesn't support Hexagon DSP execution.
W/System.err:     at org.tensorflow.lite.experimental.HexagonDelegate.<init>(HexagonDelegate.java:40)
W/System.err:     at org.tensorflow.lite.examples.classification.tflite.Classifier.<init>(Classifier.java:182)
W/System.err:     at org.tensorflow.lite.examples.classification.tflite.ClassifierQuantizedMobileNet.<init>(ClassifierQuantizedMobileNet.java:37)
W/System.err:     at org.tensorflow.lite.examples.classification.tflite.Classifier.create(Classifier.java:97)
W/System.err:     at org.tensorflow.lite.examples.classification.ClassifierActivity.recreateClassifier(ClassifierActivity.java:167)
W/System.err:     at org.tensorflow.lite.examples.classification.ClassifierActivity.lambda$onInferenceConfigurationChanged$0(ClassifierActivity.java:146)
W/System.err:     at org.tensorflow.lite.examples.classification.-$$Lambda$ClassifierActivity$83lGy2TUjuj0M5n4BhMB9qlLgSY.run(Unknown Source:8)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:883)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err:     at android.os.Looper.loop(Looper.java:214)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by karimnosseir** [comment]
Hi,
Is this Pixel rooted ? If not, then you can't use the delegate on this phone.
The delegate won't work on non-rooted Pixel phones.
You can try any other phone (not pixel) with QC chip.

Thanks

**Comment by holokai-ai** [comment]
@karimnosseir I remember seeing the TFLite team mentioning that the Hexagon Delegate won't work on Pixel phones a few months ago, but no mention of why simply copying the libhexagon*.so libraries to /data/local/tmp won't work.

Is it matter of running the libraries in escalated privilege under /system/lib64 or /vendor/lib64, which will require rooting and modifying those read-only partitions?  Or something to do with DSP library / driver signatures?

I'm curious how one needs to mod a rooted Pixel 1 phone to get the Hexagon Delegate working.    That would make a handy compact testing device instead of an EVM dev board.

I don't think the Hexagon Delegate worked on an unrooted Samsung Galaxy Tab S6 (with a QCOM SD855 SOC) either, at least when I tried a several months ago (using NNAPI didn't seem to make things run on DSP either).

Thanks

**Comment by karimnosseir** [comment]
@holokai-ai 

Pixel phones have SELinux policy that disables the DSP access directly, the only way is through HAL (NNAPI).
If you have a rooted Pixel phones, you can disable SELinux policy "abd shell setenforce 0" and then it will work same as other phones.

It should work on other production phones fine. I don't have Samsung Galaxy tab S6, but it should work. I don't have one to try it, but i used multiple Samsung phones for testing and was working fine on all the phones i've tried..
If you can get more details about the failure i can check what is wrong.

Thanks

**Comment by holokai-ai** [comment]
@karimnosseir 

Ahh ...  SELinux was the missing ingredient!   Will give it a try.

Will also retry on the Tab S6 without rooting when I get a chance.  Don't want to root that tablet because it's my primary Netflix viewing platform.  :-)   :-)   Netflix won't play on rooted devices last time I checked ...

Thanks!

**Comment by thkim-cochl** [comment]
> @holokai-ai
> 
> Pixel phones have SELinux policy that disables the DSP access directly, the only way is through HAL (NNAPI).
> If you have a rooted Pixel phones, you can disable SELinux policy "abd shell setenforce 0" and then it will work same as other phones.
> 
> It should work on other production phones fine. I don't have Samsung Galaxy tab S6, but it should work. I don't have one to try it, but i used multiple Samsung phones for testing and was working fine on all the phones i've tried..
> If you can get more details about the failure i can check what is wrong.
> 
> Thanks

@karimnosseir, thank you for the guide. Hexagon delegate is working with `abd shell setenforce 0` SELinux policy.

```
I/inference: type=1400 audit(0.0:2179): avc: denied { search } for name="soc0" dev="sysfs" ino=66478 scontext=u:r:untrusted_app_27:s0:c106,c256,c512,c768 tcontext=u:object_r:sysfs_soc:s0 tclass=dir permissive=1 app=org.tensorflow.lite.examples.classification
vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1744: Successfully opened fastrpc_shell_3
I/inference: type=1400 audit(0.0:2185): avc: denied { read } for name="fastrpc_shell_3" dev="dm-4" ino=399 scontext=u:r:untrusted_app_27:s0:c106,c256,c512,c768 tcontext=u:object_r:adsprpcd_file:s0 tclass=file permissive=1 app=org.tensorflow.lite.examples.classification
vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1890: Successfully created user PD on domain 3 (attrs 0x0)
vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:278: FastRPC latency thread started for QoS
vendor/qcom/proprietary/commonsys-intf/adsprpc/src/apps_std_imp.c:749: Warning: fopen returned 0x2 for file testsig-0x5fee24bd.so. (No such file or directory)
vendor/qcom/proprietary/commonsys-intf/adsprpc/src/apps_std_imp.c:749: Warning: fopen returned 0x2 for file testsig.so. (No such file or directory)
vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1028: remote_handle64_open: Successfully opened handle 0x25c6a190 for file:///libhexagon_nn_skel_v65.so?hexagon_nn_domains_skel_handle_invoke&_modver=1.0&_dom=cdsp on domain 3
I/tflite: Created TensorFlow Lite delegate for Hexagon.
I/tflite: Hexagon delegate: 31 nodes delegated out of 31 nodes with 1 partitions.
```

* What I did
  * Rooted Pixel 3 (AOSP)
  * `adb root` and `adb shell setenforce 0`
