### ISSUE TITLE
Training Property on Keras Layers

### ISSUE THREAD

**Issue by gdj0nes** [tensorflow/tensorflow#39036]
**System information**
- TensorFlow version (you are using): 2.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Keras Layers support a `training` argument. Since `training` is only available as an argument it cannot be varied for sublayers without constructing a new class.

Consider a model with two subnetworks, backbone and head. The encapsulating model exposes an inputs and training arg, consistent with the Keras API. Without constructing a different model it becomes impossible to change the value of `training` passed to subnetworks. 

```
class Model(Layer):

    def __init__(self, backbone, head, **kwargs):
        super().__init__(**kwargs)
        self.backbone: Layer = backbone
        self.head: Layer = head

    def call(self, inputs, training=True, **kwargs):
        features = self.backbone(inputs, training=training)
        outputs = self.head(features, training=training)
        return outputs
    
    
# -- Training
model = Model(...)
x, y = dataset()
model(x, training=True)

# -- Inference
model(x, training=False)

# -- Transfer learning (Proposed)

model.backbone.trainable = False  # freeze backbone weights and batch norm
model.backbone.training = False # used later in fine tuning
# the head trains with trainable weights and active batchnorm
model(x, training=True)

# unfreeze backbone for fine tuning while keeping batchnorm frozen
model.backbone.trainable = True
model(x, training=True)

```

**Will this change the current api? How?**

It will alter the precedence for handling the `training` argument [here](https://github.com/tensorflow/tensorflow/blob/1e2c8c6873770a70ace0613a65c11826666c4623/tensorflow/python/keras/engine/base_layer.py#L843-L873). 

A possible implementation could look something like this:

A new property:
```
@property
def training(self):
    return self.__training


@training.setter
def training(self, value: bool):
    if value is not None:
        if tensor_util.is_tensor(value):
            training_value = math_ops.cast(value, dtypes.bool)
        else:
            training_value = bool(value)
        self.__training = training_value
        self._training_arg_passed_by_property = True

    else:
        training_value = None
        self._training_arg_passed_by_property = False
    self.__training = training_value
```

Inside `__call__`:
```
# Priority 1
if self._training_arg_passed_by_property:
    training_value = self.training
    if self._expects_training_arg:
        kwargs["training"] = training_value
else:
    # Priority 2: `training` was explicitly passed.
    if self._call_arg_was_passed("training", args, kwargs):
        training_value = self._get_call_arg_value("training", args, kwargs)
        if not self._expects_training_arg:
            kwargs.pop("training")
```

**Who will benefit with this feature?**

Tensorflow users who have develop models using OO patterns that require setting of the `training` parameter for sublayers.

**Comment by gdj0nes** [comment]
This feature request was prompted by this [colab](https://colab.research.google.com/drive/17vHSAj7no7RMdJ18MJomTf8twqw1suYC#scrollTo=IMBpAwbegtdP) on transfer learning by @fchollet

**Comment by bhack** [comment]
@gdj0nes Are you still interested? Can you try to open that PR?

**Comment by gdj0nes** [comment]
@bhack I would be interested. I haven't taken a look at the latest changes to Keras but I will see if what I currently have is compatible.

**Comment by gdj0nes** [comment]
@bhack I've opened an RFC and have a pr to submit if it passes

**Comment by jvishnuvardhan** [comment]
@gdj0nes Sorry for the late response. Are you still interested in contributing? If yes, please feel free to open a PR in  [keras-team/keras repo.](https://github.com/keras-team/keras/issues) repository.

Please note that Keras development moved to keras-team/keras repository to focus on only keras. Thanks!
