### ISSUE TITLE
TF Lite Hexagon delegate support for snapdragon 865

### ISSUE THREAD

**Issue by gpapan** [tensorflow/tensorflow#39035]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

The Snapdragon 865 (Hexagon 698 DSP) is not included in the list of supported Qualcomm SoCs:
https://www.tensorflow.org/lite/performance/hexagon_delegate

Was wondering if you have plans to add support for it to the tflite Hexagon delegate.

**Comment by karimnosseir** [comment]
The guide page has only sample of the devices listed, not all.
Did you try running it on SD 865 and didn't work ?

**Comment by gpapan** [comment]
@karimnosseir I got access to a phone equipped with the SD 865 and confirm that the delegate works after the recent update of `hexagon_nn_skel` to v. 1.17. Thank you!

**Comment by St190706025** [comment]
> @karimnosseir I got access to a phone equipped with the SD 865 and confirm that the delegate works after the recent update of `hexagon_nn_skel` to v. 1.17. Thank you!

What did you use version of tensorflow?
