### ISSUE TITLE
TPU training error

### ISSUE THREAD

**Issue by acmilannesta** [tensorflow/tensorflow#39030]
Tensorflow: 2.2.0-rc3
Python: 3.6.9

I am training on colab TPU. But got the following error:
```
NotFoundError: {{function_node __inference_train_function_128421}} No registered 'PyFunc' OpKernel for 'CPU' devices compatible with node {{node PyFunc}}
	.  Registered:  <no registered kernels>

	 [[PyFunc]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional]]
```

Then I tried to use tfrecord from generator. But got another error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-a14d46c75435> in <module>()
      3 serialized_features_dataset = tf.data.Dataset.from_generator(train_D.__iter__, output_types=(tf.int32, tf.int32, tf.int32, tf.int32))
      4 with tf.io.TFRecordWriter(filename) as writer:
----> 5     writer.write(serialized_features_dataset)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/tf_record.py in write(self, record)
    311       record: str
    312     """
--> 313     super(TFRecordWriter, self).write(record)
    314 
    315   def flush(self):

TypeError: write(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorflow.python._pywrap_record_io.RecordWriter, record: str) -> None

Invoked with: <tensorflow.python.lib.io.tf_record.TFRecordWriter object at 0x7f299d088b48>, <FlatMapDataset shapes: (<unknown>, <unknown>, <unknown>, <unknown>), types: (tf.int32, tf.int32, tf.int32, tf.int32)>
```

To help replicate my issue, this is my notebook
https://colab.research.google.com/drive/1tQbhe_gGhIFoMuHu-HqazHzlP0Z83kwj

And this is the dataset to run the codes:
https://drive.google.com/drive/folders/1abgTg2uuWBmo2TTvipqiXVhxkBuLmNwb?usp=sharing

**Comment by ravikyram** [comment]
I have tried in colab with TF 2.1.0, 2.2-rc3 and was able to reproduce the issue. Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/b06a5b1bd52117b174351203706e9caf/untitled842.ipynb)Thanks!

**Comment by gowthamkpr** [comment]
@acmilannesta You cannot run `PyFunc` on `TPU worker` as there is no python interpreter on TPU machines.
You can refer to the following [comment](https://github.com/tensorflow/tensorflow/issues/24099#issuecomment-468030849) for more information.

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 2 weeks. Please add additional comments for us to open this issue again. Thanks!
