### ISSUE TITLE
For the same model Keras trains about 4x slower compared to Estimators.

### ISSUE THREAD

**Issue by yzhuang** [tensorflow/tensorflow#39039]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux (Colab)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.15 through 2.2-rc3
- Python version: 3.6

**Describe the current behavior**
For a simple model (3 layer neural net), Estimator trains about 4x faster compared to Keras. 
Something slows keras `model.fit()` down significantly.

**Describe the expected behavior**
Expecting Keras and Estimator performance to be roughly on par. 

**Standalone code to reproduce the issue**
https://colab.research.google.com/gist/yzhuang/35f037713f4181070f52b7502846f862/estimator_keras_speed_comparison.ipynb

(Reproduction script are written by @pavanky )

**Comment by ravikyram** [comment]
@yzhuang 

I have tried in colab with TF 2.2-rc3 and was able to reproduce the issue. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/90355a3669004d6d92a0007c67666138/untitled841.ipynb).Thanks!

**Comment by romanovzky** [comment]
I can also reproduce this. It only happens when I use validation data or validation split. Training works as expected if no validation step happens.

**Comment by yzhuang** [comment]
I did some more testing, and this discrepancy seems to affect CPU only but not GPU training. 

With the model and data I supplied in the colab, i am seeing the following performance:

**On CPU: (TF 1.15 and TF 2.2 has similar performance on CPU)**
- Estimator: about 400 steps / second
- Keras: about 90-100 steps / second
Summary: on CPU, with both 1.15 and 2.2, Estimator trains about 4x faster.

**On GPU with TF 2.2 (eager mode):**
- Estimator: about 280 - 320 steps / second
- Keras: about 270-280 steps / second
Summary: on GPU with TF 2.2., Estimator and Keras performances are close.  Surprisingly, Keras got a 3x speed boost from the GPU, while Estimator became 25% slower on GPU.

**On GPU with TF 1.15 (graph mode):**
Estimator: about 200 steps / second
Keras: about 200 steps / second
Summary: on GPU with TF 1.15, Estimator and Keras performed similar.  Estimator is only half as fast on GPU compared to on CPU.

**Comment by zthzthzzz** [comment]
Did some further testing and seems the overhead (time per step) in keras does not grow with the total training time, thus can be amortized with more complex models.

I change the model in 
> https://colab.research.google.com/gist/yzhuang/35f037713f4181070f52b7502846f862/estimator_keras_speed_comparison.ipynb

to have 4 hidden layers (excluding input and output layers) and each layer contains 512 nodes.
On CPU, TF 2.2:
Estimator: 34 steps/second = 29 ms/step 
Keras: 36 ms/step

Converting the numbers from the original model to time per step
> On CPU: (TF 1.15 and TF 2.2 has similar performance on CPU)
> 
> Estimator: about 400 steps / second
> Keras: about 90-100 steps / second

We get
Estimator: 2.5 ms/step 
Keras: 10 ms/step

Seems there are constant overhead per step on keras training.
