### ISSUE TITLE
Convert Mobilenet SSD to TensorFlowLite with quantization

### ISSUE THREAD

**Issue by jackyvr** [tensorflow/tensorflow#39037]
**System information**
- Didn't change the code but used my own data:
- Windows 10 + conda
- TensorFlow installed from binary
- TensorFlow version: v2.0.1 (also happened in newer version)
- Python version: 3.7.6
- CUDA/cuDNN version: 10.0
- GPU model and memory: GeForce GTX 1080 Ti

My goal is simple, I think. I want to convert a pre-trained mobilenetv2 (or v1) ssd model to TFLite with quantization and optimization as described [HERE](https://www.tensorflow.org/lite/convert/quantization). But even without any quantization, I am getting errors converting the model to TFLite model. 

```
    model = tf.saved_model.load(detection_model_dir)
    concrete_func = model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
    concrete_func.inputs[0].set_shape([1,300,300,3])
    converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
    #converter = tf.compat.v1.lite.TFLiteConverter.from_saved_model(detection_model_dir, input_shapes={"image_tensor" : [1,300,300,3]})
    tflite_model = converter.convert() 
```

Error Messages:

> 2020-04-29 13:23:58.432192: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2020-04-29 13:23:58.432342: I tensorflow/lite/toco/import_tensorflow.cc:659] Converting unsupported operation: TensorArrayWriteV3
2020-04-29 13:23:58.782402: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 4058 operators, 6882 arrays (0 quantized)
2020-04-29 13:23:59.302999: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 4005 operators, 6778 arrays (0 quantized)
2020-04-29 13:23:59.925648: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 4005 operators, 6778 arrays (0 quantized)
2020-04-29 13:24:00.227644: F .\tensorflow/lite/toco/toco_tooling.h:38] Check failed: s.ok() Found StridedSlice as non-selected output from Switch, but only Merge supported. Control flow ops like Switch and Merge are not generally supported. We are working on fixing this, please see the Github issue at https://github.com/tensorflow/tensorflow/issues/28485.
Fatal Python error: Aborted

I have spent days on converting a pretrained mobilenetv2 ssd model to TFLite. I know the command line (export_tflite_ssd_graph.py) solution works for the conversion but not the qualization part. I also would like to write python code to do the same thing and optimize (compress, quantize) the model. I have been failing in doing it. Any suggestions? 

My questions can be summarized as below:

1. How to convert a pre-trained mobilenetv2 (or v1) ssd model to TFLite with quantization and optimization using python code similar to the above code block. 
2. How to convert a pre-trained mobilenetv2 (or v1) ssd model to TFLite with quantization and optimization with command lines (object detection API and TFLite APIs if any)

**Comment by Saduf2019** [comment]
@jackyvr 
Please provide simple stand alone code for us to replicate the issue, the code shared seems incomplete.

**Comment by jackyvr** [comment]
> @jackyvr
> Please provide simple stand alone code for us to replicate the issue, the code shared seems incomplete.

The other part of the code is mostly from the object detection tutorial. 

import pathlib
import numpy as np
import os
import six.moves.urllib as urllib
import sys
import tarfile
import tensorflow as tf
import zipfile

from collections import defaultdict
from io import StringIO
from matplotlib import pyplot as plt
from PIL import Image
from IPython.display import display
from object_detection.utils import ops as utils_ops
from object_detection.utils import label_map_util
from object_detection.utils import visualization_utils as vis_util

utils_ops = tf.compat.v1
tf.gfile = tf.io.gfile

def load_model(model_name):
    base_url = 'http://download.tensorflow.org/models/object_detection/'
    model_file = model_name + '.tar.gz'
    model_dir = tf.keras.utils.get_file(
        fname=model_name,
        origin=base_url + model_file,
        untar=True)
    
    model_dir = pathlib.Path(model_dir)/"saved_model"
    
    model = tf.saved_model.load(str(model_dir))
    model = model.signatures['serving_default']
    
    return model, str(model_dir)

model_name = 'ssd_mobilenet_v1_coco_2017_11_17'
detection_model, detection_model_dir = load_model(model_name)

model = tf.saved_model.load(detection_model_dir)
concrete_func = model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
concrete_func.inputs[0].set_shape([1,300,300,3])
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
tflite_model = converter.convert()

**Comment by Saduf2019** [comment]
@jackyvr 
I ran the code shared above but face a different error, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/7dd6e3f97350ead1d9e277e48057e5ff/39037.ipynb)

**Comment by Saduf2019** [comment]
@jackyvr
Please update as per above comment
