### ISSUE TITLE
Docstring is not misleading.

### ISSUE THREAD

**Issue by andreiionutdamian** [tensorflow/tensorflow#39047]
The docstring says " it is a negative quantity between -1 and 0, where 0 indicates orthogonality and values closer to -1 indicate greater similarity". Although it is true that the function reverses the sign of the classic cosine similarity so that -1 will denote "similarity" instead of 1 in the original formula, the actual range is still -1 to 1 (not -1 to 0 as misleading by the docstring). 

https://github.com/tensorflow/tensorflow/blob/e5bf8de410005de06a7ff5393fafdf832ef1d4ad/tensorflow/python/keras/losses.py#L1073

**Comment by KrishnaRekapalli** [comment]
@MarkDaoust Are you working on this issue? If not I can pick this. Thanks!

**Comment by MarkDaoust** [comment]
This is fixed on master.
