### ISSUE TITLE
tensorflowrun for distributed training (MultiWorkerMirroredStrategy & ParameterServerStrategy)

### ISSUE THREAD

**Issue by sboshin** [tensorflow/tensorflow#39041]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.2
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
There currently is no unified way to run multiworkermirroredstrategy. From the tutorials we are expected to start each script on each instance manually. On GCP tutorials it comes with a premade run script. 

Horovod has horovodrun which like mpirun. For tensorflow, why don't create a tensorflowrun. 

Basic features of the horovodrun. 
tensorflowrun --n 2 --np 2 --clusterSpec cspec python tensorflow_script.py
Run on 2 workers, two processes locally
The clusterspec passed to tensorflowrun can have assumptions or explicitly setup. 
task ids will be defined by index in cluster

Example:
{"cluster": {"worker": ["192.168.1.1:5555", "192.168.1.2:5555"]}}
task id 0 assigned to *.1
task id 1 assigned to *.2

{'cluster': {'chief': ['10.0.0.4:2224'], 'worker': ['10.0.0.4:2223', '10.0.0.5:2222', '10.0.0.6:2222'], 'ps': ['10.0.0.4:2222']}, 'environment': 'cloud'}

worker
task id 0 *4
task id 1 *5
task id 2 *6

ps 
task id 0 *4

**Will this change the current api? How?**
No APIs will change

**Who will benefit with this feature?**
Anyone trying to run MultiWorkerMirrorredStrategy, Parameter Server can also be included.

**Any Other info.**

**Comment by sboshin** [comment]
Currently have something for Multi-worker mirrored strategy
tensorflowrun.py —cluster_spec ‘{"cluster": {"worker": ["w1:5555", "w2:5555"]}}’ python /absolute/path/script.py

Assumptions: You have ssh access without key to workers. The run script is in the same location in all workers.

**Comment by yuefengz** [comment]
It is a simple utility which I guess users can create by themselves.

**Comment by sboshin** [comment]
It is relatively simple, but could be a pain point for users trying out the different distribution strategies.
All tutorials mention starting a process on each node with the correct TF_CONFIG env. This simple utility could be expanded to solve many other pain points. 
I believe most other frameworks have something similar built into the framework that alleviates this problem.

**Comment by jvishnuvardhan** [comment]
@sboshin Is this still a feature request you are interested to work on? 

If there is any actionable PRs, please feel free to open them to contribute. Thanks!
