### ISSUE TITLE
Tensorflow GPU installation 

### ISSUE THREAD

**Issue by emiliocoutinho** [tensorflow/tensorflow#39044]
## URL(s) with the issue:

https://www.tensorflow.org/install/gpu

## Description of issue (what needs changing):

The tf-nightly pip package does not support GPU. It should be: tf-nightly-gpu

On the Windows Setup section, the path:

SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\extras\CUPTI\libx64;%PATH%

should be:

SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\extras\CUPTI\lib64;%PATH% 

Since the CUDA toolkit generates this path with lib64 and not libx64.

**Comment by ymodak** [comment]
Thanks for the issue. This is fixed now.
