### ISSUE TITLE
AttributeError: module 'tensorflow.python.data.experimental.ops.optimization' has no attribute 'AUTOTUNE'

### ISSUE THREAD

**Issue by LINYOUWEI0804** [tensorflow/tensorflow#39049]
system:ubuntu18.04
tf:2.0.0b0
python:3.6.9

I want to train a model for object recognition，Then I run [python3 train.py --logtostderr --train_dir=training/ --pipeline_config_path=ssd_mobilenet_v2_quantized_300x300_coco.config]

Get this error：AttributeError: module 'tensorflow.python.data.experimental.ops.optimization' has no attribute 'AUTOTUNE'

**Comment by Saduf2019** [comment]
@LINYOUWEI0804
Please share simple standalone code to replicate the issue faced.

**Comment by LINYOUWEI0804** [comment]
this my pipeline_config_path: [ssd_mobilenet_v2_quantized_300x300_coco.config.txt](https://github.com/tensorflow/tensorflow/files/4557323/ssd_mobilenet_v2_quantized_300x300_coco.config.txt)

tensorflow version:2.0.0b0

**Comment by LINYOUWEI0804** [comment]
I follow this instruction：「https://chtseng.wordpress.com/2019/02/16/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8google-object-detection-api%E8%A8%93%E7%B7%B4%E8%87%AA%E5%B7%B1%E7%9A%84%E6%A8%A1%E5%9E%8B/」

**Comment by Saduf2019** [comment]
@LINYOUWEI0804
I ran the code shared and it says invalid syntax, please share indented complete stand alone code or if possible share colab gist with the error for us to analyse.
