### ISSUE TITLE
tensorflow 2.0 does not detect the gpus 

### ISSUE THREAD

**Issue by SlowMonk** [tensorflow/tensorflow#39045]
actually I have 2 gpus but 

```
> gpus = tf.config.experimental.list_physical_devices('GPU')
> [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
> 
```

but this only detect the first gpu

**Comment by oke-aditya** [comment]
Is CudNN and CUDA both installed on the GPUs?
Is the version as per tensorflow requirements ?
I see that first GPU is detected.

> 
> 
> actually I have 2 gpus but
> 
> ```
> > gpus = tf.config.experimental.list_physical_devices('GPU')
> > [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
> > 
> ```
> 
> but this only detect the first gpu

**Comment by Saduf2019** [comment]
@SlowMonk 
Please update as per above comments
