### ISSUE TITLE
GPU Kernel for SparseFillEmptyRows OP

### ISSUE THREAD

**Issue by firejq** [tensorflow/tensorflow#39051]
**System information**
- TensorFlow version : 1.13.1
- Are you willing to contribute it ：Yes

I found that `SparseFillEmptyRowsOP` does not have GPU kernel support. Can someone explain the following reasons for that to me?

In my training, SparseFillEmptyRows executed on the CPU consumes a lot of time cost. Therefore, if you can move SparseFillEmptyRows OP to the GPU, I think there will be a considerable performance improvement.

**Comment by ravikyram** [comment]
@firejq 

Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!

**Comment by penpornk** [comment]
Closing this since the [GPU kernel](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/sparse_fill_empty_rows_op_gpu.cu.cc) has been added in https://github.com/tensorflow/tensorflow/pull/46172. (Thank you very much, @benbarsdell!)
