### ISSUE TITLE
Failure to convert model to tflite on local laptop

### ISSUE THREAD

**Issue by harsha113** [tensorflow/tensorflow#39053]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): tf-nightly

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
# Copy and paste here the exact command
```
converter = tf.lite.TFLiteConverter.from_keras_model(model)converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)

**The output from the converter invocation**
ConverterError                            Traceback (most recent call last)
<ipython-input-7-d6af5d9fe17b> in <module>
     14 converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
     15 converter.optimizations = [tf.lite.Optimize.DEFAULT]
---> 16 tflite_model = converter.convert()
     17 open("converted_model.tflite", "wb").write(tflite_model)
     18 e:\projecttools\venv_tf2.2\lib\site-packages\tensorflow\lite\python\lite.py in convert(self)
    709         input_tensors=input_tensors,
    710         output_tensors=output_tensors,
--> 711         **converter_kwargs)
    712 
    713     if quant_mode.post_training_int8_no_float():e:\projecttools\venv_tf2.2\lib\site-packages\tensorflow\lite\python\convert.py in toco_convert_impl(input_data, input_tensors, output_tensors, enable_mlir_converter, *args, **kwargs)
    546       input_data.SerializeToString(),
    547       debug_info_str=debug_info_str,
--> 548       enable_mlir_converter=enable_mlir_converter)
    549   return data
    550 e:\projecttools\venv_tf2.2\lib\site-packages\tensorflow\lite\python\convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    251       stdout = _try_convert_to_unicode(stdout)
    252       stderr = _try_convert_to_unicode(stderr)
--> 253       raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
    254   finally:
    255     # Must manually cleanup files.ConverterError: See console for info.
2020-04-30 17:01:13.684285: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:307] Ignored output_format.
2020-04-30 17:01:13.684836: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:310] Ignored drop_control_dependency.
2020-04-30 17:01:13.802287: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-04-30 17:01:13.813650: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x27f74d24df0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-30 17:01:13.814159: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
loc(callsite("model/time_distributed_1/lstm/while"("e:\projecttools\venv_tf2.2\lib\site-packages\tensorflow\python\eager\def_function.py":988:0) at callsite("e:\projecttools\venv_tf2.2\lib\site-packages\tensorflow\python\eager\def_function.py":1082:0 at callsite("e:\projecttools\venv_tf2.2\lib\site-packages\tensorflow\lite\python\lite.py":578:0 at callsite("<ipython-input-7-d6af5d9fe17b>":12:0 at callsite("e:\projecttools\venv_tf2.2\lib\site-packages\IPython\core\interactiveshell.py":3331:0 at callsite("e:\projecttools\venv_tf2.2\lib\site-packages\IPython\core\interactiveshell.py":3254:0 at callsite("e:\projecttools\venv_tf2.2\lib\site-packages\IPython\core\interactiveshell.py":3063:0 at callsite("e:\projecttools\venv_tf2.2\lib\site-packages\IPython\core\async_helpers.py":68:0 at callsite("e:\projecttools\venv_tf2.2\lib\site-packages\IPython\core\interactiveshell.py":2886:0 at "e:\projecttools\venv_tf2.2\lib\site-packages\IPython\core\interactiveshell.py":2858:0)))))))))): error: body function result type tensor<?x75x20xf32> is incompatible with result type tensor<15x1x20xf32> at index 3
Traceback (most recent call last):
  File "E:\ProjectTools\Python3.6.8\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\ProjectTools\Python3.6.8\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\ProjectTools\venv_tf2.2\Scripts\toco_from_protos.exe\__main__.py", line 9, in <module>
  File "e:\projecttools\venv_tf2.2\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "e:\projecttools\venv_tf2.2\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "e:\projecttools\venv_tf2.2\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "e:\projecttools\venv_tf2.2\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "e:\projecttools\venv_tf2.2\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 56, in execute
    enable_mlir_converter)
Exception: e:\projecttools\venv_tf2.2\lib\site-packages\tensorflow\python\eager\def_function.py:988:1: error: body function result type tensor<?x75x20xf32> is incompatible with result type tensor<15x1x20xf32> at index 3
        self._initialize(args, kwargs, add_initializers_to=initializers)
^
e:\projecttools\venv_tf2.2\lib\site-packages\tensorflow\python\eager\def_function.py:1082:1: note: called from
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
^
e:\projecttools\venv_tf2.2\lib\site-packages\tensorflow\lite\python\lite.py:578:1: note: called from
    concrete_func = func.get_concrete_function()
^
<ipython-input-7-d6af5d9fe17b>:12:0: note: called from
e:\projecttools\venv_tf2.2\lib\site-packages\IPython\core\interactiveshell.py:3331:1: note: called from
                    exec(code_obj, self.user_global_ns, self.user_ns)
^
e:\projecttools\venv_tf2.2\lib\site-packages\IPython\core\interactiveshell.py:3254:1: note: called from
                    if (await self.run_code(code, result,  async_=asy)):
^
e:\projecttools\venv_tf2.2\lib\site-packages\IPython\core\interactiveshell.py:3063:1: note: called from
                       interactivity=interactivity, compiler=compiler, result=result)
^
e:\projecttools\venv_tf2.2\lib\site-packages\IPython\core\async_helpers.py:68:1: note: called from
        coro.send(None)
^
e:\projecttools\venv_tf2.2\lib\site-packages\IPython\core\interactiveshell.py:2886:1: note: called from
            return runner(coro)
^
e:\projecttools\venv_tf2.2\lib\site-packages\IPython\core\interactiveshell.py:2858:1: note: called from
                raw_cell, store_history, silent, shell_futures)
^
e:\projecttools\venv_tf2.2\lib\site-packages\tensorflow\python\eager\def_function.py:988:1: note: see current operation: %146:13 = "tf.While"(%16, %7, %16, %3, %145, %50, %50, %49, %117, %127, %42, %43, %41) {_lower_using_switch_merge = false, _num_original_outputs = 13 : i64, _read_only_resource_inputs = [10, 11, 12], body = @model_time_distributed_1_lstm_while_body_5735_frozen0, cond = @model_time_distributed_1_lstm_while_cond_5734_frozen0, device = "", is_stateless = false, output_shapes = [#tf.shape<>, #tf.shape<>, #tf.shape<>, #tf.shape<>, #tf.shape<?x20>, #tf.shape<?x20>, #tf.shape<?x20>, #tf.shape<>, #tf.shape<>, #tf.shape<>, #tf.shape<10x80>, #tf.shape<80>, #tf.shape<20x80>], parallel_iterations = 32 : i64} : (tensor<i32>, tensor<i32>, tensor<i32>, tensor<15x1x20xf32>, tensor<75x20xf32>, tensor<75x20xf32>, tensor<75x20xf32>, tensor<i32>, tensor<15x75x10xf32>, tensor<15x75x1xi1>, tensor<10x80xf32>, tensor<80xf32>, tensor<20x80xf32>) -> (tensor<i32>, tensor<i32>, tensor<i32>, tensor<15x1x20xf32>, tensor<75x20xf32>, tensor<75x20xf32>, tensor<75x20xf32>, tensor<i32>, tensor<15x75x10xf32>, tensor<15x75x1xi1>, tensor<10x80xf32>, tensor<80xf32>, tensor<20x80xf32>)
        self._initialize(args, kwargs, add_initializers_to=initializers)
```

# Copy and paste the output here.
```

**Also, please include a link to the saved model or GraphDef**
NER implementation from the link https://www.depends-on-the-definition.com/lstm-with-char-embeddings-for-ner/
```

# Put link here or attach to the issue.
```
I am trying to implement NER from the link https://www.depends-on-the-definition.com/lstm-with-char-embeddings-for-ner/
I am able to generate model file(h5), but not able to convert the model to tflite with the command mentioned above

If I remove the line "converter.optimizations = [tf.lite.Optimize.DEFAULT]", then tflite model gets created. But can't infer from the model on mobile
The error i get while inferencing the model is
Failed to run on the given Interpreter: tensorflow/lite/kernels/concatenation.cc:74 t->dims->data != t0->dims->data (75 != 1)

Note: With the same command mentioned in "Copy and paste here the exact command" tflite conversion works fine with Colab. The same model works fine in mobile
The problem is happening in Local windows 10 PC

**Comment by amahendrakar** [comment]
Was able to reproduce the issue. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/f9eed538a8f24266272852d051781a3e/39053.ipynb). Thanks!

**Comment by harsha113** [comment]
Are there any ways to fix this problem?

**Comment by manmay-nakhashi** [comment]
also facing same issue !!

**Comment by pttzty** [comment]
Having the same issue

**Comment by mattiadg** [comment]
Any solutions found?

**Comment by mohantym** [comment]
Hi @harsha113! 
We are checking to see whether you still need help in this issue .Have you checked the same in Latest version TF 2.6 yet? Thanks!
