### ISSUE TITLE
TF 2.2.0rc4 does not have python 3.8 macOS wheel

### ISSUE THREAD

**Issue by yongtang** [tensorflow/tensorflow#39058]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version: TF 2.2.0 rc4
- Python version: 3.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**

While looking into the available pip wheel packages on pypi.org for 2.2.0rc4:

https://pypi.org/project/tensorflow/2.2.0rc4/#files

I noticed that pip wheel for macOS python 3.8 is not available (only two cp38 files on pypi.org, one is windows and another is linux).

However, pip wheel package for python 3.8 on macOS is available for 2.2.0rc3:

https://pypi.org/project/tensorflow/2.2.0rc4/#files

Wondering if 3.8 for macOS will be available when 2.2.0 final is released?

**Comment by goldiegadde** [comment]
@yongtang thanks for filing this issue, macos py3.8 binaries for 2.2.0-rc4 are now available both on [tensorflow](https://pypi.org/project/tensorflow/2.2.0rc4/#files) and [tensorflow-cpu](https://pypi.org/project/tensorflow-cpu/2.2.0rc4/#files) projects.

I am closing this issue, please do reopen if you run into further issues with these binaries.
