### ISSUE TITLE
Conv2d with large filters fails on V100 GPU

### ISSUE THREAD

**Issue by CNugteren** [tensorflow/tensorflow#39054]
**System information**
- Have I written custom code: **yes**
- OS Platform and Distribution: **Ubuntu 16.04**
- TensorFlow installed from: **binary**
- TensorFlow version: **2.1.0**
- Python version: **3.7.3**
- CUDA/cuDNN version: **10.1 and 7.6.4**
- GPU model and memory: **Tesla V100 with 16 or 32GB**

**Describe the current behavior**

Code segfaults when using a large 2D convolution kernel on a V100 GPU, but not on a GeForce GPU, e.g. GeForce Titan X. Also works fine without a GPU. On a V100, this code segfaults:
```
some_input = tf.random.normal((1, 512, 512, 1))
kernel = tf.random.normal((363, 363, 1, 1))
tf.nn.conv2d(some_input, kernel, strides=[1, 1, 1, 1], padding="SAME")
```
If we set the kernel size to 362 then it works again, but 363x363 and beyond segfaults on the V100 GPU.

**Describe the expected behavior**

It should not segfault on the V100.

**Standalone code to reproduce the issue**

Simple code snippet to reproduce is available here as a gist:
https://gist.github.com/CNugteren/138bc1ecbfbfa42e7b1be85923f48f62

**Other info / logs**

Example log of running the code in the above gist:
```
$ python tf_conv_bug.py
(... some TF GPU information)
>> kernel_size =  362
>> done for kernel_size =  362
>> kernel_size =  363
Segmentation fault (core dumped)
```

**Comment by ravikyram** [comment]
@CNugteren 

I have tried in colab with TF 2.1.0, 2.2-rc3 and i am not seeing any issue. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/76475d07e72d8daa6d7bc8d6ce28de49/untitled846.ipynb).Thanks!

**Comment by CNugteren** [comment]
I dont't see any GPU info in your link. Are you sure you are on a V100?

**Comment by ravikyram** [comment]
@CNugteren 

Sorry my bad i have executed in cpu but not GPU.I have tried in colab with TF 2.10-GPU and i am seeing a message (`Your session crashed for an unknown reason`. ) with kernel size 363.Thanks!

**Comment by reedwm** [comment]
This looks like a CUDA issue, since I can also reproduce in PyTorch:

```python
import torch
torch.backends.cudnn.benchmark = True  # Enable autotune, like in TF
for kernel_size in (362, 363):
  input_image = torch.ones((1, 1, 512, 512)).cuda()
  print('>> kernel_size = ', kernel_size)
  kernel = torch.ones((1, 1, kernel_size, kernel_size)).cuda()
  torch.nn.functional.conv2d(input_image, kernel, stride=1, padding=181)
  print('>> done for kernel_size = ', kernel_size)
```

Running either the TF or PyTorch version with the enviornmental variables `CUDNN_LOGINFO_DBG=1 CUDNN_LOGDEST_DBG=stderr` to enable logging, I see it crashes right after the log that shows conv2d is running with the algorithm `CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM`. I can also reproduce with CUDA 11.

@nluehr, can you address this CUDA issue?

**Comment by nluehr** [comment]
I can reproduce with CUDNN 7.x. The issue will be fixed in CUDNN 8.

**Comment by nluehr** [comment]
@CNugteren now that TF nightlies are built against cudnn 8, can you verify that the issue is resolved?

**Comment by CNugteren** [comment]
I can confirm indeed that the above code now passes successfully on a V100 using `pip install tf-nightly`, C.UDA 11.0 and cuDNN 8.0.3.
