### ISSUE TITLE
Serializing a tensor and writing to tf.train.Example from within a graph

### ISSUE THREAD

**Issue by apcode** [tensorflow/tensorflow#39056]
I would like to write tensorflow example records to a TFRecordWriter from inside an AutoGraph generated graph. I am running inference at scale over millions of examples and so don't want to collect all results in memory, but write them out as I go. I'm reading from a dataset.
Running everything inside a graph is way faster than breaking out every batch to process and save results.  So I just want to be able to write results from within the graph.

The documentation for tensorflow 2.0 states the following:

> The simplest way to handle non-scalar features is to use tf.serialize_tensor to convert tensors to binary-strings. Strings are scalars in tensorflow.

However, `tf.io.serialize_tensor` returns a tensor of byte-string. Creating an Example proto requires a bytes list, not a tensor.

How do I write a tf.train.Example to a tf record from inside a graph?

Code to reproduce:

```
%tensorflow_version 2.x
import tensorflow as tf

@tf.function
def example_write():
  writer = tf.io.TFRecordWriter("test.tfr")
  x = tf.constant([[0, 1], [2, 3]])
  x = tf.io.serialize_tensor(x)
  feature = {
      "data": tf.train.Features(
        bytes_list=tf.train.BytesList(value=[x]))
  }
  ex = tf.train.Example(features=tf.train.Features(
      feature=feature))
  writer.write(ex.SerializeToString())

example_write()
```

and the error

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-df8a97eb17c9> in <module>()
     12   writer.write(ex.SerializeToString())
     13 
---> 14 example_write()

8 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    966           except Exception as e:  # pylint:disable=broad-except
    967             if hasattr(e, "ag_error_metadata"):
--> 968               raise e.ag_error_metadata.to_exception(e)
    969             else:
    970               raise

TypeError: in user code:

    <ipython-input-6-df8a97eb17c9>:6 example_write  *
        feature = {

    TypeError: <tf.Tensor 'SerializeTensor:0' shape=() dtype=string> has type Tensor, but expected one of: bytes
```

**Comment by Saduf2019** [comment]
@apcode 
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by apcode** [comment]
I have asked on SO, with no response.

Having looked into it, I might do two things:
1) file a bug on the documentation which clearly states you can use tf.io.serialize_tensor to convert a tensor to a byte stream. Which it does not. It converts it to a tensor of type tf.string. So it cannot be used as the documentation suggests.

2) File a feature request to be able to write tf records of tf examples from within a graph. None of the TFRecordWriter classes take a tensor!!

**Comment by dqt1995** [comment]
I just modified your code a bit and end up with this:
`def _bytes_feature(value):
  """Returns a bytes_list from a string / byte."""
  return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))


@tf.function
def example_write():

    writer = tf.io.TFRecordWriter("test.tfr")

    g = tf.Graph()

    with g.as_default():
        x = tf.constant([[0, 1], [2, 3]], dtype=tf.float32)
        x = tf.io.serialize_tensor(x)
    
    with tf.compat.v1.Session(graph=g).as_default() as sess:
        x_feat = x.eval()

    print(x_feat)
    feature = {
          "data": _bytes_feature(x_feat)
        }

    ex = tf.train.Example(features=tf.train.Features(
        feature=feature))

    writer.write(ex.SerializeToString())

example_write()`
The key of this code is eval your "x" to end up with byte data, which could be consumed by tf.train.BytesList
My English is not good, so if you need more clarify, just comment below

**Comment by apcode** [comment]
I think when you call eval() you take this out of the graph so when you write it out you're not doing so inside the computation graph. IIUC.

**Comment by dqt1995** [comment]
Right. As the tf.train.BytesList only receive byte data, we must call eval() to take value from tensor. This small graph is just made for serialize tensor, so we don't need to put it inside computation graph.

**Comment by noahtren** [comment]
This would also be very helpful for me, preferably without requiring `tf.py_function`

**Comment by mattlyon93** [comment]
If you are serializing many tensors in a loop, say if you were creating `Example` objects, it would be more efficient to use the `.numpy()` method of the tensor, rather than creating an execution graph each time. So:
```python
x = tf.constant([[[0, 1], [2, 3]],[[1, 1], [2, 2]]], dtype=tf.float32)
xs = tf.io.serialize_tensor(x.numpy()
```

**Comment by tilakrayal** [comment]
@apcode ,
Can you please try the code as [commented](https://github.com/tensorflow/tensorflow/issues/39056#issuecomment-748243172) in latest stable v2.7 and let us know if the issue still persists.

**Comment by apcode** [comment]
@tilakrayal your "commented" link links to this thread, not the tensorflow documentation. I presume you mean the serialize_tensor page:  https://www.tensorflow.org/api_docs/python/tf/io/serialize_tensor

**Comment by apcode** [comment]
Looking at this comment in https://www.tensorflow.org/api_docs/python/tf/io/serialize_tensor

```
feature_of_bytes = tf.train.Feature(
  bytes_list=tf.train.BytesList(value=[serialized_nonscalar.numpy()]))
feature_of_bytes

# followed by 
writer.write(example)

```

It calls serialized_nonscalar.numpy().  So this takes it out of the graph IIUC.

My original problem was I was processing 100Ms of examples and it was extremely slow to keep jumping out of the graph to store a tf.train.Example. E.g. using tf.io.write_file(serialized_tensor) to save results inside the graph would take approx 1-2 hours to process 100Ms examples.  Having to leave the graph to save a tensor, such as calling tensor.numpy() would take over 24 hours for the same 100Ms examples.  Not insignificant.

I think this problem is due to writing to a TFRecord from a Tensor, which is not possible.

The only way I can see to write to a file from within the graph is using  tf.io.write_file(serialized_tensor)
This file writing function seems to be the only one that takes a tensor and writes it to a file inside the computation graph.

So above does not resolve my problem because I cannot write tfrecords of examples from inside the computation graph.

My work around of just writing serialized tensors to a file using tf.io.write_file() works but not ideal as I have to post process these tensors into tf records.

**Comment by kurtgodden** [comment]
I have a similar problem.  I am able to do what is described here: 
https://www.tensorflow.org/api_docs/python/tf/io/serialize_tensor 

with this code, where 'nonscaler' is an np.array of shape (250, 10): 

serialized_nonscalar = tf.convert_to_tensor(nonscalar, np.float32) 
serialized_nonscalar = tf.io.serialize_tensor(serialized_nonscalar)
serialFtr                      = tf.train.Feature(bytes_list=tf.train.BytesList(value=[serialized_nonscalar.numpy()]))

features             = {'foo': serialFtr}
example_proto  = tf.train.Example(features=tf.train.Features(feature=features))
serExProto         =       example_proto.SerializeToString()

Then writing that to file:
with tf.io.TFRecordWriter('_temp.tfrecord') as writer:
    writer.write(serExProto)

and following the tutorial in: https://www.tensorflow.org/tutorials/load_data/tfrecord 

After I read the saved example back in:
raw_dataset = tf.data.TFRecordDataset('_temp.tfrecord')

I see what I expect to see here:

for raw_record in raw_dataset.take(1):
    example = tf.train.Example()
    example.ParseFromString(raw_record.numpy())
    print(example)

And also here:
result = {}
for key, feature in example.features.feature.items():
    kind = feature.WhichOneof('kind')
    result[key] = np.array(getattr(feature, kind).value)

result # this shows: {'foo': array([b'\x08\x01\        etc.

But now I'm stuck. I cannot figure out how to get back my original numpy array from that byte array. I'm guessing this is obvious to some of you, but it sure isn't to me.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
