### ISSUE TITLE
XLA gives error about dynamic shapes in TF 2.1.0, but not in TF 1.15.2

### ISSUE THREAD

**Issue by MatthiasKohl** [tensorflow/tensorflow#39057]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): Binary I believe, it is part of a docker image
- TensorFlow version (use command below): 1.15.2 / 2.1.0
- Python version: 3.6.9
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 10.2.89 / 7.6.5
- GPU model and memory: Nvidia Tesla P100 (16GB)

**Describe the current behavior**

For the same code ([see gist here](https://gist.github.com/MatthiasKohl/3100f81e71309fb02e3b69773352e2c0)) I'm getting an error in TF2 but not in TF1 on XLA compile.

I need to migrate some code from TF1 to TF2 and want to find out what goes wrong here.
Somehow, I believe this has to do with a difference in `tf.compat.v1.data.make_initializable_iterator(tf_data_batched)` between TF1 and TF2 as it might give unknown shapes in TF2 but not TF1. But I'm not really sure and it won't always fail, such as for example when removing the following loss from the graph (lines 77/78 of the gist):
```python
gaussian = tfd.MultivariateNormalDiag(tf.zeros_like(samples), tf.ones_like(samples))
loss_samples = gaussian.log_prob(samples)
```

Can you help me figure out what's the issue here and how to migrate this to TF2 ? Thank you!
Below is the exact error I'm getting on TF2.

```
XLA compilation requires that operator arguments that represent shapes or dimensions be evaluated to concrete values at compile time. This error means that a shape or dimension argument could not be evaluate
d at compile time, usually because the value of the argument depends on a parameter to the computation, on a variable, or on a stateful operation such as a random number generator.
         [[{{node gradients/gradients/MultivariateNormalDiag_1/log_prob/MultivariateNormalDiag_chain_of_MultivariateNormalDiag_shift_of_MultivariateNormalDiag_scale_matvec_linear_operator/inverse/Multivariat
eNormalDiag_scale_matvec_linear_operator/inverse/LinearOperatorDiag/solve/LinearOperatorDiag/solve/mul_grad/Sum_grad/DynamicStitch}}]]
         [[gradients/while_loop_grad/while_loop_grad]]
        This error might be occurring with the use of xla.compile. If it is not necessary that every Op be compiled with XLA, an alternative is to use auto_jit with OptimizerOptions.global_jit_level = ON_2 o
r the environment variable TF_XLA_FLAGS="tf_xla_auto_jit=2" which will attempt to use xla to compile as much of the graph as the compiler is able to.
         [[cluster]]
         [[output_0/_3]]
0 successful operations.
0 derived errors ignored.
```

**Describe the expected behavior**
No error in TF2 just like in TF1.

**Standalone code to reproduce the issue**
See gist: https://gist.github.com/MatthiasKohl/3100f81e71309fb02e3b69773352e2c0
Note that this requires the tensorflow_probability package! I wasn't able to make a smaller example reproducing this bug, unfortunately.

**Comment by amahendrakar** [comment]
@MatthiasKohl,
While running the code with TF v2.1, I'm facing an error stating `ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.2; Detected an installation of version 2.1.0. Please upgrade TensorFlow to proceed.`

However, I did not face any errors while running the code with TF v2.2.0-rc4. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/b96b90a3e897b0396cccfadeca77f6d0/39057-2-2.ipynb). Thanks!

**Comment by MatthiasKohl** [comment]
Thank you for the pointer, I guess you used TF probability version 0.10.0-rc0/1 which is made for TF 2.2+.
Instead, I used TF probability 0.9.0 which is for TF 2.1.0.
Sorry about not stating this more clearly in the description.
I'll try with TFP 0.10 and TF 2.2 as you suggested, hopefully it'll work !

**Comment by MatthiasKohl** [comment]
So I was able to run this using TF v2.2.0-rc3 and TFP 0.10.0-rc0 as I didn't find any container for TF v2.2.0-rc4 GPU right now.
It does work with the TF v2.2.0-rc3, too, and this has solved the issue in my larger application as well.
Thank you very much!
