### ISSUE TITLE
unterminated substitute pattern in download_dependencies.sh

### ISSUE THREAD

**Issue by Jakymiw** [tensorflow/tensorflow#3906]
### Environment info

Operating System:
OS X (El capitan)

I'm trying to build a static library with the end goal of using tensorflow for mobile apps. When I run the download_dependencies script I get this terminal log:
<img width="775" alt="screen shot 2016-08-18 at 2 10 30 pm" src="https://cloud.githubusercontent.com/assets/12484426/17785182/b8263b96-654d-11e6-890b-44f9beb6750f.png">

To an untrained eye it seems like a potentially easy fix but I have no experience with what would be required to fix it so if anyone has any suggestions/could point me in the right direction that would be dope.

Thanks

**Comment by martinwicke** [comment]
@satok16 can you take a look?

**Comment by satok16** [comment]
Sure, let me take a look
