### ISSUE TITLE
Error in Keras Save with TF Lookup

### ISSUE THREAD

**Issue by luischinchillagarcia** [tensorflow/tensorflow#39064]
When using the save method from a tf.keras model (or tf.saved_model.save), an error appears that exporting the model fails due an untracked `tf.Variable`. [Here is a Colab replicating the issue](https://colab.research.google.com/drive/1PCbiubCnzUszW6mB8f8wtft7YFVZlkaB).

```python
import tensorflow as tf

# Create dummy model
model = tf.keras.Sequential([
    tf.keras.Input(shape=(1,), dtype=tf.float32),
    tf.keras.layers.Dense(1)
])

# Create Simple Signature Function
def outer_fn(filepath):
    @tf.function
    def inner_fn(b):
        text_init = tf.lookup.TextFileInitializer(filename=filepath, 
                            key_dtype=tf.string, key_index=0,
                            value_dtype=tf.int64, value_index=tf.lookup.TextFileIndex.LINE_NUMBER
                            )
        table = tf.lookup.StaticHashTable(initializer=text_init, default_value=0)
        return table.lookup(b)
    return inner_fn

# Signature
signatures = {
    'example_signature_1':
        outer_fn(filepath='./test_file').get_concrete_function(
            tf.TensorSpec(shape=[None], dtype=tf.string, name='ex_sig_1')
            ),
}

# Model Save [ERROR - Untracked Tensor]
model.save('.', signatures=signatures)

>>> AssertionError: Tried to export a function which references untracked object Tensor("164:0", shape=(), dtype=resource).TensorFlow objects (e.g. tf.Variable) captured by functions must be tracked by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly.
```
This is assuming a simple text file (here named 'test_file') like this:
```
here_is_one_row
here_is_another_row
```

To attempt to fix this, I (1) tried putting the tf.lookup outside the function, (2) created a tf.keras subclassed layer to use the `config` method - neither of which succeeded. Is there any way to save a `tf.lookup` object that does not appear in the documentation?

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.2.0-rc3](https://colab.research.google.com/gist/amahendrakar/74eb3960f6bca83268e4d9bfa34e7b6e/39064-2-2.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/7ec20802efde45edfc669f0c3e11fed2/39064-tf-nightly.ipynb).

**Comment by luischinchillagarcia** [comment]
Thanks for the response! 

The matrix error has been removed now. I should note the focus was not on this but rather on the tf.lookup working on a function wrapped with 'tf.function', but being able to save using `model.save()`.

**Comment by xiaoyunwu** [comment]
This works for me on tf2.2. Notice you need to attach table to model so that trace does not complain.

import tensorflow as tf

# Create dummy model


"""
# Create Simple Signature Function
def outer_fn(model, vocab_file, num_oov=1):
    model.init = tf.lookup.TextFileInitializer(
        filename=vocab_file,
        key_dtype=tf.string,
        key_index=tf.lookup.TextFileIndex.WHOLE_LINE,
        value_dtype=tf.int64,
        value_index=tf.lookup.TextFileIndex.LINE_NUMBER)
    model.table = tf.lookup.StaticVocabularyTable(
        model.init, num_oov, lookup_key_dtype=tf.string)

    @tf.function
    def inner_fn(b):
        return model.table.lookup(b)
    return inner_fn
"""


def out_intent_fn(model, vocab_file, num_oov=1):
    init = tf.lookup.TextFileInitializer(
        filename=vocab_file,
        key_dtype=tf.string,
        key_index=tf.lookup.TextFileIndex.WHOLE_LINE,
        value_dtype=tf.int64,
        value_index=tf.lookup.TextFileIndex.LINE_NUMBER)

    model.table = tf.lookup.StaticVocabularyTable(
        init, num_oov, lookup_key_dtype=tf.string)

    @tf.function
    def predict_fn(probes):
        ptokens = model.table.lookup(probes)
        return ptokens

    return predict_fn


def outmost():
    export_path = "./"
    vocab_file = "./test.file"

    model = tf.keras.Sequential([
        tf.keras.Input(shape=(1,), dtype=tf.float32),
        tf.keras.layers.Dense(1),
        tf.keras.layers.Dropout(rate=0.2)
    ])

    # Signature
    signatures = {
        'service_default':
            out_intent_fn(model, vocab_file=vocab_file).get_concrete_function(
                tf.TensorSpec(shape=[None], dtype=tf.string)
                ),
    }

    # Model Save [ERROR - Untracked Tensor]
    model.save(export_path, signatures=signatures)


if __name__ == "__main__":
    outmost()

**Comment by Goofy-G** [comment]
Hi @xiaoyunwu 
    I have some question about it. If your serving function like above, how to construct the serving client's input data

**Comment by spate141** [comment]
@xiaoyunwu You have some interesting answer! Can you please format the code? We can't read it properly due to bad formatting. Thanks!

**Comment by spate141** [comment]
Alrighty, since @xiaoyunwu's response was not properly formatted; putting it here _again_ in more readable format. Feel free to comment on if any line is not properly indented. 

```python
import tensorflow as tf

# Create Simple Signature Function
def outer_fn(model, vocab_file, num_oov=1):

    model.init = tf.lookup.TextFileInitializer(
            filename=vocab_file,
            key_dtype=tf.string,
            key_index=tf.lookup.TextFileIndex.WHOLE_LINE,
            value_dtype=tf.int64,
            value_index=tf.lookup.TextFileIndex.LINE_NUMBER
        )
    model.table = tf.lookup.StaticVocabularyTable(model.init, num_oov, lookup_key_dtype=tf.string)

    @tf.function
    def inner_fn(b):
        return model.table.lookup(b)

    return inner_fn


def out_intent_fn(model, vocab_file, num_oov=1):
    init = tf.lookup.TextFileInitializer(
                filename=vocab_file,
                key_dtype=tf.string,
                key_index=tf.lookup.TextFileIndex.WHOLE_LINE,
                value_dtype=tf.int64,
                value_index=tf.lookup.TextFileIndex.LINE_NUMBER)

    model.table = tf.lookup.StaticVocabularyTable(
        init, num_oov, lookup_key_dtype=tf.string)

    @tf.function
    def predict_fn(probes):
        ptokens = model.table.lookup(probes)
        return ptokens

    return predict_fn

def outmost():
    export_path = "./"
    vocab_file = "./test.file"

    model = tf.keras.Sequential([
        tf.keras.Input(shape=(1,), dtype=tf.float32),
        tf.keras.layers.Dense(1),
        tf.keras.layers.Dropout(rate=0.2)
    ])

    # Signature
    signatures = {
        'service_default':
            out_intent_fn(
                model, vocab_file=vocab_file
                ).get_concrete_function(tf.TensorSpec(shape=[None], dtype=tf.string))
    }

    # Model Save [ERROR - Untracked Tensor]
    model.save(export_path, signatures=signatures)

if name == "main":
    outmost()
```

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/9bd12e8535271cd3f78db86f7099b553/untitled302.ipynb) ..Thanks!

**Comment by mohantym** [comment]
This issue in replicating in TF 2.7 and nightly version . Attaching [Gist](https://colab.research.google.com/gist/mohantym/98e7a70c2071aa6b7d00e1c4bf4ecd31/untitled302.ipynb#scrollTo=GOXO1knUzouk) for reference. Thanks

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
