### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by SlowMonk** [tensorflow/tensorflow#39065]
Tryint to iter through the dataset 
using tensorflow 2.0 

```
def make_dataset(X_data,y_data,n_splits):
    
    def gen():
        for train_index, test_index in KFold(n_splits).split(X_data):
            X_train, X_test = X_data[train_index], X_data[test_index]
            y_train, y_test = y_data[train_index], y_data[tests_index]
            yield X_train, y_train,X_test,y_test
    return tf.data.Dataset.from_generator(gen,(tf.float32,tf.float32),(tf.TensorShape([40,40,9]), tf.TensorShape([40,40,1])))
dataset= make_dataset(X,y,5)

import tensorflow as tf
import tensorflow.contrib.eager as tfe
for X_train, y_train,X_test,y_test in tfe.Iterator(dataset):
    print(X_train.shape)

```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-950ccb8e9a23> in <module>
----> 1 for X_train, y_train,X_test,y_test in trt.Iterator(dataset):
      2     print(X_train.shape)

AttributeError: module 'tensorflow.python.compiler.tensorrt.trt_convert' has no attribute 'Iterator'
time: 17.4 ms

**Comment by iobtl** [comment]
`tf.contrib` does not exist in TensorFlow 2.0 Is there a particular reason you wish to use `tfe.Iterator(dataset)`?  

Otherwise, this may work as well:
```
import tensorflow as tf
for X_train, y_train, X_test, y_test in dataset.take(3).as_numpy_iterator():
    print(X_train.shape)
```

**Comment by ravikyram** [comment]
@SlowMonk 
tensorflow.contrib is being removed in version TF 2.x and it works in only TF 1.x. In Tensorflow 2.0, eager execution is enabled by default. Can you try with @iobtl suggestion and see if it helps you. Thanks!
