### ISSUE TITLE
Windows build error: 'mlir::FoldingHook': 'value' is not a valid template type argument for parameter 'ConcreteType'

### ISSUE THREAD

**Issue by DBraun** [tensorflow/tensorflow#39061]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro 10.0.18363
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.1 (SHA-1 is c878390581fc817564f8ebe1f4237d0cbd225f14)
- Python version: 3.7
- Installed using virtualenv? pip? conda?: N/A?
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): (BAZEL_VS: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools)
- CUDA/cuDNN version: CUDA 10.1, cuDNN 7.6.5
- GPU model and memory: RTX 2080 (8GB)

I'm following this guide https://github.com/sitting-duck/stuff/tree/master/ai/tensorflow/build_tensorflow_1.14_source_for_Windows and advice here https://github.com/tensorflow/tensorflow/issues/23542 with some adjustments to build Tensorflow 2.1 for Windows.

I ran `python configure.py` and this ended up being my `.tf_configure.bazelrc`:

    build --action_env PYTHON_BIN_PATH="C:/Python37/python.exe"
    build --action_env PYTHON_LIB_PATH="C:/Python37/lib/site-packages"
    build --python_path="C:/Python37/python.exe"
    build --config=xla
    build --action_env CUDA_TOOLKIT_PATH="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1"
    build --action_env TF_CUDA_COMPUTE_CAPABILITIES="7.5"
    build --config=cuda
    build:opt --copt=/arch:AVX2
    build:opt --define with_default_optimizations=true
    build --define=override_eigen_strong_inline=true
    test --flaky_test_attempts=3
    test --test_size_filters=small,medium
    test:v1 --test_tag_filters=-benchmark-test,-no_oss,-no_windows,-no_windows_gpu,-no_gpu,-oss_serial
    test:v1 --build_tag_filters=-benchmark-test,-no_oss,-no_windows,-no_windows_gpu,-no_gpu
    test:v2 --test_tag_filters=-benchmark-test,-no_oss,-no_windows,-no_windows_gpu,-no_gpu,-oss_serial,-v1only
    test:v2 --build_tag_filters=-benchmark-test,-no_oss,-no_windows,-no_windows_gpu,-no_gpu,-v1only
    build --action_env TF_CONFIGURE_IOS="0"

Then I did

`bazel build --config=cuda --copt=-nvcc_options=disable-warnings tensorflow:tensorflow.dll`

I've done this twice and got the same error during the build. Pardon the mess...

ERROR: C:/users/SOMEUSER/_bazel_SOMEUSER/dktb5wq4/external/llvm-project/mlir/BUILD:75:1: C++ compilation of rule '@llvm-project//mlir:IR' failed (Exit 2): python.exe failed: error executing command
  cd C:/users/SOMEUSER/_bazel_SOMEUSER/dktb5wq4/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\ATLMFC\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\lib\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\;;C:\WINDOWS\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Python37/python.exe
    SET PYTHON_LIB_PATH=C:/Python37/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\SOMEU~1\AppData\Local\Temp
    SET TF2_BEHAVIOR=1
    SET TF_CONFIGURE_IOS=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=7.5
    SET TF_ENABLE_XLA=1
    SET TF_NEED_CUDA=1
    SET TMP=C:\Users\SOMEU~1\AppData\Local\Temp
  C:/Python37/python.exe -B external/local_config_cuda/crosstool/windows/msvc_wrapper_for_nvcc.py /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/llvm-project /Ibazel-out/x64_windows-opt/bin/external/llvm-project /Iexternal/zlib /Ibazel-out/x64_windows-opt/bin/external/zlib /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/CallOpInterfacesIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/DialectSymbolRegistry /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/InferTypeOpInterfaceIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/OpAsmInterfacesIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/SideEffectInterfacesIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/SymbolInterfacesIncGen /Iexternal/llvm-project/mlir/include /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/include /Iexternal/llvm-project/llvm/include /Ibazel-out/x64_windows-opt/bin/external/llvm-project/llvm/include /Iexternal/zlib /Ibazel-out/x64_windows-opt/bin/external/zlib /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_DEPRECATE /D_CRT_NONSTDC_NO_WARNINGS /D_SCL_SECURE_NO_DEPRECATE /D_SCL_SECURE_NO_WARNINGS /DUNICODE /D_UNICODE /DLLVM_ENABLE_STATS /D__STDC_LIMIT_MACROS /D__STDC_CONSTANT_MACROS /D__STDC_FORMAT_MACROS /DLLVM_BUILD_GLOBAL_ISEL /showIncludes /MD /O2 /DNDEBUG /w /D_USE_MATH_DEFINES -DWIN32_LEAN_AND_MEAN -DNOGDI /std:c++14 /Fobazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_objs/IR/Module.o /c external/llvm-project/mlir/lib/IR/Module.cpp
Execution platform: @local_execution_config_platform//:platform
external/llvm-project/mlir/include\mlir/IR/OpDefinition.h(1185): error C2923: 'mlir::FoldingHook': 'value' is not a valid template type argument for parameter 'ConcreteType'
external/llvm-project/llvm/include\llvm/ADT/STLExtras.h(1281): note: see declaration of 'value'
external/llvm-project/mlir/include\mlir/IR/Module.h(36): note: see reference to class template instantiation 'mlir::Op<mlir::ModuleOp,mlir::OpTrait::ZeroOperands,mlir::OpTrait::ZeroResult,mlir::OpTrait::IsIsolatedFromAbove,mlir::OpTrait::PolyhedralScope,mlir::OpTrait::SymbolTable,mlir::OpTrait::SingleBlockImplicitTerminator<mlir::ModuleTerminatorOp>::Impl,mlir::SymbolOpInterface::Trait>' being compiled
external/llvm-project/mlir/include\mlir/IR/OpDefinition.h(1187): error C2955: 'mlir::FoldingHook': use of class template requires template argument list
external/llvm-project/mlir/include\mlir/IR/OpDefinition.h(273): note: see declaration of 'mlir::FoldingHook'
Target //tensorflow:tensorflow.dll failed to build
INFO: Elapsed time: 1466.809s, Critical Path: 96.50s
INFO: 3656 processes: 3656 local.
FAILED: Build did NOT complete successfully

The first time the build stopped entirely. The second time, which is right now, the same error reported, but it's still running. I see
`[10,544 / 12,151] Compiling tensorflow/core/kernels/scatter_op.cc; 5820s local`

Is there any hope that this will finish? What can be done to fix the error? Thanks for reading.
Update: I noticed my CPU wasn't working hard at all while waiting for the second round, so I decided to terminate it.

**Comment by DBraun** [comment]
I pulled 580b03a12c50df594d693bda032fdfb40b8a186b and tried to build again. No error this time but it's stalling on 
`[12,645 / 12,648] Compiling tensorflow/core/kernels/tile_ops.cc; 36514s local`

Task manager doesn't show the CPU working hard, so I think it's not going anywhere. What can I do? Problems of this sort have been my experience for several months. It's difficult to get a ballpark of how long any specific compilation task should take.

**Comment by jpienaar** [comment]
The Windows build breakage was fixed. For the slow compilation time I'd recommend filing a separate issue as it is unrelated to this issue and folks might not notice it due to issue title.

If you add -s to the bazel command it will show all the instructions being ran and you could check rerunning that command directly (I'd suggest only adding that option post it getting stuck to avoid it reporting all the successful commands too). I have not seen compile times near that length even on Windows so that's weird. Potentially also try using clang to build it on Windows to narrow down causes.
