### ISSUE TITLE
XLA function crashed when called under GradientTape

### ISSUE THREAD

**Issue by EgorLakomkin** [tensorflow/tensorflow#39060]
Hello,

**Describe the current behavior**

I have a function compiled with XLA (tf.function + experimental_compile=True) which writes the processed output to the TensorArray. When called inside GradientTape it crashes. Without experimental_compile=True everything works fine.

**Describe the expected behavior**
function does not crash

**Standalone code to reproduce the issue**
Colab link to reproduce the crash: https://colab.research.google.com/drive/1Hh7fFkWVC8YCPqTtkQXDNVB8elQS8rq0#scrollTo=MpeMlEwGje0n

**Comment by EgorLakomkin** [comment]
It seems like the TensorArray is causing this crash.

**Comment by amahendrakar** [comment]
Was able to reproduce the error with [TF v2.2.0-rc3](https://colab.research.google.com/gist/amahendrakar/8c6095ec7494526e323fd789253b753b/39060-2-2.ipynb#scrollTo=yHUVor_qkn7h) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/d113930f63ca0bb2c640ada2efaee9b4/39060-tf-nightly.ipynb). 
However, code works without any issues with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/32dfbddc0ddfb20bacb17eef47761b0a/39060-2-1.ipynb). Please find the attached gist. Thanks!

**Comment by cheshire** [comment]
@EgorLakomkin As a workaround, you can remove `@tf.function(experimental_compile=True)` around the `call` method inside the layer. Here it does not do anything (since the whole computation is compiled by the outer function), and is causing the crash.

In general, `TensorArray` handling in XLA does have some sharp edges...

**Comment by EgorLakomkin** [comment]
@cheshire Thank you for the suggestion! I am looking how to use XLA for implementing a RNN, maybe there is an alternative to TensorArray to do it?

**Comment by cheshire** [comment]
@EgorLakomkin There is one bug and one missing feature here: 

1) Nested `tf.function(experimental_compile=True)` should not affect the result at all, but here it does (the error you are seeing)
2) If you remove the outer `tf.function` you'll get the missing feature: `TensorArray` transition across TF/XLA boundary is not implemented.

If you are fine with keeping the outer `tf.function(experimental_compile=True)` you should be able to do it as you are doing now and keep good performance, right?
Or do you want to ship it as a library where you have no control over the user code which might take a derivative?

**Comment by EgorLakomkin** [comment]
@cheshire  Thank you! If I keep only the outer experimental_compile I also have the code crash (repro in colab https://colab.research.google.com/drive/1ehh6kklHmXSmcDs6mCdM-6y59v01dXKF?usp=sharing), though its completely different one:

    XLA compilation requires that operator arguments that represent shapes or dimensions be evaluated to concrete values at compile time.

**Comment by cheshire** [comment]
@EgorLakomkin I have a fix for the issue with both inner and outer function compiled, which should be released shortly.

Could you file a separate bug on `XLA compilation requires that operator arguments that represent shapes or dimensions be evaluated to concrete values at compile time.` and assign it to me? Also your colab link is requiring some permissions I don't have.

**Comment by cheshire** [comment]
0e4e0c593bf7957aefd29818e2d24caee00c841a fixes your original problem. Could you file another bug for a different problem you are seeing?

**Comment by EgorLakomkin** [comment]
@cheshire Thank you! Filed a ticket with another issue: https://github.com/tensorflow/tensorflow/issues/39904 Cannot assign you directly on GitHub (at least did not find out how).

**Comment by goldiegadde** [comment]
@EgorLakomkin can we close this issue, since the original issue is solved.

**Comment by EgorLakomkin** [comment]
Sure, thx for the fix!
