### ISSUE TITLE
Support Ragged inputs in a Dense layer.

### ISSUE THREAD

**Issue by foxik** [tensorflow/tensorflow#39072]
**System information**
- TensorFlow version (you are using): **TF 2.1, 2.2.0-rc4, TF nightly**
- Are you willing to contribute it (Yes/No): **Yes**

**Describe the feature and the current behavior/state.**

Currently, `tf.keras.layers.Dense` does not support RaggedTensor inputs.
https://github.com/tensorflow/tensorflow/blob/203aa8b6341b30abef0e24edb549c11c7966229e/tensorflow/python/keras/layers/core.py#L1180
However, if the ragged dimension is not the last, it would be extremely useful if it did.

For example, if you want to do sequence labeling, you pass a ragged tensor with differently length sequences through an Embedding layer, then through a RNN, and then you would need to add the final classification Dense layer, which is currently not straightforward.

Therefore, I propose to use something like `RaggedTensor.with_flat_values` on the output of the Dense layer applied to `RaggedTensor.flat_values`.

**Will this change the current api? How?**

No new methods; the Dense layer would only add support for ragged tensors.

**Who will benefit with this feature?**

I think anybody using ragged tensors.

**Comment by markomernick** [comment]
Hi @foxik -

Can you try wrapping your Dense layer in a TimeDistributed? As long as your innermost dimension is not ragged, this should work at head. If not, please let me know!

**Comment by foxik** [comment]
@markomernick Oh, I did not realize it could be used that way -- yes, it works (and it does exactly what I was hoping for). I am closing the issue, sorry for taking your time. Cheers!

**Comment by JohannesAck** [comment]
> Hi @foxik -
> 
> Can you try wrapping your Dense layer in a TimeDistributed? As long as your innermost dimension is not ragged, this should work at head. If not, please let me know!

Hi, I just had the same issue and this is indeed a great solution.
I think it would make sense to mention this in the error message, as currently it only reads 

>ValueError: Layer dense does not support RaggedTensors as input. Inputs received: [...],[...]. You can try converting your input to an uniform tensor.

Not sure where else to bring this up, I hope it is alright to comment here.
