### ISSUE TITLE
LSTM/GRU performance discrepancy

### ISSUE THREAD

**Issue by AwekasGerald** [tensorflow/tensorflow#39076]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Fedora32/Colab/Ubuntu 19.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0rc4/2.2.0rc3/2.1.0
- Python version: 3.7.6/3.7.4/3.6.9
- CUDA/cuDNN version: 10.1
- GPU model and memory: GTX 970 4GB/Colab GPU/NVIDIA Tesla P100 16GB

**Describe the current behavior**
I'm experimenting with models that require the state of LSTMs to be processed after after each time step. So I tried unrolling the LSTM layer in a loop, iterating over the time steps. That's were I noticed a huge increase in time per training step. Uppon further investigation I noticed that this is also the case in some other configuration featuring LSTMs/GRUs. Different versions of TensorFlow are effected differently. See below:

Some results:
|    | Colab | Compute Cloud | Local |
| ------------- | ------------- | ------------- | ------------- |
| Keras Sequential with LSTMs  | 17ms/step  | 15ms/step | 17ms/step |
| Keras Sequential with GRUs  | 17ms/step  | 14ms/step | 16ms/step |
| [Custom Model](https://www.tensorflow.org/guide/keras/custom_layers_and_models) with LSTMs  | 17ms/step  | 14ms/step | 17ms/step |
| Custom Model with GRUs  | 88ms/step  | 14ms/step | 40ms/step |
| Custom Model with LSTMs in loop  | 120ms/step  | 173ms/step | 81ms/step |
| Custom Model with GRUs in loop  | 107ms/step  | 153ms/step | 66ms/step 
| Custom Model with compat LSTMs  | 19ms/step  | 15ms/step | 17ms/step |
| Custom Model with compat GRUs  | 20ms/step  | 15ms/step | 17ms/step |
| Custom Model with compat LSTMs in loop  | 87ms/step  | 108ms/step | 62ms/step |
| Custom Model with compat GRUs in loop  | 78ms/step  | 86ms/step | 49ms/step |

Colab: TF 2.2.0rc3, Python 3.6.9, with GPU
Compute Cloud: TF 2.1.0, Python 3.7.4, Cuda 10.1, Nvidia Tesla P100, Ubuntu 19.04
Local: TF 2.2.0rc4, Python 3.7.6, Cuda 10.1, Nvidia GTX 970, Fedora 32

![index](https://user-images.githubusercontent.com/64591330/80797451-28946c80-8ba2-11ea-9196-b526c4767bd6.png)

**Describe the expected behavior**
Time per step should be more or less similar.

**Standalone code to reproduce the issue** 
[Colab Notebook](https://colab.research.google.com/drive/19-JZo_iJwsoR2gqpXtuN_sbBkEyQtxx4)

**Comment by Saduf2019** [comment]
@AwekasGerald 
I ran the code shared and face an error, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/bd5bc7699b1084438ef8bfa778ef7d90/39076.ipynb)

**Comment by AwekasGerald** [comment]
Please make sure to use a **colab runtime with GPU**!
(runtime -> change runtime type -> select "GPU" as hardware accelerator)

**Comment by Saduf2019** [comment]
@AwekasGerald
I ran the code on gpu, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/2e3fc015fd92aca06e4d8218e5a00501/39076.ipynb) and let us know if this confirms your issue.

**Comment by AwekasGerald** [comment]
Yes, it does.

**Comment by qlzh727** [comment]
Thanks for reporting the issue. I think the performance discrepancy is expected between a python while loop vs a fused LSTM/GRU layer.

In TF2, we use cudnn kernels in tf.keras.layers.LSTM/GRU, which will execute the whole timesteps in one op. This is usually much more fast than an unrolled for loop, which will execute the individual timesteps one by one (while will be slower than tf.while).
