### ISSUE TITLE
TPU usage while running a model using Transfer Learning 

### ISSUE THREAD

**Issue by prudhvirajboddu** [tensorflow/tensorflow#39078]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Google colab version
- TensorFlow version (use command below):2.2.0rc3
- Python version:3.6.9
- Bazel version (if compiling from source):No
- GCC/Compiler version (if compiling from source):No
- CUDA/cuDNN version:No
- GPU model and memory: TPU

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Showing this error while usingTransfer learning and TPU together **
 `
FailedPreconditionError: Error while reading resource variable efficientnet-b0/stem/conv2d/kernel_31710 from Container: worker. This could mean that the variable was uninitialized. Not found: Resource worker/efficientnet-b0/stem/conv2d/kernel_31710/N10tensorflow3VarE does not exist.`

**The model should start fitting the data**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
https://colab.research.google.com/drive/14Gx2l195vQaCC_GWoyhgW_Qnwsfk5vGN#scrollTo=2CVARbH2K01F&line=1&uniqifier=1

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by abhinavsp0730** [comment]
Hey, @prudhvirajboddu kindly set the share option your colab to everyone.

**Comment by prudhvirajboddu** [comment]
https://www.github.com/prudhvirajboddu/TensorFlowML/tree/master/Classification_of_Flowers_using_a_TPU.ipynb

Here it is not able to run an transfer learning models and also Tensoboard callbacks aren't working when using TPU in colab

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/4d06a579310ffead5fae8438f493e861/39078-2-1.ipynb), and [TF v2.2.0rc4](https://colab.research.google.com/gist/amahendrakar/b4044a2dfd7d20d80933ec65f1725303/39078.ipynb#scrollTo=nEip_PfXU5FB). Please find the attached gist. Thanks!
