### ISSUE TITLE
Passing call arguments to individual layers of a model

### ISSUE THREAD

**Issue by imansb** [tensorflow/tensorflow#39070]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.1.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
There does not seem to be a way to pass call argument to individual layers of a model.
For example I have been unable to find a way to pass initial_state call argument to the lstm layers inside a model. I explored multiple pathways and all failed.
          

**Will this change the current api? How?** 

**Who will benefit with this feature?** everyone

**Any Other info.** Seems to be a simple fix

**Comment by qlzh727** [comment]
I think you can build your model by subclassing tf.keras.Model like below:

```
import tensorflow as tf

class Model(tf.keras.Model):

  def __init__(self):
    super(Model, self).__init__()
    self.lstm = tf.keras.layers.LSTM(10)

  def call(self, inputs, initial_state):
    output = self.lstm(inputs, initial_state=initial_state)
    return output

model = Model()
model(tf.zeros((8, 2, 5)), initial_state=[tf.zeros((8, 10)), tf.zeros((8, 10))])
```
