### ISSUE TITLE
google.protobuf.message.DecodeError With Multi-GPU and Mirrored Strategy on 2.2rc3 (and 2.2rc4)

### ISSUE THREAD

**Issue by mattangus** [tensorflow/tensorflow#39082]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 16.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary): `python3 -m pip install tensorflow-gpu==2.2rc3` (and 2.2rc4)
- TensorFlow version (use command below): `v2.2.0-rc2-77-gaad398b5e9 2.2.0-rc3`
- Python version: `3.6.9`
- Bazel version (if compiling from source): **N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **CUDA - 10.1, cuDNN 7.6.4**
- GPU model and memory: **eight Tesla V100-SXM2-16GB**
ouput of `nvidia-smi topo -m`

```
	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	mlx5_0	mlx5_1	mlx5_2	CPU Affinity
GPU0	 X 	NV1	NV1	NV2	NV2	SYS	SYS	SYS	PIX	PHB	SYS	0-19,40-59
GPU1	NV1	 X 	NV2	NV1	SYS	NV2	SYS	SYS	PIX	PHB	SYS	0-19,40-59
GPU2	NV1	NV2	 X 	NV2	SYS	SYS	NV1	SYS	PHB	PIX	SYS	0-19,40-59
GPU3	NV2	NV1	NV2	 X 	SYS	SYS	SYS	NV1	PHB	PIX	SYS	0-19,40-59
GPU4	NV2	SYS	SYS	SYS	 X 	NV1	NV1	NV2	SYS	SYS	PIX	20-39,60-79
GPU5	SYS	NV2	SYS	SYS	NV1	 X 	NV2	NV1	SYS	SYS	PIX	20-39,60-79
GPU6	SYS	SYS	NV1	SYS	NV1	NV2	 X 	NV2	SYS	SYS	PHB	20-39,60-79
GPU7	SYS	SYS	SYS	NV1	NV2	NV1	NV2	 X 	SYS	SYS	PHB	20-39,60-79
mlx5_0	PIX	PIX	PHB	PHB	SYS	SYS	SYS	SYS	 X 	PHB	SYS	
mlx5_1	PHB	PHB	PIX	PIX	SYS	SYS	SYS	SYS	PHB	 X 	SYS	
mlx5_2	SYS	SYS	SYS	SYS	PIX	PIX	PHB	PHB	SYS	SYS	 X 	

```

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

When running the following:

```
strategy = tf.distribute.MirroredStrategy()
run_config = tf.estimator.tpu.RunConfig(
      ...
      train_distribute=strategy
  )
train_estimator = tf.estimator.tpu.TPUEstimator(
        ...
        config=run_config)
train_estimator.train(...)
```

The following exception occurs, when at least one visible GPU is not connected via NVLink. 

```
INFO:tensorflow:training_loop marked as finished
I0501 17:10:16.417816 139720608089920 error_handling.py:115] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W0501 17:10:16.418111 139720608089920 error_handling.py:149] Reraising captured error
Parsing Inputs...
Parsing Inputs...
Parsing Inputs...
Parsing Inputs...
Parsing Inputs...
Parsing Inputs...
Parsing Inputs...
Parsing Inputs...
Parsing Inputs...
Parsing Inputs...
Parsing Inputs...
Parsing Inputs...
Parsing Inputs...
Parsing Inputs...
Parsing Inputs...
Parsing Inputs...
Parsing Inputs...
Parsing Inputs...
Parsing Inputs...
Parsing Inputs...
Parsing Inputs...
Traceback (most recent call last):
  File "main.py", line 427, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 283, in main
    FLAGS.train_batch_size))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3083, in train
    rendezvous.raise_errors()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3078, in train
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1180, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1242, in _train_model_distributed
    self._config._train_distribute, input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1356, in _actual_train_model_distributed
    saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1514, in _train_with_estimator_spec
    log_step_count_steps=log_step_count_steps) as mon_sess:
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 604, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1038, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 737, in __init__
    h.begin()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/basic_session_run_hooks.py", line 563, in begin
    self._summary_writer = SummaryWriterCache.get(self._checkpoint_dir)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/summary/writer/writer_cache.py", line 63, in get
    logdir, graph=ops.get_default_graph())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/summary/writer/writer.py", line 372, in __init__
    super(FileWriter, self).__init__(event_writer, graph, graph_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/summary/writer/writer.py", line 84, in __init__
    self.add_graph(graph=graph, graph_def=graph_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/summary/writer/writer.py", line 194, in add_graph
    true_graph_def = graph.as_graph_def(add_shapes=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3136, in as_graph_def
    result, _ = self._as_graph_def(from_version, add_shapes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3053, in _as_graph_def
    graph.ParseFromString(compat.as_bytes(data))
google.protobuf.message.DecodeError: Error parsing message
```

However when limiting this to GPUs connected via NVLink (i.e. `CUDA_VISIBLE_DEVICES="0,1,2,3"` or `CUDA_VISIBLE_DEVICES="4,5,6,7"`) this error does not occur. It does occur even when 2 GPUs are given that aren't NVLink connected (i.e. `CUDA_VISIBLE_DEVICES="0,5"`).

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

I was unable to reproduce using a minimal example, however the code is a [distributed fork of google brain's efficientdet](https://github.com/fsx950223/automl).

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by anj-s** [comment]
@mattangus Using MirroredStrategy with TPUEstimator may result in unexpected errors. Can you try using [TPUStrategy or MirroredStrategy](https://www.tensorflow.org/guide/distributed_training)? Thanks!

**Comment by mattangus** [comment]
I am currently using `MirroredStrategy`.  I don't have access to TPUs so I don't think I can use `TPUStrategy`.

**Comment by mattangus** [comment]
The skeleton of that version of my code is:

```
strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
    dataset = input_fn(...)
    ...
    loss, train_op = strategy.experimental_run_v2(model_fn,
                          args=(...))
    train_group = tf.group(train_op.values)

with tf.train.MonitoredTrainingSession(...) as sess:
    for i in range(max_steps):
          sess.run(train_op)
          if sess.should_stop():
               break
          sess.run(train_group)
```

**Comment by anj-s** [comment]
@mattangus Just to confirm, does this happen without MirroredStrategy? I need a standalone reproducible example to debug this issue. Can you use the skeleton code you pasted above to make a more complete example?
We haven't tested MirroredStrategy without Estimator so it would be preferable to use Estimators in the example above. We are also focusing on Keras which is the high level API of TensorFlow. Would you be able to use Keras instead?

**Comment by mattangus** [comment]
This doesn't happen without MirroredStrategy. Only with MirroredStrategy *and* a sufficient number of GPUs. The error doesn't happen with a very small example (adding two variables). I have yet to find a sufficiently self contained example where this occurs.

**Comment by mattangus** [comment]
@anj-s Could the graph def be too large? In the function `tensorflow/python/framework/ops.py(3053)_as_graph_def()` there is a bit in the docstring saying:

> Raises:
      ValueError: If the `graph_def` would be too large.

Using `pdb.post_mortem` I get that `len(data)` is `5167271945` which is about `4.8` GB.

**Comment by mattangus** [comment]
I'm not sure if this is helpful at all but the result of `print(graph)` after the error occurs is:

```
graph
node {
  name: "Const"
  op: "Const"
  device: "/replica:0/task:0/device:CPU:0"
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 196416
            name: "\010\004"
          }
        }
      }
    }
  }
}
```

**Comment by sushreebarsa** [comment]
@mattangus It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.4.1 or 2.5.0 and let us know if the issue still persists? Thanks!

**Comment by mattangus** [comment]
I think this issue can be closed. I no longer have access to the machine that was causing problems so I cannot test if an upgrade would work.
