### ISSUE TITLE
Broken URL in Fairness Indicators documentation

### ISSUE THREAD

**Issue by catyeo18** [tensorflow/tensorflow#39081]
On this documentation [page](https://www.tensorflow.org/tfx/guide/fairness_indicators), the URL linked at the end of the paragraph under "Data" is broken.

<img width="719" alt="Screen Shot 2020-05-01 at 10 22 37" src="https://user-images.githubusercontent.com/20053362/80825676-b6b62600-8b95-11ea-90bd-84d7e64f0b2f.png">

It directs to https://www.tensorflow.org/tfx/guide/bit.ly/fairness-indicators-guidance, but that leads to an Error 404 page.

**Comment by oke-aditya** [comment]
This URL ``` https://www.tensorflow.org/tfx/guide/bit.ly/fairness-indicators-guidance ```

Needs to be changed to [this](https://www.tensorflow.org/tfx/fairness_indicators/guidance) url.

**Comment by amahendrakar** [comment]
@catyeo18,
Since this issue is regarding TFX, could you please create a new issue in the TFX repo from [this link](https://github.com/tensorflow/tfx/issues/new), so that we can track it there. Thanks!

**Comment by catyeo18** [comment]
New issue in TFX repo has been created [here](https://github.com/tensorflow/tfx/issues/1769). Closing this issue now.
