### ISSUE TITLE
About website link 404 not found in README

### ISSUE THREAD

**Issue by ericliyanghui** [tensorflow/tensorflow#39080]
Could you add the website link in the following url：
https://github.com/tensorflow/tensorflow/tree/r1.13/tensorflow/contrib/quantize

![image](https://user-images.githubusercontent.com/35229624/80811968-97e97b00-8bf9-11ea-9752-8b65e886e8d5.png)
the link marked in blue is 404 not found.

Thank you!

**Comment by ymodak** [comment]
The `contrib/quantize` is deprecated. We recommend using [post-training quantization](https://blog.tensorflow.org/2020/04/quantization-aware-training-with-tensorflow-model-optimization-toolkit.html) or [quantization aware training](https://blog.tensorflow.org/2020/04/quantization-aware-training-with-tensorflow-model-optimization-toolkit.html) approach with TF 2.X 
Thanks!
