### ISSUE TITLE
Improve training runtime reporting during .fit() for different modes.

### ISSUE THREAD

**Issue by robertlugg** [tensorflow/tensorflow#39084]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
2.0

- Are you willing to contribute it (Yes/No):
yes

**Describe the feature and the current behavior/state.**
The request is to improve the real-time timing reporting across the .fit() train variations.  The format, units, and behavior differ currently

## Baseline
"standard reporting" looks like this:
```
Epoch 9/100
3200/3200 [==============================] - 61s 19ms/sample - loss: 1.4259e-07 - accuracy: 1.0000
```
Note the implicit "per epoch" in 61s.  Also that number sometimes is "ETA" and then switches to "per epoch" once that epoch is over.  Note also that unit time is per sample.  And note that time is in milliseconds.

### Worker 1:
```
Epoch 1/100
3200/3200 [==============================] - 209s 65ms/sample - loss: 0.1447 - accuracy: 0.9873
Epoch 2/100
 480/3200 [===>..........................] - ETA: 2:44 - loss: 8.5048e-06 - accuracy: 1.0000
```
### Worker 2:
```
Epoch 1/100
  32/3200 [..............................] - ETA: 15:14 - loss: 0.7334 - accuracy: 0.66  64/3200 [..............................] - ETA: 9:05 - loss: 5.8474 - accuracy: 0.718  96/3200 [..............................] - ETA: 7:01 - loss: 3.9763 - accuracy: 0.809 128/3200 [>.............................] - ETA: 5:59 - loss: 3.1775 - accuracy: 0.802 160/3200 [>.............................] - ETA: 5:22 - loss: 2.5869 - accuracy: 0.829
```
#### My belief:  Worker 2 is not honoring the 'verbose' setting of 1 which I set in the chief worker.
The request is one way or another make the reporting the same for each worker of the same type.

## dataset versus numpy
The output of .fit() depends on the training data
Case A: Input and output are numpy arrays
Case B: Input is a dataset.
The following is for dataset:
```
Epoch 1/100
     17/Unknown - 41s 2s/step - loss: 0.6328 - accuracy: 0.9323
```
, the previous examples were for numpy inputs.
NOTE 1:  The units are now per step instead of per sample
NOTE 2: How many examples are in a "step" for a 2 worker job?  Is it batch_size or batch_size/# of workers?  What should it be?
NOTE 3:  There is only one significant digit "2".  There should be a fixed number of significant digits or maybe an absolute precision (i.e. always show to tenth of millisecond) or a combination of the two.

Anything to improve the reporting is appreciated.  I suggest:

1) Be sure that all workers comply with the "verbose" setting properly.  This is speculation as to the problem on my part.
2) Either report /step or /example, or both.  But be consistent.
3) Don't mix "ETA" with "/epoch".  Maybe show both always.  If ETA is unknown, then ok to report unknown.
4) Figure out a good rule for showing data.  One rule might be: Always show to 1/10th of a unit regardless of unit (so if a time is written in seconds, show number rounded to nearest 0.1 second, if time is in ms, then show in 0.1 ms.  Then consider significant digits.
5) Consider how time should be reported when using tf.distribute (eg reporting when running 1 worker versus reporting when running two workers.  I don't have suggestions for this one.

**Will this change the current api? How?**
no

**Who will benefit with this feature?**
Users who wish to compare runtime between various training modes
**Any Other info.**

**Comment by jvishnuvardhan** [comment]
@robertlugg Sorry for the late response. Are you still interested in contributing? If yes, please feel free to open a PR in  [keras-team/keras repo.](https://github.com/keras-team/keras/issues) repository.

Please note that Keras development moved to keras-team/keras repository to focus on only keras. Thanks!
