### ISSUE TITLE
It is not possible to train the trainable parameters of the RandomFourierFeatures keras layer in eager mode

### ISSUE THREAD

**Issue by johnamcleod** [tensorflow/tensorflow#39088]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes; minimal working example provided
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux-5.3.0-46-generic-x86_64-with-Ubuntu-18.04-bionic
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0.dev20200501
- Python version: 3.7.5
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
It is not possible to train the "trainable" parameters of the RandomFourierFeatures keras layer, when using eager execution.

**Describe the expected behavior**
It should be possible to train the "trainable" parameters of the RandomFourierFeatures keras layer, even when using eager execution.

**Standalone code to reproduce the issue**
import tensorflow as tf
from tensorflow_core.python.keras.layers import RandomFourierFeatures

fourier_features = RandomFourierFeatures(
    1,
    kernel_initializer='gaussian',
    scale=1.0,
    trainable=True,
    dtype=tf.float64
)

input = tf.keras.Input(shape=(1,), dtype=tf.float64, name='input')
output = fourier_features(input)
model = tf.keras.Model(inputs=input, outputs=output)
model.compile(loss='mean_squared_error')

model.fit(tf.constant([[1.0]]), tf.constant([[1.0]]), epochs=1)

**Other info / logs**
The call to fit throws the following error:
ValueError: No gradients provided for any variable: ['random_fourier_features/random_features_scale:0'].
1/1 [==============================] - 0s 17ms/sample

**Comment by ravikyram** [comment]
I have tried in colab with TF 2.1.0, 2.2-rc4 and i am able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/9879324436f65e80eda2cc68cdd1eb15/untitled848.ipynb).Thanks!

**Comment by arthurflor23** [comment]
Same here. I only use the `fit()` function, without customization..

In previous versions of TF, my projects ran smoothly, but now I'm getting this "No gradients provided for any variable" message.

**Comment by johnamcleod** [comment]
This appears to have been fixed in the latest nightly build (`2.3.0.dev20200531`).

**Comment by ravikyram** [comment]
@johnamcleod 

I have tried in latest nightly build (`2.3.0-dev20200531`) and i am not seeing any issue. I have changed small update in code by importing  RandomFourierFeatures by (`from tensorflow.python.keras.layers.kernelized import RandomFourierFeatures`).Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/bdf2110e533ab08ae5660620350cdad9/untitled942.ipynb).Please, verify once and close the issue.Thanks!
