### ISSUE TITLE
Feature request for supporting  stateful RNN with tf.distribute.Strategy

### ISSUE THREAD

**Issue by abhinavsp0730** [tensorflow/tensorflow#39098]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
   2.2.0-rc3
- Are you willing to contribute it (Yes/No):
No

**Describe the feature and the current behavior/state.**
 Currently RNNs with stateful=True not yet supported with tf.distribute.Strategy.
 So, my feature request is to make it supported.
**Will this change the current api? How?**
Can't say.

**Who will benefit with this feature?**
Everyone from the community is going to benefit from this because training RNN models takes a lot of time to train. Therefore, we trained our model via TPUs with distributed strategy. For example, in Shakespear's texts generation project, we've to use stateful RNNs. So, if this feature is going to be added then we can train our model via TPUs and with distributive strategy.

**Comment by anj-s** [comment]
@abhinavsp0730 can you give us more details about this FR? Is there a code snippet that should work with tf.distribute?
