### ISSUE TITLE
Keras Custom Layer could not receive `training` parameter

### ISSUE THREAD

**Issue by golden0080** [tensorflow/tensorflow#39093]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes, custom test script. Provided in the description section.

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 16.04

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
Not on mobile

- TensorFlow installed from (source or binary):
binary version from pip: tensorflow==1.14.0

- TensorFlow version (use command below):
`v1.14.0-rc1-22-gaf24dc91b5 1.14.0`

- Python version:
`Python 3.5.6 :: Anaconda, Inc.`

- Bazel version (if compiling from source):
```
Build label: 0.25.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri May 10 20:47:48 2019 (1557521268)
Build timestamp: 1557521268
Build timestamp as int: 1557521268
```

- GCC/Compiler version (if compiling from source):
Not compiled from Source - `gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~16.04~ppa1)`

- CUDA/cuDNN version:
Not using GPU version TF

- GPU model and memory:
Not using GPU version TF

**Describe the current behavior**

Tested with an example script:

```
import tensorflow as tf

import numpy as np
from tensorflow.python.ops import math_ops
from tensorflow.python import keras

class MyLayer(keras.layers.Layer):

    def call(self, inputs, training=None):
        # Expecting training to be set
        if training is not None:
            self.add_loss(math_ops.reduce_sum(inputs))

        return inputs


inputs = keras.Input((3,))
layer = MyLayer()
outputs = layer(inputs)
model = keras.Model(inputs, outputs)
model.compile('sgd', 'mse', run_eagerly=False)
loss = model.fit(np.ones((2, 3)), np.ones((2, 3)))

print(loss.history)
```

**Describe the expected behavior**

The print out loss should not 0, instead it should be "6", since during training, `self.add_loss` would run.

The behavior is more based on tests in tests in TF source code:
https://github.com/tensorflow/tensorflow/blob/v1.14.0/tensorflow/python/keras/engine/base_layer_test.py#L861

And online doc: https://www.tensorflow.org/guide/keras/custom_layers_and_models#privileged_training_argument_in_the_call_method

**Standalone code to reproduce the issue**
Pasted above.

**Other info / logs**
Above script output:

```
$: python3 test_layer.py
WARNING:tensorflow:Entity <bound method MyLayer.call of <__main__.MyLayer object at 0x7faaf7402fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method MyLayer.call of <__main__.MyLayer object at 0x7faaf7402fd0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2020-05-01 17:38:01.840747: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-05-01 17:38:01.863084: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200000000 Hz
2020-05-01 17:38:01.864264: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55efb64ae370 executing computations on platform Host. Devices:
2020-05-01 17:38:01.864288: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2020-05-01 17:38:01.879314: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
2/2 [==============================] - 0s 33ms/sample - loss: 0.0000e+00
{'loss': [0.0]}
```
Loss is "0" as the training branch of code didn't run.
Also, if enabled `eager_execution` in the code, the print out is more reasonable:

```
import tensorflow as tf
tf.enable_eager_execution()

import numpy as np
from tensorflow.python.ops import math_ops
from tensorflow.python import keras

class MyLayer(keras.layers.Layer):

    def call(self, inputs, training=None):
        # Expecting training to be set
        if training is not None:
            self.add_loss(math_ops.reduce_sum(inputs))

        return inputs


inputs = keras.Input((3,))
layer = MyLayer()
outputs = layer(inputs)
model = keras.Model(inputs, outputs)
model.compile('sgd', 'mse', run_eagerly=True)
loss = model.fit(np.ones((2, 3)), np.ones((2, 3)))

print(loss.history)

# Print out is "6" as training branch works.
```

**Comment by Saduf2019** [comment]
@golden0080 
I ran the code shared by you and do not face loss [0.0] as mentioned above, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/740bb42d041a34aefc6e76639fabd9c3/39093.ipynb)
Also is there any particular reason to use tensorflow version 1.14, you may use latest version/later versions and let us know if that helps.

**Comment by golden0080** [comment]
@Saduf2019 Thanks for the gist and I tried to re-run it, somehow got a different output from yours.
https://gist.github.com/golden0080/0087ecd517d03fd12ed4d74f031d21cd

It's somehow different from your notebook outputs, is a bit confused.

**Comment by jvishnuvardhan** [comment]
@golden0080 When using `TF1.x`, I think this is true that training parameter is not passing through `model.fit`. One workaround is to pass training argument like

`outputs = layer(inputs, training = True)
`
Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/b7c298b14c2423bfd1c5d8b8b53b5722/39093.ipynb).

In TF2.x, this training parameter is passed through `model.fit`, so you can run your code as it is and it works well and output `{'loss': [6.0]}`. Please take a look at the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/13981c093b18794f09a8da44b42e58ab/untitled153.ipynb). Can you please upgrade to `TF2.x`. I guess there won't be any updates to `TF1.15.2` unless there is any security related issues. Thanks!

Please close the issue if this was resolved for you. Thanks!

**Comment by golden0080** [comment]
I see your point, passing `training` manually does work. However, this kills the purpose of this parameter to change your model behavior automatically between training and inference.
I imagine that if I used some model that were frozen with layers with `training=True`, they would behave like `training=True` even I'm running them just for inference.

The reason why I want this to work for `1.x` TF is that the use case I'm having is to have a custom kernel that behaves differently when training and inference. It may need more temporary memory for batch size > 1, and not needed so for inference.

Another thing I think is really misleading is that: I ran some of the tests in TF source code, one of them is: https://github.com/tensorflow/tensorflow/blob/v1.14.0/tensorflow/python/keras/engine/base_layer_test.py#L861
I ran this test and it passed. Thought that would work robustly in other contexts.

I guess my updated question is that: what's the difference between this sample code and the tests in TF source code, that makes tests passed.

**Comment by golden0080** [comment]
Another I found after digging the source code a little bit more, is that `tf.python.keras.backend.in_train_phase` can somehow work in the sample code.

Checkout this notebook:
https://colab.research.google.com/gist/golden0080/5b355615735f2dac160979a52f4c523b/39093.ipynb

But my experience is this doesn't work in my real code, which unfortunately I could not show here.
Is there any other API similar to this one that I could use as temporary workaround?

**Comment by golden0080** [comment]
Any updates?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
