### ISSUE TITLE
Problem with tfjs.converters.save_keras_model

### ISSUE THREAD

**Issue by MrXhojn** [tensorflow/tensorflow#39090]
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv2d (Conv2D)              (None, 224, 224, 32)      896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 112, 112, 32)      0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 112, 112, 64)      18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 56, 56, 64)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 56, 56, 64)        36928     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 28, 28, 64)        0         
_________________________________________________________________
flatten (Flatten)            (None, 50176)             0         
_________________________________________________________________
dense (Dense)                (None, 512)               25690624  
_________________________________________________________________
dense_1 (Dense)              (None, 7)                 3591      
=================================================================
Total params: 25,750,535
Trainable params: 25,750,535
Non-trainable params: 0
_________________________________________________________________

This is a summary of the model that I made and trained, it's fairly simple, but when I use tensorflowjs to save it to a folder to be used as a javascript model in a browser, when I try to load the model, the console always returns "Provided weight data has no target variable: conv2d_3/kernel".  As can be seen, there is no conv2d_3 layer in my model, and I have no idea why the converter makes this 4th conv2d layer.  I tried passing false into the strict argument when using tf.loadLayersModel function, but it's like that pass is ignored.
Here's how I wrote the function call:  const net = await tf.loadLayersModel("path to json file", strict=false).  Am I doing it wrong?  I really need this figured out as this is a part of my senior project for my university.  Any help is appreciated, thank you.

**Comment by Saduf2019** [comment]
@MrXhojn 
This issue is not related to Tensorflow can you post this issue in relevant repo TFjs. Thanks

**Comment by MrXhojn** [comment]
Oh, okay
