### ISSUE TITLE
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.   Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by SwapnilMane22** [tensorflow/tensorflow#39092]
- OS Platform: Windows 10 64-bit
- TensorFlow version: 2.0.0
- Python version: 3.7.6
- pip version: 20.1

Installed the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017, and 2019 from
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
and updated using the file: https://aka.ms/vs/16/release/vc_redist.x64.exe 
as mentioned in Step 1 from https://www.tensorflow.org/install/pip#windows_1 

- Using anaconda: 
I installed tensorflow CPU only version from

pip install tensorflow==2.0.0

To test the successful installation I used the following command:
python -c "import tensorflow as tf; x = [[2.]]; print('tensorflow version', tf.__version__); print('hello, {}'.format(tf.matmul(x, x)))"

Output:

(base) C:\Users\chandru>python -c "import tensorflow as tf; x = [[2.]]; print('tensorflow version', tf.__version__); print('hello, {}'.format(tf.matmul(x, x)))"
Traceback (most recent call last):
  File "C:\Users\chandru\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\chandru\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\chandru\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\chandru\anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\chandru\anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\chandru\anaconda3\lib\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "C:\Users\chandru\anaconda3\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\chandru\anaconda3\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\chandru\anaconda3\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\chandru\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\chandru\anaconda3\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\chandru\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\chandru\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\chandru\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\chandru\anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\chandru\anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\chandru\anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

#Please guide me through the installation process. I'm not able to use the TensorFlow backend for Keras model which gives me the above same error.

**Comment by SwapnilMane22** [comment]
> From the template it looks like you are installing **TensorFlow** (TF) prebuilt binaries:
> 
> * For TF-GPU - See point 1
> * For TF-CPU - See point 2
> 
> **1. Installing **TensorFlow-GPU** (TF) prebuilt binaries**
> 
> _TF Version >= 1.13 requires CUDA 10.0 and TF Version < 1.13 (till TF 1.5) requires CUDA 9.0._
> 
> * If you have above configuration and using _**Windows**_ platform -
>   
>   * Try adding the CUDA, CUPTI, and cuDNN installation directories to the %PATH% environment variable.
>   * Refer [windows setup guide](https://www.tensorflow.org/install/gpu#windows_setup).
> * If you have above configuration and using _**Ubuntu/Linux**_ platform -
>   
>   * Try adding the CUDA, CUPTI, and cuDNN installation directories to the $LD_LIBRARY_PATH environment variable.
>   * Refer [linux setup guide](https://www.tensorflow.org/install/gpu#linux_setup).
> * If error still persists then, apparently your CPU model does not support AVX instruction sets.
>   
>   * Refer [hardware requirements](https://www.tensorflow.org/install/pip#hardware-requirements).
> 
> **2. Installing **TensorFlow** (TF) CPU prebuilt binaries**
> 
> _TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets._
> 
> Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.
> Apparently, your CPU model does not support AVX instruction sets. You can still use TensorFlow with the alternatives given below:
> 
> * Try Google Colab to use TensorFlow.
>   
>   * The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true).You get pre-installed latest stable TF version. Also you can use`pip install` to install any other preferred TF version.
>   * It has an added advantage since you can you easily switch to different hardware accelerators (cpu, gpu, tpu) as per the task.
>   * All you need is a good internet connection and you are all set.
> * Try to build TF from sources by changing CPU optimization flags.
> 
> _Please let us know if this helps._



> From the template it looks like you are installing **TensorFlow** (TF) prebuilt binaries:
> 
> * For TF-GPU - See point 1
> * For TF-CPU - See point 2
> 
> **1. Installing **TensorFlow-GPU** (TF) prebuilt binaries**
> 
> _TF Version >= 1.13 requires CUDA 10.0 and TF Version < 1.13 (till TF 1.5) requires CUDA 9.0._
> 
> * If you have above configuration and using _**Windows**_ platform -
>   
>   * Try adding the CUDA, CUPTI, and cuDNN installation directories to the %PATH% environment variable.
>   * Refer [windows setup guide](https://www.tensorflow.org/install/gpu#windows_setup).
> * If you have above configuration and using _**Ubuntu/Linux**_ platform -
>   
>   * Try adding the CUDA, CUPTI, and cuDNN installation directories to the $LD_LIBRARY_PATH environment variable.
>   * Refer [linux setup guide](https://www.tensorflow.org/install/gpu#linux_setup).
> * If error still persists then, apparently your CPU model does not support AVX instruction sets.
>   
>   * Refer [hardware requirements](https://www.tensorflow.org/install/pip#hardware-requirements).
> 
> **2. Installing **TensorFlow** (TF) CPU prebuilt binaries**
> 
> _TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets._
> 
> Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.
> Apparently, your CPU model does not support AVX instruction sets. You can still use TensorFlow with the alternatives given below:
> 
> * Try Google Colab to use TensorFlow.
>   
>   * The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true).You get pre-installed latest stable TF version. Also you can use`pip install` to install any other preferred TF version.
>   * It has an added advantage since you can you easily switch to different hardware accelerators (cpu, gpu, tpu) as per the task.
>   * All you need is a good internet connection and you are all set.
> * Try to build TF from sources by changing CPU optimization flags.
> 
> _Please let us know if this helps._

How do I check whether I have those AVX instructions set or not?
Is there any way that I could install or get those AVX instructions set working on my laptop?

**Comment by SwapnilMane22** [comment]
Edit: I just checked to enable or disable AVX instructions. These commands are:

Enable AVX: bcdedit /set xsavedisable 0

Disable AVX: bcdedit /set xsavedisable 1

and I got the output as follows:

C:\WINDOWS\system32>bcdedit /set xsavedisable 0
The operation completed successfully.

#I re-ran the version testing command i.e.
python -c "import tensorflow as tf; x = [[2.]]; print('tensorflow version', tf.version); print('hello, {}'.format(tf.matmul(x, x)))"
I'm still getting the same first error.

**Comment by ravikyram** [comment]
@SwapnilMane22 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here.](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
.Also, please follow the instructions from to install from [Tensorflow website.](https://www.tensorflow.org/install/source_windows)

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.
Please, refer similar issue #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
Thanks!

**Comment by mihaimaruseac** [comment]
Closing as duplicate.

https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

Just to sample over 100 similar issues: #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204

Please make sure you do a search in the future.

**Comment by KevalSenghani171** [comment]
Step1:  Guys first Download and  Anaconda Navigator
Step2: Create new environment by writing following command:
             conda create -n myenv python=3.6,
             conda activate myenv,
             conda install tensorflow,
             and other required libraries according to the project with pip install.
Step3: install spyder and run your program in that.
