### ISSUE TITLE
Fatal error in TileOps: invalid combination

### ISSUE THREAD

**Issue by bndnn** [tensorflow/tensorflow#391]
I have an RNN I adapted from the PTB example that works fine on CPU.  But when I try to run it on a GPU, it dies with:

F tensorflow/core/kernels/tile_ops.cc:131] TileOp: Invalid combination of Device, DT and NDIM: N5Eigen9GpuDeviceE, float, 0

I'm guessing this is complaining about a 0-dimensional tensor?  What's going on?

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/blob/9c3043ff3bf31a6a81810b4ce9e87ef936f1f529/tensorflow/core/kernels/tile_ops.cc#L383

Looks like it :(

@girving: is there a fix on the way or is this something more fundamental?

**Comment by girving** [comment]
Tile is a nop for scalars, so we just need to copy the input to the output.  Eigen can stay broken. :)

**Comment by girving** [comment]
Fix in review.

**Comment by girving** [comment]
Fixed.  @bndnn: Thank you for reporting!

**Comment by bndnn** [comment]
Thanks for the quick attention!  When can I expect the fix to hit github?  Or I'm happy to pull from googlesource.com if that'll happen faster.

**Comment by vrv** [comment]
We push to github/googlesource at the same time -- I'll try to upstream our commits in a few hours.

**Comment by bndnn** [comment]
Awesome!  Thanks!
