### ISSUE TITLE
Python Keras model in C++

### ISSUE THREAD

**Issue by praetorianer777** [tensorflow/tensorflow#39100]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10 and Ubuntu 18
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): yes
- TensorFlow version (use command below): 2.01
- Python version: 3.7
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**
If I set names in Keras and want to use the trained model in C++ then there seem to be no names for the nodes, so I can't set inputs or get outputs.

**Standalone code to reproduce the issue**
Python Code on the Windows 10 machine:

```
import tensorflow as tf
from tensorflow.keras import layers

model = tf.keras.Sequential()

model.add(layers.Input(2, name='INPUT'))
# Adds a densely-connected layer with 64 units to the model:
model.add(layers.Dense(8, name='layer1', input_shape=(2,), activation='tanh'))
# Add another:
model.add(layers.Dense(4, name='layer2', input_shape=(8,), activation='sigmoid'))
# Add an output layer with 1 output unit:
model.add(layers.Dense(1, name='outputlayer', input_shape=(4,), activation='sigmoid'))

model.compile(optimizer=tf.keras.optimizers.Adam(0.01),
              loss=tf.keras.losses.BinaryCrossentropy(),
              metrics=['accuracy'])
model.summary()

print(model.inputs[0].name)
import numpy as np

data = np.array([
    [0, 0],
    [1, 0],
    [0, 1],
    [1, 1]
])
labels = np.array([
    [0],
    [1],
    [1],
    [0]
])

model.fit(data, labels, epochs=500)
tf.keras.models.save_model(model, 'model')
```
C++ code on the linux machine:

```
tensorflow::Tensor inputs(tensorflow::DT_FLOAT, tensorflow::TensorShape({1, 2}));
auto input_mapped = inputs.tensor<float, 2>();
input_mapped(0, 0) = 0.0;
input_mapped(0, 1) = 1.0;

std::vector<std::pair<std::string, tensorflow::Tensor>> inp = {{"INPUT", inputs}};

std::vector<tensorflow::Tensor> outputs;
std::vector<std::string> output_names({"output"});

status = model.session->Run(inp, output_names, {}, &outputs);

```
What is the problem here? Also if I set names for the layers in Keras, save the model, load it again than the names are replaced with others. And if I use these other names in the C++ application it doesn't work.

Here are the error message:

2020-05-02 13:38:31.256880: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] model_pruner failed: Internal: Could not find node with name 'outputlayer'

Invalid argument: Tensor INPUT:0, specified in either feed_devices or fetch_devices was not found in the Graph

**Comment by jvishnuvardhan** [comment]
@praetorianer777 You can access layer names as below. Except `tf.keras.layers.Input`(which is input to the model), all the Layer names from loaded model are same as from the original model. You can print and check as 

```
for layer,layer_loaded in zip(model.layers,loaded_model.layers):
  print('From Original Model: ', layer.name, ' From loaded_model: ',layer_loaded.name)
```
#output
```
From Original Model:  layer1  From loaded_model:  layer1
From Original Model:  layer2  From loaded_model:  layer2
From Original Model:  outputlayer  From loaded_model:  outputlayer
```
 `model.summary() also shows only these three layers. There is small change in the name of `Input` layer as shown below

```
model.input_names  #['INPUT']

loaded_model.input_names. #['layer1_input']
```

**Comment by praetorianer777** [comment]
Hello, thanks for your reply, but how can I access the input and output in C++?

**Comment by praetorianer777** [comment]
Does anybody has an idea?

**Comment by k-w-w** [comment]
As of now, the Keras model isn't restored when loading into C++. Instead what I think you're loading is the default serving signature -- You should use the [saved_model_cli](https://www.tensorflow.org/guide/saved_model#details_of_the_savedmodel_command_line_interface) to get the input and output names 
```
saved_model_cli show --dir model --all
```
