### ISSUE TITLE
TFLite Interpreter fails to load quantized model on iPhone

### ISSUE THREAD

**Issue by Dmitriy90** [tensorflow/tensorflow#39101]
**Similar issue: https://github.com/tensorflow/tensorflow/issues/28163**

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): stock MobilenetV2
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone 5s
- TensorFlow installed from (source or binary): pip install tensorflow==2.1
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.4
- CUDA/cuDNN version: 10.1
- GPU model and memory: Geforce GTX 1650, 4 GB

**Describe the current behavior**
I have created a new tflite model based on MobilenetV2.
tf.keras.applications.MobileNetV2(input_shape=[SIZE, SIZE, 3], include_top=False)

It works well without quantization using CPU on iOS. I should say that TensorFlow team did a great job, many thanks.

Unfortunately there is a problem with latency.  I have read TF documentation related to optimization (post trainig quantization) and workerd with dynamic range quantization.

I executed the following python code:

```
tflite_models_dir = pathlib.Path("/tmp/mnist_tflite_models/")
tflite_models_dir.mkdir(exist_ok=True, parents=True)
converter = tf.lite.TFLiteConverter.from_saved_model('C:\Work\Python\NN\MobileNet_v2_128')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_quant_model = converter.convert()
tflite_model_quant_file = tflite_models_dir/"MobileNet_v2_128_quant.tflite"
tflite_model_quant_file.write_bytes(tflite_quant_model)
```

After this model was added to XCode project on MAC. Pod file contains the following framework:
_pod 'TensorFlowLite', '~> 1.13.1'_

**Error:**
tflite::InterpreterBuilder return this error: "Didn't find op for builtin opcode 'CONV_2D' version '2'"

**Describe the expected behavior**
I suppose this should work faster without errors.

**Other info / logs** 
I also tried to use float16 quantization.

Python code:
```
converter = tf.lite.TFLiteConverter.from_saved_model('C:\Work\Python\NN\MobileNet_v2_128')
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
tflite_quant_model = converter.convert()
open("MobileNet_v2_128_qua_float16.tflite", "wb").write(tflite_quant_model)
```

In swift code I used MetalDelegate

With _pod 'TensorFlowLiteSwift', '0.0.1-nightly'_
I have no errors, but model doesn’t work

With _pod 'TensorFlowLiteSwift', '2.1.0'_
I have the following error:

2020-05-01 21:36:13.578369+0300 TFL Segmentation[6367:330410] Initialized TensorFlow Lite runtime. 2020-05-01 21:36:20.877393+0300 TFL Segmentation[6367:330397] Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (IOAF code 3)

Is it possible to use MobilenetV2.tflite quantized model in XCode Swift project?

Best regards,
Dmitriy

**Comment by liufengdb** [comment]
Just want to confirm that the workflow works without `converter.optimizations = [tf.lite.Optimize.DEFAULT]?
`

**Comment by jdduke** [comment]
> Is it possible to use MobilenetV2.tflite quantized model in XCode Swift project?

With the 2.1 build, does it work if you run *without* the Metal delegate? Using the CPU? In general, quantized models don't work with GPU (Metal) acceleration.

**Comment by Dmitriy90** [comment]
> > Is it possible to use MobilenetV2.tflite quantized model in XCode Swift project?
> 
> With the 2.1 build, does it work if you run _without_ the Metal delegate? Using the CPU? In general, quantized models don't work with GPU (Metal) acceleration.

Yes. It works well with CPU (without delegate).
But is it possible to use  quantized MobilenetV2 model in XCode for Swift project? Maybe I need to use another approach/library?

**Comment by Dmitriy90** [comment]
> Just want to confirm that the workflow works without `converter.optimizations = [tf.lite.Optimize.DEFAULT]? `

I'm trying to understand... is it possible to to use quantized MobilenetV2 model in XCode for Swift project.

**Comment by jdduke** [comment]
> is it possible to to use quantized MobilenetV2 model in XCode for Swift project?

Yes, this is possible, however, that is independent of the issue with using Metal delegation on a quantized model (which isn't yet supported). But note that you need the latest pod (2.1.0) to use the latest set of quantized operators for your model.

**Comment by Dmitriy90** [comment]
> > is it possible to to use quantized MobilenetV2 model in XCode for Swift project?
> 
> Yes, this is possible, however, that is independent of the issue with using Metal delegation on a quantized model (which isn't yet supported). But note that you need the latest pod (2.1.0) to use the latest set of quantized operators for your model.

Thanks for answer. 
Do you mean pod '**TensorFlowLiteSwift**', '**2.1.0**'?

I tried to use pod 'TensorFlowLiteSwift', '2.1.0' and float16 quantization.

But I have the following error:
2020-05-01 21:36:13.578369+0300 TFL Segmentation[6367:330410] Initialized TensorFlow Lite runtime. 2020-05-01 21:36:20.877393+0300 TFL Segmentation[6367:330397] Execution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (IOAF code 3)

P.S. I will check this again tomorrow...

**Comment by Dmitriy90** [comment]
> > is it possible to to use quantized MobilenetV2 model in XCode for Swift project?
> 
> Yes, this is possible, however, that is independent of the issue with using Metal delegation on a quantized model (which isn't yet supported). But note that you need the latest pod (2.1.0) to use the latest set of quantized operators for your model.

I have changed a code in this example: https://github.com/tensorflow/examples/tree/master/lite/examples/image_segmentation/ios
and used pod 'TensorFlowLiteSwift', '2.1.0'
MobileNetV2 **works well** with quantization and without quantization.

And one more question...
As I understand I cannot use MobilenetV2 with GPU acceleration. Because we can use the following list of model with GPU: https://www.tensorflow.org/lite/performance/gpu#supported_models_and_ops.
Is it correct?

**Comment by jdduke** [comment]
> As I understand I cannot use GPU acceleration with MobilenetV2.tflite .

Are you referring to the quantized version? The floating point version should work, but the quantized version will not. If you're unable to use the GPU with the *floating* point version, that's a bug that we should address.

**Comment by Dmitriy90** [comment]
> > As I understand I cannot use GPU acceleration with MobilenetV2.tflite .
> 
> Are you referring to the quantized version? The floating point version should work, but the quantized version will not. If you're unable to use the GPU with the _floating_ point version, that's a bug that we should address.

Today I tried to use GPU for my model using this example: https://github.com/tensorflow/examples/tree/master/lite/examples/image_segmentation/ios

I have tested stock MobilenetV2.tflite model with pod 'TensorFlowLiteSwift', '2.1.0' and Metal delegate. It works, but _slower then CPU_.  
**CPU**: preprocessing - 114ms, postprocessing - 201ms.
**GPU**: preprocessing - 130ms, postprocessing - 212ms

I thought I can implement float16 quantization to use GPU, but it's not possible with 'TensorFlowLiteSwift', '2.1.0'.
GPU approach work slower than CPU (probably because it's try to convert Float32 to Float16)

So I have only one way to speed up segmentation process. 
1. Use CPU.
2. Implement Quantization aware training.

Is it correct?

**Comment by yyoon** [comment]
@Dmitriy90 I think you should be comparing the `Model Inference` time instead, when using the image_segmentation example.

The pre-/post-processing logic is run outside of the TFLite inference, so whether or not you use the Metal delegate is irrelevant. The difference you were seeing was likely within the typical margin of error.

Could you check again whether the Metal delegate helps shortening the model inference time? Also please make sure that you're [using the release build](https://www.tensorflow.org/lite/performance/gpu#step_5_release_mode) when testing these.

Another interesting point is that you're using the iPhone 5s model, on which we haven't tested our Metal delegate. The difference in hw specs compared to more recent models might also be one of the reasons if you're not seeing enough speed boost with GPU.

**Comment by Dmitriy90** [comment]
Hi @yyoon 
Thanks for answer. I have implemented the following recomendations: https://www.tensorflow.org/lite/performance/gpu#step_5_release_mode

CPU: And it works very fast (40 - 60ms) for different MobileNetV2.tflite versions (input image sizes 128*128, 160*160, 192*192 and 224*224)

GPU: works a bit faster, but for MobileNetV2.tflite with input 128*128.
For 160*160, 192*192 and 224*224 I see the following error: 
"Ececution of the command buffer was aborted due to an error during execution. Caused GPU Hang Error (IOAF code 3)"

Anyway it's fast enough for me. Thanks for help. Tensorflow support team is amaising.
