### ISSUE TITLE
tensorflow build from source c++

### ISSUE THREAD

**Issue by HardworkingPig** [tensorflow/tensorflow#39111]
**System information**
- Windows Platform
- TensorFlow installed from (source or binary): source
- TensorFlow version:1.15
- Python version:3.6
- Installed using virtualenv? pip? conda?:conda
- Bazel version (if compiling from source):2.0.0

Build Toco using bazel run at the end error show up, is this necessary, or it is ok to leave it be?

```ERROR: C:/tensorflow/tensorflow/core/framework/BUILD:591:1: C++ compilation of rule '//tensorflow/core/framework:bfloat16'```

here it is,

```ERROR: C:/tensorflowexpire/tensorflow/core/framework/BUILD:591:1: C++ compilation of rule '//tensorflow/core/framework:bfloat16' failed (Exit 2)
c:\users\acer\_bazel_acer\q66yhmmw\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorBlock.h(1028): error C2061: syntax error: identifier 'Kind'
c:\users\acer\_bazel_acer\q66yhmmw\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorBlock.h(1134): note: see reference to class template instantiation 'Eigen::internal::StridedLinearBufferCopy<Scalar,IndexType>' being compiled
c:\users\acer\_bazel_acer\q66yhmmw\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorBlock.h(1037): error C2061: syntax error: identifier 'Kind'
Target //tensorflow/lite/toco:toco failed to build
INFO: Elapsed time: 1135.067s, Critical Path: 33.35s
INFO: 508 processes: 508 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully```

**Comment by ravikyram** [comment]
@HardworkingPig 

Please, provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by mihaimaruseac** [comment]
Please post full error message, not only the first line
