### ISSUE TITLE
Can't run Tensorflow-Lite in NDK

### ISSUE THREAD

**Issue by orangesomethingorange** [tensorflow/tensorflow#39118]
**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- Mobile device: Samsung Galaxy S10
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2
- Python version: 3.5.2
- Bazel version (if compiling from source): 3.0.0
- GCC/Compiler version (if compiling from source): 5.4.0

**Describe the problem**

I can build TFLite from binaries but I think it's not building correctly, or maybe only partially.
I can include the AAR / SO files into Android Studio, but I can't seem to use TFLite successfully in the NDK.

This should be a very basic task - I just want to run a simple inference in Android's NDK.
What am I missing here?
I tried to follow the basic examples from https://www.tensorflow.org/ or this repository's c++ examples, but the TFLite library does not seems to respond.

More information available at the StackOverflow post:
https://stackoverflow.com/questions/61523713/how-to-run-tensorflow-lite-in-android-studio-ndk

**Comment by orangesomethingorange** [comment]
After failing to build the library as a shared / static one, I also tried to build the files straight from the IDE - see [more info in my post](https://github.com/tensorflow/tensorflow/issues/39148#issuecomment-628489924).

Building fails with memory issues from toolchain / compiler.
It's possible that build system is missing some configurations - but the closest to successful build for `arm64-v8a` is done in Tensorflow's Docker container (from [here](https://www.tensorflow.org/lite/guide/build_arm64#cross-compile_for_arm64)) but the container uses a script, and not a configurable build system.

How can the TFLite library used in Android Studio's NDK environment - if not via static library?

**Comment by daverim** [comment]
Hi orangesomethingorange@.

If I understand this correctly, you want some ndk code that links to the aar file?

From what I understand this is a bit tricky:  https://stackoverflow.com/questions/51930836/android-ndk-build-cmake-include-so-library-included-in-aar-library.

This may be a solution for you. If not, I suggest exploding the aar manually and adding a dependency on the shared object in your CMakeLists.txt (shared_library) or Android.mk (using PREBUILT_SHARED_LIBRARY).

I would, however, suggest that you will probably not get much performance benefit from this: the overhead of jni is probably not your bottleneck. I would take a look at possible optimizations such as quantization or pruning to reduce the model parameters.

**Comment by orangesomethingorange** [comment]
> Hi orangesomethingorange@.
> 
> If I understand this correctly, you want some ndk code that links to the aar file?
> 
> From what I understand this is a bit tricky: https://stackoverflow.com/questions/51930836/android-ndk-build-cmake-include-so-library-included-in-aar-library.
> 
> This may be a solution for you. If not, I suggest exploding the aar manually and adding a dependency on the shared object in your CMakeLists.txt (shared_library) or Android.mk (using PREBUILT_SHARED_LIBRARY).
> 
> I would, however, suggest that you will probably not get much performance benefit from this: the overhead of jni is probably not your bottleneck. I would take a look at possible optimizations such as quantization or pruning to reduce the model parameters.

Hey @daverim,

Could you please elaborate on optimizations?
Do you think that NDK code won't reduce running times substantially?

The link you sent is all about extracting an `.so` from an `.aar`. That's not the issue for me :)
I already have both a shared library (`.so`) file and a static library (`.a`) file for the library I wish to include, which I'm adding in my Android Studio project's `CMakeLists.txt` file.

The problem is - when I include the library file, I get errors like so:
`ninja: error: '/full/path/to/the/library/i/want/to/include/libtoinclude.so', needed by '.../app/build/intermediates/cmake/debug/obj/arm64-v8a/libnative-lib.so', missing and no known rule to make it`
(when `libnative-lib.so` being the c++ library compiled from the NDK code).

Any ideas / suggestions?

**Comment by jdduke** [comment]
> Do you think that NDK code won't reduce running times substantially?

That's right, inference times between Java and C++ should generally be comparable, as long as you avoid using multi-dimensional arrays on the Java side for things like image inputs/outputs. The Java API is just a lightweight wrapper around the C++ API.

**Comment by orangesomethingorange** [comment]
> > Do you think that NDK code won't reduce running times substantially?
> 
> That's right, inference times between Java and C++ should generally be comparable, as long as you avoid using multi-dimensional arrays on the Java side for things like image inputs/outputs. The Java API is just a lightweight wrapper around the C++ API.

I actually do have an image I'm trying to give as an input to the inference.
The output is also an image.
Currently the input image is loaded as a bitmap, and converted to an image-buffer before the inference.

How can I avoid using multi-dimensional arrays on Android's Java side?
What other options are there for image processing?

**Comment by jdduke** [comment]
You can use a FloatBuffer or ByteBuffer of the appropriate size to provide your input data and extract output data. Most (maybe all?) of our examples use this approach. You can also use some of the helper utilities from the [support library](https://www.tensorflow.org/lite/guide/android) to do this, e.g., with our [image classification example](https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/android/app/src/main/java/org/tensorflow/lite/examples/classification/tflite/Classifier.java#L248).

**Comment by orangesomethingorange** [comment]
> You can use a FloatBuffer or ByteBuffer of the appropriate size to provide your input data and extract output data. Most (maybe all?) of our examples use this approach. You can also use some of the helper utilities from the [support library](https://www.tensorflow.org/lite/guide/android) to do this, e.g., with our [image classification example](https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/android/app/src/main/java/org/tensorflow/lite/examples/classification/tflite/Classifier.java#L248).

I didn't mention it's a high definition image, my bad.
It results in memory issues, and it's not related to this issue, but yes - I actually am using ByteBuffer, thanks.

**Comment by orangesomethingorange** [comment]
@jdduke maybe this would better explain the issue:

I created an Android project from scratch and tried to build the C / C++ source files.

### steps to recreate:

1. created an Android Studio Native C++ project
2. created basic C/C++ source files and headers directory structure in `app/src/main/cpp` and put the (A) **tensorflow**, (B) **absl** and (C) **flatbuffers** files there, so now it looks like this:
```
|-- CMakeLists.txt
|-- absl
|   |-- base
|   |   |-- attributes.h
|   |   |-- config.h
|   |   |-- internal
|   |   |   |-- identity.h
|   |   |   |-- inline_variable.h
|   |   |   `-- invoke.h
|   |   |-- macros.h
|   |   |-- optimization.h
|   |   |-- options.h
|   |   |-- policy_checks.h
|   |   `-- port.h
|   |-- memory
|   |   `-- memory.h
|   |-- meta
|   |   `-- type_traits.h
|   |-- types
|   |   |-- bad_optional_access.h
|   |   |-- internal
|   |   |   `-- optional.h
|   |   `-- optional.h
|   `-- utility
|       `-- utility.h
|-- flatbuffers
|   |-- base.h
|   |-- flatbuffers.h
|   `-- stl_emulation.h
|-- native-lib.cpp
|-- native-lib.h
`-- tensorflow
    |-- core
    |   `-- public
    |       `-- version.h
    `-- lite
        |-- allocation.h
        |-- c
        |   |-- c_api.cc
        |   |-- c_api.h
        |   |-- c_api_internal.h
        |   `-- common.h
        |-- core
        |   |-- api
        |   |   |-- error_reporter.h
        |   |   |-- op_resolver.h
        |   |   `-- profiler.h
        |   |-- macros.h
        |   `-- subgraph.h
        |-- delegates
        |   `-- nnapi
        |       `-- nnapi_delegate.h
        |-- error_reporter.h
        |-- experimental
        |   `-- resource
        |       `-- resource_base.h
        |-- external_cpu_backend_context.h
        |-- interpreter.h
        |-- interpreter_builder.h
        |-- kernels
        |   `-- register.h
        |-- memory_planner.h
        |-- model.h
        |-- model_builder.h
        |-- mutable_op_resolver.h
        |-- nnapi
        |   |-- NeuralNetworksTypes.h
        |   `-- nnapi_implementation.h
        |-- schema
        |   `-- schema_generated.h
        |-- stderr_reporter.h
        |-- string_type.h
        |-- type_to_tflitetype.h
        |-- util.h
        `-- version.h
```
with `native-lib` (**native-lib.cpp** / **native-lib.h**) being the compiled library and `CMakeLists.txt` being the **cmake** configuration file - which is left unchanged since it's "the only library".
3. All / most of tensorflow's header files include some `#include "tensorflow/...` lines, which couldn't be found by the compiler. So I changed all `#include "tensorflow/...` lines to either (A) relative paths or to (B) `#include "/tensorflow/...` paths (note the addition of a slash character, before "tensorflow/...").
4. In the app's build.gradle I added a no-compression line for the `.tflite` file:
```
aaptOptions {
        noCompress "tflite"
    }
```
and I control the build target via the `ndk` **abiFilters** option.
5. I added an assets directory to the app
6. In `native-lib.cpp` I add [some example code from the TFLite website](https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_c) to use:
```
    char filename [] = "../assets/my_model.tflite";

    // Load the model
    std::unique_ptr<tflite::FlatBufferModel> model =
            tflite::FlatBufferModel::BuildFromFile(filename);

    // Build the interpreter
    tflite::ops::builtin::BuiltinOpResolver resolver;
    std::unique_ptr<tflite::Interpreter> interpreter;
    tflite::InterpreterBuilder(*model, resolver)(&interpreter);

    // Resize input tensors, if desired.
    interpreter->AllocateTensors();

    float* input = interpreter->typed_input_tensor<float>(0);
    // Fill `input`.

    interpreter->Invoke();

    float* output = interpreter->typed_output_tensor<float>(0);
```
7. Tried to build the library, source files included

### errors

1. Build target is **x86_64**:
`/path/to/Android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/memory:2339: **error**: undefined reference to 'tflite::impl::Interpreter::~Interpreter()'
`
memory, line 2339 is the "`delete __ptr;`" line:
```
_LIBCPP_INLINE_VISIBILITY void operator()(_Tp* __ptr) const _NOEXCEPT {
    static_assert(sizeof(_Tp) > 0,
                  "default_delete can not delete incomplete type");
    static_assert(!is_void<_Tp>::value,
                  "default_delete can not delete incomplete type");
    delete __ptr;
  }
```
2. Build target is **arm64-v8a**:
many errors of the following structure: 
```
...
native-lib.cpp:32: undefined reference to `tflite::DefaultErrorReporter()'
native-lib.cpp:32: undefined reference to `tflite::FlatBufferModel::BuildFromFile(char const*, tflite::ErrorReporter*)'
...
native-lib.cpp:40: undefined reference to `tflite::impl::Interpreter::AllocateTensors()'
native-lib.cpp:45: undefined reference to `tflite::impl::Interpreter::Invoke()'
...
```
and the last one, again, being:
`memory:2339: undefined reference to `tflite::impl::Interpreter::~Interpreter()'`

### additional info

The build line:
```
/path/to/app/build/intermediates/cmake/debug/obj/arm64-v8a/libnative-lib.so 
: && /path/to/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android29 --gcc-toolchain=/path/to/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/path/to/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libnative-lib.so -o /path/to/app/build/intermediates/cmake/debug/obj/arm64-v8a/libnative-lib.so CMakeFiles/native-lib.dir/native-lib.cpp.o  /path/to/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/29/liblog.so -latomic -lm
```

See anything that might cause this **clang "memory"** issue?

**Comment by jdduke** [comment]
> with native-lib (native-lib.cpp / native-lib.h) being the compiled library

Can you talk more about this? What exactly do you mean that this is the compiled library? Which library exactly? And how was it generated?

Note that we've had some internal discussions over the past week, and are planning to prioritize adding native CMake support in Q3 for TFLite. This should simplify native integration into non-bazel toolchains.

**Comment by orangesomethingorange** [comment]
> > with native-lib (native-lib.cpp / native-lib.h) being the compiled library
> 
> Can you talk more about this? What exactly do you mean that this is the compiled library? Which library exactly? And how was it generated?
> 
> Note that we've had some internal discussions over the past week, and are planning to prioritize adding native CMake support in Q3 for TFLite. This should simplify native integration into non-bazel toolchains.

These are great news :)
Non-bazel toolchains integration would be excellent.
Also - I couldn't get Bazel to build TFL for arm64-v8a either, I was only able to build a static (.a) library for x86_64.

Regarding your question:
`native-lib.cpp` and `native-lib.h` are the C++ source file and header file, respectively, that I wrote to execute my program. They're compiled by Android Studio's build system (gradle) via the NDK extension (using `cmake`), and referred as `native-lib`. This is standard in Android Studio, and configured by default when creating a Native Project in Android Studio.
So what I was trying to do is to get gradle (Android Studio's build system) to build two libraries: (1) `native-lib` (my code) and (2) `tensorflow-lite` - and have my code in `native-lib` call the `tensorflow-lite` functions.
In the last trial depicted above, the `native-lib.cpp` did not have any special functionality - I was only trying to call the Tensorflow-Lite functions, to see that I can use TFL in native code.

**Comment by orangesomethingorange** [comment]
Just for reference:

1. What I'm trying to do is to run a Tensorflow-Lite inference, from Android Studio's NDK.
2. The reason I was trying to build the `tensorflow-lite` library myself, was because it failed to be compiled from a static / shared library (for `arm64-v8a`)
3. Before trying to build and compile the code with gradle, I also tried using Android Studio's Bazel plugin to build the TFL library, with no apparent success.
4. Using a shared library is preferred, but I couldn't build an `.so` for `arm64-v8a`, or failed to have it successfully compiled / linked into the project.

**Comment by orangesomethingorange** [comment]
@jdduke I tried running TFL in NDK using the C-API via [these instructions](https://www.tensorflow.org/lite/guide/android#use_tflite_c_api) and [version 2.2](https://bintray.com/google/tensorflow/download_file?file_path=org%2Ftensorflow%2Ftensorflow-lite%2F2.2.0%2Ftensorflow-lite-2.2.0.aar) seems to work ok :)
**I assume I have you to thank for - so thanks**!

I still can't see any result from the inference but I just assume it's my bad somehow... regarding this issue specifically, I think that TFL is currently running in NDK, so I'll close it.

I still want to run the C++ API ([this](https://github.com/tensorflow/tensorflow/issues/39148) issue) and also check out GPU configuration capabilities of TFL, but I'll just open another issue for that.

**Comment by jdduke** [comment]
> @jdduke I tried running TFL in NDK using the C-API via these instructions and version 2.2 seems to work ok :)

Great news! Thanks for the feedback.

> I still want to run the C++ API (this issue) and also check out GPU configuration capabilities of TFL, but I'll just open another issue for that.

Sounds good. Our CMake work this quarter should hopefully make it much easier to build from source directly from within Android Studio.
