### ISSUE TITLE
cannot download micro speech pre-trained model 

### ISSUE THREAD

**Issue by idog-ceva** [tensorflow/tensorflow#39113]
@tensorflow/micro

**System information**
windows 10 enterprise 
firefox 75.0

**Describe the problem**
when trying to download micro speech pre-trained model an xml with the following error is received:

`Anonymous caller does not have storage.objects.get access to download.tensorflow.org/models/tflite/micro/speech_commands_2020_04_13.zip`

**Please provide the exact sequence of commands/steps when you ran into the problem**
1. open readme.md: [https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/micro_speech/train#trained-models](url)
2. click the download link: [https://storage.googleapis.com/download.tensorflow.org/models/tflite/micro/speech_commands_2020_04_13.zip](url)
3. get following error:
![image](https://user-images.githubusercontent.com/61374608/80912183-db500080-8d43-11ea-9710-386a7c45f179.png)

**Comment by amahendrakar** [comment]
@idog-ceva,
I was able to download the `speech_commands.zip` file without any issues from the [README.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/micro_speech/train/README.md) page.

The link you have provided is 
https://storage.googleapis.com/download.tensorflow.org/models/tflite/micro/speech_commands_2020_04_13.zip

whereas the link to the zip file is
https://storage.googleapis.com/download.tensorflow.org/models/tflite/micro/micro_speech_2020_04_13.zip

Could you please check this and let us know if it works? Thanks!

**Comment by idog-ceva** [comment]
@amahendrakar
updated link works, thanks.
