### ISSUE TITLE
 Installation broken - Tensorflow 2.1 Cuda 10.1 Ubuntu 18.04

### ISSUE THREAD

**Issue by jchwenger** [tensorflow/tensorflow#39116]
Hi,

I'm struggling with the same issue as [here](https://github.com/tensorflow/tensorflow/issues/36121) when trying to install TF 2.1 with Cuda 10.1. I followed the [instructions](https://www.tensorflow.org/install/gpu) for Ubuntu 18.04 twice on two different machines, worked like a charm a few weeks ago, and now on this one I get stuck as described above when trying to install `cuda-10-1` (the other libraries can be installed, and `nvidia-smi` shows the gpus):
```
$ sudo apt-get install cuda-10-1
The following packages have unmet dependencies:
 cuda-10-1 : Depends: cuda-runtime-10-1 (>= 10.1.243) but it is not going to be installed
             Depends: cuda-demo-suite-10-1 (>= 10.1.243) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
When trying to install deps:
```
$ sudo apt-get install cuda-runtime-10-1
The following packages have unmet dependencies:
 cuda-runtime-10-1 : Depends: cuda-drivers (>= 418.87) but 410.0-0~dummy18.04 is to be installed
E: Unable to correct problems, you have held broken packages.
```
Finally:
```
$ sudo apt-get install cuda-drivers
cuda-drivers is already the newest version (410.0-0~dummy18.04).
```
I read the other thread but I'm not sure how @igorhoogerwoord  managed to go beyond this. I'd also avoid installing `tf-nightly` for now as @HardRockDude did if I can...

Thanks in advance for any help!

**Comment by amahendrakar** [comment]
@jchwenger,
Could you please check [this comment](https://askubuntu.com/a/598616) from a similar issue and let us know if it works. Thanks!

**Comment by jchwenger** [comment]
Hi,
Thanks for this! 
Well, as mentioned in my post I could not install `cuda-runtime-10-1`. After much tinkering (I'm afraid it's hard for me to recall all steps now, mostly purging everything and installing again many times over, sometimes trying to install the dependencies manually), I managed to get it working.

I *think* what made a difference in the end was a full upgrade.
```
sudo apt -y full-upgrade
```
After that the steps indicated on the official [page](https://www.tensorflow.org/install/gpu#ubuntu_1804_cuda_101) lead me to the same state as the other machines: things seem to work now with TF 2.1, as well as previous ones like 1.14 in another conda env, except for Tensor RT, I'll post another question now if I don't find an answer.

**Comment by amahendrakar** [comment]
@jchwenger,
Is this still an issue? Please feel free to close the issue if resolved. Thanks!

**Comment by jchwenger** [comment]
My apologies, yes all done, thank you!
