### ISSUE TITLE
TensorFlow Lite C++ API setup

### ISSUE THREAD

**Issue by pranv12** [tensorflow/tensorflow#39120]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Ubuntu 20.04
- TensorFlow installed from (source or binary): installed from binary. (also have cloned using git clone)
- TensorFlow version: 2.1.0
- Python version: 3.7.6
- Installed using virtualenv? pip? conda?: conda

I want to setup TensorFlow Lite (TFLite) for C++ development. I searched google for it but didn't find anything. Tensorflow have posted regarding C++ development([documentation](https://www.tensorflow.org/lite/api_docs/cc)) but there's nothing about installation instruction. As of May 3, 2020 it seems to be in experimental mode. Though tensorflow has developed few [models](https://www.tensorflow.org/lite/models) out of it and build Android/iOS apps from it. I want to try those models on my own in C++. But here's a problem, to access header files required for C++  there is no direct support in tensorflow pip installation. This githubRepo of tensorflow need to be cloned which contains header files. Even after that to access some third-party header files that repository needs to be build. And I don't know how to build it. It'd be helpful if anyone working on TFLite C++ API shares how it can be done?

I want to include following header file to my C++ code. 
`#include "tensorflow/lite/model.h"`
But I got error as `cannot open source file "flatbuffers/flatbuffers.h"`. I searched complete repository but there isn't anything as `flatbuffers.h`. But I found a folder **flatbuffers** which contains some build files. I think if I can build those files I will be able to load header files I need. But I don't know how to build them.

Note : Just to be clear I want tensorflow lite C++ installation not tensorflow C api

Thank you.

**Comment by Saduf2019** [comment]
@pranv12 
please refer to these links and let us know if it helps:
[link1](https://developer.ridgerun.com/wiki/index.php?title=R2Inference/Supported_backends/TensorFlow-Lite)
[link2](https://github.com/tensorflow/tensorflow/issues/23896)

**Comment by pranv12** [comment]
@Saduf2019  
Thank you! References you provided are very helpful. 

I also found a [sample project](https://github.com/infil00p/tf_world).

Closing this issue for now.
