### ISSUE TITLE
mlir graph optimization is not built into tf-nightly

### ISSUE THREAD

**Issue by yongtang** [tensorflow/tensorflow#39135]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: tf-nightly
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**

Commit 248bc00 (@ezhulenev ) enables MLIR graph optimizations. However, it looks like this is not built as part of the tf-nightly. As a result, even though the following two methods are available:
```
tf.config.experimental.enable_mlir_graph_optimization
tf.config.experimental.disable_mlir_graph_optimization
```

There is no effect by toggle on/off the above two commands with tf-nightly installed.

From the commit, if the commit is carried in tf-nightly, then with 
```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '0'

import tensorflow as tf
...
...
```

we should see something like below (base on the code in commit 248bc00):

```
  if (!config_proto.experimental().enable_mlir_graph_optimization()) {
    VLOG(1) << "Skipping MLIR Graph Optimization Pass"
            << ", session flag not enabled";
    return Status::OK();
  }
```

But the logs does not show the above contents.

Is there any way (e.g., pass certain build options) so that the generated pip wheel could carry the MLIR graph optimizations?

**Comment by mihaimaruseac** [comment]
@jpienaar @joker-eph can you please take a look and help triage?

**Comment by joker-eph** [comment]
@ezhulenev do you know why your optimization isn't available here? Can you look into this?

**Comment by ezhulenev** [comment]
I don't know of any special handling of pass registration in the OSS TF.

Does this static registration invoked at start time: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/tensorflow/transforms/graph_optimization_pass_registration.cc#L25 ?

This registration forwarded to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/mlir_graph_optimization_pass.h, and then registered with a runtime here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/mlir_graph_optimization_pass_registration.cc#L24-L28

For now it is only registered for TF function, so if you run TF V1 graph with sessions, it will not be invoked.

For V1 you need to add `MlirV1CompatOptimizationPassRegistration` for this pass, but that's probably not going to work by default, because V1 graphs (graphs with sessions) contains control flow constructs that are not supported by MLIR importer.

**Comment by jpienaar** [comment]
Couple of different parts here (sessions vs graphs vs functions) that confuse things, so let's start simpler. MLIR importer does support V1 control flow constructs but majority of optimizations and focus is on V2 control flow.

But I didn't see V1 references until this point, is this a V1 model? Also I haven't tried the nightly build.

@ezhulenev is there an integration test of the feature that you added so that we could verify here with a bazel test command?

**Comment by ezhulenev** [comment]
No, only mlir-unit-tests for layout optimization.

And a simple python example to test it, but the end state is not observable from python, so it can't be easily converted to end-to-end test.

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf

from absl import app
from absl import flags

import numpy as np

FLAGS = flags.FLAGS

from google3.third_party.tensorflow.python.framework import config


def main(_):
  # Disable layout optimizer to not change input data_format.
  config.set_optimizer_experimental_options({'layout_optimizer': False})

  # Enable MLIR Graph Optimizations
  config.enable_mlir_graph_optimization()

  input_dims = [1, 9, 9, 4]
  filter_dims = [3, 3, 4, 8]
  input_t = np.random.rand(*input_dims).astype('f')
  filter_t = np.random.rand(*filter_dims).astype('f')

  @tf.function
  def fun(input, filter):
    input_tensor = np.random.rand(*input_dims) * 5
    x = tf.nn.convolution(
        input,
        filter,
        padding = "VALID",
        data_format='NHWC',
    )

    return x

  x = fun(input_t, filter_t)
  print(x)


if __name__ == '__main__':
  app.run(main)
```

**Comment by yongtang** [comment]
For `tf-nightly`, the above example may need to make small modifications to change  `from google3.third_party.tensorflow.python.framework import config`.  Below is the modified one that runs on Colab:
```python3
!pip install tf-nightly

import tensorflow as tf
import numpy as np

# Disable layout optimizer to not change input data_format.
tf.config.optimizer.set_experimental_options({'layout_optimizer': False})

# Enable MLIR Graph Optimizations
tf.config.experimental.enable_mlir_graph_optimization()

input_dims = [1, 9, 9, 4]
filter_dims = [3, 3, 4, 8]
input_t = np.random.rand(*input_dims).astype('f')
filter_t = np.random.rand(*filter_dims).astype('f')

@tf.function
def fun(input, filter):
  input_tensor = np.random.rand(*input_dims) * 5
  x = tf.nn.convolution(
      input,
      filter,
      padding = "VALID",
      data_format='NHWC',
  )

  return x

x = fun(input_t, filter_t)
print(x)

```

**Comment by yongtang** [comment]
I checked the bazel build file in `tensorflow/BUILD`, and think the issue is that
```
//tensorflow/compiler/mlir:mlir_graph_optimization_pass_registration
```

needs to be added to the target `//tensorflow:tensorflow_framework`, as otherwise the mlir optimization will not be included in `libtensorflow_framework.so.2` that is packaged into `tf-nightly`.

However, if I directly add `//tensorflow/compiler/mlir:mlir_graph_optimization_pass_registration` to 
`//tensorflow:tensorflow_framework` then a 
```
Non-OK-status: RegisterAlreadyLocked(deferred_[i]) status: Already exists: 
```
error will show up.

Think the issue is caused by inclusion of some components multiple times in bazel rules.

**Comment by yongtang** [comment]
I have created a PR #39231 to add MLIR graph optimizations registration to be part of the libtensorflow_framework.so, so that it could be packaged to tf-nightly pip install.

It didn't make code change, though it made several changes in bazel to remove the dependency of multiple copies, and also splits `import_model.[h|cc]` into 3 parts (no true code change):

- new `import_base.[h|cc]` consists of ImporterBase class and common shared functions (by `import_model.[h|cc]` and `import_graphdef.[h|cc]`
- new `import_graphdef.[h|cc]` consists of graph only conversion to mlir
- the `import_model.[h|cc]` has also been updated to consist model only conversion to mlir

The reason for the above change is that model imports depends on some library in core and it pulled in xla and core ops multiple times.

With the change, MLIR graph optimizations registration only need `export_graphdef.cc` and `import_graphdef.cc`, and the multiple copies of xla and core ops are avoided.

Please take a look at PR #39231  and let me know if there are any issues.
