### ISSUE TITLE
module 'tensorflow' has no attribute 'keras'

### ISSUE THREAD

**Issue by samra-irshad** [tensorflow/tensorflow#39139]
Specifications:

win10 os
python 3.6
tensorflow 2.1.0

While loading the trained model, I used:
tf.keras.models.load_model

But it resulted in error, 
AttributeError: module 'tensorflow' has no attribute 'keras'

**Comment by Saduf2019** [comment]
@samra-irshad 

Can you please try "pip install -U tensorflow" and follow [this link](https://stackoverflow.com/questions/51724309/attributeerror-module-tensorflow-has-no-attribute-name-scope-with-keras) for reference

[link](https://github.com/tensorflow/tensorflow/issues/16614#issuecomment-488962620)
[link1](https://github.com/tensorflow/tensorflow/issues/16614#issuecomment-361858036)
[link2](https://github.com/tensorflow/tensorflow/issues/28213)
[link3](https://github.com/tensorflow/tensorflow/issues/33215)

**Comment by samra-irshad** [comment]
I cannot uninstall/install packages myself. I am using a certain HPC facility and they have it installed already. I just load it to run my script

**Comment by Saduf2019** [comment]
@samra-irshad
Is this still an issue

**Comment by diaazg** [comment]
I faced same problem and I create new env with different python version and it work. Make sure to use compatible python version with tensorflow
