### ISSUE TITLE
Dataset.unbatch() sets cardinality to -2 even when batch size is known

### ISSUE THREAD

**Issue by min050820** [tensorflow/tensorflow#39136]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64 (1909)
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de410 2.1.0
- Python version: 3.7.7
- CUDA/cuDNN version: Using CPU
- GPU model and memory: Using CPU

**Describe the current behavior**
Doing `Dataset.unbatch()` on dataset with known batch size resets cardinality to -2 (unknown).

**Describe the expected behavior**
When batch size of dataset is known, it should set cardinality to `batch_size * cardinality`.

**Standalone code to reproduce the issue**
```
import tensorflow as tf
ds = tf.data.Dataset.range(10) # shape=()
ds = ds.batch(2, drop_remainder=True) # shape=(2,)
print(tf.data.experimental.cardinality(ds)) # 5
ds = ds.unbatch() # shape=()
print(tf.data.experimental.cardinality(ds)) # Should be 10, but is -2 (unknown)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
Although cardinality is currently experimental, it is used when traning keras model.

**Comment by yongtang** [comment]
Added a PR #39137 for the fix.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/caaefad7a4ba4579d410e203fa20057c/39136-tf-nightly.ipynb), [TF v2.2.0-rc4](https://colab.research.google.com/gist/amahendrakar/b2ef86f09489bdad388f089ab3ba315b/39136-2-2.ipynb#scrollTo=52pV0lOQX93A) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/b01f15c8b4e12c9e879f62eca2fb8395/39136-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by jsimsa** [comment]
@aaudiber please review the PR from Yong.
