### ISSUE TITLE
pip Install Error: don't could find version that satisfies the requirement tensorflow

### ISSUE THREAD

**Issue by an-white** [tensorflow/tensorflow#39130]
hi, I have win10 and I have tried install through cmd tensorflow with:
pip install tensorflow
pip install tensorflow-cpu
pip3 install --upgrade tensorflow
 
All these pip gave me the same error:

![image](https://user-images.githubusercontent.com/63893710/80923804-cbd8b380-8d53-11ea-8b1f-af41f380daab.png)

what's happened? What I need do to fix it?

**Comment by vikingspy** [comment]
I have a possibly related issue:  when I use 
`pip install tensorflow`
pip installs the most recent release candidate: https://pypi.org/project/tensorflow/2.2.0rc4/
I'm trying to get the most recent stable version, 2.1.0.

When I try:
`pip install tensorflow==2.1.0`

I get the error message: 
```
ERROR: Could not find a version that satisfies the requirement tensorflow==2.1.0 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4)
ERROR: No matching distribution found for tensorflow==2.1.0
```
I updated pip to 20.1.  Same behavior.
I tried:
`pip install tensorflow>=2.0.0`
And still got ver 2.2.0rc4

Why is pip installing only the rc's?

![image](https://user-images.githubusercontent.com/5289393/80924776-c8d3c800-8d3f-11ea-923e-690abed11e28.png)

**Comment by vikingspy** [comment]
Okay, I think I figured out my issue:  I was using Python 3.8 in my environment. I made a new environment using Python 3.7, and the install worked fine.

**Comment by amahendrakar** [comment]
@an-white,
TensorFlow 2 packages require a pip version >19.0. Could you please upgrade pip using the below command and let us know if it works.

`pip install --upgrade pip`.

For more information please check [this TensorFlow guide](https://www.tensorflow.org/install#download-a-package). Thanks!

**Comment by an-white** [comment]
hi, I forgot say that I have python 3.8, this can affect?, when I have already upgrade pip, this occurs:

![image](https://user-images.githubusercontent.com/63893710/81001657-1458a580-8e16-11ea-99a5-babdb9eca323.png)

**Comment by vikingspy** [comment]
@an-white :  I suggest creating a new env with python 3.7 and try installing TF2 there.

**Comment by patrickbard** [comment]
> Okay, I think I figured out my issue: I was using Python 3.8 in my environment. I made a new environment using Python 3.7, and the install worked fine.

I saw this recommendation on other forums and tried it, but it didn't work for me.

**Comment by patrickbard** [comment]
> > Okay, I think I figured out my issue: I was using Python 3.8 in my environment. I made a new environment using Python 3.7, and the install worked fine.
> 
> I saw this recommendation on other forums and tried it, but it didn't work for me.
> 
> I've tried on 3.7.0 and 3.6.4

As I expected the problem was my fault... but I think is something that can pass unnoticed and explaining it here may help people with a similar setup and issue.

I'm using Python via [pyenv-win](https://github.com/pyenv-win/pyenv-win) which is great, but the thing is that I didn't realize that `pyenv install X.Y.Z` will install the 32bit version and tensorflow **requires 64bit**. So, in my case, it was just a matter of installing an actual 64bit version with pyenv install X.Y.Z-amd64

**Comment by amahendrakar** [comment]
> hi, I forgot say that I have python 3.8, this can affect? When I have already upgrade pip, this occurs:

@an-white,
TensorFlow v2.1 is not compatible with Python 3.8. Instead, could you please try installing TF v2.2.0rc4 using the below command 

`pip install tensorflow==2.2.0rc4`

Thanks!

**Comment by amahendrakar** [comment]
@an-white,
Also, could you please check if you are using the 64 bit version of Python. TensorFlow is tested and supported only on 64-bit systems. Thanks!

**Comment by an-white** [comment]
Ok, thanks I'm going to check all this recommendation and find if works

**Comment by an-white** [comment]
Ready thank you so much, the problem was the version that I have of python 32 bit, and already I install the 64 bit version and only need wait for this finish

![image](https://user-images.githubusercontent.com/63893710/81077241-b500a100-8eba-11ea-9e04-b8594e359657.png)
 
Now only need wait, any other problem I'll tell you

**Comment by kartik1300** [comment]
thanks  i

**Comment by biswajit310** [comment]
hi..
I am using python 3.8.
wants to:       pip install tensorflow==1.31.1
but getting error.
![Capture](https://user-images.githubusercontent.com/48278850/84350175-7acfa100-abd6-11ea-94ff-9b686f8e7893.PNG)

**Comment by amahendrakar** [comment]
> hi..
> I am using python 3.8.
> wants to: pip install tensorflow==1.31.1
> but getting error.

@biswajit310,
TensorFlow 1.13 is not actively supported. Please try installing TensorFlow 2.x. If you need any help please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose), so that we can track the issue there. Thanks!

**Comment by aminou014** [comment]
verify that you have python 64bits , it solved my problem , i'm using python3.8 win10 64bits
