### ISSUE TITLE
Empty profile overview page in Tensorboard

### ISSUE THREAD

**Issue by pbruneau** [tensorflow/tensorflow#39143]
**System information**
- Stock Tensorflow example
- Linux Ubuntu 18.04
- TensorFlow installed from: binary
- TensorFlow version (tf-nightly-gpu): v1.12.1-28892-g90dd57bb43 2.2.0-dev20200405
- Python version: 3.6.9
- CUDA/cuDNN version: 10.1/7.6.5
- GPU model and memory: GTX 1080 8G

**Describe the current behavior**
I have been running the tutorial as given at https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras. I have installed the exact same TF version as used in the tutorial, the matching nightly Tensorboard version (2.3.0a20200405), and latest tensorboard_plugin_profile. 

The profile page displays correctly, but I'm getting only zeroes, and empty graph 
![image](https://user-images.githubusercontent.com/4252621/80950251-ca5fc780-8df5-11ea-8028-18438b4fced2.png)

Down the "Performance summary" panel, I'm also getting the message: "WARNING: No step markers observed and hence the step time is actually unknown. This may happen if your profiling duration is shorter than the step time. In that case, you may try to profile longer."

**Describe the expected behavior**
When opening Tensorboard, I was expecting non-zero numbers in the "Performance Summary" and "Step-time Graph" panels as shown in the figure from the tutorial (https://github.com/tensorflow/tensorboard/blob/master/docs/images/profiler_overview_page_bad_ip.png?raw=1). 

**Standalone code to reproduce the issue**
The mentioned tutorial as-is.

**Comment by alvarobasi** [comment]
I'm experiencing exactly the same error under the same circumstances. I've also followed the same tutorial.

System information

Stock Tensorflow example
Windows 10
TensorFlow installed from: pip
TensorFlow version (tf-nightly-gpu): v1.12.1-28892-g90dd57bb43 2.2.0-dev20200405
Python version: 3.6.9
CUDA/cuDNN version: 10.1/7.6.5
GPU model and memory: RTX 2080 8G

**Comment by amahendrakar** [comment]
@pbruneau,
I was able to run the code without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/7b40a39a0b3b3b59d4d54e86585f7b88/39143.ipynb).

Also, could you please check if you are using nightly builds of TensorFlow and TensorBoard and have run the uninstall cell twice, to uninstall both the 1.15.0 and 2.1.0 version of TensorFlow and TensorBoard. Thanks!

**Comment by lancechao** [comment]
I got the same problem. No number in overview_page with "WARNING: No step markers observed and hence the step time is actually unknown. This may happen if your profiling duration is shorter than the step time. In that case, you may try to profile longer." However, there is some number in the page tensorflow_stats.

System information

Ubuntu 18.04
Docker : tensorflow/tensorflow   2.2.0rc0-gpu-py3-jupyter
TensorFlow version: tensorflow-gpu             2.2.0rc0
TensorBoard version: tensorboard                2.2.0
CUDA/cuDNN version: 10.2/7.6.5
GPU model and memory:GTX 1080Ti 11g

**Comment by pbruneau** [comment]
@amahendrakar I just double-checked:
- I installed the latest tf-nightly, tb-nightly and tensorboard_plugin_profile as expected
- This is a fresh install (docker container), so I guess the prior uninstalls are pointless (?)
- I ran the same code otherwise
- Still the same result (i.e. all zeroes) on my side

On my machine steps are much shorter (7ms on average) - but this should not be an obstacle?
Also, the notebook does not tell about the underlying config - in particular, can you tell the Python, CUDA and CuDNN versions you have behind the scenes, plz?

**Comment by amahendrakar** [comment]
@pbruneau,
Thank you for the update. Below are the configuration details for the Colab gist
- Python v3.6.9
- CUDA Version 10.1.243
- CUDNN_MAJOR 7
  CUDNN_MINOR 6
  CUDNN_PATCHLEVEL 5

**Comment by pbruneau** [comment]
@amahendrakar OK so it seems we have same Python, CUDA and CuDNN versions... I'm really baffled by this problem :/ According to the other answers, it seems that I'm not an isolated case BTW.

To be perfectly accurate about my execution context:
- I put the code from the notebook in a .py file, and run it with `python3 file.py`
- The only difference in my code regards logs paths (so that my subsequent call to tensorboard in the CLI is easier), i.e. my `model.fit` goes like:
        
        tboard_callback = tf.keras.callbacks.TensorBoard(log_dir = "./logs", 
            histogram_freq = 1, 
            profile_batch = '500,520')

        model.fit(ds_train, 
            epochs=2, 
            validation_data=ds_test, 
            callbacks = [tboard_callback])
        
- After I ran `file.py`, I launch `tensorboard --logdir "./logs" --bind_all`. I use `--bind_all` as I view tensorboard on a different machine from the one hosting the server.

- I access tensorboard using Chrome on the client machine - Tensorboard opens fine (i.e. I get the display below - loads correctly, but with "erroneous zeroes").
![image](https://user-images.githubusercontent.com/4252621/81175352-b35ed800-8fa3-11ea-8ecf-4639f2d912bf.png)

Is it possible for you to try outside colab (e.g. regular Python3 CLI), to check and see it works similarly, please? I know there shouldn't be a difference, but at this stage I don't have another explanation...

**Comment by antonipelka** [comment]
Hi, I've also encountered similar problem, but had notice some errors in the terminal.
I'm running nightly docker image with GPU support (tensorflow/tensorflow:nightly-gpu-py3-jupyter).
The errors were as follows:
```
2020-05-06 22:12:04.575505: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1372] Profiler found 1 GPUs
2020-05-06 22:12:04.576324: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcupti.so.10.1
2020-05-06 22:12:04.677122: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1419] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI_ERROR_INSUFFICIENT_PRIVILEGES
2020-05-06 22:12:04.678646: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1458] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI_ERROR_INSUFFICIENT_PRIVILEGES
2020-05-06 22:12:04.681355: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1441] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI_ERROR_INVALID_PARAMETER
2020-05-06 22:12:06.055379: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-05-06 22:12:06.214657: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-05-06 22:12:16.711500: I tensorflow/core/profiler/lib/profiler_session.cc:145] Profiler session started.
2020-05-06 22:12:16.711571: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1419] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI_ERROR_NOT_INITIALIZED
2020-05-06 22:12:16.711590: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1458] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI_ERROR_NOT_INITIALIZED
2020-05-06 22:12:27.126307: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1441] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI_ERROR_INVALID_PARAMETER
2020-05-06 22:12:27.131846: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:217]  GpuTracer has collected 0 callback api events and 0 activity events.
```

I've solved my problem thanks to this issue: #35860 [(solution)](https://github.com/tensorflow/tensorflow/issues/35860#issuecomment-586558743)

In my case the problem was I've been running the Docker container with a non-root user and in an unprivileged mode. After switching back to the root user (default, no `--user`, no `--group-add`) and adding `--privileged` option the issue has gone.
Check if it is also your case!

**Comment by lancechao** [comment]
> I got the same problem. No number in overview_page with "WARNING: No step markers observed and hence the step time is actually unknown. This may happen if your profiling duration is shorter than the step time. In that case, you may try to profile longer." However, there is some number in the page tensorflow_stats.
> 
> System information
> 
> Ubuntu 18.04
> Docker : tensorflow/tensorflow 2.2.0rc0-gpu-py3-jupyter
> TensorFlow version: tensorflow-gpu 2.2.0rc0
> TensorBoard version: tensorboard 2.2.0
> CUDA/cuDNN version: 10.2/7.6.5
> GPU model and memory:GTX 1080Ti 11g

I resolved the problem thanks to this issue too. https://github.com/tensorflow/tensorflow/issues/35860#issuecomment-586558743

In my case is using docker run option '--privileged=true'.

**Comment by pbruneau** [comment]
@antonipelka This is so solving my problem, thanks! It works now :)

I should have inspected the `model.fit` logs, I actually had 2 problems:
- My `LD_LIBRARY_PATH` was not right (fixed according to https://github.com/tensorflow/tensorflow/issues/35860#issuecomment-583858751)
- I also had to run my container with the `privileged=true` option (see https://github.com/tensorflow/tensorflow/issues/35860#issuecomment-586558743)
