### ISSUE TITLE
Can't get nbextensions to work using Tensorflow docker gpu image

### ISSUE THREAD

**Issue by wee-analyze** [tensorflow/tensorflow#39140]
**Describe the problem**
I am using a Jupyter gpu docker image on Ubuntu 18.04 LTS and I can't get nbextensions to work. I made a Dockerfile adding the nbextensions and I see them available on my screen but when I enable them nothing happens on my Jupyter Notebook. This would made my productivity if I could get these nbextensions to work. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary):
- TensorFlow version: 2.1
- Python version: 3.6
- Installed using virtualenv? pip? conda?: Tensorflow Docker image
- GPU model and memory: 1080Ti

Here is the Docker file that I build my image
```
FROM tensorflow/tensorflow:2.1.0-gpu-py3-jupyter

RUN pip install --upgrade pip
RUN pip install jupyter_contrib_nbextensions
RUN jupyter contrib nbextension install --system
RUN pip install pandas 
RUN pip install matplotlib
RUN pip install scikit-learn
RUN pip install opencv-python 
```

Then I build it 
`docker build -t tf21 .`

Then run it 
`sudo docker run -u $(id -u):$(id -g) --gpus all --rm -it -p 8888:8888 -v $(pwd):/tf/notebook tf21`

From here I open the jupyter in a browser and click on the Nbextensions tab and uncheck 
`disable configuration for nbextensions without explicit compatibility (they may break your notebook environment, but can be useful to show for nbextension development)` 
Then I start checking the extensions I would like to use.

When I open my notebook, none of my selections work.

I'm not sure if this helps but this is what outputs on my terminal when I click on the extensions I want.

```
[E 07:15:56.931 NotebookApp] 500 PATCH /api/config/notebook (172.17.0.1) 1.44ms referer=http://127.0.0.1:8888/tree/notebooks
[E 07:15:57.742 NotebookApp] Uncaught exception PATCH /api/config/notebook (172.17.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='PATCH', uri='/api/config/notebook', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 3174, in wrapper
        return method(self, *args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/notebook/services/config/handlers.py", line 29, in patch
        section = self.config_manager.update(section_name, new_data)
      File "/usr/local/lib/python3.6/dist-packages/notebook/services/config/manager.py", line 34, in update
        return self.write_config_manager.update(section_name, new_data)
      File "/usr/local/lib/python3.6/dist-packages/notebook/config_manager.py", line 132, in update
        self.set(section_name, data)
      File "/usr/local/lib/python3.6/dist-packages/notebook/config_manager.py", line 109, in set
        self.ensure_config_dir_exists()
      File "/usr/local/lib/python3.6/dist-packages/notebook/config_manager.py", line 66, in ensure_config_dir_exists
        os.makedirs(self.config_dir, 0o755)
      File "/usr/lib/python3.6/os.py", line 210, in makedirs
        makedirs(head, mode, exist_ok)
      File "/usr/lib/python3.6/os.py", line 220, in makedirs
        mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: '/.jupyter'
[W 07:15:57.742 NotebookApp] Unhandled error
[E 07:15:57.742 NotebookApp] {
      "Host": "127.0.0.1:8888",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "X-Xsrftoken": "2|92e82d6a|8f936aeda218e6eed7af91384caf3a27|1588574338",
      "X-Requested-With": "XMLHttpRequest",
      "Content-Length": "51",
      "Origin": "http://127.0.0.1:8888",
      "Dnt": "1",
      "Connection": "keep-alive",
      "Referer": "http://127.0.0.1:8888/tree/notebooks",
      "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1588575705|23:username-127-0-0-1-8888|44:MTJkNzE1ZmJhZWJlNDQzZjlhZmI2ZTM5MDIxMjFjMGE=|a976c227287b6c47a53e2e8460d1df1e8da047bb0ad73f418665f60dcf55fe7f\"; _xsrf=2|92e82d6a|8f936aeda218e6eed7af91384caf3a27|1588574338"
    }
```

Does anybody know how I can get this to work? I think it has something to do with the `/.jupyter` Permission denied.

By the way, you guys are doing an awesome job! TF2 is so much easier to use than before.

**Comment by mihaimaruseac** [comment]
It seems the user you are running the docker container with (internal user) is not allowed to write to the root of the container. Maybe try a different directory / different user / grant permissions?

**Comment by wee-analyze** [comment]
Ah yes, when I took away the -u from the run it was able to write to the root of the container and work as expected.

`sudo docker run --gpus all --rm -it -p 8888:8888 -v $(pwd):/tf/notebook tf21`

Thanks!
