### ISSUE TITLE
segmentation fault (core dumped) error while running vis.py in Deeplab 

### ISSUE THREAD

**Issue by IsaacPatole** [tensorflow/tensorflow#39141]
I have trained a Deeplab model and saved checkpoints, now I am trying to run the vis.py script by the following command :

python vis.py --checkpoint_dir /home/ubuntu/Documents/tensorflow/models/research/deeplab/datasets/PQR/exp/train_on_trainval_set/train/ --log_dir /home/ubuntu/Documents/tensorflow/models/research/deeplab/datasets/PQR/exp/train_on_trainval_set/log/ --dataset_dir /home/ubuntu/Documents/tensorflow/models/research/deeplab/datasets/POR/exp/train_on_trainval_set/test_dataset/

**Comment by ravikyram** [comment]
@IsaacPatole 

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by IsaacPatole** [comment]
@ravikyram thanks for the quick response, sorry this issue didnt belong here, I got confused between one another repo of tensorflow API. Have a great day
