### ISSUE TITLE
Unbundling sqlite doesn't work with TF_SYSTEM_LIBS

### ISSUE THREAD

**Issue by npanpaliya** [tensorflow/tensorflow#39154]
Unable to use sqlite using TF_SYSTEM_LIBS

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux RHEL 7.7 ppc64le
- TensorFlow installed from (source or binary): Source 
- TensorFlow version: 2.2.0-rc4 tag
- Python version: 3.6/3.7
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): 7.2
- CUDA/cuDNN version: 10.2/7.6.5

**Describe the problem**
I'm facing an error while using TF_SYSTEM_LIBS=org_sqlite in my environment. I have correctly set PREFIX, INCLUDEDIR and LIBDIR to point to the installed location of sqlite with proper suffixes include and lib to PREFIX. In third_party/systemlibs/sqlite.BUILD, I've also created a genrule to create the symlinks of sqlite's headers which works correctly but somehow my TF's build still fails for not able to find libsqlite.so. For this I've also explicitly set LD_LIBRARY_PATH to point to the location of libsqlite.so. Another attempt was to add --linkopt in the bazel build command but still no luck. Kindly provide some thoughts on this.

Also, I believe setting PREFIX, INCLUDEDIR and LIBDIR variables should suffice for TF to locate the headers and libraries for any external dependency, instead of creating symlinks to them or setting any additional variables like LD_LIBRARY_PATH.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Build flags
```
build --action_env TF_SYSTEM_LIBS="org_sqlite"
build:linux --define=PREFIX="$SYSTEM_LIBS_PREFIX"
build:linux --define=LIBDIR="$SYSTEM_LIBS_PREFIX/lib"
build:linux --define=INCLUDEDIR="$SYSTEM_LIBS_PREFIX/include"
build --action_env LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$SYSTEM_LIBS_PREFIX/lib"
``` 
where SYSTEM_LIBS_PREFIX is the path where sqlite is installed in my environment.

Bazel build command - 
```
bazel --bazelrc=$SRC_DIR/tensorflow/tensorflow.bazelrc build \
    --config=opt \
    --config=numa \
    --curses=no \
    --linkopt="-L${SQLITE_LIB}" \
    //tensorflow/tools/pip_package:build_pip_package
```

BUILD file changes for sqlite in thirdparty/systemlibs/sqlite.BUILD
```
--- a/third_party/systemlibs/sqlite.BUILD
+++ b/third_party/systemlibs/sqlite.BUILD
@@ -1,12 +1,31 @@
 licenses(["unencumbered"])  # Public Domain

+HEADERS = [
+   "sqlite3.h",
+   "sqlite3ext.h",
+]
+
 # Production build of SQLite library that's baked into TensorFlow.
 cc_library(
     name = "org_sqlite",
+    hdrs = HEADERS,
+    includes = ["."],
     linkopts = ["-lsqlite3"],
     visibility = ["//visibility:public"],
 )

+genrule(
+    name = "link_headers",
+    outs = HEADERS,
+    message = "Printing value of $$(INCLUDEDIR)",
+    cmd = """
+      for i in $(OUTS); do
+        i=$${i##*/}
+        ln -sf $(INCLUDEDIR)/$$i $(@D)/$$i
+      done
+    """,
+)
```
**Any other info / logs**
```
[[ERROR: [/tmp/tmpTfBuild/work/tensorflow/python/BUILD:5796:1: Linking of rule '//tensorflow/python:_pywrap_tensorflow_internal.so' failed (Exit 1)
/tmp/tmpTfBuild/_build_env/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/7.2.0/../../../../powerpc64le-conda_cos7-linux-gnu/bin/ld: cannot find -lsqlite3
Target //tensorflow/tools/pip_package:build_pip_package failed to build
[ERROR: [/tmp/tmpTfBuild/work/tensorflow/tools/pip_package/BUILD:62:1 Linking of rule '//tensorflow/python:_pywrap_tensorflow_internal.so' failed (Exit 1)
```

**Comment by npanpaliya** [comment]
@perfinion - Any thoughts on this?

**Comment by Saduf2019** [comment]
@npanpaliya 
Is this still an issue

**Comment by npanpaliya** [comment]
@Saduf2019 - No, I've it fixed now.

**Comment by Saduf2019** [comment]
moving this to closed status with confirmation
