### ISSUE TITLE
Issue in google codelabs handwritten digit classifier code.

### ISSUE THREAD

**Issue by PatrickPrakash** [tensorflow/tensorflow#39160]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

https://codelabs.developers.google.com/codelabs/digit-classifier-tflite/index.html?index=..%2F..index#7

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/MyMethod

### Clear description

There is an error in the code of step 4 of the codelabs.
get a null safety error when implementing the code

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example?

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by ravikyram** [comment]
@PatrickPrakash 

It was moved out of tensorflow GitHub repository to a new repository on GitHub. Link to the new repository is [here.](https://github.com/googlecodelabs/tools/issues) Please file an issue there so that it will be resolved faster. You could also raise a PR to update the docs in that repository. Thanks!

**Comment by PatrickPrakash** [comment]
There was a line of code needed to be added on the project. The Google Colab didn't mention in there steps. Anyway the final code is in the finish project of the repository.
Issue Solved
