### ISSUE TITLE
ImportError: No module named utils using google colab

### ISSUE THREAD

**Issue by theman162** [tensorflow/tensorflow#39175]
Hi i am using google colab to run object_detection_tutorial.ipynb from https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10.I am using tensorflow cpu and anaconda prompt.I have added the utils module to path in anaconda prompt 
set PYTHONPATH=C:\tensorflow2\models;C:\tensorflow2\models\research;C:\tensorflow2\models\research\slim;C:\tensorflow2\models\research\object_detection\utils.Yet this issue is still continues

ImportErrorTraceback (most recent call last)
<ipython-input-3-aa270cd948af> in <module>()
----> 1 from utils import label_map_util
      2 
      3 from utils import visualization_utils as vis_util

ImportError: No module named utils

**Comment by Saduf2019** [comment]
@theman162 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. 
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by theman162** [comment]
*System information**
- OS Platform and Distribution :windows 10

- TensorFlow version:1.5
- Python version:python 3.7
- Installed using virtualenv? pip? conda?:pip

- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: using tensorflow cpu
- GPU model and memory:using tensorflow cpu

**Comment by theman162** [comment]
![image](https://user-images.githubusercontent.com/57122013/81046638-691a2000-8eeb-11ea-9921-9d7b867b5e10.png)

**Comment by Saduf2019** [comment]
@theman162 
Is there any particular reason for using the old version of tensor flow can you please upgrade to latest version and let us know if the problem exist. [ Please try 1.15 or 2.1 ]

**Comment by theman162** [comment]
I am running the object detection from this github commit which uses tensorflow 1.5 .he is not that responsive which is why i am asking solution for this issue https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10

**Comment by theman162** [comment]
i would like to know if i can  use tensorflow 1.9

**Comment by Saduf2019** [comment]
@theman162 
Can you please try in later versions of tensorflow as mentioned and let us know if you face any issues.

**Comment by ymodak** [comment]
duplicate https://github.com/tensorflow/models/issues/5852
refer https://github.com/tensorflow/models/issues/5852#issuecomment-443805036

**Comment by Saduf2019** [comment]
@theman162
Please confirm if we may move this to closed status

**Comment by AnxietyVendor** [comment]
https://stackoverflow.com/questions/57257530/importerror-no-module-named-in-colab-google
ref to this answer got me solved
utils will be found after explicitly changing dir
