### ISSUE TITLE
C API Release

### ISSUE THREAD

**Issue by eaplatanios** [tensorflow/tensorflow#39174]
Not sure if this is the right place to ask this, but I was wondering why the C API precompiled binaries have not been released for TF 2.x yet. Are you planning to release them soon? And I also have the same question for the java proto library.

cc @alextp

**Comment by alextp** [comment]
@gunan do you know what happened to libtensorflow_framework.so?

**Comment by eaplatanios** [comment]
fyi, I also tried using the nightly share libraries (v2.1 for mac but only v2.0 for linux for some reason) and I run into an issue because the mac libraries are not code-signed and so cannot be loaded in MacOS 15 (Catalina).

**Comment by gunan** [comment]
@alextp libtensorflow_framework.so is a part of the pip package, but I think here the users are asking for libtensorflow.so release.

The issue is, their maintainers have left the team, or google, and noone picked those up.
@av8ramit and @bmzhao will take a look at them before 2.3 release.

**Comment by eaplatanios** [comment]
I'm mainly asking about the shared libraries that were distributed independent of the pip package. But yes, it'd be great if they're picked up again. I'm relying on them for TF Scala, which I'm kind of resurrecting. :)

**Comment by av8ramit** [comment]
Yes we are taking a look at restarting those releases. Hopefully we will have them by the 2.3 release.

**Comment by eaplatanios** [comment]
That's great! Thanks @av8ramit!

**Comment by nonoesp** [comment]
Seems like `libtensorflow_framework.so.2` ships with `2.0.0` (inside of `tensorflow_core`) and the size of TensorFlow is dramatically smaller than with versions `2.1.x` and 2.2.x` (now shipped as `tensorflow` and not `tensorflow_core`).

This makes a bundle of TensorFlow with its Python dependencies the following sizes (when building against the `amazonlinux:latest` image).

| TensorFlow version | Original size | Stripped size | Compressed size |
| :-: | :-: | :-: | :-: |
| 2.1.1 | 493M | 350M | 97M |
| 2.1.1 | 1.5G | 1.3G | 433M |
| 2.2.0 | 1.7G | 1.5G | 515M |
| nightly | 1.8G | 1.6G | 524M |

_*Stripped sizes are calculated after doing `xargs strip` to `.so` files and removing unnecessary `pip`, `pip-`, `wheel`, and `wheel-` folders from the Python packages.

In my case, this increase in size makes it impossible to deploy the model (say, in AWS Lambda, which limits the zipped size to around 256M).

**Comment by nonoesp** [comment]
Somehow `libtensorflow` seems to be available via Homebrew for Linux and macOS for `2.2.0`.

https://formulae.brew.sh/formula-linux/libtensorflow

**Comment by ymodak** [comment]
You can find Libtensorflow packages on tf website now
https://www.tensorflow.org/install/lang_c#download
