### ISSUE TITLE
Something wrong with "predict_on_batch"

### ISSUE THREAD

**Issue by i7p9h9** [tensorflow/tensorflow#39178]
<em>
Performance with predict_on_batch when using not determined input size is not good enough on tf.2.2.0. In my experiments with TensorFlow version 2.1 the prediction speed is for flexible input the same as fixed input, but for tf.2.2 prediction, speed is dramatically lower. Moreover, about 10 days ago, when I used nightly build the performance was good.
</em>

**System information**
- OS Platform: Linux Ubuntu 20.04
- TensorFlow installed from: pip
- TensorFlow version: 2.2 nightly. v1.12.1-31119-gce72f093cb 2.2.0-dev20200504
- Python version: 3.6
- CUDA/cuDNN version: 10.1/7.6.5
- GPU model and memory: GTX1080 TI, 11Gb

**Describe the current behavior**
**for v2.1.0-rc2-17-ge5bf8de 2.1.0**

- **_Fixed input_**

```
from tensorflow.keras.applications.resnet50 import ResNet50
from tqdm import tqdm
import numpy as np


net = ResNet50(input_shape=(None, 224, 3), weights=None, include_top=False)
for n in tqdm(range(1000)):
    a = net.predict_on_batch(np.random.randn(1, 224, 224, 3))

output:
100%|██████████| 1000/1000 [00:13<00:00, 74.74it/s]
```

- **_Flexible input_**

```
from tensorflow.keras.applications.resnet50 import ResNet50
from tqdm import tqdm
import numpy as np

net = ResNet50(input_shape=(None, 224, 3), weights=None, include_top=False)
for n in tqdm(range(1000)):
    a = net.predict_on_batch(np.random.randn(1, np.random.randint(112, 224), 224, 3))
    
output:
100%|██████████| 1000/1000 [00:14<00:00, 68.15it/s] 
```

**for tf.2.2 nightly build (v1.12.1-31119-gce72f093cb 2.2.0-dev20200504)**

- **_Fixed input_**

```
from tensorflow.keras.applications.resnet50 import ResNet50
from tqdm import tqdm
import numpy as np

net = ResNet50(input_shape=(None, 224, 3), weights=None, include_top=False)
for n in tqdm(range(1000)):
    a = net.predict_on_batch(np.random.randn(1, 224, 224, 3))
    
output:
100%|██████████| 1000/1000 [00:26<00:00, 38.24it/s]
```

- **_Flexible input_**

```
from tensorflow.keras.applications.resnet50 import ResNet50
from tqdm import tqdm
import numpy as np

net = ResNet50(input_shape=(None, 224, 3), weights=None, include_top=False)
for n in tqdm(range(1000)):
    a = net.predict_on_batch(np.random.randn(1, np.random.randint(112, 224), 224, 3))

output:
  1%|          | 6/1000 [00:47<2:07:54,  7.72s/it]
```

upd:
for current stable version: v2.2.0-rc1-34-ge6e5d6df2a 2.2.0-rc2 
result is same:

- **_Flexible input_**

```
from tensorflow.keras.applications.resnet50 import ResNet50
from tqdm import tqdm
import numpy as np

net = ResNet50(input_shape=(None, 224, 3), weights=None, include_top=False)
for n in tqdm(range(1000)):
    a = net.predict_on_batch(np.random.randn(1, np.random.randint(112, 224), 224, 3))

output:
  0%|          | 4/1000 [00:31<2:12:39,  7.99s/it]
```

**Comment by Saduf2019** [comment]
@
I ran the code shared, please find the [gist for 2.1](https://colab.sandbox.google.com/gist/Saduf2019/340f4bbe70afbcaf60f6969fcf452a3b/2.ipynb) and for [nightly](https://colab.sandbox.google.com/gist/Saduf2019/e98c3ee313bb1429a5ccd5ec9aa0023d/untitled163.ipynb).
Please confirm if this replicates your issue.

**Comment by i7p9h9** [comment]
> @
> I ran the code shared, please find the [gist for 2.1](https://colab.sandbox.google.com/gist/Saduf2019/340f4bbe70afbcaf60f6969fcf452a3b/2.ipynb) and for [nightly](https://colab.sandbox.google.com/gist/Saduf2019/e98c3ee313bb1429a5ccd5ec9aa0023d/untitled163.ipynb).
> Please confirm if this replicates your issue.

Yes, I have similar behavior.

**Comment by i7p9h9** [comment]
@Saduf2019 FYI the same problem with "predict_generator" method.

**Comment by ymodak** [comment]
Thanks for the issue. This is fixed with tf-nightly   version 
See attached [gist](https://colab.research.google.com/gist/ymodak/838fdc95c837eb247a421fc1781ec5bb/untitled163.ipynb). Thanks!
