### ISSUE TITLE
Failed to find bogomips on s390x architecture

### ISSUE THREAD

**Issue by rposts** [tensorflow/tensorflow#39185]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): s390x Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):  v2.2.0-rc4-0-g70087ab4f4 2.2.0-rc4
- Python version: Python 3.6.9
- Bazel version (if compiling from source): Build label: 2.0.0- (@non-git)
- GCC/Compiler version (if compiling from source): gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
When running test cases on s390x architecture following Warning message is logged:

`W tensorflow/core/platform/profile_utils/cpu_utils.cc:106] Failed to find bogomips or clock in /proc/cpuinfo; cannot determine CPU frequency`

**Describe the expected behavior**
CPU frequency on s390x architecture should be correctly detected.

**Standalone code to reproduce the issue**
Run the following test case:
```
root@3cefe6d659f6:/home/tensorflow# python tensorflow/python/data/experimental/kernel_tests/optimization/shuffle_and_repeat_fusion_test.py
Running tests under Python 3.6.9: /usr/bin/python
[ RUN      ] ShuffleAndRepeatFusionTest.testShuffleAndRepeatFusion
2020-05-05 13:11:16.071244: W tensorflow/core/platform/profile_utils/cpu_utils.cc:106] Failed to find bogomips or clock in /proc/cpuinfo; cannot determine CPU frequency
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

It seems like `tensorflow/core/platform/profile_utils/cpu_utils.cc`  is not parsing `bogomips` line correctly on s390x: 
```
root@3cefe6d659f6:/home# cat /proc/cpuinfo | grep bogomips
bogomips per cpu: 3033.00
```
This patch should fix it:
```
diff --git a/tensorflow/core/platform/profile_utils/cpu_utils.cc b/tensorflow/core/platform/profile_utils/cpu_utils.cc
index 587c97875a..b22123a804 100644
--- a/tensorflow/core/platform/profile_utils/cpu_utils.cc
+++ b/tensorflow/core/platform/profile_utils/cpu_utils.cc
@@ -88,6 +88,8 @@ static ICpuUtilsHelper* cpu_utils_helper_instance_ = nullptr;
      defined(__ppc__) && (__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__))
     retval = sscanf(line.c_str(), "clock              : %lfMHz", &cpu_freq);
     freq_factor = 1.0;
+#elif defined(__s390x__)
+    retval = sscanf(line.c_str(), "bogomips per cpu: %lf", &cpu_freq);
 #else
     retval = sscanf(line.c_str(), "bogomips : %lf", &cpu_freq);
 #endif
```

**Comment by penpornk** [comment]
@rposts Thank you very much for reporting the issue and suggesting the fix! 
1. Would you like to open a PR to fix this? I can review it quickly. (Please mention me in the PR so I can see it right away.)
2. Or I can make the change now and mention your username in the commit log, but your name might not appear in the contributors list in the release note (see the end of the [2.2.0-rc4 release note](https://github.com/tensorflow/tensorflow/releases/tag/v2.2.0-rc4) for example). (I think the list is auto-generated from commit authors.) 

Let me know which way you prefer.

**Comment by rposts** [comment]
Sure - I can PR. I will get the process started on my end. Thanks.

**Comment by rposts** [comment]
Closing - Fixed in https://github.com/tensorflow/tensorflow/pull/39311
