### ISSUE TITLE
tf.data.experimental.make_csv_dataset modifies mutable variables passed to it

### ISSUE THREAD

**Issue by grofte** [tensorflow/tensorflow#39186]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- TensorFlow installed from (source or binary): docker
- TensorFlow version (use command below): TF 2.1.0

**Describe the current behavior**

tf.data.experimental.make_csv_dataset modifies passed variables in place. So if you call
`tf.data.experimental.make_csv_dataset(file_pattern, batch_size, select_columns=columns_to_use)`
the variable `columns_to_use` is changed. It's in line 463 https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/python/data/experimental/ops/readers.py#L463 but it may happen to other variables passed. Specifically the list sent to `select_columns=` is replaced by a list of the indices of those columns in the file to read.

**Describe the expected behavior**

A function should never modify the mutable objects passed to it. This is only ever appropriate for methods of a class.

**Comment by Saduf2019** [comment]
@grofte 
Please provide with simple stand alone code for us to replicate the issue faced.

**Comment by grofte** [comment]
```python
import tensorflow as tf
import pandas as pd

df = pd.DataFrame({'a': [2, 3, 5], 'b': [3, 4, 6], 'c': [4, 5, 7]})
df.to_csv('tf.csv', index=False)
columns_to_use = ['b', 'c']
print(columns_to_use)
ds = tf.data.experimental.make_csv_dataset('tf.csv', batch_size=1, select_columns=columns_to_use)
print(columns_to_use)
```

**Comment by Saduf2019** [comment]
I am able to replicate this issue please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/e52ece5e44c25385b36a7e6288063ece/untitled166.ipynb)

**Comment by jsimsa** [comment]
@rachellim could you please take a look? thanks

**Comment by rachellim** [comment]
thanks for catching this @grofte ! fix incoming.
