### ISSUE TITLE
Error while reading resource variable _AnonymousVar46 from Container: localhost.

### ISSUE THREAD

**Issue by EkaterinaAntipova** [tensorflow/tensorflow#39198]
I have this code: (all variables are initialized)
`def train(models, X_train, noise_plot, dir_result="D:\gan\result", epochs=10000, batch_size=100):
        combined, discriminator, generator = models
        nlatent_dim = noise_plot.shape[1]
        half_batch  = int(batch_size / 2)
        history = []
        for epoch in range(epochs):

            # ---------------------
            #  Train Discriminator
            # ---------------------

            # Select a random half batch of images
            idx = np.random.randint(0, X_train.shape[0], half_batch)
            imgs = X_train[idx]
            noise = get_noise(half_batch, nlatent_dim)

            # Generate a half batch of new images
            gen_imgs = generator.predict(noise)

            
            # Train the discriminator q: better to mix them together?
            d_loss_real = discriminator.train_on_batch(imgs, np.ones((half_batch, 1)))
            d_loss_fake = discriminator.train_on_batch(gen_imgs, np.zeros((half_batch, 1)))
            d_loss = 0.5 * np.add(d_loss_real, d_loss_fake)

            # ---------------------
            #  Train Generator
            # ---------------------

            noise = get_noise(batch_size, nlatent_dim)

            # The generator wants the discriminator to label the generated samples
            # as valid (ones)
            valid_y = (np.array([1] * batch_size)).reshape(batch_size,1)
            
            # Train the generator
            g_loss = combined.train_on_batch(noise, valid_y)

            history.append({"D":d_loss[0],"G":g_loss})
            
            if epoch % 100 == 0:
                # Plot the progress
                print ("Epoch {:05.0f} [D loss: {:4.3f}, acc.: {:05.1f}%] [G loss: {:4.3f}]".format(
                    epoch, d_loss[0], 100*d_loss[1], g_loss))
            if epoch % int(epochs/100) == 0:
                plot_generated_images(noise_plot,
                                      path_save=dir_result+"/image_{:05.0f}.png".format(epoch),
                                      titleadd="Epoch {}".format(epoch))
            if epoch % 1000 == 0:
                plot_generated_images(noise_plot,
                                      titleadd="Epoch {}".format(epoch))
                        
        return(history)
history = train(models=_models, X_train=X_train, noise_plot=noise, dir_result=dir_result,epochs=10000, batch_size=100)`
- OS: Windows 10

- TensorFlow version: 2.1.0
- Python version: 3.7

And I have some problems:
`FailedPreconditionError                   Traceback (most recent call last)
<ipython-input-13-7e6cdc16ab87> in <module>
     72 _models = combined, discriminator, generator
     73 
---> 74 history = train(models=_models, X_train=X_train, noise_plot=noise, dir_result=dir_result,epochs=10000, batch_size=100)
     75 end_time = time.time()
     76 print("-"*10)

<ipython-input-13-7e6cdc16ab87> in train(models, X_train, noise_plot, dir_result, epochs, batch_size)
     27 
     28             # Train the discriminator q: better to mix them together?
---> 29             d_loss_real = discriminator.train_on_batch(imgs, np.ones((half_batch, 1)))
     30             d_loss_fake = discriminator.train_on_batch(gen_imgs, np.zeros((half_batch, 1)))
     31             d_loss = 0.5 * np.add(d_loss_real, d_loss_fake)

C:\Anaconda3\envs\tf\lib\site-packages\keras\engine\training.py in train_on_batch(self, x, y, sample_weight, class_weight, reset_metrics)
   1512             ins = x + y + sample_weights
   1513         self._make_train_function()
-> 1514         outputs = self.train_function(ins)
   1515 
   1516         if reset_metrics:

C:\Anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\keras\backend.py in __call__(self, inputs)
   3725         value = math_ops.cast(value, tensor.dtype)
   3726       converted_inputs.append(value)
-> 3727     outputs = self._graph_fn(*converted_inputs)
   3728 
   3729     # EagerTensor.numpy() will often make a copy to ensure memory safety.

C:\Anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\eager\function.py in __call__(self, *args, **kwargs)
   1549       TypeError: For invalid positional/keyword argument combinations.
   1550     """
-> 1551     return self._call_impl(args, kwargs)
   1552 
   1553   def _call_impl(self, args, kwargs, cancellation_manager=None):

C:\Anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\eager\function.py in _call_impl(self, args, kwargs, cancellation_manager)
   1589       raise TypeError("Keyword arguments {} unknown. Expected {}.".format(
   1590           list(kwargs.keys()), list(self._arg_keywords)))
-> 1591     return self._call_flat(args, self.captured_inputs, cancellation_manager)
   1592 
   1593   def _filtered_call(self, args, kwargs):

C:\Anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\eager\function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1690       # No tape is watching; skip to running the function.
   1691       return self._build_call_outputs(self._inference_function.call(
-> 1692           ctx, args, cancellation_manager=cancellation_manager))
   1693     forward_backward = self._select_forward_and_backward_functions(
   1694         args,

C:\Anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\eager\function.py in call(self, ctx, args, cancellation_manager)
    543               inputs=args,
    544               attrs=("executor_type", executor_type, "config_proto", config),
--> 545               ctx=ctx)
    546         else:
    547           outputs = execute.execute_with_cancellation(

C:\Anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     65     else:
     66       message = e.message
---> 67     six.raise_from(core._status_to_exception(e.code, message), None)
     68   except TypeError as e:
     69     keras_symbolic_tensors = [

C:\Anaconda3\envs\tf\lib\site-packages\six.py in raise_from(value, from_value)

FailedPreconditionError:  Error while reading resource variable _AnonymousVar46 from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/_AnonymousVar46/class tensorflow::Var does not exist.
	 [[node mul_46/ReadVariableOp (defined at C:\Anaconda3\envs\tf\lib\site-packages\keras\backend\tensorflow_backend.py:3009) ]] [Op:__inference_keras_scratch_graph_2593]

Function call stack:
keras_scratch_graph`
![image](https://user-images.githubusercontent.com/20381972/81101401-bf508880-8f16-11ea-80fc-773a8a6f0390.png)
![image](https://user-images.githubusercontent.com/20381972/81101421-caa3b400-8f16-11ea-979b-1af07cd77b96.png)

**Comment by ravikyram** [comment]
@EkaterinaAntipova 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version?
Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!
