### ISSUE TITLE
Mac virtualenv: TensorFlow Mechanics 101 failure

### ISSUE THREAD

**Issue by shirriff** [tensorflow/tensorflow#392]
When I try to run the Mechanics 101 tutorial on a Mac using virtualenv, it fails with:

$ python fully_connected_feed.py
Traceback (most recent call last):
  File "fully_connected_feed.py", line 31, in <module>
    from tensorflow.g3doc.tutorials.mnist import input_data
ImportError: No module named g3doc.tutorials.mnist

To reproduce:
$ virtualenv --system-site-packages ~/tensorflow
$ source ~/tensorflow/bin/activate
$ pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
$ python, running "hello world" test: works fine
$ python -m tensorflow.models.image.mnist.convolutional: works fine

First problem:
$ python -c 'import site; print "\n".join(site.getsitepackages())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getsitepackages'

Expected behavior: should print path, according to instructions at http://www.tensorflow.org/get_started/os_setup.html#run-a-tensorflow-demo-model
This seems to be a problem with virtualenv: See https://github.com/pypa/virtualenv/issues/228

Second problem:
Download fully_connected_feed.py 
$ python fully_connected_feed.py
Traceback (most recent call last):
  File "fully_connected_feed.py", line 31, in <module>
    from tensorflow.g3doc.tutorials.mnist import input_data
ImportError: No module named g3doc.tutorials.mnist

Expected behavior: should run MNIST according to instructions at http://www.tensorflow.org/tutorials/mnist/tf/index.html#tutorial-files

I suspect some sort of path problem, but due to the first problem I can't figure out the right path.

System:
MacBook Pro (Retina, 15-inch, Early 2013)
OS X El Capitan, version 10.11.1 (15B42)
Python 2.7.10 (default, Aug 22 2015, 20:33:39)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)] on darwin

**Comment by vrv** [comment]
This should be fixed in our 0.6.0 release.
