### ISSUE TITLE
about attention_seq2seq function without embedding

### ISSUE THREAD

**Issue by Mev-z** [tensorflow/tensorflow#3920]
we already have a function tf.nn.seq2seq.embedding_attention_seq2seq(), but if i want to use an embedding trained from other model, the function is not convenient, do we have a function like tf.nn.seq2seq.attention_seq2seq() that need an embedding para or the inputs embedded.
Thanks!

**Comment by wagamamaz** [comment]
it seem that the seq2seq folder have different classes, but i haven't try.
let me know when you solve the problem xD

**Comment by prb12** [comment]
This does not appear to be a bug report, but rather a general question.  Please can you reask on StackOVerflow.
