### ISSUE TITLE
Tensorflow writes events file in TMPDIR with unbounded size

### ISSUE THREAD

**Issue by Bidski** [tensorflow/tensorflow#39205]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not mobile
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 1.15.0-rc1-11276-gc9f7f636eb 2.1.0
- Python version: 3.6.9
- Bazel version (if compiling from source): 2.1.1
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: 10.1/7.6
- GPU model and memory: GTX 1080Ti 11GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I have a custom keras model and I am using the fit api to train. I am NOT using the tensorboard callback. During a training an events file in generated in my `/tmp` directory that slowly grows in size until all remaining space on the hard drive is consumed, causing training to crash as it is not able to write to this file any longer.

```
-rw-r--r-- 1 bidski bidski 28G May  6 10:00 /tmp/tmp_50ztys5/events.out.tfevents.1587776979.bidski-alien.30810.513.v2
```

I once tried deleting the file once it got too large, but this resulted in the training process hanging. Why is this file even created?

**Describe the expected behavior**
I would expect a tempfile to 
  1. not consume the entire hard drive
  1. not cause training to crash when writing to the file fails

**Comment by Bidski** [comment]
I believe this is because of [StatsAggregator](https://www.tensorflow.org/api_docs/python/tf/data/experimental/StatsAggregator). I completely forgot that I had this in my code and without looking into the code for `StatsAggregator` I had no idea that it created an events file in `TMPDIR`. 

I propose that `StatsAggregator` be modified so that a log directory can be provided for `StatsAggregator` to write to, or to have a `SummaryWriter` object passed to it.

**Comment by ravikyram** [comment]
@Bidski 

Will it be possible to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by Bidski** [comment]
@ravikyram 

Here is a simple snippet of code which I suspect causes the problem. 

```
def create_dataset(path, args):
    # Create a stats aggregator for the dataset
    aggregator = tf.data.experimental.StatsAggregator()

    # Load in the dataset
    dataset = tf.data.TFRecordDataset(path)

    # Convert dataset to training format
    dataset = dataset.map(parse_entry)

    # Take a random crop
    dataset = dataset.map(random_crop)

    # Fix up element shapes
    dataset = dataset.map(fixup_shape)

    # Shuffle the elements
    if args.shuffle_size > 1:
        dataset = dataset.shuffle(args.shuffle_size, reshuffle_each_iteration=False)

    # Set up batch size
    dataset = dataset.batch(batch_size=args.batch_size, drop_remainder=False)

    # Aggregate stats
    dataset = dataset.apply(tf.data.experimental.latency_stats("total_bytes"))
    dataset = dataset.apply(tf.data.experimental.bytes_produced_stats("bytes_produced"))
    options = tf.data.Options()
    options.experimental_stats.aggregator = aggregator
    options.experimental_stats.latency_all_edges = True
    dataset = dataset.with_options(options)

    return dataset
```

It loads a TFRecord file, does some simple transformations to the data (via the map calls) and initialises stats aggregation on the dataset. This dataset is then fed to a keras model via the fit API.

With the dataset stats aggregation an events file is created in `/tmp` and this file slowly (I assume the rate of growth is dependent on on the number of the elements in the dataset and the size of the elements in the dataset) grows in size. 

Removing the dataset stats aggregation results in no event files being generated (tensorboard callback is not being used and there are no summary writers anywhere in my code).

**Comment by jvishnuvardhan** [comment]
@Bidski Is this still an issue? Can you please share a simple standalone code to reproduce the issue? Thanks!
