### ISSUE TITLE
Calling custom op changes data type

### ISSUE THREAD

**Issue by Bidski** [tensorflow/tensorflow#39206]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not mobile
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.15.0-rc1-16779-g605ebe703f 2.1.0
- Python version: 3.8.2
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: 10.2.89 / 7.6.5
- GPU model and memory: GTX 1070 8GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I have a custom op defined as follows
```
REGISTER_OP("Mean2D")
    .Attr("T: {float, double}")
    .Attr(get_data_format())
    .Attr("alpha: {float, double} ")
    .Input("img: T")
    .Input("kernel: T")
    .Output("out: T")
    .SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {
        // ... snip ...
    });
```

When I call this op like this
```
# Code  
disp[1] = ops.mean2d(img=disp[1], kernel=self.gaussian(self.params["blur_sigma"]), alpha=float(self.params["blur_threshold"]))
```

I get this error
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py", line 685, in build
    self.call(x, **kwargs)
  File "/media/RAID/Projects/PhD/HVSnet/model/structure.py", line 372, in call
    disp[1] = ops.mean2d(img=disp[1], kernel=self.gaussian(self.params["blur_sigma"]), alpha=alpha)
  File "<string>", line 68, in mean2d
  File "/usr/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 692, in _apply_op_helper
    attr_value.type = _MakeType(value, attr_def)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 180, in _MakeType
    _SatisfiesTypeConstraint(i, attr_def, param_name=attr_def.name)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 57, in _SatisfiesTypeConstraint
    raise TypeError(
TypeError: Value passed to parameter 'alpha' has DataType int8 not in list of allowed values: float32, float64
```

**Describe the expected behavior**
I would expect that parameter `alpha` would maintain its `float` data type

**Comment by rohan100jain** [comment]
This is definitely strange behavior. Lets try and find a minimal reproduction so that we can figure out what the problem is. One idea would be to try running this op by itself without it being part of a Keras model - feed in some random values of img and alpha that mimics the failure case.

**Comment by Bidski** [comment]
```
#! /usr/bin/env python3

import numpy as np
import tensorflow as tf
tf_op_module = tf.load_op_library('./tf_op.so')

x = tf.random.normal(shape=(1, 1, 20, 20))
x = tf_op_module.mean2d(img=x, alpha=6.0)
```

**Comment by Bidski** [comment]
Also, is there a reason why `GetAttr` isn't overloaded for `double`?

**Comment by rohan100jain** [comment]
Was curious how you resolved the problem? Usually when we have a list of potential values for Attrs its for the types that we'd like to have kernels for e.g. what you do with the "T" attr there. For the "alpha" attribute, it should either be a float or a double. If you want to support both, you can do 

REGISTER_OP("Mean2D")
    .Attr("T: {float, double}")
    .Attr("alpha_type: {float, double}")
    .Attr("alpha: alpha_type")
    .Input("img: T")
    .Output("out: T")

and then you can add that as a type constraint in your kernel registration. You'll then have to templatize your kernel etc. 

There is a still a problem that if you had done

REGISTER_OP("Mean2D")
    .Attr("T: {float, double}")
    .Attr("alpha: double")
    .Input("img: T")
    .Output("out: T")

you would run into issues with the kernel because GetAttr isn't overloaded for double as you pointed out. Would you be willing do a PR for this? It simply involves adding a double to GetNodeAttr here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/node_def_util.h#L192

**Comment by Bidski** [comment]
I tried this (I also tried just using `T` rather than introducing an `alpha_type`)
> REGISTER_OP("Mean2D")
> .Attr("T: {float, double}")
> .Attr("alpha_type: {float, double}")
> .Attr("alpha: alpha_type")
> .Input("img: T")
> .Output("out: T")

and I get this error when running the python script. I just assumed that you couldn't have polymorphic attributes (the documentation only says that your inputs and outputs can be polymorphic)
```
Traceback (most recent call last):
  File "./tf_op.py", line 5, in <module>
    tf_op_module = tf.load_op_library('./tf_op.so')
  File "/usr/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Trouble parsing type string at 'alpha_type ' from Attr("alpha: alpha_type ") for Op Mean2D
```

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
