### ISSUE TITLE
Inability to use tf.Session()

### ISSUE THREAD

**Issue by BattleTaco** [tensorflow/tensorflow#39208]
Hi, I am new to tensorflow and I am still learning on what to do for printing. I've seen that I should be using tf.Session() but whenever I do that(like Sess = tf.Session() or just tf.Session()) i get the error >>

module 'tensorflow' has no attribute 'Session'

I've learned that I should also use tf.compat.v1 but it doesn't provide the same for my lessons as i cannot use .run or any of the things that session uses. I also use tf.print() or print() which is standard but doesn't run the same as .Session(). Are there any alternatives to run the same thing in Tensorflow 2.1.0 or if there was a way, is there a page that can help me do so?

**Comment by ravikyram** [comment]
@BattleTaco 

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by mihaimaruseac** [comment]
You should install TF 1.15 if you want to use Session. In 2.0 world, the entire API is eager, there is no more `Session`.

This is a question better suited for StackOverflow as it is not about a bug in the implementation. Hence, closing.
