### ISSUE TITLE
download_dependencies.sh failure: Usage: download_and_extract URL DIR

### ISSUE THREAD

**Issue by whitis** [tensorflow/tensorflow#39209]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Description:	Ubuntu 18.04.4 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
source
- TensorFlow version:
cloned today
- Python version:

ii  python         2.7.15~rc1-1 amd64        interactive high-level object-ori

- Installed using virtualenv? pip? conda?:
no

- Bazel version (if compiling from source):
none
- GCC/Compiler version (if compiling from source):
ii  python         2.7.15~rc1-1 amd64        interactive high-level object-ori

- CUDA/cuDNN version:
none
- GPU model and memory:
inxi -G
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Cayman PRO [Radeon HD 6950]
           Display Server: x11 (X.Org 1.20.5 ) driver: radeon
           Resolution: 1920x1080@60.00hz
           OpenGL: renderer: AMD CAYMAN (DRM 2.50.0 / 5.3.0-51-generic, LLVM 9.0.0)
           version: 4.3 Mesa 19.2.8

**Describe the problem**
trying to build deepbacksub which depends on tensorflow lite.

build fails with:
./tensorflow/tensorflow/lite/tools/make/download_dependencies.sh: line 59: 1: Usage: download_and_extract URL DIR

with "set -x -v" added to 2nd line of script, we see it is the eigen package, which is the first one.
download_and_extract "${EIGEN_URL}" "${DOWNLOADS_DIR}/eigen"
+ download_and_extract '' tensorflow/lite/tools/make/downloads/eigen
+ local 'usage=Usage: download_and_extract URL DIR'
./download_dependencies.sh: line 60: 1: Usage: download_and_extract URL DIR

cd /usr/local/src/deepbacksub/tensorflow
grep -o 'http.*bitbucket.org/eigen/eigen/get/.*tar\.gz' "tensorflow/workspace.bzl" | grep -v mirror.tensorflow | head -n1
[nada]
 cat tensorflow/workspace.bzl | fgrep -i eigen
        name = "eigen_archive",
        build_file = clean_dep("//third_party:eigen.BUILD"),
        patch_file = clean_dep("//third_party/eigen3:gpu_packet_math.patch"),
        strip_prefix = "eigen-4e696901f873a2347f76d931cf2f701e31e15d05",
            "https://storage.googleapis.com/mirror.tensorflow.org/gitlab.com/libeigen/eigen/-/archive/4e696901f873a2347f76d931cf2f701e31e15d05/eigen-4e696901f873a2347f76d931cf2f701e31e15d05.tar.gz",
            "https://gitlab.com/libeigen/eigen/-/archive/4e696901f873a2347f76d931cf2f701e31e15d05/eigen-4e696901f873a2347f76d931cf2f701e31e15d05.tar.gz",

**Provide the exact sequence of commands / steps that you executed before running into the problem**

sudo apt-get install libopencv-dev opencv-doc
cd /usr/local/srcsudo mkdir deepbacksubcd deepbacksubsudo git clone -b v2.1.0 https://github.com/tensorflow/tensorflow
# NEXT LINE FAILS:
sudo ./tensorflow/tensorflow/lite/tools/make/download_dependencies.sh
./tensorflow/tensorflow/lite/tools/make/download_dependencies.sh: line 59: 1: Usage: download_and_extract URL DIR
sudo  ./tensorflow/tensorflow/lite/tools/make/build_lib.sh
sudo git clone https://github.com/floe/deepbacksub.git
sudo make all
sudo make install

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

sudo git clone -b v2.1.0  https://github.com/tensorflow/tensorflow/
Cloning into 'tensorflow'...
remote: Enumerating objects: 278, done.
remote: Counting objects: 100% (278/278), done.
remote: Compressing objects: 100% (244/244), done.
remote: Total 891232 (delta 104), reused 133 (delta 32), pack-reused 890954
Receiving objects: 100% (891232/891232), 523.35 MiB | 3.49 MiB/s, done.
Resolving deltas: 100% (723322/723322), done.
Note: checking out 'e5bf8de410005de06a7ff5393fafdf832ef1d4ad'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Checking out files: 100% (19161/19161), done.
sudo ./tensorflow/tensorflow/lite/tools/make/download_dependencies.sh
./tensorflow/tensorflow/lite/tools/make/download_dependencies.sh: line 59: 1: Usage: download_and_extract URL DIR

**Comment by Saduf2019** [comment]
@whitis 
please refer to these links and let us know if it helps.

[link1](https://github.com/tensorflow/tensorflow/issues/35747)
[link2](https://github.com/tensorflow/tensorflow/issues/37846)
[link3](https://github.com/tensorflow/tensorflow/issues/31799#issuecomment-525244201)
[link4](https://gitmemory.com/issue/tensorflow/tensorflow/35747/573960517)
