### ISSUE TITLE
How to release CPU memory after session.close() java api

### ISSUE THREAD

**Issue by TEE324** [tensorflow/tensorflow#39219]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (linux centOS 7):
- TensorFlow installed from (source or binary):
- TensorFlow version (1.14.0):
- javaversion:java8

I use java to load tensorflow model，When I update the model，I close session and graph like that：session.close() & graph.close(), 
But the memory is not released，How could I release CPU memory timely to avoid OOM error please?
Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
