### ISSUE TITLE
TF: Model SubCassing | AttributeError: 'NoneType' object has no attribute 'compile'

### ISSUE THREAD

**Issue by Lincoln93** [tensorflow/tensorflow#39215]
**System information**
- System: Kaggle Kernel
- TensorFlow version: 2.1.0
- Python version: 3.6.6
- TPU model and memory: TPU V3-8

I am trying to implement sub-classing for model definition but face a following error:

```python
def my_model(Model):
    def __init__(self, dim):
        super(my_model, self).__init__(**kwargs)
        self.efnet  = efn.EfficientNetB0(input_shape=(dim, 3), include_top = False, weights = 'imagenet')
        self.gap    = L.GlobalAveragePooling2D()
        self.bn     = L.BatchNormalization()
        self.denseA = L.Dense(784, activation='relu', name = 'dense_A')
        self.out    = L.Dense(1, activation='sigmoid')
    
    def call(self, inputs):
        x     = self.efnet(inputs)
        x_gap = self.gap(x)
        bn    = self.bn(x_gap)
        den_A = self.denseA(bn)
        drop  = self.drop(den_A)
        return self.out(drop)

dim = (124,124)
model = my_model((dim)
```

I understand I don't load the model properly, but I think it should load in this way. I am trying on this on Kaggle tpu with a proper strategy scheme (though I didn't mention that syntax in the above snippet). Any catch?

**Comment by ravikyram** [comment]
@Lincoln93 

Looks code is incomplete.Please, share colab link or simple standalone code to reproduce the issue in our environment. Also, please note syntax is not correct in the attached code.`model = my_model((dim)`.Two brackets given before dim where it has to be one.Thanks!

**Comment by Lincoln93** [comment]
@ravikyram, please [check ](https://colab.research.google.com/gist/ravikyram/b5346042bd4847e56f3250711859c0ac/untitled857.ipynb)this.

**Comment by ravikyram** [comment]
@Lincoln93 

i am not seeing any issue in the colab link you have provided. Can you please share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by Lincoln93** [comment]
@ravikyram sorry, would you please check again.

**Comment by ravikyram** [comment]
@Lincoln93 

I am not able to access the colab link you have provided. Please, grant me access so it helps me to reproduce the issue.Thanks!

**Comment by Lincoln93** [comment]
sorry for the inconvenience. here [it is](https://colab.research.google.com/drive/1d1oUDznS0zzO4aZrsX0BYyJl5oMw8M27?usp=sharing ).

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.1.0, 2.2-rc4 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/f8f3165fa91902706788d3a040f3bf98/untitled869.ipynb).Thanks!

**Comment by Lincoln93** [comment]
@ravikyram is it bug or there's something wrong in the code?

**Comment by ymodak** [comment]
Your `my_model` function returns `None` which is passed to `compile` method.
This looks like more of an error model building instance. Thanks!

**Comment by innat** [comment]
It should be class not function. 

Instead of `def my_model(Model):` , it should be `class my_model(Model):` . And also we need to build the model further. Here is the full code:

```python

class my_model(Model):
    def __init__(self, dim):
        super(my_model, self).__init__(**kwargs)
        self.efnet  = efn.EfficientNetB0(input_shape=(dim, 3), include_top = False, weights = 'imagenet')
        self.gap    = L.GlobalAveragePooling2D()
        self.bn     = L.BatchNormalization()
        self.denseA = L.Dense(784, activation='relu', name = 'dense_A')
        self.out    = L.Dense(1, activation='sigmoid')
    
    def call(self, inputs):
        x     = self.efnet(inputs)
        x_gap = self.gap(x)
        bn    = self.bn(x_gap)
        den_A = self.denseA(bn)
        drop  = self.drop(den_A)
        return self.out(drop)

dim = (124,124)
model = my_model((dim)
model.build((None, *dim))
model.compile(...)
model.summary()
````
