### ISSUE TITLE
MemoryError in ubuntu, not mac

### ISSUE THREAD

**Issue by aimeida** [tensorflow/tensorflow#3921]
Hello, my script gets killed by MemoryError, running in an aws EC2 instance, with 7.5G memory.
However, it has no problem running in my Mac (8g memory) !!! they use same TF, but numpy version is slightly different.

Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.11.1'

Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.11.0'

I have absolutely no idea what happened... and my data is not likely to require that much memory either...  i did memory profiling in EC2, error occurs at line 290.

Line #    Mem usage    Increment   Line Contents
================================================
   275  412.289 MiB    0.000 MiB       @profile
   276                                 def test_naive(self, mx, yls, fn_model=None, W=None, b=None):
   277                                     """load variables and calculate acc"""
   278 5117.520 MiB 4705.230 MiB           mx_array = mx.toarray()
   279 5117.520 MiB    0.000 MiB           if fn_model is not None:
   280                                         reader = tf.train.NewCheckpointReader(fn_model)
   281                                         logger.info("loaded saved param from " + fn_model)
   282                                         W, b = reader.get_tensor("W"), reader.get_tensor("b")
   283                                     else:
   284 5117.520 MiB    0.000 MiB               assert (W is not None) and (b is not None)
   285                             
   286 5117.523 MiB    0.004 MiB           print 'read', type(W), type(b), mx_array.shape
   287 5117.523 MiB    0.000 MiB           x, _ = self.init_placeholder()
   288 5117.523 MiB    0.000 MiB           with tf.Session() as sess:
   289 5117.523 MiB    0.000 MiB               tf.initialize_all_variables()
   290 5130.176 MiB   12.652 MiB               y = sess.run(tf.nn.softmax(tf.matmul(x, W) + b), feed_dict={x: mx_array})

  File "meshtags/model_bow.py", line 290, in test_naive
    y = sess.run(tf.nn.softmax(tf.matmul(x, W) + b), feed_dict={x: mx_array})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 619, in _run
    np_val = np.array(subfeed_val, dtype=subfeed_dtype)
MemoryError

any comments are welcome ! thanks a lot.

**Comment by yaroslavvb** [comment]
There were some memory problems that are fixed by running with tcmalloc -- http://goog-perftools.sourceforge.net/doc/tcmalloc.html Also, with tcmalloc you can turn on [heap profiler](http://goog-perftools.sourceforge.net/doc/heap_profiler.html) and get a more detailed statistic of where the memory is going

**Comment by aselle** [comment]
@aimeida, please let us know if tcmalloc helps.

**Comment by aimeida** [comment]
thanks a lot for the response ! The "sad" truth is that there is NO bug, the program simply runs out of memory :-) I didn't realize that EC2 instance doesn't have swap -- that's why it works on Mac. 
Very sorry for the inconvenience :-(

**Comment by aselle** [comment]
Thanks for letting us know, glad you figured out the issue.
