### ISSUE TITLE
Full screen camera needed for pose estimation androie

### ISSUE THREAD

**Issue by kittusster** [tensorflow/tensorflow#39212]
Provide code for full screen camera (now only half screen camera ) shown on pose estimation android .Please provide the code for change to full screen

**Comment by Saduf2019** [comment]
@kittusster 
Have you referred to any of these links:
[link](https://blog.tensorflow.org/2019/08/track-human-poses-in-real-time-on-android-tensorflow-lite.html)
[link1](https://www.tensorflow.org/lite/models/pose_estimation/overview)
[link2](https://www.reddit.com/r/computervision/comments/bohklz/using_pose_estimation_in_android_project/)
[link3](https://github.com/ildoonet/tf-pose-estimation)
[link4](https://github.com/google-coral/project-posenet)
[link](https://medium.com/tensorflow/real-time-human-pose-estimation-in-the-browser-with-tensorflow-js-7dd0bc881cd5)

**Comment by kittusster** [comment]
Yes ,but not found solution ..where do we change the code for full screen
camera for pose estimation

**Comment by jvishnuvardhan** [comment]
@kittusster Can you please mention little more details on your question? 
1. Are you seeing only half screen? (I can see full screen in pixel)
2. can you show me an image of half screen?
3. did you change any settings?

Provide more details so that it is easy for us to resolve faster. Thanks
