### ISSUE TITLE
FailedPreconditionError:  Error while reading resource variable _AnonymousVar555 from Container: localhost.

### ISSUE THREAD

**Issue by soumilkanwal80** [tensorflow/tensorflow#39227]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow version (use command below):2.2.0-rc-4

**Describe the current behavior**

> FailedPreconditionError:  Error while reading resource variable _AnonymousVar555 from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/_AnonymousVar555/N10tensorflow3VarE does not exist.
> 	 [[node MatMul_388/ReadVariableOp (defined at <ipython-input-86-300e1b0d20e1>:30) ]] [Op:__inference_keras_scratch_graph_21594]
> 
> Function call stack:
> keras_scratch_graph

At building Model

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1IYvi-iIM2gcTVBPhE2K2qjTVUURyZvIi

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
I have tried in colab with TF 2.1.0 , 2.2-rc4 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/9222785fa6154ec7fae7b3bbd78e12e3/untitled863.ipynb).Thanks!
