### ISSUE TITLE
Typos in source code docs

### ISSUE THREAD

**Issue by naturomics** [tensorflow/tensorflow#39222]
[Here](https://github.com/tensorflow/tensorflow/blob/fedc6d951faa73936a1154d6507d54240614d416/tensorflow/python/eager/backprop.py#L532) a minor typo in the source code: **rturns** ==> **returns**

**Comment by ymodak** [comment]
Thanks for the issue. I have sent a fix for this.

**Comment by mihaimaruseac** [comment]
Closing as fixed by fe97200
