### ISSUE TITLE
Binary classification using Keras always give wrong predictions: The acc is always 0.5

### ISSUE THREAD

**Issue by OOF-dura** [tensorflow/tensorflow#39223]
Hi~ I am using Keras to make a simple binary classification. And I am using TF as backend.

I checked:

- data shuffle: I set the param in model.fit() shuffle = True
- network structure: The NN take a vector with 1024 elements and makes a prediction 0 or 1.

ENV: 

- tensorflow 1.13.2 
- Keras 2.2.4
- Keras-applications 1.0.8
- Keras-Processing 1.1.0
- Tensorflow-estimator 1.13.0
- Ubuntu 16.04 
- python3

But the output is still wrong. The acc is always 0.5.

Some people ran my code and get the acc 0.9857 after 1 epoch.
See here:
![image](https://user-images.githubusercontent.com/22954901/81170557-79a2c700-8fcd-11ea-978e-72e2bc192f95.png)

[https://stackoverflow.com/questions/61633602/binary-classification-using-keras-always-give-wrong-predictions-the-acc-is-alwa?noredirect=1#comment109021786_61633602](https://stackoverflow.com/questions/61633602/binary-classification-using-keras-always-give-wrong-predictions-the-acc-is-alwa?noredirect=1#comment109021786_61633602)

```
import tensorflow as tf
from tensorflow.keras.layers import Input, Flatten, Dense, Lambda, Conv2D, Reshape, MaxPool2D, Average, Dropout, Concatenate, \
    Add, Maximum, Layer, Activation, Conv1D, TimeDistributed, GlobalAvgPool2D
import numpy as np


class Test(tf.keras.Model):
    def __init__(self,attention_sz,dropout_rt, name=None):
        super(Test, self).__init__(name=name)
        # here we define the layer:
        self.fc = Dense(attention_sz,input_dim = attention_sz ,activation='relu')
        self.fc2 = Dense(attention_sz, activation='relu')
        self.fc3 = Dense(1, activation='sigmoid')

        self.dp = Dropout(dropout_rt,input_shape=(attention_sz,))
        self.dp2 = Dropout(dropout_rt,input_shape=(attention_sz,))


    def call(self, inp):
        # here we get the segmentation and pose
        with tf.device('/gpu:0'):
            print("~~~~~~~~~~~")
            x = self.fc(inp)
            print(x.shape)
            z = self.dp(x)
            print(z.shape)
            x = self.fc2(z)
            print(x.shape)
            z = self.dp2(x)
            print(z.shape)
            y = self.fc3(z)
            print(y.shape)
        return y 

if __name__ == '__main__':
    model  = Test(1024, 0.05)
    model.compile(optimizer='rmsprop',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
    x = np.round(np.random.normal(1.75, 0.2, size=(10000, 1024)), 2)
    x2 = np.round(np.random.normal(100.75, 0.2, size=(10000, 1024)), 2)
    labels = np.zeros((10000, 1))
    labels2 = np.ones((10000, 1))

    x_t = np.row_stack((x, x2))
    labels = np.row_stack((labels,labels2))
    print(x_t.shape)
    print(labels.shape)
    model.fit(x_t, labels, shuffle=True, epochs=10, batch_size=32)
    x = np.round(np.random.normal(1.75, 0.2, size=(1, 1024)), 2)
    y = np.round(np.random.normal(100.75, 0.2, size=(1, 1024)), 2)
    res = model.predict(x)
    print(res)
    print(res.shape)
    res = model.predict(y)
    print(res)
    print(res.shape)

```
output:
```
WARNING:tensorflow:From /home/frank/Desktop/mesh-py3/my_venv/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2020-05-06 19:00:58.440615: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-05-06 19:00:58.616327: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-05-06 19:00:58.617158: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55201b0 executing computations on platform CUDA. Devices:
2020-05-06 19:00:58.617175: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce RTX 2080, Compute Capability 7.5
2020-05-06 19:00:58.636996: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2592000000 Hz
2020-05-06 19:00:58.637508: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x558add0 executing computations on platform Host. Devices:
2020-05-06 19:00:58.637523: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2020-05-06 19:00:58.637876: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.095
pciBusID: 0000:01:00.0
totalMemory: 7.77GiB freeMemory: 7.06GiB
2020-05-06 19:00:58.637892: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2020-05-06 19:00:58.639694: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-05-06 19:00:58.639708: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2020-05-06 19:00:58.639713: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2020-05-06 19:00:58.639923: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6868 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5)
Epoch 1/10
2020-05-06 19:00:59.495123: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
20000/20000 [==============================] - 3s 148us/sample - loss: 8.0497 - acc: 0.4997
Epoch 2/10
20000/20000 [==============================] - 2s 98us/sample - loss: 8.0590 - acc: 0.5000
Epoch 3/10
20000/20000 [==============================] - 2s 99us/sample - loss: 8.0590 - acc: 0.5000
Epoch 4/10
20000/20000 [==============================] - 2s 80us/sample - loss: 8.0590 - acc: 0.5000
Epoch 5/10
20000/20000 [==============================] - 2s 81us/sample - loss: 8.0590 - acc: 0.5000
Epoch 6/10
20000/20000 [==============================] - 2s 80us/sample - loss: 8.0590 - acc: 0.5000
Epoch 7/10
20000/20000 [==============================] - 2s 89us/sample - loss: 8.0590 - acc: 0.5000
Epoch 8/10
20000/20000 [==============================] - 2s 83us/sample - loss: 8.0590 - acc: 0.5000
Epoch 9/10
20000/20000 [==============================] - 2s 78us/sample - loss: 8.0590 - acc: 0.5000
Epoch 10/10
20000/20000 [==============================] - 2s 79us/sample - loss: 8.0590 - acc: 0.5000
[[0.]]
(1, 1)
[[0.]]
(1, 1)

Process finished with exit code 0

```
Thanks in advance!

**Comment by OOF-dura** [comment]
Plus, I change the version of TF to ```tensorflow-gpu==1.15.0``` and I get:

![image](https://user-images.githubusercontent.com/22954901/81171383-e074b000-8fce-11ea-8a70-f6531dfdc317.png)


I want to figure it out. Why I met this problem? 
Thanks!

**Comment by ravikyram** [comment]
@OOF-dura 

Can you please try with latest TF versions 1.15 and 2.2-rc4 and you can see more than 99 percent accuracy.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/002a14545c23349d5dfb08314867c3db/untitled862.ipynb).There were lots of performance improvements in the latest versions. Thanks!

**Comment by OOF-dura** [comment]
> @OOF-dura
> 
> Can you please try with latest TF versions 1.15 and 2.2-rc4 and you can see more than 99 percent accuracy.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/002a14545c23349d5dfb08314867c3db/untitled862.ipynb).There were lots of performance improvements in the latest versions. Thanks!

Hi~ Yep. I am using TF 1.15.0. But my project is build on tensorflow 1.13
When I switch to 15 I get:
```
Traceback (most recent call last):
  File "/home/frank/PycharmProjects/MultiGarmentNetwork/test_network.py", line 14, in <module>
    from network.base_network import PoseShapeOffsetModel
  File "/home/frank/PycharmProjects/MultiGarmentNetwork/network/base_network.py", line 16, in <module>
    from render.generic_renderer import render_colored_batch, render_shaded_batch, perspective_projection
  File "/home/frank/PycharmProjects/MultiGarmentNetwork/render/generic_renderer.py", line 8, in <module>
    import dirt
  File "/home/frank/Desktop/mesh-py3/my_venv/lib/python3.5/site-packages/dirt/__init__.py", line 2, in <module>
    from .rasterise_ops import rasterise, rasterise_batch, rasterise_deferred, rasterise_batch_deferred
  File "/home/frank/Desktop/mesh-py3/my_venv/lib/python3.5/site-packages/dirt/rasterise_ops.py", line 6, in <module>
    _rasterise_module = tf.load_op_library(_lib_path + '/librasterise.so')
  File "/home/frank/Desktop/mesh-py3/my_venv/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so: cannot open shared object file: No such file or directory

```
I learn it is a problem with the env. But the answer on github it quite unclear.

**Comment by OOF-dura** [comment]
I am worried about that if I switch to tf15. Is there something can never be fixed?

Thanks!

**Comment by ninjakx** [comment]
The question is why it's giving better results when switching it to the newest version what changes have been made in tf?

Thanks and Regards,
Pygirl

**Comment by jvishnuvardhan** [comment]
@OOF-dura @ninjakx Root-cause of the issue is related to numerical instabilities of `sigmoid` activation in the final layer of model when used with `tensorflow-cpu` version. I changed two lines in your code as follows and got the similar as you get with `TF1.15`. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/8921e4737e1061bc3ad24b9d1285535a/39223_cpu.ipynb).

```
self.fc3 = Dense(1) #, activation='sigmoid'

loss = tf.keras.losses.BinaryCrossentropy(from_logits=True)
model.compile(optimizer='rmsprop',
                  loss=loss, #'binary_crossentropy'
                  metrics=['accuracy'])
```

When I used your code as it is with `tensorflow-gpu` version of `TF1.13.2`, then I noticed similar results as you have seen with `TF1.15`. Please note that the `cpu` and `gpu` versions uses different libraries for optimum computational time. [Here](https://colab.research.google.com/gist/jvishnuvardhan/dfbb1b550478e5b171e407aec7b32af5/39223_with_gpu.ipynb) is a gist with `TF1.13.2-gpu` version. Hope it is clear. 

Please verify once and close the issue. Thanks!

**Comment by OOF-dura** [comment]
> @OOF-dura @ninjakx Root-cause of the issue is related to numerical instabilities of `sigmoid` activation in the final layer of model when used with `tensorflow-cpu` version. I changed two lines in your code as follows and got the similar as you get with `TF1.15`. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/8921e4737e1061bc3ad24b9d1285535a/39223_cpu.ipynb).
> 
> ```
> self.fc3 = Dense(1) #, activation='sigmoid'
> 
> loss = tf.keras.losses.BinaryCrossentropy(from_logits=True)
> model.compile(optimizer='rmsprop',
>                   loss=loss, #'binary_crossentropy'
>                   metrics=['accuracy'])
> ```
> 
> When I used your code as it is with `tensorflow-gpu` version of `TF1.13.2`, then I noticed similar results as you have seen with `TF1.15`. Please note that the `cpu` and `gpu` versions uses different libraries for optimum computational time. [Here](https://colab.research.google.com/gist/jvishnuvardhan/dfbb1b550478e5b171e407aec7b32af5/39223_with_gpu.ipynb) is a gist with `TF1.13.2-gpu` version. Hope it is clear.
> 
> Please verify once and close the issue. Thanks!

Thanks!
Closed!
