### ISSUE TITLE
TF Hub BERT model output names mismatch with the singature.

### ISSUE THREAD

**Issue by 1duo** [tensorflow/tensorflow#39236]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.15
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 2.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

```
# model is from: https://tfhub.dev/tensorflow/bert_en_cased_L-12_H-768_A-12/1

saved_model_dir = "path/to/bert_en_cased_L-12_H-768_A-12/1"
loaded_model = tf.saved_model.load(saved_model_dir)
concrete_func = loaded_model.signatures["serving_default"]
prediction = concrete_func(**inputs)
```

Expected output names:
```
concrete_fn.outputs
Out[4]: 
[<tf.Tensor 'Identity:0' shape=(None, 768) dtype=float32>,
 <tf.Tensor 'Identity_1:0' shape=(None, None, 768) dtype=float32>]
```

**However, actual prediction returns a dict with different output names.**

```
prediction.keys()
Out[5]: [u'bert_model_1', u'bert_model']
```

**Describe the expected behavior**

Expecting the prediction output has same name as `concrete_func.outputs`.

**Comment by Saduf2019** [comment]
@1duo 
 Please post TF_Hub related issues in the [Hub Repo.](https://github.com/tensorflow/hub/issues) Thanks!
