### ISSUE TITLE
tf.keras.preprocessing.image.random_rotation makes a translation instead of rotation

### ISSUE THREAD

**Issue by Dr-Gandalf** [tensorflow/tensorflow#39237]
**System information**
standard tesorflow docker, tensorflow/tensorflow:2.1.0-py3-jupyter
v2.1.0-rc2-17-ge5bf8de 2.1.0

**Describe the current behavior**
![elephant](https://user-images.githubusercontent.com/26264000/81228345-f167f600-8fbb-11ea-8722-d25dcda78a0c.jpg)

![descarga](https://user-images.githubusercontent.com/26264000/81228466-1a888680-8fbc-11ea-8801-5e9061f489b5.png)

**Describe the expected behavior**

it should rotate the image 90 degrees

**Standalone code to reproduce the issue**
![elephant](https://user-images.githubusercontent.com/26264000/81228345-f167f600-8fbb-11ea-8722-d25dcda78a0c.jpg)

```python
import tensorflow as tf
import matplotlib.pyplot as plt
def show(im,im2): 
    plt.subplot(1,2,1) 
    plt.imshow(im) 
    plt.subplot(1,2,2) 
    plt.imshow(im2) 
    plt.show() 
    
img = tf.io.read_file('elephant.jpg')
img = tf.image.decode_jpeg(img, channels=0)/255
img = tf.image.resize(img, (320,320))
show(img,tf.keras.preprocessing.image.random_rotation(img,90))
```
if I try 
```python
show(img,tf.keras.preprocessing.image.random_rotation(img, rg=30,row_axis=0,col_axis=1,channel_axis=2))
```
I got the following error

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-42509f257892> in <module>()
     11 img = tf.image.resize(img, (180,320))
     12 #np.rollaxis(img, 2, 0)
---> 13 show(img,tf.keras.preprocessing.image.random_rotation(img, rg=30,row_axis=1,col_axis=0,channel_axis=2))

2 frames
/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/affine_transformations.py in random_rotation(x, rg, row_axis, col_axis, channel_axis, fill_mode, cval, interpolation_order)
     56     x = apply_affine_transform(x, theta=theta, channel_axis=channel_axis,
     57                                fill_mode=fill_mode, cval=cval,
---> 58                                order=interpolation_order)
     59     return x
     60 

/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/affine_transformations.py in apply_affine_transform(x, theta, tx, ty, shear, zx, zy, row_axis, col_axis, channel_axis, fill_mode, cval, order)
    321         transform_matrix = transform_matrix_offset_center(
    322             transform_matrix, h, w)
--> 323         x = np.rollaxis(x, channel_axis, 0)
    324         final_affine_matrix = transform_matrix[:2, :2]
    325         final_offset = transform_matrix[:2, 2]

<__array_function__ internals> in rollaxis(*args, **kwargs)

/usr/local/lib/python3.6/dist-packages/numpy/core/numeric.py in rollaxis(a, axis, start)
   1272     axes.remove(axis)
   1273     axes.insert(start, axis)
-> 1274     return a.transpose(axes)
   1275 
   1276 

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'transpose'

```

[](https://colab.research.google.com/drive/1x8ySj1tt5zA8woEU6NUIH0AJqmYDgIop#scrollTo=sqxsXx6kxde2)
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by kari-554** [comment]
I want to work on this issue **[#39237](https://github.com/tensorflow/tensorflow/issues/39237)**

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.1, [TF v2.2.0rc4](https://colab.research.google.com/gist/amahendrakar/786180db34adfd921ca7e629e3b6786d/39237.ipynb#scrollTo=3bJ-n9TCcWnX) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/c2f9fafb5d9795db6b49192a5cb1489a/39237-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by tanzhenyu** [comment]
use the RandomRotation layer

**Comment by jvishnuvardhan** [comment]
@Dr-Gandalf As suggested by @tanzhenyu please use `layers.experimental.preprocessing.RandomRotation` layer as shown below. Please take a look at the gist [here](https://colab.research.google.com/gist/jvishnuvardhan/4698ae014a3960ce271a700de419200a/39237-tf-nightly.ipynb).

```
data_augmentation = keras.Sequential([
  layers.experimental.preprocessing.RandomRotation(0.25),
])

augmented_image = data_augmentation(tf.expand_dims(img, 0), training=True)
show(img,augmented_image[0].numpy())

```

Please verify it once and close the issue if this was resolved for you. Thanks!

**Comment by nicolas-gervais** [comment]
# SOLUTION
The default arguments work on 4D images. If you want it to word in 3D images, use the argument `channel_axis=2`
