### ISSUE TITLE
Symbol not found during bazel build

### ISSUE THREAD

**Issue by Vikas-kum** [tensorflow/tensorflow#39234]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX mojave 10.14.6 18.7.0 Darwin Kernel Version 18.7.0 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source commit 70087ab4f46a4bebaacce1023cd12bd9c655e159 (HEAD -> rc2.2, tag: v2.2.0-rc4, origin/r2.2) 
- TensorFlow version: 2.2
- Python version:Python 3.6.10 :: Anaconda, Inc.
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): bazel 2.0.0 
- GCC/Compiler version (if compiling from source):Target: x86_64-apple-darwin18.7.0
- CUDA/cuDNN version: NA
- GPU model and memory:NA

**Describe the problem**
When trying to bazel build --config=opt --copt=-g //tensorflow/tools/pip_package:build_pip_package , I get this error. 
```
ImportError: dlopen(/private/var/tmp/_bazel_vikumar/03ac0190026ff3e87deaafab7f769284/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: __ZN10tensorflow4data12experimental14SnapshotReader33kSnappyReaderInputBufferSizeBytesE
  Referenced from: /private/var/tmp/_bazel_vikumar/03ac0190026ff3e87deaafab7f769284/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so
  Expected in: flat namespace
 in /private/var/tmp/_bazel_vikumar/03ac0190026ff3e87deaafab7f769284/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so
```

I explicitly tried changing snapshot_util.h(where kSnappyReaderInputBufferSizeByte is defined) to force recompile, but still fails with same above error. 
```
index a2df3ccec1..0488136b2b 100644
--- a/tensorflow/core/kernels/data/experimental/snapshot_util.h
+++ b/tensorflow/core/kernels/data/experimental/snapshot_util.h
@@ -70,6 +70,7 @@ class SnapshotReader {
   // The reader input buffer size is deliberately large because the input reader
   // will throw an error if the compressed block length cannot fit in the input
   // buffer.
+   static constexpr const int v =1; 
```

My tf.configure.bazelrc file contents
```
(tb2-2) 38f9d370d4a3:tensorflow vikumar$ cat .tf_configure.bazelrc 
build --action_env PYTHON_BIN_PATH="/Users/vikumar/anaconda3/envs/tb2-2/bin/python"
build --action_env PYTHON_LIB_PATH="/Users/vikumar/anaconda3/envs/tb2-2/lib/python3.6/site-packages"
build --python_path="/Users/vikumar/anaconda3/envs/tb2-2/bin/python"
build --config=xla
build:opt --copt=-g
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test:v1 --test_tag_filters=-benchmark-test,-no_oss,-gpu,-nomac,-no_mac,-oss_serial
test:v1 --build_tag_filters=-benchmark-test,-no_oss,-gpu,-nomac,-no_mac
test:v2 --test_tag_filters=-benchmark-test,-no_oss,-gpu,-nomac,-no_mac,-oss_serial,-v1only
test:v2 --build_tag_filters=-benchmark-test,-no_oss,-gpu,-nomac,-no_mac,-v1only
build --action_env TF_CONFIGURE_IOS="0"
```
**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel clean --expunge 
./configure
bazel build --config=opt --copt=-g //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mihaimaruseac** [comment]
I think this should be fixed at HEAD. Please let us know if not

**Comment by mihaimaruseac** [comment]
This seems to have stalled. I'll close it but if it still reproduces at head please reopen.
