### ISSUE TITLE
Upgrade/Provide Docker Images based on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by tarmath** [tensorflow/tensorflow#39232]
Upgrade/Provide Docker Images based on Ubuntu 20.04 LTS

**Comment by Saduf2019** [comment]
@tarmath Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by tarmath** [comment]
I am running the official docker image with gpu support on kubernetes
(upgraded to 2.2.0-gpu as of yesterday)

Currently, those docker images are based on the 2 years old Ubuntu 18.04 LTS (Long Term Support) Release. A new Ubuntu LTS Release (20.04, for April 2020) came out a couple weeks ago, and as such, it hopefully follows that tensorflow would naturally start migrating towards it.

Amongst other things, this latest official release comes with python 3.7 (Released on June 27, 2018), which itself provides a ton of improvements, as announced here:

https://docs.python.org/3.7/whatsnew/3.7.html

It also may be pertinent to mention that the nvidia cuda drivers work perfectly under this new release.

Let me know if you would like anymore background on this issue!

**Comment by tarmath** [comment]
actually need to amend my previous comment slightly: 

Ubuntu 20.04 comes with python 3.8 rather than python 3.7 (even better...!)

**Comment by Saduf2019** [comment]
@tarmath 
Is this still an issue

**Comment by tarmath** [comment]
Yes, this work is as close as can be to being inevitable. 

As pointed out in previous comments, there seems to be no blocker for this to occur. 

As I understand there may be competing priorities, it would be great to minimally have a sense on when this could potentially happen, if nothing else.

Appreciate you taking time for this! 🙏

**Comment by bjarthur** [comment]
the [install docs](https://www.tensorflow.org/install) say "Ubuntu 16.04 or later".  please update the docker images to 20.04!  thanks.

**Comment by angerson** [comment]
This isn't likely to be prioritized any time soon -- all our Dockerfiles are defined [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/dockerfiles) and you're welcome to submit a PR.

**Comment by Lotte1990** [comment]
@angerson @perfinion Any updates on this? I think many people would like to upgrade to the new LTS, including myself. Currently, this is the only issue holding me back...

**Comment by bjarthur** [comment]
why does this issue have the tf2.2 label?

**Comment by anencore94** [comment]
I think there are some dockerfiles based on 20.04 already [here](https://github.com/tensorflow/tensorflow/tree/6618bbc2d145db7e9da898dff68be9d1faa5c59a/tensorflow/tools/dockerfiles/dockerfiles/onednn).
However, I guess the ci release step doesn't docker push such dockerfiles on docker hub yet.

Also, I think something wrong with using this [file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dockerfiles/partials/onednn/ubuntu/version.partial.Dockerfile). It makes all dockerfiles with Ubuntu 20.04 unintentionally as [this file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dockerfiles/dockerfiles/onednn/ubuntu-16.04-devel-jupyter.Dockerfile#L22)

If you guys have a little time, Could you explain the file or docs which explains "how pushing dockerfiles process works in CI step"?
I'd like to handle this issue, but I couldn't get such process in this project by just searching "docker push" in the source code.

**Comment by bjarthur** [comment]
@angerson you have a volunteer to resolve this issue in @anencore94 .  could you please help him per his request ^

**Comment by bjarthur** [comment]
@anencore94 thanks for the links.  as a temporary workaround i've simply pre-pended my dockerfile that used to `FROM tensorflow/tensorflow:latest-gpu` with

```
ARG UBUNTU_VERSION=20.04

FROM ubuntu:${UBUNTU_VERSION} as base

RUN apt-get update && apt-get install -y curl

# See http://bugs.python.org/issue19846
ENV LANG C.UTF-8

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip

RUN python3 -m pip --no-cache-dir install --upgrade \
    pip \
    setuptools

RUN ln -s $(which python3) /usr/local/bin/python

ARG TF_PACKAGE=tensorflow
ARG TF_PACKAGE_VERSION=
RUN python3 -m pip install --no-cache-dir ${TF_PACKAGE}${TF_PACKAGE_VERSION:+==${TF_PACKAGE_VERSION}}
```

that is, i replaced `FROM` with the above.

**Comment by tarmath** [comment]
@bjarthur just want to point out that since you're not installing the cuda drivers, you will not get any gpu acceleration with this solution.

**Comment by MatrixScenary** [comment]
Still no 20.04 images as of 2.4.1, quite sad. I hope once they are released (if ever), it will be communicated and tracked somewhere as having to literally run a container to find out what ubuntu version it has is an overhead.

**Comment by cfarrend** [comment]
Is there any traction on this? We're mostly deciding whether to wait for an official Tensorflow release or attempt it ourselves. If it's in the works then we're happy to wait.

**Comment by kuraga** [comment]
Any news on this?

**Comment by angerson** [comment]
There's been some progress, but nothing new available yet: see
https://github.com/tensorflow/tensorflow/pull/48371 and
https://github.com/tensorflow/build/pull/21.

**Comment by sanatmpa1** [comment]
@tarmath,

The [PR](https://github.com/tensorflow/tensorflow/pull/51914/files) to update docker files to Ubuntu 20.04 is merged already and can you confirm if that helps resolving your issue? Thanks!

**Comment by tarmath** [comment]
Hi @sanatmpa1! 

Thanks for the nudge! 

I have just tried downloading the latest `tensorflow/tensorflow:latest-gpu` image, and it is still on 18.04:

```shell
root@d3bdbdcc7fa2:/# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
```

My guess is that we'll be seeing images based on the newer stack (besides the nightly ones) next time tensorflow is released...

I'll be looking forward to that!

**Comment by angerson** [comment]
@tarmath Can you also try out `tensorflow/tensorflow:nightly-gpu`? Those have picked up the changes, while the other main ones will get updated once the next TF release happens.
