### ISSUE TITLE
max of two tf.Dimension objects undetermined

### ISSUE THREAD

**Issue by thjashin** [tensorflow/tensorflow#3924]
### Environment info
Operating System: ubuntu 16.04

Installed version of CUDA and cuDNN: None
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. Which pip package you installed.
https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.10.0rc0

### Steps to reproduce
```python
import tensorflow as tf
max(tf.Dimension(1), tf.Dimension(None))
# => Dimension(1)
max(tf.Dimension(None), tf.Dimension(1))
# => Dimension(None)
```

I've looked at the code of Dimension class. It defines the comparison between integers and None to return None, causing this undetermined behavior when using max. I suggest that a better way could be to raise an Error when comparing with None or to always set integers to be larger, like python does.

**Comment by mrry** [comment]
Unfortunately raising an error in the `__lt__` (etc.) operators would break many shape functions, which rely on the comparison operations being tri-state (`True` and `False` when the values are both known; `None` when either value is unknown). It would be nice to raise an error on `max()` if either dimension is unknown, but I'm not sure of a way to do that without breaking the existing behavior of the comparison operators.

**Comment by thjashin** [comment]
Thanks, so that's the difficulty. But as far I know, there seems no way to raise an error on max() outside the __lt__ operators.

**Comment by mrry** [comment]
I'm going to close this issue as "not feasible at present". We might revisit it when all the Python shape functions move to C++, as the rationale for tri-state `__lt__()` (etc.) will have been eliminated by then.
