### ISSUE TITLE
Support CUDA 10.2

### ISSUE THREAD

**Issue by softlion** [tensorflow/tensorflow#39247]
**System information**
- TensorFlow version (you are using): 2.2.0-rc4
- Are you willing to contribute it (Yes/No): no

**Describe the feature and the current behavior/state.**
tensorflow has hardcoded the dll name of CUDA and tries to detect version 10.1, but version 10.2 is the current.

```W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll ```

The current name is cudart64_102.dll

**Will this change the current api? How?**
no

**Who will benefit with this feature?**
all new users

**Any Other info.**
-

**Comment by mihaimaruseac** [comment]
Unfortunately it is too late to change this as the effort to remove the hardcoded string will be too long and we already released the final version.

However, this can be solved by symlinking the 10.2 libs to 10.1 ones. At least on Linux, there were several people reporting success doing that.

**Comment by softlion** [comment]
Do you mean there won't be any more tensorflow version ?
I was able to run with 10.1 correctly.

**Comment by mihaimaruseac** [comment]
The 2.2 release is out. Next release is 2.3 which will probably target a new version of CUDA.

Patch releases are not allowed to change binary dependencies, except for security reasons

**Comment by TylerADavis** [comment]
Is there a timeline for when 10.2 will be supported in tf-nightly? 

[The documentation for the profiler](https://www.tensorflow.org/guide/profiler#install_the_profiler_and_gpu_prerequisites) says to install CUDA 10.1 or newer, which is misleading if only 10.1 is currently supported. It also explicitly says 10.2 needs to be installed in order to profile multi-gpu setups.

**Comment by mihaimaruseac** [comment]
2.3 will likely target CUDA 11, as was discussed in a recent SIG Build meeting

**Comment by ymodak** [comment]
Closing this issue now. Thanks!

**Comment by quassy** [comment]
> 2.3 will likely target CUDA 11, as was discussed in a recent SIG Build meeting

@mihaimaruseac The notes for TF 2.3.0 RC0 make no mention of CUDA 11 or 10.2, so is it still only supporting 10.1 officially?

**Comment by mihaimaruseac** [comment]
Reopening the issue as the support for newer CUDA has been downprioritized for TF 2.4

**Comment by mihaimaruseac** [comment]
Removing the staleness label, as this is an issue we need to keep open until at least TF 2.4

**Comment by mihaimaruseac** [comment]
(accidental close, reopening)

**Comment by peterukk** [comment]
Looks like tf_nightly_gpu_2.4.0 doesn't support CUDA 10.2 either. Can anyone confirm symlinking from 10.2 to 10.2 works for GPU training too?

**Comment by wookayin** [comment]
Please reopen it until TF gets 10.2 cuda support.

**Comment by sain0722** [comment]
Is there any tf version that fits CUDA 10.2?

**Comment by prampey** [comment]
@sain0722 tf2.0.0 worked for me with CUDA 10.2

**Comment by mihaimaruseac** [comment]
No. We are jumping from CUDA 10.1 to CUDA 11.

**Comment by ymodak** [comment]
TF 2.4 is released and supports CUDA 11.
See https://github.com/tensorflow/tensorflow/releases/tag/v2.4.0 
Thanks!
