### ISSUE TITLE
GPU support for tf.image.resize with antialias=True

### ISSUE THREAD

**Issue by kylemcdonald** [tensorflow/tensorflow#39246]
**System information**
- TensorFlow version 2.1.0
- Python 3.7
- CUDA 10.1
- Ubuntu 18.04

**Describe the feature and the current behavior/state.**

Right now `tf.image.resize` returns a CPU Tensor after being called with `antialias=True`.

```python
import tensorflow as tf
with tf.device('/device:GPU:0'):
    for antialias in (True, False):
        x = tf.random.uniform((64, 32, 32, 1), maxval=1)
        x = tf.image.resize(images, (28, 28), antialias=antialias)
        print(antialias, x.device)
```

Prints:

```
True /job:localhost/replica:0/task:0/device:CPU:0
False /job:localhost/replica:0/task:0/device:GPU:0
```

When antialiasing is enabled, a CPU Tensor is returned. When it is disabled, a GPU tensor is returned.

**Will this change the current api? How?**

No.

**Who will benefit with this feature?**

Anyone who wants to rescale images without severe resampling artifacts.

**Comment by LeicongLi** [comment]
Hi @kylemcdonald ,

tf.image.resize would call different kernels according to the value of **antialias**

https://github.com/tensorflow/tensorflow/blob/e5bf8de410005de06a7ff5393fafdf832ef1d4ad/tensorflow/python/ops/image_ops_impl.py#L1228-L1357

```
      if antialias:
        return resize_with_scale_and_translate('triangle')
      else:
        return gen_image_ops.resize_bilinear(
            images_t, new_size, half_pixel_centers=True)
```

If antialias is True, it calls a function resize_with_scale_and_translate, and this func calls a kernel named scale_and_translate which has no CUDA implementation yet.
Else antialias is False, it calls kernel resize_bilinear which has a CUDA implementation, and you can find it here (https://github.com/tensorflow/tensorflow/blob/e5bf8de410005de06a7ff5393fafdf832ef1d4ad/tensorflow/core/kernels/resize_bilinear_op.cc#L391-L413).

Thats the reason why the same function (Op) gets executed on different device.

Thanks.

**Comment by jvishnuvardhan** [comment]
@LeicongLi Thanks for the clear explanation. @kylemcdonald Please check the above response and close the issue if this was resolved for you. Thanks!
