### ISSUE TITLE
save tensorflow estimator based custom model for inference 

### ISSUE THREAD

**Issue by neuralminds** [tensorflow/tensorflow#39256]
thanks for the example codes. Experimented with Text Classification for character_rnn (https://github.com/tensorflow/tensorflow/blob/671baf080238025da9698ea980cd9504005f727c/tensorflow/examples/learn/text_classification_character_rnn.py).

How can i write a serving_input_fn for it ? I want to save and restore this model

extended the code to save but getting error, please help
`from tensorflow.contrib.learn.python.learn.utils import input_fn_utils` 
`feature_spec = {"feature":tf.FixedLenFeature([100],tf.int64)}`
`serving_input_fn = input_fn_utils.build_parsing_serving_input_fn(feature_spec)`
 and than
`classifier.export_savedmodel(export_dir_base='model', serving_input_receiver_fn=serving_input_fn)`

and getting this error

TypeError: Failed to convert object of type <class 'dict'> to Tensor. Contents: {'feature': <tf.Tensor 'ParseExample/ParseExample:0' shape=(?, 100) dtype=int64>}. Consider casting elements to a supported type.

**Comment by amahendrakar** [comment]
@neuralminds,
Could you please provide a minimal code snippet to reproduce the issue reported here and also the TensorFlow version you are using.

I was able to run the code given in the link without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/fe4375a75821fcd036489ebff763321f/39256.ipynb). Thanks!

**Comment by neuralminds** [comment]
Thanks for a response. I am using Tensorflow 1.15
pls find the code snippet here(https://gist.github.com/neuralminds/ea46e94faebc2beb7af20a0b609f1485).
I have exported the trained model as .pb files but when trying to restore for inference it throws error.

Also attaching rendered notebook here for reference
[estimator save and restore example.zip](https://github.com/tensorflow/tensorflow/files/4599110/estimator.save.and.restore.example.zip)

**Comment by neuralminds** [comment]
how i can input new data to this trained model for inference?

**Comment by amahendrakar** [comment]
@neuralminds,
On running the code, I am facing an error stating `InvalidArgumentError: Name: <unknown>, Key: chars, Index: 0.  Data types don't match. Data type: float but expected type: int64
	 [[{{node ParseExample/ParseExample}}]]`

Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/f4a7a6246a1004091b0e74845bf01305/39256.ipynb). Could you please confirm if this is the intended error. Thanks!

**Comment by neuralminds** [comment]
yes

**Comment by neuralminds** [comment]
hello @jvishnuvardhan , pls help in fixing the error. Struggling to restore the model for inference

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
