### ISSUE TITLE
TensorFlowLite app's camera doesn't focus on objects - produces blurry images

### ISSUE THREAD

**Issue by AnaRhisT94** [tensorflow/tensorflow#39259]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No.**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 18.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy S10+ and Samsung Galaxy A70 and Samsung Galaxy S7 Edge (I tried on many diff. devides)
- TensorFlow installed from (source or binary): git clone https://github.com/tensorflow/examples.git
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I'm trying to achieve this image quality:
[https://i.stack.imgur.com/tPfdg.jpg](https://i.stack.imgur.com/tPfdg.jpg)

**Describe the expected behavior**
I'm achieving this image quality (currently):
[https://i.stack.imgur.com/qD8uh.jpg](https://i.stack.imgur.com/qD8uh.jpg)

**Standalone code to reproduce the issue**
All the info. can be found in the following link:
[https://stackoverflow.com/questions/61611050/tensorflows-app-camera-images-are-blurry](https://stackoverflow.com/questions/61611050/tensorflows-app-camera-images-are-blurry)

Also, I've added most of it here to. (see below)

Set up the working directory

git clone https://github.com/tensorflow/examples.git
Open the project with Android Studio

Open a project with Android Studio by taking the following steps:

Open Android Studio. After it loads select " Open an existing Android Studio project".

In the file selector, choose examples/lite/examples/image_classification/android from your working directory to load the project.

In `LegacyCameraConnectionFragment.java`, in the function `onSurfaceTextureAvailable`

Add in line 90~ this code is added to turn on the flash all the time (it's off by default):

```
List<String> flashModes = parameters.getSupportedFlashModes();
if (flashModes.contains(android.hardware.Camera.Parameters.FLASH_MODE_TORCH))
{
  parameters.setFlashMode(parameters.FLASH_MODE_TORCH);
}
```

Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

It's simple, please take a cup or any other object, which you can put your phone over it, put a small object into it, for example like a gum, or some sort of a pill w/ text in it, and see if the image is blurry or not w/ TensorFlow's app.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@AnaRhisT94 
Could you please share a simple stand alone code for us to replicate this issue, code provided is not sufficient to replicate the issue.

**Comment by terryheo** [comment]
Could you confirm that the issue is still happening without your modification of parameters.setFlashMode() ?
