### ISSUE TITLE
When I run Interpreter.run() method I get: 'DataType error: cannot resolve DataType of [[Ljava.lang.Float;' 

### ISSUE THREAD

**Issue by ArtanBerisha1** [tensorflow/tensorflow#39250]
This is the code :
    fun estimateTheAction(detectedSkeletons: ArrayList<Float>): String {
             var output = Array(1) {FloatArray(4)}
             val arrayInput: Array<Float> = detectedSkeletons.toTypedArray()
             //var output = mapOf(1 to "person_jumping", 2 to "person_kicking", 3 to "person_running", 4 to "person_walking")
             var input = arrayOf(arrayInput)
             try {
                      interpreter?.run(input, output)
             }catch (e: Exception ){
                      e.printStackTrace()
        }
        //var index = output[0].toString()
        return "actionName[output[0][0]]
    }

Complete Error:
W/System.err: java.lang.IllegalArgumentException: DataType error: cannot resolve DataType of [[Ljava.lang.Float;
W/System.err:     at org.tensorflow.lite.Tensor.dataTypeOf(Tensor.java:199)
        at org.tensorflow.lite.Tensor.throwIfTypeIsIncompatible(Tensor.java:257)
        at org.tensorflow.lite.Tensor.getInputShapeIfDifferent(Tensor.java:162)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:132)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:249)
       .....

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
