### ISSUE TITLE
Unintended tf.distribute.ReplicaContext.merge_call behavior on TPU

### ISSUE THREAD

**Issue by fengyang0317** [tensorflow/tensorflow#39269]
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 & Colab
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0rc3
- Python version: 3
- CUDA/cuDNN version: 7.6
- GPU model and memory: GTX1080Ti

**Describe the current behavior**
The argument in merge_fn is the original input tensor.

**Describe the expected behavior**
According to the doc: "merge_fn: Function that joins arguments from threads that are given as PerReplica".

**Standalone code to reproduce the issue**
```
import os

import tensorflow as tf

if 'COLAB_TPU_ADDR' in os.environ:
  resolver = tf.distribute.cluster_resolver.TPUClusterResolver(
    tpu='grpc://' + os.environ['COLAB_TPU_ADDR'])
  tf.config.experimental_connect_to_cluster(resolver)
  tf.tpu.experimental.initialize_tpu_system(resolver)
  strategy = tf.distribute.experimental.TPUStrategy(resolver)
else:
  strategy = tf.distribute.MirroredStrategy()


@tf.function
def step_fn():
  v = tf.zeros([10])

  def merge_fn(strategy, keys):
    print(keys)

  context = tf.distribute.get_replica_context()
  context.merge_call(merge_fn, args=[v])


strategy.run(step_fn)
```

**Other info / logs** 

On a two GPU machine, the output is
```
PerReplica:{
  0: Tensor("zeros:0", shape=(10,), dtype=float32, device=/job:localhost/replica:0/task:0/device:GPU:0),
  1: Tensor("replica_1/zeros:0", shape=(10,), dtype=float32, device=/job:localhost/replica:0/task:0/device:GPU:1)
}
```
On a Colab TPU, the output is
```
Tensor("zeros:0", shape=(10,), dtype=float32)
```

**Comment by fengyang0317** [comment]
In addition, the **strategy.run** has different behavior. Code to reproduce:
```
import os

import tensorflow as tf
from tensorflow.python.distribute import mirrored_strategy
from tensorflow.python.tpu.ops import tpu_ops

if 'COLAB_TPU_ADDR' in os.environ:
  resolver = tf.distribute.cluster_resolver.TPUClusterResolver(
    tpu='grpc://' + os.environ['COLAB_TPU_ADDR'])
  tf.config.experimental_connect_to_cluster(resolver)
  tf.tpu.experimental.initialize_tpu_system(resolver)
  strategy = tf.distribute.experimental.TPUStrategy(resolver)
else:
  strategy = tf.distribute.MirroredStrategy()


@tf.function
def step_fn():
  context = tf.distribute.get_replica_context()
  v = tf.zeros([10], tf.int32) + context.replica_id_in_sync_group

  def merge_fn(strategy, keys):
    if isinstance(strategy, mirrored_strategy.MirroredStrategy):
      keys = strategy.experimental_local_results(keys)
      keys = tf.concat(keys, axis=0)
    else:
      keys = tpu_ops.all_to_all([keys for _ in range(8)], 0, 0, 8)
    return keys

  val = context.merge_call(merge_fn, args=[v])
  return val


ret = strategy.run(step_fn)
print(ret)
```

Results on GPUs:
```
tf.Tensor([0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1], shape=(20,), dtype=int32)
```

Results on TPU
```
PerReplica:{
  0: tf.Tensor(
[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]], shape=(8, 10), dtype=int32),
  1: tf.Tensor(
[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]], shape=(8, 10), dtype=int32),
  2: tf.Tensor(
[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]], shape=(8, 10), dtype=int32),
  3: tf.Tensor(
[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]], shape=(8, 10), dtype=int32),
  4: tf.Tensor(
[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]], shape=(8, 10), dtype=int32),
  5: tf.Tensor(
[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]], shape=(8, 10), dtype=int32),
  6: tf.Tensor(
[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]], shape=(8, 10), dtype=int32),
  7: tf.Tensor(
[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]], shape=(8, 10), dtype=int32)
}
```

**Comment by Saduf2019** [comment]
@fengyang0317 
While i run the code shared on tpu i face a different error, please find the [gist of the same](https://colab.sandbox.google.com/gist/Saduf2019/ff29cf83a0d2cd331dfca56867707cb9/tpu.ipynb)

**Comment by fengyang0317** [comment]
Could you run the code without '!pip install tf_nightly'. The code runs with 2.2.0rc4 in Colab.
I think the error you get is caused by the unaligned TF version between Colab and TPU. Your Colab is tf-nightly and the TPU is using 2.2.0rc4.

I started a stand-alone TPU node with TF nightly and did not meet the problem.

**Comment by fengyang0317** [comment]
Actually, I find that merge_call cannot enter the cross-replica context on TPU. The merge_fn is called on each replica. This behavior is different from GPU behavior and the document.

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/1ae9894150b4bb7f1ac95d8d33846ef7/untitled191.ipynb)

**Comment by fengyang0317** [comment]
Another question is the order of the all_gather and strategy.run output. Typically, the order is 0,1,2,3,6,7,4,5 according to device id.

Is this order designed deliberately? Why not use the order 0,1,2,3,4,5,6,7?

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF 2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/62ff44ac10d2819aad544db2cdb04285/untitled318.ipynb) ..Thanks!

**Comment by mohantym** [comment]
Was able to replicate the issue with TF 2.7, Attaching Gist of [GPU](https://colab.research.google.com/gist/mohantym/4930fb330fe50366c7ba6056aa51a972/untitled318.ipynb#scrollTo=MpmxhhpkUyqs) and [TPU](https://colab.research.google.com/gist/mohantym/513fd2056b6e9f9b9be3cb074669ff7e/untitled318.ipynb#scrollTo=6qurgSsdUu5d) for Reference. Thanks!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
