### ISSUE TITLE
Cross Compile tensorflow for arm using a different python version 

### ISSUE THREAD

**Issue by franout** [tensorflow/tensorflow#39260]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):   Host linux ubuntu 18.04 amd64 , Target : linux ubuntu 18.04 arm 32 bit 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.1.0
- Python version:  3.6.9
- Installed using virtualenv? pip? conda?:  python venv
- Bazel version (if compiling from source):  4.0.0
- GCC/Compiler version (if compiling from source):  arm-linux-gnueabihf-gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04
- CUDA/cuDNN version: no
- GPU model and memory: no 

Hi,
i am cross compiling tensorflow ( version 2.1.0 ) since i need the new delegate features for my hardware accelerator. 
I tried to install directly tensorflow lite from the official binaries for linux arm 32 however when i run a model i get the "illegal instruction" which is probably due to different floating point support of the processor and/or avx instructions (those ideas come from other github issue)
My board is the Pynq Z2 from tul with arm processor on 32 bit architecture running a linux based OS. I am following the procedure for building  tensorflow from source for the rasberry ( i changed some of the compiler flags for correctly match my architecture) however i cannot change the python version of the wheel ( i need a cp36 instead of a cp35 ) from the build process. Is there any workaround?

If you are wondering why i did not install python3.5, it is becouse there may be some incompatibility with the pynq package. 

PS i tried to change brutally the name of the wheel, from cp35 to cp36, but when i import tensorflow into the python enviroment i get the incompatibility error of the two version.

**Comment by teijeong** [comment]
HI franout,

Can you give more details about the steps you have tried? Also want to ask if you want to build whl for TensorFlow, or TensorFlow Lite. These are the instructions I'm aware of for each packages, but not sure where you encountered wheel version issue.

TensorFlow: https://www.tensorflow.org/install/source_rpi#python-3
TensorFlow Lite: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package

**Comment by franout** [comment]
my first try was to cross compile tensorflow lite for the zynq board, but i got the error about the pybind11 includes ( i didn't find the #38903 ). 
Therefore i cross compiled the entire tensorflow, without any problems following the guide you already cited (cross compile tensorflow for raspberry). Following that i obtained a wheel for python3.5 ,My question is: Is possible to produce a wheel for python3.6 instead?

Anyway, I tested the wheel for python3.5 on the board ( i needed to build  python3.5 from scratch on the board) and it is up and running now.

 [https://github.com/franout/tensorflow_for_pynqz2](url)  Here you can findthe wheel for the Pynq Z2 board ( zynq 7000 xilinx SoC) and the modified build script of the raspberry.

**Comment by terryheo** [comment]
Update CROSSTOOL_PYTHON_INCLUDE_PATH to point Python3.6 if you want to produce a wheel for Python 3.6
 https://www.tensorflow.org/install/source_rpi#python-3
