### ISSUE TITLE
error while building libtensorflowlite.so

### ISSUE THREAD

**Issue by yakovdan** [tensorflow/tensorflow#39271]
**System information**
- OS Platform and Distribution: Ubuntu 18.04 running as a docker container
- Mobile device: None
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.2.0
- Python version: 2.7.17
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 2.0.1
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: None
- GPU model and memory: None

I followed the official [documentation](https://www.tensorflow.org/lite/guide/android) to build c++ libraries of tensorflow-lite locally, but build of libtensorflowlite.so fails with the following error:

/root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/ruy/ruy/BUILD:270:1: C++ compilation of rule '@ruy//ruy:detect_arm' failed (Exit 1)
external/ruy/ruy/detect_arm.cc:59:10: error: use of undeclared identifier 'getauxval'
  return getauxval(AT_HWCAP) & kLocalHwcapAsimddp;

I ran bazel using the following command:

bazel build -c opt --config=android_arm64 --config=v2 --cxxopt='--std=c++14' //tensorflow/lite:libtensorflowlite.so  

Some environment vars:

ANDROID_HOME = /usr/lib/android-sdk
ANDROID_SDK_HOME=/usr/lib/android-sdk
ANDROID_SDK_API_LEVEL=23
ANDROID_NDK_HOME=/usr/lib/android-sdk/ndk/17.2.4988734
ANDROID_NDK_API_LEVEL=17

Build tools version: 27.0.1

What am I doing wrong?

**Comment by terryheo** [comment]
I've just tried it but can't find any issue with 2.2 branch.
Did you run "./configure" script?
If you did, could you share full build log with "-s" option?

**Comment by yakovdan** [comment]
Yes, I ran ./configure script. 

Of course, here is a build log with -s
[buildlog.txt](https://github.com/tensorflow/tensorflow/files/4610132/buildlog.txt)

**Comment by terryheo** [comment]
It seems that your NDK compiler doesn't have getauxval() support.

Could you try it again after installing NDK of this version?
https://developer.android.com/ndk/downloads/older_releases#ndk-17c-downloads

**Comment by yakovdan** [comment]
I tried again with the NDK version you provided, but the result is the same. Please see build log. 
[buildlog_17c.txt](https://github.com/tensorflow/tensorflow/files/4614341/buildlog_17c.txt)

**Comment by terryheo** [comment]
Now I got it.
You used ANDROID_NDK_API_LEVEL=17. You should use 18 or higher.

FYI, NDK release revision and NDK API level are different each other.
https://source.android.com/setup/start/build-numbers
https://developer.android.com/ndk/downloads/revision_history
