### ISSUE TITLE
embedding projector - mouse enter/out tooltip incorrect

### ISSUE THREAD

**Issue by joshua-gould** [tensorflow/tensorflow#39272]
See attached animated gif for example.

![hover](https://user-images.githubusercontent.com/5237151/81316791-08f5bc00-905a-11ea-8fd4-0c1540db9f21.gif)

**Comment by Saduf2019** [comment]
@joshua-gould 
Could you please open this issue in the correct repo [tensorboard repo], hence moving this to closed status.
