### ISSUE TITLE
TF Lite Benchmark does not compile on aarch64(RK3399)

### ISSUE THREAD

**Issue by wangg** [tensorflow/tensorflow#39275]
**System information**
- OS Platform and Distribution: Debian 9.12
- Mobile device: development board of RK3399 (Based on Big.Little architecture, it integrates dual-core Cortex-A72and quad-core Cortex-A53 with separate NEON coprocessor)
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.2.0
- Python version: 3.5.3
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): 6.3.0
- CUDA/cuDNN version: N/A
- GPU model and memory: Mali T860 MP4

**Describe the problem**

`bazel build -c opt tensorflow/lite/tools/benchmark:benchmark_model` cannot successfully build the binary of benchmark.

**Any other info / logs**

ERROR: /media/linaro/9aced46d-1704-4d54-8f78-7bb9c3cc8def/tmp/_bazel_linaro/d6df223f3277e5d3a224cafaa5ad64da/external/XNNPACK/BUILD.bazel:1910:1: C++ compilation of rule '@XNNPACK//:asm_ukernels' failed (Exit 1)
external/XNNPACK/src/f32-igemm/gen/6x8-minmax-aarch64-neonfma-ios.S:1:0: error: unknown value 'armv8.2-a+fp16' for -march
 // Auto-generated file. Do not edit!

Target //tensorflow/lite/tools/benchmark:benchmark_model failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 152.931s, Critical Path: 58.65s
INFO: 81 processes: 81 local.
FAILED: Build did NOT complete successfully

Please let me know if anything else is needed to compile the benchmark on aarch64.

**Comment by freedomtan** [comment]
`armv8.2-a+fp16` is not available in gcc before 7. Either use newer gcc or change the compilation options used by XNNPACK.

See https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/architecture-support

**Comment by Saduf2019** [comment]
@wangg 
Please update as per above comment

**Comment by wangg** [comment]
It compiles perfectly after I switch to GCC 10.1. Thanks for the help.

**Comment by Hao-Tju** [comment]
Is there any way to solve this problem with GCC-8.2.0?
