### ISSUE TITLE
FailedPreconditionError on tf.estimator.BaselineClassifier()

### ISSUE THREAD

**Issue by LinCheungS** [tensorflow/tensorflow#39274]
tf: 2.2.0-rc4

- Same code works fun on **tf.compat.v1.estimator.BaselineClassifier()**.
- But raise "FailedPreconditionError: GetNext() failed because the iterator has not been initialized. Ensure that you have run the initializer operation for this iterator before getting the next element." on **tf.estimator.BaselineClassifier()**.
- Input dataset is "tensorflow.python.data.ops.dataset_ops.BatchDataset"

`baseline_estimator = tf.estimator.BaselineClassifier(n_classes = 2)
baseline_estimator.train(input_fn = lambda : make_dataset(train_df, y_train))`  
[colab-link](https://colab.research.google.com/drive/1MbQXSMgsuRuoPgoZtBtjzB96KneiidWW?usp=sharing)

**Comment by ravikyram** [comment]
I have tried in colab with TF version  2.2-rc4 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/7cd940e58effbf2551fcd9f12db7446a/untitled867.ipynb).Thanks!

**Comment by denglw** [comment]
使用 tf.compat api
tf.compat.v1.estimator.BaselineClassifier(n_classes = 2)

**Comment by tanzhenyu** [comment]
Yep like @denglw said
