### ISSUE TITLE
Using tf.nn.softmax with tensor of dtype `int321 throws exception - works fine with float32

### ISSUE THREAD

**Issue by Rubix982** [tensorflow/tensorflow#39287]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): `Yes`
- OS Platform and Distribution: `Arch Linux`, but I'm actually using [collab](https://colab.research.google.com/) .
- TensorFlow installed from (source or binary): Using Google Collab.
- TensorFlow version (use command below): `Tensorflow 2.x`, setup using `%tensorflow_version 2.x` in the notebook
- Python version: `3.6.9`

**Describe the current behavior**

Error is thrown when a tensor is used in the `tf.nn.softmax` with `dtype` of `int32`, as seen below,
![image](https://user-images.githubusercontent.com/41635766/81356987-02b02000-90ec-11ea-9d77-de3a3509559d.png)

However, in contrast, when the `int32` are converted to a `float32`, like below, the code works, 
![image](https://user-images.githubusercontent.com/41635766/81357051-24a9a280-90ec-11ea-91c6-c4e4b3a5ecfa.png)

**Describe the expected behavior**

I should get back the array of values like I have with `float32`.

**Standalone code to reproduce the issue**

```
%tensorflow_version 2.x
import tensorflow as tf

tensor = tf.constant( [[10, 2], [1, 1]] )
print(tf.nn.softmax(tensor))
```

**Other info / logs**
```
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-26-dff233aef206> in <module>()
      1 tensor = tf.constant( [[10, 2], [1, 1]] )
----> 2 print(tf.nn.softmax(tensor))

4 frames
/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

NotFoundError: Could not find valid device for node.
Node:{{node Softmax}}
All kernels registered for op Softmax :
  device='XLA_GPU'; T in [DT_FLOAT, DT_DOUBLE, DT_BFLOAT16, DT_HALF]
  device='XLA_CPU'; T in [DT_FLOAT, DT_DOUBLE, DT_BFLOAT16, DT_HALF]
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_BFLOAT16, DT_HALF]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_HALF]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_HALF]
  device='XLA_GPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_BFLOAT16, DT_HALF]
 [Op:Softmax]
```

## Other Info:

Another similar issue exist(ed) [here](https://github.com/tensorflow/tensorflow/issues/33685). 

## Possible Solution

`tf.nn.softmax` should automatically promote `intx` to `floatx` in the function itself, or generate an error that `intx` can't be used, where `x` is either `64` or `32` bits.

Thank you.

**Comment by LeicongLi** [comment]
Hi @Rubix982 ,
  From the official specs of Tensorflow, "logits: A non-empty Tensor. Must be one of the following types: half, float32, float64.", you can check the detailed specs here
  https://www.tensorflow.org/versions/r2.1/api_docs/python/tf/nn/softmax#args

Thanks

**Comment by Rubix982** [comment]
Hi @LeicongLi .
I see, but the error message is confusing. It's just that the error message was confusing. The solution can be either,
1): Error message for the user to convert their `tensor` or `logit`, to either dtypes of `half`, `float32`, `float64`, 
2): Promote `int32` or `int54` to `float32` to `float64` ( typecast ), in that case in the function itself. 
3): Error message should be friendlier since `valid device for node` does not make much quick sense when the solution is just to just change the dtype of the input.

Thank you.

**Comment by Saduf2019** [comment]
I am able to replicate the error message as reported, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/9106fba3b7d13137d64474dd79892fef/2.ipynb)

**Comment by Rubix982** [comment]
Thank you, @Saduf2019 . The gist captures the issue.

**Comment by jvishnuvardhan** [comment]
@Rubix982 Agree with you that may be the error message could have been better but the later part of the error message clearly mentions all the kernels available for this `Op:Softmax`. Moreover, the docs on TF [webpage](https://www.tensorflow.org/versions/r2.1/api_docs/python/tf/nn/softmax#args) clearly mentions what `dtypes` are supported for this `op`. Generally this `op` is used in the last layer of network where all the inputs to this `op` are in one of the `dtypes` the kernel supports. As this `op` heavily used in the training (in every step with in each epoch), I guess adding `type cast` check may affect runtime performance. 

I guess there are two options (1) writing simple function of softmax calculation or create a `feature request` mentioning which kind of use-cases will get benefited, or (2) updating the error message. Feel free to open a PR to update the error message. Thanks!

**Comment by Rubix982** [comment]
Hi @jvishnuvardhan !
Agreed, the second option does seem easier to do. 
Will definitely look into updating the error message through a PR.
Thank you for your time!

Closing this issue.
