### ISSUE TITLE
tensorflow updation issues 

### ISSUE THREAD

**Issue by geet2019** [tensorflow/tensorflow#39291]
https://github.com/geet2019/rgn 
 sir I wanted tto implement this code . but his instrcution is to have python 2.7 and tenorflow in between 1.4 and 1.11 
doubt :
Can I able to execute in python 3.7 and in tensorflow 2.1 ?

**Comment by geet2019** [comment]
whether I am able to execute all functions in tensorflow <1.11 in tensorflow 2.1 . If not , is there any possible way to do so ?

**Comment by Saduf2019** [comment]
@geet2019 
Closing this as duplicate of #39294
