### ISSUE TITLE
Custom optimizer that behaves differently depending on the shapes of weights

### ISSUE THREAD

**Issue by ihsuy** [tensorflow/tensorflow#39298]
I am attempting to create a custom TensorFlow optimizer (`tf.keras.optimizers.Optimizer`) which treats weights of different shapes differently.

For example, please consider a simple convolutional neural network with the following shape of weights (and biases):

```
(3, 3, 3, 16)
(16,)
(3, 3, 16, 16)
(16,)
(2704, 64)
(64,)
(64, 10)
(10,)
```
At the beginning of the method _resource_apply_dense(self, grad, var), I would like to transform `var` of different shapes all into 2 dimensional, and then perform some other operations.

The following is the simplified logic of the desired transformation behavior:

```python
def custom_train_step(var):
    if tf.rank(var) == 1:
        # Case1
        return tf.expand_dims(input=var, axis=0)
    elif tf.rank(var) == 2:
        # Case2
        return tf.transpose(a=var)
    elif tf.rank(var) == 4:
        # Case3
        var = tf.transpose(a=var, perm=[3,0,1,2])
        return tf.reshape(var, shape=[var.shape[0], -1])
    else:
        # Case4 omitted
        pass
```
However, this will not work when `ndim(var)<4`, because it seems that when TensorFlow constructs its computation graph, all 4 branches are traced including Case3. Consequently, 1d and 2d `var`, during tracing, will also be passed to `tf.transpose(a=var, perm=(3,0,1,2))`, which will result in an error:

`ValueError: Dimension must be 1 but is 4 for '{{node transpose}} = Transpose[T=DT_FLOAT, Tperm=DT_INT32](transpose/ReadVariableOp, Const)' with input shapes: [16], [4].`

(The error occurred when var is a bias tensor of shape (16,))

I've tried directly writing the conditional statements using `tf.cond`, `tf.case` and `tf.switch_case`, but the error stayed. I understand this is perhaps because that `custom_train_step(var)` is polymorphic which made it necessary for retracing, but I can't think of a way to avoid such behavior by improving the code. (Please note again that I probably can not write 4 branches in separate methods and decorate each of them with `tf.function`, because this is supposed to be called inside a `tf.keras` training loop. Please correct me if I am wrong.)

I would like to know if there is a workaround to achieve what I described above, or is this type of behavior not yet supported by Tensorflow?

Any help and suggestions would be appreciated. Thanks!

**Comment by ravikyram** [comment]
@ihsuy 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by ihsuy** [comment]
@ravikyram 
Thank you for your reply.

I am trying to implement the custom optimizer directly on Google Colab. The TensorFlow version I currently use is `2.2.0-rc4`.

Here is a [Toy example](https://colab.research.google.com/drive/1RimEM_msNRyadICAtlSeb7-0fH0TAZJ1?usp=sharing).

I would really like to know if there is a legit way to achieve what I want, or is this behavior not yet supported?

Please let me know if any other information should be provided to help you locate the problem.
Many Thanks!

**Comment by ravikyram** [comment]
I have tried in colab with TF 2.2-rc4 and was able to reproduce the issue .However with TF 2.1.0 i am seeing different error message `ValueError: Error when checking input: expected flatten_input to have 4 dimensions, but got array with shape (60000, 28, 28)`.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/a636c3d5c099a7d8e0cbc00e7daa2d58/untitled870.ipynb).Thanks!

**Comment by ihsuy** [comment]
Thank you very much for trying to reproduce the issue in a different version.

I notice the error you pointed out with TF2.1.0 was because of a silly mistake (unrelated to this issue) I made when defining the model. Now it is fixed ([Link to Gist](https://colab.research.google.com/drive/1RimEM_msNRyadICAtlSeb7-0fH0TAZJ1?usp=sharing)), and the same old error from `tf.transpose` shows up. 

Sorry for the trouble.

**Comment by mdanatg** [comment]
This is a known issue due to the mixed static and dynamic shape verification being made by various ops. It's very confusing and we're looking at ways to fix it. Fortunately there are workarounds. I'll explain the issue first.


First, `tf.rank(var)` always returns a `Tensor`, which makes the control flow dynamic (that is, it's transformed into `tf.cond`). As you pointed out, all branches of dynamic control flow are traced. It is at this trace time when things break up. So far I believe that matches your observations.

Second, as you probably know, Tensor objects may have a static shape (obtained using `<tensor>.shape`), which is known at trace time. The key insight is that some ops, like `tf.transpose`, verify this static shape at trace time. That's what causes the error.


There are a couple of workarounds. I'll start with the most practical one.
First is to try using `shape.ndims` instead of `tf.rank`. `shape.ndims` returns a Python bool, which allows avoiding the creation of the `tf.cond`. You'll still support multiple ranks because the tf.function retraces. That should be ok because variables always have a static shape:

```
    assert var.shape.ndims is not None, 'Oops, this method doesn't work.'
    if var.shape.ndims == 1:
        # Case1
        return tf.expand_dims(input=var, axis=0)
    elif var.shape.ndims == 2:
        # Case2
        return tf.transpose(a=var)
    # etc.
```

The second will take care of unknown ranks, so it's the most complete. But also a bit more verbose.
The reason it works is because Autograph uses lazy evaluation of Python booleans, so `tf.rank` is only evaluated when `var.shape.ndims is None`, and in that case `tf.transpose` doesn't do any trace-time checks.
```
    if var.shape.ndims == 1 or (var.shape.ndims is None and tf.rank(var) == 1):
        # Case1
        return tf.expand_dims(input=var, axis=0)
    elif var.shape.ndims == 2 or (var.shape.ndims is None and tf.rank(var) == 2):
        # Case2
        return tf.transpose(a=var)
    # etc.
```

**Comment by ihsuy** [comment]
@mdanatg 
Hello! Thank you for the detailed and completed explanation on the issue.
Following your solutions, I was able to FINALLY fix my code and make it work.

The first solution worked immediately.
I will apply the second solution when I encounter the scenario where it is needed.

If possible, could you please link me to some resources explaining the inner working of TensorFlow AutoGraph at a more detailed level than [THIS ONE](https://www.tensorflow.org/guide/function)?
I wish, someday, I could understand TensorFlow as well as you do. It is a beautiful+efficient but intricate piece of work!

Again, thanks!
I will close this issue within 48 hours.
Have a great day!

**Comment by mdanatg** [comment]
@ihsuy here are a few links that might help:

* The [AutoGraph reference docs](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/index.md) - there are some aspects of tf.function they don't cover though
* The original [tf.function RFC](https://github.com/tensorflow/community/blob/master/rfcs/20180918-functions-not-sessions-20.md) - it's an older doc, but describes the fundamental mechanics well
* There are also a few recordings of in-depth presentations on various topics, titled with "Inside TensorFlow": https://www.youtube.com/results?search_query=%22Inside+TensorFlow%22

We're also looking into putting together a complete specification.
@ccrusius FYI

**Comment by ihsuy** [comment]
@mdanatg
Awesome.
I will be reading them!
Thank you!
