### ISSUE TITLE
InvalidArgumentError: Unable to find the relevant tensor remote_handle: Op ID: 3940, Output num: 0

### ISSUE THREAD

**Issue by Sayanroy1996** [tensorflow/tensorflow#39296]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@Sayanroy1996,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by debjyoti003** [comment]
I am also getting the same issue, the exact issue is below:

InvalidArgumentError: Unable to find the relevant tensor remote_handle: Op ID: 12, Output num: 0

How can I solve this problem, this is only happening with TPU, with GPU there is no issue.

**Comment by soosub** [comment]
I also get the same error when trying to work with TPU, when running on GPU I have no problems

`InvalidArgumentError: Unable to find the relevant tensor remote_handle: Op ID: 33, Output num: 0`

**Comment by hajuyung1** [comment]
2021년 6월 3일 (목) 20:30, Joost ***@***.***>님이 작성:
