### ISSUE TITLE
How to convert my custom model(.pb) with uint8 to float16?

### ISSUE THREAD

**Issue by WhaSukGO** [tensorflow/tensorflow#39293]
I trained my custom model using [Tensorflow Object Dection API](https://github.com/tensorflow/models/tree/master/research/object_detection).

I used [ssd_resnet50_v1_fpn](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync.config).

To accelerate the process of inference, I'm planning to use TensorRT.

So, I converted my model to onnx (.pb -> .onnx), using [tf2onnx](https://github.com/onnx/tensorflow-onnx).

However, TensorRT throws an error, ```"Unsupported onnx data type: uint8 (2)"``` 

Could you help me with converting my graph?

**Comment by ravikyram** [comment]
@WhaSukGO 

Can you please share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!
