### ISSUE TITLE
No giflib at ufpr.dl.sourceforge.net - because no ufpr.dl.sourceforge.net

### ISSUE THREAD

**Issue by patfla** [tensorflow/tensorflow#3929]
Maybe this is a transient issue and I'll try again later.

```
patfla@patfla-N550JV:~/code/tensorflow$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
Sending SIGTERM to previous Bazel server (pid=12785)... done.
.
ERROR: /home/patfla/code/tensorflow/tensorflow/core/platform/default/build_config/BUILD:56:1: no such package '@gif_archive//': Error downloading from http://ufpr.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz to /home/patfla/.cache/bazel/_bazel_patfla/411134e9cd8b53ea4deaf22318a2a19e/external/gif_archive: Error downloading http://ufpr.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz to /home/patfla/.cache/bazel/_bazel_patfla/411134e9cd8b53ea4deaf22318a2a19e/external/gif_archive/giflib-5.1.4.tar.gz: ufpr.dl.sourceforge.net and referenced by '//tensorflow/core/platform/default/build_config:platformlib'.
ERROR: Analysis of target '//tensorflow/cc:tutorials_example_trainer' failed; build aborted.
INFO: Elapsed time: 12.010s
```

```
patfla@patfla-N550JV:~/code/tensorflow/tensorflow$ grep -ir ufpr *
contrib/cmake/external/gif.cmake:set(gif_URL http://ufpr.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz)
workspace.bzl:    url = "http://ufpr.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz",

```

```
patfla@patfla-N550JV:~/code/tensorflow/tensorflow$ ping ufpr.dl.sourceforge.net
ping: unknown host ufpr.dl.sourceforge.net

```

**Comment by patfla** [comment]
And now, a short while later, mysteriously - it works.

Close issue.

**Comment by Mike-Dax** [comment]
I'm experiencing the exact same issue - same file and host and lack of connectivity. I'll try again later.

**Comment by beniz** [comment]
Yes, sad truth, a whole build depends on sourceforge availability :/

**Comment by beniz** [comment]
Here's a temporary fix, I've put the giflib tarball at https://deepdetect.com/stuff/giflib-5.1.4.tar.gz
Then modify the two files below by replacing the sourceforge URL with the one above.
- `tensorflow/workspace.bzl`
- `tensorflow/contrib/cmake/external/gif.cmake`
cc @Mike-Dax

**Comment by Mike-Dax** [comment]
Turned out several packages, giflib, swig (both on sourceforge) and zlib (on their site) are having network problems - so I grabbed them from various other sources.

It also turns out the JVM doesn't like letsencrypt, so I rehosted it all myself locally and it seems to be working now.

Here's the SSL error for those who will inevitably google this later.

```
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and referenced by '//tensorflow/core/platform/default/build_config:platformlib'.
```

Thanks for your help @beniz

**Comment by parilo** [comment]
faced with the same issue, cannot connect to ufpr.dl.sourceforge.net, main sourceforge site is available

**Comment by vskubriev** [comment]
Same issue with `http://ufpr.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz`
