### ISSUE TITLE
TensorBoard,No scalar summary tags were found

### ISSUE THREAD

**Issue by chenghuige** [tensorflow/tensorflow#393]
sess = tf.Session() 
init = tf.initialize_all_variables()
sess.run(init)

summary_writer = tf.train.SummaryWriter('./tmp/tensorflow_log', graph_def=sess.graph_def)

#However after launching TensorBoard I can not see any grah def info..
I also tried tf.training.summary_io.SummaryWriter, but it will not generate any log..
""
No scalar summary tags were found.

Maybe data hasn't loaded yet, or maybe you need to add some tf.scalar_summary ops to your graph, and serialize them using the tf.training.summary_io.SummaryWriter.
"""

Seems there are people facing the same issue, on stackoverflow but not solved.
http://stackoverflow.com/questions/33634764/tensorboard-doesnt-find-scalar-statistics/33652076#33652076

**Comment by danmane** [comment]
Have you tried following this tutorial? http://www.tensorflow.org/how_tos/summaries_and_tensorboard/index.html

Note you need to create `scalar_summary` ops and run them, and write them to the SummaryWriter - just creating a SummaryWriter on its own is not enough.

In the invocation you showed there should be a graph definition written - just making sure, have you clicked the "Graph" tab in the top right corner?

**Comment by chenghuige** [comment]
@danmane Thanks danmane, seems a problem for my firefox in my virtual machine running ubuntu. On windows from chrome I can see the graph, so not an issue, closing.

**Comment by jaelim** [comment]
I've been experiencing a similar problem. Is this because only the Chrome browser is compatible with Tensorboard?

**Comment by jaelim** [comment]
@chenghuige see my question above

**Comment by danmane** [comment]
Which browser are you on? I think the graph visualizer is broken on FF at the moment. Does everything work if you're on chrome?

**Comment by jaelim** [comment]
@danmane I'm using Firefox on Ubuntu linux. The only thing I'm seeing is the 'Events' and 'Histograms'. No 'Images' nor 'Graph'. I don't think I have an option to install Chrome browser on Ubuntu, so I have no idea if it does work on Chrome.

**Comment by PeterARBork** [comment]
@jaelim I had similar problems until I realized that the summary writer did not actually write the file unless I called the summary writer's flush() function. Maybe explicitly calling the flush() function will sort it out for you too?

I'm not sure, but it's probably because I had the summary writer's code snippet in a code part that did not close (and the code finished before the standard 120 seconds between each automatic flush).

**Comment by esraahassan** [comment]
please solve this problem in video

**Comment by danmane** [comment]
@esraahassan can you explain what you mean by "please solve this problem in video"?

**Comment by yanyiwu** [comment]
I met this issue and fixed it just now using the absolute directory path (/home/xxx/path2) instead of the relative path ( './path2' ).
