### ISSUE TITLE
missing API documentation to write user ops

### ISSUE THREAD

**Issue by raingo** [tensorflow/tensorflow#3930]
For example, how to fill a tensor with all zeros. Is it built in with `context -> allocate_output` or we can get the internal memory and do `memset`?

**Comment by aselle** [comment]
We likely will not document information on how to implement internals. Fortunately there is many examples to learn from. 

Go see definition of ones for example
https://github.com/tensorflow/tensorflow/blob/8de7608075c6dd6fcaf8f5c3d921f3611f8e7611/tensorflow/python/ops/array_ops.py#L1205

It uses the constant op
https://github.com/tensorflow/tensorflow/blob/5df4c71c86b28c2a4dd746bd67f00fc0281bd24f/tensorflow/core/kernels/constant_op.cc

please look at that for guidance.

**Comment by raingo** [comment]
Thanks for this information.
