### ISSUE TITLE
Extension of the Data API `take` method to accept percent values

### ISSUE THREAD

**Issue by milost** [tensorflow/tensorflow#39308]
**System information**
- TensorFlow version (you are using): 2.1.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
The Tensorflow Data API defines the [`take` method](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#take) which makes it possible to process a certain number of dataset elements. Currently it seems to be only possible to specify an absolute number of elements to be consumed (example: 32). It would be a nice addition if the take method could also receive a percentage value (0.0 - 1.0) that permits the consumption of a certain percentage of the dataset (exmaple: 0.2 for 20% of the dataset). This would be especially helpful for experiments that require an incremental increase in the amount of training data.

**Will this change the current api? How?**
If the signature of the take method is extended to accept float as well as integer values, a fundamental change to the API should not be necessary.

**Who will benefit with this feature?**
This would be especially helpful for experiments that require an incremental increase in the amount of training data (for example in active learning scenarios).

**Comment by jsimsa** [comment]
The challenge with supporting percentage is that it is not clear what the right behavior is for a dataset whose cardinality is not statically known (or infinite). What would you expect in those cases?

On a related note, could your use case be addressed by taking any 20% of the dataset (as opposed to the initial 20%)? If so, you could achieve that by using `filter`.

**Comment by milost** [comment]
In the streaming case, where the total size of a dataset is not known or cannot be determined in advance, I would expect the method to throw a meaningful exception that clearly states that selection by percentage is not applicable to streaming data and therefore not supported.

In any case, the selection by percentage should be deterministic, so that it can be expected that the same 20% of data used in a previous training run will be used in the current run.

**Comment by jsimsa** [comment]
Thanks. If you do not care about selecting the first 20% but any 20% (approximately), then you can do so by filter:

```
import tensorflow as tf

dataset = tf.data.Dataset.range(50)
dataset = dataset.filter(lambda _: tf.less(tf.random.uniform(shape=[], maxval=100, dtype=tf.int32, seed=12), 20))

# Iterating through the dataset multiple times will print the same elements 
# because we use a fixed seed for the random uniform call.
for elem in dataset:
  print(elem)

for elem in dataset:
  print(elem) 
```

**Comment by rmothukuru** [comment]
@milost,
Can you please confirm if the above workaround has resolved your issue and consequently, if we can close this issue? Thanks!

**Comment by rmothukuru** [comment]
@milost,
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

Please refer the [Documentation of Dataset Filter](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#filter) and [jsimsa's answer](https://github.com/tensorflow/tensorflow/issues/39308#issuecomment-631706979).
