### ISSUE TITLE
CUBLAS_STATUS_NOT_INITIALIZED error when running without GPU

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#39303]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL 7.5
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.2.0
- Python version: 3.7.4
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): 8.3.0
- CUDA/cuDNN version: 10.1.243

**Describe the current behavior**

When running the stock example on a system with CUDA but without CUDA visible devices (e.g. no GPUs allowed in job, GPUs busy, disabled cgroups) Tensorflow throws an error `failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED`

**Describe the expected behavior**

Fallback to CPU execution as done when no GPU/CUDA was present at all

**Standalone code to reproduce the issue**
```
import tensorflow as tf

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax'),
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
```

**Other info / logs**

Again this happens on a node that has GPUs and CUDA properly setup but inside a job which makes the GPUS unavailable. This can be verified by `tf.config.list_physical_devices('GPU')` which comes up empty.

So the issue is the TF tries to use cublas without checking for GPUs first.

This worked in in TF 2.1 so this is a regression!

**Comment by amahendrakar** [comment]
@Flamefire,
I was able to run the code without any issues on both [TF v2.1](https://colab.research.google.com/gist/amahendrakar/48ae1033333127c1d71ff93976d8ab9f/39303-2-1.ipynb) and [TF v2.2](https://colab.research.google.com/gist/amahendrakar/416b3330bd7a3314ddca60785b5396ac/39303-2-2.ipynb). Please find the attached gist. Thanks!

**Comment by Flamefire** [comment]
I can't reproduce this anymore either. Closing until it happens again. Thanks anyway
