### ISSUE TITLE
Saving model in Single Writer Multiple Reader (SWMR) mode

### ISSUE THREAD

**Issue by markub3327** [tensorflow/tensorflow#39312]
Hello, Can I set SWMR mode when I'm saving my model to h5 file? I need a concurrent reading of an HDF5 file while it is being written from another training process. It's useful in multi-agent reinforcement learning. Thanks.

**Comment by gowthamkpr** [comment]
@markub3327 Can you explain the issue in detail? Is it a new feature that you are talking about? Thanks!

**Comment by markub3327** [comment]
### What is SWMR
&ensp; The SWMR is the feature of an HDF5 file (h5py includes support from version 2.5.0). The SWMR features allow simple concurrent reading of an HDF5 file while it is being written from another process. The writer process creates the target file and it switches file into SWMR mode.
The reader process opens the file with swmr=True.

http://docs.h5py.org/en/stable/swmr.html

### Why would it be helpful to the community? 
When we have a game, where every agent is running in own environment on another process (python multiprocessing). Agents are collecting experiences for one learner network that is on another process too. We need to read the learner's model file that is updated by the learner in update_timestep period (it's periodically saving learner's weights to h5 file). Agents in another process can at the same time read from the learner's h5 file while the learner's process is writing to the file. It's maybe dangerous, how many times we can open the model (h5) file while we're writing to it from another process?

How we can share the Keras model between processes or many computers in the local network when the model file is too large? I think that the best option is saving it to file then share it between multiple processes/computers in the local network (agents).

### Is it a new feature that you are talking about?
It isn't a new feature in h5 files, but when we're saving Keras model SWMR mode is not an option to enable.
