### ISSUE TITLE
tfjs-node does not work with Node14

### ISSUE THREAD

**Issue by jeffrson** [tensorflow/tensorflow#39317]
This is due to the new N-API-Version '6' which is missing from package.json.

The library builds apparently without issues (as N-API '5'), but the install.js script fails to symlink or copy tensorflow.dll (because folder for N-API '6' does not exist).

**Comment by amahendrakar** [comment]
@jeffrson,
As this is a TF-js issue, could you please raise a new issue in the TF-js repo from [this link](https://github.com/tensorflow/tfjs/issues/new), so that we can track it there. Thanks!

**Comment by jeffrson** [comment]
https://github.com/tensorflow/tfjs/issues/3236
