### ISSUE TITLE
Breakpoints do not stop inside tf.function

### ISSUE THREAD

**Issue by edurenye** [tensorflow/tensorflow#39320]
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): binary (pip)
- TensorFlow version (use command below): 2.2.0
- Python version: 3.7
- CUDA/cuDNN version: CUDA 10.1 / cuDNN 7
- GPU model and memory: GeForce RTX 2060 6GB GDDR6

**Describe the current behavior**

If in the code from below you set a breakpoint in the line `print('Dummy function')` it will not stop.
```
import tensorflow as tf

def read_tfrecord(x):
    print('Dummy function')
    return x

dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
print(dataset)
dataset = dataset.map(lambda x: read_tfrecord(x))
```

**Describe the expected behavior**

The code execution should stop at that line and you should be able to debug that function.

**Standalone code to reproduce the issue**

```
import tensorflow as tf

def read_tfrecord(x):
    print('Dummy function')
    return x

dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3])
print(dataset)
dataset = dataset.map(lambda x: read_tfrecord(x))
```

**Other info / logs** Include any logs or source code that would be helpful to

First I though it was a problem with the debugger that I was using so I created an issue there (https://github.com/jupyterlab/debugger/issues/435).

Then they said it might be to the underlying debugger that it was using (ptvsd / debugpy) since the problem was also present in Visual Studio Code, and both debuggers use the same, so I created an issue there as well (https://github.com/microsoft/debugpy/issues/228).

And they now point out that it might be related to how tensorflow is build, so maybe the problem comes from Tensorflow and the way it creates the threads, read comment: https://github.com/microsoft/debugpy/issues/228#issuecomment-624908204

**Comment by ravikyram** [comment]
@edurenye 

I have tried in colab with TF version 2.2-rc4 .Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/46a30c34caf46264e947d1737ad5a7b2/untitled871.ipynb)Is this the expected behavior?Thanks!

**Comment by edurenye** [comment]
You can't test in colab, colab doesn't have a debugger that you can use to set breakpoints as far as I know.
You need jupyter or Visual Studio Code.

You can't do something like this in colab:
![debug_map](https://user-images.githubusercontent.com/6824576/81548935-50dc5200-937e-11ea-8286-b261065f0ff3.png)

**Comment by gowthamkpr** [comment]
Yes I was able to reproduce this.
![image](https://user-images.githubusercontent.com/47574994/81738873-463dbd80-944f-11ea-91a0-06bcda41de2e.png)

**Comment by jsimsa** [comment]
@edurenye can you check whether you can set a breakpoint within `tf.function`? tf.data wraps all user defined functions in `tf.function` and I suspect that the behavior you have observed is not specific to tf.data and applies generally to all `tf.function`s.

**Comment by edurenye** [comment]
@jsimsa I tried with the following code:
```
import tensorflow as tf

@tf.function
def f(x, y):
    print('Operate')
    return x ** 2 + y

x = tf.constant([2, 3])
y = tf.constant([3, -2])
f(x, y)
```

And I set a breakpoint as before, it did not stop at the breakpoint.

So, yes, it happens with all `tf.function`s.

**Comment by bhack** [comment]
> Note: AutoGraph is compatible with Eager, but the converse is not always true, so exercise care when making modifications to the code while debugging.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/debugging.md#debugging-tffunction-tfconfigexperimental_execute_functions_eagerly

**Comment by edurenye** [comment]
"In Tensorflow 2.0, eager execution is enabled by default." Is that not true?

Thank you! I'll try that, but there is something fishy here.

**Comment by edurenye** [comment]
That documentation is obsolete apparently.

I got this:
```
AttributeError: module 'tensorflow._api.v2.config' has no attribute 'run_functions_eagerly'
```

**Comment by bhack** [comment]
@edurenye What is you code snippet?

**Comment by edurenye** [comment]
```
import tensorflow as tf

tf.config.run_functions_eagerly(True)

@tf.function
def f(x, y):
    print('Operate')
    return x ** 2 + y

x = tf.constant([2, 3])
y = tf.constant([3, -2])
f(x, y)
```

**Comment by bhack** [comment]
I don't get `AttributeError: module 'tensorflow._api.v2.config' has no attribute 'run_functions_eagerly` with your code. What TF version are you using?

**Comment by edurenye** [comment]
As says in the issue description, I'm using version 2.2.

And seems that this method just exists in Nightly. I can't test right now, but I will when I have time.

But I don't understand why this is needed if TF 2.0 should be eager by default, my guess is that everything is eager except the `tf.function`.

The other thing is that even if is not eager, the debug should stop the breakpoints anyway after the graph is created and during the execution of the code.

**Comment by bhack** [comment]
On TF 2.2 was `tf.config.experimental_run_functions_eagerly(True)`.
I think that point is:
> To get performant and portable models, use tf.function to make graphs out of your programs. 

> When using @tf.function, you can temporarily toggle graph execution by using tf.config.experimental_execute_functions_eagerly. This will effectively run the annotated code eagerly, **without transformation**. Since AutoGraph has semantics consistent with Eager, it's an effective way to debug the code step-by-step.

**Comment by jsimsa** [comment]
Reassigning to @jaingaurav for triage as this is not specific to tf.data.

**Comment by edurenye** [comment]
Thank you very much @bhack !!! It works perfectly.

**Comment by ravikyram** [comment]
@edurenye 

Glad to know it worked. Please close this thread as the issue was resolved. Thanks!

**Comment by edurenye** [comment]
Yes, thank you!

I guess this:

> The other thing is that even if is not eager, the debug should stop the breakpoints anyway after the graph is created and during the execution of the code.

Is not compatible with this:

> To get performant and portable models, use tf.function to make graphs out of your programs.

So I can close this issue.
And I will close the issues from the other projects as well.

Thank you very much everybody that was involved!

**Comment by bhack** [comment]
> The other thing is that even if is not eager, the debug should stop the breakpoints anyway after the graph is created and during the execution of the code

If the code is transformed debugging with the orignal breakpoint doesn't make sense.

**Comment by cgebbe** [comment]
Sorry for hijacking this thread, but the solution does not work for me with tensorflow 2.4.1, pycharm and windows. Using the example posted above and an additional `tf.config.run_functions_eagerly(True)` at the top yields the following error message:

"UserWarning: Even though the tf.config.experimental_run_functions_eagerly option is set, this option does not apply to tf.data functions. tf.data functions are still traced and executed as graphs"
