### ISSUE TITLE
No module named 'tensorflow.python.types' when building estimator from master branch

### ISSUE THREAD

**Issue by Elizaaaaa** [tensorflow/tensorflow#39326]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Lunux Ubuntu 16.04
- TensorFlow installed from (source or binary):
Pip install tensorflow==2.2.0
- TensorFlow version:
2.2.0
- Python version:
3.6
- Installed using virtualenv? pip? conda?:
pip
- Bazel version (if compiling from source):
2.0.0 & 0.25.0
- GCC/Compiler version (if compiling from source):
5.4.0

**Describe the problem**
I'm trying to compile the estimator binary from the tensorflow/estimator master branch, using the bazel commands that listed on the readme page. The building failed with the error:

```
File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/9e73ac3ed666d141725dcd5fe404d502/sandbox/linux-sandbox/2/execroot/org_tensorflow_estimator/bazel-out/host/bin/tensorflow_estimator/python/estimator/api/create_tensorflow_estimator.python.estimator_api_1_estimator_python_api_gen_compat_v1.runfiles/org_tensorflow_estimator/tensorflow_estimator/python/estimator/model_fn.py", line 29, in <module>
    from tensorflow.python.types import core
ModuleNotFoundError: No module named 'tensorflow.python.types'
```

I tried to clean the directory and checkout the `esitimator/r2.2` branch, built with the same environment and command. That build was passed with no error.
Could someone suggest why master branch is having this import issue? Thanks

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
git clone https://github.com/tensorflow/estimator.git
pip uninstall -y tensorflow
pip install tensorflow==2.2.0
bazel build //tensorflow_estimator/tools/pip_package:build_pip_package
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
/home/ubuntu/estimator/tensorflow_estimator/python/estimator/api/BUILD:38:1: Executing genrule //tensorflow_estimator/python/estimator/api:estimator_python_api_gen_compat_v1 failed (Exit 1) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/9e73ac3ed666d141725dcd5fe404d502/sandbox/linux-sandbox/2/execroot/org_tensorflow_estimator/bazel-out/host/bin/tensorflow_estimator/python/estimator/api/create_tensorflow_estimator.python.estimator_api_1_estimator_python_api_gen_compat_v1.runfiles/org_tensorflow_estimator/tensorflow_estimator/python/estimator/api/create_python_api_wrapper.py", line 26, in <module>
    from tensorflow_estimator.python.estimator import estimator_lib  # pylint: disable=unused-import
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/9e73ac3ed666d141725dcd5fe404d502/sandbox/linux-sandbox/2/execroot/org_tensorflow_estimator/bazel-out/host/bin/tensorflow_estimator/python/estimator/api/create_tensorflow_estimator.python.estimator_api_1_estimator_python_api_gen_compat_v1.runfiles/org_tensorflow_estimator/tensorflow_estimator/python/estimator/estimator_lib.py", line 22, in <module>
    from tensorflow_estimator.python.estimator.canned.baseline import BaselineClassifier
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/9e73ac3ed666d141725dcd5fe404d502/sandbox/linux-sandbox/2/execroot/org_tensorflow_estimator/bazel-out/host/bin/tensorflow_estimator/python/estimator/api/create_tensorflow_estimator.python.estimator_api_1_estimator_python_api_gen_compat_v1.runfiles/org_tensorflow_estimator/tensorflow_estimator/python/estimator/canned/baseline.py", line 59, in <module>
    from tensorflow_estimator.python.estimator import estimator
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/9e73ac3ed666d141725dcd5fe404d502/sandbox/linux-sandbox/2/execroot/org_tensorflow_estimator/bazel-out/host/bin/tensorflow_estimator/python/estimator/api/create_tensorflow_estimator.python.estimator_api_1_estimator_python_api_gen_compat_v1.runfiles/org_tensorflow_estimator/tensorflow_estimator/python/estimator/estimator.py", line 51, in <module>
    from tensorflow_estimator.python.estimator import model_fn as model_fn_lib
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/9e73ac3ed666d141725dcd5fe404d502/sandbox/linux-sandbox/2/execroot/org_tensorflow_estimator/bazel-out/host/bin/tensorflow_estimator/python/estimator/api/create_tensorflow_estimator.python.estimator_api_1_estimator_python_api_gen_compat_v1.runfiles/org_tensorflow_estimator/tensorflow_estimator/python/estimator/model_fn.py", line 29, in <module>
    from tensorflow.python.types import core
ModuleNotFoundError: No module named 'tensorflow.python.types'
Target //tensorflow_estimator/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/ubuntu/estimator/tensorflow_estimator/tools/pip_package/BUILD:18:1 Executing genrule //tensorflow_estimator/python/estimator/api:estimator_python_api_gen_compat_v1 failed (Exit 1) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 5.025s, Critical Path: 1.66s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by ymodak** [comment]
`tf.estimator` is installed silently when you install the TensorFlow pip package. So you may skip building tf.estimator package locally.

**Comment by Elizaaaaa** [comment]
> `tf.estimator` is installed silently when you install the TensorFlow pip package. So you may skip building tf.estimator package locally.

hi, we need to modify the estimator source codes before building it. To have our customized estimator binary, the building process cannot be skipped. thanks

**Comment by mihaimaruseac** [comment]
Can you post the output of `pip list` before and after building TF Estimator?

**Comment by Elizaaaaa** [comment]
> Can you post the output of `pip list` before and after building TF Estimator?

hey, sorry for the late reply. the result of pip list is:
~/estimator$ pip list
Package                            Version
---------------------------------- --------------
absl-py                            0.9.0
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.7
anaconda-project                   0.8.3
appdirs                            1.4.4
asn1crypto                         1.3.0
astroid                            2.3.3
astunparse                         1.6.3
atomicwrites                       1.3.0
attrs                              19.3.0
awscli                             1.18.65
Babel                              2.8.0
backcall                           0.1.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
bcrypt                             3.1.7
beautifulsoup4                     4.8.2
bitarray                           1.2.1
bleach                             3.1.0
boto                               2.49.0
boto3                              1.9.162
botocore                           1.16.15
cachetools                         4.1.0
certifi                            2020.4.5.1
cffi                               1.13.2
chardet                            3.0.4
Click                              7.0
cloudpickle                        1.2.2
clyent                             1.2.2
colorama                           0.4.3
conda                              4.8.2
conda-build                        3.18.11
conda-package-handling             1.6.0
conda-verify                       3.4.2
configparser                       5.0.0
contextlib2                        0.6.0.post1
cryptography                       2.8
cycler                             0.10.0
Cython                             0.29.14
cytoolz                            0.10.1
dask                               2.10.1
decorator                          4.4.1
defusedxml                         0.6.0
distlib                            0.3.0
distributed                        2.10.0
docutils                           0.15.2
entrypoints                        0.3
et-xmlfile                         1.0.1
Fabric3                            1.14.post1
fastcache                          1.1.0
filelock                           3.0.12
Flask                              1.1.1
Flask-Cors                         3.0.8
future                             0.18.2
gast                               0.3.3
gevent                             1.4.0
glob2                              0.7
gmpy2                              2.0.8
google-auth                        1.14.2
google-auth-oauthlib               0.4.1
google-pasta                       0.2.0
greenlet                           0.4.15
grpcio                             1.28.1
h5py                               2.10.0
HeapDict                           1.0.1
html5lib                           1.0.1
idna                               2.9
imagesize                          1.2.0
importlib-metadata                 1.5.0
inflect                            4.1.0
ipykernel                          5.1.4
ipython                            7.12.0
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isort                              4.3.21
itsdangerous                       1.1.0
jaraco.itertools                   5.0.0
jdcal                              1.4.1
jedi                               0.16.0
jeepney                            0.4.2
Jinja2                             2.11.1
jmespath                           0.9.4
joblib                             0.14.1
json5                              0.9.0
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     5.3.4
jupyter-console                    6.1.0
jupyter-core                       4.6.1
jupyterlab                         1.2.6
jupyterlab-launcher                0.13.1
jupyterlab-server                  1.0.6
Keras-Preprocessing                1.1.0
keyring                            21.1.0
kiwisolver                         1.1.0
lazy-object-proxy                  1.4.3
libarchive-c                       2.8
lief                               0.9.0
llvmlite                           0.31.0
locket                             0.2.0
lxml                               4.3.0
Markdown                           3.2.1
MarkupSafe                         1.1.1
mccabe                             0.6.1
mistune                            0.8.4
more-itertools                     8.2.0
mpmath                             1.1.0
msgpack                            0.6.1
multipledispatch                   0.6.0
navigator-updater                  0.2.1
nb-conda                           2.2.1
nb-conda-kernels                   2.2.2
nbconvert                          5.4.1
nbformat                           5.0.4
networkx                           2.4
nltk                               3.4.5
nose                               1.3.7
notebook                           6.0.3
numpy                              1.16.0
numpydoc                           0.9.2
oauthlib                           3.1.0
olefile                            0.46
openpyxl                           3.0.3
opt-einsum                         3.2.1
packaging                          20.1
pandocfilters                      1.4.2
paramiko                           2.7.1
parso                              0.6.0
partd                              1.1.0
path                               13.1.0
pathlib2                           2.3.5
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             5.4.1
pip                                20.1.1
pkginfo                            1.5.0.1
pluggy                             0.13.1
ply                                3.11
portpicker                         1.3.1
prometheus-client                  0.7.1
prompt-toolkit                     3.0.3
protobuf                           3.11.3
psutil                             5.6.7
ptyprocess                         0.6.0
py                                 1.8.1
pyasn1                             0.4.8
pyasn1-modules                     0.2.8
pycodestyle                        2.5.0
pycosat                            0.6.3
pycparser                          2.19
pycrypto                           2.6.1
pycurl                             7.43.0.5
pyflakes                           2.1.1
Pygments                           2.5.2
pykerberos                         1.2.1
pylint                             2.4.4
PyNaCl                             1.3.0
pyodbc                             4.0.24
pyOpenSSL                          19.1.0
pyparsing                          2.4.6
pyrsistent                         0.15.7
PySocks                            1.7.1
pytest                             5.0.1
pytest-openfiles                   0.4.0
pytest-remotedata                  0.3.2
python-dateutil                    2.8.1
pytz                               2019.3
PyYAML                             3.13
pyzmq                              17.1.2
QtAwesome                          0.6.1
qtconsole                          4.6.0
QtPy                               1.9.0
requests                           2.23.0
requests-oauthlib                  1.3.0
rope                               0.16.0
rsa                                3.4.2
ruamel-yaml                        0.15.87
s3fs                               0.1.5
s3transfer                         0.2.1
scikit-learn                       0.23.0
scipy                              1.4.1
SecretStorage                      3.1.2
Send2Trash                         1.5.0
setuptools                         46.1.3
shadowsocks                        2.8.2
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.12.0
snowballstemmer                    2.0.0
sortedcollections                  1.1.2
sortedcontainers                   2.1.0
soupsieve                          1.9.5
Sphinx                             2.3.1
sphinxcontrib-applehelp            1.0.1
sphinxcontrib-devhelp              1.0.1
sphinxcontrib-htmlhelp             1.0.2
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.2
sphinxcontrib-serializinghtml      1.1.3
sphinxcontrib-websupport           1.1.2
spyder                             3.3.6
spyder-kernels                     0.5.2
SQLAlchemy                         1.3.13
sympy                              1.5.1
tb-nightly                         2.3.0a20200604
tblib                              1.6.0
tensorboard                        2.2.1
tensorboard-plugin-wit             1.6.0.post3
tensorflow                         2.2.0
termcolor                          1.1.0
terminado                          0.8.3
testpath                           0.4.4
threadpoolctl                      2.0.0
toolz                              0.10.0
tornado                            6.0.3
tqdm                               4.42.0
traitlets                          4.3.3
typing                             3.6.4
unicodecsv                         0.14.1
urllib3                            1.25.9
virtualenv                         20.0.21
wcwidth                            0.1.8
webencodings                       0.5.1
Werkzeug                           1.0.1
wheel                              0.34.2
widgetsnbextension                 3.5.1
wrapt                              1.12.1
wurlitzer                          2.0.0
xlrd                               1.2.0
XlsxWriter                         1.2.7
xlwt                               1.3.0
zict                               1.0.0
zipp                               2.1.0

Thank you

**Comment by mihaimaruseac** [comment]
Hmm, let's try building while you have installed `tf-nightly`. That is, let's try running the following

```
pip uninstall -y tensorflow tensorboard
pip install tf-nightly
# now build estimator from master's branch, probably after a new sync
```

**Comment by Elizaaaaa** [comment]
> Hmm, let's try building while you have installed `tf-nightly`. That is, let's try running the following
> 
> ```
> pip uninstall -y tensorflow tensorboard
> pip install tf-nightly
> # now build estimator from master's branch, probably after a new sync
> ```

Thanks for the suggestion. I've tried to uninstall tensorflow, tensorflow-gpu and tensorboard, then install tf-nightly:
```
ubuntu@ip-172-31-14-213:~/estimator$ pip show tf-nightly
Name: tf-nightly
Version: 2.5.0.dev20200629
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/ubuntu/anaconda3/lib/python3.7/site-packages
Requires: scipy, tf-estimator-nightly, opt-einsum, google-pasta, wrapt, wheel, absl-py, h5py, termcolor, tb-nightly, six, astunparse, gast, numpy, keras-preprocessing, grpcio, protobuf

```

Then fetch and pull the latest estimator/master. Run the build with 
`bazel build //tensorflow_estimator/tools/pip_package:build_pip_package
`
The build failed with a new error:

AttributeError: module 'tensorflow' has no attribute 'compat'

**Comment by Elizaaaaa** [comment]
Full error message:

ubuntu@ip-172-31-14-213:~/estimator$ bazel build //tensorflow_estimator/tools/pip_package:build_pip_package
INFO: Analyzed target //tensorflow_estimator/tools/pip_package:build_pip_package (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/ubuntu/estimator/tensorflow_estimator/BUILD:79:19: Executing genrule //tensorflow_estimator:estimator_python_api_gen_compat_v2 failed (Exit 1) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
2020-06-29 18:42:13.382333: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64/openmpi/lib/:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/mpi/lib:/lib/:/home/ubuntu/src/cntk/bindings/python/cntk/libs:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/mpi/lib:/usr/lib64/openmpi/lib/:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/mpi/lib:/lib/:
2020-06-29 18:42:13.382396: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/9e73ac3ed666d141725dcd5fe404d502/sandbox/linux-sandbox/5/execroot/org_tensorflow_estimator/bazel-out/host/bin/tensorflow_estimator/create_tensorflow_estimator.python.estimator_api_2_estimator_python_api_gen_compat_v2.runfiles/org_tensorflow_estimator/tensorflow_estimator/python/estimator/api/create_python_api_wrapper.py", line 26, in <module>
    from tensorflow_estimator.python.estimator import estimator_lib  # pylint: disable=unused-import
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/9e73ac3ed666d141725dcd5fe404d502/sandbox/linux-sandbox/5/execroot/org_tensorflow_estimator/bazel-out/host/bin/tensorflow_estimator/create_tensorflow_estimator.python.estimator_api_2_estimator_python_api_gen_compat_v2.runfiles/org_tensorflow_estimator/tensorflow_estimator/python/estimator/estimator_lib.py", line 22, in <module>
    from tensorflow_estimator.python.estimator.canned.baseline import BaselineClassifier
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/9e73ac3ed666d141725dcd5fe404d502/sandbox/linux-sandbox/5/execroot/org_tensorflow_estimator/bazel-out/host/bin/tensorflow_estimator/create_tensorflow_estimator.python.estimator_api_2_estimator_python_api_gen_compat_v2.runfiles/org_tensorflow_estimator/tensorflow_estimator/python/estimator/canned/baseline.py", line 59, in <module>
    from tensorflow_estimator.python.estimator import estimator
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/9e73ac3ed666d141725dcd5fe404d502/sandbox/linux-sandbox/5/execroot/org_tensorflow_estimator/bazel-out/host/bin/tensorflow_estimator/create_tensorflow_estimator.python.estimator_api_2_estimator_python_api_gen_compat_v2.runfiles/org_tensorflow_estimator/tensorflow_estimator/python/estimator/estimator.py", line 53, in <module>
    from tensorflow_estimator.python.estimator import util as estimator_util
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/9e73ac3ed666d141725dcd5fe404d502/sandbox/linux-sandbox/5/execroot/org_tensorflow_estimator/bazel-out/host/bin/tensorflow_estimator/create_tensorflow_estimator.python.estimator_api_2_estimator_python_api_gen_compat_v2.runfiles/org_tensorflow_estimator/tensorflow_estimator/python/estimator/util.py", line 75, in <module>
    class _DatasetInitializerHook(tf.compat.v1.train.SessionRunHook):
AttributeError: module 'tensorflow' has no attribute 'compat'
Target //tensorflow_estimator/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/ubuntu/estimator/tensorflow_estimator/tools/pip_package/BUILD:18:10 Executing genrule //tensorflow_estimator:estimator_python_api_gen_compat_v2 failed (Exit 1) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 1.926s, Critical Path: 1.73s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by mihaimaruseac** [comment]
It could be the Bazel cache already contains stale data. Let's give this one more try. Can you run the following commands please (in the clone of Estimator)?

```
bazel clean --expunge
cd ..
rm -rf estimator
python -m virtualenv venv
source venv/bin/activate
pip install tf-nightly
git clone $estimator_repo_url  # fill in with the URL from which you clone
cd estimator
bazel build //tensorflow_estimator/tools/pip_package:build_pip_package &> log.txt
deactivate
```

And then attach `log.txt` in a reply. If possible, also copy-paste the output of all the commands above (which first reset environment to a clean state, then create a virtual environment for python packages to ensure no collusion with system-wide installs, then clones estimator and builds the pip package)

**Comment by minalmeg** [comment]
If you try uninstalling and reinstaling tensorflow-estimator=1.x, it might work. Did for me.

**Comment by Elizaaaaa** [comment]
> It could be the Bazel cache already contains stale data. Let's give this one more try. Can you run the following commands please (in the clone of Estimator)?
> 
> ```
> bazel clean --expunge
> cd ..
> rm -rf estimator
> python -m virtualenv venv
> source venv/bin/activate
> pip install tf-nightly
> git clone $estimator_repo_url  # fill in with the URL from which you clone
> cd estimator
> bazel build //tensorflow_estimator/tools/pip_package:build_pip_package &> log.txt
> deactivate
> ```
> 
> And then attach `log.txt` in a reply. If possible, also copy-paste the output of all the commands above (which first reset environment to a clean state, then create a virtual environment for python packages to ensure no collusion with system-wide installs, then clones estimator and builds the pip package)

building in virtualenv worked. thank you!

**Comment by drcandacemakedamoore** [comment]
Hello.

I've been trying to install TensorFlow with Anaconda on Windows for a few days now. Every version of the 2.x.x branch of TensorFlow is defective, and, is impossible to get running because of import errors.

I landed on this ticket's page because I had to downgrade TensorFlow from 2.3 (2.2. and 2.3 are completely broken and wouldn't work with any CUDA GPUs) to 2.1. And, when trying to run 2.1 version, it is unable to import the estimator because estimator cannot import `tensorflow.python.types`. I looked at the code that requires this package, and I cannot find anything in the entire distribution of the tons of different packages named "tensorflow-something" anything similar to "types.core", as that what's being used actually in the code. 

This ticket was unhelpful in understanding how to solve the problem. Not even in understanding what the problem actually is. I would appreciate some information on what this missing package is, and how to find it, if I'm missing it.

PS. I will not use Bazel to build TensorFlow. It's another extremely broken and convoluted system. I have no faith that going down that path will not just create more problems. I just want to find a distribution that works on Windows 10. Is this too much to ask?

**Comment by FazalUrRehmanFaisal** [comment]
Hi can someone guide me how to resolve this issue.

  from tensorflow_estimator.python.estimator import model_fn
  File "/home/fazal/anaconda3/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/model_fn.py", line 29, in <module>
    from tensorflow.python.types import core
ModuleNotFoundError: No module named 'tensorflow.python.types'

**Comment by minalmeg** [comment]
> ModuleNotFoundError: No module named 'tensorflow.python.types'

Have you tried upgrading pip3 and reinstalling it?

**Comment by ssss806** [comment]
File "C:\Users\ssss\.conda\envs\pointnet-master\lib\site-packages\tensorflow_estimator\python\estimator\model_fn.py", line 29, in <module>
    from tensorflow.python.types import core
ModuleNotFoundError: No module named 'tensorflow.python.types' 
 My version of tensorflow is 1.X and my tensorflow-estimator is also version 1.15.
