### ISSUE TITLE
l2_normalize broken in master

### ISSUE THREAD

**Issue by rafaljozefowicz** [tensorflow/tensorflow#3932]
`tf.nn.l2_normalize(tf.constant(np.ones([2, 2, 2, 2])), [0, 1, 2])` crashes with the following error:
`ValueError: Shape (1, 3) must have rank at most 1`

The problem is that l2_normalize function converts the dimension list into `[[0, 1, 2]]` (double brackets) and it stopped being supported recently. It works fine in 0.10 branch as far as I can tell.

Shorter repro to get the same error:
`tf.reduce_sum(tf.constant(np.ones([2, 2, 2, 2])), [[0, 1, 2]])`

**Comment by vrv** [comment]
Thanks, the bug is in l2_normalize.

tf.reduce_sum is working correctly, the dims argument must be a scalar or a vector.  I'll work on a fix + test
