### ISSUE TITLE
AutoGraph and tf.function are not working for TPU: Resubmitting this issue, because no reply so far for previous thread.

### ISSUE THREAD

**Issue by saahiluppal** [tensorflow/tensorflow#39339]
It seems that TPU only supports keras fit() function, but unable to use functions from tf.function and autographs.

Tensorflow version 2.1
python version 3.6

Issue can be reproduced in colab.

Here's the link to gist.
https://gist.github.com/saahiluppal/0bf79c27a15eaf6a72b25322eae6b6aa

Thanks.

**Comment by Saduf2019** [comment]
I am able to replicate the code shared, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/2b84b4a389373be779f5d0658e4620db/untitled177.ipynb). Thanks!

**Comment by guptapriya** [comment]
When using TPUStrategy, or any distribution strategy without keras model.fit, you need to use a few more strategy methods to distribute your computation. You can see a tutorial here: https://www.tensorflow.org/tutorials/distribute/custom_training

Just replace `MirroredStrategy` in that tutorial with `TPUStrategy` (keep the initialization etc associated w TPUStrategy). The rest of the code should work as-is.

**Comment by saahiluppal** [comment]
This helped me. 
Thanks.
