### ISSUE TITLE
Cannot import EfficientNetB0 from tensorflow.keras.applications

### ISSUE THREAD

**Issue by Hartorn** [tensorflow/tensorflow#39346]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 (docker container)
- TensorFlow installed from (source or binary): binary (using pip) 
- TensorFlow version (use command below):  v2.2.0-rc4-8-g2b96f3662b 2.2.0 (I installed version 2.2.0 from pypi)
- Python version: 3.7.7

**Describe the current behavior**
I cannot import EfficientNetB0 from tensorflow.keras.applications
When listing the module, using `print(dir(tensorflow.keras.applications))`, I can see other applications (like MobileNetV2, ...), but not efficient net or dense net
 This is weird, since here (https://github.com/tensorflow/tensorflow/tree/v2.2.0/tensorflow/python/keras/applications) it's present.

**Describe the expected behavior**
`from tensorflow.keras.applications import EfficientNetB0` should work

**Comment by amahendrakar** [comment]
@Hartorn,
As per the [documentation for EfficientNetB0](https://www.tensorflow.org/api_docs/python/tf/keras/applications/EfficientNetB0). The API is available only in TF-nightly. 

I was able to import EfficientNetB0 without any issues using TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/a977106b48183824373ed2fef510b47c/39346-tf-nightly.ipynb). Thanks!

**Comment by Hartorn** [comment]
Oh sry, did not see this.
Thanks for the answer

**Comment by sumaira78** [comment]
Try this:

from tensorflow.keras.applications.efficient import EfficientNetB0
