### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by senkoraku552** [tensorflow/tensorflow#39357]
I'm trying work with MINIST dataset with tensorflow
but it keep failed to load about the DLL file

**System information**
- WINDOWS 10
- TensorFlow installed : Anaconda (by Prompt)
- TensorFlow version: 2.1.0
- Python version: 3.8.2
- Installed using virtualenv? pip? conda?: Prompt pip
- GPU model and memory: NVIDIA GTX950 4G

ImportError: Traceback (most recent call last):
  File "C:\Users\pc\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\pc\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\pc\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\pc\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\pc\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

I've tried uninstall and reinstall all the pip, tensorflow, pillow
with different kinds of CMD / Conda / Prompt
and it just didn't work and really can't figure out wheres the problem.

**Comment by amahendrakar** [comment]
@senkoraku552,
Python 3.8 does not support Tensorflow v2.1, I'd request you to try installing TensorFlow v2.2 using the below command
`pip install tensorflow==2.2.0`

Also regarding the ImportError, please check [this comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) from a similar issue and let us know if it helps. Thanks!

**Comment by senkoraku552** [comment]
> @senkoraku552,
> Python 3.8 does not support Tensorflow v2.1, I'd request you to try installing TensorFlow v2.2 using the below command
> `pip install tensorflow==2.2.0`
> 
> Also regarding the ImportError, please check [this comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) from a similar issue and let us know if it helps. Thanks!

Thanks! I was never though about the patch thing, I'm gonna try this now!

**Comment by mihaimaruseac** [comment]
Closing as duplicate.

https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

Just to sample over 100 similar issues: #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204

Please make sure you do a search in the future.
