### ISSUE TITLE
tf.strings.join not allowed in graph

### ISSUE THREAD

**Issue by khazit** [tensorflow/tensorflow#39351]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 19.10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.2
- Python version:3.7.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
When writing a function that is mapped on a `tf.data.Dataset`, using `tf.strings.join()` yields the following error
```
OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did not convert this function. Try decorating it directly with @tf.function.
```
Even when using the `@tf.function`

**Describe the expected behavior**
Should work when calling the `@tf.function` decorator

**Standalone code to reproduce the issue**
```
@tf.function
def process_path(path):
    path = tf.strings.split(path, "_")[:3]
    path = tf.strings.join(path, "_")
    return path

path_ds = tf.data.Dataset.list_files(...)
path_ds = path_ds.map(process_path)
```

**Comment by yongtang** [comment]
@khazit `tf.strings.join` expect a list as input, so it should be `tf.strings.join([path, "_"])`.

I will close this issue, but feel free to reopen if you encounter any other issues.

**Comment by khazit** [comment]
@yongtang Thanks for the quick answer but it still doesn't work properly. 

This `tf.strings.join([path, "_"])` gives the following 
`[b'data/cityscapes/train/darmstadt_' b'000035_' b'000019_']` 

My idea was to join every element of the tensor using the "_" separator into a single string. So I'm expecting this `b'data/cityscapes/train/darmstadt_000035_000019'` as an output

**Comment by yongtang** [comment]
@khazit Ah in that case, you need to convert path into lists before the join through tf.unstack:
```
@tf.function(autograph=False)
def process_path(path):
    path = tf.strings.split(path, "_")[:3]
    path = tf.unstack(path, num=3)
    path = tf.strings.join(path, "_")
    return path
```

`num=3` is needed as otherwise tf.unstack will not be able to infer the number of output and join will not work. So `num=3` has to be passed in.

**Comment by khazit** [comment]
Great ! Thank you
I'm closing this issue

**Comment by aidenmccomiskey** [comment]
@yongtang Is there any way to not manually input the number of outputs, i.e. not have to set num=3.  I am trying to do this in a for loop where there are different sizes.
