### ISSUE TITLE
Issue with Python3.8 and Ubuntu 20.04

### ISSUE THREAD

**Issue by markub3327** [tensorflow/tensorflow#39361]
@tensorflow/micro

**System information**
- Ubuntu 20.04 arm64
- TensorFlow installed from (source or binary): https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_aarch64.whl
- Tensorflow version (commit SHA if source): 2.1.0
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33, etc.): Raspberry Pi 3

**Describe the problem**
Please make support for Python 3.8 on Ubuntu 20.04 with Raspberry Pi 3 arm64. I try to install TF Lite with Python 3.8, but it isn't a good version of TF Lite and I read that the TF 2.2.0 works with Python 3.8, but this version I cannot find on the page: https://www.tensorflow.org/lite/guide/python. Thanks.

**Please provide the exact sequence of commands/steps when you ran into the problem**
pip3 install https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_aarch64.whl

**Comment by markub3327** [comment]
Can I build my own python 'whl' file?

Here are instructions only for the C++ static library: https://www.tensorflow.org/lite/guide/build_arm64.
Where are build instructions for Python language (tflite_runtime)?

**Comment by ItsMeTheBee** [comment]
This might help you: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package

**Comment by TylerADavis** [comment]
It looks like the tflite_runtime for AARCH64 on python 3.8 and linux is now available on https://www.tensorflow.org/lite/guide/python per  4a96705. Is this what you were looking for?

https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp38-cp38-linux_aarch64.whl

**Comment by markub3327** [comment]
It's working perfectly. I tested it on a new Raspberry Pi 4 with Ubuntu 20.04 arm64.

Here is the result:
<img width="870" alt="Snímka obrazovky 2020-10-16 o 21 22 09" src="https://user-images.githubusercontent.com/16693449/96300428-ce735080-0ff5-11eb-9011-5a303d5c97ad.png">
