### ISSUE TITLE
Video summary

### ISSUE THREAD

**Issue by act65** [tensorflow/tensorflow#3936]
Hey, 
Just wondering if there are any plans to add video summaries to tensorboard??
Alex

**Comment by aselle** [comment]
@danmane can comment further, but there is work to make tensorboard more extensible so that people could add additional summaries on their own.

**Comment by danmane** [comment]
We're sure to do this eventually, although it's not on the immediate roadmap. As andrew said, we are currently working on a plugin system for TensorBoard.

If any other contributors are interested in working on this, we could get this launched a lot sooner with some help. I'm marking it contributions welcome.

**Comment by falcondai** [comment]
I have done some ad hoc video visualization in the context of video prediction (https://github.com/tensorflow/models/issues/553). I am interested to help implement this as a plugin (much like the embedding visualizer) via GIF (and/or a web-compatible video format).

**Comment by dandelionmane** [comment]
I've migrated this to the TensorBoard repo.
