### ISSUE TITLE
Example create_sine_model.ipynb disappreared 

### ISSUE THREAD

**Issue by quirli** [tensorflow/tensorflow#39362]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): all
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source):  I921176f6a8dc4c76bd45e6a508548d3b1936f89d
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): all

**Describe the problem**
The create_sine_model.ipynb was deleted from the examples. 
There is afaik no new place mentioned, where it can be found.
It is btw the introductory example in Pete Wardens TinyML book. 

**Please provide the exact sequence of commands/steps when you ran into the problem**
Ich checked the github location which is suggested in the book and could't find the example. By searching the last commit, I noticed that it was deleted recently.

**Comment by ymodak** [comment]
You may refer this [notebook link](https://github.com/tensorflow/tensorflow/blob/453399f82c212a676b9510b3dc214c7f86e06d7c/tensorflow/lite/micro/examples/hello_world/create_sine_model.ipynb) however its not on master

**Comment by quirli** [comment]
Well, in principal yes, but then Colab says the following:
<img width="861" alt="grafik" src="https://user-images.githubusercontent.com/10559666/82063230-84471580-96cb-11ea-92fa-0790eff65d57.png">
Hence, in practice I cannot use the version in some other branch.

And furthermore, the **introductory code sample** for a book **dedicated to the topic TensorFlow fpr uC** was deleted  from the master branch. I am not sure if this was intended.

I don't see a reason why this notebook had to be deleted, where it can be found in a subale variant, and furthermore there was also no comment explaining this.

**Comment by dynamicwebpaige** [comment]
Tagging in @petewarden and @dansitu -- would it be possible to add the `create_sine_model.ipynb` example back into the `hello_world` directory?

**Comment by dansitu** [comment]
Thanks @dynamicwebpaige, and sorry about this @quirli! I'm not sure why/how this was deleted, but we'll make sure it is added back ASAP.

**Comment by dansitu** [comment]
Update: Looks like it was moved into this subfolder:

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/hello_world/train

**Comment by quirli** [comment]
Ah, ok, thanks! I didn't see that one.
I will close this one, however, some sort of note will probably be nice for future users.

**Comment by dansitu** [comment]
Thanks for reporting, agreed that we should redirect folks somehow!

**Comment by mazurick** [comment]
I'm on Chapter 3 and I can't find the sine example for notebooks.

**Comment by mazurick** [comment]
@dynamicwebpaige, ^^

**Comment by dansitu** [comment]
@mazurick It was moved into this subdirectory:

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/hello_world/train

**Comment by magdaralcheva** [comment]
The file is not there either must of moved again

**Comment by dansitu** [comment]
All of the TensorFlow Lite for Microcontrollers files got moved to a new, separate repository, so you can find the file here:

https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/examples/hello_world/create_sine_model.ipynb

Warmly,
Dan

**Comment by tinyBrkML** [comment]
When I go to that link, it isn't able to display the file.
![Screenshot 2022-12-21 125824](https://user-images.githubusercontent.com/120507146/208972721-d9294c19-1897-49ad-a5b2-3174a3b8a764.png)

**Comment by crazyelectron-io** [comment]
It looks like all the example notebooks from the TinyML book are gone. They are not in the new repo/location either, just the Python source files.

I just bought this book for EUR 49 and now I'm stuck at page 34...
@petewarden any suggestions?

**Comment by dansitu** [comment]
I'm sorry you are having trouble with this! Neither Pete nor I are at Google any more and it appears they've removed the notebooks in favor of Python scripts.

That said, the URL-shortened links in the book all point to files at specific commits in the repository, so they should continue to be available unless the repository is deleted. For example, in chapter 4 the "load the notebook" link here opens the correct file:

<img width="753" alt="image" src="https://github.com/user-attachments/assets/8ccbc521-55c5-4ae0-83c2-3ace006f4e4d">

The short-link in the book, which should be the same in both printed and ebook editions: https://oreil.ly/NN6Mj

The link it resolves to: https://colab.research.google.com/github/tensorflow/tflite-micro/blob/18aec279a0f35af82e4543feae00e1c87a75c8bf/tensorflow/lite/micro/examples/hello_world/train/train_hello_world_model.ipynb

The Wakeword and Magic Wand chapter notebook links from the book both work fine for me:

https://github.com/tensorflow/tensorflow/blob/be4f6874533d78f662d9777b66abe3cdde98f901/tensorflow/lite/experimental/micro/examples/micro_speech/train_speech_model.ipynb

https://github.com/tensorflow/tensorflow/blob/be4f6874533d78f662d9777b66abe3cdde98f901/tensorflow/lite/experimental/micro/examples/magic_wand/train/train_magic_wand_model.ipynb

Is there a specific link in the book that isn't working for you?

**Comment by crazyelectron-io** [comment]
Thanks for your extensive answer.
I should have taken a little bit more time to understand the concept of Notebooks and how Google Colab works before diving head-first into running the first examples from the book, eager to learn about ML. This turned out to be a user error.

There are some small issues with running some of the examples, mostly related to updated TensorFlow versions that can be fixed.

Sorry for waisting your time on this!
