### ISSUE TITLE
ImportError: cannot import name 'export_saved_model' from 'tensorflow.python.keras.saving.saved_model'

### ISSUE THREAD

**Issue by sohamsahare123** [tensorflow/tensorflow#39367]
I tried reinstalling Tensorflow as pip install tensorflow and Keras too by pip install keras
But still i get the same ImportError

Please help me out, Thank you.

**Comment by ravikyram** [comment]
@sohamsahare123 

Can you please provide the code before running into the problem.Also, include your operating system and Tensorflow version.Please, fill [issue template.](https://github.com/tensorflow/tensorflow/issues/new/choose)Thanks!

**Comment by shivamjadhav-alfa** [comment]
i have installed  packages using "conda install tensorflow" but in spyder when i am trying to  imports that getting the import error "export_saved_model"

**Comment by shivamjadhav-alfa** [comment]
please help me out!!! ASAP

**Comment by HEKMATTAHERINEJAD** [comment]
The same issue here! I get error both on Windows and on Ubuntu 20.04 .

**Comment by Faiza-K** [comment]
I have the same issue

**Comment by uchihatashi** [comment]
guys, i have the same problem but finally, it got solved by removing and installing tensorflow and  
then restarting the kernel...
!pip uninstall -y tensorflow
!pip install tensorflow

**Comment by sohamsahare123** [comment]
After reinstalling 4-5 time and restarting it worked.
Thank you all.
