### ISSUE TITLE
[Docs] Inconsistencies with Keras Applications preprocess_input

### ISSUE THREAD

**Issue by swghosh** [tensorflow/tensorflow#39360]
The latest [keras.io](https://keras.io) website includes a whole bunch of great examples and tutorials that could help users get started with deep learning, transfer learning and combines all the goodness that comes in around with the TF 2.x support for keras.

1. https://keras.io/guides/transfer_learning/
2. https://www.tensorflow.org/tutorials/images/transfer_learning

## Description of documentation issue:
One of the major setbacks that I observed was brought in by the transfer learning examples portraying use of data augmentation involving the newly added `Resize()` and `Rescaling()` (rescaling the data from a range of 0-255 to 0.0-1.0, specific case for Xception in [1.](https://keras.io/guides/transfer_learning/) and -1.0-+1.0, specific case for MobileNetV2 in [2.](https://www.tensorflow.org/tutorials/images/transfer_learning)) layers from `tf.keras.layers.experimental` as per the latest keras RFC on Preprocessing Layers API. This is indeed a well planned transition and beneficial for users to switch to tf.data API instead of the `keras.preprocessing.image.ImageDataGenerator` in favour of performance and reducing training bottlenecks.

A majority of the users still are using the ImageDataGenerator class with pre-trained models from keras-applications instead of the new `tf.keras.preprocessing.image_dataset_from_directory` or tf.data API(s) directly. Most likely, with the use of the `preprocessing_function` argument to ImageDataGenerator objects.

eg.
```python3
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet_50 import preprocess_input
datagen = image.ImageDataGenerator(preprocessing_function=preprocess_input)
```

The new documentation encourages use of tf.data API(s) exclusively which lacks consistency with this type of legacy image preprocessing used. As a result of various pre-trained models of keras_applications being ported from a variety of frameworks apart from TensorFlow, each specific keras_applications model requires it's own way of preprocessing images. The currently available ones being: 
https://github.com/tensorflow/tensorflow/blob/de5b0cfd434c7a9f848ab100b70a6be16e48280b/tensorflow/python/keras/applications/imagenet_utils.py#L72-L83
This makes it necessary for each of the pre-trained ConvNet(s) that form of a part of the keras_applications repo, be documented relating to which pre-trained model requires which type of preprocessing whatsoever and specifically how the same can be achieved using the newer Preprocessing Layers API or directly by chaining it with `ds.map()`.

A workaround in this regard would be to:
- update the newly created [keras-io repo](https://github.com/keras-team/keras-io) to document preprocessing method for each pre-trained model. [*please mention in comments if a corresponding Issue has to be filed in that repo*]
- introduce changes to `tf.keras` and the `tf.keras.layers.experimental.preprocessing` for creating new classes that can help serve this goal
- adding some documentation in place to explicitly specify use of respective `preprocess_input` with `ds.map`

/cc: @fchollet Is there any RFC in this regard proposed by the TensorFlow community to unify legacy preprocess_input functions with the newer Preprocessing Layers API?

**Comment by swghosh** [comment]
Hi,

Any updates on this?

@tanzhenyu Can we look into this as a part of our project as well?

**Comment by tanzhenyu** [comment]
> Hi,
> 
> Any updates on this thread?
> 
> /cc: @tanzhenyu Can we look into this?

I think this is already fixed

**Comment by swghosh** [comment]
Okay okay.
