### ISSUE TITLE
bazel build; encountered error while reading extension file 'swift/repositories.bzl': no such package '@build_bazel_rules_swift//swif

### ISSUE THREAD

**Issue by louiselumapas** [tensorflow/tensorflow#39363]
**System information**
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from: source
- TensorFlow version: 1.14.0
- Python version:3.7.7
- Installed using virtualenv? pip? conda?: conda
- Bazel version: 0.24.1
- trying to build tensorflow cpu not gpu 

I followed the intructions and based my versions found here: https://www.tensorflow.org/install/source#tested_build_configurations

**Describe the problem**
When i run the command
``` bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package ``` it gives the following error: 

```
Starting local Bazel server and connecting to it...
ERROR: error loading package '': Encountered error while reading extension file 'swift/repositories.bzl': no such package '@build_bazel_rules_swift//swift': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_swift/releases/download/0.9.0/rules_swift.0.9.0.tar.gz] to /home/domingo_cm/.cache/bazel/_bazel_domingo_cm/f08b2f8b39197d5a57f7b557c17f0caf/external/build_bazel_rules_swift/rules_swift.0.9.0.tar.gz: Unknown host: github.com
ERROR: error loading package '': Encountered error while reading extension file 'swift/repositories.bzl': no such package '@build_bazel_rules_swift//swift': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_swift/releases/download/0.9.0/rules_swift.0.9.0.tar.gz] to /home/domingo_cm/.cache/bazel/_bazel_domingo_cm/f08b2f8b39197d5a57f7b557c17f0caf/external/build_bazel_rules_swift/rules_swift.0.9.0.tar.gz: Unknown host: github.com
INFO: Elapsed time: 14.145s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. git clone https://github.com/tensorflow/tensorflow.git
2. cd tensorflow
3. git checkout r1.14
4. ./configure
5. (assuing bazel is installed ) bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
I am running under a corporate proxy network if it gives any importance
Also, git version is 2.17.1 (latest in Ubuntu 18.04)

**Comment by amahendrakar** [comment]
@louiselumapas, 
Could you please check if you are able to build the package with the proxy disabled. Thanks!

**Comment by louiselumapas** [comment]
I am running under a company corporate proxy and i don’t think i can disable it anytime and i’m not allowed to.

**Comment by ymodak** [comment]
Since you are using `conda` for installing TF please post this issue on [ContinuumIO
/anaconda-issues.](https://github.com/ContinuumIO/anaconda-issues/issues) for official support.
Apologies for redirecting.
Thanks!
