### ISSUE TITLE
Failed to compile TF 1.15.2 from source code

### ISSUE THREAD

**Issue by amir28** [tensorflow/tensorflow#39372]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): want install tensorflow from source
- TensorFlow version: 1.15.2
- Python version: 3.8.2
- Installed using virtualenv? pip? conda?: -
- Bazel version (if compiling from source): bazel 0.26.1
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: -
- GPU model and memory: GPU: - Memory: 4GB

**Describe the problem**

Hello, I wanted to build TensorFlow 1.15.2 from source to works with my old non AVX supported CPU( Intel Pentium(R) Dual-Core E5300 2.60GHz). I looked [TensorFlow community wheels](https://github.com/yaroslavvb/tensorflow-community-wheels/issues) but not found any TF 1.15.2 with Python 3.8.2 and  without AVX support.

I just downloaded [TF 1.15.2 source code from github release](https://github.com/tensorflow/tensorflow/archive/v1.15.2.tar.gz), Extract it, According to [here](https://www.tensorflow.org/install/source) I installed dependencies and ...

```
$ ./configure
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.26.1 installed.
Please specify the location of python. [Default is /usr/bin/python3]: 


Found possible Python library paths:
  /usr/local/lib/python3.8/dist-packages
  /usr/lib/python3/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python3.8/dist-packages]

Do you wish to build TensorFlow with XLA JIT support? [Y/n]: 
XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: 
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: 
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: n
Clang will not be downloaded.

Do you wish to build TensorFlow with MPI support? [y/N]: 
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=gdr         	# Build with GDR support.
	--config=verbs       	# Build with libverbs support.
	--config=ngraph      	# Build with Intel nGraph support.
	--config=numa        	# Build with NUMA support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
	--config=v2          	# Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=noaws       	# Disable AWS S3 filesystem support.
	--config=nogcp       	# Disable GCP support.
	--config=nohdfs      	# Disable HDFS support.
	--config=noignite    	# Disable Apache Ignite support.
	--config=nokafka     	# Disable Apache Kafka support.
	--config=nonccl      	# Disable NVIDIA NCCL support.
Configuration finished
```
an strange error throws durring compile: /usr/bin/python not found :|
you can see in configure file I selected to use /usr/bin/python3 file so I don't know why it want that file.
`ln -s /usr/bin/python3 /usr/bin/python` silents the error but after 30 min another error occurred. I saved the details of the second error in [here](https://drive.google.com/open?id=12PtN4_7W6I1x6lS1ypT48ujmuXIecNQ8).

**Comment by ravikyram** [comment]
@amir28 

With Python 3.8 you cannot install TF-1.15, please downgrade python to 3.7 and it should work fine.
(python3.8 is not supported in TF before 2.2).

Please check on pypi, there are no files available for cp38 for 1.15, Only the versions listed by command have (i.e 2.2.0rc1 to rc4) a cp38 whl file available [here.](https://pypi.org/project/tensorflow/2.2.0rc4/#files).Thanks!

**Comment by amir28** [comment]
Thanks to reply
I another question maybe a little not related to this issue, If I compile master branch using `bazel build --config=opt --config=v1` it will compile lastest version of TF 1.x?
I'll downgrade to put 3.7 but It could be great if it works with py 3.8+. Correctly I can't use TF 2.x.
Thanks a lot.

**Comment by ravikyram** [comment]
@amir28 

Can you please raise a new issue by filling the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose) and close this issue here.Thanks!

**Comment by amir28** [comment]
Yes, of course.

**Comment by mihaimaruseac** [comment]
@amir28 yes, passing `--config=v1` will always build the V1 API and behavior. But note that we no longer test and support those from master.

**Comment by amir28** [comment]
Thanks, but between download and compile lastest release (2.x) with `--config=v1` and download and compile lastest 1.x release which one is suggested (which is better)?
