### ISSUE TITLE
Unstack a ragged tensor stacked by the tf data api

### ISSUE THREAD

**Issue by tanguycdls** [tensorflow/tensorflow#39375]
**System information**
- TensorFlow version (you are using): 2.2
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.**
For efficiency reason when saving my structured data as a tf records i save batches of input instead of only a row. 
My dataset contains mixtures of Ragged inputs and lists. 
Each tf Example contains a batch of N rows (here 10) batched together:

```
{'test': int64_list {
   value: 1
   value: 3
   value: 9
   value: 1
 }, 'test_offset': int64_list {
   value: 0
   value: 0
   value: 0
   value: 0
   value: 0
   value: 0
   value: 3
   value: 4
   value: 4
   value: 4
   value: 4
 }}
```
That i then parse using: 
```
features =  { 
       'test': tf.io.RaggedFeature(value_key='test', dtype=tf.int64, partitions=[ 
                tf.io.RaggedFeature.RowSplits(f"test_offset")])}
def mapper(ex):
    return tf.io.parse_single_example(ex, features)
res = dataset.map(mapper).batch(2)
```
When opening back the batches I want to batch them with another batch size for shuffling reasons. 
If I try to batch with size 2 the resulting tensor will be a ragged tensor of shape (2, None, None). 

Instead I would like to have a shape (N*2, None). I managed to get that tensor by doing : 

```
x = next(iter(re))
tf.concat([x[0], x[1]], axis=1)
```

splitting should be the same as `tf.unstack(x, axis=1)` which does not work and break on a 

> TypeError: object of type 'RaggedTensor' has no len()

**Will this change the current api? How?**
Provide a way of unstacking ragged tensors to be able to stack them properly. 

**Who will benefit with this feature?**
Users of ragged features

**Any Other info.**
google colab: 
https://colab.research.google.com/gist/tanguycdls/f52dbd48a7c17ce282c82f91cd7547a6/untitled11.ipynb

**Comment by edloper** [comment]
I think that you can do what you want here just using `tf.Dataset.batch()` and `tf.Dataset.unbatch()` -- you shouldn't need to use `tf.unstack`.  Here's my attempt to reproduce your example, without having to mess with the io_example stuff:

```
B = 6
N = 4

# shape = [B, N, None]
rt = tf.ragged.constant(
    [[[1], [5, 7], [], []],
     [[], [], [3, 2, 1], []],
     [[], [], [], []],
     [[], [], [18], []],
     [[], [9, 9, 22], [], []],
     [[5], [5], [5], [5]]]
)

ds = tf.data.Dataset.from_tensor_slices({'test': rt})
print("Original dataset: each item has shape [N, None]")
for item in ds: print(item)

batched = ds.batch(2)
print("Batched dataset: each item has shape [2, N, None]")
for item in batched: print(item)

rebatched = ds.unbatch().batch(2*N)
print("Rebatched dataset: each item has shape [2*N, None")
for item in rebatched: print(item)
```

So if you want to rebatch the dataset from size [2, None] to size [2*N, None], just unbatch it, and then batch it again.

If you did need to use `tf.unstack()` for some reason: it looks like it hasn't been implemented for ragged tensors yet; but I don't think it should be hard to implement.  Something like this:

```
def ragged_unstack(value, num=None, axis=0):
  if num is None:
    num = value.shape[axis]
  leading_slices = (Ellipsis,) * axis
  return [value.__getitem__(leading_slices+(i,)) for i in range(num)]
```

**Comment by tanguycdls** [comment]
Thanks @edloper, Unbatch works but i'm concerned about the performance of it. I tried to use your ragged_unstack but i'm not able to use it in tf data api using a map because `value.shape[0]`will be None when graphing the function.

```
res = dataset.map(mapper).batch(2).map(lambda x: x['test']).map(ragged_unstack)
tensor = next(iter(res))['test']
```
> return _py_range(start_or_stop, stop, step)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/operators/py_builtins.py:351 _py_range
        return range(start_or_stop)
TypeError: 'NoneType' object cannot be interpreted as an integer

I fixed the issue by passing num as a parameter (here default to two):

````
def ragged_batch(value, num=2, axis=0):
  if num is None:
    num = value.shape[axis]
  leading_slices = (Ellipsis,) * axis
  return tf.concat([value.__getitem__(leading_slices+(i,)) for i in range(num)], axis=0)
````

Is it possible to use a for loop inside tf data map without having to provide the number manually or the fact its a graph forbids that usage ? 

Thanks,

**Comment by edloper** [comment]
What's the performance issue with `unbatch`?

As for the shape of the batch dimension, I would expect it to preserve that info when we do batching, but it looks like it's not being preserved for some reason:

```
>>> ds = tf.data.Dataset.from_tensor_slices(tf.ragged.constant([[1, 2], [3]]))
>>> batched = ds.batch(2)
>>> print(ds.element_spec)
RaggedTensorSpec(TensorShape([None]), tf.int32, 0, tf.int64)
>>> print(batched.element_spec)
RaggedTensorSpec(TensorShape([None, None]), tf.int32, 1, tf.int64)
```

I would expect batched.element_spec's shape to be `[2, None]`.  In particular, the internal method that adds a batch dimension to the TensorSpec preserves it:

```
>>> ds.element_spec._batch(2)
RaggedTensorSpec(TensorShape([2, None]), tf.int32, 1, tf.int64)
```

I'll look into why that dimension size is getting dropped.

**Comment by edloper** [comment]
Looking at the code, I now remember that the shape isn't guaranteed to be statically fixed unless you pass `drop_remainder` when batching the dataset.  (In particular, the last element may have a shorter length than all the others.)  This works, using my `ragged_unstack`:

```
>>> batched = ds.batch(2, drop_remainder=True)
>>> res = batched.map(lambda x: x['test']).map(ragged_unstack)
>>> print(next(iter(res)))
(<tf.RaggedTensor [[1], [5, 7], [], []]>, <tf.RaggedTensor [[], [], [3, 2, 1], []]>)
```

**Comment by tanguycdls** [comment]
Thanks for the drop_remainder you're right it does not make any sense without it, it now works.

> What's the performance issue with unbatch?

I did some benchmarks between .unbatch().batch() and my method with each row in the TF records being a batch of 10^5 items. In prediction mode i want to score a very large batch at a time here i set it to 20*10^5. 
With unbatch:
````
%%time
res = dataset.map(mapper).unbatch().batch(20*10**5 , drop_remainder=True)
tensor = next(iter(res))['test']
print(tensor.shape)
tensor
````
> 2.92 s

````
def ragged_batch(value, num=None, axis=0):
  value = value['test']
  if num is None:
    num = value.shape[axis]
  leading_slices = (Ellipsis,) * axis
  return tf.concat([value.__getitem__(leading_slices+(i,)) for i in range(num)], axis=0)

%%time
# method where we concatenate the ragged right away.
res = dataset.map(mapper).batch(2*10, drop_remainder=True).map(ragged_batch)
tensor = next(iter(res))
print(tensor.shape)
tensor
````
> 1.47 s

did the benchmark on collab here: https://colab.research.google.com/gist/tanguycdls/419484dda4d8ab9610eeb19e6823d52e/untitled11.ipynb#scrollTo=Wv8zOzIv457n

If you save your tf record with each row being 10^4 the difference is not that clear so it might not worth it. I dont know how tf unbatches and batches back ragged inputs but i think it might be costly if the offsets array needs to be fully recalculated.

Thanks

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
