### ISSUE TITLE
tf.keras.Model does not support `*` in call method signature.

### ISSUE THREAD

**Issue by aidangomez** [tensorflow/tensorflow#39387]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- TensorFlow version (use command below): latest
- Python version: 3.7

**Describe the current behavior**
A tf.keras.Model will fail if the call method signature includes the `*` named argument only identifier from Python 3.7. (and if python 3.8 is supported by TF then it should also support the `/` identifier)

https://docs.python.org/3.7/reference/compound_stmts.html#function-definitions

**Describe the expected behavior**
Should be robust to the use of these indentifiers

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1-5-BygHPbpuBlOXNme2PEKsFqyfG6jvl?usp=sharing

**Other info / logs** 
N/A

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/c44c3ac0461260927d892fbd5f7974e8/untitled875.ipynb).Thanks!

**Comment by karmel** [comment]
Huh. Well, I've learned something today. We have not yet considered adding support for these new symbols. If you are interested in doing so, please consider putting together an [RFC](https://www.tensorflow.org/community/contribute/rfc_process), as I'm sure there is a wider community discussion to be had here.
