### ISSUE TITLE
After upgrade protobuf for the 64Mb limited , segment fault occurred

### ISSUE THREAD

**Issue by haibarasiao** [tensorflow/tensorflow#3938]
After doing "pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/protobuf-3.0.0b2.post2-cp27-none-linux_x86_64.whl" as said in "https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#protobuf-library-related-issues"
, my tensorflow did not work and got a segment fault after import tensorflow.
Could some one give me a right pip install version of >64MB limited protobuf?Thanks!

**Comment by prb12** [comment]
Please can you provide the OS and software version information and exact command lines you used, as requested in the TensorFlow issues template.

**Comment by haibarasiao** [comment]
@prb12 
CentOS Linux release 7.2.1511 (Core) 
tensorflow 0.8.0
python 2.7
protobuf-3.0.0-beta-2
used commond:
1
pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl
2
pip uninstall protobuf
3
sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/protobuf-3.0.0b2.post2-cp27-none-linux_x86_64.whl

After doing this , I got the segment fault when import tensorflow.

**Comment by haibarasiao** [comment]
@prb12 
CentOS Linux release 7.2.1511 (Core)
tensorflow 0.8.0
python 2.7
protobuf-3.0.0-beta-2
used commond:
pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl
pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/protobuf-3.0.0b2.post2-cp27-none-linux_x86_64.whl

After doing this , I got the segment fault when import tensorflow.

**Comment by prb12** [comment]
Not sure what to suggest.
Have you tried using a more recent version of TensorFlow?  (e.g. 0.9 or 0.10rc ?)
Does the output of `pip show protobuf` look like this:
```
~/tensorflow.triage$ pip show protobuf
---
Name: protobuf
Version: 3.0.0b2
Location: /usr/local/lib/python2.7/dist-packages
Requires: six, setuptools
```
You're definitely running your tensorflow program with python 2.7 not accidentally using python 3 ?  (in which case you'd need to **pip3** install the protobuf package)

@martinwicke Any ideas?

**Comment by martinwicke** [comment]
keveman@, do we have to upgrade the pre-built protobuf to 3.0.0 now that we're on 3.0.0 (no beta) for our repo and the binaries are built with it?

**Comment by aselle** [comment]
@keveman, any update? @haibarasiao any luck solving this on your own?

**Comment by haibarasiao** [comment]
no good solving, I have to reduce the number of weights to solve it.

**Comment by gunan** [comment]
I am assuming now this issue is obsolete.
@haibarasiao are you still running into this?

**Comment by haibarasiao** [comment]
no，I use mxnet now. 
------------------ Original ------------------
