### ISSUE TITLE
TF 2.1.0 doesn't recognize GPU, PyTorch does

### ISSUE THREAD

**Issue by CodeJjang** [tensorflow/tensorflow#39386]
**System information**
- Windows 10 home
- TensorFlow version: 2.1.0
- Python version: 3.7.7
- Installed using conda
- CUDA/cuDNN version: CUDA is 10.1, cuDNN is 7.6.5
- GPU model and memory: GeForce GTX 960

**Describe the problem**
TF 2.1.0 doesn't recognize my GPU.
I've double and triple checked the versions of CUDA, cuDNN and everything is matching.  
I have set the environment variables as required in the end of TF installation, and checked that they are exposed in my code.  
In addition, **PyTorch do recognize and able to use my GPU**.  
I also tried installing `tf-nightly`, without help.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
The following prints 0:
```
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
```

**Comment by jvishnuvardhan** [comment]
@CodeJjang Can you please check whether [this](https://github.com/tensorflow/tensorflow/issues/38007#issuecomment-618210369) can help you. Are you running any other code on GPUs while you executed `list_physical_devices`? Thanks!

**Comment by CodeJjang** [comment]
@jvishnuvardhan This looks more related to multi GPU thing and not my case.  
In my case, PyTorch identifies it fine, and TF doesn't.
And yes, some other code is running on the GPU, mainly code related to display.

**Comment by jvishnuvardhan** [comment]
@CodeJjang Can you please check with `TF2.2` and let us know whether it detects or not. Thanks!

**Comment by Saduf2019** [comment]
@CodeJjang 
Could you please verify on latest stable tf version if this is still an issue.
