### ISSUE TITLE
Can't install Tensorflow v1.15 with pip

### ISSUE THREAD

**Issue by tobico** [tensorflow/tensorflow#39380]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.15
- Python version: 3.8.1
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

I'm unable to install v1.15 (or any version older than 2.2.0) using pip

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Run command: `pip install tensorflow==1.15`

Results in the error:
```
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0)
ERROR: No matching distribution found for tensorflow==1.15
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

[Verbose log](https://github.com/tensorflow/tensorflow/files/4605851/pip-log.txt)

**Comment by Saduf2019** [comment]
@tobico 
Is there any particular reason for installing an older version of tensorflow when there are later versions available.
For the issue reported,could you please refer to the [comments here](https://github.com/tensorflow/tensorflow/issues/34302#issuecomment-571183939) and let us know if it helps.

- With Python 3.8 you cannot install TF-1.15,  please downgrade python and try (python3.8  is not supported in TF before 2.2)

**Comment by jyrj** [comment]
User was trying to use python 3.8, which was not officially supported when tensorflow was at version 1.15. After installation of python 3.7, problem was resolved.

Please check on pypi, there are no files available for cp38 for 1.15, Only the versions listed by command have (i.e 2.2.0rc1, 2.2.0rc2) a cp38 whl file available [here](https://pypi.org/project/tensorflow/2.2.0rc1/#files).

**Comment by egmtalo** [comment]
Icould neither install Tensorflow 2 using python 38{

Here is the problem stack

PS C:\Users\mtalo> python
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "C:\Users\mtalo\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py",
 line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\mtalo\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_inte
rnal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\mtalo\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_inte
rnal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\mtalo\AppData\Local\Programs\Python\Python38\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\mtalo\AppData\Local\Programs\Python\Python38\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mtalo\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\__init__.py", line 41, in <mo
dule>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\mtalo\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\__init__.py", line 50,
 in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\mtalo\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py",
 line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\mtalo\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py",
 line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\mtalo\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_inte
rnal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\mtalo\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_inte
rnal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\mtalo\AppData\Local\Programs\Python\Python38\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\mtalo\AppData\Local\Programs\Python\Python38\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by jyrj** [comment]
Best solution is just downgrading your tensorflow using
```pip install tensorflow==2.0```

**Comment by mihaimaruseac** [comment]
@tobico: you need to use Python3.7, (3.6, 3.5 also work) for that, not Python3.8, as @jyrj mentioned in the first comment

@egmtalo solution is in https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156 and many duplicate issues: #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204. No need to downgrade as @jyrj mentions in the last comment

**Comment by mihaimaruseac** [comment]
Closing since this is not a coding issue but a tool usage one.

**Comment by egmtalo** [comment]
Thanks Mihai,

Will replace python 3.8 with 3.7 version

Mtalo EG

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by shubhambagwari** [comment]
make sure you are using python 3.7 version. You can also refer to [here](https://stackoverflow.com/questions/52584907/how-to-downgrade-python-from-3-7-to-3-6)

**Comment by yuzuo** [comment]
I use python 3.9.16 and pip tensorflow with cmd "pip install -i https://pypi.python.org/simple  tensorflow==1.15.0" in virtualenv, but still get this error!

**Comment by mihaimaruseac** [comment]
@yuzuo: https://github.com/tensorflow/tensorflow/issues/39380#issuecomment-968560824 (the comment just above yours)
