### ISSUE TITLE
Tflite Heaxgon delegate - incompatible library

### ISSUE THREAD

**Issue by yakovdan** [tensorflow/tensorflow#39382]
I am going through the example [here](https://www.tensorflow.org/lite/performance/hexagon_delegate#hexagon_delegate_c_api) and having trouble building the binary to due to a link error:
"skipping incompatible C:/REPOSITORIES/tflite/v2.2.0/arm64-v8a/libhexagon_nn_skel.so when searching for -lhexagon_nn_skel". The error is repeated for libhexagon_nn_skel_v65 and libhexagon_nn_skel_v66 as well.

The device architecture is arm64-v8a.

I'm building the example as a part of a larger project which already uses TFlite on GPU successfully. I'm building using ndk-build, so the build.grade file is irrelevant. What should I replace it with? What else I might be doing wrong?

**Comment by yakovdan** [comment]
just noticed that the .so libraries provided are 32 bit. Do you have a 64 bit version?

**Comment by yakovdan** [comment]
to clarify, my intention is to use this as part of native c++ code

**Comment by karimnosseir** [comment]
@yakovdan What is the problem you're facing.
You just need to package the provided libraries with your app

**Comment by yakovdan** [comment]
My build was configured for the target arm64-v8a instead of armeabi-v7a which caused the previous issue. Is there a version of those libraries for arm64-v8a? 
In the mean time, I switched to armeabi-v7a and created a simple native activity project in android studio. Then I followed the provided example precisely and got a link error:

error: undefined reference to 'TfLiteHexagonDelegateDelete'

TfLiteHexagonDelegateDelete is declared in hexagon/hexagon_delegate.h, and defined in hexagon/hexagon_delegate.cc. Am I supposed to build hexagon_delegate.so using bazel and package it with my app? I've already added libtensorflowlite.so to the makefile. 

See attached my CMakeLists.txt
[CMakeLists.txt](https://github.com/tensorflow/tensorflow/files/4645427/CMakeLists.txt)

**Comment by yakovdan** [comment]
For you convenience,  the entire project is attached
[HelloJNI3.zip](https://github.com/tensorflow/tensorflow/files/4645510/HelloJNI3.zip)

**Comment by karimnosseir** [comment]
The easiest might be to fetch the nightly build see [hexagon_delegate guide](https://www.tensorflow.org/lite/performance/hexagon_delegate)

Another way, you can build the libraries yourself using bazel
* hexagon_delegate static library
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/delegates/hexagon/BUILD#L70
* libtensorflowlite_hexagon_jni.so (shared library)
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/delegates/hexagon/java/BUILD#L13
* libhexagon_interface.so:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/delegates/hexagon/hexagon_nn/BUILD#L34


For your issue with TfLiteHexagonDelegateDelete, looks like you are missing link to the hexagon_delegate library.

**Comment by yakovdan** [comment]
I did as you suggested. Now I have a bunch of error of the following form:
tensorflow/lite/experimental/delegates/hexagon/hexagon_delegate.cc:231: error: undefined reference to 'tflite::HexagonDelegateKernel::InitState()'

I went ahead and manually built all the dependent libs and added them statically. This works. Is there a better way?

**Comment by yakovdan** [comment]
Also, I need to switch the target from armeabi-v7a to arm64-v8a. What should I do except recompile the libs for arm64?

**Comment by karimnosseir** [comment]
Using shared library is easier. You will need to load the .so file and call the needed functions.

**Comment by yakovdan** [comment]
Ok, this works. 
What about compiling for arm64-v8a? just recompile the shared library for arm64-v8a and that's it?

**Comment by karimnosseir** [comment]
If you're using the prebuilt we already provide arm 64 and 32. If you're building them just pass --config=android_arm64

**Comment by yakovdan** [comment]
I verified that this works, for arm64 too. Can you explain how this works, since libhexagon_nn_skel* are 32bit libraries?

**Comment by karimnosseir** [comment]
libhexagon_nn_skel* are compiled for hexagon hardware and not Arm. You don't need to worry about them. As long as they are in correct place the delegate will load them.

Thanks
