### ISSUE TITLE
transfer learning for speech recognition ( short word vocabulary)

### ISSUE THREAD

**Issue by krishnabairavi95** [tensorflow/tensorflow#39388]
Dear Authors, 

I am trying to apply transfer learning for my dataset looking into the blog posted: 
https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/sequences/audio_recognition.md
Is there a way to download the pertained checkpoints and load it for further training? 

Thank you so much team TF

**Comment by Ihatetensorflow** [comment]
no

**Comment by Saduf2019** [comment]
@krishnabairavi95 
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
