### ISSUE TITLE
Upgrade protobuf-java to resolve Java9+ specific warning messages

### ISSUE THREAD

**Issue by cowwoc** [tensorflow/tensorflow#39381]
Please upgrade the com.google.protobuf:protobuf-java dependency to the latest version to resolve https://github.com/protocolbuffers/protobuf/issues/3781

I forced an upgrade on the application-side and it seemed to work cleanly.

**Comment by yongtang** [comment]
Added a PR #39384 for to update protobuf-java to 3.9.2 (match C++ version in tensorflow).
