### ISSUE TITLE
TFlite model performance issues on Snapdragon 855+ - using benchmark_model

### ISSUE THREAD

**Issue by amitmate** [tensorflow/tensorflow#39396]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
   
   using benchmark_model built from source (tf 2.2.0) using bazel. have a custom network model
   involving tf.matmul  (variable inputs) as target network graph for evaluation.
 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

  Ubuntu 18.04

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:

  OnePlus 7t (Snapdragon 855+)
  Android 10

- TensorFlow installed from (source or binary):
  source 2.2.0

- TensorFlow version (use command below):
  2.2.0

- Python version:

  3.5+

- Bazel version (if compiling from source):

  3.1.0

- GCC/Compiler version (if compiling from source):

 clang via android ndk toolchain

- CUDA/cuDNN version:

 N/A, GPU does not support the model and some ops

- CPU model and memory:

  Custom model involving series of Convolutions, BN, Matmuls.
  Model Size ~23 MB
  Max Memory usage ~65 MB

**Describe the current behavior**

Model has to be run on CPU since tf.matmul (variable inputs) operation is not supported on both GPU and Hexagon (or even via SNPE).

Average inference delay on cold start (of the phone) is low with low standard deviation (e.g., with 1000 runs). As the number of runs/iterations are increased (e.g., to 15000) for the benchmark_model script, the inference delay starts increasing and the phone gets hotter.

(pls note that higher delay for warm-up runs are ignored)

**Describe the expected behavior**

 The inference delay is expected to be fairly constant for continuous operation. The degradation in performance with time is not expected and perhaps related to thermal issues.

Any suggestions or ideas to support custom operation via GPU or Hexagon delegate would be useful.  

Recommendations of a chipset/platform with good thermal performance for sustained operations would also be helpful.

**Standalone code to reproduce the issue**

Any tflite model taking e.g. average inference execution time of 50-100ms on Snapdragon 855+ would do.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by aayushthakur** [comment]
Can anyone clarify what is the latest version of Tensorflow lite on Android? Because on the main page of this github it says 1.15.0 but on here https://bintray.com/google/tensorflow/tensorflow-lite
we have 2.2.0 as well. Android studio also suggests 1.15.0. Which one to use?

**Comment by terryheo** [comment]
CPU throttling is a system feature so user application usually an app can't control it.
Since running ML model with CPU is highly CPU intensive task, it's difficult to avoid it. Maybe you need to reduce the number of computation.

Using GPU or NNAPI helps since it reduces CPU burden. As you said, some ops are not supported with these delegates, you might need to refactor your model to leverage it.
BTW, did you try master branch?
There is a new feature that you can run a partial graph on GPU more efficiently.

**Comment by amitmate** [comment]
Thanks Terry for your response. I have tried NNAPI and CPU/GPU combined operation but the inference delays are higher than CPU-only operation for *my* network. I suspect the intermediate layer data  exchange between CPU and GPU may be causing it (large buffers at partial graph outputs).  I am surprised that MLPerf or AI-benchmark have not included the throttling and its effect on inference delays in the published studies/reports.  It would be great if you can suggest the best Edge-AI platform from a inference delay stability perspective.

Can you pls provide a pointer to the partial graph and corresponding checkin on master branch, i have compiled master branch about a month ago.

**Comment by terryheo** [comment]
There are several changes merged for partitioning support. I think https://github.com/tensorflow/tensorflow/commit/1912ef16d67af82aff8a18a44cd555a919145046 is the last.

This tool is useful to see what causes the delay during graph execution. (including partial delegation)
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark#profiling-model-operators

Are you building an Edge device? If it is, I think Coral EdgeTPU is the best solution. https://coral.ai/products/accelerator/

**Comment by amitmate** [comment]
Terry, thanks for the pointers on partitioning and profiling- will check.

Can i use the Coral Edge TPU on a custom imx8 based board by Toradex, assuming i can build yocto linux (with tensorflow and Edge TPU driver support) for this platform ?

**Comment by terryheo** [comment]
As far as I know it uses libusb based userlevel driver so it doesn't require any kernel patch.
https://github.com/google-coral/edgetpu#linux

**Comment by amitmate** [comment]
Thanks Terry, I am looking at the Coral Edge TPU specs - https://static6.arrow.com/aropdfconversion/bfaa407713d5f91af2008bfe17f2d2cb97118f7d/usb_accelerator.pdf

It says - 

"Caution: If you enable the maximum operating frequency, the USB Accelerator becomes very hot to
the touch during operation and might cause burn injuries. Either keep the device out of reach when
using with the maximum frequency or instead use the default clock frequency to avoid injury. "

If we clock at half the maximum speed, i am assuming the inferencing delays will be doubled. Is there some sort of thermal testing report for the Edge TPU, that i can refer to ? I am really looking to see whether Edge TPU is built for continuous operation (days at stretch) and at what frequency is this sustainable?

**Comment by karimnosseir** [comment]
@amitmate Does your Fully Connected / Matmul same shape but dynamic data, or dynamic shape ?
Note that, we support now FullyConnected with dynamic weights (with constant shape) in Hexagon Delegate.
It might be good to share more details about the unsupported ops that needs to run on CPU.

**Comment by amitmate** [comment]
thanks Karim - it is same shape and dynamic data. i had tried the hexagon delegate earlier, but it supported only certain models (it failed for my model that contained matmul with both inputs variables). Can you provide some pointers or samples to use the hexagon delegate for a custom model?

**Comment by karimnosseir** [comment]
The support was added recently, so try again. Nothing different just follow the guide and use the nightly
https://www.tensorflow.org/lite/performance/hexagon_delegate

If you are having issue, let us know what is the issue.

Thanks

**Comment by amitmate** [comment]
Thank, we will try it out and let you know.

**Comment by amitmate** [comment]
@karimnosseir , thanks , am able to delegate nodes to the hexagon processor now and there is speed-up. still need to do accuracy tests. will post after we finish more detailed tests on this.

**Comment by amitmate** [comment]
@karimnosseir  I get the following error for one of the tf operation, when i am quantizing our model using the hexagon delegate conversion instructions above. 

RuntimeError: Quantization not yet supported for op: : REDUCE_MAX

If i bypass this quantization, the delegate does not run any nodes on the hexagon. How do we handle this?

**Comment by karimnosseir** [comment]
Hi @amitmate 
These are 2 separate issues
1) Why Reduce Max is not quantized ?, can you share more details about the Op (params, type and quantization type you passed). I will check it

2) Why no nodes are delegated, it really depends on the resulting model, if your model has float ops we can't execute float on delegate, if you share the model or more details about the ops in the model, i can tell you why ?

**Comment by amitmate** [comment]
@karimnosseir thanks for looking into this.

For #1, have printed  the model summary below, hope that is sufficient, let me know if anything additional is needed. The MatrixMul custom layer has tf.matmul.

For #2, since REDUCE_MAX was not getting quantized (as INT8), i had to remove the instruction to force supported ops to be int8 i.e., i removed the following line from quantization code , but input/output types were still uint8, and so the model stayed float as you have guessed.

##converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            [(None, 3400, 1, 3)] 0                                            
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 3400, 1, 64)  256         input_1[0][0]                    
__________________________________________________________________________________________________
batch_normalization (BatchNorma (None, 3400, 1, 64)  256         conv2d[0][0]                     
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 3400, 1, 128) 8320        batch_normalization[0][0]        
__________________________________________________________________________________________________
batch_normalization_1 (BatchNor (None, 3400, 1, 128) 512         conv2d_1[0][0]                   
__________________________________________________________________________________________________
conv2d_2 (Conv2D)               (None, 3400, 1, 1024 132096      batch_normalization_1[0][0]      
__________________________________________________________________________________________________
batch_normalization_2 (BatchNor (None, 3400, 1, 1024 4096        conv2d_2[0][0]                   
__________________________________________________________________________________________________
max_pooling2d (MaxPooling2D)    (None, 1, 1, 1024)   0           batch_normalization_2[0][0]      
__________________________________________________________________________________________________
dense (Dense)                   (None, 1, 1, 512)    524800      max_pooling2d[0][0]              
__________________________________________________________________________________________________
batch_normalization_3 (BatchNor (None, 1, 1, 512)    2048        dense[0][0]                      
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 1, 1, 256)    131328      batch_normalization_3[0][0]      
__________________________________________________________________________________________________
batch_normalization_4 (BatchNor (None, 1, 1, 256)    1024        dense_1[0][0]                    
__________________________________________________________________________________________________
dense_2 (Dense)                 (None, 1, 1, 9)      2313        batch_normalization_4[0][0]      
__________________________________________________________________________________________________
reshape_1 (Reshape)             (None, 3400, 3)      0           input_1[0][0]                    
__________________________________________________________________________________________________
reshape (Reshape)               (None, 3, 3)         0           dense_2[0][0]                    
__________________________________________________________________________________________________
matrix_mul (MatrixMul)          (None, 3400, 3)      0           reshape_1[0][0]                  
                                                                 reshape[0][0]                    
__________________________________________________________________________________________________
reshape_2 (Reshape)             (None, 3400, 1, 3)   0           matrix_mul[0][0]                 
__________________________________________________________________________________________________
conv2d_3 (Conv2D)               (None, 3400, 1, 64)  256         reshape_2[0][0]                  
__________________________________________________________________________________________________
batch_normalization_5 (BatchNor (None, 3400, 1, 64)  256         conv2d_3[0][0]                   
__________________________________________________________________________________________________
conv2d_4 (Conv2D)               (None, 3400, 1, 64)  4160        batch_normalization_5[0][0]      
__________________________________________________________________________________________________
batch_normalization_6 (BatchNor (None, 3400, 1, 64)  256         conv2d_4[0][0]                   
__________________________________________________________________________________________________
conv2d_5 (Conv2D)               (None, 3400, 1, 64)  4160        batch_normalization_6[0][0]      
__________________________________________________________________________________________________
batch_normalization_7 (BatchNor (None, 3400, 1, 64)  256         conv2d_5[0][0]                   
__________________________________________________________________________________________________
conv2d_6 (Conv2D)               (None, 3400, 1, 128) 8320        batch_normalization_7[0][0]      
__________________________________________________________________________________________________
batch_normalization_8 (BatchNor (None, 3400, 1, 128) 512         conv2d_6[0][0]                   
__________________________________________________________________________________________________
conv2d_7 (Conv2D)               (None, 3400, 1, 1024 132096      batch_normalization_8[0][0]      
__________________________________________________________________________________________________
batch_normalization_9 (BatchNor (None, 3400, 1, 1024 4096        conv2d_7[0][0]                   
__________________________________________________________________________________________________
max_pooling2d_1 (MaxPooling2D)  (None, 1, 1, 1024)   0           batch_normalization_9[0][0]      
__________________________________________________________________________________________________
dense_3 (Dense)                 (None, 1, 1, 512)    524800      max_pooling2d_1[0][0]            
__________________________________________________________________________________________________
batch_normalization_10 (BatchNo (None, 1, 1, 512)    2048        dense_3[0][0]                    
__________________________________________________________________________________________________
dense_4 (Dense)                 (None, 1, 1, 256)    131328      batch_normalization_10[0][0]     
__________________________________________________________________________________________________
batch_normalization_11 (BatchNo (None, 1, 1, 256)    1024        dense_4[0][0]                    
__________________________________________________________________________________________________
dense_5 (Dense)                 (None, 1, 1, 4096)   1052672     batch_normalization_11[0][0]     
__________________________________________________________________________________________________
reshape_4 (Reshape)             (None, 3400, 64)     0           batch_normalization_6[0][0]      
__________________________________________________________________________________________________
reshape_3 (Reshape)             (None, 64, 64)       0           dense_5[0][0]                    
__________________________________________________________________________________________________
matrix_mul_1 (MatrixMul)        (None, 3400, 64)     0           reshape_4[0][0]                  
                                                                 reshape_3[0][0]                  
__________________________________________________________________________________________________
reshape_5 (Reshape)             (None, 3400, 1, 64)  0           matrix_mul_1[0][0]               
__________________________________________________________________________________________________
conv2d_8 (Conv2D)               (None, 3400, 1, 64)  4160        reshape_5[0][0]                  
__________________________________________________________________________________________________
batch_normalization_12 (BatchNo (None, 3400, 1, 64)  256         conv2d_8[0][0]                   
__________________________________________________________________________________________________
conv2d_9 (Conv2D)               (None, 3400, 1, 128) 8320        batch_normalization_12[0][0]     
__________________________________________________________________________________________________
batch_normalization_13 (BatchNo (None, 3400, 1, 128) 512         conv2d_9[0][0]                   
__________________________________________________________________________________________________
conv2d_10 (Conv2D)              (None, 3400, 1, 1024 132096      batch_normalization_13[0][0]     
__________________________________________________________________________________________________
batch_normalization_14 (BatchNo (None, 3400, 1, 1024 4096        conv2d_10[0][0]                  
__________________________________________________________________________________________________
max_pooling2d_2 (MaxPooling2D)  (None, 1, 1, 1024)   0           batch_normalization_14[0][0]     
__________________________________________________________________________________________________
dense_6 (Dense)                 (None, 1, 1, 512)    524800      max_pooling2d_2[0][0]            
__________________________________________________________________________________________________
batch_normalization_15 (BatchNo (None, 1, 1, 512)    2048        dense_6[0][0]                    
__________________________________________________________________________________________________
dropout (Dropout)               (None, 1, 1, 512)    0           batch_normalization_15[0][0]     
__________________________________________________________________________________________________
dense_7 (Dense)                 (None, 1, 1, 256)    131328      dropout[0][0]                    
__________________________________________________________________________________________________
batch_normalization_16 (BatchNo (None, 1, 1, 256)    1024        dense_7[0][0]                    
__________________________________________________________________________________________________
dropout_1 (Dropout)             (None, 1, 1, 256)    0           batch_normalization_16[0][0]     
__________________________________________________________________________________________________
dense_8 (Dense)                 (None, 1, 1, 2)      514         dropout_1[0][0]                  
__________________________________________________________________________________________________
flatten (Flatten)               (None, 2)            0           dense_8[0][0]                    
==================================================================================================
Total params: 3,482,443
Trainable params: 3,470,283
Non-trainable params: 12,160

**Comment by karimnosseir** [comment]
@amitmate I sent a fix for the Reduce max quantization. Can you retry from head of master branch, or wait for nightly and retry.

**Comment by amitmate** [comment]
@karimnosseir , we get the following error now

RuntimeError: Quantization not yet supported for op: 'REDUCE_PROD'.

Thanks for looking into this.

**Comment by karimnosseir** [comment]
@amitmate Currently we don't support quantized reduce_prod, can you convert your model partially quantized - not all ops are quantized - instead.
You can do this by using tf.lite.OpsSet.TFLITE_BUILTINS instead of tf.lite.OpsSet.TFLITE_BUILTINS_INT8

Try this and let me know 

Thanks

**Comment by amitmate** [comment]
Tried this before, when we set to  tf.lite.OpsSet.TFLITE_BUILTINS , none of the nodes are delegated to Hexagon. (netron shows most operations are floating point). Can try again with the latest to see any difference

**Comment by karimnosseir** [comment]
@amitmate Can you please paste your exact options used ?
