### ISSUE TITLE
[RNN]Failed to do full integer quantization and got error: Failed to parse the model: pybind11::init(): factory function returned nullptr.

### ISSUE THREAD

**Issue by LesterRe** [tensorflow/tensorflow#39392]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 10.15.3
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): tf-nightly

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
import tensorflow as tf
import numpy as np

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.LSTM(256, input_shape=(60, 388), activation='tanh',
                               return_sequences=True))
model.add(tf.keras.layers.Dropout(0.3))
model.add(tf.keras.layers.Dense(388, activation='softmax'))

def representative_data_gen():
  for input_value in test_ds.take(100):
    yield [input_value]
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
converter.representative_dataset = representative_data_gen
tflite_model_quant = converter.convert()
```

**The output from the converter invocation**

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 51, in __init__
    _calibration_wrapper.CalibrationWrapper(model_content))
TypeError: pybind11::init(): factory function returned nullptr

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lisichao/PycharmProjects/KerasSavedModel/mnistExample.py", line 155, in <module>
    tflite_model_quant = converter.convert()
  File "/usr/local/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 611, in convert
    constants.FLOAT, True)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 316, in _calibrate_quantize_model
    calibrate_quantize = _calibrator.Calibrator(result)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 53, in __init__
    raise ValueError("Failed to parse the model: %s." % e)
ValueError: Failed to parse the model: pybind11::init(): factory function returned nullptr.
```
**Failure details**
When I convert the TensorFlow Model without optimization, it works.
When I do post-training integer quantization without a data representative, it works.
When I provide a data representative, it fails.
The error can be reproduced from the following file.
[ReproduceTheError.zip](https://github.com/tensorflow/tensorflow/files/4607083/ReproduceTheError.zip)

**Comment by amahendrakar** [comment]
@LesterRe,
On running the given code snippet with TF v2.2, I am facing an error stating `AttributeError: 'str' object has no attribute 'call'`. 

Whereas, running the `mnistExample.py` file I am facing an error stating `IndexError: index 302 is out of bounds for axis 2 with size 60`

Could you please provide the complete code and the supporting files you are using, in order to reproduce the issue reported here. Thanks!

**Comment by LesterRe** [comment]
> @LesterRe,
> On running the given code snippet with TF v2.2, I am facing an error stating `AttributeError: 'str' object has no attribute 'call'`.
> 
> Whereas, running the `mnistExample.py` file I am facing an error stating `IndexError: index 302 is out of bounds for axis 2 with size 60`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/58b42b158d9ce310a66fd5133194ac32/39392.ipynb).
> 
> Could you please provide the complete code and the supporting files you are using, in order to reproduce the issue reported here. Thanks!

Hi amahendrakar,
Sorry for the previous zip file. I did make a mistake and I corrected it. You can find it below.
Looking forward to your reply.
[producingError.zip](https://github.com/tensorflow/tensorflow/files/4612919/producingError.zip)

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/cd8abc23078bf4cdbff771bab387770e/39392.ipynb#scrollTo=vG36_oc_ItLL) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/bfbe8488883f9f0e7f7f7b34fda11154/39392-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by marjanemd** [comment]
I am facing the same issue. Any solution for that?

**Comment by sheldoncoup** [comment]
Also having the same issues. Would love to hear if there was a workaround/update for this.

**Comment by vladdders** [comment]
I am also having this issue, any updates on this so far? Thanks!

**Comment by czabo** [comment]
Same error here, any idea?

**Comment by anthonycanino1** [comment]
I have come across the issue as well, using both an LSTM and GRU keras layer. Is this due to  lack of support for full integer quantization for RNN?

**Comment by czabo** [comment]
Yeah it seems the Calllibrator class doesn't support RNN yet, but I don't know how to fix that. Would love to though, if I could get some guidance.

**Comment by Guichaguri** [comment]
I'm also getting this error with an [object_detection](https://github.com/tensorflow/models/tree/master/research/object_detection) model. Since it is a community-driven project, I don't know whether this is a TF bug or something in the model that TF doesn't support yet.

**Comment by huberemanuel** [comment]
I'm also having this issue

**Comment by shlomi-amitai** [comment]
get this issue now also with tf-nightly (2.4.0.dev20201002).
Could you advise or update?

**Comment by shlomi-amitai** [comment]
It looks like indexing /slicing are not supported. when I remove these ops, it works.

**Comment by Aribido-Oluwaseun** [comment]
@shlomi-amitai can you kindly expantiate on how to remove indexing/slicing

**Comment by shlomi-amitai** [comment]
It's very model dependent.. I had operations like tensor2 = tensor1[:,:,:-1,:]. removing these solved the problem. it probably means that these operations are yet not implemented for tflite quantization.

**Comment by JonathanDZiegler** [comment]
I am getting the same issue with a model that contains both RNN and extensive slicing. No way I can remove that from the model. Is there an estimate on when these operations will be implemented for tflite quantization?

**Comment by wellido** [comment]
I have the same issue.😭

**Comment by wenjielu123** [comment]
I have the same issue, tested under TF2.4 and nightly (2.5.0-dev20201216), with model contains LSTM, but no explicit slicing.  I wonder if this is due to the lack of support of RNN.. Is this documented anywhere?

**Comment by pabou38** [comment]
I have the same issue, with TF2.4.1 and , with model contains LSTM, but no explicit slicing. 

https://www.tensorflow.org/lite/convert/rnn specifies : The feature is part of TensorFlow 2.3 release. is there an undocumented limitation there ?

**Comment by dmpiergiacomo** [comment]
Hi,

Same issue here with TF2.4.1.

Conversion without optimization works, but when I provide a representative dataset it fails with:
`ValueError: Failed to parse the model: pybind11::init(): factory function returned nullptr.`

Which is the planned timeline for this fix? Is there another TF version that can workaround the issue?

**Comment by wenjielu123** [comment]
I had the same error. I was able to get around it by setting `unroll=True` for the LSTM.

It is strange that, according to [this talk](https://youtu.be/2tnWHCxP8Bk?t=261), RNN/LSTM is natively supported in TF2.x, without any change to the model.

**Comment by angelocatalani** [comment]
Same error here with this model:
```python
    input = Input(shape=(time_steps, data_dim))
    lstm_units = 256
    lstm_out = LSTM(lstm_units, return_sequences=False)(input)
    output = Dense(4, activation="softmax")(lstm_out)
    model = Model(inputs=[input], outputs=output)
    model.summary()
```

**Comment by leenfirststep** [comment]
> I had the same error. I was able to get around it by setting `unroll=True` for the LSTM.
> 
> It is strange that, according to [this talk](https://youtu.be/2tnWHCxP8Bk?t=261), RNN/LSTM is natively supported in TF2.x, without any change to the model.

Setting "unroll=True" for the LSTM allows for INT Quantization, but has a significantly negative impact on the accuracy and inference time (+50%) of the model, so it is unfortunately not a viable work-around.

**Comment by sushreebarsa** [comment]
I reproduced the code shared but facing different error .Please find the gist [here ](https://colab.research.google.com/gist/sushreebarsa/5ac844ec60236bca29acb7e91bcecaf1/untitled319.ipynb)..Thanks!
