### ISSUE TITLE
add support of reduce max to tensorflow lite micro

### ISSUE THREAD

**Issue by wenhui-prudencemed** [tensorflow/tensorflow#39395]
@tensorflow/micro

tf lite micro 2.2

issue: Didn't find op for builtin opcode 'REDUCE_MAX' version '1'

suggestion: add support of reduce max to tensorflow lite micro

**Comment by patriklaurell** [comment]
Hi @wenhui-prudencemed ! I am working on an implementation for int8 support in reduce_max for TFL micro. I expect to deliver within a few weeks

**Comment by patriklaurell** [comment]
I will also be adding float32 support in the same patch.

**Comment by mohantym** [comment]
Hi @wenhui-prudencemed ! I think tf.reduce_max is supported now for lite models. Attaching relevant[ thread ](https://www.tensorflow.org/lite/guide/ops_compatibility)for reference.
