### ISSUE TITLE
when I try to install tensorflow from source by bazel, I got this problem:

### ISSUE THREAD

**Issue by haibarasiao** [tensorflow/tensorflow#3939]
the commond is : bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
ERROR is:
undeclared inclusion(s) in rule '@zlib_archive//:zlib':
this rule is missing dependency declarations for the following files included by 'external/zlib_archive/zlib-1.2.8/uncompr.c':
  '/usr/local/lib/gcc/x86_64-pc-linux-gnu/6.1.0/include-fixed/limits.h'
  '/usr/local/lib/gcc/x86_64-pc-linux-gnu/6.1.0/include-fixed/syslimits.h'
  '/usr/local/lib/gcc/x86_64-pc-linux-gnu/6.1.0/include/stddef.h'
  '/usr/local/lib/gcc/x86_64-pc-linux-gnu/6.1.0/include/stdarg.h'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
how can I deal with it?Thanks!

**Comment by reesepathak** [comment]
Also having this issue.

**Comment by haibarasiao** [comment]
@reesepathak 
#2109 will help you, and I fixed it by adding '/usr/local/lib/gcc/x86_64-pc-linux-gnu/6.1.0/include' and '/usr/local/lib/gcc/x86_64-pc-linux-gnu/6.1.0/include-fixed' in tensorflow/third_party/gpus/crosstool/CROSSTOOL file,I think this will be work for you.
