### ISSUE TITLE
Resource exhausted: OOM when allocating tensor with shape[32,960,10,10] 

### ISSUE THREAD

**Issue by sainisanjay** [tensorflow/tensorflow#39397]
Training was going fine till 47K steps and then got Resource exhausted error. 
```
File "/home/saini/.virtualenvs/cv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[32,960,10,10] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node gradients/AddN_162-1-TransposeNHWCToNCHW-LayoutOptimizer}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Loss/Cast_232/_16919]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[32,960,10,10] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node gradients/AddN_162-1-TransposeNHWCToNCHW-LayoutOptimizer}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.
```
OS: Ubuntu 18.04
Tensorflow: 1.14.0 GPU
CUDA: 10.0
CUDNN:: 7.6
Batch Size: 32

Follow changes i have made in default TF object detection API: 

```
model_lib.py
tf.estimator.EvalSpec(
            name=eval_spec_name,
            input_fn=eval_input_fn,
            steps=None,
            throttle_secs = 172800,
            exporters=exporter))
eval.proto
optional uint32 eval_interval_secs = 3 [default = 172800]; # default = 600
model_main.py
config = tf.estimator.RunConfig(model_dir=FLAGS.model_dir, save_checkpoints_steps=5000)
```

**Comment by Saduf2019** [comment]
@sainisanjay  
In order to expedite the trouble-shooting process, please provide a simple stand alone code to reproduce the issue reported here. Thanks!

**Comment by sainisanjay** [comment]
Hi @Saduf2019 
As i mentioned i am doing object detection training with ssd_mobilenet_v2_quantized_300x300_coco model. 
`python ../../models/research/object_detection/model_main.py --pipeline_config_path=./ssd_mobilenet_v2_quantized_300x300_coco.config --model_dir=./training/ --num_train_steps=2000000 --sample_1_of_n_eval_examples=1 --alsologtostderr `
Training was going fine till 47900 steps, after that i got error:

```
2020-05-11 09:53:31.475093: W tensorflow/core/common_runtime/bfc_allocator.cc:319] ****************************************************************************************************
2020-05-11 09:53:31.475131: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at transpose_op.cc:199 : Resource exhausted: OOM when allocating tensor with shape[32,960,10,10] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "/home/adas/.virtualenvs/cv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/adas/.virtualenvs/cv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/adas/.virtualenvs/cv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[32,960,10,10] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node gradients/AddN_162-1-TransposeNHWCToNCHW-LayoutOptimizer}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Loss/Cast_232/_16919]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[32,960,10,10] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node gradients/AddN_162-1-TransposeNHWCToNCHW-LayoutOptimizer}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.
```

**Comment by sainisanjay** [comment]
*Note *: The error occurred after 47900 steps. My question is why after 47900 steps there is an error. Why not at the initial steps?

**Comment by jvishnuvardhan** [comment]
@sainisanjay Can you please try `TF1.15.2` as there were lots of performance improvements after `TF1.14`. Please let us know whether you still face same issue. Did you monitor memory? Can you also fill the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose) with details of your platform. Thanks!

**Comment by sainisanjay** [comment]
Hi @jvishnuvardhan, I have tried with `TF1.15.0 GPU` and found same issue. And surprisingly OOM error got exactly same 47900 steps.

**Comment by sanjoy** [comment]
Hi @sainisanjay,

Can you try using getting a [count of all live Python](https://stackoverflow.com/questions/26889459/get-count-of-reachable-live-objects) objects and check that it isn't increasing on every step?  If it is increasing then you probably have a memory leak in your program (you can also try getting the types of the live objects to see e.g. if the number of live  `Tensor`s is increasing to narrow this down further).  If the number of live objects stays the same but you still OOM after a specific number of iterations then it could be a problem with TensorFlow.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
