### ISSUE TITLE
upgraded from 2.1 to 2.2 raised 'Unexpectedly high number of iterations in HLO passes, exiting fixed point loop'

### ISSUE THREAD

**Issue by naturomics** [tensorflow/tensorflow#39409]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Gentoo
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.2.0-rc2
- Python version: 3.7
- Bazel version (if compiling from source): 2.0
- GCC/Compiler version (if compiling from source): 8.4
- CUDA/cuDNN version: 10.2/7.6
- GPU model and memory: 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I'm using Gentoo linux and tf is installed by Gentoo's package management system(portage/emerge). After upgrading tf from 2.1.0 to 2.2.0-rc2, a new warning raised training on a same model:
`W ./tensorflow/compiler/xla/service/hlo_pass_fix.h:49] Unexpectedly high number of iterations in HLO passes, exiting fixed point loop.`
This warning might not affect training speed, but takes more GPU memory. The model with same setting works well in tf 2.1 but throws OOM in tf 2.2. It's unclear to me what this warning means and not helpful to find the problem. 

**Describe the expected behavior**
should not occupy more memory

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@naturomics.
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!
