### ISSUE TITLE
Unsigned int (tf.uint{32,64}) support for tf.{tile,repeat}

### ISSUE THREAD

**Issue by hartikainen** [tensorflow/tensorflow#39405]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `macOS Catalina 10.15.2 (19C57)`
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): `2.2.0`
- Python version: `3.7.5`

**Describe the feature and the current behavior/state.**
Feature: `tf.tile` and `tf.repeat` do not fail when input is of dtype `tf.uint{32,64}`.
Current behavior: `tf.tile` and `tf.repeat` fail when input is of dtype `tf.uint{32,64}`.

**Will this change the current api? How?**
Would add new supported input type to `tf.tile` and `tf.repeat`.

**Who will benefit with this feature?**
Users that need to repeat or tile their data of type `tf.uint{32,64}`

**Sketch of a test case**
```python
import tensorflow as tf


tf.tile(tf.constant([1,2,3], dtype=tf.uint64), (3, ))
tf.tile(tf.constant([1,2,3], dtype=tf.uint32), (3, ))
tf.repeat(tf.constant([1,2,3], dtype=tf.uint64), 3, axis=0)
tf.repeat(tf.constant([1,2,3], dtype=tf.uint32), 3, axis=0)
```

**Logs for current behavior**
```
ipdb> tf.tile(tf.constant([1,2,3], dtype=tf.uint64), (3, ))
*** tensorflow.python.framework.errors_impl.UnimplementedError: TileOp : The input data type is not supported, DataType : uint64, Dimension : 1 [Op:Tile]
ipdb> tf.tile(tf.constant([1,2,3], dtype=tf.uint32), (3, ))
*** tensorflow.python.framework.errors_impl.UnimplementedError: TileOp : The input data type is not supported, DataType : uint32, Dimension : 1 [Op:Tile]
ipdb> tf.repeat(tf.constant([1,2,3], dtype=tf.uint64), 3, axis=0)
*** tensorflow.python.framework.errors_impl.UnimplementedError: TileOp : The input data type is not supported, DataType : uint64, Dimension : 2 [Op:Tile]
ipdb> tf.repeat(tf.constant([1,2,3], dtype=tf.uint32), 3, axis=0)
*** tensorflow.python.framework.errors_impl.UnimplementedError: TileOp : The input data type is not supported, DataType : uint32, Dimension : 2 [Op:Tile]
```

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/782744d7438a74267b8e6a82a62ef2a0/untitled175.ipynb)

**Comment by yongtang** [comment]
Added a PR #39424 for uint32/uint64 support.

**Comment by hartikainen** [comment]
That was super fast. Thanks @yongtang, much appreciated!
