### ISSUE TITLE
About loading of saved_model format in tf2

### ISSUE THREAD

**Issue by wangwenchao-job** [tensorflow/tensorflow#39408]
There are too many versions of tf. Before, I used a function to load the saved_model format model.

`new_model = tf.contrib.saved_model.load_keras_model(saved_model_path) new_model.summary()`

But if folder “assets” does not exist, an error will occur,and this file is not available for every model.

So which function should I use to load？

Thank you !!

**Comment by Saduf2019** [comment]
@wangwenchao-job 
Could you please let us know which version of tf are you using and please share a simple stand alone code so we could replicate the issue faced by you..Thanks!

**Comment by wangwenchao-job** [comment]
> @wangwenchao-job
> Could you please let us know which version of tf are you using and please share a simple stand alone code so we could replicate the issue faced by you..Thanks!

Thank you very much for your reply！！

My code execution environment is:
Windows = 10
tf = 1.14


from tensorflow.keras.applications import *
from tensorflow.keras.models import Model
import tensorflow as tf
keras = tf.keras
model_dir = './saved_model/'
reload_model = tf.keras.experimental.load_from_saved_model(model_dir)
reload_model.summary()
reload_model.save('./det_model.h5')


As above is my code, I also tried other functions:

tf.compat.v1.keras.experimental.load_from_saved_model
tf.compat.v2.keras.experimental.load_from_saved_model
tf.contrib.saved_model.load_keras_model

**Comment by wangwenchao-job** [comment]
> @wangwenchao-job
> Could you please let us know which version of tf are you using and please share a simple stand alone code so we could replicate the issue faced by you..Thanks!

More information：
My saved_model only has .pb and adjustables, no assets.

When there is an assets file before, it can be imported using function ：
tf.contrib.saved_model.load_keras_model

But now I get an error:
Python unhandled win32 exception...

And automatically open vs for me to debug.

**Comment by Saduf2019** [comment]
@wangwenchao-job
Yes, please email the model.

**Comment by wangwenchao-job** [comment]
> @wangwenchao-job
> Yes, please email the model.

The model has been sent to you at the address:
notifications@github.com
Or this download link：
https://www.jianguoyun.com/p/DRuhIW8QtKK2CBjB95cD

I don't know if you can access

**Comment by Saduf2019** [comment]
@wangwenchao-job
you can email it as saduf@google.com

**Comment by wangwenchao-job** [comment]
> @wangwenchao-job
> you can email it as [saduf@google.com](mailto:saduf@google.com)

@Saduf2019 
The model has been sent to you to the above email address.

**Comment by wangwenchao-job** [comment]
> > @wangwenchao-job
> > you can email it as [saduf@google.com](mailto:saduf@google.com)
> 
> @Saduf2019
> The model has been sent to you to the above email address.

update
----
In addition, I use the following method to load the savedmodel and export pb, and my ultimate goal is to convert the savedmodel format model into a pb format file (frozen_graph)

`import tensorflow as tf
print(tf.__version__)

from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2

loaded = tf.saved_model.load('saved_model')
infer = loaded.signatures['serving_default']

f = tf.function(infer).get_concrete_function(inputs=tf.TensorSpec(shape=[None, 28, 28, 3], dtype=tf.float32))
f2 = convert_variables_to_constants_v2(f)
graph_def = f2.graph.as_graph_def()

for node in graph_def.node:
   print(node.op, node.name)

with tf.io.gfile.GFile('frozen_graph.pb', 'wb') as f:
   f.write(graph_def.SerializeToString())`

But the obtained pb model is only 1k in size, so this conversion method should be problematic.

**Comment by wangwenchao-job** [comment]
@ Saduf2019
Do you have any emails? Do you have any suggestions?

**Comment by Saduf2019** [comment]
@wangwenchao-job
no i have not received, can you please share a colab gist with the issue for us to analyse the issue faced.
