### ISSUE TITLE
Tensorflow Build from Source Raspberry Pi

### ISSUE THREAD

**Issue by tensorrpi** [tensorflow/tensorflow#39419]
**System information**
- Windows 10 Pro Version 1909 
- Python 3.8.2
- pip 20.1
- virtualenv 20.0.20

Hello,
I am trying to follow these installation instructions https://www.tensorflow.org/install/source_rpi.

When I try to "cross-compile the TensorFlow source code to build a Python pip package", I get the error message:
`The command "CI_DOCKER_EXTRA_PARAMS" is either misspelled or could not be found`

This is the command:
`CI_DOCKER_EXTRA_PARAMS="-e CI_BUILD_PYTHON=python3 -e CROSSTOOL_PYTHON_INCLUDE_PATH=/usr/include/python3.4" \`

The test command for Docker works fine:
`docker run --rm hello-world`
`"Hello from Docker!
This message shows that your installation appears to be working correctly."`

Does anyone have an idea or a tip? I suspect something is not installed properly. Is "CI_DOCKER_EXTRA_PARAMS" a Docker-command? What is the requirement for the OS to know or recognize this command?

**Comment by skaldek** [comment]
Probably the problem is that you did not fully copy the command from the site, what is visible from your text. It should look like this:
`CI_DOCKER_EXTRA_PARAMS="-e CI_BUILD_PYTHON=python3 -e CROSSTOOL_PYTHON_INCLUDE_PATH=/usr/include/python3.4" \
    tensorflow/tools/ci_build/ci_build.sh PI-PYTHON3 \
    tensorflow/tools/ci_build/pi/build_raspberry_pi.sh`
Or so, if you need support for all rpi devices:
`tensorflow/tools/ci_build/ci_build.sh PI \
    tensorflow/tools/ci_build/pi/build_raspberry_pi.sh PI_ONE`

**Comment by tensorrpi** [comment]
Of course i copied the code using the "copy code sample to clipboard" button first. The individual lines in the command window are interpreted separately. But I also wrote the entire command individually, as you suggested., which unfortunately does not help. The command "CI_DOCKER_EXTRA_PARAMS" is unknown.

**Comment by terryheo** [comment]
The build script only works with Linux. Please use Linux workstation. Thanks.
