### ISSUE TITLE
Model.fit() process grabs generators that were not passed to it. 

### ISSUE THREAD

**Issue by Abhishaike** [tensorflow/tensorflow#39413]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS, Catalina
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:NA
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.2.0-dev20200508
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: release 10.0, V10.0.130
- GPU model and memory: Titan RTX 24 GB

**Describe the current behavior**
Model.fit(generator_train) grabs generator_test information that was NEVER passed to it. 

**Describe the expected behavior**
Model.fit(generator_train) only works on generator_train information 

**Standalone code to reproduce the issue**
```
import tensorflow as tf
import numpy as np

class GeneratorFile(tf.keras.utils.Sequence):
    def __init__(self, file_list):
        self.file_list = file_list
        self.desired_file = self.file_list[0]
        print('This should be file 1:', self.desired_file)
    def __len__(self):
        return 2
    def on_epoch_end(self):
        self.desired_file = self.file_list[1]
        print('This should be file 2:', self.desired_file)
    def __getitem__(self, item):
        return np.zeros((16, 1)), np.zeros((16,))

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(1, input_dim=1, activation="softmax"))
model.compile(
    optimizer='Adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model_file_train = ['file1', 'file2']
model_file_test = ['file3']
generator_train = GeneratorFile(model_file_train)
generator_test = GeneratorFile(model_file_test) #THIS IS NEVER PASSED IN
model.fit(generator_train, epochs=2, initial_epoch = 0)

```

The output of the above code snippet: 

```
This should be file 1: file1
This should be file 1: file3
Epoch 1/2
2/2 [==============================] - 0s 1ms/step - loss: 15.2492 - accuracy: 0.0000e+00
This should be file 2: file2
Epoch 2/2
2/2 [==============================] - 0s 1ms/step - loss: 15.2492 - accuracy: 0.0000e+00
This should be file 2: file2
```

`file3` was NEVER passed to model.fit(), so how would the generator even be aware of that file? Granted, I'm not even sure if this is a Tensorflow issue, could just be I'm misunderstanding exactly how Model.fit() is supposed to work, but this is extremely unintuitive behavior. 

As a side note, if I comment out the line that defines `generator_test`, file3 never appears.

**Comment by skaldek** [comment]
Line:
`        print('This should be file 1:', self.desired_file)
`
belongs to the class initializer.  Everything that is in the `__init__` method automatically runs when you create an object of this class.
`model_file_test = ['file3']`
Therefore, you see this line on the log screen.
