### ISSUE TITLE
Categorical CrossEntropy returning wrong values

### ISSUE THREAD

**Issue by renan-cunha** [tensorflow/tensorflow#39411]
tf.losses.CategoricalCrossentropy is returning values different from those of numpy

```
import numpy as np
import tensorflow as tf

y_pred = np.array([7.3216137e-07, 3.3240074e-11, 4.4985552e-12,
                   3.9974657e-05, 7.3216137e-07, 4.4985552e-12, 
                   4.4985552e-12, 2.9537498e-04, 8.8050038e-01,
                   1.1916277e-01])
y_true = np.zeros(10)
y_true[5] = 1
cce = tf.losses.CategoricalCrossentropy()


print(f"NUMPY {-1*np.sum(y_true*np.log(y_pred))}")
print(f"TF {cce(y_true, y_pred)}")
```

**System information**
- Have I written custom code: NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installed from (source or binary): Default of Colab
- TensorFlow version (use command below): 2.2.0-rc4
- Python version: 3.6.9

**Describe the current behavior**

```
NUMPY 26.12726483737188
TF 16.11809539794922
```

**Describe the expected behavior**
```
NUMPY 26.12726483737188
TF 26.12726483737188
```

**Standalone code to reproduce the issue**
Colab Link: https://colab.research.google.com/drive/1gKb0eiKfIw4GKZo_lzDTaswWFz7gsAU0?usp=sharing

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/5214d720aa6019d3919d723ee5e660f7/untitled174.ipynb). Thanks!

**Comment by pavithrasv** [comment]
@renan-cunha Can you try with 2D inputs? https://www.tensorflow.org/api_docs/python/tf/keras/losses/CategoricalCrossentropy?version=nightly#__call__

**Comment by renan-cunha** [comment]
Hi, by using 2d inputs the output stays the same


```import numpy as np
import tensorflow as tf

y_pred = np.array([[7.3216137e-07, 3.3240074e-11, 4.4985552e-12,
                   3.9974657e-05, 7.3216137e-07, 4.4985552e-12, 
                   4.4985552e-12, 2.9537498e-04, 8.8050038e-01,
                   1.1916277e-01]])
y_true = np.zeros(10).reshape(1, 10)
y_true[0, 5] = 1
cce = tf.losses.CategoricalCrossentropy()

print(f"NUMPY {-1*np.sum(y_true*np.log(y_pred))}")
print(f"TF {cce(y_true, y_pred)}")
```

Link to reproduce: https://colab.research.google.com/drive/1gKb0eiKfIw4GKZo_lzDTaswWFz7gsAU0?usp=sharing

**Comment by Chocobo1** [comment]
Hi, it seems the `reduction` argument is involved in this, using the above [script](https://github.com/tensorflow/tensorflow/issues/39411#issuecomment-629799292) with different `reduction` values yield the following results:
```python
# tf version: v2.3.0
cce = tf.losses.CategoricalCrossentropy(reduction=tf.keras.losses.Reduction.AUTO)  # wrong, 1.1769444942474365
cce = tf.losses.CategoricalCrossentropy(reduction=tf.keras.losses.Reduction.SUM_OVER_BATCH_SIZE)  # wrong, 1.1769444942474365
cce = tf.losses.CategoricalCrossentropy(reduction=tf.keras.losses.Reduction.SUM)  # correct, 2.353888988494873
```

**Comment by ravikyram** [comment]
I have tried in colab with TF nightly version (`2.5.0-dev20201029`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/385c58c24fde2f917497cb19543da06e/untitled99.ipynb?authuser=1).Thanks!

**Comment by Saduf2019** [comment]
I have tried in colab with TF nightly version (2.6.0-dev20210415) and was able to reproduce the issue. Please, find the [gist here](https://colab.research.google.com/gist/Saduf2019/426febbf26350372206d0a84b1a977c1/untitled590.ipynb).Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
