### ISSUE TITLE
Training a model for my own dataset using tensorflow speech commands 

### ISSUE THREAD

**Issue by krishnabairavi95** [tensorflow/tensorflow#39410]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution : Google Colab 
- TensorFlow version: Tensorflow-gpu 1.14.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip 
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: Updated Google colab's CUDA and cuDNN
- GPU model and memory: Inbuilt Colab-pro GPU 

**Describe the problem**

Dear Authors, 

I am trying to train the speech recognition model for small vocabulary from the following link : https://github.com/tensorflow/tensorflow/tree/r1.9/tensorflow/examples/speech_commands

I am trying to run the following command:

!python tensorflow/examples/speech_commands/train.py --data_url= --clip_duration_ms=5000 --train_dir= /content/drive/My Drive/wuw-checkpoint --data_dir= /content/drive/My Drive/wake-up-word/ --wanted_words = up, down

I cloned into the default master file to run the same. I am getting the following error, can you please help me out in giving the right tf, CUDA and cuDNN versions that I could use to run the same?  Here's the following error I got

Traceback (most recent call last):
  File "tensorflow/examples/speech_commands/train.py", line 452, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "tensorflow/examples/speech_commands/train.py", line 201, in main
    f.write('\n'.join(audio_processor.words_list))
AttributeError: 'AudioProcessor' object has no attribute 'words_list'
Thank you, I look forward to hearing from you 
**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
@krishnabairavi95 Can you try build against the master branch?
