### ISSUE TITLE
tf.app.flags issue for multiple file AttributeError(name)

### ISSUE THREAD

**Issue by chenghuige** [tensorflow/tensorflow#3942]
python train.py 
messi
Traceback (most recent call last):
  File "train.py", line 24, in <module>
    import model 
  File "/home/gezi/mine/tensorflow-exp/tests/flags/model.py", line 23, in <module>
    print(FLAGS.batch_size)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 43, in __getattr__
    raise AttributeError(name)
AttributeError: batch_size
gezi:~/mine/tensorflow-exp/test
AttributeError: batch_size

I have 3 .pys, running tensorlow 0.10
#-----------------------------------------train.py
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import sys,os
import tensorflow as tf

flags = tf.app.flags 
FLAGS = tf.app.flags.FLAGS 

flags.DEFINE_integer('step', 5, '')

import util
import model 

#------------------------model.py
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import sys,os
import tensorflow as tf

flags = tf.app.flags 
FLAGS = tf.app.flags.FLAGS 

flags.DEFINE_integer('batch_size', 100, '')

print(FLAGS.batch_size)

#--------------------------util.py
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf

flags = tf.app.flags 
FLAGS = tf.app.flags.FLAGS 

flags.DEFINE_string('name', 'messi', '')

print(FLAGS.name)

These demo code will not cause error, if I switch to use gflags.
Another problem:
 python train.py --help
usage: train.py [-h] [--step STEP] [--name NAME]

optional arguments:
  -h, --help   show this help message and exit
  --step STEP
  --name NAME

Why not show default values as c version gflags do ?

**Comment by vrv** [comment]
I think if you have multiple files like this, tf.app.flags must be used with 'tf.app.run()'.

tf.app.run() is where the flags you have declared are parsed, so if run code that inspects FLAGS before tf.app.run(), it won't work.

My suggestion would be to set it up so that:

model.py and util.py define functions but don't inspect FLAGS on import
And then your 'train.py' would define its code in a main function 

    def main(argv):
      .. your code ...

Then at the bottom:
    if __name__ == "__main__":
      tf.app.run()


As for the default values, I'll have to look

**Comment by chenghuige** [comment]
@vrv  Got the point now, it works, thanks!

**Comment by vrv** [comment]
If someone wants to change flags.py to use https://docs.python.org/3/library/argparse.html#argparse.ArgumentDefaultsHelpFormatter when calling argparser so that it shows defaults, that would be great.  Closing the bug as is though.
