### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.keras.applications.efficientnet'

### ISSUE THREAD

**Issue by DanielMorton** [tensorflow/tensorflow#39437]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Cannot get EfficientNet models from tf.keras.applications

**Describe the expected behavior**
from tensorflow.keras.applications.efficientnet import *
should not produce an error. All other pretrained networks can be loaded.

**Standalone code to reproduce the issue**
%tensorflow_version 2.x
from tensorflow.keras.applications.efficientnet import *

run the above in Colab with tenso

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by iobtl** [comment]
Update your version to TF 2.2 if you haven't. EfficientNet is only available under ```tf.keras.applications``` as part of TF 2.2 (reference: https://github.com/tensorflow/tensorflow/blob/r2.2/tensorflow/python/keras/applications/efficientnet.py)

**Comment by amahendrakar** [comment]
@DanielMorton,
As per the [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/applications/efficientnet), `tf.keras.applications.efficientnet` API is available only in TF-nightly.
 
With the latest TF-nightly, I was able to import the API without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/64b515c5b7d20ff54f7d4a352630e808/39437.ipynb). Thanks!

**Comment by ocjosen** [comment]
This should work:
`from tensorflow.python.keras.applications.efficientnet import *`

**Comment by DanielMorton** [comment]
@amahendrakar A well hidden bit of documentation, but that does seem to be correct.

**Comment by amahendrakar** [comment]
@DanielMorton,
Could you please create a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template with the error you are facing, so that we can track the issue there. Thanks!

**Comment by amahendrakar** [comment]
> @DanielMorton,
> Could you please create a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template with the error you are facing, so that we can track the issue there. Thanks!

Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
