### ISSUE TITLE
Link to "iris_monitor.py" broken 

### ISSUE THREAD

**Issue by fansgit** [tensorflow/tensorflow#3943]
The link to [iris_monitor.py](https://www.tensorflow.org/versions/examples/tutorials/monitors/iris_monitors.py) returns `not found` on Tensorflow tutorial [logging-and-monitoring-basics](https://www.tensorflow.org/versions/r0.10/tutorials/monitors/index.html#logging-and-monitoring-basics-with-tf-contrib-learn). Should it be redirected to Github [there](https://github.com/tensorflow/tensorflow/raw/r0.10/tensorflow/examples/tutorials/monitors/iris_monitors.py) ?

**Comment by prb12** [comment]
Looks like something got lost in translation between the internal and external code repositories.

**Comment by sandersk** [comment]
Apologies for the error @fansgit. The correct link is:

https://www.tensorflow.org/code/tensorflow/examples/tutorials/monitors/iris_monitors.py

I actually already fixed this on 8/19 in 4a510c177. It just needs to be folded into the r0.10 branch and published out to the website. I'll make a PR for that.

**Comment by gunan** [comment]
This seems to be all fixed now. Closing.
