### ISSUE TITLE
TensorFlow Keras Model Hangs when .predict is Called Inside a Thread

### ISSUE THREAD

**Issue by LryF** [tensorflow/tensorflow#39431]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 19.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.7
- CUDA/cuDNN version: 10.1/7.6.5
- GPU model and memory: RTX 2070

This is a copy of a SO question I asked, but I think it deserves bug status and hasn't yet been answered.

When trying to run a TensorFlow Keras model in a thread, it hangs when the `.predict` function is called.  

```python
import multiprocessing as mp
import tensorflow as tf
import numpy as np

def predict(data):
    a = tf.keras.Sequential([tf.keras.layers.Dense(4, input_shape=(16,))])

    return a.predict(data)

fake_data = np.zeros((100, 16))

# Works
for i in range(4):
    print(predict(fake_data).shape)

# Never finishes running
processes = []
for i in range(4):
    p = mp.Process(target=predict, args=(fake_data,))
    p.start()
    processes.append(p)

for p in processes:
    p.join()
```

I'm not sure why this happens, and I've tried wrapping the inside of `predict` with `with tf.device('/cpu:0')`, moving the TensorFlow import to inside the predict function, and calling `_make_predict_function()` with no luck.

I am aware of Keras' built-in multiprocessing with the predict function, however, this code instantiates a new Model for each prediction which is fundamentally different.

This also happens when `model.fit` is called.

**Comment by ravikyram** [comment]
@LryF 

I have tried in colab with TF-GPU 2.1.0.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/417909c88f07fa0cf3dcdab5c06aa7e9/untitled877.ipynb).Is this the expected behavior?Thanks!

**Comment by LryF** [comment]
[Here's](https://gist.github.com/LryF/5ee2e7998f4679bb92dd631029bf18b5) a gist (with gColab link) that replicates my issue.  I can run your code just fine, and I don't know why my gist hangs when `.predict` is called, as our code seems identical.

**Comment by ravikyram** [comment]
@LryF 

Code is same and it runs good in my colab file and i am not sure why it hangs in your file.

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by LryF** [comment]
Alright, thank you for your time!
