### ISSUE TITLE
How to Find the Average of the Input Vectors

### ISSUE THREAD

**Issue by TryArie** [tensorflow/tensorflow#39430]
In the paper "Neural Models for Sequence Chunking", there's a formula 2. It follows:

Chj = Average (h[i], h[i+1], ... h[i+l-1])

I first thought that it was Average Layer, but it said, "Average(·) computes the average of the input vectors."

So it's actually tf.math.reduce_mean, not keras.layers.Average? Or is it really Average Layer?

I tried to use reduce_mean, but it went error.

```
# Input
inputs = Input(shape=(max_length,), name="Input")

# Embedding
embed = Embedding(input_dim=n_words+1,
                  output_dim=embedding_size,
                  input_length=max_length,
                  name="Embedding")(inputs)

# Bi-LSTM
encoder = Bidirectional(LSTM(units=hidden_state_encoder_size,
                             return_sequences=True,
                             dropout=dropout_rate,
                             name="LSTM"),
                        name="Bi-LSTM")

hidden_states = encoder(embed)

# Average
average = tf.math.reduce_mean(hidden_states)

# Outputs
outputs = Dense(n_tags,
                activation="softmax",
                name="Output")(average)
```

Error:

`ValueError: Input 0 is incompatible with layer Output: expected min_ndim=2, found ndim=0`

But, if I use Average layer

```
# Input
inputs = Input(shape=(max_length,), name="Input")

# Embedding
embed = Embedding(input_dim=n_words+1,
                  output_dim=embedding_size,
                  input_length=max_length,
                  name="Embedding")(inputs)

# Bi-LSTM
encoder = Bidirectional(LSTM(units=hidden_state_encoder_size,
                             return_sequences=True,
                             dropout=dropout_rate,
                             name="LSTM"),
                        name="Bi-LSTM")

hidden_states = encoder(embed)

# Average
average = Average()(hidden_states)

# Outputs
outputs = Dense(n_tags,
                activation="softmax",
                name="Output")(average)
```

Error:

`ValueError: A merge layer should be called on a list of inputs.`

**Comment by iobtl** [comment]
Aggregating layers like ```Average()``` are meant to be used with a list of inputs, as stated in the error.
Did you try changing it to:
```python
average = Average()([hidden_states])
```
By function, ```tf.math.reduce_mean``` should perform similarly as well, except it is simply a function whereas ```Average()``` is a layer you can implement as part of your model. 
But when using ```tf.math.reduce_mean``` do take note to retain the dimensions as necessary by passing ```keepdims=True``` and specifying the axes as well.

**Comment by amahendrakar** [comment]
@TryArie,
While running the sample code I am facing an error stating `NameError: name 'max_length' is not defined`.
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. 

Also, please check @iobtl's comment and let us know if it helps. Thanks!

**Comment by TryArie** [comment]
> Aggregating layers like `Average()` are meant to be used with a list of inputs, as stated in the error.
> Did you try changing it to:
> 
> ```python
> average = Average()([hidden_states])
> ```
> 
> By function, `tf.math.reduce_mean` should perform similarly as well, except it is simply a function whereas `Average()` is a layer you can implement as part of your model.
> But when using `tf.math.reduce_mean` do take note to retain the dimensions as necessary by passing `keepdims=True` and specifying the axes as well.

I have tried this before, but unfortunately, it went error.

Thankfully, I've got a friend who helped me with it. S/He said that maybe use GlobalAveragePooling1D. The output will be (batch_size, feature)

average = GlobalAveragePooling1D()(hidden_states)

**Comment by jvishnuvardhan** [comment]
@TryArie If the original issue was resolved by @iobtl suggestion or your friend's suggestion, then please close this issue and open a new issue for the new problem. It will be easy for the users to follow. Thanks!
