### ISSUE TITLE
Initializing the variables of a tensorflow graph over and over again gets slower and slower

### ISSUE THREAD

**Issue by benmyara** [tensorflow/tensorflow#39435]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04, MacOS 10.15.4
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1, 1.14.0
- Python version: 3.6.10
- CUDA/cuDNN version: CPU, CuDNN 9
- GPU model and memory: GeForce GTX Titan 12GB

**Describe the current behavior**

I have a graph consiting of one matrix that I initialize over and over again in a for loop using `sess.run(tf.global_variables_initializer())`.

I noticed that it takes longer and longer to initialize the variables as the iteration progresses. I haven't noticed any memory leak.

**Describe the expected behavior**

The variables initialization speed should not decrease as the iteration progresses.

**Standalone code to reproduce the issue**

Below is a fully reproducible code tested on Linux (CPU + GPU) and MacOS with TensorFlow 1.13.1 and 1.14.0:

```
import tensorflow as tf
import matplotlib.pyplot as plt
import time
from tqdm import tqdm

w = tf.get_variable('w', shape=(100, 1000))

sess = tf.Session()
times = []

for i in tqdm(range(2000)):
    s = time.time()
    sess.run(tf.global_variables_initializer())
    times.append(time.time() - s)

plt.plot(times)
plt.xlabel('iteration')
plt.ylabel('time (s)')
plt.title('Evolution of time per step')
```

![image](https://user-images.githubusercontent.com/16196950/81624193-4497d980-93fe-11ea-9934-7704d34eb44d.png)

**Comment by ravikyram** [comment]
@benmyara 

I have tried in colab with TF 1.13.1, 1.14,1.15 on [cpu](https://colab.sandbox.google.com/gist/ravikyram/df5583ab5f800d87813503e40ad520cc/untitled878.ipynb) and [gpu](https://colab.sandbox.google.com/gist/ravikyram/a4efbd7cb629f92996f871830c36db93/untitled879.ipynb).Is this the expected behavior?Thanks!

**Comment by benmyara** [comment]
@ravikyram Yes, your notebook reproduces the issue.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
