### ISSUE TITLE
MemoryError: Unable to allocate 4.00 MiB for an array with shape (512, 512, 2) and data type float64 ?

### ISSUE THREAD

**Issue by ibrahimLearning** [tensorflow/tensorflow#39442]
Environment:
Windows 10
Anaconda python 3.6
Spyder 3.3.0
Tensorflow 2.1.0
GPU GeForce RTX  11GB

Error during in the middle of training:

> Epoch 294/1500
>  25/100 [======>.......................] - ETA: 16s - loss: 6373.7927 - mean_io_u: 0.9811Traceback (most recent call last):
> 
>   File "<ipython-input-1-39886f6de552>", line 1, in <module>
>     runfile('D:/feasibilityAnalysis/RiversideProject/Code/Semantic-Segmentationtfkeras/Mytrain.py', wdir='D:/feasibilityAnalysis/RiversideProject/Code/Semantic-Segmentationtfkeras')
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "D:/feasibilityAnalysis/RiversideProject/Code/Semantic-Segmentationtfkeras/Mytrain.py", line 283, in <module>
>     initial_epoch=args.initial_epoch)
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 324, in new_func
>     return func(*args, **kwargs)
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1306, in fit_generator
>     initial_epoch=initial_epoch)
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 819, in fit
>     use_multiprocessing=use_multiprocessing)
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 342, in fit
>     total_epochs=epochs)
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 128, in run_one_epoch
>     batch_outs = execution_function(iterator)
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py", line 98, in execution_function
>     distributed_function(input_fn))
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 568, in __call__
>     result = self._call(*args, **kwds)
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 599, in _call
>     return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\eager\function.py", line 2363, in __call__
>     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\eager\function.py", line 1611, in _filtered_call
>     self.captured_inputs)
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\eager\function.py", line 1692, in _call_flat
>     ctx, args, cancellation_manager=cancellation_manager))
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\eager\function.py", line 545, in call
>     ctx=ctx)
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\eager\execute.py", line 67, in quick_execute
>     six.raise_from(core._status_to_exception(e.code, message), None)
> 
>   File "<string>", line 3, in raise_from
> 
> ResourceExhaustedError: 2 root error(s) found.
>   (0) Resource exhausted:  MemoryError: Unable to allocate 4.00 MiB for an array with shape (512, 512, 2) and data type float64
> Traceback (most recent call last):
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\ops\script_ops.py", line 236, in __call__
>     ret = func(*args)
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 789, in generator_py_func
>     values = next(generator_state.get_iterator(iterator_id))
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\keras\utils\data_utils.py", line 881, in get
>     six.reraise(*sys.exc_info())
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\six.py", line 703, in reraise
>     raise value
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\keras\utils\data_utils.py", line 875, in get
>     inputs = self.queue.get(block=True).get()
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\multiprocessing\pool.py", line 644, in get
>     raise self._value
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\multiprocessing\pool.py", line 119, in worker
>     result = (True, func(*args, **kwds))
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\keras\utils\data_utils.py", line 663, in get_index
>     return _SHARED_SEQUENCES[uid][i]
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\keras_preprocessing\image\iterator.py", line 65, in __getitem__
>     return self._get_batches_of_transformed_samples(index_array)
> 
>   File "D:\feasibilityAnalysis\RiversideProject\Code\Semantic-Segmentationtfkeras\utils\data_generator.py", line 76, in _get_batches_of_transformed_samples
>     label = one_hot(label, self.num_classes)
> 
>   File "D:\feasibilityAnalysis\RiversideProject\Code\Semantic-Segmentationtfkeras\utils\utils.py", line 124, in one_hot
>     heat_map = np.ones(shape=label.shape[0:2] + (num_classes,))
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\numpy\core\numeric.py", line 207, in ones
>     a = empty(shape, dtype, order)
> 
> MemoryError: Unable to allocate 4.00 MiB for an array with shape (512, 512, 2) and data type float64
> 
> 
> 	 [[{{node PyFunc}}]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
> 	 [[IteratorGetNext]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
> 	 [[metrics/mean_io_u/StatefulPartitionedCall/confusion_matrix/assert_less_1/Assert/AssertGuard/else/_34/Assert/data_4/_84]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
>   (1) Resource exhausted:  MemoryError: Unable to allocate 4.00 MiB for an array with shape (512, 512, 2) and data type float64
> Traceback (most recent call last):
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\ops\script_ops.py", line 236, in __call__
>     ret = func(*args)
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 789, in generator_py_func
>     values = next(generator_state.get_iterator(iterator_id))
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\keras\utils\data_utils.py", line 881, in get
>     six.reraise(*sys.exc_info())
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\six.py", line 703, in reraise
>     raise value
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\keras\utils\data_utils.py", line 875, in get
>     inputs = self.queue.get(block=True).get()
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\multiprocessing\pool.py", line 644, in get
>     raise self._value
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\multiprocessing\pool.py", line 119, in worker
>     result = (True, func(*args, **kwds))
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\tensorflow_core\python\keras\utils\data_utils.py", line 663, in get_index
>     return _SHARED_SEQUENCES[uid][i]
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\keras_preprocessing\image\iterator.py", line 65, in __getitem__
>     return self._get_batches_of_transformed_samples(index_array)
> 
>   File "D:\feasibilityAnalysis\RiversideProject\Code\Semantic-Segmentationtfkeras\utils\data_generator.py", line 76, in _get_batches_of_transformed_samples
>     label = one_hot(label, self.num_classes)
> 
>   File "D:\feasibilityAnalysis\RiversideProject\Code\Semantic-Segmentationtfkeras\utils\utils.py", line 124, in one_hot
>     heat_map = np.ones(shape=label.shape[0:2] + (num_classes,))
> 
>   File "C:\Users\Ibrahim Khalilullah\.conda\envs\TF2p1p0\lib\site-packages\numpy\core\numeric.py", line 207, in ones
>     a = empty(shape, dtype, order)
> 
> MemoryError: Unable to allocate 4.00 MiB for an array with shape (512, 512, 2) and data type float64
> 
> 
> 	 [[{{node PyFunc}}]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
> 	 [[IteratorGetNext]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
> 0 successful operations.
> 0 derived errors ignored. [Op:__inference_distributed_function_6588]
> 
> Function call stack:
> distributed_function -> distributed_function
> 

Is there any suggestion?

**Comment by amahendrakar** [comment]
@ibrahimLearning,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by ibrahimLearning** [comment]
> 
> 
> @ibrahimLearning,
> In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

Only code is OK? beacuse I cannot share the dataset.
If only code is OK, then I will share it

**Comment by amahendrakar** [comment]
> Only code is OK? beacuse I cannot share the dataset.
> If only code is OK, then I will share it

@ibrahimLearning, 
If possible, please share the both the code and dataset. If the data is confidential, please share a dummy dataset so that we can reproduce the error. Thanks!

**Comment by elanstop** [comment]
I am having the same issue

**Comment by moinabyssinia** [comment]
I do have the same issue 
"MemoryError: Unable to allocate 30.5 GiB for an array with shape (124993, 32744) and data type float64"

**Comment by amahendrakar** [comment]
@elanstop, @moinabyssinia,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by liangshui-pts** [comment]
same error, does anybody solved this or know why?

**Comment by darveshsharma** [comment]
buddy i got same error i shutdown all other programs and tried again and it's running u can try it too

**Comment by lintanggilang** [comment]
same error, how to solved this?

**Comment by darveshsharma** [comment]
buddy just shutdown the server and try again

**Comment by karbapi** [comment]
Hi All,
I have the same issue.
MemoryError: Unable to allocate 4.48 MiB for an array with shape (XX, XX).. Mere 4.48MB could not be allocated in a W10 machine with 16GB RAM and GPU having 4GB memory? Please help.
Thanks

**Comment by amahendrakar** [comment]
@liangshui-pts, @lintanggilang, @karbapi,

Please take a look at @darveshsharma's comment and if y'all are still facing the same error, please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by KartikHegde64bit** [comment]
@karbapi I'm having the same issue. Did you resolve it? If yes how?!

**Comment by karbapi** [comment]
Hi,
You may try this, after model.predict() call, 
keras.backend.clear_session()

Sorry for my late reply.

Regards,
Bapi

**Comment by AngshuBh10** [comment]
> buddy just shutdown the server and try again

I tried but not working

**Comment by Oruns** [comment]
I got this same issue on VS code. I was trying to fit a dataset into a Linear regression model. 

MemoryError: Unable to allocate 464. MiB for an array with shape (16512, 3683) and data type float64

**Comment by Ahsankiani8** [comment]
how we give this line 184.mb for any array with shape of (899,19999)

**Comment by mady2016w** [comment]
Hey I am having the same error
Unable to allocate 182. MiB for an array with shape (16598, 11494) and data type uint8

**Comment by Ahsankiani8** [comment]
Hello bro,
 i hope u r fine  and well . bro i use google colab for this issue and all my problem are solve here are the link
https://colab.research.google.com/drive/1CXuC0GkTwQk1L4Phd0d344iO0pIhrFXp
[https://colab.research.google.com/img/colab_favicon_256px.png]<https://colab.research.google.com/drive/1CXuC0GkTwQk1L4Phd0d344iO0pIhrFXp>
Google Colaboratory<https://colab.research.google.com/drive/1CXuC0GkTwQk1L4Phd0d344iO0pIhrFXp>
colab.research.google.com


________________________________

**Comment by mady2016w** [comment]
Hey thanks for your help

**Comment by mady2016w** [comment]
@Ahsankiani8 Hey when I open your link its says I am denied access to the it.
Hope you will answer soon.

**Comment by Ahsankiani8** [comment]
Hello bro ,

  How are you ,what is the actuallly issue you are facing .i think you are using jupyter notebook and your dataset is big
so kindly use google colabs .i think you get my point

________________________________

**Comment by Ahsankiani8** [comment]
https://www.google.com/search?q=google+colabs&oq=google+colabs&aqs=chrome.0.69i59j0i10i457j0i10l6.3844j0j7&sourceid=chrome&ie=UTF-8
here is the link of google colabs
and i m sending you a file to check how we are upload and use a file
________________________________

**Comment by mady2016w** [comment]
hey its still showing that error with exact details about memory

**Comment by Netsanet21** [comment]
i do have the same error please tell how to handle this problem with code

MemoryError: Unable to allocate 4.49 GiB for an array with shape (4000, 224, 224, 3) and data type float64

**Comment by mady2016w** [comment]
@Netsanet21 try breaking your data into parts it would help

**Comment by sole12343** [comment]
很简单，就是内存不够用了，把一些后台软件关掉就可以了

**Comment by sole12343** [comment]
很简单，就是内存不够用了，把一些后台软件关掉就可以了
