### ISSUE TITLE
Has someone ported tensorflow example codes to anyother microcontroller?

### ISSUE THREAD

**Issue by ms-ims** [tensorflow/tensorflow#39447]
Need porting information of tensorflow? I'm trying to use tensorflow example on my RX family  Microcontroller. Can someone help me?

**Comment by mohantym** [comment]
Hi @ms-ims !
We are checking to see whether you still need help in this issue . Supported Microcontrollers can be found from [here](https://www.tensorflow.org/lite/microcontrollers#supported_platforms).Please post this on Stackoverflow/[TF forum ](https://discuss.tensorflow.org/)for further assistance. Thank you!
