### ISSUE TITLE
how to set the gpu device in tensorflow? 

### ISSUE THREAD

**Issue by SlowMonk** [tensorflow/tensorflow#39440]
import os
os.environ["CUDA_VISIBLE_DEVICES"]="1"

this command does not set to the device 1 it keep using the device 0

**Comment by Saduf2019** [comment]
@SlowMonk

They are represented with string identifiers for example: "/device:CPU:0" : The CPU of your machine. "/GPU:0" : Short-hand notation for the first GPU of your machine that is visible to TensorFlow.

Please check these links for reference [link](https://www.tensorflow.org/guide/gpu), [link1](https://stackoverflow.com/questions/51306862/how-to-use-tensorflow-gpu), [link2](https://stackoverflow.com/questions/38559755/how-to-get-current-available-gpus-in-tensorflow) , [link3](https://databricks.com/tensorflow/using-a-gpu), [link4](https://medium.com/@liyin2015/tensorflow-cpus-and-gpus-configuration-9c223436d4ef), [link5](https://data-flair.training/blogs/gpu-in-tensorflow/), [link5](https://github.com/carla-simulator/carla/issues/116), [link6](url) 
let us know if this helps.

**Comment by Saduf2019** [comment]
@SlowMonk
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 
We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!
