### ISSUE TITLE
Asynchronous keras model loading

### ISSUE THREAD

**Issue by AleksandrBykov** [tensorflow/tensorflow#39450]
Dear developers, 

May I ask if you could create a way to asynchronously load several Keras models at the same time? I am developing a software where I need to load approximately 50-100 models into a single python programme from local files and it takes a lot of time to do that because I can not find a way to do it in a non-consecutive way.

Let me know if I am missing something. So far, I was not able to use any kind of multithreading to achieve that due to gridlocks.

Yours sincerely,
Aleksandr Bykov

**Comment by karmel** [comment]
At this time, we do not support python multithreading in Keras, as we found there were many issues and unknowns in how people were intending to use multithreading. If this is an area you are interested in, we would be willing to consider a proposal for how and what we should support here via an RFC: https://www.tensorflow.org/community/contribute/rfc_process
