### ISSUE TITLE
IdentityN

### ISSUE THREAD

**Issue by Keegan007** [tensorflow/tensorflow#39464]
**System information**
- Google Colab
- TensorFlow 1.15.2

1
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONV_2D, FULLY_CONNECTED, MAX_POOL_2D, SOFTMAX. Here is a list of operators for which you will need custom implementations: IdentityN.
Traceback (most recent call last):
  File "/tensorflow-1.15.2/python3.6/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52, in execute
    enable_mlir_converter)

2
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONV_2D, FULLY_CONNECTED, MAX_POOL_2D, SOFTMAX. Here is a list of operators for which you will need custom implementations: IdentityN.

**Standalone code to reproduce the issue** 
https://colab.research.google.com/drive/1aAaQ7kq2BDYRlspmM-N2Uuh6CZkQGRNb?usp=sharing

![FlexIdentityN seen in Netron](https://user-images.githubusercontent.com/62724378/81730803-b1b57880-94ab-11ea-9166-50e71d1c275e.png)

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by amahendrakar** [comment]
@Keegan007,
Could you please share the Dropbox file and the dataset you are using in the code. I am facing a `403: Forbidden` error while accessing the file. Thanks!

**Comment by Keegan007** [comment]
Thanks for the quick response, here is the Dropbox File Link
https://www.dropbox.com/s/3lg5eomeyedkuo5/Image_Dataset-20200327T051009Z-001.zip?dl=0

**Comment by amahendrakar** [comment]
@Keegan007,
Please add the below two lines to your code before converting the model.
```
converter.experimental_new_converter = True
converter.target_spec.supported_ops =[tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS] 
```

With these lines of code added, I was able to convert the model without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/b8f68c8df1fbaf4dd165700c379a77f7/39464.ipynb). Thanks!
