### ISSUE TITLE
model.fit hangs if validation_steps is zero

### ISSUE THREAD

**Issue by vasudev13** [tensorflow/tensorflow#39465]
**System information**
- I written custom code (as opposed to using a stock example script provided in TensorFlow)
- **OS Platform and Distribution:** Kaggle Kernel, 'Linux-4.19.112+-x86_64-with-debian-buster-sid'
- **TensorFlow installed from (source or binary):** installed from pip
- **TensorFlow version (use command below):** 2.1
- **Python version:** 3.7.6
- **CUDA/cuDNN version:** V10.1.243
- **GPU model and memory:** Tesla P100-PCIE-16GB

**Current Behaviour**
`model.fit` suspends  execution or hangs after training first epoch runs if value passed for `validation_steps=len(valid_inputs)//BATCH_SIZE` is equal to zero. 
Moreover, **validate for _x_ steps** is not printed before training starts.

I believe a ValueError could be raised if validation_steps is 0 and not None. (or execution could proceed further with next epoch over training set) 

**Standalone code to reproduce the issue**
```
VALIDATION_STEPS=len(valid_noisy)//BATCH_SIZE # Results in 0
model.fit(
    train_dataset,
    steps_per_epoch=len(train_noisy)//BATCH_SIZE,
    epochs=200,
    validation_data=valid_dataset,
    validation_steps=VALIDATION_STEPS
)

```
[Complete Notebook](https://nbviewer.jupyter.org/github/vasudev13/No-Pain-No-GANz/blob/master/conv%20autoencoders/src/notebooks/denoising-dirty-documents.ipynb) 

If feasible, can I contribute via a PR if the above issue is valid and can be addressed by not a core contributor?

Thanks a bunch!

**Comment by ravikyram** [comment]
@vasudev13 

I have tried in colab with TF version 2.2 .Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/13162b5144c0165282059bf06b3e420d/untitled886.ipynb).Is this the expected behavior? Thanks!

**Comment by vasudev13** [comment]
Close enough, in
```
train_noisy,valid_noisy,train_clean,valid_clean=train_test_split(noisy_paths,clean_paths,test_size=0.1,random_state=SEED)

VALIDATION_STEPS=1 # len(valid_noisy)//BATCH_SIZE = 0
```
change the following:
`VALIDATION_STEPS=len(valid_noisy)//BATCH_SIZE ` and print the value, its probably going to be 0. 
If fit is called with that argument (i.e. value 0) for parameter `validatiton_steps` value, it just hangs after first training iteration as opposed to some message or error being raised.

Thanks for quick response!

**Comment by ymodak** [comment]
Can you please test with tf-nightly version? Thanks!

**Comment by vasudev13** [comment]
@ymodak I tried with nightly and was getting an altogether different error, fit gives error on training itself. However, with 2.2 it does raise an error on validation (training epoch does occur) but not exactly to this issue in particular. 
I apologise for the late response. Should I attach detail error logs?

**Comment by ymodak** [comment]
Yes please attach new error logs.
I created a toy model that uses validation_steps = 0 and happens to execute successfully.
Please take a look at the [gist](https://colab.research.google.com/gist/ymodak/817034ec377485f4383e822ae9dd50c7/39465.ipynb)

**Comment by vasudev13** [comment]
@ymodak , checked with version 2.3, the execution is successful
Thanks for helping out to you and @ravikyram as well, you can close this issue!

**Comment by vasudev13** [comment]
One peculiar thing, I noticed when changing `validation_steps` argument from 0 to say 1 (or any non-zero integer) in the following snippet, validation step is still not performed (see pic 1), as well as the vice-versa i.e. when changing from 1 to 0, validation is performed (see pic 2) as opposed to not being performed. This occurs only when rerunning the same code cell in the notebook without restarting.

```
model.fit(
    train_dataset,
    steps_per_epoch=len(train_noisy)//BATCH_SIZE,
    epochs=200,
    validation_data=valid_dataset,
    validation_steps=1
)
```
![a](https://user-images.githubusercontent.com/30664477/91100972-c943f600-e683-11ea-8ffa-b15515874078.PNG)

![b](https://user-images.githubusercontent.com/30664477/91102044-08734680-e686-11ea-8faf-592ddd7454ab.png)


You can look into this if you get the time. Thanks for your patience and help!
