### ISSUE TITLE
tf-nightly-gpu not updated?

### ISSUE THREAD

**Issue by nlpyoda** [tensorflow/tensorflow#39460]
the lastest version I can pip install is 20200508, it hasn't been updated? I thought my pip manager broke or something.

**Comment by amahendrakar** [comment]
@nlpyoda,
The latest tf-nightly version has been updated to 2.3.0.dev20200512. I'm not sure what the delay was for. Could you please check if you are able to install the latest version? Thanks!

**Comment by nlpyoda** [comment]
It's working now. Upgrading to 20200513. thanks for checking!

**Comment by amahendrakar** [comment]
> It's working now. Upgrading to 20200513. thanks for checking!

@nlpyoda,
Thank you for the update. Please feel free to close the issue if resolved. Thanks!
