### ISSUE TITLE
tensorflow-gardener fighting with itself

### ISSUE THREAD

**Issue by jarednielsen** [tensorflow/tensorflow#39476]
I'm not sure if anyone cares, but parsing the commit history, it appears that tensorflow-gardener is repeatedly adding whitespace and then removing whitespace from the same file. It does this 5-6 times a day and has been doing so for at least the last month. You could probably cut the # of commits in half by fixing this bug.

See https://github.com/tensorflow/tensorflow/commits/ec2837b2a112ae3ada2c10173c12ed9b2f129b02/tensorflow/go/op/wrappers.go

**Comment by rthadur** [comment]
@jarednielsen thanks for reporting the issue we will definitely take care of it.

**Comment by jhseu** [comment]
Thanks for reporting! Fixed.
