### ISSUE TITLE
macOS build issue with tflite using make

### ISSUE THREAD

**Issue by dtrodrigues** [tensorflow/tensorflow#39478]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.15.4 (Catalina)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): Apple clang version 11.0.3
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
When attempting to build from source on macOS using `make`, the `benchmark_model` binary fails to build due to the `--whole-archive` flag

**Provide the exact sequence of commands / steps that you executed before running into the problem**

    ./tensorflow/lite/tools/make/download_dependencies.sh
    ./tensorflow/lite/tools/make/build_lib.sh

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
$ ./tensorflow/lite/tools/make/build_lib.sh
+ set -e
+++ dirname ./tensorflow/lite/tools/make/build_lib.sh
++ cd ./tensorflow/lite/tools/make
++ pwd
+ SCRIPT_DIR=/Users/username/tensorflow-master/tensorflow/lite/tools/make
+ TENSORFLOW_DIR=/Users/username/tensorflow-master/tensorflow/lite/tools/make/../../../..
+ make -j 4 -C /Users/username/tensorflow-master/tensorflow/lite/tools/make/../../../.. -f tensorflow/lite/tools/make/Makefile
g++ -O3 -DNDEBUG -fPIC --std=c++11  -DTFLITE_WITHOUT_XNNPACK -I. -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/../../../../../ -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/../../../../../../ -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/downloads/ -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/downloads/eigen -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/downloads/absl -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/downloads/gemmlowp -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/downloads/ruy -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/downloads/neon_2_sse -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/downloads/farmhash/src -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/downloads/flatbuffers/include -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/downloads/fp16/include -I -I/usr/local/include \
  -o /Users/username/tensorflow-master/tensorflow/lite/tools/make/gen/osx_x86_64/bin/benchmark_model /Users/username/tensorflow-master/tensorflow/lite/tools/make/gen/osx_x86_64/obj/tensorflow/lite/tools/benchmark/benchmark_main.o \
   -Wl,--whole-archive /Users/username/tensorflow-master/tensorflow/lite/tools/make/gen/osx_x86_64/lib/benchmark-lib.a -Wl,--no-whole-archive  -lstdc++ -lpthread -lm -lz -ldl
g++ -O3 -DNDEBUG -fPIC --std=c++11  -DTFLITE_WITHOUT_XNNPACK -I. -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/../../../../../ -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/../../../../../../ -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/downloads/ -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/downloads/eigen -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/downloads/absl -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/downloads/gemmlowp -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/downloads/ruy -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/downloads/neon_2_sse -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/downloads/farmhash/src -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/downloads/flatbuffers/include -I/Users/username/tensorflow-master/tensorflow/lite/tools/make/downloads/fp16/include -I -I/usr/local/include \
  -o /Users/username/tensorflow-master/tensorflow/lite/tools/make/gen/osx_x86_64/bin/benchmark_model_performance_options /Users/username/tensorflow-master/tensorflow/lite/tools/make/gen/osx_x86_64/obj/tensorflow/lite/tools/benchmark/benchmark_tflite_performance_options_main.o \
   /Users/username/tensorflow-master/tensorflow/lite/tools/make/gen/osx_x86_64/lib/benchmark-lib.a  -lstdc++ -lpthread -lm -lz -ldl
ld: unknown option: --whole-archive
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/username/tensorflow-master/tensorflow/lite/tools/make/gen/osx_x86_64/bin/benchmark_model] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by Saduf2019** [comment]
@dtrodrigues  
Can you please refer to below issues with similar error. and let us know if it helps
#31190 #30117 #25058 #39025 #29658 #30564 #28988 #26589

**Comment by dtrodrigues** [comment]
None of those are describing the same error. I believe the issue I'm having has to do with clang and the `--whole-archive` option.

**Comment by terryheo** [comment]
You don't need to use Makefile since bazel is available for MacOS.
You can just use
```
$ bazel build tensorflow/lite:tensorflowlite
```

**Comment by dtrodrigues** [comment]
I was able to build it successfully using bazel. However, the Makefile implies that MacOS is an intended target when using plain make: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/make/Makefile#L19 and the other make targets (such as `libtensorflow-lite.a` and the `minimal` binary) do build with the Makefile on MacOS -- just not the `benchmark` target which builds the `benchmark_model` binary.

**Comment by dtrodrigues** [comment]
Is there an update on this? Is MacOS supported as a `make` target for tensorflowlite?

**Comment by terryheo** [comment]
Could you check it with master?
I've just checked it. There is an issue with building ruy now.
After reverting the change f15d6e1efc1c52d183882b51acd0ca304f7ba82e, I can run  ./tensorflow/lite/tools/make/build_lib.sh without any error.

**Comment by dtrodrigues** [comment]
I did a fresh checkout and build against master and it looks good now. Thanks!
