### ISSUE TITLE
Tensorflow _  Symbol Initializer is already exposed as ()

### ISSUE THREAD

**Issue by Muhammad-naji** [tensorflow/tensorflow#39483]
Hello Everyone,
I'm trying to run the code posted on this page:

https://medium.com/dataflair/class-data-science-project-for-2020-traffic-signs-recognition-12b09c131742

OS: windows 10
Python: 3.6.1 (I've tried many versions, same issue)
I'm using anaconda 3
I've faced a Tensorflow Failure
I've tried the recommendations in posted in this discussion:
https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c

Now, I'm getting new error as follows:

---------------------------------------------------------------------------
SymbolAlreadyExposedError                 Traceback (most recent call last)
<ipython-input-2-644c6f02db98> in <module>
      4 import matplotlib.pyplot as plt
      5 from PIL import Image
----> 6 import tensorflow as tf
      7 from sklearn.model_selection import train_test_split
      8 from keras.utils import to_categorical

~\anaconda3\lib\site-packages\tensorflow\__init__.py in <module>
     25 import sys as _sys
     26 
---> 27 from tensorflow._api.v2 import audio
     28 from tensorflow._api.v2 import autograph
     29 from tensorflow._api.v2 import bitwise

~\anaconda3\lib\site-packages\tensorflow\_api\v2\audio\__init__.py in <module>
      6 from __future__ import print_function as _print_function
      7 
----> 8 from tensorflow.python.ops.gen_audio_ops import decode_wav
      9 from tensorflow.python.ops.gen_audio_ops import encode_wav
     10 

~\anaconda3\lib\site-packages\tensorflow\python\ops\gen_audio_ops.py in <module>
      7 import six as _six
      8 
----> 9 from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
     10 from tensorflow.python.eager import context as _context
     11 from tensorflow.python.eager import core as _core

~\anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>
     81 from tensorflow.python import data
     82 from tensorflow.python import distribute
---> 83 from tensorflow.python import keras
     84 from tensorflow.python.feature_column import feature_column_lib as feature_column
     85 from tensorflow.python.layers import layers

~\anaconda3\lib\site-packages\tensorflow\python\keras\__init__.py in <module>
     35 from tensorflow.python.keras import metrics
     36 from tensorflow.python.keras import models
---> 37 from tensorflow.python.keras import ops
     38 from tensorflow.python.keras import optimizers
     39 from tensorflow.python.keras import preprocessing

~\anaconda3\lib\site-packages\tensorflow\python\keras\ops.py in <module>
     26 # pylint: disable=bad-continuation
     27 keras_export(v1=["keras.initializers.Initializer"])(
---> 28     init_ops.Initializer)
     29 keras_export(v1=["keras.initializers.Zeros", "keras.initializers.zeros"])(
     30     init_ops.Zeros)

~\anaconda3\lib\site-packages\tensorflow\python\util\tf_export.py in __call__(self, func)
    332 
    333     _, undecorated_func = tf_decorator.unwrap(func)
--> 334     self.set_attr(undecorated_func, api_names_attr, self._names)
    335     self.set_attr(undecorated_func, api_names_attr_v1, self._names_v1)
    336     return func

~\anaconda3\lib\site-packages\tensorflow\python\util\tf_export.py in set_attr(self, func, api_names_attr, names)
    344         raise SymbolAlreadyExposedError(
    345             'Symbol %s is already exposed as %s.' %
--> 346             (func.__name__, getattr(func, api_names_attr)))  # pylint: disable=protected-access
    347     setattr(func, api_names_attr, names)
    348 

SymbolAlreadyExposedError: Symbol Initializer is already exposed as ().

**Could you please help me**

**Comment by ravikyram** [comment]
@Muhammad-naji 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by Muhammad-naji** [comment]
Thanks @ravikyram for your reply, I've put some extra time on this issue and discovered some interesting things:
1- I was using old version of Tensorflow that is not compatible with python 3.7 (the default version that comes wit Anaconda), I should use Tensorflow 2.0.0
2-  Tensorflow  wasn't activated, since I should activate it using this command (conda activate Tensorflow) even, if it's installed it will not work without this!, maybe it's a dummy thing, but I'm new in this!
After all, I discovered that with Google Colab there are no problems with Tensorflow and you will not face this issue at all, but I discovered it in the hard way! :)
