### ISSUE TITLE
Add support of uint8 and int8 for MEAN op

### ISSUE THREAD

**Issue by wenhui-prudencemed** [tensorflow/tensorflow#39489]
@tensorflow/micro

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/kernels/reduce.cc#L113

// TODO(b/144955155): Support uint8(b/144955155) and int8(b/144955018)

Could you implement this so we can use the MEAN op in int8 model?

**Comment by daverim** [comment]
Hi Meghna,

Can you give an update on these bugs?

**Comment by MeghnaNatraj** [comment]
@petewarden I've re-assigned the task.

**Comment by luke-iqt** [comment]
Are there any good work arounds for this? I am trying to do transfer learning on MobileNet and then run it on TF Micro.
Following the TF Tutorial, it uses a GlobalAveragePooling2D layer before the classifier which uses the reduce() function in it. Is there an alternate architecture that would work?

````
global_average_layer = tf.keras.layers.GlobalAveragePooling2D()
feature_batch_average = global_average_layer(feature_batch) 
prediction_layer = tf.keras.layers.Dense(1)
prediction_batch = prediction_layer(feature_batch_average)
print(prediction_batch.shape)

x = global_average_layer(x)
x = tf.keras.layers.Dropout(0.2)(x)
outputs = prediction_layer(x)
model = tf.keras.Model(inputs, outputs)
````

**Comment by MeghnaNatraj** [comment]
You can get rid of the mean op dependency by replacing `GlobalAveragePooling2D()` with two operators as follows:

**BEFORE**
```
base_model =  tf.keras.applications.MobileNetV2(....)
model = tf.keras.Sequential([
    base_model,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(1)
])
```

**AFTER**
```
base_model =  tf.keras.applications.MobileNetV2(....)
model = tf.keras.Sequential([
    base_model,
    tf.keras.layers.AveragePooling2D(POOL_SIZE),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(1),
])
```

Let us know if this works for you!

**Comment by luke-iqt** [comment]
@MeghnaNatraj Thanks for responding! That fix worked perfectly. I was able to export a TFLite model and run it on an OpenMV H7 Plus.
