### ISSUE TITLE
Add support of float in lite/kernels/kernel_util.cc#CalculateActivationRangeQuantized

### ISSUE THREAD

**Issue by wenhui-prudencemed** [tensorflow/tensorflow#39487]
Source:  https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/kernel_util.cc#L197

the CalculateActivationRangeQuantized method which only supports int8 and int16 output and raise error for float type:

```
  int32_t qmin = 0;
  int32_t qmax = 0;
  if (output->type == kTfLiteUInt8) {
    qmin = std::numeric_limits<uint8_t>::min();
    qmax = std::numeric_limits<uint8_t>::max();
  } else if (output->type == kTfLiteInt8) {
    qmin = std::numeric_limits<int8_t>::min();
    qmax = std::numeric_limits<int8_t>::max();
  } else if (output->type == kTfLiteInt16) {
    qmin = std::numeric_limits<int16_t>::min();
    qmax = std::numeric_limits<int16_t>::max();
  } else {
    TF_LITE_ENSURE(context, false);
  }
```

Could you add support so we can use float model after quantization

**Comment by pjpratik** [comment]
@wenhui-prudencemed Calculating activation ranges for float type does not seem to be feasible as the range of possible values for float data type is much larger.

To use float model after quantization,  you can consider adding `converter.optimizations = [ ]` during post training quantization. It helps the converted model to fallback to floating point precision. The converted model uses floating point hardware when available at the targeted device. 

Please refer to the [post training quantization](https://www.tensorflow.org/lite/performance/post_training_quantization) for more details and let us know if it helps.

Thank you.

**Comment by pjpratik** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks!
