### ISSUE TITLE
How to invoke Flex delegate for FlexIdentityN node on Raspberry Pi

### ISSUE THREAD

**Issue by Keegan007** [tensorflow/tensorflow#39492]
**System information**
- Google Colab and Raspberry Pi 4

FlexIdentityN Tensorflow Lite Custom Ops Error

Hello,

For our project we tried to build an Image Classification Model using a CNN to detect 4 categories of waste. The link to the full model code is shared below.

https://colab.research.google.com/drive/1aAaQ7kq2BDYRlspmM-N2Uuh6CZkQGRNb?usp=sharing

We used Tensorflow 1.15 instead of the latest Tensorflow 2.2 because I couldn’t get the validation split command in model.fit to work on Tensorflow 2 (Any explanation for this problem will be appreciated too). Looking at newer tutorials now, I believe we have to split the data into training and testing data, instead of using validation split, correct? 

The model needs to be deployed on a Raspberry Pi 4 module. To do that whilst converting the model file to a .tflite file to run on the Raspberry Pi, we encountered this problem.

Errors

(1.
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONV_2D, FULLY_CONNECTED, MAX_POOL_2D, SOFTMAX. Here is a list of operators for which you will need custom implementations: IdentityN.
Traceback (most recent call last):
File "/tensorflow-1.15.2/python3.6/bin/toco_from_protos", line 8, in
sys.exit(main())
File "/tensorflow-1.15.2/python3.6/tensorflow_core/lite/toco/python/toco_from_protos.py", line 89, in main
app.run(main=execute, argv=[sys.argv[0]] + unparsed)
File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/platform/app.py", line 40, in run
_run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
_run_main(main, args)
File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
sys.exit(main(argv))
File "/tensorflow-1.15.2/python3.6/tensorflow_core/lite/toco/python/toco_from_protos.py", line 52, in execute
enable_mlir_converter)

2.
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONV_2D, FULLY_CONNECTED, MAX_POOL_2D, SOFTMAX. Here is a list of operators for which you will need custom implementations: IdentityN.)

![FlexIdentityN seen in Netron](https://user-images.githubusercontent.com/62724378/81785708-3b049380-951c-11ea-9570-c31dece7aa6d.png)

As of now, I have no explanation as to how the FlexIdentityN Layer is formed and why. Any explanation on that will be appreciated as well.

These Errors can be solved(?) Using the following code.
```
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                         tf.lite.OpsSet.SELECT_TF_OPS]
```

However the same IdentityN Error pops up on the Raspberry Pi 4 when running the code also shown in the Google Colab file. The Error on the Raspberry Pi is shown below.

![FlexIdentityN Error](https://user-images.githubusercontent.com/62724378/81785756-4fe12700-951c-11ea-8f55-9c2194daf41c.png)

The link to the full Raspberry Pi Code is below.

https://colab.research.google.com/drive/1ptbKJ5CmQDjnTChzEIJ-5uyjYaiNYWqg?usp=sharing

I’ve followed this tutorial on YouTube by Edje Electronics to install Tensorflow on the Raspberry Pi.

https://www.youtube.com/watch?v=aimSGOAUI8Y

The Tutorial automatically installs the latest version in a virtual environment. (Maybe the difference in tensorflow version could be a problem)

Thank You.

**Comment by thaink** [comment]
Hi Keegan007,
Since TFLite does not have IdentityN op, it is formed as FlexIdentityN to use the Tensorflow implementation.
How are you running your model on Raspberry?
There are some guide about this here: https://www.tensorflow.org/lite/guide/ops_select

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
