### ISSUE TITLE
Bug when using TensorFlow Lite Object Detection Android Demo for a custom model

### ISSUE THREAD

**Issue by Ringhu** [tensorflow/tensorflow#39495]
Hi, I'm using the [TensorFlow Lite Object Detection Android Demo](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android) for my object detection model on Pixel 4.
The demo is all right and operating normally on Pixel 4, but when I used other custom model such as [ssd_mobilenet_v2_mnasfpn_coco](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_mnasfpn_shared_box_predictor_320x320_coco_sync_2020_05_06.tar.gz) and [ssd_mobilenet_v3_large_coco](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v3_large_coco_2020_01_14.tar.gz), the app will flash and quit, sometimes report error:
![Screenshot_20200513-162420](https://user-images.githubusercontent.com/47172283/81790612-351cab80-9538-11ea-91d1-e1b904f5faa5.png)

Can anyone help about this error?

**Comment by smilingday** [comment]
@Ringhu, thanks for reporting this. We will take a look. @lintian06 
Meanwhile,  maybe you can also check more detailed crash logs, to see which part has issues. Welcome PR for fixing :-)

**Comment by lintian06** [comment]
As this is a custom model from [object detection](https://github.com/tensorflow/models/tree/master/research/object_detection) research models , inputs and outputs might be slightly different from case to case. They need to be aligned with those [inputs and outputs](https://github.com/tensorflow/examples/blob/4d3a5d2b3a8fa9eeba9789544b10aaa1db3b71ac/lite/examples/object_detection/android/app/src/main/java/org/tensorflow/lite/examples/detection/tflite/TFLiteObjectDetectionAPIModel.java#L181-L191) in the Android App.

I would suggest check inputs and outputs, especially focusing on the size and data type. In the [code sample](https://www.tensorflow.org/lite/guide/inference), you can check the input and output by using `input_details` and `output_details` in our python API.

**Comment by Ringhu** [comment]
Hi @lintian06 , thank you for ur response first. I checked the input and ouput details:
```
[{'name': 'normalized_input_image_tensor', 'index': 260, 'shape': array([  1, 300, 300,   3], dtype=int32), 'shape_signature': array([  1, 300, 300,   3], dtype=int32), 'dtype': <class 'numpy.uint8'>, 'quantization': (0.0078125, 128), 'quantization_parameters': {'scales': array([0.0078125], dtype=float32), 'zero_points': array([128], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
>>> output_details = interpreter.get_output_details()
>>> print(output_details)
[{'name': 'TFLite_Detection_PostProcess', 'index': 252, 'shape': array([  1, 100,   4], dtype=int32), 'shape_signature': array([  1, 100,   4], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'TFLite_Detection_PostProcess:1', 'index': 253, 'shape': array([  1, 100], dtype=int32), 'shape_signature': array([  1, 100], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'TFLite_Detection_PostProcess:2', 'index': 254, 'shape': array([  1, 100], dtype=int32), 'shape_signature': array([  1, 100], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'TFLite_Detection_PostProcess:3', 'index': 255, 'shape': array([1], dtype=int32), 'shape_signature': array([1], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
```
I modified the `TFLiteObjectDetectionAPIModel.java` file, but still got the crash problem.

Besides, the demo file supports 80 classes in COCO, since the latest version of COCO contains 91 classes, I suggest update the demo repo if it's possible.

**Comment by Ajay-Reva** [comment]
Do we have solution to this issue? I am facing this issue as well.

**Comment by Ajay-Reva** [comment]
I get the exception "Detector could not be initialized" when I try to use a .tflite file that I created from MobileNet SSD V2 from the Tensorflow Object Detection API (https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md)
