### ISSUE TITLE
tensorflow_cc.dll build fails when enabling MKL (Windows 10)

### ISSUE THREAD

**Issue by Lotte1990** [tensorflow/tensorflow#39490]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.2.0
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): MSVC 2019

**Describe the problem**
tensorflow_cc.dll build fails when enabling MKL

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Add indicated line (with +) to tensorflow/lite/build_def.bzl (line 162)
```
tf_cc_shared_object(
    name = name,
    copts = copts,
+   features = ["windows_export_all_symbols"],
    linkstatic = linkstatic,
    linkopts = linkopts + tflite_jni_linkopts(),
```

```
python configure.py
    empty
    empty
    n
    n
    empty
    n
```

`bazel build -c opt --config=mkl //tensorflow:tensorflow_cc`

**Any other info / logs**
```
ERROR: D:/tensorflow-2.2.0/tensorflow/core/kernels/BUILD:7965:1: C++ compilation of rule '//tensorflow/core/kernels:mkl_input_conversion_op' failed (Exit 2)
.\tensorflow/core/util/mkl_util.h(1263): error C2131: expression did not evaluate to a constant
.\tensorflow/core/util/mkl_util.h(1262): note: failure was caused by a read of a variable outside its lifetime
.\tensorflow/core/util/mkl_util.h(1262): note: see usage of 'dim'
.\tensorflow/core/util/mkl_util.h(1264): error C2131: expression did not evaluate to a constant
.\tensorflow/core/util/mkl_util.h(1262): note: failure was caused by a read of a variable outside its lifetime
.\tensorflow/core/util/mkl_util.h(1262): note: see usage of 'dim'
.\tensorflow/core/util/mkl_util.h(1266): error C3863: array type 'dnnl_dim_t [kNumDims]' is not assignable
.\tensorflow/core/util/mkl_util.h(1267): error C3863: array type 'dnnl_dim_t [kNumDims]' is not assignable
Target //tensorflow:tensorflow_cc failed to build
INFO: Elapsed time: 7603.936s, Critical Path: 3739.78s
INFO: 5297 processes: 5297 local.
FAILED: Build did NOT complete successfully
```
I also get this warning, which is probably unrelated:
`WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/387c3f74fd8efdc0be464b0e1a8033cc1eeb739c.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
`

**Comment by Lotte1990** [comment]
Any updates on this?

**Comment by Lotte1990** [comment]
@Saduf2019 @TensorFlow-MKL Any updates on this?

**Comment by Dave-Stein** [comment]
We need to include this =>  label:"stat:awaiting response"

**Comment by Dave-Stein** [comment]
[Latest reasons](https://github.com/tensorflow/tensorflow/issues/39905#issuecomment-641588284) why nothing happens for last 6 months for Windows DLL for TF2.0, TF2.1 and TF2.2

**Comment by gunan** [comment]
@claynerobison @penpornk is MKL supported on windows?

**Comment by gunan** [comment]
Sorry, I mean for TF, do we support building with MKL on windows. MKL itself is indeed supported.

**Comment by penpornk** [comment]
@gunan Yes, TF-MKL can be built on Windows. Here is the [instructions](https://software.intel.com/content/www/us/en/develop/articles/intel-optimization-for-tensorflow-installation-guide.html#wind_B_S).
I'm going to re-assign @TensorFlow-MKL back for help with this issue.

**Comment by gunan** [comment]
Oops, I missed that.
@Saduf2019 please leave the issue assigned to @TensorFlow-MKL 
MKL issues are triaged by intel through that user.

**Comment by Lotte1990** [comment]
@penpornk the link you provided is related to building the pip package. I'm trying to build tensorflow_cc.dll with MKL (it builds fine without MKL).

**Comment by NeoZhangJianyu** [comment]
> @penpornk the link you provided is related to building the pip package. I'm trying to build tensorflow_cc.dll with MKL (it builds fine without MKL).
@Lotte1990 Do you have any progress?
We are reproducing it now. It's on going.

**Comment by NeoZhangJianyu** [comment]
@Lotte1990 We reproduce the issue. Check is ongoing.

**Comment by NeoZhangJianyu** [comment]
@Lotte1990  We have created an internal issue to push dev team fix is as soon. We will update if any update.

**Comment by Lotte1990** [comment]
@NeoZhangJianyu Thank you for the update!

**Comment by penpornk** [comment]
@NeoZhangJianyu Thank you for the update!

> @penpornk the link you provided is related to building the pip package. I'm trying to build tensorflow_cc.dll with MKL (it builds fine without MKL).

@Lotte1990 I only provided the link to show that MKL supports Windows build. I didn't mean to imply that the link would solve the problem. Sorry if it seemed that way!

**Comment by NeoZhangJianyu** [comment]
@Lotte1990 
This issue is fixed on 2.3.0-rc0 with the PR: https://github.com/tensorflow/tensorflow/commit/ce81212fdfe7c5e84e354b1a52b24299a20899e9

**Comment by penpornk** [comment]
@NeoZhangJianyu Thank you very much!

**Comment by NeoZhangJianyu** [comment]
@Lotte1990 
Could you feedback the solution?
If it's working, could you close the issue?

**Comment by Lotte1990** [comment]
I tried building TensorFlow 2.3.1 and this issue is indeed fixed. Thank you! I will close this issue.
However, I now run into a new issue that I already reported in #42703. We can continue there.

**Comment by NeoZhangJianyu** [comment]
@Lotte1990 
Yes, we are checking the issue in #42703.
