### ISSUE TITLE
Construct tf.SparseTensor with tf.int32 dense_shape

### ISSUE THREAD

**Issue by ngc92** [tensorflow/tensorflow#39498]
**System information**
- TensorFlow version (you are using): 2.2
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Currently, `tf.SparseTensor` raises an error when constructed with a `dense_shape` of
`int32` dtype. This is annoying, as it e.g. prevents constructs of the form
```
sparse = tf.SparseTensor(indices, values, tf.shape(other_tensor))
```
because `tf.shape` by default returns an int32 tensor. 

**Will this change the current api? How?**
Instead of throwing an error, `tf.SparseTensor.__init__` should convert int32 shapes to
int64 shapes. Since the shapes are expected to have only a few entries, this should not
lead to any unexpected performance impacts.

**Who will benefit with this feature?**
This is mostly a very small convenience improvement, but has the benefit of making `tf.shape`
and `tf.SparseTensor` interact more seamlessly.

**Any Other info.**
One step further in that direction would be to have tf.shape return int64 tensors when called on a SparseTensor, but this would be a non backwards-compatible change, so I'm not sure if thats possible/worth it.

**Comment by tilakrayal** [comment]
@ngc92,
AFAIK tf.Sparsetensor provides the output with the int64 datatype. There is an alternative approach where we can use **tf.sparse.from_dense** which converts a dense tensor into a sparse tensor and the datatype output is tf.int32. Kindly find the [gist](https://colab.research.google.com/gist/tilakrayal/6f9c7d6ac0de78fa4cf5565a471ef765/untitled1796.ipynb) for the reference. 
https://www.tensorflow.org/api_docs/python/tf/sparse/from_dense
Thank you!
