### ISSUE TITLE
Distributed training and efficient data input pipeline

### ISSUE THREAD

**Issue by Anhaoxu** [tensorflow/tensorflow#39494]
Hi, I'm using tensorflow 2.0 in 4 gpus machine, my tensorflow code using keras api, like follows:
```
model = CNN_model()
model.compile(optimizer='adam', loss='mse')
model.fit()
```
and my data pipeline is user-defined generator, like follows:
```
def train_data():
    while True:
        for i in shuffle(train_id):
            df = pd.read_pickle(df_train_val['file_name'].iloc[i],
                                compression='gzip')
            feature = df.to_numpy().reshape(df.shape[0], -1)
            yield feature.reshape(-1, 56),feature.reshape(-1, 56)
gn = tf.data.Dataset.from_generator(train_data, output_types=(tf.float32, tf.float32),
                                          output_shapes=((None, 56),(None, 56))
                                         ).prefetch(tf.data.experimental.AUTOTUNE)
```
train_id is a file_index，I have more than 200K files in local machine, so in this case one batch is a file, my problem is the gpu util is very low, about 15%，I tried tf.distribute.MirroredStrategy, just by 
```
strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
    model = CNN_model()
    model.compile(optimizer='adam', loss='mse')
model.fit()
```
but, it didn't work, and slower than one gpu, I see the gpu util is lowed.
so, I have 3 questions: how can I make the input from_generator pipeline more efficient and let the gpu util increase or speed up the training process? why prefetch and tf.distribute.MirroredStrategy not work? is there somewhere for me to study these?

**Comment by iobtl** [comment]
Did you try scaling up your batch sizes appropriately when using distributed training? Not increasing your batch sizes when running multiple GPUs can be a major bottleneck in maximizing GPU usage. 

I am also not sure what kind of data you are trying to train here, but it may be a good idea to perform  some preprocessing via ```pd.read_pickle``` and the relevant functions before trying to create a ```Dataset``` of any kind. After all, the fastest operations come from using purely TensorFlow functions when trying to preprocess and churn out the inputs to the model.

**Comment by Anhaoxu** [comment]
@iobtl  for generator Dataset, the batch is 1, I use 4 gpus, so batch is 4, data is very common float value of 56 features, and each batch is from a pickle file because all data can't be in memory at one time

**Comment by iobtl** [comment]
@Anhaoxu is your data in the form of images? or other forms? 
Have you considered serializing your data in multiple TFRecord files instead? Maybe try to store more than one training instance per file. Following from there you can interleave ```tf.data.TFRecordDataset``` to create a ```Dataset``` object and perform batching from there.

**Comment by amahendrakar** [comment]
@Anhaoxu,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!
