### ISSUE TITLE
The `external` directory missing when building from source

### ISSUE THREAD

**Issue by andreibeats** [tensorflow/tensorflow#395]
Trying to run Tensorboard, and the complains with about several things missing in the tensorflow/external directory. This entire directory is not the at all, and it's not a part of any submodule (the only submodule included is protobuf).

**Comment by danmane** [comment]
If you build from source, you need to use bazel to build TensorBoard, e.g. `bazel build //tensorflow/tensorboard:tensorboard` and then `./bazel-bin/tensorflow/tensorboard --logdir=foo`. Or, for convenience, `bazel run //tensorflow/tensorboard:tensorboard -- --logdir=foo`. It's bazel that takes responsibility for finding TensorBoard's external dependencies and setting them up properly.

If you want to be able to run TensorBoard just using the python command, and you also want to build from source, you can build the pip package (tensorflow/tools/pip_package:build_pip_package) and then if you install from that pip package you'll have a totally self-contained TensorBoard.

Going to leave this open, please close it if this fixes the issue for you (also, maybe I should update the README with this info...)

**Comment by andreibeats** [comment]
Hi @danmane. Thanks, this is exactly what I was missing. It wasn't apparent from the README unfortunately.
