### ISSUE TITLE
CUDA installation for Ubuntu 18.4

### ISSUE THREAD

**Issue by PhilipMay** [tensorflow/tensorflow#39506]
When I want to install CUDA for Ubuntu 18.4 I follow this guide: https://www.tensorflow.org/install/gpu#ubuntu_1804_cuda_101

When I want to install `cuda-10-1` it sais: `E: Unable to locate package cuda-10-1`.

Did NVIDIA change anything on its side? Does the documentation need an update? Some weeks ago this installation was all ok...

**Comment by Saduf2019** [comment]
@PhilipMay 
Can you please refer to this [link](https://askubuntu.com/questions/1153604/problems-installing-cuda-10-0), [link2](https://stackoverflow.com/questions/58921156/unable-to-install-cuda-on-ubuntu-16-04) and let us know if it helps.
