### ISSUE TITLE
Support ragged output in TextVectorization layer

### ISSUE THREAD

**Issue by shkarupa-alex** [tensorflow/tensorflow#39505]
**System information**
- TensorFlow version (you are using): 2.2.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Currently TextVectorization supports ragged input, but always outputs dense tensor padded with 0.
It would be cool if in INT mode it will output ragged tensor, so caller may call downstream layers that supports ragged tensors and convert to dense when he needed.

**Will this change the current api? How?**
No api changes

**Who will benefit with this feature?**
Users of ragged tensors

**Comment by ravikyram** [comment]
@shkarupa-alex 

Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!

**Comment by deadshotsb** [comment]
I think this one is being refered to : https://www.tensorflow.org/guide/ragged_tensor

**Comment by saikumarchalla** [comment]
@shkarupa-alex You can  pass a RaggedTensor into StringLookup, which will return a RaggedTensor. The rest of the TextVectorization preprocessing can be done via standard TF ops.

Closing  this issue since String Lookup  layer is now available in TF 2.3.  Thanks!
