### ISSUE TITLE
google colab GPU is too slow (x1 time CPU speed) when using tensorflow 1.15.0

### ISSUE THREAD

**Issue by mamidpou** [tensorflow/tensorflow#39503]
hello every one;
I tried to run the code below in google colab with both of version of tensorflow 2.0 and 1.15.0
with the 2.0 version i had no problems (mostly GPU's speed was over 29 time faster than CPU's speed) but when using the 1.15.0 version the GPU was as fast as CPU no difference at all. any solutions or suggestions. i need 1.15.0 version because of the object detection api. thank you very much for your help
                                                                  Code
`%tensorflow_version 1.x
import tensorflow.compat.v2 as tf
#import tensorflow as tf
print(tf.__version__)
#tf.enable_v2_behavior
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))
import timeit

device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  print(
      '\n\nThis error most likely means that this notebook is not '
      'configured to use a GPU.  Change this in Notebook Settings via the '
      'command palette (cmd/ctrl-shift-P) or the Edit menu.\n\n')
  raise SystemError('GPU device not found')

def cpu():
  with tf.device('/cpu:0'):
    random_image_cpu = tf.random.normal((100, 100, 100, 3))
    net_cpu = tf.keras.layers.Conv2D(32, 7)(random_image_cpu)
    return tf.math.reduce_sum(net_cpu)

def gpu():
  with tf.device('/device:GPU:0'):
    random_image_gpu = tf.random.normal((100, 100, 100, 3))
    net_gpu = tf.keras.layers.Conv2D(32, 7)(random_image_gpu)
    return tf.math.reduce_sum(net_gpu)
  

cpu()
gpu()

print('Time (s) to convolve 32x7x7x3 filter over random 100x100x100x3 images '
      '(batch x height x width x channel). Sum of ten runs.')
print('CPU (s):')
cpu_time = timeit.timeit('cpu()', number=10, setup="from __main__ import cpu")
print(cpu_time)
print('GPU (s):')
gpu_time = timeit.timeit('gpu()', number=10, setup="from __main__ import gpu")
print(gpu_time)
print('GPU speedup over CPU: {}x'.format(int(cpu_time/gpu_time)))`
                                                             results
`  TensorFlow 1.x selected.
version tensorflow:1.15.0
Found GPU at: /device:GPU:0
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Time (s) to convolve 32x7x7x3 filter over random 100x100x100x3 images (batch x height x width x channel). Sum of ten runs.
CPU (s):
0.17279088399936882
GPU (s):
0.18540516800021578
GPU speedup over CPU: 0x`

`tf.version= 2.2.0
Found GPU at: /device:GPU:0
Time (s) to convolve 32x7x7x3 filter over random 100x100x100x3 images (batch x height x width x channel). Sum of ten runs.
CPU (s):
2.4908546100000137
GPU (s):
0.10798676599998203
GPU speedup over CPU: 23x
2.2.0`

**Comment by Saduf2019** [comment]
@mamidpou 
Code shared does not seem complete and indented, please share code such that we can replicate the issue faced, or if possible share a colab gist for us to analyse the issue faced.

**Comment by mamidpou** [comment]
@Saduf2019 
this is the link to the google colab notebook thanks for your response:
https://colab.research.google.com/drive/1EaWha1zW42e8pJ5m2KXKFPe9bzPHhhLf?usp=sharing

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/b99ec30a4e3065e7e326f57ce1208d2d/replicate.ipynb)

**Comment by dpinol** [comment]
My tranining was also very slow because I was doing  `!pip install tensorflow==1.15.0`
 `!pip install tensorflow-gpu==1.15.0` solved the issue (~30 times faster)

**Comment by mamidpou** [comment]
@dpinol 
No difference even when i use !pip install tensorflow-gpu==1.15.0 problem not solved for me. have you done any configuration before installing tensorflow???

**Comment by ymodak** [comment]
I tried with TF 2.2 version and got 32X speed up.
Please upgrade to latest TF version as we are continuously monitoring it and you can expect bug/performance improvements in newer TF versions.
Unfortunately we are not accepting changes to TF 1.X unless they are security fix related issues.
Thanks!

**Comment by mamidpou** [comment]
Thank you for your réponse but i need to use object detection api that is
not yet provided into tf version 2

Le mer. 20 mai 2020 à 00:09, Yasir Modak <notifications@github.com> a
écrit :

**Comment by esp32wrangler** [comment]
> My tranining was also very slow because I was doing `!pip install tensorflow==1.15.0`
> `!pip install tensorflow-gpu==1.15.0` solved the issue (~30 times faster)

Thank you, this solved the problem for me as well!

I don't think the answer that we should use TF 2.x is acceptable, I also have saved weights that I can't load or reproduce under 2.x very easily :(

**Comment by ymodak** [comment]
Object detection api for TF2 is a work in progress. 
Refer this GitHub [thread](https://github.com/tensorflow/models/issues/6423) to know more.
Closing this issue for now. Thanks!
