### ISSUE TITLE
with_values and map_flat_values for SparseTensor

### ISSUE THREAD

**Issue by ngc92** [tensorflow/tensorflow#39507]
**System information**
- TensorFlow version (you are using): 2.2
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
`tf.RaggedTensor` offers two utility functions, `with_values` and `map_flat_values`,
which allow to modify the content of the `RaggedTensor` while keeping the structure.

This feature request is for adding the same to `tf.SparseTensor`.

**Will this change the current api? How?**
Add a new function `with_values` to `tf.SparseTensor` which updates the values
but leaves the indices unchanged.
Add a new function `tf.sparse.map_flat_values` (or maybe just `map_values`) that applies
an operation to the values Tensor of a `SparseTensor`, and updates it.

**Who will benefit with this feature?**
This would make the interfaces of sparse and ragged tensors more similar, and provides to very basic utility functions. 

**Any Other info.**
I do have a PR ready for the `with_values` function. 
Am working on `map_flat_values`. In the case of multiple `SparseTensor`s, should this function check that they have identical indices or not? `ragged.map_flat_values` checks row_splits, but I guess in a typical application the number of elements in row splits will be significantly lower than the number of values, whereas in a sparse tensor there are more indices (if the tensor is at least 2 dimensional) than values, making for a larger relative performance impact.

**Comment by ymodak** [comment]
Closing this issue since the associated PR has been merged. Thank you!
