### ISSUE TITLE
Boolean support for tf.arg{min,max}

### ISSUE THREAD

**Issue by hartikainen** [tensorflow/tensorflow#39515]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `macOS Catalina 10.15.2 (19C57)`
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): `2.2.0`
- Python version: `3.7.5`

**Describe the feature and the current behavior/state.**
Feature: `tf.argmax` and `tf.argmin` do not fail when input is of dtype `tf.bool`.
Current_behavior: `tf.argmax` and `tf.argmin` fail when input is of dtype `tf.bool`.

**Will this change the current api? How?**
Would add new supported input type to `tf.argmax`.

**Who will benefit with this feature?**
Users who need to find the first for non-zero indices from their boolean tensor along specific axis.

**Sketch of a test case**
```python
import tensorflow as tf

tf.debugging.assert_equal(tf.argmax((False, True)), tf.cast(1, tf.int64))
tf.debugging.assert_equal(tf.argmin((False, True)), tf.cast(0, tf.int64))
```

**Logs for current behavior**
```
>>> import tensorflow as tf
>>> tf.debugging.assert_equal(tf.argmax((False, True)), tf.cast(1, tf.int64))
...
tensorflow.python.framework.errors_impl.NotFoundError: Could not find valid device for node.
Node:{{node ArgMax}}
All kernels registered for op ArgMax :
  device='XLA_CPU'; output_type in [DT_INT32, DT_INT64]; Tidx in [DT_INT32, DT_INT64]; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, ..., DT_UINT16, DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64]
  device='XLA_CPU_JIT'; output_type in [DT_INT32, DT_INT64]; Tidx in [DT_INT32, DT_INT64]; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, ..., DT_UINT16, DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64]
  device='CPU'; T in [DT_INT64]; output_type in [DT_INT64]
  device='CPU'; T in [DT_INT64]; output_type in [DT_INT32]
  device='CPU'; T in [DT_INT32]; output_type in [DT_INT64]
  device='CPU'; T in [DT_INT32]; output_type in [DT_INT32]
  device='CPU'; T in [DT_UINT16]; output_type in [DT_INT64]
  device='CPU'; T in [DT_UINT16]; output_type in [DT_INT32]
  device='CPU'; T in [DT_INT16]; output_type in [DT_INT64]
  device='CPU'; T in [DT_INT16]; output_type in [DT_INT32]
  device='CPU'; T in [DT_UINT8]; output_type in [DT_INT64]
  device='CPU'; T in [DT_UINT8]; output_type in [DT_INT32]
  device='CPU'; T in [DT_INT8]; output_type in [DT_INT64]
  device='CPU'; T in [DT_INT8]; output_type in [DT_INT32]
  device='CPU'; T in [DT_HALF]; output_type in [DT_INT64]
  device='CPU'; T in [DT_HALF]; output_type in [DT_INT32]
  device='CPU'; T in [DT_BFLOAT16]; output_type in [DT_INT64]
  device='CPU'; T in [DT_BFLOAT16]; output_type in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]; output_type in [DT_INT64]
  device='CPU'; T in [DT_FLOAT]; output_type in [DT_INT32]
  device='CPU'; T in [DT_DOUBLE]; output_type in [DT_INT64]
  device='CPU'; T in [DT_DOUBLE]; output_type in [DT_INT32]
 [Op:ArgMax]
```

**Comment by hartikainen** [comment]
Looking at the `argmax_op_test.py`, it actually looks like this case is tested already: https://github.com/tensorflow/tensorflow/blob/cda7fe6da69f6ef1b25b66bf5b22c97c57e974ae/tensorflow/python/kernel_tests/argmax_op_test.py#L129-L132

Should this be a bug instead of feature request?

**Comment by yongtang** [comment]
@hartikainen The bool support was only added in b0cd75dc99237a7438c70a2f6f7489e64b5472e5 . It is not in 2.2.0 but is in tf-nightly build.

**Comment by hartikainen** [comment]
Oh, my apologies, didn't realize it's already been implemented!
