### ISSUE TITLE
when I try to install tensorflow from source by bazel, I got this new problem:

### ISSUE THREAD

**Issue by haibarasiao** [tensorflow/tensorflow#3951]
/home/scw4150/Documents/tensorflow/tensorflow/tensorflow/stream_executor/BUILD:5:1: C++ compilation of rule '//tensorflow/stream_executor:stream_executor' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 112 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
tensorflow/stream_executor/cuda/cuda_dnn.cc: In function 'cudnnConvolutionFwdAlgo_t perftools::gputools::cuda::{anonymous}::ToConvForwardAlgo(perftools::gputools::dnn::AlgorithmType)':
tensorflow/stream_executor/cuda/cuda_dnn.cc:266:10: error: 'CUDNN_CONVOLUTION_FWD_ALGO_FFT_TILING' was not declared in this scope
     case CUDNN_CONVOLUTION_FWD_ALGO_FFT_TILING:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tensorflow/stream_executor/cuda/cuda_dnn.cc: In function 'cudnnConvolutionBwdDataAlgo_t perftools::gputools::cuda::{anonymous}::ToConvBackwardDataAlgo(perftools::gputools::dnn::AlgorithmType)':
tensorflow/stream_executor/cuda/cuda_dnn.cc:284:10: error: 'CUDNN_CONVOLUTION_BWD_DATA_ALGO_FFT_TILING' was not declared in this scope
     case CUDNN_CONVOLUTION_BWD_DATA_ALGO_FFT_TILING:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tensorflow/stream_executor/cuda/cuda_dnn.cc: In member function 'virtual bool perftools::gputools::cuda::CudnnSupport::GetConvolveAlgorithms(std::vector<long long int>*)':
tensorflow/stream_executor/cuda/cuda_dnn.cc:942:7: error: 'CUDNN_CONVOLUTION_FWD_ALGO_FFT_TILING' was not declared in this scope
       CUDNN_CONVOLUTION_FWD_ALGO_FFT_TILING,
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tensorflow/stream_executor/cuda/cuda_dnn.cc:947:4: error: no matching function for call to 'std::vector<long long int>::assign(<brace-enclosed initializer list>)'
   });

any suggestions?

**Comment by hholst80** [comment]
Which version of cuDNN and Cuda toolkit are you using? Gcc version? OS version?

**Comment by haibarasiao** [comment]
@hholst80 
cuDNN v4 
Cuda toolkit 7.0
gcc version 6.1.0
CentOS Linux release 7.2.1511 (Core)

**Comment by vrv** [comment]
I would double check your cuda and cudnn install, I think you have older versions, despite what you think.  Maybe remove the existing cuda and cudnn versions and install them from scratch.

I would also recommend using:
- cudnn v4, unless you have GTX1080, in which case use cudnn v5
- cuda toolkit 7.5, unless you have GTX1080, in which case use cuda 8.0 RC

**Comment by haibarasiao** [comment]
thanks,I will try to update cuda and cudnn version.

**Comment by vrv** [comment]
(I should clarify, you can use cudnn v5 regardless of what GPU you have).

I'm going to close this since I suspect this is a cuda problem, not a TF one (yet).
