### ISSUE TITLE
issue plz reply

### ISSUE THREAD

**Issue by shreyas1212** [tensorflow/tensorflow#39513]
When i run this code 
python flow --model cfg/yolo.cfg --loadbin/yolo.weights --demo videofile.mp4 --gpu 1.0 --saveVideo
this error occurs 
Traceback (most recent call last):
  File "C:\Users\Noddy\AppData\Roaming\Python\Python36\site-packages\tensorflow\
python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Noddy\AppData\Roaming\Python\Python36\site-packages\tensorflow\
python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Noddy\AppData\Roaming\Python\Python36\site-packages\tensorflow\
python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\Noddy\AppData\Local\Programs\Python\Python36\lib\imp.py", line
243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Noddy\AppData\Local\Programs\Python\Python36\lib\imp.py", line
343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "C:\Users\Noddy\Downloads\darkflow-master\darkflow\cli.py", line 3, in <m
odule>
    from .net.build import TFNet
  File "C:\Users\Noddy\Downloads\darkflow-master\darkflow\net\build.py", line 1,
 in <module>
    import tensorflow as tf
  File "C:\Users\Noddy\AppData\Roaming\Python\Python36\site-packages\tensorflow\
__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Noddy\AppData\Roaming\Python\Python36\site-packages\tensorflow\
python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Noddy\AppData\Roaming\Python\Python36\site-packages\tensorflow\
python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Noddy\AppData\Roaming\Python\Python36\site-packages\tensorflow\
python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Noddy\AppData\Roaming\Python\Python36\site-packages\tensorflow\
python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Noddy\AppData\Roaming\Python\Python36\site-packages\tensorflow\
python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\Noddy\AppData\Local\Programs\Python\Python36\lib\imp.py", line
243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Noddy\AppData\Local\Programs\Python\Python36\lib\imp.py", line
343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

plz see this error and reply as soon as possible

**Comment by ravikyram** [comment]
@shreyas1212 

Request you to fill [issue template ](https://github.com/tensorflow/tensorflow/issues/new/choose)

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website.](https://www.tensorflow.org/install/source_windows)

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.Please, refer similar issue #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
Thanks!

**Comment by shreyas1212** [comment]
I didnt get how to solve the error

**Comment by shreyas1212** [comment]
i didnt get how to solve this issue

**Comment by ravikyram** [comment]
@shreyas1212 

It may occur because you may not have [Visual C++ Redistributable for Windows](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).Please, install Installing C++ redistributables and see if it resolve your issue.Thanks!

**Comment by mihaimaruseac** [comment]
We should close as duplicate since user wants a copy-paste-able string of commands instead of reading the hundreds of duplicated issues or the comments above which have the solution

**Comment by mihaimaruseac** [comment]
Closing as duplicate.

https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156

Just to sample over 100 similar issues: #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204

Please make sure you do a search in the future.

**Comment by shreyas1212** [comment]
Thank you so much that worked but now i have another error if you can solve
this error it will be a huge help

C:\Users\xxx\ObjectDetection>ObjectDetection.py
2020-05-06 19:21:40.487279: W
tensorflow/stream_executor/platform/default/dso_lo
ader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror:
cudart64
_101.dll not found
2020-05-06 19:21:40.487279: I
tensorflow/stream_executor/cuda/cudart_stub.cc:29]
 Ignore above cudart dlerror if you do not have a GPU set up on your
machine.
Traceback (most recent call last):
  File "C:\Users\xxx\ObjectDetection\ObjectDetection.py", line 9, in
<module>
    import mss
ModuleNotFoundError: No module named 'mss'

**Comment by shreyas1212** [comment]
yes it worked but now i have another error im stuck at my projects plz
reply as soon as possible the code which i have written is simple
ObjectDetection.py but this error is occuring
2020-05-06 19:44:53.869975: W
tensorflow/stream_executor/platform/default/dso_lo
ader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror:
cudart64
_101.dll not found
2020-05-06 19:44:53.869975: I
tensorflow/stream_executor/cuda/cudart_stub.cc:29]
 Ignore above cudart dlerror if you do not have a GPU set up on your
machine.
Traceback (most recent call last):
  File "C:\Users\Noddy\ObjectDetection\ObjectDetection.py", line 26, in
<module>

    opener.retrieve("http://download.tensorflow.org/models/object_detection/"
+
MODEL_FILE, MODEL_FILE)
  File
"C:\Users\Noddy\AppData\Local\Programs\Python\Python36\lib\urllib\request
.py", line 1791, in retrieve
    fp = self.open(url, data)
  File
"C:\Users\Noddy\AppData\Local\Programs\Python\Python36\lib\urllib\request
.py", line 1757, in open
    return getattr(self, name)(url)
  File
"C:\Users\Noddy\AppData\Local\Programs\Python\Python36\lib\urllib\request
.py", line 1936, in open_http
    return self._open_generic_http(http.client.HTTPConnection, url, data)
  File
"C:\Users\Noddy\AppData\Local\Programs\Python\Python36\lib\urllib\request
.py", line 1932, in _open_generic_http
    response.status, response.reason, response.msg, data)
  File
"C:\Users\Noddy\AppData\Local\Programs\Python\Python36\lib\urllib\request
.py", line 1952, in http_error
    return self.http_error_default(url, fp, errcode, errmsg, headers)
  File
"C:\Users\Noddy\AppData\Local\Programs\Python\Python36\lib\urllib\request
.py", line 1957, in http_error_default
    raise HTTPError(url, errcode, errmsg, headers, None)
urllib.error.HTTPError: HTTP Error 403: Forbidden

PLZ REPLY AS FAST AS YOU CAN
