### ISSUE TITLE
Which older versions(<2) are compatible with CUDA 10.1?

### ISSUE THREAD

**Issue by ibrahimLearning** [tensorflow/tensorflow#39510]
I am facing compatibility problem with CUDA 10.1 and TF 1.3.
I would like to know,
Which TF versions (<2) are supported by CUDA 10.1?

**Comment by ymodak** [comment]
<img width="899" alt="Screen Shot 2020-05-13 at 1 35 47 PM" src="https://user-images.githubusercontent.com/42785357/81862551-bc5d2580-951e-11ea-9820-87d6e97cec67.png">

We don't have TF 1.X binaries with Cuda 10.1 support.
See https://www.tensorflow.org/install/source#gpu
