### ISSUE TITLE
Pip install tensorflow, got an error

### ISSUE THREAD

**Issue by EmersonLiepe** [tensorflow/tensorflow#39514]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
none
- TensorFlow installed from (source or binary):
Binary
- TensorFlow version:
tensorflow 2.2.0
- Python version:
3.6.10
- Installed using virtualenv? pip? conda?:
conda
- Bazel version (if compiling from source):
none
- GCC/Compiler version (if compiling from source):
none
- CUDA/cuDNN version:
19.273
- GPU model and memory:
1.7tac

**Describe the problem**

Launched CMD.exe and ran command "conda install tensorflow". Returned ERROR, no matching distribution found!

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@EmersonLiepe 

Are you using 64-bit version of Python or 32 bit version?.Please, refer [link1](https://stackoverflow.com/questions/38896424/tensorflow-not-found-using-pip).Also, let us know which version of Tensorflow you are using?.Please, follow instruction in [Tensorfow website](https://www.tensorflow.org/install/pip).Thanks!
Also refer to [link](https://github.com/tensorflow/tensorflow/issues/9680#issuecomment-407278974), [link2](url)

**Comment by mihaimaruseac** [comment]
It's either a Python on 32 bits or a Python installed from MS Marketplace. Please install Python from the official page at python.org, using a 64 bits version
