### ISSUE TITLE
Undefined symbol in debug mode

### ISSUE THREAD

**Issue by conjam** [tensorflow/tensorflow#39521]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: v2.2.0-rc3
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: pip 
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): gcc 7.5.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

Tensorflow was built inside the 'tensorflow/tensorflow:devel-py3' docker image with digest 0285d09f16ff

**Describe the problem**

After building tensorflow w/ debug info, tensorflow fails when imported with the following error: 

``` python
ImportError: /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: 
undefined symbol: _ZN10tensorflow4data12experimental14SnapshotReader34kSnappyReaderOutputBufferSizeBytesE 
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. I cherry picked https://github.com/tensorflow/tensorflow/pull/39239/commits/cd8b64f7fbdc2bc8700b71dadb4c51744a752095 to fix https://github.com/tensorflow/tensorflow/issues/37498
2. bazel build --config=dbg --strip=never //tensorflow/tools/pip_package:build_pip_package
3. ./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
4. cd /tmp/tensorflow_pkg
4. pip3 install tensorflow-2.2.0rc3-cp36-cp36m-linux_x86_64.whl
5. python3 -c 'import tensorflow'

If there is anything else worth providing (readelf output?) please let me know

**Comment by Saduf2019** [comment]
@conjam 
Can you please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/12326#issuecomment-323346397) with similat error message but different version, and let us know if it helps.

**Comment by conjam** [comment]
> @conjam
> Can you please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/12326#issuecomment-323346397) with similat error message but different version, and let us know if it helps.

I tried what was recommended in this comment, but to no avail -- explicitly, I tried reinstalling protobuf version 3.3.0 but 3.8.0 is the min required for tf v2.2.0, so all I did was was re-install protobuf version 3.11.0.

FWIW, I checked out v2.2.0 and v2.1.0; v2.2.0 has the exact same issue as mentioned above, but tf v2.1.0 does not have this issue. 

Is there a docker image that is preferred for building tf v2.2.0 with py3 support (GPU support not required)?

**Comment by mihaimaruseac** [comment]
Changed title since you mention issue happens at head of r2.2 branch

**Comment by Saduf2019** [comment]
@conjam
Is this still an issue

**Comment by stalex91** [comment]
Yes, still reproducible. Please let me know If more info from me is needed.
Issue looks similar: debug build, undefined symbol on 2.2 and working on 2.1

**Comment by stalex91** [comment]
V2.4.0 (Master, ToT) Same issue:

**Comment by mihaimaruseac** [comment]
You are seeing different undefined symbols though. Can you do a `bazel clean --expunge` and compile again? Also, if you're building from master, can you also add the output of `git log -n5 --pretty=oneline`?

**Comment by stalex91** [comment]
> Can you do a `bazel clean --expunge` and compile again?

Performed, _pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow4data12experimental19SnapshotDatasetV2Op18kFileFormatVersionE

> Also, if you're building from master, can you also add the output of `git log -n5 --pretty=oneline`

ba5dddcf708e1762b924e4cd7ef07c54b34708f5 (HEAD -> master, origin/master, origin/HEAD) compat: Update forward compatibility horizon to 2020-07-06
077bc8282c3c0fffe710516ea72b8faa8b5f9ab7 Update GraphDef version to 454.
23873d4d6518a6f169600a076001dc2d7a661dd0 Fix a crash on BenchmarkTfLiteModel with delegate
108aa90714c8369a2392fba43fa62c2d0cec523a Remove the constraint the QConst couldn't be shared
1da8b52504ce5acb531a23a5db0240e72a8d80de Integrate LLVM at https://github.com/llvm/llvm-project/commit/edba2864a7a8

**Comment by mihaimaruseac** [comment]
What is the command you are using to build?

**Comment by stalex91** [comment]
> 
> 
> What is the command you are using to build?

JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 bazel --host_jvm_args '-Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts' build --host_javabase '@local_jdk//:jdk' --config=dbg tensorflow/tools/pip_package:build_pip_package

**Comment by mihaimaruseac** [comment]
Can you run the following please?

```
bazel clean --expunge  # probably also adding the JDK args in front
JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 bazel --host_jvm_args '-Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts' build --host_javabase '@local_jdk//:jdk' --config=dbg tensorflow/tools/pip_package:build_pip_package &> log.txt
```

and then *attach* `log.txt`?

**Comment by stalex91** [comment]
> 
> 
> Can you run the following please?
> 
> ```
> bazel clean --expunge  # probably also adding the JDK args in front
> JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 bazel --host_jvm_args '-Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts' build --host_javabase '@local_jdk//:jdk' --config=dbg tensorflow/tools/pip_package:build_pip_package &> log.txt
> ```
> 
> and then _attach_ `log.txt`?

Rebuilt, reinstalled:

Sure. Log zipped, original file 80mbytes
[log.zip](https://github.com/tensorflow/tensorflow/files/4892257/log.zip)

**Comment by mihaimaruseac** [comment]
Oh, you manage to build and link and it only fails at import time. Apologies, missed this part in the initial comment.

Can you also attach the output of `python -vvv -c "import tensorflow" &> log.txt`? I didn't see anything significant in the build log but maybe with the new log things should be easier.

The warnings are ok, since the code that creates the pip looks for files that can only exist on Windows (for example). We should clean that up but it's of a very low priority (though we accept PRs)

**Comment by stalex91** [comment]
> Can you also attach the output of `python -vvv -c "import tensorflow" &> log.txt`? I didn't see anything significant in the build log but maybe with the new log things should be easier.

Here please 
[log2.txt](https://github.com/tensorflow/tensorflow/files/4894734/log2.txt)

**Comment by mihaimaruseac** [comment]
We almost never built with debug information, instead we use printf-debugging and sanitizers.

I'll look at both logs later today / by Monday.

**Comment by MrGeva** [comment]
I am suffering from the same issue. Can you please enable the debug build? it helps a lot to be able to debug when trying to learn the internal implementation.

**Comment by 0gur1** [comment]
I also run into this issue with version of v2.4.0.

**Comment by 0gur1** [comment]
I finally succeeded compile the debug mode of tf2.3.0 by using "bazel build -c opt --copt=-g"

**Comment by peng2007** [comment]
> I finally succeeded compile the debug mode of tf2.3.0 by using "bazel build -c opt --copt=-g"

Could you share your complete "bazel build" command?

**Comment by 0gur1** [comment]
bazel build -c opt --copt=-g //tensorflow/tools/pip_package:build_pip_package --verbose_failures




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tensorflow/tensorflow"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月23日(星期三) 下午3:57
收件人:&nbsp;"tensorflow/tensorflow"<tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"Yu Tian"<904466829@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [tensorflow/tensorflow] Undefined symbol in debug mode (#39521)





  
I finally succeeded compile the debug mode of tf2.3.0 by using "bazel build -c opt --copt=-g"
  
Could you share your complete "bazel build" command?

**Comment by 0gur1** [comment]
> > I finally succeeded compile the debug mode of tf2.3.0 by using "bazel build -c opt --copt=-g"
> 
> Could you share your complete "bazel build" command?

bazel build -c opt --copt=-g //tensorflow/tools/pip_package:build_pip_package --verbose_failures

**Comment by rockspring** [comment]
I'm running into this issue as well in version 2.4.1. It seems wild that the debug build is broken and unsupported.

```
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/python3.8tf2.4/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/usr/local/anaconda3/envs/python3.8tf2.4/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: __ZN10tensorflow4data12experimental19SnapshotDatasetV2Op13kReaderPrefixE
  Referenced from: /usr/local/anaconda3/envs/python3.8tf2.4/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Expected in: flat namespace
 in /usr/local/anaconda3/envs/python3.8tf2.4/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
```

```
85c8b2a817f95a3e979ecd1ed95bff1dc1335cff (HEAD, tag: v2.4.1, origin/r2.4) Merge pull request #46560 from tensorflow-jenkins/version-numbers-2.4.1-3958
b44a7e3822caae51837b140ea571cf71050f8186 Update version numbers to 2.4.1
fd24839e4ce403490af01b682616678fdb95103a Merge pull request #46557 from tensorflow-jenkins/relnotes-2.4.1-3926
4072b0d80854faa28334d41b2f126e6d5bd8daf2 Update RELEASE.md
20be98a7b31ff79dc83e02fa42761431ae7c2f5d Insert release notes place-fill
```

## build command

```
bazel
build \
--config=dbg \
--copt="-Og" \
--config=noaws \
--config=nogcp \
--config=nohdfs \
--config=nonccl \
--repository_cache ../tensorflow-mac-cache \
--verbose_failures \
--explain debug_build.log \
--verbose_explanations \
//tensorflow/tools/pip_package:build_pip_package
```

**Comment by kyleg907** [comment]
I also get a usable debug build on TF 2.3.2 with  @0gur1's technique of using `-c opt --copt=-g`. I had experienced the same symptom reported in the description.

**Comment by hjmus** [comment]
On 2.5.0, seeing the same issue but with a different symbol: `_ZN10tensorflow4data17FinalizeDatasetOp15kHasCapturedRefE`

`-c opt --copt=-g` no longer helps. Linker will fail with "relocation overflows" error.

**Comment by mmaor123** [comment]
same here. tried all sort of debug build options with 2.6.0
getting /tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow4data17FinalizeDatasetOp15kHasCapturedRefE

is debug build broken? is there a new method to build debug version of TF?

**Comment by tianxh1212** [comment]
I get the same problem on r2.4.1
I solved it by using --copt -g --strip=never rather than -c dbg

**Comment by tianxh1212** [comment]
> same here. tried all sort of debug build options with 2.6.0
> getting /tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow4data17FinalizeDatasetOp15kHasCapturedRefE
> 
> is debug build broken? is there a new method to build debug version of TF?

try --copt -g --strip=never，not -c dbg，it make sense on 2.4.1~

**Comment by gglin001** [comment]
the `nightly` branch is ok with `--copt="-O0" -c dbg`
succeed on earlier commit
`3fd3ae1fbb10961dd1aa6805280674c781fd4609`

**Comment by sanatmpa1** [comment]
@conjam,

Can you try building the latest stable version of tensorflow i.e `2.6.0` and lets us know if the issue still persists in newer version? You can follow this [guide](https://www.tensorflow.org/install/source#tested_build_configurations) to build from source. Thanks!

**Comment by mennyham** [comment]
Didn't see the --copt ...

**Comment by mennyham** [comment]
I will try again
