### ISSUE TITLE
[TFLite] Failed to create Hexagon delegate on Oneplus 5

### ISSUE THREAD

**Issue by anidh** [tensorflow/tensorflow#39539]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Pop Os 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Oneplus 5
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.2
- Python version: 3.7

**Describe the current behavior**

Device Information -

    adb shell getprop ro.product.device
    OnePlus5

    adb shell getprop ro.board.platform
    msm8998

($APP_ROOT)/app/src/main/jniLibs

```
├── arm64-v8a
│   ├── libhexagon_nn_skel.so
│   ├── libhexagon_nn_skel_v65.so
│   └── libhexagon_nn_skel_v66.so
└── armeabi-v7a
    ├── libhexagon_nn_skel.so
    ├── libhexagon_nn_skel_v65.so
    └── libhexagon_nn_skel_v66.so
```
($APP_ROOT)/app/build.gradle

    apply plugin: 'com.android.application'  
    apply plugin: 'kotlin-android'  
    apply plugin: 'kotlin-android-extensions'  
      
    android {  
      
      compileSdkVersion 29  
      buildToolsVersion "29.0.3"  
      
      defaultConfig {  
      applicationId "com.example.sr_tflite"  
      minSdkVersion 25  
      targetSdkVersion 29  
      versionCode 1  
      versionName "1.0"  
      ndk {  
      abiFilters 'armeabi-v7a', 'arm64-v8a'  
      }  
      
      testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"  
      }  
      
      buildTypes {  
      release {  
      minifyEnabled false  
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'  
      }  
      aaptOptions {  
      noCompress "tflite"  
      }  
     }  
    // To inline the bytecode built with JVM target 1.8 into  
    // bytecode that is being built with JVM target 1.6. (e.g. navArgs)  
      
      
      compileOptions {  
      sourceCompatibility JavaVersion.VERSION_1_8  
      targetCompatibility JavaVersion.VERSION_1_8  
      }  
      kotlinOptions {  
      jvmTarget = "1.8"  
      }  
      
    }  
      
    dependencies {  
      def tfl_version = "0.0.0-nightly"  
      implementation fileTree(dir: 'libs', include: ['*.jar'])  
        implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"  
      implementation 'androidx.appcompat:appcompat:1.1.0'  
      implementation 'androidx.core:core-ktx:1.2.0'  
      implementation 'com.google.android.material:material:1.1.0'  
      implementation 'androidx.constraintlayout:constraintlayout:1.1.3'  
      implementation 'androidx.navigation:navigation-fragment-ktx:2.0.0'  
      implementation 'androidx.navigation:navigation-ui-ktx:2.0.0'  
      implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'  
      implementation 'org.tensorflow:tensorflow-lite-hexagon:0.0.0-nightly'  
      testImplementation 'junit:junit:4.12'  
      androidTestImplementation 'androidx.test.ext:junit:1.1.1'  
      androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'  
      implementation("org.tensorflow:tensorflow-lite:${tfl_version}") { changing = true }  
      implementation("org.tensorflow:tensorflow-lite-gpu:${tfl_version}") { changing = true }  
      implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly'  
    }

I followed the [TensorFlow Lite Hexagon delegate](https://www.tensorflow.org/lite/performance/hexagon_delegate) guide on Oneplus 5. Tensorflow Lite was failed to create Hexagon delegate.

Log

    020-05-14 16:26:19.906 27848-27848/com.example.sr_tflite I/System.out: *******/data/app/com.example.sr_tflite-WR6XEFKEipjZ_vWQYv9MSQ==/lib/arm64
    2020-05-14 16:26:19.947 27848-27848/com.example.sr_tflite V/com.example.sr_tflite: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1859: Successfully created user PD on domain 0 (attrs 0x0)
    2020-05-14 16:26:19.960 27848-28029/com.example.sr_tflite V/com.example.sr_tflite: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:270: rpc latency thread start
    2020-05-14 16:26:19.961 27848-28027/com.example.sr_tflite E/com.example.sr_tflite: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/apps_std_imp.c:729:Error 45: fopen failed for oemconfig.so. (No such file or directory)
    2020-05-14 16:26:19.961 27848-28027/com.example.sr_tflite E/com.example.sr_tflite: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/apps_std_imp.c:729:Error 45: fopen failed for libhexagon_nn_skel.so. (No such file or directory)
    2020-05-14 16:26:19.961 27848-27848/com.example.sr_tflite D/com.example.sr_tflite: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:983: Error fffffffb: remote handle open domain failed. domain 0, name file:///libhexagon_nn_skel.so?hexagon_nn_domains_skel_handle_invoke&_modver=1.0&_dom=adsp, dlerror cannot open oemconfig.so
    2020-05-14 16:26:19.961 27848-27848/com.example.sr_tflite D/com.example.sr_tflite: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:920: Error ffffffff: remote handle invoke failed. domain 0, handle 0, sc 1010200, pra 0x7fde45af88
    2020-05-14 16:26:19.961 27848-27848/com.example.sr_tflite D/com.example.sr_tflite: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1034: Error ffffffff: remote handle close failed. error 
    2020-05-14 16:26:19.961 27848-27848/com.example.sr_tflite D/com.example.sr_tflite: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1020: Error fffffffb: remote handle64 open failed. name file:///libhexagon_nn_skel.so?hexagon_nn_domains_skel_handle_invoke&_modver=1.0&_dom=adsp
    2020-05-14 16:26:19.961 27848-27848/com.example.sr_tflite W/tflite: Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.
    2020-05-14 16:26:19.961 27848-27848/com.example.sr_tflite I/tflite: Hexagon Delegate is not supported.
    2020-05-14 16:26:19.962 27848-27848/com.example.sr_tflite D/AndroidRuntime: Shutting down VM
    2020-05-14 16:26:19.966 27848-27848/com.example.sr_tflite E/AndroidRuntime: FATAL EXCEPTION: main
        Process: com.example.sr_tflite, PID: 27848
        java.lang.UnsupportedOperationException: This Device doesn't support Hexagon DSP execution.
            at org.tensorflow.lite.experimental.HexagonDelegate.<init>(HexagonDelegate.java:40)
            at com.example.sr_tflite_1.MainActivity$onCreate$1.onClick(MainActivity.kt:97)
            at android.view.View.performClick(View.java:6669)
            at android.view.View.performClickInternal(View.java:6638)
            at android.view.View.access$3100(View.java:789)
            at android.view.View$PerformClick.run(View.java:26145)
            at android.os.Handler.handleCallback(Handler.java:873)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:193)
            at android.app.ActivityThread.main(ActivityThread.java:6898)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
    2020-05-14 16:26:19.977 27848-28030/com.example.sr_tflite D/OSTracker: OS Event: crash
    2020-05-14 16:26:19.995 27848-27848/com.example.sr_tflite I/Process: Sending signal. PID: 27848 SIG: 9

I have downloaded the latest hexagon_nn_skel.run (v1.17) from the page but it still says `Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide. 2020-05-14 16:26:19.961 27848-27848/com.example.sr_tflite I/tflite: Hexagon Delegate is not supported.` Do i need to pull some other so files from somewhere else or my device is not supported.
Thanks

**Describe the expected behavior**

The DSP delegate should be initialized as my SoC is in the list of supported hardwares.

**Comment by karimnosseir** [comment]
Hi

1) the title has OnePlus5 and in the body you say Pixel 3, can you please confirm which device you are using.

2) The logcat has "fopen failed for libhexagon_nn_skel.so. (No such file or directory)", please make sure the files are correctly packaged with the app.

3) please clear you gradle cache to make sure you're pulling the latest nightly and not an old one.

Thanks

**Comment by anidh** [comment]
> Hi
> 
> 1. the title has OnePlus5 and in the body you say Pixel 3, can you please confirm which device you are using.
> 2. The logcat has "fopen failed for libhexagon_nn_skel.so. (No such file or directory)", please make sure the files are correctly packaged with the app.
> 3. please clear you gradle cache to make sure you're pulling the latest nightly and not an old one.
> 
> Thanks

1)Thanks a lot for quick response. I used a template from another user and that's why the body had pixel 3. I'm using a oneplus 5.

2)I have placed the directory as mentioned in the above body and as given in the guide. This is my directory structure straight from android studio.
![Screenshot from 2020-05-14 23-52-38](https://user-images.githubusercontent.com/17473554/81971156-451eb300-963e-11ea-931d-c6806368a182.png)

3) I have cleared the gradle cache from ~/.gradle/cache and tried building and running the app again and still the issue persists with the same error log as posted above.

Thanks,

**Comment by karimnosseir** [comment]
Few questions/instructions:

In the initialize line for the delegate
  (e.g.) hexagonDelegate = new HexagonDelegate(activity);
Can you print 
  activity.getApplicationInfo().nativeLibraryDir
and check that the shared lib files are on the device under the same path.

adb shell ls -al <PATH_PRINTED_FROM_ABOVE>

If you can paste the results in the reply will be good. Thanks

**Comment by anidh** [comment]
> Few questions/instructions:
> 
> In the initialize line for the delegate
> (e.g.) hexagonDelegate = new HexagonDelegate(activity);
> Can you print
> activity.getApplicationInfo().nativeLibraryDir
> and check that the shared lib files are on the device under the same path.
> 
> adb shell ls -al <PATH_PRINTED_FROM_ABOVE>
> 
> If you can paste the results in the reply will be good. Thanks

Hi, thanks for the prompt reply 
1)I am using the Kotlin code so `hexagonDelegate = new HexagonDelegate(activity);` this is initialized like `var tflite_hex: Interpreter? = null` and then `options.addDelegate(hexagonDelegate)`
2) The directory which I'm getting from the `activity.getApplicationInfo().nativeLibraryDir` is 
`/data/app/com.example.sr_tflite-wK5_SXPZr9owo3sD9NNzpQ==/lib/arm64` and when I'm running the ad command I'm getting
```
adb shell ls -al /data/app/com.example.sr_tflite-wK5_SXPZr9owo3sD9NNzpQ==/lib/arm64
total 16
drwxr-xr-x 2 system system 4096 2020-05-15 02:39 .
drwxr-xr-x 3 system system 4096 2020-05-15 02:39 ..
```
I see that these so files are not present in that directory? but I have laid them out in correct structure as stated in the documentation.

Thanks

**Comment by karimnosseir** [comment]
Hi,
Sorry for the late reply.
You probably have some other changes in your gradle files that impact packaging files.
You can try googling how to package share library in your project (in case you have some advanced gradle files).
If it is packaged correctly and doesn't work feel free to reopen the bug or create new one.

Thanks

**Comment by anidh** [comment]
> Hi,
> Sorry for the late reply.
> You probably have some other changes in your gradle files that impact packaging files.
> You can try googling how to package share library in your project (in case you have some advanced gradle files).
> If it is packaged correctly and doesn't work feel free to reopen the bug or create new one.
> 
> Thanks

Thanks for replying. I tried researching more around this issue and found that maybe the so files which are provided aren't compatible with my phone arch. So I found that you can generate your own so file using the bezel toolkit for dsp delegate using the command `bazel build -c opt --config=android_arm64 tensorflow/lite/experimental/delegates/hexagon/java:tensorflow-lite-hexagon` 
But I'm getting an error 
    INFO: Call stack for the definition of repository 'hexagon_nn' which is a third_party_http_archive (rule definition at /home/anidh/tensorflow/third_party/repo.bzl:219:28):  
    - /home/anidh/tensorflow/third_party/hexagon/workspace.bzl:8:5  
    - /home/anidh/tensorflow/tensorflow/workspace.bzl:54:5  
    - /home/anidh/tensorflow/tensorflow/workspace.bzl:108:5  
    - /home/anidh/tensorflow/WORKSPACE:19:1  
    ERROR: /home/anidh/.cache/bazel/_bazel_anidh/b7383c6eddfc2c0b3ec247d3a8b0f2de/external/local_config_cc/BUILD:47:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'arm64-v8a'  
    ERROR: Analysis of target '//tensorflow/lite/experimental/delegates/hexagon/java:tensorflow-lite-hexagon' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed; build aborted  
    INFO: Elapsed time: 0.122s  
    INFO: 0 processes.  
    FAILED: Build did NOT complete successfully (0 packages loaded, 1 target configured)

Any help will be appreciated :)

**Comment by karimnosseir** [comment]
@anidh that looks like you didn't run .configure to configure your environment - note that you need to configure android section.

**Comment by yuqiu1233** [comment]
> > 嗨，
> > 抱歉，您的回复很晚。
> > 您的gradle文件中可能还会有其他更改，这些更改会影响打包文件。
> > 您可以尝试谷歌搜索如何在项目中打包共享库（如果您有一些高级gradle文件）。
> > 如果打包正确且无法正常工作，请随时重新打开该错误或创建一个新错误。
> > 谢谢
> 
> 感谢回复。我尝试对这个问题进行更多研究，发现也许所提供的文件与我的手机拱门不兼容。因此，我发现您可以使用Bezel工具包为命令使用dsp委托的dsp委托来生成自己的so文件，`bazel build -c opt --config=android_arm64 tensorflow/lite/experimental/delegates/hexagon/java:tensorflow-lite-hexagon`
> 但我收到错误
> 信息：调用堆栈以定义存储库'hexagon_nn'，该存储库为third_party_http_archive（/ home中的规则定义）
> /anidh/tensorflow/third_party/repo.bzl:219:28）：- /home/anidh/tensorflow/third_party/hexagon/workspace.bzl:8:5
> - /home/anidh/tensorflow/tensorflow/workspace.bzl:54 ：5
> - /home/anidh/tensorflow/tensorflow/workspace.bzl:108:5
> - /家庭/ anidh / tensorflow / WORKSPACE：19：1
> 错误：/home/anidh/.cache/bazel/_bazel_anidh/b7383c6eddfc2c0b3ec247d3a8b0f2de/external/local_config_cc/BUILD:47:1：在cc_toolchain_suite规则@local_config_cc // :: toolchain：cc_toolchain_suites'@对于cpu'arm64-v8a'
> 错误：目标'// tensorflow / lite / experimental / delegates / hexagon / java：tensorflow-lite-hexagon'的分析失败; 构建中止：目标'@local_config_cc //：toolchain'的分析失败；构建中止
> INFO：经过的时间：0.122s
> INFO：0个进程。
> 失败：构建未成功完成（已加载0个软件包，已配置1个目标）
> 
> 任何帮助将不胜感激 ：）

hello,anidh
I met the same problem with you, have you solved it?

**Comment by yuqiu1233** [comment]
> > Hi,
> > Sorry for the late reply.
> > You probably have some other changes in your gradle files that impact packaging files.
> > You can try googling how to package share library in your project (in case you have some advanced gradle files).
> > If it is packaged correctly and doesn't work feel free to reopen the bug or create new one.
> > Thanks
> 
> Thanks for replying. I tried researching more around this issue and found that maybe the so files which are provided aren't compatible with my phone arch. So I found that you can generate your own so file using the bezel toolkit for dsp delegate using the command `bazel build -c opt --config=android_arm64 tensorflow/lite/experimental/delegates/hexagon/java:tensorflow-lite-hexagon`
> But I'm getting an error
> INFO: Call stack for the definition of repository 'hexagon_nn' which is a third_party_http_archive (rule definition at /home/anidh/tensorflow/third_party/repo.bzl:219:28):
> - /home/anidh/tensorflow/third_party/hexagon/workspace.bzl:8:5
> - /home/anidh/tensorflow/tensorflow/workspace.bzl:54:5
> - /home/anidh/tensorflow/tensorflow/workspace.bzl:108:5
> - /home/anidh/tensorflow/WORKSPACE:19:1
> ERROR: /home/anidh/.cache/bazel/_bazel_anidh/b7383c6eddfc2c0b3ec247d3a8b0f2de/external/local_config_cc/BUILD:47:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'arm64-v8a'
> ERROR: Analysis of target '//tensorflow/lite/experimental/delegates/hexagon/java:tensorflow-lite-hexagon' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed; build aborted
> INFO: Elapsed time: 0.122s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (0 packages loaded, 1 target configured)
> 
> Any help will be appreciated :)

hello,anidh
I met the same problem with you, have you solved it?

**Comment by anidh** [comment]
> > > Hi,
> > > Sorry for the late reply.
> > > You probably have some other changes in your gradle files that impact packaging files.
> > > You can try googling how to package share library in your project (in case you have some advanced gradle files).
> > > If it is packaged correctly and doesn't work feel free to reopen the bug or create new one.
> > > Thanks
> > 
> > 
> > Thanks for replying. I tried researching more around this issue and found that maybe the so files which are provided aren't compatible with my phone arch. So I found that you can generate your own so file using the bezel toolkit for dsp delegate using the command `bazel build -c opt --config=android_arm64 tensorflow/lite/experimental/delegates/hexagon/java:tensorflow-lite-hexagon`
> > But I'm getting an error
> > INFO: Call stack for the definition of repository 'hexagon_nn' which is a third_party_http_archive (rule definition at /home/anidh/tensorflow/third_party/repo.bzl:219:28):
> > 
> > * /home/anidh/tensorflow/third_party/hexagon/workspace.bzl:8:5
> > * /home/anidh/tensorflow/tensorflow/workspace.bzl:54:5
> > * /home/anidh/tensorflow/tensorflow/workspace.bzl:108:5
> > * /home/anidh/tensorflow/WORKSPACE:19:1
> >   ERROR: /home/anidh/.cache/bazel/_bazel_anidh/b7383c6eddfc2c0b3ec247d3a8b0f2de/external/local_config_cc/BUILD:47:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'arm64-v8a'
> >   ERROR: Analysis of target '//tensorflow/lite/experimental/delegates/hexagon/java:tensorflow-lite-hexagon' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed; build aborted
> >   INFO: Elapsed time: 0.122s
> >   INFO: 0 processes.
> >   FAILED: Build did NOT complete successfully (0 packages loaded, 1 target configured)
> > 
> > Any help will be appreciated :)
> 
> hello,anidh
> I met the same problem with you, have you solved it?

Hi @yuqiu1233 

I didn't get the time to follow up with this issue as I shifted my focus to running models on GPU, but I think you need to run the ./configure script inside the tensorflow repository as provide the location of SDk as well as NDK and bunch of other things. This is how I was able to run things for the GPU. Hope it helps as this is all I know for now.

**Comment by karimnosseir** [comment]
@yuqiu1233 Why do you want to build it ? Did you try to use the prebuilt packages - by putting them in your gradle files ?
Can you explain what issues you had ?

Thanks

**Comment by yuqiu1233** [comment]
@karimnosseir I have generate three .so files by run tflite_hexagon_nn_skel_v1.20.0.0.run, and put these file in app/src/main/jniLibs. the same problem appear with you like this “Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.“ 

Did you solve this problem？

- use Snapdragon 855 chip
- tensorflow2.1
- python3.6

**Comment by yuqiu1233** [comment]
@anidh thanks for your reply！

**Comment by yuqiu1233** [comment]
@karimnosseir Sorry for the late reply.

the logcat as follow，I also find that no share lib in this path(activity.getApplicationInfo().nativeLibraryDir).

2020-08-24 09:27:56.012 19062-19062/com.example.myapplication I/com.example.myapplication: Successfully opened fastrpc_shell_3
2020-08-24 09:27:56.004 19062-19062/com.example.myapplication I/e.myapplication: type=1400 audit(0.0:111368): avc: denied { read } for name="fastrpc_shell_3" dev="sde48" ino=51 scontext=u:r:untrusted_app:s0:c241,c256,c512,c768 tcontext=u:object_r:adsprpcd_file:s0 tclass=file permissive=1 app=com.example.myapplication
2020-08-24 09:27:56.039 19062-19062/com.example.myapplication I/com.example.myapplication: Successfully created user PD on domain 3 (attrs 0x0, debug_trace 0x0)
2020-08-24 09:27:56.042 19062-19062/com.example.myapplication I/com.example.myapplication: fastrpc_perf_init: enabled RPC traces (kernel 0, dsp 0) with frequency 1000
2020-08-24 09:27:56.042 19062-19338/com.example.myapplication I/com.example.myapplication: FastRPC latency thread started for QoS
2020-08-24 09:27:56.048 19062-19336/com.example.myapplication W/com.example.myapplication: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/apps_std_imp.c:749: Warning: fopen returned 0x2 for file oemconfig.so. (No such file or directory)
2020-08-24 09:27:56.049 19062-19336/com.example.myapplication W/com.example.myapplication: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/apps_std_imp.c:749: Warning: fopen returned 0x2 for file libhexagon_nn_skel_v66.so. (No such file or directory)
2020-08-24 09:27:56.050 19062-19062/com.example.myapplication E/com.example.myapplication: Error 0x80000406: remote_handle_open_domain: dynamic loading failed for file:///libhexagon_nn_skel_v66.so?hexagon_nn_domains_skel_handle_invoke&_modver=1.0&_dom=cdsp on domain 3 (dlerror cannot open oemconfig.so)
2020-08-24 09:27:56.050 19062-19062/com.example.myapplication E/com.example.myapplication: Error 0x80000406: remote_handle64_open failed for file:///libhexagon_nn_skel_v66.so?hexagon_nn_domains_skel_handle_invoke&_modver=1.0&_dom=cdsp
2020-08-24 09:27:56.050 19062-19062/com.example.myapplication W/tflite: Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.
2020-08-24 09:27:56.050 19062-19062/com.example.myapplication I/tflite: Hexagon Delegate is not supported.
2020-08-24 09:27:56.052 19062-19062/com.example.myapplication D/ForceDarkHelper: updateByCheckExcludeList: pkg: com.example.myapplication activity: com.example.myapplication.MainActivity@855d042
2020-08-24 09:27:56.053 19062-19062/com.example.myapplication D/ForceDarkHelper: updateByCheckExcludeList: pkg: com.example.myapplication activity: com.example.myapplication.MainActivity@855d042
2020-08-24 09:27:56.067 19062-19095/com.example.myapplication D/OpenGLRenderer: endAllActiveAnimators on 0x6fc51ad400 (AlertController$RecycleListView) with handle 0x7017cebca0
2020-08-24 09:27:56.887 19062-19062/com.example.myapplication I/Toast: Show toast from OpPackageName:com.example.myapplication, PackageName:com.example.myapplication

**Comment by yuqiu1233** [comment]
@karimnosseir  
Thanks for you help!

This problem has been solved by pushing that three .so files to this path(activity.getApplicationInfo().nativeLibraryDir) 
manually.  The problem now is how to package share library in android project. I will google and try other methods.

I also have another question:
Whether static-sized input must be need for both GPU and DSP accelerate? Is there any way to make the model dynamic input when using GPU or DSP accelerate?

Look forward to your reply

**Comment by karimnosseir** [comment]
Hi @yuqiu1233 Hexagon DSP delegate supports dynamic batch size. it's only available now in C API
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/hexagon/hexagon_delegate.h#L25
and a full example is in this test, this part mainly
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/hexagon/builders/tests/batch_seq_config_test.cc#L105

**Comment by yuqiu1233** [comment]
@karimnosseir  thanks for you reply!
I think you may misunderstand me, the dynamic input size doesn't means the batch size number but shape of input image.

**Comment by karimnosseir** [comment]
@yuqiu1233 Nope i did understand you. Just saying what is supported at the moment :) 

Thanks

**Comment by yuqiu1233** [comment]
@karimnosseir what a pity it is! It is so meaningful in project that dynamic input with GPU or DSP accelerate. Hoping you can finish that function as soon as possible!

I really appreciate that you have solved the trouble confusing me quite a while!

**Comment by Xiaojun-Wang** [comment]
@vikramambrose I have the same error log as you. I set  minSdkVersion<= 22 but it still went wrong. I change build.gradle many times, but it didn't work. Android 10, OnePlus 7.Is any other difference you think may be wrong. May Android 10 didn't allow read DSP files? Your reply may be helpful for me. Thanks a lot.

**Comment by anidh** [comment]
> @vikramambrose I have the same error log as you. I set  minSdkVersion<= 22 but it still went wrong. I change build.gradle many times, but it didn't work. Android 10, OnePlus 7.Is any other difference you think may be wrong. May Android 10 didn't allow read DSP files? Your reply may be helpful for me. Thanks a lot.

I upgraded my OnePlus 5 to android 10 and I'm unable to access the DSP from then could be that issue. Will suggest to take a look at Snapdragon Neural Processing Engine and run basic examples there on DSP delegate and see if it works.

**Comment by Xiaojun-Wang** [comment]
@anidh Thanks for your reply. I have been working on this problem for a long time. Because I have installed a apk that always work well on DSP runtime and AIP runtime. But recently I suddenly found it didn't work. I use that app project in my master's degree paper. Thank you. I try on one SNPE SDK demo ( image-classifiers ), and the same error log happened always. I think it may be some permissions of Android 10 or .so files of system. I tried many solutions that didn't work either.  I also sought help form OnePlus tech. Hope it will help. I decide  to wait for OnePlus's reply. Thanks a lot.

**Comment by anidh** [comment]
> @anidh Thanks for your reply. I have been working on this problem for a long time. Because I have installed a apk that always work well on DSP runtime and AIP runtime. But recently I suddenly found it didn't work. I use that app project in my master's degree paper. Thank you. I try on one SNPE SDK demo ( image-classifiers ), and the same error log happened always. I think it may be some permissions of Android 10 or .so files of system. I tried many solutions that didn't work either.  I also sought help form OnePlus tech. Hope it will help. I decide  to wait for OnePlus's reply. Thanks a lot. 

I can say that we contacted Qualcomm regarding this issue and they said that it's upto OEM for locking of DSP. I think it's related to the DSP vulnerability found this year. 
I figured out a way to use DSP by rooting my phone and using the selinux policy. This gave me access back to DSP.

**Comment by Xiaojun-Wang** [comment]
@anidh Yeah, I also found the report about the DSP vulnerability. So I always doubt if OnePlus lock it. I tried root my  phone temporarily and run "setenforce 0" , but "adb shell root" didn't work and it showed "Permission denied". Did you mean root the phone permanently? Thanks, you help me  so much.

**Comment by anidh** [comment]
> @anidh Yeah, I also found the report about the DSP vulnerability. So I always doubt if OnePlus lock it. I tried root my  phone temporarily and run "setenforce 0" , but "adb shell root" didn't work and it showed "Permission denied". Did you mean root the phone permanently? Thanks, you help me  so much.

I haven't tried temporary rooting, I rooted my phone permanently. Using the setenforce command it worked for me 1 time and didn't work for me after the reboot.
