### ISSUE TITLE
Release GPU Memory(VRAM) after tf.keras.backend.clear_session()

### ISSUE THREAD

**Issue by Arktius** [tensorflow/tensorflow#39535]
**System information**
- Windows 10 Microsoft Windows [Version 10.0.18362.418]
- TensorFlow 2.0 installed from Conda:
- Python version: 3.6.10
- CUDA/cuDNN version:   NVIDIA-SMI 445.75       Driver Version: 445.75       CUDA Version: 11.0
- GPU model and memory: NVIDIA 2060S

**Describe the current behavior**
There's no command which frees the previously used VRAM. Even deleting the model and the data had no effect on the VRAM.

**Describe the expected behavior**
Any of these commands should release the VRAM. 

**Standalone code to reproduce the issue**
```
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow import math, dtypes
from tensorflow import float32 as f32 
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Input
import random
import numpy as np # linear algebra
import gc

rseed=10
np.random.seed(rseed)
random.seed(rseed)
tf.compat.v1.set_random_seed(rseed)
    
def MMSE( preds,targets, mask_value=0.0):
    tf.print('\npred',preds)
    tf.print('target',targets)
    mask = dtypes.cast(tf.not_equal(targets,0),f32) 
    num_rating = math.reduce_sum(mask) #count ratings
    loss = math.reduce_sum(math.square(mask*(preds - targets))) / num_rating 
    return loss


input_dim = Input(shape = (3, ))
model = Sequential()
model.add(Dense(3,input_dim=3))
model.add(Dense(3))
model.compile(optimizer = Adam(lr=0.01),loss=[MMSE]) 
            
data  = tf.math.round(tf.random.normal(shape=[5,3]))
history = model.fit(data,data, epochs = 1, batch_size = 5,verbose=0, shuffle=False) 

del input_dim,model,data,history
tf.compat.v1.reset_default_graph()
tf.keras.backend.clear_session()
gc.collect()

```
I've used nvidia-smi to check the memory-usage.

**Comment by byronyi** [comment]
It is currently not possible without exiting the Python process due to the fact that many TF internal objects, e.g. GPU memory pool, device streams, do not support clean shutdown.

**Comment by ravikyram** [comment]
Similar issue #36465. Thanks!

**Comment by Arktius** [comment]
What a pity. Can I somehow estimate it by using the number of trainable parameters and the batch size?

**Comment by Arktius** [comment]
One could check the model size or the trainable parameters, but this is somehow not satisfying. [Source](https://stackoverflow.com/questions/58513385/how-to-compare-or-measure-the-actual-size-of-models-in-tensorflow)

**Comment by gowthamkpr** [comment]
@Arktius As this issue has been answered, can you please create a new issue and close this one. Thanks!

**Comment by ELind77** [comment]
> It is currently not possible without exiting the Python process due to the fact that many TF internal objects, e.g. GPU memory pool, device streams, do not support clean shutdown.

This seems like a core deficiency in the library.  Is there  a followup ticket for a line of work to fix this?
