### ISSUE TITLE
Build tensorflow-lite-with-select-tf-ops Failed

### ISSUE THREAD

**Issue by ZhuXinyan** [tensorflow/tensorflow#39534]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution   Linux Ubuntu 18.04 
- TensorFlow installed from source
- TensorFlow version: r2.2
- Python version: Python 3.6.9
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source):gcc version 7.5.0
- CUDA/cuDNN version: no GPU
- GPU model and memory:no GPU

ndk-version ndkr18
sdk-version sdk 24.4.1

**Describe the problem**
when I complie tflite as https://www.tensorflow.org/lite/guide/ops_select#android_aar,
the error comes.
ERROR: no such target '//tensorflow/lite/java:tensorflow-lite-with-select-tf-ops': target 'tensorflow-lite-with-select-tf-ops' not declared in package 'tensorflow/lite/java' defined by /tensorflow_src/tensorflow/lite/java/BUILD

**Provide the exact sequence of commands / steps that you executed before running into the problem**
firstly , I prepare the environment as the manual https://www.tensorflow.org/install/source#configure_the_build
then I run  command as https://www.tensorflow.org/lite/guide/ops_select#android_aar
bazel build --cxxopt='--std=c++11' -c opt             \
  --config=android_arm --config=monolithic          \
  //tensorflow/lite/java:tensorflow-lite-with-select-tf-ops
 
ERROR: Skipping '//tensorflow/lite/java:tensorflow-lite-with-select-tf-ops': no such target '//tensorflow/lite/java:tensorflow-lite-with-select-tf-ops': target 'tensorflow-lite-with-select-tf-ops' not declared in package 'tensorflow/lite/java' defined by /tensorflow_src/tensorflow/lite/java/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//tensorflow/lite/java:tensorflow-lite-with-select-tf-ops': target 'tensorflow-lite-with-select-tf-ops' not declared in package 'tensorflow/lite/java' defined by /tensorflow_src/tensorflow/lite/java/BUILD

**Comment by daverim** [comment]
Hi, ZhuXinyan, the documentation actually shows you should use the target
//tensorflow/lite/java:tensorflow-lite-select-tf-ops
I think you added an extra -with- in your target.

**Comment by freedomtan** [comment]
@ZhuXinyan as @daverim said there is no `-with-` in current doc and code, probably you referred to an older version of the doc. The `BUILD` file was updated and the corresponding doc you referred to was updated too.

**Comment by ZhuXinyan** [comment]
Thanks，I find the English document is right but the chinese document is expired
