### ISSUE TITLE
tf.keras replace lower layer in pretrained resnet50

### ISSUE THREAD

**Issue by coded5282** [tensorflow/tensorflow#39530]
Is it possible to remove/replace the lower layers of a pretrained ResNet50 model in tf.keras.applications? I'm trying to replace the first Conv2D layer with a new one. The only examples I've seen online do it for adding to the top of the network, not the first few layers.

For instance, I've tried doing this:

```
import tensorflow as tf
pretrained_resnet = tf.keras.applications.ResNet50(include_top=False, weights='imagenet')
inputs = tf.keras.Input(shape=(256,256,1))
x = tf.keras.layers.ZeroPadding2D()(inputs)
x = tf.keras.layers.Conv2D(filters=64,
                           kernel_size=(7,7),
                           strides=(2,2),
                           padding='same')(x)
outputs = pretrained_resnet.layers[3](x)
test = tf.keras.Model(inputs, pretrained_resnet.output)
```
But it gives this error: ValueError: Graph disconnected: cannot obtain value for tensor Tensor("input_2:0", ......

Any suggestions would be greatly appreciated!

**Comment by ameyparanjape** [comment]
How did you resolve this @coded5282 ?

**Comment by francotheengineer** [comment]
I've attempted multiple work arounds for this exact issue. I have been unable to fix it. I suggest you either copy the code in the tf.keras implementation ResNet, then slice out the layers in the ResNet construction code and tack them on after your custom layer code. This allows you to get essentially `pretrained_resnet[3:]`. Then copy the imagenet weights across.
