### ISSUE TITLE
tflite with illegal instruction - Self compile of "_interpreter_wrapper.so" ?

### ISSUE THREAD

**Issue by starbrights** [tensorflow/tensorflow#39532]
**System information**
- Yocto Poky 3.0
- embedded device with ARM Cortex A9
- https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_armv7l.whl 
- Python version: 3.7
- GCC/Compiler 9.2:
- 512MB RAM:

**Describe the problem**
I can execute some tflite nets but not all. Not working: "mobilenet_v1_1.0_224.tflite" But working: "mobilenet_v1_1.0_224_quant.tflite". My suspect is that tensorflow is not compiled for my ARM CPU (Cortex A9) - although there is just one ARM32bit selection for a python whl.
I could recompile a "libtensorflow-lite.a" but howto create a python package or at least a substitute for the "_interpreter_wrapper.so" ? (this seems to be where the magic happens).

The only hint I found was for tensorflow (the big one) handling with docker. No experience with that, but I guess this doesn't use my cross-compiler and options.

**Comment by daverim** [comment]
Hi terryheo@, do you have some experience with arm linux?

**Comment by terryheo** [comment]
This is the way to build TFLite PIP package.

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package

**Comment by starbrights** [comment]
That is exactly what I am looking for. But I need a closer look - get an error
```
+ python3 setup.py bdist bdist_wheel
Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
```
although I installed all required dependencies. Maybe a cross compilation issue.

**Comment by starbrights** [comment]
I installed the required packages (swig libjpeg-dev zlib1g-dev python3-dev python3-numpy) in my x86 Linux downloaded the requirements. Starting that script will sta (until it fails with:
`interpreter_wrapper/interpreter_wrapper_pybind11.cc:16:10: fatal error: pybind11/pybind11.h: No such file or directory`
but compiles for x86 of course. In my first attempt I did set my SDK environment (intended for C/C++ cross compiling) and there has been no numpy ... installed.  Now I am a bit confused: How can I cross compile/create that?My hope has been to crosscompile tensorflow and wrapper/python stuff is independend from architecture. But is it like that?

**Comment by terryheo** [comment]
Which command did you used?

**Comment by starbrights** [comment]
First I did: 
```
modifiy /tensorflow/lite/tools/make/targets/riscv_makefile.inc (to make it cross compileable and fit to my arm)
source ~/sdk/environment-setup-cortexa9hf-neon-poky-linux-gnueabi (steup compiler, pathes)
./tensorflow/lite/tools/make/build_rpi_lib.sh
```
then I get an tensorflow/lite/tools/make/gen/rpi_armv7l/lib/libtensorflow-lite.a

But I want to get the python version of it:
So I executed the linked commands:

```
sudo apt install swig libjpeg-dev zlib1g-dev python3-dev python3-numpy
sh tensorflow/lite/tools/make/download_dependencies.sh
sh tensorflow/lite/tools/pip_package/build_pip_package.sh
```
But this is now on x86. I need to combine both .... ways, so cross compile the tensorflow and build the whl.

**Comment by starbrights** [comment]
A little step might be to add "TENSORFLOW_TARGET="rpi" to the build_pip_package.sh. But this is not enough....

**Comment by terryheo** [comment]
For the cross build of PIP, you need to use Docker based build.
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package#building-tensorflow-lite-standalone-pip
This is the current official way.
```
make BASE_IMAGE=debian:buster PYTHON=python3 TENSORFLOW_TARGET=rpi docker-build
```

There is another experimental method which uses ARM toolchain.
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package#cross-build-for-armhf-python-37
```
CI_DOCKER_EXTRA_PARAMS="-e CI_BUILD_PYTHON=python3 -e CROSSTOOL_PYTHON_INCLUDE_PATH=/usr/include/python3.7" \
  tensorflow/tools/ci_build/ci_build.sh PI-PYTHON37 \
  tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh armhf
```
I'm wondering which compile options you need to build for your target.
There is a similar issue with this. You can also refer https://github.com/tensorflow/tensorflow/issues/39957

**Comment by terryheo** [comment]
Let's close this. Please let me know if you still have the issue.

**Comment by starbrights** [comment]
Isn't there a way without docker? Guess docker uses it's own toolchain but I want use my own (yocto) compiler ....
