### ISSUE TITLE
NEED FAST HELP! Tensorflow Training Error

### ISSUE THREAD

**Issue by LordLamy** [tensorflow/tensorflow#39544]
Hi,

I am trying to code an AI with an linear regression algorithm with tensorflow.
But my model gives an error message when i try to train it:

This is my code
linear_est.train(train_input_fn)  # train
result = linear_est.evaluate(eval_input_fn)  # get model metrics/stats by testing on tetsing data

clear_output()  # clears consoke output
print(result)  # the result variable is simply a dict of stats about our model

And it says:
InvalidArgumentError: assertion failed: [Labels must be <= n_classes - 1] [Condition x <= y did not hold element-wise:] [x (head/losses/Cast:0) = ] [[8][10][2]...] [y (head/losses/check_label_range/Const:0) = ] [1]
	 [[{{node Assert}}]]

Take a look at the rest if you want to here:
https://drive.google.com/open?id=1kN3fnQQKJk2VdIZvj1XFrxg73C8BKaWz

Big Thanks and best Regards
Justin

**Comment by mihaimaruseac** [comment]
This is better suited for StackOverflow
