### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'LSTM' and 'int'

### ISSUE THREAD

**Issue by alokssingh** [tensorflow/tensorflow#39549]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

         self.kernel = self.add_weight(shape=(input_dim, self.units * 4),
                                      name='kernel',
                                      initializer=self.kernel_initializer,

TypeError: unsupported operand type(s) for *: 'LSTM' and 'int'

**Comment by ravikyram** [comment]
@alokssingh 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.

Request you to provide colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by alokssingh** [comment]
Thanks @ravikyram  for the quick response. I have resolved it.
