### ISSUE TITLE
Linux Shell does not appear when installing Tensorflow in Dockers (Win7)

### ISSUE THREAD

**Issue by Roboball** [tensorflow/tensorflow#3954]
Following these instructions:
http://www.netinstructions.com/how-to-install-and-run-tensorflow-on-a-windows-pc/`

executing the last command in cmd shell (Win7):
`docker run -it -p 8888:8888 gcr.io/tensorflow/tensorflow`

cmd is downloading, pulling, then Jupyiter notebook services gets started..., but then I get warnings and the linux shell does not appear:

`C:\Users\user>docker` run -it b.gcr.io/tensorflow/tensorflow
Unable to find image 'b.gcr.io/tensorflow/tensorflow:latest' locally
latest: Pulling from tensorflow/tensorflow
a64038a0eeaa: Pull complete
2ec6e7edf8a8: Pull complete
0a5fb6c3c94b: Pull complete
a3ed95caeb02: Pull complete
067b43ae9d67: Pull complete
3d200b674fb1: Pull complete
88dd2043900b: Pull complete
3ea4a014aa1c: Pull complete
ed48f1cb940c: Pull complete
34a0da2387dd: Pull complete
aa5acc667d66: Pull complete
Digest: sha256:d320d2da9c958ee42e61f810f296de602c674319b7a87b163a42329ac903a12c
Status: Downloaded newer image for b.gcr.io/tensorflow/tensorflow:latest
[I 15:44:31.744 NotebookApp] Writing notebook server cookie secret to /root/.loc
al/share/jupyter/runtime/notebook_cookie_secret
[W 15:44:31.790 NotebookApp] WARNING: The notebook server is listening on all IP
 addresses and not using encryption. This is not recommended.
[W 15:44:31.791 NotebookApp] WARNING: The notebook server is listening on all IP
 addresses and not using authentication. This is highly insecure and not recomme
nded.
[I 15:44:31.799 NotebookApp] Serving notebooks from local directory: /notebooks
[I 15:44:31.800 NotebookApp] 0 active kernels
[I 15:44:31.801 NotebookApp] The Jupyter Notebook is running at: http://[all ip
addresses on your system]:8888/
[I 15:44:31.801 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip `confirmation).`

What do I need to do to get the Linux Shell?

**Comment by aselle** [comment]
You can connect to the jupiter notebook by doing http://localhost:888
To get to the shell you need to find the process # of the running docker container
> docker ps 
(this will give a list of running docker instances. Get the sha code (first column) and use it when running

> docker exec  -t -i <hash> bash

That should give you a bash shell.
(this is not a tensorflow specific answer)

**Comment by Roboball** [comment]
thank you. just one final question. Can I use some comfortable editor like spyder from anaconda?? or do I have to stick to bash in cmd prompt?

finally this code line worked for me:
`docker` run -it b.gcr.io/tensorflow/tensorflow:latest-devel``
for reference:
http://stackoverflow.com/questions/35582875/unable-to-start-tensorflow-within-docker-on-windows

**Comment by aselle** [comment]
You can install stuff from the shell using apt-get install (including
editors). If you want this to be done more persistently you can derive your
own sub dockerfile that is derived from the tensorflow one (in fact
tensorflow is derived from the ubuntu image one).

-A

**Comment by swarathesh** [comment]
im getting this error im in docker shell in ubuntu 
`root@1e94bee0135a:/tensorflow# docker ps
bash: docker: command not found
root@1e94bee0135a:/tensorflow# docker ps 
bash: docker: command not found
`
