### ISSUE TITLE
Error During Model Conversion from Keras to TFLite : AttributeError: 'Model' object has no attribute '_get_save_spec'

### ISSUE THREAD

**Issue by mahakal001** [tensorflow/tensorflow#39553]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):18.04
- TensorFlow installed from (source or binary):binary
- TensorFlow version (or github SHA if from source):2.2.0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.
https://colab.research.google.com/drive/1APB9ATKjQHfOq8kq2_SvvNYYz_AVnnZh
```
# Copy and paste here the exact command
```
converter = tf.lite.TFLiteConverter.from_keras_model(model)

**The output from the converter invocation**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-297-83ed6c530300> in <module>
----> 1 converter = tf.lite.TFLiteConverter.from_keras_model(model)

~/hdd/learning/dl/venv/lib/python3.6/site-packages/tensorflow/lite/python/lite.py in from_keras_model(cls, model)
    430       # signature including the batch dimension specified by the user.
    431       input_signature = _saving_utils.model_input_signature(
--> 432           model, keep_original_batch_size=True)
    433 
    434     func = _saving_utils.trace_model_call(model, input_signature)
~/hdd/learning/dl/venv/lib/python3.6/site-packages/tensorflow/python/keras/saving/saving_utils.py in model_input_signature(model, keep_original_batch_size)
     75     TensorSpecs. This list does not contain the `training` argument.
     76   """
---> 77   input_specs = model._get_save_spec(dynamic_batch=not keep_original_batch_size)  # pylint: disable=protected-access
     78   if input_specs is None:
     79     return None

AttributeError: 'Model' object has no attribute '_get_save_spec'

![Screenshot from 2020-05-15 00-17-16](https://user-images.githubusercontent.com/17315769/81973844-5b2e7280-9642-11ea-9424-8ed29566c46e.png)

**Comment by mahakal001** [comment]
As mentioned in one of the other issues thread, I replaced keras with tf.keras. The issue is now solved.

**Comment by Ljiajie** [comment]
> As mentioned in one of the other thread, I replaced keras with tf.keras. The issue is now solved.

Can you describe your solution detail？ I had the same problem.
