### ISSUE TITLE
Multithreaded Function Stops after Model is Instantiated

### ISSUE THREAD

**Issue by LryF** [tensorflow/tensorflow#39566]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 19.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.7
- CUDA/cuDNN version: 10.1/7.6.5
- GPU model and memory: RTX 2070

This is kind of a follow up to [a previous issue](https://github.com/tensorflow/tensorflow/issues/39431) I had, about a Python hanging when `.predict` was called in a thread, however, that wasn't thoroughly reproducible.

I have further narrowed down the issue to a model being instantiated inside a thread.  Below is a useless function that demonstrates the issue:

```python
def my_function():
    print('barfoo')
    a = tf.keras.Sequential([tf.keras.layers.Dense(4, input_shape=(16,))])
    print('foobar')
```

When this isn't put in a thread with multiprocessing, it correctly prints:

```
barfoo
foobar
```

However, when put in a multiprocessing thread, it only prints:

```
barfoo
```

[Here](https://colab.research.google.com/gist/LryF/3898b2da42d706bb0be910b572d97a6c/other-test.ipynb) is a notebook that replicates the issue.

**Comment by ravikyram** [comment]
I have tried in colab with TF GPU 2.1.0, 2.2.0 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/07100c361ddcd855b68038ede0cc19c5/untitled888.ipynb).Thanks!

**Comment by LryF** [comment]
Any thoughts? @omalleyt12

**Comment by sushreebarsa** [comment]
@LryF  Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!
