### ISSUE TITLE
predict_signature_def to support multiple inputs and outputs

### ISSUE THREAD

**Issue by NandishAndDev** [tensorflow/tensorflow#39568]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 3.6
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

To covert a Keras model to Tensorflow, we need the input and output signatures. This is registered via the function `predict_signature_def`
This methods requires inputs  and outputs be a single Tensor.  If my Keras model has multiple inputs and outputs, how to I specify them in this API? 

**Will this change the current api? How?**

**Who will benefit with this feature?**
Developers looking to migrate from Keras to Tensor format

**Any Other info.**

**Comment by ymodak** [comment]
You can specify multiple inputs and outputs in dictionary of string to tensor.
See https://www.tensorflow.org/api_docs/python/tf/compat/v1/saved_model/predict_signature_def
```python. 
 signature = tf.saved_model.predict_signature_def(
                        inputs = {'input1':x1,'input2':x2},
                        outputs = {'output1':y1,'output2:y2})
```

**Comment by NandishAndDev** [comment]
Thanks . I am able to convert now. If I may suggest, the documentation for the API is brief, and it will be useful  to have these nuances mentioned. There are lot of posts on Stackoverflow where developers assume that this API is only for Single Tensors.

**Comment by ymodak** [comment]
Thanks for the feedback. I will update that piece of documentation soon.
Closing this issue since it's resolved.
