### ISSUE TITLE
get_tensor CheckpointReader_GetTensor error

### ISSUE THREAD

**Issue by luoqishuai** [tensorflow/tensorflow#39575]
**System information**
- OS Platform and Distribution :win 10
- OS -V:1903
- TensorFlow installed from (source or binary):binary
- TensorFlow version:TensorFlow-gpu==2.0.0
- Python version:3.6.5
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:cuda:10.0.130 cudnn:7.6.5
-nvidia driver :445.87
- GPU model and memory:2070super 8G      64G Ram

The phenomenon that I encountered was this
```
from tensorflow.python import pywrap_tensorflow
model_reader = pywrap_tensorflow.NewCheckpointReader(r"E:\dl_model\chinese_L-12_H-768_A-12\bert_model.ckpt")
var_dict = model_reader.get_variable_to_shape_map()
for key in var_dict:
    print("variable name: ", key)
    print(model_reader.get_tensor(key))
```
I run this code.
ide print
```
C:\public\study\python\python.exe C:/public/study/work/test/test.py
2020-05-15 20:18:56.028434: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
variable name:  bert/encoder/layer_0/output/dense/kernel

Process finished with exit code -1073741819 (0xC0000005)
```
The code runs to
```
get_tensor

return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
```
When compat.as_bytes(tensor_str) get result.
I click step into.
The ide shows the code running for a while.
And then,print
`Process finished with exit code -1073741819 (0xC0000005).`

I try 3 models to read.They have the same result. I think it is not model cause question.
I try to delete cuda ,cudnn,nvidia driver.Install other version.
From 10.1.243/7.6.5  10.1.243/7.6.4 10.1.168/7.6.5 10.2.89/7.6.5 10.0.130/7.6.5 10.0.130/7.4.2
I install Visual Studio 2015/2017/2019 not include many plug-ins.
I install conda(python3.7) try to install tensorflow-gpu==2.0.0.

I don't know what causes this question.
Maybe it's my gpu environment,computer environment,maybe other.

My understanding of the problem is that python calls c.
So many people have no problem, so the probability is not a problem of the code.
Although I know about the installation environment, I shouldn't be looking for you on github.
But I really tried what I thought, what I found on the Internet, and it still hasn't been solved.
I hope you can help me, even if only in some directions.
If you need any other information, please tell me

**Comment by Saduf2019** [comment]
@luoqishuai 
Can you please share simple stand alone code for us to replicate this along with the error logs for us to analyse, or if possible share a colab gist with error for us to analyse and help you.

**Comment by luoqishuai** [comment]
> 
> 
> @luoqishuai
> Can you please share simple stand alone code for us to replicate this along with the error logs for us to analyse, or if possible share a colab gist with error for us to analyse and help you.

In fact, This is the code in question.At get_tensor ,ide print `Process finished with exit code -1073741819 (0xC0000005)`
```
from tensorflow.python import pywrap_tensorflow
model_reader = pywrap_tensorflow.NewCheckpointReader(r"E:\dl_model\chinese_L-12_H-768_A-12\bert_model.ckpt")
var_dict = model_reader.get_variable_to_shape_map()
for key in var_dict:
    print("variable name: ", key)
    print(model_reader.get_tensor(key))
```

I debug it.
It is exit at pywrap_tensorflow_internal.py 915  :
CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
It not raise Exception by python .

**Comment by luoqishuai** [comment]
bert_model.ckpt is download by 
https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip

**Comment by luoqishuai** [comment]
I can try anything to give you the information you want, except to smash the computer.

**Comment by luoqishuai** [comment]
When i in pywrap_tensorflow_internal.py CheckpointReader_GetTensor .
I cant click CheckpointReader_GetTensor.
There is a picture 
https://sm.ms/image/RjDNG8nLaQWfYsb

```
tf.test.is_built_with_cuda()
tf.test.is_gpu_available()
tf.test.is_built_with_gpu_support()
```
All return True
My vs2017 can import cuda10.
Is there anything else that might cause me to not be able to run **get_tensor** method?
I'm going to try everything

**Comment by luoqishuai** [comment]
@Saduf2019

**Comment by luoqishuai** [comment]
I can't 
`use _pywrap_tensorflow_internal.pyd `
`CheckpointReader_GetTensor `
to get tensor
