### ISSUE TITLE
tf.keras.preprocessing.text_dataset_from_directory function

### ISSUE THREAD

**Issue by victorkab92** [tensorflow/tensorflow#39584]
AttributeError                            Traceback (most recent call last)
<ipython-input-15-9116635614ef> in <module>()
----> 1 train_ds = tf.keras.preprocessing.text_dataset_from_directory( x_train,
      2                                                               labels='inferred',
      3                                                               label_mode='int',
      4                                                               batch_size=batch_size,
      5                                                               validation_split=0.2,

AttributeError: module 'tensorflow.keras.preprocessing' has no attribute 'text_dataset_from_directory'

**Comment by amahendrakar** [comment]
@victorkab92,
As per the [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/text_dataset_from_directory), the API is available only in TF-nightly version.

I was able to import the API with the latest TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/67a1fb7ec8dec4595659f95a8f039687/39584.ipynb). Thanks!

**Comment by Harish2104** [comment]
i am also facing the same issue and i installed tf - nightly as well as suggested, but still facing the same issue. I am getting the same error while loading text_dataset_from_directory and TextVectorization function. Please help me on this.

**Comment by amahendrakar** [comment]
> i am facing the same issue, i installed tf - nightly as well as suggested, but still unable to resolve issue. I am getting the same error while loading text_dataset_from_directory and TextVectorization functions. I am not sure if am missing anything. Please help me on this.

@Harish2104,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template along with the complete code, so that we can track the issue there. Thanks!

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by Rajalod75** [comment]
i am facing the same issue, any solution please  ?!!

**Comment by tabatabaeis** [comment]
Same error here

**Comment by amahendrakar** [comment]
@Rajalod75, @tabatabaeis 
Could y'all please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
