### ISSUE TITLE
Why am I getting a no gradient provided for any variable error?

### ISSUE THREAD

**Issue by RodrigoPina407** [tensorflow/tensorflow#39589]
I'm trying to do a style transfer program, and when I get to the optimization I get the no gradient provided for any variable.
[notebook](
https://github.com/RodrigoPina407/StyleTransfer/blob/master/StyleTransferV2.ipynb)

```
epochs=200

melhor_loss = 2000000000
melhor_imagem = None

min_value = MEAN
max_value = 255 + MEAN
loss = 0.0

for e in range(epochs):
  with tf.GradientTape() as tape:
    tape.watch(output_processado)
    output_feats = modelo(output_processado)

    loss = total_loss(content_feats, style_feats, output_feats)

    grad = tape.gradient(loss, output_processado)
    optimizer.apply_gradients(zip([grad],[output_processado]))

    clip = tf.clip_by_value(output, min_value, max_value)
    output_processado.assign(clip)
  if loss < melhor_loss:
    melhor_imagem = output_processado
    melhor_loss = loss
    print("Epoch: " + e + "Loss diminui para " + melhor_loss)
```

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-236-4b717f5a772e> in <module>()
>      16 
>      17     grad = tape.gradient(loss, output_processado)
> ---> 18     optimizer.apply_gradients(zip([grad],[output_processado]))
>      19 
>      20     clip = tf.clip_by_value(output, min_value, max_value)
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py in apply_gradients(self, grads_and_vars, name, experimental_aggregate_gradients)
>     470       ValueError: If none of the variables have gradients.
>     471     """
> --> 472     grads_and_vars = _filter_grads(grads_and_vars)
>     473     var_list = [v for (_, v) in grads_and_vars]
>     474 
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py in _filter_grads(grads_and_vars)
>    1217   if not filtered:
>    1218     raise ValueError("No gradients provided for any variable: %s." %
> -> 1219                      ([v.name for _, v in grads_and_vars],))
>    1220   if vars_with_empty_grads:
>    1221     logging.warning(
> 
> ValueError: No gradients provided for any variable: ['Variable:0']

**Comment by ravikyram** [comment]
@RodrigoPina407 

I have tried in colab with TF version 2.1.0 ,2.2.0 and i am seeing the below error message.
`OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.`.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/1f70784c1aac0b07f41b10f3c17d26ef/untitled898.ipynb).Thanks!

**Comment by RodrigoPina407** [comment]
That problem is caused by the if statement `if loss < melhor_loss:` but if I remove it and its contents I get the error I described above, "No gradiants provided for any variable"

**Comment by RodrigoPina407** [comment]
> 
> 
> @RodrigoPina407
> 
> I have tried in colab with TF version 2.1.0 ,2.2.0 and i am seeing the below error message.
> `OperatorNotAllowedInGraphError: using a `tf.Tensor`as a Python`bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.`.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/1f70784c1aac0b07f41b10f3c17d26ef/untitled898.ipynb).Thanks!

**Comment by ravikyram** [comment]
I have tried in colab with TF 2.1, 2.2 and was able to reproduce the issue.Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/88d65fc8ed4bf16c23f58685598d354f/untitled902.ipynb).Thanks!

**Comment by RodrigoPina407** [comment]
Do you have a suggestion on how to solve it?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
