### ISSUE TITLE
Model saved with Lambda layer with a ragged input breaks when reloading

### ISSUE THREAD

**Issue by tanguycdls** [tensorflow/tensorflow#39580]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
With the following model ragged inputs -> Embeddings -> reduce_sum with lambda layer -> Dense a saved model cannot be loaded back. 

```
a = Input(ragged=True, name='a', shape=(None,), dtype=tf.int32)
b = Input(ragged=True, name='b', shape=(None,), dtype=tf.int32)
embed_a = Embedding(10,  3)(a)
embed_b = Embedding(10, 3)(b)
embed_a_reduced = Lambda(tf.reduce_sum, arguments=dict(axis=1))(embed_a)
embed_b_reduced = Lambda(tf.reduce_sum, arguments=dict(axis=1))(embed_b)
concat = Concatenate()([embed_a_reduced, embed_b_reduced])
out = Dense(1)(concat)
m = Model([a, b], out)
m([tf.ragged.constant([[0], [], [1]]), tf.ragged.constant([[0], [], [1]])])
m.save('/tmp/test')
reloaded_model = tf.keras.models.load_model('/tmp/test')
```
```
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py in wrapper(*args, **kwargs)
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):

TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
14 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py in wrapper(*args, **kwargs)
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a
    204       # TypeError, when given unexpected types.  So we need to catch both.
--> 205       result = dispatch(wrapper, *args, **kwargs)
    206       if result is not OpDispatcher.NOT_SUPPORTED:
    207         return result

TypeError: 'module' object is not callable
```
if we debug dispatch is the module dispatch and not the function in that file. 

**Describe the expected behavior**
We should be able to save / load back the model.

**Standalone code to reproduce the issue**
https://colab.research.google.com/gist/tanguycdls/4685e5111c5e3bad43c7699977b49c9c/untitled.ipynb Tested on 2.2 but same error in nightlies. 

**Other info / logs** 
One fix is to use tf nightly and override a keras Layer it then works.

**Comment by Saduf2019** [comment]
I am able to replicate this error reported, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/ae5cd9a949c09ee078e41fb22d7bddc2/untitled183.ipynb)

**Comment by holi-ampx** [comment]
What is worse on this error is, that even if it is caught (by except), it somehow mangles the imports and naming and subsequently
`tf.keras.layers.Reshape([1, 1])` returns `{TypeError}super() argument 1 must be type, not function`

**Comment by tanguycdls** [comment]
Still an issue in TF 2.4.1 (same gist updated the version)

**Comment by jvishnuvardhan** [comment]
@tanguycdls I updated two lines in your code as shown below. With that modification, it worked without any error. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/c0c8c9500cb5fbfd4e71915d577e9b99/untitled183.ipynb)

#### Two line before update 
```

# embed_a_reduced = Lambda(tf.reduce_sum, arguments=dict(axis=1))(embed_a)
# embed_b_reduced = Lambda(tf.reduce_sum, arguments=dict(axis=1))(embed_b)
```

#### Two line after update 
```
embed_a_reduced = Lambda(lambda x:tf.reduce_sum(x,axis=1))(embed_a)
embed_b_reduced = Lambda(lambda x:tf.reduce_sum(x, axis=1))(embed_b)
```

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by tanguycdls** [comment]
@jvishnuvardhan Thanks that's really strange. Do you see why such behavior happens ?

**Comment by jvishnuvardhan** [comment]
@tanguycdls I am not expert in serialization. But, this approach worked for me in my other code. Thanks!

I am closing this issue as this was resolved. Please feel free to reopen if this issue persists again. Thanks!

**Comment by jvishnuvardhan** [comment]
@tanguycdls @tomerk is an expert and he recommends using tensorflow `op` layer over `lambda` layer as op layers will serialize/deserialize more reliably than arbitrary lambda layers. So, the following approach is the best. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/5a1821b0f30a02c37ff7e9ecf61840f5/untitled183.ipynb). Thanks!


```
# This works
embed_a_reduced = tf.reduce_sum(embed_a, axis=1)
embed_b_reduced = tf.reduce_sum(embed_b, axis=1)
```
