### ISSUE TITLE
Why is tensorflow-gpu still being released for new versions of tensorflow?

### ISSUE THREAD

**Issue by tobigue** [tensorflow/tensorflow#39581]
The tensorflow documentation states that the `tensorflow` package supports both CPU and GPU (since version 2.x).

My question is why the `tensorflow-gpu` package is still being released for new versions of tensorflow.

This might be confusing to people (it was for me, definitely), especially because  https://pypi.org/project/tensorflow-gpu has no information on the matter.

I think it would be nice to add a note to the documentation and pypi, _why_ the `tensorflow-gpu` package still exists (if it must), so that other people don't have to go through the trouble of downloading and `diff`ing the wheels. :grimacing:

Cheers!

**Comment by mihaimaruseac** [comment]
There are toolchains that explicitly install tensorflow-gpu, that's why we continue to release them, although they are the same pip just renamed.

**Comment by gunan** [comment]
As @mihaimaruseac expressed, it is still being released to ensure that all systems have ample time to migrate.

@yifeif Can you add some information on pypi pages for tensorflow.* and tf-nightly.* ?
