### ISSUE TITLE
tf.metrics.MeanIoU throws dimensions mismatch error when used with SparseCategoricalCrossEntropy

### ISSUE THREAD

**Issue by dhaneshr** [tensorflow/tensorflow#39586]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 20.04
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): TF.2.2.0
- Python version: 3.8
- Bazel version (if compiling from source): 2.0
- GCC/Compiler version (if compiling from source): gcc7
- CUDA/cuDNN version: 10.2
- GPU model and memory: Nvidia Titan Xp (12GB)

**Describe the current behavior**

`tf.metrics.meanIOU` throws a dimensions mismatch error when using a model trained using `SparseCategoricalCrossEntropy `for a semantic segmentation problem.
`My model outputs  dimensions = 224x224x2, y_true = 224x224x1 (class_indices).`

A workaround was suggested at https://github.com/tensorflow/tensorflow/issues/32875#issuecomment-629360707 and worked for TF2.1, but fails with a dimensions mismatch error for TF2.2.
 The suggested fix that doesn't work in TF.2.2:

```

# fix for miou calculation when using sparse_categorical _cross_entropy 
    # https://github.com/tensorflow/tensorflow/issues/32875

class UpdatedMeanIoU(tf.keras.metrics.MeanIoU):
    @tf.function
    def __call__(self, y_true, y_pred, sample_weight=None):
        self.y_pred = tf.math.argmax(self.y_pred, axis=-1)
        return super().__call__(y_true, self.y_pred, sample_weight=sample_weight)

```
Here is the error:

Traceback (most recent call last):

```

    ValueError: Dimension 0 in both shapes must be equal, but are 1048576 and 2097152. Shapes are [1048576] and [2097152].
    	From merging shape 0 with other shapes. for '{{node confusion_matrix/stack_1}} = Pack[N=2, T=DT_INT64, axis=1](confusion_matrix/control_dependency_2, confusion_matrix/control_dependency_3)' with input shapes: [1048576], [2097152].
```

Appreciate a fix.

**Comment by ravikyram** [comment]
@dhaneshr 

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by ghwatson** [comment]
also having this issue. bump!

**Comment by ghwatson** [comment]
try this out: https://stackoverflow.com/questions/61824470/dimensions-mismatch-error-when-using-tf-metrics-meaniou-with-sparsecategorical

**Comment by Hung20736** [comment]
I also have this problem, this is my notebook:

https://colab.research.google.com/drive/15Sta5cKbQ8e4UC1Fh_D2yg9nYpmVzNIT#scrollTo=NkQtWL5PMj0l

You can check it. There are some workarounds using inheritance of tf.keras.metrics.Metric but I think it's better that this bug is fixed.
