### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'numpy' in Tensorflow 2.1

### ISSUE THREAD

**Issue by kevin-bony8998** [tensorflow/tensorflow#39582]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Binary (pip install)
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: NA

**Describe the current behavior**
I am trying to generate a custom loss function but to do that I need to extract the value of the tensor. However, when I use the numpy() function, it says "AttributeError: 'Tensor' object has no attribute 'numpy'". I don't understand why this is happening. Also, tf.executing_eagerly() returns false even though I include the parameter "run_eagerly=True" in the compile statement. Any help would be appreciated.

**Describe the expected behavior**
Ideally, the code should let me access the value of the tensor for further manipulation.

**Standalone code to reproduce the issue**

```
def custom_error_finder(y_actual,y_pred):
	print(tf.executing_eagerly())
	count = 0
	qw = tf.py_function((y_actual).numpy())
	ya = ((y_actual[0].numpy()).decode())
	yp = ((y_pred[0].numpy()).decode())
	for i,j in ya,yp:
		if i!=j:
			count = count+1
	mse = pow(count,2)/len(ya)
	return mse
```
Above is the custom loss function that I am trying to use. The dataset I am training my model on contains only strings.

**Comment by ravikyram** [comment]
@kevin-bony8998 

Looks like code is incomplete. Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!
