### ISSUE TITLE
tensorboard: graph visualization failed, undefined

### ISSUE THREAD

**Issue by jmugan** [tensorflow/tensorflow#3958]
In Chrome it says: "Graph visualization failed: TypeError: Connot read property 'length' of undefined.

In Firefox it says: "Graph visualization failed: TypeError: rawNodes is undefined"

I have attached the events file (appended '.txt' so it Github would accept it.)
[events.out.tfevents.1471882692.JMugan.local.txt](https://github.com/tensorflow/tensorflow/files/430670/events.out.tfevents.1471882692.JMugan.local.txt)

When I run with inspect, I get
```
======================================================================
Processing event files... (this can take a few minutes)
======================================================================

Found event files in:
/Users/jmugan/tensorlog

These tags are in /Users/jmugan/tensorlog:
audio -
histograms -
images -
scalars
   exp_cost
   perplexity
   train_cost
======================================================================

Event statistics for /Users/jmugan/tensorlog:
audio -
graph
   first_step           0
   last_step            0
   max_step             0
   min_step             0
   num_steps            1
   outoforder_steps     []
histograms -
images -
scalars
   first_step           23210
   last_step            23230
   max_step             23230
   min_step             23210
   num_steps            3
   outoforder_steps     []
sessionlog:checkpoint -
sessionlog:start -
sessionlog:stop -
======================================================================
```

**Comment by prb12** [comment]
Please can you provide the information requested in the TensorFlow issues reporting template.

**Comment by jmugan** [comment]
Operating System: Mac OS, Ubuntu
Installed version of CUDA and cuDNN: CPU

1. Which pip package you installed.
https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.10.0rc0-py2-none-any.whl

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.10.0rc0

### Steps to reproduce
1. start tensorboard
2. go to "graphs" tab.

### What have you tried?
1. Other graghs work. There is just something about this model.
2. I tried different browsers (Firefox and Chrome) and different OS (Ubuntu)

**Comment by 3rd3** [comment]
@jmugan I am getting the same error. Did you find a workaround?

**Comment by jmugan** [comment]
@3rd3 No, still an issue. Mine uses dynamic RNNs, so that might have something to do with the problem. I thought I saw an open issue related to that.

**Comment by 3rd3** [comment]
I make use of higher-order functions (scan and map) and I think dynamic_rnn does so too.

**Comment by danmane** [comment]
Acknowledged, we're looking into it.

**Comment by chihuahua** [comment]
For the `data/graph` endpoint, the event accumulator returns a very trivial graph:
```
versions {
  producer: 10
}
```
Looking into why.

**Comment by chihuahua** [comment]
The proto within that events file does contain a (giant) graph_def: https://gist.github.com/chihuahua/00a85d5ce964e8fde833c45e400ade07

The backend's just ... not parsing it and instead returning a trivial graph. Diving deeper.

**Comment by chihuahua** [comment]
Actually, events.out.tfevents.1471882692.JMugan.local seems to lack a graph. The graph_def is trivial (15 bytes):
https://gist.github.com/chihuahua/bab7d4ac3c3bd7cf52955540dd5b9eb4

Could you please provide info on how the file was generated? For starters, the graph is being passed to the summary writer, right?

If that's the case, I wonder why the summary writer is stubbing away the graph ...

**Comment by jmugan** [comment]
I do it like this. Is this what you are asking?
```
with tf.Session() as sess:
    summary_writer = tf.train.SummaryWriter(summary_path, sess.graph)
````

**Comment by danmane** [comment]
Maybe you don't have a graph defined on the session at that point? Did you already construct your tensorflow graph at the time you invoke that line of code?

I think we'll need you to post a reproduction if we are going to debug this further. Preliminarily, it looks like it's an issue with your instantiation of the summary writer, not with the graph visualizer.

**Comment by jmugan** [comment]
Ah, you may be right. I'll take a look.

**Comment by 3rd3** [comment]
@danmane My problem was that the graph was not yet defined, sorry. Perhaps it would be worthwhile to note in the error message in TensorBoard that the graph passed to SummaryWriter needs to be fully defined. What I expected was that one could simply pass `sess.graph` before building the graph and it would be written with the next write_summaries. Or, perhaps, completely remove the writing operation from the constructor, because such side effects in a constructor are somehow counter-intuitive (but that's perhaps just me).

**Comment by jmugan** [comment]
Oh, wow, do I feel like a fool. That fixed it for me. Thanks! Yeah, I guess I didn't realize the order of operations was important there. Sorry for the trouble.

**Comment by danmane** [comment]
I think @3rd3 is right that this is really a counter-intuitive API, rather than a user error.
I'm working on re-writing the API for writing summaries and events in advance of the tensorflow 1.0 release, and I'll keep this issue in mind.

**Comment by akewarmayur** [comment]
![Capture](https://user-images.githubusercontent.com/31464781/119702060-aba1f800-be72-11eb-8fc6-b14c8af65270.PNG)
Getting this error while visualizing the .pb model.
I have created "events.out.tfevents.1621934261.6e85c43ac415" file from following code.
`model_filename = 'model.pb'
import tensorflow as tf
from tensorflow.python.platform import gfile
with tf.Session() as sess:
    with gfile.FastGFile(model_filename, 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        g_in = tf.import_graph_def(graph_def)
LOGDIR='op'
train_writer = tf.summary.FileWriter(LOGDIR)
train_writer.add_graph(sess.graph)
`
