### ISSUE TITLE
what-if-tool link broken in tensorflow.org Tools page

### ISSUE THREAD

**Issue by bikashkumars** [tensorflow/tensorflow#39599]
#38076  URL(s) with the issue:
https://www.tensorflow.org/resources/tools#

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/resources/tools#

## Description of issue (what needs changing):
Link to what-if-tool is broken, as what-if moved to new repo.

### Clear description
Current broken link, when someone clicks on "Get Started" link at 
https://www.tensorflow.org/resources/tools

Broken link ->
https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/interactive_inference/What_If_Tool_Notebook_Usage.ipynb

New Correct link should be ->
https://github.com/PAIR-code/what-if-tool/blob/master/What_If_Tool_Notebook_Usage.ipynb

For example, why should someone use this method? How is it useful?

### Correct links
https://github.com/PAIR-code/what-if-tool/blob/master/What_If_Tool_Notebook_Usage.ipynb

I wanted to submit a pull-request for this

**Comment by MarkDaoust** [comment]
Hi @bikashkumars, thanks for reporting this. 

I've converted this to an internal bug assigned to the page owner (that's a page I can't fix). 

I'm closing this as we have the internal bug now.

Thanks.
