### ISSUE TITLE
Simple Quantization aware training (TF Tutorial) throws a warning

### ISSUE THREAD

**Issue by jvishnuvardhan** [tensorflow/tensorflow#39594]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): colab
- TensorFlow installed from (source or binary): 2.2
- TensorFlow version (or github SHA if from source):

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

https://colab.research.google.com/github/tensorflow/model-optimization/blob/master/tensorflow_model_optimization/g3doc/guide/quantization/training_example.ipynb

**The output from the converter invocation**

```
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py:465: set_learning_phase (from tensorflow.python.keras.backend) is deprecated and will be removed after 2020-10-11.
Instructions for updating:
Simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/tracking.py:105: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: /tmp/tmpjvd7obgu/assets
```

**Failure details**
There is no failure as such. But there is a warning which is not clear to any common user. It would be helpful if the warning guides the user to root-cause of the issue so that user will update `training` argument.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by MeghnaNatraj** [comment]
We're currently working on removing these warnings and will update this issue once it's resolved.

**Comment by MeghnaNatraj** [comment]
Issue has been resolved.

**Comment by sammilei** [comment]
I have also on TensorFlow 2.2 with Linux 18.04 and trying transfer learning with a config file. I got the same warning and the process just stopped but not terminating.
```
WARNING:tensorflow:From /root/.local/lib/python3.6/site-packages/object_detection/model_lib_v2.py:355: set_learning_phase (from tensorflow.python.keras.backend) is deprecated and will be removed after 2020-10-11.
Instructions for updating:
Simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
W1102 19:19:05.185284 140450597959424 deprecation.py:323] From /root/.local/lib/python3.6/site-packages/object_detection/model_lib_v2.py:355: set_learning_phase (from tensorflow.python.keras.backend) is deprecated and will be removed after 2020-10-11.
Instructions for updating:
Simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
```

**Comment by MeghnaNatraj** [comment]
@sammilei As this issue is related to a warning that we print in the console, it should ideally not cause issues when training a model. Please file a [New issue](https://github.com/tensorflow/tensorflow/issues/new/choose) with more details.
