### ISSUE TITLE
Autograph AssertionError on custom layer call

### ISSUE THREAD

**Issue by ruperty** [tensorflow/tensorflow#39598]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

The errors says, "Please report this to the TensorFlow team. When filing the bug..."

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes, custom layer
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
No
- TensorFlow installed from (source or binary):
Anaconda environment with pip install
- TensorFlow version (use command below):
v2.1.0-rc2-17-ge5bf8de410 2.1.0
- Python version:
Python 3.6.10 |Anaconda, Inc.| (default, Mar 23 2020, 17:58:33) [MSC v.1916 64 bit (AMD64)]
- Bazel version (if compiling from source):
N/a
- GCC/Compiler version (if compiling from source):
N/a
- CUDA/cuDNN version:
10.1
- GPU model and memory:
GeForce RTX 2080 Ti 32Gb

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)

Run from Anaconda

== check python ===================================================

== check os platform ===============================================

== are we in docker =============================================
No

== compiler =====================================================
./tf_env_collect.sh: line 102: c++: command not found

== check pips ===================================================

== check for virtualenv =========================================
False

== tensorflow import ============================================
Traceback (most recent call last):

  File "<string>", line 1, in <module>

ModuleNotFoundError: No module named 'tensorflow'

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tf_env_collect.sh: line 147: nvidia-smi: command not found

== cuda libs  ===================================================

== tensorflow installed from info ==================

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(3, 8, 2, 'final', 0)

== bazel version  ===============================================

== check python ===================================================
python version: 3.6.10

python branch: 

python build version: ('default', 'Mar 23 2020 17:58:33')

python compiler version: MSC v.1916 64 bit (AMD64)

python implementation: CPython

== check os platform ===============================================
os: Windows

os kernel version: 10.0.18362

os release version: 10

os platform: Windows-10-10.0.18362-SP0

linux distribution: ('', '', '')

linux os distribution: ('', '', '')

mac version: ('', ('', '', ''), '')

uname: uname_result(system='Windows', node='DESKTOP-5O07H5P', release='10', version='10.0.18362', machine='AMD64', processor='Intel64 Family 6 Model 158 Stepping 13, GenuineIntel')

architecture: ('64bit', 'WindowsPE')

machine: AMD64

== are we in docker =============================================
No

== compiler =====================================================
bash: c++: command not found

== check pips ===================================================
numpy                         1.18.1                                        

numpydoc                      0.9.2                                         

protobuf                      3.11.4                                        

tensorflow-docs               0.0.084618e76cde6edf23c2e71fd1d126c3d18ba53d5-

tensorflow-gpu                2.1.0                                         

tensorflow-gpu-estimator      2.1.0                                         

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.version.VERSION = 2.1.0

tf.version.GIT_VERSION = v2.1.0-rc2-17-ge5bf8de410

tf.version.COMPILER_VERSION = MSVC 192428314

2020-05-16 10:55:03.809733: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
bash: nvidia-smi: command not found

== cuda libs  ===================================================

== tensorflow installed from info ==================

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(3, 6, 10, 'final', 0)

== bazel version  ===============================================

You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

When building a model containing my custom layer I get this message: I don't get it on the first time the code is run.

Python 3.6.10 |Anaconda, Inc.| (default, Mar 23 2020, 17:58:33) [MSC v.1916 64 bit (AMD64)]
TensorFlow version: 2.1.0
v2.1.0-rc2-17-ge5bf8de410 2.1.0
Keras version: 2.2.4-tf
tf.Tensor([[150. 150. 150. 150. 150.]], shape=(1, 5), dtype=float32)
INFO:tensorflow:Converted call: <bound method Linear.call of <layers.Linear object at 0x00000299C8EE0BE0>>
    args: (<tf.Tensor 'Placeholder:0' shape=(1, 5) dtype=float32>,)
    kwargs: {}

INFO:tensorflow:Not whitelisted: <method-wrapper '__call__' of method object at 0x00000299AA71E088>: default rule
INFO:tensorflow:Not whitelisted: <class 'layers.Linear'>: default rule
INFO:tensorflow:Not whitelisted: <bound method Linear.call of <layers.Linear object at 0x00000299C8EE0BE0>>: default rule
INFO:tensorflow:Cache hit for entity <bound method Linear.call of <layers.Linear object at 0x00000299C8EE0BE0>> key <code object call at 0x00000299CF180780, file "C:\Users\ruper\Versioning\PCTSoftware\Libraries\python\tensorflow\pct\pctdl\layers.py", line 24> subkey (<tensorflow.python.autograph.core.converter.ConversionOptions object at 0x00000299CF196F28>, frozenset()): _ConvertedEntityFactoryInfo(tf__call in tmph641gc44)
INFO:tensorflow:Error transforming entity <bound method Linear.call of <layers.Linear object at 0x00000299C8EE0BE0>>
Traceback (most recent call last):
  File "C:\Users\ruper\.conda\envs\pct-tf\lib\site-packages\tensorflow_core\python\autograph\impl\api.py", line 526, in converted_call
    converted_f = conversion.convert(target_entity, program_ctx)
  File "C:\Users\ruper\.conda\envs\pct-tf\lib\site-packages\tensorflow_core\python\autograph\impl\conversion.py", line 328, in convert
    return _instantiate(entity, converted_entity_info, free_nonglobal_var_names)
  File "C:\Users\ruper\.conda\envs\pct-tf\lib\site-packages\tensorflow_core\python\autograph\impl\conversion.py", line 266, in _instantiate
    factory = converted_entity_info.get_factory()
  File "C:\Users\ruper\.conda\envs\pct-tf\lib\site-packages\tensorflow_core\python\autograph\impl\conversion.py", line 92, in get_factory
    assert self.module_name in sys.modules
AssertionError
WARNING:tensorflow:AutoGraph could not transform <bound method Linear.call of <layers.Linear object at 0x00000299C8EE0BE0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 

**Describe the expected behavior**

I don't want the error/warning message (not sure what it means).

**Standalone code to reproduce the issue**

[test-layer.txt](https://github.com/tensorflow/tensorflow/files/4638168/test-layer.txt)
[layers.txt](https://github.com/tensorflow/tensorflow/files/4638169/layers.txt)

I have added the test code. Change to .py extension.

Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@ruperty,
I did not observe the `WARNING:tensorflow:AutoGraph could not transform` warning on running the code with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/b3c2f0ec76039aebde67d10b788dc0d7/39598-2-1.ipynb) and [TF v2.2](https://colab.research.google.com/gist/amahendrakar/b773f46a9f7ae8ff83be435fc21d3be1/39598.ipynb). Please find the attached gist.

Please take a look at [this](https://github.com/tensorflow/tensorflow/issues/38691) similar issue and set [tf.autograph.set_verbosity](
https://www.tensorflow.org/api_docs/python/tf/autograph/set_verbosity#for_example) to a lower value to disable the logs. Thanks!

**Comment by ruperty** [comment]
Yes, I did set verbosity lower to get rid of it. I was just reporting it 
because the message said it was a bug.

I didn't see any attachment. What is a gist?

Regards,
Rupert

**Comment by amahendrakar** [comment]
@ruperty,
Thank you for reporting the bug, there is already a [PR submitted](https://github.com/tensorflow/tensorflow/issues/38947#issuecomment-620923249) for the fix.

I ran the code on my end and attached the links of the Python notebook (which are saved as GitHub gist). Here are the direct links for the notebook files
- TF v2.1 - https://colab.research.google.com/gist/amahendrakar/b3c2f0ec76039aebde67d10b788dc0d7/39598-2-1.ipynb

- TF v2.2 -
https://colab.research.google.com/gist/amahendrakar/b773f46a9f7ae8ff83be435fc21d3be1/39598.ipynb

Please take a look at the links and close the issue if resolved. Thanks!
