### ISSUE TITLE
undeclared identifier 'ABSL_FALLTHROUGH_INTENDED'

### ISSUE THREAD

**Issue by museum-future** [tensorflow/tensorflow#39590]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OSX 10.15.3
- source
- 2.2.0
- Python version:3.8.2
- Installed using virtualenv? pip? conda?: No
- Bazel version (if compiling from source): bazelisk --version -> bazel 2.0.0
- Clang10 and gcc10 + Apple gcc +Apple clang

> tf2.2/tensorflow/core/lib/io/BUILD:211:1: C++ compilation of rule '//tensorflow/core/lib/io:cache' failed (Exit 1)
> 
> tensorflow/core/lib/io/cache.cc:430:9: error: use of undeclared identifier 'ABSL_FALLTHROUGH_INTENDED'
>         ABSL_FALLTHROUGH_INTENDED;
>         ^
> tensorflow/core/lib/io/cache.cc:433:9: error: use of undeclared identifier 'ABSL_FALLTHROUGH_INTENDED'
>         ABSL_FALLTHROUGH_INTENDED;

bazelisk build --config=opt --config=macos --config=monolithic --config=v2 --config=mkl   //tensorflow/tools/pip_package:build_pip_package

**Comment by sxlllslgh** [comment]
I met the same issue with yours on Windows. Finally I found that I let the compiler (MSVC 2019) to compile with C++ 17 standard in configuration file. And the default setting is to use C++ 14 standard, it's OK.

**Comment by NeoZhangJianyu** [comment]
> I met the same issue with yours on Windows. Finally I found that I let the compiler (MSVC 2019) to compile with C++ 17 standard in configuration file. And the default setting is to use C++ 14 standard, it's OK.

@museum-future Could you try this suggestion and feedback?

**Comment by museum-future** [comment]
> > I met the same issue with yours on Windows. Finally I found that I let the compiler (MSVC 2019) to compile with C++ 17 standard in configuration file. And the default setting is to use C++ 14 standard, it's OK.
> 
> @museum-future Could you try this suggestion and feedback?

Sorry for late reply.

I tried with -std=c++17 and  -std=gnu++17
with clang version 10.0.0 

when building the options are overriden

`tensorflow-2.2.0/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14`

**Comment by NeoZhangJianyu** [comment]
@museum-future
OK, we got it.
There is still problem when disable MKL.

**Comment by NeoZhangJianyu** [comment]
@museum-future 

It's not officially support TF+MKL with OSX even though oneDNN supports. It could be that oneDNN is not compiled with openMP so oneDNN code is not threaded.

In the latest master and also TF2.4, there are some changes to use an opensource openMP, it has been tested on windows and Linux but not Mac. 

Could you try these branches?

**Comment by NeoZhangJianyu** [comment]
@museum-future 
Have you try with TF2.4?
If it's working, could you close this issue?

**Comment by NeoZhangJianyu** [comment]
@museum-future 

Could you feedback the suggestion?

Thank you!
