### ISSUE TITLE
tensorflow.keras deadlock when using model's predict() in parallel

### ISSUE THREAD

**Issue by leandrocouto** [tensorflow/tensorflow#39592]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Ubuntu 20.04
- Mobile device if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6.10
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

In the toy code below, I am trying to call `predict()` from a `tf.keras` model running in parallel. However, it is getting stuck because of a deadlock.

**Describe the expected behavior**

All processes should have returned the result of `predict()` without getting stuck.

**Standalone code to reproduce the issue**

 You can find a minimal reproducible code in the gist below:
https://gist.github.com/leandrocouto/a11534688dc568ea23f20171a5dc643f

**Other info / logs**

There are two functions (`make_keras_picklable()` and `_unpack()`) that are a hotfix in order to make a tf.keras pickable. Apparently, when running code in parallel, the objects you pass as parameters needs to be pickled. I am using  `concurrent.futures` for the parallel calls.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2.0 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/c5a3a1595bfd728ec2b36855be893c7f/untitled895.ipynb).Thanks!

**Comment by saikumarchalla** [comment]
issue still persists in TF 2.5 . Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/4a4a126de447a862406f27319e24df3c/untitled80.ipynb).Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
