### ISSUE TITLE
Cifar10 example bug (batch #5 not loading)

### ISSUE THREAD

**Issue by Pfaeff** [tensorflow/tensorflow#396]
In *tensorflow/models/image/cifar10/cifar10.py* it says:

    filenames = [os.path.join(FLAGS.data_dir, 'cifar-10-batches-bin',
                            'data_batch_%d.bin' % i)
               for i in xrange(1, 5)]

which will only load batches 1 to 4, while batch number 5 is ignored entirely. This would be correct imo:

    for i in xrange(1, 6)]

**Comment by a-dai** [comment]
Fixed in next push.
