### ISSUE TITLE
Tensorflow profiler returning the wrong total_float_ops numbers for Keras Model

### ISSUE THREAD

**Issue by nullbyte91** [tensorflow/tensorflow#39603]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:No
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.6
- Bazel version (if compiling from source):NA
- GCC/Compiler version (if compiling from source):NA
- CUDA/cuDNN version:NA
- GPU model and memory:NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I'm trying to calculate FLOPs, and MAC's for the Keras models. I'm using a Tensorflow profiler from tensorflow.compat.v1. I API. I've attached the code snippet to calculate the FLOPs by using the saved Keras model. The profiler returning an incremental total_float_ops values for the same model whenever I execute.
**Describe the expected behavior**
Since no changes in the saved model, the developer expects the same total_float_ops numbers. 
**Standalone code to reproduce the issue**
```python
import tensorflow.compat.v1 as tf
def get_flops(model_h5_path):
    session = tf.compat.v1.Session()
    graph = tf.compat.v1.get_default_graph()
        

    with graph.as_default():
        with session.as_default():
            model = tf.keras.models.load_model(model_h5_path)

            run_meta = tf.compat.v1.RunMetadata()
            opts = tf.compat.v1.profiler.ProfileOptionBuilder.float_operation()
        
            # We use the Keras session graph in the call to the profiler.
            flops = tf.compat.v1.profiler.profile(graph=graph,
                                                  run_meta=run_meta, cmd='op', options=opts)
            print(flops)
            return flops.total_float_ops

FLOPs = get_flops("model.h5")
```
```bash
For Example:
First Time:
name: "_TFProfRoot"
total_float_ops: 851781854

Second Time:
name: "_TFProfRoot"
total_float_ops: 929216568

Third Time:
name: "_TFProfRoot"
total_float_ops: 1006651282
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@nullbyte91 
I ran the code shared and face a different error, please find [gist here](https://colab.sandbox.google.com/gist/Saduf2019/dabcbc4e05fe45988ad390cf2fd86d3f/untitled183.ipynb)

**Comment by nullbyte91** [comment]
@Saduf2019 You need a Keras saved model to test the get_flops function. Please let me know if you need dummy models to test.

**Comment by Saduf2019** [comment]
@nullbyte91 
Yes please share all dependencies or if possible share a colab gist with the error faced for us to analyse
