### ISSUE TITLE
Equation not being rendered in docs page

### ISSUE THREAD

**Issue by marcospgp** [tensorflow/tensorflow#39608]
## URL(s) with the issue:

https://www.tensorflow.org/agents/tutorials/0_intro_rl

## Description of issue (what needs changing):

The equation after "The optimal Q-function obeys the following Bellman optimality equation:" is not rendering correctly. This is what I see on my screen:

```
$\begin{equation} Q^(s, a) = \mathbb{E}\left[ r + \gamma \max_{a'} Q^(s', a')\right] \end{equation}$
```

**Comment by dynamicwebpaige** [comment]
Reassigning to the TensorFlow Docs team ([`tensorflow/docs`](https://www.github.com/tensorflow/docs)). @lamberta, FYI.
