### ISSUE TITLE
Memory Usage of a model

### ISSUE THREAD

**Issue by Arktius** [tensorflow/tensorflow#39605]
I'd like to have a method which returns the needed memory for a model since the allocated VRAM does not reflect the actual usage.

**Comment by ravikyram** [comment]
@Arktius 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!

**Comment by Arktius** [comment]
- Microsoft Windows [Version 10.0.18362.418]
- Nvidia 2060 Super
- TF version 2.0.0
- Are you willing to contribute it (Yes/No): Don't know yet.

**Who will benefit with this feature?**
- Everyone who's interested in optimizing lots of models while logging needed memory. 
- Everyone who wants to shift an application to another machine with a different hardware setup.

The problem is that the following commands do not free the allocated memory.
```
tf.compat.v1.reset_default_graph()
tf.keras.backend.clear_session()
gc.collect()
```
One can use 
```
gpu = tf.config.experimental.list_physical_devices('GPU') 
tf.config.experimental.set_memory_growth(gpu[0], False)
```
to give as much memory as the GPU needs. Nevertheless, the allocated memory is correctly displayed only for a single model. After training several models, the allocated memory that is displayed by nvidia-smi is the one of the largest model. 

How can I submit a PR(pull request)?

**Comment by ymodak** [comment]
For submitting a pull request see https://www.tensorflow.org/community/contribute/code

**Comment by mohantym** [comment]
Hi @Arktius ! Does [get_memory_usage api ](https://www.tensorflow.org/api_docs/python/tf/config/experimental/get_memory_usage)resolve this api? You can add this before model training and get memory usage. Thanks!
