### ISSUE TITLE
REDUCE_MAX operator support for int8 tflite

### ISSUE THREAD

**Issue by kmonachopoulos** [tensorflow/tensorflow#39601]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Catalina 10.15.4
- TensorFlow installed from (source or binary): tf-nightly (2.2.0-dev20200405)

**Any other info / logs**

I am using tf-nightly that integrates the new converter and trying to export a fully quantized int8 model using post-training quantization with calibration. 

The output model holds int8 operators including int8 input and output nodes. However, there is a specific node **REDUCE_MAX** that seems not to have support in tflite, therefore, there are quantization and dequantization operations around it, ending-up having a "hybrid" model with reference fp32 implementations as is shown below.

<img width="441" alt="Screenshot 2020-05-16 at 14 34 26" src="https://user-images.githubusercontent.com/3832904/82121078-5c66b900-9782-11ea-83a5-8f3d33dfc66a.png">

Are there any plans for this OP to be supported in tflite and in TFLu in the future? Is it possible that this operator is already supported but the properties of the operator won't allow full quantization? 

Thanks!

**Comment by amahendrakar** [comment]
@kmonachopoulos,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by kmonachopoulos** [comment]
Do you want me to provide the whole source code that I used to train the model, the code to export it, and the code for inference? I think that the description of this issue is pretty straight forward above..

**Comment by amahendrakar** [comment]
@kmonachopoulos,
Could you please provide the code to generate the model and to convert it, so that we can take a look the nodes in it. Thanks!

**Comment by kmonachopoulos** [comment]
The code is integrated into a larger framework called DeePavlov that is commonly used for NLP tasks. I can link the repo but I don't think that this is sufficient. Actually, I think that the issue raised here is pretty straight forward ->  **REDUCE_MAX** is not supported in int8...

**Comment by jdduke** [comment]
I believe we have a kernel that supports this, so we may need to look into the conversion. @suharshs can assist.

**Comment by akarmi** [comment]
> 
> 
> I believe we have a kernel that supports this, so we may need to look into the conversion. @suharshs can assist.

Yes, it appears this op is not listed in [GetOperatorProperty](https://github.com/tensorflow/tensorflow/blob/079520f252ce6ba7788b81904a40fb98895b288d/tensorflow/lite/tools/optimize/operator_property.cc#L67).

**Comment by kevinyamauchi** [comment]
I would also like use `reduce_max` in an 8 bit quantized model. Is it planned to be added in the near future?

@kmonachopoulos were you able to find a workaround?

**Comment by kevinyamauchi** [comment]
Ah bummer. Thanks for letting me know, @kmonachopoulos ! I did see this PR (https://github.com/tensorflow/tensorflow/pull/39946) adding `reduce_max` for TFLite micro. Maybe it can be ported back to TFLite?
