### ISSUE TITLE
native crash when using GpuDelegate on Float16 nn from java android.

### ISSUE THREAD

**Issue by noamfreeman** [tensorflow/tensorflow#39612]
when configuring:
```kotlin
Interpreter.Options().apply {
    val gpuDelegate = GpuDelegate()
    addDelegate(gpuDelegate)
}
```
the code crashes when the interpreter is built, even before running it, with a seg-fault from dereferencing a 0 pointer. as usual with seg-faults, no other information is given, like line-number or message.
  this error only happens when the nn is of type Float16, but not with Float32 (which, of coarse, look the exact same from the java side)
but adding eiter `.setAllowFp16PrecisionForFp32(true)` or `.setAllowFp16PrecisionForFp32(false)`
removes the crash.

i think the reason of the crash is that `Interperter.Options.allowFp16PrecisionForFp32` is declared `Boolean`, thus allowing `null` as a value, which crashes in native without a clear message.

as i see it, there are 3 solutions:
* declaring it `boolean` and initializing with `true` or `false`.
* checking on the java side if the value is null, in case the configuration needs it, and throwing an appropriate error with a clear message. ( i prefer this one)
* checkint / trying in native

**Comment by sushreebarsa** [comment]
@noamfreeman Could you please have a look at this [link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/java/src/main/java/org/tensorflow/lite/NativeInterpreterWrapper.java#L81-L84) ,probably it is a fix for this issue.Please let us know if it helps?Thank you!

**Comment by noamfreeman** [comment]
@sushreebarsa thanks. it does.
shame on me not specifying the exact version i used (i see the null check is pretty old).
thanks for checking into it.
