### ISSUE TITLE
Cannot convert model into tflite file format

### ISSUE THREAD

**Issue by vedrocks15** [tensorflow/tensorflow#39614]
System Information :
- Tensorflow Object detection api : using pipeline.config file for ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03. 
- OS Platform and Distribution : Linux Ubuntu 16.04
- TensorFlow installed from source
- TensorFlow version : 1.14.0
- Python version: 3
- CUDA/cuDNN version: CUDA Version 10.0.130
- GPU model and memory: Tesla M60 

Problem :
After making use of 
python3 model_main.py --alsologtostderr --model_dir=training/ --pipeline_config_path=training/pipeline.config

I trained the model for 94k steps.
The model was converted to frozen graph format using export_tflite_ssd_graph.py. 
The model was trained using quantization aware training by the following lines in the pipeline.config:

graph_rewriter 
{ 
 quantization 
 { 
  delay: 48000 
  weight_bits: 8 
  activation_bits: 8
  }
}

Issue : 
Using tflite convert i made use of the frozen graph from the previous step to convert the model into QUANTIZED_UINT8 format. I use the following command :

tflite_convert   --output_file='../test3.tflite' --graph_def_file='.../tflite_graph.pb' --inference_type=QUANTIZED_UINT8
 --input_arrays='normalized_input_image_tensor' 
--output_arrays='TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3' 
--mean_values=128 
--std_dev_values=128 
--input_shapes=1,300,300,3
 --change_concat_input_ranges=false 
--allow_nudging_weights_to_use_fast_gemm_kernel=true 
--allow_custom_ops

The model asks for default max & min ranges.

After giving the ranges the following error pops up : 
F ./tensorflow/lite/toco/toco_tooling.h:38] Check failed: s.ok() Unimplemented: this graph contains an operator of type Cast for which the quantized form is not yet implemented. Sorry, and patches welcome (that's a relatively fun patch to write, mostly providing the actual quantized arithmetic code for this op).
Fatal Python error: Aborted

Any help would be quite beneficial.

**Comment by daverim** [comment]
Hi @vedrocks15, 

I wonder if you are using a mismatching version of the object detection api: you should use the one matching your tensorflow version (https://github.com/tensorflow/models/releases/tag/v1.11)

**Comment by vedrocks15** [comment]
Yup this worked.
