### ISSUE TITLE
No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by munavircp** [tensorflow/tensorflow#39616]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: jupyter  notebooks
- TensorFlow installed from (source or binary): Github
- TensorFlow version: 2.1.0
- Python version:3.6
- Installed using virtualenv? pip? conda?:conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:Intel HD

**Describe the problem**

 11 sys.path.append("C:/Users/xx/.conda/envs/tensorflow_env/Lib/site-packages/tensorflow/models")
     12 import cv2
---> 13 from nets import vgg
     14 from preprocessing import vgg_preprocessing
     15 from mlxtend.preprocessing import shuffle_arrays_unison

~\.conda\envs\tensorflow_env\lib\site-packages\slim-0.1-py3.7.egg\nets\vgg.py in <module>
     43 
     44 import tensorflow as tf
---> 45 # from tensorflow.contrib import slim as contrib_slim
     46 
     47 slim = contrib_slim

ModuleNotFoundError: No module named 'tensorflow.contrib'

**Provide the exact sequence of commands / steps that you executed before running into the problem**

import os 
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from skimage.transform import resize
from tqdm import tqdm
from sklearn.model_selection import train_test_split
%matplotlib inline
sys.path.append("C:/Users/Firoz/.conda/envs/tensorflow_env/Lib/site-packages/tensorflow/models")
import cv2
from nets import vgg
from preprocessing import vgg_preprocessing
from mlxtend.preprocessing import shuffle_arrays_unison
checkpoints_dir = 'C:/Users/Firoz/checkpoints'
import warnings
warnings.filterwarnings("ignore", message="numpy.dtype size changed")

I have gone through these steps
1. https://github.com/tensorflow/tensorflow/issues/30794
2. https://github.com/tensorflow/tensorflow/issues/31350

 without downgrading my tensorflow,  so Assisstance ??

**Comment by mihaimaruseac** [comment]
Contrib does not exist in 2.0 or later. If you need `contrib` you have to use 1.15, although we recommend upgrading code to the contrib alternatives (since they are being actively maintained by an owner, unlike `contrib` which doesn't have an owner to fix issues)

**Comment by testote** [comment]
When I do "sudo -H pip2 install tensorflow==1.15" I get
ERROR: Package 'mock' requires a different Python: 2.7.18 not in '>=3.6'

When I do "sudo -H pip3 install tensorflow==1.15" I get
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0).

The fact that  tensorflow.contrib was removed from python3 tensorflow is causing quite pain. Any help?

**Comment by mihaimaruseac** [comment]
Before TF 2.2 you need python 3.5, 3.6 or 3.7. Not Python 2 or python 3.8

**Comment by testote** [comment]
trizen -S python37 --noconfirm
sudo -H python3.7 -m pip install tensorflow==1.15.3
sudo -H python3.7 -m pip install tf_slim
sed -i "s/from tensorflow.contrib import slim/import tf_slim as slim/g" file.py
sudo -H python3.7 -m pip install opencv-python

**Comment by aliefaditya** [comment]
> Contrib does not exist in 2.0 or later. If you need `contrib` you have to use 1.15, although we recommend upgrading code to the contrib alternatives (since they are being actively maintained by an owner, unlike `contrib` which doesn't have an owner to fix issues)

Thank you, it was really helpful @mihaimaruseac
