### ISSUE TITLE
tf.keras.Model docs missing get_weights method and metrics property

### ISSUE THREAD

**Issue by ThewBear** [tensorflow/tensorflow#39615]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/keras/Model

## Description of issue (what needs changing):

The docs is missing `get_weights`, `set_weights` method and `metrics` property.

`get_weights` method and `metrics` property are defined in the src. But not in the generated docs.

https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/keras/engine/training.py#L190-L197

https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/keras/engine/training.py#L361-L410

`set_weights` method is mentioned in [keras docs](https://keras.io/api/models/model_saving_apis/#setweights-method).

**Comment by ymodak** [comment]
The `get_weights` and `set_weights` property belongs to [`tf.keras.layers.Layer`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer#get_weights) 
So when you apply them on to whole model it will get/set weights for each individual layer of the model.

**Comment by ThewBear** [comment]
But why generated docs doesn't have `set_weights` and `metrics`? Is it excluded somewhere, or a bug in docs generator.

**Comment by nikitamaia** [comment]
Closing issue since get_weights and set_weights can be found at tf.keras.layers.Layers as mentioned earlier.
