### ISSUE TITLE
Is it possible to have a keras API for PhasedLSTM similar to CuDNNLSTM?

### ISSUE THREAD

**Issue by abinashsinha330** [tensorflow/tensorflow#39613]
Is it possible to have a keras API for PhasedLSTM similar to CuDNNLSTM?

**Comment by jvishnuvardhan** [comment]
@abinashsinha330 Can you please add more details to know whether you are looking for a feature or a support kind of questions that are good to be on Stackoverflow? thanks

**Comment by abinashsinha330** [comment]
Correct me if I am wrong, I think it would be counted as a new feature since I am requesting an API similar to CuDNNLSTM that we have in keras.
Basically, I am asking if we can expect an APi called CuDNNPhasedLSTM sometime in future?

**Comment by qlzh727** [comment]
I think PhasedLSTM or its Cudnn implementation are widely used like normal LSTM and GRU. This means we won't contain them in the core Keras API. 

Alternatively you can propose this request to tensorflow/addons repository, which is the place for hosting additional APIs that is not in Keras or TF API.
