### ISSUE TITLE
Successive STFT transforms increases signal amplitude

### ISSUE THREAD

**Issue by SushiEleonore** [tensorflow/tensorflow#39629]
Hi,
I successively applied tensorflow's STFT and iSTFT transforms several time on a signal, and the amplitude of the signal grows with each transform. I tried librosa's and scipy's STFT and this doesn't happen. Here is the exact code:

```
import librosa
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

length=88
fft_size = (length-1)*2   # 174
hop_size = int(fft_size/4)# 43

def get_STFT_librosa(sig):
    spec_librosa = librosa.core.stft(np.array(sig), n_fft=fft_size, hop_length=hop_size, win_length=fft_size)
    return spec_librosa

def get_iSTFT_librosa(spec):
    inverse = librosa.core.istft(spec, hop_length=hop_size, win_length=fft_size)
    return inverse
    
def get_STFT_tf(sig):
    STFT = tf.signal.stft(np.array(sig), frame_length=fft_size, frame_step=hop_size, fft_length=fft_size)
    STFT = STFT.numpy()
    spec_tf = STFT.T
    return spec_tf

def get_iSTFT_tf(spec):
    STFT = tf.convert_to_tensor(spec.T)
    sig = tf.signal.inverse_stft(STFT, frame_length=fft_size, frame_step=hop_size, fft_length=fft_size)
    return sig.numpy()

def librosa_tf_comparison():
    time = np.arange(0, 1000, 0.1);
    sig = np.sin(time)

    #STFT level 1
    tf_STFT = get_STFT_tf(sig)
    lib_STFT = get_STFT_librosa(sig)

    tf_iSTFT = get_iSTFT_tf(tf_STFT)
    lib_iSTFT = get_iSTFT_librosa(lib_STFT)

    #STFT level 2
    tf_STFT2 = get_STFT_tf(tf_iSTFT)
    lib_STFT2 = get_STFT_librosa(lib_iSTFT)

    tf_iSTFT2 = get_iSTFT_tf(tf_STFT2)
    lib_iSTFT2 = get_iSTFT_librosa(lib_STFT2)


    #STFT level 3
    tf_STFT3 = get_STFT_tf(tf_iSTFT2)
    lib_STFT3 = get_STFT_librosa(lib_iSTFT2)

    tf_iSTFT3 = get_iSTFT_tf(tf_STFT3)
    lib_iSTFT3 = get_iSTFT_librosa(lib_STFT3)

    plt.plot(sig[:800])
    plt.plot(tf_iSTFT[:800])
    plt.plot(tf_iSTFT2[:800])
    plt.plot(tf_iSTFT3[:800])
    plt.show()

    plt.plot(sig[:800])
    plt.plot(lib_iSTFT[:800])
    plt.plot(lib_iSTFT2[:800])
    plt.plot(lib_iSTFT3[:800])
    plt.show()

librosa_tf_comparison()

```
Here is what the code gives:
![librosa](https://user-images.githubusercontent.com/10775105/82160064-e69e4280-9892-11ea-9638-eb4445f45539.png)
This is what a simple sine looks like after three consecutive STFT/iSTFT with librosa (there is only one curve because they are merged, as should be)
![tf](https://user-images.githubusercontent.com/10775105/82160062-e1d98e80-9892-11ea-8a3b-5fa285c687cb.png)
This is what the same curve looks like after three consecutive STFT/iSTFT with tensorflow. The original sine wave is in blue, I get the yellow curve after one STFT/iSTFT, then green, then red.

The factor between one iSTFT wave and the previous one seems to be always the same no matter the shape of the wave (for this set of parameters), about 0.659.

I checked and the NOLA constraint is met with these parameters. Is this normal behaviour?

**Comment by Saduf2019** [comment]
@ SushiEleonore  
Can you please let us know which version of tensor flow are you facing this issue

**Comment by SushiEleonore** [comment]
I have version 2.1.0

**Comment by Saduf2019** [comment]
I am able to replicate the issue faced, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/fe82e574db3f1839b1cd6444d6bd1b19/untitled188.ipynb)

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue in TF 2.5. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/5a9f9c59f981e52f4ec722dbc7cbf6e1/untitled84.ipynb).Thanks!

**Comment by cantonios** [comment]
The signal is being scaled because it doesn't account for
1. the window function used (Hanning window by default)
2. the number of frame overlaps at a given point

We can re-scale the signal via
```
scale_factor = (frame_length / frame_step) * (3 / 8)
rescaled_tf_iSTFT = tf_iSTFT / scale_factor
```
3/8 is the energy scale factor introduced by the hanning window, and `frame_length/frame_step` is the number of values summed at each point in the reconstruction.
