### ISSUE TITLE
TFRecordDataset mapped with crop is heavily impacted by image sizes

### ISSUE THREAD

**Issue by feature-engineer** [tensorflow/tensorflow#39623]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10, Ubuntu 18.04, Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.2
- Python version: 3.7.7, 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: Colab's GPU, V100 32GB, CPU

**Describe the current behavior**
When loading a dataset with large images, and mapping it to random crop, iterating over the dataset is significantly slower, even for a small dataset of 10 images in repeat. In my example I compare a dataset of 10 240x240x3 images, to one with ten 2400x2400x3 images, both of them randomly cropped to 120x120x3 - the latter was about 100 times slower to operate on (reduce_sum, in my toy example).

**Describe the expected behavior**
I would expect there to be no effect from the size of the images in the dataset if they are being cropped right after being loaded once the dataset resides in memory. 

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1uGeLJJp2gPvgC37WxbP_yANAXB8D83ld#scrollTo=DddLV9gxm5eL

**Comment by Saduf2019** [comment]
@feature-engineer 
I tried accessing the colab shared, i do not have access permission to do so.

**Comment by feature-engineer** [comment]
Sorry, try this:
https://colab.research.google.com/drive/1uGeLJJp2gPvgC37WxbP_yANAXB8D83ld?usp=sharing

**Comment by Saduf2019** [comment]
@feature-engineer 
Can you please refer to this issue #38947 and let us know if it helps.

**Comment by feature-engineer** [comment]
No, the warnings you see are the result of running the code under timeit, it complains it can't see the source code in that environment. 

To alleviate the worries that this is the reason for this performance issue, I have added the same code outside of timeit, just using time.time to test one run of this.

The warnings regarding autograph are gone, but the significant run time difference is still there.

**Comment by jsimsa** [comment]
`repeat` re-executes the input pipeline, if you would like to cache the results of previous repeat iterations, you should use the `cache` transformation.

**Comment by feature-engineer** [comment]
`cache` indeed makes this whole run much faster, although there is still a significant run time difference between the TFRecord with 240x240 and the one with 2400x2400. 

I have updated my notebook with cache and re-ran it, you can check it out.

**Comment by jsimsa** [comment]
You need to run one epoch worth of data to populate the cache before you start timing things.

Get rid of the trailing `repeat()` and do:

```
# Warm up caches
for elem in data_from_small:
  pass
for elem in data_from_big:
  pass

start = time.time()
tf.reduce_sum([x for x in data_from_small.repeat().take(1000)])
print(time.time() - start)

start = time.time()
tf.reduce_sum([x for x in data_from_big.repeat().take(1000)])
print(time.time() - start)
```

I would expect there to be no difference in runtime at that point.

**Comment by feature-engineer** [comment]
That clears it up, thanks!
