### ISSUE TITLE
Repost of keras-team/keras #13118.

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#39627]
#### System information

* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
* TensorFlow version: tf-nightly (2.2)

#### Describe the current behavior
Loading a model once and then repeatedly calling `model.predict(...)` results in continually increasing memory usage.

#### Describe the expected behavior
Calling `model.predict(...)` should not result in any permanent increase in memory usage.

#### Code to reproduce the issue

```python
import tensorflow as tf
import numpy as np

model = tf.keras.applications.mobilenet_v2.MobileNetV2()
X = np.random.rand(1, 224, 224, 3)

while True:
    # Leaks:
    y = model.predict(X)[0]
    
    # Does not leak:
    # y = [0]
```

**Comment by jvishnuvardhan** [comment]
I ran the code for 25,000 iterations and don't see any significant increase in memory usage. [Here](https://colab.research.google.com/gist/jvishnuvardhan/d8db5a8099633cfc6ba73b27df85f13c/untitled191.ipynb) is the gist for our reference. Thanks!

**Comment by sushreebarsa** [comment]
@dynamicwebpaige Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!
