### ISSUE TITLE
TensorFlow utilization for traditional HPC scientific application written in FORTRAN for distributed computing

### ISSUE THREAD

**Issue by akshaymanu007** [tensorflow/tensorflow#39622]
Hi All,

I want to discuss and know the feasibility of using tensor flow for HPC scientific application written in FORTRAN and C using MPI for data distribution in distributed computing environment.

Few  research and feasibility study I did by writing small example of vector dot product in tensor flow. it is fairly very convenient  to write this code using python for tensor flow compared to writing a code using MPI and FORTRAN in which all the data distribution has been done programmer and relatively complex code.

Advantages:
1. No data distribution or copying data to GPU is required in Tensor flow which is underlying managed by tensor flow.
2. writing python code for array declaration or random variable initialization is very convenient.
3. Optimized mathematical operations written in tensor flow that can be directly used.

I am sure if used proper computational and bandwidth load in code we can achieve good performance also.

My Question is How feasible it is to port or develop HPC scientific applications in Tensor flow  and what are the challenges which cannot be handled by tensor flow?
Can we suggest clients to port there code in tensor flow for such advantages ?

**Comment by mihaimaruseac** [comment]
This is not a suitable medium for this question. Please only file here bug reports and feature requests
