### ISSUE TITLE
Unable to install older version of tensorflow in Python3.8.2

### ISSUE THREAD

**Issue by in2dblue** [tensorflow/tensorflow#39621]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version: Installed 2.2 but want 1.x
- Python version: 3.8.2
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I am able to install newer version of TensorFlow, i.e, 2.2. However, I need an older version of TensorFlow (1.x) to run existing code (otherwise I have to do a lot of changes as it's big repository)

CMD: sudo pip3 install tensorflow-gpu==1.15

ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.15 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0)
ERROR: No matching distribution found for tensorflow-gpu==1.15

**Comment by mihaimaruseac** [comment]
Only TF 2.2 supports python 3.8.

For all other versions of TF you have to use Python 3.5, 3.6 or 3.7
