### ISSUE TITLE
strip_unused on TensorFlow 0.10.0rc0 outputs ImportError: No module named tools

### ISSUE THREAD

**Issue by jeffxtang** [tensorflow/tensorflow#3962]
### Environment info

Operating System: Mac OS X El Capitan

Installed version of CUDA and cuDNN: N/A

Installed from binary pip package, TensorFlow version is 0.10.0rc0.

Python 2.7.11
### Steps to reproduce
1. `git clone https://github.com/tensorflow/tensorflow.git`
2. `cd tensorflow`
3. `bazel build tensorflow/python/tools:strip_unused`
4. I got the same error as in step 3 (shown in Logs below) when running the full command with the Inception V3 or V1 model. This is with the V3 model: 

`bazel-bin/tensorflow/python/tools/strip_unused --input_graph=/tmp/tensorflow_inception_graph_v3.pb --output_graph=/tmp/stripped_graph.pb --input_node_names=Mul --output_node_names=softmax --input_binary=true` 
### What have you tried?
1. I tried the same procedure previously on TensorFlow 0.8.0 on a different Mac (also running OS X El Capitan), and the above commands work perfectly: the `strip_unused` itself without any parameters outputs `Input graph file '' does not exist!` and the full command outputs the stripped data model.
2. I took a look at the `strip_unused_lib.py` file, unable to be imported when running `strip_unused`, on github and saw it's created first on Aug. 7:
   https://github.com/tensorflow/tensorflow/commits/master/tensorflow/python/tools/strip_unused_lib.py
3. I also looked at a similar issue: https://github.com/tensorflow/tensorflow/issues/3881 but it doesn't solve my problem.
4. I tried to add . to PYTHONPATH before running `bazel-bin/tensorflow/python/tools/strip_unused` and still got the same error. 
5. I did a fresh new install of TensorFlow 0.10.0rc0 on another Mac OS X El Capitan, and it's still the same.
### Logs or other output that would be helpful

```
Traceback (most recent call last):
  File "/Users/zero2one/tensorflow-src/latest/tensorflow/bazel-bin/tensorflow/python/tools/strip_unused.runfiles/tensorflow/python/tools/strip_unused.py", line 46, in <module>
    from tensorflow.python.tools import strip_unused_lib
ImportError: No module named tools
```

**Comment by gunan** [comment]
With 2 new releases after 0.10, this issue is now obsolete.
Sorry for the lack of attention to the issue.
I am closing this now.

Please open a new issue if you run into the same problem in our latest release.
