### ISSUE TITLE
Error with my Customized layers: bound method could not be transformed, Bad argument number for Name: 3, expecting 4

### ISSUE THREAD

**Issue by bzhong2** [tensorflow/tensorflow#39634]
**System information**

- OS Platform and Distribution: Linux Ubuntu 16.04:
- TensorFlow version : 1:14
- Python version: 3.7

**Standalone code to reproduce the issue**
I would like to customize a Dropout layer in which I can cache and reset the dropout mask manually. The code is as below:

```
class DropoutControl(Layer):

    def __init__(self, rate, seed=None, **kwargs):
        super(DropoutControl, self).__init__(**kwargs)
        self.rate = rate
        self.seed = seed
        self.cache_dropout_mask = None

    def reset_dropout(self):
        rate = ops.convert_to_tensor(
              self.rate, dtype=self.input_dtype, name="rate")
        random_tensor = random_ops.random_uniform(
            shape=self.shape, seed=self.seed, dtype=self.input_dtype)
        keep_prob = 1 - rate
        scale = 1 / keep_prob
        keep_mask = random_tensor >= rate
        self.cache_dropout_mask  = scale * math_ops.cast(keep_mask, self.input_dtype)

    def get_dropout_mask(self):
        return self.cache_dropout_mask 

    def call(self, inputs, training):
        if self.cache_dropout_mask is None:
            self.shape = array_ops.shape(inputs)
            self.input_dtype = inputs.dtype
            self.reset_dropout()

        def dropped_inputs():
          return inputs * self.cache_dropout_mask

        output = tf_utils.smart_cond(training,
                                     dropped_inputs,
                                     lambda: array_ops.identity(inputs))
        return output

    def compute_output_shape(self, input_shape):
        return input_shape

    def get_config(self):
        config = {
            'rate': self.rate,
            'seed': self.seed
        }
        base_config = super(DropoutControl, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))
```
**Describe the current behavior**
When I use this layer, the system gave me the following warning. What is this problem? Is it an issue that I have to fix? 

> WARNING:tensorflow:Entity <bound method DropoutControl.call of <model_utils.DropoutControl object at 0x7ffaa71b2650>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DropoutControl.call of <model_utils.DropoutControl object at 0x7ffaa71b2650>>: AssertionError: Bad argument number for Name: 3, expecting 4

Thanks ahead!

**Comment by amahendrakar** [comment]
@bzhong2,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by amahendrakar** [comment]
Also, please upgrade your TensorFlow to v1.15 or v2.2 and let us know if you are facing the same issue. Thanks!

**Comment by bzhong2** [comment]
Yes, after upgrading the TensorFlow version to 1.15, the problem was solved. Thanks a lot!
