### ISSUE TITLE
Debug keras code on Graph mode.

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/tensorflow#39636]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.15.1-2.2.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Sometimes I have to work on Graph mode(I can't use eager execution) and I can't debug Keras code with PDB since all code are converted by the autograph.
Could you disable the autograph on Graph mode?
**Will this change the current api? How?**
No
**Who will benefit with this feature?**
Developers
**Any Other info.**

**Comment by jvishnuvardhan** [comment]
@fsx950223 Is there any actionable item like raising PR? 

Please note that Keras development moved to another repository to focus entirely on only keras. Could you please repost this feature on [keras-team/keras repo](https://github.com/keras-team/keras/issues). Thanks!
