### ISSUE TITLE
saved_model README.md uses deprecated code

### ISSUE THREAD

**Issue by edurenye** [tensorflow/tensorflow#39638]
## URL(s) with the issue:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/README.md

## Description of issue (what needs changing):

That documentation uses deprecated code like 'tf.Session()'

### Submit a pull request?

No, because I don't really know how it should be used now.

**Comment by ymodak** [comment]
The `SavedModelBuilder` function is only available through v1 compatibility.
So you should be using [`tf.compat.v1.saved_model.Builder`](https://www.tensorflow.org/api_docs/python/tf/compat/v1/saved_model/Builder#top_of_page) function when using TF 2.X version.

**Comment by edurenye** [comment]
The documentation still needs to be fixed

**Comment by ymodak** [comment]
The saved_model md file is updated with commit [819eb34](https://github.com/tensorflow/tensorflow/commit/819eb34070c856a7f2881f5d14183dfa5c5c2375). Thanks!
