### ISSUE TITLE
tensorflow-io import error caused by "com_google_absl"

### ISSUE THREAD

**Issue by CuiYifeng** [tensorflow/tensorflow#39632]
**System information**
- Many Linux
- TensorFlow installed from source (master branch) and binary
- TensorFlow version: latest tf-nightly
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): GCC 8.4.0

**Describe the problem**

A NotImplementedError 
"undefined symbol: _ZNK10tensorflow10FileSystem8BasenameEN4absl11string_viewE"
occurs when importing tensorflow-io 0.13.0 or a series of tensorflow-io-nightly. The root cause is related with commit 6c7e338ae7f0b0f2e224319de7e2165141c148fb. Do you have any plan to fix this error or to replace the abseil-cpp? Or, do you have any build method to bypass this error?

**Comment by ravikyram** [comment]
@CuiYifeng 
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by CuiYifeng** [comment]
Platform: CentOS 7 (Linux version 3.10.0-957.el7.x86_64)
TensorFlow version: 2.3.0.dev20200513 (actually including TF built from master branch within the last month at least)
TensorFlow-io version: 0.13.0.dev20200515155704

How to reproduce:
`python`
`import tensorflow_io as tfio`

Then we can see error log as the following:
NotImplementedError: unable to open file: libtensorflow_io.so, from paths: ['path/to/site-packages/tensorflow_io/core/python/ops/libtensorflow_io.so']
caused by: ['path/to/site-packages/tensorflow_io/core/python/ops/libtensorflow_io.so: undefined symbol: _ZNK10tensorflow10FileSystem8BasenameEN4absl11string_viewE']

Thanks!

**Comment by byronyi** [comment]
Another issue caused by commit 6c7e338ae7f0b0f2e224319de7e2165141c148fb:


```
FAIL: //tensorflow/python/kernel_tests:substr_op_test (see /home/byronyi/.cache/bazel/_bazel_tiger/af81e00f6f55d49334af721d67cec08e/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/kernel_tests/substr_op_test/test.log)

FAILED: //tensorflow/python/kernel_tests:substr_op_test (Summary)
      /home/byronyi/.cache/bazel/_bazel_tiger/af81e00f6f55d49334af721d67cec08e/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/kernel_tests/substr_op_test/test.log
      /home/byronyi/.cache/bazel/_bazel_tiger/af81e00f6f55d49334af721d67cec08e/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/kernel_tests/substr_op_test/test_attempts/attempt_1.log
      /home/byronyi/.cache/bazel/_bazel_tiger/af81e00f6f55d49334af721d67cec08e/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/kernel_tests/substr_op_test/test_attempts/attempt_2.log
INFO: From Testing //tensorflow/python/kernel_tests:substr_op_test:
==================== Test output for //tensorflow/python/kernel_tests:substr_op_test:
Running tests under Python 3.5.9: /usr/local/bin/python3.5
[ RUN      ] SubstrOpTest.testBadBroadcast(<class 'numpy.int32'>, 'BYTE')
INFO:tensorflow:time(__main__.SubstrOpTest.testBadBroadcast(<class 'numpy.int32'>, 'BYTE')): 0.02s
I0521 18:41:29.769983 140606904841984 test_util.py:1970] time(__main__.SubstrOpTest.testBadBroadcast(<class 'numpy.int32'>, 'BYTE')): 0.02s
[       OK ] SubstrOpTest.testBadBroadcast(<class 'numpy.int32'>, 'BYTE')
[ RUN      ] SubstrOpTest.testBadBroadcast(<class 'numpy.int64'>, 'BYTE')
INFO:tensorflow:time(__main__.SubstrOpTest.testBadBroadcast(<class 'numpy.int64'>, 'BYTE')): 0.0s
I0521 18:41:29.771886 140606904841984 test_util.py:1970] time(__main__.SubstrOpTest.testBadBroadcast(<class 'numpy.int64'>, 'BYTE')): 0.0s
[       OK ] SubstrOpTest.testBadBroadcast(<class 'numpy.int64'>, 'BYTE')
[ RUN      ] SubstrOpTest.testBadBroadcast(<class 'numpy.int32'>, 'UTF8_CHAR')
INFO:tensorflow:time(__main__.SubstrOpTest.testBadBroadcast(<class 'numpy.int32'>, 'UTF8_CHAR')): 0.0s
I0521 18:41:29.773532 140606904841984 test_util.py:1970] time(__main__.SubstrOpTest.testBadBroadcast(<class 'numpy.int32'>, 'UTF8_CHAR')): 0.0s
[       OK ] SubstrOpTest.testBadBroadcast(<class 'numpy.int32'>, 'UTF8_CHAR')
[ RUN      ] SubstrOpTest.testBadBroadcast(<class 'numpy.int64'>, 'UTF8_CHAR')
INFO:tensorflow:time(__main__.SubstrOpTest.testBadBroadcast(<class 'numpy.int64'>, 'UTF8_CHAR')): 0.0s
I0521 18:41:29.775230 140606904841984 test_util.py:1970] time(__main__.SubstrOpTest.testBadBroadcast(<class 'numpy.int64'>, 'UTF8_CHAR')): 0.0s
[       OK ] SubstrOpTest.testBadBroadcast(<class 'numpy.int64'>, 'UTF8_CHAR')
[ RUN      ] SubstrOpTest.testBroadcast(<class 'numpy.int32'>, 'BYTE')
2020-05-21 18:41:29.775809: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance-critical operations:  AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-05-21 18:41:29.806852: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2400000000 Hz
2020-05-21 18:41:29.812239: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x40c7660 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-21 18:41:29.812276: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
INFO:tensorflow:time(__main__.SubstrOpTest.testBroadcast(<class 'numpy.int32'>, 'BYTE')): 0.05s
I0521 18:41:29.820772 140606904841984 test_util.py:1970] time(__main__.SubstrOpTest.testBroadcast(<class 'numpy.int32'>, 'BYTE')): 0.05s
[       OK ] SubstrOpTest.testBroadcast(<class 'numpy.int32'>, 'BYTE')
[ RUN      ] SubstrOpTest.testBroadcast(<class 'numpy.int64'>, 'BYTE')
INFO:tensorflow:time(__main__.SubstrOpTest.testBroadcast(<class 'numpy.int64'>, 'BYTE')): 0.0s
I0521 18:41:29.822387 140606904841984 test_util.py:1970] time(__main__.SubstrOpTest.testBroadcast(<class 'numpy.int64'>, 'BYTE')): 0.0s
[       OK ] SubstrOpTest.testBroadcast(<class 'numpy.int64'>, 'BYTE')
[ RUN      ] SubstrOpTest.testBroadcast(<class 'numpy.int32'>, 'UTF8_CHAR')
python3.5: external/com_google_absl/absl/strings/string_view.h:292: absl::lts_2020_02_25::string_view::operator[](absl::lts_2020_02_25::string_view::size_type) const::<lambda()>: Assertion `false && "i < size()"' failed.
Fatal Python error: Aborted
```

cc @impjdi

**Comment by byronyi** [comment]
Also cc @yongtang per this issue

**Comment by yongtang** [comment]
@byronyi @CuiYifeng tensorflow-io and tensorflow-io-nightly pip packages are still tied to TF 2.2.0. 

TF nightly recently changed quite a few APIs and is not stable enough for us to switch and build against tf-nightly.

Note this also impact some of our ongoing PRs. As a workaround, tensorflow/io have a `nightly` branch that maintains compatibility with tf-nightly.

We will push the content of `nightly` branch tensorflow/io to `master` branch around the time TF 2.3.0 release candidate is out.

I will take another look to check the absl issue.

**Comment by impjdi** [comment]
TF doesn't use abseil-cpp lts_2020_02_25, but git commit df3ea785d8c30a9503321a3d35ee7d35808f190d (labeled "LTS 2020.02.25 Patch 1") with a patch around `string_view`.  Don't replace the TF-specified abseil-cpp with any other release because it will not work.  It took me a month full time to make it happen.

Also,

```
$ bazel test :substr_op_test  # macOS Catalina v10.15.4
[ ... omitted 9001 compilation warnings ... ]
//tensorflow/python/kernel_tests:substr_op_test                          PASSED in 10.2s
```

so you're using an official variant of TF, is that correct?

**Comment by byronyi** [comment]
> TF doesn't use abseil-cpp lts_2020_02_25, but git commit df3ea785d8c30a9503321a3d35ee7d35808f190d (labeled "LTS 2020.02.25 Patch 1") with a patch around `string_view`. Don't replace the TF-specified abseil-cpp with any other release because it will not work. It took me a month full time to make it happen.
> 
> Also,
> 
> ```
> $ bazel test :substr_op_test  # macOS Catalina v10.15.4
> [ ... omitted 9001 compilation warnings ... ]
> //tensorflow/python/kernel_tests:substr_op_test                          PASSED in 10.2s
> ```
> 
> so you're using an official variant of TF, is that correct?

I am using the RBE builds with environment [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/Dockerfile.rbe.cuda10.1-cudnn7-ubuntu16.04-manylinux2010-multipython) and toolchain definitions [here](https://github.com/tensorflow/tensorflow/blob/master/third_party/toolchains/remote_config/configs.bzl#L29-L40). Manually adding `--copt=-DNDEBUG` solves my issue there, so I guess it's not really related to the absl update.

**Comment by byronyi** [comment]
> Don't replace the TF-specified abseil-cpp with any other release because it will not work. It took me a month full time to make it happen.

That's truly remarkable. Thanks for the effort!

**Comment by gunan** [comment]
It looks like the issue was root caused?

**Comment by impjdi** [comment]
@gunan

1. I think @byronyi got his problem solved somehow, but @CuiYifeng hasn't reported back.
2. QQ: I'm not familiar with tensorflow-io.  Does it apply `com_google_absl_fix_mac_and_nvcc_build.patch` before building?

**Comment by yongtang** [comment]
@impjdi For tensorflow-io, we can only update the abseil once TF 2.3.0 rc0 is out. The master branch of tensorflow-io only depending on TF releases (not tf-nightly releases) due to the C++ API difference in tf-nightly. We will update the tensorflow-io code to make it compatible once TF 2.3.0rc0 is out.

**Comment by impjdi** [comment]
tensorflow-io depending on TF releases only is fine, but that doesn't explain the situation of commit 6c7e338 breaking the nightly.  If tensorflow-io depends on TF releases and commit 6c7e338 isn't a part of the latest release, it shouldn't break, should it?

**Comment by yongtang** [comment]
@impjdi From the description by @CuiYifeng I think the build is `tf-nightly` + `tensorflow-io`. As mentioned this will not work due to C++ API change in tf-nightly. A `tensorflow (2.2.0)` + `tensorflow-io (0.13.0)` will work.

**Comment by impjdi** [comment]
Gotcha.  Thanks for clarifying!

@CuiYifeng Please try out the recommendation.  I don't think there is anything we can do at this point until TF 2.3.0 rc0 is out.

**Comment by byronyi** [comment]
> It looks like the issue was root caused?

@gunan My issue was that my RBE builds with `-c opt` does not correctly set `-DNDEBUG` and hit Abseil's assertion during unit testing, which was introduced in the aforementioned patch. Current workaround is a manual `--copt=-DNDEBUG`, but I'd like to see why `-DNDEBUG` is not set in the RBE platform and/or toolchain definitions.

**Comment by gunan** [comment]
@r4nt @hlopko may know.
Where do we control which flags are set by `-c opt`

**Comment by hlopko** [comment]
(quick answer from phone)
In the cc_toolchain_config there is a feature named "opt" where these flags usually come from. Or there are other features that are conditionally enabled/flag_sets conditionally expanded based on the "opt" feature. I can look into this issue tomorrow.

**Comment by CuiYifeng** [comment]
> TF doesn't use abseil-cpp lts_2020_02_25, but git commit df3ea785d8c30a9503321a3d35ee7d35808f190d (labeled "LTS 2020.02.25 Patch 1") with a patch around `string_view`. Don't replace the TF-specified abseil-cpp with any other release because it will not work. It took me a month full time to make it happen.
> 
> Also,
> 
> ```
> $ bazel test :substr_op_test  # macOS Catalina v10.15.4
> [ ... omitted 9001 compilation warnings ... ]
> //tensorflow/python/kernel_tests:substr_op_test                          PASSED in 10.2s
> ```
> 
> so you're using an official variant of TF, is that correct?

@impjdi `tensorflow-2.2.0` doesn't meet my needs. Actually I replace the abseil-cpp with the one in r2.2 to build TF with recent master branch. The case you mentioned hasn't affected me yet. May I think you will resolve this issue in TF 2.3.0 rc0?

**Comment by impjdi** [comment]
According to yongtang, it will be.  Again, I'm not familiar with tensorflow-io, and can't comment.  I only make sure the master branch doesn't break.  If you do custom mix & match by parts, I think you're on your own.

**Comment by yongtang** [comment]
@CuiYifeng Yes we will make sure tensorflow-io' releases works with "versioned releases" (2.2/2.3) of TF. Once TF 2.3.0rc0 is out we will update tensorflow-io.

**Comment by byronyi** [comment]
@hlopko @gunan @impjdi I just checked that f805153a25b00d12072bd728e91bb1621bfcf1b1 checked-in yesterday fixed my issue above. Thanks!

**Comment by ravikyram** [comment]
@CuiYifeng 

Is this still an issue?
Please, close this thread if your issue was resolved.Thanks!

**Comment by CuiYifeng** [comment]
@ravikyram I have got the answer for my issue. Thanks for your information!

**Comment by HectorSVAI** [comment]
Getting now NotImplementedError: unable to open file: libtensorflow_io.so, from ... venv/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZNK10tensorflow10FileSystem8BasenameEN4absl12lts_2021110211string_viewE'] on tensorflow gpu nightly 2.10

**Comment by impjdi** [comment]
@HectorSVAI see yongtang's comment on May 27, 2020
