### ISSUE TITLE
add threadpool.h to the files exported to the sysconfig.get_include() directory with a binary install

### ISSUE THREAD

**Issue by kbrems** [tensorflow/tensorflow#3963]
### Environment info

Operating System: ubuntu 14.04

Installed version of CUDA and cuDNN: 7.5, v4
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
-rw-r--r-- 1 root root   322936 Aug 15  2015 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root       19 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root   383336 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root   720192 Aug 15  2015 /usr/local/cuda/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 61453024 Feb 23 16:00 /usr/local/cuda/lib64/libcudnn.so
-rwxr-xr-x 1 root root 61453024 Feb 23 16:00 /usr/local/cuda/lib64/libcudnn.so.4
-rwxr-xr-x 1 root root 61453024 Feb 23 16:00 /usr/local/cuda/lib64/libcudnn.so.4.0.7
-rw-r--r-- 1 root root 62025862 Feb 23 16:00 /usr/local/cuda/lib64/libcudnn_static.a

If installed from binary pip package, provide:
1. Which pip package you installed.
   https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
   I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
   I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
   I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
   I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
   I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
   0.10.0rc0
### Steps to reproduce

1.pip install tensorflow version 0.10.0rc0
2.ls /usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/lib/core
error_codes.pb.h  errors.h  notification.h  refcount.h  status.h  stringpiece.h

threadpool.h is not included in the exported header files with a binary install. This means this one can't implement a multi-threaded custom operator using the tensorflow threadpool. 

Note, the files that threadpool.h includes, 
# include "tensorflow/core/platform/env.h"
# include "tensorflow/core/platform/macros.h"
# include "tensorflow/core/platform/types.h"

ARE installed and the threadpool functionality is included in the core library. 

I can work around this by copying threadpool.h into my own custom operator library include directory, and everything works fine, but this is a fragile solution.

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/blob/c99b9bef4cdce8f1724095c77a9620ccf76045be/tensorflow/core/BUILD#L997 probably need to add the file to the list there (we probably need to do this for a bunch more headers that are public too).

@kbrems do you want to send us a change that adds this and any other headers that might be missing for you?

**Comment by kbrems** [comment]
threadpool.h is the only file we are missing. Maybe others are missing some more?

I can create a PR, but it may take a while to get the CLA through our corporate legal dept.

**Comment by vrv** [comment]
I believe you work at HP Labs and I see an "HP Inc." that's already signed the Google Corporate CLA, so assuming your email is part of your company's CLA list, it should already work. :)  Let me know if you'd rather me do it though -- I'd rather give you credit for finding this :)

**Comment by kbrems** [comment]
HP split into 2 companies last year: HP Inc. and Hewlett Packard Enterprise - I'm at Hewlett Packard Enterprise Labs, so we need our own CLA. I've sent the CLA to legal - let me see if I can get a response within a week. Otherwise maybe you will need to do it.

**Comment by vrv** [comment]
(see my edit above, is Enterprise labs separate from Enterprise?)

**Comment by kbrems** [comment]
@vrv Yes, HPE Labs is part of HPE. Awaiting legal approval to get added to the contributor list for tensorflow...

**Comment by drpngx** [comment]
Fixed by #4108.
