### ISSUE TITLE
Inferring using a frozen graph requires more memory

### ISSUE THREAD

**Issue by drunkinlove** [tensorflow/tensorflow#39641]
**System information**
- Have I written custom code: **yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 18.04.4 LTS**
- TensorFlow installed from (source or binary): **source**
- TensorFlow version (use command below): **v1.14.0-rc1-22-gaf24dc91b5 1.14.0**
- Python version: **3.6.9**
- GPU model and memory: Not used

**Standalone code to reproduce the issue**
To freeze graph:
```
graph = tf.get_default_graph()
input_graph_def = graph.as_graph_def()
output_graph_def = tf.graph_util.convert_variables_to_constants(sess, input_graph_def, ['output/predictions'])
f.write(output_graph_def.SerializeToString())
```
To load graph:
```
with tf.gfile.GFile(graph_filepath, 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
tf.import_graph_def(graph_def, self.placeholders)
scores = graph.get_tensor_by_name('import/output/scores:0')
self.normalized_scores = tf.nn.softmax(scores)
self.predictions = graph.get_tensor_by_name('import/output/predictions:0')
sess = tf.Session()
sess.graph.finalize()
```
To load checkpoint, I rebuild the graph from scratch, then use:
```
sess = tf.Session()
sess.run(tf.global_variables_initializer())
saver = tf.train.Saver()
ckpt = tf.train.get_checkpoint_state(ckpt_dir)
sess.graph.finalize()
```

**Describe the current behavior**
When using a checkpoint, a call to `sess.run(tf.global_variables_initializer())` takes up 260 MB (fair, considering raw weights are around that size), and then the process plateaus. 

When using a graph however:
* `graph_def.ParseFromString()` requires 255 MB, 
* `tf.import_graph_def()` uses an additional 264 MB, 
* and the first call to `sess.run` takes up 270 MB more. 

I can retrieve 255 MB by calling `del graph`, but `del graph_def` does nothing and the memory used by the graph_def is never released.

**Describe the expected behavior**
I should be able to free the 500+ MB used by the graph_def and imported graph, so that the model initialized with a frozen graph takes up as much memory as one initialized with a checkpoint.

Follow-up questions:
1. Shouldn't the model initialized with a frozen graph use even less memory than a checkpoint, considering that the training-only nodes were taken out? Does checkpoint contain values for training-only nodes? If not, why is it much larger? Is memory allocated for training-only nodes at all if I don't use an optimizer?
2. Why do calls to tf.Session() use different amounts of memory on different machines?

I use [memory_profiler](https://pypi.org/project/memory-profiler/) to measure the used memory.
The model is a CNN.

**Comment by ravikyram** [comment]
@drunkinlove 

Request you to share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by drunkinlove** [comment]
@ravikyram I prepared two scripts along with a frozen graph and a checkpoint:
https://drive.google.com/drive/folders/1dnUp7Nc38C43JpIRfrrL4Q1kh1o6Fz91?usp=sharing

**Comment by ravikyram** [comment]
@drunkinlove 

I tried in colab with TF 2.1 and i am seeing the below error message.`DecodeError: Error parsing message`.Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/ea63e70b4c575517784e60db4664c8a9/untitled903.ipynb)Thanks!

**Comment by drunkinlove** [comment]
@ravikyram The notebook works for me though:
https://colab.research.google.com/drive/1UW1VHp612OtxgQDOv_C71kxfBWZRTZZW?usp=sharing

I suggest verifying the graph.pb file, the one I uploaded should be fine. Here's the checksum (SHA-256):
3f3abe95abff708d8ae05fb27e6389e9d6700255782af8645ada7df2f0332d0c

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
