### ISSUE TITLE
predict on batch and predict have different behavior Assert and control depedencies

### ISSUE THREAD

**Issue by tanguycdls** [tensorflow/tensorflow#39643]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
I have a custom keras layer with an assertion and a control depedencies: 

```
class CustomLayer(Layer):
  def call(self, inputs):
    assert_same_batch_size = tf.assert_equal(tf.shape(inputs[0])[0],
                                                 tf.shape(inputs[1])[0], message="inputs do not have equal batch_size")
    with tf.control_dependencies([assert_same_batch_size]):
      return tf.reshape(inputs[0], (tf.shape(inputs[0])[0], 3))   # i want it to break

a = Input(shape=1)
b = Input(shape=1)
out = CustomLayer()([a, b])
m = Model([a, b], out)
```

> `m.predict_on_batch([tf.constant(np.ones((10, 1))), tf.constant(np.ones((15, 1)))])`
```
ValueError: Cannot reshape a tensor with 10 elements to shape [10,3] (30 elements) for '{{node model_2/custom_layer_8/Reshape}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32](model_2/Cast, model_2/custom_layer_8/Reshape/shape)' with input shapes: [10,1], [2] and with input tensors computed as partial shapes: input[1] = [10,3].
```

````
def generator(): # we use a generator to trick tf dataset into letting us use different nbr of rows in each vector
#(otherwise caught by tf.data.dataset.from_tensor_slices)
  for a in range(1):
    yield [tf.constant(np.ones((10, 1))), tf.constant(np.ones((15, 1)))]
m.predict(generator())
````

````
InvalidArgumentError:  assertion failed: [inputs do not have equal batch_size] [.....
````
**Describe the expected behavior**
The assertion error should be raised in both scenario with predict_on_batch and with predict. We dont know if its because control depencies is not used with predict_on_batch or if it comes from the assert. 

**Standalone code to reproduce the issue**
https://colab.research.google.com/gist/tanguycdls/d36d2a1175cec79143d0a3e9dddfbbad/untitled14.ipynb

**Comment by Saduf2019** [comment]
@tanguycdls 
Can you please refer to these links for the value error faced in your gist:[
link](https://stackoverflow.com/questions/51746179/valueerror-cannot-reshape-a-tensor-with-99872-elements-to-shape-1-125-1-8) [link1](https://www.dotnetperls.com/reshape-tensorflow) and for the invalid argument please refer to: [link](https://stackoverflow.com/questions/58609967/tensorflow-2-0-condition-x-y-did-not-hold-element-wise) [link1](https://github.com/tensorflow/models/issues/2737) [link2](https://github.com/tensorflow/tensorflow/issues/32333), let us know if this helps.

**Comment by tanguycdls** [comment]
@Saduf2019 thanks for your message ! 

my point is not the actual errors (that i produced on purpose): its that for the same input predict yields to an error the assert_same_batch_size error and predict_on_batch breaks later in `ValueError: Cannot reshape a tensor with 10`.
I think its odd that predict and predict_on_batch does not yield to the same error being caught for the same input.

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/4abf0d96e9e3d11b30e74dcc98a959cc/untitled189.ipynb)

**Comment by jvishnuvardhan** [comment]
@tanguycdls I think there is some typo or extra dimension as input to the `assert_equal`.

I changed one line as follows and the two errors are similar and shows `InvalidArgumentError` related to mismatch in batch_size. Please take a look at the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/62a964d8cba44476778bfa17bde76459/untitled189.ipynb#scrollTo=b5zRT4LoOXzK). Thanks!

```
assert_same_batch_size = tf.assert_equal(tf.shape(inputs[0]),
                                                 tf.shape(inputs[1]), message="inputs do not have equal batch_size")
```

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by tanguycdls** [comment]
Hi @jvishnuvardhan Thanks for the response !
I checked and yes it works but actually we only want to check the first shape dim not the second one ! Maybe it's the get_item that breaks it ? maybe i can try a tf.gather instead of [0]? I will try and get back to you.

**Comment by jvishnuvardhan** [comment]
@tanguycdls Is this still an issue for you? Thanks!
