### ISSUE TITLE
Tflite "Invoke" function stuck problem

### ISSUE THREAD

**Issue by chenpengf0223** [tensorflow/tensorflow#39640]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux debian 9
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: rk3399
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.1rc
- Python version: no
- Bazel version (if compiling from source): no
- GCC/Compiler version (if compiling from source): 6.3.0
- CUDA/cuDNN version: no
- GPU model and memory: Mali-T864 GPU

**Describe the current behavior**
We run the inference every frame, after calling the "Invoke" function some times, the function stuck.

**Comment by amahendrakar** [comment]
@chenpengf0223,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by chenpengf0223** [comment]
@amahendrakar ,
Thansk for you reply, my code is as following, I call "init" once at the begining, and call "run_inference" every frame.
its parameter "cfg" is the default setting.
********************************************************************************************
std::unique_ptr<tflite::Interpreter> interpreter_;
std::unique_ptr<tflite::FlatBufferModel> model_;
TfLiteDelegate* delegate_;
struct segmentor_config {
		int input_width = 512;
		int input_height = 512;
        int input_depth = 3;

		std::string frozen_net_path;
        bool enable_multi_thread = false;
		bool enable_gpu_inference = true;

		float mean_b = 127.9489;
		float mean_g = 125.3112;
		float mean_r = 125.6642;
		float standard_deviation_reciprocal = 0.0154;
};

void init(const segmentor_config &cfg)
{
    cfg_ = cfg;
    model_ = tflite::FlatBufferModel::BuildFromFile(cfg_.frozen_net_path.c_str());
    tflite::ops::builtin::BuiltinOpResolver resolver;
    tflite::InterpreterBuilder builder(*model_.get(), resolver);
    builder(&interpreter_);
    if(cfg_.enable_multi_thread)
        interpreter_->SetNumThreads(2);
    interpreter_->AllocateTensors();

    // Prepare GPU delegate.
    if(cfg_.enable_gpu_inference){
        const TfLiteGpuDelegateOptionsV2 options = {
            .is_precision_loss_allowed = 1,
            .inference_preference = TFLITE_GPU_INFERENCE_PREFERENCE_FAST_SINGLE_ANSWER,
            //.inference_preference = TFLITE_GPU_INFERENCE_PREFERENCE_SUSTAINED_SPEED,
        };
        delegate_ = TfLiteGpuDelegateV2Create(&options);
        //delegate_ = TfLiteGpuDelegateCreate(&options);
        
        if (interpreter_->ModifyGraphWithDelegate(delegate_) != kTfLiteOk) {
            std::cout << "ModifyGraphWithDelegate return false....." << std::endl;
            return;
        }
    }
}
void run_inference(const cv::Mat &src_img, cv::Mat& fisheye_mask_result){
    auto width = cfg_.input_width;
    auto height = cfg_.input_height;
    cv::Mat resized_img;
    cv::resize(src_img, resized_img, cv::Size(width, height), 0, 0, cv::INTER_NEAREST);
    resized_img.convertTo(resized_img, CV_8UC3);
    auto input = interpreter_->typed_input_tensor<float>(0);
    for (int i = 0; i < resized_img.rows; ++i){
        for (int j = 0; j < resized_img.cols; ++j)
        {
            cv::Vec3b v = resized_img.at<cv::Vec3b>(i, j);
            int idx = (i * resized_img.cols + j) * 3;
            input[idx] = (v[0] - cfg_.mean_b) * cfg_.standard_deviation_reciprocal;
            input[idx + 1] = (v[1] - cfg_.mean_g) * cfg_.standard_deviation_reciprocal;
            input[idx + 2] = (v[2] - cfg_.mean_r) * cfg_.standard_deviation_reciprocal;
        }
    }

    if(interpreter_->Invoke() != kTfLiteOk){
        std::cout << " interpreter_->Invoke()!= kTfLiteOk  " << std::endl;
        return;
    }

    auto node_index = interpreter_->outputs()[0];
    TfLiteTensor* p_tflts_output = interpreter_->tensor(node_index);
    cv::Mat seg_res = seg_res_parse(p_tflts_output);
    result = seg_res.clone();
}

cv::Mat seg_res_parse(TfLiteTensor* p_tflts_output, float threshold) const
{
    auto dims = p_tflts_output->dims;
    auto data_size = dims->data[2] * dims->data[1];

    cv::Mat seg_res = cv::Mat::zeros(cv::Size(cfg_.input_width, cfg_.input_height), CV_8U);
    uchar* data_ptr = seg_res.data;
    float* p_output_data = (float*)p_tflts_output->data.uint8;

    //argmax
    for (int i = 0; i < data_size; ++i)
    {
        int j = i * 2;
        if(p_output_data[j] < p_output_data[j + 1])
            data_ptr[i] = 255;
    }
    return seg_res;
}

**Comment by chenpengf0223** [comment]
@amahendrakar , 
I add log in "Invoke", and found that it stuck in function "Status Run() override" (which is in tensorflow/lite/delegates/gpu/cl/api.cc), where it stuck in function "CopyToExternalObject".

  Status Run() override {
    if (gl_interop_fabric_) {
      RETURN_IF_ERROR(gl_interop_fabric_->Start());
    }
    for (auto& obj : inputs_) {
      RETURN_IF_ERROR(obj->CopyFromExternalObject());
    }

    RETURN_IF_ERROR(context_->AddToQueue(queue_));
    clFlush(queue_->queue());

    std::cout<< "mylog tf clFlush " << std::endl;

    for (auto& obj : outputs_) {
      RETURN_IF_ERROR(obj->CopyToExternalObject());
    }
    std::cout<< "mylog tf CopyToExternalObject " << std::endl;

    if (gl_interop_fabric_) {
      RETURN_IF_ERROR(gl_interop_fabric_->Finish());
    }
    return OkStatus();
  }

**Comment by impjdi** [comment]
Correct me if I'm wrong, but based on

```
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux debian 9
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: rk3399
```

I assume you're not using it on a mobile device.  Unfortunately, we don't have experience with other platforms, and is probably out of scope for our support.

**Comment by lovehuanhuan** [comment]
The same problem happens  on my Rk3399 dev-board
