### ISSUE TITLE
no such package '@androidsdk//com.android.support'

### ISSUE THREAD

**Issue by momo1986** [tensorflow/tensorflow#39648]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (MacOS 10.13.6):
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.2.0
- Python version: 3.7
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): Apple Clang 10.0.0
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

Hello， dear tensorflow guys.

I want to build the official android demo from TF team.

My command is:

`bazel build -c opt --cxxopt='--std=c++11'   //tensorflow/lite/java/demo/app/src/main:TfLiteCameraDemo --experimental_repo_remote_exec
`

I set both Android SDK and NDK enviroment.

```
export ANDROID_SDK_API_LEVEL=26
export ANDROID_NDK_API_LEVEL=21
```

However, it has the error:

> ERROR: /Users/junyan/find_android_project/tensorflow/tensorflow/lite/java/demo/app/src/main/BUILD:8:1: no such package '@androidsdk//com.android.support': BUILD file not found in directory 'com.android.support' of external repository @androidsdk. Add a BUILD file to a directory to mark it as a package. and referenced by '//tensorflow/lite/java/demo/app/src/main:TfLiteCameraDemo'
> ERROR: /Users/junyan/find_android_project/tensorflow/tensorflow/lite/java/demo/app/src/main/BUILD:8:1: no such package '@androidsdk//com.android.support': BUILD file not found in directory 'com.android.support' of external repository @androidsdk. Add a BUILD file to a directory to mark it as a package. and referenced by '//tensorflow/lite/java/demo/app/src/main:TfLiteCameraDemo'
> ERROR: Analysis of target '//tensorflow/lite/java/demo/app/src/main:TfLiteCameraDemo' failed; build aborted: no such package '@androidsdk//com.android.support': BUILD file not found in directory 'com.android.support' of external repository @androidsdk. Add a BUILD file to a directory to mark it as a package

The build script is:

```
load("@build_bazel_rules_android//android:rules.bzl", "android_binary")

package(
    default_visibility = ["//visibility:private"],
    licenses = ["notice"],  # Apache 2.0
)

android_binary(
    name = "TfLiteCameraDemo",
    srcs = glob(["java/**/*.java"]),
    assets = [
        "//tensorflow/lite/java/demo/app/src/main/assets:labels_mobilenet_quant_v1_224.txt",
        "@tflite_mobilenet_quant//:mobilenet_v1_1.0_224_quant.tflite",
        "@tflite_mobilenet_float//:mobilenet_v1_1.0_224.tflite",
    ],
    assets_dir = "",
    custom_package = "com.example.android.tflitecamerademo",
    manifest = "AndroidManifest.xml",
    nocompress_extensions = [
        ".tflite",
    ],
    resource_files = glob(["res/**"]),
    # In some platforms we don't have an Android SDK/NDK and this target
    # can't be built. We need to prevent the build system from trying to
    # use the target in that case.
    tags = ["manual"],
    deps = [
        "//tensorflow/lite/java:tensorflowlite",
        "//tensorflow/lite/java:tensorflowlite_gpu",
        "//tensorflow/lite/java/src/testhelper/java/org/tensorflow/lite:testhelper",
        "@androidsdk//com.android.support:support-v13-25.2.0",
        "@androidsdk//com.android.support:support-v4-25.2.0",
    ],
```

Should I download com.android.support:support-v13-25.2.0 aar and com.android.support:support-v4-25.2.0 under the directory of android-sdk to compile it successfully?

Thanks & Regards!

**Comment by momo1986** [comment]
Is there any solution to fix it?

**Comment by momo1986** [comment]
How can I do some configuration to correlate the android-support widget?

Thanks & Regards!
Momo

**Comment by terryheo** [comment]
Did you run "./configure" script and enabled Android support?
Your .tf_configure.bazelrc file should have a valid Android SDK / NDK configurations.

**Comment by momo1986** [comment]
Hello, @terryheo .

I run the configuration script, however, still have the problem.

To be frank, I cannot decide which directory of file path is correct for "com.android.support" corresponding directory under the Android-SDK-Home library.

Here is the presentation of Android-SDK home directory.

 
![image](https://user-images.githubusercontent.com/34225874/82296148-53c0ed80-99e3-11ea-9872-383a673b4c10.png)

Which path should I refer to? If I cannot decide which local path to follow, is there a workaround to correlate an on-line android support library?

Thanks & Regards!
Momo

**Comment by terryheo** [comment]
Bazel will find the library if you provide a valid SDK home while running the configuration script.

I'm wonder if you installed Android SDK 26 support.
Could you share the content of your .tf_configure.bazelrc?
Can you verify if you have Android SDK 26 with SDK Manager tool?
