### ISSUE TITLE
tf.math.reduce_mean takes too long and produces wrong result when input_tensor is uint32/64 and axis is array

### ISSUE THREAD

**Issue by leeyeetonn** [tensorflow/tensorflow#39649]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 16.04, macOS 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):v2.1.0-rc2-17-ge5bf8de410 2.1.0 & v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version:3.7.6
- Bazel version (if compiling from source):NA
- GCC/Compiler version (if compiling from source):NA
- CUDA/cuDNN version:NA
- GPU model and memory:NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
`tf.math.reduce_mean` hangs(?) or takes forever to compute for certain input (with dtype uint64 and uint32, and axis an array). Around when the slow down occurs, the function produces incorrect result.

This function affects other functions' performance: `tf.math.reduce_std` which calls `tf.math.reduce_variance` which calls `tf.math.reduce_mean`
**Describe the expected behavior**
It should not take forever to compute nor produce an incorrect result.
**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

An example that showed incorrect result:
```python
import tensorflow as tf
import numpy as np
import time

input_tensor = np.arange(4).astype('uint64')  # also occurs for 'uint32'

for i in range(20):
  axis = [0] * i
  print('axis = ', axis)
  start = time.time()
  res = tf.math.reduce_mean(input_tensor, axis=axis)
  end = time.time()
  time_diff = end - start
  print('result = ', res.numpy())
  print('-- took %d sec --' % time_diff)
```
An example that both became extremely slow and produced an incorrect result:
```python
import tensorflow as tf
import numpy as np
import time

# 15 is a magic number chosen for illustration
# a smaller number may not cause the slow-down but could still show the wrong result
input_tensor = np.arange(15).astype('uint64')  # also occurs for 'uint32'

for i in range(20):
  # produces incorrect result when i == 8.
  # slow down occurs around when i == 10
  axis = [0] * i
  print('axis = ', axis)
  start = time.time()
  res = tf.math.reduce_mean(input_tensor, axis=axis)
  end = time.time()
  time_diff = end - start
  print('result = ', res.numpy())
  print('-- took %d sec --' % time_diff)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.1.0 ,2.2.0 and was able to reproduce the issue.Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/5261bff929134c88bd17f6fd57e05c39/untitled904.ipynb).Thanks!
