### ISSUE TITLE
how to build tflite python for ios platform?

### ISSUE THREAD

**Issue by JunyiXie** [tensorflow/tensorflow#39644]
how to build tflite python for ios platform. 
I want to run tflite on my app python interpreter.

**Comment by amahendrakar** [comment]
@JunyiXie,
To convert your TensorFlow model to TF Lite please check [this guide](https://www.tensorflow.org/lite/convert/python_api#python_api). 

Also, please take a look at [iOS quickstart](https://www.tensorflow.org/lite/guide/ios) and [Build TensorFlow Lite for iOS](https://www.tensorflow.org/lite/guide/build_ios) guide and let us know if it helps. Thanks!

**Comment by JunyiXie** [comment]
https://www.tensorflow.org/lite/guide/python

**Comment by JunyiXie** [comment]
@amahendrakar

**Comment by ymodak** [comment]
I don't think we support TF Lite python api for iOS platform yet. Perhaps this can be a feature request.

**Comment by yyoon** [comment]
We don't have any plans to officially release a tflite python library specifically for iOS. Can you explain more details about your use case? Also, what have you already tried so far?

**Comment by JunyiXie** [comment]
I hope that I can write code in Python and execute it in the Python interpreter on iOS.

**Comment by JunyiXie** [comment]
how to build https://github.com/tensorflow/tensorflow/tree/v2.2.0/tensorflow/lite/python? I try to build the iOS version. 
I need tensorflow lite python version build script on mac os platform as a reference.

**Comment by yyoon** [comment]
You can build the standalone TFLite pip package following this guide:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package

**Comment by ymodak** [comment]
Closing this issue for now. Feel free to reopen if necessary. Thanks!
