### ISSUE TITLE
Conv2d issue with GPU

### ISSUE THREAD

**Issue by skolouri** [tensorflow/tensorflow#3965]
I have extracted the activations of a neural net at a certain layer with size [1,28,28,128] and I have a corresponding kernel that I want to convolve with these activations. The kernel shape is [3,3,128,256]. 
I am using:

   * 2 GTX-1080 GPUs
   * Cuda-8.0 (The problem persists with Cuda-7.5 as well)
   * Graphics Driver: NVIDIA-367
   * Python 2.7

When I perform 2D convolution using the CPU I get the correct answer but when I run it through the GPU I get all zeros. Note that, there is no ReLu operator involved here and the output should not be zero (as confirmed by the CPU output). In addition, I do not think this is a numerical precision error. 

I have included the codes, activations and the kernel files for reproducing the problem here: 

https://github.com/skolouri/GTX-1080_CNN_Issue

### Environment info
Operating System: Linux 14.04

Installed version of CUDA and cuDNN: Cuda-8.0.27 and cudNN-4.0.7

### Steps to reproduce

The steps are included here:

https://github.com/skolouri/GTX-1080_CNN_Issue

### What have you tried?
1. I have tried Cuda-7.5 
2. CPU works fine, GPU returns all zeros!

**Comment by Mazecreator** [comment]
Hi,

I posted a reply at: https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!msg/discuss/FTcjjGhZOkA/BHH1j9mWAgAJ

There is a little more detail in this message.  You need to use the cuDNN 5.0 that works with CUDA 8.0, that is certain.  I am not sure if you need to run Ubuntu 16.04 for the GTX1080 driver, but keep that in mind if you have trouble after the cuDNN update.

Here is my execution of your test script:

![screenshot 2016-08-22 17 11 10](https://cloud.githubusercontent.com/assets/18412448/17873198/16b0f01a-6892-11e6-975c-097f6fee4890.png)

**Comment by skolouri** [comment]
Thanks Greg! CudNN-5.0 solved the issue.

**Comment by Mazecreator** [comment]
Great, so it looks like 14.0X is okay, but need the CUDA 8.0 and cuDNN 5.0.

**Comment by prb12** [comment]
Looks to be fixed. Closing this issue.
