### ISSUE TITLE
Eager execution in TF 2.2.0rc2

### ISSUE THREAD

**Issue by vladimircape** [tensorflow/tensorflow#39656]
Tensorflow 2.2.0rc2
Windows 10
Python 3.6.8(Anaconda)
CuDNN 7.6.5 CUDA 10.1
Nvidia 1060 6Gb
I have a model based on Keras

> import tensorflow.keras as keras

when try 
```
model_details=model.fit(
    data_train,
    box_train,    
    batch_size=128,epochs=100,shuffle=True,validation_split=0.1,callbacks=[lr_scheduler,lr_reducer,checkpoint],verbose=1)
```

got error
`InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run GatherV2: Dst tensor is not initialized. [Op:GatherV2]`

but when disable Eager , everything is working?

`tf.compat.v1.disable_eager_execution()`

**Comment by amahendrakar** [comment]
@vladimircape,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here.

Also, please upgrade to the stable version of TensorFlow v2.2 and let us know if you are facing the same issue. Thanks!
