### ISSUE TITLE
Checkpoint is not work properly

### ISSUE THREAD

**Issue by shwoghk14** [tensorflow/tensorflow#39651]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64 1909 Home
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
tf.save_weights is not work properly

https://www.tensorflow.org/tutorials/keras/save_and_load#saved_model%EC%9D%84_%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

When I follow the tutorial of tensorflow checkpoint section, It does not make *.ckpt file but makes .ckpt folder!!!!

**Describe the expected behavior**
It need make .ckpt files.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import cv2
import random
import os




np.random.seed(1)
random.seed(1)
tf.random.set_seed(1)

checkpoint_path = 'checkpoint\\cp-{epoch:04d}.ckpt'
checkpoint_dir = os.path.dirname(checkpoint_path)


(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.mnist.load_data()

train_images = train_images / 255.0
test_images = test_images / 255.0


train_dataset = tf.data.Dataset.from_tensor_slices((train_images, train_labels))


model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dropout(0.02, seed=1),
    tf.keras.layers.Dense(254, activation='relu'),
    tf.keras.layers.Dropout(0.02, seed=1),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.01, seed=1),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='sigmoid'),
    tf.keras.layers.Dense(10)
])



checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_path,
    verbose=1,
    save_weight_only=True,
    period=2
)


model.save_weights(checkpoint_path.format(epoch=0))

epochs = 10

model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=['accuracy']
)


model.fit(
    train_dataset.shuffle(int(len(train_images)+500), seed=1).batch(256),
    epochs=epochs,
    callbacks=[checkpoint_callback],
    verbose=1
)


loss, acc = model.evaluate(test_images,  test_labels, verbose=2)
print("Untrained model, accuracy: {:5.2f}%".format(100*acc))

```

**Comment by Saduf2019** [comment]
@shwoghk14 
Please share simple stand alone code for us to replicate the issue faced, or share a colab gist with the error for us to analyse the issue faced

**Comment by shwoghk14** [comment]
> @shwoghk14
> Please share simple stand alone code for us to replicate the issue faced, or share a colab gist with the error for us to analyse the issue faced

I was added code that take weird actions.

Thanks.

**Comment by Saduf2019** [comment]
@shwoghk14 
I ran the code shared , please refer to [this gist](https://colab.sandbox.google.com/gist/Saduf2019/bcbf7c557ffd275a7a57fc3bbc5d65ba/untitled191.ipynb) and let us know if it confirms your issue

**Comment by shwoghk14** [comment]
> @shwoghk14
> I ran the code shared , please refer to [this gist](https://colab.sandbox.google.com/gist/Saduf2019/bcbf7c557ffd275a7a57fc3bbc5d65ba/untitled191.ipynb) and let us know if it confirms your issue

@Saduf2019 
Yes! If you seed the /content where saving location of checkpoint, you can see the folders but not .ckpt files.
It's odds!

**Comment by jvishnuvardhan** [comment]
@shwoghk14 I have changed your code very little and it is working as expected. Please verify once and let me know if this is what you are expecting.  Thanks!

Please close the issue if this was resolved for you. Thanks!

**Comment by shwoghk14** [comment]
> @shwoghk14 I have changed your code very little and it is working as expected. Please verify once and let me know if this is what you are expecting. Thanks!
> 
> Please close the issue if this was resolved for you. Thanks!

@jvishnuvardhan Where can I see the code which was eidted?
Thanks.

**Comment by jvishnuvardhan** [comment]
@shwoghk14 Sorry, forgot to attach. [Here](https://colab.research.google.com/gist/jvishnuvardhan/a650c2493304930e9e3d5d43496ccdaa/39651.ipynb) is the gist. Thanks!

**Comment by shwoghk14** [comment]
> @shwoghk14 Sorry, forgot to attach. [Here](https://colab.research.google.com/gist/jvishnuvardhan/a650c2493304930e9e3d5d43496ccdaa/39651.ipynb) is the gist.
> 
> I ran with `TF2.1` and `tf-nightly`. You can run with `TF2.1`, don't need to change (but suggested as newer versions are has better performance). Thanks!

@jvishnuvardhan I ran my computer but it occur a error.
```
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: checkpoint/cp-0001.ckpt\variables; No such file or directory
```

It is why I instead use \\ but / in  checkpoint_path.
Anyway I ran your code on gist and on my local computer(use \\ in path) not changed behaviors.
It makes folders not files.


```
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: checkpoint/cp-0001.ckpt\variables; No such file or directory
```

**Comment by jvishnuvardhan** [comment]
I will check on my windows laptop and let you know the solution. Thanks!

**Comment by shwoghk14** [comment]
@jvishnuvardhan 
Is it not done? The tensorflow bot says this issue is closed soon.

**Comment by jvishnuvardhan** [comment]
@shwoghk14 bot will not close this. I will check it on my windows laptop later today. Thanks!

**Comment by janapativishnu** [comment]
@shwoghk14 I ran it in my Windows10 laptop. It works without any error. Please check the log.

Please verify once and close the issue if this was resolved for you. Thanks!

```
C:\Users\XXXXX>python C:\Users\XXXXX\Downloads\GitHub_models\checkpoints.py
2020-07-07 17:25:22.093668: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-07-07 17:25:22.103596: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1dff5494650 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-07 17:25:22.109377: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-07 17:25:23.270684: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 376320000 exceeds 10% of free system memory.
2020-07-07 17:25:23.662429: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 376320000 exceeds 10% of free system memory.
Epoch 1/10
234/235 [============================>.] - ETA: 0s - loss: 0.3782 - accuracy: 0.9316
Epoch 00001: saving model to checkpoint/cp-0001.ckpt
2020-07-07 17:25:29.053866: W tensorflow/python/util/util.cc:329] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
WARNING:tensorflow:From c:\users\XXXXX\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:1817: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
235/235 [==============================] - 5s 21ms/step - loss: 0.3778 - accuracy: 0.9316
2020-07-07 17:25:30.085141: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 376320000 exceeds 10% of free system memory.
Epoch 2/10
234/235 [============================>.] - ETA: 0s - loss: 0.1064 - accuracy: 0.9751
Epoch 00002: saving model to checkpoint/cp-0002.ckpt
235/235 [==============================] - 5s 21ms/step - loss: 0.1064 - accuracy: 0.9751
2020-07-07 17:25:35.396674: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 376320000 exceeds 10% of free system memory.
Epoch 3/10
234/235 [============================>.] - ETA: 0s - loss: 0.0686 - accuracy: 0.9824
Epoch 00003: saving model to checkpoint/cp-0003.ckpt
235/235 [==============================] - 5s 21ms/step - loss: 0.0686 - accuracy: 0.9824
2020-07-07 17:25:40.746641: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 376320000 exceeds 10% of free system memory.
Epoch 4/10
233/235 [============================>.] - ETA: 0s - loss: 0.0492 - accuracy: 0.9870
Epoch 00004: saving model to checkpoint/cp-0004.ckpt
235/235 [==============================] - 5s 21ms/step - loss: 0.0494 - accuracy: 0.9870
Epoch 5/10
234/235 [============================>.] - ETA: 0s - loss: 0.0373 - accuracy: 0.9898
Epoch 00005: saving model to checkpoint/cp-0005.ckpt
235/235 [==============================] - 5s 22ms/step - loss: 0.0374 - accuracy: 0.9898
Epoch 6/10
235/235 [==============================] - ETA: 0s - loss: 0.0318 - accuracy: 0.9912
Epoch 00006: saving model to checkpoint/cp-0006.ckpt
235/235 [==============================] - 5s 23ms/step - loss: 0.0318 - accuracy: 0.9912
Epoch 7/10
234/235 [============================>.] - ETA: 0s - loss: 0.0257 - accuracy: 0.9928
Epoch 00007: saving model to checkpoint/cp-0007.ckpt
235/235 [==============================] - 5s 22ms/step - loss: 0.0257 - accuracy: 0.9928
Epoch 8/10
234/235 [============================>.] - ETA: 0s - loss: 0.0238 - accuracy: 0.9936
Epoch 00008: saving model to checkpoint/cp-0008.ckpt
235/235 [==============================] - 5s 22ms/step - loss: 0.0238 - accuracy: 0.9937
Epoch 9/10
235/235 [==============================] - ETA: 0s - loss: 0.0212 - accuracy: 0.9944
Epoch 00009: saving model to checkpoint/cp-0009.ckpt
235/235 [==============================] - 5s 21ms/step - loss: 0.0212 - accuracy: 0.9944
Epoch 10/10
233/235 [============================>.] - ETA: 0s - loss: 0.0179 - accuracy: 0.9951
Epoch 00010: saving model to checkpoint/cp-0010.ckpt
235/235 [==============================] - 5s 22ms/step - loss: 0.0181 - accuracy: 0.9951
313/313 - 1s - loss: 0.0891 - accuracy: 0.9787
Untrained model, accuracy: 97.87%
```

**Comment by shwoghk14** [comment]
@janapativishnu Hello.
The error is not a point.
My issue is the abnormal behavior of checkpoint.
I has known the checkpoint makes .ckpt file.
But my code makes .ckpt folder.
That is a point.

**Comment by janapativishnu** [comment]
@shwoghk14 It is expected. Code makes .ckpt folder and inside the folder there will be three things (`saved_model.pb`, and two folders `assets` and `variables`).

I used this path (instead of your's)
#checkpoint_path = 'checkpoint\\cp-{epoch:04d}.ckpt'
checkpoint_path = '/checkpoint/cp-{epoch:04d}.ckpt'
checkpoint_dir = os.path.dirname(checkpoint_path)
```
Please check the checkpoint directory.
![GitHub](https://user-images.githubusercontent.com/15189960/86864306-c9f7dd00-c081-11ea-8b6f-eb0a4e502dc6.png)

```

**Comment by janapativishnu** [comment]
@shwoghk14 I just tried your path also. It works similar to my path shown in the last comment. Similarly, each of the .ckpt directory has one file and 2 folders. Thanks!

**Comment by shwoghk14** [comment]
@janapativishnu Yes, I also got that. but, I need a cp-0001.ckpt file, not cp-0001.ckpt folder.
Make a folder is expected behavior?

but I doing this code which on below URL makes cp-0001.ckpt file.
https://www.tensorflow.org/tutorials/keras/save_and_load#saved_model%EC%9D%84_%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

Thanks.

**Comment by shwoghk14** [comment]
@janapativishnu I'm sorry. My mistakes to say cp-0001.ckpt file.

The tutorial makes cp-0005.ckpt.index, cp-0005.ckpt.data-00000-of-00002, cp-0005.ckpt.data-00001-of-00002, cp-0005.ckpt.index

I want those files which above four not ckpt folders.


this is tutorial code.
```
import os

import tensorflow as tf
from tensorflow import keras

print(tf.version.VERSION)

(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.mnist.load_data()

train_labels = train_labels[:1000]
test_labels = test_labels[:1000]

train_images = train_images[:1000].reshape(-1, 28 * 28) / 255.0
test_images = test_images[:1000].reshape(-1, 28 * 28) / 255.0

# Define a simple sequential model
def create_model():
  model = tf.keras.models.Sequential([
    keras.layers.Dense(512, activation='relu', input_shape=(784,)),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(10)
  ])

  model.compile(optimizer='adam',
                loss=tf.losses.SparseCategoricalCrossentropy(from_logits=True),
                metrics=['accuracy'])

  return model

# Create a basic model instance
model = create_model()

# Display the model's architecture
model.summary()

# Include the epoch in the file name (uses `str.format`)
checkpoint_path = "training_2/cp-{epoch:04d}.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_path)

# Create a callback that saves the model's weights every 5 epochs
cp_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_path,
    verbose=1,
    save_weights_only=True,
    period=5)

# Create a new model instance
model = create_model()

# Save the weights using the `checkpoint_path` format
model.save_weights(checkpoint_path.format(epoch=0))

# Train the model with the new callback
model.fit(train_images,
          train_labels,
          epochs=50,
          callbacks=[cp_callback],
          validation_data=(test_images,test_labels),
          verbose=0)

# This may generate warnings related to saving the state of the optimizer.
# These warnings (and similar warnings throughout this notebook)
# are in place to discourage outdated usage, and can be ignored.

model = create_model()

# Evaluate the model
loss, acc = model.evaluate(test_images,  test_labels, verbose=2)
print("Untrained model, accuracy: {:5.2f}%".format(100*acc))

```
<img width="777" alt="주석 2020-07-08 111412" src="https://user-images.githubusercontent.com/48680511/86866584-33bcc900-c10c-11ea-9dbd-f4e727ff2fb4.png">

Thanks.

**Comment by abStack-pk** [comment]
Change save_weight_only=True, to **save_weights_only**=True (weights with s) in tf.keras.callbacks.ModelCheckpoint and it should create files instead of folders

Ref : https://abstack.pk/post/tensorflow-create-ckpt-files-instead-of-folders

**Comment by shwoghk14** [comment]
@abStack-pk  HI,
I hadn't know that has missing letter 's'.
Thanks, I question is solved.

Best regards.

**Comment by jvishnuvardhan** [comment]
Closing this issue as this was resolved. Thanks!
