### ISSUE TITLE
Tensorflow containers are missing from Docker Hub

### ISSUE THREAD

**Issue by pauljohn32** [tensorflow/tensorflow#39652]
Your docker pages point at 

https://hub.docker.com/r/tensorflow/tensorflow 

Today that returns "404" Oops! Page not found.

**Comment by thomasjo** [comment]
It works fine now. I am guessing this was a temporary glitch.

**Comment by amahendrakar** [comment]
@pauljohn32,
I am able to access the link you have posted. Could you please try again and check if it works. Thanks!

**Comment by pauljohn32** [comment]
Agree. Works now. I tried to access at exact moment the offerings were being replaced, I think.
