### ISSUE TITLE
[Tf 2.x] Can't return variables as tf.keras.Model outputs

### ISSUE THREAD

**Issue by cipollone** [tensorflow/tensorflow#39653]
**System information**
- Reproduced in Colab, currently with Tensorflow 2.2
- Reproduced in Debian Buster, Tensorflow 2.1, CPU, built from source.

**Describe the current behavior**
```python
import tensorflow as tf

inputs = tf.keras.Input([])
var = tf.Variable(3.0)

# OK
tf.keras.Model(inputs=inputs, outputs=[inputs*var])

# AttributeError exception
tf.keras.Model(inputs=inputs, outputs=[inputs*var,var])
# The same happens with variants like `tf.identity(var)`
```

**Describe the expected behavior**
No exception raised

**Standalone code to reproduce the issue**
Code [https://colab.research.google.com/drive/1EBXU51kVb6zrf1gA4iHcJInzkixrXk4l?usp=sharing](https://colab.research.google.com/drive/1EBXU51kVb6zrf1gA4iHcJInzkixrXk4l?usp=sharing)

**Other info / logs**
Same as: https://github.com/keras-team/keras/issues/12673, but that was on the wrong repo, I think.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.1.0, 2.2.0, nightly versions and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/13aaca4ee43e1d7ee23143e4cf8420db/untitled907.ipynb).Thanks!

**Comment by karmel** [comment]
We do not allow setting Variables as model outputs. That said, you should be able to cast the Variable as a tensor using `tf.identity`, and the tensor can then serve as the output. 

https://www.tensorflow.org/api_docs/python/tf/identity

**Comment by cipollone** [comment]
Sorry, but it seems that it can be used as output not even with `var.value()` or `tf.identity(var)`.
Tell me if I'm wrong.
