### ISSUE TITLE
Resize images before feeding for deep tensorflow model

### ISSUE THREAD

**Issue by PythonImageDeveloper** [tensorflow/tensorflow#39662]
Hello everyone.
 I tested any size of input image for ssd detection models, it don’t effect in timing prediction and all the results are same and correct.
In your opinion, inside the frozen graph model has resizer node or operation for this task on GPU?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
