### ISSUE TITLE
New converter in tf 2.2 does not propely convert PReLU operation

### ISSUE THREAD

**Issue by anilsathyan7** [tensorflow/tensorflow#39667]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): TF Google Colaboratory
- TensorFlow version (or github SHA if from source): TF 2.2

**Command used to run the converter or code if you’re using the Python API**

```
def bilinear_resize(x, rsize):
  return tf.compat.v1.image.resize_bilinear(x, [rsize,rsize], align_corners=True)

model=load_model('/content/slim-net-157-0.02.hdf5',compile=False)

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open("model.tflite", "wb").write(tflite_model)
```

**The output from the converter invocation**

```
1511172 
```

**Also, please include a link to the saved model or GraphDef**

```
https://github.com/anilsathyan7/Portrait-Segmentation/blob/master/models/slim_seg_512/slim-net-157-0.02.hdf5
```
The result is same for any model in general with PReLU operation

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
-  It splits PReLU into Neg, ReLU and Mul layers
-  I need to run it using tflite gpu delegate which supports PReLU operation

**Any other info / logs**

It produces correct results using old converter i.e 
with option **converter.experimental_new_converter=False**

**Comment by Saduf2019** [comment]
@anilsathyan7 
Please provide complete stand alone code such that we could replicate the issue reported above, the code shared produces different error, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/88e6e8e9140b3707d09f78248d0bc280/untitled187.ipynb)

**Comment by anilsathyan7** [comment]
Here is the updated gist:https://colab.research.google.com/gist/anilsathyan7/7187a94a6c5f146f952a8f1149d287a4/untitled187.ipynb

**With new converter:-**
PReLU is split into Neg, ReLU and Mul
![prelu_split](https://user-images.githubusercontent.com/1130185/82318550-ac958380-99ed-11ea-8637-c3fb2a008ea9.png)

**With old converter:-**
We are able to convert PReLU properly
![prelu_expected](https://user-images.githubusercontent.com/1130185/82319001-6bea3a00-99ee-11ea-8f76-d8ea23778b5b.png)

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/5daf3e01cb271ba7dc1fd8622a9f554e/untitled191.ipynb)

**Comment by anilsathyan7** [comment]
How can we fix this problem?

**Comment by MeghnaNatraj** [comment]
The issue is now **resolved** with the latest TensorFlow version:
1. TF tf_nightly (2.3.0.dev20200610)
```
!pip install tf_nightly
```
2. TF 2.2 latest version (2.2.0-rc4)
```
!pip install tensorflow==2.2.0-rc4
```
