### ISSUE TITLE
tflite_interpreter.invoke() give error for 2 input tensors

### ISSUE THREAD

**Issue by mahesh2996** [tensorflow/tensorflow#39664]
project description:
auto image caption model building using LSTM and ann. and convert  model into tflite model.
 
problem:
so, in this model we need to give 2 inputs one for image another one for text.
tflite model was created.
when i checking tflite model through input, `tflite_interpreter.invoke()` arise error.

i attached my ipynb link.kindly go through it.
advance thanks for every one.
[Notebook](https://github.com/mahesh2996/image_caption)

**Comment by Saduf2019** [comment]
@ mahesh2996 
Can you please let us know the tensorflow version on which this issue is faced.

**Comment by mahesh2996** [comment]
> @ mahesh2996
> Can you please let us know the tensorflow version on which this issue is faced.

tensorflow version:2.2.0
Thank you very much for your help.

**Comment by Saduf2019** [comment]
@mahesh2996 
I ran the notebook shared but face an error, please refer to this [gist here](https://colab.sandbox.google.com/gist/Saduf2019/3c28a3a85c9c221e2e2f61720c70f4c9/untitled198.ipynb), please share all dependencies to reproduce the error faced or a colab gist if possible.

**Comment by mahesh2996** [comment]
> @mahesh2996
> I ran the notebook shared but face an error, please refer to this [gist here](https://colab.sandbox.google.com/gist/Saduf2019/3c28a3a85c9c221e2e2f61720c70f4c9/untitled198.ipynb), please share all dependencies to reproduce the error faced or a colab gist if possible.

Image caption:Gist Link
https://gist.github.com/mahesh2996/bbc9a0730bae276c94fbe7187029e928

**Comment by mahesh2996** [comment]
> > @mahesh2996
> > I ran the notebook shared but face an error, please refer to this [gist here](https://colab.sandbox.google.com/gist/Saduf2019/3c28a3a85c9c221e2e2f61720c70f4c9/untitled198.ipynb), please share all dependencies to reproduce the error faced or a colab gist if possible.
> 
> Image caption:Gist Link
> https://gist.github.com/mahesh2996/bbc9a0730bae276c94fbe7187029e928

data set:[](https://www.kaggle.com/keenwarrior/small-flicker-data-for-image-captioning/version/1)

**Comment by Saduf2019** [comment]
@mahesh2996
I am unable to access the links shared, Could you please share a gist of your complete code along with the errors faced.

**Comment by mahesh2996** [comment]
> @mahesh2996
> I am unable to access the links shared, Could you please share a gist of your complete code along with the errors faced.

i tried gist.but not able to do.sorry for that.
In this notebook all cells are executed perfectly except the error one.
i used this data set:[https://www.kaggle.com/keenwarrior/small-flicker-data-for-image-captioning/version/1](url)
[Notebook](https://github.com/mahesh2996/image_caption)

**Comment by Saduf2019** [comment]
@mahesh2996
Like the earlier gist shared i am unable to access this code, can you please paste the code here so i could try to replicate the issue.
