### ISSUE TITLE
Update "Custom Training" section for `Model.train_step`

### ISSUE THREAD

**Issue by ngc92** [tensorflow/tensorflow#39671]
## URL(s) with the issue:
https://www.tensorflow.org/tutorials/customization/custom_training
https://www.tensorflow.org/tutorials/customization/custom_training_walkthrough

## Description of issue (what needs changing):
The tutorial for custom training makes no mention of the `train_step` and related methods that have been added to `keras.Model`.  

One of these tutorials should have a section and example on using a custom `train_step` method.

**Comment by lamberta** [comment]
I don't think we need to update the entire site, but seems like a useful thing to add to the Keras guide, at least: https://www.tensorflow.org/guide/keras/overview

**Comment by ngc92** [comment]
sorry I wasn't very specific, with update I mainly meant "add a section (and example) to"; I've updated the issue to make that clearer

**Comment by amahendrakar** [comment]
@ngc92,
Please take a look at [this guide](https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit#a_first_simple_example) to customize what happens in the `model.fit()` function and let us know if this is what you're looking for? Thanks!

**Comment by ngc92** [comment]
yes, that looks good

**Comment by nikitamaia** [comment]
Closing issue since this is explained in the [Customize what happens in Model.fit](https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit#a_first_simple_example) guide. Feel free to put in a PR if you think it would help to link to the guide from the api docs.
