### ISSUE TITLE
AllocateTensors fails in hello world example

### ISSUE THREAD

**Issue by muskedunder** [tensorflow/tensorflow#39673]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): Source
- Tensorflow version (commit SHA if source): 32165792a
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Host

**Describe the problem**
I try to run the hello world example as described on page 92 of the TinyML book but it fails.

**Please provide the exact sequence of commands/steps when you ran into the problem**
Building the binary
`make -f tensorflow/lite/micro/tools/make/Makefile hello_world`
Running the binary
`tensorflow/lite/micro/tools/make/gen/linux_x86_64/bin/hello_world`
I get back
```
Failed to allocate memory. Requested: 400, available 264, missing: 136
Failed to allocate memory for node_and_registrations.
AllocateTensors() failed
[1]    9967 segmentation fault (core dumped)  tensorflow/lite/micro/tools/make/gen/linux_x86_64/bin/hello_world
```

**Comment by PhilippRamjoue** [comment]
Hi Colin,

I had the same issue. I'm using Ubuntu 18.04 on aarch64. 

I'm not sure if this solution fixes the "real" root of the problem but it helped.

In the file tensorflow/lite/micro/examples/hello_world/main_functions.cc:

You have to increase your reserved memory block.

original line 38:
`constexpr int kTensorArenaSize = 2 * 1024;`
new line 38: 
`constexpr int kTensorArenaSize = 3 * 1024;` 

I'm really not sure why this is a problem on a custom pc. I built this example with the command 

make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mbed TAGS="CMSIS-nn nucleo_f207zg" generate_hello_world_mbed_project

for my STM development board and it worked with the 2048 bytes. 

As mentioned in the book defining a tensor arena could be trail and error.

Cheers 
Philipp

**Comment by sushreebarsa** [comment]
@muskedunder It looks like you are using an older Version of Tensorflow . Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? Thanks!
