### ISSUE TITLE
ops.executing_eagerly_outside_functions AssertionError when using train_on_batch with MirroredStrategy and disable_eager_execution

### ISSUE THREAD

**Issue by chuanli11** [tensorflow/tensorflow#39670]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: Quadro RTX

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"` v2.2.0-rc4-8-g2b96f3662b 2.2.0

**Describe the current behavior**
Multi-GPU training (MirrorStrategy) with Keras train_on_batch API and disable_eager_execution() causes the following AssertionError:

```
Traceback (most recent call last):
  File "mini_test.py", line 27, in <module>
    model.train_on_batch(x, y)
  File "/home/ubuntu/keras-examples/venv-keras-examples/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_v1.py", line 1050, in train_on_batch
    output_loss_metrics=self._output_loss_metrics)
  File "/home/ubuntu/keras-examples/venv-keras-examples/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_eager.py", line 316, in train_on_batch
    output_loss_metrics=output_loss_metrics))
  File "/home/ubuntu/keras-examples/venv-keras-examples/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_eager.py", line 250, in _process_single_batch
    with backend.eager_learning_phase_scope(1 if training else 0), \
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/ubuntu/keras-examples/venv-keras-examples/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 456, in eager_learning_phase_scope
    assert ops.executing_eagerly_outside_functions()
AssertionError
```
**Describe the expected behavior**
Error only occurs when using train_on_batch, MirrorStrategy and disable_eager_execution all together at the same time. 
* Turn off MirrorStrategy or disable_eager_execution will make the error disappear. 
* Replace model.train_on_batch() by model.fit() will also make the error go away

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
import tensorflow as tf
import numpy as np

from tensorflow.python.framework.ops import disable_eager_execution
disable_eager_execution()

strategy = tf.distribute.MirroredStrategy(
    devices=["/gpu:0", "/gpu:1"])

x = np.zeros((32, 28, 28))
y = np.zeros((32,))

with strategy.scope():
    model = tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(10),
    ])

    model.compile(
        optimizer=tf.keras.optimizers.SGD(),
        loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
        metrics=['accuracy'])

for i in range (2):
    model.train_on_batch(x, y)

print(tf.executing_eagerly())
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Replace model.train_on_batch by model.fit (the code below) will make the error go away. Comment out `disable_eager_execution()` or `with strategy.scope():` will also make the error disappear. 

```
import tensorflow as tf
import numpy as np

from tensorflow.python.framework.ops import disable_eager_execution
disable_eager_execution()

strategy = tf.distribute.MirroredStrategy(
    devices=["/gpu:0", "/gpu:1"])

with strategy.scope():
    (x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
    x_train, x_test = x_train / 255.0, x_test / 255.0
    train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(512)

    model = tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(64, activation='relu'),       
        tf.keras.layers.Dense(10),
    ])

    model.compile(
        optimizer=tf.keras.optimizers.SGD(),
        loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
        metrics=['accuracy'])

model.fit(
    train_dataset,
    epochs=2
)

print(tf.executing_eagerly())
```

**Comment by Saduf2019** [comment]
@chuanli11 
I ran the code shared above on tf 2.2 please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/0d7560831307c0fd1082231651123fef/untitled187.ipynb) and confirm if it replicates the issue reported else please provide complete code such that we could replicate the issue or share a colab gist with the error for us to analyse.

**Comment by chuanli11** [comment]
@Saduf2019 Thanks for looking into this. 
* This is the [gist](https://colab.research.google.com/drive/1GHl4xSQCidFNZOgwkC5FPm52y6voiweq?usp=sharing) that reproduces the error. One need to choose GPU accelerator in the runtime setting.
* This is the [gist](https://colab.research.google.com/drive/1StQwZ8S9BBTtbiVDvHxcEO7f-lRn4Zzn?usp=sharing) that successfully run without `disable_eager_execution`
* This is the [gist](https://colab.research.google.com/drive/1ijlB3cQp_HVTXYxbcemgwUVqjNMH84m8?usp=sharing) that successfully run without `MirrorStrategy`
* This is the [gist](https://colab.research.google.com/drive/19mCtWGkO6FNEEFaOI6KD5WYr1yEoiHI5?usp=sharing) that runs successfully with `model.fit` + `disable_eager_execution` + `MirrorStrategy`

**Comment by y31101996** [comment]
Hi,
I am using a GAN model on environment Tensorflow 2.0 + CUDA 10.0 + cuDNN 7.6.5
and I have encountered the same issue
but neither two suggestions solve my problem

Before using `MirrorStrategy`
my code can work fine under both eager execution and lazy execution

After I add `MirrorStrategy`

- with eager execution
it causes following error on the line with `train_on_batch`
`TypeError: Variable is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.`

- disable eager execution
it causes AssertionError on the line with `train_on_batch`

I've try your second suggestion
but replacing `model.train_on_batch()` by `model.fit()` doesn't work for me
it still causes AssertionError

**Comment by chuanli11** [comment]
@y31101996, thanks for sharing the information. 
For the record, I wasn't proposing suggestions. My examples are extra context and I hope someone can educate me what is going on here.

**Comment by Saduf2019** [comment]
I am able to replicate the error gist shared, please find it [here](https://colab.sandbox.google.com/gist/Saduf2019/195a7e232c7591da1d3e2304aed56239/untitled190.ipynb)

**Comment by karmel** [comment]
If you are using Distribution Strategies, it is best to use the full TFv2 functionality and enable eager mode. In particular, using train_on_batch with Dist Strat and eager disabled is not supported.
