### ISSUE TITLE
Document checkpoint file format

### ISSUE THREAD

**Issue by malmaud** [tensorflow/tensorflow#3967]
Hi,
As far I can find, the internal structure of checkpoint files is not documented on tensorflow.org. I'm trying to write bindings to TensorFlow which can load checkpoints without making use of the Python API, so I was wondering if that information is available somewhere.

**Comment by vrv** [comment]
At the moment the checkpoint format isn't public for a good reason: it's changing to a more efficient format and remains an internal implementation detail of the Saver class in python.  But as part of this improvement, we'll likely make the checkpoint format public through some C++ helper classes, and a C-API to go with it.

@concretevitamin can offer more insight.

**Comment by concretevitamin** [comment]
+1 to what @vrv has said.  For now, you could use the [`TensorSliceReader::GetTensor()`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/util/tensor_slice_reader.h#L102) function to obtain a tensor from a checkpoint.

**Comment by malmaud** [comment]
Thanks guys.
