### ISSUE TITLE
Infinite Training

### ISSUE THREAD

**Issue by Shubhamai** [tensorflow/tensorflow#39675]
Code is : 
```
import tensorflow as tf

datagen = tf.keras.preprocessing.image.ImageDataGenerator(
    rescale=1./255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True, validation_split=0.2)

train_generator = datagen.flow_from_directory(
    directory="/content/dataset/data",
    target_size=(224, 224),
    color_mode="rgb",
    batch_size=2,
    class_mode="binary",
    seed=42,
    subset='training'
)

valid_generator = datagen.flow_from_directory(
    directory="/content/dataset/data",
    target_size=(224, 224),
    color_mode="rgb",
    batch_size=2,
    class_mode="binary",
    seed=42, subset='validation'
)

model = tf.keras.models.Sequential([
  tf.keras.layers.Conv2D(2, 5, activation='relu', input_shape=(224, 224, 3)),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit_generator(train_generator, epochs=1)
```

Output is 
```
799/Unknown - 231s 289ms/step - loss: 0.0250 - accuracy: 0.9981
```

Issue:
The model is training infinite it isn't stopping, I also stop running the cell and run the evaluation in test data, it is evaluating for infinite.  I have a total of 15 images in two classes. 

I am using tensorflow version `2.2.0` and keras version `2.3.0-tf` and running the code on google colab. Thanks.

**Comment by ravikyram** [comment]
@Shubhamai 

Request you to share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by mfiro** [comment]
I am experiencing the same thing. I wasn't sure if it is an expected behaviour, because using steps_per_epoch in fit method solves the issue.

**Comment by Shubhamai** [comment]
I am not sure why this happened before @ravikyram .When I was making another colab notebook to share your code and run the code, everything works perfectly, I check the versions and they were the same. Anyway, the issue is now solved for me and Thanks for the assistance 🙂.
