### ISSUE TITLE
tf.keras.callbacks.ModelCheckpoint only saves weights although save_weights_only=False

### ISSUE THREAD

**Issue by bapos** [tensorflow/tensorflow#39679]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes, although very minimal
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 16.04.5 LTS 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
Plain pip install
- TensorFlow version (use command below):
2.2.0
- Python version:
3.7.3
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
N/A
- CUDA/cuDNN version:
N/A, reproducible with CPU
- GPU model and memory:
N/A

**Describe the current behavior**
tf.keras.callbacks.ModelCheckpoint only saves weights for a subclassed model, although save_weights_only=False.

**Describe the expected behavior**
tf.keras.callbacks.ModelCheckpoint saves the full model as a tf.SavedModel.

This behaviour is expected based on the API docs:
>  save_weights_only | if True, then only the model's weights will be saved (model.save_weights(filepath)), else **the full model is saved (model.save(filepath))**.`
https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/ModelCheckpoint

And model.save:
> save_format | Either 'tf' or 'h5', indicating whether to save the model to **Tensorflow SavedModel** or HDF5. **Defaults to 'tf'** in TF 2.X, and 'h5' in TF 1.X.`
https://www.tensorflow.org/api_docs/python/tf/keras/Model#save

**Standalone code to reproduce the issue**
````
from pathlib import Path
from typing import Optional

import os
import tempfile
import tensorflow as tf

_TENSOR = tf.ones((10, 1, 1, 3))


class SomeModel(tf.keras.models.Model):
    def call(
        self,
        inputs: tf.Tensor,
        training: Optional[bool] = None,
        mask: Optional[tf.Tensor] = None,
    ) -> tf.Tensor:
        return inputs


def _get_model() -> SomeModel:
    model = SomeModel()
    model.compile()
    model.fit(x=_TENSOR, y=_TENSOR)
    return model


def _unexpected_failure() -> None:
    """
    The minimal working example to reproduce the bug.
    tf.keras.callbacks.ModelCheckpoint has a bug: it only saves weights, while the expected
    behaviour is that it saves using tf.SavedModel.
    """
    model = _get_model()
    with tempfile.TemporaryDirectory() as save_dir:
        model_save_dir = os.path.join(save_dir, "model")
        model.fit(
            x=_TENSOR,
            y=_TENSOR,
            callbacks=[
                tf.keras.callbacks.ModelCheckpoint(
                    model_save_dir, save_weights_only=False
                )
            ],
        )

        # We can see that only the weights are saved. This prints e.g.:
        # /tmp/tmpvuciirc6/model.data-00000-of-00001 contains: []
        # /tmp/tmpvuciirc6/model.index contains: []
        # /tmp/tmpvuciirc6/checkpoint contains: []
        print(_list_dir_content(Path(save_dir)))

        # Restoring throws an error:
        # Traceback (most recent call last):
        #  ............
        #   File "[...]/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 189, in load_model
        #     loader_impl.parse_saved_model(filepath)
        #   File "[...]/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 113, in parse_saved_model
        #     constants.SAVED_MODEL_FILENAME_PB))
        # OSError: SavedModel file does not exist at: /tmp/tmpvuciirc6/{saved_model.pbtxt|saved_model.pb}
        saved_model = tf.keras.models.load_model(save_dir, compile=False)


def _ok() -> None:
    """
    This shows that the same model can be saved as a tf.SavedModel just fine.
    model.save() works fine: it saves as a tf.SavedModel.
    """
    model = _get_model()
    with tempfile.TemporaryDirectory() as save_dir:
        model_save_dir = os.path.join(save_dir, "model")
        model.save(model_save_dir)

        # We can load the model again and run inference:
        saved_model = tf.keras.models.load_model(model_save_dir, compile=False)
        # We can run inference from the loaded model.
        saved_model(_TENSOR)

        # We can see that the model is saved as a tf.SavedModel. This print e.g.:
        # /tmp/tmp3f6w2q5i/model_regular_save contains: [PosixPath('/tmp/tmp3f6w2q5i/model/variables'), PosixPath('/tmp/tmp3f6w2q5i/model/assets'), PosixPath('/tmp/tmp3f6w2q5i/model/saved_model.pb')]
        print(_list_dir_content(Path(save_dir)))


class ModelCheckpointWorkAround(tf.keras.callbacks.ModelCheckpoint):
    def set_model(self, model: tf.keras.models.Model) -> None:
        # Work around, so that the if at
        # https://github.com/tensorflow/tensorflow/blob/1186e3f2098793952aa82bf356dfe51b967fb26c/tensorflow/python/keras/callbacks.py#L1189
        # is skipped, so that self.save_weights_only remains False.
        self.model = model


def _workaround() -> None:
    """
    A workaround that shows how the bug may be fixed.
    Saving and restoring using ModelCheckpointWorkAround works fine, the if at
    https://github.com/tensorflow/tensorflow/blob/1186e3f2098793952aa82bf356dfe51b967fb26c/tensorflow/python/keras/callbacks.py#L1189
    is circumvented.
    """
    model = _get_model()
    with tempfile.TemporaryDirectory() as save_dir:
        model_save_dir = os.path.join(save_dir, "model")
        model.fit(
            x=_TENSOR,
            y=_TENSOR,
            callbacks=[
                ModelCheckpointWorkAround(model_save_dir, save_weights_only=False)
            ],
        )

        # We can see the model is saved as a tf.SavedModel. This prints e.g.:
        # /tmp/tmpxmdhsfi_/model contains: [PosixPath('/tmp/tmpxmdhsfi_/model/variables'), PosixPath('/tmp/tmpxmdhsfi_/model/assets'), PosixPath('/tmp/tmpxmdhsfi_/model/saved_model.pb')]
        print(_list_dir_content(Path(save_dir)))

        # Running inference from a restored model works fine:
        saved_model = tf.keras.models.load_model(model_save_dir, compile=False)
        saved_model(_TENSOR)


def _list_dir_content(path: Path) -> str:
    return "\n".join(
        [f"{elem} contains: {list(elem.glob('*'))}" for elem in path.glob("*")]
    )


if __name__ == "__main__":
    _ok()
    _workaround()
    _unexpected_failure()
````

**Other info / logs**
I **suspect** the if block at https://github.com/tensorflow/tensorflow/blob/1186e3f2098793952aa82bf356dfe51b967fb26c/tensorflow/python/keras/callbacks.py#L1189 can simply be removed, and it is a remnant from the past when tf.SavedModel did not exist yet, and H5 was the only option. Perhaps the author, @fchollet can confirm?

My suspicion is based on the fact that the provided work around works and also based on the error message here: https://github.com/tensorflow/tensorflow/blob/35b03590f6bcd5869355ce8a0c3a995fd23ecdd7/tensorflow/python/keras/saving/save.py#L123

**Comment by ravikyram** [comment]
I have tried in colab with TF verison 2.2 and was able to reproduce the issue.Please,find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/a9cc4ee8dfa095dbf4792c24d2e5b3a2/untitled912.ipynb).Thanks!

**Comment by thusinh1969** [comment]
Gents has this been fixed please :( ... !!!

**Comment by saikumarchalla** [comment]
Issue still exists in TF 2.6 as well. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/446a5b3a9bbaafd3dba457d148202479/nighly.ipynb).Thanks!

**Comment by AlbertoMQ** [comment]
Also happening on TF 2.4.1

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
