### ISSUE TITLE
Cloud TPU not connecting

### ISSUE THREAD

**Issue by caffeine-lab** [tensorflow/tensorflow#39674]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I am trying to run a custom script in Google cloud TPUs using TPUStratagy.
Whenever I try to start the TPUs to work it is hung up on connect to the cluster and not proceeding to the next step

2020-05-19 09:43:27.869431: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-05-19 09:43:27.875081: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2300000000 Hz
2020-05-19 09:43:27.875376: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4630540 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-19 09:43:27.875476: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-19 09:43:27.882332: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> node-1:8470}
2020-05-19 09:43:27.882369: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:43986}

After this, it is not going any further or showing any error msgs.

*Code to connect to TPU*

`
cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='grpc://node-1')
tf.config.experimental_connect_to_cluster(cluster_resolver)
tf.tpu.experimental.initialize_tpu_system(cluster_resolver)
strategy = tf.distribute.experimental.TPUStrategy(cluster_resolver)
`

Instance name (VM) : instance - 1
Zone : us-central1-b
TPU name = node-1
**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@caffeine-lab,
In order to expedite the trouble-shooting process, could you please provide a minimal code sample to reproduce the issue reported here. Thanks!

**Comment by jysohn23** [comment]
Instead of:
```
cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='grpc://node-1')
````

Can you run:
```
cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='node-1')
```

If you're going to use `grpc://` you need to provide it a gprc endpoint like `grpc://10.0.0.2:8470` where `10.0.0.2` would be the TPU internal IP address.

**Comment by caffeine-lab** [comment]
> Instead of:
> 
> ```
> cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='grpc://node-1')
> ```
> 
> Can you run:
> 
> ```
> cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='node-1')
> ```
> 
> If you're going to use `grpc://` you need to provide it a gprc endpoint like `grpc://10.0.0.2:8470` where `10.0.0.2` would be the TPU internal IP address.

@jysohn23 I did try that, And It was still not connecting. 
I tried all the following, and still no success.
```
cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='node-1')
```
```
cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver('node-1')
```

**Comment by caffeine-lab** [comment]
It was an internal TPU problem, I solved it by creating a new Google Cloud project.
