### ISSUE TITLE
[TF 2.2 API docs] tf.keras.applications.resnet_v2.preprocess_input docs Returns paragraph is misleading

### ISSUE THREAD

**Issue by RaibekTussupbekov** [tensorflow/tensorflow#39677]
[https://www.tensorflow.org/api_docs/python/tf/keras/applications/resnet_v2/preprocess_input](url)
The documentation says in the 'Returns' paragraph that
> The images are converted from RGB to BGR, then each color channel is zero-centered with respect to the ImageNet dataset, without scaling. 

However, according to [the function definition](https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/keras/applications/resnet_v2.py#L125-L139) it's not true anymore  since the **mode parameter** can't be set and it is always equal to **'tf'**.

Therefore, this docs part must be corrected to 
>will scale pixels between -1 and 1,  sample-wise

**Comment by jvishnuvardhan** [comment]
@RaibekTussupbekov This was already resolved. Please check the page [here](https://www.tensorflow.org/api_docs/python/tf/keras/applications/resnet_v2/preprocess_input).

Please verify once and close the issue. Thanks!
