### ISSUE TITLE
Unclear Documentation for Keras SavedModel format

### ISSUE THREAD

**Issue by Ben-Epstein** [tensorflow/tensorflow#39689]
In the [documentation](https://www.tensorflow.org/guide/keras/save_and_serialize#savedmodel_format) for keras for saving a model, it states that you can save a model in a SavedModel format by passing in a name for a directory. This creates a directory with a pb file and 2 other folders containing assets and weights. 

This doesn't seem to me to be a true SavedModel format as it's not a single pb file. Is there documentation explaining how to create the single pb that can be used for loading SavedModels (like Tensorflow Java or DL4J)? Loading doesn't seem to be possible from a directory, only a SavedModel pb file.

Maybe I'm missing something? Thank you!

**Comment by sushantag9** [comment]
Though `model.save() or tf.keras.models.save_model()` 
creates a folder containing model file along with assets and variables folder. This is the new and updated method of saving the model.
This saves the complete model including the weights, optimizer info and the information used using the compilation of model. 
But,
you can save it in a singhle file by using
`model.save('model_name',format='h5') or model.save('model_name.h5')`
or
`model.save('model_name.pb')`

**Comment by Ben-Epstein** [comment]
@sushantag9  `model.save('model_name.pb')` does not save a single pb file. It creates a folder `model_name.pb` that contains the same contents.

And h5 is considered old and not recommended by the [Tensorflow Docs](https://www.tensorflow.org/guide/keras/save_and_serialize#whole-model_saving_loading)

Is there not a way to create a single protobuf file from a keras model?

**Comment by sushantag9** [comment]
# Save to ./model/tf_model.pb `
tf.train.write_graph(frozen_graph, "model", "tf_model.pb", as_text=False)`
In TF 2.0 there is no way to save it directly to a single file.
The above code can be used to save the graph but by using older version of TF

**Comment by ravikyram** [comment]
@Ben-Epstein 

Please, go through the[ link](https://www.tensorflow.org/tutorials/keras/save_and_load#save_the_entire_model) and see if it helps you.Thanks!

**Comment by Ben-Epstein** [comment]
@ravikyram  Thank you for the link. That's the source of my confusion, is it possible to save the model as a single .pb file? It seems like it must be a directory.

**Comment by jvishnuvardhan** [comment]
@Ben-Epstein I think the confusion is between `Freeze graph` API and `SavedModel` API. `Freeze graph` API is to freeze tensorflow graph and related files in a session and serve it for inference. However, `Freeze graph` API works only in TF1.x and is deprecated in TF2.x. In TF2.x, the primary export format is SavedModels so APIs are built to directly support SavedModels. So, you can use `SavedModel` for saving model and serving for inference.
  

> Loading doesn't seem to be possible from a directory, only a SavedModel pb file.
The *.pb file contains only the Tensorflow graph of your model. So, loading only graph doesn't work as it requires `Assets` and `variables` for tuning the saved model and inference. Please check [here](https://www.tensorflow.org/guide/saved_model) for more details on `SavedModel` API.

**Comment by Ben-Epstein** [comment]
Understood. My use case requires a single object (not a directory) so I will have to stick with the older h5 format. Thanks for the help!
