### ISSUE TITLE
Unresolved external symbol C ++ version

### ISSUE THREAD

**Issue by wangwenchao-job** [tensorflow/tensorflow#39686]
## Operating environment
windows 10
vs 2019
tensorflow 2.1 C++

## error
Compile the C ++ version of tensorflow 2.1, and report unresolved external symbols when using it
![image](https://user-images.githubusercontent.com/57739867/82340969-6c042d00-9a22-11ea-9e77-a8778c52b04e.png)

## my code
#include <sstream>
#include <iostream>

#include "tensorflow/cc/ops/standard_ops.h"
#include <tensorflow/core/framework/graph.pb.h>
#include "tensorflow/core/graph/default_device.h"
#include "tensorflow/core/graph/graph_def_builder.h"
#include "tensorflow/core/lib/core/threadpool.h"
#include "tensorflow/core/lib/strings/stringprintf.h"
#include "tensorflow/core/platform/init_main.h"
#include "tensorflow/core/platform/logging.h"
#include "tensorflow/core/platform/types.h"
#include "tensorflow/core/public/session.h"
#include "tensorflow/core/protobuf/meta_graph.pb.h"
#include "tensorflow/core/framework/graph.pb.h"
#include "tensorflow/core/public/session.h"
#include "tensorflow/core/framework/tensor.h"
#include "tensorflow/cc/saved_model/loader.h"

#include <fstream>
#include <iostream>
#include <string>
#include <vector>
#include <stdlib.h>

#include "tensorflow/cc/ops/const_op.h"
#include "tensorflow/cc/ops/standard_ops.h"
#include "tensorflow/core/framework/tensor.h"
#include "tensorflow/core/graph/default_device.h"
#include "tensorflow/core/graph/graph_def_builder.h"
#include "tensorflow/core/lib/core/errors.h"
#include "tensorflow/core/lib/core/stringpiece.h"
//#include "tensorflow/core/lib/core/threadool.h"
#include "tensorflow/core/lib/io/path.h"
#include "tensorflow/core/lib/strings/stringprintf.h"
#include "tensorflow/core/platform/env.h"
#include "tensorflow/core/platform/init_main.h"
#include "tensorflow/core/platform/logging.h"
#include "tensorflow/core/platform/types.h"
#include "tensorflow/core/public/session.h"
#include "tensorflow/core/util/command_line_flags.h"

using namespace tensorflow;
using tensorflow::Flag;
using tensorflow::Status;
using tensorflow::string;
using tensorflow::Tensor;

using std::string;

//using namespace tensorflow;

int main(int argc, char argv[]) {
	std::string model_path = R"(E:/pro_vs2019/test_vs2019/tf_model/)";

	Session* session;
	SessionOptions options;
	options.config.mutable_gpu_options()->set_visible_device_list("0"); //设置使用的gpu
	options.config.mutable_gpu_options()->set_allow_growth(true); //设置GPU内存自动增长
	TF_CHECK_OK(NewSession(options, &session));//创建新会话Session
	GraphDef graphdef; //Graph Definition for current model
	TF_CHECK_OK(ReadBinaryProto(Env::Default(), model_path, &graphdef)); //从pb文件中读取图模型;
	TF_CHECK_OK(session->Create(graphdef)); //将模型导入会话Session中;

	//tensorflow::Status status;
	//// SessionOptions sessionOptions;
	//// RunOptions runOptions;
	//// SavedModelBundle bundle;

	//// load everything
	//// status = LoadSavedModel(sessionOptions, runOptions, model_path, { "serve" }, &bundle);

	//GraphDef graphdef;

	//status = ReadBinaryProto(Env::Default(), model_path, &graphdef);

	//if (!status.ok()) {
	//	std::cout << status.ToString() << std::endl;
	//	return -1;
	//}
	//else std::cout << "Succesfully have model loaded: " << model_path << std::endl;

	return 0;
}

**Comment by mihaimaruseac** [comment]
Please:

1. fill in issue template
1. minimize your code to only have the needed lines to reproduce the issue
1. use proper markdown formatting around code and error blocks so it is readable
