### ISSUE TITLE
Wrong with converted tflite model

### ISSUE THREAD

**Issue by wwdok** [tensorflow/tensorflow#39688]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows10
- TensorFlow installed from (source or binary):pip install
- TensorFlow version (or github SHA if from source):1.13.1
 I downloaded [ssd_mobilenet_v2_quantized_coco](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03.tar.gz) and tried to convert it to tflite format using following script:

```
import os
import tensorflow as tf
print(tf.__version__)
graph_def_file = "E:/Tensorflow_detection_model_zoo/ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03/tflite_graph.pb"
input_arrays=["normalized_input_image_tensor"]
output_arrays=['TFLite_Detection_PostProcess', 'TFLite_Detection_PostProcess:1', 'TFLite_Detection_PostProcess:2', 'TFLite_Detection_PostProcess:3']
input_shape={"normalized_input_image_tensor": [1, 300, 300, 3]}

converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays, input_shape)
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter.allow_custom_ops = True
converter.post_training_quantize = True
converter.inference_type = tf.lite.constants.QUANTIZED_UINT8
input_arrays = converter.get_input_arrays()
converter.quantized_input_stats = {input_arrays[0]: (0., 1.)}  # mean, std_dev
tflite_uint8_model = converter.convert()
open("uint8_model_converted_from_"+os.path.basename(os.path.dirname(graph_def_file))+".tflite", "wb").write(tflite_uint8_model)
```
So i got the output file : **uint8_model_converted_from_ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03.tflite**.
Then i used the following script to test this tflite model:
```
import numpy as np
import os
import tensorflow as tf
import cv2 as cv
from PIL import Image
print(tf.__version__)
print(os.getcwd())

interpreter = tf.lite.Interpreter(model_path="uint8_model_converted_from_ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03.tflite")
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
print("input_details : ", input_details)
print("output_details : ", output_details)

image = cv.imread("test_images/traffic.png")
resize_img = cv.resize(image, (300, 300), interpolation=cv.INTER_CUBIC)
reshape_image = resize_img.reshape(300, 300, 3)
image_np_expanded = np.expand_dims(reshape_image, axis=0)
image_np_expanded = image_np_expanded.astype('uint8')
interpreter.set_tensor(input_details[0]['index'], image_np_expanded) 
interpreter.invoke()

output_data = interpreter.get_tensor(output_details[0]['index'])
output_data_1 = interpreter.get_tensor(output_details[1]['index'])
output_data_2 = interpreter.get_tensor(output_details[2]['index'])
output_data_3 = interpreter.get_tensor(output_details[3]['index'])

original_image_height, original_image_width, _ = image.shape
detect_image = cv.rectangle(image,
                            (int(output_data[0][0][1]*original_image_width),  
                             int(output_data[0][0][0]*original_image_height)),
                            (int(output_data[0][0][3]*original_image_width),
                             int(output_data[0][0][2]*original_image_height)),
                            (0, 255, 0), 3)
Image.fromarray(detect_image).save('test_result.png')
print(original_image_width)
print(int(output_data[0][0][3]*original_image_width))
print(original_image_height)
print(int(output_data[0][0][2]*original_image_height))
cv.imshow('detect_result', detect_image)
cv.waitKey(0)
```
But after i run this script, pycharm report this error:
![YIOczF.png](https://s1.ax1x.com/2020/05/19/YIOczF.png)
Obviously the shape is array(**[1, 0, 4]**) which is unnormal, the correct one should be array([**1, 10, 4]**) where  10 means output **10 classes**. So where is error come from ? and how to fix it ?

**Comment by amahendrakar** [comment]
Was able to reproduce the issue. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/68352df5fa8d2bfa8a79117a88aa9dc7/39688.ipynb). Thanks!

**Comment by jdduke** [comment]
@srjoglekar246 could you take a look?

**Comment by jdduke** [comment]
Actually, 1.13.1 is quite old, can you please try with the latest release (2.2.0)?

**Comment by jdduke** [comment]
Ah sounds like it still repros w/ the latest nightly.

**Comment by srjoglekar246** [comment]
@wwdok Can you check with the following converter parameters:

```
converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays, input_shape)
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS]
converter.allow_custom_ops = True
# converter.post_training_quantize = True
converter.inference_type = tf.lite.constants.QUANTIZED_UINT8
input_arrays = converter.get_input_arrays()
converter.quantized_input_stats = {input_arrays[0]: (128.0, 128.0)}  # mean, std_dev
tflite_uint8_model = converter.convert()
```

You don't need `post_training_quantize` since the model is already quantized. And the mean & std_dev for converting quantized SSD models is 128, 128 as mentioned [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md#running-on-mobile-with-tensorflow-lite)

**Comment by jvishnuvardhan** [comment]
@wwdok Thanks @srjoglekar246 It is working as expected. Please take a look at the [gist](https://colab.research.google.com/gist/jvishnuvardhan/321551f11317d0789027fab2f63186ff/ssd_mobilenet_quantized_model_tflite_converter.ipynb). I tried with `tf-nightly` but you could try `TF1.15.2` also.

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by wwdok** [comment]
@srjoglekar246 @jvishnuvardhan @jdduke @amahendrakar .Thanks everyone ! Now it works correctly !
