### ISSUE TITLE
Different SHA256 for mkl_dnn

### ISSUE THREAD

**Issue by cxyanhk** [tensorflow/tensorflow#39696]
in [tensorflow/workspace.bzl](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl):
`tf_http_archive(
        name = "mkl_dnn",
        build_file = clean_dep("//third_party/mkl_dnn:mkldnn.BUILD"),
        sha256 = "31e78581e59d7e60d4becaba3834fc6a5bf2dccdae3e16b7f70d89ceab38423f",
        strip_prefix = "mkl-dnn-0.21.3",
        urls = [
            "https://storage.googleapis.com/mirror.tensorflow.org/github.com/intel/mkl-dnn/archive/v0.21.3.tar.gz",
            "https://github.com/intel/mkl-dnn/archive/v0.21.3.tar.gz",
        ],
    )`
When the mkl_dnn is downloaded from the first url( "https://storage.googleapis.com/mirror.tensorflow.org/github.com/intel/mkl-dnn/archive/v0.21.3.tar.gz"), the SHA256  is 31e78581e59d7e60d4becaba3834fc6a5bf2dccdae3e16b7f70d89ceab38423f , which is right.
But when the mkl_dnn is downloaded from the second url(https://github.com/intel/mkl-dnn/archive/v0.21.3.tar.gz), the SHA256 is a0211aeb5e7dad50b97fa5dffc1a2fe2fe732572d4164e1ee8750a2ede43fbec, which will fail to compile.
When I unzip the compressed package downloaded from the second url, its directory is oneDNN 0.21.3. But the files in them are exactly the same. Maybe this is the reason. 
hope you can check it and fix it. Thanks.

**Comment by mihaimaruseac** [comment]
See #38517 and #38671

**Comment by yongtang** [comment]
@mihaimaruseac @cxyanhk The issue is the renaming of mkl-dnn to oneDNN, so GitHub re-archives the package (with different directory). The old link in mkl_dnn now is an alias of oneDNN which has a different top-level directory inside the archive.

Create a PR #39725 for the fix.
