### ISSUE TITLE
TextLineDataset could be more expressive

### ISSUE THREAD

**Issue by Ceceu** [tensorflow/tensorflow#39694]
TextLineDataset could be more expressive. For instance, it could have more arguments like:

```python
train_dataset = tf.data.TextLineDataset(
                                     file_path, # dataset file path
                                     format, # file format: jsonl, csv, etc.
                                     fields # a set of colums
)
```

It would also be incredible if there was a way to indicate how to tokenize each of the fields.

**Comment by ravikyram** [comment]
@Ceceu 

Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!

**Comment by jsimsa** [comment]
`TextLineDataset` is for reading text lines. For different types of format, there are dedicated tf.data sources, such as [tf.data.experimental.CsvDataset](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/experimental/ops/readers.py#L603) or [JsonIODataset](https://github.com/tensorflow/io/blob/master/tensorflow_io/core/python/ops/json_dataset_ops.py) from the `tensorflow/io` repository.
