### ISSUE TITLE
tf.lite.experimental.load_delegate throws exception with try except block

### ISSUE THREAD

**Issue by leeyeetonn** [tensorflow/tensorflow#39692]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04, macOS 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:NA
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de 2.1.0 & v2.2.0-0-g2b96f3662b 2.2.0
- Python version:3.7.6
- Bazel version (if compiling from source):NA
- GCC/Compiler version (if compiling from source):NA
- CUDA/cuDNN version:NA
- GPU model and memory:NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Currently `tf.lite.experimental.load_delegate` throws `OSError` when the passed in library doesn't exist. However when use it with `try except` block, it will throw 

> Exception ignored in: <bound method Delegate.__del__ of <tensorflow.lite.python.interpreter.Delegate object at 0x7f6fc561db00>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter.py", line 125, in __del__
    if self._library is not None:
        AttributeError: 'Delegate' object has no attribute '_library'

**Describe the expected behavior**
Exception should be caught with `try except` block.
**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Without `try except` block, the behavior looks fine
```python
import tensorflow as tf

tf.lite.experimental.load_delegate('some invalid lib')  # expect an exception
```
With `try except` block, it throws an exception which can't be caught.
```python
import tensorflow as tf
try:
    tf.lite.experimental.load_delegate('some invalid lib')
except Exception as e:
    # do something to handle exception
    pass
```
>Exception ignored in: <bound method Delegate.__del__ of <tensorflow.lite.python.interpreter.Delegate object at 0x7f6fc561d518>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter.py", line 125, in __del__
    if self._library is not None:
AttributeError: 'Delegate' object has no attribute '_library'

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/ac3dd9b17766586f192533578fd101c0/untitled190.ipynb)

**Comment by srjoglekar246** [comment]
Nupur, could you take a look?

**Comment by ymodak** [comment]
You may try with;
```python
import tensorflow as tf
try:
    tf.lite.experimental.load_delegate('some invalid lib')
except tf.errors.InvalidArgumentError as e:
    # do something to handle exception
    pass
```
