### ISSUE TITLE
Multiple step predict seems to be wrong

### ISSUE THREAD

**Issue by Lay4U** [tensorflow/tensorflow#39706]
![20200520_163852](https://user-images.githubusercontent.com/31833270/82420430-aa4d2b00-9aba-11ea-9ca2-160fba8afd6c.png)

The original data of x_test has a non-linear random walk property,

but the newly predicted 20 values have a linear shape.

Clearly, did I make the wrong prediction?

you can see full source here
https://colab.research.google.com/drive/1kk24KjpZQEZpdlBxr4D4DO-IGHJ0439v?usp=sharing

and my tf version is 2.1.0 and python 3.7.7
![image](https://user-images.githubusercontent.com/31833270/82441869-9238d400-9ad9-11ea-9ca0-1d17d649e00f.png)

**Comment by Saduf2019** [comment]
@Lay4U 
I ran the code shared and face a different error, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/9a681b694058b0b0b4965fd2aa8003d6/untitled192.ipynb)

**Comment by Lay4U** [comment]
@Saduf2019 
https://colab.research.google.com/drive/1kk24KjpZQEZpdlBxr4D4DO-IGHJ0439v?usp=sharing
is working?

**Comment by Saduf2019** [comment]
I am able to replicate the gist shared, please find the replicated [gist here](https://colab.sandbox.google.com/gist/Saduf2019/f88177e2b310971932652df0156f4f6f/untitled193.ipynb)

**Comment by Lay4U** [comment]
@Saduf2019 
I tried colab, tf2.1 and tf2.2 but problem is same

I don't think this is a version issue.

**Comment by Saduf2019** [comment]
I am able to replicate the gist shared, please find the replicated [gist here](https://colab.sandbox.google.com/gist/Saduf2019/f88177e2b310971932652df0156f4f6f/untitled193.ipynb)

**Comment by Lay4U** [comment]
> I am able to replicate the gist shared, please find the replicated [gist here](https://colab.sandbox.google.com/gist/Saduf2019/f88177e2b310971932652df0156f4f6f/untitled193.ipynb)

I don't under stand your mean

if I do translate with google

"You can duplicate the shared point. Find the cloned point here."

is my colab page wrong?

**Comment by Lay4U** [comment]
Was my question forgotten? or Is it being solved?

**Comment by omalleyt12** [comment]
@Lay4U Thanks for the issue!

This just seems like a Model quality issue. Here is a simple example showing that `predict` is working correctly:

```python
import numpy as np
import tensorflow as tf

class MyLayer(tf.keras.layers.Layer):
  def build(self, _):
    self.v = tf.Variable(2.)

  def call(self, x):
    return self.v * x

model = tf.keras.Sequential([MyLayer()])
model.compile('sgd', 'mse')
model.predict(x=np.arange(10).astype(np.float32))
```

**Comment by Lay4U** [comment]
@omalleyt12 
There is something I don't understand. you create a MyLayer and multiply it by 2, but I know that the actual lstm doesn't work like this. In other words, I can't find a connection between your answer and my question. Could you please tell me the Full source for my question if you possible?
