### ISSUE TITLE
GatherV2Grad prints a deprecation warning

### ISSUE THREAD

**Issue by bparr** [tensorflow/tensorflow#39701]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Ubuntu 20.04
- TensorFlow installed from: binary (from pip)
- TensorFlow version: 2.2.0
- Python version: 3.7

**Describe the current behavior**

GatherV2Grad prints a deprecation warning when used. The warning is from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/array_grad.py#L644

> WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/tensorflow/python/ops/array_grad.py:644: _EagerTensorBase.cpu (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
> Use tf.identity instead.

This issue is similar to https://github.com/tensorflow/tensorflow/issues/32049

**Describe the expected behavior**

No deprecation warning.

**Standalone code to reproduce the issue**

```python
import tensorflow as tf

class Model(tf.keras.Model):
  def __init__(self,):
    super(Model, self).__init__()
    self.layer = tf.keras.layers.Dense(100)
  def call(self, x):
    return self.layer(x)

model = Model()
model.build((1,2))
weights = model.trainable_variables

with tf.GradientTape(persistent=True) as tape:
    output = model(tf.zeros([1,2]))

gradients = tape.jacobian(output, weights, experimental_use_pfor=False)
```

This code is based on https://github.com/tensorflow/tensorflow/issues/36227, which was about something else, but does also show the deprecation warning.

**Comment by amahendrakar** [comment]
@bparr,
To suppress the warning, add these lines of code to your program
```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 
import tensorflow as tf
```
Please check [this gist](https://colab.research.google.com/gist/amahendrakar/d60beb96146856cbbb00fca1156effe5/39701.ipynb) for reference. Thanks!

**Comment by yongtang** [comment]
Added a PR #39731 to remove the deprecation message.
