### ISSUE TITLE
`Model.predict(...)` seems incapable of handling two inputs when using the tf.data-API

### ISSUE THREAD

**Issue by hohl** [tensorflow/tensorflow#39708]
**System information**
- Have I written custom code: *Yes, see sample below.*
- OS Platform and Distribution: *Ubuntu Server 20.04*
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): *2.2.0*
- Python version: *3.8.2*
- CUDA version: *10.1*
- GPU model and memory: *NVIDIA RTX 2080 Ti*

---

**Describe the current behavior**

While developing a model which expects two inputs (`X1` and `X2`) and generates one output (`y`), I noticed that `model.predict(...)` does not work as expected together with the `tf.data`-API.

In a simpler example, a model with only one input (`X`) can be used to make predictions by calling `y_pred = model.predict(X)`. Everything behaves as one would expected. You could also call `predict` on the full training set such as a `tf.data.Dataset` which consists of both inputs and expected outputs (for ex.: `Xy = tf.data.Dataset.zip((X, y_true))` followed by `y_pred = model.predict(Xy)`).

But let's get back to the previous example with two inputs. The following sample too works as expected:

```
X = dataset = tf.data.Dataset.zip((X1, X2))
Xy = dataset = tf.data.Dataset.zip((X, y_true))
y_pred = model1.predict(Xy)
```

But the more realistic application of `predict` were one only passes the inputs (without the true labels), does result into a crash:

```
X12 = dataset = tf.data.Dataset.zip((X1, X2))
y_pred = model2.predict(X12)  # <- crash :,(
```

... with the following error message:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/hohl/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/hohl/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/hohl/projects/hohl.thesis/test.py", line 25, in <module>
    y_pred = model.predict(X)  # <- crashes
  File "/home/hohl/venvs/tf22/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 88, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/hohl/venvs/tf22/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1268, in predict
    tmp_batch_outputs = predict_function(iterator)
  File "/home/hohl/venvs/tf22/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/hohl/venvs/tf22/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 627, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/hohl/venvs/tf22/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 505, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/home/hohl/venvs/tf22/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/hohl/venvs/tf22/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/hohl/venvs/tf22/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2657, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/hohl/venvs/tf22/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/hohl/venvs/tf22/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/hohl/venvs/tf22/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AssertionError: in user code:
    /home/hohl/venvs/tf22/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:1147 predict_function  *
        outputs = self.distribute_strategy.run(
    /home/hohl/venvs/tf22/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/hohl/venvs/tf22/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/hohl/venvs/tf22/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    /home/hohl/venvs/tf22/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:1122 predict_step  **
        return self(x, training=False)
    /home/hohl/venvs/tf22/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:927 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /home/hohl/venvs/tf22/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py:717 call
        return self._run_internal_graph(
    /home/hohl/venvs/tf22/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py:899 _run_internal_graph
        assert str(id(x)) in tensor_dict, 'Could not compute output ' + str(x)
    AssertionError: Could not compute output Tensor("dense/Identity:0", shape=(None, 1), dtype=float32)
```

The following usage, on the hand, executes without any troubles:

```
X12 = dataset = tf.data.Dataset.zip((X1, X2))
X12y = dataset = tf.data.Dataset.zip((X12, y_true))
y_pred = model2.predict(X12y)  # <- fine :)
```

This way of usage works fine, so I guess in the previous example the model though I fed it inputs with labels instead of inputs consisting of two separate inputs. However, the latter example is a rather unrealistic usage for any real-word application. Once deployed you would not know the true labels, that's exactly why you would want to predict them.

---

**Describe the expected behavior**

I would always expect `predict` to work with `y_pred = model.predict(X)` independently of the number of inputs. 

I guess the support for also accepting a combined dataset (inputs and labels) as input can come handy when testing single-input models, but I would consider it as even far more important that `model.predict(X)` works for models with any number of inputs.

One more thing: if the current behaviour is supposed to stay this way, it would be very helpful if the error message gets a bit more self-explanatory and the above fact gets mentioned explicitly in the [`predict`-documentation](https://www.tensorflow.org/api_docs/python/tf/keras/Model#predict). It took me quite a while to figure out, why my model crashes with the ambiguous `AssertionError: Could not compute output` error message.

---

**Standalone code to reproduce the issue**

Here is the above sample as a single Python script which you can run to quickly reproduce the issue:

```
import tensorflow as tf
from tensorflow.keras import Input, Model, layers


def build_model():
    input1 = Input(shape=(1,), dtype=tf.float32)
    input2 = Input(shape=(1,), dtype=tf.float32)
    y = layers.Concatenate(axis=0)([input1, input2])
    y = layers.Dense(1)(y)
    return Model(inputs=[input1, input2], outputs=y)


def make_dummy_data():
    X1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([100, 1], dtype=tf.float32))
    X2 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([100, 1], dtype=tf.float32))
    X = tf.data.Dataset.zip((X1, X2))
    y_true = tf.data.Dataset.from_tensor_slices(tf.random.uniform([100, 1], dtype=tf.float32))
    return X, y_true


X, y_true = make_dummy_data()
Xy = tf.data.Dataset.zip((X, y_true))
model = build_model()
model.compile(loss='mse')
model.fit(Xy, batch_size=32)
y_pred = model.predict(X)  # <- crashes with: "AssertionError: Could not compute output ..."
#y_pred = model.predict(Xy)  # <- works
```

**Comment by ravikyram** [comment]
I have tried in colab with TF version in 2.2 ,2.3.0-dev20200519 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/58553b02bc7e9b7a69bdeb6533f50d91/untitled915.ipynb).Thanks!

**Comment by bhack** [comment]
You need to use `tf.data.Dataset.zip(((X1, X2),))`

**Comment by mohantym** [comment]
Hi @hohl! 
We are checking to see whether you still need help in this issue . Did you check with above [suggestion](https://github.com/tensorflow/tensorflow/issues/39708#issuecomment-851420069) yet? Thanks!

**Comment by hohl** [comment]
> Hi @hohl!
> We are checking to see whether you still need help in this issue . Did you check with above [suggestion](https://github.com/tensorflow/tensorflow/issues/39708#issuecomment-851420069) yet? Thanks!

Sorry, I can‘t tell you anymore what I did to work around. I probably used `zip` as suggested, but I’m not sure anymore as it‘s already over a year ago. But I for sure figured out something to get the job done (either `zip` or some way to avoid the issue in the first place.)

**Comment by mohantym** [comment]
Ok @hohl! Is this issue good to close then?

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
