### ISSUE TITLE
builtins.TypeError: Expected binary or unicode string, got 0

### ISSUE THREAD

**Issue by Sustrommings** [tensorflow/tensorflow#39709]
I am quite new to Tensorflow, so in summary I converted the pcap file into csv file and load it in the python, I have made a column named detectionnumber such that when the Info column contains the word "SYN" and "ACK",  or "RST", it will append the value into the column I have made. Then I managed to add the column named detection I have made into the csv file. But the problem lies when I try to get the csv file into the dataset, it keeps showing the error, what should I do to solve these issues?`
Here is the file: [data.zip](https://github.com/tensorflow/tensorflow/files/4656000/data.zip)

`import datetime
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow import feature_column
from tensorflow.keras import layers
import pandas as pd
import tensorflow_datasets as tfds
import os
import csv

file_path = '/home/root2001/Documents/PythonForMachineLearning/L05-Network-Packets'
file_training_full = pd.read_csv(file_path, sep='delimiter', header=None)

f = open(file_path)
csvf = csv.reader(f)

#for row in csvf:
    #print(row)

#Adds a column to each row, a row contain SYN ACK append 1, RST append 2, or else append 0
protocol1 = "SYN"
protocol2 = "ACK"
protocol3 = "RST"

detectionnumber = []
for row1 in csvf:
   if (protocol1 in row1[6] and protocol2 in row1[6] ):
      value = 1
      detectionnumber.append(value)
   elif (protocol3 in row1[6]):
      value = 2
      detectionnumber.append(value)
   else:
      value = 0
      detectionnumber.append(value)
   
print(detectionnumber)
test = len(detectionnumber)
print(test)

file_training_full["detection"] = detectionnumber
print(file_training_full)

LABEL_COLUMN = 'detection'

def get_dataset(file_path, **kwargs):

   dataset = tf.data.experimental.make_csv_dataset(
      file_path,
      batch_size=100,
      label_name=LABEL_COLUMN,
      num_epochs=1, **kwargs) 
   return dataset

get_dataset(file_training_full)`

**Comment by Saduf2019** [comment]
@Sustrommings
 Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by Sustrommings** [comment]
System Information: Linux Ubuntu 18.04 64bit, Tensorflow version 2.0.0, Tensorflow is compiled from source (gcc 7.5.0), python version 3.6.8

CSV file - [data.zip](https://github.com/tensorflow/tensorflow/files/4656656/data.zip)



Here is the complete code

import datetime
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow import feature_column
from tensorflow.keras import layers
import pandas as pd
import tensorflow_datasets as tfds
import os
import csv

file_path = '/home/root2001/Documents/PythonForMachineLearning/L05-Network-Packets'
file_training_full = pd.read_csv(file_path, sep='delimiter', header=None)

f = open(file_path)
csvf = csv.reader(f)

#for row in csvf:
    #print(row)

#Adds a column to each row, a row contain SYN ACK append 1, RST append 2, or else append 0
protocol1 = "SYN"
protocol2 = "ACK"
protocol3 = "RST"


detectionnumber = []
for row1 in csvf:
   if (protocol1 in row1[6] and protocol2 in row1[6] ):
      value = 1
      detectionnumber.append(value)
   elif (protocol3 in row1[6]):
      value = 2
      detectionnumber.append(value)
   else:
      value = 0
      detectionnumber.append(value)
   
print(detectionnumber)
test = len(detectionnumber)
print(test)

file_training_full["detection"] = detectionnumber
print(file_training_full)


LABEL_COLUMN = 'detection'


def get_dataset(file_path, **kwargs):

   dataset = tf.data.experimental.make_csv_dataset(
      file_path,
      batch_size=100,
      label_name=LABEL_COLUMN,
      num_epochs=1, **kwargs) 
   return dataset

get_dataset(file_training_full)


#model = tf.keras.models.Sequential([
   #tf.keras.layers.Dense(128, activation='relu'),
   #tf.keras.layers.Dropout(0,2),
   #tf.keras.layers.Dense(10)
   #])

**Comment by Saduf2019** [comment]
@
I ran the code shared by you and face a different error, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/a238f8e61c367d9416b883c84edfa31a/untitled190.ipynb)

**Comment by Sustrommings** [comment]
> @
> I ran the code shared by you and face a different error, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/a238f8e61c367d9416b883c84edfa31a/untitled190.ipynb)

Ok I have now fixed the indentation error, now the problem is the file_path where the retrieval of the csv file from my ubuntu directory, but the error has shown that there are no such file or directory, how do I specify the file path in the gist?

**Comment by Sustrommings** [comment]
Ok I have now fixed the indentation error, now the problem is the file_path where the retrieval of the csv file from my ubuntu directory, but the error has shown that there are no such file or directory, how do I specify the file path in the gist

[Updated Gist](https://gist.github.com/Sustrommings/04ba51877a3067cbb712056ac2ab6051)

**Comment by Sustrommings** [comment]
I have already solved the problem, thanks for helping.
