### ISSUE TITLE
404 Not found

### ISSUE THREAD

**Issue by AlbinDavid** [tensorflow/tensorflow#39703]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):using pip 
- TensorFlow version (use command below):2.2.0-rc1
- Python version:3.5.2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):5.4.0
- CUDA/cuDNN version:10.1/
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Cannot able to import the resnet 50 model from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/eager/benchmarks/resnet50/resnet50.py
**Describe the expected behavior**
I want to use the above resnet50 model and not the tf.keras.applications.ResNet50 for the intermediate outputs
**Standalone code to reproduce the issue**
import tensorflow as tf
from tf.python.eager.benchmarks #not working
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@AlbinDavid 
I ran the standalone code shared by you and face an error,please have a look at the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/4c19b8104323e52210001d12f1ae9732/untitled190.ipynb)
