### ISSUE TITLE
TPU PyFunction results in UnavailableError: failed to connect to all addresses

### ISSUE THREAD

**Issue by jonashaag** [tensorflow/tensorflow#39719]
Similar to #38762, and unfixed in tf-nightly. See gist here https://colab.research.google.com/gist/jonashaag/128c2b9c51cb0df5d00ef072928631e3/38762.ipynb

```
ds = tf.data.Dataset.from_generator(f, output_types='int32').map(g)
(_ for _ in ds)
```

```
UnavailableError: failed to connect to all addresses
```

**Comment by jonashaag** [comment]
Note: This is partly fixed in 20200611 in that creating the `Dataset` instance works, and also turning it into a generator. However if you replace the last line in the Gist with

```
next(_ for _ in ds)
```

it is still broken in the same way.

**Comment by sushreebarsa** [comment]
Was able to reproduce this issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/8ffd408110456c34b3f40e894a74fbfb/38762.ipynb#scrollTo=esVOgxbb2rx9)..Thanks !

**Comment by sushreebarsa** [comment]
Closing this issue as it is fixed in latest version of TensorFlow. Please feel free to reopen the issue if you still have a concern. Thanks!
