### ISSUE TITLE
tfa ReduceLROnPlateau callback from Tf keras is not recognizing cohen kappa metrics direction in 'Auto' mode

### ISSUE THREAD

**Issue by yuvaramsingh94** [tensorflow/tensorflow#39715]
Hi all,
the 'auto' mode in ReduceLROnPlateau  and ModelCheckpoint  are looking for specific string 'acc' in the name of the metrics to be monitor. this actually leads to unlickly scenarious of not working properly even while using metrics that are defined in tfa and hoping tf will be aware of the direction . this can be added in the doc to make the developers understand how to name their metrics or to set min max mode on their own. 
thanks

https://github.com/tensorflow/addons/issues/1865

**Comment by ravikyram** [comment]
@yuvaramsingh94 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.Request you to fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

Request yo to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by bhack** [comment]
@ravikyram This Is as DOC improvment issue but he hasn't selected the doc template opening this.

**Comment by yuvaramsingh94** [comment]
I used colab. this is a simple one line code and its a doc issue . i do remember opening this issue under `Documentation Issue` .
at https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/ReduceLROnPlateau

under Arguments -> mode we can find this line `in auto mode, the direction is automatically inferred from the name of the monitored quantity.`

this statement is misleading as it says auto mode can detect direction on its own . but, it does not work if the naming of the metrics does not fall within the criteria set in tf callback code as explained above ('acc' string is imp to determine the direction). 

so requesting to modify this line to talk about the naming part of the metrics too. this is same for `ModelCheckpoint ` and few others.

thanks

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
