### ISSUE TITLE
Does tensorflow 1.15.0 support int8 tflite convertion? Wrong accurary.

### ISSUE THREAD

**Issue by dreamPoet** [tensorflow/tensorflow#39713]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): pip install tensorflow-gpu==1.15
- TensorFlow version (or github SHA if from source): 1.15.0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```

converter=tf.lite.TFLiteConverter.from_frozen_graph(pb_path,input_arrays=input_tensor_name
                                                   ,output_arrays=class_tensor_name
                                                   ,input_shapes=input_tensor_shape)

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8
converter.representative_dataset=representative_data_gen

tflite_model=converter.convert()
 
 
with open('owntempuint.tflite','wb') as f:
    f.write(tflite_model)

```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:

The int8 model produced successfully, however, the accuracy is very low, while from the same .pb model whose accuracy is about 0.51, float tflite model achieve 0.47 accuracy, the int8 tflite model only has 0.04 with the same input.

**Comment by Saduf2019** [comment]
@dreamPoet  
I ran the code shared and face a different error, please provide with complete code such that we can replicate the issue.
Please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/25d7a8784b7190e680df4f5b2272de10/untitled195.ipynb) of error faced.

**Comment by dreamPoet** [comment]
I think the error you showed was because you use tf2.0 which discards the .pb model. 

I can provide some codes producing tflite from .h5 model, which also have problem when producing int8 model.  
[https://github.com/dreamPoet/tflearning/](https://github.com/dreamPoet/tflearning/)

These codes are written based on the official tutorial, as the validation set was produced randomly, every time the print information will be different, sample print info was like:

`Raw model accuracy: 85.938%
Quant TF Lite accuracy: 84.375%
INT8 Quant TF Lite accuracy: 18.750%`

As u can see, the INT8 input and output version tflite has very low accuracy.

**Comment by dreamPoet** [comment]
I think the error you showed was because you use tf2.0 which discards the .pb model. 

I can provide some codes producing tflite from .h5 model, which also have problem when producing int8 model.  
[https://github.com/dreamPoet/tflearning/](https://github.com/dreamPoet/tflearning/)

These codes are written based on the official tutorial, as the validation set was produced randomly, every time the print information will be different, sample print info was like:

`Raw model accuracy: 85.938%
Quant TF Lite accuracy: 84.375%
INT8 Quant TF Lite accuracy: 18.750%`

As u can see, the INT8 input and output version tflite has very low accuracy.

**Comment by MeghnaNatraj** [comment]
The gist error can be fixed by changing the `tf.lite.TFLiteConverter.from_frozen_graph` to `tf.compat.v1.lite.TFLiteConverter.from_frozen_graph` 

Could you also share the code where you compute the inference? The one caveat with models that have `inference_input_type` and `inference_output_type` set to `int8` or `uint8` is this -- you need to manually map (aka quantize) the float inputs to integer inputs for inference on your device. To understand how this can be done -- refer to the equation provided [here](https://www.tensorflow.org/lite/performance/quantization_spec), and it's equivalent code in python [here](https://github.com/tensorflow/examples/blob/master/tensorflow_examples/lite/model_maker/core/task/model_util_test.py#L89-L113) which compares a keras model's output with it's integer-only TFLite model's output . (I hope this makes sense -- if not I can provide more details)

**Comment by MeghnaNatraj** [comment]
Closing issue due to user inactivity. Feel free to re-open it if the issue persists.

**Comment by cloudlakecho** [comment]
@MeghnaNatraj, Thanks for the suggestion, but I don't think `tf.compat.v1.lite.TFLiteConverter.from_frozen_graph` is included in Tensorflow 1.15.0. Would you check?

**Comment by MeghnaNatraj** [comment]
@cloudlakecho It looks like it is included in TF 1.15.0. You can try the code here:

1. Open https://colab.sandbox.google.com/ and start a new notebook.
2. Run `pip install tensorflow==1.15.0`
3. Restart the notebook.
5. Run the following code 
```
import tensorflow as tf
print(tf.__version__)

tf.compat.v1.lite.TFLiteConverter.from_frozen_graph
```

The output is:
```
1.15.0
<bound method TFLiteConverter.from_frozen_graph of <class 'tensorflow.lite.python.lite.TFLiteConverter'>>
```

This implies that it was able to load the API.

**Comment by cloudlakecho** [comment]
@MeghnaNatraj Thanks for instruction, I tried and it is my output:
```
>>> import tensorflow as tf
>>> print (tf.__version__)
1.15.0
>>> tf.compat.v1.lite.TFLitedConverter.from_frozen_graph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/.venv/lib/python3.6/site-packages/tensorflow_core/python/util/module_wrapper.py", line 193, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'tensorflow._api.v1.compat.v1.lite' has no attribute 'TFLitedConverter'
```

Is there any discrepancy between you and me? I think I installed using `pip` and tested in Ubuntu 16.04.

**Comment by MeghnaNatraj** [comment]
Ah there is a typo in your command

❌ It is *not* - tf.compat.v1.lite.**TFLited**Converter.from_frozen_graph.
✅ Instead it is - tf.compat.v1.lite.**TFLite**Converter.from_frozen_graph
