### ISSUE TITLE
libhexagon_interface.so for non Android - Openwrt platform

### ISSUE THREAD

**Issue by hardiksd** [tensorflow/tensorflow#39736]
@tensorflow/tflite

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Openwrt 15.05
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: ipq6018
- TensorFlow installed from (source or binary): Source
- TensorFlow version: r2.2
- GCC/Compiler version (if compiling from source): musl arch64 gcc 5.3+ (https://musl.libc.org/)

**Describe the problem**
I'm trying to get hexagon delegate to work with QC's IPQ6018 SoC which contains a hexagon DSP. The currently available libhexagon_interface.so doesn't work as it has Android Dependencies. Is it possible to get a libhexagon_interface.so cross-compiled for openwrt without Android dependencies? 

Arch: armv8-64
One can build musl arch64 compiler using this project https://github.com/richfelker/musl-cross-make
After this step, using the binary generated you can cross-compile libhexagon_interface.so

I can help with testing if there is no access to Hardware. Thanks!

**Comment by karimnosseir** [comment]
Hi,
Sorry for the delay.
We currently have also arm linux version which we can share.
Is it hard requirement to use musl ?

**Comment by hardiksd** [comment]
I can give the arm linux version a try first, can you send it to me? Also, was it compiled for Armv8 instruction set?

**Comment by karimnosseir** [comment]
Can you reach out directly, so i can share it with you to try.

Thanks

**Comment by karimnosseir** [comment]
Shared with Hardik. Closing this issue.
