### ISSUE TITLE
Documentation of accepted datatypes for `validation_data` in keras.Model.fit is incorrect. 

### ISSUE THREAD

**Issue by AdamHarries** [tensorflow/tensorflow#39733]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit

## Description of issue (what needs changing):

The description of the keras `Model.fit` function is either ambiguous, or incorrect, regarding the accepted datatypes for the parameter `validation_data`. Specifically, some data types *are* accepted, even when the documentation states that they are not. For example, the datatype `keras.utils.Sequence` *is* accepted as a possible datatype, and (as far as I can tell) behaves as one would expect. 

As far as I can tell, this is primarily true when the user passes a generator/Sequence as `x`. In this case, the function `Model.fit` dispatches to the (deprecated) function `Model.fit_generator`, which *does* accept a generator or Sequence for the `validation_data` parameter.

This documentation should be corrected to unambiguously state one of the following: 

- *exactly* the list of datatypes that are accepted (e.g. numpy arrays, lists, pandas dataframes, etc). Note, this may require more work in order to fully test this set of datatypes. 
- *an approximation* of the list of datatypes that are accepted, with a cavaeat that some may be untested/only sometimes valid

If the types accepted are dependent on the type of `x`, then this should also be documented. 

### Submit a pull request?

If necessary, I am happy to open a PR, however I think that given this is clear user-facing code, and the primary interface for most tensorflow users it woudl be best to have this fix spearheaded by an internal developer.

**Comment by ymodak** [comment]
The documentation for model.fit arguments  are now updated with latest [tf-nightly api docs](https://www.tensorflow.org/api_docs/python/tf/keras/Model?version=nightly#fit). Thanks!
