### ISSUE TITLE
Keras Tensorboard Callback conflicts with Lambda Callback writing summaries

### ISSUE THREAD

**Issue by christopherbate** [tensorflow/tensorflow#39730]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, but will test stock examples to verify issue
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Docker tensorflow/tensorflow:2.2.0-gpu
- TensorFlow version (use command below):  Docker tensorflow/tensorflow:2.2.0-gpu
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1/7.6.4 (what'ts in the docker container)
- GPU model and memory: RTX 2080, 8GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

v2.2.0-rc4-8-g2b96f3662b 2.2.0

**Describe the current behavior**

Specify callbacks for Keras:
- TensorboardCallback, with a non-default batch interval
- LambdaCallback, which uses a created summary writer to write images a >1 batch interval which differs from the above

In the below script, the following settings produce expected results only when the `update_freq` is set to 1. 

**Describe the expected behavior**

Image writer should log and the status should be 1 (true)

Both summaries are written correctly at the correct batch intervals

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
''' 
Modified from tensorboard tutorial
https://www.tensorflow.org/tensorboard/image_summaries
'''
import io
import itertools
from datetime import datetime

import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import tensorflow.keras as keras

# Define callback batch intervals
tb_callback_interval = 2
lambda_callback_interval = 10


fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = \
    fashion_mnist.load_data()

logdir = "runs/bug_test/" + datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = keras.callbacks.TensorBoard(
    log_dir=logdir, update_freq=tb_callback_interval)
file_writer_cm = tf.summary.create_file_writer(logdir + '/cm')


def log_image(batch, logs):
    tf.print("Batch: ", batch)
    if batch % lambda_callback_interval == 0:
        with file_writer_cm.as_default():
            status = tf.summary.image(
                "Confusion Matrix", tf.expand_dims(test_images[0:5, :, :], -1), step=batch)
            tf.print("File write status (should be 1): ", status)


cm_callback = keras.callbacks.LambdaCallback(on_batch_end=log_image)

model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(10, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train the classifier.
model.fit(
    train_images,
    train_labels,
    epochs=5,
    verbose=1,  # Suppress chatty output
    callbacks=[tensorboard_callback, cm_callback],
    validation_data=(test_images, test_labels),
)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.1, 2.2 and nightly version and was able to reproduce the issue.However I have noticed in expected results status shown as 1 for few results and as 0 for few results.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/789ff5fb7f91f709140582f7dbc89d98/untitled923.ipynb).Thanks!

**Comment by christopherbate** [comment]
Note that ordering of the callbacks, i.e.:
```
callbacks = [custom_callback, tensorboard_callback]
```
vs
```
callbacks = [tensorboard_callback, custom_callback]
```
also changes the behavior. 

Currently, as a work around I have the "update_freq" for both my custom writer and the Keras writer set to the same number. If my custom callback with custom writer appears first in the list of callbacks, then it will work as expected. However changing the ordering or if the log frequencies are not the same, then the result is not as expected.

**Comment by Sytronik** [comment]
Any progress for this bug? I face the same issue. The ordering of the callbacks affects the `tf.summary.*` functions' behavior. `tf.sumaary.image` returns `False` when the callback order is `[tensorboard_callback, custom_callback]`.

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF v2.5,please find the gist[ here](https://colab.research.google.com/gist/sushreebarsa/7df41bf394227bfe712290dfd64b785f/untitled128.ipynb)..Thanks !

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF 2.6.0-dev20210606,please find the gist[ here](https://colab.research.google.com/gist/sushreebarsa/7df41bf394227bfe712290dfd64b785f/untitled128.ipynb#scrollTo=0_JfNugFpPUp) ..Thanks!

**Comment by pangwong** [comment]
Inherit from tf.keras.callbacks.TensorBoard and rewrite ```on_train_batch_begin/end``` function, and use ```summary_op_v2``` directly(like that in TensorBoard source code),  code likes below:
```python
class Custom(tf.keras.callbacks.TensorBoard)
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
    def on_train_batch_end(self, , batch, logs=None):
        super().on_train_batch_end(batch, logs)
        with self._train_writer.as_default():
           summary_ops_v2.image("image", image, step=batch)
        self._train_writer.flush()

```

**Comment by mohantym** [comment]
Hi @christopherbate! 
We are checking to see whether you still need help in this issue .Have you checked above [suggestion](https://github.com/tensorflow/tensorflow/issues/39730#issuecomment-912710417) yet? Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
