### ISSUE TITLE
cd Tiger build installation isssue when I'm using command cd Tiger it's retrun such a no file directory 

### ISSUE THREAD

**Issue by Anees11** [tensorflow/tensorflow#39740]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@Anees11,
Please fill in the issue template and also provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by amahendrakar** [comment]
Regarding the error you are facing, use `ls` command to list all the directories in that folder and then try to `cd` into one of the directory. Thanks!
