### ISSUE TITLE
ERROR: Encountered unresolved custom op: Dilation2D.

### ISSUE THREAD

**Issue by pranv12** [tensorflow/tensorflow#39748]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 20.04
- TensorFlow installed from (source or binary): source
- TensorFlow version : 2.1.0

**Error Output**

```
ERROR: Encountered unresolved custom op: Dilation2D.
ERROR: Node number 2 (Dilation2D) failed to prepare.
```

**Standalone code to reproduce the issue** 
link to code: [code](https://github.com/pranv12/tflite_example_cc)
link to model: [model](https://drive.google.com/file/d/1a7HeTnzP9J2H5z6JQZAsoOLnVOsZiZt_/view?usp=sharing)

a command to reproduce error: `g++ *.cc  -ltensorflow -ltensorflowLite`

**Any other info/logs**
there is no traceback in output.

**Comment by yyoon** [comment]
Instead of using separate dilation ops, could you set the dilation parameter in the convolution ops?

TFLite only supports a subset of TF ops, and `Dilation2D` op itself is not supported. Please refer to this compatibility guide: https://www.tensorflow.org/lite/guide/ops_compatibility.
