### ISSUE TITLE
Support "depth_to_pace" for tflite GPU delegate

### ISSUE THREAD

**Issue by huanyingjun** [tensorflow/tensorflow#39746]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (or github SHA if from source): a8001b9e8db92620603c3c0588d251192d327bae

**Provide the text output from tflite_convert**

```
# Copy and paste here
```

**Standalone code to reproduce the issue** 
Could you please add "depth_to_pace" support for tflite GPU delegate ?

**Any other info / logs**

INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
ERROR: Following operations are not supported by GPU delegate:
DEPTH_TO_SPACE: Operation is not supported.

**Comment by impjdi** [comment]
@jdduke 

Acknowledged, but I don't think the TFLite GPU team can cycles to take on individual requests on missing ops.  There should be a comprehensive and prioritized list of requested ops.
