### ISSUE TITLE
Cd Tiger not opening

### ISSUE THREAD

**Issue by Anees11** [tensorflow/tensorflow#39741]
![Screenshot_2020-05-21-11-34-45-27](https://user-images.githubusercontent.com/65701344/82530632-49ab0600-9b2d-11ea-8892-3e0cee5f445b.png)
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@Anees11 
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
Is this issue related to Tensorflow build/install?
Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by mihaimaruseac** [comment]
Not relevant for this repository
