### ISSUE TITLE
PReLU operation throws error on tflite android benchmark tool with gpu

### ISSUE THREAD

**Issue by anilsathyan7** [tensorflow/tensorflow#39749]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Redmi Note 8 pro
- TensorFlow installed from (source or binary): Google Colab Tensorflow Binary
- TensorFlow version (use command below): tf  1.15 and tf 2.2
- Python version: 3.6.9

**Describe the current behavior**
I converted a tf.keras model with PReLU operation into **tflite** format. The **android tflite benchmark tool** throws an error on the model with the **default PReLU settings of shared_axes=Null**

```
adb shell /data/local/tmp/benchmark_model_tf15 --graph=/data/local/tmp/prelu_model1.tflite --enable_op_profiling=true --use_gpu=true
adb: /opt/intel/intelpython27/lib/libcrypto.so.1.0.0: no version information available (required by adb)
STARTING!
Min num runs: [50]
Min runs duration (seconds): [1]
Max runs duration (seconds): [150]
Inter-run delay (seconds): [-1]
Num threads: [1]
Benchmark name: []
Output prefix: []
Min warmup runs: [1]
Min warmup runs duration (seconds): [0.5]
Graph: [/data/local/tmp/prelu_mod3.tflite]
Input layers: []
Input shapes: []
Input value ranges: []
Use legacy nnapi : [0]
Allow fp16 : [0]
Require full delegation : [0]
Enable op profiling: [1]
Max profiling buffer entries: [1024]
CSV File to export profiling data to: []
Use gpu : [1]
Allow lower precision in gpu : [1]
Use Hexagon : [0]
Hexagon lib path : [/data/local/tmp]
Hexagon Profiling : [0]
Use nnapi : [0]
Use xnnpack : [0]
Loaded model /data/local/tmp/prelu_mod3.tflite
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
**ERROR: TfLiteGpuDelegate Init: PRELU: Dimensions are not HWC**
ERROR: TfLiteGpuDelegate Prepare: delegate is not initialized
ERROR: Node number 2 (TfLiteGpuDelegateV2) failed to prepare.

ERROR: Restored previous execution plan after delegate application failure.
Failed to apply GPU delegate.
Benchmarking failed.
```

Now, with option **shared_axes=[1,2]**, it runs the model without any error on gpu.
Also, the model runs **without any error on CPU**  in both settings.

**Describe the expected behavior**

The tflite model with default PReLU settings (i.e no shared axes ), should run without any errors on gpu delegate in android.

**Standalone code to reproduce the issue**

Colab Notebook: https://colab.research.google.com/drive/1pZRaeUB7Gj1HU1BR9DcSI6SxHfdsWbD_#scrollTo=_63mXS3A1m0r

**Other info / logs** 

* **prelu_model1.tflite**: No shared axes and **does not run on gpu**
* **prelu_model2.tflite**: Has shared_axes=[1,2] and runs on gpu
[prelu_models.zip](https://github.com/tensorflow/tensorflow/files/4662049/prelu_models.zip)

The behaviour seems to be same for tf 2.2 models and corresponding android benchmark tools.
How can we make it run on gpu with default settings ie. no shared _axes?

**Comment by ravikyram** [comment]
@anilsathyan7 

Request you to provide the access for  colab link you have shared.Thanks!

**Comment by anilsathyan7** [comment]
Here is the updated link: https://colab.research.google.com/drive/1pZRaeUB7Gj1HU1BR9DcSI6SxHfdsWbD_?usp=sharing

Are you able to view the notebook?

**Comment by multiverse-tf** [comment]
> **System information**
> 
> * Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
> * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Redmi Note 8 pro
> * TensorFlow installed from (source or binary): Google Colab Tensorflow Binary
> * TensorFlow version (use command below): tf  1.15 and tf 2.2
> * Python version: 3.6.9
> 
> **Describe the current behavior**
> I converted a tf.keras model with PReLU operation into **tflite** format. The **android tflite benchmark tool** throws an error on the model with the **default PReLU settings of shared_axes=Null**
> 
> ```
> adb shell /data/local/tmp/benchmark_model_tf15 --graph=/data/local/tmp/prelu_model1.tflite --enable_op_profiling=true --use_gpu=true
> adb: /opt/intel/intelpython27/lib/libcrypto.so.1.0.0: no version information available (required by adb)
> STARTING!
> Min num runs: [50]
> Min runs duration (seconds): [1]
> Max runs duration (seconds): [150]
> Inter-run delay (seconds): [-1]
> Num threads: [1]
> Benchmark name: []
> Output prefix: []
> Min warmup runs: [1]
> Min warmup runs duration (seconds): [0.5]
> Graph: [/data/local/tmp/prelu_mod3.tflite]
> Input layers: []
> Input shapes: []
> Input value ranges: []
> Use legacy nnapi : [0]
> Allow fp16 : [0]
> Require full delegation : [0]
> Enable op profiling: [1]
> Max profiling buffer entries: [1024]
> CSV File to export profiling data to: []
> Use gpu : [1]
> Allow lower precision in gpu : [1]
> Use Hexagon : [0]
> Hexagon lib path : [/data/local/tmp]
> Hexagon Profiling : [0]
> Use nnapi : [0]
> Use xnnpack : [0]
> Loaded model /data/local/tmp/prelu_mod3.tflite
> INFO: Initialized TensorFlow Lite runtime.
> INFO: Created TensorFlow Lite delegate for GPU.
> **ERROR: TfLiteGpuDelegate Init: PRELU: Dimensions are not HWC**
> ERROR: TfLiteGpuDelegate Prepare: delegate is not initialized
> ERROR: Node number 2 (TfLiteGpuDelegateV2) failed to prepare.
> 
> ERROR: Restored previous execution plan after delegate application failure.
> Failed to apply GPU delegate.
> Benchmarking failed.
> ```
> 
> Now, with option **shared_axes=[1,2]**, it runs the model without any error on gpu.
This is an issue specific to the gpu delegate implementation. The error msg is emitted here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/common/model_builder_helper.cc#L252-L254

> Also, the model runs **without any error on CPU** in both settings.
> 
> **Describe the expected behavior**
> 
> The tflite model with default PReLU settings (i.e no shared axes ), should run without any errors on gpu delegate in android.
> 
> **Standalone code to reproduce the issue**
> 
> Colab Notebook: https://colab.research.google.com/drive/1pZRaeUB7Gj1HU1BR9DcSI6SxHfdsWbD_#scrollTo=_63mXS3A1m0r
> 
> **Other info / logs**
> 
> * **prelu_model1.tflite**: No shared axes and **does not run on gpu**
> * **prelu_model2.tflite**: Has shared_axes=[1,2] and runs on gpu
>   [prelu_models.zip](https://github.com/tensorflow/tensorflow/files/4662049/prelu_models.zip)
> 
> The behaviour seems to be same for tf 2.2 models and corresponding android benchmark tools.
> How can we make it run on gpu with default settings ie. no shared _axes?

**Comment by anilsathyan7** [comment]
@multiverse-tf So is it a bug? How can we fix it and properly run the model using gpu delegate ?

**Comment by impjdi** [comment]
We have a candidate and will check with your models.  Stay tuned :)

**Comment by impjdi** [comment]
Ok.  fix was submitted internally.  should go live sometime soon.  commit log should read something like "TFLite GPU: Expand how an HWC tensor is read."  I'll close this issue for now; reopen if needed.
