### ISSUE TITLE
tensorflow for go install failed

### ISSUE THREAD

**Issue by moseshu** [tensorflow/tensorflow#39744]
MacOS version(10.15.4)

1. I followed the instruction of  https://www.tensorflow.org/install/lang_c  ,I installed the c Library .but it doesn't word.the error is > hello_tf.c:2:10: fatal error: 'tensorflow/c/c_api.h' file not found

2. github.com/tensorflow/tensorflow/tensorflow/go/saved_model.go:25:2: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto" in any of:
/usr/local/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOROOT)
/Users/moses/workspace/godemo/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOPATH)

how to solve this problem

**Comment by whitehse** [comment]
I have also encountered this error on Linux:

```bash
~$ /tmp/tensor/hello_tf 
Hello from TensorFlow C library version 1.15.0
~$ go get github.com/tensorflow/tensorflow/tensorflow/go
package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto" in any of:
	/usr/local/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOROOT)
	/home/dwhite/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOPATH)
~$ uname -a
Linux lab 5.2.0-3-amd64 #1 SMP Debian 5.2.17-1 (2019-09-26) x86_64 GNU/Linux
~$ echo "$GOROOT $GOPATH"

~$ go version
go version go1.12.2 linux/amd64
```

**Comment by rensburger** [comment]
Same problem on windows 10

PS C:\Users\local\go\proj\tensorflow> go get github.com/tensorflow/tensorflow/tensorflow/go
package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto" in any of:
        C:\go\src\github.com\tensorflow\tensorflow\tensorflow\go\core\protobuf\for_core_protos_go_proto (from $GOROOT)
        C:\Users\lcoal\go\src\github.com\tensorflow\tensorflow\tensorflow\go\core\protobuf\for_core_protos_go_proto (from $GOPATH)

PS C:\Users\local\go\proj\tensorflow> go version
go version go1.14.3 windows/amd64
PS C:\Users\local\go\proj\tensorflow>

**Comment by yashem66** [comment]
> I have also encountered this error on Linux:
> 
> ```shell
> ~$ /tmp/tensor/hello_tf 
> Hello from TensorFlow C library version 1.15.0
> ~$ go get github.com/tensorflow/tensorflow/tensorflow/go
> package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto" in any of:
> 	/usr/local/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOROOT)
> 	/home/dwhite/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOPATH)
> ~$ uname -a
> Linux lab 5.2.0-3-amd64 #1 SMP Debian 5.2.17-1 (2019-09-26) x86_64 GNU/Linux
> ~$ echo "$GOROOT $GOPATH"
> 
> ~$ go version
> go version go1.12.2 linux/amd64
> ```

I got the same problem last night.
I execute this and I fixxed it.
`
cd $GOPATH/src/github.com/tensorflow/tensorflow/tensorflow/go
git checkout r1.11
`

**Comment by PetrDvoracek** [comment]
> > I have also encountered this error on Linux:
> > ```shell
> > ~$ /tmp/tensor/hello_tf 
> > Hello from TensorFlow C library version 1.15.0
> > ~$ go get github.com/tensorflow/tensorflow/tensorflow/go
> > package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto" in any of:
> > 	/usr/local/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOROOT)
> > 	/home/dwhite/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOPATH)
> > ~$ uname -a
> > Linux lab 5.2.0-3-amd64 #1 SMP Debian 5.2.17-1 (2019-09-26) x86_64 GNU/Linux
> > ~$ echo "$GOROOT $GOPATH"
> > 
> > ~$ go version
> > go version go1.12.2 linux/amd64
> > ```
> 
> I got the same problem last night.
> I execute this and I fixxed it.
> `cd $GOPATH/src/github.com/tensorflow/tensorflow/tensorflow/go`
> `git checkout r1.11`

Same problem, this "fixed" the problem at least temporarily.

**Comment by rensburger** [comment]
Worked for me also

**Comment by rtrevinnoc** [comment]
Worked for me too

**Comment by jhseu** [comment]
Fixed with https://github.com/tensorflow/tensorflow/commit/e5e495db7bee77cd0fd5dda3b06bd743cbcf1ef8

**Comment by leslie-wang** [comment]
seems still exist 
```
~/go/src/github.com/tensorflow/tensorflow/tensorflow $ git log HEAD --oneline
0de929fdc1 (HEAD -> master, origin/master, origin/HEAD) Make StatusHelper safer to use and fix a related memory leak.
~/go/src/github.com/tensorflow/tensorflow/tensorflow $ go test github.com/tensorflow/tensorflow/tensorflow/go
go/saved_model.go:25:2: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto" in any of:
        /usr/local/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOROOT)
        /home/pi/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOPATH)
~/go/src/github.com/tensorflow/tensorflow/tensorflow $ go version
go version go1.12.17 linux/arm
```

**Comment by jlozano** [comment]
I am also getting this issue when running `go get github.com/tensorflow/tensorflow/tensorflow/go`:
```
saved_model.go:25:2: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto" in any of:
	/usr/local/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOROOT)
	/Users/juan/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOPATH)
```
I am using the following version of Go:
```
go version go1.14.4 darwin/amd64
```

I get this with the latest version of Tensorflow, commit `01b030b77623c5fa00a43640f77af2a43572d02c`.

Any help would be appreciated!

**Comment by batara666** [comment]
still exist

**Comment by erikdubbelboer** [comment]
This works to install the latest working version:
```
go get github.com/tensorflow/tensorflow/tensorflow/go@v1.15.0
```

**Comment by batara666** [comment]
i don't know @erikdubbelboer , it return :

```go
/usr/bin/ld: cannot find -ltensorflow
collect2: error: ld returned 1 exit status
```

someone say `-ltensorflow` are replaced by `-tensorflow_framework`

OS : Ubuntu 20.04

**Comment by domino14** [comment]
I get this same error. Any resolution?

**Comment by glindsell** [comment]
Same here:
```
$ go get github.com/tensorflow/tensorflow/tensorflow/go
cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto" in any of:
	/usr/local/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOROOT)
	/Users/gl/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOPATH)
```

**Comment by shankernaik** [comment]
Hey guys, any fix ? I am facing same issue.
```
shankernaik$ go get github.com/tensorflow/tensorflow/tensorflow/go
package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto" in any of:
	/usr/local/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOROOT)
	/Users/shankernaik/code/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOPATH)
	```

**Comment by IcoveJ** [comment]
> This works to install the latest working version:
> 
> ```
> go get github.com/tensorflow/tensorflow/tensorflow/go@v1.15.0
> ```

at least, I download it successfully, but I don't know whether its functions are all right
