### ISSUE TITLE
`Tensor` slicing is ~300x slower than `numpy` slicing

### ISSUE THREAD

**Issue by kieranricardo** [tensorflow/tensorflow#39750]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: macOS 10.14.5
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0, 2.2.0-dev20200405
- Python version: 3.6

**Describe the current behavior**

Slicing a 1D `Tensor` is approximately 2 orders of magnitude slower than slicing a `numpy` `array`. Looking at the source code I'm not entirely sure whether this is a problem with `tensorflow` or `Eigen` so sorry if this in the wrong place!

**Describe the expected behavior**

I guess the expected behaviour is that tensorflow's slicing op has a competive performance to numpy. I'd be keen to implement a fix if its appropriate 

**Standalone code to reproduce the issue**

Here's a colab link with the below code snippet: https://colab.research.google.com/drive/1XeAgdhBwzxAuy613myIGttKrQ8W_UNCK?usp=sharing

```python
import numpy as np
import tensorflow as tf

arr = np.random.random(10_000_000).astype(np.float32)
tnsr = tf.constant(arr)

%timeit _ = tnsr[:100]
%timeit _ = arr[:100]
```

This outputs:

```
50.7 µs ± 668 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
163 ns ± 2.52 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```

**Comment by rpalakkal** [comment]
Maybe try using [ tf.slice](https://www.tensorflow.org/api_docs/python/tf/slice)?

**Comment by kieranricardo** [comment]
I only get _slightly_ better performance with `tf.slice` - `35us` instead of `50us` locally.

**Comment by gavinlive** [comment]
Extra info: using CPU, not GPU.

Was able to reproduce the problem

**Comment by Saduf2019** [comment]
@kieranricardo 
I ran the code shared, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/52d4d8b3c6057d48c866d6c3cb1f291e/untitled190.ipynb) and let us know if it replicates your issue.

**Comment by kieranricardo** [comment]
hi @Saduf2019, thanks that replicates my issue

**Comment by kieranricardo** [comment]
@Saduf2019 I was also able to replicate this on `tf-nightly`, I'll update my initial description

**Comment by maciejskorski** [comment]
The issue still persist; slicing tensors is an order of magnitude slower than slicing numpy arrays. 
I can see it under TF 2.4.0 on Colab.

**Comment by rmothukuru** [comment]
Could reproduce the issue in **`Tensorflow Version 2.5`**. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/c15402aeefe4319a756ab5fb91e745dd/untitled190.ipynb). Thanks!

**Comment by sachinprasadhs** [comment]
With the use of `tf.slice` in Tensorflow 2.7, there seems to be a huge improvement in performance, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/f25805975bb22b3ae8bd5e37ffe30bd9/39750.ipynb). Thanks!
