### ISSUE TITLE
tf.keras/Tensorboard callback does not implement activation histogram (and says it does)

### ISSUE THREAD

**Issue by goulou** [tensorflow/tensorflow#39755]
**System information**
- TensorFlow version (you are using): r2.2

**Describe the feature and the current behavior/state.**

The callback v2 does advertise that it can record activations (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/callbacks.py#L1722), but the code clearly shows it doesn't : the following only saves weights histograms.
```
    if self.histogram_freq and epoch % self.histogram_freq == 0:
      self._log_weights(epoch)

```

The callback in callbacks_v1 did implement activation summary writing. However, there is one limitation where you cannot use it with eager execution enabled.

We should :
- either remove the comment saying that Tensorboard callback logs activation histogram (or at least add a note that it should be implemented in a future version)
- or, preferably of course, implement the feature...

**Comment by tonyyore** [comment]
Same issue. No activation histograms. Any idea if it is being investigated?

**Comment by jvishnuvardhan** [comment]
@goulou Sorry for the late response. Looks like interesting feature.

Are you still interested in contributing? If yes, please feel free to open a PR in  [keras-team/keras repo.](https://github.com/keras-team/keras/issues) repository.

Please note that Keras development moved to keras-team/keras repository to focus on only keras. Thanks!

**Comment by kydonian** [comment]
This feature should be reopened IMO, it would be a useful feature.

**Comment by jvishnuvardhan** [comment]
@kydonian Can you please open it in keras-team/keras repo as mentioned in my last response. Keras team is focussing their efforts in that repo only. Thanks!

**Comment by bersbersbers** [comment]
I did, see https://github.com/keras-team/keras/issues/15972.

**Comment by jvishnuvardhan** [comment]
@bersbersbers Can we close it here and follow the progress in https://github.com/keras-team/keras/issues/15972? Thanks!
