### ISSUE TITLE
unable to load model with custom objects on a Fresh Python Environment!

### ISSUE THREAD

**Issue by Ramkumar47** [tensorflow/tensorflow#39752]
Hi all, i have an issue in loading a model with custom loss function in a fresh-separate IPython Environment. Following is a sample code i used.

```
import tensorflow as tf
import tensorflow.keras.backend as K
import numpy as np


# creating the model
x = tf.keras.Input(shape = 10, name = "Input")

dense1 = tf.keras.layers.Dense(units = 10, activation = None)(x)
dense2 = tf.keras.layers.Dense(units = 10, activation = None)(dense1)
dense3 = tf.keras.layers.Dense(units = 10, activation = None)(dense2)
output = tf.keras.layers.Dense(units = 10, activation = None)(dense3)

model = tf.keras.Model(inputs = x, outputs = output)

# custom loss function
def custom_loss_func(y_true, y_pred):
    return K.mean(K.square(y_true - y_pred))

# compiling the model
model.compile(loss = custom_loss_func, optimizer = "sgd")

# sample fit
X = np.linspace(0,1,10).reshape(1,10)
Y = X**2

model.fit(X,Y,epochs = 10, batch_size = 1)

model.save("custom_model.h5")

# test code to load along with the model. and it works
#  new_model = tf.keras.models.load_model("custom_model.h5", custom_objects = {"custom_loss_func":custom_loss_func})
```
in the last line, if i uncomment and run the script means, it works fine as the function is already defined on top. 
```
# test code to load along with the model. and it works
new_model = tf.keras.models.load_model("custom_model.h5", custom_objects = {"custom_loss_func":custom_loss_func})
```

But if i run above line on a separate fresh IPython environment which hasn't seen this code yet, it throws error as below.

```
In [34]: new_model = tf.keras.models.load_model("custom_model.h5", custom_objects = {"custom_loss_func":custom_loss_func})
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-34-77825814faa4> in <module>
----> 1 new_model = tf.keras.models.load_model("custom_model.h5", custom_objects = {"custom_loss_func":custom_loss_func})

NameError: name 'custom_loss_func' is not defined
```
Its correct, because that function object isn't defined in the new environment. 
I tried by defining a dummy function in the same name and try to load model, it didn't work as well, the errors are about mismatched input parameters, then mismatched return object etc.. 

Is there any working way to load the model with custom objects back on a fresh environment?

**Comment by ravikyram** [comment]
@Ramkumar47 

I have tried in colab with TF version 2.2 , and i am not seeing any issue after defining the custom loss function and loading the model.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/571c4ab9ac499b44ac1e0312e9157f50/untitled926.ipynb).Thanks!

**Comment by Ramkumar47** [comment]
Now i understood, there is no way to load a model with custom objects, without pre-defining them in the new environment.. Thank you @ravikyram
