### ISSUE TITLE
problem running visualize.py at import flatbuffersn

### ISSUE THREAD

**Issue by jeremyholleman** [tensorflow/tensorflow#39756]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  **Mac OS 10.15.3**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **n/a**
- TensorFlow installed from (source or binary): **from source**
- TensorFlow version (use command below): v1.12.1-32248-g8670c85844 **2.2.0**
- Python version: **3.7.4**
- Bazel version (if compiling from source): **3.0.0**
- GCC/Compiler version (if compiling from source): **Apple clang version 11.0.3 (clang-1103.0.32.59) (from gcc --version)**
- CUDA/cuDNN version: **n/a**
- GPU model and memory: **n/a**

**Describe the current behavior**
visualize.py script fails with this error:
`ImportError: cannot import name 'flatbuffersn' from 'flatbuffers.python' (/private/var/tmp/_bazel_jeremy/95159cfd4782ce915016562181875cd6/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/lite/tools/visualize.runfiles/flatbuffers/python/__init__.py)`

I am running it with the command 
`bazel run //tensorflow/lite/tools:visualize ~/dev/tfl_dev/mobilenet_v1_0.25_128_quant/mobilenet_v1_0.25_128_quant.tflite ~/tmp/mobnet.html
`
from the top of my tensorflow source directory.  The build phase seems to work fine, then the import error seems to happen on running visualize.py.  Full output in attached file.
[vis_dump.txt](https://github.com/tensorflow/tensorflow/files/4662612/vis_dump.txt)
The target tflite file can be downloaded [here]( http://download.tensorflow.org/models/mobilenet_v1_2018_08_02/mobilenet_v1_0.25_128_quant.tgz), but I don't think the tflite file ever gets loaded, so I doubt that the specific file is relevant.

The directory where it is trying to import from is listed here.  There is no flatbuffersn file or directory and the __init__.py file is empty.
```
ls -l /private/var/tmp/_bazel_jeremy/95159cfd4782ce915016562181875cd6/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/lite/tools/visualize.runfiles/flatbuffers/python/
total 0
-r-xr-xr-x   1 jeremy  wheel    0 May 20 16:15 __init__.py*
drwxr-xr-x   3 jeremy  wheel   96 May 21 09:39 __pycache__/
drwxr-xr-x  10 jeremy  wheel  320 May 20 16:15 flatbuffers/
```

**Describe the expected behavior**
I would expect it to dump an html file to ~/tmp/mobnet.html containing a visualization of the mobilenet model in the target tflite file.

**Standalone code to reproduce the issue**
The command line above.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by yyoon** [comment]
Yeah, I can actually reproduce this, and I think the import name should be `flatbuffers` but the following `\n` is somehow not correctly escaped and ended up being interpreted as character `n`.

This must be a bug somewhere in the flatbuffer build rule, or the flatbuffer tool. Let me dig a bit more about it.

**Comment by yyoon** [comment]
Found the issue, which was caused by the different `sed` tool behavior between linux and mac, as described here: https://stackoverflow.com/a/22203933/922135

I'll send a fix soon, but in the meantime you should be able to try the fix locally.

In the `tensorflow/third_party/flatbuffers/build_defs.bzl` file at line365, change:

    "import flatbuffers\\n/' > %s"

to 

    "import flatbuffers\\'$'\\n/' > %s"

and try running the visualize tool again.

**Comment by jeremyholleman** [comment]
That fixed it for me.  Thanks!
