### ISSUE TITLE
Tensorflow 1.x not available for python 3.8

### ISSUE THREAD

**Issue by cboettig** [tensorflow/tensorflow#39768]
**System information**
- OS Platform and Distribution Ubuntu 20.04 (LTS)
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.15
- Python version: 3.8.2
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
It seems that tensorflow 1.15.2 binaries are not available for Python 3.8 at this time.  This is at odds with the directions at https://www.tensorflow.org/install/pip state the system requirements for `tensorflow==1.15` are:

> * Python 3.5–3.8
> * pip 19.0 or later (requires manylinux2010 support)
> * Ubuntu 16.04 or later (64-bit)

Given that Ubuntu 20.04 is now the current LTS release and it has Python 3.8, it would be great if we could still run Tensorflow 1.x on that platform for as long as Tensorflow 1.x isn't deprecated.  

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Just follow the exact instructions on https://www.tensorflow.org/install/pip for current Ubuntu release. Thanks!

**Comment by Saduf2019** [comment]
@cboettig 
TensorFlow 1.x even 2.1 does not support Python 3.8. Instead could you please try installing TensorFlow v2.2.0rc3 using the following command. or use Python3.7, (3.6, 3.5 also work) for that.

pip install tensorflow==2.2.0rc3

please refer to this [comment](https://github.com/tensorflow/tensorflow/issues/38750#issuecomment-623088620) and [this](https://github.com/tensorflow/tensorflow/issues/39380#issuecomment-626379710)

**Comment by mihaimaruseac** [comment]
We don't add new versions of Python for old releases. If you want to use TF 1.15, you have to use Python 3.7 or lower. If you want to use Python 8 you have to use TF 2.2 or newer.

**Comment by cboettig** [comment]
@mihaimaruseac Thank you very much for clarifying that.  Can we convert this bug report into a documentation bug report?  The current documentation states otherwise.  Specifically, https://www.tensorflow.org/install/pip says that you support Python 3.5 - 3.8, (right below the instruction for installing 1.15) and does not indicate this is not true of 1.15.  

I do rely on the current TF release whenever possible.  As you surely know, many packages (in my most recent case, `stable-baselines`) still run only on 1.x version, so upgrading is not always possible.  Therefore I'm glad you still provide a 1.5 version, and I can revert to an older python version to take advantage of it. Thanks for the fast reply, very impressive on a project of this scale!

**Comment by mihaimaruseac** [comment]
Made https://github.com/tensorflow/docs/pull/1581 to update documentation. Thank you for the suggestion.

**Comment by hafez-ahmad** [comment]
pip install tensorflow
 Downloading tensorflow-2.3.0-cp38-cp38-win_amd64.whl (342.5 MB)
this is not working for python 3.8 . what can I do ? please

**Comment by mihaimaruseac** [comment]
@hafez-ahmad this issue is not the right place for that, you should have opened a new issue, filling in issue template.

I gather you are on Windows. Is your python 64 bits? Did you install the latest MSCV redistributable? When you installed Python, did you get it from the Python website or from Windows Marketplace?

**Comment by hafez-ahmad** [comment]
Yesterday,I installed python 3.8. I have solved it. 
I just open cmd as Administrator. then, I have installed tensorflow in python 3.8.

**Comment by mirekphd** [comment]
> We don't add new versions of Python for old releases.

A bit opinionated IMO. Py 2.x was supported for a decade or so after its deprecation.

But I've found a workaround:
```
pip install torch
```
