### ISSUE TITLE
AttributeError: module 'tensorflow.keras.layers.experimental' has no attribute 'EinsumDense'

### ISSUE THREAD

**Issue by asking1233** [tensorflow/tensorflow#39777]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  mac os 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binany (pip)
- TensorFlow version:  2.2.0
- Python version: 3.6.0
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:
**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@asking1233,
As per the [documentation for EinsumDense](https://www.tensorflow.org/api_docs/python/tf/keras/layers/experimental/EinsumDense) the API is available only on TF-nightly.

Using TF-nightly, I was able to import the API without any issues, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/6ebf3f4e9c27407f36401c2376805b46/39777.ipynb). Thanks!

**Comment by asking1233** [comment]
thanks,I  get it

**Comment by amahendrakar** [comment]
Marking the issue as closed, as it is resolved.
