### ISSUE TITLE
Example of using SavedModel

### ISSUE THREAD

**Issue by dhiegomaga** [tensorflow/tensorflow#39772]
This issue regards TensorFlow 2.2.0

## URL(s) with the issue:

https://www.tensorflow.org/guide/saved_model
https://www.tensorflow.org/api_docs/python/tf/saved_model/save

## Description of issue:

_TL;DR:I went through the links posted and still I don't understand how to properly use SavedModel format while defining tags, input and output tensor names, etc._ 

For instance, say I have this very simple model: 

```python
import tensorflow as tf

inputs = tf.keras.Input(shape=(3,))
x = tf.keras.layers.Dense(4, activation=tf.nn.relu)(inputs)
outputs = tf.keras.layers.Dense(5, activation=tf.nn.softmax)(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)
```
Calling `model.save(folder)` will easily save the model on SavedModel format. However, if I want to load it and use it somewhere else in a production environment I need to know how to define and name the SignatureDefs, input/output tensors of the sub-graph, tags etc. 

But after reading and studying thoroughly the extensive documentation for hours, I didn't see any concrete example of how to do so.

**Comment by sushantag9** [comment]
[Documentation](https://www.tensorflow.org/guide/saved_model#creating_a_savedmodel_from_keras)

We can load the SavedModel back into Python with `tf.saved_model.load` and see how Admiral Hopper's image is classified.

**Comment by Saduf2019** [comment]
@dhiegomaga 
Please update as per above comment

**Comment by dhiegomaga** [comment]
@sushantag9  I know. My question regards how to save the model using custom sub-graphs and input and output names. 
If I do what you said and try to load it using the TensorFlow C API, I need to find out the input and output **tensor names** in the graph, **which should be defined when saving the model.** If I want to use a different sub-graph of the network, I should be able to define different input and output tensors bound to a tag. 
None of this is clear in the documentation because all examples are using [model subclassing](https://www.tensorflow.org/guide/keras/overview#model_subclassing), and the only one using the standard model approach doesn't specify any tensor names, instead just saves the default graph (i.e., without defining any SignatureDefs), shown bellow: 

```python
x = input_layer.Input((4,), name="x")
y = core.Dense(5, name="out")(x)
model = training.Model(x, y)
tf.saved_model.save(model, '/tmp/saved_model/')
# The exported SavedModel takes "x" with shape [None, 4] and returns "out"
# with shape [None, 5]
```

**Comment by rmothukuru** [comment]
@dhiegomaga,
Documentation of [Saved Model](https://www.tensorflow.org/guide/saved_model) now comprises [Specifying the Signatures](https://www.tensorflow.org/guide/saved_model#specifying_signatures_during_export), [Loading a Saved Model in C++](https://www.tensorflow.org/guide/saved_model#load_a_savedmodel_in_c), etc..

Also. please find the documentation related to [Save and Serialize](https://www.tensorflow.org/guide/keras/save_and_serialize).

Thanks!
