### ISSUE TITLE
how to get the shared library containing the TfLite Delegate.of tf.lite.experimental.load delegate

### ISSUE THREAD

**Issue by a798347923** [tensorflow/tensorflow#39783]
I am doing a real-time palm detection, using opencv to get the camera screen and input it into the tiflite model, to get the palm position and other information, and finally using opencv to frame the palm.The system I use is ubuntu18.04 and the language is python3.7.If I only use the CPU, I have done it. Because the delay is too large, I want to use the GPU to accelerate the model prediction.But I didn't find any example of GPU acceleration of tflite model on linux, both android and ios. I only saw the delegate GPU on the python api.
Like,follow:
> tf.lite.Interpreter(
>     model_path=None, model_content=None, experimental_delegates=None
> )

> tf.lite.experimental.load_delegate(
>     library, options=None
> )

library | Name of shared library containing the TfLiteDelegate.

options | Dictionary of options that are required to load the delegate. All keys and values in the dictionary should be convertible to str. Consult the documentation of the specific delegate for required and legal options. (default None)

But I don't know how to generate the library which containing the TfLiteDelegate.
Can anyone give me some advice？Thanks very much.

**Comment by srjoglekar246** [comment]
A quick clarification: Is the model running on a desktop, or an Android/iOS phone?

**Comment by a798347923** [comment]
It's running on a desktop of ubuntu,thanks.

**Comment by zldrobit** [comment]
For now, gpu delegate only works on Android and iOS.
https://github.com/tensorflow/tensorflow/issues/37116#issuecomment-592230951
