### ISSUE TITLE
Tf.shape() does not support RaggedTensor

### ISSUE THREAD

**Issue by JohannesAck** [tensorflow/tensorflow#39784]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):

Yes

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

Ubuntu 16.04

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:

No

- TensorFlow installed from (source or binary):

binary

- TensorFlow version (use command below):

v2.1.0-rc2-17-ge5bf8de 2.1.0

- Python version:

3.6.8

- Bazel version (if compiling from source):

No

- GCC/Compiler version (if compiling from source):

No

- CUDA/cuDNN version:

CPU only

- GPU model and memory:

CPU only

**Describe the current behavior**
Calling `tf.shape()` on a RaggedTensor results in an error:
`TypeError: object of type 'RaggedTensor' has no len `

**Describe the expected behavior**
It should return the shape of the tensor, similar to calling `RaggedTensor.shape`

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1aN0DJwRbjDrt9-xu3tWmoNvth24a1wm0?usp=sharing

```
import tensorflow as tf
ragged = tf.ragged.constant([[0.1, 0.3, 0.5],
                                           [0.1],
                                            [0.4,0.5]])
print(ragged)
print(ragged.shape)
tf.shape(ragged)
```

**Other info / logs** Include any logs or source code that would be helpful to**
-

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.1.0, 2.2.0, nightly version (2.3.0-dev20200522) and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/36d3b2a96c8c192d2250ba20be34f86c/untitled928.ipynb).Thanks!

**Comment by jvishnuvardhan** [comment]
@JohannesAck Are you looking for `ragged.bounding_shape()`?
` print(ragged.bounding_shape()) # tf.Tensor([3 3], shape=(2,), dtype=int64)`

tf.shape(x) output dynamic shape of `x` where as x.shape() output static shape (with `None` in its dimensions wherever applicable). Dynamic shape cannot be possible if a tensor has a `None` in its dimensions.  Please check this [resource](https://stackoverflow.com/questions/37096225/how-to-understand-static-shape-and-dynamic-shape-in-tensorflow) for more info about x.shape versus tf.shape(x).

Please check the following example about shape function of ragged tensor. 


> The RaggedTensor.shape attribute returns a tf.TensorShape for a ragged tensor, where ragged dimensions have size None:
> 
> tf.ragged.constant([["Hi"], ["How", "are", "you"]]).shape
> 
> TensorShape([2, None])
> 
> The method tf.RaggedTensor.bounding_shape can be used to find a tight bounding shape for a given RaggedTensor:
> 
> print(tf.ragged.constant([["Hi"], ["How", "are", "you"]]).bounding_shape())
> 
> tf.Tensor([2 3], shape=(2,), dtype=int64)

Please check [ragged_tensor](https://www.tensorflow.org/guide/ragged_tensor) guide on TensorFlow website. 

Please take a look at the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/8cc8e51e02892828243291b32103ac4f/39784.ipynb). Please verify once and close the issue if this was resolved for you. Thanks!
