### ISSUE TITLE
[TF.Distribute] ctx.all_reduce is failed in the codition depends on layer-intenal variable.

### ISSUE THREAD

**Issue by MokkeMeguru** [tensorflow/tensorflow#39781]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab GPU
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:  No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.2
- GPU model and memory: I don't know (Google Colab served  one.)

**Describe the current behavior**

```python
class DataDepInitInternal(DataDepInit):
  """
  initialized is internal variable as Bool
  w is internal variable as Tensor
  """
  def initialize(self, x):
    ctx = tf.distribute.get_replica_context()
    if ctx:
      n = ctx.num_replicas_in_sync * 1.0
      mean,*_ = ctx.all_reduce(tf.distribute.ReduceOp.SUM, [tf.reduce_mean(x, axis=[0, 1, 2], keepdims=True) / n])
    return mean

  def call(self, x, first=True):
    if self.initialized: # <- this condition and below assignment cause error.
      self.initialized.assign(True)
      self.w.assign(self.initialize(x))
    return x - self.w
```
**Describe the expected behavior**
like this. (this layer use argument for condition, but I don't want to use it.
```python
class DataDepInitInternal(DataDepInit):
  """
  initialized is internal variable as Bool
  w is internal variable as Tensor
  """
  def initialize(self, x):
    ctx = tf.distribute.get_replica_context()
    if ctx:
      n = ctx.num_replicas_in_sync * 1.0
      mean,*_ = ctx.all_reduce(tf.distribute.ReduceOp.SUM, [tf.reduce_mean(x, axis=[0, 1, 2], keepdims=True) / n])
    return mean

  def call(self, x, first=True):
    if first:
      self.initialized.assign(True)
      self.w.assign(self.initialize(x))
    return x - self.w
```

**Standalone code to reproduce the issue**
All reproducal code is here. https://colab.research.google.com/gist/MokkeMeguru/dbe76b1da29366f9e52fef849c449e7e/data-dep-iinitialization.ipynb

**Other info / logs** Include any logs or source code that would be helpful to
see. colab, please.

Thanks!

**Comment by ravikyram** [comment]
I have tried in colab with TF -GPU 2.2 , nightly versions and was able to reproduce the issue.Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/ec28440b0c1c433ac4bb7f1c46c379c2/untitled927.ipynb)Thanks!

**Comment by sushreebarsa** [comment]
I tried to run the code on colab with TF v2.5 and faced different error .Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/2de6ebed2587cfd2286ff76dc4eaa8cd/untitled320.ipynb)..Thanks!
