### ISSUE TITLE
Tensorflow hangs when enqueueing with session timeout specified

### ISSUE THREAD

**Issue by sygi** [tensorflow/tensorflow#3978]
I am creating a simple `FIFOQueue` and enqueueing elements to it. Everything works fine when the session timeout is not specified (code as below, with timeout commented out):

    $ time python ex.py
    enqueue
    enqueue
    enqueue
    enqueue
    enqueue
    1.56user 0.24system 0:01.70elapsed 105%CPU 

Everything finishes correctly. But when I run the same code with timeout specified (to 60 seconds):

    import tensorflow as tf
    import numpy as np

    tf.reset_default_graph()
    data = np.array([1, 2])
    num_epochs = 5
    queue1 = tf.FIFOQueue(capacity=50, dtypes=[tf.int32], shapes=[()])

    def create_session():
        config = tf.ConfigProto()
        config.operation_timeout_in_ms=60000
        return tf.InteractiveSession(config=config)

    enqueue_op = queue1.enqueue_many(data)
    sess = create_session()
    tf.train.start_queue_runners()
    for i in range(num_epochs):
        print("enqueue")
        sess.run(enqueue_op)

````
$ time python ex.py
enqueue
enqueue
E tensorflow/core/client/tensor_c_api.cc:485] Timed out waiting for notification
Traceback (most recent call last):
  File "ex.py", line 21, in <module>
    sess.run(enqueue_op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 655, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 723, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 743, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.DeadlineExceededError: Timed out waiting for notification
Command exited with non-zero status 1
1.57user 0.24system 1:01.71elapsed 2%CPU
````

The number of "enqueue"s is not deterministic, but the code never finishes. Note that with timeout specified the code didn't manage to finish in a minute (in comparison to less than 2 seconds with no timeout).

### Environment info
Operating System: lubuntu 14.04, kernel 3.13.0-32-generic

Installed version of CUDA and cuDNN: no CUDA, using just CPU
If installed from binary pip package, provide:

1. Which pip package you installed: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`: 0.10.0rc0

**Comment by yaroslavvb** [comment]
PS, I tried .10rc0 (build with --cuda) on mac and ubuntu, and that code snippet always finishes in a couple of seconds

**Comment by mrry** [comment]
Thanks for reporting - I was able to reproduce with the nightly version, and should have a fix soon.

**Comment by prb12** [comment]
@sygi   This should be fixed now in the nightly builds.  (thanks @mrry!)  
Please can you reopen if the problem persists.
