### ISSUE TITLE
add tf.version.version_info similar to sys.version_info

### ISSUE THREAD

**Issue by robertlugg** [tensorflow/tensorflow#39795]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: 
*NA*
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 
*CentOS 7*
- **TensorFlow installed from (source or binary)**:
*binary: pip*
- **TensorFlow version (use command below)**:
*2.3.0-dev20200522*
- **Python version**:
*3.7.6*

- **Exact command to reproduce**:
*Feature request*

### Describe the problem
It is inconvenient to parse `tf.version.VERSION` to do version-specific logic.  The request is to provide a function more like `sys.version_info` so that the consumer doesn't need to parse a string.

### Source code / logs
Consider the output of `tf.version.VERSION`:
```
tf.version.VERSION
'2.3.0-dev20200522'
```
Contrast that output with `sys.version_info`:
```
>>> import sys
>>> sys.version_info
sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
```

The request is to add a function that will return a object similar to `sys.version_info`'s output.  Parsing that string is harder than first imagined.  Notice that not only are the "fields" concatenated together, depending on the build, the fields are different.  For instance, an older release gives `2.1.0`.

to be consistent with the other names in tf.version, I propose `tf.version.VERSION_INFO`.  What fields? major, minor, and micro are a must.  However since it is dictionary-like, it wouldn't hurt to have all versions (such as git and compiler) also included.

No workaround is requested.

**Comment by freakcap** [comment]
I am quite new to the open source. Can you please help me from where should I start so as to address this issue ?

**Comment by bhack** [comment]
@mihaimaruseac Do we want to this in python only or with c++ tf.session/wrapper? 

This is for the standard + ext SemVer attrs (`pip install semver`):

```python
import tensorflow as tf 
import semver
from pprint import pprint
sem = semver.VersionInfo.parse(tf.__version__)
pprint(sem)
```
```python
VersionInfo(major=2, minor=5, patch=0, prerelease='dev20201227', build=None)
```

**Comment by mihaimaruseac** [comment]
I think Python only should be good for start.

In C++ we already have the components separated.

**Comment by mihaimaruseac** [comment]
https://github.com/tensorflow/tensorflow/issues/39795#issuecomment-751472512 should be the right wait to parse the components, according to API owners.
