### ISSUE TITLE
Failed to legalize operation 'xla_hlo.return'

### ISSUE THREAD

**Issue by yashjain1129** [tensorflow/tensorflow#39792]
I am using TensorFlow installed from source and running on Google-Cloud. My git commit id is b52f058cb7fe2aee523fb2f0ae8ba712d2339b3a .

I am trying to test Reduce Op. I generated a frozen graph of .pbtxt format using a very simple program by using reduce_sum on 4*3*2 tensor. I generated graph def from it given below:

```
module attributes {tf.versions = {bad_consumers = [], min_consumer = 0 : i32, producer = 175 : i32}} {
  func @main(%arg0: tensor<4x3x2xf32>) -> tensor<f32> attributes {tf.entry_function = {control_outputs = "", inputs = "Placeholder", outputs = "Sum"}} {
    %0 = tf_executor.graph {
      %outputs, %control = tf_executor.island wraps "tf.Const"() {device = "", value = dense<[0, 1, 2]> : tensor<3xi32>} : () -> tensor<3xi32>
      %outputs_0, %control_1 = tf_executor.island wraps "tf.Sum"(%arg0, %outputs) {device = "", keep_dims = false} : (tensor<4x3x2xf32>, tensor<3xi32>) -> tensor<f32>
      tf_executor.fetch %outputs_0 : tensor<f32>
    }
    return %0 : tensor<f32>
  }
```

Above is graphdef file. I converted it into Xla hlo using `./tf-opt --tf-executor-island-coarsening -canonicalize --xla-legalize-tf.` Which give the output as:

```
module attributes {tf.versions = {bad_consumers = [], min_consumer = 0 : i32, producer = 175 : i32}} {
  func @main(%arg0: tensor<4x3x2xf32>) -> tensor<f32> attributes {tf.entry_function = {control_outputs = "", inputs = "Placeholder", outputs = "Sum"}} {
    %0 = xla_hlo.constant dense<[0, 1, 2]> : tensor<3xi32>
    %1 = tensor_cast %0 : tensor<3xi32> to tensor<3xi32>
    %2 = "xla_hlo.convert"(%arg0) : (tensor<4x3x2xf32>) -> tensor<4x3x2xf32>
    %3 = xla_hlo.constant dense<0.000000e+00> : tensor<f32>
    %4 = "xla_hlo.reduce"(%2, %3) ( {
    ^bb0(%arg1: tensor<f32>, %arg2: tensor<f32>):  // no predecessors
      %6 = xla_hlo.add %arg1, %arg2 : tensor<f32>
      "xla_hlo.return"(%6) : (tensor<f32>) -> ()
    }) {dimensions = dense<[0, 1, 2]> : tensor<3xi64>} : (tensor<4x3x2xf32>, tensor<f32>) -> tensor<f32>
    %5 = "xla_hlo.convert"(%4) : (tensor<f32>) -> tensor<f32>
    return %5 : tensor<f32>
  }
}

```
Now I am trying to convert above hlo file to lhlo using command ./tf-opt  --hlo-legalize-to-lhlo
But an segmentation fault came.
```
b.txt:12:7: error: failed to legalize operation 'xla_hlo.return' that was explicitly marked illegal
      "xla_hlo.return"(%6) : (tensor<f32>) -> ()
      ^
b.txt:12:7: note: see current operation: "xla_hlo.return"(%10) : (tensor<f32>) -> ()
PLEASE submit a bug report to  and include the crash backtrace.
Stack dump:
0.	Program arguments: ./tf-opt --hlo-legalize-to-lhlo b.txt 
./tf-opt[0x7fdd05d]
./tf-opt[0x7fdb1ad]
./tf-opt[0x7fdb6fd]
/lib64/libpthread.so.0(+0x12dc0)[0x7fac3735fdc0]
./tf-opt[0x7f7ba86]
./tf-opt[0x7f7eb0e]
./tf-opt[0x7f7deca]
./tf-opt[0x7f7e3e6]
./tf-opt[0x7f834b6]
./tf-opt[0x7f2e932]
./tf-opt[0x7f2f7ca]
./tf-opt[0x7f345dd]
./tf-opt[0x7d322dc]
./tf-opt[0x7f1890b]
./tf-opt[0x7f18c0c]
./tf-opt[0x7f18c0c]
./tf-opt[0x7f18c0c]
./tf-opt[0x7f1995f]
./tf-opt[0x7e0ebc9]
./tf-opt[0x7e13c89]
./tf-opt[0x7e13cfa]
./tf-opt[0x7e1ae85]
./tf-opt[0x5964480]
./tf-opt[0x59648c5]
./tf-opt[0x5964a80]
./tf-opt[0x930390]
/lib64/libc.so.6(__libc_start_main+0xf3)[0x7fac36d95873]
./tf-opt[0xa38cce]
Segmentation fault (core dumped)
```
This is the whole output. 
So is something still missing currently in the repo?

**Comment by ravikyram** [comment]
@yashjain1129 
Request you to fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by yashjain1129** [comment]
Step by step description
1) On Google colab run the following,
import tensorflow as tf
import numpy as np
tf.compat.v1.disable_eager_execution()
x = tf.compat.v1.placeholder(tf.float32, shape=(4, 3, 2))
y = tf.reduce_sum(x)
with tf.compat.v1.Session() as sess:
    rand_array1 = np.random.rand(4, 3, 2)
    (sess.run(y, feed_dict={x:rand_array1}))
    tf.io.write_graph(sess.graph_def, '', 'graph1.pbtxt')

By this we get a graph file.[https://drive.google.com/file/d/1D4XhBJIHmArOw3QJ83NX6jm1BlUnHAcj/view?usp=sharing](url)

On the above drive link you will get graph.pbtxt file.

2)  ./tf-mlir-translate --graphdef-to-mlir --tf-enable-shape-inference-on-import=true --tf-input-arrays=Placeholder  --tf-input-shapes=4,3,2 --tf-output-arrays=Sum ./sample_files/graph.pbtxt  > a.txt
3) After above command, these two commands are there both will do the same work and you can try any of them
./tf-opt --tf-executor-island-coarsening -canonicalize --xla-legalize-tf  a.txt > b.txt
or
 ./tf-opt --tf-executor-to-control-conversion --tf-raise-control-flow --xla-legalize-tf  a.txt > b.txt
4) After all these steps you will get the code in file b.txt as in the above issue. Now I want to convert this xla-hlo file into lhlo and then into affine. But conversion from hlo to lhlo is giving me the following error. 
b.txt:12:7: error: failed to legalize operation 'xla_hlo.return' that was explicitly marked illegal
"xla_hlo.return"(%6) : (tensor) -> ()
Full error is uploaded in the statement of issue which is above one.

**Comment by mihaimaruseac** [comment]
Please use proper markdown formatting around code/error blocks so this is readable.

**Comment by yashjain1129** [comment]
@mihaimaruseac my later comment is easy to follow and can be easily tested. I tried debugging from my side and found some bugs but was not able to remove completely. In my earlier commit history [https://github.com/tensorflow/tensorflow/pull/39700](url) I tried to solve. The for loop removing the argument in the ReduceOp function in hlo_legalize_to_lhlo.cc is giving segmentation fault. Also, hlo.return op need to be erased in the same function but not removed.

**Comment by bhack** [comment]
What is the status of this?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
