### ISSUE TITLE
Failed installing tensorflow 2.1.0 into Cloud Functions runtime Python 3.7

### ISSUE THREAD

**Issue by miohana** [tensorflow/tensorflow#39794]
Hi all,

I'm trying to create a cloud function with the following config:

Runtime:
`Python 3.7`

Memory:
`256 MiB`

requirements.txt:
`tensorflow==2.1.0`

When I deploy, I got the following error:
`Build failed: {"cacheStats": [{"status": "MISS", "hash": "54f4df7672bd136f86b67fd4d2390e30c509db5", "type": "docker_layer_cache", "level": "global"}, {"status": "MISS", "hash": "54f4df7672bd136f86b6730c509db5", "type": "docker_layer_cache", "level": "project"}]}`

This version is the one in which my model has been trained.

How to fix it?

**Comment by ymodak** [comment]
Can you try installing TF 2.0 instead? I think TF 2.1 Cloud Functions is not supported currently.
Also refer this [thread](https://github.com/tensorflow/tensorflow/issues/34707)

**Comment by miohana** [comment]
> Can you try installing TF 2.0 instead? I think TF 2.1 Cloud Functions is not supported currently.
> Also refer this [thread](https://github.com/tensorflow/tensorflow/issues/34707)

@ymodak I've changed for `tensorflow==2.0.0b0` version but still not working, with a different error related to memory.

I've increased the memory allocated to 2GiB, now I receive the following message when I try to deploy:

```
Deployment failure:
Build failed: gzip_tar_runtime_package gzip /tmp/tmpFtGSwL.tar -1
exited with error [Errno 12] Cannot allocate memory
gzip_tar_runtime_package is likely not on the path; Error ID: F2E01257
```

I'm trying to run a prediction of a custom model of a CNN architecture.

**Comment by ymodak** [comment]
Can you try reducing the batch size and check if the error still happens?
