### ISSUE TITLE
XLA Interpreter is not being compiled in Tensorflow 2.2

### ISSUE THREAD

**Issue by vincentmirian-xlnx** [tensorflow/tensorflow#39807]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): N/A
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): from source
- TensorFlow version (use command below): 2.2
- Python version: 3.6
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

Interpreter jit and services does not compile in Tensorflow 2.2.

The configuration was the default values displayed.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: 
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: 
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: 
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: 
Clang will not be downloaded.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: 
Not configuring the WORKSPACE for Android builds.

Steps to reproduce:
1) git clone -b r1.15 https://github.com/tensorflow/tensorflow.git
2) cd tensorflow
3) Add random character (e.g. "dfgfsdg") in the code area of xla_interpreter_device.cc (located in tensorflow/compiler/jit/).
4) bazel build -c dbg //tensorflow/tools/pip_package:build_pip_package

The compilation should fail. However it does not.

Note: my objective is to insert a custom backend. I was successful in TF version 1.15. However, when I reproduce those steps, the backend is not detected.

**Comment by vincentmirian-xlnx** [comment]
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
>>> v2.2.0-0-g2b96f3662b 2.2.0

**Comment by vincentmirian-xlnx** [comment]
Small changes to source.
In .bazelrc, add:
# AWS SDK must be compiled in release mode. see: https://github.com/tensorflow/tensorflow/issues/37498
build:dbg --copt -DDEBUG_BUILD

In third_party/aws/aws-checksums.bazel, add:
    defines = [
        "DEBUG_BUILD"
    ],

**Comment by vincentmirian-xlnx** [comment]
adding: 'build:xla --define with_xla_support=true' to the bazelrc file solved the issue. It seems that xla support is not enabled by default in 2.2.

Thank you.

**Comment by ymodak** [comment]
Closing this issue since it's resolved. Thanks!
