### ISSUE TITLE
how to multi scale train using tf.data.dataset

### ISSUE THREAD

**Issue by fengxiuyaun** [tensorflow/tensorflow#39800]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by Saduf2019** [comment]
@fengxiuyaun 
Please refer to [this link](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras) and [link2](https://stackoverflow.com/questions/52161605/tensorflow-multi-scale-training )let us know if it helps.

**Comment by fengxiuyaun** [comment]
> @fengxiuyaun
> Please refer to [this link](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras) and [link2](https://stackoverflow.com/questions/52161605/tensorflow-multi-scale-training)let us know if it helps.
 
thank you very much. Please show me a example?

**Comment by fengxiuyaun** [comment]
I don't know how to load dif size pictures of dif batch using tf.data.dataset. eg, 1th batch, picture size is 256,; 2th batch, size is 384.....

**Comment by Saduf2019** [comment]
@fengxiuyaun 
Can you check [this link](https://stackoverflow.com/questions/49641098/tensorflow-dataset-batch-not-showing-the-real-batch-size) [link1](https://adventuresinmachinelearning.com/tensorflow-dataset-tutorial/) [link2](https://www.kaggle.com/jalammar/intro-to-data-input-pipelines-with-tf-data) [link3](https://towardsdatascience.com/how-to-use-dataset-in-tensorflow-c758ef9e4428) and let us know.

**Comment by fengxiuyaun** [comment]
> @fengxiuyaun
> Can you check [this link](https://stackoverflow.com/questions/49641098/tensorflow-dataset-batch-not-showing-the-real-batch-size) [link1](https://adventuresinmachinelearning.com/tensorflow-dataset-tutorial/) [link2](https://www.kaggle.com/jalammar/intro-to-data-input-pipelines-with-tf-data) [link3](https://towardsdatascience.com/how-to-use-dataset-in-tensorflow-c758ef9e4428) and let us know.

no help

**Comment by gowthamkpr** [comment]
@fengxiuyaun Please post this question on stackoverflow as this issue is not related to bug/performance, build/install or feature request related issues. Thanks!
