### ISSUE TITLE
Error after run category_index = label_map_util.create_category_index_from_labelmap(PATH_TO_LABELS, use_display_name=True)

### ISSUE THREAD

**Issue by goms12** [tensorflow/tensorflow#39806]
![Capture](https://user-images.githubusercontent.com/63918976/82724724-56cd1e00-9d02-11ea-91e8-34f99eb57dec.PNG)
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by mihaimaruseac** [comment]
Please fill in issue template for the bug category, not for the miscellanous one.

**Comment by Saduf2019** [comment]
@goms12  
Please update as per above comment
