### ISSUE TITLE
Upgrading Tensorflow

### ISSUE THREAD

**Issue by alan0410** [tensorflow/tensorflow#39809]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 'Windows-10-10.0.18362-SP0'
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version: 1.12.0
- Python version: Python 3.6.8 :: Acaconda, : lnc
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): No Bazel
- GCC/Compiler version (if compiling from source): I have no GCC/compiler
- CUDA/cuDNN version: I have no CUDA
- GPU model and memory: I have no GPU

**Describe the problem**
Hi, I'm a beginner of tensorflow. I want to upgrade tensorflow version from 1.12.0 to 2.2.0 using Anaconda prompt, but it didn't work at all. How can I solve this problem? 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

![cpature](https://user-images.githubusercontent.com/60909846/82727392-32366d80-9d25-11ea-80e6-7a83346304c0.JPG)

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mihaimaruseac** [comment]
Not a TF issue. You have to manually uninstall `wrapt`.

Suggesting creating a fresh virtual environment and installing there instead of in the global namespace.
