### ISSUE TITLE
can't convert a string tensor to  python string when using Dataset.list_files(PATH).map(fun)

### ISSUE THREAD

**Issue by rick-wang-musetalk** [tensorflow/tensorflow#39813]
![image](https://user-images.githubusercontent.com/63587875/82728893-e59f6200-9d25-11ea-9f30-297c82594922.png)

as showed in the image. the wavPath is Tensor("args_0:0", shape=(), dtype=string). and then librosa.load(wavPath) raise error. there is noway to convert Tensor("args_0:0", shape=(), dtype=string) to the correct python string path

**Comment by amahendrakar** [comment]
@rick-wang-musetalk,
In order to reproduce the issue reported here, could you please provide the complete code, the dataset and TensorFlow version you are using. Thanks!
