### ISSUE TITLE
tensorflow cannot use feature columns to keras model

### ISSUE THREAD

**Issue by anavanab99** [tensorflow/tensorflow#39818]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://tensorflow.google.cn/versions/r2.1/api_docs/python/tf/feature_column/numeric_column

## Description of issue (what needs changing):

I tried to input a feature column to the keras model, but it was not available and the error was as follows:

```
    input_wide2 = keras.layers.Dense(300, activation=dnn_activation, )(input_lstm)
  File "/home/zy/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 818, in __call__
    self._maybe_build(inputs)
  File "/home/zy/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2098, in _maybe_build
    self.input_spec, inputs, self.name)
  File "/home/zy/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/input_spec.py", line 163, in assert_input_compatibility
    if x.shape.ndims is None:
AttributeError: 'DenseFeatures' object has no attribute 'shape'
```

I tried to search the solution of the problem through google, and the answer I got was to use tf.keras.Sequential () to solve the problem, but my model cannot use tf.keras.Sequential (), because I need to make a multi-input and more complex model . Sequential () cannot meet my requirements. Is this error a bug? Or am I using the wrong method? My case
[text.txt](https://github.com/tensorflow/tensorflow/files/4672214/text.txt)
 code is as follows

```
from tensorflow import keras
from tensorflow import feature_column
from tensorflow.keras.layers import Dense
from tensorflow.keras import Input, Model
from tensorflow.keras import regularizers
import tensorflow as tf


def read_tfrecord_input( tf_dir, batch_size, df_columns_list, which_labels, output_size):
    raw_dataset = tf.data.TFRecordDataset(tf_dir)
    feature_description = {}

    def _parse_function(record):
        for n in df_columns_list:

            # if n =='KDJ_gold':                            
[text.txt](https://github.com/tensorflow/tensorflow/files/4672218/text.txt)

            #     feature_description['%s'%n]=tf.io.FixedLenFeature([], tf.string, default_value='')
            if 'pred' in n:
                pass
            else:
                feature_description['%s' % n] = tf.io.FixedLenFeature([], tf.float32, default_value=0.0)
            feature_description['pred'] = tf.io.FixedLenFeature([output_size], tf.float32)

        parsed = tf.io.parse_single_example(serialized=record, features=feature_description)

        labels = parsed['pred']
        # kdj_gold = tf.cast(parsed['KDJ_gold'], tf.string)
        input_dict = {}
        for n in df_columns_list:
            if 'pred' in n:
                print(n, 'pass')
                pass
            # elif n=='KDJ_gold':
            #     input_dict['%s'%n]=kdj_gold                
            else:
                input_dict['%s' % n] = parsed['%s' % n]
        return input_dict, labels

    parsed_dataset = raw_dataset.map(_parse_function, num_parallel_calls=24)  
    parsed_dataset = parsed_dataset.batch(batch_size, drop_remainder=True)
    parsed_dataset = parsed_dataset.repeat()

    return parsed_dataset
dropout_rate=0.5
dnn_activation='relu'
volume = tf.feature_column.numeric_column('volume', shape=(1,))
lstm_list=[volume]

input_deep = keras.layers.DenseFeatures(lstm_list)
input_lstm = keras.layers.DenseFeatures(lstm_list)
input_wide2 = keras.layers.Dense(300, activation=dnn_activation, )(input_lstm)
input_wide2 = keras.layers.Dropout(0.5)(input_wide2)
lstm = keras.layers.LSTM(units=300, return_sequences=True, return_state=True, activation='tanh')
whole_seq_output, final_memory_state, final_carry_state = lstm(input_wide2)
lstm_drop_layer = keras.layers.Dropout(0.5)(whole_seq_output)

dnn1 = keras.layers.Dense(units=800, activation=dnn_activation)(input_deep)
dnn1 = keras.layers.BatchNormalization(axis=1)(dnn1)
dnn1 = keras.layers.SpatialDropout1D(dropout_rate)(dnn1)
dnn2 = keras.layers.Dense(units=600, activation=dnn_activation)(dnn1)

cancat_all = keras.layers.concatenate([dnn2, lstm_drop_layer])
output = keras.layers.Dense(1, activation='tanh')(cancat_all)
model = Model(inputs=[input_lstm, input_deep], outputs=[output])

model.compile(loss="mae", optimizer="Adam")
estimatoer = keras.estimator.model_to_estimator(keras_model=model, model_dir='model/ld')
estimatoer.train(input_fn=lambda: read_tfrecord_input(
    tf_dir='data/train.tfrecord', batch_size=9600, df_columns_list=lstm_list,
    which_labels='pred_d', output_size=1), max_steps=500)
```

please help me ,thank you!!

### Clear description

For example, why should someone use this method? How is it useful?

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example?

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by Saduf2019** [comment]
@anavanab99 
Can you share a simple stand alone code that replicates your issue, indented code.

**Comment by anavanab99** [comment]
> @anavanab99
> Can you share a simple stand alone code that replicates your issue, indented code.

Ok, I have uploaded the code in txt format, if you can't receive it, you can give me your email address. Thank you.

[the_code.txt](https://github.com/tensorflow/tensorflow/files/4683301/the_code.txt)

**Comment by Saduf2019** [comment]
@anavanab99 
I ran the code shared by you and face [this error](https://colab.sandbox.google.com/gist/Saduf2019/266a4d82f620d7d8a2298b2ef4f1c83e/untitled200.ipynb), please share all dependencies.

**Comment by anavanab99** [comment]
> @anavanab99
> I ran the code shared by you and face [this error](https://colab.sandbox.google.com/gist/Saduf2019/266a4d82f620d7d8a2298b2ef4f1c83e/untitled200.ipynb), please share all dependencies.
Okay, I use anaconda to configure the tensorflow environment, which is all my environment dependent files
[tf2_env.txt](https://github.com/tensorflow/tensorflow/files/4683463/tf2_env.txt)

**Comment by anavanab99** [comment]
> @anavanab99
> I ran the code shared by you and face [this error](https://colab.sandbox.google.com/gist/Saduf2019/266a4d82f620d7d8a2298b2ef4f1c83e/untitled200.ipynb), please share all dependencies.
@Saduf2019 
[tf2_env.txt](https://github.com/tensorflow/tensorflow/files/4686151/tf2_env.txt)

Okay, I use anaconda to configure the tensorflow environment, which is all my environment dependent files

**Comment by Saduf2019** [comment]
@anavanab99 
The error is face is because the training data is missing, which needs to be shared for us to replicate.

**Comment by anavanab99** [comment]
> @anavanab99
> The error is face is because the training data is missing, which needs to be shared for us to replicate.

This error is not a lack of training data. I do not want to train a neural network that can be used, but I want to make this program run even if it can not fit pred or loss nan. I solved some errors through the following methods.
the code: 
[feature_columns_solve.txt](https://github.com/tensorflow/tensorflow/files/4702368/feature_columns_solve.txt)

By using this method ,feature columns like categorical_column_with_hash_bucket can already run smoothly.

However, using the same method,   feature columns such as sequence_categorical_column_with_hash_bucket that with **sequence** still cannot run.
Its error is as follows
ValueError: The two structures don't have the same nested structure.
First structure: type=TensorSpec str=TensorSpec(shape=(None,), dtype=tf.float64, name=None)

Second structure: type=SparseTensor str=SparseTensor(indices=Tensor("volume/indices:0", shape=(None, 2), dtype=int64), values=Tensor("volume/values:0", shape=(None,), dtype=float32), dense_shape=Tensor("volume/shape:0", shape=(2,), dtype=int64))

More specifically: Substructure "type=SparseTensor str=SparseTensor(indices=Tensor("volume/indices:0", shape=(None, 2), dtype=int64), values=Tensor("volume/values:0", shape=(None,), dtype=float32), dense_shape=Tensor("volume/shape:0", shape=(2,), dtype=int64))" is a sequence, while substructure "type=TensorSpec str=TensorSpec(shape=(None,), dtype=tf.float64, name=None)" is not
Entire first structure:


mycode：
[my_code.txt](https://github.com/tensorflow/tensorflow/files/4702404/my_code.txt)

Thank you.

**Comment by gowthamkpr** [comment]
This is similar to this question [here](https://stackoverflow.com/questions/54375298/how-to-use-tensorflow-feature-columns-as-input-to-a-keras-model) where the workaround has been provided.

**Comment by anavanab99** [comment]
> This is similar to this question [here](https://stackoverflow.com/questions/54375298/how-to-use-tensorflow-feature-columns-as-input-to-a-keras-model) where the workaround has been provided.
Yes, this problem is indeed very similar, but he can only solve the feature series of dense layers. It is used to input the **sequence** characteristic column of the lstm layer, which cannot be run by this method. You can try my code. There will be an error that I cannot understand. thank you very much
[my_code.txt](https://github.com/tensorflow/tensorflow/files/4708171/my_code.txt)

**Comment by anavanab99** [comment]
> This is similar to this question [here](https://stackoverflow.com/questions/54375298/how-to-use-tensorflow-feature-columns-as-input-to-a-keras-model) where the workaround has been provided.
Yes, this problem is indeed very similar, but he can only solve the feature series of dense layers. It is used to input the **sequence** characteristic column of the lstm layer, which cannot be run by this method. You can try my code. There will be an error that I cannot understand. thank you very much
[my_code.txt](https://github.com/tensorflow/tensorflow/files/4708173/my_code.txt)

**Comment by anavanab99** [comment]
> This is similar to this question [here](https://stackoverflow.com/questions/54375298/how-to-use-tensorflow-feature-columns-as-input-to-a-keras-model) where the workaround has been provided.



> This is similar to this question [here](https://stackoverflow.com/questions/54375298/how-to-use-tensorflow-feature-columns-as-input-to-a-keras-model) where the workaround has been provided.
@Saduf2019 
Hello, my problem has not been solved, is it forgotten? Thank you

**Comment by Saduf2019** [comment]
@anavanab99
Is this still an issue, can you please try on tf-nigtly and let us know.
