### ISSUE TITLE
Clang host compiler support?

### ISSUE THREAD

**Issue by lukeiwanski** [tensorflow/tensorflow#3981]
Hi all, 

I couldn't help but notice that currently TensorFlow is tightly coupled with GCC. Is there a plan to make it more flexible with the choice for host compiler? like clang? 
Is there any effort or plans for that?

Thanks,
Luke

**Comment by prb12** [comment]
This is a general question best suited to StackOverflow.  Please can you re-ask there.

**Comment by vrv** [comment]
Actually this question is probably not suited to StackOverflow as written...

However, ./configure does allow you to specify the choice of the host compiler, and on Macs it uses clang anyway, so I suspect it already works.
