### ISSUE TITLE
not able to run %tensorboard --logdir logs\fit

### ISSUE THREAD

**Issue by prashkjha** [tensorflow/tensorflow#39819]
TypeError                                 Traceback (most recent call last)
~\Anaconda3\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    691                 type_pprinters=self.type_printers,
    692                 deferred_pprinters=self.deferred_printers)
--> 693             printer.pretty(obj)
    694             printer.flush()
    695             return stream.getvalue()

~\Anaconda3\lib\site-packages\IPython\lib\pretty.py in pretty(self, obj)
    377                             meth = cls._repr_pretty_
    378                             if callable(meth):
--> 379                                 return meth(obj, self, cycle)
    380             return _default_pprint(obj, self, cycle)
    381         finally:

TypeError: _repr_pretty_() takes 1 positional argument but 3 were given

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\Anaconda3\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    691                 type_pprinters=self.type_printers,
    692                 deferred_pprinters=self.deferred_printers)
--> 693             printer.pretty(obj)
    694             printer.flush()
    695             return stream.getvalue()

~\Anaconda3\lib\site-packages\IPython\lib\pretty.py in pretty(self, obj)
    377                             meth = cls._repr_pretty_
    378                             if callable(meth):
--> 379                                 return meth(obj, self, cycle)
    380             return _default_pprint(obj, self, cycle)
    381         finally:

TypeError: _repr_pretty_() takes 1 positional argument but 3 were given

**Comment by amahendrakar** [comment]
@prashkjha,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!
