### ISSUE TITLE
no specification for blank index for ctc_batch_cost

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/tensorflow#39816]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/MyMethod

https://tensorflow.google.cn/api_docs/python/tf/keras/backend/ctc_batch_cost

## Description of issue (what needs changing):

there is no specification for blank index. I can see default blank index for tf.nn.ctc_loss from [here](https://tensorflow.google.cn/api_docs/python/tf/nn/ctc_loss). is tf.keras.backend.ctc_batch_cost uses the same token for blank index? the old keras interface use a different default blank index. so, I am not sure about tf.keras's ctc_batch_cost's behavior.

### Clear description

For example, why should someone use this method? How is it useful?

the specification is important for people building recurrent neural network with tf.keras interfaces.

### Correct links

Is the link to the source code correct?

yes.

### Parameters defined

Are all parameters defined and formatted correctly?

yes.

### Returns defined

Are return values defined?

yes.

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

no.

### Usage example

Is there a usage example?

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

no.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

no.

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

no.

**Comment by nikitamaia** [comment]
Hi @breadbread1984, sorry for the late response here. I'm not seeing the `tf.keras.backend.ctc_batch_cost` symbol in 2.4
Let me know if I'm missing something, or if we should close this issue.
