### ISSUE TITLE
ResourceExhaustedError with a RNN compiled with XLA

### ISSUE THREAD

**Issue by EgorLakomkin** [tensorflow/tensorflow#39811]
Hi,

I experimented with a custom RNN compilation with XLA and I hit OOM with only a single layer RNN (used LayerNormLSTMCell cell).

Repro in collab (tested on tf-nightly)  https://colab.research.google.com/drive/1YWfuRX72A-819S_YqFZ0A0BNBAR5cTFv?usp=sharing
I understand that XLA maybe more memory hungry than cuDNN LSTM implementation, but its relatively small model to not fit to one GPU (single-layer layernorm LSTM with 1536 units)

**Comment by ravikyram** [comment]
@EgorLakomkin 

Request you to provide us the access for the colab link you have given.Thanks!

**Comment by EgorLakomkin** [comment]
Sorry, should work now!

**Comment by ravikyram** [comment]
@EgorLakomkin 

I have tried in colab with TF nightly version.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/ef80fccfb02b8328a6dcc1dbaa5269d2/untitled40.ipynb).Is this the expected behavior? Thanks!

**Comment by EgorLakomkin** [comment]
Hi @ravikyram, I am getting ResourceExhaustedError as it looks like 15GB of GPU memory is asked to be allocated

**Comment by cheshire** [comment]
I've looked at the issue briefly. At the peak (at least) a 10GB array is alive, so while 15GB is excessive and we could do better (as shown by TF), it's not completely outside of the scope of reasonable.

**Comment by cheshire** [comment]
Though it is kind of strange that without XLA compilation, <200MB are seemingly used. Investigating further.

**Comment by blakehechtman** [comment]
The underlying issue is how tf2xla represents stacks as tensors instead of an array of pointers to tensors. When this interacts with an rnn, every matmul pushes the lhs and rhs operands onto a stack. In the case of a matmul the RNN is an unchanging ReadVariableOp. In native tf this would be a stack of the same pointer. in XLA this ends up the weights of the model replicated by sequence length.

**Comment by EgorLakomkin** [comment]
@cheshire Right, this was mainly the reason for filing this ticket, that the memory consumption was much larger than expected.

**Comment by cheshire** [comment]
@EgorLakomkin what Blake is saying is correct, fixing this would require large non-trivial changes to tf2xla conversion (from what I understand, in practice users who wish to use XLA end up changing their model to make it more suitable for compilation).

**Comment by EgorLakomkin** [comment]
I see, many thanks! Is there are any examples of using RNN-like architectures with XLA? Just trying to get an idea of how the model is needed to be changed to be more suitable for compilation.

**Comment by cheshire** [comment]
Sorry I don't really know, maybe @blakehechtman could provide more details?

**Comment by sushreebarsa** [comment]
@EgorLakomkin Could you please try on the latest TF version 2.7.0 and let us know if it helps?Thanks!

**Comment by mohantym** [comment]
I was getting different error in TF 2.7 . Attaching [Gist](https://colab.sandbox.google.com/gist/mohantym/0782670ce2dbad63233510b4e8e7a9d0/xla_oom.ipynb#scrollTo=kpu9ge8Oand_) for reference. Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
