### ISSUE TITLE
Can not configure by new commit

### ISSUE THREAD

**Issue by lcwyylcwyy** [tensorflow/tensorflow#3982]
the new version 6d04d601e9e8758ec4642fa9d548b7321d804d63
./configure  on Mac platform

cuda_configure.bzl:409:18: function 'repository_rule' does not exist.

**Comment by prb12** [comment]
Please can you provide the information requested in the TensorFlow issues template.  (software and OS versions, the exact sequence of command lines required to reproduce the problem)

**Comment by vrv** [comment]
You probably need to update bazel to 0.3.0.

**Comment by lcwyylcwyy** [comment]
OK I  git pull  the tensorflow on Mac book. The System is OS X EI Capitan. With Nvidia GTX750
Cuda is 7.5 and Cudnn is 5
the repo commit is 6d04d60 
I run the ./configure.  After the cuda setting,  there is an error that cuda_configure.bzl:409:18: function 'repository_rule' does not exist.

Then I delete the all repo and git clone a new one. The error also exist. The branch is on master.

**Comment by vrv** [comment]
What bazel version do you have?

**Comment by lcwyylcwyy** [comment]
I brew the bazel on Mac. so the version is 2.0
The configuration is before compilation. And I have clone a new repo. The issue is also exist.

**Comment by vrv** [comment]
The repo now needs bazel 0.3.0.  @davidzchen do you know who is in charge of bazel homebrew?

**Comment by lcwyylcwyy** [comment]
Ok I will update it. The bazel version is 3.0 on homebrew. And thank you very much!

**Comment by vrv** [comment]
https://github.com/Homebrew/homebrew-core/blob/8f35a6b808a98f5bfaee546644f80564bd95ae40/Formula/bazel.rb#L4 it looks like homebrew is already at 0.3.1, so you can upgrade.
