### ISSUE TITLE
 C++ compilation of rule '//tensorflow/core/kernels:mkl_softmax_op' failed - Win 10 / VS2019

### ISSUE THREAD

**Issue by oracle3001** [tensorflow/tensorflow#39824]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Source
- TensorFlow version: Master Branch
- Python version: 3.7
- Bazel version (if compiling from source): 2.0.1
- GCC/Compiler version (if compiling from source):  VS2019
- CUDA/cuDNN version: 10.1
- GPU model and memory: 2070 Max-Q

**Describe the problem**

Build of mkl version of TF fails to build from source, errors with the following

ERROR: C:/sdks/tensorflow-dev/tensorflow/core/kernels/BUILD:8207:1: C++ compilation of rule '//tensorflow/core/kernels:mkl_softmax_op' failed (Exit 2)
.\tensorflow/core/util/mkl_util.h(1285): error C2131: expression did not evaluate to a constant
.\tensorflow/core/util/mkl_util.h(1284): note: failure was caused by a read of a variable outside its lifetime
.\tensorflow/core/util/mkl_util.h(1284): note: see usage of 'dim'
.\tensorflow/core/util/mkl_util.h(1286): error C2131: expression did not evaluate to a constant
.\tensorflow/core/util/mkl_util.h(1284): note: failure was caused by a read of a variable outside its lifetime
.\tensorflow/core/util/mkl_util.h(1284): note: see usage of 'dim'
.\tensorflow/core/util/mkl_util.h(1288): error C3863: array type 'dnnl_dim_t [kNumDims]' is not assignable
.\tensorflow/core/util/mkl_util.h(1289): error C3863: array type 'dnnl_dim_t [kNumDims]' is not assignable
Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel build --config=mkl //tensorflow/tools/pip_package:build_pip_package

**Comment by NeoZhangJianyu** [comment]
@oracle3001 We will check as soon!

**Comment by NeoZhangJianyu** [comment]
@oracle3001 The PR should fix this issue: https://github.com/tensorflow/tensorflow/pull/37785

**Comment by NeoZhangJianyu** [comment]
@oracle3001 Is it possible to close this issue?

**Comment by NeoZhangJianyu** [comment]
@oracle3001 
Could you feedback the fix in https://github.com/tensorflow/tensorflow/pull/37785?

**Comment by NeoZhangJianyu** [comment]
@oracle3001 

If your issue is fixed, could you close this issue?

**Comment by NeoZhangJianyu** [comment]
@oracle3001 

Could you feedback?

Thank you!

**Comment by oracle3001** [comment]
Yes, it appears to be fixed in TF 2.4.

**Comment by NeoZhangJianyu** [comment]
@oracle3001 
It's great!

Could you close this issue?

Thank you!
