### ISSUE TITLE
TFLite conversion of Conv1D layer with dilation_rate>1

### ISSUE THREAD

**Issue by petros-giannakopoulos** [tensorflow/tensorflow#39823]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.7

**Describe the current behavior**
After converting a TF ```Conv1D``` op with ```dilation_rate>1``` to TFLite op, the interpreter cannot allocate tensors:

```
RuntimeError: tensorflow/lite/kernels/space_to_batch_nd.cc:98 NumDimensions(op_context.input) != kInputDimensionNum (3 != 4)Node number 0 (SPACE_TO_BATCH_ND) failed to prepare.
```

**Describe the expected behavior**
TFLite model should be able to load and execute by the interpreter.

**Standalone code to reproduce the issue**
```
import tensorflow as tf

from tensorflow.keras.models import Model
from tensorflow.keras.layers import *


def get_model():
  input = tf.keras.Input(shape=(10, 40))

  # No error when dilation rate == 1
  layer = Conv1D(32, (3), dilation_rate=2, padding='same', use_bias=False)(input)
  layer = GlobalMaxPooling1D()(layer)
  output = Dense(2)(layer)

  model = Model(inputs=[input], outputs=[output])
  return model


model = get_model()

converter = tf.lite.TFLiteConverter.from_keras_model(model)

tflite_model = converter.convert()
open("./trained_model.tflite", "wb").write(tflite_model)

interpreter = tf.lite.Interpreter(model_path="./trained_model.tflite")

interpreter.allocate_tensors()
```

**Other info / logs** 
The problem does not occur when ```dilation_rate==1```

**Comment by petros-giannakopoulos** [comment]
#30315

**Comment by amahendrakar** [comment]
@petros-giannakopoulos,
I was able to reproduce the error with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/5b883e85d2751137e47421183a0e9c9b/39823.ipynb#scrollTo=dSKM0rtCI_L3). However, the issue seems to be fixed with the latest [TF-nightly](https://colab.research.google.com/gist/amahendrakar/a8c3ae96c71321b37485754754ead583/39823-tf-nightly.ipynb). Please check the linked gist. Thanks!

**Comment by amahendrakar** [comment]
@petros-giannakopoulos,
Any updates regarding this issue? Thanks!

**Comment by petros-giannakopoulos** [comment]
I confirm the issue is fixed in latest TF-nightly. Thanks! I'm closing the issue.

**Comment by jtdutta1** [comment]
Although the issues do not exist in the tf-nightly builds, the stable versions of tensorflow does not yet support conv1d layers with dilations > 1. When will this be pushed to the stable release? I worked with 2.4.1 and this issue still persists.
