### ISSUE TITLE
Python project bug

### ISSUE THREAD

**Issue by ocean-invader** [tensorflow/tensorflow#39828]
Hi I'm new to python and I start my first project but when I type "minus" it execute addition part of program and I try and try but I fail to fix it

x = int(input("X Value: "))
y = int(input("Y Value: "))
i = 0

while i == 0:
    print(" ")
    print(f"({x}, {y})")
    cmd = input("> ")
    cmd = cmd.lower()

    # plus
    if cmd == "plus" or "Addition":
        i = 1
        while i == 1:
            sub_cmd_pos = input("(x) + y  or  (y) + x ")
            sub_cmd_pos = sub_cmd_pos.lower()
            if sub_cmd_pos == 'x':
                print(x + y)
                i = 1
            elif sub_cmd_pos == 'y':
                print(y + x)
                i = 1
            else:
                print("Invalid Command, For help type 'help' ")

    # minus
    elif cmd == "minus" or "subtraction":
        i = 2
        while i == 2:
            sub_cmd_neg = input("(x) - y  or  (y) - x ")
            sub_cmd_neg = sub_cmd_neg.lower()
            if sub_cmd_neg == 'x':
                print(x - y)
                i = 0
            elif sub_cmd_neg == 'y':
                print(y - x)
                i = 0
            else:
                print("Invalid Command, For help type 'help' ")

**Comment by yashrajjain726** [comment]
1. You are taking the value of i=0 from previously so, the code did not execute to when i=1 or 2
2. Your while loop for i=0 cannot be executed because it has an indentation problem.

**Comment by amahendrakar** [comment]
@ocean-invader,
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/ask) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by mihaimaruseac** [comment]
Not TF related
