### ISSUE TITLE
Help Changing Tensor Value

### ISSUE THREAD

**Issue by ryanmaxwell96** [tensorflow/tensorflow#39835]
How can I change a particular tensor value? It seems eagertensors cannot be changed at all in either keras or tensorflow, but it seems to me that this should be a relatively straightforward task.

**System information**
- TensorFlow version 2+:
- Are you willing to contribute it (No): I don't know how

**Describe the feature and the current behavior/state.**
Cannot change tensor values

**Will this change the current api? How?**
Give more flexibility to users

**Who will benefit with this feature?**
All TF users

**Comment by ravikyram** [comment]
@ryanmaxwell96 

Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!

**Comment by ryanmaxwell96** [comment]
Hello, thank you for the quick reply. I'm currently working on an idea to train in stages and for this I need to lock some values coming from a Dense layer in place and then unlock them after a certain stage of training. I thought it would be a simple task to just assign the values to be what I want them to be, but apparently not.

**Comment by ymodak** [comment]
Keras backend exposes [get_value](https://www.tensorflow.org/api_docs/python/tf/keras/backend/set_value) API which can be used to set the variables.

**Comment by ryanmaxwell96** [comment]
Thank you. I realized that I can lock vehicle appendages more directly with the inputs to the actual simulation itself instead, so I think I've got it figured out.
