### ISSUE TITLE
Hashing functions for tf.string

### ISSUE THREAD

**Issue by sumanthratna** [tensorflow/tensorflow#39833]
**System information**
- TensorFlow version (you are using): 2.2.0
- Are you willing to contribute it (Yes/No): depending on the time commitment

**Describe the feature and the current behavior/state.**
I want to apply SHA-512 to a `tf.string`, so this is what I'm doing
```python
def convert_to_hex_dig(input, length):
  return hashlib.sha512(
      input.numpy().decode('utf-8').encode('utf-8')
  ).hexdigest()[0:length]

current_key = tf.py_function(
  convert_to_hex_dig,
  [mystr, int(mystr_len)],
  Tout=tf.string
)
```

**Will this change the current API? How?**
A new method (or methods) will be added to `tf.strings` for SHA-512 hashing. Other methods may include other types of hashing. Alternatively, a TF addon could be created for hashing/encrypting `tf.string`s. 

**Who will benefit with this feature?**
Users who use TensorFlow for research relating to encryption systems.

**Any Other info.**
Python's `hashlib.sha512` source is here: https://github.com/python/cpython/blob/1ae035b7e847064d09df01ca62b8a761e9b5aae3/Modules/sha512module.c

**Comment by cantonios** [comment]
This likely belongs outside of core TF.  We are trying to minimize the API surface.
