### ISSUE TITLE
Installation failed on Mac OS X with protobuf 3.0.0b2

### ISSUE THREAD

**Issue by ttomato** [tensorflow/tensorflow#3983]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:
Mac OS X 10.11.6

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
No CUDA

If installed from binary pip package, provide:
1. Which pip package you installed.
# Mac OS X, CPU only, Python 2.7:
$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.10.0rc0-py2-none-any.whl

log:
Requirement already satisfied (use --upgrade to upgrade): tensorflow==0.10.0rc0 from https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.10.0rc0-py2-none-any.whl in ./tensorflow/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): mock>=2.0.0 in /usr/local/lib/python2.7/site-packages (from tensorflow==0.10.0rc0)
Requirement already satisfied (use --upgrade to upgrade): six>=1.10.0 in /usr/local/lib/python2.7/site-packages/six-1.10.0-py2.7.egg (from tensorflow==0.10.0rc0)
Requirement already satisfied (use --upgrade to upgrade): protobuf==3.0.0b2 in /usr/local/lib/python2.7/site-packages (from tensorflow==0.10.0rc0)
Requirement already satisfied (use --upgrade to upgrade): wheel in ./tensorflow/lib/python2.7/site-packages (from tensorflow==0.10.0rc0)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.10.1 in /usr/local/lib/python2.7/site-packages/numpy-1.11.1-py2.7-macosx-10.11-x86_64.egg (from tensorflow==0.10.0rc0)
Requirement already satisfied (use --upgrade to upgrade): funcsigs>=1; python_version < "3.3" in /usr/local/lib/python2.7/site-packages (from mock>=2.0.0->tensorflow==0.10.0rc0)
Requirement already satisfied (use --upgrade to upgrade): pbr>=0.11 in /usr/local/lib/python2.7/site-packages (from mock>=2.0.0->tensorflow==0.10.0rc0)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/site-packages/setuptools-26.0.0-py2.7.egg (from protobuf==3.0.0b2->tensorflow==0.10.0rc0)

And the version of the protobuf is 3.0.0b2.

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ttomato/tensorflow/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/Users/ttomato/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/ttomato/tensorflow/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/Users/ttomato/tensorflow/lib/python2.7/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/Users/ttomato/tensorflow/lib/python2.7/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/Users/ttomato/tensorflow/lib/python2.7/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 22, in <module>
    serialized_pb=_b('\n,tensorflow/core/framework/tensor_shape.proto\x12\ntensorflow\"z\n\x10TensorShapeProto\x12-\n\x03\x64im\x18\x02 \x03(\x0b\x32 .tensorflow.TensorShapeProto.Dim\x12\x14\n\x0cunknown_rank\x18\x03 \x01(\x08\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\tB2\n\x18org.tensorflow.frameworkB\x11TensorShapeProtosP\x01\xf8\x01\x01\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'

### Steps to reproduce
1. Pip install.
2.
3.

### What have you tried?
1. Tried a lot of times with "pip install --upgrade portobuf". And make sure the version of protobuf is correct.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by prb12** [comment]
Please see https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#protobuf-library-related-issues

If these instructions do not solve your problem, then please re-open, providing the **exact** sequence of commands you typed.

**Comment by vrv** [comment]
(You almost certainly have a stale copy of python protobuf 2.0 installed somewhere, because that's what the error message indicates).
