### ISSUE TITLE
Differences between model.load_weights and checkpoint.restore

### ISSUE THREAD

**Issue by BSlience** [tensorflow/tensorflow#39843]
I can checkpoint.restore(ckfile) without any questions, but raise `Nothing except the root object matched a checkpointed value. Typically this means that the checkpoint does not match the Python program.` by model.load_weights(ckfile). I want to know what's the differences between these two api.

Thank you.

**Comment by saberkun** [comment]
Hi @BSlience, tf.train.Checkpoint and model.load/save_weights are not compatible.
When you use tf.train.Checkpoint, you will specific objects as kwargs. However, they are not recognized by the keras model. So you must use checkpoint save() and restore() together.
See the comment here: https://github.com/tensorflow/tensorflow/blob/2560d6fd31b20e81a5a98a73f325fb1dcf0c68a7/tensorflow/python/keras/engine/training.py#L1976
BTW, this also confused me many times....

**Comment by BSlience** [comment]
Thanks a lot.@Saduf2019.  It's mean that two kinds of checkpoint in tf2. `Model` checkpoint only can be loaded by model_weight and also `Checkpoint` checkpoint only loaded by `Checkpoint.restore`. `CheckpointCallback` is Model checkpoint.
```python
EPOCHS = 10
checkpoint_filepath = '/tmp/checkpoint'
model_checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_filepath,
    save_weights_only=True,
    monitor='val_acc',
    mode='max',
    save_best_only=True)

# Model weights are saved at the end of every epoch, if it's the best seen
# so far.
model.fit(epochs=EPOCHS, callbacks=[model_checkpoint_callback])

# The model weights (that are considered the best) are loaded into the model.
model.load_weights(checkpoint_filepath)
```
