### ISSUE TITLE
`tf.keras.models.clone_model` does not support custom model

### ISSUE THREAD

**Issue by CNOCycle** [tensorflow/tensorflow#39856]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 18.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary): **pip**
- TensorFlow version (use command below): **2.2.0**
- Python version: **Python 3.6.10 :: Anaconda, Inc.**
- Bazel version (if compiling from source): **N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **CUDA 10.1**
- GPU model and memory: **GeForce RTX 2080 Ti**

**Describe the current behavior**

In TF2.2.0 release notes, it said 
> * You can now use custom training logic with `Model.fit` by overriding `Model.train_step`
> * Easily write state-of-the-art training loops without worrying about all of the features `Model.fit` handles for you (distribution strategies, callbacks, data formats, looping logic, etc)

I have implemented my own custom model whose `train_step` is overwrited, And I want to create an identical model by API `tf.keras.models.clone_model`.

But, the problem there is that my custom `train_step` is gone.

**Describe the expected behavior**

`tf.keras.models.clone_model` should copy not only model's layers but also `train_step`.

**Standalone code to reproduce the issue**
```python
#%%
import numpy as np
import tensorflow as tf
print(tf.__version__)

#%% 
class Composite(tf.keras.Model):
    def __init__(self, *args, **kwargs):

        super(Composite, self).__init__(*args, **kwargs)

    def train_step(self, data):

        data_adapter = tf.python.keras.engine.data_adapter
        data = data_adapter.expand_1d(data)
        x, y, sample_weight = data_adapter.unpack_x_y_sample_weight(data)

        tf.print("HIHI! I'm in function train_step!")

        with tf.GradientTape() as tape:
            y_pred = self(x, training=True)
            loss = self.compiled_loss(
                y, y_pred, sample_weight, regularization_losses=self.losses)

        _minimize = tf.python.keras.engine.training._minimize
        _minimize(self.distribute_strategy, tape, self.optimizer, loss,
                self.trainable_variables)

        self.compiled_metrics.update_state(y, y_pred, sample_weight)
        return {m.name: m.result() for m in self.metrics}

in_ = tf.keras.layers.Input(shape=(10, ) )
x = tf.keras.layers.Dense(1)(in_)
model = Composite(inputs=in_, outputs=x)
model.compile(loss='binary_crossentropy',optimizer='SGD', metrics=['accuracy'])

X = np.zeros((10,10))
Y = np.zeros((10,1))
model.fit(X,Y,verbose=2)

# %%
new_model = tf.keras.models.clone_model(model)
new_model.compile(loss='binary_crossentropy',optimizer='SGD', metrics=['accuracy'])
new_model.fit(X,Y,verbose=2)
```

**Other info / logs** 
```
there is the original model
HIHI! I'm in function train_step!
1/1 - 0s - loss: 0.0000e+00 - accuracy: 1.0000
<tensorflow.python.keras.callbacks.History at 0x7fa9603dd6a0>
there is the NEW model
1/1 - 0s - loss: 0.0000e+00 - accuracy: 1.0000
<tensorflow.python.keras.callbacks.History at 0x7fa96023bbe0>
```

From the console, you will see the output `HIHI! I'm in function train_step!` is gone when I run `new_model.fit(X,Y,verbose=2)`

**Comment by CNOCycle** [comment]
An alternative solution is:
```python
wrap_model = Composite(inputs=new_model.input, outputs=new_model.output) 
wrap_model.compile(loss='binary_crossentropy',optimizer='SGD', metrics=['accuracy'])
wrap_model.fit(X,Y,verbose=2)
```

I don't think this is good solution but it is an acceptable choice.

If `tf.keras.models.clone_model` can not support custom model. It should be emphasized in the document.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/2dce07b4fdce8b8c64a159955602b76d/39856.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/94e7f9d3fea0c318f91ecbdaf7460861/39856-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by candlewill** [comment]
Yes. Same problem here.

**Comment by saikumarchalla** [comment]
@CNOCycle When i executed the code in TF 2.6 I  am facing different error when called fit method. Please find the [gist](https://colab.research.google.com/gist/saikumarchalla/f1391267be62299c0d50eadff110e9e5/nighly.ipynb) here.Thanks!

**Comment by CNOCycle** [comment]
@saikumarchalla  because tf.python is hidden in newer TF. So I updated the testing code:
```python
#%%
import numpy as np
import tensorflow as tf
print(tf.__version__)

#%% 
class Composite(tf.keras.Model):
    def __init__(self, *args, **kwargs):

        super(Composite, self).__init__(*args, **kwargs)

    def unpack_x_y_sample_weight(self, data):
        """Unpacks user-provided data tuple."""
        if not isinstance(data, tuple):
            return (data, None, None)
        elif len(data) == 1:
            return (data[0], None, None)
        elif len(data) == 2:
            return (data[0], data[1], None)
        elif len(data) == 3:
            return (data[0], data[1], data[2])

    def train_step(self, data):

        x, y, sample_weight = self.unpack_x_y_sample_weight(data)

        tf.print("HIHI! I'm in function train_step!")

        with tf.GradientTape() as tape:
            y_pred = self(x, training=True)
            loss = self.compiled_loss(
                y, y_pred, sample_weight, regularization_losses=self.losses)

        self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
        return {m.name: m.result() for m in self.metrics}

in_ = tf.keras.layers.Input(shape=(10, ) )
x = tf.keras.layers.Dense(1)(in_)
model = Composite(inputs=in_, outputs=x)
model.compile(loss='binary_crossentropy',optimizer='SGD', metrics=['accuracy'])

X = np.zeros((10,10))
Y = np.zeros((10,1))

print("the original model")
model.fit(X,Y,verbose=2)

# %%
print("cloned model")
new_model = tf.keras.models.clone_model(model)
new_model.compile(loss='binary_crossentropy',optimizer='SGD', metrics=['accuracy'])
new_model.fit(X,Y,verbose=2)

print("the original model again")
model.fit(X,Y,verbose=2)
```

Here is the output
```2.6.0-dev20210601
the original model
HIHI! I'm in function train_step!
1/1 - 0s - loss: 0.0000e+00 - accuracy: 1.0000
cloned model
1/1 - 0s - loss: 0.0000e+00 - accuracy: 1.0000
the original model again
HIHI! I'm in function train_step!
1/1 - 0s - loss: 0.0000e+00 - accuracy: 1.0000

<tensorflow.python.keras.callbacks.History at 0x7ff9a5852490>
```

Obviously, this issue has not been fixed

**Comment by innat** [comment]
I think subclassed API model is not supported in the `clone_model` function, see the document 

https://www.tensorflow.org/api_docs/python/tf/keras/models/clone_model

```
Args 
--  model | Instance of Model (could be a Functional model or a Sequential model).
....
....
```

**Comment by CNOCycle** [comment]
I thought that this problem has not been solved yet.

**Comment by groovemaxRong** [comment]
still has this issue in tf2.7, any progress in this bug?

**Comment by innat** [comment]
@groovemaxRong you can post a feature request in the keras Github repo regarding this.

**Comment by shubham-malaviya** [comment]
I am working with Tf 4.0 and am able to solve this issue with the following:

Here is an example of cloning a model having a custom layer class `CustomLayer`

```
class CustomLayer(tf.keras.layers.Layer):
 
    def __init__(self, **kwargs):
        super(CustomLayer, self).__init__()

    def call(self, input_tensor):
        return input_tensor
```
What you need to do is register this custom object with the Keras scope as follows:
```
custom_objects = {"CustomLayer": CustomLayer}
with tf.keras.utils.custom_object_scope(custom_objects):
    new_model = tf.keras.models.clone_model(model)
```
