### ISSUE TITLE
device_spec from_string method not accepting some inputs

### ISSUE THREAD

**Issue by philippeller** [tensorflow/tensorflow#39857]
The method `from_string` of `tensorflow.python.framework.device_spec` does not accept device names reported by `tf` itself:

`tf.config.list_physical_devices()` returns device names of the form `'/physical_device:GPU:0'`, However `from_string` does not accept this as input. Only works when `'/physical_device:'` is cut out.

**Expected behaviour:**
```python
tensorflow.python.framework.device_spec.DeviceSpecV2().from_string('/physical_device:GPU:0')
<tensorflow.python.framework.device_spec.DeviceSpecV2 at 0x7f7ec46fe8a0>
```

**Actual behaviour:**
```python
tensorflow.python.framework.device_spec.DeviceSpecV2().from_string('/physical_device:GPU:0')
ValueError: Unknown attribute: 'physical_device' in '/physical_device:GPU:0'
```

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.Please, fill [issue template.](https://github.com/tensorflow/tensorflow/issues/new/choose).Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by philippeller** [comment]
system: Linux 4.15.0-99-generic #100~16.04.1-Ubuntu x86_64 GNU/Linux
tensorflow-gpu v2.2.0 installed via pip
Python 3.7.4 (default, Aug 13 2019, 20:35:49)                                                                                                                              [GCC 7.3.0] :: Anaconda, Inc. on linux  

Minimal example:
```python
tf.python.framework.device_spec.DeviceSpecV2().from_string(tf.config.list_physical_devices()
[0].name)
```
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/device_spec.py", line 157, in from_string
return cls(*cls._string_to_components(spec))
File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/device_spec.py", line 344, in _string_to_components
raise ValueError("Unknown attribute: '%s' in '%s'" % (y[0], spec))
ValueError: Unknown attribute: 'physical_device' in '/physical_device:CPU:0'
```

**Comment by sanjoy** [comment]
@jaingaurav do you want to take this?

**Comment by mypey** [comment]
Hi,
I encountered the same issue. My workaround is to use `tf.config.list_physical_devices()` instead of `tf.config.list_logical_devices()` but I am not really satisfied.
Any new about this problem?
Thanks!

**Comment by sushreebarsa** [comment]
@philippeller  Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!

**Comment by philippeller** [comment]
Hi, looks to me as this is still the same issue in tf 2.5:
```python
>>> tf.DeviceSpec().from_string(tf.config.list_physical_devices()[0].name)                                                                                                                                                                    
raise ValueError("Unknown attribute: '%s' in '%s'" % (y[0], spec))
ValueError: Unknown attribute: 'physical_device' in '/physical_device:CPU:0'
>>> tf.__version__
'2.5.0'
```

**Comment by tiruk007** [comment]
This issue still persists on the latest TF V2.11 and Tf-nightly. Please find the gist of [2.11](https://colab.research.google.com/gist/tiruk007/ef553874e285a7572fd774eaebc0d70b/untitled41.ipynb) and [tf-nightly](https://colab.research.google.com/gist/tiruk007/c6e0f0a4eac860093f068cea8be5dbce/untitled41-nightly.ipynb) for reference .
Thank you!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
