### ISSUE TITLE
Unable to calculate gradient -> AttributeError: 'Tensor' object has no attribute 'numpy'

### ISSUE THREAD

**Issue by lokesharma-dev** [tensorflow/tensorflow#39858]
**System information**
- OS Platform and Distribution: macOS Catalina
- TensorFlow installed from (source or binary): Google Colab
- TensorFlow version: >=2.0
- Python version: 3.6

** I want to compute the gradient for KL Divergence ( between two distributions aka logits) with respect to noise (kind of input and not wrt weights). It was possible with Tensorflow 1.0 but using GradientTape seems to return me a None for "grads" which I am unable to comprehend**

Code:

import tensorflow as tf
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Input, Embedding, Dense, LSTM, Bidirectional

MAX_VOCAB_SIZE = 10000 # maximum no of unique words
MAX_DOC_LENGTH = 500 # maximum no of words in each sentence
EMBEDDING_DIM = 300 # Embeddings dimension from Glove directory
def compute_kld(p_logit, q_logit): # computes difference between two distributions
  p = tf.nn.softmax(p_logit)
  q = tf.nn.softmax(q_logit)
  kl_score = tf.reduce_sum( p * (tf.math.log(p+1e-16) - tf.math.log(q+1e-16)), axis = 1)
  return kl_score # Scalar -> lower kl means closer the distributions are closer

# Create Embeddings
inputs2d = Input(shape=(MAX_DOC_LENGTH,)) # takes a sequence of words
clean_embd= Embedding(input_dim=MAX_VOCAB_SIZE + 1, output_dim=EMBEDDING_DIM,
                      input_length=MAX_DOC_LENGTH)(inputs2d) # converts each input to embedding matrix
r_embd = tf.random.uniform(shape=tf.shape(clean_embd)) # random noise to be added to clean_embd

# Create Model
inputs3d = Input(shape=(MAX_DOC_LENGTH, EMBEDDING_DIM,)) # Embedding shall be my input to the model
network = Sequential()
network.add(LSTM(units=128,))
network.add(Dense(units=16, activation='relu'))
output = network(inputs3d)
model = Model(inputs3d, output)
model.summary()

# Calculate gradient
with tf.GradientTape(watch_accessed_variables=False) as tape:
    tape.watch(r_embd)
    r_embd_ = tf.math.add(clean_embd, r_embd) # Noised input
    # Compute logits
    p_logit = model(clean_embd) # True logit distribution
    p_logit_r = model(r_embd_) # Perturbed logits distribution
    # Find the Kl Score
    kl_score = tf.reduce_mean(compute_kld(p_logit, p_logit_r))
    kl_score = tf.convert_to_tensor(kl_score, dtype=tf.float32)
**grads = tape.gradient(kl_score, r_embd) # I wish to differentiate kl_score wrt r_embd. So the Jacobian matrix should be of shape (None, 500, 300) similar to (clean_embd | r_embd_).**

**# Error is that grads is returned as None; which I can't understand.**

# Future implementation
r_vadv_embd = tf.math.add(clean_embd, g)
**q_logits = model(r_vadv_embd) # End goal is to be able to calculate q_logit**

**Any other info / logs**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-f19b613537c7> in <module>()
     15     kl_score = tf.reduce_mean(compute_kld(p_logit, p_logit_r))
     16     kl_score = tf.convert_to_tensor(kl_score, dtype=tf.float32)
---> 17 grads = tape.gradient(kl_score, r_embd)
     18 
     19 # g = [grad if grad is not None else tf.zeros_like(var)for var, grad in zip(r_embd, grads)]

4 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/backprop.py in gradient(self, target, sources, output_gradients, unconnected_gradients)
   1046         output_gradients=output_gradients,
   1047         sources_raw=flat_sources_raw,
-> 1048         unconnected_gradients=unconnected_gradients)
   1049 
   1050     if not self._persistent:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/imperative_grad.py in imperative_grad(tape, target, sources, output_gradients, sources_raw, unconnected_gradients)
     75       output_gradients,
     76       sources_raw,
---> 77       compat.as_str(unconnected_gradients.value))

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/backprop.py in _gradient_function(op_name, attr_tuple, num_inputs, inputs, outputs, out_grads, skip_input_indices, forward_pass_name_scope)
    155       gradient_name_scope = "gradient_tape/"
    156     with ops.name_scope(gradient_name_scope):
--> 157       return grad_fn(mock_op, *out_grads)
    158   else:
    159     return grad_fn(mock_op, *out_grads)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py in _SumGrad(op, grad)
    210       # more sense.
    211       output_shape_kept_dims = math_ops.reduced_shape(input_shape,
--> 212                                                       op.inputs[1])
    213     grad = array_ops.reshape(grad, output_shape_kept_dims)
    214   return [array_ops.broadcast_to(grad, input_shape), None]

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py in reduced_shape(input_shape, axes)
   3733   """
   3734   if context.executing_eagerly():
-> 3735     input_shape = input_shape.numpy()
   3736     axes = axes.numpy()
   3737     input_shape[axes] = 1

AttributeError: 'Tensor' object has no attribute 'numpy'

**Comment by Saduf2019** [comment]
@lokesharma-dev 
Can you please refer to these links and let us know if it helps:
[link](https://github.com/tensorflow/tensorflow/issues/39817#issuecomment-633675341) [link1](https://stackoverflow.com/questions/52357542/attributeerror-tensor-object-has-no-attribute-numpy) [link2](https://www.reddit.com/r/learnmachinelearning/comments/c1j7i5/attributeerror_tensor_object_has_no_attribute/) [link3](https://www.kaggle.com/c/prostate-cancer-grade-assessment/discussion/146248) #39582 #35949 #36979

**Comment by lokesharma-dev** [comment]
Thanks a lot! This was of help and we can close the issue now.

**Comment by EvsanDlg** [comment]
@lokesharma-dev so what was the solution for you? I refered all that links and didn't get the answer for me. With tf 2.0 eager execution is enabled, but I see the problem, as you had, in standart reduced_shape function, not in the custom one. I'm confused what to do with this

**Comment by lokesharma-dev** [comment]
@EvsanDlg Well TensorFlow 2.x is tricky at times especially the exceptions they provide.  
My issue was fixed when I was using an EagerTensor instead of the tensor object. In tf1.x we could compute gradient wrt to a tensor with no data inside it. I do not understand how I was getting an error relating to NumPy() conversion. However, in your case, I won't be able to comment unless have some more information.
Hope this helps.

**Comment by abmiitd** [comment]
@lokesharma-dev i am facing the same issue...can you help as to how you solved the issue by using an eagertensor ??
