### ISSUE TITLE
Freeze graph: node is not in graph (even though it's been named)

### ISSUE THREAD

**Issue by cardshuffle** [tensorflow/tensorflow#3986]
### Environment info

Operating System: Ubuntu 14.04 LTS 64-bit

Installed version of CUDA and cuDNN: none

If installed from source, provide 
1. The commit hash (`git rev-parse HEAD`): fc9162975e52978d3af38549b570cc3cc5f0ab66
2. The output of `bazel version`

```
Build label: 0.3.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 10 11:38:23 2016 (1465558703)
Build timestamp: 1465558703
Build timestamp as int: 1465558703
```
### Steps to reproduce
1. Copy the IPython Notebook for Assignment 6 of Udacity's deep learning course ([here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/udacity/6_lstm.ipynb))
2. Change `saved_sample_output = tf.Variable(tf.zeros([1, num_nodes]))` to `saved_sample_output = tf.Variable(tf.zeros([1, num_nodes]), name="saved_sample_output")`
3. Modify the code like so:

``` python
with tf.Session(graph=graph) as session:
  tf.initialize_all_variables().run()
  print('Initialized')
  mean_loss = 0
  # code omitted (no changes)
  # new code below:
  saver = tf.train.Saver(tf.all_variables())
  saver.save(session, '/home/me/Documents/checkpoint.ckpt', write_meta_graph=False)
  tf.train.write_graph(graph.as_graph_def(), '/home/me/Documents', 'graph.pb')
```
1. Run.
2. Verify that `checkpoint.ckpt` and `graph.pb` have been successfully created in the directory.
3. In the tensorflow source directory, run:

```
bazel build tensorflow/python/tools:freeze_graph && bazel-bin/tensorflow/python/tools/freeze_graph --input_graph=/home/me/Documents/graph.pb --input_checkpoint=/home/me/Documents/checkpoint.ckpt --output_graph=/home/me/Documents/frozen_graph.pb --output_node_names=saved_sample_output
```
### What have you tried?

Checked the `graph.pb` file to make sure that node had actually been named properly. Seems like it was:

```
# other stuff
node {
  name: "saved_sample_output"
  op: "Variable"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 64
        }
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
# etc.
```

I'm pretty much stumped with this one since [this](https://stackoverflow.com/questions/38958662/tensorflow-what-are-the-output-node-names-for-freeze-graph-py-in-the-model-wi) issue on StackOverflow says to pass in a name parameter for the node you want, which is what I did, to no avail (even without the name parameter, it still gave the same error).
**Edit:** Got freeze_graph to run successfully with the `sample_prediction` node (changed `sample_prediction = tf.nn.softmax(tf.nn.xw_plus_b(sample_output, w, b))` to `sample_prediction = tf.nn.softmax(tf.nn.xw_plus_b(sample_output, w, b), name="sample_prediction")`). However, I still haven't figured out why that worked, and this didn't.
### Logs or other output that would be helpful

```
Traceback (most recent call last):
  File "/home/me/tf_m/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 134, in <module>
    tf.app.run()
  File "/home/me/tf_m/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/me/tf_m/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 131, in main
    FLAGS.output_graph, FLAGS.clear_devices, FLAGS.initializer_nodes)
  File "/home/me/tf_m/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 120, in freeze_graph
    sess, input_graph_def, output_node_names.split(","))
  File "/home/me/tf_m/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/framework/graph_util.py", line 232, in convert_variables_to_constants
    inference_graph = extract_sub_graph(input_graph_def, output_node_names)
  File "/home/me/tf_m/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/framework/graph_util.py", line 156, in extract_sub_graph
    assert d in name_to_node_map, "%s is not in graph" % d
AssertionError: saved_sample_output is not in graph
```

**Comment by civilmanxx** [comment]
I meet the similar issue.

**Comment by tomx** [comment]
Facing the same issue here as well. Trying to freeze weights into graphDef proto and passing in anything into the output node name seems to give error like the one above.

**Comment by Pouyan-Jahangiri** [comment]
@petewarden I get the same error when I try to freeze_graph.py. I would appreciate if you could help me with this: 

WARNING: /home/pouyanj/.cache/bazel/_bazel_pouyanj/0e1d84e60e1e91548f16e1302589059b/external/protobuf/protobuf.bzl:90:19: Variables HOST_CFG and DATA_CFG are deprecated in favor of strings "host" and "data" correspondingly.
WARNING: /home/pouyanj/.cache/bazel/_bazel_pouyanj/0e1d84e60e1e91548f16e1302589059b/external/protobuf/protobuf.bzl:96:28: Variables HOST_CFG and DATA_CFG are deprecated in favor of strings "host" and "data" correspondingly.
WARNING: /home/pouyanj/.cache/bazel/_bazel_pouyanj/0e1d84e60e1e91548f16e1302589059b/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/profiling/instrumentation.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/pouyanj/.cache/bazel/_bazel_pouyanj/0e1d84e60e1e91548f16e1302589059b/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/profiling/profiler.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/pouyanj/.cache/bazel/_bazel_pouyanj/0e1d84e60e1e91548f16e1302589059b/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/bit_depth.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/pouyanj/.cache/bazel/_bazel_pouyanj/0e1d84e60e1e91548f16e1302589059b/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/gemmlowp.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/pouyanj/.cache/bazel/_bazel_pouyanj/0e1d84e60e1e91548f16e1302589059b/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/map.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
WARNING: /home/pouyanj/.cache/bazel/_bazel_pouyanj/0e1d84e60e1e91548f16e1302589059b/external/gemmlowp/BUILD:102:12: in hdrs attribute of cc_library rule @gemmlowp//:eight_bit_int_gemm: Artifact 'external/gemmlowp/public/output_stages.h' is duplicated (through '@gemmlowp//:eight_bit_int_gemm_public_headers' and '@gemmlowp//:gemmlowp_headers').
INFO: Found 1 target...
Target //tensorflow/python/tools:freeze_graph up-to-date:
  bazel-bin/tensorflow/python/tools/freeze_graph
INFO: Elapsed time: 7.444s, Critical Path: 0.20s
Traceback (most recent call last):
  File "/home/pouyanj/Desktop/tensorflow-r0.11/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 134, in <module>
    tf.app.run()
  File "/home/pouyanj/Desktop/tensorflow-r0.11/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/pouyanj/Desktop/tensorflow-r0.11/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 131, in main
    FLAGS.output_graph, FLAGS.clear_devices, FLAGS.initializer_nodes)
  File "/home/pouyanj/Desktop/tensorflow-r0.11/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 120, in freeze_graph
    sess, input_graph_def, output_node_names.split(","))
  File "/home/pouyanj/Desktop/tensorflow-r0.11/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/framework/graph_util.py", line 234, in convert_variables_to_constants
    inference_graph = extract_sub_graph(input_graph_def, output_node_names)
  File "/home/pouyanj/Desktop/tensorflow-r0.11/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/framework/graph_util.py", line 158, in extract_sub_graph
    assert d in name_to_node_map, "%s is not in graph" % d
AssertionError: softmax is not in graph

**Comment by kevinashaw** [comment]
Me too!

**Comment by drpngx** [comment]
@kevinashaw just to be sure, did you check on `master`?

**Comment by drpngx** [comment]
Ping anyone?

**Comment by girving** [comment]
Closing due to lack of response.

**Comment by saria85** [comment]
Hi all,
I am getting this error
in extract_sub_graph
    assert d in name_to_node_map, "%s is not in graph" % d
AssertionError: predictions is not in graph,

what that mean sub graph?

I am sure that the name of my output is correct,

this is my code for freezing:

dir = os.path.dirname(os.path.realpath(__file__))
tf.train.write_graph(sess.graph_def, '/home/saria/Downloads/sentiment_analysis_tensorflow-master', 'har.pbtxt')
saver.save(sess,save_path = "../har.ckpt")

freeze_graph.freeze_graph(input_graph = "../har.pbtxt",  input_saver = "",
             input_binary = False, input_checkpoint = "../har.ckpt", output_node_names = "predictions",
             restore_op_name = "save/restore_all", filename_tensor_name = "save/Const:0",
             output_graph = "frozen_har.pb", clear_devices = True, initializer_nodes = "")

input_graph_def = tf.GraphDef()

may please some one help with this problem, I am get stuck in this error no ways for getting the right answer

**Comment by geometrikal** [comment]
Write the graph as a text file using `as_text=True` in `write_graph`.
Open the graph file, it will have some node entries written in plane text.
Check the node name you are passing is in the graph file. When I had the same problem, the actual node name had some extra parts on the end.

**Comment by SanthoshMKunthe** [comment]
Bro check you node nameing convention. . . Naming of "matmul function to output" and "x placeholder to input". . .

**Comment by tonywangcn** [comment]
@SanthoshMKunthe Is there any possible to print all the node name in Graph? Checked the code and didn't find anything about the naming you mentioned. Thanks!

**Comment by SanthoshMKunthe** [comment]
Use json viewer. . . It helped me to solve mis naming problem. . . Its one of the solution, look for other possibilities to be sure. . .

**Comment by tonywangcn** [comment]
I used this function to get all the node names, but more than 10000 nodes are really crazy for me to figure out the one that belong to me......  print(len([n.name for n in tf.get_default_graph().as_graph_def().node]))

**Comment by moss-khaldi** [comment]
yes, the node name is incorrect according to the .pb file, you have to print the actual name used during the saving by print <name-of-model>.output.op.name same with input if that happened occasionally <name-of-model>.input.op.name, then you can use the printed name as an argument in the export function.
i hope this solved the problem.

**Comment by iamgroot42** [comment]
@moss-khaldi how did you print the output node name while saving? It isn't available for estimators using the access method you've mentioned (model,output.op.name).

**Comment by moss-khaldi** [comment]
@iamgroot42 Hi, after the building of the network use `print model.output.op.name` and by `model` i mean the name of the model you have used.

**Comment by iamgroot42** [comment]
Oh. Keras wasn't mentioned in your comments anywhere; I assumed it's for Estimator.

**Comment by moss-khaldi** [comment]
Sorry, i just cleared my answer 😊.

**Comment by SystemErrorWang** [comment]
I met similar issue, even after i print out all the node name by using `print([node.name for node in graph.as_graph_def().node])` and chose a name from them, the freeze_graph.py still return `AssertionError: MobileNet/Predictions/Softmax is not in graph`

**Comment by YoussefBenDhieb** [comment]
I got the same error, then when I printed the node names using
`out_names = [x.op.name for x in model.outputs]` I got u'activation_1_1/Sigmoid' as a name but it did not work.
Then I searched in the generated tmp.pb file for Sigmoid and the name I found is "activation_1/Sigmoid".
I used it and it worked!

**Comment by dassi25** [comment]
@YoussefBenDhieb how did you search  in tmp.pb , can you please tell step by step.

**Comment by YoussefBenDhieb** [comment]
@dassi25 You open the tmp.pb file using an editor like Sublime or Visual Studio Code and you search for the name of the activation, in my case it is Sigmoid. Also, I had only one sigmoid activation in the graph, but even if you have many, usually it will be the last one.

**Comment by wysohn** [comment]
I faced the same problem, and the `saved_model_cli` command saved me. (https://www.tensorflow.org/guide/saved_model)

So if you are in a linux environment and has tensorflow installed, you can enter the following command.

`saved_model_cli show --dir ./ --all`

of course, use the directory path of yours

It will show something like below:

    outputs['output'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 512)
        name: some/kind/of/tensor/Add:0

Then your name should be `some/kind/of/tensor/Add` without the numbering

**Comment by jiayiliu** [comment]
Just in case - I found the eager execution caused my problem.

**Comment by phamdanglam** [comment]
Hi all, 
In my network, I make name of node with 'name = 'prob' as code below

self.prob_output_layer = tf.nn.softmax(self.output_layer, name='prob')

--> and we expect that node name should be 'prob'

But we need to check the file.pb 

node {
  name: "dnn_01/Softmax"
  op: "Softmax"
  input: "dnn_01/fully_layer03/fully_layer03/Add_1"
  device: "/device:GPU:0"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
--> We found that node name is 'dnn_01/Softmax'

Therefore, we need use 'dnn_01/Softmax' name when freezing

**Comment by Nannigalaxy** [comment]
As I was using tensorflow 2.0, my issue got solved by disabling v2 behavior.

```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```

**Comment by InCogNiTo124** [comment]
I had the error, but my problem was that I was iterating over the `tf.GraphDef.node` and modifying that list at the same time (inserting and removing nodes) so be careful not to do that

**Comment by Sangpil-Han** [comment]
> I faced the same problem, and the `saved_model_cli` command saved me. (https://www.tensorflow.org/guide/saved_model)
> 
> So if you are in a linux environment and has tensorflow installed, you can enter the following command.
> 
> `saved_model_cli show --dir ./ --all`
> 
> of course, use the directory path of yours
> 
> It will show something like below:
> 
> ```
> outputs['output'] tensor_info:
>     dtype: DT_FLOAT
>     shape: (-1, 512)
>     name: some/kind/of/tensor/Add:0
> ```
> 
> Then your name should be `some/kind/of/tensor/Add` without the numbering

I think it's not working in Tensorflow 1.15.2

**Comment by sivasweta** [comment]
> TF 2.3, my issue got solved by
> 
> ```
> import tensorflow.compat.v1 as tf
> tf.disable_v2_behavior()
> ```
> 
> I have no idea why this works.
> Explanation is welcome.

Yah its working thanks

**Comment by hoaquocphan** [comment]
Hi Mr @phamdanglam1986, @InCogNiTo124, @sivasweta, @Nannigalaxy @wysohn 

I used command **saved_model_cli show --all --dir efficientnet_b0_classification_1/** with the model from tensorflow hub, and the output as below:

```
MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['image_input'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1, -1, 3)
        name: serving_default_image_input:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['probs'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 1000)
        name: StatefulPartitionedCall:0
  Method name is: tensorflow/serving/predict

Defined Functions:
  Function Name: '__call__'
    Option #1
      Callable with:
        Argument #1
          image_input: TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='image_input')
        Argument #2
          DType: bool
          Value: False
        Argument #3
          DType: NoneType
          Value: None
    Option #2
      Callable with:
        Argument #1
          inputs: TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='inputs')
        Argument #2
          DType: bool
          Value: False
        Argument #3
          DType: NoneType
          Value: None
```

so how can I get the output_node_names? Please help me

**Comment by wysohn** [comment]
@hoaquocphan 
```
  The given SavedModel SignatureDef contains the following output(s):
    outputs['probs'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 1000)
        name: StatefulPartitionedCall:0
```

Probably it's StatefulPartitionedCall, but I am not entirely sure

**Comment by hoaquocphan** [comment]
hi @wysohn 

it is ok with this model, but when I tried with other models from tensorflow hub  as below:
```
saved_model_cli show --all --dir imagenet_mobilenet_v1_025_128_classification_4/
saved_model_cli show --all --dir imagenet_resnet_v1_50_classification_4/
saved_model_cli show --all --dir tf2-preview_inception_v3_classification_4/
```

the output as below:

```
MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 

Defined Functions:
  Function Name: '__call__'
    Option #1
      Callable with:
        Argument #1
          inputs: TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='inputs')
        Argument #2
          DType: bool
          Value: True
        Argument #3
          DType: bool
          Value: True
        Argument #4
          batch_norm_momentum: TensorSpec(shape=(), dtype=tf.float32, name='batch_norm_momentum')
    Option #2
      Callable with:
        Argument #1
          inputs: TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='inputs')
        Argument #2
          DType: bool
          Value: True
        Argument #3
          DType: bool
          Value: False
        Argument #4
          batch_norm_momentum: TensorSpec(shape=(), dtype=tf.float32, name='batch_norm_momentum')
    Option #3
      Callable with:
        Argument #1
          inputs: TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='inputs')
        Argument #2
          DType: bool
          Value: False
        Argument #3
          DType: bool
          Value: False
        Argument #4
          batch_norm_momentum: TensorSpec(shape=(), dtype=tf.float32, name='batch_norm_momentum')
    Option #4
      Callable with:
        Argument #1
          inputs: TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='inputs')
        Argument #2
          DType: bool
          Value: False
        Argument #3
          DType: bool
          Value: True
        Argument #4
          batch_norm_momentum: TensorSpec(shape=(), dtype=tf.float32, name='batch_norm_momentum')
```

so how can I get the  **output_node_names**? Please help me

**Comment by wysohn** [comment]
@hoaquocphan 

> hi @wysohn
> 
> it is ok with this model, but when I tried with other models from tensorflow hub as below:
> 
> ```
> saved_model_cli show --all --dir imagenet_mobilenet_v1_025_128_classification_4/
> saved_model_cli show --all --dir imagenet_resnet_v1_50_classification_4/
> saved_model_cli show --all --dir tf2-preview_inception_v3_classification_4/
> ```
> 
> the output as below:
> 
> ```
> MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:
> 
> signature_def['__saved_model_init_op']:
>   The given SavedModel SignatureDef contains the following input(s):
>   The given SavedModel SignatureDef contains the following output(s):
>     outputs['__saved_model_init_op'] tensor_info:
>         dtype: DT_INVALID
>         shape: unknown_rank
>         name: NoOp
>   Method name is: 
> 
> Defined Functions:
>   Function Name: '__call__'
>     Option #1
>       Callable with:
>         Argument #1
>           inputs: TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='inputs')
>         Argument #2
>           DType: bool
>           Value: True
>         Argument #3
>           DType: bool
>           Value: True
>         Argument #4
>           batch_norm_momentum: TensorSpec(shape=(), dtype=tf.float32, name='batch_norm_momentum')
>     Option #2
>       Callable with:
>         Argument #1
>           inputs: TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='inputs')
>         Argument #2
>           DType: bool
>           Value: True
>         Argument #3
>           DType: bool
>           Value: False
>         Argument #4
>           batch_norm_momentum: TensorSpec(shape=(), dtype=tf.float32, name='batch_norm_momentum')
>     Option #3
>       Callable with:
>         Argument #1
>           inputs: TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='inputs')
>         Argument #2
>           DType: bool
>           Value: False
>         Argument #3
>           DType: bool
>           Value: False
>         Argument #4
>           batch_norm_momentum: TensorSpec(shape=(), dtype=tf.float32, name='batch_norm_momentum')
>     Option #4
>       Callable with:
>         Argument #1
>           inputs: TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='inputs')
>         Argument #2
>           DType: bool
>           Value: False
>         Argument #3
>           DType: bool
>           Value: True
>         Argument #4
>           batch_norm_momentum: TensorSpec(shape=(), dtype=tf.float32, name='batch_norm_momentum')
> ```
> 
> so how can I get the **output_node_names**? Please help me

For that, I am not really sure how to figure that out. It might not be named tensor or something, but it's out of my knowledge. There is a quote in the documentation, however, and it might provide some clue

> Key Point: Unless you need to export your model to an environment other than TensorFlow 2.x with Python, you probably don't need to export signatures explicitly. If you're looking for a way of  enforcing an input signature for a specific function, see the input_signature argument to tf.function.
