### ISSUE TITLE
'too many indices for array' exception depending on tensor length when masking a tensor

### ISSUE THREAD

**Issue by raharth** [tensorflow/tensorflow#39869]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10
- TensorFlow installed from (source or binary): via pip
- TensorFlow version (use command below): tensorflow 2.2.0
- Python version: 3.7.7
- CUDA/cuDNN version: 10.1
- GPU model and memory: Nvidia GTX 970

**Describe the current behavior**
I want to select possible indices based on the value of a tensor. In this case I want to get all possible indices of the tensor, where the entry of the tensor is smaller than some value.

Though depending solely on the length of a sequence it throws unexpected 'too many indices for array' exceptions.

Here is the minimal problem, that reproduces the error on my machine

```
# failing example
import numpy as np
import tensorflow as tf

sentence = tf.constant([2, 92, 79, 378, 12, 2, 1396, 596, 11, 142, 7, 1901, 6, 11, 9, 1263, 21394, 346, 5, 2, 3086, 4])
target_vocab_size = 1000
possible_indices = np.arange(len(sentence))[(sentence < target_vocab_size)]
```

If I now do nothing but enlarging the tensor, by simply copy pasting its values twice it works.

```
# working example
import numpy as np
import tensorflow as tf

sentence = tf.constant([2, 92, 79, 378, 12, 2, 1396, 596, 11, 142, 7, 1901, 6, 11, 9, 1263, 21394, 346, 5, 2, 3086, 4,
                        2, 92, 79, 378, 12, 2, 1396, 596, 11, 142, 7, 1901, 6, 11, 9, 1263, 21394, 346, 5, 2, 3086, 4])
target_vocab_size = 1000
possible_indices = np.arange(len(sentence))[(sentence < target_vocab_size)]
```

When explicitly calling .numpy() on the mask it also works with the shorter tensor

```import numpy as np
import tensorflow as tf

sentence = tf.constant([2, 92, 79, 378, 12, 2, 1396, 596, 11, 142, 7, 1901, 6, 11, 9, 1263, 21394, 346, 5, 2, 3086, 4])

target_vocab_size = 1000
possible_indices = np.arange(len(sentence))[(sentence < target_vocab_size).numpy()]
```

When replacing tensorflow with numpy all the way it works just fine as well

```import numpy as np

sentence = np.array([2, 92, 79, 378, 12, 2, 1396, 596, 11, 142, 7, 1901, 6, 11, 9, 1263, 21394, 346, 5, 2, 3086, 4])
target_vocab_size = 1000
possible_indices = np.arange(len(sentence))[(sentence < target_vocab_size)]
```

**Comment by Saduf2019** [comment]
@raharth 
Please refer to [this link](https://stackoverflow.com/questions/28036812/indexerror-too-many-indices-for-array) and let us know if it helps

**Comment by raharth** [comment]
@Saduf2019 
I have seen that post but I think it is a different problem.

If I run a loop over sentences of different length, it sometimes work sometimes it does not, even though all of them have the same shape (1D tensors). To demonstrate that I have added the code with a tensor of the same shape but a different length. Empirically it works with tensors longer than ~30 entries, but fails with shorter ones.

If you run the two first code snippets you should see the problem. The second array breaks the line, but it is still a 1D tensor! (sorry if that was not clear by the way I formatted it)

If I simply replace `tf.tensor` by `np.array` it works. If I explicitly call `.numpy()` on the mask it works as well for short and long sequences. So the problem shouldn't be related to the shape of the tensor.

**Comment by Saduf2019** [comment]
i am able to replicate this issue, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/d8fccfb3293a1a54dec5ae4361cfba68/untitled198.ipynb), Thanks!

**Comment by saikumarchalla** [comment]
I can able to reproduce the issue using TF 2.5 version and the issue still exists. Thanks!

**Comment by jvishnuvardhan** [comment]
@raharth What is the problem with `.numpy()` method. It works as expected right?  Can you add little more details on what was the problem. Thanks!

**Comment by raharth** [comment]
@jvishnuvardhan It works, yes, but I kind of have emotional trouble to rely on libs that (at least on my end) throw unpredictable and undescriptive errors :) but no for real, it throws a 'too many indices for array' exception depending on array/tensor length if the array is too **short**, so the error message seems to be unrelated to the issue and from the viewpoint of someone just using TF there is no apparent reason why the length of an input tensor that is a constant should lead to such behavior.
Thus, I just wanted to report the issue! :)

If you know the reason and could explain whats happening I would be highly interested though!

**Comment by mohantym** [comment]
Hi @raharth ! I think you were intending to use the above code by[ this way](https://colab.sandbox.google.com/gist/mohantym/a3b8188b9df3d5a94c6a4c1be457443a/untitled198.ipynb#scrollTo=qXWYKxBJrsh6).Attaching relevant threads for reference.[ link1](https://stackoverflow.com/questions/28036812/indexerror-too-many-indices-for-array),[link2](https://stackoverflow.com/questions/47733704/numpy-array-indexerror-too-many-indices-for-array/47733775)
