### ISSUE TITLE
sys.exc_info() can't put to queue in MultiProcessRunner

### ISSUE THREAD

**Issue by Hacky-DH** [tensorflow/tensorflow#39862]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):none
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:none
- TensorFlow installed from (source or binary):none
- TensorFlow version (use command below): master branch https://github.com/tensorflow/tensorflow/commit/498e5b4f6db80df13b54c44cbd657a2750067564
- Python version:nan
- Bazel version (if compiling from source):none
- GCC/Compiler version (if compiling from source):none
- CUDA/cuDNN version:none
- GPU model and memory:none

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
code line see [multi_process_runner.py:594](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/distribute/multi_process_runner.py#L594)

sys.exc_info() can't put to queue in MultiProcessRunner, because the traceback object can't be pickle, see [stackoverflow](https://stackoverflow.com/a/6132584).

when a subprocess raise an error, the line 497 of multi_process_runner.py will throw an error
`TypeError: can't pickle traceback objects`

**Describe the expected behavior**

Pls use other way to implement this. one way is using traceback.print_exc() or format_exc() functions. Don't put traceback objects in queue.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

none

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

none

**Comment by ravikyram** [comment]
@Hacky-DH 

Request you to provide colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by Hacky-DH** [comment]
I rewrite the MultiProcessRunner class, so it can run any where, not only in unittest.

See [link](https://github.com/Hacky-DH/learn/blob/master/tools/multi_process_runner.py#L200).

I use `traceback.print_exc()` fix this.

I don't test this in any unittest or colab.
