### ISSUE TITLE
tensorflow-lite as shared(dynamic) lib for C/C++ & linux/ubuntu

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#39876]
Hello

is there a way to build shared (dynamic) lib for TensorFlow-lite? If so, please share the steps to do so and possibly some simple example with it.

Thank you.

**Comment by yyoon** [comment]
You can build a shared library with the following command.

```sh
bazel build -c opt //tensorflow/lite:tensorflowlite
```

This will output the resulting shared library (`.dll`, `.so`, or `.dylib`), which you could dynamically link into your own project. You could also provide the `tensorflow` repository root as an include path so that you could include the `tensorflow/lite/...` headers.

**Comment by peter197321** [comment]
I need that lib for ARM64 target.

**Comment by yyoon** [comment]
Can you try adding `--config=elinux_aarch64` flag to the build command above?

    bazel build -c opt --config=elinux_aarch64 //tensorflow/lite:tensorflowlite

Tried this on a Linux machine and it seems to work for me.

```sh
$ file bazel-bin/tensorflow/lite/libtensorflowlite.so
bazel-bin/tensorflow/lite/libtensorflowlite.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (GNU/Linux), dynamically linked, BuildID[md5/uuid]=d9af18419c9973a6b552eba0d4f44721, stripped
```

cc/ @terryheo

**Comment by peter197321** [comment]
OK. I'll try it but why `--config=elinux_aarch64`?
I did before `--cpu=arm64`, `--cpu=aarch64` or `--cpu=arm64-v8a` ..

**Comment by peter197321** [comment]
seem unsuccessful

```
/tensorflow$ bazel build -c opt --config=elinux_aarch64 //tensorflow/lite:tensorflowlite
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=192
INFO: Reading rc options for 'build' from /media/nxa18908/work/work/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /media/nxa18908/work/work/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Found applicable config definition build:v2 in file /work/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
ERROR: Config value elinux_aarch64 is not defined in any .rc file
(base) /work/tensorflow$

```

**Comment by yyoon** [comment]
The build config is defined here, and it was added recently.
https://github.com/tensorflow/tensorflow/blob/master/.bazelrc#L76-L79

Which version of tensorflow repository are you using?

**Comment by peter197321** [comment]
I use ver.2.2

**Comment by peter197321** [comment]
I've switched to the latest (master) - now it seems building now - where is toolchain taken from (defined). 
It looks it uses arm-gcc-8.3 and how could I change to the latest GCC 9.3.1?

**Comment by yyoon** [comment]
Please refer to this commit 4961f18733ca3967198393abf419e14476b4a85c to see more details on how the toolchain was configured.

I think you'll need to update the toolchain archive url under `tensorflow/workspace.bzl`.

**Comment by peter197321** [comment]
Thanks a lot for great help!

**Comment by peter197321** [comment]
Since I am not bazel expert :( it seems defined here within `tensorflow/workspace.bzl`

```
    tf_http_archive(
        name = "aarch64_linux_toolchain",
        build_file = clean_dep("//third_party/toolchains/embedded/arm-linux:aarch64-linux-toolchain.BUILD"),
        sha256 = "8ce3e7688a47d8cd2d8e8323f147104ae1c8139520eca50ccf8a7fa933002731",
        strip_prefix = "gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu",
        urls = [
            "https://storage.googleapis.com/mirror.tensorflow.org/developer.arm.com/media/Files/downloads/gnu-a/8.3-2019.03/binrel/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu.tar.xz",
            "https://developer.arm.com/-/media/Files/downloads/gnu-a/8.3-2019.03/binrel/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu.tar.xz",
        ],
    )
```

**Comment by peter197321** [comment]
Can be applied this similarly for label_image example project [label_image](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/label_image)?

**Comment by yyoon** [comment]
1) Do you have a reason to use a specific version of GCC? I'd suggest sticking to the provided GCC version.

2) For fixing the label_image build, you could try editing the `tensorflow/lite/examples/label_image/BUILD` file.

```diff
diff --git a/tensorflow/lite/examples/label_image/BUILD b/tensorflow/lite/examples/label_image/BUILD
index 92bb503e6d..3f4d10cc57 100644
--- a/tensorflow/lite/examples/label_image/BUILD
+++ b/tensorflow/lite/examples/label_image/BUILD
@@ -38,6 +38,8 @@ cc_binary(
         "//tensorflow/lite/profiling:profiler",
         "//tensorflow/lite/tools/evaluation:utils",
         "@com_google_absl//absl/memory",
+        "@com_google_absl//absl/base",
+        "@com_google_absl//absl/strings",
     ] + select({
         "//tensorflow:android": [
             "//tensorflow/lite/delegates/gpu:delegate",
```

**Comment by peter197321** [comment]
1. nope - I'd like to know where to change it :)
2. need to exercise built lib with tflite (static, dynamic)

**Comment by yyoon** [comment]
Sure. Could this issue be considered resolved then? Or are you still blocked on something?
