### ISSUE TITLE
"ImportError: cannot import name tf2" when doing Object Detection Model Training in Google Cloud

### ISSUE THREAD

**Issue by sohartma** [tensorflow/tensorflow#39871]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:-
- TensorFlow installed from (source or binary):pip install
- TensorFlow version (use command below):('v1.15.0-rc3-22-g590d6ee', '1.15.0')
- Python version:2.7.12
- Bazel version (if compiling from source):-
- GCC/Compiler version (if compiling from source):gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
- CUDA/cuDNN version:
- GPU model and memory:

Starting a training job on google cloud for my object detection dataset. Job stops after ~7 minutes giving this error:
`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/.local/lib/python2.7/site-packages/object_detection/model_main.py", line 26, in <module>
    from object_detection import model_lib
  File "/root/.local/lib/python2.7/site-packages/object_detection/model_lib.py", line 28, in <module>
    from object_detection import exporter as exporter_lib
  File "/root/.local/lib/python2.7/site-packages/object_detection/exporter.py", line 23, in <module>
    from object_detection.builders import model_builder
  File "/root/.local/lib/python2.7/site-packages/object_detection/builders/model_builder.py", line 39, in <module>
    from object_detection.utils import tf_version
  File "/root/.local/lib/python2.7/site-packages/object_detection/utils/tf_version.py", line 17, in <module>
    from tensorflow.python import tf2  # pylint: disable=import-outside-toplevel
ImportError: cannot import name tf2`
Local training however works fine, but is really slow and will take at least a week.

As I'm using tensorflow 1.15 this error should'nt occur...?

Install Tensorflow 1.15 with pip, all other libraries for the API, model repository, pycocotools, protobuf 3.11.4 -> testing the API installation works fine.
Create dataset including tfrecord files, training pipeline, googlecloud yaml file, ...
Run google cloud training job with:
# in tensorflow/models/research
    gcloud ai-platform jobs submit training balls200_training_260520a     --runtime-version 1.12     --job-dir=gs://200balls_model/train     --packages dist/object_detection-0.1.tar.gz,slim/dist/slim-0.1.tar.gz,tmp/pycocotools/pycocotools-2.0.tar.gz     --module-name object_detection.model_main     --region us-central1     --config /home/ubuntu/Documents/200balls_modeltraining/cloud.yml     --     --model_dir=gs://200balls_model/train     --pipeline_config_path=gs://200balls_model/pipeline.config

**Comment by ravikyram** [comment]
@sohartma 

This issue is more suitable for TensorFlow Models repo. Please post it on Models repo from [here.](https://github.com/tensorflow/models/issues) Thanks!

**Comment by sohartma** [comment]
@ravikyram thanks!

**Comment by ravikyram** [comment]
@sohartma 

Can we close the issue here and track the issue in Models repo. Thanks!

**Comment by mihaimaruseac** [comment]
Closing in favor of https://github.com/tensorflow/models/issues/8572

**Comment by sohartma** [comment]
@ravikyram sure!
