### ISSUE TITLE
Mixing XLA and non XLA autograph triggers retracing

### ISSUE THREAD

**Issue by AdrienCorenflos** [tensorflow/tensorflow#39872]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): True
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux (Colab, I'm not sure what the os is)
- TensorFlow installed from (source or binary): Colab
- TensorFlow version (use command below): 2.2.0

**Describe the current behavior**
Mixing XLA (experimental_compile) and non XLA functions results in constant retracing

**Describe the expected behavior**
Functions inside an XLA function should inherit the option, XLA functions inside non XLA ones shouldn't retrace.

This is particularly important when relying on third-party libraries making use of the functionality.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1PrKsKSiKyGjjmX8Itub_BKe-SEihuWMM?usp=sharing

**Comment by Saduf2019** [comment]
I ran the gist shared and was able to replicate the issue, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/c5ceac8ed5f3bf255ed941125576e151/untitled204.ipynb)

**Comment by cheshire** [comment]
@allenlavoie Any thoughts?

**Comment by allenlavoie** [comment]
Probably outer retracing triggers inner retracing because of this entry for the cache key: https://github.com/tensorflow/tensorflow/blob/5c7469978913e8e9590c60cd2605923d0f53f0be/tensorflow/python/eager/function.py#L2978-L2982

So whoever added that might be a good person to check with.

**Comment by cheshire** [comment]
@rxsang Do we need to put the XLA context id there? Isn't it sufficient to know whether the outer XLA context exists or not?

**Comment by cheshire** [comment]
@allenlavoie Thanks!
And @AdrienCorenflos thanks a lot for the report.

**Comment by rxsang** [comment]
That's intended for TPU case, as we need to make sure the inner and outer XLA context match. Maybe it could be relaxed for non TPU case.

> @rxsang Do we need to put the XLA context id there? Isn't it sufficient to know whether the outer XLA context exists or not?
