### ISSUE TITLE
About tf.contrib.slim data prepare documentation

### ISSUE THREAD

**Issue by LinJM** [tensorflow/tensorflow#3987]
I have spend much time to understand how to prepare my data to feed into Slim Net. 
But I still can't quiet understand how to prepare my training data.
Is there a more detailed method for processing the training data, like Caffe ImageNet tutorial:http://caffe.berkeleyvision.org/gathered/examples/imagenet.html

**Comment by prb12** [comment]
This is a general question best suited to StackOverflow.   Please can you re-ask your question there.
