### ISSUE TITLE
Incompatible shapes using `sample_weight` in Graph execution

### ISSUE THREAD

**Issue by OverLordGoldDragon** [tensorflow/tensorflow#39888]
Works fine in Eager. Code + error below; pasted outputs are from a Colab instance with `tf.__version__ == 2.3.0-dev20200526`, also reproduced in 2.2.0 and on Windows 10. No error in TF 1.14.0 Graph.

<hr>

**Attempted debug**: Placing below [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/utils/losses_utils.py#L111) (in local install)

```python
print(sample_weight)
try: print("sample_weight =", K.eval(sample_weight))
except: pass
print(loss, '\n')
```

yields:

```python
# EAGER
Tensor("ExpandDims:0", shape=(32, 1), dtype=float32)
Tensor("mean_squared_error/weighted_loss/value:0", shape=(), dtype=float32)

Tensor("ExpandDims:0", shape=(32, 1), dtype=float32)
Tensor("mean_squared_error/weighted_loss/value:0", shape=(), dtype=float32)

# GRAPH
1.0
sample_weight = 1.0
Tensor("loss/conv2d_loss/weighted_loss/Mul:0", shape=(32, 28, 28), dtype=float32)

Tensor("conv2d_sample_weights:0", shape=(None,), dtype=float32)
sample_weight = [1.]
Tensor("loss_1/conv2d_loss/weighted_loss/Mul:0", shape=(32, 28, 28), dtype=float32)
```
Graph handles `sample_weight` tensor differently; also see example at bottom.

<hr>

**Reproducible code + Error**:

```python
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, Conv2D
from tensorflow.keras.models import Model
tf.compat.v1.disable_eager_execution()

batch_shape = (32, 28, 28, 1)

ipt = Input(batch_shape=batch_shape)
out = Conv2D(filters=1, kernel_size=(1, 1))(ipt)
model = Model(ipt, out)
model.compile('adam', 'mse')

x = y = np.random.randn(*batch_shape)
sw = np.ones(len(x))

model.train_on_batch(x, y, sw)
```

```python
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in __call__(self, *args, **kwargs)
   1470         ret = tf_session.TF_SessionRunCallable(self._session._session,
   1471                                                self._handle, args,
-> 1472                                                run_metadata_ptr)
   1473         if run_metadata:
   1474           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)
InvalidArgumentError: Incompatible shapes: [32] vs. [32,28,28]
	 [[{{node training/Adam/gradients/gradients/loss_1/conv2d_loss/weighted_loss/Mul_grad/Mul}}]]
```

<hr>

**No error case**: both Graph and Eager work fine if output shape is instead 2D.

<details>
   <summary><b>Example code</b></summary>

```python
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, Conv2D, Dense, Flatten
from tensorflow.keras.models import Model

tf.compat.v1.disable_eager_execution()

batch_shape = (32, 28, 28, 1)

ipt = Input(batch_shape=batch_shape)
x   = Conv2D(filters=1, kernel_size=(1, 1))(ipt)
x   = Flatten()(x)
out = Dense(10, activation='softmax')(x)
model = Model(ipt, out)
model.compile('adam', 'categorical_crossentropy')

x = np.random.randn(*batch_shape)
n_classes, batch_size = 10, 32
class_labels = np.random.randint(0, n_classes, batch_size)
y = np.eye(n_classes)[class_labels]
sw = np.random.uniform(0, 2, (len(x),))

model.train_on_batch(x, y, sw)
```
```
sample_weight = 1.0
Tensor("loss/dense_loss/weighted_loss/Mul:0", shape=(32,), dtype=float32)
Tensor("dense_sample_weights:0", shape=(None,), dtype=float32)
sample_weight = [1.]
Tensor("loss_1/dense_loss/weighted_loss/Mul:0", shape=(32,), dtype=float32)
```
</details>

_However_, `sample_weight` still prints `[1.]`, even though we passed in `np.random.uniform(0, 2, ...)`.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/f7d49ea4f957b3e5e3688553634d13a2/39888.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/1c69ec8d886adeb6d615ba891b280baa/39888-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue in TF 2.5. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/8ac76ed981d3a494f37540d725da8f9b/untitled80.ipynb). Thanks!

**Comment by chunduriv** [comment]
While trying to reproduce your issue in `tf2.6` and `tf-nightly(2.8.0-dev20211012)` facing different error, please find the gist [here](https://colab.research.google.com/gist/chunduriv/e48f0a092faf4fec3c103c1c8e391fe9/39888.ipynb),Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
