### ISSUE TITLE
Be able to specifiy the row split dtypes in a keras Ragged Input layer 

### ISSUE THREAD

**Issue by tanguycdls** [tensorflow/tensorflow#39884]
**System information**
- TensorFlow version (you are using): Nightlies
- Are you willing to contribute it (Yes/No): depends

**Describe the feature and the current behavior/state.**
Currently to create a ragged input we use:
````
q = tf.keras.layers.Input(ragged=True, dtype=tf.int32, shape=(None,), )
````
we can specify the dtype of the values array but not the one from the row_split array.

**Will this change the current api? How?**
We should be able to provide the dtype we want to use for the row_split array as well:

````
q = tf.keras.layers.Input(ragged=True, dtype=tf.int32, shape=(None,),  row_split_dtype=tf.int32)
````
instead of the default int64.

**Who will benefit with this feature?**
Users with small array with no need for an offset array of 64;

**Any Other info.**

**Comment by karmel** [comment]
Thanks @tanguycdls . At this time, we don't want to add this complicating argument to the main Keras Input API. However, we are working on some refactors that may make this easier in the future. No promises, but we will update this thread if we find that there is a user-friendly way to make the datatype specification possible.

**Comment by tomerk** [comment]
This should now be possible in the nightlies, by specifying a custom type_spec arg for your input layer.

**Comment by tanguycdls** [comment]
Thank you  @tomerk !
I just tried it !
```
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Model
import tensorflow as tf
inp0 = tf.keras.layers.Input(type_spec=tf.RaggedTensorSpec(shape=(None, None), dtype=tf.float32, row_splits_dtype=tf.int32), name='test')
a = Embedding(2, 1)(inp0)
b = tf.reduce_sum(a, axis=0)
m = Model(inp0, b)
m.predict(tf.ragged.constant([[0, 1], [1]], dtype=tf.float32, row_splits_dtype=tf.int32))
m.save('test')
```

I close the issue
