### ISSUE TITLE
Add n-dimensional tensor support for tf.unique and tf.unique_with_counts

### ISSUE THREAD

**Issue by winnietsang** [tensorflow/tensorflow#39882]
Feature request for tf.unique and tf.unique_with_counts:
1. can apply to n-D tensor
2. can select which axis to apply it

**System information**
- TensorFlow version : 2.2.0
- Python version : 3.6.9

**Comment by rmothukuru** [comment]
@winnietsang,
**`Multidimensional Support`** is available in [tf.raw_ops.UniqueV2](https://www.tensorflow.org/api_docs/python/tf/raw_ops/UniqueV2) and [tf.raw_ops.UniqueWithCountsV2](https://www.tensorflow.org/api_docs/python/tf/raw_ops/UniqueWithCountsV2). PTAL. Thanks!
