### ISSUE TITLE
[MLIR] xla hlo -> lhlo conversion issue when operand is a constant tensor

### ISSUE THREAD

**Issue by bondhugula** [tensorflow/tensorflow#39895]
With master branch as of 831a55584749593400807e0baa7478476b5dbc70 (May 26):
The xla hlo to lhlo lowering doesn't convert completely when the operand of an op (in this example below, that of broadcast_in_dim) is a constant tensor. To reproduce, please use:

```
func @main(%arg0: tensor<4x64x128x3xf32>, %arg1: tensor<5x3x3x10xf32>) {
  %cst = constant  dense<0.000000e+00> : tensor<f32>
  %0 = "xla_hlo.broadcast_in_dim"(%cst) {broadcast_dimensions = dense<[]> : tensor<0xi64>, name = "broadcast.6"} : (tensor<f32>) -> tensor<4x30x42x10xf32>
  return
}
```

and

```
$ tf-opt -hlo-legalize-to-lhlo constant-tensor-lowering.mlir 
constant-tensor-lowering.mlir:3:8: error: 'xla_lhlo.broadcast_in_dim' op operand #0 must be memref of floating-point or signless integer or complex-type values, but got 'tensor<f32>'
  %0 = "xla_hlo.broadcast_in_dim"(%cst) {broadcast_dimensions = dense<[]> : tensor<0xi64>, name = "broadcast.6"} : (tensor<f32>) -> tensor<4x30x42x10xf32>
       ^
constant-tensor-lowering.mlir:3:8: note: see current operation: "xla_lhlo.broadcast_in_dim"(%cst, %0) {broadcast_dimensions = dense<[]> : tensor<0xi64>, name = "broadcast.6"} : (tensor<f32>, memref<4x30x42x10xf32>) -> ()
```
Using `-print-ir-after-all` reveals the operand for the lhlo broadcast_in_dim op wasn't converted to a memref:

```
tuple.mlir:4:10: error: 'xla_lhlo.broadcast_in_dim' op operand #0 must be memref of floating-point or signless integer or complex-type values, but got 'tensor<f32>'
    %0 = "xla_hlo.broadcast_in_dim"(%cst) {broadcast_dimensions = dense<[]> : tensor<0xi64>, name = "broadcast.6"} : (tensor<f32>) -> tensor<4x30x42x10xf32>
         ^
tuple.mlir:4:10: note: see current operation: "xla_lhlo.broadcast_in_dim"(%cst, %0) {broadcast_dimensions = dense<[]> : tensor<0xi64>, name = "broadcast.6"} : (tensor<f32>, memref<4x30x42x10xf32>) -> ()
// *** IR Dump After mlir::detail::VerifierPass Failed ***


"module"() ( {
  "func"() ( {
  ^bb0(%arg0: memref<4x64x128x3xf32>, %arg1: memref<5x3x3x10xf32>):  // no predecessors
    %cst = "std.constant"() {name = "constant.5", value = dense<0.000000e+00> : tensor<f32>} : () -> tensor<f32>
    %0 = "std.alloc"() : () -> memref<4x30x42x10xf32>
    "xla_lhlo.broadcast_in_dim"(%cst, %0) {broadcast_dimensions = dense<[]> : tensor<0xi64>, name = "broadcast.6"} : (tensor<f32>, memref<4x30x42x10xf32>) -> ()
    %1 = "std.alloc"() : () -> memref<4x30x42x10xf32>
    "xla_lhlo.convolution"(%arg0, %arg1, %1) {batch_group_count = 1 : i64, dimension_numbers = {input_batch_dimension = 0 : i64, input_feature_dimension = 3 : i64, input_spatial_dimensions = dense<[1, 2]> : tensor<2xi64>, kernel_input_feature_dimension = 2 : i64, kernel_output_feature_dimension = 3 : i64, kernel_spatial_dimensions = dense<[0, 1]> : tensor<2xi64>, output_batch_dimension = 0 : i64, output_feature_dimension = 3 : i64, output_spatial_dimensions = dense<[1, 2]> : tensor<2xi64>}, feature_group_count = 1 : i64, lhs_dilations = dense<1> : tensor<2xi64>, name = "convolution.4", padding = dense<0> : tensor<2x2xi64>, precision_config = ["DEFAULT", "DEFAULT"], rhs_dilations = dense<1> : tensor<2xi64>, window_strides = dense<[2, 3]> : tensor<2xi64>} : (memref<4x64x128x3xf32>, memref<5x3x3x10xf32>, memref<4x30x42x10xf32>) -> ()
    %2 = "std.alloc"() : () -> memref<4x30x42x10xf32>
    "xla_lhlo.maximum"(%0, %1, %2) {name = "maximum.7"} : (memref<4x30x42x10xf32>, memref<4x30x42x10xf32>, memref<4x30x42x10xf32>) -> ()
    "xla_lhlo.terminator"() : () -> ()
  }) {sym_name = "main", type = (memref<4x64x128x3xf32>, memref<5x3x3x10xf32>) -> ()} : () -> ()
  "module_terminator"() : () -> ()
}) : () -> ()
```
This is nothing specific to broadcast_in_dim (happens with say xla_hlo.add as well). This is likely a missing conversion for std.constant that needs to be completed?

**Comment by Saduf2019** [comment]
@bondhugula 
Please share simple stand alone code for us to replicate the issue faced.

**Comment by bondhugula** [comment]
> @bondhugula
> Please share simple stand alone code for us to replicate the issue faced.

But that's exactly what I provided above. Did you expect something else?

**Comment by bondhugula** [comment]
@r4nt Please assign this issue to me - I'll add the missing rewrites needed to get this working. @MaheshRavishankar @joker-eph for visibility and their information.

**Comment by MaheshRavishankar** [comment]
THanks Uday! But is the expectation to have xla_hlo.const and I think there is a conversion from xla_hlo.const to xla_lhlo.const. Then the conversion to memref does work. I am not sure there is an expectation to mix dialects as in your example. But I dont see any reason not to have such a pattern, but maybe you could reuse some of the conversion from hlo -> lhlo for std -> lhlo conversion.

**Comment by bondhugula** [comment]
> THanks Uday! But is the expectation to have xla_hlo.const and I think there is a conversion from xla_hlo.const to xla_lhlo.const. Then the conversion to memref does work. I am not sure there is an expectation to mix dialects as in your example. But I dont see any reason not to have such a pattern, but maybe you could reuse some of the conversion from hlo -> lhlo for std -> lhlo conversion.

Dumping an XLA protobuf and using tf-mlir-translate -hlo-to-mlir-hlo actually yields such an input (std.constant instead of an xla_hlo.const). xla_hlo.const -> xla_lhlo.const would work, but the -hlo-legalize-to-lhlo pass could potentially be presented with such an input in other ways, and so making -hlo-to-mlir-hlo generate hlo.const isn't a real solution. The std.constant in these cases is isomorphic to xla_hlo.const (generates the same result type), and so as you point out, we could reuse the conversion pattern hlo -> lhlo. Since this is really "a terminal conversion" (tensor operands of some ops get their values from std.constants) and that we can't generate constant memrefs from std.constant, I guess it's fine to have this conversion pattern live in hlo_legalize_to_lhlo.

**Comment by pifon2a** [comment]
@bondhugula What "other ways" did you mean in `potentially be presented with such an input in other ways, and so making -hlo-to-mlir-hlo generate hlo.const isn't a real solution. `

**Comment by bondhugula** [comment]
> @bondhugula What "other ways" did you mean in `potentially be presented with such an input in other ways, and so making -hlo-to-mlir-hlo generate hlo.const isn't a real solution. `?

An IR generator can choose to generate std.constant or you can end up with such an input through a composition of other transformations/rewrites - there isn't really a reason to not handle std.constant in conjunction given that they are isomorphic for this part with hlo.constant. For consistency and completeness, I think we definitely should.

**Comment by pifon2a** [comment]
I agree about mixing, I don't understand the comment about `IR generator`. Aren't we in control of what an IR generator can "choose" to generate? Why can't it generate xla_hlo.constant? Then we can lower it to xla_lhlo.constant? Going std.constant -> xla_lhlo.const -> std.constant + std.store is a bit weird.

**Comment by bondhugula** [comment]
> I agree about mixing, I don't understand the comment about `IR generator`. Aren't we in control of 

What I meant was that you can't really control what input the pass will receive. The IR is valid and the mix makes sense and supporting such a mix is pretty important.

> what an IR generator can "choose" to generate? Why can't it generate xla_hlo.constant? Then we 

The tf-mlir-translate -hlo-to-mlir-hlo isn't the only thing creating input for this conversion pass. You can't choose where you can get input from! :-)

>  Going std.constant -> xla_lhlo.const -> std.constant + std.store is a bit weird.

If std.constant can be presented as input to this pass, you have no choice but to deal with it here. It's converting std.constant to hlo.const in this pass is what would be weird! :-)

**Comment by pifon2a** [comment]
If std.constant (and other ops) are presented in a mix with HLO, we can add this pattern separately after calling `populateHLOToLHLOConversionPattern`. I don't think this pattern belongs to HLO->LHLO patterns. @joker-eph are there some recommendations on what patterns should be a part of Dialect 1 -> Dialect 2 conversion and what patterns have to be appended separately?

**Comment by pifon2a** [comment]
@bondhugula strictly speaking this pattern is STD-> LHLO. It might be better to have it in std_legalize_to_lhlo.cc or maybe in the same file with a custom pass implementation where it is actually used. 
Making `tf-mlir-translate -hlo-to-mlir-hlo` pipeline generate xla_hlo.constants would also make more sense, I think.

**Comment by bondhugula** [comment]
> Making `tf-mlir-translate -hlo-to-mlir-hlo` pipeline generate xla_hlo.constants would also make more sense, I think.

This should be done anyway I think, but I don't see this versus the other part of the argument. It's not a question of choosing between the two: you need both independently. As I said, there is really no reason to not separately have std.constant -to lhlo -- the former is tensor value semantics (no way to create constant memory via std.constant), and the latter provides memory semantics. std.constant may not be a HLO op but it does provides values at the leaves to xla_hlo ops. So, std.constant -> lhlo.const is indeed a lowering that is complementary to have within hlo to lhlo. hlo already depends on std - so there is no additional dependence as well FWIW.

**Comment by bondhugula** [comment]
@joker-eph @MaheshRavishankar Need your input here - please see comment history above as well as the PR. https://github.com/tensorflow/tensorflow/pull/40120 Thanks!

**Comment by MaheshRavishankar** [comment]
I dont really work on the HLO -> LHLO conversion parts, but I agree with what @bondhugula  is saying here. Unless you can gaurantee that the input is going to always have `xla_hlo.const` instead of `std.constant` you need a way to convert `std.constant` to `xla_lhlo.const` (similar to how `xla_hlo.const` is converted to `xla_lhlo.const`). I think @pifon2a  is not opposed to adding such a pattern. The question might be just about file organization. I have no comments on that either :) 

Just to provide context in IREE. I eventually want to use the HLOToStd conversion pass (I dont know off the top of my head where it lives), so that we dont duplicate such patterns and bias towards using Standard Dialect -> ... conversions. This obviously not what you would want for TF. Maybe you can do the reverse. Add a Standard to HLO conversion so that you dont replicate code (this is a one line using DRR). Really dont see either approaches being better than the other.

**Comment by bondhugula** [comment]
> Standard Dialect -> ... conversions. This obviously not what you would want for TF. Maybe you can do the reverse. Add a Standard to HLO conversion so that you dont replicate code (this is a one line using DRR). Really dont see either approaches being better than the other.

std.const -> hlo.const would be weird since you are going from a higher-level domain-specific dialect to a base one with both having tensor value semantics. :) OTOH, since lhlo has memory/buffer semantics, std.const -> lhlo.const is seen as a lowering (values to memory) that can live in hlo->lhlo. That's the reason I didn't do a std.const -> hlo.const - I don't think we have any conversion in such a direction.

**Comment by sherhut** [comment]
I think the underlying problem here is that std does not have the concept of constants on memrefs. That is an omission as every user of std will run into this when lowering tensors to memrefs. Transforming std.const to lhlo.const is just hiding this omission by escaping to LHLO.

I would also argue that the TF legalization should produce an HLO constant so that its output is closed in HLO. This should also help with the export to proto (or does that have a rule for std.const to hlo.const?).

Lastly, if you insist to have this pattern, it should at least live in a different file. Putting it into hlo to lhlo would hide the fact that the pattern transforms part of std and maybe not all users want that lowering to happen.

**Comment by bondhugula** [comment]
> I think the underlying problem here is that std does not have the concept of constants on memrefs. That is an omission as every user of std will run into this when lowering tensors to memrefs. Transforming std.const to lhlo.const is just hiding this omission by escaping to LHLO.

As you know, memrefs aren't necessarily contiguous and can have arbitrary affine layouts, striding, padding, and so an op that stores a constant to a memref just cannot live in the std dialect! If it did, its valid lowering for codegen would have to again pass through loops, which are themselves not in the std dialect. So, I don't see the argument that the underlying problem is that of a memref constant store/assignment/filling in the std dialect. Given the nuances with memrefs, such a constant filling op cannot live in std, but only live in a dialect meant for dense tensors/tcp/linalg/lhlo etc. OTOH, tensors are value types and one can argue for having constant ops defining them in std. Transforming std.const to lhlo.const isn't thus a substitute for something missing: if const tensor -> memref is where you are going, you either need lhlo or linalg, and I see this conversion as belong to hlo to lhlo lowering.
 
> I would also argue that the TF legalization should produce an HLO constant so that its output is closed in HLO. This should also help with the export to proto (or does that have a rule for std.const 

I'm not sure what's to argue for here. TF legalization should produce HLO constant and that should be anyway independently done. That's an independent issue to be fixed separately. As I mentioned, I don't think we should choose to not deal with std.constant when it's presented to this pass.

> 
> Lastly, if you insist to have this pattern, it should at least live in a different file. Putting it into hlo to lhlo would hide the fact that the pattern transforms part of std and maybe not all users want that lowering to happen.

I don't see the reasoning here. There is an independent discussion that's going in the thread below on why forcing 0-d memrefs to model the "functional" regions of lhlo ops (like reduce/reduce_window, select_and_scatter, etc.) isn't the right design choice, and it's certainly going in the direction of actually using std dialect ops inside those regions since you'd just want to express those computations on elemental types and not force 0-d memrefs.
https://groups.google.com/a/tensorflow.org/d/msg/mlir/Ip55os0xgfU/56WXd3ZxAwAJ

So std dialect ops are going to be in the legal target set for these conversions - hlo to lhlo, and already lhlo to linalg. This whole idea of not letting std dialect ops mix with lhlo would only hurt transformations and conversions out of the dialect. You'll be forced to spill to memory when you don't need to and use fake 0-d memrefs for scalars unnecessarily.

**Comment by sherhut** [comment]
> > I think the underlying problem here is that std does not have the concept of constants on memrefs. That is an omission as every user of std will run into this when lowering tensors to memrefs. Transforming std.const to lhlo.const is just hiding this omission by escaping to LHLO.
> 
> As you know, memrefs aren't necessarily contiguous and can have arbitrary affine layouts, striding, padding, and so an op that stores a constant to a memref just cannot live in the std dialect! If it did, its valid lowering for codegen would have to again pass through loops, which are themselves not in the std dialect. 

Having a `std.const` on memrefs in the standard dialect would not imply any specific lowering. You could even have a version that allocates the buffer if you wanted. In either case, the lowering of such a memref constant is independent of the semantics. You could decide to implement `std.const` by lowering via linalg or going to `hlo.cost`. 

> > Lastly, if you insist to have this pattern, it should at least live in a different file. Putting it into hlo to lhlo would hide the fact that the pattern transforms part of std and maybe not all users want that lowering to happen.
> 
> I don't see the reasoning here. There is an independent discussion that's going on in the thread below on why forcing 0-d memrefs to model the "functional" regions of lhlo ops (like reduce/reduce_window, select_and_scatter, etc.) isn't the right design choice, and it's certainly going in the direction of actually using std dialect ops inside those regions since you'd just want to express those computations on elemental types and not force 0-d memrefs.

I would also disagree with that choice (using standard ops). Lets have that discussion there though.

> So std dialect ops are going to be in the legal target set for these conversions - hlo to lhlo, and already lhlo to linalg. This whole idea of not letting std dialect ops mix with lhlo would only hurt transformations and conversions out of the dialect. You'll be forced to spill to memory when you don't need to and use fake 0-d memrefs for scalars unnecessarily.

We have to separate two concerns here. During lowering, we gradually introduce std/linalg/whatever operations into the HLO/LHLO mix. That is different from the original form that we generate though. Coming from TensorFlow, I would expect we legalize to HLO (without standard in the mix), including the nested regions of reductions. One reason for this is the easier transition back to legacy systems.

Also, I am fine with adding this pattern from `std.const` to `hlo.const` but it should not be part of the HLO to LHLO set of patterns because that is not what it does.

**Comment by joker-eph** [comment]
> Also, I am fine with adding this pattern from std.const to hlo.const 

This makes sense to me as well: seems like a good application of transitive lowering here, isn't it?

**Comment by bondhugula** [comment]
> > Also, I am fine with adding this pattern from std.const to hlo.const
> 
> This makes sense to me as well: seems like a good application of transitive lowering here, isn't it?

But where would you have this pattern live? I'm completely fine with this as long as this pattern can run as part of -hlo-legalize-to-lhlo. If not, it's weirder to have to run a separate pass do std to hlo, and I don't see how this solves the original issue. I would then prefer having std.const to lhlo.const in the hlo to lhlo conversion which was the original proposal.

**Comment by joker-eph** [comment]
>  If not, it's weirder to have to run a separate pass do std to hlo, and I don't see how this solves the original issue

Why doesn't it solve the original issue? If you're pipeline is always including -std-to-hlo before -hlo-to-lhlo shouldn't this just work then?

**Comment by bondhugula** [comment]
> > If not, it's weirder to have to run a separate pass do std to hlo, and I don't see how this solves the original issue
> 
> Why doesn't it solve the original issue? If you're pipeline is always including -std-to-hlo before -hlo-to-lhlo shouldn't this just work then?

The original issue was of making the -hlo to lhlo pass deal with this input. 

> 
> Note that in practice in a real pipeline, one would include all the patterns to legalize to HLO, include the STD->HLO, and legalize there as a single pass before running the LHLO buffer alloc.

A new pass std to hlo just for this?! What other conversions do you foresee that to have? The conversion looks backwards intuitively.

**Comment by joker-eph** [comment]
> The original issue was of making the -hlo to lhlo pass deal with this input.

Such passes are mostly testing passes, they can't support the world. This is the case with most passes that are loading A->B conversion pattern right now. If you want A+C->B you need another pass loading the right set of patterns. I don't think there is anything specific to this pass right now.

> The conversion looks backwards intuitively.

Why? A lot of `std` dialect op can be seen as the same level of abstraction as HLO, using the existing XLA compiler to target TPU from a tensor-level computation involving `std` ops could be useful to someone for example.
Conversion don't need to be one-way: for example we have a conversion from TF->HLO and from HLO->TF.

**Comment by bondhugula** [comment]
> > The original issue was of making the -hlo to lhlo pass deal with this input.
> 
> Such passes are mostly testing passes, they can't support the world. This is the case with most passes that are loading A->B conversion pattern right now. If you want A+C->B you need another pass loading the right set of patterns. I don't think there is anything specific to this pass right now.
> 
> > The conversion looks backwards intuitively.
> 
> Why? A lot of `std` dialect op can be seen as the same level of abstraction as HLO, using the existing XLA compiler to target TPU from a tensor-level computation involving `std` ops could be useful to someone for example.
> Conversion don't need to be one-way: for example we have a conversion from TF->HLO and from HLO->TF.

TF -> HLO and HLO -> TF is a difference scenario - I assume you have many conversions there. Creating one full pass and file for a std.const to hlo.const sounds needless, and more importantly,  getting back to the main question: what's the issue with having std.const to hlo.const in hlo to lhlo? It's just an intermediate step and would anyway converge at lhlo.const. Why shouldn't one have such trivial intermediate patterns for canonicalization or to facilitate / trigger other conversions towards your legal target?

**Comment by bondhugula** [comment]
Bringing this back up: where should the conversion for std.const to hlo.const live? If we do this as a conversion pattern in HLO to LHLO, wouldn't it fail? (since the xla_hlo op generated out of the pattern would have been marked as illegal for the conversion target, making the dialect conversion reset state). Could one add an op rewrite pattern as part of a dialect conversion? I completely forget whether it would make sense (in spite of having reviewed a recent revision updating the documentation of pattern rewriting and dialect conversion).

**Comment by bhack** [comment]
What is the status of this?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
