### ISSUE TITLE
pip install Eigen:AVX512 build

### ISSUE THREAD

**Issue by cheers00** [tensorflow/tensorflow#39890]
Is it possible to pip install TF-Eigen-build with AVX512 support?

I would like to install TF2 on my server and it seems like packages `tensorflow `and `tensorflow`-cpu are not built with AVX512 enabled because I get the following warning.

`Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA`

ref: [stakoverflow
](https://stackoverflow.com/questions/62015863/how-to-install-tensorflow-2-x-with-eigen-avx512-support)

**Comment by mihaimaruseac** [comment]
You will have to build from source or look for a package provided by community.

**Comment by cheers00** [comment]
okay. Can you please confirm the following build options?

`bazel build --config=opt --copt=-mavx512f --copt=-mfma //tensorflow/tools/pip_package:build_pip_package`

**Comment by ravikyram** [comment]
@cheers00 

Request you to fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Thanks!

**Comment by mihaimaruseac** [comment]
All the `--copt` options are the options you would pass to the compiler if not using Bazel. Cannot known if those are exactly the options you need.

**Comment by cheers00** [comment]
Closing this. I ended up building tensorflow from source. That seems like the only option.

**Comment by surak** [comment]
@cheers00 how did you pass options to eigen?

**Comment by cheers00** [comment]
@surak I built it using the following command. hope it helps.

```
bazel build --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 -c opt --copt=-mavx 
--copt=-mavx2 --copt=-mfma --copt=-mavx512f --copt=-mavx512pf 
--copt=-mavx512cd --copt=-mavx512er 
//tensorflow/tools/pip_package:build_pip_package
```
