### ISSUE TITLE
Error Building Docker Image

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#3989]
Using `Dockerfile.devel-gpu` branched from 459c2fed498530b794c4871892fd68d1e6834ac6.

```
Configuration finished
INFO: Reading 'startup' options from /root/.bazelrc: --batch
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/tensorflow/third_party/gpus/cuda_configure.bzl", line 406
		_create_cuda_repository(repository_ctx)
	File "/tensorflow/third_party/gpus/cuda_configure.bzl", line 340, in _create_cuda_repository
		_find_cudnn_lib_path(repository_ctx, cudnn_install_base..., ...)
	File "/tensorflow/third_party/gpus/cuda_configure.bzl", line 249, in _find_cudnn_lib_path
		fail("Cannot find %s or %s under %s" ...))
Cannot find lib64/libcudnn.so.5 or libcudnn.so.5 under /usr/local/cuda.
____Elapsed time: 1.274s
The command '/bin/sh -c ./configure &&     bazel build --local_resources 3072,3.0,1.0 -c opt --config=cuda tensorflow/tools/pip_package:build_pip_package &&     bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/pip &&     pip install --upgrade /tmp/pip/tensorflow-*.whl' returned a non-zero code: 1

./build-all.sh returned exit code 1
```

**Comment by gunan** [comment]
Please feel free to reach out to me if you need any help with this.

**Comment by cancan101** [comment]
@gunan Inside nvidia/cuda:7.5-cudnn5-devel, it looks like the `so` moved:
```
# ls -l /usr/lib/x86_64-linux-gnu | grep dnn
lrwxrwxrwx 1 root root       29 Aug 12 05:11 libcudnn.so -> /etc/alternatives/libcudnn_so
lrwxrwxrwx 1 root root       17 Jun 10 13:07 libcudnn.so.5 -> libcudnn.so.5.1.3
-rw-r--r-- 1 root root 60696704 Jun 10 13:07 libcudnn.so.5.1.3
lrwxrwxrwx 1 root root       32 Aug 12 05:11 libcudnn_static.a -> /etc/alternatives/libcudnn_stlib
-rw-r--r-- 1 root root 59715990 Jun 10 13:07 libcudnn_static_v5.a
```

**Comment by gunan** [comment]
looking at our nightly build failures, this looks different.
I will try to look into both today.

**Comment by flx42** [comment]
@davidzchen asked us this question: https://github.com/NVIDIA/nvidia-docker/issues/172
I think it's solved now? https://github.com/tensorflow/tensorflow/pull/3269

**Comment by cancan101** [comment]
I am seeing this issue on https://github.com/tensorflow/tensorflow/commit/459c2fed498530b794c4871892fd68d1e6834ac6 which I think includes the linked PR.

**Comment by flx42** [comment]
Just modify this line:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.devel-gpu#L90

It was properly changed in the CI Dockerfile:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/Dockerfile.gpu#L25

**Comment by gunan** [comment]
@davidzchen to also get his input.

**Comment by davidzchen** [comment]
Yes, from the discussion in NVIDIA/nvidia-docker#172 and #3269, the line:

```dockerfile
ENV CUDNN_INSTALL_PATH /usr/local/cuda
```

seems to be incorrect since in the Docker image, `libcudnn.so` is installed under `/usr/lib/x86_64-linux-gnu` and not `/usr/local/cuda/lib64`. The line should be changed to:

```dockerfile
ENV CUDNN_INSTALL_PATH /usr/lib/x86_64-linux-gnu
```

as we have done so in `tensorflow/tools/ci_build/Dockerfile.gpu`.

**Comment by flx42** [comment]
I expect that users might have cuDNN at any of those two locations since we offer deb and tarball downloads. Ideally those two locations should be checked automatically and `CUDNN_INSTALL_PATH` could be reserved for unusual cuDNN install paths.

**Comment by cancan101** [comment]
>I expect that users might have cuDNN at any of those two locations since we offer deb and tarball downloads. 
Should not be relevant for the Docker image where the install location is controlled.

**Comment by flx42** [comment]
True, but it's a maintenance burden, if you want to experiment with the image you have to remember to modify this value.
For instance, if you switch to `nvidia/cuda:8.0-cudnn5-devel`, cuDNN is in `/usr/local/cuda` again since we don't have public deb packages for cuDNN 5 on CUDA 8.0 yet.

**Comment by gunan** [comment]
for cuda7.5 images, I have corrected all the paths as suggested by @flx42 
Closing the issue now.

**Comment by pwaller** [comment]
I just hit this trying to build with cuda:8.0-cudnn5-devel, sounds more or less like the same issue?

```
No Google Cloud Platform support will be enabled for TensorFlow
INFO: Reading 'startup' options from /root/.bazelrc: --batch
Extracting Bazel installation...
____Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
INFO: Reading 'startup' options from /root/.bazelrc: --batch
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/tensorflow/third_party/gpus/cuda_configure.bzl", line 412
		_create_cuda_repository(repository_ctx)
	File "/tensorflow/third_party/gpus/cuda_configure.bzl", line 344, in _create_cuda_repository
		_find_cudnn_header_dir(repository_ctx, cudnn_install_base...)
	File "/tensorflow/third_party/gpus/cuda_configure.bzl", line 233, in _find_cudnn_header_dir
		fail("Cannot find cudnn.h under %s" %...)
Cannot find cudnn.h under /usr/local/cuda-8.0/targets/x86_64-linux/lib.
Configuration finished
INFO: Reading 'startup' options from /root/.bazelrc: --batch
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/tensorflow/third_party/gpus/cuda_configure.bzl", line 412
		_create_cuda_repository(repository_ctx)
	File "/tensorflow/third_party/gpus/cuda_configure.bzl", line 344, in _create_cuda_repository
		_find_cudnn_header_dir(repository_ctx, cudnn_install_base...)
	File "/tensorflow/third_party/gpus/cuda_configure.bzl", line 233, in _find_cudnn_header_dir
		fail("Cannot find cudnn.h under %s" %...)
Cannot find cudnn.h under /usr/lib/x86_64-linux-gnu.
____Elapsed time: 0.391s
The command '/bin/sh -c ./configure &&     bazel bu
```

**Comment by pwaller** [comment]
Submitted #4397.

**Comment by wrs777** [comment]
@flx42 I encountered with the same question like this.
ERROR: error loading package 'tensorflow/examples/android': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': error loading package 'external': The repository named 'local_config_cuda' could not be resolved.

but I don't get how to modify Dockerfile.devel-gpu,here is mine
ENV CI_BUILD_PYTHON python
ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH
ENV TF_NEED_CUDA 1
ENV TF_CUDA_COMPUTE_CAPABILITIES=3.0,3.5,5.2,6.0,6.1

anything is wrong?

**Comment by flx42** [comment]
@wrs777 looks like a different issue. The original issue here should have been fixed.
