### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by pari125** [tensorflow/tensorflow#399]
Hello all,
I have a problem when running: python tensorflow/models/image/mnist/convolutional.py
An error evoked :  IOError: [Errno socket error] [Errno 111] Connection refused

Can it be related to proxy settings problem?

**Comment by vrv** [comment]
Probably a dup of https://github.com/tensorflow/tensorflow/issues/209 -- Yann's website is probably getting taken down by all of these downloads occasionally.  We haven't put up a mirror since I don't think we (yet) have the rights to - de-duping with 209 for now.

**Comment by pari125** [comment]
Thnx for the comment..But can it be related to some socket configuration also? since i tired to make connection through socket to other websites and it returned my the same error

**Comment by vrv** [comment]
It's possible - it's probably worth you instrumenting https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/image/mnist/convolutional.py#L59 to figure out what you need to get access.

**Comment by pari125** [comment]
I had the problem of setting the proxy of the netowrk..Thnx!
