### ISSUE TITLE
TFlite with hexagon delegate returns wrong result. 

### ISSUE THREAD

**Issue by yakovdan** [tensorflow/tensorflow#39907]
**System information**
- I have written custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Snapdragon 855 running Android 9
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.2.0
- Python version: python 3.8
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

I'm using TFlite on a mobile device to execute a quantized NN network. Without use of delegates, 
I get the expected output image. When using the hexagon delegate, I get a white square image instead of the expected output. The dimensions and types remain the same. 

**Describe the expected behavior**

I expect to have the same output image compared to running TFlite on the same device without delegates. 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

    {
       
        std::unique_ptr<tflite::FlatBufferModel> model =
                 tflite::FlatBufferModel::BuildFromFile(filename);
        TFLITE_MINIMAL_CHECK(model != nullptr);

    // Build the interpreter
    tflite::ops::builtin::BuiltinOpResolver resolver;
    InterpreterBuilder builder(*model, resolver);
    std::unique_ptr<Interpreter> interpreter;
    builder(&interpreter);
    TFLITE_MINIMAL_CHECK(interpreter != nullptr);

    // Allocate tensor buffers.
    TFLITE_MINIMAL_CHECK(interpreter->AllocateTensors() == kTfLiteOk);
    printf("=== Pre-invoke Interpreter State ===\n");
    tflite::PrintInterpreterState(interpreter.get());

    // input tensor type is float32
    int input = interpreter->inputs()[0];
    TfLiteIntArray* tensor_dims = interpreter->tensor(input)->dims;
    int wanted_height = tensor_dims->data[1];
    int wanted_width = tensor_dims->data[2];
    int wanted_channels = tensor_dims->data[3];

    int numberOfPixels = wanted_width*wanted_height*wanted_channels;
    if (numberOfPixels != 224*224*3) // expected input size
    {
        std::cout << "input tensor is of wrong size";
        exit(-1);
    }
    float * img_ptr = (float *)processedInput->getHostPtr();
    for (int k = 0; k < numberOfPixels; ++k)
    {
        interpreter->typed_tensor<float>(input)[k] = img_ptr[k];
    }

    /// setup hexagon delegate now
    const char * library_directory_path = "/data/local/";
    TfLiteHexagonInitWithPath(library_directory_path);  // Needed once at startup.
    TfLiteHexagonDelegateOptions params = {0};

    auto* delegate_ptr = TfLiteHexagonDelegateCreate(&params);
    Interpreter::TfLiteDelegatePtr delegate(delegate_ptr,
                                            [](TfLiteDelegate* delegate) {
                                                TfLiteHexagonDelegateDelete(delegate);
                                            });
    interpreter->ModifyGraphWithDelegate(delegate.get());

    // Run inference
    TFLITE_MINIMAL_CHECK(interpreter->Invoke() == kTfLiteOk);
    printf("\n\n=== Post-invoke Interpreter State ===\n");
    tflite::PrintInterpreterState(interpreter.get());

    int output = interpreter->outputs()[0];
    TfLiteIntArray* output_dims = interpreter->tensor(output)->dims;

    int output_w = output_dims->data[1]; // as expected, this 224 by 224 pixels
    int output_h = output_dims->data[2];
    numberOfPixels = output_h * output_w;

    // output tensor type is float32

    float * output_buffer = new float[numberOfPixels];
    for (int k=0; k < numberOfPixels;++k)
        output_buffer[k] = interpreter->typed_tensor<float>(output)[k];

    std::ofstream file;
    file.open("/data/local/rgbImage_out.bin", std::ios::binary|std::ofstream::out);
    if (file.is_open())
    {
        file.write((char *)output_buffer, 224*224*sizeof(float)); // assumed the out buffer is a vector
        file.close();

    }else{
        std::cout << "couldn't open file" << std::endl;
    }

    delete []  output_buffer;

    // After usage of delegate.
    TfLiteHexagonTearDown();  // Needed once at end of app/DSP usage.

     }

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

See attached two log files which contain interpreter state prints before and after calling invoke()
for both cases - with and without a hexagon delegate
[no_delegate_log.txt](https://github.com/tensorflow/tensorflow/files/4689474/no_delegate_log.txt)
[delegate_log.txt](https://github.com/tensorflow/tensorflow/files/4689475/delegate_log.txt)

**Comment by karimnosseir** [comment]
Hi,

It will be hard to check what is wrong without a model. 
Can you share the model ? (you can share it privately, no need to attach it here).

Thanks

**Comment by karimnosseir** [comment]
@yakovdan either email me directly (email same as username here) or send the question on tflite@tensorflow.org and i will reply and we can follow privately.

Thanks
