### ISSUE TITLE
Max and min for dynamic tensors should be recorded during calibration: Failed for tensor Shape

### ISSUE THREAD

**Issue by vladdders** [tensorflow/tensorflow#39909]
**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed using pip, it's actually tf-nightly-gpu
- TensorFlow version: tf-nightly-gpu==2.3.0.dev20200527

**Command used to run the converter or code if you’re using the Python API**

```
import numpy
import tensorflow as tf


def data_reader(size=900):
    return numpy.ones((size, 32, 86, 1), numpy.uint8) * 255


data = data_reader()
data = tf.cast(data, tf.float32)
repr_ds = tf.data.Dataset.from_tensor_slices((data)).batch(1)


def representative_data_gen():
    for input_value in repr_ds.take(100):
        yield [input_value]


converter = tf.lite.TFLiteConverter.from_saved_model("./exported")
converter.experimental_new_converter = True

converter.optimizations = [tf.lite.Optimize.DEFAULT]

converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

tflite_model = converter.convert()

open("exported.tflite", "wb").write(tflite_model)
```

```
**The output from the converter invocation**
```
Traceback (most recent call last):
  File "...", line 29, in <module>
    tflite_model = converter.convert()
  File "venv/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 920, in convert
    return super(TFLiteConverterV2, self).convert()
  File "venv/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 752, in convert
    self).convert(graph_def, input_tensors, output_tensors)
  File "venv/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 502, in convert
    constants.FLOAT, False)
  File venv/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 349, in _calibrate_quantize_model
    inference_output_type, allow_float)
  File "venv/lib/python3.6/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 93, in calibrate_and_quantize
    np.dtype(output_type.as_numpy_dtype()).num, allow_float)
RuntimeError: Max and min for dynamic tensors should be recorded during calibration: Failed for tensor Shape
Empty min/max for tensor Shape
```

**Also, please include a link to the saved model or GraphDef**

```
https://drive.google.com/file/d/1dSDVWjM2fJbT71r-EiUqkwygtYr0a5aE/view?usp=sharing
```

**Failure details**
I am trying to convert this model by performing full integer quantization described [here](https://www.tensorflow.org/lite/performance/post_training_quantization#full_integer_quantization_of_weights_and_activations), but it fails as described above. If I attempt to convert it without a representative dataset it works ok, but the input/output tensors remain float32 and I need int8. Maybe I am missing something, but I'd like to know if this is solvable. Thanks in advance.

**Comment by Saduf2019** [comment]
@vladdders 
Please refer to this issue with similar error#39718 and let us know if it helps.

**Comment by vladdders** [comment]
@Saduf2019 
I have tried with tensorflow 2.2.0, but unfortunately I get the same error :/

**Comment by xchani** [comment]
I think it's due to some latest commit. Since I also encounter this error with the nightly version, but the same code works with stable version.

**Comment by vladdders** [comment]
It doesn't work for me. Did you try my code by any chance and got it to work?

**Comment by Saduf2019** [comment]
@vladdders
Can you please try it on version as suggested by xchani and share a colab gist in case you face any issues.

**Comment by vladdders** [comment]
@Saduf2019 I have tried what @xchani suggested and sadly the same issue occurs. I have installed the stable version `2.2.0` as mentioned previously. Please find the gist [here](https://colab.research.google.com/drive/1yIx_J3NfIlDpaJw9XMgXpIT4XY69Y6nJ?usp=sharing).

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find [gist here](https://colab.sandbox.google.com/gist/Saduf2019/ff1cf5b8fbd883b1677cf41088166bc0/untitled211.ipynb). Thanks!

**Comment by vinorth05** [comment]
Hello everyone, I also have the exact same error : 

Traceback (most recent call last):
  File "convert_tflite.py", line 111, in <module>
    app.run(main)
  File "/home/vinorth/anaconda3/envs/yolov4-tflite/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/vinorth/anaconda3/envs/yolov4-tflite/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "convert_tflite.py", line 106, in main
    save_tflite()
  File "convert_tflite.py", line 80, in save_tflite
    tflite_model = converter.convert()
  File "/home/vinorth/anaconda3/envs/yolov4-tflite/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py", line 469, in convert
    self.experimental_new_quantizer)
  File "/home/vinorth/anaconda3/envs/yolov4-tflite/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py", line 243, in _calibrate_quantize_model
    inference_output_type, allow_float, enable_mlir_quantizer)
  File "/home/vinorth/anaconda3/envs/yolov4-tflite/lib/python3.7/site-packages/tensorflow_core/lite/python/optimize/calibrator.py", line 81, in calibrate_and_quantize
    enable_mlir_quantizer)
  File "/home/vinorth/anaconda3/envs/yolov4-tflite/lib/python3.7/site-packages/tensorflow_core/lite/python/optimize/tensorflow_lite_wrap_calibration_wrapper.py", line 115, in QuantizeModel
    return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_QuantizeModel(self, *args)
RuntimeError: Max and min for dynamic tensors should be recorded during calibration

If you suspect this is an IPython 7.15.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by jvishnuvardhan** [comment]
@vladdders Can you please try the solution mentioned [here](https://github.com/tensorflow/tensorflow/issues/39718#issuecomment-638386789) and let us know whether it worked for you. Thanks!

**Comment by vladdders** [comment]
hey @jvishnuvardhan thanks for your answer. I have attempted the conversion as suggested on that answer but unfortunately I am still getting the same error. I updated the [gist](https://colab.research.google.com/drive/1yIx_J3NfIlDpaJw9XMgXpIT4XY69Y6nJ?usp=sharing#scrollTo=lgWmPjJjy9e-) so you can see it as well.

**Comment by vladdders** [comment]
It seems that there was a `tf.tile` operation in my graph that cannot be quantized and probably was caught by this min/max exception. The correct exception seems to have been fixed in `tf-nightly-gpu==2.3.0.dev20200615`. Thanks for your support though!

**Comment by sandeep22-v** [comment]
I have the same issue...
I saw here that installing tf-nightly-gpu==2.3.0.dev2020061 can solve the issue,but I'm unable to install a specific version of tf-nightly-gpu using pip,it always installs the latest version.
How can tf-nightly-gpu==2.3.0.dev2020061 be installed

**Comment by jvishnuvardhan** [comment]
@sandeep22-v Can you please open a new issue with a simple standalone code to reproduce the issue? Thanks!

**Comment by sandeep22-v** [comment]
> @sandeep22-v Can you please open a new issue with a simple standalone code to reproduce the issue? Thanks!

Sure sir..will do it now
