### ISSUE TITLE
Can't import tensorflow ( tf-nightly-gpu)

### ISSUE THREAD

**Issue by voravich-ch** [tensorflow/tensorflow#39903]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Window10
- TensorFlow installed from (source or binary): Anaconda
- TensorFlow version: tf-nightly-gpu    2.3.0.dev20200526
- Python version: Python 3.7.4
- Installed using virtualenv? pip? conda?: Yes
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory:  NVIDIA GeForce RTX 2070 with Max-Q design (8GB)

**Describe the problem**
I updated my driver to the latest version, installed Visual Studio 2019 and CUDA/cuDNN version 10.1. I installed tensorflow through Anaconda prompt: pip install tf-nightly-gpu

**Provide the exact sequence of commands / steps that you executed before running into the problem**
from tensorflow.keras.applications.efficientnet import EfficientNetB0
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.efficientnet import preprocess_input

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     63   try:
---> 64     from tensorflow.python._pywrap_tensorflow_internal import *
     65   # This try catch logic is because there is no bazel equivalent for py_extension.

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-4eb6aa7ec913> in <module>
----> 1 from tensorflow.keras.applications.efficientnet import EfficientNetB0
      2 from tensorflow.keras.preprocessing import image
      3 from tensorflow.keras.applications.efficientnet import preprocess_input

~\Anaconda3\lib\site-packages\tensorflow\__init__.py in <module>
     39 import sys as _sys
     40 
---> 41 from tensorflow.python.tools import module_util as _module_util
     42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
     43 

~\Anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>
     48 import numpy as np
     49 
---> 50 from tensorflow.python import pywrap_tensorflow
     51 
     52 # Protocol buffers

~\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     81 for some common reasons and solutions.  Include the entire stack trace
     82 above this error message when asking for help.""" % traceback.format_exc()
---> 83   raise ImportError(msg)
     84 
     85 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\Users\G7\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

---------------------------------------------------------------------------

The installation works for my colleagues but it doesn't work for my notebook and we could not solve the problem. 

Thank you in advance!
Voravich

**Comment by Saduf2019** [comment]
@voravich-ch 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements).
Make sure to download the latest [microsoft visual c++ redistributable](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) from here.
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.Please, refer similar issue #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
Thanks!

**Comment by voravich-ch** [comment]
> @voravich-ch
> 
> What is make/model of your cpu?
> I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements).
> Make sure to download the latest [microsoft visual c++ redistributable](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) from here.
> .Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).
> 
> Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.Please, refer similar issue #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
> Thanks!

My CPU is Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz 2.59 GHz
Both my CPU and Python is on 64bits.

**Comment by voravich-ch** [comment]
I installed microsoft visual c++ redistributable  and it works now 
Thank you Saduf2019 !
