### ISSUE TITLE
XLA compilation requires that operator arguments that represent shapes or dimensions be evaluated to concrete values at compile time

### ISSUE THREAD

**Issue by EgorLakomkin** [tensorflow/tensorflow#39904]
Hi,

I am compiling a custom RNN with XLA (colab link to reproduce with tf-nightly https://colab.research.google.com/drive/1ehh6kklHmXSmcDs6mCdM-6y59v01dXKF?usp=sharing#scrollTo=MpeMlEwGje0n).

What I get is:
    XLA compilation requires that operator arguments that represent shapes or dimensions be evaluated to concrete values at compile time

 It could be as well that I am doing something completely wrong, though.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/2b38a0398bdb8cc66c2713689a44389c/39904.ipynb). Thanks!

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/36c6f4413dd89ea06e9403a5f9cedd5c/untitled285.ipynb) ..Thanks!

**Comment by sushreebarsa** [comment]
Closing this issue as it is fixed in latest version of TensorFlow. Please feel free to reopen the issue if you still have a concern. Thanks!
