### ISSUE TITLE
import tensorflow: Library not loaded: libcudart 7.5 (Mac OSX)

### ISSUE THREAD

**Issue by kristianmandrup** [tensorflow/tensorflow#3991]
### Environment info
Operating System: Mac OSX El Capitan

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

What is CUDA and cuDNN? I didn't notice any mention of these!?

`Optional: Install CUDA (GPUs on Linux)` but I'm on a Mac!!

```
$ ls -l /path/to/cuda/lib/libcud*
ls: /path/to/cuda/lib/libcud*: No such file or directory
```

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

`ImportError ... Library not loaded: @rpath/libcudart.7.5.dylib`

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Steps to reproduce

Following install instructions for Mac OSX: http://learningtensorflow.com/lesson1/
https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html

Just realised there is one for 0.10 as well: https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html

### What have you tried?

I tried to follow the install instructions.

```
21:37 $ source activate tensorflow
(tensorflow) ✔ 
21:38 $ pip install --ignore-installed --upgrade $TF_BINARY_URL
Collecting tensorflow==0.10.0rc0 from https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow-0.10.0rc0-py3-none-any.whl
  Downloading https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow-0.10.0rc0-py3-none-any.whl (94.1MB)
    100% |████████████████████████████████| 94.1MB 7.1kB/s 
Collecting numpy>=1.10.1 (from tensorflow==0.10.0rc0)
  Using cached numpy-1.11.1-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting six>=1.10.0 (from tensorflow==0.10.0rc0)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting protobuf==3.0.0b2 (from tensorflow==0.10.0rc0)
  Using cached protobuf-3.0.0b2-py2.py3-none-any.whl
Collecting wheel>=0.26 (from tensorflow==0.10.0rc0)
  Using cached wheel-0.29.0-py2.py3-none-any.whl
Collecting setuptools (from protobuf==3.0.0b2->tensorflow==0.10.0rc0)
  Using cached setuptools-26.0.0-py2.py3-none-any.whl
Installing collected packages: numpy, six, setuptools, protobuf, wheel, tensorflow
Successfully installed numpy-1.11.1 protobuf-3.0.0b2 setuptools-25.1.6 six-1.10.0 tensorflow-0.10.0rc0 wheel-0.29.0
(tensorflow) ✔ ~/repos/aurelia-projs/ai/ai-component [master|✔] 

21:40 $ python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kristianmandrup/anaconda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/Users/kristianmandrup/anaconda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/kristianmandrup/anaconda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Users/kristianmandrup/anaconda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/Users/kristianmandrup/anaconda/envs/tensorflow/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/kristianmandrup/anaconda/envs/tensorflow/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/kristianmandrup/anaconda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.7.5.dylib
  Referenced from: /Users/kristianmandrup/anaconda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found
```

**Comment by kristianmandrup** [comment]
Seems the trouble is this: http://stackoverflow.com/questions/38710339/library-not-loaded-rpath-libcudart-7-5-dylib-tensorflow-error-on-mac

**Comment by pkmital** [comment]
I had this issue just after upgrading to 10.11.  I had been using the GPU version of Tensorflow just fine in 10.10.  I also tried reinstalling w/ pip and from source with the same issue.  I could only resolve it by restarting in Recovery mode (CMD+R during start up), and then open Terminal, and run "csrutil disable", to disable System Integration Protection or something along those lines.  I think without doing this, 10.11 will not check DYLD/LD_LIBRARY_PATH.  In any case, hope this helps someone, or that they can shed some light on whether this was a bad idea or not (seems slightly bad).

**Comment by ruohoruotsi** [comment]
There are multiple ways to get this error, only one of which is having the wrong TF (cpu vs gpu). I've run into this, and all paths, env, CUDAs are straight, but per @pkmital I suspect I'll have to dispable 10.11's SIP :(

**Comment by yaroslavvb** [comment]
I've seen similar issue with SIP. Was getting "@rpath/libcudart.7.5.dylib" error, disable SIP, it started working. Upgraded El Capitan (this re-enabled SIP), it stopped working. Disabled SIP, started working again.

**Comment by laventura** [comment]
hi @pkmital  - I came across your solution.

I'm running in the same problems.
``Library not loaded: @rpath/libcudart.7.5.dylib

Is your solution for CUDA-8.0 or for CUDA-7.5?

Thanks!

**Comment by yaroslavvb** [comment]
CUDA-7.5 because TF official binaries (11rc0 or before) don't suport CUDA 8

**Comment by ruohoruotsi** [comment]
I was able to resolve my problem by *uninstalling* tensorflow (which I had installed using the `https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.10.0rc0-py3-none-any.whl` & my anaconda's pip). 

Instead I did `conda install -c conda-forge tensorflow=0.10.0` per [https://anaconda.org/conda-forge/tensorflow](https://anaconda.org/conda-forge/tensorflow)

My system is El Capitan (10.11.6), Python 3.5.2 :: Anaconda custom (x86_64), conda 4.1.6

**Comment by jimmyein** [comment]
Did you have NVIDA GPU on your Mac?
If not then don't use the CUDA version of the tensor flow.
Uninstall tensor flow and reinstall the CPU version of the tensor flow you will be able to bypass the error.
