### ISSUE TITLE
NNAPI Reference does not output the same result as CPU for style transfer app on android for tensorflow lite

### ISSUE THREAD

**Issue by amitDaMan** [tensorflow/tensorflow#39923]
I have altered this app significantly such that "StyleTransferModelExecutor" could configure the interpreter with more fine granularity:
For example: 
`StyleExecutor(appContext, quant = true, device = Device.NNAPI, NNAcc = "nnapi-reference")`

I am more than willing to share all that code, however the main point is:
running inference with: 
style_predict_quantized_256.tflite"
style_transfer_quantized_384.tflite

On CPU is different than NNAPI reference.

This is how I set the options for nnapi reference:
```
val tfliteOptions = Interpreter.Options()
var opts = NnApiDelegate.Options()
opts.setAcceleratorName("nnapi-reference")
tfliteOptions.addDelegate(NnApiDelegate(opts))
Interpreter(loadModelFile(context, modelName), tfliteOptions)
```

I have an instrumented test that essentially runs noise through the models, and compares the results, and the results are significantly different. 

I believe this is a bigger issue than just transfer style, and really relates to quantized models on nnapi not agreeing with cpu. I just use this app as a basis for re reproducibility

Feeding in noise:
![content](https://user-images.githubusercontent.com/16094320/83071496-10d5ca00-a022-11ea-8a42-98d64db06e93.png)
![style](https://user-images.githubusercontent.com/16094320/83071511-13d0ba80-a022-11ea-81da-79234966b65a.png)

CPU and GPU inference agree:
![cpuInference](https://user-images.githubusercontent.com/16094320/83071501-1206f700-a022-11ea-87fd-46bda36dceee.png)
![gpuInference](https://user-images.githubusercontent.com/16094320/83071504-129f8d80-a022-11ea-97ee-a0c37960ea1d.png)

NNAPI Reference differs:
![nnInference](https://user-images.githubusercontent.com/16094320/83071508-13382400-a022-11ea-9a1f-b26f9d849aac.png)

**Comment by amitDaMan** [comment]
(Further information)

The models are taken from the tflite example project "style transfer" and looking at this particular gradle file, you can see the links where the models are stored:
https://github.com/tensorflow/examples/blob/master/lite/examples/style_transfer/android/app/download_model.gradle

or:
https://www.tensorflow.org/lite/models/style_transfer/overview
at the bottom of this page, the models are there (though I used the gradle links)

And I will include them in this message as well 
[quantized_models.zip](https://github.com/tensorflow/tensorflow/files/4696938/quantized_models.zip)

**Comment by srjoglekar246** [comment]
Can confirm that the output is different for NNAPI vs CPU using the inference tool:

```
$ blaze build -c opt   --config=android_arm64   //third_party/tensorflow/lite/tools/evaluation/tasks/inference_diff:run_eval && adb push blaze-bin/third_party/tensorflow/lite/tools/evaluation/tasks/inference_diff/run_eval /data/local/tmp
...
$ adb shell /data/local/tmp/run_eval \
  --model_file=/data/local/tmp/style_predict_quantized_256.tflite \
  --delegate=nnapi
...
OutputDiff[0]: avg_error=2.25797, std_dev=0.0116284
```

This shows a raw error of 2.2 averaged across all elements of the output tensor. For comparison, `delegate=hexagon` gives an error of ~0.008. I tried delegating only half the graph by modifying the delegate, and the error is still ~0.99.

Adding Miao from NNAPI.

**Comment by miaowang14** [comment]
The issue has been found in NNAPI delegate and the fix has been submitted internally.

You should be able to sync later today and verify the fix.

Thanks for reporting the issue!
