### ISSUE TITLE
Add support for pyx_library in the open-source build.

### ISSUE THREAD

**Issue by iportillo** [tensorflow/tensorflow#3992]
I have a model that has a lot of big constant Tensors (2048x2048), and building the graph is extremely slow. After profiling my code, I see that the bottlenecks are the functions `SlowAppend<TYPE>ArrayToTensorProto`  defined in `tensorflow/python/framework/tensor_util.py` which take 98% of the time. 

Reviewing the source code I see the following lines:
```
# TODO(opensource): Add support for pyx_library in the open-source build.
# For now, we use the slow versions that fast_tensor_util replaces.
# pylint: disable=g-import-not-at-top
```
So I was wondering if it is planned to add this feature in the short term, and if not, any advice on how to speed up the graph building process? 

Thanks

**Comment by prb12** [comment]
> So I was wondering if it is planned to add this feature in the short term, 

We are unable to comment on timeframes for specific feature requests.  

>  any advice on how to speed up the graph building process?
This is a general TensorFlow usage question best suited for StackOverflow.  Please can you re-ask there. 
(In general, you would be better off avoiding adding large constants to your program.  Consider reading them as input, or computing them once at runtime.)

**Comment by iportillo** [comment]
@prb12 Sorry to open this topic again and thanks for the suggestion of using placeholders / computing them on runtime. 

However, I have a follow up question related to the implementation of the`SlowAppend<TYPE>ArrayToTensorProto` functions. Seems that most of these functions follow the pattern:

```  
def SlowAppend<TYPE>ArrayToTensorProto(tensor_proto, proto_values):
    tensor_proto.<TYPE>_val.extend([np.asscalar(x) for x in proto_values])
```

I was wondering if there is an special reason for not using the `tolist()` method from numpy, as in:

``` 
 def SlowAppend<TYPE>ArrayToTensorProto(tensor_proto, proto_values):
    tensor_proto.<TYPE>_val.extend(proto_values.tolist())
```

This is much faster for large arrays, and doing some tests seems that the values obtained using both methods are the same (value & type). So I just wanted to check if I am missing something.
The only reason for not using `tolist()` I can think of is that it does not return the same type as `np.asscalar()`. Reading the documentation for `tolist()` it says:
> Data items are converted to the nearest compatible Python type.

whereas for `np.asscalar()` it reads:

> A copy of the specified element of the array as a suitable Python scalar

Isn't the nearest compatible Python type the same as the suitable Python scalar? I just wanted to check because changing this in the code is super-fast and the speed-up for big constant tensors is really huge.

Thanks again!

**Comment by prb12** [comment]
@keveman  I realize the functions are named `SlowAppend` ... but looks like they could be slightly less slow?
