### ISSUE TITLE
MultiWorker Mirrored strategy fails to start with TF_CONFIG

### ISSUE THREAD

**Issue by ssagkriotis** [tensorflow/tensorflow#39922]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes. A few imports, no fundamental changes. 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6.9 
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Script is getting stuck at: 
2020-05-27 12:45:54.403718: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:390] Started server with target: grpc://localhost:12345

No further further output beyond this point

**Describe the expected behavior**
The training should proceed as in tutorial.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
import tensorflow as tf
import numpy as np
import os
import json

os.environ['TF_CONFIG'] = json.dumps({
    'cluster': {
        'worker': ["localhost:12345", "localhost:23456"]
    },
    'task': {'type': 'worker', 'index': 0}
})


def mnist_dataset(batch_size):
  (x_train, y_train), _ = tf.keras.datasets.mnist.load_data()
  # The `x` arrays are in uint8 and have values in the range [0, 255].
  # We need to convert them to float32 with values in the range [0, 1]
  x_train = x_train / np.float32(255)
  y_train = y_train.astype(np.int64)
  train_dataset = tf.data.Dataset.from_tensor_slices(
      (x_train, y_train)).shuffle(60000).repeat().batch(batch_size)
  return train_dataset

def build_and_compile_cnn_model():
  model = tf.keras.Sequential([
      tf.keras.Input(shape=(28, 28)),
      tf.keras.layers.Reshape(target_shape=(28, 28, 1)),
      tf.keras.layers.Conv2D(32, 3, activation='relu'),
      tf.keras.layers.Flatten(),
      tf.keras.layers.Dense(128, activation='relu'),
      tf.keras.layers.Dense(10)
  ])
  model.compile(
      loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
      optimizer=tf.keras.optimizers.SGD(learning_rate=0.001),
      metrics=['accuracy'])
  return model

strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()

# Worker related variables
num_workers = 4
per_worker_batch_size = 64
global_batch_size = per_worker_batch_size * num_workers
multi_worker_dataset = mnist_dataset(global_batch_size)

with strategy.scope():
  # Model building/compiling need to be within `strategy.scope()`.
  multi_worker_model = build_and_compile_cnn_model()

multi_worker_model.fit(multi_worker_dataset, epochs=3, steps_per_epoch=70)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Complete output of the script on execution:
2020-05-27 20:36:51.353890: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-05-27 20:36:51.353922: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-05-27 20:36:51.353941: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (dell3): /proc/driver/nvidia/version does not exist
2020-05-27 20:36:51.380090: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3392065000 Hz
2020-05-27 20:36:51.381000: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fa764000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-27 20:36:51.381033: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-27 20:36:51.396045: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> localhost:12345, 1 -> localhost:23456}
2020-05-27 20:36:51.396385: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:390] Started server with target: grpc://localhost:12345

The code is tested on a fresh virtual environment with tensorflow. The same error is reproduced with the tensorflow/tensorflow docker container. It was also reproduced with Python 3.8.3. 

The script proceeds with execution if the code that sets the TF_CONFIG environment variable is removed. However, execution on multiple machines is not possible without setting TF_CONFIG.

**Comment by amahendrakar** [comment]
@ssagkriotis,
As per [this document](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras#multi-worker_configuration), TF_CONFIG with the above values is likely to fail.

Please take a look at [this guide](https://www.tensorflow.org/guide/distributed_training#setting_up_tf_config_environment_variable) to set up TF_CONFIG and let us know if it helps. Thanks!

**Comment by ssagkriotis** [comment]
> 
> 
> @ssagkriotis,
> As per [this document](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras#multi-worker_configuration), TF_CONFIG with the above values is likely to fail.
> 
> Please take a look at [this guide](https://www.tensorflow.org/guide/distributed_training#setting_up_tf_config_environment_variable) to set up TF_CONFIG and let us know if it helps. Thanks!

Thanks for replying. The issue ended up being that I had to run another instance of the whole script with the index number set to 1.

**Comment by RoopendraSingh** [comment]
> 
@ssagkriotis 
I too facing issue,
How to run another instance of the whole script with the index number set to 1?
