### ISSUE TITLE
lstm_cell.get_initial_state(batch_size, dtype) caught 'Duplicate node name' error if batch_size is unknown

### ISSUE THREAD

**Issue by carusyte** [tensorflow/tensorflow#39936]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
<ins>Yes</ins>
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
<ins>macOS Catalina version 10.15.5</ins>
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
<ins>No</ins>
- TensorFlow installed from (source or binary):
<ins>binary</ins>
- TensorFlow version (use command below):
<ins>2.1.0</ins>
- Python version:
<ins>3.7.7</ins>
- Bazel version (if compiling from source):
<ins>N/A</ins>
- GCC/Compiler version (if compiling from source):
<ins>N/A</ins>
- CUDA/cuDNN version:
<ins>N/A</ins>
- GPU model and memory:
<ins>N/A</ins>

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Calling `get_initial_state(batch_size, dtype)` from LSTMCell caught `ValueError: Duplicate node name in graph: 'zeros/packed'` error if batch_size is unknown or inferred from `tf.shape(input)[0]`

**Describe the expected behavior**
`get_initial_state(batch_size, dtype)` returns the expected states even if batch_size is a Tensor, because often times the batch_size is unknown beforehand and could be varied from each run

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

This code works:
```
import tensorflow as tf
cell = tf.keras.layers.LSTMCell(units=32, name="controller")
state = cell.get_initial_state(batch_size=2, dtype=tf.float32)
print(state)
```

The following doesn't work:
```
import tensorflow as tf
cell = tf.keras.layers.LSTMCell(units=32, name="controller")
i = tf.keras.Input(shape=[2, 3])
state = cell.get_initial_state(batch_size=tf.shape(i)[0], dtype=tf.float32)
print(state)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
The functionality is required in a [DNC model](https://github.com/carusyte/tf-DNC/blob/2ca0f2bf7e9b2dcf45e776db0f733d434246628f/dnc/dnc.py#L148) I'm experimenting with recently.

**Comment by Saduf2019** [comment]
@carusyte 
I ran the code shared on tf 2.2 and do not face the error as faced on 2.1, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/99e8008fde16d35e7d34a86f1ef85d11/untitled198.ipynb)

**Comment by carusyte** [comment]
> @carusyte
> I ran the code shared on tf 2.2 and do not face the error as faced on 2.1, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/99e8008fde16d35e7d34a86f1ef85d11/untitled198.ipynb)

I tried the gist provided and seems they're working on 2.2 version. 
Guess I'll have to upgrade TF and keep up with the pace. Thanks so much, @Saduf2019 !
