### ISSUE TITLE
[TF 2.3.0] [Intel MKL] Eigen Threadpool Support with Intel oneDNN

### ISSUE THREAD

**Issue by nammbash** [tensorflow/tensorflow#39935]
> <em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**PR to be submitted to replace OpenMP with Eigen Threadpool.**
Attn: @penpornk 

1. https://github.com/tensorflow/tensorflow/pull/39893 **( Merged)**
2. https://github.com/tensorflow/tensorflow/pull/39915 **(Merged)**
3. #40128 **(Merged)**
4. #40254 **(Merged)**
5.  #40488 **(Merged)**
6.  #40489 **(Merged)**

Edited by penpornk@ to update the PR list.

**Comment by penpornk** [comment]
@nammbash Thank you for creating the tracking issue!

**Comment by Srini511** [comment]
@penpornk As mentioned in the description previously, #39877 has been replaced by two smaller PR's. 
https://github.com/tensorflow/tensorflow/pull/40128
https://github.com/tensorflow/tensorflow/pull/40254

**Comment by penpornk** [comment]
@Srini511 Thank you for the heads up. I've updated the first post.

**Comment by penpornk** [comment]
@nammbash Is custom thread pool still on track for 2.3? Are there more PRs for 2.3 coming?

**Comment by nammbash** [comment]
> @nammbash Is custom thread pool still on track for 2.3? Are there more PRs for 2.3 coming?

@penpornk No more PRs from our side. Just that the Eigen PR and the Random Univerform Vectorize is in the works. FYI. Thank you for all the help and hardwork on this.

**Comment by penpornk** [comment]
@nammbash Thank you for the clarification and for all the hard work from your side as well! :)

**Comment by penpornk** [comment]
Closing this issue since all the tracked PRs are merged.
