### ISSUE TITLE
[TF 2.3.0] [Intel MKL] BFloat16 Support for Intel CPUs

### ISSUE THREAD

**Issue by nammbash** [tensorflow/tensorflow#39934]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**Adding support for Bfloat16 datatype for running models on Intel CPUs.**
Attn: @penpornk 
**The following PRs have been submitted for inclusion in TF2.3.0**
1. #34504 **(Closed)**; Replaced by #40596 **(Merged)**
2. #39597 **(Merged)**
3. #40212 **(Merged)**
4. #40211 **(Merged)**
5. #40455 **(Merged)** 
6. #40330 **(Merged)**
7. #40598 **(Merged)**

TF2.3.0 performance of Resnet-50-v1.5 depends on Eigen PR: 

8. [Eigen MR #84](https://gitlab.com/libeigen/eigen/-/merge_requests/84) **(Merged)**
9. #40684 **(Merged as https://github.com/tensorflow/tensorflow/commit/8cf97846290cf7d8b95256fe3123abaaa8c8e553)**

**Postponed to 2.4**
* [Change the type `tensorflow::bfloat16` to `Eigen::bfloat16`](https://gitlab.com/libeigen/eigen/-/merge_requests/84#note_365322477).
* Vectorize RandomUniform: https://github.com/tensorflow/tensorflow/pull/39747 **(Test failure)**

**Comment by penpornk** [comment]
@nammbash Thank you for creating the tracking issue!

**Comment by nammbash** [comment]
@penpornk  
#34504 is still pending internal merge required for TF2.3. Friendly reminder

**Comment by penpornk** [comment]
@nammbash Thank you for the reminder!
Approved #40598 .
#34504 doesn't look like it's approved yet. I'll follow up on it.

**Comment by penpornk** [comment]
By the way, #39747 has a new test failure (posted on the PR) and can't be merged until it's fixed.

**Comment by penpornk** [comment]
#34504 has been replaced by #40596 which was merged yesterday. I'll update the first post.

**Comment by penpornk** [comment]
#40598 is merged.

**Comment by nammbash** [comment]
@penpornk  Looks like we were all updating together. 
Please take a look at it now. Eigen Third party PR upgraded submitted and pending Review.
@agramesh1 will update on any other Pending PR decision.

**Comment by penpornk** [comment]
The branch has been cut. I'm closing the issue now. Thank you all again for your hard work!

**Comment by nammbash** [comment]
@penpornk thank you too!
