### ISSUE TITLE
per-channel quantization

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#39944]
Hello,

It seem the tool by default uses "per-channel-quantization" is this possible to turn-off during quantization? I need that support to switch-off (switch-off per-channel quantization) since my device does not support it and is an integer only hardware accelerator.

I am looking for a way to quantize it all uniformly, so all input channels are quantized equally (in the same range) and fully. is there some special setting or the way to do it so?

Thank you for your help and advice.

**Comment by ravikyram** [comment]
@peter197321 

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by peter197321** [comment]
here is a snippet from code

```
            # full integer quantization - weights and activations
            converter.optimizations = [tensorflow.lite.Optimize.DEFAULT]
            filename += "_quant_full"
            converter.representative_dataset = __imagenet_sample_gen_fn
            if force_full_quant:  # experimental code for compatibility
                converter.target_spec.supported_ops = [tensorflow.lite.OpsSet.TFLITE_BUILTINS_INT8]
                converter.inference_input_type = tensorflow.uint8
                converter.inference_output_type = tensorflow.uint8
                filename += "_forced"
            else:
                filename += "_default"

    tf_model = converter.convert()
```

**Comment by ymodak** [comment]
You may try [Post-training integer quantization](https://www.tensorflow.org/lite/performance/post_training_integer_quant) in this case.
It ensures compatibility with integer only devices.
See https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only

**Comment by peter197321** [comment]
this way of quantization doesn't work if per-channel quantization for the device I have ... So the question of how to turn-off this way quantization and not to use per-channel quantization as you are implicitly suggesting.

**Comment by peter197321** [comment]
just fyi: models from [Hosted models](https://www.tensorflow.org/lite/guide/hosted_models) works for me but models from [Coral Edge TPU](https://coral.ai/models/) do not work.

What is a different quantization method used?

**Comment by peter197321** [comment]
Is it possible to enforce Per-axis (aka per-channel) or Per-tensor quantization on the model?

**Comment by pkgoogle** [comment]
Hi @peter197321,

As it has been awhile, can you try out the current code to see if it meets your objectives? Thanks.
