### ISSUE TITLE
Building libtensorflow.so 1.10.1 on Linux with GCC 4.8 and -std=c++11 doesn't export CXX11 symbols

### ISSUE THREAD

**Issue by segvee** [tensorflow/tensorflow#39941]
**System information**
- OS: CentOS 7.6
- TensorFlow installed from: source
- TensorFlow version: 1.10.1
- Python version: 2.7
- Bazel version: 0.15.0
- GCC version: 4.8.5

**Describe the problem**
When I try to build a shared TensorFlow library on CentOS 7 with the GCC 4.8 compiler the compiled library doesn't used C++11 for their exported symbols. However, when I try to use the library in a standalone program and include the TensorFlow headers it fails during linking because it expects C++11 symbols whereas they are not present in the libtensorflow.so shared library, e.g.
```undefined reference to `tensorflow::Status::ToString[abi:cxx11]() const```
where as libtensorflow_framework.so has
```T tensorflow::Status::ToString() const```.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Priory to building I have altered `.tf_configuration.bazelrc` (imported in .bazlerc) by including
`build --cxxopt='-std=c++11'`.
Furthermore, I have added to the tensorflow/BUILD file
`linkopts = ["-std=c++11"]`
`copts = ["-std=c++11"]`
to the libtensorflow_framework.so and libtensorflow.so targets.
Finally I invoke the build with
`bazel build --cxxopt='-std=c++11' tensorflow::libtensorflow.so`
but the resulting libtensorflow.so doesn't export C++11 symbols.

When I tried building libtensorflow.so with GCC 5 on a Linux Mint machine it exported the symbols as C++11; furthermore I can compile tensorflow 2 on my Debian machine and the symbols also use C++11. For my particular purpose, though, I need to use GCC 4.8 and that's where it fails.

Is it, bychance, possible to statically link the standard C++ libraries in the tensorflow library?

**Comment by cpkson** [comment]
Have you tried compiling with a newer devtoolset? GCC 4.8 doesn't support the C++11 flags.

```
sudo yum install centos-release-scl
sudo yum install devtoolset-8-gcc devtoolset-8-gcc-c++
scl enable devtoolset-8 -- bash #sets gcc8 as the default compiler for a session within your current session
```

**Comment by segvee** [comment]
The target system this is being built for only has GCC 4.8 that is why I need to get it working in a GCC 4.8 environment.
What do you mean GCC 4.8 doesn't support C++11 flags? I thought -std=c++11 works with GCC 4.8?

**Comment by ymodak** [comment]
Can you please try to build from one of the supported versions (1.15, 2.0, 2.1, 2.2, master)?
TF 1.10.1 is too old for support.
