### ISSUE TITLE
Tflite convertor generates 2 graphs 

### ISSUE THREAD

**Issue by OriAlpha** [tensorflow/tensorflow#39949]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04):
- TensorFlow installed from (source):
- TensorFlow version (tf-nightly.2.3.0-dev20200527):

I have used the latest version of TF-nightly and used it for the quantization of a model.
The model consists of LSTM layers, when I tried to convert to tflite version it generates main and subgraph.  

The subgraph consists of LSTM while loop. How can I combine this multiple graph into a single graph.

Following is the code used for conversion 

`converter = tf.lite.TFLiteConverter.from_keras_model(model)`
`converter.optimizations = \[tf.lite.Optimize.DEFAULT\]`
`converter.experimental_new_converter = True`
`tflite_model = converter.convert()`
`open("converted_model.tflite", "wb").write(tflite_model)`

**Comment by jvishnuvardhan** [comment]
@OriAlpha Can you please share a standalone code to reproduce the issue? Model code or saved models would be better. Thanks!

**Comment by OriAlpha** [comment]
```
model.add(TimeDistributed(Conv2D(32, (7, 7), strides=(2, 2),activation='relu', padding='same'), input_shape=(60,15,80,80,3)))
model.add(TimeDistributed(Conv2D(32, (3,3),kernel_initializer="he_normal", activation='relu')))
model.add(TimeDistributed(MaxPooling2D((2, 2), strides=(2, 2))))
model.add(TimeDistributed(Flatten()))
model.add(LSTM(256, return_sequences=False, dropout=0.5))
```

You could use this code to generate the model and use the above code to convert to TFLITE

**Comment by jvishnuvardhan** [comment]
@OriAlpha Can you please check [this issue](https://github.com/tensorflow/tensorflow/issues/39564#issuecomment-628950492) which is i guess similar. Please let us know whether it helped or not. If that didn't help, then please provide entire standalone code in one colab or jupyter notebook. Thanks!

**Comment by OriAlpha** [comment]
the page is giving errors as below 
Sorry, the file you have requested does not exist.

**Comment by jvishnuvardhan** [comment]
Can you please check this https://github.com/tensorflow/tensorflow/issues/39564. Thanks!
