### ISSUE TITLE
ERROR: Unrecognized option: --experimental_repo_remote_exec

### ISSUE THREAD

**Issue by why-freedom** [tensorflow/tensorflow#39948]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.8.0
- Python version: 3.5.2
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):0.10.0
- GCC/Compiler version (if compiling from source):6.5.0
- CUDA/cuDNN version:9.0/7.1
- GPU model and memory:1050 , 2G

**Describe the problem**
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=114
INFO: Reading rc options for 'build' from /home/why/Downloads/NVIDIA_driver&CUDA&Tensorflow/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
WARNING: while reading option defaults file '/home/why/Downloads/NVIDIA_driver&CUDA&Tensorflow/tensorflow/.bazelrc':
  invalid command name 'try-import'.
WARNING: while reading option defaults file '/home/why/Downloads/NVIDIA_driver&CUDA&Tensorflow/tensorflow/.bazelrc':
  invalid command name 'try-import'.
ERROR: Unrecognized option: --experimental_repo_remote_exec

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@why-freedom,
Is there any specific reason you are using TensorFlow 1.8? 

Could you please upgrade to TensorFlow 2.x and let us know if you are facing the same issue. Thanks!

**Comment by runfengxu** [comment]
similar problem. 
I already got tensorflow installed using conda install.

**Comment by amahendrakar** [comment]
@runfengxu,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template so that we can track the issue there. Thanks!

**Comment by wu-yy** [comment]
Maybe, the `bazel` version is not matched. so you can find the "_TF_MIN_BAZEL_VERSION" and "_TF_MAX_BAZEL_VERSION" in a file of  "tensorflow/configure.py".
