### ISSUE TITLE
The problem of using the function “SetDefaultDevice” to set the gpu

### ISSUE THREAD

**Issue by wangwenchao-job** [tensorflow/tensorflow#39953]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:no
- TensorFlow installed from (source or binary):source C++
- TensorFlow version (use command below):2.1
- Python version:3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.0 , 7.6.5
- GPU model and memory:4G

**Describe the current behavior**

Use the following code to set the gpu, but it has no effect：
```
status = LoadSavedModel(sessionOptions, runOptions, model_path, { "serve" }, &bundle);
std::unique_ptr<tensorflow::Session>& session = bundle.session;
GraphDef graphdef;
session->Create(graphdef);
graph::SetDefaultDevice("/gpu:2", &graphdef);
```

No matter how many parameters I set, it shows that gpu is found: 0

**Comment by ymodak** [comment]
By using a python session can you please print [list of visible devices](https://www.tensorflow.org/api_docs/python/tf/config/get_visible_devices) in your session.
You can use:
```python
tf.config.get_visible_devices(device_type=None)
```
This can help us determine if other devices are recognized or not. Thanks!
