### ISSUE TITLE
Convert keras model to quantized tflite lost precision

### ISSUE THREAD

**Issue by ChiHangChen** [tensorflow/tensorflow#39954]
I'm trying to convert my keras model into tflite quantized model so that I can run my model on coral TPU, but the output of my keras model and tflite model are significantly different.

The red points are quantized tflite model output, and blue points are original keras model output.

[img is here](https://i.stack.imgur.com/AdFyR.png)

Here is my code to convert keras model to quantized tflite model :

```
quant = True
gc.collect()
import tensorflow as tf
import numpy as np
import pathlib
print(tf.__version__)
converter = tf.lite.TFLiteConverter.from_keras_model(model)
if quant:
    print("Converting quant....")
    sample_size = 200
    rdm_idx = np.random.choice(range(len(X_test)),sample_size)
    rep_data = tf.cast(X_train[rdm_idx], tf.float32) / 255.0
    dataset = tf.data.Dataset.from_tensor_slices(rep_data).batch(1)

    def representative_data_gen():
        for input_value in dataset.take(sample_size):
            yield [input_value]

    converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
    converter.representative_dataset = representative_data_gen
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.uint8
    converter.inference_output_type = tf.uint8
    tflite_model_quant = converter.convert()
    open("MaskedLandMarkDetction_MobileNetV2_quant_fromKeras_v5.tflite", "wb").write(tflite_model_quant)

    print("Write quantization tflite done.")
else:
    print("Converting normal....")
    tflite_model = converter.convert()
    open("MaskedLandMarkDetction_MobileNetV2_fromKeras.tflite", "wb").write(tflite_model)
    print("Write tflite done.") 
```

`X_train `is my training data, and I will scale input images value from 0 to 1 by divided `255.`, so I do the same in `representative_data_gen `functions.

Any assistance you can provide would be greatly appreciated.

**Comment by ChiHangChen** [comment]
I use tensorflow-gpu==2.2.0 BTW.

**Comment by amahendrakar** [comment]
In order to expedite the trouble-shooting process, could you please provide the keras model file you are using in the code. Thanks!

**Comment by ChiHangChen** [comment]
> In order to expedite the trouble-shooting process, could you please provide the keras model file you are using in the code. Thanks!

Sure, you can download my weights file from my [google drive](https://drive.google.com/file/d/1_9Nl5dT17HLap0H_kNZTGqUAYh3XMsnQ/view?usp=sharing), and the following code is my model structure :
```

from tensorflow.keras.applications.mobilenet_v2 import MobileNetV2
from tensorflow.keras.layers import *
from tensorflow.keras.models import Model

input_shape = (96,96,3)
model = MobileNetV2(input_shape = input_shape, weights="imagenet",alpha=1.0, include_top=False)
inp = model.input
out = model.output
x = GlobalAveragePooling2D()(out)
x = Dropout(0.2)(x)
masked_output = Dense(64, activation = "relu")(x)
masked_output = Dense(16, activation = "relu")(masked_output)
masked_output = Dense(8, activation = "relu")(masked_output)
masked_output = Dense(2, name='masked', activation = "softmax")(masked_output)

LandMark_output = Dense(64,activation="relu")(x)
LandMark_output = Dense(32,activation="relu")(LandMark_output)
LandMark_output = Dense(10,name="landmark",activation = "sigmoid")(LandMark_output)

model = Model(inp,outputs = [masked_output,LandMark_output])

model.load_weights("best_weights_v5.h5")
```

As you can see from file name of my weights file, this is my 5th version model, and this problem only occur on this version, the same code works well on the previous version of my model weights.

**Comment by ChiHangChen** [comment]
If you need my training data to run the representative data function, there is a download link in my [github repository](https://github.com/ChiHangChen/Masked_Classification_with_Facial_Landmark)

**Comment by amahendrakar** [comment]
@ChiHangChen,
While running the code, I am facing an error stating `NameError: name 'X_test' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/184323bc4c5a9cfd16547774111b65da/39954.ipynb#scrollTo=WqwfPdl7R4YG).

I was unable find the data in your repo. Could you please provide a sample of the test and training data you are using in the code. Thanks!

**Comment by ChiHangChen** [comment]
> @ChiHangChen,
> While running the code, I am facing an error stating `NameError: name 'X_test' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/184323bc4c5a9cfd16547774111b65da/39954.ipynb#scrollTo=WqwfPdl7R4YG).
> 
> I was unable find the data in your repo. Could you please provide a sample of the test and training data you are using in the code. Thanks!

**Comment by ChiHangChen** [comment]
> @ChiHangChen,
> While running the code, I am facing an error stating `NameError: name 'X_test' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/184323bc4c5a9cfd16547774111b65da/39954.ipynb#scrollTo=WqwfPdl7R4YG).
> 
> I was unable find the data in your repo. Could you please provide a sample of the test and training data you are using in the code. Thanks!

@amahendrakar Thanks for your kindly help, I upload my `X_test` to google drive as a npy file, you can download it directly from [here]([url](https://drive.google.com/file/d/1HqjHhWZIg9kyrChAm4bXZe8sZnPCIK4L/view?usp=sharing)).

**Comment by amahendrakar** [comment]
> @amahendrakar Thanks for your kindly help, I upload my `X_test` to google drive as a npy file, you can download it directly from here.

@ChiHangChen,
Could you please add the link to the file on your Google Drive. Thanks!

**Comment by ChiHangChen** [comment]
> > @amahendrakar Thanks for your kindly help, I upload my `X_test` to google drive as a npy file, you can download it directly from here.
> 
> @ChiHangChen,
> Could you please add the link to the file on your Google Drive. Thanks!

I can't believe I forgot it.
https://drive.google.com/file/d/1HqjHhWZIg9kyrChAm4bXZe8sZnPCIK4L/view?usp=sharing
Sorry for wasting your time.

**Comment by multiverse-tf** [comment]
Suharsh, could you take a look at this? It looks like this is a duplicate one in StackOverflow: https://stackoverflow.com/questions/62059340/convert-keras-model-to-quantized-tflite-lost-precision

Note, the author had some issues w/ QAT after you suggested it as mentioned in the stackoverflow thread.

**Comment by jvishnuvardhan** [comment]
@ChiHangChen This is a stale issue. 

Is this still an issue for you? Can you please check with recent TF versions as well as try Quantization aware training https://github.com/tensorflow/model-optimization and let us know whether the issue persists or not. Thanks!
