### ISSUE TITLE
TF Lite wheel is not supported on platform including ARMv7 and python 3.6.5

### ISSUE THREAD

**Issue by FlorentijnD** [tensorflow/tensorflow#39957]
@tensorflow/micro

**System information**
- Hardware : Freescale i.MX6 Quad/DualLite
- Processor: ARMv7 Processor rev 10 (v71)
- OS Platform and Distribution: Yocto built Linux distribution (kernel 4.9.4+)
- TensorFlow Lite interpreter installed: wheel https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp36-cp36m-linux_armv7l.whl (https://www.tensorflow.org/lite/guide/python#learn_more) 
- Installed python version: 3.6.5
- Installed pip3 version: 9.0.3

I downloaded the wheel described above from Tensorflow's website and followed the guidelines doing so because the processor is of the ARMv7 type and because the installed python version is 3.6.5. 
I transferred the wheel from my local computer to the hardware over SSH. Now running `pip3 install tflite_runtime-2.1.0.post1-cp36-cp36m-linux_armv71.whl` gives me the following error message: `tflite_runtime-2.1.0.post1-cp36-cp36m-linux_armv71.wh is not a supported wheel on this platform`.

Why is that? As far as I know, the hardware and software answers to all requirements set out to be able to install this particular wheel.

**Comment by FlorentijnD** [comment]
I also tried the same exact thing but with python 3.7.4 and the corresponding ARMv7 wheel and had the same exact outcome.

**Comment by FlorentijnD** [comment]
I also updated pip to the latest current version (20.1.1) and the issue was not resolved

**Comment by terryheo** [comment]
What's the result of the following commnad?
```
python3 -c "import wheel.pep425tags as w; print('\n'.join(['-'.join(p) for p in w.get_supported()]))"
```

**Comment by FlorentijnD** [comment]
`get_supported() missing 1 positional argument: 'archive_root`

**Comment by FlorentijnD** [comment]
wheel version is 0.34.2

**Comment by FlorentijnD** [comment]
setuptools is version 47.1.1

**Comment by terryheo** [comment]
My wheel.get_supported() doesn't require any parameter. Could you check yours? You can find the library location with "pip3 show wheel"

**Comment by FlorentijnD** [comment]
Which version are you using? 
For me it does : 
![image](https://user-images.githubusercontent.com/29673343/83499350-8841a880-a4bd-11ea-8a73-e98c7ae2ecf5.png)

**Comment by terryheo** [comment]
Then why don't you try the following command?
```
python3 -c "import wheel.pep425tags as w; print('\n'.join(['-'.join(p) for p in w.get_supported('')]))"
```

**Comment by FlorentijnD** [comment]
You are right:
Output : 
![image](https://user-images.githubusercontent.com/29673343/83503791-eb363e00-a4c3-11ea-8d4d-fd08c65e36d9.png)

**Comment by FlorentijnD** [comment]
Another question: I had a similar issue with numpy and fixed it by installing from source (.zip from PyPi's latest version) so I was wondering if there is a similar strategy I could use for tf lite interpreter only (so not the complete tf), in case installing the wheel fails

**Comment by terryheo** [comment]
You can use tflite literpreter with https://www.tensorflow.org/lite/guide/python which install tflite_runtime package.
I think you're using multiple Python versions. Two things worths to try.
1. Please don't use root account for your development. You'd better have a dev account.
2. In your dev account, try to use Python virtual environment to use a specific Python version. 
https://www.tensorflow.org/install/pip#2.-create-a-virtual-environment-recommended

**Comment by FlorentijnD** [comment]
Please refer to the original question. Trying to install the wheel from the first link in your comment fails:
![image](https://user-images.githubusercontent.com/29673343/83517458-3444bd00-a4d9-11ea-80d7-0f6793b65998.png)

**Comment by FlorentijnD** [comment]
Could it have anything to do with the `TAG_FP_ARCH` in the `_interpreter_wrapper.so`?
See the following screenshot when running the command `readelf -a _interpreter_wrapper.so | grep FP`:
![image](https://user-images.githubusercontent.com/29673343/83530234-bb9b2c00-a4eb-11ea-85f1-3c3f39def604.png)

**Comment by FlorentijnD** [comment]
I also tried other TF Lite interpreter wheels, which I found in this interesting repo: https://github.com/PINTO0309/TensorflowLite-bin, to no avail

**Comment by PINTO0309** [comment]
If using a cross-compiled installer does not solve the problem, you may have success with a native build on the Yocto environment. I've only used Yocto a couple of times to run Yocto on the RaspberryPi, so I don't know much about it.

**https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/make**

**https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/make/Makefile**

**Comment by terryheo** [comment]
@FlorentijnD could you share your ABI of target platform?
Maybe this will help.
```
readelf -A /bin/ls
```

**Comment by terryheo** [comment]
It could be better to have ELF header as well.

```
readelf -Ah /bin/ls
```

**Comment by FlorentijnD** [comment]
Thank you for your response @PINTO0309 . Making a Yocto recipe and deploying it that way is the end goal indeed! 
@terryheo This is the output of `readelf -Ah /bin/ls`: 
![image](https://user-images.githubusercontent.com/29673343/83609972-3d886500-a57f-11ea-9866-dfbef75dad6d.png)
Thank you as well for looking into this

**Comment by terryheo** [comment]
As you mentioned earlier, the VFP version looks suspicious. Current TFLite PIP wheel is built with VFPv4 while your target device uses VFPv3.
Actually, I'm developing a new PIP build method with Bazel. Could you try it?
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package#alternative-build-with-bazel-experimental

The following command builds new tflite wheel for VFPv3 under x86_64 workstation.
```
CI_DOCKER_EXTRA_PARAMS="-e CUSTOM_BAZEL_FLAGS=--copt=-mfpu=neon-vfpv3 -e CI_BUILD_PYTHON=python3 -e CROSSTOOL_PYTHON_INCLUDE_PATH=/usr/include/python3.6" \
tensorflow/tools/ci_build/ci_build.sh PI-PYTHON3 tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh armhf
```

You can find a generated ARM wheel under tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/dist/tflite_runtime-2.2.0-py3-none-linux_armv7l.whl

**Comment by FlorentijnD** [comment]
I will give it a try! Will get back to you asap. Do you know of TF Lite wheels that were built in the past that support VFPv3?

**Comment by terryheo** [comment]
I don't think so. The option has been used for long time.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/make/targets/rpi_makefile.inc#L11

**Comment by FlorentijnD** [comment]
Building the wheel seemed to work without issues. Installing the wheel didn't cause any trouble too. However, when importing the `tflite_runtime`, it goes wrong. See screenshot for the error.
![image](https://user-images.githubusercontent.com/29673343/83639462-05971700-a5ab-11ea-91cf-b6a312d237e2.png)

**Comment by FlorentijnD** [comment]
If this problem persists or not easy to overcome, would you know if the CPP TF Lite API would run into similar issues to to the mismatch of VFP versions?

**Comment by FlorentijnD** [comment]
Also, I was having the same issue with numpy, and was able to install numpy from source (https://files.pythonhosted.org/packages/2d/f3/795e50e3ea2dc7bc9d1a2eeea9997d5dce63b801e08dfc37c2efce341977/numpy-1.18.4.zip from https://pypi.org/project/numpy/#files). Would there be a similar strategy possible for tf lite runtime? (tensorflow itself is too big to host on the hardware)

**Comment by terryheo** [comment]
Yes, there might be a binary compatibility issue. Let's try it out. (I've searched flags for iMX6)
Here are some commands to try. Could you copy the output file (benchmark_model) to your target and check if it runs well or not?

```
$ bazel build --config=elinux_armhf tensorflow/lite/tools/benchmark:benchmark_model
$ bazel build --config=elinux_armhf --copt=-march=armv7-a --copt=-mfpu=vfpv3 tensorflow/lite/tools/benchmark:benchmark_model
$ bazel build --config=elinux_armhf --copt=-march=armv7-a --copt=-mfpu=vfpv3 --copt=-mfloat-abi=softfp tensorflow/lite/tools/benchmark:benchmark_model
$ bazel build --config=elinux_armhf --copt=-march=armv7-a --copt=-mcpu=cortex-a9 --copt=-mtune=cortex-a9 --copt=-mfpu=vfpv3 --copt=-mfloat-abi=softfp tensorflow/lite/tools/benchmark:benchmark_model
```
Or if you have CFLAGS for your Yocto project, you can also try it with "--copt" option and share the result.

**Comment by FlorentijnD** [comment]
After running `bazel build --config=elinux_armhf tensorflow/lite/tools/benchmark:benchmark_model` successfully I don't see any binary in the directory where I understand it should be in. ![image](https://user-images.githubusercontent.com/29673343/83752772-5bca8f80-a669-11ea-9f7a-9e31e4beac1c.png) What am I missing?

**Comment by FlorentijnD** [comment]
![image](https://user-images.githubusercontent.com/29673343/83753129-02af2b80-a66a-11ea-8802-e3fc4f704b19.png)
This is the output for the binary generated by `bazel build --config=elinux_armhf tensorflow/lite/tools/benchmark:benchmark_model`

**Comment by terryheo** [comment]
Can you share which glibc version do you available with the target?

```
ls -l /lib/arm-linux-gnueabihf/libc.so.6
```

The elinux_armhf is using this toolchain. https://github.com/tensorflow/tensorflow/tree/master/third_party/toolchains/embedded/arm-linux
I'm wondering if you can update your target glibc version.

**Comment by FlorentijnD** [comment]
![image](https://user-images.githubusercontent.com/29673343/83757835-61c46e80-a671-11ea-988b-d26d5cfd713e.png)

**Comment by FlorentijnD** [comment]
https://bin.entware.net/armv7sf-k3.2/ I found libc_2.27 here. I could try that? though I'm a little hesitatne because I'm not sure if that would break anything wrt my hardware

**Comment by terryheo** [comment]
Where did you get Yocto Linux for your i.MX6 Quad/DualLite? Doesn't NXP provide updated Linux release for your device?

**Comment by FlorentijnD** [comment]
By using that specific Yocto Linux, we managed to install the most lightweight option possible. To be fair, I was not involved in creating this particular Yocto image.

**Comment by terryheo** [comment]
I think you might be able to get updated Yocto release. In the meantime, I'll check if it's feasible to support libc-2.22.
BTW, if you can share where did you get your Yocto image, it'll be helpful for us to understand user's development environment.

**Comment by FlorentijnD** [comment]
I asked around. Your question is a little bit difficult to answer. `The hardware we're using is part of a bigger hardware component which acts as a custom board. That custom board is not really supported by NXP, and the current image is created using customized yocto layers, there are bits and pieces which are based on other similar boards and reused here.` Hope this helps in some way

**Comment by mhsmith** [comment]
The filename in the original report: is tagged `linux_armv71`. That's the number 1, not the letter L as it should be. How did that happen?

**Comment by mohantym** [comment]
Hi @FlorentijnD ! 
We are checking to see whether you still need help in this issue . Have you tried with root access , latest pip  and Tensorflow version after installing the dependencies ? Attaching relevant threads for reference.[1](https://www.tensorflow.org/lite/guide/build_cmake_arm), [2 ](https://github.com/PINTO0309/Tensorflow-bin)

**Comment by FlorentijnD** [comment]
Hi @mohantym. Thanks for following up on this. I don't neet help anymore with this issue as I don't have access to the hardware that originally caused the issue to arise.
