### ISSUE TITLE
AttributeError: module 'tensorflow.python.keras.api._v2.keras.preprocessing.text' has no attribute 'text_dataset_from_directory'

### ISSUE THREAD

**Issue by Harish2104** [tensorflow/tensorflow#39955]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Using example code from tensorflow
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: On computer
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.2
- Python version:3.8.2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:Not installed
- GPU model and memory:No GPU

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

GIT Version:
v2.2.0-rc4-8-g2b96f3662b 2.2.0

**Describe the current behavior**
Unable Unable to load the function text_dataset_from_directory. I have installed tensorflow 2.2 and keras. I am not sure if any api is called from the installed package.
I installed tf - nightly as well, but still unable to resolve the issue. I am not sure if am missing anything. Please help me on this.

**Describe the expected behavior**
All functions has to work.
**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
![image](https://user-images.githubusercontent.com/7239271/83170984-00614480-a133-11ea-964e-021faa011e9d.png)

**Comment by ravikyram** [comment]
@Harish2104 

Can you please go through the [link](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/text_dataset_from_directory) and see if it helps you.Request you to share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by mujiatong** [comment]
Hi There,

I also meet this problem the same as @Harish2104.  And my Python version is 3.7,7, Tensorfow is 2.2.0

**AttributeError: module 'tensorflow.keras.preprocessing' has no attribute 'text_dataset_from_directory'**

Please give help and give advice if you know how to resolve it.
Many thanks.

![image](https://user-images.githubusercontent.com/329152/85943225-46433f80-b961-11ea-9b60-6eef8ca5e529.png)
![image](https://user-images.githubusercontent.com/329152/85943253-8a364480-b961-11ea-81ab-5d165c1ee0a1.png)

**Comment by Harish2104** [comment]
My problem is also not resolved yet. I am also not able get these functions

**Comment by RutujaWanjari** [comment]
Facing exactly same problem

**Comment by HarshVardhanSh** [comment]
@Harish2104 @RutujaWanjari @mujiatong This api is only available with tf-nightly. Please install tf-nightly before using this api.

**Comment by GF-Huang** [comment]
> @Harish2104 @RutujaWanjari @mujiatong This api is only available with tf-nightly. Please install tf-nightly before using this api. Read the doc [here](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/text_dataset_from_directory)

You tell me only available with tf-nightly?

![image](https://user-images.githubusercontent.com/4510984/98586322-84833f00-2303-11eb-8c21-afe3e24fe1df.png)
