### ISSUE TITLE
how to check quantization method applied

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#39959]
how do I check what quantization specification has been applied to model (TensorFlow quantized format)?
I'd like to know what
- Dynamic range quantization, Full integer quantization, Float16 quantization,etc...
- Symmetric vs asymmetric
- Per-axis vs per-tensor
- Signed integer vs unsigned integer
- etc..

Thank you

**Comment by ymodak** [comment]
You can use TensorBoard to load your TF model and explore [op-level graph](https://www.tensorflow.org/tensorboard/graphs#op-level_graph) to examine the node properties.
Another way is to visualize your model using [netron](https://github.com/lutzroeder/netron).

**Comment by peter197321** [comment]
can you please give some visual examples of what exactly you mean - how to check it?
