### ISSUE TITLE
Fix CMake build due to cuda_configure changes

### ISSUE THREAD

**Issue by davidzchen** [tensorflow/tensorflow#3996]
The new changes from #3269 broke the CMake build due to the header include path changes and the new `cuda_config.h` file generated by `cuda_configure`.

**Comment by mrry** [comment]
This is now fixed, thanks to @guschmue's great work on the Windows GPU build. There are still some wrinkles regarding CMake-on-Linux (see #5465), but I'm going to close this issue for now.

**Comment by davidzchen** [comment]
Thanks for fixing this, @guschmue!
