### ISSUE TITLE
Error when using Class_Weight in Keras for binary classification

### ISSUE THREAD

**Issue by xxanissarxx** [tensorflow/tensorflow#39963]
Here is the model summary: 
```
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv1d (Conv1D)              (None, 35, 32)            96        
_________________________________________________________________
batch_normalization (BatchNo (None, 35, 32)            128       
_________________________________________________________________
dropout (Dropout)            (None, 35, 32)            0         
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 34, 64)            4160      
_________________________________________________________________
batch_normalization_1 (Batch (None, 34, 64)            256       
_________________________________________________________________
dropout_1 (Dropout)          (None, 34, 64)            0         
_________________________________________________________________
flatten (Flatten)            (None, 2176)              0         
_________________________________________________________________
dense (Dense)                (None, 64)                139328    
_________________________________________________________________
dropout_2 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 65        
=================================================================
Total params: 144,033
Trainable params: 143,841
Non-trainable params: 192
```
Here is the error message:

```
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-14-09a8a255f317> in <module>()
----> 1 history = model.fit(X_Train,Y_Train, epochs = epochs, validation_data =(X_Test,Y_Test), verbose=1,class_weight=class_weights1)

8 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  indices[31] = -9223372036854775808 is not in [0, 2)
     [[{{node GatherV2}}]]
     [[IteratorGetNext]]
     [[IteratorGetNext/_2]]
  (1) Invalid argument:  indices[31] = -9223372036854775808 is not in [0, 2)
     [[{{node GatherV2}}]]
     [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_6381]

Function call stack:
train_function -> train_function
```
Somehow I'm getting a massive negative number? My dataset is all percentile data so numbers between 0 and 1.

Also here is the code to set up the model:
```
class_weights1 = {0: 1., 1: 50.}

epochs = 1
model = Sequential()
model.add(Conv1D(filters = 32, kernel_size = 2, activation='relu',input_shape=(36,1)))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Conv1D(filters = 64, kernel_size = 2, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(1,activation='sigmoid'))
```
And then the code to compile and run it:
```
model.compile(optimizer=Adam(lr=0.005),loss='binary_crossentropy',metrics=['accuracy'])

history = model.fit(X_Train,Y_Train, epochs = epochs, validation_data =(X_Test,Y_Test), verbose=1,class_weight=class_weights1)
```
I know this is a problem with my class_weight because when I remove it, everything works (but the model is terrible because the data is imbalanced and I need to increase the weight of the minority class to adjust for this).

**Comment by ravikyram** [comment]
@xxanissarxx 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

Request you to share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by rameezvora** [comment]
Hi I'm having the same issue. My model was working fine with class_weight while using tf 1.15 .  But with the new version It fails when I add class_weight

`Model: "sequential_1"
_______________________________________________________________________________________________________
Layer (type)                                  Output Shape                             Param #         
=======================================================================================================
dense_1 (Dense)                               (None, 2525)                             24699550        
=======================================================================================================
Total params: 24,699,550
Trainable params: 24,699,550
Non-trainable params: 0
_______________________________________________________________________________________________________
Epoch 1/2`

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Can not squeeze dim[0], expected a dimension of 1, got 512
	 [[{{node loss_5/dense_1_loss/weighted_loss/Squeeze}}]]
	 [[metrics_5/accuracy/Identity/_153]]
  (1) Invalid argument: Can not squeeze dim[0], expected a dimension of 1, got 512
	 [[{{node loss_5/dense_1_loss/weighted_loss/Squeeze}}]]
0 successful operations.
0 derived errors ignored.

Detailed traceback: 
  File "C:\Users\installer.CTNAD00MJ06SCHM\Documents\.conda\envs\r2\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1297, in fit_generator
    steps_name='steps_per_epoch')
  File "C:\Users\installer.CTNAD00MJ06SCHM\Documents\.conda\envs\r2\lib\site-packages\tensorflow_core\python\keras\engine\training_generator.py", line 265, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "C:\Users\installer.CTNAD00MJ06SCHM\Documents\.conda\envs\r2\lib\site-packages\tensorflow_core\python\keras\engine\training.py",

I'm using windows environment and tensorflow version is 2.0
> tensorflow::tf_version()
[1] ‘2.0’

**Comment by YokoHono** [comment]
Has anybody solved this issue? Or found a workaround?
