### ISSUE TITLE
map the input image path dataset. 

### ISSUE THREAD

**Issue by SlowMonk** [tensorflow/tensorflow#39977]
```
 images,boxes,labels,difficulties= PascalVOCDataset()
 dataset = tf.data.Dataset.from_tensor_slices((images)).shuffle(100).batch(2)

tf.Tensor(b'/media/jake/mark-4tb3/input/datasets/pascal/VOCtrainval_11-May-2012/VOCdevkit/VOC2012/JPEGImages/2008_000199.jpg', shape=(), dtype=string) tf.Tensor(b'/media/jake/mark-4tb3/input/datasets/pascal/VOCtrainval_11-May-2012/VOCdevkit/VOC2012/JPEGImages/2008_000187.jpg', shape=(), dtype=string)

```
This will return the images, boxes with

I want to map this file path to the real image path 

```
def func2(image,bbox):
    print('func2')
    print('dataset->',image)
    images = np.array(image)
    newSize = [300, 300]
    if isprint: print('image_A->', images[0].decode("utf-8"))
    image = cv2.imread(images[0].decode("utf-8"))
    if isprint: print(image.shape)
    image = np.array(image)
    scale_x = newSize[0] / image.shape[1]
    scale_y = newSize[1] / image.shape[0]
    image = cv2.resize(image, (newSize[0], newSize[1]))
    return tf.convert_to_tensor(image, dtype=tf.uint8), bbox
def fast_benchmark(dataset, num_epochs=2):
    start_time = time.perf_counter()
    for _ in tf.data.Dataset.range(num_epochs):
        for _ in dataset:
            pass
    tf.print("실행 시간:", time.perf_counter() - start_time)

fast_benchmark(dataset.map(func2).batch(1).prefetch(tf.data.experimental.AUTOTUNE))
```

**NotImplementedError: in converted code:
    relative to /home/jake:

    Gits/ssd_tensorflow/train.py:46 func2  *
        images = np.array(image)
    venv/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py:396 converted_call
        return py_builtins.overload_of(f)(*args)
    venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:736 __array__
        " array.".format(self.name))

    NotImplementedError: Cannot convert a symbolic Tensor (args_0:0) to a numpy array.

func2
dataset-> Tensor("args_0:0", shape=(), dtype=string)

Process finished with exit code 1**

**Comment by ravikyram** [comment]
@SlowMonk 
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!
