### ISSUE TITLE
Unable to use tfp.optimizer.lbfgs_minimize, error after 2 iterations

### ISSUE THREAD

**Issue by prathak** [tensorflow/tensorflow#39970]
Hi I am unable to use tfp.optimizer.lbfgs_minimize, following the tutorial on https://www.tensorflow.org/probability/examples/Optimizers_in_TensorFlow_Probability.

Similar to https://github.com/tensorflow/probability/issues/398,

I am facing error "Inputs to operation Select of type Select must have the same size and shape.  Input 0: [110] != input 1: [1] [Op:Select]"

I noticed that when my cost function if of shape (1,) and my gradient of shape (x,1) it says x!=1
But what I don't understand is why does my cost function need to be of shape(x,1)? When I add a placeholder return which returns shape (x,1) for cost value as well, it runs.  

![image](https://user-images.githubusercontent.com/7682371/83195374-09054b00-a132-11ea-8b56-f353f89b54a7.png)

**Comment by Saduf2019** [comment]
@prathak 
Please share a simple stand alone code along with tensor flow version for us to replicate the issue faced.
