### ISSUE TITLE
dataset.from_generator error with multiple inputs

### ISSUE THREAD

**Issue by sun-peach** [tensorflow/tensorflow#39973]
**System information**
- no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): tensorflow-2.1.0 (cpu)
- Python version: 3.7

**Describe the current behavior**
I use tf.keras.Model to build up a model. It has multiple inputs, say input is like `[i_1, i_2, i_3, a_1]`, output is only one, say `y`.
I have a generator function
```
def gen():
    for i in range(data_length):
        ...
        yield [i_1, i_2, i_3, a_1], y
```
Notice that the inputs have variable sizes. Then I have the dataset built as:
`ds = tf.data.dataset.from_generator(gen, output_type=(tf.float32,tf.float32, tf.float32, tf.float32, tf.int8))`
when I send the ds to model.fit, it shows the error `map_fn() takes from 1 to 3 positional arguments but 5 were given`

Then I tried 
`ds = tf.data.dataset.from_generator(gen, output_type=([tf.float32,tf.float32, tf.float32, tf.float32], tf.int8))`
and 
`ds = tf.data.dataset.from_generator(gen, output_type=((tf.float32,tf.float32, tf.float32, tf.float32), tf.int8))`
Both of them show errors. How should make the from_generator take multiple inputs?

Thank you!

**Comment by ravikyram** [comment]
@sun-peach 

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!
