### ISSUE TITLE
RandomContrast Layer - confusing __init__ error message

### ISSUE THREAD

**Issue by gnovack** [tensorflow/tensorflow#39976]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installed from (source or binary): Colab
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6.9

**Describe the current behavior**
When instantiating a RandomContrast layer object with a value > 1. (e.g. 2) for the `Factor` parameter, a `ValueError` is raised with the following error message which is somewhat confusing in this scenario: 'Factor cannot have negative values, got 2'

**Describe the expected behavior**
A `ValueError` should be raised with a more appropriate error message, something like: 'Factor cannot be greater than 1, got 2'

**Standalone code to reproduce the issue**
```python
random_contrast_layer = tf.keras.layers.experimental.preprocessing.RandomContrast(2)
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/46ccdd512567b0dd3cf99a9548aead9c/39976.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/54056391942fbc1344d936558161b88f/39976-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by jvishnuvardhan** [comment]
@gnovack Thanks for reporting this issue. The RandomContrast layer looks for two element factor (lower_bound, upper_bound) or single element where the factor should be between 0 and 1. 

The error message is improved. Please take a look at the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/6df7f036a25ff296903e9a74febc7e4e/39976-tf-nightly.ipynb). Thanks!

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by gnovack** [comment]
Looks great. Thanks @jvishnuvardhan
