### ISSUE TITLE
Can't use Keras with GPU (Tensorflow-gpu==1.15)

### ISSUE THREAD

**Issue by ChungNPH** [tensorflow/tensorflow#39972]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.4 LTS
- TensorFlow installed from (source or binary): source
- TensorFlow version: tensorflow-gpu==1.15
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: CUDA Version: 10.1 
- GPU model and memory: GeForce RTX 2080 Ti/PCIe/SSE2

Hi guys, I'm installed tensorflow-gpu 1.15 and Keras 2.1.4. 
When i run: 

sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

Return:
Device mapping:
/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:0 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:1 -> device: XLA_GPU device

But when i run:

K.tensorflow_backend._get_available_gpus()

Return []

And when i train model it don't use gpu. But if i install tensorflow-gpu 2.2, model was trained by GPU on keras.

How can i use GPU on Keras with tensorflow-gpu 1.15? Thank you so much !

**Comment by ChungNPH** [comment]
Hi @amahendrakar , i created a new env and installed tensorflow-gpu 1.15 and keras, but i still face this issue. :(

**Comment by ChungNPH** [comment]
Package              Version            
-------------------- -------------------
absl-py              0.9.0              
astor                0.8.1              
backcall             0.1.0              
certifi              2020.4.5.1         
decorator            4.4.2              
entrypoints          0.3                
gast                 0.2.2              
google-pasta         0.2.0              
grpcio               1.29.0             
h5py                 2.10.0             
importlib-metadata   1.6.0              
ipykernel            5.1.4              
ipython              7.13.0             
ipython-genutils     0.2.0              
jedi                 0.17.0             
jupyter-client       6.1.3              
jupyter-core         4.6.3              
Keras                2.3.1              
Keras-Applications   1.0.8              
Keras-Preprocessing  1.1.2              
Markdown             3.2.2              
numpy                1.18.4             
opt-einsum           3.2.1              
parso                0.7.0              
pexpect              4.8.0              
pickleshare          0.7.5              
pip                  20.0.2             
prompt-toolkit       3.0.4              
protobuf             3.12.2             
ptyprocess           0.6.0              
Pygments             2.6.1              
python-dateutil      2.8.1              
PyYAML               5.3.1              
pyzmq                18.1.1             
scipy                1.4.1              
setuptools           46.4.0.post20200518
six                  1.15.0             
tensorboard          1.15.0             
tensorflow-estimator 1.15.1             
tensorflow-gpu       1.15.0             
termcolor            1.1.0              
tornado              6.0.4              
traitlets            4.3.3              
wcwidth              0.1.9              
Werkzeug             1.0.1              
wheel                0.34.2             
wrapt                1.12.1             
zipp                 3.1.0  

here's my pip list

**Comment by jvishnuvardhan** [comment]
@ChungNPH I think there is a mismatch in the CUDA version. `TF1.15` requires `_DEFAULT_CUDA_VERSION = '10'` but you have 10.1 version. Can you please try to uninstall 10.1 and install 10 and then install `TF1.15-gpu`. 

`TF2.2` is working because it is satisfying the CUDA version requirement which is 10.1. Thanks!

Please feel free to close if this was resolved for you. Thanks!

**Comment by ChungNPH** [comment]
Thank you so much, i will try.
