### ISSUE TITLE
micro_speech example broken

### ISSUE THREAD

**Issue by leocorne** [tensorflow/tensorflow#39979]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Embedded device: Arduino Nano 33 BLE Sense (IDE 1.8.12)
- TensorFlow installed from (source or binary): Source (latest version)

**Describe the current behavior**
This issue is regarding TensorFlow Lite for Microcontrollers. The micro_speech example is not working (it doesn't detect any words) or even "unknown" tags.

**Standalone code to reproduce the issue**
The only thing I am using is the example as given in the GitHub (with the pretrained model)

**Other info / logs** 
Tried debugging a bit, but didn't get too far. It seems to be some problem with the RecognizeCommands file.

**Comment by leocorne** [comment]
I did some more digging around. It seems the inference is taking too long (about 1.9 seconds for every 1 second of recording), which doesn't allow the model to run properly. Is there any way to fix this?

**Comment by leocorne** [comment]
This is a different issue. All the tests pass on my laptop. The problem happens when running inference on the Arduino board itself. It seems the inference is taking around 2 seconds which breaks the command detection.

**Comment by wangtz** [comment]
@leocorne I'm surprised that the inference takes 2s. Could you try with the latest TF lib in Arduino? The latest version is leveraging optimized kernel from Arm so presumably it should be much faster.
