### ISSUE TITLE
Setuptools 40.0.0 is incompatible

### ISSUE THREAD

**Issue by AayushN01** [tensorflow/tensorflow#39974]
Does this error affect  tensorflow while executing it as import tensorflow as tf?

![Screenshot (5)](https://user-images.githubusercontent.com/25500477/83214482-67f3b000-a184-11ea-89ce-41725b15b702.png)

**Comment by Saduf2019** [comment]
@AayushN01
Please run a simple stand alone code and share the error in case you face any.
