### ISSUE TITLE
tf.math.maximum example is written incorrectly.

### ISSUE THREAD

**Issue by abhinavsp0730** [tensorflow/tensorflow#39981]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/math/maximum#returns

## Description of issue (what needs changing):

The example of tf.math.maximum is not written correctly.
It's written in this manner,
Example: 
``` x = tf.constant([0., 0., 0., 0.]) y = tf.constant([-2., 0., 2., 5.]) tf.math.maximum(x, y) ```
Instead of this it should've written in this manner,
``` 
    x = tf.constant([0., 0., 0., 0.])
    y = tf.constant([-2., 0., 2., 5.])
    tf.math.maximum(x, y)
    -> tf.Tensor([0. 0. 2. 5.], shape=(4,), dtype=float32)
```    

### Submit a pull request?
no

**Comment by kandekar007** [comment]
I would like to work on this issue.

**Comment by rohan100jain** [comment]
Thanks! Feel free to submit a PR

**Comment by paulis-reece** [comment]
Can I work on this issue?

**Comment by Satist** [comment]
I can fix this, can i work on the issue?

**Comment by aavishkarmishra** [comment]
@r-barnes @Saduf2019 Can I work on this issue ??

**Comment by r-barnes** [comment]
I don't have the authority to assign fix responsibility here.

**Comment by mihaimaruseac** [comment]
@paulis-reece @Satist @aavishkarmishra @kandekar007 

First one to land the PR fixing the issue wins. There is no one assigning issues to contributors.

**Comment by abhinavsp0730** [comment]
But, where to send the PR(repo) ?

**Comment by mihaimaruseac** [comment]
This repo.

**Comment by aavishkarmishra** [comment]
@mihaimaruseac  Hi can anyone help me to locate these files in  repo , as in docs folder there is readme that tell to locate them in docs repo and in docs repo there are links which just open the web page

**Comment by mihaimaruseac** [comment]
https://cs.opensource.google/search?q=tf.math.maximum&ss=tensorflow%2Ftensorflow:tensorflow%2F&ssfr=1

**Comment by aavishkarmishra** [comment]
@mihaimaruseac why this is not updated in main website ?

**Comment by mihaimaruseac** [comment]
@yashk2810 @lamberta Was the nightly not regenerated for this symbol? Or maybe the PR was not a fully working solution?

**Comment by yashk2810** [comment]
When did that go into tf-nightly?

**Comment by aavishkarmishra** [comment]
How this can be resolved ?

**Comment by aavishkarmishra** [comment]
How to resolve this problem anyone have any idea ?

**Comment by yashk2810** [comment]
> resolve this problem

I am working on that :)

**Comment by mihaimaruseac** [comment]
> When did that go into tf-nightly?

Should be 5 day ago, 1e2bf4efce13b0fd3875d3f431ba699665392cc2 (318509604)

**Comment by yashk2810** [comment]
Ahh.. I see the problem. There should be a newline after `Example:`. All doctests should have a newline before and after. Once that's fixed, it'll start appearing on the website.

**Comment by yashk2810** [comment]
I just submitted a fix for this. This should go live tomorrow or day-after-tomorrow whenever the change makes it to nightly.

**Comment by aavishkarmishra** [comment]
### Do we have to force line chage wherever we want a new line?

>As in case of markdown it changes line normally we don't have to force it(without using double space).

**Comment by yashk2810** [comment]
A new line is necessary because we do some regex matching to add stuff around it to display it on the site.
