### ISSUE TITLE
Conv3D operations are not using tensor cores with mixed float16 policy

### ISSUE THREAD

**Issue by Svdvoort** [tensorflow/tensorflow#39985]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **CentOS 7**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary): **pip package**
- TensorFlow version (use command below): **v2.2.0-rc4-8-g2b96f3662b 2.2.0**
- Python version: **3.7.4**
- Bazel version (if compiling from source): **N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **10.1/7.6.4**
- GPU model and memory: **RTX2080TI**

**Describe the current behavior**

When using Conv3D layers and a mixed float16 policy the Conv3D layers do not use tensor cores.
Using the same settings for a Conv2D layer does result in the Conv2D layers using the tensor cores.
The [description here](https://www.tensorflow.org/guide/keras/mixed_precision#ensuring_gpu_tensor_cores_are_used) also suggests that Conv3D layers should work with tensor cores

**Describe the expected behavior**

For Conv3D layers to use tensor cores

**Standalone code to reproduce the issue**

Google colab [available here](https://colab.research.google.com/drive/1PKMPvKNe-dk79BjyPK_7N0F_JBoYM9x1?usp=sharing)

**Other info / logs** 

Perhaps related to  #33672, but following the instructions given there (setting the environment variables) does not solve the problem.

**Comment by Saduf2019** [comment]
i am able to replicate the issue, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/9ed522f57b0f8f679cd4a114511e6476/untitled199.ipynb)

**Comment by reedwm** [comment]
In this case, using tensor cores is actually slower, so TensorFlow chooses not to use them. But I cannot figure out why tensor cores are slower. 

@nluehr can you take a look? Here is a smaller program to reproduce:

```python
import tensorflow as tf

x = tf.random.normal((64, 100, 100, 1, 48), dtype=tf.float16)
f = tf.random.normal((7, 7, 1, 48, 48), dtype=tf.float16)
y = tf.nn.conv3d(x, f, strides=[1, 3, 3, 1, 1], padding='SAME')

x = tf.random.normal((64, 100, 100,  48), dtype=tf.float16)
f = tf.random.normal((7, 7, 48, 48), dtype=tf.float16)
y = tf.nn.conv2d(x, f, strides=[1, 3, 3, 1], padding='SAME')
```

This program runs a Conv3D op and the equivalent Conv2D op. You can see the autorune result with:

```bash
TF_CPP_VMODULE=logger=2  python conv3d.py
```

The last two log lines will show the autotune results for Conv3D and Conv2D. On my machine, I get

```
2020-06-01 14:56:59.932860: I tensorflow/core/platform/logger.cc:29] [type.googleapis.com/tensorflow.AutotuningLog] { instr { [type.googleapis.com/tensorflow.ConvolutionProto] { kind: FORWARD input { dimensions: 64 dimensions: 48 dimensions: 100 dimensions: 100 dimensions: 1 data_type: kHalf data_layout: kBatchDepthYX } filter { dimensions: 48 dimensions: 48 dimensions: 7 dimensions: 7 dimensions: 1 data_type: kHalf filter_layout: kOutputInputYX } output { dimensions: 64 dimensions: 48 dimensions: 34 dimensions: 34 dimensions: 1 data_type: kHalf data_layout: kBatchDepthYX } conv_desc { paddings: 3 paddings: 3 paddings: 0 strides: 3 strides: 3 strides: 1 dilations: 1 dilations: 1 dilations: 1 group_count: 1 } conv_scale: 1 input_address: 140238394066432 filter_address: 140238332626176 output_address: 140238340406016 } } results { conv { algorithm: 1 tensor_ops_enabled: true } run_time { nanos: 4273632 } } results { conv { algorithm: 1 } run_time { nanos: 4330207 } } results { conv { tensor_ops_enabled: true } run_time { nanos: 4163392 } } results { conv { } run_time { nanos: 4225760 } } cudnn_version { major: 7 minor: 6 patch: 3 } compute_capability { major: 7 } device_pci_bus_id: "0000:03:00.0" blas_version: "10201" }
2020-06-01 14:56:59.953838: I tensorflow/core/platform/logger.cc:29] [type.googleapis.com/tensorflow.AutotuningLog] { instr { [type.googleapis.com/tensorflow.ConvolutionProto] { kind: FORWARD input { dimensions: 64 dimensions: 48 dimensions: 100 dimensions: 100 data_type: kHalf data_layout: kBatchYXDepth } filter { dimensions: 48 dimensions: 48 dimensions: 7 dimensions: 7 data_type: kHalf filter_layout: kOutputYXInput } output { dimensions: 64 dimensions: 48 dimensions: 34 dimensions: 34 data_type: kHalf data_layout: kBatchYXDepth } conv_desc { paddings: 3 paddings: 3 strides: 3 strides: 3 dilations: 1 dilations: 1 group_count: 1 } conv_scale: 1 input_address: 140238578386688 filter_address: 140238332626176 output_address: 140238356122880 } } results { conv { algorithm: 1 tensor_ops_enabled: true } scratch_bytes: 6944 run_time { nanos: 924800 } } results { conv { algorithm: 1 } scratch_bytes: 9408 run_time { nanos: 4439904 } } results { conv { tensor_ops_enabled: true } run_time { nanos: 4379072 } } results { conv { } run_time { nanos: 4407936 } } cudnn_version { major: 7 minor: 6 patch: 3 } compute_capability { major: 7 } device_pci_bus_id: "0000:03:00.0" blas_version: "10201" }
```

Unfortunately, the autorune results are difficult to read. You can see the performance by searching for the string "nanos:", and look a bit to the left for "tensor_ops_enabled:". For Conv3D, tensor ops make it a little bit slower (4,273,632 vs 4,163,392). But for Conv2D, tensor ops makes it a lot faster (924,800 vs 4,439,904)

**Comment by kaixih** [comment]
Yes, I can repro it.

I checked the kernels used by cuDNN for this particular case, and we don't have tensor core implementation supported in cuDNN v7.6. And that is why you might see the similar perf for conv3d whether using tensor core or not.

However, for the coming cuDNN v8, this case should be improved by using tensor core.

**Comment by Svdvoort** [comment]
From #33672 and the release notes of cuDNN I thought that it might be possible with cuDNN versions >= 7.6.2, but this is not the case? Or in order for that to work should tensorflow be compiled manually?

**Comment by Svdvoort** [comment]
@kaixih  I've compiled the latest TensorFlow master with cudnn 8, but unfortunately, the results remain the same. I had a look at the suggestions by NVidia [to get tensor cores working](https://docs.nvidia.com/deeplearning/sdk/cudnn-best-practices/index.html#cudnn-8xx), but unfortunately that didn't help.

Code:

```
import tensorflow as tf

print("3D")
x = tf.random.normal((16, 16, 32, 32, 32), dtype=tf.float16)
f = tf.random.normal((3, 3, 3, 16, 16), dtype=tf.float16)
y = tf.nn.conv3d(x, f, strides=[1, 1, 1, 1, 1], padding='SAME', data_format="NCDHW")

print("2D")
x = tf.random.normal((16, 16, 32, 32), dtype=tf.float16)
f = tf.random.normal((3, 3, 16, 16), dtype=tf.float16)
y = tf.nn.conv2d(x, f, strides=[1, 1, 1, 1], padding='SAME', data_format="NCHW")
```

Results:

```
3D
{ instr { [type.googleapis.com/tensorflow.ConvolutionProto] { kind: FORWARD input { dimensions: 16 dimensions: 16 dimensions: 32 dimensions: 32 dimensions: 32 data_type: kHalf data_layout: kBatchDepthYX } filter { dimensions: 16 dimensions: 16 dimensions: 3 dimensions: 3 dimensions: 3 data_type: kHalf filter_layout: kOutputInputYX } output { dimensions: 16 dimensions: 16 dimensions: 32 dimensions: 32 dimensions: 32 data_type: kHalf data_layout: kBatchDepthYX } conv_desc { paddings: 1 paddings: 1 paddings: 1 strides: 1 strides: 1 strides: 1 dilations: 1 dilations: 1 dilations: 1 group_count: 1 } conv_scale: 1 input_address: 46931141200128 filter_address: 46931107645184 output_address: 46931157977344 } } results { conv { algorithm: 1 tensor_ops_enabled: true } scratch_bytes: 33568272 run_time { nanos: 375297515 } } results { conv { algorithm: 1 } run_time { nanos: 2891584 } } results { conv { tensor_ops_enabled: true } run_time { nanos: 2803744 } } results { conv { } run_time { nanos: 2801280 } } results { conv { algorithm: 5 tensor_ops_enabled: true } scratch_bytes: 28311552 run_time { nanos: 3459968 } } results { conv { algorithm: 5 } scratch_bytes: 28311552 run_time { nanos: 3524576 } } cudnn_version { major: 8 } compute_capability { major: 7 minor: 5 } device_pci_bus_id: "0000:04:00.0" blas_version: "10202" }

2D
{ instr { [type.googleapis.com/tensorflow.ConvolutionProto] { kind: FORWARD input { dimensions: 16 dimensions: 16 dimensions: 32 dimensions: 32 data_type: kHalf data_layout: kBatchDepthYX } filter { dimensions: 16 dimensions: 16 dimensions: 3 dimensions: 3 data_type: kHalf filter_layout: kOutputInputYX } output { dimensions: 16 dimensions: 16 dimensions: 32 dimensions: 32 data_type: kHalf data_layout: kBatchDepthYX } conv_desc { paddings: 1 paddings: 1 strides: 1 strides: 1 dilations: 1 dilations: 1 group_count: 1 } conv_scale: 1 input_address: 46931108735232 filter_address: 46931107645184 output_address: 46931183143168 } } results { conv { algorithm: 1 tensor_ops_enabled: true } run_time { nanos: 45568 } } results { conv { algorithm: 1 } run_time { nanos: 56736 } } results { conv { tensor_ops_enabled: true } run_time { nanos: 54112 } } results { conv { } run_time { nanos: 50304 } } results { conv { algorithm: 2 tensor_ops_enabled: true } scratch_bytes: 4718592 run_time { nanos: 76416 } } results { conv { algorithm: 2 } scratch_bytes: 4718592 run_time { nanos: 76416 } } results { conv { algorithm: 4 tensor_ops_enabled: true } scratch_bytes: 17310720 run_time { nanos: 156704 } } results { conv { algorithm: 4 } scratch_bytes: 17310720 run_time { nanos: 142528 } } results { conv { algorithm: 6 tensor_ops_enabled: true } scratch_bytes: 2148432 run_time { nanos: 75712 } } results { conv { algorithm: 6 } scratch_bytes: 2148432 run_time { nanos: 58528 } } results { conv { algorithm: 5 tensor_ops_enabled: true } scratch_bytes: 5570560 run_time { nanos: 150080 } } results { conv { algorithm: 5 } scratch_bytes: 5570560 run_time { nanos: 116672 } } results { conv { algorithm: 7 tensor_ops_enabled: true } scratch_bytes: 4755456 run_time { nanos: 53024 } } results { conv { algorithm: 7 } scratch_bytes: 4755456 run_time { nanos: 42880 } } cudnn_version { major: 8 } compute_capability { major: 7 minor: 5 } device_pci_bus_id: "0000:04:00.0" blas_version: "10202" }
```

Once again for the 2D convolution, the time is reduced, but not for the 3D convolutions. Cudnn 8 is used as seen in the output. Is there still something I'm missing?

**Comment by kaixih** [comment]
@Svdvoort Just recompiling the TF with cuDNN v8 might not be enough. The TF actually convert all NDHWC to NCDHW before call the cuDNN. So, we also need to remove that logic. We are working on this now.

**Comment by kaixih** [comment]
FYI. You might want to keep track of status here: https://github.com/tensorflow/tensorflow/pull/40399

**Comment by Svdvoort** [comment]
Thanks for the info. I assumed setting the data format explicitly would force TF to use it with cuDNN. I'll await the pull request then.

**Comment by Svdvoort** [comment]
Can confirm that with the newest TF 2.3.0-rc0 (compiled with Cuda 11 and CuDNN 8.0.1) the Conv3D now works with tensor cores. 
For example:

```
import tensorflow as tf

N_filters_in = 256
N_filters_out = 256
batch_size = 16
image_size = 50
kernel_size = 3

print("3D")
x = tf.random.normal((batch_size, image_size, image_size, image_size, N_filters_in), dtype=tf.float16)
f = tf.random.normal((kernel_size, kernel_size, kernel_size, N_filters_in, N_filters_out), dtype=tf.float16)
y = tf.nn.conv3d(x, f, strides=[1, 1, 1, 1, 1], padding='SAME')
```

Running with `TF_CPP_VMODULE=logger=2` gives:

```
{ instr { [type.googleapis.com/tensorflow.ConvolutionProto] { kind: FORWARD input { dimensions: 16 dimensions: 256 dimensions: 50 dimensions: 50 dimensions: 50 data_type: kHalf data_layout: kBatchYXDepth } filter { dimensions: 256 dimensions: 256 dimensions: 3 dimensions: 3 dimensions: 3 data_type: kHalf filter_layout: kOutputYXInput } output { dimensions: 16 dimensions: 256 dimensions: 50 dimensions: 50 dimensions: 50 data_type: kHalf data_layout: kBatchYXDepth } conv_desc { paddings: 1 paddings: 1 paddings: 1 strides: 1 strides: 1 strides: 1 dilations: 1 dilations: 1 dilations: 1 group_count: 1 } conv_scale: 1 input_address: 46933021427456 filter_address: 46930973426944 output_address: 46931997427200 } } results { conv { algorithm: 1 tensor_ops_enabled: true } run_time { nanos: 561604370 } } results { conv { algorithm: 1 } scratch_bytes: 3538960 run_time { nanos: 837961303 } } cudnn_version { major: 8 patch: 1 } compute_capability { major: 7 minor: 5 } device_pci_bus_id: "0000:04:00.0" blas_version: "11000" }
```

So a speed-up from 837961303 to 561604370 when using tensor cores.
When using such a convolutional layer as part of a model tensorboard also reports the use of the tensor cores.

However, according to the [NVidia guidelines](https://docs.nvidia.com/deeplearning/sdk/cudnn-best-practices/index.html#cudnn-8xx), the following should also work:

```
import tensorflow as tf

N_filters_in = 128
N_filters_out = 128
batch_size = 16
image_size = 50
kernel_size = 3

print("3D")
x = tf.random.normal((batch_size, image_size, image_size, image_size, N_filters_in), dtype=tf.float16)
f = tf.random.normal((kernel_size, kernel_size, kernel_size, N_filters_in, N_filters_out), dtype=tf.float16)
y = tf.nn.conv3d(x, f, strides=[1, 1, 1, 1, 1], padding='SAME')
```

However, this returns: 

```
{ instr { [type.googleapis.com/tensorflow.ConvolutionProto] { kind: FORWARD input { dimensions: 16 dimensions: 128 dimensions: 50 dimensions: 50 dimensions: 50 data_type: kHalf data_layout: kBatchYXDepth } filter { dimensions: 128 dimensions: 128 dimensions: 3 dimensions: 3 dimensions: 3 data_type: kHalf filter_layout: kOutputYXInput } output { dimensions: 16 dimensions: 128 dimensions: 50 dimensions: 50 dimensions: 50 data_type: kHalf data_layout: kBatchYXDepth } conv_desc { paddings: 1 paddings: 1 paddings: 1 strides: 1 strides: 1 strides: 1 dilations: 1 dilations: 1 dilations: 1 group_count: 1 } conv_scale: 1 input_address: 46931930318592 filter_address: 46930906318080 output_address: 46931418318336 } } results { conv { algorithm: 1 tensor_ops_enabled: true } scratch_bytes: 884752 run_time { nanos: 601746276 } } results { conv { algorithm: 1 } scratch_bytes: 884752 run_time { nanos: 299774810 } } cudnn_version { major: 8 patch: 1 } compute_capability { major: 7 minor: 5 } device_pci_bus_id: "0000:04:00.0" blas_version: "11000" }
```

Thus 601746276 with tensor cores, 299774810 without tensor cores. The use of tensor cores makes it considerably slower.

I'm guessing this is due to CuDNN, perhaps this will be solved in a future release (or the final CuDNN 8 version), or perhaps TF uses a different, more optimal algorithm when not using tensor cores. In any case it seems like it at least picks up on the use of tensor cores for the 3D convolutions now. Thanks :)

**Comment by kaixih** [comment]
@Svdvoort Thanks for your comments.

I just tried your newly pasted script and I think you might forget to add a few warm-up runs to eliminate the cudnn loading overhead.

For example, I gave a shot to run the conv3d three times and I observed that the perf is ~635ms  either w/ or w/o tensor cores in your first case (256 filters). Whereas, the perf is 22ms w/ tensor cores compared to ~200ms w/o them in the second case (128 filters).

**Comment by Svdvoort** [comment]
You are right, there is definitely some warm-up effect. From the earlier scripts with the conv2d and conv3d layers it also matters in which order they are executed, probably also due to the warm-up.

I've now added a conv1d layer to use as warming up, thus the script now is:

```
import tensorflow as tf

N_filters_in = 128
N_filters_out = 128
batch_size = 16
image_size = 50
kernel_size = 3

print("Warming up")
for i in range(5):
    x = tf.random.normal((batch_size, image_size,  N_filters_in), dtype=tf.float16)
    f = tf.random.normal((kernel_size, N_filters_in, N_filters_out), dtype=tf.float16)
    y = tf.nn.conv1d(x, f, stride=[1, 1, 1], padding='SAME')


print("3D")
x = tf.random.normal((batch_size, image_size, image_size, image_size, N_filters_in), dtype=tf.float16)
f = tf.random.normal((kernel_size, kernel_size, kernel_size, N_filters_in, N_filters_out), dtype=tf.float16)
y = tf.nn.conv3d(x, f, strides=[1, 1, 1, 1, 1], padding='SAME')
```

This definitely reduces the time for the 128 filter case (it also means that placing the conv3d or conv2d first doesn't matter anymore):

```
{ instr { [type.googleapis.com/tensorflow.ConvolutionProto] { kind: FORWARD input { dimensions: 16 dimensions: 128 dimensions: 50 dimensions: 50 dimensions: 50 data_type: kHalf data_layout: kBatchYXDepth } filter { dimensions: 128 dimensions: 128 dimensions: 3 dimensions: 3 dimensions: 3 data_type: kHalf filter_layout: kOutputYXInput } output { dimensions: 16 dimensions: 128 dimensions: 50 dimensions: 50 dimensions: 50 data_type: kHalf data_layout: kBatchYXDepth } conv_desc { paddings: 1 paddings: 1 paddings: 1 strides: 1 strides: 1 strides: 1 dilations: 1 dilations: 1 dilations: 1 group_count: 1 } conv_scale: 1 input_address: 46931931342592 filter_address: 46930906728192 output_address: 46930909579008 } } results { conv { algorithm: 1 tensor_ops_enabled: true } scratch_bytes: 884752 run_time { nanos: 357543731 } } results { conv { algorithm: 1 } scratch_bytes: 884752 run_time { nanos: 300922577 } } cudnn_version { major: 8 patch: 1 } compute_capability { major: 7 minor: 5 } device_pci_bus_id: "0000:04:00.0" blas_version: "11000" }
```

Before it was 644354675 with and 300541687 w/o tensor cores, now it is 357543731 with and 300922577 without. Definitely an improvement for the tensor core case, but still slower than without.

For the case of the 256 filters the speed-up is also there:

```
{ instr { [type.googleapis.com/tensorflow.ConvolutionProto] { kind: FORWARD input { dimensions: 16 dimensions: 256 dimensions: 50 dimensions: 50 dimensions: 50 data_type: kHalf data_layout: kBatchYXDepth } filter { dimensions: 256 dimensions: 256 dimensions: 3 dimensions: 3 dimensions: 3 data_type: kHalf filter_layout: kOutputYXInput } output { dimensions: 16 dimensions: 256 dimensions: 50 dimensions: 50 dimensions: 50 data_type: kHalf data_layout: kBatchYXDepth } conv_desc { paddings: 1 paddings: 1 paddings: 1 strides: 1 strides: 1 strides: 1 dilations: 1 dilations: 1 dilations: 1 group_count: 1 } conv_scale: 1 input_address: 46932957153024 filter_address: 46930907137792 output_address: 46930918541056 } } results { conv { algorithm: 1 tensor_ops_enabled: true } run_time { nanos: 270119140 } } results { conv { algorithm: 1 } scratch_bytes: 3538960 run_time { nanos: 844934692 } } cudnn_version { major: 8 patch: 1 } compute_capability { major: 7 minor: 5 } device_pci_bus_id: "0000:04:00.0" blas_version: "11000" }
```

Before 561604370 with tensor cores and 837961303 w/o, now down to 270119140 with tensor cores and 844934692 w/o. Here there is definitely a noticeable improvement of using the tensor cores.

 Perhaps this is also related to the GPU model? This has been tested on an RTX2080Ti.

**Comment by kaixih** [comment]
Yes, it may be related to the GPU model and also the specific cuDNN version.

I tried the 128 filters case on a RTX 2080 super card and it seems the cuDNN doesn't choose the tensor core kernel when use_tensor_core is set and the perf is not good as you observed. Will contact our cudnn team about this.

**Comment by razorx89** [comment]
I modified the script from @Svdvoort to actually measure the execution of multiple op execution and I added a warmup step per conv configuration. This extra warmup is important since on the first execution several kernels are measured and the result determines which will be used in the future. Also, as already mentioned, the data format is a huge factor for performance when using float16.

```python
import time
import pandas as pd
import tensorflow as tf


batch_size = 1
kernel_size = 3
repetitions = 100

result = []


for image_size, filters in ((128, 64), (64, 128), (32, 256), (16, 512), (8, 1024)):
    for data_format in ('NCDHW', 'NDHWC'):
        if data_format == 'NCDHW':
            x = tf.random.normal((batch_size, filters, image_size, image_size, image_size), dtype=tf.float32)
        else:
            x = tf.random.normal((batch_size, image_size, image_size, image_size, filters), dtype=tf.float32)
        f = tf.random.normal((kernel_size, kernel_size, kernel_size, filters, filters), dtype=tf.float32)
        started = time.time()
        tf.nn.conv3d(x, f, strides=[1, 1, 1, 1, 1], padding='SAME', data_format=data_format)
        t_wu_fp32 = time.time() - started
        started = time.time()
        for _ in range(repetitions):
            tf.nn.conv3d(x, f, strides=[1, 1, 1, 1, 1], padding='SAME', data_format=data_format)
        t_fp32 = (time.time() - started) / repetitions

        if data_format == 'NCDHW':
            x = tf.random.normal((batch_size, filters, image_size, image_size, image_size), dtype=tf.float16)
        else:
            x = tf.random.normal((batch_size, image_size, image_size, image_size, filters), dtype=tf.float16)
        f = tf.random.normal((kernel_size, kernel_size, kernel_size, filters, filters), dtype=tf.float16)
        started = time.time()
        tf.nn.conv3d(x, f, strides=[1, 1, 1, 1, 1], padding='SAME', data_format=data_format)
        t_wu_fp16 = time.time() - started
        started = time.time()
        for _ in range(repetitions):
            tf.nn.conv3d(x, f, strides=[1, 1, 1, 1, 1], padding='SAME', data_format=data_format)
        t_fp16 = (time.time() - started) / repetitions

        speedup = t_fp32 / t_fp16

        result.append({
            'image_size': f'{image_size}x{image_size}x{image_size}',
            'filters': filters,
            'data_format': data_format,
            'avg_time_fp32_ms': t_fp32 * 1000,
            'avg_time_fp16_ms': t_fp16 * 1000,
            'warm_up_fp32_ms': t_wu_fp32 * 1000,
            'warm_up_fp16_ms': t_wu_fp16 * 1000,
            'speedup': speedup
        })

print(pd.DataFrame(result).to_markdown(index=False))
```

| image_size   |   filters | data_format   |   avg_time_fp32_ms |   avg_time_fp16_ms |   warm_up_fp32_ms |   warm_up_fp16_ms |   speedup |
|:-------------|----------:|:--------------|-------------------:|-------------------:|------------------:|------------------:|----------:|
| 128x128x128  |        64 | NCDHW         |          0.0706506 |          0.0682282 |      1438.01      |         580.63    |  1.0355   |
| 128x128x128  |        64 | NDHWC         |         38.9074    |         49.9986    |         0.178576  |          59.4954  |  0.77817  |
| 64x64x64     |       128 | NCDHW         |          0.0678205 |          0.0683904 |      7377.11      |        2004.61    |  0.991668 |
| 64x64x64     |       128 | NDHWC         |         10.2363    |         19.1658    |         0.0977516 |          15.6653  |  0.534092 |
| 32x32x32     |       256 | NCDHW         |          0.0678635 |          0.0673509 |      2217.02      |        1046.95    |  1.00761  |
| 32x32x32     |       256 | NDHWC         |          5.10965   |          9.38453   |         0.110626  |           7.80654 |  0.544476 |
| 16x16x16     |       512 | NCDHW         |          0.0669503 |          0.0678897 |      1061.39      |         481.792   |  0.986163 |
| 16x16x16     |       512 | NDHWC         |          2.79787   |          4.92591   |         0.0946522 |           4.32825 |  0.56799  |
| 8x8x8        |      1024 | NCDHW         |          0.0653195 |          0.0702453 |       580.436     |         475.603   |  0.929878 |
| 8x8x8        |      1024 | NDHWC         |          2.88254   |          4.89266   |         0.0939369 |           4.47154 |  0.589155 |

As you can see for NCDHW the performance is more or less equal (within 7% difference), but NDHWC is much much slower. Still, why is float16 not getting accelerated by the tensor cores. @kaixih Did you get any information from the cuDNN team?

Environment details:
- Docker image `tensorflow/tensorflow:2.3.0-gpu`
- Titan RTX (compute capability 7.5)

**Comment by sushreebarsa** [comment]
@Svdvoort  Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!

**Comment by Svdvoort** [comment]
@sushreebarsa I cannot reproduce the original results anymore, as the `TF_CPP_VMODULE=logger=2` option doesn't seem to work anymore. It doesn't give the logs for the use of the tensor cores, has this been updated in tf 2.5 perhaps? 

I did reproduce the table from @razorx89 and that seems to suggests the issue is fixed: 

| image_size   |   filters | data_format   |   avg_time_fp32_ms |   avg_time_fp16_ms |   warm_up_fp32_ms |   warm_up_fp16_ms |   speedup |
|:-------------|----------:|:--------------|-------------------:|-------------------:|------------------:|------------------:|----------:|
| 128x128x128  |        64 | NCDHW         |           0.313146 |           0.187511 |       3384.71     |           608.723 |  1.67001  |
| 128x128x128  |        64 | NDHWC         |           6.07016  |           0.163949 |          0.445366 |          5125.44  | 37.0248   |
| 64x64x64     |       128 | NCDHW         |           0.28568  |           0.190461 |       1104.71     |          2053.8   |  1.49994  |
| 64x64x64     |       128 | NDHWC         |           2.57943  |           0.161428 |          0.379324 |          2171.46  | 15.9788   |
| 32x32x32     |       256 | NCDHW         |           0.244176 |           0.203857 |        595.336    |          1423.26  |  1.19778  |
| 32x32x32     |       256 | NDHWC         |           1.30862  |           0.181801 |          0.302315 |          1390.37  |  7.19806  |
| 16x16x16     |       512 | NCDHW         |           0.162723 |           0.202661 |        230.961    |           678.329 |  0.802934 |
| 16x16x16     |       512 | NDHWC         |           0.662382 |           0.178571 |          0.259638 |           738.842 |  3.70935  |
| 8x8x8        |      1024 | NCDHW         |           0.30431  |           0.19779  |        132.777    |           741.014 |  1.53856  |
| 8x8x8        |      1024 | NDHWC         |           2.74531  |           0.17312  |          0.398159 |           917.235 | 15.8578   |

The float16 is faster in all but one case (the 16x16x16 NCDHW filter), but in that case the difference is too small to call significant.

**Comment by sushreebarsa** [comment]
@Svdvoort  could you please let us know if this issue is fixed for you and move this issue to closed status ,thank you !

**Comment by tokafondo** [comment]
FWIW, those are my numbers in a plain 3060.

I had to add
```
import tensorflow as tf

+ physical_devices = tf.config.list_physical_devices('GPU')
+ try:
+   tf.config.experimental.set_memory_growth(physical_devices[0], True)
+ except:
+   # Invalid device or cannot modify virtual devices once initialized.
+   pass

batch_size = 1
```

so I could get CUBLAS to have memory available enough to get loaded.

| image_size   |   filters | data_format   |   avg_time_fp32_ms |   avg_time_fp16_ms |   warm_up_fp32_ms |   warm_up_fp16_ms |   speedup |
|:-------------|----------:|:--------------|-------------------:|-------------------:|------------------:|------------------:|----------:|
| 128x128x128  |        64 | NCDHW         |           0.293372 |           0.183482 |       3076.78     |           937.201 |   1.59891 |
| 128x128x128  |        64 | NDHWC         |           3.92     |           0.151255 |          0.42367  |         10259.5   |  25.9165  |
| 64x64x64     |       128 | NCDHW         |           0.293863 |           0.180457 |       2313.67     |          2223.22  |   1.62844 |
| 64x64x64     |       128 | NDHWC         |           1.63215  |           0.161881 |          0.356197 |          2885.53  |  10.0824  |
| 32x32x32     |       256 | NCDHW         |           0.436578 |           0.174732 |       1186.67     |          1203.71  |   2.49855 |
| 32x32x32     |       256 | NDHWC         |           2.28528  |           0.158327 |          0.504732 |          1282.75  |  14.4339  |
| 16x16x16     |       512 | NCDHW         |           0.435343 |           0.175846 |        533.474    |           602.699 |   2.47571 |
| 16x16x16     |       512 | NDHWC         |           1.35215  |           0.158868 |          0.481367 |           794.932 |   8.51117 |
| 8x8x8        |      1024 | NCDHW         |           0.42227  |           0.176437 |        327.084    |           825.292 |   2.39332 |
| 8x8x8        |      1024 | NDHWC         |           2.81567  |           0.160062 |          0.495911 |          1175.79  |  17.5911  |
