### ISSUE TITLE
The problem about data flow graph?

### ISSUE THREAD

**Issue by JohnnyY8** [tensorflow/tensorflow#3999]
Hi everyone:
     I am a beginner for tensorflow, and do not understand something about the demo in tutorial files, like following:
![image](https://cloud.githubusercontent.com/assets/12611573/17914869/688d864a-69d8-11e6-8692-4c3e41e695bf.png)
     During testing, how can accuracy call the trained model for mnist.test.images and mnist.test.labels.
     Does the trained model flow to the accuracy?
     Can anyone help me? Thanks a lot!

**Comment by suiyuan2009** [comment]
this question is more suitable for stackoverflow.

**Comment by suiyuan2009** [comment]
@JohnnyY8 `accuracy` is just a node of the graph, a bfs can traversal the whole graph.

**Comment by JohnnyY8** [comment]
@suiyuan2009 Thank you.
