### ISSUE TITLE
broadcasting behavior in tensorflow keras layers vs base tensorflow operators

### ISSUE THREAD

**Issue by nitinmnsn** [tensorflow/tensorflow#39995]
ubuntu : 20.04
Tensorflow : 2.2.0

Tensorflow keras layers have different broadcasting semantics than numpy broadcasting (same as tensorflow core). Briefly speaking, AFAIK, broadcasting should keep adding a dimension on left hand side to the point where ndim of two arrays being operated on become equal and then the operation is carried out by required number of replications along all the axis of size 1. for example (5,10) + (2,5,10) would be changed to (1,5,10) + (2,5,10) and then (1,5,10) would be added to (2,5,10) by replicating itself along axis 2. But keras does not seem to follow this. Below is the code to reproduce the issue
```
from tensorflow import keras as k
from tensorflow.keras import layers as l
import tensorflow as tf
import numpy as np

inp = k.Input(shape=(10),dtype=tf.float32)
vec1 = tf.constant(np.arange(start=1000,stop=1010,dtype=np.float32).reshape(10,))
vec2 = tf.constant(np.arange(start=100,stop=110,dtype=np.float32).reshape(1,10))
ou1 = inp+vec1
ou2 = l.Add()([inp,vec1])
ou3 = inp+vec2
ou4 = l.Add()([inp,vec2])
out5 = vec1+vec2
print(ou1,'\n',ou2,'\n',ou3,'\n',ou4,'\n',ou5)
out6 = l.Add()([vec1,vec2])


```
output:
```
Tensor("AddV2_55:0", shape=(None, 10), dtype=float32) 
Tensor("AddV2_56:0", shape=(10, 10), dtype=float32) 
Tensor("AddV2_57:0", shape=(None, 10), dtype=float32) 
Tensor("AddV2_58:0", shape=(None, 10), dtype=float32) 
Tensor("Add_1:0", shape=(None, 10), dtype=float32)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-49-0cd687be06bc> in <module>
     13 out5 = vec1+vec2
     14 print(ou1,'\n',ou2,'\n',ou3,'\n',ou4,'\n',ou5)
---> 15 out6 = l.Add()([vec1,vec2])
     16 

~/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    962         # Eager execution on data tensors.
    963         with backend.name_scope(self._name_scope()):
--> 964           self._maybe_build(inputs)
    965           cast_inputs = self._maybe_cast_inputs(inputs)
    966           with base_layer_utils.autocast_context_manager(

~/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in _maybe_build(self, inputs)
   2414         # operations.
   2415         with tf_utils.maybe_init_scope(self):
-> 2416           self.build(input_shapes)  # pylint:disable=not-callable
   2417       # We must set also ensure that the layer is marked as built, and the build
   2418       # shape is stored since user defined build functions may not be calling

~/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/keras/utils/tf_utils.py in wrapper(instance, input_shape)
    314     if input_shape is not None:
    315       input_shape = convert_shapes(input_shape, to_tuples=True)
--> 316     output_shape = fn(instance, input_shape)
    317     # Return shapes from `fn` as TensorShapes.
    318     if output_shape is not None:

~/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/keras/layers/merge.py in build(self, input_shape)
    100       raise ValueError(
    101           'Can not merge tensors with different '
--> 102           'batch sizes. Got tensors with shapes : ' + str(input_shape))
    103     if input_shape[0] is None:
    104       output_shape = None

ValueError: Can not merge tensors with different batch sizes. Got tensors with shapes : [(10,), (1, 10)]
```

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/73e91c8d3f3e1a9091d69a771b0a0254/untitled208.ipynb)

**Comment by nitinmnsn** [comment]
any updates on this?

**Comment by saikumarchalla** [comment]
I can able to reproduce the issue. please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/70e5a61bd24940441463a2f5b1b10986/untitled80.ipynb).Thanks!

**Comment by chunduriv** [comment]
I was able to replicate issue in `tf2.6` and `tf-nightly(2.8.0-dev20211012)`. Please find the gist [here](https://colab.research.google.com/gist/chunduriv/bb5a62a8e81e281a7cd62af885319f39/39995.ipynb#scrollTo=I5C3xKFDEfWM).Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
