### ISSUE TITLE
tf.Module break gradient registration

### ISSUE THREAD

**Issue by AdrienCorenflos** [tensorflow/tensorflow#39996]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab default

**Describe the current behavior**
When using operations within a tf.Module init, the gradient is broken

**Describe the expected behavior**
The gradient should still be registered properly

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1X3DTc5-E-WadufSHUbVfBnVFEPQ0iOSR?usp=sharing

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/af9e7b3b1a72432c7561691518453a40/39996.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/627d9652a3c45160e098f4bdb32d0fef/39996-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by rohan100jain** [comment]
So I think the issue is that you're doing computation in __init__ but not wrapping that in the GradientTape call.

Modifying the code as 

```
phi = tf.Variable(tf.zeros(5), trainable=True)
with tf.GradientTape() as tape:
  m = MyModule(phi)
  x = tf.ones(5)
  tape.watch(phi)
  res = m.fun(x)
print(tape.gradient(res, phi))
```

seems to work now. Let me know if you run into more issues.

**Comment by AdrienCorenflos** [comment]
Yes you're right that was me being stupid. Sorry to have made you lost time
