### ISSUE TITLE
STOP UPDATING

### ISSUE THREAD

**Issue by creatist** [tensorflow/tensorflow#39998]
More updations, more pains!!!

**Comment by ravikyram** [comment]
@creatist 
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

Make sure you also include the code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in the Github [new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
