### ISSUE TITLE
Correct way of using tf.keras.layers.experimental.preprocessing layers under strategy scope

### ISSUE THREAD

**Issue by djdongjin** [tensorflow/tensorflow#39991]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Yes
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): nightly
- Python version: 3.7
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

How should I use the preprocessing layers together with distribute strategy? Since strategy requires something like this:

```python
with strategy.scope():
    model = build_model()
    model.fit(...)
```

But when I use the preprocessing layers, I got the following errors:

```python
Traceback (most recent call last):
  File "make_image_classifier.py", line 307, in <module>
    run_main()
  File "make_image_classifier.py", line 303, in run_main
    app.run(main)
  File "/home/ml/users/jdong25/.conda/envs/tf/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/ml/users/jdong25/.conda/envs/tf/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "make_image_classifier.py", line 260, in main
    FLAGS.summaries_dir)
  File "/home/ml/users/jdong25/.conda/envs/tf/lib/python3.7/site-packages/tensorflow_hub/tools/make_image_classifier/make_image_classifier_lib.py", line 380, in make_image_classifier
    hparams.do_data_augmentation, augment_params)
  File "/home/ml/users/jdong25/.conda/envs/tf/lib/python3.7/site-packages/tensorflow_hub/tools/make_image_classifier/make_image_classifier_lib.py", line 261, in build_model
    preprocessing.RandomRotation(factor=augment_params['rotation_range']),
  File "/home/ml/users/jdong25/.conda/envs/tf/lib/python3.7/site-packages/tensorflow/python/keras/layers/preprocessing/image_preprocessing.py", line 787, in __init__
    self._rng = make_generator(self.seed)
  File "/home/ml/users/jdong25/.conda/envs/tf/lib/python3.7/site-packages/tensorflow/python/keras/layers/preprocessing/image_preprocessing.py", line 1289, in make_generator
    return stateful_random_ops.Generator.from_non_deterministic_state()
  File "/home/ml/users/jdong25/.conda/envs/tf/lib/python3.7/site-packages/tensorflow/python/ops/stateful_random_ops.py", line 471, in from_non_deterministic_state
    return cls(state=state, alg=alg)
  File "/home/ml/users/jdong25/.conda/envs/tf/lib/python3.7/site-packages/tensorflow/python/ops/stateful_random_ops.py", line 384, in __init__
    trainable=False)
  File "/home/ml/users/jdong25/.conda/envs/tf/lib/python3.7/site-packages/tensorflow/python/ops/stateful_random_ops.py", line 270, in _create_variable
    "Creating a generator within a strategy scope is disallowed, because "
ValueError: Creating a generator within a strategy scope is disallowed, because there is ambiguity on how to replicate a generator (e.g. should it be copied so that each replica gets the same random numbers, or 'split' so that each replica gets different random numbers).
```

The error message is reasonable to me, but how should I use them correctly? As a reference, my model was built like:

```python
def build_model(...):
  model = tf.keras.Sequential([
      tf.keras.Input(shape=(image_size[0], image_size[1], 3)),])

  aug_preprocessor = None
  if do_data_augmentation:
    preprocessing = tf.keras.layers.experimental.preprocessing
    aug_preprocessor = tf.keras.Sequential(
      preprocessing.RandomRotation(factor=augment_params['rotation_range']),
      preprocessing.RandomWidth(factor=augment_params['width_shift_range']),
      preprocessing.RandomHeight(factor=augment_params['height_shift_range']),
      preprocessing.RandomZoom(factor=augment_params['zoom_range']),
      preprocessing.RandomFlip(mode='horizontal')
    )
    model.add(aug_preprocessor)

  model.add(module_layer)
  model.add(tf.keras.layers.Dropout(rate=hparams.dropout_rate))
  model.add(tf.keras.layers.Dense(
      num_classes,
      activation="softmax",
      kernel_regularizer=tf.keras.regularizers.l1_l2(l1=hparams.l1_regularizer,
                                                     l2=hparams.l2_regularizer)))

  print(model.summary())
  return model

with strategy.scope():
    model = build_model(model)
    summ = train_model(model,...)
```

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@djdongjin 
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by djdongjin** [comment]
> @djdongjin
> This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

Okay. I do think this is a feature request. For me, the current preprocessing layers do not support distribute strategy, which prevents them from being used in any model that wants to support distribute strategy.

**Comment by djdongjin** [comment]
Any updates?

**Comment by tanzhenyu** [comment]
This is a legitimate feature request that we should resolve

**Comment by goldiegadde** [comment]
@djdongjin thanks for reporting the issue. We are looking into it.

**Comment by mohantym** [comment]
Hi @djdongjin !
We are checking to see whether you still need help in this issue . Have you checked this issue in 2.8/2.10 version with [distribution strategy](https://www.tensorflow.org/guide/distributed_training#examples_and_tutorials) lately.

Thank you!
