### ISSUE TITLE
Error in the Getting started/Variables section of the website

### ISSUE THREAD

**Issue by cristian-frincu** [tensorflow/tensorflow#40]
_**The code part of the code**_
var = tf.Variable(0, name="counter")
one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)

_**should be changed to**_

var = tf.Variable(0, name="counter")
one = tf.constant(1)
new_value = tf.add(**var**, one)
update = tf.assign(**var**, new_value)

*The rest of the code after this section works as expected *

**Comment by vrv** [comment]
Hi Cristian, thanks for the report!  We fixed this in https://github.com/tensorflow/tensorflow/commit/db0b5da485e1d1f23003ee08ed2e191451ee0319, hasn't yet been pushed to our website, which should happen soon :).  Please re-open if this hasn't been fixed on the site in a day or two.  Thanks!

**Comment by cristian-frincu** [comment]
On the same page, the Feeds section, the *with* statement should be 

with tf.Session() **as sess**:
