### ISSUE TITLE
About the official document variable name introduced by Profiler is inconsistent！

### ISSUE THREAD

**Issue by AITutorials** [tensorflow/tensorflow#40003]
About the official document variable name introduced by Profiler is inconsistent！

Please see the URL：
[https://tensorflow.google.cn/guide/profiler?hl=en](https://tensorflow.google.cn/guide/profiler?hl=en)

![WechatIMG6](https://user-images.githubusercontent.com/61530230/83288790-8c986800-a216-11ea-94aa-0b6ddc2d4e51.png)

You can find problems with two variables：“tb_callback” and “tensorboard_callback” ！

**Comment by ymodak** [comment]
This is fixed now. Thanks!
