### ISSUE TITLE
Link error for libtensorflow_cc.so when using LoadSavedModel

### ISSUE THREAD

**Issue by dgel** [tensorflow/tensorflow#40004]
The version scripts don't export any symbols from protobuf. This is fine as long as basic functionality doesn't use symbols from protobuf, but LoadSavedModel seems to me to be a part of the basic functionality of tensorflow. Adding `*google*protobuf*` to the version scripts fixes the issue, as would hiding the protobuf data from the interface

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.2.0
- Python version: n/a
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): GCC 7.5.0
- CUDA/cuDNN version: CUDA 10.1, cuDNN 7.6.3
- GPU model and memory: n/a

**Describe the current behavior**
When using the LoadSavedModel function from c++ and linking against tensorflow_cc.so, a link error appears saying `undefined reference to 'google::protobuf::internal::MapFieldBase::SyncMapWithRepeatedField() const'`

**Describe the expected behavior**
The program links and runs without issues

**Standalone code to reproduce the issue**
Any c++ program using LoadSavedModel and linking libtensorflow_cc.so will do

**Comment by ravikyram** [comment]
@dgel 

Can you go through the l[ink1](https://github.com/tensorflow/tensorflow/issues/35623),[link2](https://github.com/tensorflow/tensorflow/issues/14632),[link3](https://github.com/tensorflow/tensorflow/issues/22980) and see if it helps you.Thanks!

**Comment by dgel** [comment]
Hi @ravikyram 

It seems links 1 and 3 are about building tensorflow_cc.so itself. I'm having no issues building the tensorflow library, just with linking against it, so I'll discard those. 

If I understand correctly from link 2, any tensorflow API that uses parts of protobuf needs to additionally link against libtensorflow_framework.so? Why is this done instead of just exporting the protobuf symbols from libtensorflow_cc.so directly? I haven't built libtensorflow_framework yet, so I'll try that and see how it goes

**Comment by xiandong79** [comment]
@dgel could you have a look on https://github.com/tensorflow/tensorflow/issues/44899

**Comment by dhgelling** [comment]
@xiandong79 That is exactly the error I reported here, perhaps mark it duplicate and close? No need to open multiple issues for the same problem

**Comment by xiandong79** [comment]
@dhgelling Sure, I have closed it.

do you have solutions to overcome/bypass the error?

**Comment by dhgelling** [comment]
yes, expanding on the solution I mentioned when reporting the issue, before building / linking libtensorflow_cc.so, add `*google*protobuf*``to the version scripts (that's `tensorflow/tf_version_script.lds` for linux and `tensorflow/tf_exported_symbols.lds` for mac)

**Comment by xiandong79** [comment]
add `*google*protobuf*;` into `tensorflow/tf_version_script.lds`
```
ubuntu@ip-172-31-14-28:~$ cat /home/ubuntu/tensorflow_cc/tensorflow_cc/build/tensorflow/tensorflow/tf_version_script.lds
tensorflow {
  global:
    *tensorflow*;
    *absl*kSeed*;
    *toco*;
    *google*protobuf*;
    *perftools*gputools*;
    *tf_*;
    *TF_*;
    *Eager*;
    *TFE_*;
    *nsync_*;
    *stream_executor*;
    *xla*;
    *PyInit_*;
  local:
    *;
};
```

As I use [ FloopCZ /tensorflow_cc ](https://github.com/FloopCZ/tensorflow_cc)

### (re-)Build and (re-)install the library
```
cd /home/ubuntu/tensorflow_cc/tensorflow_cc/build
cmake ..
make
sudo make install
```

however, it does not work yet. @dhgelling should I do other modification?

**Comment by dhgelling** [comment]
I mean if that solution works then go with that, no? The reason my solution doesn't work with `FloopCZ/tensorflow_cc` is that the resulting make script will download all the sources needed, and overwrite any changes we make. I 'solved' this by running make, waiting for bazel to start compiling, then interrupt with `ctrl+c`, then edit the version script and running make again.

Another option would be to just make the changes in a branch of tensorflow and make `FloopCZ/tensorflow_cc` use that branch instead. Also, it's possible that you won't need the fix at all if you use `SavedModelBundleLite` instead of `SavedModelBundle`

**Comment by sushreebarsa** [comment]
@dgel 
It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Can you please try using Latest Version 2.7.0 and let us know if it helps? Thanks!
