### ISSUE TITLE
Conflict python between Tensorflow, Spyder and Octave

### ISSUE THREAD

**Issue by IvanGas** [tensorflow/tensorflow#40005]
Hello,
I am very new of python environment.
After some time spent learning python through Anaconda on Windows PC (in particular with Spyder), I also decided to learn Tensorflow, always in Spyder. So, I created a new dedicated environment for TF with the v3.6.9 and v1.17.2, respectively, for python and numpy.

I have never had problems running codes that require TF import with this configuration.
However, after some time, to use the Octave symbolic library I had to download Python from Microsoft Store. The downloaded version were 3.8.3 and I also installed the pip package from cmd. The symbolic package in Octave works, but from that moment when I run a code in Spyder that requires the import of tensorflow, I get the following error:

```
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devd_ocs/user/trou_bleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.6 from "C:\Users\ivang\.conda\envs\tensorflow_cpu\python.exe"
  * The NumPy version is: "1.18.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named `'numpy.core._multiarray_umath_'
```

As suggested, checking my PATH and PYTHONPATH environment variables I obtained the paths in the attached picture. 
![PATHS](https://user-images.githubusercontent.com/47055464/83290215-999d6300-a1e6-11ea-92c7-b71af5a9f7a7.png)
These environment variables were not created by me, but by Python at the time of its stand-alone installation.

I understand that the problem is related to the different versions of python installed, but why this conflict happens if I created a dedicated environment in Anaconda, as explained at the beginning of the post? How can I solve this conflict using both TF in Spyder and the library in Octave on the same PC?

I tried to uninstall Python 3.8 but the environment variables remain and also the directory in C:\Program Files\Python38\ where site packages are installed.

Thank you so much for the help,
IG

**Comment by Saduf2019** [comment]
Can you please refer to this [comment](https://github.com/tensorflow/tensorflow/issues/39130#issuecomment-623335820) also can you down grade your python [3.7] and let us know if it helps.
please refer to his [page](https://www.tensorflow.org/install/pip)

#33374  #33543  [link](https://github.com/tensorflow/tensorflow/issues/38750#issuecomment-623088620)

**Comment by IvanGas** [comment]
Please, see the solution reported [here](https://github.com/spyder-ide/spyder/issues/12899).

Best regards.

**Comment by Saduf2019** [comment]
@IvanGas 
Please confirm if we may move this to closed status.

**Comment by IvanGas** [comment]
@Saduf2019 
I confirm that the issue can be closed.

Thank you and regards,
IG

**Comment by Saduf2019** [comment]
Moving this to closed status with confirmation
