### ISSUE TITLE
cannot import name 'compiler'

### ISSUE THREAD

**Issue by LucasColas** [tensorflow/tensorflow#40001]
Hello,

**System information**
I try to run a code on Google Colab. I'm using Tensorflow 2.2.0

When I try to run my code to import tensorflow_probability as tfp.

`import tensorflow_probability as tfp
import tensorflow as tf`

And then when I execute I get : 
`ImportError: cannot import name 'compiler' `

**Comment by ravikyram** [comment]
@LucasColas 

I have tried in colab with TF version 2.2.0 and i am not seeing any issue.Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/d7ad500756d76dc15577110c28b2bf78/untitled936.ipynb).Thanks!

**Comment by LucasColas** [comment]
I tried your gist, and now it's working ! I think it was a problem of version. Thank you !

**Comment by ravikyram** [comment]
@LucasColas 

I am closing this thread as your issue was resolved.Thanks!
