### ISSUE TITLE
Image recognition with TensorFlow Lite for Andorid

### ISSUE THREAD

**Issue by Vivaldi64** [tensorflow/tensorflow#40017]
0

I am new to Android Studio and TensorFlow lite, I have used google teachable machines to train some model an create my tflite files I started working form this git code that tensorflow provides for image-classification:

https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android

And after following this tutorial:

https://codelabs.developers.google.com/codelabs/recognize-flowers-with-tensorflow-on-android/index.html?index=..%2F..index#0

My android phone can now recognise objects using the camera, I would like to add a feature so that the app would read the name on the Object Label using the "text to speech" function, I need this to help a blind person recognising object using this app, but the code is too complex and I don't know how to implement this, can anyone help me? this video show more ore less what the app is supposed to do: https://www.youtube.com/watch?v=sa4qGxQAlqs I only miss the text to speech feature

**Comment by jvishnuvardhan** [comment]
@Vivaldi64 Can you please check [here](https://teachablemachine.withgoogle.com/v1/). You can select "Speech" tab for your application. Down the page there are additional resources that can help you. This is more related to `tensorflow.js` so please post further questions in that repo. Thanks!

Please close the issue if this resolved for you. Thanks!
