### ISSUE TITLE
Error ImageDataGenerator in multiple GPU

### ISSUE THREAD

**Issue by tsbressan** [tensorflow/tensorflow#40015]
I have the following error when running code using multiple GPUs. I am using ImageDataGenerator to classify images that are separated by directories.
The error is:

Traceback (most recent call last):
  File "new_train_alg_CNN.py", line 113, in <module>
    train = model.fit_generator(generator=train_generator,steps_per_epoch = trai              n_generator.samples/BATCH_SIZE,validation_data=validation_generator,validation_s              teps=validation_generator.samples/BATCH_SIZE,epochs= 100,callbacks=[checkpoint,               early_stop],use_multiprocessing=True)
  File "/root/anaconda3/envs/tf-gpu/lib/python3.8/site-packages/tensorflow/pytho              n/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/tf-gpu/lib/python3.8/site-packages/tensorflow/pytho              n/keras/engine/training_v1.py", line 1217, in fit_generator
    return self.fit(
  File "/root/anaconda3/envs/tf-gpu/lib/python3.8/site-packages/tensorflow/pytho              n/keras/engine/training_v1.py", line 766, in fit
    return func.fit(
  File "/root/anaconda3/envs/tf-gpu/lib/python3.8/site-packages/tensorflow/pytho              n/keras/engine/training_distributed.py", line 612, in fit
    dataset = model._distribution_standardize_user_data(
  File "/root/anaconda3/envs/tf-gpu/lib/python3.8/site-packages/tensorflow/pytho              n/keras/engine/training_v1.py", line 2167, in _distribution_standardize_user_dat              a
    assert isinstance(x, dataset_ops.DatasetV2)
AssertionError

**Comment by ravikyram** [comment]
@tsbressan 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
Request you to fill [Github new issue template.](https://github.com/tensorflow/tensorflow/issues/new/choose).

Will it be possible to share colab link or simple standalone code to reproduce the issue in our environment.It helps is in localizing the issue faster.Thanks!

**Comment by tsbressan** [comment]
Ubuntu 18.04.4 , cuda:10.1, cudnn7, running on docker.
use 3 GPUs, nVidia RTX 2080

below is the code:

#import librarys
import json
import os
import numpy as np 
import pandas as pd
import sys
import cv2


import tensorflow as tf
from tensorflow import keras

config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.compat.v1.Session(config=config)
BATCH_SIZE = 10

with tf.compat.v1.Session(config=config) as sess:
    
    patch_out = "output/train"

    #save the contents of the complete arrays
    np.set_printoptions(threshold=sys.maxsize)


    #read files in directory
    files = []
    size_files = []
    for filename in os.listdir(patch_out):
        files.append (filename)
        size_files.append (os.path.getsize(patch_out+"/"+filename))
          
    
    
    # Create a MirroredStrategy.
    strategy = tf.distribute.MirroredStrategy()
    print("Number of devices: {}".format(strategy.num_replicas_in_sync))

    # Open a strategy scope.
    with strategy.scope():

        model = keras.models.Sequential()
        model.add(keras.layers.Conv2D(32, (3, 3), padding='same', input_shape=(256,256,3)))
        model.add(keras.layers.Activation('relu'))
        model.add(keras.layers.Conv2D(32, (3, 3)))
        model.add(keras.layers.Activation('relu'))
        model.add(keras.layers.MaxPooling2D(pool_size=(2, 2)))
        model.add(keras.layers.Dropout(0.25))

        model.add(keras.layers.Conv2D(64, (3, 3), padding='same'))
        model.add(keras.layers.Activation('relu'))
        model.add(keras.layers.Conv2D(64, (3, 3)))
        model.add(keras.layers.Activation('relu'))
        model.add(keras.layers.MaxPooling2D(pool_size=(2, 2)))
        model.add(keras.layers.Dropout(0.25))

        model.add(keras.layers.Flatten())

        model.add(keras.layers.Dense(256))
        model.add(keras.layers.Activation('relu'))
        model.add(keras.layers.Dropout(0.5))
        model.add(keras.layers.Dense(14, activation='softmax'))

        model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

        checkpoint = keras.callbacks.ModelCheckpoint('logs/model_train.hdf5', monitor='val_loss', verbose=1, mode='min', save_best_only=True)

        early_stop = keras.callbacks.EarlyStopping(monitor='val_loss', min_delta=0.001, patience=5, mode='min',verbose=1)
       

        
        # Train the model on all available devices.
        
        data_generator = keras.preprocessing.image.ImageDataGenerator(rescale=1./255, validation_split=0.15)

        train_generator = data_generator.flow_from_directory(patch_out, shuffle=True, seed=13,
                                                             class_mode='categorical', batch_size=BATCH_SIZE, subset="training")
        validation_generator = data_generator.flow_from_directory(patch_out, shuffle=True, seed=13, 
                                                            class_mode='categorical', batch_size=BATCH_SIZE, subset="validation")
                                                            
        file = validation_generator.filenames                                                     
        for i in range(0,len(file)):
            files = file[i].split('/')
            print (files[1])    
    
    
        train = model.fit(train_generator,steps_per_epoch = train_generator.samples/BATCH_SIZE,validation_data=validation_generator,validation_steps=validation_generator.samples/BATCH_SIZE,epochs= 100,callbacks=[checkpoint, early_stop])  
        #train = model.fit(train_generator,epochs= 5, validation_data=validation_generator)  



        print(train.history.keys())

**Comment by ravikyram** [comment]
@tsbressan 

Please, let us know the Tensorflow version you are using?.Thanks!

**Comment by tsbressan** [comment]
CUDA 10.1.243
tensorFlow: 2.2.0

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2080    Off  | 00000000:17:00.0 Off |                  N/A |
| 41%   25C    P8     1W / 225W |     25MiB /  7979MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 2080    Off  | 00000000:65:00.0 Off |                  N/A |
| 41%   26C    P8     7W / 225W |      1MiB /  7982MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 2080    Off  | 00000000:B3:00.0 Off |                  N/A |
| 41%   25C    P8     1W / 225W |      1MiB /  7982MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
