### ISSUE TITLE
iOS ld error

### ISSUE THREAD

**Issue by lcwyylcwyy** [tensorflow/tensorflow#4001]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN:  No
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. Which pip package you installed.  
from source
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.10.0rc0

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`) 
cc3153a7a0a23533d14ead34db37e4ccd7892079

2. The output of `bazel version`  
0.3.1-homebrew

### Steps to reproduce
1. ./configure
2.  sh tensorflow/contrib/makefile/build_all_ios.sh
or sh sh tensorflow/contrib/makefile/compile_ios_tensorflow.sh

### What have you tried?
1.   only compile the libtensorflow-core-<arm arch>.a  on different platform and lipo them to get libtensorflow-core.a

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
all arm arch have got these logs.

"tensorflow::functor::ReduceAndReshape<Eigen::ThreadPoolDevice, float, 6, 1>::operator()(Eigen::ThreadPoolDevice const&, Eigen::TensorMap<Eigen::Tensor<float, 6, 1, long>, 16>, Eigen::TensorMap<Eigen::Tensor<float const, 6, 1, long>, 16>, Eigen::DSizes<long, 1> const&, Eigen::DSizes<long, 6> const&) const", referenced from:
      void tensorflow::TileGradientOp<Eigen::ThreadPoolDevice>::HandleReduce<float, 6, 1>(tensorflow::OpKernelContext*, std::__1::vector<int, std::__1::allocator<int> > const&, tensorflow::Tensor*) in libtensorflow-core-arm64.a(tile_ops.o)
  "tensorflow::functor::TileGrad<Eigen::ThreadPoolDevice, int, 6>::operator()(Eigen::ThreadPoolDevice const&, Eigen::TensorMap<Eigen::Tensor<int, 6, 1, long>, 16>, Eigen::TensorMap<Eigen::Tensor<int const, 6, 1, long>, 16>, Eigen::DSizes<long, 6> const&, Eigen::DSizes<long, 6> const&, bool) const", referenced from:
      void tensorflow::TileGradientOp<Eigen::ThreadPoolDevice>::HandleCaseImpl<(tensorflow::DataType)3, 6>(tensorflow::OpKernelContext*, std::__1::vector<int, std::__1::allocator<int> > const&, tensorflow::gtl::ArraySlice<int> const&, tensorflow::Tensor*) in libtensorflow-core-arm64.a(tile_ops.o)
  "tensorflow::functor::TileGrad<Eigen::ThreadPoolDevice, float, 6>::operator()(Eigen::ThreadPoolDevice const&, Eigen::TensorMap<Eigen::Tensor<float, 6, 1, long>, 16>, Eigen::TensorMap<Eigen::Tensor<float const, 6, 1, long>, 16>, Eigen::DSizes<long, 6> const&, Eigen::DSizes<long, 6> const&, bool) const", referenced from:
      void tensorflow::TileGradientOp<Eigen::ThreadPoolDevice>::HandleCaseImpl<(tensorflow::DataType)1, 6>(tensorflow::OpKernelContext*, std::__1::vector<int, std::__1::allocator<int> > const&, tensorflow::gtl::ArraySlice<int> const&, tensorflow::Tensor*) in libtensorflow-core-arm64.a(tile_ops.o)
  "tensorflow::functor::Tile<Eigen::ThreadPoolDevice, int, 6>::operator()(Eigen::ThreadPoolDevice const&, Eigen::TensorMap<Eigen::Tensor<int, 6, 1, long>, 16>, Eigen::TensorMap<Eigen::Tensor<int const, 6, 1, long>, 16>, std::__1::array<int, 6ul> const&) const", referenced from:
      void tensorflow::TileOp<Eigen::ThreadPoolDevice>::HandleCaseImpl<(tensorflow::DataType)3, 6>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<int> const&, tensorflow::Tensor*) in libtensorflow-core-arm64.a(tile_ops.o)
  "tensorflow::functor::ReduceAndReshape<Eigen::ThreadPoolDevice, int, 6, 1>::operator()(Eigen::ThreadPoolDevice const&, Eigen::TensorMap<Eigen::Tensor<int, 6, 1, long>, 16>, Eigen::TensorMap<Eigen::Tensor<int const, 6, 1, long>, 16>, Eigen::DSizes<long, 1> const&, Eigen::DSizes<long, 6> const&) const", referenced from:
      void tensorflow::TileGradientOp<Eigen::ThreadPoolDevice>::HandleReduce<int, 6, 1>(tensorflow::OpKernelContext*, std::__1::vector<int, std::__1::allocator<int> > const&, tensorflow::Tensor*) in libtensorflow-core-arm64.a(tile_ops.o)
  "tensorflow::functor::Tile<Eigen::ThreadPoolDevice, float, 6>::operator()(Eigen::ThreadPoolDevice const&, Eigen::TensorMap<Eigen::Tensor<float, 6, 1, long>, 16>, Eigen::TensorMap<Eigen::Tensor<float const, 6, 1, long>, 16>, std::__1::array<int, 6ul> const&) const", referenced from:
      void tensorflow::TileOp<Eigen::ThreadPoolDevice>::HandleCaseImpl<(tensorflow::DataType)1, 6>(tensorflow::OpKernelContext*, tensorflow::gtl::ArraySlice<int> const&, tensorflow::Tensor*) in libtensorflow-core-arm64.a(tile_ops.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/chh/Dev_Ling/tensorflow/tensorflow/contrib/makefile/gen/bin/ios_ARM64/benchmark] Error 1
arm64 compilation failed.

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/makefile/tf_op_files.txt#L14
if you add tile_ops_cpu_impl_6.cc to that list, does it work?

**Comment by lcwyylcwyy** [comment]
It's long time to compile the ios lib
It works! Thank you again.
And I think there is no need to compile x86 and x86-64 on ios platform.
In the compile_ios_tensorflow.sh, there are 

make -f tensorflow/contrib/makefile/Makefile \
TARGET=IOS IOS_ARCH=I386 LIB_NAME=${LIB_PREFIX}-i386.a OPTFLAGS="$1" $2 $3
if [ $? -ne 0 ]
then
  echo "i386 compilation failed."
  exit 1
fi

make -f tensorflow/contrib/makefile/Makefile \
TARGET=IOS IOS_ARCH=X86_64 LIB_NAME=${LIB_PREFIX}-x86_64.a OPTFLAGS="$1" $2 $3
if [ $? -ne 0 ]
then
  echo "x86_64 compilation failed."
  exit 1
fi

and  'lipo x86 , x64'  increases the static lib size.

**Comment by petewarden** [comment]
The reason for the x86/x64 architectures is so we can run simulator targets. It looks like this is fixed, so I'm closing, but do re-open if you have more information!
