### ISSUE TITLE
When subclassing the `Model` class, you should implement a `call` method.

### ISSUE THREAD

**Issue by w19787** [tensorflow/tensorflow#40019]
tf version: tf 2.1.0

```python
import tensorflow as tf

def sub_test_model():
    x = inputs = tf.keras.Input((5,), name='input')
    x = tf.keras.layers.Dense(8)(x)
    x = tf.keras.layers.Softmax()(x)
    
    return tf.keras.Model(inputs, x)  

def test_create_model():
    x = inputs = tf.keras.Input((3,), name='input')
    x = tf.keras.layers.Dense(5)(x)
    x = tf.keras.layers.Softmax()(x)
    
    x = sub_test_model()(x)
    
    return tf.keras.Model(inputs, x)


test_model = test_create_model()
test_model.save("checkpoints/test_model")
test_model_restore = tf.keras.models.load_model("checkpoints/test_model")
```

without sub_test_model, the model save/load will work fine. with the sub model, it will occur the following error.
![image](https://user-images.githubusercontent.com/731496/83344067-e3945f00-a334-11ea-813d-7819e99a7db9.png)

**Comment by ravikyram** [comment]
@w19787 

Can you please try with TF 2.2 .I am not seeing any issue with TF version 2.2.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/c9beebb86c45ef7bcb9f4df1eef40d91/untitled938.ipynb).Thanks!

**Comment by w19787** [comment]
> @w19787
> 
> Can you please try with TF 2.2 .I am not seeing any issue with TF version 2.2.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/c9beebb86c45ef7bcb9f4df1eef40d91/untitled938.ipynb).Thanks!

yeap, it works on TF 2.2.0. thanks. i will close this issue.
