### ISSUE TITLE
Ignoring gpu device with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#4002]
I build TF with: 
```
TF_UNOFFICIAL_SETTING=1
TF_CUDA_COMPUTE_CAPABILITIES=3.0
```
which used to work but within the last few days I now get:
```
Ignoring gpu device (device: 0, name: GRID K520, pci bus id: 0000:00:03.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
```

I wonder if this got broken with: https://github.com/tensorflow/tensorflow/commit/353235e0b2b35f3df43f42ef84ca00ccda7a3a6d

**Comment by cancan101** [comment]
Perhaps I now need `CUDA_COMPUTE_CAPABILITIES=3.0` ?

**Comment by lcwyylcwyy** [comment]
you can use cudnn 4.0,

**Comment by cancan101** [comment]
The issue is that the env flag changed.

**Comment by davidzchen** [comment]
From the discussion in #3269, it appears that the `bazel fetch` command ran by the `configure` script used the correct CUDA compute capabilities but the values are somehow changed when running `bazel build`.

**Comment by flx42** [comment]
@davidzchen @vrv Great! Can we get it cherry-picked into r0.10?
Thanks!

**Comment by vrv** [comment]
Yeah, there are a few things I need to cherry-pick into r0.10 today, so I'll try to get to it.

**Comment by davidzchen** [comment]
@cancan101 @flx42 - To confirm, did this patch fix this issue for you?

**Comment by vrv** [comment]
I assumed you already verified before merging :(.

**Comment by flx42** [comment]
Looks fine for me.

**Comment by davidzchen** [comment]
@vrv This patch works on my end, and was a needed cleanup change in any case. I wanted to be sure in case there were any issues involving Bazel re-fetching, which I recall running into at one point.
