### ISSUE TITLE
Tensorflow after built from source in High Sierra won't import in Jupyter notebook

### ISSUE THREAD

**Issue by thanoscs** [tensorflow/tensorflow#40028]
Hello and i would to apologise if this is not the right place to ask the question i have but it is my first time writing to ask for help.

Getting to my question, i built tensorflow from source in my macbook pro (mid 10) which is running on High Sierra 10.13.6. After installing tensorflow it imports without problems in python from terminal but when i open jupyter notebook and i try to import it from there it does not recognise tensorflow giving the impression as it was never installed. I looked it up before asking here and with sys.executable notebook and python use the same executables. 

An odd but interesting thing is that when i create a jupyter .ipynb file in the "/Users/mac" directory where tensorflow directory lies after source installation it loads tensorflow without problems.Elsewhere when creating a .ipynb in my laptop, tensorflow does not import.

Finally the "tf.__ version __ " won't show me my tensorflow version nowhere not even when i import it througth the terminal.

Thank you in advance for your answers.

**Comment by amahendrakar** [comment]
@thanoscs,
Could you please double check if you have built and installed TensorFlow as per [this document](https://www.tensorflow.org/install/source#install_the_package).

Also, make sure both the terminal and Jupyter notebook are using the same Python environment. Thanks!

**Comment by thanoscs** [comment]
> @thanoscs,
> Could you please double check if you have built and installed TensorFlow as per [this document](https://www.tensorflow.org/install/source#install_the_package).
> 
> Also, make sure both the terminal and Jupyter notebook are using the same Python environment. Thanks!


hi and thanks for the answer,

I rebuilt it and when i insert this command "bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
" after ./configure  it pops me these errors


![Screen Shot 2020-06-02 at 13 33 03](https://user-images.githubusercontent.com/33914304/83510407-a3201700-a4d5-11ea-8c77-07f8bc569142.png)

I should add that my cpu does not has AVX instructions and this is the reason that i am building it from source.

**Comment by ymodak** [comment]
Did you install Jupyter in the TensorFlow environment?

**Comment by thanoscs** [comment]
It's not an environment as i understand when you build it from source but a directory. Am i mistaken?

**Comment by thanoscs** [comment]
> Did you install Jupyter in the TensorFlow environment?

It's not an environment as i understand when you build it from source but a directory. Am i mistaken?

**Comment by ymodak** [comment]
Apologies for the delay in response. You may try raising this issue on [jupyter notebook repo](https://github.com/jupyter/notebook/issues)

**Comment by thanoscs** [comment]
> Apologies for the delay in response. You may try raising this issue on [jupyter notebook repo](https://github.com/jupyter/notebook/issues)

Ok thanks for your answer, i will raise it there too.
