### ISSUE TITLE
why pd  converted to cpkt, pd model detection effect is poor, nothing can be detected

### ISSUE THREAD

**Issue by DENESTY** [tensorflow/tensorflow#40022]

**Comment by amahendrakar** [comment]
@DENESTY,
In order to expedite the trouble-shooting process, could you please fill in the issue template along with the complete code to reproduce the issue reported here and the TensorFlow version you are using. Thanks!

**Comment by DENESTY** [comment]
> @DENESTY,
> In order to expedite the trouble-shooting process, could you please fill in the issue template along with the complete code to reproduce the issue reported here and the TensorFlow version you are using. Thanks!
sorry,Expression error,i have trained ssd-mobilenetv2-coco in tensorflow object detection api with my dataset .  During training，through he tensorboard ,i found the image can be detected. Then  i use export_inference_graph.py to convert ckpt to pd .but when i use (frozen inference graph pb) to detection.The detection result is very poor very very  bad compared to that i saw in tensorboard. I use tensorflow-gpu==1.13. What shall I do? very thanks

**Comment by DENESTY** [comment]
@amahendrakar 
sorry,expression error. I have train ssd-mobilenetv2 in tensorflow object detection api with my dataset.During training,i saw the image can be detection through the tensorboard.Then i use export_inference_graph.py to convert ckpt to pd .But when i use frozen_inference_graph.pb to detection. the result is very very bad .I use tensorflow-gpu==1.13.very thanks
