### ISSUE TITLE
Customizing what happens in fit()

### ISSUE THREAD

**Issue by labusi** [tensorflow/tensorflow#40041]
I read the guide document of keras, and run codes of 'Customizing what happens in fit() -> Going lower-level', just copy code on the guide and run it, but I get this error message:

"ValueError: The model cannot be compiled because it has no loss to optimize."

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): manjaro
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0 cpu
- Python version: 3.7

**Describe the current behavior**
I run code copied from here "https://keras.io/guides/customizing_what_happens_in_fit/#going-lowerlevel"

**Describe the expected behavior**
According to the doc, I can just skip passing loss function when I call model.compile, but it does not work, It seems like when I call model.fit, the overrided method "train_step" is not called.

**Comment by Saduf2019** [comment]
@labusi 
Please share simple stand alone code to replicate the issue faced or if possible share a colab gist to analyse the error faced.

**Comment by labusi** [comment]
@Saduf2019 
'https://github.com/labusi/tfbugs/blob/master/01_train_step.ipynb'
Here is the stand alone code that replicates the issue. By the way both tf2.0.0 and tf2.1.0 have this issue, but it works well in tf2.2.0

**Comment by Saduf2019** [comment]
I am able to replicate this issue , please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/8b95f953d32dd8c74c13406460210eb6/untitled214.ipynb)

**Comment by labusi** [comment]
@Saduf2019 Ok, thank you, hope that this issue will be fixed soon

**Comment by ymodak** [comment]
This [guide]([url](https://github.com/keras-team/keras-io/blob/master/guides/customizing_what_happens_in_fit.py)) was published in TF 2.2 dev cycle.
Therefore it works with TF 2.2 onwards. TF 2.1 was released in early January which is much older than recently released TF 2.2

**Comment by labusi** [comment]
Yes, I konw this, and I am using TF2.2 now, but it's still an issue for people who have not upgrade to TF 2.2, right? Should I close this issue?

**Comment by ckyleda** [comment]
So what is the solution for those of us forced to backport code from 2.2+ to 2.1.2 ?

**Comment by bwolfson97** [comment]
The same error still occurs in TF 2.4 when one turns off eager mode using `tf.compat.v1.disable_eager_execution()`. The error being:
```
ValueError: The model cannot be compiled because it has no loss to optimize.
```

This can be fixed by passing the loss function to `compile` and then using `self.compiled_loss` to compute the loss, as done in the "A first simple example" part of this tutorial.

See this [notebook](https://colab.research.google.com/gist/bwolfson97/72ffa724d990ec82b0c9f00272cd7f33/untitled214.ipynb) for an example.

**Comment by tomoleary** [comment]
> The same error still occurs in TF 2.4 when one turns off eager mode using `tf.compat.v1.disable_eager_execution()`. The error being:
> 
> ```
> ValueError: The model cannot be compiled because it has no loss to optimize.
> ```
> 
> This can be fixed by passing the loss function to `compile` and then using `self.compiled_loss` to compute the loss, as done in the "A first simple example" part of this tutorial.
> 
> See this [notebook](https://colab.research.google.com/gist/bwolfson97/72ffa724d990ec82b0c9f00272cd7f33/untitled214.ipynb) for an example.

Are there any workarounds for 2.4 with eager mode off for custom losses like in the keras VAE example?

https://keras.io/examples/generative/vae/
