### ISSUE TITLE
Format issue in `tf.ragged.constant` documentation

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#40052]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/ragged/constant

### Clear description

Format issue. In the "Args" section, format of description of `ragged_rank` is problematic. The default value should be `max(0, K-1-len(inner_shape))`

### Parameters defined

Yes

### Returns defined

Yes

### Raises listed and defined

Yes

**Comment by yongtang** [comment]
The issue was that in docstring `max(0, K - 1 - len(inner_shape))` crossed two lines and doc rendering doesn't work anymore. Created a PR #40057 for the fix.

**Comment by DNXie** [comment]
@yongtang  Thanks!
