### ISSUE TITLE
TF can't access GPU

### ISSUE THREAD

**Issue by Vatsal-Malaviya** [tensorflow/tensorflow#40058]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6
- CUDA/cuDNN version: 10
- GPU model and memory: RTX 2060

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
![image](https://user-images.githubusercontent.com/31595943/83438657-69acc480-a45f-11ea-80a1-5cb3efb584d3.png)

**Describe the expected behavior**
Tensorflow should be able to use GPU, but in the current case it is not able to while pytorch is able in the same scenario

**Comment by ymodak** [comment]
TF 2.1 pre built binary supportas cuda 10.1
Please switch to cuda 10.1 version

**Comment by Vatsal-Malaviya** [comment]
> TF 2.1 pre built binary supportas cuda 10.1
> Please switch to cuda 10.1 version

I am using cuda 10.1, sorry for not being specific earlier

**Comment by ymodak** [comment]
Did you add cuda, cudnn, cupti paths to your environment?
See https://www.tensorflow.org/install/gpu#windows_setup

**Comment by Vatsal-Malaviya** [comment]
I have updated to TF2.2 and the now I am able to see GPU listed
![image](https://user-images.githubusercontent.com/31595943/85055787-c3c9bb80-b1bb-11ea-8a53-1386949ee281.png)

**Comment by Vatsal-Malaviya** [comment]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6
- CUDA/cuDNN version: 10
- GPU model and memory: RTX 2060

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`


**Describe the current behavior**
![image](https://user-images.githubusercontent.com/31595943/85893158-f143e400-b80f-11ea-8e3b-b4de746bd50c.png)


**Describe the expected behavior**
Tensorflow should be able to use GPU, but in the current case it is not able to while PyTorch is able in the same scenario 


Now the issue has surfaced again for the newer version of TensorFlow too

**Comment by Vatsal-Malaviya** [comment]
Can anyone explain this irregular behavior with TensorFlow 2.2.0 (installed via pip) with GPU  with cuda 10.1 
![image](https://user-images.githubusercontent.com/31595943/85893857-48968400-b811-11ea-9134-ca260fb29191.png)
![image](https://user-images.githubusercontent.com/31595943/85893886-52b88280-b811-11ea-8b65-64e8bcfdc767.png)
Why is the TensorFlow acknowledging GPU after I test for GPU in the torch
I still can't run my model in GPU, please help !!!
