### ISSUE TITLE
tf.estimator.BoostedTreesClassifier does support multi-classes: AttributeError: 'NoneType' object has no attribute 'is_compatible_with'

### ISSUE THREAD

**Issue by neilteng** [tensorflow/tensorflow#40063]
System information
I am using colab to reproduce the issue and the ipynb is attached below.

You can collect some of this information using our environment capture
tf.version.GIT_VERSION: v2.2.0-0-g2b96f3662b 
tf.version.VERSION:  2.2.0

Describe the current behavior
cannot train tf.estimator.BoostedTreesClassifier on multi-classes data

Describe the expected behavior
Change the last 100 samples' label to a third class in following tutorial:
https://www.tensorflow.org/tutorials/estimator/boosted_trees#train_and_evaluate_the_model

Standalone code to reproduce the issue
https://colab.research.google.com/drive/13vl2mV7C_62HxKCw7-uuMp5WMm_OxYGL?usp=sharing

Other info / logs Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

error is show in the last cell of the colab notebook.

```
INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpf3g1hc6c
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpf3g1hc6c', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/canned/boosted_trees.py:398: VocabularyListCategoricalColumn._num_buckets (from tensorflow.python.feature_column.feature_column_v2) is deprecated and will be removed in a future version.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
INFO:tensorflow:Calling model_fn.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-35-828fa5064808> in <module>()
      8 # The model will stop training once the specified number of trees is built, not
      9 # based on the number of steps.
---> 10 est.train(train_input_fn, max_steps=100)
     11 
     12 # Eval.

13 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/parallel_for/gradients.py in batch_jacobian(output, inp, use_pfor, parallel_iterations)
    111   """
    112   output_shape = output.shape
--> 113   if not output_shape[0].is_compatible_with(inp.shape[0]):
    114     raise ValueError("Need first dimension of output shape (%s) and inp shape "
    115                      "(%s) to match." % (output.shape, inp.shape))

AttributeError: 'NoneType' object has no attribute 'is_compatible_with'
```

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/c27357d1f805ca47a449ebd6d126596e/untitled208.ipynb)

**Comment by jvishnuvardhan** [comment]
@neilteng Do we need to change the label for the last 100 samples as mentioned in your description? Does your code is a standalone code that is ready with the above change or we need to manually change the dataset?

> Change the last 100 samples' label to a third class in following tutorial:

**Comment by rsk7** [comment]
@jvishnuvardhan, the standalaone code linked above already changes the label.

**Comment by neilteng** [comment]
> @jvishnuvardhan, the standalaone code linked above already changes the label.

Yes, the code linked has been changed. Thank you rsk7.

**Comment by RonAd-1** [comment]
Hey, I had the same problem with BoostedTreesClassifier model, multi class in TF 2.2.0 (which should be available in this version). Is this has a fix already? When I changed manually the condition to:
if inp.shape[0] != output_shape[0]:
rais ValueError....
Everything seem to work OK. But surely the fix should be done within TF code.

**Comment by tejaslodaya** [comment]
Yes. Facing the same issue.

On tensorflow 2.2.0

**Comment by thomas-vl** [comment]
I've got the same issue on TF 2.2 and 2.3
@RonAd-1 could you share how you have fixed this?

**Comment by RonAd-1** [comment]
I wrote exactly what I did, 
go to the relevant line in the file and change it to what I did. 
But surely it's not a real fix, just did it to check 
if my guess was correct.

**Comment by crawles** [comment]
This was fixed in 

https://github.com/tensorflow/estimator/commit/2a3cf0794da5016bdb92239783e53859ca66c018

**Comment by helinwang** [comment]
I think tf.disable_v2_behavior() fixes the problem too.
