### ISSUE TITLE
Tensorflow S3 read performance improvement

### ISSUE THREAD

**Issue by weiqi1028** [tensorflow/tensorflow#40066]
Hello TF community,

I have a well-tuned input pipeline build using tf.data API. The data is loaded from S3 in TFRecord format. Running one pipeline gives me 7GB/min IO throughput on a p2.8xlarge EC2 instance. If I created two input pipeline instances in two separate processes, the IO throughput is almost doubled. I am thinking if it is possible to create two input pipelines in two processes and feed into one model training process. This will increase the IO throughput significantly.

Is it possible to share TF dataset between processes?

Thanks, Weiqi

**Comment by ravikyram** [comment]
@weiqi1028 

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!
