### ISSUE TITLE
Doc recommends stateful training but the batches are shuffled?

### ISSUE THREAD

**Issue by bjourne** [tensorflow/tensorflow#40067]
I'm reading this tutorial page from the documentation: https://www.tensorflow.org/tutorials/text/text_generation

The GRU layer is stateful so it remembers its state between batches. But the batches are shuffled. Therefore I think the stateful parameter should be `False`.

**Comment by paulis-reece** [comment]
Can I try to work on this?

**Comment by MarkDaoust** [comment]
> Therefore I think the stateful parameter should be False.

+1

> @paulis-reece :  Can I try to work on this?

Yes. Send me a PR on tensorflow_docs.

**Comment by paulis-reece** [comment]
Thanks! However, since I am new to this. I am not sure where the parameter is located.

**Comment by paulis-reece** [comment]
I am currently searching for which parameter this is referring to.

**Comment by MarkDaoust** [comment]
Look for the "stateful=True" line.

**Comment by paulis-reece** [comment]
Okay thanks I will get on it!

**Comment by paulis-reece** [comment]
I changed the GRU stateful to false, should I also change the Test For GRU V2 Layer stateful parameter as well?

**Comment by MarkDaoust** [comment]
No. 

The only file that needs to be changed is:

https://github.com/tensorflow/docs/blob/master/site/en/tutorials/text/text_generation.ipynb

**Comment by Saduf2019** [comment]
@bjourne 
Is this still an issue.

**Comment by MarkDaoust** [comment]
This was resolved by: https://github.com/tensorflow/docs/commit/7f4d0f1780089308106b8ee3336dca24b730d84f
