### ISSUE TITLE
from_dlpack leaking memory

### ISSUE THREAD

**Issue by alecgunny** [tensorflow/tensorflow#40061]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 18.04
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
2.2.0
- Python version:
3.6
- CUDA/cuDNN version:
10.1
- GPU model and memory:
V100 32GB

TensorFlow `from_dlpack` causes permanent decreases in available GPU memory, leading to OOM issues when called iteratively (e.g. for feeding Keras models, see [this example](https://github.com/NVIDIA/NVTabular/blob/master/nvtabular/tf_dataloader.py)). Since the tensor returned by `from_dlpack` points to the original capsule, I would expect the memory to be freed as soon as the capsule (and any of its pointers) are destroyed.

I've reproduced the issue, as well as provided comparisons with PyTorch behavior, in [this repo](https://github.com/alecgunny/tf-dlpack-repro). A basic example, run in the environment defined by the Dockerfile in the linked repo, would be
```
import tensorflow as tf
tf.config.set_logical_device_configuration(
  tf.config.list_physical_devices('GPU')[0],
  [tf.config.LogicalDeviceConfiguration(memory_limit=8192)]
)
from tensorflow.experimental.dlpack import from_dlpack

import numpy as np
import numba
import cudf


def get_free_mem():
  return numba.cuda.current_context().get_memory_info().free


def make_data(to_tf=False):
  df = cudf.DataFrame({'a': np.random.randn(1000000), 'b': np.random.randn(1000000)})
  if to_tf:
    x = {col: from_dlpack(df[col].to_dlpack()) for col in df.columns}

# initialize tf gpu
x = tf.random.normal((1,))

mem_before = get_free_mem()
make_data()
print('CuDF memory delta: {} B'.format(mem_before - get_free_mem()))

mem_before = get_free_mem()
make_data(to_tf=True)
print('CuDF to TensorFlow memory delta: {} B'.format(mem_before - get_free_mem()))
```
The output of which will look something like
```
CuDF memory delta: 0 B
CuDF to TensorFlow memory delta: 16777216 B
```

**Comment by ravikyram** [comment]
@alecgunny 

I am seeing the error message (`ModuleNotFoundError: No module named 'cudf`).Request you to help me with the reproducible code in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by alecgunny** [comment]
Hey @ravikyram , I use cudf because I need a GPU library external to TensorFlow from which to generate data and pass into TF via dlpack, though in theory I can use any GPU library which has dlpack compatibility (e.g. PyTorch). An environment with the appropriate packages can be found in the Dockerfile in the linked repo above.

That said, when you say "our environment," can you elaborate what you mean by that? I can try to get the appropriate packages installed there as well. Would the 2.2.0-gpu dockerhub container work as an appropriate stand-in?

**Comment by ravikyram** [comment]
@alecgunny 

Please, help me in reproducing the issue .Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/5a4b18dd41c2635781fe5b0adb4fae2e/untitled945.ipynb).Thanks!

**Comment by alecgunny** [comment]
@ravikyram [Here](https://colab.research.google.com/drive/1HmXq9JW9-zea2diQLGolr63m7T2LwfQV#scrollTo=dPizKdTSCzgY)'s a working repro notebook (switched to using PyTorch to simplify the environment, but the idea is the same)

**Comment by ravikyram** [comment]
@alecgunny 

Please grant me the access for the gist provided. Thanks!

**Comment by alecgunny** [comment]
@ravikyram sorry about that! Permissions should be public now
