### ISSUE TITLE
Concatenate ReLU and Batch Norm error

### ISSUE THREAD

**Issue by abhishekthanki** [tensorflow/tensorflow#40076]
**System information**
- Have I written custom code that uses Tensorflow's cReLU function:

```
...
x = tf.keras.layers.Conv2D(32, (3, 3), padding="same")(inputs)
x = tf.keras.layers.Activation("relu")(x)
x = tf.keras.layers.BatchNormalization(axis=chanDim)(x)
x = tf.keras.layers.Conv2D(32, (3, 3), padding="same")(x)
x = tf.keras.layers.Lambda(lambda t: tf.nn.crelu(x))(x)
x = tf.keras.layers.BatchNormalization(axis=chanDim)(x)
x = tf.keras.layers.MaxPooling2D(pool_size=(2, 2))(x)
x = tf.keras.layers.Dropout(0.25)(x)
...
```
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6.9
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.1 / 7.6.5
- GPU model and memory: RTX 2070 Super (8 GB)

**Describe the current behavior**

I get the following error:

```
...
ValueError: Input 0 of layer batch_normalization_1 is incompatible with the layer: expected ndim=4, found ndim=2. Full shape received: [None, 20]
```

**Describe the expected behavior**

There was no error in Tensorflow 1.X.

**Standalone code to reproduce the issue**

`zip` containing the source code: https://www.dropbox.com/s/65q937qqqqa8x8d/keras-vs-tensorflow.zip?dl=0

**Question**

It seems there is difference in either cReLU or Batch Norm implementation in Tensorflow 2.X compared to Tensorflow 1.X. Can someone point out what the change is so I can modify my code?

**Comment by Saduf2019** [comment]
@abhishekthanki 
Please share simple standalone code such that we can replicate the issue faced or if possible share a colab gist with the error faced.

**Comment by abhishekthanki** [comment]
@Saduf2019 I have provided a link to the `zip` that contains the code I'm using and you can use it to replicate it on your machine.

**Comment by abhishekthanki** [comment]
@gowthamkpr Any update on this issue?

**Comment by gowthamkpr** [comment]
@abhishekthanki I am not able to reproduce this. Please share a colab gist so that we can reproduce this issue. Thanks!

**Comment by abhishekthanki** [comment]
@gowthamkpr I'm sharing two colab notebooks, one with TF 1.15 and another with TF 2.2. The code is exactly the same but I'm getting a error in TF 2.2 while there is no such error in TF 1.15. Here are the links to the colab notebooks:

1. TF 1.15: https://colab.research.google.com/drive/10Rc3z2lgW4Xk1BbP0W2toStZ3HjPjGlJ?usp=sharing
2. TF 2.2: https://colab.research.google.com/drive/1XXYYwXG7iWtwpVawqPL0SLrkA7dwTdYV?usp=sharing

**Comment by abhishekthanki** [comment]
@omalleyt12 Just following up on this issue. Did you get a chance to take a look at it?

**Comment by sayakpaul** [comment]
Any updates here? It's been quite a while.

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue in TF 2.5 as well. Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
