### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: input depth must be evenly divisible by filter depth: 544 vs 96 [Op:Conv2D]

### ISSUE THREAD

**Issue by benedives47** [tensorflow/tensorflow#40078]
Does anyone ever experience like this? Please give enlightenment, thank you
"tensorflow.python.framework.errors_impl.InvalidArgumentError: input depth must be evenly divisible by filter depth: 544 vs 96 [Op:Conv2D]"
![1](https://user-images.githubusercontent.com/58981061/83502393-b211c400-a4eb-11ea-8b0c-891c664ac43d.PNG)

**Comment by amahendrakar** [comment]
@benedives47,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and the TensorFlow version you are using. 

Also, please take a look at [#28777](https://github.com/tensorflow/tensorflow/issues/28777) and [this](https://stackoverflow.com/a/60212961) similar StackOverflow query. Thanks!

**Comment by benedives47** [comment]
TF : 2.0
source code:
    conv2_block2_0_bn = model.get_layer('conv2_block2_0_bn')(conv2_block1_concat)
    conv2_block2_0_bn = tf.Variable(conv2_block2_0_bn)
    conv2_block2_0_relu = model.get_layer('conv2_block2_0_relu')(conv2_block2_0_bn)
    conv2_block2_0_relu = tf.Variable(conv2_block2_0_relu)
    conv2_block2_1_conv = model.get_layer('conv2_block2_1_conv')(conv2_block2_0_relu)
    conv2_block2_1_conv = tf.Variable(conv2_block2_1_conv)
    conv2_block2_1_bn = model.get_layer('conv2_block2_1_bn')(conv2_block2_1_conv)
    conv2_block2_1_bn = tf.Variable(conv2_block2_1_bn)
    conv2_block2_1_relu = model.get_layer('conv2_block2_1_relu')(conv2_block2_1_bn)
    conv2_block2_1_relu = tf.Variable(conv2_block2_1_relu)
    conv2_block2_2_conv = model.get_layer('conv2_block2_2_conv')(conv2_block2_1_relu)
    conv2_block2_2_conv = tf.Variable(conv2_block2_2_conv)
    X=concatenate([conv2_block2_0_bn, conv2_block2_0_relu, conv2_block2_1_conv, conv2_block2_1_bn, conv2_block2_1_relu, conv2_block2_2_conv])
    conv2_block2_concat= tf.Variable(X)

**Comment by amahendrakar** [comment]
@benedives47,
On running the code I'm facing an error stating `NameError: name 'model' is not defined`. 

Could you please provide the complete code to reproduce the issue. Thanks!

**Comment by benedives47** [comment]
input this code : 
from tensorflow.keras.models import load_model
model=load_model('models_that_have_been_trained.h5')

**Comment by amahendrakar** [comment]
@benedives47,
I am facing an error stating `ValueError: No such layer: conv2_block2_0_bn` on running the code with a sample `h5` file. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/771b9eae34aaed3496ace560dd09b629/40078.ipynb#scrollTo=_PXLisD1am_u).

Could you please share the complete code or the `.py` file you are running along with all the supporting files. Thanks!

**Comment by benedives47** [comment]
you have "model.summary()". because to see the layer name in your model. What model are you wearing?

**Comment by amahendrakar** [comment]
@benedives47,
Please check [this gist](https://colab.research.google.com/gist/amahendrakar/c594d2ca090be93c62a73e6a4c3f1e60/40078.ipynb) for the sample `h5` model I am using.

In order to reproduce the error, please share the complete code and all the supporting files you are using in the code. Thanks!
