### ISSUE TITLE
Request for TF example  "DeepMind : Teaching Machines to Read and Comprehend" 

### ISSUE THREAD

**Issue by sun9700** [tensorflow/tensorflow#4007]
Deepmind's paper:Teaching Machines to Read and Comprehend
[http://arxiv.org/pdf/1506.03340v3.pdf](url)
 will be a good example for RNN with **attention**. 
However, an unofficial Tensorflow implementation has been suspended over 7 months.
[https://github.com/carpedm20/attentive-reader-tensorflow](url)

Other theano implementations do not demonstrate how to visualize the attention weight:
[https://github.com/thomasmesnard/DeepMind-Teaching-Machines-to-Read-and-Comprehend](url)
[https://github.com/adbrebs/rnn_reader](url)

**Comment by prb12** [comment]
This is a general usage question best suited for StackOverflow.  Please re-ask your question there.
