### ISSUE TITLE
Tensorflow Lite GPU delegate using C++ thread detach on Galaxy Tab S6 is 2.5x slower than without a thread detach

### ISSUE THREAD

**Issue by lackhole** [tensorflow/tensorflow#40075]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.15 / Android 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy Tab S6
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.2
- Python version:
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): Apple clang version 11.0.3 (clang-1103.0.32.59)
- CUDA/cuDNN version:
- GPU model and memory: Adreno 640 / 128GB 6GB RAM, 256GB 8GB RAM

**Describe the current behavior**
I'm running a Tensorflow Lite model with C++ in Android devices.
But when I run a model with GPU delegate with C++ std::thread(s) in Galaxy Tab S6, it becomes 
slower than without using std::thread.
It happens when just using a thread, even if it's number is just 1.
But without a thread, everything works fine.

With the very same code, no such behavior is happening in other devices, such as Galaxy Tab S5, Galaxy Fold, Oppo FindX, and other Android devices.
But only in Galaxy Tab S6, using std::thread with GPU delegate is slower than without using a thread(13ms -> 30ms).
Creating a model and running a model is called from the same thread.
Tensorflow Lite libraries, C++ native codes, Java code is same in all devices.

**Describe the expected behavior**
Same inference time when with or without thread(s).

**Standalone code to reproduce the issue**
Since the model I'm using is the company's model, I can't provide the model's data. 
So I created a simple test app repository at here(it's not working since the model is absent): https://github.com/lackhole/hellovmex

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

### C/C++ Function call profiling
![No thread](https://user-images.githubusercontent.com/35574936/83500301-8a295d00-a4f9-11ea-83ee-3206b0ab7885.png)
 * Without using std::thread and run on main thread.

![Thread](https://user-images.githubusercontent.com/35574936/83500318-8f86a780-a4f9-11ea-83bd-498e92a200fd.png)
 * With using 2 detached std::thread

If any additional information is needed, please let me know.

**Comment by lackhole** [comment]
+ 
Works well if not detaching and using join.
Speed drops only when using thread detaching

**Comment by sushreebarsa** [comment]
@lackhole TF v2.2 is not actively supported, we recommend you to use TF v2.4 or later versions.Could you please try on the latest TF v2.9.0 and let us know if the issue still persists?
Thank you!

**Comment by impjdi** [comment]
One thing I wanted to mention before we close the bug is that we cut corners and rely on undefined behavior in certain cases.  If device-specific bug, there's a chance that this is not working out.  As OpenGL is not relying on those features, I would try enforcing OpenGL for that particular device.
