### ISSUE TITLE
RNN unrolled, cannot be converted using from_keras_model

### ISSUE THREAD

**Issue by SaoirseARM** [tensorflow/tensorflow#40083]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): tf-nightly
- TensorFlow version (or github SHA if from source):
-  version is 2.2.0.dev20200508, git version is v1.12.1-31489-g6047d50555

**Describe the current behavior**
Conversion fails with the following:
```
ValueError: Cannot unroll a RNN if the time dimension is undefined.
- If using a Sequential model, specify the time dimension by passing an `input_shape` or `batch_input_shape` argument to your first layer. If your first layer is an Embedding, you can also use the `input_length` argument.
- If using the functional API, specify the time dimension by passing a `shape` or `batch_shape` argument to your Input layer.
```
This seems to be due to the following addition to the from_keras_model conversion: 
```
self._keras_model.save(temp_dir, save_format="tf")
```

**Describe the expected behavior**
Conversion should succeed as it did before in previous versions.

**Standalone code to reproduce the issue**
```
import numpy as np
import tensorflow as tf

from tensorflow.keras.models import Model

class SimpleModel(Model):
    def __init__(self):
        super().__init__()
        self.model_name = "mnist"
        self.train_data = None
        self.test_data = None
        self.calib_data = None
        self.num_calib = 1000
        # (data preprocessing) Normalize the input image so that
        # each pixel value is between 0 to 1.
        self.pre_process = lambda x: x / 255.0

        self._load_data()

    def _load_data(self):
        # Load MNIST dataset
        mnist = tf.keras.datasets.mnist

        # _data: (images, labels)
        self.train_data, self.test_data = mnist.load_data()
        self.calib_data = self.pre_process(
            self.train_data[0][0 : self.num_calib].astype(np.float32)
        )

    def train(self):
        cell = tf.keras.layers.GRUCell(3)

        model = tf.keras.models.Sequential([
            tf.keras.layers.Input(shape=(28, 28), name='input'),
            #tf.keras.layers.LSTM(32),
            tf.keras.layers.RNN(cell, unroll=True),
            tf.keras.layers.Flatten(),
            tf.keras.layers.Dense(10, activation=tf.nn.softmax, name='output')
        ])
        model.summary()

        train_images = self.pre_process(self.train_data[0])
        train_labels = self.train_data[1]
        test_images = self.pre_process(self.test_data[0])
        test_labels = self.test_data[1]
        # Train the digit classification model
        model.compile(
            optimizer="adam",
            loss="sparse_categorical_crossentropy",
            metrics=["accuracy"],
        )
        model.fit(
            train_images,
            train_labels,
            epochs=1,
            validation_data=(test_images, test_labels),
        )
        # dump SavedModel - ANOTHER BUG HERE!
        #model.save(str(self.savedModel_dir))

        return model

    def eval(self, tflite_model_path: str):
        interpreter = tf.lite.Interpreter(model_path=str(tflite_model_path))
        interpreter.allocate_tensors()

        input_index = interpreter.get_input_details()[0]["index"]
        output_index = interpreter.get_output_details()[0]["index"]

        # (data preprocessing) Normalize the input image so that
        # each pixel value is between 0 to 1.
        test_images = self.pre_process(self.test_data[0])
        test_labels = self.test_data[1]
        # Run predictions on every image in the "test" dataset.
        prediction_digits = []
        for test_image in test_images:
            # Pre-processing: add batch dimension and convert to float32 to match with
            # the model's input data format.
            test_image = np.expand_dims(test_image, axis=0).astype(np.float32)
            interpreter.set_tensor(input_index, test_image)

            # Run inference.
            interpreter.invoke()

            # Post-processing: remove batch dimension and find the digit with highest
            # probability.
            output = interpreter.tensor(output_index)
            digit = np.argmax(output()[0])
            prediction_digits.append(digit)

        # Compare prediction results with ground truth labels to calculate accuracy.
        accurate_count = 0
        for index, _ in enumerate(prediction_digits):
            if prediction_digits[index] == test_labels[index]:
                accurate_count += 1
        accuracy = accurate_count * 1.0 / len(prediction_digits)

        return accuracy

    def _get_calib_data_func(self):
        def representative_data_gen():
            for input_value in self.calib_data:
                input_value = np.expand_dims(input_value, axis=0).astype(np.float32)
                yield [input_value]

        return representative_data_gen


if __name__ == "__main__":
    temp = SimpleModel()
    model = temp.train()

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = temp._get_calib_data_func()

    # save INT8 tflite
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8,
        tf.lite.OpsSet.SELECT_TF_OPS]
    converter.experimental_new_converter = True
    tflite_model_INT8 = converter.convert()
    open("lstm_unrolled_int8.tflite", "wb").write(tflite_model_INT8)

```

**Comment by Saduf2019** [comment]
@SaoirseARM 
I ran the code shared and face invalid syntax, please share complete indented code such that we can replicate the issue.
Please fin the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/430d59df445734d21c37863f0247d7bd/untitled216.ipynb)

**Comment by SaoirseARM** [comment]
Apologies @Saduf2019 , I have updated the comment with syntax error free code.

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/2ecfe7da64972d28285859574bffb33e/untitled216.ipynb) Thanks!

**Comment by SaoirseARM** [comment]
There may be a misunderstanding here, this issue can be seen building from source or from tf-nightly and not in the released tensorflow v2.2.
I have updated the description above. Apologies for the confusion.

**Comment by jdduke** [comment]
@renjie-liu can you take a look?

**Comment by renjie-liu** [comment]
Seems the issue is indeed for keras_model reloading, can you try convert from saved_model instead? see https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/Keras_LSTM_fusion_Codelab.ipynb

meanwhile, Hi Jaesung, can you help take a look about the keras_model import? I supscious it's because keras model serialize/deserialze caused the problem.

thanks!

**Comment by SaoirseARM** [comment]
Thank you, I am actually already using the workaround you suggested above and it works absolutely fine. Thanks for looking into this!

**Comment by renjie-liu** [comment]
Great!

**Comment by psunn** [comment]
Hi @renjie-liu, with the example you pointed. I tried some quantization experiments, seems:

   for dynamic range quantization, weights within RNN still FP32;
   for fully integer quantization, currently failed with a runtime error:
```RuntimeError: tensorflow/lite/kernels/unidirectional_sequence_lstm.cc:349 input_to_output_weights->dims->data[1] != n_input (28 != 0)Node number 0 (UNIDIRECTIONAL_SEQUENCE_LSTM) failed to prepare.```

[Colab example](https://colab.research.google.com/drive/1pF0bjfj19r2bN0H49J-8l4VFT4Vx60_i?usp=sharing)

**Comment by renjie-liu** [comment]
fully integer quantization is not done yet. 

but the dynamic range quantization should work, can you share any code snippet?

thanks!

**Comment by SaoirseARM** [comment]
This is no longer an issue in tensorflow-2.4.1. Thanks! Closing issue.

**Comment by kassianl26** [comment]
> Hi @renjie-liu, with the example you pointed. I tried some quantization experiments, seems:
> 
> for dynamic range quantization, weights within RNN still FP32;
> for fully integer quantization, currently failed with a runtime error:
> `RuntimeError: tensorflow/lite/kernels/unidirectional_sequence_lstm.cc:349 input_to_output_weights->dims->data[1] != n_input (28 != 0)Node number 0 (UNIDIRECTIONAL_SEQUENCE_LSTM) failed to prepare.`
> 
> [Colab example](https://colab.research.google.com/drive/1pF0bjfj19r2bN0H49J-8l4VFT4Vx60_i?usp=sharing)

I have the same error with Tensorflow-2.5.0 (MNIST_LSTM -> fully integer quantization)
RuntimeError: tensorflow/lite/kernels/unidirectional_sequence_lstm.cc:895 input_to_output_weights->dims->data[1] != n_input (28 != 528)Node number 0 (UNIDIRECTIONAL_SEQUENCE_LSTM) failed to prepare

**Comment by abattery** [comment]
@kassianl26 please upload a new issue with more reproducible information instead of commenting on the closed issue.
