### ISSUE TITLE
micro_speech train example broken

### ISSUE THREAD

**Issue by envy1400** [tensorflow/tensorflow#40087]
@tensorflow/micro

**System information**
- Windows 10
- tensorflow 1.x
- Arduino Nano 33

The training portion of the micro_speech example appears to be broken.  The only modification I have made is to train for the words "up,down,on,off" instead of "yes,no".  I ran all of the code cells except for the code cell that skips the training.  The following code cell generates an error:

with tf.Session() as sess:
  float_converter = tf.lite.TFLiteConverter.from_saved_model(SAVED_MODEL)
  float_tflite_model = float_converter.convert()
  float_tflite_model_size = open(FLOAT_MODEL_TFLITE, "wb").write(float_tflite_model)
  print("Float model is %d bytes" % float_tflite_model_size)

  converter = tf.lite.TFLiteConverter.from_saved_model(SAVED_MODEL)
  converter.optimizations = [tf.lite.Optimize.DEFAULT]
  converter.inference_input_type = tf.lite.constants.INT8
  converter.inference_output_type = tf.lite.constants.INT8
  def representative_dataset_gen():
    for i in range(100):
      data, _ = audio_processor.get_data(1, i*1, model_settings,
                                         BACKGROUND_FREQUENCY, 
                                         BACKGROUND_VOLUME_RANGE,
                                         TIME_SHIFT_MS,
                                         'testing',
                                         sess)
      flattened_data = np.array(data.flatten(), dtype=np.float32).reshape(1, 1960)
      yield [flattened_data]
  converter.representative_dataset = representative_dataset_gen
  tflite_model = converter.convert()
  tflite_model_size = open(MODEL_TFLITE, "wb").write(tflite_model)
  print("Quantized model is %d bytes" % tflite_model_size)

Error generated below:

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1364     try:
-> 1365       return fn(*args)
   1366     except errors.OpError as e:

11 frames
InvalidArgumentError: You must feed a value for placeholder tensor 'data/background_data' with dtype float and shape [16000,1]
	 [[{{node data/background_data}}]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1382                     '\nsession_config.graph_options.rewrite_options.'
   1383                     'disable_meta_optimizer = True')
-> 1384       raise type(e)(node_def, op, message)
   1385 
   1386   def _extend_graph(self):

InvalidArgumentError: You must feed a value for placeholder tensor 'data/background_data' with dtype float and shape [16000,1]
	 [[node data/background_data (defined at /tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py:1748) ]]

**Comment by jvishnuvardhan** [comment]
@envy1400 Can you please check [this similar issue](https://github.com/tensorflow/tensorflow/issues/38684) and let us know whether it helped or not? Thanks!

**Comment by envy1400** [comment]
The link to a google colab page in there seemed to work.  I don't know how it's different or if it's been updated.  I guess this is resolved

**Comment by jvishnuvardhan** [comment]
@envy1400 Yes, that colab was updated recently. 
I am closing this issue as you confirmed that this was resolved. But, feel free to reopen if this persists again later. Thanks!
