### ISSUE TITLE
Prediction failed: Could not import PIL.Image. The use of `load_img` requires PIL.

### ISSUE THREAD

**Issue by miohana** [tensorflow/tensorflow#40096]
While using Custom Prediction Routine, I've received the following error according to Logs Viewer in console:

`Prediction failed: Could not import PIL.Image. The use of 'load_img' requires PIL.
`
- TensorFlow version: `1.15`
- Python version: `3.7`

setup.py:

```
from setuptools import setup

install_requires=['pillow', 'opencv-python', 'matplotlib']

setup(
name='my_custom_code',
version='0.1',
scripts=['predictor.py'],
install_requires=install_requires
)
```

predictor.py imports:
```
import os
import pandas as pd
import pickle
import cv2
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow.python.lib.io import file_io
from pandas.compat import StringIO
from datetime import datetime
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Model
from PIL import Image
```

I need to use this library because of ImageDataGenerator (part of the predictor.py above):
 ```
# Create ImageDataGenerator for test set
    test_img_gen = ImageDataGenerator(preprocessing_function=self.remove_text,
                                       samplewise_std_normalization=True, samplewise_center=True)
    test_generator = test_img_gen.flow_from_dataframe(dataframe=setup_dict['TEST_SET'],
                                                      directory=setup_dict['RAW_DATA_PATH'],
                                                      x_col="filename", y_col='label_str',
                                                      target_size=tuple(setup_dict['IMG_DIM']), batch_size=1,
                                                      class_mode='categorical', validate_filenames=False, shuffle=False)
```

Command being used to create new versions:
`gcloud beta ai-platform versions create v1   --model MyModel   --runtime-version 1.15   --python-version 3.7   --origin gs://custom-prediction/   --package-uris gs://custom-prediction/my_custom_code-0.1.tar.gz   --prediction-class predictor.MyPredictor`

Can someone help me?

**Comment by amahendrakar** [comment]
@miohana,
Please take a look at [this](https://stackoverflow.com/a/52230898) StackOverflow answer and [this](https://github.com/asataniAIR/Image_DL_Tutorial/issues/4#issuecomment-405046904) similar GitHub issue, and let us know if it works. Thanks!

**Comment by miohana** [comment]
Hi @amahendrakar! Thanks for your reply.

I've seen those two answers before. As I said, I'm already importing pillow in my setup.py.
When adding other libraries, according to [this answer](https://github.com/asataniAIR/Image_DL_Tutorial/issues/4) (adding Keras), I receive the error below:

`Model requires more memory than allowed. please try to decrease the model size and redeploy
`

**Comment by ltung-cit** [comment]
Hi @miohana 

Saw the following dependency declaration from `keras-preprocessing/setup.py`:

```
extras_require={
    'tests': ['pandas',
              'Pillow' if sys.version_info >= (3, 0) else 'pillow',
              ...]
 }, ...
```

Really didn't know what's the difference between `Pillow` and `pillow` but it won't hurt to get a try :)

**Comment by gowthamkpr** [comment]
@miohana Did you deactivate and activate the environment after installing pillow?

**Comment by miohana** [comment]
Hi @ltung-cit!

Unfortunatelly, I've tried to change to Pillow but the error continues.
![image](https://user-images.githubusercontent.com/17110848/84031995-06de9000-a96d-11ea-8b33-3628e1055573.png)

Thanks for the reply! 😄 

@gowthamkpr since we are using Custom Prediction Routine, the environment should deactivate and activate again everytime I create a new version, right?

**Comment by gowthamkpr** [comment]
@miohana Makes sense.. Can I see full log message? Thanks!

**Comment by nikitamaia** [comment]
Are you able to import the other packages in install_requires (like matplotlib)? Or is it just pillow that is causing an error?

**Comment by anshuman20056** [comment]
> Hi @amahendrakar! Thanks for your reply.
> 
> I've seen those two answers before. As I said, I'm already importing pillow in my setup.py.
> 
> ![image](https://user-images.githubusercontent.com/17110848/83631730-5ccdc500-a574-11ea-939d-b97f0137ad12.png)
> 
> When adding other libraries, according to [this answer](https://github.com/asataniAIR/Image_DL_Tutorial/issues/4) (adding Keras), I receive the error below:
> 
> `Model requires more memory than allowed. please try to decrease the model size and redeploy `
> 
> Model settings:
> It's a pretrained resnet101v2 with 491.82MB.

I am also getting the same error. Could you please help me resolving it. Thanks
