### ISSUE TITLE
Tutorial TensorBoard: Visualizing Learning, path error

### ISSUE THREAD

**Issue by NumesSanguis** [tensorflow/tensorflow#401]
In the following tutorial about visualizing TensorBoard is an error: http://www.tensorflow.org/how_tos/summaries_and_tensorboard/index.html

The tutorial says the code to run the visualization of the mnist data is:

    tensorboard --logdir=/tmp/mnist_data

However in the code you provide, you put:

    writer = tf.train.SummaryWriter("/tmp/mnist_logs", sess.graph_def)

mnist_data =/= mnist_logs. The right code is:

    tensorboard --logdir=/tmp/mnist_logs

---
Additionally would it be possible to explain how TensorBoard takes it current path?
For example, if I change `--logdir=/tmp/mnist_logs` to `--logdir=mnist_logs` (to put it in the current directory I'm working in), it correctly makes a new folder `mnist_logs`. However if I run the following code in the current directory:

     tensorboard --logdir=mnist_logs

TensorBoard cannot find the log file. How would I run `tensorboard` from the current directory?

---
On the subject of path clarity, could you add an output which states where TensorBoard looks for the log file? Currently:

    Starting TensorBoard on port 6006
    (You can navigate to http://localhost:6006)

Could you add:

    TensorBoard looks for the log files in: /path/to/folder/
    and found a file / didn't find a file

**Comment by vrv** [comment]
I think https://github.com/tensorflow/tensorflow/pull/337 might have fixed this -- this will be in the next release but you can probably build from sources to get the fix now.

**Comment by pirate** [comment]
@NumesSanguis As well as relative paths being fixed, I believe it now prints the path right before the line `Starting TensorBoard on port 6006` (although I'm not sure when that change was made).
<img width="730" alt="screen shot 2015-12-23 at 2 11 09 pm" src="https://cloud.githubusercontent.com/assets/511499/11983846/bca15cf8-a984-11e5-946d-5291ca41021d.PNG">
