### ISSUE TITLE
`tf.compat.v1.setdiff1d` documentation refers `out_idx` as an argument

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#40104]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/compat/v1/setdiff1d

### Clear description

In the "Args" section, there is an input `out_idx`, but it is not in the signature, and the function doesn't accept the argument.

Running code: 

~~~python
tf.compat.v1.setdiff1d([1],[1],out_idx=tf.dtypes.int32, name=None)
~~~

got exception:

~~~python
TypeError: setdiff1d() got an unexpected keyword argument 'out_idx'
~~~

### Parameters defined

Yes

### Returns defined

Yes

### Raises listed and defined

No

## System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Mojave 10.14
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 2.2.0-rc3
- **Python version**: 3.8.2

**Comment by MarkDaoust** [comment]
That API is clearly marked v1 and deprecated, we're not going to invest more time in it.
