### ISSUE TITLE
[tf.data] preserve_cardinality in map()

### ISSUE THREAD

**Issue by zhuzilin** [tensorflow/tensorflow#40107]
I was wondering the reason of the `preserve_cardinality` argument in `MapDataset` and `ParallelMapDataset`. As far as I can see, the corresponding ops are both implemented with:
```c++
int64 Cardinality() const override { return input_->Cardinality(); }
```
However, in python, we have
```python
  @functools.wraps(DatasetV2.map)
  def map(self, map_func, num_parallel_calls=None, deterministic=None):
    if num_parallel_calls is None:
      return DatasetV1Adapter(
          MapDataset(self, map_func, preserve_cardinality=False))
    else:
      return DatasetV1Adapter(
          ParallelMapDataset(
              self,
              map_func,
              num_parallel_calls,
              deterministic,
              preserve_cardinality=False))
```
Could anyone tell me the purpose of `preserve_cardinality`? And if there are any modification need doing, I'd love to help. Thank you!

**Comment by Saduf2019** [comment]
@zhuzilin 
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by zhuzilin** [comment]
@Saduf2019 
Actually, I'm thinking about making an PR to remove the `preserve_cardinality` of these ops and that is why I asked the question here. And also, this is not an API opened to the user, but rather a parameter configured inside tensorflow, I suppose stackoverflow is more for tensorflow user instead of developer, right?

**Comment by Saduf2019** [comment]
@zhuzilin
It is not clear to me why tis parameter is an issue, when preserve_cardinality is an optional bool. Defaults to False. [its an optional paramater]

**Comment by zhuzilin** [comment]
@Saduf2019 
For me, the question is why the parameter is needed... Especially when the actual implementation will preserve cardinality...

**Comment by aaudiber** [comment]
@zhuzilin `preserve_cardinality` determines what to do when the map function returns an OutOfRange error: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/map_dataset_op.cc#L153-L165

The flag is used internally so that we can support both TF 1.x and TF 2.x behaviors. In TF 1.x, the map function producing OutOfRange would cause the dataset to be truncated at the element producing OutOfRange. In TF 2.x we changed the behavior so that `map` will always have the same cardinality as its input.

**Comment by zhuzilin** [comment]
@aaudiber 
Thank you for your anwser! Could you give me an example of how we can produce OutOfRange error in tf1, the only api I found is `tf.errors.OutOfRangeError` and it doesn't seem like the right one... Also, should we return the cardinality as "unknown" when `preserve_cardinality` is false?

**Comment by aaudiber** [comment]
Here's an example:

```python
import tensorflow.compat.v1 as tf

ds = tf.data.Dataset.range(10)

def map_py_fn(x):
  if x == 3:
    raise StopIteration
  return x

def map_fn(x):
  return tf.py_function(map_py_fn, [x], tf.int64)

ds = ds.map(map_fn)
for elem in ds:
  print(elem.numpy())  # Prints only 0, 1, 2 since we raise StopIteration at 3
```
https://colab.research.google.com/drive/1Uv12BpCohpWseutii3hs31z4iQPBxp3x?usp=sharing

**Comment by aaudiber** [comment]
@zhuzilin You're right, the cardinality should be "unknown" - I think it's a bug. Would you be interested in submitting a fix?

**Comment by zhuzilin** [comment]
@aaudiber I'd love to. :smile:
