### ISSUE TITLE
Unclear type/dimension dependency of `filters` in  `conv1d/3d_transpose` documentation

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#40103]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/nn/conv1d_transpose

https://www.tensorflow.org/api_docs/python/tf/nn/conv3d_transpose

### Clear description

Unclear type and dimension dependency of input `filters`. According to the document, `filters` should have the same type as `value` and the `in_channel` dimension must match that of `value`, but it is unclear what `value` is.

### Parameters defined

Yes

### Returns defined

Yes

### Raises listed and defined

https://www.tensorflow.org/api_docs/python/tf/nn/conv1d_transpose: Yes

https://www.tensorflow.org/api_docs/python/tf/nn/conv3d_transpose:  No, the "Raises" list is not provided or defined

## System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Mojave 10.14
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 2.2.0-rc3
- **Python version**: 3.8.2

**Comment by ymodak** [comment]
`input` is an alias of value here. I will try and update the docs. Thanks!
