### ISSUE TITLE
'os' has no attribute 'errno' when using keras.utils.plot_model

### ISSUE THREAD

**Issue by celsomilne** [tensorflow/tensorflow#40117]
**System information**
- Tensorflow install via pip
- `pydot` version 1.2.3
- `tensorflow` version 2.2.0
- `python` 3.7.7

**Error Details**
When running `tf.keras.utils.plot_model` an error is raised:

```
~\Anaconda3\lib\site-packages\pydot.py in create(self, prog, format)
   1878                 stderr=subprocess.PIPE, stdout=subprocess.PIPE)
   1879         except OSError as e:
-> 1880             if e.errno == os.errno.ENOENT:
   1881                 raise Exception(
   1882                     '"{prog}" not found in path.'.format(

AttributeError: module 'os' has no attribute 'errno'
```

I understand that this error is a problem with `pydot`, but perhaps a `pydot` version bump would fix this problem (most recent `pydot` version is 1.4.*).

**Code to Reproduce**
```python
import tensorflow as tf

model = tf.keras.models.Sequential([
    tf.keras.Input(shape=(512, 512, 1)),
    tf.keras.layers.Conv2D(3, 3),
    tf.keras.layers.MaxPool2D(),
])

tf.keras.utils.plot_model(model)
```

**Comment by amahendrakar** [comment]
@celsomilne,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by celsomilne** [comment]
@amahendrakar 
```
import tensorflow as tf

m = tf.keras.models.Sequential([
    tf.keras.Input(shape=(512, 512, 1)),
    tf.keras.layers.Conv2D(3, 3),
    tf.keras.layers.MaxPool2D(),
])

tf.keras.utils.plot_model(model)
```

**Comment by amahendrakar** [comment]
@celsomilne,
I was able to run the code with TF v2.2 without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/7d15484807d471f73abece2a9f0a220e/40117.ipynb). 

Could you please update TensorFlow to v2.2 and let us know if it works. Thanks!

**Comment by celsomilne** [comment]
@amahendrakar 
Thanks! I updated to TF v2.2, and downgraded `pydot` to 1.3.0 and graphviz to 0.10.1 (as it appears in your Collab) but I'm now getting the (rather unhelpful) message:

`Failed to import pydot. You must install pydot and graphviz for 'pydotprint' to work.`

I've also tried running tensorflow from both windows and a linux VM, with no difference in outcome.

Unfortunately, I can't use Collab for the analysis I'm doing.

**Comment by celsomilne** [comment]
Thanks @amahendrakar. After reading through the issue, I fixed my problem with 
````
sudo apt-get update
sudo apt-get install graphviz
```
I feel that the documentation for `plot_model` should mention the fact the `graphviz` needs to be installed separately (especially for inexperienced users who'd simply assume the `pip install graphviz` is enough). 

What do you think?

**Comment by amahendrakar** [comment]
> I feel that the documentation for `plot_model` should mention the fact the `graphviz` needs to be installed separately (especially for inexperienced users who'd simply assume the `pip install graphviz` is enough).

@celsomilne,
If we take a look at the [source code](https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/keras/utils/vis_utils.py#L28) for `tf.keras.utils.plot_model`, it uses `pydot_ng` or `pydotplus` and if both the packages are not found it then falls back to `pydot`.

If none of these packages are found (including `graphviz`), it throws an [ImportError](https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/keras/utils/vis_utils.py#L110) stating 
`Failed to import pydot. You must install pydot and graphviz for pydotprint to work.`

Hope this clears things up, please feel free to close the issue if resolved. Thanks!
