### ISSUE TITLE
Dynamically added layers do not show up in custom model layers member

### ISSUE THREAD

**Issue by SandeepNaidu** [tensorflow/tensorflow#40110]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Os X 10.15.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I have a custom model https://gist.github.com/SandeepNaidu/d4d9482daa466fa21b22211693bbae82 which is used to create dynamically the architecture in terms of depth and breadth of the network. Even upon adding directly to self.layers it does not show up later when the layers are retrieved. The number of hidden layers and breadth can vary based on experiments. So need a better way to add them to self.layers. 

**Describe the expected behavior**
Ability to add layers dynamically to layers object of Model in custom model

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
https://gist.github.com/SandeepNaidu/d4d9482daa466fa21b22211693bbae82

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2, nightly versions(`2.3.0-dev20200602`) and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/7eac58669bbc68f9abe20f12764c2b37/untitled949.ipynb).Thanks!

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue in TF 2.6 as well. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/df9e145f02310b54f89aadf6112689ef/untitled95.ipynb) for reference.Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
