### ISSUE TITLE
Dynamic libtensorflow-lite for ARM64

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#40126]
I followed [cross-compile for ARM64](https://www.tensorflow.org/lite/guide/build_arm64#cross-compile_for_arm64) and produced a static library `libtensorflow-lite.a`
Is it possible to cross-compile for ARM64 this library as dynamic (shared) *so* version for ARM64 as well?

**Comment by terryheo** [comment]
Could you try this?

```
bazel build -c opt --config=elinux_aarch64 tensorflow/lite:tensorflowlite
```
