### ISSUE TITLE
TFLite Converter not quantizing supported op weights

### ISSUE THREAD

**Issue by aselva-eb** [tensorflow/tensorflow#40129]
**System information**
-Mac OSX
-TF 2.3.0-dev20200602

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
    # From Saved Model
    converter = tf.lite.TFLiteConverter.from_saved_model(curr_dir + "saved_model")
    # converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                           tf.lite.OpsSet.SELECT_TF_OPS]
    tflite_model = converter.convert()

    # Save the TF Lite model.
    with tf.io.gfile.GFile(curr_dir + '/model.tflite', 'wb') as f:
        f.write(tflite_model)
```

Model obtained from Model Zoo
http://download.tensorflow.org/models/object_detection/ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz

Follow-up issue to : https://github.com/tensorflow/tensorflow/issues/40059

Running the above code to generate a tflite file from the pretrained ssdlite_mobilenet model. However I'm suspecting not a whole lot of optimization is happening. The file size for the frozen graph is 19911343 bytes and the optimized tflite model is 18905520 bytes. 

Dissecting the model (using Netron), I can also see that the [supported ops](https://www.tensorflow.org/lite/guide/ops_compatibility) are still using float32 type weights. 

I was hoping to see 2-4x size reduction as a good chunk of the model is conv2d with float32 weights. Any ideas why I'm not able to really optimize this particular model? 

Want to also add:

I modified my conversion code above to avoid use of the experimental flags:
```
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
```
replacing it with a stable-version documented configuration:
```
converter.optimizations = [tf.lite.Optimize.DEFAULT]
```

In this case the conversion fails:
```
error: 'tf.TensorArrayWriteV3' op is neither a custom op nor a flex op
error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
        tf.NonMaxSuppressionV2 {T = f32, T_threshold = f32, device = ""}
        tf.Size {device = ""}
        tf.TensorArrayGatherV3 {device = "", element_shape = #tf.shape<100>}
        tf.TensorArrayGatherV3 {device = "", element_shape = #tf.shape<100x4>}
        tf.TensorArrayGatherV3 {device = "", element_shape = #tf.shape<300x300x3>}
        tf.TensorArrayGatherV3 {device = "", element_shape = #tf.shape<3>}
        tf.TensorArrayGatherV3 {device = "", element_shape = #tf.shape<>}
        tf.TensorArrayReadV3 {device = ""}
        tf.TensorArrayScatterV3 {device = ""}
        tf.TensorArraySizeV3 {device = ""}
        tf.TensorArrayV3 {clear_after_read = true, device = "", dtype = f32, dynamic_size = false, element_shape = #tf.shape<*>, identical_element_shapes = false, tensor_array_name = ""}
        tf.TensorArrayV3 {clear_after_read = true, device = "", dtype = i32, dynamic_size = false, element_shape = #tf.shape<*>, identical_element_shapes = false, tensor_array_name = ""}
        tf.TensorArrayWriteV3 {device = ""}
```

**Comment by aselva-eb** [comment]
I can also see another ticket related to this that was closed

https://github.com/tensorflow/tensorflow/issues/38104

**Comment by aselva-eb** [comment]
For anyone else following this thread:
was able to address this by having both `converter.optimizations` set **and** the experimental `converter.target_spec.supported_ops` defined to accept both ops. 

Both alone won't do the trick. Without the converter.optimization flag it will simply convert the frozen graph to a float tflite file. But without enabling both tflite ops and tf native ops, more complex models cannot be converted. (This last feature to select op type is still experimental though)

**Comment by aselva-eb** [comment]
As feedback to the TF team, documentation could be improved to clarify that simply converting to a tflite model you cannot expect any default optimizations.  Further, these optimization flags should be better documented or referred to.

Thanks

**Comment by jvishnuvardhan** [comment]
@aselva-eb Is this still an issue for you? 

I ran your code and I can see the reduction in file size (4 times with OPTIMIZE_DEFAULT for size) and 2 x smaller with FLOAT16 TF_Lite model. [Here](https://colab.research.google.com/gist/jvishnuvardhan/d89b000adca26c3eb684e0376c84010e/untitled1100.ipynb) is a gist for a reference. Thanks!

There are other models (such as full integer model) described in TF Lite tutorial https://www.tensorflow.org/lite/performance/post_training_quantization
