### ISSUE TITLE
Hierarchical display for TensorBoard

### ISSUE THREAD

**Issue by alexcoca** [tensorflow/tensorflow#40127]
**System information**
- TensorFlow version (you are using): 2.1
- Are you willing to contribute it (Yes/No): Not a frontend guy so I don't know if I can help.

**Describe the feature and the current behavior/state.**
I'm using TensorBoard to display an optimisation process with two stages, `lambda_sweep` and `counterfactual_search`, so I used the `name` argument to the summary ops to display the plots for the two stages separtely:

![image](https://user-images.githubusercontent.com/30216068/83668596-1e61f580-a5c8-11ea-9fb8-5199c97b3012.png)

I would like this behaviour to be hierarchical, that is, other drop-downs would appear when clicking one of the stages. Instead, I get the follwing:

![image](https://user-images.githubusercontent.com/30216068/83669076-df806f80-a5c8-11ea-9828-866bcb4d2071.png)

I was wondering if there is any way to extend the first level logic so that, for example, under `counterfactual_search` I get another page I can click on that is called `lambda`  and so on.

**Will this change the current api? How?**
I don't think so, it sounds more like a frontnend feature to me?
**Who will benefit with this feature?**
All tensorboard users.

**Any Other info.**

**Comment by amahendrakar** [comment]
@alexcoca,
Since TensorBoard issues are tracked in the TensorBoard repo. Could you please submit a feature request from [this link](https://github.com/tensorflow/tensorboard/issues/new/choose), so that we can track it there. Thanks!

**Comment by alexcoca** [comment]
> 
> 
> @alexcoca,
> Since TensorBoard issues are tracked in the TensorBoard repo. Could you please submit a feature request from [this link](https://github.com/tensorflow/tensorboard/issues/new/choose), so that we can track it there. Thanks!

Hi @amahendrakar,

Thank you for getting back. I will request at the link indicated and close this issue!

Alex
