### ISSUE TITLE
Cross-compile the label_image with ARM64 libtensorflow-lite.a

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#40124]
I cross-compiled the TensorFlow Lite static library for ARM64-based computer and I'd like to build the label_image example for that target as well. To build label_image, it should run this command `bazel build tensorflow/examples/label_image/...` How should I set it to use that already built static library and cross-compile for ARM64-based target?

Thank you for your advice.

**Comment by terryheo** [comment]
You can build label_image with Makefile.
Please check 56cea6e30cdec9a12832def2ad97634101d8c784
```
./tensorflow/lite/tools/make/build_aarch64_lib.sh label_image
```
