### ISSUE TITLE
Add favicon to TensorBoard

### ISSUE THREAD

**Issue by grovina** [tensorflow/tensorflow#4012]
Adding `favicon.ico` (TensorFlow's, I imagine) would avoid the following warning on launch and beautify TensorBoard. ;)

`WARNING:tensorflow:IOError [Errno 2] No such file or directory: '.../tensorflow/tensorboard/favicon.ico' on path .../tensorflow/tensorboard/favicon.ico`

**Comment by drpngx** [comment]
That would be nice, if you could contribute one.

**Comment by grovina** [comment]
Actually, the following datauri favicon was added by e42fa0069.
![download](https://cloud.githubusercontent.com/assets/6004563/22270119/5030c808-e275-11e6-8fc8-e83cbbef104c.png)
