### ISSUE TITLE
Can contrib_audio.mfcc has gardient ?

### ISSUE THREAD

**Issue by winterwindwang** [tensorflow/tensorflow#40135]
tensorflow version:1.14
python:3.6
I need to used operation(mfcc) in `tensorflow.python.ops import gen_audio_ops as contrib_audio` to extract mfcc feature from an audio, then compute the gradient for this audio. But I got error `LookupError: No gradient defined for operation 'mfcc' (op type: Mfcc)`. This operation can not via gradient? If not, how can I fix this error?

**Comment by jvishnuvardhan** [comment]
@winterwindwang Can you please provide a standalone code to reproduce issue. Thanks!
