### ISSUE TITLE
different types of GPUs

### ISSUE THREAD

**Issue by fayeshine** [tensorflow/tensorflow#4013]
I have 4 GPUS, which are
gpu0, GTX 1080
gpu1, old TITAN X
gpu2, old TITAN X
gpu3, GTX 1080
when I run a CNN, it shows the information below, what does `cannot enable peer access from device ordinal 0 to device ordinal 1` mean?
Does it mean that I cannot use multiple GPUs since they are not identical(I noticed that I only have one gpu running during the training)?
What is the consequence of this info?

```
I tensorflow/core/common_runtime/gpu/gpu_init.cc:61] cannot enable peer access from device ordinal 0 to device ordinal 1
I tensorflow/core/common_runtime/gpu/gpu_init.cc:61] cannot enable peer access from device ordinal 0 to device ordinal 2
I tensorflow/core/common_runtime/gpu/gpu_init.cc:61] cannot enable peer access from device ordinal 1 to device ordinal 0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:61] cannot enable peer access from device ordinal 1 to device ordinal 3
I tensorflow/core/common_runtime/gpu/gpu_init.cc:61] cannot enable peer access from device ordinal 2 to device ordinal 0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:61] cannot enable peer access from device ordinal 2 to device ordinal 3
I tensorflow/core/common_runtime/gpu/gpu_init.cc:61] cannot enable peer access from device ordinal 3 to device ordinal 1
I tensorflow/core/common_runtime/gpu/gpu_init.cc:61] cannot enable peer access from device ordinal 3 to device ordinal 2
I tensorflow/core/common_runtime/gpu/gpu_init.cc:138] DMA: 0 1 2 3 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:148] 0:   Y N N Y 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:148] 1:   N Y Y N 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:148] 2:   N Y Y N 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:148] 3:   Y N N Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:867] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:867] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX TITAN X, pci bus id: 0000:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:867] Creating TensorFlow device (/gpu:2) -> (device: 2, name: GeForce GTX TITAN X, pci bus id: 0000:03:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:867] Creating TensorFlow device (/gpu:3) -> (device: 3, name: GeForce GTX 1080, pci bus id: 0000:04:00.0)
```

**Comment by prb12** [comment]
This usually happens when the GPUs are on different PCI buses.  The connectivity matrix looks a little strange in this case.

**Comment by vrv** [comment]
I think this is working as intended.  The DMA matrix shows which GPUs can talk as 'peers' to each other (e.g., via direct GPU to GPU copies using DMA, rather than going through CPU).

Because you are using two generations of cards, they can't talk to each other, it seems.  The only implication is that the bandwidth between all the GPUs is not uniform, but you can still use all 4 GPUs in the same model and TensorFlow will properly use them.

**Comment by chakpongchung** [comment]
So far there is no way to mix different types of gpu using some kind of load balancing? Or tensorflow does not support GPU of different types? I have 2 TitanX and 2 1080TI, very similar to the situation above.

**Comment by vrv** [comment]
@chakpongchung You can use different GPU types in TensorFlow, that is well supported.  See our installation page for instructions about mixing different compute capabilities, if that's the problem.

TF does not do dynamic load balancing across GPUs today; given a dataflow graph, it statically assigns work to devices.  So far this has worked well enough that dynamic GPU selection has not been needed.
