### ISSUE TITLE
libtensorflowlite.so crash on Android (NDK r18b)

### ISSUE THREAD

**Issue by andreydung** [tensorflow/tensorflow#40149]
[<em>Please](url) make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Android Phone 
- TensorFlow installed from (source or binary): 2.1.1
- TensorFlow version:
- Python version: 2.7
- Installed using virtualenv? pip? conda?: None
- Bazel version (if compiling from source): 0.27.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: None
- GPU model and memory:

**Describe the problem**

I built the libtensorflowlite.so for both armeabi-v7a and arm64-v8a using the build command from doc file:

```
bazel build -c opt --config=android_arm //tensorflow/lite:libtensorflowlite.so
bazel build -c opt --config=android_arm64 //tensorflow/lite:libtensorflowlite.so
```

Here is the bazel configuration:
```
build --host_force_python=PY2
build --action_env PYTHON_BIN_PATH="/usr/bin/python"
build --action_env PYTHON_LIB_PATH="/usr/local/lib/python2.7/dist-packages"
build --python_path="/usr/bin/python"
build:xla --define with_xla_support=true
build:opt --copt=-march=native
build:opt --copt=-Wno-sign-compare
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build --action_env ANDROID_NDK_HOME="/mnt/1tb-drive/software/Android/ndk/android-ndk-r18b"
build --action_env ANDROID_NDK_API_LEVEL="21"
build --action_env ANDROID_BUILD_TOOLS_VERSION="28.0.3"
build --action_env ANDROID_SDK_API_LEVEL="28"
build --action_env ANDROID_SDK_HOME="/mnt/1tb-drive/software/Android"
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test --test_tag_filters=-benchmark-test,-no_oss,-oss_serial
test --build_tag_filters=-benchmark-test,-no_oss
test --test_tag_filters=-gpu
test --build_tag_filters=-gpu
build --action_env TF_CONFIGURE_IOS="0"
```
However, when using this in a jnilibs (along with NDK r18b), the generated .so file has segmentation fault. How could I fix this problem?

```
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 20155 (Thread-3), pid 20112
```

To be clear, I was able to load model succesfully:

```
modelStftSpectrogram = tflite::FlatBufferModel::BuildFromFile(path.c_str());

    if(!model){
        exit(0);
    }
    
    tflite::ops::builtin::BuiltinOpResolver resolver;
    tflite::InterpreterBuilder(*model, resolver)(&interpreter);

    TFLITE_MINIMAL_CHECK(interpreter != nullptr);
    TFLITE_MINIMAL_CHECK(interpreter->AllocateTensors() == kTfLiteOk);
```

Then the segmentation fault happens exactly at this line:

```
    float *tflite_input = interpreter->typed_input_tensor<float>(0);

```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by terryheo** [comment]
If you're using Android, you'd better build it with dbg.
```
bazel build -c dbg --config=android_arm64 //tensorflow/lite:libtensorflowlite.so
```
Then you can use ndk-stack to find where it crashed with Android crash dump on logcat.
https://developer.android.com/ndk/guides/ndk-stack
