### ISSUE TITLE
TF model convert to TFLite

### ISSUE THREAD

**Issue by ivs-pychen** [tensorflow/tensorflow#40140]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu18.04.3
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):1.9.0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.
import tensorflow as tf

graph_def_file = "/home/pychen/MobileNetV2-SSD/MobileNetV2-SSD_600x300/frozen_inference_graph.pb"
input_arrays = ["image_tensor"]
output_arrays = ["detection_classes", "detection_boxes", "detection_scores"]

converter = tf.contrib.lite.TocoConverter.from_frozen_graph(
  graph_def_file=graph_def_file, input_arrays=input_arrays, output_arrays=output_arrays)
tflite_model = converter.convert()
open("MobileNetV2_SSD.tflite", "wb").write(tflite_model)
```
# Copy and paste here the exact command
```

**The output from the converter invocation**

```
# Copy and paste the output here.
```

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**
Traceback (most recent call last):
  File "/home/pychen/.local/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 418, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'Truncate' not in Op<name=Cast; signature=x:SrcT -> y:DstT; attr=SrcT:type; attr=DstT:type>; NodeDef: ToFloat = Cast[DstT=DT_FLOAT, SrcT=DT_UINT8, Truncate=false](image_tensor). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tf_to_tflite_graphdef.py", line 8, in <module>
    graph_def_file=graph_def_file, input_arrays=input_arrays, output_arrays=output_arrays)
  File "/home/pychen/.local/lib/python3.6/site-packages/tensorflow/contrib/lite/python/lite.py", line 204, in from_frozen_graph
    import_graph_def(graph_def, name="")
  File "/home/pychen/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home/pychen/.local/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 422, in import_graph_def
    raise ValueError(str(e))
ValueError: NodeDef mentions attr 'Truncate' not in Op<name=Cast; signature=x:SrcT -> y:DstT; attr=SrcT:type; attr=DstT:type>; NodeDef: ToFloat = Cast[DstT=DT_FLOAT, SrcT=DT_UINT8, Truncate=false](image_tensor). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ivs-pychen** [comment]
[frozen_inference_graph.zip](https://github.com/tensorflow/tensorflow/files/4734220/frozen_inference_graph.zip)

**Comment by ivs-pychen** [comment]
Do I need to retrain the model using TensorFlow v1.15 and use export_tflite_ssd_graph.py to convert Mobilenet v2 SSD to tensorflow lite?

**Comment by karimnosseir** [comment]
@ivs-pychen Looks like this model have control flows. Can you please enable control flow v2 in TF, so your model will use control flow v2 instead of v1 (which we don't support)
You can add tf.enable_control_flow_v2()

Thanks
