### ISSUE TITLE
GPU Delegate doesn't work for tflite model on Android device

### ISSUE THREAD

**Issue by ArtanBerisha1** [tensorflow/tensorflow#40144]
I was trying to increase the run speed of Posenet, these are the performances:

2020-06-04 08:41:21.143 I/InterpreterPosenet: Scaling to [-1,1] took 207.85 ms
2020-06-04 08:41:21.894 I/posenet: Interpreter took 743.94 ms
2020-06-04 08:41:22.559 I/InterpreterPosenet: Scaling to [-1,1] took 226.94 ms
2020-06-04 08:41:23.058 I/posenet: Interpreter took 498.60 ms
2020-06-04 08:41:23.497 I/InterpreterPosenet: Scaling to [-1,1] took 191.16 ms
2020-06-04 08:41:23.858 I/posenet: Interpreter took 360.01 ms
2020-06-04 08:41:24.324 I/InterpreterPosenet: Scaling to [-1,1] took 223.37 ms
2020-06-04 08:41:24.866 I/posenet: Interpreter took 541.24 ms

As you can see this aren't very good performances and I was trying to find a way to increase the speed, and then I found out the GPU Delegate from tensorflow in this link:
https://www.tensorflow.org/lite/performance/gpu

And also in this link you can see that the speed of PoseNet increased somewhere by 2x,

I followed the instructions and this is my init method of the class Posenet.kt:
  init {
    val gpuDelegate = GpuDelegate()
    val options = Interpreter.Options().addDelegate(gpuDelegate)
    interpreter = Interpreter(loadModelFile("posenet_model.tflite", context), options)
  }

Also the gradle dependencies: 
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.0.0'
    implementation 'org.tensorflow:tensorflow-lite:2.1.0'
 
I also made some measurements for 40 frames and Posenet took: 550.2947368 ms on average and after GPU Delegate: 528.7305263 ms on average 

And also I don't get any errors from the method run() or from Interpreter, so what I am doing wrong ?

The device has the RK3399 processor: http://opensource.rock-chips.com/wiki_RK3399

**EDIT:** 
I Found out that this processor (RK3399) doesn't support GPU delegate, but I also tried on a device with Qualcomm 835 processor ( https://www.qualcomm.com/products/snapdragon-835-mobile-platform ) which supports GPU Delegate but still doesn't improve the performance.

**Comment by renjie-liu** [comment]
Hi Terry, can you help take a look?

thanks!

**Comment by terryheo** [comment]
@ArtanBerisha1 could you sync the repo and try again?
I've updated the sample code to use TFLite 2.2.0
Mine shows around 40ms on average.

**Comment by ArtanBerisha1** [comment]
@terryheo Thanks for the response, 
I updated TFLite implementation to 2.2.0 in gradle file, and the 'org.tensorflow:tensorflow-lite-gpu:2.0.0' is the same, I have sync the repo and tried again but the speed is 300ms on average with  Qualcomm 835 processor and its the same when I dont have the GpuDelegate as Interpreter Option. 
The only thing that PoseNet performed better is when I set setNumThreads(4) then the speed is 180ms on average, but I need to use gpu delegate.
What processor does your device has , because 40ms on average looks to fast.

**Comment by terryheo** [comment]
I used Pixel 4 and Galaxy S10e.
Did you modify source to use GPU?

https://github.com/tensorflow/examples/blob/master/lite/examples/posenet/android/posenet/src/main/java/org/tensorflow/lite/examples/posenet/lib/Posenet.kt#L76
It should be changed to
```
val device: Device = Device.GPU
```

**Comment by ArtanBerisha1** [comment]
As I have written before in the question I have the code a little different, but I think it does the same thing:
private var interpreter: Interpreter? = null
init {
    val gpuDelegate = GpuDelegate()
    val options = Interpreter.Options()
    options.setNumThreads(4)
    options.addDelegate(gpuDelegate)
    interpreter = Interpreter(loadModelFile ( "posenet.tflite" , contex), options )
}
I create the GpuDelegate() and pass it to the Interpreter Options, but now improvement on the speed.

**Comment by terryheo** [comment]
Can you see the following log from logcat?
```
06-11 10:39:04.868 14446 14524 I tflite  : Created TensorFlow Lite delegate for GPU.
06-11 10:39:04.873 14446 14524 I tflite  : Initialized TensorFlow Lite runtime.
06-11 10:39:04.895 14446 14524 I tflite  : Initialized OpenGL-based API.
06-11 10:39:05.305 14446 14524 I posenet : Interpreter took 192.60 ms
```
(The third line could be "OpenCL")

This is a log from my Pixel 1 which uses 821 processor. I think result from 835 should be better.

**Comment by ArtanBerisha1** [comment]
@terryheo thanks for the response
These 2 lines are showing:
2020-06-12 08:55:33.250 I/tflite: Created TensorFlow Lite delegate for GPU.
2020-06-12 08:55:33.259 I/tflite: Initialized TensorFlow Lite runtime.

Can you try to remove options.setNumThreads(4) and then see if the time is the same with and without GpuDelegate ?
Because when I try without setNumThreads(4), I have the same result with GpuDelegate and without it.

**Comment by terryheo** [comment]
With GPU delegate, the thread number doesn't affect the performance.
So since you can't see the improvement, I guess you're using GPU delegate correctly.
(In my devices, 4 threads CPU performs similar to GPU)
BTW, I'm curious why you don't see "Initialized OpenGL-based API." or "Initialized OpenCL-based API."
Could you check if you're using 'org.tensorflow:tensorflow-lite-gpu:2.2.0' ?

**Comment by ArtanBerisha1** [comment]
@terryheo I had the gpu:2.0.0 version and upgrade to gpu:2.2.0, and I worked the speed of the model is around 110-100ms, but I have a question about the thread number:
You said that the thread number doesn't affect the performance but when I try just GpuDelegate without the number of threads then the speed increase around 150ms and its not to stable like it is when I set the number of threads, so is this happening just by chance ?
My code:
    val options = Interpreter.Options()
    val gpuDelegate = GpuDelegate()
    options.setNumThreads(4)
    options.addDelegate(gpuDelegate)

**Comment by terryheo** [comment]
If a model is not fully delegated to GPU, some graph will still run on CPU. In such case, setting the thread number makes sense. But this case, the graph is fully delegated to GPU, so the setting thread number is meaningless.
BTW, I've just submitted several changes including the library version change and improving preprocessing. You'll see some performance improvement with the master branch.

I think you have success with GPU delegate now. So let's close this.

**Comment by ArtanBerisha1** [comment]
Thanks for your help @terryheo
