### ISSUE TITLE
Java API doc for TFLite

### ISSUE THREAD

**Issue by badenh** [tensorflow/tensorflow#40146]
As pointed out on the tflite@tensorflow.org list recently, there's no documentation for the use of Java against the TFLite API as yet. https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/api_docs/index.md

There is however API doc for Java for full TF.

Is there anyone assigned to work on this ? If not, I'm happy to have a go.

**Comment by jdduke** [comment]
Yes, thanks for flagging! We're actively working on this and hope to have it available around the time of the upcoming TF 2.3 release. We'll use this issue for external tracking.

**Comment by lu-wang-g** [comment]
See the Java API doc here: https://www.tensorflow.org/lite/api_docs/java/org/tensorflow/lite/package-summary
