### ISSUE TITLE
tf.sparse_tensor_to_dense get the wrong result

### ISSUE THREAD

**Issue by xueyuan1990** [tensorflow/tensorflow#40147]
Python 3.6.1
tensorflow = 1.15.0
```
ids_index = tf.sparse_tensor_to_dense(ids_sparse_tensor, default_value=0, validate_indices=True,name=None) 
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    session.run(tf.tables_initializer())
    print("ids_sparse_tensor"+"*"*30)
    print(ids_sparse_tensor.indices.eval().shape)
    print(ids_sparse_tensor.values.eval().shape)
    print(ids_sparse_tensor.eval())
    print("ids_index"+"*" * 30)
    ids_index_value=ids_index.eval()
    print(ids_index_value.shape) #(1024, 91)
    print(ids_index_value)               
...
```
I got result below:
ids_sparse_tensor******************************
(93184, 2)
(93184,)
SparseTensorValue(indices=array([[   0,    0],
       [   0,    1],
       [   0,    2],
       ...,
       [1023,   88],
       [1023,   89],
       [1023,   90]], dtype=int64), values=array([7250, 1622, 2987, ...,    0,    0,    0], dtype=int64), dense_shape=array([1024,   91], dtype=int64))
ids_index******************************
(1024, 91)
[[1233 1144 7106 ...    0    0    0]
 [4758 6123 6134 ...    0    0    0]
 [2487 1965 4448 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [  57 5203    0 ...    0    0    0]
 [5848 4164 2790 ...    0    0    0]]

My question is : Why ids_index[0,0]=1233 ? I think it should be 7250.

**Comment by ravikyram** [comment]
@xueyuan1990 

Looks like code is incomplete.Request you provide colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!
