### ISSUE TITLE
TFLite: Cannot run inference on TF Lite Model: "Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 3

### ISSUE THREAD

**Issue by aselva-eb** [tensorflow/tensorflow#40155]
**System information**
- OSX Mojave
- TF 2.3.0-dev20200602
- Python 3.7.7
- TF installed using Conda

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
    converter = tf.lite.TFLiteConverter.from_saved_model(curr_dir + "saved_model")
    tflite_model = converter.convert()

    # Save the TF Lite model.
    with tf.io.gfile.GFile(curr_dir + '/model.tflite', 'wb') as f:
        f.write(tflite_model)
```

**The output from the converter invocation**

```
# Copy and paste the output here.
```

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@aselva-eb
Please share a simple stand alone code to replicate the error faced or share the colab gist with error faced for us to analyse

**Comment by aselva-eb** [comment]
Sorry! - just realized how empty this ticket is - not sure how I ended up posting this. 
The real ticket with the info is:
https://github.com/tensorflow/tensorflow/issues/40155
