### ISSUE TITLE
TFLite: ELU activation not supported on GPU delegate

### ISSUE THREAD

**Issue by ltxitai** [tensorflow/tensorflow#40152]
Models with ELU activation op cannot run on GPU delegate, getting the following error:

```
java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Next operations are not supported by GPU delegate:
ELU: Operation is not supported.
```

Can support for this op be added to GPU delegate?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (or github SHA if from source): 2.2.0

Here's a code to generate a minimal example model:

```
import tensorflow as tf
model = tf.keras.Sequential([
    tf.keras.Input(shape=(32,32)),
    tf.keras.layers.ELU()
])
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.experimental_new_converter=False
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS]
tflite_model = converter.convert()
with open('elu.tflite', "wb") as f:
    f.write(tflite_model)
```

**Comment by ltxitai** [comment]
Model generated by the code above, which fails on TFLite GPU delegate:
[elu.tflite.zip](https://github.com/tensorflow/tensorflow/files/4730972/elu.tflite.zip)

**Comment by rikner** [comment]
Having the same issue on iOS with the `MetalDelegate`. Would be awesome if this could get solved!

**Comment by sushreebarsa** [comment]
@ltxitai Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!
