### ISSUE TITLE
GPU delegate not as accurate as NNAPI reference  on 16float models on Style Transfer example. tensorflow-lite

### ISSUE THREAD

**Issue by amitDaMan** [tensorflow/tensorflow#40167]
I was comparing the output of the transfer style app (while using the floating point models).

And found the following results

I/Style: Difference on average between CPU and  CPU: 8.049963811796872E-7
I/Style: Difference on average between CPU and  GPU: 0.00804935239782874
I/Style: Difference on average between CPU and  NNAPIREFERENCE: 8.941092843719466E-7
I/Style: Difference on average between CPU and  NNAPIDEFAULT: 7.434606152762919E-7
I/Style: Difference on average between CPU and  NNAPIGPU: 8.056053260209931E-7
I/Style: Difference on average between CPU and  NNAPIDSP: 7.446350522072008E-7
I/Style: Difference on average between CPU and  NNAPIHTA: 7.532546634042985E-7

NNAPI Reference is much more accurate than GPU through gpu delegate. What exactly is the threshold or standard for correctness? 

**How to reproduce results.**

I run the same noise through each interpreter, accelerated as specified.

the model produces an output of float[1][384][384][3]. I, basically, just take the difference between each float value and average them (sum and divide). I use the results from the CPU as the baseline, and compare.

The models used are attached. 

[style_float_models.zip](https://github.com/tensorflow/tensorflow/files/4732809/style_float_models.zip)

**Comment by amitDaMan** [comment]
ping.

**Comment by impjdi** [comment]
Sorry, I started taking a look at your network but then it dropped off my radar.

This network structure of doing a mean, squared diff, rsqrt (instance norm) is quite sensitive to lower precision.  The errors in small numbers bubbles up quickly with this sequence.  This happens usually only in FP16.  Things may be okay if you use FP32.

I remember having solved this problem by fixing some accumulators to FP32.  A fix should have gone out around March IIRC.  Are you still seeing this issue at HEAD?

**Comment by sushreebarsa** [comment]
@amitDaMan Could you please refer as per the above [comment](https://github.com/tensorflow/tensorflow/issues/40167#issuecomment-683131276) and let us know if this issue still persists ?Thanks!
