### ISSUE TITLE
Unable to call "image_dataset_from_directory"

### ISSUE THREAD

**Issue by Cillinc** [tensorflow/tensorflow#40160]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): conda install tensorflow 
- TensorFlow version:- version 2.1.0
- Python version: 3.7
- Installed using virtualenv? pip? conda?:conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Am following the commands on the tensir.io site ( https://keras.io/api/preprocessing/image/#image_dataset_from_directory-function )
and when i try to do the imports of the required functions at the start of my program i get an error.  I have reviewed the directories and the image_dataset_from_directory is not in the folder so it didn't download as part of the package.  how can i get it or has it been discontinued?

Initial commands:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import preprocessing
from tensorflow.keras.preprocessing.image import image_dataset_from_directory

Error: 

from tensorflow.keras.preprocessing.image import image_dataset_from_directory
Traceback (most recent call last):

  File "<ipython-input-11-7fae7ea40691>", line 1, in <module>
    from tensorflow.keras.preprocessing.image import image_dataset_from_directory

ImportError: cannot import name 'image_dataset_from_directory' from 'tensorflow.keras.preprocessing.image' (d:\anaconda3\envs\masters\lib\site-packages\tensorflow_core\python\keras\api\_v2\keras\preprocessing\image\__init__.py)

**Comment by amahendrakar** [comment]
@Cillinc,
As per the [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image_dataset_from_directory) of `tf.keras.preprocessing.image_dataset_from_directory
` the API is new and is only available in TF-nightly. 

Could you please install TensorFlow nightly and check if you are facing the same issue. Please take a look at [this gist](https://colab.research.google.com/gist/amahendrakar/aed4310c0e8b98ab585a318a520533c1/40160.ipynb) for reference. Thanks!

**Comment by Cillinc** [comment]
thanks i have upgraded pip to version 20.1.1 and used it to do a `pip install tf-nightly`  it completed correctly (had got an error ob the lower version of pip and i am still getting the same results - errors.
from tensorflow.keras.preprocessing.image import image_dataset_from_directory
Traceback (most recent call last):

  File "<ipython-input-3-7fae7ea40691>", line 1, in <module>
    from tensorflow.keras.preprocessing.image import image_dataset_from_directory

ImportError: cannot import name 'image_dataset_from_directory' from 'tensorflow.keras.preprocessing.image' (d:\anaconda3\envs\masters\lib\site-packages\tensorflow\keras\preprocessing\image\__init__.py)



![Capture - tf-nightly 1](https://user-images.githubusercontent.com/33866780/83802569-e8de0a80-a6a2-11ea-92a6-034f9978369b.PNG)
![Capture - pip upgrade and tf-nightly 2](https://user-images.githubusercontent.com/33866780/83802578-eb406480-a6a2-11ea-8bd1-0af12f9ed70c.PNG)
![Capture keras_preprocessing dir](https://user-images.githubusercontent.com/33866780/83802580-ed0a2800-a6a2-11ea-86ab-bd9eaed906a6.PNG)

**Comment by Cillinc** [comment]
think i found the solution on one of your github postings - well concealed...

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import preprocessing
from tensorflow.keras.preprocessing import image_dataset_from_directory

looks like the text on keras.io where i got the script might need a slight adjustment

**Comment by donagiro** [comment]
> think i found the solution on one of your github postings - well concealed...
> 
> import tensorflow as tf
> from tensorflow import keras
> from tensorflow.keras import preprocessing
> from tensorflow.keras.preprocessing import image_dataset_from_directory
> 
> looks like the text on keras.io where i got the script might need a slight adjustment

don'T know who you are but thank you so much for this info

**Comment by RajputJay41** [comment]
> think i found the solution on one of your github postings - well concealed...
> 
> import tensorflow as tf
> from tensorflow import keras
> from tensorflow.keras import preprocessing
> from tensorflow.keras.preprocessing import image_dataset_from_directory
> 
> looks like the text on keras.io where i got the script might need a slight adjustment

This also wont work. you have to use tf-nightly only.

**Comment by pngimbwa** [comment]
> > think i found the solution on one of your github postings - well concealed...
> > import tensorflow as tf
> > from tensorflow import keras
> > from tensorflow.keras import preprocessing
> > from tensorflow.keras.preprocessing import image_dataset_from_directory
> > looks like the text on keras.io where i got the script might need a slight adjustment
> 
> This also wont work. you have to use tf-nightly only.

Try import it like this: - 
from keras.preprocessing.image import ImageDataGenerator

Then, use it like this: - 
train_images = ImageDataGenerator().flow_from_directory(train_path,target_size=(width,height))

**Comment by charlyBraga** [comment]
I solved using:  "tf.keras.preprocessing.image_dataset_from_directory"
Obs.: import tensorflow as tf
