### ISSUE TITLE
linking error while building TensorFlow Lite C++ image classification demo for Android

### ISSUE THREAD

**Issue by snsvis** [tensorflow/tensorflow#40168]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04

bazel build -c opt --config=android_arm64 //tensorflow/lite/examples/label_image:label_image
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=204
INFO: Reading rc options for 'build' from /home/ambuj/try/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/ambuj/try/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from /home/ambuj/try/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/ambuj/try/env/bin/python3 --action_env PYTHON_LIB_PATH=/home/ambuj/try/env/lib/python3.6/site-packages --python_path=/home/ambuj/try/env/bin/python3 --config=xla --action_env ANDROID_NDK_HOME=/opt/android-ndk --action_env ANDROID_NDK_API_LEVEL=27 --action_env ANDROID_BUILD_TOOLS_VERSION=29.0.2 --action_env ANDROID_SDK_API_LEVEL=28 --action_env ANDROID_SDK_HOME=/opt/android-sdk --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file /home/ambuj/try/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /home/ambuj/try/tensorflow/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:android_arm64 in file /home/ambuj/try/tensorflow/.bazelrc: --config=android --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a
INFO: Found applicable config definition build:android in file /home/ambuj/try/tensorflow/.bazelrc: --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --noenable_platform_specific_config --copt=-w --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Call stack for the definition of repository 'io_bazel_rules_docker' which is a git_repository (rule definition at /home/ambuj/.cache/bazel/_bazel_ambuj/9eebf77bd6558b95e6f902cd1dc311ce/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - <builtin>
 - /home/ambuj/.cache/bazel/_bazel_ambuj/9eebf77bd6558b95e6f902cd1dc311ce/external/bazel_toolchains/repositories/repositories.bzl:37:9
 - /home/ambuj/try/tensorflow/WORKSPACE:37:1
INFO: Analyzed target //tensorflow/lite/examples/label_image:label_image (0 packages loaded, 1926 targets configured).
INFO: Found 1 target...
ERROR: /home/ambuj/try/tensorflow/tensorflow/lite/examples/label_image/BUILD:15:1: Linking of rule '//tensorflow/lite/examples/label_image:label_image' failed (Exit 1)
bazel-out/arm64-v8a-opt/bin/tensorflow/lite/experimental/delegates/hexagon/builders/libop_builder.a(transpose_conv_2d_builder.o): In function `tflite::delegates::hexagon::TransposeConv2dOpBuilder::PopulateSubGraph(TfLiteIntArray const*, TfLiteIntArray const*, TfLiteContext*)':
/proc/self/cwd/tensorflow/lite/experimental/delegates/hexagon/builders/transpose_conv_2d_builder.cc:90: undefined reference to `tflite::delegates::hexagon::OpBuilder::kScalarShape'
/proc/self/cwd/tensorflow/lite/experimental/delegates/hexagon/builders/transpose_conv_2d_builder.cc:90: undefined reference to `tflite::delegates::hexagon::OpBuilder::kScalarShape'
/proc/self/cwd/tensorflow/lite/experimental/delegates/hexagon/builders/transpose_conv_2d_builder.cc:147: undefined reference to `tflite::delegates::hexagon::OpBuilder::kScalarShape'
/proc/self/cwd/tensorflow/lite/experimental/delegates/hexagon/builders/transpose_conv_2d_builder.cc:147: undefined reference to `tflite::delegates::hexagon::OpBuilder::kScalarShape'
/proc/self/cwd/tensorflow/lite/experimental/delegates/hexagon/builders/transpose_conv_2d_builder.cc:200: undefined reference to `tflite::delegates::hexagon::OpBuilder::kScalarShape'
bazel-out/arm64-v8a-opt/bin/tensorflow/lite/experimental/delegates/hexagon/builders/libop_builder.a(transpose_conv_2d_builder.o):/proc/self/cwd/tensorflow/lite/experimental/delegates/hexagon/builders/transpose_conv_2d_builder.cc:200: more undefined references to `tflite::delegates::hexagon::OpBuilder::kScalarShape' follow
bazel-out/arm64-v8a-opt/bin/tensorflow/lite/delegates/gpu/cl/libarguments.a(arguments.o): In function `char const* std::__ndk1::__search_substring<char, std::__ndk1::char_traits<char> >(char const*, char const*, char const*, char const*)':
/proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include/__string:(.text+0x230c): undefined reference to `tflite::gpu::cl::Arguments::kArgsPrefix'
/proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include/__string:(.text+0x2310): undefined reference to `tflite::gpu::cl::Arguments::kArgsPrefix'
bazel-out/arm64-v8a-opt/bin/tensorflow/lite/delegates/gpu/cl/libarguments.a(arguments.o): In function `std::__ndk1::char_traits<char>::compare(char const*, char const*, unsigned long)':
/proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include/__string:250: undefined reference to `tflite::gpu::cl::Arguments::kArgsPrefix'
/proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include/__string:250: undefined reference to `tflite::gpu::cl::Arguments::kArgsPrefix'
bazel-out/arm64-v8a-opt/bin/tensorflow/lite/delegates/gpu/cl/libarguments.a(arguments.o): In function `char const* std::__ndk1::__search_substring<char, std::__ndk1::char_traits<char> >(char const*, char const*, char const*, char const*)':
/proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include/__string:(.text+0x2b40): undefined reference to `tflite::gpu::cl::Arguments::kArgsPrefix'
bazel-out/arm64-v8a-opt/bin/tensorflow/lite/delegates/gpu/cl/libarguments.a(arguments.o):/proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include/__string:(.text+0x2b44): more undefined references to `tflite::gpu::cl::Arguments::kArgsPrefix' follow
bazel-out/arm64-v8a-opt/bin/tensorflow/lite/experimental/delegates/hexagon/builders/libop_builder.a(pack_builder.o): In function `tflite::delegates::hexagon::PackOpBuilder::PopulateSubGraph(TfLiteIntArray const*, TfLiteIntArray const*, TfLiteContext*)':
/proc/self/cwd/tensorflow/lite/experimental/delegates/hexagon/builders/pack_builder.cc:47: undefined reference to `tflite::delegates::hexagon::OpBuilder::kScalarShape'
/proc/self/cwd/tensorflow/lite/experimental/delegates/hexagon/builders/pack_builder.cc:47: undefined reference to `tflite::delegates::hexagon::OpBuilder::kScalarShape'
/proc/self/cwd/tensorflow/lite/experimental/delegates/hexagon/builders/pack_builder.cc:(.text+0x2d4): undefined reference to `tflite::delegates::hexagon::OpBuilder::kScalarShape'
/proc/self/cwd/tensorflow/lite/experimental/delegates/hexagon/builders/pack_builder.cc:(.text+0x2d8): undefined reference to `tflite::delegates::hexagon::OpBuilder::kScalarShape'
/proc/self/cwd/tensorflow/lite/experimental/delegates/hexagon/builders/pack_builder.cc:(.text+0x35c): undefined reference to `tflite::delegates::hexagon::OpBuilder::kScalarShape'
bazel-out/arm64-v8a-opt/bin/tensorflow/lite/experimental/delegates/hexagon/builders/libop_builder.a(pack_builder.o):/proc/self/cwd/tensorflow/lite/experimental/delegates/hexagon/builders/pack_builder.cc:(.text+0x360): more undefined references to `tflite::delegates::hexagon::OpBuilder::kScalarShape' follow
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //tensorflow/lite/examples/label_image:label_image failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.811s, Critical Path: 0.31s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by freedomtan** [comment]
@snsvis this is not a label_image problem. I can reproduce the problem. It also happens when building benchmark with `bazel build --config android_arm64 //tensorflow/lite/tools/benchmark:benchmark_model`. A quick workaround is
```diff
diff --git a/tensorflow/lite/delegates/gpu/cl/arguments.h b/tensorflow/lite/delegates/gpu/cl/arguments.h
index 453ffcb56b..2b24d7abf9 100644
--- a/tensorflow/lite/delegates/gpu/cl/arguments.h
+++ b/tensorflow/lite/delegates/gpu/cl/arguments.h
@@ -32,6 +32,8 @@ namespace tflite {
 namespace gpu {
 namespace cl {
 
+static constexpr char kArgsPrefix[] = "args.";
+
 class Arguments {
  public:
   Arguments() = default;
@@ -95,8 +97,6 @@ class Arguments {
                           const std::vector<std::string>& member_names,
                           std::string* code);
 
-  static constexpr char kArgsPrefix[] = "args.";
-
   struct IntValue {
     int value;
 
diff --git a/tensorflow/lite/experimental/delegates/hexagon/builders/op_builder.h b/tensorflow/lite/experimental/delegates/hexagon/builders/op_builder.h
index e130e6d2ef..7b7d25d46b 100644
--- a/tensorflow/lite/experimental/delegates/hexagon/builders/op_builder.h
+++ b/tensorflow/lite/experimental/delegates/hexagon/builders/op_builder.h
@@ -49,6 +49,7 @@ struct OpNode {
 
 class GraphBuilder;
 
+static constexpr int kScalarShape[] = {1, 1, 1, 1};
 // Represents a single Op in the TFLite graph.
 // For each op in TFLite there should be an OpBuidler, this builder is
 // responsible for constructing equivalent node(s) in the hexagon graph. A
@@ -61,7 +62,6 @@ class GraphBuilder;
 class OpBuilder {
  public:
   // Const representing the shape of a scalar value.
-  static constexpr int kScalarShape[] = {1, 1, 1, 1};
 
   OpBuilder(GraphBuilder* graph_builder, int hexagon_op_type)
       : graph_builder_(graph_builder) {

```
+@karimnosseir who made the changes.

@karimnosseir FYI. Someting weird happened. I don't know why, but the two class variables `Arguments::kArgsPrefix` and `OpBuilder::kScalarShape` are removed by the comiler/linker. So there are messages shown by @snsvis.

**Comment by karimnosseir** [comment]
Fix on the way. Sorry for the trouble
