### ISSUE TITLE
AttributeError: 'PerReplica' object has no attribute 'begin'

### ISSUE THREAD

**Issue by rayleichen** [tensorflow/tensorflow#40165]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.14
- Python version: Python 2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I'm trying to distributed evaluation on 2 GPUs on my local dev server using Mirrored Strategy. But I'm getting errors as follows:
```
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 477, in evaluate
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 517, in _actual_eval
    return _evaluate()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 508, in _evaluate
    output_dir=self.eval_dir(name))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1609, in _evaluate_run
    config=self._session_config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/evaluation.py", line 269, in _evaluate_once
    session_creator=session_creator, hooks=hooks) as session:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1007, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 713, in __init__
    h.begin()
**AttributeError: 'PerReplica' object has no attribute 'begin'**
```

I also noticed I'm having "not used by distribute strategy" error in the log (which I don't have in distributed training using mirrored strategy):
```
2020-06-04 18:40:02.149347: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/device:GPU:0 with 14006 MB memory) -> physical GPU (device: 0, name: Quadro RTX 5000, pci bus id: 0000:17:00.0, compute capability: 7.5)
2020-06-04 18:40:02.149933: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/device:GPU:1 with 14039 MB memory) -> physical GPU (device: 1, name: Quadro RTX 5000, pci bus id: 0000:65:00.0, compute capability: 7.5)
**INFO: tensorflow: Device is available but not used by distribute strategy: /device:CPU:0**
```

My distributed model evaluation is as follows:
```
strategy = tf.compat.v1.distribute.MirroredStrategy()

 self.run_config = tf.estimator.RunConfig(
        model_dir=self.job_dir,
        save_summary_steps=self.save_summary_steps,
        session_config=session_config,
        eval_distribute=strategy,
)

estimator = tf.estimator.Estimator(
    model_fn=eval_model_fn,
    config=self.run_config
)

eval_result = estimator.evaluate(
    input_fn=input_tf_dataset,
    steps=eval_steps,
    name=self.eval_name,
    hooks=hooks,
    checkpoint_path=weights_path
)          
```

**Describe the expected behavior**
I expected distributed evaluation shall work, because I also have distributed training + evaluation working properly as follows:
```
self.run_config = tf.estimator.RunConfig(
    model_dir=self.job_dir,
    save_checkpoints_steps=self.save_checkpoints_steps,
    save_checkpoints_secs=self.save_checkpoints_secs,
    keep_checkpoint_max=self.keep_checkpoint_max,
    save_summary_steps=self.save_summary_steps,
    session_config=session_config,
    train_distribute=distributed_strategy,
)

train_spec = tf.estimator.TrainSpec(
    input_fn=train_input_tf_dataset
    max_steps=max_steps,
    hooks=train_hooks,
)
eval_spec = tf.estimator.EvalSpec(
    input_fn=eval_input_tf_dataset
    steps=eval_steps,
    name=self.eval_name,
    hooks=eval_hooks
)

tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
```

**Standalone code to reproduce the issue**
I don't have standalone code to reproduce the issue right now.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

I also found this issue: https://github.com/tensorflow/tensorflow/issues/28018. But for my case, even if I remove hooks, I still get the similar error.

**Comment by rayleichen** [comment]
I replace DistributedStrategy from 
```
strategy = tf.compat.v1.distribute.MirroredStrategy()
```
to
```
strategy = tf.compat.v1.distribute.MirroredStrategy(
    devices=["/gpu:0", "/gpu:1"],
    cross_device_ops=tf.contrib.distribute.AllReduceCrossDeviceOps(
                    all_reduce_alg="hiearchical_copy"
    )
)
```
I no longer see the error: "Device is available but not used by distribute strategy: /device:CPU:0", but I still have "AttributeError: 'PerReplica' object has no attribute 'begin'"

**Comment by rayleichen** [comment]
This issue is a duplicate of https://github.com/tensorflow/tensorflow/issues/28018. 

The hooks passed into evaluate() function does cause any issue.
```
eval_result = estimator.evaluate(
    input_fn=input_tf_dataset,
    steps=eval_steps,
    name=self.eval_name,
    hooks=hooks,
    checkpoint_path=weights_path
)          
```

It's eval_hooks in EstimatorSpec causing the issue. If I comment out "evaluation_hooks", it's working fine.
```
def eval_model_fn:
        return tf.estimator.EstimatorSpec(
            mode=ModeKey.EVAL,
            evaluation_hooks=eval_hooks,
        )    

estimator = tf.estimator.Estimator(
    model_fn=eval_model_fn,
    config=self.run_config
)
```

**Comment by guptapriya** [comment]
This has been fixed (https://github.com/tensorflow/estimator/commit/131f54a62ae9ded9057aeb0eb1243d9516373b14). Please test with TF nightly.
