### ISSUE TITLE
<tf.Variable 'Variable:0' shape=(1, 56, 56, 256) dtype=float32, numpy= array([[[[0.        , 3.6259902 , 3.3980963 , ...,        nan,                  nan,        nan],

### ISSUE THREAD

**Issue by benedives47** [tensorflow/tensorflow#40161]
Does anyone ever experience like this? Please give enlightenment, thank you

![image](https://user-images.githubusercontent.com/58981061/83787982-cce86200-a6be-11ea-86be-93c587a5e45a.png)

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.

Can you please elaborate about the issue & the context.Will it be possible to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by Wiphawee112** [comment]
ฉันอ้อนวอน ด้วยความเมตา ฉันไม่มีความรุ้มากในระบบโซเชียล ฉันต้องการเงินทุนสำรองเลี้ยงบุตรและเริ่มกิจการเล้กๆของตัวเอง ในภูมิภาคิที่ฉันอยู่เต็บไปด้วยกลลวงจนฉันและครอบครัวลำบากหมดทางแก้ไข ฉันเป็นหม้าย แต่ฉันมีงานที่ดี สุจริตและต้องการศึกษาเพิ่มเกี่ยวกับโลกโซเชียล ฉันคงเข้าระบบผิด ถูกบ้าง เพื่อเข้าถึงกระเป๋าเงินและสินเชื่อ ขอบคุณ และกล่าวขอโทษ    ด้วยความนับถือ  Wiphawee
