### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[1] does not have value with aarch64

### ISSUE THREAD

**Issue by jxfruit** [tensorflow/tensorflow#40176]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
CentOS Linux release 7.6.1810 (AltArch)  4.14.0-115.el7a.0.1.aarch64
- TensorFlow installed from (source or binary):
compiled from source 
- TensorFlow version (use command below):
1.13.1
- Python version:
3.7.6
- Bazel version (if compiling from source):
0.20.0
- GCC/Compiler version (if compiling from source):
5.5.0
- CUDA/cuDNN version:
no
- GPU model and memory:
no

I use multilayers' lstm to generate texts. The network :
def buildModel(wordNum, gtX, hidden_units=128, layers=2, embedding=True):  
    """build rnn"""
    with tf.variable_scope("embedding"):  # embedding
        if embedding is True:
            embedding = tf.get_variable("embedding", [wordNum, hidden_units], dtype = tf.float32)
            inputbatch = tf.nn.embedding_lookup(embedding, gtX)

        else:
            inputbatch = tf.one_hot(gtX, wordNum)
        print('shape: ', inputbatch.shape)
    inputbatch = tf.layers.batch_normalization(inputbatch, 0)
    basicCell = tf.contrib.rnn.BasicLSTMCell(hidden_units, state_is_tuple = True)
    droped_cell = tf.contrib.rnn.DropoutWrapper(basicCell, output_keep_prob=0.5)
    stack_cells = []
    for _ in range(layers):
        stack_cells.append(droped_cell)
#     stackCell = tf.contrib.rnn.MultiRNNCell([basicCell] * layers)
    stackCell = tf.contrib.rnn.MultiRNNCell(stack_cells)
    initState = stackCell.zero_state(np.shape(gtX)[0], tf.float32)
    outputs, finalState = tf.nn.dynamic_rnn(stackCell, inputbatch, initial_state = initState)
    # outputs = tf.concat(outputs, 1)
    outputs = tf.reshape(outputs, [-1, hidden_units])
    print('outpus:', outputs.shape)
    with tf.variable_scope("softmax"):
        w = tf.get_variable("w", initializer=tf.truncated_normal([hidden_units, wordNum], stddev=0.1))
        b = tf.get_variable("b", initializer=tf.zeros(wordNum))
        logits = tf.matmul(outputs, w) + b

    probs = tf.nn.softmax(logits)
    return logits, probs, stackCell, initState, finalState
And the loss function is tf.contrib.legacy_seq2seq.sequence_loss_by_example.
The following error appears  occasionally, sometimes in one epoch, sometimes in a few epochs. I am very confused about it. What is going on? I have  tried to add dropout , BN and fix the length of input, etc. But they are useless. Please help, tks a lot!
 All error log:
Traceback (most recent call last):
  File "/ddhome/.pyenv/versions/anaconda3-5.3.1/envs/py3.7.6-tf1.13.1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/ddhome/.pyenv/versions/anaconda3-5.3.1/envs/py3.7.6-tf1.13.1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/ddhome/.pyenv/versions/anaconda3-5.3.1/envs/py3.7.6-tf1.13.1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[1] does not have value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ddhome/src/lstm_debug/HCIA-IP/exp-lstm.py", line 224, in <module>
    train()
  File "/ddhome/src/lstm_debug/HCIA-IP/exp-lstm.py", line 203, in train
    a, loss, gStep = sess.run([trainOP, cost, addGlobalStep], feed_dict={gtX: x, gtY: y})
  File "/ddhome/.pyenv/versions/anaconda3-5.3.1/envs/py3.7.6-tf1.13.1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/ddhome/.pyenv/versions/anaconda3-5.3.1/envs/py3.7.6-tf1.13.1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/ddhome/.pyenv/versions/anaconda3-5.3.1/envs/py3.7.6-tf1.13.1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/ddhome/.pyenv/versions/anaconda3-5.3.1/envs/py3.7.6-tf1.13.1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[1] does not have value

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@jxfruit,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here.

Also, is there any specific reason you are using TF v1.13? Please update TensorFlow to 2.x and let us know if you are facing the same issue. Thanks!

**Comment by jxfruit** [comment]
@amahendrakar 
sorry, I cannot update tensorflow from v1.13 to 2.x in my project. All codes are following:


import os
import collections
import numpy as np
import tensorflow as tf
import pickle

in_dir = "./exp-14"

cur_pth = os.getcwd()
# root_pth = '/'.join(cur_pth.split('/')[:-1])
# out_dir = os.path.join(root_pth, 'exp-14')
out_dir = "./exp-14"
if not os.path.exists(out_dir):
    os.makedirs(out_dir)
    print(out_dir)
else:
    print("The directionary exists")

poem_file = os.path.join(in_dir, 'poem.txt')
print(in_dir, out_dir)

poems = []
with open(poem_file, "r", encoding='UTF-8') as f:
    for line in f:
        try:
            # line = line.decode('UTF-8')
            line = line.strip(u'\n')
            title, content = line.strip(u' ').split(u':')
            content = content.replace(u' ', u'')
            if u'_' in content or u'(' in content or u'（' in content or u'《' in content or u'[' in content:
                continue
            if len(content) < 5 or len(content) > 79:
                continue
            content = u'[' + content + u']'
            poems.append(content)
        except Exception as e:
            pass

poems = sorted(poems, key=lambda line: len(line))
print('total poems: ', len(poems))
print(poems[:100])

all_words = []
for poem in poems:
    all_words += [word for word in poem]
counter = collections.Counter(all_words)

count_pairs = sorted(counter.items(), key=lambda x: -x[1])

words, _ = zip(*count_pairs)
words = words[:len(words)] + (' ',)
print(words[:20])

word_num_map = dict(zip(words, range(len(words))))
to_num = lambda word: word_num_map.get(word, len(words))
poems_vector = [list(map(to_num, poem)) for poem in poems]
print(poems[:10])
print(poems_vector[:10])

w2v_file = os.path.join(out_dir, 'w2v.data')
with open(w2v_file, "wb") as fw:
    pickle.dump([words, word_num_map, poems_vector], fw)

batch_size = 64
n_chunk = len(poems_vector) // batch_size
print(n_chunk)


class DataSet(object):
    def __init__(self, data_size):
        self._data_size = data_size
        self._epochs_completed = 0
        self._index_in_epoch = 0
        self._data_index = np.arange(data_size)

    def next_batch(self, batch_size):

        start = self._index_in_epoch

        if start + batch_size > self._data_size:
            np.random.shuffle(self._data_index)
            self._epochs_completed = self._epochs_completed + 1
            self._index_in_epoch = batch_size
            full_batch_features, full_batch_labels = self.data_batch(0, batch_size)
            return full_batch_features, full_batch_labels

        else:
            self._index_in_epoch += batch_size
            end = self._index_in_epoch

            full_batch_features, full_batch_labels = self.data_batch(start, end)

            return full_batch_features, full_batch_labels

    def data_batch(self, start, end):
        batches = []
        for i in range(start, end):
            batches.append(poems_vector[self._data_index[i]])

        length = max(map(len, poems_vector))
        xdata = np.full((end - start, length), word_num_map[' '], np.int32)

        for row in range(end - start):
            xdata[row, :len(batches[row])] = batches[row]

        ydata = np.copy(xdata)
        ydata[:, :-1] = xdata[:, 1:]
        return xdata, ydata


def neural_network(batch_size=32, model='lstm', rnn_size=128, num_layers=2, is_training=True):
    tf.reset_default_graph()
    input_data = tf.placeholder(tf.int32, [batch_size, None])
    if is_training:
        output_targets = tf.placeholder(tf.int32, [batch_size, None])
    if model == 'rnn':
        cell_fun = tf.contrib.rnn.BasicRNNCell
    elif model == 'gru':
        cell_fun = tf.contrib.rnn.GRUCell
    elif model == 'lstm':
        cell_fun = tf.contrib.rnn.BasicLSTMCell

    basicCell = cell_fun(rnn_size, state_is_tuple=True)
    droped_cell = tf.contrib.rnn.DropoutWrapper(basicCell, output_keep_prob=0.5)
    cells = []
    for _ in range(num_layers):
        cells.append(droped_cell)
    cell = tf.contrib.rnn.MultiRNNCell(cells, state_is_tuple=True)
    # cell = tf.contrib.rnn.MultiRNNCell([cell] * num_layers, state_is_tuple=True)

    initial_state = cell.zero_state(batch_size, tf.float32)

    with tf.variable_scope('rnnlm'):

        softmax_w = tf.get_variable("softmax_w", [rnn_size, len(words)])
        softmax_b = tf.get_variable("softmax_b", [len(words)])

        with tf.device("/cpu:0"):
            embedding = tf.get_variable("embedding", [len(words), rnn_size])

            inputs = tf.nn.embedding_lookup(embedding, input_data)

    outputs, last_state = tf.nn.dynamic_rnn(cell, inputs, initial_state=initial_state, scope='rnnlm')

    output = tf.reshape(outputs, [-1, rnn_size])
    logits = tf.matmul(output, softmax_w) + softmax_b
    probs = tf.nn.softmax(logits)

    if is_training:
        return logits, last_state, probs, cell, initial_state, input_data, output_targets
    else:
        return logits, last_state, probs, cell, initial_state, input_data


def load_model(sess, saver, ckpt_path):
    latest_ckpt = tf.train.latest_checkpoint(ckpt_path)
    if latest_ckpt:
        print('resume from', latest_ckpt)
        saver.restore(sess, latest_ckpt)
        return int(latest_ckpt[latest_ckpt.rindex('-') + 1:])
    else:
        print('building model from scratch')
        sess.run(tf.global_variables_initializer())
        return -1


model_read_dir = os.path.join(in_dir, 'model')
model_read_path = os.path.join(model_read_dir, 'poem.module')
model_save_dir = os.path.join(out_dir, 'model')
model_save_path = os.path.join(model_save_dir, 'poem.module')


def train_neural_network():
    logits, last_state, _, _, _, input_data, output_targets = neural_network(batch_size)

    targets = tf.reshape(output_targets, [-1])

    with tf.name_scope('sequence_loss'):
        loss = tf.contrib.legacy_seq2seq.sequence_loss_by_example([logits], [targets],
                                                                  [tf.ones_like(targets, dtype=tf.float32)], len(words))
        cost = tf.reduce_mean(loss)
        tf.summary.scalar("loss_value", cost)

    learning_rate = tf.Variable(0.0, trainable=False)

    tvars = tf.trainable_variables()

    #     tf.clip_by_global_norm(
    #     t_list,
    #     clip_norm,
    #     use_norm=None,
    #     name=None
    #     )
    # t_list[i] * clip_norm / max(global_norm, clip_norm)
    # global_norm = sqrt(sum([t**2 for t in t_list]))

    grad_vars = tf.gradients(cost, tvars)
    grads, gn = tf.clip_by_global_norm(grad_vars, 1, name='gradients_clip')

    # optimizer = tf.train.GradientDescentOptimizer(learning_rate)
    optimizer = tf.train.AdamOptimizer(learning_rate, epsilon=1e-4)

    # train_op = optimizer.minimize(cost)
    train_op = optimizer.apply_gradients(zip(grads, tvars))

    Session_config = tf.ConfigProto(allow_soft_placement=True, log_device_placement=True)

    Session_config.gpu_options.allow_growth = True

    trainds = DataSet(len(poems_vector))

    summary_merge_op = tf.summary.merge_all()
    with tf.Session(config=Session_config) as sess:
        with tf.device('/gpu:0'):
            sess.run(tf.global_variables_initializer())

            saver = tf.train.Saver(tf.all_variables())

            # last_epoch = load_model(sess, saver, model_read_dir)
            last_epoch = 0
            writer = tf.summary.FileWriter('logs/', sess.graph)
            for epoch in range(last_epoch + 1, 30):

                sess.run(tf.assign(learning_rate, 0.002 * (0.3 ** epoch)))
                # sess.run(tf.assign(learning_rate, 0.01))

                all_loss = 0.0

                for batche in range(n_chunk):

                    x, y = trainds.next_batch(batch_size)

                    # sess.run(train_op, feed_dict={input_data: x, output_targets: y})
                    train_loss, _, _, summary_info = sess.run([cost, last_state, train_op, summary_merge_op],
                                                              feed_dict={input_data: x, output_targets: y})

                    writer.add_summary(summary_info, epoch)

                    grad = sess.run(grads, feed_dict={input_data: x, output_targets: y})
                    all_loss = all_loss + train_loss
                    # print(grad)
                    # print('epoch:', epoch, 'batch:', batche, 'lr:', 0.002 * (0.97 ** epoch), 'tl:', train_loss)
                    if batche % 50 == 1:
                        #     #print(epoch, batche, 0.01,train_loss)
                        print('epoch:', epoch, 'batch:', batche, 'lr:', 0.002 * (0.3 ** epoch), 'tl:', train_loss)

                saver.save(sess, model_save_path, global_step=epoch)

                print('epoch:', epoch, ' Loss: ', all_loss * 1.0 / n_chunk)


train_neural_network() 

The demo data are following:
"""
越中狂生题旗亭:日日草重生，悠悠傍素城。诸侯逐兔白，夏满镜湖平。
清泰三年歌:丙申年，数在五楼前。但看八九月，胡虏乱中原。
蜀王氏谶文:李祜西王逢吉昌，上德兑兴丹莫当。
黄万祜题蜀宫壁:莫交牵动青猪足，动即炎炎不可扑。鸷兽不欲两头黄，黄即其年天下哭。
孟蜀丐者语:不得登，登便倒。
孟蜀桃符诗:新年纳余庆，嘉节号长春。
上蓝和尚晋汉二代谶:石榴花发石榴开。
又遗钟传偈:但看来年二三月，柳条堪作打钟槌。
又报王审知十字谶:不怕羊入屋，只怕钱入腹。
钱处士李氏谶:仿佛之间一倍杨。
孙咸题庐山神庙诗:独入玄宫礼至真，焚香不为贱贫身。秦淮两岸沙埋骨，湓浦千家血染尘。庐阜烟霞谁是主，虎溪风月属何人。九江太守勤王室，好放天兵渡要津。
南唐江州风坠诗:由来秉节世无双，独守孤城死不降。何似知机早回首，免教流血满长江。
杭州还乡和尚唱:还乡寂寂杳无踪，不挂征帆水陆通。蹋得故乡回地稳，更无南北与西东。
福州记:潮水来，岩头没。潮水去，矢口出。
黄涅槃谶:先打南，后打北，留取清源作佛国。
陈智广谶:骑马来，骑马去。
又谶:功下田，力交连。井底坐，二十年。
僧缄示王处厚:周士同成，二王殊名。王居一焉，百日为程。
任叟书授刘生:承欲往梁宋，梁宋灾方重，旦夕为人讼。承欲访郑生，郑生将有厄。即为千里客，兼亦变衫色。
昌明里中谶:欲知修续者，脚下是生毛。
宋善威诗:月落三株树，日映九重天。良夜欢宴罢，暂别庚申年。
田承嗣诳李宝臣伪谶:二帝同功势万全，将田作伴入幽燕。
皮日休造黄巢谶:欲知圣人姓，由八二十一。欲知圣人名，果头三屈律。
附：上元初嵩山石记:木子当天下，止戈龙。李代代不移宗，中鼎显真容，基千万岁。
上阳铜器篆:长宜子孙。
永安渠石铭:百年为市后为池。
漳泉分地神篆:漳泉两州，分地太平。永安龙溪，山高气清。千年不惑，万古作程。
含元殿丹石隐语:天汉二年，赤光生栗。木下有子，伤心遇酷。
长安空宅铭篆:夏天子紫金三十斤，赐有德者。
莆田石记:石敢当，镇百鬼，压灾殃。官吏福，百姓康。风教盛，礼乐昌。
符离树穴中石篆:旁有水，上有道，八百年中逢栲栳。
淮西池濠石铭:井底一竿竹，竹色深绿绿。鸡未肥，酒未熟，障车儿郎且须缩。
罗池石刻:龙城柳，神所守。驱厉鬼，山左首。福土氓，制九丑。
"""

**Comment by amahendrakar** [comment]
@jxfruit,
On running the code with TF v1.15, I am facing a different error stating `ZeroDivisionError: float division by zero`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/dcedc3c02106b6a486c9a20ea0bedbb6/40176.ipynb#scrollTo=vhm2uGOU0uHG). 

Could you please upgrade to TF v1.15 and let us know if the issue is resolved. Thanks!

**Comment by jxfruit** [comment]
@amahendrakar thanks a lot for your reply. I update TF v1.13 to TF v1.15, but I still get the same error, which is different from yours. I am so confused. By the way, our cpu is kunpeng 920 based on aarch64. I am not sure whether our chip is something wrong or not. And I cannot open your website,  may you provide a file with it. tks again!

**Comment by amahendrakar** [comment]
@jxfruit,
Value of the variable `n_chunk` was 0, hence I was facing the `ZeroDivisionError`. 

On replacng the line 
`print('epoch:', epoch, ' Loss: ', all_loss * 1.0 / n_chunk)` with 
`print('epoch:', epoch, ' Loss: ', all_loss * 1.0 / 1)`, I was able to run the code without any issues. 

Please take a look at the Python notebook attached below. 
[40176.zip](https://github.com/tensorflow/tensorflow/files/4768727/40176.zip)

Thanks!

**Comment by jxfruit** [comment]
@amahendrakar After checking the code, I found  the problem. There were only 33 poems, namely 33 data, because of the following code block:
```python
batch_size=64
n_chunk = len(poems_vector) // batch_size
print(n_chunk)
```
Obviously, n_chunk will got 0. After changing batch_size from 64 to 8 will be ok.
And I found the data is not enough, that could not get the error. When my dataset is more than 10Mb, the error can be got. Sadly, I could not upload the whole dataset. Could you produce more data to evaluate it, for example, repeating the data 1000 times?
tks!

**Comment by amahendrakar** [comment]
@jxfruit,
Even after repeating the data, I did not face any issues while running the code. Please check the attached zip file for the Python notebook. Thanks!

[40176.zip](https://github.com/tensorflow/tensorflow/files/4772659/40176.zip)

**Comment by jxfruit** [comment]
@amahendrakar hi，could I  know your experiment environment ? Mine is based HUAWEI KUNPENG920. Is this causing the problem?

**Comment by amahendrakar** [comment]
@jxfruit,
I have used [Google Colab](https://colab.research.google.com/) to run the code.

**Comment by jxfruit** [comment]
@amahendrakar @gowthamkpr Is your env  based on arm64 cpu? On x86-64 cpu, my codes is fine.

**Comment by amahendrakar** [comment]
@jxfruit,
> I have used [Google Colab](https://colab.research.google.com/) to run the code.

The platform I was running on was bacsed on x86_64 architecture.

**Comment by jxfruit** [comment]
@amahendrakar It runs good on x86_64 architecture, and the problem is on aarch64 architecture, tks

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
