### ISSUE TITLE
build failed on CentOS-7 @flatbuffers//:flatc' #1660 

### ISSUE THREAD

**Issue by cheers00** [tensorflow/tensorflow#40170]
## Bug Report
Getting the following error while building.

```
ERROR: /build/external/flatbuffers/BUILD.bazel:60:1: 
Linking of rule '@flatbuffers//:flatc' failed (Exit 1)

```

Re: #1563
this bug also reported the same issue but with building docker. Here, I am not building any docker.

### System information
- **OS Platform and Distribution (e.g., CentOS Linux 7)**:
- **TensorFlow repo (source v2.2.0)**:

### Describe the problem
Getting the above build error
### Exact Steps to Reproduce
clone and checkout the tag v2.2.0
./configure
<accept all defaults>
`bazel --output_base=$build_dir build --config=mkl //tensorflow/tools/pip_package:build_pip_package`

### Source code / logs
```
INFO: From Compiling external/snappy/snappy-stubs-internal.cc:
cc1plus: warning: command line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for C++
ERROR: /build/external/swig/BUILD.bazel:5:1: Linking of rule '@swig//:swig' failed (Exit 1)
bazel-out/host/bin/external/swig/_objs/swig/allocate.o:allocate.cxx:function Allocate::~Allocate(): error: undefined reference to 'operator delete(void*, unsigned long)'
bazel-out/host/bin/external/swig/_objs/swig/contract.o:contract.cxx:function Contracts::~Contracts(): error: undefined reference to 'operator delete(void*, unsigned long)'
bazel-out/host/bin/external/swig/_objs/swig/lang.o:lang.cxx:function Language::~Language(): error: undefined reference to 'operator delete(void*, unsigned long)'
bazel-out/host/bin/external/swig/_objs/swig/module.o:module.cxx:function Swig_register_module(char const*, Language* (*)()) [clone .cold.0]: error: undefined reference to 'operator delete(void*, unsigned long)'
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 87.968s, Critical Path: 69.22s
INFO: 4631 processes: 4631 local.
FAILED: Build did NOT complete successfully
```

**Comment by Saduf2019** [comment]
@cheers00 
Please refer to this issue and let us know if it helps:
#36170

**Comment by cheers00** [comment]
@Saduf2019 thank you.
I tried following build options mentioned in #36170 but I still get the same error.
```
--linkopt=-lm  
--host_linkopt=-lm
```

BTW, this is happening in CentOS only. I could build without any problem on Ubuntu 20.04.

**Comment by paperwhite** [comment]
I get the same issue on centos 7. My gcc version is 7.3, and I am using the master branch for the build. I added flags for mkl and avx enablement, and --host-linkopt=-lm & --linkopt=-lm option, but that didn't help either.

**Comment by sanatmpa1** [comment]
@cheers00,

Here's a similar [issue](https://github.com/bazelbuild/bazel/issues/10575#issuecomment-592647616) where they explained the cause may be due to incompatible version of different tools in build environment. We recommend you build the latest stable version of tensorflow i.e 2.6.0 using tested configurations in this [guide](https://www.tensorflow.org/install/source#tested_build_configurations) and let us know if it helps. Thanks!
