### ISSUE TITLE
ImportError: cannot import name 'function_pb2'

### ISSUE THREAD

**Issue by sangmeshcp** [tensorflow/tensorflow#40182]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CENTOS 7.8
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source(Master)
- TensorFlow version: 2.2
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): Build label: 3.0.0
- GCC/Compiler version (if compiling from source): gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC) 
- CUDA/cuDNN version: 10.2
- GPU model and memory: NVIDIA (TESLA M60)

**Describe the problem**

hittiing the following error after succesful bazel build.
INFO: 0 processes.
INFO: Build completed successfully
./bazel-bin/tensorflow/tools/pip_package/build_pip_package --nightly_flag /tmp/tensorflow_pkg

pip install /tmp/tensorflow_pkg/tensorflow-2.2.0-cp36-cp36m-linux_x86_64.whl 
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
ImportError: No module named eager

 import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nobackup/tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/nobackup/tensorflow/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/nobackup/tensorflow/tensorflow/python/eager/context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
ImportError: cannot import name 'function_pb2'

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
ImportError: No module named eager

**Comment by OdysseeT** [comment]
got the same here after a successful build on:

`import tensorflow as tf`

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/begood/Documents/tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/begood/Documents/tensorflow/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/home/begood/Documents/tensorflow/tensorflow/python/eager/context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
ImportError: cannot import name 'function_pb2' from 'tensorflow.core.framework' (unknown location)

python 3.8
tf: 2.2 - build with cuda
gcc: 8
bazel: 3.0.0

**Comment by youngtf** [comment]
I got the same problem related to 'function_pb2' after compiling TensorFlow. It is likely because I was still at the TensorFlow source folder, so that python was searching that folder instead of loading the installed package I guess? When I change to another directory (e.g., $HOME), I can successfully import the installed TF without error.

**Comment by ymodak** [comment]
@sangmeshcp Is this still an issue? If yes, does the suggestion posted by @youngtf work for your case?

**Comment by saifullah3396** [comment]
> I got the same problem related to 'function_pb2' after compiling TensorFlow. It is likely because I was still at the TensorFlow source folder, so that python was searching that folder instead of loading the installed package I guess? When I change to another directory (e.g., $HOME), I can successfully import the installed TF without error.

This worked for me. Thanks!

**Comment by AhmedEwis** [comment]
> directory

Hello,
can you explain what do you mean by "When I change to another directory (e.g., $HOME)" 
Thanks

**Comment by youngtf** [comment]
> > directory
> 
> Hello,
> can you explain what do you mean by "When I change to another directory (e.g., $HOME)"
> Thanks

@AhmedEwis 

E.g. `cd ~`. 
Or you may find more detail at https://www.techrepublic.com/article/linux-directory-navigation-tips-and-tricks/.
I hope it helps.

**Comment by shilan** [comment]
> I got the same problem related to 'function_pb2' after compiling TensorFlow. It is likely because I was still at the TensorFlow source folder, so that python was searching that folder instead of loading the installed package I guess? When I change to another directory (e.g., $HOME), I can successfully import the installed TF without error.

Thanks, even with Jupyter worked. I change the directory to the tensorflow installation directory and ran the python 3 from there and it started working :)

**Comment by ymodak** [comment]
Closing this issue since setting tensorflow installation directory correctly solves the problem and lack of response from the issue author.
Feel free to reopen if required. Thanks!

**Comment by dileepdanger** [comment]
i'm not getting hhow to resolve it

**Comment by amahendrakar** [comment]
@dileepdanger,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by taechanha** [comment]
@dileepdanger 
type **cd ~**
