### ISSUE TITLE
GPU build configuration doesn't work with Debian-packaged cuda/cudnn packages

### ISSUE THREAD

**Issue by fcahoon** [tensorflow/tensorflow#4018]
I'm on a Debian 'sid' linux computer and I am attempting to build a GPU-enabled version of TensorFlow using the Debian-packaged versions of the Nvidia libraries.

The CUDA packages are from Debian's non-free repository, e.g. https://packages.debian.org/sid/nvidia-cuda-toolkit and cuDNN I installed from using the .deb packages available from Nvidia's site (libcudnn5_5.1.3-1+cuda7.5_amd64.deb  and libcudnn5-dev_5.1.3-1+cuda7.5_amd64.deb).

These packages put the libraries and include files in standard system locations, so there is no CUDA_TOOLKIT_PATH or CUDNN_INSTALL_PATH to speak of, as this ldconfig output shows:

forrest@makemake:~$ /sbin/ldconfig -p | grep 'cud'
    libicudata.so.57 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libicudata.so.57
    libicudata.so.55 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libicudata.so.55
    libicudata.so.55 (libc6) => /usr/lib/i386-linux-gnu/libicudata.so.55
    libicudata.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libicudata.so
    libcudnn.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn.so.5
    libcudnn.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn.so
    libcudart.so.7.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudart.so.7.5
    libcudart.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudart.so
    libcuda.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so.1
    libcuda.so.1 (libc6) => /usr/lib/i386-linux-gnu/libcuda.so.1
    libcuda.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so
    libcuda.so (libc6) => /usr/lib/i386-linux-gnu/libcuda.so

I have attempted to hack the configure file to support this default Debian configuration, but so far bazel always seems to expect CUDA_INSTALL_DIR to be set.

**Comment by akors** [comment]
For starters, you should show which error messages you run into.

**Comment by aselle** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

**Comment by cnschn** [comment]
I'm having the same issue as @fcahoon and will try to add some more information on what the problem is.

I'm on Debian 8 (Jessie), cuda toolkit 7.5 and cudNN 5.1. The cuda toolkit was, however, not installed using the installer from Nvidia, but via the system package manager (in my case from the jessie-backports repo, in @fcahoon's case using the .deb packages directly downloaded from Nvidia). This places all cuda libraries in standard system locations as shown above instead of bunching them together in, e.g. `/usr/local/cuda/`.

Now, trying to build tf from source (I cloned the git repo and checked out tag `v1.2.0`), the `./configure` script asks for the cuda toolkit location:

```
[...]
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Do you want to use clang as CUDA compiler? [y/N] N
nvcc will be used as CUDA compiler
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 7.5
Please specify the location where CUDA 7.5 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
```

but there is no "installation location" to speak of, and the build would not really need any, as `#include <cuda.h>` and `-lcuda` work just fine without any path specifications (all files being in standard locations).

The exact command to reproduce is thus just `./configure` on a system with cuda installed from the `.deb` packages.

**Comment by byronyi** [comment]
Same issue here. Could we support standard FHS compatible installation of CUDA in our configure script? That would be nice to a lot of people.

**Comment by VictorQueiroz** [comment]
Same problem here also, any solutions?

**Comment by Mte90** [comment]
I can confirm the issue.
I hacked a little bit the `.tf_configure.bazelrc` file with the debian path:

```
build --action_env PYTHON_BIN_PATH="/usr/bin/python3"
build --action_env PYTHON_LIB_PATH="/usr/lib/python3/dist-packages"
build --force_python=py3
build --host_force_python=py3
build --python_path="/usr/bin/python3"
build --define with_jemalloc=true
build:gcp --define with_gcp_support=true
build:hdfs --define with_hdfs_support=true
build:s3 --define with_s3_support=true
build:kafka --define with_kafka_support=true
build --define with_xla_support=true
build --define with_gdr_support=true
build --define with_verbs_support=true
build --action_env TF_NEED_OPENCL_SYCL="0"
build --action_env TF_NEED_CUDA="1"
build --action_env CUDA_TOOLKIT_PATH="/usr/include/"
build --action_env TF_CUDA_VERSION="9.1"
build --action_env CUDNN_INSTALL_PATH="/usr/lib/x86_64-linux-gnu/"
build --action_env TF_CUDNN_VERSION="7"
build --action_env TF_NCCL_VERSION="1"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="6.1"
build --action_env TF_CUDA_CLANG="1"
build --action_env TF_DOWNLOAD_CLANG="0"
build --action_env CLANG_CUDA_COMPILER_PATH="/usr/bin/clang"
build --config=cuda_clang
test --config=cuda_clang
build --define grpc_no_ares=true
build:opt --copt=-march=native
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
build --copt=-DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK
build --host_copt=-DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK
```

I also added few symbolic links because I have CUDA 9.1:
```
ln -s /usr/lib/x86_64-linux-gnu/libcublas.so.9.1 /usr/lib/x86_64-linux-gnu/libcublas.so.9.0
ln -s /usr/lib/x86_64-linux-gnu/libcusolver.so.9.1 /usr/lib/x86_64-linux-gnu/libcusolver.so.9.0
ln -s /usr/lib/x86_64-linux-gnu/libcudart.so.9.1 /usr/lib/x86_64-linux-gnu/libcudart.so.9.0
ln -s /usr/lib/x86_64-linux-gnu/libcufft.so.9.1 /usr/lib/x86_64-linux-gnu/libcufft.so.9.0
ln -s /usr/lib/x86_64-linux-gnu/libcurand.so.9.1 /usr/lib/x86_64-linux-gnu/libcurand.so.9.0
```

In my case ignoring this last part I get when I try bazel:
```
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "/home/mte90/Desktop/kde/tensorflow/third_party/gpus/cuda_configure.bzl", line 1142
                _create_local_cuda_repository(repository_ctx)
        File "/home/mte90/Desktop/kde/tensorflow/third_party/gpus/cuda_configure.bzl", line 997, in _create_local_cuda_repository
                _find_cuda_include_path(repository_ctx, cuda_config)
        File "/home/mte90/Desktop/kde/tensorflow/third_party/gpus/cuda_configure.bzl", line 688, in _find_cuda_include_path
                auto_configure_fail(("Cannot find cuda.h under %s" %...))
        File "/home/mte90/Desktop/kde/tensorflow/third_party/gpus/cuda_configure.bzl", line 210, in auto_configure_fail
                fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Cannot find cuda.h under /usr/include
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "/home/mte90/Desktop/kde/tensorflow/third_party/gpus/cuda_configure.bzl", line 1142
                _create_local_cuda_repository(repository_ctx)
        File "/home/mte90/Desktop/kde/tensorflow/third_party/gpus/cuda_configure.bzl", line 997, in _create_local_cuda_repository
                _find_cuda_include_path(repository_ctx, cuda_config)
        File "/home/mte90/Desktop/kde/tensorflow/third_party/gpus/cuda_configure.bzl", line 688, in _find_cuda_include_path
                auto_configure_fail(("Cannot find cuda.h under %s" %...))
        File "/home/mte90/Desktop/kde/tensorflow/third_party/gpus/cuda_configure.bzl", line 210, in auto_configure_fail
                fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Cannot find cuda.h under /usr/include
INFO: Elapsed time: 0.168s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
```

Useless to say that the file /usr/include/cuda.h` exist but for bazel seems not...
