### ISSUE TITLE
Importing tensorflow using python -c causes segmentation fault on interpreter exit

### ISSUE THREAD

**Issue by RunOrVeith** [tensorflow/tensorflow#40186]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.8.0b4
- CUDA/cuDNN version: 10.2
- GPU model and memory: Quadro P2000

**Describe the current behavior**:
Running  `python -c "import tensorflow"` results in a segmentation fault:

`[1]    25266 segmentation fault (core dumped)  python -c "import tensorflow"`

**Describe the expected behavior**
No segmentation fault happens, the program just exits.

**Standalone code to reproduce the issue**

Run `python -c "import tensorflow"` using python 3.8.

I found the issue because I was running tensorflow in a subprocess like this:

```python
import subprocess


def call_subprocess_command(*command):
    with subprocess.Popen(args=command, text=True, shell=False,
                          stdout=subprocess.PIPE, stderr=subprocess.STDOUT) as process:
        assert process.stdout is not None
        for line in iter(process.stdout.readline, ""):
            line = line.strip()
            print("(subprocess)", line)

    if process.returncode != 0:
        raise RuntimeError(f"{command} failed with exit code {process.returncode}")


call_subprocess_command("python", "-X", "faulthandler", "-c", "import tensorflow;print(tensorflow.__version__)")
```

This prints the version, thus indicating that the segmentation fault happens when the interpreter exits.
```
(subprocess) 2.2.0
(subprocess) Fatal Python error: Segmentation fault
(subprocess) 
(subprocess) Current thread 0x00007fe3c40f0080 (most recent call first):
Traceback (most recent call last):
  File "/home/veith/.config/JetBrains/PyCharm2020.1/scratches/scratch.py", line 16, in <module>
    call_subprocess_command("python", "-X", "faulthandler", "-c", "import tensorflow;print(tensorflow.__version__)")
  File "/home/veith/.config/JetBrains/PyCharm2020.1/scratches/scratch.py", line 13, in call_subprocess_command
    raise RuntimeError(f"{command} failed with exit code {process.returncode}")
RuntimeError: ('python', '-X', 'faulthandler', '-c', 'import tensorflow;print(tensorflow.__version__)') failed with exit code -11

Process finished with exit code 1
```

**Comment by amahendrakar** [comment]
@RunOrVeith,
Could you update to the stable version of TensorFlow 2.2 and let us know if you are facing the same issue. Thanks!

**Comment by RunOrVeith** [comment]
I assume you meant "upgrade to a stable version of python", and it does ondeed only seem to be a problem in python 3.8.0b4.
I get the expected output using python 3.8.3, so maybe this is also a big that has since been fixed inside the python interpreter.

**Comment by amahendrakar** [comment]
> I assume you meant "upgrade to a stable version of python"

@RunOrVeith,
You have mentioned in the issue template that you are using TensorFlow release candidate v2.2 rc4 (released on Apr 30, 2020). Hence, I suggest you to check with the stable version TensorFlow v2.2 (released on May 7, 2020). 




>I get the expected output using python 3.8.3, so maybe this is also a big that has since been fixed inside the python interpreter.

Is this still an issue? Please feel free to close the issue if resolved. Thanks!
