### ISSUE TITLE
No documentatio non how to manipulate a python.data.ops.dataset_oops.BatchDataset

### ISSUE THREAD

**Issue by Cillinc** [tensorflow/tensorflow#40188]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://keras.io/api/preprocessing/image/

## Description of issue (what needs changing):
the documentation says that the object returned from the tf.keras.preprocessing.image_dataset_from_directory function is a tf.data.Dataset object.  However, there is no documentation on how to manipulate it or get details how to use it. I
### Clear description
I have a large dataset and i am trying to split it into testing and training, however while i can "complete a validation split in the  function (as documented) this is no documentation on how I can address the training or validation subsets.  Should i convert the objects to np array or can it be manipulated within TF and if so how?

### Correct links

Is the link to the source code correct?

### Parameters defined

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    wk_dir,
    labels="inferred",
    label_mode="int",
    class_names=None,
    color_mode="grayscale",
    batch_size=batches,
    image_size=image_dim,
    shuffle=True,
    seed=1968,
    validation_split=0.2,
    subset="training",
    interpolation="bilinear",
    follow_links=False,
)

### Returns defined

Found 127842 files belonging to 3 classes.
Using 102274 files for training.

print(type(train_ds))
<class 'tensorflow.python.data.ops.dataset_ops.BatchDataset'>

what are the attributes which can be used to , get details and possible split this object type?
AttributeError: 'BatchDataset' object has no attribute 'eval'

**Comment by luozhouyang** [comment]
I think the function returns an instance of `tf.data.BatchDataset`, you can read the documents of `tf.data` API here [tf.data](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#batch).

**Comment by Saduf2019** [comment]
@Cillinc 
Please update as per above comment

**Comment by Cillinc** [comment]
thanks - i am reading the documentation and struggling to get things to work.  if it is a tf.datch.BatchDataset then i will continue to work with the documentation.  one would assume that one of the most common things people did once they imported files into a TF was to split them into training and validation....but this is not clear in the documentation as to how to do it.  I have set the , validation_split=0.2,
    subset="validation", 
and that works, but i do not see how to address the subsets and `AttributeError: 'BatchDataset' object has no attribute 'subset'`
so working ahead and trying everything i can find......

**Comment by GerritMaarten** [comment]
Try making two sets one for training and one for validation. (I include my setup in COLAB).

By the way do you have any idea how to extract class_names and labels that are derived from the sub-directories? I need that to decode the outcome when I test an image. I have no idea how to get that working, yet.

 I am new in CNN so I cannot explain most of the issues. Got this together by trial and error.

<pre>
import numpy as np
import IPython.display as display 
from PIL import Image
import matplotlib.pyplot as plt
import os
import IPython.display as display
import glob

!pip install tf-nightly --quiet

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import preprocessing
import time

image_size = (331,331)
batch_size = 32
train_ds=` tf.keras.preprocessing.image_dataset_from_directory(
    "/content/drive/My Drive/AR",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    batch_size=batch_size,
    image_size=image_size,
    color_mode =  "rgb",
    shuffle=True,
    seed=142,
    validation_split=0.2,
    subset= "training",
    interpolation="bilinear",
    follow_links=False,
)

validation_ds= tf.keras.preprocessing.image_dataset_from_directory(
    "/content/drive/My Drive/AR",
    labels="inferred",
    label_mode="categorical",
    batch_size=batch_size,
    image_size=image_size,
     color_mode =  "rgb",
    shuffle=True,
    seed=142,
    validation_split=0.2,
    subset= "validation",
    interpolation="bilinear",
    follow_links=False,
    )
</pre>
That results in:
<pre>Found 34 files belonging to 3 classes.
Using 28 files for training.
Found 34 files belonging to 3 classes.
Using 6 files for validation.
</pre>

Those two sets can then be entered in your convnet. Below what I use.
<pre>
#Note: num_classes must be similar to the train_ds dataset 3 in this particular case.

data_augmentation = keras.Sequential([
  layers.experimental.preprocessing.RandomFlip('horizontal'),
  layers.experimental.preprocessing.RandomRotation(0.1),
])

train_ds = train_ds.prefetch(buffer_size=32)
validation_ds = validation_ds.prefetch(buffer_size=32)
model = tf.keras.applications.InceptionResNetV2(input_shape=(331,331, 3), include_top=False, weights='imagenet')

def make_model(input_shape, num_classes):
  inputs = keras.Input(shape=input_shape)
  # Image augmentation block
  x = data_augmentation(inputs)

  # Entry block
  x = layers.experimental.preprocessing.Rescaling(1./255)(x)
  x = model(x)

  previous_block_activation = x  # Set aside residual

  x = layers.GlobalAveragePooling2D()(x)
  if num_classes == 2:
    activation = 'sigmoid'
    units = 1
  else:
    activation = 'softmax'
    units = num_classes
  
  x = layers.Dropout(0.5)(x)
  outputs = layers.Dense(units, activation=activation)(x)
  return keras.Model(inputs, outputs)

model = make_model(input_shape=image_size + (3,), num_classes=3)
keras.utils.plot_model(model, show_shapes=True)
</pre>

Now that is my model. Below code for training en storing the best model on your googleDrive for later tests.

<pre>
epochs = 10
#model = make_model(input_shape=image_size + (3,), num_classes=3)
file_path = "/content/drive/My Drive/TrainedNetwork/."

checkpoint = tf.keras.callbacks.ModelCheckpoint("/content/drive/My Drive/TrainedNetwork/model-{epoch:03d}-{accuracy:03f}-{val_accuracy:03f}.h5", verbose=1, monitor='val_loss',save_best_only=True, mode='auto')  

#model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.compile(optimizer=keras.optimizers.Adam(1e-3),
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(train_ds, epochs=epochs, validation_data=validation_ds, callbacks=[checkpoint], verbose=2)
</pre>

**Comment by Cillinc** [comment]
thanks in my case I was not worried about what values were given to the class names - just that there was 3 classes which the model could work with.  SO i used each of the subdirectories as their own classes and it is working for me.  

now my only problem is that the image files are all B&W and the distinguishing attributes to tell one class from another is not enough for the model i have.  So might have to rethink things and put 3 filters into a RGB type image and try again......but this is the fun of things - and also a great way to learn.

**Comment by Saduf2019** [comment]
@Cillinc 
As you have a solution, should we move this issue to closed status

**Comment by Cillinc** [comment]
thanks for thew suport!!!!!
