### ISSUE TITLE
How to feed multi tf.data.Dataset objects into a multi-input/output model in tensorflow

### ISSUE THREAD

**Issue by IscaAy** [tensorflow/tensorflow#40194]
I how to deal with multi input/output when the input is numpy arrays. However, my inputs are all tf.data.datasets objects. And I would like to feed the latter into a multi-input/output in tensorflow keras 2.1. 

    def prepare_dataset(...):
        X_train = tf.data.Dataset.from_tensor_slices(final_df_QS_normalized_train_val)
        X_train = X_train.window(train_window_length, shift=1, drop_remainder=True)
        X_train = X_train.flat_map(lambda window : window.batch(train_window_length))
        X_train = X_train.shuffle(100, seed=42)
        X_train = X_train.batch(batch_size)

        y_train = tf.data.Dataset.from_tensor_slices(final_df_DQ_normalized_train_val)
        y_train = y_train.window(train_window_length, shift=1, drop_remainder=True)
        y_train = y_train.flat_map(lambda window : window.batch(train_window_length))
        y_train = y_train.shuffle(100, seed=42)
        y_train = y_train.batch(batch_size)

        sample_weights_train = tf.data.Dataset.from_tensor_slices(sample_weights_df_train_val)
        sample_weights_train = sample_weights_train.window(train_window_length, shift=1, drop_remainder=True)
        sample_weights_train = sample_weights_train.flat_map(lambda window : window.batch(train_window_length))
        sample_weights_train = sample_weights_train.shuffle(100, seed=42)
        sample_weights_train = sample_weights_train.batch(batch_size)
        ..... # the same is applied to the validation data part....
        return X_train, y_train, sample_weights_train

Then I have a method that creates a model and return the input/output as follows:

    def build_uncomplied_model(hparams, CASE_UPC_CD):
        inputs = tf.keras.Input(shape=(None, 1), name=CASE_UPC_CD + "_input")
        x = inputs

        if hparams['model_uncertainty']:
                x = layers.Bidirectional(layers.LSTM(hparams["cell_size_1"], return_sequences=True, 
                                                    dropout=hparams['dropout']), merge_mode=hparams['merge_mode'])(x, training=True)
        else:
                x = layers.Bidirectional(layers.LSTM(hparams["cell_size_1"], return_sequences=True, 
                                                    dropout=hparams['dropout']))(x)

        outputs = layers.TimeDistributed(layers.Dense(1), name=CASE_UPC_CD + "_output")(x)

        return inputs, outputs

Then inside a for loop, I created a multiple of this model. All inputs/outputs are stored in a list to be used later in model creation. 

    c = 0
    for CASE_UPC_CD in tqdm(final_df_QS_normalized_train.columns.values):
        c += 1
        logdir = os.path.join(ROOT_DIR, "logs_SeparateLSTMs", time_now, CASE_UPC_CD)

        X_train, y_train, sample_weights_train, X_valid, y_valid, sample_weights_valid = \
                                                       prepare_dataset(final_df_QS_normalized_train[CASE_UPC_CD], 
                                                       final_df_DQ_normalized_train[CASE_UPC_CD], 
                                                       final_df_QS_normalized_valid[CASE_UPC_CD], 
                                                       final_df_DQ_normalized_valid[CASE_UPC_CD], 
                                                       sample_weights_df_train[CASE_UPC_CD], 
                                                       sample_weights_df_valid[CASE_UPC_CD], hparams)

        train_input[CASE_UPC_CD + "_input"] = X_train
        train_output[CASE_UPC_CD + "_output"] = y_train

        valid_input[CASE_UPC_CD + "_input"] = X_valid
        valid_output[CASE_UPC_CD + "_output"] = y_valid

        inputs, outputs = build_uncomplied_model(hparams, CASE_UPC_CD)

        inputs_all.append(inputs)
        outputs_all.append(outputs)

        if c == 10:
            break

    train_dataset = tf.data.Dataset.from_tensor_slices((train_input, train_output))
    valid_dataset = tf.data.Dataset.from_tensor_slices((valid_input, valid_output))

This last line is throwing an error:

    ValueError: Unbatching a dataset is only supported for rank >= 1

How to solve this issue? Any help is much appreciated

**Comment by Saduf2019** [comment]
@IscaAy 
I ran the code shared, please find the gist of the same [here](https://colab.sandbox.google.com/gist/Saduf2019/f13d15dca62cf3cceee53485bc3c61d7/untitled208.ipynb). please provide complete stand alone code such that we can replicate the issue faced or if possible share a colab gist.
