### ISSUE TITLE
Rolled RNN cannot be converted to INT8

### ISSUE THREAD

**Issue by MatteoArm** [tensorflow/tensorflow#40199]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.4 LTS
- TensorFlow installed from (source or binary): tf-nightly
- TensorFlow version (use command below): 2.2.0.dev20200508 (also happens with 2.3.0.dev20200605)
- Python version: 3.7.4

**Describe the current behavior**
When converting a rolled RNN model to INT8, the conversion fails with the following error:

```
TypeError: pybind11::init(): factory function returned nullptr
During handling of the above exception, another exception occurred:
...
ValueError: Failed to parse the model: pybind11::init(): factory function returned nullptr.
```

**Describe the expected behavior**
The conversion should be successful.

**Standalone code to reproduce the issue**
Please find the gist [here](https://colab.research.google.com/gist/MatteoArm/02a4f032cab5b58a414d741b78107de1/untitled0.ipynb)

**Other info / logs** Include any logs or source code that would be helpful to
My traceback:

```
Traceback (most recent call last):
  File "/opt/anaconda/3/envs/P3.7.4_TF2.2.0.dev20200508/lib/python3.7/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 51, in __init__
    _calibration_wrapper.CalibrationWrapper(model_content))
TypeError: pybind11::init(): factory function returned nullptr

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rnn_rolled_issue.py", line 83, in <module>
    tflite_model_INT8 = converter.convert()
  File "/opt/anaconda/3/envs/P3.7.4_TF2.2.0.dev20200508/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 639, in convert
    output_tensors)
  File "/opt/anaconda/3/envs/P3.7.4_TF2.2.0.dev20200508/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 505, in convert
    constants.FLOAT, True)
  File "/opt/anaconda/3/envs/P3.7.4_TF2.2.0.dev20200508/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 337, in _calibrate_quantize_model
    calibrate_quantize = _calibrator.Calibrator(result)
  File "/opt/anaconda/3/envs/P3.7.4_TF2.2.0.dev20200508/lib/python3.7/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 53, in __init__
    raise ValueError("Failed to parse the model: %s." % e)
ValueError: Failed to parse the model: pybind11::init(): factory function returned nullptr.
```

**Comment by Saduf2019** [comment]
@MatteoArm  
Please refer to these links and let us know if it helps.
[link]((https://github.com/NVIDIA/TensorRT/issues/308))
[link1](https://github.com/traveller59/torch2trt/issues/1#issuecomment-492603147)

**Comment by MatteoArm** [comment]
@Saduf2019 Thanks for the suggestion, but this seems to be a different issue.
It looks like the problem here originates in the python bindings for the CalibrationWrapper, or in the CalibrationWrapper class itself.

**Comment by karimnosseir** [comment]
Renjie, can you take a look.

Thanks

**Comment by renjie-liu** [comment]
looks like the problem is related to pybind?

**Comment by renjie-liu** [comment]
Hi YC, do you have any idea about this?

Thanks!

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF 2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/571b08d82ee6459c4e6716035fbbf197/untitled325.ipynb) ..Thanks!

**Comment by mohantym** [comment]
Hi @MatteoArm ! This issue is not replicating in Latest version (TF 2.7) now. Attaching [Gist](https://colab.sandbox.google.com/gist/mohantym/d4d87d7c6172789be22fd0b19a977918/untitled325.ipynb#scrollTo=effYrDkvO4qA) for reference .Thanks!
