### ISSUE TITLE
Unit test //tensorflow/python:session_clusterspec_prop_test fails because eager execution is incompatible with tf.placeholder()

### ISSUE THREAD

**Issue by Sidong-Wei** [tensorflow/tensorflow#40205]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v2.2.0-0-g2b96f3662b 2.2.0
- Python version: 3.8.2
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
The test case `//tensorflow/python:session_clusterspec_prop_test` fails with the following log (Partial log, see [test.log](https://github.com/tensorflow/tensorflow/files/4738058/test.log) for the full log):
```
[ RUN      ] SessionClusterSpecPropagationTest.testClusterSpecPropagationIsolation
2020-06-03 11:07:09.469162: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:46629}
2020-06-03 11:07:09.470895: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:390] Started server with target: grpc://localhost:46629
[  FAILED  ] SessionClusterSpecPropagationTest.testClusterSpecPropagationIsolation

======================================================================
ERROR: testClusterSpecPropagationIsolation (__main__.SessionClusterSpecPropagationTest)
testClusterSpecPropagationIsolation (__main__.SessionClusterSpecPropagationTest)
Test that two sessions using ClusterSpec propagation are isolated.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sidong/.cache/bazel/_bazel_sidong/9ef871a29c692fc6a18121463529e145/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/session_clusterspec_prop_test.runfiles/org_tensorflow/tensorflow/python/client/session_clusterspec_prop_test.py", line 416, in testClusterSpecPropagationIsolation
    init_value = array_ops.placeholder(dtypes.int32, shape=[])
  File "/home/sidong/.cache/bazel/_bazel_sidong/9ef871a29c692fc6a18121463529e145/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/session_clusterspec_prop_test.runfiles/org_tensorflow/tensorflow/python/ops/array_ops.py", line 3023, in placeholder
    raise RuntimeError("tf.placeholder() is not compatible with "
RuntimeError: tf.placeholder() is not compatible with eager execution.
``` 

**Describe the expected behavior**
The test case should pass.

**Standalone code to reproduce the issue**
`bazel --host_jvm_args="-Xms1024m" --host_jvm_args="-Xmx2048m" test --host_javabase="@local_jdk//:jdk" -k --build_tests_only --test_output=errors -- //tensorflow/python:session_clusterspec_prop_test`

**Other info / logs** 
As the error message suggested, the error is caused by eager-execution. It seems to me that in this test case, eager execution should be disabled (as it is enabled by default in Tensorflow 2.x). Modifying the test file as following will knock down the error, and the test will pass.
```
diff --git a/tensorflow/python/client/session_clusterspec_prop_test.py b/tensorflow/python/client/session_clusterspec_prop_test.py
index f33b9129b8..7b0344d73e 100644
--- a/tensorflow/python/client/session_clusterspec_prop_test.py
+++ b/tensorflow/python/client/session_clusterspec_prop_test.py
@@ -563,4 +563,5 @@ class SessionClusterSpecPropagationTest(test_util.TensorFlowTestCase):
 
 
 if __name__ == '__main__':
+  ops.disable_eager_execution()
   googletest.main()
```
Please let me know if I should PR this fix, or if there is another way of disabling eager execution (or maybe do not use `tf.placeholder()`?). Thanks.

Sidong

**Comment by haoyuz** [comment]
Thanks for reporting!

As documented [here](https://www.tensorflow.org/api_docs/python/tf/compat/v1/placeholder) the placeholder is not compatible with eager execution so this test is not enabled in the TF2 release. We do not test it with explicitly disabling eager in TF2, but will keep having this case covered in the TF1 testing.

**Comment by Sidong-Wei** [comment]
Good to know that, thank you for confirming this, I will neglect this failure in the test results for 2.x version.
