### ISSUE TITLE
"Inconsistent CUDA toolkit path: /usr vs /usr/lib" when running ./configure

### ISSUE THREAD

**Issue by DoxasticFox** [tensorflow/tensorflow#40202]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version: v2.2.0 (2b96f3662bd776e277f86997659e61046b56c315)
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: No
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): 8.3.0
- CUDA/cuDNN version: 10.1/7.6.5
- GPU model and memory: GeForce GTX 1070 and 8192 MB

**Describe the problem**

I receive the error "Inconsistent CUDA toolkit path: /usr vs /usr/lib" when running `./configure`. I believe I should not receive the error.

**Any other info / logs**

Console output:

```
~/tensorflow % ./configure
You have bazel 2.0.0 installed.
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python3


Found possible Python library paths:
  /usr/local/lib/python3.7/dist-packages
  /usr/lib/python3.7/dist-packages
  /usr/lib/python3/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python3.7/dist-packages]

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: 
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: 
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: 
No TensorRT support will be enabled for TensorFlow.

Inconsistent CUDA toolkit path: /usr vs /usr/libAsking for detailed CUDA configuration... ^C
```

At the time of writing, the error comes from [`third_party/gpus/find_cuda_config.py:292`](https://github.com/tensorflow/tensorflow/blob/255f590ab64e637f49288883013d35efa0633b35/third_party/gpus/find_cuda_config.py#L292). The error occurs because, on my system, `cuda_binary_dir` evaluates to `/usr/bin`, while `nvvm_library_dir` evaluates to `/usr/lib/nvidia-cuda-toolkit/libdevice`. Although I'm using Debian 10, which isn't officially supported, this error can also occur in Ubuntu 20.04 if the user installed `nvcc` via the [`nvidia-cuda-toolkit`](https://packages.ubuntu.com/focal/amd64/nvidia-cuda-toolkit/filelist) package, which installs `nvcc` in two locations:

* `/usr/bin/nvcc`
* `/usr/lib/nvidia-cuda-toolkit/bin/nvcc`

~~The solution I tentatively suggest is to remove the consistency check from `find_cuda_config.py` because it's merely a heuristic. As a result, the check might cause `./configure` to proceed when it should exit early, or to exit early when it should proceed.~~

---
**Edit:** As pointed out by @tensorfoo and @ambertide, removing the consistency check doesn't work. A more reliable workaround is to install the cuda toolkit using Nvidia's .run file installer.

**Comment by DoxasticFox** [comment]
For whoever might have had the same problem: I was able to compile TensorFlow by uninstalling the `nvidia-cuda-toolkit` package in my package manager and installing CUDA using Nvidia's .run file installer. It may have also been possible to use their .deb package, but it required me to downgrade my graphics card driver. AFAIK, there's no practical reason for Nvidia's package to require a downgrade; it's just slightly ham-fisted dependency management on Nvidia's part.

Although I was able to work around my issue, I don't consider it properly solved because, seeing as Ubuntu is officially supported by TensorFlow, one would expect it to work with the CUDA drivers available directly from Ubuntu's software repository.

**Comment by gunan** [comment]
@chsigg FYI

**Comment by chsigg** [comment]
Hi Christian, thanks for reporting this issue. 

There is a TODO on line [third_party/gpus/find_cuda_config.py:286](https://github.com/tensorflow/tensorflow/blob/255f590ab64e637f49288883013d35efa0633b35/third_party/gpus/find_cuda_config.py#L286) that this needs some work. 

We now do pass in both `cuda_binary_dir` and `nvvm_library_dir` directories, so I think what would need to happen is to replace each use of `cuda_toolkit_path` with one of the two and then remove `cuda_toolkit_path`. 

As it stands now, we probably require that `cuda_toolkit_path` contains both nvvm libs and binaries.

Does this make sense, and would you be able and willing to write a PR to fix this?

**Comment by DoxasticFox** [comment]
@chsigg Thanks for getting back to me. What you said makes sense. Unfortunately I don't have time to raise a PR right now. I hope that I can in a few weekends from now, unless someone else would like to work on it sooner.

**Comment by tensorfoo** [comment]
ran into this trying to build 1.15, tried the solution of removing the check suggested but the build fails early with a `ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):`

**Comment by ambertide** [comment]
Honestly, this just points on the direction of the unnecessarily hard procedure to install, build or do anything with Tensorflow, or anything ML oriented in general. I have also run into this issue while trying to build 1.14 with 10.1/7.6.5, the path that brought me here was one of frustration, two times I had to reinstall the Nvidia drivers, my resolution fell to 1024 at one point, another time my apt completely broke, twice, who knows maybe I am just frustrated and unable to perform basic tasks, but it seems to me that this entire process is a tad bit harder than it should be.

**Comment by DoxasticFox** [comment]
@ambertide I started working on this issue over the weekend. I don't think it's completely TensorFlow's fault. The `nvidia-cuda-toolkit` package strangely spreads its libraries and executables throughout the file system. Part of the CUDA toolkit gets put into `/usr/lib/cuda`, part of it goes into `/usr/lib/nvidia-cuda-toolkit`, and some other bits go into `/usr/bin`. And there's also a few files which are wrappers which run executables in other directories. They could have been symlinks, but instead they're wrappers. I think Nvidia's .run file installer puts files in more sensible locations. TensorFlow works better with it, anyway.

That said, TensorFlow can circumvent all the Nvidia driver madness by just doing what PyTorch does and bundling the drivers with the Python module.

**Comment by ambertide** [comment]
> @ambertide I started working on this issue over the weekend. I don't think it's completely TensorFlow's fault. The `nvidia-cuda-toolkit` package strangely spreads its libraries and executables throughout the file system. Part of the CUDA toolkit gets put into `/usr/lib/cuda`, part of it goes into `/usr/lib/nvidia-cuda-toolkit`, and some other bits go into `/usr/bin`. And there's also a few files which are wrappers which run executables in other directories. They could have been symlinks, but instead they're wrappers. I think Nvidia's .run file installer puts files in more sensible locations. TensorFlow works better with it, anyway.
> 
> That said, TensorFlow can circumvent all the Nvidia driver madness by just doing what PyTorch does and bundling the drivers with the Python module.

Yeah, I guess I was being a bit unfair, also to add for people who may stumble upon this in the future, sadly removing the consistency check for 1.14 does not resolve the problem. It continues to say 'cuda.h' was not found.

**Comment by ClonedOne** [comment]
Just encountered what seems to be the same problem on Ubuntu 20.04 with cuda 10.1 and nvidia driver 440.1.
My error message is `Inconsistent CUDA toolkit path: /usr/lib/nvidia-cuda-toolkit vs /usr/lib/cudaAsking for detailed CUDA configuration...` 

Is there any update/workaround for this issue?

**Comment by chsigg** [comment]
Would it be possible for you to install NVIDIA's CUDA Toolkit in a single directory from NVIDIA’s .run package with

```
$ wget https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.105_418.39_linux.run
$ sudo sh cuda_10.1.105_418.39_linux.run --silent --toolkit --toolkitpath=/usr/local/cuda
```

**Comment by ClonedOne** [comment]
Thank you for the reply. Unfortunately I'm not an admin on the machine, so I was hoping in some workaround from the TF side. In the meantime I'll try to contact an admin.

**Comment by chsigg** [comment]
If you aren't su, you can install the toolkit into a different folder, where you have write permission.

**Comment by mohantym** [comment]
Hi @DoxasticFox !
We are checking to see whether you still need help in this issue . Have you tried above [suggestion](https://github.com/tensorflow/tensorflow/issues/40202#issuecomment-663435110) yet? Thanks!

**Comment by DoxasticFox** [comment]
@mohantym I just gave up.
