### ISSUE TITLE
MKL does not work with tensorflow 2.2.0

### ISSUE THREAD

**Issue by liyinhgqw** [tensorflow/tensorflow#40208]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.2.0
- Python version: N/A
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): devtoolset-7 on centos 7
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
We have built tensorflow 2.2.0 framework and jni targets from source with `--config=mkl`. When we run models, logs show that MKL is not enabled even though there are few symbols of mkl.
[tensorflow log](https://github.com/tensorflow/tensorflow/blob/r2.2/tensorflow/core/platform/cpu_feature_guard.cc#L143)

```
nm -D libtensorflow_framework.so | grep -i mkl | wc -l
     173

```
**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
BAZEL_LINKLIBS=-l%:libstdc++.a bazel build -c opt --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 --copt=-O3 \
      --copt=-Wformat --copt=-Wformat-security --copt=-fstack-protector --copt=-fPIC --copt=-fpic --linkopt=-znoexecstack --linkopt=-zrelro --linkopt=-znow --linkopt=-fstack-protector \
      --copt=-msse4.2 --copt=-mavx \
      --config=mkl \
      --linkopt -ldl \
      --copt=-march=x86-64 \
      --config=v2 \
      //tensorflow/tools/lib_package:libtensorflow_jni \
      //tensorflow/tools/lib_package:libtensorflow \
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

We were using Docker to compile and build the targets.
We used the same commands without `--config=v2` to successfully build tensorflow 1.15 with MKL enabled. It has 15718 mkl related symbols.

**Comment by pavanky** [comment]
@ashahab @preethivenkatesh @penpornk The fix from https://github.com/tensorflow/tensorflow/issues/36717#issuecomment-602733323 doesnt seem to work and we are still facing the same issue as 1.15

Would you be able to provide some help ?

**Comment by penpornk** [comment]
Sorry to hear that! I've assigned this issue to the @TensorFlow-MKL team (@ashahba is from the team).

**Comment by agramesh1** [comment]
@penpornk and @pavnky Thanks for reporting the issue, sorry for the delay. I will have someone look at and get back to you ASAP.

**Comment by NeoZhangJianyu** [comment]
@penpornk  @pavanky @agramesh1 I will check this issue as soon.

**Comment by penpornk** [comment]
@agramesh1 @NeoZhangJianyu Thank you very much!

**Comment by preethivenkatesh** [comment]
@pavanky I can reproduce and verified your docker build instructions to display the same number of mkl symbols. however, regarding the warning message not displaying Intel MKLDNN support, we have found this issue in tf2.1(now appearing in tf2.2 as well), which appeared to be cosmetic and didn't impact the performance. We are already started investigating this issue last week and will try to provide a fix to the messaging ASAP. Alternatively, you can check if MKLDNN is enabled by running this command 
```
python -c 'from tensorflow.python import _pywrap_util_port;    print("MKL enabled :", _pywrap_util_port.IsMklEnabled())'
```
I verified the mkl symbols and the warning message in the baremetal build as well, which matches the behavior as that of the docker build (175 MKL symbols, and no Intel MKLDNN warning)

**Comment by penpornk** [comment]
> however, regarding the warning message not displaying Intel MKLDNN support, we have found this issue in tf2.1(now appearing in tf2.2 as well), which appeared to be cosmetic and didn't impact the performance. We are already started investigating this issue last week and will try to provide a fix to the messaging ASAP.

The issue is because `-DINTEL_MKL` did not get passed to `cpu_feature_guard.cc`. (To pass `-DINTEL_MKL` configuration, the BUILD file needs to add `copts = tf_copts()` for the target `//tensorflow/core/platform:cpu_feature_guard`.) 

Since both vanilla TF and TF-MKL uses MKL-DNN at the time, I removed the `INTEL_MKL` guard and made both display the same message (saying MKL-DNN is used) in:  https://github.com/tensorflow/tensorflow/commit/95f92b6d33b7b405c5c327a68c216a5a5b5d9f93. Unfortunately, this fix was after the TF 2.2.0 branch cut, so the message is still wrong in 2.2.0.

**Comment by nammbash** [comment]
@penpornk @preethivenkatesh Let me do this change to the PR associated with the cpu_feature_gaurd here https://github.com/tensorflow/tensorflow/pull/40330#discussion_r439675263

**Comment by penpornk** [comment]
@nammbash Sounds great! (Although it sounds like we could use one string for both again. See [here](https://github.com/tensorflow/tensorflow/pull/40330#discussion_r439659273).)

**Comment by pavanky** [comment]
@preethivenkatesh we dont have a wheel ready with MKL right now, just the java jar file. Is there a way to test it from Java ?

**Comment by preethivenkatesh** [comment]
unfortunately we don't have the `IsMklEnabled()` support for java due to limited usage. Is it possible to run java jar file on a sample workload? setting mkldnn verbose path variable might be helpful, using `export MKLDNN_VERBOSE=1` before running a sample workload produces verbose MKLDNN logs if mkl is enabled

**Comment by pavanky** [comment]
> Since both vanilla TF and TF-MKL uses MKL-DNN at the time, I removed the INTEL_MKL guard and made both display the same message (saying MKL-DNN is used) in: 95f92b6. Unfortunately, this fix was after the TF 2.2.0 branch cut, so the message is still wrong in 2.2.0.

@preethivenkatesh @penpornk considering this comment, will we notice any difference in TF vs TF-MKL with this environment variable set ?

**Comment by preethivenkatesh** [comment]
yes, @pavanky you will still continue to see differences in the speed, the MKL op that is primarily upstreamed into the vanilla TF is for MatMul, but the MKLDNN-TF has a lot more set of ops supported that are not upstreamed yet.

**Comment by liyinhgqw** [comment]
@preethivenkatesh @penpornk  We have run some workload tests and seen the difference. Thanks.
