### ISSUE TITLE
Improving Google Indexing for the Documentation

### ISSUE THREAD

**Issue by kocabey** [tensorflow/tensorflow#4021]
Whenever I run a Google search on a TensorFlow functionality, say, `tf.reshape`, it gives me the entire documentation, not the specific documentation related to that functionality. 

Currently the way I use is  to run a search with `ctrl` + `f` to find specific documentation related to what I search for. 

Numpy has that property, i.e. when you run a Google search on `np.reshape`, you get the specific page.

It would be a nice improvement for the documentation if someone fixes the Google indexing for the documentation page, especially for the users who frequently use Google search for the documentation.

**Comment by mrry** [comment]
@wolffg Is this something that might be addressed by the upcoming changes to documentation?

**Comment by gunan** [comment]
(With delayed move to new docs) it did help
When I search for `tf.reshape`, the first result I get is to tensorflow documentation in the new TF website.
