### ISSUE TITLE
"tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value" on aarch64

### ISSUE THREAD

**Issue by Danliran** [tensorflow/tensorflow#40213]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):1.15.0
- Python version:2.7
- Bazel version (if compiling from source):0.26.0
- GCC/Compiler version (if compiling from source):7.4.0
- CUDA/cuDNN version: no
- GPU model and memory:no

**Describe the current behavior**

I used [tensorflow/benchmark](https://github.com/tensorflow/benchmarks) to train resnet50 by [tf_cnn_benchmarks.py](https://github.com/tensorflow/benchmarks/blob/master/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py) on my aarch64 platform.
command line:
python tf_cnn_benchmarks.py --device=cpu --data_format=NHWC --optimizer=sgd --distortions=false --variable_update=replicated --data_dir=/opt/imagenet/tf_train --data_name=imagenet --model=resnet50 --batch_size=32 --train_dir=/opt/data/resnet50_ckpt/cpu_v1/  --num_epochs=10--save_model_steps=20

**Describe the expected behavior**
After training thousands batchs raise "tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value"

> INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Retval[0] does not have value
I0605 18:58:49.349148 281473050139600 coordinator.py:224] Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Retval[0] does not have value
Traceback (most recent call last):
  File "tf_cnn_benchmarks.py", line 73, in <module>
    app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
  File "/root/.env/tf2.0.0/lib/python2.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/root/.env/tf2.0.0/lib/python2.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "tf_cnn_benchmarks.py", line 68, in main
    bench.run()
  File "/home/tf/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1880, in run
    return self._benchmark_train()
  File "/home/tf/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2085, in _benchmark_train
    return self._benchmark_graph(result_to_benchmark, eval_build_results)
  File "/home/tf/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2294, in _benchmark_graph
    is_chief, summary_writer, profiler)
  File "/home/tf/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2430, in benchmark_with_session
    collective_graph_key=collective_graph_key)
  File "/home/tf/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 869, in benchmark_one_step
    results = sess.run(fetches, options=run_options, run_metadata=run_metadata)
  File "/root/.env/tf2.0.0/lib/python2.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/root/.env/tf2.0.0/lib/python2.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/.env/tf2.0.0/lib/python2.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/root/.env/tf2.0.0/lib/python2.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value

**Comment by ravikyram** [comment]
@Danliran 

Request you share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by Danliran** [comment]
> @Danliran
> 
> Request you share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

@ravikyram thanks for response. tf_cnn_benchmarks.py
 https://github.com/tensorflow/benchmarks/blob/master/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py 
here is command to training resnet50 from tensorflow/benchmarks guideline. 
python tf_cnn_benchmarks.py --device=cpu --data_format=NHWC --optimizer=sgd --distortions=false --variable_update=replicated --data_dir=/opt/imagenet/tf_train --data_name=imagenet --model=resnet50 --batch_size=32 --train_dir=/opt/data/resnet50_ckpt/cpu_v1/ --num_epochs=10--save_model_steps=20

**Comment by Danliran** [comment]
@ravikyram strace log about training, hope it can help you.

> openat(AT_FDCWD, "tf_cnn_benchmarks.py", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=2476, ...}) = 0
read(3, "# Copyright 2017 The TensorFlow "..., 4096) = 2476
write(2, "    ", 4    )                     = 4
write(2, "app.run(main)  # Raises error on"..., 68app.run(main)  # Raises error on invalid flags, unlike tf.app.run()
) = 68
close(3)                                = 0
write(2, "  File \"/root/.env/tf1.15/lib/py"..., 85  File "/root/.env/tf1.15/lib/python2.7/site-packages/absl/app.py", line 299, in run
) = 85
openat(AT_FDCWD, "/root/.env/tf1.15/lib/python2.7/site-packages/absl/app.py", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=14864, ...}) = 0
read(3, "# Copyright 2017 The Abseil Auth"..., 4096) = 4096
read(3, "ilar to HelpfullFlag, but genera"..., 4096) = 4096
read(3, "\n        logging.error(traceback"..., 4096) = 4096
write(2, "    ", 4    )                     = 4
write(2, "_run_main(main, args)\n", 22_run_main(main, args)
) = 22
close(3)                                = 0
write(2, "  File \"/root/.env/tf1.15/lib/py"..., 91  File "/root/.env/tf1.15/lib/python2.7/site-packages/absl/app.py", line 250, in _run_main
) = 91
openat(AT_FDCWD, "/root/.env/tf1.15/lib/python2.7/site-packages/absl/app.py", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=14864, ...}) = 0
read(3, "# Copyright 2017 The Abseil Auth"..., 4096) = 4096
read(3, "ilar to HelpfullFlag, but genera"..., 4096) = 4096
write(2, "    ", 4    )                     = 4
write(2, "sys.exit(main(argv))\n", 21sys.exit(main(argv))
)  = 21
close(3)                                = 0
write(2, "  File \"tf_cnn_benchmarks.py\", l"..., 48  File "tf_cnn_benchmarks.py", line 68, in main
) = 48
openat(AT_FDCWD, "tf_cnn_benchmarks.py", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=2476, ...}) = 0
read(3, "# Copyright 2017 The TensorFlow "..., 4096) = 2476
write(2, "    ", 4    )                     = 4
write(2, "bench.run()\n", 12bench.run()
)           = 12
close(3)                                = 0
write(2, "  File \"/home/tf/benchma"..., 99  File "/home/tf/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1880, in run
) = 99
openat(AT_FDCWD, "/home/tf/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=164060, ...}) = 0
read(3, "# Copyright 2017 The TensorFlow "..., 4096) = 4096
read(3, "\n#   the forward-only option, wh"..., 4096) = 4096
read(3, "            'The autotune thresh"..., 4096) = 4096
read(3, "                'the number of s"..., 4096) = 4096
read(3, "ed, after the graph has been par"..., 4096) = 4096
read(3, " maximum number of GPU Ops that "..., 4096) = 4096
read(3, "or the MultiDeviceIterator that "..., 4096) = 4096
read(3, "INE_integer('kmp_settings', 1,\n "..., 4096) = 4096
read(3, "            'collective_all_redu"..., 4096) = 4096
read(3, "s.')\nflags.DEFINE_integer('save_"..., 4096) = 4096
read(3, "pointNotFoundException(Exception"..., 4096) = 4096
read(3, "params.eval_during_training_at_s"..., 4096) = 4096
read(3, "filename, ''\n      as_text = fil"..., 4096) = 4096
read(3, "\n                         (name,"..., 4096) = 4096
read(3, "loat(piece))\n      except ValueE"..., 4096) = 4096
read(3, "tf.train.RMSPropOptimizer(\n     "..., 4096) = 4096
read(3, "rning_rate_decay_factor)):\n     "..., 4096) = 4096
read(3, "d not self.params.datasets_use_p"..., 4096) = 4096
read(3, ".sync_queue_devices = [self.para"..., 4096) = 4096
read(3, "eter_server'):\n      raise Value"..., 4096) = 4096
read(3, "onstants.BenchmarkMode.TRAIN_AND"..., 4096) = 4096
read(3, "d batches per prepocessing group"..., 4096) = 4096
read(3, "ame: %s' % self.params.job_name)"..., 4096) = 4096
write(2, "    ", 4    )                     = 4
write(2, "return self._benchmark_train()\n", 31return self._benchmark_train()
) = 31
close(3)                                = 0
write(2, "  File \"/home/tf/benchma"..., 112  File "/home/tf/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2085, in _benchmark_train
) = 112
openat(AT_FDCWD, "/home/tf/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=164060, ...}) = 0
read(3, "# Copyright 2017 The TensorFlow "..., 4096) = 4096
read(3, "\n#   the forward-only option, wh"..., 4096) = 4096
read(3, "            'The autotune thresh"..., 4096) = 4096
read(3, "                'the number of s"..., 4096) = 4096
read(3, "ed, after the graph has been par"..., 4096) = 4096
read(3, " maximum number of GPU Ops that "..., 4096) = 4096
read(3, "or the MultiDeviceIterator that "..., 4096) = 4096
read(3, "INE_integer('kmp_settings', 1,\n "..., 4096) = 4096
read(3, "            'collective_all_redu"..., 4096) = 4096
read(3, "s.')\nflags.DEFINE_integer('save_"..., 4096) = 4096
read(3, "pointNotFoundException(Exception"..., 4096) = 4096
read(3, "params.eval_during_training_at_s"..., 4096) = 4096
read(3, "filename, ''\n      as_text = fil"..., 4096) = 4096
read(3, "\n                         (name,"..., 4096) = 4096
read(3, "loat(piece))\n      except ValueE"..., 4096) = 4096
read(3, "tf.train.RMSPropOptimizer(\n     "..., 4096) = 4096
read(3, "rning_rate_decay_factor)):\n     "..., 4096) = 4096
read(3, "d not self.params.datasets_use_p"..., 4096) = 4096
read(3, ".sync_queue_devices = [self.para"..., 4096) = 4096
read(3, "eter_server'):\n      raise Value"..., 4096) = 4096
read(3, "onstants.BenchmarkMode.TRAIN_AND"..., 4096) = 4096
read(3, "d batches per prepocessing group"..., 4096) = 4096
read(3, "ame: %s' % self.params.job_name)"..., 4096) = 4096
read(3, "not None:\n        # We might rei"..., 4096) = 4096
read(3, "f.batch_size)\n      mlperf.logge"..., 4096) = 4096
write(2, "    ", 4    )                     = 4
write(2, "return self._benchmark_graph(res"..., 70return self._benchmark_graph(result_to_benchmark, eval_build_results)
) = 70
close(3)                                = 0
write(2, "  File \"/home/tf/benchma"..., 112  File "/home/tf/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2294, in _benchmark_graph
) = 112
openat(AT_FDCWD, "/home/tf/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=164060, ...}) = 0
read(3, "# Copyright 2017 The TensorFlow "..., 4096) = 4096
read(3, "\n#   the forward-only option, wh"..., 4096) = 4096
read(3, "            'The autotune thresh"..., 4096) = 4096
read(3, "                'the number of s"..., 4096) = 4096
read(3, "ed, after the graph has been par"..., 4096) = 4096
read(3, " maximum number of GPU Ops that "..., 4096) = 4096
read(3, "or the MultiDeviceIterator that "..., 4096) = 4096
read(3, "INE_integer('kmp_settings', 1,\n "..., 4096) = 4096
read(3, "            'collective_all_redu"..., 4096) = 4096
read(3, "s.')\nflags.DEFINE_integer('save_"..., 4096) = 4096
read(3, "pointNotFoundException(Exception"..., 4096) = 4096
read(3, "params.eval_during_training_at_s"..., 4096) = 4096
read(3, "filename, ''\n      as_text = fil"..., 4096) = 4096
read(3, "\n                         (name,"..., 4096) = 4096
read(3, "loat(piece))\n      except ValueE"..., 4096) = 4096
read(3, "tf.train.RMSPropOptimizer(\n     "..., 4096) = 4096
read(3, "rning_rate_decay_factor)):\n     "..., 4096) = 4096
read(3, "d not self.params.datasets_use_p"..., 4096) = 4096
read(3, ".sync_queue_devices = [self.para"..., 4096) = 4096
read(3, "eter_server'):\n      raise Value"..., 4096) = 4096
read(3, "onstants.BenchmarkMode.TRAIN_AND"..., 4096) = 4096
read(3, "d batches per prepocessing group"..., 4096) = 4096
read(3, "ame: %s' % self.params.job_name)"..., 4096) = 4096
read(3, "not None:\n        # We might rei"..., 4096) = 4096
read(3, "f.batch_size)\n      mlperf.logge"..., 4096) = 4096
read(3, "ributed_collective) and\n        "..., 4096) = 4096
read(3, ".broadcast_global_variables(0)\n "..., 4096) = 4096
write(2, "    ", 4    )                     = 4
write(2, "is_chief, summary_writer, profil"..., 36is_chief, summary_writer, profiler)
) = 36
close(3)                                = 0
write(2, "  File \"/home/tf/benchma"..., 118  File "/home/tf/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2430, in benchmark_with_session
) = 118
openat(AT_FDCWD, "/home/tf/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=164060, ...}) = 0
read(3, "# Copyright 2017 The TensorFlow "..., 4096) = 4096
read(3, "\n#   the forward-only option, wh"..., 4096) = 4096
read(3, "            'The autotune thresh"..., 4096) = 4096
read(3, "                'the number of s"..., 4096) = 4096
read(3, "ed, after the graph has been par"..., 4096) = 4096
read(3, " maximum number of GPU Ops that "..., 4096) = 4096
read(3, "or the MultiDeviceIterator that "..., 4096) = 4096
read(3, "INE_integer('kmp_settings', 1,\n "..., 4096) = 4096
read(3, "            'collective_all_redu"..., 4096) = 4096
read(3, "s.')\nflags.DEFINE_integer('save_"..., 4096) = 4096
read(3, "pointNotFoundException(Exception"..., 4096) = 4096
read(3, "params.eval_during_training_at_s"..., 4096) = 4096
read(3, "filename, ''\n      as_text = fil"..., 4096) = 4096
read(3, "\n                         (name,"..., 4096) = 4096
read(3, "loat(piece))\n      except ValueE"..., 4096) = 4096
read(3, "tf.train.RMSPropOptimizer(\n     "..., 4096) = 4096
read(3, "rning_rate_decay_factor)):\n     "..., 4096) = 4096
read(3, "d not self.params.datasets_use_p"..., 4096) = 4096
read(3, ".sync_queue_devices = [self.para"..., 4096) = 4096
read(3, "eter_server'):\n      raise Value"..., 4096) = 4096
read(3, "onstants.BenchmarkMode.TRAIN_AND"..., 4096) = 4096
read(3, "d batches per prepocessing group"..., 4096) = 4096
read(3, "ame: %s' % self.params.job_name)"..., 4096) = 4096
read(3, "not None:\n        # We might rei"..., 4096) = 4096
read(3, "f.batch_size)\n      mlperf.logge"..., 4096) = 4096
read(3, "ributed_collective) and\n        "..., 4096) = 4096
read(3, ".broadcast_global_variables(0)\n "..., 4096) = 4096
read(3, "      named tensors/ops list, fe"..., 4096) = 4096
read(3, "fo.execution_barrier:\n          "..., 4096) = 4096
write(2, "    ", 4    )                     = 4
write(2, "collective_graph_key=collective_"..., 43collective_graph_key=collective_graph_key)
) = 43
close(3)                                = 0
write(2, "  File \"/home/tf/benchma"..., 113  File "/home/tf/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 869, in benchmark_one_step
) = 113
openat(AT_FDCWD, "/home/tf/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=164060, ...}) = 0
read(3, "# Copyright 2017 The TensorFlow "..., 4096) = 4096
read(3, "\n#   the forward-only option, wh"..., 4096) = 4096
read(3, "            'The autotune thresh"..., 4096) = 4096
read(3, "                'the number of s"..., 4096) = 4096
read(3, "ed, after the graph has been par"..., 4096) = 4096
read(3, " maximum number of GPU Ops that "..., 4096) = 4096
read(3, "or the MultiDeviceIterator that "..., 4096) = 4096
read(3, "INE_integer('kmp_settings', 1,\n "..., 4096) = 4096
read(3, "            'collective_all_redu"..., 4096) = 4096
read(3, "s.')\nflags.DEFINE_integer('save_"..., 4096) = 4096
read(3, "pointNotFoundException(Exception"..., 4096) = 4096
read(3, "params.eval_during_training_at_s"..., 4096) = 4096
write(2, "    ", 4    )                     = 4
write(2, "results = sess.run(fetches, opti"..., 76results = sess.run(fetches, options=run_options, run_metadata=run_metadata)
) = 76
close(3)                                = 0
write(2, "  File \"/root/.env/tf1.15/lib/py"..., 114  File "/root/.env/tf1.15/lib/python2.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
) = 114
openat(AT_FDCWD, "/root/.env/tf1.15/lib/python2.7/site-packages/tensorflow_core/python/client/session.py", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=69365, ...}) = 0
read(3, "# Copyright 2015 The TensorFlow "..., 4096) = 4096
read(3, "d to feed a run, `feed_fn2` to s"..., 4096) = 4096
read(3, ", tensor_type):\n      raise Valu"..., 4096) = 4096
read(3, ": Callable as returned by a fetc"..., 4096) = 4096
read(3, "ass.\n    \"\"\"\n    values = _get_a"..., 4096) = 4096
read(3, "\n    i = 0\n    j = 0\n    for is_"..., 4096) = 4096
read(3, "dles = []\n\n    if config is None"..., 4096) = 4096
read(3, "\n\n  @property\n  def sess_str(sel"..., 4096) = 4096
read(3, "he value of tensors in the graph"..., 4096) = 4096
write(2, "    ", 4    )                     = 4
write(2, "run_metadata_ptr)\n", 18run_metadata_ptr)
)     = 18
close(3)                                = 0
write(2, "  File \"/root/.env/tf1.15/lib/py"..., 116  File "/root/.env/tf1.15/lib/python2.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
) = 116
openat(AT_FDCWD, "/root/.env/tf1.15/lib/python2.7/site-packages/tensorflow_core/python/client/session.py", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=69365, ...}) = 0
read(3, "# Copyright 2015 The TensorFlow "..., 4096) = 4096
read(3, "d to feed a run, `feed_fn2` to s"..., 4096) = 4096
read(3, ", tensor_type):\n      raise Valu"..., 4096) = 4096
read(3, ": Callable as returned by a fetc"..., 4096) = 4096
read(3, "ass.\n    \"\"\"\n    values = _get_a"..., 4096) = 4096
read(3, "\n    i = 0\n    j = 0\n    for is_"..., 4096) = 4096
read(3, "dles = []\n\n    if config is None"..., 4096) = 4096
read(3, "\n\n  @property\n  def sess_str(sel"..., 4096) = 4096
read(3, "he value of tensors in the graph"..., 4096) = 4096
read(3, "tionary\n        whose values are"..., 4096) = 4096
read(3, "d Session.')\n    if self.graph.v"..., 4096) = 4096
write(2, "    ", 4    )                     = 4
write(2, "feed_dict_tensor, options, run_m"..., 41feed_dict_tensor, options, run_metadata)
) = 41
close(3)                                = 0
write(2, "  File \"/root/.env/tf1.15/lib/py"..., 119  File "/root/.env/tf1.15/lib/python2.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
) = 119
openat(AT_FDCWD, "/root/.env/tf1.15/lib/python2.7/site-packages/tensorflow_core/python/client/session.py", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=69365, ...}) = 0
read(3, "# Copyright 2015 The TensorFlow "..., 4096) = 4096
read(3, "d to feed a run, `feed_fn2` to s"..., 4096) = 4096
read(3, ", tensor_type):\n      raise Valu"..., 4096) = 4096
read(3, ": Callable as returned by a fetc"..., 4096) = 4096
read(3, "ass.\n    \"\"\"\n    values = _get_a"..., 4096) = 4096
read(3, "\n    i = 0\n    j = 0\n    for is_"..., 4096) = 4096
read(3, "dles = []\n\n    if config is None"..., 4096) = 4096
read(3, "\n\n  @property\n  def sess_str(sel"..., 4096) = 4096
read(3, "he value of tensors in the graph"..., 4096) = 4096
read(3, "tionary\n        whose values are"..., 4096) = 4096
read(3, "d Session.')\n    if self.graph.v"..., 4096) = 4096
read(3, "d_list)` arguments whose types\n "..., 4096) = 4096
read(3, "session.TF_DeleteBuffer(run_meta"..., 4096) = 4096
write(2, "    ", 4    )                     = 4
write(2, "run_metadata)\n", 14run_metadata)
)         = 14
close(3)                                = 0
write(2, "  File \"/root/.env/tf1.15/lib/py"..., 120  File "/root/.env/tf1.15/lib/python2.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
) = 120
openat(AT_FDCWD, "/root/.env/tf1.15/lib/python2.7/site-packages/tensorflow_core/python/client/session.py", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=69365, ...}) = 0
read(3, "# Copyright 2015 The TensorFlow "..., 4096) = 4096
read(3, "d to feed a run, `feed_fn2` to s"..., 4096) = 4096
read(3, ", tensor_type):\n      raise Valu"..., 4096) = 4096
read(3, ": Callable as returned by a fetc"..., 4096) = 4096
read(3, "ass.\n    \"\"\"\n    values = _get_a"..., 4096) = 4096
read(3, "\n    i = 0\n    j = 0\n    for is_"..., 4096) = 4096
read(3, "dles = []\n\n    if config is None"..., 4096) = 4096
read(3, "\n\n  @property\n  def sess_str(sel"..., 4096) = 4096
read(3, "he value of tensors in the graph"..., 4096) = 4096
read(3, "tionary\n        whose values are"..., 4096) = 4096
read(3, "d Session.')\n    if self.graph.v"..., 4096) = 4096
read(3, "d_list)` arguments whose types\n "..., 4096) = 4096
read(3, "session.TF_DeleteBuffer(run_meta"..., 4096) = 4096
read(3, "ssage, self._graph)\n      if 'on"..., 4096) = 4096
write(2, "    ", 4    )                     = 4
write(2, "raise type(e)(node_def, op, mess"..., 37raise type(e)(node_def, op, message)
) = 37
close(3)                                = 0
write(2, "tensorflow.python.framework.erro"..., 39tensorflow.python.framework.errors_impl) = 39
write(2, ".", 1.)                        = 1
write(2, "InvalidArgumentError", 20InvalidArgumentError)    = 20
write(2, ": ", 2: )                       = 2
write(2, "Retval[0] does not have value", 29Retval[0] does not have value) = 29
write(2, "\n", 1
)                       = 1
unlinkat(AT_FDCWD, "/tmp/tmp5HeJNi.py", 0) = 0
unlinkat(AT_FDCWD, "/tmp/tmpuWUoTb.py", 0) = 0
unlinkat(AT_FDCWD, "/tmp/tmpRaOsTY.py", 0) = 0
unlinkat(AT_FDCWD, "/tmp/tmpt0VBwu.py", 0) = 0
unlinkat(AT_FDCWD, "/tmp/tmpZMqsKy.py", 0) = 0
unlinkat(AT_FDCWD, "/tmp/tmpl2wn88.py", 0) = 0
unlinkat(AT_FDCWD, "/tmp/tmpcDvUvG.py", 0) = 0
unlinkat(AT_FDCWD, "/tmp/tmpgPPLwh.py", 0) = 0
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, {sa_handler=0xaaaada8a4260, sa_mask=[], sa_flags=0}, 8) = 0
munmap(0xfffd94779000, 262144)          = 0
munmap(0xfffd8d1bc000, 262144)          = 0
munmap(0xfffd8d33b000, 262144)          = 0
munmap(0xfffd946f9000, 262144)          = 0
munmap(0xfffdac6f9000, 262144)          = 0
munmap(0xfffd8d2bb000, 262144)          = 0
munmap(0xffff77141000, 262144)          = 0
munmap(0xfffd8cefc000, 262144)          = 0
munmap(0xfffda4339000, 262144)          = 0
close(11)                               = 0
futex(0xffff8071a674, FUTEX_WAKE_PRIVATE, 2147483647) = 0
fstat(0, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
fstat(0, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
fstat(0, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
exit_group(1)                           = ?
+++ exited with 1 +++

**Comment by gowthamkpr** [comment]
@Danliran Please post this issue in [tensorflow/benchmarks](https://github.com/tensorflow/benchmarks/issues) as the issue is related to benchmarks. Thanks!

**Comment by Danliran** [comment]
@gowthamkpr do you have any idear about this issue.  post it in tensorflow/benchmarks https://github.com/tensorflow/benchmarks/issues/479

**Comment by gowthamkpr** [comment]
@Danliran Sorry for pointing you out to multiple repos. But as mentioned in [comment](https://github.com/tensorflow/benchmarks/issues/479#issuecomment-640967838) please try to post it [here](https://github.com/tensorflow/models/issues) as well as they would be able to help you. I will keep this issue open here. Thanks!

**Comment by Danliran** [comment]
@gowthamkpr That`s all right, If this issue reproduce  in [TensorFlow Official Models ](https://github.com/tensorflow/models/tree/master/official), I will post it to tensorflow/models.

**Comment by gowthamkpr** [comment]
Sure. Thanks!
