### ISSUE TITLE
MobileNetV3

### ISSUE THREAD

**Issue by CRosero** [tensorflow/tensorflow#40217]
**System information**
- TensorFlow version (you are using): tf-nightly 2.2.0.dev20200508 
- Are you willing to contribute it (Yes/No): Would be willing to but I've never contributed code to an open sourced project.

**Describe the feature and the current behavior/state.**
I want to do transfer learning using MobileNetV3. I see on [here](https://github.com/keras-team/keras-applications/blob/master/keras_applications/mobilenet_v3.py) that MobileNetV3 is available, but I don't see it either in the [Keras website](https://keras.io/applications/) or on [TF.](https://www.tensorflow.org/api_docs/python/tf/keras/applications?version=nightly) Why is this? 

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Everyone

**Comment by qlzh727** [comment]
It seems that the code was added to keras-team/keras, but hasn't been port to tf/keras yet. We will fix it and make the pre-trained weight available.

**Comment by CRosero** [comment]
Hi, it's almost been 2 months since the last post. Are there any updates? 

I would really, really appreciate if you could port it to tf/keras because I need it for my experimentation as soon as possible.

**Comment by tanzhenyu** [comment]
> Hi, it's been almost 2 months since the last post. Are there any updates?
> 
> I would really, really appreciate if you could port it to tf/keras because I need it for my experimentation as soon as possible.

This has been done just now, please try out in tf-nightly

**Comment by CRosero** [comment]
Hi, thank you very much for the commit and for the response! 

I upgraded tf-nightly and am now in version 2.4.0.dev20200809, but sadly when I tried it out I got: 

"AttributeError: module 'tensorflow.keras.applications' has no attribute 'mobilenet_v3' "

**Comment by yixingfu** [comment]
> Hi, thank you very much for the commit and for the response!
> 
> I upgraded tf-nightly and am now in version 2.4.0.dev20200809, but sadly when I tried it out I got:
> 
> "AttributeError: module 'tensorflow.keras.applications' has no attribute 'mobilenet_v3' "

It's in 2.4.0-dev20200810. Please try again.

**Comment by CRosero** [comment]
Thank you, now it's working! I still have 3 points to address: 

1. Using the exact same parameters, dataset and identical conditions (other than the model itself used) I trained a minimalistic MobileNetV3 with alpha of 1.0 using the imagenet weights, freezing the feature extractor layers, I get a around 53% accuracy while with MobileNetV2 with alpha 1.0 I get around X% accuracy. Have you also faced similar issues?
2. When I try to run the network with lower alphas I get the following error: "". Why is this limitation present? Would be curious to understand that a bit more in depth.
3. There is a misspelling in the function

**Comment by qlzh727** [comment]
> Thank you, now it's working!
> 
> I still have 3 points to address:
> 
> 1. Using the exact same parameters, dataset and identical conditions (other than the model itself used) I trained a minimalistic MobileNetV3 with alpha of 1.0 using the imagenet weights, freezing the feature extractor layers, I get a around 53% accuracy while with MobileNetV2 with alpha 1.0 I get around 86% accuracy. Have you also faced similar issues?
From https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet/README.md, it seems that minimalistic small is achieving 61.9 TOP1 acc. Not sure which model you are using/training. 

> 2. When I try to run the network with lower alphas I get the following error:
>    "ValueError: If imagenet weights are being loaded, alpha can be one of `0.75`, `1.0` for non minimalistic or `1.0` for minimalistic only."
>    Why is this limitation present? Would be curious to understand that a bit more in depth.
This is expected since the pretrained weights from original implementation only has 0.75 and 1.0 provided. You need to set the "weight" param to None if you want to use other value of alpha.

> 3. The function "tf.keras.applications.MobileNetV3Samll" is misspelled.
It has been updated yesterday, should be available in the latest nightly release.

**Comment by sainisatish** [comment]
You can access using below - 
`from tensorflow.keras.applications import MobileNetV3Small`
