### ISSUE TITLE
train.batch with dynamic_pad=True and input as list of tensors not working as expected

### ISSUE THREAD

**Issue by alexbeloi** [tensorflow/tensorflow#4022]
### Environment info
Operating System: 
Ubuntu 14.04.4 LTS (running in Virtual Box 5.0.22 r108108)

Installed version of CUDA and cuDNN: 
None

If installed from binary pip package, provide:
1. Which pip package you installed.
pip 8.1.2
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.10.0rc0

### Preface
This issue arose from attempting to expand on an example using dynamic padding as written in: http://www.wildml.com/2016/08/rnns-in-tensorflow-a-practical-guide-and-undocumented-features/
the necessary code is copied below.

### Steps to reproduce
Run the following minimal example:
```python
import tensorflow as tf

# [0, 1, 2, 3, 4 ,...]
x = tf.range(1, 10, name="x")
 
# A queue that outputs 0,1,2,3,...
range_q = tf.train.range_input_producer(limit=5, shuffle=False)
slice_end = range_q.dequeue()
 
# Slice x to variable length, i.e. [0], [0, 1], [0, 1, 2], ....
y = tf.slice(x, [0], [slice_end], name="y")

batched_data = tf.train.batch(
    tensors=[y],
    batch_size=5,
    dynamic_pad=True,
    name="y_batch"
)
 
# Run the graph
# tf.contrib.learn takes care of starting the queues for us
res = tf.contrib.learn.run_n({"y": batched_data}, n=1, feed_dict=None)
 
# Print the result
print("Batch shape: {}".format(res[0]["y"].shape))
print(res[0]["y"])
```
Output (correct behavior):
```
Batch shape: (5, 4)
[[0 0 0 0]
 [1 0 0 0]
 [1 2 0 0]
 [1 2 3 0]
 [1 2 3 4]]
```

When attempted with different input (list of tensors of different lengths)
```python
import tensorflow as tf

y = [tf.constant(range(n)) for n in range(1,10)]

batched_data = tf.train.batch(
    tensors=[y],
    batch_size=5,
    dynamic_pad=True,
    name="y_batch"
)
 
# Run the graph
# tf.contrib.learn takes care of starting the queues for us
res = tf.contrib.learn.run_n({"y": batched_data}, n=1, feed_dict=None)
 
# Print the result
print("Batch shape: {}".format(res[0]["y"].shape))
print(res[0]["y"])
```
Output:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-8b4d52a4df68> in <module>()
     19     batch_size=5,
     20     dynamic_pad=True,
---> 21     name="y_batch"
     22 )
     23 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.pyc in batch(tensors, batch_size, num_threads, capacity, enqueue_many, shapes, dynamic_pad, allow_smaller_final_batch, shared_name, name)
    577   tensor_list = _as_tensor_list(tensors)
    578   with ops.op_scope(tensor_list, name, "batch") as name:
--> 579     tensor_list = _validate(tensor_list)
    580     (tensor_list, sparse_info) = _serialize_sparse_tensors(
    581         tensor_list, enqueue_many)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.pyc in _validate(tensor_list)
    411 
    412 def _validate(tensor_list):
--> 413   tensor_list = ops.convert_n_to_tensor_or_indexed_slices(tensor_list)
    414   if not tensor_list:
    415     raise ValueError("Expected at least one tensor in batch().")

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in convert_n_to_tensor_or_indexed_slices(values, dtype, name, as_ref)
    735       ret.append(
    736           convert_to_tensor_or_indexed_slices(value, dtype=dtype, name=n,
--> 737                                               as_ref=as_ref))
    738   return ret
    739 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in convert_to_tensor_or_indexed_slices(value, dtype, name, as_ref)
    696     return value
    697   else:
--> 698     return convert_to_tensor(value, dtype=dtype, name=name, as_ref=as_ref)
    699 
    700 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in convert_to_tensor(value, dtype, name, as_ref)
    619     for base_type, conversion_func in funcs_at_priority:
    620       if isinstance(value, base_type):
--> 621         ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    622         if ret is NotImplemented:
    623           continue

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.pyc in _autopacking_conversion_function(v, dtype, name, as_ref)
    628   if dtype is not None and dtype != inferred_dtype:
    629     return NotImplemented
--> 630   return _autopacking_helper(v, inferred_dtype, name or "packed")
    631 # pylint: enable=invalid-name
    632 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.pyc in _autopacking_helper(list_or_tuple, dtype, name)
    591           elems_as_tensors.append(
    592               constant_op.constant(elem, dtype=dtype, name=str(i)))
--> 593       return gen_array_ops._pack(elems_as_tensors, name=scope)
    594     else:
    595       return converted_elems

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.pyc in _pack(values, axis, name)
   1452     A `Tensor`. Has the same type as `values`. The packed tensor.
   1453   """
-> 1454   result = _op_def_lib.apply_op("Pack", values=values, axis=axis, name=name)
   1455   return result
   1456 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.pyc in apply_op(self, op_type_name, name, **keywords)
    701           op = g.create_op(op_type_name, inputs, output_types, name=scope,
    702                            input_types=input_types, attrs=attr_protos,
--> 703                            op_def=op_def)
    704           outputs = op.outputs
    705           return _Restructure(ops.convert_n_to_tensor(outputs),

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in create_op(self, op_type, inputs, dtypes, input_types, name, attrs, op_def, compute_shapes, compute_device)
   2310                     original_op=self._default_original_op, op_def=op_def)
   2311     if compute_shapes:
-> 2312       set_shapes_for_outputs(ret)
   2313     self._add_op(ret)
   2314     self._record_op_seen_by_control_dependencies(ret)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in set_shapes_for_outputs(op)
   1702       raise RuntimeError("No shape function registered for standard op: %s"
   1703                          % op.type)
-> 1704   shapes = shape_func(op)
   1705   if shapes is None:
   1706     raise RuntimeError(

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.pyc in _PackShape(op)
    767 
    768   for inp in op.inputs[1:]:
--> 769     input_shape = input_shape.merge_with(inp.get_shape())
    770 
    771   input_shape = input_shape.as_list()

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.pyc in merge_with(self, other)
    568       except ValueError:
    569         raise ValueError("Shapes %s and %s are not compatible" %
--> 570                          (self, other))
    571 
    572   def concatenate(self, other):

ValueError: Shapes (1,) and (2,) are not compatible
```

Expected same result as previous script.

### What have you tried?
* Attempted transforming `y` into a tensor but have not found a way. Given the first example, it appears possible to construct tensors with variable size in some dimension, but given a dataset in the form of List of List of primitive (with inner lists being of varying lengths), I don't know how to transform this into a tensor without padding the entire dataset.
```python
import tensorflow as tf

# [0, 1, 2, 3, 4 ,...]
x = tf.range(1, 10, name="x")
 
# A queue that outputs 0,1,2,3,...
range_q = tf.train.range_input_producer(limit=5, shuffle=False)
slice_end = range_q.dequeue()
 
# Slice x to variable length, i.e. [0], [0, 1], [0, 1, 2], ....
y = tf.slice(x, [0], [slice_end], name="y")

print 'Dynamic shape of y:', tf.shape(y)
print 'Static shape of y:', y.get_shape()
```
Output:
```
Dynamic shape of y: Tensor("Shape_16:0", shape=(1,), dtype=int32)
Static shape of y: (?,)
```

* Attempted replacing `tf.train.batch` line with the `tf.PaddingFIFOQueue` as follows
```python
# Creating a new queue
padding_q = tf.PaddingFIFOQueue(
    capacity=10,
    dtypes=tf.int32,
    shapes=[[None]])
 
# Enqueue the examples
enqueue_op = padding_q.enqueue([y])
 
# Add the queue runner to the graph
qr = tf.train.QueueRunner(padding_q, [enqueue_op])
tf.train.add_queue_runner(qr)
 
# Dequeue padded data
batched_data = padding_q.dequeue_many(5)
```
Output: identical to above

* Using placeholders: tried replacing `y` with a placeholder of shape `[None]` and feeding it the data, cannot seem to get this to work either.

* Padding entire dataset: this works, but defeats the purpose of dynamic padding

* Todo: am going to try passing dataset through `tf.train.SequenceExample()`, constructing an example for each sequence, but I would rather this not be necessary.

**Comment by prb12** [comment]
@mmy - This seems to go wrong in autopacking code - which is happening before the dynamic_pad logic of batch gets to fix up the ragged input data.  Is this a problem with tf.train.batch arg validation?

**Comment by mrry** [comment]
According to the documentation (and the implementation) the `tf.train.batch()` function expects either a list of tensors or a "dictionary of tensors" (i.e. a dictionary in which the values are tensors) as the `tensors` argument. If you pass a **list of lists** of tensors, it will try to interpret the inner list of tensors as a tensor, using the implicit packing code, and that fails here because the tensors aren't compatible as arguments to `tf.pack()`.

It would probably be more intuitive if the `tensors` argument to `tf.train.batch()` accept any arbitrary nesting of tensors that can be flattened using [`nest.flatten()`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/util/nest.py#L83), but it looks like `nest.flatten()` doesn't support dictionaries, so we'd need to add that support for backwards compatibility.

What a sad state of affairs. I'll mark this as "contributions welcome" for now. It looks like @ebrevdo and @kosklain have the most experience with the nesting code, so perhaps they can chime in if there's a reason not to take this route.

**Comment by alexbeloi** [comment]
Perhaps I am mistaken or am misunderstanding the documentation/implementation, but it I now believe that even the 'correct script' in my initial post is wrong (output not matching documentation). 

```python
import tensorflow as tf

# [0, 1, 2, 3, 4 ,...]
x = tf.range(1, 10, name="x")

# A queue that outputs 0,1,2,3,...
range_q = tf.train.range_input_producer(limit=5, shuffle=False)
slice_end = range_q.dequeue()

# Slice x to variable length, i.e. [0], [0, 1], [0, 1, 2], ....
y = tf.slice(x, [0], [slice_end], name="y")

batched_data = tf.train.batch(
    tensors=[y],
    batch_size=5,
    dynamic_pad=True,
    name="y_batch",
    enqueue_many=False
)

# Run the graph
# tf.contrib.learn takes care of starting the queues for us
res = tf.contrib.learn.run_n({"y": batched_data}, n=1, feed_dict=None)

# Print the result
print("Batch shape: {}".format(res[0]["y"].shape))
print(res[0]["y"])
```
Output:
```
Batch shape: (5, 4)
[[0 0 0 0]
 [1 0 0 0]
 [1 2 0 0]
 [1 2 3 0]
 [1 2 3 4]]
```
I believe this output should be expected if and only if the `enqueue_many` flag is set to `True`, as per the documentation, this means that the `tensors` in `tensors_list` are interpreted as having first dimension indexing the examples. Which is the case for `y` as it is defined.

However, with `enqueue_many=True` we get the following output:
```
Batch shape: (5,)
[1 1 2 1 2]
```

I believe passing a list of tensors of varying lengths to `tf.train.batch` should look like this (with `tensors=y` not `tensors=[y]`), however the output is not as expected.
```python
import tensorflow as tf

y = [tf.constant(range(n)) for n in range(1,10)]

batched_data = tf.train.batch(
    tensors=y,    #tensors=[y]
    batch_size=5,
    dynamic_pad=True,
    name="y_batch",
    enqueue_many=False
)

# Run the graph
# tf.contrib.learn takes care of starting the queues for us
res = tf.contrib.learn.run_n({"y": batched_data}, n=1, feed_dict=None)

# Print the result
# print("Batch shape: {}".format(res[0]["y"].shape))
print(res[0]["y"])
```
Output:
```
[array([[0],
       [0],
       [0],
       [0],
       [0]], dtype=int32), array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1]], dtype=int32), array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int32), array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int32), array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int32), array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]], dtype=int32), array([[0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6]], dtype=int32), array([[0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7]], dtype=int32), array([[0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8]], dtype=int32)]
```

It almost looks each example is being queued `batch_size` number of times, or perhaps being dequeued improperly.

**Comment by ebrevdo** [comment]
I'll answer regarding the behavior of your "correct script":

When you call `tf.train.batch` with `enqueue_many=False`, here is the sequence of what is being added to the `PaddingFIFOQueue` underneath:

```
n=0, insert []  # the empty vector
n=1, insert [1]
n=2, insert [1, 2]
n=3, insert [1, 2, 3]
n=4, insert [1, 2, 3, 4]
```
note in each case you are inserting a *single batch element* which is a vector.  just that the vectors have varying lengths.  this is because you used `enqueue_many=False`, so each input Tensor is considered one single batch element.

As a result, when you `dequeue_many` with `batch_size=5` you are asking for these 5 elements back.  The `PaddingFIFOQueue` pads these entries to the length of the longest one in the minibatch (4, from `n=4`) and you get `5` rows out:

```
[       ]
[1      ]
[1 2    ]
[1 2 3  ]
[1 2 3 4]
```
note that `PaddingFIFOQueue` pads integer valued outputs with `0`s.

In contrast, when you call `tf.train.batch` with `enqueue_many=True`, each enqueue of `y` is treated as some variable number of scalars to be added to the `PaddingFIFOQueue`.  That is, here is what gets added at each step:

```
n=0, insert nothing
n=1, insert 1
n=2, insert 1, then insert 2
n=3, insert 1, then insert 2, then insert 3
n=4, insert 1, then insert 2, then insert 3, then insert 4
```

You then ask for `5` elements from this scalar component.  The `PaddingFIFOQueue` sees you are asking for 5 scalars and as a result, no padding is necessary.  It returns to you:

```
[1]  # the single entry from the n=1 insert
[1]  # first entry from the n=2 inserts
[2]  # second entry from the n=2 inserts
[1]  # first entry from the n=3 inserts
[2]  # second entry from the n=3 inserts
```
(except you saw it as a vector, here i've written it as a column vector to show that each row is a scalar, and is considered a minibatch entry)

**Comment by alexbeloi** [comment]
Thanks for the explanation @ebrevdo, I see that the output is as you have explained. My confusion came from how `y` was constructed, after looking more carefully it's clear that it has shape `(?,)` and its first dimension indexes the scalars, so the behavior is as expected.

**Comment by botcs** [comment]
what to do then if I have a SequenceExample which is parsed, and evaluates to sequences like:
[1, 2, 3, 5, 6]
[1, 5, 1, 1]
[9, 9, 1, 5, 6, 7, 7, 8, 4]
etc.

**Comment by ebrevdo** [comment]
Csaba, this issue is closed.  Please ask your question on StackOverflow.

Short answer is: you can use the approach here (tf.train.batch with
dynamic_pad=True), or you can use
tf.contrib.training.bucket_by_sequence_length with dynamic_pad=True.
