### ISSUE TITLE
remove training nodes from freeze_graph failure using TransformGraph.

### ISSUE THREAD

**Issue by yasingh2007** [tensorflow/tensorflow#40222]
Getting TensorRT conversion failure due to ops not supported in TensorRT. Till now I have come to conclusion to optimize/prune the original tensorflow flow graph so that freeze graph should have only supported ops as per TensorRT and that should then convert easily to uff.

To do this, i want to remove training nodes (map/*) using TransformGraph. Option i used are below, other then Input shape change and “Identity” node no other node removed like : ‘switch’, ‘exit’, ‘add’.

1) what options to choose in TransformGraph() to remove ‘switch’, ‘exit’, ‘add’ nodes?
2) Used Optimize_for_inference() and remvoe_traing_nodes() without  success.

Saved_model:
https://drive.google.com/file/d/15VWWKp-F4LNcajbcG7a_awJayAjfM5r_/view?usp=sharing

Freeze_graph.pb:
https://drive.google.com/file/d/1OhWTui8Jdsh-ZBvBMYvMvyYrVh_t88cO/view?usp=sharing

TransformGraph notebook:
https://drive.google.com/file/d/1ePqNPHjcbf5IhrLAK1yRpHM9IOnhk7aG/view?usp=sharing

I want to remove thses nodes. (Graph Image)
https://drive.google.com/file/d/1SFKn-EHjP7hYrvUSNG8aaZ1p9ZYPbeG0/view?usp=sharing

Thanks

**Comment by Saduf2019** [comment]
@yasingh2007 
Please share the tensorflow version on which the error is faced.

**Comment by yasingh2007** [comment]
(base) ubuntu@usva-asd-ml-ear1:~$ pip list | grep tensor
tensorboard                        1.15.0
tensorflow                         1.15.2
tensorflow-datasets                3.1.0
tensorflow-estimator               1.15.1
tensorflow-gpu                     1.15.2
tensorflow-metadata                0.22.0
tensorrt                           7.0.0.11

**Comment by Saduf2019** [comment]
@yasingh2007 
Is there any particular reason for using an older version of tensorflow can you please use later version and let us know if you are facing any issues.

**Comment by yasingh2007** [comment]
Yes, We are developing whole project since last year when TF 1.15 was released and Porting to TF2.0 has not been successful due to API differences.  But training nodes should be removed in TF1.5 version also. Can you please check the notebook I am using to strip the training nodes from freezed graph?

All the map nodes below are training nodes, these are not coded in architecture layers but introduced when training. Do you believ that they should have been removed by "remove_traing_nodes", + "Optimize_for_refrence" + TransformGraph()? Can you check this notebook and tell us that if our method to strip training nodes is correct or need some other options?

TransformGraph notebook:
https://drive.google.com/file/d/1ePqNPHjcbf5IhrLAK1yRpHM9IOnhk7aG/view?usp=sharing

python3 -m tensorflow.python.tools.freeze_graph --input_saved_model_dir ../head-pose-estimation/assets/pose_model/ --output_node_names layer6/final_dense --output_graph frozen_graph.pb

butterfly/image_tensor
**butterfly/map/Shape
butterfly/map/strided_slice/stack
butterfly/map/strided_slice/stack_1
butterfly/map/strided_slice/stack_2
butterfly/map/strided_slice
butterfly/map/TensorArray
butterfly/map/TensorArrayUnstack/Shape
butterfly/map/TensorArrayUnstack/strided_slice/stack
butterfly/map/TensorArrayUnstack/strided_slice/stack_1
butterfly/map/TensorArrayUnstack/strided_slice/stack_2
butterfly/map/TensorArrayUnstack/strided_slice
butterfly/map/TensorArrayUnstack/range/start
butterfly/map/TensorArrayUnstack/range/delta
butterfly/map/TensorArrayUnstack/range
butterfly/map/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3
butterfly/map/Const
butterfly/map/TensorArray_1
butterfly/map/while/iteration_counter
butterfly/map/while/Enter
butterfly/map/while/Enter_1
butterfly/map/while/Enter_2
butterfly/map/while/Merge
butterfly/map/while/Merge_1
butterfly/map/while/Merge_2
butterfly/map/while/Less/Enter
butterfly/map/while/Less
butterfly/map/while/Less_1
butterfly/map/while/LogicalAnd
butterfly/map/while/LoopCond
butterfly/map/while/Switch
butterfly/map/while/Switch_1
butterfly/map/while/Switch_2
butterfly/map/while/Identity
butterfly/map/while/Identity_1
butterfly/map/while/Identity_2
butterfly/map/while/add/y
butterfly/map/while/add
butterfly/map/while/TensorArrayReadV3/Enter
butterfly/map/while/TensorArrayReadV3/Enter_1
butterfly/map/while/TensorArrayReadV3
butterfly/map/while/resize/ExpandDims/dim
butterfly/map/while/resize/ExpandDims
butterfly/map/while/resize/size
butterfly/map/while/resize/ResizeBilinear
butterfly/map/while/resize/Squeeze
butterfly/map/while/TensorArrayWrite/TensorArrayWriteV3/Enter
butterfly/map/while/TensorArrayWrite/TensorArrayWriteV3
butterfly/map/while/add_1/y
butterfly/map/while/add_1
butterfly/map/while/NextIteration
butterfly/map/while/NextIteration_1
butterfly/map/while/NextIteration_2
butterfly/map/while/Exit_2
butterfly/map/TensorArrayStack/TensorArraySizeV3
butterfly/map/TensorArrayStack/range/start
butterfly/map/TensorArrayStack/range/delta
butterfly/map/TensorArrayStack/range
butterfly/map/TensorArrayStack/TensorArrayGatherV3**
butterfly/layer1/conv2d/kernel
butterfly/layer1/conv2d/kernel/read
butterfly/layer1/conv2d/bias
butterfly/layer1/conv2d/bias/read
butterfly/layer1/conv2d/Conv2D
butterfly/layer1/conv2d/BiasAdd
butterfly/layer1/conv2d/Relu
butterfly/layer1/max_pooling2d/MaxPool
butterfly/layer2/conv2d/kernel
butterfly/layer2/conv2d/kernel/read
butterfly/layer2/conv2d/bias
butterfly/layer2/conv2d/bias/read
butterfly/layer2/conv2d/Conv2D
butterfly/layer2/conv2d/BiasAdd
butterfly/layer2/conv2d/Relu
butterfly/layer2/conv2d_1/kernel
butterfly/layer2/conv2d_1/kernel/read
butterfly/layer2/conv2d_1/bias
butterfly/layer2/conv2d_1/bias/read
butterfly/layer2/conv2d_1/Conv2D
butterfly/layer2/conv2d_1/BiasAdd
butterfly/layer2/conv2d_1/Relu
butterfly/layer2/max_pooling2d/MaxPool
butterfly/layer3/conv2d/kernel
butterfly/layer3/conv2d/kernel/read
butterfly/layer3/conv2d/bias
butterfly/layer3/conv2d/bias/read
butterfly/layer3/conv2d/Conv2D
butterfly/layer3/conv2d/BiasAdd
butterfly/layer3/conv2d/Relu
butterfly/layer3/conv2d_1/kernel
butterfly/layer3/conv2d_1/kernel/read
butterfly/layer3/conv2d_1/bias
butterfly/layer3/conv2d_1/bias/read
butterfly/layer3/conv2d_1/Conv2D
butterfly/layer3/conv2d_1/BiasAdd
butterfly/layer3/conv2d_1/Relu
butterfly/layer3/max_pooling2d/MaxPool
butterfly/layer4/conv2d/kernel
butterfly/layer4/conv2d/kernel/read
butterfly/layer4/conv2d/bias
butterfly/layer4/conv2d/bias/read
butterfly/layer4/conv2d/Conv2D
butterfly/layer4/conv2d/BiasAdd
butterfly/layer4/conv2d/Relu
butterfly/layer4/conv2d_1/kernel
butterfly/layer4/conv2d_1/kernel/read
butterfly/layer4/conv2d_1/bias
butterfly/layer4/conv2d_1/bias/read
butterfly/layer4/conv2d_1/Conv2D
butterfly/layer4/conv2d_1/BiasAdd
butterfly/layer4/conv2d_1/Relu
butterfly/layer4/max_pooling2d/MaxPool
butterfly/layer5/conv2d/kernel
butterfly/layer5/conv2d/kernel/read
butterfly/layer5/conv2d/bias
butterfly/layer5/conv2d/bias/read
butterfly/layer5/conv2d/Conv2D
butterfly/layer5/conv2d/BiasAdd
butterfly/layer5/conv2d/Relu
butterfly/layer6/flatten/Shape
butterfly/layer6/flatten/strided_slice/stack
butterfly/layer6/flatten/strided_slice/stack_1
butterfly/layer6/flatten/strided_slice/stack_2
butterfly/layer6/flatten/strided_slice
butterfly/layer6/flatten/Reshape/shape/1
butterfly/layer6/flatten/Reshape/shape
butterfly/layer6/flatten/Reshape
butterfly/layer6/dense/kernel
butterfly/layer6/dense/kernel/read
butterfly/layer6/dense/bias
butterfly/layer6/dense/bias/read
butterfly/layer6/dense/MatMul
butterfly/layer6/dense/BiasAdd
butterfly/layer6/dense/Relu
butterfly/layer6/logits/kernel
butterfly/layer6/logits/kernel/read
butterfly/layer6/logits/bias
butterfly/layer6/logits/bias/read
butterfly/layer6/logits/MatMul
butterfly/layer6/logits/BiasAdd
butterfly/layer6/final_dense

**Comment by yasingh2007** [comment]
I have trained model with TF2.2.0, it shows different training nodes. How to remove these "/map/* " training nodes?

python -m tensorflow.python.tools.freeze_graph --input_saved_model_dir saved_model/1591713086/ --output_node_names layer6/final_dense     --output_graph frozen_graph_t2.pb

butterfly/image_tensor 
**butterfly/map/Shape
butterfly/map/strided_slice/stack
butterfly/map/strided_slice/stack_1
butterfly/map/strided_slice/stack_2
butterfly/map/strided_slice
butterfly/map/TensorArrayUnstack/TensorListFromTensor/element_shape
butterfly/map/TensorArrayUnstack/TensorListFromTensor
butterfly/map/Const
butterfly/map/TensorArrayV2_1/element_shape
butterfly/map/TensorArrayV2_1
butterfly/map/while/loop_counter
butterfly/map/while
butterfly/map/while/Identity_3
butterfly/map/StopGradient_1
butterfly/map/TensorArrayV2Stack/TensorListStack/element_shape
butterfly/map/TensorArrayV2Stack/TensorListStack**
butterfly/layer1/conv2d/kernel
butterfly/layer1/conv2d/bias
butterfly/layer1/conv2d/Conv2D/ReadVariableOp
butterfly/layer1/conv2d/Conv2D
butterfly/layer1/conv2d/BiasAdd/ReadVariableOp
butterfly/layer1/conv2d/BiasAdd
butterfly/layer1/conv2d/Relu
butterfly/layer1/max_pooling2d/MaxPool
butterfly/layer2/conv2d/kernel
butterfly/layer2/conv2d/bias
butterfly/layer2/conv2d/Conv2D/ReadVariableOp
butterfly/layer2/conv2d/Conv2D
butterfly/layer2/conv2d/BiasAdd/ReadVariableOp
butterfly/layer2/conv2d/BiasAdd
butterfly/layer2/conv2d/Relu
butterfly/layer2/conv2d_1/kernel
butterfly/layer2/conv2d_1/bias
butterfly/layer2/conv2d_1/Conv2D/ReadVariableOp
butterfly/layer2/conv2d_1/Conv2D
butterfly/layer2/conv2d_1/BiasAdd/ReadVariableOp
butterfly/layer2/conv2d_1/BiasAdd
butterfly/layer2/conv2d_1/Relu
butterfly/layer2/max_pooling2d/MaxPool
butterfly/layer3/conv2d/kernel
butterfly/layer3/conv2d/bias
butterfly/layer3/conv2d/Conv2D/ReadVariableOp
butterfly/layer3/conv2d/Conv2D
butterfly/layer3/conv2d/BiasAdd/ReadVariableOp
butterfly/layer3/conv2d/BiasAdd
butterfly/layer3/conv2d/Relu
butterfly/layer3/conv2d_1/kernel
butterfly/layer3/conv2d_1/bias
butterfly/layer3/conv2d_1/Conv2D/ReadVariableOp
butterfly/layer3/conv2d_1/Conv2D
butterfly/layer3/conv2d_1/BiasAdd/ReadVariableOp
butterfly/layer3/conv2d_1/BiasAdd
butterfly/layer3/conv2d_1/Relu
butterfly/layer3/max_pooling2d/MaxPool
butterfly/layer4/conv2d/kernel
butterfly/layer4/conv2d/bias
butterfly/layer4/conv2d/Conv2D/ReadVariableOp
butterfly/layer4/conv2d/Conv2D
butterfly/layer4/conv2d/BiasAdd/ReadVariableOp
butterfly/layer4/conv2d/BiasAdd
butterfly/layer4/conv2d/Relu
butterfly/layer4/conv2d_1/kernel
butterfly/layer4/conv2d_1/bias
butterfly/layer4/conv2d_1/Conv2D/ReadVariableOp
butterfly/layer4/conv2d_1/Conv2D
butterfly/layer4/conv2d_1/BiasAdd/ReadVariableOp
butterfly/layer4/conv2d_1/BiasAdd
butterfly/layer4/conv2d_1/Relu
butterfly/layer4/max_pooling2d/MaxPool
butterfly/layer5/conv2d/kernel
butterfly/layer5/conv2d/bias
butterfly/layer5/conv2d/Conv2D/ReadVariableOp
butterfly/layer5/conv2d/Conv2D
butterfly/layer5/conv2d/BiasAdd/ReadVariableOp
butterfly/layer5/conv2d/BiasAdd
butterfly/layer5/conv2d/Relu
butterfly/layer6/flatten/Const
butterfly/layer6/flatten/Reshape
butterfly/layer6/dense/kernel
butterfly/layer6/dense/bias
butterfly/layer6/dense/MatMul/ReadVariableOp
butterfly/layer6/dense/MatMul
butterfly/layer6/dense/BiasAdd/ReadVariableOp
butterfly/layer6/dense/BiasAdd
butterfly/layer6/dense/Relu
butterfly/layer6/logits/kernel
butterfly/layer6/logits/bias
butterfly/layer6/logits/MatMul/ReadVariableOp
butterfly/layer6/logits/MatMul
butterfly/layer6/logits/BiasAdd/ReadVariableOp
butterfly/layer6/logits/BiasAdd
butterfly/layer6/final_dense

frozen_graph_t2.pb:
drive.google.com/file/d/1DPyry67p6VGOTR6qTfCDT5Kr_QsuLRa_/view?usp=sharing
saved_model:
drive.google.com/file/d/17LbKTz6yHcZU-PIGcoqchxFZne97FHeo/view?usp=sharing

I am using code in this notebook to optimize but it was valid for only TF1.15. 
For TF2.2 it says no graph_transfroms.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-f1515cd131de> in <module>
     11 from tensorflow.python.tools import freeze_graph
     12 from tensorflow.python import ops
---> 13 from tensorflow.tools.graph_transforms import TransformGraph
     15 def describe_graph(graph_def, show_nodes=False):
ModuleNotFoundError: No module named 'tensorflow.tools.graph_transforms'
 
TransformGraph notebook:
https://drive.google.com/file/d/1ePqNPHjcbf5IhrLAK1yRpHM9IOnhk7aG/view?usp=sharing

**Comment by sushreebarsa** [comment]
@yasingh2007 Could you please refer to this [blog](https://blog.metaflow.fr/tensorflow-how-to-freeze-a-model-and-serve-it-with-a-python-api-d4f3596b3adc) and also consider using Keras SavedModel format for deployment. Kindly upgrade the TF version to the latest as older versions are not actively supported.
Thank you!
