### ISSUE TITLE
Eigen download can fail due to Gitlab captcha

### ISSUE THREAD

**Issue by dtrodrigues** [tensorflow/tensorflow#40226]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS Linux release 7.8.2003
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/
- TensorFlow installed from (source or binary): source
- TensorFlow version: n/a
- Python version: n/a
- Installed using virtualenv? pip? conda?: n/a
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): GCC 4.8.5
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the problem**
Downloading eigen from the gitlab mirror sometimes fails due to captcha and doesn't have a helpful error message
**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
[root@9a53b50ad80e tensorflow]# ./tensorflow/lite/tools/make/download_dependencies.sh
downloading https://gitlab.com/libeigen/eigen/-/archive/c2ab36f47a34e572f37e3dd556ac8a04ab769277/eigen-c2ab36f47a34e572f37e3dd556ac8a04ab769277.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5511    0  5511    0     0  41050      0 --:--:-- --:--:-- --:--:-- 40822
checking sha256 of tensorflow/lite/tools/make/downloads/eigen
/tmp/tmp.y8lTsk6u19/eigen-c2ab36f47a34e572f37e3dd556ac8a04ab769277.tar.gz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
[root@9a53b50ad80e tensorflow]# head /tmp/tmp.uZlok4zSME/eigen-c2ab36f47a34e572f37e3dd556ac8a04ab769277.tar.gz
<!DOCTYPE html>
<html>
<head>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
  <title>Captcha Challenge</title>
  <style>body{color:#666;text-align:center;font-family:Helvetica Neue,Helvetica,Arial,sans-serif;margin:auto;font-size:14px;display:flex;flex-direction:column;align-items:center;justify-content:center}hr{max-width:800px;margin:18px auto;border:0;border-top:1px solid #eee;border-bottom:1px solid #fff}img{max-width:40vw}.container{margin:auto 20px}.cferror_details{list-style-type:none}.cf-error-details h1{color:#456;font-size:20px;font-weight:400;line-height:28px}</style>
</head>

<body>
  <div class="header">
```
**Any other info / logs**
In https://github.com/tensorflow/tensorflow/pull/29017 , the tensorflow mirror was filtered out, but I'm not sure if this mirror is more stable now. Options to resolve include using or falling back to the tensorflow mirror or checking for the `403` status from Gitlab to present a more descriptive error message. I didn't get this error on my own computer but did when running inside centos7 docker on https://labs.play-with-docker.com/

**Comment by Saduf2019** [comment]
@dtrodrigues 
Please update the system information, for us to analyse the issue faced.

**Comment by dtrodrigues** [comment]
I've updated the system information but this looks to be a platform-agnostic issue. It's not currently happening but as shown in the log above, there are cases where Gitlab requests a captcha when downloading and the `download_dependencies.sh` script fails and only shows that the there was a download mismatch instead of something more indicative of the issue or attempting to use the other mirror.
