### ISSUE TITLE
Unhandled Rejection (Error): No backend found in registry in a React App

### ISSUE THREAD

**Issue by programandoconro** [tensorflow/tensorflow#40238]
Hi, 

 System Specifications:
- Fedora 32
- React JS 
- npm
- Tensorflow-mobilenet

Behavior:

This basic React App using mobilenet from @tensorflow-models was working fine a few months ago. Now I am getting Unhandled Rejection error.

```
import * as mobilenet from '@tensorflow-models/mobilenet';
import photo from './assets/file.jpg';
import { loadImage } from 'canvas';
import React, { useState } from 'react';

const App = () => {
	const [res, handleRes] = useState([]);
	const myPhoto = () => {
		return <img src={photo} alt="foto "></img>;
	};
	const myPrediction = async () => {
		const loadModel = await mobilenet.load();
		const pic = await loadImage(photo);
		const pred = await loadModel.classify(pic);
		console.log(pred);
		handleRes(pred);
	};

	return (
		<div className="App">
			{myPhoto()}
			<button onClick={(e) => myPrediction(e)}>Predict</button>
			{res.map((e, k) => (
				<li key={k}>
					<h1>{e.className + ': ' + Math.round(e.probability * 100) + '%'}</h1>
				</li>
			))}
		</div>
	);
};

export default App;
```
This basic example should make a prediction on the uploaded image.

I made a post here https://programandoconro.wordpress.com/2019/12/30/react-app-para-clasificacion-de-imagenes-con-machine-learning/

Full App code is here https://github.com/programandoconro/Image-Classification-ML-App (not working either).
![file](https://user-images.githubusercontent.com/50117686/83968945-8f552600-a8c4-11ea-8928-131356e1637b.jpg)

Fortunately,  deployed App still working  https://programandoconro.github.io/Image-Classification-ML-App/

Sample image attached.

Thank you,

**Comment by gowthamkpr** [comment]
@programandoconro Please post this issue in [tensorflow/tfjs](https://github.com/tensorflow/tfjs/issues) as this issue is apt to that repo. Thanks!

**Comment by programandoconro** [comment]
@gowthamkpr Thank you, I will.
