### ISSUE TITLE
Machine translation using Seq2Seq with attention by using LSTM instead of GRU

### ISSUE THREAD

**Issue by yanglei-github** [tensorflow/tensorflow#40237]
Hello,
I am using the template in tutorial 'Machine translation using Seq2Seq with attention'. However, seq2seq is built on GRU.(The link is https://www.tensorflow.org/tutorials/text/nmt_with_attention) 

Could you please provide a template that Machine translation using Seq2Seq with attention using LSTM instead of GRU?

**Comment by gowthamkpr** [comment]
@yanglei-github Please take a look at this [doc](https://www.tensorflow.org/addons/tutorials/networks_seq2seq_nmt) where LSTM has been user for Neural Machine Translation. Thanks!

**Comment by yanglei-github** [comment]
Thanks a lot!  Also, do you have some tutorials for implementing copy mechanism(pointer-generator or copynet) codes in TensorFlow version 2? Because I think by far TensorFlow doesn't have a build-in API for using copy mechanism in TensorFlow.

**Comment by yanglei-github** [comment]
And it is really a great tutorial for machine translation. If it is possible that add some evaluation metrics such as bleu or meteor to evaluate the result

**Comment by gowthamkpr** [comment]
@yanglei-github If its a document feature request can you create a new issue to track this. Thank you!

**Comment by yanglei-github** [comment]
OK! Sure!
