### ISSUE TITLE
Request to include tf.depth_to_space

### ISSUE THREAD

**Issue by purva98** [tensorflow/tensorflow#40232]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary):  
- TensorFlow version (or github SHA if from source): 1.14

**Provide the text output from tflite_convert**

```
ValueError: Didn't find custom op for name 'DEPTH_TO_SPACE' with version 1
Registration failed.
```

**Standalone code to reproduce the issue** 
import tensorflow as tf
graph_def_file = "frozen_model.pb"
input_arrays = ["Placeholder"]
output_arrays = ["DepthToSpace"]

converter = tf.lite.TFLiteConverter.from_frozen_graph(
  graph_def_file, 
  input_arrays, 
  output_arrays, 
  input_shapes={'Placeholder':[200,200,200,4]}
  )
converter.allow_custom_ops = True
tflite_model = converter.convert()
open("fix_shape.tflite", "wb").write(tflite_model)

Link to the model : https://drive.google.com/file/d/1i9q1XtMVMe31KRGRhy1vbtiEL1hy0x_Z/view?usp=sharing

**Any other info / logs**
I tried testing with tensorflow versions >=2.0 and also tf.nightly 
It did not work out

**Comment by Saduf2019** [comment]
@purva98 
Is there any particular reason to be using an older version of tensorflow ,can you please try on later versions, also we are unable to preview the drive shared. if possible please share a colab gist for us to analyse the error.
Please refer to these links and let us know if it helps:
[link](https://github.com/google-coral/tflite/issues/2) [link1](https://github.com/nnstreamer/nnstreamer/issues/916) [link2](https://medium.com/@bsramasubramanian/running-a-tensorflow-lite-model-in-python-with-custom-ops-9b2b46efd355)

**Comment by p98-ai** [comment]
I tlhave tried with the latest tf version also. Yes, I ll refer to the links and update you. Thanks

**Comment by purva98** [comment]
I used tf 1.14 because , when I try with tf 2.2.0

converter = tf.lite.TFLiteConverter.from_saved_model('saved_model')
tflite_model = converter.convert()

I get this error : 
"This converter can only convert a single ConcreteFunction. Converting multiple functions is under development."

Thanks for the links, I will try them and update you.

**Comment by Saduf2019** [comment]
@purva98 
Please refer to these links for the mentioned error:
#34350  #35031

**Comment by purva98** [comment]
Yes, I ll follow these tutorials to build the custom operator,
Thanks
