### ISSUE TITLE
error with tf.strings.to_number()

### ISSUE THREAD

**Issue by Ahmed-fub** [tensorflow/tensorflow#40234]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by Ahmed-fub** [comment]
when I use tf.strings.to_number(keys) it gives me error 
InvalidArgumentError: StringToNumberOp could not correctly convert string: 00000000000000000000000100000000000000100010000000000000010000000100000000010100100101010000000111101101011101110100011011110111110011111110101111111011111111110111110 [Op:StringToNumber]

**Comment by ravikyram** [comment]
@Ahmed-fub 

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Also include your TensorFlow version.

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by mihaimaruseac** [comment]
Please fill in issue template and provide minimal code to reproduce.
