### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by ryankuang0618** [tensorflow/tensorflow#40236]
I want to train from tensorflow, but I always get error on this bug.
from tensorflow.contrib import data as tf_data
ModuleNotFoundError: No module named 'tensorflow.contrib'
I have try install lower version of tensorflow, but still didn't work.
environment:macos python3.7 tensorflow2.2.0

**Comment by Saduf2019** [comment]
@ryankuang0618 

tensorflow.contrib does not exist in TF 2.x. You'll have to use TF 1.x to use tensorflow.contrib
For Python version compatibility. Please check the tested build configurations [here](https://www.tensorflow.org/install/source#linux).

Thanks!

**Comment by ryankuang0618** [comment]
> @ryankuang0618 
> 
> 
> 
> tensorflow.contrib does not exist in TF 2.x. You'll have to use TF 1.x to use tensorflow.contrib
> 
> For Python version compatibility. Please check the tested build configurations [here](https://www.tensorflow.org/install/source#linux).
> 
> 
> 
> you may also refer to similar issues:
> 
> #39065 #30794  #38882 #38739 #31350 #36269
> 
> Thanks!

Thanks, I solved the error by install tensorflow version to 1.14.0
