### ISSUE TITLE
the result of each execution is very different.

### ISSUE THREAD

**Issue by Lay4U** [tensorflow/tensorflow#40230]
https://colab.research.google.com/drive/1_YW_Afi0yZS5wJQxJbHXddezIppZFUL_

As you can see in colab, the result of each execution is very different.

I understand that the results of the run change because the weights change, but the difference is too great.

Reduced to reduce loss. Why does this happen and how can I reduce the difference in execution results to increase the accuracy and reliability of predictions?

**Comment by amahendrakar** [comment]
@Lay4U,
I do not have permission to view the Colab gist you have linked. 

Could you please save the Gist using the following method. 'File' -> 'Save a copy as Github Gist', and share the link of the new window. Thanks!
