### ISSUE TITLE
(Embedding python into c) ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by bsrc** [tensorflow/tensorflow#40246]
I am working on a project which is related to object detection and ocr.  I am using Ubuntu 18.04 and python 2.7, yolov3 for object detection and tesseract 5.0.0-alpha-692-g62ea for ocr. I have to embed python code that is for ocr into the c code which is for object detection. I wrote this C code and compile at the terminal by "  sudo gcc code.c -lpython2.7  "

#include </usr/include/python2.7/Python.h>

int main() {
Py_Initialize();
PyRun_SimpleString("import sys; sys.path.append('.')");
PyRun_SimpleString("import ocr3;");
PyRun_SimpleString("print ocr3.myabs(2.0)");
Py_Finalize();

return 0;
}

but it gives an error while running a.out:

ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "./ocr3.py", line 1, in <module>
    import cv2
  File "/home/asus/.local/lib/python2.7/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'ocr3' is not defined

so, I tried another C code:

#include <stdio.h>
#include <ncurses.h>
#include </usr/local/include/python2.7/Python.h>

int main()
{
	char filename[] = "ocr3.py";
	FILE* fp;

	Py_Initialize();

	fp = _Py_fopen(filename, "r");
	PyRun_SimpleFile(fp, filename);

	Py_Finalize();
	return 0;
}
but again I have an issue while running a.out: " code.c:(.text+0x3e): undefined reference to `_Py_fopen'  "

Unfortunately, I could not find any solution. Can anyone help about the fix one of the these problems?

**Comment by amahendrakar** [comment]
@bsrc,
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/ask) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by bsrc** [comment]
@amahendrakar you are right actually, but I have asked on StackOverflow, too. Thank you for your recommendation.
