### ISSUE TITLE
Tensorflow 2.x and tf.compat issues

### ISSUE THREAD

**Issue by Zumbalamambo** [tensorflow/tensorflow#40242]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NO
- TensorFlow installed from (source or binary):Binary
- TensorFlow version (use command below): 2.2
- Python version:3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1
- GPU model and memory: gtx 1060

The Tensorflow's latest version is a complete tragedy. It just breaks each and every functions that has been written with the older version of tensorflow. The eager execution is the pain in the neck. It just throws the countless meaningless error. I got `tf.function-decorated Value error`. I fixed it and now I'm getting the following error,

```
tensorflow.python.eager.core._SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'Conv2DBackpropInput_1:0' shape=(1, 13, 13, 1280) dtype=float32>]
2020-06-07 16:49:58.682705: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]

```

```
Disabling eager execution throws the following error,

ValueError: Operation name: "AssignAddVariableOp"
op: "AssignAddVariableOp"
input: "AssignAddVariableOp/Variable"
input: "Const"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
 is not an element of this graph.
```

**Please regularize the code base before even trying to issue a vendor certificate aka TensorFlow certified developer certificate**

**Comment by amahendrakar** [comment]
@Zumbalamambo,
Could you please share the code you're trying to run, so that we can look into it and fix the issue. Thanks!

**Comment by Zumbalamambo** [comment]
+1

**Comment by amahendrakar** [comment]
> It just breaks each and every functions that has been written with the older version of tensorflow. The eager execution is the pain in the neck. It just throws the countless meaningless error.

@Zumbalamambo,
Could you please share the code you are running to that we can help you with the errors. Thanks!

**Comment by lvenugopalan** [comment]
@Zumbalamambo,
The issue tracker is for Tensorflow feature requests or bug reports. Please refrain from posting inappropriate comments. If any functionality or feature does not work to your satisfaction, please let us know, as each feedback is valuable to us. Tensorflow team will be happy to address them. Kindly share the information related to code as requested by @amahendrakar. Let us know how we can help.
