### ISSUE TITLE
Functional Keras API not getting converted using TFLiteTransferConverter in Model Personalization

### ISSUE THREAD

**Issue by sarthak-chakraborty** [tensorflow/tensorflow#40247]
**Working on Colab**
- TensorFlow version: 2.2.0

## Error
While reading about PR **RFC: On-Device Training with TensorFlow**([https://github.com/tensorflow/community/pull/124](https://github.com/tensorflow/community/pull/124)), and trying to include 'train' option in convert(I know tflite currently does not support on-device training, but was curious to check how operations would look like), I am facing the following error:

```
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py in _import_graph_def_internal(graph_def, input_map, return_elements, validate_colocation_constraints, name, producer_op_list)
    496         results = c_api.TF_GraphImportGraphDefWithResults(
--> 497             graph._c_graph, serialized, options)  # pylint: disable=protected-access
    498         results = c_api_util.ScopedTFImportGraphDefResults(results)

InvalidArgumentError: Input 0 of node SGD/SGD/update_11/ResourceApplyGradientDescent was passed float from sequential/dense_1/BiasAdd/ReadVariableOp/resource:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
12 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py in _import_graph_def_internal(graph_def, input_map, return_elements, validate_colocation_constraints, name, producer_op_list)
    499       except errors.InvalidArgumentError as e:
    500         # Convert to ValueError for backwards compatibility.
--> 501         raise ValueError(str(e))
    502 
    503     # Create _DefinedFunctions for any imported functions.

ValueError: Input 0 of node SGD/SGD/update_11/ResourceApplyGradientDescent was passed float from sequential/dense_1/BiasAdd/ReadVariableOp/resource:0 incompatible with expected resource.
```

### Command used to run the converter or code if you’re using the Python API
**Model Description**
```
model = tf.keras.Sequential([tf.keras.layers.Conv2D(32, kernel_size=3, padding='same', activation='relu', input_shape=(32,32,3)),
                             tf.keras.layers.Conv2D(32, kernel_size=3, activation='relu', padding='same'),
                             tf.keras.layers.MaxPool2D(pool_size=(2,2), strides=(2,2)),
                             tf.keras.layers.Conv2D(64, kernel_size=3, activation='relu', padding='same'),
                             tf.keras.layers.Conv2D(64, kernel_size=3, activation='relu', padding='same'),
                             tf.keras.layers.MaxPool2D(pool_size=(2,2), strides=(2,2)),
                             tf.keras.layers.Flatten(),
                             tf.keras.layers.Dense(128, activation='relu'),
                             tf.keras.layers.Dense(10)])

model.compile(optimizer='sgd', loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True), metrics=['accuracy'])
```

 **Convert Code**
```
_LOSS_FN = tf.keras.losses.CategoricalCrossentropy()
_OPTIM = tf.optimizers.SGD()

@tf.function(input_signature=[
    tf.TensorSpec(model.inputs[0].shape, model.inputs[0].dtype),
    tf.TensorSpec(model.outputs[0].shape, model.outputs[0].dtype),
])
def train(x, y):
  with tf.GradientTape() as tape:
    prediction = model(x)
    loss = _LOSS_FN(prediction, y)
  gradients = tape.gradient(loss, model.trainable_variables)
  _OPTIM.apply_gradients(zip(gradients, model.trainable_variables))

concrete_func = train.get_concrete_function()

# convert to tflite
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
converted_tflite_model = converter.convert()
```

Can anyone please help me out with the error?

**Comment by abattery** [comment]
Currently, TFLite do not support on-device training officially. And also does not support natively mutable variable use cases.

**Comment by sarthak-chakraborty** [comment]
I think that error is because of the `AssignVariableOp` that is not supported by `convert()` function. Looking at the Traceback error, it shows that `convert()` function by default freezes the parameters. 

Though I am yet to explore in detail, [https://github.com/tensorflow/examples/blob/master/lite/examples/model_personalization/README.md](https://github.com/tensorflow/examples/blob/master/lite/examples/model_personalization/README.md), shows that there is a way to do transfer learning on-device, that is, train some of the layers on android device, using a `base` model and a `head` model. Does this train only the dense layers? Or can it be used to train Conv layers too?

**Comment by abattery** [comment]
@sarthak-chakraborty you're right. We have limited supported mutable variable support via flex delegate and AssignVariableOp is an typical example of that.

@jaeyoo could you answer the model personalization questions?

**Comment by sarthak-chakraborty** [comment]
As for the Model Personalization questions, I have the following questions:

1. It contains the `head` and `base` model. I have checked that including a full CNN model in head layer works and it gets trained as well in an android phone. However, head models created with only `Sequential` API is getting converted. Does it mean there is no support for head models with `Functional` API? Using functional API gives the error: ```RuntimeError: Unexpected Keras eval signature inputs```

2. I understand that some layers like `DepthwiseConv2d` will not be converted since there is no support of `DepthwiseConv2dNativeBackpropFilter` and `DepthwiseConv2dNativeBackpropInput` in whitelisted flex ops. However, is it possible to freeze certain layers in the head model (example, freeze the depthwiseConv2d layer so that no backprop takes place)? I have tried the following:
        a) Made some layers as non-trainable in head model
        b) In the `train` function of the file `tfltransfer/heads/keras_model_head.py`, I used only the variables that are corresponding to the trainable layers for calculating `tf.gradients()` (i.e. variables in 
   ```
   with tf.name_scope(scope + '/backprop'):
       gradients = tf.gradients(loss, variables, stop_gradients=variables)
   ``` 
    contains only the variables corresponding to trainable layers) gives the error:
    ```Placeholder head/depth_conv1024_12/depthwise_kernel should be specified by input_arrays.```


Any help regarding this matter will be highly appreciated.

**Comment by abattery** [comment]
@jaeyoo friendly ping.

**Comment by Egorovlvan** [comment]
> 1. It contains the `head` and `base` model. I have checked that including a full CNN model in head layer works and it gets trained as well in an android phone. However, head models created with only `Sequential` API is getting converted. Does it mean there is no support for head models with `Functional` API? Particularly, the problem lies if we define an Input layer, i.e., `tf.keras.Input(shape=())` causes the error in both functional as well as Sequential API. However, Sequential API can be bypassed without mentioning the Input Layer which cannot be done in Functional API. Using Input Layer gives the error: `RuntimeError: Unexpected Keras eval signature inputs`

You can provide name in InputLayer in  Sequential API like this:
layers.InputLayer(input_shape=(whatever), name='target_input') and perhaps its not gonna be an error.

**Comment by jaeyoo** [comment]
> As for the Model Personalization questions, I have the following questions:
> 
> 1. It contains the `head` and `base` model. I have checked that including a full CNN model in head layer works and it gets trained as well in an android phone. However, head models created with only `Sequential` API is getting converted. Does it mean there is no support for head models with `Functional` API? Particularly, the problem lies if we define an Input layer, i.e., `tf.keras.Input(shape=())` causes the error in both functional as well as Sequential API. However, Sequential API can be bypassed without mentioning the Input Layer which cannot be done in Functional API. Using Input Layer gives the error: `RuntimeError: Unexpected Keras eval signature inputs`

Yes, currently, model personalization doesn't support Functional API. Could you try to specify your input specification as listed in `keras_head_model.py` and `tflite_transfer_converter.py`?
```python
      loss, gradients, variables = self.head_model.train(bottleneck, labels)
      converter = tfv1.lite.TFLiteConverter.from_session(
          sess, [bottleneck, labels] + variables, [loss] + gradients)
```

> 2. I understand that some layers like `DepthwiseConv2d` will not be converted since there is no support of `DepthwiseConv2dNativeBackpropFilter` and `DepthwiseConv2dNativeBackpropInput` in whitelisted flex ops. However, is it possible to freeze certain layers in the head model (example, freeze the depthwiseConv2d layer so that no backprop takes place)? I have tried the following:
>    a) Made some layers as non-trainable in head model
>    b) In the `train` function of the file `tfltransfer/heads/keras_model_head.py`, I used only the variables that are corresponding to the trainable layers for calculating `tf.gradients()` (i.e. variables in
>    ```
>    with tf.name_scope(scope + '/backprop'):
>        gradients = tf.gradients(loss, variables, stop_gradients=variables)
>    ```
>    
>    
>    contains only the variables corresponding to trainable layers) gives the error:
>    `Placeholder head/depth_conv1024_12/depthwise_kernel should be specified by input_arrays.`
> 
> Any help regarding this matter will be highly appreciated.

Could you remove the variables from the following two lists in `__init__()` of `keras_head_model.py`? 
```python
variables = tfv1.global_variables()
      self._variable_names = [variable.name for variable in variables]
      self._initial_params = [variable.eval() for variable in variables]
```

**Comment by sarthak-chakraborty** [comment]
> Yes, currently, model personalization doesn't support Functional API.

Support of Functional API in personalization layer is being easily achieved by changing line 124 in `keras_model_head.py` from `if key.endswith('_input')` to `if 'input' in key`. Or, it can be done by following @Egorovlvan 's suggestion.

>  2. I understand that some layers like `DepthwiseConv2d` will not be converted since there is no support of `DepthwiseConv2dNativeBackpropFilter` and `DepthwiseConv2dNativeBackpropInput` in whitelisted flex ops. However, is it possible to freeze certain layers in the head model (example, freeze the depthwiseConv2d layer so that no backprop takes place)? I have tried the following:
>     a) Made some layers as non-trainable in head model
>    b) In the `train` function of the file `tfltransfer/heads/keras_model_head.py`, I used only the variables that are corresponding to the trainable layers for calculating `tf.gradients()` (i.e. variables in
>    ```
>    with tf.name_scope(scope + '/backprop'):
>        gradients = tf.gradients(loss, variables, stop_gradients=variables)
>    ```
>    
>    
>    contains only the variables corresponding to trainable layers) gives the error:
>    `Placeholder head/depth_conv1024_12/depthwise_kernel should be specified by input_arrays.`
> 

In regards to this, I have also made changes in `keras_model_head.py` and by introducing `train_variables`.

Both changes are reflected in PR [https://github.com/tensorflow/examples/pull/228](https://github.com/tensorflow/examples/pull/228)

**Comment by jaeyoo** [comment]
PR tensorflow/examples#228 is merged.
