### ISSUE TITLE
 Error while reading resource variable _AnonymousVar117 from Container while training with colab

### ISSUE THREAD

**Issue by Zumbalamambo** [tensorflow/tensorflow#40248]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): colab
- TensorFlow version (use command below): 2.3
- Python version:3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: colab
- GPU model and memory: gtx 1060

I'm getting the following error,
```

FailedPreconditionError                   Traceback (most recent call last)
<ipython-input-6-daf439831857> in <module>()
     89 
     90 if __name__ == '__main__':
---> 91     _main_()

11 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

FailedPreconditionError:  Error while reading resource variable _AnonymousVar117 from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/_AnonymousVar117/N10tensorflow3VarE does not exist.
	 [[node loss/lambda_2_loss/custom_loss/Less_2/ReadVariableOp (defined at /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3009) ]] [Op:__inference_keras_scratch_graph_19741]

Function call stack:
keras_scratch_graph
```

The error log is pointless that it doesn't even tell me where the error could be in my code.

**Comment by Saduf2019** [comment]
@Zumbalamambo 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by Zumbalamambo** [comment]
+1

**Comment by Saduf2019** [comment]
@Zumbalamambo 
Please update as per above comment

**Comment by Zumbalamambo** [comment]
closing because tensorflow 2 is the storehouse of bugs and unusable
