### ISSUE TITLE
Collect runtime information when using tf.function

### ISSUE THREAD

**Issue by zhuzilin** [tensorflow/tensorflow#40255]
**System information**
- TensorFlow version (you are using): TF2.2
- Are you willing to contribute it (Yes/No):
Yes

**Describe the feature and the current behavior/state.**
In tf1.x, it is possible to use `RunOptions` and `RunMetadata` to get the runtime information for a single run. I wonder if it is possible to achieve the same functionality in tf2.x `tf.function`? I understand we have the beautiful profiling tool introduced in tf2.2, but it would be better if we can get the raw information besides viewing them through tensorboard. 
**Will this change the current api? How?**
It probably will. This may need to add a few more arguments to the function wrapped by `tf.function`.
**Who will benefit with this feature?**
The developer who may need the raw runtime information to tune the model and help make the inherent optimization in tensorflow better.
**Any Other info.**
Not yet.

**Comment by mohantym** [comment]
Hi @zhuzilin !
We are checking to see whether you still need help in this issue .

RunOptions and RunMetadata are still available through compat.v1 mode. 
Regarding collecting runtime information through tf.function , Either you can use [tf.compat.v1.logging_verbosity](tf.compat.v1.logging.set_verbosity) to see the verbose of runtime operations in real time  or [tf.debugging.experimental.enable_dump_debug_info](https://www.tensorflow.org/api_docs/python/tf/debugging/experimental/enable_dump_debug_info) to dump all the runtime information into  a folder.

Thank you!
