### ISSUE TITLE
How to convert tensorflow::tensorproto to tensorflow::tensor in C++

### ISSUE THREAD

**Issue by wangwenchao-job** [tensorflow/tensorflow#40259]
My question is just like the title.

When using tfserving, you need to get the following：
```
tensorflow::SavedModelBundle bundle;
tensorflow::LoadSavedModel(...)
```
The model needs to be predicted after loading：
```
bundle.session.Run(...)
```
However, one input requirement of the run function is tensorflow::tensor type, and my a priori data is of tensorflow::tensorproto type, how do I convert it? In addition, where is the interface documentation for C++?

**Comment by gowthamkpr** [comment]
What version of tensorflow are you using? You can refer to the following question [here](https://stackoverflow.com/questions/44125403/how-to-access-tensor-content-values-in-tensorproto-in-tensorflow) to acess tensor content values in tensorproto

**Comment by wangwenchao-job** [comment]
> What version of tensorflow are you using? You can refer to the following question [here](https://stackoverflow.com/questions/44125403/how-to-access-tensor-content-values-in-tensorproto-in-tensorflow) to acess tensor content values in tensorproto



The version used is tf2.1 C++

**Comment by gowthamkpr** [comment]
@wangwenchao-job Did you take a look at this [issue](https://stackoverflow.com/questions/44125403/how-to-access-tensor-content-values-in-tensorproto-in-tensorflow) as mentioned in the above comment?

**Comment by mihaimaruseac** [comment]
Use [`FromProto`](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/framework/tensor.h;l=361;drc=a67ee929f5aa2e16478d10e3287a248f34078cb5)

This is better suited for StackOverflow. Closing.
