### ISSUE TITLE
Support including tensorflow directly in bazel WORKSPACEs

### ISSUE THREAD

**Issue by keith** [tensorflow/tensorflow#40252]
We recently started including tensorflow in our bazel based iOS builds. Because of the currently required `./configure` step we cannot include it directly in our WORKSPACE and depend on targets as you can with some bazel dependencies, instead we have to pre-compile the targets we're interested in, and vendor them somehow into our build.

It would be great if the tensorflow build system provided a way to be able to depend on it directly from within other bazel workspaces.

Given the current job of the configure script this might be a very difficult request.

**Comment by sushreebarsa** [comment]
@keith Bazel doesn't directly support including TensorFlow as a dependency within your WORKSPACE file.
You could install TensorFlow using pip within your container or build environment and then reference it as an external dependency in your Bazel builds or you can use build from source.
Thank you!
