### ISSUE TITLE
TensorForest Fails in Modified wide_n_deep SKFlow Tutorial

### ISSUE THREAD

**Issue by craymichael** [tensorflow/tensorflow#4025]
### Environment info

Operating System: Ubuntu

Package: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl
Version: 0.10.0rc0

Edit: See update at bottom for stuff I found wrong

I cannot get TensorForest to work using the input_fn parameter as input. It failed in my code, so I tried using it in the wide_n_deep tutorial which failed for the same reasons. Categorical inputs using Sparse tensors are rejected saying the wrong dtype is being used (they're all String). Without using categorical inputs, it gets further but fails saying that it cannot concat Tensors. I was able to run the tests for the TensorForest successfully with the Iris dataset ([link here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/estimators/random_forest_test.py)), but I would like to use the input_fn ability with a similar style to the tutorial if possible. I can provide the source but the only thing changed was using the `tf.contrib.learn.TensorForestEstimator` with the number of classes and features specified in `tf.contrib.tensor_forest.tensor_forest.ForestHParams` as the params input. Can someone look into this?
### Steps to reproduce
1. Modify wide_n_deep tutorial to use a `TensorForestEstimator`
### What I've tried
1. Running using input_fn as parameter to fit
2. Running using input_fn without categorical inputs to fit
#### Output including categorical sparse tensors

```
Traceback (most recent call last):
  File "wide_n_deep_tutorial.py", line 224, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "wide_n_deep_tutorial.py", line 220, in main
    train_and_eval()
  File "wide_n_deep_tutorial.py", line 213, in train_and_eval
    m.fit(input_fn=lambda: input_fn(df_train), steps=FLAGS.train_steps)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 240, in fit
    max_steps=max_steps)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 550, in _train_model
    train_op, loss_op = self._get_train_ops(features, targets)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/random_forest.py", line 149, in _get_train_ops
    features, spec = data_ops.ParseDataTensorOrDict(features)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tensor_forest/data/data_ops.py", line 169, in ParseDataTensorOrDict
    return _ParseSparse(data)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tensor_forest/data/data_ops.py", line 101, in _ParseSparse
    raise ValueError('Only sparse tensors of type string are supported.')
ValueError: Only sparse tensors of type string are supported.
```
#### Output without categorical sparse tensors

```
Traceback (most recent call last):
  File "wide_n_deep_tutorial.py", line 224, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "wide_n_deep_tutorial.py", line 220, in main
    train_and_eval()
  File "wide_n_deep_tutorial.py", line 213, in train_and_eval
    m.fit(input_fn=lambda: input_fn(df_train), steps=FLAGS.train_steps)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 240, in fit
    max_steps=max_steps)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 550, in _train_model
    train_op, loss_op = self._get_train_ops(features, targets)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/random_forest.py", line 149, in _get_train_ops
    features, spec = data_ops.ParseDataTensorOrDict(features)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tensor_forest/data/data_ops.py", line 171, in ParseDataTensorOrDict
    return _ParseDense(data)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tensor_forest/data/data_ops.py", line 144, in _ParseDense
    else data[k] for k in sorted(data.keys())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 759, in concat
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 414, in _concat
    values=values, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2312, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1704, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 815, in _ConcatShape
    (value_shape.ndims, concat_dim))
ValueError: Expected concat_dim in range [0, 1), but got 1
```
### UPDATE

I've fooled around with more stuff and been sifting through the source and have found the following.
1. Tensor Forest doesn't support both categorical and continuous inputs (only Sparse OR Dense)? Why is that, and can we expect that being implemented soon?
2. If solely sparse tensors are inputted, `_ParseSparse` fails because `constants.DATA_ALL_CATEGORICAL` is not defined (I believe it should be `constants.DATA_CATEGORICAL`)
3. Upon changing that variable to `constants.DATA_CATEGORICAL`, everything seems ok until my terminal gets flooded with these warnings:

```
W tensorflow/contrib/tensor_forest/core/ops/sample_inputs_op.cc:164] Could not find any values for input 1 inside sparse_input_indices
W tensorflow/contrib/tensor_forest/core/ops/sample_inputs_op.cc:164] Could not find any values for input 2 inside sparse_input_indices
W tensorflow/contrib/tensor_forest/core/ops/sample_inputs_op.cc:164] Could not find any values for input 1 inside sparse_input_indices
W tensorflow/contrib/tensor_forest/core/ops/sample_inputs_op.cc:164] Could not find any values for input 2 inside sparse_input_indices
```

Those warnings repeat over and over and eventually the model runs successfully.
4. I tried messing with `_Parse_Dense` and changed the `array_ops.concat` to `array_ops.pack` with `axis=1`, which returns the expected 2-D tensor. `concat` doesn't work as it is unable to create the dimension, whereas `pack` can. This resolved the continuous input issue, but I received a negligible error

```
Traceback (most recent call last):
  File "wide_n_deep_tutorial.py", line 224, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "wide_n_deep_tutorial.py", line 220, in main
    train_and_eval()
  File "wide_n_deep_tutorial.py", line 213, in train_and_eval
    m.fit(input_fn=lambda: input_fn(df_train), steps=FLAGS.train_steps)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 240, in fit
    max_steps=max_steps)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 550, in _train_model
    train_op, loss_op = self._get_train_ops(features, targets)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/random_forest.py", line 163, in _get_train_ops
    **self.training_args),
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tensor_forest/python/tensor_forest.py", line 378, in training_graph
    **tree_kwargs))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tensor_forest/python/tensor_forest.py", line 570, in training_graph
    regression=self.params.regression))
  File "<string>", line 219, in count_extremely_random_stats
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 463, in apply_op
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'input_data' of 'CountExtremelyRandomStats' Op has type int64 that does not match expected type of float32.
```

I easily fixed above error by changing all continuous inputs to tf.float32 from tf.int64, so that might be a feature request of interest.
5. After these modifications to source, I was able to use `input_fn` successfully with solely the continuous features of the census data set of the wide_n_deep tutorial (obtained ~82% on the testing set with 10 training steps). Not sure why but it took a while for that to run, didn't really look into it though.
6. I tried including the categorical inputs via tf.string dtype constant tensors, but received another error saying input to StringToFloat was not 2-D.

```
     tensorflow.python.framework.errors.InvalidArgumentError: input_data should be two-dimensional
```

I was able to resolve it by changing `convert_ops.string_to_float` to `tf.string_to_number`, but I am still unable to input via Sparse Tensors.
7. Another issue I found: not all metrics seem to work when passed in (I passed in `streaming_precision`, `streaming_recall`, `streaming_accuracy`, and `confusion_matrix`)

```
    Traceback (most recent call last):  
      File "read.py", line 336, in <module>
        tf.app.run()
      File "/usr/local/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
        sys.exit(main(sys.argv))
      File "read.py", line 315, in main
        eval_steps=1
      File "/usr/local/tensorflow/heartwood/cross_validation/evaluate.py", line 37, in evaluate
        'cm': tf.contrib.metrics.confusion_matrix
      File "/usr/local/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 356, in evaluate
        name=name)
      File "/usr/local/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 630, in _evaluate_model
        eval_dict = self._get_eval_ops(features, targets, metrics)
      File "/usr/local/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/random_forest.py", line 198, in _get_eval_ops
        result[name] = metric(probabilities, labels)
      File "/usr/local/python2.7/dist-packages/tensorflow/contrib/metrics/python/ops/confusion_matrix_ops.py", line 73, in confusion_matrix
        predictions, name='predictions', dtype=dtypes.int64),
      File "/usr/local/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 621, in convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
      File "/usr/local/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 564, in _TensorTensorConversionFunction
        % (dtype.name, t.dtype.name, str(t)))
    ValueError: Tensor conversion requested dtype int64 for Tensor with dtype float32: 'Tensor("probabilities:0", shape=(?, 2), dtype=float32)'
```

**Comment by gilberthendry** [comment]
Sorry for all the troubles.  Long story short, TensorForestEstimator doesn't support such a heterogenous set of inputs as the wide_n_deep tutorial, partly because the TensorForest internal interfaces predate the estimator interface and a more general translation between the two was never put in place because we haven't had a driver for that yet.   What does work is:
1. All continuous numerical inputs
2. All sparse string inputs (that are hashed and mapped to a numerical space and treated as categorical)
3. A mix of continuous and categorical numerical inputs.

Let me try to comment on the things listed under Update:

1. Let me clarify that continuous and categorical inputs are different than sparse and dense representation (you can have categorical dense inputs).  It's a slightly important distinction for forests, because they have the ability to implement a x[i] == T function at nodes instead of x[i] < T.  But it is true that we only support sparse or dense input right now.

2. This was quickly fixed a while ago, but unfortunately the last Tensorflow release seems to have included that mistake.  Installing the nightly build fixes this.

3. This is usually a warning that a given example is totally empty when using sparse inputs.  If you don't think that any examples are totally empty, then it's probably something with the shape of the tensors being input (especially if they're all input 1 and 2).

4. _ParseDense expects 2-D tensors, which is what you get when you use e.g. tf.FixedLenFeature with tf.contrib.learn.read_batch_features (which is what we normally do).  TensorForest is an online training algorithm, so it's really made for reasonable mini-batch sizes (100-10000) that sample from a larger data set. This allows us to train on data sets that are infeasible to read into memory, but also works fine for smaller data sets in our experience. If I'm reading it right it seems like the wide_n_deep tutorial throws the whole column into a 1-D tf.constant. We've set up TensorForest with the assumption that x,y is used for smaller data sets that fit in memory, and input_fn is used for batched large data sets.  Maybe that's not a good assumption, but in any case this should at least be documented better.

5. Again, might be wrong here, but if not using mini-batching, it isn't surprising that training might take a long time. 

6. This is maybe related to 4 and mini-batching.

7. What is confusion_matrix expecting?  TensorForest inference outputs class probabilities, so for e.g. streaming_accuracy, we wrap it in a function that does an argmax to get class prediction.
tensorflow/contrib/tensor_forest/client/eval_metrics.py


Thanks for pointing these things out, I'll be addressing them in some combination of improved documentation, improved error conditions, patching up cases that we can make work, and maybe even some heavy refactoring.

**Comment by craymichael** [comment]
Another update:
I was able to get all metrics I tried to work (confusion matrix, precision, recall etc.) by changing `_get_eval_ops` in `tensorflow/contrib/learn/python/learn/estimators/random_forest.py` as follows:

     def _get_eval_ops(self, features, targets, metrics):
      ...
      if metrics is None:
        metrics = {self.accuracy_metric:
                   eval_metrics.get_metric(self.accuracy_metric)}
     
      result = {}
       
      predictions = math_ops.argmax(probabilities, 1)
      # undo one-hot
      labels = math_ops.argmax(labels, 1)
      for name, metric in six.iteritems(metrics):
        result[name] = metric(predictions, labels)
     
      return result

This was broken because the probabilities were being fed to the metrics instead of the predictions and same situation with the labels essentially. In the `eval_ops` file for the tensor forest, the accuracy metric won't work with these changes as it handles it in the same manner I did

**Comment by craymichael** [comment]
Thanks for the response! Please see my last comment with regards to 7. Would it be reasonable to expect the TensorForest to be implemented in such a way as the other Estimators are? The way I'm working  handles things generically for different model types, so it would be nice if the expected input for all Estimators was the same. Possibly even with features columns?
With regards to 3, none of the tensors I was using were empty to I'm assuming there is a discrepancy between the shapes of the inputs used for the non-tensorforest Estimators. Although those warnings flew by, it eventually fit using only the categorical sparse tensors and got reasonable accuracy for not having all features as input.
I don't think that's a good assumption for `input_fn`, although that's what I would like to use it for but having issues (see #4026), because it's currently the only method of being able to input tensors to the model. 
I apologize for 1, I meant continuous and categorical data not sparse vs dense. A lot of data I work with contains continuous numerical data alongside String categorical data. I've found in my research that the RandomForest models work the best with my specific data over other types of models. I guess in the meantime while it's not possible I can implement the model for a sparse representation of my categorical data and another model for the continuous part of my data and look into methods of combining predictions?

**Comment by gilberthendry** [comment]
I will certainly look into improving the interface and making it more compatible with other Estimators, though I can't promise a timeline right now.

The two-forest method would work.  Another thing that might work is translating the categorical features into dense Tensors (if they're strings, try to hash and reinterpret the bits as floats.  If they're already numbers and the index space is large but the value space is small, treat the index space as the feature value. If the value space is large but the index space is small, see if tf.sparse_to_dense won't blow up).  Another thing that would work is train an embedding on your sparse features and concat that onto your dense ones.

**Comment by craymichael** [comment]
Thanks a lot! I really appreciate it. I think I'll try the two-forest method first and compare to the categorical to dense approach. I would like to clarify what you mean by index and value space; if I have a feature with 10 different unique values and 100 examples, the value space is 10 and the index is 100?

**Comment by gilberthendry** [comment]
So I've seen SparseTensors used to represent different kinds of data.  Such as:

1. The "typical" meaning of sparse, where each example has a few columns out of many that are present and rest are assumed zero or "".  If the sparse_tensor.values are only ever 0 or 1, I consider this a small value space and possibly large feature space.

2. A convenient way to represent a variable length list of values.  e.g. a few strings per example.  While maybe this can be made to look like 1), I would consider this to have a small index space (a "few" strings) and a large value space (any possible string).  

Good luck with the two-forest, I'd be interested to hear how it goes.

**Comment by craymichael** [comment]
Ok thanks for that clarification! I won't be getting to the two-forest until next Monday but I'll share my findings! Forest hasn't performed bad at all on only categorical or continuous inputs. I'll probably start by averaging the prediction probabilities from each forest and compare that to some over methods. Thanks again!

**Comment by craymichael** [comment]
Alright, just figured out a working way for me to get categorical (non-numeric) and continuous inputs solely through Dense tensors. I made use of the layers I wanted for the model with the combination of `tf.contrib.layers.input_from_feature_columns`. I made use of `tf.contrib.layers.sparse_column_with_hash_bucket` with `tf.contrib.layers.embedding_column` to handle my categorical inputs. I restored `_Parse_Dense` to its original state as it was then receiving 2D inputs as expected via this method. I think if this Estimator is refactored it will be in the best interest to allow it to accept feature_column inputs. Thanks for your assistance and best of luck with your work!

**Comment by craymichael** [comment]
Is there currently a way to calculate mean decrease gini for each feature? I see that I'm able to retrieve the average impurity but I believe it's for the forest as a whole.

**Comment by gilberthendry** [comment]
You could calculate gini for each feature that is being considered as a split candidate for a node that is currently growing (which is how we end up picking the feature to use at a node).  The candidate_split_sums variable in each tree keeps class counts for each feature under consideration. But we don't track them on the whole-tree level, mostly because it would be expensive to keep class counts for each feature around (which becomes very important when you consider building large forests).

**Comment by craymichael** [comment]
Finally getting around to try and implement this. When I look at the `candidate_split_features` values, I see that I have values from 0 to 86 in a vector the shape of [max_fertile_nodes, num_splits_to_consider]. I'm confused as to what the 87 values correspond to; I input and specify 41 features to the forest so I am confused as to what these numbers represent.

**Comment by gilberthendry** [comment]
The values chosen for candidate_split_features are sampled from a uniform distribution with a max value of num_features as inferred from the second dimension of the input data (assuming we're talking about dense data).  Can you verify the shape of input data, and make sure all the sparse inputs are None.

candidate_split_sums (and other sums like node_sums) store the sum of all the other entries in index 0, because we make use of the sum a lot and it was easier than recalculating it all the time.  So the shape should be num_classes + 1.

**Comment by craymichael** [comment]
Oh thanks for clarifying `candidate_split_sums`, I should've figured that one out. As to `candidate_split_features`, I made the assumption that the parameter I set would be used as the max features; counting the degrees of freedom (embeddings) for each categorical feature gave me 87 inputs, which is correct.

Follow up question, how do I decipher which feature is which? I input the features in the form of a dictionary via `input_fn`, so there's no fixed order going in. Additionally, is there a straightforward way of knowing when a node is growing and the class counts/feature being split? If I have the right understanding now, I should be able to calculate the gini impurity index using the candidate class counts for each candidate feature whenever a node is growing, given I know when that node grows and which feature is which. 

What does `accumulator_sums` track? From what I've found, forests accumulate the decreases is Gini impurity from the optimal splits found.

**Comment by gilberthendry** [comment]
_ParseDense does a sorted(data.keys()) when concatenating dense inputs, so you'll get a consistent ordering according to python sort.  

There are two maps - node_to_accumulator_map and accumulator_to_node_map that let you translate between node id and accumulator id (a node assigned to an accumulator is growing).  The accumulator id is then used to index into e.g. candidate_split_features, candidate_split_sums, etc.  

accumulator_sums track the total class counts that arrive to an accumulator, and candidate_split_sums track the class counts that take the LEFT branch.  We can then infer the right-branch-taken class counts.

**Comment by craymichael** [comment]
Thanks so much for the help! I don't see the `accumulator_to_node_map` variable you mentioned when I look at all the model's variables. It's not in my way right now but just thought you should know.

**Comment by craymichael** [comment]
I see in the `_weighted_gini` calculation, the class counts are taken via `smoothed = 1.0 + array_ops.slice(class_counts, [0, 1], [-1, -1])`; may I ask why one is being added to every class count and whether this needs to be done for the class counts in variables such as `accumulator_sums`?

**Comment by gilberthendry** [comment]
That's simple Laplace smoothing, mostly to avoid div/0 when no examples have arrived to an accumulator or a leaf.

**Comment by drpngx** [comment]
Closing since it looks like we have a solution.
