### ISSUE TITLE
Code for univariate_data() preprocessing function in LSTM Timeseries documentation example incorrect

### ISSUE THREAD

**Issue by Ujustwaite** [tensorflow/tensorflow#40257]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://www.tensorflow.org/tutorials/structured_data/time_series

## Description of issue (what needs changing):

The code for the univariate_data function in the example located at the above site creates a series of indexing and method not found errors. It can be resolved by the following code. 

def univariate_data(dataset, start_index, end_index, history_size, target_size):
  data = []
  labels = []

  start_index = start_index + history_size
  if end_index is None:
    end_index = len(dataset) - target_size

  for i in range(start_index, end_index):
    #indices = range(i-history_size, i)

    # Reshape data from (history_size,) to (history_size, 1)
    data.append(dataset[i-history_size:i].values.reshape(history_size, 1))
    labels.append(dataset[i+target_size])
  return np.array(data), np.array(labels)

**Comment by marko-radojcic** [comment]
Tensorflow/Tensorflow is dynamic being. You can not steal her soul and keep
it static.
Cure your programming addiction by taking vacation.

**Comment by ravikyram** [comment]
@Ujustwaite 

Can you provide the colab link to show where exactly you are facing the problem.Thanks!
