### ISSUE TITLE
learned_unigram_candidate_sampler may enter infinite loop when range_max is a very large number

### ISSUE THREAD

**Issue by leeyeetonn** [tensorflow/tensorflow#40263]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0 & v2.1.0-rc2-17-ge5bf8de 2.1.0
- Python version: 3.7.6
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
`tf.random.learned_unigram_candidate_sampler`/`tf.nn.learned_unigram_candidate_sampler` may enter infinite loop when `range_max` is a very large number.

When `range_max` is a large number, the execution may stuck in the while loop [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/random/weighted_picker.cc#L32-L34). The `LevelSize` function returns `1 << level`, so when `level` is a large number, the left shift will have undefined behavior. So `LevelSize(num_levels_ - 1)` may never be `>= N`, causing infinite loop.

**Describe the expected behavior**
In `WeightedPicker::WeightedPicker(int N)`, there should be a boundary checking for `N` (same number as `range_max`). If input `N` is big enough to cause left shift to have undefined behavior, tensorflow should raise a warning to the user and perhaps an exception to stop the execution.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```python
import tensorflow as tf
import numpy as np

# this function call will not terminate
tf.random.learned_unigram_candidate_sampler(
    true_classes=np.random.rand(100, 10),
    num_true=10,
    num_sampled=100,
    unique=True,
    range_max=2000000000, # big enough to cause << to have undefined behavior & cause infinite loop
)
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.1, 2.2, nightly version(`2.3.0-dev20200605`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/8a6f0588ce2197d525ef1eed0715d6c6/untitled964.ipynb).Thanks!

**Comment by saikumarchalla** [comment]
Was able to replicate the issue in TF 2.5. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/c274b12e078590ef5378634ddab17360/untitled83.ipynb).Thanks!

**Comment by tilakrayal** [comment]
@leeyeetonn,
When I tried to execute the mentioned with the small input range (200), it was executed without any issue/error. With the range_max=2000000000 it was entering an infinite loop which was expected.  Kindly find the gist of it here and also This operation randomly samples a tensor of sampled classes (sampled_candidates) from the range of integers [0, range_max)].

Every integer in [0, range_max) begins with a weight of 1, and is incremented by 1 each time it is seen as a target class. The base distribution is not saved to checkpoints, so it is reset when the model is reloaded. Thank you!

**Comment by tilakrayal** [comment]
Closing this as stale. Please reopen if this is still a valid request. Thank you!
