### ISSUE TITLE
Unexpected rise in inference time after quantization

### ISSUE THREAD

**Issue by syamsruthin** [tensorflow/tensorflow#40266]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 and Colab
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 1.15.0 ,2.2.0, 2.2.0-dev20200508 for QAT
- Python version: 3.6.5
- GPU model and memory: using CPU

**Describe the current behavior**
The inference time of TF-Lite model becomes extremely high after the post training integer quantization and after Quantization Aware Training of model when using calibration dataset for static quantization.
Tried on various models and with different datasets on 1.15.0 and also on 2.2.0 and  2.2.0-dev20200508 for QAT

**Describe the expected behavior**
The inference time of TFlite model (with post-training static quantization and after QAT) should be less or at least equal to TFLite model without quantization. 

**Steps and code to reproduce the issue**

Links for notebook files: 
https://drive.google.com/file/d/1XFWXp-nXhEdBuikaW3q3uJ2EmPy8fbOZ/view?usp=sharing
https://drive.google.com/file/d/16kEu87nj-Q2gjgET6CcZUvKxJvpi6pMW/view?usp=sharing

Train keras model using the dataset.(Using california housing data)

input_size = 8 

model = keras.Sequential()
model.add(tf.keras.layers.Flatten())
for i in range(0,2):
    model.add(tf.keras.layers.Dense(1024,activation='relu'))
    
model.add(tf.keras.layers.Dense(1))

In TF 1.15.0:
----------------
Created ONNX model using h5 file of saved model using keras2onnx. (Also tried the same flow by generating ONNX model using pytorch with same model architecture)
Created '.pb' file from ONNX model. 
Using  'tf.lite.TFLiteConverter.from_frozen_graph' to create TFLite model. 

In TF 2.2.0:
----------------
Using  'tf.lite.TFLiteConverter.from_keras_model' to create TFLite model.

case-1
=======
converter = tf.lite.TFLiteConverter.from_frozen_graph(<path to .pb file>,['input_1'],['output_1'])    
converter.optimizations = [tf.lite.Optimize.DEFAULT]    
converter.representative_dataset = representative_data_gen
tflite_int_model = converter.convert()

case-2
=======
converter = tf.lite.TFLiteConverter.from_frozen_graph(<path to .pb file>,['input_1'],['output_1'])    
converter.optimizations = [tf.lite.Optimize.DEFAULT]    
converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

case-3(QAT):
=======
quantize_model = tfmot.quantization.keras.quantize_model
q_aware_model = quantize_model(model)
q_aware_model.compile(optimizer='rmsprop',loss='mean_squared_error')
q_aware_model.summary()

q_aware_model.fit(x, y, batch_size=128, epochs=2, validation_split=0.2)

converter = tf.lite.TFLiteConverter.from_keras_model(q_aware_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

Now loading the quantized TFLite models for inference. 

Without quantization, the average inference time of TFLite model is 100 microseconds in my PC and around 200 on google colab (avg for one record when run inference for 1000 input records)
In all the cases(case1,case2 and case3 mentioned above), After quantization, the average inference time of TFLite model is around 10000 microseconds in my PC and its around 500 on colab(avg for one record when run inference for 1000 input records)

**Comment by amahendrakar** [comment]
@syamsruthin,
On running the code, I'm facing an error stating `KeyError: "The name 'sequential/Identity' refers to an Operation not in the graph."`. 

Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/1bb99d7b7ec2c1c95254da120f170afd/40266-1-15.ipynb). Thanks!

**Comment by syamsruthin** [comment]
@amahendrakar 
- This is because of enabling eager execution during model creation and training. Can you please comment this "tf.enable_eager_execution()" and run the model training again before converting it to onnx. 
- tf.enable_eager_execution() is required when we are creating and during inference of static quantized tflite model. (When giving representation data set to create static quantized tflite model)
- So, after creating onnx model, this option needs to be enabled before running quantization code. 

Hope this is clear.

**Comment by syamsruthin** [comment]
@amahendrakar  any update on this?  were you able to reproduce this issue?

**Comment by syamsruthin** [comment]
@amahendrakar  Modified the notebook that you shared. I'm able to reproduce the error. You can find the results there in the notebook. 
https://colab.research.google.com/gist/syamsruthin/c64279c9e348b39d558b0ceba2697baa/40266-1-15.ipynb

**Comment by amahendrakar** [comment]
@syamsruthin,
Sorry for the delayed response. I am still unable to reproduce the issue. 

On running the code, I am facing an error stating `ValueError: Invalid tensors 'input_1' were found.` Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/878b611c6dfe8bf617634647d7a8d329/40266-1-15.ipynb#scrollTo=rIs794paf4Ql). Thanks!

**Comment by syamsruthin** [comment]
@amahendrakar  Looks like a day before the library tf2onnx got updated and I guess this issue is because of this. 
I tried to recreate this same issue in another way. 
Please find the gist of it in this link: [https://colab.research.google.com/gist/syamsruthin/f2b1307bf09542d62ebf3b15d6ae9a85/issue_40266.ipynb](url)
Thanks!

**Comment by syamsruthin** [comment]
@amahendrakar The Above link to the notebook is not working. Please copy-paste the link in the browser.
Thanks!

**Comment by amahendrakar** [comment]
@syamsruthin,
Thank you for providing the gist. I was able to reproduce the issue with TF v1.15. 

Could you please share the `model.h5` file you are using while running the code in TF 2.x. Thanks!

**Comment by syamsruthin** [comment]
@amahendrakar  Here is the gist for creating .h5 file for tf2.2
https://colab.research.google.com/gist/syamsruthin/3485c5e7cce5961bf45c554f38ba1ac7/issue_40266_tf_2.ipynb
Thanks.

**Comment by syamsruthin** [comment]
@ymodak @amahendrakar  
Hi... any update on this?

**Comment by syamsruthin** [comment]
@ymodak  @amahendrakar 
Looking forward to you answer !! 
Thanks.

**Comment by ymodak** [comment]
@syamsruthin Apologies for the delay in response. Is this still an issue?
The colab you shared contains incomplete code, I do not see quantization inference stats. 
Thanks!
