### ISSUE TITLE
Keras layer on TPU, Cannot assign a device for operation RandomUniform

### ISSUE THREAD

**Issue by albertz** [tensorflow/tensorflow#40267]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.2.0, v2.2.0-rc4-8-g2b96f3662b
- Python version: 3.6.9
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: None
- GPU model and memory: TPU

**Describe the current behavior**

I'm trying to use the `tf.keras.layers.Dense` layer on TPU.
I get the exception `InvalidArgumentError: Cannot assign a device for operation encoder/kernel/Initializer/random_uniform/RandomUniform: Could not satisfy explicit device specification '' because the node {{colocation_node encoder/kernel/Initializer/random_uniform/RandomUniform}} was colocated with a group of nodes that required incompatible device '/device:TPU:0'. All available devices [/job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0].`.

**Describe the expected behavior**

I would expect that this works.

**Standalone code to reproduce the issue**

```
import os
import tensorflow as tf
import numpy

# https://www.tensorflow.org/guide/tpu
if os.environ.get('COLAB_TPU_ADDR', ""):
  resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='grpc://' + os.environ['COLAB_TPU_ADDR'])
  tf.config.experimental_connect_to_cluster(resolver)
  # This is the TPU initialization code that has to be at the beginning.
  tf.tpu.experimental.initialize_tpu_system(resolver)

tf.compat.v1.disable_v2_behavior()
tf.compat.v1.reset_default_graph()

with tf.device("/TPU:0"):
  x = tf.compat.v1.placeholder(tf.float32, shape=(3, 4, 2), name="x")
  encoder = tf.keras.layers.Dense(units=5, activation="tanh", name="encoder")(x)

  vars_init_op = tf.compat.v1.global_variables_initializer()

rnd = numpy.random.RandomState(42)
x_np = rnd.normal(size=(3, 4, 2))

with tf.compat.v1.Session() as session:
  session.run(vars_init_op)
  session.run(encoder, feed_dict={x: x_np})

```

[Colab](https://colab.research.google.com/drive/1WTzn71tXYWeyyDxqFwXxblnDhZtxAbQX?usp=sharing).

**Other info / logs**

```
InvalidArgumentError: Cannot assign a device for operation encoder/kernel/Initializer/random_uniform/RandomUniform: Could not satisfy explicit device specification '' because the node {{colocation_node encoder/kernel/Initializer/random_uniform/RandomUniform}} was colocated with a group of nodes that required incompatible device '/device:TPU:0'. All available devices [/job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0]. 
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=-1 requested_device_name_='/device:TPU:0' assigned_device_name_='' resource_device_name_='/device:TPU:0' supported_device_types_=[CPU, XLA_CPU] possible_devices_=[]
AssignVariableOp: CPU XLA_CPU 
RandomUniform: CPU XLA_CPU 
VarIsInitializedOp: CPU XLA_CPU 
Const: CPU XLA_CPU 
Mul: CPU XLA_CPU 
ReadVariableOp: CPU XLA_CPU 
Sub: CPU XLA_CPU 
VarHandleOp: CPU XLA_CPU 
Add: CPU XLA_CPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  encoder/kernel/Initializer/random_uniform/shape (Const) 
  encoder/kernel/Initializer/random_uniform/min (Const) 
  encoder/kernel/Initializer/random_uniform/max (Const) 
  encoder/kernel/Initializer/random_uniform/RandomUniform (RandomUniform) 
  encoder/kernel/Initializer/random_uniform/sub (Sub) 
  encoder/kernel/Initializer/random_uniform/mul (Mul) 
  encoder/kernel/Initializer/random_uniform (Add) 
  encoder/kernel (VarHandleOp) /device:TPU:0
  encoder/kernel/IsInitialized/VarIsInitializedOp (VarIsInitializedOp) /device:TPU:0
  encoder/kernel/Assign (AssignVariableOp) /device:TPU:0
  encoder/kernel/Read/ReadVariableOp (ReadVariableOp) /device:TPU:0
  encoder/Tensordot/ReadVariableOp (ReadVariableOp) 

	 [[{{node encoder/kernel/Initializer/random_uniform/RandomUniform}}]]
```

Maybe #31318 is related?

**Comment by ravikyram** [comment]
I have tried in colab with TFversion 2.2, nightly version(`2.3.0-dev20200605`) .Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/5f37166e7ea2ee16949175caab8ae467/untitled965.ipynb).Is this the expected behavior?.Thanks!

**Comment by albertz** [comment]
What do you mean by expected? I expect that my code runs without error. But you have reproduced exactly the error I was reporting (for TF 2.2.0).
For nightly TF 2.3, you get another error. Which also looks strange and wrong. But this might be a different problem or bug? Or the same? Or related? I don't know.

**Comment by nikitamaia** [comment]
Hi @albertz, the tf-nightly error is unrelated and explained in this comment here:  https://github.com/tensorflow/tensorflow/issues/40622#issuecomment-654488935

As for the error you've reported, it seems that initializing the variables is what's causing the problem since it says
`Cannot assign a device for operation encoder/kernel/Initializer/random_uniform/RandomUniform`
Given that the message also says `supported_device_types_=[CPU, XLA_CPU]` then the TPU implementation does not exist for RandomUniform. If you set allow_soft_placement, your code will run:

`sess = tf.compat.v1.Session(config=tf.compat.v1.ConfigProto(allow_soft_placement=True, log_device_placement=True))`

Note that since you're using legacy TF 1, your code is prone to running into more errors and unsupported features like this. Switching to TF2 should allow you to run the computation for your encoder on the TPU, as I think it's the use of the placeholder that's causing the problem.

**Comment by albertz** [comment]
Yes, I think the error is clear. But I would still expect that this code works, or not? This is sth which can (and should) be fixed on the TF side. You can e.g. implement `RandomUniform` for TPU. Or some extra logic in `tf.keras.layers.Dense` which would use `with tf.device("/CPU:0"):` for the initializers.

Also, I really prefer the non-eager mode, and explicit sessions.

But why does that even matter? `tf.function` would use `allow_soft_placement=True` by default? Is this a good idea?

**Comment by nikitamaia** [comment]
There's better support and testing when using TF2 without disabling v2 behavior. In TF2, variables are initialized automatically both in eager and graph contexts.

The following should be equivalent TF2 code. If you set `tf.debugging.set_log_device_placement(True)` you'll see that TPU is being used for all computation

```
@tf.function
def encoder_fn(x,encoder):
    return encoder(x)

with tf.device("/TPU:0"):
  rnd = numpy.random.RandomState(42)
  x_np = rnd.normal(size=(3, 4, 2))
  x_np = tf.constant(x_np, dtype=tf.float32)
  encoder = tf.keras.layers.Dense(units=5, activation="tanh", name="encoder")
  encoder_fn(x_np, encoder)
```

You'll notice that with `tf.debugging.set_log_device_placement(True)` the first line of the logs show
`Executing op RandomUniform on task /job:worker/replica:0/task:0/device:TPU:0`
So looks like RandomUniform is being executed on the TPU. I think the problem you're running into is just from trying to use TPUs with TF2 and disabling v2 behavior.

**Comment by albertz** [comment]
How can `RandomUniform` be calculated on TPU, if the op doesn't support TPU for computation? This is independent from which behavior is enabled/disabled, right?

**Comment by nikitamaia** [comment]
I don't think it's independent since variable initialization has different behavior in TF1 and TF2. For example, Keras and TPUStrategy work best with eager execution enables as noted in issue #38506.

**Comment by albertz** [comment]
I'm just speaking about the `RandomUniform` op, not about variable initialization. Whether this op can be executed on TPU or not does not depend on the enabled behavior.

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!

**Comment by albertz** [comment]
The same problem is still there in TF 2.7.

**Comment by albertz** [comment]
@nikitamaia Why was this closed? There is no solution.
