### ISSUE TITLE
Use the trained k-NN classifier model to classify new, previously unseen objects 

### ISSUE THREAD

**Issue by Udityanshu** [tensorflow/tensorflow#40262]
I am trying to run below following lines in Jupiter notebook using necessary libraries and packages but yet its not running for me:

fruit_prediction = knn.predict([[20, 4.3, 5.5]])
lookup_fruit_name[fruit_prediction[0]]

Moreover below is the following error I am getting:
ValueError                                Traceback (most recent call last)
<ipython-input-12-1d28f9746e24> in <module>
----> 1 fruit_prediction = knn.predict([[20, 4.3, 5.5]])
      2 lookup_fruit_name[fruit_prediction[0]]

~\AppData\Roaming\Python\Python37\site-packages\sklearn\neighbors\_classification.py in predict(self, X)
    171         X = check_array(X, accept_sparse='csr')
    172 
--> 173         neigh_dist, neigh_ind = self.kneighbors(X)
    174         classes_ = self.classes_
    175         _y = self._y

~\AppData\Roaming\Python\Python37\site-packages\sklearn\neighbors\_base.py in kneighbors(self, X, n_neighbors, return_distance)
    661                 delayed_query(
    662                     self._tree, X[s], n_neighbors, return_distance)
--> 663                 for s in gen_even_slices(X.shape[0], n_jobs)
    664             )
    665         else:

~\OneDrive\Documents\Python\lib\site-packages\joblib\parallel.py in __call__(self, iterable)
   1027             # remaining jobs.
   1028             self._iterating = False
-> 1029             if self.dispatch_one_batch(iterator):
   1030                 self._iterating = self._original_iterator is not None
   1031 

~\OneDrive\Documents\Python\lib\site-packages\joblib\parallel.py in dispatch_one_batch(self, iterator)
    845                 return False
    846             else:
--> 847                 self._dispatch(tasks)
    848                 return True
    849 

~\OneDrive\Documents\Python\lib\site-packages\joblib\parallel.py in _dispatch(self, batch)
    763         with self._lock:
    764             job_idx = len(self._jobs)
--> 765             job = self._backend.apply_async(batch, callback=cb)
    766             # A job can complete so quickly than its callback is
    767             # called before we get here, causing self._jobs to

~\OneDrive\Documents\Python\lib\site-packages\joblib\_parallel_backends.py in apply_async(self, func, callback)
    204     def apply_async(self, func, callback=None):
    205         """Schedule a func to be run"""
--> 206         result = ImmediateResult(func)
    207         if callback:
    208             callback(result)

~\OneDrive\Documents\Python\lib\site-packages\joblib\_parallel_backends.py in __init__(self, batch)
    568         # Don't delay the application, to avoid keeping the input
    569         # arguments in memory
--> 570         self.results = batch()
    571 
    572     def get(self):

~\OneDrive\Documents\Python\lib\site-packages\joblib\parallel.py in __call__(self)
    251         with parallel_backend(self._backend, n_jobs=self._n_jobs):
    252             return [func(*args, **kwargs)
--> 253                     for func, args, kwargs in self.items]
    254 
    255     def __reduce__(self):

~\OneDrive\Documents\Python\lib\site-packages\joblib\parallel.py in <listcomp>(.0)
    251         with parallel_backend(self._backend, n_jobs=self._n_jobs):
    252             return [func(*args, **kwargs)
--> 253                     for func, args, kwargs in self.items]
    254 
    255     def __reduce__(self):

~\AppData\Roaming\Python\Python37\site-packages\sklearn\neighbors\_base.py in _tree_query_parallel_helper(tree, *args, **kwargs)
    488     under PyPy.
    489     """
--> 490     return tree.query(*args, **kwargs)
    491 
    492 

sklearn\neighbors\_binary_tree.pxi in sklearn.neighbors._kd_tree.BinaryTree.query()

ValueError: query data dimension must match training data dimension

Can someone please tell me what I should I do ?

**Comment by power-art** [comment]
I want to fix this issue.

**Comment by amahendrakar** [comment]
@Udityanshu,
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/ask) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by Udityanshu** [comment]
Sounds good
