### ISSUE TITLE
Shuffle buffer filled

### ISSUE THREAD

**Issue by nashid** [tensorflow/tensorflow#40273]
I am getting the following logging:

```
2020-06-08 06:09:37.995077: I tensorflow/core/kernels/shuffle_dataset_op.cc:112] Filling up shuffle buffer (this may take a while): 59921 of 64000

2020-06-08 06:09:38.725673: I tensorflow/core/kernels/shuffle_dataset_op.cc:126] Shuffle buffer filled.
````

What does it mean?

**Comment by Saduf2019** [comment]
@nashid 
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by nashid** [comment]
Please find details:

```
-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: used the default example from https://github.com/tensorflow/nmt

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: RHEL 6

-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: NA

-   **TensorFlow installed from (source or binary)**: using pip install tensorflow

-   **TensorFlow version (use command below)**: 1.5.0

-   **Python version**: 3.6.10
-   **Bazel version (if compiling from source)**: N/A
-   **GCC/Compiler version (if compiling from source)**: N/A
-   **CUDA/cuDNN version**: N/A
-   **GPU model and memory**: N/A
```

**Comment by Saduf2019** [comment]
@nashid 
Please refer to these link with similar error:

[link](https://github.com/beringresearch/ivis/issues/56#issuecomment-571191817)
[link1](https://stackoverflow.com/questions/51366082/tensorflow-get-high-loss-after-filling-up-shuffle-buffer)
[link2](https://forum.opennmt.net/t/tensorflow-error-with-training-command/3290/2)

Please update details on the version on tensorflow used and the exact steps or code before which this log is faced.

**Comment by BAParanjape** [comment]
In the code below, where do I change the font of the bounding box label?

"vis_util.visualize_boxes_and_labels_on_image_array(
      image_np,
      output_dict['detection_boxes'],
      output_dict['detection_classes'],
      output_dict['detection_scores'],
      category_index,
      instance_masks=output_dict.get('detection_masks'),
      use_normalized_coordinates=True,
      line_thickness=8)
  plt.figure(figsize=IMAGE_SIZE)
  plt.imshow(image_np)"

**Comment by Saduf2019** [comment]
@BAParanjape 
Kindly open a stackoverflow issue for this as it is not a bug or feature request, Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions.
Thanks!
