### ISSUE TITLE
TfLite Sign Op Support

### ISSUE THREAD

**Issue by lizhen2017** [tensorflow/tensorflow#40270]
How long will the sign op be surpported? Or would you please provide some suggestions for implementing a tflite custom op using eigen lib as tf sign op.

**Comment by terryheo** [comment]
You can use tf sign with Flex delegate.
https://www.tensorflow.org/lite/guide/ops_select
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/flex/whitelisted_flex_ops.cc#L369

For custom operator implementation, plz check https://www.tensorflow.org/lite/guide/ops_custom
