### ISSUE TITLE
[cmake] Build error in dependency re2

### ISSUE THREAD

**Issue by aolsux** [tensorflow/tensorflow#4027]
Somehow the re2 dependency does not get build correctly.
I think its because of `re2_INCLUDE_DIR` in re.cmake holding two directories. Then `COMMAND ${CMAKE_COMMAND} -E make_directory ${re2_INCLUDE_DIR}` fails since `cmake -E make_directory` only takes one arg. I'm just comiping and might add a PR if it works.

**Comment by prb12** [comment]
Please can you provide the information requested in the TensorFlow issues reporting template.

**Comment by tatatodd** [comment]
Closing this out due to inactivity.  Please comment with the requested information, so that we can attempt to reproduce, and I will reopen.
