### ISSUE TITLE
Floating point exception occurred in tf.nn.fractional_max_pool

### ISSUE THREAD

**Issue by mjkim720** [tensorflow/tensorflow#40287]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.6.9
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Floating point exception (arithmetic exception) occurs in c++ while executing `tf.nn.fractional_max_pool` when passing the first element of `pooling_ratio` > 2.0`. 

**Describe the expected behavior**
According to the document (https://www.tensorflow.org/api_docs/python/tf/nn/fractional_max_pool), the first and the last elements of `pooling_ratio` must be 1.0. However, in some cases,  even though these elements are not 1.0 no exception occurs.  I think the way `fractional_max_pool` handles invalid inputs should be consistent at least. 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
import tensorflow as tf

tensor_4D = [[[[0, 1, 1], 
                      [2, 3, 3],
                      [1, 3, 2]],
                     [[1, 3, 2],
                      [2, 4, 2],
                      [0, 1, 1]]],
                      [[[0, 3, 1], 
                      [2, 4, 1],
                      [1, 3, 2]],
                     [[1, 1, 1],
                      [2, 3, 4],
                      [1, 3, 2]]],
                     [[[2, 2, 4], 
                      [2, 1, 3],
                      [0, 4, 2]],
                     [[2, 4, 1],
                      [2, 3, 0],
                      [1, 3, 3]]]]
pooling_ratio = [2.1]

tf.nn.fractional_max_pool(tensor_4D, pooling_ratio)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@mjkim720 I cannot reproduce the issue. When I ran your code is colab, session was crashing. Please take a look at the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/ba918ec54c38814664568e13027f3dc0/40287.ipynb). Thanks!

Can you please a standalone code to reproduce the issue? Thanks!

**Comment by mjkim720** [comment]
The attached code above is reproducible. It is expected the session crashes in Colab because the floating point exception occurs in C++, causing it to core dump.

**Comment by jvishnuvardhan** [comment]
@mjkim720 I tested your code with `tf-nightly` and it throws a `ValueError ` as expected and the error trace is shown below. I don't see any session crashing as noticed earlier. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/539a582018d408de4a81da7d1308cea0/40287.ipynb).

The following is the error trace 

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-335f3373d27b> in <module>()
     21 pooling_ratio = [2.1]
     22 
---> 23 tf.nn.fractional_max_pool(tensor_4D, pooling_ratio)

1 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/nn_ops.py in fractional_max_pool_v2(value, pooling_ratio, pseudo_random, overlapping, seed, name)
   5614     if (pooling_ratio[0] != 1.0 or pooling_ratio[-1] != 1.0):
   5615       raise ValueError(
-> 5616           "The first and last elements of pooling ratio must be 1.0.")
   5617     for element in pooling_ratio:
   5618       if element < 1.0:

ValueError: The first and last elements of pooling ratio must be 1.0.
```
