### ISSUE TITLE
simple tf.vectorized_map raises error UnrecognizedFlagError: Unknown command line flag 'f'

### ISSUE THREAD

**Issue by AndreasMadsen** [tensorflow/tensorflow#40280]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow installed from (source or binary): Default Colab
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6.9
- CUDA/cuDNN version: N/A tested on CPU
- GPU model and memory: N/A tested on CPU

**Describe the current behavior**

```py
import tensorflow as tf

print(tf.vectorized_map(
    lambda seq: tf.reduce_min(tf.where(seq)),
    tf.constant([[False, True],
                 [True, False]])
))
```

Outputs the following error:

```
UnrecognizedFlagError: Unknown command line flag 'f'
```

I've seen this error quite often when using `tf.vectorized_map`, in very different settings. However, this is the simplest cast I've found so far. So I suspect the error is not limited to `tf.where()`.

**Describe the expected behavior**

I would expect the output to be:
```
tf.constant([1, 0], dtype=tf.dtypes.bool)
```

**Standalone code to reproduce the issue**

https://colab.research.google.com/gist/AndreasMadsen/9ee1fa1669aa7c656070ca5a850d7210/vectorized-map-bug.ipynb

**Other info / logs**

```
StagingError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py:183 f  *
        return _pfor_impl(loop_fn, iters, parallel_iterations=parallel_iterations)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py:269 _pfor_impl  **
        outputs.append(converter.convert(loop_fn_output))
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/parallel_for/pfor.py:1284 convert
        output = self._convert_helper(y)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/parallel_for/pfor.py:1457 _convert_helper
        if flags.FLAGS.op_conversion_fallback_to_while_loop:
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/flags.py:85 __getattr__
        wrapped(_sys.argv)
    /usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py:633 __call__
        name, value, suggestions=suggestions)

    UnrecognizedFlagError: Unknown command line flag 'f'
```

**Comment by ravikyram** [comment]
@AndreasMadsen 

Can you try with TF nightly version (`2.3.0-dev20200608`) and see if the issue still persists.I am not seeing any issue with nightly version.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/c450a39bee1221aad6654174fd845165/untitled968.ipynb). You could use tf-nightly for now and in the next couple of months new stable version will be released.Please,verify once and close the issue.Thanks!

**Comment by AndreasMadsen** [comment]
I can confirm it works on nightly. I was looking through the commits and I think https://github.com/tensorflow/tensorflow/commit/867673d63b6ee56229498176fc3a00235b8eb2cf#diff-081213481ade84ce14e9afaa3f3505b9L283 fixed it. Although, I think it hides an underlying bug with the `flags` API, when used with Colab.

The code

```
import sys
print(sys.argv)
```

Outputs `['/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py',
 '-f',
 '/root/.local/share/jupyter/runtime/kernel-d86e104c-d0a6-40e7-9533-ce825b3cb03d.json']`. Which causes the flag parser to fail. Because it doesn't understand the `-f` flag.

The error can be reproduced with:

```
from absl import flags
flags.FLAGS(sys.argv)
```

I don't know if this is an issue with
* `absl` for not supporting Colab
* or TensorFlow to not instructing `absl` on how to handle `-f`
* or Colab for passing in the `-f` flag.

**Comment by ravikyram** [comment]
@AndreasMadsen 

Please, close the issue as the original issue was resolved. Request you to raise a new issue with flags API by filling issue template.Thanks!

**Comment by AndreasMadsen** [comment]
I submitted an issue here: https://github.com/googlecolab/colabtools/issues/1323

**Comment by craigcitro** [comment]
FWIW, I do think there's a deeper TF-side issue here: a library shouldn't be parsing `sys.argv`, since it has no control over the program that invoked it. A simple fix might be allowing unknown flags when parsing `sys.argv`.

That said, for this particular issue, it looks like the code in question is gone, so mostly leaving this comment as a breadcrumb for posterity.

**Comment by spate141** [comment]
Seems like this is the workaround for at least TF2.2.0: https://github.com/google-research/bleurt/issues/4#issuecomment-635118502
