### ISSUE TITLE
Annoying Documentation for Tensorflow 2.2.0

### ISSUE THREAD

**Issue by y12uc231** [tensorflow/tensorflow#40283]
I saw the implementations of tf.reduce_mean, tf.reduce_sum but its not there in the documentation for tf 2.2.0. It is really annoying as it created a giant confusion in our code. Please keep documentation and implmentation in sync.

**Comment by nikitamaia** [comment]
Hi @y12uc231 
[tf.reduce_mean](https://www.tensorflow.org/api_docs/python/tf/math/reduce_mean) and [tf.reduce_sum ](https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum)are both included in the documentation. Can you please link to the implementations you are referring to, and provide more information on the discrepancy you are seeing between documentation and implementation? Thank you.

**Comment by y12uc231** [comment]
Hi @nikitamaia  : If you check the links you posted, they are tf.math.reduce_mean not tf.reduce_mean.

**Comment by nikitamaia** [comment]
If you click on the "View aliases" button at the top of the docs, you will see that tf.reduce_sum is an alias for tf.math.reduce_sum, so you can use either.

**Comment by y12uc231** [comment]
Thanks! 
Quick feedback : Based on my personal experience, documentation of tensorflow is incredibly complicated compared any other frameworks I use like pytorch or mxnet.

**Comment by nikitamaia** [comment]
Thanks for the feedback, @y12uc231. If you run into any confusion, or find something in the docs you think would benefit from some clarity, please do file an issue.
