### ISSUE TITLE
 metaclass conflict, ops.py, tensorflow.backend.py

### ISSUE THREAD

**Issue by Kottarashky** [tensorflow/tensorflow#40288]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

Hello people, firstly...im new the last beginner and maybe the mess is big so...
Some days ago i trained YOLOv3 (TrainYourOwnYOLO) everything was fine, however, when i've tried to test the algorithm the things went wrong. Issue after issue. i was looking in forums and after one issue came another one.  The last change was here:

ops.py
core_tf_types.Tensor = tuple()
# Deprecated - do not use.
# This API to avoid breaking estimator and tensorflow-mesh which depend on this
# internal API. The stub should be safe to use after TF 2.3 is released.
def is_dense_tensor_like(t):
  return isinstance(t, core_tf_types.Tensor)

tensorflow_backend.py
from tensorflow.python.types import core as core_tf_types 

def is_tensor(x):
    return isinstance(x, tf_ops.core_tf_types) or tf_ops.is_dense_tensor_like(x)

When i try to run the detector -> Detector.py
Error is:
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

Could give me an advice what to do?!?!

**Comment by amahendrakar** [comment]
@Kottarashky,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!
