### ISSUE TITLE
Mask-RCNN conversion succeeds, but requires select-tf-ops despite selecting only TFLITE_BUILTINS

### ISSUE THREAD

**Issue by jtrammell-dla** [tensorflow/tensorflow#40297]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 18.04
- TensorFlow installed from (source or binary):
tensorflow:2.2.0-gpu-jupyter docker image, so... binary?
- TensorFlow version (or github SHA if from source):
2.2.0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
converter = lite.TFLiteConverter.from_keras_model(model.keras_model)
converter.target_spec.supported_ops = [lite.OpsSet.TFLITE_BUILTINS]
converter.experimental_new_converter = True
converter.allow_custom_ops = False
converter.representative_dataset = [(np.random.random((256,256,3))*255).astype(np.uint8)]
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```

**The output from the converter invocation**

```
256614676
```

**Also, please include a link to the saved model or GraphDef**

```
What is a good way to provide this?
Original model parameters from matterport repo here: https://github.com/matterport/Mask_RCNN/releases/download/v2.0/mask_rcnn_coco.h5
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
The produced tflite model works on my android device, but it requires the tf-select-ops library, and fails to accept the provided GpuDelegate.

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by abattery** [comment]
@jtrammell-dla  Could you share which ops make it require tf-select-ops?

**Comment by jtrammell-dla** [comment]
Thanks for the fast response. Gladly! How do I figure that out?

**Comment by abattery** [comment]
FYI, the GPU delegate supported ops is a subset of TFLite builtin ops and if the given model requires tf ops, which is not supported via TFLite Builtin op, they won't be supported via GPU delegate as well.

You can find the unsupported tf ops in TFLite builtin ops in the failed log when you convert without allowing custom ops and `converter.target_spec.supported_ops = [lite.OpsSet.TFLITE_BUILTINS]`.

**Comment by jtrammell-dla** [comment]
Ugh, my apologies... After a little more digging, it turns out that I had forgotten to actually install the new tflite file on the device. I'm still having problems, but they aren't tf-selec-ops related so I'll post them on a new ticket if I can't work them out. Thanks again for the fast response!

**Comment by bmabir17** [comment]
@jtrammell-dla were you able to convert your model to tflite and run inference on it? I was able to convert it [[code](https://gist.github.com/bmabir17/754a6e0450ec4fd5e25e462af949cde6)] with tensorflow 1.13.1 but the converted model seems to have different node input as described [here](https://github.com/matterport/Mask_RCNN/issues/563#issuecomment-646546709). Would you be kind enough to share how you did this using tensorflow 2.2?

**Comment by jtrammell-dla** [comment]
I started with the matterport repo. I then switched all the keras imports to tf.keras, and then I updated the handful of function calls which no longer exist in TF2.2.0. In every case (and there were only a handful, maybe ten at most) it was a trivial issue of the function call being moved to a new path in TF2.2.0. It did not require generating any new code with one very minor exception, which was that the region proposals needed to have their shape specified so downstream ops would work.

Getting it to work from there in TFLite was a little more complex, and will vary depending on your needs. I'm still in the process of adapting it, but yes, it can be done, with some caveats. It will not run with the TFLite GpuDelegate. It will not run without select-tf-ops. I've re-written the only function (tf.image.crop_and_resize) which actually requires the additional AAR, using TFLite supported code, and it compiles, but it fails with inexplicable "dimension mismatch" errors during inference.

**Comment by bmabir17** [comment]
> using TFLite supported code, and it compiles, but it fails with inexplicable "dimension mismatch" errors during inference.
@jtrammell-dla yeah, i am also stuck in there. it seems the converted model was not converted properly.

Please refer to this [comment](https://github.com/tensorflow/tensorflow/issues/39179#issuecomment-646544647)

**Comment by jtrammell-dla** [comment]
I suggest giving up on a full-on native TFLite implementation, and just stick with tf.image.crop_and_resize, and add tensorflow-lite-select-tf-ops to your build.

**Comment by danielsernabuitrago** [comment]
> I suggest giving up on a full-on native TFLite implementation, and just stick with tf.image.crop_and_resize, and add tensorflow-lite-select-tf-ops to your build.

@jtrammell-dla  how can you do that ?

**Comment by jtrammell-dla** [comment]
> > I suggest giving up on a full-on native TFLite implementation, and just stick with tf.image.crop_and_resize, and add tensorflow-lite-select-tf-ops to your build.
> 
> @jtrammell-dla how can you do that ?

This guide here discusses including select-tf-ops:

https://www.tensorflow.org/lite/guide/ops_select

**Comment by danielsernabuitrago** [comment]
thanks @jtrammell-dla, will try it...

**Comment by danielsernabuitrago** [comment]
@jtrammell-dla thanks a lot, it worked !! I converted it and called it:

interpreter = tf.lite.Interpreter(model_path="../../logs/mask-rcnn-model2.tflite")
INFO: Initialized TensorFlow Lite runtime.

where before got the error 
ValueError: Didn't find custom op for name 'CropAndResize' with version 1

now I'm trying to continue with the inference which I'm trying to do in python to check if everything is fine... now I call:

interpreter.allocate_tensors() 

and get:

RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you invoke the Flex delegate before inference.Node number 276 (Flex) failed to prepare.

I'm following these instructions: https://www.tensorflow.org/lite/guide/inference, can you tell me if I have to do something different or maybe other link with other instructions, I'm sorry but this is my first time trying to use tflite. If you could I would greatly appreciate it.

**Comment by jtrammell-dla** [comment]
Yeah, unfortunately you have to deploy it to a mobile device to test it out. Only native TFLITE ops are supported by the Python implementation of Interpreter.

**Comment by jtrammell-dla** [comment]
Or, more specifically, it seems that the SELECT ops have support in the nightly build of the Python implementation, so if you are willing to go down that road, it might work for you...

https://www.tensorflow.org/lite/guide/ops_select

**Comment by danielsernabuitrago** [comment]
ok, thanks a lot @jtrammell-dla, will check it out.
