### ISSUE TITLE
Decoding output of object detection mobile_ssd_v2_float_coco.tflite 

### ISSUE THREAD

**Issue by sumeshpandit** [tensorflow/tensorflow#40298]
The official documentation suggests mobile_ssd_v2_float_coco.tflite model for enabling GPU delegate, but after analyzing the Model with Netron, ( visualization tool to help identify how the output tensors differ.)
mobile_ssd_v2_float_coco.tflite
OUTPUT:
raw_outputs/box_encodings
id: raw_outputs/box_encodings
type: float32[1,2034,4]
raw_outputs/class_predictions
id: raw_outputs/class_predictions
type: float32[1,2034,91]

Whereas the default model detect.tflite used in the demo has 4 different parameters.
OUTPUT:
TFLite_Detection_PostProcess
id: TFLite_Detection_PostProcess
type: float32
TFLite_Detection_PostProcess:1
id: TFLite_Detection_PostProcess:1
type: float32
TFLite_Detection_PostProcess:2
id: TFLite_Detection_PostProcess:2
type: float32
TFLite_Detection_PostProcess:3
id: TFLite_Detection_PostProcess:3
type: float32
ie for Location, Classes, Scores, Number and detections

How can we use mobile_ssd_v2_float_coco.tfliteor any model to get enable GPU with Object Detection, Please suggest?

**Comment by kozyrevsergey89** [comment]
any updates on this?

**Comment by kozyrevsergey89** [comment]
As I can see, if when we use outputs provided by this model, we are getting float32[1,2034,91] for class_predictions. 
As far as I understand, it stands for 2034 as number of recognitions, followed by 91 coco classes (with 0 corresponding to background class).
Any chance we can use another model with GPU , preferably one that uses hot-encoding, meaning just shows you recognition class, confidence and location box?

**Comment by sushreebarsa** [comment]
@sumeshpandit Could you please let us know if this is still an issue ? Thank you!

**Comment by sumeshpandit** [comment]
> @sumeshpandit Could you please let us know if this is still an issue ? Thank you!

yes

**Comment by hardikdava** [comment]
Hello, is there any update on this issue? I have the same question. How to get prediction bounding box, classes and score from 'raw_outputs/box_encodings' and 'raw_outputs/class_predictions'?

**Comment by mohantym** [comment]
Hi @sumeshpandit ! you can use [visualization_utils](https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/tf2_object_detection.ipynb#scrollTo=IZ5VYaBoeeFM&line=4&uniqifier=1)  from object_detection.utils to visualize the identified objects in the image based on boundary boxes and key-points detected from the output of the model . To  enable GPU delegate , You can refer to this [codelab](https://developer.android.com/codelabs/recognize-flowers-with-tensorflow-on-android#8) .Thanks!

**Comment by elize-anu** [comment]
> Hello, is there any update on this issue? I have the same question. How to get prediction bounding box, classes and score from 'raw_outputs/box_encodings' and 'raw_outputs/class_predictions'?

Did you able to resolve this issue? I'm facing the same issue, please help
