### ISSUE TITLE
ptb language modeling example broken with --use_fp16 and dropout other than 0

### ISSUE THREAD

**Issue by nryant** [tensorflow/tensorflow#4029]
### Environment info
Operating System: Ubuntu 16.04 LTS
GPU: GTX 1080
Nvidia driver: 370.23
CUDA: 8.0
cuDNN: 5
bazel: 

    Build label: 0.3.1- (@non-git)
    Build target: bazel-out/local- fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
    Build time: Wed Aug 24 00:13:09 2016 (1471997589)
    Build timestamp: 1471997589
    Build timestamp as int: 1471997589

git commit hash: cc3153a7a0a23533d14ead34db37e4ccd7892079

### Description
When run using the ``--use_fp16`` flag and either ``--model medium`` or ``--model large``, the PTB language model example fails:

    Traceback (most recent call last):
      File "ptb_word_lm.py", line 339, in <module>
        tf.app.run()
      File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
        sys.exit(main(sys.argv))
      File "ptb_word_lm.py", line 316, in main
        m = PTBModel(is_training=True, config=config)
      File "ptb_word_lm.py", line 117, in __init__
        inputs = tf.nn.dropout(inputs, config.keep_prob)
      File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1121, in dropout
        if tensor_util.constant_value(keep_prob) == 1:
      File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 634, in constant_value
        ret = _ConstantValue(tensor)
      File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 549, in _ConstantValue
        return MakeNdarray(tensor.op.get_attr("value"))
      File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 517, in MakeNdarray
        raise TypeError("Unsupported tensor type: %s" % tensor.dtype)
    TypeError: Unsupported tensor type: 19

Modifying the model configs so that keep probability is 1 eliminates the problem, while any value other than 1 results in a call to ``tf.nn.dropout`` and, in turn, a call to ``tensor_util.constant_value``, which results in a ``TypeError``.

### What have you tried?
I have another machine running Ubuntu 14.04, CUDA 7.5, and a slightly older version of TensorFlow that does not have this issue. Details for this other set up:

Operating System: Ubuntu 14.04 LTS
GPU: Titan X
Nvidia driver: 352.39 
CUDA: 7.5
cuDNN: 5
bazel: 

    Build label: 0.3.0-2016-07-25 (@e671d29)
    Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
    Build time: Mon Jul 25 17:47:58 2016 (1469468878)
    Build timestamp: 1469468878
    Build timestamp as int: 1469468878

git commit hash: 27eeb441bad8bcaa1bcba42a4b4ee49fb50ea0d3

**Comment by rieram** [comment]
Yea, I got this error awhile back and I had to modify MakeNdarray in /tensorflow/python/framework/tensor_util.py to support float16 in the if/elseif block. I added a case for float16 and it seems to work.

 elif tensor_dtype == dtypes.float16:
    if len(tensor.half_val) == 1:
      return np.repeat(np.array(tensor.half_val[0], dtype=dtype),
                       num_elements).reshape(shape)
    else:
      return np.fromiter(tensor.half_val, dtype=dtype).reshape(shape)

Hope this helps.

**Comment by okuchaiev** [comment]
Got this same problem and solution proposed by @rieram seems to work correctly

**Comment by benoitsteiner** [comment]
I've added support for 16 bit float to the MakeNdarray function in https://github.com/tensorflow/tensorflow/commit/b0e27a3700b4f729fdc91efe96ad0dbfcab48fc1: I'm closing the issue.

**Comment by okuchaiev** [comment]
Thanks @benoitsteiner. It would be nice to actually have support for float16 in actual matrix operations and kernels. See for example: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/cuda/cuda_blas.cc#L1683   
Right now it actually converts float16 to float32 instead of using Hgemm. This a different issue though.
