### ISSUE TITLE
AutoGraph could not transform

### ISSUE THREAD

**Issue by PeterMitrano** [tensorflow/tensorflow#40301]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: 2080TI 11gb

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
The following warning is printed
```
WARNING:tensorflow:AutoGraph could not transform <function parse_dataset.<locals>._parse at 0x7f3d8c126cb0> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 3, expecting 4
```
**Describe the expected behavior**
No warning

**Standalone code to reproduce the issue**

```
import tensorflow as tf


def bytes_feature(value):
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))


def float_tensor_to_bytes_feature(value):
    return bytes_feature(tf.io.serialize_tensor(tf.convert_to_tensor(value, dtype=tf.float32)).numpy())


def parse_dataset(dataset, feature_description, n_parallel_calls=None):
    def _parse(example_proto):
        deserialized_dict = tf.io.parse_single_example(example_proto, feature_description)
        return deserialized_dict

    parsed_dataset = dataset.map(_parse, num_parallel_calls=n_parallel_calls)
    return parsed_dataset


v = [1, 2, 3]

features = {
    'x': float_tensor_to_bytes_feature(v)
}

example_proto = tf.train.Example(features=tf.train.Features(feature=features))
example = example_proto.SerializeToString()
serialized_tensors = [example]

dataset = tf.data.Dataset.from_tensor_slices(serialized_tensors)

features_description = {
    'x': tf.io.FixedLenFeature([], tf.string),
}
parsed_dataset = parse_dataset(dataset, features_description)

print(next(iter(parsed_dataset)))

```

**Comment by ravikyram** [comment]
@PeterMitrano 

I tried in colab with TF 2.1, 2.2 and nightly versions and i am not seeing any warning message.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/3a75853c7c6841a4c8ad07afdb4206f9/untitled969.ipynb).Please, verify the issue and close the issue if you feel issue was resolved. Thanks!

**Comment by PeterMitrano** [comment]
small mistake -- I'm actually using CUDA 10.2
I also have `TF_CPP_MIN_LOG_LEVEL=3` in my environment. I also have `gast==0.3.3` instead of `gast==0.2.2` which I see from your colab notebook. perhaps one of these differences explains it?

**Comment by PeterMitrano** [comment]
yes, downgrading gast to `0.2.2` fixes the problem. Not sure how my environment got this way.
