### ISSUE TITLE
cuda8.0 cudnn5 binary release?

### ISSUE THREAD

**Issue by elvinpoon** [tensorflow/tensorflow#4030]
I've encountered lots of build errors and none of the solutions I found online can solve my problems. I'm just wondering when can you offer binary release for cuda 8.0 and cuDNN5? I think it's very important for those who don't want to get their hands dirty on building issues.

**Comment by akors** [comment]
While a binary release with the updated libraries is certainly desirable, I might be able to help you with build instructions (or even prebuilt pip-packages for Ubuntu).

If you want, you can create a new StackOverflow question with the `tensorflow` tag, and post the link here so I can have a look.
Please include the following info:
 - Operating System
 - CUDA version
 - cuDNN version
 - How you installed CUDA
 - Available compilers on your system

**Comment by elvinpoon** [comment]
I'm using ubuntu 16.04 LTS & GTX1080, with CUDA-8.0 and cuDNN-5.105 installed, I've downgrade gcc to gcc-5.3.0. I also have installed gcc-4.9 as backup choice.
The first time I got this error.
![image](https://cloud.githubusercontent.com/assets/19640630/17969359/4b950658-6b04-11e6-8845-66510656fbec.png)
However,  It returns '/usr/as' when I type 'which as' in command line. I'm tried symlinks which doesn't work. Me and my friend are guessing that it could be due to that we downgrade our complier and we still haven't figured out how to solve it.
I've tried adding cxx_buildin_include_directory and another problem

And I tried cloning the the master branch and building on the second shot. Still haven't figured out what happened.
![image](https://cloud.githubusercontent.com/assets/19640630/17969570/507a9c9a-6b05-11e6-9ed4-a26f8f2451ee.png)

I'm having a third  kind of error message now and I will paste it later...

**Comment by elvinpoon** [comment]
Now I have
> ERROR: missing input file '@local_config_cuda//cuda:include/curand_discrete.h'.
ERROR: /home/pcy/.cache/bazel/_bazel_pcy/cca4539ff6237551fb9a5b20d456f78c/external/farmhash_archive/BUILD:5:1: Executing genrule @farmhash_archive//:configure failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 15.
/home/pcy/.cache/bazel/_bazel_pcy/cca4539ff6237551fb9a5b20d456f78c/tensorflow/external/farmhash_archive/farmhash-34c13ddfab0e35422f4c3979f360635a8c050260 /home/pcy/.cache/bazel/_bazel_pcy/cca4539ff6237551fb9a5b20d456f78c/tensorflow
/tmp/tmp.wqQFr9f1IO /home/pcy/.cache/bazel/_bazel_pcy/cca4539ff6237551fb9a5b20d456f78c/tensorflow/external/farmhash_archive/farmhash-34c13ddfab0e35422f4c3979f360635a8c050260 /home/pcy/.cache/bazel/_bazel_pcy/cca4539ff6237551fb9a5b20d456f78c/tensorflow
ERROR: /home/pcy/tensorflow/tensorflow/python/BUILD:1101:1: //tensorflow/python:_pywrap_tensorflow.so: missing input file '@local_config_cuda//cuda:include/curand_discrete.h'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/pcy/tensorflow/tensorflow/python/BUILD:1101:1 1 input file(s) do not exist.
INFO: Elapsed time: 1.085s, Critical Path: 0.02s
pcy@BJSH-DATAGPU-134-200:~/tensorflow$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --verbose_failures
ERROR: Loading of target '@local_config_cuda//crosstool:crosstool' failed; build aborted: no such package '@local_config_cuda//crosstool': BUILD file not found on package path.
ERROR: Loading failed; build aborted.

**Comment by akors** [comment]
@elvinpoon I answered to your question on StackOverflow, on the missing "as" issue.

The last error, the "no such package" thing seems to be a new thing that has been introduced recently: you can only build *once* after configuring. If you run into errors, you have to actually repeat the configure step. I don't quite know why.

In case you don't want to go through the trouble, here's my last TF build for my machine:

https://dl.dropboxusercontent.com/u/1414175/tf/tensorflow_gpu_cuda8_cdnn5.1-0.10.0rc0-6d04d60-py3-none-any.whl

To install, you have to rename it (or symlink) to `tensorflow-0.10.0rc0-py3-none-any.whl`, otherwise pip installation will fail.

It's a few days old, but still more or less up to date.

**Comment by elvinpoon** [comment]
Hi I'm working on what you've suggested. Btw, do you have TF build for python2.7?

**Comment by akors** [comment]
Am 29. August 2016 03:26:01 MESZ, schrieb elvinpoon <notifications@github.com>:
>Hi I'm working on what you've suggested. Btw, do you have TF build for
>python2.7?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tensorflow/tensorflow/issues/4030#issuecomment-243013130

Nope, I only use Python 3

**Comment by StrangeTcy** [comment]
After having experienced similar issues with `bazel build`ing for several frustrating days, I've decided to look for already existing wheels too; so thanks for those.

**Comment by caisq** [comment]
The Mac GPU pip wheels of the latest release (0.12.0) are built with CUDA 8.0and CUDNN 5.1. 

See: https://www.tensorflow.org/get_started/os_setup

# Mac OS X, GPU enabled, Python 2.7:
$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow_gpu-0.12.0-py2-none-any.whl

# Mac OS X, GPU enabled, Python 3.4 or 3.5:
$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow_gpu-0.12.0-py3-none-any.whl

# Python 2
$ sudo pip install --upgrade $TF_BINARY_URL

# Python 3
$ sudo pip3 install --upgrade $TF_BINARY_URL

**Comment by StrangeTcy** [comment]
The link @caisq provided ( [tensorflow install]( https://www.tensorflow.org/get_started/os_setup) now has instructions on installing binaries, so I think the issues is resolved and thus should be closed.
