### ISSUE TITLE
TypeError: Expected int64, got 1e-07 of type 'float' instead : FasterRCNN tensorflow 2.x

### ISSUE THREAD

**Issue by ghnreigns** [tensorflow/tensorflow#40308]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linus Ubuntu 18.04.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip install tensorflow==2.1.0
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: GTX1650

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Parsing annotation files
Training images per class:
{'Platelets': 234, 'RBC': 2606, 'WBC': 231, 'bg': 0}
Num classes (including bg) = 4
Config has been written to config.pickle, and can be loaded when testing to ensure correct results
Num train samples 193
Num val samples 31
loading weights from pretrain/vgg16_weights_tf_dim_ordering_tf_kernels.h5
Could not load pretrained model weights. Weights can be found in the keras application folder           https://github.com/fchollet/keras/tree/master/keras/applications
no previous model was loaded
Starting training
Epoch 1/50
Exception: in converted code:

/home/reighns/ObjectDetection/blood_cells_detection/keras-frcnn-ken/fasterrcnn/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_eager.py:305 train_on_batch  *
    outs, total_loss, output_losses, masks = (
/home/reighns/ObjectDetection/blood_cells_detection/keras-frcnn-ken/fasterrcnn/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_eager.py:253 _process_single_batch
    training=training))
/home/reighns/ObjectDetection/blood_cells_detection/keras-frcnn-ken/fasterrcnn/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_eager.py:167 _model_loss
    per_sample_losses = loss_fn.call(targets[i], outs[i])
/home/reighns/ObjectDetection/blood_cells_detection/keras-frcnn-ken/fasterrcnn/lib/python3.6/site-packages/tensorflow_core/python/keras/losses.py:221 call
    return self.fn(y_true, y_pred, **self._fn_kwargs)
/home/reighns/ObjectDetection/blood_cells_detection/keras-frcnn-ken/keras_frcnn/losses.py:42 rpn_loss_cls_fixed_num
    return lambda_rpn_class * K.sum(y_true[:, :, :, :num_anchors] * tf.keras.losses.binary_crossentropy(y_pred[:, :, :, :], y_true[:, :, :, num_anchors:])) / K.sum(epsilon + y_true[:, :, :, :num_anchors])
/home/reighns/ObjectDetection/blood_cells_detection/keras-frcnn-ken/fasterrcnn/lib/python3.6/site-packages/tensorflow_core/python/keras/losses.py:994 binary_crossentropy
    K.binary_crossentropy(y_true, y_pred, from_logits=from_logits), axis=-1)
/home/reighns/ObjectDetection/blood_cells_detection/keras-frcnn-ken/fasterrcnn/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py:4602 binary_crossentropy
    epsilon_ = _constant_to_tensor(epsilon(), output.dtype.base_dtype)
/home/reighns/ObjectDetection/blood_cells_detection/keras-frcnn-ken/fasterrcnn/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py:678 _constant_to_tensor
    return constant_op.constant(x, dtype=dtype)
/home/reighns/ObjectDetection/blood_cells_detection/keras-frcnn-ken/fasterrcnn/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py:258 constant
    allow_broadcast=True)
/home/reighns/ObjectDetection/blood_cells_detection/keras-frcnn-ken/fasterrcnn/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py:297 _constant_impl
    allow_broadcast=allow_broadcast))
/home/reighns/ObjectDetection/blood_cells_detection/keras-frcnn-ken/fasterrcnn/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_util.py:452 make_tensor_proto
    _AssertCompatible(values, dtype)
/home/reighns/ObjectDetection/blood_cells_detection/keras-frcnn-ken/fasterrcnn/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_util.py:332 _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))

TypeError: Expected int64, got 1e-07 of type 'float' instead.

**Describe the expected behavior**
Expected to train a faster rcnn model using https://github.com/kentaroy47/frcnn-from-scratch-with-keras repo; I want to use the code in tf2.x version but encounter this error. The error might be related to the loss function py file.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@ghnreigns 
Please refer to this [comment](https://github.com/tensorflow/tensorflow/issues/33855#issuecomment-572176122) on similar issue and let us know if it helps, else share a simple stand alone code for us to replicate the issue faced or a colab gist with the error.

**Comment by ghnreigns** [comment]
@Saduf2019 Let me try it, thanks
