### ISSUE TITLE
None Type not Supported

### ISSUE THREAD

**Issue by purva98** [tensorflow/tensorflow#40306]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): 
- TensorFlow version (or github SHA if from source): 1.14

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
# Copy and paste here the exact command
```

**The output from the converter invocation**

```
# Copy and paste the output here.
```

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs*

Hi, when I trying to convert a .pb file to a .tflite model, my input tensor is of shape [None, None,None,4] . I am getting the None Type not supported error. 
How ever if I replace it with integer values like, [200,200,200,4] it works. 
How should I include the None Type support while convert .pb file to a .tflite file?

**Comment by amahendrakar** [comment]
@purva98,
Could you please provide the complete code to reproduce the issue reported here or the `.pb` file you are trying to convert. 

Also, please upgrade to TF 2.x as TF 1.x is not actively supported. Thanks!

**Comment by hegman12** [comment]
I believe the stable release of tensorflow do not support None type in input. Use nightly, this support has been added recently. I was able to convert he graphs successfully that has None shape tensors.

**Comment by purva98** [comment]
@hegman12, can you please share a small script or snippet of your code, it would be a great help!
Thanks

**Comment by ElPapi42** [comment]
check this issue #40185

**Comment by amahendrakar** [comment]
> @purva98,
> Could you please provide the complete code to reproduce the issue reported here or the `.pb` file you are trying to convert.
> 
> Also, please upgrade to TF 2.x as TF 1.x is not actively supported. Thanks!

@purva98,
Any updates regarding this issue? Thanks!

**Comment by p98-ai** [comment]
Yes the issue was resolved using tf-nightly version of tensorflow

**Comment by purva98** [comment]
Yes @amahendrakar , the issue was resolved by using the tf-nightly version of tensorflow.
