### ISSUE TITLE
Cannot register 2 metrics with the same name Error

### ISSUE THREAD

**Issue by Kmarconi** [tensorflow/tensorflow#40316]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): JetPack 4.3 (Ubuntu 18.04) 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):1.15.2
- Python version:3.6.9
- Bazel version (if compiling from source):0.26.1
- GCC/Compiler version (if compiling from source):7.5.0
- CUDA/cuDNN version:10.0/7.6.3
- GPU model and memory:Jetson AGX Xavier (GPU Volta)

**Describe the current behavior**
I'm trying to create an executable of my code (C++) which is using opencv and tensorflow. For this, I have to use autotools which is a tool used to create Makefiles. I'm successfully making my executable but I'm trying to use it I always have this error : 

`2020-06-09 14:02:25.158088: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/cc/saved_model/load_attempt_count
2020-06-09 14:02:25.158383: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/cc/saved_model/load_latency
2020-06-09 14:02:25.158467: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/cc/saved_model/load_latency_by_stage
2020-06-09 14:02:25.159111: F tensorflow/core/framework/variant_op_registry.cc:53] Check failed: existing == nullptr (0x55a3931838 vs. nullptr)Unary VariantDecodeFn for type_name: tensorflow::data::WrappedDatasetVariant already registered
Aborted (core dumped)
`

I do not really understand why,because I have included the required tensorflow flags in my configuration as you can see below : 

AM_LDFLAGS = -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_videoio -ltensorflow_cc -ltensorflow_framework -lprotobuf -lprotoc

Any help would be much appreciated, thanks !

**Comment by ravikyram** [comment]
@Kmarconi 

Request you to share related code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by Kmarconi** [comment]
Hi, thanks for your quick reply. I'm working on some object detection and my code is exactly the same as the one here : https://github.com/lysukhin/tensorflow-object-detection-cpp (I'm trying to compile the main.cpp file and to use the utils.h as a shared librarie).

**Comment by Kmarconi** [comment]
Hi, just to save you some time for other issues, I wanted to let know that I've solved my issue this morning. It was coming from my tensorflow-cpp installation, I was using the wrong flags ( probably the monolitic one which is bad for the Jetson Xavier). For my new installation, I've used the nonccl flag and the noaws flag. Everything is working perfectly now.

**Comment by JaydenTaojy** [comment]
> Hi, just to save you some time for other issues, I wanted to let know that I've solved my issue this morning. It was coming from my tensorflow-cpp installation, I was using the wrong flags ( probably the monolitic one which is bad for the Jetson Xavier). For my new installation, I've used the nonccl flag and the noaws flag. Everything is working perfectly now.

Hello, could you provide the detail of your configuration? I faced the same issue on Jetson
