### ISSUE TITLE
Can I inference models with XNNPACK backend through tensorflow lite Python APIs?

### ISSUE THREAD

**Issue by vippeterhou** [tensorflow/tensorflow#40313]
One of my areas is model compression for deployment. Previously, I worked on QNNPACK and its performance was amazing. I knew that the main author of QNNPACK went to Google from FB, and he continues his work based on QNNPACK. A new library named XNNPACK was created. I am very excited to see the Sparse ConvNets feature of XNNPACK. XNNPACK suggests the TensorFlow lite in its readme. However, I did not find a specific doc or APIs for this feature. **So, can you provide some examples of the usage of XNNAPCK?**

**Specifically, I want to inference the models with XNNPACK backend on CPU no matter what platform I am. Like QNNPACK, I can do some experiments on x86, while I can run on Arm (such as NVIDIA Xavier, TX2, etc) when I want to deploy models.**

**For your reference**, you may learn something from PyTorch quantization feature, by which I can use same APIs to invoke QNNPACK backend on different platforms (x86 or Arm).

**Comment by jdduke** [comment]
This isn't yet possible, but we plan on enabling XNNPACK by default in the near future, so you shouldn't need to do anything explicitly on your end.

**Comment by vk1z** [comment]
@jdduke Is there a way to invoke xnnpack through load_delegate()? Namely, what shared lib should be pointed to and how do we build it, if required. I'd built from master with the tflite_with_xnnpack flag.

**Comment by jdduke** [comment]
If you build with the `--define tflite_with_xnnpack=true` flag, then you shouldn't have to do anything manually. The delegate should be applied by default.

**Comment by arturdryomov** [comment]
@jdduke, hey, it’s been a year — what’s the current status of the delegate? Is it enabled by default or still requires building? 

Also — is it possible to see TF logs while executing a TF Lite model via the Python API? I see a silent output while executing so I’m not sure what’s going on under the hood.

**Comment by jdduke** [comment]
I'll let @srjoglekar246 and @multiverse-tf provide an update.

**Comment by SamSamhuns** [comment]
Just checked, it still requires building from src to enable XNNPACK

**Comment by mohantym** [comment]
Hi @vippeterhou !
We can build and run XNNPack delegates for  Desktops now with x86/x86_64 flag now.
#Build command with different architecture
```
bazel build -c opt --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a \
  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
  --define tflite_with_xnnpack=true \
  //tensorflow/lite/java:tensorflow-lite

```
TensorFlow Lite interpreter will use the XNNPACK backend by default in Desktops.

For detailed usage , Please check official documentation on [XNNPack.](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/xnnpack/README.md)

Thank you!
