### ISSUE TITLE
cant import tensorflow.contrib.tensorrt

### ISSUE THREAD

**Issue by glennford49** [tensorflow/tensorflow#40314]
is there any way to import contrib.tensorrt in tensorflow 2.2.0?

**Comment by Saduf2019** [comment]
@glennford49 
Please refer to this [comment](https://github.com/tensorflow/tensorflow/issues/31350#issuecomment-566151053) and downgrade to 1.x version to use tensorflow contrib. and let us know if we can move this issue to resolved status.

**Comment by glennford49** [comment]
I've already fix this... tensorrt has been moved to core in version 2.x

**Comment by Saduf2019** [comment]
@glennford49 
Please confirm if we may move this issue resolved status.
