### ISSUE TITLE
Using a FCN in a for loop

### ISSUE THREAD

**Issue by Antonio-git-lab** [tensorflow/tensorflow#40312]
Hello,
I have a question, if I want to create a Fully Connected Network and I would like to place it in a for loop, I want to tell Tensorflow that the weights of my FCN are shared between all iterations of this for loop, and prevent the creation of "N" instances of different FCNs.
What should I do in this case?

**Comment by amahendrakar** [comment]
@Antonio-git-lab,
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there. Thanks!
