### ISSUE TITLE
[TF Lite C API]  Zero outputs

### ISSUE THREAD

**Issue by andreydung** [tensorflow/tensorflow#40318]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: SnapDragon 645, Android 10
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v2.2.0
- Python version: 2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 10.2
- GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I'm inferencing the same model in C++ API (using libtensorflowlite.so) and C API (using libtensorflowlite_c.so) on Android NDK r18b. While the C++ code works well and passed test cases, the C version output all zeros.

**Describe the expected behavior**

Output from C and C++ version should be exactly the same.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
void forward(const float* real, const float* imag, float* pout) {
    TfLiteInterpreterAllocateTensors(interpreter);
    TfLiteTensor* tflite_real = TfLiteInterpreterGetInputTensor(interpreter, 0);
    TfLiteTensor* tflite_imag = TfLiteInterpreterGetInputTensor(interpreter, 1);
    TfLiteTensorCopyFromBuffer(tflite_real, real, N1 * sizeof(float));
    TfLiteTensorCopyFromBuffer(tflite_imag, imag, N2 * sizeof(float));

    TfLiteInterpreterInvoke(interpreter);
    const TfLiteTensor* out = TfLiteInterpreterGetOutputTensor(interpreter, 0);
    TfLiteTensorCopyToBuffer(out, pout, N_OUT * sizeof(float));
}
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by jdduke** [comment]
Just to confirm, you built the libtensorflowlite.so and libtensorflowlite_c.so from source using NDK r18b? Is the client code that uses these libs also built using NDK r18b?

You might also try inspecting the TfLiteTensor* values directly (see also the TfLiteTensor definition in `lite/c/common.h`) to see if there's an issues with the memcpy behavior.

**Comment by andreydung** [comment]
Hi @jdduke: Yes, I built both `libtensorflowlite.so` and `libtensorflowlite_c.so` using NDK r18b. Client code is using NDK r18b as well.

We were able to inference all other models. Only with this specific model that it keeps returning zero, even though input is not zeros.

If it helps for debugging, here is the link to the model:
https://drive.google.com/file/d/1ZoRjTupSMHydsbGy4cWDLIuZD7LnybsA/view?usp=sharing

**Comment by jdduke** [comment]
Can you confirm what sizes you're using for N1, N2 and N_OUT? And whether you did an explicit resize? It would be helpful to have some reference input values as well, if possible. Also, can you confirm that the entire output was zero? Thanks again.

**Comment by jdduke** [comment]
I created a local test feeding random/fixed float values to the inputs, and I get identical (non-zeroed) outputs using the C and C++ APIs for that model. I wouldn't think that this is 2.2-specific, but you might try also building from head to see if that resolves the issue?

**Comment by andreydung** [comment]
Thanks @jdduke let me retry the code.

**Comment by andreydung** [comment]
@jdduke Problem resolved, it's exactly due to memcpy and I set the wrong number of elements.
