### ISSUE TITLE
Options for tflite_convert

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#40319]
Hello guys,

I'd like to find out all options available for `tflite_convert` and since I use `--help` I got

```
(tf-cpu):~$ tflite_convert --help
usage: tflite_convert [-h] --output_file OUTPUT_FILE
                      [--saved_model_dir SAVED_MODEL_DIR | --keras_model_file KERAS_MODEL_FILE]
                      [--enable_v1_converter]
                      [--experimental_new_converter [EXPERIMENTAL_NEW_CONVERTER]]

Command line tool to run TensorFlow Lite Converter.

optional arguments:
  -h, --help            show this help message and exit
  --output_file OUTPUT_FILE
                        Full filepath of the output file.
  --saved_model_dir SAVED_MODEL_DIR
                        Full path of the directory containing the SavedModel.
  --keras_model_file KERAS_MODEL_FILE
                        Full filepath of HDF5 file containing tf.Keras model.
  --enable_v1_converter
                        Enables the TensorFlow V1 converter in 2.0
  --experimental_new_converter [EXPERIMENTAL_NEW_CONVERTER]
                        Experimental flag, subject to change. Enables MLIR-
                        based conversion instead of TOCO conversion.

``` 

I see there are more options available such as ` --inference_type` `--std_dev_values` I'd like to know those and their respective parameters.

**Comment by amahendrakar** [comment]
@peter197321,
Please check [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/r1/convert/cmdline_reference.md) command line reference page for the converter and let us know if it helps. Thanks!

**Comment by peter197321** [comment]
You declare the `--enable_v1_converter` flag I can't see it that reference page ...

**Comment by amahendrakar** [comment]
@peter197321,
As per [this documentation](https://www.tensorflow.org/lite/convert/cmdline#usage), setting `--enable_v1_converter` as `True`, enables the 1.X command line flags instead of the 2.X flags.

**Comment by peter197321** [comment]
per [quantization_config.h](https://github.com/tensorflow/tensorflow/blob/8ab1c251ed27950b850cbc106bbe9a798b16b79a/tensorflow/compiler/mlir/lite/quantization/quantization_config.h#L53) there are other possible flags which I am looking for to set e.g. 

```
  // When set to true, quantization will be done per-tensor. Currently, this
  // option is only valid when the quantization parameters need to be created by
  // scanning the constant content (post-training quantization or QAT without
  // weight FakeQuant).
  bool disable_per_channel = false;
```
is it possible to use those within `tflite_convert` call? If so please can you have some code snippet how to use?

**Comment by sachinprasadhs** [comment]
You can find the details of all options and the parameters of the methods in the source code of tflite_convert [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/tflite_convert.py).
You can also refer the high level details from the documentation [here](https://www.tensorflow.org/lite/convert). Thanks!
