### ISSUE TITLE
[TF Lite] GPU delegates for windows

### ISSUE THREAD

**Issue by emepetres** [tensorflow/tensorflow#40325]
Hi, I'm trying to run tf lite on windows with gpu support, so I can run inference on a windows desktop app as fast as possible without relying on CUDA (users may not have a nvidia graphics card or cuda installed)

Is there a way to compile/use the gpu delegates on windows?

This is related to #28830

**System information**
- OS Platform and Distribution: Windows 10 x64
- TensorFlow installed from: source
- TensorFlow version: v2.2.0
- Python version: 3.6
- Installed using conda
- Bazel version: 2.0.0
- GCC/Compiler version: Visual Studio 2019

**Describe the problem**

I cannot TF Lite with GPU support on windows. I compiled the tf lite c api, but it does not provide gpu delegates. I've tried to compile some sort of dll from //tensorflow/lite/delegates/gpu, but no luck.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
`bazel build //tensorflow/lite/c:tensorflowlite_c.dll -c opt`

Trying to compile the delegates:
`bazel build -c opt --copt -Os --copt -DTFLITE_GPU_BINARY_RELEASE --copt --linkopt -s --strip always //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so`
`bazel build //tensorflow/lite/delegates/gpu:api -c opt`

**Any other info / logs**
```
bazel build -c opt --copt -Os --copt -DTFLITE_GPU_BINARY_RELEASE
 --copt --linkopt -s --strip always //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so
...
ERROR: Z:/projects/tensorflow/tensorflow/lite/delegates/gpu/cl/BUILD:207:1: C++ compilation of rule '//tensorflow/lite/delegates/gpu/cl:egl_sync' failed (Exit 2)
cl : Command line warning D9002 : ignoring unknown option '--linkopt'
.\tensorflow/lite/delegates/gpu/cl/egl_sync.h(19): fatal error C1083: Cannot open include file: 'EGL/egl.h': No such file or directory
Target //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so failed to build
INFO: Elapsed time: 4.166s, Critical Path: 3.91s
INFO: 31 processes: 31 local.
FAILED: Build did NOT complete successfully
```

```
bazel build //tensorflow/lite/delegates/gpu:api -c opt
...
ERROR: Z:/projects/tensorflow/tensorflow/lite/delegates/gpu/BUILD:196:1: C++ compilation of rule '//tensorflow/lite/delegates/gpu:api' failed (Exit 2)
cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
.\tensorflow/lite/delegates/gpu/gl/portable_gl31.h(21): fatal error C1083: Cannot open include file: 'EGL/egl.h': No such file or directory
Target //tensorflow/lite/delegates/gpu:api failed to build
INFO: Elapsed time: 0.552s, Critical Path: 0.33s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by emepetres** [comment]
Thanks @impjdi , I guess then that the way to go would be to modify the build file to generate a opengl dll based on the android build. Anyway for now I've moved to Onnx+DirectML, which seems the only way nowadays for doing inference in desktop GPU without CUDA.

About OpenCL, indeed I don't have it installed, but as I'm on Windows, I'm trying the OpenGL version. For some reason, in the second try it seems that the build uses OpenCL by default.

**Comment by DBraun** [comment]
If anyone ever gets TF Lite on Windows with GPU support please share your knowledge here!

**Comment by WillLiGitHub** [comment]
# GPU delegate for ubuntu
# 1、install packages
sudo apt-get install mesa-common-dev libegl1-mesa-dev libgles2-mesa-dev mesa-utils
# 2、export .so to system env
echo 'export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libEGL.so /usr/lib/x86_64-linux-gnu/libGLESv2.so"' >> ~/.bashrc
# 3、download tf
git clone -b r2.5 https://github.com/tensorflow/tensorflow.git tensorflow_r2.5
# 4、change source code
cd tensorflow_r2.5
vim tensorflow/lite/delegates/gpu/gl_delegate.h
###### add two functions at line:123
// add to compile desktop gpu delegate with opengles
TFL_CAPI_EXPORT void tflite_plugin_destroy_delegate(TfLiteDelegate* delegate) {
  TfLiteGpuDelegateDelete(delegate);
}

TFL_CAPI_EXPORT TfLiteDelegate* tflite_plugin_create_delegate(const TfLiteGpuDelegateOptions* options) {
  return TfLiteGpuDelegateCreate(options);
}
# 5、build
./configure
bazel build --local_cpu_resources=3 -s -c opt --copt="-DMESA_EGL_NO_X11_HEADERS" --copt="-DEGL_NO_X11" tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_gl.so

then you will get: tensorflow_r2.5/bazel-bin/tensorflow/lite/delegates/gpu/libtensorflowlite_gpu_gl.so
