### ISSUE TITLE
TF2. How to set tf.OptimizerOptions.L0

### ISSUE THREAD

**Issue by cheers00** [tensorflow/tensorflow#40326]
**System information**
- Have I written custom code NO:
- OS Platform and Distribution Linux (Ubuntu 20.04):
- TensorFlow installed from source:
- TensorFlow version (use command below):
- Python version: 3.8.2
- Bazel version 3.0.0:
- GCC/Compiler version gcc (Ubuntu 8.4.0-3ubuntu2) 8.4.0):

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
v1.12.1-32834-g3e842e5ffc 2.2.0

**Describe the current behavior**

Reference: https://github.com/yaroslavvb/stuff/blob/master/matmul_benchmark.py

Script from TF1.14
in my TF1 workload,  I was calling this to avoid optimizing away redundant nodes and it worked.
```
config = tf.ConfigProto(graph_options=tf.GraphOptions(optimizer_options=tf.OptimizerOptions(opt_level=tf.OptimizerOptions.L0)))
sess = tf.Session(config=config)
```

**Describe the expected behavior**
With TF2, I replaced above code with the following and it seems to be not working.  

`tf.compat.v1.OptimizerOptions(opt_level=-1)`

**Comment by ymodak** [comment]
Did you use `compat.v1` modules for other functions as well?
```python
config = tf.compat.v1.ConfigProto(graph_options=tf.compat.v1.GraphOptions(optimizer_options=tf.compat.v1.OptimizerOptions(opt_level=tf.compat.v1.OptimizerOptions.L0)))
sess = tf.compat.v1.Session(config=config)
```

**Comment by cheers00** [comment]
yes.` tf.compat.v1.OptimizerOptions(opt_level=-1)` worked.

Thanks
