### ISSUE TITLE
"The name 'num_detections:0' refers to a Tensor which does not exist. The operation, 'num_detections', does not exist in the graph."

### ISSUE THREAD

**Issue by abdou31** [tensorflow/tensorflow#40322]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on a mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6
- CUDA/cuDNN version:9/7.5
- GPU model and memory: Nvidia Geforce 840m

**Describe the current behaviour**
I have successfully trained and used a face mask detection model based on Keras Yolo project, the model predicts with good accuracy, I have converted the Keras model (.h5 ) to .pb model ( frozen model ) to export the model on the web with Flask.

I'm trying to test the model ( load the pb model ) and predict face mask and face no mask with an image.
 This code that I've used:
```python

import os
import numpy as np
import cv2
import matplotlib.pyplot as plt
import tensorflow as tf
# Provide path to an image for testing
img = cv2.imread("D:\\keras_to_tensorflow\\test_images\\dss.jpg")
img_height, img_width, _ = img.shape
img_cv2 = img[:, :, [2, 1, 0]]
# Load the Model
model_path = "D:\\keras_to_tensorflow\\"
pb_file = os.path.join(model_path, 'face_detect.pb')
# Read the graph.
with tf.gfile.FastGFile(pb_file, 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=1)
with tf.Session(config=tf.ConfigProto(gpu_options=gpu_options)) as sess:
    sess.graph.as_default()
    tf.import_graph_def(graph_def, name='face_detect.pbtxt')

#Include this part with the tensorflow session
#Run the session using the tensors and feed the image to the session
#img_in = cv2.resize(img_cv2, (224, 224))
    img_in = img_cv2[:, :, [2, 1, 0]]  # BGR2RGB
    outputs = sess.run([sess.graph.get_tensor_by_name('num_detections:0'),
             sess.graph.get_tensor_by_name('detection_scores:0'),
             sess.graph.get_tensor_by_name('detection_boxes:0'),
             sess.graph.get_tensor_by_name('detection_classes:0')],
             feed_dict={
                       'input_1:0': img.reshape(1,
                        img.shape[0],
                        img.shape[1],3)})


# Visualize the results
    font = cv2.FONT_HERSHEY_SIMPLEX
    for i in range(num_detections):
        classId = int(outputs[3][0][i])
        print(classId)
        score = float(outputs[1][0][i])
        bbox = [float(v) for v in outputs[2][0][i]]
        if True:
            x = bbox[1] * img_width
            y = bbox[0] * img_height
            right = bbox[3] * img_width
            bottom = bbox[2] * img_height
            cv2.rectangle(img_cv2,
                          (int(x), int(y)),
                          (int(right), int(bottom)),
                          (225, 255, 0),
                          thickness=2)
            cv2.putText(img_cv2,str(class_list[classId-1]),(int(x),int(y)), font, 1, (200,0,0), 3, cv2.LINE_AA)
            print('SCORE:',score, ', Class:',class_list[classId-1], ', BBox:',int(x),int(y),int(right),int(bottom))

```

I got this error :

>KeyError: "The name 'num_detections:0' refers to a Tensor which does not exist. The operation, 'num_detections', does not exist in the graph."

+ Link of the project That I've used: https://github.com/experiencor/keras-yolo3
The problem that I did not have a tensor with this name, 

How can I make this code work perfectly?

**Comment by abdou31** [comment]
I used this version because I find it simple, the error you encounter comes from the version simply, so you must downgrade the version of Tensorflow.

**Comment by abdou31** [comment]
I'm waiting for a solution to my problem.

**Comment by Saduf2019** [comment]
@abdou31 
Please share your code in a colab gist with the error faced so we could analyse it. or else please upgrade the tf version and see if you still face the issue as this is a very old version that does not have support [please use 1.15 or 2.x versions]

Please refer to [this link](https://github.com/tensorflow/tensorflow/issues/40439#issuecomment-644274878).

**Comment by Saduf2019** [comment]
@abdou31
Please update as per above comment.

**Comment by abdou31** [comment]
You should know that this model is a Keras Yolo model.
I don’t have really this tensor in my model.
Those tensors are only presented when if I use Tensorflow object detection API . In this case, I should know what tensors can output the number of detected objects , the number of classes , accuracy...

**Comment by jvishnuvardhan** [comment]
@abdou31 I think. this is more related to the repo from where you are getting the `keras-yolo3`. I noticed, you already posted it in that repo. There are some issues similar to your issue but in TF2.x. Please feel free to check them. Thanks!
