### ISSUE TITLE
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type list).

### ISSUE THREAD

**Issue by neenaloysius** [tensorflow/tensorflow#40331]
Im getting this valueError in colab gpu env with keras tensorflow ver 2.
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type list). on running the following code :
 # ---- CTC ----
    # y_input layers (transcription data) for CTC loss

labels = Input(name='the_labels', shape=[None], dtype=dtype)       # transcription data (batch_size * y_seq_size)
input_length = Input(name='input_length', shape=X_train_length.shape, dtype=dtype)  # unpadded len of all x_sequences in batch
label_length = Input(name='label_length', shape=label_length.shape, dtype=dtype)  # unpadded len of all y_sequences in batch

# Lambda layer with ctc_loss function due to Keras not supporting CTC layers
loss_out = Lambda(function=ctc_lambda_func, name='ctc', output_shape=(1,))([y_pred, np.float32, Y_train, np.float32, X_train_length, np.float32, label_length, np.float32])
network_model = Model(inputs=[input_data, labels, input_length, label_length], outputs=y_pred)

PFA the screenshot for reference.
![code](https://user-images.githubusercontent.com/17008416/84185974-6e035e00-aaad-11ea-9959-c22d7e7b4624.png)

**Comment by ravikyram** [comment]
@neenaloysius 

Request you to share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!
