### ISSUE TITLE
Op not registered 'LSTMBlockCell' in binary running on..

### ISSUE THREAD

**Issue by JesseBerdowski** [tensorflow/tensorflow#40337]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13.1
- Python version: 3.6.7
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 0.20.0
- GCC/Compiler version (if compiling from source): MSVC 2019
- CUDA/cuDNN version: none
- GPU model and memory: none

**Describe the problem**

I exported a .pb model from python. I managed to import this model into Tensorflow C++, but receive the following error message when I add the graph to my session:

"Not found: Op type not registered 'LSTMBlockCell' in binary running on MYDESKTOP. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
Press any key to continue . . ."

**Provide the exact sequence of commands / steps that you executed before running into the problem**

#include "stdafx.h"
#include <stdio.h>

#include "tensorflow/core/public/session.h"
#include "tensorflow/core/platform/env.h"

using namespace tensorflow;

int main(int argc, char* argv[]) {
  // Initialize a tensorflow session
  Session* session;
  Status status = NewSession(SessionOptions(), &session);
  if (!status.ok()) {
    std::cout << status.ToString() << "\n";
    return 1;
  }

  GraphDef graph_def;
  status = ReadBinaryProto(Env::Default(), "C:\\Users\\workaccount\\Documents\\werk\\hexachord\\pycharm\\magenta\\frozen_test.pb", &graph_def);
  if (status.ok()) {
    std::cout << status.ToString() << "\n";
  }

  // Add the graph to the session
  status = session->Create(graph_def);
  if (!status.ok()) {
    std::cout << status.ToString() << "\n";
	system("pause");
  }
}

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

thank you kindly for your response

**Comment by gowthamkpr** [comment]
@JesseBerdowski Is this issue resolved?

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 2 weeks. Please add additional comments for us to open this issue again. Thanks!
