### ISSUE TITLE
tf.contrib module's alternative methods in Version 2 of Tensorflow 

### ISSUE THREAD

**Issue by ishdutt** [tensorflow/tensorflow#40348]
I'm following the documentation to migrate from V1 to V2 mentioned below which states that `tf.contrib` module is removed from the v2 and it can't be made to work even with this line of code: 
```
import tensorflow.compat.v1 as tf 
tf.disable_v2_behavior()
```
So, is the only option left is to remove them manually? If it is can we have a link mentioning the new methods for classes which are now not by supported in V2?
## URL(s) with the issue:
Guide to migration: https://www.tensorflow.org/guide/migrate
Old version's link to the tf.contrib module: https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/contrib

## Description of the issue (what needs changing):

The original documentation mentioned that the modules of `tf.contrib` are adjusted in other classes but no clear mention of where to find them. I can't find the alternative for many old methods like:
`tf.contrib.lookup.index_table_from_file`, `tf.contrib.crf.crf_decode`.
Can we have a link/mention to the new alternative methods for the removed `tf.contrib` classes in either the guide to migration or in the older version page, stating the new alternative, so that it is easier while migrating manually?

**Comment by ymodak** [comment]
Take a look at [sunsetting contrib](https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md) guide to know about whereabouts.
Also we have [TensorFlow addons ](https://github.com/tensorflow/addons)module which provides a subset of TF core contrib functionality which is no longer part of TF 2.
However there are some functions which are not absorbed by TF core neither covered by TF Addons.
For such cases you can always raise a feature request on TF addons repository.
Hope this helps. Thanks!

**Comment by ishdutt** [comment]
Hi @ymodak The first link was helpful but they were not complete, I guess. There were many empty spaces, some of them were not found in the core module like `tf.contrib.lookup` even though mentioned in their fate, some had **?** in their fate like `tf.contrib.crf`, I couldn't find them too. If the migration is still in the process, can I be a part of that SIG as mentioned in that page? I'll be happy to contribute to the TensorFlow community :)
Thanks!

**Comment by ymodak** [comment]
Sounds good. You can join SIG Addons using this [guide](https://github.com/tensorflow/community/blob/master/sigs/addons/CHARTER.md#sig-addons)
Also you can email email `community-team@tensorflow.org` directly.
