### ISSUE TITLE
Symbol file not loaded when I use C API

### ISSUE THREAD

**Issue by asxdfd** [tensorflow/tensorflow#40354]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.15.0
- Python version: 3.7
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): VS 2019 x64

Hello, here are two questions.
1. When I use C API downloaded from https://www.tensorflow.org/install/lang_c. When I run my project, VS 2019 shows "Symbol file not loaded". Later I user tensorflow_cc.dll, it shows the same error.
I use CMake x64-Release settings.
```
'TestTensorflow.exe' (Win32): Loaded 'D:\Visual Studio 2019\repos\TestTensorflow\out\build\x64-Release\TestTensorflow\tensorflow_cc.dll'. Module was built without symbols.
Exception thrown at 0x00007FFDDA4F3804 (tensorflow_cc.dll) in TestTensorflow.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
```
2. When I use C++ API compiled from source, it shows "cannot open source file 'google/protobuf/xxxx'"
Does it mean I need to install protobuf?
I compile it using
```
bazel build //tensorflow:tensorflow_cc.dll //tensorflow:tensorflow_cc_dll_import_lib //tensorflow:install_headers
```
Then I copy tensorflow_cc.dll, tensorflow_cc.lib, include/ dir in the bazel-out directory.

Thanks for your help.

**Comment by ymodak** [comment]
CMake is not supported for building TF, recommend using Bazel.

**Comment by asxdfd** [comment]
> CMake is not supported for building TF, recommend using Bazel.

Now I can use C++ API. But I still can't use C API, which is downloaded from https://www.tensorflow.org/install/lang_c. VS shows "Symbol file not loaded"
```
'TestTensorflow.exe' (Win32): Loaded 'D:\Visual Studio 2019\repos\TestTensorflow\out\build\x64-Release\TestTensorflow\tensorflow.dll'. Module was built without symbols.
Exception thrown at 0x00007FFDDA4F3804 (tensorflow_cc.dll) in TestTensorflow.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
```
Here I didn't use Cmake to build TF. I just create a CMake project to use TF C library.
Here's settings in CMakeLists.txt
```
include_directories("D:/libtensorflow-cpu-windows-x86_64-1.15.0/include")
link_directories("D:/libtensorflow-cpu-windows-x86_64-1.15.0/lib")

target_link_libraries(TestTensorflow
	tensorflow
	# other opencv lib
)
```
When code goes to TF_RunSession(), it cause an error"Symbol file not loaded".

**Comment by sachinprasadhs** [comment]
Can you try again with the latest Libtensorflow C nightly or stable packages from here https://www.tensorflow.org/install/lang_c#nightly_libtensorflow_c_packages and let us know the outcome. Thanks!
