### ISSUE TITLE
build tensorflow from source

### ISSUE THREAD

**Issue by argman** [tensorflow/tensorflow#4035]
this is not a bug, but really puzzle me. When everytime I try to build tf from source, bazel keep cloning grpc, protobuf and download something else, as my network is too slow....so this takes really a long time, is there a better way to do this?

**Comment by argman** [comment]
Found a solution, we can modify WORKSPACE to change the url to a local path, by using local_repository
[](http://bazel.io/docs/be/workspace.html#new_git_repository)

**Comment by gaussic** [comment]
@argman hi, can you explain how exactly you changed the WORKSPACE file please, i've got the save problem as you, thanks.

**Comment by argman** [comment]
@gaussic , for example
new_http_archive(
  name = "dagre",
  build_file = "bower.BUILD",
  url = "https://github.com/cpettitt/dagre/archive/v0.7.4.tar.gz",
  strip_prefix = "dagre-0.7.4",
)
you can download dagre from the link directly and store in a local path like /home/argman/dagre, then change the http archive to
new_local_repository(
  name = "dagre",
  build_file = "bower.BUILD",
  path = " /home/argman/dagre"
)

**Comment by gaussic** [comment]
@argman thank you, that's a good example, though the WORKSPACE needs to change a lot.
