### ISSUE TITLE
model.load_weights fails to find matching files in gcs bucket

### ISSUE THREAD

**Issue by CalebEverett** [tensorflow/tensorflow#40369]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux - colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
default colab installation
- TensorFlow version (use command below):
- Python version:
3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
model.load_weights from a gcs bucket fails to find matching files even though they exist

**Describe the expected behavior**
Find the files and load the weights

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

https://colab.research.google.com/drive/1PVXhopZg5RpKiJ6aUilO0oknsfNFX_Nr?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@CalebEverett 
Please update the tensorflow version used. IN case you are using an old version can you please try on later version and update.

**Comment by CalebEverett** [comment]
I have version 2.2 installed. Which version should I upgrade to?

**Comment by Saduf2019** [comment]
@CalebEverett 
I ran the code shared on tf 2.2 and do not face any error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/03077653c3302e897c0cbc00160d443e/untitled232.ipynb)

**Comment by CalebEverett** [comment]
Ok, I was able to run on 2.2. Thank you.

**Comment by Saduf2019** [comment]
Moving to closed status with confirmation.
