### ISSUE TITLE
Convert .tflite file to human-readable format

### ISSUE THREAD

**Issue by mm7721** [tensorflow/tensorflow#40363]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (or github SHA if from source): 1.15

-------------------------------------------

Is there a recommended way to convert a .tflite file into a human-readable format?  I often encounter issues with .tflite models (e.g. poor prediction performance), even though there are no error messages in the TF-->TFL conversion process.  Being able to read the contents of the .tflite file would really help with the debug process.  Thanks.

**Comment by abattery** [comment]
You can use our visualize tool. https://www.tensorflow.org/lite/guide/faq#model_conversion

```bazel run //tensorflow/lite/tools:visualize model.tflite visualized_model.html```

**Comment by abattery** [comment]
And you can get insights from our benchmark tool as well. https://www.tensorflow.org/lite/performance/benchmarks
