### ISSUE TITLE
same error using tflearn package ==0.3.2 and tenserflow ==1.14

### ISSUE THREAD

**Issue by BV-SS** [tensorflow/tensorflow#40360]
some error using tflearn package ==0.3.2 and tenserflow ==1.14 

error:'tensorflow.python.framework.op_def_registry' has no attribute 'register_op_list'

_Originally posted by @BV-SS in https://github.com/tensorflow/tensorflow/issues/34762#issuecomment-642140322_

**Comment by jvishnuvardhan** [comment]
@BV-SS Can you please provide a standalone code to reproduce the issue? You coule use colab or Jupyter notebook. Thanks!

**Comment by BV-SS** [comment]
@jvishnuvardhan running in virtual environment helped. thanks.
