### ISSUE TITLE
ilsvrc:imagenet_accuracy_eval crossed compiled for Pixel4 fails on TF2.1.0's TFlite MobileNetV3 model

### ISSUE THREAD

**Issue by luyuan2015** [tensorflow/tensorflow#40375]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): 2.1.0
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):
Pixel4

**Describe the problem**

**Please provide the exact sequence of commands/steps when you ran into the problem**
1. git clone https://github.com/tensorflow/tensorflow
2. git checkout remotes/origin/r2.1
3. conda install bazel==0.29.1
4. sudo snap install android-studio --classic
5. bazel build -c opt --config=android_arm64 //tensorflow/lite/tools/accuracy/ilsvrc:imagenet_accuracy_eval
6. Copy the imagenet_accuracy_eval to Pixel4
7. Download MobileNetV3 model and run TFLite converter with both TF1.5.0 and TF2.1.0. The two files obtained are attached.
[mbnv3_uint8q_tf150.tflite.txt](https://github.com/tensorflow/tensorflow/files/4763102/mbnv3_uint8q_tf150.tflite.txt)
[mbnv3_uint8q_tf210.tflite.txt](https://github.com/tensorflow/tensorflow/files/4763105/mbnv3_uint8q_tf210.tflite.txt)

8. Copy both tflite files to Pixel4 and run them with the following commands:
adb shell /data/local/tmp/yuan/imagenet_accuracy_eval --model_file=/data/local/tmp/yuan/mbnv3_uint8q_tf150.tflite --ground_truth_images_path=/data/local/tmp/ilsvrc_images --ground_truth_labels=/data/local/tmp/ilsvrc_validation_labels.txt --model_output_labels=/data/local/tmp/model_output_labels.txt --output_file_path=/data/local/tmp/mbv3_uint8q_tf150_output.txt --num_images=0

This will works for tf1.5 tflite model but it will crash for tf2.1.0 tflite model though I have used TF2.1 source code to compile imagenet_accuracy_eval:

Pixel4Host:~ yubei$ adb shell /data/local/tmp/yuan/imagenet_accuracy_eval_tf210 --model_file=/data/local/tmp/yuan/mbnv3_uint8q_tf210.tflite --ground_truth_images_path=/data/local/tmp/ilsvrc_images --ground_truth_labels=/data/local/tmp/yuan/ilsvrc_validation_labels.txt --model_output_labels=/data/local/tmp/model_output_labels.txt --output_file_path=/data/local/tmp/yuan/mbv3_uint8q_tf210_output.txt
native : imagenet_accuracy_eval.cc:213 Starting evaluation with: 4 threads.
native : imagenet_accuracy_eval.cc:117 Starting model evaluation: 100
INFO: Initialized TensorFlow Lite runtime.
Aborted 

It seems to me that this 2.1.0 executable doesn't support all functionalities in 2.1.0 TFLite models.

**Comment by yuan-aizip** [comment]
Any update on this issue? Many thanks.

**Comment by sushreebarsa** [comment]
@luyuan2015 
Could you please let us know if it is still an issue in TF v2.6.0 ? Thank you!
