### ISSUE TITLE
AttributeError: 'Sequential' object has no attribute '_get_save_spec'

### ISSUE THREAD

**Issue by vijay2001** [tensorflow/tensorflow#40379]
**System information**
- OS Platform and Distribution Linux Ubuntu 18.04:
- TensorFlow version 2.2.0:

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab

converter = tf.lite.TFLiteConverter.from_keras_model(model).

``---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-36-3e84dbd4022a> in <module>()
      1 import tensorflow as tf
----> 2 converter = tf.lite.TFLiteConverter.from_keras_model(model)

1 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saving_utils.py in model_input_signature(model, keep_original_batch_size)
     75     TensorSpecs. This list does not contain the `training` argument.
     76   """
---> 77   input_specs = model._get_save_spec(dynamic_batch=not keep_original_batch_size)  # pylint: disable=protected-access
     78   if input_specs is None:
     79     return None

AttributeError: 'Sequential' object has no attribute '_get_save_spec'
```

**The output from the converter invocation**

```
# Copy and paste the output here.
```

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)


**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by abattery** [comment]
I guess the error is coming from saving the given keras model object into the TF saved model directory during conversion. Probably, you need to make sure that your model is compatible with exporting to the saved model format.

Please refer #39001 I suspect that your code might be depending on keras but not on tf.keras.
