### ISSUE TITLE
Use keras `ModelCheckpoint` failed in multi-worker distribute training env

### ISSUE THREAD

**Issue by bearsroom** [tensorflow/tensorflow#40374]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, but the bug happens in official codes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): No
- TensorFlow version (use command below): 2.2.0
- Python version: 3.7
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version: 10.1
- GPU model and memory: not relevant

**Describe the current behavior**
I'm writing some codes for training a keras model in multi-worker distribute strategy env. For some compatibility issues I don't use keras `model.fit` API to launch my training loop and write my customized training loop instead. In multi-gpu env with MirroredStrategy the keras `ModelCheckpoint` works fine, but when I switch to `MultiWorkerMirroredStrategy`, the `ModelCheckpoint` returns error at the beginning of the training job.

```
Traceback (most recent call last):
  File "my_training_script.py", line 720, in custom_training_loop
    callbacks._call_begin_hook(ModeKeys.TRAIN)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/callbacks.py", line 253, in _call_begin_hook
    self.on_train_begin()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/callbacks.py", line 369, in on_train_begin
    callback.on_train_begin(logs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/callbacks.py", line 931, in on_train_begin
    training_state.MultiWorkerTrainingState(self.model, self.filepath))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/distribute/multi_worker_training_state.py", line 90, in __init__
    if not multi_worker_util.should_save_checkpoint():
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/distribute/multi_worker_util.py", line 243, in should_save_checkpoint
    return dc_context.get_current_worker_context().should_checkpoint
AttributeError: 'NoneType' object has no attribute 'should_checkpoint'
```

After a brief code search, I found the root cause of this error in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/distribute/distribute_coordinator_context.py#L26:

```
def get_current_worker_context():
  """Returns the current task context."""
  try:
    return _worker_context.current
  except AttributeError:
    return None
```
Which means the worker context is probably not set before the callback hooks launch. It returns a `None` object and `should_save_checkpoint` fails. I guess if other keras callbacks depend on the multi worker context, they will also fail if the multi-worker context is not correctly set before the training job starts.

So my question is that, is this behaviour a bug ? If not, how can I correctly setup the multi-worker training env without using `model.compile` or `model.fit`. According to the docs, the distribute training can be run by `strategy.run(step_function, args=args, kwargs=kwargs)` and `strategy.run` function handles the context settings. In this case, should I call the keras callbacks in `strategy.scope`, since my callbacks are not executed in `step_function` ?

**Comment by amahendrakar** [comment]
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!
