### ISSUE TITLE
 keras.models.save_model does not respect include_optimizer option

### ISSUE THREAD

**Issue by philipp-eisen** [tensorflow/tensorflow#40380]
**System information**
Tensorflow: v2.2.0-0-g2b96f3662b 2.2.0

**Describe the current behavior**
When passing `include_optimizer=False` to ` keras.models.save_model` the optimizers weights are included.

**Describe the expected behavior**
When passing `include_optimizer=False` to ` keras.models.save_model` the optimizers weights are **NOT** included.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1JocUwWRNmGQzE4mbL85YO-DAaVilJmlD?usp=sharing

<img width="1621" alt="Screenshot 2020-06-11 at 11 01 45" src="https://user-images.githubusercontent.com/8607233/84366389-07786000-abd3-11ea-838f-29efb095041b.png">

**Comment by ravikyram** [comment]
@philipp-eisen 

I have tried in colab with TF 2.2 , nightly version.PLease, find the gist [here](https://colab.research.google.com/gist/ravikyram/4aba249fb2cfdc244c0b9ca2eb32fb44/untitled6.ipynb).Is this the expected behavior?.Thanks!

**Comment by philipp-eisen** [comment]
@ravikyram Thanks for checking this issue out.

Unfortunately, this is not the the expected behavior. I added a workaround to the [original colab](https://colab.research.google.com/drive/1JocUwWRNmGQzE4mbL85YO-DAaVilJmlD?usp=sharing#scrollTo=laV6-irZJY9O) that produces the expected behavior.

So basically just setting the optimizer property to `None`, without compiling the model does not remove the optimizer weights. (This is what happens in the implementation that is supposed to handle `include_optimizer=False`) [see here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/saving/saved_model/save.py#L67)

<img width="1648" alt="Screenshot 2020-06-11 at 13 34 43" src="https://user-images.githubusercontent.com/8607233/84380847-5bda0a80-abe8-11ea-925b-51a6e8ad35cb.png">

**Comment by philipp-eisen** [comment]
@fchollet I think this should not be stale.

**Comment by qhduan** [comment]
Today, I found it too, when after a big model (e.g. BERT) trained, Adam's weights could be larger than model's weights ! (700MB of adams, 400MB of bert it self)

A simple reproduce work: https://colab.research.google.com/drive/1TyFfOi71njrgO8ybWRB5AlHcRHfKOhlv?usp=sharing

A little trick is replace model's optimizer before you save:

```
 old_opt = model.optimizer
 model.optimizer = tf.keras.optimizers.SGD()

 model.save(save_to, include_optimizer=False)

model.optimizer = old_opt
```

**Comment by vxacezxcv** [comment]
> Today, I found it too, when after a big model (e.g. BERT) trained, Adam's weights could be larger than model's weights ! (700MB of adams, 400MB of bert it self)
> 
> A simple reproduce work: https://colab.research.google.com/drive/1TyFfOi71njrgO8ybWRB5AlHcRHfKOhlv?usp=sharing
> 
> A little trick is replace model's optimizer before you save, if you really don't care the optimizer:
> 
> ```
> old_opt = model.optimizer
> # it WORKS, you have to assign a object which a sub-class of tf.keras.optimizers.Optimizer
> model.optimizer = tf.keras.optimizers.SGD()
> model.save(save_to, include_optimizer=False)
> model.optimizer = old_opt
> ```
> 
> ```
> old_opt = model.optimizer
> # it NOT works!
> model.optimizer = None
> model.save(save_to, include_optimizer=False)
> model.optimizer = old_opt
> ```

This trick works.
My previous walkaround was manually removing 'optimizer' from 'model._unconditional_checkpoint_dependencies'. Apparently, assigning a new optimizer looks much better.

The other trick with clone_model() is nice too, but only if the model is built with functional or sequential (not subclass).

**Comment by a7744hsc** [comment]
I also encounter this issue which makes a fine-tuned bert model 1.2G.
As Philipp said, this issue makes tf.keras API not usable for production.

**Comment by acarl005** [comment]
We are also having this problem. We moved from TF 1.15 + estimator to TF 2.3 + Keras and our model variables went from 200MB to 600MB. The extra 400MB was all the momentum and velocity variables from the ADAM optimizer. Unfortunately 600MB exceeds [AI platform's model size limit](https://cloud.google.com/ai-platform/prediction/docs/quotas#model_size_limits) so we can't put it into production.

**Comment by arnoegw** [comment]
This has been fixed with commit https://github.com/tensorflow/tensorflow/commit/5931dc3cb388063c1512b16e1b90f579a012f91c

The optimizer slot variables in @philipp-eisen 's colab go away when running it with
```
!pip -q uninstall -y tensorflow
!pip -q install 'tf-nightly==2.5.0.dev20210225'
```

**Comment by monicadsong** [comment]
Closing this issue now, as the fix has been verified!
