### ISSUE TITLE
ImportError: cannot import name 'naming' from 'tensorflow.python.autograph.core' for tf-agents

### ISSUE THREAD

**Issue by vonadz** [tensorflow/tensorflow#40385]
Hey, not sure if this is for here, for I should move it to tf-agents. I figured since the deepest part of the traceback was in tensorflow, it should be here. Please let me know if I'm wrong and I'll move to tf-agents.
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No, using this example: https://www.tensorflow.org/agents/tutorials/1_dqn_tutorial
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux 5.6.15-arch1-1
- TensorFlow installed from (source or binary): built from source
- TensorFlow version (use command below): v1.12.1-33853-gc674577870 2.2.0
- Python version: 3.8
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): 10.1.0
- CUDA/cuDNN version: 10.2 / 7.6.5
- GPU model and memory: GTX 1080 Ti  11GB

**Describe the current behavior**
Errors out when importing anything from tf-agents.
**Describe the expected behavior**
Should run without error.
**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
from tf_agents.agents.dqn import dqn_agent
**Other info / logs** Full traceback of error:
`  File "/home/frodo/Desktop/gym_project/gym-open.py", line 14, in <module>
    from tf_agents.agents.dqn import dqn_agent
  File "/home/frodo/.local/lib/python3.8/site-packages/tf_agents/agents/__init__.py", line 17, in <module>
    from tf_agents.agents import tf_agent
  File "/home/frodo/.local/lib/python3.8/site-packages/tf_agents/agents/tf_agent.py", line 26, in <module>
    from tf_agents.specs import tensor_spec
  File "/home/frodo/.local/lib/python3.8/site-packages/tf_agents/specs/__init__.py", line 20, in <module>
    from tf_agents.specs.distribution_spec import DistributionSpec
  File "/home/frodo/.local/lib/python3.8/site-packages/tf_agents/specs/distribution_spec.py", line 22, in <module>
    import tensorflow_probability as tfp
  File "/home/frodo/.local/lib/python3.8/site-packages/tensorflow_probability/__init__.py", line 76, in <module>
    from tensorflow_probability.python import *  # pylint: disable=wildcard-import
  File "/home/frodo/.local/lib/python3.8/site-packages/tensorflow_probability/python/__init__.py", line 24, in <module>
    from tensorflow_probability.python import experimental
  File "/home/frodo/.local/lib/python3.8/site-packages/tensorflow_probability/python/experimental/__init__.py", line 34, in <module>
    from tensorflow_probability.python.experimental import auto_batching
  File "/home/frodo/.local/lib/python3.8/site-packages/tensorflow_probability/python/experimental/auto_batching/__init__.py", line 24, in <module>
    from tensorflow_probability.python.experimental.auto_batching import frontend
  File "/home/frodo/.local/lib/python3.8/site-packages/tensorflow_probability/python/experimental/auto_batching/frontend.py", line 45, in <module>
    from tensorflow.python.autograph.core import naming
ImportError: cannot import name 'naming' from 'tensorflow.python.autograph.core' (/home/frodo/.local/lib/python3.8/site-packages/tensorflow/python/autograph/core/__init__.py)`

**Comment by amahendrakar** [comment]
@vonadz,
I was able to run the code without any issues on TF v2.2. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/676b1a731029776de16245ba181bd330/40385.ipynb). 

Could you please try running the same code in a virtual environment and check if it works. Thanks!

**Comment by vonadz** [comment]
@amahendrakar thanks for replying.
Using `pip install tensorflow` for the virtual env makes the code run. But when installing the tensorflow package I built from source, it fails with the same error presented in the issue. I built it with all defaults, for CUDA support, following this guide: https://www.tensorflow.org/install/source, using r2.2.

**Comment by cfabio** [comment]
I have the exact same issue, Tensorflow 2.2.0 compiled from source following the official documentation.

**Comment by cfabio** [comment]
@vonadz I found something rather interesting, with the Tensorflow binary I compiled myself (version 2.2.0) I am able to use Tensorflow Probability (both self compile or installed from PIP) version 0.7, anything newer than that gives the same error:  
~~~
tensorflow.python.autograph.core import naming ImportError: cannot import name 'naming' from 'tensorflow.python.autograph.core' (/home/frodo/.local/lib/python3.8/site-packages/tensorflow/python/autograph/core/__init__.py)
~~~

**Comment by amahendrakar** [comment]
>I found something rather interesting, with the Tensorflow binary I compiled myself (version 2.2.0) I am able to use Tensorflow Probability (both self compile or installed from PIP) version 0.7, anything newer than that gives the same error:
> 
> ```
> tensorflow.python.autograph.core import naming ImportError: cannot import name 'naming' from 'tensorflow.python.autograph.core' (/home/frodo/.local/lib/python3.8/site-packages/tensorflow/python/autograph/core/__init__.py)
> ```

@vonadz,
Could you please check @cfabio's comment and let us know if it helps. Thanks!

**Comment by vonadz** [comment]
@cfabio yes it worked! Thanks.

**Comment by amahendrakar** [comment]
Marking the issue as closed, as it is resolved. Please feel free to re-open the issue if necessary. Thanks!

**Comment by cfabio** [comment]
I am not sure we can consider this resolved, since to "make it work" I had to downgrade to an older version of Tensorflow Probability.  
My impression is that the Tensorflow (not Probability) me and @vonadz compile from source is missing something, which is even weirder since we both followed the official documentation.  
For now I might be able to live with Tensorflow Probability version 0.7, but in the future I would like to be able to use the latest version.

**Comment by amahendrakar** [comment]
> I am not sure we can consider this resolved, since to "make it work" I had to downgrade to an older version of Tensorflow Probability.

@cfabio,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template so that we can track the issue there. Thanks!

**Comment by yaowang1111** [comment]
I have the exactly same problem.

**Comment by Echo9k** [comment]
Same problem when I try to import from tensorflow_probabilty.
I'm using the official TensorFlow docker.
[tf install reference](https://www.tensorflow.org/install/source)
`docker run -it -p 8888:8888 tensorflow/tensorflow:nightly-jupyter`

**Comment by amahendrakar** [comment]
@yaowang1111, @Echo9k,
Please take a look at [#40584](https://github.com/tensorflow/tensorflow/issues/40584). The issue is already being tracked there. Thanks!

**Comment by hafiz031** [comment]
I managed to run `tensorflow-probability` with this combination:
```
pip install tensorflow==2.1.0
pip install tensorflow-probability==0.9.0```
