### ISSUE TITLE
ValueError: tf.function-decorated function tried to create variables on non-first call.

### ISSUE THREAD

**Issue by jifei** [tensorflow/tensorflow#40381]
Standalone code to reproduce the issue
https://colab.research.google.com/drive/1gNzsl6mYg8_H2GRHpdxhk8VPGEOqREti?usp=sharing

**Comment by Saduf2019** [comment]
@jifei 
Please refer to these issues with similar error:
[link](https://github.com/tensorflow/tensorflow/issues/27120)
[link1](https://github.com/tensorflow/tensorflow/issues/34983)
[link2](https://stackoverflow.com/questions/58352326/running-the-tensorflow-2-0-code-gives-valueerror-tf-function-decorated-functio)
