### ISSUE TITLE
Feature Request: API to access peak memory usage of a function call that uses TF

### ISSUE THREAD

**Issue by patrickvonplaten** [tensorflow/tensorflow#40383]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): TF 2.0, 2.1, 2.2
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

In TF 1 it was possible to retrieve the peak memory usage via:
`tensorflow.contrib.memory_stats.python.ops.memory_stats_ops import MaxBytesInUse`

This does not seem to be possible anymore in TF 2.0+

**Will this change the current api? How?**

It should not change the current api, it should something like `tf.profiler.memory_stats_ops` to the API

**Who will benefit with this feature?**

Everybody, that wants to benchmark deep learning models in TF 2.0

**Any Other info.**

The function could behave similarly to the corresponding pytorch function: 
tensorflow.contrib.memory_stats.python.ops.memory_stats_ops import MaxBytesInUse

**Comment by golden0080** [comment]
With TF 1.x 's contrib sunset, there seems no way to access memory stats during training/inference.
This makes it very hard to measure memory footprint improvements between different implementations.

**Comment by sushreebarsa** [comment]
@patrickvonplaten The tensorflow.contrib module, which contained memory_stats_ops.MaxBytesInUse, has been deprecated in TensorFlow 2.0 and later versions. The workaround could be the tensorflow profiler in TF v2.x. 
Please follow [this](https://www.tensorflow.org/guide/profiler) for reference.
Thank you!
