### ISSUE TITLE
Protobuf not choosing the right libstdc++ while building with Bazel

### ISSUE THREAD

**Issue by boubasse** [tensorflow/tensorflow#40388]
Hi everyone,

I'm having a bug which seems to be recurrent since 2016 and concerns the build of TensorFlow from the source using Bazel. Here are some system information and description of the problem.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Scientific Linux 7
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6.2
- Bazel version (if compiling from source): 3.2.0
- GCC/Compiler version (if compiling from source): 8.2.0
- CUDA/cuDNN version: 10.2/7
- GPU model and memory: V100/16GB

**Describe the current behavior**
I'm trying to build the last version of TensorFlow (2.20) using Bazel 3.2.0. Everything goes fine ignoring some warings until the protoc execution of protobuf. Please find the error snippet hereafter :

``
ERROR: /nobackup/anon/tensorflow/tensorflow/core/protobuf/BUILD:153:17: ProtoCompile tensorflow/core/protobuf/named_tensor.pb.h failed (Exit 1): protoc failed: error executing command 
  (cd /nobackup/anon/cache/bazel/_bazel_af261718/0773f41f5efd7b2afa75c2b5b53f9c82/execroot/org_tensorflow && \
  exec env - \
  bazel-out/host/bin/external/com_google_protobuf/protoc '--cpp_out=bazel-out/k8-opt-exec-50AE0418/bin' -I. -Iexternal/com_google_protobuf/src -Ibazel-out/k8-opt-exec-50AE0418/bin/external/com_google_protobuf/src tensorflow/core/protobuf/named_tensor.proto)
Execution platform: @local_execution_config_platform//:platform
bazel-out/host/bin/external/com_google_protobuf/protoc: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by bazel-out/host/bin/external/com_google_protobuf/protoc)
bazel-out/host/bin/external/com_google_protobuf/protoc: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by bazel-out/host/bin/external/com_google_protobuf/protoc)
bazel-out/host/bin/external/com_google_protobuf/protoc: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by bazel-out/host/bin/external/com_google_protobuf/protoc)
bazel-out/host/bin/external/com_google_protobuf/protoc: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by bazel-out/host/bin/external/com_google_protobuf/protoc)
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: /nobackup/anon/tensorflow/tensorflow/python/tools/BUILD:282:10 ProtoCompile tensorflow/core/framework/graph.pb.h failed (Exit 1): protoc failed: error executing command 
  (cd /nobackup/anon/cache/bazel/_bazel_af261718/0773f41f5efd7b2afa75c2b5b53f9c82/execroot/org_tensorflow && \
  exec env - \
  bazel-out/host/bin/external/com_google_protobuf/protoc '--cpp_out=bazel-out/k8-opt-exec-50AE0418/bin' -I. -Iexternal/com_google_protobuf/src -Ibazel-out/k8-opt-exec-50AE0418/bin/external/com_google_protobuf/src tensorflow/core/framework/graph.proto)
Execution platform: @local_execution_config_platform//:platform
``
As we can see, it refers to /lib64 instead of refering to the lib specified in LD_LIBRARY_PATH. Actually, the `exec env -` will erase all the env vars passed to command ... I've tried several workarounds by adding a `--linkopt="-Wl, -rpath,/path/to/lib64"` or even in the following issues: https://github.com/bazelbuild/bazel/issues/1358#issuecomment-232019644 and https://github.com/bazelbuild/bazel/issues/649#issuecomment-166710509 but it seems that the CROSSTOOL file doesn't exist anymore... These workarounds don't work for me and I don't know what to do anymore.

**Describe the expected behavior**
Passing correct lib64 folder to LD_LIBRARY_PATH should overcome the problem but since `exec env -` is still active the variable is erased.

Do you have a solution for this problem?
Thanks

**Comment by boubasse** [comment]
Problem solved, I was building on the master directly instead of checking out the r2.2 branch.

However, the problem still exists with SWig.

The solution to address the issue is the following:

- Navigating to `bazel-tensorflow/external/swig`
- Modify the file `BUILD.bazel`
- Add this add the end of the `cc_library` object:
``
linkopts = ["-Wl,-rpath,/path/to/custom/libstdc/path/",
                  "-L/path/to/custom/libstdc/path"
]
``

The issue can be closed.

**Comment by ymodak** [comment]
Closing this issue since it's resolved. @boubasse Thanks for sharing solution.
