### ISSUE TITLE
clarification with TF datasets: more efficient to vectorize with unbatching (batch -> map -> unbatch) or just map?

### ISSUE THREAD

**Issue by jshyatt2** [tensorflow/tensorflow#40386]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://www.tensorflow.org/guide/data
https://www.tensorflow.org/guide/data_performance

## Description of issue (what needs changing):

The documentation for vectorizing code says that vectorizing transformations is more efficient, as with batch -> map. However, it doesn't say anything about the overhead of unbatch; as a result, I have seen the process batch -> map -> unbatch to vectorize transformations before adding more methods (like cache -> shuffle) that you don't want to perform on the batched dataset.

It's not clear which is better, or whether it depends on hardware, dataset, batch size, etc.:
1) Just performing dataset.map(my_transformation)
2) Performing dataset.batch(batch_size).map(my_transformation).unbatch()

When the whole dataset fits in memory, the map would be performed once (in front of cache), and so an inefficient implementation would only bear a one-time cost. However, if the dataset is large enough to require sharding (I haven't looked into this), wouldn't this extra cost be paid every time a new shard is loaded? 

I have seen (2) show up in numerous (non-official) tutorials, but at least in the few cases I have tested, it can cause a slowdown of up to 1.5x. It seems like a small change could clarify this, especially if the overhead in unbatch is probably always higher than the cost of non-vectorized transformations. I could also see it being that for certain cases, (2) is actually more efficient, but that's just a guess.

**Comment by aaudiber** [comment]
Thanks for reporting this @jshyatt2. 

I expect that the overhead of calling `unbatch` will almost always outweigh the overhead saved by vectorizing the map. It is better to vectorize at the final batch level, so that no `unbatch` is needed.

I'll update https://www.tensorflow.org/guide/data_performance to follow the best practice of vectorizing at the final batch level.

**Comment by jshyatt2** [comment]
Good to know; I was afraid I'd have to worry about case-by-case optimizing. Thanks!

**Comment by jshyatt2** [comment]
@aaudiber Just to offer an additional comment with respect to unbatch (and specifically on https://www.tensorflow.org/guide/data_performance):

In https://www.tensorflow.org/guide/data_performance#pipelines_comparison, batch (with drop_remainder=True), followed by unbatch, is used to (as far as I can tell) get rid of the ragged batch at the end of the dataset.

In https://www.tensorflow.org/guide/data_performance#optimized (at least currently), it is used to vectorize a transformation, then unbatch, and in that case unbatch is actually called after prefetch.
