### ISSUE TITLE
tf_upgrade_v2 needs explicit encodings on Windows to upgrade utf-8

### ISSUE THREAD

**Issue by sbuser** [tensorflow/tensorflow#40387]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary x64
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.8.2
- CUDA/cuDNN version: 10.1
- GPU model and memory: Tesla K80, 1080ti (11GB per gpu)

**Describe the current behavior**

Running tf_upgrade_v2 yields encoding errors on Windows, even with defaults set to utf-8 (though no explicit encodings in each file -- as this isn't required in Python 3). 

Adding explicit encoding to `tensorflow\tools\compatibility\ast_edits.py` as shown below resolved this for me -- if a default of utf-8 isn't desirable maybe a command line option?

```
    # Write to a temporary file, just in case we are doing an implace modify.
    # pylint: disable=g-backslash-continuation
    with open(in_filename, "r", encoding='utf-8') as in_file, \
        tempfile.NamedTemporaryFile("w", delete=False, encoding='utf-8') as temp_file:
      ret = self.process_opened_file(in_filename, in_file, out_filename,
                                     temp_file)
    # pylint: enable=g-backslash-continuation
```

**Comment by Saduf2019** [comment]
@sbuser 
Please share simple stand alone code for us to replicate the issue faced or is possible share a colab gist for us to analyse the issue.
