### ISSUE TITLE
[TF2.2] Loading a Saved Model from tensorflow_hub failed with `AttributeError: '_UserObject' object has no attribute 'summary'`

### ISSUE THREAD

**Issue by kinos9** [tensorflow/tensorflow#40392]
**System info:**
Python: 3.6.9
Tensorflow: 2.2.0 CPU package from _pip_

**The issue:**
I got https://tfhub.dev/google/imagenet/resnet_v2_50/classification/4?tf-hub-format=compressed from tf-hub and then uncompressed in a new directory.

with following code:

```
print(tf.__version__)

resnet50v2_save_path = os.path.join('.', "test2/imagenet_resnet_v2_50_feature_vector_4/")

loaded1 = tf.keras.models.load_model(resnet50v2_save_path)
print(loaded1.summary())
```

I get:
```
2.2.0
2020-06-11 21:51:49.413961: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1995500000 Hz
2020-06-11 21:51:49.414437: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x57d3130 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-11 21:51:49.414460: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "./test2.py", line 43, in <module>
    print(loaded1.summary())
AttributeError: '_UserObject' object has no attribute 'summary'
```
However, if I create my own model and then save into .pb format and then load in the same way it works.

Why? Thx

**Comment by Saduf2019** [comment]
@kinos9 
Can you please refer to these issues with similar error:
[link](https://github.com/tensorflow/tensorflow/issues/33870#issuecomment-576925084)
[link1](https://stackoverflow.com/questions/60979586/how-do-i-convert-a-tensorflow-model-into-a-tensorrt-optimized-model-using-trt-tr) 
[link2](https://github.com/tensorflow/tensorflow/issues/26814#issuecomment-610067468)
Please share simple standalone code for us to replicate the issue in case the above issues are not helpful.

**Comment by kinos9** [comment]
I have already found and tried those solution without success.
This is what I do to get the error:

```
wget https://storage.googleapis.com/tfhub-modules/google/imagenet/resnet_v2_50/feature_vector/4.tar.gz
mkdir test_pb
mv 4.tar.gz test_pb
cd test_pb
tar -xvf 4.tar.gz
rm 4.tar.gz
cd ..
./test.py
```

`test.py` is the Python script, and this following is the standalone code:

```
#!/usr/bin/env python3
from __future__ import absolute_import, division, print_function, unicode_literals

import os
import tensorflow as tf

print(tf.__version__)

resnet50v2_save_path = os.path.join('.', "./test_pb/")

loaded1 = tf.keras.models.load_model(resnet50v2_save_path)
print("Load done")

print("Signatures: ", loaded1.signatures)

print("Type: ", type(loaded1))

print(loaded1.summary())
```

that give this output:

```
2.2.0
2020-06-12 20:29:07.677555: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 1995455000 Hz
2020-06-12 20:29:07.678219: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x59eb130 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-12 20:29:07.678241: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Load done
Signatures:  _SignatureMap({})
Type:  <class 'tensorflow.python.saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject'>
Traceback (most recent call last):
  File "./test.py", line 18, in <module>
    print(loaded1.summary())
AttributeError: '_UserObject' object has no attribute 'summary'
```

that is the mentioned error.

Thx

**Comment by kinos9** [comment]
> @kinos9
> Can you please refer to these issues with similar error:
> [link](https://github.com/tensorflow/tensorflow/issues/33870#issuecomment-576925084)
> [link1](https://stackoverflow.com/questions/60979586/how-do-i-convert-a-tensorflow-model-into-a-tensorrt-optimized-model-using-trt-tr)
> [link2](https://github.com/tensorflow/tensorflow/issues/26814#issuecomment-610067468)
> Please share simple standalone code for us to replicate the issue in case the above issues are not helpful.

If you run `print(loaded1.tensorflow_version)` it prints 1.14.0.
May .pb version is incompatible with 2.2.0 one?

**Comment by gowthamkpr** [comment]
Yes. Looks like it.

**Comment by gowthamkpr** [comment]
@kinos9 Can you please respond to the above comment so that we can take the discussion forward. Thanks!

**Comment by kinos9** [comment]
> Yes. Looks like it. Instead of downloading the model, can you load the model as a Keras Layer using `hub.KerasLayer()` and then use the model? Thanks!

Sorry, I miss this answer.
Yes of course and in that way work, but when I export the graph as protobuf for inference with C++ APIs it looks for a KerasLayer object.

**Comment by gowthamkpr** [comment]
So, Did you try using `tf.keras.applications.ResNet50V2` instead of loading from a hub?

**Comment by twohiccups** [comment]
Hi, having the same issue, can this be reopened?

**Comment by Biplab097** [comment]
please reopen this Issue

**Comment by AndyMcPython** [comment]
I had this issue after converting a pytorch model to .onnx, to .pb

How top get something like a summary:
https://github.com/onnx/onnx-tensorflow/issues/855#issuecomment-765028398
How to use the .pb file:
https://github.com/onnx/onnx-tensorflow/issues/901#issuecomment-821686852
