### ISSUE TITLE
Saving/Loading Subclassed Models TF2+/keras

### ISSUE THREAD

**Issue by ryanmaxwell96** [tensorflow/tensorflow#40395]
**Update-template** I don't really see how to fill in this template.
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

Hello,

I am having a lot of difficulties saving a subclassed model and reloading it. I have uploaded the current files I'm working on (specifically, policy.py) to https://github.com/ryanmaxwell96/trpo_fractal5NN. Now, I know you are supposed to be able to save things under the SavedModel format so that is what I've been trying to follow. But I'm still getting the error seen here:

'''
Traceback (most recent call last):
  File "train.py", line 411, in <module>
    main(**vars(args))
  File "train.py", line 367, in main
    policy_model.save('policy_model')
  File "/home/ryan/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 975, in save
    signatures, options)
  File "/home/ryan/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py", line 115, in save_model
    signatures, options)
  File "/home/ryan/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/saved_model/save.py", line 74, in save
    save_lib.save(model, filepath, signatures, options)
  File "/home/ryan/.local/lib/python3.6/site-packages/tensorflow_core/python/saved_model/save.py", line 883, in save
    _ = _SaveableView(checkpoint_graph_view)
  File "/home/ryan/.local/lib/python3.6/site-packages/tensorflow_core/python/saved_model/save.py", line 164, in __init__
    self.checkpoint_view.objects_ids_and_slot_variables())
  File "/home/ryan/.local/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/graph_view.py", line 418, in objects_ids_and_slot_variables
    object_names[obj] = _object_prefix_from_path(path)
  File "/home/ryan/.local/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/graph_view.py", line 64, in _object_prefix_from_path
    for trackable in path_to_root))
  File "/home/ryan/.local/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/graph_view.py", line 64, in <genexpr>
    for trackable in path_to_root))
  File "/home/ryan/.local/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/graph_view.py", line 57, in _escape_local_name
    return (name.replace(_ESCAPE_CHAR, _ESCAPE_CHAR + _ESCAPE_CHAR)
AttributeError: 'NoneType' object has no attribute 'replace'
'''

In line 90 of the policy.py file is where I'm trying to save the subclassed model "self.trpo" after having called train_on_batch and predict_on_batch. I have absolutely no idea what the error is telling me.

Any help would be greatly appreciated!

Thanks,

Ryan

**Comment by ravikyram** [comment]
@ryanmaxwell96 

Request you to fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Also, let us know Tensorflow version you are using.

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by ryanmaxwell96** [comment]
Here is the colab file with the issue I was referring to. https://colab.research.google.com/drive/1dD9QKj9-NzdCECBWKkkihS18Iqmlf5-o?usp=sharing

For the prompts it asks for, input the following in this order:
CartPoleBulletEnv-v1
n
1.0

**Comment by ryanmaxwell96** [comment]
Ahh bummer. It gave me the error the first time through, but now is giving me another error I haven't seen before.

**Comment by ryanmaxwell96** [comment]
Ok so I think I may see a problem. I used the model.summary() command to get:

trpo summary
Model: "trpo"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
policy_nn (PolicyNN)         multiple                  4393      
_________________________________________________________________
log_prob (LogProb)           multiple                  0         
_________________________________________________________________
kl_entropy (KLEntropy)       multiple                  0         
=================================================================
Total params: 4,394
Trainable params: 4,393
Non-trainable params: 1
_________________________________________________________________
None

I have no idea why it says None at the end, but I'm guessing this is the problem. Any way to remove it?

**Comment by ravikyram** [comment]
@ryanmaxwell96 

Request you to grant me the access for the colab link you have shared. Thanks!

**Comment by ryanmaxwell96** [comment]
I think I gave it. Do you have access now?

**Comment by ravikyram** [comment]
@ryanmaxwell96 

I am not able to reproduce the issue.Please, find the gist [here.](https://colab.research.google.com/gist/ravikyram/7bf8b324c941de603121854dcdea118b/untitled36.ipynb)Please, help with the reproducible code .It helps us in localizing the issue faster.Thanks!

**Comment by ryanmaxwell96** [comment]
Sorry for the round-about way of doing this, as I don't really know how to use colab very well. But you need to upload these (https://github.com/ryanmaxwell96/trpo_w_subclassing/upload) files to the colab as well as use !pip install pybullet to get the errors that I've been talking about.

**Comment by ryanmaxwell96** [comment]
Also, don't forget this part:

For the prompts it asks for, input the following in this order:
CartPoleBulletEnv-v1
n
1.0

**Comment by ryanmaxwell96** [comment]
This should show the errors I've been getting:
https://colab.research.google.com/drive/1dD9QKj9-NzdCECBWKkkihS18Iqmlf5-o#scrollTo=Ft_-1u1cnjW2

**Comment by gowthamkpr** [comment]
@ryanmaxwell96 I am not able to reproduce this issue. Please share us a minimal reproducible code to reproduce this. Thanks!

**Comment by ryanmaxwell96** [comment]
If you follow the steps that I listed: upload these (https://github.com/ryanmaxwell96/trpo_w_subclassing/upload) files to the colab, use !pip install pybullet, and then type these (CartPoleBulletEnv-v1, n, 1.0) in when prompted, you should get the errors I was referring to.

I have shared the train colab file with you that should show the errors.

**Comment by gowthamkpr** [comment]
@ryanmaxwell96 I tried to reproduce this issue but I am not able to. Please find my gist [here](https://colab.research.google.com/gist/gowthamkpr/9ecc1e702bb55c37d6e8c41158dee09b/train.ipynb)
