### ISSUE TITLE
Mixed precision does not improve the speed

### ISSUE THREAD

**Issue by xlnwel** [tensorflow/tensorflow#40397]
I'm using TF 2.2 to write reinforcement learning algorithms. Because I use a relatively large model, I try to apply mixed precision to improve the training speed. My network consists of three ResNet blocks of depth `[16, 32, 32]`(features are downsampled using maxpooling layer with stride 2 before each block) following by 2 dense layers of size 512, and the input data is of shape `[512, 64, 64, 3]`. After applying the mixed_precision (following [this guide](https://www.tensorflow.org/guide/keras/mixed_precision)), I see the memory usage drops from 3787MB to 1229MB, but the training speed decreases from 20 training steps per second to 15 training steps per second. My code restrictly follows the [official guide](https://www.tensorflow.org/guide/keras/mixed_precision), but I cannot get the improvement on the speed. What might cause the problem?

By the way, my GPU is RTX 2080Ti.

**Comment by Saduf2019** [comment]
@xlnwel 
Please share simple stand alone code to replicate the issue faced or if possible share a colab gist for us to analyse the issue

**Comment by xlnwel** [comment]
Hi, @Saduf2019 . Here's a colab file I create. Please check it
https://colab.research.google.com/drive/1nBuYrmmH5kM0jbtIZdsuiG6uJbU6mpA7?usp=sharing

**Comment by Saduf2019** [comment]
@xlnwel 
I ran the code shared but face a different issue,the code continous to run for ever after mixed precision result.
Please find the [gist here](https://colab.research.google.com/gist/Saduf2019/c1a8afc6efce10617eef66d96cedb962/untitled231.ipynb)

**Comment by xlnwel** [comment]
Maybe because you did not use GPU? Following "Runtime -> set runtime type -> GPU", you can set GPU. Running the gist you provided, I did not see any issue. Here's a screenshot of the result

<img width="673" alt="image" src="https://user-images.githubusercontent.com/10184153/84834504-18f2b980-b064-11ea-87ae-227fb33dd870.png">

**Comment by Saduf2019** [comment]
I am able to replicate the issue faced, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/48cc78aedf6dbde9df80973aadb5d5cf/untitled235.ipynb).

**Comment by xlnwel** [comment]
Hi, @Saduf2019 and @gowthamkpr. Any idea why using `mixed_float16` takes longer time than using `float32`?

**Comment by reedwm** [comment]
I cannot reproduce with TF 2.4rc3. On a Titan V, I get 16.7 seconds with float16 and 43.2 seconds with float32, so I'm assuming this has been fixed.
