### ISSUE TITLE
Importing TensorFlow package in PyCharm

### ISSUE THREAD

**Issue by jforjay1** [tensorflow/tensorflow#40401]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.2.0
- Python version: 3.8
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: 11.0
- GPU model and memory: NVIDIA Geforce GTX 1050

**Describe the problem**

I installed tensorflow using `pip install tensorflow ` in cmd and tested in python its working or not using `import tensorflow as tf; print(tf.__version__)` successfully ran and got output 2.2.0. What means is I have installed tensorflow  correctly on my PC. But when I am trying to import tensorflow package in Pycharm using following Steps it doesn't work. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Steps:
1.Opened project.
2. File -> Settings ->Project Interpreter (under Project: <Your project title>)
![image](https://user-images.githubusercontent.com/46365760/84466587-51c31500-ac97-11ea-9749-9a230b58e8c5.png)
3. Okay so there is no tensorflow package I need to add it now!
4.When I hit + button to add package I found Tensorflow but when I import it is says `conda.exceptions.UnsatisfiableError:`
![image](https://user-images.githubusercontent.com/46365760/84466734-b8e0c980-ac97-11ea-920d-af87263bafbc.png)
5. Error Screenshot
![image](https://user-images.githubusercontent.com/46365760/84466975-5b994800-ac98-11ea-8cbd-811f4d8999f8.png)

**Any other info / logs**

Tried Solutions:
1. Tensorflow works in Spyder too for me perfectly.
2. Tried creating new interpreter also but no luck!

Other Questions:
1. Why in second screenshot tensorflow version 2.1.0 is shown at bottom right side(Specific version) as I haven't installed any other versions previously and no option of 2.2.0?
2. Why tensorflow is located in Anaconda folder while I haven't installed tensorflow through Anaconda? 
3. Coping tensorflow package folder to pkgs folder i.e in my case from `C:\ProgramData\Anaconda3\Lib\site-packages\tensorflow` to `C:\ProgramData\Anaconda3\pkgs` Pycharm will able to access tensorflow ?
4. I referred a lot of your previous solved issues but why none have proper solution for 2.2.0?

**Comment by leehanchung** [comment]
Conda has poor compatibility with PyCharm. If you have `conda` installed in your system, you would have to start PyCharm manually from an activate conda environment, e.g. `base`.

There are two ways to solve this:
1. Select `conda` when you create an virtual environment in PyCharm.
2. Launch PyCharm from your command prompt/powershell *after* you activate an conda enviroment (`base` is fine).  And then select `venv` when you create an virtual environment in PyCharm

For example, I installed PyCharm for myself only, and I have to launch PyCharm by the following for #2 to work:
```
cd AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\201.7846.77\bin
./pycharm.bat
```

Hope this helps.

My spec is as follows:
```
Windows 10 Pro
nvidia-smi CUDA Version: 11.0
nvcc CUDA version: 10.1
```

**Comment by jforjay1** [comment]
> Conda has poor compatibility with PyCharm. If you have `conda` installed in your system, you would have to start PyCharm manually from an activate conda environment, e.g. `base`.
> 
> There are two ways to solve this:
> 
> 1. Select `conda` when you create an virtual environment in PyCharm.
> 2. Launch PyCharm from your command prompt/powershell _after_ you activate an conda enviroment (`base` is fine).  And then select `venv` when you create an virtual environment in PyCharm
> 
> For example, I installed PyCharm for myself only, and I have to launch PyCharm by the following for #2 to work:
> 
> ```
> cd AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\201.7846.77\bin
> ./pycharm.bat
> ```
> 
> Hope this helps.
> 
> My spec is as follows:
> 
> ```
> Windows 10 Pro, Build 19041
> nvidia-smi CUDA Version: 11.0
> nvcc CUDA version: 10.1
> ```

@leehanchung  Is there anything to do with environmental variables? I have added all envs while installation.

**Comment by leehanchung** [comment]
@jforjay1 It's a known issue for PyCharm on Windows. PyCharm creates the venv using conda environment (conda is the bully). But when PyCharm activates the venv it doesnt activate conda first, thus the issue.

So the workaround, at least for me, is to launch PyCharm within an activated conda environment from command line.

Try my workaround and see if that works for you.

**Comment by jforjay1** [comment]
> @jforjay1 It's a known issue for PyCharm on Windows. PyCharm creates the venv using conda environment (conda is the bully). But when PyCharm activates the venv it doesnt activate conda first, thus the issue.
> 
> So the workaround, at least for me, is to launch PyCharm within an activated conda environment from command line.
> 
> Try my workaround and see if that works for you.

@leehanchung  I did it. Thanks mate.
There was another environment as `myenv` already I added that environment and interpreter located inside it.

**Comment by Saduf2019** [comment]
@jforjay1
Is this still an issue
