### ISSUE TITLE
tensorflow.keras slower than keras for repetitive calls to Model.predict()

### ISSUE THREAD

**Issue by gringet** [tensorflow/tensorflow#40412]
**System information**
- google colab notebook: [https://colab.research.google.com/drive/17PCkA9z5i8Yj9qd4QREYOSoaz8JFjk0C?usp=sharing](https://colab.research.google.com/drive/17PCkA9z5i8Yj9qd4QREYOSoaz8JFjk0C?usp=sharing)

**Describe the current behavior**
tensorflow.keras is significantly slower than keras when using repetitive calls to Model.predict().

**Describe the expected behavior**
Should be about the same no?

**Comment by Saduf2019** [comment]
I am able to replicate the issue, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/e3fcf08b38ac343e851b48aa6e51646a/untitled229.ipynb)

**Comment by gringet** [comment]
This stackoverflow post give a lot of information related to this problem : [https://stackoverflow.com/questions/58441514/why-is-tensorflow-2-much-slower-than-tensorflow-1](https://stackoverflow.com/questions/58441514/why-is-tensorflow-2-much-slower-than-tensorflow-1)

I think it boil down to the fact that tf.keras is in eager mode by default. I disabled it in this [notebook](https://colab.research.google.com/drive/17PCkA9z5i8Yj9qd4QREYOSoaz8JFjk0C?usp=sharing) and speed is on par with keras. I don't really know the implication of doing this though.

**Comment by ymodak** [comment]
Please try using TF 2.3 I noticed it runs faster ([trained on colab gpu](https://colab.research.google.com/gist/ymodak/3d76e547dcdca9c6843c8f300949ab7e/untitled229.ipynb)). The repetitive calls are are faster than the first `Model.predict()` too. Thanks!
