### ISSUE TITLE
Building Tensorflow from the source for the second time fails

### ISSUE THREAD

**Issue by shilan** [tensorflow/tensorflow#40418]
I am trying to build Tensorflow from the source (master branch) to get **AVX2** problem solved and get training faster, on my 
- **windows 10** machine 
-  intel(R) cpu Core i78650U 1.90GHz 2.11  which apparently doesn't have GPU support.
- **Python 3.7.4**.
First time I set my mavx2 and mavx flags when running configure.py and then I tried this command:
`bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --config=cuda -k //tensorflow/tools/pip_package:build_pip_package`

It ran quite fast and built successfully though I could read in the log:

> cl : Command line warning D9002 : ignoring unknown option '-mavx'
> cl : Command line warning D9002 : ignoring unknown option '-mavx2'
> cl : Command line warning D9002 : ignoring unknown option '-mfma'
> cl : Command line warning D9002 : ignoring unknown option '-mfpmath=both'
> cl : Command line warning D9002 : ignoring unknown option '-msse4.2'
> cl : Command line warning D9002 : ignoring unknown option '-fno-strict-aliasing'
> cl : Command line warning D9002 : ignoring unknown option '-fexceptions' so these options aren't known

I made a wheel anyway and I could run the train command, however I am getting this warning:

>  This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance-critical operations:  AVX AVX2
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

and it doesn't run any faster.
I decided to manipulate the flags and run the bazel build again but now it fails! I cannot compile it anymore and I don't know if the previous build is failing this one or what?
How should I clean the previous build/installation? Should I checkout the code again?

And by the way what should I set my flags to, to get it right this time?

**Comment by Saduf2019** [comment]
@shilan 
Please refer to this [link](https://stackoverflow.com/questions/47068709/your-cpu-supports-instructions-that-this-tensorflow-binary-was-not-compiled-to-u) and let us know if it helps.
#37876 #35052 #35056

**Comment by mihaimaruseac** [comment]
`bazel clean --expunge`

**Comment by shilan** [comment]
@Saduf2019 I had seen this stackoverflow ticket and this one [this one](https://stackoverflow.com/questions/41293077/how-to-compile-tensorflow-with-sse4-2-and-avx-instructions?rq=1) too. As a matter of fact I ran the command from their suggestions. Otherwise the one suggested by **Intel** or **tensorflow document** gets stuck somewhere and doesn't continue from there.

@mihaimaruseac thanks for the clean command, I am going to a mini vacation but I will give it a try when I am back.

**Comment by Saduf2019** [comment]
@shilan 
In that case can we please close this issue and in case you still face an issue after your vacation you can open an issue.

**Comment by shilan** [comment]
I will be back next week, but closing this might be a false indication that it solved the problem, which it didn't. I ran the commands they had suggested and none worked for me. The only thing I haven't tried though is the downloading the windows compiled wheel that @King has suggested. However that doesn't solve my problem entirely. What if I need to change the tensorflow code and compile it again.

**Comment by shilan** [comment]
I ran the command provided by Intel. It doesn't set any flags for avx2 or avx but it also got stock for 2 days and I just stopped it.
It is so weird that there is no clear command or flag to build tensorflow with **avx2** flags on **windows** platform in tensorflow documents or anywhere! 
I just cannot believe there is no certain or tested way of doing this!

**Comment by shilan** [comment]
I am gonna close this issue, but it doesn't mean that it is resolved. It just means I gave up on tensorflow and intel poor documentation.
