### ISSUE TITLE
Seq2Seq using copy mechanism(such as pointer-generator network)

### ISSUE THREAD

**Issue by yanglei-github** [tensorflow/tensorflow#40411]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):tf 2.1
- Are you willing to contribute it (Yes/No):Yes

**Describe the feature and the current behavior/state.**
I am using the template in tutorial 'Machine translation using Seq2Seq with attention'. 
However, nowadays, copy mechanism(pointer-generator and copynet) is really important when we train seq2seq model.

Could you please provide an API that Machine translation using pointer-generator network?

**Will this change the current API? How?**  it may need a new API or old API with new parameters that can let us use pointer-generator.

**Who will benefit with this feature?**
The researcher who focus on machine translation and chatbot would be benefited with this feature

**Any Other info.**

**Comment by ravikyram** [comment]
@yanglei-github 

Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!
