### ISSUE TITLE
ValueError: we need atleast 1 value to plot word cloud,  got 0

### ISSUE THREAD

**Issue by AasthaNagpal** [tensorflow/tensorflow#40419]
normal_words = ' '.join([text for text in combi['tidy_tweet'][combi['label'] == 0]]) wordcloud = WordCloud(width=800, height=500, random_state=21, max_font_size=110).generate(normal_words) plt.figure(figsize=(10, 7)) plt.imshow(wordcloud, interpolation="bilinear") plt.axis('off') plt.show()

ValueError: we need atleast 1 word to plot word cloud, got 0.

**Comment by amahendrakar** [comment]
@AasthaNagpal,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!
