### ISSUE TITLE
Codelab: Recognize Flowers with TensorFlow Lite on Android - emulator crashes

### ISSUE THREAD

**Issue by add-more-tabasco** [tensorflow/tensorflow#40426]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://codelabs.developers.google.com/codelabs/recognize-flowers-with-tensorflow-on-android/#7

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/MyMethod

## Description of issue (what needs changing):

Adding clear requirements for running the app on an emulator.

### Clear description

I was unable to get the app to fully run on an emulator in Android Studio. It loads once, then when I click 'Allow' on the camera permissions window, it crashes and cannot restart. 

I tried running both the app after following the codelab, and the prebuilt one in the finish directory (having moved the tf model file to its assets directory). I tried various emulator configurations in the AVD manager, including what was shown on screen. There may be some incompatible configuration in the emulator or another requirement that isn't being specified.

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example?

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by ymodak** [comment]
This codelab is now updated and uses TF Lite Model Maker module  https://codelabs.developers.google.com/codelabs/recognize-flowers-with-tensorflow-on-android#0
Please give it a try and let us know if you have any questions.
Thanks!
