### ISSUE TITLE
How to bind the tensor data for some node?

### ISSUE THREAD

**Issue by haolujun** [tensorflow/tensorflow#40424]
HI :
    I use some other distributed-train-framework got a model include meta_graph.pb and param data separate， and the checkpoint format is different  from tensorflow,  In order to speed the online predict service, avoid build some tensor frequently, I want to bind some param data in some tensor-node, like bias and layer. Could you show me how to do this?

**Comment by Saduf2019** [comment]
@haolujun 

This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
