### ISSUE TITLE
Can't load subclassed model 's architecture from keras.layers.serialize(model)

### ISSUE THREAD

**Issue by AlexanderJLiu** [tensorflow/tensorflow#40429]
According to the [guide](https://www.tensorflow.org/guide/keras/save_and_serialize#custom_objects), I defined a subclass model with get_config method:

```python
from tensorflow import keras
from tensorflow.keras import layers

class ThreeLayerMLP(keras.Model):
    def __init__(self, hidden_units):
        super().__init__()
        self.hidden_units = hidden_units
        self.dense_layers = [layers.Dense(u) for u in hidden_units]

    def call(self, inputs):
        x = inputs
        for layer in self.dense_layers:
            x = layer(x)
        return x

    def get_config(self):
        config = {"hidden_units": self.hidden_units}
        return config

model = ThreeLayerMLP([64, 64, 10])
serialized_model = keras.layers.serialize(model)
new_model = keras.layers.deserialize(
    serialized_model, custom_objects={'ThreeLayerMLP': ThreeLayerMLP})
```

After serialized the model, I tried to load it but failed with errors:

```shell
Traceback (most recent call last):
  File "demo14.py", line 35, in <module>
    serialized_model, custom_objects={'ThreeLayerMLP': ThreeLayerMLP})
  File "D:\Program Files\anaconda3\envs\tf2.2\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 109, in deserialize
    printable_module_name='layer')
  File "D:\Program Files\anaconda3\envs\tf2.2\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 373, in deserialize_keras_object

    list(custom_objects.items())))
  File "D:\Program Files\anaconda3\envs\tf2.2\lib\site-packages\tensorflow\python\keras\engine\network.py", line 987, in from_config
    config, custom_objects)
  File "D:\Program Files\anaconda3\envs\tf2.2\lib\site-packages\tensorflow\python\keras\engine\network.py", line 2018, in reconstruct_from_config
    for layer_data in config['layers']:
KeyError: 'layers'
```

So I want to know how to safely load a subclassed model's architecture? Thanks~

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2, nightly versions(`2.3.0-dev20200614`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/0f40a7e00bf059c154086323eee7ef94/untitled19.ipynb).Thanks!

**Comment by jvishnuvardhan** [comment]
@AlexanderJLiu If you are looking for serializing a subclass layer, then please follow [this guidie](https://www.tensorflow.org/guide/keras/save_and_serialize#defining_the_config_methods) on TF website. If you want to serialize, a subclassed model then you could you `model.save` and 'tf.keras.models.load_model` to load the model. Another approach is to use `save_weights` and instantiate the model, call predict and then use `load_weights`. Please let me know what you think. Thanks!

**Comment by AlexanderJLiu** [comment]
@jvishnuvardhan Yes, I've read this [guide](https://www.tensorflow.org/guide/keras/save_and_serialize#custom_objects) for several  times, 
and subclassed layers could be serialized and deserialized correctly.

The method `model.save` you provide would save the **whole model** including weights and optimizer state etc. And `save/load weights` just use the weights info with reinstantiating the model.

What I want to know is that is there a way to  just save the **subclassed model's architecture** just like Sequential of Functional models' `get_config method` do?  

Also I don't understand that why subclassed **layer** could be serialized/deserialized by that way but **subclassed** model couldn't?

Thanks~

**Comment by AlexanderJLiu** [comment]
According to the newest(2020-06-19) update guide [here](https://www.tensorflow.org/guide/keras/save_and_serialize#custom_objects), It seems that there is no way just to save a subclassed model's architecture **util now**.

But We could just load the tensorflow graph of subclassed model using `tf.saved_model.load("path_to_my_model")`. The graph is not a keras object, so we can't use methods like predict or fit.

Anyway, I'm just curious about the reason, some convincing explanations would be nice for me.

Thanks~

**Comment by k-w-w** [comment]
`tf.saved_model.load("path_to_my_model")` doesn't restore a Keras model (e.g. this is used by Tensroflow Hub to restore their own Layer object). If you want to use the Keras APIs, load with `tf.keras.models.load_model`
