### ISSUE TITLE
when support tflite op: SparseFillEmptyRows

### ISSUE THREAD

**Issue by hellozmz** [tensorflow/tensorflow#40427]
why not support SparseFillEmptyRows in tflite, and when support?

**Comment by Saduf2019** [comment]
@hellozmz 
Please provide details on the mentioned requirement.

**Comment by hellozmz** [comment]
> @hellozmz
> Please provide details on the mentioned requirement.

now tf support op:SparseFillEmptyRows, but not support the op in tflite, so I want to know when can you support the op in tflite.

**Comment by jdduke** [comment]
Do you have a link to a model that requires this? Are you sure this is the only op that is needed? You can try using the following approach to integrate this op, though it will come at the cost of binary size: https://www.tensorflow.org/lite/guide/ops_select
