### ISSUE TITLE
Issue with tensorflow not being able to use my gpu after installing cuda and cuDNN

### ISSUE THREAD

**Issue by ZiZizou** [tensorflow/tensorflow#40437]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): used sudo pip3 install tensorflow-gpu and sudo pip3 install tensorflow to install both versions.
- TensorFlow version (use command below): 2.2.0
- Python version: 3.8.2
- CUDA: release 10.1
- cuDNN version: 7.6.5 
- GPU model and memory: Geoforce GTX - 1050

**Current behavior**

running the following code (to verify if I have completed all the steps correctly of installing cuda and cuDNN) - 
`from tensorflow.python.client import device_lib`
`print(device_lib.list_local_devices())`

currently the following error occurs - 
W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory

**Expected behavior**
Due to the above error, I am not able to let tensorflow use my gpu for machine learning purposes. I would like to rectify this error

Kindly help me solve this problem, and let me know if any further details are required from my side.

**Comment by grudloff** [comment]
hey, I resently installed cuda an cudnn in my machine (ubuntu 18.04) so maybe I can help you. Clearly there is some issue with your cudnn install. How did you install it?

**Comment by ZiZizou** [comment]
Installed cuda toolkit with the following command - 
`sudo apt install nvidia-cuda-toolkit`
Then I followed the steps on the nvidia website for cuDNN to install cuDNN 7.6.5 for cuda 10.1 from a tar file from the following link - 
https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html

**Comment by grudloff** [comment]
what does your terminal display if you run `nvidia-smi` ?

**Comment by ZiZizou** [comment]
nvidia - smi shows:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   40C    P3    N/A /  N/A |   1050MiB /  4040MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1073      G   /usr/lib/xorg/Xorg                            45MiB |
|    0      1674      G   /usr/lib/xorg/Xorg                           363MiB |
|    0      1930      G   /usr/bin/gnome-shell                         224MiB |
|    0      2301      C   /usr/lib/libreoffice/program/soffice.bin      45MiB |
|    0      3048      G   ...AAAAAAAAAAAACAAAAAAAAAA= --shared-files   179MiB |
|    0      4099      G   ...uest-channel-token=16056379025461602208   127MiB |
|    0     14258      G   ...quest-channel-token=7332220839678530975    49MiB |
+-----------------------------------------------------------------------------+


while nvcc --version shows - 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

**Comment by grudloff** [comment]
if you go to `/usr/local/` what `cuda-x.x` folder(s) do you see? ( you can do this with `cd /usr/local` and then 'ls')

**Comment by ZiZizou** [comment]
I don't have a /usr/local/cuda directory.
Rather I have a /usr/lib/cuda directory
does this mean something is wrong ?

**Comment by grudloff** [comment]
I don't think so, but you moved the cudnn files to `/usr/lib/cuda` then?

**Comment by ZiZizou** [comment]
yes

**Comment by grudloff** [comment]
Then you did that just fine, not really sure what the issue could be. The discrepancy between `nvidia-smi` and `nvcc --version` is odd though, but from what I read what `nvidia-smi` displays isn't necesarily true. 

Maybe you can try the deb alternativo of cudnn installation, don't forget to erase the previous files you moved to cuda. Also as a sanity check, that this is no tensorflow issue but rather a cudnn installation issue, you can do the verification process outlined in the link you provided above.

**Comment by ZiZizou** [comment]
I think the debian files are only for the ubuntu 18.04 and below. I do not want to risk ruining something on this version of ubuntu 20.04, but I will look at other methods. Thank you for your quick responses!

**Comment by grudloff** [comment]
No problem, good luck! I recommend you try to install cuda toolkit from some official nvidia source as `nvidia-cuda-toolkit` isn't made by nvidia and maybe it's incompatible with that cudnn installation method.

**Comment by amahendrakar** [comment]
@ZiZizou,
Please take a look at [this](https://github.com/tensorflow/tensorflow/issues/20271) similar issue and let us know if it helps. Thanks!

**Comment by ratansingh98** [comment]
> **System information**
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
> * TensorFlow installed from (source or binary): used sudo pip3 install tensorflow-gpu and sudo pip3 install tensorflow to install both versions.
> * TensorFlow version (use command below): 2.2.0
> * Python version: 3.8.2
> * CUDA: release 10.1
> * cuDNN version: 7.6.5
> * GPU model and memory: Geoforce GTX - 1050
> 
> **Current behavior**
> 
> running the following code (to verify if I have completed all the steps correctly of installing cuda and cuDNN) -
> `from tensorflow.python.client import device_lib`
> `print(device_lib.list_local_devices())`
> 
> currently the following error occurs -
> W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory
> 
> **Expected behavior**
> Due to the above error, I am not able to let tensorflow use my gpu for machine learning purposes. I would like to rectify this error
> 
> Kindly help me solve this problem, and let me know if any further details are required from my side.

To avoid complications, I would recommend you using anaconda.
You need to run this one line and it will create a tensorflow-gpu environment for you,
`conda create --name tf_gpu tensorflow-gpu `
