### ISSUE TITLE
tensorflow-gpu==1.13.1

### ISSUE THREAD

**Issue by alex-wey** [tensorflow/tensorflow#40439]
**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow version: 1.13.1
- Python version: 3.6.9
- Installed using: Miniconda3, pip3
- GPU model and memory: Google Colab

**Description of the problem**
 In order to run this python script, TensorFlow-GPU and TensorBoard both version 1.13.1 are required. According to the log, the second code block does run successfully - however, in reality, there seems to be an installation issue since a ModuleNotFoundError is prompted.

Some general assistance and explanation would be extremely helpful - perhaps there exists a direct link that can be used for these installations instead?

**Sequence of commands executed before running into the problem**
```bash
!wget -c https://repo.anaconda.com/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh
!chmod +x Miniconda3-4.5.4-Linux-x86_64.sh
!bash ./Miniconda3-4.5.4-Linux-x86_64.sh -b -f -p /usr/local
!conda install -q -y --prefix /usr/local python=3.6 ujson
import sys
sys.path.append('/usr/local/lib/python3.6/site-packages')
# test it
import ujson
```
```bash
!pip3 install tensorboard==1.13.1
!pip3 install tensorflow-gpu==1.13.1
```
**Unsuccessful command and traceback**
```bash
!conda create -y -n grover python=3.6 && source activate grover && pip3 install -r /content/drive/My\ Drive/CS/GPT-2/grover/requirements-gpu.txt
!python /content/drive/My\ Drive/CS/GPT-2/grover/download_model.py base
!PYTHONPATH=$(pwd) python /content/drive/My\ Drive/CS/GPT-2/grover/sample/contextual_generate.py -model_config_fn lm/configs/base.json -model_ckpt models/base/model.ckpt -metadata_fn sample/april2019_set_mini.jsonl -out_fn april2019_set_mini_out.jsonl
```
```
Traceback (most recent call last):
  File "/content/drive/My Drive/CS/GPT-2/grover/sample/contextual_generate.py", line 1, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
```

**Comment by Saduf2019** [comment]
@alex-wey 
Is there any specific reason you are trying to install TensorFlow 1.12?
TensorFlow 1.x is not actively supported, instead could you please install the latest version of TensorFlow i.e. v2.2 and let us know if you are facing the same issue.

Please refer to this [comment](https://github.com/tensorflow/tensorflow/issues/39937#issuecomment-635397756) and let us know if it helps.
For more information, please check this [installation guide.](https://www.tensorflow.org/install/pip#system-requirements) Thanks!

**Comment by mihaimaruseac** [comment]
Please switch to 1.15, 2.0, 2.1 or 2.2 (or nightly) as these are the only versions supported at this time.

**Comment by alex-wey** [comment]
> @alex-wey
> Is there any specific reason you are trying to install TensorFlow 1.12?
> TensorFlow 1.x is not actively supported, instead could you please install the latest version of TensorFlow i.e. v2.2 and let us know if you are facing the same issue.
> 
> Please refer to this [comment](https://github.com/tensorflow/tensorflow/issues/39937#issuecomment-635397756) and let us know if it helps.
> For more information, please check this [installation guide.](https://www.tensorflow.org/install/pip#system-requirements) Thanks!

Hi @Saduf2019,

I have tried using TensorFlow v2.2,

**Comment by KinWaiCheuk** [comment]
> @alex-wey Is there any specific reason you are trying to install TensorFlow 1.12? TensorFlow 1.x is not actively supported, instead could you please install the latest version of TensorFlow i.e. v2.2 and let us know if you are facing the same issue.
> 
> Please refer to this [comment](https://github.com/tensorflow/tensorflow/issues/39937#issuecomment-635397756) and let us know if it helps. For more information, please check this [installation guide.](https://www.tensorflow.org/install/pip#system-requirements) Thanks!

Hi, I also need to use tensorflow 1.12 to rerun one project that our group did few years ago. When using the latest version of TensorFlow, the result we get is different from what we reported before. Therefore, we would like to install tensorflow 1.12 to do debugging.
