### ISSUE TITLE
the document description  of tensorflow java api  is not detailed enough.

### ISSUE THREAD

**Issue by zhaojc001** [tensorflow/tensorflow#40430]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/MyMethod

### Clear description

For example, why should someone use this method? How is it useful?

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example?

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by Saduf2019** [comment]
@zhaojc001 
Please provide with details on why are you claiming there is an issue with the documentation

**Comment by zhaojc001** [comment]
Tensorflow's Java API does not specify how to use GPU acceleration. The following content is configured in maven, but it has no effect:
<dependency>
  <groupId>org.tensorflow</groupId>
  <artifactId>tensorflow</artifactId>
  <version>1.8.0</version>
</dependency>
<dependency>
  <groupId>org.tensorflow</groupId>
  <artifactId>libtensorflow</artifactId>
  <version>1.8.0</version>
</dependency>
<dependency>
  <groupId>org.tensorflow</groupId>
  <artifactId>libtensorflow_jni_gpu</artifactId>
  <version>1.8.0</version>
</dependency>

**Comment by zhaojc001** [comment]
Please tell me how maven is configured, how to set GPU in the code, and how to specify GPU number.

**Comment by zhaojc001** [comment]
Please give an example of Java tensorflow API using GPU acceleration, including Maven and code parts, such as image classification.

**Comment by Saduf2019** [comment]
@zhaojc001 
Please refer to [this link](https://medium.com/google-cloud/how-to-invoke-a-trained-tensorflow-model-from-java-programs-27ed5f4f502d) and let us know if it helps.
[Link1](https://eicweb.phy.anl.gov/EIC/tensorflow-for-eic/blob/9bd0e0e06874b558a07a7cb5ae87753bd17dd9d5/tensorflow/docs_src/install/install_java.md)
[Link1](https://www.inspirisys.com/objectdetection_in_tensorflowdemo.pdf)

**Comment by zhaojc001** [comment]
when i use maven project,i run java -jar target/tensorflow-test-1.0-SNAPSHOT.jar，it occurs the following error,please help me,how to solve it:
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/tensorflow_native_libraries-1592366046358-0/libtensorflow_jni.so: libtensorflow_framework.so.1: cannot open shared object file: No such file or directory

**Comment by MarkDaoust** [comment]
Hi, 

SIG-JVM is taking over a lot of TensorFlow's java work.

You can contact them them at: jvm@tensorflow.org 
Their repository is: https://github.com/tensorflow/java

They may be able to help more than me.
