### ISSUE TITLE
neural structured learning for NLP text classification

### ISSUE THREAD

**Issue by jazlielee** [tensorflow/tensorflow#40435]
I like the idea of neural structured learning, would like to use the adversarial concept on NLP. I'm using bidirection LSTM model to classify a text input and sequence of the words is important. I want it to be able to identify similarity of the sequence of text

can I used neural structured learning so that it can generate 'textual perturbation' for training purpose for the given sentence to increase the accuracy of prediction?

**Comment by TheNewSound** [comment]
This is not a question for the Tensorflow source code repository? More something for stackoverflow?

**Comment by jazlielee** [comment]
I'm not sure where to get support for 'how to' or feature question.

**Comment by ravikyram** [comment]
@jazlielee 

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!
