### ISSUE TITLE
Create a function to compute positive negative and neutral tweets. 

### ISSUE THREAD

**Issue by AasthaNagpal** [tensorflow/tensorflow#40444]
# Create a function to compute negative (-1), neutral (0) and positive (+1) analysis
def getAnalysis(score):
if score < 0:
  return 'Negative'
elif score == 0:
  return 'Neutral'
else:
  return 'Positive'
df['Analysis'] = df['Polarity'].apply(getAnalysis)
# Show the dataframe
df

This program doesn't creates analysis column.

**Comment by ravikyram** [comment]
@AasthaNagpal 

This issue is not related to Tensorflow.

This question is better asked on StackOverflow since it is not a bug or feature request related to Tensorflow. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!
