### ISSUE TITLE
add None 0-dimension to output tensor (tf2)

### ISSUE THREAD

**Issue by HoangTienDuc** [tensorflow/tensorflow#40440]
to get dynamic batch, i need to add None to below ouput tensor. 
```
out = tf.gather(decode_preds, selected_indices)
```
Can someone guide me?

**Comment by amahendrakar** [comment]
@HoangTienDuc,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!
