### ISSUE TITLE
Deploy an application with tensorflow

### ISSUE THREAD

**Issue by Lucysmith8** [tensorflow/tensorflow#40458]
**System information**
- windows 10:
- load_model and image
- TensorFlow 2.2
- Python 3.7
- Installed using pip

**Describe the problem**

I am trying to deploy an application on my local server using tensorflow. But I have a problem. In fact, I create an executable of my application by including tensorlfow, but impossible to include tensorflow since it tries to get modules in python \ lib \ sites-packages \ tensorflow, or I try to create an executable which will be distributed. Is there a tensorflow version that can be used for applications? How can I use tensorflow as a local module? I only need two modules (load_model and image).

Here is the error I encounter:

  [![error][1]][1]

  [1]: https://i.stack.imgur.com/M0Z6L.jpg

**Comment by gowthamkpr** [comment]
@Lucysmith8 What does
`How can I use tensorflow as a local module?` mean? Can you please elaborate. Thanks!

**Comment by Lucysmith8** [comment]
> @Lucysmith8 What does
> `How can I use tensorflow as a local module?` mean? Can you please elaborate. Thanks!

In fact, what I would like to do. It's using tensorflow.keras.models without importing tensorflow. Transfer this package to another folder and use it. @gowthamkpr

**Comment by gowthamkpr** [comment]
@Lucysmith8 I am afraid to say that you cant do that. You definitely have to import tensorflow.

**Comment by Lucysmith8** [comment]
> @Lucysmith8 I am afraid to say that you cant do that. You definitely have to import tensorflow.

You know how I can solve the problem with the path?

**Comment by Lucysmith8** [comment]
He found the solution. But instead of sharing, he closed his question and he didn't answer anyone. https://github.com/anthony-tuininga/cx_Freeze/issues/514
