### ISSUE TITLE
model.fit() is 10% slower over custom training loops when using TPUs

### ISSUE THREAD

**Issue by bjourne** [tensorflow/tensorflow#40453]
I've created two training loops for training models on TPUs. One using the model.fit() method and one using a custom training loop based on information I've found in various notebooks.

The custom training loop consistently beats model.fit() by 10-15%.

Some overhead for using model.fit() over custom code is of course acceptable but 10-15% seem excessive. Maybe there's a bug somewhere?

Here are the relevant parts of my custom training loop:

```python
class LossAccObserver:
    def __init__(self):
        self.loss = metrics.SparseCategoricalCrossentropy()
        self.acc = metrics.SparseCategoricalAccuracy()
    def reset(self):
        self.loss.reset_states()
        self.acc.reset_states()
    def update(self, y, y_hat):
        self.loss.update_state(y, y_hat)
        self.acc.update_state(y, y_hat)

def compute_and_apply_gradients(model, x, y):
    with tf.GradientTape() as tape:
        y_hat = model(x, training = True)
        loss = model.compiled_loss(y, y_hat,
                                   regularization_losses = model.losses)
    vars = model.trainable_variables
    grads = tape.gradient(loss, vars)
    grads = [tf.clip_by_norm(g, 0.5) for g in grads]
    model.optimizer.apply_gradients(zip(grads, vars))
    return y_hat

@tf.function
def train_epoch(model, strategy, batch_size, dataset, obs):
    def step_fn(x, y):
        y_hat = compute_and_apply_gradients(model, x, y)
        obs.update(y, y_hat)
    for x, y in dataset:
        strategy.run(step_fn, args = (x, y))

@tf.function
def evaluate_epoch(model, strategy, dataset, obs):
    def step_fn(x, y):
        y_hat = model(x, training = False)
        obs.update(y, y_hat)
    for x, y in dataset:
        strategy.run(step_fn, args = (x, y))

def manual_training(model, strategy, train, valid, batch_size, epochs):
    with strategy.scope():
        train_obs = LossAccObserver()
        valid_obs = LossAccObserver()
    ...
    for i in range(epochs):
        ...
        train_epoch(model, strategy, batch_size, train, train_obs)
        evaluate_epoch(model, strategy, valid, valid_obs)
        ...
```
Here is my model.fit() training code:
```python
class MyModel(Model):
    def train_step(self, data):
        x, y = data
        y_hat = compute_and_apply_gradients(self, x, y)
        self.compiled_metrics.update_state(y, y_hat)
        return {m.name: m.result() for m in self.metrics}

def automatic_training(model, train, valid, batch_size, epochs):
    ...
    model.fit(x = train, validation_data = valid,
              epochs = epochs,
              verbose = 2)
```

**Comment by ravikyram** [comment]
@bjourne 

Can you please share colab link or complete code snippet to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by bjourne** [comment]
Sure! Here is my code: https://github.com/bjourne/python3-libs/blob/master/programs/char_lm_tf.py

**Comment by ravikyram** [comment]
@bjourne 

I have tried in colab with TF version 2.2 and  i am seeing the below error message(`ModuleNotFoundError: No module named 'observations'`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/5c0d2e9e5b178e3a8151ea015411afa1/untitled24.ipynb).Thanks!

**Comment by bjourne** [comment]
It's a dependency. You need to `pip install observations docopt` to be able to run the code.

**Comment by ravikyram** [comment]
@bjourne 

I tried again in colab with your suggestion and i am seeing new error message.(`DocoptLanguageError: "usage:" (case-insensitive) not found.`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/7a7a1493ff7ded74db66c9444328b8ee/untitled975.ipynb).Thanks!

**Comment by bjourne** [comment]
You have not copied the docstring correctly. You could also modify the main function to hard code the parameters I'm reading from the command line.

**Comment by gowthamkpr** [comment]
@bjourne Can you please hardcode the parameters and share the working gist with us. Thanks!

**Comment by bjourne** [comment]
https://gist.github.com/bjourne/486bad6b28320735c2283f03facd4a99

**Comment by rjpower** [comment]
There are some known inefficiencies in how the model.fit training loop works, in particular around how metrics are calculated.

These are being worked on, but for the time being a small performance loss should be expected.

**Comment by rxsang** [comment]
HI Bjorn,

If you are using `model.fit`, there is an `experimental_steps_per_execution` argument you can tune in `model.compile` https://www.tensorflow.org/api_docs/python/tf/keras/Model?version=nightly#compile. Setting to a higher number (like your epoch size) should help the performance.

**Comment by goldiegadde** [comment]
@bjourne were you able to rerun with `experimental_steps_per_execution` as noted above by rxsang@. 
Please let us know if that helped and if we can go ahead and close the issue! Thanks
