### ISSUE TITLE
passing labels=None to image_dataset_from_directory doesn't work

### ISSUE THREAD

**Issue by mulka** [tensorflow/tensorflow#40462]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS
- TensorFlow installed from (source or binary): tf-nightly
- TensorFlow version (use command below): v1.12.1-34068-g9a70ab8813 2.3.0-dev20200614
- Python version: 3.7.7

**Describe the current behavior**
Gives an error:
ValueError: `labels` argument should be a list/tuple of integer labels, of the same size as the number of image files in the target directory. If you wish to infer the labels from the subdirectory names in the target directory, pass `labels="inferred"`. If you wish to get a dataset that only contains images (no labels), pass `labels=None`.

**Describe the expected behavior**
Should return a dataset hat only contains images (like the error message says)

**Standalone code to reproduce the issue**

```
import tensorflow as tf

train_images = tf.keras.preprocessing.image_dataset_from_directory(
    'images',
    labels=None,
)
```

**Other info / logs** 

```
Traceback (most recent call last):
  File "train.py", line 5, in <module>
    labels=None,
  File "/opt/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/keras/preprocessing/image_dataset.py", line 145, in image_dataset_from_directory
    '`labels` argument should be a list/tuple of integer labels, of '
ValueError: `labels` argument should be a list/tuple of integer labels, of the same size as the number of image files in the target directory. If you wish to infer the labels from the subdirectory names in the target directory, pass `labels="inferred"`. If you wish to get a dataset that only contains images (no labels), pass `labels=None`.
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/4bb0f4d2439bbc4efc2e9d53a7ce6e4d/40462.ipynb). Thanks!

**Comment by ymodak** [comment]
Perhaps you can use `label_mode` arg to achieve this.
```python
train_images = tf.keras.preprocessing.image_dataset_from_directory(
                 '/content/cats_and_dogs_filtered/train',
                  label_mode = None)
```

**Comment by mulka** [comment]
@ymodak I think that's the right way to do it, but would also be nice if labels=None worked, or at least if the error message that comes up tells you the right way to do it. Right now it says "If you wish to get a dataset that only contains images (no labels), pass `labels=None`" which doesn't work.

**Comment by gowthamkpr** [comment]
@mulka Agreed. As the error message suggests

> ValueError: `labels` argument should be a list/tuple of integer labels, of the same size as the number of image files in the target directory. If you wish to infer the labels from the subdirectory names in the target directory, pass `labels="inferred"`. If you wish to get a dataset that only contains images (no labels), pass `labels=None`.

As the error message suggests, passing `labels=None` as an argument should work but its not in this case.

**Comment by ymodak** [comment]
This is fixed with the latest tf-nightly. The error message has been updated to,
```python
. . . If you wish to get a dataset that only contains images (no labels), pass `labels_mode=None`.
```
Thanks!

**Comment by mulka** [comment]
It looks like label_mode has been misspelled as labels_mode.

**Comment by ymodak** [comment]
Ahh.. I see.. thanks for pointing that out.
Will fix it now.

**Comment by phrasenmaeher** [comment]
> 

I've also noticed this, it's still prevalent in TF2.8. To get around this, I have moved the images into an a subdirectory with the name 1, which will later be interpreted as the label of all images.
Then, alter the function call as follows:

```
train_ds = (
    tf.keras.preprocessing.image_dataset_from_directory(
        directory="path/to/dir/", # <-- note, it does not directly point to the '1' folder, but to its parent
        image_size=image_size,
        validation_split=0.3,
        subset="training",
        seed=1337,
    )
    .map(lambda x, y: x) # manually remove the faulty label
```
