### ISSUE TITLE
Tensorflow 2.2.0 import error - DLL load failed

### ISSUE THREAD

**Issue by saharatech** [tensorflow/tensorflow#40461]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro [Version 10.0.19041.264]
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): pip install
- TensorFlow version: 2.2.0
- Python version: 3.6.8 (issue also occurs with 3.7.7 and 3.8.3)
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
I get the error that I'm missing some dynamic libraries when I try to import tensorflow after installing it. In the error message it is suggested that I download certain C++ dlls from visual studio. I did that and it still didn't work. I also downloaded visual studio code and the same problem persisted. Please note: the error message attached below also occurred with only tensorflow installed, with only tensorflow and tensorflow-gpu installed and finally, with all 3 (tensorflow, tensorflow-gpu, and tensorflow-cpu) installed.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
pip install tensorflow
pip install tensorflow-gpu
pip install tensorflow-cpu
python
>>import tensorflow

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

[tensorflow import error log.txt](https://github.com/tensorflow/tensorflow/files/4777264/tensorflow.import.error.log.txt)

**Comment by Saduf2019** [comment]
@saharatech 
Please go through [this comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) and [this issue](#33348) and let us know if it helps.
[Link](https://github.com/tensorflow/tensorflow/issues/39423#issuecomment-628957625)

**Comment by saharatech** [comment]
@Saduf2019 
Yes, that helped, thank you very much. My CPU does not support AVX2. I will try building TensorFlow from source. Please feel free to close this issue.

**Comment by Saduf2019** [comment]
@saharatech
Glad you were able to resolve the issue, hence moving it to closed status.
