### ISSUE TITLE
Tensorflow Lite subtraction in TOCO quantized model takes longer than all the convolutions in a MobileNet v3 model

### ISSUE THREAD

**Issue by msalvaris** [tensorflow/tensorflow#40469]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu/ARM
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2
- Python version:3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: 

**Describe the current behavior**
Created MobileNet v3 model that includes subtraction and multiplication for normalization in the graph. Quantized the model with TOCO using post training quantization. Model was running very slow on ARM and x86. Profiling shows suctraction is responsible for 21% of the time
![image](https://user-images.githubusercontent.com/6794993/84648998-b2538b80-aefd-11ea-8407-36839ea175cf.png)

Using MLIR produces much more reasonable results
![image](https://user-images.githubusercontent.com/6794993/84649672-d499d900-aefe-11ea-9324-9cde5fd5c0ce.png)

**Describe the expected behavior**
Latency due to subtraction should be negligible

Can supply model and other info if necessary

**Comment by renjie-liu** [comment]
hi, quantized Sub is not optimized yet.

**Comment by msalvaris** [comment]
Thanks for the update. Is there a timeline for this?

**Comment by renjie-liu** [comment]
can you share your model for testing?

thanks

**Comment by msalvaris** [comment]
Unfortunately it looks like not in a public forum like this. Happy to share privately

**Comment by renjie-liu** [comment]
what's your sub's config? shape? datatype?

thanks

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Comment by sushreebarsa** [comment]
@msalvaris Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!
