### ISSUE TITLE
Equal function forgets static shape in graph-mode in tensorflow 2.1 and 2.2

### ISSUE THREAD

**Issue by PistaSaki** [tensorflow/tensorflow#40471]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Microsoft Windows 10 Enterprise
- TensorFlow installed from (source or binary): official pipy wheel
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.7.6

**Describe the current behavior**
In graph-mode when `x.shape == [None, 10, 1]`, `y.shape == [None, 1, 4]` then one would expect `(x==y).shape` to be `[None, 10, 4]`. This really works in tensorflow 2.0. In tensorflow 2.1 and 2.2 it is a completely undefined shape.

**Describe the expected behavior**
The same behaviour as in tensorflow 2.0.

**Standalone code to reproduce the issue**
```python
import tensorflow as tf

@tf.function(input_signature=[tf.TensorSpec([None, 10, 1]), tf.TensorSpec([None, 1, 4])])
def fun(x, y):
    z = x == y
    tf.print("z.shape =", z.shape)
    return z

fun(tf.ones([5, 10, 1]), tf.ones([5, 1, 4]));
```
In tensorflow 2.0, this code prints `z.shape = TensorShape([None, 10, 4])`.
In tensorflow 2.2 and 2.1, this code prints `z.shape = TensorShape(None)`.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.1, 2.2 and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/cf487e179e38859d2301e11969b41bbb/untitled25.ipynb).Thanks!

**Comment by yongtang** [comment]
Added a PR #40480 for the fix.
