### ISSUE TITLE
Using own dataset in microspeech project doesn't work 

### ISSUE THREAD

**Issue by eeesi** [tensorflow/tensorflow#40470]
@tensorflow/micro

**System information**

- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): currently working with Google Colab 
- TensorFlow installed from (source or binary):
- Tensorflow version (commit SHA if source): Tensorflow 1.x
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Arduino Nano 33 BLE Sense

**Describe the problem**

Hello everyone, 

I just started to get into the world of machine learning and deep learning and I still need to learn a lot, but I hope that there might be someone who faced similar problems to the ones that I try to solve at the moment. 

A few weeks ago, I started working with the microspeech example for microcontrollers. My goal was (and still is) to get the project working with an own wake word. To save time, I decided to expand the speech commands dataset with a folder containing my own data. My wanted wake word is a german one (I'm not sure if this is an important information but I try to tell as much information as possible at the moment). 

At first, I only used samples of my own voice. To get more samples in a short time, I combined the original recordings with ones that were slightly manipulated. 
After that, I uploaded my data to Google Drive so that I could import it to Colab. I changed the 'wanted word' section and the 'data_dir' section according to my wanted word. 

Training seemed to work well and I changed the code in the microspeech project in the Arduino IDE and uploaded it to the Arduino. I expected the green LED to flash when I say the wake word and the blue one to do so if I say some other word of the dataset (as it is intended in the original project). But no matter what I said, only the blue one LED flashed. 

In a second step, I changed my dataset because I thought that it might be a problem that my dataset only consists of recordings of my own voice. So I collected new data with recordings from different people and tried everything that I did before with my new data. 
This time the arduino behaves a bit different as the green LED flashes randomly when nothing is said at all. And when I say my wake word, the blue LED is still flashing as it did before. 

As I said at the beginning, I'm new to this topic and so I only can imagine some possible causes for my issues (please feel free to correct me if some things don't make sense):

- I didn't collect enough samples of my wake word (at the moment there are 820 samples in the folder)
- there might be a problem that I only want to detect one word instead of two or more
- I forgot to change sth. in the Arduino project code or did sth. wrong
- it could be a problem that my dataset is a mix of English and German words 

**Please provide the exact sequence of commands/steps when you ran into the problem**

After training, I copy the code and paste it into the _micro_features_tiny_conv_micro_features_model_data.cpp_ and I also correct the data length parameter at the end of the source file. 

Then, I change _micro_features_micro_model_settings.cpp_ and _micro_features_micro_model_settings.h_ according to my wake word and the number of labels that I've got. 

Finally I go to the _arduino_command_responder.cpp_ and change the first if condition to **if(found_command[0] == 'h')**, as the wake word begins with an h. I erase the second if condition because I don't have a second wake word. 

Then I upload the project to the arduino. 

If there are any information missing please tell me and I will provide them.

Kind regards, 
eeesi

**Comment by jaredpb** [comment]
Hi eeesi, the issue is the Tensorflow Lite library for Arduino is not compatible with the models produced by newly updated Google Collab code. A "fix" is to download the Tensorflow repository and run test_arduino.sh to create an up to date zip library to import into the Arduino IDE. I put fix in parentheses because while it does detect audio the inference runs too slow with the example micro speech code which causes issues. As of right now this seems to be an ongoing issue the Tensorflow Lite team has not addressed so I am glad more people are bringing it to attention here.

**Comment by askemottelson** [comment]
Anyone found a solution to this issue? I tried the same as @eeesi, but cannot get the Arduino code to work with an updated model trained using the Colab code

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.
