### ISSUE TITLE
How to use sliding_window_batch in TF 2.2.0

### ISSUE THREAD

**Issue by santoshreddy254** [tensorflow/tensorflow#40481]
How to use tf.contrib.data.sliding_window_batch in tf 2.2.0

**Comment by amahendrakar** [comment]
@santoshreddy254,
`tf.contrib` has been deprecated from TensorFlow 2.x.

Instead, please take a look at the [window method](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#window) from `tf.data.Dataset` and let us know if it works. Thanks!

**Comment by masip85** [comment]
Window method from tf.data.Dataset cannot be integrated as a tf transformation inside tfx. I think is relevant.
