### ISSUE TITLE
tfcompile for non-x86-64 CPU

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#40487]
Are there possibilities to cross-compile with `tfcompile` for other architectures (aarch64, CortexM, etc..)?

**Comment by tilakrayal** [comment]
@peter197321,
Have you got the chance to have a look at this tfcompile.bzl file where it was mentioned that the below are the **aarch64** architectures provided. 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/aot/tfcompile.bzl

```
      "//tensorflow:android_arm64": "aarch64-none-android",
        "//tensorflow:android_x86": "i686-none-android",
        "//tensorflow:ios": "arm64-none-ios",
        "//tensorflow:ios_x86_64": "x86_64-apple-ios",
        "//tensorflow:linux_ppc64le": "ppc64le-ibm-linux-gnu",
        "//tensorflow:linux_aarch64": "aarch64-none-linux-gnu",
        "//tensorflow:macos_x86_64": "x86_64-none-darwin",
        "//tensorflow:macos_arm64": "aarch64-none-darwin"
```

Thank you!
