### ISSUE TITLE
Compute Capability 3.0 not working with latest docker builds

### ISSUE THREAD

**Issue by tetmin** [tensorflow/tensorflow#4048]
Using the most recent docker image 'tensorflow/tensorflow:nightly-devel-gpu' doesn't work on AWS EC2 anymore, it results in the below error:

Ignoring gpu device (device: 0, name: GRID K520, pci bus id: 0000:00:03.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.

**Comment by msevrens** [comment]
Building from scratch yesterday had no issues on AWS. If this is the plan moving forward though thats ridiculous. Tf needs to be able to run on AWS.

**Comment by tetmin** [comment]
Thanks, building Dockerfile.gpu from scratch now, will report back.

**Comment by tetmin** [comment]
I got further this time but now have the following error:

Loaded runtime CuDNN library: 5103 (compatibility version 5100) but source was compiled with 4007 (compatibility version 4000).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.

**Comment by msevrens** [comment]
Yeah, you do need to update CuDNN.

https://developer.nvidia.com/compute/machine-learning/cudnn/secure/v5.1/prod/7.5/cudnn-7.5-linux-x64-v5.1-tgz

**Comment by vrv** [comment]
I think the cuda auto configuration change had a bug that didn't properly propagate the cuda capabilities env variable, but we cherry-picked that into r0.10 in https://github.com/tensorflow/tensorflow/commit/761e6de4357786bee049e63e227b03d57f18bab0

so hopefully the latest nightly build has that in and it should work.

**Comment by chenliu0831** [comment]
Is there an official image built with the CUDA compute 3.0 support? It's weird the CI build image in the repo has the `TF_CUDA_COMPUTE_CAPABILITIES 3.0,5.2` but not for those in `tools/docker`

**Comment by chenliu0831** [comment]
@martinwicke Thanks. I'll try the binary one. Just submit a tiny PR [#4301](https://github.com/tensorflow/tensorflow/pull/4301) adding the env in devel-gpu.

**Comment by caisq** [comment]
The PR referred to above should have addressed this issue. This should have been reflected in the latest* and nightly* tags on gcr.io and Docker Hub now. Please re-open this issue if there are any remaining problems. Thanks.
