### ISSUE TITLE
Bug in tf.strings.split vs tf.compat.v1.string_split

### ISSUE THREAD

**Issue by tommywei110** [tensorflow/tensorflow#40484]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installed from (source or binary): Colab
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6.9

**Describe the current behavior**
tf.strings.split doesn't work as expected when the seperator is multiple characters.
**Describe the expected behavior**
tf.strings.split().to_sparse() should have the exact same behavior as tf.compat.v1.string_split()
yet when multiple characters are provided, tf.strings.split doesn't work

**Standalone code to reproduce the issue**
[github gist](https://gist.github.com/tommywei110/85328711e3cf1c0544fb4aca14bda37b)

`import tensorflow as tf`
`sentence = tf.constant([['cat goes meow'], ['dog?goes!woof']])`
`print(sentence)`
`v2 = tf.strings.split(sentence,' !?').to_sparse()`
`print(v2)`
`v1 = tf.compat.v1.string_split(tf.reshape(sentence, [-1]), ' !?')`
`print(v1)`

**Comment by yongtang** [comment]
@tommywei110 Since TF 2.0+, the behavior of `tf.strings.split` has been adjusted to match the behavior of python's native split, i.e., 
```
>>> 'cat goes meow'.split(' !?')
['cat goes meow']
>>> 'cat goes meow'.split(' ')
['cat', 'goes', 'meow']
>>> 
```

For that the behavior of `tf.strings.split` is expected.

**Comment by Saduf2019** [comment]
@tommywei110
Please update as per above comment

**Comment by tommywei110** [comment]
I see how this complies with python's string split.
But on the other hand, I wish there's a clearer indication in the documentation to talk about this upgrade from v1.
And from the usability standpoint, the equivalent of splitting on multiple characters by v1.string_split would be harder for the v2 strings.split to accomplish. In the python equivalent, I would have to use re.split.
Is there any work to support this funtionaility?

**Comment by edloper** [comment]
tf.text has a "regex_split" operation.

```
!pip install tensorflow-text
import tensorflow as tf
import tensorflow_text as tf_text
tf_text.regex_split("dog?goes!woof", "[!?]")
```

**Comment by gowthamkpr** [comment]
@tommywei110 Can I go ahead and close this issue as the issue has been resolved? Thanks!

**Comment by tommywei110** [comment]
Thanks for the swift response from the team.
