### ISSUE TITLE
tf-nightly build spits out thousands of lines about "whitelisting" during training

### ISSUE THREAD

**Issue by adrian-dalessandro** [tensorflow/tensorflow#40494]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2
- Python version: 3.6.2
- CUDA/cuDNN version: release 10.0, V10.0.130
- GPU model and memory: TITAN X

**Describe the current behavior**
I am attempting to train a model using the tf-nightly build using the tf.data.Dataset api. It works (and continues to train) but prints out thousands (if not hundreds of thousands) of lines about "whitelisting" parameters.

**Other info / logs**
This is an example of what it's printing out:

I0615 19:58:57.821352 140192954160896 ag_logging.py:140] Whitelisted <function OptimizerV2._distributed_apply.<locals>.apply_grad_t
o_update_var at 0x7f80b7957620>: from cache
Whitelisted <function OptimizerV2._distributed_apply.<locals>.apply_grad_to_update_var at 0x7f80b7957620>: from cache
I0615 19:58:57.822939 140192954160896 ag_logging.py:140] Converted call: <function OptimizerV2._distributed_apply.<locals>.apply_gr
ad_to_update_var at 0x7f80b7957620>
    args: (<tf.Variable 'conv4_block11_1_bn/gamma:0' shape=(256,) dtype=float32>, <tf.Tensor 'gradient_tape/resnet152v2/conv4_block
11_1_bn/FusedBatchNormGradV3:1' shape=(256,) dtype=float32>)
    kwargs: {}

Converted call: <function OptimizerV2._distributed_apply.<locals>.apply_grad_to_update_var at 0x7f80b7957620>
    args: (<tf.Variable 'conv4_block11_1_bn/gamma:0' shape=(256,) dtype=float32>, <tf.Tensor 'gradient_tape/resnet152v2/conv4_block
11_1_bn/FusedBatchNormGradV3:1' shape=(256,) dtype=float32>)
    kwargs: {}

I0615 19:58:57.823056 140192954160896 ag_logging.py:140] Whitelisted <function OptimizerV2._distributed_apply.<locals>.apply_grad_t
o_update_var at 0x7f80b7957620>: from cache
Whitelisted <function OptimizerV2._distributed_apply.<locals>.apply_grad_to_update_var at 0x7f80b7957620>: from cache
I0615 19:58:57.824649 140192954160896 ag_logging.py:140] Converted call: <function OptimizerV2._distributed_apply.<locals>.apply_gr
ad_to_update_var at 0x7f80b7957620>
    args: (<tf.Variable 'conv4_block11_1_bn/beta:0' shape=(256,) dtype=float32>, <tf.Tensor 'gradient_tape/resnet152v2/conv4_block1
1_1_bn/FusedBatchNormGradV3:2' shape=(256,) dtype=float32>)
    kwargs: {}

Converted call: <function OptimizerV2._distributed_apply.<locals>.apply_grad_to_update_var at 0x7f80b7957620>
    args: (<tf.Variable 'conv4_block11_1_bn/beta:0' shape=(256,) dtype=float32>, <tf.Tensor 'gradient_tape/resnet152v2/conv4_block1
1_1_bn/FusedBatchNormGradV3:2' shape=(256,) dtype=float32>)
    kwargs: {}

I0615 19:58:57.824765 140192954160896 ag_logging.py:140] Whitelisted <function OptimizerV2._distributed_apply.<locals>.apply_grad_t
o_update_var at 0x7f80b7957620>: from cache
Whitelisted <function OptimizerV2._distributed_apply.<locals>.apply_grad_to_update_var at 0x7f80b7957620>: from cache
I0615 19:58:57.826352 140192954160896 ag_logging.py:140] Converted call: <function OptimizerV2._distributed_apply.<locals>.apply_gr
ad_to_update_var at 0x7f80b7957620>
    args: (<tf.Variable 'conv4_block11_2_conv/kernel:0' shape=(3, 3, 256, 256) dtype=float32>, <tf.Tensor 'gradient_tape/resnet152v
2/conv4_block11_2_conv/Conv2DBackpropFilter:0' shape=(3, 3, 256, 256) dtype=float32>)
    kwargs: {}

Converted call: <function OptimizerV2._distributed_apply.<locals>.apply_grad_to_update_var at 0x7f80b7957620>
    args: (<tf.Variable 'conv4_block11_2_conv/kernel:0' shape=(3, 3, 256, 256) dtype=float32>, <tf.Tensor 'gradient_tape/resnet152v
2/conv4_block11_2_conv/Conv2DBackpropFilter:0' shape=(3, 3, 256, 256) dtype=float32>)
    kwargs: {}

**Comment by Saduf2019** [comment]
@adrian-dalessandro 
Can you please share a simple stand alone code for us to replicate the issue faced or if possible share a colab gist for us to analyse the issue.
