### ISSUE TITLE
Tensorflow 2.0 converter.experimental_new_converter = True still giving 'str' object has no attribute 'call'

### ISSUE THREAD

**Issue by JacobOfCorns** [tensorflow/tensorflow#40499]
**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow installed from (source or binary): pip
- TensorFlow version (or github SHA if from source): tensorflow 2.2.0

**Command used to run the converter or code if you’re using the Python API**

```
converter = tf.lite.TFLiteConverter.from_keras_model(keras_file)
converter.experimental_new_converter = True
tflite_model = converter.convert()
open("linear.tflite", "wb").write(tflite_model)
```

**The output from the converter invocation**

```
AttributeError                            Traceback (most recent call last)
<ipython-input-12-b0b66b38a77c> in <module>
----> 1 converter = tf.lite.TFLiteConverter.from_keras_model(keras_file)
      2 converter.experimental_new_converter = True
      3 tflite_model = converter.convert()
      4 open("linear.tflite", "wb").write(tflite_model)

c:\python\python38\lib\site-packages\tensorflow\lite\python\lite.py in from_keras_model(cls, model)
    426     # to None.
    427     # Once we have better support for dynamic shapes, we can remove this.
--> 428     if not isinstance(model.call, _def_function.Function):
    429       # Pass `keep_original_batch_size=True` will ensure that we get an input
    430       # signature including the batch dimension specified by the user.

AttributeError: 'str' object has no attribute 'call'

```

(https://github.com/tensorflow/tensorflow/issues/32693)
I referred to this previous forum for the same error and saw one of the solutions was to use the 'experimental_new_converter = True' function but I'm still getting the same error. I would reopen the mentioned forum if I could but I'm not sure how.

**Comment by abattery** [comment]
@JacobOfCorns

Hi, I think you need to use the following converter API since `from_keras_model_file` accepts the keras file while `from_keras_model` accepts the keras model instance.

```
converter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file(keras_file)
converter.experimental_new_converter = True
tflite_model = converter.convert()
open("linear.tflite", "wb").write(tflite_model)
```

**Comment by JacobOfCorns** [comment]
It works!! you are amazing thank you so much!

> @JacobOfCorns
> 
> Hi, I think you need to use the following converter API since `from_keras_model_file` accepts a keras file path while `from_keras_model` accepts a keras model instance.
> 
> ```
> converter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file(keras_file)
> converter.experimental_new_converter = True
> tflite_model = converter.convert()
> open("linear.tflite", "wb").write(tflite_model)
> ```
