### ISSUE TITLE
tf.GatherV2 is always not support 

### ISSUE THREAD

**Issue by sunzhe09** [tensorflow/tensorflow#40498]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):18.04
- TensorFlow installed from (source or binary):pip
- TensorFlow version (or github SHA if from source):
2.2

**Provide the text output from tflite_convert**
tflite_convert   --from_keras_model
```
# Copy and paste here
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**
tf.gatherV2 op is neither a custom op nor a flex op
Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

my use case is  tf.gather(params.index,batch_dims=1)

**Comment by abattery** [comment]
@sunzhe09 could you use conversion with flex?
https://www.tensorflow.org/lite/guide/ops_select

**Comment by sunzhe09** [comment]
@abattery I want to run on android,the   flexop is not support

**Comment by abattery** [comment]
@sunzhe09 Actually you can run with `org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly` aar. If you have concern about the binary size requirement, @thaink can help you in that area.

**Comment by sunzhe09** [comment]
@abattery thx! besides, if I want to post train quant my model ,what should I do? @thaink  can you help me?

**Comment by abattery** [comment]
For the post-quantization training, you can just use the following option during conversion.
FYI, https://www.tensorflow.org/lite/performance/post_training_quantization#dynamic_range_quantization

```
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_quant_model = converter.convert()
```

**Comment by sunzhe09** [comment]
in fact，my use case  is full quant :
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
def representative_dataset_gen():
  for _ in range(num_calibration_steps):
    # Get sample input data as a numpy array in a method of your choosing.
    yield [input]
converter.representative_dataset = representative_dataset_gen
tflite_quant_model = converter.convert()
is this mode support with flexop ?

**Comment by abattery** [comment]
As far as I know, the mode will be supported with the flex op. If you have any issues with it, please let us know.

**Comment by thaink** [comment]
We haven't have an official guide to do the selective build to save binary size yet. But if you want to do that, please let me know.

**Comment by sunzhe09** [comment]
@abattery I found it can't  use with tf.lite.OpsSet.TFLITE_BUILTINS_INT8 and tf.lite.OpsSet.SELECT_TF_OPS  ,it  will  get  an error  with "tf.GatherV2 op is neither a custom op nor a flex op"   ,but with  tf.lite.OpsSet.TFLITE_BUILTIN and tf.lite.OpsSet.SELECT_TF_OPS   it will   pass

**Comment by abattery** [comment]
I see. Thanks for reporting the issue. Will take a look at the issue.

**Comment by mohantym** [comment]
Hi @sunzhe09 !
We are checking to see whether you still need help in this issue . tf.GatherV2 is supported through [select ops allow list](https://www.tensorflow.org/lite/guide/op_select_allowlist#:~:text=raw_ops.GatherNd-,raw_ops.GatherV2,-raw_ops.GetSessionHandle) now.  After following[ select ops syntax](https://www.tensorflow.org/lite/guide/ops_select#convert_a_model) during model-TF lite conversion . You can use[ Android-aar ](https://www.tensorflow.org/lite/guide/ops_select#android_aar)documentation to enable select ops run time in android.

Thank you!
