### ISSUE TITLE
gcc-4.8.1 wouldn't compile matrix_inverse_op.cc

### ISSUE THREAD

**Issue by azzolini** [tensorflow/tensorflow#405]
gcc-4.8.1 didn't like the way 'using' was used. This patch fixed the issue for me.

[using_typename.txt](https://github.com/tensorflow/tensorflow/files/51293/using_typename.txt)

**Comment by vrv** [comment]
Do you want to follow our [contributing](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md) guidelines and send us a request via Gerrit, or would you rather us make the change for you?

**Comment by azzolini** [comment]
Since it's a simple change, if you guys can do it it would be awesome. Meanwhile I'll check on the guidelines for further contribution. Thanks!

**Comment by girving** [comment]
I'll apply it now.  Thanks!

**Comment by girving** [comment]
@azzolini: To satisfy my curiosity, what was the error message?  Also, it's useful to include the full error message for this kind of issue.

**Comment by girving** [comment]
In review.
