### ISSUE TITLE
Android-PoseNet is not accurate when person is laying down

### ISSUE THREAD

**Issue by ArtanBerisha1** [tensorflow/tensorflow#40503]
I am running PoseNet on mobile and saw that when the person is laying down the model can't detect the legs of the person, does this is something that is happening only to me or is a general problem. If so is there any way I can improve the accuracy of PoseNet ?

- Running on mobile device: Xiaomi MI A2 (the speed was around 100ms, but I also tried on another device with Qualcomm 835 which had better speed but not improvement on accuracy)

-Also why its so unstable, I mean I stay in one place and points keep changing places 

-Can it work better on black and white frames ?

**Comment by murtuza07** [comment]
Hi,

I'm facing the same issue as well. What's a possible solution for this. 

Thank you!

**Comment by mariem1992** [comment]
Hi, Same problem here, any solution found?? @ArtanBerisha1 ??

**Comment by ArtanBerisha1** [comment]
Hi, not yet on PoseNet, but I also tried the Google ML Kit Pose Detection model and is better than PoseNet.
I hope it helps @mariem1992

**Comment by sushreebarsa** [comment]
@ArtanBerisha1 Could you please let us know if this is still an issue ?Thanks!

**Comment by ArtanBerisha1** [comment]
Hi @sushreebarsa , 
I didn't replace the .tflite so I guess this is still an issue, if there is newer .tflite model let me know so I can give it a try and test it.

Thank you!

**Comment by sushreebarsa** [comment]
@ArtanBerisha1 Could you please refer to the [examples here](https://www.tensorflow.org/lite/examples/pose_estimation/overview) and try with the latest TF v2.7.0 ? please let us know if it helps?  Thank you!

**Comment by ArtanBerisha1** [comment]
Hi @sushreebarsa ,
Thank you, I was already trying those models but I found them in TF Hub page searching for skeleton models (didn't see that the pose estimation page was updated ). These models are more accurate, but I have a question, can we train these models even more or not ?
