### ISSUE TITLE
Possible improvement in documentation

### ISSUE THREAD

**Issue by zplizzi** [tensorflow/tensorflow#4050]
I'm following the documentation [here](https://www.tensorflow.org/versions/r0.10/how_tos/adding_an_op/index.html#compiling_the_kernel_for_the_gpu_device). Specifically, I find that running the second command in the code block of the section "Compiling the kernel for the GPU device" returns a linker error complaining about the lack of the `lcudart` library. I have solved this issue by adding the option `-L /usr/local/cuda-8.0/lib64/` to the command, since the `libcudart.so` library is located in that folder on my machine. I'm not sure how else this library would be located (LD_LIBRARY_PATH is only searched on execution, not compile-time), so I'm thinking this problem might not be specific to my configuration. If so, adding mention of this option on the documentation might be valuable.

**Comment by prb12** [comment]
@zplizzi  Could you please let me know what the value was of `$TF_INC` as per the following step in the instructions:
```
TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
```
@keveman  Should there also be an equivalent `$TF_LIB` path?

**Comment by keveman** [comment]
We do have `tf.sysconfig.get_lib()` that gives you the path to use for the `-L` option. However that's for the TensorFlow libraries. These instructions assume that cuda libraries are available in `/usr/local/lib64` which is typical if you install cuda with the default options. In that case, you wouldn't need to pass the extra `-L` to point to the location of cuda libraries. But @zplizzi does have a point, it might be valuable to add that to the documentation. @zplizzi do you mind sending out a PR?

**Comment by zplizzi** [comment]
Okay, I've submitted a PR adding a note in the docs about this.

@prb12 My `$TF_INC` is `/home/zack/venv/2/local/lib/python2.7/site-packages/tensorflow/include`, since I've installed TensorFlow into a virtual environment. The result of `tf.sysconfig.get_lib()` is `/home/zack/venv/2/local/lib/python2.7/site-packages/tensorflow/core`, as expected from @keveman's comments.
