### ISSUE TITLE
GatherV2 bug from pb->tflite

### ISSUE THREAD

**Issue by paulgheorghecristian** [tensorflow/tensorflow#40509]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.1
- Python version: 3.5
- Bazel version (if compiling from source): 0.16.0
- GCC/Compiler version (if compiling from source):7.4.0
- CUDA/cuDNN version: 10.2
- GPU model and memory: RTX 2080TI

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
v2.1.0-rc2-17-ge5bf8de 2.1.0

**Describe the current behavior**
![Screenshot from 2020-06-16 17-29-43](https://user-images.githubusercontent.com/17722852/84787868-26be2580-aff7-11ea-98b0-4b29c446c3ce.png)

I am trying to create a tflite from this pb, but it fails to convert this GatherV2 because
`2020-06-16 17:32:12.974945: F tensorflow/lite/toco/graph_transformations/resolve_constant_gather.cc:65] Check failed: stride * coords_shape.dims(0) == output_data.size() (131072 vs. 1310720)
`
The code is from resolve_constant_gather.cc
`  CHECK_EQ(stride * coords_shape.dims(0), output_data.size());
`
Is this desired? I think this is a bug.

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by abattery** [comment]
@paulgheorghecristian TOCO converter is now deprecated. Could you try conversion with MLIR converter from the recent TF version?

**Comment by paulgheorghecristian** [comment]
@abattery Thank you for your response! Are you referring to the tflite_convert tool? If not, do you guys have a tutorial for this MLIR?

**Comment by abattery** [comment]
The recent version of TF uses MLIR converter by default. You can reuse your conversion code.

**Comment by paulgheorghecristian** [comment]
I'm pretty sure you are referring to tflite_convert, I receive a similar error from this tool:
`2020-06-16 18:01:51.768228: F tensorflow/lite/toco/graph_transformations/propagate_fixed_sizes.cc:118] Check failed: dim_x == dim_y (2048 vs. 256)Dimensions must match
`

**Comment by paulgheorghecristian** [comment]
I'm sorry, I am not sure what you are referring to. If I use tflite_convert, which supposedly uses `    converter = lite.TFLiteConverterV2.from_saved_model(flags.saved_model_dir)
`, I still get an TOCO error:
`2020-06-16 18:01:51.768228: F tensorflow/lite/toco/graph_transformations/propagate_fixed_sizes.cc:118] Check failed: dim_x == dim_y (2048 vs. 256)Dimensions must match
`

**Comment by abattery** [comment]
I think in your model, one Mul op has an unsupported shape like the last error message. Mul op supports broadcasting but it can no handle invalid broadcasting inputs. The converter can catch that. Could you verify your model code with this behavior? The hint is in the location information "transformer-wmt14-seq10-d512-head8-1592317046/decoder/dec_0/attn/mul_1.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
