### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'numpy'

### ISSUE THREAD

**Issue by devspartan** [tensorflow/tensorflow#40508]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from (source or binary):
- TensorFlow version: 2.1.0
- Python version: 3.6
- GPU model and memory: NVIDIA 4GB gmx150

**currently my code giving me the error 'AttributeError: 'Tensor' object has no attribute 'numpy'' in line 11**

**i wanted to print the error in custom loss function**

**Here is my code**
import tensorflow as tf
import numpy as np
import keras.backend as K
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense, Conv2D, MaxPool2D, Input

def loss(yT, yP):
    err = yT - yP
    print(err.numpy())
    squaredError = tf.square(err)
    meanError = tf.reduce_mean(squaredError)
    return meanError

(xTrain, yTrain), (xTest, yTest) = mnist.load_data()
print(xTrain.shape, yTrain.shape, type(xTest))

xTrain, xTest = xTrain / 255, xTest / 255
yTrain, yTest = to_categorical(yTrain, num_classes=10), to_categorical(yTest, num_classes=10)

model = Sequential()
model.add(Flatten(input_shape=(28, 28)))
model.add(Dense(100, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.summary()
model.compile(optimizer='adam', loss=loss, metrics=['accuracy'])
model.fit(xTrain, yTrain, epochs=4, verbose=1)

Also tf.executing_eagerly is True
i don't know why this error is coming

**Comment by nikitamaia** [comment]
Hi @devspartan I suspect this is because you are calling numpy() within model.fit, which uses @tf.function under the hood automatically. If you add the argument run_eagerly=True to your model.compile, you should no longer get the error. However, then your model will train very slowly. 

You might want to investigate [adding a callback](https://www.tensorflow.org/guide/keras/custom_callback) for a more scalable solution.

**Comment by devspartan** [comment]
Thanks. For sure it did work. But why is the training so slow. Is there any better way to do that??

**Comment by nikitamaia** [comment]
The training is slow because you are no longer leveraging @tf.function, and instead training eagerly. You could try using a callback or implementing a custom metric, instead of printing directly within the loss function.

**Comment by devspartan** [comment]
Thanks for explanation and quick response.
