### ISSUE TITLE
SavedModel does not work correctly with signatures that use structured inputs or outputs

### ISSUE THREAD

**Issue by leandro-gracia-gil** [tensorflow/tensorflow#40501]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): N/A
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.1-34056-gde8db50778 2.3.0-dev20200613
- Python version: 3.7.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
As described [here](https://www.tensorflow.org/guide/concrete_function#nested_arguments), support for structured/nested arguments is available in TF nightly builds and coming to 2.3. Getting concrete functions with structured inputs and outputs works as documented, but using these concrete functions as signatures in saved models leads to a various issues.

See the following code snippet for simple example cases.
```python
from collections import namedtuple
import tensorflow as tf

Pair = namedtuple('Pair', ('x', 'y'))

class TestModel(tf.keras.Model):
  @tf.function
  def test(self, inputs: Pair):
    # Unlike inputs, outputs would need to be manually flattened if nested.
    return Pair(inputs.x + inputs.y, inputs.x - inputs.y)

model = TestModel()
specs = Pair(tf.TensorSpec([], tf.int32), tf.TensorSpec([], tf.int32))
signatures = {'test': model.test.get_concrete_function(inputs=specs)}

tf.saved_model.save(model, 'test_model', signatures=signatures)
loaded_model = tf.saved_model.load('test_model')

# When using the original signature it works correctly.
# This produces a Pair with tensor values (5, 1).
inputs = Pair(tf.constant(3, tf.int32), tf.constant(2, tf.int32))
output_pair = signatures['test'](inputs)

# The same does not work when using the signature from the loaded model.
# It fails because inputs have been flattened. This is acceptable, but not documented.
loaded_model.signatures['test'](inputs)

# However, flattening the input data does not help.
# This fails too because the signature now requires keyword arguments.
loaded_model.signatures['test'](*tf.nest.flatten(inputs, expand_composites=True))

# This fails too because the keyword argument names are generated by TF.
loaded_model.signatures['test'](x=inputs.x, y=inputs.y)

# This works, but it's utterly confusing. Note the args 'inputs' and 'inputs_1'.
outputs = loaded_model.signatures['test'](inputs=inputs.x, inputs_1=inputs.y)

# Outputs are also flattened. However, we get a dict. This means we cannot
# do this to recover the structure as order is not necessarily preserved.
# For more complex nested structures this would be pretty much needed.
bad_output_pair = tf.nest.pack_sequence_as(specs, list(outputs.values()))

# Not only that, but key names are not even consistent with inputs.
# This fails because the 'output' key does not exist.
output_pair = Pair(outputs['output'], outputs['output_1'])

# This works, but it's again confusing and not self-consistent.
output_pair = Pair(outputs['output_0'], outputs['output_1'])
```

**Describe the expected behavior**
While it would be desirable to be able to use structured types directly, flattening them is a reasonable tradeoff for signatures in exported models.

However:
1. It should be properly documented.
2. It should make recovering arbitrarily nested structures easy.
3. It should be self-consistent.

If flattening inputs and outputs is required, then a much better approach would be to transform potentially nested structures into tuples of their flattened contents. These tuples could then be referred either by position or by their keyword argument.

For example:
```python
# This could work if it accepted flattened tuples by position.
flat_outputs = loaded_model.signatures['test'](tf.nest.flatten(inputs, True))

# This could work if it accepted flattened tuples by keyword argument,
# which would help with functions taking multiple structured input arguments.
flat_outputs = loaded_model.signatures['test'](inputs=tf.nest.flatten(inputs, True))

# flat_outputs can still be a dict if it maps to tuples of flattened tensors.
# This would work for arbitrarily complex nested structures,
# and would also remove the need to generate new output names.
output_pair = tf.nest.pack_sequence_as(specs, flat_outputs['output'])

# Returning the flattened tuple directly or a sequence of outputs instead of a dict
# would perhaps make more sense, but this would need to work with other use cases.
output_pair = tf.nest.pack_sequence_as(specs, flat_outputs[0])
```

These changes would make the behavior of loaded model signatures tf.nest-friendly.

It would also be best to make these changes before the feature goes public in the incoming TF 2.3 release, as otherwise developers might start writing code that depends on the current confusing and inconsistent keyword args behavior.

Edit: corrected the code example to correctly account for composite tensors on inputs, and to mention the additional issue from the first comment.

**Comment by leandro-gracia-gil** [comment]
Another issue: unlike inputs, nested outputs (not just a named tuple like in the example, but nesting them) are not automatically flattened. You need to manually flatten them to be able to export them.

If you don't, you get a `ValueError` that says:
> Signatures have one Tensor per output, so to have predictable names Python functions used to generate these signatures should avoid outputting Tensors in nested structures.

This is another inconsistency and a problem that could also be avoided with the proposal above, since the entire nested structure would be flattened in a tuple with a single name.

**Comment by Saduf2019** [comment]
@leandro-gracia-gil 
I ran the code shared above, please let us know if [this gist](https://colab.research.google.com/gist/Saduf2019/10e7dfe5c9a68ee76391c9dcb266b11f/untitled233.ipynb) confirms your issue.

**Comment by leandro-gracia-gil** [comment]
@Saduf2019 Yes it does. However, note that my code contains multiple examples of failing cases for different reasons as indicated in the comments. Each of these will cause an error (with the exception of the `bad_output_pair` result where there is no error but the result is unsafe due to unreliable ordering). The gist is simply failing on the first of such cases.

**Comment by leandro-gracia-gil** [comment]
Looks like the input structure issues I reported here actually come from a misunderstanding of how exported signatures should be used. In the example above, instead of `loaded_model.signatures['test'](inputs)` what should be used is `loaded_model.test(inputs)`, which works as expected and correctly produces an output `Pair`.  (Thanks to @edloper for clarifying this in the RFC review).

However, there's still an issue with nested structured outputs. If instead of a simple `Pair` we nest them, we get an error.

```python
class TestModel(tf.keras.Model):
  @tf.function
  def test(self, inputs: Pair):
    pair = Pair(inputs, Pair(inputs.x + inputs.y, inputs.x - inputs.y))
    return pair
```

Trying to save the model exporting the signature now raises this:
`ValueError: Got non-flat outputs 'Pair(x=Pair(x=<tf.Tensor 'PartitionedCall:0' shape=() dtype=int32>, y=<tf.Tensor 'PartitionedCall:1' shape=() dtype=int32>), y=Pair(x=<tf.Tensor 'PartitionedCall:2' shape=() dtype=int32>, y=<tf.Tensor 'PartitionedCall:3' shape=() dtype=int32>))' from 'b'__inference_test_26'' for SavedModel signature 'test'. Signatures have one Tensor per output, so to have predictable names Python functions used to generate these signatures should avoid outputting Tensors in nested structures.`

This issue can be manually avoided by manually flattening the outputs: `return tf.nest.flatten(pair)`, but the output structure is lost and it must be reconstructed. If instead of one output the function returns multiple of them, then all of them need to be flattened and concatenated together.

Is this the expected behavior? Would it be possible to somehow preserve the nested structure of the outputs, given that it does seem possible to preserve it in the inputs?

**Comment by edloper** [comment]
@leandro-gracia-gil As I commented on the extension types RFC, the `signatures` in a `SavedModel` are intended to interoperate with non-python interfaces (c++, tensorflow serving, etc.), where Python's types (such as namedtuple) are not available.  Currently, this means that the concrete functions in the `signatures` dictionary are expected to take tensor arguments and return a tensor or a string-keyed dictionary of tensors.

But if you're going to be using your saved model from Python, then you don't need to use `signatures` at all.  You can save a model with functions that take nested or composite tensor parameters, and that return nested or composite tensor values.  You do need to call `get_concrete_function` for each concrete signature you want the saved model to contain (so it can trace the graph for those signatures), but you don't need to store the result.  (You can call `get_concrete_function` multiple times if you want your saved model to support different input signatures.)  

I.e., I think that the following will do what you want:

```python
class TestModel(tf.keras.Model):
  @tf.function
  def test(self, inputs: Pair):
    pair = Pair(inputs, Pair(inputs.x + inputs.y, inputs.x - inputs.y))
    return pair

model = TestModel()
specs = Pair(tf.TensorSpec([], tf.int32), tf.TensorSpec([], tf.int32))
model.test.get_concrete_function(inputs=specs)  # trace graph for expected spec(s)

tf.saved_model.save(model, 'test_model')  # note: no signatures argument here
loaded_model = tf.saved_model.load('test_model')
print(loaded_model.test(Pair(10, 20)))
```

**Comment by leandro-gracia-gil** [comment]
Thanks for the info. This approach does seem to work and keep the structure of the outputs too without having to flatten, but it rises a couple of questions.

1. How can I decide which concrete functions to export? I have other concrete functions in my actual model for my train and test pipelines, but I only want to export the ones relevant for inference. With signatures I could control this, but this way it seems like every single concrete function of the model gets automatically exported.

2. If I do not use explicit signatures, is it still possible to use the model from C++? How would the arguments work in that case?

**Comment by stefan-falk** [comment]
Hi @leandro-gracia-gil 

have you been able to get answers to those questions?

**Comment by leandro-gracia-gil** [comment]
@stefan-falk No, not yet.

**Comment by stefan-falk** [comment]
Ah I see. I am at this point my self right now. I guess you solved it using a wrapper?

```python
class MyModelWrapper:
  def __init__(self, model):
    self.my_fun = tf.function(model.my_fun, ...)
```

or something like that?

**Comment by leandro-gracia-gil** [comment]
@stefan-falk I'm not currently using `signatures`, so my model is exporting all concrete functions (though I only want to export a few particular ones). As for the C++ question, I haven't tried using the exported functions in C++ yet.

**Comment by stefan-falk** [comment]
@leandro-gracia-gil Alright, thank you for the insight :)

**Comment by stefan-falk** [comment]
@edloper If I do what you're suggesting I get:

```
ValueError: Expected a Trackable object for export, got <__main__.GreedyModel object at 0x7fa30ce3d6a0>.
```

```python
greedy_model = GreedyModel(model)
greedy_model.greedy_decode.get_concrete_function()
tf.saved_model.save(greedy_model, export_dir='/tmp/stream_greedy')
```

am I missing something here?

**Comment by sushreebarsa** [comment]
@leandro-gracia-gil Could you please let us know if this is still an issue ?Thanks!

**Comment by leandro-gracia-gil** [comment]
@sushreebarsa Following the instructions provided in [this comment](https://github.com/tensorflow/tensorflow/issues/40501#issuecomment-669187477) it works fine. There's still the problem that it forces you to export all concrete functions that are ever traced instead of a signature subset of your choice, but at least there's a workaround for getting things working. I'll be closing this for now.
