### ISSUE TITLE
Tensorflow's FixedLengthRecordDataset reads binary file significantly slower than pure Python

### ISSUE THREAD

**Issue by mhorlacher** [tensorflow/tensorflow#40502]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7.6
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: CPU Only
- GPU model and memory: CPU Only

**Describe the current behavior**
I'm wondering why Tensorflow's FixedLengthRecordDataset is so slow when reading records from a binary file (without processing the records). My implementation in plain Python (see code below) appears to be two order of magnitude faster. 

**Describe the expected behavior**
I would expect that reading a file with FixedLengthRecordDataset would perform comparably or faster than the pure Python implementation. 

**Standalone code to reproduce the issue**
```
import time
import numpy as np
import tensorflow as tf

with open('some_file', 'wb') as f:
    f.write(np.ones(10000, dtype=np.int32).tobytes())


def time_tf():
    start_time = time.time()
    for record in tf.data.FixedLengthRecordDataset('some_file', record_bytes = 4):
        _ = record
    print(f'FixedLengthRecordDataset: {time.time() - start_time}')

def time_py():
    start_time = time.time()
    with open('some_file', 'rb') as f:
        b = f.read(4)
        while b:
            b = f.read(4)
    print(f'Plain Python: {time.time() - start_time}')

time_tf()
time_py()
```

```
FixedLengthRecordDataset: 0.6247196197509766
Plain Python: 0.001483917236328125
```

**Other info / logs** 
None, but happy to provide on request.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/d27936b334109100a63e1f41af3250cc/40502.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/2a3b0437187fd5ee7e79ce3d4c303415/40502-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by mhorlacher** [comment]
To add to this, the problem seem to lie with the Dataset itself rather than IO:

```
import numpy as np
import tensorflow as tf
import time

a = np.ones(100000, dtype=np.float32)

start_time = time.time()
for x in a:
    pass
print(time.time() - start_time)

start_time = time.time()
for x in tf.data.Dataset.from_tensor_slices(a):
    pass
print(time.time() - start_time)
```

```
0.05548405647277832
5.67711615562439
```

**Comment by aaudiber** [comment]
@mhorlacher For a more apples to apples comparison, we should append `skip(10000)` to the dataset, so that the iteration happens in C++ instead of python. We should also make the benchmark run longer, to reduce the impact on constant overheads. With those changes, the difference is between 3x and 4x. This isn't concerning, since real use cases don't fetch tens of thousands of elements per second from `tf.data`. The performance advantages of using `tf.data` come out when doing non-trivial input processing to train a model.

**Comment by mhorlacher** [comment]
Thanks for your response @aaudiber . I'm fitting a large number (billions) of short sequences to a shallow network so in my case the above issue becomes a critical performance bottleneck, as both CPU and GPU are at very low utilization when using `tf.data` as described above. Is this a hopeless case or can you provide me with / point me towards any information to optimize performance for that task?

**Comment by aaudiber** [comment]
Is the data stored in a single file? If you split the data into multiple files, you can use `Dataset.interleave` to read from many files in parallel to speed up the input. If you share the dataset you are using, I can give recommendations

**Comment by mhorlacher** [comment]
Thanks for looking into this @aaudiber  . I'm unsure how to share my dataset properly, but I can provide you with some simulated data. 

Briefly, my inputs are sequences of length 24 over the alphabet {A, C, G, T} and they are paired with corresponding counts which I aim to predict. To reduce the size of the dataset, sequences are encoded as integers, since enumerating all possible sequences of length 24 fits into a 64-bit integer. In fact, I only need 6 bytes to encode a sequence of 24 and corresponding counts fit into a 32-bit integer, leading to 10 bytes per sample. Samples are stored across dozens of files (in fact, file-of-origin is another model input but irrelevant here). 

Generating some data:
```
import numpy as np
import tensorflow as tf
from pathlib import Path

n_files = 4
n_samples = 10000

out_dir = '.'

for i in range(0, n_files):
    with open(Path(out_dir).joinpath(f'file_{i}.gerbil'), 'wb') as f:
        for j in range(0, n_samples):
            mer_bytes = np.random.randint(0, 4 ** 24 - 1, size=None, dtype=np.uint64).tobytes()[:6]
            count_bytes = np.random.randint(1, 2 ** 32 - 1, size=None, dtype=np.uint32).tobytes()
            f.write(count_bytes + mer_bytes)
```

Loading raw byte records:
```
filepaths = [str(fp) for fp in Path(out_dir).glob('*.gerbil')]

dataset = tf.data.FixedLengthRecordDataset(filepaths, record_bytes=10)
print(dataset.element_spec)
```

Parsing raw records, i.e. decoding bytes and one-hot encoding sequence:
```
def _decode_mer_base(mer_int64, i):
    mer_int64_rs = tf.bitwise.right_shift(mer_int64, 2*i)
    return tf.math.floormod(mer_int64_rs, tf.constant(4, tf.int64))

def _decode_mer(mer_int64, k):
    """Decode an int64-encoded kmer to a k*4 one-hot matrix."""
    vec = tf.vectorized_map(lambda i: _decode_mer_base(mer_int64, i), tf.range(k, dtype=tf.int64))
    return tf.one_hot(vec, 4, dtype=tf.dtypes.float16)

def _parse_raw_record(raw_record, k):
    # decode mer count
    count = tf.io.decode_raw(tf.strings.substr(raw_record, 0, 4), out_type=tf.int32, little_endian=True)[0]

    # decode mer
    mer_int64 = tf.io.decode_raw(tf.strings.substr(raw_record, 4, 6) + b'\x00\x00', out_type=tf.int64, little_endian=False)[0]
    mer_int64 = tf.bitwise.right_shift(mer_int64, (32-k)*2)
    mer_onehot = _decode_mer(mer_int64, k)

    return mer_onehot, count

dataset = dataset.map(lambda x: _parse_raw_record(x, k=24))
print(dataset.element_spec)
```

The last code block is mostly for completeness and to demonstrate that the CPU is not fully utilized when decoding and preparing the raw input. The sequences are fed into a shallow CNN to detect short sequence motifs.

**Comment by mhorlacher** [comment]
Dear @aaudiber - thanks for the suggestions, I did some testing. 

First, I repeat parts of the code above, but with a larger synthetic data sample. 

```
import numpy as np
from pathlib import Path

import tensorflow as tf
tf.__version__

n_files = 4
n_samples = 400000

out_dir = '.'

for i in range(0, n_files):
    with open(Path(out_dir).joinpath(f'file_{i}.gerbil'), 'wb') as f:
        for j in range(0, n_samples):
            mer_bytes = np.random.randint(0, 4 ** 24 - 1, size=None, dtype=np.uint64).tobytes()[:6]
            count_bytes = np.random.randint(1, 2 ** 32 - 1, size=None, dtype=np.uint32).tobytes()
            f.write(count_bytes + mer_bytes)
```

1. Testing the influence of `num_parallel_reads` on runtime:

```
import time

def time_ParallelReads_1():
    dataset = tf.data.FixedLengthRecordDataset(filepaths, record_bytes=10, num_parallel_reads = 1)
    dataset = dataset.skip(10000)

    start_time = time.time()
    for r in dataset:
        _ = r
    print(f'time_ParallelReads_1: {time.time() - start_time}')

def time_ParallelReads_4():
    dataset = tf.data.FixedLengthRecordDataset(filepaths, record_bytes=10, num_parallel_reads = 4)
    dataset = dataset.skip(10000)

    start_time = time.time()
    for r in dataset:
        _ = r
    print(f'time_ParallelReads_4: {time.time() - start_time}')

def time_ParallelReads_AUTOTUNE():
    dataset = tf.data.FixedLengthRecordDataset(filepaths, record_bytes=10, num_parallel_reads = tf.data.experimental.AUTOTUNE)
    dataset = dataset.skip(10000)

    start_time = time.time()
    for r in dataset:
        _ = r
    print(f'time_ParallelReads_4: {time.time() - start_time}')

time_ParallelReads_1()
time_ParallelReads_4()
time_ParallelReads_AUTOTUNE()
```
```
time_ParallelReads_1: 148.9105041027069
time_ParallelReads_4: 153.37963438034058
time_ParallelReads_4: 158.80391359329224
```

It seems like increasing the number of parallel reads has no effect, indicating that the overhead of iterating over the tf.data.Dataset is indeed the problem. 

2. Batching the data before iterating
```
import time

def time_Batch_64():
    dataset = tf.data.FixedLengthRecordDataset(filepaths, record_bytes=10)
    dataset = dataset.skip(10000)
    dataset = dataset.batch(64)

    start_time = time.time()
    for r in dataset:
        _ = r
    print(f'time_Batch_64: {time.time() - start_time}')

def time_Batch_512():
    dataset = tf.data.FixedLengthRecordDataset(filepaths, record_bytes=10)
    dataset = dataset.skip(10000)
    dataset = dataset.batch(512)

    start_time = time.time()
    for r in dataset:
        _ = r
    print(f'time_Batch_512: {time.time() - start_time}')

def time_Batch_4096():
    dataset = tf.data.FixedLengthRecordDataset(filepaths, record_bytes=10)
    dataset = dataset.skip(10000)
    dataset = dataset.batch(4096)

    start_time = time.time()
    for r in dataset:
        _ = r
    print(f'time_Batch_4096: {time.time() - start_time}')

time_Batch_64()
time_Batch_512()
time_Batch_4096()
```
```
time_Batch_64: 2.4835407733917236
time_Batch_512: 1.2220275402069092
time_Batch_4096: 1.0555901527404785
```

Iterating over batches instead of individual samples leads to impressive runtime improvements. I was wondering whether bringing down the number of iteration over the dataset through other means (while keeping amount of data constant) will effect the runtime as well, so I tried to increase the number of bytes I read of the files. 

```
import time

def time_RecordBytes_40():
    dataset = tf.data.FixedLengthRecordDataset(filepaths, record_bytes=40)
    dataset = dataset.skip(10000)

    start_time = time.time()
    for r in dataset:
        _ = r
    print(f'time_RecordBytes_40: {time.time() - start_time}')

def time_RecordBytes_400():
    dataset = tf.data.FixedLengthRecordDataset(filepaths, record_bytes=400)
    dataset = dataset.skip(10000)

    start_time = time.time()
    for r in dataset:
        _ = r
    print(f'time_RecordBytes_400: {time.time() - start_time}')

def time_RecordBytes_4000():
    dataset = tf.data.FixedLengthRecordDataset(filepaths, record_bytes=4000)
    dataset = dataset.skip(10000)

    start_time = time.time()
    for r in dataset:
        _ = r
    print(f'time_RecordBytes_4000: {time.time() - start_time}')

time_RecordBytes_40()
time_RecordBytes_400()
time_RecordBytes_4000()
```
```
time_RecordBytes_40: 18.031224489212036
time_RecordBytes_400: 1.4269778728485107
time_RecordBytes_4000: 0.010393857955932617
```

Indeed, reading multiple samples at once by increasing the number of record bytes reduces iteration time drastically. 

---

Continuing further I decided to preprocess and fit data in batches. 

First, I redefine the above processing functions for a single sample:

```
def _decode_mer_base(mer_int64, i):
    mer_int64_rs = tf.bitwise.right_shift(mer_int64, 2*i)
    return tf.math.floormod(mer_int64_rs, tf.constant(4, tf.int64))

def _decode_mer(mer_int64, k):
    """Decode an int64-encoded kmer to a k*4 one-hot matrix."""
    vec = tf.vectorized_map(lambda i: _decode_mer_base(mer_int64, i), tf.range(k, dtype=tf.int64))
    return tf.one_hot(vec, 4, dtype=tf.dtypes.float16)

def _parse_raw_record(raw_record, k):
    # decode mer count
    count = tf.io.decode_raw(tf.strings.substr(raw_record, 0, 4), out_type=tf.int32, little_endian=True)[0]

    # decode mer
    mer_int64 = tf.io.decode_raw(tf.strings.substr(raw_record, 4, 6) + b'\x00\x00', out_type=tf.int64, little_endian=False)[0]
    mer_int64 = tf.bitwise.right_shift(mer_int64, (32-k)*2)
    mer_onehot = _decode_mer(mer_int64, k)

    return mer_onehot, count
```

Then, I use `map_fn` to map the preprocessing function over the entire batch and pass the dataset into the model. 

```
dataset = tf.data.FixedLengthRecordDataset(filepaths, record_bytes=10)
dataset = dataset.skip(10000)
dataset = dataset.batch(512).prefetch(tf.data.experimental.AUTOTUNE)
dataset = dataset.map(lambda x: tf.map_fn(lambda y: _parse_raw_record(y, k=24), x, dtype=(tf.float16, tf.int32)), num_parallel_calls=tf.data.experimental.AUTOTUNE)
dataset = dataset.prefetch(tf.data.experimental.AUTOTUNE)

dataset.element_spec
```

This brings GPU usage on my server from essentially idle to around 8-10%. Only when I `.cache` the preprocessed dataset I archive close to maximum GPU utilization (unfortunately this is not possible as my data does not fit into RAM). 

I think from here I need to work on optimizing the preprocessing for further improvements. If you have any immediate recommendations on that, please let me know. Otherwise I think I'll close the issue soon as I now understand the source of the initial problem better.

Thanks and best regards

**Comment by kunal-moloco** [comment]
@mhorlacher This thread helped me a lot! Just a quick question, were you able to optimize it any further? I have a very similar task as you did and am trying to further optimize my preprocessing.
