### ISSUE TITLE
Performance difference of TFlite in Android and iOS (model with quantization)

### ISSUE THREAD

**Issue by zampnrs** [tensorflow/tensorflow#40518]
I've trained a model to detect custom objects to be used in mobile devices (Android and iOS), my code is based in the tensorflow's examples for [iOS](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/ios) and [Android](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android). During my tests in pyshical devices (iPad 6th gen and Xiaomi RedMi Note 7) I've been noticing a difference of performance on Android app and iOS app.

Some examples of performance (number of objects detected):
IMG - iOS - Android
img1 - 57 - 74
img2 - 9 - 33
img3 - 43 - 78
img4 - 17 - 25

The real number of objects is a bit more than Android's result.

I'm using the **ssd_mobilenet_v2_quantized_coco** from the [tensorflow model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) and **tensorflow-v1.14**.

I'm using [this class](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/app/src/main/java/org/tensorflow/lite/examples/detection/tflite/TFLiteObjectDetectionAPIModel.java) in the Android version, and [this equivalent one](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/ios/ObjectDetection/ModelDataHandler/ModelDataHandler.swift) in the iOS version, both without any modification from the ones provided by Tensorflow.

**My question is**: What should I investigate to know the reason of the performance difference and fix it? My model should give the same result for the customer in both mobile platforms.

If it's something unclear please let me know, any help would be great. Thanks!

**Comment by Saduf2019** [comment]
@zampnrs 
Please share simple stand alone code to replicate the performance issue faced.

**Comment by zampnrs** [comment]
@Saduf2019 
**In Android I did it:**
`private Classifier detector; //tflite
    private Bitmap sbit; //bitmap scaled for 300x300
    List<Classifier.Recognition> results = detector.recognizeImage(sbit);`

The `Classifier` comes from this [interface](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/app/src/main/java/org/tensorflow/lite/examples/detection/tflite/Classifier.java) and the `recognizeImage` is a method from [this class](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/app/src/main/java/org/tensorflow/lite/examples/detection/tflite/TFLiteObjectDetectionAPIModel.java), both files are provided by tensorflow and I used it without any modification.

**In iOS I did it:**
`@State private var result: Result?
    private var modelDataHandler: ModelDataHandler? =
        ModelDataHandler(modelFileInfo: MobileNetSSD.modelInfo,
                         labelsFileInfo: MobileNetSSD.labelsInfo)
    self.result = self.modelDataHandler?.runModel(onFrame: buffer)`

The `result` is where I store my results, modelDataHandler is the variable with the tflite and txt files. The `buffer` from the last line is a CVPixelBuffer that I get from my UIImage using the function bellow:

`func getBuffer(from image: UIImage) -> CVPixelBuffer? {
        let attrs = [kCVPixelBufferCGImageCompatibilityKey: kCFBooleanTrue,     kCVPixelBufferCGBitmapContextCompatibilityKey: kCFBooleanTrue] as CFDictionary
        var pixelBuffer : CVPixelBuffer?
        let status = CVPixelBufferCreate(kCFAllocatorDefault, Int(image.size.width),    Int(image.size.height), kCVPixelFormatType_32BGRA, attrs, &pixelBuffer)
        guard (status == kCVReturnSuccess) else {
          return nil
        }
    
        CVPixelBufferLockBaseAddress(pixelBuffer!, CVPixelBufferLockFlags(rawValue: 0))
        let pixelData = CVPixelBufferGetBaseAddress(pixelBuffer!)
    
        let rgbColorSpace = CGColorSpaceCreateDeviceRGB()
        let context = CGContext(data: pixelData, width: Int(image.size.width), height:  Int(image.size.height), bitsPerComponent: 8, bytesPerRow:   CVPixelBufferGetBytesPerRow(pixelBuffer!), space: rgbColorSpace, bitmapInfo:    CGImageAlphaInfo.noneSkipFirst.rawValue)
    
        context?.translateBy(x: 0, y: image.size.height)
        context?.scaleBy(x: 1.0, y: -1.0)
    
        UIGraphicsPushContext(context!)
        image.draw(in: CGRect(x: 0, y: 0, width: image.size.width, height: image.size.height))
        UIGraphicsPopContext()
        CVPixelBufferUnlockBaseAddress(pixelBuffer!, CVPixelBufferLockFlags(rawValue: 0))
    
        return pixelBuffer
    }`

**Comment by yyoon** [comment]
Hi @zampnrs. When converting your trained model into tflite format, did you use quantization, or just the float model? If you were using a float model, #40442 might have been the cause. If you were using a quantized model, we may need to investigate further to find the root cause.

**Comment by zampnrs** [comment]
Hi @yyoon. Yes, I'm using quantization. I'll check this other issue, it seems similar with I'm facing. Thanks! Any update I post here.

**Comment by yyoon** [comment]
Well, if you're using a quantized model, then it's probably a different issue from the one I linked above.

Another possibility is that this is caused by the difference in the way image is preprocessed before fed into the model. IIUC, the image is cropped and then resized in the Android app, whereas the iOS app does not properly crop the image.

Do you think this could be the cause?

**Comment by zampnrs** [comment]
You're right, it's a different issue.

Maybe not. As far as I could see, the image is cropped in Android to make the real time detection faster, It's visible the velocity detection difference in both apps, in iOS it's slower. Since I'm using a single image, in my Android app I just resize the image to 300 x 300 and call the inference, in iOS I convert my `UIImage` to `CVPixelBuffer` and then call the inference, the resizing is made after it. I tried to modify the iOS class to use the Android cropping and resizing approach but the result is equal.

I'm not a big expert in iOS dev but I think it's something with the pre-processing logic, especially in the method `rgbDataFromBuffer()`. Comparing to Android app, there is coding differences beyond to syntax, some parameters are defined different in both apps when the model is quantized or not, like `numBytesPerChannel` in Android and `inputChannels` in iOS, in Android this parameter is 1 for quantized models and 4 for non-quantized models, in iOS this parameter is always 4. I've been testing this and other differences today but I still couldn't figure out anything.

**Comment by yyoon** [comment]
> I convert my UIImage to CVPixelBuffer and then call the inference
> I tried to modify the iOS class to use the Android cropping and resizing approach but the result is equal.

Can you share the actual code doing this?

> in iOS this parameter is always 4

I don't see any issues (yet) with the constants in the code.
* The `inputChannels` is always 3 (not 4), and this represents the number of image channels expected by the model input, which is correct.
* The `imageChannels` value is always 4, which is probably meant to represent the number of image channels in the image taken from the camera, but it doesn't seem to be used. (Well, we should fix that..)

**Comment by zampnrs** [comment]
Yes, sure. The code to convert UIImage to CVPixelBuffer is in my reply above to Saduf2019. 

I've already undone my change to the `ModelDataHandler.swift` since I couldn't get any difference in the results, but the changes were:
- Take out these lines:
`    // Crops the image to the biggest square in the center and scales it down to model dimensions.
    let scaledSize = CGSize(width: inputWidth, height: inputHeight)
    guard let scaledPixelBuffer = pixelBuffer.resized(to: scaledSize) else {
        print("Failed to scale pixel buffer")
      return nil
    }`

And then change the `scaledPixelBuffer` to `pixelBuffer`, the original one.
`// Remove the alpha component from the image buffer to get the RGB data.
      guard let rgbData = rgbDataFromBuffer(
        scaledPixelBuffer,
        byteCount: batchSize * inputWidth * inputHeight * inputChannels * imageChannels,
        isModelQuantized: inputTensor.dataType == .uInt8
      ) else {
        print("Failed to convert the image buffer to RGB data.")
        return nil
      }`

When I get my bounding box coordinates, I plot them rescaling from 300 x 300 coordinate space to myImage coordinate space.

Sorry, the parameter I was talking about is the `imageChannels`, not the other one.

Well, If the parameters are not wrong, I sincerally have no idea right now of what is the problem. I'll try to investigate it further

**Comment by Jamesweng** [comment]
Hi @zampnrs  in your code

"getBuffer: 
let status = CVPixelBufferCreate(kCFAllocatorDefault, Int(image.size.width), Int(image.size.height), kCVPixelFormatType_32BGRA, attrs, &pixelBuffer)"

you're assuming input image is kCVPixelFormatType_32BGRA, which is not always true, sometimes you may got a kCVPixelFormatType_32ARGB image, suggest to debug from here. 

Thanks,

**Comment by Jamesweng** [comment]
and you need a small change in lite/examples/object_detection/ios/ObjectDetection/Extensions/CVPixelBufferExtension.swift to support selecting ARGB image from iPhone gallery, which i created a pull request here - 

https://github.com/tensorflow/examples/pull/227/commits/6cf2adbe333c9c1a4194cbb78b07423792e317f4

Thanks,

**Comment by zampnrs** [comment]
@Jamesweng thanks a lot! I didn't know that images from iOS gallery come in ARGB, I've changed to this format in the line you suggested and the number of detected objects has increased a lot in iOS. 

There is still a small difference between the performance in both platform, differences usually of 1 to 3 detected objects. Do you think this difference could be due to the different way that each platform deal with images (e. g. Bitmaps, UIImage, CVPixelBuffer etc.) ?

Another question: if the image from the iOS gallery was not originally taken by an Apple device (e. g. downloaded from the web), will it still be ARGB? Or should I check the pixel format for every image?

**Comment by Jamesweng** [comment]
for #1 i would suggest you log input pixel values in both platforms to check if there're any differences from model input. image preprocessing operator(e.g., how image resize is implemented) may cause differences

for #2 you need to check pixel format for safe handling

**Comment by zampnrs** [comment]
Humm... Ok, I'll try it. Thank a lot @Jamesweng and also @yyoon for your time to help me. Any updates I post here.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
