### ISSUE TITLE
Tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.

### ISSUE THREAD

**Issue by mahdiabdollahpour** [tensorflow/tensorflow#40516]
**System information**
- Tf 2.2.0
- Windows10
- Python version: 5.7.6
- git version v2.2.0-rc4-8-g2b96f3662b

When I pass class_weight to model.fit() this error comes and when I do not pass it goes? any idea how to solve it?

`
Tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  indices[84] = 31 is not in [0, 31)
	 [[{{node GatherV2}}]]
	 [[IteratorGetNext]]
	 [[ReverseSequence_1/_502]]
  (1) Invalid argument:  indices[84] = 31 is not in [0, 31)
	 [[{{node GatherV2}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_28314]

Function call stack:
train_function -> train_function
`

`       model_input = tf.keras.layers.Input(shape=(timesteps,), dtype='int32')
        self.createBertLayer()

        bert = self.bert_layer(model_input)

        self.d = tf.keras.layers.Dense(num_hiddens, activation=tf.nn.relu)(bert)
        h = tf.keras.layers.Dropout(0.5)(self.d)
        self.y1 = tf.keras.layers.Dense(classes, activation=tf.nn.softmax)(h)

        self.crf = CRF()
        output = self.crf(self.y1)

        model = Model(model_input, output)
        model.build(input_shape=(None, timesteps))
        self.bert_layer.apply_adapter_freeze()
        self.bert_layer.trainable = False

        model.compile(loss=self.crf.loss, optimizer=tf.keras.optimizers.Adam(0.001), metrics=[self.crf.accuracy])

        history = self.model.fit(
            training_set,
            training_label,
            class_weight=class_weights,
            epochs=n_epochs,
            # validation_data=(testing_set, one_hotted2),
            validation_split=0.1,
            verbose=1,
            batch_size=256
            # callbacks=[cp_callback]
        )
`

I checked class_weight keys and there was no problem with it.

**Comment by amahendrakar** [comment]
@mahdiabdollahpour,
On running the code, I'm facing an error stating `NameError: name 'timesteps' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/340241daddb4646b07b9788dd009f549/40516.ipynb).

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!
