### ISSUE TITLE
Tensorflow lite v1 converter not correctly quantizing model (tf 2.2.0)

### ISSUE THREAD

**Issue by melhabr** [tensorflow/tensorflow#40519]
**System information**
- OS Platform and Distribution: Ubuntu 18.04.4 LTS
- TensorFlow installed using pip, version 2.2.0

**Python Code**

```
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
        "mobilenet_v2_quantized/tflite_graph.pb", ['normalized_input_image_tensor'],
        ['TFLite_Detection_PostProcess:0','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'],
        input_shapes={'normalized_input_image_tensor': [1, 300, 300, 3]})
converter.inference_type = tf.compat.v1.lite.constants.QUANTIZED_UINT8
converter.quantized_input_stats = {'normalized_input_image_tensor' : (128, 128)}
converter.change_concat_input_ranges = False
converter.allow_custom_ops = True
model = converter.convert()
open("converted_model.tflite", "wb").write(model)```
```

# Issue:

This code successfully produces a tflite flatbuffer, but the flatbuffer does not appear to be quantized correctly. When I attempt to compile the resulting model using Google's edgetpu_compiler tool, I encounter the following error:

```
Edge TPU Compiler version 2.1.302470888
Invalid model: converted_model.tflite
Model not quantized
```
The input model is SSD_mobilenet_v2_quantized, available [here](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03.tar.gz).

**Comment by amahendrakar** [comment]
@melhabr,
On running the given code I am facing an error stating 
```
Exception: Op type not registered 'TFLite_Detection_PostProcess' in binary running on 933ed180d2c1. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
``` 
Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/97503b8d532545c2d168efc8379d72f5/40519.ipynb). Thanks!

**Comment by melhabr** [comment]
It seems the zero output index is causing issues in some versions, this code should work correctly:
```
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
        "mobilenet_v2_quantized/tflite_graph.pb", ['normalized_input_image_tensor'],
        ['TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'],
        input_shapes={'normalized_input_image_tensor': [1, 300, 300, 3]})
converter.inference_type = tf.compat.v1.lite.constants.QUANTIZED_UINT8
converter.quantized_input_stats = {'normalized_input_image_tensor' : (128, 128)}
converter.change_concat_input_ranges = False
converter.allow_custom_ops = True
model = converter.convert()
open("converted_model.tflite", "wb").write(model)
```
I tried this code in a clean virtual environment and it successfully produced a quantized model. There seems to be some issue with my installation, despite it being version 2.2.0. A full reinstall should fix it.

**Comment by amahendrakar** [comment]
@melhabr,
The issue seems to be fixed with the latest TF-nightly. 

I was able to compile the model with the edgetpu-compiler tool, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/19e793d8d1e9b9c412c3854610861eaf/40519.ipynb). Thanks!

**Comment by melhabr** [comment]
Thank you!
