### ISSUE TITLE
TFBertForSequenceClassification: Non-deterministic when training on GPU, even with seeds fixed and TF_DETERMINISTIC_OPS="1"

### ISSUE THREAD

**Issue by MFreidank** [tensorflow/tensorflow#40514]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): used on Google Colab
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6.9
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 10.1
- GPU model and memory: Tesla K80

**Describe the current behavior**
[Colab Link with a minimal example](https://colab.research.google.com/drive/1VSU8lYFD0E1HKZrIL1MvyIRwAktlSF_t#scrollTo=9NM47IRsy_v4)

Training a [transformers](huggingface/transformers/) `TFBertForSequenceClassification` model ([model code direkt link](https://github.com/huggingface/transformers/blob/3d495c61efbd2ca8a17827ff3103f7c820f0e9da/src/transformers/modeling_tf_bert.py#L910)) with keras/tf2.2.0 on the GPU is non-deterministic, even when setting all relevant random seeds and following the best practice guide in [these gputechconf slides](https://developer.download.nvidia.com/video/gputechconf/gtc/2019/presentation/s9911-determinism-in-deep-learning.pdf). 
As clearly documented in [this table](https://github.com/NVIDIA/tensorflow-determinism#confirmed-current-gpu-specific-sources-of-non-determinism-with-solutions), training on the GPU can be expected to be deterministic for TF 2.2.0 when setting environment variable `TF_DETERMINISTIC_OPS` to `"1"`. 
In spite of me setting this variable in my code (prior to importing tensorflow), this is not the case in my example.

Having seen previous issues (#38185) documented for `CrossEntropyLoss`, I also used the [suggested workaround for those](https://github.com/tensorflow/tensorflow/issues/38185#issuecomment-643014439). 
Nonetheless, my code remains non-deterministic on the GPU. 

The following table summarizes my results **after only training for five steps** , numbers were computed using [this function suggested to verify training reproducibility](https://github.com/NVIDIA/tensorflow-determinism/issues/2#issuecomment-548210203):

| | Device | Before training | After training |
| ------------- | ------------- | ------------- | ------------- |
| Run 1  | GPU | -641227.5609667897224  | -641237.442 **`5159916282`** |
| Run 2  | GPU | -641227.5609667897224  | -641237.442 **`3093758523`** |
| | |  | |
| Run 1 | CPU | -641227.5609667301178 | -641238.1506845243275 |
| Run 2 | CPU | -641227.5609667301178 | -641238.1506845243275 |

**Describe the expected behavior**
For TF 2.2.0, training on the GPU is expected to be deterministic when fixing random seeds and using: 
```python
os.environ["TF_DETERMINISTIC_OPS"] = "1"
```
Thus, my expectation is that the example code provided in my colab notebook should be deterministic on the colab GPU runtime as well.

**Standalone code to reproduce the issue**
Colab Link, reproducible on CPU runtime, non-deterministic on GPU runtime: https://colab.research.google.com/drive/1VSU8lYFD0E1HKZrIL1MvyIRwAktlSF_t#scrollTo=9NM47IRsy_v4

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
I have tried reproducing issue in TF2.2 -[CPU ](https://colab.research.google.com/gist/ravikyram/baaff5ec5a89755b7bb210925995d0b7/untitled34.ipynb) and [GPU](https://colab.research.google.com/gist/ravikyram/644e4ada0911e91dba7072ca7844c592/untitled33.ipynb).Is this the expected behavior?.Thanks!

**Comment by duncanriach** [comment]
Note that this issue is being addressed as an [issue in the tensorflow-determinism repo](https://github.com/NVIDIA/tensorflow-determinism/issues/19).
