### ISSUE TITLE
Docker images with tags '1.15.3' are missing on Docker Hub

### ISSUE THREAD

**Issue by soleares** [tensorflow/tensorflow#40513]
We would like to update our images to release 1.15.3 for the security fixes it contains. I'm not seeing any 1.15.3 images on dockerhub though.

https://hub.docker.com/r/tensorflow/tensorflow/tags?name=1.15.3

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
