### ISSUE TITLE
Building binaries for Arduino fails, fatal error: PDM.h

### ISSUE THREAD

**Issue by victorromeo** [tensorflow/tensorflow#40524]
@tensorflow/micro

**System information**
- Ubuntu 20.04 x86_64
- TensorFlow installed from source:
- Tensorflow version : 389405a77946410400ed410246e4cc7257802dde
- Target platform: Arduino Nano 33

Documentation [here](https://www.tensorflow.org/lite/microcontrollers/library) under Build binaries heading suggest that a binary build can be initiated with a call as follows:

```
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=<target> <project_name>_bin
```
Therefore a simple call as follows should work or need specific architecture to run to success.
```
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=arduino micro_speech_bin
```

However, as the required `PDM.h` Arduino library is not in the source tree, when compiling micro_speech for Arduino, this fails with the error.

```
tensorflow/lite/micro/examples/micro_speech/arduino/audio_provider.cc:39:10: fatal error: PDM.h: No such file or directory
   39 | #include "PDM.h"
      |          ^~~~~~~
```
Supported targets and target architectures are not documented anywhere I have found.

Furthermore, the `Makefile.inc` in the arduino folder `tensorflow/lite/micro/examples/micro_speech/arduino` contains a reference to 'sparkfun_edge' instead of 'arduino' the following:

```
ifeq ($(TARGET),$(filter $(TARGET),arduino))

MICRO_SPEECH_SRCS += \
	tensorflow/lite/micro/examples/micro_speech/sparkfun_edge/audio_provider.cc \
	tensorflow/lite/micro/examples/micro_speech/sparkfun_edge/command_responder.cc

endif

```

**Comment by sushreebarsa** [comment]
@victorromeo Could you please let us know if the issue still persists ? Thanks!
