### ISSUE TITLE
SavedModel generates different probabilities than Estimator model It is exported from for RNNClassifier

### ISSUE THREAD

**Issue by linbrian** [tensorflow/tensorflow#40525]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS Catalina 10.15.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): b'v1.13.2-5-g04256c89d8' 1.13.2
- Python version: 3.6.10
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
For a tf.contrib.estimator.RNNClassifier estimator model, the estimator produces different probabilities when making predictions than the same model when exported to a SavedModel and making predictions (both using Serving and locally). When using the same code, except the estimator is changed to a DNNClassifier (and tf.contrib.feature_column.sequence_categorical_column_with_identity is changed to tf.feature_column.categorical_column_with_identity for feature_column), the SavedModel produces the same probabilities as expected. 

**Describe the expected behavior**
The SavedModel should generate the same probability as the estimator model it is generated from for any sample. 

**Standalone code to reproduce the issue**
Jupyter notebooks + small example datasets are provided in this repo: https://github.com/linbrian/tf_1.13_rnn_classifier_bug/tree/master

**Comment by ravikyram** [comment]
I have tried in colab with TF version 1.13.2, 1.15 .Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/e1c42b10092adb5b5d4cec1ba49c3c4c/untitled37.ipynb).Is this the expected behavior?.Thanks!

**Comment by linbrian** [comment]
The gist shows the behavior I saw, in which the probabilities are different, but the expected behavior is that the probabilities are the same.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
