### ISSUE TITLE
High memory use / leak in model.fit

### ISSUE THREAD

**Issue by davsklaus** [tensorflow/tensorflow#40523]
I have an issue with a high memory uses, from this simple code sample. (link [Test.py](https://gist.github.com/davsklaus/6764bb3cf90841ce57d3658f83e14fa7)

````
import tensorflow as tf
from tensorflow.keras import layers
import time, os, gc
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.optimizers import SGD, Adam
import numpy as np

os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
print(tf.version.VERSION)

X = np.random.random((1119440, 100, 12)).astype(dtype=np.float32)
Y = np.random.random((1119440,)).astype(dtype=np.float32)
X_val = np.zeros( ( 300000, 100, 12), dtype=np.float32)
Y_val = np.zeros( (X_val.shape[0]), dtype=np.float32)

inputs = Input((100,12))
outputs = layers.Dense(1)(inputs)
model = Model(inputs=inputs, outputs=outputs, name='my_model')

model.compile(optimizer='SGD', loss = 'MSLE', metrics=['MSE'])
print(model.summary())

model.fit(X,Y, batch_size=32, verbose=1, shuffle=True, epochs=20, validation_data=(X_val,Y_val))

````
**For each epoch the the memory consumption inc with 1GB**, And after 20 epoch my system run out of memory.
I don't know if it a true memory leak, because gc.collect are able to collect a large portion of it.

I have localized the issue to be related to "validation_data=(X_val,Y_val)" 
The memory uses are stable if i replace the line with "model.fit(X,Y, batch_size=32, verbose=1, shuffle=True, epochs=20)"

I can see there are reported other issues with use of generators, but in this case X_val and Y_val are simple numpy arrary.

Tested with this docker file  
    FROM tensorflow/tensorflow:2.2.0-jupyter 
    COPY test.py /tmp/test.py 
    CMD python3 /tmp/test.py 

Same result if I uses tensorflow/tensorflow:lastest

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04):
- TensorFlow installed from (source or binary): docker tensorflow/tensorflow:2.2.0-jupyter
- TensorFlow version (use command below): 2.2.0
- Python version: 3
- Tested on a PC with 16GB of physical mem and 10GB of swap space

**Comment by Saduf2019** [comment]
@davsklaus 
Could you please provide with complete code such that we could replicate the issue faced or please share a colab gist withe error for us to analyse.

**Comment by bjourne** [comment]
I have a similar problem although I'm not using any validation data:
```python
from tensorflow.keras import *
from tensorflow.keras.layers import *
from tensorflow.keras.optimizers import *
import tensorflow as tf

model = Sequential([
    Embedding(input_dim = 11,
              output_dim = 100,
              mask_zero = True,
              batch_input_shape = [None, None]),
    LSTM(1024, stateful = False,
         return_sequences = True),
    TimeDistributed(Dense(11, activation = 'softmax'))])
X, Y = [], []
for _ in range(10000):
    v1 = tf.random.uniform((50,), minval = 1, maxval = 11,
                           dtype = tf.int32)
    v2 = tf.zeros((10,), dtype = tf.int32)
    sample = tf.concat((v1, v2), axis = 0)
    X.append(sample[:-1])
    Y.append(sample[1:])
optimizer = RMSprop(learning_rate = 0.01)
model.compile(
    optimizer = optimizer,
    loss = 'sparse_categorical_crossentropy',
    metrics = ['sparse_categorical_accuracy'])
print('fitting')
model.fit(X, Y, epochs = 30)
```
TensorFlow stalls for a long while at the model.fit call. Then its memory usage slowly starts increasing until it has consumed over 4gb and then my oom killer kills it. The dataset isn't that large and should readily fit in a few mb's of memory.

**Comment by davsklaus** [comment]
@Saduf2019 

I have update the issue and added a link to the source code used to provoke the isssue.
I have also try the code on Colab - i had to reduce the size of the train data to get it to fit. But on colab the memory use was stable.  Afterwards i try the modified code in the docker image, but here i still run out of memory.

But afterward i fund that i can get it to run, if I change the garbage threshold - by setting "gc.threshold(15,2,1)"

**Comment by gowthamkpr** [comment]
@davsklaus So, is the issue resolved right now as you were able to run  it? Thanks!

**Comment by davsklaus** [comment]
Yes - i got it to run by tweaking the garbage collection setting. 
But it seems a bit wrong - wonder if framework are doing some strange things. Where it generate some complicated memory reference that make it hard for the garbage collection to cleanup.

**Comment by gowthamkpr** [comment]
@davsklaus On what OS are you running into this error? Can you be more clear about the configuration of your PC? Thanks!

**Comment by davsklaus** [comment]
My machine are Ubuntu 20.04 with kernel version 5.4.0

But the error was seen running in a docker image - using tensorflow/tensorflow:2.2.0-jupyter and  tensorflow/tensorflow:lastest

**Comment by rmothukuru** [comment]
@davsklaus,
Sorry for the delayed response. Your code could be run without any error in **`Tensorflow Version 2.5`**. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/c8cd506e3718d723c2cf3581af1100f2/gh_40523.ipynb) of the working code.

If possible, can you please check if the issue is resolved, when run in [the Docker Image](https://github.com/tensorflow/tensorflow/issues/40523#issuecomment-655624912) as well? Thanks!

**Comment by davsklaus** [comment]
Hi thanks for your response.

It was newer an issue in colab - the memory use was stable there.
The issue was seen using the docker image tensorflow/tensorflow:2.2.0-jupyter - but also in other version of tensorflow 2.2 

I have retested the script on newer version (2.3.0, 2.40 & 2.50)  and there are the memory use stable - so it look like the issue has been fix since the issue was created

**Comment by davsklaus** [comment]
Hi thanks for your response.

It was newer an issue in colab - the memory use was stable there.
The issue was seen using the docker image tensorflow/tensorflow:2.2.0-jupyter - but also in other version of tensorflow 2.2 

I have retested the script on newer versions (2.3.0, 2.40 & 2.50)  and there are the memory use stable - so it look like the issue has been fix since the issue was created.
