### ISSUE TITLE
Combining multiple savedmodels into one SavedModel

### ISSUE THREAD

**Issue by yaswitag1** [tensorflow/tensorflow#40536]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**Describe the expected behavior**
I was able to combine multiple tf estimator savedmodels (linear classifiers) into one and then serve that final model instead of serving multiple models. I assumed the same process would work for boosted trees saved models.

**Describe the current behavior**

But when it comes to boosted trees, i am experiencing the following error :

NotFoundError:  Resource localhost/boosted_trees/QuantileAccumulator/_load_2153_load_11463/N10tensorflow34BoostedTreesQuantileStreamResourceE does not exist.
	 [[node import/boosted_trees/BoostedTreesQuantileStreamResourceGetBucketBoundaries_1 (defined at <ipython-input-136-92a81f76cf4e>:2) ]] [Op:__inference_pruned_12525]

Function call stack:
pruned

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Model1, Model2 are my two loaded linear classifer estimators on the same feature set but for different cities; replacing them with boosted trees estimators yields the error 

# 
class CombinedModel(tf.Module):
    def __init__(self):
        self.model1 = model1
        self.model2 = model2
    @tf.function(input_signature=[tf.TensorSpec(shape=[None], dtype=tf.float32),
                                 tf.TensorSpec(shape=[None], dtype=tf.float32),
                                 tf.TensorSpec(shape=[None], dtype=tf.string)])
    def __call__(self, feature1, feature2, city):
        input1 = {
            "feature1" : feature1,
            "feature2": feature2
        }
        print(type(allotment_eta))
        city_chennai = tf.constant(["chennai"])
        city_mumbai = tf.constant(["mumbai"])

        # IF CITY IS CHENNAI
        if tf.equal(city[0],city_chennai):
            inference_func = self.model1.signatures["predict"]
            predictions = inference_func(**({"feature1": feature1, "feature2": feature2}))        
            return predictions['probabilities']
        # ELSE CITY IS MUMBAI
        else :
            inference_func = self.model2.signatures["predict"]
            predictions = inference_func(**({"feature1": feature1, "feature2": feature2}))        
            return predictions['probabilities']

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@yaswitag1 
Please, let us which Tensorflow version you are using?. Request you to share colab link or simple standalone code with proper indentation and supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by yaswitag1** [comment]
Hey,
The notebook can be found in the link attached below.
[https://drive.google.com/file/d/1LaLmnzHAeRdqw-2LDv8Ew_TD-CGB7jvI/view?usp=sharing](url)

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2 ,nightly versions and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/d8b40c810496be63402ca0427ff45f4d/untitled39.ipynb).Thanks!

**Comment by yaswitag1** [comment]
Hey,
  Are there any updates on this ?

**Comment by saikumarchalla** [comment]
@yaswitag1 I tried to execute the code in TF 2.5 and facing different error. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/d4362e264996d6c54a5bbb2f6b87938a/untitled39.ipynb#scrollTo=x2I_IrKzp5Zb&uniqifier=3).Thanks!
