### ISSUE TITLE
Feature request: facemesh example for tensorflow lite

### ISSUE THREAD

**Issue by Starsky-Synlitec** [tensorflow/tensorflow#40539]
Facemesh example for tensorflow lite

To get the result of facemesh we need first to detect face using blazeface。But how to use the result of blazeface estimation as the input of facemesh model, it is not very clear.
Can we have a facemesh example for tensorflow lite ?

**Comment by Starsky-Synlitec** [comment]
Hi guys, @ymodak @xunkai55.
Do we have an example using facemesh on tensorflow lite now?

**Comment by lintian06** [comment]
Thank you for the feature request! 

I think you are asking some sample code from MediaPipe: https://google.github.io/mediapipe/solutions/face_mesh.html, an application framework that uses TFLite.

**Comment by GulderBone** [comment]
I would love to get sample code to (in normal form, can't open the bazel one)
