### ISSUE TITLE
how to build no stripped tensorflow lite so

### ISSUE THREAD

**Issue by dreamtalee** [tensorflow/tensorflow#40533]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): mac os
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14
- Python version: 2.7
- Installed using virtualenv? pip? conda?:no
- Bazel version (if compiling from source): 0.25.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: no
- GPU model and memory: no

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

bazel build  --strip=never -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a \
  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
  //tensorflow/lite/java:tensorflow-lite

i want build an no stripped so so that i can investigate the crash from user, even i add the '-strip=never', the so is also stripped

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by dreamtalee** [comment]
I found the strip flag is in tensorflow/lite/build_def.bzl and define in this method`tflite_symbol_opts`, after comment the '-s ', the so built will no stripped :
    
    def tflite_symbol_opts():
        """Defines linker flags whether to include symbols or not."""
        return select({
            "//tensorflow:android": [
                "-latomic",  # Required for some uses of ISO C++11 <atomic> in x86.
            ],
            "//conditions:default": [],
        }) + select({
            "//tensorflow:debug": [],
            "//conditions:default": [],
            #     "-s",  # Omit symbol table, for all non debug builds
            # ],
        })

**Comment by wangtz** [comment]
By reading tflite_symbol_opts definition, it sounds doable if you do a debug build 
 e.g. include "//tensorflow:debug" as a dependency.

**Comment by terryheo** [comment]
You'd better use debug build.

```
bazel build -c dbg --fat_apk_cpu=arm64-v8a,armeabi-v7a
--host_crosstool_top=@bazel_tools//tools/cpp:toolchain
//tensorflow/lite/java:tensorflow-lite
```

**Comment by dreamtalee** [comment]
Actually, the origin problem is the app crashed and i had collected the crashed address, i need translate the address to the code line number.

**Comment by terryheo** [comment]
Once you have stack traces with debug build aar, you can use ndk-stack.
https://developer.android.com/ndk/guides/ndk-stack

**Comment by dreamtalee** [comment]
> Once you have stack traces with debug build aar, you can use ndk-stack.
> https://developer.android.com/ndk/guides/ndk-stack

Thanks for your reply, i can't reproduce the crash with my own app, so i checkout the code to the version used in the app, and build a so with symbols, then translate the user crash address to the code line number.
