### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by thepontiacbandit** [tensorflow/tensorflow#40530]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version: 2.2.0
- Python version: 3.6.5
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: v11
- GPU model and memory: 

I am trying to run the following code
```
import tensorflow as tf
print("Num GPUs Avaiable: ", len(tf.config.experimental.list_physical_devices('GPU')))
```

I get the error

> AttributeError: module 'tensorflow' has no attribute 'config'

I tried the following 

```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
print("Num GPUs Avaiable: ", len(tf.config.experimental.list_physical_devices('GPU')))

```
I got the error

> ModuleNotFoundError: No module named 'tensorflow.compat'

Edit1: After uninstalling and reinstalling tensorflow, now i'm getting the error:

> The Kernal appears to have died. It will restart automatically

I cannot understand what I'm doing wrong, I'm using jupyter notebook

for reference, if there is an issue with the versions
`pip list`  

> Package                            Version
> ---------------------------------- -------------------
> absl-py                            0.9.0
> alabaster                          0.7.12
> anaconda-client                    1.7.2
> anaconda-navigator                 1.9.12
> anaconda-project                   0.8.3
> argh                               0.26.2
> asn1crypto                         1.3.0
> astroid                            2.4.1
> astropy                            4.0.1.post1
> astunparse                         1.6.3
> atomicwrites                       1.4.0
> attrs                              19.3.0
> autopep8                           1.4.4
> Babel                              2.8.0
> backcall                           0.1.0
> backports.functools-lru-cache      1.6.1
> backports.shutil-get-terminal-size 1.0.0
> backports.tempfile                 1.0
> backports.weakref                  1.0.post1
> bcrypt                             3.1.7
> beautifulsoup4                     4.9.0
> bitarray                           1.2.2
> bkcharts                           0.2
> bleach                             1.5.0
> bokeh                              2.0.2
> boto                               2.49.0
> Bottleneck                         1.3.2
> cachetools                         4.1.0
> certifi                            2020.4.5.1
> cffi                               1.14.0
> chardet                            3.0.4
> click                              7.1.2
> cloudpickle                        1.4.1
> clyent                             1.2.2
> colorama                           0.4.3
> comtypes                           1.1.7
> conda                              4.8.3
> conda-build                        3.10.5
> conda-package-handling             1.7.0
> conda-verify                       3.4.2
> contextlib2                        0.6.0.post1
> contextvars                        2.4
> cryptography                       2.9.2
> cycler                             0.10.0
> Cython                             0.29.17
> cytoolz                            0.10.1
> dask                               2.17.2
> decorator                          4.4.2
> defusedxml                         0.6.0
> diff-match-patch                   20181111
> distributed                        2.17.0
> docutils                           0.16
> entrypoints                        0.3
> et-xmlfile                         1.0.1
> fastcache                          1.1.0
> filelock                           3.0.12
> flake8                             3.8.2
> Flask                              1.1.2
> fsspec                             0.7.4
> future                             0.18.2
> gast                               0.3.3
> gevent                             1.4.0
> glob2                              0.7
> google-auth                        1.16.1
> google-auth-oauthlib               0.4.1
> google-pasta                       0.2.0
> greenlet                           0.4.15
> grpcio                             1.29.0
> h5py                               2.10.0
> HeapDict                           1.0.1
> html5lib                           0.9999999
> hypothesis                         5.11.0
> idna                               2.9
> imageio                            2.8.0
> imagesize                          1.2.0
> immutables                         0.11
> importlib-metadata                 1.6.1
> intervaltree                       3.0.2
> ipykernel                          5.1.4
> ipython                            7.13.0
> ipython-genutils                   0.2.0
> ipywidgets                         7.5.1
> isort                              4.3.21
> itsdangerous                       1.1.0
> jdcal                              1.4.1
> jedi                               0.15.2
> Jinja2                             2.11.2
> joblib                             0.15.1
> json5                              0.9.5
> jsonschema                         3.2.0
> jupyter                            1.0.0
> jupyter-client                     6.1.3
> jupyter-console                    6.1.0
> jupyter-core                       4.6.3
> jupyterlab                         1.2.6
> jupyterlab-server                  1.1.4
> Keras-Preprocessing                1.1.2
> keyring                            21.1.1
> kiwisolver                         1.2.0
> lazy-object-proxy                  1.4.3
> libarchive-c                       2.9
> llvmlite                           0.32.1
> locket                             0.2.0
> lxml                               4.5.0
> Markdown                           3.2.2
> MarkupSafe                         1.1.1
> matplotlib                         3.1.3
> mccabe                             0.6.1
> menuinst                           1.4.16
> mistune                            0.8.4
> mkl-fft                            1.0.15
> mkl-random                         1.1.1
> mkl-service                        2.3.0
> mock                               4.0.2
> more-itertools                     8.3.0
> mpmath                             1.1.0
> msgpack                            1.0.0
> multipledispatch                   0.6.0
> navigator-updater                  0.2.1
> nbconvert                          5.6.1
> nbformat                           5.0.6
> networkx                           2.4
> nltk                               3.4.5
> nose                               1.3.7
> notebook                           6.0.3
> numba                              0.49.1
> numexpr                            2.7.1
> numpy                              1.18.5
> numpydoc                           0.9.2
> oauthlib                           3.1.0
> olefile                            0.46
> openpyxl                           3.0.3
> opt-einsum                         3.2.1
> packaging                          20.3
> pandas                             1.0.3
> pandocfilters                      1.4.2
> paramiko                           2.7.1
> parso                              0.5.2
> partd                              1.1.0
> path                               13.1.0
> pathlib2                           2.3.5
> pathtools                          0.1.2
> patsy                              0.5.1
> pep8                               1.7.1
> pexpect                            4.8.0
> pickleshare                        0.7.5
> Pillow                             7.1.2
> pip                                20.1.1
> pkginfo                            1.5.0.1
> pluggy                             0.13.1
> ply                                3.11
> prometheus-client                  0.7.1
> prompt-toolkit                     3.0.5
> protobuf                           3.12.2
> psutil                             5.7.0
> py                                 1.8.1
> pyasn1                             0.4.8
> pyasn1-modules                     0.2.8
> pycodestyle                        2.6.0
> pycosat                            0.6.3
> pycparser                          2.20
> pycrypto                           2.6.1
> pycurl                             7.43.0.5
> pydocstyle                         4.0.1
> pyflakes                           2.2.0
> Pygments                           2.6.1
> pylint                             2.5.2
> PyNaCl                             1.3.0
> pyodbc                             4.0.0-unsupported
> pyOpenSSL                          19.1.0
> pyparsing                          2.4.7
> pyreadline                         2.1
> pyrsistent                         0.16.0
> PySocks                            1.7.1
> pytest                             5.4.2
> pytest-arraydiff                   0.3
> pytest-astropy                     0.8.0
> pytest-astropy-header              0.1.2
> pytest-doctestplus                 0.7.0
> pytest-openfiles                   0.5.0
> pytest-remotedata                  0.3.2
> python-dateutil                    2.8.1
> python-jsonrpc-server              0.3.4
> python-language-server             0.31.9
> pytz                               2020.1
> PyWavelets                         1.1.1
> pywin32                            227
> pywin32-ctypes                     0.2.0
> pywinpty                           0.5.7
> PyYAML                             5.3.1
> pyzmq                              18.1.1
> QDarkStyle                         2.8.1
> QtAwesome                          0.7.0
> qtconsole                          4.7.4
> QtPy                               1.9.0
> requests                           2.23.0
> requests-oauthlib                  1.3.0
> rope                               0.17.0
> rsa                                4.0
> Rtree                              0.9.4
> ruamel-yaml                        0.15.87
> scikit-image                       0.16.2
> scikit-learn                       0.22.1
> scipy                              1.4.1
> seaborn                            0.10.1
> Send2Trash                         1.5.0
> setuptools                         47.1.1.post20200604
> simplegeneric                      0.8.1
> singledispatch                     3.4.0.3
> six                                1.15.0
> snowballstemmer                    2.0.0
> sortedcollections                  1.1.2
> sortedcontainers                   2.1.0
> soupsieve                          2.0.1
> Sphinx                             3.0.4
> sphinxcontrib-applehelp            1.0.2
> sphinxcontrib-devhelp              1.0.2
> sphinxcontrib-htmlhelp             1.0.3
> sphinxcontrib-jsmath               1.0.1
> sphinxcontrib-qthelp               1.0.3
> sphinxcontrib-serializinghtml      1.1.4
> sphinxcontrib-websupport           1.2.1
> spyder                             4.1.3
> spyder-kernels                     1.9.1
> SQLAlchemy                         1.3.17
> statsmodels                        0.11.1
> sympy                              1.5.1
> tables                             3.5.1
> tblib                              1.6.0
> tensorboard                        2.2.2
> tensorboard-plugin-wit             1.6.0.post3
> tensorflow                         2.2.0
> tensorflow-estimator               2.2.0
> termcolor                          1.1.0
> terminado                          0.8.3
> testpath                           0.4.4
> toml                               0.10.0
> toolz                              0.10.0
> tornado                            6.0.4
> tqdm                               4.46.0
> traitlets                          4.3.3
> typed-ast                          1.4.1
> typing-extensions                  3.7.4.1
> ujson                              1.35
> unicodecsv                         0.14.1
> urllib3                            1.25.8
> watchdog                           0.10.2
> wcwidth                            0.1.9
> webencodings                       0.5.1
> Werkzeug                           1.0.1
> wheel                              0.34.2
> widgetsnbextension                 3.5.1
> win-inet-pton                      1.1.0
> win-unicode-console                0.5
> wincertstore                       0.2
> wrapt                              1.12.1
> xlrd                               1.2.0
> XlsxWriter                         1.2.9
> xlwings                            0.19.4
> xlwt                               1.3.0
> xmltodict                          0.12.0
> yapf                               0.28.0
> zict                               2.0.0
> zipp                               3.1.0
>

**Comment by amahendrakar** [comment]
@thepontiacbandit,
I was able to run the code without any issues. Could you please create a virtual environment and check if you are facing the same error.

Also, just to confirm are you running the code within Anaconda environment? Thanks!

**Comment by thepontiacbandit** [comment]
Yes, i was running in an anaconda virtual environment. 
The isssue was with CUDA  v10.2, 
running the same code after installation of v10.1, worked, 
Closing the issue, Thanks.
