### ISSUE TITLE
Need: Tensorflow for Unity plugin

### ISSUE THREAD

**Issue by Starsky-Synlitec** [tensorflow/tensorflow#40534]
**System information**
- TensorFlow version (you are using): 2.0.1

**Feature requested**
-Tensorflow for Unity plugin needed. 

For three reasons:

1.Although tensorflow lite can be used to build Android or IOS apps, developer prefer to use cross-platform IDEs so they only need to adapt and develop once.

2. Native Andoird (Android studio) or IOS (Xcode) are not really designed for 3D apps. For 3D developers, it is hard to create 3D scene and manipulate them in Android studio or Xcode. On the other hand, more and more AI  module in tensorflow can now show us 3d informaitons from 2D image (facemesh, hand pose, etc.), a 3d based IDE + tensorflow would be a better solution to use these 3d information in real productive apps.

3. There is no official release of Unity Tensorflow plugin, I tried some no-official ones, some of them can not use GPUs, some of them are full of bugs. Developers are strugglling finding a right version. If we have an official version, a large number of user would be increased.

**Comment by jdduke** [comment]
Here's an [example TFLite Unity plugin](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/examples/unity/TensorFlowLitePlugin). There are some community examples using this plugin, e.g., https://github.com/asus4/tf-lite-unity-sample. We don't have any plans to release a full TF Unity plugin.
