### ISSUE TITLE
Tensorflow tf function with numpy hyper-parameters and numpy calls

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/tensorflow#40537]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.2
- Python version: 3.6.8
- CUDA/cuDNN version: happens on CPU as well

**Describe the current behavior**

I am trying to build a `tf.function` which has numpy hyper-parameters and performs some numpy operations.
I currently am getting the following error:

```
NotImplementedError: in user code:

    <ipython-input-2-7da02a23bf62>:7 my_function  *
        range_array = np.arange(range_lim)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:749 __array__  **
        " array.".format(self.name))

    NotImplementedError: Cannot convert a symbolic Tensor (strided_slice:0) to a numpy array.
```

**Describe the expected behavior**

I would like `tf.function` to be able to handle functions with numpy code in them.

**Standalone code to reproduce the issue**
My current minimal reproducible example is the following ([colab link](https://colab.research.google.com/drive/1VWkX7sQP4QKd52qb4S1pCZXAJPjuWYpk?usp=sharing)):

```python
import numpy as np
import tensorflow as tf

@tf.function
def my_function(params):
  np_array = params['np_array']
  my_list = []
  for i in range(2):
    range_lim = np_array[i]
    range_array = np.arange(range_lim)
    my_list.append(range_array)
  # then do other things

params = {'np_array': np.array([4, 5])}

my_function(params)
```

**Other info / logs**
When I look at the autograph generated code, using `print(tf.autograph.to_code(my_function.python_function))`, I see that the pure-numpy call `range_array = np.arange(range_lim)` is converted:

```python
range_array = ag__.converted_call(np.arange, (range_lim,), None, fscope)
```
I think this is where the bug is coming from: autograph is called on a line which shouldn't be transformed.

**Comment by Saduf2019** [comment]
@zaccharieramzi 
Please refer to issues with similar error:
[link](https://stackoverflow.com/questions/58479556/notimplementederror-cannot-convert-a-symbolic-tensor-2nd-target0-to-a-numpy) [link1](https://github.com/krasserm/super-resolution/issues/35) [link2](https://cnasolution.com/questions/223061/notimplementederror-cannot-convert-a-symbolic-tensor-up-sampling2d-4-target-0-to-a-numpy-array).

**Comment by zaccharieramzi** [comment]
The [first one](https://stackoverflow.com/questions/58479556/notimplementederror-cannot-convert-a-symbolic-tensor-2nd-target0-to-a-numpy) is actually just a confusion in writing between tensors and numpy arrays.
The [second one](https://github.com/krasserm/super-resolution/issues/35) is seemingly a version problem.
The [third one](https://cnasolution.com/questions/223061/notimplementederror-cannot-convert-a-symbolic-tensor-up-sampling2d-4-target-0-to-a-numpy-array) from what I gather although not clear is also about the confusion between numpy arrays and tensors.

**Comment by gowthamkpr** [comment]
@zaccharieramzi tf.function works best with TensorFlow ops; NumPy and Python calls are converted to constants

**Comment by zaccharieramzi** [comment]
Oh are you saying that `np_array` is converted to a constant Tensor? that's why `range_lim` would be a Tensor (`(strided_slice:0)` more specifically) that can't be used to do a numpy call.

I think maybe then it should be made clearer in the documentation that all python and numpy objects are converted to constants (I don't think it's the call that is converted to a constant but rather the object itself). Wdyt?

**Comment by gowthamkpr** [comment]
@zaccharieramzi Its mentioned clearly in the documentation [here](https://www.tensorflow.org/guide/function). Please take a look at it and let me know if it helps. Thanks!

**Comment by zaccharieramzi** [comment]
Hahaha ok my bad indeed !
