### ISSUE TITLE
Make keras.callbacks.Callback and tensorflow.keras.callbacks.Callback mutually compatible

### ISSUE THREAD

**Issue by PiotrJander** [tensorflow/tensorflow#40548]
`tensorflow.keras.callbacks.Callback` has private methods [`_implements_train_batch_hooks`](https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/keras/callbacks.py#L739) etc which are [called](https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/keras/callbacks.py#L328) e.g. when the callback is used with `tensorflow.keras.models.Model.fit`.

`keras.callbacks.Callback` provides no such methods and so using it with e.g. `tensorflow.keras.models.Model.fit` results in `AttributeError: 'SomeClassExtendingCallback' object has no attribute '_implements_train_batch_hooks'`.

If those two versions of Keras aim to be compatible, then this should be fixed.

**Comment by amahendrakar** [comment]
@PiotrJander,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by PiotrJander** [comment]
Versions:

```
tensorflow==2.2.0
Keras==2.3.1
```

Minimal example:

```python
import neptune
from tensorflow import keras
from keras.callbacks import BaseLogger

mnist = keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = keras.models.Sequential([
  keras.layers.Flatten(),
  keras.layers.Dense(100, activation=keras.activations.softmax)
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train,
          epochs=5,
          batch_size=256,
          callbacks=[BaseLogger()])
```

Output and error:

```
Using TensorFlow backend.
2020-06-19 10:32:15.050829: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-06-19 10:32:15.069239: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7ff6bf6ae880 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-19 10:32:15.069257: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "tf-issue.py", line 18, in <module>
    model.fit(x_train, y_train,
  File "/Users/piotr/projects/neptune-sandbox/.env/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/Users/piotr/projects/neptune-sandbox/.env/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 819, in fit
    callbacks = callbacks_module.CallbackList(
  File "/Users/piotr/projects/neptune-sandbox/.env/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 230, in __init__
    self._should_call_train_batch_hooks = any(
  File "/Users/piotr/projects/neptune-sandbox/.env/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 231, in <genexpr>
    cb._implements_train_batch_hooks() for cb in self.callbacks)
AttributeError: 'BaseLogger' object has no attribute '_implements_train_batch_hooks
```

I hope this helps!

**Comment by kl5017** [comment]
> Versions:
> 
> ```
> tensorflow==2.2.0
> Keras==2.3.1
> ```
> 
> Minimal example:
> 
> ```python
> import neptune
> from tensorflow import keras
> 
> # this is an import from standalone Keras, as opposed to the Keras shipped with TF
> from keras.callbacks import BaseLogger 
> 
> mnist = keras.datasets.mnist
> (x_train, y_train), (x_test, y_test) = mnist.load_data()
> x_train, x_test = x_train / 255.0, x_test / 255.0
> 
> model = keras.models.Sequential([
>   keras.layers.Flatten(),
>   keras.layers.Dense(100, activation=keras.activations.softmax)
> ])
> 
> model.compile(optimizer='adam',
>               loss='sparse_categorical_crossentropy',
>               metrics=['accuracy'])
> 
> model.fit(x_train, y_train,
>           epochs=5,
>           batch_size=256,
>           callbacks=[BaseLogger()])
> ```
> 
> Output and error:
> 
> ```
> Using TensorFlow backend.
> 2020-06-19 10:32:15.050829: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2020-06-19 10:32:15.069239: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7ff6bf6ae880 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
> 2020-06-19 10:32:15.069257: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
> Traceback (most recent call last):
>   File "tf-issue.py", line 18, in <module>
>     model.fit(x_train, y_train,
>   File "/Users/piotr/projects/neptune-sandbox/.env/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
>     return method(self, *args, **kwargs)
>   File "/Users/piotr/projects/neptune-sandbox/.env/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 819, in fit
>     callbacks = callbacks_module.CallbackList(
>   File "/Users/piotr/projects/neptune-sandbox/.env/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 230, in __init__
>     self._should_call_train_batch_hooks = any(
>   File "/Users/piotr/projects/neptune-sandbox/.env/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 231, in <genexpr>
>     cb._implements_train_batch_hooks() for cb in self.callbacks)
> AttributeError: 'BaseLogger' object has no attribute '_implements_train_batch_hooks
> ```
> 
> I hope this helps!

same issue

**Comment by amahendrakar** [comment]
> `keras.callbacks.Callback` provides no such methods and so using it with e.g. `tensorflow.keras.models.Model.fit` results in `AttributeError: 'SomeClassExtendingCallback' object has no attribute '_implements_train_batch_hooks'`.

@PiotrJander,
You are facing this error because of the mixed up imports of `keras` and `tf.keras`. 

I was able to run the code without any issues using [keras](https://colab.research.google.com/gist/amahendrakar/9bb1bc3830a1b184c0d21ca6f4bbf9b3/40548-keras.ipynb), whereas I'm facing an error stating `KeyError: 'metrics'` on running the code with [tf.keras](https://colab.research.google.com/gist/amahendrakar/4c583e22e490ace733b043e48e8c135e/40548-tf-keras.ipynb#scrollTo=tmmFSCO_mhdV). Please check the linked gist. 

For more information, please take a look at [this](https://stackoverflow.com/a/57123200) StackOverflow comment. Thanks!

**Comment by PiotrJander** [comment]
Thank you. I knew this is due to mixing up `keras` and `tf.keras`, I just wanted to raise this in case mutual compatibility were a goal.

Perhaps the docs should state visibly that `keras` and `tf.keras` are not mutually compatible?

**Comment by kl5017** [comment]
I solved this problem by using tensorflow==1.14.0 and keras==2.3.1

**Comment by gowthamkpr** [comment]
@PiotrJander This is a well known fact in the tensorflow community.

tf.keras is the Tensorflow specific implementation of the Keras API specification. It adds the framework the support for many Tensorflow specific features like: perfect support for tf.data.Dataset as input objects, support for eager execution, ...

In Tensorflow 2.0 tf.keras will be the default and I highly recommend to start working using tf.keras

**Comment by PiotrJander** [comment]
Sure, we can close this

**Comment by parijatparimal29** [comment]
Using tensorflow.keras instead of keras worked for me. Thanks!

**Comment by Kanishk-03-Jain** [comment]
Code: 
```
import pandas as pd
from transformers import BertTokenizer, TFBertForSequenceClassification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

# Load your dataset
df = pd.read_csv('/kaggle/input/complaints10k/indian_railway_complaints_10k.csv')

# Encode the labels
label_encoder = LabelEncoder()
df['label'] = label_encoder.fit_transform(df['Complaint Category'])

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(df['Complaint'], df['label'], test_size=0.2, random_state=42)

# Load pre-trained BERT tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Tokenize the input texts
def tokenize(sentences, tokenizer, max_len=128):
    return tokenizer(
        sentences.tolist(),
        max_length=max_len,
        truncation=True,
        padding=True,
        add_special_tokens=True,  # Add [CLS] and [SEP]
        return_tensors='tf'       # Return TensorFlow tensors
    )

X_train_tokenized = tokenize(X_train, tokenizer)
X_test_tokenized = tokenize(X_test, tokenizer)
# Load BERT model for sequence classification
model = TFBertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=len(categories))

# Compile the model
# optimizer = Adam(learning_rate=2e-5)
model.compile(optimizer= 'adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

# Define EarlyStopping and ReduceLROnPlateau callbacks
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=2, min_lr=1e-5) #reduce learning rate when mteric not improving

# Train the model
history = model.fit(
    train_dataset,
    validation_data=val_dataset,
    epochs=3,
    callbacks=[early_stopping, reduce_lr]
)
```
Output: 
```

AttributeError                            Traceback (most recent call last)
Cell In[76], line 8
      5 reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=2, min_lr=1e-5) #reduce learning rate when mteric not improving
      7 # Train the model
----> 8 history = model.fit(
      9     train_dataset,
     10     validation_data=val_dataset,
     11     epochs=3,
     12     callbacks=[early_stopping, reduce_lr]
     13 )

File /opt/conda/lib/python3.10/site-packages/transformers/modeling_tf_utils.py:1229, in TFPreTrainedModel.fit(self, *args, **kwargs)
   1226 @functools.wraps(keras.Model.fit)
   1227 def fit(self, *args, **kwargs):
   1228     args, kwargs = convert_batch_encoding(*args, **kwargs)
-> 1229     return super().fit(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/tf_keras/src/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File /opt/conda/lib/python3.10/site-packages/tf_keras/src/callbacks.py:245, in <genexpr>(.0)
    237 # Performance optimization: determines if batch hooks need to be called.
    239 self._supports_tf_logs = all(
    240     getattr(cb, "_supports_tf_logs", False) for cb in self.callbacks
    241 )
    242 self._batch_hooks_support_tf_logs = all(
    243     getattr(cb, "_supports_tf_logs", False)
    244     for cb in self.callbacks
--> 245     if cb._implements_train_batch_hooks()
    246     or cb._implements_test_batch_hooks()
    247     or cb._implements_predict_batch_hooks()
    248 )
    250 self._should_call_train_batch_hooks = any(
    251     cb._implements_train_batch_hooks() for cb in self.callbacks
    252 )
    253 self._should_call_test_batch_hooks = any(
    254     cb._implements_test_batch_hooks() for cb in self.callbacks
    255 )

AttributeError: 'EarlyStopping' object has no attribute '_implements_train_batch_hooks'
```

I am still facing the issue even though I am using tf.keras

**Comment by othnielObasi** [comment]
Please has there been any way to resolve  this issue :"AttributeError: 'EarlyStopping' object has no attribute" '_implements_train_batch_hooks'. Despite  using from tensorflow.keras.callbacks import EarlyStopping, the issue still persist

**Comment by TinChung41** [comment]
The issue still persist for me, we might have to open a new issue

**Comment by saran1995** [comment]
Facing same issue even after using tf.keras also I need tf >2.0 so cannot use the downgrade solution as well (pip install --upgrade "tensorflow==1.4" "keras>=2.0")
