### ISSUE TITLE
TF 2.2 GPU memory usage regression on model.predict() with big inputs

### ISSUE THREAD

**Issue by alkamid** [tensorflow/tensorflow#40547]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: Ubuntu 16.04
- TensorFlow installed from: PyPI
- TensorFlow version : v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.7.1
- CUDA/cuDNN version: 10.1
- GPU model and memory: NVIDIA Tesla M60, 8GB

**Describe the current behavior**

I created a 3D Unet which takes 192x192x192 inputs and outputs a segmentation of the same size. I did not train the network but tried passing dummy inputs to `model.predict()` instead. I'm getting an OOM error when I limit the available GPU memory to 5GB on an input of size (70, 192, 192, 192, 1) (`batch_size=1`). I don't get the same error on TF 2.1 with the same input size. In order for the script to work on 2.2, I need to increase available memory to 5.7GB.
The exception is raised repeatably at batch 47 of 70.
I can't see anything related in v2.2 changelog, which leads me to believe that this is a regression.

**Describe the expected behavior**
For `batch_size=1`, I expect the inputs to be transferred to GPU memory one by one, and the outputs to be transferred back to RAM sequentially. There should not be significant GPU memory usage differences between predicting on 1000 inputs and 100 inputs. There probably should be a buffer such that the next batch of prediction is not held up by GPU-RAM I/O, but a difference of 700MB is suspicious.
I could work around this by splitting the prediction and then concatenating it like so:
```
MAX_INPUT_SIZE = 47
pred1 = model.predict(test_input[:MAX_INPUT_SIZE], batch_size=1)
pred2 = model.predict(test_input[MAX_INPUT_SIZE:], batch_size=1)
```
but this should probably be done by TF, not the user. Am I seeing a feature or a bug? 

**Standalone code to reproduce the issue**
```python
import numpy as np
from tensorflow.keras import Input
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv3D, BatchNormalization, Activation, Layer, MaxPool3D, Conv3DTranspose, Concatenate

import tensorflow as tf


def limit_gpu_memory_use(limit=None):
    gpus = tf.config.experimental.list_physical_devices("GPU")
    for gpu in gpus:
        if limit is None:
            tf.config.experimental.set_memory_growth(gpu, True)
        else:
            tf.config.experimental.set_virtual_device_configuration(
                gpu, [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=limit)]
                )


def test_big_model():
    # TF 2.1: 5000, TF 2.2: 5700
    limit_gpu_memory_use(5000)
    model = build_model()
    test_input = np.ones(shape=(70, 192, 192, 192, 1), dtype=np.int16)
    model.predict(test_input, verbose=1, batch_size=1)


def build_model():
    depth = 4
    n_base_filters = 8
    actfun = "relu"

    skip_layers = []
    inputs = Input(shape=(192, 192, 192, 1))
    x = Conv3D(
        filters=n_base_filters,
        kernel_size=(3, 3, 3),
        activation=actfun,
        padding="same",
    )(inputs)

    x = BatchNormalization()(x)
    x = Conv3D(
        filters=n_base_filters * 2,
        kernel_size=(3, 3, 3),
        activation=actfun,
        padding="same",
    )(x)

    skip_layers.append(x)

    for i in range(1, depth):
        x = create_downsampling_block(input_layer=x, num_filters=n_base_filters * 2 ** i, actfun=actfun)
        skip_layers.append(x)

    for i in range(depth - 1, 0, -1):
        x = create_upsampling_block(
            input_layer=x,
            skip_input_layer=skip_layers[i - 1],
            num_filters=n_base_filters * 2 ** (i + 1),
            actfun=actfun,
        )

    x = Conv3D(filters=1, kernel_size=(1, 1, 1))(x)
    out = Activation("sigmoid", dtype="float32")(x)

    return Model(inputs=inputs, outputs=out)


def create_downsampling_block(input_layer: Layer, num_filters: int, actfun: str) -> Layer:
    x = MaxPool3D(pool_size=(2, 2, 2))(input_layer)
    for i in [1, 2]:
        x = Conv3D(
            filters=num_filters * i,
            kernel_size=(3, 3, 3),
            activation=actfun,
            padding="same",
        )(x)
    return x


def create_upsampling_block(input_layer: Layer, skip_input_layer: Layer, num_filters: int, actfun: str) -> Layer:
    x = Conv3DTranspose(filters=num_filters, kernel_size=(2, 2, 2), strides=(2, 2, 2))(input_layer)
    x = Concatenate()([skip_input_layer, x])
    for _ in range(2):
        x = Conv3D(
            filters=num_filters // 2,
            kernel_size=(3, 3, 3),
            activation=actfun,
            padding="same",
        )(x)

    return x

test_big_model()
```

**Other info / logs** 
[traceback.log](https://github.com/tensorflow/tensorflow/files/4793605/traceback.log)

**Comment by Saduf2019** [comment]
@alkamid 
Please let us know if [this gist](https://colab.research.google.com/gist/Saduf2019/cf62fcb02d8a75e68c9c3fb5a28f6736/untitled237.ipynb) confirms your issue.

**Comment by alkamid** [comment]
@Saduf2019 yes, it does. The point at which the gist fails (30/70) is different, but I suppose it might be environment-dependent.

**Comment by alkamid** [comment]
I can reproduce the error on TF 2.3 and CUDA 10.2.

**Comment by torabshaikh** [comment]
@Saduf2019 I can reproduce the issue with the provided example and want to try to resolve it. I want to start contributing to the repo. Can you please guide me on that?

**Comment by rmothukuru** [comment]
Could reproduce the issue with **`Tensorflow Version, 2.5`**. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/d255a4f5b7106f424675e0f126df2a95/untitled237.ipynb#scrollTo=hAsAgD-9PHSi). Thanks!

**Comment by kretes** [comment]
In [this gist](https://colab.research.google.com/drive/17GvpewWCpnrMq6ozrKUYphirpA1SuWxr?usp=sharing) I have reproduced the issue with tensorflow 2.6, using IODataset.from_numpy() as an input source, as this was suggested (e.g. https://github.com/tensorflow/tensorflow/issues/44711#issuecomment-736186819) as a way to handle large inputs in a more memory-optimized way.

**Comment by kretes** [comment]
This is still there in tf 2.7 - see [Colab](https://colab.research.google.com/drive/1PqNtXN1ojugT9yt1Prs49GcwhMIShXJv?usp=sharing)

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
