### ISSUE TITLE
how to get image's shape using tf.data map

### ISSUE THREAD

**Issue by colorful-ocean** [tensorflow/tensorflow#40541]
my dataset is large and the image is irregular. I need to pad the image according to different width and length, but I can't get the image's shape using image.shape. The shape is [None, None, 3].

**Comment by iobtl** [comment]
Have you applied any image resizing/altering functions using `tf.image` operations? Namely, from here: https://www.tensorflow.org/api_docs/python/tf/image

You can chain together such operations in a separate function then pass it to a `tf.data.Dataset.map` function. For instance,

```python
def preprocess_image(image):
    # .. define your desired operations here
    return preprocessed_image

ds = tf.data.Dataset.from_tensor_slices(...)
ds = ds.map(preprocess_image)
```

**Comment by Saduf2019** [comment]
@colorful-ocean 
Please update as per above comment.

**Comment by colorful-ocean** [comment]
@iobtl

def process_image(image, hw_dst=416):
    h_src, w_src = image.shape[:2]
    
    if h_src>w_src:
        scales = hw_dst/h_src
        h_resize = hw_dst
        w_resize = int(w_src*scales)
    else:
        scales = hw_dst/w_src
        h_resize = int(h_src*scales)
        w_resize = hw_dst
    
    image = tf.image.convert_image_dtype(image, dtype=tf.float32)#/255.
    image = tf.image.resize(image, [h_resize, w_resize])
    #image = tf.math.divide(image, 255.)
    image = tf.image.pad_to_bounding_box(image, 0, 0, hw_dst, hw_dst)
    return image, scales

I need to pad the image according to different width and length, like the function above. use map method can't work, because the **image.shape** is (None,None,3)

**Comment by iobtl** [comment]
How are you forming your `tf.data.Dataset` object? Could you try generating the output from the following code:
```python
ds = tf.data.Dataset.from_tensor_slices(image_paths)
ds = ds.map(tf.io.read_file)
ds = ds.map(tf.image.decode_jpeg)

for image in ds.take(5):
    print(image.shape)
```

To verify your image shapes. Using `tf.data.Dataset.map` is not an issue even if you have different image shapes. The image.shape is (None, None, 3) because you have different image shapes for every image.

**Comment by colorful-ocean** [comment]
@iobtl 
yes，but I need divide the img's h and w. This will get error, because it is None.
```python
    hr_image = tf.io.read_file(image_path)
    hr_image = tf.io.decode_png(hr_image, channels=3)
    
    h_src, w_src = hr_image.shape[:2]
    inp_h, inp_w = input_shape
    
    lr_h, lr_w = h_src//downscale+1, w_src//downscale+1
    hr_h, hr_w = lr_h*downscale, lr_w*downscale
```

```
    <ipython-input-2-1c8a4b52a1ec>:21 make_dataset  *
        lr_h, lr_w = h_src//downscale+1, w_src//downscale+1

    TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'
```
**This problem has been bothering me**

**Comment by colorful-ocean** [comment]
@iobtl
I found the solution! 
**fail**
```python
    h_src, w_src = hr_image.shape[:2]
```
**fail**
```python
    h_src, w_src = tf.shape(hr_image)[:2]
```
**success**
```python
    h_src = tf.shape(hr_image)[0]
    w_src = tf.shape(hr_image)[1] 
```
finally!

**Comment by bm777** [comment]
h_src = tf.shape(hr_image)[0]; w_src = tf.shape(hr_image)[1]


Le mar. 23 juin 2020 à 15:01, colorful-ocean <notifications@github.com> a
écrit :

**Comment by RobinKips** [comment]
using tf.shape does not seems to work depending on which method will use the image shape. For instance: 

**working**
```python
def rnd_crop(img):
    w = tf.shape(img)[0]
    h = tf.shape(img)[1]
    c = tf.shape(img)[2]
    crop_size = (w,h,c)
    img_crop = tf.reshape(img, crop_size)
    return img_crop
```

**not working** 
```python
def rnd_crop(img):
    w = tf.shape(img)[0]
    h = tf.shape(img)[1]
    c = tf.shape(img)[2]
    crop_size = (w,h,c)
    img_crop = tf.image.random_crop(img,  crop_size)
    return img_crop
```

I am getting the folloring error 

>  ValueError: Dimensions must be equal, but are 4 and 3 for '{{node random_crop/GreaterEqual}} = GreaterEqual[T=DT_INT32](random_crop/Shape, random_crop/size)' with input shapes: [4], [3].

it seems that the shape of the image in tf.image.random.crop does not has the same rank as the one returned by tf.shape...
