### ISSUE TITLE
Installed Tensorflow-directml show no module named tensorflow

### ISSUE THREAD

**Issue by limapedro** [tensorflow/tensorflow#40549]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
 import tensorflow as tf
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 1903
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):  pip install tensorflow-directml==0.0.1.dev0
- TensorFlow version (use command below):
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

So the long waited Directml was released today, but it seems that the package wasn't compiled yet
, I installed through pypi, obviously that size of wheel is 6.4 KB, which isn't right
, should be about 200 MB or so.

**Describe the expected behavior**

Any schedule on when the proper wheels will be released? 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by jstoecker** [comment]
Hi limapedro,

The tensorflow-directml PyPI package is a placeholder until the project's [size limit is increased](https://github.com/pypa/pypi-support/issues/457). For now, you'll need to get the actual packages from our [GitHub ](https://github.com/microsoft/DirectML/releases/tag/tensorflow-directml-1.15.3.dev200615)(notes for [Windows](https://docs.microsoft.com/en-us/windows/win32/direct3d12/gpu-tensorflow-windows); notes for [WSL](https://docs.microsoft.com/en-us/windows/win32/direct3d12/gpu-tensorflow-wsl)).

Thanks for testing this out!

**Comment by limapedro** [comment]
@jstoecker Thank you.

**Comment by ravikyram** [comment]
@limapedro 

was this resolved by following @jstoecker  suggestion? Please close the issue if it was resolved already. Thanks!

**Comment by limapedro** [comment]
@ravikyram It's all working now, the pypi page is working, you can see the files for the project here: https://pypi.org/project/tensorflow-directml/#files
