### ISSUE TITLE
AttributeError: type object 'TFLiteConverterV2' has no attribute 'from_keras_model_file'

### ISSUE THREAD

**Issue by MevadaRavikumar** [tensorflow/tensorflow#40550]
I am having one TensorFlow Keras model "model.h5". I want to generate tflite from it. I am using the below-mentioned code for that. I am using tensorflow version '2.0.0' on Anaconda Spyder 3.7, 64 bit, windows10. Later on I want to convert this model for the google coral edge tpu. 

    import tensorflow as tf
    import numpy as np
    from tensorflow import lite

    dataset_dir = "C:\\Users\\Ravi\\dataset"
    IMAGE_SIZE = 224
    saved_keras_model = "C:\\Users\\Ravi\\model.h5"

    def representative_data_gen():
      dataset_list = tf.data.Dataset.list_files(dataset_dir + '/*/*')
      for i in range(100):
        image = next(iter(dataset_list))
        image = tf.io.read_file(image)
        image = tf.io.decode_jpeg(image, channels=3)
        image = tf.image.resize(image, [IMAGE_SIZE, IMAGE_SIZE])
        image = tf.cast(image / 255., tf.float32)
        image = tf.expand_dims(image, 0)
        yield [image]

    converter =  lite.TFLiteConverter.from_keras_model_file(saved_keras_model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    # This ensures that if any ops can't be quantized, the converter throws an error
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    # These set the input and output tensors to uint8
    converter.inference_input_type = tf.uint8
    converter.inference_output_type = tf.uint8
    # And this sets the representative dataset so we can quantize the activations
    converter.representative_dataset = representative_data_gen
    tflite_model = converter.convert()

    with open('mobilenet_v2_1.0_224_quant.tflite', 'wb') as f:
          f.write(tflite_model)

I am getting this kind of error.

    Traceback (most recent call last):

     File "C:\Users\Ravi\tflite_model.py", line 28, in <module>
        converter =  lite.TFLiteConverter.from_keras_model_file(saved_keras_model)

    AttributeError: type object 'TFLiteConverterV2' has no attribute 'from_keras_model_file'

What can be the problem? How can I solve this issue?

**Comment by abattery** [comment]
You can either depend on the following choices:

1) After loading a keras model instance, you can use `tf.lite.TFLiteConverter.from_keras_model`.

```
from tensorflow import keras
model = keras.models.load_model('path/to/location')
```

2) Or you can use the v1 API, `tf.compat.v1.lite.TFLiteConverter.from_keras_model_file`.

**Comment by MevadaRavikumar** [comment]
I have tried with the "tf.compat.v1.lite.TFLiteConverter.from_keras_model_file". Now I am getting value error. 

    ValueError: Cannot set tensor: Got tensor of type STRING but expected type FLOAT32 for input 183, name: input_1 

    INFO:tensorflow:Froze 264 variables.
    INFO:tensorflow:Converted 264 variables to const ops.
    Traceback (most recent call last):

      File "C:\Users\Ravi\tflite_model.py", line 47, in <module>
    tflite_model = converter.convert()

      File "C:\Users\Ravi\anaconda3\lib\site-packages\tensorflow\lite\python\lite.py", line 908, in convert
    inference_output_type)

      File "C:\Users\Ravi\anaconda3\lib\site-packages\tensorflow\lite\python\lite.py", line 200, in _calibrate_quantize_model
    inference_output_type, allow_float)

      File "C:\Users\Ravi\anaconda3\lib\site-packages\tensorflow\lite\python\optimize\calibrator.py", line 75, in calibrate_and_quantize
    self._calibrator.FeedTensor(calibration_sample)

      File "C:\Users\Ravi\anaconda3\lib\site-packages\tensorflow\lite\python\optimize\tensorflow_lite_wrap_calibration_wrapper.py", line 112, in FeedTensor
        return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_FeedTensor(self, input_value)

    ValueError: Cannot set tensor: Got tensor of type STRING but expected type FLOAT32 for input 183, name: input_1

**Comment by MevadaRavikumar** [comment]
I have tried on google colab and it worked!
