### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by pvnieo** [tensorflow/tensorflow#40558]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): pip install --upgrade tensorflow
- TensorFlow version (use command below): v1.14.0-rc1-22-gaf24dc91b5 1.14.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.2
- GPU model and memory: GeForce RTX 2080, 12GB

**Describe the current behavior**
Hi, 
I installed tensorflow from source in python3 using cuda 10.2. But when I run my script, I got this error without any further details:
```
Segmentation fault (core dumped)
```
What is the cause of this issue?

Thank you in advance.

**Comment by ravikyram** [comment]
@pvnieo 

Can you try with cuda 10.0 and see if the problem still persists.Please, see tested build configuration from [here](https://www.tensorflow.org/install/source#gpu).Also refer few related issues #39939,#36841 #37689 #35968 #36201 and see if it helps you. Request you to share the exact sequence of commands / steps that you executed before running into the problem.Thanks!
