### ISSUE TITLE
TFLite General OpenGL delegate 

### ISSUE THREAD

**Issue by WHSnyder** [tensorflow/tensorflow#40555]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.2/master on Ubuntu 18.04
- Are you willing to contribute it (Yes/No): Yes, I have a working version on TF 2.2.

**Describe the feature and the current behavior/state.**
Deprecated GL delegate runs in the GL context attached to the calling thread, instead of initializing an EGL/GLES context upon preparation.           

**Will this change the current api? How?**
This change would allow builds to macro out all references to EGL/GLES in the deprecated gl_delegate package.  A build target ~"libgeneral_opengl.so" would be added to the lite/delegates/gpu BUILD file.  Users would provide paths to the relevant OpenGL headers (glew, glad, gl3w...) and link flags in the BUILD file.  The GL context would be initialized outside of the TFLite API. 

**Who will benefit with this feature?**
Anyone looking to integrate TFLite into their OpenGL render pipeline, without having to deal with GLES/Android dependencies.  Particularly useful for Linux users looking to build plugins for other engines e.g. Unreal or Unity.  

**Any Other info.**
Perfectly understandable if this change is undesired, since simple GPU acceleration for Android is the only reason the GL delegate exists.  Asking here before PRing so I don't waste time merging into master from my 2.2 based branch.

**Comment by wangtz** [comment]
"Anyone looking to integrate TFLite into their OpenGL render pipeline, without having to deal with GLES/Android. Particularly useful for Linux users looking to build plugins for other engines e.g. Unreal or Unity."

This sounds interesting. Adding people who know more about this.

**Comment by WHSnyder** [comment]
Also, I'm not sure how deprecation works at the scale of a project like TF.  Either, 
1) you don't people adding to a deprecated feature, because it will soon be removed entirely, 
2 you don't want additions because that will result in support requests for something the TF team would rather ignore, or
3) adding to deprecated features is fine, because they're deprecated and thus nobody is obligated to support them.

I tested this idea with the deprecated GL delegate for simplicity's sake.  If it's on the chopping block I'll refocus to making the gl package changes work with the V2 multi-backend delegate. 

I figured this change would hold similar status to the MacOS Metal delegate changes. Documentation would be provided through comments.  Support would just be "best effort."

**Comment by WHSnyder** [comment]
Hi, just checking in to see if anyone has an update on this.  I was also wondering if anyone plans on upgrading the GL delegate's [mean kernel](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/gl/kernels/mean.cc) from the current naive implementation.
`
      highp vec4 sum = vec4(0.0);
      highp float size = float($input_data_0_w$ * $input_data_0_h$);
      for (int w = 0; w < $input_data_0_w$; w++) {
        for (int h = 0; h < $input_data_0_h$; h++) {
          sum += $input_data_0[w, h, gid.z]$;
        }
      }
      value_0 = sum / size;`
I was testing my real time style transfer demo with a 1660ti and the mean kernel was a staggering bottleneck.  For now I just approximate the mean by increasing the loop's increment to 8 and multiplying the result by 64 (12 -> 76 fps boost).  Unless someone plans on parallelizing it across more workgroups soon I might take a whack at it.  Diving through the TFL compiler structure should be a windy rabbit hole 😊

**Comment by impjdi** [comment]
Sorry for the late response; I somehow failed to prioritize certain github issues and just read this.

Due to the small team size, it's impossible for us to accommodate non-Android use cases.  We know that with a small change, things can run on Linux desktops using Mesa, but hey, it didn't run on my desktop, so we're not even trying to sell that it works on Linux desktops.  If you're trying to employ the OpenGL ES backend for some other platform, you're unfortunately on your own and we won't be able to help.

re: the deprecated delegate, we will just remove it from the repository.  In fact, it hasn't been updated for quite some time unlike the new v2 delegate, so I suggest that you switch over.

re: `MEAN`, you may want to check the OpenCL kernels.  That may have better kernel implementations.

**Comment by WHSnyder** [comment]
@impjdi Thanks for the update!  My apologies for the lag in this response.  Just to be clear, the ```gl_delegate.cc/.h``` files will be removed, but most/all files in ```delegates/gpu/gl/``` will stay for use in the v2 delegate?  I ask because developed a new ```MEAN``` GLSL kernel that runs fast enough for real-time style transfer on Android phones, and I don't want dig into the official testing process if _all_ OpenGL delegation will be removed/replaced by OpenCL.

**Comment by impjdi** [comment]
That is correct.  We probably can't remove OpenGL in favor of OpenCL, because OpenCL is not available on all Android devices.
