### ISSUE TITLE
Tensorflow Roadmap README link broken

### ISSUE THREAD

**Issue by 4d55397500** [tensorflow/tensorflow#40551]
Link to 'Tensorflow Roadmap' in README is broken: https://www.tensorflow.org/community/roadmap

This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by amahendrakar** [comment]
@4d55397500,
Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/37509#issuecomment-598049023) from a similar issue and let us know if it helps. Thanks!

**Comment by 4d55397500** [comment]
Ah I see @amahendrakar

**Comment by amahendrakar** [comment]
@4d55397500,
Hope the above comment answers your query. Please feel free to close the issue if resolved. Thanks!
