### ISSUE TITLE
populateTypeInferenceInfo hits assertion when generating type inference interface for tf_ops

### ISSUE THREAD

**Issue by summacod** [tensorflow/tensorflow#40559]
mlir-tblgen: external/llvm-project/mlir/lib/TableGen/Type.cpp:22: mlir::tblgen::TypeConstraint::TypeConstraint(const llvm::Record*): Assertion `def->isSubClassOf("TypeConstraint") && "must be subclass of TableGen 'TypeConstraint' class"' failed.

**System information**
- Linux Ubuntu 20.04
- TensorFlow installed from source
- TensorFlow version: Latest from source
- Python version: 3.8.2
- Installed using virtualenv? NO
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: 11.0
- GPU model and memory: GeForce RTX 2070 8G

bazel build --config=opt --config=noaws --config=nogcp //tensorflow/tools/pip_package:build_pip_package --verbose_failures

ERROR: /home/xxxxx/Downloads/tensorflow/tensorflow/compiler/mlir/tensorflow/BUILD:62:1: Generating code from table: ir/tf_ops.td //tensorflow/compiler/mlir/tensorflow:tensorflow_ops_inc_gen__gen_op_defs_genrule failed (Aborted): bash failed: error executing command 
  (cd /home/xxxx/.cache/bazel/_bazel_xxxxx/b7319a1803ca3236e14ad4085fc7b534/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda-11.0 \
    GCC_HOST_COMPILER_PATH=/usr/bin/x86_64-linux-gnu-gcc-9 \
    PATH=/home/xxxxx/anaconda3/condabin:/home/xxxxx/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    TF2_BEHAVIOR=1 \
    TF_CONFIGURE_IOS=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=7.5 \
    TF_ENABLE_XLA=1 \
    TF_NEED_CUDA=1 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/external/llvm-project/mlir/mlir-tblgen -gen-op-defs tensorflow/compiler/mlir/tensorflow/ir/tf_ops.td -Ibazel-out/k8-opt/bin -I external/llvm-project/mlir/include -I external/org_tensorflow -I bazel-out/k8-opt/bin/external/llvm-project/mlir/include -I $(dirname tensorflow/compiler/mlir/tensorflow/ir/tf_ops.td) -o bazel-out/k8-opt/bin/tensorflow/compiler/mlir/tensorflow/ir/tf_ops.cc.inc')
Execution platform: @local_execution_config_platform//:platform
mlir-tblgen: external/llvm-project/mlir/lib/TableGen/Type.cpp:22: mlir::tblgen::TypeConstraint::TypeConstraint(const llvm::Record*): Assertion `def->isSubClassOf("TypeConstraint") && "must be subclass of TableGen 'TypeConstraint' class"' failed.
PLEASE submit a bug report to  and include the crash backtrace.
Stack dump:
0.	Program arguments: bazel-out/host/bin/external/llvm-project/mlir/mlir-tblgen -gen-op-defs tensorflow/compiler/mlir/tensorflow/ir/tf_ops.td -Ibazel-out/k8-opt/bin -I external/llvm-project/mlir/include -I external/org_tensorflow -I bazel-out/k8-opt/bin/external/llvm-project/mlir/include -I tensorflow/compiler/mlir/tensorflow/ir -o bazel-out/k8-opt/bin/tensorflow/compiler/mlir/tensorflow/ir/tf_ops.cc.inc 
 #0 0x000055b79f119f53 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (bazel-out/host/bin/external/llvm-project/mlir/mlir-tblgen+0xe9f53)
 #1 0x000055b79f117f45 llvm::sys::RunSignalHandlers() (bazel-out/host/bin/external/llvm-project/mlir/mlir-tblgen+0xe7f45)
 #2 0x000055b79f1184e5 SignalHandler(int) (bazel-out/host/bin/external/llvm-project/mlir/mlir-tblgen+0xe84e5)
 #3 0x00007fdfd66ed3c0 __restore_rt (/usr/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
 #4 0x00007fdfd633018b raise (/usr/lib/x86_64-linux-gnu/libc.so.6+0x4618b)
 #5 0x00007fdfd630f859 abort (/usr/lib/x86_64-linux-gnu/libc.so.6+0x25859)
 #6 0x00007fdfd630f729 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x25729)
 #7 0x00007fdfd6320f36 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x36f36)
 #8 0x000055b79f0c26bf mlir::tblgen::TypeConstraint::TypeConstraint(llvm::Record const*) (bazel-out/host/bin/external/llvm-project/mlir/mlir-tblgen+0x926bf)
 #9 0x000055b79f0b2fda mlir::tblgen::Operator::getResultTypeConstraint(int) const (bazel-out/host/bin/external/llvm-project/mlir/mlir-tblgen+0x82fda)
#10 0x000055b79f0b3f9c mlir::tblgen::Operator::populateTypeInferenceInfo(llvm::StringMap<int, llvm::MallocAllocator> const&)::'lambda'(int)::operator()(int) const (.isra.0) (bazel-out/host/bin/external/llvm-project/mlir/mlir-tblgen+0x83f9c)
#11 0x000055b79f0b5693 mlir::tblgen::Operator::populateTypeInferenceInfo(llvm::StringMap<int, llvm::MallocAllocator> const&) (bazel-out/host/bin/external/llvm-project/mlir/mlir-tblgen+0x85693)
#12 0x000055b79f0b6cd9 mlir::tblgen::Operator::populateOpStructure() (bazel-out/host/bin/external/llvm-project/mlir/mlir-tblgen+0x86cd9)
#13 0x000055b79f0b75b1 mlir::tblgen::Operator::Operator(llvm::Record const&) (bazel-out/host/bin/external/llvm-project/mlir/mlir-tblgen+0x875b1)
#14 0x000055b79f05ec60 emitOpList(std::vector<llvm::Record*, std::allocator<llvm::Record*> > const&, llvm::raw_ostream&)::'lambda'(llvm::Record*)::operator()(llvm::Record*) const (.isra.0) (bazel-out/host/bin/external/llvm-project/mlir/mlir-tblgen+0x2ec60)
#15 0x000055b79f06f356 _ZNSt17_Function_handlerIFbRKN4llvm12RecordKeeperERNS0_11raw_ostreamEEUlS3_S5_E2_E9_M_invokeERKSt9_Any_dataS3_S5_ (bazel-out/host/bin/external/llvm-project/mlir/mlir-tblgen+0x3f356)
#16 0x000055b79f0c5042 llvm::TableGenMain(char const*, bool (*)(llvm::raw_ostream&, llvm::RecordKeeper&)) (bazel-out/host/bin/external/llvm-project/mlir/mlir-tblgen+0x95042)
#17 0x000055b79f04c6df main (bazel-out/host/bin/external/llvm-project/mlir/mlir-tblgen+0x1c6df)
#18 0x00007fdfd63110b3 __libc_start_main (/usr/lib/x86_64-linux-gnu/libc.so.6+0x270b3)
#19 0x000055b79f04ef7e _start (bazel-out/host/bin/external/llvm-project/mlir/mlir-tblgen+0x1ef7e)
/bin/bash: line 1: 494760 Aborted                 (core dumped) bazel-out/host/bin/external/llvm-project/mlir/mlir-tblgen -gen-op-defs tensorflow/compiler/mlir/tensorflow/ir/tf_ops.td -Ibazel-out/k8-opt/bin -I external/llvm-project/mlir/include -I external/org_tensorflow -I bazel-out/k8-opt/bin/external/llvm-project/mlir/include -I $(dirname tensorflow/compiler/mlir/tensorflow/ir/tf_ops.td) -o bazel-out/k8-opt/bin/tensorflow/compiler/mlir/tensorflow/ir/tf_ops.cc.inc
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 23.476s, Critical Path: 16.84s
INFO: 414 processes: 414 local.
FAILED: Build did NOT complete successfully

**Comment by jpienaar** [comment]
Thanks for reporting this, at what rev is this?

**Comment by jpienaar** [comment]
The change that caused this failure has been rolled back and the root cause of this failure has been address upstream.

**Comment by summacod** [comment]
Compiled successfully now.
