### ISSUE TITLE
Prediciting the model with features on TPU (AssertionError: Could not compute output Tensor("dense_3/Identity:0", shape=(None, 1), dtype=float32))

### ISSUE THREAD

**Issue by prudhvirajboddu** [tensorflow/tensorflow#40565]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Kaggle using TPU
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.2
- Python version: 3.7.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
After succesful Training , prediction of the model was not happening even if the dataset was right 
And throwing this error
`    AssertionError: Could not compute output Tensor("dense_3/Identity:0", shape=(None, 1), dtype=float32)
`
**Describe the expected behavior**
Model should sucessfully predict the dataset

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
[https://www.kaggle.com/prudhvi9999/image-and-metadata](url)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
Logs are 
[logs.txt](https://github.com/tensorflow/tensorflow/files/4797768/logs.txt)

**Comment by amahendrakar** [comment]
@prudhvirajboddu,
I was able to run the code without any issues, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/1011a622c82d670157c10ff1ea1b96eb/40565.ipynb). Thanks!

**Comment by prudhvirajboddu** [comment]
That was the latest version of changed code Not exactly I want the model to run.
This was the kernel version 2 . I was not able to run . Please take a look at it .
Thank you.
[https://www.kaggle.com/prudhvi9999/image-and-metadata?scriptVersionId=36605669](url)

**Comment by prudhvirajboddu** [comment]
> That was the latest version of changed code Not exactly I want the model to run.
> This was the kernel version 2 . I was not able to run . Please take a look at it .
> Thank you.
> https://www.kaggle.com/prudhvi9999/image-and-metadata?scriptVersionId=36605669

@amahendrakar  any update ?

**Comment by hamzarabi3** [comment]
I'm having the same issue on Kaggle, model fit ran successfully, but I can't generate predictions.
` AssertionError: Could not compute output Tensor("dense_7/Identity:0", shape=(None, 1), dtype=float32)`

**Comment by prudhvirajboddu** [comment]
> I'm having the same issue on Kaggle with TPU, model fit ran successfully, but I can't generate predictions.
> ` AssertionError: Could not compute output Tensor("dense_7/Identity:0", shape=(None, 1), dtype=float32)`
> Temporary fix:
> since mode.predict() can accept the format of training data and ignores the label, you can leverage this using map() on test data:
> ` def prepare_test_data(sample):`
> `----return sample, 0`
> just make sure to do it before batching.

Can you share the code snippet for that ?

**Comment by hamzarabi3** [comment]
This worked for me
`def prepare_test_data(sample):`
`----return sample, 0`

`test_ds = get_test_dataset()`
`test_images_ds = test_ds.map(prepare_test_data).batch(BATCH_SIZE)`
`ouput = model.predict(test_images_ds)
`

**Comment by amahendrakar** [comment]
Was able to reproduce the issue, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/8381d48dfeba929a493d1bd1493b8117/40565.ipynb). Thanks!

**Comment by prudhvirajboddu** [comment]
Got the solution for that issue. We've to get the test dataset without batching from that function and batch them after parsing with image and tabular data with '0' and batch them .Check this link for more . Thanks 
https://colab.research.google.com/drive/1F4enrsOUuxbXUlN4YWwQd9H2_Sy1eMGm?usp=sharing
