### ISSUE TITLE
New Model on Android not working

### ISSUE THREAD

**Issue by tomeroto** [tensorflow/tensorflow#40563]
I have make new model build with:
https://teachablemachine.withgoogle.com/

I download example SDK from:
https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android

I put my model with 2 files on assets directory:
1. model.tflite
2. model_label.txt

I make new class with extend to "Classifier". I replace this two methods:

```
  @Override
  protected String getModelPath() {
    return "model.tflite";
  }

  @Override
  protected String getLabelPath() {
    return "model_label.txt";
  }
```
And then run the project. And I dont see any effect. If I use mobilnet model is working.
I was test this model with tensorflow.js and using webcam, and its working, but why on android not working. I have miss it something? Pleaselet me know.

**Comment by Saduf2019** [comment]
@tomeroto 
Please share the tensorflow version, and simple sample code such that we can replicate the issue faced. or if possible share a colab gist withe the issue faced for us to analyse.

**Comment by tomeroto** [comment]
Hello,

Below is my model that I use on project:
https://drive.google.com/file/d/17mFDcUynbK1ctnRtLSgVfAyE2bkD-gmv/view?usp=sharing

On that archive have two tipe model:

1. Floating Point
-> facemask_unquant.tflite
-> facemask_unquant_labels.txt

2. Quantized
-> facemask.tflite
-> facemask_labels.txt

I use this example code of tensorflow for android:
https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android

And I was follow the instruction, but nothing happen. Please help. Thank you.

**Comment by Saduf2019** [comment]
@tomeroto 
I do not have access to the drive shared, please share a colab gist or the code you ran for which the error was faced.

**Comment by tomeroto** [comment]
Thank you for your response. THis is I make a github link for code:

https://github.com/tomeroto/tensorflow_image_classifications

Please help. Thank you.

**Comment by jvishnuvardhan** [comment]
@tomeroto Can you please share the files. The drive you shared is private, so I cannot download the files. Thanks!

**Comment by tomeroto** [comment]
@jvishnuvardhan this for new link:
https://drive.google.com/file/d/17mFDcUynbK1ctnRtLSgVfAyE2bkD-gmv/view?usp=sharing

**Comment by jvishnuvardhan** [comment]
@tomeroto Can you please try the instructions provided in [this tutorial](https://codelabs.developers.google.com/codelabs/recognize-flowers-with-tensorflow-on-android/#1) and let us know how it progresses. Thanks!
