### ISSUE TITLE
Building Tensorflow for arm based linux systems.

### ISSUE THREAD

**Issue by scocoyash** [tensorflow/tensorflow#40568]
System information
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04):
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.2.0
- Python version: 3.6
- Bazel Version: 2.0.0

**Describe the problem**
I want to build tensorflow shared library from source for arm based 32 bit linux platform but nowhere i find the build command in documentation.
Is it that some different toolchain is required for arm-linux-androideabi ?
What bazel command shall i try to build it ?

**Comment by wangtz** [comment]
Hi Yash,

If you are trying to build TensorFlow (both training and inference) on Arm based system, the cloest thing to checkout is the RasberryPi build. 

https://www.tensorflow.org/install/source_rpi

If you only care about inference, you might want to check out TensorFlow Lite which has pretty intensive Android (mostly Arm chips) support. 

https://www.tensorflow.org/lite/guide/build_arm64

In the past, we had TensorFlow mobile for Android, which is effectively building slimmed TensorFlow on Android for Arm chip. But that project has been deprecated by Tensorflow Lite.

Thx

**Comment by scocoyash** [comment]
Hi @wangtz ,
I was tryng to build inference only tflite for arm 32 bit linux OS which is not based on android.
I have a static library libtensorflowlite.a which works but I  need libtensorflowlite.so shared library which runs on my hardware.
Thanks

**Comment by terryheo** [comment]
There is a way to build shared library using the Bazel.

[ARM32]
```
bazel build --config=elinux_armhf tensorflow/lite:libtensorflowlite.so
```

[ARM64]
```
bazel build --config=elinux_aarch64 tensorflow/lite:libtensorflowlite.so
```

**Comment by scocoyash** [comment]
ohh, great! Thanks @terryheo :)
I will try this and close the issue if it works.

**Comment by scocoyash** [comment]
@terryheo 
The above commands aren't working for me. 
It says --config=elinux_aarch64/elinux_armhf not found in .bazelrc
Do I have to downoad any dependencies for it ?

**Comment by terryheo** [comment]
@scocoyash, the configuration is available since TF2.3. You should use 2.3 or master branch.

**Comment by scocoyash** [comment]
Built it, Thanks @terryheo

**Comment by MUNI9849** [comment]
Hi Sir,
I am not able to build bazel for pynq-z2. I am getting java.lang.OutOfMemoryError: Java heap space even though I use ${JAVAC}" -J-Xms750m -J-Xmx1024m -J-Xms750m.  Could you please help me in this?

![bazel_build_error](https://user-images.githubusercontent.com/70973340/168486426-44076fca-0324-475d-8138-1dfc9c6c2f88.png)

**Comment by vlasov01** [comment]
@MUNI9849 You can add some swap space to get around the memory limit.
