### ISSUE TITLE
ImportError: cannot import name 'policy' from 'tensorflow.python.keras.mixed_precision.experimental'

### ISSUE THREAD

**Issue by Lucysmith8** [tensorflow/tensorflow#40567]
**System information**
- Windows 10
- TensorFlow installed from pip
- TensorFlow version 2.2
- Python version: 3.7
- Installed using virtualenv? pip? conda?:

How to solve this problem ?

![image](https://user-images.githubusercontent.com/66785574/85010400-3907a300-b160-11ea-99ec-3fe0c37e66cc.png)

**Comment by Saduf2019** [comment]
@Lucysmith8 
Please share simple stand alone code for us to replicate the issue faced or share a colab gist with the error for us to analyse
