### ISSUE TITLE
tensor scatter nd add doesn't support complex64 in tf 2.3-dev

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/tensorflow#40577]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.3-dev
- Python version: 3.6.8
- CUDA/cuDNN version: 10.1
- GPU model and memory: Quadro P5000, 16Gb

**Describe the current behavior**

When using `tf.tensor_scatter_nd_add` with complex data, I have the following error:

```
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-4-35a6b23ae93f> in <module>
----> 1 tf.tensor_scatter_nd_add(tf.transpose(to_update), arr_ind, updates)

~/workspace/tfkbnufft/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py in tensor_scatter_add(tensor, indices, updates, name)
  10686       return _result
  10687     except _core._NotOkStatusException as e:
> 10688       _ops.raise_from_not_ok_status(e, name)
  10689     except _core._FallbackException:
  10690       pass

~/workspace/tfkbnufft/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6841   message = e.message + (" name: " + name if name is not None else "")
   6842   # pylint: disable=protected-access
-> 6843   six.raise_from(core._status_to_exception(e.code, message), None)
   6844   # pylint: enable=protected-access
   6845 

~/workspace/tfkbnufft/venv/lib/python3.6/site-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: Unsupported dtype: complex64 [Op:TensorScatterAdd]
```

**Describe the expected behavior**

`tf.tensor_scatter_nd_add` should work with complex data.

**Standalone code to reproduce the issue**

```python
import tensorflow as tf 
to_update = tf.ones([1, 640000], dtype=tf.complex64)
arr_ind = tf.range(324000)[:, None]
updates = tf.cast(tf.random.normal([324000, 1], dtype=tf.float32), tf.complex64)
tf.tensor_scatter_nd_add(tf.transpose(to_update), arr_ind, updates)
```

[Colab link](https://colab.research.google.com/drive/1omAKl8vcqd2TBVbXEnVGvey8Urmcp-kH?usp=sharing).

**Other info / logs** 

This problem only appears for tf-nightly and on GPU.

**Comment by yongtang** [comment]
Added a PR #40585 for complex support

**Comment by zaccharieramzi** [comment]
Hi @yongtang , thanks for taking care of this.

Do you know if by any chance there is a link between this issue (i.e. complex support not being straightfoward) and issue #40672 ?
