### ISSUE TITLE
ValueError: Cannot set tensor: Got tensor of type STRING but expected type FLOAT32

### ISSUE THREAD

**Issue by MevadaRavikumar** [tensorflow/tensorflow#40570]
Hi, 
I am very new to Tensorflow. I am using TensorFlow 1.14.0, Anaconda Spyder 3.7 64 bit and windows 10 64 bit. In my DATASET I am having two folders with classification images (in png and jpeg format). 
I am trying to convert my Keras model.h5 into tflite model. For that, I am using the below-mentioned code. It gives me an error(full traceback can be found at the bottom): 
    ValueError: Cannot set tensor: Got tensor of type STRING but expected type FLOAT32 for input 185, name: mobilenetv2_1.00_224_input 

I have tried to convert images into float 32 using the TensorFlow image converter and NumPy but the same error. 

    import tensorflow as tf
    dataset_dir = "C:\\Users\\Ravi\\dataset"

    IMAGE_SIZE = 224
    BATCH_SIZE = 64

    datagen = tf.keras.preprocessing.image.ImageDataGenerator(
        rescale=1./255, 
        validation_split=0.2)

    train_generator = datagen.flow_from_directory(
    dataset_dir,
    target_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE, 
    subset='training')

    val_generator = datagen.flow_from_directory(
    dataset_dir,
    target_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE, 
    subset='validation')

    image_batch, label_batch = next(val_generator)
    image_batch.shape, label_batch.shape

    print (train_generator.class_indices)

    labels = '\n'.join(sorted(train_generator.class_indices.keys()))

    with open('Mask_labels.txt', 'w') as f:
      f.write(labels)
  
    IMG_SHAPE = (IMAGE_SIZE, IMAGE_SIZE, 3)

    # Create the base model from the pre-trained MobileNet V2
    base_model = tf.keras.applications.MobileNetV2(input_shape=IMG_SHAPE,
                                              include_top=False, 
                                              weights='imagenet')
    base_model.trainable = False
    model = tf.keras.Sequential([
      base_model,
      tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.GlobalAveragePooling2D(),
      tf.keras.layers.Dense(units=2, activation='softmax')
    ])

    model.compile(optimizer=tf.keras.optimizers.Adam(), 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

    print(model.summary())
    print('Number of trainable weights = {}'.format(len(model.trainable_weights)))

    history = model.fit_generator(train_generator, 
                    epochs=2, 
                    validation_data=val_generator)

    # A generator that provides a representative dataset
    def representative_data_gen():
      dataset_list = tf.data.Dataset.list_files(dataset_dir + '/*/*')
      for i in range(100):
        global image
        image = next(iter(dataset_list))
        image = tf.io.read_file(image)
        image = tf.io.decode_jpeg(image, channels=3)
        image = tf.image.resize(image, [IMAGE_SIZE, IMAGE_SIZE])
        #image = np.array(image, dtype="float32")
        image = tf.image.convert_image_dtype(image, tf.float32)
        #image = tf.expand_dims(image, 0)
        yield [image]
    
    saved_keras_model = 'model.h5'
    model.save(saved_keras_model)

    converter =  tf.compat.v1.lite.TFLiteConverter.from_keras_model_file("model.h5")
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    # This ensures that if any ops can't be quantized, the converter throws an error
    #converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    # These set the input and output tensors to uint8
    converter.inference_input_type = tf.uint8
    converter.inference_output_type = tf.uint8
    # And this sets the representative dataset so we can quantize the activations
    converter.representative_dataset = representative_data_gen
    tflite_model = converter.convert()
 
    with open('mobilenet_v2_1.0_224_quant.tflite', 'wb') as f:
      f.write(tflite_model)

Traceback (most recent call last):

      File "C:\Users\Ravi\train_the_model.py", line 120, in <module>
        tflite_model = converter.convert()

      File "C:\Users\Ravi\anaconda3\lib\site-packages\tensorflow\lite\python\lite.py", line 908, in convert
    inference_output_type)

      File "C:\Users\Ravi\anaconda3\lib\site-packages\tensorflow\lite\python\lite.py", line 200, in _calibrate_quantize_model
    inference_output_type, allow_float)

      File "C:\Users\Ravi\anaconda3\lib\site-packages\tensorflow\lite\python\optimize\calibrator.py", line 75, in calibrate_and_quantize
    self._calibrator.FeedTensor(calibration_sample)

      File "C:\Users\Ravi\anaconda3\lib\site-packages\tensorflow\lite\python\optimize\tensorflow_lite_wrap_calibration_wrapper.py", line 112, in FeedTensor
    return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_FeedTensor(self, input_value)

    ValueError: Cannot set tensor: Got tensor of type STRING but expected type FLOAT32 for input 185, name: mobilenetv2_1.00_224_input

**Comment by Saduf2019** [comment]
@MevadaRavikumar 
Please refer to below links for reference and let us know if it helps.
[link](https://stackoverflow.com/questions/52530724/python-tensorflow-lite-error-cannot-set-tensor-got-tensor-of-type-1-but-expecte) [link1](https://github.com/tensorflow/tensorflow/issues/22409)

**Comment by Saduf2019** [comment]
I ran the code shared, please share all dependencies or a colab gist for us to analyse the issue faced.
Please find the [gist here](https://colab.research.google.com/gist/Saduf2019/d0c3679f8e5f543357633ba9b13fed58/untitled236.ipynb)

**Comment by MevadaRavikumar** [comment]
It got solved by running the code on google colab.
