### ISSUE TITLE
Iterator.make_initializer returns None

### ISSUE THREAD

**Issue by pvnieo** [tensorflow/tensorflow#40588]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: 10.2 / 7.6
- GPU model and memory: GeForce RTX 2080 / 12 Gb

**Describe the current behavior**
I'm trying to run a code written in tensorflow 1.1 using tensorflow 2.2. I already run the `tf_upgrade_v2` which changed most of the unsupported things. However, while creating an iterator
```
train_data = tf.data.Dataset.from_generator(gen_function, gen_types, gen_shapes)
train_data = train_data.map(map_func=map_func, num_parallel_calls=self.num_threads)
# Prefetch data
train_data = train_data.prefetch(10)
# create a iterator of the correct shape and type
iterator = tf.compat.v1.data.Iterator.from_structure(tf.compat.v1.data.get_output_types(train_data), tf.compat.v1.data.get_output_shapes(train_data))
```
and when I initialize it:
```
train_init_op = iter.make_initializer(train_data)
```
The initalization operator `train_init_op` is `None`. and I got the following error when i run `sess.run(train_init_op)`
:
```
File "/home/pvnieo/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 958, in run
    run_metadata_ptr)
  File "/home/pvnieo/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1166, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "/home/pvnieo/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 477, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/home/pvnieo/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 263, in for_fetch
    (fetch, type(fetch)))
TypeError: Fetch argument None has invalid type <class 'NoneType'>
```

How can I solve this issue?

**Comment by ravikyram** [comment]
@pvnieo 
Can you please share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by pvnieo** [comment]
Actually, I don't have a small reproducing example, but what I wan't to do is to run the code provided in this github repo: https://github.com/HuguesTHOMAS/KPConv
You can set up a quick example using the following commands:
**NB**: before running `sh compile_op.sh`, you should comment the flag `-D_GLIBCXX_USE_CXX11_ABI=0` if you are running the code on tf v2.
```
git clone https://github.com/HuguesTHOMAS/KPConv.git
wget https://shapenet.cs.stanford.edu/ericyi/shapenetcore_partanno_segmentation_benchmark_v0.zip
tf_upgrade_v2 --intree KPConv/ --outtree KPConv_v2/ --reportfile report2.txt
mkdir KPConv_v2/Data
mkdir KPConv_v2/Data/ShapeNetPart
unzip shapenetcore_partanno_segmentation_benchmark_v0.zip
cp shapenetcore_partanno_segmentation_benchmark_v0 KPConv_v2/Data/ShapeNetPart/shapenetcore_partanno_segmentation_benchmark_v0
cd KpConv_v2/tf_custom_ops
sh compile_op.sh
cd ../cpp_wrappers
sh compile_wrappers.sh
cd ..
python3 training_ShapeNetPart.py
```

**Comment by aaudiber** [comment]
@pvnieo I tried running the suggested commands but encountered build errors in my environment. If you can isolate the issue to something reproducible in colab, it will help a lot with figuring out the root problem.

**Comment by pvnieo** [comment]
Hi, Thank you for your response.

what is the error you getting?

**Comment by aaudiber** [comment]
/usr/bin/ld: cannot find -ltensorflow_framework
collect2: error: ld returned 1 exit status

**Comment by heujnd** [comment]
@pvnieo since you closed the issue, were you able to solve the issue? If so how?
(I am having a similar issue porting the code from KPConv from tf1.12 to tf2.4)

**Comment by pvnieo** [comment]
Hi @heujnd 
Yes, I solved the issue by moving from tensorflow to pytorch!
