### ISSUE TITLE
`tf.nn.swish` documentation refers `name` as an argument

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#40592]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/nn/swish

### Clear description

In the "Args" section, there is an input ` name`, but it is not in the signature, and the function doesn't accept the argument.

Running code:

~~~python
tf.nn.swish(1, name=None)
~~~

got exception:

~~~python
TypeError: swish() got an unexpected keyword argument 'name'
~~~

### Parameters defined

Yes

### Returns defined

Yes

### Raises listed and defined

No

## System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Mojave 10.14
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 2.2.0-rc3
- **Python version**: 3.8.2

**Comment by Patryk999** [comment]
I would like to work on this issue

**Comment by MarkDaoust** [comment]
It looks like all it needs is for someone to add the name argument, and an [ops.name_scope](https://github.com/tensorflow/tensorflow/blob/r2.2/tensorflow/python/framework/ops.py#L6189)

**Comment by Saduf2019** [comment]
Moving the issue to closed status as the change is reflecting.
