### ISSUE TITLE
Building for iOs fails with "ld: 44 duplicate symbols for architecture armv7" error

### ISSUE THREAD

**Issue by timosadchiy** [tensorflow/tensorflow#4059]
Hi all,

Trying to build Tensorflow for [iOs.](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile#ios) The step `tensorflow/contrib/makefile/build_all_ios.sh` after around 20 minutes of building returns errors including `duplicate symbols for architecture armv7`. Please find the details bellow.

### Environment info
Operating System: Mac OS X 10.11.6 (15G31)
Xcode 7.3.1 (7D1014)

### Steps to reproduce
In terminal:
1. `git clone git@github.com:tensorflow/tensorflow.git`
2. `cd tensorflow`
3. `tensorflow/contrib/makefile/download_dependencies.sh`
4. `tensorflow/contrib/makefile/build_all_ios.sh`

### What have you tried?
1. Removing the repository directory and going through the steps again.
2. Going through "Building by hand" steps described [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile#building-by-hand). Error: `ld: 44 duplicate symbols for architecture armv7s` ([Error log](https://github.com/tensorflow/tensorflow/files/439452/tensorflow-error-log2.txt)).

### Error log ([Full log](https://github.com/tensorflow/tensorflow/files/439413/tensorflow-error-log.txt))
`...`
`ld: 44 duplicate symbols for architecture armv7`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
`make: *** [/Users/b0915218/Xcode/tensorflow/tensorflow/contrib/makefile/gen/bin/ios_ARMV7/benchmark]` `Error 1`
`+ '[' 2 -ne 0 ']'`
`+ echo 'armv7 compilation failed.'`
`armv7 compilation failed.`
`+ exit 1`

**Comment by joeling2001** [comment]
Hi,

I'm having the exact same error message.

OS: OS X 10.11.6
Xcode 7.3.1

Many thanks,

Joe

**Comment by timosadchiy** [comment]
Today tried to pull the project again and go through all the steps from the beginning. It worked. Thanks for fixing!
