### ISSUE TITLE
How to do a Bilinear Tensor Product? Or generally multiply 3D tensor by a vector?

### ISSUE THREAD

**Issue by zfrenchee** [tensorflow/tensorflow#406]
Seems like there are only two multiplication operations available, tf.mul which is element-wise and tf.matmul which performs regular 2d matrix multiplication. Am I missing something?

**Comment by georgedahl** [comment]
There is also http://www.tensorflow.org/api_docs/python/math_ops.html#batch_matmul

You can compute a bilinear form just using matmul of course.

**Comment by zfrenchee** [comment]
What I'm trying to do is multiply each 2d slice of a 3d tensor by the same vector. There seems to be no way to perform this operation that I can see. It's the key operation in this paper: [Reasoning With Neural Tensor Networks for Knowledge Base Completion](http://papers.nips.cc/paper/5028-reasoning-with-neural-tensor-networks-for-knowledge-base-completion.pdf)

**Comment by vrv** [comment]
Matrix-vector can be done via a reshape of the vector, though #216 is the feature request to make a 'numpy.dot' equivalent that automatically broadcasts.

I'm not an expert, but if bilinear tensor product is roughly equivalent to tensor contraction, then it should be somewhat straightforward to add tensor contraction as an operation: our CPU matmul is actually using eigen's tensor contraction underneath.

**Comment by zfrenchee** [comment]
I don't quite understand what you mean by reshape. Could you point me towards resources to understand that? It seems like to do matrix-vector, you could do traditional tf.mul and then a reduce along the rows of the matrix in order to get a vector. Is there a better way, with reshape? 

In order to do this product, do I want to define my own op? That's a little bit intimidating.

**Comment by zfrenchee** [comment]
I've [posted to stackoverflow](http://stackoverflow.com/questions/34110502/bilinear-tensor-product-in-tensorflow). That's probably where this question belongs. Nevertheless, I'm curious about why tf.matmul fails here. 

<img width="1130" alt="screen shot 2015-12-05 at 4 29 46 pm" src="https://cloud.githubusercontent.com/assets/2761597/11610324/7948b34a-9b6d-11e5-8fbb-c18e1d07004f.png">

**Comment by zfrenchee** [comment]
I think that the best way to solve this would be to solve #216 and #175. But in the meantime, doing some clever reshaping seems sufficient. Thanks guys!

**Comment by RylanSchaeffer** [comment]
Has anyone added this functionality to TensorFlow since 2015? I have a similar need.

**Comment by mitkof6** [comment]
@zfrenchee I had a similar problem to solve so I came up with a solution that uses tensor product and tensor contraction as mentioned by @vrv. I have replied to your [stackoverflow question](https://stackoverflow.com/questions/34110502/bilinear-tensor-product-in-tensorflow/49095661#49095661).
