### ISSUE TITLE
cudaGetDevice() failed. Status: cudaGetErrorString symbol not found.

### ISSUE THREAD

**Issue by piyushdavda007** [tensorflow/tensorflow#40603]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): tensorflow-gpu 2.0.0 from pip
- TensorFlow version (use command below): tensorflow-gpu 2.0.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: 1650, 4 gb

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

when using tf.test.is_gpu_available()
it shows error like this 
cudaGetDevice() failed. Status: cudaGetErrorString symbol not found.

**Describe the expected behavior**
True

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@piyushdavda007 

TensorFlow supports CUDA 10.0 (TensorFlow >= 1.13.0).See [software requirements](https://www.tensorflow.org/install/gpu#software_requirements).Also see which TF binary suits your case https://www.tensorflow.org/install/pip?lang=python3#older-versions-of-tensorflow.
Please refer similar issue #30726,#34354,#34820,#32381 and see if it helps you.Also, try reinstalling CUDA once and see id the problem still persists.Thanks!
