### ISSUE TITLE
tflite model failed to prepare in inference 

### ISSUE THREAD

**Issue by NicholaiStaalung** [tensorflow/tensorflow#40607]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 9
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.14
- Python version: 3.7
- Bazel version (if compiling from source):  0.28.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10
- GPU model and memory: P100 16VRAM

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
After obtaining a .pb model with export_tflite_ssd_graph.py im using TOCO to create a detect.tflite model. I cant run inference with this model or compile it for the TPU.

Im getting this error when running inference with detect.tflite 

> Traceback (most recent call last):
  File "test_tflite.py", line 33, in <module>
    main()
  File "test_tflite.py", line 21, in main
    interpreter.allocate_tensors() 
  File "/usr/local/lib/python3.5/dist-packages/tflite_runtime/interpreter.py", line 242, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/usr/local/lib/python3.5/dist-packages/tflite_runtime/interpreter_wrapper.py", line 110, in AllocateTensors
    return _interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: tensorflow/lite/kernels/kernel_util.cc:129 std::abs(input_product_scale - bias_scale) <= 1e-6 * std::min(input_product_scale, bias_scale) was not true.Node number 108 (CONV_2D) failed to prepare.

I suspect it involves using SIGMOID as a score converter. When i use SOFTMAX the model works fine.

I understand the difference between the two, but i suspect that the post-processing-op is not capable of handling num_classes > 2 when using sigmoid. 

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@NicholaiStaalung 
Please share a simple stand alone code to replicate the issue faced or share a colab gist to analyse the error.

**Comment by NicholaiStaalung** [comment]
> @NicholaiStaalung
> Please share a simple stand alone code to replicate the issue faced or share a colab gist to analyse the error.

[replicate_issue.tar.gz](https://github.com/tensorflow/tensorflow/files/4804424/replicate_issue.tar.gz)

unpack and enter the folder
`python3 test_tflite.py detect.tflite`

**Comment by NicholaiStaalung** [comment]
Okay, i was able to compile the .tlifte model after a low number of training steps with SIMOID and num_classes = 2. I kept it training over the weekend and now i got the same error as above. Kind of frustrating. So for now im switching feature extractor. I do find it really weird that this error occurs since i have been using the exact same workflow for almost a year. Please help me here!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
