### ISSUE TITLE
keras.models.clone_model ignores input_tensors for functional models

### ISSUE THREAD

**Issue by tobiasmaier** [tensorflow/tensorflow#40617]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.7.7
- CUDA/cuDNN version: 10.1
- GPU model and memory:

**Describe the current behavior**
For functional models `tensorflow.keras.models.clone_model` ignores input_tensors if they are InputLayer objects. It keeps the original input tensors and does not build the model "on top of new inputs tensors".

**Describe the expected behavior**
The cloned model should be built on provided "input tensors or InputLayer objects" as stated in the documentation and as it is for sequential models.
This would allow to change the input shape and dtype or clone a model on top of a model.

**Standalone code to reproduce the issue**
```python
import tensorflow as tf

# Build a sequential and functional model
original_input = tf.keras.Input(shape=(1,), dtype=tf.float32)
sequential_model = tf.keras.Sequential([
    original_input,
    # tf.keras.layers.Lambda(lambda x: x),
])
functional_model = tf.keras.Model(sequential_model.inputs, sequential_model.outputs)

# Predict some data
print("sequential_model:", sequential_model.predict([[1.5]]))
print("functional_model:", functional_model.predict([[1.5]]))

# Clone the model
cloned_sequential_model = tf.keras.models.clone_model(sequential_model)
cloned_functional_model = tf.keras.models.clone_model(functional_model)
assert id(cloned_sequential_model.input) != id(original_input)  # OK
assert id(cloned_functional_model.input) != id(original_input)  # OK

# Clone the model and make the input expect a different shape and dtype
new_input = tf.keras.Input(shape=(None,), dtype=tf.uint8)
cloned_sequential_model = tf.keras.models.clone_model(sequential_model, input_tensors=[new_input])
cloned_functional_model = tf.keras.models.clone_model(functional_model, input_tensors=[new_input])

assert id(cloned_sequential_model.input) == id(new_input) # OK
assert id(cloned_functional_model.input) == id(new_input) # FAILS (expected to pass)
assert id(cloned_functional_model.input) != id(original_input)  # FAILS (expected to pass)

print("cloned_sequential_model.inputs:", cloned_sequential_model.inputs)
print("cloned_functional_model.inputs:", cloned_functional_model.inputs)

assert(cloned_sequential_model.predict([[1.5]]) == cloned_functional_model.predict([[1.5]])) # FAILS (expected to pass)
print("cloned_sequential_model:", cloned_sequential_model.predict([[1.5]]))
print("cloned_functional_model:", cloned_functional_model.predict([[1.5]]))

## Chain example
x = tf.keras.Input(shape=(1,), dtype=tf.float32)
y = tf.keras.layers.Lambda(lambda x: -x)(x)
other_model = tf.keras.Model(x, y)

chained_models = tf.keras.models.clone_model(functional_model, other_model.outputs)
assert chained_models.predict([[1]]) == [[-1]] # FAILS (expected to pass)
print("chained_models:", chained_models.predict([[1]]))

```

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/da1dd12adf48a54fc633fa2856bc3d2a/untitled233.ipynb)

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210603,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/75bfd103e7cff4317dd6a21c44d6d93f/untitled200.ipynb#scrollTo=DJ0ccRYHA4CN)..Thanks !

**Comment by sushreebarsa** [comment]
@tobiasmaier I tried to reproduce the issue on colab using TF v2.7.0 and faced different error .Please find the gist[ here](https://colab.research.google.com/gist/sushreebarsa/75bfd103e7cff4317dd6a21c44d6d93f/untitled200.ipynb#scrollTo=Sd_v1TUCA_0m) for reference.Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
