### ISSUE TITLE
 C++ interface session->Close() does not reclaim memory resources

### ISSUE THREAD

**Issue by zhiyu-deep** [tensorflow/tensorflow#40615]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Utuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.5
- Python version:
- Bazel version (if compiling from source):0.24.1
- GCC/Compiler version (if compiling from source):5.5.0
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

When I have executed session->closing(), the memory is not completely released.
I found that after the destruction of the session object, only a part of the memory was released, not completely released.

In my scenario, the complete memory is 4.28G, after executing session->Close() and destructuring the object, the memory is 3G.

**Describe the expected behavior**

Theoretically，after executed session->Close()， will Close the session to release the resources associated with.

**Standalone code to reproduce the issue**

int main() {
  {
    tensorflow::SessionOptions sess_options_;
    sess_options_.config.set_use_per_session_threads(true);
    sess_options_.config.set_intra_op_parallelism_threads(1);
    sess_options_.config.set_inter_op_parallelism_threads(1);

    std::unique_ptr<tensorflow::Session> sess_;
    sess_.reset(tensorflow::NewSession(sess_options_));

    tensorflow::GraphDef graph_def;
    auto default_env = tensorflow::Env::Default();
    tensorflow::Status s = tensorflow::ReadBinaryProto(default_env, 
      pd_path, &graph_def);

    sess_->Create(graph_def);

    std::vector<tensorflow::Tensor> output;
    std::vector<std::pair<std::string, tensorflow::Tensor>> tf_input;

    tf_input.emplace_back(...);
    auto status = sess_->Run(tf_input,
                             std::vector<std::string>{"output_node"}, {},
                             &output);
    sess_->Close();
  }
}

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
