### ISSUE TITLE
I want to implement the beam search

### ISSUE THREAD

**Issue by ousshml** [tensorflow/tensorflow#40627]
i am using this code : https://www.tensorflow.org/tutorials/text/nmt_with_attention

I want to implement the beam search to this code in order to generate more than one sentence, but i don't know how can i do it. Can you please help me ?

**Comment by amahendrakar** [comment]
@ousshml,
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!
