### ISSUE TITLE
python sequence example context_features  Unsupported FixedLenSequenceFeature

### ISSUE THREAD

**Issue by darrenwang00** [tensorflow/tensorflow#40629]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):   tf 2.2
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**

   */miniconda3/lib/python3.7/site-packages/tensorflow/python/ops/parsing_ops.py:548 parse_sequence_example  **
        context_features, [VarLenFeature, FixedLenFeature, RaggedFeature])
    /data1/arc_seven/miniconda3/lib/python3.7/site-packages/tensorflow/python/ops/parsing_config.py:461 from_features
        (type(feature).__name__, feature))

    ValueError: Unsupported FixedLenSequenceFeature FixedLenSequenceFeature(shape=(), dtype=tf.float32, allow_missing=-1, default_value=None).

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by darrenwang00** [comment]
when the tf.data sequence example context_features support FixedLenSequenceFeature

**Comment by gowthamkpr** [comment]
@darrenwang00 Can you please share the code for us to reproduce this issue. Thanks!

**Comment by gowthamkpr** [comment]
CLosing this issue as it has been awaiting response for more than 2 weeks. Please add additional comments for us to open this issue again. Thanks!
