### ISSUE TITLE
Tensorboard icons invisible when building from source

### ISSUE THREAD

**Issue by poindextrose** [tensorflow/tensorflow#4062]
The refresh, configure, and plot buttons (expand, log/linear) are not visible when building tensorboard from source. However, they are clickable.
<img width="1438" alt="screen shot 2016-08-26 at 8 10 32 am" src="https://cloud.githubusercontent.com/assets/1794423/18010495/9a428d32-6b65-11e6-8f7f-23a490ae05fb.png">

### Environment info
Build/execute operating System: Ubuntu 16.04
Viewing operating System: OS X 10.11.6
Viewing browsers: Chrome 52 & Safari 9.1.2
Installed from source from a recent master commit 99ce233191920fb0dde2d823cf493e28b89618c7
Bazel 0.3.0

### Steps to reproduce
1. git clone https://github.com/tensorflow/tensorflow.git
2. cd tensorflow
3. ./configure
4. bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
5. pushd tensorflow/tensorboard
6. npm run prepare
7. npm run compile
8. gulp regenerate
9. popd
10. bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
11. bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
12. pip install /tmp/tensorflow_pkg/tensorflow-0.10.0rc0-py3-none-any.whl
13. tensorboard

### What have you tried?
1. Building from r0.10 branch but it doesn't work either.

**Comment by danmane** [comment]
Known issue. Will be fixed today at r0.10 and master.

**Comment by poindextrose** [comment]
It is fixed in master now. Thanks.

**Comment by danmane** [comment]
Fix will be merged into r0.10 by https://github.com/tensorflow/tensorflow/pull/4137.
