### ISSUE TITLE
Loss function not accessible when overriding optimizer_v2.OptimizerV2

### ISSUE THREAD

**Issue by ruperty** [tensorflow/tensorflow#40635]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
n/a
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
TensorFlow version: 2.1.0
- Python version:
Python 3.6.10 |Anaconda, Inc.| (default, Mar 23 2020, 17:58:33) [MSC v.1916 64 bit (AMD64)]
- Bazel version (if compiling from source):
n/a
- GCC/Compiler version (if compiling from source):
n/a
- CUDA/cuDNN version:
- GPU model and memory:
n/a

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)

== check for virtualenv =========================================
False

== tensorflow import ============================================
Traceback (most recent call last):

  File "<string>", line 1, in <module>

ModuleNotFoundError: No module named 'tensorflow'

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
tf_env_collect.sh: line 145: nvidia-smi: command not found

== cuda libs  ===================================================

== tensorflow installed from info ==================

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(3, 8, 2, 'final', 0)

== bazel version  ===============================================

You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
v2.1.0-rc2-17-ge5bf8de410 2.1.0

**Describe the current behavior**

There is no access to the loss function within the methods that are allowed to be overridden in the optimizer_v2.OptimizerV2 class, i.e _resource_apply_dense(). The result is that weights do not change within during training. I have tried overriding _compute_gradients(),but it is never called. 

As can be seen from the output at the last line, the weights do not change.

**Describe the expected behavior**

I want to be able to change the weights based upon the loss. In this case to change them randomly if the loss has not decreased. However, to do this one of the methods I am allowed to override should be passed the loss function.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

https://colab.research.google.com/github/ruperty/colab/blob/master/optimizer_test.ipynb

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
I am able to replicate the issue, please find the [gist here.](https://colab.research.google.com/gist/Saduf2019/c0cb51b51cc736dbb1f1aab3cc49e31b/untitled240.ipynb)

**Comment by Saduf2019** [comment]
@ruperty 

Is this till an issue, could you please try is later tf versions [2.4 or nightly] and let us know.
