### ISSUE TITLE
C++ compilation of rule '//tensorflow/core/kernels:softsign_op' 

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#40639]
Under Windows-10 I have tried to build [TensorFlow 2.2 from the source](https://www.tensorflow.org/install/source_windows) and it ends with the following error

```
ERROR: C:/tensorflow/tensorflow/core/kernels/BUILD:4748:1: C++ compilation of rule '//tensorflow/core/kernels:softsign_op' failed (Exit 2)
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_search.h(14): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 9402.886s, Critical Path: 4760.75s
INFO: 6735 processes: 6735 local.
FAILED: Build did NOT complete successfully
```

**Comment by Saduf2019** [comment]
@peter197321 
Can you please refer to these links and let us know if it helps:
[link](https://wiki.qt.io/Cannot_open_include_file_stddef_h_No_such_file_or_directory) [link1](https://social.msdn.microsoft.com/Forums/vstudio/en-US/0f580a73-6f11-4aa6-abbe-6bf1438734c2/standard-files-quotstddefhquot-quotstringhquot-missing-in-visual-studio-2015-rc?forum=vclanguage) [link2](https://github.com/weidai11/cryptopp/issues/781#issuecomment-454076517)
