### ISSUE TITLE
Looping over tf.data.Dataset very slow compared to that of Numpy Array

### ISSUE THREAD

**Issue by rakeshmothukuru1** [tensorflow/tensorflow#40634]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): N/A. Can be replicated in Google Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): N/A
- TensorFlow version (use command below): 2.2 and tf-nightly
- Python version: 3.6.7 (Google Colab)
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**: `For-Loop` over samples of a `tf.data.Dataset` is much slower (almost 500 times) than looping over the corresponding `numpy array`.

**Describe the expected behavior**: Looping over `tf.data.Dataset` shouldn't take so long.

**Standalone code to reproduce the issue**: This is the [Colab link](https://colab.research.google.com/gist/rakeshmothukuru1/c411d6de49f6cfb3d610d05c54a6d172/so_62453823.ipynb) to reproduce the issue.

```
import numpy as np
import tensorflow as tf
import time

print(tf.__version__)

a = np.ones(100000, dtype=np.float32)

start_time = time.time()
for x in a:
    pass
print(time.time() - start_time)

start_time = time.time()
for x in tf.data.Dataset.from_tensor_slices(a):
    pass
print(time.time() - start_time)
```

**Comment by nikitamaia** [comment]
Hi @rakeshmothukuru1, try wrapping your code in a @tf.function and the time should be almost the same for both loops. @tf.function will use autograph to transform your Python Eager code into graph-compatible TensorFlow ops.

**Comment by ravikyram** [comment]
@rakeshmothukuru1 

As @nikitamaia suggested try wrapping your code in @tf.function and you will see better performance or almost same performance with tf.data.Dataset than Numpy array.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/00d036886c185865d5054ce43bee6370/untitled51.ipynb).Please, verify once and close this issue if you feel your query has been answered.Thanks!

**Comment by jorgeecardona** [comment]
if that print inside of the function is only executed during tracing, is it really measuring the time spend in the loop? or is it just measuring the time it takes to construct a part of the graph?

**Comment by jorgeecardona** [comment]
This code addresses different ways (not too different though) to check the performance, they all return similar times
https://colab.research.google.com/drive/1NGQ-_f75s-8KG8elNZrGYqjtnyUsOfV4#scrollTo=1MZTQH_IumI7
