### ISSUE TITLE
SparseTensor from dense conversion error when dtype tf.string

### ISSUE THREAD

**Issue by aldragan0** [tensorflow/tensorflow#40633]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): conda/binary
- TensorFlow version (use command below): unknown 2.1.0
- Python version: 3.7.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.2/7.6.5
- GPU model and memory: GTX 1070 8GB

**Describe the current behavior**
Fails to convert the Tensor to a SparseTensor representation

**Describe the expected behavior**
b should contain the SparseTensor representation of a

**Standalone code to reproduce the issue**

a = tf.constant(list("ababa"))
print(a)
b = tf.sparse.from_dense(a)
print(b)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Traceback (most recent call last):
  File "test.py", line 264, in <module>
    b = tf.sparse.from_dense(a)
  File "/home/alex/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/ops/sparse_ops.py", line 121, in from_dense
    math_ops.not_equal(tensor, array_ops.constant(0, tensor.dtype)))
  File "/home/alex/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 258, in constant
    allow_broadcast=True)
  File "/home/alex/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 266, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/alex/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 96, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
TypeError: Cannot convert 0 to EagerTensor of dtype string

**Comment by yongtang** [comment]
Added a PR #40633 for the fix.
