### ISSUE TITLE
AttributeError: 'StringIntLabelMapItem' object has no attribute 'keypoints'

### ISSUE THREAD

**Issue by chuasonglin** [tensorflow/tensorflow#40649]
I'm following the tutorial (https://www.youtube.com/watch?v=HjiBbChYRDw) and got into a problem of getting the category index from the labelmap.

PATH_TO_LABELS = 'training/labelmap.pbtxt'
![keypoints](https://user-images.githubusercontent.com/60057917/85229903-28d11b80-b41f-11ea-8579-82c6da4bbf7a.JPG)

**Comment by amahendrakar** [comment]
@chuasonglin,
In order to reproduce the issue reported here, could you please provide the complete code, the TensorFlow version and the dataset you are using. Thanks!

**Comment by chuasonglin** [comment]
I just managed to resolve it. Thank you

Basically, change two things:
from utils import label_map_util 
----> from object_detection.utils import label_map_util 
from utils import visualization_utils as vis_util 
----> from object_detection.utils import visualization_utils as vis_util

**Comment by amahendrakar** [comment]
> I just managed to resolve it. Thank you

Thank you for the update @chuasonglin. Marking this issue as closed, as it is resolved. Thanks!
