### ISSUE TITLE
i can not run examples with downloadPredictFloat16ModelFile

### ISSUE THREAD

**Issue by cowcomic** [tensorflow/tensorflow#40645]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://github.com/tensorflow/examples/tree/master/lite/examples/style_transfer/android

## Description of issue (what needs changing):
i follow the description

then run this project

log
```
> Task :app:downloadPredictFloat16ModelFile
Unable to get progress logger. Download progress will not be displayed.

> Task :app:downloadPredictFloat16ModelFile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:downloadPredictFloat16ModelFile'.
> org.apache.http.conn.HttpHostConnectException: Connect to tfhub.dev:443 [tfhub.dev/172.217.27.142] failed: Connection timed out: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 24s
7 actionable tasks: 1 executed, 6 up-to-date

```

**Comment by Saduf2019** [comment]
@cowcomic 
Please share the tensorflow version and simple stand alone code for us to replicate the issue faced.

**Comment by cowcomic** [comment]
it solved.
i use a proxy for gradle
then everything is ok

**Comment by Allen7276** [comment]
so how to use proxy for gradle please? For the result of China Government, we normal Chinese cant use Google at random!

**Comment by Allen7276** [comment]
I try to deal with this question more than 4h, but I couldn't find a suitable way to solve it!

**Comment by SpringManer** [comment]
> so how to use proxy for gradle please? For the result of China Government, we normal Chinese cant use Google at random!

hi brother,could you solve this problem
