### ISSUE TITLE
Tensorflow creating too many threads

### ISSUE THREAD

**Issue by dgaleareading** [tensorflow/tensorflow#40656]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): via pip
- TensorFlow version (use command below): v1.12.1-26458-gc251e83 2.2.0-rc0
- Python version: 3.7.3
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.2
- GPU model and memory: 2x V100 (32GB) or 4x V100 (32GB)

**Describe the current behavior**

I am trying to run a simple model through some custom cross-validation code using Distributed Training and python multiproccessing to speed up execution. I get nearly through the first fold of CV when the command "watch -n1 nvidia-smi" (used to monitor GPU usage) starts giving an error of "fork failed: Resource temporary unavailable", i.e. the maximum number of threads has been reached. This is when the code hangs. I use this via LSF, so after some time where I notice that no progress has been made, I kill off the job myself, at which time, I get an error saying "Runtime error: can't start new thread"

**Describe the expected behavior**

All folds of the CV code are finshed and some metrics are calculated.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

I have ~100K image files, and their name gives their respective label. I first load them all to get them into cache:

```
def load_file(path):

    arr = np.load(path)['arr_0'][0:None:resolution, 0:None:resolution, :fields]
    for field in range(arr.shape[-1]):

        scaler = StandardScaler()
        scaler.fit(arr[:, :, field])
        arr[:, :, field] = scaler.transform(arr[:, :, field])
    
    name = path.replace(".npz", "").split("/")[-1]

    if "no" in name:
        cat, start_lat, end_lat, start_lon, end_lon, date = name.split("_")
        label = 0
    else:
        cat, press, wind, start_lat, end_lat, start_lon, end_lon, date = name.split("_")
        cat = int(cat)
        if cat < 1:
            label = 0
        else:
            label = 1
            
    return arr, label

pool = mp.Pool(int(mp.cpu_count()))
res = list(tqdm.tqdm(pool.imap(load_file, cat1_files), total=len(cat1_files)))
res = list(tqdm.tqdm(pool.imap(load_file, cat2_files), total=len(cat2_files)))
res = list(tqdm.tqdm(pool.imap(load_file, cat3_files), total=len(cat3_files)))
res = list(tqdm.tqdm(pool.imap(load_file, cat4_files), total=len(cat4_files)))
res = list(tqdm.tqdm(pool.imap(load_file, cat5_files), total=len(cat5_files)))
res = list(tqdm.tqdm(pool.imap(load_file, no_files), total=len(no_files)))
```

I then create a Generator to load the data in the model. The previously opened pool is used here as well to speed up loading of files:

```
class DataGenerator(tf.keras.utils.Sequence):
    
    def __init__(self, paths, batch_size=32, dim=(86, 128, 5), shuffle=True, data_aug=True):
        self.dim = dim
        self.batch_size = batch_size
        self.paths = paths
        self.shuffle = shuffle
        self.on_epoch_end()

    def __len__(self):
        'Denotes the number of batches per epoch'
        return int(np.floor(len(self.paths) / self.batch_size))

    def __getitem__(self, index):
        'Generate one batch of data'
        # Generate indexes of the batch
        indexes = self.indexes[index*self.batch_size:(index+1)*self.batch_size]

        # Find list of IDs
        paths_temp = [self.paths[k] for k in indexes]

        # Generate data
        X, y = self.__data_generation(paths_temp)

        return X, y

    def on_epoch_end(self):
        self.indexes = np.arange(len(self.paths))
        if self.shuffle == True:
            np.random.shuffle(self.indexes)
            
    def __data_generation(self, paths_temp):
        
        X = np.zeros((self.batch_size, self.dim[0], self.dim[1], self.dim[2]), dtype="float32")
        y = np.zeros(self.batch_size)
        pool_res = list(pool.imap(load_file, paths_temp))
        
        for i in range(len(pool_res)):
            X[i], y[i] = pool_res[i]
            
        return X, y
```

The penultimate step is to create a function that instantiates a new model. This is a fairly simple CNN classifier:

```
def create_model(shape):
    
    mirrored_strategy = tf.distribute.MirroredStrategy()
    with mirrored_strategy.scope():

        model = models.Sequential() 

        model.add(layers.Conv2D(8, (2, 2), padding="same", strides=(1, 1), input_shape=(shape))) 
        model.add(layers.ReLU())
        model.add(layers.MaxPooling2D((2, 2), strides=1)) 
        model.add(layers.Conv2D(16, (1, 1), strides=(1, 1))) 
        model.add(layers.ReLU())
        model.add(layers.MaxPooling2D((2, 2), strides=1))
        model.add(layers.Conv2D(32, (2, 2), strides=(1, 1))) 
        model.add(layers.ReLU())
        model.add(layers.MaxPooling2D((2, 2), strides=1))
        model.add(layers.Conv2D(64, (2, 2), strides=(1, 1))) 
        model.add(layers.ReLU())
        model.add(layers.MaxPooling2D((2, 2), strides=1))
        model.add(layers.Conv2D(128, (2, 2), strides=(1, 1))) 
        model.add(layers.ReLU())
        model.add(layers.MaxPooling2D((2, 2), strides=1))
        model.add(layers.Conv2D(256, (2, 2), strides=(1, 1))) 
        model.add(layers.ReLU())
        model.add(layers.MaxPooling2D((2, 2), strides=1))

        model.add(layers.Flatten()) 
        model.add(layers.Dense(128))
        model.add(layers.ReLU())
        model.add(layers.Dense(64))
        model.add(layers.ReLU())
        model.add(layers.Dense(32))
        model.add(layers.ReLU())
        model.add(layers.Dense(1, activation='sigmoid')) 

        METRICS = [
              tf.keras.metrics.TruePositives(name='tp'),
              tf.keras.metrics.FalsePositives(name='fp'),
              tf.keras.metrics.TrueNegatives(name='tn'),
              tf.keras.metrics.FalseNegatives(name='fn'), 
              tf.keras.metrics.BinaryAccuracy(name='accuracy'),
              tf.keras.metrics.Precision(name='precision'),
              tf.keras.metrics.Recall(name='recall'),
              tf.keras.metrics.AUC(name='auc'),
        ]

    model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=METRICS) 
    
    return model
```

Finally, the Cross-Validation code, which trains a model on each fold and saves the model:

```
train_fold_paths = []
val_fold_paths = []

for fold in range(k):
    
    cat1_fold = cat1_train_files[int(fold/k*len(cat1_train_files)) : int((fold+1)/k*len(cat1_train_files))]
    cat2_fold = cat2_train_files[int(fold/k*len(cat2_train_files)) : int((fold+1)/k*len(cat2_train_files))]
    cat3_fold = cat3_train_files[int(fold/k*len(cat3_train_files)) : int((fold+1)/k*len(cat3_train_files))]
    cat4_fold = cat4_train_files[int(fold/k*len(cat4_train_files)) : int((fold+1)/k*len(cat4_train_files))]
    cat5_fold = cat5_train_files[int(fold/k*len(cat5_train_files)) : int((fold+1)/k*len(cat5_train_files))]  
    yes_fold = cat1_fold + cat2_fold + cat3_fold + cat4_fold + cat5_fold
    no_fold = no_train_files[int(fold/k*len(no_train_files)) : int((fold+1)/k*len(no_train_files))]
    
    fold_data = yes_fold + no_fold
    
    val_fold_paths.append(fold_data)
    
    fold_data = no_fold + yes_fold
    train_fold_paths.append(fold_data)

history_folds = []
model_folds = []

for i_fold in range(k):
    
    train_folds = list(np.arange(i_fold, k-1+i_fold)%k)

    train_paths = []
    for fold_index in train_folds:
        if train_paths != None:
            train_paths += train_fold_paths[fold_index]
        else:
            train_paths = train_fold_paths[fold_index]
            
    val_paths = val_fold_paths[(k+i_fold-1)%k]
    
    dummy_file, _ = load_file(cat1_files[0])
    
    params_train = {'dim': dummy_file.shape, 'batch_size': batch_size, 'shuffle': True, 'data_aug': False}
    params_val = {'dim': dummy_file.shape, 'batch_size': batch_size, 'shuffle': False, 'data_aug': False}

    training_generator = DataGenerator(train_paths, **params_train)
    validation_generator = DataGenerator(val_paths, **params_val)
    
    model = create_model(dummy_file.shape)

    print("Training Fold " + str(i_fold+1))
    print("Training Fold " + str(i_fold+1), file=console_out)
        
    history = model.fit_generator(generator=training_generator, validation_data=validation_generator, use_multiprocessing=True, workers=int(0.5*mp.cpu_count()), 
                                  verbose=1, epochs=epochs, max_queue_size = int(len(train_paths)/batch_size))
    
    history_folds.append(history)
        
    model.save(fold_model_name + str(i_fold+1))
    tf.keras.backend.clear_session()
    
    tf.keras.experimental.terminate_keras_multiprocessing_pools(grace_period=0.1, use_sigkill=True)

```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Output of "ulimit -a":

```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 3090396
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 48000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 2097151
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

```

Part of Stacktrace:

```
Exception in thread Thread-31178:
Traceback (most recent call last):
  File "/apps/contrib/jaspy/miniconda_envs/jaspy3.7/m3-4.6.14/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/apps/contrib/jaspy/miniconda_envs/jaspy3.7/m3-4.6.14/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/users/dgalea/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/data_utils.py", line 843, in _run
    with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor:
  File "/home/users/dgalea/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/data_utils.py", line 732, in <lambda>
    self.executor_fn = lambda _: get_pool_class(False)(workers)
  File "/apps/contrib/jaspy/miniconda_envs/jaspy3.7/m3-4.6.14/lib/python3.7/multiprocessing/dummy/__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "/apps/contrib/jaspy/miniconda_envs/jaspy3.7/m3-4.6.14/lib/python3.7/multiprocessing/pool.py", line 802, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/apps/contrib/jaspy/miniconda_envs/jaspy3.7/m3-4.6.14/lib/python3.7/multiprocessing/pool.py", line 176, in __init__
    self._repopulate_pool()
  File "/apps/contrib/jaspy/miniconda_envs/jaspy3.7/m3-4.6.14/lib/python3.7/multiprocessing/pool.py", line 241, in _repopulate_pool
    w.start()
  File "/apps/contrib/jaspy/miniconda_envs/jaspy3.7/m3-4.6.14/lib/python3.7/multiprocessing/dummy/__init__.py", line 51, in start
    threading.Thread.start(self)
  File "/apps/contrib/jaspy/miniconda_envs/jaspy3.7/m3-4.6.14/lib/python3.7/threading.py", line 847, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

```

**Comment by Saduf2019** [comment]
@dgaleareading 
Please share complete executable code such that we can replicate the issue faced, i ran the code shared and face different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/db23ed9f34b0f9851738ffa6d2ac9d62/untitled237.ipynb) or if possible please share a colab gist with the reported issue for us to analyse.

**Comment by dgaleareading** [comment]
@Saduf2019 I have put the whole notebook on my Google Drive at https://drive.google.com/file/d/1O9phSN7moTo-5KQNqPPQ4Qfl9OJLqZvd/view?usp=sharing

**Comment by Saduf2019** [comment]
@dgaleareading 
I ran the code shared, please let us know if [this gist](https://colab.research.google.com/gist/Saduf2019/90c0bd531b8915ba97889d0de2271000/untitled239.ipynb) confirm your issue.

**Comment by dgaleareading** [comment]
Unfortunately it does not as you don't have any of the correct input files.

**Comment by nikitamaia** [comment]
Hi @dgaleareading, given your error message "fork failed: Resource temporary unavailable" it sounds like you are creating too many processes and exceeding your max of 4096. [Pool](https://docs.python.org/3.4/library/multiprocessing.html?highlight=process) uses process based parallelism, which will also create more processes, and then you're also calling model.fit_generator with use_multiprocess=True.

A couple of questions to help with investigation:
1) do you have this same problem when running without distributed training?
2) can you try fit.generator with use_multiprocessing=False

Also, can you try running [pstree](https://man7.org/linux/man-pages/man1/pstree.1.html) to see which process is creating a lot of child processes?

**Comment by dgaleareading** [comment]
Hi @nikitamaia, thanks for your reply. Here are my answers:

>1. do you have this same problem when running without distributed training?

Yes, I still have the same problem without distributed training

>2. can you try fit_generator with use_multiprocessing=False

I still get the same problem with use_multiprocessing=False

>Also, can you try running pstree to see which process is creating a lot of child processes?

My system is down for a few days (due to a power cut at the HPC site), but I will put the readout of the pstree command whenever it is bck online.

**Comment by dgaleareading** [comment]
@nikitamaia I have managed to run pstree while my code was running. These results were obtained during the first epoch of my first fold.

[full_tree.txt](https://github.com/tensorflow/tensorflow/files/4827892/full_tree.txt) has the full expanded tree returned by `pstree -ac` while [collapsed_full_tree.txt](https://github.com/tensorflow/tensorflow/files/4827890/collapsed_full_tree.txt) has the slightly more compressed tree returned by `pstree -a`

I have also run the command only for my user and the output is given in [user_tree.txt](https://github.com/tensorflow/tensorflow/files/4827893/user_tree.txt) with the collapsed version in [collapsed_user_tree.txt](https://github.com/tensorflow/tensorflow/files/4827891/collapsed_user_tree.txt)

In the above results, there is the line `180*[{python3}]` which seems to be unnecessarily large. Do you have any idea on how I can fix my issue?

**Comment by dgaleareading** [comment]
UPDATE:  My code works with TF 1.14, Keras 2.3 and Python 3.6.8. I think it would be useful to see why it doesn't work in pure TF2.

**Comment by nikitamaia** [comment]
Hm that is very mysterious indeed. Have you tried loading all data and generating the folds (without training) to see if the process of loading the data is causing the large number of processes?

**Comment by dgaleareading** [comment]
Yes I have but it did not soolve the problem.

**Comment by nikitamaia** [comment]
Can you clarify what you mean? Did you still get the same "fork failed" error when trying to load the data and create the folds without training?

**Comment by dgaleareading** [comment]
Yes, I still get  "fork failed" when trying to load the data and creating the folds without training?

**Comment by nikitamaia** [comment]
Yes I think so. Sounds like the use of pool in the multiprocessing library is causing excessive creation of processes.
