### ISSUE TITLE
the memory couldn't be released after training

### ISSUE THREAD

**Issue by ucasiggcas** [tensorflow/tensorflow#40655]
hi,dear
help wanted,
when I see the memory after a training in While
confused me that the memory can't be released in time sleep
the codes down for reference
```
import tensorflow as tf
import numpy as np
import time
def train_func():
    model = tf.keras.Sequential() #
    model.add(tf.keras.layers.Dense(512,activation='relu',input_shape=(784,)))
    model.add(tf.keras.layers.Dense(256,activation='relu'))
    model.add(tf.keras.layers.Dense(10,activation='softmax'))
    model.summary()


    X_train=np.random.randn(10000,784)
    y_train=np.random.randint(0,10,size=10000)

    y_train=tf.keras.utils.to_categorical(y_train,10)
    model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
    model.fit(X_train,y_train,batch_size=64,epochs=1)
    
while True:
    train_func()
    print("training over !!!")
    time.sleep(1000)
```

the memory 
```
10000/10000 [==============================] - 1s 59us/sample - loss: 2.3762 - acc: 0.1027
training over !!!
```
![image](https://user-images.githubusercontent.com/35590066/85261428-b99b0c00-b49e-11ea-8d13-10974796160b.png)

SO how to release the memory ?

thx

**Comment by ucasiggcas** [comment]
of course could ignore the **while**
as follows
```
train_func()
print("training over !!!")
time.sleep(1000)
```
could also see the same situation

**Comment by ravikyram** [comment]
@ucasiggcas 

Can you please fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.I have tried in colab with TF version-gpu  2.2 and i noticed its hanging.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/6cec38b478643cd5db62981198cc0a70/untitled57.ipynb).Thanks!

**Comment by ucasiggcas** [comment]
hi,dear
any version could try,
ONLY need GPU,
I just want to know the memory after training
could you see the pic by 
`nvidia-smi`

**Comment by gowthamkpr** [comment]
@ucasiggcas Please take a look at similar [issue](https://github.com/tensorflow/tensorflow/issues/36465) and let me know if it helps. Thanks!

**Comment by ucasiggcas** [comment]
hi,thx
have tried the codes,SUCCESS

```
process_eval = multiprocessing.Process(target=evaluate, args=(...))
process_eval.start()
process_eval.join()
```
will close
