### ISSUE TITLE
build failed with build_all_android.sh as "make: *** No rule to make target '/tensorflow/contrib/makefile/downloads/eigen/unsupported/Eigen/CXX1', needed by '/home/jason/workspace/algo/tf/tensorflow/tensorflow/contrib/makefile/gen/obj/android_armeabi-v7a/tensorflow/core/kernels/cast_op_impl_bool.o'.  Stop. make: *** Waiting for unfinished jobs....

### ISSUE THREAD

**Issue by jianhua-hsu** [tensorflow/tensorflow#40661]
Hi Guys,
I need to generate tensorflow static library for 32bit or 64 bit Arm for qsee platform. This is my first time to use tensorflow. I am trying to use "./tensorflow/contrib/makefile/build_all_android.sh " to generate such static library. Unfortunetly, it build failed.

Below are the information I am using, and problem are also described. Do you have any idea about it. Appreciated very much ^ ^.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.1 LTS
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.5
- Python version: Python 2.7.17
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source): android-ndk-r12b

**Describe the problem**
Can not build successful with script build_all_android.sh

**Provide the exact sequence of commands / steps that you executed before running into the problem**
build command used: ./tensorflow/contrib/makefile/build_all_android.sh 

**Any other info / logs**
**make: *** No rule to make target '/home/jason/workspace/algo/tf/tensorflow/tensorflow/contrib/makefile/downloads/eigen/unsupported/Eigen/CXX1', needed by '/home/jason/workspace/algo/tf/tensorflow/tensorflow/contrib/makefile/gen/obj/android_armeabi-v7a/tensorflow/core/kernels/cast_op_impl_bool.o'.  Stop.
make: *** Waiting for unfinished jobs....**

**Comment by jianhua-hsu** [comment]
Hi guys,

Is there any other way that can generate static libraryy tensoflowlite.a. ^ ^. or someone can share the experience of it. I've been trying many ways such as bazel build, still meet many errors. 

should the tensorflow version be consistent with bazel version or android NDK version or GCC version? ^^

**Comment by terryheo** [comment]
Please, check these.

https://www.tensorflow.org/lite/guide/build_rpi
https://www.tensorflow.org/lite/guide/build_arm64
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/make
