### ISSUE TITLE
Coral edge TPU Classification coordinates 

### ISSUE THREAD

**Issue by MevadaRavikumar** [tensorflow/tensorflow#40663]
Hi,
I am running my object classification using Raspberry pi 4, model B, coral edge TPU. I am using this command to classify the image. 

    ‘model.classify_with_image(frame, threshold=args[“confidence”])’

It works perfectly but It does not give me coordinates like 

    ‘model.detect_with_image()’ 

Is there any way I can get the coordinates?

From the official documentation: 

    detection: 
    detect_with_image(img, threshold=0.1, top_k=3, keep_aspect_ratio=False, relative_coord=True, resample=0)
    classification: 
    classify_with_image(img, threshold=0.1, top_k=3, resample=0)

**Comment by ymodak** [comment]
The image classification model will predict the probability of an image representing a particular class.
Thus you can expect output as an array of probabilities between 0 and 1.
