### ISSUE TITLE
having impport error ..tensorflow and tflearn

### ISSUE THREAD

**Issue by BV-SS** [tensorflow/tensorflow#40667]
having impport error ..tensorflow and tflearn

AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

i  am experiencing same import error in tflearn as well as tensorflow ..when i comment out import tensorflow same error is been reported as shown below ...
also thse libraries where working just fine a couple of days before ...i had imported them without showing errors .
i have just added python socketio and flask packages in virtual env
using python 3.6.10
tflearn :0.3
tensorflow :1.14
![Screenshot (65)](https://user-images.githubusercontent.com/65727171/85283770-890d9f00-b4ab-11ea-9d42-2094a54d75a7.png)
![Screenshot (64)](https://user-images.githubusercontent.com/65727171/85283781-8dd25300-b4ab-11ea-91d2-69381ab042b5.png)

_Originally posted by @BV-SS in https://github.com/tensorflow/tensorflow/issues/38589#issuecomment-647464978_

**Comment by amahendrakar** [comment]
@BV-SS,
Installation issues within the Anaconda environment are tracked in the Anaconda repo.

Could you please submit a new issue using [this link](https://github.com/ContinuumIO/anaconda-issues/issues) and fill in the template, so that the issue can be tracked there. Thanks!

**Comment by amahendrakar** [comment]
Also, please take a look at [this](https://stackoverflow.com/a/47278208) StackOverflow comment from a similar issue and let us know if it helps. Thanks!
