### ISSUE TITLE
retrying_file_system does not use exponential backoff

### ISSUE THREAD

**Issue by davidj-github** [tensorflow/tensorflow#4066]
In tensorflow-0.10.0rc0/tensorflow/core/platform/cloud/retrying_file_system.cc,
the retry logic does not insert a delay between successive attempts.

Status CallWithRetries(const std::function<Status()>& f) {
  int attempts = 0;
  while (true) {
    attempts++;
    auto status = f();
    if (!IsRetriable(status) || attempts >= kMaxAttempts) {
      return status;
    }
    LOG(ERROR) << "The operation resulted in an error and will be retried: "
               << status.ToString();
  }
}

**Comment by prb12** [comment]
Yes-  this retry logic does look pretty basic.  
@davidj-github  Could you please explain a bit more about the problem you are having.
@rinugun  Is there another backoff mechanism at a lower level (e.g. in an RPC layer?) or does this just retry 4 times without sleeping?

**Comment by davidj-github** [comment]
I was reviewing the code and noticed that it does not conform to Google's recommendation to insert a delay between retries.

**Comment by prb12** [comment]
@davidj-github I agree this is not usually very desirable behavior.  If it's not causing you an immediate problem, then I assume there's no great urgency here?  I'll let the authors of this module comment further.

**Comment by rinugun** [comment]
That's correct, there is no backoff, it simply retries 3 times, so that there is at most 4 attempts including the original one.

The underlying layers do not attempt any retries.

The reason for the lack of a backoff was that the actual Google Cloud Storage errors don't require it -- very infrequently GCS can return an internal error for a read or write operation and an immediate retry typically succeeds.

That said, I don't mind having a backoff if it's recommended.

**Comment by moontails** [comment]
I would like to work on this

**Comment by moontails** [comment]
Updating CallWithRetries to do exponential backoff #4501 .

Could you all please review?

**Comment by davidj-github** [comment]
Schlumberger-Private
The Cloud storage documentation for exponential backoff recommends adding a random term to the sleep time. See https://cloud.google.com/storage/docs/exponential-backoff

**Comment by moontails** [comment]
@davidj-github @rinugun 

Proposed changes to incorporate the above random sleep for milliseconds

```
#include <chrono>
#include <random>
#include <thread>

void WaitBeforeRetry(const int delay_seconds) {
    std::random_device rd;
    std::mt19937 gen(rd());
    std::uniform_int_distribution<> dist(1, 1000);

    const int delay_milliseconds = delay_seconds * 1000;
    const int random_milliseconds = dist(gen);
    const int delay = std::min(delay_to_milliseconds + random_milliseconds,
                                                kMaximumBackoffSeconds);

    std::this_thread::sleep_for(std::chrono::milliseconds(delay));
}

Status CallWithRetries(const std::function<Status()>& f,
                       const int initial_delay_seconds) {
  int retries = 0;
  while (true) {
    auto status = f();
    if (!IsRetriable(status) || retries >= kMaxRetries) {
      return status;
    }
    LOG(ERROR) << "The operation resulted in an error and will be retried: "
               << status.ToString();
    WaitBeforeRetry(initial_delay_seconds << retries);
    retries++;
  }
}



```

**Comment by moontails** [comment]
@davidj-github @rinugun @prb12 what do you guys think?

**Comment by rinugun** [comment]
I'm curious, is random delay better than the fixed delay that was
implemented in https://github.com/tensorflow/tensorflow/pull/4501? The
random sub-second sleep seems to be adding a particular complexity to the
retry logic, I wonder if this is justified and what the expected wins are.

**Comment by moontails** [comment]
From the Google Cloud storage documentation - 

> random_number_milliseconds is a random number of milliseconds less than or equal to 1000. This helps to avoid cases where many clients get synchronized by some situation and all retry at once, sending requests in synchronized waves. The value of random_number_milliseconds is recalculated after each retry request.

**Comment by rinugun** [comment]
I could only find this text in Google Analytics docs (
https://developers.google.com/analytics/devguides/reporting/core/v4/errors),
is that also mentioned somewhere for the Google Cloud Storage docs?
Anyways, I agree that it might be potentially useful. I have a few comments
re the code snippet:
 - not sure <chrono> is supported in the TF code, but you could use
Env::Default()->SleepForMilliseconds() from env.h instead
 - other minor comments, probably could be discussed during a code review

Thanks
Alex

**Comment by moontails** [comment]
It is documented here - https://cloud.google.com/storage/docs/exponential-backoff

**Comment by moontails** [comment]
@davidj-github @rinugun @prb12 have updated the PR(#4501) to include the random millisecond delay. Please review!

**Comment by moontails** [comment]
shouldnt this be marked closed?
