### ISSUE TITLE
Windowing on multiple timeseries

### ISSUE THREAD

**Issue by JoSw16** [tensorflow/tensorflow#40669]
Usecase:
I have 360 day history of 1000 company stocks. My requirement is to create overlapping windows of the timeseries data for every company stock.

Current Solution (none TF one):
Currently I have implemented this by grouping the data on 'company' and applying a function that creates multi-step input and multistep output using pd.shift() function. Looking to upgrade the code using Tensorflow2.2 preprocessing functions.

Partial solutions tried:
I have tried the "window" function of the tf.data.Dataset that comprises of a single company's history. And I have tried the group_by_reducer function to group the data using 'company' as key. But could not figure a complete solution that can replace my current solution.

Please let me know if any code snippets are required. Appreciate any help or pointers on this.

Regards,
Jo

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
