### ISSUE TITLE
Very strange Reshape layer behavier in Keras

### ISSUE THREAD

**Issue by fire717** [tensorflow/tensorflow#40666]
**System information**
- win10
- TensorFlow installed from pip
- TensorFlow version (use command below): 1.15.0, cpu version
- Python version: 3.6
- Keras: 2.2.4

**Describe the current behavior**
while I create a net,like this:

```
print(priorbox3.shape) #got (?, 38, 38, 3, 8)
priorbox3_reshape = Reshape((38*38*3, 4))(priorbox3)
print(priorbox3_reshape.shape) #(?, 4332, 4)
```

It runs successfully, but in fact 38 * 38 * 3 * 8 != 4332 * 4!

 if I set Reshape((38 * 38 * 3, 8)), I will get a mismatch error.

You can download the code and run:

```
python libfacemodel.py
```

[code.zip](https://github.com/tensorflow/tensorflow/files/4812938/code.zip)

**Comment by Saduf2019** [comment]
@fire717 
I ran the code shared and face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/b773342f5175609abe9e1e9d36038a66/untitled238.ipynb)

**Comment by fire717** [comment]
> @fire717
> I ran the code shared and face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/b773342f5175609abe9e1e9d36038a66/untitled238.ipynb)

thx for reply, in your gist link, i just saw two blocks,
```
pip install tensorflow==1.14

print(priorbox3.shape) #got (?, 38, 38, 3, 8)
priorbox3_reshape = Reshape((38*38*3, 4))(priorbox3)
print(priorbox3_reshape.shape) #(?, 4332, 4)
```

of course, you'll get priorbox3 not define error.

I didn't saw the 3 python files in code.zip I uploaded here.

**Comment by fire717** [comment]
I've paste the 3 files and meet the same error :
[gist here](https://colab.research.google.com/gist/fire717/d0ea1f2528680e4af4b4021af6f55c88/untitled238.ipynb)

**Comment by fire717** [comment]
I sovled this by rewrite the layer function: compute_output_shape.
