### ISSUE TITLE
Tensorflow import issues

### ISSUE THREAD

**Issue by codey-code** [tensorflow/tensorflow#40664]
i can't import tensorflow in python
because it says 'ModuleNotFoundError: No module named 'tensorflow.contrib''
tensorflow version is 2.x
what should i do?
windows 8.1
complete nooob to ml and ai
(i am new to github)

**Comment by codey-code** [comment]
please help :/

**Comment by amahendrakar** [comment]
@codey-code,
Seems like you are trying to run code meant for TF 1.x on TF 2.x. 

`tensorflow.contrib` has been deprecation in TensorFlow 2.x. For more information, please take a look at [this guide](https://www.tensorflow.org/guide/migrate#a_note_on_slim_contriblayers). Thanks!

**Comment by codey-code** [comment]
a question: we can't import tensorflow 2.x ?
i just used "import tensorflow"?

**Comment by codey-code** [comment]
anyways.... what version of tensorflow should i use?

**Comment by amahendrakar** [comment]
> a question: we can't import tensorflow 2.x ?

Please run the below code to check if TensorFlow was installed successfully. 
```
import tensorflow as tf
print(tf.__version__)
```


> anyways.... what version of tensorflow should i use?

You can try running the code with TF v1.15.3. But I'd suggest you to migrate the code to TF 2.x since TF 1.x is not actively supported. Thanks!

**Comment by codey-code** [comment]
well it din't work
import tensorflow as tf
print(tf.__version__)

**Comment by mihaimaruseac** [comment]
What was the output? 'It didn't work" does not give us actionable information and we cannot help you by guessing what the error was.

Also, when posting code, please use markdown formatting around it to make it readable. A readable and well written issue request gets solved ~10 times faster than one who is not like that, according to studies.

**Comment by codey-code** [comment]
sorry @mihaimaruseac here is the error
```
 'ModuleNotFoundError: No module named 'tensorflow.contrib''
```
i can't get through this to even check its version

**Comment by amahendrakar** [comment]
@codey-code,
Could you please run the below commands and paste the output here.

- `python3 --version`

- `pip3 freeze`

Also, try creating a Python virtual environment and check if you are facing the same issue. Thanks!

**Comment by mihaimaruseac** [comment]
`pip list` should display versions for all installed packages. `tf.contrib` no longer exists since TF 2.0.
