### ISSUE TITLE
quantization not yet supported for op %

### ISSUE THREAD

**Issue by sunzhe09** [tensorflow/tensorflow#40676]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):tf-nightly2.3
- TensorFlow version (or github SHA if from source):

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
# Copy and paste here the exact command
```
conventer=tf.lite.TFLiteConverter.from_keras_model(inference)
conventer.optimizations = [tf.lite.Optimize.DEFAULT]
conventer.representative_dataset = representative_data_gen
conventer.experimental_new_converter=True
conventer.target_spec.supported_ops=[tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
conventer.inference_input_type = tf.uint8  # or tf.uint8
conventer.inference_output_type = tf.uint8  # or tf.uint8
tflitemodel=conventer.convert()
open("./centernet.tflite","wb").write(tflitemodel)

**The output from the converter invocation**
quantization not yet supported for op % 
```
# Copy and paste the output here.
```

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)
post-traiing quantization for uint8 model 

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**
got an error:quantization not yet supported for op %
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
Can you please attach your model/ share google colab code to debug further? Thanks!

**Comment by sunzhe09** [comment]
@ymodak  I think  it was in my topk op， the code  is here：
    def __topK(scores, K):
        B, H, W, C = scores.shape
        scores = tf.reshape(scores, shape=(B, -1))
        topk_scores, topk_inds = tf.math.top_k(input=scores, k=K, sorted=True)
        topk_clses = topk_inds % C
        topk_xs = tf.cast(topk_inds // C % W, tf.float32)
        topk_ys = tf.cast(topk_inds // C // W, tf.float32)
        topk_inds = tf.cast(topk_ys * tf.cast(W, tf.float32) + topk_xs, tf.int32)
        return topk_scores, topk_inds, topk_clses, topk_ys, topk_xs

**Comment by ymodak** [comment]
Thanks for your response. Are you able to quantize correctly if you remove`%` operations from the code above?

**Comment by sunzhe09** [comment]
@ymodak   yes without % it can convert  success

**Comment by ymodak** [comment]
If still using `%` op in your code try setting custom_op flag true and convert again.
`python
converter.allow_custom_ops = True
`
