### ISSUE TITLE
saved_model_cli convert tensorrt adds unknown inputs to serving signature

### ISSUE THREAD

**Issue by ievgen-goichuk-rft** [tensorflow/tensorflow#40686]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Catalina 10.15.4 
- TensorFlow installed from (source or binary): pip install
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.7

**Describe the current behavior**
```
saved_model_cli convert \
    --dir /tmp/bert \
    --output_dir /tmp/bert-fp16 \
    --tag_set serve \
    tensorrt --precision_mode FP16
```
results in the 100s additional inputs in the converted model `serving_default` signature.  

```
signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input_mask'] tensor_info:
        dtype: DT_INT32
        shape: (-1, -1)
        name: serving_default_input_mask:0
    inputs['input_type_ids'] tensor_info:
        dtype: DT_INT32
        shape: (-1, -1)
        name: serving_default_input_type_ids:0
    inputs['input_word_ids'] tensor_info:
        dtype: DT_INT32
        shape: (-1, -1)
        name: serving_default_input_word_ids:0
    inputs['unknown'] tensor_info:
        dtype: DT_RESOURCE
        shape: ()
        name: serving_default_unknown:0
    inputs['unknown_0'] tensor_info:
        dtype: DT_RESOURCE
        shape: ()
        name: serving_default_unknown_0:0
    inputs['unknown_1'] tensor_info:
        dtype: DT_RESOURCE
        shape: ()
        name: serving_default_unknown_1:0
    inputs['unknown_10'] tensor_info:
        dtype: DT_RESOURCE
        shape: ()
        name: serving_default_unknown_10:0
    inputs['unknown_100'] tensor_info:
        dtype: DT_RESOURCE
        shape: ()
        name: serving_default_unknown_100:0
    inputs['unknown_101'] tensor_info:
        dtype: DT_RESOURCE
        shape: ()
        name: serving_default_unknown_101:0
    inputs['unknown_102'] tensor_info:
        dtype: DT_RESOURCE
        shape: ()
        name: serving_default_unknown_102:0
...
```

**Describe the expected behavior**
Converted signature corresponds to the original SavedModel

```
signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input_mask'] tensor_info:
        dtype: DT_INT32
        shape: (-1, -1)
        name: serving_default_input_mask:0
    inputs['input_type_ids'] tensor_info:
        dtype: DT_INT32
        shape: (-1, -1)
        name: serving_default_input_type_ids:0
    inputs['input_word_ids'] tensor_info:
        dtype: DT_INT32
        shape: (-1, -1)
        name: serving_default_input_word_ids:0
  The given SavedModel SignatureDef contains the following output(s):
...
```
**Standalone code to reproduce the issue**
Try converting BERT from TF Hub
https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/2

**Comment by ravikyram** [comment]
@ievgen-goichuk-rft 

This issue is more suitable for TensorFlow Serving repo. Please post it on Serving repo from [here.](https://github.com/tensorflow/serving/issues) Thanks!

**Comment by ievgen-goichuk-rft** [comment]
OK. I have raised a https://github.com/tensorflow/serving/issues/1675 .

**Comment by ravikyram** [comment]
@ievgen-goichuk-rft 

Can we close the issue here and track the issue in serving repo. Please, confirm.Thanks!

**Comment by ievgen-goichuk-rft** [comment]
@ravikyram Well, they closed an issue in tensorflow/serving saying I need to raise it either here or in tensorflow/tensorrt. And a similar issue was raised in there https://github.com/tensorflow/tensorrt/issues/202  but nobody from ternsorrt has confirmed so far it is their work.

**Comment by sushreebarsa** [comment]
@ievgen-goichuk-rft  Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!
