### ISSUE TITLE
tf.keras.activations.relu doesn't support fp16 through mixed precision for threshold greater than 0

### ISSUE THREAD

**Issue by vishalsubbiah** [tensorflow/tensorflow#40687]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2
- Python version: 3.6
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
tf.keras.activations.relu doesn't support fp16 for threshold greater than 0. The documentation says it should honor the input dtype but defaults to float32 through floatx
**Describe the expected behavior**
Should cast to input dtype instead of floatx

Addressing issue in pr #40685

**Comment by Saduf2019** [comment]
@vishalsubbiah 
The pr is in merged status, please let us know if we could move this to closed status.

**Comment by vishalsubbiah** [comment]
@Saduf2019  it can be closed.
