### ISSUE TITLE
Segmentation fault when running TFLite's benchmark_model

### ISSUE THREAD

**Issue by prabhat00155** [tensorflow/tensorflow#40680]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Darwin Kernel Version 19.5.0(for model conversion, Linux 4.9.140-tegra for running the benchmark tool)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Installed TFLite benchmark_model tool using the instructions given here: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark.
- TensorFlow version (use command below): N/A
- Python version: N/A
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I converted emotion_ferplus (https://github.com/onnx/models/tree/master/vision/body_analysis/emotion_ferplus) ONNX model to TF using onnx-tensorflow(https://github.com/onnx/onnx-tensorflow) and then converted the TF model to TFLite using tflite_convert.
```
$ onnx-tf convert -i model.onnx -o emotion.pb
$ tflite_convert --enable_v1_converter --graph_def_file=emotion.pb --output_file=emotion.tflite --output_format=TFLITE --input_shape=1,1,64,64 --input_arrays=Input3 --output_arrays=Plus692_Output_0 --inference_type=FLOAT --input_data_type=FLOAT
```
Then I ran benchmark_model tool on the tflite model I got from the previous step.
```
onnxruntime@onnxruntime-desktop:~/Documents/tensorflow$ bazel-bin/tensorflow/lite/tools/benchmark/benchmark_model --graph=emotion.tflite --num_runs=10 --num_threads=4
STARTING!
Duplicate flags: num_threads
Min num runs: [10]
Min runs duration (seconds): [1]
Max runs duration (seconds): [150]
Inter-run delay (seconds): [-1]
Num threads: [0]
Benchmark name: []
Output prefix: []
Min warmup runs: [1]
Min warmup runs duration (seconds): [0.5]
Graph: [emotion.tflite]
Input layers: []
Input shapes: []
Input value ranges: []
Input layer values files: []
Allow fp16 : [0]
Require full delegation : [0]
Enable op profiling: [0]
Max profiling buffer entries: [1024]
CSV File to export profiling data to: []
Enable platform-wide tracing: [0]
#threads used for CPU inference: [0]
Max number of delegated partitions : [0]
Min nodes per partition : [0]
External delegate path : []
External delegate options : []
Use gpu : [0]
Use xnnpack : [0]
Loaded model ../models/tflite/emotion.tflite
The input model file size (MB): 35.0461
Initialized session in 1.645ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
Segmentation fault (core dumped)

```

**Describe the expected behavior**
benchmark tool should run without crashing and give model performance metrics like the following:
```
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=10 first=101249 curr=46906 min=46491 max=101249 avg=52839.8 std=16163

Running benchmark for at least 10 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=22 first=46543 curr=46554 min=46473 max=49668 avg=46957.8 std=627

Inference timings in us: Init: 218485, First inference: 101249, Warmup (avg): 52839.8, Inference (avg): 46957.8
Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
Peak memory footprint (MB): init=1.23047 overall=28.8906
```

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by talumbau** [comment]
Hi Can you attach the generated TF lite model? Thanks!

**Comment by prabhat00155** [comment]
> Hi Can you attach the generated TF lite model? Thanks!

How do you suggest I do that? I can't attach a TFLite model here. Also, if you follow the steps mentioned above, you can get the TFLite model.

**Comment by talumbau** [comment]
The dialog box I am typing in now says "Attach files by dragging and dropping":

<img width="530" alt="Screen Shot 2020-06-23 at 7 48 18 AM" src="https://user-images.githubusercontent.com/1891418/85418755-0675f580-b526-11ea-99e9-7551fa77677f.png">


I think this should work for the model.

**Comment by prabhat00155** [comment]
You can't attach a TFLite model here(unsupported file type).

**Comment by prabhat00155** [comment]
I tried creating a zip and attaching it, but the zipped version is 31 MB and there is a 10 MB limit here.

**Comment by talumbau** [comment]
Ah I see. I created the `emotion.pb` file by using `onnx-tf` released version with TF 1.15. I was unable to convert this tflite_convert. What version of TF did you use for TF->TFL conversion? Can you execute the instructions in the template so we can get version information?

**Comment by prabhat00155** [comment]
```
(onnxrt_env) prroy-Mac:emotion_ferplus prroy$ python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
v1.15.0-92-g5d80e1e8e6 1.15.2
(onnxrt_env) prroy-Mac:emotion_ferplus prroy$ tflite_convert --enable_v1_converter --graph_def_file=emotion.pb --output_file=emotion.tflite --output_format=TFLITE --input_shape=1,1,64,64 --input_arrays=Input3 --output_arrays=Plus692_Output_0 --inference_type=FLOAT --input_data_type=FLOAT
2020-06-24 13:49:23.852168: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-06-24 13:49:23.863606: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fbd4d6ecc90 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-24 13:49:23.863622: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-24 13:49:24.062042: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2020-06-24 13:49:24.062143: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-06-24 13:49:24.500949: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:786] Optimization results for grappler item: graph_to_optimize
2020-06-24 13:49:24.500974: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   constant_folding: Graph size after: 175 nodes (-86), 174 edges (-56), time = 243.756ms.
2020-06-24 13:49:24.500979: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   constant_folding: Graph size after: 175 nodes (0), 174 edges (0), time = 86.759ms.
```

**Comment by talumbau** [comment]
thanks! I was able to successfully convert the model. When I visualized it with `tensorflow/lite/tools:visualize` I see that the model has int64 inputs to the ADD op:

<img width="1396" alt="Screen Shot 2020-06-24 at 2 34 08 PM" src="https://user-images.githubusercontent.com/1891418/85630269-33aacc80-b628-11ea-9e03-f57bfba880cc.png">

This is not supported in TF Lite, so when I run`benchmark_model` I get this error:

```
ERROR: Inputs and outputs not all float|uint8|int16 types.
ERROR: Node number 3 (ADD) failed to invoke.
```

I converted the model successfully with `--target_ops=SELECT_TF_OPS` and then ran with `tensorflow/lite/tools/benchmark:benchmark_model_plus_flex`:

```
INFO: Created TensorFlow Lite delegate for select TF ops.
INFO: TfLiteFlexDelegate delegate: 102 nodes delegated out of 102 nodes with 1 partitions.

The input model file size (MB): 35.0607
Initialized session in 34.002ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=16 first=51470 curr=29156 min=28983 max=51470 avg=31982 std=5605

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=50 first=29166 curr=29189 min=28529 max=29906 avg=28935.9 std=255

Inference timings in us: Init: 34002, First inference: 51470, Warmup (avg): 31982, Inference (avg): 28935.9
```



By the way, I think it is best in this case to use the same version of `benchmark_model` as you used for the ONNX conversion. Apparently their toolchain requires TF 1.15, so I did a `git checkout` to release 1.15.2 before building and running benchmark_model. Perhaps there is a way to tell ONNX that the largest int type should be `int32`? I am not very familiar with the tool.

**Comment by prabhat00155** [comment]
> thanks! I was able to successfully convert the model. When I visualized it with `tensorflow/lite/tools:visualize` I see that the model has int64 inputs to the ADD op:
> 
> <img alt="Screen Shot 2020-06-24 at 2 34 08 PM" width="1396" src="https://user-images.githubusercontent.com/1891418/85630269-33aacc80-b628-11ea-9e03-f57bfba880cc.png">
> 
> This is not supported in TF Lite, so when I run`benchmark_model` I get this error:
> 
> ```
> ERROR: Inputs and outputs not all float|uint8|int16 types.
> ERROR: Node number 3 (ADD) failed to invoke.
> ```
> 
> I converted the model successfully with `--target_ops=SELECT_TF_OPS` and then ran with `tensorflow/lite/tools/benchmark:benchmark_model_plus_flex`:
> 
> ```
> INFO: Created TensorFlow Lite delegate for select TF ops.
> INFO: TfLiteFlexDelegate delegate: 102 nodes delegated out of 102 nodes with 1 partitions.
> 
> The input model file size (MB): 35.0607
> Initialized session in 34.002ms.
> Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
> count=16 first=51470 curr=29156 min=28983 max=51470 avg=31982 std=5605
> 
> Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
> count=50 first=29166 curr=29189 min=28529 max=29906 avg=28935.9 std=255
> 
> Inference timings in us: Init: 34002, First inference: 51470, Warmup (avg): 31982, Inference (avg): 28935.9
> ```
> 
> By the way, I think it is best in this case to use the same version of `benchmark_model` as you used for the ONNX conversion. Apparently their toolchain requires TF 1.15, so I did a `git checkout` to release 1.15.2 before building and running benchmark_model. Perhaps there is a way to tell ONNX that the largest int type should be `int32`? I am not very familiar with the tool.

I didn't get that error when running benchmark_model. The tool itself crashed with segmentation fault. I can retry everything on latest TF version.

**Comment by prabhat00155** [comment]
I upgraded TF version and saw the error:
ERROR: tensorflow/lite/kernels/add.cc:326 Type INT64 is unsupported by op Add.
ERROR: Node number 5 (ADD) failed to invoke.

Shouldn't tflite_convert fail in such cases?

**Comment by herbiezhao** [comment]
> I upgraded TF version and saw the error:
> ERROR: tensorflow/lite/kernels/add.cc:326 Type INT64 is unsupported by op Add.
> ERROR: Node number 5 (ADD) failed to invoke.
> 
> Shouldn't tflite_convert fail in such cases?

Did you solve it, I have the same problem.

**Comment by prabhat00155** [comment]
> > I upgraded TF version and saw the error:
> > ERROR: tensorflow/lite/kernels/add.cc:326 Type INT64 is unsupported by op Add.
> > ERROR: Node number 5 (ADD) failed to invoke.
> > Shouldn't tflite_convert fail in such cases?
> 
> Did you solve it, I have the same problem.

No, it didn't work for me.

**Comment by tengshaofeng** [comment]
I face the same error. any body solved?

**Comment by prabhat00155** [comment]
> I face the same error. any body solved?

I was unable to solve it. Perhaps @talumbau could help you. Also, as this is an unresolved issue, this issue should be reopened.
