### ISSUE TITLE
Tensorflow will not recognize GPU

### ISSUE THREAD

**Issue by Cillinc** [tensorflow/tensorflow#40683]
An truing to get TensorFlow to recognize that there is a GPU installed on the PC.  
Windows10 Pro 64bit version
Nvidia GTX1660 TI with latest drivers 
Tensorflow - 2.3.0-dev20200615
CUDA v10.0
cudnn 7.6.5.32

`print(device_lib.list_local_devices())`
```
print(device_lib.list_local_devices())
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 4283633287383166880
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 5791820499534504026
physical_device_desc: "device: XLA_CPU device"
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 15245658627817172966
physical_device_desc: "device: XLA_GPU device"
]
```
so system sees that there isa GPU installed, however 

```
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
Num GPUs Available:  0
```
Trying to get a model to train using the GPU to complete faster - my current training takes 5 hours per epoch.....please help as its for a college project and i really need the speed of the GPU to help.

**Comment by amahendrakar** [comment]
@Cillinc,
As per [this](https://github.com/tensorflow/tensorflow/issues/32967) similar issue installing the GPU package of TensorFlow fixed the issue. 

Could you please install TensorFlow using the command `pip install tf-nightly-gpu` and let us know if it works. Thanks!

**Comment by Cillinc** [comment]
```
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
Num GPUs Available:  1
```

tanks guys for the help - it's worknig now after :
`pip install tf-nightly-gpu `

**Comment by drElenaSmirnova** [comment]
hm.. after installing the above, tensor flow is failing to be imported: 

tf.__internal__.register_load_context_function(in_load_context)
AttributeError: module 'tensorflow.compat.v2.__internal__' has no attribute 'register_load_context_function'

**Comment by Taechai** [comment]
> 

I found that problem is from Keras packages, so I execute these commands

```
pip uninstall keras
pip install tensorflow
```

**Comment by Taechai** [comment]
> hm.. after installing tf-nightly-gpu, tensorflow is failing to be imported:
> 
> tf.**internal**.register_load_context_function(in_load_context) AttributeError: module 'tensorflow.compat.v2.**internal**' has no attribute 'register_load_context_function'

I found that problem is from Keras packages, so I execute these commands

```
pip uninstall keras
pip install tensorflow
```
