### ISSUE TITLE
Quuantization.keras.quantize_model failed for subclasses model

### ISSUE THREAD

**Issue by ek9852** [tensorflow/tensorflow#40699]
We are using a subclassed mode:
class MyNet(tf.keras.Model):

When trying to do 
model = MyNet()
model = tfmot.quantization.keras.quantize_model(model)

We get:
  File "/usr/local/lib/python3.7/site-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize.py", line 134, in quantize_model
    '`to_quantize` can only either be a tf.keras Sequential or '
**ValueError: `to_quantize` can only either be a tf.keras Sequential or Functional model**

So does quantization does not works on subclasses network ?
If so how can I get it to run on quantization only edge devices ?

**Comment by amahendrakar** [comment]
@ek9852,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by ek9852** [comment]
@amahendrakar 
# Tensorflow 2.2.0

import tensorflow as tf
import tensorflow_model_optimization as tfmot

class MyNet(tf.keras.Model):

    def __init__(self, filter_nbr=8):
        """Init MyNet fields."""
        super(MyNet, self).__init__()

        self.conv11 = tf.keras.layers.Conv2D(filter_nbr, kernel_size=3, padding='SAME')

    def call(self, inputs):
        """Forward method."""
        # Stage 1
        x11 = (tf.nn.relu(self.bn11(self.conv11(inputs))))

        return x1d


model = MyNet()
model = tfmot.quantization.keras.quantize_model(model)

# Got:
# ValueError: `to_quantize` can only either be a tf.keras Sequential or Functional model.

# expected no error

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.2 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/9303ee19320d88829887a61245a678ca/40699.ipynb). Thanks!

**Comment by gowthamkpr** [comment]
As the error message clearly suggests and looking into the [code](https://github.com/tensorflow/model-optimization/blob/570444d4b9afb56e91992e8f5ae61abb12f4384f/tensorflow_model_optimization/python/core/quantization/keras/quantize.py#L133), it only works for sequential or functional model, not subclassed  models.

**Comment by gowthamkpr** [comment]
Closing this issue as its not a bug/performance issue. Please add additional comments for us to open this issue again. Thanks!

**Comment by un-knight** [comment]
@ek9852 Hi, do you found a solution to this problem?
