### ISSUE TITLE
Conv1DTranspose documentation inconsistent with code and unclear

### ISSUE THREAD

**Issue by EnderWiggin14** [tensorflow/tensorflow#40692]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:

[https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv1DTranspose](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv1DTranspose)

## Description of issue (what needs changing):
The documentation claims that padding options {"valid" and "same"} are supported, but when following the code path to deconv_output_length at line 140 [here](https://github.com/tensorflow/tensorflow/blob/0c227aed65e62f741a88c9915923d262710fc8c9/tensorflow/python/keras/utils/conv_utils.py#L140) there is the option for {"full"} as well.

Additionally, the equation provided for calculating output shape merely says "padding" for a variable which is represented as a string in the API. This makes for a guessing game of how to achieve the desired output shape.

### Clear description

For example, why should someone use this method? How is it useful?

### Correct links
[https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/convolutional.py#L16](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/convolutional.py#L16l)
Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example?

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by jpodivin** [comment]
@EnderWiggin14 

> The documentation claims that padding options {"valid" and "same"} are supported, but when following the code path to deconv_output_length at line 140 here there is the option for {"full"} as well.

Full padding is just an extreme case of zero padding. When applied it makes output tensor larger than the input tensor. Unlike Tensorflow implementation, stand alone Keras doesn't allow 'full' padding. Instead it passes value of padding variable to  `_preprocess_padding`  helper function.

```
def _preprocess_padding(padding):
    """Convert keras' padding to tensorflow's padding.

    # Arguments
        padding: string, `"same"` or `"valid"`.

    # Returns
        a string, `"SAME"` or `"VALID"`.

    # Raises
        ValueError: if `padding` is invalid.
    """
    if padding == 'same':
        padding = 'SAME'
    elif padding == 'valid':
        padding = 'VALID'
    else:
        raise ValueError('Invalid padding: ' + str(padding))
    return padding

```
> Additionally, the equation provided for calculating output shape merely says "padding" for a variable which is represented as a string in the API. This makes for a guessing game of how to achieve the desired output shape.

The padding in this case means number of symbols, for example 0s, used to pad the tensor. Ideally it should be something like `padding_size`. 

The docs are, just like the code, derived from stand alone Keras, which defines output shape for [2D Transposed convolution](https://keras.io/api/layers/convolution_layers/convolution2d_transpose/) as:
```
new_rows = ((rows - 1) * strides[0] + kernel_size[0] - 2 * padding[0] +
output_padding[0])
new_cols = ((cols - 1) * strides[1] + kernel_size[1] - 2 * padding[1] +
output_padding[1])
```

**Comment by ymodak** [comment]
I think the documentation is correct. Following example fails;
```python
#TF 2.4.0-dev20200719
tf.keras.layers.Conv1DTranspose(filters = 2, kernel_size = 3, strides=1, padding='full', output_padding=None)
#Output -
ValueError: The `padding` argument must be a list/tuple or one of "valid", "same" 
(or "causal", only for `Conv1D). Received: full
```

**Comment by MarkDaoust** [comment]
@ymodak is correct about "full not being an option. 

> Additionally, the equation provided for calculating output shape merely says "padding" for a variable which is represented as a string in the API. This makes for a guessing game of how to achieve the desired output shape.

Yes, it could help if that part were more clar about how to convert from a padding string to a padding-length. `padding="vaild"`  == `padding=0` but `padding="same"` is more complicated.
