### ISSUE TITLE
Didn't find op for builtin opcode 'LOGISTIC' version '1'

### ISSUE THREAD

**Issue by mlubinsky-arm** [tensorflow/tensorflow#40704]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution: Mac OS 10.16
- TensorFlow installed from  source at  2020-06-22  ( git clone.. )
- Target platform :  Arm Mbed OS

**Describe the problem**

Run-time error on FRDM-K66F board:
```
Didn't find op for builtin opcode 'LOGISTIC' version '1'
Failed to get registration from op code LOGISTIC
```
I looked at the TFLite source code, at it uses LOGISTIC version=0 :

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/kernels/logistic.cc#L124

**Please provide the exact sequence of commands/steps when you ran into the problem**
Compiled code as described here:

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/micro_speech#deploy-to-nxp-frdm-k66f

Instead original model.cc I use my own model.cc which uses LOGISTIC op code.
Compiled, deployed to board and got the run-time error on FRDM-K66F board:
```
Didn't find op for builtin opcode 'LOGISTIC' version '1'
Failed to get registration from op code LOGISTIC
```

**Comment by wangtz** [comment]
Hi Michael,

version 0 is the default value passed in and it will be overwritten when the builtin operator is added. 

The error message seem to suggest that you didn't register this operator in the resolver.

Could you share which OpResovler are you using?

Also add @advaitjain who has been working on the versioning etc.

Thanks,

**Comment by mlubinsky-arm** [comment]
Adding operation to resolver solves the issue.
I expected what TFLite may figure out from the model file all  ops and register it automatically

**Comment by sushreebarsa** [comment]
@mlubinsky-arm Could you please let us know if the issue still persists and feel free to close the issue if it is resolved for you ? Thanks!
