### ISSUE TITLE
How to use Tensorflow Lite GPU support for python code

### ISSUE THREAD

**Issue by swim77** [tensorflow/tensorflow#40706]
<em>I want to run tflite model on GPU using python code. But it seems that the code does not use GPU (There's no increase in GPU resource usage.). Is it possible to give an GPU-related option in "tf.lite.Interpreter(model_path, option)"? </em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 16.04
- Python version:  3.6
- CUDA/cuDNN version: 10.1 
- GPU model and memory: 2080 ti

**Describe the current behavior**
tflite model with python code runs on cpu.

**Describe the expected behavior**
tflite model with python code runs on gpu.

**Comment by ravikyram** [comment]
@swim77 

Please, let us know which tensorflow version you are using?.Request you to share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by swim77** [comment]
I downloaded the tflite model from https://www.tensorflow.org/lite/models/image_classification/overview.

And used the simple code as below:
===============================================================
import cv2
import pathlib
import tensorflow as tf

folder_path = './data'

interpreter = tf.lite.Interpreter(model_path="test.tflite")
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
interpreter.allocate_tensors()

images = []

for file in pathlib.Path(folder_path).iterdir():

    img = cv2.imread(r"{}".format(file.resolve()))
    new_img = cv2.resize(img, (224, 224))

    images.append(new_img)

    interpreter.set_tensor(input_details[0]['index'], images)
    interpreter.invoke()
    output_data = [interpreter.get_tensor(output_details[i]['index']) for i in range(len(output_details))]

    images.clear()
===============================================================

The tensorflow version is 2.2.0.

**Comment by ymodak** [comment]
TF Lite does not support Nvidia gpu. See https://github.com/tensorflow/tensorflow/issues/34536#issuecomment-565632906
