### ISSUE TITLE
How to run TF lite model on Nvidia GPU (NNAPI or GPU delegate)?

### ISSUE THREAD

**Issue by swim77** [tensorflow/tensorflow#40712]
I found that TF lite targeted major mobile GPUs including Adreno, Mali, and PowerVR from closed issue (https://github.com/tensorflow/tensorflow/issues/34536).

1. I wonder if... I can run TF lite model on the gpu, Nvidia T4.

2. I wonder if... "TF lite model is optimized to mobile gpus" means the case of using NNAPI.
I want to check if the sentence above means that ... the gpus that I can run TF lite model using NNAPI is limited to mobile GPUs. But, it's possible to infer TF lite model on other gpus like Nvidia gpu using GPU delegate.

Thank you!

**Comment by impjdi** [comment]
1. I think with some plumbing, I think it should work for Nvidia GPUs.  For OpenGL backend, you will need Mesa.  For OpenCL backend, you will need OpenCL drivers for your Nvidia GPUs.  Same with Vulkan.

2. I don't think the models are optimized with a particular backend in mind.  The runtime incl. GPU parameters such as the workgroup sizes however are optimized for mobile.  You might achieve better performance with different numbers.
