### ISSUE TITLE
"Cannot find bazel" return 0 in configure.py

### ISSUE THREAD

**Issue by hedgehog91** [tensorflow/tensorflow#40719]
Hello!
In file configure.py inside a function check_bazel_version when bazel is not exists this function returns 0.

Here is a part of code:
  if which('bazel') is None:
    print('Cannot find bazel. Please install bazel.')
    sys.exit(0)

Should be sys.exit(1)? It's an error.

**Comment by mihaimaruseac** [comment]
Sounds good. Can you send a PR please?

**Comment by hedgehog91** [comment]
Yes
