### ISSUE TITLE
Writing custom py_function inside custom layer , gradient backpropagation

### ISSUE THREAD

**Issue by nikhil1008** [tensorflow/tensorflow#40717]
Hi , 

I'm writing a custom py_function inside a custom layer. But I get error during gradient backpropagation. I'm using tensorflow 1.1.4 with eager execution enabled. While debugging I reduced the complexity of code, and now 'm just trying 1-d DCT of input. I still get the error. 

Here is my code : 

from scipy.special import expit
from scipy.fftpack import dct, idct
import time

def fdct (a): 
    return dct(a.T, norm='ortho').T

def fdct_top (inp): 
    return tf.convert_to_tensor(np.array([fdct(in_) for in_ in list(inp.numpy())]))
    

def fidct (a): 
    return idct(a.T, norm='ortho').T

def fidct_top (inp): 
    return tf.convert_to_tensor(np.array([fidct(in_) for in_ in list(inp.numpy())]))

    
class MyDenseLayer(tf.keras.layers.Layer):
  def __init__(self, y_mat):
    super(MyDenseLayer, self).__init__()
    self.w_mat = y_mat
    
  def build(self, input_shape):
    self.w = tf.Variable (initial_value = self.w_mat, trainable = True)
  
  def call(self, input):
    dct_i = tf.py_function (fdct_top, (input,), 'float32')
    dct_i.set_shape(tf.TensorShape((None, 10)))
    
    dcts_q = tf.multiply(dct_i, 1/self.w)    
    print(dcts_q)
    z_floored_NOT_differentiable = tf.floor(dcts_q)
    z_floored_differentiable = (dcts_q - (tf.stop_gradient(dcts_q) - z_floored_NOT_differentiable))
    print(z_floored_differentiable)
    dcts_deg = tf.multiply(z_floored_differentiable, tf.cast(self.w, 'float32'))
    
    dcts_deg = tf.py_function (fidct_top, (dcts_deg,), 'float32')
    dcts_deg.set_shape(tf.TensorShape((None, 10)))
    
    return dcts_deg

img_inputs1 = keras.Input(shape=(10,))
q_mat = 5*np.ones((10)).astype(np.float32)
mul_layer = MyDenseLayer (q_mat)
outputs = mul_layer (img_inputs1)
model = keras.Model(inputs=[img_inputs1], outputs=outputs)
model.summary()

x = 10*np.random.rand(100,10).astype(np.float32)
y = x 

optimizer = tf.keras.optimizers.RMSprop(0.1)

model.compile(loss=tf.keras.losses.MSE,
                optimizer=optimizer,
                 )

history = model.fit(x, y, epochs = 50 )

InvalidArgumentError: Input to reshape is a tensor with 10 values, but the requested shape has 320
	 [[{{node training_1/RMSprop/gradients/Mul_3_grad/Reshape}}]] [Op:StatefulPartitionedCall]

**Comment by Saduf2019** [comment]
@nikhil1008 
I ran your code on tf 1.14 and 2.2 and do not face any error as reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/a80dfe73ebd37b6c1cf63e7ae7f43164/untitled238.ipynb).

**Comment by NickNickGo** [comment]
Hi, 
I think the Indentation in your code was not same as mine , I corrected it in your notebook. 

Here is my full code : 

https://colab.research.google.com/drive/1ZEc9cGJ6uNT6ZBxwxIX08J4-RR9_rEzU#scrollTo=lMYfv3ChvZRE



pasting here as well : 


import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from PIL import Image
CUDA_VISIBLE_DEVICES=0
tf.compat.v1.enable_eager_execution()
tf.compat.v1.enable_v2_behavior

from scipy.special import expit
from scipy.fftpack import dct, idct
import time

def fdct (a): 
    return dct(a.T, norm='ortho').T

def fdct_top (inp): 
    return tf.convert_to_tensor(np.array([fdct(in_) for in_ in list(inp.numpy())]))
    

def fidct (a): 
    return idct(a.T, norm='ortho').T

def fidct_top (inp): 
    return tf.convert_to_tensor(np.array([fidct(in_) for in_ in list(inp.numpy())]))

    
class MyDenseLayer(tf.keras.layers.Layer):
  def __init__(self, y_mat):
    super(MyDenseLayer, self).__init__()
    self.w_mat = y_mat
    
  def build(self, input_shape):
    self.w = tf.Variable (initial_value = self.w_mat, trainable = True)
  
  def call(self, input):
    dct_i = tf.py_function (fdct_top, (input,), 'float32')
    dct_i.set_shape(tf.TensorShape((None, 10)))
    
    dcts_q = tf.multiply(dct_i, 1/self.w)    
    print(dcts_q)
    z_floored_NOT_differentiable = tf.floor(dcts_q)
    z_floored_differentiable = (dcts_q - (tf.stop_gradient(dcts_q) - z_floored_NOT_differentiable))
    print(z_floored_differentiable)
    
    dcts_deg = tf.multiply(z_floored_differentiable, tf.cast(self.w, 'float32'))

    dcts_deg = tf.py_function (fidct_top, (dcts_deg,), 'float32')
    dcts_deg.set_shape(tf.TensorShape((None, 10)))


    return dcts_deg

img_inputs1 = keras.Input(shape=(10,))
q_mat = 5*np.ones((10)).astype(np.float32)
mul_layer = MyDenseLayer (q_mat)
outputs = mul_layer (img_inputs1)
model = keras.Model(inputs=[img_inputs1], outputs=outputs)
model.summary()

x = 10*np.random.rand(100,10).astype(np.float32)
y = x 

optimizer = tf.keras.optimizers.RMSprop(0.1)

model.compile(loss=tf.keras.losses.MSE,
                optimizer=optimizer,
                 )

history = model.fit(x, y, epochs = 50, batch_size  = 1 )

**Comment by Saduf2019** [comment]
@nikhil1008 
I had to correct the indentation in your code else i am facing indentation error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/68a3926dc13fcd6f4f29daeedcc24117/untitled238.ipynb).
Please share a  colab gist with your code where you face an error. the above link is not accessible.
Is there any particular reason for using older version on tf when later versions are available, you could try using later versions and let us know if that helps.

**Comment by NickNickGo** [comment]
@Saduf2019 

I edited **your** notebook, Please take a look. The issue is reproducible now. 

https://colab.research.google.com/gist/Saduf2019/68a3926dc13fcd6f4f29daeedcc24117/untitled238.ipynb#scrollTo=bR0mK9eG0CHF

I have dependency over cuda version , therefore I need to use TF=1.14. Btw, I tried with 2.2.0 as well , I get same error.

**Comment by NickNickGo** [comment]
Please use following link in case you can't see changes I made to your notebook. 

https://colab.research.google.com/drive/1s9QPYIclIMcrcFPkrhcOhOHemB-LSuKl?usp=sharing

**Comment by karmel** [comment]
There is a lot that has changed between 1.14 and 2.x, especially for eager execution. Can you retry this with a pure 2.x install, and open a new issue if you run into trouble?
