### ISSUE TITLE
Question: About Intra-threadpool core affinity

### ISSUE THREAD

**Issue by Leslie-Fang** [tensorflow/tensorflow#40711]
When we use the intra-threadpool, which I believe is based on pthread,it seems we didn't find some where the code would try to set the CPU hard affinity
https://github.com/tensorflow/tensorflow/blob/e5023a1738cce7efcdf9d87863b85c80ab2f8c9e/tensorflow/core/common_runtime/local_device.cc#L114-L159
by calling the functions like `pthread_setaffinity_np` and `pthread_getaffinity_np` 
Is anyone knowing the reason behind?

**Comment by Saduf2019** [comment]
@Leslie-Fang 
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by Leslie-Fang** [comment]
@Saduf2019 Thanks, I will open it in StackOverflow.
