### ISSUE TITLE
BERT has a invaild variable

### ISSUE THREAD

**Issue by transformerzhou** [tensorflow/tensorflow#40715]
tensorflow 2.2.0
tensorflow_hub 0.8.0

my code is `bert_url = r"https://tfhub.dev/tensorflow/bert_en_cased_L-12_H-768_A-12/2"

 bert = hub.KerasLayer(bert_url, trainable=True)

 print(bert.variables[-1])`
and the result is '**<tf.Variable 'Variable:0' shape=() dtype=bool, numpy=False>**'
my another task is limited by the variable, how to remove it?

**Comment by amahendrakar** [comment]
@transformerzhou,
Issues related to Hub modules are tracked in the TensorFlow Hub repo. 

Could you please submit a new issue from [this link](https://github.com/tensorflow/hub/issues/new) and fill in the template, so that we can track the issue there. Thanks!
