### ISSUE TITLE
Invalid test case from test_zero_padding_2d in convolutional_test.py

### ISSUE THREAD

**Issue by xingyu-long** [tensorflow/tensorflow#40724]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04

**Describe the current behavior**
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/convolutional_test.py#L654 
They try to test on different data_format configurations, ie. `channels_first`, `channels_last`. But for the code in the abovementioned link, it's meaningless, it always takes the last inputs. We should construct the inputs separately under different conditions. Even though it didn't cause any error but it should be fixed.

**Comment by jpodivin** [comment]
Would something like:

```
    data_formats = zip(['channels_first', 'channels_last'], 
        [(num_samples, stack_size, input_num_row, input_num_col), 
            (num_samples, input_num_row, input_num_col, stack_size)])
            
    for data_format, shape in data_formats:
      inputs = np.ones(shape)
```
do the trick?

**Comment by xingyu-long** [comment]
already fixed. https://github.com/tensorflow/tensorflow/pull/41253
