### ISSUE TITLE
Incorrect documentation for model_from_config 

### ISSUE THREAD

**Issue by Trel725** [tensorflow/tensorflow#40725]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/keras/models/model_from_config

## Description of issue (what needs changing):

tf.keras.models.model_from_config function can create only layers, not the complete model as it is described in documentation. Correct usage is mentioned at https://www.tensorflow.org/guide/keras/save_and_serialize, but not described in the main documenation for tf.keras.Model class.

> Calling config = model.get_config() will return a Python dict containing the configuration of the model. The same model can then be reconstructed via Sequential.from_config(config) (for a Sequential model) or Model.from_config(config) (for a Functional API model).

### Clear description
The behavior of tf.keras.models.model_from_config does not correspond to the documentation.
Moreover, it is even more confusing when compared with similar methods, like

`tf.keras.models.model_from_json(model.to_json())`

> <tensorflow.python.keras.engine.training.Model at 0x7fa2e443aa20>

`tf.keras.models.model_from_yaml(model.to_yaml())`

> <tensorflow.python.keras.engine.training.Model at 0x7fa2e443ca40>

while model_from_config 

`tf.keras.models.model_from_config(model.get_config())`

> > ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> <ipython-input-99-f3b4bb685ac8> in <module>
> ----> 1 tf.keras.models.model_from_config(model.get_config())
> 
> ~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/model_config.py in model_from_config(config, custom_objects)
>      53                     '`Sequential.from_config(config)`?')
>      54   from tensorflow.python.keras.layers import deserialize  # pylint: disable=g-import-not-at-top
> ---> 55   return deserialize(config, custom_objects=custom_objects)
>      56 
>      57 
> 
> ~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py in deserialize(config, custom_objects)
>      99   globs['SequenceFeatures'] = sfc.SequenceFeatures
>     100 
> --> 101   layer_class_name = config['class_name']
>     102   if layer_class_name in _DESERIALIZATION_TABLE:
>     103     config['class_name'] = _DESERIALIZATION_TABLE[layer_class_name]
> 
> KeyError: 'class_name'
> 

### Correct usage

`tf.keras.Model().from_config(model.get_config())`

> <tensorflow.python.keras.engine.training.Model at 0x7fa2e4480080>

**Comment by yil532** [comment]
Hi, can I work on this issue? Push a PR to solve this?

**Comment by ymodak** [comment]
@yil532 Feel free to raise one and tag this issue. Thanks!

**Comment by yil532** [comment]
Thank you @ymodak

**Comment by ymodak** [comment]
Closing this issue since the PR has merged. Thanks!
