### ISSUE TITLE
Unexpected difference in scatter_nd_update variants

### ISSUE THREAD

**Issue by AlexKuhnle** [tensorflow/tensorflow#40729]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 (subsystem on Windows)
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.6.6
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**

This problem (?) was observed for a [unit-test in the RL framework Tensorforce](https://github.com/tensorforce/tensorforce/blob/tf2/test/test_saving.py#L226) when using `tf.saved_model`. When using `variable.scatter_nd_update(indices, updates)`, I get the exception below. When instead using `value = tf.tensor_scatter_nd_update(variable, indices, updates); variable.assign(value)`, everything works well. The assignment happens [here](https://github.com/tensorforce/tensorforce/blob/tf2/tensorforce/core/models/tensorforce.py#L1012).

**Describe the expected behavior**

I would expect that both functions use the same implementation of the `scatter_nd_update` functionality, so I don't understand why one works and the other doesn't.

**Other info / logs**

```
Traceback (most recent call last):
  File "python3.6/site-packages/tensorflow/python/framework/importer.py", line 497, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: The inner -2 dimensions of input.shape=[] must match the inner 1 dimensions of updates.shape=[?,1]: Shapes must be equal rank, but are 0 and 1 for '{{node agent/ResourceScatterNdUpdate}} = ResourceScatterNdUpdate[T=DT_BOOL, Tindices=DT_INT64, _output_shapes=[], use_locking=true](agent_resourcescatterndupdate_ref:0, agent/stack_1:0, args_0:0)' with input shapes: [], [?,2], [?,1].
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  Tensorforce/test/test_saving.py", line 227, in test_explicit
    agent = tf.saved_model.load(export_dir=os.path.join(self.__class__.directory, 'agent-1'))
  File "python3.6/site-packages/tensorflow/python/saved_model/load.py", line 578, in load
    return load_internal(export_dir, tags)
  File "python3.6/site-packages/tensorflow/python/saved_model/load.py", line 604, in load_internal
    export_dir)
  File "python3.6/site-packages/tensorflow/python/saved_model/load.py", line 116, in __init__
    meta_graph.graph_def.library))
  File "python3.6/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 311, in load_function_def_library
    func_graph = function_def_lib.function_def_to_graph(copy)
  File "python3.6/site-packages/tensorflow/python/framework/function_def_to_graph.py", line 63, in function_def_to_graph
    importer.import_graph_def_for_function(graph_def, name="")
  File "python3.6/site-packages/tensorflow/python/framework/importer.py", line 412, in import_graph_def_for_function
    graph_def, validate_colocation_constraints=False, name=name)
  File "python3.6/site-packages/tensorflow/python/framework/importer.py", line 501, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: The inner -2 dimensions of input.shape=[] must match the inner 1 dimensions of updates.shape=[?,1]: Shapes must be equal rank, but are 0 and 1 for '{{node agent/ResourceScatterNdUpdate}} = ResourceScatterNdUpdate[T=DT_BOOL, Tindices=DT_INT64, _output_shapes=[], use_locking=true](agent_resourcescatterndupdate_ref:0, agent/stack_1:0, args_0:0)' with input shapes: [], [?,2], [?,1].
```

**Comment by ravikyram** [comment]
@AlexKuhnle 

Request you to share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!
