### ISSUE TITLE
TF Unit test flaky in haswell/broadwell machines

### ISSUE THREAD

**Issue by jojivk73** [tensorflow/tensorflow#40720]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.2
- Python version:  3.7
- Bazel version (if compiling from source):3.1
- GCC/Compiler version (if compiling from source):7.5
- CUDA/cuDNN version:
- GPU model and memory:
-CPUModel : Haswell/Broadwell

**Describe the current behavior**
   _**//tensorflow/core/kernels:sparse_matmul_op_test**_ 
     Is flaky on haswell/broadwell machines (-march=haswell -mtue=broadwell) and fails often (not always). The failure is in vectorization when setting the parameters for the op.

**Describe the expected behavior**

**Standalone code to reproduce the issue**
      //tensorflow/core/kernels:sparse_matmul_op_test
  build and run on broadwell platform. 

**Other info / logs** I

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Comment by sushreebarsa** [comment]
@jojivk73  Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!
