### ISSUE TITLE
compilation of rule '//tensorflow/python:bfloat16_lib' failed when building TF2.2 from source

### ISSUE THREAD

**Issue by xlnwel** [tensorflow/tensorflow#40742]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): r2.2.0
- Python version: 3.7.7
- Bazel version (if compiling from source):2.0.0
- GCC/Compiler version (if compiling from source):7.5.0
- CUDA/cuDNN version:10.2
- GPU model and memory: 12

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

I receive an error when build TF2.2 from source. Here's the error message:

> tensorflow/python/lib/core/bfloat16.cc:610:60: note:   no known conversion for argument 2 from ‘<unresolved overloaded function type>’ to ‘PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}’
> tensorflow/python/lib/core/bfloat16.cc:655:36: error: no match for call to ‘(tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>) (const char [14], <unresolved overloaded function type>, const std::array<int, 3>&)’
>                        compare_types)) {
>                                     ^
> tensorflow/python/lib/core/bfloat16.cc:610:60: note: candidate: tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>
>                              const std::array<int, 3>& types) {
>                                                             ^
> tensorflow/python/lib/core/bfloat16.cc:610:60: note:   no known conversion for argument 2 from ‘<unresolved overloaded function type>’ to ‘PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}’
> Target //tensorflow/tools/pip_package:build_pip_package failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> ERROR: /home/aptx4869/github/tensorflow/tensorflow/python/tools/BUILD:281:1 C++ compilation of rule '//tensorflow/python:bfloat16_lib' failed (Exit 1)
> INFO: Elapsed time: 20.016s, Critical Path: 7.56s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully

I've taken advice from [this issue](https://github.com/tensorflow/tensorflow/issues/40688?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDk0OTk2NDQwMToxMDE4NDE1Mw%3D%3D#issuecomment-648539630) to downgrade numpy to 1.18.5 but it does not work for me.

**Comment by jvishnuvardhan** [comment]
@xlnwel Can you please try again. I think the above PR might have resolved your issue. Thanks!

**Comment by xlnwel** [comment]
Thanks. I finally got it worked

**Comment by cmzapa** [comment]
Commenting to save people my head ache, remember to run `hazel clean` after downgrading numpy

**Comment by Wzlclhy** [comment]
> 
> 
> Thanks. I finally got it worked

Could you please tell the method you solved the problem?

**Comment by Wzlclhy** [comment]
> after downgrading numpy

Sorry..i don't know how to use 'hazel clean'

**Comment by p-sh07** [comment]
> Commenting to save people my head ache, remember to run `hazel clean` after downgrading numpy

Thank you so much!! Indeed saved me a lot of headache =)! Came here from https://github.com/tensorflow/tensorflow/issues/40688, also had the bfloat16 issue after 20 mins of compiling ... !

**Comment by p-sh07** [comment]
> > after downgrading numpy
> 
> Sorry..i don't know how to use 'hazel clean'

He means run `basel clean` after downgrading numpy, this restarts the compilation and bfloat16 issue is fixed. I downgraded to numpy==1.18.5

**Comment by yiakwy-xpu-ml-framework-team** [comment]
Note @p-sh07 for python 3.10 , tensorflow 1.15 users, you have to apply the diff#1 from tensorflow 1.15 side to reflect change of Numpy ABI since numpy <1.19.0 cannot compile directly without apply diff#2 from numpy side:

- diff#1 (for python 3.10, tf 1.15.0 users: https://github.com/tensorflow/tensorflow/commit/75ea0b31477d6ba9e990e296bbbd8ca4e7eebadf
- diff#2 (for tf 2.x users) : https://github.com/numpy/numpy/commit/ad2a73c18dcff95d844c382c94ab7f73b5571cf3
