### ISSUE TITLE
Tensorflow-rocm GPU useage confirmation

### ISSUE THREAD

**Issue by Chr0m0s0m3s** [tensorflow/tensorflow#40751]
**System information**
- OS Platform and Distribution : Linux Ubuntu 20.04 LTS
- TensorFlow installed from (source or binary): tensorflow-rocm
- TensorFlow version: 2.2.0
- Python version: 3.8
- Installed using virtualenv? pip? conda?: pip3
- Rocm version: 3.5.1
- GPU model and memory: RX580

**The problem**
while importing the tensorflow api module there is no issue but while im trying to confirm that its running on gpu
with the following code : ```print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))```
the issue pops up

**logs**
```
2020-06-24 14:42:51.220457: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libhip_hcc.so'; dlerror: libhip_hcc.so: cannot open shared object file: No such file or directory
2020-06-24 14:42:51.220491: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Failed precondition: Could not load dynamic library 'libhip_hcc.so'; dlerror: libhip_hcc.so: cannot open shared object file: No such file or directory
Aborted (core dumped)
```
**Additional Info**
I have setup the tensorflow-rocm with the following commands :
```
sudo apt install libnuma-dev
wget -q -O - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add -
echo 'deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main' | sudo tee /etc/apt/sources.list.d/rocm.list
sudo apt install rocm-dkms
sudo usermod -a -G video $LOGNAME
echo 'export PATH=$PATH:/opt/rocm/bin:/opt/rocm/profiler/bin:/opt/rocm/opencl/bin' | sudo tee -a /etc/profile.d/rocm.sh
sudo apt install rocm-libs miopen-hip rccl
pip3 install tensorflow-rocm
```

**Comment by vuquocan1987** [comment]
I have error

**Comment by vuquocan1987** [comment]
Hi, I did solved it (some other guy tell me) but running into another problem: 

https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/1022
basically you have to run:
a) cp /opt/rocm/hip/lib/libamdhip64.so.3.5.30501 /usr/lib/libhip_hcc.so
b) ldconfig (the first letter is L - this is used for updating the links/cache of shared libraries, you can run it from anywhere)

But I got another problem: 
:
2020-06-24 19:13:58.587688: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-06-24 19:13:58.587693: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-06-24 19:13:58.587837: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7399 MB memory) -> physical GPU (device: 0, name: Ellesmere [Radeon RX 470/480/570/570X/580/580X], pci bus id: 0000:01:00.0)
Segmentation fault (core dumped)

please try it and tell me you have this same problem.

**Comment by Chr0m0s0m3s** [comment]
and here i got the following error after following the above steps :
```2020-06-24 18:12:21.057717: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libhip_hcc.so
2020-06-24 18:12:21.057866: E tensorflow/stream_executor/rocm/rocm_driver.cc:975] could not retrieve ROCM device count: HIP_ERROR_NoDevice
2020-06-24 18:12:21.057886: E tensorflow/stream_executor/rocm/rocm_driver.cc:975] could not retrieve ROCM device count: HIP_ERROR_NoDevice
Num GPUs Available:  0```

**Comment by vuquocan1987** [comment]
Hmm, for your information I after the steps above could print out number of GPUs device ( which is 1 on my computer ). But I couldn't do any operation GPUS related on tensorflow. Which lead to error I mentioned.

Did you tried rocm-smi?

**Comment by Chr0m0s0m3s** [comment]
rocm-smi not detecting GPU too 
logs :
```========================ROCm System Management Interface========================
================================================================================
GPU  Temp   AvgPwr   SCLK    MCLK    Fan     Perf  PwrCap  VRAM%  GPU%  
0    37.0c  30.047W  600Mhz  300Mhz  42.75%  auto  145.0W    2%   0%    
================================================================================
==============================End of ROCm SMI Log ==============================
```

**Comment by vuquocan1987** [comment]
It look like your rocm-smi working fine ( 0 is the index of the device ). So indeed rocm detected your GPU. I don't know ... Please keep updating as we have same set up.

**Comment by Chr0m0s0m3s** [comment]
did you try the docker installation tho? worked fine for me tbh 
link : https://hub.docker.com/r/rocm/tensorflow
but i need the base installation for my work now and the issues are popping up

**Comment by Chr0m0s0m3s** [comment]
> It look like your rocm-smi working fine ( 0 is the index of the device ). So indeed rocm detected your GPU. I don't know ... Please keep updating as we have same set up.

i fixed the problem by adding my user to the rendergroup thanks alot

**Comment by Chr0m0s0m3s** [comment]
> Hi, I did solved it (some other guy tell me) but running into another problem:
> 
> [ROCmSoftwarePlatform#1022](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/1022)
> basically you have to run:
> a) cp /opt/rocm/hip/lib/libamdhip64.so.3.5.30501 /usr/lib/libhip_hcc.so
> b) ldconfig (the first letter is L - this is used for updating the links/cache of shared libraries, you can run it from anywhere)
> 
> But I got another problem:
> :
> 2020-06-24 19:13:58.587688: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108] 0
> 2020-06-24 19:13:58.587693: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0: N
> 2020-06-24 19:13:58.587837: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7399 MB memory) -> physical GPU (device: 0, name: Ellesmere [Radeon RX 470/480/570/570X/580/580X], pci bus id: 0000:01:00.0)
> Segmentation fault (core dumped)
> 
> please try it and tell me you have this same problem.

i have the same error as well while tryna run the code

**Comment by jnairfamily** [comment]
> Hi, I did solved it (some other guy tell me) but running into another problem:
> 
> [ROCmSoftwarePlatform#1022](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/1022)
> basically you have to run:
> a) cp /opt/rocm/hip/lib/libamdhip64.so.3.5.30501 /usr/lib/libhip_hcc.so
> b) ldconfig (the first letter is L - this is used for updating the links/cache of shared libraries, you can run it from anywhere)
> 
> But I got another problem:
> :
> 2020-06-24 19:13:58.587688: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108] 0
> 2020-06-24 19:13:58.587693: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0: N
> 2020-06-24 19:13:58.587837: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7399 MB memory) -> physical GPU (device: 0, name: Ellesmere [Radeon RX 470/480/570/570X/580/580X], pci bus id: 0000:01:00.0)
> Segmentation fault (core dumped)
> 
> please try it and tell me you have this same problem.

Thanks, This is working for me (with vega 56 GPU, everything else is same as the first post)

**Comment by vuquocan1987** [comment]
> > Hi, I did solved it (some other guy tell me) but running into another problem:
> > [ROCmSoftwarePlatform#1022](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/1022)
> > basically you have to run:
> > a) cp /opt/rocm/hip/lib/libamdhip64.so.3.5.30501 /usr/lib/libhip_hcc.so
> > b) ldconfig (the first letter is L - this is used for updating the links/cache of shared libraries, you can run it from anywhere)
> > But I got another problem:
> > :
> > 2020-06-24 19:13:58.587688: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108] 0
> > 2020-06-24 19:13:58.587693: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0: N
> > 2020-06-24 19:13:58.587837: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7399 MB memory) -> physical GPU (device: 0, name: Ellesmere [Radeon RX 470/480/570/570X/580/580X], pci bus id: 0000:01:00.0)
> > Segmentation fault (core dumped)
> > please try it and tell me you have this same problem.
> 
> i have the same error as well while tryna run the code

I fixed it by reinstall every thing AND DID NOT do `cp /opt/rocm/hip/lib/libamdhip64.so.3.5.30501 /usr/lib/libhip_hcc.so` instead, I tried: `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rocm/hip/lib` as in:
https://github.com/RadeonOpenCompute/ROCm/issues/1163#issuecomment-648910306

Please try it and tell me if that solved yours problem.
Sigh ... finally, I can get some sleep.

**Comment by Chr0m0s0m3s** [comment]
solves the issue for one terminal not fully

**Comment by Chr0m0s0m3s** [comment]
Ok issue solved fully type these in the terminal
```
echo 'export LD_LIBRARY_PATH=/opt/rocm/lib:$LD_LIBRARY_PATH' >> $HOME/.bashrc source $HOME/.bashrc sudo reboot
```

Thanks everyone closing the issue
