### ISSUE TITLE
model.fit taking 30 minutes to set-up but only 3ms to run an epoch

### ISSUE THREAD

**Issue by MarinoBrundu** [tensorflow/tensorflow#40754]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
-Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
-OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux ubuntu 20.04 LTS
-Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
-TensorFlow installed from (source or binary): via pip3
-TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0
-Python version: 3.8.2
-Bazel version (if compiling from source): N/A
-GCC/Compiler version (if compiling from source): N/A
-CUDA/cuDNN version: 10.1
-GPU model and memory: GeForce RTX 2070 8gb

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

When running model.fit it takes around 30 minutes each epoch before the progress bar shows up. the actual step then takes around 3ms to complete. is there any way to speed this up? and what is happening during these 30 minutes? I'm using Jupyter Notebook to run the code.

**Describe the expected behavior**

Not letting model.fit take 30 minutes per epoch.

**Standalone code to reproduce the issue**
```
import matplotlib.pyplot as plt
 import numpy as np
 import pandas as pd
 from sklearn.model_selection import train_test_split

 import tensorflow as tf

 from tensorflow.keras import layers

 from tensorflow.keras import Model
 from tensorflow.keras.models import *
 from tensorflow.keras.layers import *
 from tensorflow.keras.callbacks import *
 from tensorflow.keras.optimizers import *
 from tensorflow.keras.utils import to_categorical, plot_model
 dataset_controller = pd.read_csv("data_template_braincap.csv")
 randomint = round((len(dataset_controller.index) * 0.8))
 randomint2 = round(len(dataset_controller.index) - randomint)
 train=dataset_controller.head(randomint)
 test=dataset_controller.tail(randomint2)
 X_train = train.drop(['actual time', 'timestamp bci', 'timestamp controller', 'left stick x:', 'left stick y:', 'right stick x:', 'right stick y:', 'a:', 'b:', 'x:', 'y:', 'right trigger:'], axis = 1)
 y_train = train['a:']
 X_test = test.drop(['actual time', 'timestamp bci', 'timestamp controller', 'left stick x:', 'left stick y:', 'right stick x:', 'right stick y:', 'a:', 'b:', 'x:', 'y:', 'right trigger:'], axis = 1)
 y_test = test['a:']


 y_train = y_train.head(len(y_train)-256)

 y_train = y_train.values.reshape((1, len(y_train), 1))
 X_train = X_train.shift(periods=-256, fill_value=0)
 X_train = X_train.head(len(X_train)-256)
 X_train = X_train.values.reshape((1, len(X_train), 19))
 model = tf.keras.Sequential()
 model.add((layers.SimpleRNN(64, input_shape=(X_train.shape[1], X_train.shape[2]), return_sequences=False)))
 model.add(Dropout(0.3))
 model.add(Dense(1024))
 model.add(Dense(1024))
 model.add(Dense(1024))
 model.add(Dense(1))
 model.compile(optimizer="adam", loss="mean_squared_error")
 model.summary()
 model.fit(X_train, y_train, epochs=500, batch_size=2048)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

the dataset has 31 columns and 339972 rows. the first 5 rows look like this:
```
0,44295.68,15337.95,-187500.02,-187500.02,-56777.86,-41605.74,-73884.49,-78516.45,-187500.02,6256.72,-187500.02,-64932.48,-53366.2,-59987.21,-187500.02,-24877.74,0.0,0.0,0.0,14:08:15.156,1591358895156,1591358895164,0,12,0,0,0,0,0,0,0
1,43882.2,14582.72,-187500.02,-187500.02,-57811.38,-43702.24,-74505.63,-79345.52,-187500.02,-17205.57,-187500.02,-62077.83,-52917.82,-57371.2,-187500.02,-32231.13,0.02,0.972,0.168,14:08:15.214,1591358895214,1591358895172,0,12,0,0,0,0,0,0,0
2,44356.3,15663.66,-187500.02,-187500.02,-55410.51,-41974.36,-72097.02,-76903.34,-187500.02,-2991.58,-187500.02,-63242.92,-52042.46,-58320.08,-187500.02,-29449.72,0.0,0.0,0.0,14:08:15.214,1591358895214,1591358895180,0,12,0,0,0,0,0,0,0
3,43967.04,14665.94,-187500.02,-187500.02,-58229.8,-42705.06,-75319.74,-80001.02,-187500.02,-3170.95,-187500.02,-64025.45,-53815.11,-59228.72,-187500.02,-26920.17,0.0,0.0,0.0,14:08:15.214,1591358895214,1591358895188,0,12,0,0,0,0,0,0,0
4,44212.8,15311.93,-187500.02,-187500.02,-55950.53,-43095.84,-72422.33,-77356.32,-187500.02,-15505.09,-187500.02,-61992.98,-51984.52,-57185.35,-187500.02,-33186.15,0.0,0.0,0.0,14:08:15.214,1591358895214,1591358895196,0,9,0,0,0,0,0,0,0 
```
Keras output during model.fit:
```
Epoch 1/500
1/1 [==============================] - 0s 3ms/step - loss: 0.3895
Epoch 2/500
1/1 [==============================] - 0s 4ms/step - loss: 232.1620
Epoch 3/500
1/1 [==============================] - 0s 4ms/step - loss: 20.5877
Epoch 4/500
1/1 [==============================] - 0s 3ms/step - loss: 51.7856
```

**Comment by amahendrakar** [comment]
@MarinoBrundu,
Could you please share the `data_template_braincap.csv` file used in the code, so that we can reproduce the issue on our end. Thanks!

**Comment by MarinoBrundu** [comment]
I can't attach the file because the file type is not supported, but I uploaded it to google drive and you can download it from there.

https://drive.google.com/file/d/1Kah4XS94L_loKs0XExq6ecpkGIG_ti1t/view?usp=sharing

**Comment by yixingfu** [comment]
@MarinoBrundu Your data is one big sequence so each epoch only have one big step. That is why epoch time is very short relative to the waiting time, and make batch_size senseless. 
I am not sure what you want, but it seems like you may want to break the sequence into small sequences in some way.

**Comment by MarinoBrundu** [comment]
@yixingfu that fixed the problem, thank you.
