### ISSUE TITLE
Memory leak in macOS Catalina 10.15

### ISSUE THREAD

**Issue by SawyerGao92** [tensorflow/tensorflow#40757]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  macOS Catalina 10.15.5
- TensorFlow installed from (source or binary): from conda install
- TensorFlow version (use command below):  1.15
- Python version: 3.7.6

**Describe the current behavior**

When I run a tensorflow code on my Macbook, the memory usage keeps rising. Then I tried the following::
-I simplified the code to the following form and still can reproduce the problem.
-I found that this problem occurs only when running train_op. So I attempt to change the "sigmoid_cross_entropy_with_logits" to "softmax_cross_entropy_with_logits", the memory leak disappeared. I don’t know why.
-I ran this code in the Windows 10 and docker. And the memory leak also disappeared.

The activity monitor shows that the memory usage, and it continues to grow (most of them are swap).
![123](https://user-images.githubusercontent.com/12993399/85534520-fc4a1900-b643-11ea-8968-5d5242e83cc2.png)

**Standalone code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf
from tqdm import tqdm

data_x = np.array([[72, 20], [16, 20]], dtype=np.int32)
data_y = np.array([[0], [1]])

x = tf.placeholder(tf.float32, [2, 2], name='x')
y = tf.placeholder(tf.float32, [2, 1], name='y')

outputs = tf.layers.dense(x, 1, use_bias=True)

# loss = tf.reduce_mean(tf.pow(y - outputs, 2))
loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels=y, logits=outputs))    #softmax_cross_entropy_with_logits
train_op = tf.train.AdamOptimizer(0.001).minimize(loss)
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    for i in tqdm(range(10000000)):
        sess.run([loss, train_op], feed_dict={x: data_x, y: data_y})
```

**Comment by ymodak** [comment]
@SawyerGao92 Does this happen with TF 2.2 version as well?
@Gariane Can you please provide a minimal code repro ?
