### ISSUE TITLE
Error while using makefile

### ISSUE THREAD

**Issue by AlperenAydin** [tensorflow/tensorflow#4075]
Hello. I  tried to us TF using the method described [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile)  on Linux. 

After installin protobuf ( as instructed),  I get these two errors after using the last command ( make -f tensorflow/contrib/makefile/Makefile) 

>tensorflow/core/util/example_proto_fast_parsing.cc:177:38: error: invalid conversion from ‘tensorflow::uint64* {aka long long unsigned int*}’ to ‘google::protobuf::uint64* {aka long unsigned int*}’ [-fpermissive]
           if (!stream.ReadVarint64(&n)) return false;
and
> tensorflow/core/util/example_proto_fast_parsing.cc:186:38: error: invalid conversion from ‘tensorflow::uint64* {aka long long unsigned int*}’ to ‘google::protobuf::uint64* {aka long unsigned int*}’ [-fpermissive]
           if (!stream.ReadVarint64(&n)) return false;

BTW: the commit hash I am using is: f9ae4fe749c5d7dbf1851cffc94730086e588c35
and CUDA isn't installed.

**Comment by petewarden** [comment]
Sorry you're hitting problems! Could you give me some more details on the Linux version you're using?

The issue looks like it's a mismatch between the protobuf version TensorFlow's being compiled with, and the one you have installed on the system.

**Comment by AlperenAydin** [comment]
I am currently on a ubuntu 16.04.

**Comment by petewarden** [comment]
I've updated the makefile to include a build_all_linux.sh script that compiles the protobuf locally, rather than using the system-installed version. I believe this should fix this problem you're hitting, can you give it a try and let me know?

**Comment by asimshankar** [comment]
Closing this out due to inactivity. @AlperenAydin : feel free to reopen if your issue hasn't been resolved with Pete's changes above.
