### ISSUE TITLE
Gradients error when using while_loop: "ValueError: None values not supported"

### ISSUE THREAD

**Issue by liorfritz** [tensorflow/tensorflow#4076]
Working on Tensorflow version 0.10, I am getting the following error when using `tf.gradients`:
```
.../python2.7/site-packages/tensorflow/python/ops/gradients.py", line 478, in gradients
...
.../python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 346, in make_tensor_proto
    raise ValueError("None values not supported.")
```

The error occurs due to the use of the function `tf.while_loop` . When I turn off its use, the gradients are calculated with no error.

A similar issue was related to in https://github.com/tensorflow/tensorflow/issues/783, but I can't fix the error using the suggested solutions.

**Comment by girving** [comment]
We'll need more information.  What are you doing?
