### ISSUE TITLE
tfcompile  --target_triple="armv7em-none-eabi" calling wrong libraries

### ISSUE THREAD

**Issue by DroneMesh** [tensorflow/tensorflow#40762]
I found a bug inside tfcompile especially if your compiling for ARM embedded devices the  --target_triple="armv7em-none-eabi" is calling incorrect functions when compiling. This should be compatible with arm-none-eabi-gcc libraries and one example is libgcc.a in the none-eabi version it does not have a function called __multi3 however in every other version such as gnu and linux its availble. So when tfcompile generates the files the compiler can not find the function __multi3.

Is there a possible work around to this?

**System information**
- OS Platform and Distribution ( Linux Ubuntu 18):
- TensorFlow installed from (source):
- TensorFlow version (1.5 > ):
- Python version: 3.6
- Bazel version (0.10 > ):
- GCC/Compiler version (if compiling from source):

**Comment by Saduf2019** [comment]
@DroneMesh 
Please update the tensor flow version and details on platform, in case you encountered the issue while running code hsare a simple indented stand alone code such that we can replicate the issue faced or colab gist with code and error for su to analyse.

**Comment by DroneMesh** [comment]
@Saduf2019 I am unable to update due to the nature of the project. The tfcompile is thinking I have long long int in my graphs when i don't. The project is very large and i will not be able to create a collab i wish a could. 

is there a way to specify and limit the int types?

**Comment by DroneMesh** [comment]
Solved it its a bug with LLVM
