### ISSUE TITLE
ways to import keras model without tensorflow

### ISSUE THREAD

**Issue by Lucysmith8** [tensorflow/tensorflow#40772]
**System information**
- Windows 10
- TensorFlow installed from pip
- TensorFlow 2.2
- Python 3.7
- Installed using pip

Is it possible to import keras .h5 model without tensorflow. I'm having trouble using tensorflow with my app. I have an error message. 

I installed tfdploy but I don't know how to use it. Is there a lighter version of tensorflow for deployment? Or can we use modules like pytorch to import a .h5 keras model?

I need two tensorflow modules:

    from tensorflow.keras.models import load_model
    from tensorflow.keras.preprocessing import image

When I import these two modules with my application, I get the following error:
[![error][1]][1]

  [1]: https://i.stack.imgur.com/nFgUf.jpg

**Comment by Saduf2019** [comment]
@Lucysmith8 
Please refer to these links with similar error, and let us know if it helps:
#33730 [link](https://github.com/pyinstaller/pyinstaller/issues/4200) [link1](https://webspark.hk/blog/python/pyinstaller-expected-str-error-fix/)

**Comment by Lucysmith8** [comment]
It is not the same problem. They use pyinstaller, I use cx_freeze @Saduf2019

**Comment by Lucysmith8** [comment]
He found the solution. But instead of sharing, he closed his question and he didn't answer anyone. https://github.com/anthony-tuininga/cx_Freeze/issues/514

**Comment by Saduf2019** [comment]
@Lucysmith8 
There is duplicate for this issue, please close current issue as its already traced.
duplicates:
#40485  #40458
