### ISSUE TITLE
Tensorflow 2 - oneDNN 1.x build fails searching for i_malloc.h, mkl_cblas.h on non-x86 machines.

### ISSUE THREAD

**Issue by cfRod** [tensorflow/tensorflow#40771]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
NAME="CentOS Linux"
VERSION="8 (Core)"

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version: master & 2.2.0
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): GCC 8.3.1
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
I am building Tensorflow with oneDNN 1.4.0 on an Aarch64 machine, which causes issues when searching for MKL-ML header files (e.g. i_malloc.h). 

Example log 1:

``` 
/home/../tensorflow-nb/packages/tensorflow/tensorflow/core/common_runtime/BUILD:1018:1: C++ compilation of rule '//tensorflow/core/common_runtime:mkl_cpu_allocator' failed (Exit 1)
In file included from tensorflow/core/common_runtime/mkl_cpu_allocator.cc:18:
./tensorflow/core/common_runtime/mkl_cpu_allocator.h:33:10: fatal error: i_malloc.h: No such file or directory
 #include "i_malloc.h"
 ^~~~~~~~~~~~
compilation terminated.
```
Example log 2:
```
ERROR: /home/.../tensorflow-nb/packages/tensorflow/tensorflow/core/kernels/BUILD:4109:1: C++ compilation of rule '//tensorflow/core/kernels:mkl_batch_matmul_op' failed (Exit 1)
tensorflow/core/kernels/mkl_batch_matmul_op.cc:31:10: fatal error: mkl_cblas.h: No such file or directory
 #include "mkl_cblas.h"
          ^~~~~~~~~~~~~
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: /home/.../tensorflow-nb/packages/tensorflow/tensorflow/lite/toco/python/BUILD:84:1 C++ compilation of rule '//tensorflow/core/kernels:mkl_batch_matmul_op' failed (Exit 1) 
```

In previous Tensorflow versions  (1.x), for example, when building with the older mkldnn library 0.21.x, these header files were removed with mkldnn ifdefs (INTEL_MKL_DNN_ONLY):
https://github.com/tensorflow/tensorflow/blob/590d6eef7e91a6a7392c8ffffb7b58f2e0c8bc6b/tensorflow/core/common_runtime/mkl_cpu_allocator.h#L32

 while these ifdefs are not activated when building with the new oneDNN 1.x (with for e.g -DENABLE_MKLDNN_V1)

There are several sources that have this issue (this is from a successful x86 build):
```
./tensorflow/core/kernels/_objs/mkl_transpose_op/mkl_transpose_op.pic.d:3: external/mkl_linux/include/mkl_trans.h \
./tensorflow/core/kernels/_objs/mkl_transpose_op/mkl_transpose_op.pic.d:5: external/mkl_linux/include/mkl_types.h \
./tensorflow/core/kernels/_objs/mkl_batch_matmul_op/mkl_batch_matmul_op.pic.d:51: external/mkl_linux/include/mkl_cblas.h \
./tensorflow/core/kernels/_objs/mkl_batch_matmul_op/mkl_batch_matmul_op.pic.d:52: external/mkl_linux/include/mkl_types.h \
./tensorflow/core/common_runtime/_objs/mkl_cpu_allocator/mkl_cpu_allocator.pic.d:623: external/mkl_linux/include/i_malloc.h
./tensorflow/core/common_runtime/_objs/threadpool_device/threadpool_device.pic.d:718: tensorflow/core/lib/core/bits.h external/mkl_linux/include/i_malloc.h \ 
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
bazel build --config=v2 --config=mkl  \
    --copt="-mtune=native" --copt="-march=armv8-a" --copt="-O3" --copt="-fopenmp" \
    --cxxopt="-mtune=native" --cxxopt="-march=armv8-a" --cxxopt="-O3" --cxxopt="-fopenmp" \
    --linkopt="-lm" --linkopt="-fopenmp" \
    --config=noaws  --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" \
    //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by agramesh1** [comment]
Adding @nSircombe  for support of oneDNN on ARM.

**Comment by nSircombe** [comment]
Thanks for the heads-up @agramesh1, as it happens I'm actually working with @cfRod!

At the moment, oneDNN v1.4+ builds on AArch64 'out of the box' and we've been able to build TensorFlow with oneDNN v0.20.x. But, as @cfRod details, we have some problems with building TensorFlow with oneDNN v1.x. - these don't appear to be an issue with oneDNN. It looks as if there are two issues which balance each other out in the case of an x86 build:
1. the ifdefs for a v1.x build appear to re-include headers omitted from v0.x builds.
2. TensorFlow downloads an MKL-ML tarball (https://github.com/intel/mkl-dnn/releases/download/v0.21/mklml_lnx_2019.0.5.20190502.tgz) which includes those headers (as well as an MKL-ML binary). This doesn't appears (now) to be necessary, and possibly unintentional?
This download does not happen for an AArch64 build, hence the missing header files.

**Comment by agramesh1** [comment]
@nSircombe yes, for MKL DNN 0.2.x version had defines that will allow you to compile with only opensource components.
With the move to oneDNN 1.4x in TF2.2 that broke and we haven't fixed it as yet.  You should be able to remove all references of mkl in the allocator code to get it compile. We are working on cleaning up the code and remove the blob dependencies when compiled with oneDNN 1.4.

**Comment by cfRod** [comment]
Submitted PR: https://github.com/tensorflow/tensorflow/pull/41232

**Comment by agramesh1** [comment]
> Submitted PR: #41232

@cfRod Thanks, I will review the code.
