### ISSUE TITLE
tf.image.random_flip_left_right should be also to apply to a list of tsor

### ISSUE THREAD

**Issue by ek9852** [tensorflow/tensorflow#40787]
**System information**
- TensorFlow version (you are using): 2.2.0
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.**
Add support to randomly flip image for a list o tensor images instead a single tensor. tf.image.random_flip_left_right, random_flip_top_bottom..
The problem is that for segmentation training, we wants to use data augment to randomly flip the input left or right. But there is no way the flip the ground true (the labels) together. 
Since  we don't know which direction the random flip api is flipping to. Batching make it worse since each image will flip randomly. We need to  modify the api to take  either a single tensor or a list of tensors and flip the images together in the same direction. which is required  for  image segmentation.

**Will this change the current api? How?**
No. We can detect the input argument is a list or single tensor

**Who will benefit with this feature?**

**Any Other info.**

**Comment by ravikyram** [comment]
@ek9852 
Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!

**Comment by ek9852** [comment]
@ravikyram  I already state the use case.
I want to train a network  with image segmentation.
How can I randomly flip input image and  ground true label (which is another image) to the same direction randomly for data augmentation ?

**Comment by sachinprasadhs** [comment]
You could feed the multiple images for `random_flip_left_right`, see the example [here](https://www.tensorflow.org/api_docs/python/tf/image/random_flip_left_right#example_usage). Thanks!
