### ISSUE TITLE
the link to stable version of this codelab is broken 

### ISSUE THREAD

**Issue by navczydev** [tensorflow/tensorflow#40785]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/MyMethod

### Clear description

For example, why should someone use this method? How is it useful?

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example?

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by Saduf2019** [comment]
@navczydev 
Please share the link mentioned in the issue.

**Comment by navczydev** [comment]
Here is the link : https://developer.android.com/codelabs/recognize-flowers-with-tensorflow-on-android/index.html?index=..%2F..index#0
and it's. in this codelab  👇
https://developer.android.com/codelabs/recognize-flowers-with-tensorflow-on-android-beta#0

**Comment by ymodak** [comment]
Can you please point the page where this is hosted?
We have `Recognize flowers with TensorFlow` codelab tutorial on TF website on this [web page](https://www.tensorflow.org/lite/models/image_classification/overview)

**Comment by navczydev** [comment]
If you go to this link
https://developer.android.com/codelabs/recognize-flowers-with-tensorflow-on-android-beta#0
and there is a link to stable version of this codelab which is broken

**Comment by ymodak** [comment]
Do you mean `Colab` from this web page?

<img width="1371" alt="Screen Shot 2020-07-04 at 11 18 16 AM" src="https://user-images.githubusercontent.com/42785357/86518709-39eb3680-bde8-11ea-8b32-e8626d9e27b1.png">

Clicking on `Colab` takes you to https://colab.sandbox.google.com/github/tensorflow/examples/blob/master/lite/codelabs/flower_classification/ml/Flower_Classification_with_TFLite_Model_Maker.ipynb correctly.
