### ISSUE TITLE
Jetson Nano build fails with missing "cudnn_version" string (default=7)

### ISSUE THREAD

**Issue by TheMindVirus** [tensorflow/tensorflow#40784]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Ubuntu 16.04 for Nvidia Jetson Nano (Tegra ARM64)
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.1.1
- Python version: 2.7.17 and 3.6.9 (issue occurs with both)
- Installed using virtualenv? pip? conda?: no
- Bazel version (if compiling from source): 0.29.1
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: CUDA 10.2 cuDNN 8.0.0
- GPU model and memory: Nvidia Maxwell 4GB LPDDR4

**Describe the problem**
Build halts due to missing tuple entry (instead of blank string) for option 9: cudnn_version
The default as set in "configure.py" is cuDNN 7, but this is not reflected in the dictionary.
I have cuDNN version 8 installed but it has not been detected by the build script.
Everything else has been detected fine before this point (line 1318 in "configure.py").

**Provide the exact sequence of commands / steps that you executed before running into the problem**
"sudo ./configure" and say "Y/y" all dependencies (including python, computecpp, CUDA etc.)

**Any other info / logs**
![tensorflow2-debug](https://user-images.githubusercontent.com/8195854/85642678-16a6e580-b68a-11ea-8c51-7c6282261786.png)

**Comment by ravikyram** [comment]
@TheMindVirus 

Can you try with [tested build configuration](https://www.tensorflow.org/install/source#gpu) for TF 2.1 and see whether the problem still persists?.Thanks!

**Comment by TheMindVirus** [comment]
Even if I try one of the default configurations I’m not likely to get the same performance out of the board. The library versions have been compiled especially to support this board and others. Changing the environment will likely cause damage to my system and other applications.

**Comment by TheMindVirus** [comment]
I am proceeding to following the build instructions here: https://www.tensorflow.org/install/source_rpi
These instructions are for the Raspberry Pi which the Jetson Nano is based around and is also ARM64.
I will let you know if this builds correctly. It is currently taking a long time to build numpy on 1 core.

**Comment by TheMindVirus** [comment]
When trying to build from the docker image I get errors while building SciPy such as the following:
https://github.com/scipy/scipy/issues/9005
This is even the case on a Raspberry Pi 4. Any fixes have to be made to the docker container.
The system has the libraries required but they are not being used.

**Comment by mohantym** [comment]
Hi @TheMindVirus!
We are checking to see whether you still need help in this issue . Have you checked this [thread](https://towardsdatascience.com/getting-started-with-nvidia-jetson-nano-and-installing-tensorflow-gpu-ad4a3da8ed26) yet? Thanks!

**Comment by TheMindVirus** [comment]
A few 404 Errors while building from source with bazel and CUDA support:
https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/bcad20bc6591c8b503923402038c735a77373f99.tar.gz
http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/03b3c4c9baa9b99b2073a4f342b810e8843e43c2.tar.gz
https://storage.googleapis.com/mirror.tensorflow.org/github.com/NVIDIA/cudnn-frontend/archive/73210a930333eaf66b42b01693bce7b70719c354.zip
but it is currently still building. I will give you an update when it finishes.

**Comment by TheMindVirus** [comment]
The build has failed with more 404 Errors and some Internal Compiler Errors.
There are even more possible combinations than are shown in the documentation you linked, many projects look like version hell at the moment.
![Screenshot from 2021-11-03 16-51-16](https://user-images.githubusercontent.com/8195854/140107898-3e0595c9-7696-4d7b-a6e3-35337464f9c0.png)

**Comment by mohantym** [comment]
Ok @TheMindVirus!  Could you check out this [thread](https://github.com/PINTO0309/Tensorflow-bin#usage) then ?  Thank you!

**Comment by TheMindVirus** [comment]
The Jetson Nano terminal repeatedly grinds to a halt when "Installing backend dependencies" of h5py 3.1.0 required for building for Python.

Python is definitely the way to go for Tensorflow as it's the only thing that ever needs to be built with C in the modern era.

As for the version control, the old habit of removing the old system before replacing it with the new potentially broken one is frowned upon.

There is a prebuilt binary which may work but cannot reliably be rebuilt later with exactly the same source code.

Cutting down on dependency libraries and just using raw Python would make it much simpler to use and also to port to e.g MicroPython and CircuitPython for use in projects.

**Comment by SuryanarayanaY** [comment]
@TheMindVirus ,

We are going through the backlog issues and find this issue.The [Source](https://github.com/tensorflow/build/tree/master/raspberry_pi_builds) you mentioned in one of above [comment](https://github.com/tensorflow/tensorflow/issues/40784#issuecomment-650864028) seems updated though currently there is no support for raspberrry builds. Could you get a chance to test with latest versions as the build configurations changed and old configurations may not work now. Please check and confirm if you have any similar issue with latest versions. If resolved already please feel free to close. 

Thanks!

**Comment by SuryanarayanaY** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks.
