### ISSUE TITLE
ValueError: Shapes (1, 107, 3) and (1, 107, 2) are incompatible

### ISSUE THREAD

**Issue by jianmosier** [tensorflow/tensorflow#40799]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): colab system(Linux version 4.19.104+ )
- TensorFlow installed from (source or binary):colab system installed it 
- TensorFlow version (use command below): tf2.2.0
- Python version: 3.6

**Describe the current behavior**
I am doing some work about tensor train decomposition.
      

- Firstly, I represent a video with tensor. The tensor  dimension is 4 which shape can be see with [ frames, width, heights,channels]. And the tensor shape is [107, 60, 80, 3]. 
- Secondly, I convert the tf tensor to TT tensor via t3f library. 
- Thirdly, I write a Riemann dimension reduction function for the TT tensor. 
- In the end, I reduce  the TT tensor dimension via my function. But the bug come out in the end step.

What I want to say is that the bug didn't come out when I represent another data with tensor which shape is [107, 60, 80, 2] .In that situtation code runned very good.

The exit:

>  ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> ipython-input-34-e5f2500494ee in module()
>       1 log = []
>       2 for i in range(1000):
> ----> 3     F = step()
>       4     if i % 10 == 0:
>       5         print(F)
> 
> 4 frames
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py in assert_is_compatible_with(self, other)
>    1115     """
>    1116     if not self.is_compatible_with(other):
> -> 1117       raise ValueError("Shapes %s and %s are incompatible" % (self, other))
>    1118 
>    1119   def most_specific_compatible_shape(self, other):
> 
> ValueError: Shapes (1, 107, 3) and (1, 107, 2) are incompatible

**Describe the expected behavior**
I expect the video convert to TT tensor can also be reduced dimension by my function been mentioned above without any error just as the shape [107, 60, 80, 2] data.  

**Standalone code to reproduce the issue**
Here is the bug code colab address [Link](https://colab.research.google.com/drive/1Qz-TBBAbnflKioPn-YxxFwl59K3DVlWb?usp=sharing)
Here is the video data address which shape is [107, 60, 80, 3] [Link](https://drive.google.com/file/d/1DVB7ReloEKTkqRBFyj8Uop6_FKf-oBYe/view?usp=sharing)
Here is the another data address which shape is [107, 60, 80, 2] [Link](https://drive.google.com/file/d/1DNS5xCMikgsvye1NZRmdDl3ebcG10ves/view?usp=sharing)

#33948 
@jvishnuvardhan

**Comment by mihaimaruseac** [comment]
Can you provide a **minimal** code to reproduce the issue? The error message makes sense, the last dimension in the shape does not match.

**Comment by jianmosier** [comment]
@mihaimaruseac I have put a minimal code in the [cell](https://colab.research.google.com/drive/1bZiaDNQqpJjMFSQOhpXEgfMy-fwrhC8d?usp=sharing). But I can't provide the input data directly on the cell. If you need reproduce the issue, can download the data from my Google Drive link which is [video data](https://drive.google.com/file/d/1DVB7ReloEKTkqRBFyj8Uop6_FKf-oBYe/view?usp=sharing) and [another data](https://drive.google.com/file/d/1DNS5xCMikgsvye1NZRmdDl3ebcG10ves/view?usp=sharing).

**Comment by jianmosier** [comment]
I know the error message makes sense, but I don't think my two tensor have a different shape. And the another data I have shared can identify the code is well.

**Comment by jianmosier** [comment]
@mihaimaruseac I have find the reason the bug have been caused. I ignored a detail that a rank value need be modify in myself function. What a primary mistake. Thanks for all your patience! And I will close the issue.
