### ISSUE TITLE
Documentation Error: padded_shapes isn't provided in padded_batch method.

### ISSUE THREAD

**Issue by devspartan** [tensorflow/tensorflow#40791]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/tutorials/keras/text_classification

## Description of issue (what needs changing): Under heading 'Prepare the data for training'  in first code snippet 
BUFFER_SIZE = 1000

train_batches = (
    train_data
    .shuffle(BUFFER_SIZE)
    .padded_batch(32))

test_batches = (
    test_data
    .padded_batch(32))

padded_shape isn't provided while it is mandatory i guess. Also when i was following this tutorial i got the error: "TypeError: padded_batch() missing 1 required positional argument: 'padded_shapes'"

So please update the documentation. And also please help me out what should be the padded_shapes for this example. 
I've read the documentation for padded_batch but i still got different errors. Thank You

For example, why should someone use this method? How is it useful?

### Correct links

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by ravikyram** [comment]
@devspartan 

I have tried executing tutorial in colab with TF 2.2 and i am not seeing any issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/e09d0a0e89ac7cbbbbcb2f40472fd88a/untitled67.ipynb)..Can you please help me to understand where exactly you are facing the issue.If possible please share colab link or simple standalone code to reproduce the issue.It helps us in localizing the issue faster.Thanks!

**Comment by devspartan** [comment]
I've been using TF 2.1. After upgraded to TF 2.2 it works fine. Thank you for your quick response
