### ISSUE TITLE
Cannot test op using mutlithreading

### ISSUE THREAD

**Issue by liyinhgqw** [tensorflow/tensorflow#40797]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): master
- Python version: 3.6.0
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): Apple clang version 11.0.0 (clang-1100.0.33.12)
- CUDA/cuDNN version: None
- GPU model and memory: None

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Still only single thread is being used even if I uncommented https://github.com/petewarden/tensorflow_makefile/blob/master/tensorflow/python/kernel_tests/sparse_tensor_dense_matmul_op_test.py#L168.

Here is how I tested it:
VLOG(0) << worker_threads.num_threads;

Output:
1

**Describe the expected behavior**
VLOG(0) << worker_threads.num_threads;

Expected Output:
100

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Uncomment:
https://github.com/petewarden/tensorflow_makefile/blob/master/tensorflow/python/kernel_tests/sparse_tensor_dense_matmul_op_test.py#L168.

bazel build -c opt --copt=-mavx --copt=-msse4.2 --copt=-O3 tensorflow/python/kernel_tests:sparse_tensor_dense_matmul_op_test

./bazel-bin/tensorflow/python/kernel_tests/sparse_tensor_dense_matmul_op_test --benchmarks

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by rohan100jain** [comment]
Could you point to where you added the logging?

**Comment by liyinhgqw** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/sparse_tensor_dense_matmul_op.cc#L47

Added:
```
auto worker_threads = ctx->device()->tensorflow_cpu_worker_threads();
const int num_threads = worker_threads->num_threads;
VLOG(0) << num_threads;
```

**Comment by mohantym** [comment]
Hi @liyinhgqw !
1.x version are not supported any more. I could not find above kernel test .  Have you checked this issue in 2.8 version yet?
Thank you!
