### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by vgkakade** [tensorflow/tensorflow#40802]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:3.6
- Installed using virtualenv? pip? conda?:conda
- GPU model and memory:

**Describe the problem**
  File "main.py", line 6, in <module>
    import tflearn
  File "C:\Users\V\Anaconda3\envs\chatbot\lib\site-packages\tflearn\__init__.py", line 4, in <module>
    from . import config
  File "C:\Users\V\Anaconda3\envs\chatbot\lib\site-packages\tflearn\config.py", line 5, in <module>
    from .variables import variable
  File "C:\Users\V\Anaconda3\envs\chatbot\lib\site-packages\tflearn\variables.py", line 7, in <module>
    from tensorflow.contrib.framework.python.ops import add_arg_scope as contrib_add_arg_scope
ModuleNotFoundError: No module named 'tensorflow.contrib'

**Provide the exact sequence of commands / steps that you executed before running into the problem**
python main.py is only command I ran

full code:
import nltk
from nltk.stem.lancaster import LancasterStemmer  #for stemming
stemmer  = LancasterStemmer()

import numpy
import tflearn
import tensorflow
import random
import json

#file import
with open("intents.json") as file:
	data = json.load(file)
	print(data)

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@vgkakade 

Which version of tensorflow you are using?.
tensorflow.contrib is being removed in version TF 2.x and it works in only TF 1.x. For more info see this https://www.tensorflow.org/guide/migrate#a_note_on_slim_contriblayers
Thanks!

**Comment by vgkakade** [comment]
I am 

> 
> 
> @vgkakade
> 
> Which version of tensorflow you are using?.
> tensorflow.contrib is being removed in version TF 2.x and it works in only TF 1.x. For more info see this https://www.tensorflow.org/guide/migrate#a_note_on_slim_contriblayers
> Thanks!

I am using 2.0.0.

And if i want to cotinue with how can resolve this issue?

**Comment by ymodak** [comment]
The only way to use `contrib` functionality is to use TF 1.X version.
For TF 2.X you may try following: 
A subset of contrib functions are not part of [`TF Addons`](https://github.com/tensorflow/addons).
You have to install `addons` package separately.
You can also raise a FR on the `addons` to repo to add feature not already available.
Thanks!
