### ISSUE TITLE
tf.io.gfile.GFile truncates gzipped files loaded from Google Cloud buckets

### ISSUE THREAD

**Issue by jall** [tensorflow/tensorflow#40801]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.15.5
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): `v2.2.0-rc4-8-g2b96f3662b 2.2.0`
- Python version: 3.6.2
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

Loading a CSV file with `tf.io.gfile.GFile("gs://my-bucket/my-file.csv")` from a Google Cloud bucket is truncating the results for gzipped files.

E.g. one test file is stored with gzip compression & has a compressed filesize of 45kb, but an uncompressed size of 170kb. Reading from the file via `GFile.read()` only outputs 45kb of (uncompressed) data, then the file closes. Checking the size of the file with `GFile.size()` reports 45kb.

There don't appear to be any options available regarding compression, and the data is correctly uncompressed, but truncated

**Describe the expected behavior**

The entire file is returned, and `GFile.size()` returns the uncompressed filesize.

**Standalone code to reproduce the issue**

https://colab.research.google.com/drive/15xXT8nXAr0cqjmvV1-JMu3es4e9a34xL?usp=sharing

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.2 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/ae4de5593b1d31db7ee78fa5149fbb51/40801-tf-nightly.ipynb). Thanks!

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue in TF 2.5. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/f1d07b700d6e4cd22aed0b135cf9174b/untitled85.ipynb).Thanks!

**Comment by pjpratik** [comment]
@jall I was checking if the issue still exists in TF 2.11. I got error while accessing the bucket. Please find the gist [here](https://colab.research.google.com/gist/pjpratik/78669b004aaf999ba41b495421b11adf/40801.ipynb). Could you please help us with this. Thank you.

**Comment by jall** [comment]
@pjpratik the company that owns that GCP account shut down this year!

I think this issue should be reproducible with any gzipped file in any account, but I don't have access to a GCP account to help out

**Comment by mihaimaruseac** [comment]
GCS file issues should now be moved to tensorflow/io

**Comment by pjpratik** [comment]
@jall Could you please refer this [comment](https://github.com/tensorflow/tensorflow/issues/40801#issuecomment-1365940539) and move the issue to [tensorflow/io](https://github.com/tensorflow/io/issues) repo. Thank you!
