### ISSUE TITLE
Error while running CIFAR-10 example from the site.

### ISSUE THREAD

**Issue by tamimcsedu19** [tensorflow/tensorflow#4081]
When I run the CIFAR-10 code from [https://www.tensorflow.org/versions/r0.10/tutorials/deep_cnn/index.html#convolutional-neural-networks](here) I get the error
 `argparse.ArgumentError: argument --batch_size: conflicting option string: --batch_size`

I didn't modify anything in the code. Just ran the code with `python cifar10.py`  after cloning the tensorflow repo. Python version is 3.5 , and tensorflow version  0.10.0rc0

**Comment by deepali-c** [comment]
To execute the sample run `python cifar10_train.py` or `python cifar10_eval.py` instead.
