### ISSUE TITLE
Add "align_corners" and "half_pixel_centers" as argument to tf.image.resize 

### ISSUE THREAD

**Issue by winnietsang** [tensorflow/tensorflow#40812]
tf.compat.v1.image.resize_nearest_neighbor, tf.compat.v1.image.resize_bilinear and tf.compat.v1.image.resize_bicubic all have "align_corners" and "half_pixel_centers" as argument for user to set or unset.
Can tf.image.resize provides "align_corners" and "half_pixel_centers" as argument for user to use too? 

**System information**
- TensorFlow version (you are using): 2.2.0

**Who will benefit with this feature?**
For user who is currently using "align_corners" and "half_pixel_centers" in tf.compat.v1.image.resize_nearest_neighbor, tf.compat.v1.image.resize_bilinear and tf.compat.v1.image.resize_bicubic, want to migrate to use tf.image.resize

**Comment by jvishnuvardhan** [comment]
@winnietsang Sorry for the late response. Are you still interested in contributing this feature?

Please note that Keras development moved to another repository to focus entirely on only keras. Could you please repost this issue or raise a PR in [keras-team/keras repo.](https://github.com/keras-team/keras/issues). Thanks!

**Comment by dzsonigg** [comment]
It would be a nice feature. We using cv2 and tf 2.10 for resize and it is not the same. 

With this, we set half_pixel_centers=False, we can get the same results.
