### ISSUE TITLE
segmentation fault in ctc_decode function

### ISSUE THREAD

**Issue by mjkim720** [tensorflow/tensorflow#40810]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.7.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
Segmentation fault occurs in `tf.keras.backend.ctc_decode` when passing a large value for `top_paths` and setting `greedy` to `False`. If it is far large enough to be out of range of `int32`, the function handles the error properly by throwing an exception in python, but when it is around the boundary of the range, the function produces a segfault.

**Describe the expected behavior**
No segfault. 

**Standalone code to reproduce the issue**
```python
import tensorflow as tf

y_pred = [[[4.7, 3.2, 2.8],
        [4.9, 1.0, 3.0]],

       [[3.9, 3.8, 1.4],
        [1.0, 1.6, 3.8]],

       [[4.0 , 4.5, 3.9],
        [2.2, 2.2, 4.5]]]
input_length = [3, 2, 2]
top_paths = 2147483697

tf.keras.backend.ctc_decode(y_pred, input_length, False, 100, top_paths)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
Segmentation fault (core dumped)
```

**Comment by ymodak** [comment]
Colab session crashes after using all available RAM. Tested with TF version 2.2.0

**Comment by kkimdev** [comment]
Fixed https://github.com/tensorflow/tensorflow/commit/23693102bf820cbed93b7be0cf43f44db9faca02
