### ISSUE TITLE
Tensorflow models getting lag on safari-12 and safari-13 (Iphone5 to Iphone 8 and MAC IOS 12)

### ISSUE THREAD

**Issue by vasanthhr** [tensorflow/tensorflow#40818]
Hello,

We ran the web-version of tensor-flow models([facemesh](https://github.com/tensorflow/tfjs-models/tree/master/facemesh)) on safari-12/safari-13 version on different devices like iphon5 to iphone8 and MAC(IOS12).

But the model's inferences getting slowed down and facing lag on these devices.

Please suggest me any improvement can be done on this platforms (like safari-12/13 and iphone5 to iphone 8 and MAC IOS-12).

**Comment by ravikyram** [comment]
@vasanthhr 

I think this issue belongs to models repo. You can raise an issue in models repo from [here]( Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose)).Thanks!
