### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by RengarWang** [tensorflow/tensorflow#40819]
After installing tensorflow-gpu=2.0.0, "import tensorflow as tf" reports an error：
AttributeError: module 'tensorflow' has no attribute 'compat'

How to deal with it?

**Comment by arp99** [comment]
I can't even install tensorflow on windows 10
my pip version 20.1.1
python version: 3.8.2
I have already installed CUDA toolKit and added to my system variables

**Comment by RengarWang** [comment]
> I can't even install tensorflow on windows 10
> my pip version 20.1.1
> python version: 3.8.2
> I have already installed CUDA toolKit and added to my system variables

Maybe it's a version problem. You'd better install Python version 3.7。
Now I've solved that problem.
![image](https://user-images.githubusercontent.com/51586022/85832091-072ab800-b7c2-11ea-995a-5581d51ed754.png)
The problem is tensorflow-estimator==2.2.0！！！So uninstall it and retry install again.
conda uninstall tensorflow-estimator
conda install tensorflow-estimator==2.0.0 
conda install tensorflow-gpu==2.0.0

**Comment by Saduf2019** [comment]
@RengarWang 
Please confirm your issue is resolved so we could move this to closed status.

**Comment by RengarWang** [comment]
> @RengarWang
> Please confirm your issue is resolved so we could move this to closed status.

yes,it is solved,thanks.
