### ISSUE TITLE
Quantized tflite model's inference slower than the un-quantized tflite model on Raspberry Pi

### ISSUE THREAD

**Issue by pkb14197** [tensorflow/tensorflow#40825]
**Issue** 
I have two keras models, named as model1.h5 and model2.h5.

- They are converted into tflite model, named as model1.tflite and model2.tflite through code:

```
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
```

- They are quantized and converted into tflite model, named as quanmodel1.tflite and quanmodel2.tflite through code:
```
converter = tf.lite.TFLiteConverter.from_keras_model(model) 
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_quant_model = converter.convert()
```
When I run the four tflite models on Raspberry Pi for inference, I find the inference speed per image (listed below) is strange:

- model1.tflite (model size 240 KB) -- 0.1s;
- quanmodel1.tflite (model size 68KB) -- 0.2s;
- model2.tflite (model size 1990 KB) -- 0.17s;
- quanmodel2.tflite (model size 514 KB) -- 0.1s.

Why the inference speed of model1.tflite is faster than that of quantized model (quanmodel1.tflite) while model2.tflite is slower than that of quanmodel2.tflite?

**Comment by Saduf2019** [comment]
@pkb14197 
Please provide sample code for us to replicate the issue faced along with the version or share a colab gist with the error faced.

**Comment by pkb14197** [comment]
> @pkb14197
> Please provide sample code for us to replicate the issue faced along with the version or share a colab gist with the error faced.

The code of converting the models to tflite model has been shown above. The same codes are used to convert the two models. However the inference speed for model1 is strange.

**Comment by jvishnuvardhan** [comment]
@pkb14197 Can you please the code to create the model? I want to check the root-cause of the issue. Thanks!
