### ISSUE TITLE
Saver not created because there are no variables in the graph to restore

### ISSUE THREAD

**Issue by kwijik** [tensorflow/tensorflow#40824]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below): 2.2.0
- Python version: 3.74
- GPU model and memory: Intel(R) HD Graphics 530

I write in C# and use ML.net but the error comes from Tensorflow library.
While trying to Fit the model
`ITransformer model = trainingPipeline.Fit(trainingDataView);
`
 it gives following error:
Saver not created because there are no variables in the graph to restore

**Comment by ravikyram** [comment]
@kwijik 

Can you please help us with the simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by kwijik** [comment]
@ravikyram Thank you for your answer.
I generated an image classification model with Visual Studio. After I tried to change some hyper-parameters like number of epochs, batchsize, etc to see if it will give better results. But it gave me an error "Saver not created because there are no variables in the graph to restore". I began to look for an error, returned initial parameters and tried to recreate default model:
`ModelBuilder.CreateModel()` 
CreateModel() works good till the moment when it calls
`ITransformer model = trainingPipeline.Fit(trainingDataView);`
Here something goes wrong and I have the error.

**Comment by ravikyram** [comment]
@kwijik 

Will it be possible to share complete code snippet to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by kwijik** [comment]
@ravikyram  
You will find the code here https://github.com/kwijik/ict 
There are 4 .cs files and a folder _images_ with images.

**Comment by gowthamkpr** [comment]
@kwijik I am not able to reproduce the issue. Please give us complete steps to reproduce the issue. Thanks!

**Comment by kwijik** [comment]
@gowthamkpr No problem. You can use the code from  https://github.com/kwijik/ict . If for some reason you cannot, follow these steps:
1 Install Visual studio 2019
2 Download images from my repository
3 Install ML.Net and Model Builder
4 Try to generate image classification model (here is an example https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet/model-builder) 
After I describe my actions here https://github.com/tensorflow/tensorflow/issues/40824#issuecomment-651021357

**Comment by gowthamkpr** [comment]
@kwijik We need a minimal reproducible code... Can you please share a small code snippet that can reproduce this issue. Thanks!
