### ISSUE TITLE
Not able to install tensorflow through pip

### ISSUE THREAD

**Issue by PeaNButT** [tensorflow/tensorflow#40822]
![issue](https://user-images.githubusercontent.com/45734921/85836310-00537380-b7c9-11ea-818e-d678d1534409.png)

- OS Platform and Distribution : win 10
- TensorFlow installed from (source or binary): pip
- TensorFlow version: 2.2
- Python version: 3.7
- Installed using : pip with no virtual env

So I tried to install tensorflow >= 2.0.0 with pip and no virtual env, but it always says ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none) and ERROR: No matching distribution found for tensorflow. Can anyone help me with it? Thanks.

**Comment by Saduf2019** [comment]
@PeaNButT 
Please check if you have the latest version of pip installed. You can upgrade pip using the below command.

python3 -m pip install --upgrade pip

Also check if you have met all the system requirements for installing TensorFlow from [this link](https://www.tensorflow.org/install/pip#system-requirements).

Here are few similar issues you could refer to.
#38750 #20444 [link](https://stackoverflow.com/questions/48720833/could-not-find-a-version-that-satisfies-the-requirement-tensorflow)

**Comment by PeaNButT** [comment]
@Saduf2019 
I have checked all the requirement, and I'm using windows 10 (64-bit), Python 3.7.3,  pip version 20.1.1. It still says 
" ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow"

**Comment by PeaNButT** [comment]
Thanks, problem solved, I was using Python 32 bit, now I have changed to 64 bit.
