### ISSUE TITLE
[TF 2.3.0] [Intel MKL] OMP Threads are created with variable number when we compile with XLA flag ON

### ISSUE THREAD

**Issue by nammbash** [tensorflow/tensorflow#40836]
Attn: @penpornk 
### **Issue:**
**_The number of OMP thread created varies for the same model across multiple runs._**

**_This also causes varied performance across multiple runs for the same model on same platform with same setting/tuning parameters._**

### **Issue Detailed:**
With options: **_--data-num-inter-threads=1 --data-num-intra-threads=28 --socket-id=0_**
When running benchmarks for RN50 inference on master branch(HEAD) with OMP_NUM_THREADS set to 28:  

We notice threads being created to be - 156 threads . **_(Incorrect)_**
Using May 24th commit sha: (fbc4da8201f5c3acecb998854d087c663f1f5cd8) - 28 threads are created **_(correct)_**

### **Observation:**
**_Disabling the XLA compile flag_** by setting TF_ENABLE_XLA=0 **_creates the proper number of 28 threads_** in current master (HEAD). **_(Correct)_**

### **_How to Reproduce:_**
Run resnet_50_v1.5 inference with XLA on the latest master
https://github.com/IntelAI/models/blob/master/benchmarks/image_recognition/tensorflow/resnet50v1_5/README.md#fp32-inference-instructions

**Comment by penpornk** [comment]
@nammbash Thank you for reporting! I've tagged this for 2.3.0.

**Comment by nammbash** [comment]
> @nammbash Thank you for reporting! I've tagged this for 2.3.0.

Do we need the Comp:MKl label?

**Comment by penpornk** [comment]
@nammbash Yes, we do. Thank you for bringing it up!

**Comment by bhack** [comment]
What is the status of this?

**Comment by sachinprasadhs** [comment]
@nammbash , Could you please try this latest Tensorflow version 2.9 and let us know if you still face an issue. Thanks!
