### ISSUE TITLE
issue with parallelizing dataset

### ISSUE THREAD

**Issue by alexmil2019** [tensorflow/tensorflow#40838]
tensorflow version: '2.1.0'

I am trying the dataset pipeline from tensorflow web page: https://www.tensorflow.org/guide/data_performance. on P3.8x GPU, Amazon EC2.
it is mentioned that using
```
benchmark(
    tf.data.Dataset.range(2)
    .interleave(ArtificialDataset)
)
```
we can parallelize dataset, however I get a total different behavior.
I increased the num_samples in given ArtificialDataset to 1000, and changed the benchmark to print the sample
```
def benchmark(dataset, num_epochs=1):
         start_time = time.perf_counter()
         for epoch_num in range(num_epochs):
             for sample in dataset:
                 # Performing a training step
                 tf. print(sample)
                 time.sleep(0.01)
         tf.print("Execution time:", time.perf_counter() - start_time)
```
and when I run
```
benchmark(
         tf.data.Dataset.range(2)
         .interleave(ArtificialDataset)
     )
```
I get
```
[0]
Execution time: 0.10175556794274598
```
for 
```
benchmark(
         tf.data.Dataset.range(4)
         .interleave(ArtificialDataset)
     )
```
I get
```
[0]
[0]
[0]
[1]
[1]
[2]
Execution time: 0.29265988897532225
```
which means it doesn't go through the whole dataset. what I am expecting based on documentation is that it should open up 2 datasets, each with 1000 samples and in parallel generates the numbers. if not how can I get this functionality using this dataset API?

**Comment by alexmil2019** [comment]
has this been fixed?
https://github.com/tensorflow/tensorflow/issues/19933

it seems dataset API is still slow.

**Comment by Saduf2019** [comment]
@alexmil2019 
Can you please try with the latest tf versions and let us know if this is still an issue.

**Comment by sushreebarsa** [comment]
Hi @alexmil2019 Could you please let us know if this is still an issue in latest stable TF v2.6.0 ?Thank you!
