### ISSUE TITLE
tf.io.decode_image(img, channels=3) outputs 4 channels when reading 4-channel BMP

### ISSUE THREAD

**Issue by mchanchee** [tensorflow/tensorflow#40839]
**EDIT:** attached a sample BMP file
[rgb32.zip](https://github.com/tensorflow/tensorflow/files/4845825/rgb32.zip)

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution: Windows 10
- TensorFlow installed from (source or binary): binary (pip)
- TensorFlow version: 2.2.0
- Python version: 3.7.7

**Describe the current behavior**
When reading in a **4-channel BMP**:
- `tf.io.decode_image(img, channels=3)` gives shape **(..., ..., 4) instead of (..., ..., 3)**
- `tf.io.decode_bmp(img, channels=3)` gives the following error
```
Traceback (most recent call last):
  File "channels.py", line 44, in <module>
    loop()
  File "channels.py", line 14, in loop
    img = tf.io.decode_bmp(img, channels=3)
  File "C:\Users\mattchee\Miniconda3\lib\site-packages\tensorflow\python\ops\gen_image_ops.py", line 899, in decode_bmp
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\mattchee\Miniconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 6653, in raise_from_not_ok_status     
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: channels attribute 3 does not match bits per pixel from file 4 [Op:DecodeBmp]
```

I'm following [this guide](https://www.tensorflow.org/tutorials/load_data/images#load_using_tfdata) to load images efficiently so `tf.keras.preprocessing.image.load_img(img_path, color_mode="rgb")` is not an option.

**Describe the expected behavior**
This is inconsistent with `tf.io.decode_image(img, channels=3)` and `tf.io.decode_png(img, channels=3)` which give shape (..., ..., 3) when reading a 4-channel PNG.

Both `tf.io.decode_image(img, channels=3)` and `tf.io.decode_bmp(img, channels=3)` would be expected to give shape (..., ..., 3) when reading in a 4-channel BMP.

**Standalone code to reproduce the issue**
```python
img = tf.io.read_file(img_path)
img = tf.io.decode_image(img, channels=3)
print(img.shape) # This prints (64, 127, 4)
```
Or
```python
img = tf.io.read_file(img_path)
img = tf.io.decode_bmp(img, channels=3) # Error
print(img.shape)
```

**Comment by yongtang** [comment]
@mchanchee Can you share a sample bmp file to reproduce the issue?

**Comment by mihaimaruseac** [comment]
Can you also test with `tf-nightly`. There has been a refactoring of `tf.io.decode_image` recently which I think covers this issue too.

**Comment by hyeygit** [comment]
Thank you for reporting the issue. It appears to be an inherent issue with `decode_bmp` op. I will look into it and loop back with updates.

**Comment by mchanchee** [comment]
@yongtang @hyeygit Thank you for looking into it. I've added a sample BMP file to the issue description

**Comment by mchanchee** [comment]
I've tried it with `tf-nightly 2.4.0-dev20200708` and it's all good.

Thank you very much for fixing the issue!

**Comment by hyeygit** [comment]
Again, thank you for reporting, also for confirming that the issue is fixed!
