### ISSUE TITLE
Process hanging when using TF_SessionRun with multiple times the same input

### ISSUE THREAD

**Issue by LaurentMazare** [tensorflow/tensorflow#4084]
It seems that if the same input appears multiple times in the inputs argument of TF_SessionRun (from c_api.h) then the TF_SessionRun call never returns.
This issue can be reproduced by modifying c_api_test.cc and replacing the line:
   csession.SetInputs({{feed, Int32Tensor(3)}});
With:
   csession.SetInputs({{feed, Int32Tensor(3)}, {feed, Int32Tensor(3)}});
According to gdb, the process is waiting for a mutex in the RunState destructor from DirectSession.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
none

### Environment info
Operating System: Linux 4.4

Installed version of CUDA and cuDNN: none

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
008bcaea38815f46804fc3f56492f4dd93837a56
2. The output of `bazel version`
Build label: 0.3.1
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 29 09:09:52 2016 (1469783392)
Build timestamp: 1469783392
Build timestamp as int: 1469783392

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
See above.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by poxvoculi** [comment]
Thanks for the report.

**Comment by mrry** [comment]
In general the C API is unforgiving when it comes to usage, but this should be an easy and cheap piece of validation code to add.

**Comment by mrry** [comment]
Running tests now... it should appear after the next push.
