### ISSUE TITLE
Training has slowed down 46 times when fit on TF2.0 compared to TF1.15?

### ISSUE THREAD

**Issue by ctmckee** [tensorflow/tensorflow#40847]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Amazon Linux AMI 2018.03, rhel fedora
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:NA
- TensorFlow installed from (source or binary):I installed via pip install tensorflow==2.0.0
- TensorFlow version (use command below): 2.0.0 and 1.15.2
- Python version: 3.6.10 
- Bazel version (if compiling from source):NA
- GCC/Compiler version (if compiling from source):NA
- CUDA/cuDNN version: Cuda compilation tools: release 10.0, V10.0.130
- GPU model and memory: NVIDIA Corporation GV100GL [Tesla V100 SXM2 16GB] (rev a1)

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I would like to serve my keras model with TensorFlow serving using a TensorFlow SavedModel format.  I was following TF's tutorial on how to do that at this link https://www.tensorflow.org/tfx/tutorials/serving/rest_simple.   I found out though that this requires TF2.x.  So I installed TF2.0.0 and tried to refit my model using all the same code.  However, the training time takes 46 times as long(=46 times more expensive) in TF2.0.0 as compared to TF1.15.2.  So I can't continue that path.   Obviously there have been some changes in TF2.0.0, suggesting I may need to change how I create models and fit them?  However, I don't know what I should do.
**Describe the expected behavior**
I expect that TF2.0.0 be able to fit models at speeds that are comparable to TF1.15.2
**Standalone code to reproduce the issue**
I don't know if you need to see all of the model (it is an encode-decode model for object detection).  Here is the troublesome bit and the output receive (in TF1.15.2 and TF2.0.0)
```
#create the model
model = Model(input_img,d1)

#review the model   
model.summary()

#Compile the model
model.compile(optimizer=optimizer,loss=theLoss,metrics =['accuracy'])

#save the only the best weights acheived during training
filepath='weights.best.hdf5'
checkpoint = ModelCheckpoint(filepath, monitor='val_acc',verbose=1,save_best_only=True,mode='max')
callbacks_list=[checkpoint]

y_train = to_categorical(y_train,num_classes=2)
X_train = X_train

#fit model
model.fit(X_train,y_train,validation_split=(0.15),epochs=1,batch_size=2,verbose=1,callbacks=callbacks_list,shuffle=True)
```
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
Here is the logs for the fitting of the first epoch.  First in TF1.15 and then in TF2.0.0

TF1.15 (51 seconds per epoch)
`
Train on 850 samples, validate on 150 samples
848/850 [============================>.] - ETA: 0s - loss: 44.0265 - acc: 0.5417
Epoch 00001: val_acc improved from -inf to 0.97858, saving model to weights.best.hdf5
850/850 [==============================] - 50s 59ms/sample - loss: 44.0126 - acc: 0.5419 - val_loss: 37.6455 - val_acc: 0.9786
`

TF2.0 ( 2324 seconds per epoch.  Side note, TF2.0 skipped saving the best model weights using the checkpoint?)
`
Train on 850 samples, validate on 150 samples
848/850 [============================>.] - ETA: 5s - loss: 44.8913 - accuracy: 0.5424 WARNING:tensorflow:Can save best model only with val_acc available, skipping.
850/850 [==============================] - 2324s 3s/sample - loss: 44.8785 - accuracy: 0.5425 - val_loss: 41.7605 - val_accuracy: 0.0883
`

**Comment by amahendrakar** [comment]
@ctmckee,
Could you please provide the complete code to reproduce the issue reported here.

Also, please check if you are facing the same issue with the latest version of TensorFlow v2.2. Thanks!

**Comment by ctmckee** [comment]
Here is the full code to reproduce.  I will try on v2.2 as well.

```
import tensorflow as tf
print(tf.__version__)
import tensorflow.keras.backend as K
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.initializers import glorot_normal, VarianceScaling,he_normal
from tensorflow.keras.utils import to_categorical, HDF5Matrix
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.layers import Dense, Flatten, Input, GlobalMaxPooling2D, Dropout, Conv2D,Activation,MaxPooling2D,Add
from tensorflow.keras.layers import BatchNormalization, concatenate, UpSampling2D, Concatenate
from tensorflow.keras.optimizers import Adam, Nadam, RMSprop
from tensorflow.keras import regularizers

tf.compat.v1.reset_default_graph()
K.clear_session()

#hyperparams
input_img = Input(shape=(512,512,1))
ch1=32
ch2=ch1*2
ch3=ch2*2
ch4 = ch3*2
ch5 = ch4*2
ks=3
rg = 0.01
init = glorot_normal(seed=0)
activation = 'relu'
optimizer = Adam(learning_rate=0.00001)
theLoss = 'categorical_crossentropy'

#model layers
xin = Conv2D(ch1,ks,padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(input_img)
x1 = Conv2D(ch1,ks,padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(xin)
x1 = Activation(activation)(x1)
x1 = BatchNormalization(axis=-1)(x1)
x1 = Add()([xin,x1])
x1 = MaxPooling2D((2,2),padding='same')(x1) #image size = 256

xin = Conv2D(ch2,ks,padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(x1)
x2 = Conv2D(ch2,ks,padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(xin)
x2 = Activation(activation)(x2)
x2 = BatchNormalization(axis=-1)(x2)
x2 = Add()([xin,x2])
x2 = MaxPooling2D((2,2),padding='same')(x2) #image size = 128

xin = Conv2D(ch3,ks,padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(x2)
x3 = Conv2D(ch3,ks,padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(xin)
x3 = Activation(activation)(x3)
x3 = BatchNormalization(axis=-1)(x3)
x3 = Add()([xin,x3])
x3 = MaxPooling2D((2,2),padding='same')(x3) #image size = 64

xin = Conv2D(ch4,ks,padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(x3)
x4 = Conv2D(ch4,ks,padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(xin)
x4 = Activation(activation)(x4)
x4 = BatchNormalization(axis=-1)(x4)
x4 = Add()([xin,x4])
x4 = MaxPooling2D((2,2),padding='same')(x4) #image size = 32

xin = Conv2D(ch5,ks,padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(x4)
x5 = Conv2D(ch5,ks,padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(xin)
x5 = Activation(activation)(x5)
x5 = BatchNormalization(axis=-1)(x5)
x5 = Add()([xin,x5])

encoded = MaxPooling2D((2,2),padding='same')(x5) #image size = 16
xu = Conv2D(ch5,(1,1),padding='valid')(encoded)

x6 = concatenate([xu,encoded],axis=-1)
x6 = UpSampling2D((2,2), interpolation='bilinear')(x6)                  #image size = 32
x6 = Conv2D(ch5,kernel_size=(1,1),padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(x6)
x6 = Conv2D(ch5,ks,padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(x6)
x6 = Conv2D(ch5,ks,padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(x6)
x6 = Activation(activation)(x6)
x6 = BatchNormalization(axis=-1)(x6)


x7 = concatenate([x6,x4],axis=-1)
x7 = UpSampling2D((2,2), interpolation='bilinear')(x7)                  #image size =  64
x7 = Conv2D(ch4,kernel_size=(1,1),padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(x7)
x7 = Conv2D(ch4,ks,padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(x7)
x7 = Conv2D(ch4,ks,padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(x7)
x7 = Activation(activation)(x7)
x7 = BatchNormalization(axis=-1)(x7)


x8 = concatenate([x7,x3],axis=-1)
x8 = UpSampling2D((2,2), interpolation='bilinear')(x8)                  #image size = 128
x8 = Conv2D(ch3,kernel_size=(1,1),padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(x8)
x8 = Conv2D(ch3,ks,padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(x8)
x8 = Conv2D(ch3,ks,padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(x8)
x8 = Activation(activation)(x8)
x8 = BatchNormalization(axis=-1)(x8)


x9 = concatenate([x8,x2],axis=-1)
x9 = UpSampling2D((2,2), interpolation='bilinear')(x9)                  #image size = 256
x9 = Conv2D(ch2,kernel_size=(1,1),padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(x9)
x9 = Conv2D(ch2,ks,padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(x9)
x9 = Activation(activation)(x9)
x9 = BatchNormalization(axis=-1)(x9)


x10 = concatenate([x9,x1],axis=-1)
x10 = UpSampling2D((2,2), interpolation='bilinear')(x10)                  #image size = 512
x10 = Conv2D(ch1,kernel_size=(1,1),padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(x10)
x10 = Conv2D(ch1,ks,padding='same',use_bias=1,kernel_initializer=init,kernel_regularizer=regularizers.l2(rg),bias_initializer='zeros')(x10)
x10 = Activation(activation)(x10)
x10 = BatchNormalization(axis=-1)(x10)

decoded = Conv2D(2,(1,1),padding='valid',use_bias=1)(x10)
d1 = Activation('softmax')(decoded)

#create the model
model = Model(input_img,d1)

#review the model   
model.summary()

#Compile the model
model.compile(optimizer=optimizer,loss=theLoss,metrics =['accuracy'])

#save the only the best weights acheived during training
filepath='weights.best.hdf5'
checkpoint = ModelCheckpoint(filepath, monitor='val_acc',verbose=1,save_best_only=True,mode='max')
callbacks_list=[checkpoint]

#fit the model
y_train = to_categorical(y_train,num_classes=2)
X_train=X_train
model.fit(X_train,y_train,validation_split=(0.15),epochs=1,batch_size=2,verbose=1,callbacks=callbacks_list,shuffle=True)
```

**Comment by amahendrakar** [comment]
@ctmckee,
I am facing an error stating `NameError: name 'y_train' is not defined` on running the code. Could you please share the dataset and all supporting files you are using as well? Thanks!

**Comment by ctmckee** [comment]
I cannot share the data set.  It is proprietary.  Let me see if can create a fake batch of data

**Comment by ctmckee** [comment]
I tested on TF2.2.0 with CUDA 10.1

The time issue is resolved.  Although it still won't save my checkpoint.  I'll track that down.
```
425/425 [==============================] - ETA: 0s - loss: 44.4419 - accuracy: 0.5496WARNING:tensorflow:Can save best model only with val_acc available, skipping.
425/425 [==============================] - 26s 62ms/step - loss: 44.4419 - accuracy: 0.5496 - val_loss: 47.7793 - val_accuracy: 0.0371
```
