### ISSUE TITLE
Python3.9 support

### ISSUE THREAD

**Issue by skaldek** [tensorflow/tensorflow#40840]
Has anyone tried to build tensorflow for Python3.9? For the assembly, everything seems to go fine, except for troubles with installing some pypi packages (Maybe there is a problem in Windows, installing using .wheel passes). Almost all the necessary packages are present except for grpcio. It turns out, we just need to wait until it appears.

**Comment by mihaimaruseac** [comment]
We need to wait until official release of Python 3.9 and then we need to have our dependencies (numpy, pybind, grpcio, etc.) also update.

**Comment by Saduf2019** [comment]
@skaldek 
Please update as per above comment.

**Comment by ChihweiLHBird** [comment]
> We need to wait until official release of Python 3.9 and then we need to have our dependencies (numpy, pybind, grpcio, etc.) also update.

Python 3.9 is officially released, so when do you plan to add 3.9 support to TensorFlow?

**Comment by mihaimaruseac** [comment]
As mentioned in the quote, when all of our dependencies support py3.9

**Comment by bersbersbers** [comment]
I may be wrong, but I believe this is the case:

```
python3.8 -m pipdeptree -p tensorflow | grep "^  -" | sed "s/  - //" | sed "s/ \[.*]//" | xargs python3.9 -m pip install
```

which is essentially
```
python3.9 -m pip install absl-py astunparse flatbuffers gast google-pasta grpcio h5py keras-preprocessing numpy opt-einsum protobuf six tensorboard tensorflow-estimator termcolor typing-extensions wheel wrapt
```

works fine for me. Am I missing anything?

**Comment by bersbersbers** [comment]
Anyone interested in updates, best follow https://github.com/tensorflow/tensorflow/issues/44485
