### ISSUE TITLE
Implementation of T-LSTM keras layer

### ISSUE THREAD

**Issue by dougzec** [tensorflow/tensorflow#40844]
This is a feature request regarding the implementation of T-LSTM cells. This feature enables taking into account time within unevenly sampled data, like medical consulting, queue arrivals, traffic flow and so on.

References:
Paper: [Patient Subtyping via Time-Aware LSTM Networks](https://www.kdd.org/kdd2017/papers/view/patient-subtyping-via-time-aware-lstm-networks)
[Tensorflow implementation by the author](https://www.google.com/url?sa=t&source=web&rct=j&url=https://github.com/illidanlab/T-LSTM&ved=2ahUKEwiU2PS3lKDqAhVkGbkGHf9LDOwQFjAAegQIAxAB&usg=AOvVaw1hTrTDWbewgCVIfbk94_-j)

**Comment by ravikyram** [comment]
@dougzec 

 Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!
