### ISSUE TITLE
Building Issue: Is it possible to download everything before building from source?

### ISSUE THREAD

**Issue by bfluo** [tensorflow/tensorflow#4085]
I am trying to build Tensorflow from source on Ubuntu 16.04 with CUDA 8.0 and CUDNN 5.

However, since I am blocked by the firewall, I encountered a bunch of network issues after running `./configure`, for example:

`ERROR: /home/icstpie/lbf/tensorflow/tensorflow/tensorboard/bower/BUILD:5:1: no such package '@iron_form_element_behavior//': Error cloning repository: https://github.com/polymerelements/iron-form-element-behavior.git: cannot open git-upload-pack caused by https://github.com/polymerelements/iron-form-element-behavior.git: cannot open git-upload-pack caused by Connection refused github.com and referenced by '//tensorflow/tensorboard/bower:bower'.`
`
ERROR: /home/icstpie/lbf/tensorflow/tensorflow/core/platform/default/build_config/BUILD:56:1: no such package '@gif_archive//': Error downloading from http://ufpr.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz to /home/icstpie/.cache/bazel/_bazel_root/2510eb67c1daed69b89d219166d8dadf/external/gif_archive: Error downloading http://ufpr.dl.sourceforge.net/project/giflib/giflib-5.1.4.tar.gz to /home/icstpie/.cache/bazel/_bazel_root/2510eb67c1daed69b89d219166d8dadf/external/gif_archive/giflib-5.1.4.tar.gz: Expected 721KB, got 294KB and referenced by '//tensorflow/core/platform/default/build_config:platformlib'.`
`
ERROR: Evaluation of query "deps((//... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.`

I think these errors are caused by the command `bazel fetch //...` in the configure file.

Since bazel ignores the proxy environment LD_PRELOAD, I'm wondering that if I can manually download these things with my proxy and put them somewhere so that bazel can find them? I've tried putting the protobuf repository (the first thing bazel will download) in the root directory of tensorflow but bazel still tries to download it anyway.

I'm not sure if there is any workaround to use proxy with bazel. However, since my GPU server has a slow network and I can use faster network elsewhere, it will be nice if I can download these things manually instead of running `bazel fetch //...` on my server.

**Comment by bfluo** [comment]
I somehow managed to use a faster network on my server and the error of cloning github repositories just disappeared. I think this error is caused by the slow network.

And I also find that shadowsocks+proxychains works fine with bazel when I operate on the server directly rather than login with SSH. I'm not sure if this is the real reason but the downloading part just finished smoothly after these two changes.

I'll close this issue since I have successfully built tensorflow from source. Feel free to reopen if my experience cannot help you with this problem.

**Comment by samhodge** [comment]
OK I have an example of this problem, I have one machine I can run on the internet, and then I have another machine behind the firewall with no internet access where I can build

can I run "bazel fetch **" where everything possible gets pulled down and then go to the other machine and build

stopping and pulling one more package is wasting me hours of time.
