### ISSUE TITLE
TFTRT combinednms fail in in TRT 6 and TF 1.15.

### ISSUE THREAD

**Issue by qinyao-he** [tensorflow/tensorflow#40856]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.15
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 10.0 cuDNN 7.6.3
- GPU model and memory:

**Describe the current behavior**
TensorRT 6 support is added by https://github.com/tensorflow/tensorflow/pull/32397 which include three changes: header files, fall to fp16, and combined nms WAR last output dim.

However in 1.15 release, only header file change is cherry-picked https://github.com/tensorflow/tensorflow/pull/32828, as a result, two other change is missing. TFTRT CombinedNMS is no workable with TRT 6.

**Describe the expected behavior**

Should also cherry-pick other two changes.

**Comment by qinyao-he** [comment]
@aaroey

**Comment by aaroey** [comment]
@bixia1
