### ISSUE TITLE
tfrecords on s3 very slow on tf-nightly, not tensorflow 2.2

### ISSUE THREAD

**Issue by Abhipray** [tensorflow/tensorflow#40855]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS 10.14.6
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.1-35161-gd659eb9c0d 2.3.0-dev20200625
- Python version: 3.7.1

**Describe the current behavior**

Loading tfrecord data from s3 is slow in the nightly version. Following script takes 0.8 seconds on tf2.2 but 5 seconds on tf-nightly. The effects are more pronounced with slow network speeds. 

**Describe the expected behavior**

tfrecord streaming should be as fast in tf-nightly as in tf2.2. 

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1Q5zsGJYKrogNGqfQ6DXds4AKWEXSzwKx?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@Abhipray,
I did not observe much difference on comparing TF v2.2 with the latest TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/145c3807e9e932202ecad1aa9cb89a44/40855-2-2.ipynb). The difference was about ~0.07 seconds.

Could you please upgrade to the latest nightly version i.e. TF v2.5.0-dev20200629 and check if it works. Thanks!

**Comment by Abhipray** [comment]
@amahendrakar 
You are right. On Google colab with 2.5.0-dev20200629, I am no longer able to replicate this issue. However, I still see this issue on my macbook. tf 2.5.0-dev20200629 is 3x slower than tf 2.2. How can I produce a gist that captures this on my local machine?

**Comment by amahendrakar** [comment]
@Abhipray,
Please share the `.ipynb` file or the Jupyter notebook which you have run. Thanks!
