### ISSUE TITLE
Access feature map regions in keras custom layer and assigning values to output layer.

### ISSUE THREAD

**Issue by Aviral-Aggarwal** [tensorflow/tensorflow#40863]
I am creating a custom layer where I have to access the individual map windows and do operations on them, but because the model sends in none type as the first dimension of the input, I am unable to iterate over or access the region. Some help would be greatly appreciated. Here is the link to the full problem and the code:
[stack_overflow_link](https://stackoverflow.com/questions/62564980/access-image-regions-in-keras-custom-layer-and-assigning-values-to-the-output)

**Comment by Aviral-Aggarwal** [comment]
I am trying to implement custom pooling layer. If the pooing region would be (3x3), then I would need to convert it into an array or vector of size 9, and then operations on that including exponential and sorting. Any idea on how I can access such regions or iterate over it?

**Comment by ravikyram** [comment]
@Aviral-Aggarwal 

Request you to fill [issue template.](https://github.com/tensorflow/tensorflow/issues/new/choose)

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.

Request you to share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!
