### ISSUE TITLE
module 'keras.backend' has no attribute 'get_session'

### ISSUE THREAD

**Issue by nikita-neo** [tensorflow/tensorflow#40869]
**System information**
- macOS 10.15.5
- TensorFlow installed from (source or binary):
- TensorFlow version: 2.2.0
- Python version: 3.8.3

hey guys! just got a trouble, can't find any ansewrs at web, can some one help me?

**Error:**
Traceback (most recent call last):
  File "/Users/a/PycharmProjects/untitled/venv/main.py", line 7, in <module>
    detector = ObjectDetection()
  File "/Users/a/PycharmProjects/untitled/venv/lib/python3.7/site-packages/imageai/Detection/__init__.py", line 88, in __init__
    self.sess = K.get_session()
AttributeError: module 'keras.backend' has no attribute 'get_session

**code:**
from imageai.Detection import ObjectDetection
import tensorflow.keras.backend
import os

exec_path = os.getcwd()
detector = ObjectDetection()
detector.setModelTypeAsRetinaNet()
detector.setModelPath(os.path.join(exec_path, "resnet50_coco_best_v2.0.1.h5"))
detector.loadModel()

List = detector.detectObjectsFromImage(input_image=os.path.join(exec_path, "traffic_jam.jpg"),
                                       output_image_path=os.path.join(exec_path, "new_traffic_jam.jpg")
                                       )

**Comment by shenyubin1990** [comment]
I had the same error and fixed by downgrading tensorflow to 1 rather than 2.2. Personally I used 1.14 and the error disappeared. Also the imageai doc shows the tf 2 is coming soon, which means not available currently.

**Comment by nikita-neo** [comment]
Thank u so much, i downgraded tensorflow and keras to 2.1.2, works good)

**Comment by multitown25** [comment]
> I had the same error and fixed by downgrading tensorflow to 1 rather than 2.2. Personally I used 1.14 and the error disappeared. Also the imageai doc shows the tf 2 is coming soon, which means not available currently.

How did you downgrade tensorflow? I get an error while installing tensorflow 1.14 
![image](https://user-images.githubusercontent.com/62503301/88225281-e21b4f00-cc72-11ea-99c5-7093dfeb4cae.png)

**Comment by shenyubin1990** [comment]
> > I had the same error and fixed by downgrading tensorflow to 1 rather than 2.2. Personally I used 1.14 and the error disappeared. Also the imageai doc shows the tf 2 is coming soon, which means not available currently.
> 
> How did you downgrade tensorflow? I get an error while installing tensorflow 1.14
> ![image](https://user-images.githubusercontent.com/62503301/88225281-e21b4f00-cc72-11ea-99c5-7093dfeb4cae.png)
> 
> > Are you satisfied with the resolution of your issue?
> > [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/40869)
> > [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/40869)

Firstly, your screenshot showed the version was 1.4. Secondly, if your Python version is 3.8, it only supports tf 2.2 or later. I hope this will help you.

**Comment by multitown25** [comment]
> > > I had the same error and fixed by downgrading tensorflow to 1 rather than 2.2. Personally I used 1.14 and the error disappeared. Also the imageai doc shows the tf 2 is coming soon, which means not available currently.
> > 
> > 
> > How did you downgrade tensorflow? I get an error while installing tensorflow 1.14
> > ![image](https://user-images.githubusercontent.com/62503301/88225281-e21b4f00-cc72-11ea-99c5-7093dfeb4cae.png)
> > > Are you satisfied with the resolution of your issue?
> > > [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/40869)
> > > [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/40869)
> 
> Firstly, your screenshot showed the version was 1.4. Secondly, if your Python version is 3.8, it only supports tf 2.2 or later. I hope this will help you.

How can I solve the problem that the author had? When trying to install tensorflow I see this
![image](https://user-images.githubusercontent.com/62503301/88231210-7c33c500-cc7c-11ea-97b4-a7a31bdd4484.png)
I think I have version 2.2

**Comment by sjadlakha** [comment]
> > I had the same error and fixed by downgrading tensorflow to 1 rather than 2.2. Personally I used 1.14 and the error disappeared. Also the imageai doc shows the tf 2 is coming soon, which means not available currently.
> 
> How did you downgrade tensorflow? I get an error while installing tensorflow 1.14
> ![image](https://user-images.githubusercontent.com/62503301/88225281-e21b4f00-cc72-11ea-99c5-7093dfeb4cae.png)
> 
> > Are you satisfied with the resolution of your issue?
> > [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/40869)
> > [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/40869)

I think, you have typed "1.4" instead of "1.14" by mistake.

**Comment by Unterbelichtet** [comment]
You first need to uninstall tensorflow by typing `pip uninstall tensorflow`, then you can install the older version with `pip3 install tensorflow==1.4`.

**Comment by ChopsKingsland** [comment]
I had this error, so I downgraded to Tensorflow 1.14, but then I get this error... `ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via 'pip install tensorflow'`

**Comment by rohan100jain** [comment]
What version of Keras are you using? https://imageai.readthedocs.io/en/latest/ suggests 2.2.3. The imageai library is not built for TF 2.0 (it says so on their website) and so you need TF 1.x for this to work. Only some versions of keras are compatible with TF 1.x, so you need to make sure you have those versions installed.

**Comment by Halkyon64** [comment]
In my case help replacing 
from keras import backend as K
to
import tensorflow.python.keras.backend as K

**Comment by emailic** [comment]
In the previous tf versions: 
`data_aug_iter = val_ds.make_one_shot_iterator()`
`next_element= data_aug_iter.get_next()`

`# Running next element in our graph will produce a batch of images`
`for i in range(5):`
    `batch_of_imgs, label = tf.keras.backend.get_session().run(next_element)`
   ` img = batch_of_imgs[0]`

Now becomes (tf version 2.8.2) : 
`iterator = iter(val_ds)`
`next_element = iterator.get_next()`

`#Running next element in our graph will produce a batch of images` 
`for i in range(5):`
 ` batch_of_imgs, label = next_element`
 ` img = batch_of_imgs[0]`
