### ISSUE TITLE
Why models with different parameter size all allocate all the GPU memory

### ISSUE THREAD

**Issue by qinshuaihua** [tensorflow/tensorflow#40879]
I use tensorflow-gpu 1.15 trains models , and for resnet models with different parameter size, they all allocate all the memory for a V100 GPU. However, when I train a larger transformer model, it only allocate a part of the memory.  When I set:
fraction = round(0.5, 1)
    # config = tf.ConfigProto()
    # sess_config.gpu_options.per_process_gpu_memory_fraction = fraction
    config = tf.ConfigProto()
    gpu_option = tf.GPUOptions(allow_growth=True,per_process_gpu_memory_fraction=fraction)
    config.allow_soft_placement=True
    config.gpu_options.allow_growth = True
    with tf.Session(config=config) as sess:
the gpu_options do not work effectively.  May the code cause this problem?
![image](https://user-images.githubusercontent.com/34976119/85942146-1c3a4f00-b95a-11ea-86b5-a8a2d808db51.png)

**Comment by Saduf2019** [comment]
@qinshuaihua 
Please share complete code for us to replicate the issue faced or share a colab gist with error to analyse.
