### ISSUE TITLE
Bug when serializing optimizer with `tf.keras.utils.serialize_keras_object` but works fine with `tf.keras.optimizers.serialize`

### ISSUE THREAD

**Issue by SpikingNeuron** [tensorflow/tensorflow#40878]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.8
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
I have provided two code snippets for serializing and deserializing Keras optimizer. One of them works and other doesn't.

**Describe the expected behavior**
Both the code snippets should work.

**Standalone code to reproduce the issue**

<a href="https://colab.research.google.com/github/SpikingNeuron/tfpy_warrior/blob/master/try_optimizer_serialization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

For your quick reference, I provide here the two code snippets

### Snippet 1 - does not work

```python
import tensorflow.keras as tk
opt = tk.optimizers.Adam()
opt_ser = tk.utils.serialize_keras_object(opt)
opt_deser = tk.utils.deserialize_keras_object(opt_ser)
print(opt_deser)
```

### Snippet 2 - works

```python
import tensorflow.keras as tk
opt = tk.optimizers.Adam()
opt_ser = tk.optimizers.serialize(opt)
opt_deser = tk.optimizers.deserialize(opt_ser)
print(opt_deser)
```

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2, nightly and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/008110269c775bd28e1ce2515ddbdaee/untitled.ipynb).Thanks!

**Comment by saikumarchalla** [comment]
@SpikingNeuron  Was able to replicate the issue using TF 2.5 but error message has been given clearly how it should be passed.
Could you please check the [gist](https://colab.research.google.com/gist/saikumarchalla/f2ddc24fbd3df428845fa3cfa1649206/untitled85.ipynb) and confirm if we can go ahead and close the issue. Thanks!

**Comment by SpikingNeuron** [comment]
The error says `ValueError: Unknown object: Adam.`
But the Adam object is inbuilt.
If you think that should not be an issue and users can understand that they still need to use the `custom_objects` argument for builtins then please close the issue.
