### ISSUE TITLE
Pinned scipy dependency

### ISSUE THREAD

**Issue by mirekphd** [tensorflow/tensorflow#40884]
**System information**
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.2.0
- Python version: 3.7
- Installed using: pip

**Describe the problem**
Pinned `scipy` dependency. Accepted requirements should be greater than or equal to the version tested by devs, but here are just equal (currently pinned to 1.4.1).

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
pip install scipy
pip install tensorflow
```

**Any other info / logs**
```
ERROR: tensorflow 2.2.0 has requirement scipy==1.4.1; python_version >= "3", but you'll have scipy 1.5.0 which is incompatible.
```

**Comment by mihaimaruseac** [comment]
Can you make a PR to completely remove the dependency please?

See also #35709 and #40789

**Comment by mirekphd** [comment]
@mihaimaruseac - I did not realize it can be an even greater bug, i.e. an unused dependency... I can only report the mismatch of requirements with the latest version of this dependency, and an easy workaround - replacing the first equality sign in the requirements file with a "greater than" sign:) Are we absolutely sure the dependency is unused?

**Comment by mihaimaruseac** [comment]
A few months ago it was unused. I'm quite confident it is unused now too.

**Comment by mirekphd** [comment]
> 
> 
> A few months ago it was unused. I'm quite confident it is unused now too.

I think some unit tests would fail if the user had no `scipy` package pre-installed. But pinning it to obsolete version now seems to me even more capricious given the simple usage case for this package:)

Some tests where `scipy` is required:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/random/random_binomial_test.py#L53
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/utils/composite_tensor_support_test.py#L386
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/distributions/student_t_test.py#L46

**Comment by mihaimaruseac** [comment]
Yes, `scipy` is used only at test time. It should not show as install dependency in `setup.py` though.

**Comment by Saduf2019** [comment]
@mirekphd 
Please update as per above comment.

**Comment by stonebig** [comment]
hum, this is apparently not in Tensorflow_cpu-2.3.0rc2. is it normal ?

**Comment by mihaimaruseac** [comment]
The `r2.3` branch used for the 2.3 release has https://github.com/tensorflow/tensorflow/blob/b36436b087bd8e8701ef51718179037cccdfc26e/tensorflow/tools/pip_package/setup.py#L72-L73

The relaxation only occurred on master.

**Comment by stonebig** [comment]
it may be a problem when  pip new strict resolver comes in full force this fall 2020. Is there any hope to remove it for final 2.3.0 ?

**Comment by mihaimaruseac** [comment]
Unfortunately we have started the final build steps, so we can only attempt removal on a subsequent patch release.

**Comment by jklaise** [comment]
Can we re-open this issue so it doesn't get lost?

**Comment by mihaimaruseac** [comment]
Did it in a better way. Now, if there is a patch release for any of the affected branches the scipy pinning will also be removed.

**Comment by matthewfeickert** [comment]
> Did it in a better way. Now, if there is a patch release for any of the affected branches the scipy pinning will also be removed.

Thanks very much for fixing this, as this is keeping `pyhf` from using TensorFlow Probability `v0.11.0`. :+1:

**Comment by Darsh-Dev** [comment]
I'm seeing similar issue on aarch64 platform. 
`tensorflow 2.3.0 requires scipy==1.4.1, but you'll have scipy 1.5.3 which is incompatible`
