### ISSUE TITLE
How to enable XNNPACK on android using official repository?

### ISSUE THREAD

**Issue by kafan1986** [tensorflow/tensorflow#40888]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: armv7 and v8
- TensorFlow version: 2.2.0
- Installed using virtualenv?
    implementation 'org.tensorflow:tensorflow-lite:2.2.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.2.0'
    implementation 'org.tensorflow:tensorflow-lite-support:0.0.0-nightly'

**Describe the problem**

I am using tflite on android using below repos. Is the XNNPACK enabled by default on android or is there anything else required to enable it?
```
    implementation 'org.tensorflow:tensorflow-lite:2.2.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.2.0'
    implementation 'org.tensorflow:tensorflow-lite-support:0.0.0-nightly'
```

**Comment by ymodak** [comment]
You can try enabling XNNPACK using Java Api for android.
See https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/xnnpack#enable-xnnpack-via-java-api-on-android-recommended-on-android
