### ISSUE TITLE
Eager execution is turned off with a custom train_step() function

### ISSUE THREAD

**Issue by KacperKubara** [tensorflow/tensorflow#40880]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2
- Python version: 3.7

**Describe the current behavior**
According to the TF documentation, from TF 2.0 onwards Eager Execution is enabled by default: https://www.tensorflow.org/guide/eager

In TF 2.2, train_step function was added so we can create custom training loops using Subclassing API (thanks for that!). An expected behaviour would be that eager execution is enabled by default in this train_step function (according to docs and a common sense). 

When train_step function is implemented Eager execution is disabled even if it was previously enabled. It is not possible to switch it back to eager execution (e.g. by forcing tf.compat.v1.enable_eager_execution in the train step function). I would also suspect that it might be happening for test_step and predict_step but I haven't checked that yet.

**Describe the expected behavior**
train_step, predict_step and test_step run in eager mode by default.

**Standalone code to reproduce the issue**
_Link to colab notebook:_
https://colab.research.google.com/drive/1LZmKSlzYgOpX_pjnpB7P5EiRxm9_2CmN?usp=sharing

_Copy-paste version below_
``` Python
import tensorflow as tf
import numpy as np
print(tf.__version__) # Has to be 2.2

# Example modified from: https://keras.io/api/models/model/
class MyModel(tf.keras.Model):
    def __init__(self):
        super(MyModel, self).__init__()
        self.dense1 = tf.keras.layers.Dense(4, activation=tf.nn.relu)
        self.dense2 = tf.keras.layers.Dense(1, activation=tf.nn.softmax)

    def compile(self, optimizer, loss, metric):
        """
        Overriden .compile() method to initialize
        optimizer, loss, and metric for train_step function
        """
        super().compile()
        self.opt = optimizer
        self.loss = loss
        self.metric = metric  
    
    def train_step(self, data):
        print(f"Eager execution mode: {tf.executing_eagerly()}")
        X, y = data
        
        # Track gradients
        with tf.GradientTape() as tape:
             y_pred = self.call(X)
             loss = self.loss(y, y_pred)
        
        # Compute and modify the weights
        grads = tape.gradient(loss, self.trainable_weights)
        self.opt.apply_gradients(zip(grads, self.trainable_weights))        

        # Compute metric
        metric = self.metric(y, y_pred)
        return {"loss": loss, "metric": metric}
    
    def call(self, inputs):
        x = self.dense1(inputs)
        return self.dense2(x)

if __name__ == "__main__":
    # Should be True
    print(f"Eager execution mode: {tf.executing_eagerly()}")

    X = np.random.rand(10, 4)
    y = np.random.randint(0, 2, (10, 1))
    model = MyModel()
    model.compile(tf.keras.optimizers.Adam(), 
                tf.keras.losses.BinaryCrossentropy(),
                tf.keras.metrics.Accuracy())
    # Should print True
    model.fit(X, y)
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
![image](https://user-images.githubusercontent.com/33067446/85945306-403b6780-b93d-11ea-8b7f-21486eb9fe1d.png)

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.2 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/c63aadb726f15417b0399992ab80e985/40880.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment]
@KacperKubara By default, model.compile() runs in graph mode. This is to get better performance. If you want to run the training eagerly, then pass `run_eagerly=True` to the compile. As we are inheriting the functionality, compile is running in graph mode by default. 

I changed one line in your code from 
`super().compile()` to `super().compile(run_eagerly=True)`

With the above change, model prints "Eager execution mode: True". Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/0165e193fed78a5acb5cccb77b18387a/40880.ipynb)

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by KacperKubara** [comment]
Hey @jvishnuvardhan , I can confirm that it's now working as expected. Thanks for clarification! Issue can be closed.
