### ISSUE TITLE
Building C API under Windows 10 fails

### ISSUE THREAD

**Issue by InfiniteLife** [tensorflow/tensorflow#40882]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 2.2
- Python version: 3.5
- Installed using virtualenv? pip? conda?: No
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): Build Tools VC 19
- CUDA/cuDNN version: 10.1, cudann 7.6
- GPU model and memory: RTX 2080 Ti 11 Gb

**Describe the problem**
Building C API fails with this command:
`bazel build --config=opt --config=cuda --incompatible_strict_action_env=false --define=no_tensorflow_py_deps=true //tensorflow:libtensorflow.so`

Error:
```
LINK : warning LNK4217: symbol 'TF_DeleteDimensionHandle' defined in 'libops.lo(ops.o)' is imported by 'libbitcast_op_lib.lo(bitcast.o)' in function '"void __cdecl ComputeNewShape(struct TF_ShapeInferenceContext *,struct TF_ShapeHandle *,unsigned __int64,unsigned __int64,struct TF_Status *)" (?ComputeNewShape@@YAXPEAUTF_ShapeInferenceContext@@PEAUTF_ShapeHandle@@_K2PEAUTF_Status@@@Z)'
ERROR: D:/dev/tensorflow/tensorflow/BUILD:677:1: declared output 'tensorflow/libtensorflow.so.2' is a dangling symbolic link
ERROR: D:/dev/tensorflow/tensorflow/BUILD:677:1: not all outputs were created or valid
Target //tensorflow:libtensorflow.so failed to build
INFO: Elapsed time: 8143.925s, Critical Path: 1171.29s
INFO: 6722 processes: 6722 local.
FAILED: Build did NOT complete successfully
```

**Comment by amahendrakar** [comment]
@InfiniteLife,
Is this still an issue?

Could you please update TensorFlow to the latest stable version v2.4.1 and let us know if you are facing the same error. Thanks!
