### ISSUE TITLE
Tensorflow Installation via windows command prompt

### ISSUE THREAD

**Issue by Praba00** [tensorflow/tensorflow#40890]
Hi,
I have python 3.8 in my computer (windows-10 64 bit) and i'm getting error while installing tensor via command prompt.
Below are the lines i executed:
C:\Program Files (x86)\Python38-32\Scripts>pip install --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-2.2.0-cp38-cp38m-window.whl

ERROR: tensorflow-2.2.0-cp38-cp38m-window.whl is not a supported wheel on this platform. 

Need help to install.

NOTE: I'm able to install tensorflow-1.12.0 . But during import i'm getting error
ImportError: No module named '_pywrap_tensorflow_internal'

**Comment by amahendrakar** [comment]
@Praba00,
Could you please check if you are using 64-bit version of Python? 

TensorFlow is tested and supported on 64-bit systems, for more information please check the system requirements [here](https://www.tensorflow.org/install/pip#system-requirements). Thanks!

**Comment by KacperKubara** [comment]
Hi @Praba00 , conda does not support TF 2.2 on windows. You can install it with pip. 
You can find which TF version is supported by specific operating system [here](https://anaconda.org/anaconda/tensorflow)

**Comment by Praba00** [comment]
Hi @amahendrakar

My python version is of 32 bit. I will install 64 bit and try installing tensorflow again. Thanks for your response

**Comment by ayushmanantal** [comment]
> Hi,
> I have python 3.8 in my computer (windows-10 64 bit) and i'm getting error while installing tensor via command prompt.
> Below are the lines i executed:
> C:\Program Files (x86)\Python38-32\Scripts>pip install --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-2.2.0-cp38-cp38m-window.whl
> 
> ERROR: tensorflow-2.2.0-cp38-cp38m-window.whl is not a supported wheel on this platform.
> 
> Need help to install.
> 
> NOTE: I'm able to install tensorflow-1.12.0 . But during import i'm getting error
> ImportError: No module named '_pywrap_tensorflow_internal'

The Problem might be with python version, check again if you installed 64-bit version of python.

**Comment by amahendrakar** [comment]
> My python version is of 32 bit. I will install 64 bit and try installing tensorflow again. Thanks for your response

@Praba00,
Any updates regarding this? Please feel free to close the issue if resolved. Thanks!
