### ISSUE TITLE
Bake TF git commit hash into TensorFlow build

### ISSUE THREAD

**Issue by akors** [tensorflow/tensorflow#4089]
Hi, is it possible to record the Git commit hash, when building from source and making it available as a variable?

Currently, there is only 

`tensorflow.__version__`

which is nice, but with a fast-moving codebase is not quite granular enough. Something like 

`tensorflow.__commit__` would make each build uniquely identifiable which is important for me to produce reproducible runs.

**Comment by martinwicke** [comment]
Andrew is working on this.

**Comment by vrv** [comment]
Now currently available as "__git_version__": 

Example: 
```
$ python
>>> import tensorflow
>>> tensorflow.__git_version__
'v0.10.0-1576-g754048a-dirty'
```

**Comment by akors** [comment]
Thanks a lot!
