### ISSUE TITLE
Make CUDA library version numbers available from python

### ISSUE THREAD

**Issue by akors** [tensorflow/tensorflow#4090]
Hi!

Is it possible to make the versions of the CUDA libraries available as a python variable? Currently, after importing, there is the following output:

```
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so.5.1.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so.8.0 locally
```

So apparently the versioning information is loaded, I just couldn't find an API to access it.

I would like to record the CUDA as meta-information along with my checkpoint and event files, to be able to 100% reproduce any runs.

**Comment by zheng-xq** [comment]
@akors, this information is only known to stream-executor, not TensorFlow. It would take quite a bit of plumbing to set that information to TensorFlow. For your use case, would be sufficient to save the log file itself?

**Comment by akors** [comment]
@zheng-xq Well, is there a way for me to get it from stream-executor?
I guess the log file would work, although it's not an ideal solution.

**Comment by akors** [comment]
The log file is better than nothing. Is there at least a way to somehow capture that specific portion of the log, preferably without any stdout/stderr redirections?

**Comment by Mistobaan** [comment]
maybe add the "contributions welcome" label ? seems reasonable to have more info about the stream_executor.

**Comment by gunan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

deduping against https://github.com/tensorflow/tensorflow/issues/10827
