### ISSUE TITLE
Using zeros_like in tensorflow with keras add_loss leads to error

### ISSUE THREAD

**Issue by adrian-dalessandro** [tensorflow/tensorflow#40908]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 4.4.0-109-generic
- TensorFlow installed from (source or binary): binary
- Python version: 3.6
- CUDA/cuDNN version:
- GPU model and memory:

git_version == v2.0.0-rc2-26-g64c3d38
version == 2.0.0

### ISSUE

If I run the following code, I get an the error "InternalError: Invalid tape state.". However, if I switch tf.keras.backend.zeros_like(x) to ones_like(x) the issue disappears. It appears that the issue is arising from the zeros_like()
`imgin = tf.keras.Input((112,112,3))
x = tf.keras.layers.GlobalAvgPool2D()(imgin)
x = tf.keras.layers.Dense(1, activation="sigmoid")(x)
x_ = tf.keras.layers.Dense(1, activation="sigmoid")(x)
model = tf.keras.Model(imgin, x_)
model.add_loss(tf.keras.losses.binary_crossentropy(tf.keras.backend.zeros_like(x), x))
model.compile("Adam", "binary_crossentropy")
model.train_on_batch(tf.ones((1,112,112,3)), [1])`

**Comment by adrian-dalessandro** [comment]
Switching to tf 2.2.0 fixes the issue.

**Comment by Saduf2019** [comment]
Moving this to closed status as this is resolved.
