### ISSUE TITLE
Unexpected (incomplete ?) 4-bit quantization-aware training conversion

### ISSUE THREAD

**Issue by corvoysier** [tensorflow/tensorflow#40917]
**System information**
- OS Platform and Distribution : Linux Ubuntu 18.04
- TensorFlow installed from (source or binary):  nightly docker image 
- TensorFlow version (or github SHA if from source): 2.3.0-dev20200618

**Command used to run the converter or code if you’re using the Python API**

From this gist:

https://gist.github.com/corvoysier/906818ec1de2a84be31156d09042fce4

Type the following command:

```
python mnist_qat_nbit.py --save
```
This will produce three files:
- a `mnist_baseline.h5` non-quantized float model,
- a `mnist_qat.h5` quantized float model,
- a `mnist_integer.tflite` converted 4-bit integer model ([mnist_integer.tflite.zip](https://github.com/tensorflow/tensorflow/files/4846585/mnist_integer.tflite.zip))

You can dump the intermediate outputs of the inference of a single image using this command ([inference.txt](https://github.com/tensorflow/tensorflow/files/4846566/inference.txt)):

```
python mnist_tflite_debug.py -m mnist_integer.tflite
```

The 4-bit quantization configurations (and their associated quantizers) are defined in `n_bit_qat_helpers.py` and are just sub-classes of the base TFMOT QAT classes. 

**Failure details**

The model is converted without errors, but the weights and activations are not exactly quantized as expected.

Expected:

- filters should be int8 in the range [-7,7],
- biases should be int32,
- activations should be uint8 in the range [0, 15].

Obtained:

- filters are 4-bit quantized int8 in the range [-127, 127],
- biases are int32 (correct),
- activations are non-quantized int8.

**Comment by amahendrakar** [comment]
@corvoysier,
On running the code I am facing an error stating `ModuleNotFoundError: No module named 'n_bit_qat_helpers'`. 

Looks like you are using custom Python modules in your code. Could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by corvoysier** [comment]
> @corvoysier,
> On running the code I am facing an error stating `ModuleNotFoundError: No module named 'n_bit_qat_helpers'`.
> 
> Looks like you are using custom Python modules in your code. Could you please provide the complete code to reproduce the issue reported here. Thanks!

Hi, as explained in the description:

The 4-bit quantization configurations (and their associated quantizers) are defined in n_bit_qat_helpers.py and are just sub-classes of the base TFMOT QAT classes.

So everythin is in the gist.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/c39a3be40ace47dc098b114c5216126c/40917.ipynb). Thanks!

**Comment by corvoysier** [comment]
> Was able to reproduce the issue, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/c39a3be40ace47dc098b114c5216126c/40917.ipynb). Thanks!

Thanks for taking the time to reproduce. However, it looks like your notebook uses TF 2.2, which does not support QAT at all: you must use the TF nightly to reproduce this QAT issue.

**Comment by joyalbin** [comment]
Facing the same issue here..
@corvoysier could you able to find any solution for this? or its still an open issue?

**Comment by joyalbin** [comment]
@nutsiepully @jvishnuvardhan , Could you please help on this?

**Comment by nutsiepully** [comment]
QAT supports training + conversion only for the default TF quantization [spec](https://www.tensorflow.org/lite/performance/quantization_spec).

For experimental quantization, training is supported but conversion and execution are not supported. Please see
[https://www.tensorflow.org/model_optimization/guide/quantization/training#experiment_with_quantization_and_associated_hardware] (this).
