### ISSUE TITLE
`Package                Version

### ISSUE THREAD

**Issue by 13121283123** [tensorflow/tensorflow#40915]
`Package                Version
---------------------- -------------------
absl-py                0.9.0
astor                  0.8.1
astunparse             1.6.3
cachetools             4.0.0
certifi                2019.11.28
chardet                3.0.4
gast                   0.2.2
google-auth            1.11.3
google-auth-oauthlib   0.4.1
google-pasta           0.2.0
grpcio                 1.27.2
h5py                   2.10.0
idna                   2.9
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.0
keyboard               0.13.4
Markdown               3.2.1
mss                    5.0.0
numpy                  1.18.2
oauthlib               3.1.0
opt-einsum             3.2.0
pip                    20.0.2
protobuf               3.11.3
pyasn1                 0.4.8
pyasn1-modules         0.2.8
requests               2.23.0
requests-oauthlib      1.3.0
rsa                    4.0
scipy                  1.4.1
setuptools             41.2.0
six                    1.14.0
tb-nightly             2.2.0a20200320
tensorboard            2.1.1
tensorboard-plugin-wit 1.6.0.post2
tensorflow             2.1.0
tensorflow-estimator   2.1.0
termcolor              1.1.0
tf-estimator-nightly   2.3.0.dev2020032001
urllib3                1.25.8
Werkzeug               1.0.0
wheel                  0.34.2
wrapt                  1.12.1`

_Originally posted by @gragundier in https://github.com/tensorflow/tensorflow/issues/37756#issuecomment-601865269_

**Comment by 13121283123** [comment]
Have you solved this problem?  module 'tensorflow' has no attribute 'compat'

**Comment by mihaimaruseac** [comment]
https://github.com/tensorflow/tensorflow/issues/37756#issuecomment-601899742 has the solution, it's just the comment after the one you quoted
