### ISSUE TITLE
Add TF_AllocateTensor to version 0.10

### ISSUE THREAD

**Issue by IvanUkhov** [tensorflow/tensorflow#4091]
Recently there was [added](https://github.com/tensorflow/tensorflow/commit/ae7b1310c5b2bbb333191d0def7985202dee382a) a very useful function to the C API—namely, `TF_AllocateTensor`. Currently the commit is not present on branch `r0.10`. I’m wondering if it’s possible to cherry-pick the commit to `r0.10` so that the function is available already in version 0.10. Thank you.

Regards,
Ivan

**Comment by martinwicke** [comment]
@josh11b what do you think? Is this part of the C API completeness?

**Comment by martinwicke** [comment]
Looks like that commit didn't make it into 0.10. Don't worry, 0.11 is going to contain it.
