### ISSUE TITLE
LLVM requires at least MSVC 2017

### ISSUE THREAD

**Issue by MevadaRavikumar** [tensorflow/tensorflow#40910]
Hi, 
I am following this tutorial (https://github.com/EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi) in order to convert my TensorFlow frozen model into tflite using TOCO. I am stuck at Step 2e. Build the TensorFlow package. 
When I am running this command 'bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package '. It is giving me this kind of error.  I have used tensorflow 1.15, Windows 10 OS, Bazel 0.24.1, Anaconda Spyder 64 bit. 

Trace Back: 

    ERROR: C:/users/ravi/_bazel_ravi/mxogbt5u/external/llvm/BUILD.bazel:2263:1: C++ compilation of rule '@llvm//:mc' failed (Exit 
    2): cl.exe failed: error executing command
      cd C:/users/ravi/_bazel_ravi/mxogbt5u/execroot/org_tensorflow
      SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Windows 
    Kits\10\include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\8.1\include\shared;C:\Program Files (x86)\Windows 
    Kits\8.1\include\um;C:\Program Files (x86)\Windows Kits\8.1\include\winrt;
        SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\WINDOWS\Microsoft.NET\Framework64\;C:\Program Files (x86)\Windows Kits\8.1\bin\x64;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;;C:\WINDOWS\system32
        SET PWD=/proc/self/cwd
        SET PYTHON_BIN_PATH=C:/Users/Ravi/anaconda3/envs/tensorflow-make/python.exe
        SET PYTHON_LIB_PATH=C:/Users/Ravi/anaconda3/envs/tensorflow-make/lib/site-packages
        SET TEMP=C:\Users\Ravi\AppData\Local\Temp
        SET TF2_BEHAVIOR=0
        SET TF_CONFIGURE_IOS=0
        SET TMP=C:\Users\Ravi\AppData\Local\Temp
      C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/llvm /Ibazel-out/x64_windows-opt/genfiles/external/llvm /Ibazel-out/x64_windows-opt/bin/external/llvm /Iexternal/zlib_archive /Ibazel-out/x64_windows-opt/genfiles/external/zlib_archive /Ibazel-out/x64_windows-opt/bin/external/zlib_archive /Iexternal/llvm/include /Ibazel-out/x64_windows-opt/genfiles/external/llvm/include /Ibazel-out/x64_windows-opt/bin/external/llvm/include /Iexternal/zlib_archive /Ibazel-out/x64_windows-opt/genfiles/external/zlib_archive /Ibazel-out/x64_windows-opt/bin/external/zlib_archive /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_DEPRECATE /D_CRT_NONSTDC_NO_WARNINGS /D_SCL_SECURE_NO_DEPRECATE /D_SCL_SECURE_NO_WARNINGS /DUNICODE /D_UNICODE /DLLVM_ENABLE_STATS /D__STDC_LIMIT_MACROS /D__STDC_CONSTANT_MACROS /D__STDC_FORMAT_MACROS /DLLVM_BUILD_GLOBAL_ISEL /showIncludes /MD /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Gy /Gw -w -w -DWIN32_LEAN_AND_MEAN -DNOGDI /arch:AVX -Zc:inline -Zc:strictStrings -Zc:rvalueCast -Oi -wd4141 -wd4146 -wd4180 -wd4244 -wd4258 -wd4267 -wd4291 -wd4345 -wd4351 -wd4355 -wd4456 -wd4457 -wd4458 -wd4459 -wd4503 -wd4624 -wd4722 -wd4800 -wd4100 -wd4127 -wd4512 -wd4505 -wd4610 -wd4510 -wd4702 -wd4245 -wd4706 -wd4310 -wd4701 -wd4703 -wd4389 -wd4611 -wd4805 -wd4204 -wd4577 -wd4091 -wd4592 -wd4319 -wd4324 -w14062 -we4238 /Fobazel-out/x64_windows-opt/bin/external/llvm/_objs/mc/MCAsmInfoELF.obj /c 
    external/llvm/lib/MC/MCAsmInfoELF.cpp
    Execution platform: @bazel_tools//platforms:host_platform
    external/llvm/include\llvm/Support/Compiler.h(79): fatal error C1189: #error:  LLVM requires at least MSVC 2017.
     Target //tensorflow/tools/pip_package:build_pip_package failed to build
    INFO: Elapsed time: 327.786s, Critical Path: 57.27s
    INFO: 14 processes: 14 local.
    FAILED: Build did NOT complete successfully

What should I do to overcome this problem?

**Comment by mihaimaruseac** [comment]
You need to install MSVC 2017

**Comment by gowthamkpr** [comment]
As mention in the above comment and in the error message 
`fatal error C1189: #error:  LLVM requires at least MSVC 2017.
 Target //tensorflow/tools/pip_package:build_pip_package failed to build`

you atleast nead MSVC 2017. Thanks!
