### ISSUE TITLE
how to convert  save RNN-based model(TF2.0) as TF1.x pb format

### ISSUE THREAD

**Issue by hahadashi** [tensorflow/tensorflow#40927]
Tensorflow 2.0
Linux
`
`import tensorflow as tf
from absl import logging

class ModelRnn(tf.keras.Model):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        layers = tf.keras.layers
        input_feature = layers.Input(
            shape=(None, 40, 1),
            dtype=tf.float32
        )
        inner = layers.Conv2D(
            filters=16,
            kernel_size=(41, 11),
            strides=(2, 2),
            padding="same",
            use_bias=False,
            data_format="channels_last",
        )(input_feature)
        inner = layers.BatchNormalization()(inner)
        inner = tf.nn.relu6(inner)
        inner = layers.Conv2D(
            filters=16,
            kernel_size=(21, 11),
            strides=(2, 1),
            padding="same",
            use_bias=False,
            data_format="channels_last",
        )(inner)
        inner = layers.BatchNormalization()(inner)
        inner = tf.nn.relu6(inner)
        _, _, dim, channels = inner.get_shape().as_list()
        output_dim = dim * channels
        inner = layers.Reshape((-1, output_dim))(inner)
        gru = tf.keras.layers.GRUCell(1024)
        inner, last_state = tf.keras.layers.RNN(
            cell=gru,
            return_sequences=True,
            return_state=True
        )(inputs=[inner])
        inner = layers.BatchNormalization()(inner)
        inner = layers.Dense(1024, activation=tf.nn.relu6)(inner)
        inner = layers.Dense(10)(inner)
        self.net = tf.keras.Model(inputs=[input_feature], outputs=[inner]) 
         
    def call(self, samples, training=None):
        return self.out(samples, training=training)

if __name__ == "__main__":
    rnn = ModelRnn()
     
    inputs = tf.random.normal([32, 100, 40, 1])
    labels = tf.random.normal([32, 25, 10])
    
    loss_func = tf.keras.losses.CategoricalCrossentropy(from_logits=True)
    num = 0
    while num < 10:
        with tf.GradientTape() as tape:
            logits, state = rnn(inputs, training=True) 
            loss = loss_func(labels, logits)
            print("loss: ", loss)
            grads = tape.gradient(loss, rnn.trainable_variables)
            optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
            optimizer.apply_gradients(zip(grads, rnn.trainable_variables))
        num += 1
    rnn.save_weights("net.h5")
`
`

**Comment by amahendrakar** [comment]
@hahadashi,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by hahadashi** [comment]
@amahendrakar hi,  i update my demo code,  i want to frozen the model to pb format for C++ inference. i tried lots of ways.  but didn`t work. other, i have converted transformer model to pb, but it not work for RNN. hope some advices.

**Comment by hahadashi** [comment]
@amahendrakar hi, i want to insert a placehoder replace the initial_states of RNN after convert the model

**Comment by syw2014** [comment]
@hahadashi Met the same confuse,I train model with TF2.2 and want to deploy the model only with TF1.x, but I have no idea how to do this, Could you give me some advice?

**Comment by hahadashi** [comment]
> @hahadashi Met the same confuse,I train model with TF2.2 and want to deploy the model only with TF1.x, but I have no idea how to do this, Could you give me some advice?

@syw2014 your code use keras.layers.RNN ? i have not deal with the problem.  i can get a pb model, but  A lot of operations（relate to rnn） are missing.  when i use transform tool deal the pb model i will get error"fold_constants: Ignoring error Input 7 of node model/rnn/while was passed float from rnn/bias:0 incompatible with expected resource." @amahendrakar  hope you give some advice, thxs

**Comment by hahadashi** [comment]
@amahendrakar  i want to convert TF2.0 model() to TF1.x pb model to inference C++, but i meet problem. please read the page [https://github.com/esdu/misc/blob/master/bug_report_lstm_freeze.ipynb], i get same problem, if use keras.layers.GruCell i will get "tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 7 of node prefix/out_model/rnn/while was passed float from prefix/rnn/bias:0 incompatible with expected resource."

**Comment by amahendrakar** [comment]
@hahadashi,
On running the given code, I am facing an error stating `AttributeError: 'ModelRnn' object has no attribute 'out'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/7284156a6140eddf71e6709572b56d22/40927.ipynb).

Could you please correct the error and provide a reproducible code snippet. Alternatively, you can also attach the Python script or the notebook file you are running. Thanks!

**Comment by hahadashi** [comment]
> @hahadashi,
> On running the given code, I am facing an error stating `AttributeError: 'ModelRnn' object has no attribute 'out'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/7284156a6140eddf71e6709572b56d22/40927.ipynb).
> 
> Could you please correct the error and provide a reproducible code snippet. Alternatively, you can also attach the Python script or the notebook file you are running. Thanks!

please check https://github.com/esdu/misc/blob/master/bug_report_lstm_freeze.ipynb,  i have the similar problem with it.

**Comment by amahendrakar** [comment]
> please check https://github.com/esdu/misc/blob/master/bug_report_lstm_freeze.ipynb, i have the similar problem with it.

@hahadashi,
On running the code, I am facing an error stating `ValueError: Input 0 of node import_1/lstm/while/split/ReadVariableOp/Enter was passed resource from import_1/lstm/kernel:0 incompatible with expected float.`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/cbbb85757e1880c134e7be58dff754a0/40927.ipynb#scrollTo=uMxGftRAeSVI). 

Could you please confirm if this is the same error you are facing? Thanks!
