### ISSUE TITLE
get error "assert initial_state is None and constants is None"

### ISSUE THREAD

**Issue by hahadashi** [tensorflow/tensorflow#40928]
operating system: Linux
TensorFlow version: Tensroflow2.0
        
         ```
import tensorflow as tf
from absl import logging

class ModelRnn(tf.keras.Model):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        layers = tf.keras.layers
        input_feature = layers.Input(
            shape=(None, 40, 1),
            dtype=tf.float32
        )
        inner = layers.Conv2D(
            filters=16,
            kernel_size=(41, 11),
            strides=(2, 2),
            padding="same",
            use_bias=False,
            data_format="channels_last",
        )(input_feature)
        inner = layers.BatchNormalization()(inner)
        inner = tf.nn.relu6(inner)
        inner = layers.Conv2D(
            filters=16,
            kernel_size=(21, 11),
            strides=(2, 1),
            padding="same",
            use_bias=False,
            data_format="channels_last",
        )(inner)
        inner = layers.BatchNormalization()(inner)
        inner = tf.nn.relu6(inner)
        _, _, dim, channels = inner.get_shape().as_list()
        output_dim = dim * channels
        inner = layers.Reshape((-1, output_dim))(inner)
        gru = tf.keras.layers.GRUCell(1024)
        initial = gru.get_initial_state(inputs=inner)
        inner, last_state = tf.keras.layers.RNN(
            cell=gru,
            return_sequences=True,
            return_state=True
        )(inputs=[inner], initial_state=[initial])
        inner = layers.BatchNormalization()(inner)
        inner = layers.Dense(1024, activation=tf.nn.relu6)(inner)
        inner = layers.Dense(10)(inner)
        self.net = tf.keras.Model(inputs=[input_feature], outputs=[inner]) 
         
    def call(self, samples, training=None):
        return self.out(samples, training=training)

if __name__ == "__main__":
    rnn = ModelRnn()
     
    inputs = tf.random.normal([32, 100, 40, 1])
    labels = tf.random.normal([32, 25, 10])
    
    loss_func = tf.keras.losses.CategoricalCrossentropy(from_logits=True)
    num = 0
    while num < 10:
        with tf.GradientTape() as tape:
            logits, state = rnn(inputs, training=True) 
            loss = loss_func(labels, logits)
            print("loss: ", loss)
            grads = tape.gradient(loss, rnn.trainable_variables)
            optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
            optimizer.apply_gradients(zip(grads, rnn.trainable_variables))
        num += 1
    rnn.save_weights("net.h5")


```
 i use these code in my model ,when i run, i get error "assert initial_state is None and constants is None", hope some advice

**Comment by ravikyram** [comment]
@hahadashi 

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
what platform you are using (operating system, architecture). Also include your TensorFlow version. 

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by hahadashi** [comment]
@ravikyram hi，i update my demo code, hope give me some advice.

**Comment by ravikyram** [comment]
@hahadashi 

Can you please provide colab link or simple standalone code with proper indentation and supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by hahadashi** [comment]
@ravikyram thxs your reply, i have fixed the problem. i also want to convert TF2.0 model() to TF1.x pb model to inference C++, but i meet another problem.  please read the page [https://github.com/esdu/misc/blob/master/bug_report_lstm_freeze.ipynb], i get same problem, if use  keras.layers.GruCell i whill get "tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 7 of node prefix/out_model/rnn/while was passed float from prefix/rnn/bias:0 incompatible with expected resource."

**Comment by ravikyram** [comment]
@hahadashi 

If original issue is resolved ,please close the issue and  raise new issue by filling issue template and also provide colab link or simple standalone code to reproduce the issue.Thanks!

**Comment by hahadashi** [comment]
@ravikyram ok, thnx

**Comment by ravikyram** [comment]
@hahadashi 
Please, close this thread and we can track the new issue at #40986.Thanks!

**Comment by alexiatoumpa** [comment]
> @ravikyram thxs your reply, i have fixed the problem. i also want to convert TF2.0 model() to TF1.x pb model to inference C++, but i meet another problem. please read the page [https://github.com/esdu/misc/blob/master/bug_report_lstm_freeze.ipynb], i get same problem, if use keras.layers.GruCell i whill get "tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 7 of node prefix/out_model/rnn/while was passed float from prefix/rnn/bias:0 incompatible with expected resource."

Could you please explain how you fixed the issue?

**Comment by alexiatoumpa** [comment]
I was getting the same error message when I was trying to set the initial state in a ConvLSTM2D layer:
```python
encoder_inputs = Input(shape=(samples, rows, cols, channels))
encoder_layer = ConvLSTM2D(filters = units, return_sequences = True, return_states = True)
encoder_outputs, state_h, state_c = encoder_layer(encoder_inputs)
encoder_states = [state_h, state_c]
decoder_layer = ConvLSTM2D(filters = units, return_sequence = False, return_states = False)
decoder_outputs = decoder_layer(encoder_outputs, initial_state = encoder_states)
model = Model([encoder_inputs], decoder_outputs)
```
I managed to solve this issue by setting:

`encoder_states = [state_h[0:], state_c[0:]]` instead of `encoder_states = [state_h, state_c]` .
