### ISSUE TITLE
module 'tensorflow.keras.layers' has no attribute 'Conv1DTranspose'

### ISSUE THREAD

**Issue by asd8095075** [tensorflow/tensorflow#40937]
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import Sequential

model = keras.Sequential(
    [
        layers.Input(shape=(288, 1)),
        layers.Conv1D(
            filters=32, kernel_size=7, padding="same", strides=2, activation="relu"
        ),
        layers.Dropout(rate=0.2),
        layers.Conv1D(
            filters=16, kernel_size=7, padding="same", strides=2, activation="relu"
        ),
        layers.Conv1DTranspose(
            filters=16, kernel_size=7, padding="same", strides=2, activation="relu"
        ),
        layers.Dropout(rate=0.2),
        layers.Conv1DTranspose(
            filters=32, kernel_size=7, padding="same", strides=2, activation="relu"
        ),
        layers.Conv1DTranspose(filters=1, kernel_size=7, padding="same"),
    ]
)
model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.001), loss="mse")
model.summary()

**Comment by ravikyram** [comment]
@asd8095075 

Please, fill [issue template.](https://github.com/tensorflow/tensorflow/issues/new/choose).

what platform you are using (operating system, architecture). Also include your TensorFlow version.

Can you please elaborate about the issue & the context.Will it be possible to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by asd8095075** [comment]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Repeat keras.io Code examples Timeseries anomaly detection using an Autoencoder
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10 64bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):pypi.douban.com/simple
- TensorFlow version (use command below):TensorFlow 2.2
- Python version:Python 3.7.2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:CUDA 10.2,cuDNN7.4.5
- GPU model and memory:1050ti 16G

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`


**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Repeat keras.io Code examples Timeseries anomaly detection using an Autoencoder

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2 ,nightly versions and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/929ec256b64bc482bae38fd5f42d8c73/untitled.ipynb).Thanks!

**Comment by gowthamkpr** [comment]
@asd8095075 This has been fixed in 2.3.0rc0 and also in tf-nightly. Please find the gist [here](https://colab.research.google.com/gist/gowthamkpr/1fae23cf2447dbff807bcc6c2be5155e/untitled.ipynb)

**Comment by asd8095075** [comment]
TensorFlow update 2.3.0rc0，the problem has been solved，thank！

**Comment by ravikyram** [comment]
@asd8095075 

Please, close this thread as your issue was resolved with the 2.3-rc0.Thanks!

**Comment by mhuertascompany** [comment]
Hello. I have tried to fix this issue with the solution proposed but then the import of tf probability fails in colab with the following error: 

----> 3 import tensorflow_probability as tfp
      4 import numpy as np
      5 from sklearn import preprocessing

4 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/experimental/auto_batching/frontend.py in <module>()
     43 from tensorflow.python.autograph.converters import return_statements
     44 from tensorflow.python.autograph.core import converter
---> 45 from tensorflow.python.autograph.core import naming
     46 from tensorflow.python.autograph.pyct import anno
     47 from tensorflow.python.autograph.pyct import inspect_utils

ImportError: cannot import name 'naming'

**Comment by 3803531** [comment]
Can you make an example of a GAN fader with Tensorflow please
