### ISSUE TITLE
Colab kernal crash when specify"report_tensor_allocations_upon_oom"

### ISSUE THREAD

**Issue by a7744hsc** [tensorflow/tensorflow#40934]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
No
- TensorFlow installed from (source or binary):
Colab
- TensorFlow version (use command below):
1.15.2
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

When running this [colab](https://colab.research.google.com/drive/1I9eQDqYT4qBQT-jUXvOkvzoTKXB83Hy3?usp=sharing) notebook, the python kernel gets crashed.
If I remove the `options=tf.compat.v1.RunOptions(report_tensor_allocations_upon_oom = True)` or set `report_tensor_allocations_upon_oom ` to False, the notebook works fine.

**Describe the expected behavior**
**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1I9eQDqYT4qBQT-jUXvOkvzoTKXB83Hy3?usp=sharing
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 1.15, 2.2 and was able to reproduce the issue. However If I remove the options=tf.compat.v1.RunOptions(report_tensor_allocations_upon_oom = True) or set report_tensor_allocations_upon_oom to False then i am not seeing any issue as described in the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/6d1d416a3b58a5caa66cbbaa9a381f9e/untitled71.ipynb).Thanks!

**Comment by a7744hsc** [comment]
@ravikyram ,  yes, the issue also exists on tensorflow 2.2.0 .

By the way, is there a recommended way to investigate GPU memory detail on tf2.x?
