### ISSUE TITLE
 Could not open edgetpu.tflite 

### ISSUE THREAD

**Issue by MevadaRavikumar** [tensorflow/tensorflow#40939]
I have generated my own object detection model. For that I have used pre quantized 'ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18' model.  I have used TensorFlow 1.15 version, I haven't converted the model using Bazel and TOCO. I have quantized the model before converting it to the edgetpu model because it is already a quantized, model. 

I have converted the frozen graph model using: 

    tflite_convert \
    --graph_def_file=tflite/tflite_graph.pb \ 
     --output_file=tflite/detect.tflite \ 
     --output_format=TFLITE \
     --input_shapes=1,300,300,3 \
     --input_arrays=normalized_input_image_tensor \
     --     output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' \
     --inference_type=QUANTIZED_UINT8 \
     --mean_values=128 \
     --std_dev_values=127 \
     --change_concat_input_ranges=false \
     --allow_custom_ops

Then I have converted that model into edge tpu using: 

    ! edgetpu_compiler "/content/drive/My Drive/detect (1).tflite"

The  compilation message: 

     Edge TPU Compiler version 2.1.302470888

     Model compiled successfully in 568 ms.

     Input model: /content/drive/My Drive/detect (1).tflite
     Input size: 5.34MiB
     Output model: detect (1)_edgetpu.tflite
     Output size: 5.75MiB
     On-chip memory used for caching model parameters: 5.66MiB
     On-chip memory remaining for caching model parameters: 1.96MiB
     Off-chip memory used for streaming uncached model parameters: 0.00B
     Number of Edge TPU subgraphs: 1
     Total number of operations: 64
     Operation log: detect (1)_edgetpu.log

     Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
     Number of operations that will run on Edge TPU: 63
     Number of operations that will run on CPU: 1
     See the operation log file for individual operation details.

When I am running the example script I got from 'https://github.com/EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi/blob/master/TFLite_detection_video.py'

It gives me this kind of error. 

    python3 detection_picam.py --model /home/pi/ detection_model/detection_edgetpu.tflite --labels /home/pi /detection_model/labelmap.txt --edgetpu
    Traceback (most recent call last):
       File "detection_picam.py", line 135, in <module>
         experimental_delegates=[load_delegate('libedgetpu.so.1.0')])
      File "/home/pi/.local/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 204, in __init__
        model_path, self._custom_op_registerers))
    ValueError: Could not open '/home/pi/detection_model/detection_edgetpu.tflite/edgetpu.tflite'.

Is there any problem with the detection_edgetpu.tflite model? What can be the solution here?

**Comment by amahendrakar** [comment]
@MevadaRavikumar,
In order to expedite the trouble-shooting process, could you please provide the `detection_picam.py` file, `.pb`, `.tflite` and all other supporting files required to reproduce the issue reported here. Thanks!
