### ISSUE TITLE
C++ compilation of rule '@llvm//:binary_format' failed (Exit 2) 

### ISSUE THREAD

**Issue by MevadaRavikumar** [tensorflow/tensorflow#40931]
I am running TensorFlow 1.15 CPU version, Bazel 0.24.1, Spyder Anaconda 3.7 64 bit, and Windows 10. I am trying to build TensorFlow from the source using Bazel.
When I am running this command 'bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package '
It is throwing me this error.

    INFO: From ProtoCompile tensorflow/core/profiler/tfprof_options.pb.h:
    bazel-out/x64_windows-opt/genfiles/external/com_google_protobuf/src: warning: directory does not exist.
    bazel-out/x64_windows-opt/genfiles/external/com_google_protobuf/src: warning: directory does not exist. 
    bazel-out/x64_windows-opt/genfiles/external/com_google_protobuf/src: warning: directory does not exist.
    bazel-out/x64_windows-opt/genfiles/external/com_google_protobuf/src: warning: directory does not exist.
    ERROR: C:/users/ravi/_bazel_ravi/mxogbt5u/external/llvm/BUILD.bazel:1327:1: C++ compilation of rule '@llvm//:binary_format' 
    failed (Exit 2): cl.exe failed: error executing command
      cd C:/users/ravi/_bazel_ravi/mxogbt5u/execroot/org_tensorflow
      SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\8.1\include\shared;C:\Program Files (x86)\Windows Kits\8.1\include\um;C:\Program Files (x86)\Windows Kits\8.1\include\winrt;
        SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\WINDOWS\Microsoft.NET\Framework64\;C:\Program Files (x86)\Windows Kits\8.1\bin\x64;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;;C:\WINDOWS\system32
        SET PWD=/proc/self/cwd
        SET PYTHON_BIN_PATH=C:/Users/Ravi/anaconda3/envs/tensorflow4/python.exe
        SET PYTHON_LIB_PATH=C:/Users/Ravi/anaconda3/envs/tensorflow4/lib/site-packages
        SET TEMP=C:\Users\Ravi\AppData\Local\Temp
        SET TF2_BEHAVIOR=0
        SET TF_CONFIGURE_IOS=0
        SET TMP=C:\Users\Ravi\AppData\Local\Temp
      C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/llvm /Ibazel-out/x64_windows-opt/genfiles/external/llvm /Ibazel-out/x64_windows-opt/bin/external/llvm /Iexternal/zlib_archive /Ibazel-out/x64_windows-opt/genfiles/external/zlib_archive /Ibazel-out/x64_windows-opt/bin/external/zlib_archive /Iexternal/llvm/include /Ibazel-out/x64_windows-opt/genfiles/external/llvm/include /Ibazel-out/x64_windows-opt/bin/external/llvm/include /Iexternal/zlib_archive /Ibazel-out/x64_windows-opt/genfiles/external/zlib_archive /Ibazel-out/x64_windows-opt/bin/external/zlib_archive /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_DEPRECATE /D_CRT_NONSTDC_NO_WARNINGS /D_SCL_SECURE_NO_DEPRECATE /D_SCL_SECURE_NO_WARNINGS /DUNICODE /D_UNICODE /DLLVM_ENABLE_STATS /D__STDC_LIMIT_MACROS /D__STDC_CONSTANT_MACROS /D__STDC_FORMAT_MACROS /DLLVM_BUILD_GLOBAL_ISEL /showIncludes /MD /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Gy /Gw -w -w -DWIN32_LEAN_AND_MEAN -DNOGDI /arch:AVX -Zc:inline -Zc:strictStrings -Zc:rvalueCast -Oi -wd4141 -wd4146 -wd4180 -wd4244 -wd4258 -wd4267 -wd4291 -wd4345 -wd4351 -wd4355 -wd4456 -wd4457 -wd4458 -wd4459 -wd4503 -wd4624 -wd4722 -wd4800 -wd4100 -wd4127 -wd4512 -wd4505 -wd4610 -wd4510 -wd4702 -wd4245 -wd4706 -wd4310 -wd4701 -wd4703 -wd4389 -wd4611 -wd4805 -wd4204 -wd4577 -wd4091 -wd4592 -wd4319 -wd4324 -w14062 -we4238 /Fobazel-out/x64_windows-opt/bin/external/llvm/_objs/binary_format/Dwarf.obj /c external/llvm/lib/BinaryFormat/Dwarf.cpp
    Execution platform: @bazel_tools//platforms:host_platform
     external/llvm/include\llvm/Support/Compiler.h(79): fatal error C1189: #error:  LLVM requires at least MSVC 2017.
    Target //tensorflow/tools/pip_package:build_pip_package failed to build
     INFO: Elapsed time: 1150.456s, Critical Path: 326.66s
    INFO: 1003 processes: 1003 local.
    FAILED: Build did NOT complete successfully

My python config (python ./configure.py) looks like this:

    (tensorflow4) C:\tensorflow-make\tensorflow>python ./configure.py
    WARNING: Running Bazel server needs to be killed, because the startup options are different.
    WARNING: An illegal reflective access operation has occurred
    WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil 
    (file:/C:/Users/Ravi/_bazel_Ravi/install/41e4b00c041f69b9ddd856a8576133ae/_embedded_binaries/A-server.jar) to field java.nio.Buffer.address
    WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
    WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
    WARNING: All illegal access operations will be denied in a future release
    WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
    You have bazel 0.24.1- (@non-git) installed.
    Please specify the location of python. [Default is C:\Users\Ravi\anaconda3\envs\tensorflow4\python.exe]:

    Found possible Python library paths:
      C:\Users\Ravi\anaconda3\envs\tensorflow4\lib\site-packages
    Please input the desired Python library path to use.  Default is [C:\Users\Ravi\anaconda3\envs\tensorflow4\lib\site-packages]

    Do you wish to build TensorFlow with XLA JIT support? [y/N]: n
    No XLA JIT support will be enabled for TensorFlow.

    Do you wish to build TensorFlow with ROCm support? [y/N]: n
    No ROCm support will be enabled for TensorFlow.

    Do you wish to build TensorFlow with CUDA support? [y/N]: n
    No CUDA support will be enabled for TensorFlow.

    Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:

    Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: n
    Not overriding eigen strong inline, some compilations could take more than 20 mins.

    Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
            --config=mkl            # Build with MKL support.
            --config=monolithic     # Config for mostly static monolithic build.
            --config=gdr            # Build with GDR support.
            --config=verbs          # Build with libverbs support.
            --config=ngraph         # Build with Intel nGraph support.
            --config=numa           # Build with NUMA support.
            --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
            --config=v2             # Build TensorFlow 2.x instead of 1.x.
    Preconfigured Bazel build configs to DISABLE default on features:
            --config=noaws          # Disable AWS S3 filesystem support.
            --config=nogcp          # Disable GCP support.
            --config=nohdfs         # Disable HDFS support.
            --config=noignite       # Disable Apache Ignite support.
            --config=nokafka        # Disable Apache Kafka support.
            --config=nonccl         # Disable NVIDIA NCCL support.

It would be great If someone can guide me to understand and solve this problem.

**Comment by gunan** [comment]
Here is the error message:
```
fatal error C1189: #error:  LLVM requires at least MSVC 2017.
```

Please make sure to upgrade your visual studio version.
