### ISSUE TITLE
Please add a example for tf.compat.v1.estimator.experimental.KMeans in savemodel load example 

### ISSUE THREAD

**Issue by lilihongjava** [tensorflow/tensorflow#40932]
python3.6
tensorflow2.0.0

error:KeyError: 'predict'

code:
import numpy as np
import tensorflow as tf

if __name__ == '__main__':
    num_points = 100
    dimensions = 1
    points = np.random.uniform(0, 1000, [num_points, dimensions])
    num_clusters = 5
    kmeans = tf.compat.v1.estimator.experimental.KMeans(
        num_clusters=num_clusters, use_mini_batch=False)

    def input_fn():
        return tf.data.Dataset.from_tensors(tf.convert_to_tensor(points, dtype=tf.float32)).repeat(1)
    # train
    num_iterations = 10
    previous_centers = None
    for _ in range(num_iterations):
        kmeans.train(input_fn)
        cluster_centers = kmeans.cluster_centers()
        if previous_centers is not None:
            print('delta:', cluster_centers - previous_centers)
        previous_centers = cluster_centers
        print('score:', kmeans.score(input_fn))
    print('cluster centers:', cluster_centers)

    input_column = tf.feature_column.numeric_column("x")
    serving_input_fn = tf.estimator.export.build_parsing_serving_input_receiver_fn(
        tf.feature_column.make_parse_example_spec([input_column]))
    estimator_path = kmeans.export_saved_model("./data/", serving_input_fn)

    imported = tf.saved_model.load("./data/1593503127/")
    print(imported.signatures["predict"])

reference documents
https://www.tensorflow.org/guide/saved_model#savedmodels_from_estimators
https://www.tensorflow.org/api_docs/python/tf/compat/v1/estimator/experimental/KMeans#export_saved_model

**Comment by Saduf2019** [comment]
@lilihongjava 
I ran the code hsared and face a different error, please share complete code or colab gist with error faced.
Please find the [gist here](https://colab.research.google.com/gist/Saduf2019/04ee1e008048b61d4d4053e4a5d412cc/untitled249.ipynb)

**Comment by lilihongjava** [comment]
> @lilihongjava
> I ran the code shared and face a different error, please share complete code or colab gist with error faced.
> Please find the [gist here](https://colab.research.google.com/gist/Saduf2019/04ee1e008048b61d4d4053e4a5d412cc/untitled249.ipynb)



I'm very sorry, I modified the code, please have a look:
https://colab.research.google.com/gist/lilihongjava/ffa3e64469ab181f17ca522a7737997b/untitled249.ipynb

**Comment by Saduf2019** [comment]
@lilihongjava 
Can you refer to these links with similar issues:
[link](https://stackoverflow.com/questions/39687554/keyerror-in-tensorflow-when-calling-predict-on-trained-model) [link1](https://github.com/allenai/allennlp/issues/2833#issuecomment-491885391)

**Comment by lilihongjava** [comment]
> @lilihongjava
> Can you refer to these links with similar issues:
> [link](https://stackoverflow.com/questions/39687554/keyerror-in-tensorflow-when-calling-predict-on-trained-model) [link1](https://github.com/allenai/allennlp/issues/2833#issuecomment-491885391)

I don't think it's the same problem，I modified my example code to make it clearer。https://colab.research.google.com/gist/lilihongjava/ffa3e64469ab181f17ca522a7737997b/untitled249.ipynb
There is no problem in the prediction after model training. The problem is in the prediction after loading the model on the hard disk。
I suspect that the   tf.compat.v1.estimator.experimental.KMeans  export model method does not provide predictive capabilities .
The reason is that I print imported.signatures, there is no prediction method:
_SignatureMap({'cluster_index': <tensorflow.python.eager.wrap_function.WrappedFunction object at 0x000001A8171C8F98>, 'serving_default': <tensorflow.python.eager.wrap_function.WrappedFunction object at 0x000001A8171B9DA0>, 'all_distances': <tensorflow.python.eager.wrap_function.WrappedFunction object at 0x000001A8185C8278>})

**Comment by Saduf2019** [comment]
I am able to replicate the issue faced, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/6081cae9fa23ad7008224e8fd31f0f3b/untitled254.ipynb)

**Comment by jvishnuvardhan** [comment]
@lilihongjava As there was a `keyError`, I changed last line of your code from

```
re = imported.signatures["predict"]( 
        examples=tf.constant([example.SerializeToString()]))
```
to

```
re = imported.signatures["serving_default"]( 
        examples=tf.constant([example.SerializeToString()]))
```

With that change, code ran without any issues. Please take a look at the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/37829b301324b5ff4582665b82d95b20/untitled254.ipynb).

Please verify once and close if the issue was resolved for you. Thanks!

**Comment by lilihongjava** [comment]
> @lilihongjava As there was a `keyError`, I changed last line of your code from
> 
> ```
> re = imported.signatures["predict"]( 
>         examples=tf.constant([example.SerializeToString()]))
> ```
> 
> to
> 
> ```
> re = imported.signatures["serving_default"]( 
>         examples=tf.constant([example.SerializeToString()]))
> ```
> 
> With that change, code ran without any issues. Please take a look at the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/37829b301324b5ff4582665b82d95b20/untitled254.ipynb).
> 
> Please verify once and close if the issue was resolved for you. Thanks!

This method solves the problem, thank you
