### ISSUE TITLE
tflite micro mbed image recognition example accuracy difference for custom model

### ISSUE THREAD

**Issue by fran203** [tensorflow/tensorflow#40935]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): 2.1
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Arm mbed os Disco F746NG

When running tests for custom model,getting different results as compared to using python(floating point model)

1.Convert model to tflite :
converter = tf.lite.TFLiteConverter.from_keras_model(tf_model)
tflite_model = converter.convert()
open('./converted_model_v1.tflite', 'wb').write(tflite_model)
![image](https://user-images.githubusercontent.com/63789049/86102915-becd0c00-bad9-11ea-9a38-dfe0e4c0c0d2.png)

2.created image header with test images 18 :
for i,j in enumerate(image_list[:]):
    print(j)
    im = Image.open(j)
    im = im.resize((32,32))
    im = (np.array(im))

    r = im[:,:,0].flatten()
    g = im[:,:,1].flatten()
    b = im[:,:,2].flatten()
    label = [i//6]
    if i==0:
        out = np.array(list(label)+list(b)+list(g)+list(r),np.uint8)
        
    else:
        out=np.append(out,np.array(list(label)+list(b)+list(g)+list(r),np.uint8))

out.tofile("tflite_sliced_images.bin")

xxd -i tflite_sliced_images.bin test_image.h

3.Accessing outputs using :
data.f[0],
data.f[1],
data.f[2]

**Comment by Saduf2019** [comment]
@fran203 
Please share complete stand alone code such that we could replicate your issue or please share colab gist with issue faced for us to analyse

**Comment by fran203** [comment]
Image recognition example :

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/image_recognition_experimental

modifications made to main:
[main.zip]
(https://github.com/tensorflow/tensorflow/files/4851720/main.zip)

other changes : 
1.replaced image model with a custom model
2.replaced data in image_header.

I'm not sure whether while creating the image binary input has to be set to float32/uint8 and whether that is causing the difference in predictions.

**Comment by fran203** [comment]
@Saduf2019 let me know if any other details are required

**Comment by fran203** [comment]
I have also tried with quantized model.When using quantized model,the interpreter call gives a hardfault error.

Conversion :
```
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
# This ensures that if any ops can't be quantized, the converter throws an error
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
# These set the input and output tensors to uint8
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
# And this sets the representative dataset so we can quantize the activations
converter.representative_dataset = representative_data_gen
tflite_model = converter.convert()
```

Ops register : (quantize and dequantize ops added and versions specified based on error message received when running)
```
  static tflite::MicroOpResolver<8> micro_op_resolver;

  micro_op_resolver.AddBuiltin(tflite::BuiltinOperator_QUANTIZE,
                               tflite::ops::micro::Register_QUANTIZE());
  micro_op_resolver.AddBuiltin(tflite::BuiltinOperator_CONV_2D,
                               tflite::ops::micro::Register_CONV_2D(),3);
  micro_op_resolver.AddBuiltin(tflite::BuiltinOperator_RELU,
                               tflite::ops::micro::Register_RELU());
    micro_op_resolver.AddBuiltin(tflite::BuiltinOperator_RESHAPE,
                              tflite::ops::micro::Register_RESHAPE());
  micro_op_resolver.AddBuiltin(tflite::BuiltinOperator_MAX_POOL_2D,
                               tflite::ops::micro::Register_MAX_POOL_2D(),2);
  micro_op_resolver.AddBuiltin(tflite::BuiltinOperator_FULLY_CONNECTED,
                               tflite::ops::micro::Register_FULLY_CONNECTED(),4);
  micro_op_resolver.AddBuiltin(tflite::BuiltinOperator_SOFTMAX,
                               tflite::ops::micro::Register_SOFTMAX(),2);
  micro_op_resolver.AddBuiltin(tflite::BuiltinOperator_DEQUANTIZE,
                               tflite::ops::micro::Register_DEQUANTIZE(),2);


```

![image](https://user-images.githubusercontent.com/63789049/86303861-ba643880-bc2a-11ea-9f30-eff2675f78d7.png)

**Comment by fran203** [comment]
@jvishnuvardhan @Saduf2019 is there anywhere i can find the model details(tf version used for training...and conversion to tflite) that gets downloaded in currently in the image_recognition example?
The model input and output in the sample model has uint8 as input and output type,but there are no quantize/dequantize ops in it.So if details about it can be provided, I can use the same versions and steps for my tflite generation.

**Comment by uf19414** [comment]
Did you find the file "image_recognition_model.cc"? Or train the model by yoursefl?

I would like to run "image_recognition_test" but I did not find the data of trained model, only headfile.

Thank you!

**Comment by fran203** [comment]
cifar model and cifar test bin gets downloaded and the model.cc and image header is created with xxd when you run make for micro recognition tests..

**Comment by fran203** [comment]
@uf19414 
you can find the urls here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/tools/make/third_party_downloads.inc

IMAGE_RECOGNITION_MODEL_URL := "https://storage.googleapis.com/download.tensorflow.org/models/tflite/cifar_image_recognition_model_2020_05_27.zip"

**Comment by wangtz** [comment]
I'd like to check a few things:

- Micro for now only support post-training quantization (the one with representative dataset) with int8 input and output for now.

- When you feed the data in C++, you need to quantize the data from float to int8. 

- Another common issue is the quality of representative dataset. The quantization process will calibrate the min and max value for each tensor, if your dataset is ordered and biased (towards large value/small values) are fed in the representative dataset, then you have a bad quantization quality. 

Let me know if it helps.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Comment by sushreebarsa** [comment]
@fran203  This is a micro related issue,Please post this in [micro repository](https://github.com/tensorflow/tflite-micro/issues) and move this issue to closed status  ..Thanks!
