### ISSUE TITLE
tensorflow:Layer will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria (using with GRU layer and dropout)

### ISSUE THREAD

**Issue by oren0e** [tensorflow/tensorflow#40944]
When trying to follow along F. Chollet's "Deep Learning with Python" listing 6.40 I encounter this warning:
`WARNING:tensorflow:Layer gru_4 will not use cuDNN kernel since it doesn't meet the cuDNN kernel criteria. It will use generic GPU kernel as fallback when running on GPU`
after executing the following code:
```python
input_tensor = layers.Input((None, float_data.shape[-1]))
kmodel = layers.GRU(32, dropout=0.2, recurrent_dropout=0.2)(input_tensor)
output_tensor = layers.Dense(1)(kmodel)
model = models.Model(input_tensor, output_tensor)
```
My imports are:
```python
import os

import numpy as np
import matplotlib.pyplot as plt

from typing import Tuple

from tensorflow.keras import models, layers
from tensorflow.keras.optimizers import RMSprop
```

Note that if I don't use `dropout` and `recurrent_dropout` in the `GRU` layer everything works fine and fast. In the case I do use dropout like in the code above, it still works but with **very** slow performance.

System information:
Python 3.7.7
tensorflow-gpu 2.2.0
GPU: Cuda compilation tools, release 10.1, V10.1.243 on GeForce RTX 2080 Ti 11016MiB
OS: Ubuntu 18.04.4 LTS

**Comment by amahendrakar** [comment]
@oren0e,
On running the code I am facing an error stating `NameError: name 'float_data' is not defined`.

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and the dataset you are using. Thanks!

**Comment by oren0e** [comment]
Sure. This is taken from F. Chollet's book:
First download the data:
`wget https://s3.amazonaws.com/keras-datasets/jena_climate_2009_2016.csv.zip`
Then unzip it to a folder and specify the full path to this folder in `data_dir`.
The code:
```python
import os

import numpy as np
import matplotlib.pyplot as plt

from typing import Tuple

from tensorflow.keras import models, layers
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence

data_dir = '**path_to_your_folder**'
fname = os.path.join(data_dir, 'jena_climate_2009_2016.csv')

f = open(fname)
data = f.read()
f.close()

lines = data.split('\n')
header = lines[0].split(',')
lines = lines[1:]
print(header)
print(len(lines))

# convert the data into numpy array
float_data = np.zeros((len(lines), len(header) - 1))
for i, line in enumerate(lines):
    values = [float(x) for x in line.split(',')[1:]]    # drop the timestamp
    float_data[i, :] = values

temp = float_data[:, 1]  # temperature (in degrees celsius)
plt.plot(range(len(temp)), temp)
plt.show()

# first 10 days (temp is recorded every 10 minutes))
plt.plot(range(1440), temp[:1440])
plt.show()

mean = float_data[:200000].mean(axis=0)
float_data -= mean
std = float_data[:200000].std(axis=0)
float_data /= std


def generator(data: np.ndarray, lookback: int, delay: int, min_index: int, max_index: int,
              shuffle: bool = False, batch_size: int = 128, step: int = 6) -> Tuple[np.ndarray, np.ndarray]:
    if max_index is None:
        max_index = len(data) - delay - 1
    i = min_index + lookback
    while 1:
        if shuffle:
            rows = np.random.randint(min_index + lookback, max_index, size=batch_size)
        else:
            if i + batch_size >= max_index:
                i = min_index + lookback
            rows = np.arange(i, min(i + batch_size, max_index))
            i += len(rows)

        samples = np.zeros((len(rows), lookback // step, data.shape[-1]))
        targets = np.zeros((len(rows),))
        for j, row in enumerate(rows):
            indices = range(rows[j] - lookback, rows[j], step)
            samples[j] = data[indices]
            targets[j] = data[rows[j] + delay][1]
        yield samples, targets

lookback = 1440
step = 6
delay = 144
batch_size = 128

train_gen = generator(float_data, lookback=lookback, delay=delay, min_index=0, max_index=200000,
                      shuffle=True, step=step, batch_size=batch_size)
val_gen = generator(float_data, lookback=lookback, delay=delay, min_index=200001, max_index=300000,
                      shuffle=True, step=step, batch_size=batch_size)
test_gen = generator(float_data, lookback=lookback, delay=delay, min_index=300001, max_index=None,
                      shuffle=True, step=step, batch_size=batch_size)

# these are the forecasted parts that we will want to look at
val_steps = (300000 - 200001 - lookback) // batch_size   # how many steps to draw from val_gen in order to see
                                            # the entire validation set
test_steps = (len(float_data) - 300001 - lookback) // batch_size     # " " for test

input_tensor = layers.Input((None, float_data.shape[-1]))
kmodel = layers.GRU(32, recurrent_dropout=0.2, dropout=0.2)(input_tensor)
output_tensor = layers.Dense(1)(kmodel)
model = models.Model(input_tensor, output_tensor)

model.compile(optimizer=RMSprop(), loss='mae')
history = model.fit_generator(train_gen, steps_per_epoch=500,
                              epochs=40,
                              validation_data=val_gen,
                              validation_steps=val_steps)
```
In my understanding, the problem is with the `recurrent_dropout` argument.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.2 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/730299a66d1086a1986f69b830d5b999/40944-gpu.ipynb). Thanks!

**Comment by amahendrakar** [comment]
@oren0e,
Please take a look at the [requirements](https://www.tensorflow.org/api_docs/python/tf/keras/layers/GRU#used-in-the-notebooks_1) to use cuDNN implementation for the GRU layer and let us know if it helps. Thanks!

**Comment by oren0e** [comment]
@amahendrakar,
The link you have provided just reconfirms that the problem is with the `recurrent_dropout` argument. The requirement is to set it to  0, i.e., not using it. I think this should be implemented in the TF backend since it is an important option that highly affects performance (training time).

**Comment by qlzh727** [comment]
@oren0e, this issue is expected since the recurrent dropout is not implemented in the Nvidia's cudnn kernel. We have to fallback to use the generic kernel when user specify the recurrent dropout. See the docstring of GRU and LSTM for the criteria of using cudnn kernel. https://www.tensorflow.org/api_docs/python/tf/keras/layers/GRU#used-in-the-notebooks_1.
