### ISSUE TITLE
bazel build label_image

### ISSUE THREAD

**Issue by guxiwuruo** [tensorflow/tensorflow#40946]
i change some code in label_image/main.cc,   when i use 

bazel build //tensorflow/examples/label_image:label_image

command to compile label_image,  it builds all the source code. how can I only compile this one specific file （label_image/main.cc）?
thanks

**Comment by Saduf2019** [comment]
@guxiwuruo 
Could you please share the stand alone indented code or a colab gist with the error faced or share colab gist with error faced.

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 2 weeks. Please add additional comments for us to open this issue again. Thanks!
