### ISSUE TITLE
How to use pre-trained word embeddings in seq2seq?

### ISSUE THREAD

**Issue by zhaopku** [tensorflow/tensorflow#4095]
I am building a seq2seq model using functions in seq2seq.py, where they have a function like this:

```
embedding_rnn_seq2seq(encoder_inputs, decoder_inputs, cell,
                          num_encoder_symbols, num_decoder_symbols,
                          embedding_size, output_projection=None,
                          feed_previous=False, dtype=dtypes.float32,
                          scope=None)
```
however, it seems that this function does not take pre-trained embeddings as input, are there any ways that I can take pre-trained word embeddings as input in this function?

**Comment by ebrevdo** [comment]
What you want to do is load pretrained embedding variables and use the tf.nn.rnn_cell.EmbeddingWrapper (or some variant of this that accesses the exact correct variable) around your cell instance, instead of calling embedding_rnn_seq2seq.  the code you're referring will be deprecated in some near future because it's not very flexible (the example you are asking about is one which should be more easily supported) + @lukaszkaiser.  To see how to load pretrained embeddings, see @mrry's excellent answer to this StackOverflow post:

http://stackoverflow.com/questions/35687678/using-a-pre-trained-word-embedding-word2vec-or-glove-in-tensorflow

**Comment by ebrevdo** [comment]
(Lukasz, if you'd like to say more, feel free to reopen & assign self)

**Comment by andrewjylee** [comment]
Hi @ebrevdo , quick question....
What I don't understand is how to match the IDs in x with the IDs of your embedding.

For instance, if my sentence is "I like to run with dogs", and that is vectorized as
[5, 9, 2, 25, 16, 4], how will Tensorflow know that id 5 in the pretrained embedding matrix should correspond to 'I' and 9 to 'like', 2 to 'to', 25 to 'run', and so on? 

so maybe we have something like 
x=tf.placeholder(...)   # [5, 9, 2, 25, 16, 4]
W = tf.Variable... # What the attached stackoverflow answer says
...

So when we do
tf.nn.embedding_lookup(W, x), how will this know that the first element of x (5) and the 5th entry in W are mapping to the same underlying word?

I hope my question made sense. Thanks in advance.

**Comment by ebrevdo** [comment]
It doesn't, you have to have a map and reorder your loaded embedding to
your vocabulary.  This can be done with the vocabulary lookup table,
tf.range, and tf.nn.top_k but is not obvious.  Alternatively manually
reshuffle the embedding matrix to match your vocabulary.  We hope to have
an example of how to do this in tf in the upcoming seq2seq tutorial with
glove embedding files.

**Comment by adakum** [comment]
@ebrevdo Can u pls point me to the seq2seq tutorial which uses glove embedding files ?

**Comment by jkneng** [comment]
Hi @andrewjylee, I have the same doubt with you. did you know how to align the word ids to ones in the pretrained embeddings? thanks

**Comment by monk1337** [comment]
I was facing same issue so I wrote detailed tutorial on that , check it out this notebook how to Use Pre-trained word_embedding in Tensorflow

https://github.com/monk1337/word_embedding-in-tensorflow/blob/master/Use%20Pre-trained%20word_embedding%20in%20Tensorflow.ipynb
