### ISSUE TITLE
How to verify Tensorflow install

### ISSUE THREAD

**Issue by omatai** [tensorflow/tensorflow#40959]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://www.tensorflow.org/install/pip#windows_1

### Clear description

See above

### Correct links

Is the link to the source code correct? n/a

### Parameters defined

Are all parameters defined and formatted correctly? n/a

### Returns defined

Are return values defined? n/a

### Raises listed and defined

n/a

### Usage example

Is there a usage example? Half of one - it lacks any output to check against, or instructions on how to interpret the result

### Request visuals, if applicable

n/a

### Submit a pull request?

No - I am far too new to github/tensorflow to ask sensible questions, let alone give sensible answers

**Comment by amahendrakar** [comment]
@omatai,
When you run 
`python3 -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"`

if the code prints the tensor, in your case `tf.tensor(72.93745, shape=(), dtype=float32)`, it means that TensorFlow was successfully imported.

Please take a look at the breakdown of the code from this [gist](https://colab.research.google.com/gist/amahendrakar/9b82b578e1dacdfc3f097811963d392a/40959.ipynb). Thanks!

**Comment by omatai** [comment]
OK - so you know that, and now I know that... but how will anyone else know that if it is not in the documentation? And how should all the information, warnings and errors be interpreted? When I follow the link you provide, it gives an error... which kinda makes it worse than when I first did it and only got warnings. So I'm not sure you have helped :-)

The point is: all this needs to be in the documentation, not here, because nobody will ever find this again :-)

**Comment by amahendrakar** [comment]
@omatai, 
Sorry for the confusion, the error was raised as I was running the code on CPU. Switching to GPU does not throw the error.

Also, the logs are displayed based on the logging level. Changing the default log level does not print `INFO` messages. Please check [this updated gist](https://colab.research.google.com/gist/amahendrakar/185c45f1c1027f13699e3e700502fcbd/40959.ipynb) for reference. Thanks!

**Comment by mihaimaruseac** [comment]
@omatai, can you please send a PR to fix documentation?

**Comment by omatai** [comment]
> 
> 
> @omatai, can you please send a PR to fix documentation?

I have no idea what is involved in a PR, no time available for several weeks to learn... and am deeply confused by why the results I got do not match the results shown by @amahendrakar - I get a tensor with value 72.something; he gets -573 or something.

If the purpose of the test is to validate the install, there needs to be a definitive and meaningful result. I am in no position to say what this result should be, nor how to interpret variations on it. Sorry - I have nothing constructive to contribute - I'm unsubscribing.

**Comment by mihaimaruseac** [comment]
Hey, @omatai. The code example listed there is just a set of TF APIs that should run. Any output is fine.

Would you be ok if we replaced it with something like `python3 -c "import tensorflow as tf; print(tf.constant("Everything installed successfully))`? In this the output either contains "Everything installed successfully" (✅) or some error (so installation fails).

**Comment by omatai** [comment]
That certainly makes more sense than printing some random number and leaving people no advice on how to interpret it :-)

But I would suggest it might be better to think about something that tests if the tensorflow installation is using GPU or CPU, and detects if that is installed correctly. As it turns out, I had installed the latest (incompatible) version of CUDA, so was not using GPU. When I ran my first heavy duty training, the CPU went to 100%, overheated and restarted my PC after 20 seconds.

I don't know if what you suggest is sufficient to detect installation problems like that (CUDA is separate, after all...) but the computation recommended might be suitable. It just lacks any guidance as to how to interpret the result... which is clearly different on my machine from @amahendrakar 's. That doesn't help anyone.

**Comment by mihaimaruseac** [comment]
That is actually a good idea. I'll try to write a `diagnose_me.py` script over the weekend and then the verify instructions would be just `python tools/diagnose_me.py` or something like that. Thank you for the reminder for adding this tool (we have many `DLL import failed` issues that would be quickly solved by this).

**Comment by iishipatel** [comment]
As suggested by @mihaimaruseac, I would like to work on making the diagnose_me.py script.

**Comment by mihaimaruseac** [comment]
With the merging of https://github.com/tensorflow/docs/pull/1749 this can be now closed.

For `diagnose_me.py` script, we should probably open a feature request.
