### ISSUE TITLE
BinaryOp vs OpKernel in Im2Col

### ISSUE THREAD

**Issue by AhmedHussKhalifa** [tensorflow/tensorflow#40955]
I have just started to create my custom OP based on "conv_ops_using_gemm.cc" and "quantized_conv_ops.cc". I want to modify the im2col algorithm inside TensorFlow to improve the performance of the inference. 

I have some questions in both files. I have some question from what I understood from the tutorial and  conv_ops_using_gemm.cc shown is the following:

1. There are some methods called **ClassName+OP** or **ClassName+functor**, I did not get the difference between them in the TensorFlow library context.
2. These classes OpKernel or BinaryOp, I do not get what are they responsible for and How I can understand them more deeply from the documentation. 
3. In [Part(1),](https://github.com/tensorflow/tensorflow/blob/d9a3a849edc198e90172bc58eb293de457f9d986/tensorflow/core/kernels/conv_ops_using_gemm.cc#L565) what I understood, it is a registration for the kernel on the CPU to be called from the python by "tf.nn.conv2d()", but I did not get how conv2d are called Im2ColConvFunctor from Conv2DUsingGemmOp class at the end of this class using "conv_factor" in [Part(2)](https://github.com/tensorflow/tensorflow/blob/d9a3a849edc198e90172bc58eb293de457f9d986/tensorflow/core/kernels/conv_ops_using_gemm.cc#L551).

Part(1):

```
#define REGISTER_CPU(T) \
 REGISTER_KERNEL_BUILDER( \
 Name("Conv2D").Device(DEVICE_CPU).TypeConstraint<T>("T"), \
 Conv2DUsingGemmOp< \
 T, Im2ColConvFunctor<T, T, T, FastGemmFunctor<T, T, T>>>);
```

Part(2):

```
 TConvFunctor conv_functor;
 conv_functor(context, input.flat<T>().data(), batch, input_rows, input_cols,
 in_depth, filter.flat<T>().data(), filter_rows, filter_cols,
 out_depth, stride_rows, stride_cols, padding_,
 output->flat<T>().data(), out_rows, out_cols);
```

**Comment by jvishnuvardhan** [comment]
@AhmedHussKhalifa 
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
