### ISSUE TITLE
Problems building TensorRT engine. 'TypeError: Expected at most 1 positional arguments'

### ISSUE THREAD

**Issue by ltorlay** [tensorflow/tensorflow#40951]
[MCNet_Model_30%_SNR10+.zip](https://github.com/tensorflow/tensorflow/files/4880911/MCNet_Model_30._SNR10%2B.zip)
(https://github.com/tensorflow/tensorflow/files/4858531/saved_model.zip)
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Nvidia JetPack 4.4 (binary)
- TensorFlow version (use command below): tensorflow 2.1.0+nv20.4
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Receiving "TypeError" when I try to build the TensorRT engine. The dataset is custom and the initial saved TF model file (saved_model.pb) is attached below. This is a similar issue as seen at #34708, and I have tried everything suggested there with no luck. I have also tried changing the input shape (changing channels and batch size), but this seems to have no effect. 

**Describe the expected behavior**
Trying to convert a TF saved model and build a tensorRT engine to be saved.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
`import tensorflow as tf 
import numpy as np
from tensorflow.python.compiler.tensorrt import trt_convert as trt

tf.enable_eager_execution()
tf.keras.backend.set_learning_phase(0)

# User input
input_path = '/home/xv/my-recognition-python/custom_model/MCNet_Model_30%_SNR10+'
output_path = '/home/xv/my-recognition-python/custom_model/TensorRT'
precision = 'FP16'

#params = tf.experimental.tensorrt.ConversionParams(precision_mode=precision)
#converter = tf.experimental.tensorrt.Converter(input)

# Conversion Parameters
conversion_params = trt.DEFAULT_TRT_CONVERSION_PARAMS
conversion_params = conversion_params._replace(
    max_workspace_size_bytes=(1<<32))
conversion_params = conversion_params._replace(precision_mode="FP16")
conversion_params = conversion_params._replace(
    maximum_cached_engines=100)

# Convert, Build and Save
tf.compat.v1.enable_eager_execution()
converter = trt.TrtGraphConverterV2(input_saved_model_dir=input_path,conversion_params=conversion_params)
converter.convert()
def my_input_fn():
    input = np.random.normal(size=(32,2,1024,1)).astype(np.float32)
    return input
converter.build(input_fn=my_input_fn)
converter.save(output_path)`

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
`Traceback (most recent call last):
  File "tf2tensorrt.py", line 31, in <module>
    converter.build(input_fn=my_input_fn)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/compiler/tensorrt/trt_convert.py", line 1040, in build
    self._converted_func(*map(ops.convert_to_tensor, inp))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 1551, in __call__
    return self._call_impl(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 1570, in _call_impl
    ).format(self._num_positional_args, self._arg_keywords, args))
TypeError: Expected at most 1 positional arguments (and the rest keywords, of ['input_1']), got (<tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[-0.6344961 ],
        [-1.4673657 ],
        [ 0.15545663],
        ...,
        [-0.0928062 ],
        [-1.3549978 ],
        [ 0.9633423 ]],

       [[-1.0417418 ],
        [-2.0699146 ],
        [-0.30908048],
        ...,
        [-0.11305276],
        [-1.1771021 ],
        [ 1.3303916 ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[-0.02007438],
        [ 0.5109657 ],
        [-1.2260785 ],
        ...,
        [-0.54254615],
        [-0.8100358 ],
        [ 0.27891546]],

       [[ 1.3610845 ],
        [ 0.24926041],
        [-0.16650145],
        ...,
        [-0.54429305],
        [-0.32332402],
        [-1.0127826 ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[ 0.62289035],
        [ 0.29980063],
        [ 0.2861899 ],
        ...,
        [ 0.9005576 ],
        [-0.62317663],
        [-0.06627446]],

       [[-0.10040612],
        [-0.09332627],
        [ 1.1089867 ],
        ...,
        [ 1.0935025 ],
        [ 0.08065958],
        [-1.2275263 ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[-0.0846673 ],
        [ 0.51114583],
        [ 1.4352379 ],
        ...,
        [ 0.95028365],
        [ 2.7874076 ],
        [ 0.77085507]],

       [[ 0.58681023],
        [ 1.0490478 ],
        [-1.3703693 ],
        ...,
        [ 1.8135824 ],
        [-0.23638606],
        [ 0.18856032]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[-0.45678732],
        [ 1.6005052 ],
        [-0.8796155 ],
        ...,
        [-0.9854982 ],
        [-0.9157079 ],
        [-0.65166223]],

       [[ 1.6831336 ],
        [-1.6157633 ],
        [-1.553059  ],
        ...,
        [ 0.34703007],
        [-0.14187814],
        [ 0.73059773]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[ 0.4139533 ],
        [ 0.50489587],
        [ 0.65386546],
        ...,
        [-0.40917957],
        [ 1.7364669 ],
        [-0.99362046]],

       [[ 0.27688766],
        [ 0.58144623],
        [ 0.40299714],
        ...,
        [ 0.7578483 ],
        [ 0.9832838 ],
        [ 1.002946  ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[-1.0991313 ],
        [-2.3144197 ],
        [-0.98326117],
        ...,
        [ 0.37580004],
        [-1.4070382 ],
        [ 0.95411766]],

       [[ 1.328169  ],
        [ 0.704368  ],
        [ 1.4499707 ],
        ...,
        [ 0.60652196],
        [ 1.4832685 ],
        [ 0.684714  ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[-0.11087849],
        [-0.07940213],
        [ 0.50273675],
        ...,
        [-0.5097304 ],
        [ 1.4458168 ],
        [-1.2201035 ]],

       [[-0.5431153 ],
        [-0.42222708],
        [ 1.092256  ],
        ...,
        [-0.04186005],
        [ 0.9809653 ],
        [-0.7850843 ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[ 1.0818578e+00],
        [-4.6179372e-01],
        [ 4.2473122e-01],
        ...,
        [-1.0006120e+00],
        [ 1.9919460e-03],
        [ 8.5118961e-01]],

       [[-1.8546258e+00],
        [ 7.0895630e-01],
        [ 2.0718536e+00],
        ...,
        [-2.4367233e-01],
        [ 6.7389584e-01],
        [ 9.7365260e-01]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[ 1.0906012 ],
        [-0.06402431],
        [ 0.91972494],
        ...,
        [-0.52831906],
        [ 1.2781252 ],
        [-0.06841598]],

       [[-1.341631  ],
        [ 0.53109026],
        [-0.11353733],
        ...,
        [ 1.1344278 ],
        [ 1.4150394 ],
        [ 1.2143872 ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[-0.36829016],
        [ 1.0754083 ],
        [ 0.16599853],
        ...,
        [-1.1099495 ],
        [-0.70543027],
        [-2.4914129 ]],

       [[-0.25961915],
        [-0.33185184],
        [-1.9378744 ],
        ...,
        [-0.64549893],
        [ 0.21132562],
        [-0.6391495 ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[-0.6435254 ],
        [-0.1136331 ],
        [ 0.25582156],
        ...,
        [ 0.00787924],
        [ 1.2224247 ],
        [ 1.2220552 ]],

       [[ 1.384727  ],
        [ 1.9391284 ],
        [ 0.04586202],
        ...,
        [ 0.06961127],
        [-0.03484035],
        [ 0.17856297]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[ 0.28783402],
        [-1.0524169 ],
        [-1.0904337 ],
        ...,
        [ 0.43865943],
        [-0.97926116],
        [ 0.2378908 ]],

       [[ 0.9016964 ],
        [-0.06834929],
        [-1.0139452 ],
        ...,
        [-0.15281294],
        [ 1.0535744 ],
        [-0.21410678]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[ 1.0744122 ],
        [-0.56937873],
        [-0.11793306],
        ...,
        [ 1.4719427 ],
        [-0.44377735],
        [-0.9831226 ]],

       [[-1.5557859 ],
        [ 1.0128443 ],
        [ 2.067592  ],
        ...,
        [-0.48884177],
        [-0.5740634 ],
        [-0.293522  ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[ 0.8241517 ],
        [ 1.8754789 ],
        [-0.8107462 ],
        ...,
        [-0.7464624 ],
        [-1.9949435 ],
        [-1.5022945 ]],

       [[ 0.63984567],
        [ 0.47466007],
        [-0.0431034 ],
        ...,
        [-0.8277903 ],
        [-0.30004153],
        [-1.1758301 ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[-0.13899833],
        [-0.6309596 ],
        [-0.54699975],
        ...,
        [ 0.5980539 ],
        [-0.5291892 ],
        [ 0.20535517]],

       [[ 0.07299482],
        [-1.5210488 ],
        [-2.2613964 ],
        ...,
        [ 1.0103334 ],
        [ 0.8114666 ],
        [-0.6411918 ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[-0.9746104 ],
        [ 0.43699232],
        [ 0.86292136],
        ...,
        [-2.000652  ],
        [ 0.19808927],
        [-0.58109105]],

       [[ 3.002488  ],
        [-0.27825996],
        [ 0.7989333 ],
        ...,
        [-0.34547755],
        [-0.576817  ],
        [ 0.47699323]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[ 0.7425528 ],
        [-0.88114923],
        [ 1.2816385 ],
        ...,
        [ 0.61273754],
        [-0.43834418],
        [-1.0978663 ]],

       [[-0.21802038],
        [-0.10342378],
        [-0.6027409 ],
        ...,
        [-0.09381349],
        [-2.0900886 ],
        [ 0.34896147]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[-1.4537004 ],
        [-0.23114291],
        [-0.5871747 ],
        ...,
        [ 1.7588977 ],
        [-0.64653444],
        [-0.8479624 ]],

       [[-0.8888948 ],
        [ 0.667874  ],
        [-0.11591944],
        ...,
        [ 1.5969365 ],
        [ 0.3887264 ],
        [ 2.6164393 ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[-0.71152514],
        [ 0.31899413],
        [ 0.59584296],
        ...,
        [-0.4681486 ],
        [-0.18287487],
        [-0.6718022 ]],

       [[-0.536758  ],
        [ 0.16100785],
        [ 1.1793295 ],
        ...,
        [-1.6710243 ],
        [-1.2068127 ],
        [-0.71454585]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[-1.8764349 ],
        [-0.4220016 ],
        [-0.3832036 ],
        ...,
        [ 0.396611  ],
        [ 0.4031959 ],
        [ 0.35724488]],

       [[-0.65015966],
        [ 0.2224573 ],
        [ 0.20525123],
        ...,
        [-0.45926374],
        [ 0.6471609 ],
        [ 0.3332496 ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[ 0.80413526],
        [ 1.1347907 ],
        [ 0.94075084],
        ...,
        [ 0.00755476],
        [ 0.06562049],
        [ 1.1542311 ]],

       [[-1.5574476 ],
        [ 0.69488364],
        [ 0.6990288 ],
        ...,
        [ 1.4017487 ],
        [-0.59805775],
        [-1.2751728 ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[-0.40774116],
        [-0.9957925 ],
        [ 0.7808731 ],
        ...,
        [-0.41433212],
        [ 0.5268629 ],
        [-0.9951206 ]],

       [[-1.3662847 ],
        [ 0.4806584 ],
        [-0.9774015 ],
        ...,
        [ 1.8218778 ],
        [-1.0483685 ],
        [-0.40153572]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[ 0.03537908],
        [ 0.30871132],
        [-0.43272868],
        ...,
        [ 0.78636587],
        [ 0.12341707],
        [-0.4693344 ]],

       [[ 0.08255825],
        [-1.047672  ],
        [ 0.5959074 ],
        ...,
        [-1.0461427 ],
        [-1.0181618 ],
        [ 1.9093345 ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[-0.66075665],
        [ 1.8946798 ],
        [-0.23847736],
        ...,
        [ 1.020657  ],
        [ 0.20324162],
        [ 1.6452681 ]],

       [[ 0.4298775 ],
        [-1.6225889 ],
        [-0.75322384],
        ...,
        [ 0.02752435],
        [ 1.7630118 ],
        [ 0.6711645 ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[-0.46049008],
        [-0.7228323 ],
        [ 0.49198708],
        ...,
        [-2.6658268 ],
        [ 0.5688557 ],
        [ 1.2088995 ]],

       [[-0.32607743],
        [-0.4941861 ],
        [-0.4495856 ],
        ...,
        [ 0.46143514],
        [ 0.04375907],
        [-1.2433708 ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[-2.1594412 ],
        [-1.7406673 ],
        [-0.34877333],
        ...,
        [-0.18708955],
        [-1.3062778 ],
        [ 1.0276945 ]],

       [[ 0.8192844 ],
        [ 1.2739064 ],
        [-1.1833884 ],
        ...,
        [ 0.5369094 ],
        [-1.4730651 ],
        [-0.5227384 ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[ 0.9111539 ],
        [ 1.0799477 ],
        [ 0.5658374 ],
        ...,
        [-0.05691434],
        [ 0.50694185],
        [-0.5104034 ]],

       [[-0.5456287 ],
        [ 0.5273403 ],
        [ 0.7272648 ],
        ...,
        [-0.35712332],
        [ 0.8400177 ],
        [ 1.5469983 ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[-0.02717604],
        [-2.182759  ],
        [-0.95963657],
        ...,
        [-0.1727186 ],
        [ 1.0064832 ],
        [ 1.1638952 ]],

       [[ 0.9377752 ],
        [ 0.15913202],
        [ 0.39370653],
        ...,
        [-0.26473373],
        [-0.09181631],
        [-2.8304796 ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[ 0.37767184],
        [-1.506959  ],
        [-0.28660896],
        ...,
        [-0.3206233 ],
        [ 1.5128583 ],
        [ 0.5174895 ]],

       [[ 0.23141655],
        [ 1.4028056 ],
        [-0.33944097],
        ...,
        [ 0.45577055],
        [ 1.2758701 ],
        [ 0.7810977 ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[-0.72600114],
        [ 0.75190115],
        [-0.8629814 ],
        ...,
        [-0.6400315 ],
        [ 0.45446384],
        [ 0.4231863 ]],

       [[ 0.66919667],
        [-1.4157479 ],
        [-1.7317768 ],
        ...,
        [-0.06310534],
        [ 0.3752666 ],
        [ 1.365589  ]]], dtype=float32)>, <tf.Tensor: shape=(2, 1024, 1), dtype=float32, numpy=
array([[[ 0.34559423],
        [-1.4900172 ],
        [ 0.913667  ],
        ...,
        [ 2.4927645 ],
        [-1.9354457 ],
        [-0.31414458]],

       [[-0.93749714],
        [-0.3028151 ],
        [ 0.6019532 ],
        ...,
        [-0.18828262],
        [ 0.52485734],
        [ 0.5387431 ]]], dtype=float32)>). When calling a concrete function, positional arguments may not be bound to Tensors within nested structures.
`

**Comment by amahendrakar** [comment]
@ltorlay,
While running the code I am facing an error stating `OSError: SavedModel file does not exist at: /home/xv/my-recognition-python/custom_model/MCNet_Model_30%_SNR10+/{saved_model.pbtxt|saved_model.pb}`. 

Could you please share the saved model file you are using in the code. Zip the contents of the folder, then drag and drop it in the input text box to share it. Thanks!

**Comment by ltorlay** [comment]
@amahendrakar It is now added.

**Comment by ltorlay** [comment]
Still awaiting a response on this. It's happening with different network architectures as well. I believe it is related to the input dimensions. Please direct me to help if you can @amahendrakar 

Thanks

**Comment by amahendrakar** [comment]
@ltorlay,
Sorry for the delayed response.

On running the code I am facing an error stating `Failed to get matching files on ./model/1/variables/variables: Not found: ./model/1/variables; No such file or directory`. 
Could you please share the contents of the whole parent folder including the assets and variables folder. Thanks!

**Comment by ltorlay** [comment]
> @ltorlay,
> Sorry for the delayed response.
> 
> On running the code I am facing an error stating `Failed to get matching files on ./model/1/variables/variables: Not found: ./model/1/variables; No such file or directory`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/a9e0f35e9ff58889290f1f0c7a2add10/40951-1-15.ipynb#scrollTo=smU-wOE7-VqU).
> 
> Could you please share the contents of the whole parent folder including the assets and variables folder. Thanks!

My mistake. I added the zip file with the variables included

**Comment by amahendrakar** [comment]
@ltorlay,
I was able to reproduce the issue with [TF v1.15](https://colab.research.google.com/gist/amahendrakar/b4bda2f5dfbba7aa3a57c00368091fc0/40951-1-15.ipynb) and [TF v2.2](https://colab.research.google.com/gist/amahendrakar/6ca96b2cd8dc481d9996ac1d4ef334a6/40951-2-2.ipynb). Please find the attached gist. 


Also, please take a look at these similar issues, [issue #1](https://github.com/huggingface/transformers/issues/2021) and [issue #2](https://github.com/tensorflow/tensorflow/issues/34603), and let us know if it helps. Thanks!

**Comment by ltorlay** [comment]
I have gone ahead and looked at all of it. Do you think it is more of a problem related to the batch dimensions as mentioned in [https://github.com/huggingface/transformers/issues/2021]? I don't see a clear point of action.  

Thanks!

**Comment by varunsapre** [comment]
Looking at [this solution](https://github.com/tensorflow/tensorflow/issues/34708#issuecomment-582622230), using yield instead of return worked for me.

**Comment by ltorlay** [comment]
@varunsapre I used: "yield [input]" rather than return and it worked! 
for the sake of completeness, here is my new function: 
def my_input_fn():
    num_runs=10
    for _ in range(num_runs):
        input = np.random.normal(size=(32,2,1024,1)).astype(np.float32)
        yield [input]
