### ISSUE TITLE
Plase Help!

### ISSUE THREAD

**Issue by jairforero** [tensorflow/tensorflow#40967]
package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto" in any of:
        c:\go\src\github.com\tensorflow\tensorflow\tensorflow\go\core\protobuf\for_core_protos_go_proto (from $GOROOT)
        C:\Users\JairForero\go\src\github.com\tensorflow\tensorflow\tensorflow\go\core\protobuf\for_core_protos_go_proto (from $GOPATH)

**Comment by Saduf2019** [comment]
@jairforero 
Please mention the tensor flow version on which this was encountered.
Can you refer to [this issue](https://github.com/tensorflow/tensorflow/issues/39744#issuecomment-636431128) with similar error and let us know.

**Comment by jairforero** [comment]
Thanks! I'm not sure which version I just run
go run github.com/tensorflow/tensorflow/tensorflow/go

**Comment by Saduf2019** [comment]
@jairforero 
Could you please let us know if you have referred to the issue shared, the link in above comment does not exist. please fill in the template for us to help.

**Comment by jairforero** [comment]
Thanks This problems is to 
![image](https://user-images.githubusercontent.com/57493863/86364879-5d727d80-bc3e-11ea-93bc-fbb0e1fafe93.png)

**Comment by mihaimaruseac** [comment]
Please paste the error message (using makrdown formatting around it) instead of screenshotting. Screenshots are not searchable so they don't help in looking for the issue and also don't help other people having the same error from finding about the issue.

**Comment by Saduf2019** [comment]
@jairforero
Please update as per above comment.

**Comment by jairforero** [comment]
Hi This is error
PS E:\go\jairforero\bot> go run ocr.go
E:\Go\go\src\github.com\tensorflow\tensorflow\tensorflow\go\saved_model.go:25:2: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto" in any of:
        c:\go\src\github.com\tensorflow\tensorflow\tensorflow\go\core\protobuf\for_core_protos_go_proto (from $GOROOT)
        E:\Go\go\src\github.com\tensorflow\tensorflow\tensorflow\go\core\protobuf\for_core_protos_go_proto (from $GOPATH)

**Comment by Saduf2019** [comment]
@jairforero 
Can you please follow [this comment](https://github.com/tensorflow/tensorflow/issues/34580#issuecomment-646753289) on same error faced and let us know.

**Comment by UMUTBAYGUT** [comment]
Same Error still is continues

**Comment by lifepeer** [comment]
Still the same issue present. Any idea what causes this? I've followed the official install guide to the point.
