### ISSUE TITLE
Missing "Connected to" column in model summary

### ISSUE THREAD

**Issue by MasterJEET** [tensorflow/tensorflow#40969]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04.2 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
Binary
- TensorFlow version (use command below):
v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version:
Python 3.7.3
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
N/A
- CUDA/cuDNN version:
10.2
- GPU model and memory:
TITAN X (Pascal), ~12GB

**Describe the current behavior**
`model.summary()` output is missing column `Connected to`

**Describe the expected behavior**
it should contain the column

**Standalone code to reproduce the issue**
```
import tensorflow as tf

def res_net_block(shape):
    filters = shape[-1]

    inputs = tf.keras.layers.Input(shape)
    x = tf.keras.layers.Conv3D(filters=filters, kernel_size=3, padding='same')(inputs)
    outputs = x + inputs

    return tf.keras.Model(inputs, outputs)

def encoder(shape):
    kernel_size = 3
    strides = 2

    inputs = tf.keras.layers.Input(shape)
    outputs = res_net_block(inputs.shape[1:])(inputs)

    return tf.keras.Model(inputs, outputs)

shape = [256,256,128,1]
model = encoder(shape)
model.summary()
```
Summary output looks like below:
```
Model: "model_36"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_42 (InputLayer)        [(None, 256, 256, 128, 1) 0         
_________________________________________________________________
model_35 (Model)             (None, 256, 256, 128, 1)  28        
=================================================================
Total params: 28
Trainable params: 28
Non-trainable params: 0
_________________________________________________________________
```

**Other info / logs**
Interestingly, if I move the addition out of `res_net_block` into `encoder`, display is as expected.
```
def res_net_block(shape):
    filters = shape[-1]

    inputs = tf.keras.layers.Input(shape)
    outputs = tf.keras.layers.Conv3D(filters=filters, kernel_size=3, padding='same')(inputs)

    return tf.keras.Model(inputs, outputs)

def encoder(shape):
    kernel_size = 3
    strides = 2

    inputs = tf.keras.layers.Input(shape)
    x = res_net_block(inputs.shape[1:])(inputs)
    outputs = x + inputs # This addition is not here in previous code, instead it's inside `res_net_block` function

    return tf.keras.Model(inputs, outputs)
```
Output with above function definitions:
```
Model: "model_38"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_44 (InputLayer)           [(None, 256, 256, 12 0                                            
__________________________________________________________________________________________________
model_37 (Model)                (None, 256, 256, 128 28          input_44[0][0]                   
__________________________________________________________________________________________________
tf_op_layer_AddV2_20 (TensorFlo [(None, 256, 256, 12 0           model_37[1][0]                   
                                                                 input_44[0][0]                   
==================================================================================================
Total params: 28
Trainable params: 28
Non-trainable params: 0
__________________________________________________________________________________________________
```

**Comment by amahendrakar** [comment]
@MasterJEET,
Please take a look at [this](https://stackoverflow.com/a/54465485) similar StackOverflow comment and let us know if it resolves your query. Thanks!

**Comment by MasterJEET** [comment]
I see, this makes sense. When the addition is inside the `res_net_block`, the `encoder` simply stacks one layer on top of another and is essentially a sequential like model where we can safely assume that each layer in `model.summary()` is connected to its previous layer, hence `Connected to` column would be redundant, whereas if addition is inside `encoder` it deviates from simple sequential like structure and `Connected to` column is necessary to know inter-layer connectivity.
