### ISSUE TITLE
tf.nn.log_poisson_loss missing from tf.nn

### ISSUE THREAD

**Issue by elibixby** [tensorflow/tensorflow#4097]
On Ubuntu 14.04: pip freeze is

```
funcsigs==1.0.2
mock==2.0.0
numpy==1.11.1
pbr==1.10.0
protobuf==3.0.0b2
six==1.10.0
tensorflow==0.10.0rc0
```

Trying to import tf.nn.log_poisson_loss fails

```
>>> import tensorflow as tf
>>> 'log_poisson_loss' in tf.nn.__dict__
False
>>> tf.nn.log_poisson_loss(tf.constant(1), tf.constant(1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'log_poisson_loss'
```

Looking at the source, it looks fine to me, not sure why it's missing.

**Comment by martinwicke** [comment]
That makes no sense. In nn_test it is used exactly this way (via import of tensorflow).

**Comment by martinwicke** [comment]
(I'm not saying you're wrong, I'm just confused)

**Comment by elibixby** [comment]
No I know what you mean! I replicated this bug like 6 times because I was sure I was crazy.

**Comment by vrv** [comment]
I just installed the nightly pip in a fresh virtualenv, and:

$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:110] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:110] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:110] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:110] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:110] successfully opened CUDA library libcurand.so locally
>>> tf.nn.log_poisson_loss
<function log_poisson_loss at 0x7fa705e0fde8>

So I don't know what's wrong with your install.  We've got 99+ issues but a pip ain't one.

**Comment by elibixby** [comment]
I installed `0.10.0rc0` is this not a stable release? Shouldn't this issue be tested against the release that I claimed it occurred in? 

FYI I just found another one. Fresh installation:

```
>>> 'OPTIMIZER_SUMMARIES' in tf.contrib.layers.optimizers.__dict__
False
```

**Comment by martinwicke** [comment]
That one should probably be module private. No need to use that.
@ilblackdragon what do you think?

**Comment by vrv** [comment]
Hm.  It looks like when we cherry-pick new commits into r0.10, we're not rebuilding the .whl's that go to storage.googleapis.  So yeah, this is basically fixed, but we haven't pushed out new wheels yet.  We'll work on this process in the future.

I believe r0.10 will be out of RC very soon, so this will be fixed when we push out the official release.

**Comment by elibixby** [comment]
@martinwicke best practice to avoid magic strings. Much better to say `OPTIMIZER_SUMMARIES`, which says gives me all available summaries, especially if the list of available summaries expands in the future. Or `OPTIMIZER_SUMMARIES[0], OPTIMIZER_SUMMARIES[:2]` e.g.

**Comment by martinwicke** [comment]
@vrv The RC wheels should not magically upate -- that would destroy the
notion of an RC. We could automatically make a new RCx release every time
we push (similar to nightlies), maybe.

@elibixby I would welcome a PR.

**Comment by vrv** [comment]
@martinwicke yeah, but we should be bumping up the rc number on every set of cherry-picks :).  I'm sure we'll get there

**Comment by martinwicke** [comment]
We can do that, but only as a nightly process -- it involves a bit of extra
setup, but could actually be not too bad. Basically a release job which
points to a branch (or set of branches) and updates automatically on push.
