### ISSUE TITLE
Resizing in Tensorflow Lite

### ISSUE THREAD

**Issue by AliBahri94** [tensorflow/tensorflow#40975]
Dear Tensorflow developers, 
I have got a trained model that has Conv, GlobalAveargePooling, Fully Connected, Reshape, and Deconve (upsampling) layers.  I converted the frozen graph to tflite and this model with fixed input size didn't have any errors when running but when resizing I get below error.
"Internal error: Unexpected failure when preparing tensor allocations: tensorflow/lite/kernels/kernel_util.cc:224 d1 == d2 || d1 == 1 || d2 == 1 was not true. Node number 94 (ADD) failed to prepare."
anybody can help me?
Thanks!

**Comment by amahendrakar** [comment]
@AliBahri94,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, complete code and the dataset you are using. Thanks!

**Comment by AliBahri94** [comment]
Thank you for your attention.
TensorFlow version: 1.15
convert code (.pb to .tflite):
################
graph_def_file = "address of the saved model (pb)"
input_arrays = ["model/t_lr"]
output_arrays = ["model/Generator/add_global_res"]
converter = tf.lite.TFLiteConverter.from_frozen_graph(
graph_def_file, input_arrays, output_arrays, input_shapes= {"model/t_lr" : [1, 512, 512, 3]})
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
#################

This error happened on mobile GPU  when I resize the graph.
Thanks!

**Comment by amahendrakar** [comment]
@AliBahri94,
Could you please share the `.pb` file or the code to generate the `.pb` file as well. Thanks!
