### ISSUE TITLE
importing tensorflow gives error "illegal instruction"

### ISSUE THREAD

**Issue by AnikaTabassum** [tensorflow/tensorflow#40978]
Hi.. I am trying to install tensorflow  in my python3 virtual environment.
OS- centos 7.8kvm
tensorflow installed from binary
tensorflow version 1.15.0
python version 3.6.8
installed in virtualenv  using pip with the command
`TMPDIR=/data/vincents/ pip install --cache-dir=/data/vincents/ --build /data/vincents/ tensorflow==1.15.0`
I have 2GB RAM and I am using 2GB swap memory

this is my CPU info
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 13
Model name:            QEMU Virtual CPU version 2.5+
Stepping:              3
CPU MHz:               2397.222
BogoMIPS:              4794.44
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
L3 cache:              16384K
NUMA node0 CPU(s):     0,1
Flags:                 fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl xtopology eagerfpu pni cx16 x2apic hypervisor lahf_lm

I have succeeded to install tensorflow=1.15.0, but whenever  I try to import it in a python shell in throws error
`illegal instruction`
![106207928_274334003654354_6896801223456467874_n](https://user-images.githubusercontent.com/35559892/86229455-8c8edd80-bbb1-11ea-8e2b-af699107dcd3.jpg)

DO I NEED TO UPGRADE MY SERVER TO 4CPU? OR IS THERE SOME OTHER PROBLEM?

N.B: I CANNOT SWITCH TO ANY OTHER VERSION. I NEED EXACTLY THIS VERSION

**Comment by freedomtan** [comment]
from the TensorFlow [installation guide](https://www.tensorflow.org/install/pip), you need AVX.
```
Starting with TensorFlow 1.6, binaries use AVX instructions which may not run on older CPUs.
```

**Comment by Saduf2019** [comment]
@AnikaTabassum 
Is there any particular reason to install older version of tensor flow when later versions are available.
Please refer to [this link](https://github.com/tensorflow/tensorflow/issues/40875#issuecomment-650698437) , [ this link with same error](https://github.com/tensorflow/tensorflow/issues/21969#issuecomment-417262184 ) and let us know.

**Comment by AnikaTabassum** [comment]
yes for an open source package I need to install tensorflow 1.15.0. .i cannot use any other versions.

DOES INCREASING CPUS SOLVE THIS PROBLEM?????
I AM SORRY I AM NOT AN EXPERT

**Comment by Saduf2019** [comment]
@AnikaTabassum
Can you please confirm if your cpu supports AVX,  as informed earlierplease refer to the instructions [here](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Please verify if you meet the requirements.

**Comment by AnikaTabassum** [comment]
No, my cpu Doesn't support avx. So it Doesn't matter how many cpus but if those support AVX

**Comment by AnikaTabassum** [comment]
Sorry I closed this by mistake.  So do I need to upgrade my CPU?

**Comment by Saduf2019** [comment]
@AnikaTabassum 
Can you refer to [this link](https://github.com/tensorflow/tensorflow/issues/34558#issuecomment-565150738) as it answers the issue faced.
[This comment](https://github.com/tensorflow/tensorflow/issues/36138#issuecomment-578010350) confirms the alternative for your issue.

**Comment by AnikaTabassum** [comment]
thanks for your assistance. so i have build tf from source. I am afraid I couldn't find any source of tensorflow 1.15.0
can you please assist me with the link exact version?

**Comment by mihaimaruseac** [comment]
`git switch r1.15` after you clone the repository.

**Comment by AnikaTabassum** [comment]
Hi @mihaimaruseac ! I tried this after cloning, but unfortunately got this error 
`fatal: not a git repository (or any of the parent directories): .git`
![image](https://user-images.githubusercontent.com/35559892/86284632-069c8200-bc05-11ea-99a6-7b980ba667b3.png)

**Comment by Lukious** [comment]
There was the same problem to me, but version dependencies made it difficult to solve this problem previously. I recommend you upgrading the CPU.

**Comment by freedomtan** [comment]
@AnikaTabassum `cd tensorflow` before `git switch ...`. BTW, since you are running qemu, it might be possible to turn on AVX. See [qemu menu](https://www.qemu.org/docs/master/system/target-i386.html)

**Comment by AnikaTabassum** [comment]
SO i installed bazel 0.26.1 from the linux installer, as it is the necessary version for tf 1.15 (got form the docs) with the command-
`./bazel-0.26.1-installer-linux-x86_64.sh`
Then tried to build tf 1.15 with the following command:
` bazel build --config=v1 //tensorflow/tools/pip_package:build_pip_package`

it took about one hour and I finally got this error:
`ERROR: /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/local_config_mlir/BUILD:1546:1: C++ compilation of rule '@local_config_mlir//:mlir-tblgen' fai
led (Exit 1)
gcc: error: unrecognized command line option '-std=c++14'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3239.923s, Critical Path: 89.28s
INFO: 4043 processes: 4043 local.
FAILED: Build did NOT complete successfully`

![image](https://user-images.githubusercontent.com/35559892/86328152-2dd76b80-bc66-11ea-989f-cec614b3165d.png)

**Comment by Saduf2019** [comment]
@AnikaTabassum 
Can you please let us know the gcc version, and as per error faced can you refer to [this link](https://github.com/tensorflow/tensorflow/issues/31760#issuecomment-523114446).
[link](https://github.com/tensorflow/tensorflow/issues/32677#issuecomment-534278822).

**Comment by AnikaTabassum** [comment]
gcc version 4.8.5
`gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

**Comment by mihaimaruseac** [comment]
You need `gcc 7.3.1` See https://www.tensorflow.org/install/source#cpu

**Comment by Saduf2019** [comment]
@AnikaTabassum 
Please update as per above comment.

**Comment by AnikaTabassum** [comment]
sorry, i have tried to install with gcc 7.3.1, made gcc7.3.1 as my default gcc version but unfoltunately getting the following error:
![image](https://user-images.githubusercontent.com/35559892/86457984-55056a00-bd46-11ea-9b66-128cac68716b.png)

**Comment by mihaimaruseac** [comment]
Please post the actual error message in properly formatted Markdown, not a screenshot. It is much easier to read, easy to grep for, easy to select and copy-paste in other places (search in code, create new issues, triage duplicates), easier for others to locate similar errors. Plus, not all people have all images loaded in the browser. Textual error message takes a few hundred of bytes whereas an image takes MB.

Now that that is aside, can you try `bazel clean --expunge` and then `bazel build -s ... &> log.txt` (replace `...` with all other arguments you would have used) and then **attach** `log.txt` to a reply?

**Comment by AnikaTabassum** [comment]
@mihaimaruseac I am extremely sorry for my fault.
I am attaching the log.txt file.
i gave the coomand:
`bazel build --config=v1 //tensorflow/tools/pip_package:build_pip_package &> log.txt`
and my gcc version is 7.3.1
[log.txt](https://github.com/tensorflow/tensorflow/files/4872198/log.txt)

**Comment by mihaimaruseac** [comment]
It seem you get a compile failure from the start

```
ERROR: /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/com_google_protobuf/BUILD:106:1: C++ compilation of rule '@com_google_protobuf//:protobuf_lite' failed (Exit 1)
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

What is the output of `git show`? How about the output of `git log -n=5 --format=oneline`?

**Comment by freedomtan** [comment]
Mostly, because g++ not installed.

**Comment by Saduf2019** [comment]
@AnikaTabassum 
Please update as per above comment.

**Comment by AnikaTabassum** [comment]
Hi.. so I these instructions didn't solve my issue. I had to create an anaconda environment and install tensorflow 1.15.0 there.
but thanks for all your assistance..

**Comment by pablo-blancoc** [comment]
Hi @AnikaTabassum 
I'm trying to build tensorflow from source on centOS 7. Have upgraded gcc to 5.4.0 but I see I need >7 version. Getting same errors as you. How did you make it work?

**Comment by AnikaTabassum** [comment]
I updated the gcc version but it didn't help. So I switched environment. Previously I was working in a python3 environment, I started using anaconda environment. Installed tensorflow using conda, and it's working.

**Comment by hsundt** [comment]
The reported error message has to do with that Rosetta2 (the Intel translation layer) on Apple Silicon does not emulate Intel’s AVX instructions, which are used by Tensorflow. So the Intel version of the package will not work on Apple Silicon, even when emulated. A possible solution is to follow the instructions given at https://developer.apple.com/metal/tensorflow-plugin/ to do a native ARM installation.

But this package cannot be used alongside Python libraries compiled for Intel, due to ABI incompatibility. It means that the entire project using this Tensorflow package will have to be built for ARM, as well being on the ARM branch of Conda / Python for Mac.
