### ISSUE TITLE
Import error-- OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by krn-sharma** [tensorflow/tensorflow#40974]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.2
- Python version:3.8 64 bit
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0
- GPU model and memory: RTX 2060, 6GB 

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
![tensorflow](https://user-images.githubusercontent.com/55295294/86224846-05d50300-bba7-11ea-989f-9ff087e62858.PNG)
i have installed all the requirement given in tensorflow website but keep getting this error. I have one more question- if everything is 64 bit then why it is showing win32?

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by krn-sharma** [comment]
i have install tensorflow using 'pip install tensorflow-gpu'

**Comment by krn-sharma** [comment]
i just reinstall scipy and it worked

**Comment by CristianoPatricio** [comment]
> i just reinstall scipy and it worked

Yes! It works :)
