### ISSUE TITLE
Frozen TF2.0 model to TF1.x pb model

### ISSUE THREAD

**Issue by hahadashi** [tensorflow/tensorflow#40986]
Linux, Tensorflow2.0
i also want to convert TF2.0 model() to TF1.x pb model to inference C++, but i meet another problem. please read the page [https://github.com/esdu/misc/blob/master/bug_report_lstm_freeze.ipynb], i get same problem, 
if use keras.layers.GruCell i whill get "tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 7 of node prefix/out_model/rnn/while was passed float from prefix/rnn/bias:0 incompatible with expected resource."
if use keras.layers.GruCell i whill get "ValueError: Input 0 of node import/lstm/while/ReadVariableOp/Enter was passed float from import/lstm/kernel:0 incompatible with expected resource."

**Comment by ravikyram** [comment]
@hahadashi 

I have tried in colab with TF 2.2 .Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/0841e741547600d63017049f7e4c1d2c/untitled64.ipynb).You are seeing the same behavior?.Thanks!

**Comment by hahadashi** [comment]
> @hahadashi
> 
> I have tried in colab with TF 2.2 .Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/0841e741547600d63017049f7e4c1d2c/untitled64.ipynb).You are seeing the same behavior?.Thanks!

yes. 
in my another demo code,  i try to use keras.layers.GruCell，i get error message "ValueError: Input 0 of node import/lstm/while/ReadVariableOp/Enter was passed float from import/lstm/kernel:0 incompatible with expected resource.". i think there are similar bug when we want to frozen keras.layers.GruCell or keras.layers.LstmCell to pb. please give some advice to fix these problem. thxs

**Comment by qlzh727** [comment]
Sorry for the long wait. I am not sure if this is a LSTM problem, or a graph conversion problem. Assigning to @gargn from tf-lite team.
