### ISSUE TITLE
breakpoints not working in tf_ios_makefile_example

### ISSUE THREAD

**Issue by jeffxtang** [tensorflow/tensorflow#4098]
### Environment info
Operating System: OS X El Capitan
Xcode v7.3.1

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
I'm able to build and the run the tf_ios_makefile_example according to https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/ios_examples but while debugging the app, the breakpoints I set in the app (RunModelViewController.mm even in AppDelegate.mm) doesn't work - NSLog statements next to the breakpoints work fine. 

Anyone has the problem? Any solutions or ideas? Thanks!

### What other attempted solutions have you tried?
I verified new Xcode project or other existing Xcode projects work fine with pause at set breakpoints. I also Googled "xcode 7 breakpoints not working" but didn't see helpful info. I noticed 
the line CFLAGS="-DNDEBUG..." in compile_ios_protobuf.sh but am not sure if it's the cause.

**Comment by petewarden** [comment]
If you look at the "Other Linker Flags" section of your Xcode settings, you should see several settings. If you remove 
`
-Xlinker
-S
-Xlinker
-x
-Xlinker
-dead_strip
`
you should see more symbols when you run your app, and so find it easier to set breakpoints.

**Comment by jeffxtang** [comment]
After I removed `-Xlinker -S -Xlinker -x -Xlinker -dead_strip` I got linker errors: `Undefined symbols for architecture x86_64: "_deflate", reference from: tensorflow::io::ZliboutputBuffer::Deflate(int) in libtensorflow-core.a`... Are those -Xlinker settings optional for building the app?

**Comment by jackflips** [comment]
@jeffxtang You can get rid of those errors by linking with libz. Add libz.1.2.5.tbd in Link Binary with Libraries.

**Comment by jeffxtang** [comment]
Thanks @jackflips! It works like a charm! Sorry for my late response - I just came back from a 2-week trip and tested it.
