### ISSUE TITLE
properly setting up and compiling in windows with tensorflow c api

### ISSUE THREAD

**Issue by LJWxyz** [tensorflow/tensorflow#40987]
https://www.tensorflow.org/install/lang_c

Add,window eg with at least mingw or cmake,or simply from cmd line/*terminal* with gcc/g++?

For example, why should someone use this method? How is it useful?
Well,you see i wanted to make sure when I use it in production in the years to come I can make sure.
I as an individual can make it work even if I am stranded on an island with no internet.
With probably only a disk filled with backup of binaries and backup of OS in iso.etc. 

Is the link to the source code correct?yes

Are all parameters defined and formatted correctly?yes

Are return values defined?yes

I need help in getting it to work.After getting it to work. Then ,well I will contribute respectively.

My trial,as known we need to setup path point to the compiler path/*area.Then we declare lib included files right?
Then we go to source code,take all bam,compiled piece of essence.

Below is my attempt.well second attempt

D:\Coding\C\ALLCinone>set PATH=D:\Coding\C\ALLCinone\MinGW64\bin;D:\Coding\C\ALLCinone\MinGW64\x86_64-w64-mingw32\bin;C:\Windows\system32;C:\Windows;(Bloated Winapps path don't need to bother)

D:\Coding\C\ALLCinone>cmd /k"set includepath=E:\Coding\C\WinGW\include;E:\Coding\C\WinGW\msys\1.0\include"

D:\Coding\C\ALLCinone>cd D:\Coding\C\3rdpartylib\libtensorflow-gpu-windows-x86_64-\include

D:\Coding\C\3rdpartylib\libtensorflow-gpu-windows-x86_64-\include>set includepath=%includepath%;%cd%

D:\Coding\C\3rdpartylib\libtensorflow-gpu-windows-x86_64-\include>cd D:\Coding\C\ljwversrccodes\testtensorflow\test2

D:\Coding\C\ljwversrccodes\testtensorflow\test2>gcc hello_tf.c -l"%includepath%" -o hello_tf
hello_tf.c:2:32: fatal error: tensorflow/c/c_api.h: No such file or directory
 #include <tensorflow/c/c_api.h>
                                ^
compilation terminated.

D:\Coding\C\ljwversrccodes\testtensorflow\test2>%includepath%
The system cannot find the drive specified.

D:\Coding\C\ljwversrccodes\testtensorflow\test2>echo %includepath%
E:\Coding\C\WinGW\include;E:\Coding\C\WinGW\msys\1.0\include;D:\Coding\C\3rdpartylib\libtensorflow-gpu-windows-x86_64-\include

D:\Coding\C\ljwversrccodes\testtensorflow\test2>cd D:\Coding\C\3rdpartylib\libtensorflow-gpu-windows-x86_64-\include\tensorflow

D:\Coding\C\3rdpartylib\libtensorflow-gpu-windows-x86_64-\include\tensorflow>set includepath=%includepath%;%cd%

D:\Coding\C\3rdpartylib\libtensorflow-gpu-windows-x86_64-\include\tensorflow>cd D:\Coding\C\3rdpartylib\libtensorflow-gpu-windows-x86_64-\include\tensorflow

D:\Coding\C\3rdpartylib\libtensorflow-gpu-windows-x86_64-\include\tensorflow>cd D:\Coding\C\ljwversrccodes\testtensorflow\test2

D:\Coding\C\ljwversrccodes\testtensorflow\test2>gcc hello_tf.c -l"%includepath%" -o hello_tf
hello_tf.c:2:32: fatal error: tensorflow/c/c_api.h: No such file or directory
 #include <tensorflow/c/c_api.h>
                                ^
compilation terminated.

D:\Coding\C\ljwversrccodes\testtensorflow\test2>gcc hello_tf.c -L"%includepath%" -o hello_tf
hello_tf.c:2:32: fatal error: tensorflow/c/c_api.h: No such file or directory
 #include <tensorflow/c/c_api.h>
                                ^
compilation terminated.

D:\Coding\C\ljwversrccodes\testtensorflow\test2>g++ hello_tf.c -L"%includepath%" -o hello_tf
hello_tf.c:2:32: fatal error: tensorflow/c/c_api.h: No such file or directory
 #include <tensorflow/c/c_api.h>
                                ^
compilation terminated.

D:\Coding\C\ljwversrccodes\testtensorflow\test2>g++ hello_tf.c -I"%includepath%" -o hello_tf
hello_tf.c:2:32: fatal error: tensorflow/c/c_api.h: No such file or directory
 #include <tensorflow/c/c_api.h>
                                ^
compilation terminated.

D:\Coding\C\ljwversrccodes\testtensorflow\test2>g++ hello_tf.c -I%includepath% -o hello_tf
hello_tf.c:2:32: fatal error: tensorflow/c/c_api.h: No such file or directory
 #include <tensorflow/c/c_api.h>
                                ^
compilation terminated.

D:\Coding\C\ljwversrccodes\testtensorflow\test2>g++ hello_tf.c -I%includepath% -o hello_tf
hello_tf.c:2:32: fatal error: tensorflow/c/c_api.h: No such file or directory
 #include <tensorflow/c/c_api.h>
                                ^
compilation terminated.

D:\Coding\C\ljwversrccodes\testtensorflow\test2>g++ hello_tf.c -I %includepath% -o hello_tf
hello_tf.c:2:32: fatal error: tensorflow/c/c_api.h: No such file or directory
 #include <tensorflow/c/c_api.h>
                                ^
compilation terminated.

D:\Coding\C\ljwversrccodes\testtensorflow\test2>#(someone please save me from this hell.w)

**Comment by LJWxyz** [comment]
test3:

D:\Coding\C\ALLCinone>set PATH=D:\Coding\C\ALLCinone\MinGW64\bin;D:\Coding\C\ALLCinone\MinGW64\x86_64-w64-mingw32\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Users\kami\AppData\Local\Microsoft\WindowsApps;

D:\Coding\C\ALLCinone>cmd /k"set includepath=D:\Coding\C\ALLCinone\MinGW64\include;D:\Coding\C\ALLCinone\cmake-3.17.1\Utilities"

D:\Coding\C\ALLCinone>d D:\Coding\C\3rdpartylib\libtensorflow-gpu-windows-x86_64-\include
'd' is not recognized as an internal or external command,
operable program or batch file.

D:\Coding\C\ALLCinone>cd D:\Coding\C\3rdpartylib\libtensorflow-gpu-windows-x86_64-\include

D:\Coding\C\3rdpartylib\libtensorflow-gpu-windows-x86_64-\include>set includepath=%includepath%;%cd%

D:\Coding\C\3rdpartylib\libtensorflow-gpu-windows-x86_64-\include>cd D:\Coding\C\ljwversrccodes\testtensorflow\v3

D:\Coding\C\ljwversrccodes\testtensorflow\v3>gcc hello_tf.c -ltensorflow -o hello_tf
hello_tf.c:2:32: fatal error: tensorflow/c/c_api.h: No such file or directory
 #include <tensorflow/c/c_api.h>
                                ^
compilation terminated.

D:\Coding\C\ljwversrccodes\testtensorflow\v3>gcc hello_tf.c -ltensorflow -o hello_tf
hello_tf.c:2:32: fatal error: tensorflow/c/c_api.h: No such file or directory
 #include <tensorflow/c/c_api.h>
                                ^
compilation terminated.

D:\Coding\C\ljwversrccodes\testtensorflow\v3>gcc hello_tf.c -l%includepath% -o hello_tf
hello_tf.c:2:32: fatal error: tensorflow/c/c_api.h: No such file or directory
 #include <tensorflow/c/c_api.h>
                                ^
compilation terminated.

D:\Coding\C\ljwversrccodes\testtensorflow\v3>gcc hello_tf.c -L%includepath% -o hello_tf
hello_tf.c:2:32: fatal error: tensorflow/c/c_api.h: No such file or directory
 #include <tensorflow/c/c_api.h>
                                ^
compilation terminated.

D:\Coding\C\ljwversrccodes\testtensorflow\v3>gg.

**Comment by Saduf2019** [comment]
@LJWxyz 
Appologies for delayed response, could you please check [this comment](https://github.com/tensorflow/tensorflow/issues/41362#issuecomment-658301003) according to which this issue is resolved.
