### ISSUE TITLE
_MklSoftmax 2-2.5x Slower in 1.15 Compared to 1.14 and 1.13

### ISSUE THREAD

**Issue by pks** [tensorflow/tensorflow#40989]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `intelaipg/intel-optimized-tensorflow:1.14.0-mkl-py3` and `intelaipg/intel-optimized-tensorflow:1.15.2-mkl-py3`
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): see OS
- Python version: 3.6
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
We found that the `_MklSoftmax` operation is quite a bit slower in 1.15 than it was in Tf 1.13 and 1.14, about 2-2.5x worse. 

**Describe the expected behavior**
Comparable speed to previous versions.

**Standalone code to reproduce the issue**
n/a but confirmed by @NeoZhangJianyu (see https://github.com/tensorflow/tensorflow/issues/39851#issuecomment-652150250)

**Other info / logs**
n/a

**Comment by ravikyram** [comment]
@pks 

Will it be possible to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by pks** [comment]
We found that in our implementation of a Transformer model, which I unfortunately cannot share. @NeoZhangJianyu said that he could reproduce it. He could possibly add a minimal example.

**Comment by NeoZhangJianyu** [comment]
@ravikyram @pks 
Yes, I have reproduced the issue.
I have reported this issue to dev team. The checking is ongoing.

Thank you!

**Comment by pks** [comment]
@NeoZhangJianyu Is there any progress on this?

**Comment by NeoZhangJianyu** [comment]
@pks It's still on going. I will push to confirm and fix.

**Comment by NeoZhangJianyu** [comment]
@pks 
We got the answer from dev team:

The TF 1.15 uses the mkldnn 0.20 version, which will run new path (avx512 impl on CLX or SKX), while TF 1.14 with 0.18 mkldnn will run a reference implementation.

The new path will take much more time for primitive creating than the latter path. 
It's the root cause why we have poor performance for SoftMax on TF 1.15, especially for small problem size.

And TF master branch has enabled the primitive cache for SoftMax, so there's no such performance issue.

This issue has been fixed in TF 2.2.0 and later. Please use TF 2.2.0 and later.
We can't port this new feature back to TF 1.15 because Google has cut off the updates for that branch.

**Comment by rohan100jain** [comment]
Thanks a lot for the investigation! Closing this issue for now.

**Comment by pks** [comment]
@NeoZhangJianyu That's unfortunate, since the softmax is a pretty central operation in neural networks (especially Transformers).

What about machines that do not have AVX-512 extensions (Haswell?), will those run the reference implementation? And is there a way to enable the primitive cache when building Tensorflow from source? Switching to Tensorflow 2 is a longer endeavor if one wants to directly run graphs.

**Comment by NeoZhangJianyu** [comment]
@pks 
For the machine without AVX-512, the issue is present too: it uses AVX2.
I will check for any work around and feedback later.

Additional, it's recommended to upgrade to Tf 2.x. 
For TF 1.15: `This is the last 1.x release for TensorFlow. We do not expect to update the 1.x branch with features, although we will issue patch releases to fix vulnerabilities for at least one year.` -- refer to https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md

**Comment by NeoZhangJianyu** [comment]
@pks
I checked with the designer. There is no simple way to merge back the solution from TF 2.x to TF 1.15.

**Comment by pks** [comment]
@NeoZhangJianyu Alright, thanks for checking!

**Comment by NeoZhangJianyu** [comment]
@pks There is solution for this issue now.
Intel release a special version: Intel TF 1.15.0up1 today. It includes many bugs fix of TF2.x.
I have tested the MKLSoftmax issue. The performance is increased than 1.15 in small size (like 1000).  Note, all of releases have same performance in big size (like 100,000).

But it is still not same as TF 1.14.
TF 2.2.0-MKL is with same performance of TF 1.14.

Please build it from source code by following guide:
```
$ git clone https://github.com/Intel-tensorflow/tensorflow.git  
$ git checkout v1.15.0up1

bazel build --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 --copt=-O3 --copt=-Wformat --copt=-Wformat-security --copt=-fstack-protector --copt=-fPIC --copt=-fpic --linkopt=-znoexecstack --linkopt=-zrelro --linkopt=-znow --linkopt=-fstack-protector --config=mkl --define build_with_mkl_dnn_v1_only=true --copt=-DENABLE_INTEL_MKL_BFLOAT16 --copt=-march=native //tensorflow/tools/pip_package:build_pip_package 

./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

pip install /tmp/tensorflow_pkg/tensorflow-xxx-xxx.whl
```

**Comment by pks** [comment]
Thanks @NeoZhangJianyu! Unfortunately I don't seem to be able to build the wheel from this branch:
```
> bazel build --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 --copt=-O3 --copt=-Wformat --copt=-Wformat-security --copt=-fstack-protector --copt=-fPIC --copt=-fpic --linkopt=-znoexecstack --linkopt=-zrelro --linkopt=-znow --linkopt=-fstack-protector --config=mkl --define build_with_mkl_dnn_v1_only=true --copt=-DENABLE_INTEL_MKL_BFLOAT16 --copt=-march=native //tensorflow/tools/pip_package:build_pip_package

Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=127
INFO: Reading rc options for 'build' from ~/intel_tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include
INFO: Found applicable config definition build:mkl in file ~/intel_tensorflow/.bazelrc: --define=build_with_mkl=true --define=enable_mkl=true --define=tensorflow_mkldnn_contraction_kernel=0 --define=build_with_mkl_dnn_v1_only=true --copt=-DENABLE_INTEL_MKL_BFLOAT16 -c opt
WARNING: ~/intel_tensorflow/tensorflow/core/BUILD:1091:11: in linkstatic attribute of cc_library rule //tensorflow/core:framework_lite: setting 'linkstatic=1' is recommended if there are no object files
WARNING: ~/intel_tensorflow/tensorflow/core/BUILD:2428:11: in linkstatic attribute of cc_library rule //tensorflow/core:lib_internal: setting 'linkstatic=1' is recommended if there are no object files
ERROR: ~/intel_tensorflow/tensorflow/core/common_runtime/eager/BUILD:277:11: in nocopts attribute of cc_library rule //tensorflow/core/common_runtime/eager:mkl_eager_op_rewrite: This attribute was removed. See https://github.com/bazelbuild/bazel/issues/8706 for details.
ERROR: ~/tf115/intel_tensorflow/tensorflow/core/common_runtime/eager/BUILD:277:11: in nocopts attribute of cc_library rule //tensorflow/core/common_runtime/eager:mkl_eager_op_rewrite: This attribute was removed. See https://github.com/bazelbuild/bazel/issues/8706 for details.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed
INFO: Elapsed time: 13.751s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (402 packages loaded, 17775 targets configured)
    Fetching @llvm; Restarting.
```

This seems to be a problem with bazel. Which version should I be using?
```
> bazel --version
bazel 3.4.1
```

**Comment by NeoZhangJianyu** [comment]
@pks My bazel is 3.1.0.

There is binary release now, please install the TF 1.15.0up1 by PIP:
`pip install https://storage.googleapis.com/intel-optimized-tensorflow/intel_tensorflow-1.15.0up1-cp36-cp36m-manylinux2010_x86_64.whl `

**Comment by NeoZhangJianyu** [comment]
@pks It's great news! 👍 
Thank you support!

**Comment by pks** [comment]
@NeoZhangJianyu Which is the earliest CPU generation the wheel will work with?

**Comment by NeoZhangJianyu** [comment]
@pks
It will work well with the CPU supports AVX2 & AVX512. AVX512 could speed up more.
The info could be searched in https://ark.intel.com/content/www/us/en/ark.html#@Processors

**Comment by NeoZhangJianyu** [comment]
@pks 
Hi,
   It's great to know TF 1.15.0up1 to fix your issue.
  
   I want to collect the customer to expect/use TF 1.15.0up1.
   Could you share your company name to me?
   You could send to my email: jianyu.zhang@intel.com.

   Thank you!
