### ISSUE TITLE
.pb object detection model with 1 output tensor conversion to 4 output tensors

### ISSUE THREAD

**Issue by Iorek73** [tensorflow/tensorflow#40999]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10, build 7601: SP1
& Linux 16.04 guest
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
[Google Coral Edge Dev Board
](https://coral.ai/products/dev-board/)- TensorFlow installed from (source or binary):
Pip
- TensorFlow version:
2.3.0-dev20200620
- Python version: 3.7
- Installed using virtualenv? pip? conda?: Pip
- Bazel version (if compiling from source): N/A 
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A CPU only
- GPU model and memory: N/A CPU only

-------------------------------------------------------------------------------------------------------------------------

**Describe the problem**
This problem is somewhat related to comment [#547708153](https://github.com/tensorflow/tensorflow/issues/33774#issuecomment-547708153) and subsequent answers.

Using Microsoft Azure CustomVision (as in above issue), I trained and labelled a tensorflow object detection model. Azure allows you to download this object detection model directly to .pb or .tflite. 

The output of the .pb object detection model looks like this:
![pzN0L](https://user-images.githubusercontent.com/14267992/86273918-ef2aae00-bb9e-11ea-965f-057c216d2c20.png)

This appears to be a single output tensor model on an object detection model. How does one convert to 4 output tensors as required by mobile devices?

-------------------------------------------------------------------------------------------------------------------------

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Attempting to convert to .tflite with tflite_convert and quantization (note --enable_v1_converter flag enabled as per the answers in the above thread)
```
python tflite_convert.py \
--output_file=model.tflite \
--graph_def_file=model.pb \
--enable_v1_converter \
--inference_type=QUANTIZED_UINT8 \
--input_shapes=1,416,416,3  \
--input_arrays=Placeholder \
--output_arrays=model_outputs \
--mean_values=128 \
--std_dev_values=128 \
--allow_custom_ops \
--change_concat_input_ranges=false \
--allow_nudging_weights_to_use_fast_gemm_kernel=true
```

This command creates a model.tflite. The tensor output of this .tflite is identical to the tensor in the .pb file above

The rest of this works, but for repeatability purposes I will continue. I then drag this .tflite into the guest linux account and push it onto the Edge device
`mdt push model.tflite`

The .tflite is now on the Coral Edge board, so I set it up to run
```
export DEMO_FILES="/usr/lib/python3/dist*/edgetpu/demo"
sudo cp model.tflite DEMO_FILES

export DISPLAY=:0 && edgetpu_detect \
-- source /dev/video1:YUY2:1280x720:20/1 \
--model ${DEMO_FILES}/model.tflite
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Coral Edge Output confirms only one tensor (the ValueError is noted in their [docs](https://coral.ai/docs/reference/edgetpu.detection.engine/))
```
INFO: Initialized TensorFlow Lite runtime.
Traceback (most recent call last):
  File "/usr/bin/edgetpu_detect", line 11, in <module>
    load_entry_point('edgetpuvision==1.0', 'console_scripts', 'edgetpu_detect')()
  File "/usr/lib/python3/dist-packages/edgetpuvision/detect.py", line 207, in main
    run_app(add_render_gen_args, render_gen)
  File "/usr/lib/python3/dist-packages/edgetpuvision/apps.py", line 70, in run_app
    display=args.displaymode):
  File "/usr/lib/python3/dist-packages/edgetpuvision/gstreamer.py", line 240, in run_gen
    inference_size = render_overlay_gen.send(None)  # Initialize.
  File "/usr/lib/python3/dist-packages/edgetpuvision/detect.py", line 144, in render_gen
    engines, titles = utils.make_engines(args.model, DetectionEngine)
  File "/usr/lib/python3/dist-packages/edgetpuvision/utils.py", line 53, in make_engines
    engine = engine_class(model_path)
  File "/usr/lib/python3/dist-packages/edgetpu/detection/engine.py", line 77, in __init__
    'This model has {}.'.format(output_tensors_sizes.size)))
ValueError: Dectection model should have 4 output tensors!This model has 1.
```

And finally, personally I have used Google's AutoML vision to train a model and push it onto the Edge device. The output of the AutoML looks like the following. This output (4 tensors) works on the Edge device. 

![Hzl6A](https://user-images.githubusercontent.com/14267992/86274029-108b9a00-bb9f-11ea-8cea-629093a2d49a.png)

Many thanks for any ideas!

**Comment by amahendrakar** [comment]
@Iorek73,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and a link to the object detection model you are using. 

Also, please take a look at [this link](https://www.tensorflow.org/lite/models/object_detection/overview#customize_model) to customize your model and let us know if it helps. Thanks!

**Comment by Iorek73** [comment]
Here's a [link ](https://drive.google.com/file/d/1H_zWdvPjK7idA7IA467sv1DXphH2pBiz/view?usp=sharing)to the model. Since it was trained directly using Azure CustomVision.ai there was no code required to build it. Drop images, label, train, export. All the following code is above the OP.

**Comment by re0saya** [comment]
@Iorek73 
Hello, is that model exported from Azure cannot be used in mobile? So I have to retrain the model using Google's AutoML vision right?

**Comment by Iorek73** [comment]
Hi @re0saya , no the model is trained with Azure and should be usable for mobile but is not. The key point is a I don't want to train it with AutoML (I know AutoML works but I don't want to use it).

**Comment by amahendrakar** [comment]
> Here's a [link ](https://drive.google.com/file/d/1H_zWdvPjK7idA7IA467sv1DXphH2pBiz/view?usp=sharing)to the model.

@Iorek73,
I do not have access to the link. Could you please grant the required permissions or share the file here on GitHub, so that we can look into this. Thanks!

**Comment by Iorek73** [comment]
Hi @amahendrakar , sorry, the file was too large (>25MB for github). Please try again.
