### ISSUE TITLE
SavedModel file does not exist at: ‪ try.h5/{saved_model.pbtxt|saved_model.pb}

### ISSUE THREAD

**Issue by yash88600** [tensorflow/tensorflow#40991]
Hi, I am trying to load a saved model using load_model('path') but i am getting the following error :

**SavedModel file does not exist at: ‪C:\Users\YASH\try.h5/{saved_model.pbtxt|saved_model.pb}**
The path provided is correct.
i see the same issue raises at #22480 but the solutions provided there didn't worked for me.

system info:
OS: windows 10
python version : '3.7.7'
tensorflow version :  '2.2.0' 

here is a simpler version of code : 
from tensorflow.keras.applications.vgg16 import VGG16
model = VGG16(weights='imagenet', include_top=True)
model.save('try.h5')

after saving it when i tried to load it again using the following code:
mod = load_model('‪C:\\Users\\YASH\\try.h5')
i got the following error:

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-9-455ec8db1264> in <module>
----> 1 mod = load_model('‪C:\\Users\\YASH\\try.h5')

~\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\keras\saving\save.py in load_model(filepath, custom_objects, compile)
    187       filepath = str(filepath)
    188     if isinstance(filepath, six.string_types):
--> 189       loader_impl.parse_saved_model(filepath)
    190       return saved_model_load.load(filepath, compile)
    191 

~\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\saved_model\loader_impl.py in parse_saved_model(export_dir)
    111                   (export_dir,
    112                    constants.SAVED_MODEL_FILENAME_PBTXT,
--> 113                    constants.SAVED_MODEL_FILENAME_PB))
    114 
    115 

OSError: SavedModel file does not exist at: ‪C:\Users\YASH\try.h5/{saved_model.pbtxt|saved_model.pb}

**Comment by Saduf2019** [comment]
@yash88600 
Please share the code for us to replicate the issue faced, or is possible share colab gist with the code and error faced.

**Comment by yash88600** [comment]
i have already mentioned the code above.
i have trained a model few months back, now when i tried to load it using load_model() i am getting the mentioned error.

so i tried a simple code :
from tensorflow.keras.applications.vgg16 import VGG16
model = VGG16(weights='imagenet', include_top=True)
model.save('try.h5')

after saving it, i tried to load it again using the following code:
mod = load_model('‪C:\\Users\\YASH\\try.h5')

but i am getting the mentioned error in this code too.

**Comment by gowthamkpr** [comment]
@yash88600 Without reproducing this issue, its hard for us to debug it. Please provide us the full reproducible code for us to reproduce this issue.Thanks!

**Comment by yash88600** [comment]
Hey,
i got the issue resolved but recreating the TensorFlow environment.
Thanks for the help!

**Comment by rishabhs-s** [comment]
Hi, I am trying to load a saved model using load_model('path') but i am getting the following error :

 
 File "F:\anaconda\envs\facerecog\lib\site-packages\tensorflow\python\keras\saving\save.py", line 189, in load_model
    loader_impl.parse_saved_model(filepath)
  File "F:\anaconda\envs\facerecog\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 113, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: ferlatest.h5/{saved_model.pbtxt|saved_model.pb}

(facerecog) E:\Face-Recog-update>

**Comment by MangalamPalod** [comment]
> Hey,
> i got the issue resolved but recreating the TensorFlow environment.
> Thanks for the help!

Could you please elaborate?

**Comment by yekm** [comment]
File "/home/birds/birdpred/pred.py", line 31, in <module>
    model_yn1 = tf.keras.models.load_model('./yn1_model.h5')
  File "/usr/lib/python3.9/site-packages/tensorflow/python/keras/saving/save.py", line 186, in load_model
    loader_impl.parse_saved_model(filepath)
  File "/usr/lib/python3.9/site-packages/tensorflow/python/saved_model/loader_impl.py", line 110, in parse_saved_model
    raise IOError("SavedModel file does not exist at: %s/{%s|%s}" %
OSError: SavedModel file does not exist at: ./yn1_model.h5/{saved_model.pbtxt|saved_model.pb}

`/usr/lib/python3.9/site-packages/tensorflow/python/keras/saving/save.py`:
```
    if (h5py is not None and (
        isinstance(filepath, h5py.File) or h5py.is_hdf5(filepath))):
      return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
```

for me `h5py is None` because 2.10.0 is broken after recent archlinux update. New version (3.1.0) does not work because of #44467

**Comment by Haris33-coder** [comment]
> Hey,
> i got the issue resolved but recreating the TensorFlow environment.
> Thanks for the help!

How did you resolve it? I am facing the same issue.

**Comment by anki-xyz** [comment]
I was just searching for solving this error.

## The issue

I have two scripts, `batch.py` and `analysis.py` - in  `analysis.py` I do the following (roughly) inside of a class:

        class A:
              def do(self, model_fn, images):
                   from tensorflow.keras.models import load_model
                   print(model_fn, os.path.exists(model_fn)) # True --> Exists!!!
                   model = load_model(model_fn, compile=False)
                   ....

In `batch.py` I am doing then the following:

    a = A()
    a.do(model_fn, images)

This gives me the following error:

    OSError: SavedModel file does not exist at: C:\Path\To\File\model.h5\{saved_model.pbtxt|saved_model.pb}

## Solving the issue

In `batch.py`, I just import

    import tensorflow as tf

at the beginning of the script, and et voila, it works like a charm!
I think this is what @yash88600 was talking about.
