### ISSUE TITLE
Run micro speech example on Apollo 2

### ISSUE THREAD

**Issue by uf19414** [tensorflow/tensorflow#40992]
Sorry to bother you.

I tried to run micro speech example provided by Tensorflow Lite on Apollo 2 blue EVB but failed.

Once I load this code, the function failed.

![image](https://user-images.githubusercontent.com/61425756/86256122-d5459700-bbaf-11ea-9619-417071056778.png)

I would like to ask if Apollo 2 blue has C++11 compatibility.

Or could you tell me why this happen?

Thank you!

**Comment by Saduf2019** [comment]
@uf19414 
Please share the tensorflow version and simple indented stand alone code to replicate the  issue or if possible share a colab gist with error to analyse.

**Comment by uf19414** [comment]
> @uf19414
> Please share the tensorflow version and simple indented stand alone code to replicate the issue or if possible share a colab gist with error to analyse.

The tensorflow version is 2.0. 

![image](https://user-images.githubusercontent.com/61425756/86383191-f37dc680-bc85-11ea-9207-e28123d75b70.png)


There is not  error when debugging and the model could run normally when simulating.

But when I load the Tensorflow code to Apollo 2 blue EVB, the LEDs dont flash.

I tried deleting the "Tensoflow CNN" to check other function. LED parts and Deep sleep parts can work without Tensorflow CNN parts.

Therefore I guess there must be something wrong with CNN. But I dont know how to correct it.

Could you tell me why this happen? Thank you!

Here is the whole code.

![image](https://user-images.githubusercontent.com/61425756/86382874-d77a2500-bc85-11ea-91d2-688423be42b5.png)
