### ISSUE TITLE
Build Error Keeps Coming

### ISSUE THREAD

**Issue by vyraun** [tensorflow/tensorflow#4099]
vyraun@vyraun:~/tensorflow$ bazel build //tensorflow/examples/android:tensorflow_demo
WARNING: Bazel Android NDK crosstools are based on Android NDK revision 11. The revision of the Android NDK given in android_ndk_repository rule 'androidndk' is '12.1.2977051'.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/debug:debug_graph_utils.cc' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/debug:debug_graph_utils.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:avgpooling_op.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:bounds_check.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_activations.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_attention.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_backward_cuboid_convolutions.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_backward_spatial_convolutions.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_cuboid_convolution.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_patch_3d.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_pooling.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_softmax.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_spatial_convolutions.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:maxpooling_op.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:ops_util.cc' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:ops_util.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:pooling_ops_common.cc' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:pooling_ops_common.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/ctc:ctc_beam_entry.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/ctc:ctc_beam_scorer.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/ctc:ctc_beam_search.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/ctc:ctc_decoder.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/vyraun/tensorflow/tensorflow/core/BUILD:646:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/ctc:ctc_loss_util.h' directly. You should either move the file to this package or depend on an appropriate rule there.
INFO: Found 1 target...
ERROR: missing input file '@androidsdk//:build-tools/23.0.1/aapt'.
ERROR: /home/vyraun/.cache/bazel/_bazel_vyraun/b219210c52a294104956e4ed70d84022/external/androidsdk/BUILD:5:1: @androidsdk//:aapt_binary: missing input file '@androidsdk//:build-tools/23.0.1/aapt'.
Target //tensorflow/examples/android:tensorflow_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/vyraun/.cache/bazel/_bazel_vyraun/b219210c52a294104956e4ed70d84022/external/androidsdk/BUILD:5:1 1 input file(s) do not exist.
INFO: Elapsed time: 2.821s, Critical Path: 0.03s
vyraun@vyraun:~/tensorflow$ bazel clean
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
vyraun@vyraun:~/tensorflow$ bazel build //tensorflow/examples/android:tensorflow_demo
ERROR: no such package '@androidndk//': Could not read RELEASE.TXT in Android NDK: /home/vyraun/.cache/bazel/_bazel_vyraun/b219210c52a294104956e4ed70d84022/external/androidndk/ndk/RELEASE.TXT (No such file or directory).
ERROR: no such package '@androidndk//': Could not read RELEASE.TXT in Android NDK: /home/vyraun/.cache/bazel/_bazel_vyraun/b219210c52a294104956e4ed70d84022/external/androidndk/ndk/RELEASE.TXT (No such file or directory).
INFO: Elapsed time: 2.406s

I tried changing the api levels in workspace. Didn't work. I do not have any folder for 23.0.1 in my build-tools directory. I guess there is some configuration issue. How could I resolve them? Thanks for your help.

**Comment by martinwicke** [comment]
Pete, help with Android build?

**Comment by vyraun** [comment]
Hi, thanks for the reply. I had to change the workspace SDK to my own
version 24.0.2 and then it worked.
