### ISSUE TITLE
About tf.slim ，Any plan to release pretrained checkpoint?

### ISSUE THREAD

**Issue by LinJM** [tensorflow/tensorflow#4100]
About tf.contrib. slim ，Any plan to release pretrained checkpoint?

**Comment by sguada** [comment]
Inception v3 and many other networks are available using the new TF-Slim at
[TF-Slim Image Models](https://github.com/tensorflow/models/tree/master/slim)

**Comment by sguada** [comment]
Check the blog post
https://research.googleblog.com/2016/08/tf-slim-high-level-library-to-define.html
