### ISSUE TITLE
tf.where doc on Args "x" seems incorrect

### ISSUE THREAD

**Issue by Chenni** [tensorflow/tensorflow#41005]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/api_docs/python/tf/where#args_1

## Description of issue (what needs changing):
For Args "x".
Original:
If provided, a Tensor which is of the same type as y, and has a shape broadcastable with condition and y.
Should be:
If provided, a Tensor which is of the same type as **x**, and has a shape broadcastable with condition and y.

**Comment by aavishkarmishra** [comment]
@amahendrakar I would like to work on this issue

**Comment by aavishkarmishra** [comment]
Can you help, how to edit that as in api_def of where visibility is set to hidden.

**Comment by aavishkarmishra** [comment]
@jvishnuvardhan will you please help me with this?

**Comment by mihaimaruseac** [comment]
`x` and `y` are two tensors. On the description of `x` we are saying that `x` has the same type as the `y` tensor.

**Comment by Chenni** [comment]
Thanks for the update. In that case, it looks like the document problem is with "y".

Original:
y | If provided, a Tensor which is of the same type as y, and has a shape broadcastable with condition and x.
Should be:
y | If provided, a Tensor which is of the same type as **x**, and has a shape broadcastable with condition and x.

**Comment by mihaimaruseac** [comment]
#41044 landed and fixed this in nightly.

**Comment by Chenni** [comment]
It does not seem to be fixed in https://www.tensorflow.org/api_docs/python/tf/where.

**Comment by aavishkarmishra** [comment]
@chenni you can see the updated version in nightly mode!!

**Comment by Chenni** [comment]
Sorry, but would you mind sharing the link to the nightly mode? Not sure how to check that. thx.

**Comment by aavishkarmishra** [comment]
@Chenni 
### **You can see nightly version in the link given below**
[`tf.where`](https://www.tensorflow.org/api_docs/python/tf/where?version=nightly)`

**Comment by Chenni** [comment]
Thanks! But the main website https://www.tensorflow.org/api_docs/python/tf/where that is visible to all the users are still not updated after more than a week. When will that be fixed?

**Comment by mihaimaruseac** [comment]
The main website is always in sync with the last TF release. So it will be updated when we release 2.3.0 (in a few weeks)
