### ISSUE TITLE
Support matmul operation for tf.complex64

### ISSUE THREAD

**Issue by galah92** [tensorflow/tensorflow#41000]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab CPU
- TensorFlow version (or github SHA if from source): 2.2.0

[Colab example](https://colab.research.google.com/drive/1_2YSQ21OwpxGhbdrDznNUsL77aesBynH?usp=sharing)

Note: I wouldn't mind to use `tf.einsum` instead, but that's not supported at all.
Also, not sure which operation *are* supported for `tf.complex`.

Thanks

**Comment by ravikyram** [comment]
I have tried in colab with TF versions, 2.2, 2.3-rc0 ,nightly versions and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/ce354d8108913f2eb4def033799b658a/untitled70.ipynb).Thanks!

**Comment by karimnosseir** [comment]
TF Lite doesn't support Complex natively, you will need to use Select (which runs TF kernels instead)
https://www.tensorflow.org/lite/guide/ops_select

See more details about what TFLite Supports here
https://www.tensorflow.org/lite/guide/inference#supported_operations

**Comment by karimnosseir** [comment]
Should be
"TF Lite doesn't support Complex natively for the requested ops"

**Comment by galah92** [comment]
Thanks, so I guess this issue is about supporting complex natively. Is that on the roadmap? when can we expect this?

**Comment by karimnosseir** [comment]
No plans at the current moment.
