### ISSUE TITLE
OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution

### ISSUE THREAD

**Issue by louisgriffin** [tensorflow/tensorflow#41003]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.4
- TensorFlow version (use command below): 2.2.0
- Python version: 3.7

**Describe the current behavior**
Getting 'OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution' error , while Eager execution is actually enabled

**Standalone code to reproduce the issue**
```python
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf

from tensorflow.keras import datasets, layers, models
(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()

# Normalize pixel values to be between 0 and 1
train_images, test_images = train_images / 255.0, test_images / 255.0

class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck']

model = models.Sequential()
model.add(layers.InputLayer(input_shape=(32, 32, 3)))
model.add(layers.Conv2D(16, (3,3)))
model.add(layers.Flatten())
model.add(layers.Dense(10, activation='softmax'))
model.summary()

def to_list(x):
  if isinstance(x, list):
    return x
  return [x]

outs = []
for l in model.layers:
    output_tensors = [to_list(inbound.output_tensors)[0] for inbound in l.inbound_nodes]
    outs.append(output_tensors)

ins = []
for l in model.layers:
    input_tensors = [to_list(inbound.input_tensors)[0] for inbound in l.inbound_nodes]
    ins.append(input_tensors)

assert tf.executing_eagerly()
for i_tensor in ins:
    if i_tensor in outs:
        print("BOOM")


```
Note that it passes the assertion, making sure the eager execution is on, but still raises the error on the if statement and suggests to 'Use Eager execution'. What am I missing? The eager execution is on by default in TF 2.2

**Comment by Saduf2019** [comment]
@louisgriffin 
Can you please refer to [this link](https://github.com/matterport/Mask_RCNN/issues/1911#issuecomment-595682013) and let us know if it helps.
[Link1](https://stackoverflow.com/questions/59308263/using-a-tf-tensor-as-a-python-bool-is-not-allowed-in-graph-execution-use-ea) [link2](https://github.com/tensorflow/tensorflow/issues/37393#issuecomment-646815275) #36848

**Comment by louisgriffin** [comment]
> @louisgriffin
> Can you please refer to [this link](https://github.com/matterport/Mask_RCNN/issues/1911#issuecomment-595682013) and let us know if it helps.
> [Link1](https://stackoverflow.com/questions/59308263/using-a-tf-tensor-as-a-python-bool-is-not-allowed-in-graph-execution-use-ea) [link2](https://github.com/tensorflow/tensorflow/issues/37393#issuecomment-646815275) #36848

@Saduf2019 In the link you provided you suggest using tf 1.15? I need tf 2.x

**Comment by gowthamkpr** [comment]
@louisgriffin I have run into a different error. Please find the gist [here](https://colab.research.google.com/gist/gowthamkpr/567a1a1200e6901d397b5a4e8bb9e8dd/untitled301.ipynb)
