### ISSUE TITLE
error: ‘tensorflow::error’ has not been declared----Status(tensorflow::error::Code code, tensorflow::StringPiece msg);

### ISSUE THREAD

**Issue by Johnny19-91** [tensorflow/tensorflow#41018]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution : Linux Ubuntu 16.04
- TensorFlow installed from :    source
- TensorFlow version :  1.14
- Python version:   3.5
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version :  5.4.0 20160609
- CUDA/cuDNN version: 10.0/7.6.5
- GPU model and memory:  GF1080 TI

**Describe the current behavior**

I am a newer to c++, I want to accomplish CNN model with c++ tensorflow API. I follow the manual on the Internet and finishe tensorflow compiling and  generate the libtensorflow_cc.so file.   Now I want to build a test using cmake 3.13.0, I create a "CMakeLists.txt" and execute
'''
cmake .
make
'''

the errors:

'''
[make[2]: Warning: File '/home/john/tensorflow/tensorflow/contrib/makefile/downloads/eigen/Eigen/src/Core/arch/NEON/Complex.h' has modification time 11068 s in the future
[ 50%] Building CXX object CMakeFiles/tensorflow_cc_test.dir/hello.cpp.o
In file included from /home/john/tensorflow/tensorflow/core/lib/core/errors.h:21:0,
                 from /home/john/tensorflow/tensorflow/core/platform/env.h:24,
                 from /home/john/文档/tensorflow_cc_test/hello.cpp:1:
/home/john/tensorflow/tensorflow/core/lib/core/status.h:45:22: error: ‘tensorflow::error’ has not been declared
   Status(tensorflow::error::Code code, tensorflow::StringPiece msg);
                      ^
/home/john/tensorflow/tensorflow/core/lib/core/status.h:45:34: error: expected ‘)’ before ‘code’
   Status(tensorflow::error::Code code, tensorflow::StringPiece msg);
                                  ^
/home/john/tensorflow/tensorflow/core/lib/core/status.h:56:15: error: ‘error’ in namespace ‘tensorflow’ does not name a type
   tensorflow::error::Code code() const {
               ^
/home/john/tensorflow/tensorflow/core/lib/core/status.h:90:17: error: ‘error’ in namespace ‘tensorflow’ does not name a type
     tensorflow::error::Code code;
                 ^
In file included from /home/john/tensorflow/tensorflow/core/platform/env.h:24:0,
                 from /home/john/文档/tensorflow_cc_test/hello.cpp:1:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:30:23: error: ‘error’ in namespace ‘tensorflow’ does not name a type
 typedef ::tensorflow::error::Code Code;
                       ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘void tensorflow::errors::AppendToMessage(tensorflow::Status*, Args ...)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:65:15: error: ‘class tensorflow::Status’ has no member named ‘code’
       status->code(),
               ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘tensorflow::Status tensorflow::errors::Cancelled(Args ...)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:95:9: error: ‘error’ is not a member of ‘tensorflow’
         ::tensorflow::error::CONST,                                      \
         ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:103:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(Cancelled, CANCELLED)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘bool tensorflow::errors::IsCancelled(const tensorflow::Status&)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:19: error: ‘const class tensorflow::Status’ has no member named ‘code’
     return status.code() == ::tensorflow::error::CONST;                  \
                   ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:103:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(Cancelled, CANCELLED)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:43: error: ‘tensorflow::error’ has not been declared
     return status.code() == ::tensorflow::error::CONST;                  \
                                           ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:103:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(Cancelled, CANCELLED)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘tensorflow::Status tensorflow::errors::InvalidArgument(Args ...)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:95:9: error: ‘error’ is not a member of ‘tensorflow’
         ::tensorflow::error::CONST,                                      \
         ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:104:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(InvalidArgument, INVALID_ARGUMENT)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘bool tensorflow::errors::IsInvalidArgument(const tensorflow::Status&)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:19: error: ‘const class tensorflow::Status’ has no member named ‘code’
     return status.code() == ::tensorflow::error::CONST;                  \
                   ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:104:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(InvalidArgument, INVALID_ARGUMENT)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:43: error: ‘tensorflow::error’ has not been declared
     return status.code() == ::tensorflow::error::CONST;                  \
                                           ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:104:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(InvalidArgument, INVALID_ARGUMENT)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘tensorflow::Status tensorflow::errors::NotFound(Args ...)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:95:9: error: ‘error’ is not a member of ‘tensorflow’
         ::tensorflow::error::CONST,                                      \
         ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:105:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(NotFound, NOT_FOUND)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘bool tensorflow::errors::IsNotFound(const tensorflow::Status&)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:19: error: ‘const class tensorflow::Status’ has no member named ‘code’
     return status.code() == ::tensorflow::error::CONST;                  \
                   ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:105:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(NotFound, NOT_FOUND)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:43: error: ‘tensorflow::error’ has not been declared
     return status.code() == ::tensorflow::error::CONST;                  \
                                           ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:105:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(NotFound, NOT_FOUND)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘tensorflow::Status tensorflow::errors::AlreadyExists(Args ...)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:95:9: error: ‘error’ is not a member of ‘tensorflow’
         ::tensorflow::error::CONST,                                      \
         ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:106:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(AlreadyExists, ALREADY_EXISTS)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘bool tensorflow::errors::IsAlreadyExists(const tensorflow::Status&)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:19: error: ‘const class tensorflow::Status’ has no member named ‘code’
     return status.code() == ::tensorflow::error::CONST;                  \
                   ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:106:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(AlreadyExists, ALREADY_EXISTS)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:43: error: ‘tensorflow::error’ has not been declared
     return status.code() == ::tensorflow::error::CONST;                  \
                                           ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:106:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(AlreadyExists, ALREADY_EXISTS)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘tensorflow::Status tensorflow::errors::ResourceExhausted(Args ...)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:95:9: error: ‘error’ is not a member of ‘tensorflow’
         ::tensorflow::error::CONST,                                      \
         ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:107:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(ResourceExhausted, RESOURCE_EXHAUSTED)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘bool tensorflow::errors::IsResourceExhausted(const tensorflow::Status&)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:19: error: ‘const class tensorflow::Status’ has no member named ‘code’
     return status.code() == ::tensorflow::error::CONST;                  \
                   ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:107:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(ResourceExhausted, RESOURCE_EXHAUSTED)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:43: error: ‘tensorflow::error’ has not been declared
     return status.code() == ::tensorflow::error::CONST;                  \
                                           ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:107:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(ResourceExhausted, RESOURCE_EXHAUSTED)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘tensorflow::Status tensorflow::errors::Unavailable(Args ...)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:95:9: error: ‘error’ is not a member of ‘tensorflow’
         ::tensorflow::error::CONST,                                      \
         ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:108:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(Unavailable, UNAVAILABLE)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘bool tensorflow::errors::IsUnavailable(const tensorflow::Status&)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:19: error: ‘const class tensorflow::Status’ has no member named ‘code’
     return status.code() == ::tensorflow::error::CONST;                  \
                   ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:108:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(Unavailable, UNAVAILABLE)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:43: error: ‘tensorflow::error’ has not been declared
     return status.code() == ::tensorflow::error::CONST;                  \
                                           ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:108:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(Unavailable, UNAVAILABLE)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘tensorflow::Status tensorflow::errors::FailedPrecondition(Args ...)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:95:9: error: ‘error’ is not a member of ‘tensorflow’
         ::tensorflow::error::CONST,                                      \
         ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:109:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(FailedPrecondition, FAILED_PRECONDITION)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘bool tensorflow::errors::IsFailedPrecondition(const tensorflow::Status&)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:19: error: ‘const class tensorflow::Status’ has no member named ‘code’
     return status.code() == ::tensorflow::error::CONST;                  \
                   ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:109:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(FailedPrecondition, FAILED_PRECONDITION)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:43: error: ‘tensorflow::error’ has not been declared
     return status.code() == ::tensorflow::error::CONST;                  \
                                           ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:109:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(FailedPrecondition, FAILED_PRECONDITION)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘tensorflow::Status tensorflow::errors::OutOfRange(Args ...)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:95:9: error: ‘error’ is not a member of ‘tensorflow’
         ::tensorflow::error::CONST,                                      \
         ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:110:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(OutOfRange, OUT_OF_RANGE)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘bool tensorflow::errors::IsOutOfRange(const tensorflow::Status&)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:19: error: ‘const class tensorflow::Status’ has no member named ‘code’
     return status.code() == ::tensorflow::error::CONST;                  \
                   ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:110:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(OutOfRange, OUT_OF_RANGE)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:43: error: ‘tensorflow::error’ has not been declared
     return status.code() == ::tensorflow::error::CONST;                  \
                                           ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:110:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(OutOfRange, OUT_OF_RANGE)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘tensorflow::Status tensorflow::errors::Unimplemented(Args ...)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:95:9: error: ‘error’ is not a member of ‘tensorflow’
         ::tensorflow::error::CONST,                                      \
         ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:111:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(Unimplemented, UNIMPLEMENTED)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘bool tensorflow::errors::IsUnimplemented(const tensorflow::Status&)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:19: error: ‘const class tensorflow::Status’ has no member named ‘code’
     return status.code() == ::tensorflow::error::CONST;                  \
                   ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:111:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(Unimplemented, UNIMPLEMENTED)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:43: error: ‘tensorflow::error’ has not been declared
     return status.code() == ::tensorflow::error::CONST;                  \
                                           ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:111:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(Unimplemented, UNIMPLEMENTED)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘tensorflow::Status tensorflow::errors::Internal(Args ...)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:95:9: error: ‘error’ is not a member of ‘tensorflow’
         ::tensorflow::error::CONST,                                      \
         ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:112:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(Internal, INTERNAL)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘bool tensorflow::errors::IsInternal(const tensorflow::Status&)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:19: error: ‘const class tensorflow::Status’ has no member named ‘code’
     return status.code() == ::tensorflow::error::CONST;                  \
                   ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:112:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(Internal, INTERNAL)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:43: error: ‘tensorflow::error’ has not been declared
     return status.code() == ::tensorflow::error::CONST;                  \
                                           ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:112:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(Internal, INTERNAL)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘tensorflow::Status tensorflow::errors::Aborted(Args ...)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:95:9: error: ‘error’ is not a member of ‘tensorflow’
         ::tensorflow::error::CONST,                                      \
         ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:113:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(Aborted, ABORTED)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘bool tensorflow::errors::IsAborted(const tensorflow::Status&)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:19: error: ‘const class tensorflow::Status’ has no member named ‘code’
     return status.code() == ::tensorflow::error::CONST;                  \
                   ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:113:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(Aborted, ABORTED)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:43: error: ‘tensorflow::error’ has not been declared
     return status.code() == ::tensorflow::error::CONST;                  \
                                           ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:113:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(Aborted, ABORTED)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘tensorflow::Status tensorflow::errors::DeadlineExceeded(Args ...)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:95:9: error: ‘error’ is not a member of ‘tensorflow’
         ::tensorflow::error::CONST,                                      \
         ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:114:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(DeadlineExceeded, DEADLINE_EXCEEDED)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘bool tensorflow::errors::IsDeadlineExceeded(const tensorflow::Status&)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:19: error: ‘const class tensorflow::Status’ has no member named ‘code’
     return status.code() == ::tensorflow::error::CONST;                  \
                   ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:114:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(DeadlineExceeded, DEADLINE_EXCEEDED)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:43: error: ‘tensorflow::error’ has not been declared
     return status.code() == ::tensorflow::error::CONST;                  \
                                           ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:114:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(DeadlineExceeded, DEADLINE_EXCEEDED)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘tensorflow::Status tensorflow::errors::DataLoss(Args ...)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:95:9: error: ‘error’ is not a member of ‘tensorflow’
         ::tensorflow::error::CONST,                                      \
         ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:115:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(DataLoss, DATA_LOSS)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘bool tensorflow::errors::IsDataLoss(const tensorflow::Status&)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:19: error: ‘const class tensorflow::Status’ has no member named ‘code’
     return status.code() == ::tensorflow::error::CONST;                  \
                   ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:115:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(DataLoss, DATA_LOSS)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:43: error: ‘tensorflow::error’ has not been declared
     return status.code() == ::tensorflow::error::CONST;                  \
                                           ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:115:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(DataLoss, DATA_LOSS)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘tensorflow::Status tensorflow::errors::Unknown(Args ...)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:95:9: error: ‘error’ is not a member of ‘tensorflow’
         ::tensorflow::error::CONST,                                      \
         ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:116:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(Unknown, UNKNOWN)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘bool tensorflow::errors::IsUnknown(const tensorflow::Status&)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:19: error: ‘const class tensorflow::Status’ has no member named ‘code’
     return status.code() == ::tensorflow::error::CONST;                  \
                   ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:116:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(Unknown, UNKNOWN)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:43: error: ‘tensorflow::error’ has not been declared
     return status.code() == ::tensorflow::error::CONST;                  \
                                           ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:116:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(Unknown, UNKNOWN)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘tensorflow::Status tensorflow::errors::PermissionDenied(Args ...)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:95:9: error: ‘error’ is not a member of ‘tensorflow’
         ::tensorflow::error::CONST,                                      \
         ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:117:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(PermissionDenied, PERMISSION_DENIED)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘bool tensorflow::errors::IsPermissionDenied(const tensorflow::Status&)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:19: error: ‘const class tensorflow::Status’ has no member named ‘code’
     return status.code() == ::tensorflow::error::CONST;                  \
                   ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:117:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(PermissionDenied, PERMISSION_DENIED)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:43: error: ‘tensorflow::error’ has not been declared
     return status.code() == ::tensorflow::error::CONST;                  \
                                           ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:117:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(PermissionDenied, PERMISSION_DENIED)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘tensorflow::Status tensorflow::errors::Unauthenticated(Args ...)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:95:9: error: ‘error’ is not a member of ‘tensorflow’
         ::tensorflow::error::CONST,                                      \
         ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:118:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(Unauthenticated, UNAUTHENTICATED)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: In function ‘bool tensorflow::errors::IsUnauthenticated(const tensorflow::Status&)’:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:19: error: ‘const class tensorflow::Status’ has no member named ‘code’
     return status.code() == ::tensorflow::error::CONST;                  \
                   ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:118:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(Unauthenticated, UNAUTHENTICATED)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:100:43: error: ‘tensorflow::error’ has not been declared
     return status.code() == ::tensorflow::error::CONST;                  \
                                           ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:118:1: note: in expansion of macro ‘DECLARE_ERROR’
 DECLARE_ERROR(Unauthenticated, UNAUTHENTICATED)
 ^
/home/john/tensorflow/tensorflow/core/lib/core/errors.h: At global scope:
/home/john/tensorflow/tensorflow/core/lib/core/errors.h:158:21: error: ‘tensorflow::error’ has not been declared
 using ::tensorflow::error::OK;
                     ^
CMakeFiles/tensorflow_cc_test.dir/build.make:62: recipe for target 'CMakeFiles/tensorflow_cc_test.dir/hello.cpp.o' failed
make[2]: *** [CMakeFiles/tensorflow_cc_test.dir/hello.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/tensorflow_cc_test.dir/all' failed
make[1]: *** [CMakeFiles/tensorflow_cc_test.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
'''

I can not search Internet for anythin about this, can somebody help?

**Comment by Johnny19-91** [comment]
I forgot to submit the CMakeLists Info:
'''
cmake_minimum_required(VERSION 3.10)
project(tensorflow_cc_test)
set(CMAKE_CXX_STANDARD 11)
set(TENSORFLOW_DIR /home/john/tensorflow)
include_directories(${TENSORFLOW_DIR})
include_directories(${TENSORFLOW_DIR}/tensorflow/contrib/makefile/downloads/absl)
include_directories(${TENSORFLOW_DIR}/tensorflow/contrib/makefile/downloads/protobuf/src)
include_directories(${TENSORFLOW_DIR}/tensorflow/contrib/makefile/gen/proto)
include_directories(${TENSORFLOW_DIR}/tensorflow/contrib/makefile/gen/protobuf-host/include)
include_directories(${TENSORFLOW_DIR}/tensorflow/contrib/makefile/downloads)
include_directories(${TENSORFLOW_DIR}/tensorflow/contrib/makefile/downloads/eigen)
include_directories(${TENSORFLOW_DIR}/tensorflow/contrib/makefile/downloads/nsync/public)

link_directories(${TENSORFLOW_DIR}/tensorflow/contrib/makefile/gen/lib)
link_directories(${TENSORFLOW_DIR}/tensorflow/contrib/makefile/gen/protobuf-host/lib)
link_directories(${TENSORFLOW_DIR}/tensorflow/contrib/makefile/downloads/nsync/builds/default.linux.c++11)
link_directories(${TENSORFLOW_DIR}/bazel-bin/tensorflow)

add_executable(tensorflow_cc_test hello.cpp)
target_link_libraries(tensorflow_cc_test tensorflow_cc tensorflow_framework)
'''

**Comment by Johnny19-91** [comment]
I add a declare "class tensorflow::error::Code;" , the errors disappear.

**Comment by Saduf2019** [comment]
@Johnny19-91 
Please confirm if the issue is resolved.

**Comment by tcervi** [comment]
Hi @Johnny19-91 
I just came across the same build issue you described here. I'm unable to compile my project (linking to built libs) due to several erros on "errors.h" and "status.h" files, mainly related to this first one:
`error: C2039: 'error' is not a member of 'tensorflow'`

Do you mind explaining better how did you manage to get rid of this issue? 
I saw your comment about declaring the class "class tensorflow::error::Code;" but couldn't really get what/where you did. That is exactly my point of failure, "error" and "error::Code".
Or maybe @Saduf2019 has more info about how this was solved?

Follow my environment:

**System information**

I'm also using CMake and trying to link the generated DLLs to my source code (C++).
**OS Platform and Distribution:** Windows 10 
**TensorFlow installed from:** source
**TensorFlow version:** 2.1.0
**Python version:** 3.8.3 (x64 - using venv)
**Bazel version:** 0.29.0
**GCC/Compiler version:** MSVC 19.27.29111.0
**CUDA/cuDNN version:** not used
**GPU model and memory:** not used

Obs.: On my CMakeLists.txt I'm using "find_library" to get tensorflow.dll and tensorflow_cc.dll (not sure which one should I use, I bulit both using Bazel) and am also including the headers directory on "target_include_directories($<BUILD_INTERFACE:>)". Finally, I'm including the libraries found to "target_link_libraries"


Thanks in advance folks!
Cheers.

**Comment by Johnny19-91** [comment]
sorry, I sign in the github and do not find the topic.



---Original---
