### ISSUE TITLE
'fit' takes a dataset with increasing batch size

### ISSUE THREAD

**Issue by tabergma** [tensorflow/tensorflow#41019]
**System information**
- TensorFlow version (you are using): 2.2
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
I have a custom model to train a text classifier. So far (tensorflow 2.1) we overwrote all important methods of `tf.keras.models.Model`, e.g. `fit`, `predict` etc. One of the reasons for that was that we wanted to adapt the batch size of our dataset every epoch. So, during the first epoch we would have, for example, a batch size of 16, in the next iteration the batch size would increase to 20, and so on. Until we reach an upper limit.

Here is the method that generates our tf.Dataset. We would call this method every epoch to get a dataset with the desired batch size.
```
def as_tf_dataset(
    self, batch_size: int, batch_strategy: Text = SEQUENCE, shuffle: bool = False
) -> tf.data.Dataset:
    """Create tf dataset."""

    shapes, types = self._get_shapes_types()

    return tf.data.Dataset.from_generator(
        lambda batch_size_: self._gen_batch(batch_size_, batch_strategy, shuffle),
        output_types=types,
        output_shapes=shapes,
        args=([batch_size]),
    )
```

With Tensorflow 2.2. it is possible to just overwrite `train_step` and `test_step` instead of `fit` etc (we followed this [guide](https://keras.io/guides/customizing_what_happens_in_fit/)). This would simplify our code quite a bit and would allow us to use callbacks. 
However, when we would overwriting `train_step` instead of `fit` we would loose the possibility to control the dataset, e.g. adapt the batch size of the dataset every epoch. `fit` just takes a dataset and with the help of a `DataHandler` it create a new iterator over that dataset every epoch. 

I am not sure how to solve this, but maybe we could allow users to define a custom `DataHandler` that takes care of the dataset generation. 

**Who will benefit with this feature?**
Any users that use a `tf.keras.models.Model`.

**Comment by tabergma** [comment]
I found a way to make this work. We can implement a custom data generator that will take care of the increasing batch size depending on the current epoch. This can be passed on to `fit`. However, the data adapter used inside `fit` assumes the number of steps is the same across all epochs, which is not true in case of an increasing batch size. 
To make that work, we need to add the line 
```
self._inferred_steps = self._infer_steps(None, self._dataset)
``` after the following line:
workshttps://github.com/tensorflow/tensorflow/blob/fcc4b966f1265f466e82617020af93670141b009/tensorflow/python/keras/engine/data_adapter.py#L1143
This ensure that not only the dataset is updated, but also the steps per epoch.

Will create a PR for this.

**Comment by bhack** [comment]
@nikitamaia Can we assign to @tabergma ?
