### ISSUE TITLE
Add the steps related to Pickling the Tokenization in Text Classification Tutorial

### ISSUE THREAD

**Issue by rakeshmothukuru1** [tensorflow/tensorflow#41016]
## Description of issue (what needs changing): 
Can include the Code related to Pickling the Tokenization and then Loading the Pickle File while predicting on the Loaded Saved Model.

### Clear description : 
Recently, I have worked on a `Text Classification project`. Everything was good and the Model is `95%` Accurate. But when performing `Predictions` after `Loading the Saved Model`, and while performing Inference using `Tensorflow Serving`, **Model's Predictions were very poor**. After investigating for more than 10 days, we figured out that we need to **Save the Tokenizations in a Pickle File and then Load that Pickle File while Performing Predictions on a Loaded Saved Model or using TF Serving or using TF Lite**.

### Code that can be added in the Documentation: 

Below code needs to be added after the command, `tokenizer = Tokenizer(num_words = vocab_size, oov_token=oov_tok)`

```
import pickle

# Saving the Tokenization in Pickle File

with open('tokenizer.pickle', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)

```

Also, below code needs to be added before the command, `train_sequences = tokenizer2.texts_to_sequences(Train_Resume_Data)`

```
# Loading the Tokeniztion Pickle File
with open('tokenizer.pickle', 'rb') as handle:
    tokenizer2 = pickle.load(handle)
```

This will help all the Developers working on Text Classification projects or any other NLP Task. Thanks.

**Comment by yil532** [comment]
Hi, can I work on this issue?

**Comment by jvishnuvardhan** [comment]
@yil532 Please feel free to open a PR to update this doc. Thanks!

**Comment by yil532** [comment]
Thanks! Working on it

**Comment by yil532** [comment]
I didn't find line of code `tokenizer = Tokenizer(num_words = vocab_size, oov_token=oov_tok)` in the [link you shared](https://www.tensorflow.org/tutorials/text/text_classification_rnn) Could you be more specific where the issue exists?
@rakeshmothukuru1

**Comment by rakeshmothukuru1** [comment]
@yil532,
I'm surprised to see that Tokenization is not applied in [Text Classification Tutorial](https://www.tensorflow.org/tutorials/text/text_classification_rnn). Can someone clarify why Tokenization is not required in Text Classification Tutorial?

Sorry for the confusion. It's not present in [Text Classification Tutorial](https://www.tensorflow.org/tutorials/text/text_classification_rnn) but is present in [Image Captioning Tutorial](https://www.tensorflow.org/tutorials/text/image_captioning#preprocess_and_tokenize_the_captions). So this change can be applied in [Image Captioning Tutorial](https://www.tensorflow.org/tutorials/text/image_captioning#preprocess_and_tokenize_the_captions).

**Comment by MarkDaoust** [comment]
Hi, we are actively working on a fix for this, using the new [text vectorization layers](https://www.tensorflow.org/api_docs/python/tf/keras/layers/experimental/preprocessing/TextVectorization) which will make this less of a headache for everyone.
