### ISSUE TITLE
AutoGraph could not transform with "Cause: Inconsistent ASTs detected" with pymc4

### ISSUE THREAD

**Issue by Isa-rentacs** [tensorflow/tensorflow#41027]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
  * Yes, with [pymc4](https://github.com/pymc-devs/pymc4)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
  * Ubuntu 16.04 on WSL (WSL1)
  * Windows version : Windows 10 1909 (18363.900) 
- TensorFlow installed from (source or binary):
  * binary
- TensorFlow version (use command below):
  * v1.12.1-35610-gd8c49c2fde 2.4.0-dev20200701
- Python version:
  * Python 3.8.3, built from source
- CUDA/cuDNN version:
- GPU model and memory:
  * No GPU

**Describe the current behavior**
When I execute a script which uses pymc4, TF writes logs which says:
```
WARNING:tensorflow:AutoGraph could not transform <function _convert_function_call.<locals>.f at 0x7f2d04ec3f70> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Inconsistent ASTs detected. This is a bug. Cause: 
inconsistent values for field args: [<gast.gast.Name object at 0x7f2d04d7b370>] and []Diff:
```
**Describe the expected behavior**
The script runs without the warning log from TF.

**Standalone code to reproduce the issue**
1. Install pymc4 with ```pip install pymc4```
   * This will also install TF
1. Run [this script](https://gist.github.com/Isa-rentacs/aef5629956b17493072f44478bf0d3dd)

**Other info / logs** 
The log is available on [this gist](https://gist.github.com/Isa-rentacs/72ca156134a172d56cbe4ae5da827003)

**Comment by Saduf2019** [comment]
@Isa-rentacs 
Please share a simple stand alone indented code for us to replicate the issue faced

**Comment by Isa-rentacs** [comment]
Both the code for repro and TF version is in the original post.
Gist for the code to reproduce : https://gist.github.com/Isa-rentacs/aef5629956b17493072f44478bf0d3dd
TF version : 2.4.0-dev20200701
TF-P version : 0.11.0-dev20200702

**Comment by Saduf2019** [comment]
@Isa-rentacs 
I ran the code shared and face different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/8f1c71988114e6fd0cd4b9c9b7b2ba95/untitled261.ipynb).
