### ISSUE TITLE
Installation broken - Tensorflow 2.2 Cuda 10.1 Ubuntu 18.04

### ISSUE THREAD

**Issue by rsuhada-ampx** [tensorflow/tensorflow#41025]
This is essentially the same issue to  #36121 with Tensorflow 2.2. The issue doesn't list a proper solution, only led to an update of documentation, that is now apparently again out of date.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version: 2.2
- Python version:  3.7.5
- Installed using virtualenv? pip? conda?: virtualenv 20.0.25
- CUDA/cuDNN version: 10.1
- GPU model and memory: GeForce RTX 2070 with Max-Q Design/PCIe/SSE2

**Describe the problem**
I'm following the installation instructions:
https://www.tensorflow.org/install/gpu#ubuntu_1804_cuda_101

Finished these steps (no errors):

    #Add NVIDIA package repositories
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.1.243-1_amd64.deb
    sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
    sudo dpkg -i cuda-repo-ubuntu1804_10.1.243-1_amd64.deb
    sudo apt-get update
    wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
    sudo apt install ./nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
    sudo apt-get update
    
    # Install NVIDIA driver
    sudo apt-get install --no-install-recommends nvidia-driver-430
    # Reboot. Check that GPUs are visible using the command: nvidia-smi

`nvidia-smi` returns:
    NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2

Two notable points:

- 440 was fetched
- CUDA is listed as 10.2 (although the next step of installation tries to install 10.1:

    sudo apt-get install --no-install-recommends \
        cuda-10-1 \
        libcudnn7=7.6.4.38-1+cuda10.1  \
        libcudnn7-dev=7.6.4.38-1+cuda10.1

This gives same error as #36121:

    The following packages have unmet dependencies:
     cuda-10-1 : Depends: cuda-runtime-10-1 (>= 10.1.243) but it is not going to be installed
             Depends: cuda-demo-suite-10-1 (>= 10.1.243) but it is not going to be installed

The discussion in #36121 is bit unclear on resolution and differs slightly in driver/library version numbers.
I'm on a freshly installed system and I have *not* attempted to install the dependencies manually, before consulting you.

Thank you!

**Comment by amahendrakar** [comment]
@rsuhada-ampx,
Please check [this thread](https://github.com/tensorflow/tensorflow/issues/39116) regarding a similar issue and let us know if it helps. Thanks!

**Comment by rsuhada-ampx** [comment]
> @rsuhada-ampx,
> Please check [this thread](https://github.com/tensorflow/tensorflow/issues/39116) regarding a similar issue and let us know if it helps. Thanks!

No, [this reply](https://github.com/tensorflow/tensorflow/issues/39116#issuecomment-623686956) has not resolved the issue. The author says that he doesn't know what worked, but assumes doing:
    
    sudo apt -y full-upgrade

This doesn't work for me: my system is a fresh install, completely upgraded. The issue persists exactly the same as before.

Thank you.

**Comment by suneeta-mall** [comment]
```
   add-apt-repository universe && \
    apt-get update -yqq && \
    apt-get install freeglut3-dev -y && \
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.1.243-1_amd64.deb && \
    apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub && \
    dpkg -i cuda-repo-ubuntu1804_10.1.243-1_amd64.deb && \
    apt-get update -y && \
    wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb && \
    apt-get install -y ./nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb && \
    apt-get update -y && \
    mkdir -p /usr/lib/nvidia && \
    apt-get install -y --no-install-recommends nvidia-driver-430 && \
    apt-get install -y --no-install-recommends \
        cuda \
        cuda-10-1 \
        cuda-toolkit-10-1 \
        cuda-samples-10-1 \
        cuda-documentation-10-1 \
        libcudnn7=7.6.4.38-1+cuda10.1  \
        libcudnn7-dev=7.6.4.38-1+cuda10.1 
```

^^ This worked for me, note the install of `freeglut3-dev` a first step as advised [here](https://forums.developer.nvidia.com/t/cuda-install-unmet-dependencies-cuda-depends-cuda-10-0-10-0-130-but-it-is-not-going-to-be-installed/66488/9) for an earlier version

**Comment by mihaimaruseac** [comment]
Note that nothing in this issue is related to TensorFlow code. This question is better asked on StackOverflow/elsewhere, as we are trying to triage these issues to be only those relevant to the code itself.

**Comment by suneeta-mall** [comment]
> Note that nothing in this issue is related to TensorFlow code. This question is better asked on StackOverflow/elsewhere, as we are trying to triage these issues to be only those relevant to the code itself.

Would not TF want to update its doco though to reflect right instructions thats mentioned here https://www.tensorflow.org/install/gpu 
Perhaps this issue is more of documentation.

**Comment by rsuhada-ampx** [comment]
> Note that nothing in this issue is related to TensorFlow code. This question is better asked on StackOverflow/elsewhere, as we are trying to triage these issues to be only those relevant to the code itself.

In that case you might want to remove the option for build/install issue label as it misleads the users that they can get help here.

**Comment by rsuhada-ampx** [comment]
> ```
>    add-apt-repository universe && \
>     apt-get update -yqq && \
>     apt-get install freeglut3-dev -y && \
>     wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.1.243-1_amd64.deb && \
>     apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub && \
>     dpkg -i cuda-repo-ubuntu1804_10.1.243-1_amd64.deb && \
>     apt-get update -y && \
>     wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb && \
>     apt-get install -y ./nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb && \
>     apt-get update -y && \
>     mkdir -p /usr/lib/nvidia && \
>     apt-get install -y --no-install-recommends nvidia-driver-430 && \
>     apt-get -y --fix-broken -o Dpkg::Options::="--force-overwrite" install \
>         cuda \
>         cuda-10-1 \
>         cuda-toolkit-10-1 \
>         cuda-samples-10-1 
> ```
> 
> ^^ This worked for me, note the install of `freeglut3-dev` a first step as advised [here](https://forums.developer.nvidia.com/t/cuda-install-unmet-dependencies-cuda-depends-cuda-10-0-10-0-130-but-it-is-not-going-to-be-installed/66488/9) for an earlier version

Thank you Suneeta! 
`apt-get install freeglut3-dev -y` definitely made a difference, though I run into issues anyway.

For posterity, if somebody had a similar issue:

- I followed Suneeta's instructions
- the installation still failed at the last step. I unfortunately could not save the error message
- after restart I could not boot into Linux, but fortunately booting into recovery mode and running a package repair mode worked
- oddly enough after finally managing to get into the system:
- nvidia-smi worked, but says I'm on v450 with CUDA 11 (!)
- re-trying the last step of installation says that everything is installed and up to date (despite failing previously). I think the recovery repair fixed it.

- Doing the basic tensorflow test (v2.2) worked - GPU detected. I haven't tried anything fancier, so not sure if the installation is stable... Fingers crossed.

So, I suspect (but don't know for sure), that you should reboot before doing the last step in Suneeta's instructions.

As this was a clean slate system, I do not think the official install instructions are correct for 18.04.

**Comment by mihaimaruseac** [comment]
@rsuhada-ampx apologies, there are countless of configurations and operating systems where TF could be installed and we only do the release in one (Ubuntu 16). Of course, we accept updates to the documentation if our configuration is broken, but for all others we can only provide minimal guidance in these types of issues and then redirect to StackOverflow / SIG Build.

In this case, you are using Ubuntu 18, while we were building for Ubuntu 16. So, installation of dependent packages is not documented and we don't have enough people to also fully investigate.

**Comment by suneeta-mall** [comment]
Just putting it there in case anyone needs it .. I have jumped through manny hoops but this works without any fixup or overwrites and also pins everything so no moving target (kernels-commons) overwrites anything ..

```bash
apt-get update -yqq && \
    apt-get install freeglut3-dev -y && \
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.1.243-1_amd64.deb && \
    apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub && \
    dpkg -i cuda-repo-ubuntu1804_10.1.243-1_amd64.deb && \
    apt-get update -y && \
    wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb && \
    apt-get install -y ./nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb && \
    apt-get update -y && \
    mkdir -p /usr/lib/nvidia && \
    apt-get install -y --no-install-recommends \
        nvidia-driver-450=450.36.06-0ubuntu1 \
        libnvidia-common-450=450.36.06-0ubuntu1 \
        nvidia-kernel-common-450=450.36.06-0ubuntu1 \
        libnvidia-gl-450=450.36.06-0ubuntu1 \
        nvidia-dkms-450=450.36.06-0ubuntu1 \
        nvidia-kernel-source-450=450.36.06-0ubuntu1 \
        libnvidia-compute-450=450.36.06-0ubuntu1 \
        nvidia-compute-utils-450=450.36.06-0ubuntu1 \
        libnvidia-decode-450=450.36.06-0ubuntu1 \
        libnvidia-encode-450=450.36.06-0ubuntu1 \
        nvidia-utils-450=450.36.06-0ubuntu1 \
        xserver-xorg-video-nvidia-450=450.36.06-0ubuntu1 \
        libnvidia-cfg1-450=450.36.06-0ubuntu1 \
        libnvidia-ifr1-450=450.36.06-0ubuntu1 \
        libnvidia-fbc1-450=450.36.06-0ubuntu1 \
        nvidia-modprobe=450.36.06-0ubuntu1 \
        libxnvctrl0=450.36.06-0ubuntu1 \
        nvidia-settings=450.36.06-0ubuntu1 && \
    apt-get -y --no-install-recommends install \
        cuda-10-1 \
        cuda-toolkit-10-1 \
        cuda-samples-10-1 \
        cuda-drivers-450=450.36.06-1 \
        cuda-drivers=450.36.06-1 \
        cuda-documentation-10-1 && \
    apt-get install -y --no-install-recommends \
        libcudnn7=7.6.4.38-1+cuda10.1 \
        libcudnn7-dev=7.6.4.38-1+cuda10.1 && \
    apt-get install -y --no-install-recommends \
        libnvinfer6=6.0.1-1+cuda10.1 \
        libnvinfer-dev=6.0.1-1+cuda10.1 \
        libnvinfer-plugin6=6.0.1-1+cuda10.1 
```

Switching the `450` nvidia driver to 440/430/418 will also work provided minor pin version resolves correctly
