### ISSUE TITLE
ucf101 video dataset seems to be gone

### ISSUE THREAD

**Issue by grofte** [tensorflow/tensorflow#41026]
The ucf101 activity recognition dataset seems to have been completely removed. There's a link here https://www.tensorflow.org/datasets/catalog/ucf101 and when you go further both the landing page and the .zip file results in 404 errors. 

To be honest I am a little surprised that Google wasn't hosting these datasets. You could link it up in Colaboratory so you didn't even have to download anything when using them from there. Just an idea.

**Comment by ymodak** [comment]
This issue is more suitable on https://github.com/tensorflow/datasets/issues platform.
For quicker turnaround time you may try raising it on [datasets](https://github.com/tensorflow/datasets/issues) repo.
Thanks!

**Comment by ymodak** [comment]
Thanks for the issue. The correct weblink should point to https://www.crcv.ucf.edu/datasets/human-actions/ucf101/UCF101.rar

**Comment by grofte** [comment]
Thank you so much! And I'm so sorry for putting it here rather than in /datasets - I was  a bit confused I think =)

**Comment by Conchylicultor** [comment]
Thank you for reporting

> To be honest I am a little surprised that Google wasn't hosting these datasets.

Google does not own the original data, so we are not legally allowed to re-host the dataset ourself (even if we would love to as it would greatly benefit the open source community).

Closing this as we've updated the link internally.
