### ISSUE TITLE
Failed to build 1.15.3 release with GCC9.3

### ISSUE THREAD

**Issue by Leslie-Fang** [tensorflow/tensorflow#41020]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):   https://github.com/tensorflow/tensorflow/archive/v1.15.3.zip
- TensorFlow version: 1.15.3
- Python version: 3.8
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): GCC 9.3
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Build failed with error message:
```
external/grpc/src/core/lib/gpr/log_linux.cc:43:13: error: ambiguating new declaration of 'long int gettid()'
   43 | static long gettid(void) { return syscall(__NR_gettid); }
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
bazel --output_user_root=$build_dir build --config=mkl --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mavx512f --copt=-mavx512cd  //tensorflow/tools/pip_package:build_pip_package 2>&1 | tee /root/build.log
```

Refer to this issue: https://github.com/grpc/grpc/issues/20043
May need to upgrade the grpc version.

**Comment by mihaimaruseac** [comment]
We need a PR to upgrade `grpc` version. Can you send it please?

**Comment by mihaimaruseac** [comment]
Oh, this is against `r1.15`. That branch is fixed, we only update it for security reasons.

**Comment by Leslie-Fang** [comment]
@mihaimaruseac Thanks for the feed-back. I see there is a release of r1.15.3 last monthly. If we still plan some release based on r1.15, may be we can submit a PR to that branch then?

**Comment by mihaimaruseac** [comment]
If `grpc` version bump covers a security vuln yes, we can accept it. Otherwise, unfortunately, we cannot justify a version bump.

**Comment by Leslie-Fang** [comment]
@mihaimaruseac Thanks for the reply. I don't think there is a security issue. So I will close this issue ticket.
