### ISSUE TITLE
Overhead of calling " ModifyGraphWithDelegate() "

### ISSUE THREAD

**Issue by babuya7** [tensorflow/tensorflow#41024]
**System information**
- I have written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04):
- Mobile device : Qualcomm 855
- TensorFlow installed from source:
- TensorFlow version r.14:
- Python version 3.6:
- Bazel version : 3.1:
- GCC/Compiler version : ndk21_rb
- GPU model and memory:

We are running inference on GPU using TFLite. We observed that invoking ModifyGraphWithDelegate() takes 22 second on Qualcomm 855 device.
This time is so huge, We are not able to find any other way to reduce the 22 second overhead.

Is there any way to get ride of this overhead.
Could you please help me .

**Comment by brucechou1983** [comment]
@impjdi 

This issue becomes critical in Android 11. We got a lot of ANR timeout warning messages when launching GPU delegate.

**Comment by impjdi** [comment]
Oh my apologies.  Didn't notice this bug assigned to me.  For optimal performance, it performs some auto tuning which can take a long time.  If you want to bypass this auto tuning phase, you can set `TFLITE_GPU_INFERENCE_PREFERENCE_FAST_SINGLE_ANSWER`, but your performance may not be as optimal.
