### ISSUE TITLE
ImportError: Traceback

### ISSUE THREAD

**Issue by thiagohlopes** [tensorflow/tensorflow#41032]
**System information**
- Windowns 10
- 
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version: Python 3.7.7
- Installed using virtualenv? pip? conda?: pip install tensorflow    was(2.1.1)  and      pip install --upgrade tensorflow    was (2.2)
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: galaxy gt 1030 (2Gb) / 8Gb(ram)

ImportError: Traceback (most recent call last):
  File "C:\Users\thiag\miniconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\thiag\miniconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\thiag\miniconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\thiag\miniconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\thiag\miniconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Uma rotina de inicialização da biblioteca de vínculo dinâmico (DLL) falhou.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by amahendrakar** [comment]
@thiagohlopes,

Please check [this comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156
) thread from a similar issue and let us know if it helps. Thanks!

**Comment by amitpsingh1** [comment]
Please close all sessions of Jupyter Notebook and relaunch. Try to import again as a first step and it should work fine.
