### ISSUE TITLE
Error while saving a model with one layer having a list of one ragged item

### ISSUE THREAD

**Issue by tanguycdls** [tensorflow/tensorflow#41034]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 2.3.rc0
- TensorFlow version (use command below):
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
If you try to save a model which has a layer that takes only one ragged input in a list you can save it but not load it. 

**Describe the expected behavior**
To be able to load it back. 

**Standalone code to reproduce the issue**

````
import tensorflow as tf
class Test(tf.keras.layers.Layer):
  def call(self, inputs):
    return inputs[0][0][0]

a = tf.keras.layers.Input(ragged=True, shape=(None,))
m = tf.keras.models.Model(a, Test()([a]))
m.save('test')
tf.keras.models.load_model('test')
`````
> ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (1 total):
    * tf.RaggedTensor(values=Tensor("inputs:0", shape=(None,), dtype=float32), row_splits=Tensor("inputs_1:0", shape=(None,), dtype=int64))
  Keyword arguments: {}
Expected these arguments to match one of the following 1 option(s):
Option 1:
  Positional arguments (1 total):
    * [RaggedTensorSpec(TensorShape([None, None]), tf.float32, 1, tf.int64)]
  Keyword arguments: {}

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Link to gist: https://colab.research.google.com/gist/tanguycdls/cfbed31d313c247d2dc9d12bc19148cc/untitled20.ipynb

**Comment by Saduf2019** [comment]
@tanguycdls 
I ran the code shared and face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/7d4d902cbe7cecdf4281ee077d2d7bf2/untitled251.ipynb).

**Comment by tanguycdls** [comment]
@Saduf2019 I think you imported keras from keras.layers.input and not tf.keras.
 Input has a keyword argument ragged described here: https://www.tensorflow.org/api_docs/python/tf/keras/Input

**Comment by Saduf2019** [comment]
@tanguycdls 
Can you please share a executable gist with the error faced.

**Comment by tanguycdls** [comment]
> @tanguycdls
> Can you please share a executable gist with the error faced.

Yes Link to gist: https://colab.research.google.com/gist/tanguycdls/cfbed31d313c247d2dc9d12bc19148cc/untitled20.ipynb
Does it work? it was on the issue.

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/4f689f0495d0753ad9155eb624b22477/untitled264.ipynb).

**Comment by tanguycdls** [comment]
Issue is still happening in TF2.4rc2 :(

**Comment by tanguycdls** [comment]
Still an issue in TF2.5.rc1

**Comment by saikumarchalla** [comment]
issue still exist in TF 2.5 stable version. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/b48945bdaeed3129482d23a664004c71/untitled86.ipynb).

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
