### ISSUE TITLE
Build failure while following TensorFlow from source following TF documentation

### ISSUE THREAD

**Issue by mkolod** [tensorflow/tensorflow#4103]
### Problem

TensorFlow build  of the pip package with CUDA support using the following command, taken from the [TensorFlow documentation](https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#installing-from-sources), fails:

```bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package```

### Error message

```
/usr/include/string.h: In function 'void* __mempcpy_inline(void*, const void*, size_t)':
/usr/include/string.h:652:42: error: 'memcpy' was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
ERROR: /home/marek/src/tensorflow/tensorflow/contrib/rnn/BUILD:63:1: output 'tensorflow/contrib/rnn/_objs/python/ops/_gru_ops_gpu/tensorflow/contrib/rnn/kernels/gru_ops_gpu.cu.pic.o' was not created.
ERROR: /home/marek/src/tensorflow/tensorflow/contrib/rnn/BUILD:63:1: not all outputs were created.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

### Environment

- OS: Ubuntu 16.04 (64-bit)
- CUDA 8.0
- GCC 4.9.3
- Java 1.8 (r101_b13)
- Python 2.7.12 (Anaconda 4.1.1)
- Bazel 0.3.1

### Related problems for CUDA-based frameworks reported on StackOverflow and Github
https://github.com/tensorflow/tensorflow/issues/1346
https://github.com/torch/torch7/issues/670
https://github.com/BVLC/caffe/issues/4046
https://github.com/opencv/opencv/issues/6500

### Solutions tried (none of them worked)

- downgrading to CUDA 7.5 and CUDNN 4
- changing downgrading and upgrading GCC away from 4.9.3
- changing GCC and cmake options to include ```-D_FORCE_INLINES``` flag (see related Github issues above)

### Solution that worked

Build succeeds when the ```-c opt``` option is removed from the Bazel build command. That is, the final command should be

```bazel build --config=cuda //tensorflow/tools/pip_package:build_pip_package```

**Comment by martinwicke** [comment]
I am stumped. Omitting -c opt is certainly unpleasant. We're upgrading our test servers to 16.04, so we should either hit this soon, or it's very mysterious indeed.

**Comment by xu1985129** [comment]
Well, first time post on github. @mkolod @martinwicke the problem may be solved by 'sed -i "s/nvccopts = ''/nvccopts = '-D_FORCE_INLINES '/g" './third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl'', which replaces the empty nvccopts with a starting flag '-D_FORCE_INLINES ' from tensorflow root.
However, my environment differences are 
CUDA 7.5
GCC 4.9.4
Python 3.5.2 :: Anaconda 4.1.1 (64-bit)

another theoretical solution may be 
'bazel build -c opt --config=cuda --verbose_failures //tensorflow/tools/pip_package:build_pip_package --per_file_copt=//tensorflow/.*\.cu\.cc@-D_FORCE_INLINES', which does roughly similar thing as above. However, I haven't checked this solution.
Anyway, the point is to add an extra flag of '-D_FORCE_INLINES' to nvcc complier
