### ISSUE TITLE
Accuracy Benchmarks

### ISSUE THREAD

**Issue by uu-praveeng** [tensorflow/tensorflow#41038]
Hi,

I am trying to find the baseline results for Top-1 accuraciesfor different tensorflow models .
I found more than one link. Could not decide which accuracies are latest and valid results. Below are the links for your reference. Let me know which link to be considered  for baseline/latest.

https://www.tensorflow.org/lite/performance/model_optimization 
https://blog.tensorflow.org/2020/04/quantization-aware-training-with-tensorflow-model-optimization-toolkit.html 
https://blog.tensorflow.org/2019/06/tensorflow-integer-quantization.html 
https://www.tensorflow.org/lite/guide/hosted_models 

Thank you,
Praveen.

**Comment by Saduf2019** [comment]
@uu-praveeng 
Please check [link](https://blog.tensorflow.org/2020/04/quantization-aware-training-with-tensorflow-model-optimization-toolkit.html), as per the latest date on it, and let us know
