### ISSUE TITLE
Abandon the use of abseil internal API absl::base_internal::NominalCPUFrequency

### ISSUE THREAD

**Issue by Sidong-Wei** [tensorflow/tensorflow#41033]
Currently, an Abseil internal API is used [here](https://github.com/tensorflow/tensorflow/blob/62b6c316d2a9a1fb06aefb086856e76241280c08/tensorflow/core/platform/default/port.cc#L348), but according to Abseil's [Compatibility Guidelines](https://abseil.io/about/compatibility), the internal API should not be used outside of Abseil library.

The reason I raise this issue is that this API has been broken on s390x machines for a while, as I was trying to fix this issue, the Abseil community told me that this method was not called by any Abseil code, and Tensorflow should not depend on this API, see [here](https://github.com/abseil/abseil-cpp/pull/728#issuecomment-652044095). So even though this API is working on most architectures, I suggest abandon the use of this API and try to find an alternative one to avoid depending on Abseil internal APIs.

**Comment by Sidong-Wei** [comment]
Hi @gunan , would you mind taking a look at this issue? Thanks.

**Comment by gunan** [comment]
We definitely do not want to depend on this. However I have been swamped with other things.
I will try to do this the first chance I get. In case anyone else would like to contribute, I believe this can be a nice simple contribution to TF.

**Comment by Sidong-Wei** [comment]
Thanks for the reply, I just have one thought that is it possible to reuse the implementation of cpu frequency [here](https://github.com/tensorflow/tensorflow/blob/5491487f9a17d5012808c505cb27375cf7e12ccf/tensorflow/core/platform/profile_utils/cpu_utils.cc#L71) in this case?

**Comment by gunan** [comment]
It is definitely possible!
would you like to make the change?

**Comment by Sidong-Wei** [comment]
Sure, I can give it a try, I think it should be a relatively simple patch.
