### ISSUE TITLE
FP32 model performance is better than quant model using TFLite on raspi 3 for mobilenetv2 

### ISSUE THREAD

**Issue by uu-praveeng** [tensorflow/tensorflow#41035]
Hi,

I have checked out the the tensorflow master and built the tflite library on raspi3. When I use the label_image.cpp and pass in the  mobilenet_v2_1.0_224.tflite and execute , its performance is better than mobilenet_v2_1.0_224_quant.tflite model .  Ideally quant model performance should better than FP32. Below are the numbers that are observed  
For FP32 -332 ms
For quant  model - 538 ms.

Is this a known issue? Could you check the same on your side and clarify.

Note: I do not see the same issue with mobilenetv1_1.0_224.tflite model. In mobilenetv1 quant model performs better than FP32.

Thank you,
Praveen.

**Comment by advaitjain** [comment]
Adding @petewarden for raspberry pi performance.
