### ISSUE TITLE
 Failed launching ResizeNearestNeighbor

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/tensorflow#41049]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):2.3.0-rc0
- Python version:3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:7.6.5.32-1+cuda10.2
- GPU model and memory:mx150

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
tensorflow.python.framework.errors_impl.InternalError: Failed launching ResizeNearestNeighbor [Op:ResizeNearestNeighbor]
![Screenshot from 2020-07-03 13-07-02](https://user-images.githubusercontent.com/17592563/86433753-27142b80-bd2e-11ea-8eec-604f6e875fce.png)
[tf_env.txt](https://github.com/tensorflow/tensorflow/files/4867906/tf_env.txt)
**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```python
tf.image.resize(tf.ones([1,416,416,3]),[200,100],tf.image.ResizeMethod.NEAREST_NEIGHBOR, preserve_aspect_ratio=True)
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Related https://github.com/google/automl/pull/536

I used GPU

I can't meet any bug when I ran GPU kernel tests.

**Comment by gowthamkpr** [comment]
@fsx950223 Can you try using CUDA 10.1 and let me know if you are running into the same error? Thanks!

**Comment by gowthamkpr** [comment]
@fsx950223 I am not able to reproduce this in colab. Heres my [gist](https://colab.research.google.com/gist/gowthamkpr/5bff9e1a09be1beebd055ff8b8837d70/untitled293.ipynb). Can you try using CuDA 10.1 and see if you are running into the same issue. Thanks!

**Comment by fsx950223** [comment]
> @fsx950223 I am not able to reproduce this in colab. Heres my [gist](https://colab.research.google.com/gist/gowthamkpr/5bff9e1a09be1beebd055ff8b8837d70/untitled293.ipynb). Can you try using CUDA 10.1 and see if you are running into the same issue. Thanks!

It worked on tf2.2.

**Comment by gowthamkpr** [comment]
@fsx950223 If you see in my gist, its working on 2.3.0rc0 too. Can you please be specific about this issue as I am not running into the issue on Colab.

**Comment by fsx950223** [comment]
> @fsx950223 If you see in my gist, its working on 2.3.0rc0 too. Can you please be specific about this issue as I am not running into the issue on Colab.

I have uploaded my env info. [tf_env.txt](https://github.com/tensorflow/tensorflow/files/4867906/tf_env.txt)

**Comment by hyeygit** [comment]
I am not able to reproduce the issue. How was tensorflow (that is throwing the error) installed?

**Comment by fsx950223** [comment]
> I am not able to reproduce the issue. How was tensorflow (that is throwing the error) installed?

I installed tf2.3rc0 in two computers by pip binary, they have same problem.

**Comment by mihaimaruseac** [comment]
I was unable to reproduce either.

Can you please post output of `pip list` and attach `log.txt` obtained after running `python -vvv -c "import tensorflow as tf; print(tf.image.resize(tf.ones([1,416,416,3]),[200,100],tf.image.ResizeMethod.NEAREST_NEIGHBOR, preserve_aspect_ratio=True))" &> log.txt`?

**Comment by fsx950223** [comment]
[log.txt](https://github.com/tensorflow/tensorflow/files/4906414/log.txt)
[pip.txt](https://github.com/tensorflow/tensorflow/files/4906417/pip.txt)

**Comment by fsx950223** [comment]
I fix the bug by ```apt-get install cuda-cudart-10-2```
