### ISSUE TITLE
Feature request: Tensor decomposition

### ISSUE THREAD

**Issue by 015988** [tensorflow/tensorflow#4104]
( Related to issue https://github.com/tensorflow/tensorflow/issues/2207 )

Tensors can be used for a whole lot more than implementing a NN. One of the useful operations in multidimensional arrays is its decomposition into smaller components. Tucker / CP native implementations would allow the use of tensorflow in other ML contexts...

refs: 
https://en.wikipedia.org/wiki/Tensor_rank_decomposition
https://en.wikipedia.org/wiki/Higher-order_singular_value_decomposition

**Comment by rmlarsen** [comment]
@015988 Thanks for the suggestion. I agree that TensorFlow would be well suited for the class of algorithms you mention, but this is probably out of scope for core TensorFlow at this point, and should probably live in an independent repository.

**Comment by ebigelow** [comment]
@015988 I've recently implemented tucker and CP decompositions in TensorFlow ([tf-decompose](https://github.com/ebigelow/tf-decompose)). Any contributions there would be welcome!

**Comment by nlw0** [comment]
Just adding a bit to the discussion. It may not be clear and obvious right now, but Tensor decomposition has a chance of becoming very relevant for image analysis, what is probably well within the scope of TensorFlow right now. Let's wait and see...

**Comment by bionicles** [comment]
this would be extremely useful for big data DR in molecular dynamics
