### ISSUE TITLE
Can I compile the source code of TF1.10 with gcc8.3？

### ISSUE THREAD

**Issue by AI-Friend** [tensorflow/tensorflow#41048]
**I use gcc8.3, but when installing TF1.10, the error is as follows. Can I compile the source code of TF1.10 with gcc8.3？**

command: `python -m joyTf/ --model deepwalk ...`

```
Log:
_OPS_PATH=/export/home/lijunli/joyGraph/joyOps/lib/libjoy_ops.so
Traceback (most recent call last):
  File "/export/home/joyGraph-env/python_3.6/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/export/home/joyGraph-env/python_3.6/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/export/home/joyGraph-env/python_3.6/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/export/home/lijunli/joyGraph/joyTf/__init__.py", line 18, in <module>
    from joyTf.python.joy_ops import *
  File "/export/home/lijunli/joyGraph/joyTf/python/joy_ops/__init__.py", line 22, in <module>
    from joyTf.python.joy_ops.base import initialize_graph
  File "/export/home/lijunli/joyGraph/joyTf/python/joy_ops/base.py", line 34, in <module>
    JOY_OPS = tf.load_op_library(_OPS_PATH)
  File "/export/home/joyGraph-env/python_3.6/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /export/home/lijunli/joyGraph/joyOps/lib/libjoy_ops.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**It is strange that this error is not reported when I use tf1.10-gpu on the GPU machine, 
but it is still the same when using other tf1.x-gpu versions.
What is the cause of this error？**

Thank you for the answer!

**Comment by amahendrakar** [comment]
@AI-Friend,
TensorFlow 1.10 is not actively supported. Please try installing TensorFlow 2.x or 1.15 and let us know if you are facing the same issue.

Also, please take a look at the [tested build configurations](https://www.tensorflow.org/install/source#cpu) while building TensorFlow. Thanks!

**Comment by mihaimaruseac** [comment]
Supported build configurations during release time are at https://www.tensorflow.org/install/source#cpu

**Comment by AI-Friend** [comment]
I re installed tf1.15.0, and then put libtensorflow_ framework.so .1 copy to /usr/lib, then call or report this error. Do I have to compile the source code of TF1.15.0 with gcc8.3?

**Comment by mihaimaruseac** [comment]
This looks like a link issue, you need to find which library provides `_ZNK4Json5Value14getMemberNamesEv` and make sure you link against that/load it. I don't think this comes from TensorFlow (on a quick search, I could not find a `Json::Value::getMemberNames` method in TF code)

**Comment by AI-Friend** [comment]
Yes, this problem has been solved. Thank you very much！

**Comment by mihaimaruseac** [comment]
Perfect. Closing the issue as resolved.
