### ISSUE TITLE
Cuda 11.0 with cuDNN v8.0.1 problem when using GPU : libcudnn.so.7: cannot open shared object file

### ISSUE THREAD

**Issue by jbuisine** [tensorflow/tensorflow#41041]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Debian GNU/Linux 10 (buster)`
- TensorFlow installed from (source or binary): `binary`
- TensorFlow version: `2.2.0`
- Python version: `3.7.0`
- Installed using virtualenv: from `pyenv` using `pip`
- CUDA/cuDNN version: `11.0 / v8.0.1`
- GPU model and memory: `NVIDIA Corporation TU102 [GeForce RTX 2080 Ti Rev. A]`

**Problem encountered:**

I first installed cuda 11.0 using [runfile](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=runfilelocal):
```bash
wget http://developer.download.nvidia.com/compute/cuda/11.0.1/local_installers/cuda_11.0.1_450.36.06_linux.run
sudo sh cuda_11.0.1_450.36.06_linux.run
```
Then installed cuDNN v8.0.1 (`cuDNN Library for Linux (x86)`) following Nvidia website : [https://developer.nvidia.com/rdp/cudnn-download](https://developer.nvidia.com/rdp/cudnn-download)

```bash
tar -xzvf cudnn-x.x-linux-x64-v8.x.x.x.tgz

sudo cp cuda/include/cudnn*.h /usr/local/cuda/include
sudo cp cuda/lib64/libcudnn* /usr/local/cuda/lib64
sudo chmod a+r /usr/local/cuda/include/cudnn*.h /usr/local/cuda/lib64/libcudnn*
```

I configured some PATH variables into my `~/.bashrc` and reload it using `source`:
```bash
export PATH=/usr/local/cuda-11.0/bin:${PATH}
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH=/usr/local/cuda-11.0/lib64:${LD_LIBRARY_PATH}
export CUDA_HOME=/usr/local/cuda
```

**_Encountered problem_** with `libcudnn.so.7` which is not found: 
```bash
2020-07-02 21:06:53.502117: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.0/lib64:/usr/local/cuda/lib64:
2020-07-02 21:06:53.502124: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
```

The problem was as I installed cuDNN v8.0.1, hence the expected share object file is now (and cannot be found by TensorFlow):
```bash
/usr/local/cuda/lib64/libcudnn.so.8
```
I do not know if I have to reconfigure TensorFlow to tell him the cuDNN version. I fixed the problem (worst fix ever) doing:

```bash
sudo mv /usr/local/cuda/lib64/libcudnn.so.8 /usr/local/cuda/lib64/libcudnn.so.7
```

Now, TensorFlow can recognized the share object file... When lauching a neural network training script, now my GPU is used and seems to work well:
```bash
I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
...
Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10211 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:2d:00.0, compute capability: 7.5)
```

Can you please tell me how I can fix this problem following a better way always using my virtualenv ?

**Comment by TheNewSound** [comment]
Tensorflow is compiled for a specific CUDA + cuDNN version. Either build from source or down grade these CUDA libraries.

By the way people constantly post these kind of questions. Maybe one should train a tensorflow bot to detect questions + auto close and reply to questions like these.

**Comment by jbuisine** [comment]
Hello,

Thank you for your comment.

I agree with you and I've never said otherwise before. The problem here is that I want to go through a python virtual environment and unless I'm wrong, it doesn't seem to me that it's possible to retrieve a binary version via the python manager package with the latest version of cuda (or at least target a cuda version). I just wanted to know if it was possible and if so, how.

**Comment by Saduf2019** [comment]
@jbuisine 
Please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/39247#issuecomment-628924933) and let us know if it helps.
#40423 [link](https://github.com/tensorflow/tensorflow/issues/40278#issuecomment-643252454)

**Comment by jbuisine** [comment]
I tried to install Tensorflow 2.3.0 as well but the cuDNN 8.0.1 library is always not found.

**Comment by gowthamkpr** [comment]
As shown in the [documentation](https://www.tensorflow.org/install/source#gpu) for tensorflow 2.2.0 use CUDA 10.1 and CuDNN 7.6 and let me know if the problem still persists. Thanks!

**Comment by jbuisine** [comment]
It seems I need last cuda version for my GPU and hence cuDNN 8.0.1, that's why I opened this issue

**Comment by gowthamkpr** [comment]
@jbuisine As mentioned [here](https://www.tensorflow.org/install/source#gpu), please try using cuDNN 7.6 and let me know if you are running into the same error. Thanks!

**Comment by jbuisine** [comment]
@gowthamkpr Sorry for the delay in answering. My GPU card seems to really need cuda v11.0, hence cuDNN v8.0.1. Compiling tensorflow from scratch works but the issue was using the available binary from pip (it seems to not have v11.0 cuda support as indicated in your link). You can close the issue if you want.

**Comment by gowthamkpr** [comment]
@jbuisine Glad that its working. I am gonna go ahead and close this issue. Thanks!

**Comment by Joeytje50** [comment]
> Tensorflow is compiled for a specific CUDA + cuDNN version. Either build from source or down grade these CUDA libraries.
> 
> By the way people constantly post these kind of questions. Maybe one should train a tensorflow bot to detect questions + auto close and reply to questions like these.

Instead of creating a bot to reply with that answer to people asking this, it would probably be useful if _any_ other place on the internet would mention this. Your comment is the only place where I can find this claim. For example, https://www.reddit.com/r/nvidia/comments/hg45ux/is_cuda_11_compatible_with_tensorflow/ claims that because of backwards compatibility it should work just fine...

Creating a bot to respond to people is not solving the problem of bad documentation of this fact. It's just solving the symptom of people getting confused by this.

**Comment by Muhammad-Talha-MT** [comment]
@jbuisine 
Run this command
`source /home/{user_name}/.bashrc`

You must have these two environment variables there "PATH" & "LD_LIBRARY_PATH" and also cuda variable 

export PATH="/usr/local/cuda-11.4/bin:$PATH"
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda-11.4/lib6

If you don't have these variables there you must add them. Otherwise, you will face this issue.
