### ISSUE TITLE
Could not find a version that satisfies the requirement tensorflow-gpu==1.15.0

### ISSUE THREAD

**Issue by uday60** [tensorflow/tensorflow#41054]
1.15.0 version is available as can be show here:
https://pypi.org/project/tensorflow-gpu/1.15.0/

However while running the command:

> pip install tensorflow-gpu==1.15.0

I am getting the following output:

  Could not find a version that satisfies the requirement tensorflow-gpu==1.15.0 (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.9.0, 1.10.0, 1.10.1, 1.11.0, 1.12.0, 1.12.2, 1.12.3, 1.13.1, 1.13.2, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow-gpu==1.15.0

**Comment by ravikyram** [comment]
@uday60 

I tried in colab and i am not seeing any issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/2050ea3d295e142484d0cb97f8b2c671/untitled78.ipynb).Thanks!

**Comment by uday60** [comment]
@ravikyram Somehow it is working now. I guess someone fixed the issue without accepting the bug.
