### ISSUE TITLE
C++ compilation error when building tensorflow/examples/android:tensorflow.demo

### ISSUE THREAD

**Issue by Regulater27** [tensorflow/tensorflow#41059]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4
- Python version: 3.8.3
- Installed using virtualenv? pip? conda?: source
- Bazel version (if compiling from source): 3.3.0
- GCC/Compiler version (if compiling from source): Java JDK 11, Android ndk 20 and MSVS 2019
- CUDA/cuDNN version: NA
- GPU model and memory: NA

Brief description:
I have been trying to get this demo to work all week, getting various errors along the way.  However, I have run into this problem that doesn't have similar previously reported issues.  I get about 15 min into the bazel build command and it throws this error: ERROR: C:/users/adamr/tensorflow/tensorflow/examples/android/BUILD:23:10: C++ compilation of rule '//tensorflow/examples/android:libtensorflow_demo.so' failed (Exit 1): clang failed: error executing command

I have tried several versions of Android NDK and tried both MSVS 2017 and 2019. I also have msys64 installed and placed in my computers PATH.

After failed bazel build command, I clear the contents of my _bazel_adamr folder and run bazel clean --expunge.

Sequence of commands (all run on cmd):
git clone --recurse-submodules https://github.com/tensorflow/tensorflow.git
cd tensorflow

python configure.py
***
location of python: C:\Users\adamr\AppData\Local\Programs\Python\Python38\python.exe
Python libraries: C:\Users\adamr\AppData\Local\Programs\Python\Python38\lib\site-packages
ROCm support? N
CUDA support? N
optimization flags? Default
override eigen strong inline? n
interactively configure WORKSPACE? y
Android NDK path: C:/Users/adamr/AppData/Local/Android/android-ndk-r20b
NDK API: default
Android SDK: C:/Users/adamr/AppData/Local/Android/Sdk
SDK API: 29
Build tools: 30.0.0-rc4
***

bazel build -c opt --fat_apk_cpu=armeabi-v7a --record_rule_instantiation_callstack --experimental_repo_remote_exec --verbose_failures //tensorflow/examples/android:tensorflow_demo --host_crosstool_top=@bazel_tools//tools/cpp:toolchain

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Attached error Log:
[TensoflowDemoError.txt](https://github.com/tensorflow/tensorflow/files/4869078/TensoflowDemoError.txt)

**Comment by Saduf2019** [comment]
@Regulater27 
Can you please refer to this issue and let us know if it helps:
#38525

**Comment by Regulater27** [comment]
That thread is incredibly helpful, I can't believe I missed it!  Thank you, you can close this issue.

**Comment by Saduf2019** [comment]
Moving this to closed status with confirmation.
