### ISSUE TITLE
Error with the TF Dataset -Plant_Village 

### ISSUE THREAD

**Issue by davequinta** [tensorflow/tensorflow#41051]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution: Google Collab
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.2.0
- Python version:  3.6

**Describe the current behavior**

It happens when we(@Mtrejo and @DYuusha) try to use tfds.load of 'plant_village, it throws this error: 
DownloadError: Failed to get url https://data.mendeley.com/datasets/tywbtsjrjv/1/files/127d0761-7c63-46f0-b08e-d0d9f7cad9da/Plant_leaf_diseases_dataset_without_augmentation.zip. HTTP code: 404.

And it's because, the url is different from the ones in the docs.
**The correct one:** https://data.mendeley.com/datasets/tywbtsjrjv/1/files/d5652a28-c1d8-4b76-97f3-72fb80f94efc/Plant_leaf_diseases_dataset_without_augmentation.zip 

**The one in plant_village.py**: https://data.mendeley.com/datasets/tywbtsjrjv/1/files/127d0761-7c63-46f0-b08e-d0d9f7cad9da/Plant_leaf_diseases_dataset_without_augmentation.zip

**Describe the expected behavior**
Success of the tfds.load

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1aZ4EjqnNa8g0fWg9lccdJLmr0KU4ZL8r?usp=sharing

**Comment by davequinta** [comment]
I forgot to add that, before it works just fine.

**Comment by Saduf2019** [comment]
@davequinta 
Please confirm if the issue is resolved, so we could move the issue to closed status.

**Comment by davequinta** [comment]
No, it keeps throwing 404 in the URL of the dataset

**Comment by davequinta** [comment]
![TF_PLANT_VILLAGE](https://user-images.githubusercontent.com/11913893/86438167-40cc5900-bcc3-11ea-9454-02c7c0c5ec86.PNG)

**Comment by ymodak** [comment]
Thanks for the PR. Will keep this open till we merge the PR.
