### ISSUE TITLE
Build from Souce Failed Dependencies cudnn_stub.cc

### ISSUE THREAD

**Issue by JSunRae** [tensorflow/tensorflow#41057]
Hi All,

I have not been able to figure out what I need to do to fix this error, or what I have done wrong:

> ERROR: C:/users/jason/tensorflow/tensorflow/stream_executor/cuda/BUILD:319:11: undeclared inclusion(s) in rule '//tensorflow/stream_executor/cuda:cudnn_stub': this rule is missing dependency declarations for the following files included by 'tensorflow/stream_executor/cuda/cudnn_stub.cc': 'tensorflow/stream_executor/cuda/cudnn_version.h'
> Target //tensorflow/tools/pip_package:build_pip_package failed to build
> INFO: Elapsed time: 1331.616s, Critical Path: 270.82s
> INFO: 5993 processes: 5993 local.
> FAILED: Build did NOT complete successfully

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from: source
- TensorFlow version:
- Python version: 3.7.7
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 3.3.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0
- GPU model and memory: RTX2070
- Intel(R0 Core i9-9980HK CPU

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
The last few steps I completed were:
1. cd tensorflow
2. python ./configure/py
  - No to ROCM support
  - Yes to CUDA support
  - Computer capability 6.1,7.5 (because I have an RTZ2070 and GTX1080TI). The second was not attached while running this.
  - Yes to eigen strong line
  - No to andriod workspace builds
3. bazel build //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
> INFO: From Compiling tensorflow/compiler/xla/shape_util.cc:
> C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include\numeric(35): warning C4244: '=': conversion from '_Ty' to '_Ty', possible loss of data
>         with
>         [
>             _Ty=tensorflow::int64
>         ]
>         and
>         [
>             _Ty=int
>         ]
> tensorflow/compiler/xla/shape_util.cc(1570): note: see reference to function template instantiation '_Ty std::accumulate<const __int64*,int,std::multiplies<tensorflow::int64>>(const _InIt,const _InIt,_Ty,_Fn)' being compiled
>         with
>         [
>             _Ty=int,
>             _InIt=const __int64 *,
>             _Fn=std::multiplies<tensorflow::int64>
>         ]
> INFO: From Compiling tensorflow/compiler/xla/service/hlo_lexer.cc:
> C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include\utility(152): warning C4244: 'initializing': conversion from '_Ty' to '_Ty2', possible loss of data
>         with
>         [
>             _Ty=google::protobuf::uint64
>         ]
>         and
>         [
>             _Ty2=unsigned int
>         ]
> tensorflow/compiler/xla/service/hlo_lexer.cc(415): note: see reference to function template instantiation 'std::pair<unsigned int,unsigned int>::pair<unsigned int&,size_t,0>(_Other1,_Other2 &&) noexcept' being compiled
>         with
>         [
>             _Other1=unsigned int &,
>             _Other2=size_t
>         ]
> tensorflow/compiler/xla/service/hlo_lexer.cc(415): note: see reference to function template instantiation 'std::pair<unsigned int,unsigned int>::pair<unsigned int&,size_t,0>(_Other1,_Other2 &&) noexcept' being compiled
>         with
>         [
>             _Other1=unsigned int &,
>             _Other2=size_t
>         ]
> ERROR: C:/users/jason/tensorflow/tensorflow/stream_executor/cuda/BUILD:319:11: undeclared inclusion(s) in rule '//tensorflow/stream_executor/cuda:cudnn_stub':
> this rule is missing dependency declarations for the following files included by 'tensorflow/stream_executor/cuda/cudnn_stub.cc':
>   'tensorflow/stream_executor/cuda/cudnn_version.h'
> Target //tensorflow/tools/pip_package:build_pip_package failed to build
> INFO: Elapsed time: 1331.616s, Critical Path: 270.82s
> INFO: 5993 processes: 5993 local.
> FAILED: Build did NOT complete successfully

**Comment by amahendrakar** [comment]
@JSunRae,
As mentioned in the [guide](https://www.tensorflow.org/install/source_windows) could you please try building TensorFlow from a different branch like `r2.2` or `r2.3.0-rc0`, instead of the master branch.

Also, please take a look at the [tested build configuration](https://www.tensorflow.org/install/source_windows#gpu) while building TensorFlow. Thanks!

**Comment by alanpurple** [comment]
same

**Comment by alanpurple** [comment]
@amahendrakar 
same with 2.3.0rc1

**Comment by amahendrakar** [comment]
> As mentioned in the [guide](https://www.tensorflow.org/install/source_windows) could you please try building TensorFlow from a different branch like `r2.2` or `r2.3.0-rc0`, instead of the master branch.
> 
> Also, please take a look at the [tested build configuration](https://www.tensorflow.org/install/source_windows#gpu) while building TensorFlow. Thanks!

@JSunRae,
Any updates regarding this? Please feel free to close the issue if resolved. Thanks!

**Comment by amahendrakar** [comment]
> same with 2.3.0rc1

@alanpurple,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by JSunRae** [comment]
Unfortunately, I tried both of those. Also retried other various versions. I have tried many different ways as well Bazel, Choco, etc erc I have been trying for 2 weeks and have given up. Every time I get a different issue that I cannot seem to get around. I am sticking with pip install for now.

**Comment by alanpurple** [comment]
There was a time I could build tensorflow with windows 10 easily....  the day was gone....long gone.

**Comment by srogatch** [comment]
Same with r2.3 .

**Comment by Zhaopudark** [comment]
Same with me

**Comment by surak** [comment]
@Zhaopudark Did you manage to fix?

**Comment by Zhaopudark** [comment]
> @Zhaopudark Did you manage to fix?

not yet. I will determine to try compiling tf2.2 with cuda10.2 and cudnn 8.0.2

**Comment by Zhaopudark** [comment]
> @Zhaopudark Did you manage to fix?

Thanks for your guide and this issues [https://github.com/tensorflow/tensorflow/issues/41446](https://github.com/tensorflow/tensorflow/issues/41446) first method. I have finally compiled tf2.3 on win10(2004)|python3.8.5|cuda11.0(Update 1)|cudnn8.0.2 successfully and test my original algorithms. It seems OK.

The problem about "dependencies of cudnn_stub.cc"  is in the file "//tensorflow/stream_executor/cuda/BUILD". Considering that I had build successfully with tensorflow master branch(Tf 2.4), I try to find the different part about "cudnn_stub" in both "//tensorflow/stream_executor/cuda/BUILD" file. The result is that tf2.3‘s file less the codes ":cudnn_version".

So, I modified "//tensorflow/stream_executor/cuda/BUILD" form line 319 to 329, adding ":cudnn_version" in the "cc_library"s member, "deps". As follows.

```C++
cc_library(
    name = "cudnn_stub",
    srcs = if_cuda_is_configured(["cudnn_stub.cc"]),
    textual_hdrs = glob(["cudnn_*.inc"]),
    deps = if_cuda_is_configured([
        "@local_config_cuda//cuda:cudnn_header",
        "//tensorflow/stream_executor/lib",
        "//tensorflow/stream_executor/platform:dso_loader",
        ":cudnn_version",
    ]),
)
```
Another problem about "CUB" can find methods in this issue [https://github.com/tensorflow/tensorflow/issues/41803](https://github.com/tensorflow/tensorflow/issues/41803)

**Comment by surak** [comment]
@Zhaopudark turns out that it's somewhere else. cudnn 8 has different headers from that cudnn.h and bazel fails to identify the correct version. It's at `third_party/gpus/cuda_configure.bzl` line 1164:

```python
    if [int(x) for x in cuda_config.cudnn_version.split(".")] < [8, 0]:
      cudnn_headers = ["cudnn.h"]
    else:
      cudnn_headers = ["cudnn_adv_infer.h",
                       "cudnn_adv_train.h",
                       "cudnn_cnn_infer.h",
                       "cudnn_cnn_train.h",
                       "cudnn_ops_infer.h",
                       "cudnn_ops_train.h",
                       "cudnn.h",
                       "cudnn_version.h",
                      ]
```

This cudnn version is somehow wrong. 

This is my patch:

```diff
--- third_party/gpus/cuda_configure.bzl.orig	2020-08-26 18:55:08.405838123 +0200
+++ third_party/gpus/cuda_configure.bzl		2020-08-26 19:24:47.466666178 +0200
@@ -1136,10 +1136,11 @@
         out_dir = "cuda/bin",
     ))
 
-    if [int(x) for x in cuda_config.cudnn_version.split(".")] < [8, 0]:
-      cudnn_headers = ["cudnn.h"]
-    else:
-      cudnn_headers = ["cudnn_adv_infer.h",
+    #if [int(x) for x in cuda_config.cudnn_version.split(".")] < [8, 0]:
+    #  cudnn_headers = ["cudnn.h"]
+    #else:
+    cudnn_headers = ["cudnn_adv_infer.h",
+                       "cudnn_backend.h",
                        "cudnn_adv_train.h",
                        "cudnn_cnn_infer.h",
                        "cudnn_cnn_train.h",
```

This will break with older cuDNNs, but turns out that because check fails, I really don't care. I only need this version of TensorFlow for the A100 gpus, which only support CUDA 11 and cuDNN 8+ anyway.

**Comment by sushreebarsa** [comment]
@JSunRae Is this still an issue? 
Could you please try with the latest TF v2.7.0 and have a look at the[ build from source](https://www.tensorflow.org/install/source_windows) , [tested build configurations](https://www.tensorflow.org/install/source_windows#gpu) ?Please let us know if it helps. Thank you!

**Comment by JSunRae** [comment]
I got it working but from memory I just gave up on building from source
