### ISSUE TITLE
APK size increased

### ISSUE THREAD

**Issue by truptigoqii** [tensorflow/tensorflow#41055]
I am using TensorFlow posenet module but it increases my APK size drastically is there any way to reduce model size.

**Comment by Saduf2019** [comment]
@truptigoqii 
Could you please share the code, fill in issue template for us to analyse the issue faced.

**Comment by truptigoqii** [comment]
i m using dependency in app gradle file
implementation 'org.tensorflow:tensorflow-lite:2.2.0'
and imported posenet Module in my app

**Comment by ymodak** [comment]
The posenet tflite model size is 12.7 mb
See https://www.tensorflow.org/lite/models/pose_estimation/overview
