### ISSUE TITLE
Rename tf.nn.swish to tf.nn.silu to give appropriate credit

### ISSUE THREAD

**Issue by TFUsers** [tensorflow/tensorflow#41066]
The swish was originally coined the "SiLU" in https://arxiv.org/pdf/1606.08415.pdf and https://arxiv.org/abs/1702.03118 long before the swish paper. Renaming other peoples' exact same ideas is unacceptable and tensorflow's naming convention implicitly erases the research and work of people outside of Google.
This request inspired by a [recent discussion](https://www.reddit.com/r/MachineLearning/comments/hkiyir/r_google_has_a_credit_assignment_problem_in/), but this problem has been brought up every few months for the past few years. In light of recent efforts to make the ML community more equitable and _fair_, this is a no-brainer and long overdue.

**Will this change the current api? How?**
tf.nn.swish ought to be renamed tf.nn.silu and both of the aforementioned papers will be cited in the documentation. At the very least they should be documented in the swish documentation already.

**Comment by rmlarsen** [comment]
Thank you for bringing this to our attention. Due to backwards compatibility constraints, we cannot remove tf.nn.swish, but we will a expose the same functionality as tf.nn.silu to give proper credit to the earlier invention.
