### ISSUE TITLE
Feature request: ability to sample from seq2seq decoder given input

### ISSUE THREAD

**Issue by grenager** [tensorflow/tensorflow#4106]
Given some particular encoder input, it would be great to be able to sample sequences from the embedding_tied_rnn_seq2seq decoder. To my understanding, at present, this is possible with the tied_rnn_seqw2seq decoder, by passing in a custom loop_function, but it isn't possible in the embedding version. It appears that only argmax is supported with the feed_previous parameter. This would be useful in dialog/conversation applications, and perhaps others.

.

**Comment by drpngx** [comment]
We're still working on seq2seq. Feel free to open a new github issue if the problem still persists in recent versions.
