### ISSUE TITLE
C++ compilation of rule '//tensorflow/python:bfloat16_lib' failed (Exit 1) tensorflow/python/lib/core/bfloat16.cc

### ISSUE THREAD

**Issue by miguel-santos** [tensorflow/tensorflow#41061]
I'm trying to build tf 1.15 from source (cpu-only), in order to convert an object detection model to tflite.

<pre>bazel build --config=v1 //tensorflow/tools/pip_package:build_pip_package
</pre>
------------------------

### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.04
-   **TensorFlow installed from (source or binary)**: source
-   **TensorFlow version (use command below)**: 1.15
-   **Python version**: 3.8
-   **Installed using virtualenv? pip? conda?: conda
-   **Bazel version (if compiling from source)**: 0.26.1
-   **GCC/Compiler version (if compiling from source)**: 7.5.0

<pre><font color="#CC0000"><b>ERROR: </b></font>/home/user/tensorflow/tensorflow/python/BUILD:329:1: C++ compilation of rule &apos;//tensorflow/python:bfloat16_lib&apos; failed (Exit 1)
tensorflow/python/lib/core/bfloat16.cc: In function &apos;bool tensorflow::{anonymous}::Initialize()&apos;:
tensorflow/python/lib/core/bfloat16.cc:634:36: error: no match for call to &apos;(tensorflow::{anonymous}::Initialize()::&lt;lambda(const char*, PyUFuncGenericFunction, const std::array&lt;int, 3&gt;&amp;)&gt;) (const char [6], &lt;unresolved overloaded function type&gt;, const std::array&lt;int, 3&gt;&amp;)&apos;
                       compare_types)) {
                                    ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note: candidate: tensorflow::{anonymous}::Initialize()::&lt;lambda(const char*, PyUFuncGenericFunction, const std::array&lt;int, 3&gt;&amp;)&gt;
                             const std::array&lt;int, 3&gt;&amp; types) {
                                                            ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note:   no known conversion for argument 2 from &apos;&lt;unresolved overloaded function type&gt;&apos; to &apos;PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}&apos;
tensorflow/python/lib/core/bfloat16.cc:638:36: error: no match for call to &apos;(tensorflow::{anonymous}::Initialize()::&lt;lambda(const char*, PyUFuncGenericFunction, const std::array&lt;int, 3&gt;&amp;)&gt;) (const char [10], &lt;unresolved overloaded function type&gt;, const std::array&lt;int, 3&gt;&amp;)&apos;
                       compare_types)) {
                                    ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note: candidate: tensorflow::{anonymous}::Initialize()::&lt;lambda(const char*, PyUFuncGenericFunction, const std::array&lt;int, 3&gt;&amp;)&gt;
                             const std::array&lt;int, 3&gt;&amp; types) {
                                                            ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note:   no known conversion for argument 2 from &apos;&lt;unresolved overloaded function type&gt;&apos; to &apos;PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}&apos;
tensorflow/python/lib/core/bfloat16.cc:641:77: error: no match for call to &apos;(tensorflow::{anonymous}::Initialize()::&lt;lambda(const char*, PyUFuncGenericFunction, const std::array&lt;int, 3&gt;&amp;)&gt;) (const char [5], &lt;unresolved overloaded function type&gt;, const std::array&lt;int, 3&gt;&amp;)&apos;
   if (!register_ufunc(&quot;less&quot;, CompareUFunc&lt;Bfloat16LtFunctor&gt;, compare_types)) {
                                                                             ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note: candidate: tensorflow::{anonymous}::Initialize()::&lt;lambda(const char*, PyUFuncGenericFunction, const std::array&lt;int, 3&gt;&amp;)&gt;
                             const std::array&lt;int, 3&gt;&amp; types) {
                                                            ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note:   no known conversion for argument 2 from &apos;&lt;unresolved overloaded function type&gt;&apos; to &apos;PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}&apos;
tensorflow/python/lib/core/bfloat16.cc:645:36: error: no match for call to &apos;(tensorflow::{anonymous}::Initialize()::&lt;lambda(const char*, PyUFuncGenericFunction, const std::array&lt;int, 3&gt;&amp;)&gt;) (const char [8], &lt;unresolved overloaded function type&gt;, const std::array&lt;int, 3&gt;&amp;)&apos;
                       compare_types)) {
                                    ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note: candidate: tensorflow::{anonymous}::Initialize()::&lt;lambda(const char*, PyUFuncGenericFunction, const std::array&lt;int, 3&gt;&amp;)&gt;
                             const std::array&lt;int, 3&gt;&amp; types) {
                                                            ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note:   no known conversion for argument 2 from &apos;&lt;unresolved overloaded function type&gt;&apos; to &apos;PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}&apos;
tensorflow/python/lib/core/bfloat16.cc:649:36: error: no match for call to &apos;(tensorflow::{anonymous}::Initialize()::&lt;lambda(const char*, PyUFuncGenericFunction, const std::array&lt;int, 3&gt;&amp;)&gt;) (const char [11], &lt;unresolved overloaded function type&gt;, const std::array&lt;int, 3&gt;&amp;)&apos;
                       compare_types)) {
                                    ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note: candidate: tensorflow::{anonymous}::Initialize()::&lt;lambda(const char*, PyUFuncGenericFunction, const std::array&lt;int, 3&gt;&amp;)&gt;
                             const std::array&lt;int, 3&gt;&amp; types) {
                                                            ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note:   no known conversion for argument 2 from &apos;&lt;unresolved overloaded function type&gt;&apos; to &apos;PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}&apos;
tensorflow/python/lib/core/bfloat16.cc:653:36: error: no match for call to &apos;(tensorflow::{anonymous}::Initialize()::&lt;lambda(const char*, PyUFuncGenericFunction, const std::array&lt;int, 3&gt;&amp;)&gt;) (const char [14], &lt;unresolved overloaded function type&gt;, const std::array&lt;int, 3&gt;&amp;)&apos;
                       compare_types)) {
                                    ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note: candidate: tensorflow::{anonymous}::Initialize()::&lt;lambda(const char*, PyUFuncGenericFunction, const std::array&lt;int, 3&gt;&amp;)&gt;
                             const std::array&lt;int, 3&gt;&amp; types) {
                                                            ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note:   no known conversion for argument 2 from &apos;&lt;unresolved overloaded function type&gt;&apos; to &apos;PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}&apos;
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
<font color="#4E9A06">INFO: </font>Elapsed time: 1344.879s, Critical Path: 142.68s
<font color="#4E9A06">INFO: </font>765 processes: 765 local.
<font color="#CC0000"><b>FAILED:</b></font> Build did NOT complete successfully
</pre>

--------
I've already downgraded numpy to <1.19.0, as mentioned in [#40688](https://github.com/tensorflow/tensorflow/issues/40688), but that didn't solve the problem.

**Comment by ymodak** [comment]
For TF 1.15 supported Python versions are 2.7, 3.3-3.7

**Comment by roastduck** [comment]
Same here with Python 3.7.6.

**Comment by CoolIceFire** [comment]
@

> For TF 1.15 supported Python versions are 2.7, 3.3-3.7
> See https://www.tensorflow.org/install/source#tested_build_configurations

my python version is 3.6.9, however I have the same problem.

**Comment by himanshu816** [comment]
use numpy version < 1.19.0 to resolve this issue under python3.6 environment.
pip install 'numpy<1.19.0'

**Comment by mars1248** [comment]
my python version is 3.6.9, bazel version is 0.19.2,gcc version is 4.8.4,numpy version is 1.18.5,however I have the same problem。i want compile tf1.13.1

**Comment by himanshu816** [comment]
> my python version is 3.6.9, bazel version is 0.19.2,gcc version is 4.8.4,numpy version is 1.18.5,however I have the same problem。i want compile tf1.13.1

**use bazel version 0.26.1 , gcc version 6.3 for better..**

these keras version for dependency installation for TF-1.15. 
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.2

for TF-1.13:
numpy=1.15.4
keras_applications==1.0.4 
keras_preprocessing==1.0.2

it should work.

**Comment by omi-engg** [comment]
Have tried all above options it is not working for both cpu as well as GPU versions

**Comment by lamhoangtung** [comment]
I have tried all above options it is not working as well. Noted that the only difference is my ubuntu version is 18.04, python is 3.7

**Comment by hamlatzis** [comment]
For TF 1.15 & 1.14 I have no problem, but for TF2 I have exactly the same problem and have tried all of the above

**Comment by himanshu816** [comment]
**Python** 3.6.9

**TF-1.14:**
pip install 'numpy<1.19.0'
pip install -U pip six wheel mock
pip  install future
pip install keras_applications==1.0.4 --no-deps
pip install keras_preprocessing==1.0.2 --no-deps
pip install pandas

**bazel version:** bazel-0.25.2-installer-linux-x86_64.sh

**TF-1.15 & TF-2.0:**
pip install 'numpy<1.19.0'
pip install -U pip six wheel mock
pip  install future
pip install keras_applications==1.0.8 --no-deps
pip install keras_preprocessing==1.1.2 --no-deps
pip install pandas

**bazel version:** bazel-0.26.1-installer-linux-x86_64.sh

during TF-1.15 & 2.0 build you may face problem related to zlib library. for that you can follow this.
[](https://github.com/tensorflow/tensorflow/issues/31196)

i am able to build for all cases.

**Comment by lamhoangtung** [comment]
@himanshu816. Look like I was missing `pandas`. The build is now complete. Thanks for your help!

**Comment by wookayin** [comment]
I think this should remain open. Even the latest version has a conflicting dependency with latest versions of numpy, pandas, etc.

**Comment by wookayin** [comment]
Duplicate of: #40688

**Comment by congjianting** [comment]
> my python version is 3.6.9, bazel version is 0.19.2,gcc version is 4.8.4,numpy version is 1.18.5,however I have the same problem。i want compile tf1.13.1

bazel clean firstly run after downgrading numpy, it worked for me.

**Comment by grmelacz** [comment]
> **TF-1.15 & TF-2.0:**
> pip install 'numpy<1.19.0'
> pip install -U pip six wheel mock
> pip install future
> pip install keras_applications==1.0.8 --no-deps
> pip install keras_preprocessing==1.1.2 --no-deps
> pip install pandas
> 
> 
> i am able to build for all cases.
Thanks! This approach worked just fine. No problems with zlib. Successfully built TF 2.3.2 on Ubuntu 18.04 LTS (Python 3.6.9, bazel 3.1.0, numpy 1.19.5, gcc 7.5.0)

**Comment by yongwww** [comment]
`pip install 'numpy<1.19.0'` works for me

**Comment by Asuna88** [comment]
Python 3.6.9

TF-1.14:
pip install 'numpy<1.19.0'
pip install -U pip six wheel mock
pip install future
pip install keras_applications==1.0.4 --no-deps
pip install keras_preprocessing==1.0.2 --no-deps
pip install pandas

bazel version: bazel-0.25.2-installer-linux-x86_64.sh

Useful for me!
