### ISSUE TITLE
How to load tensorflow lite during the reboot process 

### ISSUE THREAD

**Issue by MevadaRavikumar** [tensorflow/tensorflow#41063]
Hi, 

I am using Raspberry Pi 4, Model B, 8 GB RAM, Raspbian OS, Python 3.7. 
I am running on an object detection script that uses edgetpu.tflite model.  It works perfectly. Now I am trying to run that script automatically when I power up the Pi. 

I have tried this solution: 

    sudo nano /home/pi/.bashrc

add 

    echo Running at boot 
    sudo python /home/pi/sample.py

it gives me this error: 
    
        Running at boot
    Traceback (most recent call last):
      File "sample.py", line 92, in <module>
        from tensorflow.lite.python.interpreter import Interpreter
    ModuleNotFoundError: No module named 'tensorflow'

How can I run the script which uses modules like TensorFlow and TensorFlow Lite during the reboot or at the power-up?

**Comment by sushreebarsa** [comment]
@MevadaRavikumar Could you please let us know if this issue still persists ? Thanks!
