### ISSUE TITLE
tf.data, construct a batch with different data? Are there easy ways to do it? TensorFlow1.15

### ISSUE THREAD

**Issue by guotong1988** [tensorflow/tensorflow#41076]
I want to construct a batch of data with batchsize 16, using `tf.data`, where `[:8]` is a kind of data A, `[8:16]` is a kind of data B.

It is easy to do without `tf.data`. If use `tf.data`, the code could be:

```
def _decode_record(record, name_to_features):
    example = tf.parse_single_example(record, name_to_features)
    return example

dataA = tf.data.TFRecordDataset(input_files)
dataA = dataA.apply(
            tf.contrib.data.map_and_batch(
                lambda record: _decode_record(record, name_to_features),
                batch_size=batch_size)
           )
```
How to do it next? I try:
```
dataB = tf.data.TFRecordDataset(input_files2)
dataB = dataB.apply(
            tf.contrib.data.map_and_batch(
                lambda record: _decode_record(record, name_to_features),
                batch_size=batch_size)
           )
dataC = dataA.concatenate(dataB) 
```
But `concatenate` is: Append the whole dataset `dataB` to the end of `dataA`.

For `concatenate`, note that `name_to_features` should be same for `dataA` and `dataB`, which means I should pad a lot dummy data.

I don't want to use `tf.cond` or `tf.where` to judge different data inside the `model_fn` of `tf.estimator`, where it is also very hard to debug.

Are there easy ways to do it?

Thank you.

**Comment by guotong1988** [comment]
One solution is to judge different data:
```
import tensorflow as tf

data_type = tf.constant([1, 2, 1, 2])
where_index1 = tf.where(tf.equal(data_type, 1))
where_index2 = tf.where(tf.equal(data_type, 2))

data = tf.constant([[10,10],[20,20],[30,30],[40,40]])

data1 = tf.gather_nd(data,where_index1)
data2 = tf.gather_nd(data,where_index2)

sess = tf.Session()

print(sess.run(data1))
print(sess.run(data2))

```
But this answer just pass the question somehow.

**Comment by sanjoy** [comment]
CC @jsimsa

**Comment by guotong1988** [comment]
```
import tensorflow as tf

dataset_1 = tf.data.Dataset.from_tensors(1).repeat(100)
dataset_2 = tf.data.Dataset.from_tensors(2).repeat(100)

dataset = tf.data.Dataset.zip((dataset_1, dataset_2))
dataset = dataset.batch(8)
dataset = dataset.map(lambda a, b: tf.concat([a, b], 0))
```
I havn't try it in my real code.

**Comment by sachinprasadhs** [comment]
You can achieve this with `Batching datasets elements`  by simple batching using `tf.data.Dataset.zip` or batching tensors with padding using `dataset.padded_batch`. More details can be found [here](https://www.tensorflow.org/guide/data#batching_dataset_elements).
