### ISSUE TITLE
Dataset error with uc_merced dataset

### ISSUE THREAD

**Issue by gallorob** [tensorflow/tensorflow#41078]
**System information**
- Using Google Colab's default TF installation
- TensorFlow version: 2.2.0
- Python version: 3.6

**Describe the current behavior**
Dataset's samples are not all of the expected 256x256x3 shape, I found 44 out of 2100 samples with different shape. Currently, during preprocessing, I have to rescale the image if necessary.

**Describe the expected behavior**
All samples should have 256x256x3 shape.

**Standalone code to reproduce the issue**
```
import tensorflow.compat.v2 as tf
import tensorflow_datasets as tfds

dataset, info = tfds.load('uc_merced',
                            split='train',
                            as_supervised=True,
                            with_info=True,
                            shuffle_files=True)

exp_shape = (256, 256, 3)
n = 0
for sample in dataset.take(-1):
    if sample[0].shape != exp_shape:
        n += 1

print('Found {} samples with wrong shape'.format(n))
```

**Other info / logs**
`Found 44 samples with wrong shape`

**Additional notes**
This may seem to be a problem with the original dataset (http://weegee.vision.ucmerced.edu/datasets/landuse.html). If a fix is not possible, it may be a good idea to add a note in the documentation page https://www.tensorflow.org/datasets/catalog/uc_merced to let new users know about the issue.
Alternatively, a possible solution that the user would have to implement is something like:
```
def correct_dims(x, y):
    some_resizing_function(x, (256, 256, 3))
```
and after loading the dataset:
```
dataset = dataset.map(correct_dims)
```

**Comment by ravikyram** [comment]
I have tried in colab with TF versions 2.2,2.3-rc0 and nightly versions(`2.4.0-dev20200705`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/cab3b78ef9cebabe2b641cf9fb5e17e5/untitled81.ipynb).Thanks!

**Comment by MarkDaoust** [comment]
Hi, thanks for reporting this, but this is an issue with [tensorflow-datasets](https://github.com/tensorflow/datasets) can you rep[ort the issue there instead?
