### ISSUE TITLE
version cocossd 2.0.4 does not work use 2.0.3 model

### ISSUE THREAD

**Issue by el1tehAx0r** [tensorflow/tensorflow#41071]
so after the update 2.0.4 for coco-ssd cdn kept saying issues about loadmodelgraph undefined so I thought I would let you guys know to use 2.0.3 with this https://cdn.jsdelivr.net/npm/@tensorflow-models/coco-ssd@2.0.3 in your script tags otherwise you have have bad time cuz it didnt work when I just had https://cdn.jsdelivr.net/npm/@tensorflow-models/coco-ssd right after da update liek bro u gonna just make a new version dat ruin everyding.  LOL but ye jus bein bro lul

**Comment by ravikyram** [comment]
@el1tehAx0r 

I think this issue is more related to TF models repo. Please, raise an issue in models repo from [here](https://github.com/tensorflow/models/issues/new/choose).Thanks!
