### ISSUE TITLE
TPU errro InvalidArgumentError: NodeDef expected inputs 'string' do not match 0 inputs specified;

### ISSUE THREAD

**Issue by legacyai** [tensorflow/tensorflow#41075]
TPU is not working with any version greater than TF 2.2.0 . Even in TF 2.2.0, it gets stuck indefinitely. 

https://colab.research.google.com/gist/legacyai/0895547e3d7fa573aab03a2073afff7e/tpu.ipynb

**Comment by ravikyram** [comment]
I am not seeing any issue with TF version 2.2.0. However i am able to reproduce the issue in colab with TF versions 2.3-rc0 ,nightly versions(`2.4.0-dev20200703`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/19198e0210466deb8218777103608c5e/untitled80.ipynb).Thanks!

**Comment by frankchn** [comment]
This looks like it is a duplicate of #40622. There is probably a mismatch of TPU versions (Colab doesn't have 2.3 builds yet) causing the error (the OpKernel expects one thing on 2.3, but the TPU version itself is only 2.2).
