### ISSUE TITLE
Tensorflow Check failed: status == CUDNN_STATUS_SUCCESS (7 vs. 0)Failed to set cuDNN stream

### ISSUE THREAD

**Issue by sword134** [tensorflow/tensorflow#41087]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 8.1
- TensorFlow installed from (source or binary): Conda installation
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6.10
- CUDA version: 10.1.243
- cuDNN version:  7.6.5 (windows 7)
- GPU model and memory: GTX 1060 6GB

**Describe the current behavior**
When I run my tensorflow keras model it will sometimes stop after an epoch and throw the following error:

```
    tensorflow/stream_executor/dnn.cc:613] CUDNN_STATUS_EXECUTION_FAILED
    in tensorflow/stream_executor/cuda/cuda_dnn.cc(1867): 'cudnnRNNForwardTraining( cudnn.handle(), rnn_desc.handle(), model_dims.max_seq_length, input_desc.handles(), input_data.opaque(), input_h_desc.handle(), input_h_data.opaque(), input_c_desc.handle(), input_c_data.opaque(), rnn_desc.params_handle(), params.opaque(), output_desc.handles(), output_data->opaque(), output_h_desc.handle(), output_h_data->opaque(), output_c_desc.handle(), output_c_data->opaque(), workspace.opaque(), workspace.size(), reserve_space.opaque(), reserve_space.size())'
    2020-06-27 17:19:45.741256: F tensorflow/stream_executor/cuda/cuda_dnn.cc:189] Check failed: status == CUDNN_STATUS_SUCCESS (7 vs. 0)Failed to set cuDNN stream.
```

**Describe the expected behavior**
It should run the model without any crashes.

**Standalone code to reproduce the issue**
Im using the GPU version of tensorflow and it has worked without problems up until about 3 days ago when it began giving me this error. I also have the following callbacks in my model so that it saves checkpoints and epochs locally. Please note I am using Autokeras thus why the nodes have the ak. library prefix. However it works just like keras, it just automatically tries to find the best set of hyperparameters when running the .fit function.

```
input_node = ak.Input()
    #output_node1 = ak.Normalization()(input_node)
    output_node1 = ak.RNNBlock(return_sequences=True,
                               layer_type='lstm')(input_node)
    output_node2 = ak.RNNBlock(return_sequences=True,
                               layer_type='lstm')(output_node1)
    output_node3 = ak.RNNBlock(return_sequences=True,
                               layer_type='lstm')(output_node2)
    output_node4 = ak.RNNBlock(layer_type='lstm')(output_node3)
    output_node5 = ak.DenseBlock()(output_node4)
    output_node = ak.Merge()(
        [output_node1, output_node2, output_node3, output_node4, output_node5])
    output_nodefinal = ak.ClassificationHead()(output_node)
    
    my_callbacks = [tf.keras.callbacks.EarlyStopping(patience=15, restore_best_weights=True, monitor="val_accuracy", mode="auto"),
                    tf.keras.callbacks.ModelCheckpoint(filepath="D:\AutoKerasProject\TimeseriesCallbackModel\TimeseriesCallbackModel", save_weights_only=True, monitor='val_accuracy', mode='auto', save_best_only=True)]
    
    classifier = ak.AutoModel(
        inputs=input_node, outputs=output_nodefinal, max_trials=500, directory="D:\AutoKerasProject\TimeseriesModel", overwrite=True)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@sword134 
Please refer to the links below and let us know if it helps you resolve the issue.
#40877 #35950 #31645 #25709 #35791 #35950 [link](https://stackoverflow.com/questions/43147983/could-not-create-cudnn-handle-cudnn-status-internal-error) .

**Comment by v3551G** [comment]
I encounter the same problem, the problem only appears when Autograph was used when runing,
-----------------------------------
Configure: 
OS: Win10
GPU: RTX 2080TI
tensorflow: 2.1.0
CUDA: v11.0.167
CUDNN:  v8.0.1.13
----------------------------------
Two ways may help:
1.  Clear the template file at path: C:\Users\admin\AppData\Local\Temp
2.  Try simplify the network,
