### ISSUE TITLE
Invalid link in documentation to code: https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb

### ISSUE THREAD

**Issue by jajas** [tensorflow/tensorflow#41089]
TensorFlow documentation issue. 

## URL(s) with the issue:
The link/page not found(404); "images -> object detection API" under https://www.tensorflow.org/tutorials/
namely: https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb

## Description of issue (what needs changing):
Material was moved to https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb

**Comment by amahendrakar** [comment]
@jajas,
Looks like this issue is a duplicate of [#8736](https://github.com/tensorflow/models/issues/8736)

Can we close this issue since it is already being tracked in the models repo? Thanks!

**Comment by jajas** [comment]
@amahendrakar 
But https://www.tensorflow.org/tutorials/ should be fixed too

**Comment by amahendrakar** [comment]
@jajas,
Similar issue has been raised [here](https://github.com/tensorflow/models/issues/8698). 

Also, seems like the tutorials page has been updated. There is no `Object detection API` under `Images`. Instead it has been replaced with `Object detection with TF Hub`. 


![Screenshot 2020-07-12 at 10 06 55 PM](https://user-images.githubusercontent.com/57165142/87251846-4dec0380-c48c-11ea-989d-9f0cd044d217.png)

Please check the above image and feel free to close the issue if resolved. Thanks!
