### ISSUE TITLE
TFLite inference is slower than benchmark reported

### ISSUE THREAD

**Issue by andreydung** [tensorflow/tensorflow#41094]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Pixel 4
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.2.0
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
While I benchmark the tflite model using the benchmark tool, latency is only 6ms. However, when I actually run this inside an apk, the latency increases to 11ms. I'm wondering if it's due to the usage of buffer copy? Do they actually take that much time (~4ms)? Could you please suggest an alternative option that would be faster?

**Describe the expected behavior**

**Standalone code to reproduce the issue**

```
void mask_speech(const float* input, float* mask) {
    TfLiteTensor* tflite_input = TfLiteInterpreterGetInputTensor(interpreter, 0);
    TfLiteTensorCopyFromBuffer(tflite_input, input, NUM_INPUT * sizeof(float));
    TfLiteInterpreterInvoke(interpreter);
    const TfLiteTensor* tflite_output = TfLiteInterpreterGetOutputTensor(interpreter, 0);
    TfLiteTensorCopyToBuffer(tflite_output, mask, NUM_OUTPUT * sizeof(float));
}
```

Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by hajuho** [comment]
Hi,
The benchmark tool actually does not copy buffer while measuring the inference time repeatedly. So it might be possible.
Could you measure the time for copying buffer in your app to make it clear?
Also is there any heavy job on other thread while running your app?

**Comment by Saduf2019** [comment]
@andreydung 
Please update as per above comment.

**Comment by dhruv-arcot** [comment]
I'm facing a similar issue. The timings from the Benchmarking tool don't match that of the one's seen on Android Studio. The discrepence is large, almost double infact.

**Comment by dhruv-arcot** [comment]
@andreydung were you able to resolve this?
