### ISSUE TITLE
Unable to use tf-hub models locally

### ISSUE THREAD

**Issue by devspartan** [tensorflow/tensorflow#41092]
I've been working on a task using bert model [.](https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/2) As per the instructions I've added the line:

bert_layer = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/2", trainable=True)

But problem comes when it downloads the model again on every run. That's annoying. I've already spent a lot of time on searching How to download and work with tf-hub models . But i got no proper answer. That's why I'm here for guidance from official tf team.

I've downloaded the .tar.gz file from https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/2 and extracted the file. It contains <assets, variable, saved_model.pb>.

I've tried this
`
os.environ["TFHUB_CACHE_DIR"] = r'C:\Users\devendra\PycharmProjects\NeuralMachineTranslation\tf_hub'

handle = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/2"
hashlib.sha1(handle.encode("utf8")).hexdigest()
print(hashlib.sha1(handle.encode("utf8")).hexdigest())  #to rename directory

embed = hub.load("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/2")
print('Loaded')
print(embed)
`
but it is giving me error:
`FileNotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\devendra\PycharmProjects\NeuralMachineTranslation\tf_hub/ce53fe6769d2ac3a260e92555120c54e1aecbea6/variables/variables
 If trying to load on a different device from the computational device, consider using setting the `experimental_io_device` option on tf.saved_model.LoadOptions to the io_device such as '/job:localhost'.
`

I've using tensorflow and tf-hub latest upto the version on Ubuntu 18.04

 Now please guide me how to use the model properly and efficiently. Please provide concerned information and script. Thanking You.

**Comment by amahendrakar** [comment]
@devspartan,
Issues related to TF-Hub are handled in the hub repo.

Could you please submit a new issue using [this link](https://github.com/tensorflow/hub/issues/new) and fill in the template, so that we can track the issue there. Thanks!

**Comment by devspartan** [comment]
I've already submitted a issue over there. But i wasn't getting reply for 3 days. But i did get and it solved my problem. Sorry for inconvenience.
