### ISSUE TITLE
Issue using segment_prod in custom keras layer

### ISSUE THREAD

**Issue by pstjohn** [tensorflow/tensorflow#41090]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): colab
- TensorFlow installed from (source or binary): nightly
- TensorFlow version (use command below): nightly
- Python version: colab

I'm trying to write a custom keras layer that uses `segment_prod` on model features, i.e., not the batch dimension. To do that, I've been using tf.transpose to put the feature dimensions first, and then transposing the resulting calculation. Forward calculation seems to work using this approach, but there appears to be an issue with gradients with `segment_prod`: the following code fails with `LookupError: gradient registry has no entry for: SegmentProd`:

```python
class MyLayer1(layers.Layer):

  def call(self, inputs):

    segments = tf.constant([0, 0, 0, 1, 1])
    return tf.transpose(
        tf.math.segment_prod(tf.transpose(inputs), segments))

inputs = layers.Input(10)
embed = layers.Embedding(20, 5)(inputs)
output = MyLayer1()(embed)
output = layers.GlobalAveragePooling1D()(output)
model = tf.keras.Model(inputs, output)

X = np.random.randint(20, size=(100, 10))
y = np.random.randn(100,2)

model.compile(loss='mae')
model.fit(X, y)
```

Replacing `tf.math.segment_prod` with other operations, like `tf.math.unsorted_segment_prod(..., num_segments=2)` or `tf.math.segment_sum` seems to work, however.

Colab gist:
https://colab.research.google.com/gist/pstjohn/8fa2faf274679742ba628290a94c2b2b/untitled0.ipynb

**Comment by ravikyram** [comment]
I have tried in colab with TF versions 2.2,2.3-rc0,nightly versions(`2.4.0-dev20200705`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/95302a74087ba08432ece90213095b22/untitled83.ipynb).Thanks!
