### ISSUE TITLE
GPU is not running

### ISSUE THREAD

**Issue by Itzikwa** [tensorflow/tensorflow#41102]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 (on Azure VM)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.2.0
- Python version: 3.8.3
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA - 10.1, cuDNN - 7.6.4
- GPU model and memory: NVIDIA Tesla k80

**Describe the problem**
When I'm running  "tf.test.is_gpu_available()" I got False.

**Any other info / logs**
I installed c++ redistributable, cuda, cudnn and set the path environments as shown on the tensorflow gpu support.

**Comment by amahendrakar** [comment]
@Itzikwa,
Could you please run the below code and share the output with us

```
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
```
Thanks!

**Comment by Itzikwa** [comment]
Thank you for your response! I run the code and that what that came out:

`Num GPUs Available:  0`

**Comment by Itzikwa** [comment]
Hi, I just run the command on the cmd, and I noticed that for some reason tf couldn't open the cudnn64_7.dll file (it wasn't show up  when I run this command on the jupyter notebook), although I set it in the path as I mentioned above. So I move the file manually to a folder which I were sure tf could open successfully. 

Thanks a lot, and I'm sorry about my confusion...
