### ISSUE TITLE
GPU significantly slower than CPU on WSL 2 & nvidia-docker2

### ISSUE THREAD

**Issue by Scarysize** [tensorflow/tensorflow#41108]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows Subsystem For Linux 2 (WSL 2) with Ubuntu 20 LTS, Kernel 4.19.121-microsoft-standard**
- TensorFlow installed from (source or binary): **binary** (unsure, via pip install)
- TensorFlow version (use command below): **v1.15.2-30-g4386a66 1.15.3**
- Python version: **3.7.8**
- CUDA/cuDNN version: **libcudnn7-dev/now 7.6.4.38-1+cuda10.1 amd64**
- GPU model and memory: **RTX 2070, 8GB**

**Describe the current behavior**

Training is significantly slower on GPU compared to CPU (Intel Xeon E3-1230 v3, 3.30 GHz, 4 Cores)

**Describe the expected behavior**

Training is significantly faster on GPU

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

I'm using nvidia-docker2 with the tensorflow docker containers, I've verified that the GPU is in use when it's configured.

| python | container  | tensorflow | gpu | comment                                   | time      |
| ------ | ---------- | ---------- | --- | ----------------------------------------- | --------- |
| 3.7.8  | latest     | 1.15.3     | no  | desktop                                   | 7m24.035s |
| 3.7.8  | 1.15.2-gpu | 1.15.3     | yes | desktop, tf-gpu package                   | ~166m     |
| 3.7.8  | latest-gpu | 1.15.3     | no  | desktop, tf-gpu package                   | 6m30.067s |
| 3.7.8  | latest-gpu | 2.2.0      | yes | desktop, keras 2.4.x                      | ~175m     | 

I'm using keras with a sequential model (see below), doing reinforcement learning with 180 memory replays (model.fit) per episode.

```
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
reshape (Reshape)            (None, 40, 1)             0         
_________________________________________________________________
conv1d (Conv1D)              (None, 38, 16)            64        
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, 19, 16)            0         
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 17, 16)            784       
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 8, 16)             0         
_________________________________________________________________
flatten (Flatten)            (None, 128)               0         
_________________________________________________________________
dense (Dense)                (None, 48)                6192      
_________________________________________________________________
dense_1 (Dense)              (None, 24)                1176      
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 75        
=================================================================
Total params: 8,291
Trainable params: 8,291
Non-trainable params: 0
```

I'm going to try and provide a minimal python example ASAP.

**Comment by Saduf2019** [comment]
@Scarysize 
Can you please share a simple stand alone code such that we can replicate the issue faced.

**Comment by Scarysize** [comment]
I'm gonna close this for now, currently don't have the time to provide a script for reproduction.

**Comment by nicksahler** [comment]
I know that this ticket is closed, but if you could follow up with any other findings you had - I ran into the same thing on CUDA. Albeit with torch, my calls made for operations on the GPU are incredibly slow, slower even than CPU ops. It's very odd.

**Comment by m4gr4th34** [comment]
Apparently this is because CUDA is being run on a VM, according to these discussions.  I wish I had found this before installing WSL2 and cuda the past few hours.  It seemed too good to be true, and I guess it is.  :)  At least at this point.  I guess it's dual boot Debian for me now.

https://www.phoronix.com/scan.php?page=news_item&px=WSL2-CUDA-Perf-Early-Look

**Comment by nicksahler** [comment]
Ah - that's disappointing - but I'm not sure that's the sole reason given that VM performance overall is not much slower than bare-metal linux.

That said, I updated to the latest version of WSL and saw a decreates from about 60 seconds per iteration to 30 which is confidence building, but still painfully slow given the usual 2 seconds per iteration on this gpu.

**Comment by m4gr4th34** [comment]
It shouldn't be.  Passthrough of single GPU on VM seems to have been no-go till very recently, but seems like it's doable: https://www.youtube.com/watch?v=3BxAaaRDEEw
Caveat is to avoid conflict between host and VM using gpu at the same time; but given that WSL2 is such a tightly controlled env, and NVIDIA installs the driver on windows only, with only the CUDA toolkit installed in linux, I imagine it should be theoretically possible to get 100% of gpu compute on WSL2.  But, looking at redis, MS does have a track record of not following through on supporting linux projects, so I would not hold my breath on this.

**Comment by nicksahler** [comment]
Yeah I all but gave up on GPU on WSL until they just cold announced it. I think cuda internal performance hinges more on NVidia now though; Regarding memory: what i ended up doing was using my intel graphics card plugged into my monitor to prevent windows from using any GPU memory, and then having Tensorflow and torch train on the main GPU as usual. The biggest offenders, though, are apps like Firefox which took up for GB(!) of VRAM when allowed.

**Comment by m4gr4th34** [comment]
I am reading how-to dual boot into Debian 10, I just want to get on with the coding and serving.  Hoping I wont miss windows too much.  I just need multi-gpu support easily setup for serving, without the 'freeze_support' headache and lack of native redis for streamers.  After many all-nighters, and with ridiculously puffy eyes, I just want things to work.  I'm looking forward to trying linux, it seems ready for prime time on home desktops (last time i tried it was ~2005), so, let's see.

**Comment by nectario** [comment]
I am also seeing a significant reduction in speed on WSL2 with CUDA/CUDNN. 6 seconds per epoch vs 2 seconds on Windows.

**Comment by elchorro** [comment]
Can confirm. CUDA on WSL is painfully slow with Jax and Pytorch.
