### ISSUE TITLE
Broken link in www.tensorflow.org/resources/learn-ml

### ISSUE THREAD

**Issue by dsrbecky** [tensorflow/tensorflow#41100]
https://www.tensorflow.org/resources/learn-ml
-> The four areas of machine learning education
-> Build your own projects
-> [colab]
-> https://colab.research.google.com/github/tensorflow/docs/blob/r2.0rc/site/en/r2/tutorials/keras/basic_classification.ipynb

Gives me "Notebook not found"
Fetch for https://api.github.com/repos/tensorflow/docs/contents/site/en/r2/tutorials/keras?per_page=100&ref=r2.0rc failed: {
  "message": "No commit found for the ref r2.0rc",
  "documentation_url": "https://developer.github.com/v3/repos/contents/"
}

**Comment by MarkDaoust** [comment]
Thanks for reporting, we've moved this to the internal bug tracker. I'm closing this since there's no loop back.
