### ISSUE TITLE
UnimplementedError: Fused conv implementation does not support grouped convolutions for now.

### ISSUE THREAD

**Issue by kelingkece** [tensorflow/tensorflow#41107]
I follow the TensorFlow tutorial [(https://www.tensorflow.org/tutorials/images/classification)] for image classification when I try to compile the model, it gave me an error like this

> Epoch 1/100
> ---------------------------------------------------------------------------
> UnimplementedError                        Traceback (most recent call last)
> <ipython-input-117-7335ac61164f> in <module>()
>       4     epochs=epochs,
>       5     validation_data=validation_data_gen,
> ----> 6     validation_steps=total_val // batch_size,
>       7 )
> 
> 8 frames
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
>      58     ctx.ensure_initialized()
>      59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
> ---> 60                                         inputs, attrs, num_outputs)
>      61   except core._NotOkStatusException as e:
>      62     if name is not None:
> 
> UnimplementedError:  Fused conv implementation does not support grouped convolutions for now.
> 	 [[node sequential_5/conv2d_33/Relu (defined at <ipython-input-115-4d151b570f4c>:6) ]] [Op:__inference_train_function_6419]
> 
> Function call stack:
> train_function

I use my own data and follow the same code as the post, but still got an error like that.

**Comment by ravikyram** [comment]
@kelingkece 

Request you to share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by kelingkece** [comment]
@ravikyram its solved

**Comment by Karamya** [comment]
@kelingkece can you share how you solved the problem. I have the same issue

**Comment by Karamya** [comment]
Thanks, I found the solution. The problem was due to the difference in the number of channels in the image and the model

**Comment by kelingkece** [comment]
@Karamya glad that u found the solutions, I did the same thing as u did

**Comment by abhishekkuber** [comment]
@bhack they haven't mentioned the steps they took or the code that they changed

**Comment by NevilShingala** [comment]
> @ravikyram its solved

can you share how you solved the problem. I have the same issue

**Comment by vanshgautam** [comment]
can you please show the steps to solve this problem as i m also having this problem
