### ISSUE TITLE
Socket closed when "LayerNormalization" was used for tensors of 3 or more dimensions with TPU in colab.

### ISSUE THREAD

**Issue by gdhy9064** [tensorflow/tensorflow#41106]
When I used `LayerNormalization` on tensors of 3 or more dimensions in the colab with TPU, I encountered the following error:
> UnavailableError: Socket closed
> Additional GRPC error information:
> {"created":"@1593962551.753581454","description":"Error received from peer ipv4:10.10.67.202:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}
  
Please find the gist [here](https://colab.research.google.com/gist/gdhy9064/19ac8fafc46bdaa647a8b71bc31c3d2b/-pianist-ipynb.ipynb), thanks.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.2. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/df608a021b57ed4f897a5aeb7fb0cc64/41106.ipynb). Thanks!

**Comment by nicosacco** [comment]
Any news here? I am getting the same error with TF2.3rc2.

**Comment by yunxing** [comment]
Sorry for the delay. Just saw this issue, will fix soon.

**Comment by JerryLiuMY** [comment]
Same issue here https://github.com/tensorflow/tensorflow/issues/42228, will we get notified when it gets fixed and will it get fixed on the nightly version before the 2.4.0 release?

**Comment by sayakpaul** [comment]
Issue still persists in TensorFlow 2.4.1

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue with TF v2.5,please find the gist [here ](https://colab.research.google.com/gist/sushreebarsa/b1840e425c670d6bf83cff4ba43a72b3/untitled284.ipynb)..Thanks!

**Comment by gdhy9064** [comment]
@sushreebarsa Yes, it have been fixed in TF v2.5, thanks for your kind reminder.
