### ISSUE TITLE
Artistic Style Transfer Android Demo missing "Style blending" code

### ISSUE THREAD

**Issue by InternetMaster1** [tensorflow/tensorflow#41110]
Hi,

I have two questions regarding "Artistic Style Transfer with TensorFlow Lite"
https://www.tensorflow.org/lite/models/style_transfer/overview

**1) Style Blending Missing in Android**

In [Artistic Style Transfer with TensorFlow Lite](https://www.tensorflow.org/lite/models/style_transfer/overview) blog, there is complete section for "[Style blending](https://www.tensorflow.org/lite/models/style_transfer/overview#style_blending)" which says
> We can blend the style of content image into the stylized output, which in turn making the output look more like the content image. 
```
# Define content blending ratio between [0..1].
# 0.0: 0% style extracts from content image.
# 1.0: 100% style extracted from content image.
```

But in the [Android Demo](https://github.com/tensorflow/examples/tree/master/lite/examples/style_transfer/android) for the same, there is no option or code for "Style Blending".

Could you provide some code or guide me on how to achieve this in Android?

**2) Face Blending**

If I am doing artistic style transfer on any portrait images, the face looks too wrinkled. Is there any technique to make the face look better? Something like,
https://github.com/zfergus/face-preserving-style-transfer

**Comment by jdduke** [comment]
@Khanh is this expected?

**Comment by khanhlvg** [comment]
> 1) Style Blending Missing in Android

You can follow the logic described in the [notebook](https://www.tensorflow.org/lite/models/style_transfer/overview#style_blending): 
1. run style_predict with your content image
1. mix the style bottleneck of your content image and style image
`blended_bottleneck = alpha * content_bottleneck + (1-alpha) * style_bottleneck`
1. run style_transform with content_image and blended_bottleneck.

You can also refer to a community implementation here:
https://github.com/farmaker47/video_style_transfer

> 2) Face Blending
You can try with a different style transfer model which is larger but produce higher quality images/
https://tfhub.dev/sayakpaul/lite-model/arbitrary-image-stylization-inceptionv3/dr/predict/1

**Comment by khanhlvg** [comment]
@InternetMaster1 Did I answer your question in [this comment](https://github.com/tensorflow/tensorflow/issues/41110#issuecomment-660772317)?

**Comment by InternetMaster1** [comment]
Dear @khanhlvg ,

Many thanks for your reply. 

The logic for blending was clear, but I wasn't aware how to implement the same in Java for Android

I will try our the code provided in your linked repo regarding blending

https://github.com/farmaker47/video_style_transfer/blob/28e38183a1186036b7ae76640d59b6ac5aac109a/styleTransferModule/src/main/java/com/george/lite/examples/video_style_transfer/lib/StyleTransferModelExecutor.kt#L159

Many thanks!
