### ISSUE TITLE
Unable to convert ALBERT lite

### ISSUE THREAD

**Issue by wing-yiu** [tensorflow/tensorflow#41119]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Catalina 10.15.3 (19D76), also tried using colab runtime
- TensorFlow installed from source
- TensorFlow version: have tried multiple - 2.3.0-dev20200608, 2.4.0-dev20200705, 2.2.0, 1.15.0

Please refer to the [colab notebook](https://colab.research.google.com/drive/16eEDreq7F2DZLSFrQJJrrwPQ2MubKrh3#scrollTo=WOZp9iGvp9yb), I am able to convert [bert_en_uncased](https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/1) but not [albert_lite](https://tfhub.dev/tensorflow/albert_lite_base/1) even though albert lite is meant to be tflite compatible. 

I have tried different versions of tensorflow, as well as different ways of converting - from keras model / saved model / concrete function but none works :(

related issue: https://github.com/tensorflow/tensorflow/issues/34396

**Comment by abattery** [comment]
Hey wing-yiu@  I have a fix for this. Please wait for landing.

**Comment by karimnosseir** [comment]
This should be fixed. @wing-yiu can you please retry.

Thanks

**Comment by karimnosseir** [comment]
Please reopen if needed

**Comment by wing-yiu** [comment]
@karimnosseir 

Is there a specific version of tensorflow that I'm supposed to use?

I get the same error below when I use the colab notebook that was provided to convert from keras model.
`InvalidArgumentError: Input 3 of node functional_3/albert_lite/StatefulPartitionedCall was passed float from functional_3/albert_lite/73237:0 incompatible with expected resource.`

**Comment by abattery** [comment]
Please save the keras model into a saved model and use the from_saved_model API with tf-nightly version.

**Comment by wing-yiu** [comment]
Thank you, using `from_saved_model` works! Just a couple of questions:
- The original [Albert Lite model](https://tfhub.dev/tensorflow/albert_lite_base/1) was 42.5mb, and after conversion it only reduced to 33.6mb. Is this expected behaviour? When I previously converted the [large BERT model](https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/1) it was able to reduce size by 4x from 400+mb to 100+mb.

- Can you please briefly explain the changes that were made for this to work? Would like to learn from this in case I encounter similar issues in the future.

**Comment by abattery** [comment]
The graph node pruning result can be vary depending on the part to be pruned in the model. During conversion, pruning will be conducted based on the control dependencies described in the graph and I guess the large BERT model could be pruned since they have a lot of heavy dangling nodes in the graph.

V2 saved_model converter path is updated with the recent changes and capable to convert more TF models.
