### ISSUE TITLE
Doc of rmsprop optimizer seems not consistent with the code

### ISSUE THREAD

**Issue by tzm1003306213** [tensorflow/tensorflow#41115]
https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/RMSprop

**Comment by amahendrakar** [comment]
@tzm1003306213,
Could you please point out the inconsistencies in the document and mention the required changes to be made? Thanks!

**Comment by tzm1003306213** [comment]
> @tzm1003306213,
> Could you please point out the inconsistencies in the document and mention the required changes to be made? Thanks!

1) The momentum state update rule in document is "mom_t = momentum * mom_t-1 + g_t / sqrt(rms_t + epsilon)", while in the code is "mom_t = momentum * mom_t-1 + g_t / (sqrt(rms_t) + epsilon)".

2) I noticed a previous version of RMSprop optimizer https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/training_ops.cc#L564. The momentum state update rule is "mom_t = momentum * mom_t-1 + (learning_rate * g_t) / sqrt(rms_t + epsilon)", and the parameter update rule is "theta_t = theta_t-1 - mom_t". Why you use a different update rule in the current version?

3) The centered momentum state update rule in document is "mom_t = momentum * mom_t-1 + learning_rate * g_t / sqrt(rms_t - mg_t^2 + \epsilon)". It seems that in the code is "mom_t = momentum * mom_t-1 + g_t / (sqrt(rms_t - mg_t^2) + epsilon)". Similar difference in the parameter update.

4)  "x/x^2 = sign(x)", is this a typo? I think it should be "x/sqrt(x^2) = sign(x)"

Thanks

**Comment by MarkDaoust** [comment]
@tanzhenyu has done a lot of work on these optimizers. 

I assume the reason the epsilon was moved is just to make it simpler to think about the effect of the epsilon, `eps=1e-6` under the square root acts like `eps=1e-3` outside of the root.

**Comment by ymodak** [comment]
The optimizer docs are cleaned and updated. See commit [f6302e4](https://github.com/tensorflow/tensorflow/commit/f6302e4ec726225036b3419af7d218e93aa06783#diff-5b552f23144694a0bad1666a8ce66710f6f1b4a0587c9bfecc45d6df1ecdbd38)
Feel free to reopen if have any questions. Thanks!
