### ISSUE TITLE
Huge memory usage on hosts with 1TB RAM

### ISSUE THREAD

**Issue by a-a-davydov** [tensorflow/tensorflow#41122]
**System information**

We use keras and TF for our models:

Centos7

Python 3.6.1

Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0

tensorboard==1.12.2
tensorflow==1.12.0
tensorflow-estimator==1.13.0

Threre is no GPU on our servers.

**Describe the current behavior**

Our script loads trained model from files (json + h5) and predict some useful parameter.
When we run script on small server with 8GB RAM and measure memory after script load model we see it take 160Mb commited memory 1,5GB  virtual size.

When we run script on large production server with 1TB RAM and measure memory after script load exactly same model we see it take 220Mb commited memory 14GB  virtual size.

**Describe the expected behavior**

There are some limitation from our DEVOPS team and our models must take not more 1GB commited and not more 2GB virtual size. So we would like to have same memory fingerprint on any server. If there is any way setup TF to use fixed memory size on any server?

**Comment by amahendrakar** [comment]
> When we run script on large production server with 1TB RAM and measure memory after script load exactly same model we see it take 220Mb commited memory 14GB virtual size.

@a-a-davydov,
Could you please check if you are facing the same issue with TF v2.2 or TF v1.15? Thanks!

**Comment by a-a-davydov** [comment]
Hello,

I'm sorry, I can't setup new software on large server. It is require to get some agreements and plan admin team hours. It cat take some weeks, I will inform you if we do it and test fresh TF behaviour on large server.

Now we add following workaround in our code:

```
def init_keras_tf():
        from keras.backend.tensorflow_backend import set_session
        import tensorflow as tf
        config = tf.ConfigProto()  # create TF configuration
        config.gpu_options.allow_growth = True  # Disable memory pre allocation
        sess = tf.Session(config=config)
        set_session(sess)  # set this TensorFlow session as the default session for Keras
```

As we see, gpu_options.allow_growth works well and for CPU RAM and we get same memory fingerprint on any server

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
