### ISSUE TITLE
tf.io.decode_image rotates the images

### ISSUE THREAD

**Issue by samquar** [tensorflow/tensorflow#41126]
When I read some image files tf.io.decode_image rotates the images by n*90 degrees in comparison with how the images are shown in image viewers programs such as IrfanView and OpenCV's imread. I'm attaching one of the images: https://imgur.com/vPMQPq7
You can check it using my code:

```
import os
import tensorflow as tf

path = r'path_to_folder'

filenames = os.listdir(path)
new_path = path + '_after_tf'
if not os.path.isdir(new_path):
    os.mkdir(new_path)

for filename in filenames:
    img_bytes = open(os.path.join(path, filename), 'rb').read()
    img = tf.io.decode_image(img_bytes)
    new_img_bytes = tf.io.encode_jpeg(img)
    tf.io.write_file(os.path.join(new_path, os.path.splitext(filename)[0] + '.jpg'), new_img_bytes)
```
It inputs image files in folder "path" and outputs images after tf.io.decode_image, tf.io.encode_jpeg, tf.io.write_file in the folder with the same name + the suffix "_after_tf"

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip install
- TensorFlow version (use command below): 2.2
- Python version: 3.7

**Comment by hyeygit** [comment]
@samquar - I haven't been able to reproduce the issue (here is a [colab](https://colab.research.google.com/drive/1aK_MaGreXl4jbGNT4rq5N8wFYJT2NYcB?usp=sharing)). I'm wondering if I'm missing something that's different from your setup. Would you be able to provide a gist that shows and reproduces the exact issue you're seeing, please?

**Comment by rmothukuru** [comment]
@samquar,
Can you please respond to the above comment? Thanks!
