### ISSUE TITLE
Slow TFLite GPU inference on Android, not matched with the benchmark

### ISSUE THREAD

**Issue by andreydung** [tensorflow/tensorflow#41128]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Pixel 2
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): nightly build
- Python version:
- Bazel version (if compiling from source): 3.3.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

We're running GPU delegate on an Android phone (NDKr18b). However, it's very slow (15ms) compared with the latency running benchmark tool (6ms).

This is the performance reported by benchmark tool (6ms):
![Screenshot from 2020-07-06 23-42-06](https://user-images.githubusercontent.com/1322198/86620587-c105fd80-bfe6-11ea-8c16-79c3b42a74f2.png)

While this is the actual latency when running within our app (15ms)
![Screenshot from 2020-07-06 23-43-36](https://user-images.githubusercontent.com/1322198/86620591-c2cfc100-bfe6-11ea-9f28-7566a57e983e.png)

We're using `libtensorflowlite_gpu_gl.so` generated by running the following:

```
bazel build -c opt --config android_arm64 tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_gl.so  # for dynamic library
```

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by multiverse-tf** [comment]
Sorry for the very late response. Is this the same issue that you reported here: https://github.com/tensorflow/tensorflow/issues/41094? And does [the reply](https://github.com/tensorflow/tensorflow/issues/41094#issuecomment-655337940) by @hajuho help?
