### ISSUE TITLE
Possible bug(?): tensorflow.python.eager.core._SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor X>]

### ISSUE THREAD

**Issue by hoangcuong2011** [tensorflow/tensorflow#41135]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS High Sierra
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): >= 2.0
- Python version: 3.6
- Running on: CPUs (But I guess it happens on GPUs as well)

The following issue is very similar to this [one](https://github.com/tensorflow/tensorflow/issues/41111) I posted before. The difference here is that I use eager execution in the code and it produces an error of Keras symbolic tensors. To be fair I am not sure this is a bug or the error is on purpose. Here is the code to produce the error:

```
import tensorflow as tf
from tensorflow.keras import backend as K
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

class MyWordEmbedding(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(MyWordEmbedding, self).__init__(**kwargs)

    def build(self, input_shape):
        self.kernel = self.add_weight(shape=(300, 512), dtype='float32')
        super(MyWordEmbedding, self).build(input_shape)  # Be sure to call this at the end
    
    def call(self, inputs):
        return tf.nn.embedding_lookup(params=self.kernel, ids=inputs[0])

class EncoderLayer(tf.keras.layers.Layer):
    def __init__(self, mask_para, **kwargs):
        self.mask_para = mask_para
        super(EncoderLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        self.Qdense = self.add_weight(name='Qdense', shape=(512, 512))
        super(EncoderLayer, self).build(input_shape)

    def call(self, x):
        Qoutput = tf.einsum('aij,jk->aik', x[0], self.Qdense)
        Koutput =  tf.einsum('aij,jk->aik', x[0], self.Qdense)
        Voutput =  tf.einsum('aij,jk->aik', x[0], self.Qdense)
        a = tf.einsum('ajk,afk->ajf', Qoutput, Koutput) * tf.tile(K.expand_dims(self.mask_para, axis=1), [1, 64, 1])
        a = tf.matmul(a, Voutput)
        print(a)
        return a

    def compute_mask(self, inputs, mask):
        return mask

    def compute_output_shape(self, input_shape):
        return input_shape[0]

def create_encoder_model():
    word_ids_fr = tf.keras.layers.Input(dtype='int32', shape=(None,))
    a = MyWordEmbedding()([word_ids_fr])
    a = EncoderLayer(K.cast(K.not_equal(0, word_ids_fr), dtype='float32'))([a])
    model = tf.keras.models.Model(inputs=[word_ids_fr], outputs=a)
    return model

def create_model():
    word_ids_en = tf.keras.layers.Input(dtype='int32', shape=(None,))
    a = tf.keras.layers.Input(shape=(None, 512,))
    b = MyWordEmbedding()([word_ids_en])
    b = b + a
    model = tf.keras.models.Model(inputs=[word_ids_en, a], outputs=b)
    return model
    
def evaluate():
    source_sequence_ids = pad_sequences(np.random.randint(5, size=(3, 64)), maxlen=64, padding='pre')
    output = decoder_model.predict([pad_sequences(np.random.randint(5, size=(3, 64)), maxlen=64, padding='post'), encoder_model(source_sequence_ids, training=False)], steps=1, verbose=1, batch_size=256)

decoder_model = create_model()
encoder_model = create_encoder_model()
evaluate()
```

Error:

`tensorflow.python.eager.core._SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'MatMul:0' shape=(3, 64, 512) dtype=float32>]`

Meanwhile, I also provide a way to fix this as follows (just a simple modification):

```
import tensorflow as tf
from tensorflow.keras import backend as K
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

class MyWordEmbedding(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(MyWordEmbedding, self).__init__(**kwargs)

    def build(self, input_shape):
        self.kernel = self.add_weight(shape=(300, 512), dtype='float32')
        super(MyWordEmbedding, self).build(input_shape)  # Be sure to call this at the end
    
    def call(self, inputs):
        return tf.nn.embedding_lookup(params=self.kernel, ids=inputs[0])

class EncoderLayer(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(EncoderLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        self.Qdense = self.add_weight(name='Qdense', shape=(512, 512))
        super(EncoderLayer, self).build(input_shape)

    def call(self, x):
        mask_para = x[1]
        Qoutput = tf.einsum('aij,jk->aik', x[0], self.Qdense)
        Koutput =  tf.einsum('aij,jk->aik', x[0], self.Qdense)
        Voutput =  tf.einsum('aij,jk->aik', x[0], self.Qdense)
        a = tf.einsum('ajk,afk->ajf', Qoutput, Koutput) * tf.tile(K.expand_dims(mask_para, axis=1), [1, 64, 1])
        a = tf.matmul(a, Voutput)
        print(a)
        return a

    def compute_mask(self, inputs, mask):
        return mask

    def compute_output_shape(self, input_shape):
        return input_shape[0]

def create_encoder_model():
    word_ids_fr = tf.keras.layers.Input(dtype='int32', shape=(None,))
    a = MyWordEmbedding()([word_ids_fr])
    a = EncoderLayer()([a, K.cast(K.not_equal(0, word_ids_fr), dtype='float32')])
    model = tf.keras.models.Model(inputs=[word_ids_fr], outputs=a)
    return model

def create_model():
    word_ids_en = tf.keras.layers.Input(dtype='int32', shape=(None,))
    a = tf.keras.layers.Input(shape=(None, 512,))
    b = MyWordEmbedding()([word_ids_en])
    b = b + a
    model = tf.keras.models.Model(inputs=[word_ids_en, a], outputs=b)
    return model
    
def evaluate():
    source_sequence_ids = pad_sequences(np.random.randint(5, size=(3, 64)), maxlen=64, padding='pre')
    output = decoder_model.predict([pad_sequences(np.random.randint(5, size=(3, 64)), maxlen=64, padding='post'), encoder_model(source_sequence_ids, training=False)], steps=1, verbose=1, batch_size=256)

decoder_model = create_model()
encoder_model = create_encoder_model()
evaluate()
```

**Comment by ravikyram** [comment]
@hoangcuong2011 

I have tried in colab with TF version 2.2, nightly versions and i am seeing the error message`(AttributeError: 'Tensor' object has no attribute '_datatype_enum'`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/7e2356466b56bc3dcb896afcab13cb76/untitled90.ipynb).Thanks!

**Comment by AgoloCuongHoang** [comment]
@ravikyram: Interesting. If you run it with TF 2.0, you got a different error - the one that I reported (see the gist [here](https://colab.research.google.com/drive/1LfiWeoYiWtGK8pjuG9xHOKfxdVDInPqp?usp=sharing))
in any case this is very likely a bug. Any thoughts on this?

**Comment by hoangcuong2011** [comment]
@ravikyram: Interesting. If you run it with TF 2.0, you got a different error - the one that I reported (see the gist here)
in any case this is very likely a bug. Any thoughts on this?

**Comment by AlucardNosferatu** [comment]
I have a same problem, but runs well without BiLSTM:
[https://github.com/AlucardNosferatu/LostXmas/issues/2#issue-658065152](url)

**Comment by AlucardNosferatu** [comment]
> I have a same problem, but runs well without BiLSTM:
> [https://github.com/AlucardNosferatu/LostXmas/issues/2#issue-658065152](url)

Solved.

**Comment by AlucardNosferatu** [comment]
> I have a same problem, but runs well without BiLSTM:
> [AlucardNosferatu/LostXmas#2 (comment)](https://github.com/AlucardNosferatu/LostXmas/issues/2#issue-658065152)

Solved

**Comment by tanzhenyu** [comment]
Re-assigning to someone who's more familiar with Keras tensors.

**Comment by tomerk** [comment]
Hi @hoangcuong2011 
This unfortunately isn't the most helpful of error messages (we can look into trying to provide a more meaningful error message for this in the future once an upcoming refactoring of the internals lands), but it is behaving as expected.

Keras symbolic tensors cannot be passed to a layer's constructor, it is only valid to pass them into a layer's __call__. Your first example passes the symbolic tensors to the constructor and tries to use them, raising the error message. Your second example makes sure to pass all symbolic tensors as arguments to the layer calls, so it works.

**Comment by hoangcuong2011** [comment]
@tomerk Thanks. I did not know that we should not pass Keras symbolic tensors to a layer's constructor? May I know why it is designed that way? (Why we should the tensor to a layer's call instead of constructor?)

**Comment by tomerk** [comment]
Hi @hoangcuong2011 , it's this way because models contain layer objects that they reuse, rather than re-creating the layers each time you call the model. These layers may get called in different settings (individually, as part of the larger model, in a tf.function, totally eagerly, etc.

We can handle Functional model definition via layer calls because we define `__call__` in Keras and have users just override `call`. So, we can track a variety of metadata under the hood. We use this metadata whenever you call the constructed model to get the model working in the above settings. (e.g. we keep track of what partially-created values need to be forwarded to what)

But, arbitrary layer constructors for custom layers don't give us the same ability to track model structure metadata. Arguably there's maybe stuff we could do with python's `__new__` in certain circumstances, but it would be very unreliable and would make for a poor user experience. So, it's the most straightforward to disallow it altogether.

It's generally fairly easy to make sure a layer takes all tensor inputs directly in `call` as opposed to in the constructor.

**Comment by hoangcuong2011** [comment]
@tomerk  Your answer is thoughtful and helpful to me. Thank you!
