### ISSUE TITLE
[TF/MLIR] Graph pruning / canonicalization pass doesn't eliminate some dead constant nodes

### ISSUE THREAD

**Issue by bondhugula** [tensorflow/tensorflow#41133]
This is with the tensorflow trunk at e13ff2da43ab00dba94dd00d87a876b2a03f48e7 (Jul 6). 

This is a reduced test case where both nodes/operations in the graph are supposed to be dead (results unused and not side-effecting), but neither the `-tf-executor-graph-pruning` nor the `-canonicalize` pass gets rid of them. However, if one of them is removed, `-canonicalize` is able to eliminate the other. Similar patterns are often DCE'd by `-tf-executor-graph-pruning` in the presence of other larger islands. 

```
module {
  func @main() attributes {tf.entry_function = {control_outputs = "", inputs = "", outputs = ""}} {
    tf_executor.graph {
      %outputs, %control = tf_executor.island wraps "tf.Const"() {value = dense<1> : tensor<1xi32>} : () -> tensor<1xi32>
      %outputs_0, %control_1 = tf_executor.island wraps "tf.Const"() {value = dense<100> : tensor<1xi32>} : () -> tensor<1xi32>
      tf_executor.fetch
    }
    return
  }
}
```
To reproduce, run:
```
$ tf-opt -tf-executor-graph-pruning -canonicalize test_case.mlir
```

OS: CentOS 8 x86-64.
TF built from sources with GCC 8.3.1 and with --linkopt='-fuse-ld=lld'.

**Comment by joker-eph** [comment]
Because if you import a graphdef without any fetch the pruning would just eliminate the entire graph, we rather not do anything: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/tensorflow/transforms/graph_pruning.cc#L90-L94

**Comment by bondhugula** [comment]
On a narrow note, why would it be incorrect to eliminate everything here? Not having a fetch is still defined behavior, right? (I'm thinking about the multiple functions case - one of them could just be empty and completely removed. )

**Comment by joker-eph** [comment]
It'd may be correct for a tf function that does not return anything, but at the same time we're trying to move away from the executor dialect for TF2 and functions.

**Comment by bondhugula** [comment]
> It'd may be correct for a tf function that does not return anything, but at the same time we're trying to move away from the executor dialect for TF2 and functions.

I see. What would the new entry point then be when converting/importing from TF Graphdef?

**Comment by joker-eph** [comment]
Mainly SavedModel I think for loading from file. 
When running online we're working on having the tracing `tf.function` directly build MLIR in the first place without going through the Graph data structure.

**Comment by bondhugula** [comment]
Please do keep the translation to tf.executor (`convert_graph_def` python binding) until the in-memory replacement (tracing `tf.function`) is available. Thanks!

**Comment by joker-eph** [comment]
SavedModel are style storing GraphDef (and will continue for a while): so the conversion to tf.executor will stay there for a while!
