### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none) ERROR: No matching distribution found for tensorflow

### ISSUE THREAD

**Issue by nesrinebnh** [tensorflow/tensorflow#41130]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Windows 10 64bits
- pip install tensorflow
- Tensorflow 2.2
- python 3.8.3
- installation with pip
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0 / 11.0
- NVIDIA GEFORCE 920M

i installed all the required packages and checked if my hardward is equiped with what i need, i have VT-X and GPU but can't install i have this kind of error:

ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow

can anyone explain me why? and how to fix it?
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Comment by Saduf2019** [comment]
@nesrinebnh 
Could you please refer to [this link](https://github.com/tensorflow/tensorflow/issues/40822#issuecomment-650075807) and let us know if it helps.

**Comment by nesrinebnh** [comment]
oh yeah true, i was running different versions of python, i missed this point. 
thank you

**Comment by nesrinebnh** [comment]
hello,
thank you for your reply, i would say your fast reply, yes it was my issue,
thank you so much
I'm so satisfied
