### ISSUE TITLE
bug in create an op of tensorflow 1.15 

### ISSUE THREAD

**Issue by szliu90** [tensorflow/tensorflow#41149]
- tensorflow
  - tensorflow core
    - create an op
       - GPU kernels
There is an example of GPU kernel implementation.
There are three files:
kernel_example.h  kernel_example.cc  kernel_example.cu.cc
When I compile the kernel_example.cu.cc with the commond:
```
nvcc -std=c++11 -c -o kernel_example.cu.o kernel_example.cu.cc \
  ${TF_CFLAGS[@]} -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC
```
there are some errors:
```
kernel_example.h: error: a class or namespace qualified name is required
kernel_example.h: warning: nonstandard qualified name in global scope declaration
kernel_example.h: error: class template "ExampleFunctor " has already been defined
```
How to deal with that?

**Comment by Saduf2019** [comment]
@szliu90 
Is there any particular reason for using older version of tf when their are newer versions available.

**Comment by szliu90** [comment]
> @szliu90
> Is there any particular reason for using older version of tf when their are newer versions available.

Many people use the GPUs together. The CUDA version can't be changed to fit my own demand.

**Comment by sanjoy** [comment]
Hi @szliu90 ,

This looks like a general CUDA/C++ programming question.  Have you tried asking on StackOverflow?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
