### ISSUE TITLE
Tensorflow GPU needs to wait a few minutes each time before computing

### ISSUE THREAD

**Issue by huoxingwen** [tensorflow/tensorflow#41148]
**Tensorflow GPU needs to wait a few minutes each time before computing,GPU runs slower than CPU because of waiting**

**System information**
- OS Platform: ubuntu18.04
- TensorFlow:  2.2
- Python version:3.7
- CUDA/cuDNN version: cuda10.2/cudnn7.6.5
- GPU model and memory: GTX 950m, memory is 2048MB

The code  is official's helloworld demo .
[https://www.tensorflow.org/tutorials/quickstart/beginner](url)

Here is the information of output.
 `2020-07-07 13:59:25.106703: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 950M, Compute Capability 5.0``

I've tried the official apt installation, but it's still the same. Does anyone have the same problem? How did you solve it.

**Comment by ravikyram** [comment]
@huoxingwen 

Request you to share colab link or simple standalone code with proper indentation to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by huoxingwen** [comment]
> @huoxingwen
> 
> Request you to share colab link or simple standalone code with proper indentation to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

The code is official's helloworld demo .
[https://www.tensorflow.org/tutorials/quickstart/beginner](url)

**Comment by ravikyram** [comment]
@huoxingwen 

I have tried in colab with TF version 2.2 and i am seeing the same time for both [cpu](https://colab.research.google.com/gist/ravikyram/773c240585600c5242703be55ef9b50d/untitled99.ipynb) and [gpu](https://colab.research.google.com/gist/ravikyram/a57a6e33bc02650a521a6a5188740d98/untitled99.ipynb).I noticed it takes few more minutes in installing Tensorflow with GPU.Apart from that almost performance is same.Thanks!

**Comment by huoxingwen** [comment]
> @huoxingwen
> 
> I have tried in colab with TF version 2.2 and i am seeing the same time for both [cpu](https://colab.research.google.com/gist/ravikyram/773c240585600c5242703be55ef9b50d/untitled99.ipynb) and [gpu](https://colab.research.google.com/gist/ravikyram/a57a6e33bc02650a521a6a5188740d98/untitled99.ipynb).I noticed it takes few more minutes in installing Tensorflow with GPU.Apart from that almost performance is same.Thanks!


Thank  for your replying, I  tested it in window10 and google colab, there is no problem and run code instantly. However it still have to wait  a few mins to start computing in ubuntu16 & ubuntu18 & ubuntu20. it shows that the memory of graphics card is high, but the gpu performance is low.

**Comment by ymodak** [comment]
@huoxingwen I see that you are using cuda 10.2 along with TF 2.2 version.
The TF 2.2 pre built packages support cuda 10.1 
So you may want to switch to cuda 10.1 , set appropriate cuda env paths and try again.
Right now what's happening is that your computation is falling back on cpu due incorrect [gpu setup](https://www.tensorflow.org/install/gpu#software_requirements).

**Comment by huoxingwen** [comment]
> @huoxingwen I see that you are using cuda 10.2 along with TF 2.2 version.
> The TF 2.2 pre built packages support cuda 10.1
> So you may want to switch to cuda 10.1 , set appropriate cuda env paths and try again.
> Right now what's happening is that your computation is falling back on cpu due incorrect [gpu setup](https://www.tensorflow.org/install/gpu#software_requirements).

Thank you for your idea. I used to think this way and I've changed the version of cuda to 10.1, but it's the same. And my system information is after the change.

OS Platform: ubuntu18.04
TensorFlow: 2.2
Python version:3.7
CUDA/cuDNN version: cuda10.1/cudnn7.6.5
GPU model and memory: GTX 950m, memory is 2048MB

**Comment by ymodak** [comment]
As a sanity check  can you please test if gpu is detected by your machine
```python
[tf.config.list_physical_devices('GPU')](https://www.tensorflow.org/api_docs/python/tf/config/list_physical_devices)
```

**Comment by huoxingwen** [comment]
> As a sanity check can you please test if gpu is detected by your machine
> 
> ```python
> tf.config.list_physical_devices('GPU')
> ```
> 
> (https://www.tensorflow.org/api_docs/python/tf/config/list_physical_devices)

> I had tried this code 
> `tf.config.list_physical_devices('GPU')`
> and got the result

> > 2020-07-14 06:18:04.804962: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
> 2020-07-14 06:18:04.809154: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2020-07-14 06:18:04.809499: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
> pciBusID: 0000:01:00.0 name: GeForce GTX 950M computeCapability: 5.0
> coreClock: 1.124GHz coreCount: 5 deviceMemorySize: 1.96GiB deviceMemoryBandwidth: 26.82GiB/s
> 2020-07-14 06:18:04.809804: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
> 2020-07-14 06:18:04.811523: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
> 2020-07-14 06:18:04.813105: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
> 2020-07-14 06:18:04.813470: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
> 2020-07-14 06:18:04.816187: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
> 2020-07-14 06:18:04.817683: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
> 2020-07-14 06:18:04.821731: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
> 2020-07-14 06:18:04.821897: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2020-07-14 06:18:04.822220: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2020-07-14 06:18:04.822409: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
> [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

**Comment by sanjoy** [comment]
GTX 950m has compute capability 5.0 and TF nightly does not ship with SASS with this compute capability.  So it is JIT compiling PTX and that is likely the pause you see.

Are you able to build TF from source?  The best solution for is probably to build from source and include sm_50 in the build.

**Comment by rmothukuru** [comment]
@huoxingwen,
Can you please confirm if your issue is resolved? If not, can you please respond to the above comment? Thanks!
