### ISSUE TITLE
Creating an instance of ResNet50() uses high GPU Memory

### ISSUE THREAD

**Issue by kartik1395** [tensorflow/tensorflow#41147]
Creating a model using the below method results in 14GB of GPU usage

import tensorflow as tf
from tensorflow.keras.applications import MobileNet, MobileNetV2, resnet
base_model = resnet.ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

![image](https://user-images.githubusercontent.com/52433565/86726230-f5b49c00-c05c-11ea-8676-f7cf1b8a26fb.png)

Any reason for such high GPU usage ?

**Comment by amahendrakar** [comment]
@kartik1395,
Please take a look at [this guide](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) to limit GPU memory growth and let us know if it helps. Thanks!

**Comment by kartik1395** [comment]
@amahendrakar i followed the guide. Seems its not capturing all the memory at one go. Thanks!
