### ISSUE TITLE
Predict is slow on first call when using variable batch_size

### ISSUE THREAD

**Issue by bayandin** [tensorflow/tensorflow#41141]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary (via pip)
- TensorFlow version (use command below): v2.2.0-0-g2b96f3662b 2.2.0 (and tf-nightly: v1.12.1-35161-gd659eb9c0d 2.3.0-dev20200625)
- Python version: 3.6.9
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.1 
- GPU model and memory: Tesla P100 / 16GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
- When I use a variable batch_size (<=32) the first prediction for a new size is slow. The following predictions for the same shape are fast. The interesting thing is for batch sizes > 32 there is no slowdown:
![tf-nightly](https://user-images.githubusercontent.com/864213/86664759-ea268e00-bfe6-11ea-93fc-d646bce6fb64.png)

**Describe the expected behavior**
- I expect that calls will take the same time for execution

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1er9s3e4GgyMevU7MC6gOkpscsJ3j0Nr-?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

There is a similar issue with the variable input shape: https://github.com/tensorflow/tensorflow/issues/39458

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2,nightly version and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/5110443db05e1c5f7ce1fe588537e53a/untitled91.ipynb).Thanks!

**Comment by rmothukuru** [comment]
@bayandin,
Sorry for the delayed response. Could reproduce the issue with **`Tensorflow Version 2.5`** Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/2228c5e1ad558afa39adc77b5d59153d/untitled91.ipynb). 

Can you please let us know the use-case where **`variable`** **`batch_size`** will be applicable? Thanks!

**Comment by bayandin** [comment]
Hey @rmothukuru, thanks for the response! 

> Can you please let us know the use-case where **`variable`** **`batch_size`** will be applicable?

A service collects requests from multiple clients into a batch. Then it runs inference on this batch. Since the number of requests/clients is variable, we end up with different batch size. The idea behind collecting requests into a batch is a sequential inference of N requests take more time than running these N requests in a batch (for some N).

**Comment by foxik** [comment]
Just an observation, the `model.predict` does not process the whole input in a single batch, it instead splits it into batches itself. The default batch_size is 32, which explains the drop in 32. (For larger inputs, they get split into two batches, one of size 32 and the other 1-32, so these are already "used" batch sizes, so the second half of the first measurement is also "fast" because of reusing large batch sizes.)

If you want to process single batches, use `.predict_on_batch`, which does not split the data; for that method, the first batch is slow until the batch size 64.

**Comment by bayandin** [comment]
I believe this issue still reproducibly in version 2.5 as per @rmothukuru comment https://github.com/tensorflow/tensorflow/issues/41141#issuecomment-853778917

**Comment by kumariko** [comment]
I could reproduce the issue with TF 2.7 .Please, find the gist [here](https://colab.research.google.com/gist/kumariko/b43baff89735a177f7944c09974cbb36/untitled91.ipynb#scrollTo=fEf-HVQKpBQi).Thanks!

**Comment by gowthamkpr** [comment]
@bayandin As mentioned [here](https://github.com/tensorflow/tensorflow/issues/39458#issuecomment-669588856), this is expected. If you still think this is an issue, please open an issue in [keras-team/keras](https://github.com/keras-team/keras/issues/new/choose) as the development of keras has been moved to a different repo. Thanks!!
