### ISSUE TITLE
TimeDistributed does not infer output batch size when timesteps=None

### ISSUE THREAD

**Issue by jmontalt** [tensorflow/tensorflow#41157]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): N/A
- TensorFlow version (use command below): v2.2.0-0-g2b96f3662b 2.2.0
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I am trying to create a convolutional LSTM model which makes use of `ConvLSTM2D` as well as other layers such as `Conv2D` and `MaxPool2D`, wrapped in `TimeDistributed` layers. I'm using the Functional API.

This model should be stateful. Therefore, I pass the batch size to the `Input` layer, but I would like to keep the `timesteps` dimension flexible, so I set that to `None`.

The problem arises when using `TimeDistributed` layers, because their output batch size is always set to `None`, even if their input batch size is fixed (see following summary).

```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_18 (InputLayer)        [(4, None, 64, 64, 1)]    0         
_________________________________________________________________
time_distributed_27 (TimeDis (None, None, 64, 64, 1)   257       # no LSTMs after this point because batch_size=None
=================================================================
```

As a result, stateful LSTM layers cannot be used after `TimeDistributed`, as they will fail with "ValueError: If a RNN is stateful, it needs to know its batch size".

**Describe the expected behavior**

I certainly could be missing something, but I don't see any reason why the TimeDistributed layer shouldn't be able to infer its output batch size correctly (is it not always the same as the input batch size?). Even if that's not true, shouldn't it be possible to have a mechanism to help the layer figure it out?

**Standalone code to reproduce the issue**

Link to a simple example in Colab:
https://colab.research.google.com/drive/11efUrQpkahgk-jgb0-4Flwii7Fd1y5Ej?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@jmontalt 
Please refer to below issues with similar error and let us know if it helps.

#36363 #31028 [link](https://github.com/keras-team/keras/issues/7770) [link1](https://github.com/keras-team/keras/issues/7770#issuecomment-326762841)  [link2](https://github.com/tensorflow/tensorflow/issues/31028#issuecomment-520290743)

**Comment by jmontalt** [comment]
Hi, thank you very much for your reply. It looks like the problem is the same as that described in #36363 for the `Reshape` layer, and indeed the same solution (i.e. setting the static shape using `set_shape` at the end of the layer's `call` method) works for me. Should I raise a PR with the equivalent fix for `TimeDistributed`?

**Comment by Saduf2019** [comment]
@jmontalt
Please go ahead with the PR creation, proceeding to move this issue to closed status as its resolved.

**Comment by q-55555** [comment]
@jmontalt Did you edit the PR ? (I was not able to find it).
If not, can you publish here the resolution please ?

**Comment by jmontalt** [comment]
This slipped my mind, but I have created the PR now. In the meantime, you can fix the issue using `set_shape` on the output of your TimeDistributed layer.
```
layer = tf.keras.layers.TimeDistributed(tf.keras.layers.Conv2D(16, (3, 3)))
inputs = tf.keras.Input(batch_shape=(1, None, 32, 32, 1))
outputs = layer(inputs)
outputs.set_shape(layer.compute_output_shape(inputs.shape))
```

**Comment by q-55555** [comment]
Thanks a lot, I applied your PR locally and it is working well !
(BTW a review is required in order to merge, one test has failed)
