### ISSUE TITLE
InternalError: Tensorflow type 21 not convertible to numpy dtype.

### ISSUE THREAD

**Issue by lokesharma-dev** [tensorflow/tensorflow#41159]
`kl = tf.reduce_mean(compute_kld( p_logit , p_logit_r ))
grad_kl = tf.gradients( kl ,r_tensor)[0]
r_vadv = tf.stop_gradient(grad_kl)
r_vadv = make_unit_norm( r_vadv )/3.0
p_logit_no_gradient = tf.stop_gradient(p_logit)

vadv_tensor = tf.add(clean_emb, grad_kl)
print('Gradient: ',type(grad_kl), grad_kl.shape)
print('Adversarial embedding: ',type(vadv_tensor), vadv_tensor.shape)`

Gradient:  <class 'tensorflow.python.framework.ops.Tensor'> (None, 500, 50)
Adversarial embedding:  <class 'tensorflow.python.framework.ops.Tensor'> (None, 500, 50)

`hidden = LSTM(units=128)(vadv_tensor)
output = Dense(units=32, activation='relu')(vadv_tensor)
q_logit = Dense(units=1, activation='relu')(output)

print('Q_Logit: ',type(q_logit), q_logit.shape)`

# Error

> /usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1472: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  run_metadata_ptr)
InternalError                             Traceback (most recent call last)
<ipython-input-8-9bcdd73aa054> in <module>()
----> 1 hidden = LSTM(units=128)(vadv_tensor)
      2 output = Dense(units=32, activation='relu')(vadv_tensor)
      3 q_logit = Dense(units=1, activation='relu')(output)
      4 
      5 print('Q_Logit: ',type(q_logit), q_logit.shape)

10 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in __call__(self, *args, **kwargs)
   1470         ret = tf_session.TF_SessionRunCallable(self._session._session,
   1471                                                self._handle, args,
-> 1472                                                run_metadata_ptr)
   1473         if run_metadata:
   1474           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

InternalError: Tensorflow type 21 not convertible to numpy dtype.

---------------------------------------------------------------------------

I am using Tensorflow 1.x. Any suggestions on how I can solve this error. 
Thanks for your consideration.

The error can be replicated from this collab: https://colab.research.google.com/drive/1RlZTQaqM8Mb2MnyviUO0K88QXztFlY8Z?usp=sharing

The dataset used for the above code:
[npy.zip](https://github.com/tensorflow/tensorflow/files/4886083/npy.zip)

**Comment by amahendrakar** [comment]
@lokesharma-dev,
Please take a look [this comment](https://github.com/tensorflow/tensorflow/issues/34683#issuecomment-572791147) from a similar issues and let us know if it helps. Thanks!
