### ISSUE TITLE
Persistent GradientTape not working with LSTM

### ISSUE THREAD

**Issue by GPla** [tensorflow/tensorflow#41156]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes. Adapted code from [this tutorial](https://keras.io/guides/customizing_what_happens_in_fit/)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Build 1903
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.7.7

**Describe the current behavior**

Training a model with `tf.keras.layers.LSTM`  and  custom `train_step` that uses a `tf.GradientTape(persistent=True)` is 
stuck at the first batch. The python process slowly uses all available RAM.

**Describe the expected behavior**

The model should train the same way as when using `persistent=False`.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/16tBJzlHqPY5oL5im20noFSN8luVzPnjt?usp=sharing

**Comment by ravikyram** [comment]
I have tried in colab with TF versions 2.2,nightly versions(`2.4.0-dev20200707`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/6f20f5647385a1841529f98b9de85066/untitled93.ipynb).Thanks!

**Comment by nikitamaia** [comment]
Seems to happen with GRU as well but not SimpleRNN. Possibly related to issue [#39697](https://github.com/tensorflow/tensorflow/issues/39697) ?

**Comment by qlzh727** [comment]
@GPla, I think this is the same issue as  #39697 and tf core team is trying to address it. Please track the progress in  #39697 and I am closing this issue for now.
