### ISSUE TITLE
tensorflow/tensorflow:2.1.1-gpu has python3 instead of python2

### ISSUE THREAD

**Issue by jeroendecroos** [tensorflow/tensorflow#41153]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  N/A
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): N/A
- TensorFlow version (use command below): v2.1.0-33-g3ffdb91 2.1.1
- Python version: See details
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
Docker image tensorflow/tensorflow:2.1.1-gpu contains python3.6.9

**Describe the expected behavior**
Docker image tensorflow/tensorflow:2.1.1-gpu contains python2.7.17 as is expected for docker images <= 2.1 https://hub.docker.com/r/tensorflow/tensorflow/

**Standalone code to reproduce the issue**
$docker run tensorflow/tensorflow:2.1.1-gpu python --version
Python 3.6.9            

**Other info / logs** Include any logs or source code that would be helpful to
Note:  tensorflow/tensorflow:2.1.0-gpu contains python2 
$docker run tensorflow/tensorflow:2.1.0-gpu python --version
Python 2.7.17

**Comment by mihaimaruseac** [comment]
This is working as intended

> Versioned images <= 1.15.0 (1.x) and <= 2.1.0 (2.x) have Python 3 (3.5 for Ubuntu 16-based images; 3.6 for Ubuntu 18-based images) in images tagged "-py3" and Python 2.7 in images without "py" in the tag. All newer images are Python 3 only. Tags containing -py3 are deprecated.

Version 2.1.1 is not smaller than 2.1.0.

Any patch release after January 2020 will be only Python3, regardless if the original final release included python 2 support.
