### ISSUE TITLE
Add universal Tensor/EagerTensor to ndarray conversion function

### ISSUE THREAD

**Issue by EnderWiggin14** [tensorflow/tensorflow#41168]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): tf-nightly==2.3.0dev20200622
- Are you willing to contribute it (Yes/No): Not skilled enough or knowledgeable enough of TF architecture

**Describe the feature and the current behavior/state.**
Currently there are many different ways to convert individual types of Tensor-like objects into corresponding ndarrays; however, each of these has a specific use condition.
<EagerTensor>.numpy() : only works with eager execution
<Tensor> : must be evaluated inside a tf.function or a Graph. Might not work in all environments either ( I couldn't get this to work)
There is a function that converts ProtoTensors, but it doesn't work on Tensors or EagerTensors.

The goal is to have a function that can convert at least Tensors and EagerTensors to ndarrays regardless of whether Eager Execution is enabled or not.

it should be callable in a manner like `X = tf.make_ndarray(model(X))`

**Will this change the current api? How?** To the best of my knowledge, it will not change the surface level API.

**Who will benefit with this feature?**
This will particularly benefit anyone who has to run multiple, separately-trained networks in the same python session where at least one of them is a port from TF 1.X that requires eager execution to be disabled. Because Eager Execution is a global setting (to the best of my knowledge), this causes the output to be as Tensors when they may normally be expected to be EagerTensors.
`X=model(X)` returns 'X' as a EagerTensor with EagerExecution but returns a Tensor with EagerExecution disabled. This could easily cause downstream data processing problems (i.e. numpy math operations no longer work because of non-compatibility).

The implementation of this would remove a significant barrier to making generalized code/networks. It also prevents unnecessary imports of tensorflow or tensorflow functions.

Supposedly, Tensors have to be evaluated in a graph because of something to do with unknown states (or something that sounds similar) and EagerTensors don't have that limitation. However, TF clearly has the tf.math module and knows what the numbers are and knows how to do math with them. I don't see why the tf.math module can't simply have a function that can return a ndarray.

**Any Other info.**

**Comment by ccrusius** [comment]
Graph mode only deals with symbolic tensors, so ndarrays don't fit there. This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by EnderWiggin14** [comment]
This is absolutely a feature request. I never claimed it was a bug either. Please do not put words in my mouth. To my knowledge I filled out all of the issue template for a feature request aside from "Additional Info"

I have already used stack exchange and the frank reality is that most question are left unanswered. Most (if not all) of the results that are pulled up by searching are strictly related tensorflow 1.X. There are functions that transform one kind of tensor to other tensors but nothing that transforms a tensor to an EagerTensor or directly into a ndarray. I am well aware of the the whole session.run() method, but when I've tried getting a session (I don't remember which function that is) it will return the global session (or create a new one if one doesn't exist). The output of the model that forced eager execution (it is not my model but a different package built from TF 1 that uses compatibility functions of TF 2) can no longer be fed into a tf.keras built autoencoder (running non-eagerly because of the graph constructed ANN turns off eager execution) because the tensor didn't originate from the same graph. Why tensors are not portable between models is beyond me. Both models work fine if they are alone.

I am aware that there are functions that allow the enabling and disabling of eager execution, but those functions also come with documentation that claims that they can only be run before any models or sessions are constructed. I can't just turn it on and off.
