### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'lambda'

### ISSUE THREAD

**Issue by Delarti** [tensorflow/tensorflow#41164]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
N/A (google colab)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
n/a
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
1.15.2
- Python version:
3.6.9
- Bazel version (if compiling from source):
n/a

**Describe the current behavior**
I cannot load a saved model containing a subclass of keras.regularizer.Regularizer.
Error = TypeError: __init__() got an unexpected keyword argument 'lambda'

**Describe the expected behavior**
I expect it to load my model since the model works well and is saved correctly.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
class My_Regularizer(Regularizer):
    def __init__(self, lambd, matrix_x, matrix_y, matrix_z):
        self.lambd = lambd
        self.matrix_x = matrix_x
        self.matrix_y = matrix_y
        self.matrix_z = matrix_z

    def __call__(self, x):
        return tf.linalg.tensor_diag(tf.diag_part(self.lambd * K.dot(K.transpose(K.square(x)), K.variable(self.matrix_x, dtype='float32') + K.variable(self.matrix_y, dtype='float32') + K.variable(self.matrix_z, dtype='float32'))))

    def get_config(self):
        return {'lambd': float(self.lambd),
                'matrix_x': self.matrix_x,
                'matrix_y': self.matrix_y,
                'matrix_z': self.matrix_z,
               }
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-d7b61e297765> in <module>()
----> 1 test = load_model('/content/drive/My Drive/Memoire/Wolfsky models/final_regularized_model.h5')

13 frames
/usr/local/lib/python3.6/dist-packages/keras/regularizers.py in from_config(cls, config)
     24     @classmethod
     25     def from_config(cls, config):
---> 26         return cls(**config)
     27 
     28 

TypeError: __init__() got an unexpected keyword argument 'lambda'
```

**Comment by amahendrakar** [comment]
@Delarti,
Could you please provide the complete code to reproduce the issue reported here. Alternatively, you can share the Colab file you are running.

Also, is there any particular reason you are using TF v1.15? Please upgrade to TF v2.2 and check if you are facing the same issue. Thanks!
