### ISSUE TITLE
pypi packages built against different CUDA versions needed

### ISSUE THREAD

**Issue by fokx** [tensorflow/tensorflow#41179]
**System information** Arch Linux
- TensorFlow version (you are using): 2.2.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Different Linux distributions ships with different CUDA & cudnn version, it would help researchers save a lot of time to build pip package if you can provide pypi package built against different CUDA version, just as what pytorch has done:
![pytorch](https://user-images.githubusercontent.com/36614441/86866464-8f616500-c0c0-11ea-8aa0-881ce6d65032.png)
Thank you!

**Will this change the current api? How?**
No.
**Who will benefit with this feature?**
People without plenty of resources.
**Any Other info.**
No.

**Comment by MarkDaoust** [comment]
This question is above my level. +Gunan to confirm.

My understanding is that the support matrix for TensorFlow is already huge and unmanageable, and we can't add new dimensions to it.

I think we're just going to close this.

**Comment by gunan** [comment]
Mark has a great point. In addition:
pypi is a very limited resource. If you look at the above image carefully, you will see that most pytorch packages are not available on pypi. They are served out of "download.pytorch.org". 
So, we will need to create a separate pip package mirror we own to do this. But then we have the problem of expanded support matrix.

While in the future this might happen, at the moment this is not a priority for TF.

**Comment by fokx** [comment]
Hope you can build a separate pip package mirror soon!

**Comment by goern** [comment]
@fridex @sub-mod @harshad16
