### ISSUE TITLE
Shape issue for `tensordot` with nested `vectorized_map` and graph exectued function

### ISSUE THREAD

**Issue by rrkarim** [tensorflow/tensorflow#41170]
I have some issues with shapes for nested vectorized function call, I'm including the simplest code here:
```python
import tensorflow as tf
x = tf.ones((100, 10, 5))
@tf.function()
def tdot(x):
    res = tf.tensordot(x, x, 1)
    return res
def func(x):
    def func_inner(x_):
        return tf.vectorized_map(tdot, x_)
    return tf.vectorized_map(func_inner, x)

@tf.function
def test():
    res = func(x)
    print(res.shape) # shape should be (100, 10) instead of (None, 10)

test()
```
Isn't it expected for the first dimension to be defined in the resulting tensor (see the comment). Or I am missing something in the docs?

**Comment by ravikyram** [comment]
@rrkarim 
Please, let us know which TF version you are using? Also, in the given code you have defined the functions and you are not calling.On calling the test function i got the output(`<tensorflow.python.eager.def_function.Function at 0x7fd6a4a9e630>`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/d9b21ed97733e50fab2d1ff4127afa38/untitled95.ipynb).
Please, help us with the reproducible code.Thanks!

**Comment by rrkarim** [comment]
@ravikyram edited the code.

**Comment by ravikyram** [comment]
@rrkarim 

If you run in eager mode instead of using autograph you will not face this issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/388c03f523202c42f04dab218f85e24c/untitled101.ipynb).Thanks!

**Comment by rrkarim** [comment]
@ravikyram If we change tensordot to other tf op, we dont have the issue.

**Comment by ravikyram** [comment]
I am able to reproduce the issue in colab with TF versions 2.2,2.3-rc1,nightly versions.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/33086d474185f4df68d2cfbb43dea014/untitled100.ipynb).If i run the code in eager mode you will not see any issue.Thanks!

**Comment by rrkarim** [comment]
@ravikyram If also run with no vectorization, we don't see any issues.

**Comment by jvishnuvardhan** [comment]
@rrkarim @tf.function builds a callable graph of the function that it decorates. Using nested @tf.function is not suggestable. When I removed @tf.function decorating `def test():`, you can print the shape as expected. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/c013d0fccace2c99f967d9ce98261640/untitled100.ipynb).

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by rrkarim** [comment]
@jvishnuvardhan I don't get why it is not suggestable, can you please expand on that? And how it is connected to `vectorized_map` being used?

**Comment by rrkarim** [comment]
@jvishnuvardhan Can you please recommend the easiest way of debugging pfor?

**Comment by agarwal-ashish** [comment]
TF Shape inference and constant propagation are not perfect.  PFor (underlying tf.vectorized_map) does an explicit set_shape to make up for this.  Please see:
https://github.com/tensorflow/tensorflow/blob/8b87c1a09bf156ca9a42d9f72fad07da62100318/tensorflow/python/ops/parallel_for/pfor.py#L1564

It looks like the constant_value call there is not able to extract that value. Note that the value is passed in by vectorized_map here:
https://github.com/tensorflow/tensorflow/blob/8b87c1a09bf156ca9a42d9f72fad07da62100318/tensorflow/python/ops/parallel_for/control_flow_ops.py#L428

Can you check where the shape values are first becoming unknown in the call chain ?

**Comment by rrkarim** [comment]
@agarwal-ashish thanks, I'm debugging the issue right now. The thing I observe is that assigning `x = tf.ones((100, 10, 5, 5))` works as expected.

**Comment by jvishnuvardhan** [comment]
@rrkarim Is this still an issue? Please close the issue if this was already resolved for you. Thanks!

**Comment by rrkarim** [comment]
Closing, thanks.
