### ISSUE TITLE
C++ Program crashed while running tensorflow 2.0.0 with cuda 10.0 on NVIDIA Tegra Tx2

### ISSUE THREAD

**Issue by harendra247** [tensorflow/tensorflow#41184]
I am trying to build tensorflow2.0.0 on tx2. below are the details.

**System information**
- OS Platform and Distribution: jetpack 4.3
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.0.0
- Python version: 2.7
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 7.5
- CUDA/cuDNN version: 10.0/7.6.3
- GPU model and memory: Tegra TX2

**Describe the current behavior**
when I try running sample application it is crashing. With error logs as "CUDA runtime implicit initialization on GPU:0 failed. Status: unknown error"

**Describe the expected behavior**
it should start a session.

**Standalone code to reproduce the issue**
Sample Code 
```
#include <tensorflow/core/platform/env.h>
#include <tensorflow/core/public/session.h>
#include <iostream>
using namespace std;
using namespace tensorflow;

int main()
{
    Session* session;
    Status status = NewSession(SessionOptions(), &session);
    if (!status.ok()) {
        cout << status.ToString() << "\n";
    }
    session->Close();
    cout << "Session successfully created.\n";
}

```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.10)

project(test_hello)

set(TENSORFLOW_LIBRARIES tensorflow_cc protobuf)
add_executable(example example.cpp)
set(CUDA_NVCC_FLAGS
        ${CUDA_NVCC_FLAGS};
        -O3 -gencode arch=compute_30,code=sm_30;
        --std=c++11
        )
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Link the Tensorflow library.
# TensorFlow headers
include_directories("/usr/local/include/")
include_directories("/usr/local/include/tensorflow/")
include_directories("/usr/local/include/third-party/")
target_link_libraries(example "/usr/local/lib/libtensorflow_cc.so")

# You may also link cuda if it is available.
find_package(CUDA)
if(CUDA_FOUND)
  target_link_libraries(example ${CUDA_LIBRARIES})
endif()

```

**Other info / logs**

```
$ ./example 
2020-07-08 15:01:34.122381: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-07-08 15:01:34.127413: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:973] ARM64 does not support NUMA - returning NUMA node zero
2020-07-08 15:01:34.127566: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: NVIDIA Tegra X2 major: 6 minor: 2 memoryClockRate(GHz): 1.3
pciBusID: 0000:00:00.0
2020-07-08 15:01:34.127608: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-07-08 15:01:34.127693: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:973] ARM64 does not support NUMA - returning NUMA node zero
2020-07-08 15:01:34.127815: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:973] ARM64 does not support NUMA - returning NUMA node zero
2020-07-08 15:01:34.127879: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
Internal: CUDA runtime implicit initialization on GPU:0 failed. Status: unknown error
Segmentation fault (core dumped)

```

I am very new to tensorflow ...not sure what is going on. Appreciate the help.

NOTE: I even tried by installing tensorflow-1.15.0 and running the same program. Same crash happens.

**Comment by amahendrakar** [comment]
@harendra247,
Could you please update TensorFlow to v2.2 and check if you are facing the same issue?

Also, please take a look at the [tested build configurations](https://www.tensorflow.org/install/source#gpu) and check if you are running the compatible CUDA and cuDNN versions. Thanks!

**Comment by harendra247** [comment]
@amahendrakar Thank you for replying. 
Yes I am running compatible CUDA and cuDNN versions (10.0 and 7.6.3). This is coming by defaults in the jetpack 4.3. , I started this activity with tensorflow-2.2.0 but it was not even compiling so I downgraded to 2.0.0.

**Comment by harendra247** [comment]
@amahendrakar 

I was trying to search this error on google. I found at some place to set CUDA_VISIBLE_DEVICES env variable. I tried the program as follows and now I am facing another error.

_*setenv("CUDA_VISIBLE_DEVICES", "", 0);*_

Update Sample Code
```
#include <tensorflow/core/platform/env.h>
#include <tensorflow/core/public/session.h>
#include <iostream>
using namespace std;
using namespace tensorflow;

int main()
{
    setenv("CUDA_VISIBLE_DEVICES", "", 0);    // <--- Here the line added
    Session* session;
    Status status = NewSession(SessionOptions(), &session);
    if (!status.ok()) {
        cout << status.ToString() << "\n";
    }
    session->Close();
    cout << "Session successfully created.\n";
}
```
Error logs are as follows.

```
$ ./example
2020-07-10 15:49:20.957008: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so
.1                                                                                        
2020-07-10 15:49:20.961536: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-cap
able device is detected                                           
2020-07-10 15:49:20.961633: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this
 host (civilmapstx2-desktop): /proc/driver/nvidia/version does not exist
Session successfully created.                                  
```

**Comment by sanjoy** [comment]
The error with the `CUDA_VISIBLE_DEVICES` change is a red herring: that disables GPUs and thus the program is failing.

Regarding your original problem, it is tricky to narrow down `cudaErrorUnknown`.  Can you cat `.tf_configure.bazelrc` and paste it here?  Maybe we'll be able to spot a red flag in there.

**Comment by harendra247** [comment]
@sanjoy,

I think this is duplicate of #41191.


I have pasted .tf_configure.bazelrc in the issue #41191. Can you please comment on that issue. 

I am closing it. I'll continue discussing #41191 .
