### ISSUE TITLE
 module 'tensorflow' has no attribute 'compat' in 2.2.0

### ISSUE THREAD

**Issue by sejal129** [tensorflow/tensorflow#41187]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow version: 2.2.0
- Python version: 3.8.2
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: 10.1
- GPU model and memory: 

After installing tensorflow 2.2.0 and CUDA 10.1 by using pip but when I am importing tensorflow, I get this error - module 'tensorflow' has no attribute 'compat' .

**Comment by mihaimaruseac** [comment]
What is the output of `pip list`?

**Comment by sejal129** [comment]
@mihaimaruseac 
Check This:
![Screenshot (81)](https://user-images.githubusercontent.com/46136132/86943286-dfddce80-c163-11ea-8af7-902540bf1e25.png)

![Screenshot (82)](https://user-images.githubusercontent.com/46136132/86943227-cfc5ef00-c163-11ea-8d27-2307ea2c1c80.png)

**Comment by amahendrakar** [comment]
@sejal129,
Comments from similar issues [#1](https://github.com/tensorflow/tensorflow/issues/40422#issuecomment-651677723), [#2](https://github.com/tensorflow/tensorflow/issues/40422#issuecomment-651677723), [#3](https://github.com/tensorflow/tensorflow/issues/37525#issuecomment-598480859), [#4](https://github.com/tensorflow/tensorflow/issues/40819#issuecomment-650028666) say installing `tensorflow-estimator` fixes the error. 

Could you please try uninstalling TensorFlow completely and check if a fresh install works? Thanks!

**Comment by sejal129** [comment]
> @sejal129,
> Comments from similar issues [#1](https://github.com/tensorflow/tensorflow/issues/40422#issuecomment-651677723), [#2](https://github.com/tensorflow/tensorflow/issues/40422#issuecomment-651677723), [#3](https://github.com/tensorflow/tensorflow/issues/37525#issuecomment-598480859), [#4](https://github.com/tensorflow/tensorflow/issues/40819#issuecomment-650028666) say installing `tensorflow-estimator` fixes the error.
> 
> Could you please try uninstalling TensorFlow completely and check if a fresh install works? Thanks!

Yaa. I have tried uninstalling and then fresh installing multiple times.

**Comment by amahendrakar** [comment]
@sejal129,
Please run the below commands in that particular order and check if it works.


`pip uninstall tensorflow-gpu-estimator`
`pip uninstall tensorflow-gpu`
`pip uninstall tensorflow-estimator`
`pip uninstall tensorflow`
`pip install tensorflow`


Also, try installing TensorFlow in a virtual environment and check if you are facing the same error. Thanks!

**Comment by mihaimaruseac** [comment]
@sejal129 please always post the textual output, not an image. The text is easier to search (so others can also identify if they have similar issues), visible even for people who cannot see the images (eye reasons, data reasons, getting the notification via email instead of from GitHub, etc.), and easier to select, copy and paste in responses.

In this case, you have both the gpu and the non-gpu versions of the code. Recommendation is to uninstall all TF ecosystem packages and install `tensorflow` (it should be the same as `tensorflow_gpu`) after that. Doing so in a virtual environment is even better

**Comment by sejal129** [comment]
> @sejal129 please always post the textual output, not an image. The text is easier to search (so others can also identify if they have similar issues), visible even for people who cannot see the images (eye reasons, data reasons, getting the notification via email instead of from GitHub, etc.), and easier to select, copy and paste in responses.
> 
> In this case, you have both the gpu and the non-gpu versions of the code. Recommendation is to uninstall all TF ecosystem packages and install `tensorflow` (it should be the same as `tensorflow_gpu`) after that. Doing so in a virtual environment is even better

Okay. I will do that

**Comment by sejal129** [comment]
> @sejal129,
> Please run the below commands in that particular order and check if it works.
> 
> `pip uninstall tensorflow-gpu-estimator`
> `pip uninstall tensorflow-gpu`
> `pip uninstall tensorflow-estimator`
> `pip uninstall tensorflow`
> `pip install tensorflow`
> 
> Also, try installing TensorFlow in a virtual environment and check if you are facing the same error. Thanks!

Thanks. I will try this.
