### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow_core.keras'

### ISSUE THREAD

**Issue by tongtiger** [tensorflow/tensorflow#41186]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10, anaconda
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Nope
- TensorFlow installed from (source or binary): Anaconda Navigator
- TensorFlow version (use command below):  tensorflow 2.0
- Python version: 3.6.10
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I wrote the code below, and I came up with an error.(error report is attached under the code)
------------------------------------------------------------------------------------------------------------------------------------------
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

import pandas as pd
import numpy as np
import tensorflow as tf

np.random.seed(3)
tf.random.set_seed(3)

'''
dataset = np.loadtxt("C:\\Users\\tongt\\PycharmProjects\\kaggle\\titanic\\train_sample1.csv", delimiter= ',')
Y = dataset[:, 0]
X = dataset[:, 1:6+1]
'''
df= pd.read_csv("C:\\Users\\tongt\\PycharmProjects\\kaggle\\train_sample1.csv")

dataset = df.values
X = dataset[:, 2:6+1]
Y = dataset[:, 1]

model = Sequential()
model.add(Dense(12, input_dim=6, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss = 'binary_crossentropy', optimizer='adam', metrics = ['accracy'])

model.fit(X, Y, epochs = 200, batch_size = 10)
--------------------------------------------------------------------------------------------------------------------------------------

C:\Users\tongt\anaconda3\envs\ML\python.exe C:/Users/tongt/PycharmProjects/kaggle/code.py
Traceback (most recent call last):
  File "C:/Users/tongt/PycharmProjects/kaggle/code.py", line 1, in <module>
    from tensorflow.keras.models import Sequential
  File "C:\Users\tongt\anaconda3\envs\ML\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\tongt\anaconda3\envs\ML\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\tongt\anaconda3\envs\ML\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\tongt\anaconda3\envs\ML\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\tongt\anaconda3\envs\ML\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\tongt\anaconda3\envs\ML\lib\site-packages\tensorflow_core\python\__init__.py", line 75, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "C:\Users\tongt\anaconda3\envs\ML\lib\site-packages\tensorflow_core\python\framework\framework_lib.py", line 25, in <module>
    from tensorflow.python.framework.ops import Graph
  File "C:\Users\tongt\anaconda3\envs\ML\lib\site-packages\tensorflow_core\python\framework\ops.py", line 58, in <module>
    from tensorflow.python.platform import app
  File "C:\Users\tongt\anaconda3\envs\ML\lib\site-packages\tensorflow_core\python\platform\app.py", line 23, in <module>
    from absl.app import run as _run
  File "C:\Users\tongt\anaconda3\envs\ML\lib\site-packages\absl\app.py", line 35, in <module>
    import pdb
  File "C:\Users\tongt\anaconda3\envs\ML\lib\pdb.py", line 76, in <module>
    import code
  File "C:\Users\tongt\PycharmProjects\kaggle\code.py", line 1, in <module>
    from tensorflow.keras.models import Sequential
  File "C:\Users\tongt\anaconda3\envs\ML\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\tongt\anaconda3\envs\ML\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\tongt\anaconda3\envs\ML\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'tensorflow_core.keras'

----------------------------------------------------------------------------------------------------------------------------------------------

I already searched google and tensorflow document to fix this problem, but I cannot handle this one... 
So I tried to reinstall anaconda and pycharm. But it didn't work..

**Describe the expected behavior**
dd
**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@tongtiger 
Please refer to these issues with similar error and let us know if it helps:

#34607 #32768 #37144 #36441 #32768  [link](https://stackoverflow.com/questions/59253581/flask-keras-webservice-modulenotfounderror-no-module-named-tensorflow-core-ker) [link1](https://www.kaggle.com/c/digit-recognizer/discussion/69597) [link2](https://www.edureka.co/community/67388/modulenotfounderror-no-module-named-keras).

**Comment by tongtiger** [comment]
> @tongtiger 
> 
> Please refer to these issues with similar error and let us know if it helps:
> 
> 
> 
> #34607 #32768 #37144 #36441 #32768  [link](https://stackoverflow.com/questions/59253581/flask-keras-webservice-modulenotfounderror-no-module-named-tensorflow-core-ker) [link1](https://www.kaggle.com/c/digit-recognizer/discussion/69597) [link2](https://www.edureka.co/community/67388/modulenotfounderror-no-module-named-keras).
> 
> 

Actually, I have already read that but I couldn’t solve the problem... Do I need to add CUDA to path even if I don’t use Tensorfow GPU?

**Comment by gowthamkpr** [comment]
@tongtiger Please try it using the latest version of tensorflow i.e., 2.3.0 and see if the issue still persists. Thanks!
