### ISSUE TITLE
How to gather the last X indices embeddings before every grouping of False in a boolean mask for every row in a batch

### ISSUE THREAD

**Issue by vyshnavigutta369** [tensorflow/tensorflow#41185]
Urgent help needed in doing the below operation. Mask for input is given, its shape is [batch size, no of timesteps]. From this, I need to collect X number of embeddings of shape [batch size, timestep index, embedding size] such that they are grouped just before each grouping of False.

say mask of a batch size of 1 is T,T,T,F,F,F,F,|T,T,F,F,F,F,F and X=2 (by '|', I assumed a break which indicates a row split length=7), then should get list of concatenated embeddings given by indices (1,2) (8, 9). In the case when X is greater than number of Trues, should return the embeddings from index of first True till index which is X away from it.

Should be able to replicate the above when batch size is variable without having to do individually for each batch as my batch size is pretty high. Output should be [ [ (1,2) , (.,.),.. for other batches at first row split (0:7) ] , [ (8,9) , (.,.) for other batches at second row split (7:14)], ..]

Any help will be highly appreciated.

**Comment by ravikyram** [comment]
@vyshnavigutta369 

Request you to fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!
