### ISSUE TITLE
index error found in tf.keras.backend.dot function 

### ISSUE THREAD

**Issue by sataliulan** [tensorflow/tensorflow#41180]
<em>Sorry for bothering. an error both found in tf1.15</em>

**System information**
- OS: Windows 10 1904
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tensorflow 1.15 and tensorflow 2.1
- Python version: python 3.6 for tensorflow 1.15, python 3.6 for tensorflow 2.1
- CUDA/cuDNN version:10
- GPU model and memory: Nvidia rtx 2080ti 11g

**Describe the current behavior**
Here is the source code of tensorflow.keras.backend.dot:
`
@keras_export('keras.backend.dot')
def dot(x, y):
  """Multiplies 2 tensors (and/or variables) and returns a *tensor*.

  When attempting to multiply a nD tensor
  with a nD tensor, it reproduces the Theano behavior.
  (e.g. `(2, 3) * (4, 3, 5) -> (2, 4, 5)`)

  Arguments:
      x: Tensor or variable.
      y: Tensor or variable.

  Returns:
      A tensor, dot product of `x` and `y`.
  """
   if ndim(x) is not None and (ndim(x) > 2 or ndim(y) > 2):
        x_shape = []
        for i, s in zip(int_shape(x), tf.unstack(tf.shape(x))):
            if i is not None:
                x_shape.append(i)
            else:
                x_shape.append(s)
        x_shape = tuple(x_shape)
        y_shape = []
        for i, s in zip(int_shape(y), tf.unstack(tf.shape(y))):
            if i is not None:
                y_shape.append(i)
            else:
                y_shape.append(s)
        y_shape = tuple(y_shape)
        y_permute_dim = list(range(ndim(y)))
        y_permute_dim = [y_permute_dim.pop(-2)] + y_permute_dim
        xt = tf.reshape(x, [-1, x_shape[-1]])
        yt = tf.reshape(tf.transpose(y, perm=y_permute_dim), [y_shape[-2], -1])
        return tf.reshape(tf.matmul(xt, yt),
                          x_shape[:-1] + y_shape[:-2] + y_shape[-1:])
    if is_sparse(x):
        out = tf.sparse.sparse_dense_matmul(x, y)
    else:
        out = tf.matmul(x, y)
    return out

`
The issue is that I have a tensor x, which shape is (?,?,128) and a tensor y with shape (128,) . Thus , satisfy the 
if judgement clause, and variant **y_permute_dim will be [0]**.  Next, an index out of range error would be raised
from the code `y_permute_dim = [y_permute_dim.pop(-2)] + y_permute_dim`.
It is obvious, for there is only one element in y_permute_dim.
This error was caught both in tensorflow_backend.py(tensorflow1.15), and source code is just the same in backend.py(tensorflow 2.1)

Looking forward for your reply.

**Other info / logs** I
  File "d:\Anaconda3\envs\tf1.15\lib\site-packages\keras\backend\tensorflow_backend.py", line 1365, in dot
    y_permute_dim = [y_permute_dim.pop(-2)] + y_permute_dim
IndexError: pop index out of range

**Comment by amahendrakar** [comment]
@sataliulan,
In order to expedite the trouble-shooting process, could you please provide a sample code to reproduce the issue reported here. Thanks!
