### ISSUE TITLE
model.fit hangs when using matplotlib in the same script.

### ISSUE THREAD

**Issue by dddiaz** [tensorflow/tensorflow#41183]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
MacOS Catalina 10.15.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
No
- TensorFlow installed from (source or binary):
Anaconda 3.6
- TensorFlow version (use command below):
unknown 2.0.0
- Python version:
Python 3.6
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
N/A
- CUDA/cuDNN version:
N/A
- GPU model and memory:
Radeon Pro 560X / Intel UHD Graphics 630

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When displaying a plot, then running model.fit, the following error is produced:
```bash
Train on 60000 samples
Epoch 1/5
OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
```
I have discovered two workarounds:
-  One workaround is described in this github issue # https://github.com/dmlc/xgboost/issues/1715
```python
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'
```
- The other is to remove any references to matplot lib code. I have included an example in my sample code below.

**Describe the expected behavior**
I would expect that leveraging matplotlib code and tensorflow code in the same script to work without any work aorunds.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```python
if __name__ == '__main__':
    import tensorflow as tf
    import matplotlib.pyplot as plt

    mnist = tf.keras.datasets.mnist
    (x_train, y_train), (x_test, y_test) = mnist.load_data()

    # This pyplot block of code contributes to the error. Without it, model.train functions fine.
    # Begin Block
    def display_image(position):
        image = x_train[position].squeeze()
        plt.title('Example %d. Label: %d' % (position, y_train[position]))
        plt.imshow(image, cmap='gray')
    display_image(0)
    # End block

    x_train = x_train.reshape(len(x_train), 28, 28, 1)
    x_test = x_test.reshape(len(x_test), 28, 28, 1)

    model = tf.keras.models.Sequential([
        tf.keras.layers.Conv2D(filters=6, kernel_size=(5, 5), activation='relu', input_shape=(28, 28, 1)),
        tf.keras.layers.AveragePooling2D(),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(units=10, activation='relu'),
        tf.keras.layers.Dense(10, activation=tf.nn.softmax)
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    """
    # This will throw the error
    OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized.
    OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
    """
    model.fit(x_train, y_train, epochs=5, verbose=1)

    # test accuracy
    model.evaluate(x_test, y_test)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

This error doesnt seem to be reproducible in google collab.

**Comment by jvishnuvardhan** [comment]
@dddiaz Sorry for the late response. I ran your code in `TF2.3` and `tf-nightly` and I don't see the code hangs when matplotlib in the same script. Please take a look at the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/fcca315efc54b535ec23fa5380c2ca2a/untitled22.ipynb).

When I ran this code in GPU it took ~25 sec and in CPU it took ~110 sec. 

Please verify once and close the issue if this was resolved for you. Thanks!
