### ISSUE TITLE
Building a custom delegate as shared library

### ISSUE THREAD

**Issue by blacktoby** [tensorflow/tensorflow#41194]
## Description of the system/problem
My research group is currently working on a custom delegate to accelerate neural networks using FPGAs.
We wanted to build a custom delegate for the inference of the neural networks using the tensorflow lite interpreter.
To achieve this we wanted to build a shared library which can be loaded by "tflite.load_delegate" - using the the tflite_runtime in python.

I created the delegate using c++, with help of the official tensorflow lite delegate [guide](https://www.tensorflow.org/lite/performance/delegates) and the source code of the [nnapi delegate](https://github.com/tensorflow/tensorflow/blob/v2.1.1/tensorflow/lite/delegates/nnapi/nnapi_delegate.cc).
For compiling and linking I used CMake and built a static library of tensorflow lite using the [build scripts](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/make). I made sure, to use the same git repository version of tensorflow, as the newest runtime wheel build did (tflite_runtime-2.1.0.post1) and which I am using.

Writing and compiling a small inference example in c++ using my delegate and the compiled static library works as expected and without errors. If I want to use my delegate as shared library in combination with the tflite_runtime, it comes to weird behaviors:  
The tensors seem not to be allocated directly. Data access / Dimension array access are leading to segmentation faults. Allocation Types and Data Types containing really large numbers instead of enum indices.

I suppose there is something wrong in the way I compile my shared library. I will append the source code I used.
Any help is appreciated!

## Source Code
Delegate source code, with minimal example. Requires compiled tensorflow lite static library:
[delegate.zip](https://github.com/tensorflow/tensorflow/files/4890288/delegate.zip)

Python minimal example using tflite_runtime-2.1.0.post1 and numpy:
[python_example.zip](https://github.com/tensorflow/tensorflow/files/4890286/python_example.zip)

Used tensorflow git version: `0.6.0-76902-gd855adfc5a` (output of `git describe`)

Expected output from delegate:
```
OutputIndex: 10 
Using outputIndex: 10
Allocation type is: 2 kTfLiteArenaRw
tensor type: 9 INT8
dims pointer: 0x557c461b2d20 is null: 0
dims: [1 75 75 64  ]
```

Given output using delegate shared library:
```
OutputIndex: 10 
Using outputIndex: 10
Allocation type is: 33539632 UNKNOWN!
tensor type: 1016998161 Unknown type
dims pointer: 0x15f900 is null: 0
Segmentation fault (core dumped)
```

**Comment by blacktoby** [comment]
I managed to get this working:  
I was building the static library with the false git repo version (not the one mentioned above).
Using the version `0.6.0-76902-gd855adfc5a` fixed the problem.
Before the static library could be build I had to manually fix the Makefile regarding the commit in issue #36184.

Is there a way to contribute to the docs, so other people trying to build shared library delegate may have a example how to build it?

**Comment by sjoshi30** [comment]
Hi @blacktoby I am trying to create custom delegate and shared library too. I'm new to delegates. Can you tell me the steps to build the delegate.zip i.e. I need to link it with libtensorflow-lite.so?
Also when I try to execute your python example I get error
OSError: ./libastericsdelegate.so: cannot open shared object file: No such file or directory
(But the library is present)
Did you face this issue?

**Comment by blacktoby** [comment]
Well, I think you've tried to use my delegate. Which I wouldn't recommend, since it was only to rebuild my issue.
As I said in my post, I have built a static library with the Makefiles located in [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/make).
With the static library created, you can build your own delegate and link this static library to use all the TF-Lite functionality provided.
