### ISSUE TITLE
module 'tensorflow.keras.layers' has no attribute 'Conv1DTranspose'

### ISSUE THREAD

**Issue by mhuertascompany** [tensorflow/tensorflow#41195]
Hello,

I am trying to import tf.keras.layers.conv1DTranspose in colab and this creates an error message.
I have followed this fix: https://github.com/tensorflow/tensorflow/issues/40937

However, this makes tensorflow probability import to fail:
----> 3 import tensorflow_probability as tfp
      4 import numpy as np
      5 from sklearn import preprocessing

4 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/experimental/auto_batching/frontend.py in <module>()
     43 from tensorflow.python.autograph.converters import return_statements
     44 from tensorflow.python.autograph.core import converter
---> 45 from tensorflow.python.autograph.core import naming
     46 from tensorflow.python.autograph.pyct import anno
     47 from tensorflow.python.autograph.pyct import inspect_utils

ImportError: cannot import name 'naming'

Thanks for your help!

Marc

**Comment by AbhinavTalari** [comment]
I would like to work on this if no one is working on it

**Comment by ravikyram** [comment]
@mhuertascompany 

Please, let us know which tensorflow version you are using?

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by ravikyram** [comment]
@mhuertascompany 

I have tried in colab with TF version 2.2 and i am not seeing any issue while import naming.Please, find the gist [here.](https://colab.research.google.com/gist/ravikyram/7e795f67892441fb926515aac30c309e/untitled96.ipynb).Thanks!

**Comment by mhuertascompany** [comment]
Thanks. The problem comes when you try to import tensorflow-probability with 2.3-rc0 as explained here:
https://github.com/tensorflow/tensorflow/issues/40937

I need to upgrade to 2.3-rc0 to be able to use keras.layers.Conv1DTranspose as explained here: https://github.com/tensorflow/tensorflow/issues/40937

However, then, the import of tf-probability fails.
See here:
https://colab.research.google.com/drive/1DC7FkM7m7BNlajmAfz_xTZO7EnIrgMRm?usp=sharing

**Comment by ravikyram** [comment]
@mhuertascompany 

I am able to replicate the issue with TF 2.3-rc1 anf nightly versions.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/f18fe304e86da3b20a48218ad20c8ca9/untitled103.ipynb).This issue seems to be duplicate#40584 .Thanks!

**Comment by ravikyram** [comment]
@mhuertascompany 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment]
@mhuertascompany 

I have tried in colab with TF nightly version(`2.4.0-dev20200730`) and i am not seeing any issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/f558ae06a47fb650d1e0e6d22511d8f5/untitled208.ipynb).Please, verify once and close the issue.Thanks!

**Comment by mhuertascompany** [comment]
Thanks!
