### ISSUE TITLE
TF-Lite Ops supported (available)

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#41206]
Is there a way to check what operations (list of all operators) are supported and distinguish CPU vs. GPU or other platform specifics?
What is the best way to check their correction of operation and functionality?

**Comment by srjoglekar246** [comment]
Exhaustive list of CPU ops can be seen [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/versioning/runtime_version.cc).

The platform-specific ops that are supported with [TFLite Delegates](https://www.tensorflow.org/lite/performance/delegates) are usually found in the code for that delegate, for eg [GPU](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/common/operations.h#L33) & [Hexagon DSP](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/hexagon). Note that there might be certain restrictions on parameters that determine if it will get accelerated with that particular delegate.

Assuming you have a model, you can compare performance on CPU vs platforms using the following tools:
1. [Benchmark tool](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark) for latency performance.
2. [Accuracy tasks](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/evaluation/tasks) to gauge correctness. There is also the [inference_diff](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/evaluation/tasks/inference_diff) tool that provides raw output errors for CPU vs delegate, as long as you know how to interpret the output tensors.

**Comment by peter197321** [comment]
Thank you for your answer. 
B.T.W: Do you somehow able to distinguish on OPs target for 8bit vs float?

**Comment by srjoglekar246** [comment]
The individual delegate documentation (linked above) will usually describe what kind of models they support. A more consolidated chart is [here](https://www.tensorflow.org/lite/performance/model_optimization#quantization).
