### ISSUE TITLE
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by shoujomami** [tensorflow/tensorflow#41205]
hello i keep getting error 
(The max number of people in your video.
If no input and press Enter, the number of be set to default: 1 person.
The max number of people in your video: 2
--------------
If you want the detailed information of GIF, input yes.
If no input and press Enter, the generation setting of GIF will be set to default.
warn If you input warn, then no GIF will be generated.
the detailed information[yes/no/warn]: yes
Traceback (most recent call last):
  File "C:\Users\laris\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\laris\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\laris\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\laris\anaconda3\envs\tensorflow\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\laris\anaconda3\envs\tensorflow\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/openpose_3dpose_sandbox_vmd.py", line 9, in <module>
    import tensorflow as tf
  File "C:\Users\laris\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\laris\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\laris\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\laris\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\laris\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\laris\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\laris\anaconda3\envs\tensorflow\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\laris\anaconda3\envs\tensorflow\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
(tensorflow) C:\Users\laris\OneDrive\Bureaublad\OpenMMD_1.0\3d-pose-baseline-vmd>) 
 i trying to follow this video https://www.youtube.com/watch?v=hKx6jl9a5-I&t=293s
but i keep run problem after problem please someone help . i keep run into trials of errors

**Comment by shoujomami** [comment]
can you please make it is easier what do i need to type ?  and what my issu is? 
 i keep uninstall-install

**Comment by amahendrakar** [comment]
@shoujomami,
Please check [this comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) thread from a similar issue and let us know if it helps. 

Also, please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) and check if you have all compatible dependencies installed. Thanks!

**Comment by shoujomami** [comment]
> @shoujomami,
> Please check [this comment](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) thread from a similar issue and let us know if it helps.
> 
> Also, please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) and check if you have all compatible dependencies installed. Thanks!

well my GPU is Geforec GTX 960 and CPU is  I5 650 " 3.20GHZ 3.19 GHZ 
i wonder if my CPUI support AVX instructions

**Comment by amahendrakar** [comment]
@shoujomami,
Intel's product specification page for [i5-650](https://ark.intel.com/content/www/us/en/ark/products/43546/intel-core-i5-650-processor-4m-cache-3-20-ghz.html) doesn't mention support for AVX.

In this case as mentioned below, you can try building TensorFlow [from source](https://www.tensorflow.org/install/source_windows) or use [Google Colab](https://colab.research.google.com/) instead.


> * Try Google Colab to use TensorFlow.
>   
>   * The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true). You get pre-installed latest stable TF version. Also you can use `pip install`  to install any other preferred TF version.
>   * It has an added advantage since you can you easily switch to different hardware accelerators (cpu, gpu, tpu) as per the task.
>   * All you need is a good internet connection and you are all set.
> * Try to build TF from sources by changing CPU optimization flags.

Thanks!

**Comment by shoujomami** [comment]
and how do i use google colab?

**Comment by shoujomami** [comment]
there files data in my system i want TensorFlow switching it to motion and all files i need it is in my system , so what i should? should i uploode my whole folder in google drive so google colab can use the files/data based in python codes?

**Comment by dailylifesking** [comment]
Yes, you can transfer files easily with either 'Google Colab' or 'Kaggle'.
They use Cloud CPU. GPU. and TPU and not at your computer.
https://www.kaggle.com/
https://colab.research.google.com/

**Comment by shoujomami** [comment]
@dailylifesking 
Well my file is 5GB and higher plus it is have bat files must open it in my process to transform date to 3D pose motion  success . does kaggle/google cloab support bat files?

**Comment by shoujomami** [comment]
OK i found out that i can run it for my GPU thank you
