### ISSUE TITLE
Uninstal TensorFlow with all it's packages *Windows 10

### ISSUE THREAD

**Issue by MohaDou** [tensorflow/tensorflow#41220]
Hello, 
I uninstalled TensorFlow with `pip uninstall tensorflow` but there are still some packages that came with it when i installed it and now i have to uninstall them manually.
Is there anyway to uninstall them all together not by one? 

Thanks for any help in advanced.

**Comment by Saduf2019** [comment]
@MohaDou 
Can you please try the below commands and confirm (for python3)

python3 -m pip uninstall protobuf 
python3 -m pip uninstall tensorflow   
python3 -m pip uninstall tensorflow-gpu

Please refer to these links:
[link](https://github.com/tensorflow/tensorflow/issues/8785#issuecomment-289937786) [link1](https://stackoverflow.com/questions/11248073/what-is-the-easiest-way-to-remove-all-packages-installed-by-pip) [link2](https://github.com/tensorflow/tensorflow/issues/20416#issuecomment-401470771) [link3](https://www.roseindia.net/tensorflow/tensorflow2/uninstall-tensorflow-2.0-beta.shtml)

**Comment by MohaDou** [comment]
protobuf are one of tens, Also i didn't install TensorFlow with gpu so that wouldn't help too 

here are all the packages that came with the installation:
They came but don't want to go 
![Screenshot (37)](https://user-images.githubusercontent.com/45735118/87068624-c42f0280-c20d-11ea-9593-bd326af5d358.png)
