### ISSUE TITLE
rnn/translate: IOError: [Errno 2] No such file or directory: '/mnt/tf1/translate/giga-fren.release2.fr.gz'

### ISSUE THREAD

**Issue by loretoparisi** [tensorflow/tensorflow#4122]
### Environment info

Operating System:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:    14.04
Codename:   trusty
```

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
`NONE`
If installed from binary pip package, provide:
1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
   `$ python -c "import tensorflow; print(tensorflow.__version__)"
   0.10.0rc0`
### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

```
$ cd tensorflow/tensorflow/models/rnn/translate/
$ python translate.py --data_dir /mnt/tf1/translate
Preparing WMT data in /mnt/tf1/translate
Downloading http://www.statmt.org/wmt10/training-giga-fren.tar to /mnt/tf1/translate/training-giga-fren.tar
Succesfully downloaded training-giga-fren.tar 2595102720 bytes
Extracting tar file /mnt/tf1/translate/training-giga-fren.tar
Unpacking /mnt/tf1/translate/giga-fren.release2.fr.gz to /mnt/tf1/translate/giga-fren.release2.fr
Traceback (most recent call last):
  File "translate.py", line 290, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "translate.py", line 287, in main
    train()
  File "translate.py", line 147, in train
    FLAGS.data_dir, FLAGS.en_vocab_size, FLAGS.fr_vocab_size)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/rnn/translate/data_utils.py", line 265, in prepare_wmt_data
    train_path = get_wmt_enfr_train_set(data_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/rnn/translate/data_utils.py", line 83, in get_wmt_enfr_train_set
    gunzip_file(train_path + ".fr.gz", train_path + ".fr")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/rnn/translate/data_utils.py", line 68, in gunzip_file
    with gzip.open(gz_path, "rb") as gz_file:
  File "/usr/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/usr/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/mnt/tf1/translate/giga-fren.release2.fr.gz'
ubuntu@ip-10-169-182-86:~/tensorflow/tensorflow/tensorflow/models/rnn/translate$ ls /mnt/tf1/translate/training-giga-fren.tar 
```

```
$ ls -l /mnt/tf1/translate/training-giga-fren.tar 
-rw-rw-r-- 1 ubuntu ubuntu 2595102720 Aug 31 10:53 /mnt/tf1/translate/training-giga-fren.tar
```
### What other attempted solutions have you tried?

```
$ python translate.py --data_dir /mnt/tf1/translate
Preparing WMT data in /mnt/tf1/translate
Extracting tar file /mnt/tf1/translate/training-giga-fren.tar
...(same error)
```

```
$ ls -l /mnt/tf1/translate/
total 5073524
-rw-rw-r-- 1 ubuntu ubuntu 1214224978 Aug 30 19:55 giga-fren.release2.fixed.en.gz
-rw-rw-r-- 1 ubuntu ubuntu 1380871453 Aug 29 21:43 giga-fren.release2.fixed.fr.gz
-rw-rw-r-- 1 ubuntu ubuntu 2595102720 Aug 31 10:53 training-giga-fren.tar
```
### Logs or other output that would be helpful

(If logs are large, please upload as attachment or provide link).

**Comment by loretoparisi** [comment]
Same happens for `giga-fren.release2.en.gz`, so I have partially solved it by `symlink`

```shell
ubuntu@ip-10-169-182-86:/mnt/tf1/translate$ ls -l
total 9536168
lrwxrwxrwx 1 ubuntu ubuntu         30 Aug 31 15:17 giga-fren.release2.en.gz -> giga-fren.release2.fixed.en.gz
-rw-rw-r-- 1 ubuntu ubuntu 1214224978 Aug 30 19:55 giga-fren.release2.fixed.en.gz
-rw-rw-r-- 1 ubuntu ubuntu 1380871453 Aug 29 21:43 giga-fren.release2.fixed.fr.gz
-rw-rw-r-- 1 ubuntu ubuntu 4565271815 Aug 31 15:15 giga-fren.release2.fr
lrwxrwxrwx 1 ubuntu ubuntu         30 Aug 31 15:13 giga-fren.release2.fr.gz -> giga-fren.release2.fixed.fr.gz
-rw-rw-r-- 1 ubuntu ubuntu 2595102720 Aug 31 10:53 training-giga-fren.tar
```

**Comment by andrewt3000** [comment]
In tensorflow/models/rnn/translate/data_utils.py  line 76

-  train_path = os.path.join(directory, "giga-fren.release2")
+  train_path = os.path.join(directory, "giga-fren.release2.fixed")

**Comment by andrewt3000** [comment]
Ideal solution is that someone hosts the file that won't change it.  Not sure what else is different besides file name.

**Comment by andrewt3000** [comment]
I don't know if this error is related to the new files, but when I try to run it, with the new files hosted at statmt.org. The program fails when trying to train.

  reading data line 13900000
  reading data line 14000000
  reading data line 14100000
  reading data line 14200000
  reading data line 14300000
  reading data line 14400000
ubuntu@ip-10-147-46-5:~/tensorflow/tensorflow/models/rnn/translate$

**Comment by 0bserver07** [comment]
I don't think this is tensorflow problem.

the files inside training-giga-fren.tar have been renamed:
After extracting you get this error:
`IOError: [Errno 2] No such file or directory: ...`

ls into the folder of the data downloaded, in the default example it's `/tmp/` and what you will see is this:
```
giga-fren.release2.fixed.en.gz  
giga-fren.release2.fixed.fr.gz  
training-giga-fren.tar 
...
```

Next, try doing this:

`mv /tmp/giga-fren.release2.fixed.fr.gz /tmp/giga-fren.release2.fr.gz`

`mv /tmp/giga-fren.release2.fixed.en.gz /tmp/giga-fren.release2.en.gz`

Which will recorrect name of the files into (giga-fren.release2.en or giga-fren.release2.fr) rather than the one with fixed.

re turn the python translate and bam it works now 😄

**Comment by martinwicke** [comment]
pull requests are welcome!

**Comment by abhimanu** [comment]
In the tensorflow-0.10.0rc0 release, changing line 76 by adding '.fixed' in data_utils.py doesnt work. Instead creating the soft link for giga-fren.release2.fixed.en.gz  and giga-fren.release2.fixed.fr.gz  in the data_dir works as of today.

**Comment by ymakkapa** [comment]
Hello everyone,
I executed the code translate.py from sequence to sequence models tutorial of tensorflow 60 hours ago and still waiting for the output.
Can anyone tell me how much more time will it take to display the output
System specifications:
I installed Ubuntu 16.04 on VMware with a disk space of 100
![seqop](https://cloud.githubusercontent.com/assets/20130992/22991763/68078e36-f38b-11e6-84ed-f288cfa00087.PNG)
 GB and RAM of 1 GB.

**Comment by skye** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
