### ISSUE TITLE
Can anyone give a C_api example with multiple inputs and multiple outputs, like object detection?

### ISSUE THREAD

**Issue by xiaowenhe** [tensorflow/tensorflow#41227]
Hello,
        Can anyone give a C_api example with multiple inputs and multiple outputs , like object detection,with one input and three outputs( detection boxes, detection classes and detection scores)?
        With one input and one output, I can run without error. But for mutilple outputs, I do not know how to set 
[const TF_Output* outputs, TF_Tensor** output_values] the two parameter in TF_SessionRun(***) function.
![image](https://user-images.githubusercontent.com/28335784/87021919-5c29ed80-c208-11ea-8756-6fd5f39f9163.png)

Thank you !

**Comment by amahendrakar** [comment]
@xiaowenhe,
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!
