### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow' on windows 8.1

### ISSUE THREAD

**Issue by Nazanin-87** [tensorflow/tensorflow#41238]
Tensorflow is successfully installed on my laptop.
`Name: tensorflow
Version: 2.2.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: c:\users\my name\anaconda3\lib\site-packages
Requires: protobuf, astunparse, h5py, opt-einsum, wrapt, grpcio, termcolor, gast, tensorflow-estimator, scipy, six, tensorboard, wheel, google-pasta, numpy, keras-preprocessing, absl-py
Required-by:`

The environment is Windows 8.1, python 3.7.1, pip 20.1.1.

When I run this test file
`import tensorflow as tf
hello = tf.constant("hello TensorFlow!")
sess=tf.Session()
print(sess.run(hello))`

, I get the following error message:
`ModuleNotFoundError: No module named 'tensorflow'.`
How can I resolve this problem?

**Comment by Saduf2019** [comment]
@Nazanin-87 
Can you please verify:
'''import tensorflow
tf.__version__'''
and please share the steps followed for installation, steps before you faced this error..

Please go through [this link for requirements](https://www.tensorflow.org/install/pip)

Below issues should help you resolve:
#27935 #32147 [link](https://github.com/tensorflow/tensorflow/issues/9473#issuecomment-297613687)  [link](https://stackoverflow.com/questions/46568913/tensorflow-import-error-no-module-named-tensorflow) [link1](https://www.heatonresearch.com/2019/09/03/tf-no-module-jupyter.html) [link2](https://stackoverflow.com/questions/42244198/importerror-no-module-named-tensorflow) [link3](https://geekcops.com/tutorials/modulenotfounderror-no-module-named-tensorflow-solved/) [link4](https://github.com/tensorflow/tensorflow/issues/40664#issuecomment-647453546) [link5](https://github.com/tensorflow/tensorflow/issues/10474#issuecomment-306668929)

**Comment by Nazanin-87** [comment]
Thanks for your response.
Actually, I can't import TensorFlow.
For showing the version of it, I used the following command in cmd
" pip show TensorFlow "
That shows its version as follows
" Name: TensorFlow
Version: 2.2.0 "

For the installation of TensorFlow, firstly, I updated python and pip. Then I used " pip install TensorFlow".

**Comment by Nazanin-87** [comment]
Tensorflow is installed on Anaconda folder "C:\Users\....\Anaconda3\Lib\site-packages", but I think I should install that on " C:\Users\.....\venv\Lib\site-packages". How can I do this?

**Comment by Saduf2019** [comment]
@Nazanin-87 
This issue is more suitable on [Continuum Anaconda repo](https://github.com/ContinuumIO/anaconda-issues/issues) since its related to TF installation with Anaconda.
Please post it on [Continuum Anaconda](https://github.com/ContinuumIO/anaconda-issues/issues).
Thanks!
