### ISSUE TITLE
TF2 add a reduce or aggregation key to tf.scatter_nd

### ISSUE THREAD

**Issue by Wirg** [tensorflow/tensorflow#41234]
**System information**
- TensorFlow version (you are using): `2.2.0`
- Are you willing to contribute it (Yes/No): maybe

**Describe the feature and the current behavior/state.**
`tf.scatter_nd` currently sum the updates having the same indices.

I would like to be able to provide a different tensor reduce or aggregation function.
Keeping the current default to a sum :
```python
import tensorflow as tf

indices = tf.constant([[0], [0]], dtype=tf.int32)
updates = tf.constant([[0, 1], [1, 2]])
tf.assert_equal(
    tf.scatter_nd(indices, updates, (3, 2)), # default
    tf.scatter_nd(indices, updates, (3, 2), reduce=lambda current, new: current + new),
)
tf.assert_equal(
    tf.scatter_nd(indices, updates, (3, 2)), # default
    tf.scatter_nd(indices, updates, (3, 2), agg=lambda batched_update: tf.reduce_sum(batched_update, axis=0)
)
```

**Will this change the current api? How?**
It will add new key to `scatter_nd` and `scatter_nd_update`

**Who will benefit with this feature?**
People which will use `tf.scatter_nd`.

I think it will be especially useful to implement some SotA detection algorithms.
For example, for yolo boxes `[N_boxes, (x, y, h, w, o, c1, c2, ..., cn)]` are scattered in a kind of sparse Tensor to mimic the network output `[batch_size, y_grid_index, x_grid_index, anchor_n, (x, y, h, w, o, c1, c2, ..., cn)]`.
In the current situation, if 2 objects / boxes are similar (same anchor) and positionned nearby, they will hit the same position on the output grid and be summed.
The sum does not make any sense in that case :
- x, y, h, w are ~ summed. This signifies moving the boxe after positioning it : first or a mean will be better
- o is summed. It should stay 1 : the value is a bolean indicating if there is one element or not. First or reduce_any will be better.
- c1...cn are similar to o.
This happens for overlapping elements and may greatly improve the handling of this situation.

**Any Other info.**

Referenced here : https://github.com/tensorflow/tensorflow/issues/32235, without a need.
`tf.scatter_nd_update` is probably impacted

**Comment by rmothukuru** [comment]
@Wirg,
Sorry for the delayed response. Can you please let us know if [tf.tensor_scatter_nd_add](https://www.tensorflow.org/api_docs/python/tf/tensor_scatter_nd_add) is what you are looking for? Thanks!
