### ISSUE TITLE
missing comma in script

### ISSUE THREAD

**Issue by seyedrezamirkhani** [tensorflow/tensorflow#41231]
## URL(s) with the issue:

https://www.tensorflow.org/tfx/guide/build_tfx_pipeline#build_a_custom_pipeline

## Description of issue (what needs changing):

A comma needs to be added to the script used in step 3 at the end of line: data_path=DATA_PATH

### Submit a pull request?
YES

https://github.com/seyedrezamirkhani/tfx/pull/1

**Comment by ravikyram** [comment]
@seyedrezamirkhani 

This issue is more suitable for TensorFlow TFX repo. Please post it on TFX repo from [here.](https://github.com/tensorflow/tfx/issues) Thanks!

**Comment by seyedrezamirkhani** [comment]
@ravikyram 

Thanks for your guidance, I've created the issue with the TFX repo and will close this issue.

**Comment by seyedrezamirkhani** [comment]
Moved issue to https://github.com/tensorflow/tfx/issues/2121
