### ISSUE TITLE
TensorFlow 2.2, No progress of distributed training for a TensorFlow example code on GPU clusters

### ISSUE THREAD

**Issue by umusa** [tensorflow/tensorflow#41247]
I am running the example code at 
     https://www.tensorflow.org/tutorials/distribute/multi_worker_with_estimator

on GPU clusters (1 master 2 workers) from databricks py3 notebook. 

      Tensorflow version : 2.2.0
      Num XLA_GPUs Available:  1
      Num GPUs Available:  1
      [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU'), PhysicalDevice(name='/physical_device:XLA_GPU:0', device_type='XLA_GPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

But, this training makes no progress:

        tf.estimator.train_and_evaluate(
        classifier,
       train_spec=tf.estimator.TrainSpec(input_fn=input_fn),
       eval_spec=tf.estimator.EvalSpec(input_fn=input_fn)

The log : 

     Instructions for updating:
     Use the iterator's `initializer` property instead.
     INFO:tensorflow:Graph was finalized.
     INFO:tensorflow:Graph was finalized.

From GPU cluster Ganglia: all GPUs and CPUs are idle.

I have tried all comms:
 
     communication=tf.distribute.experimental.CollectiveCommunication.NCCL/RING/AUTO

 but the same thing.

Could anybody help me about this ?

**Comment by Saduf2019** [comment]
@umusa 
Please share xprof traces for performance issue, using [this link](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras#profiler_service)
