### ISSUE TITLE
Anaconda Jupyter Notebook - Tensorflow ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by JimmyJ2020** [tensorflow/tensorflow#41241]
Hello Team, 

Please see my issue below. I'm working in Jupyter Notebooks launched within Anaconda to work on a computer vision project. 

Would it be helpful for me to share all the packages I have in my particular environment just in case there's a conflict that's not immediately obvious? I have 137 in total. I'm a casual user.

![image](https://user-images.githubusercontent.com/44557668/87065048-266c1100-c1d6-11ea-941c-7f1295275cd2.png)
![image](https://user-images.githubusercontent.com/44557668/87065138-44397600-c1d6-11ea-9a1c-e9dd47aab698.png)
![image](https://user-images.githubusercontent.com/44557668/87065204-5b786380-c1d6-11ea-8d2b-5be360e9d448.png)
![image](https://user-images.githubusercontent.com/44557668/87065294-79de5f00-c1d6-11ea-8169-98f302e3b0b4.png)
![image](https://user-images.githubusercontent.com/44557668/87065335-882c7b00-c1d6-11ea-8c2d-6eb701e45667.png)
![image](https://user-images.githubusercontent.com/44557668/87065422-9da1a500-c1d6-11ea-8fb6-e367db18bb5b.png)
![image](https://user-images.githubusercontent.com/44557668/87065483-b0b47500-c1d6-11ea-95a1-7a4430730d88.png)
![image](https://user-images.githubusercontent.com/44557668/87065521-bdd16400-c1d6-11ea-9773-ed034cbea9ba.png)

### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: None
-   **TensorFlow installed from (source or binary)**: pip install
-   **TensorFlow version (use command below)**: 2.2.0
-   **Python version**: 3.7.7
-   **Bazel version (if compiling from source)**: Not installed
-   **GCC/Compiler version (if compiling from source)**: Unsure
-   **CUDA/cuDNN version**: unsure
-   **GPU model and memory**: Intel(R) HD Graphics 520
-   **Exact command to reproduce**: import tensorflow as tf

### Describe the problem
I cannot import tensorflow in my jupyter notebook. I have a specific environment created to within Anaconda Navigator to handle computer vision packages

### Source code / logs

>%pylab notebook
>import cv2
>import tensorflow as tf
>import pytesseract as ptess

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\anaconda3\envs\Tigers Football Image Processin\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59 

~\anaconda3\envs\Tigers Football Image Processin\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

~\anaconda3\envs\Tigers Football Image Processin\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

~\anaconda3\envs\Tigers Football Image Processin\lib\imp.py in load_module(name, file, filename, details)
    241         else:
--> 242             return load_dynamic(name, filename, file)
    243     elif type_ == PKG_DIRECTORY:

~\anaconda3\envs\Tigers Football Image Processin\lib\imp.py in load_dynamic(name, path, file)
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343 

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-5-fe1814e2e27b> in <module>
      1 import cv2
----> 2 import tensorflow as tf
      3 import dlib
      4 import pytesseract as ptess

~\anaconda3\envs\Tigers Football Image Processin\lib\site-packages\tensorflow\__init__.py in <module>
     39 import sys as _sys
     40 
---> 41 from tensorflow.python.tools import module_util as _module_util
     42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
     43 

~\anaconda3\envs\Tigers Football Image Processin\lib\site-packages\tensorflow\python\__init__.py in <module>
     48 import numpy as np
     49 
---> 50 from tensorflow.python import pywrap_tensorflow
     51 
     52 # Protocol buffers

~\anaconda3\envs\Tigers Football Image Processin\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     67 for some common reasons and solutions.  Include the entire stack trace
     68 above this error message when asking for help.""" % traceback.format_exc()
---> 69   raise ImportError(msg)
     70 
     71 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\Users\jimmy\anaconda3\envs\Tigers Football Image Processin\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\jimmy\anaconda3\envs\Tigers Football Image Processin\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\jimmy\anaconda3\envs\Tigers Football Image Processin\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\jimmy\anaconda3\envs\Tigers Football Image Processin\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\jimmy\anaconda3\envs\Tigers Football Image Processin\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Thank you, 

Jimmy

**Comment by JimmyJ2020** [comment]
I'm needing to download CUDA 10.1... Please see the below and let me know which installer type I should go with before downloading?

![image](https://user-images.githubusercontent.com/44557668/87066532-59170900-c1d8-11ea-8643-483e017d0125.png)

**Comment by Saduf2019** [comment]
@JimmyJ2020 
This issue is more suitable on Continuum [Anaconda repo](https://github.com/ContinuumIO/anaconda-issues/issues) since its related to TF installation with Anaconda.
Please post it on [Continuum Anaconda](https://github.com/ContinuumIO/anaconda-issues/issues).
Thanks!

I did come across few issues you could refer to them:
#36986 #35749 [link](https://intellipaat.com/community/49940/error-occured-while-import-tensorflow-in-jupyter-notebook) [link1](https://stackoverflow.com/questions/56311402/dll-error-when-importing-tensorflow-in-anaconda-environment) [link2](https://datascience.stackexchange.com/questions/45726/importerror-dll-load-failed-the-specified-module-could-not-be-found)  hope these help.
