### ISSUE TITLE
Difference between result of code and description of guide

### ISSUE THREAD

**Issue by jianrui1995** [tensorflow/tensorflow#41245]
## URL(s) with the issue:
https://www.tensorflow.org/guide/keras/train_and_evaluate#passing_data_to_multi-input_multi-output_models

### Clear description
When I debug my code according to the guide("Passing data to multi-input, multi-output models,Training & evaluation with the built-in methods"), I found it is difference between result of code and description of guide.
The guide told us that we could choose not to compute a loss for certain outputs, if these outputs meant for prediction but not for training.
like follows:
```
model.compile(
    optimizer=keras.optimizers.RMSprop(1e-3),
    loss=[None, keras.losses.CategoricalCrossentropy()],
) 
```
But, in Linux OS and version of tensorflow is 2.1.0, "None" can not be used to there, and  pull a error.
like：
```
model.compile(
        optimizer=op,
        loss=[None,LossForTask(),LossForLMP()],
        metrics=[[F1()],[],[]]
        # loss_weights=[1,1,0]
    )
```
error：
ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), for inputs ['output_2', 'output_3'] but instead got the following list of 3 arrays

I use same code in win10 OS，it is fine without any error。

**Comment by amahendrakar** [comment]
> I use same code in win10 OS，it is fine without any error。

@jianrui1995,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!
