### ISSUE TITLE
Why my Xception model is very very slow on TPU compared to large models like efficientnet-b6 or b7?

### ISSUE THREAD

**Issue by mobassir94** [tensorflow/tensorflow#41243]
i am having this while trying Xception model on tpu :

WARNING: AutoGraph could not transform <function at 0x7f1e447a1950> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, export AUTOGRAPH_VERBOSITY=10) and attach the full output.
Cause: Unable to locate the source code of <function at 0x7f1e447a1950>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert

and also it is taking a lot of time
for 2 epochs it takes 59 minutes on TPU with Xception model
but same code where if i change Xception with efficientnet-b6 or b7 then i can run 13 epochs which will finish within 1 hour!!

here is my code : https://www.kaggle.com/mobassir/in-depth-melanoma-and-modeling?scriptVersionId=38354798

and here you can see : https://www.kaggle.com/agentauers/incredible-tpus-finetune-effnetb0-b6-at-once

same code with efficientnet-b6 or b7 is extremely fast compared to my simple Xception model
please help?

**Comment by ravikyram** [comment]
@mobassir94 

Request you to fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).It helps us in reproducing the issue.Thanks!
