### ISSUE TITLE
Support for DepthwiseConv2D with output channel less than input channel

### ISSUE THREAD

**Issue by ek9852** [tensorflow/tensorflow#41246]
**System information**
- TensorFlow version (you are using):2.2 and nightly
- Are you willing to contribute it (Yes/No):No

**Describe the feature and the current behavior/state.**
DepthwiseConv2D use depth_multiplier (int), which makes number of output channel always greater than or  equal to number of input channel. But for unet use case, we need to reduce the number of output channels after doing upsampling using depthwise convolution. There is currently no way to support that in tensorflow. pytorch is much more dynamic since it supports grouping in convolution2D which tensorflow does not support and use a delicate  DepthwiseConv2D API.

**Comment by ravikyram** [comment]
@ek9852 

Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!

**Comment by ek9852** [comment]
Sure,  as mentioned in my previous email. Such as unet, u  need to reduce
the number of channel after upsampling. And would like to do that in
depthwise convolution. But in tensorflow there is no way to have the output
channels less than input channels. Since it is a delicate api.

**Comment by tanzhenyu** [comment]
Makes sense. Seems important to fix

**Comment by ek9852** [comment]
I am not sure what is the best approach.
I believe the right approach is to bring grouping to Conv2D and depreciate
depthwiseconv2d api.
(depthwise convolution 2d is basically conv2d with grouping number  = input
channels , then do  a 1x1 conv2D.)
Tensorflow is the only AI engine I encountered that does not support
grouping in conv2d and introduce a feature limited depthwiseconv2d..

BTW if tensorflow runs on nvidia gpu, it does support grouping in conv2d
with some hacks , but not in its cpu implementation.

**Comment by sachinprasadhs** [comment]
`Conv2D` does support grouping with `groups` parameter, you can find more details about the parameter [here](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2D#arguments).
