### ISSUE TITLE
Error building basic AOT library

### ISSUE THREAD

**Issue by adanlopeza** [tensorflow/tensorflow#41254]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **No**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Debian GNU/Linux rodete**
- TensorFlow installed from (source or binary): **source**
- TensorFlow version (use command below): **v2.2.0-rc4-8-g2b96f3662b 2.2.0**
- Python version: **Python3**
- Bazel version (if compiling from source): **3.1.0**

**Background**

I'm following [this](https://www.tensorflow.org/xla/tfcompile) tutorial. I can't build the sample library. I've already read [this](https://github.com/tensorflow/tensorflow/issues/13482) issue, which seems similar to mine, but it didn't help.

**Steps followed**

1. Clone tensorflow and go to aot's directory

`git clone https://github.com/tensorflow/tensorflow.git`
`cd tensorflow/tensorflow/compiler/aot`

2. Run scipt to generate protobuf

`python3 tests/make_test_graphs.py --out_dir=.`

3. Run test_graph_tfmatmul rule.

`bazel build :test_graph_tfmatmul`

**Describe the current behavior**

Step 3 errors out with the following message:

ERROR: /usr/local/google/home/adanlopez/tfcompile/tensorflow/tensorflow/python/BUILD:873:1: undeclared inclusion(s) in rule '//tensorflow/python:_pywrap_checkpoint_reader.so':
this rule is missing dependency declarations for the following files included by 'tensorflow/python/util/py_checkpoint_reader_wrapper.cc':
  'bazel-out/host/bin/external/local_config_python/python_include/numpy/arrayobject.h'
  'bazel-out/host/bin/external/local_config_python/python_include/numpy/ndarrayobject.h'
  'bazel-out/host/bin/external/local_config_python/python_include/numpy/ndarraytypes.h'
  'bazel-out/host/bin/external/local_config_python/python_include/numpy/npy_common.h'
  'bazel-out/host/bin/external/local_config_python/python_include/numpy/numpyconfig.h'
  'bazel-out/host/bin/external/local_config_python/python_include/numpy/_numpyconfig.h'
  'bazel-out/host/bin/external/local_config_python/python_include/numpy/npy_endian.h'
  'bazel-out/host/bin/external/local_config_python/python_include/numpy/npy_cpu.h'
  'bazel-out/host/bin/external/local_config_python/python_include/numpy/utils.h'
  'bazel-out/host/bin/external/local_config_python/python_include/numpy/_neighborhood_iterator_imp.h'
  'bazel-out/host/bin/external/local_config_python/python_include/numpy/__multiarray_api.h'
  'bazel-out/host/bin/external/local_config_python/python_include/numpy/npy_interrupt.h'
  'bazel-out/host/bin/external/local_config_python/python_include/numpy/ufuncobject.h'
  'bazel-out/host/bin/external/local_config_python/python_include/numpy/npy_math.h'
  'bazel-out/host/bin/external/local_config_python/python_include/numpy/npy_common.h'
  'bazel-out/host/bin/external/local_config_python/python_include/numpy/arrayobject.h'
  'bazel-out/host/bin/external/local_config_python/python_include/numpy/__ufunc_api.h'
Target //tensorflow/compiler/aot/tests:test_graph_tfmatmul failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 135.764s, Critical Path: 47.52s
INFO: 336 processes: 336 local.
FAILED: Build did NOT complete successfully

**Describe the expected behavior**

Step 3 should not error out.

**Comment by gunan** [comment]
This happens when you do not have numpy installed for the python distribution you are using to build TF.
Please make sure to read the full guide here before building from sources:
https://www.tensorflow.org/install/source
