### ISSUE TITLE
 do tensorflow support lmdb or hdf5 data?

### ISSUE THREAD

**Issue by JulyUp** [tensorflow/tensorflow#4125]
Now I have lmdb and hdf5 data for image classification. And I want to use tensorflow to train some convnets. So do tensorflow support lmdb or hdf5 data?

**Comment by wangg12** [comment]
@JulyUp tensorflow/examples/skflow/hdf5_classification.py

**Comment by JulyUp** [comment]
@wangg12  Thank you very much. It is useful.
