### ISSUE TITLE
Configuring `TF_CONFIG` in practice + a small "bug" in the Multi-worker training with Keras tutorial

### ISSUE THREAD

**Issue by 8bitmp3** [tensorflow/tensorflow#41257]
Hey @lamberta and team 👋

A couple of things here related to the **[Multi-worker training with Keras](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras)** tutorial (with `tf.distribute.experimental.MultiWorkerMirroredStrategy()`):

### 1. Configuring the `TF_CONFIG` environment variable for multi-worker training in practice

**URL:** https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras#multi-worker_configuration

**Description:**
There is an important section dedicated to [Multi-worker Configuration](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras#multi-worker_configuration), which states that outside of the free Colab environment:

> In practice, users would create multiple workers on external IP addresses/ports, and set `TF_CONFIG` on each worker appropriately.

The current example snippet shows that in the `task` component of `TF_CONFIG`, the `index` value of the worker is set to `0` (`task` is different on each worker):

```python
# Import necessary libraries (not currently included in the tutorial)
import json
import os

os.environ['TF_CONFIG'] = json.dumps({
    'cluster': {
        'worker': ["localhost:12345", "localhost:23456"]
    },
    'task': {'type': 'worker', 'index': 0}
})
```

However, this may create some confusion, as demonstrated in https://github.com/tensorflow/tensorflow/issues/39922. The user tried setting the `TF_CONFIG` environment variable (with `index: 0`), as shown in the tutorial, but that wouldn't let the rest of the script proceed with execution. If the user runs the experiment with `index: 1`, all is OK.

As mentioned in https://github.com/tensorflow/tensorflow/issues/39922, you should be following this TensorFlow distributed training [guide](https://www.tensorflow.org/guide/distributed_training#setting_up_tf_config_environment_variable), where it says:

> One example of TF_CONFIG is:
> 
> ```python
> os.environ["TF_CONFIG"] = json.dumps({
>     "cluster": {
>         "worker": ["host1:port", "host2:port", "host3:port"],
>         "ps": ["host4:port", "host5:port"]
>     },
>    "task": {"type": "worker", "index": 1}
> })
> ```

**Proposed solution:** 

1) Borrow the sample code from the [Setting up TF_CONFIG environment variable](https://www.tensorflow.org/guide/distributed_training#setting_up_tf_config_environment_variable
) section from the [Distributed training with TensorFlow](https://www.tensorflow.org/guide/distributed_training) guide into; and
2) Add this code sample to the [Multi-worker Configuration](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras#multi-worker_configuration) section of the [Multi-worker training with Keras](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras) tutorial.

For example:
> In this example, we set the task `type` to `"worker"` and the task `index` to `0`. This means the machine that has such setting is the first worker...
>...
> [ORIGINAL CODE SNIPPET]
>...
> In your use case, you may also set the task `type` to `"worker"` and the task `index` to `1` instead of `0`.
> 
> ```python
> # Import necessary libraries (not currently included in the tutorial)
> import json
> import os
> os.environ["TF_CONFIG"] = json.dumps({
>     "cluster": {
>         "worker": ["host1:port", "host2:port", "host3:port"],
>         "ps": ["host4:port", "host5:port"]
>     },
>    "task": {"type": "worker", "index": 1}
> })
> ```

### 2. A small "bug" in the Dataset sharding and batch size section

**URL:** https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras#dataset_sharding_and_batch_size

**Description:** The following sentence in **Dataset sharding and batch size** looks a bit odd:

> If you prefer manual sharding for your training, automatic sharding can be turned off via `tf.data.experimental.DistributeOptions` api. Concretely,

(this is followed by a code snippet)

### Submit a pull request?

Yes for (1), once this has been clarified.
Regarding (2), I think it's up to the team.

**Comment by guptapriya** [comment]
Hi, apologies for the late response.

#1 Re: TF_CONFIG - I am not sure how the 2 examples are different. One of them uses example of TF_CONFIG from task 0 and the other one uses task id 1. One is not more correct than the other. If there are 2 workers, the user needs to setup one task with id=0 and one with id=1. What we can probably change in the tutorial is clarify that the task index should be different on both workers. But I don't think the [current explanation in the guide](https://www.tensorflow.org/guide/distributed_training#setting_up_tf_config_environment_variable) is any better than the [current one in the multi worker tutorial](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras#choose_the_right_strategy)


#2 Sorry, I am not quite sure what "bug" are you referring to. Could you elaborate?

**Comment by 8bitmp3** [comment]
> Hi, apologies for the late response.

No worries @guptapriya 🙂

> What we can probably change in the tutorial is clarify that the task index should be different on both workers. But I don't think the [current explanation in the guide](https://www.tensorflow.org/guide/distributed_training#setting_up_tf_config_environment_variable) is any better than the [current one in the multi worker tutorial](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras#choose_the_right_strategy)

It's likely that the Issue another user raised was due to the confusion over the `'index'` paramter (set to `0` by default in the original guide). 

Perhaps, we can mention that one you (the user) can use the value or `1` and above - WDYT?

For example:

> You can also set the `task` `'index'` to `1` instead of `0` [use case explanation].

or something along those lines.

> #2 Sorry, I am not quite sure what "bug" are you referring to. Could you elaborate?

Pardon me. The last sentence starts with "Concretely" and it's followed by a comma. Maybe, we could use "For example:" (with a colon)?

> If you prefer manual sharding for your training, automatic sharding can be turned off via `tf.data.experimental.DistributeOptions` API. For example:
>
```python
options = tf.data.Options()
options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.OFF
dataset_no_auto_shard = multi_worker_dataset.with_options(options)
```

I've also capitalized "API" in "`tf.data.experimental.DistributeOptions` API".

Let me know what you think. Thank you!

**Comment by guptapriya** [comment]
> Perhaps, we can mention that one you (the user) can use the value or `1` and above - WDYT?
> 
> For example:
> 
> > You can also set the `task` `'index'` to `1` instead of `0` [use case explanation].
> 
> or something along those lines.

I am still not sure why 1 is better than 0. I think the core issue that they should be different on each worker. So if you have 2 workers, it should be 0 and 1. If you have 3 workers, it should be 0, 1, and 2. Is that what you're saying too? 

> 
> > #2 Sorry, I am not quite sure what "bug" are you referring to. Could you elaborate?
> 
> Pardon me. The last sentence starts with "Concretely" and it's followed by a comma. Maybe, we could use "For example:" (with a colon)?
> 
> > If you prefer manual sharding for your training, automatic sharding can be turned off via `tf.data.experimental.DistributeOptions` API. For example:
> 
> ```python
> options = tf.data.Options()
> options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.OFF
> dataset_no_auto_shard = multi_worker_dataset.with_options(options)
> ```
> 
> I've also capitalized "API" in "`tf.data.experimental.DistributeOptions` API".
> 
> Let me know what you think. Thank you!

Sure, those changes sound fine to me 👍

**Comment by 8bitmp3** [comment]
> I think the core issue that they should be different on each worker. So if you have 2 workers, it should be 0 and 1. If you have 3 workers, it should be 0, 1, and 2. Is that what you're saying too?

@guptapriya I really like this idea - it's simple and may help with future potential issues, such as https://github.com/tensorflow/tensorflow/issues/39922. 

What do you think about adding this one sentence at the end (I've included two existing paragraphs for context):

```diff
In this example, we set the task `type` to `"worker"` and the task `index` to `0`. 
This means the machine that has such setting is the first worker, which will 
be appointed as the chief worker and do more work than other workers. Note 
that other machines will need to have `TF_CONFIG` environment variable set as well, 
and it should have the same `cluster` dict, but different task `type` or task `index` 
depending on what the roles of those machines are.

For illustration purposes, this tutorial shows how one may set a `TF_CONFIG` with 2 
workers on `localhost`. In practice, users would create multiple workers on external 
IP addresses/ports, and set `TF_CONFIG` on each worker appropriately.
+ So, for example, if you have 2 workers, you should set the task `index` to `0` and `1` separately.
```

Thank you!

**Comment by guptapriya** [comment]
@8bitmp3 that SGTM, feel free to send a PR to update the tutorial (maybe in both places). thanks!
