### ISSUE TITLE
Unknown call to ResizeNearestNeighbor?

### ISSUE THREAD

**Issue by abuchele** [tensorflow/tensorflow#41250]
I am trying to convert a model to tflite format and run inferencing. I am aware that the ResizeNearestNeighbor is supported on tf_nightly, but unfortunately I am not able to use tf_nightly for my application. I am trying to rework the model so as to not call ResizeNearestNeighbor, but I am not sure where it is being called. I am not using image.resize anywhere. How can I find where the model is calling this operation?

Thank you!

**Comment by abattery** [comment]
You can use different TF version on creating a TF model and converting the TFLite and running the inference.

For example,
- Export your model via a saved model with your TF version.
- Convert the saved model with tf-nightly and use tf-nightly based inference program.

**Comment by ravikyram** [comment]
@abuchele 

Any update on this issue please. Thanks!

**Comment by abuchele** [comment]
The ResizeNearestNeighbor call ended up being by Keras.layers.UpSampling2D, so as a temporary workaround I'm just not using that, although that's not ideal. 

The solution above doesn't fix the issue, as I can use tf-nightly for converting the model, but I cannot use it for running inference.

**Comment by abattery** [comment]
@abuchele Could you share why the converted model can not be used for inference? I think you can run inference based on the same TF version library.
