### ISSUE TITLE
ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [<tf.Tensor 'cond_8/Identity_1:0' shape=(?, 25) dtype=float32>]...

### ISSUE THREAD

**Issue by Dabuk** [tensorflow/tensorflow#41268]
I have a tf.keras model with one encoder and two decoders. I'm attempting to train the model with tf dataset generated from 

tf.data.Dataset.from_generator

Model -
`
# encoder
inp = tf.keras.Input(shape=(None, 25))
x = tf.keras.layers.Dense(64)(inp)
enc = tf.keras.layers.Dense(64)(x)

# decoder1
latentInputs1 = tf.keras.Input(shape=(64,))
 x1 = tf.keras.layers.Dense(64)(latentInputs1)
 x1 = tf.keras.layers.Dense(64)(x1)
dec1 = tf.keras.layers.Dense(25, activation='softmax', name='dec1')(x1)

# decoder2
latentInputs2 = tf.keras.Input(shape=(64,))
x1 = tf.keras.layers.Dense(64)(x1)
x1 = tf.keras.layers.Dense(64)(x1)
dec2 = tf.keras.layers.Dense(5, activation='softmax', name='dec2')(x1)

#model
encoder = tf.keras.Model(inputs = inp, outputs = enc)
decode1 = tf.keras.Model(inputs = latentInputs, outputs = dec, name='dec1')
decode2 = tf.keras.Model(inputs = latentInputs1, outputs = classif_dec, name='dec2')

model = tf.keras.Model( inputs = inp, outputs = [decode1(encoder(inp)), decode2(encoder(inp))] )

#dataset definition
train_data = tf.data.Dataset.from_generator(
       lambda: generator_fn(file_path),
       output_types=(tf.float32, tf.float32, f.float32}),
       output_shapes=(tf.TensorShape([None]), tf.TensorShape([None]), tf.TensorShape([None])})
       )

#compile
losses = {
                    "dec1": "mean_absolute_error",
                    "dec2": "mean_absolute_error",
                }

model.compile(optimizer=keras.optimizers.Adam(learning_rate=experiment_params['learning_rate'])
                          loss=losses,
                          metrics=[keras.metrics.MeanSquaredError()]
                          )

model.fit(train_data, epochs=data_params.epochs,
                        steps_per_epoch=train_steps,
                        callbacks=callbacks,)
`

should I make changes in the dataset shape ? what's the course of action ?

**Comment by amahendrakar** [comment]
@Dabuk,
On running the given code, I am facing an error stating `NameError: name 'latentInputs' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/aa9bf620bb9f2104d56b8764728a063d/41268.ipynb).

In order to reproduce the issue reported here, could you please provide the complete code, the dataset and the TensorFlow version you are using. Thanks!

**Comment by amahendrakar** [comment]
Also, please take a look at [this comment](https://stackoverflow.com/a/56806002) from a similar StackOverflow issue and let us know if it helps. Thanks!

**Comment by Dabuk** [comment]
Will add the code update,

But can I know if the dataset shape can be maitained somehow when I use a map ?

For example:

generaor_fn(file_path):
     datain, dataout1, dataout2 = load(file_path)
     yield datain, [dataout1, dataout2]

train_data = tf.data.Dataset.from_generator(
lambda: generator_fn(file_path),
output_types=(tf.float32, tf.float32, f.float32}),
output_shapes=(tf.TensorShape([None]), tf.TensorShape([None]), tf.TensorShape([None])})
)

does this work ?
train_data = train_data.map( lambda inp1, inp2: inp1, [ map_fn(inp2[0]), map_fn(inp2[1]) ] )

**Comment by amahendrakar** [comment]
> Will add the code update,

@Dabuk,
Any updates regarding the complete reproducible code? Thanks!

**Comment by Dabuk** [comment]
Hello, sorry for the delay. I solved the error with the links and some lucky random guesses
Had to modify outputs of the data generator

tf.data.Dataset.from_generator(
                    lambda: generator_fn(file_path, dataset_params, labelout),
                    output_types=(tf.float32, {"dec1":tf.float32, "dec2":tf.float32}),
                    )

**Comment by amahendrakar** [comment]
@Dabuk,
Thank you for the update. Marking this issue as close, as it is resolved. Thanks!
