### ISSUE TITLE
Training with Coco dataset 2017 for a pretrained model

### ISSUE THREAD

**Issue by nyanmn** [tensorflow/tensorflow#41266]
I am training with Coco dataset to have a pretrained model for a new network architecture.
2017 Coco dataset was used. dataset_tools/create_coco_tf_record.py was used to create tfrecords.

I have error at 
```
object_detection_evaluation.py", line 285, in add_single_ground_truth_image_info
    raise ValueError('Image with id {} already added.'.format(image_id))
ValueError: Image with id b'559842' already added.
```
Then comment out the lines 285 and 286 in `object_detection_evaluation.py` and can continue the evaluation.
```
if image_id in self._image_ids:
      raise ValueError('Image with id {} already added.'.format(image_id))
```

The eval results are
```
I0710 15:06:50.361298 140470232598272 eval_util.py:82] Losses/Loss/BoxClassifierLoss/classification_loss: 0.426311
I0710 15:06:50.361555 140470232598272 eval_util.py:82] Losses/Loss/BoxClassifierLoss/localization_loss: 0.273654
I0710 15:06:50.361709 140470232598272 eval_util.py:82] Losses/Loss/RPNLoss/localization_loss: 0.571312
I0710 15:06:50.361852 140470232598272 eval_util.py:82] Losses/Loss/RPNLoss/objectness_loss: 0.382609
```
Is that result acceptable?

**Comment by ravikyram** [comment]
@nyanmn 

I think this issue belongs to models repo. You can raise an issue in models repo from [here](https://github.com/tensorflow/models/issues/new/choose).Thanks!

**Comment by nyanmn** [comment]
I have already raised at Issue: [Research Model] Feature Request. Not sure that is the right place to raise.

**Comment by ravikyram** [comment]
@nyanmn 

This issue belongs to models repo.Please, close the issue here and  track the issue in models repo from [here](https://github.com/tensorflow/models/issues/8824) .Thanks!
