### ISSUE TITLE
pip install error : unable to install tensorflow on py 3.7 64 bit version

### ISSUE THREAD

**Issue by saifiShaddil** [tensorflow/tensorflow#41262]
unable to install tensorflow on python 3.7  64 bit version

 (tensor) C:\Users\Saifi's\Desktop\tensor_env>pip install tensorflow
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow

even tried python 3.8 still same issue.
 pip version pip 20.1.1 (installed)

**Comment by Saduf2019** [comment]
@saifiShaddil 

1. Please confirm if you have refered to complete installation [steps here](https://www.tensorflow.org/install/pip#windows)
2. TensorFlow 2.0 does not support Python 3.8. Instead could you please try installing TensorFlow v2.2 or nightly using the following

command:
pip install tensorflow==2.2
or
pip install -upgrade tensorflow==2.2 and let us know if it works.

Thanks!


Can you please refer to below issues with similar error:
#37457 #38750 #39621 #36380  #33374 #34302 #39130  [link](https://github.com/tensorflow/tensorflow/issues/29704#issuecomment-583732543) [link1](https://github.com/tensorflow/tensorflow/issues/40822#issuecomment-650075807)

**Comment by saifiShaddil** [comment]
> -upgrade tensorflow==2.2 and let us know if it works.

I actually didn't checked my python installed was 32 bit, so just installed 64 bit version and used cmd pip pip install tensorflow==2.2
working perfectly fine. thanks for the help
