### ISSUE TITLE
How to check programmatically TF-Lite Ops supported

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#41263]
How to check programmatically TF-Lite Ops supported?

Is there a way to check the list of all operators available per platform CPU ([BuiltinOperator](https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/lite/tools/versioning/runtime_version.cc#L53)), GPU ([OperationType](https://github.com/tensorflow/tensorflow/blob/9e54b4b299f27dfdd2cb8d9d00c7186eb7d9826f/tensorflow/lite/delegates/gpu/common/operations.h#L33)) programmatically?

**Comment by srjoglekar246** [comment]
Short answer, no. Apart from grepping the source code files, there is no other way.

Out of curiosity, what is the use case here? Are you using an environment where the client is allowed to execute *any* TFLite model they might have?
