### ISSUE TITLE
Device logging from C API not appearing

### ISSUE THREAD

**Issue by malmaud** [tensorflow/tensorflow#4126]
Hello,
I'm using the C API and creating a session with the `log_device_placement` config parameter set to `true`, but am not actually seeing any logging output on STDOUT. Is there something special I need to be doing to capture and display the TensorFlow log from C?

**Comment by poxvoculi** [comment]
Could you give a simple example I might be able to reproduce?

**Comment by tatatodd** [comment]
@malmaud, in addition to a simple example to help us reproduce the issue, you might try adding --alsologtostderr on the command-line of your binary.

**Comment by tatatodd** [comment]
Closing this out due to lack of activity.  Feel free to post on this issue if it's still a problem.  Thanks!
