### ISSUE TITLE
tensorflow2.3 android cannot open armv7-a/libatomic.a

### ISSUE THREAD

**Issue by ShifengJin** [tensorflow/tensorflow#41267]
/tensorflow-r2.3/tensorflow/lite/java/BUILD:404:18: Linking of rule '//tensorflow/lite/java:libtensorflowlite_jni.so' failed (Exit 1)
external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot open external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/lib/../lib/armv7-a/libatomic.a: No such file or directory
clang.exe: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Saduf2019** [comment]
@ShifengJin 
Please refer to these links and let us know if it helps:
#31190 [link](https://forum.unity.com/threads/il2cpp-build-error-missing-libatomic-a.786005/) [link1](https://answers.unity.com/questions/1683287/cannot-build-android-il2cpp-for-unity.html) [link2](https://stackoverflow.com/questions/52366135/android-ndk-cmake-linker-so-no-such-file-or-directory)
