### ISSUE TITLE
Could the argument alpha in leakyrelu be minus?

### ISSUE THREAD

**Issue by Hamoni-XJTU** [tensorflow/tensorflow#41260]
I have tried to set alpha <0 in my model, the model did not work. Some document said the argument should >0, is it really? How can I make it?

**Comment by Leslie-Fang** [comment]
@Hamoni-XJTU What's error message did you see?

**Comment by Leslie-Fang** [comment]
This https://github.com/tensorflow/tensorflow/blob/f1c2b67ff7dc33d2eee7ea58e5502cfede470d9c/tensorflow/python/keras/layers/advanced_activations.py#L63 tells us alpha should be positive.
But I didn't see any error with the below test code.

```
import tensorflow as tf
layer = tf.keras.layers.LeakyReLU(alpha=-0.1)
output = layer([-3.0, -1.0, 0.0, 2.0])
print(output)
```
