### ISSUE TITLE
tf_doctest.py fails on import 

### ISSUE THREAD

**Issue by jpodivin** [tensorflow/tensorflow#41279]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 20.04 LTS**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary): **pip package**
- TensorFlow version: **2.2.0**
- Python version: **3.8.2**
- Installed using virtualenv? pip? conda?: **pip**
- Bazel version (if compiling from source): **N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **N/A**
- GPU model and memory: **N/A**

I was testing my changes to the documentation, specifically the doctests as specified in #40619, using the `tf_doctest.py` as described in [documentation](https://www.tensorflow.org/community/contribute/docs_ref).

Unfortunately the command: `python tf_doctest.py --file=../../python/module/module.py` failed producing following error.
```
Traceback (most recent call last):
  File "tf_doctest.py", line 30, in <module>
    import tensorflow.compat.v2 as tf

ModuleNotFoundError: No module named 'tensorflow.compat'
```
I tried the same in container spun from devel image with similar results. In order to identify the issue I reinstalled tensorflow on my machine and for the good measure removed nightly packages. The result wasn't any better.

Please note that I only altered module.py file, as described in #40619

**Comment by ravikyram** [comment]
@jpodivin 

Can you refer  #26546 and see if it helps you.Thanks!

**Comment by jpodivin** [comment]
> @jpodivin
> 
> Can you refer #26546 and see if it helps you.Thanks!


That doesn't seem like really work. I have the right version of tensorflow installed, both in venv and in system itself. 
The output of `python -c "import tensorflow as tf; print(tf.__version__)"` confirms it.

**Comment by jpodivin** [comment]
I reinstalled the tensorflow yet again on both system and venv. The only result is that now I get:

```
Traceback (most recent call last):
  File "tf_doctest.py", line 33, in <module>
    from tensorflow.tools.docs import tf_doctest_lib
ImportError: cannot import name 'tf_doctest_lib' from 'tensorflow.tools.docs' (/home/jpodivin/.local/lib/python3.8/site-packages/tensorflow/tools/docs/__init__.py)

```

**Comment by yashk2810** [comment]
Yeah.. I'l fix this. 

@mihaimaruseac Do I need to add tf_doctest_lib to the pip package thing for it to get exported out?

**Comment by mihaimaruseac** [comment]
I think so.

**Comment by Harsh188** [comment]
Hello, 
I came across this issue recently as well while trying to test the changes I made to the python documentation in math_ops #42619. @yashk2810 I'd love to contribute if I could get some guidance!

**Comment by RonLek** [comment]
@Harsh188 I've made some changes to math_ops as well. Any idea how you fixed this issue?

**Comment by ashwin-phadke** [comment]
Any workarounds ? So far I have tried to change import to local file but that doesn't work too.

**Comment by Harsh188** [comment]
> @Harsh188 I've made some changes to math_ops as well. Any idea how you fixed this issue?

Can you link your PR so I can take a look?

**Comment by RonLek** [comment]
Sure @Harsh188 here it is #43758

**Comment by Harsh188** [comment]
@mihaimaruseac Could you help workout this issue? I took a peek at [`pip_package/BUILD`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/BUILD) but I'm not sure how I'm supposed to make the appropriate change.

**Comment by mihaimaruseac** [comment]
Is this still an issue?

@Harsh188 you probably need to add to `COMMON_PIP_DEPS` list.
