### ISSUE TITLE
TypeError: Failed to convert object of type <class 'tensorflow.python.ops.ragged.ragged_tensor.RaggedTensor'> to Tensor.

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#41276]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: Yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Colab
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:
-   **TensorFlow installed from (source or binary)**:
-   **TensorFlow version (use command below)**: 2.4.0-dev20200709
-   **Python version**:
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:
-   **GPU model and memory**:
-   **Exact command to reproduce**:

### Describe the problem
I am referring to [this official Keras example](https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/vision/ipynb/captcha_ocr.ipynb) that shows how to train an OCR model using the CTC loss. I am trying to extend it to the [**IAM dataset**](http://www.fki.inf.unibe.ch/DBs/iamDB/iLogin/index.php) which is rawer in terms of its quality and the images are of handwritten characters. 

I was able to construct the dataset in the way expected by the model used in the example. However, the labels, in this case, are of variable length. This is why they are getting converted to RaggedTensors. This is producing the following error - 

```
TypeError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:806 train_function  *
        return step_function(self, iterator)
    <ipython-input-42-e0e4c73f8c9f>:10 call  *
        batch_len = tf.cast(tf.shape(y_true)[0], dtype="int64")
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py:201 wrapper  **
        return target(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py:617 shape_v2
        return shape(input, name, out_type)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py:644 shape
        return shape_internal(input, name, optimize=True, out_type=out_type)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py:668 shape_internal
        input = ops.convert_to_tensor(input)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:1525 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py:338 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py:264 constant
        allow_broadcast=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/constant_op.py:282 _constant_impl
        allow_broadcast=allow_broadcast))
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_util.py:553 make_tensor_proto
        "supported type." % (type(values), values))

    TypeError: Failed to convert object of type <class 'tensorflow.python.ops.ragged.ragged_tensor.RaggedTensor'> to Tensor. Contents: tf.RaggedTensor(values=tf.RaggedTensor(values=Tensor("ocr_model_v1/Cast_1:0", shape=(None,), dtype=float32), row_splits=Tensor("RaggedFromVariant/RaggedTensorFromVariant:1", shape=(None,), dtype=int64)), row_splits=Tensor("RaggedFromVariant/RaggedTensorFromVariant:0", shape=(None,), dtype=int64)). Consider casting elements to a supported type.
```

What I am looking for is a way to bypass this so that the ground truth labels and the predicted labels could be sent to the CTC loss. 

### Source code / logs
Here's the [Colab Notebook](https://colab.research.google.com/gist/sayakpaul/529500ca05252277f1c1f390ef37e4d3/scratchpad.ipynb). 

The commands that download the dataset are as follows:
```
$ wget http://www.fki.inf.unibe.ch/DBs/iamDB/data/words/words.tgz --user=**user** --password=**password**
$ wget http://www.fki.inf.unibe.ch/DBs/iamDB/data/ascii/words.txt --user=**user** --password=**password**
```

**_Please register here first: http://www.fki.inf.unibe.ch/DBs/iamDB/iLogin/index.php and then replace the username and password accordingly. This is a requirement._**

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/71ce949e24f2ac3a4c8ad6ad71590a04/41276-2-3.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/02ef24654712fad95814b72d8bf4b0ce/41276-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by sayakpaul** [comment]
@amahendrakar you forgot to attach the Colab Gist link I guess.

**Comment by ymodak** [comment]
Thanks for your issue. For quicker troubleshooting can you please help us with minimalistic code to reproduce the reported behavior?

**Comment by sayakpaul** [comment]
I think I already did that and you can also see that @amahendrakar was able to confirm it. Unfortunately, I don't have anything more minimalistic at the moment.

**Comment by edloper** [comment]
The problem is that `tf.shape` isn't defined for RaggedTensors, since it's not possible to encode the shape of a `RaggedTensor` in a vector.  If you know that `y_true` is ragged, then you can change this:

```
batch_len = tf.cast(tf.shape(y_true)[0], dtype="int64")
```

to this:

```
batch_len = y_true.nrows(dtype=tf.int64)
```

If you don't know whether it's ragged or not, then the best solution at the moment might be to do something like `batch_len = _nrows(y_true, 'int64')` where `_nrows` is defined as:

```
def _nrows(tensor, out_type=dtypes.int32):
  if isinstance(tensor, RaggedTensor):
    return tensor.nrows(out_type=out_type)
  else:
    return array_ops.shape(tensor, out_type=out_type)[0]
```

We have some general ideas about how `tf.shape` could be implemented for `RaggedTensor`, but it would need to return a different type (a `RaggedTensorShape`), which is currently only used internally; and that type would need to be updated with __getitem__ etc.  But I don't think that's likely to get implemented in the near-term future.

**Comment by edloper** [comment]
I just took a quick look at the colab in question, and there are a few other things you're likely to need to tweak.  E.g., you may need to change:

```
        input_length = tf.cast(tf.shape(y_pred)[1], dtype="int64")
        label_length = tf.cast(tf.shape(y_true)[1], dtype="int64")
```

to:

```
        input_length = y_pred.uniform_row_length
        label_length = y_true. uniform_row_length
```

Alternatively, if `y_pred` and `y_true` have statically known shapes, you could possibly use:

```
        batch_len = tf.cast(y_true.shape[0], dtype="int64")
        input_length = tf.cast(y_pred.shape[1], dtype="int64")
        label_length = tf.cast(y_true.shape[1], dtype="int64")
```

Another option might be to convert `y_pred` and `y_true` to non-ragged (padded) tensors (with `y_pred.to_tensor()` and `y_true.to_tensor()`), though I'm not familiar enough with this code to know whether that would do the right thing.

**Comment by sayakpaul** [comment]
@edloper I changed

```python
batch_len = tf.cast(y_true.shape[0], dtype="int64")
input_length = tf.cast(y_pred.shape[1], dtype="int64")
label_length = tf.cast(y_true.shape[1], dtype="int64")
```
to

```python
batch_len = batch_len = nrows(y_true, 'int64')
input_length = y_pred.uniform_row_length
label_length = y_true.uniform_row_length
```

where `nrows()` is defined as - 

```python
def nrows(tensor, out_type=tf.dtypes.int32):
  if isinstance(tensor, tf.RaggedTensor):
    return tensor.nrows(out_type=out_type)
  else:
    return tf.python.ops.array_ops.shape(tensor, out_type=out_type)[0]
```

Now, I am getting while building the model - 

```
AttributeError: in user code:

    <ipython-input-23-0940c7590da2>:10 call  *
        input_length = y_pred.uniform_row_length

    AttributeError: 'Tensor' object has no attribute 'uniform_row_length'
```

Here's the [Colab Gist](https://colab.research.google.com/gist/sayakpaul/fdb3591ea69ce7f4644f03253aae93a7/scratchpad.ipynb). Any pointers?

**Comment by edloper** [comment]
@sayakpaul It looks to me like the keras code would need some refactoring to be able to deal with variable-length labels -- right now, it's assuming a specific rank for its input.  I.e., you could fix your `call` code with something like the following:

```
    def call(self, y_true, y_pred):
        # Compute the training-time loss value and add it
        # to the layer using `self.add_loss()`.
        if isinstance(y_true, tf.RaggedTensor):
          batch_len = y_true.nrows(out_type='int64')
          input_length = tf.cast(
              tf.expand_dims(y_true.row_lengths(), 1), 'int64'),
        else:
          y_true_shape = tf.shape(y_true, out_type='int64')
          batch_len = y_true_shape[0]
          input_length = tf.fill([batch_len, 1], y_true_shape[1])

        if isinstance(y_pred, tf.RaggedTensor):
          label_length = tf.cast(
              tf.expand_dims(y_pred.row_lengths(), 1), 'int64'),
        else:
          y_pred_shape = tf.shape(y_pred, out_type='int64')
          label_length = tf.fill([batch_len, 1], y_pred_shape[1])

        loss = self.loss_fn(y_true, y_pred, input_length, label_length)
        self.add_loss(loss)

        # At test time, just return the computed predictions
        return y_pred
```

But then things will still fail inside `ctc_batch_cost` in `keras/backend.py` (when it tries to call `ctc_label_dense_to_sparse`).  So I think `ctc_batch_cost` itself would need to be edited/modified to make this work.

**Comment by sayakpaul** [comment]
Ah. Thanks for sharing it. So, for now, I am gonna close this issue. If needed I will reopen.

**Comment by sayakpaul** [comment]
@alextp any ideas/pointers how to extend `ctc_batch_cost` from `keras/backend.py` to support variable-length labels labels?

**Comment by alextp** [comment]
Can you file a separate issue for that? nothing immediately comes to mind as better than other alternatives

**Comment by sayakpaul** [comment]
Okay let me do that.
