### ISSUE TITLE
Real-time prediction using Keras

### ISSUE THREAD

**Issue by vasilevskykv** [tensorflow/tensorflow#41274]
THi! I would like to ask, does Keras Neural Networks do predictions in real time?
I see, that one of your parameters in prediction is array of data. But when you need to predict future data, you don't have an array of data - you have only previous data and time interval for prediction and nothing more.
As I undestand, you simply checked the prediction because to predict future data I need to give to a function predict a time interval in future, not a previous data trainX as necessary in this function predict

Here is my Neuro Network:
look_back = 3
model = Sequential()
model.add(LSTM(4, input_shape=(look_back, 1)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(trainX, trainY, epochs=20, batch_size=1, verbose=2)
trainPredict = model.predict(trainX)

I would like to predict future values of EMA oscillator using previous values and a value in the current time moment

def create_dataset(dataset, look_back=1):
dataX, dataY = [], []
for i in range(len(dataset)-look_back-1):
a = dataset[i:(i+look_back), 0]
dataX.append(a)
dataY.append(dataset[i + look_back, 0])
return np.array(dataX), np.array(dataY)

I would like to predict future values of EMA oscillator using previous values and a value in the current time moment
data2 = pandas.read_csv('ratevalues.csv')[::-1]
data2.columns = ['date','high','low','open','close','volume','quoteVolume','weightedAverage']
dataset = pandas.DataFrame(data2.close.ewm(span=14).mean())
train_size = int(len(dataset) * 0.67)
train = dataset[0:train_size,:]
trainX, trainY = create_dataset(train, look_back)

Can you show an example of predicting in real time?

**Comment by Saduf2019** [comment]
@vasilevskykv 
Please share indented stand alone code with all dependencies for us to replicate the issue or if possible share a colab gist for us to analyse the error.

**Comment by vasilevskykv** [comment]
The question is not to find an error. I would like to know if it is possible to predict future data in real time and how to do it because I didn't see where to put a future time interval to the function **predict**.

Here is the whole code:

`import numpy as np
import matplotlib.pyplot as plt
import pandas
import math
#import DataFrame
import datetime as dt
from datetime import datetime
from getDataFromPoloniex import get_data_from_poloniex
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

np.random.seed(7)

data2 = pandas.read_csv('ratevalues.csv')[::-1]
data2.columns = ['date','high','low','open','close','volume','quoteVolume','weightedAverage']
dataset = pandas.DataFrame(data2.close.ewm(span=14).mean())

def create_dataset(dataset, look_back=1):
	dataX, dataY = [], []
	for i in range(len(dataset)-look_back-1):
		a = dataset[i:(i+look_back), 0]
		dataX.append(a)
		dataY.append(dataset[i + look_back, 0])
	return np.array(dataX), np.array(dataY)

scaler = MinMaxScaler(feature_range=(0, 1))
dataset = scaler.fit_transform(dataset)

look_back = 3

train_size = int(len(dataset) * 0.67)
train = dataset[0:train_size,:]
trainX, trainY = create_dataset(train, look_back)

trainX = np.reshape(trainX, (trainX.shape[0], trainX.shape[1], 1))

model = Sequential()
model.add(LSTM(4, input_shape=(look_back, 1)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(trainX, trainY, epochs=20, batch_size=1, verbose=2)
trainPredict = model.predict(trainX)

trainPredict = scaler.inverse_transform(trainPredict)
trainY = scaler.inverse_transform([trainY])
trainScore = math.sqrt(mean_squared_error(trainY[0], trainPredict[:,0]))
`

**Comment by vasilevskykv** [comment]
I've already read the documentation. Everywhere I saw **model.predict(testX)**. But when I predict in real-time mode I don't have testX because **testX will be in future**. What should I give to the function **predict** instead of testX to make real-time prediction?

**Comment by gowthamkpr** [comment]
@vasilevskykv Please take a look at this [example](https://www.tensorflow.org/tutorials/structured_data/time_series) and let me know if it helps.

**Comment by yongtang** [comment]
@vasilevskykv The testX could be passed as a `tf.data.Dataset`, and, if the `tf.data.Dataset` is blocking then you should have a real-time prediction pipeline. One way of achieve that is to use KafkaIODataset in https://github.com/tensorflow/io Let me know if you have questions (you can also create an issue there for further discussion).

**Comment by vasilevskykv** [comment]
I tried to use your idea, but I had a problem:
`Traceback (most recent call last):
  File "D:\CryptoTrading\Prediction\BinanceNeuroPrediction\TFPredict.py", line 1, in <module>
    import tensorflow as tf
  File "I:\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "I:\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "I:\Python\Python36\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "I:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "I:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "I:\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module was not found.`

**Comment by vasilevskykv** [comment]
I installed tensorflow-gpu and then I got the following:
`2020-08-17 10:10:24.670105: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Traceback (most recent call last):
  File "D:\CryptoTrading\Prediction\BinanceNeuroPrediction\TFPredict.py", line 2, in <module>
    import tensorflow_io as tfio
  File "I:\Python\Python36\lib\site-packages\tensorflow_io\__init__.py", line 17, in <module>
    from tensorflow_io.core.python.api.v0 import *  # pylint: disable=wildcard-import
  File "I:\Python\Python36\lib\site-packages\tensorflow_io\core\python\api\v0\__init__.py", line 18, in <module>
    from tensorflow_io.core.python.ops.io_dataset import IODataset
  File "I:\Python\Python36\lib\site-packages\tensorflow_io\core\python\ops\__init__.py", line 71, in <module>
    core_ops = _load_library("libtensorflow_io.so")
  File "I:\Python\Python36\lib\site-packages\tensorflow_io\core\python\ops\__init__.py", line 67, in _load_library
    + "{}, from paths: {}\ncaused by: {}".format(filename, filenames, errs)
NotImplementedError: unable to open file: libtensorflow_io.so, from paths: ['I:\\Python\\Python36\\lib\\site-packages\\tensorflow_io\\core\\python\\ops\\libtensorflow_io.so']
caused by: ['I:\\Python\\Python36\\lib\\site-packages\\tensorflow_io\\core\\python\\ops\\libtensorflow_io.so not found']`
I'm working in Windows 10, not in Linux

**Comment by yongtang** [comment]
@vasilevskykv Can you open an issue in [tensorflow/io](https://github.com/tensorflow/io)? Please also includes additional information such as how python was installed and how tensorflow and tensorflow-io were installed (e.g., through pip or custom build).

**Comment by vasilevskykv** [comment]
I wrote this question to
https://github.com/tensorflow/io/issues/1091
