### ISSUE TITLE
Compile failure in TF 2.3 rc0 on python 3.5

### ISSUE THREAD

**Issue by shwetaoj** [tensorflow/tensorflow#41287]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 16.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version: **2.3**
- Python version: **3.5**
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): **3.1.0**
- GCC/Compiler version (if compiling from source): **gcc version: 8.2.1**
- CUDA/cuDNN version:
- GPU model and memory:

**I am trying to build Tensorflow 2.3 on python 3.5 and getting following compile errors:
ERROR: /root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/com_google_protobuf/BUILD:795:1: C++ compilation of rule '@com_google_protobuf//:python/google/protobuf/internal/_api_implementation.so' failed (Exit 1)
In file included from bazel-out/k8-opt/bin/external/local_config_python/python_include/Python.h:8,
                 from external/com_google_protobuf/python/google/protobuf/internal/api_implementation.cc:31:
bazel-out/k8-opt/bin/external/local_config_python/python_include/pyconfig.h:3:12: fatal error: x86_64-linux-gnu/python3.5m/pyconfig.h: No such file or directory
 #  include <x86_64-linux-gnu/python3.5m/pyconfig.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
**

**I ran with the following bazel options:
'build' options: --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 --copt=-O3 --copt=-Wformat --copt=-Wformat-security --copt=-fstack-protector --copt=-fPIC --copt=-fpic --linkopt=-znoexecstack --linkopt=-zrelro --linkopt=-znow --linkopt=-fstack-protector --config=mkl --copt=-march=sandybridge
**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by av8ramit** [comment]
This may not be TensorFlow specific but perhaps related to your installation of Python 3.5 on your machine. I think you need to add the location of `python3.5m/pyconfig.h` to your path, or symlink it to that location?

https://github.com/okfn/piati/issues/65
https://github.com/BVLC/caffe/issues/410

^ Similar issues that were solved that way. Have you been able to build TF prior to in the same env?

**Comment by shwetaoj** [comment]
Thanks for your suggestion. Let me try that.
To answer your question, yes we were able to build TF 2.2 using the same scripts on python 3.5.

**Comment by shwetaoj** [comment]
@av8ramit Thanks for the pointers adding libxml2-dev libxslt-dev in the python 3.5 container fixed the issue.

**Comment by av8ramit** [comment]
@shwetaoj no problem! Glad I could help!

**Comment by shwetaoj** [comment]
The issue is with gcc version. With gcc 5.x it works but with gcc 8.x it fails.
Surprisingly this works fine with python versions 3.6, 3.7 and 3.8.

**Comment by shwetaoj** [comment]
Installing python 3.5.9 from the source fixed the issue. Using the default python version 3.5.2 of the ubuntu 16.04 container was causing compile errors.
