### ISSUE TITLE
Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.

### ISSUE THREAD

**Issue by cam145** [tensorflow/tensorflow#41284]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
Ubuntu 18.04
- TensorFlow version (you are using): 2.3.0-r0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.

**Will this change the current api? How?**No

**Who will benefit with this feature?** networks with dynamic tensors.

**Any Other info.**

**Comment by Saduf2019** [comment]
@cam145 
Please provide with more details on the issue.
