### ISSUE TITLE
device:GPU missing from the list not accepting XLA_GPU

### ISSUE THREAD

**Issue by Vatsal-Malaviya** [tensorflow/tensorflow#41281]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.2.0
- Python version: 3.7.6
- CUDA/cuDNN version: 10.1 update 2 / 7.5
- GPU model and memory: RTX 2060, dedicated 6 GB and shared 8 GB

**Describe the current behavior**
>>> tf.test.is_gpu_available(cuda_only=False, min_cuda_compute_capability=None)                                                                                                                                    WARNING:tensorflow:From <stdin>:1: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.                                                            Instructions for updating:                                                                                                                                                                                         Use `tf.config.list_physical_devices('GPU')` instead.                                                                                                                                                              2020-07-10 19:37:38.026206: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2                                          2020-07-10 19:37:38.077466: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2311a9eb5d0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:                    2020-07-10 19:37:38.085075: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version                                                                                   2020-07-10 19:37:38.099271: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll                                                                         2020-07-10 19:37:39.351124: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:                                                                                               pciBusID: 0000:01:00.0 name: GeForce RTX 2060 computeCapability: 7.5                                                                                                                                               coreClock: 1.335GHz coreCount: 30 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 312.97GiB/s                                                                                                                     2020-07-10 19:37:39.369392: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found                                 2020-07-10 19:37:39.375813: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cublas64_10.dll'; dlerror: cublas64_10.dll not found                                   2020-07-10 19:37:39.381862: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found                                     2020-07-10 19:37:39.388101: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'curand64_10.dll'; dlerror: curand64_10.dll not found                                   2020-07-10 19:37:39.392995: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found                               2020-07-10 19:37:39.398977: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusparse64_10.dll'; dlerror: cusparse64_10.dll not found                               2020-07-10 19:37:39.403336: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudnn64_7.dll'; dlerror: cudnn64_7.dll not found                                       2020-07-10 19:37:39.408632: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.                                                                 Skipping registering GPU devices...                                                                                                                                                                                2020-07-10 19:37:39.596047: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:                                                               2020-07-10 19:37:39.599475: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0                                                                                                                        2020-07-10 19:37:39.601116: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N                                                                                                                        2020-07-10 19:37:39.607957: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x23112e31a20 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:                    2020-07-10 19:37:39.611013: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2060, Compute Capability 7.5                                                                False  

>>> tf.config.list_physical_devices('GPU')                                                                                                                                                                         2020-07-10 19:40:03.191437: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:                                                                                               pciBusID: 0000:01:00.0 name: GeForce RTX 2060 computeCapability: 7.5                                                                                                                                               coreClock: 1.335GHz coreCount: 30 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 312.97GiB/s                                                                                                                     2020-07-10 19:40:03.220558: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found                                 2020-07-10 19:40:03.234827: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cublas64_10.dll'; dlerror: cublas64_10.dll not found                                   2020-07-10 19:40:03.244975: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found                                     2020-07-10 19:40:03.254710: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'curand64_10.dll'; dlerror: curand64_10.dll not found                                   2020-07-10 19:40:03.263915: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found                               2020-07-10 19:40:03.274163: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusparse64_10.dll'; dlerror: cusparse64_10.dll not found                               2020-07-10 19:40:03.283131: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudnn64_7.dll'; dlerror: cudnn64_7.dll not found                                       2020-07-10 19:40:03.291143: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.                                                                 Skipping registering GPU devices...                                                                                                                                                                                [] 

>>> tf.config.list_physical_devices()                                                                                                                                                                              [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU'), PhysicalDevice(name='/physical_device:XLA_GPU:0', device_type='XLA_GPU')]  

**Describe the expected behavior**
Cuda available and GPU also should be available 
**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Vatsal-Malaviya** [comment]
Also,

>>> tf.test.is_built_with_cuda()                                                                                                                                                                                   True

**Comment by Vatsal-Malaviya** [comment]
![image](https://user-images.githubusercontent.com/31595943/87164740-c2853d80-c2e6-11ea-9cf4-9e3a1472a6e0.png)
While using tensorboard i got this message
But I already got that file
![image](https://user-images.githubusercontent.com/31595943/87164894-fa8c8080-c2e6-11ea-8cf2-35f7d14704e4.png)
and also it has been added to the path
![image](https://user-images.githubusercontent.com/31595943/87165100-4dfece80-c2e7-11ea-95cc-7a7da2d73ea7.png)

I have tried to follow the guidelines provided by [https://towardsdatascience.com/installing-tensorflow-with-cuda-cudnn-and-gpu-support-on-windows-10-60693e46e781](url) for installation

**Comment by bhack** [comment]
Is this a dup of https://github.com/tensorflow/tensorflow/issues/36111?

**Comment by Vatsal-Malaviya** [comment]
its one of the problem, TensorFlow fails to acknowledge GPU,

**Comment by Vatsal-Malaviya** [comment]
> Is this a dup of #36111?

also, I saw that #36111 suggests updating cuda path that it is showing already

**Comment by amahendrakar** [comment]
@Vatsal-Malaviya,
Just to make sure, did you check this comment from [#36111](https://github.com/tensorflow/tensorflow/issues/36111#issuecomment-614933000)? 

Could you please let us know if you have installed Python from the Microsoft Store or from python.org. Thanks!
