### ISSUE TITLE
How to disable mkl_dnn when compile TensorFlow 1.15?

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [tensorflow/tensorflow#41299]
Compile TensorFlow 1.15 from source code will use more than 1.5 hours, and during compile I find mkl_cudnn is compiled by default.  What I need is TensorFlow 1.15 with CUDA support, how to reduce the compile time?

**Comment by Keepmoving-ZXY** [comment]
And could anyone tell me how to let bazel compile the changed code file, not all the code?

**Comment by Keepmoving-ZXY** [comment]
And if I logout ssh, and re-connect to the same workstation, any change to source code will lead to bazel compile the whole code,  it is so bad.

**Comment by PINTO0309** [comment]
I don't know if this will help you, but I'm using Bazel's Remote Caching feature for fast builds.
1. **[Ultra-fast build of Tensorflow with Bazel Remote Caching [Docker version]](https://qiita.com/PINTO/items/49ce77a6ee03b404c156)**
2. **[Ultra-fast build of Tensorflow with Bazel Remote Caching [Google Cloud Storage version]](https://qiita.com/PINTO/items/eef2eccc21dc72227d0f)**
![001](https://user-images.githubusercontent.com/33194443/87235951-7688e480-c41d-11ea-9339-5ac436d9bc28.gif)

**Comment by Keepmoving-ZXY** [comment]
@PINTO0309  thank you, I will have a try.

**Comment by amahendrakar** [comment]
@Keepmoving-ZXY,
As mentioned in the [build from source](https://www.tensorflow.org/install/source#gpu_support) guide, please set `cuda=Y` for GPU/CUDA support.  Thanks!

**Comment by Keepmoving-ZXY** [comment]
@amahendrakar I want to know when build tensorflow 1.15 with cuda support, how to disable mkl_dnn manually ?

**Comment by NeoZhangJianyu** [comment]
@Keepmoving-ZXY 
mkl_dnn is disable by default.

`--config=mkl` will enable mkl_dnn.

Could you share your build cmd if there is still enable mkl_dnn?

Note, please clean the build env before rebuild it for disable mkl_dnn.

**Comment by NeoZhangJianyu** [comment]
@Keepmoving-ZXY 

Is there any feedback?

**Comment by NeoZhangJianyu** [comment]
@Keepmoving-ZXY 

Is it possible to close this issue?
