### ISSUE TITLE
Model.fit(): class_weight leads to error with distributed Dataset 

### ISSUE THREAD

**Issue by caisq** [tensorflow/tensorflow#41290]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): effectively tf-nightly 20200710
- Python version:
- Bazel version (if compiling from source):

**Describe the current behavior**

When I call tf.keras.Model.fit() with a distributed dataset, one obtained from 
`strategy.experimental_distribute_dataset()`, in conjunction with class_weight, 
I get the following error:

```
    dataset = dataset.map(_make_class_weight_map_fn(class_weight))
AttributeError: 'DistributedDataset' object has no attribute 'map'
```

The model fit code looks like:

```py
    model.fit(
      train_ds,
      epochs=FLAGS.epochs,
      steps_per_epoch=train_steps_per_epoch,
      validation_data=val_ds,
      validation_steps=val_steps_per_epoch,
      class_weight={
          0: 1.0,
          1: 5.0,
      },
      callbacks=[
          tf.keras.callbacks.TensorBoard(FLAGS.logdir, profile_batch=50)
      ])
```

However, if I don't call `strategy.experimental_distribute_dataset()` on train_ds
and val_ds, the fit() works correctly.

The `strategy` here is simpley a OneDeviceStrategy with my GPU.

**Describe the expected behavior**

The expected behavior is that class_weight should work regardless of 
whether the Dataset is distributed or not.

**Comment by ravikyram** [comment]
@caisq 

Request you to share colab link or complete code snippet to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by nikitamaia** [comment]
Hi @caisq, looking [at the docs for](https://www.tensorflow.org/api_docs/python/tf/distribute/Strategy#experimental_distribute_dataset) `experimental_distribute_dataset` you'll see it says "NOTE: Currently, the user cannot add any more transformations to a distributed dataset." I suspect this is what is causing the problem given the error message that there's `no attribute 'map'` for a `'DistributedDataset'`. Happy to help debug further if you can provide minimal reproducible code.

**Comment by juzzmac** [comment]
Hi, I'm running into the same issue. This demo script below replicates the error. If the `class_weight` parameter is removed then the code completes without error:

```
from bigdl.orca import init_orca_context, OrcaContext

init_orca_context(cluster_mode="local")
spark = OrcaContext.get_spark_session()


from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Model

def model_creator(config):
    input_layer = Input(shape=(1,))
    x = Dense(2, activation='relu')(input_layer)
    output_layer = Dense(1, activation='relu')(x)

    model = Model(inputs=input_layer, outputs=output_layer)
    model.compile(
        loss='categorical_crossentropy',
        optimizer='adam',
        metrics=['accuracy']
    )
    return model

from bigdl.orca.learn.tf2 import Estimator

est = Estimator.from_keras(model_creator=model_creator, workers_per_node=2)

test_data = spark.createDataFrame(
    [
        {'VAR1': 5, 'VAR2': 0},
        {'VAR1': 6, 'VAR2': 0},
        {'VAR1': 7, 'VAR2': 0},
        {'VAR1': 9, 'VAR2': 1},
        {'VAR1': 10, 'VAR2': 1},
        {'VAR1': 11, 'VAR2': 1},
    ]
)

batch_size = 2

stats = est.fit(
    test_data,
    feature_cols=['VAR1'],
    label_cols=['VAR2'],
    epochs=1,
    batch_size=batch_size,
    steps_per_epoch=6 // batch_size,
    class_weight={0: 0.5, 1: 0.5},
)
```

**Comment by juzzmac** [comment]
Can we reopen this issue?
