### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot add tensor to the batch: number of elements does not match. Shapes are: [tensor]: [3], [batch]: [5]

### ISSUE THREAD

**Issue by SlowMonk** [tensorflow/tensorflow#41298]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.2 
- Python version: 3.7.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: titan xp 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

getting error  

`tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot add tensor to the batch: number of elements does not match. Shapes are: [tensor]: [3], [batch]: [5]`

```
def train():
    print('train')
    print(tf.__version__)
    batch_size= 2
    images,boxes,labels,difficulties,new_boxes= PascalVOCDataset()
    new_boxes = list(new_boxes)


    boxes = tf.ragged.constant(boxes)
    labels = tf.ragged.constant(labels)
    new_boxes = tf.ragged.constant(new_boxes)

    print('boxes->',boxes.shape)
    print('labels->',labels.shape)
    print('images->', np.array(images).shape)

    dataset = tf.data.Dataset.from_tensor_slices((images,new_boxes,labels))
    run_train(dataset.map(resize_image_bbox, num_parallel_calls=tf.data.experimental.AUTOTUNE).batch(batch_size).prefetch(tf.data.experimental.AUTOTUNE))

def main():
    train()
if __name__ =='__main__':
    main()
boxes-> (5717, None, None)
labels-> (5717, None)
images-> (5717,)
===============================================resize_image_bbox
new_image-> (300, 300, 3)
new_boxes-> (None, None)
labels-> (None,)
run_train
dataset-> <PrefetchDataset shapes: ((None, 300, 300, 3), (None, None, None), (None, None)), types: (tf.float32, tf.float32, tf.int32)>
=========================================================
image_shape-> (2, 300, 300, 3)
labels_shape-> (2, 2)
boxes_shape-> (2,)
```

when I change the batch_size 1-> any number it gives this error 

```
Traceback (most recent call last):
  File "/home/jake/Gits/ssd_tensorflow/train.py", line 64, in <module>
    main()
  File "/home/jake/Gits/ssd_tensorflow/train.py", line 62, in main
    train()
  File "/home/jake/Gits/ssd_tensorflow/train.py", line 59, in train
    run_train(dataset.map(resize_image_bbox, num_parallel_calls=tf.data.experimental.AUTOTUNE).batch(batch_size).prefetch(tf.data.experimental.AUTOTUNE))
  File "/home/jake/Gits/ssd_tensorflow/train.py", line 26, in run_train
    for idx,(images,boxes,labels) in enumerate(dataset): # (batch_size (N), 300, 300, 3)
  File "/home/jake/venv/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 631, in __next__
    return self.next()
  File "/home/jake/venv/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 670, in next
    return self._next_internal()
  File "/home/jake/venv/lib/python3.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 661, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/jake/venv/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 1989, in execution_mode
    executor_new.wait()
  File "/home/jake/venv/lib/python3.7/site-packages/tensorflow/python/eager/executor.py", line 67, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot add tensor to the batch: number of elements does not match. Shapes are: [tensor]: [3], [batch]: [5]

Process finished with exit code 1
```

**Comment by Saduf2019** [comment]
@SlowMonk 
Please provide us with indented code such that we can replicate the issue faced, we face a different error for the code shared, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/07c95841a809d3ef4da348962508fbde/untitled272.ipynb)

With respect to the error please refer to below issues and let us know if it helps:
#34544 # [link](https://stackoverflow.com/questions/59006696/cannot-add-tensor-to-the-batch-number-of-elements-does-not-match-shapes-are) [link](https://github.com/tensorflow/tensorflow/issues/40919#issuecomment-656728535)
