### ISSUE TITLE
Let Attention layer accept a layer mask of list of length 3, namely [query_mask, value_mask, key_mask]

### ISSUE THREAD

**Issue by bubblebooy** [tensorflow/tensorflow#41294]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (2.2.0):
- Are you willing to contribute it (Yes):

**Describe the feature and the current behavior/state.**
for tf.keras.layers.Attention currently the layer mask must be a list of length 2, namely [query_mask, value_mask]
change it to also accept a layer mask of list of length 3, namely [query_mask, value_mask, key_mask]

currently def compute_mask() returns the query_mask and ignores the value_mask. If passed a key_mask it could also just be ignored

**Will this change the current api? How?**
No

**Comment by bubblebooy** [comment]
**Who will benefit with this feature?**
Example:
```Encoder example
input = tf.keras.layers.Input(shape=(None,))
x = tf.keras.layers.Embedding(input_vocab_size, d_model, mask_zero=True)(input)
query = tf.keras.layers.Dense(d_model)(x)
value =  tf.keras.layers.Dense(d_model)(x)
key    =  tf.keras.layers.Dense(d_model)(x)
attention = tf.keras.layers.Attention()([query, value, key])
...
```
```Error
ValueError: Attention layer mask must be a list of length 2, namely [query_mask, value_mask]. Given length: 3

**Comment by goldiegadde** [comment]
Marking this as closed as it is fixed with the above PR.
