### ISSUE TITLE
How to use tensorflow python API from the source tree?

### ISSUE THREAD

**Issue by pronobis** [tensorflow/tensorflow#413]
I am trying to setup an efficient development environment for new code inside tensorflow source tree and an external library. Therefore, I am trying to avoid the pip installation process (after every code change) and use the output of bazel build directly in the source tree. In particular, I need access to the Python API from the external library. Can that be accomplished?

**Comment by vrv** [comment]
I'm not entirely sure, this might be a better question for the bazel team at github.com/bazelbuild/bazel.  Hopefully the use of 'bazel' isn't viral.

**Comment by zheng-xq** [comment]
Can you set up your binary similar to any of the checked-in model? 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/image/alexnet/BUILD

You can run either as: 
bazel run -c opt --config=cuda third_party/tensorflow/models/image/alexnet:alexnet_benchmark

Or 
bazel build -c opt --config=cuda third_party/tensorflow/models/image/alexnet:alexnet_benchmark
bazel-bin/third_party/tensorflow/models/image/alexnet/alexnet_benchmark

**Comment by pronobis** [comment]
That sounds like a good suggestion. Will check it out.

**Comment by akuz** [comment]
@pronobis - Did that work well for you?

**Comment by akuz** [comment]
I was wondering if running the following after building would do the trick (while in tensorflow root folder):

python ./tensorflow/tools/pip_package/setup.py develop

**Comment by akuz** [comment]
Ok it doesn't work, but something that would do the trick would be so useful...

**Comment by nikitakit** [comment]
I think I have a setup for development without rebuilding the wheel / re-installing it after every change. It does, however, require re-running the bazel build every time the C++ file change, or if any python files are added or deleted.

From the tensorflow repo root:
```sh
bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
mkdir _python_build
cd _python_build

ln -s ../bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/* 
ln -s ../tensorflow/tools/pip_package/* .
python setup.py develop
```

**Comment by martinwicke** [comment]
This is great! I'll make this part of os_setup.md if you don't mind (or you can)?

**Comment by nikitakit** [comment]
@martinwicke You can go ahead and do that
