### ISSUE TITLE
Confusing documentation for tf.image.rgb_to_yuv

### ISSUE THREAD

**Issue by tonychenxyz** [tensorflow/tensorflow#41300]
The documentation for tf.image.rgb_to_yuv says "Outputs a tensor of the same shape as the images tensor, containing the YUV value of the pixels. The output is only well defined if the value in images are in [0,1]." Does that mean the RGB values should be [0,1]?

If so, the usage example added confusion:
```
x = [[[1.0, 2.0, 3.0],
      [4.0, 5.0, 6.0]],
    [[7.0, 8.0, 9.0],
      [10.0, 11.0, 12.0]]]
tf.image.rgb_to_yuv(x)
```

Clearly, x does not lie in [0,1]

**Comment by NullOsama** [comment]
There are two ways of representing an image: 
1. [0, 255] pixel values range.
2. [0, 1] (as float) pixel values range
So you need to convert the input image into a float [0, 1] range.

**Comment by jvishnuvardhan** [comment]
@tonychenxyz [Here](https://www.tensorflow.org/api_docs/python/tf/image/rgb_to_yuv?version=nightly) is the link to the `tf-nightly` doc. The usage example was updated in the `tf-nightly`. It clearly says that 

> The output is only well defined if the value in images are in [0,1].

Please verify and close the issue if this was resolved for you. thanks!
