### ISSUE TITLE
Resnet weights link 

### ISSUE THREAD

**Issue by pn12** [tensorflow/tensorflow#41301]
Where can I find the Resnet50 pretrained weights to download ?

Thanks

**Comment by ymodak** [comment]
ResNet 50 weights can be downloaded from [here](https://github.com/fchollet/deep-learning-models/releases/tag/v0.2)

**Comment by pn12** [comment]
These are old versions, prompting errors while code run.
Please check.

**Comment by ymodak** [comment]
You may try https://github.com/tensorflow/models/blob/master/research/slim/README.md#pre-trained-models

**Comment by pn12** [comment]
Switching to pytorch, keras seems to have quite a few version issues while installing effnet as well.
Thanks everybody for quick fixes.

> You may try https://github.com/tensorflow/models/blob/master/research/slim/README.md#pre-trained-models
> [ResNet 50 weights](https://storage.googleapis.com/tensorflow/keras-applications/resnet/resnet50_weights_tf_dim_ordering_tf_kernels.h5)



> You may try https://github.com/tensorflow/models/blob/master/research/slim/README.md#pre-trained-models
> [ResNet 50 weights](https://storage.googleapis.com/tensorflow/keras-applications/resnet/resnet50_weights_tf_dim_ordering_tf_kernels.h5)

They are prompting size shape errorrs.

**Comment by Saduf2019** [comment]
@pn12 
Can you please share simple stand alone code for us to replicate the issue faced or if possible please share a colab gist for us to analyse.
