### ISSUE TITLE
ValueError: Tensor-typed variable initializers must either be wrapped in an init_scope or callable (e.g., `tf.Variable(lambda : tf.truncated_normal([10, 40]))`) when building functions.

### ISSUE THREAD

**Issue by Isabellaleesln** [tensorflow/tensorflow#41306]
### Version ###

OS Platform
Python 3.7.6
tensorflow 2.2.0
keras 2.3.0-tf
mem 64247.95703125
cpu 16

### Try to reproduce this work ###
https://www.kaggle.com/devang/transfer-learning-with-keras-and-mobilenet-v2

## The error occurs when I try to define layers and compile model using: ##
---------------------------------------------------------------------------------------------------------------------------------------------
epochs = 100
batch_size = 150
testsplit = .2
targetx = 224
targety = 224
learning_rate = 0.0001
classes = 120
seed = random.randint(1, 1000)

shape=(targetx, targety, 3))

x = base_model.output
x = GlobalAveragePooling2D()(x)

x = Dropout(rate = .2)(x)
x = BatchNormalization()(x)
x = Dense(1280, activation='relu', kernel_initializer=glorot_uniform(seed), bias_initializer='zeros')(x)

x = Dropout(rate = .2)(x)
x = BatchNormalization()(x)
predictions = Dense(classes, activation='softmax', kernel_initializer='random_uniform', bias_initializer='zeros')(x)

model = Model(inputs=base_model.input, outputs=predictions)

---------------------------------------------------------------------------------------------------------------------------------------------
### Error report ###

---------------------------------------------------------------------------------------------------------------------------------------------
ValueError Traceback (most recent call last)
in
12 """
13
---> 14 x = Dense(1280, activation='relu', kernel_initializer=glorot_uniform(seed), bias_initializer='zeros')(x)
15 x = Dropout(rate = .2)(x)
16 x = BatchNormalization()(x)

/apps/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py in symbolic_fn_wrapper(*args, **kwargs)
73 if _SYMBOLIC_SCOPE.value:
74 with get_graph().as_default():
---> 75 return func(*args, **kwargs)
76 else:
77 return func(*args, **kwargs)

/apps/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/keras/engine/base_layer.py in call(self, inputs, **kwargs)
461 'You can build it manually via: '
462 'layer.build(batch_input_shape)')
--> 463 self.build(unpack_singleton(input_shapes))
464 self.built = True
465

/apps/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/keras/layers/core.py in build(self, input_shape)
893 name='kernel',
894 regularizer=self.kernel_regularizer,
--> 895 constraint=self.kernel_constraint)
896 if self.use_bias:
897 self.bias = self.add_weight(shape=(self.units,),

/apps/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/keras/engine/base_layer.py in add_weight(self, name, shape, dtype, initializer, regularizer, trainable, constraint)
280 dtype=dtype,
281 name=name,
--> 282 constraint=constraint)
283 if regularizer is not None:
284 with K.name_scope('weight_regularizer'):

/apps/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py in variable(value, dtype, name, constraint)
618 """
619 v = tf_keras_backend.variable(
--> 620 value, dtype=dtype, name=name, constraint=constraint)
621 if hasattr(value, 'tocoo'):
622 v._keras_shape = value.tocoo().shape

/apps/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/keras/backend.py in variable(value, dtype, name, constraint)
843 dtype=dtypes_module.as_dtype(dtype),
844 name=name,
--> 845 constraint=constraint)
846 if isinstance(value, np.ndarray):
847 v._keras_shape = value.shape

/apps/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/ops/variables.py in call(cls, *args, **kwargs)
259 return cls._variable_v1_call(*args, **kwargs)
260 elif cls is Variable:
--> 261 return cls._variable_v2_call(*args, **kwargs)
262 else:
263 return super(VariableMetaclass, cls).call(*args, **kwargs)

/apps/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/ops/variables.py in _variable_v2_call(cls, initial_value, trainable, validate_shape, caching_device, name, variable_def, dtype, import_scope, constraint, synchronization, aggregation, shape)
253 synchronization=synchronization,
254 aggregation=aggregation,
--> 255 shape=shape)
256
257 def call(cls, *args, **kwargs):

/apps/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/ops/variables.py in (**kws)
234 shape=None):
235 """Call on Variable class. Useful to force the signature."""
--> 236 previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)
237 for _, getter in ops.get_default_graph()._variable_creator_stack: # pylint: disable=protected-access
238 previous_getter = _make_getter(getter, previous_getter)

/apps/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py in default_variable_creator_v2(next_creator, **kwargs)
2645 synchronization=synchronization,
2646 aggregation=aggregation,
-> 2647 shape=shape)
2648
2649

/apps/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/ops/variables.py in call(cls, *args, **kwargs)
261 return cls._variable_v2_call(*args, **kwargs)
262 else:
--> 263 return super(VariableMetaclass, cls).call(*args, **kwargs)
264
265

/apps/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py in init(self, initial_value, trainable, collections, validate_shape, caching_device, name, dtype, variable_def, import_scope, constraint, distribute_strategy, synchronization, aggregation, shape)
1432 aggregation=aggregation,
1433 shape=shape,
-> 1434 distribute_strategy=distribute_strategy)
1435
1436 def _init_from_args(self,

/apps/opt/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py in _init_from_args(self, initial_value, trainable, collections, caching_device, name, dtype, constraint, synchronization, aggregation, distribute_strategy, shape)
1515 if isinstance(initial_value, ops.Tensor) and hasattr(
1516 initial_value, "graph") and initial_value.graph.building_function:
-> 1517 raise ValueError("Tensor-typed variable initializers must either be "
1518 "wrapped in an init_scope or callable "
1519 "(e.g., `tf.Variable(lambda : "

ValueError: Tensor-typed variable initializers must either be wrapped in an init_scope or callable (e.g., tf.Variable(lambda : tf.truncated_normal([10, 40]))) when building functions. Please file a feature request if this restriction inconveniences you.

---------------------------------------------------------------------------------------------------------------------------------------------
I had a few go on changing the 'seed' to the following:

- [1, seed]
- tf.constant(np.random.rand(2, 2))
- tf.keras.Variable(lambda : tf.truncated_normal([1, seed]))

However, I still can't manage to convert 'seed' to a tensor.

Can anyone help me please?

Any suggestions/feedback will be much appreciated!

**Comment by Saduf2019** [comment]
@Isabellaleesln 
I ran the code shared, it seems incomplete.Please provide with code such that it can replicate the issue faced, [gist of the code shared](https://colab.research.google.com/gist/Saduf2019/134b453e41309630ac0f0052d330fe8d/untitled272.ipynb).

With respect to the error faced please refer to these issues and let us know if it helps:
[link](https://stackoverflow.com/questions/59229898/tensor-typed-variable-initializers-must-either-be-wrapped-in-an-init-scope-or-ca) [link1](https://github.com/shamangary/LOUPE_Keras/issues/1)

**Comment by Isabellaleesln** [comment]
Hi @Saduf2019 Thank you for response =)
Please find the full code here: https://www.kaggle.com/devang/transfer-learning-with-keras-and-mobilenet-v2. 

Regards,

**Comment by Isabellaleesln** [comment]
Hi @Saduf2019  I have looked at your links. [link1](https://stackoverflow.com/questions/59229898/tensor-typed-variable-initializers-must-either-be-wrapped-in-an-init-scope-or-ca) seems not the same as mine. 

You can find the remaining code of your first [link](https://colab.research.google.com/gist/Saduf2019/134b453e41309630ac0f0052d330fe8d/untitled272.ipynb) [Here](https://www.kaggle.com/devang/transfer-learning-with-keras-and-mobilenet-v2)

Thank you for looking at this issue!

**Comment by Saduf2019** [comment]
@Isabellaleesln
Please share simple stand alone indented code to replicate the issue or please share a colab gist with the error faced for us to analyse.

**Comment by Isabellaleesln** [comment]
@Saduf2019 
Please find the _**full mobilenet_v2 model code**_ and **_related weights_** in the attached below. Thanks.

[mobilenet_v2_model_weights.zip](https://github.com/tensorflow/tensorflow/files/4915590/mobilenet_v2_model_weights.zip)

**Comment by gowthamkpr** [comment]
@Isabellaleesln Were you able to solve this problem?
