### ISSUE TITLE
[DLPack] DLPack doesn't work with int32 on gpu

### ISSUE THREAD

**Issue by VoVAllen** [tensorflow/tensorflow#41307]
Reproduce code: https://colab.research.google.com/drive/1kwR_ZVutSot7yA7FqPUvCsKgXcirmNLh?pli=1#scrollTo=UI-LuV7EUick

Error message on my machine:
```python
2020-07-11 14:42:25.598880: E tensorflow/stream_executor/cuda/cuda_driver.cc:1037] failed to enqueue async memcpy from device to host: CUDA_ERROR_INVALID_VALUE: invalid argument; host dst: 0x1abfd2c0; GPU src: 0x1a027e80; size: 12=0xc
2020-07-11 14:42:25.598954: F tensorflow/core/common_runtime/gpu/gpu_util.cc:291] GPU->CPU Memcpy failed
```

It seems the int32 tensor's data pointer is on cpu instead of being on gpu, althought its device is "gpu". Previously as I know there's special case handling for int32 tensor(https://github.com/tensorflow/tensorflow/issues/34071), not sure whether this is related.

And I just found I used constant_op.constant to test dlpacks, which means now it only test the case on cpu since tf.constant always place data on host memory

Do you have any idea on this issue? @sanjoy @alextp

**Comment by sanjoy** [comment]
Looks like `.device` returns the [device of the operation](https://github.com/tensorflow/tensorflow/blob/0d7e40f0dba759a54a8ee4e4c2a96e05937e14c2/tensorflow/python/framework/ops.py#L420) which is not correct for operations with `HostMemory` outputs, like [int32 identity](https://github.com/tensorflow/tensorflow/blob/0d7e40f0dba759a54a8ee4e4c2a96e05937e14c2/tensorflow/core/kernels/identity_op.cc#L162).

We can probably add a method that returns the true devices for a given `TFE_TensorHandle` (`Tensor`s know how to deallocate themselves so this information is in principle already present), but this is a high impact API change and we need to think this through.

Also, @VoVAllen , what should be the behavior of `to_dlpack` if it is passed a non-GPU tensor?

**Comment by sanjoy** [comment]
CC @jaingaurav

**Comment by VoVAllen** [comment]
For DLPack, there's a ctx field indicating which device this pointer belongs to. 

Two things I think needed:
- Be able to get the real device of the pointer
  - I believe there should be such API in tensorflow now, because operator needs to know the pointer's location for further computation.
- Be able to explicitly copy int32 tensor to gpu
  - Currently our workaround is `cast it to uint32 -> copy to gpu ->cast it back to int32`

I understand why int32 tensor are on cpu if using tf.constant, but why it needs exception in `tf.identity` also that still not copying it to gpu?

**Comment by sanjoy** [comment]
> * I believe there should be such API in tensorflow now, because operator needs to know the pointer's location for further computation.

I agree, I have filed a Google-internal bug about this.

> but why it needs exception in `tf.identity` also that still not copying it to gpu?

The `int32` `Identity` kernel [explicitly places](https://github.com/tensorflow/tensorflow/blob/ac3456f3ad9ab8af38d933f823aa665358f7c4fe/tensorflow/core/kernels/identity_op.cc#L134) its input and output on the host, via a `HostMemory` annotation.

**Comment by VoVAllen** [comment]
Any updates on this issue?

**Comment by sanjoy** [comment]
Internally we decided that this is a documentation bug.  The physical device of a `Tensor` can be accessed via the `backing_device` property, not the `device` property.

**Comment by VoVAllen** [comment]
Is there any API to get the `backing_device` I can use to fix the bug in dlpack for now? Currently I use https://github.com/tensorflow/tensorflow/blob/3ace29966b79711b848a76135248c743b2fdeace/tensorflow/c/eager/dlpack.cc#L112, which seems the op device instead of backing_devicce

**Comment by alextp** [comment]
Just call BackingDeviceName instead of DeviceName
