### ISSUE TITLE
AttributeError: module 'tensorflow.python.ops.special_math_ops' has no attribute 'bessel_i0e'

### ISSUE THREAD

**Issue by attianopp** [tensorflow/tensorflow#41315]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64-bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version: 2.2.0
- Python version: 3.7.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: AMD RX-580

**Describe the problem**
AttributeError: module 'tensorflow.python.ops.special_math_ops' has no attribute 'bessel_i0e' arises when trying to use tensorflow's object detection API to fine-tune EfficientDet to detect a custom class I created a dataset and matching test/train TFrecord files.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. I followed the instructions on https://github.com/tensorflow/models/tree/master/official#running-the-models under "How to get started with the official models" to install dependencies, clone the models repo, and add the models folder to my python path. The last part I accomplished by adding a sys.path.append(r'C:\Users\user\models') line to the beginning of model_main_tf2.py, which is the file I was under the impression runs the training loop. I also installed protoc-3.12.3-win64.zip and ran "C:/Program Files/protoc/bin/protoc" object_detection/protos/*.proto --python_out=. in the models directory.

2. I downloaded and configured the config files for EfficientDet D7 from https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md to point to my TFrecord test/train files, the checkpoint/ckpt-0 file and label_map.txt files.

3. I ran the following command in an anaconda powershell which prompted the AttributeError: module 'tensorflow.python.ops.special_math_ops' has no attribute 'bessel_i0e':

python model_main_tf2.py --model_dir=C:\Users\user\efficientdet_d7_coco17_tpu-32\training --num_train_steps=10000 --sample_1_of_n_eval_examples=1 --pipeline_config_path=C:\Users\user\efficientdet_d7_coco17_tpu-32\pipeline.config --alsologtostderr 

I also tried it with and without the --checkpoint_dir = C:\Users\user\efficientdet_d7_coco17_tpu-32\checkpoint flag

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

(base) C:\Users\user\models\research\object_detection>python model_main_tf2.py --model_dir=C:\Users\user\efficientdet_d7_coco17_tpu-32\training --num_train_steps=10000 --sample_1_of_n_eval_examples=1 --pipeline_config_path=C:\Users\user\efficientdet_d7_coco17_tpu-32\pipeline.config --alsologtostderr
2020-07-12 02:03:31.351897: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-07-12 02:03:31.356039: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "model_main_tf2.py", line 35, in <module>
    import tensorflow.compat.v2 as tf
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 74, in <module>
    from tensorflow.python.ops.standard_ops import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\standard_ops.py", line 27, in <module>
    from tensorflow.python.training.experimental import loss_scaling_gradient_tape
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\experimental\loss_scaling_gradient_tape.py", line 21, in <module>
    from tensorflow.python.distribute import distribution_strategy_context
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\distribute\__init__.py", line 28, in <module>
    from tensorflow.python.distribute.experimental import collective_all_reduce_strategy
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\distribute\experimental\__init__.py", line 25, in <module>
    from tensorflow.python.distribute import tpu_strategy
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\distribute\tpu_strategy.py", line 28, in <module>
    from tensorflow.compiler.xla.experimental.xla_sharding import xla_sharding
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\compiler\xla\experimental\xla_sharding\xla_sharding.py", line 23, in <module>
    from tensorflow.compiler.tf2xla.python import xla as tf2xla
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\compiler\tf2xla\python\xla.py", line 107, in <module>
    bessel_i0e = _unary_op(special_math_ops.bessel_i0e)
AttributeError: module 'tensorflow.python.ops.special_math_ops' has no attribute 'bessel_i0e'

Please let me know if there is any other info I can provide.

**Comment by Saduf2019** [comment]
@attianopp 
Can you please confirm if this is a build on anaconda.

Please refer to these issues and let us know if it helps:
#38589 [link](https://github.com/tensorflow/tensorflow/issues/25517#issuecomment-465844967)
 [link](https://github.com/keras-team/keras/issues/12118#issuecomment-459333540)

**Comment by attianopp** [comment]
Yes this is an anaconda build, but installed using pip in the anaconda prompt. The second link seems to have been fruitful, un-installing and re-installing tensorflow/keras. Thanks
