### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot add tensor to the batch: number of elements does not match. Shapes are: [tensor]: [2], [batch]: [5]

### ISSUE THREAD

**Issue by SlowMonk** [tensorflow/tensorflow#41316]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.2
- Python version: 3.7.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

`tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot add tensor to the batch: number of elements does not match. Shapes are: [tensor]: [2], [batch]: [5]`

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```

from datasets import PascalVOCDataset

class PascalVOCDataset(Dataset):
    """
    A PyTorch Dataset class to be used in a PyTorch DataLoader to create batches.
    """

    def __init__(self, data_folder, split, keep_difficult=False):
        """
        :param data_folder: folder where data files are stored
        :param split: split, one of 'TRAIN' or 'TEST'
        :param keep_difficult: keep or discard objects that are considered difficult to detect?
        """
        self.split = split.upper()

        assert self.split in {'TRAIN', 'TEST'}

        self.data_folder = data_folder
        self.keep_difficult = keep_difficult

        # Read data files
        with open(os.path.join(data_folder, self.split + '_images.json'), 'r') as j:
            self.images = json.load(j)
        with open(os.path.join(data_folder, self.split + '_objects.json'), 'r') as j:
            self.objects = json.load(j)
        print('dataset_path->',os.path.join(data_folder, self.split + '_images.json'))

        assert len(self.images) == len(self.objects)

    def __getitem__(self, i):
        # Read image
        #print('get_item')
        image = Image.open(self.images[i], mode='r')
        image = image.convert('RGB')

        #print('images_shape->',np.array(image).shape)

        # Read objects in this image (bounding boxes, labels, difficulties)
        objects = self.objects[i]
        #print('image->',image)
        #print('objects[boxes]->',objects['boxes'])
        boxes = torch.FloatTensor(objects['boxes'])  # (n_objects, 4)
        labels = torch.LongTensor(objects['labels'])  # (n_objects)
        difficulties = torch.ByteTensor(objects['difficulties'])  # (n_objects)

        # Discard difficult objects, if desired
        if not self.keep_difficult:
            boxes = boxes[1 - difficulties]
            labels = labels[1 - difficulties]
            difficulties = difficulties[1 - difficulties]

        # Apply transformations
        #print('dataset_boxes->',boxes)
        image, boxes, labels, difficulties = transform(image, boxes, labels, difficulties, split=self.split)

        return image, boxes, labels, difficulties

 # Custom dataloaders
    train_dataset = PascalVOCDataset(data_folder,
                                     split='train',
                                     keep_difficult=keep_difficult)

def run_train(dataset, num_epochs=1):
    start_time = time.perf_counter()
    print('run_train')
    model = SSD(n_classes=20)
    criterion = MultiBoxLoss(priors_cxcy=model.priors_cxcy)
    print('dataset->',dataset)

    for _ in tf.data.Dataset.range(num_epochs):
        for idx,(images,boxes,labels) in enumerate(dataset): # (batch_size (N), 300, 300, 3)
            print('=========================================================')
            images = np.array(images)
            labels = np.array(labels)
            boxes = np.array(list(boxes))
            print('image_shape->', images.shape)
            print('labels_shape->',labels.shape)
            print('boxes_shape->',boxes.shape)

            if isprint: tf.print(type(images), type(labels),images.shape,labels.shape)
            predicted_locs, predicted_socres = model(images)# (N, 8732, 4), (N, 8732, n_classes)
            loss = criterion(predicted_locs,predicted_socres,boxes,labels)
            print('loss->',loss)
            if idx ==10: break
        pass
    tf.print("실행 시간:", time.perf_counter() - start_time)
def train():
    print('train')
    print(tf.__version__)
    batch_size= 8
    images,boxes,labels,difficulties,new_boxes= PascalVOCDataset()
    new_boxes = list(new_boxes)


    boxes = tf.ragged.constant(boxes)
    labels = tf.ragged.constant(labels)
    new_boxes = tf.ragged.constant(new_boxes)

    print('boxes->',boxes.shape)
    print('labels->',labels.shape)
    print('images->', np.array(images).shape)

    dataset = tf.data.Dataset.from_tensor_slices((images,new_boxes,labels))
    run_train(dataset.map(resize_image_bbox, num_parallel_calls=tf.data.experimental.AUTOTUNE).batch(batch_size).prefetch(tf.data.experimental.AUTOTUNE))

def main():
    train()
if __name__ =='__main__':
    main()

```

**Comment by amahendrakar** [comment]
@SlowMonk,
On running the code I am facing an error stating `NameError: name 'PascalVOCDataset' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/2404b379932ae206f2776e152ad64ea7/41316.ipynb#scrollTo=dDXsAE63p9ld). 

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and the dataset you are using. Thanks!

Also, please check [this comment](https://github.com/tensorflow/tensorflow/issues/34544#issuecomment-581446568) from a similar issue and let us know if it helps. Thanks!
