### ISSUE TITLE
reduce_max and maximum give different results for negative infinity

### ISSUE THREAD

**Issue by pronobis** [tensorflow/tensorflow#4131]
Using `tf.maximum` with negative inf inputs as follows:

    tf.maximum(-math.inf, -math.inf).eval()

gives the expected result `-inf`

However, `tf.reduce_max`, on the same inputs:

    tf.reduce_max([-math.inf, -math.inf]).eval()

gives: `-3.40282e+38` which is the min float32.

For positive infinity inputs, both functions result in `inf`.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
I posted this as an SO question first:
http://stackoverflow.com/questions/39211546/bug-in-tensorflow-reduce-max-for-negative-infinity

### Environment info
Operating System: Ubuntu 16.04

Installed version of CUDA and cuDNN: 
```
-rw-r--r-- 1 root root   560184 May 25 17:48 /usr/local/cuda-8.0/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 May 25 17:52 /usr/local/cuda-8.0/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 May 25 17:52 /usr/local/cuda-8.0/lib64/libcudart.so.8.0 -> libcudart.so.8.0.27
-rw-r--r-- 1 root root   394472 May 25 17:48 /usr/local/cuda-8.0/lib64/libcudart.so.8.0.27
-rw-r--r-- 1 root root   737516 May 25 17:48 /usr/local/cuda-8.0/lib64/libcudart_static.a
lrwxrwxrwx 1 root root       13 Jul  4 16:22 /usr/local/cuda-8.0/lib64/libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 root root       17 Jul  4 16:22 /usr/local/cuda-8.0/lib64/libcudnn.so.5 -> libcudnn.so.5.0.5
-rwxr-xr-x 1 root root 78065952 Jul  4 16:22 /usr/local/cuda-8.0/lib64/libcudnn.so.5.0.5
-rw-r--r-- 1 root root 68709594 Jul  4 16:22 /usr/local/cuda-8.0/lib64/libcudnn_static.a

```

Installed from source.

Commit hash: 3cb39956e622b322e43547cf2b6e337020643f21

Bazel:
```
Build label: 0.3.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 10 11:38:23 2016 (1465558703)
Build timestamp: 1465558703
Build timestamp as int: 1465558703

```

**Comment by rmlarsen** [comment]
@pronobis Thanks for the bug report. I have fixed the bug internally at Google and in the open source Eigen repository (https://bitbucket.org/eigen/eigen/commits/741b932c41cebff49c4419b7e0ef9910ef1b2907). We will have to wait until a few unrelated issues are resolved in Eigen before pushing the fix to open source TensorFlow. Stay tuned! :-)

**Comment by rmlarsen** [comment]
@pronobis Update: The issues in Eigen have been resolved and the fix for this issue will be pushed out on Monday.

**Comment by pronobis** [comment]
Great! Thanks!
