### ISSUE TITLE
Tensorflow default supports dynamic preprocessing (e.g. masking).

### ISSUE THREAD

**Issue by MokkeMeguru** [tensorflow/tensorflow#41311]
# Environment
- tensorflow 2.x
- google colab

# Reproducible code
https://colab.research.google.com/gist/MokkeMeguru/8c867b2bbc941cc82e115b9044276afc/test.ipynb

# Problem
if text data preprocessing using the map function, each epoch resets previous preprocessing information.

```python
def encode(text):
    encoded_text = encoder.encode(text.numpy())
    tf.print("raw", encoded_text)
    
    def random_masking(s):
        s = [word if tf.random.uniform([]) > mask_rate else mask_idx for word in s]
        return s

    encoded_text = random_masking(encoded_text)
    tf.print("masked", encoded_text)
    return [encoded_text

def encode_map_fn(text):
    encoded_text = tf.py_function(encode, inp=[text], Tout=(tf.int64))
    encoded_text.set_shape([None])
    return encoded_text

encoder.encode(next(iter(ds)).numpy()

encoded_ds = ds.map(encode_map_fn).padded_batch(3)

print("mask is", mask_idx)

for epoch in range(3):
    print("epoch :", epoch)
    for batch in encoded_ds:
        print(batch)
```
```
mask is 12
epoch : 0
raw [11, 6, 1, 5, 9]
masked [11, 6, 1, 12, 9] # <---------!
...
epoch : 1
raw [11, 6, 1, 5, 9]
masked [11, 6, 12, 12, 9] # <------!
...
```

In some NLP methods, we know static preprocessing (like BERT) and dynamic preprocessing (like RoBERTa) don't have the same performance.

**I want to know whether this dynamic preprocessing is the correct attribute or not.**
And also
**How to keep the preprocessing information**

**Comment by ravikyram** [comment]
@MokkeMeguru 

I have tried in colab with TF 2.2, 2.3-rc1, nightly version(`2.4.0-dev20200712`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/6070d45a1939082f62b9cb8df7a11139/untitled.ipynb).You are seeing the same bahavior?Thanks!

**Comment by MokkeMeguru** [comment]
Yes. It has same problem.

**Comment by sachinprasadhs** [comment]
Tried to reproduce the issue in Tf Nightly 2.6, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/b483514585d014e12c582a84746f61b0/41311.ipynb) and confirm if this is still an issue. Thanks!
