### ISSUE TITLE
tensorflow lite example is not working converting file to tflite model. 

### ISSUE THREAD

**Issue by kotran88** [tensorflow/tensorflow#41318]
what I'm facing is as same as below link

https://github.com/tensorflow/tensorflow/issues/30005

it worked a couple of month ago, but now, it's not working. 
there's gesture calssification listed on example on github and I opened index.html from web folder then I trained to get file. 
but then, how can I convert it to tflite model without collab? 
collab code is not working as link says

**Comment by Saduf2019** [comment]
@kotran88 
Please share a simple standalone code for us to replicate the issue faced and tf version to replicate it.
The issue reported is tensorflow js issue, in that case please open it on [respective repo](https://github.com/tensorflow/tfjs/issues).
