### ISSUE TITLE
 when using keras, report error: Use Eager execution or decorate this function with @tf.function 

### ISSUE THREAD

**Issue by cookingbear** [tensorflow/tensorflow#41329]
I do not think currently tensorflow supports building a tf.keras.Model which contains tf.cond or tf.while_loop. 

I have built a model based on tf2.0 which contains while loop, but I want to save it as a pb file, so I need to use tf.keras.Model to rebuild my model.

I have tried the code below and it reported the error:
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

# the code
import tensorflow as tf
layers = tf.keras.layers
a = layers.Input(shape=tf.TensorShape([]), dtype=tf.bool)
b = a[0]
c = tf.cond(b, lambda: 1, lambda: 0)
print (c)

the tensorflow version I used: 
v2.0.0-69-g765ac8d 2.0.1

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2, 2.3-rc1,nightly version and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/eb1e01c6e24448e366bb0ad00aa0b885/untitled111.ipynb).Thanks!

**Comment by gowthamkpr** [comment]
@cookingbear As the error message suggests, you cant use a boolean tensor in tf.cond(). that s the cause of the error.

**Comment by cookingbear** [comment]
> @cookingbear As the error message suggests, you cant use a boolean tensor in tf.cond()

If the stop condition of the while loop depends on the input data length, is there any way to use keras.model to build this kind of model?

**Comment by cookingbear** [comment]
The reason I have this concern is that in eager mode I have built the model successfully which contains while loops in which tensors control the flow. However, for some reason, I have to freeze the model into pb format. To accomplish this work, I thought maybe firstly I should use keras.model to rebuild the model. So the problem arised.

**Comment by nikitamaia** [comment]
Hi @cookingbear, taking a look at issue [#31848](https://github.com/tensorflow/tensorflow/issues/31848) might be helpful, as it seems similar to the problem you're facing. The suggested workaround there is to use a keras [lambda layer](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Lambda). Let me know if this helps.
