### ISSUE TITLE
MethodChannel#tflite(23624): Node number 8 (FlexConv2D) failed to prepare. 

### ISSUE THREAD

**Issue by e-shawakri** [tensorflow/tensorflow#41327]
Hey I've trained a custom object detector model using pytorch and convert it into ONNX format then into tflite format.
When I deploy my model into app using the flutter tflite it shows me this error: 

> MethodChannel#tflite(23624): Node number 8 (FlexConv2D) failed to prepare.

How to handle such error?

Please any ML and Flutter expert could help me to solve it?

This is the code that I have used to done the pipeline conversion:

```
from onnx_tf.backend import prepare
import onnx

model_onnx = onnx.load('/mydrive/YOLOv5_Model/app/weights/best_fit.onnx')
tf_rep = prepare(model_onnx, device='cpu')
tf_rep.export_graph('/content/model_tf.pb')

def wrap_frozen_graph(graph_def, inputs, outputs):
    def _imports_graph_def():
        tf.compat.v1.import_graph_def(graph_def, name="")

    wrapped_import = tf.compat.v1.wrap_function(_imports_graph_def, [])
    import_graph = wrapped_import.graph

    return wrapped_import.prune(
        tf.nest.map_structure(import_graph.as_graph_element, inputs),
        tf.nest.map_structure(import_graph.as_graph_element, outputs))

with tf.io.gfile.GFile("/content/model_tf.pb", "rb") as f:
    graph_def = tf.compat.v1.GraphDef()
    loaded = graph_def.ParseFromString(f.read())

frozen_func = wrap_frozen_graph(graph_def=graph_def,
                                inputs=["images:0"],
                                outputs=['output_0:0','output_1:0', 'output_2:0'])

converter = tf.lite.TFLiteConverter.from_concrete_functions([frozen_func])
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tf_lite_model = converter.convert()
open('/content/best_fit.tflite', 'wb').write(tf_lite_model)
```

**Comment by abattery** [comment]
@e-shawakri did you include the aar that enables tf ops?

https://www.tensorflow.org/lite/guide/ops_select#android_aar

**Comment by yyoon** [comment]
> deploy my model into app using the flutter tflite

Can you elaborate this part? What exact plugin were you using?

As @abattery alluded to, since you provided the `tf.lite.OpsSet.SELECT_TF_OPS` to the converter, the runtime on which the model runs should support the select TF ops.

**Comment by yyoon** [comment]
We can't help you further without knowing what exact method you used for integrating TFLite with Flutter.
Are you using this package? https://pub.dev/packages/tflite_flutter

Also, could you share your project, if possible? Is it available on GitHub? Seeing the actual project configuration would be helpful.

**Comment by Saduf2019** [comment]
@e-shawakri 
Please update as per above comment.
