### ISSUE TITLE
Doc error for `tf.linalg.trace`

### ISSUE THREAD

**Issue by we-taper** [tensorflow/tensorflow#41323]
I think the doc-string [here](https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/ops/math_ops.py#L2758):
```python
  `output[i, j, k, ..., l] = trace(x[i, j, i, ..., l, :, :])`
```

should be:

```python
  `output[i, j, k, ..., l] = trace(x[i, j, k, ..., l, :, :])`
```

**Comment by yil532** [comment]
Hi, Can I create a PR to fix this?

**Comment by yil532** [comment]
PR is here https://github.com/tensorflow/tensorflow/pull/41348
@jvishnuvardhan

**Comment by jvishnuvardhan** [comment]
Closing this issue as this was resolved. The corresponding PR was merged already. Thanks!
