### ISSUE TITLE
using 3.2GB ram for the simplest mnist model

### ISSUE THREAD

**Issue by faruknane** [tensorflow/tensorflow#41321]
I create the simplest model, but it uses so much ram. Can you help this issue?

**System information**
- Cuda 10.1
- Gtx 1050 ti
- Windows 10 platform
- Tensorflow-gpu 2.2.0
- keras 2.4.3

**Describe the current behavior**
Using ~3.2GB Video Ram

**Describe the expected behavior**
Using ~300MB Video Ram

**Code**
```
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

import keras
from keras.datasets import mnist
from keras.models import Sequential, load_model
from keras.layers.core import Dense, Dropout, Activation, Flatten 
from keras.utils import np_utils
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPool2D, BatchNormalization

# The first time you run this might be a bit slow, since the
# mnist package has to download and cache the data.
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = np.array(x_train, dtype=np.float32)
x_test = np.array(x_test, dtype=np.float32)

x_train /= 255
x_test /= 255
y_train = np_utils.to_categorical(y_train, 10)
y_test = np_utils.to_categorical(y_test, 10)

x_train = x_train.reshape((x_train.shape[0], 28, 28, 1))
x_test = x_test.reshape((x_test.shape[0], 28, 28, 1))

print(x_train.shape) # (60000, 28, 28)
print(y_train.shape) # (60000,)

model = Sequential()
#model.add(Conv2D(32, kernel_size=(3, 3), padding='valid', activation='relu', kernel_initializer='he_normal', input_shape=(28,28, 1)))
#model.add(MaxPool2D((2, 2)))
#model.add(Conv2D(64, kernel_size=(3, 3), activation='relu', kernel_initializer='he_normal'))
#model.add(MaxPool2D((2, 2)))
#model.add(Conv2D(128, kernel_size=(3, 3), activation='relu', kernel_initializer='he_normal'))
#model.add(MaxPool2D((2, 2)))
#model.add(Conv2D(256, kernel_size=(1, 1), activation='relu', kernel_initializer='he_normal'))
model.add(Flatten())
model.add(Dense(30, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.25))
model.add(Dense(10, activation='softmax'))
#model.summary()
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
```

![image](https://user-images.githubusercontent.com/37745467/87245731-7229ef00-c450-11ea-9bcf-cd5703acfbb3.png)

//EDIT: More info
I had cuda 10.2 installed in my computer. I installed keras and tensorflow. It didn't work at the beginning because tf needs CUDA 10.1. Then I tried to uninstall cuda, reinstalling cuda 10.1. It failed couple times etc. Finally I was able to install cuda 10.1 and tensorflow. I don't know if this is related with the current memory issue.

**Comment by Saduf2019** [comment]
@faruknane 
Please confirm if [this gist](https://colab.research.google.com/gist/Saduf2019/8546222f759b6adbb288517166584d17/untitled279.ipynb) confirms your issue.

**Comment by faruknane** [comment]
Yes, exactly @Saduf2019 
![image](https://user-images.githubusercontent.com/37745467/87550154-6b50e580-c6b7-11ea-917a-827c4c00bf67.png)

**Comment by ymodak** [comment]
I tried your example in google colab and I see 1.27 gb ram usage.
<img width="212" alt="Screen Shot 2020-07-15 at 12 46 06 PM" src="https://user-images.githubusercontent.com/42785357/87588831-2a49d880-c699-11ea-9df9-25a650446240.png">

You may try again by closing all the applications and rebooting your system.

**Comment by faruknane** [comment]
@ymodak I have cudnn64_7.dll and Cuda 10.1 installed. I don't know what's wrong. But I think it's decreasing the performance. On my PC, it uses 3.2 gib GPU ram. It's not about the apps that are running. When I restart the kernel of the notebook, GPU memory is 77mb. When I run the notebook, the memory usage is 3.2gib. 

I only did install TensorFlow-GPU and Keras packages. Do you have any idea what's the issue about?

**Comment by faruknane** [comment]
At least can you guide me on how to remove all and reinstall them proper and successfully?

**Comment by ymodak** [comment]
I see you are using anaconda to install TF.
For installing TF with conda you may raise a request on https://github.com/ContinuumIO/anaconda-issues/issues
