### ISSUE TITLE
ValueError: quantized_dimension must be in range [0, 1). Was 3.

### ISSUE THREAD

**Issue by IlkayW** [tensorflow/tensorflow#41324]
I am trying to load a tflite model using the following python code:
````
import tensorflow as tf #version=2.0.0
tf.lite.Interpreter(model_path="model.tflite")
````
with the following error message:
````
ValueError: quantized_dimension must be in range [0, 1). Was 3.
````
Can anyone help me to solve this problem?

**Comment by Saduf2019** [comment]
@IlkayW 
Please refer to below links and let us know if it helps:
[link](https://stackoverflow.com/questions/57234308/edge-tpu-compiler-error-quantized-dimension-must-be-in-range-0-1-was-3) [link1](https://github.com/tensorflow/tensorflow/issues/27880) [link2](https://www.thetopsites.net/article/58082806.shtml) [link3](https://stackoom.com/question/3s9G0/%E8%BE%B9%E7%BC%98TPU%E7%BC%96%E8%AF%91%E5%99%A8-%E9%94%99%E8%AF%AF-quantized-dimension%E5%BF%85%E9%A1%BB%E5%9C%A8-%E8%8C%83%E5%9B%B4%E5%86%85-%E6%98%AF)
