### ISSUE TITLE
Shuffling then zip tf.data.Dataset

### ISSUE THREAD

**Issue by mathieuorhan** [tensorflow/tensorflow#41334]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: None
- GPU model and memory: None

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When applying shuffling => warped copy => zip, shuffling is applied after the warping. 

**Describe the expected behavior**
I would expect it to happen before the warping.

**Standalone code to reproduce the issue**
```
import tensorflow as tf
master = tf.data.Dataset.range(10)
master = master.shuffle(10)
warped = master.map(lambda x: -x)
dataset = tf.data.Dataset.zip((master, warped))
list(dataset.as_numpy_iterator())
```
We get
```
[(3, -1),
 (7, -9),
 (4, -2),
 (9, -5),
 (5, -4),
 (6, 0),
 (1, -8),
 (0, -3),
 (2, -6),
 (8, -7)]
```
When something like this was expected:
```
[(7, -7),
 (9, -9),
 (6, -6),
 (1, -1),
 (3, -3),
 (5, -5),
 (4, -4),
 (0, 0),
 (2, -2),
 (8, -8)]
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@mathieuorhan,
To get the excepted output, add the `reshuffle_each_iteration=False` argument to the `shuffle` function. Please check this [gist](https://colab.research.google.com/gist/amahendrakar/6d38a8aa489ae215ce1da2d6c95a50b1/41334.ipynb) for reference.

For more information, please take a look at these similar issues [#27680](https://github.com/tensorflow/tensorflow/issues/27680#issuecomment-517747300
), [#35682](https://github.com/tensorflow/tensorflow/issues/35682#issuecomment-573251373
). Thanks!

**Comment by mathieuorhan** [comment]
Thank you @amahendrakar. 
After reading your links and the docs, I still don't get this `reshuffle_each_iteration` option. I only iterate the dataset once, so it looks like it's unrelated to the issue, except it isn't. Here is the documentation:

> A boolean, which if true indicates that the dataset should be pseudorandomly reshuffled each time it is iterated over.

So this is what I would expect:
```
>>> import tensorflow as tf
>>> master = tf.data.Dataset.range(10)
>>> master = master.shuffle(10, reshuffle_each_iteration=False)
>>> warped = master.map(lambda x: -x)
>>> dataset = tf.data.Dataset.zip((master, warped))
>>> list(dataset.as_numpy_iterator())
 [(7, -7),
 (9, -9),
 (6, -6),
 (1, -1),
 (3, -3),
 (5, -5),
 (4, -4),
 (0, 0),
 (2, -2),
 (8, -8)]
>>> list(dataset.as_numpy_iterator())
 [(4, -4),
(6, -6),
(1, -1),
(7, -7),
(9, -9),
(3, -3),
(5, -5),
(0, 0),
(2, -2),
(8, -8)]
```
```
>>> import tensorflow as tf
>>> master = tf.data.Dataset.range(10)
>>> master = master.shuffle(10, reshuffle_each_iteration=False)
>>> warped = master.map(lambda x: -x)
>>> dataset = tf.data.Dataset.zip((master, warped))
>>> list(dataset.as_numpy_iterator())
 [(7, -7),
 (9, -9),
 (6, -6),
 (1, -1),
 (3, -3),
 (5, -5),
 (4, -4),
 (0, 0),
 (2, -2),
 (8, -8)]
>>> list(dataset.as_numpy_iterator())
 [(7, -7),
 (9, -9),
 (6, -6),
 (1, -1),
 (3, -3),
 (5, -5),
 (4, -4),
 (0, 0),
 (2, -2),
 (8, -8)]
```

**Comment by mathieuorhan** [comment]
@amahendrakar, I just had a similar issue, which is related to zip, not shuffle, as I first thought. Same system setup.

```
import tensorflow as tf
master = tf.data.Dataset.range(5)
master = master.map(lambda x: tf.cast(x, tf.float32) + tf.random.uniform(()) /10)
warped = master.map(lambda x: -x)
data = tf.data.Dataset.zip((master, warped))
list(data.as_numpy_iterator())
```

In my case, I'm warping images, then creating pairs (master, warped) using zip. I would like to apply image augmentations prior to the warping, something I cannot do, as the augmentation is sometimes applied to image, sometimes to other, sometimes to both of them.
If it's not a bug, how I am supposed to do this? and why am I getting this result?

**Comment by aaudiber** [comment]
@mathieuorhan,

`tf.data.Dataset` objects don't eagerly compute all of their data. They work like blueprints, where the data is computed on the fly every time you iterate through the dataset. As a result, iterating through the same dataset multiple times could result in different output.

The `Dataset.zip` transformation takes multiple datasets and iterates through them in parallel. If you want to iterate through the input just once, use `map` instead of `zip`:

```
import tensorflow as tf
master = tf.data.Dataset.range(10)
master = master.shuffle(10)
dataset = master.map(lambda x: (x, -x))
list(dataset.as_numpy_iterator())
[(3, -3),
 (9, -9),
 (7, -7),
 (5, -5),
 (2, -2),
 (8, -8),
 (1, -1),
 (4, -4),
 (0, 0),
 (6, -6)]
```

**Comment by mathieuorhan** [comment]
@aabadie, thank you, applying map is so simple I've missed it. Also, thank you for the general explanation. I think tough that zip deserves maybe a bit of documentation to warn about this, for instance quoting you:

> The Dataset.zip transformation takes multiple datasets and iterates through them in parallel. If you want to iterate through the input just once, use map instead of zip

**Comment by chunduriv** [comment]
Closing this issue as it is [answered](https://github.com/tensorflow/tensorflow/issues/41334#issuecomment-662747527) by @aaudiber. Please feel free to reopen the issue if you still have a concern. Thanks!
