### ISSUE TITLE
Keras 2.4.3 does not calculate output shape in reshape layer

### ISSUE THREAD

**Issue by fjhheras** [tensorflow/tensorflow#41338]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- TensorFlow installed from (source or binary): conda
- TensorFlow version (use command below): 2.2.0
- Python version: tested in both 3.7.6 and 3.8.3
- I tested both with a non-gpu version and with cudnn 7.6.5 + cuda10.1_0

**Describe the current behavior**

Output length of a reshape layer with last element of length unknown is marked as None

**Describe the expected behavior**

In previous versions of Keras, it was calculated from the other input shapes

**Standalone code to reproduce the issue**

The following code:
```
import keras
layer = keras.layers.Reshape([5, -1])
k_input = keras.Input((5, 6, 4))
model = keras.Model(inputs = [k_input], outputs = layer(k_input))
model.summary()
```
has different outputs depending on the version. In Keras 2.3.1 the last dimension of output is correctly deduced to be 24:

```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, 5, 6, 4)           0         
_________________________________________________________________
reshape_1 (Reshape)          (None, 5, 24)             0         
=================================================================
```

In Keras 2.4.3 the last dimension of output is None
```
 _________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 5, 6, 4)]         0         
_________________________________________________________________
reshape (Reshape)            (None, 5, None)           0         
=================================================================
```

**Comment by Saduf2019** [comment]
@fjhheras 
Could you please try with tf.keras instead of just keras and let us know if it helps.
I ran the code on tf nightly and it works fine with tf.keras, please refer to [gist](https://colab.research.google.com/gist/Saduf2019/e00caf45925842bc86c8628628ea4ee2/untitled268.ipynb) and confirm.

**Comment by fjhheras** [comment]
With Keras 2.4.3, using tf.keras instead of keras still does not do the trick, I am afraid.

Please note that in the gist that you sent, tf.keras version is 2.4.0 (as shown by putting `print(tf.keras.__version__)` in the notebook), and thus earlier than the version I am having problems with (2.4.3)

**Comment by ymodak** [comment]
Is this still an issue? Can you try executing your code in a virtual environment?
Works fine with keras 2.4.3 see the [gist].(https://colab.research.google.com/gist/ymodak/b889199dd9bc61bbd3321b9543d1676f/github_issue_41338.ipynb)

I also tried in my local with python 3.7.6 and keras 2.4.3.
See attached pycharm console screenshot.

<img width="548" alt="Screen Shot 2020-08-06 at 12 09 08 PM" src="https://user-images.githubusercontent.com/42785357/89572185-a4273a80-d7dd-11ea-8519-43b6b6b372c2.png">
