### ISSUE TITLE
ImportError : cannot import name 'context from 'tensorflow.python.eager'

### ISSUE THREAD

**Issue by SSSUBB** [tensorflow/tensorflow#41339]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version: tensorflow 2.0.0
- Python version: python 3.7.7
- Installed using virtualenv? pip? conda?: pip

**Describe the problem**

cannot import keras. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

import keras

Using TensorFlow backend.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-88d96843a926> in <module>
----> 1 import keras

C:\Python\anaconda3\lib\site-packages\keras\__init__.py in <module>
      1 from __future__ import absolute_import
      2
----> 3 from . import utils
      4 from . import activations
      5 from . import applications

C:\Python\anaconda3\lib\site-packages\keras\utils\__init__.py in <module>
      4 from . import data_utils
      5 from . import io_utils
----> 6 from . import conv_utils
      7 from . import losses_utils
      8 from . import metrics_utils

C:\Python\anaconda3\lib\site-packages\keras\utils\conv_utils.py in <module>
      7 from six.moves import range
      8 import numpy as np
----> 9 from .. import backend as K
     10
     11

C:\Python\anaconda3\lib\site-packages\keras\backend\__init__.py in <module>
----> 1 from .load_backend import epsilon
      2 from .load_backend import set_epsilon
      3 from .load_backend import floatx
      4 from .load_backend import set_floatx
      5 from .load_backend import cast_to_floatx

C:\Python\anaconda3\lib\site-packages\keras\backend\load_backend.py in <module>
     88 elif _BACKEND == 'tensorflow':
     89     sys.stderr.write('Using TensorFlow backend.\n')
---> 90     from .tensorflow_backend import *
     91 else:
     92     # Try and load external backend.

C:\Python\anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py in <module>
      4
      5 import tensorflow as tf
----> 6 from tensorflow.python.eager import context
      7 from tensorflow.python.framework import device as tfdev
      8 from tensorflow.python.framework import ops as tf_ops

ImportError: cannot import name 'context' from 'tensorflow.python.eager' (unknown location)

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@SSSUBB,
Is there any specific reason you are using TensorFlow v2.0?

Please update TensorFlow to the latest version v2.2 and check if you are facing the same issue. Thanks!

**Comment by nssiw1** [comment]
Hi guys, I have the same issue, any suggestions?

**Comment by nssiw1** [comment]
> @SSSUBB,
> Is there any specific reason you are using TensorFlow v2.0?
> 
> Please update TensorFlow to the latest version v2.2 and check if you are facing the same issue. Thanks!

@amahendrakar , Hi I have updated the Tensorflow to V2.2 and still facing the same issue. Thanks!
