### ISSUE TITLE
faster rcnn training

### ISSUE THREAD

**Issue by Rahul-kateith** [tensorflow/tensorflow#41332]
Everything works fine, just at the end step, training stops.
I user faster rcnn. As soon as I run train.py with all the parameters provided, it stopped training

**Comment by ravikyram** [comment]
@Rahul-kateith 

I think this is more related to models repo.Please, raise an issue in models repo by filling issue template from [here](https://github.com/tensorflow/models/issues/new/choose).Also, please share related code so it helps us in localizing the isue faster.Thanks!
