### ISSUE TITLE
WARNING:tensorflow:11 out of the last 11 via using Keras library

### ISSUE THREAD

**Issue by BestSithInEU** [tensorflow/tensorflow#41347]
Hello all, I'm getting this warning, I wonder why?

>WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_train_function.<locals>.train_function at 0x0000023D1D542C80> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings is likely due to passing python objects instead of tensors. Also, tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. Please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for more details.

My whole code is [here.](https://github.com/BestSithInEU/Warning)

**Comment by amahendrakar** [comment]
@BestSithInEU,
This issue has already been addressed here [#38561](https://github.com/tensorflow/tensorflow/issues/38561#issuecomment-629937796) and looks like it is fixed.

Please update TensorFlow to v2.3.0rc1 and check if you are facing the same issue. Thanks!

**Comment by BestSithInEU** [comment]
It worked thanks.
