### ISSUE TITLE
TensorFlow Lite runtime check doesn't account for bytecode

### ISSUE THREAD

**Issue by faustomorales** [tensorflow/tensorflow#41352]
This line in TensorFlow Lite doesn't consider the possibility that the name of the file could end with `pyc` instead of `py` if the module is compiled to bytecode (e.g., when used by PyInstaller). I can file a PR but wanted to check first if there's a reason why this is the way that it is. Right now, this causes the TensorFlow Lite runtime to try to import full TensorFlow when it's compiled to bytecode, which of course fails.

https://github.com/tensorflow/tensorflow/blob/df56513aa9b004313c2cff818e138d78cd667b67/tensorflow/lite/python/interpreter.py#L28

I would plan to change this to:

```
import os

if not os.path.splitext(__file__)[0].endswith('tflite_runtime/interpreter')
```

Feedback welcome!

**Comment by jdduke** [comment]
Great catch, thanks! @MeghnaNatraj can you take this one?

**Comment by MeghnaNatraj** [comment]
@faustomorales Thank you for catching this bug. Let us know if you've filed a PR, otherwise I'll go ahead and make the update.

**Comment by faustomorales** [comment]
I'm happy to file the PR for this in the next couple of days. Just wanted to file an issue before I assume that this behavior was unintentional. Thanks for the feedback!

**Comment by MeghnaNatraj** [comment]
@faustomorales Whenever you file the PR, feel free to add me as a reviewer for a quicker turnaround time. Thank you.

**Comment by jspaezp** [comment]
@faustomorales

Would a more robust option be to use a try statement to attempt to import the runtime from tensorflow and fall back to tflite_runtime if it fails to load the module? 
What is the rationale behind having the check be done with the file name?

Best,
Sebastian

**Comment by faustomorales** [comment]
> @faustomorales
> 
> 
> 
> Would a more robust option be to use a try statement to attempt to import the runtime from tensorflow and fall back to tflite_runtime if it fails to load the module? 
> 
> What is the rationale behind having the check be done with the file name?
> 
> 
> 
> Best,
> 
> Sebastian 

Switching to a try/catch seems more idiomatc (ask forgiveness, not permission) but would result in TensorFlow getting used if a user has installed TensorFlow *and* the TFLite runtime in the same environment. In the best case, this causes surprising behavior (the TFLite runtime would rely on TensorFlow when it was intended to operate independently). In the worst case, there could be an API mismatch between TFLite and TensorFlow. For those reasons, I think it would be wise to stick with the path check. Let me know if I've missed something!

**Comment by jspaezp** [comment]
@faustomorales thanks for the explanation, really look forward to this patch being released in a stable version (right now I am patching "manually" the file to bundle it in pyinstaller).
Best!
