### ISSUE TITLE
Can't register an optimizer by name: TensorRTOptimizer

### ISSUE THREAD

**Issue by liyinhgqw** [tensorflow/tensorflow#41354]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.15.3+gpu+tensorrt
- Python version:3.6
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): devtoolset7
- CUDA/cuDNN version: 10.0
- GPU model and memory: Tesla V100

**Describe the problem**
We built tensorflow with --config=cuda and --config=tensorrt enabled, but when using TRT converter, it said 
```
2020-07-13 18:15:56.098448: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:247] Registered default graph optimizer: constfold
2020-07-13 18:15:56.098455: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:297] Can't register an optimizer by name: TensorRTOptimizer
2020-07-13 18:15:56.098461: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:292] Registered default graph optimizer: constfold
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```python
import os

os.environ['TF_CPP_MIN_VLOG_LEVEL'] = '2'

import time
import logging
import numpy as np

import tensorflow as tf
print("TensorFlow version: ", tf.__version__)

from tensorflow.python.compiler.tensorrt import trt_convert as trt

logging.getLogger("tensorflow").setLevel(logging.INFO)

SAVED_MODEL_DIR = "hdfs:///smf1/dw2/user/yinl/resnet_v1_fp32_savedmodel_NHWC"
FP32_SAVED_MODEL_DIR = "hdfs:///smf1/dw2/user/yinl/resnet_v1_fp32_savedmodel_NHWC_TRT"

converter = trt.TrtGraphConverter(
    input_saved_model_dir=SAVED_MODEL_DIR,
	  precision_mode=trt.TrtPrecisionMode.FP32)
converter.convert()

converter.save(FP32_SAVED_MODEL_DIR)
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Build script
```
BAZEL_LINKLIBS=-l%:libstdc++.a bazel build -c opt \
      ${CC_OPT_FLAGS} \
      ${TF_CONFIG_ARGS} \
      --config=cuda --config=tensorrt \
      --linkopt -ldl \
      //tensorflow/tools/pip_package:build_pip_package \
      //tensorflow/tools/lib_package:libtensorflow_jni \
      //tensorflow/tools/lib_package:libtensorflow
```

**Comment by liyinhgqw** [comment]
Figured it out. Close it.

**Comment by myunuro** [comment]
@liyinhgqw May I ask how did you resolve this issue?
