### ISSUE TITLE
Why TF-OP runs slower than pure API?

### ISSUE THREAD

**Issue by venuswu** [tensorflow/tensorflow#41363]
![1188470626](https://user-images.githubusercontent.com/3830256/87379019-d61ff500-c5c1-11ea-8bb0-85a03c98b7aa.jpg)

====================

![483313243](https://user-images.githubusercontent.com/3830256/87379023-d7512200-c5c1-11ea-8830-f6822bc13f72.jpg)

The op is made up of several GPU kernels, but I found it runs slower in TF than in pure api, the above two pictures represents the nv prof result for pure api and TF-OP seperately. Obviously, kernels in the pure api runs one by one, but there are more space between kernels in TF-OP.

Why could this happened?

**Comment by amahendrakar** [comment]
@venuswu,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by venuswu** [comment]
@amahendrakar the OP is a custom-OP made by nvidia called FasterTransformer, which is an open source, https://github.com/NVIDIA/DeepLearningExamples/tree/master/FasterTransformer. The TF version I used is 1.14.

**Comment by sanjoy** [comment]
Hi @venuswu,

These gaps the TF timeline are not surprising since TF has overhead above and beyond just calling these APIs.  We can minimize the overhead, but it won't ever be zero.

Do you see the same behavior with recent versions of TF?

**Comment by venuswu** [comment]
Hi @sanjoy,
  I have not tested on recent versions, and I want to know what is the overhead of TF compared with the pure api.

**Comment by venuswu** [comment]
@sanjoy,  May I ask what's the overhead beyond just calling the nvidia API in an OP ?

**Comment by sanjoy** [comment]
> @sanjoy, May I ask what's the overhead beyond just calling the nvidia API in an OP ?

If you're running with a small batch size then the graphs could be coming from the host not being able to keep up with the GPU due to overhead from the framework.  However, it is difficult to say without detailed analysis.

What happens when you increase the batch size?

**Comment by rmothukuru** [comment]
@venuswu,
As per [this comment](https://github.com/tensorflow/tensorflow/issues/41363#issuecomment-659725026),  can you please test it on the **`recent versions`** (**`2.5 or Nightly`**) and let us know if the issue persists? Thanks!
