### ISSUE TITLE
pip install tf-nightly (macOS) installs build dated 20200610

### ISSUE THREAD

**Issue by lutzroeder** [tensorflow/tensorflow#41366]
**System information**
- OS Platform: macOS Catalina 13.1.1 (15609.2.9.1.2)
- TensorFlow installed from (source or binary): pip
- TensorFlow version: tf-nightly
- Python version: 3.8.3 (default, Jul  8 2020, 14:27:55) 
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

Installing `tf-nightly` installs a old build dated from mid-June.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
~: pip3 install tf-nightly
Collecting tf-nightly
  Downloading tf_nightly-2.3.0.dev20200610-cp38-cp38-macosx_10_14_x86_64.whl (165.4 MB)
```

**Comment by Saduf2019** [comment]
@lutzroeder 
Please follow below command and let us know:
pip install tf-nightly==2.4.0.dev20200712

or download the whl file from here:
https://pypi.org/project/tf-nightly/2.4.0.dev20200712/#files

**Comment by lutzroeder** [comment]
@Saduf2019 

```
~/pip install tf-nightly==2.4.0.dev20200712
ERROR: Could not find a version that satisfies the requirement tf-nightly==2.4.0.dev20200712 (from versions: 2.3.0.dev20200605, 2.3.0.dev20200608, 2.3.0.dev20200609, 2.3.0.dev20200610)
ERROR: No matching distribution found for tf-nightly==2.4.0.dev20200712
```

**Comment by Saduf2019** [comment]
@lutzroeder 
Please upgrade pip and try again, can you refer to [this comment](https://github.com/tensorflow/tensorflow/issues/27470#issuecomment-600504369) and install "pip install tf-nightly"  and confirm.

**Comment by lutzroeder** [comment]
Pip is latest. The issue seems to be that `brew` is now using 3.8 and `tf-nightly` has only been building 3.7 since June 10?

```
~: pip install --upgrade pip
Requirement already up-to-date: pip in /usr/local/lib/python3.8/site-packages (20.1.1)
~: pip install tf-nightly==2.4.0.dev20200712
ERROR: Could not find a version that satisfies the requirement tf-nightly==2.4.0.dev20200712 (from versions: 2.3.0.dev20200605, 2.3.0.dev20200608, 2.3.0.dev20200609, 2.3.0.dev20200610)
ERROR: No matching distribution found for tf-nightly==2.4.0.dev20200712
```

**Comment by mihaimaruseac** [comment]
Apparently we had a few missed nightlies. The [most recent ones](https://pypi.org/project/tf-nightly/2.4.0.dev20200715/#files) should support all 3 operating systems and all pythons, except py38 on macos.

The last py38 on macos [has been released successfully on 6/10](https://pypi.org/project/tf-nightly/2.4.0.dev20200715/#files)

We will investigate why there is no recent macos/py38 release and fix.

**Comment by mihaimaruseac** [comment]
During a refactoring we accidentally stopped the job that was doing this particular release. We triggered the job manually and made the needed changes so that from tomorrow the job will run at the proper time.

Apologies again for the breakage and thanks for pointing this out

**Comment by mihaimaruseac** [comment]
[Today's pips](https://pypi.org/project/tf-nightly/2.4.0.dev20200716/#files) include macos py38 too. This seems solved now, but please reopen if there are still issues.

Thank you for pointing out the error and for debugging.
