### ISSUE TITLE
bazel build tensorflow failed

### ISSUE THREAD

**Issue by Julius-ZCJ** [tensorflow/tensorflow#41369]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NO
- TensorFlow installed from (source or binary):  
- TensorFlow version: latest version
- Python version: 
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 3.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9
- GPU model and memory:

I want to use docker build a tensorflow-gpu container, Here is my Dockerfile:

`FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

RUN apt-get update

RUN apt-get install -y wget \
                vim \
                cmake

RUN apt-get -y install \
    python3 \
    python3-pip \
    python3-setuptools`

and build command is that:

docker build -t tensorlfow_gpu -f Dockerfile .

docker run -d --name tensorflow-gpu-demo -v ***/tensorflow:tensorflow tensorflow_gpu

**Describe the problem**

And I login the container 
install bazel3.1 and some require tag and start build tensorflow

Then I get these errors:

C++ compilation of rule '//tensorflow/core/kernels:determinant_op_gpu' failed (Exit 1)

C++ compilation of rule '//tensorflow/core/util:einsum_op_util' failed (Killed)

C++ compilation of rule '//tensorflow/core/kernels:roll_op_gpu' failed (Exit 1)

I found every time the error raise, the error is different, What should I do to compile tensorflow successful.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@Julius-ZCJ 
Please confirm if you followed instructions from [TensorFlow](https://www.tensorflow.org/install/source) website .
Can you  check this link with same error and update:
#37430 [link](https://github.com/tensorflow/tensorflow/issues/39333#issuecomment-647012051) [link1](https://developer.codeplay.com/products/computecpp/ce/guides/tensorflow-guide/tensorflow-native-compilation?)

**Comment by mihaimaruseac** [comment]
Please include an actionable error message, nut just the file where the compilation stopped.

Could it be that you ran out of memory during compile?

**Comment by Julius-ZCJ** [comment]
@Saduf2019 
I see the link you provide, but my error is not same as them.

**Comment by Saduf2019** [comment]
@Julius-ZCJ
Please update as per comment from @mihaimaruseac.
