### ISSUE TITLE
twice embedding_lookup‘ result is the same as once embedding_lookup,but gradients not

### ISSUE THREAD

**Issue by akafen** [tensorflow/tensorflow#41368]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I have to use twice embedding_lookup to do the same thing as once embedding_lookup,but their gradients dont act the same

`
import tensorflow as tf
import numpy as np

a = tf.convert_to_tensor(np.random.random([2048,32]))
b = tf.convert_to_tensor([1,2,2,3,4,4,5,1,2,3,4,5])
sess = tf.Session()
b_,idx = tf.unique(b)
print(sess.run(b_))
w = tf.nn.embedding_lookup(a,b_)
print(sess.run(w))

perm = tf.argsort(b)
aux = tf.gather_nd(b,tf.reshape(perm,[-1,1]))
mask = tf.not_equal(aux[1:],aux[:-1])
pos = tf.boolean_mask(perm[1:],mask)
pos = tf.concat([[0],pos],axis=0)

print(sess.run(pos))

w_2 = tf.nn.embedding_lookup(a,b)
w_1 = tf.nn.embedding_lookup(w_2,pos)

print(sess.run(w_1))

`

![E5@B5_ XNA U83Q1BJ1 0XO](https://user-images.githubusercontent.com/22000530/87393434-c49a1580-c5e0-11ea-8cfa-9f755ad9818d.png)

**Describe the expected behavior**

Their performance is the same,but when I use them in my models(all is the same except one is once embedding_lookup,one is twice embedding_lookup),they don't perform the same.

use once embedding_lookup:
![MMZZQFLBEKQE8MJHKK8Y5FO](https://user-images.githubusercontent.com/22000530/87393621-0cb93800-c5e1-11ea-8da5-27f363fb7c0c.png)

use twice embedding_lookup:
![X`K9D(FEM_HBM%17UO~5MRS](https://user-images.githubusercontent.com/22000530/87393625-0dea6500-c5e1-11ea-9f5f-28d36a9111fe.png)
We could see before training they perform the same,but after training, they perform different,I assume because their gradients are different,but I don't know how to fix them,by the way I have to use twice embedding_lookup

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@akafen 

Request you to share colab link or simple standalone code with proper indentation to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by akafen** [comment]
A simple standalone code is below:

`

import tensorflow as tf
from keras.layers.embeddings import Embedding
from lazy import lazy
import numpy as np
from keras.layers import Input
from keras.layers.core import Dense, Lambda,Reshape
from keras.models import Model
from keras.layers import Layer
from keras import backend as K
from keras import activations


class TiedEmbeddingsTransposed(Layer):

    def __init__(self, tied_to=None,
                 activation=None,
                 **kwargs):
        super(TiedEmbeddingsTransposed, self).__init__(**kwargs)
        self.tied_to = tied_to
        if activation is not None:
            self.activation = activations.get(activation)
        else:
            self.activation = None

    def build(self, input_shape):
        self.transposed_weights = K.transpose(self.tied_to.weights[0])
        #self.transposed_weights = K.l2_normalize(self.transposed_weights,axis=1)
        super(TiedEmbeddingsTransposed, self).build(input_shape)

    def compute_mask(self, inputs, mask=None):
        return mask

    def compute_output_shape(self, input_shape):
        return input_shape[0], K.int_shape(self.tied_to.weights[0])[0]

    def call(self, inputs, mask=None):
        #inputs = K.l2_normalize(inputs,axis=1)
        output = K.dot(inputs, self.transposed_weights)
        if self.activation is not None:
            output = self.activation(output)
        return output

class Once_embedding_lookup_Layer(Layer):
    def __init__(self,input,**kwargs):

        self.inputs = input
        super(Once_embedding_lookup_Layer, self).__init__(**kwargs)

    def build(self, input_shape):
        super(Once_embedding_lookup_Layer, self).build(input_shape)


    def compute_loss(self, ys_true,video_embedding):
        ys_true = tf.cast(ys_true,'int64')

        ys_true = tf.reshape(ys_true,[-1])
        ys_true,idx = tf.unique(ys_true)


        all_w = tf.nn.embedding_lookup(video_embedding,ys_true)

        logits = tf.matmul(self.inputs,all_w,transpose_b=True)

        loss = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=idx, logits=logits)

        return loss

    def call(self, inputs, **kwargs):
        ys_true = inputs[0]
        video_embedding = inputs[1]
        loss = self.compute_loss(ys_true,video_embedding)
        self.add_loss(loss)
        return loss

class Twice_embedding_lookup_Layer(Layer):
    def __init__(self,input,**kwargs):

        self.inputs = input
        super(Twice_embedding_lookup_Layer, self).__init__(**kwargs)

    def build(self, input_shape):
        super(Twice_embedding_lookup_Layer, self).build(input_shape)


    def compute_loss(self, ys_true,video_embedding):
        ys_true = tf.cast(ys_true,'int64')

        ys_true = tf.reshape(ys_true,[-1])

        perm = tf.argsort(ys_true)
        aux = tf.gather_nd(ys_true, tf.reshape(perm, [-1, 1]))
        mask = tf.not_equal(aux[1:], aux[:-1])
        pos = tf.boolean_mask(perm[1:], mask)
        pos = tf.concat([[0], pos], axis=0)

        all_w = tf.nn.embedding_lookup(video_embedding,ys_true)
        all_w = tf.nn.embedding_lookup(all_w,pos)

        logits = tf.matmul(self.inputs,all_w,transpose_b=True)

        ys_true,idx = tf.unique(ys_true)

        loss = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=idx, logits=logits)

        return loss

    def call(self, inputs, **kwargs):
        ys_true = inputs[0]
        video_embedding = inputs[1]
        loss = self.compute_loss(ys_true,video_embedding)
        self.add_loss(loss)
        return loss


class Once_embedding_lookup_model(object):
    def __init__(self,video_size,embedding_size):
        self.video_size = video_size
        self.embedding_size = embedding_size

    @lazy
    def _video_embeddings(self):
        return Embedding(self.video_size, self.embedding_size, weights=[np.ones([self.video_size,self.embedding_size])], mask_zero=False,
                         name='video-embd')

    @lazy
    def _user_state_model(self):
        user_feature = Input(shape=(1,),name='user_feature')
        user_state_features = Dense(256, activation='relu', name='user-state-dense-256')(
            user_feature)
        user_state_features = Dense(128, activation='relu', name='user-state-dense-128')(user_state_features)
        user_state_features = Dense(self.embedding_size, activation='relu')(user_state_features)
        return Model(inputs=user_feature, outputs=user_state_features)

    @lazy
    def _video_embedding_model(self):
        target_id_input = Input(shape=(1,),name='target_id_input')
        target_id_embedding = self._video_embeddings(target_id_input)
        target_id_embedding = Reshape((self.embedding_size,))(target_id_embedding)

        target_id_embedding = Dense(128,activation='relu',name='video_embedding_dense_128')(target_id_embedding)
        target_id_embedding = Dense(self.embedding_size,activation='relu',name='video_embedding')(target_id_embedding)

        model = Model(inputs=target_id_input,outputs=target_id_embedding)
        model.summary()
        return model

    @lazy
    def once_embedding_lookup_layer(self):
        y_true = Input(shape=(1,),name='y_true')
        inputs = self._user_state_model.outputs[0]
        video_embedding = self._video_embedding_model.outputs[0]
        loss = Once_embedding_lookup_Layer(input=inputs,name='once_embedding_lookup_loss')([y_true,video_embedding])

        predict_softmax = TiedEmbeddingsTransposed(tied_to=self._video_embeddings, activation='softmax',name='predict_softmax_once')(
            self._user_state_model.outputs[0])

        model = Model(inputs=self._user_state_model.inputs + self._video_embedding_model.inputs + [y_true],
                      outputs=[predict_softmax, loss],
                      name='once_embedding_lookup_model')
        model.summary()
        return model

class Twice_embedding_lookup_model(object):
    def __init__(self,video_size,embedding_size):
        self.video_size = video_size
        self.embedding_size = embedding_size

    @lazy
    def _video_embeddings(self):
        return Embedding(self.video_size, self.embedding_size, weights=[np.ones([self.video_size,self.embedding_size])], mask_zero=False,
                         name='video-embd-twice')

    @lazy
    def _user_state_model(self):
        user_feature = Input(shape=(1,),name='user_feature_twice')
        user_state_features = Dense(256, activation='relu', name='user-state-dense-256_twice')(
            user_feature)
        user_state_features = Dense(128, activation='relu', name='user-state-dense-128_twice')(user_state_features)
        user_state_features = Dense(self.embedding_size, activation='relu')(user_state_features)
        return Model(inputs=user_feature, outputs=user_state_features)

    @lazy
    def _video_embedding_model(self):
        target_id_input = Input(shape=(1,),name='target_id_input_twice')
        target_id_embedding = self._video_embeddings(target_id_input)
        target_id_embedding = Reshape((self.embedding_size,))(target_id_embedding)

        target_id_embedding = Dense(128,activation='relu',name='video_embedding_dense_128_twice')(target_id_embedding)
        target_id_embedding = Dense(self.embedding_size,activation='relu',name='video_embedding_twice')(target_id_embedding)

        model = Model(inputs=target_id_input,outputs=target_id_embedding)
        model.summary()
        return model

    @lazy
    def twice_embedding_lookup_layer(self):
        y_true = Input(shape=(1,),name='y_true')
        inputs = self._user_state_model.outputs[0]
        video_embedding = self._video_embedding_model.outputs[0]
        loss = Twice_embedding_lookup_Layer(input=inputs,name='twice_embedding_lookup_loss')([y_true,video_embedding])

        predict_softmax = TiedEmbeddingsTransposed(tied_to=self._video_embeddings, activation='softmax',name='predict_softmax_twice')(
            self._user_state_model.outputs[0])

        model = Model(inputs=self._user_state_model.inputs + self._video_embedding_model.inputs + [y_true],
                      outputs=[predict_softmax, loss],
                      name='twice_embedding_lookup_model')
        model.summary()
        return model

def mean_pred(y_true,y_pred):
    return K.mean(y_pred)

from keras.metrics import sparse_top_k_categorical_accuracy
def top10(y_true,y_pred):
    return sparse_top_k_categorical_accuracy(y_true, y_pred, 10)

import os
os.environ['CUDA_VISIBLE_DEVICES'] = '1'

if __name__ == '__main__':
    once_model = Once_embedding_lookup_model(2048,32).once_embedding_lookup_layer
    twice_model = Twice_embedding_lookup_model(2048,32).twice_embedding_lookup_layer
    once_model.compile(
        loss={
            'predict_softmax_once': 'sparse_categorical_crossentropy',
            "once_embedding_lookup_loss": lambda y_true, y_pred: y_pred,
        },
        loss_weights={
            'predict_softmax_once': 0,
            "once_embedding_lookup_loss": 1,
        },
        metrics={
            "predict_softmax_once": top10,
            'once_embedding_lookup_loss': mean_pred,
        },
        optimizer='adam')
    twice_model.compile(
        loss={
            'predict_softmax_twice': 'sparse_categorical_crossentropy',
            "twice_embedding_lookup_loss": lambda y_true, y_pred: y_pred,
        },
        loss_weights={
            'predict_softmax_twice': 0,
            "twice_embedding_lookup_loss": 1,
        },
        metrics={
            "predict_softmax_twice": top10,
            'twice_embedding_lookup_loss': mean_pred,
        },
        optimizer='adam')

    x = []
    for i in range(128):
        x.append(i)
    x = np.array(x).astype('int64')

    y = []
    for i in range(128,256):
        y.append(i)
    y = np.array(y).astype('int64')
    inputs = []
    inputs.append(x)
    inputs.append(y)

    labels = []
    for i in range(2):
        for j in range(64):
            labels.append(j)
    labels = np.array(labels).astype('int64')
    inputs.append(labels)

    predict_softmax_once, loss = once_model.predict(inputs, batch_size=128)
    print('once',predict_softmax_once)

    predict_softmax_twice, loss = twice_model.predict(inputs, batch_size=128)
    print('twice',predict_softmax_twice)

    for i in range(100):
        loss_metrics = once_model.train_on_batch(inputs,[labels,labels])
        loss_metrics = twice_model.train_on_batch(inputs,[labels,labels])

    predict_softmax_once, loss = once_model.predict(inputs, batch_size=128)
    print('once',predict_softmax_once)

    predict_softmax_twice, loss = twice_model.predict(inputs, batch_size=128)
    print('twice',predict_softmax_twice)

`

**Comment by akafen** [comment]
A simple standalone code is below:

'
aaa
'

**Comment by akafen** [comment]
A simple standalone code is below 
`
   aaa
`

**Comment by akafen** [comment]
A simple standalone code is below :
`   
    import tensorflow as tf
    from keras.layers.embeddings import Embedding
    from lazy import lazy
    import numpy as np
    from keras.layers import Input
    from keras.layers.core import Dense, Lambda,Reshape
    from keras.models import Model
    from keras.layers import Layer
    from keras import backend as K
    from keras import activations
    
    
    class TiedEmbeddingsTransposed(Layer):
    
        def __init__(self, tied_to=None,
                     activation=None,
                     **kwargs):
            super(TiedEmbeddingsTransposed, self).__init__(**kwargs)
            self.tied_to = tied_to
            if activation is not None:
                self.activation = activations.get(activation)
            else:
                self.activation = None
    
        def build(self, input_shape):
            self.transposed_weights = K.transpose(self.tied_to.weights[0])
            #self.transposed_weights = K.l2_normalize(self.transposed_weights,axis=1)
            super(TiedEmbeddingsTransposed, self).build(input_shape)
    
        def compute_mask(self, inputs, mask=None):
            return mask
    
        def compute_output_shape(self, input_shape):
            return input_shape[0], K.int_shape(self.tied_to.weights[0])[0]
    
        def call(self, inputs, mask=None):
            #inputs = K.l2_normalize(inputs,axis=1)
            output = K.dot(inputs, self.transposed_weights)
            if self.activation is not None:
                output = self.activation(output)
            return output
    
    class Once_embedding_lookup_Layer(Layer):
        def __init__(self,input,**kwargs):
    
            self.inputs = input
            super(Once_embedding_lookup_Layer, self).__init__(**kwargs)
    
        def build(self, input_shape):
            super(Once_embedding_lookup_Layer, self).build(input_shape)
    
    
        def compute_loss(self, ys_true,video_embedding):
            ys_true = tf.cast(ys_true,'int64')
    
            ys_true = tf.reshape(ys_true,[-1])
            ys_true,idx = tf.unique(ys_true)
    
    
            all_w = tf.nn.embedding_lookup(video_embedding,ys_true)
    
            logits = tf.matmul(self.inputs,all_w,transpose_b=True)
    
            loss = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=idx, logits=logits)
    
            return loss
    
        def call(self, inputs, **kwargs):
            ys_true = inputs[0]
            video_embedding = inputs[1]
            loss = self.compute_loss(ys_true,video_embedding)
            self.add_loss(loss)
            return loss
    
    class Twice_embedding_lookup_Layer(Layer):
        def __init__(self,input,**kwargs):
    
            self.inputs = input
            super(Twice_embedding_lookup_Layer, self).__init__(**kwargs)
    
        def build(self, input_shape):
            super(Twice_embedding_lookup_Layer, self).build(input_shape)
    
    
        def compute_loss(self, ys_true,video_embedding):
            ys_true = tf.cast(ys_true,'int64')
    
            ys_true = tf.reshape(ys_true,[-1])
    
            perm = tf.argsort(ys_true)
            aux = tf.gather_nd(ys_true, tf.reshape(perm, [-1, 1]))
            mask = tf.not_equal(aux[1:], aux[:-1])
            pos = tf.boolean_mask(perm[1:], mask)
            pos = tf.concat([[0], pos], axis=0)
    
            all_w = tf.nn.embedding_lookup(video_embedding,ys_true)
            all_w = tf.nn.embedding_lookup(all_w,pos)
    
            logits = tf.matmul(self.inputs,all_w,transpose_b=True)
    
            ys_true,idx = tf.unique(ys_true)
    
            loss = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=idx, logits=logits)
    
            return loss
    
        def call(self, inputs, **kwargs):
            ys_true = inputs[0]
            video_embedding = inputs[1]
            loss = self.compute_loss(ys_true,video_embedding)
            self.add_loss(loss)
            return loss
    
    
    class Once_embedding_lookup_model(object):
        def __init__(self,video_size,embedding_size):
            self.video_size = video_size
            self.embedding_size = embedding_size
    
        @lazy
        def _video_embeddings(self):
            return Embedding(self.video_size, self.embedding_size, weights=[np.ones([self.video_size,self.embedding_size])], mask_zero=False,
                             name='video-embd')
    
        @lazy
        def _user_state_model(self):
            user_feature = Input(shape=(1,),name='user_feature')
            user_state_features = Dense(256, activation='relu', name='user-state-dense-256')(
                user_feature)
            user_state_features = Dense(128, activation='relu', name='user-state-dense-128')(user_state_features)
            user_state_features = Dense(self.embedding_size, activation='relu')(user_state_features)
            return Model(inputs=user_feature, outputs=user_state_features)
    
        @lazy
        def _video_embedding_model(self):
            target_id_input = Input(shape=(1,),name='target_id_input')
            target_id_embedding = self._video_embeddings(target_id_input)
            target_id_embedding = Reshape((self.embedding_size,))(target_id_embedding)
    
            target_id_embedding = Dense(128,activation='relu',name='video_embedding_dense_128')(target_id_embedding)
            target_id_embedding = Dense(self.embedding_size,activation='relu',name='video_embedding')(target_id_embedding)
    
            model = Model(inputs=target_id_input,outputs=target_id_embedding)
            model.summary()
            return model
    
        @lazy
        def once_embedding_lookup_layer(self):
            y_true = Input(shape=(1,),name='y_true')
            inputs = self._user_state_model.outputs[0]
            video_embedding = self._video_embedding_model.outputs[0]
            loss = Once_embedding_lookup_Layer(input=inputs,name='once_embedding_lookup_loss')([y_true,video_embedding])
    
            predict_softmax = TiedEmbeddingsTransposed(tied_to=self._video_embeddings, activation='softmax',name='predict_softmax_once')(
                self._user_state_model.outputs[0])
    
            model = Model(inputs=self._user_state_model.inputs + self._video_embedding_model.inputs + [y_true],
                          outputs=[predict_softmax, loss],
                          name='once_embedding_lookup_model')
            model.summary()
            return model
    
    class Twice_embedding_lookup_model(object):
        def __init__(self,video_size,embedding_size):
            self.video_size = video_size
            self.embedding_size = embedding_size
    
        @lazy
        def _video_embeddings(self):
            return Embedding(self.video_size, self.embedding_size, weights=[np.ones([self.video_size,self.embedding_size])], mask_zero=False,
                             name='video-embd-twice')
    
        @lazy
        def _user_state_model(self):
            user_feature = Input(shape=(1,),name='user_feature_twice')
            user_state_features = Dense(256, activation='relu', name='user-state-dense-256_twice')(
                user_feature)
            user_state_features = Dense(128, activation='relu', name='user-state-dense-128_twice')(user_state_features)
            user_state_features = Dense(self.embedding_size, activation='relu')(user_state_features)
            return Model(inputs=user_feature, outputs=user_state_features)
    
        @lazy
        def _video_embedding_model(self):
            target_id_input = Input(shape=(1,),name='target_id_input_twice')
            target_id_embedding = self._video_embeddings(target_id_input)
            target_id_embedding = Reshape((self.embedding_size,))(target_id_embedding)
    
            target_id_embedding = Dense(128,activation='relu',name='video_embedding_dense_128_twice')(target_id_embedding)
            target_id_embedding = Dense(self.embedding_size,activation='relu',name='video_embedding_twice')(target_id_embedding)
    
            model = Model(inputs=target_id_input,outputs=target_id_embedding)
            model.summary()
            return model
    
        @lazy
        def twice_embedding_lookup_layer(self):
            y_true = Input(shape=(1,),name='y_true')
            inputs = self._user_state_model.outputs[0]
            video_embedding = self._video_embedding_model.outputs[0]
            loss = Twice_embedding_lookup_Layer(input=inputs,name='twice_embedding_lookup_loss')([y_true,video_embedding])
    
            predict_softmax = TiedEmbeddingsTransposed(tied_to=self._video_embeddings, activation='softmax',name='predict_softmax_twice')(
                self._user_state_model.outputs[0])
    
            model = Model(inputs=self._user_state_model.inputs + self._video_embedding_model.inputs + [y_true],
                          outputs=[predict_softmax, loss],
                          name='twice_embedding_lookup_model')
            model.summary()
            return model
    
    def mean_pred(y_true,y_pred):
        return K.mean(y_pred)
    
    from keras.metrics import sparse_top_k_categorical_accuracy
    def top10(y_true,y_pred):
        return sparse_top_k_categorical_accuracy(y_true, y_pred, 10)
    
    import os
    os.environ['CUDA_VISIBLE_DEVICES'] = '1'
    
    if __name__ == '__main__':
        once_model = Once_embedding_lookup_model(2048,32).once_embedding_lookup_layer
        twice_model = Twice_embedding_lookup_model(2048,32).twice_embedding_lookup_layer
        once_model.compile(
            loss={
                'predict_softmax_once': 'sparse_categorical_crossentropy',
                "once_embedding_lookup_loss": lambda y_true, y_pred: y_pred,
            },
            loss_weights={
                'predict_softmax_once': 0,
                "once_embedding_lookup_loss": 1,
            },
            metrics={
                "predict_softmax_once": top10,
                'once_embedding_lookup_loss': mean_pred,
            },
            optimizer='adam')
        twice_model.compile(
            loss={
                'predict_softmax_twice': 'sparse_categorical_crossentropy',
                "twice_embedding_lookup_loss": lambda y_true, y_pred: y_pred,
            },
            loss_weights={
                'predict_softmax_twice': 0,
                "twice_embedding_lookup_loss": 1,
            },
            metrics={
                "predict_softmax_twice": top10,
                'twice_embedding_lookup_loss': mean_pred,
            },
            optimizer='adam')
    
        x = []
        for i in range(128):
            x.append(i)
        x = np.array(x).astype('int64')
    
        y = []
        for i in range(128,256):
            y.append(i)
        y = np.array(y).astype('int64')
        inputs = []
        inputs.append(x)
        inputs.append(y)
    
        labels = []
        for i in range(2):
            for j in range(64):
                labels.append(j)
        labels = np.array(labels).astype('int64')
        inputs.append(labels)
    
        predict_softmax_once, loss = once_model.predict(inputs, batch_size=128)
        print('once',predict_softmax_once)
    
        predict_softmax_twice, loss = twice_model.predict(inputs, batch_size=128)
        print('twice',predict_softmax_twice)
    
        for i in range(100):
            loss_metrics = once_model.train_on_batch(inputs,[labels,labels])
            loss_metrics = twice_model.train_on_batch(inputs,[labels,labels])
    
        predict_softmax_once, loss = once_model.predict(inputs, batch_size=128)
        print('once',predict_softmax_once)
    
        predict_softmax_twice, loss = twice_model.predict(inputs, batch_size=128)
        print('twice',predict_softmax_twice)
`

**Comment by ravikyram** [comment]
@akafen 

I have tried in colab with TF 2.2.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/80a4bde009d50f43284f718457194a9b/untitled128.ipynb).You also see the same behavior?Thanks!

**Comment by akafen** [comment]
@ravikyram 
Yes, after some steps training, once embedding_lookup perform different to twice embedding_lookup,but they choose the same index as I said before,so I think their gradients are different

**Comment by sushreebarsa** [comment]
Was able to replicate the isuue in TF 2.6.0-dev20210530,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/42307dda070f3933c3cdbc53c72bfee3/untitled135.ipynb#scrollTo=h0W4-1fPTNQ0)..Thanks !

**Comment by sachinprasadhs** [comment]
I see that you're using deprecated import modules and some of the code still follows version 1 compatible code structure.
After making some changes I'm able to see specific error in your code, please find the gist [here](https://colab.sandbox.google.com/gist/sachinprasadhs/6bcaedde4e2f0ece819a39040610ceb8/untitled135.ipynb) and could you please provide the reproducible code in the latest Tensorflow version. Thanks!
