### ISSUE TITLE
how to build tflite2.3 on windows

### ISSUE THREAD

**Issue by Tomhouxin** [tensorflow/tensorflow#41364]
how to build tflite2.3 on windows and mac

**Comment by ravikyram** [comment]
@Tomhouxin 

Can you please go through this[ link ](https://github.com/tensorflow/tensorflow/issues/37899#issuecomment-607623498)and see if it helps you.Thanks!

**Comment by Tomhouxin** [comment]
@ravikyram 
Oh! 
bazel build -c opt //tensorflow/lite:tensorflowlite
I get tensorflowlite.dll(16.8M), But how to distinguish the Debug and Release, x86 or x64

**Comment by terryheo** [comment]
"-c opt" is for release.
"-c dbg" for debug build.

If your workstation is x64, bazel generates a x64 binary by default.
"--cpu=x86" option is needed to build x86 binary.

**Comment by Tomhouxin** [comment]
@terryheo ok, thank you, good job
