### ISSUE TITLE
Not able to use libtensorflow-lite.a static library in Android studio for including headers.

### ISSUE THREAD

**Issue by anandchandra1011** [tensorflow/tensorflow#41373]
**System information**
- OS Platform and Distribution (windows 10):
- Mobile device (oppo reno2) i am building and running on this device through android studio.
- TensorFlow installed from (source or binary): Ubuntu terminal through pip3
- TensorFlow version:
- Python version: python 3.8.2
- Installed using pip 
- Bazel version (if compiling from source): I have created libtensorflow-lite.a using bazle . Now trying to directly use the lib. 
- GCC/Compiler version (if compiling from source): gnu++11
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
![image](https://user-images.githubusercontent.com/23177883/87418459-5872de00-c5ef-11ea-8b71-9f1d69a8a161.png)
I am trying to inclue interpreter.h, model.h etc in native c code. But it is showing file not found. If i add tensorflow folder and add the include paths in cmake then build is sucecssfull but include dont work- like I am not able to load model or run interpreter. 
**Provide the exact sequence of commands / steps that you executed before running into the problem**
I have build the libtensorflow-lite.a for arm64 platform and now using it as static library to include the required dependencies of tflite, to code in native cpp in Android studio using NDK.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by terryheo** [comment]
For using TFLite C API, you'd better check this.
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/c

For using prebuilt library with Android Studio, please check this.
https://developer.android.com/ndk/guides/cmake#using_prebuilt_libraries

**Comment by anandchandra1011** [comment]
Thanks terryheo, I am using shared object libtensorflow.so , created using https://www.tensorflow.org/lite/guide/android#use_tflite_c_api

while build and install via android studio, i am getting these error related to interpretor. Please help

[8/8] Linking CXX shared library C:\Users\admin\Documents\TeamTalk\download\IN006407\android_tflite-master\tflite_segmentation\app\build\intermediates\cmake\debug\obj\arm64-v8a\libnative-activity.so
FAILED: C:/Users/admin/Documents/TeamTalk/download/IN006407/android_tflite-master/tflite_segmentation/app/build/intermediates/cmake/debug/obj/arm64-v8a/libnative-activity.so 
cmd.exe /C "cd . && C:\Users\admin\AppData\Local\Android\Sdk\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android27 --gcc-toolchain=C:/Users/admin/AppData/Local/Android/Sdk/ndk/21.2.6472646/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/admin/AppData/Local/Android/Sdk/ndk/21.2.6472646/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -std=gnu++11 -Wall -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments  -u ANativeActivity_onCreate -shared -Wl,-soname,libnative-activity.so -o C:\Users\admin\Documents\TeamTalk\download\IN006407\android_tflite-master\tflite_segmentation\app\build\intermediates\cmake\debug\obj\arm64-v8a\libnative-activity.so CMakeFiles/native-activity.dir/android_main.cpp.o CMakeFiles/native-activity.dir/app_engine.cpp.o CMakeFiles/native-activity.dir/tflite_deeplab.cpp.o CMakeFiles/native-activity.dir/camera_manager.cpp.o CMakeFiles/native-activity.dir/9a7cbc7930929ec4da523570f5b7600c/app/src/include/common/android/camera_utils.cpp.o CMakeFiles/native-activity.dir/9a7cbc7930929ec4da523570f5b7600c/app/src/include/common/android/util_asset.cpp.o CMakeFiles/native-activity.dir/cca59a257428af77379c25c93fd919d9/tflite_segmentation/app/src/include/common/util_tflite.cpp.o CMakeFiles/native-activity.dir/cca59a257428af77379c25c93fd919d9/tflite_segmentation/app/src/include/common/assertgl.c.o CMakeFiles/native-activity.dir/cca59a257428af77379c25c93fd919d9/tflite_segmentation/app/src/include/common/assertegl.c.o CMakeFiles/native-activity.dir/cca59a257428af77379c25c93fd919d9/tflite_segmentation/app/src/include/common/util_egl.c.o CMakeFiles/native-activity.dir/cca59a257428af77379c25c93fd919d9/tflite_segmentation/app/src/include/common/util_shader.c.o CMakeFiles/native-activity.dir/cca59a257428af77379c25c93fd919d9/tflite_segmentation/app/src/include/common/util_matrix.c.o CMakeFiles/native-activity.dir/cca59a257428af77379c25c93fd919d9/tflite_segmentation/app/src/include/common/util_texture.c.o CMakeFiles/native-activity.dir/cca59a257428af77379c25c93fd919d9/tflite_segmentation/app/src/include/common/util_render2d.c.o CMakeFiles/native-activity.dir/cca59a257428af77379c25c93fd919d9/tflite_segmentation/app/src/include/common/util_debugstr.c.o CMakeFiles/native-activity.dir/cca59a257428af77379c25c93fd919d9/tflite_segmentation/app/src/include/common/util_pmeter.c.o CMakeFiles/native-activity.dir/9a7cbc7930929ec4da523570f5b7600c/app/src/include/common/winsys/winsys_null.c.o  -landroid libnative_app_glue.a -lm -lcamera2ndk -lmediandk -lEGL -lGLESv2 C:/Users/admin/Documents/TeamTalk/download/IN006407/android_tflite-master/tflite_segmentation/app/src/main/cpp/../jniLibs/arm64-v8a/libtensorflowlite.so -llog -latomic -lm && cd ."
CMakeFiles/native-activity.dir/tflite_deeplab.cpp.o: In function `invoke_deeplab':
C:/Users/admin/Documents/TeamTalk/download/IN006407/android_tflite-master/tflite_segmentation/app/src/main/cpp/tflite_deeplab.cpp:110: undefined reference to `tflite::impl::Interpreter::Invoke()'
CMakeFiles/native-activity.dir/tflite_deeplab.cpp.o: In function `std::__ndk1::default_delete<tflite::impl::Interpreter>::operator()(tflite::impl::Interpreter*) const':
C:/Users/admin/AppData/Local/Android/Sdk/ndk/21.2.6472646/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1/memory:2338: undefined reference to `tflite::impl::Interpreter::~Interpreter()'
CMakeFiles/native-activity.dir/cca59a257428af77379c25c93fd919d9/tflite_segmentation/app/src/include/common/util_tflite.cpp.o: In function `tflite_create_interpreter(tflite_interpreter_t*, char const*, unsigned long)':
C:/Users/admin/Documents/TeamTalk/download/IN006407/android_tflite-master/tflite_segmentation/app/src/include/common/util_tflite.cpp:97: undefined reference to `tflite::impl::InterpreterBuilder::InterpreterBuilder(tflite::FlatBufferModel const&, tflite::OpResolver const&)'
C:/Users/admin/Documents/TeamTalk/download/IN006407/android_tflite-master/tflite_segmentation/app/src/include/common/util_tflite.cpp:97: undefined reference to `tflite::impl::InterpreterBuilder::operator()(std::__ndk1::unique_ptr<tflite::impl::Interpreter, std::__ndk1::default_delete<tflite::impl::Interpreter> >*)'
C:/Users/admin/Documents/TeamTalk/download/IN006407/android_tflite-master/tflite_segmentation/app/src/include/common/util_tflite.cpp:97: undefined reference to `tflite::impl::InterpreterBuilder::~InterpreterBuilder()'
C:/Users/admin/Documents/TeamTalk/download/IN006407/android_tflite-master/tflite_segmentation/app/src/include/common/util_tflite.cpp:97: undefined reference to `tflite::impl::InterpreterBuilder::~InterpreterBuilder()'
C:/Users/admin/Documents/TeamTalk/download/IN006407/android_tflite-master/tflite_segmentation/app/src/include/common/util_tflite.cpp:175: undefined reference to `tflite::impl::Interpreter::SetNumThreads(int)'
C:/Users/admin/Documents/TeamTalk/download/IN006407/android_tflite-master/tflite_segmentation/app/src/include/common/util_tflite.cpp:176: undefined reference to `tflite::impl::Interpreter::AllocateTensors()'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by terryheo** [comment]
Could you try to provide "-Wl,--whole-archive" link option to link libtensorflowlite.so ?

**Comment by anandchandra1011** [comment]
![image](https://user-images.githubusercontent.com/23177883/88025834-89ed2b80-cb52-11ea-83e7-ded96f16fe2e.png)

Do you mean to change in condition default option and rebuild the shared object?

**Comment by terryheo** [comment]
No. I meant linker command to your hello-libs JNI target.

**Comment by anandchandra1011** [comment]
![image](https://user-images.githubusercontent.com/23177883/88037221-3e427e00-cb62-11ea-9272-cbb734de1406.png)

I have added this in my cmake file. still problem persist.

**Comment by anandchandra1011** [comment]
[CMakeLists.txt](https://github.com/tensorflow/tensorflow/files/4952527/CMakeLists.txt)

I am also attaching cmake file for reference.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
