### ISSUE TITLE
freezing the app(.py to exe)

### ISSUE THREAD

**Issue by daynial132** [tensorflow/tensorflow#41372]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):N/A
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary):  source
- TensorFlow version (use command below): 1.15.0
- Python version:3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:N/A
- GPU model and memory:

**Describe the current behavior**
I have tried to freeze the custom app with auto-py-to-exe and it is giving mw the error of "ImportError: No module named 'tensorflow_core.python'"

can anyone please help me with it

Thanks in advance
![tf_error](https://user-images.githubusercontent.com/61754297/87411293-f317f080-c5e0-11ea-99d8-64a6914ace7c.PNG)

**Comment by ravikyram** [comment]
@daynial132 

tensorflow_core only exists in 1.15, 2.x.
Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by daynial132** [comment]
I have created a virtual environment  in anaconda on 3.5 python 
installed the packages specifically used for the my app
then installed the auto-py-to-exe and run it
and finally include the script to script location used one direction option,
in additional files  i added complete folder to it and all the files in the folder 
in advance option on runtime-hooks-dir  I added complete site-packages

thats it. and press the convert button on auto-py-to-exe

**Comment by daynial132** [comment]
have i done something wrong ?? 
or missing some thing

**Comment by gowthamkpr** [comment]
@daynial132 This is a conversion issue, not the tensorflow issue itself. It would be better if you post this issue in stackoverflow where there is a wider community to respond. Thanks!
