### ISSUE TITLE
Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize

### ISSUE THREAD

**Issue by jingweimo** [tensorflow/tensorflow#41377]
I am using tensorflow-gpu 1.15.3 and keras 2.3.1, with python 3.7 and cuda 10.0. I confirm that the tensorflow version matches up with the python and cuda (including cudnn).  The tensorflow-gpu works fine when I test it with a demon example on image classification (e.g., https://github.com/keras-team/keras/blob/master/examples/cifar10_cnn.py). But when I tried a large cnn model such as Yolo-v3 (i.e., https://github.com/qqwweee/keras-yolo3), it gives the error: 
```
UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d_1/convolution}}]]
	 [[Mean/_2311]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d_1/convolution}}]]
0 successful operations.
0 derived errors ignored.
```

Most often the above error is due to the mismatch between tensorflow-gpu and cuda versions. But it seems not to be that case.

It is very interesting to note if I first run the small image classification test, which would go smoothly without any error, and thereafter run the Yolo-v3, the Yolo training will be fine without the "Failled to get convolution algorithm".  But if I directly run the yolo training, it won't proceed because of the error. 

Anyone has similar experiences? What possible reasons for the cuda error?

**Comment by amahendrakar** [comment]
@jingweimo,
Please try limiting GPU memory growth as shown in this guide [here](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) and let us know if you are facing the same issue. Thanks!

**Comment by jingweimo** [comment]
@amahendrakar I put the following codes in the front of my script:
```
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  # Restrict TensorFlow to only use the first GPU
  try:
    tf.config.experimental.set_visible_devices(gpus[0], 'GPU')
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPU")
  except RuntimeError as e:
    # Visible devices must be set before GPUs have been initialized
    print(e)

if gpus:
  try:
    # Currently, memory growth needs to be the same across GPUs
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Memory growth must be set before GPUs have been initialized
    print(e)
```

But unfortunately, that issue still persistent. To train the YOLO model, I do have to run the small example first, and then switch to the YOLO model, If I directly do the latter, the errors will occur.

**Comment by sanjoy** [comment]
Can you please share the full log?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
