### ISSUE TITLE
Deprecation of validation_data in tensorflow.keras.Callbacks

### ISSUE THREAD

**Issue by Guillermogsjc** [tensorflow/tensorflow#41378]
Hi,

why the `validation_data` attribute has been dropped from  *callbacks* ?

The only alternative is to set `validation_data` as a constructor parameter in the `Callback`, I can understand that this is a solution, but why we lost that useful feature? Could be recovered in subsequent releases? Previously callbacks where able to use  validation data generated with `validation_split` on the fit call.

In the documentation  https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/Callback there is any example that uses validation data, it is uncommon to lack such an important example in a flawless overall documentation like Tensorflow has right now.

Thanks.
Kind regards.

**Comment by jvishnuvardhan** [comment]
@Guillermogsjc As mentioned in the `Callbacks` [guide](https://www.tensorflow.org/guide/keras/custom_callback),

> A callback is a powerful tool to customize the behavior of a Keras model during training, evaluation, or inference. Examples include tf.keras.callbacks.TensorBoard to visualize training progress and results with TensorBoard, or tf.keras.callbacks.ModelCheckpoint to periodically save your model during training.

There are several callbacks to monitor different things during training/validation. 

> Previously callbacks where able to use validation data generated with validation_split on the fit call.
Sorry, didn't get what you meant. Currently callbacks in `.fit` uses `validation_split` as shown in the `Callbacks` guide mentioned above.

Please add more details and possibly a standalone code (if required) about the issue. thanks!
