### ISSUE TITLE
model_server_config requires platform information

### ISSUE THREAD

**Issue by hanneshapke** [tensorflow/tensorflow#41387]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://www.tensorflow.org/tfx/serving/serving_config#model_server_config_details

## Description of the issue (what needs changing):

The model configuration file in the TF Serving docs (link above) should include the `model_platform`. If left out, TF Serving stops with the error below:

```
Error: Invalid argument: Illegal setting neither ModelServerConfig::model_type (deprecated) nor ModelServerConfig::model_platform.
```

### Clear description

The configuration example should be updated from 

```
model_config_list {
  config {
    name: 'my_first_model'
    base_path: '/tmp/my_first_model/'
  }
  config {
    name: 'my_second_model'
    base_path: '/tmp/my_second_model/'
  }
}
```

to

```
model_config_list {
  config {
    name: 'my_first_model'
    base_path: '/tmp/my_first_model/'
    model_platform: 'tensorflow'
  }
  config {
    name: 'my_second_model'
    base_path: '/tmp/my_second_model/'
    model_platform: 'tensorflow'
  }
}
```

### Parameters defined

Please see the example above

### Submit a pull request?

PR requested here: https://github.com/tensorflow/serving/pull/1687

**Comment by ravikyram** [comment]
@hanneshapke 

This issue is more suitable for TensorFlow Serving repo. Please post it on Serving repo from [here.](https://github.com/tensorflow/serving/issues) Thanks!
