### ISSUE TITLE
Add the mention bot to tensorflow's github

### ISSUE THREAD

**Issue by Mistobaan** [tensorflow/tensorflow#4139]
Integrate Mention-bot with the tensorflow github pull request system

https://github.com/facebook/mention-bot 

>The mention bot will automatically mention potential reviewers on pull requests. It helps getting faster turnaround on pull requests by involving the right people early on.

**Comment by martinwicke** [comment]
By analyzing the text of this issue I've identified @aselle as someone who will want to know about this. 

I'm all for it. Adding it now.

**Comment by martinwicke** [comment]
Let's see how this works. We have a PR triage, but I bet it'll be relaxing as hell to have a reviewer recommendation. We can also play with the config. I wish it had an option to not @mention people, but just say their names instead (as a recommendation for a human). 

If this catches on, we may make a PR.

**Comment by aselle** [comment]
Pretty cool.
