### ISSUE TITLE
Keras Sequence Generators not compatible with ragged tensors when using mode.fit

### ISSUE THREAD

**Issue by sidhomj** [tensorflow/tensorflow#41397]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: cuDNN 10
- GPU model and memory: V100/24GB RAM

**Describe the current behavior**
I have written the following generator to take numpy arrays and convert to ragged tensors within a Keras Sequence Data generator.

'''python
class get_batches(tf.keras.utils.Sequence):
    def __init__(self,x,y,batch_size=10,random=False):
        self.batch_size = batch_size
        self.random = random
        self.x = x
        self.y = y
        self.on_epoch_end()

    def on_epoch_end(self):
        self.indexes = np.arange(len(self.x[0]))
        if self.random == True:
            np.random.shuffle(self.indexes)

    def __getitem__(self, index):
        'Generate one batch of data'
        # Generate indexes of the batch
        indexes = self.indexes[index * self.batch_size:(index + 1) * self.batch_size]

        x_out = [turn_into_ragged(var[indexes]) for var in self.x]
        # x_out = [var[indexes] for var in self.x]
        y_out = [var[indexes] for var in self.y]

        return (x_out, y_out)

    def __len__(self):
        x = self.x
        batch_size = self.batch_size
        if len(x[0]) % batch_size == 0:
            n_batches = (len(x[0]) // batch_size)
        else:
            n_batches = (len(x[0]) // batch_size) + 1
        return n_batches

When I run this generator in a for loop, I am able to take the outputs and feed it to my model.fit command but when I put the generator into the model.fit command, I get the following error:

 TypeError: `generator` yielded an element that could not be converted to the expected type. The expected type was float64, but the yielded element was <tf.RaggedTensor

**Describe the expected behavior**
I would expect the generator to be compatible with model.fit and train.

**Standalone code to reproduce the issue**

'''python
class get_batches(tf.keras.utils.Sequence):
    def __init__(self,x,y,batch_size=10,random=False):
        self.batch_size = batch_size
        self.random = random
        self.x = x
        self.y = y
        self.on_epoch_end()

    def on_epoch_end(self):
        self.indexes = np.arange(len(self.x[0]))
        if self.random == True:
            np.random.shuffle(self.indexes)

    def __getitem__(self, index):
        'Generate one batch of data'
        # Generate indexes of the batch
        indexes = self.indexes[index * self.batch_size:(index + 1) * self.batch_size]

        x_out = [turn_into_ragged(var[indexes]) for var in self.x]
        # x_out = [var[indexes] for var in self.x]
        y_out = [var[indexes] for var in self.y]

        return (x_out, y_out)

    def __len__(self):
        x = self.x
        batch_size = self.batch_size
        if len(x[0]) % batch_size == 0:
            n_batches = (len(x[0]) // batch_size)
        else:
            n_batches = (len(x[0]) // batch_size) + 1
        return n_batches

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@sidhomj,
In the given code snippet you have defined the functions but you're not calling them anywhere. 

To reproduce the issue reported here, could you please share the complete code or the `.ipynb`/`.py` file you are running. Thanks!
