### ISSUE TITLE
[TF2.2] tf.data.Dataset memory leak

### ISSUE THREAD

**Issue by Wirg** [tensorflow/tensorflow#41395]
**System information**
- Have I written custom code : yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.4
- TensorFlow installed from (source or binary): wheel
- TensorFlow version (use command below):  v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.6.7
- CUDA/cuDNN version: 10.2  
- GPU model and memory: GeForce RTX 2080 Ti

**Describe the current behavior**

I have a memory leak when using `tf.data.Dataset`.
It happens when I use fit on a tf.keras.Model.
It seems to happend when iterating inside a `tf.function` too.

**Describe the expected behavior**

Memory should not be incread

**Standalone code to reproduce the issue**
```python

import numpy as np
import tensorflow as tf
import psutil
from tqdm import tqdm

n = 80
dataset = (
    tf.data.Dataset.from_tensor_slices(
        (
            np.random.rand(n, 416, 416, 3),
            np.zeros((n, 1)),
        )
    )
    .batch(8)
    .repeat()
)

@tf.function
def inspect_dataset(dataset):
    for _ in tqdm(dataset, "iterating through dataset"):
        pass


inspect_dataset(dataset)
```

![image](https://user-images.githubusercontent.com/17848620/87487333-aadaeb80-c63d-11ea-8d51-8e1c4a794abf.png)

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2 ,2.3-rc1 and i am seeing the error message(`Your session crashed after using all available RAM. `).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/849620e259f735b1a72c4b95c30134dc/untitled127.ipynb).Thanks!

**Comment by jvishnuvardhan** [comment]
@Wirg Can you please share full code with the `model.fit` so that we can reproduce and find the root-cause of the issue? Thanks!
