### ISSUE TITLE
GPU memory consumption soars up when "device_record_tensor_accesses_" in executor.cc .

### ISSUE THREAD

**Issue by gangmuk** [tensorflow/tensorflow#41398]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): TensorFlow 1.13
- Python version: Python 3.6.10
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: 10.0
- GPU model and memory: NVIDIA Tesla V100, 32GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

There is flag named "device_record_tensor_accesses_" which is set by "RequiresRecordingAccessedTensors()" function in gpu_device.cc. It sets record accessed tensors and delay tensor release time until actual GPU execution is finished. Comment said it may be useful for multi stream situation which never happened. Hence, it is set to false by default. I need this sort of feature so test it, changing it into true. When I turned it on, weirdly GPU memory consumption soars up. I used Resnet50 with batch 64 from tf_cnn_benchmark. It used around 8GB but when "device_record_tensor_accesses_" is turned on, it uses more than 15GB and keeps growing during training. I saw source code quite a long time to figure out where this problem comes from but I still can't.

I looked up why it happens and found out that there are actually more tensor allocation.

I saw that this feature is removed many part of related codes from recent TensorFlow since it has never been used.

Related files: executor.cc, gpu_device.cc, gpu_event_mgr.h/cc, unique_tensor_references.h/cc

**Describe the expected behavior**

I guess it should have stayed using the same amount of GPU memory.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

I simply use tf_cnn_benchmark's Resnet50 model training job.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

This shows tensor allocation from that operator(kernel) which didn't exist when "device_record_tensor_accesses_" is turned off.
So, they are newly appearing tensor allocation. (There are more but I just post some of them due to space limit.)

![image](https://user-images.githubusercontent.com/20127356/87491362-e8159c80-c682-11ea-9837-39724853e6be.png)

and I grep one of those newly created operator "AssignMovingAvg". And it appears in a strange path.

I just turned on "device_record_tensor_accesses_", but why are those operator added??
Is there any reason or is it bug?

![image](https://user-images.githubusercontent.com/20127356/87505594-30918200-c6a4-11ea-9e64-3f4143d1da9c.png)

Is it supposed to change the 

I guess this is bug. I believe there is no reason that the peak GPU memory consumption goes up.

Thank you in advance!

**Comment by ymodak** [comment]
Thanks for your issue. Perhaps tensorflow/benchmarks repo can be a good platform to raise this issue since your issue talks about [tf_cnn_benchmarks](https://github.com/tensorflow/benchmarks/tree/master/scripts/tf_cnn_benchmarks).
Please try posting it to [tensorflow/benchmarks](https://github.com/tensorflow/benchmarks/issues).

**Comment by gangmuk** [comment]
Thank you for replying!
