### ISSUE TITLE
Debugging predictions step with tf.debugging.experimental.enable_dump_debug_info throws an error.

### ISSUE THREAD

**Issue by mshavlovsky** [tensorflow/tensorflow#41392]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): I slightly modified a colab notebook from tf ranking package to demonstrate the issue. The modified notebook is  https://colab.research.google.com/drive/1FVkkYCo_ZtN6mu-kmF1IqDYI4C1-jxaw?usp=sharing 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
I get error while trying to log debug information with [tf.debugging.experimental.enable_dump_debug_info](https://www.tensorflow.org/api_docs/python/tf/debugging/experimental/enable_dump_debug_info) .
This is the only change to the notebook is that I added a cell with `tf.debugging.experimental.enable_dump_debug_info("/tmp/debug")` right before calling predictions (in the end of the notebook).
The error is 
```
INFO:tensorflow:vocabulary_size = 30522 in document_tokens is inferred from the number of elements in the vocabulary_file /tmp/vocab.txt.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-33-81eaf5e40876> in <module>()
----> 1 x = next(predictions)
      2 assert(len(x) == _LIST_SIZE)  ## Note that this includes padding.

13 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/normalization.py in build(self, input_shape)
    374       if axis_to_dim[x] is None:
    375         raise ValueError('Input has undefined `axis` dimension. Input shape: ',
--> 376                          input_shape)
    377     self.input_spec = InputSpec(ndim=ndims, axes=axis_to_dim)
    378 

ValueError: ('Input has undefined `axis` dimension. Input shape: ', TensorShape([None, None]))
```
**Describe the expected behavior**
I expect to get debugging information while calling predictions.

**Standalone code to reproduce the issue**
To reproduce run this notebook https://colab.research.google.com/drive/1FVkkYCo_ZtN6mu-kmF1IqDYI4C1-jxaw?usp=sharing

**Comment by Saduf2019** [comment]
@mshavlovsky 
Can you please share simple stand alone indented code such that we can replicate the issue faced, the code shared is too large to replicate.

similar issues:
[link](https://stackoverflow.com/questions/43480732/none-dimension-raise-valueerror-in-batch-norm-with-tensorflow )[link1](https://github.com/tensorflow/tensorflow/issues/14809) #31751

**Comment by mshavlovsky** [comment]
@Saduf2019 
I simplified the [notebook](https://colab.research.google.com/drive/1FVkkYCo_ZtN6mu-kmF1IqDYI4C1-jxaw?usp=sharing) to have only two cells. The first one doing the necessary job from installing TF to training the model . The second cell is where the error appears. It is where I enable debugging and call `predict`.
```
tf.debugging.experimental.enable_dump_debug_info("/tmp/debug")

predictions = ranker.predict(input_fn=lambda: predict_input_fn("/tmp/test.tfrecords"))
x = next(predictions)
```
 Note that the fist cell is large, but it takes about five to ten minutes to complete. Its content is taken from the [tfranking colab tutorial](https://colab.research.google.com/github/tensorflow/ranking/blob/master/tensorflow_ranking/examples/handling_sparse_features.ipynb).

**Comment by caisq** [comment]
@mshavlovsky Can you try the following

`tf.debugging.experimental.enable_dump_debug_info("/tmp/debug", tensor_debug_mode="FULL_HEALTH", circular_buffer_size=-1)`

The `tensor_debug_mode` specifies a mode that gives more information compared to the default `"NO_TENSOR"` mode; it'll also probably bypass the problem you are experiencing. The `circular_buffer_size=-1` lets the debugger dump all tensor info, instead of only the most recent 1000.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/debug/lib/dumping_callback.py#L747 for more info about the two arguments. 

Let me know if this resolves your issue.

**Comment by mshavlovsky** [comment]
@caisq Thanks for looking into the problem. The following code still returns an error
```
tf.debugging.experimental.enable_dump_debug_info("/tmp/debug", tensor_debug_mode="FULL_HEALTH", circular_buffer_size=-1)

predictions = ranker.predict(input_fn=lambda: predict_input_fn("/tmp/test.tfrecords"))
x = next(predictions)
```
The output is:


> INFO:tensorflow:Done calling model_fn.
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-2-b971928e3770> in <module>()
>       3 
>       4 predictions = ranker.predict(input_fn=lambda: predict_input_fn("/tmp/test.tfrecords"))
> ----> 5 x = next(predictions)
> 
> 14 frames
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saving/saveable_object_util.py in op_list_to_dict(op_list, convert_variable_to_tensor)
>     290             var = ops.convert_to_tensor(var, as_ref=True)
>     291           if not _tensor_comes_from_variable(var):
> --> 292             raise TypeError("Variable to save is not a Variable: %s" % var)
>     293         if var.op.type == "ReadVariableOp":
>     294           name = var.op.inputs[0].op.name
> 
> TypeError: Variable to save is not a Variable: Tensor("encoding_layer/document_tokens_embedding/embedding_weights/Read/ReadVariableOp/Identity:0", shape=(30522, 20), dtype=float32)

**Comment by caisq** [comment]
Yep. The new error "Variable to save is not a Variable" is related to a known issue that the `enable_dump_debug_info()` API is incompatible with checkpoint saving. Can you disable saving in your program during debugging and try again?

**Comment by mshavlovsky** [comment]
After disabling checkpoint saving, I still get the "Variable to save is not a Variable" error. To disable checkpoint saving, I use the following RunConfig
```
  run_config = tf.estimator.RunConfig(
      save_checkpoints_steps=None,
      save_checkpoints_secs=None,
      save_summary_steps=None,
      keep_checkpoint_every_n_hours=None)
```

After training, the model's directory does not have `ckpt` files. Checking the model's directory
`! ls "/tmp/ranking_model_dir"` yields 

> events.out.tfevents.1595773363.3ec7490ced7d

Can it be that checkpoint saving is not properly disabled ? Or the issue still persists?

**Comment by mshavlovsky** [comment]
@caisq Any update on the issue? The problem still persists after disabling checkpoint saving. Thank you.

**Comment by sushreebarsa** [comment]
Was able to replicate the isuue in TF 2.6.0-dev20210530,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/eb00193a698ade7a8799a99610ae5c9e/untitled136.ipynb)..Thanks !
