### ISSUE TITLE
pylint errors on master branch

### ISSUE THREAD

**Issue by pooyadavoodi** [tensorflow/tensorflow#41396]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): N/A
- TensorFlow version (use command below): master branch
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
When I run pylint on TF python files, I get a lot of failures. The following is an example (using master branch):

* Is this expected or is a bug?
* Fixing pylint issues in our PRs is hard given all the existing failures. What do you suggest to make the contribution easier? 

```
tensorflow/python~ % pylint --rcfile=../tools/ci_build/pylintrc ./keras/layers/pooling.py
************* Module keras.layers.pooling
keras/layers/pooling.py:167:71: C0303: Trailing whitespace (trailing-whitespace)
keras/layers/pooling.py:168:74: C0303: Trailing whitespace (trailing-whitespace)
keras/layers/pooling.py:213:71: C0303: Trailing whitespace (trailing-whitespace)
keras/layers/pooling.py:214:74: C0303: Trailing whitespace (trailing-whitespace)
keras/layers/pooling.py:377:0: C0303: Trailing whitespace (trailing-whitespace)
keras/layers/pooling.py:379:0: C0303: Trailing whitespace (trailing-whitespace)
keras/layers/pooling.py:383:60: C0303: Trailing whitespace (trailing-whitespace)
keras/layers/pooling.py:385:41: C0303: Trailing whitespace (trailing-whitespace)
keras/layers/pooling.py:387:62: C0303: Trailing whitespace (trailing-whitespace)
keras/layers/pooling.py:426:71: C0303: Trailing whitespace (trailing-whitespace)
keras/layers/pooling.py:427:74: C0303: Trailing whitespace (trailing-whitespace)
keras/layers/pooling.py:483:71: C0303: Trailing whitespace (trailing-whitespace)
keras/layers/pooling.py:484:74: C0303: Trailing whitespace (trailing-whitespace)
keras/layers/pooling.py:628:71: C0303: Trailing whitespace (trailing-whitespace)
keras/layers/pooling.py:629:74: C0303: Trailing whitespace (trailing-whitespace)
keras/layers/pooling.py:681:71: C0303: Trailing whitespace (trailing-whitespace)
keras/layers/pooling.py:682:74: C0303: Trailing whitespace (trailing-whitespace)
keras/layers/pooling.py:72:2: W0221: Parameters differ from overridden 'call' method (arguments-differ)
keras/layers/pooling.py:95:4: R1705: Unnecessary "else" after "return" (no-else-return)
keras/layers/pooling.py:288:2: W0221: Parameters differ from overridden 'call' method (arguments-differ)
keras/layers/pooling.py:315:4: R1705: Unnecessary "else" after "return" (no-else-return)
keras/layers/pooling.py:564:2: W0221: Parameters differ from overridden 'call' method (arguments-differ)
keras/layers/pooling.py:600:4: R1705: Unnecessary "else" after "return" (no-else-return)
keras/layers/pooling.py:734:4: R1705: Unnecessary "else" after "return" (no-else-return)
keras/layers/pooling.py:739:2: W0221: Parameters differ from overridden 'call' method (arguments-differ)
keras/layers/pooling.py:792:2: W0221: Parameters differ from overridden 'call' method (arguments-differ)
keras/layers/pooling.py:794:4: R1705: Unnecessary "else" after "return" (no-else-return)
keras/layers/pooling.py:868:4: R1705: Unnecessary "else" after "return" (no-else-return)
keras/layers/pooling.py:873:2: W0221: Parameters differ from overridden 'call' method (arguments-differ)
keras/layers/pooling.py:918:4: R1705: Unnecessary "else" after "return" (no-else-return)
keras/layers/pooling.py:959:4: R1705: Unnecessary "else" after "return" (no-else-return)
keras/layers/pooling.py:975:4: R1705: Unnecessary "else" after "return" (no-else-return)
keras/layers/pooling.py:980:2: W0221: Parameters differ from overridden 'call' method (arguments-differ)
keras/layers/pooling.py:1019:4: R1705: Unnecessary "else" after "return" (no-else-return)
keras/layers/pooling.py:1054:4: R1705: Unnecessary "else" after "return" (no-else-return)

------------------------------------------------------------------
Your code has been rated at 8.54/10 (previous run: 8.81/10, -0.27)
```

**Comment by Saduf2019** [comment]
@pooyadavoodi 
Can you please share simple indented stand alone code to replicate the issue faced or if possible share a colab gist with the error faced for us to analyse.

**Comment by pooyadavoodi** [comment]
To reproduce the issue, you can simply run the command I provided above on TF source code. For the example above, I used pooling layer source code from keras.

**Comment by pooyadavoodi** [comment]
Just to clarify, the example I gave above is not the only TF python file that has pylint errors. Pretty much every Python file I chose from tensorflow/python has pylint errors, and for some of them score is as low as 6.0.

**Comment by mihaimaruseac** [comment]
Can you send a pull request please?

**Comment by mihaimaruseac** [comment]
There might also be a difference between the settings we are using and the setting you are running with

**Comment by pooyadavoodi** [comment]
@mihaimaruseac There are a huge number of errors across the whole tensorflow/python. 

I also think this is due to having different settings. Could you share how you run pylint and which rc file you use?

This is how I run it which is documented here: https://www.tensorflow.org/community/contribute/code_style#pylint

```pylint --rcfile=tensorflow/tools/ci_build/pylintrc tensorflow/python/keras/layers/pooling.py```

**Comment by pooyadavoodi** [comment]
Perhaps fixing pylint errors in my PRs is not required anymore given the existing errors in the source code? 

If that's the case, it would be good to indicate that in the documentation: https://www.tensorflow.org/community/contribute/code_style#pylint

**Comment by pooyadavoodi** [comment]
By the way, I see almost the same failures in r2.2 branch.

**Comment by mihaimaruseac** [comment]
[This](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/tools/ci_build/presubmit/ubuntu_16/sanity/build.sh) is the script we are using for the sanity build. It invokes [this script](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/tools/ci_build/ci_sanity.sh) for the actual tests. And [this](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/tools/ci_build/ci_sanity.sh;l=92-223;drc=7eab1f3bfe796f453b4549a0923ef954c822671c) is the code that does the actual sanitization.

**Comment by pooyadavoodi** [comment]
Thanks for the links. Unfortunately I am still struggling with how to run pylint properly.
I think the issue is lack of good documentation here: https://www.tensorflow.org/community/contribute/code_style#pylint

Here is what I did using the links provided by @mihaimaruseac 
* I only kept "do_pylint" in SANITY_STEPS and removed everything else: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/ci_sanity.sh#L648
* I only kept "Python 3 pylint" in SANITY_STEPS_DESC and removed everything else: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/ci_sanity.sh#L649
* Ran this command locally: `./tensorflow/tools/ci_build/ci_sanity.sh --incremental` from the TF root.
* The output says `FAIL: Found 155 non-whitelisted pylint errors`.
* Here is the full output log: https://gist.github.com/pooyadavoodi/d2a47e3e23fc10e5fbf473d99cad647d 
* As an example, this page seems to show the command used on the cloud for GitHub but I cannot run it that way locally: https://source.cloud.google.com/results/invocations/010e6117-22ed-48df-8a94-b3136583d5ef/details

**Comment by bhack** [comment]
Yes this is quite a problem also for the integrated pylint support in IDEs

**Comment by bhack** [comment]
What was the original rationale to not use `# pylint: disable=message-name`?

**Comment by bhack** [comment]
We need to also find a solution for astroid at https://github.com/PyCQA/pylint/issues/2603

**Comment by bhack** [comment]
In master you can run now `pylint  tensorflow/python/keras/layers/pooling.py`. 

@mihaimaruseac I think that we could close this.
