### ISSUE TITLE
exponential_avg_factor not in Op FusedBatchNormV3: model deployed using Golang Tensorflow v2.0.2

### ISSUE THREAD

**Issue by anilknayak** [tensorflow/tensorflow#41391]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Training:
*TensorFlow v2.2.0
*GPU distributed training with 4 GPUs
*Use ```strategy = tf.distribute.MirroredStrategy()``` for multiple GPU training
*MobileNet model is trained using ```model.fit```
*Trained model is saved using ```.keras_model.save(path)```
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
*Model is trained on Machine type ```n1-standard-8 (8 vCPUs, 30 GB memory)```
*GCP VM with image ```c5-deeplearning-tf2-2-2-cu101-v20200706```
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
*Raspberry Pi Golang model deployment
*Model optimization
- TensorFlow installed from (source or binary):
*Training model in GCP VM ( ```c5-deeplearning-tf2-2-2-cu101-v20200706``` )
*Local using ```pip install tensorflow==2.2.0```
- TensorFlow version (use command below):
*Training model in GCP VM ( ```c5-deeplearning-tf2-2-2-cu101-v20200706``` )
*Local using ```pip install tensorflow==2.2.0```
- Python version:
3.7
- Bazel version (if compiling from source):
0.24.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:
4 x NVIDIA Tesla K80, 11GB each

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
*Model trained on GCP VM with 4 GPU using TensorFlow version as per google deep learning image ```c5-deeplearning-tf2-2-2-cu101-v20200706``` is v2.2.2
*Model is saved using ```keras_model.save(path)```
*I am facing issue with model freeze and optimization, so that I can deploy that model in Golang Tensorflow
1. Freeze model  using ```tf.compat.v1.graph_util.convert_variables_to_constants``` 
I have tool the keras saved model directory from GCP VM and try to freeze the model in local.
```
from tensorflow.python.framework import graph_io
tf.compat.v1.disable_v2_behavior()
tf.keras.backend.set_learning_phase(0)
tf.compat.v1.keras.backend.set_floatx('float16')
# model_dir: keras model saved dir
model = tf.keras.models.load_model(model_dir, compile=False)
output_node_names = ["input","out1/Softmax","out2/Softmax"]
sess = tf.compat.v1.keras.backend.get_session()
frozen_graph = tf.compat.v1.graph_util.convert_variables_to_constants(sess, 
                                                                              sess.graph.as_graph_def(), 
                                                                              output_node_names)
input_names = ["input"]
output_names = ["out1/Softmax","out2/Softmax"]
frozen_graph = optimize_for_inference_lib.optimize_for_inference(frozen_graph,
                                                                         input_names,
                                                                         output_names,
                                                                         input_node.dtype.as_datatype_enum)
graph_io.write_graph(frozen_graph, output_dir, freezed_model_file, as_text=False)
```
2. The output model .pb (single file), is freezed using above code.
while freezing following is the warning
```
WARNING:tensorflow:Didn't find expected Conv2D or DepthwiseConv2dNative input to 'depth_conv_bn_5/FusedBatchNormV3'
```
3. Then converted the freezed model to builder.SaveModelBuilder
```
tf.compat.v1.disable_v2_behavior()
tf.compat.v1.keras.backend.set_floatx('float16')
with gfile.FastGFile(freezed_model.pb, "rb") as f:
    graph_def = tf.compat.v1.GraphDef()
    byte = f.read()
    graph_def.ParseFromString(byte)
    tf.import_graph_def(graph_def, name='')
count_nodes = 0
for node in tf.compat.v1.Session().graph_def.node:
    count_nodes += 1
print("Number of nodes that not optimized freezed model has: ", count_nodes)
# golang_tf_model_dir: where the golang specific model is prepared
builder = saved_model_builder.SavedModelBuilder(golang_tf_model_dir)
with tf.compat.v1.Session() as sess:
    builder.add_meta_graph_and_variables(sess=sess,
                                    tags=["model"],
                                    clear_devices=True)
    
builder.save()
``` 
4. After this when I am trying to load this model in golang tensorflow version v2.0.2
I found this error
```
 NodeDef mentions attr 'exponential_avg_factor' not in Op<name=FusedBatchNormV3; signature=x:T, scale:U, offset:U, mean:U, variance:U -> y:T, batch_mean:U, batch_variance:U, reserve_space_1:U, reserve_space_2:U, reserve_space_3:U; attr=T:type,allowed=[DT_HALF, DT_BFLOAT16, DT_FLOAT]; attr=U:type,allowed=[DT_FLOAT]; attr=epsilon:float,default=0.0001; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]; attr=is_training:bool,default=true>; NodeDef: {{node depth_conv_bn_5/FusedBatchNormV3}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
FAIL
```

**Describe the expected behavior**
Earlier I have used tensorflow version 1.12.0 to my model training, freeze and deployment and I did not see FusedBatchNormV3
but in recent changes in TensorFlow v2.0 BatchNormalization layer is freezed to FusedBatchNormV3 which is causing issue.

Earlier same trained model on Tf1.12.0 has FusedBatchNorm only no FusedBatchNormV3.

My expectation
1. How to exponential_avg_factor will be considered in FusedBatchNormV3
2. GraphDef-generating binary is ```tf.compat.v1.GraphDef()``` 
3. GraphDef-interpreting binary is ```graph_def.pb2``` i think because deployment is in TensorFlow version v2.0.2
Or I am doing something wrong.

**Standalone code to reproduce the issue**
For golang model loading code
```
model := tf.LoadSavedModel(<golang_tf_model_dir>, []string{<model_tag>}, nil /*options*/)
```
model_tag is default ```serve``` is not changed while freezing
golang_tf_model_dir: is mentioned earlier

**Other info / logs**
Attached logs earlier

**Comment by anilknayak** [comment]
I have checked there is fix for tensorflow lite https://github.com/tensorflow/tensorflow/pull/29615/files
But this is not the case for keras-model

**Comment by anilknayak** [comment]
I got some insights to this issue
1. If a keras model has BatchNormalization after a Concatenation layer then the ```optimize_for_inference_lib.optimize_for_inference``` API could not fuse the batch norm
2. Because it could not fuse the batch norm the FuseBatchNormV3 stays as it is after inference (freezed model)
3. If you put this freezed model to graph tranformation
```
bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph=freezed_model.pb \
--out_graph=optimized_saved_model.pb \
--inputs='input' \
--outputs='out1/Softmax,out2/Softmax' \
--transforms='
  obfuscate_names
  add_default_attributes
  remove_nodes(op=Identity, op=CheckNumerics)
  fold_constants(ignore_errors=true)
  fold_batch_norms
  fold_old_batch_norms
  strip_unused_nodes
  sort_by_execution_order'
```

this will throw error as follows
```
fold_constants: Ignoring error NodeDef mentions attr 'exponential_avg_factor' not in Op<name=FusedBatchNormV3; signature=x:T, scale:U, offset:U, mean:U, variance:U -> y:T, batch_mean:U, batch_variance:U, reserve_space_1:U, reserve_space_2:U, reserve_space_3:U; attr=T:type,allowed=[DT_HALF, DT_BFLOAT16, DT_FLOAT]; attr=U:type,allowed=[DT_FLOAT]; attr=epsilon:float,default=0.0001; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]; attr=is_training:bool,default=true>; NodeDef: {{node 1i}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
```
4. After if you try to convert the optimized model pb  to saved model for deployment in Golang environment
the same error persists

**Is this behavior is correct? we can not put a batch normalization layer after a concatenation layer?**
**or this need a fix**

**Comment by BernardinD** [comment]
Any progress here?

**Comment by geekysethi** [comment]
Hey! did you find any solution for this?

**Comment by codethief** [comment]
I'm seeing the same error, albeit in a slightly different context:

I downloaded ssd_mobilenet_v2_mnasfpn_coco from the [TFv1 model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md) and am trying to convert it to ONNX using TensorFlow 1.15.3 and [tf2onnx](https://github.com/onnx/tensorflow-onnx) 1.8.2:

```
$ python3 -m tf2onnx.convert --input frozen_inference_graph.pb --output model.onnx --opset 11
```

Unfortunately, it doesn't even get to the converting step but already fails at loading the frozen graph:

```
Traceback (most recent call last):
  File "/home/user/opt/miniconda3/envs/my-conda-env/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 501, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'exponential_avg_factor' not in Op<name=FusedBatchNormV3; signature=x:T, scale:U, offset:U, mean:U, variance:U -> y:T, batch_mean:U, batch_variance:U, reserve_space_1:U, reserve_space_2:U, reserve_space_3:U; attr=T:type,allowed=[DT_HALF, DT_BFLOAT16, DT_FLOAT]; attr=U:type,allowed=[DT_FLOAT]; attr=epsilon:float,default=0.0001; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]; attr=is_training:bool,default=true>; NodeDef: {{node FeatureExtractor/MobilenetV2/Conv/BatchNorm/FusedBatchNormV3}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/opt/miniconda3/envs/my-conda-env/lib/python3.6/site-packages/tf2onnx/convert.py", line 221, in <module>
    main()
  File "/home/user/opt/miniconda3/envs/my-conda-env/lib/python3.6/site-packages/tf2onnx/convert.py", line 148, in main
    graph_def, inputs, outputs = tf_loader.from_graphdef(args.graphdef, args.inputs, args.outputs)
  File "/home/user/opt/miniconda3/envs/my-conda-env/lib/python3.6/site-packages/tf2onnx/tf_loader.py", line 200, in from_graphdef
    tf.import_graph_def(graph_def, name='')
  File "/home/user/opt/miniconda3/envs/my-conda-env/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/user/opt/miniconda3/envs/my-conda-env/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/home/user/opt/miniconda3/envs/my-conda-env/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 505, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: NodeDef mentions attr 'exponential_avg_factor' not in Op<name=FusedBatchNormV3; signature=x:T, scale:U, offset:U, mean:U, variance:U -> y:T, batch_mean:U, batch_variance:U, reserve_space_1:U, reserve_space_2:U, reserve_space_3:U; attr=T:type,allowed=[DT_HALF, DT_BFLOAT16, DT_FLOAT]; attr=U:type,allowed=[DT_FLOAT]; attr=epsilon:float,default=0.0001; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]; attr=is_training:bool,default=true>; NodeDef: {{node FeatureExtractor/MobilenetV2/Conv/BatchNorm/FusedBatchNormV3}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
```

**Comment by robertlugg** [comment]
It appears that that option appeared in TF 2.2.  Compare tf 2.1 to tf 2.2:

https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/python/ops/nn_impl.py
https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/python/ops/nn_impl.py

Search for the string avg_ and you will find it new to 2.2.  I check in 1.n up to 15 and it is not in there.  I suspect model created by a newer version of TF 2.2+ and trying to load in using a pre 2.2 version.

**Comment by jsmeredith** [comment]
The last comment sounds like correct to me, thanks!  From 
https://www.tensorflow.org/guide/versions#backward_and_partial_forward_compatibility, forward compatibility is only offered within Patch releases. Closing for now, but of course report back if you think this should still work.
