### ISSUE TITLE
crosstool_wrapper_driver_is_not_gcc cannot find libpython2.7.so.1.0

### ISSUE THREAD

**Issue by zhiyun** [tensorflow/tensorflow#414]
I encountered error
python2: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
while trying to install tensorflow from source with GPU-enabled.

I can see the error command is
 (cd /home/xxx/.cache/bazel/_bazel_xxx/d568262eb4464bf011ab3d998aff21ac/tensorflow && \
  exec env - \
    INTERCEPT_LOCALLY_EXECUTABLE=1 \
    PATH=/share/software/python/2.7.10/Python-2.7.10/release/bin:/share/software/java/jdk1.8.0_66/bin:/share/software/NLP/bazel/output:/usr/local/cuda/bin:/opt/attila/:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ibutils/bin:/usr/local/MATLAB/R2014a/bin \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -iquote . -iquote bazel-out/local_linux-opt/genfiles -isystem tools/cpp/gcc3 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_linux-opt/bin/external/gemmlowp/_objs/eight_bit_int_gemm/external/gemmlowp/eight_bit_int_gemm/eight_bit_int_gemm.o' -MD -MF bazel-out/local_linux-opt/bin/external/gemmlowp/_objs/eight_bit_int_gemm/external/gemmlowp/eight_bit_int_gemm/eight_bit_int_gemm.d -c external/gemmlowp/eight_bit_int_gemm/eight_bit_int_gemm.cc -o bazel-out/local_linux-opt/bin/external/gemmlowp/_objs/eight_bit_int_gemm/external/gemmlowp/eight_bit_int_gemm/eight_bit_int_gemm.o)

I guess the problem is I'm using a local python version, which is installed under
/share/software/python/2.7.10/Python-2.7.10/release/bin
and path to libpython2.7.so.1.0 is not accessible. 
If I add LD_LIBRARY_PATH=/share/software/python/2.7.10/Python-2.7.10/release/lib to the error command, I would be able to get rid of the error.

It seems to me bazel does not allow user to add ld_library_path(?), so what should I do in this case..?

This error has bothered me for days and I still cannot get over it.... Thank you in advance for your help and suggestions!

**Comment by vrv** [comment]
If building from HEAD, you should be able to use ./configure to specify the path of the python you want to use -- let us know if that works.

**Comment by zhiyun** [comment]
Hi vrv,
I have pulled the most recent version, and configure python with the local installation. However, the error is still there.
actually the lib link points to the site-package, which I assume will resolve numpy errors.

python_include -> /share/software/python/2.7.10/Python-2.7.10/release/include/python2.7
python_lib -> /share/software/python/2.7.10/Python-2.7.10/release/lib/python2.7/site-packages

I have created softlink to libpython2.7.so.1.0 under /share/software/python/2.7.10/Python-
2.7.10/release/lib/python2.7/site-packages, which doesn't help either... 

thanks!

**Comment by ebrevdo** [comment]
where is your libpython2.7.so.1.0?  what directory is it in?

have you tried using a virtualenv with that python, and pointing configure at that virtualenv?

**Comment by ebrevdo** [comment]
Can you do something for me?  Load up the version of python you set up with config, and run:

from distutils import sysconfig
print sysconfig.get_config_vars('LIBPL')

it should return a path.  can you reply with that path?  also, for the path, type: ls -l <<path>>  (and paste the results here as well)

**Comment by ebrevdo** [comment]
@girving  we may need to point the pythonX_path to a script (copied from a template via e.g. sed) which sets the LD_LIBRARY_PATH correctly based on e.g. LIBPL output, and calls the python interpreter.

**Comment by zhiyun** [comment]
Hi ebrevdo,
libpython2.7.so.1.0 is under /share/software/python/2.7.10/Python-2.7.10/release/lib

Here is the output.
print sysconfig.get_config_vars('LIBPL')
['/share/software/python/2.7.10/Python-2.7.10/release/lib/python2.7/config']

ls -l /share/software/python/2.7.10/Python-2.7.10/release/lib/python2.7/config
total 9768
-rw-rw-r--. 1 xxxx    2200 Oct  2 15:44 config.c
-rw-rw-r--. 1 xxxx    1507 Oct  2 15:44 config.c.in
-rwxrwxr-x. 1 xxxx    7122 Oct  2 15:44 install-sh
-rw-rw-r--. 1 xxxx 9883714 Oct  2 15:44 libpython2.7.a
-rw-rw-r--. 1 xxxx   49734 Oct  2 15:44 Makefile
-rwxrwxr-x. 1 xxxx    7431 Oct  2 15:44 makesetup
-rw-rw-r--. 1 xxxx    6256 Oct  2 15:44 python.o
-rw-rw-r--. 1 xxxx   18479 Oct  2 15:44 Setup
-rw-rw-r--. 1 xxxx     368 Oct  2 15:44 Setup.config
-rw-rw-r--. 1 xxxx      41 Oct  2 15:44 Setup.local

**Comment by ebrevdo** [comment]
Interesting.  Can you run the python-config associated with that python
bin?  i imagine it's something like:

/share/software/python/2.7.10/Python-2.7.10/release/python-config

can you run it separately with each of: --ldflags, --cflags, --includes,
--libs, --prefix, --exec-prefix?

thanks!

**Comment by zhiyun** [comment]
I am using /share/software/python/2.7.10/Python-2.7.10/release/bin/python in configure under tensorflow, but have that error.
There is a 
/share/software/python/2.7.10/Python-2.7.10/release/bin/python2.7-config file, are you suggesting me to do anything with this file? 
thanks a lot!

**Comment by zhiyun** [comment]
Here is the result (your comment was folded previously, and did not get the flags the first time)
/share/software/python/2.7.10/Python-2.7.10/release/bin/python-config --ldflags
-lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic

/share/software/python/2.7.10/Python-2.7.10/release/bin/python-config --cflags
-I/share/software/python/2.7.10/Python-2.7.10/release/include/python2.7 -I/share/software/python/2.7.10/Python-2.7.10/release/include/python2.7 -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes


/share/software/python/2.7.10/Python-2.7.10/release/bin/python-config --includes
-I/share/software/python/2.7.10/Python-2.7.10/release/include/python2.7 -I/share/software/python/2.7.10/Python-2.7.10/release/include/python2.7

/share/software/python/2.7.10/Python-2.7.10/release/bin/python-config --libs
-lpython2.7 -lpthread -ldl -lutil -lm

/share/software/python/2.7.10/Python-2.7.10/release/bin/python-config --prefix
/share/software/python/2.7.10/Python-2.7.10/release

/share/software/python/2.7.10/Python-2.7.10/release/bin/python-config --exec-prefix
/share/software/python/2.7.10/Python-2.7.10/release

**Comment by ebrevdo** [comment]
On my machine, libpython...so is in
  /usr/lib/python2.7/config-x86_64-linux-gnu
and my python-config --ldflags adds this line:
  -L/usr/lib/python2.7/config-x86_64-linux-gnu -L/usr/lib

in contrast, on your system we can't use python-config to get the location of the so file.

In addition, while on my system I can find a copy of the .so file in my LIBPL directory, on your system it isn't there.  It's very strange.

You seem to have a fairly nonstandard installation of python 2.7.  Are you an administrator of this machine?  Perhaps you could reinstall python?  Or install a version of python in your home directory, where you have write permissions and can install a properly built version?

**Comment by girving** [comment]
@vrv: Reassigning since Eugene is out.

**Comment by zhiyun** [comment]
Hi,
Here is an update. Unfortunately I don't have admin access to the machine.
I installed another python with config
./configure --prefix=$PWD/release/ --enable-shared LDFLAGS="-L$PWD/release/lib/python2.7/config -Wl,--rpath=$PWD/release/lib/python2.7/config -L$PWD/release/lib/ -Wl,--rpath=$PWD/release/lib/" CPPFLAGS="-I$PWD/release/include"
(I found these from some stackoverflow answers, though I don't fully understand how it works yet)

though libpython...so is still not under lib/python2.7/config/, nor does python-config --ldflags
-lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic return -L....

I was able to get pass that libpython2.7.so.1.0 not found error building tensorflow.

But I encountered error
/usr/bin/env: python2.7: No such file or directory
ERROR: /share/software/tensorflow/google/protobuf/BUILD:270:1: Linking of rule '//google/protobuf:protoc' failed: crosstool_wrapper_driver_is_not_gcc failed: ....

because the command generated by bazel seems not to set the PATH variable (I do not understand why)
(cd /home/zhiyunlu/.cache/bazel/_bazel_zhiyunlu/d568262eb4464bf011ab3d998aff21ac/tensorflow && \
  exec env - \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc....)

So I fixed the problem by changing the first line of crosstool_wrapper_driver_is_not_gcc to be
#!/share/software/python/2.7.10/Python-2.7.10-tf/release/bin/python2
to run with specific python I installed.

With some other modifications to use local gcc installation version ([issue649](https://github.com/bazelbuild/bazel/issues/649)), I am able to build tensorflow successfully.

I saw many warnings, for example
warning: calling a __host__ function from a __host__ __device__ function is not allowed.
But I assume it is okay...?

So I think the libpython...so problem is fixed now. Thanks a lot for helping this out!

**Comment by ebrevdo** [comment]
The warnings are fine. The underlying Eigen library doesn't always mark
functions as OK to run on a gpu, even if they are. That results in many of
the warnings.
