### ISSUE TITLE
memory leak in tf(2.2).keras.Model.predict function

### ISSUE THREAD

**Issue by bruceliuxing** [tensorflow/tensorflow#41404]
pre:
1. train detection model  using tf.keras under tf2.2 version
2. inference using tf.compat.v1.keras 
 config = tf.compat.v1.ConfigProto()
 config.gpu_options.per_process_gpu_memory_fraction = 0.25
  sess = tf.compat.v1.Session(config = config)
  tf.compat.v1.keras.backend.set_session(sess)

3. load model: 
   model = tf.keras.models.load_model(self.modelpath, compile=False)

found memory leak using [model.predict(image_np)] to get prediction

is this a serious bug in tf.keras.model.predict function???

**Comment by bruceliuxing** [comment]
finally I found  using [model(image_np)] can avoid memory leak

**Comment by amahendrakar** [comment]
> finally I found using [model(image_np)] can avoid memory leak

@bruceliuxing,
Is this still an issue? Please feel free to close the issue if resolved. Thanks!

**Comment by bruceliuxing** [comment]
look forward to be fixed in the future version
