### ISSUE TITLE
Build TensorFlow 2.3 from source for the Raspberry Pi (Python 3.7)

### ISSUE THREAD

**Issue by vinorth05** [tensorflow/tensorflow#41415]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04 LTS
- TensorFlow installed from : Git repository
- TensorFlow version: 2.3.0rc0
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip

**Describe the problem**

Hello, 

I would like to build a wheel file for my Raspberry Pi 3B (Buster) with TensorFlow version 2.3.0rc0.
So I run the following command : 
```CI_DOCKER_EXTRA_PARAMS="-e CI_BUILD_PYTHON=python3 -e CROSSTOOL_PYTHON_INCLUDE_PATH=/usr/include/python3.7"     tensorflow/tools/ci_build/ci_build.sh PI-PYTHON37     tensorflow/tools/ci_build/pi/build_raspberry_pi.sh```

However, the output I obtain is the wheel file for Python 3.5 so it won't work for my RPI..
So is my command correct? 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Output can be found here:
output-artifacts
output-artifacts/tensorflow-2.3.0rc0-cp35-none-linux_armv7l.whl
output-artifacts/benchmark_model
output-artifacts/libtensorflow_framework.so
output-artifacts/libtensorflow.so

**Comment by Saduf2019** [comment]
@vinorth05 
Can you please refer to this issue with similar error and update.
#35116

**Comment by terryheo** [comment]
@vinorth05 there was an issue with Python 3.7 build script. Could you try it again with master?

Now the build command is simpler.
```
$  tensorflow/tools/ci_build/ci_build.sh PI-PYTHON37 \
    tensorflow/tools/ci_build/pi/build_raspberry_pi.sh
```
