### ISSUE TITLE
Built-in Method to check if a GPU is already Reserved

### ISSUE THREAD

**Issue by EnderWiggin14** [tensorflow/tensorflow#41418]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): tf-nightly==2.3.0dev20200622 & tf-nightly-gpu==2.3.0dev20200622
- Are you willing to contribute it (Yes/No): No - this is far beyond my current abilities

**Describe the feature and the current behavior/state.**
The idea is to have a TF 2.X compatible function that checks to see which GPUs/Resources that are actually available for computation as opposed to simply addressable. An example of this would be running one python script that assigns only 1 gpu out of 2 available gpus, and then another python script, in a completely separate instance, would call said function to check which of the 2 gpus is currently being used and which is available to still be used.

**Will this change the current api? How?**
It would add a new function/method to a module. It shouldn't need to modify currently existing methods.
**Who will benefit with this feature?**
Anyone who wants to run multiple instances of a training script without having to explicitly program which GPU/CPU/TPU to use. There are certainly ways to do this task, but they require the usage of either custom message passing, bash scripted resource management, or an external python script that uses multiprocessing or subprocess packages. Having something that can give a status update on truly available resources would be useful.

**Additional Info**
It is possible that this is done behind the scenes in tensorflow already. If it is, it is not clearly reflected in Tensorflow documentation. However, it would appear that it isn't done behind the scenes because I have network and dataset that causes core dumps on a 2 gpu system if I run two instances but succeeds if I run only one instance. As far as I can tell it's because the GPUs are running out of memory.

**Comment by sanjoy** [comment]
We can probably base this off of the amount of GPU memory allocated -- if only a small fraction of the GPU memory is left we can (practically) assume that the GPU is "reserved" by another TF process.

**Comment by tilakrayal** [comment]
@EnderWiggin14,
Could you please try the code that will return free GPU memory in MegaBytes for each GPU:

```
import subprocess as sp
import os

def get_gpu_memory():
    command = "nvidia-smi --query-gpu=memory.free --format=csv"
    memory_free_info = sp.check_output(command.split()).decode('ascii').split('\n')[:-1][1:]
    memory_free_values = [int(x.split()[0]) for i, x in enumerate(memory_free_info)]
    return memory_free_values

get_gpu_memory()
```


Also please take a look at the below doc for the reference.
https://www.tensorflow.org/api_docs/python/tf/config/experimental/get_memory_info

Thank you!
