### ISSUE TITLE
Output of tf.keras.utils.Sequence is automatically cast to Tensor even if it is a SparseTensor

### ISSUE THREAD

**Issue by danielegrattarola** [tensorflow/tensorflow#41419]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Catalina 10.15.5
- TensorFlow installed from (source or binary): binary 
- TensorFlow version (use command below): 2.2.0
- Python version: 3.8

**Describe the current behavior**
All outputs produced by `tensorflow.keras.utils.Sequence` are automatically cast to `Tensor` when calling `model.fit()`, even if they are of class `SparseTensor`.
This makes it impossible to use sparse operations in a model if the model is trained with the Keras training loop. 

**Describe the expected behavior**
`model.fit()` should not automatically cast the inputs to `Tensor` if the inputs are supported by TensorFlow operations.

**Standalone code to reproduce the issue**
```python
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.utils import Sequence


class Dataset(Sequence):
    def __init__(self):
        pass

    def __len__(self):
        return 1

    def __getitem__(self, idx):
        return tf.SparseTensor([[0, 1], [1, 0]], [1, 1], (2, 2))


class Net(Model):
    def __init__(self):
        super().__init__()

    def call(self, x, **kwargs):
        return x.values


net = Net()
net.compile()
net.fit(Dataset())
```

Causes the following error:
```python
AttributeError: 'Tensor' object has no attribute 'values'
```

**Comment by danielegrattarola** [comment]
Possibly related issue: https://github.com/tensorflow/tensorflow/issues/16689
It seems like TF casts inputs to `Tensor` by default, even when it shouldn't

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.2, TF v2.3.0rc1 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/7b77c8a55e6003da0d01ca45ee7e129e/41419.ipynb). Thanks!

**Comment by karmel** [comment]
The Keras Sequence utility works well with numpy arrays, but for TensorFlow composite tensor types like RaggedTensor and SparseTensor, we would recommend you use tf.data.Datasets. You can read more about how to use Datasets in your input pipeline here: https://www.tensorflow.org/guide/data

**Comment by danielegrattarola** [comment]
@karmel The two do not share the same functionality. 
With tf.keras.Sequence I can have logic inside my generator that dynamically decides the batch size, and `model.fit()` will not care about it. 
On the other hand, tf.data.Dataset delegates the choice of batch size to the training loop, so it cannot have dynamic batch sizes. 

This is especially limiting when working with graphs and graph neural networks, as it does not allow to have batches of graphs with different sizes which can be produced by a generator and consumed by the model. 

tf.keras.Sequence *would* be suitable to do this, if it didn't force all outputs to be Tensors. This is unnecessarily constraining.

Cheers
