### ISSUE TITLE
Docs: incomplete description of callbacks.ModelCheckpoint's save_best_only parameter

### ISSUE THREAD

**Issue by bersbersbers** [tensorflow/tensorflow#41420]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/ModelCheckpoint

## Description of issue (what needs changing):

1. `mode`: "{auto, min, max}" should be `{auto, min, max}`, I guess (minor)
2.  `save_best_only`: I believe the description is incomplete. With `save_best_only=True`, not only will "the latest best model [...] not be overwritten": but also the current model is not written at all, even if it has another filename than the "latest best model". This is kind of implied by the name of the parameter, but the description should include that, too.

**Comment by yil532** [comment]
Hi Can I create a PR to fix this?

**Comment by yil532** [comment]
PR to fix this issue is here https://github.com/tensorflow/tensorflow/pull/41567
Please review, thank

**Comment by jvishnuvardhan** [comment]
This is already fixed by https://github.com/tensorflow/tensorflow/pull/41567. Please check the updated `tf-nightly` page https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/ModelCheckpoint?version=nightly.

I am closing this issue as this was already resolved. Thanks!
