### ISSUE TITLE
Python Keras code out of memory for no apparent reason

### ISSUE THREAD

**Issue by ivdorelian** [tensorflow/tensorflow#41428]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu Server 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): conda
- TensorFlow version (use command below): 2.2.0
- Python version: 3.7
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 10.2 / 7.6.5
- GPU model and memory: Geforce GTX Titan X 12 GB RAM, 16 GB system RAM

**Describe the current behavior**
See this Stackoverflow question for details: https://stackoverflow.com/questions/62917349/python-keras-code-out-of-memory-for-no-apparent-reason

**Describe the expected behavior**
The code shouldn't cause Python to crash with code 137. I have over 12 GB system RAM available and nothing else is using the GPU.

**Standalone code to reproduce the issue**

Code causes Python to crash with exit code 137 around 1 (sometimes a bit more, sometimes a bit less) iteration of the outer for loop. System memory usage keeps increasing while the program is running.

```
import tensorflow as tf
from sklearn.datasets import fetch_openml
from sklearn.utils import shuffle

data, targets = shuffle(*fetch_openml('CIFAR_10', version=1, return_X_y=True)) # same happens if I force these to be float32s
train_sz = 50000
X_train, X_test, y_train, y_test = data[:train_sz, :], data[train_sz:, :], np.asarray(targets[:train_sz], dtype=np.int), np.asarray(targets[train_sz:], dtype=np.int)

model = tf.keras.Sequential()
model.add(tf.keras.Input(shape=(X_train.shape[1],)))
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(10))
model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), optimizer='adam')

s = 0
for _ in range(500):
    for i in range(100):
        layers = []
        for layer in model.get_weights():
            layers.append(np.random.normal(0, 1, layer.shape))
        model.set_weights(layers)
        eval = model.evaluate(X_train, y_train)
        s += eval
        print(f'Done {i}')
print(s)
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.2 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/1523dedba35e4dca42822053dce2512a/41428.ipynb). Thanks!

**Comment by omalleyt12** [comment]
@ivdorelian Thanks for the issue!

Can you try running `tf.keras.backend.clear_session()` periodically when calling the `set_weights` in a loop? There are some global-graph-related things in Keras that we are working on getting rid of, but the `clear_session()` call usually helps to release the memory from these items

**Comment by ivdorelian** [comment]
@omalleyt12 thanks for the reply!

Unfortunately, adding that at the end of the second for loop doesn't help.

What did help though was not doing it like this:

```
preds = model(X_train)
eval = my_loss(y_train, preds)
```

Note that calling `.predict()` followed by `my_loss(...)` results in the same issue.

In my case this isn't a huge issue, although it would be nice to be able to pass in a batch size to evaluate.

**Comment by jvishnuvardhan** [comment]
@ivdorelian Is this still an issue for you. There were some performance improvements over the last few months. I tested your code with `tf-nightly` and it was running without memory issues. i ran outer `for` loop for 10 iterations without any issue. As it was taking long time, i interrupted execution. 

[Here](https://colab.research.google.com/gist/jvishnuvardhan/ccff56d41112909cdee938cb411cd518/41428.ipynb) is a gist for your reference. 

The only change i did was adding `tf.keras.backend.clear_session()` as mentioned by @omalleyt12 and added `gc.collect()`

```
s = 0
for j in range(100):
    for i in range(100):
        layers = []
        for layer in model.get_weights():
            layers.append(np.random.normal(0, 1, layer.shape))
        model.set_weights(layers)
        eval = model.evaluate(X_train, y_train)
        s += eval
        tf.keras.backend.clear_session()
        gc.collect()
        print(f'Done {i}')
    print('*'*100)
    print(f'Done {j}')
        
print(s)
```

Please close the issue if this was resolved for you. Thanks!
