### ISSUE TITLE
Tensorflow keras timeseries prediction with X and y having different shapes

### ISSUE THREAD

**Issue by Nestak2** [tensorflow/tensorflow#41422]
I am trying to do time series prediction with tensorflow and keras with `X` and `y` having different dimensions:

```
X.shape = (5000, 12)
y.shape = (5000, 3, 12)
```
When I do the following

```
n_input = 7
generator = TimeseriesGenerator(X, y, length=n_input, batch_size=1)

for i in range(5):
    x_, y_ = generator[i]
    print(x_.shape)
    print(y_.shape)
```
I get as desired the output

```
(1, 7, 12)
(1, 3, 12)
(1, 7, 12)
(1, 3, 12)
...
```
This is because my data is meteorological, I have 5000 days, for training in the array `X` I use a sliding window of 7 days, with each day containing 12 features (air pressure, temperature, humidity a.o.). And in the target array `y` I have sliding windows of 3 days, trying to predict the next 3 days to each window of 7 days.

But then when I try to fit the model I get an error due to the mismatch in the shape of the `X` and `y` arrays:

```
model = Sequential()
model.add(LSTM(4, input_shape=(None, 12)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
history = model.fit_generator(generator, epochs=3).history
```

`ValueError: A target array with shape (1, 3, 12) was passed for an output of shape (None, 1) while using as loss "mean_squared_error". This loss expects targets to have the same shape as the output.`

So is there a way to adjust the architecture for the mismatch in the dimensions? Or is there a way to reshape `X` and y to make them work with this architecture? I tried the late reshaping `X` into (5000, 7, 12), but this gave also a dimensionality error. Tnx

**Comment by Dynmi** [comment]
1. The reason for the *ValueError* you encountered is that the model you build outputs a tensor with shape (None, 1) while your data *y* has a shape (None, 3, 12), but they don't match!
2. I guess your intension is to build a model with input_shape=(None, 7, 12) & output_shape=(None, 3, 12). The best way is to change the shape of *Y* to (None, 36), as followed:
```
y=np.reshape(y,(-1,y.shape[-1]*y.shape[-2]))

n_input = 7
generator = TimeseriesGenerator(X, y, length=n_input, batch_size=1)

model = Sequential()
model.add(LSTM(64, input_shape=(7, 12)))
model.add(Dense(Y.shape[-1]))
model.summary()
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])
history = model.fit_generator(generator, epochs=3).history
```

**Comment by Saduf2019** [comment]
@Nestak2 
Please refer to [this link](https://stackoverflow.com/questions/58578374/how-can-i-change-my-data-to-make-it-work-with-loss-mean-squared-error) with same error and let us know. Thanks!

**Comment by Nestak2** [comment]
@Dynmi Thanks for the suggestion, I found out that I could also use an architecture with max pooling for my problem, e.g. this would work 

```
model = Sequential()
model.add(LSTM(4, return_sequences=True, input_shape=(n_input, 12)))
model.add(MaxPool1D(2)) # also AvgPool1D is ok
model.add(Dense(12))
model.compile(loss='mean_squared_error', optimizer='adam')

model.summary()
model.fit(generator, epochs=2)
```

Do you have an opinion which of the 2, maxpooling vs. your suggestion, would be a better solution (give more accurate results)?
Somehow I fear to follow your suggestion of turning the shape of `y` from (None, 3, 12) to (None, 36), because the neural network would lose track of what feature is what, but this is only an intuition of mine and not tested

**Comment by Dynmi** [comment]
Hhh, You can try both of them and see which one works better.
After all, Practice is the sole criterion for testing truth.

**Comment by Saduf2019** [comment]
@Nestak2 
Please update as per above comment.
