### ISSUE TITLE
Issue with running post quantized TF Lite on ArmNN

### ISSUE THREAD

**Issue by kg512** [tensorflow/tensorflow#41438]
I am have following setup:

Original Model: Retrained Mobilenetv2 with lesser classes (using TF-Keras APIs)
Converted Model: Post quantized- Full integer quantization- uint8 TFLite Model (using TF-Keras APIs)
Tensorflow version: 1.15

I am trying to run this model on a GPU using ArmNN support.

_I faced the following issue:_

Optimize graph and load the optimized graph onto a compute device...
Warning: WARNING: Layer of type Convolution2d is not supported on requested backend GpuAcc for input data type QAsymmS8 and output data type QAsymmS8 (reason: in validate src/runtime/CL/functions/CLGEMMConvolutionLayer.cpp:423: Input data type not compatible with Weights), falling back to the next backend.
Warning: ERROR: Layer of type Convolution2d is not supported on any preferred backend [GpuAcc ]

_I got the following reply from ArmNN git:_

That error occurs if the weights are QSymm8 with per channel quantization (that's QSYMM8_PER_CHANNEL) and the input is not QAsymm8. In this case your input is QAsymmS8 so it's not supported right now.
In order to use the GpuAcc you would have to retrain the model to use QASymm8 instead of QAsymmS8 or not to use per channel quantization on your weights.

**Link**: https://github.com/ARM-software/armnn/issues/425

I don't quite understand how I can do the above mentioned using the TFLite Converter. Please help. Thanks in advance

**Comment by Saduf2019** [comment]
@kratika5 
Please share a simple stand alone indented code for us to replicate the issue faced or if possible share a colab gist with the error faced.

**Comment by kratika5** [comment]
Here is a link to Keras model training and conversion to TFLite:
https://colab.research.google.com/drive/1lLSimDVdU2oFYH1HH00uYyzRogWkFCuJ?usp=sharing

For the second part, as it runs on an embedded platform, I cannot share a direct colab.
I am using this test code provided by ArmNN and I use the TFLite model generated above. 
Just for additional information, pretrained quantized models as well as a quantize-aware trained uint8 model (using TF1.15 Slim) work fine with ArmNN.

**Comment by terryheo** [comment]
Could you share which datatype of the model ArmNN is complaining?
"src/runtime/CL/functions/CLGEMMConvolutionLayer.cpp:423: Input data type not compatible with Weights), falling back to the next backend."

**Comment by kratika5** [comment]
The model I have is a uint8 (post quantized model), the error mentioned above says:
Input/Output Datatypes - QAsymmS8

**Comment by terryheo** [comment]
@daverim could you guide this?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
