### ISSUE TITLE
SERLU activation function support

### ISSUE THREAD

**Issue by SungmanHong** [tensorflow/tensorflow#41443]
here, SERLU activation function works better than elu or RELU or leakyRELU

https://www.researchgate.net/figure/Subplot-a-shows-6-different-activation-functions-where-their-main-differences-sit-in_fig1_326646583

I wonder, if tensorflow can officially support SERLU in next update

**Comment by caltrops6490** [comment]
good stuff I'm still very far from feeling like I can contribute +!

**Comment by seanpmorgan** [comment]
> /cc @seanpmorgan

Happy to have this as a PR in TensorFlow Addons if it is deemed not widely applicable or yet proven by TF core team:
https://github.com/tensorflow/addons

**Comment by saikumarchalla** [comment]
@SungmanHong  Due to lack of recent activity we are closing this issue. Please feel free to reopen the issue if necessary.

 As per @seanpmorgan  comment  could you please submit a  Pull Request  in the addons [repo](https://github.com/tensorflow/addons/pulls).Thanks!
