### ISSUE TITLE
windows build issues(finally made it)

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#41446]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4.0
- Python version: 3.8.3 x64
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 3.4.1
- GCC/Compiler version (if compiling from source): visual studio 2019
- CUDA/cuDNN version: 11.0/8.0.1
- GPU model and memory: RTX2070 GDDR6 8GB

**Describe the problem**
many problems with windows build, and I made a few fixes

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. cudnn_stub  dependency problem ( https://github.com/tensorflow/tensorflow/issues/41057 )
I simply add dependency in that BUILD

2. then thrust version unmatch error
I delete thrust version - cub version comparison codes from
bazel-out\x64_windows-opt\bin\external\local_config_cuda\cuda\cuda\include\thrust\system\cuda\config.h

3. finally, big old numpy problem
this has been very long and unsolvable error, I made same fix as before( simply pip uninstall numpy ( uninstall conda numpy ) and pip install numpy )

and still there are too many "ignoring unknown options" from cl

anyway now I succeeded build and have my wheel file

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
> anyway now I succeeded build and have my wheel file

@alanpurple,
Is this still an issue? Please feel free to close the issue if resolved. Thanks!

**Comment by alanpurple** [comment]
this is 4 issues, 3 I fixed myself,  1(warnings) I can't fix

**Comment by alanpurple** [comment]
think of this post as kinda PR since I made fixes

**Comment by amahendrakar** [comment]
@alanpurple,
In this case, could you please submit a new PR for the fix. Thanks!

**Comment by alanpurple** [comment]
@amahendrakar 

Is conda numpy problem unsolvable?

**Comment by amahendrakar** [comment]
> Is conda numpy problem unsolvable?

Could you please describe this issue and provide the steps to reproduce it, so that we can look into it? Thanks!

**Comment by alanpurple** [comment]
@amahendrakar 
#35977

**Comment by amahendrakar** [comment]
@alanpurple,
Can we close this issue since it is already being tracked there? Thanks!

**Comment by alanpurple** [comment]
@amahendrakar 

ok

**Comment by isleong** [comment]
@surak I believe this is what he did: 
https://github.com/tensorflow/tensorflow/pull/41822/commits/d480a3ad713e50057a2b1a611e7cacd6bbca1eb5

Didn't realize that cudnn_version.h was already defined somewhere in the file. Anyhow, tried it again with fresh source for 2.3.0 and with this change and it builds successfully on Windows now.

**Comment by surak** [comment]
I still get a directory without the correct file. All I get is

```sh
In file included from tensorflow/stream_executor/cuda/cudnn_stub.cc:15:
bazel-out/k8-py2-opt/bin/external/local_config_cuda/cuda/_virtual_includes/cudnn_header/third_party/gpus/cudnn/cudnn.h:59:10: fatal error: cudnn_version.h: No such file or directory
   59 | #include "cudnn_version.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
SUBCOMMAND: # //tensorflow/core:function_ops_op_lib [action 'Compiling tensorflow/core/ops/function_ops.cc']
(cd /tmp/eb-w9wkEo/tmpSnNZgZ-bazel-build/execroot/org_tensorflow && \
```

And this directory has 

```bash
ls -la bazel-out/k8-py2-opt/bin/external/local_config_cuda/cuda/_virtual_includes/cudnn_header/third_party/gpus/cudnn
total 12
drwxrwxr-x 2 strube1 jusers 4096 Aug 25 19:27 .
drwxrwxr-x 3 strube1 jusers 4096 Aug 25 19:27 ..
lrwxrwxrwx 1 strube1 jusers  139 Aug 25 19:27 cudnn.h -> /tmp/eb-w9wkEo/tmpSnNZgZ-bazel-build/execroot/org_tensorflow/bazel-out/k8-py2-opt/bin/external/local_config_cuda/cuda/cudnn/include/cudnn.h
```

I don't really understand Bazel's syntax. Can you help me with that?

**Comment by surak** [comment]
@isleong @alanpurple turns out that it's somewhere else. cudnn 8 has different headers from that cudnn.h and bazel fails to identify the correct version. It's at `third_party/gpus/cuda_configure.bzl` line 1164:

This is the problematic part:
```python
    if [int(x) for x in cuda_config.cudnn_version.split(".")] < [8, 0]:
      cudnn_headers = ["cudnn.h"]
    else:
      cudnn_headers = ["cudnn_adv_infer.h",
                       "cudnn_adv_train.h",
                       "cudnn_cnn_infer.h",
                       "cudnn_cnn_train.h",
                       "cudnn_ops_infer.h",
                       "cudnn_ops_train.h",
                       "cudnn.h",
                       "cudnn_version.h",
                      ]
```

This cudnn version is somehow wrong. 

This is my patch:

```diff
--- third_party/gpus/cuda_configure.bzl.orig	2020-08-26 18:55:08.405838123 +0200
+++ third_party/gpus/cuda_configure.bzl		2020-08-26 19:24:47.466666178 +0200
@@ -1136,10 +1136,11 @@
         out_dir = "cuda/bin",
     ))
 
-    if [int(x) for x in cuda_config.cudnn_version.split(".")] < [8, 0]:
-      cudnn_headers = ["cudnn.h"]
-    else:
-      cudnn_headers = ["cudnn_adv_infer.h",
+    #if [int(x) for x in cuda_config.cudnn_version.split(".")] < [8, 0]:
+    #  cudnn_headers = ["cudnn.h"]
+    #else:
+    cudnn_headers = ["cudnn_adv_infer.h",
+                       "cudnn_backend.h",
                        "cudnn_adv_train.h",
                        "cudnn_cnn_infer.h",
                        "cudnn_cnn_train.h",
```

This will break with older cuDNNs, but turns out that because check fails, I really don't care. I only need this version of TensorFlow for the A100 gpus, which only support CUDA 11 and cuDNN 8+ anyway.
