### ISSUE TITLE
model_from_json return deserialize(config, custom_objects=custom_objects), How to remove this error?

### ISSUE THREAD

**Issue by Dilshad737** [tensorflow/tensorflow#41442]
**I am using this code:**

```
import numpy as np
import cv2
from keras.preprocessing import image
import time

#-----------------------------
#opencv initialization

face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

#-----------------------------
#face expression recognizer initialization
from keras.models import model_from_json
model = model_from_json(open("facial_expression_model_structure.json", "r").read())
model.load_weights('facial_expression_model_weights.h5') #load weights
#-----------------------------
```
**I am getting this error:**

```
File "emotion-analysis-from-video.py", line 15, in <module>
    model = model_from_json(open("facial_expression_model_structure.json", "r").read())
  File "C:\Users\DILSHAD\Desktop\lfe\lib\site-packages\tensorflow\python\keras\saving\model_config.py", line 116, in model_from_json
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\DILSHAD\Desktop\lfe\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 105, in deserialize
    return deserialize_keras_object(
  File "C:\Users\DILSHAD\Desktop\lfe\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 361, in deserialize_keras_object
    (cls, cls_config) = class_and_config_for_serialized_keras_object(
  File "C:\Users\DILSHAD\Desktop\lfe\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 325, in class_and_config_for_serialized_keras_object
    for key, item in cls_config.items():
AttributeError: 'list' object has no attribute 'items'
```
**Here is the result of my pip freeze:**

```
absl-py==0.9.0
astunparse==1.6.3
cachetools==4.1.1
certifi==2020.6.20
chardet==3.0.4
cycler==0.10.0
decorator==4.4.2
efficientnet==1.1.0
gast==0.3.3
google-auth==1.19.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.30.0
h5py==2.10.0
idna==2.10
imageio==2.9.0
Keras==2.4.3
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
kiwisolver==1.2.0
Markdown==3.2.2
matplotlib==3.2.2
networkx==2.4
numpy==1.19.0
oauthlib==3.1.0
opencv-contrib-python==4.3.0.36
opt-einsum==3.2.1
Pillow==7.2.0
protobuf==3.12.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==2.4.7
python-dateutil==2.8.1
PyWavelets==1.1.1
PyYAML==5.3.1
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
scikit-image==0.17.2
scipy==1.4.1
six==1.15.0
tensorboard==2.2.2
tensorboard-plugin-wit==1.7.0
tensorflow==2.2.0
tensorflow-estimator==2.2.0
termcolor==1.1.0
tifffile==2020.7.4
urllib3==1.25.9
Werkzeug==1.0.1
wrapt==1.12.1
```
I run this code about a month ago It runs without any error! Now I created a new virtualenv for it and now it is not working fine!!! Any actionable help with be appreciated!!!

**Comment by Saduf2019** [comment]
@Dilshad737 
I ran the code shared by you and face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/bbf213e050ab8b2ff175b0af39baf176/untitled281.ipynb), please share all dependencies to replicate the issue or share a colab gist with the error.

Can you change your imports from keras to tensorflow.keras and confirm if issue persists?

With respect to the error faced refer to below issue:
#35934 #38135 [link](https://forum.cogsci.nl/discussion/5318/unexpected-error-attributeerror-list-object-has-no-attribute-copy) [link](https://stackoverflow.com/questions/33949856/why-i-get-list-object-has-no-attribute-items)

**Comment by Dilshad737** [comment]
> @Dilshad737
> I ran the code shared by you and face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/bbf213e050ab8b2ff175b0af39baf176/untitled281.ipynb), please share all dependencies to replicate the issue or share a colab gist with the error.
> 
> Can you change your imports from keras to tensorflow.keras and confirm if issue persists?
> 
> With respect to the error faced refer to below issue:
> #35934 #38135 [link](https://forum.cogsci.nl/discussion/5318/unexpected-error-attributeerror-list-object-has-no-attribute-copy) [link](https://stackoverflow.com/questions/33949856/why-i-get-list-object-has-no-attribute-items)

I ran the code in Google colab all is working fine but when I run it on my local machine it produces the same error I mentioned earlier!!!!

**Comment by Saduf2019** [comment]
@Dilshad737 
Can you share the steps followed before you faced this issue, please provide all details.

**Comment by Dilshad737** [comment]
gestyy.com/ewzP5P

**Comment by gowthamkpr** [comment]
@Dilshad737 Please use anaconda environment in your local machine and let me know if the error still persists. I am unable to reproduce this issue. Thanks!
