### ISSUE TITLE
macos not raising OOM error

### ISSUE THREAD

**Issue by scarrazza** [tensorflow/tensorflow#41457]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Catalina 10.15
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.x

**Describe the current behavior**

When allocating a large tensor on macos the code is killed by the kernel instead of raising a OOM error.

**Describe the expected behavior**

The code above should raise a Resource Exhausted OOM error, as it does on Linux.

**Standalone code to reproduce the issue**

Here a minimal example:
```python
import tensorflow as tf
tf.ones(2**40, dtype=tf.complex128)
```

**Comment by mihaimaruseac** [comment]
It is likely macos throws a different error that we don't manage to capture. Thanks for pointing the issue out

**Comment by mohantym** [comment]
Hi @scarrazza! 
We are checking to see whether you still need help in this issue . Have you tried this [thread ](https://developer.apple.com/metal/tensorflow-plugin/)for Tensorflow installation in Mac OS yet? . Thanks!
