### ISSUE TITLE
LUP factorization (tensorflow.linalg.lu) throws "Input is not invertible" error.

### ISSUE THREAD

**Issue by touqir14** [tensorflow/tensorflow#41451]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Mint 20
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not tested
- TensorFlow installed from (source or binary): binary. Installed tensorflow-2.2.0-cp38-cp38-manylinux2010_x86_64.whl from https://www.wheelodex.org/projects/tensorflow/
- TensorFlow version (use command below):
- Python version: v2.2.0-rc4-8-g2b96f3662b
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: Cuda: 10.1.243 and cuDNN: 7.6.5
- GPU model and memory: GTX 1050 (Notebook) with 4GB

When I am trying to compute the LUP factorization of a particular type of rank deficient square matrix using tensorflow.linalg.lu, I am getting the following error regarding the input being non-invertible:

```python
Traceback (most recent call last):
  File "LU_bug.py", line 10, in <module>
    lu, _ = tf.linalg.lu(A_tensor)
  File "/home/touqir/pyenvs/py3.8/lib/python3.8/site-packages/tensorflow/python/ops/gen_linalg_ops.py", line 1183, in lu
    _ops.raise_from_not_ok_status(e, name)
  File "/home/touqir/pyenvs/py3.8/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6653, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input is not invertible. [Op:Lu]
```

The following code reproduces the above error message:
```python
import numpy as np
import tensorflow as tf

A = np.random.rand(4,6)
m, n = A.shape
A_tensor = np.zeros(shape=[m+n, m+n], dtype=A.dtype)
A_tensor[:m, :n] = A
A_tensor[-n:, -m:] = A.T
A_tensor = tf.convert_to_tensor(A_tensor)
lu, _ = tf.linalg.lu(A_tensor)
```

However, LUP factorization does not require the input to be a full rank matrix. ie. not invertible. I have tried with other types of rank deficient square matrices for which tensorflow's LUP factorization works fine.

**Comment by ravikyram** [comment]
I have tried in colab with TF versions 2.2, 2.3-rc1,nightly versions(`2.4.0-dev20200716`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/c5316f4ca70a6918564972b1a8c8830c/untitled142.ipynb).Thanks!

**Comment by jvishnuvardhan** [comment]
@touqir14 From the [TF website](https://www.tensorflow.org/api_docs/python/tf/linalg/lu), `The input has to be invertible.` but the input is not invertible in your case. Just printed the `input`. Please let me know what you think. Thanks!

```
tf.Tensor(
[[0.13732078 0.36229924 0.76132223 0.0201788  0.89308874 0.98938961
  0.         0.         0.         0.        ]
 [0.024854   0.54382015 0.27550137 0.40642625 0.76440885 0.9682706
  0.         0.         0.         0.        ]
 [0.25347575 0.13755833 0.33073567 0.05386851 0.79757004 0.56537101
  0.         0.         0.         0.        ]
 [0.44360238 0.34834656 0.13454647 0.82118215 0.21367512 0.05590622
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.13732078 0.024854   0.25347575 0.44360238]
 [0.         0.         0.         0.         0.         0.
  0.36229924 0.54382015 0.13755833 0.34834656]
 [0.         0.         0.         0.         0.         0.
  0.76132223 0.27550137 0.33073567 0.13454647]
 [0.         0.         0.         0.         0.         0.
  0.0201788  0.40642625 0.05386851 0.82118215]
 [0.         0.         0.         0.         0.         0.
  0.89308874 0.76440885 0.79757004 0.21367512]
 [0.         0.         0.         0.         0.         0.
  0.98938961 0.9682706  0.56537101 0.05590622]], shape=(10, 10), dtype=float64)
```

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210530,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/46a5a4758e3287007779ce892681eaa2/untitled137.ipynb)..Thanks !

**Comment by cantonios** [comment]
The LU implementation we use is a partial-pivoting scheme that only works on invertible matrices, or ones which the leading principal minors are all non-zero.  So it will *sometimes* work for non-invertible matrices.

For non-square matrices, Eigen has a full-pivoting LU decomposition: `A = P^{-1} L U Q^{-1}`.  We don't currently support this in tensorflow, and currently have no plans to.

Note that the partial-pivoting LU decomposition is not reliable for rank determination. See [Eigen's table of decompositions](https://eigen.tuxfamily.org/dox/group__TopicLinearAlgebraDecompositions.html).
