### ISSUE TITLE
tf.random.categorical overflow before OOM on GPU

### ISSUE THREAD

**Issue by scarrazza** [tensorflow/tensorflow#41458]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 LTS
- TensorFlow version (use command below): 2.2.0 and 2.1.0
- Python version: 3.x
- CUDA/cuDNN version: 10.1
- GPU model and memory: V100 32GB

**Describe the current behavior**

When running the `tf.random.categorical` with a large `num_samples` on a V100 with 32GB we get the following crash:
```bash
2020-07-15 21:58:02.621909: F ./tensorflow/core/util/gpu_launch_config.h:129] Check failed: work_element_count > 0 (-2099511296 vs. 0)
Aborted (core dumped)
```
This looks like an overflow before raising the OOM error.

Here a minimalist code which reproduces the aborted (core dumped) on the V100 with 32GB:
```python
import tensorflow as tf
probs = tf.random.uniform((2 ** 15,), dtype=tf.float64)
probs = probs / tf.reduce_sum(probs)
logits = tf.math.log(probs)
samples = tf.random.categorical(logits[tf.newaxis], 70000, dtype=tf.int64)[0]
```

Here some tests on different cards:
- V100 32GB, cuda 10.1, tf2.2 and tf2.1: Aborted (core dumped)
- V100 16GB, cuda 10.1, tf2.1: OOM
- TitanV 12GB, cuda 10.2, tf2.2: OOM
- RTX2080TI, 12GB, cuda 10.2, tf2.2: OOM

This issue only happens on V100 with 32GB.

**Describe the expected behavior**

The code should raise a Resource Exhausted OOM error instead of being aborted.

**Comment by scarrazza** [comment]
@amahendrakar, good idea, thanks. 

If I limit the V100 32GB to use just 16GB then I get the OOM error, as expected.
However, if I increase the memory to 18GB, then I get the usual `Aborted (core dumped)`.

**Comment by jvishnuvardhan** [comment]
@scarrazza Sorry for the late response. I tried reproducing it with recent `TF2.4rc3` in colab but didn't see OOM or coredump. [Here](https://colab.research.google.com/gist/jvishnuvardhan/db34461fc50a37fd5ee65c2f4808a938/untitled.ipynb) is the gist for reference. 

Can you please check and let us know whether the error still persists in recent TF version? Thanks!

**Comment by scarrazza** [comment]
@jvishnuvardhan I have tested your gist on Colab, however tensorflow-gpu==2.4rc3 doesn't seem to detect the GPU (check the `tf.config.list_physical_devices()` on your notebook), your code is running on CPU. 

I also tried to install 2.4rc3 on other machine with larger GPU memory however also there it doesn't detect the GPU device, so I can't test.

**Comment by sushreebarsa** [comment]
I have tried this using TF 2.5 version ,please check this gist [here](https://colab.research.google.com/gist/sushreebarsa/f6ebe38bde51d74a2aa9fd22bb58047f/untitled114.ipynb?authuser=1)..Thanks !

**Comment by sushreebarsa** [comment]
Closing this issue as it is fixed in latest version of TensorFlow. Please feel free to reopen the issue if you still have a concern. Thanks!
