### ISSUE TITLE
TF to s3a:// access needed

### ISSUE THREAD

**Issue by vaibhavsingh007** [tensorflow/tensorflow#41459]
There is funcionality for basic `s3://` scheme on Linux. Then there is work for tensorflow/community#101 to convert all these filesystem to a plugin based form so they can be used on all platforms, on demand.

Regarding `s3a` and `s3n`, can you file a new issue, feature request type, and assign it to me/mention me? just to keep this issue only for the `s3` not implemented error.

_Originally posted by @mihaimaruseac in https://github.com/tensorflow/tensorflow/issues/40302#issuecomment-659517610_

**Comment by p9anand** [comment]
@mihaimaruseac : when should we expect this feature?

**Comment by mihaimaruseac** [comment]
Modular filesystems are scheduled to land in TF 2.5.

**Comment by sachinprasadhs** [comment]
Could you please refer this https://github.com/tensorflow/tensorflow/issues/40302 issue and as per the latest comments in the linked issue the problem is solved, could you please confirm the same. Thank you!
