### ISSUE TITLE
Updating labels during online augmentations - ImageGenerator + imgaug

### ISSUE THREAD

**Issue by ectg** [tensorflow/tensorflow#41465]
Hi, 

I have been using imgaug with ImageGenerator's preprocessing_function for augmentations while training. This works well for non-geometric augmentations. 

My labels include location, orientation, etc, and they need to change when I apply geometric transformations like flip/rotate. The preprocessing_function takes in just one argument: "image", so I do not have the label information at the time of augmentation, in this callback function.

Is there a way to do this? Other that pre-augmenting the images.

(I am on TensorFlow 2.2, Windows 10)

**Comment by ravikyram** [comment]
@ectg 

Request you to share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by ectg** [comment]
This isn't an issue per se, but a question on whether such a feature exists. Here is what I do for online augmentations right now:

`datagen = ImageDataGenerator(preprocessing_function=additional_augmentation)`

The function additional_augmentation is user defined, with the stipulation that it takes in an image and nothing else. This function gets called for every image while training, and inside this function, I use the imgaug library to transform the image. But since I don't have access to the image label here, I cannot change it in response to geometric operations like flip. Hence I am sticking to non-geometric augmentations in the example below:

`from imgaug import augmenters as iaa`

```
aug = iaa.OneOf([iaa.ElasticTransformation(alpha=(0.1, 1.5), sigma=0.025),
                    iaa.Multiply((1, 1.5), per_channel=0.2),
                    iaa.ContrastNormalization((0.75, 2.5), per_channel=0.5),
                    iaa.GaussianBlur(sigma=(3, 10.0))
                    ])

```

```
def additional_augmentation(image):
aug.augment_image(image)
return image
```

The traingenerator is then declared as:
```
train_generator = datagen.flow_from_dataframe(dataframe=df_train,
                                                directory=train_dir,
                                                x_col='image',
                                                y_col=['x', 'y', 'dvx', 'dvy'],
                                                subset='training',
                                                batch_size=batch_size,
                                                shuffle=True,
                                                class_mode="raw", 
                                                target_size=(img_rows,img_cols))
```

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
