### ISSUE TITLE
Provide generic android JNI interface

### ISSUE THREAD

**Issue by llhe** [tensorflow/tensorflow#4146]
In the Android example, the developer need to write some customized C++ code for the JNI call, this extra effort is not needed especially in the prototyping step.

Could we provide a generic JNI interface (just like generic inference serving, with input/output as a map of tensors, using serialized protobuf bytes or customized serialization), then the developer will not need to write and BUILD C++ code anymore.

Of course, the developers are free to optimize the code by writing the customized JNI calls. This feature will definitely boost the development process.

**Comment by andrewharp** [comment]
We have to plans to provide a basic Java interface as you suggest for inference, which should handle most situations without the need for custom C++ modification.

**Comment by llhe** [comment]
Sounds great @andrewharp

**Comment by andrewharp** [comment]
Android-specific Java interface for inference added in 54bd703932480790643c641796386c225e4e1cf3. It may eventually be superseded by a full Java API implementation, but for now it should allow running a variety of graphs without any native code recompilation.
