### ISSUE TITLE
tf.contrib.framework.assign_from_values in v2

### ISSUE THREAD

**Issue by sreyahalder** [tensorflow/tensorflow#41461]
## Description of issue (what needs changing):
I'm running inference on a model that used tf1, and I've converted most of the code to v2 but I can't seem to find anywhere the proper v2 (or even tf.compat.v1) version of framework.assign_from_values. I'm just getting the error
`AttributeError: module 'tensorflow.compat.v1' has no attribute 'contrib'`

**Comment by amahendrakar** [comment]
@sreyahalder,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by mainguyenanhvu** [comment]
Have you fixed this bug without installing tensorflow v1.x?
I used code in tensorflow 2. I need to copy a tensor from a graph to another graph to convert into numpy by using `copy_graph.copy_variable_to_graph`. However, it said that `AttributeError: module 'tensorflow.compat.v1' has no attribute 'contrib'`.


Please help me. Thank you a lot.
