### ISSUE TITLE
Model Maker Outputing Single File, no labels.txt

### ISSUE THREAD

**Issue by vdaita** [tensorflow/tensorflow#41470]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://www.tensorflow.org/lite/tutorials/model_maker_image_classification
Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/MyMethod

## Description of issue (what needs changing):

The tutorial for Tensorflow Model Maker says that on export, there will be a model.tflite file and then a labels.txt file. However, when I export the model using the instructions, it only outputs a single model.tflite. The console output says that it is stored in a temp directory (which appears to be subsequently deleted), and that the labels are merged into the model.tflite file. Would I still be able to use this on mobile or is there any way I can extract labels.txt?

### Clear description

For example, why should someone use this method? How is it useful?

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example?

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by lauslim12** [comment]
Hello!

I managed to extract the 'labels.txt' file by the following method.
- Let's say that you have a `dataset` folder where you train your images. Inside the `dataset` folder, there's bound to be subfolders consisting of images (e.g. inside the `dataset` folder, there is also `dandellions`, `tulips`, `lilies`, `roses`, et cetera).
- The thing is that TensorFlow trains your data in a descending order. If we take above assumption, then TensorFlow will train your data starting from `dandellions`, `lilies`, `roses`, and then finally the `tulips`.
- What I infer from this is that you can recreate your own `labels.txt` file by simply listing the names of each folder. How do we do that?

We simply use this following Python snippet (I run this on Google Colab's Jupyter Notebook):
```
def recreate_labels():
  # 1) We use this in order to ignore any hidden files that might be here.
  # 'Datasets' is the name of the folder where we store our training data. The 'listdir' is used to fetch all the folder names.
  labels = [folder for folder in os.listdir('datasets') if not folder.startswith('.')]
  
  # 2) Then, we output the contents of each folder name to a file.
  with open('labels.txt', 'w') as file:
    for label in labels:
      file.write(label)
      file.write('\n')

recreate_labels()   
```

This should be the workaround for now. After this is done, you could test it using various methods, one of them is [Python's TensorFlow Lite Image Classification Tester](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/python). If you are using this, then make sure to change the filename where it takes the `labels` file (line 94).

Alternatively, you could use the [TensorFlow's Make Image Classifier](https://github.com/tensorflow/hub/tree/master/tensorflow_hub/tools/make_image_classifier). This tool also outputs the image classifier model that you are creating to a `.tflite` model, complete with `labels.txt`.

Thank you and please don't hesitate to comment if you have anymore questions!
