### ISSUE TITLE
Server terminated abruptly (error code: 14, error message: 'Socket closed'

### ISSUE THREAD

**Issue by Julius-ZCJ** [tensorflow/tensorflow#41480]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):   Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):  source
- TensorFlow version:  2.4.0
- Python version: 3.5
- Installed using virtualenv? pip? conda?:  docker
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.0
- GPU model and memory:  Tesla P100 16G

Here is my Dockerfile :

FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

RUN apt-get update

RUN apt-get install -y wget \
                vim \
                cmake

RUN apt-get -y install \
    python3 \
    python3-pip \
    python3-setuptools

Here is my configure:
You have bazel 3.1.0 installed.
Please specify the location of python. [Default is /usr/bin/python3]:

Found possible Python library paths:
  /usr/lib/python3/dist-packages
  /usr/local/lib/python3.5/dist-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python3/dist-packages]

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: n
No TensorRT support will be enabled for TensorFlow.

Found CUDA 9.0 in:
    /usr/local/cuda-9.0/targets/x86_64-linux/lib
    /usr/local/cuda-9.0/targets/x86_64-linux/include
Found cuDNN 7 in:
    /usr/lib/x86_64-linux-gnu
    /usr/include

Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus. Each capability can be specified as "x.y" or "compute_xy" to include both virtual and binary GPU code, or as "sm_xy" to only include the binary code.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 3.5,7.0]:

Do you want to use clang as CUDA compiler? [y/N]: n
nvcc will be used as CUDA compiler.

Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]:

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]:

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v2             # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=nonccl         # Disable NVIDIA NCCL support.
Configuration finished

Here is my compile command:
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

and then I get the error:
   ^
[15,648 / 26,555] 16 actions running
    Compiling tensorflow/compiler/xla/service/hlo_instructions.cc [for host]; 102s local
    Compiling tensorflow/compiler/xla/service/hlo_computation.cc [for host]; 102s local
    Compiling tensorflow/compiler/xla/service/hlo_instruction.cc [for host]; 101s local
    Compiling tensorflow/compiler/xla/service/hlo_parser.cc [for host]; 97s local
    Compiling tensorflow/compiler/xla/service/hlo_domain_map.cc [for host]; 96s local
    Compiling tensorflow/compiler/xla/service/hlo_query.cc [for host]; 93s local
    Compiling tensorflow/compiler/xla/service/channel_tracker.cc [for host]; 93s local
    Compiling tensorflow/compiler/xla/service/collective_ops_utils.cc [for host]; 92s local ...

Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/root/.cache/bazel/_bazel_root/7c482caa6d82184234d890a1494c53ec/server/jvm.out')

I search this error in issue, but I not found the answer. How can I  fix this bug?

By the way, I can compile success in win10 system, use the same tensorflow source, 
and the wheel named "tensorflow-2.4.0-cp36-cp36m-win_amd64.whl"

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@Julius-ZCJ 
Please refer to [this link](https://github.com/tensorflow/models/issues/3647) with same error, this does not seem like a TF issue.

Similar error:
#35431  [this link explains a directory issue](https://stackoverflow.com/questions/50658110/bazel-server-terminated-abruptly-error-code-14-error-message-log-file-c) [link1](https://github.com/tensorflow/tensorflow/issues/36093#issuecomment-580854910)

**Comment by Julius-ZCJ** [comment]
@Saduf2019 
Yes, I have see these issues before I raise this issue, but not found fix this error method, if you can reproduce this error, can you tell me how to fix this bug.

**Comment by gowthamkpr** [comment]
@Julius-ZCJ As mentioned [here](https://github.com/tensorflow/models/issues/3647#issuecomment-610666720), you are running out of memory while building from source. Please take a look at it and let me know if it helps. Thanks!

**Comment by Julius-ZCJ** [comment]
@gowthamkpr 
OK, I will try again, I remember I still have memory when this error raise. I will run again to check it. Thank you

**Comment by gowthamkpr** [comment]
@Julius-ZCJ Any updates on this issue?

**Comment by bkmgit** [comment]
Still get this issue on Cent OS 8, 16 cores, 16 GB RAM, CPU only build with bazel 3.7.0 and python 3.6.8 Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz
bazel build --config=opt --local_ram_resources=12000 --local_cpu_resources=14 -j 14 --remote_retries=100 --remote_max_connections=20 --remote_download_minimal --verbose_failures //tensorflow/tools/pip_package:build_pip_package

Am using the following compiler flags to get a portable build without AVX and AVX2 flags:
-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wno-sign-compare

**Comment by bkmgit** [comment]
@gowthamkpr Maybe helpful to reopen this issue.

**Comment by jobbofhe** [comment]
I have also encountered this problem. Generally, insufficient memory space will lead to this error. You can use 【-- local_ ram_ Resources = 40960】 (40Gb) to limit the memory size。
