### ISSUE TITLE
I'm having issue when trying to convert keras model to json

### ISSUE THREAD

**Issue by lexms** [tensorflow/tensorflow#41484]
I found an error where it could not find my keras model (input path) and the output path, I think it's because of the space character between "My Drive", since I was using google drive to load and save the model. And I think you can't change the name "My Drive". 
So Instead of using google drive, I was using the local google colab's drive. So then I uploaded the keras model and convert it and save it in the google colab's drive and downloaded it. 

So If it's a bug, I hope in the future it will be fixed. Thank you.

**Environment**
- Google Colab

**System information**
- TensorFlow 2.2
- tensorflowjs ver2.0.1.post1

**Code**
from google.colab import drive
drive.mount('/content/gdrive')

!tensorflowjs_converter --input_format=keras '/content/gdrive/My Drive/model/model.h5' '/content/gdrive/My Drive/json'

**Error**
usage: TensorFlow.js model converters. [-h]
                                       [--input_format {keras,tf_frozen_model,keras_saved_model,tf_hub,tfjs_layers_model,tf_saved_model}]
                                       [--output_format {keras_saved_model,tfjs_graph_model,tfjs_layers_model,keras}]
                                       [--signature_name SIGNATURE_NAME]
                                       [--saved_model_tags SAVED_MODEL_TAGS]
                                       [--quantize_float16 [QUANTIZE_FLOAT16]]
                                       [--quantize_uint8 [QUANTIZE_UINT8]]
                                       [--quantize_uint16 [QUANTIZE_UINT16]]
                                       [--quantization_bytes {1,2}]
                                       [--split_weights_by_layer] [--version]
                                       [--skip_op_check]
                                       [--strip_debug_ops STRIP_DEBUG_OPS]
                                       [--weight_shard_size_bytes WEIGHT_SHARD_SIZE_BYTES]
                                       [--output_node_names OUTPUT_NODE_NAMES]
                                       [--control_flow_v2 CONTROL_FLOW_V2]
                                       [input_path] [output_path]
TensorFlow.js model converters.: error: unrecognized arguments: /content/gdrive/My Drive/json

**Comment by ravikyram** [comment]
@lexms 

This issue is more suitable for TFjsrepo. Please post it on TFjs repo from [here.](https://github.com/tensorflow/tfjs/issues) Thanks!

**Comment by lexms** [comment]
Right, thank you! I've posted [here](https://github.com/tensorflow/tfjs/issues/3618)
