### ISSUE TITLE
Does TensorFlow Profiler step-time consider overlapping?

### ISSUE THREAD

**Issue by gaoteng-git** [tensorflow/tensorflow#41495]
In TensorFlow Profiler overview page, the "step-time graph" consists of 8 parts of time, such as "Input", "Host compute", "Device compute". Is it from wall-clock time view, or does it consider each part separately?
For example, if I use tensorflow to invoke a matrix multiply operation on GPU which lasts for 3ms in CUDA kernel, at the same time I use tensorflow to invoke another operator on CPU which lasts for 2ms. Then 2ms of the first GPU computing is overlapped(hided) by the CPU computing, and only the last 1ms is observed. In TensorFlow Profiler, will it show "Device compute" as "3ms" or as "1ms"?

**Comment by prb12** [comment]
I do not work on TensorFlow any more.

**Comment by rmothukuru** [comment]
@gaoteng-git,
Sorry for the delayed response. Can you please try executing [**`Tensorflow Profiler`** ](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras) with the latest **`Tensorflow Version (2.5)`** and let us know if the issue still persists? Thanks!
