### ISSUE TITLE
Failed to load the native TensorFlow runtime

### ISSUE THREAD

**Issue by digvijayv** [tensorflow/tensorflow#41491]
Getting Below error while initializing tensor flow in python:

**Failed to load the native TensorFlow runtime. See https://www.tensorflow.org/install/errors for some common reasons and solutions. Include the entire stack trace above this error message when asking for help.**

Also the console part start flickering as in this error message is displaying for an infinite loop

**Comment by ravikyram** [comment]
@digvijayv 

Request you to fill [issue template.](https://github.com/tensorflow/tensorflow/issues/new/choose).

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?.

Can you please share error log.

Please, refer similar issues #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
