### ISSUE TITLE
Cannot download celeb_a dataset from tensorflow_datasets :(

### ISSUE THREAD

**Issue by braindotai** [tensorflow/tensorflow#41492]
Running this
```python
(train_data, test_data), info = tfds.load(name = 'celeb_a', split = ['train', 'test'], as_supervised = True, shuffle_files = True, with_info = True)
```
Gives this
```
NonMatchingChecksumError: Artifact https://drive.google.com/uc?export=download&id=0B7EVK8r0v71pZjFTYXZWM3FlRnM, downloaded to /root/tensorflow_datasets/downloads/ucexport_download_id_0B7EVK8r0v71pZjFTYXZWM3FlDDaXUAQO8EGH_a7VqGNLRtW52mva1LzDrb-V723OQN8.tmp.4ec0de7ede1541dca88a21190e298882/uc, has wrong checksum.
```

As far as I know, this issue is there because the dataset is on the google drive.

**Comment by lordtt13** [comment]
Please check now, Checksum error resolved, I think it was unaccessible because too many people were viewing the original GDrive Link.

**Comment by braindotai** [comment]
Nope, still getting the same error!

**Comment by braindotai** [comment]
I guess this issue can be resolved easily if the dataset is stored somewhere else, other than google drive :(

**Comment by lordtt13** [comment]
You can download from [source](http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html) if you're getting the same problem.

**Comment by braindotai** [comment]
Oh yeah sure I can, but the problem is if I do that, there is no way (as far as I know) I can load this folder as `tf.data.Dataset`.

Tensorflow does not allow to create a **full custom dataset** by sub classing `tf.data.Dataset`... (like in Pytorch), though we can read the images from a folder but it is required that the images are in their respective folders whose names are the names of the classes...

But CelebA is a multi class dataset, each image belongs to more than single class.

So reading such a folder and creating dataset from it in tensorflow, is just impossible (as far as I know, I tried my best by reading all the docs and tutorials, etc...), that is why I had to rely on tensorflow_dataset to provide a pre defined dataset, which would be an instance of `tf.data.Dataset`, so that I can apply `.batch`, `.map`, `.cache` etc...

Have a look at [this](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html), here as you can see we can subclass the `torch.utils.data.Dataset`, and then can easily load literally any kind of data with all sorts of complexity in terms of reading it.

If there's any way that is possible in tensorflow then please do tell me, it would be my dream come true.

(I'm in love with the ecosystem of the tensorflow and do want to completely switch all of my workflow to it, but this hassle and inconvenience of reading complex dataset from folders always makes me switch back to Pytorch)

**Comment by lordtt13** [comment]
There is way to add a adatset, check it out [here](https://www.tensorflow.org/datasets/add_dataset).

**Comment by braindotai** [comment]
Is there any other way of creating a custom dataset other than this? Cuz this looks a whole lot of unnecessary work to do for  reading a simple dataset.

**Comment by braindotai** [comment]
l have seen `tf.data.Dataset.list_files` and `tf.data.TextLineDataset`, and do think these might solve my issue. Could you provide me with an working example of em?

**Comment by braindotai** [comment]
Hi there, I think there is a way and I've managed to do what I wanted. Here's my code:-

```python
image_paths = sorted(glob.glob(os.path.join('dataset', 'img_align_celeba', 'img_align_celeba', '*.jpg')))

df = pd.read_csv('dataset/list_attr_celeba.csv')
df.replace(to_replace = -1, value = 0, inplace = True)
labels = df.iloc[:, 1:].values

print(image_paths[:2])
print(labels[:2])
# prints
'''
['dataset/img_align_celeba/img_align_celeba/000001.jpg', 'dataset/img_align_celeba/img_align_celeba/000002.jpg']
[[0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 1 0 0 1 0 0 0 1 1 0 1 0
  1 0 0 1]
 [0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0
  0 0 0 1]]
'''

# here's the tensorflow part...
@tf.function
def read_image(image_path):
    image = tf.io.read_file(image_path)
    image = tf.image.decode_image(image, channels = 3, dtype = tf.float32)
    return image

@tf.function
def normalize(image):
    image = (image - tf.reduce_min(image))/(tf.reduce_max(image) - tf.reduce_min(image))
    image = (2 * image) - 1
    return image

@tf.function
def augment(image):
    image = tf.image.random_crop(image, (178, 178, 3))
    image = tf.image.resize(image, (256, 256))
    image = tf.image.random_flip_left_right(image)
    image = tf.image.random_saturation(image, 0.5, 2.0)
    image = tf.image.random_brightness(image, 0.5)
    return image

@tf.function
def preprocess(image_path, label):
    image = read_image(image_path)
    image = augment(image)
    image = normalize(image)
    return image, label

dataset = tf.data.Dataset.from_tensor_slices((image_paths, labels))
dataset = dataset.map(preprocess)
dataset = dataset.shuffle(buffer_size = 1024)
dataset = dataset.batch(batch_size = 128)
dataset = dataset.prefetch(buffer_size = 128)

for x, y in dataset:
    break

print(x.shape, y.shape)
# prints
# (128, 256, 256, 3) (128, 40)
```

With this code, everything is working just fine for now. Also, do share your opinion for reading the data based on the above code, like performance and memory wise, and some modifications that I should make if any. And if everything is okay, then please add this example to the official tensorflow documentation, it'd very helpful for others as well.

Now one thing I'd still want to achieve, in the the `augment` function, I can't get the dimensions of the image, like if I run 

```python
print(min(image.shape[:-1])) # :-1 to ignore the channels
```
inside this `augment` function to get the minimum of height and width, then it gives me `<unknown>`. I want to replace this line "`image = tf.image.random_crop(image, (178, 178, 3))`" with this
```python
min_dim = min(image.shape[:-1])
image = tf.image.random_crop(image, (min_dim, min_dim, 3))
```
I tried removed the `@tf.function` decorator, but still not working.

So is a there a way I can get this last part done?

Thanks for your time.

**Comment by Saduf2019** [comment]
@braindotai 
I ran the code shared please find the [gist here](https://colab.research.google.com/gist/Saduf2019/ce3d5838f99e76424bf4653261ea507c/untitled284.ipynb).
 Please share all dependencies for us to replicate the issue faced or if possible share a colab gist with the issue reported.

**Comment by braindotai** [comment]
[Here's](https://colab.research.google.com/drive/1-laADHFzT_2qyx10IBvm6tmJeVhCxxCN?usp=sharing) the running notebook.

**Comment by braindotai** [comment]
[Here's](https://colab.research.google.com/drive/1-laADHFzT_2qyx10IBvm6tmJeVhCxxCN?usp=sharing) the colab link.

**Comment by braindotai** [comment]
[Here's](https://colab.research.google.com/drive/1-laADHFzT_2qyx10IBvm6tmJeVhCxxCN?usp=sharing) the colab link

**Comment by braindotai** [comment]
Run below cells first:-
```python
!pip install -q kaggle
from google.colab import files
files.upload()
```
This will ask you to upload the kaggle api json file, which you can get from your kaggle account section.
After uploading that, run:-

```
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 /root/.kaggle/kaggle.json
```
```
!kaggle datasets download jessicali9530/celeba-dataset
!unzip -d dataset celeba-dataset.zip
```
After after this, you can run the rest

**Comment by braindotai** [comment]
I further looked into other api's, and found that I should decode the image using `tf.image.decode_jpeg` instead of `tf.image.decode_image`. And now I'm successfully being able to random crop the image based on its shape.

Loading celeb_a from tensorflow_datasets is still giving error though. :(

**Comment by DvdDuarte** [comment]
> Posting an alternative solution here since (1) automatically downloading CelebA still doesn't work, and (2) I found the above solution too manual. This solution (tested with TFDS v3.2.1) simply overrides a method of the CelebA dataset builder to use manually downloaded data.
> 
> **Step 1.** Manually download data. This should get you the files `{DATA_DIR}/img_align_celeba.zip`, `{DATA_DIR}/list_eval_partition.txt`, `{DATA_DIR}/list_landmarks_align_celeba.txt`, and `{DATA_DIR}/list_attr_celeba.txt` . The following links are provided in the source [code](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/datasets/celeb_a/celeb_a_dataset_builder.py) for the CelebA dataset builder.
> 
> * img_align_celeba.zip: https://drive.google.com/uc?export=download&id=0B7EVK8r0v71pZjFTYXZWM3FlRnM
> * list_eval_partition.txt: https://drive.google.com/uc?export=download&id=0B7EVK8r0v71pY0NSMzRuSXJEVkk
> * list_landmarks_align_celeba.txt: https://drive.google.com/uc?export=download&id=0B7EVK8r0v71pd0FJY3Blby1HUTQ
> * list_attr_celeba.txt: https://drive.google.com/uc?export=download&id=0B7EVK8r0v71pblRyaVFSWGxPY0U
> 
> **Step 2.** Override the `_split_generators` function of the CelebA builder class. Then call `download_and_prepare`. Full code is provided below.
> 
> ```
> import tensorflow_datasets as tfds
> 
> DATA_DIR = "~/my_data_dir"
> 
> class CelebA(tfds.image.celeba.CelebA):
>   def _split_generators(self, dl_manager):
>     
>     downloaded_dirs = {
>       "img_align_celeba": DATA_DIR + "img_align_celeba.zip",
>       "list_eval_partition": DATA_DIR + "list_eval_partition.txt",
>       "list_attr_celeba": DATA_DIR + "list_attr_celeba.txt",
>       "landmarks_celeba": DATA_DIR + "list_landmarks_align_celeba.txt",
>     }
> 
>     # Load all images in memory (~1 GiB)
>     # Use split to convert: `img_align_celeba/000005.jpg` -> `000005.jpg`
>     all_images = {
>         os.path.split(k)[-1]: img
>         for k, img in dl_manager.iter_archive(
>             downloaded_dirs["img_align_celeba"]
>         )
>     }
> 
>     return [
>         tfds.core.SplitGenerator(
>             name=tfds.Split.TRAIN,
>             gen_kwargs={
>                 "file_id": 0,
>                 "downloaded_dirs": downloaded_dirs,
>                 "downloaded_images": all_images,
>             },
>         ),
>         tfds.core.SplitGenerator(
>             name=tfds.Split.VALIDATION,
>             gen_kwargs={
>                 "file_id": 1,
>                 "downloaded_dirs": downloaded_dirs,
>                 "downloaded_images": all_images,
>             },
>         ),
>         tfds.core.SplitGenerator(
>             name=tfds.Split.TEST,
>             gen_kwargs={
>                 "file_id": 2,
>                 "downloaded_dirs": downloaded_dirs,
>                 "downloaded_images": all_images,
>             },
>         ),
>     ]
> 
> builder = CelebA()
> builder.download_and_prepare()
> ```
> 
> You can now call `tfds.load('celeb_a')` or `builder = tfds.builder('celeb_a'); builder.download_and_prepare()` and reuse the prepared dataset.

That code results in a error on my end.
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[7], line 3
      1 DATA_DIR = "dataset"
----> 3 class CelebA(tfds.image.celeba.CelebA):
      4   def _split_generators(self, dl_manager):
      6     downloaded_dirs = {
      7       "img_align_celeba": DATA_DIR + "img_align_celeba.zip",
      8       "list_eval_partition": DATA_DIR + "list_eval_partition.txt",
      9       "list_attr_celeba": DATA_DIR + "list_attr_celeba.txt",
     10       "landmarks_celeba": DATA_DIR + "list_landmarks_align_celeba.txt",
     11     }

TypeError: LazyBuilderImport.__init__() takes 2 positional arguments but 4 were given
```

**Comment by AmonB** [comment]
I think I have solved this problem (tested with TFDS V 4.9.2). 
First, download the source [code](https://github.com/tensorflow/datasets/tree/master/tensorflow_datasets/datasets/celeb_a/celeb_a_dataset_builder.py). Actually I downloaded the whole celeb_a directory.
Then  you will see Line 31 in the file `celeb_a_dataset_builder.py` is `import tensorflow_datasets.public_api as tfds`. Here I changed this line with  `import tensorflow_datasets as tfds`
Next, build this dataset manually. Open your terminal and cd to `celeb_a` directory where you download the source code and run commond `tfds build celeb_a`. Surprisingly, this dataset will be downloaded automatically  : )

**Comment by minkichunm** [comment]
> I think I have solved this problem (tested with TFDS V 4.9.2). First, download the source [code](https://github.com/tensorflow/datasets/tree/master/tensorflow_datasets/datasets/celeb_a/celeb_a_dataset_builder.py). Actually I downloaded the whole celeb_a directory. Then you will see Line 31 in the file `celeb_a_dataset_builder.py` is `import tensorflow_datasets.public_api as tfds`. Here I changed this line with `import tensorflow_datasets as tfds` Next, build this dataset manually. Open your terminal and cd to `celeb_a` directory where you download the source code and run commond `tfds build celeb_a`. Surprisingly, this dataset will be downloaded automatically : )

INFO[build.py]: Loading dataset celeb_a from imports: tensorflow_datasets.datasets.celeb_a.celeb_a_dataset_builder
2023-10-08 20:38:45.862750: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
INFO[utils.py]: NumExpr defaulting to 2 threads.
2023-10-08 20:38:49.014201: W tensorflow/tsl/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "NOT_FOUND: Could not locate the credentials file.". Retrieving token from GCE failed with "NOT_FOUND: Error executing an HTTP request: HTTP response code 404".
INFO[dataset_info.py]: Load pre-computed DatasetInfo (eg: splits, num examples,...) from GCS: celeb_a/2.1.0
INFO[dataset_info.py]: Load dataset info from /tmp/tmp8r9lmqcqtfds
INFO[build.py]: download_and_prepare for dataset celeb_a/2.1.0...
INFO[dataset_builder.py]: Generating dataset celeb_a (/root/tensorflow_datasets/celeb_a/2.1.0)
Downloading and preparing dataset 1.39 GiB (download: 1.39 GiB, generated: 1.63 GiB, total: 3.01 GiB) to /root/tensorflow_datasets/celeb_a/2.1.0...
Dl Completed...: 0 url [00:00, ? url/s]
                                       
INFO[download_manager.py]: Skipping download of https://drive.google.com/uc?export=download&id=1_ee_0u7vcNLOfNLegJRHmolfH5ICW-XS: File cached in /root/tensorflow_datasets/downloads/ucexport_download_id_1_ee_0u7vcNLOfNLegJRHm-XSxhQ4V8PiYwrC2p94LpwSMuXlm-mTqdROinkWx4phWMA
Dl Completed...: 0 url [00:00, ? url/s]
Dl Completed...:   0% 0/1 [00:00<?, ? url/s]
Dl Completed...: 100% 1/1 [00:00<00:00, 597.82 url/s]
Dl Completed...: 100% 1/1 [00:00<00:00, 557.98 url/s]
Dl Completed...: 100% 1/1 [00:00<00:00, 524.94 url/s]
                                                     
INFO[download_manager.py]: Downloading https://drive.google.com/uc?export=download&id=0B7EVK8r0v71pZjFTYXZWM3FlRnM into /root/tensorflow_datasets/downloads/ucexport_download_id_0B7EVK8r0v71pZjFTYXZWM3FlDDaXUAQO8EGH_a7VqGNLRtW52mva1LzDrb-V723OQN8.tmp.6700c63961bb46279b09696cc33e3ab0...
Dl Completed...: 100% 1/1 [00:00<00:00, 349.41 url/s]
Dl Completed...:  50% 1/2 [00:00<00:00, 330.23 url/s]
                                                     
INFO[download_manager.py]: Skipping download of https://drive.google.com/uc?export=download&id=0B7EVK8r0v71pd0FJY3Blby1HUTQ: File cached in /root/tensorflow_datasets/downloads/ucexport_download_id_0B7EVK8r0v71pd0FJY3Blby1HbAKodWmQf22yupkBkIVpdZZzDoEp9no9YWWfGYxI1Ds
Dl Completed...:  50% 1/2 [00:00<00:00, 169.25 url/s]
Dl Completed...:  33% 1/3 [00:00<00:00, 143.25 url/s]
Dl Completed...:  67% 2/3 [00:00<00:00, 279.18 url/s]
Dl Completed...:  67% 2/3 [00:00<00:00, 273.74 url/s]
Dl Completed...:  67% 2/3 [00:00<00:00, 266.95 url/s]
                                                     
INFO[download_manager.py]: Skipping download of https://drive.google.com/uc?export=download&id=0B7EVK8r0v71pblRyaVFSWGxPY0U: File cached in /root/tensorflow_datasets/downloads/ucexport_download_id_0B7EVK8r0v71pblRyaVFSWGxP8OXaKJ1cz3X_6IERMmlJIrYPKvWSVu02KvoD_vujJNA
Dl Completed...:  67% 2/3 [00:00<00:00, 242.45 url/s]
Dl Completed...:  50% 2/4 [00:00<00:00, 237.78 url/s]
Dl Completed...:  75% 3/4 [00:00<00:00, 350.57 url/s]
Dl Completed...:  75% 3/4 [00:00<00:00, 345.03 url/s]
Dl Completed...:  75% 3/4 [00:00<00:00, 339.72 url/s]
                                                     
INFO[download_manager.py]: Skipping download of https://drive.google.com/uc?export=download&id=0B7EVK8r0v71pY0NSMzRuSXJEVkk: File cached in /root/tensorflow_datasets/downloads/ucexport_download_id_0B7EVK8r0v71pY0NSMzRuSXJE_JVbyz74-999VkDZqGk6hDG18u4pGlwUSaFUnn4HP-c
Dl Completed...:  75% 3/4 [00:00<00:00, 308.72 url/s]
Dl Completed...:  60% 3/5 [00:00<00:00, 303.19 url/s]
Dl Completed...:  80% 4/5 [00:00<00:00, 399.22 url/s]
Dl Completed...:  80% 4/5 [00:00<00:00, 393.64 url/s]
Dl Completed...:  80% 4/5 [00:00<00:00, 384.54 url/s]
Dl Size...: 100% 45137925/45137925 [00:01<00:00, 44636539.95 MiB/s]  
Dl Completed...:  80% 4/5 [00:01<00:00,  3.95 url/s] 
Traceback (most recent call last):
  File "/usr/local/bin/tfds", line 8, in <module>
    sys.exit(launch_cli())
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_datasets/scripts/cli/main.py", line 109, in launch_cli
    app.run(main, flags_parser=_parse_flags)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_datasets/scripts/cli/main.py", line 104, in main
    args.subparser_fn(args)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_datasets/scripts/cli/build.py", line 312, in _build_datasets
    process_builder_fn(builder)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_datasets/scripts/cli/build.py", line 551, in _download_and_prepare
    builder.download_and_prepare(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_datasets/core/logging/__init__.py", line 166, in __call__
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 691, in download_and_prepare
    self._download_and_prepare(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 1547, in _download_and_prepare
    split_generators = self._split_generators(  # pylint: disable=unexpected-keyword-arg
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_datasets/datasets/celeb_a/celeb_a_dataset_builder.py", line 100, in _split_generators
    downloaded_dirs = dl_manager.download({
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_datasets/core/download/download_manager.py", line 601, in download
    return _map_promise(self._download, url_or_urls)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_datasets/core/download/download_manager.py", line 831, in _map_promise
    res = tree_utils.map_structure(
  File "/usr/local/lib/python3.10/dist-packages/tree/__init__.py", line 435, in map_structure
    [func(*args) for args in zip(*map(flatten, structures))])
  File "/usr/local/lib/python3.10/dist-packages/tree/__init__.py", line 435, in <listcomp>
    [func(*args) for args in zip(*map(flatten, structures))])
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_datasets/core/download/download_manager.py", line 832, in <lambda>
    lambda p: p.get(), all_promises
  File "/usr/local/lib/python3.10/dist-packages/promise/promise.py", line 512, in get
    return self._target_settled_value(_raise=True)
  File "/usr/local/lib/python3.10/dist-packages/promise/promise.py", line 516, in _target_settled_value
    return self._target()._settled_value(_raise)
  File "/usr/local/lib/python3.10/dist-packages/promise/promise.py", line 226, in _settled_value
    reraise(type(raise_val), raise_val, self._traceback)
  File "/usr/local/lib/python3.10/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/lib/python3.10/dist-packages/promise/promise.py", line 844, in handle_future_result
    resolve(future.result())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_datasets/core/download/downloader.py", line 230, in _sync_download
    with _open_url(url, verify=verify) as (response, iter_content):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_datasets/core/download/downloader.py", line 303, in _open_with_requests
    _assert_status(response)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow_datasets/core/download/downloader.py", line 330, in _assert_status
    raise DownloadError(
tensorflow_datasets.core.download.downloader.DownloadError: Failed to get url https://doc-0s-84-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/5ikg3vh0k0mui2cturj90udo3kodjtdk/1696797525000/13182073909007362810/*/0B7EVK8r0v71pZjFTYXZWM3FlRnM?e=download&uuid=b4b3bab2-3267-4ab0-896f-02660c49a3a3. HTTP code: 429.

**Comment by Iliceth** [comment]
> Posting an alternative solution here since (1) automatically downloading CelebA still doesn't work, and (2) I found the above solution too manual. This solution (tested with TFDS v3.2.1) simply overrides a method of the CelebA dataset builder to use manually downloaded data.
> 
> **Step 1.** Manually download data. This should get you the files `{DATA_DIR}/img_align_celeba.zip`, `{DATA_DIR}/list_eval_partition.txt`, `{DATA_DIR}/list_landmarks_align_celeba.txt`, and `{DATA_DIR}/list_attr_celeba.txt` . The following links are provided in the source [code](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/datasets/celeb_a/celeb_a_dataset_builder.py) for the CelebA dataset builder.
> 
>     * img_align_celeba.zip: https://drive.google.com/uc?export=download&id=0B7EVK8r0v71pZjFTYXZWM3FlRnM
> 
>     * list_eval_partition.txt: https://drive.google.com/uc?export=download&id=0B7EVK8r0v71pY0NSMzRuSXJEVkk
> 
>     * list_landmarks_align_celeba.txt: https://drive.google.com/uc?export=download&id=0B7EVK8r0v71pd0FJY3Blby1HUTQ
> 
>     * list_attr_celeba.txt: https://drive.google.com/uc?export=download&id=0B7EVK8r0v71pblRyaVFSWGxPY0U
> 
> 
> **Step 2.** Override the `_split_generators` function of the CelebA builder class. Then call `download_and_prepare`. Full code is provided below.
> 
> ```
> import tensorflow_datasets as tfds
> 
> DATA_DIR = "~/my_data_dir"
> 
> class CelebA(tfds.image.celeba.CelebA):
>   def _split_generators(self, dl_manager):
>     
>     downloaded_dirs = {
>       "img_align_celeba": DATA_DIR + "img_align_celeba.zip",
>       "list_eval_partition": DATA_DIR + "list_eval_partition.txt",
>       "list_attr_celeba": DATA_DIR + "list_attr_celeba.txt",
>       "landmarks_celeba": DATA_DIR + "list_landmarks_align_celeba.txt",
>     }
> 
>     # Load all images in memory (~1 GiB)
>     # Use split to convert: `img_align_celeba/000005.jpg` -> `000005.jpg`
>     all_images = {
>         os.path.split(k)[-1]: img
>         for k, img in dl_manager.iter_archive(
>             downloaded_dirs["img_align_celeba"]
>         )
>     }
> 
>     return [
>         tfds.core.SplitGenerator(
>             name=tfds.Split.TRAIN,
>             gen_kwargs={
>                 "file_id": 0,
>                 "downloaded_dirs": downloaded_dirs,
>                 "downloaded_images": all_images,
>             },
>         ),
>         tfds.core.SplitGenerator(
>             name=tfds.Split.VALIDATION,
>             gen_kwargs={
>                 "file_id": 1,
>                 "downloaded_dirs": downloaded_dirs,
>                 "downloaded_images": all_images,
>             },
>         ),
>         tfds.core.SplitGenerator(
>             name=tfds.Split.TEST,
>             gen_kwargs={
>                 "file_id": 2,
>                 "downloaded_dirs": downloaded_dirs,
>                 "downloaded_images": all_images,
>             },
>         ),
>     ]
> 
> builder = CelebA()
> builder.download_and_prepare()
> ```
> 
> You can now call `tfds.load('celeb_a')` or `builder = tfds.builder('celeb_a'); builder.download_and_prepare()` and reuse the prepared dataset.

@berthyf96 Hello, I get the same "TypeError: LazyBuilderImport.__init__() takes 2 positional arguments but 4 were given" error as @DvdDuarte. Can you help?

**Comment by giulio98** [comment]
Hello i have uploaded celeba into 🤗 Datasets.
[eurecom-ds/celeba](https://huggingface.co/datasets/eurecom-ds/celeba)

**Comment by cuixue** [comment]
您好，邮件已经收到，我会尽快处理的。谢谢
