### ISSUE TITLE
tf.parallel_stack() doesn't support eager execution

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/tensorflow#41493]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
Bug example:
```python
x = tf.constant([1, 4])
y = tf.constant([2, 5])
z = tf.constant([3, 6])
tf.parallel_stack([x, y, z])
```
Work example
```python
x = tf.constant([1, 4])
y = tf.constant([2, 5])
z = tf.constant([3, 6])
with tf.compat.v1.Session() as sess:
    print(sess.run(tf.parallel_stack([x, y, z])))
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@fsx950223,
I was able to reproduce the issue reported here, but the 'working example' too seems to throw an error. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/07cc20c8528e0f6209800732ec5aa297/41493.ipynb).

If possible could you please provide a working example too? Thanks!

**Comment by fsx950223** [comment]
```python
@tf.function
def test():
  x = tf.constant([1, 4])
  y = tf.constant([2, 5])
  z = tf.constant([3, 6])
  return tf.parallel_stack([x, y, z])
test()
```

**Comment by codecolony** [comment]
I have a similar issue but with "Moving average".

`ValueError: Moving average not supported in eager mode.`

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/cb1060f15cfb1bd38cdec20ad1e53ec9/41493-2-2.ipynb), [TF v2.3.0rc2](https://colab.research.google.com/gist/amahendrakar/8da30a0e2e728a189dcf709baf807e09/41493-2-3.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/401e1a9ff76255026c667b19e5e42ac3/41493-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by rohan100jain** [comment]
https://github.com/tensorflow/tensorflow/commit/868256f05a2abd55b43746c7b3c8b6fb9053668e should have fixed the issue. Parallel Stack has no eager implementation and we now raise an error.

**Comment by rohan100jain** [comment]
Please open a separate issue for moving average and we'll address it.
