### ISSUE TITLE
Session->Run (c++) not working if launched in a thread

### ISSUE THREAD

**Issue by Kmarconi** [tensorflow/tensorflow#41494]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):1.15.2
- Python version:3.8
- Bazel version (if compiling from source):0.26.1
- GCC/Compiler version (if compiling from source):5.5
- CUDA/cuDNN version:10.1/7.5
- GPU model and memory:Jetson Xavier

**Describe the current behavior**
I'm working on creating an object detection script using Tensorflow in C++. For this, I've used https://github.com/lysukhin/tensorflow-object-detection-cpp as a start and after some changes to make it faster, I'm able to run it at a very good speed on the Jetson Xavier. But today, I would like to separate the capture and inference task to let them run by themself as threads. The problem is that my "session ->run" instruction is not giving me any information about what is going on. The only thing that I know is that my session->run is not working properly because it should output a tensorflow::Status and I'm getting nothing (neither an error). Since there is no error, It is pretty hard for me to find why my run instruction is not doing anything.

**Describe the expected behavior**
Described above.

Thanks for the futur help !

**Comment by ravikyram** [comment]
@Kmarconi 

I think this is more related to models repo.Please, raise an issue in models repo by filling issue template from [here](https://github.com/tensorflow/models/issues/new/choose).Also, please share related code so it helps us in localizing the issue faster.Thanks!
