### ISSUE TITLE
RGB to YUV: Conflicting information between example and description

### ISSUE THREAD

**Issue by aigagror** [tensorflow/tensorflow#41496]
https://www.tensorflow.org/api_docs/python/tf/image/rgb_to_yuv

The documentation says this function is only well defined if the values are between 0 and 1, but the example uses an input with values greater than 1.

**Comment by yil532** [comment]
Hi, Can I create a PR to fix this? Thank you!

**Comment by yil532** [comment]
PR to fix this issue is here, https://github.com/tensorflow/tensorflow/pull/41565
Please take a look, thank you!

**Comment by jvishnuvardhan** [comment]
This was resolved in `tf-nightly` with this PR https://github.com/tensorflow/tensorflow/pull/42270.

Please check the page here https://www.tensorflow.org/api_docs/python/tf/image/rgb_to_yuv?version=nightly

I am closing this issue as this was already resolved. Thanks!
