### ISSUE TITLE
'import cifar10' bug

### ISSUE THREAD

**Issue by ookykim** [tensorflow/tensorflow#415]
I have inserted simple print('xxx') in cifar10.py and run cifar10_train.py but no 'xxx' is printed.
Examining cifar10_train.py find out 'import cifar10' from different source:
    from tensorflow.models.image.cifar10 import cifar10
I changed it to:
   import cifar10
and run again, get 'xxx' but crashed the program at the function loss() in cifar10.py saying:

Traceback (most recent call last):
  File "cifar10_train.py", line 139, in <module>
    tf.app.run()
  File "/home/ooky/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 11, in run
    sys.exit(main(sys.argv))
  File "cifar10_train.py", line 135, in main
    train()
  File "cifar10_train.py", line 77, in train
    loss = cifar10.loss(logits, labels)
  File "/home/ooky/work/cifar10/cifar10.py", line 401, in loss
    indices = tf.reshape(tf.range(FLAGS.batch_size), [FLAGS.batch_size, 1])
TypeError: range() takes at least 2 arguments (1 given)

What's wrong?

**Comment by girving** [comment]
I recently fixed `tf.range` to accept between 1 and 3 arguments (like Python's `range`).  This change will be part of the upcoming 0.6.0 release, but you're using the 0.5.0 release, and a version of cifar10 from git.  Quick fix: use `tf.range(0, FLAGS.batch_size)` instead of `tf.range(FLAGS.batch_size)`.

**Comment by ookykim** [comment]
Thanks much for prompt reply!
2015. 12. 6. 오전 7:09에 "Geoffrey Irving" <notifications@github.com>님이 작성:
