### ISSUE TITLE
GV100 Tensorflow 2.0.0 not working

### ISSUE THREAD

**Issue by yskale** [tensorflow/tensorflow#41507]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by yskale** [comment]
![image](https://user-images.githubusercontent.com/14827177/87822046-d5e05d80-c83e-11ea-990b-991d5d08ce82.png)

**Comment by lordtt13** [comment]
How have you compiled TF?

**Comment by yskale** [comment]
Yes
print(tf.__version__)
2.0.0
f.test.gpu_device_name()
' '

**Comment by lordtt13** [comment]
I meant did you install it using conda or from source or from binaries?

**Comment by Saduf2019** [comment]
@yskale 
Please provide with detailed information for us to help you, we see that you have not filled the issue template. steps followed before you faced this issue.Thanks!

**Comment by yskale** [comment]
x86_64
NAME="SLES"
VERSION="15"
VERSION_ID="15"
PRETTY_NAME="SUSE Linux Enterprise Server 15"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15"

Kernel - > 4.12.14-150.47-default
GCC - > gcc (SUSE Linux) 7.5.0

![image](https://user-images.githubusercontent.com/14827177/87972869-a8412180-ca95-11ea-917b-d2c896bb2bf7.png)

**Comment by yskale** [comment]
I am able to run the cuda sample programs but the gpu are not visible in python for torch and tensorflow.
I have installed torch using coda and for diiferent version of torch and cuda but do not see the gpu.

**Comment by jvishnuvardhan** [comment]
@yskale I think there is a mismatch in CUDA drivers. Please check the tested build configurations [here](https://www.tensorflow.org/install/source#gpu).  Please check the CUDA driver version for `TF2.0`. As you have used `pip` binaries, Tensorflow2.0 will be looking for `*CUDA10.0` folder for related drivers and you have `*CUDA10.0`, so there is a mismatch.

Can you please uninstall cuda10.1, uninstall TF, and follow the instructions on TF website ( install cuda10.0 and then install TF).


Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow-2.0.0 | 2.7, 3.3-3.7 | GCC 7.3.1 | Bazel 0.26.1 | 7.4 | 10.0

Alternatively, you can install TF2.2 (which requires CUDA10.1) and see whether that solves your problem. TF2.2 is much better than TF2.0.
 

Please let us know how it progresses. Thanks!

**Comment by yskale** [comment]
Thanks for the information @jvishnuvardhan , I was able to figure out the problem and fix it.
