### ISSUE TITLE
fit the model with features on GPU (AssertionError: Could not compute output Tensor("dense_3/Identity:0", shape=(None, 1), dtype=float32)) 

### ISSUE THREAD

**Issue by jayaBalaR** [tensorflow/tensorflow#41500]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

TF version 2.2

**Issue occurs when we call model.fit after creating keras model. We are using tfhub bert layer for its word embeddings ,setting trainable =False** as below:-
```
bert_layer = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/2", trainable=False)
pooled_output, sequence_output = bert_layer([input_word_ids, input_mask, segment_ids])

bert_model = Model(inputs=[input_word_ids, input_mask, segment_ids], outputs=pooled_output)
```

```
X_train_pooled_output.shape(50,000,768)  and X_test_pooled_output.shape(20,000, 768) batch_size = 32
mode3.fit(X_train_pooled_output, y_train, epochs=nb_epoch,batch_size=batch_size,verbose=1,validation_data = (X_test_pooled_output,y_test),callbacks=callback_list)
```

![image](https://user-images.githubusercontent.com/21074002/87811649-9cc6de00-c87c-11ea-9f77-0d705e230c5e.png)

**Comment by jayaBalaR** [comment]
thanks the issue is resolved now. hence closing the issue

**Comment by dhruv1394** [comment]
Facing the same issue. What has been the resolution provided for this?

**Comment by jayaBalaR** [comment]
no resolution. We took a workaround in our code.

**Comment by JackHunt** [comment]
> no resolution. We took a workaround in our code.

What was the workaround? I am currently encountering the same/related issue.
