### ISSUE TITLE
ValueError: Tape is still recording, This can happen if you try to re-enter an already-active tape.

### ISSUE THREAD

**Issue by andrescodas** [tensorflow/tensorflow#41510]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
_Yes_
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
  _dockerhub container 'latest'  Digest:  08901711826b185136886c7b8271b9fdbe86b8ccb598669781a1f5cb340184eb_
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
   _v2.2.0-rc4-8-g2b96f3662b 2.2.0_
- Python version:
   _Python 3.6.9_
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
on line `grads = tape.jacobian(w, [x, y])`
`ValueError: Tape is still recording, This can happen if you try to re-enter an already-active tape.`

**Describe the expected behavior**

I was expecting to get the jacobian calculation:
`grads == [dwdx, dwdy]`
or similar (not the error)

**Standalone code to reproduce the issue**

```
        import tensorflow as tf

        # x,y,v potentially a large batch
        x = tf.constant([[1.0],[5.0]])
        y = tf.constant([[2.0],[6.0]])
        v = tf.Variable([[1.0],[3.0]])

        with tf.GradientTape(persistent=True) as tape:
            tape.watch(x)
            tape.watch(y)
            tape.watch(v)

            # w1 and w2 a nonlinear function independent for each row
            w1 = (x + y + v )
            w2 = y * y * v
            w = tf.concat([w1, w2], axis=1)

            grads = tape.jacobian(w, [x, y])

        dgradsdv = tape.jacobian(grads, v)

        print(dgradsdv)

```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Log
```
    grads = tape.jacobian(w, [x, y])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/backprop.py", line 1113, in jacobian
    self._push_tape()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/backprop.py", line 844, in _push_tape
    raise ValueError("Tape is still recording, This can happen if you try to "
ValueError: Tape is still recording, This can happen if you try to re-enter an already-active tape.
```
If I substitute `tape.jacobian` by `tape.gradient` there is no error.
I would like to know how to implement these Jacobians efficiently.  Thanks!

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.2 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/173981f159dcf4853852de2404bedf8a/41510.ipynb). Thanks!

**Comment by yidiq7** [comment]
I tried something similar with nested GradientTape, had the same issue with TF v2.3.

**Comment by nikitamaia** [comment]
Hi @andrescodas, I think it was reported a while ago in #34260 but because there was no reproducible example or follow up from the author, it fell through the cracks.

@yidiq7 can you provide example code for the issue you're facing?

**Comment by andrescodas** [comment]
Hi @nikitamaia, I'm glad to help and provide more information if required.  I managed to use calls to tape.gradient to replace the need for jacobian, however I'm concerned that this workaround might be inefficient. It would be useful to me if you could point out when to use GradientTape.graident vs GradientTape.jacobian vs GradientTape.batch_gradient, particularly when performing automatic differentiation on a function with many outputs to many inputs , and a batch to calculate on that function

**Comment by yidiq7** [comment]
Hi @andrescodas @nikitamaia, after some debugging, I found it was probably due to the indentation:
In the original code provided by @andrescodas:

`        
with tf.GradientTape(persistent=True) as tape:
    ...
    grads = tape.jacobian(w, [x, y])
`

It should be like this instead:

`        
with tf.GradientTape(persistent=True) as tape:
    ...
grads = tape.jacobian(w, [x, y])
`

Not sure if this really does what you want, but the error was gone.

**Comment by andrescodas** [comment]
Hi @yidiq7, thanks for digging.

Although the problem disappear with the indentation you suggest, the behavior is different.   Let me illustrate with the following examples:

```python
import tensorflow as tf

y = tf.constant(2.0,)
v = tf.Variable(3.0,)

with tf.GradientTape(persistent=True) as tape:
    tape.watch(y)
    tape.watch(v)

    w =  y * y * v

    grads = tape.gradient(w, y)  # 2*y*v
dgradsdv = tape.gradient(grads, v)  # 2 * y

print(grads)  # prints tf.Tensor(12.0, shape=(), dtype=float32)
print(dgradsdv) # prints tf.Tensor(4.0, shape=(), dtype=float32)
```
This code above is working as expected, according to the comments.  Observe that I used gradient instead of jacobian to avoid the `ValueError` issue.

If I use the indentation you suggest, the first gradient operation is not in the tape, and therefore I think the answer is correctly None, because the graph missed the last operation linking v to grads, see:

```python
import tensorflow as tf

y = tf.constant(2.0,)
v = tf.Variable(3.0,)

with tf.GradientTape(persistent=True) as tape:
    tape.watch(y)
    tape.watch(v)

    w =  y * y * v

grads = tape.gradient(w, y)  # 2*y*v  # operation not taped !
dgradsdv = tape.gradient(grads, v)  # ?

print(grads)  # prints tf.Tensor(12.0, shape=(), dtype=float32)
print(dgradsdv) # None
```

Lastly, for the record:  The code below still raises `ValueError` and it is simpler than the one in the first post:

```python
import tensorflow as tf

y = tf.constant(2.0,)
v = tf.Variable(3.0,)

with tf.GradientTape(persistent=True) as tape:
    tape.watch(y)
    tape.watch(v)

    w =  y * y * v

    grads = tape.jacobian(w, y) 

```

**Comment by yidiq7** [comment]
A nested GradientTape can give you correct results. (Note the indentation for jacobian here)
Also persistent=True is not required in this case.

I am not sure if this is the most efficient way to do this though.
```
import tensorflow as tf

y = tf.constant(2.0,)
v = tf.Variable(3.0,)

with tf.GradientTape() as tt:
    tt.watch(v)
    with tf.GradientTape() as t:
        t.watch(y)
        w =  y * y * v

    grads = t.jacobian(w, y)  # 2*y*v  
dgradsdv = tt.jacobian(grads, v)  # 2*y

print(grads) # <tf.Tensor: shape=(), dtype=float32, numpy=12.0>
print(dgradsdv) # <tf.Tensor: shape=(), dtype=float32, numpy=4.0>
```

**Comment by nikitamaia** [comment]
@andrescodas does the suggestion from @yidiq7 work for you?

**Comment by andrescodas** [comment]
Hi @nikitamaia ,

> @andrescodas does the suggestion from @yidiq7 work for you?

It computes the correct answer.  However:

- It is an open question whether it is the most efficient way (or preferred way) to compute a batch_jacobian of many targerts with respect to many sources.
- It seems to be bug that GradientTape.jacobian raises ValueError while recording within the gradient context.
- The message `ValueError: Tape is still recording, This can happen if you try to re-enter an already-active tape` is misleading because the user piece of code does not leave and re-enter the tape context.

**Comment by nikitamaia** [comment]
Agreed, that is a misleading message and I think a bug. It is currently being investigated and I can update this thread when there's a fix. For now, use the workaround from @yidiq7 and I'll post any updates here.
