### ISSUE TITLE
Export frozen inference graph with custom eager mode in tf 2.0

### ISSUE THREAD

**Issue by pardeep-kesnani1234** [tensorflow/tensorflow#41527]
hello, I am training my custom object detection API with eager mode which is totally working fine but now I want to convert this eager mode model into a frozen inference graph so i can use it in opencv can u guyz help me out with this. I tried the traditional approach for exporting frozen graph but this won't work in our case
here's the link of colab notebook you can try this by your own too
https://colab.research.google.com/github/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tf2_colab.ipynb#scrollTo=YBD6l-E4N71y

**Comment by ravikyram** [comment]
@pardeep-kesnani1234 

I think this is more related to models repo.Please, raise an issue in models repo by filling issue template from [here](https://github.com/tensorflow/models/issues/new/choose).Also, please share related code so it helps us in localizing the issue faster.Thanks!
