### ISSUE TITLE
Not able to get NV profile for tensorflow(inception)

### ISSUE THREAD

**Issue by asispatra** [tensorflow/tensorflow#4152]
### Environment info
Operating System: Ubuntu 14.04
Machine: x86
Installed version of CUDA and cuDNN: 
CUDA 7.5, cuDNN 5.1.3
Installed from source:
1. The commit hash (`git rev-parse HEAD`)
9454b9015567ae0641250004fd2fafccede54a93
2. The output of `bazel version`
(tensorflow)asis@ws:~$ bazel version
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 01 00:00:00 1970 (0)
Build timestamp: Thu Jan 01 00:00:00 1970 (0)
Build timestamp as int: 0

### Getting NV Profile for the following sample code:
```
(tensorflow)asis@ws:~$ cat test.py
import tensorflow as tf
c = []
for d in ['/gpu:0', '/gpu:1']:
  with tf.device(d):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3])
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2])
    c.append(tf.matmul(a, b))
with tf.device('/cpu:0'):
  sum = tf.add_n(c)
sess = tf.Session()
print sess.run(sum)

(tensorflow)asis@ws:~$ nvprof -o nvtest_x86 python test.py
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so.5.1.3 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so.7.5 locally
==41815== NVPROF is profiling process 41815, command: python test.py
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties:
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.562
pciBusID 0000:84:00.0
Total memory: 12.00GiB
Free memory: 11.87GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0x313af00
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 1 with properties:
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.562
pciBusID 0000:85:00.0
Total memory: 12.00GiB
Free memory: 11.87GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 1
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y Y
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 1:   Y Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:84:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla K80, pci bus id: 0000:85:00.0)
[[  44.   56.]
 [  98.  128.]]
==41815== Generated result file: /home/asis/samples/asis/nvtest_x86
(tensorflow)asis@ws:~$
```
__Generated result file: /home/asis/samples/asis/nvtest_x86__
### Not getting VN profile for the following TensorFlow(Inception)
```
(tensorflow)asis@ws:~$ nvprof -o nvprof_bs64_2gpu_3 bazel-bin/inception/imagenet_train --max_steps=3 --num_gpus=2 --batch_size=64 --train_dir=/home/asis/googlenet/test/train_bs64_2gpu_20160901_041429 --data_dir=/home/asis/inception_output_data
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so.5.1.3 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so.7.5 locally
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties:
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:84:00.0
Total memory: 12.00GiB
Free memory: 11.88GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0x7eb0000
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 1 with properties:
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:85:00.0
Total memory: 12.00GiB
Free memory: 11.88GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 1
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y Y
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 1:   Y Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:84:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla K80, pci bus id: 0000:85:00.0)
WARNING:tensorflow:Passing a `GraphDef` to the SummaryWriter is deprecated. Pass a `Graph` object instead, such as `sess.graph`.
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:244] PoolAllocator: After 7536 get requests, put_count=4071 evicted_count=1000 eviction_rate=0.24564 and unsatisfied allocation rate=0.605759
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:256] Raising pool_size_limit_ from 100 to 110
2016-09-01 07:00:14.565170: step 0, loss = 13.07 (0.6 examples/sec; 104.984 sec/batch)
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:244] PoolAllocator: After 0 get requests, put_count=2012 evicted_count=2000 eviction_rate=0.994036 and unsatisfied allocation rate=0
======== Warning: No CUDA application was profiled, exiting
```
__======== Warning: No CUDA application was profiled, exiting__

### Problem
For the Sample code we are getting nv profile, but for the tensorflow(inception) code we are not getting nv profile and getting the following warning.
__Warning: No CUDA application was profiled, exiting__

How can we get nv profile on x86 for tensorflow(inception)

**Comment by benbarsdell** [comment]
This happens because the inception script being run is actually a wrapper that launches the real script in a subprocess.

A workaround is to use the real script directly:

`nvprof -o nvprof_bs64_2gpu_3 python bazel-bin/inception/imagenet_train.runfiles/__main__/inception/inception_train.py`

**Comment by asispatra** [comment]
Hi @benbarsdell 
If I try as you specified, I am getting the following error:
```
Traceback (most recent call last):
  File "bazel-bin/inception/imagenet_train.runfiles/__main__/inception/inception_train.py", line 30, in <module>
    from inception import image_processing
ImportError: No module named inception
======== Warning: No CUDA application was profiled, exiting
======== Error: Application returned non-zero code 1
```

**Comment by benbarsdell** [comment]
Sorry, I forgot about another step to the WAR that needs to be done first:

$ touch inception/__init__.py
$ touch inception/slim/__init__.py

**Comment by asispatra** [comment]
This also did not help.

**Comment by asispatra** [comment]
Hi @benbarsdell 

Finally it worked. I ran the following command under "bazel-bin/inception/imagenet_train.runfiles/__main__/" directory where as it should on the current directory. 
```
$ touch inception/__init__.py
$ touch inception/slim/__init__.py
```
Now I am able to get NV profile.

Thanks :+1:

**Comment by asispatra** [comment]
Closing the issue.

**Comment by mry94** [comment]
Hi @asispatra 
I'm trying to learn how to profile tensorflow codes with nvprof. I tried this simple code that you shared:

import tensorflow as tf
c = []
for d in ['/gpu:0', '/gpu:1']:
  with tf.device(d):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3])
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2])
    c.append(tf.matmul(a, b))
with tf.device('/cpu:0'):
  sum = tf.add_n(c)
sess = tf.Session()
print sess.run(sum)


but I'm getting this error:

======== Warning: No CUDA application was profiled, exiting
======== Error: Application returned non-zero code 127


I can run this program successfully without using nvprof.

**Comment by huangjiasen100** [comment]
> Hi @benbarsdell
> Finally it worked. I ran the following command under "bazel-bin/inception/imagenet_train.runfiles/main/" directory where as it should on the current directory.
> $ touch inception/__init__.py
> $ touch inception/slim/__init__.py
> 
> Now I am able to get NV profile.
> Thanks 👍

I deployed tensorflow with Anaconda. The directories are different with that listed above. Similarly, when I try to measure the bandwidth of some specific neural networks, such as alexnet, the .py of which locates in two directories, one is "xxx\Anaconda3\pkgs\tensorflow-base-1.13.1-eigen_py36hf8af7b3_0\Lib\site-packages\tensorflow\contrib\slim\python\slim\nets" and the other is "C:\Users\hygon\Anaconda3\pkgs\tensorflow-gpu-1.10.0-py36_0\Lib\site-packages\tensorflow\contrib\slim\python\slim\nets". The command  "nvprof --log-file xxx.log python alexnet.py", however, brings about the same warning "No CUDA application was profiled, exiting", while the error that follows returns non-zero code of -1 rather than 127. I have no idea of how to profile the net. Could you please give me some advice?
