### ISSUE TITLE
Model titled with int8 is not quantized(Artistic Style Transfer with TensorFlow Lite)

### ISSUE THREAD

**Issue by mistake0316** [tensorflow/tensorflow#41521]
I am trying to compile the model [Style transform model (int8)](https://tfhub.dev/google/lite-model/magenta/arbitrary-image-stylization-v1-256/int8/transfer/1?lite-format=tflite) to edgetpu version, but the error message say that model is not quantized.
Can anybody tell me how to fix it?

I have downloaded 2 int8 models at the bottom of https://www.tensorflow.org/lite/models/style_transfer/overview
Style prediction model (int8) : https://tfhub.dev/google/lite-model/magenta/arbitrary-image-stylization-v1-256/int8/prediction/1?lite-format=tflite
Style transform model (int8) : https://tfhub.dev/google/lite-model/magenta/arbitrary-image-stylization-v1-256/int8/transfer/1?lite-format=tflite

I try to convert these 2 model to _edgetpu version by typing following commands in my terminal.
>edgetpu_compiler magenta_arbitrary-image-stylization-v1-256_int8_prediction_1.tflite
>edgetpu_compiler magenta_arbitrary-image-stylization-v1-256_int8_transfer_1.tflite

The compile for first file : *_prediction_1.tflite is OK.
However, the compile for  *_transfer_1.tflite reports error:
**********************************************************************
Edge TPU Compiler version 14.1.317412892
Invalid model: magenta_arbitrary-image-stylization-v1-256_int8_transfer_1.tflite
Model not quantized
**********************************************************************

**Comment by amahendrakar** [comment]
Was able to reproduce the issue, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/e7cd2b91834feae2f57366378fd88e05/41521.ipynb). Thanks!

**Comment by karimnosseir** [comment]
This is expected error as the style transform model is not fully quantized (some operations are not quantized). 
You will need to change the model to be able to get fully quantized version.
