### ISSUE TITLE
data input into model.fit() for multiple dense(2,)  layers 

### ISSUE THREAD

**Issue by Samjith888** [tensorflow/tensorflow#41524]
```
def func(img_batch, lb_batch):
  lbs = tf.one_hot(lb_batch,depth=2)
  return img_batch, lbs

train_Data = train_ds.map(func)

model.fit(train_Data,steps_per_epoch=400,validation_steps=40,
                    epochs=50,verbose=1))
```

Error:
The model is expecting a 2 separate arrays , but the custom funtion return single array with shape (2,2).

Here the lbs in func is retrun single array with shape (2,2), how can i make the lb into seperate array with each having shape (1,2)?

**Comment by Samjith888** [comment]
Any updates ?

**Comment by Saduf2019** [comment]
@Samjith888 
I ran the above shared code, its incomplete hence i [face a different error](https://colab.research.google.com/gist/Saduf2019/e51869bb8cbc7b062aca0256c6149de9/untitled284.ipynb), please share all dependencies and complete indented code and tf version such that we can replicate the issue faced or a colab gist with the error to analyse. Thanks!

**Comment by Samjith888** [comment]
> @Samjith888
> I ran the above shared code, its incomplete hence i [face a different error](https://colab.research.google.com/gist/Saduf2019/e51869bb8cbc7b062aca0256c6149de9/untitled284.ipynb), please share all dependencies and complete indented code and tf version such that we can replicate the issue faced or a colab gist with the error to analyse. Thanks!

General use case:

Assume the model is expecting a 2 separate arrays , but the custom funtion return single array with shape (2,2).

```
def func(img_batch, lb_batch):
  lbs = tf.one_hot(lb_batch,depth=2)
  return img_batch, lbs

train_Data = train_ds.map(func)

model.fit(train_Data,steps_per_epoch=400,validation_steps=40,
                    epochs=50,verbose=1))
```
Here the lbs in  func is retrun single array with shape (2,2), how can i make the lb into seperate array with each having shape (1,2)?

**Comment by Samjith888** [comment]
> > @Samjith888
> > I ran the above shared code, its incomplete hence i [face a different error](https://colab.research.google.com/gist/Saduf2019/e51869bb8cbc7b062aca0256c6149de9/untitled284.ipynb), please share all dependencies and complete indented code and tf version such that we can replicate the issue faced or a colab gist with the error to analyse. Thanks!
> 
> General use case:
> 
> Error:
> The model is expecting a 2 separate arrays , but the custom funtion return single array with shape (2,2).
> 
> ```
> def func(img_batch, lb_batch):
>   lbs = tf.one_hot(lb_batch,depth=2)
>   return img_batch, lbs
> 
> train_Data = train_ds.map(func)
> 
> model.fit(train_Data,steps_per_epoch=400,validation_steps=40,
>                     epochs=50,verbose=1))
> ```
> 
> Here the lbs in func is retrun single array with shape (2,2), how can i make the lb into seperate array with each having shape (1,2)?

@Saduf2019  here i have simplified the error

**Comment by Samjith888** [comment]
> ```
> def func(img_batch, lb_batch):
>   lbs = tf.one_hot(lb_batch,depth=2)
>   return img_batch, lbs
> 
> train_Data = train_ds.map(func)
> 
> model.fit(train_Data,steps_per_epoch=400,validation_steps=40,
>                     epochs=50,verbose=1))
> ```
> 
> Error:
> The model is expecting a 2 separate arrays , but the custom funtion return single array with shape (2,2).
> 
> Here the lbs in func is retrun single array with shape (2,2), how can i make the lb into seperate array with each having shape (1,2)?

@Saduf2019  please look at the updated issue ,, there  i have simplified the use case

**Comment by Saduf2019** [comment]
@Samjith888 
I ran the code again its incomplete, please share a colab gist and the tf version.
