### ISSUE TITLE
  The memory required for the training model is equivalent to the size of “model.ckpt-0.data”？

### ISSUE THREAD

**Issue by AI-Friend** [tensorflow/tensorflow#41538]
I want to allocate enough memory space in advance for my model.
The size of "model.ckpt-0.data" is 1GB,
Does it mean that the memory consumed during training is about 1GB.

**Comment by lordtt13** [comment]
You could try [this](https://stackoverflow.com/questions/36331419/tensorflow-how-to-measure-how-much-gpu-memory-each-tensor-takes) on colab before allocating memory locally.

**Comment by Saduf2019** [comment]
@AI-Friend 
If you want to use colab, you may select gpu by changing runtime type and run your code.

**Comment by AI-Friend** [comment]
Thank you，I see!  
I have this problem：“Allocation of 25046108416 exceeds 10% of system memory.” 
Why just over 10% of the memory, the model can not be trained?

**Comment by ymodak** [comment]
If you can use estimators then it provides a handy api [tf.estimator.BestExporter](https://www.tensorflow.org/api_docs/python/tf/estimator/BestExporter) which can be useful in your case.
You can also see external contributors https://github.com/vonclites/checkmate wrapper for `tf.train.Saver` api.
