### ISSUE TITLE
Can Keras be installed to work with the TensorFlow 1.15.0 for C++ binary or should I build TensorFlow 2.0 for C++ from source to get Keras?

### ISSUE THREAD

**Issue by ProfHariSeldon** [tensorflow/tensorflow#41533]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04 LTS Oracle VM Virtualbox inside Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): Binary https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-1.15.0.tar.gz
- TensorFlow version: 1.15.0
- Python version: Actually I'm using the C++ 0.29.0 extension in Visual Studio Code 1.47.1, but my Python version is Python 3.8.2
- Installed using virtualenv? pip? conda?: No installed from TensorFlow C++ binary libtensorflow-gpu-linux-x86_64-1.15.0.tar.gz
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a?
- GPU model and memory: NVIDIA GeForce GTS 965M with 2,048 MB GDDR5 memory. 32 GB RAM.

**Describe the problem**

I do not know how to install Keras in TensorFlow 1.15.0 for C++ even though I have previously installed and used Keras in Python.  The description of Keras on their website suggests that Keras only works in Python and cannot be used in C++, while on the other hand I heard that TensorFlow 2.0 has Keras inside so maybe I could build that from source to work in C++?

> Keras is a deep learning API written in **Python**, running on top of the machine learning platform TensorFlow.

https://keras.io/about/

On the other hand I heard that TensorFlow 2.0 has Keras inside:

> Now with version 2, TensorFlow includes Keras built it.

https://towardsdatascience.com/creating-a-tensorflow-cnn-in-c-part-2-eea0de9dcada

So would it be possible to build TensorFlow 2.0 alpha in C++ to get Keras that way?

> Build TensorFlow 2.0 Alpha from source

https://itnext.io/how-to-use-your-c-muscle-using-tensorflow-2-0-and-xcode-without-using-bazel-builds-9dc82d5e7f80

Is this where the TensorFlow 2.0 source is?
https://github.com/tensorflow/tensorflow

I want to use Keras in C++ because I am doing a Udemy.com C++ online course capstone project to use a Convolutional Neural Network for image classification.  I have successfully installed TensorFlow 1.15.0 for C++ by following the directions here: https://www.tensorflow.org/install/lang_c and some C++ TensorFlow test code worked.

So the installation instructions for Keras say do this but the problem is I think that's for python only not C++:
```
sudo apt install python3-pip
pip install --upgrade pip
pip install keras
pip install --upgrade keras
```
https://linuxize.com/post/how-to-install-pip-on-ubuntu-18.04/
https://www.liquidweb.com/kb/how-to-install-keras/

The alternative is to not use Keras to do the Convolutional Neural Network project and maybe this tutorial would show me how to do that, though they say that Keras is more efficient than doing it without Keras:
https://itnext.io/how-to-use-your-c-muscle-using-tensorflow-2-0-and-xcode-without-using-bazel-builds-9dc82d5e7f80
https://itnext.io/creating-a-tensorflow-dnn-in-c-part-1-54ce69bbd586
https://towardsdatascience.com/creating-a-tensorflow-cnn-in-c-part-2-eea0de9dcada
https://towardsdatascience.com/creating-a-tensorflow-cnn-in-c-part-3-freezing-the-model-and-augmenting-it-59a07c7c4ec6

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gowthamkpr** [comment]
@ProfHariSeldon tensorflow 2.x comes with Keras built in. However you can't find much documentation using it. You can follow this [example](https://towardsdatascience.com/creating-a-tensorflow-cnn-in-c-part-2-eea0de9dcada#:~:text=Now%20with%20version%202%2C%20TensorFlow,and%20documentation%20are%20in%20Python.) for implementing Convolution neural network in C++

**Comment by ProfHariSeldon** [comment]
> @ProfHariSeldon tensorflow 2.x comes with Keras built in. However you can't find much documentation using it. You can follow this [example](https://towardsdatascience.com/creating-a-tensorflow-cnn-in-c-part-2-eea0de9dcada#:~:text=Now%20with%20version%202%2C%20TensorFlow,and%20documentation%20are%20in%20Python.) for implementing Convolution neural network in C++

One more question: If I build tensorflow 2.x from source will it work with C++?  Or NOT work with C++ and only work with Python?

The instructions online (https://www.tensorflow.org/install/source) seem to imply that tensorflow 2.x from source only works with Python because it has a whole "Python version" column in the table and NO "C++ version" column in the table.

**Comment by ProfHariSeldon** [comment]
@gowthamkpr I got TensorFlow 2.2.0 to compile but Visual Studio Code does not know how to #include the files from the 2.2.0 compiled source.  I got Visual Studio Code to #include and run test code when I installed the 1.15.0 binary, but that binary does not have keras, which I want.

I followed these install instructions:
https://gist.github.com/philwo/f3a8144e46168f23e40f291ffe92e63c

With these changes:
```
sudo curl -Lo /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.5.0/bazelisk-linux-amd64

curl -LO https://github.com/tensorflow/tensorflow/archive/v2.2.0.tar.gz
tar xvfz v2.2.0.tar.gz
rm v2.2.0.tar.gz
cd tensorflow-2.2.0

# ./configure.py:_TF_MAX_BAZEL_VERSION = '2.0.0'

echo "2.0.0" > .bazelversion
```

When I did "bazel build //tensorflow/tools/pip_package:build_pip_package" I got a successful message:
```
...
INFO: From Executing genrule //tensorflow/lite/python/testdata:permute_float:
2020-07-22 11:05:51.444193: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 1 operators, 3 arrays (0 quantized)
2020-07-22 11:05:51.444364: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 1 operators, 3 arrays (0 quantized)
2020-07-22 11:05:51.444434: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 1 operators, 4 arrays (0 quantized)
2020-07-22 11:05:51.444460: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 1 operators, 4 arrays (0 quantized)
2020-07-22 11:05:51.444476: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 1 operators, 4 arrays (0 quantized)
2020-07-22 11:05:51.444489: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Identify nearest upsample.: 1 operators, 4 arrays (0 quantized)
2020-07-22 11:05:51.444507: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 0 bytes, theoretical optimal value: 0 bytes.
2020-07-22 11:05:51.444522: I tensorflow/lite/toco/toco_tooling.cc:456] Estimated count of arithmetic ops: 36 ops, equivalently 18 MACs
2020-07-22 11:05:51.444531: I tensorflow/lite/toco/toco_tooling.cc:471] Number of parameters: 20
Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package
INFO: Elapsed time: 76329.124s, Critical Path: 260.54s
INFO: 14283 processes: 14283 local.
INFO: Build completed successfully, 15315 total actions
```

When I did the next step "./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg" I got warnings:
```
tlroot@tlroot-VirtualBox:~/tensorflow-2.2.0$ ./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
Wed 22 Jul 2020 11:49:17 AM EDT : === Preparing sources in dir: /tmp/tmp.8j7NtK55u8
~/tensorflow-2.2.0 ~/tensorflow-2.2.0
~/tensorflow-2.2.0
~/tensorflow-2.2.0/bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow ~/tensorflow-2.2.0
~/tensorflow-2.2.0
/tmp/tmp.8j7NtK55u8/tensorflow/include ~/tensorflow-2.2.0
~/tensorflow-2.2.0
Wed 22 Jul 2020 11:49:37 AM EDT : === Building wheel
warning: no files found matching 'README'
warning: no files found matching '*.pyd' under directory '*'
warning: no files found matching '*.pyi' under directory '*'
warning: no files found matching '*.pd' under directory '*'
warning: no files found matching '*.dylib' under directory '*'
warning: no files found matching '*.dll' under directory '*'
warning: no files found matching '*.lib' under directory '*'
warning: no files found matching '*.csv' under directory '*'
warning: no files found matching '*.h' under directory 'tensorflow/include/tensorflow'
warning: no files found matching '*.proto' under directory 'tensorflow/include/tensorflow'
warning: no files found matching '*' under directory 'tensorflow/include/third_party'
Wed 22 Jul 2020 11:50:14 AM EDT : === Output wheel file is in: /tmp/tensorflow_pkg
tlroot@tlroot-VirtualBox:~/tensorflow-2.2.0$
```

When I tried to run my test code I got errors:
```
#include <stdio.h>
#include <tensorflow/c/c_api.h>

#include "/home/tlroot/tensorflow-2.2.0/tensorflow/c/c_api.h"

int main() {
  printf("Hello from TensorFlow C library version %s\n", TF_Version());
  return 0;
}
```

```
#include <tensorflow/c/c_api.h>
```
cannot open source file "tensorflow/c/c_api.h"C/C++(1696)

```
#include "/home/tlroot/tensorflow-2.2.0/tensorflow/c/c_api.h"
```
#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit (/home/tlroot/Documents/C++/Capstone/CppND-Capstone-Hello-World/src/hello_tf.c).C/C++(1696)
cannot open source file "tensorflow/c/tf_attrtype.h" (dependency of "/home/tlroot/tensorflow-2.2.0/tensorflow/c/c_api.h")C/C++(1696)

**Comment by gowthamkpr** [comment]
@ProfHariSeldon Tensorflow 2.3.0 is now released. You can start using it

**Comment by ProfHariSeldon** [comment]
Thanks that might solve it.  I also found out I can use OpenCV to solve this problem:
https://answers.opencv.org/question/232940/help-updating-10-lines-of-deprecated-opencv-code-in-c/

Specifically by using cats.vs.dogs.cpp:
https://gist.github.com/berak/70bcf5e8240c4af4426f9eff3f42121c
