### ISSUE TITLE
TensorFlow imports into python3 correctly, but I receive unexpected messages

### ISSUE THREAD

**Issue by TCIII** [tensorflow/tensorflow#41534]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): NVIDIA Jetpack4.3 Ubuntu 18.0.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Jetson Nano
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.1.0+nv20.3
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory:

**Describe the problem**

I followed these instruction to install TensorFlow 2.1.0 on Jetpack4.3 on my Jetson Nano: https://docs.nvidia.com/deeplearning/frameworks/install-tf-jetson-platform/index.html except that I installed TensorFlow in a virtual environment (py3cv4) per Section 3 Installing TensorFlow/3.1 Installing Multiple Versions.

When I am in my virtual environment if I start python3 and import tensorflow, I get the following response before the command line prompt returns:

(py3cv4) thomas@thomas-desktop:~$ python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0] on linux
Type “help”, “copyright”, “credits” or “license” for more information.

import tensorflow
2020-07-18 17:28:48.819958: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-07-18 17:28:51.385750: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-07-18 17:28:51.387403: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6

Is this an issue I should be concerned about or did I miss installing a particular TensorFlow dependency?

Regards,
TCIII

**Comment by lordtt13** [comment]
No you shouldn't be, these are just loader messages that CUDA libs have been communicated with.

**Comment by TCIII** [comment]
@lordtt13 ,

Thanks for the response, much appreciated.
Regards,
TCIII

**Comment by lordtt13** [comment]
If that's resolved your issue, please close it.

**Comment by TCIII** [comment]
@lordtt13,

I will close it as soon as I get concurrence from the NVIDIA Developer Forum as this is their version of Tensorflow for the Jetson Nano Jetpack4.3.
However I will not let this issue drag on very long if I do not hear from them.
Regards,
TCIII

**Comment by ravikyram** [comment]
@TCIII 

The following NVIDIA® software must be installed on your system:

NVIDIA® GPU drivers —CUDA 10.1 requires 418.x or higher.
CUDA® Toolkit —TensorFlow supports CUDA 10.1 (TensorFlow >= 2.1.0)
CUPTI ships with the CUDA Toolkit.
cuDNN SDK (>= 7.6)
(Optional) TensorRT 6.0 to improve latency and throughput for inference on some models.
You can find a tutorial here: https://medium.com/@ardianumam/installing-tensorrt-in-ubuntu-dekstop-1c7307e1dcf6

**Comment by TCIII** [comment]
The NVIDIA developers forum concurs that this is normal and there is no problem with my installation.
Regards,
TCIII
