### ISSUE TITLE
Incorrect processing in tf.image.decode_gif for multiple-frame image

### ISSUE THREAD

**Issue by yongtang** [tensorflow/tensorflow#41549]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): n/a
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS or Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:  n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0 and 2.3.0rc1
- Python version: 3.7
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**

While working with `tf.image.decode_gif` for mult-frame image, I noticed the returned value is incorrect after the first image.

**Describe the expected behavior**

All frames should be handled correctly.

**Standalone code to reproduce the issue**

```
import tensorflow as tf
import matplotlib.pyplot as plt

print(tf.version.VERSION)

!curl -OL https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Animated_GIF_cheloVechek.gif/440px-Animated_GIF_cheloVechek.gif

image = tf.image.decode_gif(tf.io.read_file('440px-Animated_GIF_cheloVechek.gif'))
for i in range(image.shape[0]):
  plt.imshow(image[i])
  plt.figure()
```
**Other info / logs** Include any logs or source code that would be helpful to

The image is downloaded from WIKI page:
https://en.wikipedia.org/wiki/GIF#Animated_GIF

Original picture (gif):

![cradle](https://user-images.githubusercontent.com/6932348/87897007-da537480-c9fe-11ea-848e-258add6a3dd5.gif)

First frame extracted:

![test_0](https://user-images.githubusercontent.com/6932348/87897022-e4757300-c9fe-11ea-9020-9c979e5216db.png)
Second frame extracted:

![test_1](https://user-images.githubusercontent.com/6932348/87897023-e7706380-c9fe-11ea-9cc6-b3e2991a26d5.png)

**Comment by mihaimaruseac** [comment]
Can you also check with 2.1.0 please? To detect if there was a regression.

**Comment by yongtang** [comment]
Thanks @mihaimaruseac. I tested with 2.1.0 and the result remains the same.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/1bb8d8abb8ac6eec6eccd48f32735fbc/41549-2-1.ipynb), [TF v2.2](https://colab.research.google.com/gist/amahendrakar/f0bdede175086ce81f5830f577a65389/41549-2-2.ipynb), [TF v2.3.0rc2](https://colab.research.google.com/gist/amahendrakar/4a078bcb9f0dab11ac12d037a084de65/41549-2-3.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/ed185d4223655cce1ce94cb3ec2817ad/41549-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by hyeygit** [comment]
This should be fixed with: https://github.com/tensorflow/tensorflow/commit/3741a7bda7131f7ba26c840d9906a5824bbbc3c3

Here is a [colab](https://colab.research.google.com/drive/1VtcWpG82O4dl4zbC2cyOvDy0hMp6RKQ_?usp=sharing) verifying the fix with a tf-nightly.
