### ISSUE TITLE
TensorFlow Lite currently doesn't support control flow ops

### ISSUE THREAD

**Issue by isfoxHjl** [tensorflow/tensorflow#41547]
TensorFlow Lite currently doesn't support control flow ops: Merge, Switch. We are working on supporting control flow ops, please see github issue at https://github.com/tensorflow/tensorflow/issues/28485. Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, ADD_N, ARG_MAX, CAST, CONCATENATION, CONV_2D, EXPAND_DIMS, FILL, FLOOR, FULLY_CONNECTED, GATHER_ND, GREATER_EQUAL, LESS, LOGICAL_AND, LOGISTIC, MAXIMUM, MAX_POOL_2D, MINIMUM, MUL, PACK, PAD, RANGE, REDUCE_MAX, RESHAPE, RESIZE_BILINEAR, REVERSE_SEQUENCE, SELECT, SHAPE, SLICE, SPARSE_TO_DENSE, SPLIT, SQUEEZE, STRIDED_SLICE, SUB, TANH, TILE, TRANSPOSE, UNPACK. Here is a list of operators for which you will need custom implementations: CTC_BEAM_SEARCH_DECODER, RandomUniform.

**Comment by abattery** [comment]
Currently, TFLite does not support v1 control flow ops. Please try the conversion with the following option or you can upgrade the old control flow ops with v2 control flow ops.

https://www.tensorflow.org/api_docs/python/tf/compat/v1/enable_control_flow_v2

**Comment by karimnosseir** [comment]
As Jaesung mentioned, you will need to enable Control Flow v2
Please reopen if you're having issues and provide details and reproduce steps.

Thanks

**Comment by marziehoghbaie** [comment]
Hi, 
I'm having the same error. "Exception: TensorFlow Lite currently doesn't support control flow ops: Enter, Exit, Merge, Switch."
The problem is that my model has some custom layers implemented in tf1.x.
Besides, The solution @abattery proposed is only possible when using tf2.x, So that for tf1.x the error still remains. 
In the following I attach the code that I used for loading and conversion:(Please Note that I have saved the model weights, and in tf1.x, it is only possible to save in tflite format from session not keras model(when having custom layers)):
`
def convert_h5_2TFLite():
    # DOES NOT WORK !!!!!!!!!!!!!!!
    # load model
    model_path = 'keras_model/model_weights.h5'
    K.set_learning_phase(0)  # make sure its testing mode
    
    with tf.Graph().as_default():

        with tf.Session() as sess:
    
            K.set_session(sess)
            model = create_model_obj(image_size, num_classes)()
            model.load_weights(model_path)

            # convert keras model to tflite
            tfLite_Path = 'tfLite_model/model_Lite.tflite'

            # Convert the model.
            converter = tf.lite.TFLiteConverter.from_session(sess, model.inputs,
                                                         model.outputs)
            converter.allow_custom_ops=True
            tflite_model = converter.convert()
            open(tfLite_Path, "wb").write(tflite_model)`
