### ISSUE TITLE
How to load tensorflow 2.0 savedbundle file  by using Java

### ISSUE THREAD

**Issue by ryanshin712** [tensorflow/tensorflow#41544]
From Tensorflow 1.x version, Java can handle a pb file after using freeze_graph.pb.
But, from Tensorflow 2, since the saved pb structure is different, I don't think a regular way to export file does not work.

I was wondering how to load Tensorflow 2 saved files by using Java.

**Comment by aiscientist** [comment]
I searched several explanations and found out tensorflow 2.0 only supports Andriod app using tflite. So, it seems like there is no way we can use tensorflow 2.0 model file to use Java, right?

**Comment by esgomezm** [comment]
It's possible to do it using tensorflow 2.2.0 by copying the graph and loading the weights:
```
from tensorflow.keras.models import clone_model
    w = tf_model.get_weights()
    with tf.Graph().as_default():
        # clone model in new graph and set weights
        _model = clone_model(tf_model)
        _model.set_weights(w)
```
then save `_model` as usual. I tried the same with tensorflow 2.3.0 and it didn't work for me. Is there any reason?

Also, is there any plan to update the Java API to Tensorflow 2?
