### ISSUE TITLE
libtensorflowlite.so built with flex delegates too big!

### ISSUE THREAD

**Issue by aselva-eb** [tensorflow/tensorflow#41559]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 x86_64 GNU/Linux Docker (official tensorflow image)
- TensorFlow installed from (source or binary): pip
- TensorFlow version (or github SHA if from source): 2.4.0-dev20200712

Modified BUILD to add following dependency:
```
"//tensorflow/lite/delegates/flex:delegate",
```

And did a build using the following command:
```
bazel build --config=monolithic --define=with_select_tf_ops=true -c opt //tensorflow/lite:libtensorflowlite.so
```

**The output:**

`libtensorflowlite.so` that is `147104080` bytes (147MB)

Followed the above instructions to generate a libtensorflow with interpreter support for flex ops. Is this file size of 147MB on the library expected? Is this because I added the flex:delegate dependency? How can I reduce this to be <10MB like the lib produced if I follow the lite/tools/make shell scripts (i.e build_lib.sh)

**Comment by thaink** [comment]
Hi aselva-eb,
For size reduction, I would recommend to use our new selective build rule in tensorflow/lite/delegates/flex/build_def.bzl.
There are several rule that you could uses. Ex: tflite_flex_cc_library for the cc_library and tflite_flex_android_library for android_library.
Note that, it currently only work when you build it for android. selective build for linux is not supported yet.

**Comment by aselva-eb** [comment]
Hi @thaink 

Are there instructions anywhere of how to use the selective build rules?

But also, my target is linux. If selective build rule is not supported for Linux, do you have any suggestions for how I can reduce the lib size by modifying source code maybe? Perhaps manually removing unused non-TFLite ops from being built in by flex (from the allowlist or elsewhere) ? 

Any insight would be appreciated.

**Comment by thaink** [comment]
Hi @aselva-eb 
I think you could try to remove some unused deps from:
`tensorflow/core:all_kernels`
and
`tensorflow/core:all_kernels_impl`
Please let me know the size after you do that.

**Comment by aselva-eb** [comment]
Ok! Will explore that option and get back to you!
Thanks Thai!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Saduf2019** [comment]
@aselva-eb 
Please update on the issue.

**Comment by aselva-eb** [comment]
> @aselva-eb
> Please update on the issue.

Hi. I haven't had the chance to try that. 
Will let you know as soon as I get results

**Comment by aselva-eb** [comment]
> Hi @aselva-eb
> I think you could try to remove some unused deps from:
> `tensorflow/core:all_kernels`
> and
> `tensorflow/core:all_kernels_impl`
> Please let me know the size after you do that.

Hi Thai. It looks like it does reduce the lib size incrementally when I remove kernels.
Looking at the kernels dir it's about 40MB. Not sure how much this contributes to the library size when compiled. Could be more or less.

Can you suggest any big-ticket dependencies I can remove? Or other areas that can be trimmed down? Hoping to reduce this size to less than 50MB if possible.. Any suggestions would be appreciated.

**Comment by thaink** [comment]
Hi @aselva-eb 
It depends a lot on your models. So my recommendations is to remove them all first. Then gradually add them back and use  `bazel run -c opt -- tensorflow/lite/tools:list_flex_ops_main --graphs=<your tflite model>` to check when the lib contains enough kernels for your models.

**Comment by aselva-eb** [comment]
Thank you @thaink - that helped a lot! Was able to shrink the lib to less than half the original

**Comment by Saduf2019** [comment]
@aselva-eb 
Please move this issue to closed status if resolved.
