### ISSUE TITLE
Tensorboard: Feature and/or documentation request: Viz hyper parameter set 

### ISSUE THREAD

**Issue by hholst80** [tensorflow/tensorflow#4155]
(I am not sure if this is a documentation issue or a feature request.)

Running multiple studies using different hyper parameters can be difficult when more than a handful of hyper parameters are investigated over a shorter timespan. The way we done it is to show the active hyper parameter set  in an ascii string (the log directory name). 

We already have 10 or so hyper parameters and showing them all in the directory name of the plot and comparing them is simply not a sustainable workflow. Naming the log directories the same as the input file (spec. the hyperparameters) is not so good either because the researcher have to open up the file and see / remind himself what the specific hyperparamteres where set to.

I wonder what people suggests using in this workflow? Is there a efficient workflow for this that I just have not discovered yet, or is some new feature required?

**Comment by poxvoculi** [comment]
This seems more like a stackoverflow question.  It doesn't seem like a feature that TensorFlow would plausibly provide.

**Comment by tatatodd** [comment]
Yes, this is a question better suited for StackOverflow.  Please ask it there and tag it with the `tensorflow` tag.  Thanks!
