### ISSUE TITLE
keras.Model.save_weights is overwriting all_model_checkpoint_paths

### ISSUE THREAD

**Issue by stefan-falk** [tensorflow/tensorflow#41553]
**System information**
- Tensorflow 2.2.0

**Describe the current behavior**

`keras.Model.save_weights` does not respect existing checkpoints.

Using `save_weights()` from a Keras model seems to overwrite the `checkpoint` file without preserving existing checkpoints (`all_model_checkpoint_paths`) of that file.

https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/keras/engine/network.py#L1173

**Describe the expected behavior**

`keras.Model.save_weights` should respect existing checkpoints.

**Standalone code to reproduce the issue**

```python
import os
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers


def main():
    nb_checkpoints = 3

    inputs = layers.Input(shape=(8,))
    x = layers.Dense(2)(inputs)
    outputs = layers.Dense(2)(x)
    model = keras.Model(inputs=[inputs], outputs=[outputs])

    model_dir = '/tmp/save-weights'
    for i in range(nb_checkpoints):
        model.save_weights(os.path.join(model_dir, 'ckpt-%04d' % (i + 1)))

    state = tf.train.get_checkpoint_state(model_dir)
    print('')
    print(state.all_model_checkpoint_paths)

    checkpoint_fp = os.path.join(model_dir, 'checkpoint')
    print('\nContent of %s' % checkpoint_fp)
    with open(checkpoint_fp) as f:
        print(f.read())

    assert state.all_model_checkpoint_paths == nb_checkpoints, \
        'Expected %d checkpoints got %d' % (nb_checkpoints, len(state.all_model_checkpoint_paths))


if __name__ == '__main__':
    main()
```

Output:

```none
['/tmp/save-weights/ckpt-0003']

Content of /tmp/save-weights/checkpoint
model_checkpoint_path: "ckpt-0003"
all_model_checkpoint_paths: "ckpt-0003"

Traceback (most recent call last):
    ...
    assert state.all_model_checkpoint_paths == nb_checkpoints, \
AssertionError: Expected 3 checkpoints got 1
```

**Comment by amahendrakar** [comment]
@stefan-falk,
Could you please try setting the `overwrite` argument as `False` and check if you are facing the same issue. Thanks!

Documentation of [save_weights](https://www.tensorflow.org/api_docs/python/tf/keras/Model#save_weights) for reference.

**Comment by stefan-falk** [comment]
@amahendrakar I just tried it out. Using `overwrite=False` has the same effect.

It should be the line I posted in my first comment that causes this:

https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/keras/engine/network.py#L1173

**Comment by jenishah** [comment]
Hi @amahendrakar , I am interested in working on this.  @gowthamkpr please let me know if you haven't already started and if it's okay if I work on this.

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF 2.6.0-dev20210530,please find the gist[ here](https://colab.research.google.com/gist/sushreebarsa/0e402dfc620207ca74534413626bcc7d/untitled115.ipynb#scrollTo=9rXLNxQgPe87)..Thanks !

**Comment by sachinprasadhs** [comment]
The code which you are referring to is no longer exists in Master brach, update the details with the recent version and post the issue in keras-team/keras repo.

To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
