### ISSUE TITLE
"Introduction to Tensors" has incorrect example image

### ISSUE THREAD

**Issue by SteveXCIV** [tensorflow/tensorflow#41564]
## URL(s) with the issue:

https://www.tensorflow.org/guide/tensor
https://www.tensorflow.org/guide/tensor#multi-axis_indexing

## Description of issue (what needs changing):

The left side image in the figure called "Selecting the last feature across all locations in each example in the batch" has batches 1 (blue) and 2 (green) swapped. The right side image and the surrounding code example show the correct order.

The image that needs an edit is: https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/index1.png

### Submit a pull request?

No. I do not have a way to edit the image.

**Comment by MarkDaoust** [comment]
Thanks for reporting. Fixed. It will take a day for the change to propagate to the site.
