### ISSUE TITLE
AutoGraph fails due to an end-of-line between parentheses

### ISSUE THREAD

**Issue by fachu000** [tensorflow/tensorflow#41563]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): uname -a:
Darwin Daniels-MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

- TensorFlow installed from (source or binary): binary

- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0

- Python version: Python 3.6.8 :: Anaconda, Inc.

**Describe the current behavior**

AutoGraph fails if we introduce an end of line in the definition of a lambda function.  

**Describe the expected behavior**

AutoGraph should work the same way as if there is no EOL. An EOL between parentheses is legitimate Python syntax. In my own code, YAPF introduces the EOL that caused the problem. It was difficult to figure out that this was the problem.

**Standalone code to reproduce the issue**

[colab](https://colab.research.google.com/drive/1b_REMiUPxOwIQ3spSzqpLr6HDJ-yY4j-?usp=sharing)

```python
f = tf.function(
    lambda a, 
    b: a + b)
print(f(1, 2))
```
AutoGraph works however if one removes the EOL between `a,` and `b:`.

**Other info / logs** 

WARNING:tensorflow:AutoGraph could not transform <function <lambda> at 0x7f1132d6a268> and will run it as-is.
Cause: could not parse the source code:

    lambda a, 

This error may be avoided by creating the lambda in a standalone statement.

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <function <lambda> at 0x7f1132d6a268> and will run it as-is.
Cause: could not parse the source code:

    lambda a, 

This error may be avoided by creating the lambda in a standalone statement.

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert

**Comment by rxng8** [comment]
I am pretty sure that multiple line parameter works when complete parameters are on the same line. For example, in this case, a complete parameter of tf.function is the whole lambda function, so it needs to be written on one line. I believe the that if you still want to separate the lambda function on different lines, you can always use "\" to tell the compiler that there is an EOL.

**Comment by fachu000** [comment]
> it needs to be written on one line

I do not understand why. Equivalent Python syntax should yield the same behavior.

**Comment by Saduf2019** [comment]
@fachu000 
I ran the code on nightly version and there and face no warning, please have a look at the [gist here](https://colab.research.google.com/gist/Saduf2019/cacc8cd5c819f58c14b6d8710528e6f4/untitled284.ipynb)

**Comment by fachu000** [comment]
Yes, it seems it has been fixed in nightly. Thanks.
