### ISSUE TITLE
Build tflite_runtime version 2.1.0.post1 for python3.8

### ISSUE THREAD

**Issue by ItsMeTheBee** [tensorflow/tensorflow#41562]
Hey all!

I´m working on a aarch64 system and inside a ros:foxy docker container.
Because I´m working with the google coral chip I need to use tflite_runtime version 2.1.0.post1.
According to the edge tpu guy I need to build from commit "d855adfc5a0195788bf5f92c3c7352e638aa1109"  but after building a python 3.8 wheel file and installing that I still get this error:
`ValueError: Model provided has model identifier ' TPU', should be 'TFL3'`
I´m not sure if this is a edge tpu or tflite issue (see [this](https://github.com/google-coral/edgetpu/issues/170) issue for reference).
I´m also not sure whether i build the correct version because tflite_runtime.__version__ displays 2.1.0. 

Here are my two questions:

- Which branch/tag do I need to pull for version 2.1.0.post1?
- Do you have any idea where this error might come from? (I´m 100% sure I´m loading the correct file)

**Comment by karimnosseir** [comment]
From the error looks like you're trying to load a model in TFLite interpreter that is not a TFLite flatbuffer. Follow EdgeTPU guide for running your converted model.

**Comment by ItsMeTheBee** [comment]
I know that's what it looks like but i´m using the provided examples from the "Getting started" tutorial so the models should be fine. And these issues occur with compiled models as well as normal models.
The paths are fine as well, I tried copy pasting the commands as well as writing them using tab completion.
On the other hand [these](https://github.com/guichristmann/edge-tpu-tiny-yolo) things work just fine so maybe something about the model conversion changed that breaks the EdgeTPU example models?

Does the commit "d855adfc5a0195788bf5f92c3c7352e638aa1109" build version 2.1.0.post1? 
If not maybe this version is responsible for this behavior and I just need to know the right commit to build the right version.

**Comment by karimnosseir** [comment]
@ItsMeTheBee If it is TFLite that you're using please send reproduce steps to the issue. If it is the EdgeTPU part, then please file issue with EdgeTPU so they can help you.

Commit "d855adfc5a0195788bf5f92c3c7352e638aa1109" is available in v2.2 +
