### ISSUE TITLE
ValueError on evaluate with generator.

### ISSUE THREAD

**Issue by surGeonGG** [tensorflow/tensorflow#41569]
```
output = classifier.predict(x=generator)
evaluate = classifier.evaluate(x=generator)
```

This code throws ValueError: Shapes (None, None, None) and (100, 4, 1, 200) are incompatible on the evaluate. The prediction works just fine. 

I don't understand. Why does the predict work when the evaluate gives me a error? Anyone have any ideas?

**Comment by ravikyram** [comment]
@surGeonGG 

Request you to fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by surGeonGG** [comment]
Figured it out. It was because I added another output.

Removed this and everything works fine,

```
    classifier.summary()
    classifier = Model(inputs=classifier.input,
                   outputs=[classifier.output, classifier.get_layer('attention').output])
    classifier.compile(loss='categorical_crossentropy', optimizer=SGD(), metrics=['accuracy'])
```

**Comment by ravikyram** [comment]
@surGeonGG 

Glad to know the issue was resolved. Please, close this thread as your issue was resolved.Thanks!
