### ISSUE TITLE
Unable to generate .pbtxt file for Tensorflow 2.0 models.

### ISSUE THREAD

**Issue by Deep-learning-practitioner** [tensorflow/tensorflow#41575]
**System information**

Running Code on Google Colab
Using Tensorflow 2.2

**Problem**

I'm trying to generate a .pbtxt file from a .pb file that I trained using **TFOD 2 api**  but I'm getting a parsing message error. In fact I'm even getting this error when I try to use a trained SSD mobilenet V2 model from tensorflow model Zoo.

**This is the Code Used to get .pbtxt, you can just paste this code in google colab and the error will be reproduced**

```

!wget 'http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_320x320_coco17_tpu-8.tar.gz'
!tar -xf ssd_mobilenet_v2_320x320_coco17_tpu-8.tar.gz
model_path = 'ssd_mobilenet_v2_320x320_coco17_tpu-8/saved_model/saved_model.pb'

import tensorflow as tf

with tf.io.gfile.GFile(model_path, "rb") as f:
    graph_def = tf.compat.v1.GraphDef()
    graph_def.ParseFromString(f.read())

    for i in reversed(range(len(graph_def.node))):
        if graph_def.node[i].op == 'Const':
            del graph_def.node[i]

    tf.io.write_graph(graph_def, "", 'graph.pbtxt', as_text=True)
```

Facing this Error while running the code:
```

----> graph_def.ParseFromString(f.read())
DecodeError: Error parsing message
```

**How can I generate a .pbtxt file from Tensorflow Object detection api 2.x models. The end goal is to use these models inside OpenCV DNN module**

**Comment by ravikyram** [comment]
I have tried in colab with TF 2.2, 2.3-rc1,nightly version and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/958ba7472041d6d10f58229a2808539f/untitled155.ipynb).Thanks!

**Comment by Deep-learning-practitioner** [comment]
Closing as a duplicate of #8923 in tensorflow/models/issues
