### ISSUE TITLE
Tensorflow lite make error

### ISSUE THREAD

**Issue by jiahueytsao** [tensorflow/tensorflow#41578]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows 10 x64
- TensorFlow installed from (source or binary):source(tensorflow-master) for github
- Tensorflow version (commit SHA if source):
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): keil IDE 5.30

**Describe the problem**
Git Bash 2.270 x64 was used
error of make the generate_projects=>error1
**Please provide the exact sequence of commands/steps when you ran into the problem**
1.start git bash
2. change the file directory to d;\tensorflow-master
3. make -f tensorflow/lite/micro/tools/make/Makefile generate_projects
4. error1 ocurred, process stopped
![tensorflow lite make error](https://user-images.githubusercontent.com/44084579/88012475-8eaee100-cb4c-11ea-8e9b-a0182d91d3a1.PNG)

**Comment by Saduf2019** [comment]
@jiahueytsao 
Can we please have the error message within quotes for better readability, with the tensorflow version .

**Comment by jiahueytsao** [comment]
> @jiahueytsao
> Can we please have the error message within quotes for better readability, with the tensorflow version .

Dear Saduf,
The error message in text as following(by using the git bash for windows-x64):
"$ make -f tensorflow/lite/micro/tools/make/Makefile generate_projects
tensorflow/lite/micro/tools/make/Makefile:305: warning: overriding recipe for ta
rget 'tensorflow/lite/micro/tools/make/downloads/ruy'
tensorflow/lite/micro/tools/make/Makefile:305: warning: ignoring old recipe for
target 'tensorflow/lite/micro/tools/make/downloads/ruy'
tensorflow/lite/micro/tools/make/Makefile:305: warning: overriding recipe for ta
rget 'tensorflow/lite/micro/tools/make/downloads/person_model_grayscale'
tensorflow/lite/micro/tools/make/Makefile:305: warning: ignoring old recipe for
target 'tensorflow/lite/micro/tools/make/downloads/person_model_grayscale'
tensorflow/lite/micro/tools/make/Makefile:305: warning: overriding recipe for ta
rget 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
tensorflow/lite/micro/tools/make/Makefile:305: warning: ignoring old recipe for
target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://github.com/goo
gle/gemmlowp/archive/719139ce755a0f31cbf1c37f7f98adcc7fc9f425.zip" "7e8191b24853
d75de2af87622ad293ba" tensorflow/lite/micro/tools/make/downloads/gemmlowp
downloading https://github.com/google/gemmlowp/archive/719139ce755a0f31cbf1c37f7
f98adcc7fc9f425.zip
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://github.com/goo
gle/flatbuffers/archive/v1.12.0.zip" "a1afdbf114dec01a861c1b8c917d0fc7" tensorfl
ow/lite/micro/tools/make/downloads/flatbuffers
downloading https://github.com/google/flatbuffers/archive/v1.12.0.zip
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://github.com/goo
gle/ruy/archive/d492ac890d982d7a153a326922f362b10de8d2ad.zip" "3a5c19abc60c3d9a8
045ddf6b114067f" tensorflow/lite/micro/tools/make/downloads/ruy
downloading https://github.com/google/ruy/archive/d492ac890d982d7a153a326922f362
b10de8d2ad.zip
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://storage.google
apis.com/download.tensorflow.org/models/tflite/cifar_image_recognition_model_202
0_05_27.zip" "1f4607b05ac45b8a6146fb883dbc2d7b" tensorflow/lite/micro/tools/make
/downloads/image_recognition_model
downloading https://storage.googleapis.com/download.tensorflow.org/models/tflite
/cifar_image_recognition_model_2020_05_27.zip
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://www.cs.toronto
.edu/~kriz/cifar-10-binary.tar.gz" "c32a1d4ab5d03f1284b67883e8d87530" tensorflow
/lite/micro/tools/make/downloads/cifar10 patch_cifar10_dataset
downloading https://www.cs.toronto.edu/~kriz/cifar-10-binary.tar.gz
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://github.com/mbo
rgerding/kissfft/archive/v130.zip" "438ba1fef5783cc5f5f201395cc477ca" tensorflow
/lite/micro/tools/make/downloads/kissfft patch_kissfft
downloading https://github.com/mborgerding/kissfft/archive/v130.zip
Finished patching kissfft
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://storage.google
apis.com/download.tensorflow.org/data/tf_lite_micro_person_data_grayscale_2020_0
5_27.zip" "55b85f76e2995153e660391d4a209ef1" tensorflow/lite/micro/tools/make/do
wnloads/person_model_grayscale
downloading https://storage.googleapis.com/download.tensorflow.org/data/tf_lite_
micro_person_data_grayscale_2020_05_27.zip
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://storage.google
apis.com/download.tensorflow.org/data/tf_lite_micro_person_data_int8_grayscale_2
020_06_23.zip" "9b5b6d4677dd0a91b1bb992d1c4c0417" tensorflow/lite/micro/tools/ma
ke/downloads/person_model_int8
downloading https://storage.googleapis.com/download.tensorflow.org/data/tf_lite_
micro_person_data_int8_grayscale_2020_06_23.zip
/usr/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/usr/bin/sh: -c: line 1: syntax error: unexpected end of file
make: *** [tensorflow/lite/micro/examples/hello_world/Makefile.inc:34: tensorflo
w/lite/micro/tools/make/gen/windows_x86_64/prj/hello_world_test/keil/keil_projec
t.uvprojx] Error 1
"
Meanwhile, the error picture was attached again for your reference.
The tensorflow version was the newest, just download from the github site of tensorflow on 2020/7/24
![generate_projects make error](https://user-images.githubusercontent.com/44084579/88372873-57993380-cdc9-11ea-9de0-1d835426a74c.png)

**Comment by jiahueytsao** [comment]
Dear Saduf,
The error message in text as following(by using the git bash for windows-x64):
"$ make -f tensorflow/lite/micro/tools/make/Makefile generate_projects
tensorflow/lite/micro/tools/make/Makefile:305: warning: overriding recipe for ta
rget 'tensorflow/lite/micro/tools/make/downloads/ruy'
tensorflow/lite/micro/tools/make/Makefile:305: warning: ignoring old recipe for
target 'tensorflow/lite/micro/tools/make/downloads/ruy'
tensorflow/lite/micro/tools/make/Makefile:305: warning: overriding recipe for ta
rget 'tensorflow/lite/micro/tools/make/downloads/person_model_grayscale'
tensorflow/lite/micro/tools/make/Makefile:305: warning: ignoring old recipe for
target 'tensorflow/lite/micro/tools/make/downloads/person_model_grayscale'
tensorflow/lite/micro/tools/make/Makefile:305: warning: overriding recipe for ta
rget 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
tensorflow/lite/micro/tools/make/Makefile:305: warning: ignoring old recipe for
target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://github.com/goo
gle/gemmlowp/archive/719139ce755a0f31cbf1c37f7f98adcc7fc9f425.zip" "7e8191b24853
d75de2af87622ad293ba" tensorflow/lite/micro/tools/make/downloads/gemmlowp
downloading https://github.com/google/gemmlowp/archive/719139ce755a0f31cbf1c37f7
f98adcc7fc9f425.zip
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://github.com/goo
gle/flatbuffers/archive/v1.12.0.zip" "a1afdbf114dec01a861c1b8c917d0fc7" tensorfl
ow/lite/micro/tools/make/downloads/flatbuffers
downloading https://github.com/google/flatbuffers/archive/v1.12.0.zip
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://github.com/goo
gle/ruy/archive/d492ac890d982d7a153a326922f362b10de8d2ad.zip" "3a5c19abc60c3d9a8
045ddf6b114067f" tensorflow/lite/micro/tools/make/downloads/ruy
downloading https://github.com/google/ruy/archive/d492ac890d982d7a153a326922f362
b10de8d2ad.zip
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://storage.google
apis.com/download.tensorflow.org/models/tflite/cifar_image_recognition_model_202
0_05_27.zip" "1f4607b05ac45b8a6146fb883dbc2d7b" tensorflow/lite/micro/tools/make
/downloads/image_recognition_model
downloading https://storage.googleapis.com/download.tensorflow.org/models/tflite
/cifar_image_recognition_model_2020_05_27.zip
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://www.cs.toronto
.edu/~kriz/cifar-10-binary.tar.gz" "c32a1d4ab5d03f1284b67883e8d87530" tensorflow
/lite/micro/tools/make/downloads/cifar10 patch_cifar10_dataset
downloading https://www.cs.toronto.edu/~kriz/cifar-10-binary.tar.gz
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://github.com/mbo
rgerding/kissfft/archive/v130.zip" "438ba1fef5783cc5f5f201395cc477ca" tensorflow
/lite/micro/tools/make/downloads/kissfft patch_kissfft
downloading https://github.com/mborgerding/kissfft/archive/v130.zip
Finished patching kissfft
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://storage.google
apis.com/download.tensorflow.org/data/tf_lite_micro_person_data_grayscale_2020_0
5_27.zip" "55b85f76e2995153e660391d4a209ef1" tensorflow/lite/micro/tools/make/do
wnloads/person_model_grayscale
downloading https://storage.googleapis.com/download.tensorflow.org/data/tf_lite_
micro_person_data_grayscale_2020_05_27.zip
tensorflow/lite/micro/tools/make/download_and_extract.sh "https://storage.google
apis.com/download.tensorflow.org/data/tf_lite_micro_person_data_int8_grayscale_2
020_06_23.zip" "9b5b6d4677dd0a91b1bb992d1c4c0417" tensorflow/lite/micro/tools/ma
ke/downloads/person_model_int8
downloading https://storage.googleapis.com/download.tensorflow.org/data/tf_lite_
micro_person_data_int8_grayscale_2020_06_23.zip
/usr/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/usr/bin/sh: -c: line 1: syntax error: unexpected end of file
make: *** [tensorflow/lite/micro/examples/hello_world/Makefile.inc:34: tensorflo
w/lite/micro/tools/make/gen/windows_x86_64/prj/hello_world_test/keil/keil_projec
t.uvprojx] Error 1
"
Meanwhile, the error picture was attached again for your reference.
The tensorflow version was the newest, just download from the github site of tensorflow on 2020/7/24
generate_projects make error
![generate_projects make error](https://user-images.githubusercontent.com/44084579/88373059-b65ead00-cdc9-11ea-8e6e-67377c2d7a8d.png)

**Comment by ymodak** [comment]
@jiahueytsao You need to pass project names individually . See example usage below;
https://github.com/tensorflow/tensorflow/blob/a4725be4a74c9acae623231e80d5a8002a54e94a/tensorflow/lite/micro/tools/make/Makefile#L10
Also see similar [thread](https://github.com/tensorflow/tensorflow/issues/41818)
Thanks!
