### ISSUE TITLE
TFDBG doesn't display any tensor 

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/tensorflow#41573]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.0rc2
- Python version: 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
![Screenshot from 2020-07-21 10-49-27](https://user-images.githubusercontent.com/17592563/88007139-df6c0d00-cb3f-11ea-8309-749d1df03c43.png)

**Describe the expected behavior**
Display record tensors which like tf1.x
**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```
python -m tensorflow.python.debug.examples.v2.debug_mnist_v2     --dump_dir /tmp/tfdbg2_logdir --dump_tensor_debug_mode FULL_HEALTH
```
```
python -m tensorflow.python.debug.cli.offline_analyzer --dump_dir="/tmp/tfdbg2_logdir"
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by caisq** [comment]
`tensorflow.python.debug.cli.offline_analyzer` is not compatible with the debugger v2 API in TF 2.x (i.e., the `tf.debugging.experimental.enable_dump_debug_info()` as used in the `debug_mnist_v2` example). Instead, please use tensorboard (2.3+, to be released soon) to look at the dumped debug data. 

Please take a look at https://www.tensorflow.org/tensorboard/debugger_v2 for more details.

**Comment by fsx950223** [comment]
> `tensorflow.python.debug.cli.offline_analyzer` is not compatible with the debugger v2 API in TF 2.x (i.e., the `tf.debugging.experimental.enable_dump_debug_info()` as used in the `debug_mnist_v2` example). Instead, please use tensorboard (2.3+, to be released soon) to look at the dumped debug data.
> 
> Please take a look at https://www.tensorflow.org/tensorboard/debugger_v2 for more details.

Any plan to fix cli?
Sometimes, I worried about Tensorboard has worse performance than cli.
Because Tensorboard uses resources to render web UI.
