### ISSUE TITLE
tensorflow lite performs linear relation between batch size and inference time

### ISSUE THREAD

**Issue by yushcs** [tensorflow/tensorflow#41580]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS Linux release 7.2.1511
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):2.3.0.dev2020062301
- Python version:3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):4.8.5
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
  I converted a tiny bert module to tflite and run the  inference with the tensorflow lite c++ api. When batch size=1, tensorflow lite performs average runtime 0.6ms, while tensorflow performs average runtime 1ms(with default threads num); when batch size=10, tensorflow lite performs average runtime 5ms, while tensorflow performs average runtime 3ms.
  It seems tensorflow lite did nothing on multi thread speed up, as i tried to apply SetNumThreads(4).
  And SetNumThreads(4) and SetNumThreads(1) performs same runtime, though cpu usage change from 100% to 200%

**Describe the expected behavior**
  I am wondering is this a normal performance for tflite in the X86 desktop?

**Standalone code to reproduce the issue**
Here is the part of my custom tflite c code
 ```
 class Session {
 public:
    Session() {
      model_ = NULL;
      interpreter_ = NULL;
    }

  bool Open(const std::string &saved_model) {
    model_ = tflite::FlatBufferModel::BuildFromFile(saved_model.c_str());
    if (!model_) {
      return false;
    }

    tflite::InterpreterBuilder(*model_.get(), resolver_)(&interpreter_);

    if (!interpreter_) {
      return false;
    }
    interpreter_->SetNumThreads(4);
    return true;
  }

  bool Run(std::vector<int> &dims, int32_t *tok_id, int32_t *msk_id, int32_t *seg_id, float *output) const {
     int tok_index = interpreter_->inputs()[2];
     int msk_index = interpreter_->inputs()[1];
     int seg_index = interpreter_->inputs()[0];
     interpreter_->ResizeInputTensor(tok_index, dims);
     interpreter_->ResizeInputTensor(msk_index, dims);
     interpreter_->ResizeInputTensor(seg_index, dims);

     if(interpreter_->AllocateTensors() != kTfLiteOk) //remove AllocateTensors() did not change the runtime
         return false;
     int32_t bytes = dims[0] * dims[1] * sizeof(int32_t);
     int32_t* tok_tensor = interpreter_->typed_tensor<int32_t>(tok_index);
     memcpy(tok_tensor, tok_id, bytes);
     int32_t* msk_tensor = interpreter_->typed_tensor<int32_t>(msk_index);
     memcpy(msk_tensor, msk_id, bytes);
     int32_t* seg_tensor = interpreter_->typed_tensor<int32_t>(seg_index);
     memcpy(seg_tensor, seg_id, bytes);
     if(interpreter_->Invoke() != kTfLiteOk)
         return false;
     bytes = dims[0] * sizeof(float);
     float* result = interpreter_->typed_output_tensor<float>(0);
     memcpy(output, result, bytes);
     return true;
  }

private:
  std::unique_ptr<tflite::FlatBufferModel> model_;
  std::unique_ptr<tflite::Interpreter> interpreter_;
  tflite::ops::builtin::BuiltinOpResolver resolver_;
};

```

**Comment by karimnosseir** [comment]
T.J Can you please help.

Thanks

**Comment by pjpratik** [comment]
Hi @yushcs 

Is the issue still persists with the TF Lite model converted from TF 2.11 or TF 2.12 ?

The tflite provides benchmarking tool to measure and calculate statistics for the following different performance metrics like Initialization time, Inference time of warmup state, Inference time of steady state, Memory usage during initialization time and Overall memory usage.

Please check this [document](https://www.tensorflow.org/lite/performance/measurement#benchmark_tools) on benchmarking the tflite models and let us know if that helps.

Thanks.
