### ISSUE TITLE
tf.keras.datasets.imdb.load_data() where path is a local path

### ISSUE THREAD

**Issue by Hailprob** [tensorflow/tensorflow#41582]
When I download imdb dataset and save it in my disk, say, the **loacl path** is 'D:/datasets/imdb.npz', when I pass the path into load_data() API, remote download will start rather than load data from local path.

**Comment by Saduf2019** [comment]
@Hailprob 
Please follow [this comment](https://github.com/tensorflow/tensorflow/issues/32278#issuecomment-531051609) and let us know.
