### ISSUE TITLE
Add support for NVIDIA nccl library

### ISSUE THREAD

**Issue by Mistobaan** [tensorflow/tensorflow#4158]
The nccl library supports fast GPU-GPU communications and tensorflow could leverage its use.

https://github.com/NVIDIA/nccl

I think I read somewhere that Google is implementing this internally, but would be good to know what is the plan.

**Comment by poxvoculi** [comment]
We're aware of this.  The TensorFlow programming model is somewhat different from what this library addresses.  We want programmers to specify their computations at a higher level, and plan to automatically support parallel distribution including efficient data transfers as needed.

**Comment by Mistobaan** [comment]
So let me reframe the question. What is the plan to leverage the GPU to GPU communication capabilities of hardware like PCI switch or the DGX1 ? [nccl seems to use NVLINK and QPI primitives](https://github.com/NVIDIA/nccl/blob/75bad643bde5e252346176fe26df08c65ecbb6b6/src/libwrap.cu) and doing a github search for those same primitive names, seems the stream_executor does not support that.

**Comment by zheng-xq** [comment]
It is unlikely TensorFlow can use NCCL in its current form, as it doesn't fit into TensorFlow's programming and memory model. However, we could implement something similar to leverage the lower-level functionalities. Although I don't have a timeline at this point.

**Comment by Mistobaan** [comment]
I think this has changed recently right?

**Comment by poxvoculi** [comment]
Looks like NCCL support has been added via contrib.  @cwhipkey

**Comment by cwhipkey** [comment]
yes, basic support for all-reductions + broadcast is checked in to contrib.

**Comment by pzz2011** [comment]
@cwhipkey where is the support?

**Comment by cwhipkey** [comment]
tf.contrib.nccl  - see https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/nccl/python/ops/nccl_ops.py
