### ISSUE TITLE
Camera does not resume when activity is resumed - TFLite Android flower-classification codelab

### ISSUE THREAD

**Issue by chiragmittal19** [tensorflow/tensorflow#41581]
<em>This is a bug as per the [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md)</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 8
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Moto E5

**Describe the current behavior**
Camera is stopped when the activity is paused, but does not resume/reinitialize when the activity is resumed

**Describe the expected behavior**
Camera should reinitialize when the activity is resumed.

**How to reproduce the issue**
Open the app. Go to home through system navigation, i.e, pause the activity. Reopen the app from recents screen, i.e, resume the activity. You'll see that the camera is stuck.

**Other info / logs**
Link to Tensorflow Lite Android flower-classification Codelab project -
https://github.com/tensorflow/examples/tree/master/lite/codelabs/flower_classification/android/start

I've already identified the error and fixed it in my fork. Would be glad to create a pull request here.

**Comment by sachinprasadhs** [comment]
Could you please try in the latest Tensorflow version and follow the below tutorial https://codelabs.developers.google.com/codelabs/recognize-flowers-with-tensorflow-on-android#0.
Let us know if you still face an issue. Thanks!
