### ISSUE TITLE
How can I run Tensorflow on one single core, single thread CPP?

### ISSUE THREAD

**Issue by amitpandey2194** [tensorflow/tensorflow#41604]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.12.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I am trying to restrict the number of threads that TensorFlow spawns. In python, I understand we need to use the following steps as pointed out [Here](https://stackoverflow.com/questions/38187808/how-can-i-run-tensorflow-on-one-single-core) I was trying to do the same in CPP, but it doesn't seem that straight forward. 
Questions:
How to modify intra_op_parallelism_threads and inter_op_parallelism_threads correctly?
How to modify the device_count to control the core as well?

**Provide the exact sequence of commands / steps that you executed before running into the problem**
SessionOptions options;
    ConfigProto* config = &options.config;
    string key = "CPU";
    //not sure if this is the correct way to do it.
    (*config->mutable_device_count())[key] = 1; 
    config->set_inter_op_parallelism_threads(1);
    config->set_intra_op_parallelism_threads(1);

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@amitpandey2194 
Can you please refer to existing issue for the same reported here and let us know.
#35784 [link](https://stackoverflow.com/questions/38187808/how-can-i-run-tensorflow-on-one-single-core) [link1](https://ask.cyberinfrastructure.org/t/tensorflow-script-to-run-on-single-core/225)
