### ISSUE TITLE
Unable to import tensorflow 2.2.0 in conda environment

### ISSUE THREAD

**Issue by vinayakvaid** [tensorflow/tensorflow#41602]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.2.0
- Python version:3.7.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Error Details - 

    ***---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    ~\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
         57 
    ---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
         59 
    
    ~\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>
         27             return _mod
    ---> 28     _pywrap_tensorflow_internal = swig_import_helper()
         29     del swig_import_helper
    
    ~\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
         23             try:
    ---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
         25             finally:
    
    ~\.conda\envs\mldeep\lib\imp.py in load_module(name, file, filename, details)
        241         else:
    --> 242             return load_dynamic(name, filename, file)
        243     elif type_ == PKG_DIRECTORY:
    
    ~\.conda\envs\mldeep\lib\imp.py in load_dynamic(name, path, file)
        341             name=name, loader=loader, origin=path)
    --> 342         return _load(spec)
        343 
    
    ImportError: DLL load failed: The specified module could not be found.
    
    During handling of the above exception, another exception occurred:
    
    ImportError                               Traceback (most recent call last)
    <ipython-input-1-d6579f534729> in <module>
    ----> 1 import tensorflow
    
    ~\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py in <module>
         39 import sys as _sys
         40 
    ---> 41 from tensorflow.python.tools import module_util as _module_util
         42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
         43 
    
    ~\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\__init__.py in <module>
         48 import numpy as np
         49 
    ---> 50 from tensorflow.python import pywrap_tensorflow
         51 
         52 # Protocol buffers
    
    ~\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
         67 for some common reasons and solutions.  Include the entire stack trace
         68 above this error message when asking for help.""" % traceback.format_exc()
    ---> 69   raise ImportError(msg)
         70 
         71 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long
    
    ImportError: Traceback (most recent call last):
      File "C:\Users\Vinayak\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *
      File "C:\Users\Vinayak\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()
      File "C:\Users\Vinayak\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
      File "C:\Users\Vinayak\.conda\envs\mldeep\lib\imp.py", line 242, in load_module
        return load_dynamic(name, filename, file)
      File "C:\Users\Vinayak\.conda\envs\mldeep\lib\imp.py", line 342, in load_dynamic
        return _load(spec)
    ImportError: DLL load failed: The specified module could not be found.
    
    
    Failed to load the native TensorFlow runtime.
    
    ***

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I am getting below error on importing tensorflow. The steps I followed were -
> Installed anaconda 
> Created conda env and installed using conda command prompt.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@vinayakvaid 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.Please, refer similar issue #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
Thanks!

**Comment by vinayakvaid** [comment]
@ravikyram My processor is Intel i5 8th gen.

I followed the instructions given on the tensorflow website only. Actually i earlier had tensorflow's 1.x version which was working fine. Recently only I had updated it to 2.2.0 to use keras where the issue has come.

**Comment by ravikyram** [comment]
@vinayakvaid 

Did you install the latest MSVC redistributable from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads .
Tensorflow 2.2 is compiled using MSVC 2019, which appears to require an additional DLL.
Your CPU/Python is on 32 bits?

Thanks!

**Comment by Bluewind001** [comment]
Hi  @ravikyram ，  I have compiled the c++ version of  r2.2 branch  tflite successfully.   use this 
> bazel build -c opt  --config=opt --local_ram_resources=2048  //tensorflow/tools/lib_package:libtensorflow
bazel build -c opt //tensorflow/lite:tensorflowlite

But it is x64 lib, How I can the x86 or win32  library.

**Comment by ravikyram** [comment]
@Bluewind001 

If your workstation is x64, bazel generates a x64 binary by default.
"--cpu=x86" option is needed to build x86 binary.

**Comment by Bluewind001** [comment]
@ravikyram, I try this:
> bazel build --cpu=x86 -c opt  --config=opt --local_ram_resources=2048  //tensorflow/tools/lib_package:libtensorflow

but, it tell me , no cpu x86 toolchain 
> ERROR: C:/users/administrator/_bazel_administrator/rqkipcky/external/local_config_cc/BUILD:47:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'x86'
ERROR: Analysis of target '//tensorflow/tools/lib_package:libtensorflow' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed; build aborted

I try clean bazel info, but still get this error.

**Comment by ravikyram** [comment]
@Bluewind001 

Can you please raise a new issue by filling issue template .We can have discussion there and we can track the issue.Thanks!

**Comment by Bluewind001** [comment]
this issue #41765. Thanks!

**Comment by clement2019** [comment]
hi i had the same issue of importing tensorflow  from conda command prompt  or jupyter  on my CPU .i already  successfully installed Anaconda and later install tensor flow successfully.i got the above error.latter i downloaded and installed msv140 dll still didn't work .i then latter downloaded
Microsoft Visual C++ 2015-2019 Redistributable (x64) and installed
VC_redist.x64 version.
 i had the problem resolved afterwards. hope this help someone out-there with same problem.
cheers
