### ISSUE TITLE
Where is Tensorflow Lite Support Library 

### ISSUE THREAD

**Issue by amitDaMan** [tensorflow/tensorflow#41612]
Here is the guide to Tensorflow Lite Support Library:
https://www.tensorflow.org/lite/guide/lite_support

An exert:

> The [TensorFlow Lite Android Support Library](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/support/java) is designed to help process the input and output of TensorFlow Lite models, and make the TensorFlow Lite interpreter easier to use.

Which links to:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/support/java

which is 404 Page not found.

**Comment by amitDaMan** [comment]
Found it.
https://github.com/tensorflow/tflite-support

You can close this ticket if you want, I will leave it open because the guide should be updated.

**Comment by abattery** [comment]
Thanks for reporting the broken links! Team will fix the links soon.
