### ISSUE TITLE
Error in loading tflite model at runtime from native C++ library.

### ISSUE THREAD

**Issue by sunilkumar-op** [tensorflow/tensorflow#41619]
**System information**

OS Platform and Distribution (windows 10):
Mobile device (oppo reno2) i am building and running on this device through android studio.
TensorFlow installed from (source or binary): Ubuntu terminal through pip3
TensorFlow version:
Python version: python 3.8.2
Installed using pip
Bazel version (if compiling from source): I have created libtensorflowlite.so using bazle(2.0.0) . Now trying to directly use the lib.
GCC/Compiler version (if compiling from source): gnu++11
CUDA/cuDNN version:
GPU model and memory:

**Describe the current behavior**
Trying to load trained model in native source code but getting an error "Could not open '/deeplab/deeplabv3_257_mv_gpu.tflite'." I have built libtensorflowlite.so through bazel for arm64.

Code:-
Java_com_example_myapplication_MainActivity_stringFromJNI(JNIEnv *env, jobject thiz) {
    string model_file = "/deeplab/deeplabv3_257_mv_gpu.tflite";
    StderrReporter error_reporter;
    unique_ptr<tflite::FlatBufferModel> model;

    model = FlatBufferModel::BuildFromFile(model_file.c_str(),
                                           &error_reporter);
    ops::builtin::BuiltinOpResolver resolver;
    std::unique_ptr<tflite::Interpreter> interpreter;
    if(model){
        InterpreterBuilder(*model, resolver)(&interpreter);
        interpreter->AllocateTensors();
    }else{
        return env->NewStringUTF("Model is Null");
    }
    return env->NewStringUTF("Hi from JNI LIBS!");
}
![Code_1](https://user-images.githubusercontent.com/68632656/88143714-5a532780-cc15-11ea-972b-59deda7e0f6b.PNG)

Tried to keep model at different locations like inside cpp folder where source file is present or inside assets folder parallel to cpp folder but still same error is coming.
Also tried to put model in mobile sdcard  and passing that path but still no luck.
**Describe the expected behavior**
Model should load.

**Other info / logs** 

2020-07-22 12:13:07.773 13653-13653/com.example.myapplication D/Main: loaded
2020-07-22 12:13:07.875 13653-13653/com.example.myapplication E/tflite: Could not open '/deeplab/deeplabv3_257_mv_gpu.tflite'.

**Comment by ymodak** [comment]
@sunilkumar-op Apologies for the delay in response. Is this still an issue?
