### ISSUE TITLE
training hangs using `tf.keras.model.fit` on `tf.data.Dataset` in GAN

### ISSUE THREAD

**Issue by aegooby** [tensorflow/tensorflow#41616]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.4
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6.9
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: CUDA 10.1.243/cuDNN 7.6.5
- GPU model and memory: Tesla K80

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

after training for any number of steps equivalent to processing roughly 200 images, the training hangs and does not progress. reports CPU usage to be at over 100% even though the GPU is available and being used.

**Describe the expected behavior**

the training continues as normal at a fairly consistent pace.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

    ...
    31/Unknown - 12s 380ms/step - psnr: 21.3111 - sharpdiff: 14.1349 - disc_loss: 0.6919 - gen_loss: 363.1030 
    32/Unknown - 12s 379ms/step - psnr: 21.3856 - sharpdiff: 14.1562 - disc_loss: 0.6919 - gen_loss: 355.9599  
    33/Unknown - 12s 379ms/step - psnr: 21.4397 - sharpdiff: 14.1673 - disc_loss: 0.6919 - gen_loss: 348.9806  
    34/Unknown - 13s 380ms/step - psnr: 21.5334 - sharpdiff: 14.1921 - disc_loss: 0.6919 - gen_loss: 341.5822
    <hangs here>

the call to `model.fit`:

    checkpoint = tf.keras.callbacks.ModelCheckpoint \
    (
        filepath = os.path.join(util.get_dir("save/checkpoints"), "checkpt"),
        save_weights_only = True,
        save_freq = 25
    );

    image_save = callbacks.ImageSave(util.get_dir("save/images"));

    model = models.GAN(num_scales = 4, hist_len = 4, pred_len = 1);
    model.compile \
    (
        disc_optim = tf.keras.optimizers.Adam(learning_rate = 1e-6, beta_1 = 0.89, beta_2 = 0.99),
        gen_optim = tf.keras.optimizers.Adam(learning_rate = 1e-4, beta_1 = 0.89, beta_2 = 0.99),
        disc_loss = losses.Adversarial(),
        gen_loss = losses.Combined(),
        metrics = [ metrics.PSNR(), metrics.SharpDiff() ],
        run_eagerly = True
    );

    model.fit \
    (
        dataset,
        epochs = epochs,
        callbacks = [ checkpoint, image_save ]
    );

the losses, metrics, `GAN` model, and the `ImageSave` callback are custom (subclassed in keras), if it matters.

**Comment by amahendrakar** [comment]
@aegooby,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by aegooby** [comment]
i fixed the issue - i was using `PIL.Image.open` to load my image files from animated PNGs, which would not load the files correctly all the time. i switched to using `np.savez_compressed` to save images
