### ISSUE TITLE
tf error : Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by zolora** [tensorflow/tensorflow#41623]
![erreur](https://user-images.githubusercontent.com/68639810/88160941-a56a3c00-cc0f-11ea-8416-0a869e5818a1.png)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version: 2.1
- Python version: 3.7
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10
- GPU model and memory: NVIDIA Quattro 2000

I have, at the origins tf2.1, which works very well. For some Reason I have wanted to update to tf2.2. But when I did it "import tensorflow" make this error. So I thought that I aven't good composante like GPU, and I try to go back to tf1.15 but nothing changed. so I decided to comme back to the 2.1 version. And now I have also this error. I Don't undestand how a version could worked in the past  but not now.

I precise that I read a lot of issues and try a lot of thinks but nothing works.
Please help me

**Comment by Saduf2019** [comment]
@zolora 

Please refer to [this link](https://github.com/tensorflow/tensorflow/issues/36683#issuecomment-585097726) and let us know as this is a common resolved issue.
