### ISSUE TITLE
Parallelize and prioritize model inference on ARM CPU with tensorflow lite.

### ISSUE THREAD

**Issue by beyse** [tensorflow/tensorflow#41629]
I have two different neural networks running with tensorflow lite on an embedded device, using an arm cpu. 
My questions are: How can I execute both models at parallel? How can I give one of the two models a higher priority than the other one? The background is: I do not want one model to block or interrept execution of the other model.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
 Thanks!

**Comment by beyse** [comment]
Excellent
