### ISSUE TITLE
contrib.layers: TypeError: optimize_loss() got an unexpected keyword argument 'summaries'

### ISSUE THREAD

**Issue by elibixby** [tensorflow/tensorflow#4162]
Trying to provide a custom list of summaries to `tf.contrib.layers.optimize_loss` fails 

```
>>> import tensorflow as tf
>>> tf.contrib.layers.optimize_loss(tf.constant(1), tf.constant(1), 0.01, tf.train.AdamOptimizer, summaries=['loss', 'gradients'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: optimize_loss() got an unexpected keyword argument 'summaries'
>>> 
```

Tested on a fresh 0.10.0rc0 install, as well as in the `tensorflow/tensorflow:nightly` docker image. 

Little mystified by how this is occuring since the it's correct in source. I suspect it has something to do with everything being brought into the layers namespace.

**Comment by ilblackdragon** [comment]
Just checked with current version (0.11rc1) - doesn't seem to have this issue. Please re-open if it still persists on your side.
