### ISSUE TITLE
batch_to_space & space_to_batch usage.

### ISSUE THREAD

**Issue by sudzam** [tensorflow/tensorflow#41634]
This is a request to improve the documentation to add some examples/use cases.

## URL(s) with the issue:
N/A

Please provide a link to the documentation entry, for example:
**https://www.tensorflow.org/api_docs/python/tf/space_to_batch
https://www.tensorflow.org/api_docs/python/tf/batch_to_space**

## Description of issue (what needs changing):
It's not very clear where/how these two (space_to_batch & batch_to_space) operations are used.

### Clear description
Some examples of how/where these operations are used will help.

### Correct links
https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/python/ops/array_ops.py#L3676-L3678
https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/python/ops/array_ops.py#L3735-L3849

### Parameters defined
N/A

### Returns defined
N/A

### Raises listed and defined
N/A

### Usage example
This is exactly what's required: usage example

### Request visuals, if applicable
Possibly..

### Submit a pull request?
N/A

**Comment by jvishnuvardhan** [comment]
@sudzam I think this is resolved. The updated pages of [space_to_batch](https://www.tensorflow.org/api_docs/python/tf/space_to_batch) and [batch_to_space](https://www.tensorflow.org/api_docs/python/tf/batch_to_space?version=nightly) include examples and an explanation. 


I am closing this issue as it was resolved. Please feel free to reopen if I am mistaken. Thanks!
