### ISSUE TITLE
Can you optimize the text.text_to_word_sequence API？

### ISSUE THREAD

**Issue by jtyoui** [tensorflow/tensorflow#41647]
**System information**
- TensorFlow version (you are using):    2.2.0
- Are you willing to contribute it (Yes/No):  Yes

**Describe the feature and the current behavior/state.**
  
   I want to use ```tf.keras.preprocessing.text.text_to_word_sequence(s, filters='{regex}', split='{regex}')  ```  API to split and filter text. but ```filter``` paramter mapping ```split``` paramter. I just want to ```split``` paramter only split and ```filters``` paramter only filter. It best supports ```regex``` from all paramters.eg:
```python
import tensorflow as tf
s = '该文件夹包含，该文件安装了安装了Keras2.1.5环境。该环境可用Docker'
text_to_word_sequence = tf.keras.preprocessing.text.text_to_word_sequence(s, filters='[0-9.]', split='[，。]')
print(text_to_word_sequence)
# ['该文件夹包含','该文件安装了安装了Keras环境','该环境可用Docker']
```

**Comment by gowthamkpr** [comment]
@jtyoui Can you please let us know how this is gonna help the community. Thanks!
