### ISSUE TITLE
tf.data.Dataset - You must feed a value for placeholder tensor

### ISSUE THREAD

**Issue by leaguilar** [tensorflow/tensorflow#41648]
**System information**
- OS: Ubuntu 18.04.4 LTS (also tested in Windows 10 obtaining the same behaviour)
- TensorFlow installed from: pypi, pip install tf-nightly
- TensorFlow version (use command below): 2.4.0-dev20200718
- Python version: 3.6.9 
 
2020-07-23 09:58:13.497096: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
v1.12.1-36900-g829256e314 2.4.0-dev20200718

**Describe the current behavior**
Computations involving tf.data.Dataset stall. 
If the dataset is small the execution continues properly but the error is still registered in the server logs.

**Standalone code to reproduce the issue**

Excerpt from: https://www.tensorflow.org/tutorials/load_data/images

```
import tensorflow as tf
import pathlib
dataset_url = "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz"
data_dir = tf.keras.utils.get_file(origin=dataset_url, 
                                   fname='flower_photos', 
                                   untar=True)
data_dir = pathlib.Path(data_dir)
list_ds = tf.data.Dataset.list_files(str(data_dir/'*/*'), shuffle=False)
# Triggers the abort message
for f in list_ds.take(5):
    print(f.numpy()) 
```

**Jupyter lab server log**

**2020-07-23 09:52:42.605408: W tensorflow/core/common_runtime/executor.cc:1086] [/device:CPU:0] Executor start aborting: Invalid argument: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [3670]
         [[{{node Placeholder/_0}}]]**

**Comment by Saduf2019** [comment]
@leaguilar 
Can you please refer to [this link](https://stackoverflow.com/questions/40521295/invalid-argument-you-must-feed-a-value-for-placeholder-tensor-with-dtype-float) and let us know if it helps.
I ran your code on nightly and do not face any error, please refer to the [gist here](https://colab.research.google.com/gist/Saduf2019/5c23ca410e27dc9635e844d1278b0f37/untitled284.ipynb)

**Comment by leaguilar** [comment]
@Saduf2019 
Thanks for having a look. 

Yes, I found the discussion you refer to in the link while trying to solve the issue, but the minimal code I posted doesn't use any feed_dict. 

Regarding your collab gist. The error message is logged on the server-side, I have experienced it with a Jupyter lab server both in Linux and Windows. On the client-side (the notebook) no error is logged **(as seen from your colab gist)**. I have no idea if there is a way of reading the server-side log in colab or if there is a way of redirecting that error output to the notebook. So there is no way to know if the error is happening in colab too. 

The minimal code I posted is enough to consistently generate the error message in two of my systems but doesn't produce the stalling behaviour.  As I mentioned, with small enough computations seems like the abort "signal" is triggered after the computation finished with no effect, i.e. no stalling. I believe that the error message should be enough to track down the error.

**Comment by leaguilar** [comment]
@Saduf2019 
After further inspection, the error does get logged in colab's server-side too (using your gist).

Runtime > View runtime logs

![bug](https://user-images.githubusercontent.com/13425173/88288795-914c3a80-ccf4-11ea-940b-ff73cb7e0daf.png)

**Comment by tianhuat** [comment]
I also faced the same issue here, any update?

**Comment by spawnaga** [comment]
I just upgraded my computer so I had to install a new system now my own code I used to have it worked with no issues started giving me this error message today. Not sure why!!!!

**Comment by jsimsa** [comment]
@MarkDaoust could you please take a look? thank you

**Comment by spawnaga** [comment]
I found this issue only happens if you are using tf-nightly. Switching to tensorflow 2.3 resolved the issue

**Comment by MarkDaoust** [comment]
> I found this issue only happens if you are using tf-nightly. Switching to tensorflow 2.3 resolved the issue

Agreed, I can get the warning to pop up with the replication instructions and this nightly:

```
!pip install tf-nightly==2.4.0.dev20200722
```

But not with the current nightly, or with the stable release, so whatever this problem was it seems to have been fixed.
