### ISSUE TITLE
Similar problem happened to me: "tile_functor_gpu.cu.pic.o was not created"

### ISSUE THREAD

**Issue by nonlinear1** [tensorflow/tensorflow#41659]
Similar problem happened to me: "tile_functor_gpu.cu.pic.o was not created"
Tensorflow r1.9
Ubuntu 16.04
gcc 4.8
CUDA 9.0
cuDNN 7.0

_Originally posted by @apepkuss in https://github.com/tensorflow/tensorflow/issues/18839#issuecomment-465826851_

**Comment by nonlinear1** [comment]
I have the same problem. someone know how to solve it?Thank you very much!!!

**Comment by ravikyram** [comment]
@nonlinear1 

Can you please provide code snippet to reproduce the issue.
Also, TF version 1.8 ,1.9 is too old.Can you please upgrade to TF 1.15 and see if the issue still persists.Thanks!

**Comment by nonlinear1** [comment]
I have solve this problem. the version of cudnn must be 7.0.5

在 2020-07-23 23:27:28，ravikyram <notifications@github.com> 写道：


@nonlinear1

Can you please provide code snippet to reproduce the issue.
Also, TF version 1.8 ,1.9 is too old.Can you please upgrade to TF 1.15 and see if the issue still persists.Thanks!

**Comment by ravikyram** [comment]
@nonlinear1 

Glad to know issue was resolved. Please, close this thread as your issue was resolved.Thanks!
