### ISSUE TITLE
The first paragraph of the documentation for tf.linalg.inv is cut in half

### ISSUE THREAD

**Issue by lovasoa** [tensorflow/tensorflow#41656]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/api_docs/python/tf/linalg/inv

## Description of issue (what needs changing):

The first paragraph says

> Computes the inverse of one or more square invertible matrices or their

instead of 

> Computes the inverse of one or more square invertible matrices or their adjoints (conjugate transposes).

![image](https://user-images.githubusercontent.com/552629/88276649-b2eef700-ccdf-11ea-9b32-1eb450ffc57a.png)

**Comment by yongtang** [comment]
The issue is in:

https://github.com/tensorflow/tensorflow/blob/v2.3.0-rc2/tensorflow/core/api_def/base_api/api_def_MatrixInverse.pbtxt#L18-L22

where the summary spans across the description. Created a PR #41665 for the fix.
