### ISSUE TITLE
TensorFlowLite C++ Mobile

### ISSUE THREAD

**Issue by wanglelewang** [tensorflow/tensorflow#41651]
I am a iOS developer

I know you have  
TensorFlowLiteSwift, 2.2.0
TensorFlowLiteC,2.2.0
TensorFlowLiteOC,2.2.0

but  where i can get TensorFlowLite,2.2.0?  ,this only 1.31.0 verison

1.31.0 not working result right answer

**Comment by Saduf2019** [comment]
@wanglelewang 
Could you please share more details as what do you want to install.
Please confirm if you have referred to [this link](https://www.tensorflow.org/lite/guide/build_ios).

**Comment by wanglelewang** [comment]
I want to  build C++ Api used iOS/Android          but  TensorFlowLite only 1.31.0 version

**Comment by wanglelewang** [comment]
eg:   In iOS  use cocoapods  

pod 'TensorFlowLite', '1.31.0' 

this version  can not work, I try it , but result is not right

**Comment by wanglelewang** [comment]
I hope 
pod 'TensorFlowLite', '2.2.0'

**Comment by wanglelewang** [comment]
I try build new Lite  genreal libtensorflow-lite.a  
but  I can not  found Headers.h
  
I use 1.31.0 version Headers  but  error

**Comment by wanglelewang** [comment]
How general  new verison tensorflow_lite.framework  in iOS ?

**Comment by wanglelewang** [comment]
https://www.tensorflow.org/lite/guide/build_ios    I read this link  
but I can not  get framework  
I only get .a not get header files
How I do can get header files???

**Comment by wanglelewang** [comment]
You can give me general TensorFlowLite.frameworks 2.0.0or2.2.0 verison   readme?

**Comment by wanglelewang** [comment]
I use 0.26.1 bazel  run r2.0's  create_ios_frameworks.sh   but  cp: /Users/wanglele/Desktop/TFL/tensorflow/tensorflow/lite/lib_package/../../../bazel-genfiles/tensorflow/tools/lib_package/include/tensorflow/c/LICENSE: No such file or directory  error

How I do ?

**Comment by wanglelewang** [comment]
help

**Comment by terryheo** [comment]
@teijeong could you check this?

**Comment by wanglelewang** [comment]
Starting
Package dir:  /var/folders/sz/hpsf6s1j0px40kq9qdkb4f5w0000gn/T/tmp.AByuZJY5
Creating target Headers directories
Headers, populating: TensorFlow Lite
Headers, populating: Flatbuffer
Generate master LICENSE file and copy to target
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'build' from /Users/wanglele/Desktop/TFLite/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --copt=-w --config=v2
INFO: Reading rc options for 'build' from /Users/wanglele/Desktop/TFLite/tensorflow/.tf_configure.bazelrc:
  'build' options: --host_force_python=PY2 --action_env PYTHON_BIN_PATH=/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python --action_env PYTHON_LIB_PATH=/Library/Python/2.7/site-packages --python_path=/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python --config=xla --action_env TF_CONFIGURE_IOS=1
INFO: Found applicable config definition build:v2 in file /Users/wanglele/Desktop/TFLite/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /Users/wanglele/Desktop/TFLite/tensorflow/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:xla in file /Users/wanglele/Desktop/TFLite/tensorflow/.tf_configure.bazelrc: --define with_xla_support=true
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
INFO: Analyzed target //tensorflow/tools/lib_package:clicenses_generate (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //tensorflow/tools/lib_package:clicenses_generate up-to-date:
  bazel-bin/tensorflow/tools/lib_package/THIRD_PARTY_TF_C_LICENSES
INFO: Elapsed time: 3.129s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
cp: /Users/wanglele/Desktop/TFLite/tensorflow/tensorflow/lite/lib_package/../../../bazel-genfiles/tensorflow/tools/lib_package/include/tensorflow/c/LICENSE: No such file or directory

**Comment by wanglelewang** [comment]
Some people?

**Comment by wanglelewang** [comment]
？

**Comment by terryheo** [comment]
@yyoon any idea on this?

**Comment by yyoon** [comment]
@wanglelewang Is there any reason why you can't use either the `TensorFlowLiteSwift` or `TensorFlowLiteObjc` pods?
As you already mentioned, the `TensorFlowLite` CocoaPod is deprecated, and no longer actively maintained.

Are you trying to use the C++ API in your app?

**Comment by wanglelewang** [comment]
I want to write one code  run iOS/Andriond  ...so  I need C++ API

**Comment by wanglelewang** [comment]
may be  i can use souce code  copy in my code ??  how i do?

**Comment by yyoon** [comment]
> I want to write one code run iOS/Andriond ...so I need C++ API

In general, you can't save that much duplicate code even when you use the C++ API. You still need to write the remaining part of your apps, such as the UI elements, pre/post data processing logic, etc.

If you're main goal is to write a single codebase and use it in both Android/iOS, I would suggest you to take a look at Flutter and its TFLite plugin.

* Flutter: https://flutter.dev/
* tflite_flutter plugin: https://pub.dev/packages/tflite_flutter

**Comment by wanglelewang** [comment]
can not use C++ ?  this feel not good  ,, may be support it?

**Comment by wanglelewang** [comment]
i want to write one C++ Api   code  , be used ios/android  app .. ,  then make easy my work..

**Comment by yyoon** [comment]
Thanks for the feedback. We are considering supporting C++ on iOS in the future, but it won't be ready in the near future.
One alternative that you can consider right now is to use the C API, which you can use in both Android/iOS.

* Android: https://www.tensorflow.org/lite/guide/android#use_tflite_c_api
* iOS: Use the `TensorFlowLiteC` CocoaPod and `#include "c_api.h"` in your code.

**Comment by wanglelewang** [comment]
ok  thans  ,    I hope it's faster，

**Comment by fengsky401** [comment]
> * https://www.tensorflow.org/lite/guide/android#use_tflite_c_api

I think tensorflowlite support C++ API in camera demo. Why not continue supporting?

**Comment by fengsky401** [comment]
> Thanks for the feedback. We are considering supporting C++ on iOS in the future, but it won't be ready in the near future.
> One alternative that you can consider right now is to use the C API, which you can use in both Android/iOS.
> 
> * Android: https://www.tensorflow.org/lite/guide/android#use_tflite_c_api
> * iOS: Use the `TensorFlowLiteC` CocoaPod and `#include "c_api.h"` in your code.

I think tensorflowlite support C++ API in camera demo:https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/ios/camera
Why not continue supporting?
