### ISSUE TITLE
WARNING: /home/dl/.cache/bazel/_bazel_dl/5c17eaa27118632cc679170e55a5e91b/external/boringssl_git/WORKSPACE:1

### ISSUE THREAD

**Issue by jiqiujia** [tensorflow/tensorflow#4165]
WARNING: /home/dl/.cache/bazel/_bazel_dl/5c17eaa27118632cc679170e55a5e91b/external/boringssl_git/WORKSPACE:1: Workspace name in /home/dl/.cache/bazel/_bazel_dl/5c17eaa27118632cc679170e55a5e91b/external/boringssl_git/WORKSPACE (@boringssl) does not match the name given in the repository's definition (@boringssl_git); this will cause a build error in future versions.

### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN: cuda7.5 cuDNN5
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
 ls -l /usr/local/cuda/lib/libcud*
-rw-r--r-- 1 root root 189170  6月 15 13:58 /usr/local/cuda/lib/libcudadevrt.a
lrwxrwxrwx 1 root root     16  6月 15 13:58 /usr/local/cuda/lib/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19  6月 15 13:58 /usr/local/cuda/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 311596  6月 15 13:58 /usr/local/cuda/lib/libcudart.so.7.5.18
-rw-r--r-- 1 root root 558020  6月 15 13:58 /usr/local/cuda/lib/libcudart_static.a

I install tensorflow from the latest source
1. The commit hash (`git rev-parse HEAD`)
1f681d207f56fe3f2ef684873484011e8189ec05

2. The output of `bazel version`
0.3.1

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
this warning produced when I run ./configure. I worry that this will cause some trouble if I upgrade my tensorflow someday

**Comment by martinwicke** [comment]
It's just a warning, and it's an easy fix. Just rename the boringssl repo in the tensorflow workspace, and the dependent rules accordingly. We jus haven't gotten around to it. PRs welcome.

An update to bazel may break the TensorFlow build, at which point we will be bery motivated to fix this quickly.

**Comment by haosdent** [comment]
hi, @jiqiujia @martinwicke Sorry to ping you. A naive question, how could I reproduce this warning.
I run

```
./configure
bazel build -c opt //tensorflow:libtensorflow.so
```

in CentOS 7 and could not find this warning.

**Comment by martinwicke** [comment]
Yup, I think we fixed it, just forgot to close this bug. Thanks!
