### ISSUE TITLE
Can't install Tensorflow 1.x

### ISSUE THREAD

**Issue by NNDEV1** [tensorflow/tensorflow#41667]
I am trying to install Tensorflow 1.14 for a package that I am trying to use. I tried:
`pip3 uninstall tensorflow`

Then I tried to install Tensorflow 1.14 using:
`pip3 install tensorflow==1.14`

and I get the following error
`ERROR: Could not find a version that satisfies the requirement tensorflow==1.14 (from versions: 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2)
ERROR: No matching distribution found for tensorflow==1.14`

I also tried making a new virtual env and tried the following commands but it didn't work. Is there any way to install Tensorflow 1?

**Comment by amahendrakar** [comment]
@NNDEV1,
Please upgrade pip to the latest version using the below command and check if you are facing the same issue.

`python3 -m pip install --upgrade pip`

Also, please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) and check if you have all the required dependencies installed. Thanks!

**Comment by mihaimaruseac** [comment]
You have python3.8. The only TF versions with python3.8 support are versions after and including TF2.2.

TF1.14 is no longer supported
