### ISSUE TITLE
Maybe incorrect Brier score calculation

### ISSUE THREAD

**Issue by maia-adar** [tensorflow/tensorflow#41664]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- TensorFlow version (use command below): 1.15.0
- TensorFlow Probability version: 0.8.0

**Describe the current behavior**

I believe that the way the Brier score calculation is implemented in tensorflow_probability.stats.brier_score is incorrect. The formula used is
 
sum_i p[i]* p[i] - 2*p[k]
  
where p is the probability vector over all discrete outcomes, and k is the realized outcome. (Note: This gives element wise Brier scores, and to get the actual Brier score across the dataset, reduce_mean() must be called.)

**Describe the expected behavior**

This formula does not match the reference cited nor [Wikipedia](https://en.wikipedia.org/wiki/Brier_score) nor the definition that [sklearn](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.brier_score_loss.html) uses. Also, it is stated in the tensorflow_probability docs that the Brier score can be negative, which is not true. 

The reference cited is Brier’s original paper, found [here](https://journals.ametsoc.org/mwr/article/78/1/1/96424/VERIFICATION-OF-FORECASTS-EXPRESSED-IN-TERMS-OF), which states the formula as 

<img width="182" alt="Screen Shot 2020-07-23 at 09 48 34" src="https://user-images.githubusercontent.com/41973500/88304392-3277c880-ccd6-11ea-84c3-237be5929f82.png">

where r is the number of possible classes, n is the number of forecasts, fij is the probability forecast of class j for instance i, and Eij is 0 or 1 depending if the event occurred in class j or not. This is the same formula that is used in sklearn and Wikipedia. By definition, this score cannot be negative.

If we consider the element wise Brier score from this formula, it is

sum_j (p[j] - E[j])2

which is not equivalent to sum_i p[i]* p[i] - 2*p[k]. Tensorflow’s Brier score formula should be corrected to match the commonly accepted definition.

**Comment by jvishnuvardhan** [comment]
@maia-adar Are you referring to [this page](https://www.tensorflow.org/probability/api_docs/python/tfp/stats/brier_score) on TF website?

Are you interested in raising a PR to update the docs? Thanks!

**Comment by MarkDaoust** [comment]
@jvdillon, this looks like a `tfp` issue. Can you triage and/or transfer it over? (The transfer button is in the bottom of the right control panel)

**Comment by rmothukuru** [comment]
@maia-adar,
Sorry for the delayed response. Can you please confirm if the issue still persist. If so, request you to file an issue in [TFP Github Repository](https://github.com/tensorflow/probability/issues/new). Thanks!

**Comment by brianwa84** [comment]
Filed on tfp
