### ISSUE TITLE
Sub-classes of keras.metrics.Metric do not inherit set_model function

### ISSUE THREAD

**Issue by obtu** [tensorflow/tensorflow#41663]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: Linux
- TensorFlow installed from: Binary
- TensorFlow version: v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: Python 3.8.2

**Describe the current behavior**
When creating a custom callback function for use in training/evaluation I get an error:
```python
AttributeError: 'BinaryTruePositives' object has no attribute 'set_model'
```

**Describe the expected behavior**
Fitting/evaluation to continue normally, using custom callback.

**Standalone code to reproduce the issue**
``` python
import tensorflow as tf
import tensorflow.keras as keras
batch_size = 25
N = 10

# From https://www.tensorflow.org/api_docs/python/tf/keras/metrics/Metric
class BinaryTruePositives(tf.keras.metrics.Metric):
    ...

# Set up model
input = keras.layers.Input(shape=(1))
dense = keras.layers.Dense(100, activation='relu')(input)
output = keras.layers.Dense(1, activation='tanh')(dense)

# Create model
model = keras.Model(inputs=input, outputs=output)
model.compile(loss='MSE')

# Following two lines give the error
model.fit(BinaryTruePositives(), steps_per_epoch=N, callbacks=[BinaryTruePositives()])
model.evaluate(BinaryTruePositives(), steps=N, callbacks=[BinaryTruePositives()])

```

**Other info / logs** 
```python
Traceback (most recent call last):
  File "up_test.py", line 47, in <module>
    model.fit(my_generator(), steps_per_epoch=N, callbacks=[BinaryTruePositives()])
  File "~/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 819, in fit
    callbacks = callbacks_module.CallbackList(
  File "~/.local/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 219, in __init__
    self.set_model(model)
  File "~/.local/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 281, in set_model
    callback.set_model(model)
```

**Comment by obtu** [comment]
Are `metric`s only intended for model training, and not for model prediction/evaluation? If so, then I misunderstood the role of `metric`s, and the documentation/guides are not very clear on when `metric`s can be used, and when callbacks can be used.

**Comment by amahendrakar** [comment]
@obtu,
On running the code, I am facing a different error stating `ValueError: Failed to find data adapter that can handle input: <class '__main__.BinaryTruePositives'>, <class 'NoneType'>`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/3ee1278a43a2c1eba17717861f47e555/41663.ipynb#scrollTo=n6ZJiM33UFBi).

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by obtu** [comment]
My bad. Accidentally removed/changed the generator. This is the correct tail of the code:

```python
# Create data
class my_generator(keras.utils.Sequence):
    def __len__(self): return N*N
    def __getitem__(self,index):
        return (np.random.random(batch_size), np.zeros(batch_size))

# Fit model
model.fit(my_generator(), steps_per_epoch=N, callbacks=[BinaryTruePositives()])
model.evaluate(my_generator(), steps=N, callbacks=[BinaryTruePositives()])
```

**Comment by amahendrakar** [comment]
@obtu,
I was able to reproduce the issue with TF v2.2 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/02f0e86424c61cf18154269a82dbb3ed/41663.ipynb#scrollTo=n6ZJiM33UFBi). 

Could you please check [this comment](https://stackoverflow.com/a/47791254) from a similar StackOverflow issue and let us know if it helps. Thanks!

**Comment by obtu** [comment]
`BinaryTruePositives` subclasses `tf.keras.metrics.Metric`in the example, thus the StackOverflow answer is insufficient.

The problem is that `metrics` cannot be used as `callbacks`, and vice versa, in model `compile` and `fit`, respectively.
