### ISSUE TITLE
Creating model in subprocess consume all memory

### ISSUE THREAD

**Issue by tangcxx** [tensorflow/tensorflow#41660]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Keras version: 2.3.1
- Python version: 3.7

The code is below.
I expect the model would be created once. but instead it seems being created again and again. And it never got released.

**Standalone code to reproduce the issue**

```
import keras as k
import numpy as np 
import multiprocessing as mp

def createmodel():
    inputs = k.layers.Input(shape=(720,))
    x = k.layers.Dense(256, activation="relu")(inputs)
    x = k.layers.Dense(256, activation="relu")(x)
    outputs = k.layers.Dense(1, activation="sigmoid")(x)
    model = k.models.Model(inputs, outputs)
    model.compile(loss="binary_crossentropy",
                optimizer="adam")
    return model

class TRAINER:
    def __init__(self):
        self.model = createmodel()

    def play(self, args):
        return (1, np.zeros((720)))

    def train(self):
        mp.set_start_method('spawn')
        p = mp.Pool(4)
        while True:
            res = p.map(self.play, [0] * 128)

trainer = TRAINER()
if __name__ == '__main__':
    trainer.train()
```

**Comment by jvishnuvardhan** [comment]
@tangcxx I am not able to reproduce the exact same error but found different error. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/2326da1679628ce05f9b6909a79f2a0f/untitled963.ipynb). Thanks!

> TypeError: can't pickle _thread.RLock objects

**Comment by tangcxx** [comment]
@jvishnuvardhan I am not sure what it is. Anyway, I 'd solved my problem by removing the class definition. Instead I'd made a global model.
