### ISSUE TITLE
tensorboard error, segement fault core dump

### ISSUE THREAD

**Issue by shartoo** [tensorflow/tensorflow#4166]
Hi, i got an error when using tensorboard.

envirnoment is:

+ python: 2.7
+ os: docker on centos 7, 64bit
+ tensorflow : 0.9.8

i ran the tensorboard on mnist example,and get log file as `/tmp/mnist_logs/` .When i ran tensorboard directily as below ,error as `segement fault, core dump`

```
tensoboard --logdir=/tmp/mnist_logs/

```
if the command changed to 
```
python /usr/lib/python2.7/site-packages/tensorflow/tensoboard/tensorboard.py --logdir=/tmp/mnist_logs/
```
error same. Can anybody help me?

**Comment by dhwajraj** [comment]
this may occur when there are too many logs/checpoints/meta in that directory then tensorboard could go out of memory and throw this error. try keeping only 1 run in logdir.

**Comment by shartoo** [comment]
I checked the logdir ,there is only one file `events.out.tfevents.1472783342.docker01` , and the file size is 1.1MB .

**Comment by shartoo** [comment]
It seems a version bug, after updated to 0.10.0rc0  the tensorboard ran successful.Thank you anyway!
