### ISSUE TITLE
how to batch learning when using input builder function, in skflow

### ISSUE THREAD

**Issue by lsh5207** [tensorflow/tensorflow#4167]
I have got some problem in modifying wide_n_deep_tutorial.py
The problem is the same as 
http://nticformation.com/solutions_problems.php?tuto=145994&subCategory=python+tensorflow+skflow&Category=python

Sorry for my poor english. And many thanks in advance.

**Comment by poxvoculi** [comment]
This sort of question is better asked on stackoverflow, using the #tensorflow tag.
