### ISSUE TITLE
Problems with Transformations when trying to model.fit() my 2D CNN Model, leading to two exceptions

### ISSUE THREAD

**Issue by zhilothebest** [tensorflow/tensorflow#41671]
**System information**
- Have I written custom code [posted below]:
- Microsoft Windows [Version 10.0.18363.959]
- TensorFlow v2.2.0-rc4-8-g2b96f3662b 2.2.0 installed via pip. Cuda 10.1 with CUDNN 10.1. GPU enabled.
- Python version: 3.7
- GPU model and memory: GeForce GTX 1650 with Max-Q Design computeCapability: 7.5
coreClock: 1.245GHz coreCount: 16 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 104.34GiB/s
-Done in Jupyter Notebook

While training my model using the model.fit() method, my generator inputs the first image slice (with corresponding segmentation truth). During that process, I get 2 exceptions, which ill post after my code. I believe the issue has to do during the flatten method, but I do not know how to address that change.

**Standalone code to reproduce the issue**
```
import ctypes
#hllDll = ctypes.WinDLL("C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\cudart64_101.dll")
#incase cudart64_101.dll is unable to be loaded
import os
import numpy as np
from medpy.io import load
import tensorflow as tf
import tensorflow.keras as tfk
from tensorflow.keras import layers
import keras
from keras.utils.vis_utils import plot_model
import sklearn
from scipy.ndimage import rotate
import scipy
from sklearn import datasets, preprocessing, model_selection, metrics
import matplotlib.pyplot as plt
%matplotlib inline
```

```
#Image dict is just a dictionary of paths to .mhd files for images and segmentation truths    

def image_preprocessing(array):
    logging.info("Beginning Preprocessing")
    
    logging.info("Rotating Image into axial plane")
    array = rotate(array, 90, axes=(0,2), reshape=True) #rotates to axial form sup to inf
    
    logging.info("Making image to uniform size")
    
    blank_array = np.full((1,512,512),-3024) #-3024 is the "background, out of zoom data point"
    
    while len(array) < 69:
        array = np.append(array, blank_array, axis = 0)
        array = np.append(blank_array, array, axis = 0)
        
    if len(array) == 69:
        array = np.append(array,blank_array, axis = 0)
    else:
        pass
    
    logging.info("Image Preprocessing is complete")
    
    return array

def image_generator(img_dict, mask):
    
    include_mask = False
    
    logging.info("creating generator for {}.".format(img_dict))
    
    if mask == True:
        include_mask = True
    
    if include_mask == True:
        
        for path1, path2 in zip(img_dict['image'],img_dict['mask']):
            logging.info("loading {} {} into generator".format("image",os.path.basename(path1)))
            image, header_img = load(path1)
            print("Image processing")
            image = image_preprocessing(image)
            
            
            logging.info("loading {} {} into generator".format("mask",os.path.basename(path2)))
            mask_img, header_mask = load(path2)
            print("Mask Processing")
            mask_img = image_preprocessing(mask_img)
        
            logging.info("Generator is prepped")
            
            for img_slice, mask_slice in zip(image,mask_img):
                img_slice = np.reshape(img_slice,(1,512,512,1))
                mask_slice = np.reshape(mask_slice,(1,512,512,1))
                
                yield img_slice, mask_slice
            
    elif include_mask == False:
        for path in dict_obj["image"]:
            logging.info("loading {} {} into generator".format("image",os.path.basename(path)))
            image, header  = load(path)
            image = image_preprocessing(image)
            logging.info("Generator is prepped")
            
            for slice in image:
                slice = np.reshape(slice,(512,512,1))
                yield slice
    else:
        raise TypeError("Problem with inputs.")
        logging.error("Unable to load image into generator")
```

`tr_data = image_generator(tr_dict,mask = True)
`

```
''' Creating NN'''


if os.path.isdir(Model_path+model_vers)==True:
    logging.info("Loading Network")
    model=tfk.models.load_model("Model_path+model_vers")
    
else:
    logging.info("Creating Network")
    model= tfk.Sequential()
    model.add(layers.Conv2D(32, kernel_size=(3, 3), activation='relu', kernel_initializer='he_uniform', input_shape=input_shape, data_format="channels_last", padding='SAME'))
    model.add(layers.MaxPooling2D(pool_size=(3, 3)))
    model.add(layers.BatchNormalization(center=True, scale=True))
    model.add(layers.Dropout(0.5))
    model.add(layers.Conv2D(16, kernel_size=(3, 3), activation='relu', kernel_initializer='he_uniform', padding ='SAME'))
    model.add(layers.MaxPooling2D(pool_size=(3, 3)))
    model.add(layers.BatchNormalization(center=True, scale=True))
    model.add(layers.Dropout(0.5))
    model.add(layers.Flatten())
    model.add(layers.Dense(100, activation='relu', kernel_initializer='he_uniform'))
    model.add(layers.Dense(50, activation='relu', kernel_initializer='he_uniform'))
    model.add(layers.Dense(10, activation='relu'))


'''Hyper Parameters'''
logging.info("Adding Hyperparameters")

optimizer=tfk.optimizers.Adadelta() #'Adam' 
loss= "categorical_crossentropy" #'sparse_categorical_crossentropy'
metrics = ['accuracy']
model.compile(optimizer = optimizer, loss= loss, metrics= metrics )
```

When I run:

```
"""Training NN"""
logging.info("Training Neural Network")
tf.autograph.experimental.do_not_convert(func=model.fit(tr_data,epochs = 10,verbose=10))
#model.save("Model_path+model_vers")
```
My error is:
```
Image processing
Mask Processing
Epoch 1/10
WARNING:tensorflow:AutoGraph could not transform <function Model.make_train_function.<locals>.train_function at 0x000002785034A9D8> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 4, expecting 3
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <function Model.make_train_function.<locals>.train_function at 0x000002785034A9D8> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 4, expecting 3
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <function Model.make_train_function.<locals>.train_function at 0x000002785034A9D8> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 4, expecting 3
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
```

Traceback attached in .txt file
Model Summary in .txt file.
[Tensorflow Traceback.txt](https://github.com/tensorflow/tensorflow/files/4967995/Tensorflow.Traceback.txt)
[Model Summary.txt](https://github.com/tensorflow/tensorflow/files/4967996/Model.Summary.txt)

The 2 exceptions can be found in the tracebook, but summarized here:
```

AssertionError: Bad argument number for Name: 4, expecting 3

During handling of the above exception, another exception occurred:

ValueError: Shapes (None, None, None, None) and (None, 10) are incompatible

```

**Have tried remedy without any change:**
- reisntall tensorflow and keras, as well as gast. 
- restarted computer
- altering input shapes
- rewrote by hand in a new file, no change.
Edit:
- altered size of NN
-altered data shape

**Comment by ravikyram** [comment]
@zhilothebest 

I tried in colab with TF 2.2 and i am seeing the error (`NameError: name 'tr_dict' is not defined`).
Request you to provide colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by zhilothebest** [comment]
My code can be found at this repo: I have made a separate branch called tensorflow-debug that has unnecessary code commented out.  https://github.com/zhilothebest/Coronary_Calcium

A sample of the dataset is uploaded to here: https://drive.google.com/drive/folders/1K4zL49pnDQsQDagCgHZko8jbtN-UNfX0?usp=sharing

Let me know if there is anything else I can do to help!

**Comment by zhilothebest** [comment]
During some debugging, I found this might be related to the fact my computer cant load cudnn, and thus cant find the convolution algorithm. All the versions seem to match up to work properly, and my CUDA paths are appropriate. Ive tried limiting GPU memory space, and limiting to CPU only, but cudnn I still not being readable by tensorflow. Any thoughts on this?

**Comment by ravikyram** [comment]
@zhilothebest 

Can you go through the [link ](https://stackoverflow.com/questions/41402409/tensorflow-doesnt-seem-to-see-my-gpu), [link2](https://stackoverflow.com/questions/43658989/tensorflow-not-loading-cudnn) and see if it helps you.Thanks!

**Comment by zhilothebest** [comment]
Here is my `nvidia-smi` as well:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 442.19       Driver Version: 442.19       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 165... WDDM  | 00000000:02:00.0 Off |                  N/A |
| N/A   40C    P8     3W /  N/A |   4076MiB /  4096MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     10124      C   ...cal\Programs\Python\Python37\python.exe N/A      |
|    0     12672      C   ...cal\Programs\Python\Python37\python.exe N/A      |


I currently have two Jupyter Kernels open.

**Comment by ymodak** [comment]
Your gpu is cuda enabled. See https://forums.developer.nvidia.com/t/cuda-enabled-geforce-1650/81010
Did you try limiting gpu memory growth after closing all the python sessions, terminating jupyter notebooks, exiting the interpreter/rebooting the system?
```python
import tensorflow as tf
gpus = tf.config.experimental.list_physical_devices('GPU')
 tf.config.experimental.set_visible_devices(gpus[0], 'GPU')
# Your code here
# . . .
```

**Comment by zhilothebest** [comment]
Hi @ymodak, I was running my code in the Jupyter notebook session, but everything else was closed. Only the cmd prompt window and the Jupyter notebook with the one kernel was open. I have reset kernels. Restarted computer. All of that! 

I also tried limiting GPU memory growth as well, no luck.

**Comment by sanjoy** [comment]
Hi @zhilothebest can you please attach the logs from your TF run?

**Comment by zhilothebest** [comment]
The traceback is posted above in the first post. Sadly, I don't quite know how to export any logging that tensorflow may have internally into a file?

**Comment by zhilothebest** [comment]
@sanjoy any update?

**Comment by sanjoy** [comment]
> Sadly, I don't quite know how to export any logging

By "logging" I meant everything TensorFlow prints to stderr and stdout during execution.  That output might have a hint on what's going wrong with cuDNN.

**Comment by zhilothebest** [comment]
Hi, It appears my last comment didnt post; but everything that was printed in stderr and stdout is above.

**Comment by sushreebarsa** [comment]
@zhilothebest Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!
