### ISSUE TITLE
Git Pull doesn't work in building from source for GPU

### ISSUE THREAD

**Issue by RayLucchesi** [tensorflow/tensorflow#41683]
**System information**
Ubuntu 20.04
TensorFlow installed from "docker pull tensorflow/tensorflow:devel-gpu"
- TensorFlow version: 2.4?
- Python version: 3.8.2 (installed on system but what's running in the container I don't know
- Not sure but believe it's Pip
- Bazel version (if compiling from source): Don't know
- GCC/Compiler version (if compiling from source): don't know
- CUDA/cuDNN version: 10.1
- GPU model and memory: 3  GeForce GTX 1070s with 8GB each

**Describe the problem**
In following the instructions on the bottom of the page for compiling TensorFlow from source for GPU. I ran across a problem with the git pull. when I run the docker container I end up in the /tensorflow directory. But there's no .git file there. But there is one in the /tensorflow_src directory. Either you need to change the docker run command to end up in that directory or I suggest you add a "cd ../tensorflow_src" command before the "git pull" command. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
docker pull tensorflow/tensorflow:devel-gpu
docker run --gpus all -it -w /tensorflow -v $PWD:/mnt -e HOST_PERMS="$(id -u):$(id -g)" \
    tensorflow/tensorflow:devel-gpu bash
git pull  # within the container, download the latest source code

**Any other info / logs**
N/A

**Comment by sachinprasadhs** [comment]
Could you please try with the latest version, if you are using docker for GPU, you can follow this link https://www.tensorflow.org/install/docker#gpu_support. 
For building from source for GPU on Linux system, you can follow this link https://www.tensorflow.org/install/source#gpu_support_3 and perform the git pull within the container.
