### ISSUE TITLE
image_dataset_from_directory(label_mode=None) dosen't work.

### ISSUE THREAD

**Issue by QLaHPD** [tensorflow/tensorflow#41685]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow version (use command below): tf-nightly-gpu 
v1.12.1-37350-g537f3ec52f 
2.4.0-dev20200723
- Python version: 3.8
- GPU model and memory: Nvidia GTX 1080Ti 11GB

**Describe the current behavior**
Using the code provided below results in:

> Found 0 files belonging to 0 classes.
> Using 0 files for training.

And at the end of the output:
> TypeError: Input 'filename' of 'ReadFile' Op has type float32 that does not match expected type of string.

**Describe the expected behavior**
As described in the documentation, expected to return a tensor of shape=[n,h,w,c].

> _If label_mode is None, it yields float32 tensors of shape (batch_size, image_size[0], image_size[1], num_channels), encoding images (see below for rules regarding num_channels)._

**Standalone code to reproduce the issue**
```
from tensorflow.keras.preprocessing import image_dataset_from_directory
train_data = image_dataset_from_directory(directory='/folder/with/images', label_mode=None)
```

**Other info / logs** Include any logs or source code that would be helpful to
[Traceback.txt](https://github.com/tensorflow/tensorflow/files/4969755/Traceback.txt)

**Comment by aymenfurter** [comment]
Ran into the same issues. I assume you have your files located in '/folder/with/images' - Does it behave the same if you put them in '/folder/with/images/foo'?

**Comment by QLaHPD** [comment]
No, it dosen't, but with that it returns: x = tensor of shape=[n,h,w,c]; y = label [foo].
And I don't want this, I want just the 'x'.

**Comment by amahendrakar** [comment]
@QLaHPD,
I was able to run the code without any issues and got the expected output for `x`. Please check [this gist](https://colab.research.google.com/gist/amahendrakar/9452f651f1c59bac66570941d6659a59/41685.ipynb) for reference. 

Also, please take a look at the [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image_dataset_from_directory) and make sure the images are in the right directory structure. Thanks!

**Comment by QLaHPD** [comment]
> EDIT: https://colab.research.google.com/drive/1NSnMNnrFrpaB4zQsdm7AQPzThRMpRBxi?usp=sharing

Interesting, here it works like this, but when I use model.fit(train_data, train_data), returns:

> ValueError: `y` argument is not supported when using dataset as input.

So I'm assuming its another type of error. If you can help me more, I'd be grateful, but thanks for helping out.

**Comment by amahendrakar** [comment]
> Interesting, here it works like this, but when I use model.fit(train_data, train_data), returns:
> 
> > ValueError: `y` argument is not supported when using dataset as input.

@QLaHPD,
In order to reproduce this error could you please provide the complete code and the dataset you are using, so that we can look into it. Thanks!
