### ISSUE TITLE
Not able to create libtensorflow-lite.a from build_ios_universal_lib.sh

### ISSUE THREAD

**Issue by SimonFernandes7** [tensorflow/tensorflow#41696]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac 10.15.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NO
- TensorFlow installed from (source or binary): 
- TensorFlow version (use command below): 2.1.1
- Python version: Python 2.7.16 and Python 3.7.3
- Bazel version (if compiling from source): bazel 3.4.1-homebrew
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
I was able to create libtensorflow-lite.a on my mac for Tensorflow version 1.8.0 before.
Now, I am trying to do the same for version 2.1.0 but it's giving the following error 

```
clang: error: no such file or directory: 'i386'
clang: warning: no such sysroot directory: '-arch' [-Wmissing-sysroot]
clang: error: no such file or directory: 'i386'
clang: warning: no such sysroot directory: '-arch' [-Wmissing-sysroot]
make: *** [/Users/myMac/TFLite_2_1/tensorflow/lite/tools/make/gen/ios_i386/obj/tensorflow/lite/core/api/flatbuffer_conversions.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [/Users/myMac/TFLite_2_1/tensorflow/lite/tools/make/gen/ios_i386/obj/tensorflow/lite/allocation.o] Error 1
clang: clang: error: no such file or directory: 'i386'
error: no such file or directory: 'i386'
clang: warning: no such sysroot directory: '-arch' [-Wmissing-sysroot]
clang: warning: no such sysroot directory: '-arch' [-Wmissing-sysroot]
clang: error: no such file or directory: 'i386'
clang: warning: no such sysroot directory: '-arch' [-Wmissing-sysroot]
make: *** [/Users/myMac/TFLite_2_1/tensorflow/lite/tools/make/gen/ios_i386/obj/tensorflow/lite/arena_planner.o] Error 1
make: *** [/Users/myMac/TFLite_2_1/tensorflow/lite/tools/make/gen/ios_i386/obj/tensorflow/lite/core/api/error_reporter.o] Error 1
clang: error: no such file or directory: 'i386'
clang: warning: no such sysroot directory: '-arch' [-Wmissing-sysroot]
clang: error: no such file or directory: 'i386'
clang: warning: no such sysroot directory: '-arch' [-Wmissing-sysroot]
make: *** [/Users/myMac/TFLite_2_1/tensorflow/lite/tools/make/gen/ios_i386/obj/tensorflow/lite/core/api/op_resolver.o] Error 1
clang: error: no such file or directory: 'i386'
clang: warning: no such sysroot directory: '-arch' [-Wmissing-sysroot]
make: *** [/Users/myMac/TFLite_2_1/tensorflow/lite/tools/make/gen/ios_i386/obj/tensorflow/lite/c/c_api_internal.o] Error 1
make: *** [/Users/myMac/TFLite_2_1/tensorflow/lite/tools/make/gen/ios_i386/obj/tensorflow/lite/core/api/tensor_utils.o] Error 1
make: *** [/Users/myMac/TFLite_2_1/tensorflow/lite/tools/make/gen/ios_i386/obj/tensorflow/lite/core/subgraph.o] Error 1
```

**Standalone code to reproduce the issue**
1. Have downloaded the code from https://github.com/tensorflow/tensorflow/tree/r2.1
2. First, run download_dependencies.sh script and then build_ios_universal_lib.sh.

**Facing the same issue in ver 2.2. I have also tried for ver 2.3 but it showed warning "This build script is deprecated..."**

**Comment by Saduf2019** [comment]
@SimonFernandes7 
Could you please refer to [this link](https://stackoverflow.com/questions/28420982/clang-error-no-such-file-or-directory-project-sdwebimage-3-7-1-build-releas) and let us know if it helps.

**Comment by SimonFernandes7** [comment]
@Saduf2019 Thanks, but the error that I'm facing is while creating the libtensorflow-lite.a file and not while using that file in Xcode. The reference link that you have provided is an issue while accessing the .a file in Xcode.

**Comment by SimonFernandes7** [comment]
Thanks, for your reference. I was able to solve the issue by running the below command on terminal.
`sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer/`

As it was not able to locate SDK "iphonesimulator"
