### ISSUE TITLE
SPLIT_V for tensorflow lite micro

### ISSUE THREAD

**Issue by Abhipray** [tensorflow/tensorflow#41690]
Currently SPLIT_V is not supported in tensorflow lite micro as a builtin op code. My model uses SPLIT_V. I need help with either preventing tflite conversion from generating SPLIT_V or how can I add it as a builtin op?

**Comment by Saduf2019** [comment]
@Abhipray 
Can you please share simple stand alone code in support of the issue faced with the error faced or if possible share colab gist with error and tf version.

**Comment by Abhipray** [comment]
@Saduf2019  Here is a colab that has a model that generates a SPLIT_V op with tflite converter. https://colab.research.google.com/drive/1XzrvDvxOVizrY5AT23hokcJHdgUcRd4r?usp=sharing

It generates a tflite file that you can download and view with netron https://github.com/lutzroeder/netron. You will see that the model uses SPLIT_V op which is currently not supported in tf lite micro.

**Comment by jvishnuvardhan** [comment]
@Abhipray I am noticing an error in the model building code itself. Can you please check [this gist](https://colab.research.google.com/gist/jvishnuvardhan/a467b8730595ecb44e45fa826550c093/missing_split_v.ipynb) and share updated code to reproduce your issue? Thanks!

**Comment by Abhipray** [comment]
@jvishnuvardhan Sorry about that. It's fixed now: https://colab.research.google.com/drive/1XzrvDvxOVizrY5AT23hokcJHdgUcRd4r?usp=sharing

**Comment by renjie-liu** [comment]
Hi Pete,

Do you mind taking a look?

Thanks!

**Comment by Abhipray** [comment]
Pete, just to add to this, I was able to create my own SPLIT_V op and add to the resolver easily before May. Since then, changes have been made to how ops are added and read from the flatbuffer and I can't figure out the necessary steps. What would be super helpful to me immediately is if you can share a link to an example PR that adds a built-in op that I can emulate. 
Thanks!
