### ISSUE TITLE
Explanation of the constants in the tutorials for TensorFlow

### ISSUE THREAD

**Issue by shyamalschandra** [tensorflow/tensorflow#417]
Hi,

Would you be able to provide more explanation in the comments for the code (or at least the papers that are relevant to the underlying theory) for the TensorFlow tutorials?

Thanks!

Shyamal

**Comment by vrv** [comment]
I think the udacity course materials are the right place to put these types of docs, since they're more geared towards teaching the theory behind the practice.

**Comment by shyamalschandra** [comment]
@vrv The Udacity course is nonlinear and doesn't have a rich, drill-down vocabulary that is required for pedogogical purposes.  Thus, it doesn't, by itself, suffice for the purposes of providing documentation for Tensorflow.  The theory that is presented is half-baked and too abstract to convert to code from some high-level graphics.
