### ISSUE TITLE
tf.ones produces zeros on GPU in an unclear scenario

### ISSUE THREAD

**Issue by mathieuorhan** [tensorflow/tensorflow#41704]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2
- Python version: 3.7.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1, 7
- GPU model and memory: 2080Ti 11GB + 1070 8GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I was using my GPUs for another task, with near full memory taken. 
When using aside ipython, `tf.ones(())` (with any shape/dtype, except tf.int32 working as intented) produced 0s (like tf.zeros). I repeated this multiple times, in multiple instance of ipython. When setting running on CPU, tf.ones correctly produced 1s. After clearing the GPU memory, the issue disappeared, and now I'm unable to reproduce (for instance by filling my GPUs memories).

**Describe the expected behavior**
Output 1s, or an error

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
Cannot provide one, I'm not able to reproduce again

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@mathieuorhan 
Can you please share simple indented stand alone code such that we could replicate the issue faced or if possible share a colab gist with the issue reported.

**Comment by mathieuorhan** [comment]
@Saduf2019 
I could not reproduce the issue

**Comment by Saduf2019** [comment]
@mathieuorhan 
In that case we will have to move this issue to closed status, please feel free to reopen or create new issue in case you find a stand alone code to replicate.
