### ISSUE TITLE
Linking cross compiled  libtensorlowlite.so for aarch64 causes reference errors: undefined reference to `fcntl64@GLIBC_2.28'

### ISSUE THREAD

**Issue by aselva-eb** [tensorflow/tensorflow#41709]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18
- TensorFlow installed from (source or binary): pip
- Python version: 3.7
- Installed using virtualenv? pip? conda?:
- GCC/Compiler version (if compiling from source):  aarch64-linux-gnu-g++

**Describe the problem**

I am trying to cross compile a binary to make use of a cross compiled libtensorflowlite.so library. However upon compilation I get the error
```
/home/aarch64/libtensorflowlite.so: undefined reference to `fcntl64@GLIBC_2.28'
```

I've followed the exact same steps using the native compiler (x86_64) and had no issues linking. 

Here is how I build from source:
```
bazel build --config=elinux_aarch64 --config=monolithic --cxxopt=--std=c++14 --define=with_select_tf_ops=true -c opt //tensorflow/lite:libtensorflowlite.so
```

Once I have my shared library, I link it to my inference code via:
```
aarch64-linux-gnu-g++ -std=c++11 hello_world.cpp -I/home/tensorflow/ -I/home/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/include   -L/home/aarch64 -ltensorflowlite -lm -lpthread
```

However the above error occurs.
I'm wondering if its due to the steps in which I'm building from source. Specifically the `--config=elinux_aarch64` flag that I add for this cross-compilation case, and didn't have when I compiled natively. Otherwise is there a way to build that missing symbol into the library statically in compilation? Is this a tensorflow build issue? 

FYI: my system itself is running `Ubuntu GLIBC 2.27-3ubuntu1.2`.

**Comment by terryheo** [comment]
This is the toolchain of elinux_aarch64
https://github.com/tensorflow/tensorflow/tree/master/third_party/toolchains/embedded/arm-linux
You'd better update glibc of the target system to 2.28 or higher.
