### ISSUE TITLE
Tensorflow C abruptly hangs at absl::synchronization_internal::Waiter::Wait(absl::synchronization_internal::KernelTimeout)

### ISSUE THREAD

**Issue by saran001** [tensorflow/tensorflow#41703]
Hi All,

I'm using Tensorflow 1.15 C libraries for running Parallel Image Processing Computations in my cluster. The cluster consists of 8 worker nodes, each running 40 computation threads, where each of them makes use of tensorflow c libraries to process the incoming data.

All works fine, when suddenly the entire cluster gets abruptly hanged. On getting the GDB from my nodes, I'm seeing additional threads (apart from my pre-configured setup of 40 per node), which I'm assuming to be created by Tensorflow. The GDB shows that the threads have been abruptly blocked at **absl::synchronization_internal::Waiter::Wait(absl::synchronization_internal::KernelTimeout)** 

On viewing the system-level logs, I also see one of the nodes having kernel bug log stating

[598428.945633] BUG: kernel NULL pointer dereference, address: 
0000000000000038
  ...
  [598428.945749] Workqueue: cifsoplockd cifs_oplock_break [cifs]
  [598428.945793] RIP: 0010:smb2_push_mandatory_locks+0xd6/0x5a0 [cifs]
  ...
  [598428.945834] Call Trace:
  [598428.945870]  ? cifs_revalidate_mapping+0x45/0x90 [cifs]
  [598428.945901]  cifs_oplock_break+0x13d/0x450 [cifs]
  [598428.945909]  process_one_work+0x1db/0x380
  [598428.945914]  worker_thread+0x4d/0x400
  [598428.945921]  kthread+0x104/0x140
  [598428.945925]  ? process_one_work+0x380/0x380
  [598428.945931]  ? kthread_park+0x80/0x80
  [598428.945937]  ret_from_fork+0x35/0x40

After restarting the cluster, everything goes back to the way it was. But still, this issue keeps on occuring at random.
Can someone help me to understand and resolve this issue? Thanks.

**System information**

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): SLES 12
- TensorFlow installed from (source or binary): Downloaded C Binaries from official website
- TensorFlow version (use command below): 1.15
- GCC/Compiler version (if compiling from source): 6.4.0

**Logs** 
Sample GDB Thread Call Stack

Line 222195: [23] Thread 98 (Thread 0x7ef1b0fb1700 (LWP 36711)):
	Line 222196: [23] #0  0x00007efc2bc9a9f9 in syscall () from /lib64/libc.so.6
	Line 222197: [23] No symbol table info available.
	Line 222198: [23] #1  0x00007efc365aadc2 in absl::synchronization_internal::Waiter::Wait(absl::synchronization_internal::KernelTimeout) () from /usr/local/lib/libtensorflow.so
	Line 222203: [24]         __local = {<std::__shared_ptr<std::thread::_Impl_base, (__gnu_cxx::_Lock_policy)2>> = {_M_ptr = <optimized out>, _M_refcount = {_M_pi = 0x7f46400a7a50}}, <No data fields>}[23] No symbol table info available.
	Line 222204: [23] #2  0x00007efc365aad02 in AbslInternalPerThreadSemWait () from /usr/local/lib/libtensorflow.so
	Line 222209: [23] No symbol table info available.
	Line 222210: [23] #3  0x00007efc365ac2fd in absl::Mutex::Block(absl::base_internal::PerThreadSynch*) () from /usr/local/lib/libtensorflow.so
	Line 222211: [23] No symbol table info available.
	Line 222212: [23] #4  0x00007efc365ad1ed in absl::Mutex::AwaitCommon(absl::Condition const&, absl::synchronization_internal::KernelTimeout) () from /usr/local/lib/libtensorflow.so
	Line 222219: [23] No symbol table info available.
	Line 222220: [23] #5  0x00007efc365ad26d in absl::Mutex::Await(absl::Condition const&) () from /usr/local/lib/libtensorflow.so
	Line 222223: [23] No symbol table info available.
	Line 222224: [23] #6  0x00007efc32120f44 in stream_executor::host::HostStream::WorkLoop() () from /usr/local/lib/libtensorflow.so
	Line 222240: [23] No symbol table info available.
	Line 222241: [23] #7  0x00007efc2c75a810 in std::execute_native_thread_routine_compat (__p=<optimized out>) at ../../../.././libstdc++-v3/src/c++11/thread.cc:110
	Line 222498: [23]         __t = <optimized out>
	Line 222499: [23]         __local = {<std::__shared_ptr<std::thread::_Impl_base, (__gnu_cxx::_Lock_policy)2>> = {_M_ptr = <optimized out>, _M_refcount = {_M_pi = 0x7ef24c0f3270}}, <No data fields>}[23] 
	Line 222499: [23]         __local = {<std::__shared_ptr<std::thread::_Impl_base, (__gnu_cxx::_Lock_policy)2>> = {_M_ptr = <optimized out>, _M_refcount = {_M_pi = 0x7ef24c0f3270}}, <No data fields>}[23] 
	Line 222500: [23] #8  0x00007efc2d05c74a in start_thread () from /lib64/libpthread.so.0
	Line 222501: [23] No symbol table info available.
	Line 222502: [23] #9  0x00007efc2bc9ef6d in clone () from /lib64/libc.so.6

**Comment by alextp** [comment]
TF has a bunch of internal thread pools. Those thread pools sit on a condition variable while waiting for work to be available, which is probably what you're seeing here.

To be able to debug this we need to find the one or two threads which are not idling on the threadpool (you can recognize them for having more stack frames) and find out what they are blocked on. Building TF with debug symbols or with thread sanitize will help a lot in diagnosing this.

Alternatively you can give us a reproducing example. What is the smallest program you can write that hits this occasional deadlock?
