### ISSUE TITLE
Conv1DTranspose Dilation support - Might be a bug, IDK.

### ISSUE THREAD

**Issue by EnderWiggin14** [tensorflow/tensorflow#41712]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
[https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv1DTranspose]()

## Description of issue (what needs changing):
Conv1DTranspose - Dilation - Does not inform uses that dilation doesn't work for any value  of `Dilation>1` because it isn't implemented yet. 
### Clear description
Currently documentation says:
_"an integer, specifying the dilation rate to use for dilated convolution. Currently, specifying a dilation_rate value != 1 is incompatible with specifying a stride value != 1."_

This may not be implemented yet in the newest of nightly build, but with my tf-nightly==2.5.0dev20200629 build this didn't work. I fear updating to new nightly builds in case in breaks my research code which relies on nightly builds until Conv1DTranspose is released in a supported build.
```
InvalidArgumentError:  Current libxsmm and customized CPU implementations do not yet support dilation rates larger than 1.
	 [[node test1_AE/decoder/conv1d_transpose/conv1d_transpose (defined at D:\Users\[username]\Desktop\libs_python\nn4n_autoencoder4.py:120) ]] [Op:__inference_train_function_2185]

Function call stack:
train_function
```
This is with stride == 1.
### Correct links

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/convolutional.py

### Parameters defined

Yes, setting my dilation to 1 gets rid of the issue.

### Returns defined

Not necessary. (I'm not sure if you are asking if I have define returns in my code or if my code returns a defined value, or if the documentation claims to return something)

### Raises listed and defined
```
InvalidArgumentError:  Current libxsmm and customized CPU implementations do not yet support dilation rates larger than 1.
	 [[node test1_AE/decoder/conv1d_transpose/conv1d_transpose (defined at D:\Users\[username]\Desktop\libs_python\nn4n_autoencoder4.py:120) ]] [Op:__inference_train_function_2185]

Function call stack:
train_function
```

### Usage example

Nightly build, so no.

### Request visuals, if applicable
 No.

### Submit a pull request?
I will not be doing so.

### Test Code

Note 1: This is built with tf-nightly==2.5.0dev20200626 which was removed from the PyPi archive for unknown reasons.

Note 2: model.fit must be called for the error to occur. Simpy constructing and compiling the network was not enough to reproduce the error.

```
import tensorflow as tf
import tensorflow.keras as krs
import numpy as np

train_data = np.random.uniform(-1,1,(20,20))

inputs = krs.Input((20,1))

x = inputs

x = krs.layers.Conv1D(1,3,strides = 1,padding='same',dilation_rate=2,activation='relu')(x)
x = krs.layers.Flatten()(x)
x = krs.layers.Dense(10,activation='relu')(x)
x = krs.layers.Dense(2,activation='relu')(x)
x = krs.layers.Dense(10,activation='relu')(x)
x = krs.layers.Dense(20,activation='relu')(x)
x = krs.layers.Reshape(target_shape=(20,1))(x)
x = krs.layers.Conv1DTranspose(1,3,strides=1,dilation_rate=2,padding='same',activation='relu',output_padding=0)(x)
output = krs.layers.Flatten()(x)

model = krs.Model(inputs,output,name='test')

model.compile(optimizer='adam',loss='MSE')

model.summary()

model.fit(train_data,train_data)
```

**Comment by Saduf2019** [comment]
@EnderWiggin14 
Could you please update the issue template, we do not find any details.
Please provide with simple indented stand alone code such that we can replicate the issue faced or if possible please provide a colab gist with error faced.

**Comment by EnderWiggin14** [comment]
Well, this was originally labeled as a Documentation issue so that "Details" section wasn't part of the standard template. I will try to get a short example added to the issue.

**Comment by Saduf2019** [comment]
I ran the code on nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/c7953f7c83b7c403adadec092931076f/untitled284.ipynb) and on [2.3.0rc0 the dilation support error is seen as reported](https://colab.research.google.com/gist/Saduf2019/79a85b1424a878f63d7fa31b369c5f68/untitled296.ipynb).

**Comment by EnderWiggin14** [comment]
It is very odd that the TF nightly build used in the GIST (tf-nightly==2.4.0dev20200724) doesn't have Conv1DTranspose() support. I have another system that's running a slightly older tf-nightly build (tf-nightly==2.3.0dev20200622) which was still available 2-3 weeks ago but appears to now be deleted. This is one of the two builds that I actively use as well, and it supports the Conv1DTranspose() method, but also lacks the dilation support.

**Comment by ymodak** [comment]
I can repro this with latest nightly build. See [gist](https://colab.research.google.com/gist/ymodak/a230402addcdda55e1cb87f7c1447ab7/untitled284.ipynb)
When `strides = 1` and `dilation_rate = 1` in the `tf.keras.layers.Conv1DTranspose` layer the code executes successfully.
However for dilation_rate > 1 it fails.
Perhaps the documentation can be updated for the `dilation_rate` parameter. Thanks!

**Comment by ymodak** [comment]
Docs are updated now.  See commit [75801da](https://github.com/tensorflow/tensorflow/commit/75801da4cd321aabbf79e78da1e5de1a10ba4c2a#diff-aa6c341a4b212afc57b49be73e689dc2)
Thanks!

**Comment by EnderWiggin14** [comment]
Thanks! Is there any news as to when the dilation_rate > 1 will be supported?
