### ISSUE TITLE
`--config=c++17` option is incompatible with GCC build

### ISSUE THREAD

**Issue by planetmarshall** [tensorflow/tensorflow#41710]
**System information**
- OS Platform and Distribution **Ubuntu Linux 18.04 LTS**
- TensorFlow installed from (source or binary): **source**
- TensorFlow version: **master** (`e2204b27`)
- Python version: **3.8.3**
- Bazel version (if compiling from source): **3.1.0**
- GCC/Compiler version (if compiling from source): **7.5.0-3ubuntu1~18.04**

**Describe the problem**

The `--config=c++17` build configuration option adds compiler flags which are incompatible with GCC.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
./configure (Accept defaults)
```

```
bazel build --config=c++17 //tensorflow:tensorflow_cc
```

**Any other info / logs**

```
ERROR: /home/andrew/.cache/bazel/_bazel_andrew/05f0c1fc0fd5d93d6530b840ab375f68/external/com_github_grpc_grpc/BUILD:487:1: C++ compilation of rule '@com_github_grpc_grpc//:gpr_base' failed (Exit 1)
gcc: error: unrecognized command line option '-stdlib=libc++'
```

The `c++17` configuration option adds the `-stdlib=libc++` flag to the C++ compiler, but this is a Clang flag, not GCC.

**Comment by ravikyram** [comment]
@planetmarshall 

Can you please try with C++11 and C++14 and see if the error still persists.Please, refer #39617, #23561 and see if it helps you.Thanks!

**Comment by planetmarshall** [comment]
Thanks for the response. I can build with C++11 and C++14. The issue is the incompatible compiler flag - I note @golden0080 made the same observation in #23561

**Comment by ravikyram** [comment]
@planetmarshall 

Please, close this thread if your issue was resolved.Thanks!

**Comment by mihaimaruseac** [comment]
Can you send a PR to remove the `libc++` setup? We now have a different config option for that.

**Comment by planetmarshall** [comment]
> @planetmarshall
> 
> Please, close this thread if your issue was resolved.Thanks!

Well, it's not really resolved. The bazel file contains a configuration option that can't possibly work. Perhaps it should be removed?

**Comment by mihaimaruseac** [comment]
That's why I suggested sending a PR to remove the flag.

**Comment by mihaimaruseac** [comment]
Made #42158 to try removing the flag. If that works, we can use `--config=c++17_gcc` to compile as if `--config=c++17` was passed in but without linking `libc++`. If you want, can you patch in the PR and test too?

Unfortunately, we might not be able to change the existing config as there might be people already using the old config.

**Comment by mihaimaruseac** [comment]
#42158 landed, I think we can close this now.
