### ISSUE TITLE
run tht tfmot.quantization.keras.quantize_model(model) and raise the error "`model` must be a built model. been built yet" while model.built is True

### ISSUE THREAD

**Issue by ChenHaoHere** [tensorflow/tensorflow#41728]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10
- TensorFlow version (use command below):2.1.0
- Python version:3.7.7

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I write my own `GRUCell` and create a model by `keras.RNN()`.  Here's my model
```python
class GRUCell(keras.layers.Layer):
    def __init__(self, units, **kwargs):
        self.units = units
        self.state_size = tf.TensorShape([units])
        self.output_size = tf.TensorShape([units])
        super(GRUCell, self).__init__(**kwargs)

    def build(self, input_shape):
        self.dim = input_shape[-1]

        self.w_r = self.add_weight(shape=[self.dim+self.units, self.units], initializer='uniform', name='reset_gate', trainable=True)
        self.b_r = self.add_weight(shape=[self.units], initializer='zeros', name='reset gate bias', trainable=True)

        self.w_z = self.add_weight(shape=[self.dim+self.units, self.units], initializer='uniform', name='update_gate', trainable=True)
        self.b_z = self.add_weight(shape=[self.units], initializer='zeros', name='update gate bias', trainable=True) 

        self.w_n = self.add_weight(shape=[self.dim+self.units, self.units], initializer='uniform', name='intetim', trainable=True)
        self.b_n = self.add_weight(shape=[self.units], initializer='zeros', name='interim gate bias', trainable=True)

        self.build = True


    def call(self, inputs, states):
        
        states, = states
        
        r = tf.nn.sigmoid(inputs @ self.w_r[:self.dim] + states @ self.w_r[self.dim:] + self.b_r)
        z = tf.nn.sigmoid(inputs @ self.w_z[:self.dim] + states @ self.w_z[self.dim:] + self.b_z)
        n = tf.nn.tanh(inputs @ self.w_n[:self.dim] + (states * r) @ self.w_n[self.dim:] + self.b_n)
        
        output = (1 - z) * states + z * n

        return output, output

    def get_config(self):
        return {"units": self.units}

def create_model(units):
    model = keras.Sequential([
            keras.layers.RNN(GRUCell(units)),
            keras.layers.Dense(1)
            ])
    model.compile(optimizer=keras.optimizers.RMSprop(),
                loss='mae', metrics=['mse'])

    return model
```
This model works well.
![](https://raw.githubusercontent.com/ChenHaoHere/PicGo/master/20200725222620.png)
But when I'd like to use the snippet from (https://www.tensorflow.org/model_optimization/guide/quantization/training_example), the error **ValueError: `model` must be a built model. been built yet. Please call `model.build(input_shape)` before quantizing your model.** was raised. But `model.built` is True.

![](https://raw.githubusercontent.com/ChenHaoHere/PicGo/master/20200725223938.png)

**Comment by Saduf2019** [comment]
@ChenHaoHere 
I ran the code shared but face a different issue, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/8ef662ce3db69aecb3a4c61bba6ccf3e/untitled288.ipynb). Can you share complete stand alone code such that we can replicate error faced or if possible share a colab gist with the error.

With respect to error shared, please share error log in text format, and refer to similar issue [link](https://stackoverflow.com/questions/55908188/this-model-has-not-yet-been-built-error-on-model-summary).
