### ISSUE TITLE
Tensorflow using Intel GPU instead of NVIDIA GPU

### ISSUE THREAD

**Issue by tamimmirza** [tensorflow/tensorflow#41727]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home 64-bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.2.0
- Python version: 3.8.3
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.1/7.6
- GPU model and memory: NVIDIA GTX 1050 (4 GB) 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
TensorFlow, by default is using GPU 0, which on my PC is my built-in Intel GPU while I have a dedicated NVIDIA GPU and have CUDA installed yet TF is using Intel.

**Describe the expected behavior**
TensorFlow should display current device to be NVIDIA GPU

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

![Annotation 2020-07-25 190353](https://user-images.githubusercontent.com/35456031/88458751-b8983880-cea9-11ea-8237-44bcc66eef19.png)
![Annotation 2020-07-25 190430](https://user-images.githubusercontent.com/35456031/88458754-bafa9280-cea9-11ea-9375-de1ba6feec2b.png)

**Comment by ravikyram** [comment]
@tamimmirza 

Can you list all gpus by following the below link and then manually place the gpu you need.
https://www.tensorflow.org/guide/gpu#setup

Thanks!

**Comment by tamimmirza** [comment]
I did that before and it shows me that it has detected one GPU despite me having two as you can see in the task manager windows above:

![Annotation 2020-07-27 164537](https://user-images.githubusercontent.com/35456031/88538614-18691d80-d029-11ea-8672-5543a5ae77ee.png)

Which is weird considering I have installed up-to-date drivers and CUDA Toolkit 10.1 Update 2 (along with cuDNN 7.6)

![Annotation 2020-07-27 164719](https://user-images.githubusercontent.com/35456031/88538664-2e76de00-d029-11ea-9df4-672b20dd33d9.png)

Here is the verification that CUDA is installed via Visual Studio 2019 IDE

![Annotation 2020-07-27 165055](https://user-images.githubusercontent.com/35456031/88538806-6bdb6b80-d029-11ea-89e8-8fca793b850a.png)

**Comment by ravikyram** [comment]
@tamimmirza 

Please try install TensorFlow gpu using the below command 
`pip install tensorflow-gpu==2.2.0` and check if you are still facing the same issue. Thanks!

**Comment by tamimmirza** [comment]
I did that prior to opening the issue
I uninstalled `tensorflow` and installed `tensorflow-gpu` and I still got the same result

I also did a fresh install of Miniconda

**Comment by tamimmirza** [comment]
I installed TensorFlow 2.3.0 along with a fresh install of Miniconda3 and it solved my problem and correctly identifies the proper GPU

![Annotation 2020-07-28 173250](https://user-images.githubusercontent.com/35456031/88665704-7add1f00-d0f8-11ea-8e5e-d722d6110e9d.png)
