### ISSUE TITLE
How to convet "tf.nn.ctc_greedy_decoder" output into readable format?

### ISSUE THREAD

**Issue by vishalthengane** [tensorflow/tensorflow#41722]
I am using `tf.nn.ctc_greedy_decoder` to decode the text but I am not able to read `decoder[0].indices`. how to read this decoder data (or how to convert it to NumPy)?

code:
`
decoder, _ = tf.compat.v1.nn.ctc_greedy_decoder(inputs=inputs, 
													sequence_length=seqLen, 
													merge_repeated=True)
print(decoder[0].indices)
`

**Comment by amahendrakar** [comment]
@vishalthengane,
In order to expedite the trouble-shooting process, could you please provide the TensorFlow version, complete code and the dataset you are using. Thanks!
