### ISSUE TITLE
Tensorflow stuck in training with more than two GPUs

### ISSUE THREAD

**Issue by g-soto** [tensorflow/tensorflow#41724]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No, I am using the example presented in https://www.tensorflow.org/guide/gpu#using_multiple_gpus

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04.3 LTS

- TensorFlow installed from (source or binary):
I am using the TensorFlow Docker image tensorflow/tensorflow:latest-gpu-jupyter

- TensorFlow version (use command below):
2.2.0

- Python version:
3.6.9

- CUDA/cuDNN version:
CUDA version: 10.1
- GPU model and memory:
Nvidia Tesla P100-SXM2

**Describe the current behavior**
When I try to run the code below in a jupyter notebook with more than two GPUs it get stuck in the training step. It works fine with two GPUs.

**Standalone code to reproduce the issue**

```
import tensorflow as tf
strategy = tf.distribute.MirroredStrategy()
input_values = tf.random.uniform((256,), minval=0, maxval=1, dtype=tf.dtypes.float32)
with strategy.scope():
    inputs = tf.keras.layers.Input(shape=(1,))
    predictions = tf.keras.layers.Dense(1)(inputs)
    model = tf.keras.models.Model(inputs=inputs, outputs=predictions)
    model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(learning_rate=0.2))
    
    model.fit(input_values, input_values, batch_size=32)
```

**Comment by nikitamaia** [comment]
Hi @g-soto, I ran this code with 4 GPUs and training completed successfully.
Since I am unable to reproduce, I'm wondering if maybe there's an issue with one of your GPUs. Can you first run a test to make sure each GPU is functioning by running training with a single GPU at a time. If you have more than one GPU in your system, the GPU with the lowest ID will be selected by default, so you'll need to specify which GPU you want utilized. You can do that with tf.config.set_visible_devices to specify which devices are visible to the runtime.

**Comment by g-soto** [comment]
Hi @nikitamaia, I ran the training on each GPU individually without a problem.

**Comment by nikitamaia** [comment]
Can you try the following:
`strategy = tf.distribute.MirroredStrategy(cross_device_ops=tf.distribute.ReductionToOneDevice())`
 this is to check whether NCCL is causing problems.

**Comment by g-soto** [comment]
With the `cross_device_ops=tf.distribute.ReductionToOneDevice()` argument it works perfectly in eight GPUs.

**Comment by obriensystems** [comment]
Thanks for this - I with the strategy change I was able to run on more than 2 L4s
or on a triple RTX-4500/4500/4000
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/655
