### ISSUE TITLE
Missing files and flag for building linkable archives with `make` on Linux (Ubuntu)

### ISSUE THREAD

**Issue by ic** [tensorflow/tensorflow#4172]
Trying to build under Linux, I have faced two issues, one for PIC missing, and one for a missing file in the source build list.

I guess the origin of the problem is the `Makefile` depends on Bazel's build, and changes may be missing.

How does this looks for you? Here is a temporary [patch](https://github.com/tensorflow/tensorflow/compare/master...ic:master).

### Environment info
Operating System: Linux 16_04

Installed version of CUDA and cuDNN: None

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`): 461caa86137aee3d2e40843ea308c216f10c4655
2. The output of `bazel version`: It does not apply here (using `make` from the `tensor flow/contrib/makefile` project.

### If possible, provide a minimal reproducible example:

    cd TF_HOME
    ./tensorflow/contrib/makefile/download_dependencies.sh
    cd tensorflow/contrib/makefile/downloads/protobuf
    make && make check && sudo make install && sudo ldconfig
    cd -
    make -f tensorflow/contrib/makefile/Makefile

    # Long build
    # Leading to error when building `benchmark`

### What other attempted solutions have you tried?

I have tried to build on Ubuntu 14_04 and Mac OS X (10.10). It worked only on Mac OS X. Then I realized that the build chokes on my Linux boxes for PIC, and then for a missing file. Adding them (see a [solution here](https://github.com/tensorflow/tensorflow/compare/master...ic:master)) fixes all.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

The build fails with (added breaks for readability):

    gcc --std=c++11 -DIS_SLIM_BUILD -O0 -fPIC -I. 
    -I./tensorflow/contrib/makefile/downloads/ 
    -I./tensorflow/contrib/makefile/downloads/eigen-eigen-9e1b48c333aa 
    -I./tensorflow/contrib/makefile/gen/proto/ 
    -I./tensorflow/contrib/makefile/gen/proto_text/ -I/usr/local/include 
    -o ./tensorflow/contrib/makefile/gen/bin/benchmark
    ./tensorflow/contrib/makefile/gen/obj/tensorflow/core/util/reporter.o
    ./tensorflow/contrib/makefile/gen/obj/tensorflow/tools/benchmark/benchmark_model.o
    ./tensorflow/contrib/makefile/gen/obj/tensorflow/tools/benchmark/benchmark_model_main.o -Wl,--allow-multiple-definition -Wl,--whole-archive ./tensorflow/contrib/makefile/gen/lib/libtensorflow-core.a -L/usr/local/lib -lstdc++ -lprotobuf -lz -lm -ldl -lpthread
    ./tensorflow/contrib/makefile/gen/lib/libtensorflow-core.a(conv_ops.o): In function `tensorflow::LaunchDeepConvOp<Eigen::ThreadPoolDevice, float>::Run(tensorflow::OpKernelContext*, tensorflow::Tensor const&, tensorflow::Tensor const&, int, int, int, int, int, int, int, int, int, int, int, int, int, tensorflow::Tensor*, tensorflow::TensorFormat)':
    conv_ops.cc:
    (.text._ZN10tensorflow16LaunchDeepConvOpIN5Eigen16ThreadPoolDeviceEfE3RunEPNS_15OpKernelContextERKNS_6TensorES8_iiiiiiiiiiiiiPS6_NS_12TensorFormatE[_ZN10tensorflow16LaunchDeepConvOpIN5Eigen16ThreadPoolDeviceEfE3RunEPNS_15OpKernelContextERKNS_6TensorES8_iiiiiiiiiiiiiPS6_NS_12TensorFormatE]+0x70): 
    undefined reference to `tensorflow::CanUseDeepConv2D(int, int, int, int, int, int, int, int)'
    conv_ops.cc:
    (.text._ZN10tensorflow16LaunchDeepConvOpIN5Eigen16ThreadPoolDeviceEfE3RunEPNS_15OpKernelContextERKNS_6TensorES8_iiiiiiiiiiiiiPS6_NS_12TensorFormatE[_ZN10tensorflow16LaunchDeepConvOpIN5Eigen16ThreadPoolDeviceEfE3RunEPNS_15OpKernelContextERKNS_6TensorES8_iiiiiiiiiiiiiPS6_NS_12TensorFormatE]+0x184): 
    undefined reference to `tensorflow::functor::DeepConv2D<Eigen::ThreadPoolDevice, float>::operator()(tensorflow::OpKernelContext*, tensorflow::Conv2DArgs const&, float const*, float const*, float*)'
    collect2: error: ld returned 1 exit status

**Comment by martinwicke** [comment]
Send a PR with the fixes? @petewarden can you review that PR?

**Comment by ic** [comment]
[PR](https://github.com/tensorflow/tensorflow/pull/4260) ready.

**Comment by petewarden** [comment]
Thanks for the PR @ic! Closing since this appears to be fixed.
