### ISSUE TITLE
error shows when doing the command 'python -m tensorflow.models.image.mnist.convolutional' #3674

### ISSUE THREAD

**Issue by JulyUp** [tensorflow/tensorflow#4173]
After I install tensorflow using pip, I do the simplest command to train minst. But it shows error:

I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally Extracting data/train-images-idx3-ubyte.gz Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 326, in <module> tf.app.run() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run sys.exit(main(sys.argv)) File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 138, in main train_data = extract_data(train_data_filename, 60000) File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 85, in extract_data buf = bytestream.read(IMAGE_SIZE * IMAGE_SIZE * num_images * NUM_CHANNELS) File "/usr/lib/python2.7/gzip.py", line 261, in read self._read(readsize) File "/usr/lib/python2.7/gzip.py", line 308, in _read self._read_eof() File "/usr/lib/python2.7/gzip.py", line 347, in _read_eof hex(self.crc))) IOError: CRC check failed 0x56d16c09 != 0x39bbe345L

**Comment by JulyUp** [comment]
What should I do to solve this problem？

**Comment by hholst80** [comment]
try and unpack `data/train-images-idx3-ubyte.gz` manually - does it work?

**Comment by hholst80** [comment]
Otherwise you could try and delete `train-images-idx3-ubyte.gz` and the script should try and download it again from the source. Hopefully without any errors. It could be a problem with gzip library on your machine but that is less likely.

**Comment by JulyUp** [comment]
@hholst80  I delete train-images-idx3-ubyte.gz and download it again from the source. And it works. Thank you very much !
