### ISSUE TITLE
Confusion regarding TensorFlow licensing

### ISSUE THREAD

**Issue by rani-pinchuk** [tensorflow/tensorflow#41739]
## URL(s) with the issue: 
https://www.tensorflow.org/install/lang_c
and 
https://www.tensorflow.org

## Description of issue (what needs changing):
- There is no text in the documentation regarding the licensing of the C API.
- There is no text in the documentation regarding the licensing of TensorFlow as a whole (see below).

### Clear description
When downloading the tar.gz file of the C API, or when building that C API, it comes with two license files: LICENSE and THIRD_PARTY_TF_C_LICENSES. The second file contains the GPL license for everything under ./bench/btl.

Yet, when looking at the package, there is no such path. Actually, this path is not available also in the source code of TensorFlow. This is confusing and may lead to the conclusion that this license is not applicable for the C API code or to TensorFlow as a whole and is provided by mistake.  

However, when compiling the TensorFlow code, such a path is created. Yet, still not in the package of the C API.

Could this be clarified: what is the license of the C API libraries? Is it allowed to link these libraries to commercial code without being exposed to GPL? 

And what is the license of TensorFlow code as a whole? Is it allowed to, for example, use TensorFlow code as part of a commercial Python application without being exposed to GPL?

I think that this information should come in the above mentioned URLs - the page about C API and the main page of TensorFlow.

**Comment by mihaimaruseac** [comment]
All files start with a license header https://github.com/tensorflow/tensorflow/blob/76319741cd303273a542eae0cdf78df61e2c4e83/tensorflow/c/c_api.h#L1-L14

Adding a few more people to answer the questions

**Comment by ewilderj** [comment]
@lamberta for potential API doc consequence.

There is no strict need for the documentation to specify the license as it is mentioned in the source.
However, for ease of users recognizing this it's worth considering making this information obvious in documentation.

**Comment by rani-pinchuk** [comment]
All files indeed start with a license header. This is correct. But if we look at the example given - the C API library - one will have to go through many many files to check which licenses are used. Moreover, it seems that with respect to the specific issue mentioned above, the Eigen library can be compiled using the EIGEN_MPL2_ONLY flag. And this flag is used in the TensorFlow code, but I am not sure how exactly and if it is used everywhere. The bench/btl that is mentioned above seem to be related to comparing performance and running benchmarks, so probably it does not have to be included when building the C API library or the rest of TensorFlow. But how can a user that download these libraries, when they are already built, know if it is included or not?

**Comment by lamberta** [comment]
For docs and code samples. this is the text at the footer of each developer page (such as https://www.tensorflow.org/install/lang_c):

> Except as otherwise noted, the content of this page is licensed under the [Creative Commons Attribution 4.0 License](https://creativecommons.org/licenses/by/4.0/), and code samples are licensed under the [Apache 2.0 License](https://www.apache.org/licenses/LICENSE-2.0). For details, see the [Google Developers Site Policies](https://developers.google.com/site-policies). Java is a registered trademark of Oracle and/or its affiliates.

**Comment by rani-pinchuk** [comment]
None of the explanations above address the most important issue here: when downloading one of the *compiled* packages from https://www.tensorflow.org/install/lang_c, it comes with a THIRD_PARTY_TF_C_LICENSES file that contains, among other things, the following:
"Following applies to:
  everything under ./bench/btl

                    GNU GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007
..."

Nowhere it is mentioned how the package itself was compiled. This leaves the user with doubts with respect to the licensing of that package. As licensing is a delicate matter, I think that this should be clarified both in the packages themselves and in the page that provides the link to download them.

**Comment by mihaimaruseac** [comment]
That is the Eigen license https://github.com/tensorflow/tensorflow/blob/57395f70dbc24d3ac5f97626520194f6773303e8/third_party/eigen3/LICENSE#L1013-L1017

However, we don't import those benchmark files. https://github.com/tensorflow/tensorflow/tree/57395f70dbc24d3ac5f97626520194f6773303e8/third_party/eigen3

**Comment by rani-pinchuk** [comment]
Thank mihaimaruseac - you write that the Eigen benchmark files are not imported. Does this mean that the downloads in https://www.tensorflow.org/install/lang_c are built without them? But then, why do the .zip files contain that GPL license in the THIRD_PARTY_TF_C_LICENSES ? 

If the DLL is built without the Eigen files, then the GPL license is not applicable for this download, and should be removed from the THIRD_PARTY_TF_C_LICENSES file. 

So the question here is simple but crucial for companies that need to work with the TensorFlow C API library - what licenses are applicable to the DLL that is downloaded?

**Comment by rani-pinchuk** [comment]
When looking further into this, I find that in https://github.com/tensorflow/tensorflow/blob/master/third_party/eigen.BUILD it is mentioned that 

> "Eigen is an MPL2 library that includes GPL v3 and LGPL v2.1+ code. We've taken special care to not reference any restricted code."

> "Guarantees that any non-MPL2 file added to the list above will fail to compile", 

and

> "This define (mostly) guarantees we don't link any problematic code. We use it, but we do not rely on it, as evidenced above". 

It is therefore looks like it is simply a mistake to include the GPL in the THIRD_PARTY_TF_C_LICENSES file. 

Could you please remove the GPL mention from that file, or explain why it is included there?

**Comment by rani-pinchuk** [comment]
Could you please react to my last comment above? This issue is a blocking issue for me. 

I have just checked the and the file libtensorflow-cpu-windows-x86_64-2.4.0.zip (of the new TensorFlow 2.4.0 release) still contain the mention of GPL with respect to bench/btl.

(please note also that the page https://www.tensorflow.org/api_docs/python/tf is not updated with the correct links to the latest builds).

**Comment by ewilderj** [comment]
@theadactyl can you take a look?

**Comment by theadactyl** [comment]
Hi @rani-pinchuk thanks for explaining this issue to us. We will take a look at this in the next couple of days as the team returns from holiday.

**Comment by lamberta** [comment]
Thanks, all.
https://github.com/tensorflow/tensorflow/commit/8ab9ab6217aba0b771f05b3bd883ee33ae860931 clarifies that TensorFlow has taken special care to not reference any restricted code and removes the GPL from that license section.
