### ISSUE TITLE
BoostedTreesClassifier only supports dictionary-based dataset

### ISSUE THREAD

**Issue by dwyatte** [tensorflow/tensorflow#41732]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): All
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.7.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
When using `BoostedTreesClassifier` (and likely related classes), the features part of the dataset must be represented as a dictionary of strings to tensors whereas the docs state that the dataset can consist of "A tuple (features, labels): Where features is a **tf.Tensor or** a dictionary of string feature name to Tensor..."

```python

    772   outputs = {}
    773   with ops.name_scope(
--> 774       None, default_name='transform_features', values=features.values()):
    775     transformation_cache = FeatureTransformationCache(features)
    776     for column in feature_columns:

AttributeError: 'Tensor' object has no attribute 'values'
```

**Describe the expected behavior**
The features part of the dataset should be able to be represented as a tensor (preferred) or the docs should be updated to reflect this constraint.

**Standalone code to reproduce the issue**
```python
import numpy as np
import pandas as pd
import tensorflow as tf

N_OBS = 100
N_DIM = 10
BATCH_SIZE = N_OBS

df = pd.DataFrame(np.random.rand(N_OBS, N_DIM), columns=[f'dim_{i}' for i in range(N_DIM)])
labels = pd.Series(np.random.rand(N_OBS).round())

def input_fn(df, labels, batch_size=BATCH_SIZE):
    # dataset = tf.data.Dataset.from_tensor_slices((dict(df), labels.values))  # works
    dataset = tf.data.Dataset.from_tensor_slices((df.values, labels.values))  # does not work 
    dataset = dataset.repeat().batch(batch_size)
    return dataset

feature_columns = [tf.feature_column.numeric_column(f'dim_{i}') for i in range(N_DIM)]
estimator = tf.estimator.BoostedTreesClassifier(
    feature_columns,
    n_batches_per_layer=N_OBS // BATCH_SIZE
)

estimator.train(lambda: input_fn(df, labels), max_steps=100)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Feature column source where `features.values()` is referenced: https://github.com/tensorflow/tensorflow/blob/090f260aab3dab00bcdf0232962e753bb9fab696/tensorflow/python/feature_column/feature_column_v2.py#L418

**Comment by Saduf2019** [comment]
@dwyatte 
Could you please refer to [this link](https://stackoverflow.com/questions/47030644/tensorboard-error-tensor-object-has-no-attribute-value) and let us know if it helps.
also [link1](https://github.com/keras-team/keras/issues/7362#issuecomment-315922830)

**Comment by dwyatte** [comment]
@Saduf2019 this error appears to be specifically due to the expectation that the features part of the dataset has a `.values()` method, which is true of dictionaries.

Looking at the other canned estimators, they raise a more useful exception e.g. for `LinearClassifier`, 

```
~/GitHub/tf_boosted_trees/venv/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/canned/linear.py in _linear_model_fn_v2(features, labels, mode, head, feature_columns, optimizer, config, sparse_combiner)
    652   if not isinstance(features, dict):
    653     raise ValueError('features should be a dictionary of `Tensor`s. '
--> 654                      'Given type: {}'.format(type(features)))
    655 
    656   del config

ValueError: features should be a dictionary of `Tensor`s. Given type: <class 'tensorflow.python.framework.ops.Tensor'>
```

I think it would be helpful to raise this same exception for `BoostedTreesEstimator/BoostedTreesClassifier/BoostedTreesRegressor`. Furthermore, we might consider updating the docs to reflect that **only** dictionaries of `Tensor`s are supported for canned estimators (currently they suggest a user can alternatively pass a tensor without wrapping the columns in a dictionary).

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF 2.6.0-dev20210530,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/1ce715eb3d42316042e3900bf919e721/untitled113.ipynb#scrollTo=QyptKXfpNiB6)..Thanks !

**Comment by dwyatte** [comment]
BoostedTreesClassifier and other estimators are now deprecated

**Comment by fredowashere** [comment]
What happened to BoostedTreesClassifier? I can't find them within the estimator namespace in the doc

**Comment by xqliang** [comment]
See https://github.com/tensorflow/tensorflow/issues/53871#issuecomment-1023768134

> `BoostedTreesClassifier` is depreciated, you can refer to [TensorFlow Decision Forests](https://www.tensorflow.org/decision_forests) and for contribution you can check in the github repo tensorflow/decision-forests [here](https://github.com/tensorflow/decision-forests).
