### ISSUE TITLE
Tensorflow build from source doesn’t see GPUs gets “ failed call to cuInit: UNKNOWN ERROR (-1)”

### ISSUE THREAD

**Issue by RayLucchesi** [tensorflow/tensorflow#41748]
System information:
Tensorflow 2.4.0 (built from tensorflow/tensorflow:develgpu and then followed Build from source on 24Jul2020)
Nvidia-cuda 11.0
Nvidia-driver-450

This from nvidia-smi 

nvidia-smi
Sun Jul 26 20:50:35 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.57       Driver Version: 450.57       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    On   | 00000000:01:00.0 Off |                  N/A |
|  0%   28C    P8     4W / 166W |    191MiB /  8116MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1070    On   | 00000000:05:00.0 Off |                  N/A |
|  0%   29C    P8     5W / 166W |    150MiB /  8119MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 107...  On   | 00000000:06:00.0 Off |                  N/A |
|  0%   34C    P8     5W / 180W |    168MiB /  8119MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1010      G   /usr/lib/xorg/Xorg                 36MiB |
|    0   N/A  N/A      1708      G   /usr/bin/gnome-shell                9MiB |
|    0   N/A  N/A      4316      C   nvidia-cuda-mps-server            141MiB |
|    1   N/A  N/A      1010      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A      4316      C   nvidia-cuda-mps-server            141MiB |
|    2   N/A  N/A      1010      G   /usr/lib/xorg/Xorg                  4MiB |
|    2   N/A  N/A      4316      C   nvidia-cuda-mps-server            159MiB |

I got beyond the error above when I changed the LD_LIBRARY_PATH using:

export LD_LIBRARY_PATH=“/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/include/x64_64-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64” 

This deleted the stubs library. 

And then I started to get CUDA_ERROR_MAP_FAILED
And in /var/log/nvidia-mps/control.log I see: 

User did not send valid credentials

looking up this error. Someone suggested adding —ipc=“host” to the docker run command and that fixed the problem for me. 

So what your team should do is document that when build from source and trying to execute under that container the “stubs” library needs to be deleted from the LD_LIBRARY_PATH 
AND
the container needs to be run with —ipc=“host” on the docker run command.

<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@RayLucchesi,
In order to expedite the trouble-shooting process, please provide the 'System information' details in the template.

Also as per the [tested build configurations](https://www.tensorflow.org/install/source#gpu), please try building TensorFlow with CUDA 10.1 and cuDNN 7.6 and check if it works. Thanks!

**Comment by RayLucchesi** [comment]
@amahendrakar i've now build from source 2 in the last week or so. Each time took on the order of 11hrs of dedicated server time. And ~20GB of disk space on my 128GB SSD to commit the container and save the image file. In your tested configuration table you don't seem to have Tf 2.4 or even 2.3 so it was unclear what I was supposed to use for CUDA and cuDNN so I just took the latest stable levels of all that. 

I ended up building twice because I couldn't understand why cuinit.cc was throwing an unknown error (-1), so thought I had done the build wrong. 

Sorry I'm not going to retry with these the CUDA and cuDNN levels you suggest are valid for TF2.4. I would need to down level my now working system and spend another 11 hrs compiling something that I'm going to throw out anyway. 

You can go ahead and close this issue if you wish. Or you could re-attempt the build yourself. I had to build from source because of my Skylake CPU was not supported by the tf/tf: containers that were already built. Or you could examine the tf/tf:devel-gpu container and see that the LD_LIBRARY_PATH indeed includes the STUBs library (which won't work after you build from source AND check to see if when using NVIDIA-MPS that the --ipc="host" parameter needs to be specified of if it could be allowed to be defaulted. 

BY THE WAY, It was not clear whether I should be running NVIDIA-MPS or not but as it's running in a docker container and there's the outside possibility that I might be running something else on the GPUs it seemed to me (and others) to be the right thing to use.

Thanks,

**Comment by amahendrakar** [comment]
@RayLucchesi,
I understand your concern, we'll help you through the process and fix the issue. 

Could you please provide the platform details of the machine you're trying to build TensorFlow on. Also, list out the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by RayLucchesi** [comment]
I Build from source using the information provided in https://www.tensorflow.org/install/source.
Committed the container into an image file (and saved it).

and then issued the following commands at a terminal:

sudo nvidia-smi -pm 1
docker run --gpus 1 --ipc="host" -it -w /tensorflow -v $PWD:/mnt -p 8888:8888 -e HOST_PERMS="$(id -u):$(id -g)" tensorflow/tensorflow:from-src2 bash 
export LD_LIBRARY_PATH=“/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/include/x64_64-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64”
pip install jupyter
pip install jupyter_http_over_ws
jupyter serverextension enable --py jupyter_http_over_ws
jupyter notebook --no-browser --notebook-dir=/mnt/notebooks --ip=0.0.0.0 --MappingKernelManager.cull_interval=1200 --debug --NotebookApp.allow_origin='https://www.example.com' --NotebookApp.allow_remote_access=True --allow-root

At this point if I run your text-classification notebook it bombs with the error.  

I'll send sys info in next comment.

**Comment by RayLucchesi** [comment]
lspci command results. 

00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Host Bridge/DRAM Registers (rev 07)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x16) (rev 07)
00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model
00:14.0 USB controller: Intel Corporation 200 Series/Z370 Chipset Family USB 3.0 xHCI Controller
00:14.2 Signal processing controller: Intel Corporation 200 Series PCH Thermal Subsystem
00:16.0 Communication controller: Intel Corporation 200 Series PCH CSME HECI #1
00:17.0 SATA controller: Intel Corporation 200 Series PCH SATA controller [AHCI mode]
00:1b.0 PCI bridge: Intel Corporation 200 Series PCH PCI Express Root Port #17 (rev f0)
00:1b.2 PCI bridge: Intel Corporation 200 Series PCH PCI Express Root Port #19 (rev f0)
00:1c.0 PCI bridge: Intel Corporation 200 Series PCH PCI Express Root Port #1 (rev f0)
00:1c.5 PCI bridge: Intel Corporation 200 Series PCH PCI Express Root Port #6 (rev f0)
00:1c.6 PCI bridge: Intel Corporation 200 Series PCH PCI Express Root Port #7 (rev f0)
00:1c.7 PCI bridge: Intel Corporation 200 Series PCH PCI Express Root Port #8 (rev f0)
00:1f.0 ISA bridge: Intel Corporation 200 Series PCH LPC Controller (Z270)
00:1f.2 Memory controller: Intel Corporation 200 Series/Z370 Chipset Family Power Management Controller
00:1f.3 Audio device: Intel Corporation 200 Series PCH HD Audio
00:1f.4 SMBus: Intel Corporation 200 Series/Z370 Chipset Family SMBus Controller
01:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1070 Ti] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GP104 High Definition Audio Controller (rev a1)
03:00.0 USB controller: ASMedia Technology Inc. ASM2142 USB 3.1 Host Controller
05:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)
05:00.1 Audio device: NVIDIA Corporation GP104 High Definition Audio Controller (rev a1)
06:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)
06:00.1 Audio device: NVIDIA Corporation GP104 High Definition Audio Controller (rev a1)
07:00.0 Ethernet controller: Qualcomm Atheros Killer E2500 Gigabit Ethernet Controller (rev 10)

**Comment by RayLucchesi** [comment]
here is output from lshw command:

ubuntu-ai                   
    description: Desktop Computer
    product: MS-7A62 (Default string)
    vendor: MSI
    version: 1.0
    serial: Default string
    width: 64 bits
    capabilities: smbios-3.0.0 dmi-3.0.0 smp vsyscall32
    configuration: boot=normal chassis=desktop family=Default string sku=Default string uuid=00000000-0000-0000-0000-4CCC6AF7447F
  *-core
       description: Motherboard
       product: Z270 GAMING M3 (MS-7A62)
       vendor: MSI
       physical id: 0
       version: 1.0
       serial: H316061861
       slot: Default string
     *-firmware
          description: BIOS
          vendor: American Megatrends Inc.
          physical id: 0
          version: 1.10
          date: 02/07/2017
          size: 64KiB
          capacity: 16MiB
          capabilities: pci upgrade shadowing cdboot bootselect socketedrom edd int13floppy1200 int13floppy720 int13floppy2880 int5printscreen int9keyboard int14serial int17printer acpi usb biosbootspecification uefi
     *-memory
          description: System Memory
          physical id: 3c
          slot: System board or motherboard
          size: 8GiB
        *-bank:0
             description: [empty]
             physical id: 0
             slot: ChannelA-DIMM0
        *-bank:1
             description: DIMM DDR4 Synchronous 2400 MHz (0.4 ns)
             product: BLS4G4D240FSB.8FBD2
             vendor: 859B
             physical id: 1
             serial: A624BDFD
             slot: ChannelA-DIMM1
             size: 4GiB
             width: 64 bits
             clock: 2400MHz (0.4ns)
        *-bank:2
             description: [empty]
             physical id: 2
             slot: ChannelB-DIMM0
        *-bank:3
             description: DIMM DDR4 Synchronous 2400 MHz (0.4 ns)
             product: BLS4G4D240FSB.8FBD2
             vendor: 859B
             physical id: 3
             serial: A624BDFC
             slot: ChannelB-DIMM1
             size: 4GiB
             width: 64 bits
             clock: 2400MHz (0.4ns)
     *-cache:0
          description: L1 cache
          physical id: 42
          slot: L1 Cache
          size: 128KiB
          capacity: 128KiB
          capabilities: synchronous internal write-back unified
          configuration: level=1
     *-cache:1
          description: L2 cache
          physical id: 43
          slot: L2 Cache
          size: 512KiB
          capacity: 512KiB
          capabilities: synchronous internal write-back unified
          configuration: level=2
     *-cache:2
          description: L3 cache
          physical id: 44
          slot: L3 Cache
          size: 3MiB
          capacity: 3MiB
          capabilities: synchronous internal write-back unified
          configuration: level=3
     *-cpu
          description: CPU
          product: Intel(R) Pentium(R) CPU G4400 @ 3.30GHz
          vendor: Intel Corp.
          physical id: 45
          bus info: cpu@0
          version: Intel(R) Pentium(R) CPU G4400 @ 3.30GHz
          serial: To Be Filled By O.E.M.
          slot: U3E1
          size: 3206MHz
          capacity: 4005MHz
          width: 64 bits
          clock: 100MHz
          capabilities: lm fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp x86-64 constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust erms invpcid rdseed smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d cpufreq
          configuration: cores=2 enabledcores=2 threads=2
     *-pci
          description: Host bridge
          product: Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Host Bridge/DRAM Registers
          vendor: Intel Corporation
          physical id: 100
          bus info: pci@0000:00:00.0
          version: 07
          width: 32 bits
          clock: 33MHz
          configuration: driver=skl_uncore
          resources: irq:0
        *-pci:0
             description: PCI bridge
             product: Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x16)
             vendor: Intel Corporation
             physical id: 1
             bus info: pci@0000:00:01.0
             version: 07
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm msi pciexpress normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:120 ioport:e000(size=4096) memory:de000000-df0fffff ioport:c0000000(size=301989888)
           *-display
                description: VGA compatible controller
                product: GP104 [GeForce GTX 1070 Ti]
                vendor: NVIDIA Corporation
                physical id: 0
                bus info: pci@0000:01:00.0
                version: a1
                width: 64 bits
                clock: 33MHz
                capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
                configuration: driver=nvidia latency=0
                resources: irq:137 memory:de000000-deffffff memory:c0000000-cfffffff memory:d0000000-d1ffffff ioport:e000(size=128) memory:c0000-dffff
           *-multimedia
                description: Audio device
                product: GP104 High Definition Audio Controller
                vendor: NVIDIA Corporation
                physical id: 0.1
                bus info: pci@0000:01:00.1
                version: a1
                width: 32 bits
                clock: 33MHz
                capabilities: pm msi pciexpress bus_master cap_list
                configuration: driver=snd_hda_intel latency=0
                resources: irq:17 memory:df080000-df083fff
        *-generic:0 UNCLAIMED
             description: System peripheral
             product: Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model
             vendor: Intel Corporation
             physical id: 8
             bus info: pci@0000:00:08.0
             version: 00
             width: 64 bits
             clock: 33MHz
             capabilities: msi pm cap_list
             configuration: latency=0
             resources: memory:dd12f000-dd12ffff
        *-usb
             description: USB controller
             product: 200 Series/Z370 Chipset Family USB 3.0 xHCI Controller
             vendor: Intel Corporation
             physical id: 14
             bus info: pci@0000:00:14.0
             version: 00
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi xhci bus_master cap_list
             configuration: driver=xhci_hcd latency=0
             resources: irq:127 memory:dd110000-dd11ffff
           *-usbhost:0
                product: xHCI Host Controller
                vendor: Linux 5.4.0-42-generic xhci-hcd
                physical id: 0
                bus info: usb@1
                logical name: usb1
                version: 5.04
                capabilities: usb-2.00
                configuration: driver=hub slots=16 speed=480Mbit/s
              *-usb:0
                   description: Mouse
                   product: USB Optical Mouse
                   vendor: Logitech
                   physical id: 7
                   bus info: usb@1:7
                   version: 72.00
                   capabilities: usb-2.00
                   configuration: driver=usbhid maxpower=100mA speed=2Mbit/s
              *-usb:1
                   description: Keyboard
                   product: USB Keyboard
                   vendor: Logitech
                   physical id: 8
                   bus info: usb@1:8
                   version: 64.00
                   capabilities: usb-1.10
                   configuration: driver=usbhid maxpower=90mA speed=2Mbit/s
           *-usbhost:1
                product: xHCI Host Controller
                vendor: Linux 5.4.0-42-generic xhci-hcd
                physical id: 1
                bus info: usb@2
                logical name: usb2
                version: 5.04
                capabilities: usb-3.00
                configuration: driver=hub slots=10 speed=5000Mbit/s
        *-generic:1 UNCLAIMED
             description: Signal processing controller
             product: 200 Series PCH Thermal Subsystem
             vendor: Intel Corporation
             physical id: 14.2
             bus info: pci@0000:00:14.2
             version: 00
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi cap_list
             configuration: latency=0
             resources: memory:dd12e000-dd12efff
        *-communication
             description: Communication controller
             product: 200 Series PCH CSME HECI #1
             vendor: Intel Corporation
             physical id: 16
             bus info: pci@0000:00:16.0
             version: 00
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi bus_master cap_list
             configuration: driver=mei_me latency=0
             resources: irq:132 memory:dd12d000-dd12dfff
        *-sata
             description: SATA controller
             product: 200 Series PCH SATA controller [AHCI mode]
             vendor: Intel Corporation
             physical id: 17
             bus info: pci@0000:00:17.0
             logical name: scsi0
             version: 00
             width: 32 bits
             clock: 66MHz
             capabilities: sata msi pm ahci_1.0 bus_master cap_list emulated
             configuration: driver=ahci latency=0
             resources: irq:131 memory:dd128000-dd129fff memory:dd12c000-dd12c0ff ioport:f050(size=8) ioport:f040(size=4) ioport:f020(size=32) memory:dd12b000-dd12b7ff
           *-disk
                description: ATA Disk
                product: SanDisk SDSSDA12
                physical id: 0.0.0
                bus info: scsi@0:0.0.0
                logical name: /dev/sda
                version: 80RL
                serial: 171833459715
                size: 111GiB (120GB)
                capabilities: gpt-1.00 partitioned partitioned:gpt
                configuration: ansiversion=5 guid=725cc7ba-faa9-4fe5-9e62-6b7b8a0b7aa7 logicalsectorsize=512 sectorsize=512
              *-volume:0
                   description: Windows FAT volume
                   vendor: mkfs.fat
                   physical id: 1
                   bus info: scsi@0:0.0.0,1
                   logical name: /dev/sda1
                   logical name: /boot/efi
                   version: FAT32
                   serial: 1773-3e94
                   size: 510MiB
                   capacity: 511MiB
                   capabilities: boot fat initialized
                   configuration: FATs=2 filesystem=fat mount.fstype=vfat mount.options=rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro state=mounted
              *-volume:1
                   description: EXT4 volume
                   vendor: Linux
                   physical id: 2
                   bus info: scsi@0:0.0.0,2
                   logical name: /dev/sda2
                   logical name: /boot
                   version: 1.0
                   serial: af28e231-0e6d-41f6-a632-b96cc017ffba
                   size: 1GiB
                   capabilities: journaled extended_attributes large_files huge_files dir_nlink recover 64bit extents ext4 ext2 initialized
                   configuration: created=2020-07-22 19:01:51 filesystem=ext4 lastmountpoint=/boot modified=2020-08-03 17:23:18 mount.fstype=ext4 mount.options=rw,relatime mounted=2020-08-03 17:23:18 state=mounted
              *-volume:2
                   description: EFI partition
                   physical id: 3
                   bus info: scsi@0:0.0.0,3
                   logical name: /dev/sda3
                   serial: PYSAzy-ypr8-pyaN-oJcD-y4NN-YdMJ-hPwFpv
                   size: 110GiB
                   capabilities: lvm2
        *-pci:1
             description: PCI bridge
             product: 200 Series PCH PCI Express Root Port #17
             vendor: Intel Corporation
             physical id: 1b
             bus info: pci@0000:00:1b.0
             version: f0
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:121
        *-pci:2
             description: PCI bridge
             product: 200 Series PCH PCI Express Root Port #19
             vendor: Intel Corporation
             physical id: 1b.2
             bus info: pci@0000:00:1b.2
             version: f0
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:122 memory:df300000-df3fffff
           *-usb
                description: USB controller
                product: ASM2142 USB 3.1 Host Controller
                vendor: ASMedia Technology Inc.
                physical id: 0
                bus info: pci@0000:03:00.0
                version: 00
                width: 64 bits
                clock: 33MHz
                capabilities: msi msix pm pciexpress xhci bus_master cap_list
                configuration: driver=xhci_hcd latency=0
                resources: irq:18 memory:df300000-df307fff
              *-usbhost:0
                   product: xHCI Host Controller
                   vendor: Linux 5.4.0-42-generic xhci-hcd
                   physical id: 0
                   bus info: usb@3
                   logical name: usb3
                   version: 5.04
                   capabilities: usb-2.00
                   configuration: driver=hub slots=2 speed=480Mbit/s
              *-usbhost:1
                   product: xHCI Host Controller
                   vendor: Linux 5.4.0-42-generic xhci-hcd
                   physical id: 1
                   bus info: usb@4
                   logical name: usb4
                   version: 5.04
                   capabilities: usb-3.10
                   configuration: driver=hub slots=2 speed=10000Mbit/s
        *-pci:3
             description: PCI bridge
             product: 200 Series PCH PCI Express Root Port #1
             vendor: Intel Corporation
             physical id: 1c
             bus info: pci@0000:00:1c.0
             version: f0
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:123
        *-pci:4
             description: PCI bridge
             product: 200 Series PCH PCI Express Root Port #6
             vendor: Intel Corporation
             physical id: 1c.5
             bus info: pci@0000:00:1c.5
             version: f0
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:124 ioport:d000(size=4096) memory:dc000000-dd0fffff ioport:a0000000(size=301989888)
           *-display
                description: VGA compatible controller
                product: GP104 [GeForce GTX 1070]
                vendor: NVIDIA Corporation
                physical id: 0
                bus info: pci@0000:05:00.0
                version: a1
                width: 64 bits
                clock: 33MHz
                capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
                configuration: driver=nvidia latency=0
                resources: irq:138 memory:dc000000-dcffffff memory:a0000000-afffffff memory:b0000000-b1ffffff ioport:d000(size=128) memory:dd000000-dd07ffff
           *-multimedia
                description: Audio device
                product: GP104 High Definition Audio Controller
                vendor: NVIDIA Corporation
                physical id: 0.1
                bus info: pci@0000:05:00.1
                version: a1
                width: 32 bits
                clock: 33MHz
                capabilities: pm msi pciexpress bus_master cap_list
                configuration: driver=snd_hda_intel latency=0
                resources: irq:18 memory:dd080000-dd083fff
        *-pci:5
             description: PCI bridge
             product: 200 Series PCH PCI Express Root Port #7
             vendor: Intel Corporation
             physical id: 1c.6
             bus info: pci@0000:00:1c.6
             version: f0
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:125 ioport:c000(size=4096) memory:da000000-db0fffff ioport:80000000(size=301989888)
           *-display
                description: VGA compatible controller
                product: GP104 [GeForce GTX 1070]
                vendor: NVIDIA Corporation
                physical id: 0
                bus info: pci@0000:06:00.0
                version: a1
                width: 64 bits
                clock: 33MHz
                capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
                configuration: driver=nvidia latency=0
                resources: irq:139 memory:da000000-daffffff memory:80000000-8fffffff memory:90000000-91ffffff ioport:c000(size=128) memory:db000000-db07ffff
           *-multimedia
                description: Audio device
                product: GP104 High Definition Audio Controller
                vendor: NVIDIA Corporation
                physical id: 0.1
                bus info: pci@0000:06:00.1
                version: a1
                width: 32 bits
                clock: 33MHz
                capabilities: pm msi pciexpress bus_master cap_list
                configuration: driver=snd_hda_intel latency=0
                resources: irq:19 memory:db080000-db083fff
        *-pci:6
             description: PCI bridge
             product: 200 Series PCH PCI Express Root Port #8
             vendor: Intel Corporation
             physical id: 1c.7
             bus info: pci@0000:00:1c.7
             version: f0
             width: 32 bits
             clock: 33MHz
             capabilities: pci pciexpress msi pm normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:126 ioport:b000(size=4096) memory:df200000-df2fffff
           *-network
                description: Ethernet interface
                product: Killer E2500 Gigabit Ethernet Controller
                vendor: Qualcomm Atheros
                physical id: 0
                bus info: pci@0000:07:00.0
                logical name: enp7s0
                version: 10
                serial: 4c:cc:6a:f7:44:7f
                size: 1Gbit/s
                capacity: 1Gbit/s
                width: 64 bits
                clock: 33MHz
                capabilities: pm pciexpress msi msix bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
                configuration: autonegotiation=on broadcast=yes driver=alx duplex=full ip=10.0.0.184 latency=0 link=yes multicast=yes port=twisted pair speed=1Gbit/s
                resources: irq:19 memory:df200000-df23ffff ioport:b000(size=128)
        *-isa
             description: ISA bridge
             product: 200 Series PCH LPC Controller (Z270)
             vendor: Intel Corporation
             physical id: 1f
             bus info: pci@0000:00:1f.0
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: isa bus_master
             configuration: latency=0
        *-memory UNCLAIMED
             description: Memory controller
             product: 200 Series/Z370 Chipset Family Power Management Controller
             vendor: Intel Corporation
             physical id: 1f.2
             bus info: pci@0000:00:1f.2
             version: 00
             width: 32 bits
             clock: 33MHz (30.3ns)
             configuration: latency=0
             resources: memory:dd124000-dd127fff
        *-multimedia
             description: Audio device
             product: 200 Series PCH HD Audio
             vendor: Intel Corporation
             physical id: 1f.3
             bus info: pci@0000:00:1f.3
             version: 00
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi bus_master cap_list
             configuration: driver=snd_hda_intel latency=32
             resources: irq:133 memory:dd120000-dd123fff memory:dd100000-dd10ffff
        *-serial
             description: SMBus
             product: 200 Series/Z370 Chipset Family SMBus Controller
             vendor: Intel Corporation
             physical id: 1f.4
             bus info: pci@0000:00:1f.4
             version: 00
             width: 64 bits
             clock: 33MHz
             configuration: driver=i801_smbus latency=0
             resources: irq:16 memory:dd12a000-dd12a0ff ioport:f000(size=32)
     *-pnp00:00
          product: PnP device PNP0c02
          physical id: 1
          capabilities: pnp
          configuration: driver=system
     *-pnp00:01
          product: PnP device PNP0303
          physical id: 2
          capabilities: pnp
          configuration: driver=i8042 kbd
     *-pnp00:02
          product: PnP device PNP0f03
          physical id: 3
          capabilities: pnp
          configuration: driver=i8042 aux
     *-pnp00:03
          product: PnP device PNP0501
          physical id: 4
          capabilities: pnp
          configuration: driver=serial
     *-pnp00:04
          product: PnP device PNP0c02
          physical id: 5
          capabilities: pnp
          configuration: driver=system
     *-pnp00:05
          product: PnP device PNP0c02
          physical id: 6
          capabilities: pnp
          configuration: driver=system
     *-pnp00:06
          product: PnP device PNP0b00
          physical id: 7
          capabilities: pnp
          configuration: driver=rtc_cmos
     *-pnp00:07
          product: PnP device INT3f0d
          physical id: 8
          capabilities: pnp
          configuration: driver=system
     *-pnp00:08
          product: PnP device PNP0c02
          physical id: 9
          capabilities: pnp
          configuration: driver=system
     *-pnp00:09
          product: PnP device PNP0c02
          physical id: a
          capabilities: pnp
          configuration: driver=system
     *-pnp00:0a
          product: PnP device PNP0c02
          physical id: b
          capabilities: pnp
          configuration: driver=system
     *-pnp00:0b
          product: PnP device PNP0c02
          physical id: c
          capabilities: pnp
          configuration: driver=system
  *-power UNCLAIMED
       description: To Be Filled By O.E.M.
       product: To Be Filled By O.E.M.
       vendor: To Be Filled By O.E.M.
       physical id: 1
       version: To Be Filled By O.E.M.
       serial: To Be Filled By O.E.M.
       capacity: 32768mWh
  *-network:0
       description: Ethernet interface
       physical id: 2
       logical name: vetha11e727
       serial: 7e:40:7f:0a:04:8c
       size: 10Gbit/s
       capabilities: ethernet physical
       configuration: autonegotiation=off broadcast=yes driver=veth driverversion=1.0 duplex=full link=yes multicast=yes port=twisted pair speed=10Gbit/s
  *-network:1
       description: Ethernet interface
       physical id: 3
       logical name: docker0
       serial: 02:42:69:a5:23:2a
       capabilities: ethernet physical
       configuration: broadcast=yes driver=bridge driverversion=2.3 firmware=N/A ip=172.17.0.1 link=yes multicast=yes

**Comment by RayLucchesi** [comment]
Let me know if there is any other system info you need.

**Comment by RayLucchesi** [comment]
Provided the requested info in the issue 
Ray

**Comment by RayLucchesi** [comment]
it seems this is due to having STUBS in the LD_LIBRARY_PATH when I remove that it works.

**Comment by gowthamkpr** [comment]
@RayLucchesi Glad that it works. Can we close this issue as it has been resolved. Thanks!

**Comment by RayLucchesi** [comment]
Yes
Ray

**Comment by gowthamkpr** [comment]
Closing this issue as it has been resolved. Please add additional comments for us to open this issue again. Thanks!
