### ISSUE TITLE
Building tensorflow 2.2 fails

### ISSUE THREAD

**Issue by amirekhlasi** [tensorflow/tensorflow#41743]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.2
- Python version: 3.8
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): 7.5
- CUDA/cuDNN version: 10.1/7.6
- GPU model and memory: GeForce GTX 1080 8111MiB

**Describe the problem**

Every time I use the ```bazel``` command to build tensorflow, this error appears:

```
ERROR: /home/amir/Documents/tensorflow/tensorflow/tensorflow/core/kernels/BUILD:2734:1: output 'tensorflow/core/kernels/_objs/eye_functor_gpu/eye_functor_gpu.cu.pic.o' was not created
```

or something like above that includes ```_gpu.cu.pic.o```.
I have built previous versions of tensorflow many times including tensorflow 1.9-1.13 with previous versions of cuda without problem

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
bazel build --config=opt --config=mkl //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**

Here is the .tf_configure_bazelrc configurations:

```
build --action_env PYTHON_BIN_PATH="/home/amir/Documents/tensorflow/py-env/bin/python"
build --action_env PYTHON_LIB_PATH="/home/amir/Documents/tensorflow/py-env/lib/python3.8/site-packages"
build --python_path="/home/amir/Documents/tensorflow/py-env/bin/python"
build --config=xla
build --action_env TF_CUDA_VERSION="10.1"
build --action_env TF_CUDNN_VERSION="7.6"
build --action_env TF_NCCL_VERSION="2.7"
build --action_env TF_CUDA_PATHS="/usr/local/cuda/cuda-10.1/extras/CUPTI,/usr/local/cuda/cuda-10.1/nccl/nccl-2.7,/usr/local/cuda/cuda-10.1/cudnn/cudnn-7.6,/usr/local/cuda/cuda-10.1"
build --action_env CUDA_TOOLKIT_PATH="/usr/local/cuda/cuda-10.1"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="6.1"
build --action_env LD_LIBRARY_PATH="/usr/local/cuda/cuda-10.1/extras/CUPTI/lib64:/usr/local/cuda/cuda-10.1/nccl/nccl-2.7/lib:/usr/local/cuda/cuda-10.1/cudnn/cudnn-7.6/lib64:/usr/local/cuda/cuda-10.1/lib64"
build --action_env GCC_HOST_COMPILER_PATH="/usr/bin/x86_64-linux-gnu-gcc-7"
build --config=cuda
build:opt --copt=-march=native
build:opt --copt=-Wno-sign-compare
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test:v1 --test_tag_filters=-benchmark-test,-no_oss,-gpu,-oss_serial
test:v1 --build_tag_filters=-benchmark-test,-no_oss,-gpu
test:v2 --test_tag_filters=-benchmark-test,-no_oss,-gpu,-oss_serial,-v1only
test:v2 --build_tag_filters=-benchmark-test,-no_oss,-gpu,-v1only
build --action_env TF_CONFIGURE_IOS="0"
```

**Comment by amahendrakar** [comment]
@amirekhlasi,
Looking at similar issues [#18980](https://github.com/tensorflow/tensorflow/issues/18980) and [#18522](https://github.com/tensorflow/tensorflow/issues/18522), the GCC version installed seems to be the issue. 

As per the [cuda installation guide](https://docs.nvidia.com/cuda/archive/10.1/cuda-installation-guide-linux/index.html), could you please try installing GCC v8.2.0 and check if you are able to build TensorFlow. Thanks!

**Comment by amirekhlasi** [comment]
That didn't solve the problem. I use gcc-8.2 and gcc-8.4 and the problem didn't solve. However that error didn't occur using cuda version 10.0. However in the final stages of compilation the following error occured:
```
ERROR: /home/amir/program-tools/tensorflow/tensorflow/tensorflow/python/BUILD:2308:1: Executing genrule //tensorflow/python:test_ops_pygenrule failed (Exit 127)
bazel-out/host/bin/tensorflow/python/gen_test_ops_py_wrappers_cc: error while loading shared libraries: libiomp5.so: cannot open shared object file: No such file or directory
```
but the above library exist in bazel cache:

```
./home/amir/.cache/bazel/_bazel_amir/4630ddb84c6dfcc49e38b17c2862818c/external/mkl_linux/lib/libiomp5.so
```

**Comment by amirekhlasi** [comment]
I can solve this problem by adding that directory to ```$LD_LIBRARY_PATH```. 
But the problem with CUDA 10.1 still exists

**Comment by amirekhlasi** [comment]
The latter can be solved by copying ```*/mkl_linux``` directory to an arbitrary location and adding ```*/mkl_linux/lib``` to ```LD_LIBRARY_PATH```.  
However the CUDA 10.1 problem is a serious bug and I was able to build Tensorflow 2.2 using both CUDA 10.0 and 10.2 but not 10.1. It seems CUDA 10.1 has serious problems, specially TensorRT 7 supports CUDA 9.x, 10.0, 10.2 but not 10.1!

**Comment by amahendrakar** [comment]
@amirekhlasi,
Thank you for the update. 

Is this still an issue? Please feel free to close the issue if resolved.
