### ISSUE TITLE
Autograph fails to convert nested **if-else** in a for loop

### ISSUE THREAD

**Issue by AakashKumarNain** [tensorflow/tensorflow#41746]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory: P100

**Describe the current behavior**

Unexpected behavior of `tf.function` decorator. The decorator fails to convert `if-else` inside a loop and because of this behavior, it can't be used standalone or inside `tf.keras` `train_step` function
 

**Standalone code to reproduce the issue**
```python
import tensorflow as tf
import numpy as np

class Sampler:
    def __init__(self, sample_size=10):
        self.sample_size = tf.Variable(sample_size, dtype=tf.int32)
        self.samples = tf.TensorArray(dtype=tf.float32, size=0, dynamic_size=True)
     
    @tf.function
    def get_new_samples(self, data):
        size = tf.shape(data)[0]
        new_samples = tf.TensorArray(dtype=tf.float32, size=0, dynamic_size=True)
        
        for i in range(size):
            if self.samples.size() < self.sample_size:
                self.samples.write(i, data[i,:])
                new_samples.write(i, data[i, :])
            else:
                if (tf.random.uniform([1]) > 0.5):
                    idx = np.random.randint(0, size)
                    new_sample = self.samples.read(idx)
                    self.samples.write(idx, data[i, :])
                    new_samples.write(i, new_sample)
                else:
                    new_samples.write(i, data[i, :])
        return new_samples.stack()
        
    
    def __call__(self, data):
        return tf.cond(tf.equal(self.sample_size, 0),
                      true_fn=lambda: data,
                      false_fn=self.get_new_samples(data))

s = Sampler()
s(tf.convert_to_tensor(np.random.rand(5, 3).astype(np.float32)))
```

https://colab.research.google.com/drive/1Tf1Pj-_HzpUC8CMG8gS4U2nGV0EPxVd7?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```python
OperatorNotAllowedInGraphError: in user code:

    <ipython-input-2-b3cdab60c185>:13 get_new_samples  *
        self.samples.write(i, data[i,:])
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/tf_should_use.py:235 wrapped  **
        return _add_should_use_warning(fn(*args, **kwargs),
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/tensor_array_ops.py:1159 write
        return self._implementation.write(index, value, name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/tensor_array_ops.py:833 write
        self._write(index, value)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/tensor_array_ops.py:796 _write
        if index < 0:
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:778 __bool__
        self._disallow_bool_casting()
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:545 _disallow_bool_casting
        "using a `tf.Tensor` as a Python `bool`")
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:532 _disallow_when_autograph_enabled
        " decorating it directly with @tf.function.".format(task))

    OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed: AutoGraph did not convert this function. Try decorating it directly with @tf.function.


```

**Comment by Saduf2019** [comment]
I am able to replicate this issue reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/42ac41ed8b81114b7ba13b52e11bbc47/untitled301.ipynb)

**Comment by AakashKumarNain** [comment]
Any updates on this? :)

**Comment by nikitamaia** [comment]
Hi @AakashKumarNain, if I run this code with tf-nightly I get the slightly different error message that 
`AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.`

Have you taken a look a the Autograph [limitations guide](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md) to make sure you're not attempting something that Autograph currently doesn't support?  There are some limitations when you apply Autograph to TF control flow (eg if statement with a tf.Tensor condition, as you have in your example). One thing to check is if the for loop is the culprit, ie make sure the if statements run correctly with Autograph when not in a loop.

**Comment by AakashKumarNain** [comment]
Hi @nikitamaia Thanks for the limitation guide. I looked at it and tried to make my example much simpler to replicate. Here is the updated version:

```python
import tensorflow as tf
import numpy as np

pool1 = tf.TensorArray(dtype=tf.float32, size=0, dynamic_size=True)
pool2 = tf.TensorArray(dtype=tf.float32, size=0, dynamic_size=True)
new_items = tf.TensorArray(dtype=tf.float32, size=0, dynamic_size=True)

def write_to_array(array, idx, item):
    array = array.write(idx, item)
    return array

@tf.function
def sampler(items, array1, array2):
    num_items = tf.shape(items)[0]
    for i in tf.range(num_items):
        if array1.size() < 10:
            array1 = write_to_array(array1, i, items[i, :, :, :])
            array2 = write_to_array(array2, i, items[i, :, :, :])
        else:
            array2 = write_to_pool(array2, i, items[i, :, :, :])
    return array2.stack()

items = tf.convert_to_tensor(np.random.rand(2, 2, 2, 3).astype(np.float32))
sampler(items, pool1, new_items)

```

This runs fine in eager mode but fails with `@tf.function`. TBH, this is a pretty basic use case where sampling is involved and if we can't run this, then we cannot override  the `train_step` in `keras` for model training.

**Comment by nikitamaia** [comment]
Have you tried creating the `TensorArrays` within your function as the error message suggests?
`You may be attempting to capture a TensorArray inside a tf.function or tf.data map function. Instead, construct a new TensorArray inside the function.`

That seems to work, but I cannot test your code fully since `write_to_pool` hasn't been provided.

**Comment by AakashKumarNain** [comment]
Sorry, my bad. Let me try to make it more clear this as much as I can. 

There are three arrays in total. Two of these arrays, `pool1` and `pool2` will be populated once until each of them contains `10` samples. After that, the values in these arrays won't change. The third array, `new_items` will contain some elements from the current batch `items` and  some other elements from the arrays `pool1` and `pool2` depending on the `if-else` condition.  I can create `new_items` inside the function as it will keep changing but I can't do that for the other two. Here is a much simpler version:

```python

import tensorflow as tf
import numpy as np

pool1 = tf.TensorArray(dtype=tf.float32, size=0, dynamic_size=True)
pool2 = tf.TensorArray(dtype=tf.float32, size=0, dynamic_size=True)

def write_to_array(array, idx, item):
    array = array.write(idx, item)
    return array

@tf.function
def sampler(items, array1):
    num_items = tf.shape(items)[0]
    new_items = tf.TensorArray(dtype=tf.float32, size=0, dynamic_size=True)
    for i in tf.range(num_items):
        if array1.size() < 10:
            array1 = write_to_array(array1, i, items[i, :, :, :])
            new_items = write_to_array(new_items, i, items[i, :, :, :])
        else:
            new_items = write_to_array(new_items, i, items[i, :, :, :])
    return new_items.stack()

items = tf.convert_to_tensor(np.random.rand(2, 2, 2, 3).astype(np.float32))
sampler(items, pool1, new_items)
```

**Comment by nikitamaia** [comment]
Ah, okay. Linking to a few related issues below since this has been previously reported. It is a known limitation, and unfortunately for now the only workaround is to either convert the TensorArray to a Tensor before passing it as an argument or returning it, or moving the code that creates and uses the TensorArray inside the @tf.function.

#38454 #34683 #34683

**Comment by AakashKumarNain** [comment]
This seems to be a long standing issue. Is there any roadmap for this to track?

**Comment by nikitamaia** [comment]
There's no roadmap I can share that's tracking this bug. It's a known limitation (hence the error message) and I can certainly update this thread when there is any progress to support passing TensorArrays to a tf.function.

**Comment by AakashKumarNain** [comment]
Sure. That would be great help. Thanks @nikitamaia

**Comment by BichengWang** [comment]
Found same issue when I try to reproduce code:
https://github.com/tensorflow/docs/blob/master/site/en/tutorials/reinforcement_learning/actor_critic.ipynb

Is there any solution update on most recent version or alternative solution when compare tensor with value in the graph? 

And another thing I notice: when I execute it in [colab.reasearch.google.com](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/reinforcement_learning/actor_critic.ipynb) it could work.

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF v2.5 ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/5ad8ef27f224b8486ec8acd533f50ad0/untitled112.ipynb)..Thanks !

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
