### ISSUE TITLE
GPU memory issue with triton server 20.03 

### ISSUE THREAD

**Issue by loveppdog** [tensorflow/tensorflow#41759]
I know Tf uses Best-Fit with Coalescing to deal GPU memory. 
Some oom issues always happen when I inferences lots of models at the same time. So I just take some tests to check the issue. 

I have two models A/B trained by tenforflow1.13 and I inference by  triton server 20.03.

When I only load A model with warm up in triton sever, I find GPU memory is 3G.
When I only load B model with warm up in triton sever, I find GPU memory is 4G.
When I load A model and B model with warm up at the same time in triton sever, I find GPU memory is 4.1G. Why not 7G?

If I inference A/B at the same time, should GPU memory increase from 4.1G to 7G?

**Comment by gowthamkpr** [comment]
@loveppdog Can you please fill the issue template as shown [here](https://github.com/tensorflow/tensorflow/issues/new?labels=type%3Aperformance&template=80-performance-issue.md). Thanks!

**Comment by sanjoy** [comment]
How are you measuring the amount of allocated memory?  And does Triton share the same memory allocator between different inference models?

**Comment by loveppdog** [comment]
> How are you measuring the amount of allocated memory?  And does Triton share the same memory allocator between different inference models?
I just only run or load with warm-up one model and check gpu memory usage by nvidia-smi.
In general, the gpu memory usage remains unchanged after inference once.

About triton, it seems to deal gpu memory by different backends and some triton info likes the follows link:
https://github.com/NVIDIA/triton-inference-server/issues/1507#issuecomment-630926105
https://github.com/NVIDIA/triton-inference-server/issues/1499

**Comment by sanjoy** [comment]
> I just only run or load with warm-up one model and check gpu memory usage by nvidia-smi.

Does Triton run the inference models on different streams?  Or does it run them on a single stream?  If the latter then this is not surprising -- the TF memory allocator must be reusing memory allocated and freed by the first model for the second model.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
