### ISSUE TITLE
Encountered unresolved custom op: Slice.

### ISSUE THREAD

**Issue by zhaojc001** [tensorflow/tensorflow#41758]
I have converted pb to tflite,When I transplant algorithms,it appears the following error:
java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: Encountered unresolved custom op: Slice.
    Node number 0 (Slice) failed to prepare.
please help me.

**Comment by ravikyram** [comment]
@zhaojc001 

Can you add below 3 steps before converting would help.
```
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter.allow_custom_ops=True
converter.experimental_new_converter =True
tflite_model = converter.convert()
```
Also, request you to fill issue template  and share reproducible code in colab if you are still facing the issue.It helps us in localizing the issue faster.Thanks!
