### ISSUE TITLE
Please list XLA flags

### ISSUE THREAD

**Issue by bionicles** [tensorflow/tensorflow#41763]
## URL(s) with the issue:

https://www.tensorflow.org/xla

### Clear description

It's hard to find a list of XLA environment variables / flags, and examples of how/when to use them, like: 

```
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false"
os.environ["XLA_PYTHON_CLIENT_ALLOCATOR"] = "platform"
```

### Usage example

Usage examples are buried across many different open/closed github issues

Desired usage:

```
def run_agent_on_env(agent, env_name):
  env = gym.make(env_name)
  obs = env.reset()
  action = agent(obs) # how do you make this the only thing to run on XLA?
  obs, reward, done, info = env.step(action)
  # ... loop ... 
  return total_reward

def main():
  agents = get_agents()
  with futures.ProcessPoolExecutor() as pool:
      jobs = [pool.submit(run_agent_on_env, (agent, name)) for agent, name in ...]
      for future in futures.as_completed(jobs):
           # optimize stuff
           # log stuff
           # submit more jobs
```
Problem is, XLA runs OOM

### Request visuals, if applicable

XLA configuration often makes the difference between running, and not running code, given memory issues etc. A simple table of XLA environment variables / "flags" would be hugely useful for users 

### Submit a pull request?

I can't

**Comment by yil532** [comment]
Can I submit a PR to fix this? Thank you! @r4nt 
Where do you prefer to add the usage example? Could you be more specific on that? Such as before which section, which line... @bionicles

**Comment by yil532** [comment]
A question, where is the source code of this issue? I couldn't find where is the code pattern that I can create PR with. @ymodak

**Comment by bionicles** [comment]
Not sure about where to put it, it would be epic to have a function in tensorflow which lists the xla flags, or just a simple page of the docs with a table of them, I don't mind where it is, but XLA has a lot of feature flags and it's good if we can find the list!

**Comment by vaibhavarora102** [comment]
hi, @bionicles,
with reference to your above reply, what I understood is need of doc with listed XLA feature flags
correct me if I am wrong, as I am new to open source contribution
can I work on this if this is still open
thanks

**Comment by sachinprasadhs** [comment]
All the flags which are allowed are currently listed in the source code [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/jit/flags.cc#L82-L142) along with the description. You can refer the same.
If you want the same to be included in the document let us know, will create a PR for the same. Thanks!

**Comment by marcelroed** [comment]
Are there any updates on how to find the complete set of XLA flags? I'm using Jax and found a reference to

```
XLA_FLAGS=--xla_force_host_platform_device_count=N
```

Where can I find a list of the other flags I can use to control compilation or the runtime?

**Comment by bionicles** [comment]
clearly there are some missing flags, could these be extensions outside of the tensorflow repo, maybe in jax? 

@sachinprasadhs since these flags seem to control key aspects of XLA, it would be nice to have them well documented! 

I deployed a feature upgrade to `tree_plus` @marcelroed ... you can clone tensorflow/tensorflow and run 

`pip install -U tree_plus`
`cd tensorflow && tree_plus -g "**/*flags.cc" -i "third_party" -i "tools"` 

(tested and deployed this hour)

![image](https://github.com/tensorflow/tensorflow/assets/24532336/3fb6aa33-4c70-4a0d-bdfc-74254af9a6ed)
