### ISSUE TITLE
[TF 2.2.0] Error on creating optimizer slot variable under multi GPU training with tf.distribute.MirroredStrategy

### ISSUE THREAD

**Issue by DekraN** [tensorflow/tensorflow#41768]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: Red Hat Enterprise Linux Server release 7.6 (Maipo)
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): tensorflow/2.2.0--cuda--10.1
- Python version: 3.8.2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
- CUDA/cuDNN version: 10.1
- GPU model and memory: 4x Tesla V100-SXM2-16GB

**Describe the current behavior**
I am using Tensorflow 2.2.0 GPU with Tensorflow's Keras API for training a GAN model with multi GPU using Distributed Tensorflow MirroredStrategy. Under the mirrored strategy scope, I've:
- instantiated the model;
- defined the optimizer (tf.keras.optimizer.RMSProp);
- compiled the model with that optimizer.

In the train_step function I've defined the computational graph in Pythonic-way. I'm using Lazy mode (as opposed to the default TF2.0 eager mode and Keras graph mode) because TF warned me that running MirroredStrategy with eager execution still has overhead problems.
When the execution arrives to the apply_gradients call on the optimizer of my model, TF crashes reporting me this error:

`    ValueError: Trying to create optimizer slot variable under the scope for tf.distribute.Strategy (<tensorflow.python.distribute.distribute_lib._DefaultDistributionStrategy object at 0x20079d15d4f0>), which is different from the scope used for the original variable (MirroredVariable:{
      0: <tf.Variable 'conv2d_20/kernel:0' shape=(3, 3, 2, 2) dtype=float32>,
      1: <tf.Variable 'conv2d_20/kernel/replica_1:0' shape=(3, 3, 2, 2) dtype=float32>,
      2: <tf.Variable 'conv2d_20/kernel/replica_2:0' shape=(3, 3, 2, 2) dtype=float32>,
      3: <tf.Variable 'conv2d_20/kernel/replica_3:0' shape=(3, 3, 2, 2) dtype=float32>
    }). Make sure the slot variables are created under the same strategy scope. This may happen if you're restoring from a checkpoint outside the scope
`

**Describe the expected behavior**
The apply gradient should execute fine, because I've correctly defined the model and the optimizer under the MirroredStrategy object, as reported in: https://www.tensorflow.org/guide/distributed_training

**Standalone code to reproduce the issue**
https://pastebin.com/MyT6p1T8

**Other info / logs**

**Comment by nikitamaia** [comment]
Hi @DekraN, I've tried to run the code you've shared but am getting syntax errors. If I fix the syntax errors, I get the error `'Model' object has no attribute 'generator'` Can you please double check the code runs and provide it in Colab?

Additionally, although I am not able to run the code yet, there are a few things that stand out. Firstly the use of `tf.compat.v1.disable_eager_execution()` as we don't support custom losses in legacy graph mode (which is what you have if you disable eager mode). It is true that running MirroredStrategy with eager execution still has overhead problems, but that just means you need to wrap your distributed training step in a @tf.function (which it looks like you have done), and not disable eager execution all together.

Lastly, it doesn't look like you've distributed your dataset. As explained [here](https://www.tensorflow.org/guide/distributed_training#using_tfdistributestrategy_with_custom_training_loops), you'll need `tf.distribute.Strategy.experimental_distribute_dataset` when using MirroredStrategy with a custom training loop.
Happy to provide further support if you can share reproducible code.

**Comment by DekraN** [comment]
Greatly thanks for the answer! I was looking for a confirm regarding the execution modality to use in TF2.2.0. In fact, in my code I use custom losses, therefore I should use normal eager execution instead of legacy graph mode.
Now, after some other issues, I've been successful in executing with multi-GPU my code in eager execution
Sorry for the not reproducible code.

**Comment by Lion-William** [comment]
@DekraN Could you please tell me how exactly do you fix the code? I am encountering the same issues.
