### ISSUE TITLE
XLA_CPU_JIT unsupports  NonMaxSuppressionV2 ?

### ISSUE THREAD

**Issue by chaozju** [tensorflow/tensorflow#41761]
- Model: mtcnn downloaded [here](https://github.com/blaueck/tf-mtcnn)
- OS: Linux WSL 4.4.0-19041-Microsoft
- TensorFlow: Source code [@a50de3e](https://github.com/tensorflow/tensorflow/tree/a50de3e381ccb6d0b37a0bfe5d033cf312b53955)
- Python version: 2.7
- Bazel version: 0.11.0 (binary installer installed)

After hacking according to [this repo](https://github.com/nuchi/tf-to-xla-to-wasm)

cmd
```bash

bazel-bin/tensorflow/compiler/aot/tfcompile \
    --target_triple="wasm32-unknown-unknown-wasm" \
    --target_cpu="generic" \
    --xla_cpu_multi_thread_eigen=false \
    --graph="./mtcnn.pbtxt" \
    --config="./mtcnn_config.pbtxt" \
    --out_function_object="out_model.o" \
    --out_header="out_header.h" \
    --out_metadata_object="out_helper.o" \
    --cpp_class="MyClass"
```

log
``` bash
INVALID ARGUMENTS: Detected unsupported operations when trying to compile graph tfcompile on XLA_CPU_JIT:NonMaxSuppressionV2
```

**Comment by gowthamkpr** [comment]
@chaozju I think you are using an old version of tensorflow. Can you pleas use tensorflow 1.15 or 1.14 and let me know if the problem still persists. Thanks!
