### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by aamina-cybex** [tensorflow/tensorflow#41766]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
![pye1](https://user-images.githubusercontent.com/66160761/88523988-69234b00-d016-11ea-9c74-0b00bb25d371.PNG)

**Comment by Saduf2019** [comment]
@aamina-cybex 
Please provide with simple indented stand alone code and tf version such that we could replicate the issue faced or if possible share colab gist with the error faced.

With respect to the error reported refer to below links and let us know if it helps:
#36358 #29917 [link](https://stackoverflow.com/questions/43708541/python-typeerror-typeerror-not-supported-between-instances-of-nonetype)

**Comment by aamina-cybex** [comment]
Hi

I am new in GitHub so can you please guide me how to share complete code here. I did this python code in PyCharm.

**Comment by Saduf2019** [comment]
@aamina-cybex
please let us know if you referred to the links, you can attach files  as mention in below box "drag and drop or click and attach", or update the issue template, share a colab gist if possible with the error faced.

**Comment by aamina-cybex** [comment]
Hi
I have shared these codes as you advised. 

![p1](https://user-images.githubusercontent.com/66160761/88759391-529d0100-d188-11ea-894a-a9d3f1a180a1.PNG)
![p2](https://user-images.githubusercontent.com/66160761/88759392-53ce2e00-d188-11ea-8d72-51d30b171063.PNG)

**Comment by Saduf2019** [comment]
@aamina-cybex
Please provide with simple indented stand alone code and tf version such that we could replicate the issue faced in text format or if possible share colab gist with the error faced.
Also have you referred to the links shared with similar error.
