### ISSUE TITLE
MirroredStrategy with train_on_batch: Method requires being in cross-replica context, use get_replica_context().merge_call()

### ISSUE THREAD

**Issue by OdysseeT** [tensorflow/tensorflow#41773]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.4.0-dev20200727
- Python version: 3.8.3
- CUDA/cuDNN version: 10.2
- GPU model and memory: 2x GTX 1060 6Go

**Describe the current behavior**
When using **MirroredStrategy** with **train_on_batch**, I get the error that the **Method requires being in cross-replica context**
I have the same behavior with TF2.2, 2.3

The code is taken from issue #39270, and I added the wrapper `strategy.run`

**Describe the expected behavior**
To have the workload distributed across 2 GPUs

**Standalone code to reproduce the issue**
```
import tensorflow as tf

strategy = tf.distribute.MirroredStrategy()

with strategy.scope():
    (x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
    x_train, x_test = x_train / 255.0, x_test / 255.0
    train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(32)

    model = tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dense(10),
    ])

    model.compile(
        optimizer=tf.keras.optimizers.SGD(),
        loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
        metrics=['accuracy'])

def train_step(x, y):
    model.train_on_batch(x, y)
    
for x, y in train_dataset:
    strategy.run(train_step, args=(x, y,))
```

**Other info / logs** 
```
~/anaconda3/envs/distributed/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py in __enter__(self)
    385     # Allow this scope to be entered if this strategy is already in scope.
    386     if distribution_strategy_context.has_strategy():
--> 387       _require_cross_replica_or_default_context_extended(
    388           self._context.strategy.extended)
    389       self._same_scope_again_count += 1

~/anaconda3/envs/distributed/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py in _require_cross_replica_or_default_context_extended(extended)
    309     _wrong_strategy_scope(strategy, context)
    310   assert cross_replica is None
--> 311   raise RuntimeError("Method requires being in cross-replica context, use "
    312                      "get_replica_context().merge_call()")
    313 

RuntimeError: Method requires being in cross-replica context, use get_replica_context().merge_call()
```

[error.log](https://github.com/tensorflow/tensorflow/files/4983379/error.log)

**Comment by amahendrakar** [comment]
@OdysseeT,
Could you please take a look at [this](https://stackoverflow.com/a/61091830) StackOverflow comment form a similar issue and let us know if it helps. Thanks!

**Comment by OdysseeT** [comment]
@amahendrakar 
I spent 2 days on that post already... none of the proposed solutions worked for me. 
The major differences with my code are:
- I compile my model - where is the SO post he doesn't
- I'm using `train_on_batch` method - where in the SO post he's using the `__call__` method

**Comment by OdysseeT** [comment]
I took the same code as in the post (the working version), and I replaced the line:
`predictions = model(images, training=True)`
by
`predictions = model.train_on_batch(images)`

and I get the same error:

`RuntimeError: Method requires being in cross-replica context, use get_replica_context().merge_call()
`

Please note that I got intermediate errors before getting this one:
```RuntimeError: You must compile your model before training/testing. Use `model.compile(optimizer, loss)`.```
--> So I added `model.compile`

```RuntimeError: Detected a call to `Model.train_on_batch` inside a `tf.function`. `Model.train_on_batch is a high-level endpoint that manages its own `tf.function`. Please move the call to `Model.train_on_batch` outside of all enclosing `tf.function`s. Note that you can call a `Model` directly on `Tensor`s inside a `tf.function` like: `model(x)```
--> So I remove the `tf.function`

**Comment by OdysseeT** [comment]
My code worked with `model((x,y), training=True)`. So, it is coming from the `train_on_batch` method. Is it supported with **MirroredStrategy**?

**Comment by nikitamaia** [comment]
Hi @OdysseeT, `train_on_batch` indeed now works with MirroredStrategy as noted in the issue #39270. I'm curious why you added `strategy.run`, as you shouldn't need that unless you're using a custom training loop (and not using the Keras API)

**Comment by OdysseeT** [comment]
Hi @nikitamaia, thanks for your answer.
I have simplified the code here to reproduce the issue, but the full code is using a custom training loop.
I might be mistaken here. I thought I could use the loss returned by `train_on_batch` to compute the average loss from the global batch size. But from what you say, `train_on_batch` should not be used in `strategy.run`. Is that correct? Thanks

**Comment by nikitamaia** [comment]
`Model.train_on_batch` is a high level endpoint so I don't think it makes sense to use with `strategy.run` just like how you wouldn't wrap model.fit within `strategy.run`.

**Comment by OdysseeT** [comment]
Clear, thanks for the clarification.
