### ISSUE TITLE
Build TFLite with Flex Ops without Bazel 

### ISSUE THREAD

**Issue by aselva-eb** [tensorflow/tensorflow#41770]
Tensorflow Version: `2.4.0-dev20200712`
OS: Ubuntu 18.10 
(tensorflow/tensorflow docker)

Hello

Followed these instructions (C++ section) in the past to build a shared libtensorflowlite.so library
https://www.tensorflow.org/lite/guide/ops_select

```
Add the TensorFlow ops delegate library dependency to the build dependencies: tensorflow/lite/delegates/flex:delegate.
```

Problem is now I'm running into compatibility issues when I upload to the target device..

Few questions:
(1) How can I build a static library using the bazel pipeline? I used the `--config monolithic` flag but upon linking it still requires a newer glibc than my system supports
```bazel build --config=elinux_aarch64 --cpu=aarch64 --config=monolithic --cxxopt=--std=c++14 --define=with_select_tf_ops=true -c opt //tensorflow/lite:libtensorflowlite.so```

(2) How can I add the same flex op dependency to the makefile in lite/tools in order to build the lib without Bazel?

**Comment by ymodak** [comment]
What TF version you are using?

**Comment by aselva-eb** [comment]
> What TF version you are using?

2.4.0-dev20200712

Adding to my original post

**Comment by aselva-eb** [comment]
@thaink - would you happen to be able to support with my question (2) above?

**Comment by terryheo** [comment]
(1) We don't provide a rule to build static library via Bazel now. Doesn't shared library work for you? Could you share why?
(2) We don't have this path either.

If you want to build libtensorflowlite.so with Flex support, please apply the following patch.
https://github.com/terryheo/tensorflow/commit/cdb8f3045669ea7adcd7ac4b115b01f13f7dad6e

**Comment by aselva-eb** [comment]
Hi @terryheo - 

The problem is that the aarch64 toolchain that is provided uses a glibc version that is incompatible with my target. I was hoping to circumvent this through building the library statically . The shared library works for running on the host.

Do you have any suggestions? I tried to configure a new toolchain but ran into issues mid-compilation that wasn't so obvious for me to debug.

Thanks for the patch

**Comment by terryheo** [comment]
I see.
I'm wondering which target OS platform you're using. (also glibc version of the target) If it's popular, I might need to consider supporting it.

You can try new toolchain by referring https://github.com/tensorflow/tensorflow/commit/4961f18733ca3967198393abf419e14476b4a85c#diff-f37bff3c4001d49511871eb70980dc27 change. But right, it's not trivial to do it.

**Comment by aselva-eb** [comment]
It's an aarch64 linux target with glibc of 2.26.

Is it not trivial to add the flex dependency to the Makefiles as it is for a Bazel-based build?

**Comment by terryheo** [comment]
I see.
To build Flex delegate, it needs to build TF kernels. So until we have a way to build TF framework with Makefile, it's very difficult to build Flex delegate with Makefile.

**Comment by tilakrayal** [comment]
@aselva-eb,
As commented by the developer, please try to build TF Kernels and go for the Flex delegate. 

If you're using **Bazel** or [CMake](https://www.tensorflow.org/lite/guide/build_cmake) to build TensorFlow Lite interpreter, you can enable Flex delegate by linking a **TensorFlow Lite Flex delegate** shared library. You can build it with Bazel as the following command.

`bazel build -c opt --config=monolithic tensorflow/lite/delegates/flex:tensorflowlite_flex`

Also please take a look at this official document [link](https://www.tensorflow.org/lite/guide/ops_select) for the reference. Thank you!
