### ISSUE TITLE
why can i not install tensorflow library at python 3.8?

### ISSUE THREAD

**Issue by Motasem2000** [tensorflow/tensorflow#41774]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:2.2
- Python version:3.8
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow

**Provide the exact sequence of commands / steps that you executed before running into the problem**
pip install tensorflow==2.2
pip install tensorflow

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@Motasem2000 

What is the output of

```
pip list
pip --version
python -vv
python -w
```
In general you don't need to download the pip from storage.googleapis.com, a pip install tensorflow should be able to get it, assuming your Python is on 64 bits, your pip is up to date, you have the needed MSVC redistributable installed and that Python is installed from the Python website, not from Microsoft Marketplace (apparently, there is a bug with that).
Make sure your python was installed 64 bit.Thanks!
