### ISSUE TITLE
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, DEPTHWISE_CONV_2D, FAKE_QUANT, LOGISTIC, RESHAPE. Here is a list of operators for which you will need custom implementations: TFLite_Detection_PostProcess.

### ISSUE THREAD

**Issue by Dasinator21** [tensorflow/tensorflow#41786]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip installed
- TensorFlow version (or github SHA if from source): 1.15

**Provide the text output from tflite_convert**
I can make the tflite file by adding --allow_custom_ops at the end of the conversion code. toco --graph_def_file="C:\tensorflow5\models\research\object_detection\TFLite_model\tflite_graph.pb" --output_file=tflite_graph.tflite --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --input_shape=1,300,300,3 --input_array=normalized_input_image_tensor --output_array=TFLite_Detection_PostProcess:2 --inference_type=FLOAT --input_type=FLOAT --allow_custom_ops 
however when I run the model for inference, I get an runtime error saying node number 180 (TFLite_Detection_PostProcess) failed to prepare.
```
# Copy and paste here
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.[

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by mihaimaruseac** [comment]
Recommend trying in 2.3/nightly and also using a much readable title, not the full error message.

**Comment by ymodak** [comment]
You can also refer [tf lite object detection guide](https://www.tensorflow.org/lite/models/object_detection/overview) for your case.
