### ISSUE TITLE
Timeseries example and warning message with latest code: Executor start aborting: Invalid argument:

### ISSUE THREAD

**Issue by summa-code** [tensorflow/tensorflow#41781]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): Pulled from source on 27th EST
- TensorFlow version (use command below): Latest from source
- Python version: 3.8.1
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0
- GPU model and memory: TRX 2070

**Describe the current behavior**
When i run Timeseries example from Tensorflow.org, i get the following warning messages (a lot)

2020-07-27 14:23:21.829669: W tensorflow/core/common_runtime/executor.cc:1086] [/device:CPU:0] :  You must feed a value for placeholder tensor 'Placeholder/_1' with dtype double and shape [119759,72]
	 [[{{node Placeholder/_1}}]]

**Standalone code to reproduce the issue**
https://www.tensorflow.org/tutorials/structured_data/time_series#part_2_forecast_a_multivariate_time_series

**Comment by amahendrakar** [comment]
@summa-code,
On running the code with the latest TF-nightly, I did not face any errors or warnings. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/88001ef1ee580e1342e51cdf29bd6297/41781.ipynb). Thanks!

**Comment by summa-code** [comment]
I will try in the next build and let you know.

**Comment by summa-code** [comment]
They are gone, but another error or information started popping out,

I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:118] None of the MLIR optimization passes are enabled (registered 1)

**Comment by summa-code** [comment]
@amahendrakar This information is happening on TF 2.4, the original issue is gone. Should i file new one ?

**Comment by amahendrakar** [comment]
@summa-code,
Yes please. Please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
