### ISSUE TITLE
What do readers do after their input is exhausted?

### ISSUE THREAD

**Issue by danijar** [tensorflow/tensorflow#4178]
I would like to train for multiple epochs on a dataset, using TensorFlow readers and queues. How do reader signal the end of the dataset? I couldn't find any [documentation][1] on this.

[1]: https://www.tensorflow.org/versions/r0.10/api_docs/python/io_ops.html#readers

**Comment by tatatodd** [comment]
There's some useful documentation under the "How-Tos" section of the tensorflow.org site.  The one on "Reading Data" is most relevant to your question; in particular look here:
https://www.tensorflow.org/versions/r0.10/how_tos/reading_data/index.html#aside-how-clean-shut-down-when-limiting-epochs-works

FYI we use github issues primarily for bugs and installation issues.  In the future please ask these types of questions on StackOverflow and tag it with the `tensorflow` tag.  Thanks!
