### ISSUE TITLE
RuntimeError: tensorflow/lite/kernels/detection_postprocess.cc:158 NumOutputs(node) != 4 (3 != 4)Node number 180 (TFLite_Detection_PostProcess) failed to prepare.

### ISSUE THREAD

**Issue by Dasinator21** [tensorflow/tensorflow#41787]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip install -ignore-installed --upgrade tensorflow-gpu==1.15
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**
FULL ERROR
C:\Users\Sreed\Anaconda3\envs\tensorflow2\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Sreed\Anaconda3\envs\tensorflow2\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
C:\Users\Sreed\Anaconda3\envs\tensorflow2\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  stacklevel=1)
2020-07-27 23:06:48.543673: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Traceback (most recent call last):
  File "TFLite_detection_webcam.py", line 140, in <module>
    interpreter.allocate_tensors()
  File "C:\Users\Sreed\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow_core\lite\python\interpreter.py", line 244, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "C:\Users\Sreed\Anaconda3\envs\tensorflow2\lib\site-packages\tensorflow_core\lite\python\interpreter_wrapper\tensorflow_wrap_interpreter_wrapper.py", line 106, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: tensorflow/lite/kernels/detection_postprocess.cc:158 NumOutputs(node) != 4 (3 != 4)Node number 180 (TFLite_Detection_PostProcess) failed to prepare.
```
# Copy and paste here
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

Code from https://raw.githubusercontent.com/EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi/master/TFLite_detection_webcam.py by someone else. 
Right now have a detect.tflite file as well as a labelmap.txt file

**Comment by Saduf2019** [comment]
@Dasinator21 
Can you please share simple indented stand alone code such that we can replicate the issue faced or if possible provide colab gist with the code and error.

**Comment by Dasinator21** [comment]
https://github.com/Dasinator21/Replicate-Error
This will hopefully allow someone to get to the same error.

**Comment by Saduf2019** [comment]
@Dasinator21 
Please provide with a colab gist with the error faced for us to analyse the issue faced or simple stand lone code for us to replicate.
