### ISSUE TITLE
failed call to cuInit: UNKNOWN ERROR (-1)

### ISSUE THREAD

**Issue by prismspecs** [tensorflow/tensorflow#41785]
Running the latest docker with:

    docker run -it -p 8888:8888 tensorflow/tensorflow:latest-gpu-jupyter jupyter notebook --notebook-dir=/tf --ip 0.0.0.0 --no-browser --allow-root --NotebookApp.allow_origin='https://colab.research.google.com'

code:

    import tensorflow as tf
    print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

gives me:

    2020-07-27 19:44:03.826149: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
    2020-07-27 19:44:03.826179: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (-1)
    2020-07-27 19:44:03.826201: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] no NVIDIA GPU device is present: /dev/nvidia0 does not exist

I'm on Pop_OS 20.04, have tried installing the CUDA drivers from the Pop repository as well as from NVidia. No dice. Any help appreciated.

Running 

    docker run --gpus all nvidia/cuda:10.0-base nvidia-smi

gives me:

    +-----------------------------------------------------------------------------+
    | NVIDIA-SMI 450.51.05    Driver Version: 450.51.05    CUDA Version: 11.0     |
    |-------------------------------+----------------------+----------------------+
    | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
    | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
    |                               |                      |               MIG M. |
    |===============================+======================+======================|
    |   0  GeForce RTX 2080    On   | 00000000:09:00.0  On |                  N/A |
    |  0%   52C    P5    15W / 225W |    513MiB /  7959MiB |     17%      Default |
    |                               |                      |                  N/A |
    +-------------------------------+----------------------+----------------------+
                                                                                   
    +-----------------------------------------------------------------------------+
    | Processes:                                                                  |
    |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
    |        ID   ID                                                   Usage      |
    |=============================================================================|
    +-----------------------------------------------------------------------------+

**Comment by amahendrakar** [comment]
@prismspecs,
Please check if [this comment](https://github.com/NVIDIA/nvidia-docker/issues/1330#issuecomment-664069187) from your issue in the NVIDIA repo works.

Also, please take a look at [this thread](https://gridforums.nvidia.com/default/topic/10801/general-discussion/unable-to-run-tensorflow-with-vgpu/post/16395/#16395) on the NVIDIA forum and let us know if it helps. Thanks!

**Comment by prismspecs** [comment]
I simply needed to add --gpus all

I feel like this should be default since it's a GPU based docker image no?

Thanks!

**Comment by amahendrakar** [comment]
@prismspecs,
Is this still an issue? Always refer to the [official guide](https://www.tensorflow.org/install/docker#gpu_support) while installing TensorFlow. 

Please feel free to close the issue if resolved. Thanks!
