### ISSUE TITLE
Keras saves invalid JSON files containing Infinity

### ISSUE THREAD

**Issue by lutzroeder** [tensorflow/tensorflow#41797]
**Describe the current behavior**

JSON saved by Keras contains `Infinity` which is invalid according to [RFC 7159](https://tools.ietf.org/html/rfc7159):

> "Numeric values that cannot be represented in the grammar below (such as Infinity and NaN) are not permitted."

**Describe the expected behavior**

Keras saves correct JSON format.

**Standalone code to reproduce the issue** 

```
from tensorflow import keras
input = keras.Input(shape=(1))
x = keras.backend.sqrt(input)
model = keras.Model(input, x)
model.compile(optimizer='adam', loss='mse')
with open('repro.json', 'w') as json_file:
    json_file.write(model.to_json())
```

```
~ node
> JSON.parse(require('fs').readFileSync('repro.json', 'utf-8'))
Uncaught SyntaxError: Unexpected token I in JSON at position 508
```

[repro.zip](https://github.com/tensorflow/tensorflow/files/4985883/repro.zip)

tensorflow/tensorflow#37196
lutzroeder/netron#553

@goldiegadde @howl-anderson

**Comment by ravikyram** [comment]
@lutzroeder 

In the JSON file you uploaded I see a value named `infinity `but there is no value `identity.`
On running the code in colab with TF 2.2 I see neither `infinity` nor `identity`. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/a9f1d86821c63ef8227129b3e710dcb2/untitled191.ipynb).Thanks!

**Comment by lutzroeder** [comment]
@ravikyram good catch, corrected to `Infinity`.

This does repro in `tensorflow 2.3.0` on macOS and @imxieyi reported lutzroeder/netron#553 for `Keras v2.2.4-tf`.

**Comment by howl-anderson** [comment]
I think it is the same issue as #37196, I will have a deep look at it.
