### ISSUE TITLE
Golang Tensorflow v2.3.0 installation fails

### ISSUE THREAD

**Issue by jobale** [tensorflow/tensorflow#41808]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux-4.19.0-9-amd64-x86_64-with-debian-10.4
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: 
-   **TensorFlow installed from (source or binary)**: Not installed (golang go command pull tensorflow from github)
-   **TensorFlow version (use command below)**: 2.3.0 (same bug in 2.2.0)
-   **Python version**:  2.7.16 (but python 3.7 is installed too)
-   **Bazel version (if compiling from source)**: 3.1.0
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:
-   **GPU model and memory**:
-   **Exact command to reproduce**: go get github.com/tensorflow/tensorflow/tensorflow/go

### Describe the problem
BUG --- As in tensorflow-go@v2.2.0, tensorflow-go@v2.3.0 fail at installation.

### Source code / logs
From inside GOPATH:
go: found github.com/tensorflow/tensorflow/tensorflow/go in github.com/tensorflow/tensorflow v2.3.0+incompatible
go: finding module for package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto
go: finding module for package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto
../../go/pkg/mod/github.com/tensorflow/tensorflow@v2.3.0+incompatible/tensorflow/go/saved_model.go:25:2: module github.com/tensorflow/tensorflow@latest found (v2.3.0+incompatible), but does not contain package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto

From inside a go.mod compliant directory:
go: found github.com/tensorflow/tensorflow/tensorflow/go in github.com/tensorflow/tensorflow v2.3.0+incompatible
go: finding module for package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto
go: finding module for package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto
../../go/pkg/mod/github.com/tensorflow/tensorflow@v2.3.0+incompatible/tensorflow/go/saved_model.go:25:2: module github.com/tensorflow/tensorflow@latest found (v2.3.0+incompatible), but does not contain package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto

Looks like exactly the same old bug from tensorflow@v2.2.0 from this issue: https://github.com/tensorflow/tensorflow/issues/39307

**Comment by naspredam** [comment]
Happened the same for me... in order to use go with tensorflow I used the 1.15.0 as go dependency.

But still, not sure why the 2.x it is not working... as it seems that for python 3.8 it should use only 2.2+

**Comment by batara666** [comment]
confirmed, urgently need fix

**Comment by batara666** [comment]
this broke the whole go tensorflow

**Comment by rubens21** [comment]
Same issue here :( 
And it is not happening only in 2.3. It is affecting all 2.* versions.

I found discussions https://github.com/tensorflow/tensorflow/issues/39744 and here https://github.com/tensorflow/tensorflow/pull/40752

There was a PR (https://github.com/tensorflow/tensorflow/commit/e5e495db7bee77cd0fd5dda3b06bd743cbcf1ef8) the supposedly would fix the issue, but I checkout master and tested it, and I got the same error.

@jhseu since your changes are not in a tag yet, I tested using master branch. I got the same error.
I followed the steps in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/README.md, and I did not found the proto files in the Go code (in src/github...), they were generated inside Bazel cache directories.

I believe the problem is that Bazel is generating the files, so they are created inside Bazel building dirs (bazel-tensorflow/tensorflow/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto).

Should we have a script to generate the files within the golang code?
I am trying to make it work in my environment by generating the proto files, but I am having other issues because the importing path from other libs... 

Help, please :(

**Comment by rubens21** [comment]
Well, it is working for me now, but I had to do some hacks to make it works.

First, differently of what I said in the comment above, we do have a script that generates the proto files outside Bazel dir, however it only generates inside a vendor dir (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/genop/generate.sh#L70).

These are the steps I followed to make it works in my environment

0. Follow the steps described on https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/README.md#build
0. The `3.a` (Copying it to a system location) step will fail, you must copy `libtensorflow_framework.so.2` instead of `libtensorflow_framework.so` 
0. The step 4 (generate **and** test) also will fail, but no worries, keep going...
0. Now run these commands inside `${GOPATH}/src/github.com/tensorflow/tensorflow/`
   ```
   cp -R tensorflow/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core tensorflow/go/core
   cp -R tensorflow/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/stream_executor tensorflow/go/
   ```
0. Run the tests again `go test github.com/tensorflow/tensorflow/tensorflow/go`, if you get the error saying "_libtensorflow.so.2: cannot open shared object file: No such file or directory_", may need to execute the step 3.b instead of the 3.a

Assuming the test is passing, you may continue.

If your Go project is using Go modules ON, you will have to:

0. Force Go to use the local directory instead of importing it. So, add this to your go.mod file:
   ```
   replace github.com/tensorflow/tensorflow => [your absolute Gopath]/src/github.com/tensorflow/tensorflow
   ```
0. Force `github.com/tensorflow/tensorflow` looks like a Go module project. 
   ```
   cd  ${GOPATH}/src/github.com/tensorflow/tensorflow/
   go mod init github.com/tensorflow/tensorflow
   ```

Just keep in mind that it is a workaround. I did it because the bug was blocking me.

**Comment by robmir44** [comment]
^^ i don't undestand why tensorflow makes problems? golang is product from google, tensorflow is prodact from google :/ 
My question is, is the problem so hard that the bug fix takes so long time?

**Comment by jhseu** [comment]
This is actually fixed at master following the instructions at:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/README.md

The fix didn't make it into TensorFlow 2.3. (The `go get -d` command will warn about package not found, but you can ignore it since it's built with `go generate`)

Note that you _must_ build an updated version of libtensorflow.so as indicated in the instructions, otherwise you'll get errors.

**Comment by EricLi404** [comment]
> This is actually fixed at master following the instructions at (just ran the commands just now to verify):
> https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/README.md
> 
> The fix didn't make it into TensorFlow 2.3. (The `go get -d` command will warn about package not found, but you can ignore it since it's built with `go generate`)
> 
> Note that you _must_ build an updated version of libtensorflow.so as indicated in the instructions, otherwise you'll get errors.

Do you have a plan for: 
- make the fix into a release
- offer a new libtensorflow.so in [google cloud platform](https://console.cloud.google.com/storage/browser/vml-tf-lib;tab=objects?project=dev-vml-cm&prefix=&forceOnObjectsSortingFiltering=false)

**Comment by shravanshetty1** [comment]
I hope this can be easily go gettable soon....

**Comment by iliailmer** [comment]
Hi, when I follow the build instructions, I get ` libtensorflow_framework.2.5.0.dylib` and `libtensorflow_framework.2.dylib` but no `libtensorflow_framework.2.so` in my `${GOPATH}/src/github.com/tensorflow/tensorflow/bazel-bin/tensorflow/` directory and i'm not sure why, has anyone had this problem?

**Comment by batara666** [comment]
yeah folks, we need this library  **go gettable**

**Comment by domino14** [comment]
can we please fix this, i don't want to do any of these hacks on prod

**Comment by zxpan** [comment]
How hard to release this? it has been a while for this issue.

**Comment by domino14** [comment]
Yes please. I spent most of the day trying to build this and am stuck. Proto compiler refuses to use the include directory on my computer to find those common protos (like Any, etc). Help!

**Comment by rubens21** [comment]
> Hi, when I follow the build instructions, I get ` libtensorflow_framework.2.5.0.dylib` and `libtensorflow_framework.2.dylib` but no `libtensorflow_framework.2.so` in my `${GOPATH}/src/github.com/tensorflow/tensorflow/bazel-bin/tensorflow/` directory and i'm not sure why, has anyone had this problem?
> Edit: for me, everything after step 4 fails with
> 
> ```
> tensorflow/go/saved_model.go:25:2: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto" in any of:
> 	/usr/local/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOROOT)
> 	/Users/<user>/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOPATH)
> ```

@iliailmer did you try the steps I suggested above? I got the same error too. Those steps should work around that.

**Comment by domino14** [comment]
> > Hi, when I follow the build instructions, I get ` libtensorflow_framework.2.5.0.dylib` and `libtensorflow_framework.2.dylib` but no `libtensorflow_framework.2.so` in my `${GOPATH}/src/github.com/tensorflow/tensorflow/bazel-bin/tensorflow/` directory and i'm not sure why, has anyone had this problem?
> > Edit: for me, everything after step 4 fails with
> > ```
> > tensorflow/go/saved_model.go:25:2: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto" in any of:
> > 	/usr/local/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOROOT)
> > 	/Users/<user>/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOPATH)
> > ```
> 
> @iliailmer did you try the steps I suggested above? I got the same error too. Those steps should work around that.

hi @rubens21, how did you get the protobuf to build?

```
✘-1 ~/go/src/github.com/tensorflow/tensorflow [master ↓·81|…48]
10:48 $ go generate github.com/tensorflow/tensorflow/tensorflow/go/op
google/protobuf/any.proto: File not found.
google/protobuf/duration.proto: File not found.
tensorflow/core/protobuf/autotuning.proto:10:1: Import "google/protobuf/any.proto" was not found or had errors.
tensorflow/core/protobuf/autotuning.proto:11:1: Import "google/protobuf/duration.proto" was not found or had errors.
tensorflow/core/protobuf/autotuning.proto:61:3: "google.protobuf.Duration" is not defined.
tensorflow/core/protobuf/autotuning.proto:74:3: "google.protobuf.Any" is not defined.
../genop/generate.go:19: running "bash": exit status 1
tensorflow/go/op/generate.go:17: running "go": exit status 1
```

My /usr/local/include has the right paths (`google/protobuf/any.proto` etc)

**Comment by domino14** [comment]
I finally got the protobuf to build by copying the `/usr/local/include/google` directory (which has the protobuf include files) to my `${GOPATH}/src/github.com/tensorflow/tensorflow" directory. I don't know why it needs to look there, or why it wasn't there. However, I get another error:

```
15:27 $ go generate github.com/tensorflow/tensorflow/tensorflow/go/op
dyld: Symbol not found: __ZN10tensorflow10FileSystem10FilesExistERKNSt3__16vectorINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS6_IS8_EEEEPNS2_INS_6StatusENS6_ISD_EEEE
  Referenced from: /usr/local/lib/libtensorflow.2.dylib
  Expected in: /usr/local/lib/libtensorflow_framework.2.dylib
 in /usr/local/lib/libtensorflow.2.dylib
signal: abort trap
tensorflow/go/op/generate.go:18: running "go": exit status 1
```

**Comment by mrene** [comment]
@domino14 protoc looks at all the paths passed to protoc with the -I option, in this case it's called from the bash script in `genop/generate.sh` - you can always adjust the include paths there.

Symbol errors like this are often mismatches between header files and compiled binaries, make sure you used a released version instead of building from master.

Since you've been at it for quite some time, I can share the temporary solution that we're using until the issue is fixed - I basically [forked the bindings and included the generated protos](https://github.com/zia-ai/tensorflow-go), if it helps you feel free to use it and replace the dep inside your go.mod file as such:

```
replace github.com/tensorflow/tensorflow v2.3.1 => github.com/zia-ai/tensorflow-go v2.3.1
```

There's a matching [official pre-build C library](https://www.tensorflow.org/install/lang_c) available.

**Comment by domino14** [comment]
@mrene thank you. I did that and got this error:

```
/src/go.mod:19: replace github.com/zia-ai/tensorflow-go: version "v2.3.1" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

**Comment by go-dockly** [comment]
you have to change the tag to v1.0.0 that worked for me somehow go does not pick up on the v2.3.1 zia-ai git tag

**Comment by giautm** [comment]
Hey, I just want to share.
> "libtensorflow.so.2: cannot open shared object file: No such file or directory"

To resolve this error, you need setting LIBRARY_PATH/LD_LIBRARY_PATH point to `/usr/local/lib`. I found this instruction from stackoverflow https://stackoverflow.com/a/57156500

**Comment by janhartman** [comment]
Hey, has there been any progress on this? It would be really nice if this was fixed in the official TF repo so it's usable OOTB - I'd rather not use forks or mess with building protobufs by myself.

**Comment by galeone** [comment]
Since this issue isn't getting fixed, I decided to maintain a fork: https://github.com/galeone/tensorflow

```
go get github.com/galeone/tensorflow/tensorflow/go@r2.4-go
```

You can also use [tfgo](https://github.com/galeone/tfgo) that depends on the fork and it allows a simplified usage of the Go bindings:

```
go get github.com/galeone/tfgo
```

**Comment by shankernaik** [comment]
I am using tensorflow 2.4.0, this one worked for me.

While configuring the env variables for linker from https://www.tensorflow.org/install/lang_c. instead try Absolute path as below
```
export LIBRARY_PATH=/mydir/lib
export DYLD_LIBRARY_PATH=/mydir/lib
```

This worked for me, caching the go package here.
```
shankernaik$ go test github.com/tensorflow/tensorflow/tensorflow/go
# github.com/tensorflow/tensorflow/tensorflow/go.test
ld: warning: directory not found for option '-L/Users/shankernaik/Users/shankernaik/libtensorflow-cpu-darwin-x86_64-2.4.0'
ok  	github.com/tensorflow/tensorflow/tensorflow/go	(cached)
```

**Comment by 9nut** [comment]
@galeone @jhseu is this a correct summary of the issue and work-around?

Some of the modules that are required for using TF from Go are artifacts that are generated during the TF build process (therefore, NOT checked into the repository). Go module processing expects to "get" those modules from their "import" paths;  but, obviously, it can't find them.  The solution is to build the library, and generate the Go modules, locally and map the well-known path to the local copy using go.mod "replace".

**Comment by giautm** [comment]
Hi, I have some comments to share.

First, I starting my application by trying to use TensorFlow API directly in Go. In development environment, I used [DevContainer to run Go code](https://github.com/giautm/tensorflow-go-example) with TensorFlow in binary. But, when I trying to deploy my application to production mode. I realize that TensorFlow is too big to be deployed with the same application. (Docker image contain TensorFlow & application will have > 1.2GB for size).

So, I try to using another way to use TensorFlow in my app. `tensorflow/serving:2.4.0` has 76.62 MB for size, then with GPU is 3.44 GB. It's a great option to deploy your app to production environment. (76.62MB for TensorFlow + ~10 MB for application). ;)

**Comment by kekeimiku** [comment]
2021 is half past

**Comment by galeone** [comment]
> 2021 is half past

Here's the working available solution: https://github.com/tensorflow/tensorflow/issues/41808#issuecomment-779766175

**Comment by lastzero** [comment]
Speechless.

**Comment by domino14** [comment]
right?

**Comment by rubens21** [comment]
> Speechless.

yup. And disappointing.

**Comment by giautm** [comment]
@jhseu Well done. 🙄🙄

**Comment by deslum** [comment]
Not works.

**Comment by michele-sama-dialpad** [comment]
Having the same issue :/
Yes can be worked around but still not pleasant

**Comment by galeone** [comment]
> Having the same issue :/ Yes can be worked around but still not pleasant

```
go get github.com/galeone/tfgo
```

This project depends on the fork I maintain (galeone/tensorflow) that is go-gettable

**Comment by lastzero** [comment]
See:
-  #53549

**Comment by baothg** [comment]
`go: finding module for package github.com/tensorflow/tensorflow/tensorflow/go
go: found github.com/tensorflow/tensorflow/tensorflow/go in github.com/tensorflow/tensorflow v2.7.0+incompatible
go: finding module for package github.com/tensorflow/tensorflow/tensorflow/go/core/framework/types_go_proto
go: finding module for package google.golang.org/protobuf/proto
go: finding module for package github.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor_shape_go_proto
go: finding module for package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto
go: found google.golang.org/protobuf/proto in google.golang.org/protobuf v1.27.1
go: finding module for package github.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor_shape_go_proto
go: finding module for package github.com/tensorflow/tensorflow/tensorflow/go/core/framework/types_go_proto
go: finding module for package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto
golang/database imports
	github.com/tensorflow/tensorflow/tensorflow/go imports
	github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto: module github.com/tensorflow/tensorflow@latest found (v2.7.0+incompatible), but does not contain package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto
golang/database imports
	github.com/tensorflow/tensorflow/tensorflow/go tested by
	github.com/tensorflow/tensorflow/tensorflow/go.test imports
	github.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor_shape_go_proto: module github.com/tensorflow/tensorflow@latest found (v2.7.0+incompatible), but does not contain package github.com/tensorflow/tensorflow/tensorflow/go/core/framework/tensor_shape_go_proto
golang/database imports
	github.com/tensorflow/tensorflow/tensorflow/go tested by
	github.com/tensorflow/tensorflow/tensorflow/go.test imports
	github.com/tensorflow/tensorflow/tensorflow/go/core/framework/types_go_proto: module github.com/tensorflow/tensorflow@latest found (v2.7.0+incompatible), but does not contain package github.com/tensorflow/tensorflow/tensorflow/go/core/framework/types_go_proto
`

go version go1.17.6 darwin/arm64

Is there any solution yet?

**Comment by galeone** [comment]
There's no prebuild C library for arm64: https://www.tensorflow.org/install/lang_c

Hence not even [tfgo](https://github.com/galeone/tfgo) supports this

**Comment by mohantym** [comment]
Hi @jobale ! Could you check this [document ](https://github.com/tensorflow/build/tree/master/golang_install_guide)for go-lang installation of Tensorflow. Please post your query [here](https://github.com/tensorflow/build/issues) for further assistance. Thank you!

**Comment by domino14** [comment]
This is definitely not stale if the repo cannot be go-gotten.

**Comment by lastzero** [comment]
Safe to assume that *Python* snake folks hate *Gophers* and other rodents.

I mean, we had such a good start and now this... 🙄

![tensorgologo](https://user-images.githubusercontent.com/301686/174059259-3ead1661-b1a6-4228-a560-5794a1c4c30f.png)

**Comment by galeone** [comment]
> ![tensorgologo](https://user-images.githubusercontent.com/301686/174059259-3ead1661-b1a6-4228-a560-5794a1c4c30f.png)
lol I'm the one that created that ugly pic :smile: 

Anyway, the only solution is to use my fork and my project.

See this comment: https://github.com/tensorflow/tensorflow/issues/41808#issuecomment-779766175

My fork is go-gettable, and tfgo uses my fork under the hood.

**Comment by lastzero** [comment]
@galeone This is getting a bit off-topic, but anyway: Should you consider updating your fork to the then latest version in the upcoming weeks/months, please [let me/us know](https://github.com/photoprism/photoprism). Waiting is fine if it saves us from having to upgrade to a new TF version twice in short order. In our specific situation, this includes building and distributing new C libs for all supported architectures and operating systems, thus I mentioned it.

I could then also help with testing, documentation, or fixing minor issues. We are in no hurry, as there is more than enough other work for us to do in the foreseeable future.

**Comment by galeone** [comment]
@lastzero I'll do - I have some other projects going on right now, but whenever I'll work on tfgo and galeone/tensorflow I'll ping you there

**Comment by tenhan** [comment]
I am facing the similar problem:
```
go get -d github.com/tensorflow/tensorflow/tensorflow/go                                                                                                                                 ─╯
github.com/tensorflow/tensorflow/tensorflow/go imports
	github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto: cannot find module providing package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto
```
Is this will be fixed?

**Comment by tenhan** [comment]
I am facing the similar problem:
```
go get -d github.com/tensorflow/tensorflow/tensorflow/go                                                                                                                                 ─╯
github.com/tensorflow/tensorflow/tensorflow/go imports
	github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto: cannot find module providing package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto
```
Is this will be fixed?

**Comment by galeone** [comment]
> I am facing the similar problem:
> 
> ```
> go get -d github.com/tensorflow/tensorflow/tensorflow/go                                                                                                                                 ─╯
> github.com/tensorflow/tensorflow/tensorflow/go imports
> 	github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto: cannot find module providing package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto
> ```
> 
> Is this will be fixed?

Use tfgo or galeone/tensorflow 
https://github.com/tensorflow/tensorflow/issues/41808#issuecomment-1007418081

**Comment by galeone** [comment]
FYI I updated https://github.com/galeone/tensorflow to TensorFlow 2.10 (https://github.com/galeone/tensorflow/tree/r2.10-go)

You can update via `go get -u github.com/galeone/tensorflow/tensorflow/go@r2.10-go`

Moreover, if you use (or plan to use) [galeone/tfgo](https://github.com/galeone/tfgo) the dependency of tfgo on galeone/tensorflow is already updated.

**Comment by SuryanarayanaY** [comment]
Hi @jobale ,

Tensorflow Golang instructions has been maintained by a community member.Please find the attached [source](https://github.com/tensorflow/build/tree/master/golang_install_guide).
The source is updated till 2.11 version.

As TF 2.3 version is not actively supported, Please try with latest version by following the instructions in above source and let us know if having any problems there. Thanks!

**Comment by SuryanarayanaY** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks.
