### ISSUE TITLE
Converting MediaPipe Handpose model to TFLite model

### ISSUE THREAD

**Issue by akshayvernekar** [tensorflow/tensorflow#41800]
HI team,

I am developing an embedded IOT device and I wanted to use the Handpose model for hand-tracking and gesture recognition but I didnt yet find a guide for converting Mediapipe models to TFLite model. Could you please provide a guide if its possible.

Thanks

**Comment by rmothukuru** [comment]
@akshayvernekar,
I have transferred this issue from TF Hub repository to TF Lite Repository, as the issue is related to Lite.

**Comment by ymodak** [comment]
@akshayvernekar Did you get a chance to look at [mediapipe/models](https://github.com/google/mediapipe/tree/master/mediapipe/models)?
For hand detection models see https://github.com/google/mediapipe/tree/master/mediapipe/models#hand-detection-and-tracking

**Comment by akshayvernekar** [comment]
Thanks @ymodak this is exactly what I was looking for, the repository has the necessary .tflite files .

**Comment by ymodak** [comment]
Glad I could help. Closing this issue now. Thanks!

**Comment by TheBricktop** [comment]
@ymodak link provided is void
the tflite model for hands was deleted from repo

**Comment by kinivi** [comment]
The same problem, model was deleted

**Comment by kinivi** [comment]
@TheBricktop I found this https://github.com/google/mediapipe/blob/master/mediapipe/modules/palm_detection/palm_detection.tflite

**Comment by TheBricktop** [comment]
@kinivi do you have any idea how to convert pbtx to tflite? I need it for gpu accelerated palm and hand landmark

**Comment by kinivi** [comment]
@TheBricktop I can mislead, but I think you can use tflite model with GPU acceleration just by checking one parameter in the interpretator.

**Comment by sgowroji** [comment]
Hand tflite https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark.tflite

**Comment by jepious** [comment]
Hello, the tflite model for hands was deleted from repo.
Could anyone please help me?
