### ISSUE TITLE
Is there any document for running a model which is built by tf.estimator by tf-serving ?

### ISSUE THREAD

**Issue by DachuanZhao** [tensorflow/tensorflow#41814]
The same [stackoverflow](https://stackoverflow.com/questions/63069621/tensorflow-serving-can-run-a-model-built-by-tensorflow-estimator)

**Comment by Saduf2019** [comment]
@DachuanZhao 
Please refer to [this link](https://www.tensorflow.org/tfx/guide/serving) and confirm.

**Comment by DachuanZhao** [comment]
> @DachuanZhao
> Please refer to [this link](https://www.tensorflow.org/tfx/guide/serving) and confirm.

There isn't an example , either .

**Comment by DachuanZhao** [comment]
> @DachuanZhao
> Please refer to [this link](https://www.tensorflow.org/tfx/guide/serving) and confirm.

I can find an example which shows how to running a model which is built by tf.keras by  tf-serving  at this [link](https://www.tensorflow.org/tfx/serving/serving_basic) , but I can't find a tf.estimator example .

**Comment by ymodak** [comment]
@DachuanZhao Please take a look at this [thread](https://branyang.gitbooks.io/tfdocs/content/get_started/export.html)
Also see section `Serving the exported model locally` in the above thread.
