### ISSUE TITLE
Document events file format

### ISSUE THREAD

**Issue by malmaud** [tensorflow/tensorflow#4181]
Hello,
In the documentation for Tensorboard, I can't find a description for the format of the events file beyond that it contains Event protobufs. Is it recordio? Are there any tools for writing event files for 3rd-party Tensorflow clients that aren't using the Python API?

**Comment by tatatodd** [comment]
The code that manages writing out the events file is tf.train.SummaryWriter (Python), which is defined here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/summary_io.py

It uses the tensorflow::EventsWriter (C++) class to actually write each file:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/util/events_writer.cc

The underlying file format is indeed recordio.  I don't believe there are any special tools for writing Tensorboard events files; you're just supposed to use the tf.train.SummaryWriter Python class.

@danmane probably has an opinion on using Tensorboard with non-Python clients.

**Comment by danmane** [comment]
It's close to recordio, but it is actually "tfrecord" It has a few differences from recordio so a standard recordio reader won't work.

If you want to write events without using the python api, you should use the tensorflow::EventsWriter class, like tatatodd suggested. 

Please feel free to submit a pull request improving the documentation :)

**Comment by jart** [comment]
This issue has been migrated to https://github.com/tensorflow/tensorboard/issues/72.
