### ISSUE TITLE
[Doc] Are partial batches supported with MultiWorkerMirroredStrategy

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#41812]
## URL(s) with the issue:

- https://github.com/tensorflow/tensorflow/releases/tag/v2.3.0
- https://www.tensorflow.org/tutorials/distribute/input#partial_batches

## Description of issue (what needs changing):

The release note states 
> tf.distribute.experimental.MultiWorkerMirroredStrategy adds support for partial batches.

However the documentation/tutorial states
> Currently this is supported for all strategies except tf.distribute.experimental.MultiWorkerMirroredStrategy.
> [...] Partial batches are supported for all strategies except tf.distribute.experimental.MultiWorkerMirroredStrategy.

This sounds like those contradict each other. What is the actual reality? Can the documentation or the release notes be updated to clarify?

**Comment by nikitamaia** [comment]
Hi @Flamefire, thanks for pointing this out. Partial batches are now supported with MWMS. A documentation change has just been submitted and I will update this thread when it goes through.

**Comment by nikitamaia** [comment]
Closing this issue now because [documentation](https://www.tensorflow.org/tutorials/distribute/input#partial_batches) has been updated to be consistent with the release notes. Thanks again for spotting this one!
