### ISSUE TITLE
esp - No rule to make target person_detect_model_data.cc

### ISSUE THREAD

**Issue by cgreening** [tensorflow/tensorflow#41818]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

macOS Catalina - 10.15.5 (19F101)

- TensorFlow installed from (source or binary):

source cloned from git - have tried r2.2, r2.3 and master

- Tensorflow version (commit SHA if source):

f295633406569f9a6ee71467a9bb34ef1cc6852b

- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):

ESP32

**Describe the problem**

Trying to generate all projects fails

**Please provide the exact sequence of commands/steps when you ran into the problem**

```
$make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_projects
tensorflow/lite/micro/tools/make/Makefile:305: warning: overriding recipe for target 'tensorflow/lite/micro/tools/make/downloads/ruy'
tensorflow/lite/micro/tools/make/Makefile:305: warning: ignoring old recipe for target 'tensorflow/lite/micro/tools/make/downloads/ruy'
tensorflow/lite/micro/tools/make/Makefile:305: warning: overriding recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_grayscale'
tensorflow/lite/micro/tools/make/Makefile:305: warning: ignoring old recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_grayscale'
tensorflow/lite/micro/tools/make/Makefile:305: warning: overriding recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
tensorflow/lite/micro/tools/make/Makefile:305: warning: ignoring old recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
make: *** No rule to make target 'tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/person_detection/make/tensorflow/lite/micro/examples/person_detection/person_model_grayscale/person_detect_model_data.cc', needed by 'generate_person_detection_make_project'.  Stop.
```

**Comment by cgreening** [comment]
ok - I think this is just me not understanding how this should work - running:

```
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp  generate_person_detection_esp_project
```

Seems to work - am I right that each project needs to be generated individually?

**Comment by ymodak** [comment]
That's correct. See example usage below;
https://github.com/tensorflow/tensorflow/blob/a4725be4a74c9acae623231e80d5a8002a54e94a/tensorflow/lite/micro/tools/make/Makefile#L10
Thanks!
