### ISSUE TITLE
TFLM 2.3 fails assert in CMSIS-NN fully_connected.cc

### ISSUE THREAD

**Issue by janjongboom** [tensorflow/tensorflow#41816]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Verified on Mbed OS 5.13
- TensorFlow installed from (source or binary): Source
- Tensorflow version (commit SHA if source): 0c43ad89f81b22d81d1894f5b53f9fbdda0b738a
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Mbed OS (ST IoT Discovery Kit)

**Describe the problem**

We have a very simple fully connected network (33x20x10x4 neurons) that fails an assert when being invoked with CMSIS-NN kernels here (in **fully_connected.cc**):

```
    cmsis_nn_dims input_dims;
    input_dims.n = batches;
    input_dims.h = input_shape.Dims(1);
    input_dims.w = input_shape.Dims(2); // <-- here
```

Here `input_shape` is the input layer (33 neurons) which does not have this dimension (`size_` is 2). Setting `input_dims.w` and `input_dims.c` to `1` solves the issue.

**Please provide the exact sequence of commands/steps when you ran into the problem**

See above. Attached the tflite model.
[ei-continuous-gestures-nn-classifier-tensorflow-lite-int8-quantized-model.lite.zip](https://github.com/tensorflow/tensorflow/files/4987903/ei-continuous-gestures-nn-classifier-tensorflow-lite-int8-quantized-model.lite.zip)

**Comment by biagiom** [comment]
Hello @janjongboom,
Could you have a look at my PR (#41285) ? I think it can solve this issue.

Regards,
Biagio.

**Comment by njeffrie** [comment]
It looks like this is related to the linked PR (and should be fixed by it). Thanks for pointing out this issue. Let's verify that once the PR lands this is resolved.

**Comment by janjongboom** [comment]
@dansitu ^

**Comment by felix-johnny** [comment]
PR https://github.com/tensorflow/tensorflow/pull/42314 provides a fix for this issue.
