### ISSUE TITLE
Support for ragged tensor targets (variable-length y)

### ISSUE THREAD

**Issue by Jordy-VL** [tensorflow/tensorflow#41810]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.3
- Python version: 3.6.9
- CUDA/cuDNN version: v10.2
- GPU model and memory: GeForce GTX 1070 - 8117MiB

**Describe the current behavior**:
In compiling the model, the loss function fails to capture the shape of y_true as it is a ragged tensor. 
This impedes sequence labelling tasks with both ragged inputs (x) and ragged sequential targets (y).

**Describe the expected behavior**:
I would expect to be able to train with both ragged inputs and targets (following the same internal structure).
In a sequence labelling task, e.g. named entity recognition, sentences and target vectors are variable-length-sequences. 

**Standalone code to reproduce the issue**

Link to the issue and reproducible code:
[LSTM ragged targets sequence labelling](https://colab.research.google.com/drive/18P6gZQUlP6qxBq70UCRfI42RSilRJ2Mx?usp=sharing)

**Comment by ravikyram** [comment]
@Jordy-VL 

Please, grant me access for the colab link you have attached.Thanks!

**Comment by Jordy-VL** [comment]
I updated the link, can you try again? :) thanks!

**Comment by ravikyram** [comment]
I have tried in colab with TF 2.3-rc2 ,nightly version(`2.4.0-dev20200728`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/9fdbbbeb20bc39bd6ead149bece7f945/untitled193.ipynb).Thanks!

**Comment by Jordy-VL** [comment]
Any updates? 
Thank you in advance :)

**Comment by pawarrick** [comment]
I also would like to see this functionality soon this for input-output sequences that are both ragged (was surprised that it was not supported). Thx

**Comment by qlzh727** [comment]
Thanks for reporting the issue, I think there are a few issues within this report.

1. In the example provided, the output of the lstm layer is a dense tensor with shape (batch, unit). There isn't a ragged dim involved in the model after the lstm layer, which is why the loss function failed afterwards (failed to compare the dense and ragged tensor). This is expected and working as intended.

2. If we change your model's lstm layer to "return_sequences=True" and let it output the ragged output, the model failed at dense layer since it doesn't support ragged input. 

```
ValueError: Layer dense does not support RaggedTensors as input. Inputs received: tf.RaggedTensor(values=Tensor("lstm/RaggedFromTensor/boolean_mask/GatherV2:0", shape=(None, 32), dtype=float32), row_splits=Tensor("lstm/RaggedFromTensor/concat:0", shape=(None,), dtype=int64)). You can try converting your input to an uniform tensor.
```

So far adding more support for ragged and composite input/output is one of the item on the keras road map. We will probably address this issue in near future.

**Comment by Jordy-VL** [comment]
> Thanks for reporting the issue, I think there are a few issues within this report.
> 
> 1. In the example provided, the output of the lstm layer is a dense tensor with shape (batch, unit). There isn't a ragged dim involved in the model after the lstm layer, which is why the loss function failed afterwards (failed to compare the dense and ragged tensor). This is expected and working as intended.
> 2. If we change your model's lstm layer to "return_sequences=True" and let it output the ragged output, the model failed at dense layer since it doesn't support ragged input.
> 
> ```
> ValueError: Layer dense does not support RaggedTensors as input. Inputs received: tf.RaggedTensor(values=Tensor("lstm/RaggedFromTensor/boolean_mask/GatherV2:0", shape=(None, 32), dtype=float32), row_splits=Tensor("lstm/RaggedFromTensor/concat:0", shape=(None,), dtype=int64)). You can try converting your input to an uniform tensor.
> ```
> 
> So far adding more support for ragged and composite input/output is one of the item on the keras road map. We will probably address this issue in near future.

No problem. Would it be possible to share a link with regards to the Keras roadmap or some time estimate on addressing this issue? Then I know when to come back to the topic.

**Comment by qlzh727** [comment]
We don't have a public doc for that so far, but probably in next two releases (tf release every 3 months).

**Comment by MiquelFerriol** [comment]
Any news on this topic? Did you manage to trick TF in some way? For now, it looks TF does not support ragged tensors on target variables.

**Comment by Jordy-VL** [comment]
@MiquelFerriol  Hi Miquel, sorry to disappoint but I did not find a short-term workaround :/ 
Dynamic padding and batching is the only solution I see for now...

**Comment by pawarrick** [comment]
I don't see mention of this issue in the 2.4.0-rc0 release notes

**Comment by foxik** [comment]
Note that supporting RaggedTensors as targets (e.g., in `model.fit`) is a frequent request, see #44988, #44112, #43591, #43093, #42320, #41810.

Some partial progress is in pull requests #45060 and #45015, which will allow using custom losses in Keras model (but existing losses like MSE or (S)CE will still not work).

**Comment by foxik** [comment]
Note that I created a new feature request #45403 to support RaggedTensors in standard Keras loss functions.

**Comment by foxik** [comment]
The issue is now fixed in `tf-nightly-2.5.0.dev20210302`, see https://colab.research.google.com/drive/18P6gZQUlP6qxBq70UCRfI42RSilRJ2Mx?usp=sharing

**Comment by rmothukuru** [comment]
@Jordy-VL,
Can you please confirm if we can close this issue as it has been fixed per [above comment](https://github.com/tensorflow/tensorflow/issues/41810#issuecomment-788876673)? Thanks!

**Comment by Jordy-VL** [comment]
@rmothukuru I confirm it works, thanks for the effort!

**Comment by nectario** [comment]
How do I utilize ragged labels? Just set the input to ragged=True?

**Comment by federhub** [comment]
Hello everyone, I am facing issues in working on an RNN with variable length in both the input and output sequences, and I found this thread. I went through the colab posted by @foxik (https://colab.research.google.com/drive/18P6gZQUlP6qxBq70UCRfI42RSilRJ2Mx?usp=sharing) but it seems it is not working (or no longer working with tf 2.11.0-dev20221013). Any idea of why?
