### ISSUE TITLE
Are break statements in tf.function supported?

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#41813]
## URL(s) with the issue:

https://www.tensorflow.org/tutorials/distribute/input

## Description of issue (what needs changing):

https://www.tensorflow.org/tutorials/distribute/input#usages states
> However break and return are currently not supported if the loop is placed inside a tf.function

But later the example at https://www.tensorflow.org/tutorials/distribute/input#use_iter_to_create_an_explicit_iterator shows:
```
@tf.function
def train_fn(distributed_iterator):
  for _ in tf.range(steps_per_loop):
    optional_data = distributed_iterator.get_next_as_optional()
    if not optional_data.has_value():
      break
    per_replica_results = strategy.run(lambda x:x, args=(optional_data.get_value(),))
    tf.print(strategy.experimental_local_results(per_replica_results))
```

This shows the usage of a `break` statement in a `tf.function`.

So are those statements supported? Are there conditions under which they are supported?

**Comment by nikitamaia** [comment]
Hi @Flamefire, if you run the following:

```
global_batch_size = 16
mirrored_strategy = tf.distribute.MirroredStrategy()

dataset = tf.data.Dataset.from_tensors(([1.],[1.])).repeat(100).batch(global_batch_size)
dist_dataset = mirrored_strategy.experimental_distribute_dataset(dataset)

@tf.function
def train_step(inputs):
  features, labels = inputs
  return labels - 0.3 * features

@tf.function
def loop(dist_dataset):
  for x in dist_dataset:
    # train_step trains the model using the dataset elements
    loss = mirrored_strategy.run(train_step, args=(x,))
    print("Loss is ", loss)
    break

loop(dist_dataset)
```

You'll see the error message,  `NotImplementedError: break and return statements are not yet supported in for ... in distributed input loops` (important thing to note here is that it's specifically not implemented for distributed input loops)

I think the difference in the `train_fn(distributed_iterator)` example that you've pointed out from the docs is that the for loop is looping over a tf.range, and not a distributed dataset, so a break statement is allowed. I agree it's a bit confusing, but seems to be the break statements are supported in @tf.function, but not when your looping over distributed input

**Comment by Flamefire** [comment]
I see, so I can't do `for x in distributed_dataset: ... break` but I can do `for something_else: x = next(distributed_iterator) ... break`

That's confusing, maybe the docs can be made more clear to point this out?

**Comment by nikitamaia** [comment]
Agreed, it is a bit confusing. Any suggestions on how to make the docs clearer here?

**Comment by Flamefire** [comment]
Maybe:
> However break and return are currently not supported when looping over a distributed dataset inside a tf.function. You can however create an iterator and call `next` on it inside a loop over some other collection(? is this the right term for python?) like `range`

**Comment by nikitamaia** [comment]
Change has been made to the docs
https://www.tensorflow.org/tutorials/distribute/input#usages

`Placing the loop inside a tf.function will give a performance boost. However, break and return are currently not supported for a loop over a tf.distribute.DistributedDataset that is placed inside of a tf.function.`
