### ISSUE TITLE
Hadoop Filesystem for C API Modular filesystem

### ISSUE THREAD

**Issue by vnvo2409** [tensorflow/tensorflow#41826]
**System information**
- TensorFlow version (you are using): 2.2.0
- Are you willing to contribute it: Yes

**Describe the feature and the current behavior/state.**
This issue is used to track the implementation of `hadoop` filesystem for c api modular filesystem

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Users

cc @mihaimaruseac

**Comment by vnvo2409** [comment]
@mihaimaruseac 
I can not file any suitable place so I create an issue here. Currently, the `core` implementation of `hadoop` use 2 functions:
- https://github.com/tensorflow/tensorflow/blob/e82d258f17bb47ce5fe8daa5c88cbbd7fcc0924b/tensorflow/core/platform/hadoop/hadoop_file_system.cc#L73
- https://github.com/tensorflow/tensorflow/blob/e82d258f17bb47ce5fe8daa5c88cbbd7fcc0924b/tensorflow/core/platform/hadoop/hadoop_file_system.cc#L38

Because we can not build `libhdfs.so` ( C interface using JAVA and C ), we have to load it and get the symbols inside it. This is not possible because `C API` does not support these functions. So we have 2 options:
- Add these functions to `C API`.
- Build our own library [`libhdfspp.so`](https://github.com/apache/hadoop/tree/trunk/hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfspp) ( C++ interface with C++ and Proto ). I prefer this approach but converting from `cmake` to `bazel` is troublesome and will take a lot of time ( of course I will continue to work until everything is done ).

Which one do you prefer ?

**Comment by mihaimaruseac** [comment]
I would go for the first option as it is reusable. We will need to load libraries in the future too.

Note that we have one of them already (or very similar) https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/c/c_api.h;l=1431-1443;drc=24f835217fd27f21141ff0254a2b93ea3cfd7b6c

**Comment by Saduf2019** [comment]
@vnvo2409 
Please update as per above comment.

**Comment by vnvo2409** [comment]
That function return a `TF_Library*` https://github.com/tensorflow/tensorflow/blob/bf86c225f059bd6f8e1624001f4644cce2c18fe8/tensorflow/c/c_api.h#L1442

https://github.com/tensorflow/tensorflow/blob/bf86c225f059bd6f8e1624001f4644cce2c18fe8/tensorflow/c/c_api_internal.h#L65-L68

I would like to ask whether `op_list` is the list of the symbols of the library or we have to add a new function `TF_GetSymbolFromLibrary` into `c_api.h`

**Comment by mihaimaruseac** [comment]
Hmm, no, the `op_list` is just the list of TF ops included in the library. It's a protobuf, not something we can use unfortunately.

Looking around, I found that `TF_LoadLibrary` ends up calling [`tensorflow::LoadLibrary`](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/framework/load_library.cc;l=46;drc=d5e414d34ab4b9d918e1eadd5428caf3ef99d6fe) which is different from [`tensorflow::Env::LoadLibrary`](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/platform/env.h;l=337;drc=791f4f2b773208b21ece71e1d37204a91720346d) that we need.

I think now that we will actually need to expose both symbols from `tensorflow/core/platform/env.h` into `tensorflow/c/c_api.h`.

**Comment by vnvo2409** [comment]
I will send you a PR right now
