### ISSUE TITLE
windows build error(makedataset)

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#41820]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4.0
- Python version: 3.8.3
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 3.4.1
- GCC/Compiler version (if compiling from source): Visual Studio 2019
- CUDA/cuDNN version: 11.0/8.0.2
- GPU model and memory: RTX2070 GDDR6 8GB

**Describe the problem**

build error ( link error )

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
./configure
bazel build --copt=-nvcc_options=disable-warnings --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
optimize_dataset_op.lo.lib(optimize_dataset_op.obj) : error LNK2019: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl tensorflow::port::JobName(void)" (?JobName@port@tensorflow@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function "protected: virtual void __cdecl tensorflow::data::OptimizeDatasetOp::MakeDataset(class tensorflow::OpKernelContext *,class tensorflow::data::DatasetBase *,class tensorflow::data::DatasetBase * *)" (?MakeDataset@OptimizeDatasetOp@data@tensorflow@@MEAAXPEAVOpKernelContext@3@PEAVDatasetBase@23@PEAPEAV523@@Z)
bazel-out\x64_windows-opt\bin\tensorflow\python\_pywrap_tensorflow_internal.so : fatal error LNK1120: 1 unresolved externals
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

**Comment by gunan** [comment]
Looks like a missing symbol issue about tf.data ?

**Comment by jsimsa** [comment]
This has been fixed by https://github.com/tensorflow/tensorflow/commit/a912a8ed6cc873e1b4ed5de0fb0524d2e499ea34

**Comment by av8ramit** [comment]
Thank you @jsimsa
