### ISSUE TITLE
Tensorflow Serving 2.2.0 error: output_shape has incorrect number of elements: 2 should be: 1

### ISSUE THREAD

**Issue by ansreng** [tensorflow/tensorflow#41823]
I have a SavedModel, which a am serving with Tensorflow Serving. When I load and run it in a separate script, it's working fine. But sending a request to the serving API throws the following error:

    {
        "error": "[_Derived_]{{function_node __inference__wrapped_model_6314}} {{function_node __inference__wrapped_model_6314}} output_shape has incorrect number of elements: 2 should be: 1\n\t [[{{node model/feature_input/Code_trait._indicator/SparseToDense}}]]\n\t [[StatefulPartitionedCall_66/StatefulPartitionedCall]]"
    }

The normal output shape of the model is (1, 1).

The curl call I use is:

    curl -d '{"instances":[{"Sexe":"M","MCD":5,"Code_diag.":"I33.5","Code_trait.":"b66","Med._traitant":"RickRich","DRG":"x","N_med.":"5324","Traitement_principal":[126,178,177,175,162,93,160,165,172,160,93,162,169,162,160,177],"Operation":[161,205,208,205,204,191,208,205,197,208,191,206,198,199,195,0],"Diag._principal":[144,179,172,188,52,23,6,7,106,26,106,176,182,191,190,35],"Diagnostic":[181,186,194,177,191,192,181,179,173,192,181,187,186,191,108,175]}]}' -X POST http://localhost:8501/v1/models/Excel_AI_Model:predict
  

The versions used to create the SavedModel are the following: 

Python version:  3.6.9

Tensorflow version:  2.2.0

The Serving is the docker image tensorflow/serving:2.2.0.

The model metadata while served is this:

        {
    "model_spec":{
     "name": "Excel_AI_Model",
     "signature_name": "",
     "version": "4"
    }
    ,
    "metadata": {"signature_def": {
     "signature_def": {
      "serving_default": {
       "inputs": {
        "Operation": {
         "dtype": "DT_INT32",
         "tensor_shape": {
          "dim": [
           {
            "size": "1",
            "name": ""
           },
           {
            "size": "16",
            "name": ""
           }
          ],
          "unknown_rank": false
         },
         "name": "serving_default_Operation:0"
        },
        "DRG": {
         "dtype": "DT_STRING",
         "tensor_shape": {
          "dim": [
           {
            "size": "1",
            "name": ""
           },
           {
            "size": "1",
            "name": ""
           }
          ],
          "unknown_rank": false
         },
         "name": "serving_default_DRG:0"
        },
        "Code_trait.": {
         "dtype": "DT_STRING",
         "tensor_shape": {
          "dim": [
           {
            "size": "1",
            "name": ""
           },
           {
            "size": "1",
            "name": ""
           }
          ],
          "unknown_rank": false
         },
         "name": "serving_default_Code_trait.:0"
        },
        "MCD": {
         "dtype": "DT_INT32",
         "tensor_shape": {
          "dim": [
           {
            "size": "1",
            "name": ""
           },
           {
            "size": "1",
            "name": ""
           }
          ],
          "unknown_rank": false
         },
         "name": "serving_default_MCD:0"
        },
        "Diagnostic": {
         "dtype": "DT_INT32",
         "tensor_shape": {
          "dim": [
           {
            "size": "1",
            "name": ""
           },
           {
            "size": "16",
            "name": ""
           }
          ],
          "unknown_rank": false
         },
         "name": "serving_default_Diagnostic:0"
        },
        "Traitement_principal": {
         "dtype": "DT_INT32",
         "tensor_shape": {
          "dim": [
           {
            "size": "1",
            "name": ""
           },
           {
            "size": "16",
            "name": ""
           }
          ],
          "unknown_rank": false
         },
         "name": "serving_default_Traitement_principal:0"
        },
        "N_med.": {
         "dtype": "DT_STRING",
         "tensor_shape": {
          "dim": [
           {
            "size": "1",
            "name": ""
           },
           {
            "size": "1",
            "name": ""
           }
          ],
          "unknown_rank": false
         },
         "name": "serving_default_N_med.:0"
        },
        "Code_diag.": {
         "dtype": "DT_STRING",
         "tensor_shape": {
          "dim": [
           {
            "size": "1",
            "name": ""
           },
           {
            "size": "1",
            "name": ""
           }
          ],
          "unknown_rank": false
         },
         "name": "serving_default_Code_diag.:0"
        },
        "Diag._principal": {
         "dtype": "DT_INT32",
         "tensor_shape": {
          "dim": [
           {
            "size": "1",
            "name": ""
           },
           {
            "size": "16",
            "name": ""
           }
          ],
          "unknown_rank": false
         },
         "name": "serving_default_Diag._principal:0"
        },
        "Sexe": {
         "dtype": "DT_STRING",
         "tensor_shape": {
          "dim": [
           {
            "size": "1",
            "name": ""
           },
           {
            "size": "1",
            "name": ""
           }
          ],
          "unknown_rank": false
         },
         "name": "serving_default_Sexe:0"
        },
        "Med._traitant": {
         "dtype": "DT_STRING",
         "tensor_shape": {
          "dim": [
           {
            "size": "1",
            "name": ""
           },
           {
            "size": "1",
            "name": ""
           }
          ],
          "unknown_rank": false
         },
         "name": "serving_default_Med._traitant:0"
        }
       },
       "outputs": {
        "result_output": {
         "dtype": "DT_FLOAT",
         "tensor_shape": {
          "dim": [
           {
            "size": "1",
            "name": ""
           },
           {
            "size": "1",
            "name": ""
           }
          ],
          "unknown_rank": false
         },
         "name": "StatefulPartitionedCall_66:0"
        }
       },
       "method_name": "tensorflow/serving/predict"
      },
      "__saved_model_init_op": {
       "inputs": {},
       "outputs": {
        "__saved_model_init_op": {
         "dtype": "DT_INVALID",
         "tensor_shape": {
          "dim": [],
          "unknown_rank": true
         },
         "name": "NoOp"
        }
       },
       "method_name": ""
      }
     }
    }
    }
    }

Already posted this on stackoverflow, but got no reply:
https://stackoverflow.com/questions/63073490/tensorflow-serving-2-2-0-error-output-shape-has-incorrect-number-of-elements-2

**Comment by amahendrakar** [comment]
@ansreng,
TensorFlow Serving issues are handled in the Serving repo. Could you please create a new issue from [this link](https://github.com/tensorflow/serving/issues/new) and fill in the template, so that we can track the issue there. Thanks!

**Comment by ansreng** [comment]
Created new issue in the Tensorflow Serving repo:
https://github.com/tensorflow/serving/issues/1703
