### ISSUE TITLE
FailedPreconditionError: Error while reading resource variable block1_conv2_30/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/block1_conv2_30/kernel/N10tensorflow3VarE does not exist. 	 [[{{node block1_conv2_30/Conv2D/ReadVariableOp}}]]

### ISSUE THREAD

**Issue by nickinack** [tensorflow/tensorflow#41835]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.1.1
- Python version: 2.7.17

Trying to model a neural style transfer using VGG16.

Error while reading resource variable block1_conv2_30/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/block1_conv2_30/kernel/N10tensorflow3VarE does not exist.
	 [[{{node block1_conv2_30/Conv2D/ReadVariableOp}}]]

**Standalone code to reproduce the issue**
https://github.com/nickinack/NST-VGG16/blob/master/nst-vgg.ipynb

**Other info/logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@nickinack,
On running the code with TF v1.15, I am facing an error stating `InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [1,320,480,3] vs. shape[2] = [1,480,320,3]`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/c48ac409fd2513a2c0f4431b39e020f5/41835.ipynb). 

Could you please try running the code with TF v1.15 and check if you are still facing the issue. Thanks!

**Comment by nickinack** [comment]
Hey, thank you very much! It indeed seems to be a dimension based problem!
