### ISSUE TITLE
Issue when trying to import tensorflow in my conda environment right after I downloaded it

### ISSUE THREAD

**Issue by kcelestinomaria** [tensorflow/tensorflow#41831]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version: 2.3.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory:N/A

Here below is the error message:
  

**Describe the problem**
_It fails to load Tensorflow runtime whenever I try "import tensorflow" or "from tensorflow import keras" right after I have installed(using pip) tensorflow 2.3.0 from my conda environment.... I used "pip install tensorflow"
**Provide the exact sequence of commands / steps that you executed before running into the problem**
Installed Anaconda on my machine,
I then successfully setup a new conda environment on Cmd right in the Users/home folder
Onwards, I started downloading libraries I needed for ML/DL, specifically tensorflow
After successful downloaded, I tried importing it, but it _failed__

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
 from tensorflow.python._pywrap_tensorflow_interanl import keras
Traceback (most recent call last):
  File "C:\Users\celestino\anaconda3\envs\packt_exercises\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

_Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\celestino\anaconda3\envs\packt_exercises\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\celestino\anaconda3\envs\packt_exercises\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\celestino\anaconda3\envs\packt_exercises\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\celestino\anaconda3\envs\packt_exercises\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\celestino\anaconda3\envs\packt_exercises\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\celestino\anaconda3\envs\packt_exercises\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime._

**Comment by ravikyram** [comment]
@kcelestinomaria 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website.](https://www.tensorflow.org/install/source_windows)

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.
Please, refer similar issue #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
Thanks!

**Comment by ravikyram** [comment]
@kcelestinomaria 

Sorry, but we don't provide support for issues with the conda environment.

This issue is more suitable on Continuum Anaconda [repo](https://github.com/ContinuumIO/anaconda-issues/issues) since its related to TF installation with Anaconda.
Please post it on [Continuum Anaconda](https://github.com/ContinuumIO/anaconda-issues/issues).Thanks!
