### ISSUE TITLE
Tensorflow not working in pycharm

### ISSUE THREAD

**Issue by blanshe** [tensorflow/tensorflow#41830]
**System information**
-   MacOs Version 10.14.6 (18G5033)
- Installed through Pycharm CE 
- TensorFlow version 2.0 but I have also installed Tensorflow 1.14 on python hoping it would work but didn't work.
- Python version: 3.7.4
- Installed using: pip
- 1.6 GHz Intel Core i5

**The problem**

Today is my first time trying learn Tensorflow through LinkedIn Learning. I followed tutorials which uses Pycharm CE. It is through Pycharm where I installed Tensorflow. However, when it came to running the model, the response I got is that **ModuleNotFoundError: No module named 'tensorflow.contrib'**

I have read some debugging related to this question but they were unclear and unhelpful. Any assistance will be highly appreciated. Thank you.

**Comment by ymodak** [comment]
Looks like you are trying to import contrib module in TF 2 which raises the error. `contrib` is no longer part of TF 2 and above.

**Comment by blanshe** [comment]
Thank you ymodak, what can I do?

**Comment by mihaimaruseac** [comment]
If you want to use `tf.contrib`, you need to use TF 1.15.

If you want to use TF newer than 2.0 (2.3 was released yesterday), then you need to change the code to not use `tf.contrib`.

**Comment by jdvylder** [comment]
The tf.contrib module is not included in TensorFlow 2. Many of its submodules have been integrated into TensorFlow core, or spun-off into other projects like tensorflow_io, or tensorflow_addons. So probably you can still do the same things, you will just need to find the right locations for the function you want to use.

**Comment by blanshe** [comment]
Thank you. It's no doubt tough for a beginner who is watching tutorials. I have been scanning through internet to look at the available answers. One the debugs I came across is this, **python -m pip install --user --upgrade tensorflow==1.15**

That was meant to change my version from 2.20 to 1.15. I run the code in Pycharm terminal and it seems to have successfully installed. But when I try to check tensorflow version on Pycharm terminal, I can't get it. When I run the code, I get the original error of **ModuleNotFoundError: No module named 'tensorflow.contrib'**

Not sure of what I should try out next. Thank you once again.

**Comment by jdvylder** [comment]
what shows when running `python -c 'import tensorflow as tf; print(tf.__version__)'` ?

**Comment by blanshe** [comment]
Thank you. It shows that I have tensorflow version 1.15. Could there be a way that I can connect it to Pycharm like the way it synchronizes python because now, I see, I have tensorflow installed, but Pycharm isn't getting it like the way is connects to python as the interpreter. Thank you once again for the help.

**Comment by amahendrakar** [comment]
@blanshe,
Please take a look at [this guide](https://www.jetbrains.com/help/pycharm/installing-uninstalling-and-upgrading-packages.html?keymap=primary_macos) to install Python packages from PyCharm itself. Try installing TensorFlow using the guide and let us know if it works.

**Comment by blanshe** [comment]
I am really grateful. It has worked. I went to python interpreter settings and downgraded tensorflow from 2.3 to 1.15 version. Thank you all.

**Comment by fabiogeraci** [comment]
Hello, i am trying to run tensorflow, with the following setup:
macbook mid 2009
Ubuntu 20.04
Pycharm latest version
python 3.7.9, installed with pycharm

now if i use tensorflow 2.3.1 i get an error 132
if i run tensorflow 1.5 ModuleNotFoundError: No module named 'tensorflow.python.platform' but it is install on the virtual environment.

is there a fix or a work around?

**Comment by amahendrakar** [comment]
@fabiogeraci,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
