### ISSUE TITLE
Keras ImageDataGenerator Preprocessing-Function

### ISSUE THREAD

**Issue by marang7** [tensorflow/tensorflow#41833]
I am quite new to Tensorflow and Keras and not sure if am getting something wrong or if there really is a difference between the documentation and the code. If any futher informations are necessarry I will add them quickly.

## URL(s) with the issue:

https://keras.io/api/preprocessing/image/#imagedatagenerator-class

### Clear description

According to the documentation the class `ImageDataGenerator` takes a function `preprocessing_function` when initializing it. In the discription it says that the function is executed AFTER the input has been rescaled:
"...The function will run after the image is resized and augmented..."
When going through the code I realized that in the class `ImageDataGenerator` within the function `standardize` the `preprocessing_function `is applied BEFORE rescaling the image.

### Correct links

Is the link to the source code correct? Yes

### Parameters defined

Are all parameters defined and formatted correctly? yes

### Returns defined

Are return values defined? Yes

### Raises listed and defined

Are the errors defined? Yes

**Comment by Saduf2019** [comment]
@marang7 
Could you please fill in the issue template with the issue faced and details as requested for along with tf version [simple stand alone code and error logs or colab gist with the error or steps that you ran before you ran into the issue]
