### ISSUE TITLE
"inputs" method of tflite::Interpreter causes crash.

### ISSUE THREAD

**Issue by y-ich** [tensorflow/tensorflow#41844]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: MatePad Pro
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): Android NDK 21.3.6528147
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Using TensorFlow Lite C++ API, when you call "inputs" method of tflite::Interpreter, you get the error `terminating with uncaught exception of type std::length_error: vector` and the program crashes.

Until the source code with the tag 2.3.0-rc2, it works and the source code with the tag 2.3.0 and later, it crashes.

**Describe the expected behavior**

No crashes and get the result of inputs.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@y-ich,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by mihaimaruseac** [comment]
Can you provide a model that I can use to debug please?

**Comment by y-ich** [comment]
It was my mistake.
I used different version of include path. That was the cause.

I am sorry that I wasted your time.
