### ISSUE TITLE
Tensorflow raises exception in eager mode but works in graph mode "AttributeError: 'float' object has no attribute '_id'"

### ISSUE THREAD

**Issue by Ghost---Shadow** [tensorflow/tensorflow#41845]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): `v2.1.0-rc2-17-ge5bf8de410 2.1.0`
- Python version: 3.7.6
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version: V10.1.243
- GPU model and memory: RTX2070 MaxQ, 8GB

**Describe the current behavior**

Running the following code in Eager mode, the line `tf.print(tape.gradient(y, x))` throws with exception  `AttributeError: 'float' object has no attribute '_id'`. In Graph mode it returns `None` gradient as expected.

```python
# @tf.function
def sign(x):
    tf.debugging.assert_rank(x, 0)
    
    if x > 0:
        return 1.0
    else:
        return -1.0
    
x = tf.constant(3.0, dtype=tf.float32)

with tf.GradientTape() as tape:
    tape.watch(x)
    y = sign(x)
    
tf.print(y)
tf.print(tape.gradient(y, x))
```

However, wrapping the return values in `tf.constant` does not throw an exception

```python
def sign(x):
    tf.debugging.assert_rank(x, 0)
    
    if x > 0:
        return tf.constant(1.0)
    else:
        return tf.constant(-1.0)
    
x = tf.constant(3.0, dtype=tf.float32)

with tf.GradientTape() as tape:
    tape.watch(x)
    y = sign(x)
    
tf.print(y)
tf.print(tape.gradient(y, x))
```

**Describe the expected behavior**

It should either not throw an error in Eager mode or give a more verbose error message

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-f537fe9b7f6f> in <module>
     15 
     16 tf.print(y)
---> 17 tf.print(tape.gradient(y, x))

c:\users\windows\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\eager\backprop.py in gradient(self, target, sources, output_gradients, unconnected_gradients)
   1027         output_gradients=output_gradients,
   1028         sources_raw=flat_sources_raw,
-> 1029         unconnected_gradients=unconnected_gradients)
   1030 
   1031     if not self._persistent:

c:\users\windows\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\eager\imperative_grad.py in imperative_grad(tape, target, sources, output_gradients, sources_raw, unconnected_gradients)
     75       output_gradients,
     76       sources_raw,
---> 77       compat.as_str(unconnected_gradients.value))

AttributeError: 'float' object has no attribute '_id'
```

**Comment by ravikyram** [comment]
I have tried in colab with TF 2.1, 2.3, nightly versions(`2.4.0-dev20200728`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/2c242efbd330d1be2aef5ff16cfb802e/untitled194.ipynb).Thanks!

**Comment by nikitamaia** [comment]
Hi @Ghost---Shadow, you'll notice that if you `print(type(y))` within your gradient tape, y is `<class 'float'>`. 

`tape.gradient` only works with tensors or variables, [as specified in the docs.](https://www.tensorflow.org/api_docs/python/tf/GradientTape#gradient) Hence why everything works when `sign(x)` returns tf.constant instead of float.

The reason your code works with the @tf.function decorator is because [Autograph is on by default](https://www.tensorflow.org/guide/function#autograph_transformations), and transforms your python eager code into graph-compatible TensorFlow ops.

**Comment by Ghost---Shadow** [comment]
@nikitamaia I am aware of that. However, I think it should either not throw an error in Eager mode or give a more verbose error message. 

> gradient function expects Tensor, received float

or it should coerce to Tensor automatically.

**Comment by nikitamaia** [comment]
Removing the bug label, since there is no bug here. 
That being said, there is always a lot of room to improve Tensorflow error messages and make everything more intuitive (especially when switching between eager and graph mode!). 
Please file a feature request if you are proposing a different error message or functionality.
