### ISSUE TITLE
GPU Installation instructions may need to be updated

### ISSUE THREAD

**Issue by elishafer** [tensorflow/tensorflow#41848]
I'm following the [GPU install instructions](https://www.tensorflow.org/install/gpu) for Ubuntu 18.04 and getting the following after running this:
```
sudo apt-get install --no-install-recommends \
    cuda-10-1 \
    libcudnn7=7.6.5.32+cuda10.1  \
    libcudnn7-dev=7.6.5.32-1+cuda10.1
```
I'm getting this:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '7.6.5.32+cuda10.1' for 'libcudnn7' was not found
```
 `7.6.5.32+cuda10.1` may need to be changed to  `7.6.5.32-1+cuda10.1`  since the latter works.

**Comment by bigboy32** [comment]
Same

**Comment by nishitnshah** [comment]
There is 1 missing in libcudnn7 package, following works

libcudnn7=7.6.5.32**-1**+cuda10.1
