### ISSUE TITLE
protoc fails to execute due to missing environment (LD_LIBRARY_PATH)

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#41857]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL 7
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3.0

**Describe the problem**

Build fails during execution of `protoc` due to unset `LD_LIBRARY_PATH

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Setup custom GCC + binutils and export PATH/LD_LIBRARY_PATH

**Any other info / logs**

This is the same problem as fixed in https://github.com/bazelbuild/bazel/pull/11860 which copied a file from grpc, fixed in https://github.com/grpc/grpc/pull/23664

**Comment by gowthamkpr** [comment]
@Flamefire Isn't this issue caused by bazel itself, not tensorflow?

**Comment by Flamefire** [comment]
Depends. It is caused by the (IMO horrible) decision of Bazel to by default erase the user environment including essential variables like PATH. This has caused a lot of headaches for package maintainers already because issues like this one pop up again and again.

However this particular issue is caused by grpc, I reported it in https://github.com/grpc/grpc/issues/23682 and fixed in https://github.com/grpc/grpc/pull/23664 pending merge.

As TensorFlow directly uses grpc in a specific revision it is now also an issue in tensorflow and can be fixed by updating grpc once the fix is accepted or by backporting the patch. See my PR https://github.com/tensorflow/tensorflow/pull/41889
