### ISSUE TITLE
ImportError : cannot import name 'cloud” from  ' tensorflow.contrib' (/usr/1ocal/lib/ python3.7/dist-packages/tensorflow/ contrib/_ init Py)

### ISSUE THREAD

**Issue by Dolphinzzx** [tensorflow/tensorflow#41858]
I am using TensorFlow 1.14.0 and python3.7.
When  i run code, this erro will display.
![image](https://user-images.githubusercontent.com/31792429/88808693-c7eaef00-d1e5-11ea-9df3-afd3706d4806.png)

**Comment by Saduf2019** [comment]
@Dolphinzzx 
Can you please try to :
find the path corresponding to ImportError, open the __init__.py file of tensorflow, and comment out the line corresponding to the error. (and let us know)

Also please refer to below resolved issues with same error:
#23976 [link](https://github.com/yaroslavvb/tensorflow-community-wheels/issues/117) [link](https://github.com/tensorflow/tensorflow/issues/23758#issuecomment-442615804) [link1](https://stackoverflow.com/questions/55172923/tensorflow-v1-12-importerror-cannot-import-name-cloud)

**Comment by erwincoumans** [comment]
got the same error, you have to manually comment-out the import line cloud from tensorflow/contrib/__init__.py
