### ISSUE TITLE
Using tf.keras.Model.test_on_batch inside tf.function

### ISSUE THREAD

**Issue by louisgriffin** [tensorflow/tensorflow#41853]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.4
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.7

**Describe the current behavior**
Given a tf.keras.Model and a tf.data.Dataset, I'd like to be able to iterate a batched dataset and perform mode.test_on_batch and collect the results.
Note: eager execution is disabled due to other reported bugs 

```python
import tensorflow as tf
import numpy as np

tf.compt.v1.disable_eager_execution()

x = tf.keras.Input(shape=(3,))
y = tf.keras.layers.Dense(2)(x)
model = tf.keras.Model([x], [y])
compile_kwargs = {'optimizer': 'sgd', 'loss': tf.keras.losses.mean_squared_error}
model.compile(**compile_kwargs)

data = [np.full(shape=(3,), fill_value=i) for i in range(10)]
data = np.asarray(data)
labels = [np.full(shape=(2,), fill_value=i)*3 for i in range(10)]
labels = np.asarray(labels)

ds = tf.data.Dataset.from_tensor_slices((data, labels)).batch(2)

# Option 1 - doesn't work when eager execution is disabled
# Throws - RuntimeError: __iter__() is only supported inside of tf.function or when eager execution is enabled.
# ins = ds.map(lambda x, y: x)
# for batch in ins:
   # r = model.test_on_batch(batch)
   # print(r)

# Option 2
@tf.function
def test_on_batch_example(model, ins):
  for batch in ins:
    r = model.test_on_batch(batch)
    print(r)
  
ins = ds.map(lambda x, y: x)
test_on_batch_example(model, ins)
```

Option 2 throws:
    <ipython-input-7-e1744a238c31>:5 test_on_batch_example  *
        r = model.test_on_batch(batch)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training_v1.py:1163 test_on_batch  **
        self._make_test_function()
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training_v1.py:2054 _make_test_function
        **self._function_kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py:3943 function
        model = models.Model(inputs=inputs, outputs=outputs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:242 __new__
        return functional.Functional(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/base.py:464 _method_wrapper
        result = method(self, *args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py:111 __init__
        self._init_graph_network(inputs, outputs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/base.py:464 _method_wrapper
        result = method(self, *args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py:138 _init_graph_network
        base_layer_utils.create_keras_history(self._nested_outputs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_utils.py:189 create_keras_history
        _, created_layers = _create_keras_history_helper(tensors, set(), [])
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_utils.py:249 _create_keras_history_helper
        constants[i] = backend.eval_in_eager_or_function(op_input)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py:3880 eval_in_eager_or_function
        raise ValueError('Unknown graph. Aborting.')

    ValueError: Unknown graph. Aborting.

**Standalone code to reproduce the issue**

https://colab.research.google.com/drive/1exTEugyIZCoc4j0rGyexj1CTf58weuaO?usp=sharing

**Comment by amahendrakar** [comment]
@louisgriffin,
As per the error log from the Colab notebook you have linked, I've moved `Model.test_on_batch` outside of `tf.function` and was able to run the code without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/8bdf32af1485e7e7c63a3431eac2939f/41853.ipynb). Thanks!

**Comment by louisgriffin** [comment]
@amahendrakar 
you missed ```tf.compat.v1.disable_eager_execution()``` that was in the original gist.

**Comment by nikitamaia** [comment]
Hi @louisgriffin, using `test_on_batch` inside tf.function will result in a runtime error as noted [here in the docs.](https://www.tensorflow.org/api_docs/python/tf/keras/Model#test_on_batch) This is because test_on_batch is a high-level end point that manages its own tf.function. You might want to try `Model.test_step`, which is just the logic of the testing step and is safe to use with tf.function.
