### ISSUE TITLE
Building of the PIP package (as described in docs) is broken

### ISSUE THREAD

**Issue by lithuak** [tensorflow/tensorflow#41864]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3.0
- Python version: 3.7.6
- Installed using virtualenv? pip? conda?: neither
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: 10.2.89/7.6.5
- GPU model and memory: GeForce RTX 2080 Ti

**Describe the problem**

The documentation [says](https://www.tensorflow.org/install/source) that in order to build the PIP package from source you have to:

`./bazel-bin/tensorflow/tools/pip_package/build_pip_package --nightly_flag /tmp/tensorflow_pkg
`

This doesn't work, since there is no more `bazel-bin` in the TF source tree, and running the same command with `bazel-tensorlflow` instead of `bazel-bin` doesn't work either.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

`./bazel-bin/tensorflow/tools/pip_package/build_pip_package --nightly_flag /tmp/tensorflow_pkg`

**Comment by mihaimaruseac** [comment]
`bazel-bin` should be created as a symlink after successful run of `bazel build //tensorflow/tools/pip_package:build_pip_package`.

**Comment by lithuak** [comment]
@mihaimaruseac Got it, thanks!
