### ISSUE TITLE
Returning tf.data.UNKNOWN_CARDINALITY when the cardinality can be easily computed

### ISSUE THREAD

**Issue by andrescodas** [tensorflow/tensorflow#41869]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): *yes*
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): *dockerhub tensorflow/tensorflow:latest*
- TensorFlow installed from (source or binary): *dockerhub image*
- TensorFlow version (use command below): *v2.3.0-rc2-23-gb36436b087 2.3.0*

**Describe the current behavior**

*tf.data.Dataset.cardinality returns tf.data.UNKNOWN_CARDINALITY when the cardinality can be easily computed*

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python

import tensorflow as tf

print(tf.__version__)
# prints 2.3.0

nx = 2

t = tf.data.Dataset.from_tensor_slices(tf.constant([[0],[1]]))
t2 = t.flat_map(lambda ti: tf.data.Dataset.from_tensors(ti).repeat(nx))

#########################
for ti in t2:
    print(ti)

# correctly prints:
#tf.Tensor([0], shape=(1,), dtype=int32)
#tf.Tensor([0], shape=(1,), dtype=int32)
#tf.Tensor([1], shape=(1,), dtype=int32)
#tf.Tensor([1], shape=(1,), dtype=int32)

#############################3

print((t2.cardinality() == tf.data.UNKNOWN_CARDINALITY).numpy())
# prints True


```

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3,nightly version(`2.4.0-dev20200729`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/5da063bb8958058992570807f07fe612/untitled199.ipynb).Thanks!

**Comment by jsimsa** [comment]
How do you propose the cardinality could be "easily" computed in this case?

Executing the input pipeline does not qualify as an acceptable solution because it can be in general expansive (and possibly not terminate).

**Comment by andrescodas** [comment]
I see that executing the pipeline could be expensive in general.  I was not saying that this was a valid alternative for the general case.

I'm not a tensorflow developer, and therefore, I don't know the implementation details to suggest an alternative.  However, it could be better documented when cardinality return tf.data.UNKNOWN_CARDINALITY.  I guess the answer in general will be that this is the case whenever you use a 'flat_map'. If that is the case, you may look into flat_map and check if you could propagate the cardinality computation propagation through it.

**Comment by jsimsa** [comment]
I agree that the behavior of the method should be documented better. @aaudiber could you please update the cardinality documentation to address this issue. In particular, to call out that:

1) A known cardinality is returned only when it can be inferred statically (i.e. the computation does not execute the input pipeline). Consequently, input pipelines that make use of file-based source datasets or transformations which construct datasets from their input using a user-defined function are expected to return unknown cardinality.

2) The users can provide cardinality hints through the `assert_cardinality` transformation.

@andrescodas as for your suggestion about inspecting `flat_map` (or `interleave` for that matter). It is generally not possible to statically determine what he cardinality would be. The cardinality of `flat_map` is a function of the values generated by the `flat_map` input dataset, which are generally not known statically (i.e. without executing the input dataset) and so we do not attempt to do it.

**Comment by aaudiber** [comment]
Thanks for bringing this up @andrescodas! I've updated the cardinality docs in https://github.com/tensorflow/tensorflow/commit/2fe61b03cd2703de2658ece095edb7a0ada3f681
