### ISSUE TITLE
Keras ModelCheckpoint callback not raising exception when h5 save fails

### ISSUE THREAD

**Issue by yixingfu** [tensorflow/tensorflow#41874]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3
- Python version:3.6

**Describe the current behavior**
The callback conceals the exception thrown by `save_model`. The checkpoints are not saved but no error is reported. 

**Describe the expected behavior**
The callback should re-throw the error after catching it. 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
https://colab.research.google.com/drive/1Nq5ARA3BHTxUyguiFFBBH74tXC54MABB?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ymodak** [comment]
@yixingfu The colab gist you shared cannot be opened due to permissions. Can you please save it as GitHub gist and share again? Thanks!

**Comment by yixingfu** [comment]
Here is the gist
https://gist.github.com/yixingfu/79e0693627c8e0aeaccaead6d4068cbf

**Comment by ymodak** [comment]
As per new tf-nightly version 2.4.0-dev20200803 the error is not raised while loading weights.
See [gist](https://colab.research.google.com/gist/ymodak/a6e26acf6a1bfb3d2d042cac55a8b655/callback-exception.ipynb).

**Comment by yixingfu** [comment]
No it still raises error when loading weight. And this error comes from the checkpoint failing to save, which should actually raise an error. 

I think I know where the error come from. I will open a PR to fix it soon.

**Comment by ymodak** [comment]
You are right this works for `tf` format but not `h5`.
I forgot to reset the colab runtime while testing for different formats so didn't get any error.
Feel free to raise a PR and tag this issue thread. Thanks!
