### ISSUE TITLE
Pylint E1121 caused by arguments to reshape method.

### ISSUE THREAD

**Issue by jpodivin** [tensorflow/tensorflow#41873]
When I run pylint (with provided rc file) on Tensorflow, lot of E1121 popped up. Looking over the code I found lines like this to be the cause:
https://github.com/tensorflow/tensorflow/blob/206ed7a37f0e5e80b1f62e2172f96a9a2f7041c8/tensorflow/python/kernel_tests/parsing_ops_test.py#L449-L454

Specifically the reshape method. Now tests run just fine as they are and it's just a style issue. 
It's completely possible that this was a conscious choice on part of people involved, but if so it might be good idea to adjust relevant parts of projects style definition.

Especially because most of the numpy docs seem to show tuple as a way to pass new shape to the method:
https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy.reshape

If this is an oversight I can open a PR with fix for at least several files. Alternatively I can take a look at the style definition adjustment.

**Comment by mihaimaruseac** [comment]
This has slipped through cracks, apologies for the long delay. Please send a PR to fix this.

**Comment by mihaimaruseac** [comment]
Is this still an issue with newest TF?

**Comment by chunduriv** [comment]
@jpodivin,

Sorry for the late response. This issue was fixed.

    # pylint: disable=too-many-function-args
    expected_output = {
        aname:
            np.array([[1, 1], [-1, -1]], dtype=np.float32).reshape(2, 1, 2, 1),
        bname:
            np.array(["b0_str", ""], dtype=bytes).reshape(2, 1, 1, 1, 1),
    }
    # pylint: enable=too-many-function-args

For more details please refer to PR ec5ff5df834bcd32941ffac649950558f2adea1f. Thank you.
