### ISSUE TITLE
Model was stuck when build model with inputs and outputs based on transformer.

### ISSUE THREAD

**Issue by Askfk** [tensorflow/tensorflow#41879]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MACOS 10.15.5 Catalina
- TensorFlow version: 2.2 and 2.3
- Python version: 3.6

**Describe the problem**
I want to build a transformer (according to this [notebook](https://www.tensorflow.org/tutorials/text/transformer)) model in non-eager execution, and everything runs smoothly only when building model with the tf.keras.layers.Input and its corresponding outputs, the whole program is stuck. By the way, when executing the for loop in block 10, it consumes extremely much time.

There are no error messages about this phenomenon, totally have no idea about what leads to this.

I have replicated this issue [here](https://colab.research.google.com/drive/1sGkTwMUgOUSlfbYmyuEOaQK7inECuCp9?usp=sharing) in google colab.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I initialized an Input `tf.keras.layers.Input` and generate outputs with transformer model, then use the input and outputs to build a model but the whole program is stuck.

**Comment by Saduf2019** [comment]
@Askfk 
I ran the code shared and do not face any errors, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/b521db122ab3946669c05f4c3fd8472d/untitled310.ipynb)

**Comment by Askfk** [comment]
> @Askfk
> I ran the code shared and do not face any errors, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/b521db122ab3946669c05f4c3fd8472d/untitled310.ipynb)

Sorry I made some changes for testing which part leads to the stuck in the notebook so based on these changes it can run without problems but in the [original notebook](https://colab.research.google.com/drive/1sGkTwMUgOUSlfbYmyuEOaQK7inECuCp9?usp=sharing) the problems are still there.

**Comment by Saduf2019** [comment]
@Askfk 
I re-ran the above colab and do not face any errors.

**Comment by Askfk** [comment]
Thank you for your efforts, but I will still be stuck in the for loop (it costs too much time in every iteration which is abnormal).

**Comment by nikitamaia** [comment]
Hi @Askfk, are you still facing this problem? Can you try commenting out `tf.compat.v1.disable_eager_execution()`?
