### ISSUE TITLE
Unable to install tensorflow even after upgrading pip

### ISSUE THREAD

**Issue by KapilBansal320** [tensorflow/tensorflow#41871]
![error](https://user-images.githubusercontent.com/42766576/88843049-199f7380-d1fe-11ea-9477-2bac3760a634.png)
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Windows 10.0.18363
- TensorFlow installed from (source or binary): Tried to install using `pip install tensorFlow`
- TensorFlow version: 
- Python version: Tried on both 3.6.0 and 3.8.5
- Installed using pip

**Describe the problem**
I tried to install tensorflow but encountered an error as there is no matching distribution. By going through the previous issues I upgrade my pip version to 20.2. Tried it on both python 3.6 and python 3.8.5

**Comment by AbdulKhadhar** [comment]
Backup your libraries(lib) of current python . 
Reinstall python of 64bit [Executable File](https://www.python.org/ftp/python/3.8.5/python-3.8.5-amd64.exe) for windows.
Remove the previous path(of python 32bit) from Environment Variable .
Restore libraries or reassign pip
Retry the install 😊

**Comment by Saduf2019** [comment]
@KapilBansal320 
Please verify if you are using python 32 bit [use 64 bit] and upgrade pip, let us know.

Please provide all details as per issue template for us to analyse, please share error log in text format for ease of use in case the issue is not resolved.

**Comment by mihaimaruseac** [comment]
This is either 32 bits Python or Python installed from the marketplace instead of from the official Python sources.

**Comment by KapilBansal320** [comment]
Yes, I was using 32 bit python. Thanks for help.
But why this doesn't work in 32 bit python

**Comment by mihaimaruseac** [comment]
Because C++ datatypes are different on 32bits vs on 64bits. Since we only test on 64bits, providing a package for 32bits is impossible for us. Community can attempt builds for 32bits but it's not as simple as just building, you will need to also ensure no security issues arise from the type width change.

Since this is solved, closing.
