### ISSUE TITLE
Resource exhausted: OOM when allocating tensor with shape[256] 

### ISSUE THREAD

**Issue by suresh-s** [tensorflow/tensorflow#41888]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution : ubuntu 18.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:  Jetson Nano
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tensorflow==1.15.2+nv20.6
- Python version: 3.6
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 10.2 / cuDNN 8.00
- GPU model and memory: NVIDIA Tegra X1 (nvgpu)/integrated and 4GB memory
Keras: 2.0.5

**Describe the current behavior**
**Error :**

**tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at assign_op.h:117 : Resource exhausted: OOM when allocating tensor with shape[256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc**

![image](https://user-images.githubusercontent.com/2168986/88894424-7b46f880-d265-11ea-98bb-55ea40271009.png)

**Source code**

![image](https://user-images.githubusercontent.com/2168986/88894492-9154b900-d265-11ea-8799-58202d7338b0.png)

**Refer the Logs, generated while start executing**

**“adding visible gpu devices: 0”**

**is GPU not allocated for the job?**
![image](https://user-images.githubusercontent.com/2168986/88894707-ee506f00-d265-11ea-9cac-b9d1d29c13bc.png)

**Comment by ravikyram** [comment]
@suresh-s 

Please, share colab link or simple standalone code with supporting files with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by suresh-s** [comment]
ravikyram,
I am testing the following github project.   Could you use this code repository to check? 
https://github.com/foamliu/Car-Recognition

**Comment by ravikyram** [comment]
@suresh-s 
Limiting gpu memory can help resolve OOM error.
See https://www.tensorflow.org/guide/using_gpu#allowing_gpu_memory_growth.
Thanks!

**Comment by suresh-s** [comment]
I have improved the performance by specifying configs per_process_gpu_memory_fraction =0.2, allow_growth =True and visible_device_list="0".  But at one point in time, Swap memory reaches "100%" and System freezed.   Could you suggest to resolve this issue?

**Comment by ravikyram** [comment]
@suresh-s 

Can you please try setting hard limit on the GPU as shown in the second method under `Limiting gpu memory growth` section
https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth
Thanks!

**Comment by suresh-s** [comment]
I have tried hard limit on the GPU. I have created swap file of size 6 GB. But again i got Out of memory exception on Jetson Nano.   I am using [Stanford Cars Dataset ](https://ai.stanford.edu/~jkrause/cars/car_dataset.html) 

this is the source code https://github.com/suresh-s/Car-Recognition-Phd/blob/master/train.py

Please help me to solve this issue

**Comment by gowthamkpr** [comment]
@suresh-s First of all please use CUDA 10.0 with cuDNN 7.4 as shown in the [doc](https://www.tensorflow.org/install/source#gpu).
Also a few recommendations:
1. try to run the same script on a bigger machine with more memory and see if it fixes it.
2. try reducing the batch size and see if it fixes it.

I think its a memory issue from your end, try running your code on Colab gpu and let me know if it works. Thanks!
