### ISSUE TITLE
module 'tensorflow.python.framework.ops' has no attribute 'register_tensor_conversion_function'

### ISSUE THREAD

**Issue by wkr-ux** [tensorflow/tensorflow#41887]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@wkr-ux,
Please fill in the template and clearly describe the issue you are facing.

Also in in order to reproduce the issue reported here, please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!

**Comment by Xnhyacinth** [comment]
@wkr-ux the same problem. How do u solve it?

**Comment by jdsannchao** [comment]
> 



> @wkr-ux the same problem. How do u solve it?

Hi, did you solve it?

**Comment by Xnhyacinth** [comment]
I have not solved it

**Comment by jdsannchao** [comment]
> I have not solved it

Hi, I managed to solve it by changing the "tpu_variables.py" file. The problem was that the "type conversion" function was no longer under the "tensorflow.python.framework.ops". Tt was changed to "tensorflow.python.framework.tensor_conversion_registry." in later Tensorflow versions.

**Comment by jdsannchao** [comment]
> I have not solved it

Hi, may I ask if you also have this error: 

From /job:worker/replica:0/task:0:
Trying to modify element 0 in a list with 0 elements.
	 [[{{node while/body/_1/cond/else/_155/TensorArrayV2Write/TensorListSetItem}}]]
	 [[while/IteratorGetNext]]

**Comment by Xnhyacinth** [comment]
> > I have not solved it
> 
> Hi, I managed to solve it by changing the "tpu_variables.py" file. The problem was that the "type conversion" function was no longer under the "tensorflow.python.framework.ops". Tt was changed to "tensorflow.python.framework.tensor_conversion_registry." in later Tensorflow versions.

I try it now~ thanks a lot

**Comment by Xnhyacinth** [comment]
> > I have not solved it
> 
> Hi, may I ask if you also have this error:
> 
> From /job:worker/replica:0/task:0: Trying to modify element 0 in a list with 0 elements. [[{{node while/body/_1/cond/else/_155/TensorArrayV2Write/TensorListSetItem}}]] [[while/IteratorGetNext]]

I have not met

**Comment by Patataman** [comment]
In the `tpu_variables.py` ass the import `from tensorflow.python.framework.tensor_conversion_registry import register_tensor_conversion_function`

Probably you will face another import error, but it will be different
