### ISSUE TITLE
When i run code by python2 but it read python3 library files erro. What should i do?

### ISSUE THREAD

**Issue by Dolphinzzx** [tensorflow/tensorflow#41882]
When i run code by python2 but it read python3 library files all time.
As shown below.
![image](https://user-images.githubusercontent.com/31792429/88876372-bb9e7a80-d255-11ea-8ad3-ffb226e50c26.png)

**Comment by ymodak** [comment]
Can you jupyter notebook kernel specks?? I think the kernel path is incorrectly configured.

**Comment by ravikyram** [comment]
@Dolphinzzx 

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
Provide the exact sequence of commands / steps that you executed before running into the problem.

Thanks!
