### ISSUE TITLE
Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

### ISSUE THREAD

**Issue by nicgar20** [tensorflow/tensorflow#41886]
With: 

#### load MNIST dataset
mnist = tf.keras.datasets.mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

print(X_train.shape, y_train.shape)
print(X_train.min(), X_train.max(), y_train.min(), y_train.max())

X_train, X_test = X_train/255., X_test/255.

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(10),
    ])

predictions = model(X_train.astype('float32')[:1]).numpy()
print(predictions)

y_pred = tf.nn.softmax(predictions).numpy()
print(y_pred)
print(y_pred.sum())

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=15)

model.evaluate(X_test, y_test, verbose=2)

model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Conv2D(16, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(tf.keras.layers.MaxPool2D((2, 2)))
model.add(tf.keras.layers.Conv2D(32, (3, 3), activation='relu'))
model.add(tf.keras.layers.MaxPooling2D((2, 2)))
model.add(tf.keras.layers.Conv2D(32, (3, 3), activation='relu'))

model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(64, activation='relu'))
model.add(tf.keras.layers.Dense(10))

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
             metrics=['accuracy'])
             
history = model.fit(X_train[:, :, :, np.newaxis], y_train, epochs=10,
                    validation_data=(X_test[:, :, :, np.newaxis], y_test))

###################
**I get:**
###################

Epoch 1/10

---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
<ipython-input-20-0e520e098f8a> in <module>
      4 
      5              # fit
----> 6 history = model.fit(X_train[:, :, :, np.newaxis], y_train, epochs=10,
      7                     validation_data=(X_test[:, :, :, np.newaxis], y_test))
      8 

~/miniconda3/envs/ML/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
     64   def _method_wrapper(self, *args, **kwargs):
     65     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
---> 66       return method(self, *args, **kwargs)
     67 
     68     # Running inside `run_distribute_coordinator` already.

~/miniconda3/envs/ML/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
    846                 batch_size=batch_size):
    847               callbacks.on_train_batch_begin(step)
--> 848               tmp_logs = train_function(iterator)
    849               # Catch OutOfRangeError for Datasets of unknown size.
    850               # This blocks until the batch has finished executing.

~/miniconda3/envs/ML/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    578         xla_context.Exit()
    579     else:
--> 580       result = self._call(*args, **kwds)
    581 
    582     if tracing_count == self._get_tracing_count():

~/miniconda3/envs/ML/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    642         # Lifting succeeded, so variables are initialized and we can run the
    643         # stateless function.
--> 644         return self._stateless_fn(*args, **kwds)
    645     else:
    646       canon_args, canon_kwds = \

~/miniconda3/envs/ML/lib/python3.8/site-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   2418     with self._lock:
   2419       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
-> 2420     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2421 
   2422   @property

~/miniconda3/envs/ML/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _filtered_call(self, args, kwargs)
   1659       `args` and `kwargs`.
   1660     """
-> 1661     return self._call_flat(
   1662         (t for t in nest.flatten((args, kwargs), expand_composites=True)
   1663          if isinstance(t, (ops.Tensor,

~/miniconda3/envs/ML/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1743         and executing_eagerly):
   1744       # No tape is watching; skip to running the function.
-> 1745       return self._build_call_outputs(self._inference_function.call(
   1746           ctx, args, cancellation_manager=cancellation_manager))
   1747     forward_backward = self._select_forward_and_backward_functions(

~/miniconda3/envs/ML/lib/python3.8/site-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    591       with _InterpolateFunctionError(self):
    592         if cancellation_manager is None:
--> 593           outputs = execute.execute(
    594               str(self.signature.name),
    595               num_outputs=self._num_outputs,

~/miniconda3/envs/ML/lib/python3.8/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     57   try:
     58     ctx.ensure_initialized()
---> 59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:

UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node sequential_1/conv2d/Conv2D (defined at <ipython-input-20-0e520e098f8a>:6) ]] [Op:__inference_train_function_59155]

Function call stack:
train_function`

####################
**My specs:**
####################

NAME="elementary OS"
VERSION="5.1.6 Hera"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 5.1.6 Hera"
LOGO=distributor-logo
VERSION_ID="5.1.6"
HOME_URL="https://elementary.io/"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/os/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=hera
UBUNTU_CODENAME=bionic

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

GPU drivers (nvidia-smi)
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 207...  Off  | 00000000:09:00.0  On |                  N/A |
|  0%   51C    P8    25W / 215W |   7915MiB /  7979MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
 

(All installed with conda install)
**Tensorflow-gpu version 2.2.0**
cudnn                     7.6.5                cuda10.1_0  
cudatoolkit               10.1.243             h6bb024c_0  
                                                                             
I tried installing driver version 435 and it worked but my screen stops being recognized, therefore I cannot readjust the resolution

**Comment by Saduf2019** [comment]
@nicgar20 
I ran the code shared and do not face any issues, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/13d41c917309a9d495a6fefbaad57f92/untitled302.ipynb).

Can you please try setting allow_growth option at the top of your code:

```
import tensorflow as tf
config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.compat.v1.Session(config=config)

# your code 
```

Can you please refer to below resolved issues with same error[as per which this error occurs due to mismatch of cudaa/cudnn with your tensorflow version]:
#41146 [link](https://github.com/tensorflow/tensorflow/issues/36025#issuecomment-628145158) [link1](https://stackoverflow.com/questions/53698035/failed-to-get-convolution-algorithm-this-is-probably-because-cudnn-failed-to-in)

**Comment by summa-code** [comment]
> @nicgar20
> I ran the code shared and do not face any issues, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/13d41c917309a9d495a6fefbaad57f92/untitled302.ipynb).
> 
> Can you please try setting allow_growth option at the top of your code:
> 
> ```
> import tensorflow as tf
> config = tf.compat.v1.ConfigProto()
> config.gpu_options.allow_growth = True
> sess = tf.compat.v1.Session(config=config)
> 
> # your code 
> ```
> 
> Can you please refer to below resolved issues with same error[as per which this error occurs due to mismatch of cudaa/cudnn with your tensorflow version]:
> #41146 [link](https://github.com/tensorflow/tensorflow/issues/36025#issuecomment-628145158) [link1](https://stackoverflow.com/questions/53698035/failed-to-get-convolution-algorithm-this-is-probably-because-cudnn-failed-to-in)

This command prettymuch moves the calculations to CPU rather than GPU. This disables GPU.
