### ISSUE TITLE
Compilation Failure when using tf.keras.layers.UpSampling2D() with colab TPU

### ISSUE THREAD

**Issue by linkun-1998** [tensorflow/tensorflow#41899]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):macOS, Mojave 10.14.6 (Running in Colab)
- TensorFlow version (use command below):2.2.0
- Python version: Python 3.6.9

**Describe the current behavior**
While using tf.keras.layers.Upsampling2D() in Colab TPU, The following error occurs:

```UnimplementedError                        Traceback (most recent call last)
<ipython-input-34-7125d086c152> in <module>()
     10   model.compile(optimizer='sgd', loss='mse', metrics=['accuracy'])
     11 model.summary()
---> 12 history = model.fit(training_dataset, epochs=10, validation_data=validation_dataset, steps_per_epoch=steps_per_epoch)

10 frames
/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

UnimplementedError: {{function_node __inference_train_function_66860}} Compilation failure: CustomCall is not supported to have a dynamic dimension
	TPU compilation failed
	 [[{{node tpu_compile_succeeded_assert/_7048177641045036345/_5}}]]
```

**Describe the expected behavior**
If I use tf.keras.UpSampling2D((2,2)), I should expect the tensor to be resized by a factor of 2.

**Standalone code to reproduce the issue**
```
def create_model():
    
    pretrained_model = tf.keras.applications.Xception(input_shape=[*IMAGE_SIZE, 3], include_top=False)
    pretrained_model.trainable = True

    model = tf.keras.Sequential([
        pretrained_model,
        tf.keras.layers.MaxPooling2D((2,2)),
        tf.keras.layers.UpSampling2D((2,2)),
        tf.keras.layers.GlobalAveragePooling2D(),
        #tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(5, activation='softmax', dtype=tf.float32) # the float32 is needed on softmax layer when using mixed precision
    ])

    model.compile(
        optimizer='adam',
        loss = 'categorical_crossentropy',
        metrics=['accuracy']
    )

    return model
with strategy.scope():
  model = create_model()
model.summary()
start_time = time.time()
history = model.fit(training_dataset, validation_data=validation_dataset,
                    steps_per_epoch=TRAIN_STEPS, epochs=EPOCHS, callbacks=[lr_callback])

final_accuracy = history.history["val_accuracy"][-5:]
print("FINAL ACCURACY MEAN-5: ", np.mean(final_accuracy))
print("TRAINING TIME: ", time.time() - start_time, " sec")
```

This is the [link](https://colab.research.google.com/drive/1yABsMbLguooJutACqH3splUq3lMkc38N?usp=sharing) to the Colab Notebook

**Other info / logs** 
The training dataset is a publicly available TFRecord Dataset

**Comment by Saduf2019** [comment]
@linkun-1998 
Please refer to [this link](https://github.com/tensorflow/tensorflow/issues/38234#issuecomment-609482622) and let us know if it helps resolve your issue.[[link]](https://stackoverflow.com/questions/57658114/how-to-solve-propagation-of-dynamic-dimension-failed-error-in-tf-keras-with-tp)

**Comment by chenghuige** [comment]
@Saduf2019  Seems still will face this problem using tf 2.3 on colab. model.fit ok but model.predict model.evaluate all fail due to this failure.

**Comment by Rybarik1** [comment]
If @Saduf2019 's answer doesn't solve it for you, there might be two different solutions to this error. 

TPU requires explicitly defined shape of input in your data pipeline. First, make sure you're using tf.data pipeline since it offers best compatibility with TPUs. 

As the shape of input image/label looks something like (batch_size, height, weight, channels), all of them have to be stated explicitly and statically for the TPU. 

1. For h, w, c,  you should use tf.reshape when reading tf.Example and extracting image, label, etc. Example code below for reading TFRecords. Note that tf.reshape() has to be used even if it just preserves the original shape.

```python
def read_tfrecord(record, dim):
    LABELED_TFREC_FORMAT = {
        "image": tf.io.FixedLenFeature([], tf.string), # tf.string means bytestring
        "label": tf.io.FixedLenFeature([], tf.string),  # shape [] means single element
    }
    example = tf.io.parse_single_example(example, LABELED_TFREC_FORMAT)
    image = tf.io.decode_image(example['image'], dtype=tf.float32, channels=3)
    >>>image = tf.reshape(image, (dim, dim, 3))<<<
  
    label = tf.io.decode_image(example['label'], dtype=tf.float32, channels=1)
    >>>label = tf.reshape(label, (dim, dim, 1))<<<
 
    return image, label # returns a dataset of (image, label) pairs
```

2. Now, we also need to make sure batch size is constant. This can be ensured by using tf.data.Dataset.batch(batch_size, **drop_remainder=True**). Second argument is crucial here since without it, batch size would be dynamic in order to include the remainder.
