### ISSUE TITLE
How to disable Cudnn for reproducible results

### ISSUE THREAD

**Issue by edwardyehuang** [tensorflow/tensorflow#41906]
I use the setting in [https://github.com/NVIDIA/framework-determinism](https://github.com/NVIDIA/framework-determinism), But I found my model still get random result each time (1% mIOU different)

Is there any way in Tensorflow provides the feature like Pytorch:
```
torch.backends.cudnn.enabled = False
```
I also found there is an enviroment variable "TF_USE_CUDNN" but it does not work.

**Comment by gowthamkpr** [comment]
@edwardyehuang Non-determinism for a priori deterministic operations come from concurrent (multi-threaded) implementations.
Despite constant progress on that front, TensorFlow does not currently guarantee determinism for all of its operations. After a quick search on the internet, it seems that the situation is similar with the other major toolkits.
During training, unless you are debugging an issue, it is OK to have fluctuations between runs. Uncertainty is in the nature of training, and it is wise to measure it and take it into account when comparing results – even when toolkits eventually reach perfect determinism in training.
You can also look at the complete explanation [here](https://stackoverflow.com/questions/50744565/how-to-handle-non-determinism-when-training-on-a-gpu)

You can also take a look at this [video](https://developer.nvidia.com/gtc/2019/video/S9911). Thanks!

**Comment by duncanriach** [comment]
For anyone visiting this issue, please see the documentation for [tf.config.experimental.enable_op_determinism](https://www.tensorflow.org/api_docs/python/tf/config/experimental/enable_op_determinism) and also the detailed status of ops [here](https://github.com/NVIDIA/framework-determinism/blob/master/doc/tensorflow_status.md).
