### ISSUE TITLE
ERROR: undeclared inclusion(s) in rule '//tensorflow/core/kernels:multinomial_op_gpu'

### ISSUE THREAD

**Issue by FlorinAndrei** [tensorflow/tensorflow#4190]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

none

### Environment info
Operating System:

Ubuntu 16.04 64bit with all updates applied

Installed version of CUDA and cuDNN: 

I've downloaded these from Nvidia and installed them per "official" instructions:

- cuda_8.0.27_linux.run
- cuda_8.0.27.1_linux.run
- cudnn-8.0-linux-x64-v5.1.tgz

(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

```
# ls -l /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root   560184 Sep  3 21:37 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Sep  3 21:37 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Sep  3 21:37 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.27
-rwxr-xr-x 1 root root   394472 Sep  3 21:37 /usr/local/cuda/lib64/libcudart.so.8.0.27
-rw-r--r-- 1 root root   737516 Sep  3 21:37 /usr/local/cuda/lib64/libcudart_static.a
lrwxrwxrwx 1 root root       13 Sep  3 21:37 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 root root       17 Sep  3 21:37 /usr/local/cuda/lib64/libcudnn.so.5 -> libcudnn.so.5.1.5
-rwxr-xr-x 1 root root 79337624 Sep  3 21:37 /usr/local/cuda/lib64/libcudnn.so.5.1.5
-rw-r--r-- 1 root root 69756172 Sep  3 21:37 /usr/local/cuda/lib64/libcudnn_static.a
```

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)

```
# git rev-parse HEAD
3c177a54cf48efdab49d716ee27936ead31c3388
```

2. The output of `bazel version`

```
# bazel version     
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 01 00:00:00 1970 (0)
Build timestamp: Thu Jan 01 00:00:00 1970 (0)
Build timestamp as int: 0
```

It's bazel 0.3.1 actually. No idea why the output from version is so useless. I've installed it from the official deb repo.

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

```
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
./configure

# Hit ENTER on every question except:
# Do you wish to build TensorFlow with GPU support? (answer: y)
# Please specify a list of comma-separated Cuda compute capabilities you want to build with. (answer: 6.1)

bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```

It's actually a bit more complicated, as the first attempt fails to even begin to compile. So I delete the TF repo, clone again, and configure/build again. It begins to compile, keeps chugging along for a few minutes, and then I get the error shown in the title.

More details here (you'll find there a fully automated procedure to completely reproduce the environment and build process):

https://github.com/tensorflow/tensorflow/issues/4105#issuecomment-244573108

### What other attempted solutions have you tried?

Tried to google around, hoping it's a known issue. Could not find anything related.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

This is the end of the build messages:

https://gist.github.com/FlorinAndrei/b378e45709185ef40808e7537a3df4e8

**Comment by unbuilt** [comment]
I got the same issue here.
ERROR: /home/unbuilt/Works/tensorflow/tensorflow/core/kernels/BUILD:1550:1: undeclared inclusion(s) in rule '//tensorflow/core/kernels:depth_space_ops_gpu':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/depthtospace_op_gpu.cu.cc':
  '/usr/local/cuda-8.0/include/cuda_runtime.h'
  '/usr/local/cuda-8.0/include/host_config.h'
  '/usr/local/cuda-8.0/include/builtin_types.h'
  '/usr/local/cuda-8.0/include/device_types.h'
...

**Comment by davidzchen** [comment]
When you run `./configure`, did you explicitly specify your CUDA version? If not, then you are most likely hitting #3985.

**Comment by FlorinAndrei** [comment]
I did not specify the CUDA version explicitly. I try again with explicit settings and will let you know how it goes.

**Comment by FlorinAndrei** [comment]
I've explicitly specified CUDA version 8.0 and now compilation fails in a different way:

https://github.com/tensorflow/tensorflow/issues/4214

**Comment by davidzchen** [comment]
@FlorinAndrei Thanks. In that case, I'll de-dup this with #3985.

@4214 appears to be unrelated.
