### ISSUE TITLE
Could not import PIL.Image. The use of `array_to_img` requires PIL

### ISSUE THREAD

**Issue by suresh-s** [tensorflow/tensorflow#41901]
**System information**
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
OS Platform and Distribution : ubuntu 18.04 LTS
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Jetson Nano
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): tensorflow==1.15.2+nv20.6
Python version: 3.6
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version: CUDA 10.2 / cuDNN 8.00
GPU model and memory: NVIDIA Tegra X1 (nvgpu)/integrated and 4GB memory
Keras: 2.0.5

**Describe the problem**

While executing an application, i got following exception

![image](https://user-images.githubusercontent.com/2168986/88942166-83c02300-d2a7-11ea-8948-551074acb48d.png)

After that, I installed pillow-7.2.0. But i am getting same error message **ImportError: Could not import PIL.Image. The use of array_to_img requires PIL**.

Could you please help me to resolve the issue?

**Comment by ravikyram** [comment]
@suresh-s 

Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!
