### ISSUE TITLE
Should this be "ZerosLike" ?

### ISSUE THREAD

**Issue by amturati** [tensorflow/tensorflow#41912]
https://github.com/tensorflow/tensorflow/blob/05632ed9bad5bf9eee3edd57ade3d8250d580019/tensorflow/c/eager/gradients.cc#L104

**Comment by amturati** [comment]
@saxenasaurabh

**Comment by alextp** [comment]
Indeed. Can you fix?

**Comment by ymodak** [comment]
Closing this issue since its fixed with [7fafd21](https://github.com/tensorflow/tensorflow/commit/7fafd216eb116a092a85d35d1e56d486c36d8727#diff-90a2d1c5b6dd65802ebf77e266d4d2e5). Thanks for the fix!
