### ISSUE TITLE
tf.math.reduce_euclidean_norm can not be in tf.function with experimental_compile=True

### ISSUE THREAD

**Issue by WindQAQ** [tensorflow/tensorflow#41915]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.0-dev20200730
- Python version: colab
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: no

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

```
EuclideanNorm: unsupported op: No registered 'EuclideanNorm' OpKernel for XLA_CPU_JIT devices compatible with node {{node EuclideanNorm}}
```

**Describe the expected behavior**

The op can run as usual.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python3
import tensorflow as tf

x = tf.complex(tf.random.uniform(shape=(5, 5)), tf.random.uniform(shape=(5, 5)))

@tf.function(experimental_compile=True)
def reduce_euclidean_norm(x):
  return tf.math.reduce_euclidean_norm(x)

print(reduce_euclidean_norm(x))
```

https://colab.research.google.com/drive/1YENmpGDLU6kCupseizWTO1wBiDDj8v9x?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@WindQAQ 

I have tried in colab with TF nightly version(2.4.0-dev20200730) and was able to reproduce the issue.However if I change 
`@tf.function(experimental_compile=True)`to `@tf.function`in the code I am not seeing any issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/5167b8076f8f98b64664c351843fec89/untitled209.ipynb).Thanks!

**Comment by WindQAQ** [comment]
> @WindQAQ
> 
> I have tried in colab with TF nightly version(2.4.0-dev20200730) and was able to reproduce the issue.However if I change
> `@tf.function(experimental_compile=True)`to `@tf.function`in the code I am not seeing any issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/5167b8076f8f98b64664c351843fec89/untitled209.ipynb).Thanks!

Yes, but in that case, it does not utilize XLA.

**Comment by mdanatg** [comment]
It looks like the ops is missing an XLA kernel for the gradient. @cheshire could you triage?

**Comment by WindQAQ** [comment]
Thanks for the triage! I think it misses the XLA kernel for `EuclideanNorm` instead of its gradient as the gradient is defined with python ops [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/math_grad.py#L52-L64).
