### ISSUE TITLE
pbfile output different result with checkpoint when using slim model

### ISSUE THREAD

**Issue by cryandme** [tensorflow/tensorflow#41918]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by amahendrakar** [comment]
@cryandme,
Could you please elaborate and describe the issue you are facing. 

Also, in order to expedite the trouble-shooting process, please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!

**Comment by cryandme** [comment]
I am very glad to receive your reply.
The version of TensorFlow I use is 1.13.1,
Looking forword to your reply.Thanks!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tensorflow/tensorflow"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 晚上7:45
收件人:&nbsp;"tensorflow/tensorflow"<tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"樱雪如薇"<1003328735@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tensorflow/tensorflow] pbfile output different result with checkpoint when using slim model (#41918)





 
@cryandme,
 Could you please elaborate and describe the issue you are facing.
 
Also, in order to expedite the trouble-shooting process, please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

test_data.zip (158.73M, 2020年09月02日 09:39 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=77613335895d2392eaf5fe0e1f63054b075401000b02545518590a07584e035253001e0c5f51004956570a0d0d00525d03530205396e37105012476a5d0243051b1b5a45395e&t=exs_ftn_download&code=5a359c7d




code.zip (135.35M, 2020年09月02日 09:41 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=04386135845ceb91e6acac0e12325349580f595652035650145c0400551f55555c0a4c570d53024b090f5907525659505c000402343a6105565c041b4e5b116604&t=exs_ftn_download&code=98a542af

**Comment by amahendrakar** [comment]
@cryandme,
To help up reproduce the issue, please provide the complete code and the dataset too.

Also, TensorFlow 1.13 is not actively supported. please update TensorFlow to 2.x or v1.15 . Thanks!

**Comment by cryandme** [comment]
@amahendrakar，
I don't think my question has anything to do with the tensorFlow version,because I solidified the model (without calling the NETS module in TF.Slim), CKPT and PB had the same detection result,but Now the detection accuracy of PB decreases greatly when the model is solidified (nets in the called Slim).and the code used twice is exactly the same (CKPT to PB)
Also,I have sent l the complete code and the dataset to you

**Comment by amahendrakar** [comment]
@cryandme,
I am not able to access the links you have given due to network restrictions. Could you please try sending the data in an alternative way? Thanks!
