### ISSUE TITLE
Support outputting tree leaves in BoostedTreesClassifier

### ISSUE THREAD

**Issue by mafhcow** [tensorflow/tensorflow#41913]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.14 and would like to migrate to 2.3
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Currently the `BoostedTreesClassifier` canner estimator does not support outputting the activated leaves of the tree on output, instead only supporting outputting the natural output of the classifier. The feature request I am making is to also support outputting the leaves, such as what the `CoreGradientBoostedDecisionTreeEstimator` in TF 1.14 supported via the flag `output_leaf_index=True`. With this flag the estimator would also provide an output on which leaves were output on an evaluation.

**Will this change the current api? How?**
The estimator will gain an initialization argument of `output_leaf_index`. When set to true, the estimator would add leaf indices as one of its predict keys which will be output to the user on evaluation.

**Who will benefit with this feature?**
One common use case of boosted trees models is in stacked architectures where the output of the tree model is fed into a deep neural network. For this use case the leaf indices are oftentimes more useful as an input to the DNN than the raw prediction of the tree model. This use case is supported in TF 1 but not in TF 2 so it prevents migrating code for this use case to TF 2.

**Comment by rmothukuru** [comment]
@mafhcow ,
Sorry for the delayed response. In the **`Tensorflow Version 2.x`**, since we use [TF Keras](https://www.tensorflow.org/api_docs/python/tf/keras/) and [tf.data](https://www.tensorflow.org/guide/data) predominantly and don't use [Estimators](https://www.tensorflow.org/guide/estimator) much, can you please let us know if this Feature is still relevant? 

Thanks!
