### ISSUE TITLE
tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error

### ISSUE THREAD

**Issue by Shikaz** [tensorflow/tensorflow#41937]
I am trying to build an image with Centos and tensorflow 1.14 GPU, I have installed in the host the Cuda 10 and tried also 11, in the image i tried 10 and also 11 , different versions and I keep getting below error

tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error

Full Error:
>>> import tensorflow as tf
/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
>>> print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
2020-07-31 16:03:16.558174: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2020-07-31 16:03:16.562049: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2020-07-31 16:03:16.562109: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: c15680640844
2020-07-31 16:03:16.562130: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: c15680640844
2020-07-31 16:03:16.562276: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 418.152.0
2020-07-31 16:03:16.562335: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 418.152.0
2020-07-31 16:03:16.562359: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 418.152.0
Num GPUs Available:  0

I tried nvidia-modprobe, check /dev/nvidia script, install different cudn, nvidia-smi working fine...etc

System Info:

Python 3.6.9
tensorflow-estimator (1.14.0)
tensorflow-gpu (1.14.0)

kmod-nvidia-latest-dkms-418.152.00-1.el7.x86_64
nvidia-modprobe-latest-418.152.00-1.el7.x86_64
nvidia-driver-latest-NvFBCOpenGL-418.152.00-1.el7.x86_64
nvidia-driver-latest-devel-418.152.00-1.el7.x86_64
nvidia-driver-latest-418.152.00-1.el7.x86_64
nvidia-driver-local-repo-rhel7-418.152.00-1.0-1.x86_64
nvidia-driver-latest-cuda-libs-418.152.00-1.el7.x86_64
nvidia-xconfig-latest-418.152.00-1.el7.x86_64

Fri Jul 31 16:02:21 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.152.00   Driver Version: 418.152.00   CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M60           Off  | 00000000:00:1B.0 Off |                    0 |
| N/A   39C    P0    42W / 150W |      0MiB /  7618MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla M60           Off  | 00000000:00:1C.0 Off |                    0 |
| N/A   35C    P0    41W / 150W |      0MiB /  7618MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla M60           Off  | 00000000:00:1D.0 Off |                    0 |
| N/A   36C    P0    47W / 150W |      0MiB /  7618MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla M60           Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   35C    P0    47W / 150W |      0MiB /  7618MiB |     53%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by amahendrakar** [comment]
@Shikaz,
TensorFlow v1.14 is not actively supported. 

Please try installing TensorFlow 2.x or v1.15 and make sure you have the compatible dependency versions installed as per the [tested build configurations](https://www.tensorflow.org/install/source#gpu). Thanks!

**Comment by Shikaz** [comment]
> @Shikaz,
> TensorFlow v1.14 is not actively supported.
> 
> Please try installing TensorFlow 2.x or v1.15 and make sure you have the compatible dependency versions installed as per the [tested build configurations](https://www.tensorflow.org/install/source#gpu). Thanks!

@amahendrakar I don't think this is the issue.

I tried the following and same error:

gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)

tensorflow-gpu                2.3.0

cuda-repo-rhel7-10-1-local-10.1.243-418.87.00-1.0-1.x86_64
cuda-license-10-1-10.1.243-1.x86_64
nvidia-driver-latest-cuda-libs-418.152.00-1.el7.x86_64
cuda-cudart-10-1-10.1.243-1.x86_64

**No meaningful error , is there a way to debug as failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error does not help much**


>>> import tensorflow as tf
2020-07-31 19:30:35.310489: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
>>> print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
2020-07-31 19:30:39.964043: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-07-31 19:30:39.967983: E tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2020-07-31 19:30:39.968040: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: c15680640844
2020-07-31 19:30:39.968061: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: c15680640844
2020-07-31 19:30:39.968189: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 418.152.0
2020-07-31 19:30:39.968248: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 418.152.0
2020-07-31 19:30:39.968271: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 418.152.0
Num GPUs Available:  0

**Comment by Shikaz** [comment]
I tried to instead of do pip install the gpu tensorflow to build using bazel and still no luck.

**Comment by amahendrakar** [comment]
@Shikaz,
Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/40920#issuecomment-653279389) from a similar issue and let us know if it helps. Thanks!

**Comment by Shikaz** [comment]
> @Shikaz,
> Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/40920#issuecomment-653279389) from a similar issue and let us know if it helps. Thanks!

@amahendrakar - This is different error, i am getting CUDA_ERROR_UNKNOWN: unknown error , the one you shared is CUDA_ERROR_NO_DEVICE which was fixed by updating the driver.

Is installing on Centos differs than Ubuntu ? also is there a way to debug or get more insight on what CUDA_ERROR_UNKNOWN means

**Comment by amahendrakar** [comment]
@Shikaz,
The [installation steps](https://www.tensorflow.org/install/source) for all Linux distributions are the same. 

Could you please provide the complete code you are running. Also, check [#32623](https://github.com/tensorflow/tensorflow/issues/32623) and [#7653](https://github.com/tensorflow/tensorflow/issues/7653) and let us know if it works. Thanks!

**Comment by hlmhlr** [comment]
> > @Shikaz,
> > TensorFlow v1.14 is not actively supported.
> > Please try installing TensorFlow 2.x or v1.15 and make sure you have the compatible dependency versions installed as per the [tested build configurations](https://www.tensorflow.org/install/source#gpu). Thanks!
> 
> @amahendrakar I don't think this is the issue.
> 
> I tried the following and same error:
> 
> gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)
> 
> tensorflow-gpu 2.3.0
> 
> cuda-repo-rhel7-10-1-local-10.1.243-418.87.00-1.0-1.x86_64
> cuda-license-10-1-10.1.243-1.x86_64
> nvidia-driver-latest-cuda-libs-418.152.00-1.el7.x86_64
> cuda-cudart-10-1-10.1.243-1.x86_64
> 
> **No meaningful error , is there a way to debug as failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error does not help much**
> 
> > > > import tensorflow as tf
> > > > 2020-07-31 19:30:35.310489: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
> > > > print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
> > > > 2020-07-31 19:30:39.964043: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
> > > > 2020-07-31 19:30:39.967983: E tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
> > > > 2020-07-31 19:30:39.968040: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: c15680640844
> > > > 2020-07-31 19:30:39.968061: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: c15680640844
> > > > 2020-07-31 19:30:39.968189: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 418.152.0
> > > > 2020-07-31 19:30:39.968248: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 418.152.0
> > > > 2020-07-31 19:30:39.968271: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 418.152.0
> > > > Num GPUs Available:  0

Dear @Shikaz, How did you manage to solve your issue as i am also facing the same. and getting no solution anywhere. It really would be helpful if you could share the details. 
Thanks,

**Comment by amahendrakar** [comment]
@hlmhlr,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by hlmhlr** [comment]
> @hlmhlr,
> Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

Dear @amahendrakar, Thanks for your response. Since i didn't get any feedback at the time of error and i restarted the machine just to give a one more try and luckily it worked without error. But it is still puzzled for me that why  this error occurred.
Thanks,
