### ISSUE TITLE
Only 1 subgraph is currently supported - CMSIS-NN

### ISSUE THREAD

**Issue by Sixaxis9** [tensorflow/tensorflow#41932]
@tensorflow/micro

System information

Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): make with Linux Ubuntu 20.04, complied on Atmel Studio on Windows 10, Python 3.7.7
TensorFlow installed from (source or binary): downloaded from master
Tensorflow version (commit SHA if source): 2.3.0, e544dce
Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Atmel SAMD51 - Atmel Studio

**Describe the problem**
After some issue to link correctly the TFLite with cmsis-nn kernels files into my Atmel Studio project I have built a static library with Atmel Studio and linked the .a file. To do that I make the project with TAGS=cmsis-nn, copy the the files from a Keil project (I used the image recognition example) from the make directory and compile with Atmel Studio to get the .a file.

When I run inference compiling the C files (obtained without the cmsis-tag in the Tensorflow-Lite subdirectory of the image recognition example in the make folder) within the project everything works fine. When I run inference with the static library obtained from making with the cmsis-nn tag I get the following error: "Only 1 subgraph is currently supported. Exiting with status 1". The flatbuffer file is the same.

**Please provide the exact sequence of commands/steps when you ran into the problem**
Please refere to this Colab to see the python code: https://drive.google.com/file/d/1k-9Id6ljpf4EjlcYIy6D4-fAHwOg1hI-/view?usp=sharing
Please refere there to see the trained models: https://drive.google.com/drive/folders/1hQgInGGy3A7EEOB0xZHw5CgheXp8nl_9?usp=sharing
Please refere there for the project (in the cmsis-nn brench): https://github.com/Sixaxis9/TFLite-SAMD51
Replicating the issue: copying and pasting the flatbuffer inside a working project with the cmsis-nn version of TFLite, loading the model and running inference.

**Comment by Sixaxis9** [comment]
Edit: added links to models

**Comment by brad-nix** [comment]
I get the same error, "Only 1 subgraph is currently supported. Exiting with status 1" when trying to implement RNNs.
[Issue: 36688](https://github.com/tensorflow/tensorflow/issues/36688)

**Comment by Sixaxis9** [comment]
Update on the issue. I manage to solve the problem and to compile the C files within the uC project. I run the make with the TAGS=cmsis-nn and TARGET=sparkfun_edge (since my board has a Cortex M4-F, same as Sparkfun edge) and imported the folders "tensorflow" and "third_party" in the my project directory from the Kiel folder created by the makefile. After some dependancy fixing I successfully built the project.
I now have another problem, my output are constant zeros, but I'll open another issue for that.

**Comment by ossa77** [comment]
> I get the same error, "Only 1 subgraph is currently supported. Exiting with status 1" when trying to implement RNNs.
> [Issue: 36688](https://github.com/tensorflow/tensorflow/issues/36688)

bro did u find sloution

**Comment by Sixaxis9** [comment]
Hi ossa77, are you having troubles with RNNs? 
I might help on CNNs
