### ISSUE TITLE
Tensorflow 2.2.0 require scipy-1.4.1??

### ISSUE THREAD

**Issue by beew** [tensorflow/tensorflow#41941]
**System information**
- OS Platform and Distribution :Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 2.2.0
- Python version: 3.8.5
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version:  Cuda10.0, cudnn 7.6.5.32
- GPU model and memory: GTX1070 , 8G

**Describe the problem**
installing tensorflow removes existing scipy 1.5.2 and installs 1.4.1

**Provide the exact sequence of commands / steps that you executed before running into the problem**

After building tensorflow2.2.0 successfully, I installed it with
```
pip install --no-cache-dir tensorflow-2.2.0-cp38-cp38-linux_x86_64.whl
```
(pip = pip3 in my set up)

It was installed successfully and I checked the installation with some tests, all passed. But it uninstalls my already exist scipy 1.5.2 and installed 1.4.1

```
Attempting uninstall: scipy
    Found existing installation: scipy 1.5.2
    Uninstalling scipy-1.5.2:
      Successfully uninstalled scipy-1.5.2
```

**Comment by mihaimaruseac** [comment]
Please see #40884 and issues linked there as well as the PRs listed in the transitive set of github issues/prs from there.

In short, TF 2.3 no longer needs it and older TF will remove the dependency when a new patch release happens.

**Comment by beew** [comment]
@mihaimaruseac 

So it means the restriction is not necessary and upgrading scipy back to 1.5.2 after installing tensorflow-2.2.0 won't break it?
Please clarify. Thanks.

**Comment by mihaimaruseac** [comment]
Yes, you can upgrade.
