### ISSUE TITLE
AOT compiled graph is 2-7x slower than Python

### ISSUE THREAD

**Issue by battuzz** [tensorflow/tensorflow#41940]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2
- Python version: 3.6.8
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**

For `tf.matmul` and `tf.linalg.triangular_solve` AOT is much slower (2-7x) than the equivalent TF-Python version. For `triangular_solve`, which is easy to hand-code, this also applies wrt bespoke C implementation.

**Describe the expected behavior**

I expect that the computation time of the AOT compiled graph is better than the Python counterpart.

**Standalone code to reproduce the issue**

The graph is the following:

```python
def trisolve(A, b):
    """ Builds a graph. A is a lower-triangular MxM matrix, b is a Mx1 column vector """    
    res = tf.linalg.triangular_solve(A, b, lower=True)    
    return res

M = 2048
predict_fn = tf.function(trisolve,
        input_signature=[tf.TensorSpec(shape=[M,M], dtype=tf.float64, name='A'),
        tf.TensorSpec(shape=[M,1], dtype=tf.float64, name='b')], experimental_compile=False)
    
module_to_save = tf.Module()
module_to_save.predict = predict_fn
tf.saved_model.save(module_to_save, 'saved_model', signatures={'serving_default': module_to_save.predict})
```

The graph is then compiled with:
```bash
$ cd saved_model
$ saved_model_cli aot_compile_cpu --checkpoint_path .\variables\variables --dir . --signature_def_key serving_default --target_triple x86_64-none-windows --cpp_class trisolve --output_prefix libs64/libtrisolve --tag_set serve
```

and is linked to a simple cpp file that just runs the model for benchmark.

```cpp
#include <iostream>
#include "third_party/eigen3/unsupported/Eigen/CXX11/Tensor"
#include "libtrisolve.h" // generated
#include <chrono>
#include <fstream>

using namespace std::chrono;

#define M 2048

int main(int argc, char** argv) {  
  trisolve model;  

  int i, j, idx;
  double *test_A;   // Initialize with a MxM lower triangular matrix
  double *test_b;   // Initialize with a Mx1 vector

  std::copy(test_A, test_A+M*M, model.arg0_data());
  std::copy(test_b, test_b+M, model.arg1_data());
  
  int N = 1000;
  auto tStart = high_resolution_clock::now(); 
  for (int i = 0; i < N; i++)
    model.Run();
  auto tEnd = high_resolution_clock::now();
  auto duration = duration_cast<microseconds>((tEnd - tStart)/N); 
  std::cout << "Time TF Compiled: " << duration.count() << "us" << std::endl;

  return 0;
}
```

**Performance Issue:**

Triangular Solve (as above):
- A very simple single-threaded C++ implementation takes just 2ms;
- Running the triangular solve from the Python code, takes ~3ms;
- Running the compiled executable, instead, takes 17ms.

MatMul (multiplication of two square matrices 2048x2048):
- Python version takes ~150ms
- Compiled version takes ~370ms

**Comment by marcoadurno** [comment]
Hi @ymodak  ,

Have you been able to replicate the issue? Do you need any further information?

Best Regards,

Marco

**Comment by sanjoy** [comment]
This isn't too surprising for triangular solve since XLA has fairly naive implementation.

For GEMM this is quite surprising.  Maybe the AOT compiled GEMM is using only one thread?  Can you try passing `--enable_multithreading` to `saved_model_cli aot_compile_cpu`?

CC @ebrevdo

**Comment by ebrevdo** [comment]
For `aot_compile_cpu` if I remember correctly we explicitly disable this because we avoid adding additional external dependencies on things like `libnsync`.  If you look at the docstring for `enable_multithreading` you'll see it's not supported.

**Comment by battuzz** [comment]
I can confirm that `--enable_multithreading` raises this exception:

`NotImplementedError: Multithreading is not currently supported because it requires additional dependencies in the AOT runtime.`

However I think multithreading is not the problem for triangular solve in this case because, as I stated above, a very simple single-threaded implementation in C is ~8 times faster than the tf compiled version.

This is my implementation of triangular solve:
```cpp
void Solve(double* A, double* b, double* ret, int S) {
    // A is SxS, b is size S, ret is size S
    
    for (int i = 0; i < S; i++) {
        double acc = 0.0;
        for (int j = 0; j < i; j++) {
            acc += *(A+i*S+j) * (*(ret + j));
        }
        *(ret + i) = (*(b + i) - acc) / (*(A + i*S + i));
    }

}
```

**Comment by sanjoy** [comment]
Hi @battuzz,

I believe this issue reported two issues:

 * TriangularSolve is much slower than expected.  This has nothing to with multi-threading, XLA CPU just does not have an optimized triangular solve implementation today.
 * Matrix multiply is much slower than expected.  In this case I believe the Python version is using multiple threads while XLA isn't.  XLA does support multi-threaded matrix multiplies, but that isn't exposed via the `saved_model_cli` interface.  @ebrevdo I was not able to see how tfcompile depends on nsync.

**Comment by battuzz** [comment]
@sanjoy I agree with you about the matrix multiplication. I tried with a smaller matrix (256x256) and the performance is similar to the Python version.

However, for the triangular solve, I don't believe that the cause of such slowdown is a missing optimized implementation, since it is really easy to make one that goes much faster.

Is there the possibility that something else is going on?

**Comment by sanjoy** [comment]
> Is there the possibility that something else is going on?

Currently XLA CPU lowers TriangularSolve to a fairly [loop](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/service/triangular_solve_expander.cc) of HLO instructions.  It is slightly surprising but entirely possible that a naively written C++ implementation will be faster.  Would you be willing to contribute a C++ implementation to XLA?

@hawkinsp does JAX have an optimized custom-call implementation for `triangular-solve`?

**Comment by battuzz** [comment]
Hi @sanjoy , 

I've checked the XLA CPU implementation of TriangularSolve and honestly I think some weird stuff is going on, because apparently it is calculating unnecessary matrix inversions that take a lot of time. 
However my experience with XLA and C++ is very limited to be able to contribute directly. I wrote a graph implementation of triangular solve, instead, that leverages dot products between rows of L and the solution vector x, and works for N-dimensional inputs:

```python
def triangular_solve(L,b):
    """ Solves the equation Lx = b given that L is lower triangular
    
    Parameters:
        - L: a tensor with dimensions [..., M, M]
        - b: a tensor with dimensions [..., M, N]
    """
    # Make all matrices with unitary diagonal
    d = tf.linalg.diag_part(L)
    d = tf.expand_dims(tf.pow(d,-1), axis=-1)
    b = b*d
    L = L*d

    M = tf.shape(b)[-2]
    x = tf.TensorArray(tf.float64, size=M, clear_after_read=False, dynamic_size=False)
    
    # Move last two axis in front    
    b = tf.einsum("...ij->ij...", b)
    L = tf.einsum("...ij->ij...", L)
    
    x = x.unstack(tf.zeros_like(b))                
    L = tf.expand_dims(L, 2)

    def body_fn(i, x):
        coeffsum = tf.reduce_sum(tf.multiply(tf.gather_nd(L, [i]), x.stack()), axis=0)
        x = x.write(i, tf.gather_nd(b, [i]) - coeffsum)
        i = i+1
        return i,x
    
    cond_fn = lambda i,*_: tf.less(i, M)
    _,x = tf.while_loop(cond_fn, body_fn, (tf.constant(0), x))

    return tf.einsum("ij...->...ij", x.stack())
```

When compiled in XLA, this implementation is fast for small matrices (~ 5-10 times faster than `tf.linalg.triangular_solve` for a matrix 256x256), but slows down when the matrix is large, probably due to the TensorArray stack() use in the loop...

I hope this may help in optimizing the performance of `tf.linalg.triangular_solve` in XLA. Is there someone able to do that?

Thanks

**Comment by battuzz** [comment]
Hi @sanjoy 

While searching for a workaround for the poor runtime performance of `tf.linalg.triangular_solve`, I have just found another problem that may be correlated with this issue (otherwise, you can tell me and I'll create a new issue for this).

Consider the following class:
```python
class ModelA():
    def __init__(self, L):
        """ L is a lower triangular MxM matrix """
        self.L = L
        M = self.L.shape[-1]
        self.invL = tf.linalg.triangular_solve(self.L, tf.eye(M, dtype=tf.float64), lower=True)    # Computes the inverse of L
    
    def predict(self, b):        
        """ b is a Mx1 vector """                
        return tf.matmul(self.invL, b)
```

This works just fine, and the compiled graph for `predict` is just the `matmul` operation.

However, if I move the `tf.linalg.triangular_solve` operation in the predict function in this way:
```python
class ModelA1():
    def __init__(self, L):
        """ L is a lower triangular MxM matrix """
        self.L = L
    
    def predict(self, b):        
        """ b is a Mx1 vector """                
        M = self.L.shape[-1]
        invL = tf.linalg.triangular_solve(self.L, tf.eye(M, dtype=tf.float64), lower=True)    # Computes the inverse of L
        return tf.matmul(invL, b)
```
the compiled graph shouldn't change as `invL` is constant and can be optimized away. Unfortunately this does not happen with `modelA1`. 
I believe this is a problem specifically for `tf.linalg.triangular_solve` because, if I compute the inverse using `tf.linalg.inv` instead (as in `modelB` herebelow), the optimization procedure works just fine and the compiled `predict` function only performs the `matmul` and not the inverse.

```python
class ModelB():
    def __init__(self, L):
        """ L is a lower triangular MxM matrix """
        self.L = L
    
    def predict(self, b):        
        """ b is a Mx1 vector """                
        invL = tf.linalg.inv(self.L)    # Computes the inverse of L
        return tf.matmul(invL, b)
```

**Comment by hawkinsp** [comment]
@sanjoy On CPU, JAX uses a CustomCall to invoke LAPACK for triangular solves. I guess the closest equivalent in TF would be to call Eigen.

The HLO TriangularSolve implementation being called here was never particularly intended for CPU use (more GPU and TPU, primarily TPU).

**Comment by sanjoy** [comment]
> the compiled graph shouldn't change as invL is constant and can be optimized away. Unfortunately this does not happen with modelA1.

I didn't quite follow this -- isn't `invL` dependent on `L` which is a runtime variable value (i.e. not a constant)?

**Comment by battuzz** [comment]
`L` should become a constant when compiling only function `predict`, as there is no possibility of modifying `L` from the resulting graph.

This is the resulting graph for `modelA1`.

![image](https://user-images.githubusercontent.com/456857/91410139-bf1e2500-e846-11ea-877d-43ee7c7a2aa5.png)

While this is the resulting graph for `modelB` that does the same thing, but with `tf.linalg.inv` instead of `tf.linalg.triangular_solve`. In this case the inverse is precomputed..

![image](https://user-images.githubusercontent.com/456857/91410600-6e5afc00-e847-11ea-8d65-cd7b5507be0b.png)

**Comment by battuzz** [comment]
Hi @sanjoy 

I have an update on this last issue: I thought the culprit was the `tf.linalg.triangular_solve`, but now I think the issue is with `tf.eye`. In fact, this `modelC` below behaves exactly like `modelB` and will be optimized:

```python
import numpy as np

class ModelC():
    def __init__(self, L):
        """ L is a lower triangular MxM matrix """
        self.L = L
    
    def predict(self, b):        
        """ b is a Mx1 vector """                
        M = self.L.shape[-1]
        eye = tf.constant( np.eye(M) , dtype=tf.float64)   # Use numpy to generate an eye matrix
        invL = tf.linalg.triangular_solve(self.L, eye, lower=True)    # Computes the inverse of L
        return tf.matmul(invL, b)
```

I believe that the output of `tf.eye(N)`, when `N` is constant, sometimes is not treated as constant, and thus may break constant propagation.

**Comment by sushreebarsa** [comment]
@battuzz 
It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Can you please execute your code using Latest Version 2.7.0 and let us know if the issue still persists? Thanks!

**Comment by battuzz** [comment]
@sushreebarsa  Thank you for your reply, I'll have a look as soon as possible!

**Comment by battuzz** [comment]
@sushreebarsa Here I am with some results!
I ran some tests with Tensorflow 2.7.0 and here are the results divided by the problems I've found:

1) The CPU implementation of `triangular_solve` is still very very slow. For my tests I used a matrix 2048x2048 and I measured the following inference times:

- Naive implementation in pure C (I used the code above, single thread):    **~1ms**
- `tf.linalg.triangular_solve` from Python:  (multithread)   **~3ms**
- AOT compiled version of `tf.linalg.triangular_solve` (single thread):        **~13ms**
- AOT compiled version of `my_triangular_solve` (single thread):             **~4ms**      

Here is the naive implementation of `my_triangular_solve` (I'm sure something better can be done):
```python
def my_triangular_solve(A, b):
    S = tf.shape(A)[0]
    ret = tf.zeros(S, dtype=tf.float64)

    for i in tf.range(S):
        acc = tf.reduce_sum(A[i,:] * ret)
        ret = tf.tensor_scatter_nd_update(ret, [[i]], (b[i] - acc) / A[i,i])
    
    return tf.reshape(ret, (1,-1))
```

Now, I know it will be hard to obtain the same performance of a pure C implementation (even though it would be amazing), but the current implementation is way slower than expected... 


2) I compared the `ModelA` vs `ModelA1` classes listed above in this thread and their performance is now similar, so the `triangular_solve` operation will be precomputed as expected.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
