### ISSUE TITLE
tensorflow-io 0.14.0 requires tensorflow<2.3.0,>=2.2.0, but you'll have tensorflow 2.3.0 which is incompatible

### ISSUE THREAD

**Issue by tkrsh** [tensorflow/tensorflow#41954]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
 - TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3.0
- Python version:3.8.2
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: 10.1
- GPU model and memory: 1650 4GB

**Describe the problem**
Cant use tensorflow-io , if I try to install tensorflow-io with pip  tensorflow downgrades  please fix this dependency issue.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
pip install tensorflow 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
pip install tensorflow 
Defaulting to user installation because normal site-packages is not writeable
Collecting tensorflow

Using cached tensorflow-2.3.0-cp38-cp38-manylinux2010_x86_64.whl (320.5 MB)
Requirement already satisfied: wrapt>=1.11.1 in ./.local/lib/python3.8/site-packages (from tensorflow) (1.12.1)
Requirement already satisfied: gast==0.3.3 in ./.local/lib/python3.8/site-packages (from tensorflow) (0.3.3)
Requirement already satisfied: numpy<1.19.0,>=1.16.0 in ./.local/lib/python3.8/site-packages (from tensorflow) (1.18.4)
Requirement already satisfied: tensorflow-estimator<2.4.0,>=2.3.0 in ./.local/lib/python3.8/site-packages (from tensorflow) (2.3.0)
Requirement already satisfied: termcolor>=1.1.0 in ./.local/lib/python3.8/site-packages (from tensorflow) (1.1.0)
Requirement already satisfied: astunparse==1.6.3 in ./.local/lib/python3.8/site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: google-pasta>=0.1.8 in ./.local/lib/python3.8/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: keras-preprocessing<1.2,>=1.1.1 in ./.local/lib/python3.8/site-packages (from tensorflow) (1.1.2)
Requirement already satisfied: protobuf>=3.9.2 in ./.local/lib/python3.8/site-packages (from tensorflow) (3.12.2)
Requirement already satisfied: h5py<2.11.0,>=2.10.0 in ./.local/lib/python3.8/site-packages (from tensorflow) (2.10.0)
Requirement already satisfied: tensorboard<3,>=2.3.0 in ./.local/lib/python3.8/site-packages (from tensorflow) (2.3.0)
Requirement already satisfied: scipy==1.4.1 in ./.local/lib/python3.8/site-packages (from tensorflow) (1.4.1)
Requirement already satisfied: grpcio>=1.8.6 in ./.local/lib/python3.8/site-packages (from tensorflow) (1.29.0)
Requirement already satisfied: six>=1.12.0 in /usr/lib/python3/dist-packages (from tensorflow) (1.14.0)
Requirement already satisfied: wheel>=0.26 in /usr/lib/python3/dist-packages (from tensorflow) (0.34.2)
Requirement already satisfied: opt-einsum>=2.3.2 in ./.local/lib/python3.8/site-packages (from tensorflow) (3.2.1)
Requirement already satisfied: absl-py>=0.7.0 in ./.local/lib/python3.8/site-packages (from tensorflow) (0.9.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from protobuf>=3.9.2->tensorflow) (45.2.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in ./.local/lib/python3.8/site-packages (from tensorboard<3,>=2.3.0->tensorflow) (0.4.1)
Requirement already satisfied: google-auth<2,>=1.6.3 in ./.local/lib/python3.8/site-packages (from tensorboard<3,>=2.3.0->tensorflow) (1.16.0)
Requirement already satisfied: markdown>=2.6.8 in ./.local/lib/python3.8/site-packages (from tensorboard<3,>=2.3.0->tensorflow) (3.2.2)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/lib/python3/dist-packages (from tensorboard<3,>=2.3.0->tensorflow) (2.22.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in ./.local/lib/python3.8/site-packages (from tensorboard<3,>=2.3.0->tensorflow) (1.6.0.post3)
Requirement already satisfied: werkzeug>=0.11.15 in ./.local/lib/python3.8/site-packages (from tensorboard<3,>=2.3.0->tensorflow) (1.0.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in ./.local/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<3,>=2.3.0->tensorflow) (1.3.0)
Requirement already satisfied: rsa<4.1,>=3.1.4 in ./.local/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard<3,>=2.3.0->tensorflow) (4.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in ./.local/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard<3,>=2.3.0->tensorflow) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in ./.local/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard<3,>=2.3.0->tensorflow) (4.1.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<3,>=2.3.0->tensorflow) (3.1.0)
Requirement already satisfied: pyasn1>=0.1.3 in ./.local/lib/python3.8/site-packages (from rsa<4.1,>=3.1.4->google-auth<2,>=1.6.3->tensorboard<3,>=2.3.0->tensorflow) (0.4.8)
Installing collected packages: tensorflow
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

tensorflow-io 0.14.0 requires tensorflow<2.3.0,>=2.2.0, but you'll have tensorflow 2.3.0 which is incompatible

**Comment by yongtang** [comment]
@tkrsh For API compatible reasons, tensorflow-io 0.14.0 only works with `tensorflow<2.3.0,>=2.2.0`. We are, however, in the process of releasing a new version tensorflow-io 0.15.0 which works with `tensorflow<2.4.0,>=2.3.0`. (tracked in https://github.com/tensorflow/io/issues/1060). The new version 0.15.0 is planned to be released on Monday (barring any surprises). Once 0.15.0 is released you can update to have a compatible version and the issue should be resolved.

**Comment by yongtang** [comment]
@tkrsh The 0.15.0 release of tensorflow-io is available now: https://pypi.org/project/tensorflow-io/0.15.0/

I think the issue could be closed. Please feel free to re-open if the issue persists.

**Comment by Andjela010** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\PC\Desktop\kodak.py", line 3, in <module>
    from keras.datasets import imdb

  File "C:\ass\lib\site-packages\keras\__init__.py", line 5, in <module>
    raise ImportError(

ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`


I have this problem.


Python 3.8, windows 64 
In anaconda powersheel prompt I write 

pip install tensorflow==2.2
Requirement already satisfied: tensorflow==2.2 in c:\ass\envs\tf-gpu\lib\site-packages (2.2.0)
Requirement already satisfied: protobuf>=3.8.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow==2.2) (3.13.0)
Requirement already satisfied: h5py<2.11.0,>=2.10.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow==2.2) (2.10.0)
Requirement already satisfied: absl-py>=0.7.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow==2.2) (0.11.0)
Requirement already satisfied: tensorflow-estimator<2.3.0,>=2.2.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow==2.2) (2.2.0)
Requirement already satisfied: gast==0.3.3 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow==2.2) (0.3.3)
Requirement already satisfied: keras-preprocessing>=1.1.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow==2.2) (1.1.2)
Requirement already satisfied: six>=1.12.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow==2.2) (1.15.0)
Requirement already satisfied: wrapt>=1.11.1 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow==2.2) (1.12.1)
Requirement already satisfied: google-pasta>=0.1.8 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow==2.2) (0.2.0)
Requirement already satisfied: numpy<2.0,>=1.16.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow==2.2) (1.19.2)
Requirement already satisfied: scipy==1.4.1 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow==2.2) (1.4.1)
Requirement already satisfied: astunparse==1.6.3 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow==2.2) (1.6.3)
Requirement already satisfied: grpcio>=1.8.6 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow==2.2) (1.32.0)
Requirement already satisfied: wheel>=0.26 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow==2.2) (0.36.2)
Requirement already satisfied: termcolor>=1.1.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow==2.2) (1.1.0)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow==2.2) (3.3.0)
Requirement already satisfied: tensorboard<2.3.0,>=2.2.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow==2.2) (2.2.2)
Requirement already satisfied: setuptools in c:\ass\envs\tf-gpu\lib\site-packages (from protobuf>=3.8.0->tensorflow==2.2) (51.0.0.post20201207)
Requirement already satisfied: werkzeug>=0.11.15 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow==2.2) (1.0.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow==2.2) (2.25.1)
Requirement already satisfied: google-auth<2,>=1.6.3 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow==2.2) (1.24.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow==2.2) (1.6.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow==2.2) (0.4.2)
Requirement already satisfied: markdown>=2.6.8 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow==2.2) (3.3.3)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\ass\envs\tf-gpu\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2) (4.6)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\ass\envs\tf-gpu\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in c:\ass\envs\tf-gpu\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2) (4.2.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\ass\envs\tf-gpu\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\ass\envs\tf-gpu\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2) (0.4.8)
Requirement already satisfied: idna<3,>=2.5 in c:\ass\envs\tf-gpu\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\ass\envs\tf-gpu\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\ass\envs\tf-gpu\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2) (3.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\ass\envs\tf-gpu\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2) (1.26.2)
Requirement already satisfied: oauthlib>=3.0.0 in c:\ass\envs\tf-gpu\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.3.0,>=2.2.0->tensorflow==2.2) (3.1.0)
(tf-gpu) PS C:\Users\PC> pip install tensorflow-gpu==2.2
Requirement already satisfied: tensorflow-gpu==2.2 in c:\ass\envs\tf-gpu\lib\site-packages (2.2.0)
Requirement already satisfied: keras-preprocessing>=1.1.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow-gpu==2.2) (1.1.2)
Requirement already satisfied: grpcio>=1.8.6 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow-gpu==2.2) (1.32.0)
Requirement already satisfied: numpy<2.0,>=1.16.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow-gpu==2.2) (1.19.2)
Requirement already satisfied: absl-py>=0.7.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow-gpu==2.2) (0.11.0)
Requirement already satisfied: protobuf>=3.8.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow-gpu==2.2) (3.13.0)
Requirement already satisfied: wrapt>=1.11.1 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow-gpu==2.2) (1.12.1)
Requirement already satisfied: wheel>=0.26 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow-gpu==2.2) (0.36.2)
Requirement already satisfied: astunparse==1.6.3 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow-gpu==2.2) (1.6.3)
Requirement already satisfied: termcolor>=1.1.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow-gpu==2.2) (1.1.0)
Requirement already satisfied: gast==0.3.3 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow-gpu==2.2) (0.3.3)
Requirement already satisfied: scipy==1.4.1 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow-gpu==2.2) (1.4.1)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow-gpu==2.2) (3.3.0)
Requirement already satisfied: tensorboard<2.3.0,>=2.2.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow-gpu==2.2) (2.2.2)
Requirement already satisfied: six>=1.12.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow-gpu==2.2) (1.15.0)
Requirement already satisfied: h5py<2.11.0,>=2.10.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow-gpu==2.2) (2.10.0)
Requirement already satisfied: google-pasta>=0.1.8 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow-gpu==2.2) (0.2.0)
Requirement already satisfied: tensorflow-gpu-estimator<2.3.0,>=2.2.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorflow-gpu==2.2) (2.2.0)
Requirement already satisfied: setuptools in c:\ass\envs\tf-gpu\lib\site-packages (from protobuf>=3.8.0->tensorflow-gpu==2.2) (51.0.0.post20201207)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2) (0.4.2)
Requirement already satisfied: werkzeug>=0.11.15 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2) (1.0.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2) (2.25.1)
Requirement already satisfied: google-auth<2,>=1.6.3 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2) (1.24.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2) (1.6.0)
Requirement already satisfied: markdown>=2.6.8 in c:\ass\envs\tf-gpu\lib\site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2) (3.3.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\ass\envs\tf-gpu\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in c:\ass\envs\tf-gpu\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2) (4.2.0)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\ass\envs\tf-gpu\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2) (4.6)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\ass\envs\tf-gpu\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\ass\envs\tf-gpu\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2) (0.4.8)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\ass\envs\tf-gpu\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in c:\ass\envs\tf-gpu\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\ass\envs\tf-gpu\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\ass\envs\tf-gpu\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2) (1.26.2)
Requirement already satisfied: oauthlib>=3.0.0 in c:\ass\envs\tf-gpu\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.3.0,>=2.2.0->tensorflow-gpu==2.2) (3.1.0)


But again problem ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

**Comment by amahendrakar** [comment]
@Angelafe123,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
