### ISSUE TITLE
not sure but should it not be "ZerosLike" rather than "OnesLike" over here?

### ISSUE THREAD

**Issue by smj007** [tensorflow/tensorflow#41956]
https://github.com/tensorflow/tensorflow/blob/05632ed9bad5bf9eee3edd57ade3d8250d580019/tensorflow/c/eager/gradients.cc#L104

**Comment by ravikyram** [comment]
@smj007 

This is duplicate of #41912. Can we track with that issue and close this one. It will help us to follow easily. Please let us know. Thanks!

**Comment by smj007** [comment]
@ravikyram 

Oh I did not see that! Thanks for pointing it out, I shall close this issue!
