### ISSUE TITLE
use tf.image.ssim to calculate ssim is differen from paper(matlab?)

### ISSUE THREAD

**Issue by Stealers** [tensorflow/tensorflow#41951]
I use the following code to calculate the ssim of set5 dataset, but the results is differen from paper. When use 'Bicubic' method and set scale to 4, papers are usually PSNR(28.42)/ SSIM(0.810) .
```python
import tensorflow as tf
ssims = 0
psnrs = 0

for i in range(5):
    path1 = 'Set5\\Set5\\image_SRF_4\\img_00'+str(i+1)+'_SRF_4_bicubic.png'#bicubic
    path2 = 'Set5\\Set5\\image_SRF_4\\img_00'+str(i+1)+'_SRF_4_HR.png'
    img1 = tf.io.read_file(path1)
    img1 = tf.io.decode_image(img1,3,expand_animations=False)

    img2 = tf.io.read_file(path2)
    img2 = tf.io.decode_image(img2,3,expand_animations=False)

    ssims = ssims + tf.image.ssim(img1, img2, max_val=255)
    psnrs = psnrs + tf.image.psnr(img1, img2, max_val=255)
    
ssims/5,psnrs/5
```
```
(<tf.Tensor: shape=(), dtype=float32, numpy=0.7731458>,
 <tf.Tensor: shape=(), dtype=float32, numpy=26.69437>)
```
**Why is there a big gap between my results and the paper? Is my calculation wrong?**

**Comment by amahendrakar** [comment]
@Stealers,
Could you please provide the link to the paper you are comparing the results with?

Also, share the sample images you are using along with the TensorFlow version. Thanks!

**Comment by Stealers** [comment]
@amahendrakar I made a mistake. The paper is testing y channel not RGB.
