### ISSUE TITLE
cross compilation for tflite delegate testing tools

### ISSUE THREAD

**Issue by junhyk** [tensorflow/tensorflow#41960]
Hi,

I'm implementing my custom delegates for tflite to use RiscV-based accelerators.
While following the guides in **https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/utils/dummy_delegate**
I found that kernel tests are not convenient for cross-compilation.

Is there a recommended way to test my delegate functions for other architectures?

Thanks!

**Comment by srjoglekar246** [comment]
CCing @multiverse-tf who recently worked on this.

**Comment by multiverse-tf** [comment]
Hi Junhyeok,

How do you cross-compile the TFLite main library and TFLite tests at the moment? Could you elaborate on the inconvenience?

**Comment by zzoon91** [comment]
Thanks for reply!

I was doing cross-compilation by modifying the scripts given in `tensorflow/lite/tool/make`, which does not compile test codes in `tensorflow/lite/kernels`
If I can plug riscv toolchains in Bazel, it would definitely help. :)

I'm following the commit you suggested but I faced another error below.
How can I solve it?
```
$ bazel build --config=riscv64 //tensorflow/lite/kernels:fully_connected_test
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=187
INFO: Reading rc options for 'build' from /home/jhjang/ml-accelerator/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/jhjang/ml-accelerator/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Found applicable config definition build:short_logs in file /home/jhjang/ml-accelerator/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/jhjang/ml-accelerator/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:riscv64 in file /home/jhjang/ml-accelerator/tensorflow/.bazelrc: --crosstool_top=@local_config_riscv64//:toolchain --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=riscv64
INFO: Found applicable config definition build:linux in file /home/jhjang/ml-accelerator/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/jhjang/ml-accelerator/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
ERROR: /home/jhjang/.cache/bazel/_bazel_jhjang/8a72e618241ede75353c494f725f5447/external/XNNPACK/BUILD.bazel:3031:1: Configurable attribute "deps" doesn't match this configuration (would a default condition help?).
Conditions checked:
 @XNNPACK//:linux_k8
 @XNNPACK//:linux_arm
 @XNNPACK//:linux_armeabi
 @XNNPACK//:linux_armhf
 @XNNPACK//:linux_armv7a
 @XNNPACK//:linux_aarch64
 @XNNPACK//:macos_x86_64
 @XNNPACK//:windows_x86_64_clang
 @XNNPACK//:windows_x86_64_mingw
 @XNNPACK//:windows_x86_64_msys
 @XNNPACK//:windows_x86_64
 @XNNPACK//:android_armv7
 @XNNPACK//:android_arm64
 @XNNPACK//:android_x86
 @XNNPACK//:android_x86_64
 @XNNPACK//:ios_armv7
 @XNNPACK//:ios_arm64
 @XNNPACK//:ios_arm64e
 @XNNPACK//:ios_x86
 @XNNPACK//:ios_x86_64
 @XNNPACK//:watchos_armv7k
 @XNNPACK//:watchos_arm64_32
 @XNNPACK//:watchos_x86
 @XNNPACK//:watchos_x86_64
 @XNNPACK//:tvos_arm64
 @XNNPACK//:tvos_x86_64
 @XNNPACK//:emscripten_wasm
 @XNNPACK//:emscripten_wasmsimd
 @XNNPACK//:emscripten_asmjs
ERROR: Analysis of target '//tensorflow/lite/kernels:fully_connected_test' failed; build aborted:

/home/jhjang/.cache/bazel/_bazel_jhjang/8a72e618241ede75353c494f725f5447/external/XNNPACK/BUILD.bazel:3031:1: Configurable attribute "deps" doesn't match this configuration (would a default condition help?).
Conditions checked:
 @XNNPACK//:linux_k8
 @XNNPACK//:linux_arm
 @XNNPACK//:linux_armeabi
 @XNNPACK//:linux_armhf
 @XNNPACK//:linux_armv7a
 @XNNPACK//:linux_aarch64
 @XNNPACK//:macos_x86_64
 @XNNPACK//:windows_x86_64_clang
 @XNNPACK//:windows_x86_64_mingw
 @XNNPACK//:windows_x86_64_msys
 @XNNPACK//:windows_x86_64
 @XNNPACK//:android_armv7
 @XNNPACK//:android_arm64
 @XNNPACK//:android_x86
 @XNNPACK//:android_x86_64
 @XNNPACK//:ios_armv7
 @XNNPACK//:ios_arm64
 @XNNPACK//:ios_arm64e
 @XNNPACK//:ios_x86
 @XNNPACK//:ios_x86_64
 @XNNPACK//:watchos_armv7k
 @XNNPACK//:watchos_arm64_32
 @XNNPACK//:watchos_x86
 @XNNPACK//:watchos_x86_64
 @XNNPACK//:tvos_arm64
 @XNNPACK//:tvos_x86_64
 @XNNPACK//:emscripten_wasm
 @XNNPACK//:emscripten_wasmsimd
 @XNNPACK//:emscripten_asmjs
INFO: Elapsed time: 0.871s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (101 packages loaded, 2309 targets configured)
```

**Comment by multiverse-tf** [comment]
> Thanks for reply!
> 
> I was doing cross-compilation by adding `riscv64_makefile.inc` in `tensorflow/lite/tool/make/targets` and setting environment variable when invoking `make`. 

I see. As we primarily use Bazel, the support for Makefile is indeed generally behind Bazel BUILD rules.

I share my `riscv64_makefile.inc` below.
> 
> ```
> # Settings for RiscV platforms.
> ifeq ($(TARGET), riscv64)
>   TARGET_ARCH := riscv64
>   TARGET_TOOLCHAIN_PREFIX := riscv64-unknown-linux-gnu-
> 
>   CXXFLAGS += -march=rv64gc
> 	LIBS += -ldl -latomic
> endif
> ```
> 
> But I believe the Makefile does not provide a compilation for test codes in `tensorflow/lite/kernels`
> If I can plug riscv toolchains in Bazel, it would definitely help. :)
> 
> I'm following the commit you suggested but I faced another error below.
> How can I solve it?
> 
> ```
> $ bazel build --config=riscv64 //tensorflow/lite/kernels:fully_connected_test
It looks like it's because XNNPACK isn't configured to support this option as suggested by "external/XNNPACK/BUILD.bazel:3031:1: Configurable attribute "deps" doesn't match this configuration (would a default condition help?)." 

One way to bypass XNNPACK in this case, I think, is to comment out  the xnnpack delegate provider in //tensorflow/lite/kernels:test_util_delegate_providers BUILD rule.

> INFO: Options provided by the client:
>   Inherited 'common' options: --isatty=1 --terminal_columns=187
> INFO: Reading rc options for 'build' from /home/jhjang/ml-accelerator/tensorflow/.bazelrc:
>   Inherited 'common' options: --experimental_repo_remote_exec
> INFO: Reading rc options for 'build' from /home/jhjang/ml-accelerator/tensorflow/.bazelrc:
>   'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
> INFO: Found applicable config definition build:short_logs in file /home/jhjang/ml-accelerator/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
> INFO: Found applicable config definition build:v2 in file /home/jhjang/ml-accelerator/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
> INFO: Found applicable config definition build:riscv64 in file /home/jhjang/ml-accelerator/tensorflow/.bazelrc: --crosstool_top=@local_config_riscv64//:toolchain --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=riscv64
> INFO: Found applicable config definition build:linux in file /home/jhjang/ml-accelerator/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
> INFO: Found applicable config definition build:dynamic_kernels in file /home/jhjang/ml-accelerator/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
> ERROR: /home/jhjang/.cache/bazel/_bazel_jhjang/8a72e618241ede75353c494f725f5447/external/XNNPACK/BUILD.bazel:3031:1: Configurable attribute "deps" doesn't match this configuration (would a default condition help?).
> Conditions checked:
>  @XNNPACK//:linux_k8
>  @XNNPACK//:linux_arm
>  @XNNPACK//:linux_armeabi
>  @XNNPACK//:linux_armhf
>  @XNNPACK//:linux_armv7a
>  @XNNPACK//:linux_aarch64
>  @XNNPACK//:macos_x86_64
>  @XNNPACK//:windows_x86_64_clang
>  @XNNPACK//:windows_x86_64_mingw
>  @XNNPACK//:windows_x86_64_msys
>  @XNNPACK//:windows_x86_64
>  @XNNPACK//:android_armv7
>  @XNNPACK//:android_arm64
>  @XNNPACK//:android_x86
>  @XNNPACK//:android_x86_64
>  @XNNPACK//:ios_armv7
>  @XNNPACK//:ios_arm64
>  @XNNPACK//:ios_arm64e
>  @XNNPACK//:ios_x86
>  @XNNPACK//:ios_x86_64
>  @XNNPACK//:watchos_armv7k
>  @XNNPACK//:watchos_arm64_32
>  @XNNPACK//:watchos_x86
>  @XNNPACK//:watchos_x86_64
>  @XNNPACK//:tvos_arm64
>  @XNNPACK//:tvos_x86_64
>  @XNNPACK//:emscripten_wasm
>  @XNNPACK//:emscripten_wasmsimd
>  @XNNPACK//:emscripten_asmjs
> ERROR: Analysis of target '//tensorflow/lite/kernels:fully_connected_test' failed; build aborted:
> 
> /home/jhjang/.cache/bazel/_bazel_jhjang/8a72e618241ede75353c494f725f5447/external/XNNPACK/BUILD.bazel:3031:1: Configurable attribute "deps" doesn't match this configuration (would a default condition help?).
> Conditions checked:
>  @XNNPACK//:linux_k8
>  @XNNPACK//:linux_arm
>  @XNNPACK//:linux_armeabi
>  @XNNPACK//:linux_armhf
>  @XNNPACK//:linux_armv7a
>  @XNNPACK//:linux_aarch64
>  @XNNPACK//:macos_x86_64
>  @XNNPACK//:windows_x86_64_clang
>  @XNNPACK//:windows_x86_64_mingw
>  @XNNPACK//:windows_x86_64_msys
>  @XNNPACK//:windows_x86_64
>  @XNNPACK//:android_armv7
>  @XNNPACK//:android_arm64
>  @XNNPACK//:android_x86
>  @XNNPACK//:android_x86_64
>  @XNNPACK//:ios_armv7
>  @XNNPACK//:ios_arm64
>  @XNNPACK//:ios_arm64e
>  @XNNPACK//:ios_x86
>  @XNNPACK//:ios_x86_64
>  @XNNPACK//:watchos_armv7k
>  @XNNPACK//:watchos_arm64_32
>  @XNNPACK//:watchos_x86
>  @XNNPACK//:watchos_x86_64
>  @XNNPACK//:tvos_arm64
>  @XNNPACK//:tvos_x86_64
>  @XNNPACK//:emscripten_wasm
>  @XNNPACK//:emscripten_wasmsimd
>  @XNNPACK//:emscripten_asmjs
> INFO: Elapsed time: 0.871s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (101 packages loaded, 2309 targets configured)
> ```

**Comment by zzoon91** [comment]
It worked! Thanks
Though I also had to remove some other delegates as well, like hexagon.

But I found that bazel can only generate shared libraries, which is quite hard to deploy in my machine.
Is there a workaround to statically build the tests?

If not, what should I include to build some executables with my delegate?
libtensorflow-lite.a of course, and then?

**Comment by multiverse-tf** [comment]
> It worked! Thanks
> Though I also had to remove some other delegates as well, like hexagon.
Great to hear this! Might consider contribute your RISC-V toolchain configuration back to TF :-)?
> 
> But I found that bazel can only generate shared libraries, which is quite hard to deploy in my machine.
> Is there a workaround to statically build the tests using bazel?
Have you tried adding "linkstatic=True" to your rule? By default, I think bazel generates shared libraries.
> 
> If not, what should I include to build some executables with my delegate using cmake?
> libtensorflow-lite.a of course, and then?
We have plans to support CMake in TFLite in the near future.

**Comment by zzoon91** [comment]
> Great to hear this! Might consider contribute your RISC-V toolchain configuration back to TF :-)?
Sure, I'll make a pull request after some minor cleanups

>Have you tried adding "linkstatic=True" to your rule? By default, I think bazel generates shared libraries.
Could you be more specific about how to add linkstatic to a rule? To be honest, I'm not quite familiar with bazel, yet.
What I want to compile is `tensorflow/lite/kernels/fully_connected_test`

**Comment by zzoon91** [comment]
I figured it out by adding `-static` in `default_link_flags_feature` in my `cc_config.bzl.tpl` :)

**Comment by junhyk** [comment]
I share [my repository](https://github.com/junhyk/tensorflow) which contains how I figured out to build TFLite using RISC-V toolchains with bazel.
My solution is a bit hacky way since I commented out lots of line related to XNNPACK . I don't think I can directly contribute to TF. Hopefully, someone would find a better way.

**Comment by vaibhavjadhav377** [comment]
Hi all,
I am also trying to cross compile label_image for riscv. Following is a command used.
$bazel build --config=riscv //tensorflow/lite/examples/label_image:label_image

I too get the same error as previously occured:
bazel build --config=riscv //tensorflow/lite/examples/label_image:label_image
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=204
INFO: Reading rc options for 'build' from /home/vaibhavvj/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/vaibhavvj/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Found applicable config definition build:short_logs in file /home/vaibhavvj/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/vaibhavvj/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:riscv in file /home/vaibhavvj/tensorflow/.bazelrc: --crosstool_top=//toolchain:riscv64 --cpu=riscv --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
INFO: Found applicable config definition build:linux in file /home/vaibhavvj/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/vaibhavvj/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
ERROR: /home/vaibhavvj/.cache/bazel/_bazel_vaibhavvj/91ae5ce1d1ec4fdc8dfbac046528275c/external/XNNPACK/BUILD.bazel:3692:1: Configurable attribute "deps" doesn't match this configuration (would a default condition help?).
Conditions checked:
 @XNNPACK//:linux_k8
 @XNNPACK//:linux_arm
 @XNNPACK//:linux_armeabi
 @XNNPACK//:linux_armhf
 @XNNPACK//:linux_armv7a
 @XNNPACK//:linux_aarch64
 @XNNPACK//:macos_x86_64
 @XNNPACK//:windows_x86_64_clang
 @XNNPACK//:windows_x86_64_mingw
 @XNNPACK//:windows_x86_64_msys
 @XNNPACK//:windows_x86_64
 @XNNPACK//:android_armv7
 @XNNPACK//:android_arm64
 @XNNPACK//:android_x86
 @XNNPACK//:android_x86_64
 @XNNPACK//:ios_armv7
 @XNNPACK//:ios_arm64
 @XNNPACK//:ios_arm64e
 @XNNPACK//:ios_x86
 @XNNPACK//:ios_x86_64
 @XNNPACK//:watchos_armv7k
 @XNNPACK//:watchos_arm64_32
 @XNNPACK//:watchos_x86
 @XNNPACK//:watchos_x86_64
 @XNNPACK//:tvos_arm64
 @XNNPACK//:tvos_x86_64
 @XNNPACK//:emscripten_wasm
 @XNNPACK//:emscripten_wasmsimd
ERROR: Analysis of target '//tensorflow/lite/examples/label_image:label_image' failed; build aborted: 

/home/vaibhavvj/.cache/bazel/_bazel_vaibhavvj/91ae5ce1d1ec4fdc8dfbac046528275c/external/XNNPACK/BUILD.bazel:3692:1: Configurable attribute "deps" doesn't match this configuration (would a default condition help?).
Conditions checked:
 @XNNPACK//:linux_k8
 @XNNPACK//:linux_arm
 @XNNPACK//:linux_armeabi
 @XNNPACK//:linux_armhf
 @XNNPACK//:linux_armv7a
 @XNNPACK//:linux_aarch64
 @XNNPACK//:macos_x86_64
 @XNNPACK//:windows_x86_64_clang
 @XNNPACK//:windows_x86_64_mingw
 @XNNPACK//:windows_x86_64_msys
 @XNNPACK//:windows_x86_64
 @XNNPACK//:android_armv7
 @XNNPACK//:android_arm64
 @XNNPACK//:android_x86
 @XNNPACK//:android_x86_64
 @XNNPACK//:ios_armv7
 @XNNPACK//:ios_arm64
 @XNNPACK//:ios_arm64e
 @XNNPACK//:ios_x86
 @XNNPACK//:ios_x86_64
 @XNNPACK//:watchos_armv7k
 @XNNPACK//:watchos_arm64_32
 @XNNPACK//:watchos_x86
 @XNNPACK//:watchos_x86_64
 @XNNPACK//:tvos_arm64
 @XNNPACK//:tvos_x86_64
 @XNNPACK//:emscripten_wasm
 @XNNPACK//:emscripten_wasmsimd
INFO: Elapsed time: 6.659s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (56 packages loaded, 1600 targets configured)

So how can I reject xnnpack dependency, during label_image build.
