### ISSUE TITLE
UserWarning: Tensorflow optimizers do not mkae it possible to access optimizer attributes or optimizer state after instantiation.

### ISSUE THREAD

**Issue by kaen2891** [tensorflow/tensorflow#41967]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):  
- TensorFlow version: 2.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: Quadro GV100, 32GB

**Describe the problem**

Hello, I just make some model from keras, and got some problems like below:
```UserWarning: Tensorflow optimizers do not mkae it possible to access optimizer attributes or optimizer state after instantiation. As a result, we cannot save the optimizer as part of the model save file. You will have to compile your model again after loading it. Prefer using a Keras optimizer instead (see keras.io/optimizers)```

In my codes,
```
model = Sequential()
model.add(Conv2D(filters=16, kernel_size=(3, 3), strides=(1, 1), data_format="channels_last", activation='relu', input_shape=(x_train.shape[1], x_train.shape[2], x_train.shape[3])))
model.add(Flatten())
model.add(Dense(len(label), activation='softmax'))
model.summary()

initial_learning_rate = args.lr
    
lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
initial_learning_rate,
decay_steps=4000,
decay_rate=0.96,
staircase=True)

optimizer = tf.keras.optimizers.Adam(lr_schedule, beta_1=0.9, beta_2=0.98, epsilon=1e-9)

model.compile(loss=tf.keras.losses.KLDivergence(), optimizer=optimizer, metrics=['accuracy'])

model_path='./'
file_path = os.path.join(model_path, 'saved-model-{epoch:02d}-{val_loss:.2f}.hdf5') # 
checkpoint = ModelCheckpoint(file_path, monitor='val_loss', verbose=1, save_best_only=False, mode='max') # 
callback_list = [checkpoint]

hist = model.fit(train_datagen.flow(x_train, y_train, batch_size=args.batch_size), epochs=args.epochs, steps_per_epoch=train_steps, validation_data = (valid_datagen.flow(x_valid, y_valid, batch_size=args.batch_size)), callbacks = callback_list, shuffle=True)
```
As shown in my code, I used the optimizers from ```tf.keras.optimizers``` but I got some errors.

When I do evaluate, I got this warning message:
```UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually```

Here the summary of my ```eval.py``` code:
```
model = keras.models.load_model(model_dir)
model.summary()

y_pred = model.predict(x_test)
```

Is it possible to use that saved model directly? or how should I use this model? May I ignore that Warning message?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam

**Comment by Saduf2019** [comment]
@kaen2891 
The code shared is not sufficient to replicate the issue faced , please provide stand alone code[with all dependencies] such that we can replicate the issue faced or if possible share a colab gist with the error

meanwhile for your first error can you refer to [this link](https://datascience.stackexchange.com/questions/45893/tf-tells-me-to-use-keras-optimizer-tells-me-the-opposite-when-i-change-it) and make changes a s suggested.

for the warning please refer to [this link](https://stackoverflow.com/questions/53295570/userwarning-no-training-configuration-found-in-save-file-the-model-was-not-c). and let us know.
