### ISSUE TITLE
Pycharm:TensorFlow-Attribute error issue 

### ISSUE THREAD

**Issue by vigneshenoy-SDET** [tensorflow/tensorflow#41962]
Hi,

While trying to run the below code I encountered an Attribute error, description for which is given below.

Code

import tensorflow as tf

node1 = tf.constant (3.0,tf.float32)

node2 = tf.constant (4.0)

print(node1,node2)

Error Message encountered-AttributeError: module 'os' has no attribute 'add_dll_directory'

System Configurations are as mentioned below

OS-Windows 7
Python version-3.8.0
Pycharm version-Community 2019.1
Tensorflow-2.3.0

PFA the screenshots of Pycharm packages
![pycharm_packages_1](https://user-images.githubusercontent.com/64397079/89103662-09bba580-d431-11ea-86ec-29bbd93c066a.jpg)
![pycharm_packages_2](https://user-images.githubusercontent.com/64397079/89103664-0b856900-d431-11ea-8003-395027d06fef.jpg)

**Comment by amahendrakar** [comment]
@vigneshenoy-SDET,
Could you please check if you are running 64-bit Python and take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) to install TensorFlow.

Also, please run the command `pip list` and share the output with us. Thanks!
