### ISSUE TITLE
Looking for Post-training Quantization for int 16 in TF2/TF Lite

### ISSUE THREAD

**Issue by YiranCdr** [tensorflow/tensorflow#41968]
**System information**
- TensorFlow version (you are using): TF 2.2.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Dear TF developers, I'm looking for a 16-bits integer Post-training Quantization (PQ) solution. I noticed that we have 16-bit Quantization Aware Training (QAT) APIs for TF2 (which is great!), while for PQ, INT16 is not supported in TF Lite. 

Or do you know any framework that can achieve int16 PQ currently?

**Will this change the current api? How?**
Yes or No. For the tf.lite.TFLiteConverter.from_keras_mode, we need to import another parameter in order to indicate the quantization bits. Or we can create a new api to fit this method. 

**Who will benefit with this feature?**
Platforms that have a nice 16 bits calculation support. This will save more calculation 

**Any Other info.**

**Comment by MeghnaNatraj** [comment]
We currently have an [experimental integer quantization (16-bit activations with 8-bit weights)](https://www.tensorflow.org/lite/performance/post_training_quantization). Does this work for you? [Note: weights are still in int8]

**Comment by YiranCdr** [comment]
> We currently have an [experimental integer quantization (16-bit activations with 8-bit weights)](https://www.tensorflow.org/lite/performance/post_training_quantization). Does this work for you? [Note: weights are still in int8]

Hi Meghna, 
Thanks for the reply :) Actually no... since we're hoping to carry out 16bits (int) calculation as much as we can. Do you have any future plans for INT 16 post-training quantization?

**Comment by MeghnaNatraj** [comment]
@YiranCdr Probably not in the near future. Will let @suharshs answer that. :)

**Comment by YiranCdr** [comment]
> @YiranCdr Probably not in the near future. Will let @suharshs answer that. :)

Thanks!

**Comment by sachinprasadhs** [comment]
Post training quantization for INT16 is supported as 
`converter.target_spec.supported_ops = [tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8]`
Please refer the guide https://www.tensorflow.org/lite/performance/post_training_integer_quant_16x8 for detailed steps. Thanks!
