### ISSUE TITLE
Error when running two simultaneous sessions

### ISSUE THREAD

**Issue by JohnRobson** [tensorflow/tensorflow#4196]
Can I run two simultaneous sessions?

I start with: "with tf.Graph().as_default(), tf.Session() as sess:"

When I run my script alone, the result is OK, but when I run 2 instances the result is completely wrong or throw some errors like:

Error max() arg is an empty sequence
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:924] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: Quadro K2000M
major: 3 minor: 0 memoryClockRate (GHz) 0.745
pciBusID 0000:01:00.0
Total memory: 1.95GiB
Free memory: 1.47GiB

(and also)
float division by zero

Can I do something in my code do avoid these errors?

Maybe check if TF is already running and hold it?

Than you very much.

OS: Arch Linux

$ ls -l /opt/cuda/lib/libcud*
/opt/cuda/lib/libcudadevrt.a
/opt/cuda/lib/libcudart.so.7.5.18
/opt/cuda/lib/libcudart_static.a
/opt/cuda/lib/libcudnn.so -> /opt/cuda/lib64/libcudnn.so.4.0.7

PIP: 0.9.0

**Comment by tatatodd** [comment]
If I'm understanding you correctly, you are running two instances of the same python program, each in its own process.  I believe that should work.

One simple suggestion is to try with the latest release version 0.10.0.

Otherwise, can you try to boil your problem down to a minimal program that exhibits the failure?  That will either narrow in on the problem, or allow me to reproduce.  Thanks!

**Comment by vrv** [comment]
Actually you probably don't want to be using the same GPU simultaneously from two TensorFlow processes.  It's somewhat safe to pause one while the other uses the GPU, but if they are both actively using the GPU, bad things are likely to happen, I believe.

**Comment by kracwarlock** [comment]
I have tried using the same GPU from two TF processes simultaneously. Sometimes both run; sometimes one crashes with messages like these:
```
E tensorflow/stream_executor/cuda/cuda_blas.cc:367] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
W tensorflow/stream_executor/stream.cc:1334] attempting to perform BLAS operation using StreamExecutor without BLAS support
E tensorflow/stream_executor/cuda/cuda_blas.cc:367] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
W tensorflow/stream_executor/stream.cc:1334] attempting to perform BLAS operation using StreamExecutor without BLAS support
E tensorflow/stream_executor/cuda/cuda_blas.cc:367] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
W tensorflow/stream_executor/stream.cc:1334] attempting to perform BLAS operation using StreamExecutor without BLAS support
E tensorflow/core/client/tensor_c_api.cc:485] Blas SGEMM launch failed : a.shape=(128, 100), b.shape=(100, 16), m=128, n=16, k=100
```
Why is that?

**Comment by ArturoDeza** [comment]
Agree with the post above (and had the same errors complaining about not finding CUBLAS). I had to close my other tensorflow terminals to re-run a new tensorflow program that is calling a single GPU.

**Comment by smhoang** [comment]
I got the same issue when running 2 Tensorflow/Keras at the same time, each in its process. The error is: "failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED". Any suggestion ? Thanks a lot.

**Comment by jpowie01** [comment]
I've also encountered this problem today. Any tips?

**Comment by yaroslavvb** [comment]
`CUBLAS_STATUS_NOT_INITIALIZED` can be thrown when you are out of memory, which can happen when you run two GPU TensorFlow processes in parallel. TensorFlow doesn't like sharing GPU memory with another process, the solution is to run only a single TensorFlow process per GPU (using `CUDA_VISIBLE_DEVICES=k` to restrict k'th process to k'th GPU)

**Comment by DanielTakeshi** [comment]
Just to be clear, this means that if I have only one GPU on my machine, I should only have one Tensorflow session (or code) active? No other easy way around it?

**Comment by yaroslavvb** [comment]
You should have at most one active TensorFlow process per GPU. Use CUDA_VISIBLE_DEVICES to determine which process gets which GPU (CUDA_VISIBLE_DEVICES='' will disable GPU)

**Comment by xolott** [comment]
I'm trying to run 2 models in 2 different process (multiprocess in python). Each process create a session. One load a MTCNN model and the other one load a CNN. 1/20 times, both work fine. 
If I run one or another process alone, work just fine. I set <50% of GPU memory on each process
My error is:
InternalError: Failed to create session.

Or:
F tensorflow/core/kernels/conv_ops.cc:605] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms) 

Always the same process fail...

**Comment by sagardatascientists** [comment]
Its better to use Theano if you want to run two process on same GPU.

**Comment by ayyappa428** [comment]
how to create multiple instances using theano. If i change OMP_NUM_THREADS = 2 two cores will be enabled.But i want to create more instances like multi processing instead of having multiple workers.I want to send the multiple requests using theano is it possible?

**Comment by zwfcrazy** [comment]
By using  `gpu_options.per_process_gpu_memory_fraction` or `gpu_options.allow_growth` to limit memory pre-allocation of each tf process, I was able to run multiple tf processes on the same GPU simultaneously. (of course, your model needs to be small enough in order to do so)
But I am not sure if there will be any other problems.
I also don't know how this will affect the computing speed of each process.

**Comment by xolott** [comment]
As far as I know, TF can't have more than one session per GPU. It will have problem accessing gpu memory and using the Cuda cores. If you want multiple models go to TensorflowServing

**Comment by MrWanter** [comment]
same problem for multiple process run on same GPU, I have some machine with titanx , others with p40, with `gpu_options.per_process_gpu_memory_fraction` and `gpu_options.allow_growth`, I can run on titanx machine, but always get `CUBLAS_STATUS_NOT_INITIALIZED` on p40 machines

**Comment by loretoparisi** [comment]
@tatatodd I think this issue should not be closed, but tagged as Question.

**Comment by jotes35** [comment]
I have a similar problem. I use an HPC server with 6 different compute nodes I run tensorflow simultaneously on two different nodes . I still got an error on one of them. Is that not strange?
