### ISSUE TITLE
Tensor into numpy

### ISSUE THREAD

**Issue by surGeonGG** [tensorflow/tensorflow#41965]
How do I turn a tensor such as `Tensor("lstm_42/Identity:0", shape=(1, 100, 13), dtype=float32)` into a numpy array in keras? Tried .numpy() and .eval() but nothing seems to work.

**Comment by FalsoMoralista** [comment]
What's the current tensorflow version you're using? besides that, have you read the template before publlishing? 

```For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow). ```

**Comment by surGeonGG** [comment]
I thought I read it, but somehow I missed that.

My bad, I'll close the issue.
