### ISSUE TITLE
Incorrect documentation for dynamic_rnn

### ISSUE THREAD

**Issue by vladfi1** [tensorflow/tensorflow#4197]
The help for `tf.nn.dynamic_rnn` states that the optional `initial_state` kwarg, if `cell.state_size` is an integer, must be a `Tensor` of appropriate type and shape `[batch_size x cell.state_size]`. This is incorrect; the shape must be actually be `[batch_size, cell.state_size]`.

**Comment by tatatodd** [comment]
Thanks for the report!  I'll update this issue once the fixed documentation has been merged in.

**Comment by tatatodd** [comment]
OK the docs have been updated, thanks @vladfi1 for filing the issue!
