### ISSUE TITLE
Hi, I am trying to load a saved model using load_model('path') but i am getting the following error :

### ISSUE THREAD

**Issue by rishabhs-s** [tensorflow/tensorflow#41974]
File "F:\anaconda\envs\facerecog\lib\site-packages\tensorflow\python\keras\saving\save.py", line 189, in load_model
    loader_impl.parse_saved_model(filepath)
  File "F:\anaconda\envs\facerecog\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 113, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: ferlatest.h5/{saved_model.pbtxt|saved_model.pb}

**Comment by ravikyram** [comment]
@rishabhs-s 

Can you please, fill [issue template.](https://github.com/tensorflow/tensorflow/issues/new/choose).
Request you to share colab link or simple standalone code to reproduce the issue in our environment.

You can refer the [tutorial](https://www.tensorflow.org/tutorials/keras/save_and_load) which will help you in loading the saved model.Thanks!

**Comment by rishabhs-s** [comment]
https://github.com/rishabhs-s/Face-Recog-update
In this web app when I run I get the error.
Please see

**Comment by ravikyram** [comment]
@rishabhs-s 

Can you try by loading with the below command and see if you are able to load model or not.
`model= tf.keras.models.load_model('ferlatest.h5')`
Please, refer this [documentation](https://www.tensorflow.org/tutorials/keras/save_and_load).Thanks!
