### ISSUE TITLE
Error in nce_loss using intermediate layer output

### ISSUE THREAD

**Issue by chchannn** [tensorflow/tensorflow#41971]
**Standalone code to reproduce the issue**
[colab notebook](https://colab.research.google.com/drive/1JTQzXF_Gu4WHzwCg_EWbjAU2gc-8VAOx?usp=sharing)

**System information**
tensorflow version on my machine v2.2.0-rc4-8-g2b96f3662b 2.2.

I am trying to use the nce_loss by passing the second to last layer's ouput to this loss function, then I got error

>OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2 and was able to reproduce the issue.However with TF nightly version i am seeing the different errror message.
(`TypeError: Keras symbolic inputs/outputs do not implement `__len__`. You may be trying to pass Keras symbolic inputs/outputs to a TF API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the Functional Model. This error will also get raised if you try asserting a symbolic input/output directly.`).
Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/2e33f9829e2eca5558d1b5a798c63e9e/untitled76.ipynb).Thanks!

**Comment by jvishnuvardhan** [comment]
@chchannn `model.inputs` and `model.layer.output` are symbolic Tensors that cannot be used in losses, metrics, etc. Please check [here](https://github.com/tensorflow/tensorflow/issues/39702#issuecomment-631750377) more details about the root-cause. Thanks!

For further support questions, please post them in stackoverflow as there is a big community to support this kind of support questions. Either community or us will answer those support questions. GitHub is mainly for Bug and performance related issues. Thanks!

**Comment by chchannn** [comment]
I see. I did post on stackoverflow first but the [question](https://stackoverflow.com/questions/63201831/negative-sampling-for-classification-task-with-tensorflow-nce) is never answered.
