### ISSUE TITLE
Memory Leak with latest Tensorflow

### ISSUE THREAD

**Issue by fabianvdW** [tensorflow/tensorflow#41973]
**System information**
- Have I written custom code: Yes, but minimal
- OS Platform and Distribution: Windows 10
- TensorFlow installed from: conda
- TensorFlow version: `2.3.0`
- Python version: 3.7.4

**Current behavior**
Memory leaks.
**Expected behavior**
Memory does not leak.
**Code to reproduce the issue**
```Python
import numpy as np
import tensorflow
from tensorflow import keras
from tensorflow.keras import layers
import gc
import tracemalloc    
if __name__ == "__main__":
    tracemalloc.start()
    while True:
        inputs = keras.Input(shape=(10,))
        out = layers.Dense(1)(inputs)
        model = keras.Model(inputs=inputs, outputs=out)
        model.compile(optimizer="adam", loss="mse")
        train = np.random.rand(1000,10)
        label = np.random.rand(1000)
        model.fit(train, label)
        gc.collect()
        current, peak = tracemalloc.get_traced_memory()
        print(f"Current memory usage is {current / 10**6}MB; Peak was {peak / 10**6}MB")
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/1e765ba9a8323af3d0ecfbdcf81a7243/41973.ipynb). Thanks!

**Comment by tomerk** [comment]
Hi @fabianvdW, in TF 2.3 and earlier Keras puts all model construction in the same global background graph workspace, which leads to a memory leak unless you explicitly call keras.backend.clear_session.

A few days ago though we enabled a refactoring of the Functional API implementation internals in the nightlies which gets rid of this background global graph, so you should no longer see this memory leak. (In the nightlies at least). Please do re-open this issue if you're still seeing one in the nightlies though or if you spot memory leaks elsewhere!

Best,
Tomer

**Comment by ems7** [comment]
This issue still exists in the nightlies. It affects` model.fit() `and `model.predict()`. I have also tried passing a generator to `model.fit()` but the leak persists.
I have tried several versions of tensorflow, built from sources with different versions of cuda and cudnn - the problem exists in all versions I tested.
Tensorflow  2.3.0/2.4.0/nightly
Cuda 10.1/10.2
Cudnn 7.6/8.0
nvidia driver 440.33

I am using psutil to check memory consumption - `pip install psutil`

Code to reproduce:

```
import tensorflow as tf
import psutil
import numpy as np
print(tf.__version__)


def generateInps():
    for i in range(200000):
        states = [ [ 1 ] * rows * columns for i in range(2000) ]
        y = np.zeros([2000,512])
        states = tf.one_hot(states, dtype='float32', depth=3)
        print('iteration', i, "memory usage %s" %psutil.virtual_memory().percent)
        yield states, y
 
use_generator = True 
fit = True
    
rows = 6
columns = 7

model = tf.keras.Sequential([
  tf.keras.layers.Flatten(input_shape=[rows * columns, 3]),
  tf.keras.layers.Dense(512, input_shape=[rows * columns * 3]),
])

model.compile(
  optimizer=tf.keras.optimizers.SGD(lr=0.01),
  loss='mean_squared_error',
  metrics=['accuracy']
)


if fit:
    if use_generator:
        model.fit(generateInps(), verbose=0)
    else:
        states = [ [ 1 ] * rows * columns for i in range(2000) ]
        y = np.zeros([2000,512])
        states = tf.one_hot(states, dtype='float32', depth=3)
        for iteration in range(1000000):
            print('iteration', iteration, "memory usage %s" %psutil.virtual_memory().percent)
            model.fit(states, y, verbose=0)
            tf.keras.backend.clear_session()
else:
    states = [ [ 1 ] * rows * columns for i in range(2000) ]
    y = np.zeros([2000,512])
    states = tf.one_hot(states, dtype='float32', depth=3)        
    for iteration in range(1000000):
        print('iteration', iteration, "memory usage %s" %psutil.virtual_memory().percent)
        model.predict(states)        

```

Explicitly calling `tf.keras.backend.clear_session()` does not work and is therefore not a work around.

My current work around is to save a model after each batch of training and keep track of where in the training data I am and continue from there, this isn't ideal, but until this bug is fixed, I don't see a better option.

**Comment by amahendrakar** [comment]
@ems7,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
