### ISSUE TITLE
Typo on the order number for title on guide "Automatic Differentiation"

### ISSUE THREAD

**Issue by zsk843** [tensorflow/tensorflow#41986]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://tensorflow.google.cn/guide/autodiff

## Description of issue (what needs changing):

When listing the reason of the "None" gradient (Chapter of "Getting a gradient of None"), the text  "**3. Took gradients through an integer or string**" is followed by order number "5", which is "**5. Took gradients through a stateful object**". Suggest to correct it to  "**4. Took gradients through a stateful object**"

**Comment by jvishnuvardhan** [comment]
@zsk843 Thanks for reporting the typo. We updated the doc. It is already reflecting in the TF website.

Please verify once and close the issue if this was resolved. Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing this issue as this was already resolved and TF website reflects the correction. Thanks!
