### ISSUE TITLE
Posenet when change to front facing camera displays the camera preview upside down. 

### ISSUE THREAD

**Issue by mohitgithubprojects** [tensorflow/tensorflow#41985]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Microsoft Windows 10 64-bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: all

**Describe the current behavior**

As in the current behaviour the app displays the camera preview with upside down orientation from the front facing camera.
( According to the example code provided for posenet sample app. )

**Describe the expected behavior**

It should displays the camera preview as perfect and well oriented as it shows from the back facing camera.

Please help as i have working on something important.

**Comment by amahendrakar** [comment]
@mohitgithubprojects,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by mohitgithubprojects** [comment]
@amahendrakar , Thank you for responsing,

**[Actually i'm just using the example code provided by tflite of posenet in android.]**
[](https://github.com/tensorflow/examples/tree/master/lite/examples/posenet/android)

The example code displays the results using the back camera of the device but as i have mentioned i want the results using the front camera of the android device . So, i have updated the code in this class :- 
[](https://github.com/tensorflow/examples/blob/master/lite/examples/posenet/android/app/src/main/java/org/tensorflow/lite/examples/posenet/PosenetActivity.kt#L283)

 to do so in the line no. " 283 ".

**example code:-**   cameraDirection == CameraCharacteristics.LENS_FACING_FRONT

**My updated code :-** cameraDirection == CameraCharacteristics.LENS_FACING_BACK

**Results by the example code when using with the Back camera :-**  

As you can see the orientation of the preview is perfect.

![Screenshot_20200803-202041 1](https://user-images.githubusercontent.com/60915290/89196081-5802ad00-d5c7-11ea-883d-fcbf3fe07109.png)

**Results by the example code when using with the Front camera :-**
As you can see the orientation of the preview is Upside down. ( just by changing that one line (283) to front camera )

![Screenshot_20200803-201945 1](https://user-images.githubusercontent.com/60915290/89196346-b760bd00-d5c7-11ea-9ac5-3554a9bc2c4e.png)

**Comment by ymodak** [comment]
@mohitgithubprojects Thanks for your issue. 
The code needs to be tweaked for implementing front camera as you tried.
Perhaps you may try referring this [thread](https://stackoverflow.com/questions/37103571/android-front-camera-images-are-being-saved-upside-down) for custom code implementing the front camera.
Currently this is [not supported](https://github.com/tensorflow/examples/blob/4fd91657a3242dca66165e68e377b2b891846c08/lite/examples/posenet/android/app/src/main/java/org/tensorflow/lite/examples/posenet/PosenetActivity.kt#L280) by the example out of the box.
