### ISSUE TITLE
NotFoundError:  No algorithm worked! .... convolutional model

### ISSUE THREAD

**Issue by summa-code** [tensorflow/tensorflow#41987]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 20.04
- TensorFlow installed from (source or binary): Latest as of today
- TensorFlow version (use command below): 2.4.0
- Python version: 3.8.0
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0
- GPU model and memory: RTX 2070

The sample code to debug this issue is at,
https://www.tensorflow.org/tutorials/structured_data/time_series

NotFoundError:  No algorithm worked!
	 [[node sequential_3/conv1d/conv1d (defined at <ipython-input-42-716049f06cb3>:12) ]] [Op:__inference_train_function_127130]

Function call stack:
train_function

**Comment by Saduf2019** [comment]
@summa-code 
Please provide simple stand alone code for us to replicate the issue faced or if possible share colab gist with the error faced.

**Comment by summa-code** [comment]
@Saduf2019 , the link is provided with the bug. Please look above link.

**Comment by summa-code** [comment]
It is the sample code that is on Tensorflow.org. Do you need any other information ?

**Comment by summa-code** [comment]
Closed by mistake.

**Comment by Saduf2019** [comment]
@summa-code 
Can you please provide a colab gist with the error faced for us to analyse.

**Comment by summa-code** [comment]
Wow... i really don't have colab, here is the link again, can you not use this ?
I do it locally. This code is a sample code from Tensorflow.org and it is not working with the latest build i do locally. 

The sample code to debug this issue is at,
https://www.tensorflow.org/tutorials/structured_data/time_series

**Comment by mihaimaruseac** [comment]
@summa-code can you please check formatting in the above message? Please use ` ``` ` before and after code blocks and errors

**Comment by summa-code** [comment]
Looks like this is not happening in Colab, not sure what changed. But I still have the original error... some people are reporting that this is CUDNN initialization issue. And the shortcut seems to disable GPU completely, and only runs on CPU.
=========================================
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession
config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)
=========================================

And this solution did not help either, TF_CUDNN_RESET_RND_GEN_STATE=1

So i wonder, how would we go about convolution network if GPU support is not available.

**Comment by summa-code** [comment]
I am giving up on these because i have many core CPU, i have a problem to work on.
