### ISSUE TITLE
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed. Failed to load the native TensorFlow runtime. 

### ISSUE THREAD

**Issue by shoother813** [tensorflow/tensorflow#41991]
I'm receiving this error message when importing keras: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow'

When I downgrade to keras 2.3.1, I receive the following error "ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed."  

Stackoverflow link: https://stackoverflow.com/questions/63209972/error-while-loading-keras-2-4-3-for-tensorflow-2-2?noredirect=1#comment111793997_63209972

###update as of 8/2/2020###
I've narrowed the problem down to the c:\windows\system32\msvcp140_1.dll file.  The file is not read-only and everyone has full permissions on the file.  I've tried condas install and reinstalling C++ redistrib packages and still receive the same error message that the DLL can't initialize. 

import struct
print("Python version: " + str(8 * struct.calcsize("P")))  # outputs 64
print("loading keras.layers...")
from keras.layers import Input, LSTM, Dense
print("loading keras.models...")
from keras.models import Model
print("loading nltk.corpus...")
from nltk.corpus import stopwords
------------------------

### System information

Windows Server 2012 R12 x64 (VM)
python 3.8.3 x64
Keras 3.4.1 or 3.2.1
tensorflow 2.2
C++ redistribution
No GPU

##### Error Message When Laucnhing the above Test Script ####

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", lin
e 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dyna
mic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python\lib\site-packages\tensorflow\__init__.py", line 41, in <module
>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Python\lib\site-packages\tensorflow\python\__init__.py", line 40, in
<module>
    from tensorflow.python.eager import context
  File "C:\Python\lib\site-packages\tensorflow\python\eager\context.py", line 35
, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Python\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, i
n <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", lin
e 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", lin
e 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dyna
mic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by amahendrakar** [comment]
@shoother813,
Could you please share the output of the `pip list` command with us?

Also, check this these similar issues [#22512](https://github.com/tensorflow/tensorflow/issues/22512), [#36167](https://github.com/tensorflow/tensorflow/issues/36167) and let us know if it works. Thanks!

**Comment by shoother813** [comment]
Package                Version
---------------------- ---------
absl-py                0.9.0
appdirs                1.4.4
asgiref                3.2.10
astor                  0.8.1
astroid                2.4.2
astunparse             1.6.3
attrs                  19.3.0
bcrypt                 3.1.7
beautifulsoup4         4.8.2
bs4                    0.0.1
cached-property        1.5.1
cachetools             4.1.1
certifi                2020.6.20
cffi                   1.14.1
chardet                3.0.4
click                  7.1.2
colorama               0.4.3
cryptography           3.0
cx-Oracle              7.3.0
cycler                 0.10.0
defusedxml             0.6.0
Django                 3.0.8
et-xmlfile             1.0.1
gast                   0.3.3
google-auth            1.20.0
google-auth-oauthlib   0.4.1
google-pasta           0.2.0
grpcio                 1.30.0
h5py                   2.10.0
idna                   2.10
importlib-metadata     1.7.0
isodate                0.6.0
jdcal                  1.4.1
joblib                 0.16.0
Keras                  2.4.3
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.2
lazy-object-proxy      1.4.3
lxml                   4.5.2
Markdown               3.2.2
nltk                   3.5
numpy                  1.18.5
oauthlib               3.1.0
openpyxl               3.0.4
opt-einsum             3.3.0
pandas                 1.1.0
paramiko               2.7.1
pip                    20.2
protobuf               3.12.4
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycparser              2.20
PyNaCl                 1.4.0
pyodbc                 4.0.30
python-dateutil        2.8.1
pytz                   2020.1
PyYAML                 5.3.1
regex                  2019.11.1
requests               2.24.0
requests-oauthlib      1.3.0
requests-toolbelt      0.9.1
rsa                    4.6
scikit-learn           0.23.1
scipy                  1.4.1
setuptools             47.1.0
six                    1.15.0
sklearn                0.0
soupsieve              2.0.1
sql-server.pyodbc      1.0
sqlparse               0.3.1
tensorboard            2.3.0
tensorboard-plugin-wit 1.7.0
tensorflow             2.3.0
tensorflow-estimator   2.3.0
termcolor              1.1.0
threadpoolctl          2.1.0
tqdm                   4.48.0
urllib3                1.25.10
Werkzeug               1.0.1
wheel                  0.34.2
wrapt                  1.12.1
XlsxWriter             1.3.0
zeep                   3.4.0
zipp                   3.1.0

**Comment by shoother813** [comment]
I've also tried downgrading to python 3.7 and installed tensorflow 2.0, but still received the exact same problem.  I'm currently back to python 3.8 and tensorflow 2.3

**Comment by amahendrakar** [comment]
@shoother813,
Please create a virtual environment and then try installing TensorFlow in it, and check if it works. Thanks!
