### ISSUE TITLE
Tensorflow Build Failure with Bazel

### ISSUE THREAD

**Issue by Bmoser-boop** [tensorflow/tensorflow#41996]
**Apologies in advance for the text dump**

I am attempting to compile Tensorflow in OSX 10.13.4 using Bazel based on these instructions:
https://medium.com/xplore-ai/nvidia-egpu-macos-tensorflow-gpu-the-definitive-setup-guide-to-avoid-headaches-f40e831f26ea

I attempted the build using the following command: 
`bazel build --config=cuda --config=opt --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --action_env PATH --action_env LD_LIBRARY_PATH --action_env DYLD_LIBRARY_PATH //tensorflow/tools/pip_package:build_pip_package`

Here are the versions of all relevant programs:
Python: 3.6
CUDA: 10.0
cuDNN: 7.4
Tensorflow: https://github.com/zylo117/tensorflow-gpu-macosx
GPU: NVIDIA GTX 980
Bazel Version: 0.16.1

Here is the verbose error information along with some run info:

5 warnings generated.

```
ERROR: /Users/brianmoser/tensorflow-gpu-macosx/tensorflow/core/kernels/BUILD:3423:1: error while parsing .d file: /private/var/tmp/_bazel_brianmoser/9608e82147ff56f68b42fd19bee93cb0/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/core/kernels/_objs/bincount_op_gpu/bincount_op_gpu.cu.d (No such file or directory)

nvcc fatal : The version ('10.0') of the host compiler ('Apple clang') is not supported

Target //tensorflow/tools/pip_package:build_pip_package failed to build

Use --verbose_failures to see the command lines of failed build steps.

INFO: Elapsed time: 1407.017s, Critical Path: 63.10s

INFO: 2389 processes: 2389 local.

FAILED: Build did NOT complete successfully
```

Additionally, here is the final step the build conducted:

`tensorflow/stream_executor/cuda/cuda_dnn.cc:1506:19: warning: private field 'data_type_' is not used [-Wunused-private-field]
  cudnnDataType_t data_type_;
`

Finally, here is the final relevant information:

```
git rev-parse HEAD

795d7c36152a1f96adca0c48f4537e500f5ad36b
```
```

bazel version

Build label: 0.16.1

```
Build target: 
`bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar`

Does anybody have any idea what could be the reason for this error?

**Comment by amahendrakar** [comment]
@Bmoser-boop,
Please refer to the [official guide](https://www.tensorflow.org/install/source#macos) while building the TensorFlow package. 

Also, check the [tested build configurations](https://www.tensorflow.org/install/source#cpu_2) and make sure you have the correct dependencies installed. Thanks!

**Comment by amahendrakar** [comment]
@Bmoser-boop,
Could you please provide the exact sequence of commands / steps that you executed before running into the problem? Also, specify the TensorFlow version you are trying to build. Thanks!

**Comment by Bmoser-boop** [comment]
Sure, here are is the full list of commands:

```
brew install coreutils llvm

brew install cliutils/apple/libomp

git clone https://github.com/zylo117/tensorflow-gpu-macosx

cd tensorflow-gpu-macosx

./configure

bazel build --config=cuda --config=opt --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --action_env PATH --action_env LD_LIBRARY_PATH --action_env DYLD_LIBRARY_PATH //tensorflow/tools/pip_package:build_pip_package
```

Also, I don't think I can give an exact version of Tensorflow because this is a custom-made version of Tensorflow 18 that is designed to allow GPU access for users of Mac OSX 10.13
https://github.com/zylo117/tensorflow-gpu-macosx

More details about the steps I have executed can be found here: https://medium.com/xplore-ai/nvidia-egpu-macos-tensorflow-gpu-the-definitive-setup-guide-to-avoid-headaches-f40e831f26ea

**Comment by Bmoser-boop** [comment]
Additionally, I tried downgrading to Xcode 9.4 and was able to get further, now to 4583 processes completed

**Comment by gowthamkpr** [comment]
@Bmoser-boop What version of tensorflow are you using?

**Comment by Bmoser-boop** [comment]
I was trying to use 1.4.0

**Comment by gowthamkpr** [comment]
@Bmoser-boop Can you please try using latest version of tensorflow like tensorvlow 1.14.0 or 1.15.0 instead of old version of tensorfow. Thanks!
