### ISSUE TITLE
Need to build tensorflow version 2.1.0 from source on Windows

### ISSUE THREAD

**Issue by manidevi** [tensorflow/tensorflow#41997]
**System information**
- OS Platform and Distribution : Windows 10
- TensorFlow installed from (source or binary): source
- TensorFlow version: r2.1
- Python version: 3.6.8
- Bazel version (if compiling from source): 0.29.1
- GCC/Compiler version (if compiling from source):

**Describe the problem**
I want to build tensorflow 2.1.0 from source. Github Branch r2.1 builts tensorflow version 2.1.1 by default. May I know how to explicitly give the tensorflow version for compilation ?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@manidevi 

Please follow this guide to build tensorflow and when you checkout the branch enter the command 
git checkout r2.1.0
https://www.tensorflow.org/install/source_windows

**Comment by manidevi** [comment]
I get the following error for the above command
```
$ git checkout r2.1.0 
error: pathspec 'r2.1.0' did not match any file(s) known to git
```

**Comment by bhack** [comment]
@manidevi you need to run `git checkout v2.1.0`

**Comment by ravikyram** [comment]
@manidevi 

As suggested by @bhack you can try with `git checkout v2.1.0`.Please, check this [gist](https://colab.research.google.com/gist/ravikyram/4206629a3953fa6ede6daf219ca89b53/untitled80.ipynb) for your reference.Thanks!
`

**Comment by manidevi** [comment]
Got it. Thanks @ravikyram  and @bhack
