### ISSUE TITLE
There are some repeated calls in the data_augmentation.ipynb！

### ISSUE THREAD

**Issue by AITutorials** [tensorflow/tensorflow#42007]
The location of the problem：/docs/site/en/tutorials/images/data_augmentation.ipynb
You can find it according to the mark of the picture：
![9371596469059_ pic_hd](https://user-images.githubusercontent.com/61530230/89200299-627e7000-d5e2-11ea-910e-50ee98f30cb8.jpg)
---
`image,label = convert(image, label)`  AND `image = tf.image.convert_image_dtype(image, tf.float32)`  are the same.

**Comment by bhack** [comment]
Can you prepare a small PR?

**Comment by AITutorials** [comment]
OK

**Comment by AITutorials** [comment]
OK



发自我的iPhone


------------------ Original ------------------
