### ISSUE TITLE
Please add Tensorflow 2.3 GPU and all subsequent versions to Conda package manager for Windows and Linux

### ISSUE THREAD

**Issue by johncaling40** [tensorflow/tensorflow#42003]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.2
- Are you willing to contribute it (Yes/No): No because I do not think I can

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**
This will change the current API. It will add the latest version of TensorFlow to Conda. 
**Who will benefit with this feature?**
Anyone who wants to get started with TensorFlow GPU fast or wants to have multiple versions of TensorFlow GPU across multiple environments because when you install TensorFlow-GPU from Conda, it automatically installs CUDA and cuDNN for that specific virtual environment. 
**Any Other info.**
As of right now, only version 2.1 is there for windows and 2.2 for Linux as seen [https://anaconda.org/anaconda/tensorflow-gpu](here)

**Comment by bhack** [comment]
As suggested in others Conda tickets I think it is better to track this in conda github repositories.

**Comment by johncaling40** [comment]
What do you mean by that. Sorry... I am new to this.

**Comment by johncaling40** [comment]
Oh ok...thanks

**Comment by bhack** [comment]
@johncaling40 Could you close this?

**Comment by johncaling40** [comment]
Sure
