### ISSUE TITLE
tf.string.format is not returning Unicode characters

### ISSUE THREAD

**Issue by mikael-epigram** [tensorflow/tensorflow#42001]
As also described in [this Stackoverflow post](https://stackoverflow.com/questions/59795552/tf-string-format-is-not-returning-unicode-characters), when a string passes through `tf.strings.format` unicode characters are not represented correctly.

```python
import tensorflow as tf

print(tf.constant('😊:😊').numpy().decode('utf-8')) # output: 😊:😊
print(tf.strings.format("😊:{}", tf.constant('😊')).numpy().decode('utf-8')) # output: 😊:"\\360\\237\\230\\212" 
```

Error observed in tensorflow 2.2 and 2.3

**Comment by bhack** [comment]
The problem is that the formatted tensor string is escaped:
`b'\xf0\x9f\x98\x8a:"\\360\\237\\230\\212"'`

**Comment by bhack** [comment]
Also the formatted tensor is in Octal Escape Sequence

**Comment by yongtang** [comment]
Added a PR #42067 for the fix.
