### ISSUE TITLE
error: 'std.constant' op requires attribute's type ('tensor<500x2450xf32>') to match op's return type ('tensor<*xf32>')

### ISSUE THREAD

**Issue by tabeareichmann** [tensorflow/tensorflow#42006]
Hello,
We are currently using TFlite to quantize our trained models with FP16 and INT8. When running the experiments the unquantized baseline and FP16 quantization seem to work, but with INT8 the logfile created gives us the following error and output: 
error: 'std.constant' op requires attribute's type ('tensor<500x2450xf32>') to match op's return type ('tensor<*xf32>')
00000000C1C040BD00000000000000000000000000000000C1C040BDC1C0403D00000000C1C0403D000000000000000000000000C1C0403D00000000000000000000000000000000C1C040BDC1C0403D00000000C1C0403D000000000000000000000000C1C0403DC1C0403D00000000C1C0403D00000000C1C040BDC1C0403DC1C0403D00000000000000000000000000000000…
We are running our experiments on the CPUs of a DGX1 and are using TF 2.3, is there anything we are missing?
Thank you!

**Comment by ravikyram** [comment]
@tabeareichmann 

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose).
Provide the exact sequence of commands / steps that you executed before running into the problem.

Thanks!

**Comment by SumanDeedwaniya** [comment]
@tabeareichmann ....Do you got the solution? Can you please tell me if resolved as I am facing the same error while doing the tflite conversion

**Comment by LucasStromberg** [comment]
Facing the same issue when converting a QAT model with quantized Dense layers. Works with Conv2D layers but not Dense.
