### ISSUE TITLE
KeyError on concrete_functions while loading a model

### ISSUE THREAD

**Issue by idofr** [tensorflow/tensorflow#42004]
**System information**
- Have I written custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b
- Python version: 3.7.7
- CUDA/cuDNN version: 10.0 / 7.6
- GPU model and memory: Nvidia Quadro P1000, 4GB

**Describe the current behavior**
When loading a SavedModel object, function_deserialization.py#265 (`concrete_function_objects.append(concrete_functions[concrete_function_name])`) throws a `KeyError` exception caused from looking for a concrete function which is not in the SavedModel (was not serialised). In my case the missing functions are called
1. `__inference_my_model_layer_call_fn_37929`
2. `__inference_my_model_layer_call_fn_38165`
All other concrete functions are successfully located and recovered.

The call traces back to `saved_model/load.py` at line 604. Yet when I debug the values in `object_graph_proto` I can't see these missing keys, meaning they're added at a later phase.
I also tried changing the original code line to
```python
        try:
            concrete_function_objects.append(concrete_functions[concrete_function_name])
        except KeyError:
            print(
                f'from saved_model/function_deserialization.py: couldnt find concrete function {concrete_function_name}'
            )
            continue
        print(
            f'from saved_model/function_deserialization.py: found concrete function {concrete_function_name}'
        )
```
It indeed shows that only these two functions are not found while all other ones are there. Also by doing that I can use the model for testing and inference, i.e. I see no limited functionality at the moment.
Notice there are two similarly-named functions in `concrete_functions` called
1. `__inference_my_model_layer_call_and_return_conditional_losses_35962`
2. `__inference_my_model_layer_call_and_return_conditional_losses_37693`

I guess there are two functions there as one originates from the training function and the other is related to the cross validation function.

My `MyModel` object extends Keras' Model class and contains a series of Models and Layers which are called in the `call` function. `MyModel` doesn't have any paramters or variables of its own. The last object in the series (an object extending `Layer`) also uses `self.add_loss` in its `call` function.

**Describe the expected behavior**
Model should load and work properly.

**Standalone code to reproduce the issue**
Not easy to do since the model structure is rather complicated.

**Other info / logs** Include any logs or source code that would be helpful to
The output without my workaround:
```
Traceback (most recent call last):
  File "test.py", line 148, in <module>
    main()
  File "test.py", line 107, in main
    model = tf.keras.models.load_model(model_path)
  File "tensorflow\python\keras\saving\save.py", line 190, in load_model
    return saved_model_load.load(filepath, compile)
  File "tensorflow\python\keras\saving\saved_model\load.py", line 116, in load
    model = tf_load.load_internal(path, loader_cls=KerasObjectLoader)
  File "tensorflow\python\saved_model\load.py", line 604, in load_internal
    export_dir)
  File "tensorflow\python\keras\saving\saved_model\load.py", line 188, in __init__
    super(KerasObjectLoader, self).__init__(*args, **kwargs)
  File "tensorflow\python\saved_model\load.py", line 123, in __init__
    self._load_all()
  File "tensorflow\python\keras\saving\saved_model\load.py", line 212, in _load_all
    super(KerasObjectLoader, self)._load_all()
  File "tensorflow\python\saved_model\load.py", line 134, in _load_all
    self._load_nodes()
  File "tensorflow\python\saved_model\load.py", line 264, in _load_nodes
    node, setter = self._recreate(proto, node_id)
  File "tensorflow\python\keras\saving\saved_model\load.py", line 233, in _recreate
    obj, setter = super(KerasObjectLoader, self)._recreate(proto, node_id)
  File "tensorflow\python\saved_model\load.py", line 370, in _recreate
    return factory[kind]()
  File "tensorflow\python\saved_model\load.py", line 359, in <lambda>
    "function": lambda: self._recreate_function(proto.function),
  File "tensorflow\python\saved_model\load.py", line 398, in _recreate_function
    proto, self._concrete_functions), setattr
  File "tensorflow\python\saved_model\function_deserialization.py", line 265, in recreate_function
    concrete_function_objects.append(concrete_functions[concrete_function_name])
KeyError: '__inference_my_model_layer_call_fn_37929'
```

**Comment by bhack** [comment]
Can you share a very minimal/dummy but runnable code to reproduce this?

**Comment by idofr** [comment]
No very easily. The model is rather complicated. Dismantling it to the level where I can provide a minimal example would take hours.

**Comment by bhack** [comment]
Are these custom objects?

**Comment by idofr** [comment]
Well.. yes. They are either implementations of keras.layers.Layer or, in the case of multiple layers with a shared semantic meaning, an implementation of keras's Model object, grouping layers together.
For example, imagine an encoder decoder framework for something like VAE. The encoder and decoder are `Model`s and the sampling layer is the custom layer in the middle. The entire thing is then wrapped in a MyModel `Model` class

**Comment by bhack** [comment]
Have you correctly loaded custom objects? e.g.:

```
with CustomObjectScope({'AttentionLayer': AttentionLayer}): model = load_model('my_model.h5')
```

**Comment by idofr** [comment]
No
Where is this documented? 
What does it do?
For what types of objects do i need this?

**Comment by bhack** [comment]
It Is documented many places but I suggest  https://keras.io/guides/serialization_and_saving/

**Comment by idofr** [comment]
The explanations and examples in this page only use the `with` scope if loading from config. Not when using the native `load` function.
Also, it refers the reader to [this](https://keras.io/guides/serialization_and_saving/save_and_serialize.ipynb#custom-objects) page which doesn't exist

**Comment by bhack** [comment]
https://www.tensorflow.org/api_docs/python/tf/keras/utils/CustomObjectScope?hl=en#used-in-the-notebooks

**Comment by idofr** [comment]
It's the same thing. They're not loading a model but restoring from a config
``` python
with custom_object_scope({'my_regularizer': my_regularizer}):
  layer = Dense.from_config(config)
```

**Comment by idofr** [comment]
Ok, so this wasn't the solution, but it set me in the right direction, so many thanks 👍 
After doing the following changes to the code, this now seems to work

1. All `Model` implementations, except for the "main model wrapper thingy", were changes to `Layer` objects.
2. All custom implementations (both the `Layer`s and the `Model`) were given a `get_config` function.
I'm not sure which of these did the trick, but my money is on the first point.

Anyway it's working now so many thanks

**Comment by bhack** [comment]
@idofr To speed-up a little bit the process I suggest you to open a new documentation ticket mentioning this one at https://github.com/keras-team/keras-io

**Comment by Saduf2019** [comment]
@idofr Please update as per above comment

**Comment by idofr** [comment]
What is there to update? you can see exactly that I opened a ticket in keras-io and that the ticket has the status 'open'

**Comment by peri044** [comment]
@idofr Can you elaborate on your [comment ](https://github.com/tensorflow/tensorflow/issues/42004#issuecomment-669118318)as to what those exact changes were ? 
I'm facing a similar issue https://github.com/tensorflow/tensorflow/issues/50706 and it will be helpful.

**Comment by HJasperson** [comment]
To save any future readers my pain, point 1 in [the comment above](https://github.com/tensorflow/tensorflow/issues/42004#issuecomment-669118318) is trying to say that you should change any instances of `tf.keras.Model` to `tf.keras.layers.Layer`. 

My issue was slightly different, but ultimately came down to incorrect/missing concrete functions and point 1 fixed the problem.
