### ISSUE TITLE
assertion error on tf.random.normal() and tf.keras.layers.conv2D()

### ISSUE THREAD

**Issue by Mrutyunjay01** [tensorflow/tensorflow#42008]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: NO
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 64 bit
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: NO
-   **TensorFlow installed from (source or binary)**: Source
-   **TensorFlow version (use command below)**: 2.1.0
-   **Python version**: 3.7.4
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**: 10.1
-   **GPU model and memory**: NVIDIA GeForce MX 250, 2GB
-   **Exact command to reproduce**:
** Following is the code I took from the official documentation [here](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2D) after getting the exact here at tf.keras.layers.Conv2D traceback. 
![Capture](https://user-images.githubusercontent.com/53314831/89201564-50df9d00-d5cf-11ea-8f70-a0dd89fd182d.PNG)

input_shape = (4, 28, 28, 3)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(2, 3, activation='relu', input_shape=input_shape[1:])(x)
print(y.shape)

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-403-88a6eef2a73d> in <module>
----> 1 tf.random.normal((2, 2))

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\ops\random_ops.py in random_normal(shape, mean, stddev, dtype, seed, name)
     67   """
     68   with ops.name_scope(name, "random_normal", [shape, mean, stddev]) as name:
---> 69     shape_tensor = tensor_util.shape_tensor(shape)
     70     mean_tensor = ops.convert_to_tensor(mean, dtype=dtype, name="mean")
     71     stddev_tensor = ops.convert_to_tensor(stddev, dtype=dtype, name="stddev")

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\tensor_util.py in shape_tensor(shape)
    992       # not convertible to Tensors becasue of mixed content.
    993       shape = tuple(map(tensor_shape.dimension_value, shape))
--> 994   return ops.convert_to_tensor(shape, dtype=dtype, name="shape")
    995 
    996 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py in convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, dtype_hint, ctx, accepted_result_types)
   1312 
   1313     if ret is None:
-> 1314       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
   1315 
   1316     if ret is NotImplemented:

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    315                                          as_ref=False):
    316   _ = as_ref
--> 317   return constant(v, dtype=dtype, name=name)
    318 
    319 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py in constant(value, dtype, shape, name)
    256   """
    257   return _constant_impl(value, dtype, shape, name, verify_shape=False,
--> 258                         allow_broadcast=True)
    259 
    260 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py in _constant_impl(value, dtype, shape, name, verify_shape, allow_broadcast)
    264   ctx = context.context()
    265   if ctx.executing_eagerly():
--> 266     t = convert_to_eager_tensor(value, ctx, dtype)
    267     if shape is None:
    268       return t

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\framework\constant_op.py in convert_to_eager_tensor(value, ctx, dtype)
     93     except AttributeError:
     94       dtype = dtypes.as_dtype(dtype).as_datatype_enum
---> 95   ctx.ensure_initialized()
     96   return ops.EagerTensor(value, ctx.device_name, dtype)
     97 

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\eager\context.py in ensure_initialized(self)
    491       if self._initialized:
    492         return
--> 493       assert self._context_devices is None
    494       opts = pywrap_tensorflow.TFE_NewContextOptions()
    495       try:

AssertionError:

**Comment by bhack** [comment]
Can you test with tensorflow `2.2.0` or `2.3.0`?

**Comment by amahendrakar** [comment]
@Mrutyunjay01,
The code snippet you have provided is different from the one in the screenshot. Could you please provide the complete code you are running.

Also, I was able to run the code without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/80686f6f457d043f9b4b870c762a60d9/42008.ipynb#scrollTo=cjXyBOvJHupy). 

As suggested by @bhack, please upgrade to TF v2.3 and check if you are facing the same error in a virtual environment. Thanks!

**Comment by Mrutyunjay01** [comment]
@amahendrakar Yeah, When Conv2D didn't work, I tried running that simple one. But it showed exactly the same error.  However, using tf.compat.v1.disable_eager_execution() surprisingly suppressed the error. But, again I encountered
![error](https://user-images.githubusercontent.com/53314831/89341212-94fd9b00-d6be-11ea-8726-f2e1194e33fe.PNG)
 the same here, Here I am attaching the snippet.

**Comment by Mrutyunjay01** [comment]
If you have noticed, the error is at 493 line of last block, having this line
assert self._context_devices is None.
Yeah, in google colab, it works fine. But what's the problem in my system? And how did it get suppress while using tf.disable_eager_execution(), but again gave error in the same environment?

**Comment by bhack** [comment]
What Is this? Are you changing the code example again?

Could you share a single very very minimal but runnable code and tell us  what kind of error you got?

Thanks

**Comment by Mrutyunjay01** [comment]
Closing the issue as uninstalling and re-installing the updated version solved the issue.

> @Mrutyunjay01,
> The code snippet you have provided is different from the one in the screenshot. Could you please provide the complete code you are running.
> 
> Also, I was able to run the code without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/80686f6f457d043f9b4b870c762a60d9/42008.ipynb#scrollTo=cjXyBOvJHupy).
> 
> As suggested by @bhack, please upgrade to TF v2.3 and check if you are facing the same error in a virtual environment. Thanks!

I am not getting any error now, but Kindly review the 493rd line of my snippet or comment. The code is 
- self._context_devices is None.
And it has no assertion statement. If you could clarify the cause once, thank you.
