### ISSUE TITLE
Sparse input name missing in exported model

### ISSUE THREAD

**Issue by yusliang** [tensorflow/tensorflow#42018]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: Yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: No
-   **TensorFlow installed from (source or binary)**: binary
-   **TensorFlow version (use command below)**: 2.3.0
-   **Python version**: 3.6.11
-   **Bazel version (if compiling from source)**: not used
-   **GCC/Compiler version (if compiling from source)**: not used
-   **CUDA/cuDNN version**: not used
-   **GPU model and memory**: not used
-   **Exact command to reproduce**:  please check below descriptions

### Describe the problem
When using tf.keras.Input with 'sparse=True', the input tensor info names are unreadable in serving signatures, such as args_0, args_0_1, args_0_2. As a result, it is very hard to distinguish when multiple sparse inputs are used in one model.

### Source code / logs
**[produce model]**
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

inputs =  keras.Input(shape=(10,), sparse=True, name='input')  # use a sparse input
dense = layers.Dense(64, activation="relu")
outputs = dense(inputs)
model = keras.Model(inputs=inputs, outputs=outputs, name="model")

tf.keras.models.save_model(model, "exported_model", overwrite=True, include_optimizer=False)

**[examine exported_model]**
$ saved_model_cli show --dir exported_model/ --tag_set serve --signature_def serving_default
output:
The given SavedModel SignatureDef contains the following input(s):
  **inputs['args_0'] tensor_info:**
      dtype: DT_INT64
      shape: (-1, 2)
      **name: serving_default_args_0:0**
  **inputs['args_0_1'] tensor_info:**
      dtype: DT_FLOAT
      shape: (-1)
      **name: serving_default_args_0_1:0**
  **inputs['args_0_2'] tensor_info:**
      dtype: DT_INT64
      shape: (2)
      **name: serving_default_args_0_2:0**
The given SavedModel SignatureDef contains the following output(s):
  outputs['dense'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 64)
      name: StatefulPartitionedCall:0
Method name is: tensorflow/serving/predict

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3,nightly version and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/5b84fee554f77abd68df912ff8d2e9bb/untitled216.ipynb).Thanks!

**Comment by yusliang** [comment]
any updates?

**Comment by yaooolei** [comment]
any updates? +1

**Comment by henglili** [comment]
any updates? +1

**Comment by anirban6908** [comment]
any updates? +1

**Comment by zhangmingnine** [comment]
I ran into the same problem, have you solved it?

**Comment by stephenzwj** [comment]
is there any updates on this issue?

**Comment by tanguycdls** [comment]
Still an issue in 2.5 rc3 any updates on the subject ?

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210530,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/828257b5977439dea95ee3d48bcab242/untitled105.ipynb).Thanks !

**Comment by alionkun** [comment]
it's 2022 H2, any updates ?

**Comment by gowthamkpr** [comment]
@yusliang @alionkun @tanguycdls As mentioned [here](https://github.com/tensorflow/tensorflow/issues/47010#issuecomment-777845056), this cannot be fixed and please use the workarounds. Thanks!!

**Comment by cpy18727** [comment]
any updates? +1

**Comment by Xls1994** [comment]
> @yusliang @alionkun @tanguycdls As mentioned [here](https://github.com/tensorflow/tensorflow/issues/47010#issuecomment-777845056), this cannot be fixed and please use the workaround provided. Thanks!!

Hi, when I uses the sample code in tf 2.10.0 as follows:
```
x_ids = keras.layers.Input(name="x_ids_name",  type_spec=tf.SparseTensorSpec(shape=[None,10], dtype=tf.int64))
output = .... 

model =keras.Model()
model.save("path there",save_format="tf")
```
the saved model still missing the input name, what's wrong with my code?

```
The given SavedModel SignatureDef contains the following input(s):
    inputs['args_0'] tensor_info:
        dtype: DT_INT64
        shape: (-1, 7)
        name: serving_default_args_0:0
```

**Comment by Xls1994** [comment]
the demo code also meets this problem as follows:

```
import tensorflow as tf
from tensorflow import keras

inputs = keras.Input(type_spec=tf.SparseTensorSpec(shape=[None,10],dtype="int64"), name='input') # use a sparse input
dense = keras.layers.Dense(64, activation="relu")
outputs = dense(inputs)
model = keras.Model(inputs=inputs, outputs=outputs, name="model")

tf.keras.models.save_model(model, "./exported_model", overwrite=True, include_optimizer=False)
```

The saved model cli outputs:
```
The given SavedModel SignatureDef contains the following input(s):
  inputs['args_0'] tensor_info:
      dtype: DT_INT64
      shape: (-1, 2)
      name: serving_default_args_0:0
  inputs['args_0_1'] tensor_info:
      dtype: DT_INT64
      shape: (-1)
      name: serving_default_args_0_1:0
  inputs['args_0_2'] tensor_info:
      dtype: DT_INT64
      shape: (2)
      name: serving_default_args_0_2:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['dense'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 64)
      name: StatefulPartitionedCall:0
Method name is: tensorflow/serving/predict
```

**Comment by k-w-w** [comment]
We're trying to figure out a good long-term solution (because at this point arbitrarily renaming the signature names might cause some breaking changes). In the meantime here is an example workaround of how to create understandable names:


```python
def generate_understandable_signature(model):
  # Assume model inputs are a flat list of tensors 
  # (does not support dictionary features)

  # Currently TF2 SavedModel does not support SparseTensor inputs, so we must
  # flatten the sparse tensors into its components (which is why you see args_0,
  # args_0_1, etc.)

  # First, generate TensorSpecs for each Tensor and SparseTensor
  flat_input_specs = []
  for inp, name in zip(model.inputs, model.input_names):
    type_spec = inp.type_spec
    if isinstance(type_spec, tf.SparseTensorSpec):
      rank = type_spec.shape.ndims
      num_values = None
      flat_input_specs.append((
          tf.TensorSpec([num_values, rank], tf.int64, name=f"{name}_indices"),
          tf.TensorSpec([num_values], type_spec.dtype, name=f"{name}_values"),
          tf.TensorSpec([rank], tf.int64, name=f"{name}_shape"))) 
    else:
      # Assume the input is a dense tensor (this snippet doesn't handle ragged)
      flat_input_specs.append(
          tf.TensorSpec(type_spec.dense_shape, dtype=self._dtype, name=f"{name}"))

  # Next, define a tf.function that takes the flat specs as an input and returns the model outputs.
  # The names that were defined in the specs are used as the names from the input signature.
  @tf.function(input_signature=flat_input_specs)
  def model_signature(*args):
    # Re-combine all Sparse components passed into the args.
    model_inputs = []
    for inp in args:
      if isinstance(inp, tuple):
        model_inputs.append(tf.SparseTensor(inp[0], inp[1], inp[2]))
      else:
        model_inputs.append(inp)

    outputs = model(*model_inputs)
    # The SignatureDef outputs are also a map from string name -> tensor,
    # and uses the keys in the returned dictionary as the output names.
    # If outputs is a list / dict, then you should unflatten the outputs like:
    # return {"classes": outputs[0], "scores": outputs[1]}
    return {"outputs": outputs}
  return model_signature
```

You can use this function by calling:
```
tf.keras.models.save_model(model, "./exported_model", overwrite=True,
                           include_optimizer=False,
                           signatures=generate_understandable_signature(model))
```

@Xls1994 's model will return this SignatureDef

```
signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input_indices'] tensor_info:
        dtype: DT_INT64
        shape: (-1, 2)
        name: serving_default_input_indices:0
    inputs['input_shape'] tensor_info:
        dtype: DT_INT64
        shape: (2)
        name: serving_default_input_shape:0
    inputs['input_values'] tensor_info:
        dtype: DT_INT64
        shape: (-1)
        name: serving_default_input_values:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['outputs'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 64)
        name: StatefulPartitionedCall:0
  Method name is: tensorflow/serving/predict
```

**Comment by 648374hub** [comment]
> We're trying to figure out a good long-term solution (because at this point arbitrarily renaming the signature names might cause some breaking changes). In the meantime here is an example workaround of how to create understandable names:
> 
> ```python
> def generate_understandable_signature(model):
>   # Assume model inputs are a flat list of tensors 
>   # (does not support dictionary features)
> 
>   # Currently TF2 SavedModel does not support SparseTensor inputs, so we must
>   # flatten the sparse tensors into its components (which is why you see args_0,
>   # args_0_1, etc.)
> 
>   # First, generate TensorSpecs for each Tensor and SparseTensor
>   flat_input_specs = []
>   for inp, name in zip(model.inputs, model.input_names):
>     type_spec = inp.type_spec
>     if isinstance(type_spec, tf.SparseTensorSpec):
>       rank = type_spec.shape.ndims
>       num_values = None
>       flat_input_specs.append((
>           tf.TensorSpec([num_values, rank], tf.int64, name=f"{name}_indices"),
>           tf.TensorSpec([num_values], type_spec.dtype, name=f"{name}_values"),
>           tf.TensorSpec([rank], tf.int64, name=f"{name}_shape"))) 
>     else:
>       # Assume the input is a dense tensor (this snippet doesn't handle ragged)
>       flat_input_specs.append(
>           tf.TensorSpec(type_spec.dense_shape, dtype=self._dtype, name=f"{name}"))
> 
>   # Next, define a tf.function that takes the flat specs as an input and returns the model outputs.
>   # The names that were defined in the specs are used as the names from the input signature.
>   @tf.function(input_signature=flat_input_specs)
>   def model_signature(*args):
>     # Re-combine all Sparse components passed into the args.
>     model_inputs = []
>     for inp in args:
>       if isinstance(inp, tuple):
>         model_inputs.append(tf.SparseTensor(inp[0], inp[1], inp[2]))
>       else:
>         model_inputs.append(inp)
> 
>     outputs = model(*model_inputs)
>     # The SignatureDef outputs are also a map from string name -> tensor,
>     # and uses the keys in the returned dictionary as the output names.
>     # If outputs is a list / dict, then you should unflatten the outputs like:
>     # return {"classes": outputs[0], "scores": outputs[1]}
>     return {"outputs": outputs}
>   return model_signature
> ```
> 
> You can use this function by calling:
> 
> ```
> tf.keras.models.save_model(model, "./exported_model", overwrite=True,
>                            include_optimizer=False,
>                            signatures=generate_understandable_signature(model))
> ```
> 
> @Xls1994 's model will return this SignatureDef
> 
> ```
> signature_def['serving_default']:
>   The given SavedModel SignatureDef contains the following input(s):
>     inputs['input_indices'] tensor_info:
>         dtype: DT_INT64
>         shape: (-1, 2)
>         name: serving_default_input_indices:0
>     inputs['input_shape'] tensor_info:
>         dtype: DT_INT64
>         shape: (2)
>         name: serving_default_input_shape:0
>     inputs['input_values'] tensor_info:
>         dtype: DT_INT64
>         shape: (-1)
>         name: serving_default_input_values:0
>   The given SavedModel SignatureDef contains the following output(s):
>     outputs['outputs'] tensor_info:
>         dtype: DT_FLOAT
>         shape: (-1, 64)
>         name: StatefulPartitionedCall:0
>   Method name is: tensorflow/serving/predict
> ```

Hello @k-w-w , I'm facing the same issue when using Ragged tensor inputs. Is there any equivalent solution that can accommodate Ragged Tensor inputs ? Please help as I believe it's an open issue.
