### ISSUE TITLE
After I used SyncReplicasOptimizer, tf hang at sess.run 

### ISSUE THREAD

**Issue by haibarasiao** [tensorflow/tensorflow#4201]
After I used SyncReplicasOptimizer and chief queue runner in distribute tensorflow, it hangs at sess.run.
But after I added below:
        queue_runners = tf.get_collection(tf.GraphKeys.QUEUE_RUNNERS)
        sv.start_queue_runners(sess, queue_runners)  
this queue runs OK.
Anyone can tell me why?
I added this code before:
      if is_chief:
          sv.start_queue_runners(sess, chief_queue_runner)
          sess.run(init_token_op)

**Comment by tatatodd** [comment]
We primarily use github issues to track bugs and installation issues.  This is a question better suited for StackOverflow.  Please ask it there and tag it with the `tensorflow` tag.  Thanks!

Some links that you may find helpful:
https://www.tensorflow.org/versions/r0.10/how_tos/distributed/index.html
http://stackoverflow.com/questions/38732502/tensorflow-master-and-worker-service/38749421#38749421
