### ISSUE TITLE
ValueError: Input tensors to a Functional must come from `tf.keras.Input` (TF 2.3)

### ISSUE THREAD

**Issue by OverLordGoldDragon** [tensorflow/tensorflow#42014]
Example below works in 2.2; `K.function` [now builds](https://github.com/tensorflow/tensorflow/blob/r2.3/tensorflow/python/keras/backend.py#L3911) a `Model` in Eager execution, so we're passing `Model(inputs=[learning_phase,...])`.

I do have a workaround in mind, but it's hackish, and lot more complex than `K.function`; is there an analog to below in 2.3?

<hr>

```python
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
from tensorflow.python.keras import backend as K
import numpy as np

ipt = Input((16,))
x   = Dense(16)(ipt)
out = Dense(16)(x)
model = Model(ipt, out)
model.compile('sgd', 'mse')

outs_fn = K.function([model.input, K.symbolic_learning_phase()],
                     [model.layers[1].output])  # error
x = np.random.randn(32, 16)
print(outs_fn([x, True]))
```
```
>>> ValueError: Input tensors to a Functional must come from `tf.keras.Input`. 
Received: Tensor("keras_learning_phase:0", shape=(), dtype=bool) 
(missing previous layer metadata).
```

**Comment by OverLordGoldDragon** [comment]
[Resolved](https://stackoverflow.com/q/63238203/10133797).

**Comment by mohammadrezaghorvei** [comment]
I have a problem like you what can I do to solve it

**Comment by amahendrakar** [comment]
> I have a problem like you what can I do to solve it

@mohammadrezaghorvei,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
