### ISSUE TITLE
Issue Running T5 in colab TPU - Tensorflow

### ISSUE THREAD

**Issue by ashispapu** [tensorflow/tensorflow#42021]
Hi Team,

I was trying to do a pre training of T5 from scratch on colab. I could see if i install t5 using (pip install t5[gcp]), and tried to connect to execute tf.tpu.experimental.initialize_tpu_system(tpu), getting below error.

InvalidArgumentError: NodeDef expected inputs 'string' do not match 0 inputs specified; Op<name=_Send; signature=tensor:T -> ; attr=T:type; attr=tensor_name:string; attr=send_device:string; attr=send_device_incarnation:int; attr=recv_device:string; attr=client_terminated:bool,default=false; is_stateful=true>; NodeDef: {{node _Send}}

If install/ upgrade tensorflow, it gets resolved, however import of t5 does not work as below.
import t5

NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl11string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS8_EE

Please let me know how if there is a way to resolve this.
Thanks.

**Comment by Saduf2019** [comment]
@ashispapu 

This error has already been answered in another issue. Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/40622#issuecomment-654488935) from a member of the TensorFlow team. Thanks!


In case you issue is not resolved can you please update update the issue template with the tf version on which this error was faced and simple stand alone code to replicate it or is possible share colab gist with error.

**Comment by ashispapu** [comment]
@Saduf2019  I also got the same issues, when i tried to connect the a VM instance with a TPU node(v2-8).

**Comment by Saduf2019** [comment]
@ashispapu
Please share the colab gist for us to replicate the issue faced.
