### ISSUE TITLE
Stale(?) references to activation histograms

### ISSUE THREAD

**Issue by bersbersbers** [tensorflow/tensorflow#42027]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard

### Clear description

URL above says

> `histogram_freq`    frequency (in epochs) at which to compute activation and weight histograms ...

However,
- I do not see any activation histograms in my TensorBoard despite using `validation_data` - only biases and kernels.
- I do not see any activation-specific code in https://github.com/tensorflow/tensorflow/blob/b36436b087bd8e8701ef51718179037cccdfc26e/tensorflow/python/keras/callbacks.py#L2227-L2238

See also https://stackoverflow.com/questions/60816678/

Therefore, I suspect that activation histograms are not logged at all.

**Comment by bersbersbers** [comment]
For more information, the code that produces activation histograms seems to have been removed here:
https://github.com/tensorflow/tensorflow/commit/5b7063a3cfdc7710721924c5b4350c8265d5ff2d#diff-7db86ff688aaa0e9c0619dace9b487e7

**Comment by jvishnuvardhan** [comment]
@bersbersbers Can you please share a simple standalone code to reproduce the issue? Thanks!

**Comment by bersbersbers** [comment]
@jvishnuvardhan sure:

```
import tensorflow as tf

(model := tf.keras.applications.vgg16.VGG16()).compile(loss="mse")
model.fit(
    x=tf.zeros((1, *model.input.shape[1:])),
    y=tf.zeros((1, *model.output.shape[1:])),
    callbacks=tf.keras.callbacks.TensorBoard(histogram_freq=1),
)

# then do
# tensorboard --logdir logs --port 6007
# and open
# http://localhost:6007/
```

![image](https://user-images.githubusercontent.com/12128514/89502519-69b1a380-d7c5-11ea-90d4-c6cf6cd8419b.png)

Note bias and kernels - no activations

**Comment by jvishnuvardhan** [comment]
@bersbersbers I ran your code and see more histograms. Can you please check [the gist here](https://colab.research.google.com/gist/jvishnuvardhan/b8585ef3e6e0fcfcbc981c24a5e7eb40/untitled973.ipynb) and let me know whether we are missing anything. Thanks!

If the above gist is not working, then please look into this [page](https://github.com/jvishnuvardhan/GitHub_Questions/blob/master/42027.ipynb).

Thanks!

**Comment by bersbersbers** [comment]
@jvishnuvardhan it seems that my screenshot still shows the histograms of the VGG16 network that I used in my earlier example. I wanted to switch the screenshot as well as the code, but apparently I missed the former. (You can also see that the layer names are different.)

But still: yes, MobileNet has more types of parameters than VGG16, so it shows more histograms. But all of these shown I understand more as weights, definitely not as activations. So your gist does show the issue: activation histograms are missing.

**Comment by hunse** [comment]
I am also having this issue, using completely different code.

**Comment by hunse** [comment]
Here's a minimal example:
```python
import tensorflow as tf

inp = x = tf.keras.Input(1)
x = tf.keras.layers.Dense(units=10, activation=tf.nn.relu)(x)
x = tf.keras.layers.Dense(units=10)(x)
x = tf.keras.layers.Activation(tf.nn.relu)(x)
model = tf.keras.Model(inp, x)

model.compile(loss="mse", optimizer="adam")
model.fit(
    tf.ones((32, 1)),
    tf.ones((32, 10)),
    callbacks=[tf.keras.callbacks.TensorBoard("logs", histogram_freq=1)],
    epochs=100,
)
```
When viewing the logs with ``tensorboard --logdir logs`` and going to the Histograms tab, histograms for the layer weights show up, but not for any of the activities.

**Comment by bersbersbers** [comment]
This may be a duplicate of #39755.

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/a9b892e97465169e3791040285fa874a/untitled973.ipynb#scrollTo=Da1K5IYVzoxs)..Thanks !

**Comment by bersbersbers** [comment]
I re-posted this issue in https://github.com/keras-team/keras/issues/15972.
