### ISSUE TITLE
RESIZE_NEAREST_NEIGHBOR Operation version not supported

### ISSUE THREAD

**Issue by ZhouKai90** [tensorflow/tensorflow#42024]
def save_tflite():
  converter = tf.lite.TFLiteConverter.from_saved_model(FLAGS.weights)
  converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
  converter.optimizations = [tf.lite.Optimize.DEFAULT]
  converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
  converter.allow_custom_ops = True
  converter.representative_dataset = representative_dataset_gen
  tflite_model = converter.convert()
  open(FLAGS.output, 'wb').write(tflite_model)

  TF version:2.3.0  

Edge TPU Compiler version 14.1.317412892
Input: yolov3-416-int8.tflite
Output: yolov3-416-int8_edgetpu.tflite

Operator                       Count      Status

DEQUANTIZE                     3          Operation is working on an unsupported data type
QUANTIZE                       2          More than one subgraph is not supported
QUANTIZE                       1          Operation is otherwise supported, but not mapped due to some unspecified limitation
CONV_2D                        15         More than one subgraph is not supported
CONV_2D                        60         Mapped to Edge TPU
RESIZE_NEAREST_NEIGHBOR        2          Operation version not supported
PAD                            5          Mapped to Edge TPU
CONCATENATION                  2          More than one subgraph is not supported
ADD                            23         Mapped to Edge TPU

when I use Edge TPU Compiler compile tflite model, I got the error about RESIZE_NEAREST_NEIGHBOR,ths.

**Comment by ymodak** [comment]
I see RESIZE_NEAREST_NEIGHBOR Op is [supported](https://coral.ai/docs/edgetpu/models-intro/#supported-operations).
Also [google-coral/edgetpu](https://github.com/google-coral/edgetpu/issues) repo can be a good platform to raise this issue.
Please try posting it there.
I am tagging similar [thread ](https://github.com/google-coral/edgetpu/issues/187) for your reference. Thanks!

**Comment by Namburger** [comment]
@ymodak thanks! This is a compiler issue, not tflite conversion

**Comment by ymodak** [comment]
@Namburger Thanks for your help.
@ZhouKai90 I will close this issue since you have a more helpful dialogue on another thread. Thanks!
