### ISSUE TITLE
Tensorflow 2.1 + Docker + CUDA 10.2 Issue with the recognition of the graphics card

### ISSUE THREAD

**Issue by johnny-mueller** [tensorflow/tensorflow#42030]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Developer laptop -> Win10, Docker container: ubuntu18.04, Server: Linux
- TensorFlow installed from (source or binary): Source with pip
- TensorFlow version: 2.1
- Python version: 3.6
- Installed using virtualenv? pip? conda?: docker (pip)
- CUDA/cuDNN version: Developer laptop: 10.2, Server: 10.2
- GPU model and memory: Developer laptop GTC 1660 Ti, Server=?

**Describe the problem**
I am developing a deep learning model with Tensorflow2 and this model should be trained inside a docker container on the server. If I run the code on my laptop without a docker container, the GPU of the laptop will be recognized and can be trained with it. As soon as the code is in the container, no graphics card is recognized anymore, but the output of Tensorflow2 is generated, which is located at the bottom of **Any other info / logs**.

the problem seems to be that the containers do not allow access to the graphics cards.

**Any other info / logs**
```python
2020-08-04 10:44:10.798030: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-08-04 10:44:10.798086: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-08-04 10:44:10.798117: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (12e682dbeadb): /proc/driver/nvidia/version does not exist
```

**Comment by Saduf2019** [comment]
@johnny-mueller 
Can you try setting the environment variable CUDA_VISIBLE_DEVICES to either blank or emptystring "", or possibly -1.
Please refer to [this resolved issue](https://github.com/tensorflow/tensorflow/issues/4267#issuecomment-248656096) and let us know.
resolved issues related to the error reported
#4078 [link](https://github.com/tensorflow/tensorflow/issues/255#issuecomment-384846967) [link1](https://stackoverflow.com/questions/60706122/cuda-driver-errors-on-the-machine-without-gpu-while-loading-model)

**Comment by johnny-mueller** [comment]
@Saduf2019 

Output of "ls -l /usr/local/cuda/lib/libcud*":
```python
root@1dbaa98b68fb:/# ls -l /usr/local/cuda/lib/libcud*
ls: cannot access '/usr/local/cuda/lib/libcud*': No such file or directory
```

Output of "export LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/lib":
```python
root@1dbaa98b68fb:/# root@1dbaa98b68fb:/# ls -l /usr/local/cuda/lib/libcud*
root@1dbaa98b68fb:/# ls: cannot access '/usr/local/cuda/lib/libcud*': No such file or directory
```


```python
root@1dbaa98b68fb:/# export NVID_VER=440.33.01
root@1dbaa98b68fb:/# cd /path/to/libcuda.so.$NVID_VER
bash: cd: /path/to/libcuda.so.440.33.01: No such file or directory
root@1dbaa98b68fb:/# ln -s libcuda.so.$NVID_VER libcuda.so
root@1dbaa98b68fb:/# ln -s libcuda.so.$NVID_VER libcuda.so.1
```

**Comment by bhack** [comment]
@johnny-mueller Can you share the output of `docker run --gpus all nvidia/cuda:10.0-base nvidia-smi`?

**Comment by johnny-mueller** [comment]
@bhack 
```python
docker run --gpus all nvidia/cuda:10.0-base nvidia-smi
Unable to find image 'nvidia/cuda:10.0-base' locally
10.0-base: Pulling from nvidia/cuda
7ddbc47eeb70: Already exists                                                                                            
c1bbdc448b72: Already exists                                                                                            
8c3b70e39044: Already exists                                                                                            
45d437916d57: Already exists                                                                                            
d8f1569ddae6: Already exists                                                                                            
de5a2c57c41d: Already exists                                                                                            
ea6f04a00543: Already exists                                                                                            
Status: Downloaded newer image for nvidia/cuda:10.0-base
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
```

**Comment by bhack** [comment]
Can you try to re-run the same command after these https://github.com/NVIDIA/nvidia-docker#ubuntu-160418042004-debian-jessiestretchbuster?

**Comment by johnny-mueller** [comment]
@bhack that is quite complicated because im working on an Windows laptop and i have not the specific rights to execute these on the linux server

**Comment by bhack** [comment]
Let see if you have an old installation can you test `docker run --rm --runtime=nvidia -ti nvidia/cuda nvidia-smi`

**Comment by johnny-mueller** [comment]
```python
docker run --rm --runtime=nvidia -ti nvidia/cuda nvidia-smi
docker: Error response from daemon: Unknown runtime specified nvidia.
See 'docker run --help'.
```

**Comment by bhack** [comment]
@johnny-mueller So I think that you need to talk with the linux machine sysadmin to ask about enable the docker gpu setup.

**Comment by johnny-mueller** [comment]
@bhack thanks for the advice. I will call the admin tomorrow and will link this issue. Thanks for your help

**Comment by gowthamkpr** [comment]
@johnny-mueller Any updates on this issue?
