### ISSUE TITLE
Add deterministic tf.image.crop_and_resize backprop

### ISSUE THREAD

**Issue by duncanriach** [tensorflow/tensorflow#42033]
Note: I am willing and able to implement this feature but I don't know when I will get to it. My intention in creating this issue is to clearly reproduce and document the current nondeterministic functionality for the community and to allow for someone else to address it, if they have available bandwidth.

**System information**
- TensorFlow version: nondeterminism reproduced using version 2.3.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
See nondeterminism repro code at the end of this comment.
- Backprop to `image` is nondeterministic on both CPU and GPU. CPU variance is much higher.
- Backprop to `boxes` is nondeterministic on GPU.

**Will this change the current api? How?**
**No**. Existing environment variable `TF_DETERMINISTIC_OPS=1` will enable deterministic operation for `tf.image.crop_and_resize`

**Who will benefit with this feature?**
Users who care about determinism in TensorFlow, which includes users running safety-critical applications or anyone who wants to save time and compute cycles spent re-running nondeterministic processes for reproing, debugging, experimentation, and regression testing. This current feature request was prompted by framework-determinism [issue 18](https://github.com/NVIDIA/framework-determinism/issues/18).

**Any Other info.**
A solution will look similar to [PR 39243](https://github.com/tensorflow/tensorflow/pull/39243), from me, in this current repo. A solution will require new CUDA kernels in `crop_and_resize_op_gpu.cu.cc`. The existing kernels utilize CUDA `atomicAdd` in such a way as to introduce nondeterminism.

**Test / Repro Code**
```
import os
import tensorflow as tf

# Force-disable GPU:
# os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

# The following line is how determinism will be enabled, but is not expected
# to currently have any effect on the output.
os.environ['TF_DETERMINISTIC_OPS'] = '1'

batch_size = 16
input_height = 64
input_width = 64
depth = 1
input_shape = (batch_size, input_height, input_width, depth)
tf.random.set_seed(456)
image = tf.random.uniform(
    input_shape, minval=-1.0, maxval=1.0, dtype=tf.float32)

# Image Gradients:
#
# Upsampling of a crop, leading to three or more output pixels being derived
# from an input pixel, will contribute to nondeterminism in the gradient
# associated with that input pixel location.
#
# Note that the number of boxes can be less than, equal to, or greater than
# the batch size. Three or more crops overlapping on the same input image pixel
# can independently contribute to nondeterminism in the image gradient
# associated with that input pixel location. This is independent of
# contributions caused by the upsampling of any given crop.
#
# Boxes Gradients:
#
# If the input and output dimensions are the same, then the boxes gradients
# will be deterministically zero, otherwise they will contain nondeterminism
# weather there is upsampling or downsampling and whether or not there are
# overlapping crops.

box_count = 4 * batch_size
boxes = tf.random.uniform(
  (box_count, 4), minval=0.0, maxval=1.01, dtype=tf.float32)

box_indices = tf.random.uniform(
  (box_count, ), minval=0, maxval=batch_size, dtype=tf.int32)

crop_size = [input_height*2, input_width*2]
output_shape = (box_count, *crop_size, depth)

injected_gradients = tf.random.uniform(
    output_shape, minval=-0.001, maxval=0.001, dtype=tf.float32)

def gradients():
  with tf.GradientTape() as tape:
    tape.watch([image, boxes])
    output = tf.image.crop_and_resize(
        image, boxes, box_indices, crop_size, method='bilinear')
    upstream = output * injected_gradients
  return tape.gradient(upstream, [image, boxes])

def sum(tensor):
  return tf.reduce_sum(tensor)

for device in ['gpu', 'cpu']:
  print("\n# Running on {}:\n".format(device))
  print("#         Image Gradients |  Boxes Gradients")
  print("#        -----------------+------------------")
  msg = "# Run {:d}: {:15.13f} | {:16.13f}"
  with tf.device("/{}:0".format(device)):
    for i in range(8):
      image_gradients, boxes_gradients = gradients()
      print(msg.format(i+1, sum(image_gradients), sum(boxes_gradients)))

print("")

# Example output (running on TensorFlow 2.3.0):

# Running on gpu:

#         Image Gradients |  Boxes Gradients
#        -----------------+------------------
# Run 1: -1.2592203617096 | -55.5643386840820
# Run 2: -1.2592202425003 | -55.5643081665039
# Run 3: -1.2592201232910 | -55.5643692016602
# Run 4: -1.2592203617096 | -55.5644264221191
# Run 5: -1.2592200040817 | -55.5643730163574
# Run 6: -1.2592201232910 | -55.5644035339355
# Run 7: -1.2592202425003 | -55.5643386840820
# Run 8: -1.2592201232910 | -55.5643272399902

# Running on cpu:

#         Image Gradients |  Boxes Gradients
#        -----------------+------------------
# Run 1: -1.2608621120453 | -55.5644989013672
# Run 2: -1.2792857885361 | -55.5644989013672
# Run 3: -1.2577195167542 | -55.5644989013672
# Run 4: -1.2553272247314 | -55.5644989013672
# Run 5: -1.2539256811142 | -55.5644989013672
# Run 6: -1.2622516155243 | -55.5644989013672
# Run 7: -1.2515500783920 | -55.5644989013672
# Run 8: -1.2537302970886 | -55.5644989013672
```

**Comment by rmothukuru** [comment]
@duncanriach,
As per your statement,

> I am willing and able to implement this feature 

Can you please let us know if you are planning to implement this feature? Thanks!

**Comment by duncanriach** [comment]
I'm sorry, @rmothukuru, but I cannot give an ETA for a deterministic GPU solution right now.

## Additional Information

I maintain a publicly-visible status for progress on GPU-determinism of this op [here](https://github.com/NVIDIA/framework-determinism/blob/master/tensorflow_status.md#crop-and-resize).

PR [48905](https://github.com/tensorflow/tensorflow/pull/48905), which will almost certainly be represented in TF 2.6, adds deterministic CPU functionality for this op plus exception-throwing (if determinism is expected) on GPU.

Our focus right now is on implementing [RFC: Enabling Determinism in TensorFlow](https://github.com/tensorflow/community/blob/master/rfcs/20210119-determinism.md), which adds exception-throwing for all nondeterministic GPU-op paths (if determinism is expected) and also GPU-determinism for the segment reduction ops and the softmax/cross-entropy loss functions.

**Comment by jvishnuvardhan** [comment]
@duncanriach Is this still an issue? I have seen your contributions (in other GitHub issues) related to determinism. Also, this TF page also mentions about running ops deterministically https://www.tensorflow.org/api_docs/python/tf/config/experimental/enable_op_determinism.

Should we still keep this open? Thanks!

**Comment by duncanriach** [comment]
Hi @jvishnuvardhan, this is one of several ops that do still need to have deterministic GPU implementations added. I do intend to get to this at some point, but it's not currently my highest priority. It is still an issue, but I cannot give an ETA for resolution. Do you think it should be closed, or left open?

**Comment by jvishnuvardhan** [comment]
@duncanriach We will leave it open. Thanks!

**Comment by duncanriach** [comment]
@mohantym, nothing has changed since TF 2.6, as reported in my 2021-05-06 [comment](https://github.com/tensorflow/tensorflow/issues/42033#issuecomment-833869754) above. Since TF 2.6, the CPU functionality has been deterministic, and the GPU functionality throws an exception to alert the user that op-determinism is not yet available on GPU. This is also as reported in [this status](https://github.com/NVIDIA/framework-determinism/blob/master/doc/tensorflow_status.md#crop-and-resize).

To demonstrate, I took [the original repro code](https://github.com/tensorflow/tensorflow/issues/42033#issue-672761931) and put it into [this colab](https://colab.research.google.com/drive/1M6Ud6vge8z7pB50Ho8sfa2lfR---00uh?usp=sharing), with some updates and enhancements. Here is the output from that:

```
# TensorFlow version: 2.8.0

# Running on gpu:

#         Image Gradients |  Boxes Gradients
#        -----------------+------------------
#        UnimplementedError: Deterministic GPU implementation of CropAndResizeBackpropImage not available. [Op:CropAndResizeGradImage]

# Running on cpu:

#         Image Gradients |  Boxes Gradients
#        -----------------+------------------
# Run 1: -1.2592202425003 | -55.5644302368164
# Run 2: -1.2592202425003 | -55.5644302368164
# Run 3: -1.2592202425003 | -55.5644302368164
# Run 4: -1.2592202425003 | -55.5644302368164
# Run 5: -1.2592202425003 | -55.5644302368164
# Run 6: -1.2592202425003 | -55.5644302368164
# Run 7: -1.2592202425003 | -55.5644302368164
# Run 8: -1.2592202425003 | -55.5644302368164
```

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
