### ISSUE TITLE
TF with CUDA 11 and cuDNN 8

### ISSUE THREAD

**Issue by pkanwar23** [tensorflow/tensorflow#42047]
Enable TF-nightly with CUDA 11 and cuDNN 8 for Ubuntu and Windows.

**Comment by summa-code** [comment]
NVIDIA pretty much pushed CUDA 10 out of the view. This team needs to have tf-nightly with CUDA 11. A lots of bugs are being introduced because of this not being to CUDA 11.

**Comment by mihaimaruseac** [comment]
This bug is the tracking bug for converting to CUDA 11.

**Comment by summa-code** [comment]
But this used to work.

**Comment by mihaimaruseac** [comment]
Accidentally. We never tested it and breakages of something that was accidentally working were not discovered.

This bug tracks moving to building with CUDA 11 by default

**Comment by summa-code** [comment]
As of now, i am building from source for Nvidia 11. But... we have to be careful though, the recent Nvidia update upended my system. :-( and had to spend lots of time figuring out.

**Comment by sanjoy** [comment]
>  the recent Nvidia update upended my system

@summa-code I recommend using [docker](https://www.tensorflow.org/install/docker#download_a_tensorflow_docker_image) if that works for your use case.

**Comment by summa-code** [comment]
Well, i know i would have used docker if there are frequent issues in building in the source. But the problem was in the system level nvidia kernal. Reinstalling fixed the issue.

**Comment by pkanwar23** [comment]
Hi all: We made the changes for Ubuntu last night. Changes for Windows should land soon.

**Comment by mihaimaruseac** [comment]
Closing as nightly now uses CUDA 11
