### ISSUE TITLE
Import Tensorflow giving error

### ISSUE THREAD

**Issue by pratapmalani** [tensorflow/tensorflow#42058]
Hi,
I am trying to deploy a simple CNN on FLASK. on operating system Windows 10, 
Python 3.8.3
tensor flow version is 2.3.0  (installed using pip install)
keras version 2.4.3 (installed using pip install)

I uninstalled and reinstalled Anaconda also. 
Upgraded  Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019 from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

My system has CPU (no GPU), 4GB RAM, i5 processor

For the statement "import tensorflow as tf" i am getting an error.

D:\>python -c "import tensorflow as tf"
Traceback (most recent call last):
  File "C:\Users\amala\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\amala\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\amala\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\amala\Anaconda3\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\amala\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\amala\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\amala\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

*******************************************************************************************************

### If I use TensorFlow 2.2.0, I get the following error

D:\>python -c "import tensorflow as tf"
Traceback (most recent call last):
  File "C:\Users\amala\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\amala\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\amala\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\amala\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\amala\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\amala\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\amala\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\amala\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\amala\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\amala\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\amala\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\amala\Anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\amala\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ayush0x00** [comment]
Since you are using python v3, try installing tensorflow using pip3.
See this [link](https://www.tensorflow.org/install/pip) for installing tensorflow.

**Comment by amahendrakar** [comment]
@pratapmalani,
You might be facing this issue because of the following reasons

- You you running 32-bit Python or 32-bit OS
- You have not installed the [Microsoft Visual C++ Redistributable](https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads) package
- Your CPU does not support AVX instructions. 

Please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) and check if you have the correct dependencies installed.

Also, check these similar duplicate issues: #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204.

Thanks!

**Comment by pratapmalani** [comment]
@ayush0x00 Thanks for your response. using pip3 instead of pip is giving the same error.

@amahendrakar
Thanks for your response. 

**From System Requirement:**

pip3 version is 20.1.1

Windows 10 Home Single Language
Version 1909
OS build 18363.959

I already installed installed MS Visual C++ (as mentioned in first message)

I have also installed NVIDIA CUDA 10.2

**Hardware Details:**

HP Laptop 15-da1xxx
Processor: Intel(R) Core(TM) i5-8265U CPU @ 1.60Ghz 1.80GHz
System type: 64-bit operating system, x64-based processor

My processor supports AVX ( https://en.wikichip.org/wiki/intel/core_i5/i5-8265u )

Please suggest if i am missing something here.

**Comment by pratapmalani** [comment]
> @pratapmalani,
> You might be facing this issue because of the following reasons
> 
> * You you running 32-bit Python or 32-bit OS
> * Your CPU does not support AVX instructions, please provide the make and model of your CPU in this case.
> 
> Please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) and check if you have the correct dependencies installed.
> 
> Also, check these similar duplicate issues: #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204.
> 
> Thanks!



@amahendrakar
Thanks for your response.

From System Requirement:

pip3 version is 20.1.1

Windows 10 Home Single Language
Version 1909
OS build 18363.959

I already installed installed MS Visual C++ (as mentioned in first message)

I have also installed NVIDIA CUDA 10.2

Hardware Details:

HP Laptop 15-da1xxx
Processor: Intel(R) Core(TM) i5-8265U CPU @ 1.60Ghz 1.80GHz
System type: 64-bit operating system, x64-based processor

My processor supports AVX ( https://en.wikichip.org/wiki/intel/core_i5/i5-8265u )

Please suggest if i am missing something here.

**Comment by pratapmalani** [comment]
> Since you are using python v3, try installing tensorflow using pip3.
> See this [link](https://www.tensorflow.org/install/pip) for installing tensorflow.

@ayush0x00 Thanks for your response. using pip3 instead of pip is giving the same error.

**Comment by amahendrakar** [comment]
@pratapmalani,
Could you please check if the Anaconda version is also 64 bit? Thanks!

**Comment by pratapmalani** [comment]
@amahendrakar 

I have used Anaconda3-2020.07-Windows-x86_64.exe to setup Anaconda.

Jupyter notebook is opening well.

import tensorflow in jupyter notebook is also throwing same error.

**Comment by jvishnuvardhan** [comment]
@pratapmalani 

> I have also installed NVIDIA CUDA 10.2

I am not sure why you installed CUDA drivers as you don't have GPU. 

Some time back when i had issues with CPU and windows10 (but not Anaconda), I uninstalled all the TF versions and completely removed the folders related to Tensorflow and then reinstalled TF. Can you also try installing Python3.7/3.6 to check whether that resolves your issue.

Generally we don't support Anaconda based Installation issues as Anaconda maintain those builds. It is better if you post this issue in Anaconda repo, then you might get faster resolution so that you can start using TF.

Please let me know how it progresses. thanks!

**Comment by pratapmalani** [comment]
@jvishnuvardhan 

Thanks for your help and guidance. Yes, i uninstalled TF and Anaconda, deleted all related folders and did a fresh installation. Now things are working well.

Thanks to @amahendrakar  @ayush0x00  for your help and guidance.
