### ISSUE TITLE
TensorFlow Lite causes segementation faults in C++ when creating threads if fully statically linked

### ISSUE THREAD

**Issue by Lif3line** [tensorflow/tensorflow#42057]
**System information**
- Linux Ubuntu 18.04
- TensorFlow Binary (via `pip`)
- Tested on 2.1.0, 2.2.0, 2.3.0 & all recent master branches of `tensorflow/tensorflow:devel` up to my last comment
  - I have a local CI script tracking this issue
- Tested on `x86_64` as well as ARM builds

**Problem**
- Segmentaion fault on `invoke()` when running any model that spawns threads 
  - Only occurs if TensorFlow Lite library has been statically linked
  - Not an issue in older versions (pre-2.0.0)

**Problem Reproduction**
- Standard Tensorflow Lite library build
  - Spin up `tensorflow/tensorflow:devel` docker container
  - `cd tensorflow_src`
  - `./tensorflow/lite/tools/make/download_dependencies.sh`
  - `./tensorflow/lite/tools/make/build_lib.sh`
  - Grab TensorFlow and Flatbuffer headers, as well as Tensorflow `.a` file
- Compile [tflite c++ minimal example](https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_c)
  - GCC 7.5
  - Static
    - `g++ minimal.cc -I../tensorflow_headers -I../flatbuffers_include -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -pthread -g -static -L../tensorflow_lib -ltensorflow-lite -ldl -o tflite_min_static`
  - Dynamic
    - `g++ minimal.cc -I../tensorflow_headers -I../flatbuffers_include -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -pthread -g -L../tensorflow_lib -ltensorflow-lite -ldl -o tflite_min_dynamic`
- Make some test models
  - Convolutional model creates extra threads, non-convolutional model does not
```python
import tensorflow as tf
from tensorflow.keras.layers import Conv2D, Flatten, Input, Dense
from tensorflow.keras.models import Model

### With a convolution (creates threads on invoke())
inputs = Input(shape=[10, 5, 1])
x = inputs
x = Conv2D(32, (3, 3))(x)
x = Flatten()(x)
x = Dense(1)(x)

model = Model(inputs, x)
model.compile()

# Convert the model.
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

# Save the TF Lite model.
with tf.io.gfile.GFile("min_model_with_conv.tflite", "wb") as f:
    f.write(tflite_model)

### Without convolution (no extra threading)
inputs = Input(shape=[10, 5, 1])
x = inputs
# x = Conv2D(32, (3, 3))(x)
x = Flatten()(x)
x = Dense(1)(x)

model = Model(inputs, x)
model.compile()

# Convert the model.
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

# Save the TF Lite model.
with tf.io.gfile.GFile("min_model_no_conv.tflite", "wb") as f:
    f.write(tflite_model)

```
- Run minimal examples
  - `tflite_min_dynamic min_model_no_conv.tflite`: pass
  - `tflite_min_dynamic min_model_with_conv.tflite`: pass
  - `tflite_min_static min_model_no_conv.tflite`: pass
  - `tflite_min_static min_model_with_conv.tflite`: segmentation fault
- From `gdb --args tflite_min_static min_model_with_conv.tflite`
```
Node   2 Operator Builtin Code   9 FULLY_CONNECTED
  Inputs: 6 2 -1
  Outputs: 7
[New Thread 0x7fffff7b0700 (LWP 2331)]
[New Thread 0x7ffffefa0700 (LWP 2332)]

Thread 2 "tflite_min_stat" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffff7b0700 (LWP 2331)]
0x0000000000000000 in ?? ()
```

**Bazel Reproduction**
Using the minimal example above, the problem can be reproduced under Bazel by adding the following build rule:
```
cc_binary(
    name = "tflite_minimal_bazel",
    srcs = ["minimal.cc"],
    deps = [
        ":framework",
        "//tensorflow/lite/kernels:builtin_ops_all_linked", # For kernels/register.h
    ],
    features = ["fully_static_link"], # For full static link of standard library
    linkstatic=True,
)
```

**Files for Reproduction**
See [here](https://www.dropbox.com/sh/0ztotvfm5l92aaz/AAAI4-TYwyuddKnb4S2uaKBja?dl=0).

**Comment by jdduke** [comment]
@multiverse-tf can you take a look?

**Comment by multiverse-tf** [comment]
Hi Adam,

Thx for giving detailed instructions to reproduce the issue! While I am going to take a look at this, I'm just wondering is this reproducible w/ the Bazel build toolchain? Considering you're using the tensorflow:devel docker to do the compilation, I think it's quite simple to use Bazel then.

For example, as for the minimal.cc program, you could simply put it under "tensorflow/lite" directory and add a BUILD rule like the following to get it compiled later.
cc_binary(
    name = "tflite_minimal",
    srcs = ["minimal.cc"],
    deps = [
        ":framework",
        # OTHER DEPS...
    ],
    linkstatic=true,
)

Then, "bazel build //tensorflow/lite:tflite_minimal" cmd should get it compiled.

**Comment by Lif3line** [comment]
Hey Chao, thanks for getting back to me. I'm not familiar with Bazel, but compiling with the suggested rule only created a static link for TensorFlow Lite itself and not the standard C/C++ library. This compilation is essentially the same as the dynamic case referenced in the issue. I tried adding `features = ["fully_static_link"]` for a full static build, but this generated compilation errors (largely undefined symbols); I've added this error and the successful compilation to the dropbox link.

It's interesting that `bazel` generates compilation errors while `g++` does not. My guess is the cause is something to do with the weak symbol linking for `pthread`; the standard solution to the symbol problem in `g++`: `-Wl,--whole-archive -lpthread -Wl,--no-whole-archive` (+/- `-lrt -pthread`) doesn't appear to work here.

I had previously been compiling on the image `tensorflow:nightly-devel` referenced in the ARM build guide [here](https://www.tensorflow.org/lite/guide/build_arm64), but it appears to be quite outdated as it pulls `6798656ce64201afe7d8d9ed5445cd5114bfd9b4` which is from 2018 and `v1.12.1` - this may warrant its own issue. Using my original build process on that image (targetting an RPi rather than `x86_64`) allowed for a complete static compilation without the segmentation issue. That might imply that a change in how the threading is handled between then and now is the underlying cause.

Small change for successful bazel compilation (may not be the best/correct way to do the include):
```
cc_binary(
    name = "tflite_minimal_bazel",
    srcs = ["minimal.cc"],
    deps = [
        ":framework",
        "//tensorflow/lite/kernels:builtin_ops_all_linked", # For kernels/register.h
    ],
    # features = ["fully_static_link"], # For static link of standard library
    linkstatic=True,
)
```

**Comment by Lif3line** [comment]
@multiverse-tf did you get a chance to look into this?

**Comment by Lif3line** [comment]
@Saduf2019 it might be relevant to add tags for versions 2.1 & 2.3 as I can confirm this issue is present in those releases. I don't believe I can add those myself.

**Comment by Lif3line** [comment]
Thanks @mihaimaruseac. I just want to confirm that this is still an issue as of the newest `tensorflow/tensorflow:devel`. Any help would be greatly appreciated.

**Comment by Lif3line** [comment]
Bumping since this is still a bug. Any updates @multiverse-tf? I have a CI script replicating the problem and I'm happy to help fix it, but I need some pointers on where to look and what the potential causes might be.

**Comment by Lif3line** [comment]
Is anyone interested in trying to solve this?

@multiverse-tf @advaitjain @mihaimaruseac @jdduke @ymodak @Saduf2019

**Comment by jdduke** [comment]
@Lif3line do you have a more detailed, symbolized stack trace (from a debug build) that we can use for reference?

**Comment by mihaimaruseac** [comment]
Unfortunately I have a very large queue of bugs so I won't be able to look at this before 2.4 release :(

**Comment by Lif3line** [comment]
Fair enough @mihaimaruseac, I appreciate we're all busy, thanks for getting back to me though.

@jdduke, I can get one although I'm afraid I don't know exactly how I'd do that. Presumably add `-g` to the Tensorflow library compilation then running through `gdb` again? Or do you have some expanded debug build via Bazel?

**Comment by jdduke** [comment]
> Presumably add -g to the Tensorflow library compilation then running through gdb again? Or do you have some expanded debug build via Bazel?

Yes, for the makefile build for the tensorflow-lite lib you'll want to include `-g`. Note that we're also working on CMake support, and we should probably also extend the minimal example to also export a CMake-based build variant. @terryheo FYI.

**Comment by Lif3line** [comment]
Unfortunately I don't seem to get anything extra out: 

```
Tensor  75 (null)               kTfLiteNoType  kTfLiteMemNone          0 bytes ( 0.0 MB)  (null)
Tensor  76 (null)               kTfLiteNoType  kTfLiteMemNone          0 bytes ( 0.0 MB)  (n[New Thread 0x7fa70f8a6700 (LWP 361)]
[New Thread 0x7fa70f0a5700 (LWP 362)]
[New Thread 0x7fa70e8a4700 (LWP 363)]
Thread 2 "tflite_minimal" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fa70f8a6700 (LWP 361)]
0x0000000000000000 in ?? ()
```

I rebuilt Tensorflow with the following Make target copied into `/tensorflow_src/tensorflow/lite/tools/make/targets/linux_debug_makefile.inc`:
```MAKEFILE
ifeq ($(TARGET), linux_debug)
    CXXFLAGS += \
        -fPIC \
        -DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK \
        -pthread \
        -g

    CFLAGS += \
        -fPIC \
        -DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK \
        -pthread \
        -g

    LIBS += -ldl

endif
```

Then compiled via `./tensorflow/lite/tools/make/build_lib.sh TARGET=linux_debug`. The rest was the same as the above with `gdb -ex run --args ${DEPLOY_SRC}/tflite_minimal_static/tflite_minimal adv_model.tflite` to see what was happening.

**Comment by jdduke** [comment]
Hi @Lif3line, I've forward this issue internally where we'll try to repro. There have certainly been changes over the past several years with threading that could account for the breakage. Thanks for your patience, I've added this to the hotlist for the next release.

**Comment by Lif3line** [comment]
Great, thanks very much for that. I'll leave the code I used to reproduce available via [the link above](https://www.dropbox.com/sh/0ztotvfm5l92aaz/AAAI4-TYwyuddKnb4S2uaKBja?dl=0], let me know if there's anything else useful I can do to help.

**Comment by Lif3line** [comment]
Just want to bump because this still exists in `2.4.1`. Same symptoms, still reproducible with the above.

**Comment by multiverse-tf** [comment]
Hi @Lif3line,

Sorry for not looking into this for such a long time.

I tried to reproduce the issue by following the "Bazel Reproduction" part using the tensorflow/tensorflow:devel docker image, but ended up w/ static linking errors as shown below :(
"
...
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
external/flatbuffers/src/util.cpp:50: error: undefined reference to 'std::basic_ifstream<char, std::char_traits<char> >::basic_ifstream(char const*, std::_Ios_Openmode)'
external/flatbuffers/src/util.cpp:51: error: undefined reference to 'std::basic_ios<char, std::char_traits<char> >::good() const'
external/flatbuffers/src/util.cpp:50: error: undefined reference to 'std::basic_ifstream<char, std::char_traits<char> >::~basic_ifstream()'
external/flatbuffers/src/util.cpp:50: error: undefined reference to 'std::basic_ifstream<char, std::char_traits<char> >::~basic_ifstream()'
external/flatbuffers/src/util.cpp:56: error: undefined reference to 'std::basic_ifstream<char, std::char_traits<char> >::basic_ifstream(char const*, std::_Ios_Openmode)'
external/flatbuffers/src/util.cpp:57: error: undefined reference to 'std::basic_ifstream<char, std::char_traits<char> >::is_open()'
external/flatbuffers/src/util.cpp:60: error: undefined reference to 'std::istream::seekg(long, std::_Ios_Seekdir)'
external/flatbuffers/src/util.cpp:61: error: undefined reference to 'std::istream::tellg()'
...
"

Just wondering does this happen to you? My docker image has the id as "sha256:e6925c167c691d50a61fdf06f3495ccdd6612c8b3da29659e121da7e723459e3" which was created on 2020-12-30 according to "docker inspect <IMAGE ID>". Just wondering whether the docker image could play a role here or not.

**Comment by Lif3line** [comment]
No worries, I had issues (although not exactly the same error) when using `features = ["fully_static_link"]`, but I don't know enough about Bazel to debug. The fact that a full static build doesn't compile could well be the underlying issue though. 

The particular bug you posted looks like the include for `<fstream>` is missing or not linked properly somewhere in the `flatbuffers` library, but I know even less about that.

I have this issue running in a GitLab instance, if you have access to your own with CI time I could edit down a minimal example and share it? It directly uses the build script `/tensorflow/lite/tools/make/build_lib.sh` to build Tensorflow non-statically in the first instance then a CMAKE version of the above `g++` to create a static version of the minimal example.

**Comment by Lif3line** [comment]
Just want to bump because this still exists in 2.5 (Can someone tag for 2.4 and 2.5?). Same symptoms, still reproducible with the above.

For building with `bazel` I'd guess this is issue is tied with `fully_static_link` not working at build time. That error can be replicated using the above example and adding the following at the bottom of the `bazel` script.
```
cc_binary(
    name = "tflite_minimal_bazel",
    srcs = ["minimal.cc"],
    deps = [
        ":framework",
        "//tensorflow/lite/kernels:builtin_ops_all_linked", # For kernels/register.h
    ],
    features = ["fully_static_link"], # For static link of standard library
    linkstatic=True,
)
```

**Comment by sushreebarsa** [comment]
@Lif3line Could you please try using latest TF v2.7.0 and let us know if it helps?Thanks!

**Comment by Lif3line** [comment]
Looks fixed as of most recent `tensorflow/tensorflow:devel` image! Thanks for checking in^^

Minimal example [here](https://gitlab.com/Lif3line/tensorflow_static_build_test).
