### ISSUE TITLE
How to check whether MKL is supported or not  with the installed tensorflow

### ISSUE THREAD

**Issue by manidevi** [tensorflow/tensorflow#42054]
**System information**
- OS Platform and Distribution : Windows 10
- TensorFlow installed from : binary
- TensorFlow version: 2.1.0
- Python version: 3.7.0
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

I installed tensorflow with mkl support following [this guide](https://software.intel.com/content/www/us/en/develop/articles/intel-optimization-for-tensorflow-installation-guide.html). Now I want to check whether mkl is properly installed or not. I tried the following as suggested by Intel, but encountered no matching attribute error.
>>>import tensorflow
>>> print(tensorflow.pywrap_tensorflow.IsMklEnabled())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'pywrap_tensorflow'

Is there any other way to do the same?

I installed tensorflow with the following cmd:
` pip install tensorflow-mkl`

**Comment by bhack** [comment]
Can you try with:
`python -c 'from tensorflow.python import _pywrap_util_port; print(_pywrap_util_port.IsMklEnabled())'`

**Comment by manidevi** [comment]
It works! Thanks @bhack
