### ISSUE TITLE
All validation loss reported as 0.0000e+00 in keras / TF

### ISSUE THREAD

**Issue by becker929** [tensorflow/tensorflow#42053]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
This is running on Google Colab. I am running macOS 10.15.6. Colab is opened in Chrome 84.0.4147.105 .
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
Not installed by me as it is running in Colab. 
- TensorFlow version (use command below):
v2.3.0-0-gb36436b087 2.3.0
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: N/A although this also happens when using Tesla P100 on Colab

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

During training, val_loss is reported as 0.0000e+00.
When printing model.history.history['val_loss'], an array of [0.0,..., 0.0] is printed.
However, when evaluating the model on examples val_x, val_y, a non-zero loss is reported.
This happens for at least 4 different notebooks, including notebooks that worked properly earlier today.

**Describe the expected behavior**

During training, a non-zero validation loss should be reported in most cases.
These non-zero losses should be reported in the model history.
When evaluating the model against the validation examples val_x, val_y, a loss similar to that reported in the model history should be reported.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

https://colab.research.google.com/drive/1YP_dR7O9KsqSeLyrgFTzOSna0EggL9Gs?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2,2.3 and was able to reproduce the issue.Please, find the gist [here.](https://colab.research.google.com/gist/ravikyram/0dc65503474d05f733976aff98c25a48/untitled217.ipynb).
However i am seeing the below error message with [TF nightly version](https://colab.research.google.com/gist/ravikyram/9f41ca81a451c2a069f219d200eb729a/untitled218.ipynb)(`2.4.0-dev20200804`).
`ValueError: Layer functional_1 expects 1 input(s), but it received 2 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(10, 1, 10) dtype=float32>, <tf.Tensor 'IteratorGetNext:1' shape=(10, 1, 1) dtype=float32>]`
Thanks!

**Comment by jvishnuvardhan** [comment]
@becker929 Thanks for creating this issue. 
Root-cause of this issue is that the `validation_data` was provided as a list where as  `validation_data` needs to be a tuple. Please check the argument of `modell.fit`[here](https://www.tensorflow.org/api_docs/python/tf/keras/Model).

> tuple (x_val, y_val) of Numpy arrays or tensors
> tuple (x_val, y_val, val_sample_weights) of Numpy arrays

I updated `validation_data` argument within the `model.fit` from `validation_data=[val_x, val_y]` to `validation_data=(val_x, val_y)` . There was no error after this modification. 

Please check the gist [here](https://colab.research.google.com/gist/jvishnuvardhan/d551d006d57ce271e8c3d396b2d7f439/untitled218.ipynb).

Please verify once and close the issue if this resolved your issue. Thanks!

**Comment by becker929** [comment]
Hi, thanks! Indeed, after trying this with some other train/val data, this does solve the problem. I did not have to install the nightly build to solve the problem. I updated the notebook in the issue description demonstrating the change. Thanks again.

**Comment by brethvoice** [comment]
FYI, completely not the same reason, but I got the exact same problem when I failed to specify a loss function (in tensorflow 2.3.0) during the call to .compile() on the model.

**Comment by jvishnuvardhan** [comment]
@brethvoice Please open a new issue with a simple standalone code to reproduce the issue. thanks!

**Comment by brethvoice** [comment]
> @brethvoice Please open a new issue with a simple standalone code to reproduce the issue. thanks!

Actually it was my failure to read the API that caused the issue.  This is not something Tensorflow can or should "fix."

**Comment by ArpithaFAU** [comment]
Hello I am also having a similar issue. The validation loss is always 0 even though i use keras and not tf.keras. But i have values for validation accuracy.
I am using tf-version 2.1.0 and keras 2.3.1.
Can anyone help me with this?

**Comment by brethvoice** [comment]
> Hello I am also having a similar issue. The validation loss is always 0 even though i use keras and not tf.keras. But i have values for validation accuracy.
> I am using tf-version 2.1.0 and keras 2.3.1.
> Can anyone help me with this?

Check your .compile() call and make sure you have a loss function specified there.

**Comment by ArpithaFAU** [comment]
> > Hello I am also having a similar issue. The validation loss is always 0 even though i use keras and not tf.keras. But i have values for validation accuracy.
> > I am using tf-version 2.1.0 and keras 2.3.1.
> > Can anyone help me with this?
> 
> Check your .compile() call and make sure you have a loss function specified there.

I have a loss function specified but still i have the issue.

**Comment by brethvoice** [comment]
> > > Hello I am also having a similar issue. The validation loss is always 0 even though i use keras and not tf.keras. But i have values for validation accuracy.
> > > I am using tf-version 2.1.0 and keras 2.3.1.
> > > Can anyone help me with this?
> > 
> > 
> > Check your .compile() call and make sure you have a loss function specified there.
> 
> I have a loss function specified but still i have the issue.

@ArpithaFAU another thing I would check is that your validation data are being presented in a tuple (x, y).  If they are not then the validation calculation will not be possible.

**Comment by ArpithaFAU** [comment]
> > > > Hello I am also having a similar issue. The validation loss is always 0 even though i use keras and not tf.keras. But i have values for validation accuracy.
> > > > I am using tf-version 2.1.0 and keras 2.3.1.
> > > > Can anyone help me with this?
> > > 
> > > 
> > > Check your .compile() call and make sure you have a loss function specified there.
> > 
> > 
> > I have a loss function specified but still i have the issue.
> 
> @ArpithaFAU another thing I would check is that your validation data are being presented in a tuple (x, y). If they are not then the validation calculation will not be possible.

@brethvoice i have done that as well but i still have the same issue. If you are aware of any other solution pls let me know.

**Comment by nirav0999** [comment]
I  am facing the same issue.
WIth tf.keras I used validation_data as a  tuple to get
 /lib/python3.7/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 630, in_is_list_of_scalars
 return ListsOfScalarsDataAdapter._is_list_of_scalars(inp[0])
IndexError: list index out of range

With keras and on using validation data as a tuple I get the same error

With keras and on using validation data as a list I get the 0 validation loss.

Would greatly appreciate any help.

**Comment by ArpithaFAU** [comment]
What i tried is upgrading to tensorflow and keras to the latest version and
that fixed my problem.

**Comment by CJSeqtek** [comment]
I get a similar error, I have the latest version. Any help with this?

**Comment by njoppi2** [comment]
Try changing the loss in your model.fit from `loss="categorical_crossentropy"` to `loss="binary_crossentropy"`

I Had the SAME problem, but this worked for me. The thing is that I have a binary classification model, with only 1 output node, not a multi-classification model with multiple output node, so `loss="binary_crossentropy"` is the appropriate loss function in this case.

😊
