### ISSUE TITLE
android use XNNPACK happen error

### ISSUE THREAD

**Issue by yeyupiaoling** [tensorflow/tensorflow#42056]
- android 7
 - ssd_mobilenet_v2

```
    implementation 'org.tensorflow:tensorflow-lite:2.3.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.3.0'
    implementation 'org.tensorflow:tensorflow-lite-support:0.1.0-rc1'
```

```java
Interpreter.Options options = new Interpreter.Options();
options.setUseXNNPACK(true);
options.setNumThreads(NUM_THREADS);
NnApiDelegate delegate = new NnApiDelegate();
options.addDelegate(delegate);
tflite = new Interpreter(file, options);
```

error log:
```
Failed to apply XNNPACK delegate: ModifyGraphWithDelegate is disallowed when graph is immutable.
```

**Comment by ymodak** [comment]
@yeyupiaoling Can you please attach the full stacktrace? Thanks!

**Comment by yeyupiaoling** [comment]
@ymodak hi，this is log：

![image](https://user-images.githubusercontent.com/26297768/89478269-1a1da880-d7c2-11ea-9604-09db1854d22e.png)

**Comment by yeyupiaoling** [comment]
If I close NNAPI, XNNPACK works fine

**Comment by srjoglekar246** [comment]
@yeyupiaoling Is it working for you now? We fixed it on our end, should be there in the nightly builds.

**Comment by yeyupiaoling** [comment]
@srjoglekar246 Which version is it ?

```
    implementation 'org.tensorflow:tensorflow-lite:2.3.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.3.0'
    implementation 'org.tensorflow:tensorflow-lite-support:0.1.0-rc1'
```

**Comment by srjoglekar246** [comment]
You would probably need to use the 2.4 nightly. The fix landed after 2.3

**Comment by ravikyram** [comment]
@yeyupiaoling 

Can you please try in TF nightly version and see if the issue still persists. Thanks!

**Comment by yeyupiaoling** [comment]
@srjoglekar246 @ravikyram There is no version of this. 
url: https://bintray.com/google/tensorflow/tensorflow-lite
![image](https://user-images.githubusercontent.com/26297768/93564480-5563e780-f9bc-11ea-88db-04df48210135.png)
