### ISSUE TITLE
[Docs] RAM usage when building from source

### ISSUE THREAD

**Issue by Smankusors** [tensorflow/tensorflow#42066]
## URL(s) with the issue:
https://www.tensorflow.org/install/source

## Description of issue (what needs changing):
Aproximately the RAM that used when compiling. IMO, "Building TensorFlow from source can use **a lot of** RAM", is not clear how "a lot of" is how many GB. I have VM with 6vCPU 10GB RAM and I frequently run out of memory. This run out of memory is not only slowing down the compiling, but also make system freeze/unresponsive, Every this happens, I need to increase the RAM by 500MB to unlock the system.

### Clear description
Why we need this? Because we don't want to sleep with the machine compiling overnight. And when we wakes up, it turns out the compiling failed, or the machine frozen, and it's really waste of time. This "aproximately RAM usage" should help anticipate this though.

### How about `--local_ram_resources`?
Well, I already tried with this flag `--local_ram_resources=HOST_RAM*.2` as described from [here](https://docs.bazel.build/versions/master/user-manual.html#flag--local_{ram,cpu}_resources). Is this mean the building process will only take 20% RAM? Is this global or for every thread? Is this flag supported on the `v2.3.0` tag on this repo? I watched `htop` and seen many tasks at once using more than 20%. I run out of memory again even with this, this is ridiculous. 😭 

### Submit a pull request?
To this [repo](https://github.com/tensorflow/docs)? Yes if I can get how aproximately the RAM usage... I think it's max around 3GB per CPU core? Correct me if I'm wrong.

### Other information
Well it seems I got a lot of RAM, but I running out of memory. The VM is live CD (not installed), and also the swap.... yeah it's zram (5GB) instead of swapfile. Because... uh..., I don't want to kill the SSD :(

### Related issue
#30047

**Comment by bhack** [comment]
https://community.arm.com/developer/ip-products/processors/b/ml-ip-blog/posts/building-bazel-and-tensorflow-2-x-on-aarch64
> Using --local_ram_resources=1600 won't limit gcc or clang building individual kernels and can cause an unrecoverable compiler crash on machines with less than 4GB 

/cc @gunan

**Comment by gunan** [comment]
@bhack, I think that is a common issue for all build frameworks, no?
If there is a compiler flag, you can always set the flag to limit compiler memory usage with `--copt`
How does cmake/make handle this?

**Comment by bhack** [comment]
@gunan Other than globally reducing jobs (or going ahead to explore --copt for finentuing compiler settings) I think that there could be some "clustering tricks" if you have some domain information. E.g. see Blender with Ninja https://developer.blender.org/D4780?id=

**Comment by bhack** [comment]
@gunan Do you know some internals of the Bazel (very crude) estimates heuristic on the single job?

https://docs.bazel.build/versions/master/user-manual.html#flag--jobs

> Note that the number of concurrent jobs that Bazel will run is determined not only by the --jobs setting, but also by Bazel's scheduler, which tries to avoid running concurrent jobs that will use up more resources (RAM or CPU) than are available, based on some (very crude) estimates of the resource consumption of each job. The behavior of the scheduler can be controlled by the --local_ram_resources option.

**Comment by Smankusors** [comment]
Eh alternatively, I could futher reduce the RAM usage by using `--local_cpu_resources` instead of `--local_ram_resources`. I think this should be mentioned on the install documentation?

**Comment by bhack** [comment]
@Smankusors I don't know if in your case there is a specific error on this API call cause you are inside the virtual machine. If you see this line of code the exception don't print any warning:
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/actions/ResourceManager.java#L392

**Comment by bhack** [comment]
@Smankusors Can you test with `--experimental_local_memory_estimate`?

**Comment by gunan** [comment]
I do not know about the internal bazel heuristics, but bazel by default sets the value of jobs to value of CPU.
I have seen (similarly with cmake) that for smaller systems this is still too much, so you have to further limit, by doing --jobs=1 or 2

**Comment by summa-code** [comment]
I have 64 GB, i never run out of Memory, it hovers around 14 to 15 GB when building. If you have 10GB, that may be low, because bazel server alone takes about 10G and check your Swap as well.

**Comment by Smankusors** [comment]
> @Smankusors Can you test with `--experimental_local_memory_estimate`?

Hmm... I will try this later

> I have 64 GB, i never run out of Memory, it hovers around 14 to 15 GB when building. If you have 10GB, that may be low, because bazel server alone takes about 10G and check your Swap as well.

Interesting, how many CPU cores do you have? I see mine around 2-3 GB used by Bazel server

**Comment by summa-code** [comment]
@Smankusors 24 threads

**Comment by ryandesign** [comment]
The MacPorts project has been suffering from this problem for a long time: https://trac.macports.org/ticket/58932

> bazel server alone takes about 10G.

That would be an absolutely batshit crazy requirement.

**Comment by bhack** [comment]
Have you explored all the solutions in https://docs.bazel.build/versions/master/memory-saving-mode.html?

**Comment by ryandesign** [comment]
I'll suggest that to our maintainer of tensorflow. However it is not, as that page says, that we "may want Bazel to use minimal memory". I would be delighted for Bazel to use all of the available memory, but currently it uses much more than the available memory, and I am guessing that the swapping that this incurs is what is slowing down our builds. Don't you think that using almost all of the available memory, but not more than that, would be a good default behavior for the build system to have?

**Comment by bhack** [comment]
In that case we are more in bazel domain and It is repo than in TF. 
You need to check also Bazel scheduler performance for the parallel build. See https://docs.bazel.build/versions/master/user-manual.html#flag--jobs

**Comment by bhack** [comment]
See also https://jmmv.dev/2019/12/bazel-local-resources.html for extra details.

**Comment by ryandesign** [comment]
I know how `--jobs` works and I read the other document before I found this bug report. Nobody wants to set twelve flags to unknown magic values to get the build system to do what it should do by default.

**Comment by bhack** [comment]
> I know how `--jobs` works and I read the other document before I found this bug report. Nobody wants to set twelve flags to unknown magic values to get the build system to do what it should do by default.

It could be ok but I don't think we could solve this here. Probably you need to open a bazel ISSUE or comment on an exsisting one in its repo if you want to improve bazel herustics.

**Comment by mohantym** [comment]
Hi @Smankusors ! I do see the documentation on the --local_ram_resources flag in [linux section ](https://www.tensorflow.org/install/source#bazel_build_options)now. I think resource usage must be lesser if you check out a specific branch (like r2.8 or 2.7) after cloning Tensorflow Repo.  

`bazel build    --local_ram_resources=2048 //tensorflow/tools/pip_package:build_pip_package   # will use 2GB RAM `

Could you create a fresh issue with device specification and other details for testing. Thank you!

**Comment by Smankusors** [comment]
@mohantym uh oh... unfortunately this has been a very long time... I'm no longer have the resources to do this anymore 😅 

And because of that I'm not sure if this issue still relevant? Welp it's up to you then to close this or not.

**Comment by mohantym** [comment]
@boegel! You can refer to this [document](https://www.tensorflow.org/lite/microcontrollers) (lite models fit for low memory usage) if you are trying to install Tensorflow in microcontrollers . Thank you!

**Comment by mohantym** [comment]
@Smankusors!  
Thanks for the update. Moving this issue to closed status for now. Please create a new issue if you need further assistance . Thank you!
