### ISSUE TITLE
tf.keras.utils.plot_model doesn't work

### ISSUE THREAD

**Issue by pochtar** [tensorflow/tensorflow#42068]
**System information**
Google colab.

**Steps to reproduce:**
1. Click "Run all" at Colab of https://www.tensorflow.org/tutorials/structured_data/feature_columns
2. Add a cell with the following code:
```tf.keras.utils.plot_model(model, show_shapes=True, show_layer_names=True)```

**Describe the current behavior**
1. It displays only 1 block `[sequential]`.
2. If you copy all cells + plot_model and run locally in a separate py script (not Colab), you'll also get a lot of warnings that features v2 are deprecated and will be removed in next releases (tf 2.2).

**Describe the expected behavior**
1. The model would be displayed.
2. No deprecation warning would be displayed.

**Standalone code to reproduce the issue**
https://www.tensorflow.org/tutorials/structured_data/feature_columns

**Comment by bhack** [comment]
Probably you need to consider https://github.com/tensorflow/tensorflow/issues/27416#issuecomment-565255351. 
I don't know if the tutorial could be updated.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3, nightly version(`2.4.0-dev20200805`) and it displays only `1 block [sequential] `when we execute `tf.keras.utils.plot_model(model, show_shapes=True, show_layer_names=True)`.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/ad694d97ade05d0fb7590e23f5ad0a7e/untitled223.ipynb).Thanks!

**Comment by jvishnuvardhan** [comment]
@pochtar I think this is due to shape inference. For Sequential API, we need to provide `input_shape` so that it will infer shape of the other layers. When I executed, `model.summary` it shows `multiple` as `output_shape`. 

Looking at the [link](https://github.com/tensorflow/tensorflow/issues/27416#issuecomment-565255351) provided by @bhack , 

> The interaction between feature columns and Keras is painful. To address this issue, we have proposed Keras preprocessing layers.

```
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
dense_features_6 (DenseFeatu multiple                  1328      
_________________________________________________________________
dense (Dense)                multiple                  19328     
_________________________________________________________________
dense_1 (Dense)              multiple                  16512     
_________________________________________________________________
dropout (Dropout)            multiple                  0         
_________________________________________________________________
dense_2 (Dense)              multiple                  129       
=================================================================
Total params: 37,297
Trainable params: 37,297
Non-trainable params: 0
_________________________________________________________________
```

**Comment by nikitamaia** [comment]
@pochtar, have you seen the [Classify structured data using Keras Preprocessing Layers tutorial](https://www.tensorflow.org/tutorials/structured_data/preprocessing_layers)? This is the same PetFinder dataset example and shows the results of `tf.keras.utils.plot_model`.
