### ISSUE TITLE
Hello World example project's generated binary is empty for Bluepill

### ISSUE THREAD

**Issue by djzenma** [tensorflow/tensorflow#42075]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOs Catalina version 10.15.3
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): 89851a6a7725d92735e9817ee6a1f551dd7492ab
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Bluepill

**Describe the problem**
When I build the Hello World Tensorflow Lite example project for the blue pill microcontroller, the resulting binary is empty. This is demonstrated when I objdump the resulting ELF file:

```
bluepill_cortex-m3/bin/hello_world:     file format elf32-littlearm




Disassembly of section ._user_heap_stack:


20000000 <._user_heap_stack>:
    ...

```

**Please provide the exact sequence of commands/steps when you ran into the problem**
Build the Hello World binary by specifying the bluepill as target:
```
gmake -f tensorflow/lite/micro/tools/make/Makefile TARGET=bluepill hello_world_bin
```
Then see the objdump of the ELF:
```
tensorflow/tensorflow/lite/micro/tools/make/downloads/gcc_embedded/arm-none-eabi/bin/objdump tensorflow/tensorflow/lite/micro/tools/make/gen/bluepill_cortex-m3/bin/hello_world -D
```

**Comment by mohantym** [comment]
Hi @djzenma ! Could you post this on [tflite-micro](https://github.com/tensorflow/tflite-micro/issues) repo . Thank you!
