### ISSUE TITLE
Feature request: Ogg (or equivalent) compression for AudioSummary with TensorBoard

### ISSUE THREAD

**Issue by carlthome** [tensorflow/tensorflow#4207]
When logging an AudioSummary every couple of epochs, the logs grow quickly (as in several gigabytes), and checking TensorBoard remotely (as in not on the same LAN) also becomes very slow. Would it be possible to have builtin support for Ogg compression or an equivalent lossy format? There are multiple use cases where this would be beneficial.

**Comment by carlthome** [comment]
Or in TensorBoard at least, maybe just download an audio file upon hitting play (or just the most recent AudioSummary per default), instead of loading everything?

**Comment by rryan** [comment]
This is certainly an issue -- for those hitting it here are some workarounds until we get some better codecs in TensorFlow:

- Use ```tf.summary.audio```'s ```max_outputs``` argument to limit the number of WAVs you're writing to your events file per summary run.
- If using ```tf.Supervisor```, increase your ```save_summaries_secs``` to write summaries less frequently.

**Comment by rryan** [comment]
IMHO a lossless codec like FLAC would greatly improve the situation without degrading the quality of the synthesized audio.

**Comment by wchargin** [comment]
This is certainly a reasonable suggestion. I've migrated it to our new repository at https://github.com/tensorflow/tensorboard/issues/64. Please feel free to submit PRs there, too!
