### ISSUE TITLE
[TFLite] Error: TfLiteGpuDelegate Init: MUL: 1024x131  cannot be reduced to linear.

### ISSUE THREAD

**Issue by cathy-kim** [tensorflow/tensorflow#42085]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 10.0 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Pixel3 
- TensorFlow installed from (source or binary): binary 
- TensorFlow version (use command below): org.tensorflow:tensorflow-lite-gpu:2.2.0 / 0.0.0-nightly 
- Python version: 3.6 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: X
- GPU model and memory:  Adreno 630

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Hi. I'm trying to serve our model on Pixel3(Android 10), using TFLite's GPU backend. 
But, this error makes our app crash. (Both of tensorflow-lite-gpu:2.2.0 and 0.0.0-nightly)
```
  Process: org.tensorflow.lite.examples.posenet, PID: 30052
    java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Next operations are not supported by GPU delegate:
    SUM: Operation is not supported.
    First 141 operations will run on the GPU, and the remaining 7 on the CPU.
    TfLiteGpuDelegate Init: MUL: 1024x131  cannot be reduced to linear.
    TfLiteGpuDelegate Prepare: delegate is not initialized
    Node number 148 (TfLiteGpuDelegateV2) failed to prepare.
```
The error is "TfLiteGpuDelegate Init: MUL: 1024x131  cannot be reduced to linear." 
What is the matter and what can I do to utilize TfLiteGPUDelegate?    

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by zldrobit** [comment]
Hello @cathy-kim , have you solved the problem?

**Comment by cathy-kim** [comment]
@zldrobit Actually, No. 
I just replace 'MUL'(in TFLite, that operation is the same as 'FullyConnected') to another operation.

**Comment by zldrobit** [comment]
@cathy-kim thanks for your confirming.
I see now, and I decide to reconstruct my network.

**Comment by Saduf2019** [comment]
@cathy-kim 
Is this still an issue.

**Comment by zldrobit** [comment]
I found a relevant issue where someone seemed to solve the problem.
https://github.com/tensorflow/tensorflow/issues/37102
