### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by SRJaffry** [tensorflow/tensorflow#42087]
I am getting the following error when trying to import tensorflow. I have tried many solutions and non seem to work.

I have seen Issue #22794, but it does not seem to help.

Versions -- > python 3.7.4 -- > tensorflow 2.3.0

> 
> runfile('C:/Users/pshad/.spyder-py3/temp.py', wdir='C:/Users/pshad/.spyder-py3')
> Traceback (most recent call last):
> 
>   File "<ipython-input-30-bc8fb4f78acd>", line 1, in <module>
>     runfile('C:/Users/pshad/.spyder-py3/temp.py', wdir='C:/Users/pshad/.spyder-py3')
> 
>   File "C:\Users\pshad\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Users\pshad\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "C:/Users/pshad/.spyder-py3/temp.py", line 9, in <module>
>     import tensorflow as tf
> 
>   File "C:\Users\pshad\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
>     from tensorflow.python.tools import module_util as _module_util
> 
>   File "C:\Users\pshad\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
>     from tensorflow.python.eager import context
> 
>   File "C:\Users\pshad\Anaconda3\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
>     from tensorflow.python import pywrap_tfe
> 
>   File "C:\Users\pshad\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
>     from tensorflow.python import pywrap_tensorflow
> 
>   File "C:\Users\pshad\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
>     raise ImportError(msg)
> 
> ImportError: Traceback (most recent call last):
>   File "C:\Users\pshad\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
>     from tensorflow.python._pywrap_tensorflow_internal import *
> ImportError: DLL load failed: The specified module could not be found.
> 
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/errors

I tried to reinstall the tensorflow, downgrade,  and upgrade as well. Nothing seem to work, unfortunately.

**Comment by ravikyram** [comment]
@SRJaffry 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See[ hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here.](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
.Also, please follow the instructions from to install from [Tensorflow website.](https://www.tensorflow.org/install/source_windows)

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.Please, refer similar issue #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
Thanks!

**Comment by SRJaffry** [comment]
Thanks, I installed the latest distribution of Visual C++ from the link your shared and the problem seem to solve. Thank you.
