### ISSUE TITLE
Wrong JPEG library version: library is 90, caller expects 80

### ISSUE THREAD

**Issue by jeshxxx** [tensorflow/tensorflow#42083]
I got this error when i call tf.image.decode_jpeg in my program which linked a libjpeg of version 90.
Tensorflow : 1.14
Opencv : 3.1.0

**Comment by amahendrakar** [comment]
@jeshxxx,
TensorFlow v1.14 is not actively supported. Please upgrade to TensorFlow 2.x or v1.15. 

In order to expedite the trouble-shooting process, please provide the complete code, the dataset you are using and the complete error log. Thanks!

**Comment by amahendrakar** [comment]
I was able to use `tf.image.decode_jpeg` without any issues with TF v1.15. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/e82b0db953601c538b6a25f82131b81d/42083.ipynb).

Also, take a look at [this thread](https://forum.qt.io/topic/52899/solved-wrong-jpeg-library-version-library-is-90-caller-expects-80) from a similar issue and let us know if it helps. Thanks!

**Comment by jeshxxx** [comment]
`TEST(ScalarPreprocessor, SavedModelWithImageInputTest) {
  tensorflow::GraphDef graph_def_;
  tensorflow::SessionOptions opts_;
  tensorflow::Session* session_;
  tensorflow::SavedModelBundle saved_bundle_;
  tensorflow::RunOptions run_options;
  std::string path = "./saved_model/";
  std::unordered_set<std::string> saved_model_tags;
  saved_model_tags.insert("serve");
  tensorflow::Status s = LoadSavedModel(opts_, run_options, path, saved_model_tags, &saved_bundle_);
  graph_def_ = saved_bundle_.meta_graph_def.graph_def();
  session_ = saved_bundle_.session.release();
  std::vector<std::pair<std::string, tensorflow::Tensor>> tf_inputs_;

  std::ifstream t;
  int length;
  t.open("test.jpg", std::ifstream::binary);
  t.seekg(0, std::ios::end);
  length = t.tellg();
  t.seekg(0, std::ios::beg);
  char *buffer = new char[length];
  t.read(buffer, length);
  t.close();
  tensorflow::TensorProto proto;
  proto.set_dtype(tensorflow::DataType::DT_STRING);
  proto.mutable_tensor_shape()->add_dim()->set_size(1);
  proto.add_string_val(buffer, length);
  tensorflow::TensorShape shape;
  tf_inputs_.push_back(std::make_pair("ParseExample/ParseExample:0",
                                      tensorflow::Tensor(tensorflow::DataType::DT_STRING, shape)));
  bool converted = tf_inputs_.back().second.FromProto(proto);
  ASSERT_TRUE(converted);
  std::vector<tensorflow::Tensor> tf_outputs_;
  std::vector<std::string> output_tensor_names;
  output_tensor_names.push_back("ArgMax:0");
  tensorflow::Status status = session_->Run(
      tf_inputs_, output_tensor_names, {}, &tf_outputs_);
  std::cout << status.ToString() << std::endl;
}`
It works with libjpeg version 80. But I need link OpenCV-3.1.0 which depends on libjpeg version 90.

**Comment by jeshxxx** [comment]
When link with libjpeg version 90, it returns status like: Invalid argument: 2 root error(s) found.
  (0) Invalid argument: Invalid JPEG data or crop window, data size 19075
	 [[{{node map/while/DecodeJpeg}}]]
  (1) Invalid argument: Invalid JPEG data or crop window, data size 19075
	 [[{{node map/while/DecodeJpeg}}]]
	 [[map/while/DecodeJpeg/_43]]
0 successful operations.
0 derived errors ignored.

**Comment by amahendrakar** [comment]
@jeshxxx,
Could you please check if you are facing the same issue with TF v1.15 or TF v2.3? Thanks!

**Comment by jeshxxx** [comment]
Sorry, my mistake. I mean running a tensorflow::GraphDef with DecodeJpeg op. My model is the same as https://github.com/tensorflow/serving/blob/r1.7/tensorflow_serving/example/inception_saved_model.py. And i load it using LoadSavedModel function in my cpp program which linked opencv-3.1.0.

**Comment by gowthamkpr** [comment]
@jeshxxx We are not clear what you are trying to explain. Can you give us a detailed explanation on what you are trying to accomplish here. Thanks!
