### ISSUE TITLE
Problem with tf.train.FloatList Precision

### ISSUE THREAD

**Issue by kaka-lin** [tensorflow/tensorflow#42088]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.3.0
- Python version: 3.6.10
- CUDA/cuDNN version: 10.2

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I want to convert my Pascal VOC to TFRecords.
But my bounding box values are not the same.
For example:
my xmin is:  [0.620390625]
but the value I get from example is: [0.6203906536102295]

```python
import tensorflow as tf

xmin = [0.620390625]
feature_dict = {
    'xmin':
        tf.train.Feature(float_list=tf.train.FloatList(value=xmin)),
}
example = tf.train.Example(features=tf.train.Features(feature=feature_dict))

print(xmin) # [0.620390625]
print(example.features.feature['xmin'].float_list.value) # [0.6203906536102295]
```
And I also try other values, only the value `2.7182817459106445` show in [TFRecord tutorials](https://www.tensorflow.org/tutorials/load_data/tfrecord) would be the same, as below:

![Screenshot from 2020-08-06 16-57-53](https://user-images.githubusercontent.com/20853096/89513954-ce8ded80-d807-11ea-8c2a-d8ba7a19424a.png)

**Describe the expected behavior**

value should be the same

**Standalone code to reproduce the issue**
Colab link: https://colab.research.google.com/drive/1X_PnjlxA948OpgXaN2laNzdVRQ-1wuHl

**Comment by Saduf2019** [comment]
I am able to replicate the issue, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/7b67b35ac33d672c9415f843453278a1/untitled329.ipynb)

**Comment by bhack** [comment]
@Saduf2019 I don't think it is a bug. @kaka-lin Check https://github.com/tensorflow/tensorflow/issues/12876#issuecomment-328295387

**Comment by Saduf2019** [comment]
@kaka-lin
Can you please update as per above comment.

**Comment by kaka-lin** [comment]
@Saduf2019 
OK! I would try it.

**Comment by kaka-lin** [comment]
Because my case is want to confirm `raw_input` is equal `value get from tfrecord` or not
My workaround is I will storing the data as strings and casting them back.

@bhack  Thanks !
