### ISSUE TITLE
ValueError: slice index 0 of dimension 0 out of bounds. for 'strided_slice' (op: 'StridedSlice') with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <0>, input[2] = <1>, input[3] = <1>.

### ISSUE THREAD

**Issue by shepan6** [tensorflow/tensorflow#42091]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: Code provided by TensorFlow themselves. Tutorial link: https://www.tensorflow.org/tutorials/structured_data/feature_columns 

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Catalina v10.15.4
-   **TensorFlow installed from (source or binary)**: source
-   **TensorFlow version (use command below)**: 2.0.0
-   **Python version**: 3.7.7

### Describe the problem
Bug with Tensorflow code, which I have executed in a Anaconda Environment on Jupyter Notebooks. I have tried running the notebook provided by Tensorflow themselves (link specified above) and was confronted with the following traceback:

`Epoch 1/10
231/231 [==============================] - 4s 19ms/step - loss: 0.6898 - accuracy: 0.6893
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py in _create_c_op(graph, node_def, inputs, control_inputs)
   1609   try:
-> 1610     c_op = c_api.TF_FinishOperation(op_desc)
   1611   except errors.InvalidArgumentError as e:

InvalidArgumentError: slice index 0 of dimension 0 out of bounds. for 'strided_slice' (op: 'StridedSlice') with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <0>, input[2] = <1>, input[3] = <1>.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-39-9b1057f115c9> in <module>
     13 model.fit(train_ds,
     14           validation_data=val_ds,
---> 15           epochs=10)

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    726         max_queue_size=max_queue_size,
    727         workers=workers,
--> 728         use_multiprocessing=use_multiprocessing)
    729 
    730   def evaluate(self,

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, **kwargs)
    368                       mode=ModeKeys.TEST,
    369                       training_context=eval_context,
--> 370                       total_epochs=1)
    371                   cbks.make_logs(model, epoch_logs, eval_result, ModeKeys.TEST,
    372                                  prefix='val_')

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py in run_one_epoch(model, iterator, execution_function, dataset_size, batch_size, strategy, steps_per_epoch, num_samples, mode, training_context, total_epochs)
    121         step=step, mode=mode, size=current_batch_size) as batch_logs:
    122       try:
--> 123         batch_outs = execution_function(iterator)
    124       except (StopIteration, errors.OutOfRangeError):
    125         # TODO(kaftan): File bug about tf function and errors.OutOfRangeError?

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py in execution_function(input_fn)
     84     # `numpy` translates Tensors to values in Eager mode.
     85     return nest.map_structure(_non_none_constant_value,
---> 86                               distributed_function(input_fn))
     87 
     88   return execution_function

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py in __call__(self, *args, **kwds)
    455 
    456     tracing_count = self._get_tracing_count()
--> 457     result = self._call(*args, **kwds)
    458     if tracing_count == self._get_tracing_count():
    459       self._call_counter.called_without_tracing()

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py in _call(self, *args, **kwds)
    501       # This is the first call of __call__, so we have to initialize.
    502       initializer_map = object_identity.ObjectIdentityDictionary()
--> 503       self._initialize(args, kwds, add_initializers_to=initializer_map)
    504     finally:
    505       # At this point we know that the initialization is complete (or less

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
    406     self._concrete_stateful_fn = (
    407         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
--> 408             *args, **kwds))
    409 
    410     def invalid_creator_scope(*unused_args, **unused_kwds):

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   1846     if self.input_signature:
   1847       args, kwargs = None, None
-> 1848     graph_function, _, _ = self._maybe_define_function(args, kwargs)
   1849     return graph_function
   1850 

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   2148         graph_function = self._function_cache.primary.get(cache_key, None)
   2149         if graph_function is None:
-> 2150           graph_function = self._create_graph_function(args, kwargs)
   2151           self._function_cache.primary[cache_key] = graph_function
   2152         return graph_function, args, kwargs

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   2039             arg_names=arg_names,
   2040             override_flat_arg_shapes=override_flat_arg_shapes,
-> 2041             capture_by_value=self._capture_by_value),
   2042         self._function_attributes,
   2043         # Tell the ConcreteFunction to clean up its graph once it goes out of

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    913                                           converted_func)
    914 
--> 915       func_outputs = python_func(*func_args, **func_kwargs)
    916 
    917       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    356         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    357         # the function a weak reference to itself to avoid a reference cycle.
--> 358         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    359     weak_wrapped_fn = weakref.ref(wrapped_fn)
    360 

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py in distributed_function(input_iterator)
     71     strategy = distribution_strategy_context.get_strategy()
     72     outputs = strategy.experimental_run_v2(
---> 73         per_replica_function, args=(model, x, y, sample_weights))
     74     # Out of PerReplica outputs reduce or pick values to return.
     75     all_outputs = dist_utils.unwrap_output_dict(

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py in experimental_run_v2(self, fn, args, kwargs)
    758       fn = autograph.tf_convert(fn, ag_ctx.control_status_ctx(),
    759                                 convert_by_default=False)
--> 760       return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    761 
    762   def reduce(self, reduce_op, value, axis):

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py in call_for_each_replica(self, fn, args, kwargs)
   1785       kwargs = {}
   1786     with self._container_strategy().scope():
-> 1787       return self._call_for_each_replica(fn, args, kwargs)
   1788 
   1789   def _call_for_each_replica(self, fn, args, kwargs):

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py in _call_for_each_replica(self, fn, args, kwargs)
   2130         self._container_strategy(),
   2131         replica_id_in_sync_group=constant_op.constant(0, dtypes.int32)):
-> 2132       return fn(*args, **kwargs)
   2133 
   2134   def _reduce_to(self, reduce_op, value, destinations):

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    290   def wrapper(*args, **kwargs):
    291     with ag_ctx.ControlStatusCtx(status=ag_ctx.Status.DISABLED):
--> 292       return func(*args, **kwargs)
    293 
    294   if inspect.isfunction(func) or inspect.ismethod(func):

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py in test_on_batch(model, x, y, sample_weight, reset_metrics)
    319       x, y, sample_weight=sample_weight, extract_tensors_from_dataset=True)
    320 
--> 321   batch_size = array_ops.shape(nest.flatten(x, expand_composites=True)[0])[0]
    322   outputs = training_eager.test_on_batch(
    323       model,

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py in _slice_helper(tensor, slice_spec, var)
    811         ellipsis_mask=ellipsis_mask,
    812         var=var,
--> 813         name=name)
    814 
    815 

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py in strided_slice(input_, begin, end, strides, begin_mask, end_mask, ellipsis_mask, new_axis_mask, shrink_axis_mask, var, name)
    977       ellipsis_mask=ellipsis_mask,
    978       new_axis_mask=new_axis_mask,
--> 979       shrink_axis_mask=shrink_axis_mask)
    980 
    981   parent_name = name

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py in strided_slice(input, begin, end, strides, begin_mask, end_mask, ellipsis_mask, new_axis_mask, shrink_axis_mask, name)
  10392                         ellipsis_mask=ellipsis_mask,
  10393                         new_axis_mask=new_axis_mask,
> 10394                         shrink_axis_mask=shrink_axis_mask, name=name)
  10395   _result = _op.outputs[:]
  10396   _inputs_flat = _op.inputs

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py in _apply_op_helper(self, op_type_name, name, **keywords)
    791         op = g.create_op(op_type_name, inputs, dtypes=None, name=scope,
    792                          input_types=input_types, attrs=attr_protos,
--> 793                          op_def=op_def)
    794       return output_structure, op_def.is_stateful, op
    795 

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py in create_op(***failed resolving arguments***)
    546     return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
    547         op_type, inputs, dtypes, input_types, name, attrs, op_def,
--> 548         compute_device)
    549 
    550   def capture(self, tensor, name=None):

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py in _create_op_internal(self, op_type, inputs, dtypes, input_types, name, attrs, op_def, compute_device)
   3427           input_types=input_types,
   3428           original_op=self._default_original_op,
-> 3429           op_def=op_def)
   3430       self._create_op_helper(ret, compute_device=compute_device)
   3431     return ret

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py in __init__(self, node_def, g, inputs, output_types, control_inputs, input_types, original_op, op_def)
   1771           op_def, inputs, node_def.attr)
   1772       self._c_op = _create_c_op(self._graph, node_def, grouped_inputs,
-> 1773                                 control_input_ops)
   1774     # pylint: enable=protected-access
   1775 

~/miniconda3/envs/cogsci/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py in _create_c_op(graph, node_def, inputs, control_inputs)
   1611   except errors.InvalidArgumentError as e:
   1612     # Convert to ValueError for backwards compatibility.
-> 1613     raise ValueError(str(e))
   1614 
   1615   return c_op

ValueError: slice index 0 of dimension 0 out of bounds. for 'strided_slice' (op: 'StridedSlice') with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <0>, input[2] = <1>, input[3] = <1>.`

**Comment by ravikyram** [comment]
@shepan6 

Request you to share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.

You can refer similar issue #34850, [link](https://stackoverflow.com/questions/55962508/valueerror-slice-index-0-of-dimension-0-out-of-bounds-while-using-google-colab) and see if it helps you .Thanks!

**Comment by shepan6** [comment]
Google Colab link:
https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/structured_data/feature_columns.ipynb

In terms of the solution you have provided: I have tried reduced batch size, and this does not resolve the issue.

**Comment by ravikyram** [comment]
@shepan6 

I tried in colab with TF nightly version and i am not seeing any issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/eced86aace6268e56b0eb0502a5763fc/untitled316.ipynb).Thanks!

**Comment by fernandobperezm** [comment]
## System information

- **Have I written custom code (as opposed to using a stock example script
provided in TensorFlow)**: Custom Code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Big Sur v11.3
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.0
- Python version: 3.7.7

### Instructions to install
```
conda create -n venv python=3.7 pip
conda activate venv
pip install tensorflow
```

 ### Describe the problem

`ValueError` is raised when working with RaggerTensors and functions decorated with `tf.function`. More specifically, if I do a `concatenate` on a RaggedTensor inside a `tf.function`, then a `ValueError` is raised. Instead, if I place the `concatenate` outside the `tf.function`, the code exits successfully. See the provided script.


### Script with the issue

I define two functions `f()` and `g()` that perform the same goal: concatenate the tuples in the RaggedTensor.  I named this script `test.py` and ran it with `python test.py`. I placed a print between both calls (which should be equivalent, please correct me if they're not) that demonstrates that the implementation in `f` raises an error while the one in `g` does not. The only difference between them is that the `tf.concat` call is placed outside the `tf.function` or not.

In my real use case, the RaggedTensor is created after some pre-processing, as opposed to this case where I already set up the values and row-lengths. I provide this script as a minimal-reproducible example :) 

```python
import sys
import numpy as np
import tensorflow as tf


@tf.function
def f(values, row_lengths):
    b = tf.RaggedTensor.from_row_lengths(
        values=values,
        row_lengths=row_lengths,
    )

    return tf.concat([x for x in b], axis=0)


@tf.function
def g(values, row_lengths):
    return tf.RaggedTensor.from_row_lengths(
        values=values,
        row_lengths=row_lengths,
    )


if __name__ == '__main__':
    values = tf.convert_to_tensor(
        np.array([
            [0, 1],
            [0, 2],
            [1, 0],
            [1, 2],
            [2, 0],
            [2, 1],
        ])
    )
    row_lengths = [2, 2, 2]

    print(sys.version)
    print(tf.__version__)
    print(tf.concat([x for x in g(values, row_lengths)], axis=0))
    print("G Ready")
    print(f(values, row_lengths))
```

### Error
```
2021-05-01 00:27:58.195310: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-01 00:27:58.195688: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
3.7.10 (default, Feb 26 2021, 10:16:00) 
[Clang 10.0.0 ]
2.4.0
2021-05-01 00:27:58.307849: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-05-01 00:27:58.318700: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:906] Skipping loop optimization for Merge node with control input: RaggedFromRowLengths/RowPartitionFromRowLengths/assert_non_negative/assert_less_equal/Assert/AssertGuard/branch_executed/_8
tf.Tensor(
[[0 1]
 [0 2]
 [1 0]
 [1 2]
 [2 0]
 [2 1]], shape=(6, 2), dtype=int64)
G Ready
Traceback (most recent call last):
  File "test_numpy.py", line 41, in <module>
    print(f(values, row_lengths))
  File "/Users/fernandobperezm/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/Users/fernandobperezm/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/Users/fernandobperezm/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 726, in _initialize
    *args, **kwds))
  File "/Users/fernandobperezm/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/Users/fernandobperezm/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/fernandobperezm/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3206, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Users/fernandobperezm/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/fernandobperezm/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/fernandobperezm/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    test_numpy.py:13 f  *
        return tf.concat([x for x in b], axis=0)
    /Users/fernandobperezm/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/ops/ragged/ragged_getitem.py:103 ragged_tensor_getitem
        return _ragged_getitem(self, key)
    /Users/fernandobperezm/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/ops/ragged/ragged_getitem.py:186 _ragged_getitem
        row = rt_input.values[starts[row_key]:limits[row_key]]
    /Users/fernandobperezm/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /Users/fernandobperezm/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:1047 _slice_helper
        name=name)
    /Users/fernandobperezm/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /Users/fernandobperezm/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:1219 strided_slice
        shrink_axis_mask=shrink_axis_mask)
    /Users/fernandobperezm/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py:10479 strided_slice
        shrink_axis_mask=shrink_axis_mask, name=name)
    /Users/fernandobperezm/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:750 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    /Users/fernandobperezm/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py:592 _create_op_internal
        compute_device)
    /Users/fernandobperezm/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:3536 _create_op_internal
        op_def=op_def)
    /Users/fernandobperezm/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:2016 __init__
        control_input_ops, op_def)
    /Users/fernandobperezm/miniconda3/envs/venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:1856 _create_c_op
        raise ValueError(str(e))

    ValueError: slice index 3 of dimension 0 out of bounds. for '{{node RaggedGetItem_3/strided_slice_2}} = StridedSlice[Index=DT_INT32, T=DT_INT64, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1](RaggedGetItem_3/strided_slice, RaggedGetItem_3/strided_slice_2/stack, RaggedGetItem_3/strided_slice_2/stack_1, RaggedGetItem_3/strided_slice_2/stack_2)' with input shapes: [3], [1], [1], [1] and with computed input tensors: input[1] = <3>, input[2] = <4>, input[3] = <1>.
```

**Comment by bkocis** [comment]
any resolution to these issues?
