### ISSUE TITLE
Build Failure of version 2.3.0 in macOS, MacPorts

### ISSUE THREAD

**Issue by essandess** [tensorflow/tensorflow#42090]
Version 2.3.0 fails to build on macOS.

First issue, `Action failed to execute: java.io.IOException: Cannot run program… error=24, Too many open files`:
```
ERROR: /opt/local/var/macports/build/_opt_local_ports_python_py-tensorflow/py37-tensorflow/work/tensorflow-tensorflow-b36436b/tensorflow/core/common_runtime/BUILD:328:11: C++ compilation of rule '//tensorflow/core/common_runtime:collective_executor_mgr' failed (Exit -1): wrapped_clang failed: error executing command 
  (cd /opt/local/var/macports/build/_opt_local_ports_python_py-tensorflow/py37-tensorflow/work/e3571a779784f9da03a7824d69817047/execroot/org_tensorflow && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.15 \
    PATH=/opt/local/bin:/opt/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin \
    XCODE_VERSION_OVERRIDE=11.6.0.11E708 \
  external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG '-std=c++11' -iquote . -iquote bazel-out/host/bin -iquote external/com_google_absl -iquote bazel-out/host/bin/external/com_google_absl -iquote external/eigen_archive -iquote bazel-out/host/bin/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/host/bin/external/local_config_sycl -iquote external/nsync -iquote bazel-out/host/bin/external/nsync -iquote external/gif -iquote bazel-out/host/bin/external/gif -iquote external/libjpeg_turbo -iquote bazel-out/host/bin/external/libjpeg_turbo -iquote external/com_google_protobuf -iquote bazel-out/host/bin/external/com_google_protobuf -iquote external/com_googlesource_code_re2 -iquote bazel-out/host/bin/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/host/bin/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/host/bin/external/fft2d -iquote external/highwayhash -iquote bazel-out/host/bin/external/highwayhash -iquote external/zlib -iquote bazel-out/host/bin/external/zlib -iquote external/double_conversion -iquote bazel-out/host/bin/external/double_conversion -isystem external/eigen_archive -isystem bazel-out/host/bin/external/eigen_archive -isystem external/nsync/public -isystem bazel-out/host/bin/external/nsync/public -isystem external/gif -isystem bazel-out/host/bin/external/gif -isystem external/com_google_protobuf/src -isystem bazel-out/host/bin/external/com_google_protobuf/src -isystem external/farmhash_archive/src -isystem bazel-out/host/bin/external/farmhash_archive/src -isystem external/zlib -isystem bazel-out/host/bin/external/zlib -isystem external/double_conversion -isystem bazel-out/host/bin/external/double_conversion -MD -MF bazel-out/host/bin/tensorflow/core/common_runtime/_objs/collective_executor_mgr/collective_executor_mgr.d -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DEIGEN_HAS_TYPE_TRAITS=0' '-frandom-seed=bazel-out/host/bin/tensorflow/core/common_runtime/_objs/collective_executor_mgr/collective_executor_mgr.o' -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/MacOSX.platform/Developer/Library/Frameworks '-mmacosx-version-min=10.15' -g0 '-march=x86-64' -g0 '-std=c++14' -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare '-ftemplate-depth=900' -fno-exceptions '-DTENSORFLOW_USE_XLA=1' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c tensorflow/core/common_runtime/collective_executor_mgr.cc -o bazel-out/host/bin/tensorflow/core/common_runtime/_objs/collective_executor_mgr/collective_executor_mgr.o)
Execution platform: @local_execution_config_platform//:platform. Note: Remote connection/protocol failed with: execution failed
Action failed to execute: java.io.IOException: Cannot run program "/opt/local/var/macports/build/_opt_local_ports_python_py-tensorflow/py37-tensorflow/work/install/1eb24b6f9fb447fbef56fd6c7521f126/process-wrapper" (in directory "/opt/local/var/macports/build/_opt_local_ports_python_py-tensorflow/py37-tensorflow/work/e3571a779784f9da03a7824d69817047/execroot/org_tensorflow"): error=24, Too many open files
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

This is with system settings:
```bash
$ ulimit -n
65536
$ launchctl limit maxfiles
	maxfiles    65536          200000   
```

Starting the build again, another issue is encountered, apparently arising from https://github.com/tensorflow/tensorflow/pull/40654.

Second issue, `error: no matching function for call to object of type '(lambda at tensorflow/python/lib/core/bfloat16.cc:637:25)`:
```
:info:build tensorflow/python/lib/core/bfloat16.cc:678:8: error: no matching function for call to object of type '(lambda at tensorflow/python/lib/core/bfloat16.cc:637:25)'
:info:build   if (!register_ufunc("less_equal", CompareUFunc<Bfloat16LeFunctor>,
:info:build        ^~~~~~~~~~~~~~
:info:build tensorflow/python/lib/core/bfloat16.cc:637:25: note: candidate function not viable: no overload of 'CompareUFunc' matching 'PyUFuncGenericFunction' (aka 'void (*)(char **, const long *, const long *, void *)') for 2nd argument
:info:build   auto register_ufunc = [&](const char* name, PyUFuncGenericFunction fn,
:info:build                         ^
:info:build tensorflow/python/lib/core/bfloat16.cc:682:8: error: no matching function for call to object of type '(lambda at tensorflow/python/lib/core/bfloat16.cc:637:25)'
:info:build   if (!register_ufunc("greater_equal", CompareUFunc<Bfloat16GeFunctor>,
:info:build        ^~~~~~~~~~~~~~
```

macOS 10.15.6 19G73
Xcode 11.6 11E708 

Related:
* https://trac.macports.org/ticket/60960
* https://github.com/macports/macports-ports/pull/7575
* https://github.com/tensorflow/tensorflow/pull/40654

**Comment by amahendrakar** [comment]
@essandess,
Could you please provide the exact sequence of commands / steps that you executed before running into the error?

Also, please take a look at the [tested build configurations](https://www.tensorflow.org/install/source#macos) and check if you have the compatible dependencies installed, Thanks!

**Comment by essandess** [comment]
I have the enormous log file. What's the best way to transmit to you?

Also, this has all dependencies. The MacPorts build was working up until version 2.2.0.

**Comment by rockspring** [comment]
ERROR: /Users/xxx/oss/tensorflow/tensorflow/python/BUILD:501:1: C++ compilation of rule '//tensorflow/python:bfloat16_lib' failed (Exit 1)
tensorflow/python/lib/core/bfloat16.cc:663:8: error: no matching function for call to object of type '(lambda at tensorflow/python/lib/core/bfloat16.cc:637:25)'
  if (!register_ufunc("equal", CompareUFunc<Bfloat16EqFunctor>,
       ^~~~~~~~~~~~~~
tensorflow/python/lib/core/bfloat16.cc:637:25: note: candidate function not viable: no overload of 'CompareUFunc' matching 'PyUFuncGenericFunction' (aka 'void (*)(char **, const long *, const long *, void *)') for 2nd argument
  auto register_ufunc = [&](const char* name, PyUFuncGenericFunction fn,
                        ^
tensorflow/python/lib/core/bfloat16.cc:667:8: error: no matching function for call to object of type '(lambda at tensorflow/python/lib/core/bfloat16.cc:637:25)'
  if (!register_ufunc("not_equal", CompareUFunc<Bfloat16NeFunctor>,
       ^~~~~~~~~~~~~~
tensorflow/python/lib/core/bfloat16.cc:637:25: note: candidate function not viable: no overload of 'CompareUFunc' matching 'PyUFuncGenericFunction' (aka 'void (*)(char **, const long *, const long *, void *)') for 2nd argument
  auto register_ufunc = [&](const char* name, PyUFuncGenericFunction fn,
                        ^
tensorflow/python/lib/core/bfloat16.cc:671:8: error: no matching function for call to object of type '(lambda at tensorflow/python/lib/core/bfloat16.cc:637:25)'
  if (!register_ufunc("less", CompareUFunc<Bfloat16LtFunctor>, compare_types)) {
       ^~~~~~~~~~~~~~
tensorflow/python/lib/core/bfloat16.cc:637:25: note: candidate function not viable: no overload of 'CompareUFunc' matching 'PyUFuncGenericFunction' (aka 'void (*)(char **, const long *, const long *, void *)') for 2nd argument
  auto register_ufunc = [&](const char* name, PyUFuncGenericFunction fn,
                        ^
tensorflow/python/lib/core/bfloat16.cc:674:8: error: no matching function for call to object of type '(lambda at tensorflow/python/lib/core/bfloat16.cc:637:25)'
  if (!register_ufunc("greater", CompareUFunc<Bfloat16GtFunctor>,
       ^~~~~~~~~~~~~~
tensorflow/python/lib/core/bfloat16.cc:637:25: note: candidate function not viable: no overload of 'CompareUFunc' matching 'PyUFuncGenericFunction' (aka 'void (*)(char **, const long *, const long *, void *)') for 2nd argument
  auto register_ufunc = [&](const char* name, PyUFuncGenericFunction fn,
                        ^
tensorflow/python/lib/core/bfloat16.cc:678:8: error: no matching function for call to object of type '(lambda at tensorflow/python/lib/core/bfloat16.cc:637:25)'
  if (!register_ufunc("less_equal", CompareUFunc<Bfloat16LeFunctor>,
       ^~~~~~~~~~~~~~
tensorflow/python/lib/core/bfloat16.cc:637:25: note: candidate function not viable: no overload of 'CompareUFunc' matching 'PyUFuncGenericFunction' (aka 'void (*)(char **, const long *, const long *, void *)') for 2nd argument
  auto register_ufunc = [&](const char* name, PyUFuncGenericFunction fn,
                        ^
tensorflow/python/lib/core/bfloat16.cc:682:8: error: no matching function for call to object of type '(lambda at tensorflow/python/lib/core/bfloat16.cc:637:25)'
  if (!register_ufunc("greater_equal", CompareUFunc<Bfloat16GeFunctor>,
       ^~~~~~~~~~~~~~
tensorflow/python/lib/core/bfloat16.cc:637:25: note: candidate function not viable: no overload of 'CompareUFunc' matching 'PyUFuncGenericFunction' (aka 'void (*)(char **, const long *, const long *, void *)') for 2nd argument
  auto register_ufunc = [&](const char* name, PyUFuncGenericFunction fn,
                        ^
6 errors generated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /Users/xxx/oss/tensorflow/tensorflow/tools/pip_package/BUILD:66:1 C++ compilation of rule '//tensorflow/python:bfloat16_lib' failed (Exit 1)

**Comment by amahendrakar** [comment]
> I have the enormous log file. What's the best way to transmit to you?

@essandess,
You can copy the logs to a text file and then share the file with us. Thanks!

**Comment by amahendrakar** [comment]
@rockspring,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by essandess** [comment]
> @rockspring,
> Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

Please see https://github.com/tensorflow/tensorflow/issues/42479

**Comment by amahendrakar** [comment]
> Please see #42479

@essandess,
The message to submit a new issue was addressed to the user @rockspring.

Since you have already submitted a new issue, can we close this since it is being tracked there? Thanks!

**Comment by essandess** [comment]
> > Please see #42479
> 
> @essandess,
> The message to submit a new issue was addressed to the user @rockspring.
> 
> Since you have already submitted a new issue, can we close this since it is being tracked there? Thanks!

Yes, closed.
