### ISSUE TITLE
cross-compile Inference Diff tool

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#42096]
Hello guys,

is it posible to cross-compile the [Inference Diff tool](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/evaluation/tasks/inference_diff) - I mean with bazel ...
If so, can you please indicate how?

Thank you

**Comment by freedomtan** [comment]
Surely yes
```
bazel build -c opt \
  --config=android_arm64 \
  //tensorflow/lite/tools/evaluation/tasks/inference_diff:run_eval
```
example in its REAME.md is to cross-compile it on x86_64 Linux or macOS for arm64 Android devices :-)

What's your target device?

**Comment by peter197321** [comment]
Target device: ARM64 with Linux

**Comment by ymodak** [comment]
@peter197321 Is this still an issue? Were you able to build successfully with https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/evaluation/tasks/inference_diff#running-the-binary-on-android?

**Comment by peter197321** [comment]
I wanna build for aarch64 Linux device and not android.
