### ISSUE TITLE
SequenceFeatures cant get embedding with shared_embedding_columns

### ISSUE THREAD

**Issue by alansplaza** [tensorflow/tensorflow#42099]
```
import tensorflow as tf # tf.version==1.14.0

def test_crossed_column():
    """ crossed column测试 """
    features = {
        'price': [[0,1], [1,0], [2,1]],
        'color': [[1,2], [2,2], [0,0]]
    }
    price = tf.feature_column.sequence_categorical_column_with_vocabulary_list('price', [1,2], default_value=-1)
    color = tf.feature_column.sequence_categorical_column_with_vocabulary_list('color', [1,2], default_value=-1)
    price = tf.feature_column.shared_embedding_columns([price, color], 4)
    price_layer = tf.keras.experimental.SequenceFeatures(price)
    x = price_layer(features)
    with tf.Session() as session:
        session.run(tf.global_variables_initializer())
        session.run(tf.tables_initializer())
        print(session.run([x]))
test_crossed_column()
```
with the code, tf cant get embedding value with shared_embdding_columns, for the reason
```
ValueError: Items of feature_columns must be a FeatureColumn. Given (type <class 'tensorflow.python.feature_column.feature_column._SharedEmbeddingColumn'>): _SharedEmbeddingColumn(categorical_column=_SequenceCategoricalColumn(categorical_column=VocabularyListCategoricalColumn(key='price', vocabulary_list=(1, 2), dtype=tf.int64, default_value=-1, num_oov_buckets=0)), dimension=4, combiner='mean', initializer=<tensorflow.python.ops.init_ops.TruncatedNormal object at 0x7f8fd783a850>, shared_embedding_collection_name='color_price_shared_embedding', ckpt_to_load_from=None, tensor_name_in_ckpt=None, max_norm=None, trainable=True).
```
Why _SharedEmbeddingColumn isn't a type of fc?

**Comment by Saduf2019** [comment]
@alansplaza 
Please paste the error message (using makrdown formatting around it) instead of screenshotting. Screenshots are not searchable so they don't help in looking for the issue and also don't help other people having the same error from finding about the issue.
Also please provide complete stand alone code such that we can replicate the issue reported, as i am facing different error, [gist for the same](https://colab.research.google.com/gist/Saduf2019/06c0ade874976589c30c9865fb20db36/untitled330.ipynb).

**Comment by alansplaza** [comment]
> @alansplaza
> Please paste the error message (using makrdown formatting around it) instead of screenshotting. Screenshots are not searchable so they don't help in looking for the issue and also don't help other people having the same error from finding about the issue.
> Also please provide complete stand alone code such that we can replicate the issue reported, as i am facing different error, [gist for the same](https://colab.research.google.com/gist/Saduf2019/06c0ade874976589c30c9865fb20db36/untitled330.ipynb).

My tf version is '1.14.0'. Thanks.

**Comment by alansplaza** [comment]
> @alansplaza
> Please paste the error message (using makrdown formatting around it) instead of screenshotting. Screenshots are not searchable so they don't help in looking for the issue and also don't help other people having the same error from finding about the issue.
> Also please provide complete stand alone code such that we can replicate the issue reported, as i am facing different error, [gist for the same](https://colab.research.google.com/gist/Saduf2019/06c0ade874976589c30c9865fb20db36/untitled330.ipynb).

The error and complete code is updated.

**Comment by Saduf2019** [comment]
I ran the code on 1.15 and tf nightly , i am able to replicate the issue, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/a48af59e613e7ee81f4f4f9a0129a6b0/untitled343.ipynb).

**Comment by tanzhenyu** [comment]
Keras layers like this are known to not work with shared embeddings, even for `DenseFeatures`.
I'd recommend you trying out [keras preprocessing layers](https://github.com/tensorflow/community/blob/master/rfcs/20191212-keras-categorical-inputs.md#workflow-1----official-guide-on-how-to-replace-feature-columns-with-kpl)
