### ISSUE TITLE
[Tensorflow Lite] MobileBert Inferencing Latency on mobile device significantly slower than expected

### ISSUE THREAD

**Issue by gregburman** [tensorflow/tensorflow#42098]
I am trying to run the BERT Question and Answer demo outlined on [this page](https://www.tensorflow.org/lite/models/bert_qa/overview), which demonstrates inferencing MobileBert on a mobile device.

I have cloned the relevant Android repository code found [here](https://github.com/tensorflow/examples/tree/master/lite/examples/bert_qa/android), and deployed the project to my Pixel 3 device.

The demo runs, however it takes significantly longer than expected: according to this [blog post](https://blog.tensorflow.org/2020/04/whats-new-in-tensorflow-lite-from-devsummit-2020.html), model latency should be around 74ms, however I'm seeing latency on the order of 500ms.

Can someone please advise if there's some setting/configuration that I'm missing? I have noted that the supplied MobileBert model is Float32 and so hasn't been quantised which means it won't use any hardware acceleration. I've also noted that no delegate has been specified to leverage any dedicated hardware acceleration (e.g. GPU).

Note: I'm submitting this issue here, as there's no option to submit issues under the relevant [examples](https://github.com/tensorflow/examples) repository. Please do let me know if I should be raising this query elsewhere.

Thanks in advance for any assistance/advice you can provide :)

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Pixel 3
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: n/a
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**

Query inferencing time is ~500ms.

**Describe the expected behavior**

Query inference time should be closer to 74ms.

**Standalone code to reproduce the issue**
I used the code from the example project repository verbatim (without any changes/customisations).

**Comment by gregburman** [comment]
Just checking in to see if anyone has had an opportunity to look at this issue?

I also have an update from our side:

we updated to Tensorflow 2.3.0 on the mobile device, and found that the inference time for Albert dropped down to ~800 ms, while the inference time for MobileBERT remained the same (~500ms).

Further, I noted that the authors of [SqeezeBERT](https://arxiv.org/pdf/2006.11316.pdf) obtained similar inference latencies to us, also using a Pixel 3 device.

**Comment by karimnosseir** [comment]
Renjie, Can you please help check what is wrong with the setup

Thanks

**Comment by renjie-liu** [comment]
Hi, 

The blog post is benchmarking for a 128 seq_len model on pixel4 with 4 threads.

For the qa task app, it's using a 384 seq_len model, and I don't think it's using 4 threads.

Also, pixel4 is faster than pixel3, so I guess the number is expected.
