### ISSUE TITLE
Compilation and Linking errors in MSVC Debug builds

### ISSUE THREAD

**Issue by planetmarshall** [tensorflow/tensorflow#42094]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10**
- TensorFlow installed from (source or binary): **Source**
- TensorFlow version: **2.3.0**
- Python version: **3.8.5**
- Bazel version (if compiling from source): **3.3.1**
- GCC/Compiler version (if compiling from source): **Visual Studio 2019**

Also reproduced in master (4be925e3)

**Describe the problem**

Multiple compilation errors when building in Windows Debug mode due to [C4716 ('function' must return a value)](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4716?view=vs-2019)

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
bazel build --config=dbg //tensorflow:tensorflow_framework
```

**Any other info / logs**

Compilation errors due to C4716 being elevated to an error in debug mode, eg in [`device_base.cc`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/device_base.cc)

```.py 
const DeviceAttributes& DeviceBase::attributes() const {
  LOG(FATAL) << "Device does not implement attributes()";
}
```

Since AFAIK tensorflow does not use C++ exceptions (I believe it compiles with `-fno-exceptions` on Clang/GCC so I assume this is official policy) this would have to be handled with a `pragma warning (disable: 4217)` somewhere in the code. Will submit a suitable PR when I have time if no one gets to it first.

**Comment by planetmarshall** [comment]
Unfortunately there's more to this than simply disabling the warning. MSVC debug builds link in a number of symbols that would normally be excluded by compile-time type checks, meaning the the Windows CPU build will not link.

For example, in `spacetodepth_op.cc`

```.cpp
if (std::is_same<Device, GPUDevice>::value) {
   ...
   functor::SpaceToDepthOpFunctor<GPUDevice, int32, FORMAT_NCHW> functor;
   ...
```

`functor` would never be instantiated on a CPU build where the `GPUDevice` is not available. In a release build this is not a problem. However, in a debug build the code is still generated and linked, even though it would never be executed - which results in a linking error because the `GPUDevice` instantiation is not available

```
depth_space_ops.lo.lib(depthtospace_op.obj) : error LNK2019: unresolved external symbol "public: void __cdecl tensorflow::functor::DepthToSpaceOpFunctor<struct Eigen::GpuDevice,unsigned __int64,1>::operator() ... referenced in function "public: virtual void __cdecl tensorflow::DepthToSpaceOp<struct Eigen::ThreadPoolDevice,unsigned __int64>::Compute(class tensorflow::OpKernelContext *)"
```

**Comment by planetmarshall** [comment]
I believe this issue can be resolved with

```.cpp
if constexpr(std::is_same<Device, GPUDevice>::value) {...}
```

But requires C++17 support to be enabled. 

As Bazel has been attempting to link the `tensorflow_cc.dll` for over an hour now, I may just have to give up on the MSVC debug build anyway.

**Comment by gunan** [comment]
As much as I would like to help, I never was able to make the debug build work in any OSs with TF.
Especially on windows, I do not have much experience.

**Comment by mihaimaruseac** [comment]
#42676 might be able to fix this

**Comment by mihaimaruseac** [comment]
This should be done by #42676, I think
