### ISSUE TITLE
Use __all__ to restrict exported Python symbols to the public API

### ISSUE THREAD

**Issue by girving** [tensorflow/tensorflow#421]
As part of semantic versioning, our public Python API is (about to be) defined as the symbols documented at https://www.tensorflow.org/api_docs/python.  This is a good definition, but it makes it easy for users to accidentally depend on the non-public API.  To fix this, we should add `__all__` to our Python modules and make sure `__all__` matches the documented public API exactly.

Since we already declare the public symbols via '@@' references in the module docstring, we may be able to do this programmatically.  Indeed,

```
__all__ = [m.group(1) for m in re.finditer(r'^@@(\w+)$', sys.modules[__name__].__doc__)]
```

For Google folk, see b/25561952.

**Comment by martinwicke** [comment]
I like that __all__ solution, then we only have to worry about the top-level tf module.

**Comment by girving** [comment]
We can build the toplevel `__all__` by concatenating the submodule `__all__`s.

**Comment by martinwicke** [comment]
This will not work for classes and class members, correct? I suppose we can rely on _ for members, but classes may be trickier.

**Comment by girving** [comment]
It should work fine for classes, and class members aren't part of either `__all__` or the module docstring.

**Comment by girving** [comment]
Internal note: Once this is done, we should test that all exposed symbols are documented.

**Comment by girving** [comment]
@cwhipkey has made progress on this.

**Comment by girving** [comment]
@cwhipkey: What's the recent status of this?  Are we still in large whitelist stage?

**Comment by cwhipkey** [comment]
Yes, still in the large whitelist stage for the modules that have __all__ added.  There are also some modules that don't have __all__ added, like 'flags'.

**Comment by aselle** [comment]
This is now done. Thanks!
