### ISSUE TITLE
deepdream tutorial rename_nodes error

### ISSUE THREAD

**Issue by lonce** [tensorflow/tensorflow#4210]
Hi -
    The tensorflow/examples/deepdream README.md says that Python 2.7 is required. However, loading the deepdream.ipynb notebook fires up the 3.5 kernel (due to info I believe is stored in the notebook itself. 
    
But the error I am encountering on the line:
tmp_def = rename_nodes(graph_def, lambda s:"/".join(s.split('_',1)))

may or may not be due to a python version issue. The line generates the error:
TypeError: '<stripped 37632 bytes>' has type <class 'str'>, but expected one of: (<class 'bytes'>,)

I'm running Mac OS X 10.10.5, python 2.7 for the Mac, and 3.5 for everything else. 
Best,
            - lonce

**Comment by tatatodd** [comment]
I'm not sure about the Python 2.7 / 3.5 issue, or whether that's related either.

Please provide the following additional info.  FYI this also appears in the default template when you click on the green "New issue" button at the top of the webpage for this issue.
```
If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`
```

Also - what do you mean by "everything else" in "...python 2.7 for the Mac, and 3.5 for everything else."

**Comment by lonce** [comment]
Hi tatatodd,

 > 1. A link to the pip package you installed:
https://www.python.org/ftp/python/3.5.2/python-3.5.2-macosx10.6.pkg

 > 2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
   https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.10.0-py3-none-any.whl 

 > Also - what do you mean by "everything else" in "...python 2.7 for the Mac, and 3.5 for everything else."
I mean I also have python 2.7 installed (I understand it is needed by OSX for something), but for my own development, I use 3.5.

This may be more info than you need, by the traceback for the error follow: 
TypeError                                 Traceback (most recent call last)
<ipython-input-4-f63c00409564> in <module>()
     56 # internal structure. We are going to visualize "Conv2D" nodes.
     57 tmp_def = rename_nodes(graph_def, lambda s:"/".join(s.split('_',1)))
---> 58 show_graph(tmp_def)

<ipython-input-4-f63c00409564> in show_graph(graph_def, max_const_size)
     35     if hasattr(graph_def, 'as_graph_def'):
     36         graph_def = graph_def.as_graph_def()
---> 37     strip_def = strip_consts(graph_def, max_const_size=max_const_size)
     38     code = """
     39         <script>

<ipython-input-4-f63c00409564> in strip_consts(graph_def, max_const_size)
     18             size = len(tensor.tensor_content)
     19             if size > max_const_size:
---> 20                 tensor.tensor_content = "<stripped %d bytes>"%size
     21     return strip_def
     22 

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/google/protobuf/internal/python_message.py in field_setter(self, new_value)
    662     # Testing the value for truthiness captures all of the proto3 defaults
    663     # (0, 0.0, enum 0, and False).
--> 664     new_value = type_checker.CheckValue(new_value)
    665     if clear_when_set_to_default and not new_value:
    666       self._fields.pop(field, None)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/google/protobuf/internal/type_checkers.py in CheckValue(self, proposed_value)
    106       message = ('%.1024r has type %s, but expected one of: %s' %
    107                  (proposed_value, type(proposed_value), self._acceptable_types))
--> 108       raise TypeError(message)
    109     return proposed_value
    110 

TypeError: '<stripped 37632 bytes>' has type <class 'str'>, but expected one of: (<class 'bytes'>,)

Thank you,
                      - lonce

**Comment by aselle** [comment]
Can you manually change the ipynb's kernel to your py2.7 kernel spec (the jupyter menu)? If you don't have a py2.7 kernel spec you can create one using the standard jupyter techniques (google search). You may want to use virtualenv to isolate your tensorflow related setup.

**Comment by MatthiasWinkelmann** [comment]
DeepDream almost works with Python 3.5. I've submitted a pull request in #4366 but until then, you can just change the line in strip_consts to:

```
tensor.tensor_content = bytes("<stripped %d bytes>"%size, 'utf-8')
```

Python 3.5 seems to be stricter about implicit conversions, in this case refusing to convert string -> byte without knowing the encoding (which defines the conversion,)

**Comment by lonce** [comment]
Sweet! That did the trick, Matthias.
Thanks to all.

**Comment by normanheckscher** [comment]
Python 2.7 didn't like that. Needed to revert the line of code to get it to run.
