### ISSUE TITLE
ModelCheckpoint does not return the least val_loss when number of batch is not 32.

### ISSUE THREAD

**Issue by alirezaghader** [tensorflow/tensorflow#42107]
the had been issue solved

**Comment by ravikyram** [comment]
@alirezaghader 

Request you to fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
 Also include your TensorFlow version.Thanks!

**Comment by alirezaghader** [comment]
@ravikyram  I have tested the code with tf 2.3 2.2 2.11 and 1.14, in all of them result was same
