### ISSUE TITLE
Input size of converted lite model doesn't match the original model input size

### ISSUE THREAD

**Issue by hahmad2008** [tensorflow/tensorflow#42114]
**System information**
- COLAB:
- TensorFlow version 2.4.0-dev20200805:

**Command used to run the converter or code if you’re using the Python API**
this [Link](https://colab.research.google.com/gist/jvishnuvardhan/23066f1a722fc566b437a5210d1b97b0/ssd_saved_model_tflite_conversion.ipynb#scrollTo=X5s5D5ufCcKb) for code I used in converting the saved model to TensorFlow lite

```
!pip install tf-nightly
model_dir=saved_model'
converter = tf.lite.TFLiteConverter.from_saved_model(model_dir,signature_keys=['serving_default'],)

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]

tflite_model = converter.convert()

#open("saved_model/converted_model.tflite", "wb").write(tflite_model)
open('tflite_model.tflite','wb').write(tflite_model)
```

**The output from the converter invocation**
- successfully generate the model.tflite
- But When I checked the input for both the original and converted model, I found the following mismatching:
- -  checked the input for the model I got it as [1,1,1,3] instead of [1,300,300,3]
-- in my config file to train the object detection model, I have the following image resize:
```
image_resizer {
      fixed_shape_resizer {
        height: 300
        width: 300
      }
    }
```

**The original model I used is saved model,  It is the same as all models in the [model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md).**

**I was training the object detection API and run it successfully with original .pb saved model ([using this backbone model](http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_320x320_coco17_tpu-8.tar.gz))**

Any recommendations here? Thanks.

**Comment by MeghnaNatraj** [comment]
I was able to run this and noticed that i get the same error as https://github.com/tensorflow/tensorflow/issues/41877. This issue also has many related github issues added in last few days/weeks. 


```
!pip install tf-nightly
import tensorflow as tf

converter = tf.compat.v1.lite.TFLiteConverter.from_saved_model(
    saved_model_dir='saved_model',
    input_arrays = ['serving_default_input_tensor'],
    input_shapes={'serving_default_input_tensor': [1,320,320,3]},
    signature_key='serving_default')
# converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
open("model.tflite", "wb").write(tflite_model)
```

```
INFO:tensorflow: tensor name: serving_default_input_tensor:0, shape: (1, -1, -1, 3), type: DT_UINT8
INFO:tensorflow:output tensors info: 
INFO:tensorflow:output tensors info: 
INFO:tensorflow:Tensor's key in saved_model's tensor_map: raw_detection_boxes
INFO:tensorflow:Tensor's key in saved_model's tensor_map: raw_detection_boxes
INFO:tensorflow: tensor name: StatefulPartitionedCall:6, shape: (1, 1917, 4), type: DT_FLOAT
INFO:tensorflow: tensor name: StatefulPartitionedCall:6, shape: (1, 1917, 4), type: DT_FLOAT
INFO:tensorflow:Tensor's key in saved_model's tensor_map: detection_scores
INFO:tensorflow:Tensor's key in saved_model's tensor_map: detection_scores
INFO:tensorflow: tensor name: StatefulPartitionedCall:4, shape: (1, 100), type: DT_FLOAT
INFO:tensorflow: tensor name: StatefulPartitionedCall:4, shape: (1, 100), type: DT_FLOAT
INFO:tensorflow:Tensor's key in saved_model's tensor_map: raw_detection_scores
INFO:tensorflow:Tensor's key in saved_model's tensor_map: raw_detection_scores
INFO:tensorflow: tensor name: StatefulPartitionedCall:7, shape: (1, 1917, 91), type: DT_FLOAT
INFO:tensorflow: tensor name: StatefulPartitionedCall:7, shape: (1, 1917, 91), type: DT_FLOAT
INFO:tensorflow:Tensor's key in saved_model's tensor_map: detection_anchor_indices
INFO:tensorflow:Tensor's key in saved_model's tensor_map: detection_anchor_indices
INFO:tensorflow: tensor name: StatefulPartitionedCall:0, shape: (1, 100), type: DT_FLOAT
INFO:tensorflow: tensor name: StatefulPartitionedCall:0, shape: (1, 100), type: DT_FLOAT
INFO:tensorflow:Tensor's key in saved_model's tensor_map: detection_multiclass_scores
INFO:tensorflow:Tensor's key in saved_model's tensor_map: detection_multiclass_scores
INFO:tensorflow: tensor name: StatefulPartitionedCall:3, shape: (1, 100, 91), type: DT_FLOAT
INFO:tensorflow: tensor name: StatefulPartitionedCall:3, shape: (1, 100, 91), type: DT_FLOAT
INFO:tensorflow:Tensor's key in saved_model's tensor_map: detection_classes
INFO:tensorflow:Tensor's key in saved_model's tensor_map: detection_classes
INFO:tensorflow: tensor name: StatefulPartitionedCall:2, shape: (1, 100), type: DT_FLOAT
INFO:tensorflow: tensor name: StatefulPartitionedCall:2, shape: (1, 100), type: DT_FLOAT
INFO:tensorflow:Tensor's key in saved_model's tensor_map: num_detections
INFO:tensorflow:Tensor's key in saved_model's tensor_map: num_detections
INFO:tensorflow: tensor name: StatefulPartitionedCall:5, shape: (1), type: DT_FLOAT
INFO:tensorflow: tensor name: StatefulPartitionedCall:5, shape: (1), type: DT_FLOAT
INFO:tensorflow:Tensor's key in saved_model's tensor_map: detection_boxes
INFO:tensorflow:Tensor's key in saved_model's tensor_map: detection_boxes
INFO:tensorflow: tensor name: StatefulPartitionedCall:1, shape: (1, 100, 4), type: DT_FLOAT
INFO:tensorflow: tensor name: StatefulPartitionedCall:1, shape: (1, 100, 4), type: DT_FLOAT
INFO:tensorflow:Restoring parameters from saved_model/variables/variables
INFO:tensorflow:Restoring parameters from saved_model/variables/variables
Use '@tf.function' or '@defun' to decorate the function.Use '@tf.function' or '@defun' to decorate the function.Use '@tf.function' or '@defun' to decorate the function.........
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    198                                                  debug_info_str,
--> 199                                                  enable_mlir_converter)
    200       return model_str

5 frames
Exception: <unknown>:0: error: loc("Func/StatefulPartitionedCall/input/_1"): requires all operands and results to have compatible element types
<unknown>:0: note: loc("Func/StatefulPartitionedCall/input/_1"): see current operation: %1 = "tf.Identity"(%arg0) {_class = ["loc:@Func/StatefulPartitionedCall/StatefulPartitionedCall/input/_992"], device = ""} : (tensor<1x320x320x3x!tf.quint8>) -> tensor<1x320x320x3xui8>


During handling of the above exception, another exception occurred:

ConverterError                            Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    200       return model_str
    201     except Exception as e:
--> 202       raise ConverterError(str(e))
    203 
    204   if distutils.spawn.find_executable(_toco_from_proto_bin) is None:

ConverterError: <unknown>:0: error: loc("Func/StatefulPartitionedCall/input/_1"): requires all operands and results to have compatible element types
<unknown>:0: note: loc("Func/StatefulPartitionedCall/input/_1"): see current operation: %1 = "tf.Identity"(%arg0) {_class = ["loc:@Func/StatefulPartitionedCall/StatefulPartitionedCall/input/_992"], device = ""} : (tensor<1x320x320x3x!tf.quint8>) -> tensor<1x320x320x3xui8>
```

**Comment by MeghnaNatraj** [comment]
I was able to get this working by running the following code:

```
!pip install tf-nightly
import tensorflow as tf

## TFLite Conversion
model = tf.saved_model.load("saved_model")
concrete_func = model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
concrete_func.inputs[0].set_shape([1, 300, 300, 3])
tf.saved_model.save(model, "saved_model_updated", signatures={"serving_default":concrete_func})
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir='saved_model_updated', signature_keys=['serving_default'])

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()

## TFLite Interpreter to check input shape
interpreter = tf.lite.Interpreter(model_content=tflite_model)
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test the model on random input data.
input_shape = input_details[0]['shape']
print(input_shape)
```

```
[  1 300 300   3]
```

**Comment by hahmad2008** [comment]
@MeghnaNatraj  Thank you so much :) 
I really appreciate it. it works now 👯

**Comment by utkrist-karky** [comment]
Try this: 
`model = tf.saved_model.load("dir/to/model")
concrete_func = model.signatures[
  tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
concrete_func.inputs[0].set_shape([None, 224, 224, 3]) #your input size
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
tflite_model = converter.convert()
with open('model.tflite', 'wb') as f:
  f.write(tflite_model)`

**Comment by creativesh** [comment]
@utkrist-karky
Thanks, your approach worked for me.

**Comment by patrickjdarrow** [comment]
> I was able to get this working by running the following code:
> 
> ```
> !pip install tf-nightly
> import tensorflow as tf
> 
> ## TFLite Conversion
> # Before conversion, fix the model input size
> model = tf.saved_model.load("saved_model")
> model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY].inputs[0].set_shape([1, 300, 300, 3])
> tf.saved_model.save(model, "saved_model_updated", signatures=model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY])
> # Convert
> converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir='saved_model_updated', signature_keys=['serving_default'])
> converter.optimizations = [tf.lite.Optimize.DEFAULT]
> converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
> tflite_model = converter.convert()
> 
> ## TFLite Interpreter to check input shape
> interpreter = tf.lite.Interpreter(model_content=tflite_model)
> interpreter.allocate_tensors()
> 
> # Get input and output tensors.
> input_details = interpreter.get_input_details()
> output_details = interpreter.get_output_details()
> 
> # Test the model on random input data.
> input_shape = input_details[0]['shape']
> print(input_shape)
> ```
> 
> ```
> [  1 300 300   3]
> ```
> 
> Feel free to re-open this if you still face an issue.

When saving the updated SavedModel, the input shape does not persist for me:
> model = tf.saved_model.load("saved_model")
> model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY].inputs[0].set_shape([1, 300, 300, 3])
> tf.saved_model.save(model, "saved_model_updated", signatures=model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY])
> model = tf.saved_model.load("saved_model_updated")
> model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY].inputs[0].shape
> >>> TensorShape([None, None, None, 3])

**Comment by karthik87s** [comment]
@utkrist-karky Your suggestion worked for me. Thanks.

**Comment by Monaco12138** [comment]
> I was able to get this working by running the following code:
> 
> ```
> !pip install tf-nightly
> import tensorflow as tf
> 
> ## TFLite Conversion
> # Before conversion, fix the model input size
> model = tf.saved_model.load("saved_model")
> model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY].inputs[0].set_shape([1, 300, 300, 3])
> tf.saved_model.save(model, "saved_model_updated", signatures=model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY])
> # Convert
> converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir='saved_model_updated', signature_keys=['serving_default'])
> converter.optimizations = [tf.lite.Optimize.DEFAULT]
> converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
> tflite_model = converter.convert()
> 
> ## TFLite Interpreter to check input shape
> interpreter = tf.lite.Interpreter(model_content=tflite_model)
> interpreter.allocate_tensors()
> 
> # Get input and output tensors.
> input_details = interpreter.get_input_details()
> output_details = interpreter.get_output_details()
> 
> # Test the model on random input data.
> input_shape = input_details[0]['shape']
> print(input_shape)
> ```
> 
> ```
> [  1 300 300   3]
> ```
> 
> Feel free to re-open this if you still face an issue.

Thanks, it works for me in tensorflow2.3 . Other verion of tensorflow like 2.8 failed to do that. However, it seems that using  'model = tf.saved_model.load()' is necessary, the model can not be load like keras.models.Model().
