### ISSUE TITLE
autograph fails inside keras model train_step including a for loop over a tensor

### ISSUE THREAD

**Issue by klaimans** [tensorflow/tensorflow#42119]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linus Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): binary (docker image latest-gpu-py3)
- TensorFlow version (use command below): 2.3
- Python version: Python 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: V100

**Describe the current behavior**

When writing a python "for" loop inside a tf.keras.Model.train_step I get the following error:

OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.

The same function works correctly when outside of a keras model but still decorated with tf.function. 

**Describe the expected behavior**

autograph should support iterating over a tensor also inside a keras model

**Standalone code to reproduce the issue**

```
import tensorflow as tf
import numpy as np

t = tf.Variable(0)

@tf.function()
def foo():
    for n in tf.range(tf.constant(10)):
        t.assign_add(n)
    return t

nt = foo()
nt #  <tf.Tensor: shape=(), dtype=int32, numpy=45>

class mymodel(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.t = tf.Variable(0)
    def train_step(self, data):
        for n in tf.range(tf.constant(10)):
            t.assign_add(n)
        return {"loss": t}

mm = mymodel()
mm.compile()
mm.fit(np.random.random((5)), steps_per_epoch=1) # this doesn't work see trace below
```

**Other info / logs** 

OperatorNotAllowedInGraphErrorTraceback (most recent call last)
<ipython-input-18-c68155fbb474> in <module>
----> 1 mm.fit(np.random.random((5)), steps_per_epoch=1)

~usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
    106   def _method_wrapper(self, *args, **kwargs):
    107     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
--> 108       return method(self, *args, **kwargs)
    109 
    110     # Running inside `run_distribute_coordinator` already.

~usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1096                 batch_size=batch_size):
   1097               callbacks.on_train_batch_begin(step)
-> 1098               tmp_logs = train_function(iterator)
   1099               if data_handler.should_sync:
   1100                 context.async_wait()

~usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    778       else:
    779         compiler = "nonXla"
--> 780         result = self._call(*args, **kwds)
    781 
    782       new_tracing_count = self._get_tracing_count()

~usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    821       # This is the first call of __call__, so we have to initialize.
    822       initializers = []
--> 823       self._initialize(args, kwds, add_initializers_to=initializers)
    824     finally:
    825       # At this point we know that the initialization is complete (or less

~usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
    695     self._concrete_stateful_fn = (
    696         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
--> 697             *args, **kwds))
    698 
    699     def invalid_creator_scope(*unused_args, **unused_kwds):

~usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   2853       args, kwargs = None, None
   2854     with self._lock:
-> 2855       graph_function, _, _ = self._maybe_define_function(args, kwargs)
   2856     return graph_function
   2857 

~usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   3211 
   3212       self._function_cache.missed.add(call_context_key)
-> 3213       graph_function = self._create_graph_function(args, kwargs)
   3214       self._function_cache.primary[cache_key] = graph_function
   3215       return graph_function, args, kwargs

~usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   3073             arg_names=arg_names,
   3074             override_flat_arg_shapes=override_flat_arg_shapes,
-> 3075             capture_by_value=self._capture_by_value),
   3076         self._function_attributes,
   3077         function_spec=self.function_spec,

~usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    984         _, original_func = tf_decorator.unwrap(python_func)
    985 
--> 986       func_outputs = python_func(*func_args, **func_kwargs)
    987 
    988       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

~usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    598         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    599         # the function a weak reference to itself to avoid a reference cycle.
--> 600         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    601     weak_wrapped_fn = weakref.ref(wrapped_fn)
    602 

~usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    971           except Exception as e:  # pylint:disable=broad-except
    972             if hasattr(e, "ag_error_metadata"):
--> 973               raise e.ag_error_metadata.to_exception(e)
    974             else:
    975               raise

OperatorNotAllowedInGraphError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:806 train_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:789 run_step  **
        outputs = model.train_step(data)
    <ipython-input-12-62f0dcb0797d>:6 train_step
        for n in tf.range(tf.constant(10)):
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:503 __iter__
        self._disallow_iteration()
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:496 _disallow_iteration
        self._disallow_when_autograph_enabled("iterating over `tf.Tensor`")
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:474 _disallow_when_autograph_enabled
        " indicate you are trying to use an unsupported feature.".format(task))

    OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.

**Comment by klaimans** [comment]
any update on this?

**Comment by ravikyram** [comment]
@klaimans 

Could you please check [this comment](https://github.com/tensorflow/tensorflow/issues/33308#issuecomment-542565633) from a similar issue and let us know if it works? Thanks!

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3, nightly version (`2.4.0-dev20200831`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/9f6070bd493f21cff47d50d2a43e630b/untitled283.ipynb). Thanks!

**Comment by klaimans** [comment]
@jvishnuvardhan 

any updates on this? The above suggestion from @ravikyram did not resolve the issue.

**Comment by jvishnuvardhan** [comment]
@klaimans Sorry for the late response. Can you please add @tf.function as shown below.

```
class mymodel(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.t = tf.Variable(0)
    @tf.function()
    def train_step(self, data):
        for n in tf.range(tf.constant(10)):
            self.t.assign_add(n)
        return {"loss": self.t}

```

With the above modification, everything worked as expected. Please take a look at the gist [here](https://colab.research.google.com/gist/jvishnuvardhan/ee83104a1f5d8263f10f96570df3a99d/untitled283.ipynb). Thanks!

Also, I guess you need to replace `t` with `self.t` as I updated above. Thanks!

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by klaimans** [comment]
@jvishnuvardhan, thank you very much for your reply. Indeed I had a small typo in the example code but this was not responsible for the error I saw. 

The reason seems to be the specific decoration of the train_step method with @tf.function. This is in contrast to the documentation under https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit and https://www.tensorflow.org/api_docs/python/tf/keras/Model#test_step where it specifically says: 

"Configuration details for how this logic is run (e.g. tf.function and tf.distribute.Strategy settings), should be left to Model.make_train_function, which can also be overridden."

Without the decoration I still get the same error as before. Did I misunderstand the documentation in this case?

**Comment by jvishnuvardhan** [comment]
@klaimans Forgot to delete part of the gist. Please check [this gist](https://colab.research.google.com/gist/jvishnuvardhan/5d73b1a5af3dd9674ee0f91f9521125c/untitled283.ipynb) which shows same result with or without tf.function. Please let me know what you think? Thanks!

**Comment by klaimans** [comment]
@jvishnuvardhan 

It still fails for me without the explicit tf.function decorator when running tensorflow inside a docker container using the tensorflow/tensorflow:latest-gpu-jupyter image (tf version 2.3.0). I also tried using the nightly version on my mac and that fails as well with the same error (version '2.4.0-dev20200926').

Now for the interesting part, directly on the Ubuntu Server it seems to work (although I have a mismatch in cuda versions 10.0 vs 10.1 which is required for the current version). I tried with nightly ('2.4.0-dev20200928'), 2.3 and 2.3.1. Any ideas?

**Comment by jvishnuvardhan** [comment]
@klaimans I am not sure about the docker build but I ran the same code that I shared above on my Mac and it runs and output same results from the two models. My TF version is `'2.4.0-dev20200819'` Thanks!

**Comment by klaimans** [comment]
@jvishnuvardhan 

I finally found the difference between our tests. In your last gist (where it runs without the decorator) you changed the original example so that the **for loop** iterates over the python object **range(10)** rather than the original **tf.range(tf.constant(10))** which is what leads to the issue and the original error I reported above. Changing back to the original example leads to the original issue. Thanks!

**Comment by jvishnuvardhan** [comment]
@klaimans Please close the issue if this was resolved for you. Thanks!

**Comment by klaimans** [comment]
@jvishnuvardhan

I have to admit I am a bit confused. The recommendation is to use tf.range(tf.constant(10)) but this leads to an autograph failure. Are you saying we should use range? Wouldn't this lead to retracing? And why does it work for functions outside a keras model and only fails there?

**Comment by nikitamaia** [comment]
Hi @klaimans, just to clarify, it seems that the following works:

```
class mymodel(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.t = tf.Variable(0)
    @tf.function()
    def train_step(self, data):
        for n in tf.range(tf.constant(10)):
            self.t.assign_add(n)
        return {"loss": self.t}
```

So, the main question here is why @tf.function is necessary when customizing `train_step` and using `model.fit` since the docs seem to imply that is not necessary. Am I summarizing correctly?

**Comment by klaimans** [comment]
Hi @nikitamaia, yes that is exactly correct.

**Comment by rubirah** [comment]
Sorry, but I am facing quite a similar problem and I didn't manage to solve it just by the solutions provided here.

**Describe the current behavior**
I am trying to call a c++ function through _cython_ inside each training step of tf. My cython function takes an array as input, transforms it into a c++ vector and calculates a c++ function that takes this vector as input. When Tensorflow calls the cython function in the training phase, it passes a tf.Tensor as parameter (basically because it vectorizes the function for many calls). Therefore, when I try to set c++ vector = tf.tensor it complains saying that I am iterating over `tf.Tensor`

**Describe the expected behavior**
I wish I could vectorize with my "for" in cython with no problems.

**My codes**

wrapper.pyx
```
cdef extern from "eft.h":
    double integrand_1l(double * c_array)

def integrand_1d_python(array_test):
    output = []
    cdef Py_ssize_t i
    cdef Py_ssize_t n = array_test.shape[0]
    cdef double [2] c_array
    for i in tf.range(n):
        c_array = array_test[i]
        output.append(integrand_1l(c_array) )
    return output 
```

file.py in which I train the NN
```
class TestFunctions:

    def __init__(self, ndims, alpha, **kwargs):
        self.ndims = ndims
        self.alpha = alpha
        self.variables = kwargs
        self.calls = 0

    def loop1(self, x):
        self.calls += 1 
        my_new_temp = tf.cast(wrapper.integrand_1d_python(x), dtype=tf.float64) 

        return my_new_temp

```
**The log I get: (same as @klaimans )**

OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.

**What I have tried so far (with no success)**
- adding @tf.function()
- transform from vector to numpy array
- using tf.map_fn

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/f962f871d13e99593d845c26171e3f75/untitled102.ipynb)..Thanks !

**Comment by yang-stressfree** [comment]
Same problem here.

When decorating train_step with `@tf.function` and run on CPU, the model.fit works fine.

But when train on multi-GPU with `tf.distribute.MirroredStrategy`, the train_step with `@tf.function` will cause error:

_RuntimeError: `merge_call` called while defining a new graph or a tf.function. This can often happen if the function `fn` passed to `strategy.run()` contains a nested `@tf.function`, and the nested `@tf.function` contains a synchronization point, such as aggregating gradients (e.g, optimizer.apply_gradients), or if the function `fn` uses a control flow statement which contains a synchronization point in the body. Such behaviors are not yet supported. Instead, please avoid nested `tf.function`s or control flow statements that may potentially cross a synchronization boundary, for example, wrap the `fn` passed to `strategy.run` or the entire `strategy.run` inside a `tf.function` or move the control flow out of `fn`. If you are subclassing a `tf.keras.Model`, please avoid decorating overridden methods `test_step` and `train_step` in `tf.function`._ 

This error said:

> please avoid decorating overridden methods `test_step` and `train_step` in `tf.function`

if we remove `@tf.function` from train_step, we will get error like:

_OperatorNotAllowedInGraphError: iterating over tf.Tensor is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature._

This is extremely confusing...

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
