### ISSUE TITLE
Tensorflow getting stuck when running forward pass for a tf hub module

### ISSUE THREAD

**Issue by perone** [tensorflow/tensorflow#42126]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Catalina 10.15.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version (use command below): v2.3.0-rc2-23-gb36436b087 2.3.0
- Python version: 3.6.4
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: using on CPU
- GPU model and memory: using on CPU

**Describe the current behavior**
Tensorflow get stuck, it hangs suddenly and intermittently

**Describe the expected behavior**
Tensorflow not getting stuck

**Standalone code to reproduce the issue**
```
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text

module = hub.load("https://tfhub.dev/google/universal-sentence-encoder-multilingual-qa/3")
for i in range(50):
    response_embeddings = module.signatures['response_encoder'](
        input=tf.constant(["I am happy", "I am not happy"]),
        context=tf.constant(["I am happy", "I am not happy"]))
    t = response_embeddings["outputs"].numpy()
    print(t.shape)
```
If you repeat that last loop of 50 iterations like 3 times or something it will just get stuck and hang.

**Comment by ravikyram** [comment]
@perone 

I have tried in colab with TF version 2.3 and i am not seeing any issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/3bd590659765b397f6c993f074bfa775/untitled.ipynb).Thanks!

**Comment by perone** [comment]
If it is working on Colab, it looks that it might be something related to environment or resources, since it is a big model, it might be memory management, are there any debugging flags I can enable to get more verbose info on what is going on ? I understand it doesn't reproduce on Colab, but that is like "works on my computer". 

This is the log I get on the first run of the loop:

```
2020-08-12 16:03:37.207634: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-08-12 16:03:37.262803: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f854448af90 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-12 16:03:37.262836: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
```

it allocates 922MB of memory, and then the process just get stuck (no CPU usage).

**Comment by ravikyram** [comment]
@perone 

Issues related to TensorFlow Hub are handled in the Hub repo. Please submit a new issue using [this link](https://github.com/tensorflow/hub/issues/new) and fill in the template, so that we can track it there. Thanks!
