### ISSUE TITLE
No documentation on how to profile the memory usage for TF

### ISSUE THREAD

**Issue by Remit** [tensorflow/tensorflow#42123]
Hello,

## URL(s) with the issue:

https://www.tensorflow.org/guide/profiler#memory_profile_tool

### Clear description

TF profiler only outputs the CPU information with the default configuration, but I was not able to find neither in the documentation nor on the StackOverflow etc. how to set it up for monitoring the memory usage.

I get only this message on the "memory_profile" tools page:
"There is no memory profile to display because there were no memory activity data in the captured duration. "

TF and tensorboard versions are both 2.3.0.
Profiling is run on the machine without GPU, under the non-root user, in Jupyter Notebook.

### Usage example

No code example for the memory profiling is provided, hence it is not clear whether some setting should be provided to the profiler.

**Comment by maurice-g** [comment]
Experiencing same issue on CPU. With GPU it does show the "summary information" correctly, but the memory breakdown table doesn't contain meaningful entries.
<img width="1161" alt="Screenshot 2020-08-07 at 14 55 25" src="https://user-images.githubusercontent.com/2892585/89647615-1f601d80-d8be-11ea-83a6-1f305c29fa48.png">

**Comment by MarkDaoust** [comment]
@anirudh161 you've been working on docs for these, any ideas?

**Comment by ckluk-github** [comment]
This tool reports memory consumption on the device (i.e. GPU or TPU); not on the host (CPU).

For the GPU issue (no breakdown to TF Ops), this is a bug that we found and fixed after TF 2.3 release. You will need to get the latest TF (https://pypi.org/project/tf-nightly/). You don't need a newer profiler plugin (i.e. the TF 2.3 release is okay).

**Comment by Remit** [comment]
> This tool reports memory consumption on the device (i.e. GPU or TPU); not on the host (CPU).
> 
> For the GPU issue (no breakdown to TF Ops), this is a bug that we found and fixed after TF 2.3 release. You will need to get the latest TF (https://pypi.org/project/tf-nightly/). You don't need a newer profiler plugin (i.e. the TF 2.3 release is okay).

Thanks a lot for clarifying this!

**Comment by kunalkukreja21** [comment]
@ckluk-github how to profile memory on the CPU host?
