### ISSUE TITLE
How to implement Multiplexer

### ISSUE THREAD

**Issue by zsdonghao** [tensorflow/tensorflow#4212]
How to takes a single input and select one of many output lines, which is connected to the input, by using placeholder?

For example if we have a TF variable as follow, how could we forward it to the 1st output ?

```
intputs = tf.constant(0.2, shape=[2, 2])
sel = tf.placeholder(tf.int32)
n_out = 3
out = xxxx(sel, inputs, n_out)  # here

sess.run(out, feed_dict = {sel: 0}) 
# [[[0.2, 0.2],[0.2, 0.2]], 
   [[0, 0],[0, 0]], 
    [[0, 0],[0, 0]]]

```

**Comment by tatatodd** [comment]
We primarily use github issues to track bugs and installation issues.  This is a question better suited for StackOverflow.  Please ask it there and tag it with the `tensorflow` tag.  Thanks!
