### ISSUE TITLE
Add __name__ property to optimizer classes

### ISSUE THREAD

**Issue by naivoder** [tensorflow/tensorflow#42128]
**System information**
- TensorFlow version (you are using): 1.15.3
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Add __name__ property to optimizer classes (and potentially others) for easy access at runtime. 

Current behavior:
`opt = SGD()`
`opt.__name__`
AttributeError: 'Adam' object has no attribute '__name__'

Suggested behavior: 
`opt = SGD()`
`opt.__name__`
"SGD"

**Will this change the current api? How?**

Will allow quick access to class name as string.

**Who will benefit with this feature?**

Researchers compiling results from models using several different optimizers. 

**Any Other info.**

**Comment by FirefoxMetzger** [comment]
`type(opt).__name__` ?

```
import tensorflow as tf
opt = tf.keras.optimizers.SGD()
print(type(opt).__name__)  # prints: SGD
```
