### ISSUE TITLE
tflite runtime package compatibility for Raspeberry Pi

### ISSUE THREAD

**Issue by Vinay-Rao** [tensorflow/tensorflow#42122]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspbian GNU/Linux 10(buster)
- TensorFlow installed from (source or binary):
- Tensorflow version (commit SHA if source):
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Raspberry Pi Model B Rev 2

**Describe the problem**
I have an old Raspberry Pi, probably one of the first model they released. It as an ARMv6-compatible processor rev 7, BCM2835. It is RPi Model B Rev 2

I get the error : **tflite_runtime-2.1.0.post1-cp37-cp37m-linux_armv7l.whl is not a supported wheel on this platform**

**Please provide the exact sequence of commands/steps when you ran into the problem**

1. Installed latest version of python, pip-20.2.1 wheel-0.34.2, Python3.7
2. Installed OpenCV
`sudo apt-get -y install libjpeg-dev libtiff5-dev libjasper-dev libpng12-dev
sudo apt-get -y install libavcodec-dev libavformat-dev libswscale-dev libv4l-dev
sudo apt-get -y install libxvidcore-dev libx264-dev
sudo apt-get -y install qt4-dev-tools libatlas-base-dev
pip3 install opencv-python==3.4.6.27`

3. Tried installing https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_armv7l.whl and https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_aarch64.whl (as given in https://www.tensorflow.org/lite/guide/python) gives the same error **_*.whl is not a supported wheel on this platform_**
![image](https://user-images.githubusercontent.com/64406245/89629896-d8166480-d89e-11ea-9735-53e8fa80ccf6.png)

Please let me know if TF Lite runtime package is supported on this platform.

**Comment by ymodak** [comment]
Perhaps you can try [Building TensorFlow Lite Standalone Pip](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package#building-tensorflow-lite-standalone-pip).

**Comment by Vinay-Rao** [comment]
Trying the first method in the link, build in progress - `tensorflow/lite/tools/pip_package/build_pip_package.sh`. It is taking more time than I thought, probably since the RPi processor is slow.

In the process of getting this script to build, realized, I was missing another wheel related tool, had to do `pip3 install wheel`. May be it will help the initial pip3 install of the .whl file I was trying. Not sure, need to check.
 
Hope to update soon on the Standalone Pip

**Comment by Vinay-Rao** [comment]
Build is stuck (Raspberrypi hangs), with the first method, tried it a couple of times. It is as shown in the image below from past 4 hours. 
![image](https://user-images.githubusercontent.com/64406245/90140355-eb7f6f00-dd79-11ea-8e23-68ae2dfdfcd4.png)

Do you suggest any other method?

**Comment by terryheo** [comment]
You'd better cross build TFLite PIP since it requires more RAM than you have.
Regarding RPI Zero (or armv6 support), we don't have PIP supports yet.
But you can build the static library https://www.tensorflow.org/lite/guide/build_rpi#step_4b_to_build_armv6_binary_for_raspberry_pi_zero

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
