### ISSUE TITLE
keras.models.load_model fails after tf.reset_default_graph OR tf.keras.backend.clear_session

### ISSUE THREAD

**Issue by mkravchik** [tensorflow/tensorflow#42121]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.15.0-rc3-22-g590d6eef7e 1.15.0
- Python version: Python 3.6.2 |Anaconda custom (64-bit)| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bit (AMD64)] on win32
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1.243/6.14.11.10010
- GPU model and memory: GeForce GTX 960M 3040 MB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
The second load_model fails with error "Cannot interpret feed_dict key as Tensor: Tensor Tensor("Placeholder:0", shape=(40, 80), dtype=float32) is not an element of this graph."

**Describe the expected behavior**
I expect the model to be loaded, exactly like in the first call 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
    import tensorflow as tf
    from keras.models import load_model

    model = load_model("model.h5")
    model.summary()

    # tf.reset_default_graph() OR
    tf.keras.backend.clear_session()

    model = load_model("model.h5")
    model.summary()

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@mkravchik,
Please take a look at [this](https://stackoverflow.com/a/47162390) StackOverflow comment from a similar issue and let us know if it helps. Thanks!

**Comment by mkravchik** [comment]
Well, no exactly.
Debugging revealed that the problem is that Keras uses the default session if it exists and if some initialization was done on this session resetting the graph causes the Keras's confusion  because it is expecting that the session state will not change and the session's graph will not be reset. I haven't seen neither of this in the documentation and it caused me to spend a few hours on this issue. 
So if I want to load the model and then use it multiple times with calls to reset_default_graph in between, I need to keep the session with the graph around like this:
```
def load():
    with tf.Graph().as_default() as g:
        config = tf.ConfigProto(log_device_placement=False)
        config.gpu_options.allow_growth = True
        sess = tf.Session(graph=g, config=config)
        with sess.as_default():
            model = load_model("model.h5")
            model.summary()
            X = np.random.normal(0, 1, (20,2))
            pred = model.predict(X[np.newaxis])
            print(pred)

            return model, sess

model, sess = load()

with sess.as_default():
    X = np.random.normal(0, 1, (20, 2))
    pred = model.predict(X[np.newaxis])
    print(pred)
```

I still think this is not how I expect Keras's load_model to behave

**Comment by amahendrakar** [comment]
@mkravchik,
I was able to run the given code snippet with a sample `.h5` file, without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/75e3f3c27c6f90b91a18b84ec8fd7b1e/42121.ipynb). Thanks!
