### ISSUE TITLE
tf.keras.callbacks.TensorBoard does not save batch - level statistics when profiling is disabled completely

### ISSUE THREAD

**Issue by Zahlii** [tensorflow/tensorflow#42139]
During profile setup, _should_trace is set to false.

https://github.com/tensorflow/tensorflow/blob/b36436b087bd8e8701ef51718179037cccdfc26e/tensorflow/python/keras/callbacks.py#L2137

However, during the batch begin, this is also used:
https://github.com/tensorflow/tensorflow/blob/b36436b087bd8e8701ef51718179037cccdfc26e/tensorflow/python/keras/callbacks.py#L2160

Thus, disabling profiling ALSO disables batch level outputs.

**Comment by jvishnuvardhan** [comment]
@Zahlii Can you please share a simple standalone code to reproduce the issue? Thanks!

**Comment by nikitamaia** [comment]
Hi @Zahlii, do you have a reproducible example you can share? This helps us to debug. Thanks!

**Comment by Zahlii** [comment]
I wasn't able to reproduce the issue with the latest tensorflow version. I think this can be closed.
