### ISSUE TITLE
FCNs cannot be used for segmentation of variable size images after training.

### ISSUE THREAD

**Issue by Huxwell** [tensorflow/tensorflow#4213]
Yann LeCun pointed,  ConvNets don't need to have a fixed-size input.
One can train Fully-convolutional network using small images, and than use the model (without scaling or cropping) and feed it with large images for segmentation.
It works right away with Keras+Theano.
If one trains the same model with TensorFlow as Keras'es backend, during application of pretrained model on image larger than the images used for training, he will get A ValueError due to tensor shape mismatch (same for manual model definition directly in TF).

The shape check needs to be disabled and the convolution layers need to work properly with variable size during model using/testing phase if the framework is to be competitive.
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

https://www.facebook.com/yann.lecun/posts/10152820758292143
http://stackoverflow.com/questions/39050557/fully-convolutional-network-training-image-size
https://www.quora.com/How-does-the-conversion-of-last-layers-of-CNN-from-fully-connected-to-fully-convolutional-allow-it-to-process-images-of-different-size 
http://tutorial.caffe.berkeleyvision.org/caffe-cvpr15-pixels.pdf
### Environment info

Operating System:  Ubuntu 14.04.4 LTS 
Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
[cuda_config.txt](https://github.com/tensorflow/tensorflow/files/455666/cuda_config.txt)
### Error log:

ValueError: Cannot feed value of shape (1, 3, 350, 600) for Tensor u'convolution2d_input_2:0', which has shape '(?, 3, 15, 15)'

**Comment by tatatodd** [comment]
Thanks for the note @Huxwell!

@sherrym might have an opinion on this, or know the right person to redirect this to.

**Comment by jeandut** [comment]
It seems to me you can simply use a placeholder with undefined shape at least this is what I am doing and it works:  x=tf.placeholder(tf.float32,[None,None,None,3],name="input_network"). Not very memory efficient I suppose but it works.

**Comment by jeandut** [comment]
But possibly not if different sized images are in the same batch, never tried.

**Comment by jeandut** [comment]
However for the first part of your question it works as you use same shape inputs for training batches. It is only during inference that you feed different sized batches.

**Comment by Huxwell** [comment]
I am testing it right now, rewriting my models from keras to tensorflow, but it's gonna take some time due to CUDNN problems, and I'll post results as soon as I have them

**Comment by drpngx** [comment]
@Huxwell how did that go?

**Comment by Huxwell** [comment]
Changing input size manually in the exported .json file with the model architecture and using it with the same weights in different file works OK with me.

**Comment by drpngx** [comment]
Great to hear!
