### ISSUE TITLE
how to make tensorflow2.1.0 to rpm ，or even have some git  link can also

### ISSUE THREAD

**Issue by lzb-James** [tensorflow/tensorflow#42145]
I want to build tensorflow to rpm is there have any tools to compile ?

Thank U very much

**Comment by Saduf2019** [comment]
@ibz-james
Please refer to [this link](https://www.tensorflow.org/install/source) and confirm once done.

**Comment by lzb-James** [comment]
> @ibz-james
> Please refer to [this link](https://www.tensorflow.org/install/source) and confirm once done.
Thank you but i don`t want to install tf by pip wheel ,I want to make the source code to rpm . for linux like centos7

**Comment by Saduf2019** [comment]
@lzb-James 
Please refer to this [link for build from source](https://www.tensorflow.org/install/source) and let us know.
