### ISSUE TITLE
Keras plot_model bug when rendering to svg

### ISSUE THREAD

**Issue by PaulPauls** [tensorflow/tensorflow#42150]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.7.7

**Describe the current behavior**
The tf.keras.utils.plot_model() function (and by extension the tf.keras.utils.model_to_dot() function) when specifying the file extension as svg creates an svg with an incorrectly set 'view'. Only the view is incorrect, as the model is correctly plotted, just partly outside the visible range. 
The reason for this bug is that the dpi standard value of 96 prevents graphviz from figuring out the correct svg view window itself. If the dpi is set to 'None', graphviz figures out the correct view. I am uncertain if this bug also occurs with other vector graphic formats, I however tested it with pdfs and it seemed fine.

Graphviz is set to figure out the correct dpi by itself anyway and applies standard values as 96 to bitmap formats by default [1]. Offering a standard value in the keras plot_model function overwrites that functionality.
The problem can be solved by setting the dpi default value in the plot_model/model_to_dot function to None and letting graphviz figure out the correct dpi; or by checking for edge cases when converting to special formats such as svg. As I am unaware of the default-value policy of tensorflow did I not want to create an unnecessary pull request, though I would gladly help in the bug fix [2].

[1] https://graphviz.org/doc/info/attrs.html#d:dpi
[2] mail@paulpauls.de

**Standalone code to reproduce the issue**

The code is not reproducible within a jupyter notebook / Google colab, as IPython does not support svg display. Therefore am I attaching minimal reproducing code below:

```
import tensorflow as tf
from tensorflow.keras import models, layers

print(tf.__version__)

model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))

tf.keras.utils.plot_model(model, to_file='./model.png')

tf.keras.utils.plot_model(model, to_file='./model_96DPI.svg')

tf.keras.utils.plot_model(model, to_file='./model_NoneDPI.svg', dpi=None)
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/97522b7a131ac82284ab0fa91ce99a03/42150.ipynb#scrollTo=W3EvU_efS0lS) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/6b728ee61d04e9dc2196c06b601e3534/42150.ipynb). Please find the attached gist. 

Saving the image as `svg` throws a `ValueError`, but the image is saved on disk.

- Output of `plot_model(model, to_file='./model_96DPI.svg')`
![model_96DPI](https://user-images.githubusercontent.com/57165142/89752025-36865180-daf0-11ea-9225-621f73dcf35d.png)

- Output of `plot_model(model, to_file='./model_NoneDPI.svg', dpi=None)`
![model_NoneDPI](https://user-images.githubusercontent.com/57165142/89752079-78af9300-daf0-11ea-8ef3-191533278871.png)


Thanks!

**Comment by Saduf2019** [comment]
I could reproduce the issue with TF 2.5 .Please, find the gist [here](
https://colab.research.google.com/gist/Saduf2019/4ce54a15776dfb50c0096c200ce65bc0/untitled589.ipynb).Thanks!

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF 2.6.0-dev20210529,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/7211a26c91ceff1c16959305566b9cc8/untitled99.ipynb#scrollTo=5kAfupf3TM2z)..Thanks !

**Comment by gowthamkpr** [comment]
@PaulPauls SVG format is not the first-class citizen like png and jpeg. Would recomment using jpeg or png. If you still this this is an issue, please create an issue in [keras-team/keras](https://github.com/keras-team/keras/issues/new/choose) as the development of keras has been moved to a new repo. Thanks!
