### ISSUE TITLE
floating point exception in `tf.nn.atrous_conv2d` when there is 0 in filters.shape

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#42152]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.6.9
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
`tf.nn.atrous_conv2d` throws floating point exception when the shape of `filters` is `[0,*,*,*]`, or there is `0` in the first three dimension of the shape, e.g. `[*,0,*,*]. [*,*,0,*]`

**Describe the expected behavior**
Expect no floating point exception

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
~~~python
import tensorflow as tf
tf.nn.atrous_conv2d(filters=tf.ones((0,1,1,1)), value=tf.ones((1,1,1,1)), rate=1, padding="SAME")
tf.nn.atrous_conv2d(filters=tf.ones((1,0,1,1)), value=tf.ones((1,1,1,1)), rate=1, padding="SAME")
tf.nn.atrous_conv2d(filters=tf.ones((1,1,0,1)), value=tf.ones((1,1,1,1)), rate=1, padding="SAME")
~~~
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
~~~python
Floating point exception (core dumped)
~~~

**Comment by Saduf2019** [comment]
Colab crashes when the code is run on it.

**Comment by rmothukuru** [comment]
@DNXie,
Sorry for the delayed response. When tried to reproduce your code in [Colab](https://colab.research.google.com/gist/rmothukuru/3ae57aa459e26ab8510f7d8a24c2095b/gh_42152.ipynb), it is **crashing**, instead of the **`Floating Point Exception`** that you mentioned. Can you please help us to reproduce your issue? Thanks!

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210529 in colab & it  crashes,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/48e57901256f81051ebef4e5555bceea/untitled98.ipynb)..Thanks !

**Comment by yongtang** [comment]
I believe this issue has been fixed with the latest nightly. Now an error message is thrown (instead of crash):

```
$ python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.nn.atrous_conv2d(filters=tf.ones((0,1,1,1)), value=tf.ones((1,1,1,1)), rate=1, padding="SAME")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: filter must not have zero elements (i.e. all dimensions must be non-zero) [Op:Conv2D]
>>> tf.nn.atrous_conv2d(filters=tf.ones((1,0,1,1)), value=tf.ones((1,1,1,1)), rate=1, padding="SAME")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: filter must not have zero elements (i.e. all dimensions must be non-zero) [Op:Conv2D]
>>> tf.nn.atrous_conv2d(filters=tf.ones((1,1,0,1)), value=tf.ones((1,1,1,1)), rate=1, padding="SAME")
2021-08-18 16:39:22.851505: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at conv_ops.cc:666 : INVALID_ARGUMENT: filter depth must be stricly positive, got 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: filter depth must be stricly positive, got 0 [Op:Conv2D]
>>> 
```

This issue can be closed now.

**Comment by yongtang** [comment]
Close as the issue has been resolved in the latest nightly build. Please feel free to re-open if the issue persists.
