### ISSUE TITLE
 ValueError: No gradients provided for any variable

### ISSUE THREAD

**Issue by tianhuat** [tensorflow/tensorflow#42167]
For the code

    import  tensorflow as tf
    
    y_N= tf.Variable([1., 2., 3.],name="dd")
    cost = -tf.reduce_mean(input_tensor=tf.reduce_sum(input_tensor=tf.math.log(y_N), axis=0))
    
    loss=lambda:cost
    
    train_step = tf.keras.optimizers.Adam(0.5).minimize(loss, var_list=[y_N])

I got error

    ValueError: No gradients provided for any variable: ['dd:0'].

**Comment by WindQAQ** [comment]
You have to put the computation inside lambda so that it fits in the scope of `GradientTape`.

```python
import  tensorflow as tf

y_N= tf.Variable([1., 2., 3.],name="dd")

loss=lambda: -tf.reduce_mean(input_tensor=tf.reduce_sum(input_tensor=tf.math.log(y_N), axis=0))

train_step = tf.keras.optimizers.Adam(0.5).minimize(loss, var_list=[y_N])
```

https://colab.research.google.com/drive/1dOxkRdJ2GY31hC7S1rqs00H0Ft26fLBe?usp=sharing

**Comment by Saduf2019** [comment]
@tianhuat 
I ran the code with the changes and do not face any error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/2ae0717ccd683507d63bd59b7048a7a8/untitled356.ipynb)

**Comment by tianhuat** [comment]
Thanks, it works.
