### ISSUE TITLE
looking for libcudart.so.10 when  libcudart.so.11 installed

### ISSUE THREAD

**Issue by iplayfast** [tensorflow/tensorflow#42162]
using anacoda
setting enviroment,
installing pip
using pip to install tensorflow
testrun
python
import tensorflow as tf
gives error 

2020-08-08 23:41:49.327601: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-08-08 23:41:49.327623: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

so I dutifully went to nvidia and installed cuda.
Trying again give same error.

using updatedb and locate I found 
the following instances.

/usr/local/cuda-11.0/doc/man/man7/libcudart.so.7
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudart.so.11.0
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudart.so.11.0.221

so it looks like Nvidia has a newer version out then whats been looked at.

I'm not sure who's error this is, if it's not yours please redirect me to whomever it is. thanks

**System information**
linux mint 20,

**Comment by amahendrakar** [comment]
@iplayfast,
CUDA 11 compatibility with TensorFlow is currently a work in progress.

Please try installing TensorFlow with CUDA 10.1 and cuDNN 7.6 as per the [tested build configurations](https://www.tensorflow.org/install/source#gpu) and let us know if you are facing the same issue. Thanks!

**Comment by iswarup** [comment]
@iplayfast 
[tensorflow-nightly-gpu](https://pypi.org/project/tf-nightly-gpu/) was released yesterday!
CUDA-11 support is here!

**Comment by amahendrakar** [comment]
@iplayfast,
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by versusnja** [comment]
I follow this guide and it helped to build from source: https://towardsdatascience.com/how-to-compile-tensorflow-2-3-with-cuda-11-1-8cbecffcb8d3

Edit `third_party/gpus/cudas_configure.bzl`
Replace with "11.0" string

```"cudart": _check_cuda_lib_params(
    "cudart",
    cpu_value,
    cuda_config.config["cuda_library_dir"],
    # Comment this out since cudart is still on 11.0 instead of
    # the same as cuda 11.1
    # cuda_config.cuda_version,
    "11.0"
    static = False,
),
"cudart_static": _check_cuda_lib_params(
    "cudart_static",
    cpu_value,
    cuda_config.config["cuda_library_dir"],
    # Comment this out since cudart is still on 11.0 instead of
    # the same as cuda 11.1
    # cuda_config.cuda_version,
    "11.0"
    static = True,
),```
