### ISSUE TITLE
Update TensorFlow docs for a11y

### ISSUE THREAD

**Issue by 8bitmp3** [tensorflow/tensorflow#42168]
### Description:

Hey @lamberta @MarkDaoust @yashk2810, 

I've put together a few small commits to update the TensorFlow docs for more inclusive language. It's to do with ~~”Native”~~ -> “Built-in”. (Source: an a11y [presentation](https://docs.google.com/presentation/d/1UVHzuMo5Ef1zUCZ3qdFwDQh-aVHpkYnY73TrJ2yHt3E/edit#slide=id.g6fe49527a0_0_334) by @heyawhite—a tech writer at Google). 

[Link to diffs](https://github.com/tensorflow/docs/compare/master...8bitmp3:master).

If you're OK with these changes, I can submit a PR.

### Submit a pull request?

Yes, can do

### Affected docs:

- TF testing best practices guide
- TensorFlow (R1) C++ API guide
- TF 1.x Eager mode notebook
- TensorFlow Customization basics notebook
- Build TensorFlow on Windows guide
- TensorFlow 2 migration notebook
- tf.function notebook
- TF create an op in C++ guide
- TF (R1) Adding a new op in C++ guide

**Comment by lamberta** [comment]
Hi @8bitmp3 

Yes, for the most part this looks like a great change. Take a look through the Google dev docs style guide for inclusive language: https://developers.google.com/style/inclusive-documentation

But will need to make sure the context fits and it remains technically accurate. For example, "native code" has a meaning that "built-in" might not account for.

**Comment by lamberta** [comment]
Would also be useful to add some of these words to the `nblint` style module for Google dev docs: https://github.com/tensorflow/docs/blob/master/tools/tensorflow_docs/tools/nblint/style/google.py

**Comment by lamberta** [comment]
Added an inclusive language check to `nblint` (https://github.com/tensorflow/docs/commit/1dd9809aaeaab958acd847ae29b4de87c79668fe). Can now use this to find issues in notebooks (wordlist should be easy to update). It's also part of the CI on the tensorflow/docs repo.

```
$ python3 -m pip install -U --user git+https://github.com/tensorflow/docs

# Accepts notebooks or directories as arguments
$ python3 -m tensorflow_docs.tools.nblint --arg=repo:tensorflow/docs notebook.ipynb
```

**Comment by jpoehnelt** [comment]
Also see https://github.com/apps/in-solidarity. I wrote it last week and have it running on the googlemaps org right now.

**Comment by 8bitmp3** [comment]
> Added an inclusive language check to nblint (tensorflow/docs@1dd9809). 

@lamberta Nice one. For the wordlist in `nblint` (`/tools/tensorflow_docs/tools/nblint/style/google.py`), what do think about these:

“turn on” -> “toggle (the) on (switch)”
“first class” -> “feature, built-in, top-level”
“cripple” -> “negatively impact”
“simply” -> False (Jim Fisher’s Don’t Say Simply)
“as you can see” -> False
“see” -> “go to”

This is more challenging:
“enable” -> “toggle/switch on" or "allow”
“disable” -> “toggle/switch off" or "disallow”
(also "enabled" and "disabled")

cc @jpoehnelt @heyawhite

**Comment by lamberta** [comment]
Makes sense. We should create separate lint checks to distinguish between inclusive language versus regular ole' unclear language. Ideally, every lint rule can link to a page in the [Google Dev Docs Style Guide](https://developers.google.com/style/highlights).

**Comment by lamberta** [comment]
Closing this issue since work was done and there's no specific action item left. Thanks
