### ISSUE TITLE
Difference between TF2.3 and TF2.2[MKL]

### ISSUE THREAD

**Issue by electricSamarth** [tensorflow/tensorflow#42164]
I am working on project and we are trying to make TF use functions that we have written, these functions are there in the form of a .so file, we managed to get Tensorflow2.2 to use our MatMul function, but it stopped working for TF2.4. We achieved our aim in TF2.2 by using LD_PRELOAD, Any guesses as to why this has happened. An important detail is that both of these TF environments we built from source with MKL support (--config=mkl)
Also these are the function defined inside our .so file (nm command on the .so file, screenshot)

**Comment by electricSamarth** [comment]
> I am working on project and we are trying to make TF use functions that we have written, these functions are there in the form of a .so file, we managed to get Tensorflow2.2 to use our MatMul function, but it stopped working for TF2.4. We achieved our aim in TF2.2 by using LD_PRELOAD, Any guesses as to why this has happened. An important detail is that both of these TF environments we built from source with MKL support (--config=mkl)
> Also these are the function defined inside our .so file (nm command on the .so file, screenshot)

![Screenshot from 2020-08-08 21-38-06](https://user-images.githubusercontent.com/44555985/89737985-d8775100-da92-11ea-9853-04c082583e95.png)

**Comment by electricSamarth** [comment]
@penpornk can you help please?

**Comment by agramesh1** [comment]
I am assuming you are providing your own implementation of cblas_gemm. We made some changes between 2.2 and 2.3 and no longer call clbas_gemm, instead we use dnnl_sgemm.  If you want to TF+MKL to use cblas_gemm you have to change the code.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/mkl/mkl_matmul_op.cc#L174  and recompile. Note, we will removing the cblas calls soon.

**Comment by electricSamarth** [comment]
If you will be removing Cblas, then what will it be repalced by?.... Thanks! for the reply

**Comment by electricSamarth** [comment]
@agramesh1

**Comment by NeoZhangJianyu** [comment]
@electricSamarth 

auto eigen_tp = MklDnnThreadPoolWrapper::GetInstance().CreateThreadPoolPtr(ctx);
what does this bit here do?
A: it's used for thread pool.
 
what is the difference b/w dnnl_sgemm and dnnl_sgemm_tp
A: not use thread pool or use.

**Comment by electricSamarth** [comment]
ThankYou @NeoZhangJianyu ! :)
