### ISSUE TITLE
libcudart.so.10.1 is not included in the cuda 10.2 package

### ISSUE THREAD

**Issue by vinhdiesal** [tensorflow/tensorflow#42166]
I'm trying to see enabled GPUs in tensorflow by the following: 
```
import tensorflow as tf
from tensorflow.python.client import device_lib
import os
os.environ["TF_MIN_GPU_MULTIPROCESSOR_COUNT"]="2"
os.environ["CUDA_VISIBLE_DEVICES"]="0,1"
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
```
It returns 0 GPUs because it is looking for a `cuda` library called 'libcudart.so.10.1'. 
What I tried to so was rename the latest file `libcudart.so.10.2.89` to `libcudart.so.10.1` with no success.
The only way we can probably get this to work is by building from source which takes 10 hours on my machine. 
Can you make tensorflow to point to libcudart.so.10.2 in tensorflow 2.3?

Thanks,

**Comment by Srikeshram** [comment]
Try installing CUDnn....

**Comment by ravikyram** [comment]
@vinhdiesal 

Can you please see https://github.com/tensorflow/tensorflow/issues/34759#issuecomment-633819017 will help you?
For using cuda 10.2 you have to install TF from source. 
Also refer https://github.com/tensorflow/tensorflow/issues/38194#issuecomment-629801937, #39247
Thanks!
