### ISSUE TITLE
the tensorflow binary package in tensorflow r0.10 is build with cudnn5.1 not cudnn4.0

### ISSUE THREAD

**Issue by LinJM** [tensorflow/tensorflow#4217]
I use pip to install tf r0.10.
# Ubuntu/Linux 64-bit, GPU enabled, Python 2.7
# Requires CUDA toolkit 7.5 and CuDNN v4. For other versions, see "Install from sources" below.
$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0-cp27-none-linux_x86_64.whl

# Python 2
$ sudo pip install --upgrade $TF_BINARY_URL

When I run the program, the program raise error for the cudnn version. 
Actually, the binary package is builded with cudnn5.1 and cuda7.5.

**Comment by vrv** [comment]
Yup, our website needs to be pushed but the sources have been updated.
