### ISSUE TITLE
ValueError: Data cardinality is ambiguous. No issue in version 2.0.0 but fails with 2.2.0/2.3.0

### ISSUE THREAD

**Issue by sramakrishnan247** [tensorflow/tensorflow#42175]
### Functional API Multi input/output model works correctly in TF 2.0.0 but fails with TF 2.2.0 and 2.3.0

**Describe the current behavior**
Created a Multi Input/Output model using the functional api.
model.fit fails with the following error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-20532c7b88ab> in <module>()
     11 print('x',np.asarray(x).shape)
     12 print('y',y.shape)
---> 13 model.fit(x,y,epochs=1)

3 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weights, sample_weight_modes, batch_size, epochs, steps, shuffle, **kwargs)
    280             label, ", ".join(str(i.shape[0]) for i in nest.flatten(data)))
    281       msg += "Please provide data which shares the same first dimension."
--> 282       raise ValueError(msg)
    283     num_samples = num_samples.pop()
    284 

ValueError: Data cardinality is ambiguous:
  x sizes: 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224, 224
  y sizes: 2
Please provide data which shares the same first dimension.
```
Colab link:  https://colab.research.google.com/drive/1A3ociecOo4fMtuQep_cdWNDpBlVkad19?usp=sharing
Colab Github Gist: https://colab.research.google.com/gist/sramakrishnan247/0897350c315280935b1617e325665c08/tf2-3-issue.ipynb

**Describe the expected behavior**
model.fit should work successfully (similar to tensorflow 2.0.0)
```
x (10, 2, 224, 224, 20)
y (2, 3)
Train on 2 samples
14/2 [==================================================================================================================================================================================================================] - 34s 2s/sample - loss: 1.4392
<tensorflow.python.keras.callbacks.History at 0x7f444928b048>
```
Colab link: https://colab.research.google.com/drive/1mfom6_DMVohjfZ-cg-n1HF_XTFCB5qXc?usp=sharing
Colab Github gist: https://colab.research.google.com/gist/sramakrishnan247/08becc3e024ad21a2b90fa2ebabcfe76/tf2-0-sample.ipynb

**Comment by amahendrakar** [comment]
@sramakrishnan247,
In order to expedite the trouble-shooting process, please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by sramakrishnan247** [comment]
@amahendrakar 
Create Colab sample files for 2.0.0 and 2.3.0 for reproducibility. Please check.

**Comment by amahendrakar** [comment]
@sramakrishnan247,
I do not have the permission to view the files. Please try saving the Gist using the following method 'File' -> 'Save a copy as Github Gist', and share the link of the new window. Thanks!

**Comment by sramakrishnan247** [comment]
@amahendrakar Fixed it!
Please check. Thanks!

**Comment by amahendrakar** [comment]
Was able to reproduce the issue. 

Code works fine with [TF v2.0](https://colab.research.google.com/gist/amahendrakar/671050dc6cd79a0ca135757a208f4c74/42175-2-0.ipynb). Facing a `ValueError` on running with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/d549faa23c1d6c4f599379696ff27b40/42175.ipynb#scrollTo=R4ExMVpez7S3) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/87aac4f378f62d74ea766f8e3223145d/42175-tf-nightly.ipynb). 

Please find the attached gist. Thanks!

**Comment by omalleyt12** [comment]
@sramakrishnan247 Thanks for the issue!

The issue you're running into is bc you're passing a list-of-lists for `x`. We dropped support for treating inner lists as `Tensor`s bc it's ambiguous as to whether a list should be interpreted as a `Tensor` or as a Python list (as this example shows). Instead, you can pass a list of `np.array`s like this:

```python
x = []
for i in range(10):
  x.append([])
data = np.random.rand(2,10,224, 224, 20)
for data_vector in data:
  for index in range(10):
    x[index].append(data_vector[index]) 

for i in range(10):
  x[i] = np.asarray(x[i]) 
   
y = np.random.rand(2,3)
print('x',np.asarray(x).shape)
print('y',y.shape)
model.fit(x,y,epochs=1)
```

**Comment by sramakrishnan247** [comment]
@omalleyt12 
Thanks!
