### ISSUE TITLE
`DepthwiseConv2D` is no faster than `Conv2D`

### ISSUE THREAD

**Issue by xlnwel** [tensorflow/tensorflow#42172]
I'm reimplementing [MobileNet](https://arxiv.org/abs/1704.04861), but I find the depthwise convolution is no faster than conv2d(I haven't included the 1 by 1 pointwise convolution yet). Here's the test code run on colab: https://colab.research.google.com/drive/1nBuYrmmH5kM0jbtIZdsuiG6uJbU6mpA7?usp=sharing

```python
import tensorflow as tf
import time
x = tf.random.normal((2, 64, 64, 3))
conv = tf.keras.layers.Conv2D(16, 3, strides=1, padding='same')
dw = tf.keras.layers.DepthwiseConv2D(3, padding='same')
start = time.time()
conv(x)
print('conv2d:', time.time() - start)    # approximate 0.0036s
start = time.time()
dw(x)
print('dw:', time.time() - start)    # approximate 0.0034s
%timeit conv(x)    # 1000 loops, best of 3: 225 µs per loop
%timeit dw(x)    # 1000 loops, best of 3: 352 µs per loop
```

I also try it on my laptop using CPUs only, similar results are spotted. Any idea of how to speed up `DepthwiseConv2D`?

**Comment by ravikyram** [comment]
@xlnwel 

I have tried in colab with TF version 2.3, nightly versions.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/33f43ac514e69990d8e6666d725ddf65/untitled233.ipynb).You are also seeing the same behavior?
Thanks!

**Comment by xlnwel** [comment]
Hi @ravikyram 

I ran the link you provide. It runs on CPU and the result is shown in the following figure

![image](https://user-images.githubusercontent.com/10184153/89783345-5e55d380-db49-11ea-84cf-f9bd336c50cb.png)


The following figure shows the result on GPU

![image](https://user-images.githubusercontent.com/10184153/89783290-48e0a980-db49-11ea-9a89-6dde23e0f30f.png)

I also run the code on my laptop. Here's the result

![image](https://user-images.githubusercontent.com/10184153/89783482-98bf7080-db49-11ea-9731-d114f6689d50.png)

And notice that all the results simply report the comparisons between depthwise convolution and the standard convolution. The depthwise separable convolution consists of depthwise convolution and an additional 1x1 standard convolution. So the depthwise separable convolutions seem slower than the standard convolutions despite the theoretical promise, am I right?

**Comment by jvishnuvardhan** [comment]
@xlnwel I agree with you. I think the `dw` is slower when you have smaller dataset. 
I checked by increasing dataset to 100 by updating one line of your code to  `x = tf.random.normal((100, 64, 64, 3))`

With colab (GPU) I see the following results

> conv2d: 0.0032930374145507812
> dw: 0.0029036998748779297
> 1000 loops, best of 3: 805 µs per loop
> 1000 loops, best of 3: 339 µs per loop

[Here](https://colab.research.google.com/gist/jvishnuvardhan/f44955d2a895365e81c19e4f3348f310/untitled233.ipynb) is the gist for your reference.

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by xlnwel** [comment]
Hi, @jvishnuvardhan 

Thanks for the observation. I see similar results as you reported. I also test the performance using inputs like `x = tf.random.normal((1000, 8, 8, 3))` and find dw is slower:

> 1000 loops, best of 3: 208 µs per loop
1000 loops, best of 3: 322 µs per loop

I'll be careful to use dw in my research. Thanks again.
