### ISSUE TITLE
TF Lite version for examples/lite/examples/image_classification

### ISSUE THREAD

**Issue by alisonwh** [tensorflow/tensorflow#42176]
I tried to run image classification demo on Android based on the following link. It can work successfully.
https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/android/README.md

I have a question about the version number for this TF Lite. I want to know weather this demo is using libtflite.so in my Android OS or some other TF Lite version?

Thanks.

**Comment by alisonwh** [comment]
According to my understanding, the libraries as below are just for JNI support. libtflite.so is still needed. Well, who provides libtflite.so? My Android OS or others?

implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly'
implementation 'org.tensorflow:tensorflow-lite-support:0.0.0-nightly'

**Comment by jdduke** [comment]
The example pulls the native TFLite binaries from the nightly builds. Generally, the nightly builds have a newer "true" version than the last publicly released TFLite builds (in this case, 2.3). That is, `org.tensorflow:tensorflow-lite:0.0.0-nightly` corresponds to an AAR package that has both the Java and C++ code (libtensorflowlite_jni.so) that contains the TFLite implementation. That library gets statically linked into your app, so it won't be using libtflite.so from your OS (which isn't a true Android platform library).

**Comment by alisonwh** [comment]
I see now. Thank you very much for your detailed explanation.
