### ISSUE TITLE
Get error during converting ResizeNearestNeighbor to tflite

### ISSUE THREAD

**Issue by neesetifa** [tensorflow/tensorflow#42184]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Arch Linux
- TensorFlow installed from (source or binary):  package manager
- TensorFlow version (or github SHA if from source):  2.2.0 - 1

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
# Copy and paste here the exact command
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
tflite_model_quant = converter.convert()
```

**The output from the converter invocation**

```
# Copy and paste the output here.
2020-08-10 18:10:20.777385: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
loc(callsite("sequential/up_sampling2d/resize/ResizeNearestNeighbor"("/usr/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py":865:0) at callsite("/usr/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py":959:0 at callsite("/usr/lib/python3.8/site-packages/tensorflow/lite/python/lite.py":435:0 at "test.py":51:0)))): error: 'tf.ResizeNearestNeighbor' op is neither a custom op nor a flex op
error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag): ResizeNearestNeighbor.
Traceback (most recent call last):
  File "/usr/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/lib/python3.8/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/lib/python3.8/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/lib/python3.8/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 50, in execute
    output_str = _pywrap_toco_api.TocoConvert(
Exception: /usr/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py:865:9: error: 'tf.ResizeNearestNeighbor' op is neither a custom op nor a flex op
        self._initialize(args, kwargs, add_initializers_to=initializers)
        ^
/usr/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py:959:5: note: called from
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
    ^
/usr/lib/python3.8/site-packages/tensorflow/lite/python/lite.py:435:5: note: called from
    concrete_func = func.get_concrete_function()
    ^
test.py:51:1: note: called from
converter = tf.lite.TFLiteConverter.from_keras_model(model)
^
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag): ResizeNearestNeighbor.

```

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
```

**Failure details**
Conversion fails.

In the attachment zip file, there is a .py file that you can run and reproduce the error. The code is originally from this tutorial:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/performance/post_training_integer_quant.ipynb

The cause of the failure is that I added a UpSampling2D layer with "nearest neighbor" in the model and do "Convert using integer-only quantization".  Everything is ok if I delete UpSampling2D, or use UpSampling2D with "bilinear".

[test.zip](https://github.com/tensorflow/tensorflow/files/5050250/test.zip)

**Comment by Saduf2019** [comment]
@neesetifa 
I ran the .py file shared and do not face any issues on tf nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/2e92a6fddd0d149ca0b9a34683bbf4ba/untitled337.ipynb)
With respect to the error reported please refer to below issues:
#36517 #41085 [link](https://github.com/google-coral/edgetpu/issues/152) #35590

**Comment by neesetifa** [comment]
@Saduf2019  Thank you for the quick reply. I ran the gist and everything seems fine on tf nightly.
Actually this problem happened when I tried to convert a mobilenet yolo v3 model in my office. I will try it again with tf nightly when I get back to the office tomorrow.

**Comment by abattery** [comment]
Could you try conversion with tf select ops?

https://www.tensorflow.org/lite/guide/ops_select

**Comment by Saduf2019** [comment]
@neesetifa 
Could you please update.

**Comment by neesetifa** [comment]
@Saduf2019  I'm so sorry for the delay.  
Yesterday, I successfully convert the model using tf nightly, but got following problems:
1. If I use tf 2.2 to do inference, we get error "Didn't find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR' version '3' ", which is same as the one you mentioned before [link](https://github.com/google-coral/edgetpu/issues/152)

2. If I use tf nightly to do inference, we get new error:
> 2020-08-12 02:29:00.559305: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5459220 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-12 02:29:00.559335: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "test_on_single_image_tflite_ver.py", line 63, in <module>
    interpreter_quant.set_tensor(input_index_quant, resized_image)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter.py", line 408, in set_tensor
    self._interpreter.SetTensor(tensor_index, value)
ValueError: Cannot set tensor: Got value of type FLOAT32 but expected type INT8 for input 0, name: input_1 

attachment is the model converted by tf nightly
[tflite.zip](https://github.com/tensorflow/tensorflow/files/5060321/tflite.zip)

following is my conversion code

```
def process_single_image_with_opencv(image):
    image_shape = image.shape[:2]
    image = cv2.resize(image, (416, 416))  
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB).astype(np.float32)
    image = image / 255.0
    return image, image_shape

# load model
model_yolo = get_model()
model_yolo.load_weights(filepath = SAVE_MODEL_DIR + "final_weights.h5")

txt_dataset = tf.data.TextLineDataset(filenames=TRAIN_TXT_DIR)
def representative_data_gen():
      for txt in txt_dataset.take(1000):
            image_name, _, _ = ReadTxt(txt.numpy()).parse_line()
            image = cv2.imread(image_name)
            image, _ = process_single_image_with_opencv(image)
            image = tf.expand_dims(image, axis = 0)
            yield [image]
            
tflite_models_dir = pathlib.Path(TFLite_MODEL_DIR)

converter = tf.lite.TFLiteConverter.from_keras_model(model_yolo)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8
    
tflite_model_quant = converter.convert()
tflite_model_quant_file = tflite_models_dir/"mobilenet_yolo_v3_fixed_size_416_alpha_50_int8.tflite"
tflite_model_quant_file.write_bytes(tflite_model_quant)
```


following is my inference code

```
test_image = cv2.imread( "xxxxx.jpg" ) # just use any image
resized_image,  _ = process_single_image_with_opencv(test_image)
resized_image = np.expand_dims(resized_image, axis = 0)

interpreter_quant = tf.lite.Interpreter(model_path = 'mobilenet_yolo_v3_fixed_size_416_alpha_50_int8.tflite')
interpreter_quant.allocate_tensors()

input_index_quant  = interpreter_quant.get_input_details()[0]["index"]
output_index_quant = interpreter_quant.get_output_details()[0]["index"]

interpreter_quant.set_tensor(input_index_quant, resized_image)
interpreter_quant.invoke()
output_data = interpreter_quant.get_tensor(output_index_quant) 

# then use output_data to get best boxes
```

**Comment by neesetifa** [comment]
@abattery   Thanks for the reply. I tried that one before, and I get "segmentation fault" during conversion with no other information.

**Comment by abattery** [comment]
For the quantization problem after conversion, it is related to the model optimization toolkit.

**Comment by jaeyoo** [comment]
@neesetifa You are using `process_single_image_with_opencv()`, but it seems to output float image. It is not compatible with your quantized integer model. Could you check with integer images again?

**Comment by neesetifa** [comment]
@jaeyoo  Thank you for your reply. I double checked `process_single_image_with_opencv()`, this used to work in 2.2.  I read the latest tutorial and it seems that I need to manually convert the image back to integer in 2.3 or nightly before doing invoke(). Now everything works perfect. 
This issue can be closed.
