### ISSUE TITLE
While Tensorflow usually uses GatherV2, TFLite only supports Gather

### ISSUE THREAD

**Issue by junhyk** [tensorflow/tensorflow#42180]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): v2.3.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
While TensorFlow converts tf.gather to GatherV2, TFlite only supports Gather.
So we cannot directly convert tf.gather to TFlite. I think it doesn't make sense.
(Flex delegate somehow works, though)
I argue that TFLite should support GatherV2.

**Will this change the current api? How?**
Since it only requires to modify the underlying kernel, user API would not be changed.

**Who will benefit with this feature?**
The one who wants to use gather and convert their model to TFlite
**Any Other info.**

**Comment by abattery** [comment]
By the way, TFLite currently supports GatherV2 only when batch_dims = 0 and axis is constant.

**Comment by hamlatzis** [comment]
Is there an OpenCL kernel for either Gather or GatherV2?

**Comment by terryheo** [comment]
@hamlatzis 
No. Gather is not supported by GPU delegate.
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/gpu

**Comment by mohantym** [comment]
Hi @junhyk !
We are checking to see whether you still need help in this issue . You can use [GatherV2](https://www.tensorflow.org/lite/guide/op_select_allowlist#:~:text=raw_ops.GatherNd-,raw_ops.GatherV2,-raw_ops.GetSessionHandle)  through [select ops](https://www.tensorflow.org/lite/guide/ops_select#convert_a_model) syntax now.
Thank you!

**Comment by junhyk** [comment]
Thank you for the information.
I think that would help.
I don't need help on this issue now.

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
