### ISSUE TITLE
Not every keras.metrics.* accept from_logits=True

### ISSUE THREAD

**Issue by adamp87** [tensorflow/tensorflow#42182]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Linux Ubuntu 18.04.3
- TensorFlow installed from: binary (Docker Image tensorflow:2.3.0-gpu)
- TensorFlow version: v2.3.0-rc2-23-gb36436b087 2.3.0
- Python version: 3.6.9 
- CUDA/cuDNN version: CUDA10.2
- GPU model and memory: RTX 2080 8GB

**Describe the current behavior**
The issue is the same as described by MeghnaNatraj in ticket [37103](https://github.com/tensorflow/tensorflow/issues/37103). The mentioned ticket states the problem has been solved. I was requested to open a new ticket.

If I have a model with an output layer of one neuron and 'sigmoid' activation function and using BinaryCrossentropy(from_logits=False), then the model.fit() function accepts any metrics (e.g. Precision)
If I have the same model as before but without activation function and BinaryCrossentropy(from_logits=True), then model.fit() function will return an error.

**Describe the expected behavior**
- Having a model, which has an output layer without an activation function: keras.layers.Dense(1) # Output range is [-inf, +inf]
- Loss function of the model working with logits: BinaryCrossentropy(from_logits=True)
- Accepting metrics during fitting like keras.metrics.Precision

**Standalone code to reproduce the issue**
I have copied the same test code by MeghnaNatraj in ticket [37103](https://github.com/tensorflow/tensorflow/issues/37103) 

```
# INITIALIZE

import tensorflow as tf
import numpy as np
# define dataset
dataset = np.array([[6,148,72,35,0,33.6,0.627,50,1],
[1,85,66,29,0,26.6,0.351,31,0],
[8,183,64,0,0,23.3,0.672,32,1],
[1,89,66,23,94,28.1,0.167,21,0],
[0,137,40,35,168,43.1,2.288,33,1]])
# split into input (X) and output (y) variables
X = dataset[:,0:8]
y = dataset[:,8]
```

```
# WORKS: Model output is in range [0, 1]
# define the keras model
model = tf.keras.models.Sequential([tf.keras.layers.Dense(12, input_dim=8, activation='relu'),
                                    tf.keras.layers.Dense(1, activation='sigmoid')])
# compile the keras model
model.compile(loss=tf.keras.losses.BinaryCrossentropy(),
              optimizer=tf.keras.optimizers.RMSprop(),
              metrics=[tf.keras.metrics.Accuracy(name='accuracy'),
                       tf.keras.metrics.Precision(name='precision'),
                       tf.keras.metrics.TruePositives(name='tp')])
# fit the keras model on the dataset
model.fit(X, y, epochs=10, batch_size=10, verbose=0)
```

```
# DOES NOT WORK: Model output is in range [-inf, inf]
# define the keras model
model = tf.keras.models.Sequential([tf.keras.layers.Dense(12, input_dim=8, activation='relu'),
                                    tf.keras.layers.Dense(1)])
# compile the keras model
model.compile(loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              optimizer=tf.keras.optimizers.RMSprop(),
              metrics=[tf.keras.metrics.Accuracy(name='accuracy'),
                       tf.keras.metrics.Precision(name='precision'),
                       tf.keras.metrics.TruePositives(name='tp')])
# fit the keras model on the dataset
model.fit(X, y, epochs=10, batch_size=10, verbose=0)

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  assertion failed: [predictions must be <= 1] [Condition x <= y did not hold element-wise:] [x (sequential_8/dense_17/BiasAdd:0) = ] [[22.0911655][62.7297783][35.2793274]...] [y (metrics/precision/Cast_3/x:0) = ] [1]
	 [[{{node metrics/precision/assert_less_equal/Assert/AssertGuard/else/_11/Assert}}]]
	 [[metrics/tp/assert_greater_equal/Assert/AssertGuard/pivot_f/_31/_61]]
  (1) Invalid argument:  assertion failed: [predictions must be <= 1] [Condition x <= y did not hold element-wise:] [x (sequential_8/dense_17/BiasAdd:0) = ] [[22.0911655][62.7297783][35.2793274]...] [y (metrics/precision/Cast_3/x:0) = ] [1]
	 [[{{node metrics/precision/assert_less_equal/Assert/AssertGuard/else/_11/Assert}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_distributed_function_12253]

Function call stack:
distributed_function -> distributed_function

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  assertion failed: [predictions must be <= 1] [Condition x <= y did not hold element-wise:] [x (sequential/dense_1/BiasAdd:0) = ] [[28.8497276][37.4658966][48.6209221]...] [y (Cast_5/x:0) = ] [1]
         [[{{node assert_less_equal/Assert/AssertGuard/else/_11/assert_less_equal/Assert/AssertGuard/Assert}}]]
         [[assert_less_equal_1/Assert/AssertGuard/pivot_f/_41/_81]]
  (1) Invalid argument:  assertion failed: [predictions must be <= 1] [Condition x <= y did not hold element-wise:] [x (sequential/dense_1/BiasAdd:0) = ] [[28.8497276][37.4658966][48.6209221]...] [y (Cast_5/x:0) = ] [1]
         [[{{node assert_less_equal/Assert/AssertGuard/else/_11/assert_less_equal/Assert/AssertGuard/Assert}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_1165]
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/a935a6152c181e3dc41a634fbb0014f7/42182-2-2.ipynb#scrollTo=JpJKOKSJLXea), [TF v2.3](https://colab.research.google.com/gist/amahendrakar/3b2889c03a765d80bab6b5b444920d73/42182.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/ff1cbac265479597dde7294de7547a4d/42182-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by w19787** [comment]
any one is working on this?

**Comment by neeps** [comment]
Would also like to know if there is any progress on this issue.

**Comment by barskern** [comment]
Looking at the source code for `tf.keras.metrics.Precision`, one can see that there is an assertion that thresholds are between 0 and 1. See trail of links below:

https://github.com/tensorflow/tensorflow/blob/4ef28c5f287cd0a96daad3e7634b570de7e1f496/tensorflow/python/keras/metrics.py#L1256

https://github.com/tensorflow/tensorflow/blob/4ef28c5f287cd0a96daad3e7634b570de7e1f496/tensorflow/python/keras/utils/metrics_utils.py#L178

https://github.com/tensorflow/tensorflow/blob/4ef28c5f287cd0a96daad3e7634b570de7e1f496/tensorflow/python/keras/utils/metrics_utils.py#L169

https://github.com/tensorflow/tensorflow/blob/4ef28c5f287cd0a96daad3e7634b570de7e1f496/tensorflow/python/keras/utils/metrics_utils.py#L171

Further to change this, it seems like there has to be made a change here: https://github.com/tensorflow/tensorflow/blob/4ef28c5f287cd0a96daad3e7634b570de7e1f496/tensorflow/python/keras/utils/metrics_utils.py#L336-L345

**Comment by hugokitano** [comment]
would like some resolution on this!

**Comment by nialloh23** [comment]
Also running into this problem at the moment.

**Comment by zicofish** [comment]
run into this problem for a combination use of `tf.keras.losses.BinaryCrossentropy(from_logits=True)` (for a numerically stable loss computation) and `tf.keras.metrics.AUC`

**Comment by bobbyinfj** [comment]
This issue also arises when trying to add metrics to [classify text with bert tutorial](https://www.tensorflow.org/tutorials/text/classify_text_with_bert)

**Comment by lucasdavid** [comment]
Thank you very much, @barskern. It works perfectly!
I did find a more compact way to express your solution. Thought Id share it:

```py
class FromLogitsMixin:
  def __init__(self, from_logits=False, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.from_logits = from_logits

  def update_state(self, y_true, y_pred, sample_weight=None):
    if self.from_logits:
      y_pred = tf.nn.sigmoid(y_pred)
    return super().update_state(y_true, y_pred, sample_weight)


class AUC(FromLogitsMixin, tf.metrics.AUC):
  ...

class BinaryAccuracy(FromLogitsMixin, tf.metrics.BinaryAccuracy):
  ...

class TruePositives(FromLogitsMixin, tf.metrics.TruePositives):
  ...

class FalsePositives(FromLogitsMixin, tf.metrics.FalsePositives):
  ...

class TrueNegatives(FromLogitsMixin, tf.metrics.TrueNegatives):
  ...

class FalseNegatives(FromLogitsMixin, tf.metrics.FalseNegatives):
  ...

class Precision(FromLogitsMixin, tf.metrics.Precision):
  ...

class Recall(FromLogitsMixin, tf.metrics.Recall):
  ...

class F1Score(FromLogitsMixin, tfa.metrics.F1Score):
  ...
```

**Comment by barskern** [comment]
@lucasdavid That looks a lot cleaner! Thank you for the improvements 😁

**Comment by sushreebarsa** [comment]
I was  able to reproduce this issue on TF nightly ,please check the gist [here](https://colab.research.google.com/gist/sushreebarsa/0b8aa23e900fb3c195eb5a393db985ff/untitled131.ipynb?authuser=1) ..Thanks !

**Comment by sradc** [comment]
F1Score based on @barskern's code:

```python
class F1Score(tf.keras.metrics.Metric):
    def __init__(self, name="f1", from_logits=False, **kwargs):
        super(F1Score, self).__init__(name=name, **kwargs)
        self.precision = Precision(from_logits)
        self.recall = Recall(from_logits)

    def update_state(self, y_true, y_pred, sample_weight=None):
        self.precision.update_state(y_true, y_pred, sample_weight)
        self.recall.update_state(y_true, y_pred, sample_weight)

    def result(self):
        p = self.precision.result()
        r = self.recall.result()
        return (2 * p * r) / (p + r + tf.keras.backend.epsilon())

    def reset_states(self):
        self.precision.reset_states()
        self.recall.reset_states()
```

**Comment by sushreebarsa** [comment]
Closing this issue as it is fixed in latest version of TensorFlow. Please feel free to reopen the issue if you still have a concern. Thanks!

**Comment by sushreebarsa** [comment]
Closing this issue as it is fixed in latest version of TensorFlow. Please feel free to reopen the issue if you still have a concern. Thanks!

**Comment by raftAtGit** [comment]
> Closing this issue as it is fixed in latest version of TensorFlow. Please feel free to reopen the issue if you still have a concern. Thanks!

Hi @sushreebarsa, I believe this issue is not solved yet, at least not completely. Please see my post in the TensorFlow forum below.
https://discuss.tensorflow.org/t/metrics-related-predictions-must-be-1-error/6144/9

Would you reopen the issue or should I create a new one?

**Comment by sushreebarsa** [comment]
Hi @raftAtGit , 
Please create a new issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by wjlgatech** [comment]
> ```python
> f self._from_logits:
>             super(FalseNegatives, self).update_state(y_true, tf.nn.sigmoid(y_pred), sample_weight)
>         else:
>             super(FalseNegatives, self).update_state(y_true, y_pred, sample_weight)
> 
> 
> class Precision(tfm.Precision):
>     def __init__(self, from_logits=False, *args, **kwargs):
>         super().__init__(*args, **kwargs)
>         self._from_logits = from_logits
> 
>     def update_state(self, y_true, y_pred, sample_weight=None):
>         if self._from_logits:
>             super(Precision, self).update_state(y_true, tf.nn.sigmoid(y_pred), sample_weight)
>         else:
>             super(Precision, self).update_state(y_true, y_pred, sample_weight)
> 
> 
> class Recall(tfm.Recall):
>     def __init__(self, from_logits=False, *args, **kwargs):
>         super().__init__(*args, **kwargs)
>         self._from_logits = from_logits
> 
>     def update_state(self, y_true, y_pred, sample_weight=None):
>         if self._from_logits:
>             super(Recall, self).update_state(y_true, tf.nn.sigmoid(y_pred), sample_weight)
>         else:
>             super(Recall, self).update_state(y_true, y_pred, sample_weight)
> ```

@lucasdavid can you explicitly write out what `...`mean under each class? an example will be helpful. Thanks

**Comment by zzzlxhhh** [comment]
> This issue also arises when trying to add metrics to [classify text with bert tutorial](https://www.tensorflow.org/tutorials/text/classify_text_with_bert)

yep! I met with the same issue. How did you solve it? It would be nice if you can show me some hints to solve this! I've tried the tricks mentioned above ,but they dont work

**Comment by lucasdavid** [comment]
@wjlgatech, my sincere apologies for taking so long to answer. I must have missed your question. You probably don't need it anymore, but I'll explain it for documentation purposes: The ellipses operator is a modern alternative (but equivalent) to command "pass" in this example. It's just used to state that that context has no additional statements. So for the AUC class:
```py
class AUC(FromLogitsMixin, tf.metrics.AUC):
  ...
```

I'm saying "This class inherits from both `FromLogitsMixin` and `tf.metrics.AUC`, and has no other properties/methods.
