### ISSUE TITLE
How to load onnx model in Keras

### ISSUE THREAD

**Issue by Aleksey1555** [tensorflow/tensorflow#42198]
Hello!
Keras version: 2.4.3
Tensorflow version: 2.2.0
Python version:  3.7.7
OS: Windows 10 x64

I want to load onnx model [(this yolov3 model)](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov3) in keras.
I download this model and run command to convert onnx to pb file, like this:
**nnx-tf convert -i yolov3.onnx -o saved_model.pb**
this command was taken from [link](https://github.com/onnx/onnx-tensorflow)
Command finished with success!
Then i try to load pb file like this:
` from tensorflow import keras
  model = keras.models.load_model('my path to folder with saved_model.pb file')`

And result is error:
 **String field 'tensorflow.MetaGraphDef.MetaInfoDef.meta_graph_version' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.**

Please help

**Comment by jvishnuvardhan** [comment]
@Aleksey1555 `keras.models.load_model` cannot be used to load *.pb file. I think this is more related to `onnx` repo. Can you please post your issue in [`onnx` repo here](https://github.com/onnx/onnx-tensorflow/issues).  Thanks!
