### ISSUE TITLE
Keras RNNs do not respect get_initial_state if stateful=True

### ISSUE THREAD

**Issue by drasmuss** [tensorflow/tensorflow#42193]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.8
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**

RNNs created with `stateful=True` always start with all-zero initial state, even if there is a `get_initial_state` function defined.

**Describe the expected behavior**

The state variables should be initialized with the values returned by `get_initial_state`

**Standalone code to reproduce the issue**

``` python
import tensorflow as tf
import numpy as np


class TestCell(tf.keras.layers.Layer):
    state_size = 1
    output_size = 1

    def get_initial_state(self, inputs=None, batch_size=None, dtype=None):
        return tf.ones((batch_size, 1), dtype=dtype)

    def call(self, inputs, states):
        tf.assert_equal(states, 1.0)
        return inputs, states


layer = tf.keras.layers.RNN(TestCell(), stateful=True)

x = np.ones((1, 10, 1), dtype=np.float32)

layer(x)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Condition x == y did not hold.
First 1 elements of x:
[0.]
First 1 elements of y:
[1.]
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/9f76798b4dc0a8c77468dfe9ff58b31d/42193-tf-nightly.ipynb). Thanks!
