### ISSUE TITLE
Reduction is average step time when disabling certain HLO passes

### ISSUE THREAD

**Issue by mmadala95** [tensorflow/tensorflow#42207]
**System information**
- Model: ResNet50 with Cifar-10
- OS Platform and Distribution : Linux Ubuntu 18.04
- TensorFlow: installed from source
- TensorFlow version : v2.2.0
- Python version: 3.6.9
- Bazel version : 2.0.0
- GCC/Compiler version : 7.5.0
- CUDA/cuDNN version: 10.1/7.6
- GPU model and memory: GeForce RTX 2080 / 7982MiB

**Describe the current behavior**

Hi all,

I am currently trying to find way if a model execution time can be reduced further . For instance I saw 5 ms reduction in average step time (Tensorboard Profile Summary) at times when I disabled certain HLO passes like  gpu-conv-padding-legalization, transpose-folding while running ResNet50 with Cifar 10 . Now I understand that entire set of 51 HLO passes(Target Dependent and Target Independent) are there for a reason. But considering the reduction in step time , is this normal behavior if not can some of these passes be avoided depending on the model we execute ? 

I tried disabling some HLO passes 
- convolution_4d_expander
- gpu-conv-padding-legalization
- multi_output_fusion
- reduction-degenerate-dim-remover
- reduction-dimension-grouper
- transpose-folding

** plots with some results obtained **
https://github.com/mmadala95/xla_analysis/tree/master/results

**Describe the expected behavior**

probably execution time of model might not improve when disabling certain HLO passes (which might not be useful to a model).  

**Standalone code to reproduce the issue**
https://github.com/mmadala95/xla_analysis/blob/master/ResNet50_xla.py

**Comment by mmadala95** [comment]
> **System information**
> 
> * Model: ResNet50 with Cifar-10
> * OS Platform and Distribution : Linux Ubuntu 18.04
> * TensorFlow: installed from source
> * TensorFlow version : v2.2.0
> * Python version: 3.6.9
> * Bazel version : 2.0.0
> * GCC/Compiler version : 7.5.0
> * CUDA/cuDNN version: 10.1/7.6
> * GPU model and memory: GeForce RTX 2080 / 7982MiB
> 
> **Describe the current behavior**
> 
> Hi all,
> 
> I am currently trying to find way if a model execution time can be reduced further . For instance I saw 5 ms reduction in average step time (Tensorboard Profile Summary) at times when I disabled certain HLO passes like gpu-conv-padding-legalization, transpose-folding while running ResNet50 with Cifar 10 . Now I understand that entire set of 51 HLO passes(Target Dependent and Target Independent) are there for a reason. But considering the reduction in step time , is this normal behavior if not can some of these passes be avoided depending on the model we execute ?
> 
> I tried disabling some HLO passes
> 
> * convolution_4d_expander
> * gpu-conv-padding-legalization
> * multi_output_fusion
> * reduction-degenerate-dim-remover
> * reduction-dimension-grouper
> * transpose-folding
> 
> ** plots with some results obtained **
> https://github.com/mmadala95/xla_analysis/tree/master/results
> 
> **Describe the expected behavior**
> 
> Ideally as per , execution time of model must not improve when disabling certain HLO passes which might not be useful to a model.
> 
> **Standalone code to reproduce the issue**
> https://github.com/mmadala95/xla_analysis/blob/master/ResNet50_xla.py

Adding Sanjoy as per his suggestion

@sanjoy

**Comment by ravikyram** [comment]
@mmadala95 

I tried reproducing the issue in colab with TF version 2.2 and i am seeing the below error message.
`KeyError: 'XLA_Current_Disabled'`

Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/5d4393a5d52662370b3a7179793a7097/untitled236.ipynb).Thanks!

**Comment by mmadala95** [comment]
@ravikyram 
sorry for that, please ignore that environment variable that was custom set to modify logs folder names.

replace line 167 with 

logs = <logs directory path >+ datetime.now().strftime("%Y%m%d")

before each run of this model , I used to set this flag with HLO passes I need to disable 
for ex:  export XLA_FLAGS="--xla_disable_hlo_passes=convolution_4d_expander,multi_output_fusion"

and obtained results from tensorboard profiling on logs generated in above path .

**Comment by sanjoy** [comment]
Tim, does this mean we need to adjust some of our heuristics in the passes listed?

CC @thomasjoerg @akuegel

**Comment by akuegel** [comment]
At least regarding convolution_4d_expander, I doubt that it has an impact on resnet average step time.
As far as I know, resnet doesn't have 4 spatial dimensions in its convolutions, so this pass will not trigger. Given that you seem to have measured some timing difference, this is most likely noise (or you are also measuring compile time, not only runtime). If you measured compile time, there is not much to optimize there: we just iterate once over all HLO instructions to see which ones do match (I expect none), and only on match do some replacements.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
