### ISSUE TITLE
tf.nn.space_to_depth and tf.nn.depth_to_space crashes (segfault) in `NCHW_VECT_C ` mode with certain input

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#42203]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.6.9
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

`tf.nn.space_to_depth ` and `tf.nn.depth_to_space` crashes (segfault) in when `input` is of length EXACTLY 4, `block_size>1` and `data_format=NCHW_VECT_C`.

**Describe the expected behavior**

Expect no segfault

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

~~~python
import tensorflow as tf
tf.nn.space_to_depth(input=tf.zeros((4)), block_size = 2, data_format ='NCHW_VECT_C')
tf.nn.depth_to_space(input=tf.zeros((4)), block_size = 2, data_format ='NCHW_VECT_C')
~~~

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
~~~python
Segmentation fault (core dumped)
~~~

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. 

Session crashes on running the code, never reaches the print statement.  Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/473b0b7e56de406bdf4e5da95898c7c1/42203.ipynb). Thanks!

**Comment by Saduf2019** [comment]
I ran the code on nightly and face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/5b068248c0aba40244fbaa1db5f56d2c/untitled499.ipynb)

**Comment by kkimdev** [comment]
Those API only support NHWC today.
- https://github.com/tensorflow/tensorflow/blob/8cc5a3a/tensorflow/core/kernels/spacetodepth_op.cc#L76
- https://github.com/tensorflow/tensorflow/blob/8cc5a3a/tensorflow/core/kernels/depthtospace_op.cc#L61

Adding contribution welcome tag.

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210529,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/bca7a1f300d75a6d5acaed1fbce1b615/untitled97.ipynb#scrollTo=EKi5jI-ZQrnf)..Thanks !

**Comment by jvishnuvardhan** [comment]
@DNXie Thanks for creating this issue. It was crashing with `TF2.3`. With recent `tf-nightly`, it doesn't crash anymore and throws an error as expected. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/60575c690ea58dd5f55092cf80b1fa0c/untitled499.ipynb) with `tf-nightly`. Thanks!
