### ISSUE TITLE
Confusing error in gradient of assign_add + while_loop + gather

### ISSUE THREAD

**Issue by kentslaney** [tensorflow/tensorflow#42201]
**Describe the current behavior**
Autograph produces a static graph with the wrong number of inputs when a trainable variable is in a separate class. I also get a warning about converting a sparse op to a dense one, which seems to be related (while to gather, problem goes away when removed).

**Describe the expected behavior**
The function should execute without errors.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1x36cCyKsSxsOCw1Z4mnR4AzbwDSuXzTY#scrollTo=O6GzPt2gZiPF

**Comment by kentslaney** [comment]
Turns out it was unrelated to the secondary class, I've updated the colab accordingly

**Comment by kentslaney** [comment]
Interestingly, the error actually seems to go away if you switch to gather_nd

https://colab.research.google.com/drive/1Pa8g79qxnzlzf0oUM0cEtDoJrOUZSICd#scrollTo=cJDdoS6OR_Fc

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/73b647d45206ec4167c0672b817a3b2d/untitled358.ipynb)

**Comment by mdanatg** [comment]
It looks like certain inputs are indeed mismatched in the graph, but the error happens in the gradient ops. The error message about incorrect number of inputs looks like a red herring. Will update the bug title a bit.

**Comment by kentslaney** [comment]
Actually, I think assign_add is unrelated, it seems to fail with any graph op that requires the variable, eg
https://colab.research.google.com/drive/11MZorVrToy1bng_GfgmSWwum4z6kUvEL#scrollTo=wGyr_8aK0iv5

**Comment by kentslaney** [comment]
I think [this commit](https://github.com/tensorflow/tensorflow/commit/2d1e9501e391c4588be68dabef039112b6643f2a) fixes the bug ([colab](https://colab.research.google.com/drive/19BMMQsnMc8sMZGEuXL7lGu0YyNWjUniz?usp=sharing#scrollTo=O6GzPt2gZiPF)), should I close the issue @mdanatg?

**Comment by mdanatg** [comment]
Yep looks like the issue is resolved and can be closed. Thanks!
