### ISSUE TITLE
/usr/bin/env: 'python': No such file or directory

### ISSUE THREAD

**Issue by leematthewshome** [tensorflow/tensorflow#42211]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Built from Github source
- TensorFlow version: Latest (2.2)
- Python version: 3.8
- Installed using virtualenv? pip? conda?: No virtual or conda used
- Bazel version (if compiling from source): 3.4.1
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

Issue "Tensorflow does not build in a python3 only environment #15618" is still a problem. 

Rather than have to trawl through google posts and forums to find a solution it would be preferable if the build instructions mentioned the simple work-around of creating a Sym link to Python3 using the following

sudo link /usr/bin/python3 /usr/bin/python

**Comment by Saduf2019** [comment]
@leematthewshome 
Please provide with all details/steps followed before the issue was faced, including the error log for us to analyse.

**Comment by mihaimaruseac** [comment]
This is a bazel issue, not TF
