### ISSUE TITLE
tf.random.learned_unigram_candidate_sampler crashes(segfault) when true_classes contain large value

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#42212]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
`tf.random.learned_unigram_candidate_sampler` crashes(segfault) when `true_classes` containa large value AND `num_true=rank(true_classes)[-1]`.

**Describe the expected behavior**
expect no crashes

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
~~~python
import tensorflow as tf
true_classes = [[1, 100000]]  # shape(1,2)
num_true = 2
tf.random.learned_unigram_candidate_sampler(true_classes=true_classes, num_true=num_true, num_sampled=10, unique=False, range_max=1)
~~~
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
~~~python
Segmentation fault (core dumped)
~~~

**Comment by amahendrakar** [comment]
@DNXie,
I was able to run the code without any issues on [TF v2.1](https://colab.research.google.com/gist/amahendrakar/ccf6ef3fea0c7a952867fc34d02ff0a1/42212-2-1.ipynb), [TF v2.3](https://colab.research.google.com/gist/amahendrakar/eb8091c6fed7dc4a5eb7fc8300cca5d7/42212.ipynb#scrollTo=OtuJ_qBYFRri) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/50618d2fba1e9b1f3f1a9411e25e84ba/42212.ipynb). Please find the attached gist.

Could you please update TensorFlow to v2.3 or try running the code in a virtual environment and check if you are facing the same issue? Thanks!
