### ISSUE TITLE
[comp:data] link invalid in the "Analyze tf.data performance with the TF Profiler" guide

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#42218]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue: https://www.tensorflow.org/guide/data_performance_analysis

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/guide/data_performance_analysis#3_are_you_reaching_high_cpu_utilization

## Description of issue (what needs changing):

Referring to the following line:

> tf.data achieves high throughput by trying to make the best possible use of available resources. In general, even when running your model on an accelerator like a GPU or TPU, the tf.data pipelines are run on the CPU. You can check your utilization with tools like sar and htop, or in the cloud monitoring console if you’re running on GCP.

The link attached to "cloud monitoring console" is invalid.

**Comment by ashwin-phadke** [comment]
I'dl like to take this up.

**Comment by jvishnuvardhan** [comment]
I am closing this issue as it is resolved in `tf-nightly` through the https://github.com/tensorflow/docs/pull/1648 that was merged already. New change will be reflected soon. 

[here](https://cloud.google.com/monitoring/docs/monitoring_in_console) is the correct link. Thanks!
