### ISSUE TITLE
make failed and it print this . The keywords is Undefine Reference

### ISSUE THREAD

**Issue by TSrain** [tensorflow/tensorflow#42216]
../../lib/libhuge_ctr_static.a(parser.cpp.o): In function `void HugeCTR::create_pipeline_internal<long long>(std::unique_ptr<HugeCTR::DataReader<long long>, std::default_delete<HugeCTR::DataReader<long long> > >&, std::unique_ptr<HugeCTR::DataReader<long long>, std::default_delete<HugeCTR::DataReader<long long> > >&, std::vector<std::unique_ptr<HugeCTR::Embedding<long long>, std::default_delete<HugeCTR::Embedding<long long> > >, std::allocator<std::unique_ptr<HugeCTR::Embedding<long long>, std::default_delete<HugeCTR::Embedding<long long> > > > >&, std::vector<std::unique_ptr<HugeCTR::Network, std::default_delete<HugeCTR::Network> >, std::allocator<std::unique_ptr<HugeCTR::Network, std::default_delete<HugeCTR::Network> > > >&, std::shared_ptr<HugeCTR::GPUResourceGroup> const&, nlohmann::basic_json<std::map, std::vector, std::string, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer>, unsigned long, bool, float)':
parser.cpp:(.text+0xc233): undefined reference to `HugeCTR::EmbeddingCreator::create_localized_sparse_embedding_hash(std::vector<std::shared_ptr<HugeCTR::Tensor<long long> >, std::allocator<std::shared_ptr<HugeCTR::Tensor<long long> > > > const&, std::vector<std::shared_ptr<HugeCTR::Tensor<long long> >, std::allocator<std::shared_ptr<HugeCTR::Tensor<long long> > > > const&, HugeCTR::SparseEmbeddingHashParams_, std::string, std::shared_ptr<HugeCTR::GPUResourceGroup> const&)'
../../lib/libhuge_ctr_static.a(parser.cpp.o): In function `void HugeCTR::create_pipeline_internal<unsigned int>(std::unique_ptr<HugeCTR::DataReader<unsigned int>, std::default_delete<HugeCTR::DataReader<unsigned int> > >&, std::unique_ptr<HugeCTR::DataReader<unsigned int>, std::default_delete<HugeCTR::DataReader<unsigned int> > >&, std::vector<std::unique_ptr<HugeCTR::Embedding<unsigned int>, std::default_delete<HugeCTR::Embedding<unsigned int> > >, std::allocator<std::unique_ptr<HugeCTR::Embedding<unsigned int>, std::default_delete<HugeCTR::Embedding<unsigned int> > > > >&, std::vector<std::unique_ptr<HugeCTR::Network, std::default_delete<HugeCTR::Network> >, std::allocator<std::unique_ptr<HugeCTR::Network, std::default_delete<HugeCTR::Network> > > >&, std::shared_ptr<HugeCTR::GPUResourceGroup> const&, nlohmann::basic_json<std::map, std::vector, std::string, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer>, unsigned long, bool, float)':
parser.cpp:(.text+0x10df3): undefined reference to `HugeCTR::EmbeddingCreator::create_localized_sparse_embedding_hash(std::vector<std::shared_ptr<HugeCTR::Tensor<unsigned int> >, std::allocator<std::shared_ptr<HugeCTR::Tensor<unsigned int> > > > const&, std::vector<std::shared_ptr<HugeCTR::Tensor<unsigned int> >, std::allocator<std::shared_ptr<HugeCTR::Tensor<unsigned int> > > > const&, HugeCTR::SparseEmbeddingHashParams_, std::string, std::shared_ptr<HugeCTR::GPUResourceGroup> const&)'
../../lib/libhuge_ctr_static.a(parser.cpp.o): In function `HugeCTR::DataReader<long long>::create_heap_workers_()':
parser.cpp:(.text._ZN7HugeCTR10DataReaderIxE20create_heap_workers_Ev[_ZN7HugeCTR10DataReaderIxE20create_heap_workers_Ev]+0x6f1): undefined reference to `tensorflow::io::RecordReaderOptions::CreateRecordReaderOptions(std::string const&)'
../../lib/libhuge_ctr_static.a(parser.cpp.o): In function `HugeCTR::DataReader<unsigned int>::create_heap_workers_()':
parser.cpp:(.text._ZN7HugeCTR10DataReaderIjE20create_heap_workers_Ev[_ZN7HugeCTR10DataReaderIjE20create_heap_workers_Ev]+0x6f1): undefined reference to `tensorflow::io::RecordReaderOptions::CreateRecordReaderOptions(std::string const&)'
../../lib/libhuge_ctr_static.a(parser.cpp.o): In function `HugeCTR::TFrecordFileSource::process_features(float*)':
parser.cpp:(.text._ZN7HugeCTR18TFrecordFileSource16process_featuresEPf[_ZN7HugeCTR18TFrecordFileSource16process_featuresEPf]+0x41): undefined reference to `tensorflow::io::RecordReader::ReadRecord(unsigned long long*, std::string*)'
parser.cpp:(.text._ZN7HugeCTR18TFrecordFileSource16process_featuresEPf[_ZN7HugeCTR18TFrecordFileSource16process_featuresEPf]+0x36a): undefined reference to `tensorflow::strings::StrCat(tensorflow::strings::AlphaNum const&)'
parser.cpp:(.text._ZN7HugeCTR18TFrecordFileSource16process_featuresEPf[_ZN7HugeCTR18TFrecordFileSource16process_featuresEPf]+0x1259): undefined reference to `google::protobuf::io::CodedInputStream::ReadString(std::string*, int)'
../../lib/libhuge_ctr_static.a(parser.cpp.o): In function `HugeCTR::TFrecordFileSource::next_source()':
parser.cpp:(.text._ZN7HugeCTR18TFrecordFileSource11next_sourceEv[_ZN7HugeCTR18TFrecordFileSource11next_sourceEv]+0x54): undefined reference to `tensorflow::Env::NewRandomAccessFile(std::string const&, std::unique_ptr<tensorflow::RandomAccessFile, std::default_delete<tensorflow::RandomAccessFile> >*)'
collect2: error: ld returned 1 exit status
utest/parser/CMakeFiles/parser_test.dir/build.make:110: recipe for target 'bin/parser_test' failed
make[2]: *** [bin/parser_test] Error 1
CMakeFiles/Makefile2:1781: recipe for target 'utest/parser/CMakeFiles/parser_test.dir/all' failed
make[1]: *** [utest/parser/CMakeFiles/parser_test.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by TSrain** [comment]
i solve this problem by  using **_cmake -DCMAKE_CXX_COMPILER=$(which g++) -DCMAKE_C_COMPILER=$(which gcc) -DCMAKE_BUILD_TYPE=Release -DSM=61 .._**  when cmake，and  make successfully

**Comment by ravikyram** [comment]
@TSrain 

Glad to know that issue was resolved.Please, close this thread as your issue was resolved.Thanks!
