### ISSUE TITLE
Wheel size increase from 2.0 to 2.1 onward

### ISSUE THREAD

**Issue by RaresDima** [tensorflow/tensorflow#42219]
I am asking this here because I could not find any centralized patch notes that explain this.

If we go to pypi and look at tensorflow 2.0 for py3.6 win64 it has a big, but reasonable wheel size of ~50MB:

https://pypi.org/project/tensorflow/2.0.0/#files

However release 2.1 jumps that number to ~355 MB and release 2.2 goes to ~460 MB. This is an almost x10 size increase!

I highly doubt that almost half a GB of raw code was added (was it?) so I am wondering what exactly was added since a Google search seems to yield no results.

**Comment by mihaimaruseac** [comment]
TF 2.1 and later have a single pip package for both CPU and GPU. The GPU kernels and glue to CUDA take the additional space.

We are working on reducing size of pip package through multiple projects, including modularization, reducing number of CUDA capabilities we support, selective registration of kernels, etc.

Release notes, either in repo (https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) or on individual releases (https://github.com/tensorflow/tensorflow/releases/) should contain more details about every step taken.

**Comment by RaresDima** [comment]
@mihaimaruseac Thank you!

**Comment by barbolo** [comment]
@mihaimaruseac Do you have any resource that explains how to use selective registration of kernels when build `tflite_runtime` with Flex delegates?
