### ISSUE TITLE
Typo in TFLite CoreML framework build command example

### ISSUE THREAD

**Issue by kalaluthien** [tensorflow/tensorflow#42217]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
There is a single typo in build command example:

https://github.com/tensorflow/tensorflow/blob/4b901e2a7ea0b849ad1d1cea311cd131bc089ebe/tensorflow/lite/experimental/ios/BUILD.apple#L82-L94

This introduce bazel build fails to newbies:

```
ERROR: Skipping '//tensorflow/lite/experimental/ios:TensorFlowLiteCCoreMl_framework': no such target '//tensorflow/lite/experimental/ios:TensorFlowLiteCCoreMl_framework': target 'TensorFlowLiteCCoreMl_framework' not declared in package 'tensorflow/lite/experimental/ios' (did you mean 'TensorFlowLiteCCoreML_framework'?) defined by /Users/mumu/hpcnt/tensorflow/tensorflow/lite/experimental/ios/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//tensorflow/lite/experimental/ios:TensorFlowLiteCCoreMl_framework': target 'TensorFlowLiteCCoreMl_framework' not declared in package 'tensorflow/lite/experimental/ios' (did you mean 'TensorFlowLiteCCoreML_framework'?) defined by /Users/mumu/hpcnt/tensorflow/tensorflow/lite/experimental/ios/BUILD
INFO: Elapsed time: 21.011s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
```

**Describe the expected behavior**

At Line 82, `TensorFlowLiteCCoreMl_framework` should be fixed to `TensorFlowLiteCCoreML_framework`

**Standalone code to reproduce the issue**

**Other info / logs** Include any logs or source code that would be helpful to

**Comment by jvishnuvardhan** [comment]
@kalaluthien Thanks for finding the typo. we have updated the doc and it is already reflecting in the `master` [branch](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/ios/BUILD.apple#L82).

As this is resolved, I am closing this issue. Thanks!
