### ISSUE TITLE
TensorFlow model in commercial projects

### ISSUE THREAD

**Issue by swel4ik** [tensorflow/tensorflow#42227]
Hi, I  don't understand the various licenses well. Now I am working with my mobile app, and I would like to know: can I use tensorflow models (like posenet) in commercial projects? Thank you

**Comment by MarkDaoust** [comment]
Hi @swel4ik, 

TensorFlow's license is here: https://github.com/tensorflow/tensorflow/blob/master/LICENSE
Beyond that, we can't provide any legal advice.  You may want to consult your own counsel if you have questions.
