### ISSUE TITLE
Please add tf 1.15's related cuda/cudnn version

### ISSUE THREAD

**Issue by zchrissirhcz** [tensorflow/tensorflow#42222]
Hi, the official documentation webpage gives the version table for tensorflow version and cuda/cudnn version:

https://www.tensorflow.org/install/source#common_installation_problems

However, there's no information about tensorflow 1.15.

Please consider adding it. Thanks.

**Comment by amahendrakar** [comment]
@zchrissirhcz,
Please check the [GPU section](https://www.tensorflow.org/install/source#gpu) under tested build configurations. The table has TensorFlow v1.15 listed along with the compatible CUDA and cuDNN versions. 

Screenshot for reference:
![image](https://user-images.githubusercontent.com/57165142/89875527-fc45ae80-dbda-11ea-9d7e-8e5b07c8d1c1.png)

Thanks!

**Comment by zchrissirhcz** [comment]
@amahendrakar OK, let me make it clear. 

There **is** TensorFlow v1.15 in the **English** version of this webpage, but isn't in the **Chinese** version. It directly show me the Chinese version webpage thus I didn't find it.

**Comment by amahendrakar** [comment]
@zchrissirhcz,
Could you please confirm if [this](https://www.tensorflow.org/install/source?hl=zh-cn#gpu) is the page you are referring to? Thanks!

**Comment by zchrissirhcz** [comment]
@amahendrakar Yes, you are right, [this](https://www.tensorflow.org/install/source?hl=zh-cn#gpu) is the page I'm refering to.

**Comment by amahendrakar** [comment]
@zchrissirhcz,
The [documentation](https://www.tensorflow.org/install/source?hl=zh-cn#gpu) has been updated and CUDA/cuDNN versions have been added for TensorFlow v1.15. 

Closing this issue as resolved. Please feel free to re-open if necessary. Thanks!

**Comment by zchrissirhcz** [comment]
@amahendrakar  Thanks for your contribution. 
Right now I can't access tensorflow official site, blocked by the GFW. When accesible, will try again for validation.

**Comment by zchrissirhcz** [comment]
![image](https://user-images.githubusercontent.com/3831847/107754570-a1913900-6d5c-11eb-9f1f-4949b42b8d1b.png)

@amahendrakar Validated, fixed. Good job!
