### ISSUE TITLE
version 2.3.0 build error: user_ops_gen_cc: undefined symbol

### ISSUE THREAD

**Issue by Char-Aznable** [tensorflow/tensorflow#42221]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  CentOS Linux release 7.8.2003
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3.0
- Python version: 3.8.5
- Installed using virtualenv? pip? conda?: build from source
- Bazel version (if compiling from source): 3.4.1 or 3.1.0 (both give the same error shown below)
- GCC/Compiler version (if compiling from source): gcc 8.4.0
- CUDA/cuDNN version: 11.0
- GPU model and memory: RTX2080; 10GB

**Describe the problem**

I am building version 2.3.0 from source and get this error:
```
bazel-out/k8-opt-exec-50AE0418/bin/tensorflow/cc/ops/user_ops_gen_cc: symbol lookup error: bazel-out/k8-opt-exec-50AE0418/bin/tensorflow/cc/ops/user_ops_gen_cc: undefined symbol: _ZN10tensorflow8OpKernel11TraceS
tringB5cxx11EPNS_15OpKernelContextEb
```
The exact command that fails is:
```
cd ../tensorflow_cache_dir/_bazel_aznb/73fa4b3fd284d99232eec1bc01a9093d/execroot/org_tensorflow &&
exec env - \
CUDA_TOOLKIT_PATH=/home/aznb/.linuxbrew/Cellar/cuda/11.0 \
CUDNN_INSTALL_PATH=/home/aznb/.linuxbrew/Cellar/cuda/11.0 \
GCC_HOST_COMPILER_PATH=/home/aznb/.linuxbrew/Cellar/gcc@8/8.4.0_1/bin/gcc-8 \
PATH=/usr/bin:/bin:/home/aznb/.linuxbrew/bin \
PYTHONPATH=/home/aznb/.pyenv/versions/venv-tensorflow-py3.8.5-cuda11.0/lib/python3.8/site-packages \
PYTHON_BIN_PATH=/home/aznb/.pyenv/shims/python3 \
PYTHON_LIB_PATH=/home/aznb/.pyenv/versions/venv-tensorflow-py3.8.5-cuda11.0/lib/python3.8/site-packages \
TF2_BEHAVIOR=1 \
TF_CONFIGURE_IOS=0 \
TF_CUDA_COMPUTE_CAPABILITIES=6.1,7.5 \
TF_CUDA_PATHS=/home/aznb/.linuxbrew/Cellar/cuda/11.0 \
TF_CUDA_VERSION=11.0 \
TF_CUDNN_VERSION='' \
TF_NEED_CUDA=1 \
/bin/bash bazel-out/k8-opt/bin/tensorflow/cc/user_ops_genrule.genrule_script.sh
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
export CUDA_TOOLKIT_PATH=$CUDAPATH                                                                                                                                                                                 
export CUDNN_INSTALL_PATH=$CUDA_TOOLKIT_PATH                                                                                                                                                                       
export TF_CUDA_VERSION="$($CUDA_TOOLKIT_PATH/bin/nvcc --version | sed -n 's/^.*release \(.*\),.*/\1/p')"
export TF_CUDA_COMPUTE_CAPABILITIES=$CUDACC
export TF_CUDA_PATHS=$CUDAPATH
export TF_NEED_CUDA=1

export TF_CUDA_CLANG=0
export TF_NEED_GCP=0
export TF_NEED_HDFS=0
export TF_NEED_OPENCL=0
export TF_NEED_JEMALLOC=1
export TF_ENABLE_XLA=0
export TF_NEED_VERBS=0
export TF_CUDNN_VERSION="$(sed -n 's/^#define CUDNN_MAJOR\s*\(.*\).*/\1/p' $CUDNN_INSTALL_PATH/include/cudnn.h)"
export TF_NEED_MKL=0
export TF_DOWNLOAD_MKL=0
export TF_DOWNLOAD_CLANG=0
export TF_NEED_AWS=0
export TF_NEED_MPI=0
export TF_NEED_GDR=0
export TF_NEED_S3=0
export TF_NEED_ROCM=0
export TF_NEED_OPENCL_SYCL=0
export TF_SET_ANDROID_WORKSPACE=0
export TF_NEED_COMPUTECPP=0
# for some reason, this gcc path can't be a symlink to the actual path
export GCC_HOST_COMPILER_PATH=$LINUXBREWHOME/bin/gcc-8
export CC_OPT_FLAGS="-march=native"
#export TF_SET_ANDROID_WORKSPACE=0
export TF_NEED_KAFKA=0
export TF_NEED_TENSORRT=0
#output cache dir
export TEST_TMPDIR="../tensorflow_cache_dir"
export TEMPOUTPUT="./output_dir"
bazel clean --async --expunge
rm -rf ~/.cache/bazel
./configure

bazel build --explain=buildwhl.txt --verbose_explanations -s --verbose_failures --jobs 24 --crosstool_top=@local_config_cuda//crosstool:toolchain --config=noaws --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@Char-Aznable 

Can you please refer to below issues with the same error:
#35115 [link](https://github.com/tensorflow/tensorflow/issues/15958#issuecomment-356146258) [link1](https://github.com/tensorflow/tensorflow/issues/35584#issuecomment-570920203)

**Comment by Char-Aznable** [comment]
@Saduf2019 Those are irrelevant. I managed to build v2.1 with CUDA 10.2. I am using bazel 3.4.0 as required. The error is reproducible with all cache removed

**Comment by Char-Aznable** [comment]
I got same error when building with bazel 3.1.0

**Comment by angerson** [comment]
Can you try and reproduce this at `master` HEAD, please?

**Comment by Char-Aznable** [comment]
It doesn't work. Same error

**Comment by Char-Aznable** [comment]
I got the same error with 2.6.0

**Comment by sanatmpa1** [comment]
@Char-Aznable,

Are you following this [guide](https://www.tensorflow.org/install/source) and you have other configurations like Python version, GCC version,CUDA version and etc same as the tested build configurations in this [link](https://www.tensorflow.org/install/source#tested_build_configurations)?

**Comment by sanatmpa1** [comment]
Also you have gcc 8.4.0 compiler, whereas most of the tested builds has GCC version 7.3.1, Can you fix this and try building to see if the issue persists? Thanks!

**Comment by Char-Aznable** [comment]
@sanatmpa1 That was what I did. BTW, It would be much easier to locate the problem if someone from your team can point out the specific compiling commands involved in the error so that I don't have to go through the entire build process again and again. Also, there are a lot of things to try obviously but wouldn't it be more efficient for you to give me some hint on what went wrong with the error?

**Comment by gadagashwini** [comment]
@Char-Aznable,
This error might be when we install multiple versions of Tensorflow. Each Installation creates `/opt/tensorlibs` directory where gcc linking will be available. While building Tensorflow it takes static library directory.

Recommend to uninstall existing Tensorflow version or create new virtual environment or  remove `/opt/tensorlibs` directory. clear the cache before running Bazel build command `bazel clean --expunge`. This should solve your problem.
Thanks!

**Comment by Char-Aznable** [comment]
> Recommend to uninstall existing Tensorflow version or create new virtual environment or remove `/opt/tensorlibs` directory. clear the cache before running Bazel build command `bazel clean --expunge`. This should solve your problem. Thanks!

That was what I did in the OP -- the build script I posted remove all build cache before rebuild. I also tried building this on different machines from scratch. I don't think this is the cause of the problem

**Comment by gadagashwini** [comment]
@Char-Aznable,
Issue is not reproducible on my system. 
Could you please try workaround mention on similar issue [#48064](https://github.com/tensorflow/tensorflow/issues/48064#issuecomment-811554566)
