### ISSUE TITLE
Tf-nightly 2.4.0 does not recognize Cuda 10.2

### ISSUE THREAD

**Issue by Echambouleyron** [tensorflow/tensorflow#42229]
### System information
-   **TF-nightly 2.4.0-dev20200808 installed with PIP**:
-   **OS Platform and Distribution: Windows 10**:
-   **Python version:  3.8.5**:
-   **CUDA/cuDNN version: 10.2**:
-   **GPU model and memory: GeForce GTX 1050 Ti**:

### Describe the problem
After installing tf-nightly and cuda 10.2 and changing the corresponding environmental variables, tensorflow does not recognize CUDA 10.2.
### Source code / logs
While importing tensorflow:
2020-08-11 10:04:37.795114: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-08-11 10:04:37.798451: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

**Comment by amahendrakar** [comment]
@Echambouleyron,
Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/38194#issuecomment-657233766) from a similar issue and let us know if it works. Thanks!

**Comment by Echambouleyron** [comment]
Thank you for the answer. I renamed the folder in question as suggested in that post and even though I am not getting the error I mentioned above, the problem remains. When I run my model the ETA is very high, which suggests that tensorflow is not using GPU. Is quite strange because when I run tf.config.list_physical_devices("GPU") I get: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')].

**Comment by amahendrakar** [comment]
@Echambouleyron,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!
