### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError : when trying to run rasa init --no-prompt

### ISSUE THREAD

**Issue by garchaaman19** [tensorflow/tensorflow#42226]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): **pip3 install --upgrade tensorflow rasa**
**pip3 install --upgrade tensorflow-addons rasa**
- TensorFlow version (use command below):tensorflow 2.3.0  , **v2.3.0-rc2-23-gb36436b087 2.3.0**
- Python version: **Python 3.6.9**

**Describe the current behavior**
When I am trying to run rasa init command it throws me error tensorflow.python.framework.errors_impl.NotFoundError

**Describe the expected behavior**
It should train the model.

**Other info / logs** Include any logs or source code that would be helpful to
tensorflow.python.framework.errors_impl.NotFoundError: /home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/tensorflow_addons/custom_ops/activations/_activation_ops.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl11string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS8_EE

**Comment by amahendrakar** [comment]
@garchaaman19,
Could you please the exact sequence of commands / steps that you executed before running into the problem? Thanks!
