### ISSUE TITLE
[TFLite micro] Max number of channels (kMaxChannels) for DepthwiseConv should be updated (CMSIS-NN)

### ISSUE THREAD

**Issue by biagiom** [tensorflow/tensorflow#42224]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): f63877d6371aa5e47391e520a29a6aa1ef2e0199
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Any

**Describe the problem**
The current implementation of DepthwiseConv based on CMSIS-NN [defines the maximum number of channels as a constant value (set to 256)](https://github.com/tensorflow/tensorflow/blob/b4ab032959b2fb68022b2cf70de46e9564a50d6f/tensorflow/lite/micro/kernels/cmsis-nn/depthwise_conv.cc#L40). This can be a limitation for someone that want to run a model having one or more DepthwiseConv ops with a number of channels greater than 256. In fact, in that case, the assertion `TFLITE_DCHECK_LE(num_channels, kMaxChannels);` will become false and inference will stop.
There are several ways to solve this limitation, each having some pros and cons:

- The simplest way is to increase the value of `kMaxChannels`, for example to 1024. This will increase the set of models that can be run such as MobileNet v1 with alpha=100 or 75. On the other hand, when we need to run a DepthwiseConv op with a number of channels less than 1024, we will allocate more memory (for `per_channel_output_multiplier` and `per_channel_output_shift`) than what is needed.
I am also aware that when designing a model for a MCU, the 'keep-it-simple' (I would also say 'keep-it-small') principle is very important and useful in order to reduce memory and computational requirements. So, in this case, the value of `kMaxChannels` represent an important trade-off.
A variant of this approach is to allow the user to set the max number of channels of all DepthwiseConv ops through compile-time constants and macros. For example, we can use the following code snippet to set it:
```
#if defined(TFLITE_DEPTHWISECONV_MAX_CHANNELS) && TFLITE_DEPTHWISECONV_MAX_CHANNELS > 0
  constexpr int kMaxChannels = TFLITE_DEPTHWISECONV_MAX_CHANNELS;
#else 
  constexpr int kMaxChannels = 256;
#endif
```
The user can re-define it at compile time according to the model to be run (for example compiling the source code with `-DTFLITE_DEPTHWISECONV_MAX_CHANNELS=1024`).

- Another way is to use dynamic allocation in order to allocate only the needed memory for the temp buffers. On the other hand, dynamic memory allocation can result in memory fragmentation or runtime issues (especially when memory is not managed by a  RTOS or because it is general quite small in size), and so it is generally avoided (think about the use of the `tensor_arena`). However this approach could be quite useful to save memory and if the number of channels is not very high heap issues like overflow should not happen.
I'm also wondering if it is possible to allocate memory for the needed buffers in the `tensor_arena`.

- Other suggestions ?

So, my question is: can we handle `kMaxChannels` in a better way ?

Best regards,
Biagio.

**Comment by freddan80** [comment]
I think we can close this issue. Fix [here](https://github.com/tensorflow/tensorflow/commit/b18a353b7819c4049e70c6b77594221df1563fe7#diff-0245be3835c3d7fa9d9e844a74d9db3bfc05afbd412f77b4368b3f2211b3b2ad).

**Comment by biagiom** [comment]
Great !
