### ISSUE TITLE
ValueError when using dictionary format for input of optimizer options in Tensorflow 2.2.0 Keras models

### ISSUE THREAD

**Issue by hallabjorg5** [tensorflow/tensorflow#42234]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes (but very basic)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): I used pip
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6.10
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: More than one machine

**Describe the current behavior**
I am using the dictionary format (see code below) to input options to an optimizer when compiling a Tensorflow Keras model. However, in Tensorflow 2.2.0 this throws an error. I fixed this issue for now by switching back to Tensorflow 2.1.0. Another workaround is to define the loss beforehand as tf.keras.losses.Nadam(**config). Neither of those is a final solution so I thought it best to report this bug. 

**Describe the expected behavior**
The dictionary format should work for easy input of non-default options of optimizers when compiling Keras models with Tensorflow 2.2.0.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python script
import tensorflow as tf
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(3, activation='sigmoid'))
compiler_params = {
    "optimizer": {
        'class_name': 'Nadam',
        'config': {
            'lr': 0.0001
        }
    }
}
model.compile(**compiler_params)
```

**Other info / logs** 
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```python script
ValueError                                Traceback (most recent call last)
<ipython-input-2-187c8cc52bd6> in <module>
     11     }
     12 }
---> 13 model.compile(**compiler_params)
     14

~\AppData\Local\Continuum\anaconda3\envs\cinc3\lib\site-packages\tensorflow\python\keras\engine\training.py in compile(self, optimizer, loss, metrics, loss_weights, sample_weight_mode, weighted_metrics, **kwargs)
    326       self._run_eagerly = kwargs.pop('run_eagerly', None)
    327
--> 328       self.optimizer = self._get_optimizer(optimizer)
    329       self.compiled_loss = compile_utils.LossesContainer(
    330           loss, loss_weights, output_names=self.output_names)

~\AppData\Local\Continuum\anaconda3\envs\cinc3\lib\site-packages\tensorflow\python\keras\engine\training.py in _get_optimizer(self, optimizer)
    348       return opt
    349
--> 350     return nest.map_structure(_get_single_optimizer, optimizer)
    351
    352   @trackable.no_automatic_dependency_tracking

~\AppData\Local\Continuum\anaconda3\envs\cinc3\lib\site-packages\tensorflow\python\util\nest.py in map_structure(func, *structure, **kwargs)
    615
    616   return pack_sequence_as(
--> 617       structure[0], [func(*x) for x in entries],
    618       expand_composites=expand_composites)
    619

~\AppData\Local\Continuum\anaconda3\envs\cinc3\lib\site-packages\tensorflow\python\util\nest.py in <listcomp>(.0)
    615
    616   return pack_sequence_as(
--> 617       structure[0], [func(*x) for x in entries],
    618       expand_composites=expand_composites)
    619

~\AppData\Local\Continuum\anaconda3\envs\cinc3\lib\site-packages\tensorflow\python\keras\engine\training.py in _get_single_optimizer(opt)
    342
    343     def _get_single_optimizer(opt):
--> 344       opt = optimizers.get(opt)
    345       if (self._dtype_policy.loss_scale is not None and
    346           not isinstance(opt, lso.LossScaleOptimizer)):

~\AppData\Local\Continuum\anaconda3\envs\cinc3\lib\site-packages\tensorflow\python\keras\optimizers.py in get(identifier)
    900     return deserialize(config)
    901   else:
--> 902     raise ValueError('Could not interpret optimizer identifier:', identifier)

ValueError: ('Could not interpret optimizer identifier:', 0.0001)
```

**Comment by Saduf2019** [comment]
@hallabjorg5 
Is there any particular reason for using a dictionary, I have tried the code with out dictionary and it works with out error.
Can you please refer to [this link](https://www.tensorflow.org/api_docs/python/tf/keras/Sequential) and update, nowhere has a dict been used.

**Comment by hallabjorg5** [comment]
Apart from backwards compatibility reasons, it has been a very nice feature to easily feed parameters from config files.

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF v2.5 ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/fbe069571ded5bcf915f5f766cf6c71b/untitled71.ipynb)..Thanks !

**Comment by mohantym** [comment]
Hi @hallabjorg5 ! According to this [document](https://keras.io/api/models/model_training_apis/) ,You can pass only a string value for optimizer  and dictionary/list for other parameters in model.compile.

**Comment by rchao** [comment]
Is it possible that you create an optimizer object and provide it to `Model.compile()` instead of a dict?

**Comment by mohantym** [comment]
Hi @hallabjorg5 !
This issue is getting resolved after passing compile_param like below. Attached [gist ](https://colab.sandbox.google.com/gist/mohantym/7840b22748d35c80eaf843f59d6ed35e/untitled71.ipynb#scrollTo=uV6PdRB00qhm)for reference.
```
compile_kwargs = {
        'loss': tf.keras.losses.MeanSquaredError(),
        'optimizer': tf.keras.optimizers.Nadam(learning_rate=.001),
    }
model.compile(**compile_kwargs)
```

Thank you!
