### ISSUE TITLE
Unrecognized device error when setting memory growth

### ISSUE THREAD

**Issue by Echambouleyron** [tensorflow/tensorflow#42236]
**System information**
- OS Platform and Distribution : Windows 10
- TensorFlow installed from: PIP
- TensorFlow version: tf-nightly-gpu 2.4.0-dev20200808
- Python version: 3.7.4
- Installed using virtualenv? PIP
- CUDA/cuDNN version: CUDA 10.2
- GPU model and memory: GeForce GTX 1050 Ti

**Describe the problem**
When listing available physical devices GPU does appear. Nonetheless, when setting memory growth (tf.config.experimental.set_memory_growth(gpu, True)), python does not recognize the device. 

**Any other info / logs**
ValueError: Unrecognized device: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

**Comment by ravikyram** [comment]
@Echambouleyron 

Please, provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!
