### ISSUE TITLE
There is memory leak in Invoke() of gpu delegate (OpenCL) in Tensorflow lite v2.3.0

### ISSUE THREAD

**Issue by wanglei-source** [tensorflow/tensorflow#42252]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android armv8
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): tag v2.3.0
- Python version:
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source):  android-ndk-r18b
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I use tflite with delegate creating by TfLiteGpuDelegateV2Create(&options), and call ModifyGraphWithDelegate and AllocateTensors, and when I call interpreter->Invoke() in a loop, I see the memory increasing continuously.
**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

std::unique_ptr<tflite::FlatBufferModel> model;
tflite::ops::builtin::BuiltinOpResolver op_resolver;
std::unique_ptr<tflite::Interpreter> interpreter;
TfLiteDelegate* delegate = nullptr;

        struct : public tflite::ErrorReporter {
            virtual int Report(const char *format, va_list args) {
                return __android_log_vprint(ANDROID_LOG_INFO, "native_jni", format, args);
            }
        } er;
        model = tflite::FlatBufferModel::BuildFromFile(
                "/storage/emulated/0/Android/data/com.example.myapplication2/files/model.tflite",
                &er);
        if (!model) {
            LOG("build model error");
            return;
        } else {
            LOG("build model success:%p", model.get());
        }
        tflite::InterpreterBuilder(*model, op_resolver)(&interpreter);

        TfLiteGpuDelegateOptionsV2 options = TfLiteGpuDelegateOptionsV2Default();
        options.is_precision_loss_allowed = 1;
        options.inference_preference = TFLITE_GPU_INFERENCE_PREFERENCE_SUSTAINED_SPEED;
        options.inference_priority1 = TFLITE_GPU_INFERENCE_PRIORITY_MIN_LATENCY;
        options.inference_priority2 = TFLITE_GPU_INFERENCE_PRIORITY_AUTO;
        options.inference_priority3 = TFLITE_GPU_INFERENCE_PRIORITY_AUTO;
        options.experimental_flags = TFLITE_GPU_EXPERIMENTAL_FLAGS_CL_ONLY;
        options.max_delegated_partitions = 1;
        delegate = TfLiteGpuDelegateV2Create(&options);

        if (interpreter->ModifyGraphWithDelegate(delegate) != kTfLiteOk) {
            __android_log_print(ANDROID_LOG_INFO, "native_jni", "ModifyGraphWithDelegate error");
            return;
        }
        __android_log_print(ANDROID_LOG_INFO, "native_jni", "ModifyGraphWithDelegate success");
        if (interpreter->AllocateTensors() == kTfLiteOk) {
            __android_log_print(ANDROID_LOG_INFO, "native_jni", "allocate success");
        } else {
            __android_log_print(ANDROID_LOG_INFO, "native_jni", "allocate error");
        }
        while (true)
            interpreter->Invoke();

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

I suspect that the bug is something about using opencl. In  CLCommandQueue::DispatchImplicit (tensorflow/lite/delegates/gpu/cl/cl_command_queue.cc)，if I comment the code calling clEnqueueNDRangeKernel, the memory leak disappears.

**Comment by impjdi** [comment]
@wanglei-source 

Can you add details of the mobile device that you're using?  We need more info such as manufacturer & model, e.g. Samsung Galaxy S12, and your GPU specs, e.g. Adreno 650.

**Comment by NALanhnt2** [comment]
@impjdi hi. i use tensorflow-lite on ios. I have memory leak on iphone 6, but not on iphone 7+

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
