### ISSUE TITLE
Resource exhausted error during training on GPU with tensorflow 2.1.0

### ISSUE THREAD

**Issue by HelloFloor** [tensorflow/tensorflow#42257]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Custom code, but nothing really fancy
- TensorFlow installed from (source or binary): conda installed from source
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7
- CUDA/cuDNN version: CUDA 10.1
- GPU model and memory:  Quadro M1200. 8GB RAM

**Describe the current behavior**
I get an ResourceExhaustedError during my training. Even if I have a batch size of one. I have to predict and fit my data seperately, because in between I have to create a return function based on my predictions, which is input for the model.fit(). When I train my model, it starts with 4000 MB free memory in the GPU, after initialization it goes to 2022 MB free memory. It stays like this till 92 epochs, after 92 epochs it goes to 949 MB free memory. After 186 epochs it goes to 730 MB free memory in the GPU and after 197 epochs I get the error: 

ResourceExhaustedError:  OOM when allocating tensor with shape[108,32,103,66] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node MaxPoolGrad_2 (defined at C:\Users\Floor\Documents\Basic model\testmap\test.py:233) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_distributed_function_3945]

**Standalone code to reproduce the issue**
import tensorflow as tf
tf.config.experimental.set_memory_growth(tf.config.experimental.list_physical_devices('GPU')[0], True)
import numpy as np
import sys
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Dense, Conv2D, Activation, Flatten,MaxPooling2D

def create_model(): 
   
    model = Sequential()
    model.add(Conv2D(32, (6, 6), input_shape=( 108, 71, 9)))
    model.add(Activation("relu"))
    model.add(MaxPooling2D(pool_size=(2, 2)))

    model.add(Conv2D(32, (6, 6)))
    model.add(Activation("relu"))
    model.add(MaxPooling2D(pool_size=(2, 2)))

    model.add(Conv2D(32, (6, 6)))
    model.add(Activation("relu"))
    model.add(MaxPooling2D(pool_size=(2, 2)))

    model.add(Flatten())
    model.add(Dense(256, activation='relu'))
    model.add(Dense(1, activation = "sigmoid"))

    model.compile(optimizer=Adam(lr=0.00001/10), loss='mean_squared_error')  
    return(model)
For i in range(N) #amount of epochs
    model.predict(EpisodesP.reshape([-1,img_w, img_h, dim]))

    #Return function G 

    model.fit(EpisodesP, G, epochs = 1, verbose = 0, batch_size=1)

**Other info / logs** 
raceback (most recent call last):

  File "C:\Users\Floor\Documents\Basic model\testmap\test.py", line 267, in <module>
    history,value,model,loss, loss_episode= basic_code(Episodes, Success, N = 1000, P = 1)

  File "C:\Users\Floor\Documents\Basic model\testmap\test.py", line 233, in basic_code
    model.fit(EpisodesP, GP, epochs = 1, verbose = 0, batch_size=sum(TP)) #model fitted to get the loss

  File "C:\Users\Floor\anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)

  File "C:\Users\Floor\anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 342, in fit
    total_epochs=epochs)

  File "C:\Users\Floor\anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)

  File "C:\Users\Floor\anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))

  File "C:\Users\Floor\anaconda3\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)

  File "C:\Users\Floor\anaconda3\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 599, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable

  File "C:\Users\Floor\anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py", line 2363, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access

  File "C:\Users\Floor\anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py", line 1611, in _filtered_call
    self.captured_inputs)

  File "C:\Users\Floor\anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))

  File "C:\Users\Floor\anaconda3\lib\site-packages\tensorflow_core\python\eager\function.py", line 545, in call
    ctx=ctx)

  File "C:\Users\Floor\anaconda3\lib\site-packages\tensorflow_core\python\eager\execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)

  File "<string>", line 3, in raise_from

ResourceExhaustedError:  OOM when allocating tensor with shape[108,32,103,66] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node MaxPoolGrad_2 (defined at C:\Users\Floor\Documents\Basic model\testmap\test.py:233) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_distributed_function_3945]

Function call stack:
distributed_function

**Comment by ravikyram** [comment]
@HelloFloor 

Limiting gpu memory can help resolve OOM error.
See https://www.tensorflow.org/guide/using_gpu#allowing_gpu_memory_growth.
Thanks!

**Comment by HelloFloor** [comment]
@ravikyram, thank you for the answer. I tried that already, as is visible in my code snippet: 
import tensorflow as tf
tf.config.experimental.set_memory_growth(tf.config.experimental.list_physical_devices('GPU')[0], True)
Do you have any other advice how to fix this error? 
Thanks!

**Comment by gowthamkpr** [comment]
Your model just doesn't fit in your GPU. The memory of your GPU is not enough, that's why you're getting it.

Please take a look at this [issue](https://stackoverflow.com/questions/59394947/how-to-fix-resourceexhaustederror-oom-when-allocating-tensor) to solve this problem. Thanks!

**Comment by HelloFloor** [comment]
Thank you for the response. But if it doesn't fit, how is it possible that I can run it for almost 200 epochs before I get the ResourceExhaustedError?

**Comment by HelloFloor** [comment]
@gowthamkpr Would you know why I can run it for the 200 epochs before I get the ResourceExhaustedError? Thank you!

**Comment by gowthamkpr** [comment]
@HelloFloor As you are running your model for a longer time, the number of parameters of your model is increasing, thats the reason why you are running out of memory.

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 2 weeks. Please add additional comments for us to open this issue again. Thanks!

**Comment by AzinPoshtyar** [comment]
Decreasing batch size is helpful as well.

**Comment by syedhamzamohiuddin** [comment]
I am having issues. I getting this error after some epochs

**Comment by seemab-yamin** [comment]
I am having this issue during my first epoch.
ResourceExhaustedError: Graph execution error:
