### ISSUE TITLE
How to avoid AddV2 op in TFLite model?

### ISSUE THREAD

**Issue by zldrobit** [tensorflow/tensorflow#42256]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Ubuntu 18.04`
- TensorFlow installed from (source or binary): `pip/binary`
- TensorFlow version (or github SHA if from source):
`2.3.0`
`tflite 2.3.0 aar`

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
import tensorflow as tf                                                 
if not tf.__version__.startswith('1'):                                  
    import tensorflow.compat.v1 as tf                                   
tf.disable_v2_behavior()                                                
# Path to the frozen graph file                                         
graph_def_file = 'weights/yolov5s.pb'                                   
# A list of the names of the model's input tensors                      
input_arrays = ['images']                                               
# A list of the names of the model's output tensors                     
output_arrays = ['Concat_442']                                          
# Load and convert the frozen graph                                     
converter = tf.lite.TFLiteConverter.from_frozen_graph(                  
    graph_def_file, input_arrays, output_arrays)                        
# converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
#                                        tf.lite.OpsSet.SELECT_TF_OPS]  
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS]
converter.allow_custom_ops = True                                     
# converter.experimental_new_converter = False                            
tflite_model = converter.convert()                                      
# Write the converted model to disk                                     
open("weights/yolov5s.tflite", "wb").write(tflite_model)                
```

**The output from the converter invocation**

```
# Copy and paste the output here.
```

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
```

**Failure details**
I try to convert a Tensorflow GraphDef model to TFLite model, and I want to void AddV2 op.
If I use `tf.lite.OpsSet.SELECT_TF_OPS` option, FlexAddV2 will be generated instead of AddV2, which I would like to avoid too.
AddV2 is unsupported in tflite 2.3.0 aar.
FlexAddV2 is supported by flex delegate, but cannot work on Android Emulator (Pixel 2 API 24) .

The last thing I tried is substituting 'AddV2' with 'Add' manually in pbtxt format (AddV2 is in the original GraphDef ).
After I convert the processed GraphDef with tflite converter, the 'AddV2' ops emerge again.

PS:
https://github.com/tensorflow/tensorflow/issues/33393 says that TensorFlow 1.15 can resolve this problem.

**Comment by Saduf2019** [comment]
@zldrobit 
Please share complete information for us to replicate th eissue faced, i ran the code shared and face a different issue, [gist](https://colab.research.google.com/gist/Saduf2019/f43423fa38f09670c520cd8ac731758c/untitled365.ipynb) for the same.

**Comment by zldrobit** [comment]
@Saduf2019 I have uploaded the model to https://drive.google.com/file/d/1Z4jJ6DwP_A1o2fyN8oSMhEz6quRJ42Jf/view?usp=sharing

**Comment by Saduf2019** [comment]
@zldrobit 
I tried to access the link shared it says no preview available.

**Comment by zldrobit** [comment]
@Saduf2019 you can click *Download* to download the file directly.

**Comment by dan0978520303** [comment]
hi @zldrobit 
i have a same issue~~
and then test #33393 tensorflow 1.15.0 but have a trouble .
tensorflow-addons hope tensorflow1.15.0 to tensorflow 2.x 

under is command line log
'''
ImportError: This version of TensorFlow Addons requires TensorFlow version >= 2; Detected an installation of version 1.15.0. Please upgrade TensorFlow to proceed.
'''

ps . i install tensorflow-addons 0.5.0

**Comment by Saduf2019** [comment]
@zldrobit 
I ran the code on 2.3, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/9133c142c3231beb79c2ed6a86ae5330/untitled379.ipynb ), whereas in nightly i face an issue, [gist for nightly](https://colab.research.google.com/gist/Saduf2019/4d5120b5e5fc76c7329592bbeb4c89e7/untitled379.ipynb).

@dan0978520303 
Can you please try with later versions of tf and let us know if you still face any issues.

**Comment by dan0978520303** [comment]
> @dan0978520303
> Can you please try with later versions of tf and let us know if you still face any issues.

tf2.3 can work in my converter (pb -> tflite) but the graph appear AddV2 (have same trouble with author)

i still find version (tf, onnx-tf, ... ) such that AddV2 becoming Add

appreciation any advice !!!

**Comment by zldrobit** [comment]
@Saduf2019 , I notice that you changed 
`converter.allow_custom_ops = False` to `converter.allow_custom_ops = True`.
It won't work if you use `converter.allow_custom_ops = False`.

@dan0978520303, I find that TF v2.1.1 works in converting tf.AddV2 to tfl add.

I conjuecture that something is wrong with v2.3.0 MLIR TFLite converter.

**Comment by dan0978520303** [comment]
> @dan0978520303, I find that TF v2.1.1 works in converting tf.AddV2 to tfl add.
> 
> I conjuecture that something is wrong with v2.3.0 MLIR TFLite converter.

hi! thank you replication~
But i run the tf2.1.1 still appear familiar situation (attr.value_case() == AttrValue::kType (1 vs. 6)) ps : tf2.3 , it can work 
Can i see your environment (pb to tflite file )?
thx very much~~~
I stuck over 5 days =(

**Comment by zldrobit** [comment]
@dan0978520303  Of course.
It's just the [first thread](https://github.com/tensorflow/tensorflow/issues/42256#issue-677499982) I wrote in this issue .
It seems you are using the *OLD* TOCO converter, while the key is to turn the experimental converter switch *ON*:
```
converter.experimental_new_converter = True
```

**Comment by dan0978520303** [comment]
> @dan0978520303 Of course.
> It's just the [first thread](https://github.com/tensorflow/tensorflow/issues/42256#issue-677499982) I wrote in this issue .
> It seems you are using the _OLD_ TOCO converter, while the key is to turn the experimental converter switch _ON_:
> 
> ```
> converter.experimental_new_converter = True
> ```

thx~~~
I add this '''converter.experimental_new_converter = True ''' to avoid  AttrValue::kType (1 vs. 6) problem =)
But i encounter this error
'tfl.padv2' op failed to verify that operand 0's rank equals operand 1's size

Could you encounter this error ?
thx one more again !!!

**Comment by Saduf2019** [comment]
> @zldrobit

I ran the same code shared by you in the issue template where "converter.allow_custom_ops = True " is true and did not face any issues, as shared above with you.

**Comment by zldrobit** [comment]
@Saduf2019 I can convert the model using either v2.1.1 or v2.2.

**Comment by dan0978520303** [comment]
hi! @zldrobit 
Do you encounter an error : RuntimeError: Inputs and outputs not all float|uint8|int16 types.Node number 91 (ADD) failed to invoke. ?
I run this test to try if the tflite file can work on the android ~

this is my code : 
----------------------------------------------------------------------------------
import tensorflow as tf
import numpy as np

interpreter = tf.lite.Interpreter(model_path="0824.tflite")
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)
interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)
----------------------------------------------------------------------------------

thanks any advices ~~~

**Comment by Saduf2019** [comment]
@zldrobit 
Is this still an issue.

**Comment by zldrobit** [comment]
@Saduf2019 It's not an issue for me now. I had a workaround to convert a model using TF v2.1.1/v2.2, and infer the model with TF v2.3.

@dan0978520303 Have you tried to use the new experimental converter 
`converter.experimental_new_converter = False`?

**Comment by dan0978520303** [comment]
> @dan0978520303 Have you tried to use the new experimental converter
> `converter.experimental_new_converter = False`?

hi ! @zldrobit 
I have tried to change "converter.experimental_new_converter = False" and "converter using TF v2.1.1/v2.2 and infer TF v2.3".
Above, not work =(

**Comment by Saduf2019** [comment]
@dan0978520303 
Please provide complete stand alone(indented) code with system details or if possible share colab gist with error faced.

**Comment by dan0978520303** [comment]
> @dan0978520303
> Please provide complete stand alone(indented) code with system details or if possible share colab gist with error faced.

Hi @Saduf2019 
here is my code :  
https://colab.research.google.com/drive/19XeVNkstkkyGLQVy3J624-S13_G8PkEI#scrollTo=nFrw6ehVM-Aj

ps:

1. my env is conda
-------------------------------------------------------------------------
onnx 1.6.0
tensorflow-addons 0.11.1
pytorch 1.4.0
python  3.7.7
onnx-tf 1.6.0 (pip install git+https://github.com/onnx/onnx-tensorflow.git)

-------------------------------------------------------------------------

2. my unet  model is from  :  
-------------------------------------------------------------------------
https://github.com/switchablenorms/CelebAMask-HQ/tree/master/face_parsing

-------------------------------------------------------------------------

I really appreciate any advice !!!

**Comment by Saduf2019** [comment]
@dan0978520303 
I am unable to replicate your code, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/e5b7df3c91c19673a8b30d88685bc2c2/untitled395.ipynb).

**Comment by dan0978520303** [comment]
> @dan0978520303
> I am unable to replicate your code, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/e5b7df3c91c19673a8b30d88685bc2c2/untitled395.ipynb).

hi @Saduf2019 
My onnx model is too complex and then simplify the onnx model by onnx-simplifier.
It can work for me~

Hope this can help  =)

**Comment by Saduf2019** [comment]
@dan0978520303 
Can you please provide a colab gist with the error reported.

**Comment by dan0978520303** [comment]
> @dan0978520303
> Can you please provide a colab gist with the error reported, Can you please create a new issue with these details as the issue reported by user is resolved.

OK~
Let me list my process to open new issue.
Because i first use github, my report maybe not good~

**Comment by Saduf2019** [comment]
@dan0978520303 
Please submit the new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the issue template, so that we can track the issue there. Thanks!
