### ISSUE TITLE
Seg fault after installing version 2.3.0

### ISSUE THREAD

**Issue by yananchen1989** [tensorflow/tensorflow#42255]
I test my tensorflow by using the official guide:
`python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"`

It crashed with the info below:
```
2020-08-12 15:48:11.443235: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-08-12 15:48:11.443280: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

2020-08-12 15:48:13.930797: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-08-12 15:48:13.930842: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-08-12 15:48:13.930871: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (c4-miui-sec-preview0.bj): /proc/driver/nvidia/version does not exist
2020-08-12 15:48:13.931321: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-08-12 15:48:13.946009: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2399965000 Hz
2020-08-12 15:48:13.949467: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x59646e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-12 15:48:13.949501: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
tf.Tensor(-19.847946, shape=(), dtype=float32)
段错误
```
**段错误 means  seg fault**
I also test with my own code in Python and it also crashed randomly. 

Python Ver: 3.6.5

**Comment by LeicongLi** [comment]
You might want to share the specs of your environment, otherwise no one is able to reproduce.

**Comment by yananchen1989** [comment]
I am not in the account of ROOT, so I suppose I have use some functions which can not be used by non-administrator.

I run iPython in virtual environment.

(```
venv3.6) [work@c4-miui-sec-preview0 yanan]$ python3 --version
Python 3.6.5
(venv3.6) [work@c4-miui-sec-preview0 yanan]$ pip3 --version

pip 20.2.1 from /home/work/bigdata/venv3.6/lib/python3.6/site-packages/pip (python 3.6)
(venv3.6) [work@c4-miui-sec-preview0 yanan]$ virtualenv --version
virtualenv 20.0.30 from /home/work/.pyenv/versions/2.7.9/lib/python2.7/site-packages/virtualenv/__init__.pyc
```
and here is the pip list:


```
Package                Version
---------------------- --------------
-loud-ml-sdk           0.3.34
absl-py                0.7.1
argcomplete            1.10.0
asdf                   2.7.0
asn1crypto             0.24.0
astor                  0.7.1
astunparse             1.6.3
attrs                  19.3.0
bazel                  0.0.0.20200723
cachetools             4.1.1
certifi                2019.3.9
cffi                   1.12.3
chardet                3.0.4
cloud-ml-common        0.2.3
cloud-ml-sdk           0.4.13
cloudpickle            1.2.0
conda                  4.3.16
cPython                0.0.5
cryptography           2.7
cycler                 0.10.0
Cython                 0.29.13
dask                   1.2.2
decorator              4.4.0
docker                 4.3.0
fire                   0.1.3
galaxy-fds-sdk         1.4.21
gast                   0.3.3
google-auth            1.20.1
google-auth-oauthlib   0.4.1
google-pasta           0.1.8
grpcio                 1.20.1
h5py                   2.10.0
idna                   2.7
imageio                2.4.1
importlib-metadata     1.7.0
inflection             0.4.0
ipython                5.1.0
ipython-genutils       0.2.0
jieba                  0.39
jsonschema             3.2.0
Keras                  2.4.3
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.2
kiwisolver             1.1.0
lxml                   4.2.6
Markdown               3.1
matplotlib             3.0.3
mock                   3.0.4
netaddr                0.7.19
networkx               2.3
nltk                   3.4
numpy                  1.18.5
oauthlib               3.1.0
opencv-python          4.1.1.26
opt-einsum             3.3.0
pandas                 0.24.2
pexpect                4.8.0
pickleshare            0.7.5
Pillow                 6.0.0
pip                    20.2.1
progressbar2           3.38.0
prompt-toolkit         1.0.18
protobuf               3.12.4
ptyprocess             0.6.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycosat                0.6.3
pycparser              2.19
Pygments               2.6.1
pymongo                3.9.0
pyOpenSSL              19.0.0
pyparsing              2.4.0
pyrsistent             0.16.0
python-dateutil        2.8.0
python-utils           2.3.0
pytz                   2019.1
PyWavelets             1.0.3
PyYAML                 5.1.1
requests               2.24.0
requests-oauthlib      1.3.0
rsa                    4.6
ruamel.yaml            0.16.10
ruamel.yaml.clib       0.2.0
scikit-image           0.14.2
scikit-learn           0.20.3
scipy                  1.4.1
semantic-version       2.8.5
setuptools             41.0.0
Shapely                1.6.4.post2
simplegeneric          0.8.1
singledispatch         3.4.0.3
six                    1.12.0
sklearn                0.0
tensorboard            2.2.2
tensorboard-plugin-wit 1.7.0
tensorflow             2.2.0
tensorflow-estimator   2.2.0
termcolor              1.1.0
test1                  1.0
toolz                  0.9.0
tqdm                   4.27.0
traitlets              4.3.3
UNKNOWN                0.0.0
urllib3                1.23
wcwidth                0.2.5
websocket-client       0.57.0
Werkzeug               0.15.2
wheel                  0.33.1
wrapt                  1.11.2
xlrd                   1.2.0
zipp                   3.1.0
```

**Comment by yananchen1989** [comment]
I changed the version of tf to 2.2.0, as shown above. 
The issue is still there.

**Comment by ravikyram** [comment]
@yananchen1989 

Request you to fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by mihaimaruseac** [comment]
Can you upgrade `scipy` to 1.5.2?

**Comment by mihaimaruseac** [comment]
That being said, can you create a new virtualenvironment and install there instead? If you need `scipy`, make sure it is newer than 1.4.1

**Comment by sasikiran** [comment]
@mihaimaruseac Upgrading `scipy` to 1.5.2, `pip` throws:
`ERROR: tensorflow 2.3.0 has requirement scipy==1.4.1, but you'll have scipy 1.5.2 which is incompatible.`

Either way with `scipy 1.4.1` or `1.5.2`, the error doesn't seem to go away for me. 
I'm on a mac with `pip install tensorflow==2.3.0 `.

**Comment by mihaimaruseac** [comment]
Can you install in a new virtualenv and then post the output of `pip list`?

**Comment by miaotianshi** [comment]
I meet the same problem. I upgrade the OS from Debian 8 to Debian 9 and no seg fault occurs.
