### ISSUE TITLE
Custom TF metric: "Graph" tensor leakage

### ISSUE THREAD

**Issue by Jordy-VL** [tensorflow/tensorflow#42263]
System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): v2.2
Python version: 3.6.9
CUDA/cuDNN version: v10.2
GPU model and memory: GeForce GTX 1070 - 8117MiB

Describe the current behavior:
My custom metric works on sample inputs; yet after model compilation breaks down due to an error related to eager and graph tensors. I did not find anything specific which helps me resolve the issue.

Issue: 
```An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: Max:0
```

Describe the expected behavior:
Custom metric is usable as a metric in a TF2 model, logging to tensorboard as well.  

Standalone code to reproduce the issue
https://colab.research.google.com/drive/1FPGz3dK2zSI2wjuTYrywaUG0UlHnej6c?usp=sharing

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/8c8a0b0da94d5de7210ab07d077fba22/untitled369.ipynb).

**Comment by Jordy-VL** [comment]
Any updates @ymodak?

**Comment by nikitamaia** [comment]
Hi @Jordy-VL, I've seen this error reported a few times and as I understand it it's caused when an outer tf.function is retraced where there's an inner tf.function that has accessed a tensor created in the outer tf.function. Here is a simple example which results in the same error function. Removing (1) or (2) should make the error go away.
```
class Model:
  def __init__(self):
    self.v = None
    self.t = None

  @tf.function  # (1)
  def bar(self):
    print('tracing bar_g')
    return self.t  # (2)

  def foo(self):
    y = self.bar()
    self.v.assign_sub(1.0)
    
  @tf.function
  def loop(self):
    print('tracing loop')
    if self.t is None:
      self.t = tf.constant(1.0)
    if self.v is None:
      self.v = tf.Variable(1.0)
    self.foo()

m = Model()
m.loop()
```
 I think that explains why you aren't seeing the error in `test_simple()` and you are seeing the error with fit. If you set run_eagerly=True in compile, it seems to run okay as well.

It's not immediately obvious to me from your code what is causing the problem. Can you take a look at this similar issue #32889 and let me know if that helps? I'll do some more investigation into whether this is a bug or intended behavior.

**Comment by Jordy-VL** [comment]
> Hi @Jordy-VL, I've seen this error reported a few times and as I understand it it's caused when an outer tf.function is retraced where there's an inner tf.function that has accessed a tensor created in the outer tf.function. Here is a simple example which results in the same error function. Removing (1) or (2) should make the error go away.
> 
> ```
> class Model:
>   def __init__(self):
>     self.v = None
>     self.t = None
> 
>   @tf.function  # (1)
>   def bar(self):
>     print('tracing bar_g')
>     return self.t  # (2)
> 
>   def foo(self):
>     y = self.bar()
>     self.v.assign_sub(1.0)
>     
>   @tf.function
>   def loop(self):
>     print('tracing loop')
>     if self.t is None:
>       self.t = tf.constant(1.0)
>     if self.v is None:
>       self.v = tf.Variable(1.0)
>     self.foo()
> 
> m = Model()
> m.loop()
> ```
> 
> I think that explains why you aren't seeing the error in `test_simple()` and you are seeing the error with fit. If you set run_eagerly=True in compile, it seems to run okay as well.
> 
> It's not immediately obvious to me from your code what is causing the problem. Can you take a look at this similar issue #32889 and let me know if that helps? I'll do some more investigation into whether this is a bug or intended behavior.

Thank you for the explanation.
Essentially, I believe my error is caused by having my` self.confidences` and `self.correctness` as np.arrays or lists to which I concatenate new entries. Since it is not a TF.variable or constant, it loses the trace. 
**So my follow-up question is, how can I keep a variable-size list to which I append more entries?** 
The metric does not work when only saving float/int information like "True_Positives" AND the number of training/validation samples is not known upfront.

**Comment by nikitamaia** [comment]
For a variable-size list have you tried using a [tf.TensorArray](https://www.tensorflow.org/api_docs/python/tf/TensorArray)? The [Accumulating values in a loop](https://www.tensorflow.org/guide/function#loops) example in the tf.function guide might be helpful.

**Comment by Jordy-VL** [comment]
I tried it with Tf.TensorArrray.
```
            self.correctness = tf.TensorArray(tf.int32, dynamic_size=True, infer_shape=True)
            self.confidences =tf.TensorArray(tf.float32, dynamic_size=True, infer_shape=True)
```
I got the following error: 
`ValueError: Size must be declared for TensorArrays when eager execution is enabled.`

**Comment by nikitamaia** [comment]
You can set the `size` argument to your TensorArray. With `dynamic_size=True` then the array can grow past its original size. You can see that noted under the [Args section of the TensorArray docs](https://www.tensorflow.org/api_docs/python/tf/TensorArray) for `dynamic_size`
