### ISSUE TITLE
ValueError: Unknown activation: ELU

### ISSUE THREAD

**Issue by yash04singh** [tensorflow/tensorflow#42260]
from keras.models import load_model
model = load_model('discriminator_model_800.h5')

above got  this error ValueError: Unknown activation: ELU

**Comment by ravikyram** [comment]
@yash04singh 

Request you to fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

Can you please share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.

Also, refer similar type of issues with activation functions [link1
](https://stackoverflow.com/questions/55364954/keras-load-model-cant-recognize-tensorflows-activation-functions),[link2](https://stackoverflow.com/questions/59771314/valueerror-unknown-activation-activation-while-trying-to-load-a-model-with-c) and see if it helps you.Thanks!

**Comment by yash04singh** [comment]
link 1 works but shows this warning : WARNING:tensorflow:Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
 I did this>>  model = tf.keras.models.load_model('discriminator_model_010.h5', custom_objects={'ELU': ELU})

this is my model 
def define_discriminator(size):
    model = Sequential()
    model.add(Dense(400, input_dim=size, activation=ELU(alpha=0.5,),kernel_initializer=initializer))
    model.add(Dense(200, activation=ELU(alpha=0.5,),kernel_initializer=initializer))
    model.add(Dense(100, activation=ELU(alpha=0.5,),kernel_initializer=initializer))
    model.add(Dense(50, activation=ELU(alpha=0.5,),kernel_initializer=initializer))
    model.add(Dense(1, activation='sigmoid',kernel_initializer=initializer))
    # compile model
    opt = Adam(lr=0.002, beta_1=0.5)
    model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])
    return model

**Comment by ravikyram** [comment]
@yash04singh 

Please, go through similar issue #37968 and see if it helps you.Thanks!
