### ISSUE TITLE
Model using Conv1D returns socket closed error on TPU while with SeparableConv1D works

### ISSUE THREAD

**Issue by nicosacco** [tensorflow/tensorflow#42271]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): GCP instance Debian 9
- TensorFlow installed from (source or binary): installed via pip 
- TensorFlow version (use command below): 2.3
- Python version: 3.7.6
- **TPU** model: TPU v3-8

**Describe the current behavior**
I am executing a deep CNN model to handle sequences using TPUs. The exact same model, if layers are Conv1D, does not work returning a specific error, while, if I use SeparableConv1D, the model works fine.

**Describe the expected behavior**
The model should work using Conv1D layers.

**Other info / logs** 

> /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
>     106   def _method_wrapper(self, *args, **kwargs):
>     107     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
> --> 108       return method(self, *args, **kwargs)
>     109 
>     110     # Running inside `run_distribute_coordinator` already.
> 
> /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
>    1098               tmp_logs = train_function(iterator)
>    1099               if data_handler.should_sync:
> -> 1100                 context.async_wait()
>    1101               logs = tmp_logs  # No error, now safe to assign to logs.
>    1102               end_step = step + data_handler.step_increment
> 
> /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/context.py in async_wait()
>    2317   an error state.
>    2318   """
> -> 2319   context().sync_executors()
>    2320 
>    2321 
> 
> /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/context.py in sync_executors(self)
>     656     """
>     657     if self._context_handle:
> --> 658       pywrap_tfe.TFE_ContextSyncExecutors(self._context_handle)
>     659     else:
>     660       raise ValueError("Context is not initialized.")
> 
> UnavailableError: 2 root error(s) found.
>   (0) Unavailable: Socket closed
>   (1) Invalid argument: Unable to find a context_id matching the specified one (5208125777247716751). Perhaps the worker was restarted, or the context was GC'd?
> 0 successful operations.
> 0 derived errors ignored.

**Comment by amahendrakar** [comment]
@nicosacco,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by nicosacco** [comment]
> @nicosacco,
> In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

@amahendrakar I am sorry, but at the moment I cannot share either the code or the data, because they are part of an ongoing research project. If I can help you in any other way, please, do not hesitate to ask.

**Comment by amahendrakar** [comment]
@nicosacco,
In this case, could you please provide a dummy model and data to mimic the error you are facing.

Also, please take a look at [this](https://github.com/huan/tensorflow-handbook-tpu/issues/1#issuecomment-606189444) similar issue and let us know if it helps. Thanks!
