### ISSUE TITLE
tensorflow lite native app, undefined reference to `NnApiImplementation()'

### ISSUE THREAD

**Issue by amitDaMan** [tensorflow/tensorflow#42276]
I am getting the following error on these line:

```
uint32_t device_count = 0;
auto nnapi_result = NnApiImplementation()->ANeuralNetworks_getDeviceCount(&device_count);
```
.../benchmark_jni.cpp:413: undefined reference to `NnApiImplementation()'

NnApiImplementation() is referenced in nnapi_implementation.h:
```
/**
 * Load the NNAPI implementation from the shared libraries.
 * The NnApi structure is filled with all the pointers. If one function doesn't
 * exist, a null pointer is stored.
 */
const NnApi* NnApiImplementation();
```

I had previously built the arm64-v8a shared library as illustrated in this guide: 
https://www.tensorflow.org/lite/guide/android#build_in_android_studio 

using the docker image method and finally building with this command:

`bazel build -c opt --config=android_arm64 //tensorflow/lite:libtensorflowlite.so`

However when I try to find the NnApiImplementation in the .so file using:
`nm -gDC libtensorflowlite.so | grep "NnApiImplementation"
`
Nothing is returned.

**Comment by amitDaMan** [comment]
@Saduf2019 can you put the lite, and build/install tags on this, its been 2 days

**Comment by Saduf2019** [comment]
@amitDaMan 
Can you please fill/update the issue template with tf version, steps before error was faced, simple stand alone code if applicable and system information for us to analyse.

**Comment by amitDaMan** [comment]
I do not think that this problem is related to my particular usecase and is really about whether the proper nnapi functions are packaged in the shared library.

However, to answer your question. 
There is a machine learning test suite located in AOSP
https://android.googlesource.com/platform/test/mlts/

And it is built in soong and make.

And I am trying to build it in gradle and cmake to work with android studio. 

However MLTS uses the C++ api of tensorflow lite, which means I need to build the C++ shared libraries:

using: 
bazel build -c opt --config=android_arm64 //tensorflow/lite:libtensorflowlite.so

as described:
https://www.tensorflow.org/lite/guide/android#build_in_android_studio

**Comment by amitDaMan** [comment]
*ping*

**Comment by terryheo** [comment]
NnApiImplementation() is a TFLite internal function for NNAPI wrapping. It's not for external use.
If you want to use NNAPI, you can use it directly instead of calling it via TFLite internal functions.
https://developer.android.com/ndk/reference/group/neural-networks#aneuralnetworks_getdevicecount
