### ISSUE TITLE
SparseTensor doesn't have get_shape() function

### ISSUE THREAD

**Issue by kuza55** [tensorflow/tensorflow#4227]
I've been trying to add SparseTensor support to Keras (https://github.com/fchollet/keras/pull/3695) and one of the issues I've run into is that because of the lack of get_shape() I need to add SparseTensor-specific code.

Luckily so far I've only needed the rank of SparseTensors, so sparse.shape.get_shape()[0] has worked for me, but if I pass in a shape in the sparse_placeholder constructor (https://github.com/tensorflow/tensorflow/issues/4226) I would like to be able to retrieve it with sparse.get_shape()

**Comment by tatatodd** [comment]
Related to #4226, and again @concretevitamin might know more.

**Comment by concretevitamin** [comment]
We very much welcome a PR for this.  Should just be an alias of `def shape(..)`, I think.

**Comment by kuza55** [comment]
I don't think this is just an alias of def shape(..) since get_shape() returns the value through shape inference without running the graph; this is pretty close to the code that should be fixed for #4226 so hopefully this can be resolved in the same pass.

**Comment by yongtang** [comment]
I think this issue has been fixed and could be closed.

The `get_shape()` was added in commit https://github.com/tensorflow/tensorflow/commit/2939f53ea2d5dc9de018d9ad64a3ac03d03d4925, and PR #4226 was fixed through commit https://github.com/tensorflow/tensorflow/commit/b00e940445a03dd5edbe47ff34762ec8ff4087fb
