### ISSUE TITLE
[breaking? change] Concatenate dict of keras layers breaks on tf 2.3 (but worked in 2.2)

### ISSUE THREAD

**Issue by ntakouris** [tensorflow/tensorflow#42283]
**System information**
- Have I written custom code : **No**
- OS Platform and Distribution : **macos-latest, ubuntu-latest (github actions)** , macOS Mojave 10.14.1 (locally)
- TensorFlow installed from (source or binary): **pip install**
- TensorFlow version (use command below): *2.2 -> 2.3*
- Python version: **3.6 and 3.7**

**Describe the current behavior**
(this is on `tensorflow 2.2.0`)
```python
features_in = ['a', 'b']
input_layers = {
    colname: tf.keras.layers.Input(
        name=colname, shape=(1,), dtype=tf.float32)
    for colname in features_in
}

# the following line just works
x = tf.keras.layers.Concatenate(axis=-1)(input_layers.values())
x
```
`<tf.Tensor 'concatenate_1/Identity:0' shape=(None, 2) dtype=float32>`

**Describe the expected behavior**

(The following is in tensorflow 2.3.0)
`<the same snippet from above>`

The following error occurs:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-332d856dc8d7> in <module>
      6 }
      7 
----> 8 x = tf.keras.layers.Concatenate(axis=-1)(input_layers.values())
      9 x

/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    924     if _in_functional_construction_mode(self, inputs, args, kwargs, input_list):
    925       return self._functional_construction_call(inputs, args, kwargs,
--> 926                                                 input_list)
    927 
    928     # Maintains info about the `Layer.call` stack.

/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in _functional_construction_call(self, inputs, args, kwargs, input_list)
   1115           try:
   1116             with ops.enable_auto_cast_variables(self._compute_dtype_object):
-> 1117               outputs = call_fn(cast_inputs, *args, **kwargs)
   1118 
   1119           except errors.OperatorNotAllowedInGraphError as e:

/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/merge.py in call(self, inputs)
    120   def call(self, inputs):
    121     if not isinstance(inputs, (list, tuple)):
--> 122       raise ValueError('A merge layer should be called on a list of inputs.')
    123     if self._reshape_required:
    124       reshaped_inputs = []

ValueError: A merge layer should be called on a list of inputs.
```

**Comment by wookayin** [comment]
I am not sure why, but I believe the `Concatenate` layer has expected inputs to be a list or tuple even in [TF 2.2](https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/python/keras/layers/merge.py#L120-L122).

One easy fix for you would be to use `list(input_layers.values())`, because `dict.values` returns a view rather than a slit.

**Comment by ntakouris** [comment]
It worked with `list(input_layers.values())`.

I see no reason why it should not work with just `input_layers.values()`, but I'll leave the design of the api to the tensorflow team.

Many thanks :)

**Comment by amahendrakar** [comment]
@ntakouris,
Please feel free to close the issue resolved. Thanks!

**Comment by gowthamkpr** [comment]
@ntakouris This issue has been fixed in the latest version of nightly. Please find my gist [here](https://colab.research.google.com/gist/gowthamkpr/9a1e119b2f06cc59ee62190ce80482aa/untitled308.ipynb)

**Comment by ntakouris** [comment]
Thank you.
