### ISSUE TITLE
(please help) model.predict  Error   

### ISSUE THREAD

**Issue by nashWX** [tensorflow/tensorflow#42284]
Hello, I am new to coding but I keep running into an error with what should be a very simple code (I have pasted below)

**import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D, Dropout, Reshape
from tensorflow.keras import layers
from tensorflow.keras.utils import to_categorical
import numpy as np
import matplotlib.pyplot as plt
from keras import backend as K
plt.style.use('fivethirtyeight')

from tensorflow.keras.datasets import cifar10
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

print(type(x_train))
print(type(y_train))
print(type(x_test))
print(type(y_test))

print('x_train shape:', x_train.shape)
print('y_train shape:', y_train.shape)
print('x_test shape:', x_test.shape)
print('y_test shape:', y_test.shape)

index = 1
x_train[index]

img = plt.imshow(x_train[index])

classification = ['airplane', 'automobile','bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
                  
print('the image class is:', classification[y_train[index][0]])

y_train_one_hot = to_categorical(y_train)
y_test_one_hot = to_categorical(y_train)

print('the new one hot label is:', y_train_one_hot)

x_train = x_train / 255
x_test = x_train / 255

x_train[index]

model = Sequential()

model.add( Conv2D(32, (5,5), activation='relu', input_shape=(32,32,3)) )

model.add(MaxPooling2D(pool_size = (2,2)))

model.add( Conv2D(32, (5,5), activation='relu') )

model.add(MaxPooling2D(pool_size = (2,2)))

model.add(Flatten())

model.add(Dense(1000, activation='relu'))

model.add(Dropout(0.5))

model.add(Dense(500, activation='relu'))

model.add(Dropout(0.5))

model.add(Dense(250, activation='relu'))

model.add(Dense(10, activation='softmax'))

model.compile(loss = 'categorical_crossentropy',
              optimizer = 'adam',
              metrics = ['accuracy'])
#hist = model.fit(x_train, y_train_one_hot,
               #batch_size = 256,
               #epochs = 10,
               #validation_split = 0.2)
#model.evaluate(x_test, y_test_one_hot)[1]

#plt.plot(hist.history['accuracy'])
#plt.plot(hist.history['val_accuracy'])
#plt.title('Model Accuracy')
#plt.ylabel('Accuracy')
#plt.xlabel('Epoch')
#plt.legend(['Train','Val'],loc='upper right')
#plt.show()

new_image = plt.imread('/Users/home/Sunflower_from_Silesia2.jpg')
img=plt.imshow(new_image)
from skimage.transform import resize
resized_image = resize(new_image, (32,32,3))
img = plt.imshow(resized_image)

predictions = model.predict(np.array([resized_image]))

predictions**

The error I am recieving is:

**INFO:tensorflow:Converted call: <function TensorLikeDataAdapter.__init__.<locals>.permutation at 0x155eb1680>
    args: (<tf.Tensor 'args_0:0' shape=() dtype=int64>,)
    kwargs: {}

Converted call: <function TensorLikeDataAdapter.__init__.<locals>.permutation at 0x155eb1680>
    args: (<tf.Tensor 'args_0:0' shape=() dtype=int64>,)
    kwargs: {}

INFO:tensorflow:Allowlisted: <function TensorLikeDataAdapter.__init__.<locals>.permutation at 0x155eb1680>: DoNotConvert rule for tensorflow
Allowlisted: <function TensorLikeDataAdapter.__init__.<locals>.permutation at 0x155eb1680>: DoNotConvert rule for tensorflow
INFO:tensorflow:Converted call: <function TensorLikeDataAdapter.__init__.<locals>.slice_batch_indices at 0x155eb1830>
    args: (<tf.Tensor 'args_0:0' shape=(1,) dtype=int64>,)
    kwargs: {}

Converted call: <function TensorLikeDataAdapter.__init__.<locals>.slice_batch_indices at 0x155eb1830>
    args: (<tf.Tensor 'args_0:0' shape=(1,) dtype=int64>,)
    kwargs: {}

INFO:tensorflow:Allowlisted: <function TensorLikeDataAdapter.__init__.<locals>.slice_batch_indices at 0x155eb1830>: DoNotConvert rule for tensorflow
Allowlisted: <function TensorLikeDataAdapter.__init__.<locals>.slice_batch_indices at 0x155eb1830>: DoNotConvert rule for tensorflow
INFO:tensorflow:Converted call: <function TensorLikeDataAdapter.slice_inputs.<locals>.grab_batch at 0x155eb1d40>
    args: (<tf.Tensor 'args_0:0' shape=(None,) dtype=int64>, <tf.Tensor 'args_1:0' shape=(1, 32, 32, 3) dtype=float32>)
    kwargs: {}

Converted call: <function TensorLikeDataAdapter.slice_inputs.<locals>.grab_batch at 0x155eb1d40>
    args: (<tf.Tensor 'args_0:0' shape=(None,) dtype=int64>, <tf.Tensor 'args_1:0' shape=(1, 32, 32, 3) dtype=float32>)
    kwargs: {}

INFO:tensorflow:Allowlisted: <function TensorLikeDataAdapter.slice_inputs.<locals>.grab_batch at 0x155eb1d40>: DoNotConvert rule for tensorflow
Allowlisted: <function TensorLikeDataAdapter.slice_inputs.<locals>.grab_batch at 0x155eb1d40>: DoNotConvert rule for tensorflow
INFO:tensorflow:Converted call: <function Model.make_predict_function.<locals>.predict_function at 0x156df00e0>
    args: (<tensorflow.python.data.ops.iterator_ops.OwnedIterator object at 0x155e9a050>,)
    kwargs: {}

Converted call: <function Model.make_predict_function.<locals>.predict_function at 0x156df00e0>
    args: (<tensorflow.python.data.ops.iterator_ops.OwnedIterator object at 0x155e9a050>,)
    kwargs: {}

INFO:tensorflow:<function Model.make_predict_function.<locals>.predict_function at 0x156df00e0> is not cached for subkey ConversionOptions[{}]
<function Model.make_predict_function.<locals>.predict_function at 0x156df00e0> is not cached for subkey ConversionOptions[{}]
INFO:tensorflow:Source code of <function Model.make_predict_function.<locals>.predict_function at 0x156df00e0>:

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
def predict_function(iterator):
  """Runs an evaluation execution with one step."""
  return step_function(self, iterator)

Source code of <function Model.make_predict_function.<locals>.predict_function at 0x156df00e0>:

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
def predict_function(iterator):
  """Runs an evaluation execution with one step."""
  return step_function(self, iterator)

INFO:tensorflow:Error transforming entity <function Model.make_predict_function.<locals>.predict_function at 0x156df00e0>
Traceback (most recent call last):
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 444, in converted_call
    converted_f = _convert_actual(target_entity, program_ctx)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 284, in _convert_actual
    transformed, module, source_map = _TRANSPILER.transform(entity, program_ctx)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 286, in transform
    return self.transform_function(obj, user_context)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 470, in transform_function
    nodes, ctx = super(PyToPy, self).transform_function(fn, user_context)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 363, in transform_function
    result = self.transform_ast(node, context)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 252, in transform_ast
    node = self.initial_analysis(node, ctx)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 240, in initial_analysis
    node = activity.resolve(node, ctx, None)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 708, in resolve
    return ActivityAnalyzer(context, parent_scope).visit(node)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transformer.py", line 445, in visit
    result = super(Base, self).visit(node)
  File "/Users/home/opt/anaconda3/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 578, in visit_FunctionDef
    node = self._visit_arg_annotations(node)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 554, in _visit_arg_annotations
    node = self._visit_arg_declarations(node)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 559, in _visit_arg_declarations
    node.args.posonlyargs = self._visit_node_list(node.args.posonlyargs)
AttributeError: 'arguments' object has no attribute 'posonlyargs'
Error transforming entity <function Model.make_predict_function.<locals>.predict_function at 0x156df00e0>
WARNING:tensorflow:AutoGraph could not transform <function Model.make_predict_function.<locals>.predict_function at 0x156df00e0> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <function Model.make_predict_function.<locals>.predict_function at 0x156df00e0> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
INFO:tensorflow:Converted call: <function Model.make_predict_function.<locals>.step_function.<locals>.run_step at 0x156df0950>
    args: (<tf.Tensor 'IteratorGetNext:0' shape=(None, 32, 32, 3) dtype=float32>,)
    kwargs: {}

Converted call: <function Model.make_predict_function.<locals>.step_function.<locals>.run_step at 0x156df0950>
    args: (<tf.Tensor 'IteratorGetNext:0' shape=(None, 32, 32, 3) dtype=float32>,)
    kwargs: {}

INFO:tensorflow:Allowlisted: <function Model.make_predict_function.<locals>.step_function.<locals>.run_step at 0x156df0950>: DoNotConvert rule for tensorflow
Allowlisted: <function Model.make_predict_function.<locals>.step_function.<locals>.run_step at 0x156df0950>: DoNotConvert rule for tensorflow
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x156df00e0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Traceback (most recent call last):
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 444, in converted_call
    converted_f = _convert_actual(target_entity, program_ctx)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 284, in _convert_actual
    transformed, module, source_map = _TRANSPILER.transform(entity, program_ctx)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 286, in transform
    return self.transform_function(obj, user_context)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 470, in transform_function
    nodes, ctx = super(PyToPy, self).transform_function(fn, user_context)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 363, in transform_function
    result = self.transform_ast(node, context)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 252, in transform_ast
    node = self.initial_analysis(node, ctx)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 240, in initial_analysis
    node = activity.resolve(node, ctx, None)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 708, in resolve
    return ActivityAnalyzer(context, parent_scope).visit(node)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transformer.py", line 445, in visit
    result = super(Base, self).visit(node)
  File "/Users/home/opt/anaconda3/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 578, in visit_FunctionDef
    node = self._visit_arg_annotations(node)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 554, in _visit_arg_annotations
    node = self._visit_arg_declarations(node)
  File "/Users/home/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 559, in _visit_arg_declarations
    node.args.posonlyargs = self._visit_node_list(node.args.posonlyargs)
AttributeError: 'arguments' object has no attribute 'posonlyargs'**

Everything works except for the predictions line. Are there any idea how to fix this? I am running this on Spyder on Anaconda-Navigator. Thank you!

**Comment by ravikyram** [comment]
@nashWX 

I have tried in colab with TF version 2.3 and i am not seeing any issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/b7bdff2dd8cba17bbe3e367d1cc207eb/untitled246.ipynb). Thanks!

**Comment by nashWX** [comment]
Thanks for the speedy reply. I ran the exact code you sent in Spyder and received this error when it attempts to predict the image:

WARNING:tensorflow:AutoGraph could not transform <function Model.make_predict_function.<locals>.predict_function at 0x1552da560> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <function Model.make_predict_function.<locals>.predict_function at 0x1552da560> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


My TF version is 2.3 and my keras version is also 2.3.

**Comment by ravikyram** [comment]
@nashWX 

You can ignore those warning.If you want to disable the warning messages add the below code.

```
import os
import tensorflow as tf
os.environ['TF_CPP_MIN_LOG_LEVEL'] = "2"
```

Thanks!

**Comment by nashWX** [comment]
Thank you! I'm now just ignoring the error message.

**Comment by ravikyram** [comment]
@nashWX 

Please, close this thread if your issue was resolved. Thanks!
