### ISSUE TITLE
tf.nn.ctc_beam_search_decoder crashes(bad_alloc) when top_paths is large

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#42281]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
`tf.nn.ctc_beam_search_decoder` crashes(bad_alloc) when `top_paths` is extremely large

**Describe the expected behavior**
Expect no crashes

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
~~~python
import tensorflow as tf
tf.nn.ctc_beam_search_decoder(inputs=tf.ones((1,1,1)), sequence_length=[1], top_paths=1000000000000)
~~~
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
~~~python
  what():  std::bad_alloc
Aborted (core dumped)
~~~

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.1,2.3 and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/99e50916ee8722c2a5930df8b27cc1ee/untitled247.ipynb).Thanks!

**Comment by ebrevdo** [comment]
Depending on the version of TF i use, I get different errors.

Internally; I get the error
```ValueError: Attr top_paths has value 1000000000000 out of range for an int32```

using python3.6; which I think is the real expected error.

In OSS ipython3 I get the error:

```MemoryError: std::bad_alloc```

at the line

```
--> 118   _result = _execute.execute(b"CTCBeamSearchDecoder", top_paths + top_paths +
    119                              top_paths + 1, inputs=_inputs_flat, attrs=_attrs,
    120                              ctx=ctx, name=name)
```

(eager execution)

**Comment by ebrevdo** [comment]
@alextp who should take this over?  looks like an error in attr size validation?  or perhaps we're allowing an int64 through when it should be an int32; and then differences in tcmalloc vs. some other malloc externally?

**Comment by ebrevdo** [comment]
The internal error is correctly identified here, I think:

```
.../tensorflow/python/framework/ops.py in __init__(self, node_def, g, inputs, output_types, control_inputs, input_types, original_op, op_def)
   2003         op_def = self._graph._get_op_def(node_def.op)
   2004       self._c_op = _create_c_op(self._graph, node_def, inputs,
-> 2005                                 control_input_ops, op_def)
   2006       name = compat.as_str(node_def.name)
   2007     # pylint: enable=protected-access

.../tensorflow/python/framework/ops.py in _create_c_op(graph, node_def, inputs, control_inputs, op_def)
   1843   except errors.InvalidArgumentError as e:
   1844     # Convert to ValueError for backwards compatibility.
-> 1845     raise ValueError(str(e))
   1846 
   1847   return c_op

ValueError: Attr top_paths has value 1000000000000 out of range for an int32
```

**Comment by alextp** [comment]
@rohan100jain can you help triage this? The error seems to be in the TF C API layer.
