### ISSUE TITLE
import tensorflow  issue

### ISSUE THREAD

**Issue by yapifu** [tensorflow/tensorflow#42297]
Hi guys,

I have reinstalled my python 3.8.5 64 bit and use pip installed tensorflow 2.3.0. on my window 10 intel Core i7-6700HQ CPU @2.6Ghz.  And I can see it installed successfully using pip list

however whenever I try to import : import tensorflow   in jupyter notebook.

It shows following error:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-bc8d927cf602> in <module>
      1 import import_ipynb
----> 2 import tensorflow

ModuleNotFoundError: No module named 'tensorflow'

Any one can help me ? how can I get over it?

thanks

<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@yapifu,
Looks like the Jupyter notebook is using a different Python interpreter from the one where TensorFlow is installed. 

Please make sure you are installing TensorFlow and running Jupyter from the same Python installation and check if it works. Thanks!

**Comment by yapifu** [comment]
@amahendrakar 
Thanks for your feedback. Can you tell me how to check it and how to make the Jupyter notebook use same python interpreter as the one where TensorFlow is installed?

I am pretty new to the config of the Jupyter notebook.
thanks

**Comment by amahendrakar** [comment]
@yapifu,
Run the below code snippet from the terminal where you installed TensorFlow and the same code within a Jupyter Notebook.

```
import os
import sys
os.path.dirname(sys.executable)
```
The output will print the path of the Python interpreter being used. Make sure both the environments are using the same interpreter.

If you are still facing the same issue.

**Comment by yapifu** [comment]
@amahendrakar 
I run your code in Jupyter notebook, it gave me this : "'d:\\Anaconda3'"
however, I don't know whether it's the right version of python it uses.
I also check the link you gave. 

I didn't see any Conda tab. Here is what my jupyter notebook look like.
![image](https://user-images.githubusercontent.com/67816810/90591117-d787a300-e1a7-11ea-8043-cb1fb75fbb81.png)

How can I change so that I can use TensorFlow

thanks

**Comment by yapifu** [comment]
It  looks like I have 2 pythons
One is under anacodna folder, one is in another folder
![image](https://user-images.githubusercontent.com/67816810/90591986-10287c00-e1aa-11ea-980b-a5f8b71da06c.png)

![image](https://user-images.githubusercontent.com/67816810/90592006-25050f80-e1aa-11ea-918d-0544f7fe7ffe.png)


any idea? the 2nd one, is the one I installed before anaconda, the first one is the one came with the installation of anaconda .

**Comment by amahendrakar** [comment]
@yapifu,
In this case, you'll have to install TensorFlow in the Anaconda folder. You can do this through the Anaconda prompt.

But to avoid any further conflicts, I'd suggest you to delete both the environments, restart your machine and then install a single fresh copy of Anaconda or Python. Thanks!

**Comment by yapifu** [comment]
thanks for your feedback. The issue was solved. I installed TensorFlow under windows prompt rather than Anaconda prompt.

thanks
