### ISSUE TITLE
How to set different learning rate at different layers when using tf.keras.model.fit

### ISSUE THREAD

**Issue by jianrui1995** [tensorflow/tensorflow#42296]
hello:
I am wondering if there is a way that I can use different learning rate for different layers. I am trying to modify a pre-trained model and use it for other tasks. What I want is to speed up the training for new added layers and keep the trained layers at low learning rate in order to prevent them from being distorted. for example, I have a 5-conv-layer pre-trained model. Now I add a new conv layer and fine tune it. The first 5 layers would have learning rate of 0.00001 and the last one would have 0.001. Any idea how to achieve this? another important part is I want to use model.fit().
thanks

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by ymodak** [comment]
You have to custom implement this piece as we don't out of the box functionality.
This [blog](https://ksaluja15.github.io/Learning-Rate-Multipliers-in-Keras/) can be good starting point in your case.

**Comment by ymodak** [comment]
You have to custom implement this piece as we don't out of the box functionality.
This [blog](https://ksaluja15.github.io/Learning-Rate-Multipliers-in-Keras/) can be good starting point in your case.

**Comment by jianrui1995** [comment]
I read a part of source code of op and think this method can be used.
```
from tensorflow.python.training import training_ops
import tensorflow as tf

class Adam_with_layer(tf.keras.optimizers.Adam):
    def __init__(self, lr=0.001):
        super(Adam_with_layer, self).__init__(learning_rate=lr)
        self.dict_lr_schedul = {
            0.01: ["/bert/embeddings"] + ["/bert/encoder/layer_._" + str(i) for i in range(0, 6)],
            0.02: ["/bert/encoder/layer_._" + str(i) for i in range(6, 9)],
            0.1: ["/bert/encoder/layer_._" + str(i) for i in range(9, 12)] + ["/bert/pooler"],
            1: ["bidirectional", "layer_normalization", "label_attention"]
        }
    def _resource_apply_dense(self, grad, var, apply_state=None):
        var_device, var_dtype = var.device, var.dtype.base_dtype
        coefficients = ((apply_state or {}).get((var_device, var_dtype))
                        or self._fallback_apply_state(var_device, var_dtype))

        m = self.get_slot(var, 'm')
        v = self.get_slot(var, 'v')

        if not self.amsgrad:
            return training_ops.resource_apply_adam(
                var.handle,
                m.handle,
                v.handle,
                coefficients['beta_1_power'],
                coefficients['beta_2_power'],
                # coefficients['lr_t'],  # replaced by next
                coefficients['lr_t']*self.lr_with_layer(var),
                coefficients['beta_1_t'],
                coefficients['beta_2_t'],
                coefficients['epsilon'],
                grad,
                use_locking=self._use_locking)
        else:
            vhat = self.get_slot(var, 'vhat')
            return training_ops.resource_apply_adam_with_amsgrad(
                var.handle,
                m.handle,
                v.handle,
                vhat.handle,
                coefficients['beta_1_power'],
                coefficients['beta_2_power'],
                # coefficients['lr_t'],# replaced by next
                coefficients['lr_t'] * self.lr_wide_layer(var),
                coefficients['beta_1_t'],
                coefficients['beta_2_t'],
                coefficients['epsilon'],
                grad,
                use_locking=self._use_locking)

    def lr_with_layer(self,var):
        """
        
        :return:
        """
        name = var.name
        for k, v in self.dict_lr_schedul.items():
            for title in v:
                if name.find(title) != -1:
                    return k
        return 1
```

**Comment by omalleyt12** [comment]
@jianrui1995 Your solution looks good to me, I think the options are either to do that or to override `Model.train_step` to process the gradients in a custom way. In `tf-nightly`, there's also the option to supply the `gradient_transformers` argument in `Optimizer.__init__`: [link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/optimizer_v2/optimizer_v2.py#L313). With that argument, you could write a function that multiplies each gradient by some fraction based on its position in the list of Variables.
