### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: No implementation found for long org.tensorflow.lite.nnapi.NnApiDelegate.createDelegate()

### ISSUE THREAD

**Issue by chuanpham** [tensorflow/tensorflow#42302]
java.lang.UnsatisfiedLinkError: No implementation found for long org.tensorflow.lite.nnapi.NnApiDelegate.createDelegate() (tried Java_org_tensorflow_lite_nnapi_NnApiDelegate_createDelegate and Java_org_tensorflow_lite_nnapi_NnApiDelegate_createDelegate__)
        at org.tensorflow.lite.nnapi.NnApiDelegate.createDelegate(Native Method)

How can i resolve this problem? Thanks very much!

**Comment by amahendrakar** [comment]
@chuanpham,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by amahendrakar** [comment]
Also, please take a look at [#31114](https://github.com/tensorflow/tensorflow/issues/31114), [#35931](https://github.com/tensorflow/tensorflow/issues/35931) and let us know if it works. Thanks!
