### ISSUE TITLE
Exception on converting the 'stacked LSTM model' as a 'TF Lite' format.

### ISSUE THREAD

**Issue by YeongHyeon** [tensorflow/tensorflow#42308]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, FULLY_CONNECTED, LESS, LOGICAL_AND, LOGISTIC, MUL, RANGE, RESHAPE, SPLIT, TANH, TRANSPOSE. Here is a list of operators for which you will need custom implementations: Enter, Exit, LoopCond, Merge, Switch, TensorArrayGatherV3, TensorArrayReadV3, TensorArrayScatterV3, TensorArraySizeV3, TensorArrayV3, TensorArrayWriteV3.
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

The exception was triggered when I try to convert the stacked LSTM model.
The original source code is provided as following URL.
 -> https://github.com/YeongHyeon/FARED_for_Anomaly_Detection
For making 'tflite' file, I have already trained the above neural network.
Also, I have prepared the 'pbtxt' and 'pb' files
Please give me some solution!
Thank you and have a nice day.
:)

**Comment by Saduf2019** [comment]
@YeongHyeon 
Can you please update the issue template with the tensorflow version used for us to replicate the issue.
Please provide "simple stand alone code" for us to replicate the issue or if possible share a colab gist with the error faced.

With respect to the error can you please refer to these issues and update us:
#34266 #29117 [link](https://github.com/tensorflow/tensorflow/issues/34868#issuecomment-564180966) [link1](https://stackoverflow.com/questions/57774575/tflite-converter-randomstandardnormal-implemented-for-keras-model-but-not-for)

**Comment by YeongHyeon** [comment]
The new model, working as the same function, was developed for solving this issue.
In the LSTM series, it is often a problem that I found via the web searching, so I have replaced the LSTM layer to a convolutional layer.

It seems TensorFlow 2 version has solved the above problem.
I will try them in future times and I hope to contact you again.

Thank you for answering.

**Comment by Saduf2019** [comment]
Thank you for your update. glad that your issue is resolved, moving this to closed status.
