### ISSUE TITLE
Don't include json headers as include/json/json.h

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#42303]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL 7
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3.0
- Bazel version (if compiling from source): 3.1

**Describe the problem**

Currently the JsonCPP headers are all included by `#include "include/json/json.h"`. This is very unusual as in pretty much all cases the "include" folder is added to the compiler include paths and does not appear in `#include` statements

Due to this workarounds are required such as symlinking the "system headers" into a folder structure such that the above include works which may lead to e.g. #42267

What is the reasoning to use this include scheme?

I'd like to propose using "standard" include schemes like `#include "json/json.h"` and adjust the include paths appropriately. By doing so the symlinking is avoided which would resolve #42267

**Comment by mihaimaruseac** [comment]
Can you send a PR please?

**Comment by Flamefire** [comment]
Added https://github.com/tensorflow/tensorflow/pull/42516, please verify carefully as I still don't know why it was done like it was in the first place.
