### ISSUE TITLE
tflite after quantization : Didn't find op for builtin opcode 'CONV_2D' version '5'

### ISSUE THREAD

**Issue by ayush9096** [tensorflow/tensorflow#42305]
**System information**
- OS Platform and Distribution : Linux Ubuntu 19.04
- TensorFlow installed from (source or binary): Model was generated with TF from binary
- TensorFlow version (or github SHA if from source): Tensorflow version 2.4.0-dev20200715, for conversion to tflite and also in C++ for executing.

** Error logs **
Its working completely fine, when running in model in float32 format, it is giving error when performing a post-training quantization on the model.
```
ERROR: Didn't find op for builtin opcode 'CONV_2D' version '5'
ERROR: Registration failed.
```

** Loading Model **

```
    ...
    M1 = TfLiteModelCreateFromFile(modelPath.c_str());
    TfLiteInterpreterOptions* options1 = TfLiteInterpreterOptionsCreate();
    TfLiteInterpreterOptionsSetNumThreads(options1, 2);
    
    I1 = TfLiteInterpreterCreate((TfLiteModel*)M1, options1);
    TfLiteInterpreterOptionsDelete(options1);
    TfLiteModelDelete((TfLiteModel*)M1);
    ...
```

**Any other info / logs**

A similar issue flutter_tflite has been reported here #41943 .

**Comment by amahendrakar** [comment]
@ayush9096,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by ayush9096** [comment]
@amahendrakar  It worked if I did the conversion of the model, using tensorflow version 2.2 and inference in C++, using the version tf-2.4-dev . I won't be able to provide the complete code, as it is in private for now. The model is similar to a Generator network like in GANs, with Conv2D and ConvTranspose2D. Thanks!

**Comment by amahendrakar** [comment]
>I won't be able to provide the complete code, as it is in private for now.

@ayush9096,
Without a sample code it would be difficult for us to debug the issue. In this case, could you please provide a dummy model and code to mimic the error so that we can look into this. Thanks!

**Comment by dsp1589** [comment]
> > I won't be able to provide the complete code, as it is in private for now.
> 
> @ayush9096,
> Without a sample code it would be difficult for us to debug the issue. In this case, could you please provide a dummy model and code to mimic the error so that we can look into this. Thanks!

Attaching python script which I used to train the model and facing the same issue.


[trainer.py.zip](https://github.com/tensorflow/tensorflow/files/5212455/trainer.py.zip)

**[[Unable to attach training data.]]**

**_Code for exporting pb saved model to tflite:_**

```
import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model('efficientdet_d0_coco17_tpu-32/saved_model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()

open("efficientdet.tflite", "wb").write(tflite_model)
```

**Comment by dsp1589** [comment]
https://1drv.ms/u/s!As1jbBIP1BYU3THC_LhtcvdY8Cjl?e=usmRZq 

Data in one drive

**Comment by dsp1589** [comment]
Can you reopen the issue @ayush9096

**Comment by amahendrakar** [comment]
@dsp1589,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by dsp1589** [comment]
unfortunately the issue is no more reproducible. it automatically resolved for me. 
@amahendrakar still you want me to open a new issue?

**Comment by zhg-kj** [comment]
> unfortunately the issue is no more reproducible. it automatically resolved for me.
> @amahendrakar still you want me to open a new issue?

It resolved for you? You did not change any of your code for conversion?

**Comment by amahendrakar** [comment]
> @amahendrakar still you want me to open a new issue?

@dsp1589,
You need not open a new issue if it is resolved. However if you could comment here, the changes you made to fix the error, it would helpful to the community. Thanks!

**Comment by mgalgs** [comment]
@dsp1589 

> it automatically resolved for me.

Any idea what changed to get it working?

**Comment by pranathivemuri** [comment]
@dsp1589 

yes, could you please post the steps on how you got it to work for you, thank you!

**Comment by MareSeestern** [comment]
Any solution?
