### ISSUE TITLE
Loading model with tf.linalg.band_part in regularisation

### ISSUE THREAD

**Issue by RoelantStegmann** [tensorflow/tensorflow#42301]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- Model trained on linux, loading fails on windows
- Model trained on tf 2.2.0, but loading on 2.3.0 also doesn't work - Py 3.7

**Describe the current behavior**

`tf.keras.models.load_model(model_path)` results in 

```
ValueError: Inconsistent values for attr 'Tindex' DT_INT32 vs. DT_INT64 while building NodeDef 'tf_op_layer_MatrixBandPart_3/MatrixBandPart' using Op<name=MatrixBandPart; signature=input:T, num_lower:Tindex, num_upper:Tindex -> band:T; attr=T:type; attr=Tindex:type,default=DT_INT64,allowed=[DT_INT32, DT_INT64]>
```

Which probably comes from this custom regularisation that has been added to the model

```
def orthog_reg(weight_matrix):
    """ The orthogonality inducing regularization. Compute: |upper_triang(dot_prod(W,W))| """
    # weight_matrix shape is batch_size x latent_dim so we have row vectors so dot prod is WW^T
    dot_prod = tf.linalg.matmul(weight_matrix, tf.transpose(weight_matrix))
    # we only care about the upper triangular matrix, because the matrix is symmetric and the diagonal represents
    # orthogonality of vectors with itself which we do not care about
    # https://www.tensorflow.org/api_docs/python/tf/linalg/band_part
    upper_triang_dot_prod = tf.linalg.band_part(dot_prod, -1, 0) - tf.linalg.band_part(dot_prod, 0, 0)
    return tf.reduce_sum(upper_triang_dot_prod)
```

It is added like this

```
   # get regularisation
    weights = embedding_one_layer.get_weights()[0]
    weights_relu = tf.nn.relu(weights)
    orthog_reg_result = orthog_reg(weights_relu)

    # add orthogonal regularisation loss to model loss
    orthog_reg_result = 0.01 * orthog_reg_result
    model.add_loss(orthog_reg_result)
``` 

**Describe the expected behavior**

Expect it to load ;)

**Standalone code to reproduce the issue**
(Will add this soon)

**Comment by Saduf2019** [comment]
@RoelantStegmann 
Please provide with simple stand alone code to replicate the issue faced or if possible share a colab gist with the issue faced for us to analyse.

With respect to the error, follow the below:
#32375
