### ISSUE TITLE
tensorflow lite inference via c++ : interpreter->output_tensor(0) gives wrong tensor value

### ISSUE THREAD

**Issue by Jumpool** [tensorflow/tensorflow#42310]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 16.4 and windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:  Samsung  Galaxy S8
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.3.0
- Python version: 3.7.8
- Bazel version (if compiling from source):  3.1.0
- GCC/Compiler version (if compiling from source): c++11
- CUDA/cuDNN version: Non
- GPU model and memory: Tesla V100, 16G memory

**Describe the current behavior**
I tried to run a TensorFlow (v2.3.0) lite inference of Mobilentnet v2 in various languages, such as python, Android (Java), and C++ (Android JNI). It works well for python and Android(Java), but the output in C++ (Android JNI) is a mess.

If I roll back to Tensorflow v2.0.0, it works well in python, Android, and c++.

The code in Android JNI c++  is as below:
_model = tflite::FlatBufferModel::BuildFromBuffer(data,numBytesRead );
tflite::ops::builtin::BuiltinOpResolver resolver;  
tflite::InterpreterBuilder(*_model, resolver)(&interpreter);
if (interpreter->AllocateTensors() != kTfLiteOk ){ 
        return false;
    }
interpreter->SetNumThreads(1);

if (interpreter->outputs().size() != 1) {  
     return false;
}
outputs = interpreter->output_tensor(0);

I debugged the code and found several issues:
a. interpreter->outputs().size() = 18446743945091386451
b. outputs->dims->shape = 4
c. [pseudo code] outputs->dims->data[0,1,2,3] = 1, 224, 224, 3

I debugged it and found the issue of 
**Describe the expected behavior**
a. interpreter->outputs().size() = 1
b. outputs->dims->shape = 2
c. [pseudo code] outputs->dims->data[0,1] = 1, 1000

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Mobilenet V2 is from keras_applications.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

NA.

**Comment by hpssjellis** [comment]
I have a similar situation happening on Arduino_TensorFlowLite, where  
**interpreter->output(0)** and  **interpreter->input(0)**   seem to be sharing values.

**interpreter->output(0)->dims->size** seems to have the same value as **interpreter->input(0)->dims->size**.

Also **interpreter->input(0)->data.f[0]** value can be set before  interpreter->Invoke(); but after  interpreter->Invoke();   **interpreter->input(0)->data.f[0]** seems to have the same value as  **interpreter->output(0)->data.f[0]**

I have semi-helpful code [here](https://github.com/hpssjellis/my-examples-for-the-arduino-portentaH7/blob/master/m09-Tensoflow/b03_makerML_layers.ino). One file has everything in it. The model has 2 inputs but only one output. The output shows **interpreter->input(0)->dims->size** as 2 when it should be 1.

**Comment by sachinprasadhs** [comment]
Hi, could you please try again with the recent Tensorflow version and let us know if the issue still exists, Thanks!
