### ISSUE TITLE
Could not load dynamic library 'libcusparse.so.10

### ISSUE THREAD

**Issue by dark0ghost** [tensorflow/tensorflow#42318]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):  binary
- TensorFlow version:  2.4.0
- Python version: 3.8.5
- Installed using virtualenv? pip? conda?:virtualenv
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 10/9
- CUDA/cuDNN version: 11/8
- GPU model and memory: nvidia 2060

**Describe the problem**
I can't figure out how to install the module:__Could not load dynamic library 'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory__
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
 I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
 I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
 I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
 I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
 W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
 W tensorflow/core/common_runtime/gpu/gpu_device.cc:1753] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices..

**Comment by ravikyram** [comment]
@dark0ghost 

Can you try with tested build configurations from here and try building TensorFlow with CUDA 10.1, and check if it works. 
To use CUDA 10.2  Please build the Tensorflow from source.
Follow the instructions mentioned [here.](https://www.tensorflow.org/install/source) And also take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/38194#issuecomment-609922803).
Thanks!

**Comment by dark0ghost** [comment]
tensorflow  no support  cuda 11?

**Comment by ravikyram** [comment]
@dark0ghost 

Please, refer https://github.com/tensorflow/tensorflow/issues/42084#issuecomment-670208947 . Thanks!
