### ISSUE TITLE
variable_scope raise exception if reuse=False and no name_or_scope

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#4231]
Right now `variable_scope` [raises an exception](https://github.com/tensorflow/tensorflow/blob/5c07198777fd641ffb5f55fa6604050ccf55e8c8/tensorflow/python/ops/variable_scope.py#L1373) if `reuse=True` and there is no `name_or_scope`, but there is no similar error when `reuse=False` (explicitly set and not using default of `None`). 

Obviously no error should be raised when `reuse=None` but I think as a safety check if I have explicitly set `reuse=False`, then I do want to raise an error if I have forgotten to set the scope for a given layer / node.

I am using this construct in tf-slim to deal with creating a different graph for training vs validation. Right now if I forget to assign a `scope` to a given layer, than the call to create the graph will not fail even though I want it to.

**Comment by tatatodd** [comment]
This is a bit complicated, and I'm not sure I fully understand it, but I believe the explanation of this is here, in the paragraph that starts with "Note that you cannot set the reuse flag to False."
https://www.tensorflow.org/versions/r0.10/how_tos/variable_scope/index.html#basics-of-tf-variable-scope

Let me know if that answers your question; if not just ping this issue.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity, please reopen or provide more information when it becomes available.
