### ISSUE TITLE
Input and output tensors of converted TFLite model do not accord with trained model in TF

### ISSUE THREAD

**Issue by FlorentijnD** [tensorflow/tensorflow#42312]
@tensorflow/micro

**System information**
Hardware : Freescale i.MX6 Quad/DualLite
Processor: ARMv7 Processor rev 10 (v71)
OS Platform and Distribution: Yocto built Linux distribution (kernel 4.9.4+)
The tf-lite library was built with flex delegate enabled and using default makefile: https://github.com/tensorflow/tensorflow/blob/r2.2/tensorflow/lite/tools/make/Makefile
API : CPP

**Describe the problem**
I developed a custom image segmentation model (based on ENet's architecture) that works with 320x240x3 images and outputs 320x240 images. The pixel values range from 0 to 2, corresponding with one of the three classes. During training and evaluation everything went fine. Converting the graph to pb and then to TF Lite format messes up the input and output sizes.

**Please provide the exact sequence of commands/steps when you ran into the problem**

I trained the ENet based model locally on a GPU. Everything went fine. I then followed the guidelines and then froze the graph (the inputs and outputs) so ended up with a model in protobuf format (.pb). In the last step I converted the model to .lite (using integer quantization). When examining statistics of the model with the TFLite interpreter on my embedded device, I see that the output corresponds to one float only (instead of the expected 320x240 ints) and that the input tensor is of size 921600. (exactly four times the amount of pixels in 320x240x3 images - because, during training, the batch size was 5 I see no link with the batch size). The same is true for the output tensor (`ENET/logits_to_softmax` - node 286) : 
![image](https://user-images.githubusercontent.com/29673343/90166030-df0b0e80-dd99-11ea-9547-a583bbd6da19.png)

My main question is thus why the input and output tensors are so 4 times too big to account for the input and output data?

**Comment by FlorentijnD** [comment]
Inspecting the input and output in Netron of the .pb model results in : ![image](https://user-images.githubusercontent.com/29673343/90118765-01306c80-dd59-11ea-829b-2f06c9771984.png)
![image](https://user-images.githubusercontent.com/29673343/90119350-bb27d880-dd59-11ea-8181-a71322aa99b7.png)

Inspecting the input (and output) in Netron of the .lite model results in : 
![image](https://user-images.githubusercontent.com/29673343/90118856-22915880-dd59-11ea-95b1-d312da31b891.png)
![image](https://user-images.githubusercontent.com/29673343/90119427-da266a80-dd59-11ea-8887-77f15936c425.png)

Part of the output of the cpp script (just after the pre-invoke interpreter state) looks like this :
![image](https://user-images.githubusercontent.com/29673343/90119025-553b5100-dd59-11ea-82c3-1cbc224e6877.png)

I also like to mention that picking a number bigger than the input tensor (921602 > 921600) does not result in a segmentation fault (while 2 000 000 does).

**Comment by FlorentijnD** [comment]
I can also send over the scripts I used for the conversions or the models (they are small in size - about 600kb)

**Comment by FlorentijnD** [comment]
I just found out that the repo I started off with has the same problem.
https://github.com/PINTO0309/TensorFlow-ENet/blob/pinto0309work/checkpoint/semanticsegmentation_enet.pb

This ENet in protobuf format also has the same output - namely a float instead of an output image

**Comment by FlorentijnD** [comment]
@PINTO03091 as this is your repository, do you have an idea of what's going on?

**Comment by PINTO0309** [comment]
I've lost interest in ENet for now, but it might be worthwhile to try Integer Quantization on the .pb in the path below with FlexDelegate enabled. 
**https://github.com/PINTO0309/TensorflowLite-flexdelegate/tree/master/models/enet**

**Comment by FlorentijnD** [comment]
Thanks for your reply, the problem is not speed or quantization related. It's about the input and output of the graph that are messed up when converting to protobuf format. Output is a single float instead of a pixel map (of which the size is equal to the input images' sizes) corresponding to the classes

**Comment by FlorentijnD** [comment]
Important update and finding to this thread : 

```

# load the graph

GRAPH_PB_PATH = '/content/drive/My Drive/models-cnh/enet_cut_16layers_filtersdown_320240.pb'

with tf.io.gfile.GFile(GRAPH_PB_PATH,'rb') as f:
    graph_def = tf.compat.v1.GraphDef()
graph_def.ParseFromString(f.read())

with tf.Graph().as_default() as graph:
        tf.import_graph_def(
            graph_def,
            input_map=None,
            return_elements=None,
            name="prefix",
            op_dict=None,
            producer_op_list=None
        )   
    
# assign session
sess =  tf.compat.v1.Session(graph=graph)
# get correct tensor
# enets
output_name = "prefix/ENet/logits_to_softmax:0"
input_name = "prefix/input:0"

y_tensor = graph.get_tensor_by_name(output_name)
x_tensor = graph.get_tensor_by_name(input_name)

seg = sess.run(y_tensor, feed_dict={x_tensor: input})

print(seg.shape)
```

prints the following : 
![image](https://user-images.githubusercontent.com/29673343/90162946-b2ed8e80-dd95-11ea-84de-3c3026d47206.png)

So that means that the output of size 240x320 actually exists in the graph.
This means that the problem is not residing in the conversion from checkpoint files to protobuf.
The information is there somewhere in the graph but I can't find it in netron (for the protobuf file - see OP).

The output of the model after conversion to tf lite only outputs a single float while we are able to extract the whole result in protobuf format using the python API.

**Comment by FlorentijnD** [comment]
Here goes the protobuf model used in all the code above, and the same model converted to TF Lite. The netron visualisations were carried out with these models. 
[pb_and_lite.model.zip](https://github.com/tensorflow/tensorflow/files/5070342/pb_and_lite.model.zip)

**Comment by jdduke** [comment]
@abattery can you take a look? This might just be a matter of changing the output tensor name during conversion.

**Comment by FlorentijnD** [comment]
I updated my comments to make the problem clearer: 

- I'd like to know why the input and output tensor have a shape that is much larger than the input and output images the network has been trained with (912600 in both cases, while I expect input to have an array length of 320x240x3 and output array lenght of 320x240)
- I'd like to know why surpassing this array with length 912600 (e.g. feeding the input 9126002 elements) does not result in a segmentation error - while feeding 2 000 000 elements does
- I'd like to know why netron does not show the correct output sizes (1 float instead of e.g. [1,320,240,1])

- A previous question I had but figured out myself is why the output of the TFLite was also just a float, but that was because I was reading the output wrongly

**Comment by jdduke** [comment]
> Output is an array of 921600 elements according to TFLite

How are you checking this? Note that the *byte* size of the tensor will be 9126000 if the shape is 320x240x3 for a float tensor.

> e.g. feeding the input 9126002 elements)

How exactly are you feeding in the elements? If you're just writing to an array (in C++), then this is undefined behavior and subject to the same issues as out-of-bounds array access with C++ arrays.

**Comment by abattery** [comment]
After loading both models from https://github.com/tensorflow/tensorflow/issues/42312#issuecomment-673592182,

Both TF and TFLite models have the same input/output tensor size in the netron tool.

Frozen graph: Input name:input, type:float32 (?, 320, 240, 3) -> Output name:ENet/logits_to_softmax type: float32
Lite graph: Input name:input type:float32 (1, 320, 240, 3) -> Output name:ENet/logits_to_softmax type:float32.

They looks fine to me.

**Comment by saikumarchalla** [comment]
@FlorentijnD  Please check the previous comment and let us know if you have any concern still. Thanks!

**Comment by FlorentijnD** [comment]
Thanks for coming back on this. @abattery's comment solved my issue and forgot to close this thread.
