### ISSUE TITLE
Poor code on Docs

### ISSUE THREAD

**Issue by parsarahimi** [tensorflow/tensorflow#42316]
Code doesn't work, imports aren't listed and K.dot is just too vague
https://www.tensorflow.org/api_docs/python/tf/keras/layers/RNN

**Comment by ntakouris** [comment]
It's a well known convention that you do:
`import tensorflow.keras.backend as K`

**Comment by ymodak** [comment]
You may use following imports on top of the example:
```python
# Setup modules
  from tensorflow import keras
  from tensorflow.keras.layers import RNN
  from tensorflow.keras import backend as K
# Rest of the example
````

**Comment by parsarahimi** [comment]
Thanks ymodak
