### ISSUE TITLE
Ragged Tensors in Keras Model Output

### ISSUE THREAD

**Issue by ablanch5** [tensorflow/tensorflow#42320]
**System information**
- TensorFlow version (you are using): 2.3.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
I don't think ragged tensors are supported as the outputs to a model. For example the following code does not work

import tensorflow as tf

y_pred = tf.ragged.constant([[0], [0, 0]])
y_true = tf.ragged.constant([[1], [1,1]])

model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(None,), ragged=True)
])

model.compile(loss='MSE', optimizer='adam')
model.evaluate(x=y_pred, y=y_true)

Returns error:
 TypeError: Failed to convert object of type <class 'tensorflow.python.ops.ragged.ragged_tensor.RaggedTensor'> to Tensor. Contents: tf.RaggedTensor(values=Tensor("sequential_1/Cast_1:0", shape=(None,), dtype=float32), row_splits=Tensor("RaggedFromVariant/RaggedTensorFromVariant:0", shape=(None,), dtype=int64)). Consider casting elements to a supported type.

**Will this change the current api? How?**
yes. implement support for ragged tensors in keras model output

**Who will benefit with this feature?**
People who want to use ragged tensors in output, for example sequence to sequence models with variable lengths.

**Any Other info.**
No.

**Comment by amahendrakar** [comment]
@ablanch5,
Please take a look at [this](https://github.com/tensorflow/tensorflow/issues/41276) similar issue and let us know if it helps. Thanks!

**Comment by ablanch5** [comment]
Maybe I'm not reading it properly but it doesn't seem like that issue was actually resolved it was just propogated to a different issue. I agree the same problem is being discussed. Anyway hoping tagged tensors can be supported for labels in the future without the need for custom code on user end.

**Comment by foxik** [comment]
Note that supporting RaggedTensors as targets (e.g., in `model.fit`) is a frequent request, see #44988, #44112, #43591, #43093, #42320, #41810.

Some partial progress is in pull requests #45060 and #45015, which will allow using custom losses in Keras model (but existing losses like MSE or (S)CE will still not work).

**Comment by foxik** [comment]
Note that I created a new feature request #45403 to support RaggedTensors in standard Keras loss functions.

**Comment by ashishmagar600** [comment]
@ablanch5 were  you able to solve this issue. I think it is still not resolved. They have made progress in terms of not having to write custom loss functions for ragged inputs.

**Comment by ablanch5** [comment]
> 
> 
> @ablanch5 were you able to solve this issue. I think it is still not resolved. They have made progress in terms of not having to write standard loss functions for ragged inputs.

I was not able to solve it

**Comment by jvishnuvardhan** [comment]
Looks like this was resolved in recent `tf-nightly`. [Here](https://colab.research.google.com/gist/jvishnuvardhan/6027e225ae010de63ee88cd8fc8ee84d/untitled86.ipynb) is a gist for reference.

Can you please verify once and close the issue if this was resolved for you.

If this was not resolved, can you please open the issue in  [keras-team/keras repo](https://github.com/keras-team/keras/issues) repo as keras development moved to that repo to focus mainly on Keras. Thanks!

**Comment by karllessard** [comment]
I had the exact same issue as @ablanch5 and just tried it again with TensorFlow 2.8.0rc1, and confirm that it now works :+1:

**Comment by jvishnuvardhan** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
