### ISSUE TITLE
Build Error at Building 'tensorflow/core/distributed_runtime/eager:remote_tensor_handle_data'

### ISSUE THREAD

**Issue by Yasin40** [tensorflow/tensorflow#42328]
**System information**
- OS Platform and Distribution : **Linux UBUNTU 18.04**
- My device (Platform): **Odroid XU4**
- TensorFlow installed from **Source**
- TensorFlow version: **1.15.3** (and this issue appear in 1.15.0, 1.15.1)
- Python version: **3**
- Installed using virtualenv? pip? conda?: No pip package, **Only C++ lib**
- Bazel version : **0.26.1**
- GCC/Compiler version : **7**
- CUDA/cuDNN version: No CUDA Suppot, **CPU-Only**
- GPU model and memory: Armhf with 1GB Ram and 4G SWAP Memory

**Describe the problem**
I'm Trying instatal TensorFlow 1.15 on `ODROID XU4`, I'm success in installing TensorFlow 1.13 by Source Compiling on my Hardware but for TF 1.15 after few days and many efforts get an Error that i don't know what caused and how fixes.

My Bazel Command:
`bazel --output_base=/media/odroid/ExternalHard/CacheFolder build --config=opt             --config=monolithic --config=noaws      --jobs 1    --copt="-funsafe-math-optimizations" --copt="-ftree-vectorize" --copt="-fomit-frame-pointer"  --cpu=armeabi       --local_resources 2024,0.5,1.0 --define tensorflow_mkldnn_contraction_kernel=0    tensorflow:libtensorflow_cc.so        --discard_analysis_cache --verbose_failures
`
But I get this Error:
`ERROR: /home/odroid/buildFile/tensorflow/tensorflow/tensorflow/core/distributed_runtime/eager/BUILD:148:1: C++ compilation of rule '//tensorflow/core/distributed_runtime/eager:remote_tensor_handle_data' failed (Exit 1): gcc failed: error executing command 
  (cd '/media/odroid/ExternalHard/CacheFolder/execroot/org_tensorflow' && \
  exec env - \
    PATH=/home/odroid/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    TF2_BEHAVIOR=0 \
    TF_CONFIGURE_IOS=0 \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/arm-opt/bin/tensorflow/core/distributed_runtime/eager/_objs/remote_tensor_handle_data/remote_tensor_handle_data.pic.d '-frandom-seed=bazel-out/arm-opt/bin/tensorflow/core/distributed_runtime/eager/_objs/remote_tensor_handle_data/remote_tensor_handle_data.pic.o' -fPIC '-DPB_FIELD_32BIT=1' -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DEIGEN_HAS_TYPE_TRAITS=0' -DTF_USE_SNAPPY -DCURL_STATICLIB -iquote . -iquote bazel-out/arm-opt/bin -iquote external/com_google_protobuf -iquote bazel-out/arm-opt/bin/external/com_google_protobuf -iquote external/zlib_archive -iquote bazel-out/arm-opt/bin/external/zlib_archive -iquote external/grpc -iquote bazel-out/arm-opt/bin/external/grpc -iquote external/com_github_nanopb_nanopb -iquote bazel-out/arm-opt/bin/external/com_github_nanopb_nanopb -iquote external/boringssl -iquote bazel-out/arm-opt/bin/external/boringssl -iquote external/com_google_absl -iquote bazel-out/arm-opt/bin/external/com_google_absl -iquote external/nsync -iquote bazel-out/arm-opt/bin/external/nsync -iquote external/eigen_archive -iquote bazel-out/arm-opt/bin/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/arm-opt/bin/external/local_config_sycl -iquote external/gif_archive -iquote bazel-out/arm-opt/bin/external/gif_archive -iquote external/jpeg -iquote bazel-out/arm-opt/bin/external/jpeg -iquote external/com_googlesource_code_re2 -iquote bazel-out/arm-opt/bin/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/arm-opt/bin/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/arm-opt/bin/external/fft2d -iquote external/highwayhash -iquote bazel-out/arm-opt/bin/external/highwayhash -iquote external/double_conversion -iquote bazel-out/arm-opt/bin/external/double_conversion -iquote external/snappy -iquote bazel-out/arm-opt/bin/external/snappy -iquote external/hwloc -iquote bazel-out/arm-opt/bin/external/hwloc -iquote external/curl -iquote bazel-out/arm-opt/bin/external/curl -iquote external/jsoncpp_git -iquote bazel-out/arm-opt/bin/external/jsoncpp_git -iquote external/local_config_cuda -iquote bazel-out/arm-opt/bin/external/local_config_cuda -iquote external/local_config_tensorrt -iquote bazel-out/arm-opt/bin/external/local_config_tensorrt -Ibazel-out/arm-opt/bin/external/local_config_cuda/cuda/_virtual_includes/cuda_headers_virtual -Ibazel-out/arm-opt/bin/external/local_config_tensorrt/_virtual_includes/tensorrt_headers -isystem external/com_google_protobuf/src -isystem bazel-out/arm-opt/bin/external/com_google_protobuf/src -isystem external/zlib_archive -isystem bazel-out/arm-opt/bin/external/zlib_archive -isystem external/grpc/include -isystem bazel-out/arm-opt/bin/external/grpc/include -isystem external/grpc/third_party/address_sorting/include -isystem bazel-out/arm-opt/bin/external/grpc/third_party/address_sorting/include -isystem external/boringssl/src/include -isystem bazel-out/arm-opt/bin/external/boringssl/src/include -isystem external/nsync/public -isystem bazel-out/arm-opt/bin/external/nsync/public -isystem external/eigen_archive -isystem bazel-out/arm-opt/bin/external/eigen_archive -isystem external/gif_archive -isystem bazel-out/arm-opt/bin/external/gif_archive -isystem external/farmhash_archive/src -isystem bazel-out/arm-opt/bin/external/farmhash_archive/src -isystem external/double_conversion -isystem bazel-out/arm-opt/bin/external/double_conversion -isystem external/hwloc/hwloc -isystem bazel-out/arm-opt/bin/external/hwloc/hwloc -isystem external/hwloc/include -isystem bazel-out/arm-opt/bin/external/hwloc/include -isystem external/curl/include -isystem bazel-out/arm-opt/bin/external/curl/include -isystem external/jsoncpp_git/include -isystem bazel-out/arm-opt/bin/external/jsoncpp_git/include -isystem external/local_config_cuda/cuda -isystem bazel-out/arm-opt/bin/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/cuda/include -isystem bazel-out/arm-opt/bin/external/local_config_cuda/cuda/cuda/include -w '-march=native' -Wno-sign-compare -funsafe-math-optimizations -ftree-vectorize -fomit-frame-pointer -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c tensorflow/core/distributed_runtime/eager/remote_tensor_handle_data.cc -o bazel-out/arm-opt/bin/tensorflow/core/distributed_runtime/eager/_objs/remote_tensor_handle_data/remote_tensor_handle_data.pic.o)
Execution platform: @bazel_tools//platforms:host_platform
tensorflow/core/distributed_runtime/eager/remote_tensor_handle_data.cc: In function 'void tensorflow::{anonymous}::DestoryRemoteTensorHandle(tensorflow::EagerContext*, tensorflow::eager::EagerClient*, tensorflow::uint64, tensorflow::uint64, int)':
tensorflow/core/distributed_runtime/eager/remote_tensor_handle_data.cc:30:12: error: 'class tensorflow::EagerContext' has no member named 'GetContextId'; did you mean 'NewContextId'?
   if (ctx->GetContextId() != context_id) {
            ^~~~~~~~~~~~
            NewContextId
Target //tensorflow:libtensorflow_cc.so failed to build
INFO: Elapsed time: 5417.963s, Critical Path: 60.17s
INFO: 1043 processes: 1043 local.
FAILED: Build did NOT complete successfully
`
I think main error log is this LIne:
`tensorflow/core/distributed_runtime/eager/remote_tensor_handle_data.cc:30:12: error: 'class tensorflow::EagerContext' has no member named 'GetContextId'; did you mean 'NewContextId'?
   if (ctx->GetContextId() != context_id) {
            ^~~~~~~~~~~~
            NewContextId`

![Screenshot from 2020-08-13 21-53-40](https://user-images.githubusercontent.com/38716150/90166519-9f4f2180-ddaf-11ea-96d9-c6455652d559.png)

**Comment by Saduf2019** [comment]
@Yasin40 
Please paste the error message (using makrdown formatting around it) instead of screenshotting. Screenshots are not searchable so they don't help in looking for the issue and also don't help other people having the same error from finding about the issue.

**Comment by Yasin40** [comment]
@Saduf2019 .
Thanks for attention. I pasted error before screenshot. bu if you complete than:
`INFO: Found 1 target...
INFO: Deleting stale sandbox base /media/odroid/ExternalHard/CacheFolder/sandbox
SUBCOMMAND: # @curl//:curl [action 'Compiling external/curl/lib/llist.c']
(cd '/media/odroid/ExternalHard/CacheFolder/execroot/org_tensorflow' && \
  exec env - \
    PATH=/home/odroid/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    TF2_BEHAVIOR=0 \
    TF_CONFIGURE_IOS=0 \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -MD -MF bazel-out/arm-opt/bin/external/curl/_objs/curl/llist.pic.d '-frandom-seed=bazel-out/arm-opt/bin/external/curl/_objs/curl/llist.pic.o' -fPIC -DCURL_STATICLIB -iquote external/curl -iquote bazel-out/arm-opt/bin/external/curl -iquote external/zlib_archive -iquote bazel-out/arm-opt/bin/external/zlib_archive -iquote external/boringssl -iquote bazel-out/arm-opt/bin/external/boringssl -isystem external/curl/include -isystem bazel-out/arm-opt/bin/external/curl/include -isystem external/zlib_archive -isystem bazel-out/arm-opt/bin/external/zlib_archive -isystem external/boringssl/src/include -isystem bazel-out/arm-opt/bin/external/boringssl/src/include -w '-march=native' -Wno-sign-compare '-std=c++11' '-march=native' '-mfpu=vfp' -funsafe-math-optimizations -ftree-vectorize -fomit-frame-pointer -Iexternal/curl/lib -D_GNU_SOURCE -DBUILDING_LIBCURL -DHAVE_CONFIG_H -DCURL_DISABLE_FTP -DCURL_DISABLE_NTLM -DHAVE_LIBZ -DHAVE_ZLIB_H -Wno-string-plus-int '-DCURL_MAX_WRITE_SIZE=65536' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/curl/lib/llist.c -o bazel-out/arm-opt/bin/external/curl/_objs/curl/llist.pic.o)
SUBCOMMAND: # //tensorflow/core/distributed_runtime/rpc:grpc_server_lib [action 'Compiling tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc']
(cd '/media/odroid/ExternalHard/CacheFolder/execroot/org_tensorflow' && \
  exec env - \
    PATH=/home/odroid/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    TF2_BEHAVIOR=0 \
    TF_CONFIGURE_IOS=0 \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/arm-opt/bin/tensorflow/core/distributed_runtime/rpc/_objs/grpc_server_lib/grpc_server_lib.pic.d '-frandom-seed=bazel-out/arm-opt/bin/tensorflow/core/distributed_runtime/rpc/_objs/grpc_server_lib/grpc_server_lib.pic.o' -fPIC '-DGRPC_ARES=0' '-DPB_FIELD_32BIT=1' -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DEIGEN_HAS_TYPE_TRAITS=0' -DTF_USE_SNAPPY -DCURL_STATICLIB -DSQLITE_OMIT_DEPRECATED -iquote . -iquote bazel-out/arm-opt/bin -iquote external/grpc -iquote bazel-out/arm-opt/bin/external/grpc -iquote external/zlib_archive -iquote bazel-out/arm-opt/bin/external/zlib_archive -iquote external/com_github_nanopb_nanopb -iquote bazel-out/arm-opt/bin/external/com_github_nanopb_nanopb -iquote external/boringssl -iquote bazel-out/arm-opt/bin/external/boringssl -iquote external/com_google_protobuf -iquote bazel-out/arm-opt/bin/external/com_google_protobuf -iquote external/com_google_absl -iquote bazel-out/arm-opt/bin/external/com_google_absl -iquote external/nsync -iquote bazel-out/arm-opt/bin/external/nsync -iquote external/eigen_archive -iquote bazel-out/arm-opt/bin/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/arm-opt/bin/external/local_config_sycl -iquote external/gif_archive -iquote bazel-out/arm-opt/bin/external/gif_archive -iquote external/jpeg -iquote bazel-out/arm-opt/bin/external/jpeg -iquote external/com_googlesource_code_re2 -iquote bazel-out/arm-opt/bin/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/arm-opt/bin/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/arm-opt/bin/external/fft2d -iquote external/highwayhash -iquote bazel-out/arm-opt/bin/external/highwayhash -iquote external/double_conversion -iquote bazel-out/arm-opt/bin/external/double_conversion -iquote external/snappy -iquote bazel-out/arm-opt/bin/external/snappy -iquote external/hwloc -iquote bazel-out/arm-opt/bin/external/hwloc -iquote external/curl -iquote bazel-out/arm-opt/bin/external/curl -iquote external/jsoncpp_git -iquote bazel-out/arm-opt/bin/external/jsoncpp_git -iquote external/local_config_cuda -iquote bazel-out/arm-opt/bin/external/local_config_cuda -iquote external/local_config_tensorrt -iquote bazel-out/arm-opt/bin/external/local_config_tensorrt -iquote external/png_archive -iquote bazel-out/arm-opt/bin/external/png_archive -iquote external/lmdb -iquote bazel-out/arm-opt/bin/external/lmdb -iquote external/icu -iquote bazel-out/arm-opt/bin/external/icu -iquote external/org_sqlite -iquote bazel-out/arm-opt/bin/external/org_sqlite -iquote external/gemmlowp -iquote bazel-out/arm-opt/bin/external/gemmlowp -Ibazel-out/arm-opt/bin/external/local_config_cuda/cuda/_virtual_includes/cuda_headers_virtual -Ibazel-out/arm-opt/bin/external/local_config_tensorrt/_virtual_includes/tensorrt_headers -isystem external/grpc/include -isystem bazel-out/arm-opt/bin/external/grpc/include -isystem external/zlib_archive -isystem bazel-out/arm-opt/bin/external/zlib_archive -isystem external/grpc/third_party/address_sorting/include -isystem bazel-out/arm-opt/bin/external/grpc/third_party/address_sorting/include -isystem external/boringssl/src/include -isystem bazel-out/arm-opt/bin/external/boringssl/src/include -isystem external/com_google_protobuf/src -isystem bazel-out/arm-opt/bin/external/com_google_protobuf/src -isystem external/nsync/public -isystem bazel-out/arm-opt/bin/external/nsync/public -isystem external/eigen_archive -isystem bazel-out/arm-opt/bin/external/eigen_archive -isystem external/gif_archive -isystem bazel-out/arm-opt/bin/external/gif_archive -isystem external/farmhash_archive/src -isystem bazel-out/arm-opt/bin/external/farmhash_archive/src -isystem external/double_conversion -isystem bazel-out/arm-opt/bin/external/double_conversion -isystem external/hwloc/hwloc -isystem bazel-out/arm-opt/bin/external/hwloc/hwloc -isystem external/hwloc/include -isystem bazel-out/arm-opt/bin/external/hwloc/include -isystem external/curl/include -isystem bazel-out/arm-opt/bin/external/curl/include -isystem external/jsoncpp_git/include -isystem bazel-out/arm-opt/bin/external/jsoncpp_git/include -isystem external/local_config_cuda/cuda -isystem bazel-out/arm-opt/bin/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/cuda/include -isystem bazel-out/arm-opt/bin/external/local_config_cuda/cuda/cuda/include -isystem external/png_archive -isystem bazel-out/arm-opt/bin/external/png_archive -isystem external/icu/icu4c/source/common -isystem bazel-out/arm-opt/bin/external/icu/icu4c/source/common -w '-march=native' -Wno-sign-compare '-std=c++11' '-march=native' '-mfpu=vfp' -funsafe-math-optimizations -ftree-vectorize -fomit-frame-pointer -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc -o bazel-out/arm-opt/bin/tensorflow/core/distributed_runtime/rpc/_objs/grpc_server_lib/grpc_server_lib.pic.o)
ERROR: /home/odroid/buildFile/tensorflow/tensorflow/tensorflow/core/distributed_runtime/rpc/BUILD:279:1: C++ compilation of rule '//tensorflow/core/distributed_runtime/rpc:grpc_server_lib' failed (Exit 1): gcc failed: error executing command 
  (cd '/media/odroid/ExternalHard/CacheFolder/execroot/org_tensorflow' && \
  exec env - \
    PATH=/home/odroid/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    TF2_BEHAVIOR=0 \
    TF_CONFIGURE_IOS=0 \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/arm-opt/bin/tensorflow/core/distributed_runtime/rpc/_objs/grpc_server_lib/grpc_server_lib.pic.d '-frandom-seed=bazel-out/arm-opt/bin/tensorflow/core/distributed_runtime/rpc/_objs/grpc_server_lib/grpc_server_lib.pic.o' -fPIC '-DGRPC_ARES=0' '-DPB_FIELD_32BIT=1' -D__CLANG_SUPPORT_DYN_ANNOTATION__ -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DEIGEN_HAS_TYPE_TRAITS=0' -DTF_USE_SNAPPY -DCURL_STATICLIB -DSQLITE_OMIT_DEPRECATED -iquote . -iquote bazel-out/arm-opt/bin -iquote external/grpc -iquote bazel-out/arm-opt/bin/external/grpc -iquote external/zlib_archive -iquote bazel-out/arm-opt/bin/external/zlib_archive -iquote external/com_github_nanopb_nanopb -iquote bazel-out/arm-opt/bin/external/com_github_nanopb_nanopb -iquote external/boringssl -iquote bazel-out/arm-opt/bin/external/boringssl -iquote external/com_google_protobuf -iquote bazel-out/arm-opt/bin/external/com_google_protobuf -iquote external/com_google_absl -iquote bazel-out/arm-opt/bin/external/com_google_absl -iquote external/nsync -iquote bazel-out/arm-opt/bin/external/nsync -iquote external/eigen_archive -iquote bazel-out/arm-opt/bin/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/arm-opt/bin/external/local_config_sycl -iquote external/gif_archive -iquote bazel-out/arm-opt/bin/external/gif_archive -iquote external/jpeg -iquote bazel-out/arm-opt/bin/external/jpeg -iquote external/com_googlesource_code_re2 -iquote bazel-out/arm-opt/bin/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/arm-opt/bin/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/arm-opt/bin/external/fft2d -iquote external/highwayhash -iquote bazel-out/arm-opt/bin/external/highwayhash -iquote external/double_conversion -iquote bazel-out/arm-opt/bin/external/double_conversion -iquote external/snappy -iquote bazel-out/arm-opt/bin/external/snappy -iquote external/hwloc -iquote bazel-out/arm-opt/bin/external/hwloc -iquote external/curl -iquote bazel-out/arm-opt/bin/external/curl -iquote external/jsoncpp_git -iquote bazel-out/arm-opt/bin/external/jsoncpp_git -iquote external/local_config_cuda -iquote bazel-out/arm-opt/bin/external/local_config_cuda -iquote external/local_config_tensorrt -iquote bazel-out/arm-opt/bin/external/local_config_tensorrt -iquote external/png_archive -iquote bazel-out/arm-opt/bin/external/png_archive -iquote external/lmdb -iquote bazel-out/arm-opt/bin/external/lmdb -iquote external/icu -iquote bazel-out/arm-opt/bin/external/icu -iquote external/org_sqlite -iquote bazel-out/arm-opt/bin/external/org_sqlite -iquote external/gemmlowp -iquote bazel-out/arm-opt/bin/external/gemmlowp -Ibazel-out/arm-opt/bin/external/local_config_cuda/cuda/_virtual_includes/cuda_headers_virtual -Ibazel-out/arm-opt/bin/external/local_config_tensorrt/_virtual_includes/tensorrt_headers -isystem external/grpc/include -isystem bazel-out/arm-opt/bin/external/grpc/include -isystem external/zlib_archive -isystem bazel-out/arm-opt/bin/external/zlib_archive -isystem external/grpc/third_party/address_sorting/include -isystem bazel-out/arm-opt/bin/external/grpc/third_party/address_sorting/include -isystem external/boringssl/src/include -isystem bazel-out/arm-opt/bin/external/boringssl/src/include -isystem external/com_google_protobuf/src -isystem bazel-out/arm-opt/bin/external/com_google_protobuf/src -isystem external/nsync/public -isystem bazel-out/arm-opt/bin/external/nsync/public -isystem external/eigen_archive -isystem bazel-out/arm-opt/bin/external/eigen_archive -isystem external/gif_archive -isystem bazel-out/arm-opt/bin/external/gif_archive -isystem external/farmhash_archive/src -isystem bazel-out/arm-opt/bin/external/farmhash_archive/src -isystem external/double_conversion -isystem bazel-out/arm-opt/bin/external/double_conversion -isystem external/hwloc/hwloc -isystem bazel-out/arm-opt/bin/external/hwloc/hwloc -isystem external/hwloc/include -isystem bazel-out/arm-opt/bin/external/hwloc/include -isystem external/curl/include -isystem bazel-out/arm-opt/bin/external/curl/include -isystem external/jsoncpp_git/include -isystem bazel-out/arm-opt/bin/external/jsoncpp_git/include -isystem external/local_config_cuda/cuda -isystem bazel-out/arm-opt/bin/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/cuda/include -isystem bazel-out/arm-opt/bin/external/local_config_cuda/cuda/cuda/include -isystem external/png_archive -isystem bazel-out/arm-opt/bin/external/png_archive -isystem external/icu/icu4c/source/common -isystem bazel-out/arm-opt/bin/external/icu/icu4c/source/common -w '-march=native' -Wno-sign-compare '-std=c++11' '-march=native' '-mfpu=vfp' -funsafe-math-optimizations -ftree-vectorize -fomit-frame-pointer -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc -o bazel-out/arm-opt/bin/tensorflow/core/distributed_runtime/rpc/_objs/grpc_server_lib/grpc_server_lib.pic.o)
Execution platform: @bazel_tools//platforms:host_platform
In file included from ./tensorflow/core/distributed_runtime/rpc/eager/grpc_eager_service_impl.h:22:0,
                 from tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:39:
./tensorflow/core/distributed_runtime/eager/eager_service_impl.h: In member function 'virtual tensorflow::Status tensorflow::eager::EagerServiceImpl::ClientTensorHandleDeleteNode::Run()':
./tensorflow/core/distributed_runtime/eager/eager_service_impl.h:183:35: error: 'class tensorflow::EagerContext' has no member named 'RemoteMgr'
       return context_->Context()->RemoteMgr()->DeleteTensorHandle(
                                   ^~~~~~~~~
Target //tensorflow:libtensorflow_cc.so failed to build
INFO: Elapsed time: 368.275s, Critical Path: 38.82s
INFO: 1 process: 1 local.
`

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
