### ISSUE TITLE
How to load a tflite model directly from a link or aws s3?

### ISSUE THREAD

**Issue by MiladGhorbaniG** [tensorflow/tensorflow#42323]
In order to deploy an aws-lambda function, I want to load a large tflite model from s3 or a web_link using 'tflite.interpreter' function. This function has 'model_path' and 'model_content' arguments. I don't have enough space in the local '/tmp' was lambda folder to store the model there (with 500 MB limitation)  and use the 'model_path' argument. Is it possible to load the model directly from s3 or another web link? For example, can we use file streaming with BytesIO and the 'model_content' argument? 

Note that I'm using python=3.7 

#s3 #aws-lambda #tflite

**Comment by MiladGhorbaniG** [comment]
Hi, I solved my issue by importing before unzipping the packages into `/tmp` folder. However, I got some errors when using `BytesIO` and 'StringIO' and it wasn't successful. Is it related to the python wrapper?

**Comment by jdduke** [comment]
Are you using Python 2 or 3?

**Comment by MiladGhorbaniG** [comment]
I tested with python 3.6

**Comment by jdduke** [comment]
Apologies for the delay, @MeghnaNatraj can you help with this one?

**Comment by MeghnaNatraj** [comment]
Hello @MiladGhorbaniG, you try this with Google drive + Google Colab

Upload your model to your google drive and authorize access to it from Google colab by running the following code in Google colab:

```
# 1. Mount (and authorize) Google Drive
from google.colab import drive
drive.mount('/content/drive')


# 2. Find your SavedModel path
# In the left section of google colab, select the 'Files' tab and refresh the folders. You'll notice a 'gdrive' option. Navigate to your saved model and drag and drop it into a colab cell ==> it'll automatically copy-paste the file-path

# Use the file path to load it into the converter
converter = tf.lite.TFLiteConverter(saved_model_dir="/content/drive/My Drive/...<path-to-saved-model>")
```
