### ISSUE TITLE
data.Dataset.as_numpy_iterator is non-reentrant compared to tensorflow data iterator.

### ISSUE THREAD

**Issue by ethanluoyc** [tensorflow/tensorflow#42327]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac 10.15.5 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.3.0-rc2-23-gb36436b087 2.3.0
- Python version: 3.8.5
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When using the numpy iterator returned from tensorflow Dataset, the iterator is not reentrant. This is different compared to the dataset iterator in tensorflow.

**Describe the expected behavior**
the numpy iterator should be reentrant which shares the same behaviour as tensorflow

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```python
ds = (
    tf.data.Dataset.from_tensor_slices((np.arange(2))))

iterator = ds
for elem in iterator:
    print(elem)
for elem in iterator:
    print(elem)
```
gives 
```
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
```
whereas 
```
ds = (
    tf.data.Dataset.from_tensor_slices((np.arange(2))))

iterator = ds.as_numpy_iterator()
for elem in iterator:
    print(elem)
for elem in iterator:
    print(elem)
```
gives 
```
0
1
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
NA

**Comment by ethanluoyc** [comment]
I think the issue is here

https://github.com/tensorflow/tensorflow/blob/b36436b087bd8e8701ef51718179037cccdfc26e/tensorflow/python/data/ops/dataset_ops.py#L526

where the _NumpyIterator is used, however in _NumpyIterator's __iter__ method (line 3776), the state for the iterator is not initialized at every iter.

https://github.com/tensorflow/tensorflow/blob/b36436b087bd8e8701ef51718179037cccdfc26e/tensorflow/python/data/ops/dataset_ops.py#L3770-L3783.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3, nightly versions(`2.4.0-dev20200813`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/2cdbc8759c76dca116fd7ea098ce7a99/untitled254.ipynb).Thanks!

**Comment by aaudiber** [comment]
In tf.data (and in Python in general) iterators can only be iterated through once. `tf.data.Dataset` is an **Iterable**, not an **Iterator**. See https://stackoverflow.com/a/9884259/401884 for more information about the difference. 

[This colab](https://colab.research.google.com/drive/1A19aX1JlvYoRMoShcfs9RyhHDtRnVexB) demonstrates the difference and shows how to create a numpy Iterable that has the behavior you're looking for.

```python
class NumpyIterable(object):
  def __init__(self, dataset):
    self.dataset = dataset

  def __iter__(self):
    return self.dataset.as_numpy_iterator()

numpy_iterable = NumpyIterable(ds)
print("\nIterate numpy iterable first time:")
for elem in numpy_iterable:
  print(elem)
print("\nIterate numpy iterable second time:")
for elem in numpy_iterable:
  print(elem)
```

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/2d6b50dbb874c8cdb7d2952238fa6824/untitled69.ipynb)..Thanks !
