### ISSUE TITLE
tf.nest.assert_same_structure crashes (abort) when some constraints are violated

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#42329]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
`tf.nest.assert_same_structure` crashes (abort, systemerror) when some either `check_types` or `expand_composites` is 0d bool is violated.

**Describe the expected behavior**
Expect no crash

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

When `check_types` is boolean is violated
~~~python
import tensorflow as tf
import numpy as np
tf.nest.assert_same_structure(nest1=np.zeros((1)), nest2=tf.ones((1,1,1)), check_types=tf.ones((2)))
~~~
When `expand_composites` is boolean is violated
~~~python
import tensorflow as tf
import numpy as np
tf.nest.assert_same_structure(nest1=np.zeros((1)), nest2=tf.ones((1,1,1)), expand_composites=tf.ones((2)))
~~~

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
~~~python
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  SystemError: <class 'type'> returned a result with an error set

At:
  /root/miniconda3/lib/python3.7/site-packages/numpy/core/arrayprint.py(1388): _array_repr_implementation
  /root/miniconda3/lib/python3.7/site-packages/tensorflow/python/util/nest.py(397): assert_same_structure
  <stdin>(1): <module>

Aborted (core dumped)
~~~

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.1, TF v2.3 and TF-nightly. 

Session crashes on running the `tf.nest.assert_same_structure` line. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/7e2519ef8640e2d849516d0d363ae230/42329.ipynb). Thanks!

**Comment by yongtang** [comment]
The issue is more or less complicated and is related to pybind's handling of mismatched python type binding. A easy fix might be to enforce the type passed to pybind conforms to bool (for check_types and expand_composites). Created a PR #42397 for the fix.
