### ISSUE TITLE
Issue with iou_threshold in non_max_suppression

### ISSUE THREAD

**Issue by jnd77** [tensorflow/tensorflow#42348]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.2
- GPU model and memory: 2060

**Describe the current behavior**

With TF 2.2.0, it looks like the threshold is weak (i.e. it excludes all the boxes if their iou is greater or equal than the threshold).

**Describe the expected behavior**

With TF 1.15, this threshold is strong.
In general, it doesn't make a lot of difference, except in one particular use case.
If I do a NMS to keep only non overlapping boxes, I would use a threshold of 0.
With TF 1.15, the result is the list of all non-overlapping boxes as expected.
With TF 2.2, the ouput is a single box, the one with the highest score.
There is an easy workaround of adding a small epsilon, but it's not very intuitive.

**Standalone code to reproduce the issue**

    boxes = tf.constant([[0.1, 0.1, 0.3, 0.3], [0.5, 0.5, 0.7, 0.7], [0.6, 0.6, 0.8, 0.8]], dtype=tf.float32)
    scores = tf.constant([0.9, 0.8, 0.7], dtype=tf.float32)

    print('Expected indices')
    print(tf.image.non_max_suppression(boxes, scores, 100, iou_threshold=1e-5))

    print('Actual indices')
    print(tf.image.non_max_suppression(boxes, scores, 100, iou_threshold=0.))

Output

```
Expected indices
tf.Tensor([0 1], shape=(2,), dtype=int32)
Actual indices
tf.Tensor([0], shape=(1,), dtype=int32)
```

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3, nightly version and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/6a1118b74f9cf4fe3a71dc5c0f788b23/untitled251.ipynb).Thanks!

**Comment by sushreebarsa** [comment]
Was able to reproduce this issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/02ef1ba736dbd7d3c0d445eb78d96866/untitled68.ipynb)..Thanks !

**Comment by chunduriv** [comment]
@jnd77,

Sorry for the late response. This issue was fixed.

```
import tensorflow as tf

boxes = tf.constant([[0.1, 0.1, 0.3, 0.3], [0.5, 0.5, 0.7, 0.7], [0.6, 0.6, 0.8, 0.8]], dtype=tf.float32)
scores = tf.constant([0.9, 0.8, 0.7], dtype=tf.float32)

print('Expected indices')
print(tf.image.non_max_suppression(boxes, scores, 100, iou_threshold=1e-5))

print('Actual indices')
print(tf.image.non_max_suppression(boxes, scores, 100, iou_threshold=0.))
```
Output:
```
Expected indices
tf.Tensor([0 1], shape=(2,), dtype=int32)
Actual indices
tf.Tensor([0 1], shape=(2,), dtype=int32)
```
Please feel free to move this issue to close status. Thank you.

**Comment by jnd77** [comment]
Thank you.
