### ISSUE TITLE
tf.data.Dataset.list_files(file_path, shuffle=True) fails (on Windows w/ CUDA)

### ISSUE THREAD

**Issue by optiluca** [tensorflow/tensorflow#42358]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): WIN 10 LTSC BUILD 17763
- TensorFlow installed from (source or binary): BINARY - https://pypi.org/project/tensorflow/2.3.0/
- TensorFlow version (use command below): 2.3.0
- Python version: 3.6.8
- CUDA/cuDNN version: 10.1, CUDNN 7.6.5
- GPU model and memory: Quadro M2000M, 4096MiB

TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
v2.3.0-rc2-23-gb36436b087 2.3.0 

**Describe the current behavior**
Specifically on this Windows system, with CUDA enabled (not happening w/ `os.environ["CUDA_VISIBLE_DEVICES"] = "-1"`, and not happening on my Linux system at all), calling tf.data.Dataset.list_files(tfrecord_path, shuffle=True) produces the following error message:

Traceback (most recent call last):
  File "C:/lbortolotti/PerformanceMethods/python_generic_toolbox/bad_list_files.py", line 22, in <module>
    tf.data.Dataset.list_files(tfrecord_path, shuffle=True)
  File "C:\Python\36\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1125, in list_files
    dataset = dataset.shuffle(buffer_size, seed=seed)
  File "C:\Python\36\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 1240, in shuffle
    return ShuffleDataset(self, buffer_size, seed, reshuffle_each_iteration)
  File "C:\Python\36\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3676, in __init__
    **self._flat_structure)
  File "C:\Python\36\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 6215, in shuffle_dataset_v3
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Python\36\lib\site-packages\tensorflow\python\framework\ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: buffer_size must be greater than zero. [Op:ShuffleDatasetV3]

**Describe the expected behavior**
No errors, shuffled file list returned.

**Standalone code to reproduce the issue**
Gist: https://gist.github.com/optiluca/d84d169315035b8a1dadc97d52b88f24

**Comment by Saduf2019** [comment]
@optiluca 
I ran the code sharedand face a different error, please have a look at the [gist here](https://colab.research.google.com/gist/Saduf2019/cc7035e9a28774c7c32e4d2387ac345f/untitled374.ipynb).

**Comment by optiluca** [comment]
Hi. The error is presumably related to a quirk of colab where __file__ is not defined. The aim of that line is to simply establish what the working directory is so we can write some (empty) test files needed to reproduce the issue.

In any case, as I mentioned in my original post, the issue only occurs on windows with cuda enabled, so we won't be able to see it on colab.

**Comment by ymodak** [comment]
Does this happen on Linux system enabled with cuda support?
The cuda compute capability for Quadro M2000M | 5.0 which is not in the [list of supported architectures](https://www.tensorflow.org/install/gpu#hardware_requirements).

**Comment by optiluca** [comment]
Hi @ymodak .  I've tried with:

W10 + M2000M (as per original issue) -> broken
Ubuntu+ V100 -> working
W10 + T2000 -> working

So it appears to be specific to my card, presumably because 5.0 is no longer supported.

As a slight aside, what's the criterion by which CUDA architectures are supported?  Judging by the slightly-arbirary-looking list of supported versions it doesn't seem to be as simple as having a "recent" card?

Thanks,

Luca

**Comment by ymodak** [comment]
Thanks for sharing your analysis. T2000 has cuda compute capability of 7.5 and V100 has 7.0 both are supported by TF.
For more information you may try posting the question on stackoverflow. Thanks!
