### ISSUE TITLE
How to implement dynamic network with TensorFlow ?

### ISSUE THREAD

**Issue by zsdonghao** [tensorflow/tensorflow#4235]
Hi, I am trying to implement a dynamic network, which is able to change the network structure according to the input data. Here is an example  https://arxiv.org/abs/1511.02799

I wonder it that possible to use TensorFlow to implement dynamic network?
I think we may need to use placeholder to control the network?

Thank you very much.

**Comment by tatatodd** [comment]
We primarily use github issues to track bugs and installation issues.  This is a question better suited for StackOverflow.  Please ask it there and tag it with the `tensorflow` tag.  Thanks!
