### ISSUE TITLE
Indexing into EagerTensor returns all zeros (on Windows w/ CUDA)

### ISSUE THREAD

**Issue by optiluca** [tensorflow/tensorflow#42355]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): WIN 10 LTSC BUILD 17763
- TensorFlow installed from (source or binary): BINARY - https://pypi.org/project/tensorflow/2.3.0/
- TensorFlow version (use command below): 2.3.0
- Python version: 3.6.8
- CUDA/cuDNN version: 10.1, CUDNN 7.6.5
- GPU model and memory: Quadro M2000M, 4096MiB

TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
v2.3.0-rc2-23-gb36436b087 2.3.0 

**Describe the current behavior**
Specifically on this Windows system, with CUDA enabled (not happening w/ `os.environ["CUDA_VISIBLE_DEVICES"] = "-1"`, and not happening on my Linux system at all), reading a tfrecord with tf.data.* returns an EagerTensor which attempting to index results in incorrect zero output.

**Describe the expected behavior**
Indexing into the EagerTensor should return the correct output!

**Standalone code to reproduce the issue**
Gist: https://gist.github.com/optiluca/ff34d153c9ff339adedf5f905cdc8240

On a working system the output is:
tf.Tensor([100. 105. 110. 115. 120.], shape=(5,), dtype=float32)
100.0
100.0

On my windows system:
tf.Tensor([100. 105. 110. 115. 120.], shape=(5,), dtype=float32)
0.0
100.0

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3 and i am not seeing any issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/66a5b557f05848ae794eec1c902bac0d/untitled256.ipynb).
I have not tested on windows.Thanks!

**Comment by optiluca** [comment]
Hi @ravikyram.  As per issue #42506 I've tried with:

W10 + M2000M (as per original issue) -> broken
Ubuntu+ V100 -> working
W10 + T2000 -> working

So it appears to be specific to my card, presumably because CUDA architecture 5.0 is no longer supported.  The particular failure mode in this case still leaves something to be desired, I'd expect some sort of error to be thrown at least!

Thanks,

Luca

**Comment by sanjoy** [comment]
> So it appears to be specific to my card, presumably because CUDA architecture 5.0 is no longer supported.

Can you please check TF nightly?  If this works on TF nightly (which includes SASS for 5.0) then it should work on TF 2.4 as well.

I agree that the (lack of) error reporting is surprising, can you please attach the full logs from your run?

**Comment by Saduf2019** [comment]
@optiluca 
Could you please refer to [this gist](https://colab.research.google.com/gist/Saduf2019/02568b0315cfa0a409f2c69412dc08a8/untitled597.ipynb) and confirm if this issue can be closed.

**Comment by optiluca** [comment]
Sorry for the silence, yes I've just checked and on TF 2.4 the issue was resolved.  Thanks!

**Comment by Saduf2019** [comment]
@optiluca 
Thank you for your update, glad the issue is solved.
