### ISSUE TITLE
Googleapis no longer usable as a system lib with ignored com_github_googleapis_googleapis

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#42361]
**Describe the problem**

TF 2.3.0 introduced a regression with https://github.com/tensorflow/tensorflow/commit/b9e1252bcb8cf8247e7393a0df65adf5b0a18c16:

Although a `com_github_googleapis_googleapis` value is still valid for `TF_SYSTEM_LIBS` it is no longer used and the project is always downloaded which might conflict with system installed versions of it.

Note how the name changed from com_github_googleapis_googleapis to com_google_googleapis and the system_build_file option is gone: https://github.com/tensorflow/tensorflow/commit/b9e1252bcb8cf8247e7393a0df65adf5b0a18c16#diff-455a4c7f8e22d7c514e8c2caa27506c5

**Comment by mihaimaruseac** [comment]
I think best way forward here would be to make a PR to fix forward.

**Comment by Flamefire** [comment]
There are 2 solutions: Either re-add the possibility of using the system installed library or remove the entry in `VALID_LIBS`. I don't know why it was removed, if that was an oversight or a conscious decision because something doesn't work otherwise. So I can't tell which solution is the right one to do.

From the commit I can't tell who the committer was, so is there any way to find that out and ask that person?

**Comment by mihaimaruseac** [comment]
It is very likely it was an oversight, as the change looks to be made by someone outside of TF team

**Comment by ymodak** [comment]
Closing this issue since the above PR is merged and fixes it. Feel free to reopen if necessary. Thanks!
