### ISSUE TITLE
Why add the parameter ‘fallback_to_while_loop’ in the 2.3 API tf.vectorized_map( fn, elems, fallback_to_while_loop=True)

### ISSUE THREAD

**Issue by zjzh** [tensorflow/tensorflow#42368]
Hello,
       Does the parameter 'fallback_to_while_loop' is to fix some bugs so as to the function could perform normally?

**Comment by amahendrakar** [comment]
@zjzh,
If `fallback_to_while_loop` is set to `True`, on failing to vectorize an operation, the unsupported op is wrapped in a tf.while_loop to execute the map iterations. 


For more information, please take a look at the [documentation](https://www.tensorflow.org/api_docs/python/tf/vectorized_map#args_1) for the arguments of `tf.vectorized_map`. Thanks!
