### ISSUE TITLE
"No module named tensorflow" though it is installed

### ISSUE THREAD

**Issue by Kosta404** [tensorflow/tensorflow#42367]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code:
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from (source or binary): "pip install tensorflow-gpu"
- TensorFlow version (use command below): 2.3.0
- Python version: 3.6.10
- CUDA/cuDNN version: Cuda==10.1, cuDNN==7.6.5
- GPU model and memory: NVIDIA GeForce GT 710

**Describe the current behavior**
Tensorflow is installed and works if run it from the Terminal. "Hello World" test for Tensorflow also works. 
When Running code from Jupyter an error occurs (described lower) 

**Describe the expected behavior**
Code from Jupyter must run and give a default output photo.

**Standalone code to reproduce the issue**
The code is taken from your examples. The name: "object_detection_tutorial.ipynb"

**Other info / logs** 
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-cdfb01024084> in <module>
      4 import sys
      5 import tarfile
----> 6 import tensorflow as tf
      7 import zipfile
      8 

ModuleNotFoundError: No module named 'tensorflow'

**Comment by knslee07** [comment]
I am having the same issue.
I installed tensorflow following the website by creating a virtual env (conda create -n tf-gpu tensorflow-gpu;conda activate tf-gpu).
My current Python is 3.8.3 (Anaconda) but the tf-gpu python version is automatically 3.7.7 for compatibility.
Importing  tensorflow works in terminal, but it does not in Jupyter after I imported the kernel using ipykernel.
I removed the env and reinstalled it and removed the tf-gpu kernel in Jupyter and reimported it a few times. But Jupyter still cannot import tensorflow.

**Comment by cserpell** [comment]
This is probably an issue on your installation of packages. You can try adding the correct environment variables inside the notebook to find the tensorflow package:

```python
import sys

sys.path.append('/home/Kosta404/path_to_your_py_packages/')
```

Anyway, I would recommend having separated environments for system libraries and for development. You can have a look to virtualenv - venv packages.

**Comment by cserpell** [comment]
Maybe it is related to #42297 .

**Comment by Saduf2019** [comment]
@Kosta404 
Looks like the Jupyter notebook is using a different Python interpreter from the one where TensorFlow is installed.
Please make sure you are installing TensorFlow and running Jupyter from the same Python installation and check if it works. 

Also please check if your [AVX is supported](https://www.tensorflow.org/install/pip#hardware-requirements) (cpu supports AVX instruction sets.), if not  only options are either compiling from source or #19584



Check below resolve issues for reference:
#32147 #40664 #9473 [link](https://stackoverflow.com/questions/46568913/tensorflow-import-error-no-module-named-tensorflow) [link1](https://stackoverflow.com/questions/42244198/importerror-no-module-named-tensorflow) [link2](https://geekcops.com/tutorials/modulenotfounderror-no-module-named-tensorflow-solved/) [link3](https://github.com/tensorflow/tensorflow/issues/10474#issuecomment-306668929)
Thanks!

**Comment by Kosta404** [comment]
@knslee07 
https://www.youtube.com/watch?v=tPq6NIboLSc
this one helped
but i did all this stuff on a newly-reinstalled system
