### ISSUE TITLE
Inference for two or more neural networks on gpu

### ISSUE THREAD

**Issue by progred2** [tensorflow/tensorflow#42360]
I am using tensorflow 1.15.0 and built a library from source with GPU gl delegates. I am using the native C ++ API. With Android NDK I am building an executable for Android.

I want to make inference for two or more networks. To do this, I create an instance of the class, in which the interpreter is created during initialization, the GPU delegate is applied and the inference is executed. The first instance with a neural network is created and performs the inference perfectly. But when the second instance of the class is initialized, 

**Problem**: I get an error when calling the ModifyGraphWithDelegate method:

`Assertion failed (TfLiteGpuDelegate Prepare: Shader compilation failed: 0:8: L0001: Typename expected, found 'unknown' : Node number 69 (TfLiteGpuDelegate) failed to prepare.`

or

`Assertion failed (TfLiteGpuDelegate Prepare: Shader compilation failed: ERROR: 0:6: 'data' : Syntax error:  syntax error INTERNAL ERROR: no main() function! ERROR: 1 compilation errors.  No code generated. Node number 69 (TfLiteGpuDelegate) failed to prepare.`

I have verified that for the second EGL thread the context is created normally and set as current. Devices supports OpenGL ES 3.2

<details>
<summary>Some code:</summary>

<code><pre>
class Model
{
public:
	typedef std::shared_ptr<ModelInterpreter> Ptr;

	Model(const std::string tflite_model_path)
	{
                auto model = FlatBufferModel::BuildFromFile(tflite_model_path);
                if (!model) return false;

                tflite::ops::builtin::BuiltinOpResolver resolver;

                tflite::InterpreterBuilder interpreter_builder(
                	*model,
                	resolver);

                const TfLiteStatus build_status = interpreter_builder(&interpreter, 1);

                TfLiteGpuDelegateOptions delegate_options = TfLiteGpuDelegateOptionsDefault();
                delegate_options.metadata = nullptr;
                delegate_options.compile_options.precision_loss_allowed = true; // FP16
                delegate_options.compile_options.preferred_gl_object_type = TFLITE_GL_OBJECT_TYPE_FASTEST;
                delegate_options.compile_options.dynamic_batch_enabled = 0;

                gl_delegate = TfLiteGpuDelegateCreate(&delegate_options);

                interpreter->ModifyGraphWithDelegate(gl_delegate);

                interpreter->SetAllowFp16PrecisionForFp32(true);
        }

        ~Model()
        {
                interpreter = nullptr;
                TfLiteGpuDelegateDelete(gl_delegate);
        }

        void predict(
                const Size input_size,
                float const* const input_data,
                const Size output_size,
                float* const output_data)
        {
               WriteToInputTensor(interpreter->typed_input_tensor<float>(0));
               interpreter->Invoke();
               ReadFromOutputTensor(interpreter->typed_output_tensor<float>(0));
        }

        private:
                std::unique_ptr<tflite::Interpreter> interpreter;
                TfLiteDelegate* gl_delegate;

                Model(const Model&) = delete;
                Model& operator=(const Model&) = delete;
};

</pre></code>

</details>

Why does this error occur, tell me?

**Comment by tilakrayal** [comment]
@progred2,
Could you please check this [comment](https://github.com/tensorflow/tensorflow/issues/28902#issuecomment-945493161) from the user with similar error and also please try to install latest tensorflow v2.9 and let us know if the issue still persists. Thank you!
