### ISSUE TITLE
Cube root of negative number returns nan

### ISSUE THREAD

**Issue by PyFormulae** [tensorflow/tensorflow#42379]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.3.0-0-gb36436b087 2.3.0
- Python version: 3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: P100, 16GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
tf.constant(-1.)**(1/3.) returns nan

**Describe the expected behavior**
It should return -1

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
tf.constant(-1.)**(1/3.)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Odd roots are defined while even roots are imaginary

**Comment by WindQAQ** [comment]
I think this is c++ semantics on `pow`.

https://en.cppreference.com/w/cpp/numeric/math/pow

> `pow(base, exp)` returns NaN and raises FE_INVALID if base is finite and negative and exp is finite and non-integer.

**Comment by PyFormulae** [comment]
I think this could be done for integer roots. You could implement a separate function for roots called `root`. If it's an odd integer root, return sign(x)*root(abs(x))

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/de7370c64572ba7004c11239e1b0ef5b/42379.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment]
@PyFormulae I think you forgot to add another set of parenthesis. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/87264b76972fdb097a633dae2791f508/42379.ipynb). Thanks!

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by PyFormulae** [comment]
> @PyFormulae I think you forgot to add another set of parenthesis. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/87264b76972fdb097a633dae2791f508/42379.ipynb). Thanks!
> 
> Please verify once and close the issue if this was resolved for you. Thanks!

That computes the cube root of a float, not a tensor.
