### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found - while importing tensorflow 

### ISSUE THREAD

**Issue by sparachi1011** [tensorflow/tensorflow#42372]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version:2.2
- Python version: checked 3.6,3.7,3.8
- Installed using virtualenv? pip? conda?: both pip and conda
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: AMD Radeon(TM) Vega 8 Graphics

**Describe the problem**
facing the problem of module not found while loding DLL when importing tensorflow.
Tried with multiple options like python version, tensorflow versions etc.

is tesnorflow also supports ADM graphic drivers ?
![Tensorflow issue](https://user-images.githubusercontent.com/37170486/90266971-7a6fb280-de72-11ea-86d3-d100f24ce971.png)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
import tensorflow as tf

**Any other info / logs**

import tensorflow
Traceback (most recent call last):

  File "<ipython-input-1-d6579f534729>", line 1, in <module>
    import tensorflow

  File "C:\Users\SaiKoushik\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util

  File "C:\Users\SaiKoushik\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context

  File "C:\Users\SaiKoushik\Anaconda3\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe

  File "C:\Users\SaiKoushik\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Users\SaiKoushik\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\Users\SaiKoushik\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by Saduf2019** [comment]
@sparachi1011 
What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the latest [microsoft visual c++ redistributable from here.](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
.Also, please follow the instructions from to install from [Tensorflow](https://www.tensorflow.org/install/source_windows) website.

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.Please, refer similar issues #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
Thanks!

**Comment by sparachi1011** [comment]
hi @Saduf2019 ,
What is make/model of your cpu: Dell Inspiron 15 5000 series,
I suspect your cpu model does not support AVX instructions sets:: it support, its a ADM Ryzen 5 series(latest version from ADM family)
Make sure to download the latest microsoft visual c++:: yes i have installed MS Visual 2019. 

I can able to install tensorflow 1.15 and keras 2.0 but unable to use the upgraded versions.
Please, check Your CPU/Python is on 32 bits?:: python in on 64bits.

![processor details ](https://user-images.githubusercontent.com/37170486/90385693-1bdc4b80-e0a1-11ea-9f61-bd3ea4d278cb.png)
![VS 2019](https://user-images.githubusercontent.com/37170486/90385698-1d0d7880-e0a1-11ea-9d8b-b810ef3e96d4.png)

**Comment by jvishnuvardhan** [comment]
@sparachi1011 Few questions.
1) did you notice the issue when you installed in `virtualenv`?
2) were you able to install and import TF1.15 without any issue?

Can you please uninstall TF all versions, uninstall python all versions, restart comp/laptop, install python 3.7, install TF2.3 and then check whether you can import without any issue. Thanks!
