### ISSUE TITLE
InvalidArgumentError:  indices[28,46] = -1 is not in [0, 1000) 	 [[node functional_3/embedding_4/embedding_lookup (defined at <ipython-input-64-77fdd54ae821>:5) ]] [Op:__inference_train_function_387521]

### ISSUE THREAD

**Issue by samprithahm** [tensorflow/tensorflow#42375]
I am not sure why this error pops out, New to deep learning, Trying to add bert embedding to the LSTM model.
 Input is CSV of 2 columns - 1st column words, 2nd column labels

Problem: classification problem

**Comment by amahendrakar** [comment]
@samprithahm,
In order to expedite the trouble-shooting process, could you please provide the TensorFlow version, the complete code to reproduce the issue and the TensorFlow version you are using. Thanks!

**Comment by amahendrakar** [comment]
Also, please take a look at issue [#23698](https://github.com/tensorflow/tensorflow/issues/23698#issuecomment-439063103) and [this comment](https://stackoverflow.com/a/51224078) from a similar StackOverflow issue and let us know if it helps. Thanks!
