### ISSUE TITLE
No difference in time for Conv1DTranspose before and after post training quantization

### ISSUE THREAD

**Issue by ayush9096** [tensorflow/tensorflow#42371]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu19.04 Linux
- TensorFlow installed from (source or binary): Source
- TensorFlow version (or github SHA if from source):  2.4.0-dev20200715

**Command used to run the converter or code if you’re using the Python API**

```
class TFConvTranspose1d(tf.keras.Model):

    def __init__(self, channels, ksize, stride, padding):
        super(TFConvTranspose1d, self).__init__()
        self.conv1d_transpose = tf.keras.layers.Conv2DTranspose(
            filters = channels,
            kernel_size = (ksize, 1),
            strides = (stride, 1),
            padding = "same",
        )

    def call(self, x):
#         x = tf.expand_dims(x, axis=2)
        
#         print(" CONV TRANSPOSE 1D ", x.shape)
        x = self.conv1d_transpose(x)
#         print(" CONV TRANSPOSE 1D ", x.shape)
#         x = tf.squeeze(x, axis=2)
        return x
```

**The output from the converter invocation**

```
checkModel = TFConvTranspose1d(256, 16, 8, "same")
input_shape = (1, 100,1,  512)
checkModel.build(input_shape)

x = np.random.rand(1, 100,1,  512)
x = x.astype('float32')

out = checkModel.predict(x)
print( "KERAS OUTPUT : ", out.shape)

print(" Number of Params : ", checkModel.count_params())

tflite_converter = tf.lite.TFLiteConverter.from_keras_model(checkModel)
tflite_converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_converter.allow_custom_ops = True
tflite_converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_converter.post_training_quantize = True
tfmodel = tflite_converter.convert()

open("convTranspose.tflite", "wb").write(tfmodel)
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
-  No difference in time in Raspberry PI before and after quantization
- Producing correct results, but the model is slower than expected (model generated from old converter)

**Comment by karimnosseir** [comment]
Hi,

Few notes:
1) You don't need "tf.lite.OpsSet.SELECT_TF_OPS"
2) You don't need allow_custom_ops = True
3) You don't need "post_training_quantize = True" it is deprecated you should be using tflite_converter.optimizations = [tf.lite.Optimize.DEFAULT] instead.

Now for your model,
Setting optimization only without providing representative dataset like this "tflite_converter.optimizations = [tf.lite.Optimize.DEFAULT]"
will enable only dynamic quantization, which will quantization for weights and activations only if possible.

See the instructions here
https://www.tensorflow.org/lite/performance/post_training_quantization#full_integer_quantization

Thanks

**Comment by ayush9096** [comment]
@karimnosseir  Thanks, for those points,  will try full integer quantization  with some dataset.

**Comment by karimnosseir** [comment]
You're welcome.
Closing the issue. Please feel free to reopen or create new issue if needed.

Thanks
