### ISSUE TITLE
Undocumented S3_DISABLE_MULTI_PART_DOWNLOAD variable and its behavior

### ISSUE THREAD

**Issue by knopt** [tensorflow/tensorflow#42389]
## URL(s) with the issue:

S3 environment variables are partially documented here: https://github.com/tensorflow/examples/blob/master/community/en/docs/deploy/s3.md.
However, there doesn't seem to be a complete documentation of this feature anywhere.

## Description of issue (what needs changing):

TensorFlow's S3 client use `S3_DISABLE_MULTI_PART_DOWNLOAD` environment variable (see [s3_file_system.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/s3/s3_file_system.cc#L482)). However, it's not documented anywhere.

### Clear description

This environment variable disables multi-part download from S3, and S3-like storage systems (like [AIStore](https://github.com/NVIDIA/aistore/)). Neither it's documented in this repository, nor google returns any valid result when searching it.

It's not clear for users (including me) if it's safe to use this variable. It does work, however, is it deprecated or is it going to be supported continuously?

Additionally, the required value of this variable, for multi-part download to be disabled, is any string with the first character `1`, which is not a perfect solution (having in mind lack of documentation).

### Correct links

Source code using this environment variable: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/s3/s3_file_system.cc#L482

### Usage example

There is no documentation, nor usage examples.

**Comment by ymodak** [comment]
Closing this issue since tensoflow/io repo is the right place for this issue.
To know more refer the issue tagged above in the thread. Thanks!
