### ISSUE TITLE
Embedding for Embedding Projector works on one computer, not on another.

### ISSUE THREAD

**Issue by leszekmp** [tensorflow/tensorflow#42380]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 1909
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): Version: 2.3.0 (same problem with 2.2.0)
- Python version: 3.7, 3.8
Working computer
- CUDA/cuDNN version: 10.1
- GPU model and memory: GTX1080 8 GB
Non-working computer 1 (Lenovo Y470P)
- CUDA/cuDNN version 10.1
- GPU model and memory: GTX950M, variable memory
Non-working computer 2 (Dell XPS 8500)
- CUDA/cuDNN version 10.1
-GPU model and memory: GTX970, 4 GB (actually only 3.5 GB)

Projections for use with Embedding Projector works on one computer, doesn't work on two others. On computer 1 I get the "No checkpoint found." message; on computer 2 I get a blank screen in the Projecter area, nothing at all. Computer 1 used to be able to display Embedding Projector with Tensorflow 1.x.  I've never tried running Tensorboard on Computer 2 until now. All systems are 64-bit Windows 10, same version.

Expected behavior was that Embedding projector would work on computers other than my main desktop.

Embedding folders can be downloaded at this link:
https://drive.google.com/file/d/18Zojdf50CmwsS-YulwMMOBYFY-3_YORI/view?usp=sharing

No significant error or logging messages show up.

**Comment by rmothukuru** [comment]
@leszekmp,
Can you please share the below details:

1. Browsers of all the 3 computers, in which you've tried opening Embedding Projector
2. Operating Systems of all the 3 Computers
3. Screenshots of both working and non-working Embedding Projectors.
4. Steps you have followed to visualize the embeddings.

Thanks!

**Comment by leszekmp** [comment]
Thanks for responding! Checked my original posting, and the info I gave got scrambled. I've tried it on three computers:

A. My main computer (the one it's working on):
CUDA/cuDNN version: 10.1
GPU model and memory: GTX1080 8 GB
System memory: 64 GB RAM
Intel 6-core processor

B. My laptop ( the first one it's not working on):
Lenovo Y470P, 16 GB RAM, 4-core Intel processor
CUDA/cuDNN version 10.1
GPU model and memory: GTX950M, variable memory

C. My secondary desktop (the second one it's not working on):
Dell XPS 8500, 32 GB RAM, 4-core Intel processor
CUDA/cuDNN version 10.1
-GPU model and memory: GTX970, 4 GB (actually only 3.5 GB)


1. I've tried Chrome and Edge on all three computers. Chrome and Edge both work on the "working computer", both don't work on the other two. All three systems run Tensorboard 2.2.2.
2. All three systems run Windows 10 1909.
3. I've attached screenshots from all three computers from Chrome at the bottom; Edge looks identical.
4.  Here's the Python code that creates the embedding files for Tensorboard. (Frankensteined from online code I found). One of these days, I'll update it to TF 2. The sprite and metadata files are created elsewhere. 

def register_embedding(embedding_tensor_name, meta_data_fname, sprite_name, log_dir):
    image_dims=[224,224]
    config = projector.ProjectorConfig()
    embedding = config.embeddings.add()
    embedding.tensor_name = embedding_tensor_name + ":0"
    embedding.metadata_path = meta_data_fname
    embedding.sprite.image_path = sprite_name
    embedding.sprite.single_image_dim.extend(image_dims)
    projector.visualize_embeddings(log_dir, config)

LOG_DIR = PATH+ '/' + test_id
META_DATA_FNAME = test_id+ '.meta.tsv'  # Labels will be stored here
EMBEDDINGS_TENSOR_NAME = 'features'
EMBEDDINGS_FPATH = os.path.join(LOG_DIR, EMBEDDINGS_TENSOR_NAME + '.ckpt')
SPRITE_NAME=test_id+'.jpg'
STEP=0

register_embedding(EMBEDDINGS_TENSOR_NAME, META_DATA_FNAME, SPRITE_NAME, LOG_DIR)

tensor_embeddings = tf.Variable(feature_vectors, name=EMBEDDINGS_TENSOR_NAME)
saver = tf.compat.v1.train.Saver([tensor_embeddings])  # Must pass list or dict
saver.save(sess=None, global_step=STEP, save_path=EMBEDDINGS_FPATH)

Same command used on all three for invoking Tensorboard: tensorboard --logdir (data_directory). I use the same batch file for all three computers to start up Tensorboard, but I've also hand-typed the commands as well, and they only work on my main computer.

5. I tried switching over to the online projector (project.tensorflow.org), but ran into a problem. PCA and UMAP look the same on both my main "working computer" and the online projector, but t-SNE looks completely different. Have checked the t-SNE settings multiple times, and they're the same on both the local and web projectors. No idea as to why t-SNE looks different, but the other two don't.

![TB_working_computer](https://user-images.githubusercontent.com/8127516/90819433-d5772e80-e2e4-11ea-8464-a2ed12beb8e3.png)
![TB_not_working_laptop](https://user-images.githubusercontent.com/8127516/90819430-d4de9800-e2e4-11ea-9d5b-742456504b69.png)
![TB_not_working_desktop](https://user-images.githubusercontent.com/8127516/90819436-d60fc500-e2e4-11ea-8dc2-e0ad22b22b28.png)

**Comment by tilakrayal** [comment]
@leszekmp,
Could you please try the below steps and test in your environment:

- Try restarting the TensorBoard server on both computers.
- Clear the browser's cache and cookies.
- Try using a different browser.
- Make sure that the embedding data is accessible to the server.

Also please take a look at this [issue](https://github.com/tensorflow/tensorboard/issues/4673) and the SO [link](https://stackoverflow.com/questions/52612984/how-to-extract-tensorflow-trained-weights-from-graph-pbtxt-to-raw-data?rq=1) for the reference. Thank you!
