### ISSUE TITLE
Tensorflow Aborted due to tensorflow/core/lib/monitoring/sampler.cc:42

### ISSUE THREAD

**Issue by nrchaudhry** [tensorflow/tensorflow#42387]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
Binary
- TensorFlow version (use command below):
- Python version:
All versions
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
Can't import

**Describe the current behavior**
2020-08-15 13:43:45.726668: F tensorflow/core/lib/monitoring/sampler.cc:42] Check failed: bucket_limits_[i] >
Aborted

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@nrchaudhry 
Can you please update the issue template, tf version and the steps performed before the error was encountered, and the error logs for us to analyse.

**Comment by bdockbockd** [comment]
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/32613582/106357008-18c6d600-6336-11eb-87fb-4949bc0d543d.png">
I'm stucking from this monitoring. Could anyone help?

**Comment by Saduf2019** [comment]
@bdockbockd 
Please create a new issue as this is closed.

**Comment by scchess** [comment]
Tensorflow no longer supports Mac OSX. This error message will come up while running Tensorflow on Mac OSX.

**Comment by carlthome** [comment]
@scchess are you sure about that? I thought it was only GPU support that got removed but that CPU support should still work on macOS. There are still wheels published for Mac on PyPI anyway: https://pypi.org/project/tensorflow/#files

**Comment by harraz** [comment]
Still getting this error message every time I try to import tensorflow
F tensorflow/core/lib/monitoring/sampler.cc:42] Check failed: bucket_limits_[i] > bucket_limits_[i - 1] (0 vs. 10)
qemu: uncaught target signal 6 (Aborted) - core dumped

Any ideas or clear steps to fix this?
I'm running a docker container on a Apple M1 Pro chip

**Comment by harraz** [comment]
> <img alt="image" width="1164" src="https://user-images.githubusercontent.com/32613582/106357008-18c6d600-6336-11eb-87fb-4949bc0d543d.png">
> 
> I'm stucking from this monitoring. Could anyone help?

Did you find a way to solve this problem?
