### ISSUE TITLE
tf-nightly: 'bfloat16' in namespace 'Eigen' does not name a type.

### ISSUE THREAD

**Issue by tgaddair** [tensorflow/tensorflow#42392]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, custom op
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf-nightly==2.4.0.dev20200815
- Python version: 3.6.9
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: 7.6.5.32
- GPU model and memory: t4

**Describe the current behavior**

Attempting to compile a custom op (Horovod) with the latest tf-nightly produces numerous error messages of the form:

```

In file included from /usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/platform/types.h:21:0,

from /usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/platform/logging.h:20,
from /usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/platform/status.h:24,
from /usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/lib/core/status.h:19,
from /usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/framework/op_def_builder.h:25,
from /usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/framework/op.h:23,
from horovod/tensorflow/mpi_ops.cc:24:
/usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/platform/bfloat16.h:25:16: error: 'bfloat16' in namespace 'Eigen' does not name a type
typedef Eigen::bfloat16 bfloat16;
^~~~~~~~
```

This may be related to https://github.com/tensorflow/tensorflow/commit/576d1d395d01a24483a9ebf66ba704ba38043e63 and https://github.com/tensorflow/tensorflow/commit/dab490a8bfb0cf1f289c9352c4d086356d0e5949 which were merged yesterday.

Looks like there may be some missing headers.

**Comment by amahendrakar** [comment]
@tgaddair,
Could you please provide the complete code and the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by tgaddair** [comment]
Hey @amahendrakar, looks like the issue was due to a conflict between TensorFlow's use of Eigen and the version we were using for our code.  After updating Eigen, the issue was solved.

**Comment by ahoereth** [comment]
> Hey @amahendrakar, looks like the issue was due to a conflict between TensorFlow's use of Eigen and the version we were using for our code. After updating Eigen, the issue was solved.

Hi @tgaddair -- I also ran into this. What version(s) are you using? Built tensorflow from source and brought over the third_party libs and its Eigen. The rest of the codebase uses Eigen 3.3.7.

**Comment by tgaddair** [comment]
Hey @ahoereth, it may be that you're pointing to the old GitHub repo for Eigen.  They switched over to GitLab about a year ago, and the previous repo hasn't been updated since.  Updating to point to GitLab addressed the issue for us: https://gitlab.com/libeigen/eigen

**Comment by ahoereth** [comment]
Thanks for the quick response, I'm using the 3.3.7 release targz from https://gitlab.com/libeigen/eigen. Am now building a older version of tensorflow to see whether the commits you reference actually produced the problem.
