### ISSUE TITLE
TFA can't load _image_ops.so - says file doesn't exist, but its there?

### ISSUE THREAD

**Issue by jeball** [tensorflow/tensorflow#42398]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64-bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): TF 2.1.0 installed via conda
- TensorFlow version: 2.1.0
- Python version: 3.7.0
- Installed using virtualenv? pip? conda?: TF installed via conda, TFA via pip.
TFA installed via pip install tensorflow_addons==0.9.1

- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
# packages in environment at C:\ProgramData\Anaconda3\envs\tf:
#
# Name                    Version                   Build  Channel
cudnn                     7.6.5                cuda10.1_0
- GPU model and memory:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 442.19       Driver Version: 442.19       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108... WDDM  | 00000000:01:00.0  On |                  N/A |
| 23%   38C    P8    17W / 250W |   1049MiB / 11264MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108... WDDM  | 00000000:03:00.0 Off |                  N/A |
| 23%   29C    P8     9W / 250W |    137MiB / 11264MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Describe the problem**

TFA can't load _image_ops.so

File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow_addons\image\distance_transform.py", line 69, in euclidean_dist_transform
    output = _image_so.ops.addons_euclidean_distance_transform(images)
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow_addons\utils\resource_loader.py", line 56, in ops
    self._ops = tf.load_op_library(get_path_to_datafile(self.relative_path))
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\framework\load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow_addons\custom_ops\image\_image_ops.so not found

The file exists in the specified directory

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

As you can see, the library file is clearly there...

(tf) C:\ProgramData\Anaconda3\envs\tf\Lib\site-packages\tensorflow_addons\custom_ops\image>dir
 Volume in drive C has no label.
 Volume Serial Number is 62E0-530C

 Directory of C:\ProgramData\Anaconda3\envs\tf\Lib\site-packages\tensorflow_addons\custom_ops\image

08/15/2020  02:19 PM    <DIR>          .
08/15/2020  02:19 PM    <DIR>          ..
08/15/2020  02:19 PM           172,544 _distort_image_ops.so
08/15/2020  02:19 PM           977,408 _image_ops.so
08/15/2020  02:19 PM           169,984 _resampler_ops.so
               3 File(s)      1,319,936 bytes
               2 Dir(s)  255,060,709,376 bytes free

Here is the code.

```
"""
    Debug Euclidean distance
"""
from silence_tensorflow import silence_tensorflow
silence_tensorflow()

import os
os.system('cls' if os.name == 'nt' else 'clear')

import warnings
warnings.filterwarnings('ignore', category=FutureWarning)

import tensorflow
import numpy as np
import tensorflow_addons as tfa
import matplotlib.pyplot as plt

with tensorflow.device('/GPU:1'):

    M = 500
    img = np.zeros((M, M))
    top = 50
    bottom = 270
    left = 300
    right = 450
    img[np.ix_(np.arange(top, bottom + 1), np.arange(left, right + 1))] = 1
    img = tensorflow.convert_to_tensor(img)
    img = tensorflow.expand_dims(img, -1)
    img = img.numpy()

    # TFA - Euclidean distance transform
    img = tensorflow.cast(img, dtype=tensorflow.uint8)
    d_img = tfa.image.euclidean_dist_transform(img)  # See https://github.com/tensorflow/addons

    # Plot it
    plt.figure()
    plt.title('True TFA Distance Image')
    _ = plt.imshow(d_img)

    # Tell user how to end code.
    print("\nPress ctrl-c or ctrl-break or close windows to exit.\n")
    plt.show()
```

Thanks for the help. I can't understand why the system is telling me this library doesn't exist.

**Comment by Saduf2019** [comment]
@jeball 
I am facing a different error when i run your code, please find [gist here](https://colab.research.google.com/gist/Saduf2019/6842c50df0023878987da3ba10816559/untitled373.ipynb).
Can you please share a colab gist with the error faced for us to analyse.

**Comment by jeball** [comment]
Just remove the first lines. Here is the code.

import tensorflow
import numpy as np
import tensorflow_addons as tfa
import matplotlib.pyplot as plt

with tensorflow.device('/CPU:0'):

    M = 500
    img = np.zeros((M, M))
    top = 50
    bottom = 270
    left = 300
    right = 450
    img[np.ix_(np.arange(top, bottom + 1), np.arange(left, right + 1))] = 1
    img = tensorflow.convert_to_tensor(img)
    img = tensorflow.expand_dims(img, -1)
    img = img.numpy()

    # TFA - Euclidean distance transform
    img = tensorflow.cast(img, dtype=tensorflow.uint8)
    d_img = tfa.image.euclidean_dist_transform(img)  # See https://github.com/tensorflow/addons

    # Plot it
    plt.figure()
    plt.title('True TFA Distance Image')
    _ = plt.imshow(d_img)

    # Tell user how to end code.
    print("\nPress ctrl-c or ctrl-break or close windows to exit.\n")
    plt.show()

**Comment by jeball** [comment]
I didn't mean to close this. Hit wrong button.

**Comment by Saduf2019** [comment]
@jeball 
I ran the code and face an error please refer to [gist here](https://colab.research.google.com/gist/Saduf2019/aac88f6c369b8d569071c5929e44cf48/untitled367.ipynb).

**Comment by jeball** [comment]
Thanks

I think the problem is tensorflow 2.1 GPU was installed with anaconda and tensorflow addons with pip and they seem to be incompatible. The error you get is different from the error I am receiving. I think to resolve I need to install tensorflow with pip.

Can you verify – after more research this seems to be the main problem.

John Ball, Ph.D.
Associate Professor and Robert Guyton Endowed Chair for Teaching Excellence | Electrical and Computer Engineering

[cid:image001.png@01D67531.64CF41C0]
Associate Editor | IEEE Signal Processing Letters
Associate Editor | Journal of Applied Remote Sensing
Editorial Board Member | MDPI Electronics
Faculty Advisory Council | Transactions on Stem Education
Lab Director | Simrall Radar Laboratory
Lab Co-Director | Center for Advanced Vehicular Systems (CAVS) Sensor Lab
Research Fellow | Geosystems Research Institute (GRI)
Simrall 233, 406 Hardy Rd., Mississippi State, MS 39762
p:662.325.4169  e:jeball@ece.msstate.edu<mailto:jeball@ece.msstate.edu>

**Comment by jeball** [comment]
My error was with TF 2.1.0, not 2.3.0

John Ball, Ph.D.
Associate Professor and Robert Guyton Endowed Chair for Teaching Excellence | Electrical and Computer Engineering

[cid:image001.png@01D67537.E129C370]
Associate Editor | IEEE Signal Processing Letters
Associate Editor | Journal of Applied Remote Sensing
Editorial Board Member | MDPI Electronics
Faculty Advisory Council | Transactions on Stem Education
Lab Director | Simrall Radar Laboratory
Lab Co-Director | Center for Advanced Vehicular Systems (CAVS) Sensor Lab
Research Fellow | Geosystems Research Institute (GRI)
Simrall 233, 406 Hardy Rd., Mississippi State, MS 39762
p:662.325.4169  e:jeball@ece.msstate.edu<mailto:jeball@ece.msstate.edu>

**Comment by Saduf2019** [comment]
@jeball 
Please try latest version of tf and let us know if the issue exist.

**Comment by jeball** [comment]
Last I knew TF 2.1.0 was the latest version supported on Windows 10. I will try TF 2.3.
I still have a question – if I install via Conda will it work or does it require a pip install?

Thanks

John Ball, Ph.D.
Associate Professor and Robert Guyton Endowed Chair for Teaching Excellence | Electrical and Computer Engineering

[cid:image001.png@01D6760D.8BD3BC10]
Associate Editor | IEEE Signal Processing Letters
Associate Editor | Journal of Applied Remote Sensing
Editorial Board Member | MDPI Electronics
Faculty Advisory Council | Transactions on Stem Education
Lab Director | Simrall Radar Laboratory
Lab Co-Director | Center for Advanced Vehicular Systems (CAVS) Sensor Lab
Research Fellow | Geosystems Research Institute (GRI)
Simrall 233, 406 Hardy Rd., Mississippi State, MS 39762
p:662.325.4169  e:jeball@ece.msstate.edu<mailto:jeball@ece.msstate.edu>

**Comment by Saduf2019** [comment]
@jeball 
>>I still have a question – if I install via Conda will it work or does it require a pip install?
     You can go ahead with either of them, and let us know.
