### ISSUE TITLE
Add Object Detection EfficientDet/Retinanet Model(s) to tf.keras.applications

### ISSUE THREAD

**Issue by DrChrisLevy** [tensorflow/tensorflow#42393]
**System information**
- TensorFlow version (2.3): Although this request feels very TF 2.4.
- Are you willing to contribute it: I could be involved in testing. 

**Describe the feature and the current behavior/state.**

`tf.keras.applications` is amazing. With all the model architectures and the pre-trained weights there is a lot
of possibilities for transfer learning and feature extraction. However, there are not any object detection models.

I would love to see some object detection models baked into 
`tf.keras.applications`  as well as pre-trained weights (trained on object detection tasks like coco for example) that would make it possible for training new object detection models, via transfer learning, on custom data. Very much like how the current API works for classification models for example i.e. (import resnet, remove top/head, add layer, freeze, train).

Since we already have Resnet backbones and Efficient backbones (as of TF 2.3), would it be possible to add object detection architectures on top of these such as [Retinanet](https://arxiv.org/abs/1708.02002) or [EfficientDet](https://arxiv.org/abs/1911.09070). As well as have the pre-trained weights trained on coco for example for such models. Then having some sort of easy way to adjust these for training on custom object detection data. Much like with the current models we can remove the top/head and add on top for custom classifiers. 

It's not straight forward to get started with object detection using tf.keras.  I am also aware of the newly designed TF Models Detection API but it still feels bloated and very disconnected from TF main library. It would be lovely to see something built into tf.keras.applications.

**Will this change the current api? How?**
Just by adding the new feature request.

**Who will benefit with this feature?**
All users of tf.keras.applications. Anyone working in industry with current TF 2 in their tech stack looking to add object detection functionality.

**Any Other info.**
I think this would be amazing! 

There is the project https://github.com/google/automl/tree/master/efficientdet which is Google and it seems like they are trying to use tf.keras there some. There is also https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md but it has so much else going on in it. How can we take these projects and pick out the pieces and build for example EfficientDet into tf.keras.applications. At the moment things are convoluted and lots of outside projects. Having this within tf.keras.applications main code would be nice and easier to build off in existing tech stacks that already use Tensorflow.

**Comment by aavishkarmishra** [comment]
Hello @ymodak, I would like to work on this issue. I am new to this but this **can help me learn alot**. 
Can you tell where I have to add this in your code base?

**Comment by DrChrisLevy** [comment]
@aavishkarmishra , love the enthusiasm but I think this is a good project for internal Google developers and core tf.keras team developers. It’s a fairly big ask but one that I think would have tons of value.

**Comment by DrChrisLevy** [comment]
@pengchongjin @fchollet , think this will get any attention? Thanks for your hard work.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
