### ISSUE TITLE
Hi everybody, I 'm trying to excute a free avialble code for CNN model to classify 4 classes of dogs, cats, horses and humans. Unfortunatly, I faced this issue: "ValueError: Calling `Model.fit` in graph mode is not supported when the `Model` instance was constructed with eager mode enabled. Please construct your `Model` instance in graph mode or call `Model.fit` with eager mode enabled." how can I handle it?

### ISSUE THREAD

**Issue by Al-Badri179** [tensorflow/tensorflow#42395]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/MyMethod

### Clear description

For example, why should someone use this method? How is it useful?

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example?

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by amahendrakar** [comment]
@Al-Badri179,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!

**Comment by mihaimaruseac** [comment]
Template not filled in. Wrong template used (issue is a bug, template is documentation issues). Title contains the entire issue. This is actually not a TF coding issue but a question regarding usage of TF, probably better asked on StackOverflow.

**Comment by Al-Badri179** [comment]
@amahendrakar 

tensorflow-estimator     2.3.0
Keras                              2.4.3

This is the code for the CNN modal:
[CNN modal.txt](https://github.com/tensorflow/tensorflow/files/5086292/CNN.modal.txt)

for the dataset it is free available on the internet (dogs, cats, horses, humans)
