### ISSUE TITLE
Error. Converter does not support Quantization NN with 'tanh' activation

### ISSUE THREAD

**Issue by mr-goldhands** [tensorflow/tensorflow#42390]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 2.3.0 (Google Collab)

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.
https://colab.research.google.com/drive/12K7FKEFvbJx7gUuI93hsS6si1n0zYRSO?usp=sharing

```
# Copy and paste here the exact command
```

**The output from the converter invocation**

```
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/tracking.py:111: Layer.updates (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/tracking.py:111: Layer.updates (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: /tmp/tmpnq1srnbk/assets
INFO:tensorflow:Assets written to: /tmp/tmpnq1srnbk/assets
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-27-89960d743844> in <module>()
      9 converter.representative_dataset = representative_dataset_generator
     10 
---> 11 tflite_model = converter.convert()

3 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/optimize/calibrator.py in calibrate_and_quantize(self, dataset_gen, input_type, output_type, allow_float, activations_type, resize_input)
     96         np.dtype(input_type.as_numpy_dtype()).num,
     97         np.dtype(output_type.as_numpy_dtype()).num, allow_float,
---> 98         np.dtype(activations_type.as_numpy_dtype()).num)
     99 
    100   def calibrate_and_quantize_single(self,

RuntimeError: Quantization not yet supported for op: 
```

**Also, please include a link to the saved model or GraphDef**

```
See in Google Collab notebook.
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Converter fails during conversion

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

My network uses 'tanh' activation.
If I use 'tanh' activation the converter fails.
If I use only 'relu' activations the converter does conversion successfully.

**Comment by MeghnaNatraj** [comment]
Thanks for catching this bug! :) @liufengdb is looking into this and will post an update when it's fixed!

**Comment by liufengdb** [comment]
I will create a fix internally and will push it to open source.

**Comment by gan3sh500** [comment]
What is the recommended way to debug such errors? If many possible operations are there which can fail. Is there a way to see which Op it was trying convert when failure happens?

**Comment by MeghnaNatraj** [comment]
Ideally you shouldn't face this issue. If you do, the error should contain the name of the operator that failed (we're looking why it currently doesn't print the name) so the user can either change the operator (as the TFLite doesn't support quantization for it yet) or file a bug so we can look into it (such as the current github issue).

**Comment by MeghnaNatraj** [comment]
Closing the issue as it's resolved, feel free to re-open this if it's unresolved.
