### ISSUE TITLE
Using Linear Algebraic Functions In TensorFlow Python

### ISSUE THREAD

**Issue by LeavesBreathe** [tensorflow/tensorflow#424]
Hey TF, 

Matrix norm in python, it doesn't appear the documentation. However, in your Eigen section, there is a matrix norm function. 

Is it possible to use these eigen functions via python and ensure that it is performed on the gpu? These linear algebraic functions are very easy to do in theano, but I'm having difficulty figuring out how to do this in python. 

My ultimate goal is to perform a [euclidean norm](http://mathworld.wolfram.com/FrobeniusNorm.html).  I just don't know what is the best way to do this in python would be. Thanks!

**Comment by LeavesBreathe** [comment]
Oh wow...I'm pretty dumb...You can just make them from tensorflow's functions. In case anyone needs them:

```python
def euclidean_norm(tensor, reduction_indicies = None):
	squareroot_tensor = tf.sqrt(tensor)
	euclidean_norm = tf.sum(squareroot_tensor, reduction_indicies =  reduction_indicies)
	return euclidean_norm

def frobenius_norm(tensor, reduction_indicies = None):
	squareroot_tensor = tf.sqrt(tensor)
	tensor_sum = tf.sum(squareroot_tensor, reduction_indicies =  reduction_indicies)
	frobenius_norm = tf.sqrt(tensor_sum)
	return frobenius_norm
```

**Comment by ebrevdo** [comment]
For your norms, I think you want to square before the sum instead of sqrt.

**Comment by LeavesBreathe** [comment]
@ebrevdo Thanks for the correction! Here are they corrected:

```python
def euclidean_norm(tensor, reduction_indicies = None, name = None):
	with tf.op_scope(tensor + reduction_indicies, name, "euclidean_norm"): #need to have this for tf to work
		squareroot_tensor = tf.square(tensor)
		euclidean_norm = tf.sum(squareroot_tensor, reduction_indicies =  reduction_indicies)
		return euclidean_norm

def frobenius_norm(tensor, reduction_indicies = None, name = None):
	with tf.op_scope(tensor + reduction_indicies, name, "frobenius_norm"): #need to have this for tf to work
		squareroot_tensor = tf.square(tensor)
		tensor_sum = tf.sum(squareroot_tensor, reduction_indicies =  reduction_indicies)
		frobenius_norm = tf.sqrt(tensor_sum)
		return frobenius_norm

```
