### ISSUE TITLE
[new feature]: Roll slice of a tensor

### ISSUE THREAD

**Issue by yiliu9090** [tensorflow/tensorflow#42402]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):2.30
- Are you willing to contribute it (Yes/No):
Yes

**Describe the feature and the current behavior/state.**

I want tf.roll to do the following, I want to roll only one row. out of all the rows.
[[0,1,2,3,4],
[5,6,7,8,9]]
I want to roll only the bottom row by 2. i.e. the result will be 
[[0,1,2,3,4]
[8,9,5,6,7]]
 
Currently, tf.roll can do 
[[3,4,0,1,2]
[8,9,5,6,7]]
but not be specific row

**Will this change the current api? How?**
Add new feature to tensorflow
**Who will benefit with this feature?**

Many System biologists and physicist who want to use TensorFlow to compute Transcription Models. A key breakthrough on this idea. 
I am planning to implement the algorithms in this paper at larger scale for much harder problems. 
https://academic.oup.com/bioinformatics/article/36/Supplement_1/i499/5870526

**Any Other info.**

**Comment by rohan100jain** [comment]
I don't think we need to change tf.roll to accomplish this. We can achieve this by slice assignment

a = [[0,1,2,3,4], [5,6,7,8,9]]

```
tf_a = tf.constant(a)
updated_slice = tf.roll(tf_a[1, :], 2, axis=0)
tf_b = tf.tensor_scatter_nd_update(tf_a, [[1]], [updated_slice])
```
where tf.tensor_scatter_nd_update does the slice assignment logic. If we had numpy like slice update APIs, it could have been a bit more easier e.g.

```
np_a = np.array(a)
np_a[1, :] = np.roll(np_a[1, :], 2, axis=0)
```
