### ISSUE TITLE
Cannot initialize variables on GPU with keras?

### ISSUE THREAD

**Issue by ziofil** [tensorflow/tensorflow#42409]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.1 LTS
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.8.2
- CUDA/cuDNN version: 10.2/7.4.2
- GPU model and memory: Tesla V100-PCIe 32GB

**Describe the current behavior**
When I call `model.fit()` for a Keras model on the GPU, I get the following error message:
```python
InvalidArgumentError: Cannot assign a device for operation quantum_circuit/quantum_layer/ReadVariableOp: Could not satisfy explicit device specification '' because the node {{colocation_node quantum_circuit/quantum_layer/ReadVariableOp}} was colocated with a group of nodes that required incompatible device '/job:localhost/replica:0/task:0/device:GPU:0'. All available devices [/job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0, /job:localhost/replica:0/task:0/device:GPU:0]. 
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=2 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
ResourceApplyAdam: CPU XLA_CPU XLA_GPU 
_Arg: GPU CPU XLA_CPU XLA_GPU 
ReadVariableOp: GPU CPU XLA_CPU XLA_GPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  quantum_circuit_quantum_layer_readvariableop_resource (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  adam_adam_update_resourceapplyadam_m (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  adam_adam_update_resourceapplyadam_v (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  quantum_circuit/quantum_layer/ReadVariableOp (ReadVariableOp) 
  Adam/Adam/update/ResourceApplyAdam (ResourceApplyAdam) 

	 [[{{node quantum_circuit/quantum_layer/ReadVariableOp}}]] [Op:__inference_train_function_6330]
```

I can avoid it if in the `build()` method of my custom Keras layers I call `add_weight()` inside a `tf.device('/CPU:0')` context (I tried this after I read the top post in issue https://github.com/tensorflow/tensorflow/issues/1310, from 2016!)

Is this what should be done? It seems that the GPU is heavily underused if I do that.

**Describe the expected behavior**
I would expect Keras/TF to handle device assignment on its own, and not force me to adapt the code for each machine where it runs.

**Standalone code to reproduce the issue**
Code is way too long

**Comment by ziofil** [comment]
I've also tried to explicitly call the code in my custom initializers (which I pass to `build(..., initializer=...)`) inside a `tf.device('CPU:0')` context, and to use `tf.config.set_soft_device_placement(True)`, but that leads me to the same error.

**Comment by sanjoy** [comment]
What is the type of the variable?  `ResourceApplyAdam` has GPU kernels for floating point types.

@jaingaurav should we be logging the dtypes from the error message above?

**Comment by sushreebarsa** [comment]
@ziofil  Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!

**Comment by seednov** [comment]
same on tf1.15
