### ISSUE TITLE
ConverterError: input resource[0] expected type resource != float, the type of while_model_embed_gather_resource_0[0]

### ISSUE THREAD

**Issue by usimarit** [tensorflow/tensorflow#42410]
**System information**
- OS Platform and Distribution: Linux archlinux 5.8.1-arch1-1 x86_64 GNU/Linux (using Anaconda3)
- TensorFlow installed from (source or binary): pip
- TensorFlow version (or github SHA if from source): >=2.2.0

**Command used to run the converter or code if you’re using the Python API**

```python
import tensorflow as tf
print(tf.__version__)


class Embed(tf.keras.layers.Layer):
    def __init__(self, vocab_size, embed_dim, **kwargs):
        self.vocab_size = vocab_size
        self.embed_dim = embed_dim
        super().__init__(**kwargs)

    def build(self, input_shape):
        self.embeddings = self.add_weight(
            "weight",
            shape=[self.vocab_size, self.embed_dim],
            initializer=tf.keras.initializers.GlorotNormal(),
        )

    def call(self, inputs):
        return tf.gather(self.embeddings, tf.cast(inputs, tf.int32))


class Model(tf.keras.Model):
    def __init__(self, vocab_size, embed_dim, **kwargs):
        super().__init__(**kwargs)
        self.embed = Embed(vocab_size, embed_dim)
        self.dense = tf.keras.layers.Dense(350)

    def _build(self):
        self(tf.keras.Input([None], dtype=tf.int32))

    def call(self, inputs, training=False):
        outputs = self.embed(inputs, training=training)
        return self.dense(outputs, training=training)


model = Model(29, 320)
model._build()
model.summary()


@tf.function(
    input_signature=[
        tf.TensorSpec([1, None], dtype=tf.int32)
    ]
)
def func(inputs):
    i = tf.constant(0, dtype=tf.int32)
    T = tf.constant(100, dtype=tf.int32)

    def _cond(i, T): return tf.less(i, T)

    def _body(i, T):
        _ = model(inputs)
        return i + 1, T

    _, _ = tf.while_loop(
        _cond,
        _body,
        loop_vars=(i, T),
        shape_invariants=(
            tf.TensorShape([]),
            tf.TensorShape([])
        )
    )

    return inputs


print(func(tf.zeros([1, 100], tf.int32)))

concrete_func = func.get_concrete_function()
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
tflite = converter.convert()
```

**The output from the converter invocation**

[log.txt](https://github.com/tensorflow/tensorflow/files/5080482/log.txt)

Short output:

```
Traceback (most recent call last):
  File "test.py", line 77, in <module>
    tflite = converter.convert()
  File "/home/nlhuy/anaconda3/envs/tf/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 1076, in convert
    return super(TFLiteConverterV2, self).convert()
  File "/home/nlhuy/anaconda3/envs/tf/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 899, in convert
    return super(TFLiteFrozenGraphConverterV2,
  File "/home/nlhuy/anaconda3/envs/tf/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 629, in convert
    result = _toco_convert_impl(
  File "/home/nlhuy/anaconda3/envs/tf/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 569, in toco_convert_impl
    data = toco_convert_protos(
  File "/home/nlhuy/anaconda3/envs/tf/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 202, in toco_convert_protos
    raise ConverterError(str(e))
tensorflow.lite.python.convert.ConverterError: input resource[0] expected type resource != float, the type of while_model_embed_gather_resource_0[0]
	In {{node while/model/embed/Gather}}
```

**Failure details**
If I don't use `tf.while_loop`, the conversion works. However, it doesn't if I use `tf.gather` inside `tf.while_loop`

**Any other info / logs**
This bug also occurs in `tf.keras.layers.Embedding`

**Comment by dathudeptrai** [comment]
@usimarit expand last dimention in ur input so [1, None] -> [1, None, 1] then use `tf.gather_nd` rather than `tf.gather`. I just tested, it works fine but not convinced :))). @jaeyoo can you take a look :)).

**Comment by Saduf2019** [comment]
@usimarit 
Please update as per above comment.

**Comment by usimarit** [comment]
@Saduf2019 I've tested the solution provided by @dathudeptrai and it works. Thank you a lot :smile:

**Comment by dathudeptrai** [comment]
@Saduf2019 even it woks it's still not convinced, we should fix the `tf.gather` problem :)).

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find [gist here](https://colab.research.google.com/gist/Saduf2019/29ff1ec42f9401833986c08086c586ff/untitled377.ipynb)

**Comment by gyin-ai** [comment]
Look forward to this fix. Since huggingface transformers uses tf.gather for embeddings lookup. And it is currently blocked by this issue for coreml conversion.

**Comment by karimnosseir** [comment]
Meghna, can you please have a look

Thanks

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF 2.6.0-dev20210528,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/981de58c616763b39d1012eb55dbfec6/untitled64.ipynb#scrollTo=PdHnKroHlnYZ)..Thanks !

**Comment by hetarth18** [comment]
I am also facing the same issue. 
My methodology is as below->

1 - I am trying to build a model using the TF-Hub's universal-sentence-encoder in TF2.0 to serve as the embeddings like below -
`embedding = "https://tfhub.dev/google/universal-sentence-encoder/4" # SOTA Achieved with this
# hub_layer = hub.KerasLayer(embedding, input_shape=[],
#                            dtype=tf.string, trainable=True)
hub_layer = hub.KerasLayer(embedding, input_shape=[],dtype=tf.string, trainable=True)
model = tf.keras.Sequential()
model.add(hub_layer)
# model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dense(64, activation='elu',input_shape=(512,)))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(32, activation='swish'))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001), 
              loss='binary_crossentropy',
              metrics=['accuracy'])`
              
2 - Now I am trying to save the model definition into a single .pb file using the below approach 
```

# Convert Keras model to ConcreteFunction
full_model = tf.function(lambda x: model(x))
full_model = full_model.get_concrete_function(
    tf.TensorSpec(model.inputs[0].shape, model.inputs[0].dtype, name="input"))
# Get frozen ConcreteFunction
frozen_func = convert_variables_to_constants_v2(full_model)
frozen_func.graph.as_graph_def()
layers = [op.name for op in frozen_func.graph.get_operations()]
print("-" * 50)
print("Frozen model layers: ")
for layer in layers:
    print(layer)
print("-" * 50)
print("Frozen model inputs: ")
print(frozen_func.inputs)
print("Frozen model outputs: ")
print(frozen_func.outputs)
# Save frozen graph from frozen ConcreteFunction to hard drive
tf.io.write_graph(graph_or_graph_def=frozen_func.graph,
                  logdir="./frozen_models",
                  name="frozen_graph_keraslayer.pb",
                  as_text=False)


```

3 - On running these codes, the warning can be seen. 


OS  - macOS Catalina intel i3 2020
Python Version - 3.7.11
TF Version - 2.7.0
TF-Hub Version - 0.12.0
 

Tagging everyone to bump this topic up again. @usimarit, @MeghnaNatraj , @ymodak, @dathudeptrai , @karimnosseir

**Comment by mohantym** [comment]
@usimarit !
This issue is getting resolved by passing model while importing concrete function.
Attached [gist](https://colab.research.google.com/gist/manas1988/f9149946fa489b7db97dd8e85521506f/github_42410.ipynb#scrollTo=pfsehHEPlwRo) for reference.

Thank you!

**Comment by mohantym** [comment]
@usimarit !
This issue is getting resolved by passing model while importing concrete function.
Attached [gist](https://colab.research.google.com/gist/manas1988/f9149946fa489b7db97dd8e85521506f/github_42410.ipynb#scrollTo=pfsehHEPlwRo) for reference.

Thank you!
