### ISSUE TITLE
InternalError : failed to call ThenRNNBackward... on version 2.3 but not 2.1

### ISSUE THREAD

**Issue by Ananas120** [tensorflow/tensorflow#42412]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:/
- TensorFlow installed from (source or binary): Installed with pip
- TensorFlow version (use command below): tensorflow 2.3
- Python version: 3.6
- Bazel version (if compiling from source): /
- GCC/Compiler version (if compiling from source): /
- CUDA/cuDNN version: CUDA 10.1 and CuDnn 7.5
- GPU model and memory: GeForce GTX 1070 with 6,2Gb memory

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

In march, i coded the Tacotron-2 model with tensorflow 2.1 and trained it without issue (but some strange thing but not the subject of this issue)
Now i want to retrain it with version 2.3 and at random step (less than 250), i have an error : « InternalError : failed to call ThenRnnBackward with model config ... »

Today i downgraded tensorflow to version 2.1 and run the training loop and i am actually at step 1500 without the issue

I also tried to downgrade at version 2.2 but the error still occurs

**Describe the expected behavior**

**Standalone code to reproduce the issue**

Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

I can’t share the whole code because it’s too big (part of a big project) but here is a small description : 
- Model is tacotron-2 implementation inspired from pytorch NVIDIA so it has 1 BidirectionalLSTM in the encoder and 2 LSTMCell in the decoder
- I use K.rnn to use a custom decoder step
- The error occurs at the tape.gradient() call
- I use custom training loop where i split the whole input frames into sub frames (because memory issue) so for a mel-spec of 400 frames, i make 8 optimization step of 50 frames (with passing the last LSTM-states to the next 50-frames block optimization step (it’s really strange that my 6Gb memory only accepts 50 frames with batch_size 16 (75 frames run OOM))

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

The model is actually training but i will share my training loop code and anything other you want when it’s finished... i can also check my CuDnn version but i’m pretty sure it’s 7.5

**Comment by amahendrakar** [comment]
> I can’t share the whole code because it’s too big (part of a big project) but here is a small description 

@Ananas120,
Without a reproducible code it is hard for us to pinpoint the issue. Could you please remove the dependencies and provide a simplest possible repro, so that it will be easier for us to debug the error. Thanks!

**Comment by Ananas120** [comment]
Yes i will post my model architecture and training loop in 3 or 4 days... do you need also the dataset processing or just shapes / dtype to make fake inputs are ok (the processing is a custom mel spectrogram fn and tf.data.Dataset mapping) ?

**Comment by amahendrakar** [comment]
@Ananas120,
The original data and pre-processing steps would not be necessary. Fake inputs which can reproduce the error would be fine. Thanks!

**Comment by Ananas120** [comment]
Ok nice ! i will share my code tomorrow morning on my github (i’ll post the link here) (the architecture and the training step) (the training loop is just a for loop on the dataset and call to callbacks so not important)

**Comment by Ananas120** [comment]
@amahendrakar  here is the link of the repo : https://github.com/Ananas120/Tacotron-2-tf2.0

I don’t test the training code (i just copy-paste the original one and removed the calls to ‘self.xxx’ by removing the self and passing the variable as argument) so i hope it works (i also added fake inputs to show the dtype and approximate shape)

The model is a C/C of the original i used (and had error) so normally it can be initialized without issue !

**Comment by amahendrakar** [comment]
@Ananas120,
On running the code I am facing an error stating `TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/cdb819e8cd25e8d81953837dcb4a69cb/42412.ipynb).

Could you please provide a minimal reproducible code, so that we can look into this? Alternatively, you can run the code on Google Colab and share the notebook with us. Thanks!

**Comment by Ananas120** [comment]
Sorry for the time, my vakanties will nearly ends so i need to finish my project so i train with the version 2.1 for now, I will retest with version 2.3 and share more code if it crashes in 1 or 2 weeks (you can close this issue if you want, i can re-open one if needed)

**Comment by Ananas120** [comment]
@amahendrakar i updated my github by cleaning the code and replacing my SV2TTS tacotron by the original tacotron
Also i trained it and also have the error after around 300 steps

I also have a strange warning when running the model saying that the input type of my BiLSTM-forward node isn’t of the right type but the error is only shown on the command line of jupyter (and not in the notebook itself)

Hope my code will work !

**Comment by amahendrakar** [comment]
@Ananas120,
Thank you for the update. 

On running the `train.py` file, I am facing an error stating `TypeError: __init__() missing 1 required positional argument: 'vocab_size'`.  Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/99a34554cbc7c1deff0b94c987a9cca5/42412.ipynb#scrollTo=IeM-n0BPBC2y). Thanks!

**Comment by Ananas120** [comment]
@amahendrakar  i updated your colab code by C/C the train.py and correct bugs (so now it runs correctly as you can see)
Error occurs around step 200-400 so i think if you can run more than 1k steps without the error, it should be perfect but it never happens for me... 
Also i think with a better GPU than mine you can increase the max_train_step (for me 50 is the max for non-graph mode and 25 on graph mode) with batch_size 48 (non-graph) and 64 (graph) 

Note : « graph mode » means only the `call()`method is in tf.function and not the optimization step function (when i put the optimize_step in graph i’m not sure but i think it also raises an error)

**Comment by amahendrakar** [comment]
> @amahendrakar i updated your colab code by C/C the train.py and correct bugs (so now it runs correctly as you can see)

@Ananas120,
Seems like the changes have not been saved. Could you please make the same changes in your GitHub repo. Alternatively you can run the code on [Google Colab](https://colab.research.google.com/) and share the notebook with us. Thanks!

**Comment by Ananas120** [comment]
Ah zut... i will do this today and say you when it’s done

**Comment by Ananas120** [comment]
@amahendrakar  i corrected my github and today i had the same issue with a simple CNN model ended by a LSTM layer (in tf 2.3.1) so i suppose the LSTM layer has an issue in version > 2.1...

**Comment by amahendrakar** [comment]
@Ananas120,
Thank you for the update. I was able to run the code without any issues on TF v2.3, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/c77e0956a871f2c57e9d6fba5bb7ba12/42412.ipynb). 

Please try running the code in a virtual environment and check if you are still facing the same issue. Thanks!

**Comment by Ananas120** [comment]
Ok thank’s but in your gist i see you ran on 1 step and for me the error occurs only at step 300-400... so the code runs well for me too but not for a real training ^^’

**Comment by amahendrakar** [comment]
@Ananas120,
Could you please point out the required changes to be made to run the code for 400 steps? Thanks!

**Comment by Ananas120** [comment]
Yes you should just run the « train_step(...) » function for n times (like à simple for _ in range(500): loss = train_step(...) »

**Comment by amahendrakar** [comment]
@Ananas120,
I did not face any errors even on running the `train_step` function for 500 times. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/c30551922fa8edda8bd2d001532da5d4/42412.ipynb#scrollTo=IfpfhWMBW09b). Thanks!

**Comment by Ananas120** [comment]
Ok thank you but then i don’t know why the error occurs for me... maybe because i run on Windows or i used an older version of jupyterlab... i updated it and will see if it happens
