### ISSUE TITLE
Tensorflow 2.3 modules not found

### ISSUE THREAD

**Issue by intelligentgoldfish** [tensorflow/tensorflow#42418]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Windows 10
- TensorFlow installed from conda
- TensorFlow version: 2.3
- Python version: 3.7
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the problem**

When installing Tensorflow via conda to my machine, Keras fails to load models properly, returning KeyError 0.  Conda installs Tensorflow 2.1, and it was recommended that I upgrade to the lastest tf/keras versions, which I did via pip:
`pip install tensorflow --upgrade`

However, this then produced the following errors when I attempted to run a file which imported tensorflow:
`Traceback (most recent call last):
  File "C:\Users\Thomas DeWitt\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot_2.py", line 12, in <module>
    import tensorflow as tf
  File "C:\Users\Thomas DeWitt\Anaconda3\envs\tf\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Thomas DeWitt\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\Thomas DeWitt\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\Thomas DeWitt\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Thomas DeWitt\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Thomas DeWitt\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.`

I've uninstalled Tensorflow and reinstalled it twice, once with pip and once with conda.  The pip install returns a warning about the assorted .exe files not being associated with PATH:
`WARNING: The scripts estimator_ckpt_converter.exe, saved_model_cli.exe, tensorboard.exe, tf_upgrade_v2.exe, tflite_convert.exe, toco.exe and toco_from_protos.exe are installed in 'C:\Users\Thomas DeWitt\AppData\Roaming\Python\Python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.`

The conda install works, but again fails to load models with tf.keras.models.load_model('model')

I'm not sure if this is a problem on my machine or with the latest Tensorflow release, as I usually operate in Colab and I've never needed to run Tensorflow locally before.

**Comment by Srikeshram** [comment]
Try Installing CuDnn,Which is essential to run Tensorflow to run in  the local machine

**Comment by Saduf2019** [comment]
@intelligentgoldfish 
Please refer to these links with same error and let us know:
[link](https://stackoverflow.com/questions/59822162/error-installing-tensorflow-with-pip-install) [link1](https://superuser.com/questions/1372793/the-script-is-installed-in-directory-which-is-not-path)

**Comment by intelligentgoldfish** [comment]
I don't have admin access on my machine, so I'm not able to simply add the variables to the path.

**Comment by Saduf2019** [comment]
@intelligentgoldfish 
For the issue to be resolved you will have to make the changes as suggested.
