### ISSUE TITLE
fp16/bf16 is much slower than fp32

### ISSUE THREAD

**Issue by zhao1157** [tensorflow/tensorflow#42422]
I tested `fp16` and `bf16` training performance on `Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz` CPU, which I guess does not support `fp16` or `bf16` computation, however, the training went through without throwing me any errors, but the performance was much worse than `fp32`. I was wondering how TensorFlow handles such case, i.e. running `fp16` or `bf16` on a `Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz` CPU.

**Comment by amahendrakar** [comment]
@zhao1157,
Could you please provide the code you have used or the commands you have run to test the performance and also the TensorFlow version you are using? Thanks!

**Comment by zhao1157** [comment]
Tf version tested: 1.14.0 and 2.2.0

Code used: [https://github.com/tensorflow/benchmarks/tree/master/scripts/tf_cnn_benchmarks](url)

Command for testing `fp32`: `python tf_cnn_benchmarks.py --input_preprocessor=default --optimizer=sgd --batch_size=50 --data_name=imagenet --model=resnet50 --variable_update=replicated --device=cpu --data_format=NHWC` 

Command for testing `fp16`: `python tf_cnn_benchmarks.py --input_preprocessor=default --optimizer=sgd --batch_size=50 --data_name=imagenet --model=resnet50 --variable_update=replicated --device=cpu --data_format=NHWC --fp16_loss_scale=500 --use_fp16=True --fp16_vars=False --fp16_inc_loss_scale_every_n=10 --fp16_enable_auto_loss_scale=True`

As for `bf16`, I used Intel's MLPerf v0.7 code [https://github.com/mlperf/training_results_v0.7/tree/master/Intel/benchmarks/resnet/1-node-8s-cpx-1-tensorflow/mlperf_resnet](url), and in `run_and_time.sh`, we have to set `use_bfloat16`  `True` or `False` to comparing the performance of `bf16` and `fp32`.

**Comment by ymodak** [comment]
Apologies for the delay in response but [readme](https://github.com/tensorflow/benchmarks/tree/master/scripts/tf_cnn_benchmarks#tf_cnn_benchmarks-high-performance-benchmarks) file helps explain the discrepancy.
`
tf_cnn_benchmarks is no longer maintained. Although it will run with TensorFlow 2, it was written and optimized for TensorFlow 1, and has not been maintained since TensorFlow 2 was released. 
`
