### ISSUE TITLE
Why is Graph 4x slower than Eager on large model? (TF 2.3.0)

### ISSUE THREAD

**Issue by OverLordGoldDragon** [tensorflow/tensorflow#42429]
[Follow-up](https://github.com/tensorflow/tensorflow/issues/39665). Plots are from running TF on Colab GPU.

What's the deal? Isn't Graph supposed to be speed-optimized?

<img src="https://user-images.githubusercontent.com/16495490/90391241-d8cca900-e09d-11ea-9233-ee9b8906105e.png" width="650">

<hr>

<details>
  <summary><b>Test code</b></summary>

```python
import numpy as np
import tensorflow as tf
import random
import matplotlib.pyplot as plt
from termcolor import cprint
from time import time

from tensorflow.keras.layers import Input, Dense, Conv1D
from tensorflow.keras.layers import Dropout, GlobalAveragePooling1D
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
import tensorflow.keras.backend as K

# tf.compat.v1.disable_eager_execution()

###############################################################################
def reset_seeds(reset_graph_with_backend=None, verbose=1):
    if reset_graph_with_backend is not None:
        K = reset_graph_with_backend
        K.clear_session()
        tf.compat.v1.reset_default_graph()
        if verbose:
            print("KERAS AND TENSORFLOW GRAPHS RESET")

    np.random.seed(1)
    random.seed(2)
    tf.compat.v1.set_random_seed(3)
    if verbose:
        print("RANDOM SEEDS RESET")

print("TF version: {}".format(tf.__version__))
reset_seeds()

def timeit(func, iterations, *args, _verbose=0, **kwargs):
    times = []
    t0 = time()
    for _ in range(iterations):
        t1 = time()
        func(*args, **kwargs)
        times.append(time() - t1)
        print(end='.'*int(_verbose))
    print("Time/iter: %.4f sec" % ((time() - t0) / iterations))
    plt.stem(times)
    plt.ylim(0, 15)

###############################################################################
def make_model_large(batch_shape):
    ipt   = Input(batch_shape=batch_shape)
    x     = Conv1D(64,  400, strides=4, padding='valid')(ipt)
    x     = Conv1D(128, 200, strides=1, padding='valid')(x)
    for _ in range(40):
        x = Conv1D(256,  12, strides=1, padding='same')(x)
    x     = Conv1D(512,  20, strides=2, padding='valid')(x)
    x     = Conv1D(1028, 10, strides=2, padding='valid')(x)
    x     = Conv1D(256,   1, strides=1, padding='valid')(x)
    x     = GlobalAveragePooling1D()(x)
    x     = Dense(256, activation='relu')(x)
    x     = Dropout(0.5)(x)
    x     = Dense(128, activation='relu')(x)
    x     = Dense(64,  activation='relu')(x)
    out   = Dense(1,   activation='sigmoid')(x)
    model = Model(ipt, out)
    model.compile(Adam(lr=1e-4), 'binary_crossentropy')
    return model

def make_data(batch_shape):
    return np.random.randn(*batch_shape), \
           np.random.randint(0, 2, (batch_shape[0], 1))

def test_all():
    for model_fn, model_name, iters in zip(make_model_fns, model_names,
                                           iterations):
        for batch_shape, shape_name in zip(batch_shapes, shape_names):
            reset_seeds(reset_graph_with_backend=K)
            data = make_data(batch_shape)
            model = model_fn(batch_shape)

            model.train_on_batch(*data)
            timeit(model.train_on_batch, iters, *data, _verbose=1)
            
            cprint(">> {}, {} done <<\n".format(model_name, shape_name), 'blue')
            del model
###############################################################################

batch_shape_large  = (32, 14000, 30)
batch_shape = batch_shape_large
model_fn = make_model_large

batch_shapes = batch_shape_large,
make_model_fns = make_model_large,
iterations = [200]
shape_names = ["Large data"]
model_names = ["Large model"]

test_all()
```

</details>

**Comment by ravikyram** [comment]
@OverLordGoldDragon 

I have tried in colab  with TF-GPU 2.3.0.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/b44ded3ff86c82ae9e6b308b4f1cfe0e/untitled258.ipynb).IYou are also seeing the same behavior?.Thanks!

**Comment by OverLordGoldDragon** [comment]
@ravikyram No, I'm not - and this time, the results are worse than in any prior test:

<img src="https://user-images.githubusercontent.com/16495490/90526186-22da8b00-e181-11ea-9817-572d0ac33aae.png" width="650">

The only culprit to my mind is Colab's GPU, which is known to change between sessions. Can you run again, and check GPU? This run's:

```
GPU: Tesla K80
Gen RAM Free: 11.7 GB  | Proc size: 2.1 GB
GPU RAM Free: 2995MB | Used: 8446MB | Util  74% | Total 11441MB
```

<details>
    <summary><b>GPU info code</b></summary>

```python
!ln -sf /opt/bin/nvidia-smi /usr/bin/nvidia-smi
!pip install gputil
!pip install psutil
!pip install humanize

import psutil
import humanize
import os
import GPUtil as GPU

GPUs = GPU.getGPUs()
gpu = GPUs[0]

process = psutil.Process(os.getpid())
print("GPU:", gpu.name)
print("Gen RAM Free: " + humanize.naturalsize( psutil.virtual_memory().available ), " | Proc size: " + humanize.naturalsize( process.memory_info().rss))
print("GPU RAM Free: {0:.0f}MB | Used: {1:.0f}MB | Util {2:3.0f}% | Total {3:.0f}MB".format(gpu.memoryFree, gpu.memoryUsed, gpu.memoryUtil*100, gpu.memoryTotal))
```

</details>

**Comment by tomerk** [comment]
So a number of comments looking at this colab:

1. compat.v1.disable_eager_execution is not supposed to put you in a performance-optimized graph. It puts you in a legacy graph compatibility mode that is meant to keep behavior the same as the equivalent APIs in TF 1.x. Performance in compat.v1 graphs takes a backseat to general eager performance.

The appropriate way to use performance-optimized-graphs in TF2 is with `tf.function`: https://www.tensorflow.org/guide/function

2. Though not under TF 1.x, `model.train_on_batch` mainly exists for backwards compatibility reason. It is not how we recommend you train your models.
We recommend using `model(x, training=True/False)` directly, using `model.fit/evaluate`, using `model.train_step`, etc. See the Keras guide to customizing `fit` as well: https://keras.io/guides/customizing_what_happens_in_fit/

For those same reasons, `model.train_on_batch` is generally much less performant than any of the above alternatives.

Note that we will only automatically `tf.function` your training process if you use `model.fit/evaluate`. If you use the model call or train_step directly you'll have to apply your own `tf.function`s as you deem fit.

3. While we accept numpy data as input, it's not the most performant way to feed data to your model (as we currently have to do copies to convert it to tensors). For maximum performance you should use `tf.data`. If you need to use numpy-like operations w/ tf or tf.data you can check out the recently-announced tf-numpy (https://www.tensorflow.org/guide/tf_numpy). We do have some tentative plans on the roadmap to make large numpy inputs to Keras models more performant.

We're also planning a "performance guide" for Keras, which should cover all of the above as well as some other things users might not be aware of.

Please let us know if you have any questions!

**Comment by OverLordGoldDragon** [comment]
@tomerk Thanks for the insight, had no clue `tf.compat.v1` wasn't the supposed way to Graph. I'd definitely recommend an explicit Eager vs. Graph guide.

However, I commented the line, and switched to `.fit`, and `@tf.function def return model.train_step`; they run 13% and 7%, respectively, slower than `.train_on_batch` with `tf.compat.v1.disable_eager_execution()`, still on numpy data. The idea is to have new numpy data input at each iteration, so whether we handle it before passing in or TF handles it shouldn't make much a difference - and our reference is relative to TF1.x, still with numpy inputs. (But yes, for _fixed_ data, one-time conversion is faster.)

I also confirmed the GPU difference; Tesla T4 runs twice as fast in Graph, averaging ~4 sec/iter vs. ~8 sec with K80, while not making much a difference with Eager. I wonder if same will hold with `model.fit`.

**Comment by OverLordGoldDragon** [comment]
I'll test again later on K80 and see if it makes a difference; if Graph is 8 sec again with all three modes while Eager is 4 sec, there's still some explaining to do. And to clarify, this is the Graph function I use:

```python
@tf.function
def step(*args, **kwargs):
    return model.train_step(*args, **kwargs)
```

**Comment by OverLordGoldDragon** [comment]
@tomerk Tested with `tf.function` as described; no difference. _However_; I once again was unable to reproduce the 2 sec/iter for Eager, implying only one thing: GPUs were unluckily swapped in my original test. This makes far more sense.

My question persists, however; how is it that "optimized graph" isn't notably faster than Eager (using prev comment's function)?
