### ISSUE TITLE
`tf.data.experimental.sample_from_datasets` imports all the dataset into GPU memory

### ISSUE THREAD

**Issue by Zhao-Kuangshi** [tensorflow/tensorflow#42423]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: Yes
-   **OS Platform and Distribution**: Ubuntu 18.04.5 LTS 
-   **TensorFlow installed from (source or binary)**: binary
-   **TensorFlow version (use command below)**: 2.3.0
-   **Python version**: 3.7.3
-   **CUDA/cuDNN version**: CUDA 10.1 & cuDNN 7.6.5
-   **GPU model and memory**: NVIDIA RTX 2070 8GB (Single GPU)

### Describe the problem
I was using `tf.data` API to build an input pipeline for my inbalanced dataset. So I used `tf.data.experimental.sample_from_datasets` function as [the tutorial](https://tensorflow.google.cn/tutorials/structured_data/imbalanced_data?hl=en#using_tfdata) recommended. 

My dataset's shape is shown below:
```python
>>> print(x.shape)
(63, 1330, 3001, 8)
>>> print(y.shape)
(63, 5)
```

Before I use `tf.data.experimental.sample_from_datasets` function. My system memory usage was approximately 9 GB, and **GPU Memory Usage** only 15 MiB /  7949MiB . Which I had did before `sample_from_datasets` was:
```python
import tensorflow as tf
import numpy as np
from sklearn.model_selection import ShuffleSplit

# load dataset from files
x = np.load('result/experiment_2_0816/x.npy')
y = np.load('result/experiment_2_0816/y.npy')

# there is five classes
A = []
B = []
C = []
D = []
E = []

# distribute dataset by labels
# A,B,C,D,E are just indices of the data (not slices)
for i in range(63):
    if y[i].argmax() == 0:
        A.append(i)
    elif y[i].argmax() == 1:
        B.append(i)
    elif y[i].argmax() == 2:
        C.append(i)
    elif y[i].argmax() == 3:
        D.append(i)
    elif y[i].argmax() == 4:
        E.append(i) 

# split validation set
A = next(ShuffleSplit(n_splits=1, test_size=0.1).split(A))
B = next(ShuffleSplit(n_splits=1, test_size=0.1).split(B))
C = next(ShuffleSplit(n_splits=1, test_size=0.1).split(C))
D = next(ShuffleSplit(n_splits=1, test_size=0.1).split(D))
E = next(ShuffleSplit(n_splits=1, test_size=0.1).split(E))

def make_dataset(features, labels):
    ds = tf.data.Dataset.from_tensor_slices((features, labels)).cache()
    ds = ds.shuffle(100).repeat()
    return ds

# using `tf.data.Dataset.from_tensor_slices` function to build pipelines
A_train = make_dataset(x[A[0]], y[A[0]])
B_train = make_dataset(x[B[0]], y[B[0]])
C_train = make_dataset(x[C[0]], y[C[0]])
D_train = make_dataset(x[D[0]], y[D[0]])
E_train = make_dataset(x[E[0]], y[E[0]])
A_val = make_dataset(x[A[1]], y[A[1]])
B_val = make_dataset(x[B[1]], y[B[1]])
C_val = make_dataset(x[C[1]], y[C[1]])
D_val = make_dataset(x[D[1]], y[D[1]])
E_val = make_dataset(x[E[1]], y[E[1]])

# collect garbage
del x,y
import gc
gc.collect()
```

However, once we execute
```python
resampled_train = tf.data.experimental.sample_from_datasets([A_train, B_train, C_train, D_train, E_train], weights=[0.84, 3.15, 0.9, 0.54782609, 1.8])
resampled_val = tf.data.experimental.sample_from_datasets([A_val, B_val, C_val, D_val, E_val], weights=[0.84, 3.15, 0.9, 0.54782609, 1.8])
```
the **GPU memory usage** suddenly rise to **7491MiB /  7949MiB **. The function loaded all the data into GPU memory, which was unnecessary and waste of GPU resources. Here we were doing nothing about Neural Network Models. The model hasn't been created at all.

So I wonder whether it is a bug or necessary step to load data into GPU. Or I've done some steps wrong?

**Comment by rmothukuru** [comment]
@Zhao-Kuangshi,
When trying to reproduce the error, I encountered the error, 

`FileNotFoundError: [Errno 2] No such file or directory: 'result/experiment_2_0816/x.npy'` . Can you please share the files, `x.npy` and `y.npy`. Thanks!

**Comment by Zhao-Kuangshi** [comment]
> 
> 
> @Zhao-Kuangshi,
> When trying to reproduce your issue, I encountered the error,
> 
> `FileNotFoundError: [Errno 2] No such file or directory: 'result/experiment_2_0816/x.npy'` . Can you please share the files, `x.npy` and `y.npy`. Thanks!

Thanks for your prompt reply. Github Issues cannot seem to upload files. And my `x.npy` is really a huge file (which is 7.5G). So I recommand you to use code below:

```python
x = np.random.rand(63, 1330, 3001, 8)
y = np.random.rand(63,5)
```

to replace `np.load()` lines in my original code.

Before doing that, you should ensure you've got enough computer memory because the matrix with the shape `(63, 1330, 3001, 8)` is really large. You can also use a smaller matrix to reproduce my code, it will not change the essence.

**Comment by jvishnuvardhan** [comment]
@Zhao-Kuangshi I tried running initial part of your code without tf.data, it is still crashing without the data pipeline. 

Please verify it. [Here](https://colab.research.google.com/gist/jvishnuvardhan/7d1732bcb3284a6c4a1fa97e01130c31/untitled10.ipynb) is the gist for your reference. Thanks!

**Comment by Zhao-Kuangshi** [comment]
> 
> 
> @Zhao-Kuangshi I tried running initial part of your code without tf.data, it is still crashing without the data pipeline.
> 
> Please verify it. [Here](https://colab.research.google.com/gist/jvishnuvardhan/7d1732bcb3284a6c4a1fa97e01130c31/untitled10.ipynb) is the gist for your reference. Thanks!

I tried it on Colab. It crashed because of OOM. Because the array with shape `(63, 1330, 3001, 8)` was really large. My workstation has 32GB of RAM and 8GB of GPU Memory. So `(63, 1330, 3001, 8)` numpy,array will not cause crashing. Due to smaller memory limitation on Colab, a smaller data such as `x = np.random.rand(63, 1330, 3001)` is also representative, as I have mentioned before. 

In most of user cases, **a user usually has larger RAM than GPU Memory**. When facing big data, a user will try using pipelines or generators or cache such as `tf.data` to save GPU memory (and avoid program crashing out). While other functions in `tf.data` module almost did not increase memory usage, `sample_from_datasets` did consume GPU memory. So **the point is the change of  GPU memory usage after using `sample_from_datasets`**.
