### ISSUE TITLE
Error in Validation split percentage - Image Classification tutorial

### ISSUE THREAD

**Issue by roca77** [tensorflow/tensorflow#42420]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://github.com/tensorflow/docs/blob/master/site/en/tutorials/images/classification.ipynb

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/MyMethod

## Description of issue (what needs changing):
Under Load using Keras.preprocessing > Create Dataset, the percentage under training_ds for validation_split is set to 0.2. I believe is supposed to be 0.8.

### Clear description

When you used 0.8 on the number of images in the directory, it will result to 2936, but 0.2 is way smaller.

**Comment by Saduf2019** [comment]
@roca77 
Could you please give in more details or an example of the issue faced.

**Comment by roca77** [comment]
@Saduf2019 @jvishnuvardhan The error is in the documentation itself; In both tutorials (on github and on tensorflow's website), there is an error on the percentage when the program splits the data into training dataset and validation dataset. I believe the correct percentage is 0.8 for training and 0.2 for validation.

**Comment by jvishnuvardhan** [comment]
@roca77 Thanks for raising the issue. 
The percentage `0.2` is correct. The split is percentage of data reserved for validation which is `0.2`. You can check the documentation [here](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image_dataset_from_directory)

The documentation says that

> validation_split | Optional float between 0 and 1, fraction of data to reserve for validation.
> -- | --

Please verify once and close the issue. Thanks!

**Comment by roca77** [comment]
Closing; Thanks for checking
