### ISSUE TITLE
```tf.stack``` returns different shapes when run in eager and graph mode

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/tensorflow#42424]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):2.3
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
```tf.stack(list(np.ones([2,0,3]))).shape```
returns EagerTensor with shape [2,0]
**Describe the expected behavior**
```tf.stack(list(np.ones([2,0,3]))).shape```
returns EagerTensor with shape [2,0,3] which same as graph mode

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
Eager mode:
``` python
import tensorflow as tf
print(tf.stack(list(np.ones([2,0,3]))).shape)
tf.compat.v1.disable_eager_execution()
print(tf.stack(list(np.ones([2,0,3]))).shape)
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@fsx950223 
I ran your code on colab tf 2.3 and did not face the issue mentioned, please have a look at the [gist here](https://colab.research.google.com/gist/Saduf2019/80b8950b2b559c2a64057a6bd8f3c3a2/untitled375.ipynb).

**Comment by fsx950223** [comment]
> @fsx950223
> I ran your code on colab tf 2.3 and did not face the issue mentioned, please have a look at the [gist here](https://colab.research.google.com/gist/Saduf2019/80b8950b2b559c2a64057a6bd8f3c3a2/untitled375.ipynb).

You should run it in eager mode and graph mode

**Comment by fsx950223** [comment]
You could test it via follow example:
```python
import tensorflow as tf
import numpy as np

print(tf.stack(list(np.ones([2,0,3]))).shape)
@tf.function
def test():
  print(tf.stack(list(np.ones([2,0,3]))).shape)

test()
```

**Comment by yongtang** [comment]
The issue is really due to `tf.convert_to_tensor` which does not handling shape correctly:
```
% python3
Python 3.7.3 (default, Jun  2 2020, 19:48:59) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import numpy as np
>>> x = list(np.ones([2,0,3]))
>>> x
[array([], shape=(0, 3), dtype=float64), array([], shape=(0, 3), dtype=float64)]
>>> y = tf.convert_to_tensor(x)
>>> y
<tf.Tensor: shape=(2, 0), dtype=float32, numpy=array([], shape=(2, 0), dtype=float32)>
```

It looks like `tf.convert_to_tensor()` in eager mode (or more specifically `InitEagerTensor`), dropped the dimension of `3`.

**Comment by aavishkarmishra** [comment]
I would like to work on this issue. How can I remove this error?

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in 2.6.0-dev20210528,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/ee363c69aca3ac5bcd18e73007c2bd0b/untitled61.ipynb#scrollTo=LQl8zZLibQ4m)..Thanks !

**Comment by mohantym** [comment]
Hi @fsx950223 !  This issue getting resolved with tf.config.run_functions_eagerly(False) instead of tf.compat.v1.disable_eager_execution(). Attaching [gist](https://colab.sandbox.google.com/gist/mohantym/91a282de6964cd1fde9c83951e5cf3bd/git_42424.ipynb) for reference. Thank you!

**Comment by mohantym** [comment]
@fsx950223 ,Sorry! Can you please check this updated [gist](https://colab.sandbox.google.com/gist/mohantym/649e6467c6caa1b404ac258eae79a378/git_42424.ipynb) again? We have to disable eager execution at beginning of code right?

**Comment by sushreebarsa** [comment]
@fsx950223 I was able to replicate this issue using tf-nightly 2.10.0.dev2022072608, please find the [gist](https://colab.sandbox.google.com/gist/sushreebarsa/33f354d67395585dc88ee91a0504369e/git_42424.ipynb) here. Thank you!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
