### ISSUE TITLE
Full integer Quantization of SSD-Mobilenet V2 doesn't work

### ISSUE THREAD

**Issue by dtch1997** [tensorflow/tensorflow#42426]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary):  binary
- Tensorflow version (commit SHA if source): '2.4.0-dev20200805'
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Arm Mbed OS

**Describe the problem**

I need to convert a SSD-Mobilenet V2 model for an 8-bit microcontroller which runs Mbed OS and would like to use optimized CMSIS-NN kernels. Model was trained and exported with [Tensorflow Object Detection API](https://github.com/tensorflow/models/tree/master/research/object_detection). 

However, the saved and exported model cannot be converted to TfLite. Truncated error message is as follows: 
```
Exception: <unknown>:0: error: loc(callsite(callsite("Postprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/SortByField_1/Size@__inference___call___8168" at "StatefulPartitionedCall@__inference_signature_wrapper_9547") at "StatefulPartitionedCall")): 'tf.Size' op is neither a custom op nor a flex op
```

**Please provide the exact sequence of commands/steps when you ran into the problem**

Code to replicate the problem can be found here: 
https://colab.research.google.com/drive/1vR6L0uUQQb3PTL8Ze0keIVGjSLusa_WI?usp=sharing

**Comment by dtch1997** [comment]
@ymodak please let me know if there's anything i can do to help with the resolution of this issue.

**Comment by ymodak** [comment]
Thanks for the issue. I cannot view the attached colab can you please change its permissions visible to public?

**Comment by dtch1997** [comment]
@ymodak thanks for the quick response. I have updated the sharing link.

**Comment by srjoglekar246** [comment]
Please look at [this guide](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md) for TFLite inference. 

For post-training quant, Be sure to use a
[representative dataset](https://www.tensorflow.org/lite/performance/post_training_quantization#full_integer_quantization)
and set the following options on the converter:

```
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8,
                                       tf.lite.OpsSet.TFLITE_BUILTINS]
converter.representative_dataset = <...>
```

**Comment by ChowderII** [comment]
Can we reopen this issue? It doesn't work for me either. Any type of quantization I have ever tried fails for ssd_mobilenet_v2. I have the same error but mine is: ```failed while converting 'main'```. Please help!

**Comment by srjoglekar246** [comment]
@ChowderII Where are you getting the model from? Did you follow [these instructions](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md)? 

if yes, please post your code for post-training quantization if you are trying that

**Comment by ChowderII** [comment]
@srjoglekar246 
hm, I may have forgotten to export to TFlite first. I thought only the conversion was necessary. Let me do that first and I'll report back
Thanks!

**Comment by ChowderII** [comment]
@srjoglekar246  So I have tried it and I receive the following errors:
```Traceback (most recent call last):
  File "export_tflite_graph_tf2.py", line 126, in <module>
    app.run(main)
  File "/home/brackman/anaconda3/lib/python3.8/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/brackman/anaconda3/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "export_tflite_graph_tf2.py", line 118, in main
    export_tflite_graph_lib_tf2.export_tflite_model(pipeline_config,
  File "/home/brackman/anaconda3/lib/python3.8/site-packages/object_detection/export_tflite_graph_lib_tf2.py", line 245, in export_tflite_model
    concrete_function = detection_module.inference_fn.get_concrete_function(
  File "/home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1299, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1205, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 725, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2976, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3371, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3206, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3897, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /home/brackman/anaconda3/lib/python3.8/site-packages/object_detection/export_tflite_graph_lib_tf2.py:169 inference_fn  *
        predicted_tensors = self._model.predict(image, true_image_shapes=None)
    /home/brackman/anaconda3/lib/python3.8/site-packages/object_detection/meta_architectures/ssd_meta_arch.py:591 predict  *
        predictor_results_dict = self._box_predictor(feature_maps)
    /home/brackman/anaconda3/lib/python3.8/site-packages/object_detection/core/box_predictor.py:202 call  *
        return self._predict(image_features, **kwargs)
    /home/brackman/anaconda3/lib/python3.8/site-packages/object_detection/predictors/convolutional_keras_box_predictor.py:204 _predict  *
        prediction = head_obj(net)
    /home/brackman/anaconda3/lib/python3.8/site-packages/object_detection/predictors/heads/head.py:69 call  *
        return self._predict(features)
    /home/brackman/anaconda3/lib/python3.8/site-packages/object_detection/predictors/heads/keras_class_head.py:143 _predict  *
        class_predictions_with_background = layer(
    /home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:999 __call__  **
        self._maybe_build(inputs)
    /home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:2670 _maybe_build
        self.build(input_shapes)  # pylint:disable=not-callable
    /home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/layers/convolutional.py:198 build
        self.kernel = self.add_weight(
    /home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:614 add_weight
        variable = self._add_variable_with_custom_getter(
    /home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py:805 _add_variable_with_custom_getter
        new_variable = getter(
    /home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer_utils.py:130 make_variable
        return tf_variables.VariableV1(
    /home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/variables.py:260 __call__
        return cls._variable_v1_call(*args, **kwargs)
    /home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/variables.py:206 _variable_v1_call
        return previous_getter(
    /home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/variables.py:67 getter
        return captured_getter(captured_previous, **kwargs)
    /home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py:712 variable_capturing_scope
        v = UnliftedInitializerVariable(
    /home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/variables.py:264 __call__
        return super(VariableMetaclass, cls).__call__(*args, **kwargs)
    /home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py:227 __init__
        initial_value = initial_value()
    /home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py:81 __call__
        return CheckpointInitialValue(
    /home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py:117 __init__
        self.wrapped_value.set_shape(shape)
    /home/brackman/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:1215 set_shape
        raise ValueError(

    ValueError: Tensor's shape (1, 1, 576, 273) is not compatible with supplied shape (1, 1, 576, 9)
```

What is that tensor? Right now, I tried to download the ssd_mobilenet_v2 from the model zoo and directly convert it (I just want to know it's possible before training). I unfortunately have no idea what that error means. Maybe I goofed up in the pipeline?

**Comment by srjoglekar246** [comment]
Look at the last section in [this colab](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb) for an example of how to export & convert to TFLite.

**Comment by ChowderII** [comment]
They only mention how to convert it with 
```bash
python models/research/object_detection/export_tflite_graph_tf2.py \
  --pipeline_config_path output/pipeline.config \
  --trained_checkpoint_dir output/checkpoint \
  --output_directory tflite
```
Which is what I am doing. Maybe I should create a separate issue?

**Comment by srjoglekar246** [comment]
Which model areyou downloading? Can you send me the name of model you downloading from the [TF2 Zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md)?

Also, note that you need the latest TF nightly for this to work.

If this still doesn't work for you, can you post your exact commands for me to take a look?

**Comment by ChowderII** [comment]
I tried using every SSD_mobilenet_v2. I never was able to do any type of quantization on any of them. I am also running tf-nightly
I tried the `graph_rewriter` but the model would never begin training.
Currently I was able to export SSD MobileNet V2 FPNLite 320x320 using tflite so I am currently training it. I hope it will survive convertion.
As for the command, I am using : I am training it using model_main_tf2.py
Then I try to export it using export_tflite_graph_tf2.py
After that, I try this code
```python
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
def representative_dataset_gen():
  for _ in range(num_calibration_steps):
    # Get sample input data as a numpy array in a method of your choosing.
    yield [input]
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8
tflite_quant_model = converter.convert()
```
Given from the [Post-training quantization](https://www.tensorflow.org/lite/performance/post_training_quantization) guide from Tensorflow.

I feel like I am doing something fundamentally wrong but I've poking at it for well over a month now.
I need to have it run on INT8 because I am trying to have the model run on a custom chip.

**Comment by srjoglekar246** [comment]
You need to add `tf.lite.OpsSet.TFLITE_BUILTINS` to `tf.lite.OpsSet.TFLITE_BUILTINS_INT8`

Also, you need to implement representative_dataset_gen to produce inputs in the correct format. Its usually something like this:

```
def representative_dataset_gen():
  for i in range(100):
    image = tf.io.read_file(os.path.join(data_dir, image_files[i % NUM_FILES]))
    image = tf.compat.v1.image.decode_jpeg(image)
    image = preprocess(image)

    yield [image]
```

You can see an implementation of `preprocess` [here](https://github.com/tensorflow/models/blob/master/research/slim/preprocessing/inception_preprocessing.py#L258).

**Comment by Petros626** [comment]
> Please look at [this guide](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md) for TFLite inference.
> 
> For post-training quant, Be sure to use a [representative dataset](https://www.tensorflow.org/lite/performance/post_training_quantization#full_integer_quantization) and set the following options on the converter:
> 
> ```
> converter.optimizations = [tf.lite.Optimize.DEFAULT]
> converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8,
>                                        tf.lite.OpsSet.TFLITE_BUILTINS]
> converter.representative_dataset = <...>
> ```

not sure if you can use this in the TF OD API, all scripts are given it's note like working in an IDE..
