### ISSUE TITLE
Keras `Layer.call` args signature inconsistent with actual code

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorflow#42435]
## URL(s) with the issue:

<https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer#call>

### Clear description

The `call` method is listed as `call(inputs, **kwargs)`, and documents
that `inputs` is an “Input tensor, or list/tuple of input tensors.” But
actual code usage shows that `call` may accept multiple positional
arguments depending on the actual layer implementation. For instance:

  - <https://www.tensorflow.org/guide/keras/custom_layers_and_models#the_add_metric_method>
  - <https://github.com/tensorflow/models/blob/27bda1fc2d3557555ee8a48bbf1fb04f5c2f59e8/official/nlp/bert/bert_models.py#L68-L73>

This is confusing when reviewing code that defines a custom layer,
because the docs for `call` don’t reflect the actual usage.

### Submit a pull request?

> Are you planning to also submit a pull request to fix the issue?

No; I don’t have enough domain expertise to be confident about the
details.

**Comment by jvishnuvardhan** [comment]
@wchargin I think this was resolved with small update in the nightly docs. Please check [here](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer?version=nightly#call).

I am closing this issue as this was resolved. Please feel free to reopen if I am mistaken. Thanks!
