### ISSUE TITLE
No module named 'tensorflow.python.platform' 

### ISSUE THREAD

**Issue by skgreb** [tensorflow/tensorflow#42438]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary):binary
- TensorFlow version: Version 2.3
- Python version:3.8
- Installed using virtualenv? pip? conda?: in a conda eviroment with pip

I want to import tensorflow but everytime  I get 
tensorflow.python.platform import self_check
ModuleNotFoundError: No module named 'tensorflow.python.platform' 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I have already tried different tensorflow 2.x version and also completed uninstalled anconda and reinstall it. I also tried it in different enviorments. 
Also I had tensorflow running, but I update and also deleted some of the Microsoft Visual C++ Redistributable due to another problem. I did update and reinstalled all of the version but tensorflow is still not working.

Also I looked in the file and there is no python.plattform. Is there anyway to copy it or does anyone have some other solution?

**Comment by ravikyram** [comment]
@skgreb 

Please, follow the steps as mentioned [here.](https://www.tensorflow.org/install/source_windows).
Have you installed pip package?
Install the PIP package. You can either download the pre-built package, or build from source by following the instructions here: http://tensorflow.org/get_started/os_setup.md#create-pip

Does import tensorflow work in a Python shell?

If not, try reinstalling with `pip install --upgrade --force-reinstall <package>.`

Thanks!

**Comment by skgreb** [comment]
@ravikyram 
I tried all the setup and it finally worked by using python3.7 and also with python3.6 and with the command pip install tensorflow
Thank you for your help

**Comment by ravikyram** [comment]
@skgreb 

Please, close this thread if your issue was resolved.Thanks!
