### ISSUE TITLE
CTC ERROR: Saw a non-null label (index >= num_classes - 1) following a null label, batch: 0 num_classes: 12 labels: 2,10,5,1

### ISSUE THREAD

**Issue by LinJM** [tensorflow/tensorflow#4243]
I use TF rc 0.10 to run a project (https://github.com/synckey/tensorflow_lstm_ctc_ocr), but the program raise a error:
Invalid argument: Saw a non-null label (index >= num_classes - 1) following a null label, batch: 0 num_classes: 12 labels: 2,10,5,1

what does it mean?

**Comment by tatatodd** [comment]
@LinJM I see that you've already filed a similar issue under the synckey repo, which is great!

In general it's hard for us on tensorflow to provide support for third-party programs.  I do hope you get your issue figured out!

**Comment by liumanfei** [comment]
@LinJM Have you solve the problem? I'm in the same trouble~

**Comment by kei6** [comment]
Have anyone solved this problem??

**Comment by EngMohamedSaeed2001** [comment]
> Have you solved this problem?

Have you solved this problem?
