### ISSUE TITLE
sparkfun-tensorflow-codelab

### ISSUE THREAD

**Issue by taunoe** [tensorflow/tensorflow#42437]
Page: https://codelabs.developers.google.com/codelabs/sparkfun-tensorflow/#3
Broken commands:

is: make -f tensorflow/lite/experimental/micro/tools/make/Makefile TARGET=sparkfun_edge micro_speech_bin
should be: make -f tensorflow/lite/micro/tools/make/Makefile TARGET=sparkfun_edge micro_speech_bin

is: test -f tensorflow/lite/experimental/micro/tools/make/gen/sparkfun_edge_cortex-m4/bin/micro_speech.bin && echo "Binary was successfully created" || echo "Binary is missing"
should be: test -f tensorflow/lite/micro/tools/make/gen/sparkfun_edge_cortex-m4/bin/micro_speech.bin && echo "Binary was successfully created" || echo "Binary is missing"

And so on. All command where is lite/experimental/micro/ > lite/micro/

Where is /AmbiqSuite-Rel2.0.0/ > /AmbiqSuite-Rel2.2.0/

And also "Report a mistake" link is broken.

**Comment by amahendrakar** [comment]
@taunoe,
Could you please submit a new issue from [this link](https://github.com/googlecodelabs/tools/issues). So that we can track the issue there. Thanks!

**Comment by taunoe** [comment]
Ok , I will do that.

**Comment by taunoe** [comment]
I opened new issue there: https://github.com/googlecodelabs/tools/issues/450
