### ISSUE TITLE
Can I specify the version of NAPI ?

### ISSUE THREAD

**Issue by yangshengdong** [tensorflow/tensorflow#42444]
Can I specify the version of nAPI? In my environment, Node 10.15.x only supports NAPi-v4, but tensorFlow is actually NAPi-V6 (/node_modules/_@tensorflow_tfjs-node@2.1.0@@tensorflow/tfjs-node/lib/ NAPi-v6) after My deployment.

- tensorflowVersion：2.1.0

![image](https://user-images.githubusercontent.com/12997948/90458256-7e305d00-e130-11ea-8dee-98dccb97bd3f.png)

**Comment by amahendrakar** [comment]
@yangshengdong,
Issues related to TensorFlow.js are handled in the tensorflow/tfjs repo. Could you please submit a new issue from [this link](https://github.com/tensorflow/tfjs/issues/new) and fill in the template, so that we can track the issue there. Thanks!
