### ISSUE TITLE
Problem running tensorflow in Pycharm - ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by PODEE** [tensorflow/tensorflow#42440]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (Windows 10, 4GB Ram, 64-bit OS, x64 basedprocessor, Microsoft Visual C++ 2015-19 Re....installed):
- Mobile device (N/A):
- TensorFlow installed from (pip install tensorflow Pycharm Terminal):
- TensorFlow version: latest
- Python version: 3.7.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Installation seems to work fine (successfully installed absl.....). But when I run import tensorflow as tf

**Provide the exact sequence of commands / steps that you executed before running into the problem**
import tensorflow as tf

**Any other info / logs**
C:\Users\D'AVON\PycharmProjects\Test\venv\Scripts\python.exe C:/Users/D'AVON/PycharmProjects/Test/start.py
Traceback (most recent call last):
  File "C:\Users\D'AVON\PycharmProjects\Test\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/D'AVON/PycharmProjects/Test/start.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\D'AVON\PycharmProjects\Test\venv\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\D'AVON\PycharmProjects\Test\venv\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\D'AVON\PycharmProjects\Test\venv\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\D'AVON\PycharmProjects\Test\venv\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\D'AVON\PycharmProjects\Test\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\D'AVON\PycharmProjects\Test\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Process finished with exit code 1

**Comment by amahendrakar** [comment]
@PODEE,
You might be facing this issue because of the following reasons

- You are running 32-bit Python
- Your CPU does not support AVX instructions. Please share the make and model of your CPU, so that we can verify this.

Please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) and check if you have the correct dependencies installed.

Also, check these similar duplicate issues: #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204.

Thanks!

**Comment by PODEE** [comment]
![SystemModel](https://user-images.githubusercontent.com/17114177/90534326-9d86b480-e147-11ea-9b44-d52de1aec442.PNG)
System Model attached.
I installed 64-bit Python and I've gone through most of the duplicate issues but still not working

**Comment by amahendrakar** [comment]
@PODEE,
The [product specification](https://ark.intel.com/content/www/us/en/ark/products/82105/intel-pentium-processor-n3540-2m-cache-up-to-2-66-ghz.html) for your CPU doesn't mention AVX support.

In this case, you can either [build TensorFlow](https://www.tensorflow.org/install/source_windows) from source or use [Google Colab](https://colab.research.google.com/) as alternatives. Thanks!
