### ISSUE TITLE
Feature request: Docker image build (parameterized_docker_build.sh) lacks option for AVX2 optimization

### ISSUE THREAD

**Issue by hholst80** [tensorflow/tensorflow#4244]
As far as I can understand there is no way to tell the script `parameterized_docker_build.sh`  to build an AVX2 optimized docker image.

I see a note about Python 2 and 3 but nothing about AVX2:
```
# TODO(cais): Add support for TF_DOCKER_BUILD_PYTHON_VERSION (PYTHON2/PYTHON3)
```

**Comment by tatatodd** [comment]
@caisq can you comment on this?  Thanks!

**Comment by tatatodd** [comment]
BTW in the meantime, I wanted to mention that we're happy to accept pull requests.  :)
