### ISSUE TITLE
Setting multithreading  for tensorflowlite does not work！

### ISSUE THREAD

**Issue by hzq-zjm** [tensorflow/tensorflow#42445]
Hi guys,
I set up tensorflowlite for four threads,but compared with single thread, the time consumption has not decreased. by the way, i quantizate my models.
Hope to get your help,ths!

**Comment by ravikyram** [comment]
@hzq-zjm 

Can you please fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by hzq-zjm** [comment]
The relevant codes are as follows：   
   

 　private static Interpreter tflite_segm;
    private static Interpreter tflite_ocr ;
    /** Options for configuring the Interpreter. */
    private static Interpreter.Options tfliteOptions_seg = new Interpreter.Options();;
    private static Interpreter.Options tfliteOptions_ocr = new Interpreter.Options();

    /** The loaded TensorFlow Lite model. */
    private static MappedByteBuffer tfliteModel_segm;
    private static MappedByteBuffer tfliteModel_ocr;


            tfliteModel_segm=loadModelFile("frozen_qnt",activity);
            tfliteModel_ocr =loadModelFile("model_12y4r",activity);

            tfliteOptions_seg.setNumThreads(4);
            tfliteOptions_ocr.setNumThreads(4);

            tflite_segm = new Interpreter(tfliteModel_segm,tfliteOptions_seg);
            tflite_ocr = new Interpreter(tfliteModel_ocr,tfliteOptions_ocr);

**Comment by hzq-zjm** [comment]
Only the CPU is used to run the model.

**Comment by thaink** [comment]
@hzq-zjm What model are you running?
Currently, only Conv2D and DepthwiseConv has multithreaded kernels.
So you will only get benefit of they are significant in your model.

**Comment by hzq-zjm** [comment]
> @hzq-zjm What model are you running?
> Currently, only Conv2D and DepthwiseConv has multithreaded kernels.
> So you will only get benefit of they are significant in your model.

Thks for your reply. There are two models in my project, one of which is trained based on deeplab-v3 +, and the other is OCR model  based on densenet-18.  All models are quantized by post quantization, which makes multithreading not work?

**Comment by thaink** [comment]
Could you run the performance benchmark(https://www.tensorflow.org/lite/performance/benchmarks) on both models with the --enable_op_profiling=true?
It will give much more details.
