### ISSUE TITLE
Keras Model accepts unnamed 

### ISSUE THREAD

**Issue by jjh42** [tensorflow/tensorflow#42443]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

Colab.

- TensorFlow installed from (source or binary):
colab

- TensorFlow version (use command below):

tf 2.3.0

- Python version:
colab default

**Describe the current behavior**

Keras model (in eager mode at least) accepts a dictionary for named input, but will accept without warning any dictionary of the correct length regardless of the key names.

**Describe the expected behavior**

A warning or error if the keys provided as input when running a keras model do not match the named input.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
import tensorflow as tf

# Define a simple model with named input
a = tf.keras.Input(shape=[1], name='a')
b = tf.keras.Input(shape=[1], name='b')
out = tf.concat([a, b], axis=0)
out = tf.reduce_sum(out, axis=0)
model = tf.keras.Model([a, b], [out])

# As expected models runs with named input
model({'a': tf.convert_to_tensor([1]), 'b': tf.convert_to_tensor([1])})

# However, model will silently accept any dictionary with two tensors
# (of appropriate shape) without warning.
model({'c': tf.convert_to_tensor([1]), 'd': tf.convert_to_tensor([1])})

# It will warn if the dictionary has too many entries
model({'c': tf.convert_to_tensor([1]), 'd': tf.convert_to_tensor([1]), 'e': tf.convert_to_tensor([1])})

# Or raise an Assertion if the dictionary has too few entries.
model({'c': tf.convert_to_tensor([1])})
```

**Comment by Saduf2019** [comment]
@jjh42 
I ran the code shared but face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/eb5f441b670e9c8714d9adfeed572f46/untitled377.ipynb), please share a colab gist with the error and let us know.

**Comment by jjh42** [comment]
Yes that assertion error is as what I noted in the code on the last line

# Or raise an Assertion if the dictionary has too few entries.
model({'c': tf.convert_to_tensor([1])})

If you remove that last line it won't raise an assertion error and the key issue is this line:
# However, model will silently accept any dictionary with two tensors
# (of appropriate shape) without warning.
model({'c': tf.convert_to_tensor([1]), 'd': tf.convert_to_tensor([1])})

the model will silently accept a dictionary with completely the wrong keys if it is of the correct length.

**Comment by Dynmi** [comment]
```
        # In the case that the graph is constructed with dict input tensors,
        # We will use the original dict key to map with the keys in the input
        # data. Note that the model.inputs is using nest.flatten to process the
        # input tensors, which means the dict input tensors are ordered by their
        # keys.
```
Refered from https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/python/keras/engine/functional.py#L5329

It seems that in tf2.3.0 it only cares about the order of the dict input tensors, but doesn't check the the keys' name.

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/d1740f300d9779e3af0872dd1e91c233/untitled59.ipynb)..Thanks !

**Comment by jvishnuvardhan** [comment]
@jjh42 This was resolved in recent TF versions. [Here](https://colab.research.google.com/gist/jvishnuvardhan/fa909317e2d6fdd2d48eaa1e30b6ea65/untitled377.ipynb) is a gist for a reference.

It throws a warning as expected. I am closing this issue as this was resolved. Please feel free to reopen if the issue persists again. Thanks!
