### ISSUE TITLE
CosineSimilarity documentation range incorrect

### ISSUE THREAD

**Issue by danielplatt** [tensorflow/tensorflow#42458]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/keras/losses/CosineSimilarity

### Clear description

"Note that it is a negative quantity between -1 and 0" should be changed to "Note that it is a negative quantity between -1 and 1"

### Submit a pull request?

Don't plan to submit pull request

**Comment by Dynmi** [comment]
There is no negative quantity in (0,1).

**Comment by ymodak** [comment]
This is fixed now with commit [7e7641d](https://github.com/tensorflow/tensorflow/commit/7e7641d95c6c9b7e46b129c10ec7a965fb2f848d) . Thanks!
