### ISSUE TITLE
AttributeError: module 'tensorflow.python.keras' has no attribute 'abs'

### ISSUE THREAD

**Issue by lakwin-chandula** [tensorflow/tensorflow#42457]
<em>I am working on a multi-class image classification problem by using a siamese model.</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.1.0
- Python version: 3.6.10
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: Nvidia 920MX

I am working on a image classification problem with multiple classes and i follow a siamese face recognition sample in here. I have saved processed data in **.npy** format and i have used **Lambda** in the siamese model. It shows an error in `lambda `:

**`distance_euclid = Lambda( lambda tensors : K.abs( tensors[0] - tensors[1] ))( [output_x1 , output_x2] )`**

**Comment by Saduf2019** [comment]
@lakwin-chandula 
Please refer to [this link](https://stackoverflow.com/questions/57406870/importerror-cannot-import-name-abs-from-tensorflow-python-keras-impl-keras-b) with same error and let us know.

Few more links with similar suggestions:
[link](https://www.edureka.co/community/67412/tensorflow-importerror-cannot-import-name-abs-error) [link1](https://github.com/tensorflow/tensorflow/issues/19436#issuecomment-433685257) [link2](https://github.com/tensorflow/tensorflow/issues/20984#issuecomment-407882330)

**Comment by lakwin-chandula** [comment]
This attribute error seems to be triggered by `from tensorflow.python import keras as K`. I have changed it to `import tensorflow.python.keras.backend as K`. But then, it shows an `AttributeError: module 'tensorflow' has no attribute 'python'`. 

[AttributeError: module 'tensorflow' has no attribute 'python' #42486](https://github.com/tensorflow/tensorflow/issues/42486)

**Comment by Saduf2019** [comment]
@lakwin-chandula
As the new error faced is been tracked in #42486 we will have to move this issue to closed status please confirm, also as initial error abs is resolved as well.
