### ISSUE TITLE
Error Importing Tensorflow

### ISSUE THREAD

**Issue by muriloasouza** [tensorflow/tensorflow#42456]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution:  (Windows 10 64 bits)
- Mobile device: None
- TensorFlow installed from (source or binary):
- TensorFlow version:  2.3.0
- Python version: 3.8.4
- Installed using virtualenv? pip? conda? : pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: Nvidia GeForce 920M 2GB

**Describe the problem**
When trying to import tensorflow, i got the following error:

> Traceback (most recent call last):
>   File "C:\Users\Muril\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
>     from tensorflow.python._pywrap_tensorflow_internal import *
> ImportError: DLL load failed while importing _pywrap_tensorflow_internal: Não foi possível encontrar o módulo especificado.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "deep_versions.py", line 2, in <module>
>     import tensorflow
>   File "C:\Users\Muril\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
>     from tensorflow.python.tools import module_util as _module_util
>   File "C:\Users\Muril\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
>     from tensorflow.python.eager import context
>   File "C:\Users\Muril\Anaconda3\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
>     from tensorflow.python import pywrap_tfe
>   File "C:\Users\Muril\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "C:\Users\Muril\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "C:\Users\Muril\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
>     from tensorflow.python._pywrap_tensorflow_internal import *
> ImportError: DLL load failed while importing _pywrap_tensorflow_internal: Não foi possível encontrar o módulo especificado.
> 
> 
> Failed to load the native TensorFlow runtime.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
# tensorflow
import tensorflow
print('tensorflow: %s' % tensorflow.__version__)
```
**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I'm using Anaconda, and installed through pip in the command prompt. Using `python -VV` i got the following:

`Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]`

Later, i tried install using `conda install -c conda-forge tensorflow`, and got the following:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - tensorflow -> python[version='3.5.*|3.6.*|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|3.7.*']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/win-64::__cuda==10.1=0

Your installed version is: 10.1
```

**Comment by ravikyram** [comment]
@muriloasouza 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.Please, refer similar issues #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
Thanks!

**Comment by muriloasouza** [comment]
@ravikyram 

1 - It's an Intel Core i7-5500U;
2 - Not really sure what microsoft visual c++ i should download there, x64? x86? ARM64?
3 - Do i really need to install those versions of Python (3.6 or 3.7)? I've seen it should work in Python 3.8;
4 - Both my CPU and Python are on 64 bits (as you can see in the `python -VV` result i posted earlier).
