### ISSUE TITLE
What Grappler optimizers turned on by default?

### ISSUE THREAD

**Issue by shkarupa-alex** [tensorflow/tensorflow#42450]
## URL(s) with the issue:
https://www.tensorflow.org/guide/graph_optimization

## Description of issue (what needs changing):
It should be cleared which optimizers Grappler applies by default. 
For now it's not clear if i should turn on a lot of features by myself

### Parameters defined

Are all parameters defined and formatted correctly? - No.

**Comment by Harsh188** [comment]
Hi @shkarupa-alex! I'm currently working on the documentation of `set_optimizer_experimental_options` to specify the parameters more clearly. I believe that the different functions of the graph optimizers are explained thoroughly so depending on your problem you should decide which features to turn on.

**Comment by andrescodas** [comment]
Hi @Harsh188 

I have been trying to leverage grappler for some time and I'm finding it hard to find the relevant documentation.

I sub-classed tf.Module following **Saving a custom model here** [here](https://www.tensorflow.org/guide/saved_model#saving_a_custom_model).  There I write several graphs (with tf.function) that I would like to optimize them for fast execution.

Could you exemplify how to run the MetaOptimizer procedure described [here](http://web.stanford.edu/class/cs245/slides/TFGraphOptimizationsStanford.pdf) on slide 13 ?.  Further, I'm wondering how to save the resulting optimized graph for later re-use.

Thanks!

**Comment by Harsh188** [comment]
@andrescodas unfortunately I'm not the best person to tackle your questions so excuse me if I don't answer your question.

By the looks of it `MetaOptimizer` is the top-level which performs the graph optimizations. Take a look at the list of optimizers provided in https://www.tensorflow.org/api_docs/python/tf/config/optimizer/set_experimental_options and determine which ones suit you. Using `set_optimizer_experimental_options` you can then enable the optimizer of your choice.

If you have any specific documentation changes you have in mind please let me know! I'll do my best to clear up the confusion.

**Comment by andrescodas** [comment]
> If you have any specific documentation changes you have in mind please let me know! I'll do my best to clear up the confusion.

Thank you!.  I have seen `set_optimizer_experimental_options` however I'm missing an example use case in the interface of tf.saved_model and grappler.  E.g.

Suppose I have a complex graph that I want to optimize and save for later use:

```python
class CustomModule(tf.Module):

  @tf.function
  def f(self, x, y):
    z = x * y   # potentially complex graph where I want to run the different grappler optimizers
    return z

module = CustomModule()

# 
#  here I apply graph optimization to `module`.  How can I implement run_grappler_optimizations_on_module?
#
module = run_grappler_optimizations_on_module(module)


# here I save it
tf.saved_model.save(module, '/my/model/directory')
```

Later in a different process I may load it and run,
``` python 

module = tf.saved_model.load('/my/model/directory')

# here I run the optimized function without needing to re-run run_grappler_optimizations_on_module
z = module.f(...)

```

**Comment by zhuzilin** [comment]
For anyone still have interest in whether a grappler optimizer is default on or off, please check `tensorflow/core/protobuf/rewriter_config.proto`. This is the protobuf file used to send grappler information from python side to backend C++ side and it includes rich information on what every grappler optimizer does.

**Comment by rmothukuru** [comment]
@shkarupa-alex,
As the [Documentation of Grappler Optimizers](https://www.tensorflow.org/guide/graph_optimization#available_graph_optimizers) specify which Optimizers are turned on by Default, can you please confirm if we can close this issue? Thanks!

**Comment by shkarupa-alex** [comment]
Now it's clear.
Thanks!

**Comment by rmothukuru** [comment]
Closing the issue as it has been resolved.
