### ISSUE TITLE
Compiler crash with clang 7.1

### ISSUE THREAD

**Issue by yair-ehrenwald** [tensorflow/tensorflow#42468]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): LLVM Clang 7.1.0
- CUDA/cuDNN version:
- GPU model and memory:

When building TF Micro I get a compiler crash on micro_allocator.cc (commit  d5ed5f9).
[dump.txt](https://github.com/tensorflow/tensorflow/files/5091697/dump.txt)
(See attached dump)
The issue apparently is unstable support in clang 7.1 for flexible members.

defining data[] as data[0] in TfLiteIntArray definition solves the issue.
See PR:
https://github.com/tensorflow/tensorflow/pull/42464

**Comment by advaitjain** [comment]
Copying some communication over email into this github issue:

Hi Yair,

We don't have an easy way to reproduce your error, so could you try one of these two fixes at your end and send in a PR if either of them work:

 * Add an appropriate check for your compiler version / platform in tensorflow/lite/c/common.h similar to [this commit](https://github.com/tensorflow/tensorflow/commit/481aec85d669dad80f8d8e0c53e03c45f956959d).

 * If that doesn't work, try changing the initialization of the offending line to const TfLiteIntArray kZeroLengthIntArray = {0};
   * This bit of initialization has changed over different commits ([1](https://github.com/tensorflow/tensorflow/commit/076bbc5edfe655299b006b3c1b2c6281d330d638#diff-6dace628e5372fb3c3fbb76e0fd9d37aR51), [2](https://github.com/tensorflow/tensorflow/commit/290487b03ed7a9fa78af6faa2d8c19f7e5fde30e#diff-6dace628e5372fb3c3fbb76e0fd9d37aR56), [3](https://github.com/tensorflow/tensorflow/commit/c29d6434bae6680039ca4c8b9aaf6dd30dae4c62#diff-6dace628e5372fb3c3fbb76e0fd9d37aR53)) so if option 1 does the trick for you, that would likely be more future-proof.

Thanks,
Advait
