### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError:  No algorithm worked!

### ISSUE THREAD

**Issue by Ashiix** [tensorflow/tensorflow#42474]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux -  Linux 5.8.1
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.8
- CUDA/cuDNN version: 11.0.2 / 8.0.2.39
- GPU model and memory: RTX 2060 6 GB

**Describe the current behavior**
Crashing on conv_ops.cc when running on basic MNIST dataset

**Standalone code to reproduce the issue**
https://gist.github.com/Ashiix/9b00c28ee11411de4f052c0733fcbffd

**Other info / logs**
https://gist.github.com/Ashiix/053749aed670c3c2f3de02c3b193e5d3

**Comment by ravikyram** [comment]
@Ashiix 

I have tried in colab with TF version 2.3. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/3ca66219954eafae5dcb46e33f9959a1/untitled264.ipynb).You are also seeing the same behavior?

Thanks!

**Comment by yenigma** [comment]
Downgrading to version 2.2 solves the problem.
Command:
$ downgrade python-tensorflow-cuda

**Comment by ravikyram** [comment]
@Ashiix 

Any update on this issue please. Thanks!

**Comment by erinhong** [comment]
**System Information** 

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 
TensorFlow version (use command below): 2.3.0
Python version: 3.8
CUDA/cuDNN version: 11.0.2 / 8.0.2.39
GPU model and memory: 1080Ti 10GB

**Describe the current behavior**

2020-09-01 20:57:59.779251: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at conv_ops_3d.cc:491 : Not found: No algorithm worked!

tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError:  No algorithm worked!
         [[node functional_1/conv3d/Conv3D (defined at train.py:348) ]] [Op:__inference_train_function_1168]

**Comment by yenigma** [comment]
Try again with TensorFlow version 2.2.
Works for me.

**Comment by erinhong** [comment]
@yenigma Thanks for the suggestion. Unfortunately, I have also tried Tensorflow 2.2 and also changed CUDA 10.1, cuDNN 7.6.5 and the error doesn't change.
