### ISSUE TITLE
Extremely Large Slow Down in Performance Between 21th July & 22nd July Nightly Release

### ISSUE THREAD

**Issue by oracle3001** [tensorflow/tensorflow#42478]
**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow installed from (source or binary): Tf-Nightly-GPU
- TensorFlow version (use command below): 2.4.0.dev
- Python version: 3.7
- CUDA/cuDNN version: 10.1 / 7.6
- GPU model and memory: nVidia 2070 Max-Q

It appears some change was made between the nightly release of the 21st and the 22nd July 2020 that has caused a dramatic (over x10) slow down in the time to complete an epoch of training apart of an optimization I am running. Furthermore, I have checked right up to the current date and this slow down still exists. As well as up to TF2.4 (21st July), TF 2.3 release also runs fine.

Unfortunately, for both reasons of IP and that the code is rather involved I can't share it publicly on here. And thus I appreciate trying to resolve this issue is challenging. However, is there anything in particular that was changed over these two dates that stands that out that could potential cause such a large change in time to optimize and  / or anything I could do further to investigate and thus assist with what might have resulted in this issue? 

Between the two release, when running the code, there is no obvious difference in the start-up debug output that is displayed in terms of adding gpu device, successfully opening the cuda libraries, etc.

**Comment by ravikyram** [comment]
@oracle3001 

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!
