### ISSUE TITLE
Which TensorFlow-Slim is the "real" one?

### ISSUE THREAD

**Issue by ohmystack** [tensorflow/tensorflow#4247]
I have found 3 TensorFlow-Slim in repo `tensorflow/tensorflow` and `tensorflow/model`

* (tensorflow/tensorflow) [`tensorflow.contrib.slim`](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/slim)
* (tensorflow/model) [`model.slim`](https://github.com/tensorflow/models/blob/master/slim)
* (tensorflow/model) [`model.inception.inception.slim`](https://github.com/tensorflow/models/blob/master/inception/inception/slim)

Among these places, there are some duplicated codes.
e.g.
* (tensorflow/tensorflow) [`tensorflow/tensorflow/contrib/slim/python/slim/nets/overfeat.py`](https://github.com/tensorflow/tensorflow/blob/3d1ee95e612b1987e664ca46a7c584872d36dde9/tensorflow/contrib/slim/python/slim/nets/overfeat.py)
* (tensorflow/model) [`slim/nets/overfeat.py`](https://github.com/tensorflow/models/blob/master/slim/nets/overfeat.py)

### Question:

1. What are these 3 `slim` packages used for? What's the differences?
2. In the future, which one may be deprecated? Or which one will be the future.

**Comment by ohmystack** [comment]
cc @nathansilberman @lukaszkaiser @sguada

**Comment by sguada** [comment]
Use tensorflow.contrib.slim for all the core functionality.

Use tensorflow/model/slim for the models and nets.

This one is deprecated: (tensorflow/model) model.inception.inception.slim

**Comment by ohmystack** [comment]
@sguada Thanks for your explanation!
