### ISSUE TITLE
SetNumThreads makes inference slower!

### ISSUE THREAD

**Issue by anhkhoa45** [tensorflow/tensorflow#42480]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution: Android 9
- Mobile device: Vsmart JOY 3
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.0
- Python version:
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

Inference time when using SetNumThreads (numThreads = 4):

![image](https://user-images.githubusercontent.com/16491585/90585698-a5099480-e1ff-11ea-831e-a1294f910b68.png)

Inference time without SetNumThreads:

![image](https://user-images.githubusercontent.com/16491585/90585816-f74ab580-e1ff-11ea-9490-87cfb3304b44.png)

Currently, I'm using 2 tflite models in our project, the first one runs normally without any performance degradation,

**Describe the expected behavior**

SetNumThreads shouldn't make the inference slower.

**Standalone code to reproduce the issue**

```c++
FaceDetector::FaceDetector(void *modelBuff, int size, int threadNum)
{
    if (size < 1)
        return;

    this->_modelBytes = (char *)malloc(sizeof(char) * size);
    memcpy(this->_modelBytes, modelBuff, sizeof(char) * size);

    // Build the model
    this->_model = tflite::FlatBufferModel::BuildFromBuffer(this->_modelBytes, size);

    // Build the interpreter
    tflite::ops::builtin::BuiltinOpResolver resolver;
    tflite::InterpreterBuilder builder(*this->_model, resolver);
    builder(&this->_interpreter);

    // Allocate tensor buffers.
    this->_interpreter->AllocateTensors();

    // Set threads num
    this->_interpreter->SetNumThreads(threadNum);

    this->_ready = true;
}

FaceDetector::~FaceDetector()
{
    free(this->_modelBytes);
    this->_modelBytes = nullptr;
}

bool FaceDetector::isReady()
{
    return this->_ready;
}

void FaceDetector::detect(void *data, int width, int height, int channel)
{
    // Set input/output tensor ptr
    float* _inputTensor = this->_interpreter->typed_input_tensor<float>(0);
    float* _boxesTensor = this->_interpreter->typed_output_tensor<float>(0);
    float* _scoresTensor = this->_interpreter->typed_output_tensor<float>(1);

    Mat image = Mat(height, width, CV_8UC3, data);
    Mat scaled, fImage;
    resize(image, scaled, Size(128, 128), 0, 0, INTER_AREA); // Scale RGB image to model input size
    float IMAGE_STD = 127.5f, IMAGE_MEAN = 127.5f;
    scaled.convertTo(fImage, CV_32FC3, 1 / IMAGE_STD, -IMAGE_MEAN / IMAGE_STD);

    memcpy(_inputTensor, fImage.data, 128*128*3*sizeof(float));

    this->_interpreter->Invoke();
}
```

**Comment by freedomtan** [comment]
If your device have less than 4 cores with same capability or some of the cores are busy, this is likely to happen.

**Comment by anhkhoa45** [comment]
@freedomtan 

Thanks for your reply! My device has 8 cores.

**Comment by freedomtan** [comment]
It's unlikely you have a phone having 8 cores with same capabilities. Most SoCs available for Android nowadays are 4+4, 1+3+4, and 2+2+4.

**Comment by anhkhoa45** [comment]
I don't think it's the problem since the other tflite model runs well with 4 threads.

> Currently, I'm using 2 tflite models in our project, the first one runs normally without any performance degradation

(When testing this model I disabled the first one)

Is there any other factor that could affect the performance of tf multithread?

**Comment by thaink** [comment]
@anhkhoa45 
Could you run the performance benchmark(https://www.tensorflow.org/lite/performance/benchmarks) on both models with the --enable_op_profiling=true?
It will give much more details for analysis. Thanks.

**Comment by anhkhoa45** [comment]
@thaink Sure! Here's the result:

First model: https://pastebin.com/Z0KkJWFK

Second model: https://pastebin.com/8E0Ksq4d

**Comment by anhkhoa45** [comment]
This is my mistake during argument passing. I'll close this issue. Thanks 🙇
