### ISSUE TITLE
Missing masOS Big Sur build, Could not find a version that satisfies the requirement tensorflow

### ISSUE THREAD

**Issue by BrikerMan** [tensorflow/tensorflow#42482]
**System information**
- OS Platform and Distribution: masOS Big Sur
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.3.0
- Python version: 3.7/3.8
- Installed using virtualenv? pip? conda?: virtualenv + pip

**Describe the problem**
Could not find a version that satisfies the requirement tensorflow (from versions: none)

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```bash
$ pip install tensorflow
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```

```bash
$ pip install tensorflow==2.3.0
ERROR: Could not find a version that satisfies the requirement tensorflow==2.3.0 (from versions: none)
ERROR: No matching distribution found for tensorflow==2.3.0
```

```bash
$ pip install /Users/brikerman/Downloads/tensorflow-2.3.0-cp38-cp38-macosx_10_11_x86_64.whl
ERROR: tensorflow-2.3.0-cp38-cp38-macosx_10_11_x86_64.whl is not a supported wheel on this platform.
```

**Comment by Saduf2019** [comment]
@BrikerMan 
Please check if you have the latest version of pip installed. As per the [documentation](https://www.tensorflow.org/install) TensorFlow 2 packages require a pip version >19.0.
You can upgrade pip using the below command:

python3 -m pip install --upgrade pip first

Also, please check the Python version installed on your machine. As per the [PyPI website](https://pypi.org/project/tensorflow/), 
and try python3 -m pip install tensorflow==2.3.0

#37457 #41262 [Link](https://github.com/tensorflow/tensorflow/issues/38882#issuecomment-624759253) please check compatibility issue.

**Comment by BrikerMan** [comment]
Python: 3.7.8
Pip: 20.2.2

```bash
➜ which python
/Users/brikerman/Desktop/ai/rl/unity_rl/venv/bin/python
➜ which python3
/Users/brikerman/Desktop/ai/rl/unity_rl/venv/bin/python3

➜ python --version
Python 3.7.8

➜ pip --version
pip 20.2.2 from /Users/brikerman/Desktop/ai/rl/unity_rl/venv/lib/python3.7/site-packages/pip (python 3.7)

➜ pip install tensorflow==2.3.0
ERROR: Could not find a version that satisfies the requirement tensorflow==2.3.0 (from versions: none)
ERROR: No matching distribution found for tensorflow==2.3.0

➜ python3 -m pip install tensorflow==2.3.0
ERROR: Could not find a version that satisfies the requirement tensorflow==2.3.0 (from versions: none)
ERROR: No matching distribution found for tensorflow==2.3.0

➜ python3 -c "import platform; print(platform.architecture())"
('64bit', '')
```

**Comment by Saduf2019** [comment]
@BrikerMan 

Can you please verify is you are using 32 bit python version.

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the latest [microsoft visual c++ redistributable from here.](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).

Please, refer #36167 and see if it helps you.

**Comment by BrikerMan** [comment]
It is a 64bit python. checkout this. And I am using MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports). I am able to run tf 2.2.0 before I installed the `Big Sur Beta`

```
➜ python3 -c "import platform; print(platform.architecture())"
('64bit', '')
```

**Comment by BrikerMan** [comment]
I think I found the issue. It is caused by `pyenv`
I am able to install tensorflow==2.2.0, 2.3.0 on Python3.8 (pre-installed on mac Big Sur)
When I using python 3.7.8 installed by pyenv, then I have this issue.

**Comment by prouast** [comment]
@BrikerMan I am having the same issue with Pyenv. Did you end up finding a solution, or have you just stopped using Pyenv on Big Sur?

**Comment by chris-moov** [comment]
@BrikerMan @prouast Same issue here using Pyenv on MacOS 11.0.1, with Python 3.7.9 & 3.8.5. 

I also tried running Python installed using brew install python3@7, it still does not work.

**Comment by BrikerMan** [comment]
@prouast @chris-moov I just stopped using Pyenv on Big Sur. I used miniconda and it works just fine.

**Comment by prouast** [comment]
@BrikerMan Thanks for the pointer. I installed miniconda via Pyenv and that seems to solve the problem.

**Comment by jeyabbalas** [comment]
I was facing the same problem after I upgraded to macOS Big Sur (11.0.1). I was unable make it work with pyenv as well. Upgrading my local Python build to 3.8.6 solved my problem.

**Comment by chris-moov** [comment]
I tried installing miniconda, that failed too. I reckon there is a bug in the Python builds in pyenv and/or brew. 

I have downloaded Python from python.org and it worked!

**Comment by dgladkov** [comment]
I don't think this is a bug since Big Sur is a new major release of macOS. The current platform matching behavior for macOS wheels matches the exact major version and will not match wheels built for the platform `macosx_10_9_x86_64`. I do not understand how changing Python versions would help this problem, since this is the behavior dictated by `pip`.

To guarantee proper wheel support, tensorfow needs to just reupload existing wheels with `macosx_11_0_x86_64` tag and update PyPI publishing pipeline to upload wheels for both major versions.

To mitigate the problem right now, you can download the wheel for macOS 10.x and rename the tag. E.g. for Python 3.7:
```shell
$ wget https://files.pythonhosted.org/packages/0d/ea/f936c14b6e886221e53354e1992d0c4e0eb9566fcc70201047bb664ce777/tensorflow-2.3.1-cp37-cp37m-macosx_10_9_x86_64.whl
$ mv tensorflow-2.3.1-cp37-cp37m-macosx_10_9_x86_64.whl tensorflow-2.3.1-cp37-cp37m-macosx_11_0_x86_64.whl
$ pip install ./tensorflow-2.3.1-cp37-cp37m-macosx_11_0_x86_64.whl
```

**Comment by umeshksingla** [comment]
@dgladkov I get: 
```
$ pip install ./tensorflow-2.3.1-cp37-cp37m-macosx_11_0_x86_64.whl

ERROR: tensorflow-2.3.1-cp37-cp37m-macosx_11_0_x86_64.whl is not a supported wheel on this platform.```

**Comment by umeshksingla** [comment]
Try this: https://github.com/apple/tensorflow_macos

**Comment by sector84** [comment]
Have the same problem
not only with tensorflow but also with scikit-learn
found some hacks that helps me for now (until we have to wait for pip to fix this issue)
https://github.com/scikit-learn/scikit-learn/issues/18861

1. install python from conda-forge (via miniconda):
- brew cask install miniconda
- conda config --add channels conda-forge
- conda install libpython-static python
2. create venv with that interpreter (mkvirtualenv dl4cv -p /usr/local/Caskroom/miniconda/base/bin/python)
3. install tensorflow with pip
4. profit

**Comment by mo22** [comment]
you can also patch `site-packages/pip/_vendor/packaging/tags.py` and patch the `version_str`:
```
    version_str, _, cpu_arch = platform.mac_ver()  # type: ignore
    version_str = "10.15"  # add this
```

**Comment by vqbang96** [comment]
I am having problem installing TensorFlow with anaconda3. Trying to create an environment and `pip3 install tensorflow==2.1.0` but still get and error missing package

ERROR: Could not find a version that satisfies the requirement tensorflow==2.1.0
ERROR: No matching distribution found for tensorflow==2.1.0

**Comment by dbl001** [comment]
I am trying to install tensorflow on metal following these instructions:
https://developer.apple.com/metal/tensorflow-plugin/

ERROR: Could not find a version that satisfies the requirement tensorflow-macos (from versions: none)
ERROR: No matching distribution found for tensorflow-macos

I am on Big Sur OS X 11.4 the tensorflow_metal virtual environment.
```
% python3 -c "import platform; print(platform.architecture())"
('64bit', '')
(base) (tensorflow-metal) davidlaxer@x86_64-apple-darwin13 notebooks % python --version
Python 3.8.5
(base) (tensorflow-metal) davidlaxer@x86_64-apple-darwin13 notebooks % 


 python -m pip install tensorflow-macos
ERROR: Could not find a version that satisfies the requirement tensorflow-macos (from versions: none)
ERROR: No matching distribution found for tensorflow-macos
(base) (tensorflow-metal) davidlaxer@x86_64-apple-darwin13 notebooks % python -m pip install tensorflow-metal
```
I added:
vi  /Users/davidlaxer/tensorflow-metal/lib/python3.8/site-packages/pip/_vendor/packaging/tags.py 
 version_str = "10.15" # added this dbl

**Comment by georgebohnisch** [comment]
Having the same issue, did anyone figure this out?
