### ISSUE TITLE
how to get a tensorflow tf by index?

### ISSUE THREAD

**Issue by SlowMonk** [tensorflow/tensorflow#42485]
```
    object_for_each_prior = tf.constant([1 for i in range(8732)])
    -><tf.Tensor: shape=(8732,), dtype=int32, numpy=array([1, 1, 1, ..., 1, 1, 1], dtype=int32)>
```

Then if I want to get the position 1148,1149<br/>

```
    prior_for_each_object = tf.constant([1148,1149])
    object_for_each_prior[prior_for_each_object]
```

Then I got the following error <br/>

`    TypeError: Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices, got <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1148, 1149], dtype=int32)>
`
If I want to get the tensor's number by index how should I approach it?

**Comment by SlowMonk** [comment]
and if I want to set the different number 

`            object_for_each_prior[prior_for_each_object] = tf.constant(list(range(n_objects)),dtype=tf.int64)
`
How should I do it?

**Comment by Saduf2019** [comment]
@SlowMonk 
Please fill the issue template for us to assist you with the issue.
