### ISSUE TITLE
TFLite - enable XNNPACK with dynamic shapes of tensors

### ISSUE THREAD

**Issue by svobora** [tensorflow/tensorflow#42491]
**System information**
- TensorFlow version (you are using): 2.3.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
In 2.3.0, dynamic shapes  were fixed in TFLite ("TFLite now properly supports dynamic shapes during conversion and inference."). We can now process tensors with varying batch size, everything works, great. 

However, running on Windows 10 64b, the processing is slower than base TF2. Using TFLite with XNNPACK and fixed batch size 1, the processing is about 2x faster than with base TF2. So the final difference is about 3x in latency. My request is to enable XNNPACK Delegate to process dynamic shaped tensors to enjoy fast processing with variable batch size.

**Will this change the current api? How?**
No.

**Who will benefit with this feature?**
Anyone wishing to process batches of images of various size.

**Any Other info.**

**Comment by pkgoogle** [comment]
Hi @svobora, we do not currently plan to support tflite dynamic shapes, https://www.tensorflow.org/lite/guide/inference. If you have no more open items please feel free to close the issue as not planned.
