### ISSUE TITLE
Inception-v3 checkpoint - Tensor name not found

### ISSUE THREAD

**Issue by tenscraft** [tensorflow/tensorflow#4249]
Trying to run the Inceptionv3 Tensorflow model with the architecture and the checkpoint provided by Google [here](https://research.googleblog.com/2016/08/improving-inception-and-image.html).

The issue is that tensorflow crashes on `saver.restore(sess, "./inception_v3.ckpt")` with the following error:

`tensorflow.python.framework.errors.NotFoundError: Tensor name "InceptionV3/Mixed_5b/Branch_1/Conv2d_0b_5x5/biases" not found in checkpoint files ./inception_v3.ckpt`

I get the same errors with the inception resnet v2 checkpoint/model combination.
Missing tensor in the checkpoint or issue with the model file?

Thank you

**Comment by tatatodd** [comment]
Have you seen the documentation here?  It might be useful in getting started:
https://github.com/tensorflow/models/tree/master/slim
https://github.com/tensorflow/models/blob/master/slim/slim_walkthough.ipynb

The first link describes how to run eval:
```
CHECKPOINT_FILE = ${CHECKPOINT_DIR}/inception_v3.ckpt  # Example
$ python eval_image_classifier.py \
    --alsologtostderr \
    --checkpoint_path=${CHECKPOINT_FILE} \
    --dataset_dir=${DATASET_DIR} \
    --dataset_name=imagenet \
    --dataset_split_name=validation \
    --model_name=inception_v3
```
https://github.com/tensorflow/models/blob/master/slim/eval_image_classifier.py

You can use eval_image_classifier.py as a starting point to do what you'd like.  Hope that helps!

**Comment by tenscraft** [comment]
I have tried to run eval with those scripts too, and with randomly generated images as shown in the .ipynb file, but keep getting this error:

`tensorflow.python.framework.errors.NotFoundError: Tensor name "InceptionResnetV2/Repeat/block35_9/Branch_2/Conv2d_0b_3x3/biases" not found in checkpoint files`

**Comment by sguada** [comment]
Need to use the right arg_scope 

```
with tf.Session() as sess:
  image = tf.read_file('./file.jpg')
  # code to decode, crop, convert jpeg
  eval_inputs = tf.pack([image])
  with slim.arg_scope(inception_v3.inception_v3_arg_scope()):
    logits, _ = inception_v3.inception_v3(eval_inputs, num_classes=1001, is_training=False)
  sess.run(tf.initialize_all_variables())
```

**Comment by tatatodd** [comment]
@tenscraft does @sguada's suggestion fix your problem?

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Comment by shikongzxz** [comment]
same problem here, with @sguada 's suggestion,  solved my problems.
