### ISSUE TITLE
Minimum requirement for Tensorflow Lite

### ISSUE THREAD

**Issue by emzei** [tensorflow/tensorflow#42490]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):  source
- TensorFlow version: N/A
- Python version: N/A
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

I tried to make an inference program with C/C++ (TF Lite Microcontroller) in ARMv7(32-bit) environment at the very beginning, but the model that I converted includes complex bidirectional LSTM and DNN, and it was hard to use with the C/C++ environment. 
I got errors when my codes load the converted model in C/C++ even though there was no error while conversion.

Before converting the model, I checked that  simple exmaple binary such as hello_world (TF Lite example) is running well on c/c++ with armv7 environment, and the converted model is also running well on python with x86 environment.

I changed my plan into using Python, but my embedded board has no tools like pip, wget, python, and other basic binaries to use. (Thus, now I'm trying to build python for my board.) Additionally, there is only 300 MB that I can use in the board.
I want to know the minimum requirement of Tensorflow Lite for Python and Microcontroller (C/C++).

The board has nxp4330(ARM32) chipset and it has only minimum binaries to run, so I have no idea what I have to do first for using TF Lite with this board. 
Thank you in advance.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by terryheo** [comment]
You can start with TFLite C library.
https://www.tensorflow.org/lite/guide/build_rpi#c_library
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/c

If you need more tiny inference platform, you can consider TFLite micro.
https://www.tensorflow.org/lite/microcontrollers
