### ISSUE TITLE
multi-dimensional array frequency count TF API  

### ISSUE THREAD

**Issue by 17patelumang** [tensorflow/tensorflow#42499]
**System information** 

     OS Platform and Distribution : macOS Catalina 10.15.3

    TensorFlow installed from : binary

    TensorFlow version : 1.15.0

    Python version: 3.7.3

**Describe the current behavior**

We have a tensor 

input = `tf.Tensor([[1296,266,504,190,44,60,13,2,337,6742,2667,14,1,119,580,338,785,739,855,200,37,1,3,4,5,6],
 [1296,266,504,190,44,60,13,2,337,6742,2667,14,1,119,580,338,785,739,855,200,37,1,3,4,5,6]], shape=(2, 29), dtype=int64)`

output = `tf.Tensor([[0,2,1, ... 0. 0. 0.][0, 2, 1, ... 0, 0, 0]], shape=(2, 10000), dtype=float32)`

Here 10000 is the dictionary size. 

**Describe the expected behavior**

We want vector output such that for each index it tell the frequency of each element 
ie in 
`[1296  266  504  190   44   60   13    2  337 6742 2667   14    1  119
   580  338  785  739  855  200   37    1    3    4    5    6]` ie we see 0 occurs 0 times , 1 occurs 2 times and so on .

Currently what we are getting is `tf.Tensor([[0. 4. 2. ... 0. 0. 0.]], shape=(1, 10000), dtype=float32)` we want of shape (2,10000)

Please tell us the right TF API transformation to do this . We tried code in https://github.com/tensorflow/tensorflow/issues/42374 but with no luck.

**Comment by amahendrakar** [comment]
@17patelumang,
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by 17patelumang** [comment]
@amahendrakar  thanks created question - https://stackoverflow.com/questions/63515872/multi-dimensional-array-frequency-count-in-tensorflow-api

**Comment by 17patelumang** [comment]
This is for others who read this ticket , we used recently released https://blog.tensorflow.org/2020/08/introducing-tensorflow-coder-tool.html?linkId=98162087&m=1  and found our fix , super nice tool !
