### ISSUE TITLE
Warning produced by Logging and Monitoring Basics with tf.contrib.learn example

### ISSUE THREAD

**Issue by ReaddyEddy** [tensorflow/tensorflow#4250]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
Similar issue here:
1. http://stackoverflow.com/questions/39249704/tensorflow-valueerror-duplicate-feature-column-key-found-for-column
2. have tried example at 
https://www.tensorflow.org/versions/master/tutorials/monitors/index.html
still exhibits same issue
3. I will look at github deltas in 0.10.0rc0 between 1 above head and see if same fix applied to tf.contrib.learn 
### Environment info
Operating System:
OS-X 10.11.6 Python 3.5 vi Homebrew 
Installed version of CUDA and cuDNN: 
N/A

## installed from binary pip package:
1. link to the pip package you installed:
https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.10.0rc0-py3-none-any.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.10.0rc0

### minimal reproducible example (
```python

import tensorflow as tf
import numpy as np

# Data sets
IRIS_TRAINING = "iris_training.csv"
IRIS_TEST = "iris_test.csv"

# Load datasets.
training_set = tf.contrib.learn.datasets.base.load_csv(filename=IRIS_TRAINING,
                                                       target_dtype=np.int)
test_set = tf.contrib.learn.datasets.base.load_csv(filename=IRIS_TEST,
                                                   target_dtype=np.int)

# Specify that all features have real-value data
feature_columns = [tf.contrib.layers.real_valued_column("", dimension=4)]

# Build 3 layer DNN with 10, 20, 10 units respectively.
classifier = tf.contrib.learn.DNNClassifier(feature_columns=feature_columns,
                                            hidden_units=[10, 20, 10],
                                            n_classes=3,
                                            model_dir="/tmp/iris_model")

# Fit model.
classifier.fit(x=training_set.data,
               y=training_set.target,
               steps=2000)

# Evaluate accuracy.
accuracy_score = classifier.evaluate(x=test_set.data,
                                     y=test_set.target)["accuracy"]
print('Accuracy: {0:f}'.format(accuracy_score))

# Classify two new flower samples.
new_samples = np.array(
    [[6.4, 3.2, 4.5, 1.5], [5.8, 3.1, 5.0, 1.7]], dtype=float)
y = classifier.predict(new_samples)
print('Predictions: {}'.format(str(y)))
```

### What other attempted solutions have you tried?
Referenced head example 

### Logs or other output that would be helpful

WARNING:tensorflow:Setting feature info to TensorSignature(dtype=tf.float32, shape=TensorShape([Dimension(None), Dimension(4)]), is_sparse=False)
WARNING:tensorflow:Setting targets info to TensorSignature(dtype=tf.int64, shape=TensorShape([Dimension(None)]), is_sparse=False)
WARNING:tensorflow:Given features: Tensor("input:0", shape=(?, 4), dtype=float32), required signatures: TensorSignature(dtype=tf.float32, shape=TensorShape([Dimension(None), Dimension(4)]), is_sparse=False).
WARNING:tensorflow:Given targets: Tensor("output:0", shape=(?,), dtype=int64), required signatures: TensorSignature(dtype=tf.int64, shape=TensorShape([Dimension(None)]), is_sparse=False).

**Comment by terrytangyuan** [comment]
You can change the logging level if you want to avoid them.

**Comment by tatatodd** [comment]
@ReaddyEddy thanks for reporting an issue!  It's unclear to me from your description what the actual problem is.  Is it...
1. You see warnings, but otherwise things work as you expected.  Or...
2. You see warnings, and immediately afterwards things crash.

Note that the first stackoverflow link you provided has some extra details about things working at HEAD.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity, please reopen or provide more information when it becomes available.

**Comment by martinwicke** [comment]
Note for posterity, these warnings are gone now. They were a bug.
