### ISSUE TITLE
Native crash when using GpuDelegate() on Android 11

### ISSUE THREAD

**Issue by Nublo** [tensorflow/tensorflow#42511]
We found out that issue is reproducing on Android 11, and works fine for Android 10 and less.
However this is our current crash rate distribution, maybe it can vary when we will get more data.

**System information**
- OS Platform and Distribution: Android 11: 100%
- Mobile device: Google Pixel 4 XL (34.35%), Google Pixel 3 (17.54%), Google Pixel 3 XL (14.84%), Google Pixel 3a (11.0%), Other devices (22.27%)
- TensorFlowLite installed from binary
- TensorFlowLite version:
"org.tensorflow:tensorflow-lite:0.0.0-nightly"
"org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly"

**Describe the current behavior**
Crash happens when we are trying to access `org.tensorflow.lite.gpu.GpuDelegate()` constructor.

**Describe the expected behavior**
No crash

**Other info / logs**
```
java.lang.Runtime.loadLibrary0(Runtime.java:1067)
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.bumble.app-8irvW4hQxSV1mR3fxr2zRQ==/base.apk", zip file "/data/app/com.bumble.app-8irvW4hQxSV1mR3fxr2zRQ==/split_config.en.apk", zip file "/data/app/com.bumble.app-8irvW4hQxSV1mR3fxr2zRQ==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.bumble.app-8irvW4hQxSV1mR3fxr2zRQ==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libtensorflowlite_gpu_jni.so"
```

```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "log2" referenced by "/data/app/~~_HPfJLFw-mGTIuaom9KTxg==/com.bumble.app-_q0StbZdkqA1sVAJw4oWDQ==/lib/arm64/libtensorflowlite_gpu_jni.so"...
  at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
  at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
  at java.lang.System.loadLibrary(System.java:1664)
  at org.tensorflow.lite.gpu.GpuDelegate.<clinit>(:165)
```

**Comment by Nublo** [comment]
We tried to migrate to the latest versions without using nightly builds and it helped.
"org.tensorflow:tensorflow-lite:2.3.0"
"org.tensorflow:tensorflow-lite-gpu:2.3.0"

Let's close this issue in this case.

**Comment by knumat** [comment]
I had a similar issue where the GpuDelegate() constructor was sometimes throwing a "cannot locate symbol" error for `ceilf` and `frexpf`.  I switched from 1.14.0 to 2.3.0 of the `tensorflow-lite` and `tensorflow-lite-gpu` libraries, and the error seems to have gone away now.  Thanks for the suggestion, @Nublo !
