### ISSUE TITLE
pip installation 0.10.0 requires cuDNN v5, not cuDNN v4

### ISSUE THREAD

**Issue by jakubsimanek** [tensorflow/tensorflow#4251]
[Download and Setup, Pip installation instructions for 0.10.0](https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#pip-installation) say that `Ubuntu/Linux 64-bit, GPU enabled, Python 2.7` version `Requires CUDA toolkit 7.5 and CuDNN v4.`,

That setup results in:

`E tensorflow/stream_executor/cuda/cuda_dnn.cc:347] Loaded runtime CuDNN library: 4007 (compatibility version 4000) but source was compiled with 5103 (compatibility version 5100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.`

**Installation of cuDNN v5 (`cudnn-8.0-linux-x64-v5.1`) resolves the problem.**
I think the instructions need an update to `Requires CUDA toolkit 7.5 and CuDNN v5.`.

### Environment info
Operating System: Ubuntu 14.04.4 LTS (GNU/Linux 3.19.0-68-generic x86_64)

Installed version of CUDA and cuDNN: CUDA 7.5, cuDNN v4 (`cudnn-7.0-linux-x64-v4.0`)
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
```
$ ls -l /usr/local/cuda/lib/libcud*
-rw-r--r-- 1 root root 189170 Jul 25 11:00 /usr/local/cuda/lib/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Jul 25 11:00 /usr/local/cuda/lib/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Jul 25 11:00 /usr/local/cuda/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 311596 Jul 25 11:00 /usr/local/cuda/lib/libcudart.so.7.5.18
-rw-r--r-- 1 root root 558020 Jul 25 11:00 /usr/local/cuda/lib/libcudart_static.a
```

1. A link to the pip package you installed: `https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0-cp27-none-linux_x86_64.whl`
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
```
$ python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
0.10.0
```

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
```
$ python -m tensorflow.models.image.mnist.convolutional
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Extracting data/train-images-idx3-ubyte.gz
Extracting data/train-labels-idx1-ubyte.gz
Extracting data/t10k-images-idx3-ubyte.gz
Extracting data/t10k-labels-idx1-ubyte.gz
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:925] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties:
name: GRID K2
major: 3 minor: 0 memoryClockRate (GHz) 0.745
pciBusID 0000:00:04.0
Total memory: 3.44GiB
Free memory: 3.41GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GRID K2, pci bus id: 0000:00:04.0)
Initialized!
E tensorflow/stream_executor/cuda/cuda_dnn.cc:347] Loaded runtime CuDNN library: 4007 (compatibility version 4000) but source was compiled with 5103 (compatibility version 5100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
F tensorflow/core/kernels/conv_ops.cc:457] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms)
Aborted (core dumped)
```

**Comment by tatatodd** [comment]
Thanks for the report @jakubsimanek!  Note that we haven't officially released 0.10 yet (we're still shaking out issues like this one), but it's always good to notice and fix these things.

In fact #4236 just went in yesterday to fix this up.  If you notice any other problems, please don't hesitate to file more issues!

**Comment by vinaynath** [comment]
Just wanted to point out further, its **CuDNN v5.1 for CUDA toolkit 7.5 (cudnn-7.5-linux-x64-v5.1.tgz)** that solves the problem. cudnn-8.0-linux-x64-v5.1 should be used if you have CUDA toolkit 8.0

**Comment by vsoto** [comment]
Won't work for me, I just installed CUDA 8.0 with CuDNN v5.1 and this is the output I get. Any ideas?

`sudo python /usr/local/lib/python2.7/dist-packages/tensorflow/models/image/mnist/convolutional.py
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting data/train-images-idx3-ubyte.gz
Extracting data/train-labels-idx1-ubyte.gz
Extracting data/t10k-images-idx3-ubyte.gz
Extracting data/t10k-labels-idx1-ubyte.gz
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:04:00.0
Total memory: 11.17GiB
Free memory: 11.11GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:590] creating context when one is currently active; existing: 0x35484f0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 1 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:05:00.0
Total memory: 11.17GiB
Free memory: 11.11GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 1 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 1:   Y Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:04:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla K80, pci bus id: 0000:05:00.0)
Initialized!
E tensorflow/stream_executor/cuda/cuda_dnn.cc:378] Loaded runtime CuDNN library: 5005 (compatibility version 5000) but source was compiled with 5105 (compatibility version 5100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
F tensorflow/core/kernels/conv_ops.cc:532] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms) 
`

**Comment by hsiaoyi0504** [comment]
I have similar problems

**Comment by vsoto** [comment]
I fixed it installing everything from sources:

https://www.tensorflow.org/versions/r0.12/get_started/os_setup.html#installing-from-sources <https://www.tensorflow.org/versions/r0.12/get_started/os_setup.html#installing-from-sources>

**Comment by brando90** [comment]
I don't know if this is the right place to ask but can someone explain to me what the error is even say so that I can start to try to debug this?

In particular I would like to start with the first line:

```
E tensorflow/stream_executor/cuda/cuda_dnn.cc:347] Loaded runtime CuDNN library: 4007 (compatibility version 4000) but source was compiled with 5103 (compatibility version 5100).
```

**Comment by jakubsimanek** [comment]
@brando90 you probably have a wrong version (v4) of cuDNN installed. If you are using the [pip installation](https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#pip-installation), be sure you meet the requirements (versions 0.10-0.12 require CuDNN v5)

**Comment by zdx3578** [comment]
use tensorflow 0.9  i am ok.

**Comment by yuvval** [comment]
In my case (with TF0.12.1) CuDNNv5 was installed, but was not the default.
setting  `export LD_LIBRARY_PATH="/usr/local/lib/cuda-8.0/lib64:/usr/local/lib/cudann5/lib64/"` solved the issue

**Comment by wjiangcmu** [comment]
Thanks to @yuanbyu. If you installed CuDNN v5.1 and confirmed with `ls -l /usr/local/cuda/lib64/libcud*`, but still see the same issue, it is probably what @yuanbyu described.
