### ISSUE TITLE
Lite: Hello world, Sparkfun Edge

### ISSUE THREAD

**Issue by taunoe** [tensorflow/tensorflow#42517]
@tensorflow/micro

**System information**
- Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): git clone https://github.com/tensorflow/tensorflow.git
- Tensorflow version (commit SHA if source): commit 6787ce30efdfefbf69681ca9795959fb7244240b
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Sparkfun Edge

**Describe the problem**
Hello world example: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/hello_world

**Please provide the exact sequence of commands/steps when you ran into the problem**
$ make -f tensorflow/lite/micro/tools/make/Makefile TARGET=sparkfun_edge hello_world_bin
tensorflow/lite/micro/tools/make/Makefile:303: warning: overriding recipe for target 'tensorflow/lite/micro/tools/make/downloads/ruy'
tensorflow/lite/micro/tools/make/Makefile:303: warning: ignoring old recipe for target 'tensorflow/lite/micro/tools/make/downloads/ruy'
tensorflow/lite/micro/tools/make/Makefile:303: warning: overriding recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_grayscale'
tensorflow/lite/micro/tools/make/Makefile:303: warning: ignoring old recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_grayscale'
tensorflow/lite/micro/tools/make/Makefile:303: warning: overriding recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
tensorflow/lite/micro/tools/make/Makefile:303: warning: ignoring old recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
tensorflow/lite/micro/tools/make/downloads/gcc_embedded/bin/arm-none-eabi-g++ -std=c++11 -Wstrict-aliasing -DTF_LITE_STATIC_MEMORY -Werror -Wsign-compare -Wdouble-promotion -Wshadow -Wunused-variable -Wmissing-field-initializers -Wunused-function -DNDEBUG -O3 -DPART_apollo3 -DAM_PACKAGE_BGA -DAM_PART_APOLLO3 -DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK -DTF_LITE_STATIC_MEMORY -DNDEBUG -DTF_LITE_MCU_DEBUG_LOG -D __FPU_PRESENT=1 -DARM_MATH_CM4 -fno-rtti -fmessage-length=0 -fno-exceptions -fno-unwind-tables -ffunction-sections -fdata-sections -funsigned-char -MMD -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -std=gnu++11 -Wvla -Wall -Wextra -Wno-missing-field-initializers -Wno-strict-aliasing -Wno-type-limits -Wno-unused-function -Wno-unused-parameter -fno-delete-null-pointer-checks -fno-threadsafe-statics -fomit-frame-pointer -fno-use-cxa-atexit -nostdlib -ggdb -O3 -I. -Itensorflow/lite/micro/tools/make/downloads/ -Itensorflow/lite/micro/tools/make/downloads/gemmlowp -Itensorflow/lite/micro/tools/make/downloads/flatbuffers/include -Itensorflow/lite/micro/tools/make/downloads/ruy -Itensorflow/lite/micro/tools/make/downloads/AmbiqSuite-Rel2.2.0/boards_sfe/common/third_party/hm01b0 -isystemtensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/Core/Include/ -isystemtensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/DSP/Include/ -Itensorflow/lite/micro/tools/make/downloads/gcc_embedded//arm-none-eabi/ -Itensorflow/lite/micro/tools/make/downloads/AmbiqSuite-Rel2.2.0/mcu/apollo3/ -Itensorflow/lite/micro/tools/make/downloads/AmbiqSuite-Rel2.2.0/mcu/apollo3/regs -Itensorflow/lite/micro/tools/make/downloads/AmbiqSuite-Rel2.2.0/mcu/apollo3/hal -Itensorflow/lite/micro/tools/make/downloads/AmbiqSuite-Rel2.2.0/CMSIS/AmbiqMicro/Include/ -Itensorflow/lite/micro/tools/make/downloads/AmbiqSuite-Rel2.2.0/boards_sfe/edge/bsp -Itensorflow/lite/micro/tools/make/downloads/AmbiqSuite-Rel2.2.0/devices/ -Itensorflow/lite/micro/tools/make/downloads/AmbiqSuite-Rel2.2.0/utils/  -Itensorflow/lite/micro/tools/make/downloads/AmbiqSuite-Rel2.2.0/boards_sfe/common/third_party/lis2dh12/ -Itensorflow/lite/micro/tools/make/downloads/kissfft -c tensorflow/lite/micro/examples/hello_world/sparkfun_edge/output_handler.cc -o tensorflow/lite/micro/tools/make/gen/sparkfun_edge_cortex-m4/obj/tensorflow/lite/micro/examples/hello_world/sparkfun_edge/output_handler.o
tensorflow/lite/micro/examples/hello_world/sparkfun_edge/output_handler.cc: In function 'void HandleOutput(tflite::ErrorReporter*, float, float)':
tensorflow/lite/micro/examples/hello_world/sparkfun_edge/output_handler.cc:58:17: error: implicit conversion from 'float' to 'double' to match other operand of binary expression [-Werror=double-promotion]
     if (y_value <= -0.75) {
         ~~~~~~~~^~~~~~~~
tensorflow/lite/micro/examples/hello_world/sparkfun_edge/output_handler.cc:71:17: error: implicit conversion from 'float' to 'double' to match other operand of binary expression [-Werror=double-promotion]
     if (y_value >= 0.75) {
         ~~~~~~~~^~~~~~~
In file included from ./tensorflow/lite/micro/micro_error_reporter.h:20:0,
                 from ./tensorflow/lite/micro/examples/hello_world/output_handler.h:20,
                 from tensorflow/lite/micro/examples/hello_world/sparkfun_edge/output_handler.cc:16:
./tensorflow/lite/core/api/error_reporter.h:53:70: error: implicit conversion from 'float' to 'double' when passing argument to function [-Werror=double-promotion]
     static_cast<tflite::ErrorReporter*>(reporter)->Report(__VA_ARGS__); \
                                                                      ^
tensorflow/lite/micro/examples/hello_world/sparkfun_edge/output_handler.cc:78:3: note: in expansion of macro 'TF_LITE_REPORT_ERROR'
   TF_LITE_REPORT_ERROR(error_reporter, "x_value: %f, y_value: %f\n", x_value,
   ^~~~~~~~~~~~~~~~~~~~
./tensorflow/lite/core/api/error_reporter.h:53:70: error: implicit conversion from 'float' to 'double' when passing argument to function [-Werror=double-promotion]
     static_cast<tflite::ErrorReporter*>(reporter)->Report(__VA_ARGS__); \
                                                                      ^
tensorflow/lite/micro/examples/hello_world/sparkfun_edge/output_handler.cc:78:3: note: in expansion of macro 'TF_LITE_REPORT_ERROR'
   TF_LITE_REPORT_ERROR(error_reporter, "x_value: %f, y_value: %f\n", x_value,
   ^~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [tensorflow/lite/micro/tools/make/Makefile:315: tensorflow/lite/micro/tools/make/gen/sparkfun_edge_cortex-m4/obj/tensorflow/lite/micro/examples/hello_world/sparkfun_edge/output_handler.o] Error 1

**Comment by advaitjain** [comment]
@taunoe: This PR should fix the issue that you reported.

**Comment by taunoe** [comment]
I tested this fix and it works. Thank You.
