### ISSUE TITLE
ReduceLROnPlateau not logging LR to tensorboard anymore

### ISSUE THREAD

**Issue by lminer** [tensorflow/tensorflow#42520]
I use the `ReduceLROnPlateau` callback and LR used to be logged to tensorboard. However since 2.3.0 it isn't showing up anymore. I tried to find a change that may explain the issue, but can't find anything. Was this some deliberate change?

**Comment by ravikyram** [comment]
@lminer 

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
Please, share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!
