### ISSUE TITLE
Low performance of Object Detection Models in Coral Dev Board

### ISSUE THREAD

**Issue by IvanChavR** [tensorflow/tensorflow#42534]
Hi 

Recently my company bought a Coral Board Dev and  Coral USB Accelerator to detect some objects in outdoor environment.

We have tried to train MobileNet V1 and V2 using TPU on the Cloud, as well using GPU RT2070 and finally we have implemented other models such as Inception Lite and Tiny Yolo V3 but the results are no good according the accuracy during the performance. 

For this reason, I would like to know what else could be done to improve this model in real Object detection in Coral edge device?

**Comment by ravikyram** [comment]
@IvanChavR 

Provide the exact sequence of commands / steps that you executed before running into the problem.

Thanks!
