### ISSUE TITLE
Tensorflow V2.2.0 boot fail on aarch64

### ISSUE THREAD

**Issue by darmac** [tensorflow/tensorflow#42545]
When I run a testcase on my `aarch64` platform, it reports error as:
```
tensorflow/core/platform/profile_utils/cpu_utils.cc:106] Failed to find bogomips or clock in /proc/cpuinfo; cannot determine CPU frequency
```

And I found `core/platform/profile_utils/cpu_utils.cc` not support `aarch64` yet as follows:
```
#if (defined(__powerpc__) || \
     defined(__ppc__) && (__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__))
    retval = sscanf(line.c_str(), "clock              : %lfMHz", &cpu_freq);
    freq_factor = 1.0;
#else
    retval = sscanf(line.c_str(), "bogomips : %lf", &cpu_freq);
#endif
    if (retval > 0) {
      const double freq_ghz = cpu_freq / 1000.0 / freq_factor;
      if (retval != 1 || freq_ghz < 0.01) {
        LOG(WARNING) << "Failed to get CPU frequency: " << freq_ghz << " GHz";
        return INVALID_FREQUENCY;
      }
      const int64 freq_n =
          static_cast<int64>(freq_ghz * 1000.0 * 1000.0 * 1000.0);
      LOG(INFO) << "CPU Frequency: " << freq_n << " Hz";
      return freq_n;
    }
  }
  LOG(WARNING)
      << "Failed to find bogomips or clock in /proc/cpuinfo; cannot determine "
         "CPU frequency";
  return INVALID_FREQUENCY;
```

But my `proc/cpuinfo` is
```
BogoMIPS        : xxx.xx
```
which not match `bogomips : %lf`

Could anyone help to fix this issue?

**Comment by amahendrakar** [comment]
@darmac,
A similar issue [#39185](https://github.com/tensorflow/tensorflow/issues/39185), was fixed in TensorFlow v2.3. Could you please update TensorFlow to v2.3 and check if you are facing the same issue?

Also, please provide the exact sequence of commands or the code that you executed before running into the error? Thanks!

**Comment by darmac** [comment]
Got it, I have not test the latest version yet. Thanks.

**Comment by darmac** [comment]
Got it.

**Comment by amahendrakar** [comment]
> Got it, I have not test the latest version yet. Thanks.

@darmac,
In this case, can we close the issue. Please feel free to re-open the issue when you have updates regarding it. Thanks!
