### ISSUE TITLE
[Estimator] bazel test failures

### ISSUE THREAD

**Issue by satishpasumarthi** [tensorflow/tensorflow#42544]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version: r2.3
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.2/7
- GPU model and memory:

**Describe the problem**
Estimator bazel test failures
**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel test //tensorflow_estimator/... --test_output=errors --verbose_failures=true
  --keep_going --test_verbose_timeout_warnings

**Any other info / logs**
//tensorflow_estimator/python/estimator:rnn_test                         FAILED in 197.2s
//tensorflow_estimator/python/estimator:distribute_strategy_estimator_training_test FAILED in 48 out of 48 in 13.4s
//tensorflow_estimator/python/estimator:distribute_strategy_estimator_training_test_gpu FAILED in 48 out of 48 in 10.1s

-------------------------------------------------------------------
rnn_test failues:
[  FAILED  ] RNNClassifierEvaluationTest.testMultiClassEvaluationMetrics
[  FAILED  ] RNNClassifierPredictionTest.testBinaryClassPredictions
[  FAILED  ] RNNClassifierPredictionTest.testBinaryClassPredictionsSequential
[  FAILED  ] RNNClassifierPredictionTest.testMultiClassPredictions
[  FAILED  ] RNNClassifierTrainingTest.testBinaryClassFromCheckpoint
[  FAILED  ] RNNClassifierTrainingTest.testBinaryClassFromCheckpointSequential
[  FAILED  ] RNNClassifierTrainingTest.testBinaryClassFromCheckpointSequentialWithWeights
[  FAILED  ] RNNClassifierTrainingTest.testBinaryClassFromScratchWithDefaultOptimizer
[  FAILED  ] RNNClassifierTrainingTest.testBinaryClassWithExampleWeight
[  FAILED  ] RNNClassifierTrainingTest.testDefaultGradientClipping
[  FAILED  ] RNNClassifierTrainingTest.testFromScratchWithCustomRNNCellFn
[  FAILED  ] RNNClassifierTrainingTest.testMultiClassFromCheckpoint
[  FAILED  ] RNNClassifierTrainingTest.testMultiClassFromScratchWithDefaultOptimizer
[  FAILED  ] RNNClassifierTrainingTest.testMultiClassWithExampleWeight
[  FAILED  ] RNNLogitFnTest.testMultiDimLogitsSequential
[  FAILED  ] RNNLogitFnTest.testMultiDimLogitsStatic
[  FAILED  ] RNNLogitFnTest.testOneDimLogitsSequential
[  FAILED  ] RNNLogitFnTest.testOneDimLogitsSequentialInfer
[  FAILED  ] RNNLogitFnTest.testOneDimLogitsSequentialTrain
[  FAILED  ] RNNLogitFnTest.testOneDimLogitsStatic
[  FAILED  ] RNNLogitFnTest.testTrainingMode('train', True)
[  FAILED  ] RNNLogitFnTest.testTrainingMode('eval', False)
[  FAILED  ] RNNLogitFnTest.testTrainingMode('infer', False)

More details on testOneDimLogitsSequentialTrain failure
======================================================================
ERROR: testOneDimLogitsSequentialTrain (__main__.RNNLogitFnTest)
testOneDimLogitsSequentialTrain (__main__.RNNLogitFnTest)
testOneDimLogitsSequentialTrain(return_sequences=True, expected_logits=[[[-1.4388], [-0.6033]]], training=True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/test_util.py", line 1178, in decorated
    f(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/absl/testing/parameterized.py", line 263, in bound_param_test
    test_method(self, **testcase_params)
  File "/root/.cache/bazel/_bazel_root/d226403c339549ea2db666353bf31144/sandbox/processwrapper-sandbox/902/execroot/org_tensorflow_estimator/bazel-out/k8-fastbuild/bin/tensorflow_estimator/python/estimator/rnn_test.runfiles/org_tensorflow_estimator/tensorflow_estimator/python/estimator/canned/rnn_test.py", line 325, in testOneDimLogits
    training=training)
  File "/root/.cache/bazel/_bazel_root/d226403c339549ea2db666353bf31144/sandbox/processwrapper-sandbox/902/execroot/org_tensorflow_estimator/bazel-out/k8-fastbuild/bin/tensorflow_estimator/python/estimator/rnn_test.runfiles/org_tensorflow_estimator/tensorflow_estimator/python/estimator/canned/rnn_test.py", line 268, in _test_logits
    logits = logit_layer(features_fn(), training=training)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 776, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py", line 258, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /root/.cache/bazel/_bazel_root/d226403c339549ea2db666353bf31144/sandbox/processwrapper-sandbox/902/execroot/org_tensorflow_estimator/bazel-out/k8-fastbuild/bin/tensorflow_estimator/python/estimator/rnn_test.runfiles/org_tensorflow_estimator/tensorflow_estimator/python/estimator/canned/rnn.py:221 call  *
        rnn_outputs = self._rnn_layer(
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/recurrent.py:663 __call__  **
        return super(RNN, self).__call__(inputs, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:776 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/recurrent.py:1573 call
        inputs, mask=mask, training=training, initial_state=initial_state)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/recurrent.py:807 call
        zero_output_for_mask=self.zero_output_for_mask)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/backend.py:4327 rnn
        **while_loop_kwargs)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/control_flow_ops.py:2696 while_loop
        back_prop=back_prop)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/while_v2.py:229 while_loop
        len_orig_loop_vars], expand_composites=True))
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/while_v2.py:1151 _check_shapes_compat
        "specify a less-specific shape." % (input_t.name, shape, t.shape))

    ValueError: Input tensor 'rnn_model/simple_rnn/zeros_like:0' enters the loop with shape (1, 2), but has shape (None, 2) after one iteration. To allow the shape to vary across iterations, use the `shape_invariants` argument of tf.while_loop to specify a less-specific shape.
-------------------------------------------------------------------------
The distribute_strategy_estimator_training_test.* failed with the below error in the logs.
[  FAILED  ] setUpClass (__main__.DistributeCoordinatorIntegrationTest)
We tried to use portpicker but ran into segmentation failures.
-------------------------------------------------------------------

**Comment by satishpasumarthi** [comment]
sure @Saduf2019 . let me get that info.

**Comment by Saduf2019** [comment]
@satishpasumarthi
Please update.
