### ISSUE TITLE
Mixed precision training on TensorFlow 2.3 doesn't speed-up training progress as TensorFlow 2.2 does

### ISSUE THREAD

**Issue by dathudeptrai** [tensorflow/tensorflow#42546]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0/2.3.0
- Python version: 3.6/3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: Cuda 10.1, cuDNN 7.6.5
- GPU model and memory: 2080Ti/12Gb

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Mixed precision training on tensorflow 2.3 doesn't speed-up training progress as Tensorflow 2.2 does 

**Describe the expected behavior**

faster or at least equal

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

[nmt_with_attention.zip](https://github.com/tensorflow/tensorflow/files/5106684/nmt_with_attention.zip)

I modify a bit based on tensorflow offcial tutorial nmt here (https://www.tensorflow.org/tutorials/text/nmt_with_attention). You can see the flag `IS_MIXED_PRECISION` in the head of the notebook, let change it to True/False to check by urself.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

[log.txt](https://github.com/tensorflow/tensorflow/files/5106690/log.txt)

here is my summary about the time consuming for tensorflow2.2/2.3 on both mixex precision and non-mixed precision.

I have many model on my framework TensorFlowTTS (https://github.com/TensorSpeech/TensorFlowTTS). All of my model training on mixed precsion Tensorflow2.3 have this problem. The above notebook is just example. 

BTW, colab gpu haven't support mixed precision so to run this notebook require a local GPU to reproduce my issue.

**Comment by dathudeptrai** [comment]
@reedwm seem you are the person working on mixed precision :)).

**Comment by bibzzzz** [comment]
what's the latest on this issue?
