### ISSUE TITLE
Tensorflow Lite python interpreter for armv6

### ISSUE THREAD

**Issue by olimexsmart** [tensorflow/tensorflow#42550]
Very simple question:

I'd like to install the Lite python interpreter ([https://www.tensorflow.org/lite/guide/python](https://www.tensorflow.org/lite/guide/python)) on an old RaspberryPi, that has an armv6.

At that page there is a list of downloadable Python wheels, but there is not the right one for my Pi, in fact, there are none for armv6. 

Ideally I would need: armv6, Py3.7, Tensorflow version 2.3 (actually I don't if version match between TF and TF Lite)

What should I do?

Thanks, have a great day

**Comment by olimexsmart** [comment]
I'd like to add that, more confusingly, there is a [pip package](https://pypi.org/project/tflite/) by @jackwish named 'tflite' which i'm not sure what really does and how it relates to the "official" TF Lite parser

**Comment by olimexsmart** [comment]
[Relevant SO question with no answer](https://stackoverflow.com/questions/62749168/modulenotfounderror-no-module-named-tflite-runtime)

**Comment by ymodak** [comment]
You may try building your own tf lite pip package using this [guide](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package).
