### ISSUE TITLE
Bazel fixes for other toolchains should be global

### ISSUE THREAD

**Issue by surak** [tensorflow/tensorflow#42561]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Redhat 7
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.15.3+nv20.07
- Python version: 3.8.5
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source):9.3.0
- CUDA/cuDNN version:Cuda 11.0.207 cuDNN 8.0.1.13
- GPU model and memory: Nvidia A100

**Describe the current behavior**
```
(...)  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -shared -o bazel-out/k8-py2-opt/bin/tensorflow/python/_tf_stack.so '-Wl,-rpath,$ORIGIN/,-rpath,$ORIGIN/..' -Wl,--version-script bazel-out/k8-py2-opt/bin/tensorflow/python/_tf_stack-version-script.lds -Wl,-no-as-needed -Wl,-z,relro,-z,now '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -no-canonical-prefixes -fno-canonical-system-headers -B/usr/bin -Wl,--gc-sections -Wl,@bazel-out/k8-py2-opt/bin/tensorflow/python/_tf_stack.so-2.params)
Execution platform: @bazel_tools//platforms:host_platform
/usr/bin/ld.gold: --push-state: unknown option
/usr/bin/ld.gold: use the --help option for usage information
collect2: error: ld returned 1 exit status
```

**Describe the expected behavior**
Fixed ld.gold versions work

**Code to reproduce the issue**
Compile with standard Redhat's GCC

**Other info / logs**
You describe the issue yourself here: https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/cuda_configure.bzl#L1192

But that does not help with other toolchains other than your own. So the solution is to use a properly patched libtool, and remove the hardcoded path to /usr/bin. The fine gentlemen of the EasyBuild project have a patch that does exactly this: https://github.com/easybuilders/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.13.1_remove_usrbin_from_linker_bin_path_flag.patch

**Comment by amahendrakar** [comment]
@surak,
Could you please provide the exact sequence of commands / steps that you executed before running into the problem? Thanks!

**Comment by surak** [comment]
Did you read the other bug fix referenced above? 

I'm talking about this one: https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/cuda_configure.bzl#L1192

Your fix is: either use whatever bazel gives, or, when it's clang, use this thing. But the problem appears in any system where the standard toolchain is not used.

**Comment by mihaimaruseac** [comment]
Can you send a PR please?

**Comment by mihaimaruseac** [comment]
This likely is a bazel issue anyway

**Comment by surak** [comment]
It seems that a patch exists, using host_compiler_prefix
