### ISSUE TITLE
Kohonen SOM

### ISSUE THREAD

**Issue by sandorvasas** [tensorflow/tensorflow#42565]
Just wondering how come there is no "factory" implementation of Kohonen SOM in Tensorflow? Or is there? Is it planned to include it in next releases?

**Comment by mihaimaruseac** [comment]
TF is a library providing the minimum things needed to implement ML models. We cannot incorporate everything as that would result in huge packages and a lot of pieces of code that will no longer be maintained.

You can implement self organizing maps using Keras layers. Or, see https://github.com/cgorman/tensorflow-som Alternatively, you can try to look in https://github.com/tensorflow/addons or add an implementation there
