### ISSUE TITLE
Bandwidth on TPU v3 > 900 GB/s

### ISSUE THREAD

**Issue by shz0116** [tensorflow/tensorflow#42566]
I've testing the performance of EmbeddingTPU on GCP TPU v3-8. I found that the computed memory access
bandwidth is beyond > 900 GB/s when using one core (900 GB/s is the theoretical upper bound). I think this may be
a tensorflow bug. The test code is developed in Python interface.

Here is the code TGTBT.py and the tf_env.txt (file is too big to put here, collected using tf_env_collect.sh).
https://github.com/shz0116/testTF/blob/master/TGTBT.py
https://github.com/shz0116/testTF/blob/master/tf_env.txt

The run command and output is listed at the top of TGTBT.py file. It's pretty simple.

~$ python3 -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
v1.12.1-34769-gfd2d4cdb70 2.3.0-dev20200620

**Describe the current behavior**
We see the computed memory bandwidth for one TPU v3 core is > 900 GB/s.
 
**Describe the expected behavior**
We expect the bandwidth number is below 900 GB/s.

**Standalone code to reproduce the issue**
See above.

Update: I found that if I add a statement res.numpy() into the timer, the performance will change from too good (> 900 GB/s) to too bad (1.4 GB/s).

**Comment by nikitamaia** [comment]
Hi @shz0116, when you say bandwidth is beyond > 900 GB/s, what is the number you calculated? Trying to understand how much larger than 900. Additionally, can you explain how you did this calculation? I see in your script that your calculation for `total_bytes` depends on command line arguments, and I'm wondering what those numbers were. Additionally can you explain what `em` and `nnz` are?

**Comment by shz0116** [comment]
This is for table lookup. Suppose you have a 2D table or matrix, T[features=1000000, em=128] datatype=float32. 
 Each time (or call batch), we search nnz rows and compute the sum across the columns. The row id is generated by random.
Now we have a sum vector with size [em=128].  Here we repeat the search 65536 times.
So, finally we have a results matrix R[batch=65536, em=128].  

During this process, we read from the matrix (or memory) total_bytes data. So the memory bandwidth is total_bytes/Time.
It should be less than theoretical memory bandwidth. By the way, TPU have cache or not like CPU cache ?

Hope this helps. Just let me know if you have any question.

**Comment by nikitamaia** [comment]
What was the result of the calculation you did? You mentioned it was larger than 900, But what was the actual number?

**Comment by shz0116** [comment]
1683.631 GB/s
The line 10 in file https://github.com/shz0116/testTF/blob/master/TGTBT.py.

**Comment by nikitamaia** [comment]
Can you point to where you found the upper bound to be 900 GB/s ?

**Comment by shz0116** [comment]
https://cacm.acm.org/magazines/2020/7/245702-a-domain-specific-supercomputer-for-training-deep-neural-networks/fulltext
Did you find anything wrong with my code ?

**Comment by nikitamaia** [comment]
Thanks for sharing that link. Although I couldn't find the 900GB/s noted there specifically. I don't think there's any bug here since it's not possible for the bandwidth to be higher than the maximum bandwidth. It seems that if your calculation is correct than the upper limit for bandwidth is > 900 GB/s.

**Comment by shz0116** [comment]
Look at "Table 3. Key processor features." Row : Memory GBs/Chip.

I think we are lacking a reasonable explanation why BW > 900 GB/s the theoretical peak if not a bug.
Do you know whether TPUEMbedding implementation using multiple threading or other parallel data access ?

**Comment by nikitamaia** [comment]
I think in this case it would be worth contacting the authors of that link you provided to understand how they measured the 900GB/s. It doesn't make sense for the BW to be higher than the limit, so either the limit is greater than 900 or your calculation is incorrect. Either way, I think the best next step is to contact the authors to better understand how they got the 900GB/s number.
