### ISSUE TITLE
'retval_' must have the same nested structure in the main and else branches

### ISSUE THREAD

**Issue by SmileTM** [tensorflow/tensorflow#42575]
Tensorflow=2.3
python=3.7

I want to control the running process of call() through ‘mode’. but when the number of returned tensors is inconsistent, an error will be prompted. How can I fix this error?

My goal is to deploy the saved model to tensorflow serving.

```python
class MLP(tf.keras.Model):
    def __init__(self, **kwargs):
        super(MLP, self).__init__(**kwargs)
        self.dense = tf.keras.layers.Dense(1)
    @tf.function
    def call(self, inputs):
        a, b, mode = inputs
        if mode == 'predict':
            return a
        
        return self.dense(a + b),b
```
```python
if __name__ == '__main__':
    a = tf.ones((2, 10))
    b = tf.ones((2, 10))
    mode = 'train'
    mode = tf.cast(mode, tf.string)
    model = MLP()
    print(model((a, b, mode)))
    model.save('test_model/1/')
```

errors:
```python
    TypeError: 'retval_' must have the same nested structure in the main and else branches:
    
    The two structures don't have the same nested structure.
    
    First structure: type=Tensor str=Tensor("inputs:0", shape=(2, 10), dtype=float32)
    
    Second structure: type=tuple str=(<tf.Tensor 'cond/dense/BiasAdd:0' shape=(2, 1) dtype=float32>, <tf.Tensor 'inputs_1:0' shape=(2, 10) dtype=float32>)
    
    More specifically: Substructure "type=tuple str=(<tf.Tensor 'cond/dense/BiasAdd:0' shape=(2, 1) dtype=float32>, <tf.Tensor 'inputs_1:0' shape=(2, 10) dtype=float32>)" is a sequence, while substructure "type=Tensor str=Tensor("inputs:0", shape=(2, 10), dtype=float32)" is not
    Entire first structure:
    .
    Entire second structure:
    (., .)


```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/020a87afbf540510aad43bee183ebca8/42575.ipynb). Thanks!

**Comment by nikitamaia** [comment]
Hi @SmileTM, when you subclass Model, you can optionally have a training argument (boolean) in your call method, which you can use to specify different behavior in training and inference. Example:

```
class MLP(tf.keras.Model):
    def __init__(self, **kwargs):
        super(MLP, self).__init__(**kwargs)
        self.dense = tf.keras.layers.Dense(1)
    
    @tf.function
    def call(self, inputs, training):
        a, b = inputs
        if training:
          return self.dense(a + b),b
        else:
          return a
```

Then you'll get different behavior in the following two scenarios:

`print(model((a, b),training=True))`
`print(model((a, b),training=False))`

Hope this helps!

**Comment by SmileTM** [comment]
@nikitamaia 
Yes, this method works well in normal training, inference  and save model.
 But when I deployed the model by using docker tensorflow/serving , it cannot control output by using `training=False`

```python 
saved_model_cli show --dir  test_model/1/  --all
```
the model info:
```python
signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input_1'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 10)
        name: serving_default_input_1:0
    inputs['input_2'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 10)
        name: serving_default_input_2:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output_1'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 10)
        name: PartitionedCall:0
  Method name is: tensorflow/serving/predict
```

```bash
curl -d '{"inputs": {"input_1":[[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]],"input_2":[[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]]},"training":false}' -X POST http://localhost:8501/v1/models/test_model:predict
```
just return `a` . The `"training":false` not work.

**Comment by nikitamaia** [comment]
Ah I see. Presumably you would only ever want training to be False when you're serving the model, then you can just set the default value for training=False like so:

```
    def call(self, inputs, training=False):
        a, b = inputs
        if training:
          return self.dense(a + b),b
        else:
          return a
```

This should give you the desired behavior in when serving without having to pass in an extra argument, and then you could pass training=True in your training environment. Does that work?

**Comment by SmileTM** [comment]
> Ah I see. Presumably you would only ever want training to be False when you're serving the model, then you can just set the default value for training=False like so:
> 
> ```
>     def call(self, inputs, training=False):
>         a, b = inputs
>         if training:
>           return self.dense(a + b),b
>         else:
>           return a
> ```
> 
> This should give you the desired behavior in when serving without having to pass in an extra argument, and then you could pass training=True in your training environment. Does that work?

this still not work.

**Comment by nikitamaia** [comment]
Please provide more information on why that did not work. Is there an error message or stack trace you can provide?

**Comment by SmileTM** [comment]
the model info still just one   `outputs['output_1']`.

```python
signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input_1'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 10)
        name: serving_default_input_1:0
    inputs['input_2'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 10)
        name: serving_default_input_2:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output_1'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 10)
        name: PartitionedCall:0
  Method name is: tensorflow/serving/predict
```

No matter how I input "train", I cannot control the output of the model.
The output format seems to be fixed when I save the model.
**The training process is ok.** 
**But** if the model `.pb` file is deployed in tensorflow/serving, the output cannot be controlled by train=‘true’ or train=‘false’.
Sometimes I need the outputs of train=‘false’, sometimes I need the outputs of train=‘true’. like the `MLP()`
It seems that the `.pb` file does not save the logical branch structure.
emmm, I suggest you try to deploy the .pb file to tensorflow/serving, and then request the service through curl. Then you will understand my question.

**Comment by gowthamkpr** [comment]
@SmileTM This issue is related to tensorflow serving not tensorflow. Please post this issue [here](https://github.com/tensorflow/serving/issues) and close this issue here. Thanks!
