### ISSUE TITLE
Move all model implementations to tensorflow/models ?

### ISSUE THREAD

**Issue by keonkim** [tensorflow/tensorflow#4257]
If I am correct, tensorflow.models is being deprecated.
But some model implementations are still kept inside this directory because of tensorflow tutorials. 
I think it would be more straight forward and relevant to keep all the model implementations in tensorflow/models repository.

(This is a same issue discussed in [tensorflow/models issue 361](https://github.com/tensorflow/models/issues/361).)

I made a [pull request](https://github.com/tensorflow/models/pull/393) that moves all tensorflow/tensorflow model implementations to tensorflow/models without losing commit histories.

I can make another pull request to tensorflow/tensorflow to fully deprecate the model implementations and update tutorials.

**Comment by tatatodd** [comment]
I'll let @martinwicke comment on this.

**Comment by martinwicke** [comment]
This is the right thing to do. We need to update the docs though, and our website. Maybe we can do that here, but I'm not sure. @wolffg @random-forests @dr4b what do you think? Kick start our tutorials/docs reorg?

**Comment by gunan** [comment]
@nealwu Is this all complete?
Did we also update the docs?

**Comment by nealwu** [comment]
Yep, this is complete. The models are now in https://github.com/tensorflow/models/tree/master/tutorials. The docs are also mostly updated, but I'm still working on a few issues with them now.
