### ISSUE TITLE
[IOS TfLite] Missing Operations for TfLite GPU Delegate

### ISSUE THREAD

**Issue by terminate25** [tensorflow/tensorflow#42577]
**System information**
In Podfile: TensorFlowLiteSwift', '~> 0.0.1-nightly', :subspecs => ['Metal']
Tensorflow Lite version: 2.3.0
Swift 5
Xcode ver 11.6

**Model information**
The model file is YOLOv4-tiny, training with darknet framework, the config file similar to: 
https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4-tiny-custom.cfg

Convert to model tflite using this following open project sourecode:
https://github.com/hunglc007/tensorflow-yolov4-tflite

**
I'm trying to use the GPU delegate for my custom tflite model, create the interpreter with GPU delegate using this code:

```
var metalOptions = MetalDelegate.Options()
metalOptions.waitType = .passive
let delegate = MetalDelegate(options: metalOptions)
var options = Interpreter.Options()
options.threadCount = threadCount
interpreter = try Interpreter(modelPath: modelPath, options: options,delegates: [delegate])
```
*****
After running, got this error:

```
TensorFlow Lite Error: Following operations are not supported by GPU delegate:
DEQUANTIZE: 
SPLIT: Operation is not supported.
SPLIT_V: Operation is not supported.
106 operations will run on the GPU, and the remaining 100 operations will run on the CPU
```
How can I fix this error?
Thanks.

**Comment by Saduf2019** [comment]
@terminate25 
Could you please provide with complete indented stand alone code for us to replicate the issue faced, or if possible share a colab gist with the issue reported:

Meanwhile you may refer to below issues and let us know f they help:
#40157  #34679 #39746
