### ISSUE TITLE
TF2.3 can't use GPU with CUDA11.0(windows)

### ISSUE THREAD

**Issue by Stealers** [tensorflow/tensorflow#42578]
Do I have to reduce the CUDA version?

**Comment by Stealers** [comment]
@davidfegyver When will it be updated to support cuda11.0？pytorch 1.6 is compatible now, reinstall is a troublesome thing.

**Comment by TheNewSound** [comment]
You can install cuda 10.1 next to cuda 11.0, in a different directory.
Then if you need CUDA you can load the correct version to your PATH and other environment variables

**Comment by amahendrakar** [comment]
@Stealers,
As per the [tested build configurations](https://www.tensorflow.org/install/source_windows#gpu), please check if you are facing the same issue with CUDA 10.1 and cuDNN 7.4.

Also, please take a look at [#42047](https://github.com/tensorflow/tensorflow/issues/42047) for more information regarding TensorFlow support for CUDA 11. Thanks!

**Comment by Stealers** [comment]
@amahendrakar Thanks! using tf_nightly successfully load cuda, but can't use!
```
UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [Op:Conv2D]
```

**Comment by amahendrakar** [comment]
@Stealers,
Could you please provide the complete code and the dataset you are using in order to reproduce the error. Thanks!

**Comment by Stealers** [comment]
@amahendrakar it's very strange!  i was tested in jupyter lab using following code.
```python
import tensorflow as tf
from tensorflow.keras.layers import *

c = Conv2D(12,3,1,padding='same',name='/Conv')
c(tf.ones((1,64,64,3)))
```
**some jupyter notebook successfully run, but some failed.**

**fail:**  
```
UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node model/Head/Conv/Conv2D (defined at <ipython-input-4-71857f6da7f0>:3) ]] [Op:__inference_predict_function_668]
```
**success**  
```
<tf.Tensor: shape=(1, 64, 64, 12), dtype=float32, numpy=
array([[[[ 0.1533156 ,  0.03336769,  0.13701904, ..., -0.53224814,
           0.24510589, -0.28095055],
         [ 0.5889714 ,  0.38427442,  0.16817504, ..., -0.43800074,
           0.25934196,  0.24368674],
         [ 0.5889714 ,  0.38427442,  0.16817504, ..., -0.43800074,
           0.25934196,  0.24368674],
         ...,
```

**Comment by Stealers** [comment]
@amahendrakar The same  jupyter notebook sometimes can run successfully. sometimes it can't, and it uses a lot of memory(both GPU's and common's)

**Comment by amahendrakar** [comment]
> **I found the key. It can‘t be used in multiple notebooks. we can only use tensorflow in one notebook at a time. when the first notebook is created, and uses tensorflow successfully. The next notebook created can't use tensorflow.**
> Is this a bug？

@Stealers,
Could you please check if you are facing the same issue in a virtual environment as well? Thanks!

**Comment by FacundoPinela98** [comment]
I follow this article and solve the problem:
https://medium.com/analytics-vidhya/install-tensorflow-gpu-2-4-0-with-cuda-11-0-and-cudnn-8-using-anaconda-8c6472c9653f
