### ISSUE TITLE
issues with tf.math.reduce_euclidean_norm

### ISSUE THREAD

**Issue by keowang** [tensorflow/tensorflow#42573]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**:
    Yes

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
     macOS Mojave (10.14.5)

-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:
    N/A

-   **TensorFlow installed from (source or binary)**:
    from anaconda

-   **TensorFlow version (use command below)**:
    1.14

-   **Python version**:
     3.7

-   **Bazel version (if compiling from source)**:
     N/A

-   **GCC/Compiler version (if compiling from source)**:
     N/A

-   **CUDA/cuDNN version**:
     No GPU needed

-   **GPU model and memory**:
     N/A
 
-   **Exact command to reproduce**:
     Just run the program

### Describe the problem
tf.math.reduce_euclidean_norm makes the model non-differentiable, I getting the error message ```ValueError: No gradients provided for any variable, check your graph for ops that do not support gradients, between variables ["<tf.Variable 'embedding_matrix:0' shape=(5, 3) dtype=float32_ref>"] and loss Tensor("EuclideanNorm:0", dtype=float32).``` for the following program

```
mport tensorflow as tf

index1 = tf.placeholder(tf.int32, None)
index2 = tf.placeholder(tf.int32, None)

embedding = tf.get_variable('embedding_matrix', [5, 3])

vector1 = tf.nn.embedding_lookup(embedding, index1)
vector2 = tf.nn.embedding_lookup(embedding, index2)

loss = tf.math.reduce_euclidean_norm(vector1-vector2, axis=1)
train_step = tf.train.AdamOptimizer(learning_rate=0.001, beta1=0.9, beta2=0.999).minimize(loss)

with tf.Session() as sess:            
    init = tf.global_variables_initializer()
    sess.run(init)
   
    for i in range(5):
        result = sess.run([loss, train_step], feed_dict={index1:1,index2:0})
        print(result[0])
```

Replace the line

```
loss = tf.math.reduce_euclidean_norm(vector1-vector2, axis=1)
```
with a custom implementation

```
loss = tf.math.sqrt(tf.reduce_sum((vector1-vector2)**2, axis=-1))
```

solves the problem. So we think this is a bug. It would be great if you can take a look or maybe let us know how we may use ```tf.math.reduce_euclidean_norm``` assuming we misused it.

Thanks

**Comment by Saduf2019** [comment]
@keowang 
I ran teh code shared on tf 1.15, as we have support from 1.15 and 2.x, but i face a different error.
Please refer tot he [gist here](https://colab.research.google.com/gist/Saduf2019/4a46b12ec2bd207ef6472fd5be2fa862/untitled388.ipynb)

**Comment by keowang** [comment]
By looking at the last line ```ValueError: No gradients provided for any variable, check your graph for ops that do not support gradients, between variables ["<tf.Variable 'embedding_matrix:0' shape=(5, 3) dtype=float32_ref>"] and loss Tensor("EuclideanNorm:0", dtype=float32).``` I think the error is the same.

**Comment by cantonios** [comment]
The reduction dimension is invalid. It should be `axis=0` since both `vector1` and `vector2` are rank-1 tensors:
```
loss = tf.math.reduce_euclidean_norm(vector1-vector2, axis=0)
```
This now works in the latest version of tensorflow, if you import v1 as
```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```
