### ISSUE TITLE
TensorScatterUpdate unsupported dtype complex64/128, tf2.3.0, GPU

### ISSUE THREAD

**Issue by scarrazza** [tensorflow/tensorflow#42581]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- TensorFlow installed from (source or binary): binary (pip)
- TensorFlow version (use command below): 2.3.0
- Python version: 3.8
- CUDA/cuDNN version: 10.1/10.2
- GPU model and memory: TITAN V, RTX2080TI

**Describe the current behavior**

The `tf.tensor_scatter_nd_update` function raises:

`InvalidArgumentError: Unsupported dtype: complex64 [Op:TensorScatterUpdate]`
`InvalidArgumentError: Unsupported dtype: complex128 [Op:TensorScatterUpdate]`

when running tf2.3.0 on GPU, in eager mode, and using dtypes `complex64` and `complex128`.

You can reproduce this error by executing the following code on GPU with tf2.3.0: 

```python
import tensorflow as tf
var = tf.Variable(tf.zeros(10, dtype=tf.complex64))
up = tf.constant([1], dtype=tf.complex64) 
tf.tensor_scatter_nd_update(var, [[0]], up)
```
Note that the code works as expected if we compile the call with `tf.function`, and it also works fine on CPU.

**Describe the expected behavior**

The `tensor_scatter_nd_update` in tf2.3 should work on GPU if the dtype is complex64 or complex128, as in tf2.2 and tf2.1.

**Comment by Saduf2019** [comment]
@scarrazza 
 ETA depends on lot of factors. But the last release candidate is 2.3rc2. So I guess there will in 2.4 in near future.

**Comment by scarrazza** [comment]
Thanks, anyway I would suggest to include a specific test for this function to avoid similar issues in future releases.

**Comment by Saduf2019** [comment]
@scarrazza
Surely, Can we move this issue to closed status as its resolved.
