### ISSUE TITLE
convert tesnorflow::ops::cast to tensorflow::tensor

### ISSUE THREAD

**Issue by naserpiltan** [tensorflow/tensorflow#42588]
System information

- Have I written custom code :yes 
- OS Platform and Distribution :Linux ubtuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.15
- Python version: 3.6
- Bazel version (if compiling from source): 0.25.0
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: 10.2.89/7.6.5.32
- GPU model and memory: NVidia GTX 1060
- OpenCv 4.4.2

I have written a custom code and trying to read an image with opencv and convert it to a tensorflow::Tensor.
I did it successfully and can do inference on my model but my model gives me a tensor of int64  and now i wanna cast it to a tensor of int32. 

    ` auto root = tensorflow::Scope::NewRootScope();
      Tensor inputImg(tensorflow::DT_UINT8, tensorflow::TensorShape({1, input_height_, input_width_, 3}));
      uint8_t *image1_p_ = inputImg.flat<uint8_t>().data();
      Mat cv_image1_ = cv::Mat(input_height_, input_width_, CV_8UC3, image1_p_);
      Mat image = imread("test_img.jpg");
      cv::Mat resized_img;
      resize(image,resized_img,cv::Size(input_width_,input_height_));
      cvtColor(resized_img,resized_img,COLOR_BGR2RGB);
      resized_img.convertTo(cv_image1_, CV_8UC3);
      std::vector<std::pair<std::string, tensorflow::Tensor>> inputs = {{ "ImageTensor:0", inputImg} };
      std::vector<tensorflow::Tensor> outputs;
      status = session->Run(inputs, {"SemanticPredictions:0"},{}, &outputs);
      if (!status.ok()) {
        std::cout << status.ToString() << "\n";
        return 1;
        }
      auto int64_caster =  Cast(root.WithOpName("int64_caster"), outputs[0], tensorflow::DT_INT32);` 

I searched and found tensorflow **Cast** function. it gives me an tensorflow::opes::cast output  with the name of **int64_caster**
but i don't know how to convert it to tensorflow::tensor object.

**Comment by naserpiltan** [comment]
@Saduf2019  hi and thank you so much for your answer. sorry for my bad writing.
I am working on a semantic segmentation project with tensorflow deeplab project([deeplab project](https://github.com/tensorflow/models/tree/master/research/deeplab))
I made a test project to run some pretrained models provided in tensorflow deeplab modelzoo ([deeplab modelzoo](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md))
I downloaded xception65_cityscapes_trainfine model to my project.
I can read an image with opencv c++ library and convert it to tensorflow::tensor  and can do inference successfully.
When i run my code , Tensorflow  gives me a output tensor with the data type of int64.
Now i have to  convert this tensor of int64 to an opencv Mat for showing the segmentation results but opencv doesn't support int64 data type,it just support's int32 and int16  , int8 , etc. so i wanna cast the output tensor to a tensor of int32 .  I searched and found the **cast** function in tensorflow::ops. i did casting in the last line of  my project.
This is my whole project code :

`
      #include <tensorflow/cc/ops/array_ops.h>
      #include "tensorflow/cc/client/client_session.h"
      #include "tensorflow/cc/ops/standard_ops.h"
      #include "tensorflow/core/framework/tensor.h"
      #include "tensorflow/cc/ops/standard_ops.h"
      #include <tensorflow/core/framework/graph.pb.h>
      #include <tensorflow/core/framework/tensor.h>
      #include <tensorflow/core/lib/core/status.h>
      #include <tensorflow/core/platform/env.h>
      #include <tensorflow/core/protobuf/config.pb.h>
      #include <tensorflow/core/public/session.h>
      #include <tensorflow/core/public/session_options.h>
      #include <tensorflow/core/util/command_line_flags.h>
      #include <opencv2/opencv.hpp>
      #include "tensorflow/cc/client/client_session.h"
      #include "tensorflow/cc/ops/standard_ops.h"
      #include <iostream>
      #include <opencv2/core/hal/intrin.hpp>
      #include <cstdint>
      #include <cassert>
      using tensorflow::Scope;
      using tensorflow::Output;
      using tensorflow::Tensor;
      using tensorflow::ClientSession;
      using tensorflow::ops::Const;
      using tensorflow::ops::MatMul;
      using tensorflow::ops::Cast;
      using namespace tensorflow::ops;
      using namespace std;
      using namespace tensorflow;
      using namespace cv;
      using namespace cv::dnn;
      int main(int argc, char *argv[])
     {


    std::string PathGraph = "frozen_inference_graph.pb";
    int input_width_ = 513; /// Width of the input placeholder
    int input_height_ = 288;/// height of the input placeholder
    //initial declaration Tensorflow
    tensorflow::Session* session;
    tensorflow::Status status;

    status = tensorflow::NewSession(tensorflow::SessionOptions(), &session);
    if (!status.ok()) {
        std::cout << status.ToString() << "\n";
        return 1;
    }
    // Define Graph
    tensorflow::GraphDef graph_def;
    status = ReadBinaryProto(tensorflow::Env::Default(),PathGraph, &graph_def);

    if (!status.ok()) {
        std::cout << status.ToString() << "\n";
        return 1;
    }

    // Add the graph to the session
    status = session->Create(graph_def);
    if (!status.ok()) {
        std::cout << status.ToString() << "\n";
        return 1;
    }

    auto root = tensorflow::Scope::NewRootScope();
    Tensor inputImg(tensorflow::DT_UINT8, tensorflow::TensorShape({1, input_height_, input_width_, 3}));
    uint8_t *image1_p_ = inputImg.flat<uint8_t>().data();
    Mat cv_image1_ = cv::Mat(input_height_, input_width_, CV_8UC3, image1_p_);
    Mat image = imread("test_img.jpg");
    cv::Mat resized_img;
    while(1)
    {
        resize(image,resized_img,cv::Size(input_width_,input_height_));
        cvtColor(resized_img,resized_img,COLOR_BGR2RGB);
        resized_img.convertTo(cv_image1_, CV_8UC3);
        std::vector<std::pair<std::string, tensorflow::Tensor>> inputs = {
            { "ImageTensor:0", inputImg},
        };
        std::vector<tensorflow::Tensor> outputs;
        status = session->Run(inputs, {"SemanticPredictions:0"},{}, &outputs);
        if (!status.ok()) {
            std::cout << status.ToString() << "\n";
            return 1;
        }
        auto int64_caster_output =  Cast(root.WithOpName("int64_caster"), outputs[0], tensorflow::DT_INT32);
    }
}
`
I am stuck in the last line, i don't know how to convert **int64_caster_output** to a tensorflow::tensor . i know that this function output is an **tensorflow::opes::cast** object but haven't any insight about that.  i searched for a couple of days but i didn't find any docs about that. 
Hope you  help me.
Thanks in advance.

**Comment by naserpiltan** [comment]
@ymodak sir can you help me please ? i am stuck in this step. i searched alot but there is no any document about that.

**Comment by alextp** [comment]
@annarev do you know who understands the C++ API enough to answer this?

**Comment by annarev** [comment]
Seems like Cast creates a Node which needs to output a Tensor. The following works for me:

```cpp
  auto root = tensorflow::Scope::NewRootScope();
  tensorflow::ClientSession session(root);
  std::vector<tensorflow::Tensor> int_outputs;
  auto int64_caster_output =
      Cast(root.WithOpName("int64_caster"), outputs[0], tensorflow::DT_INT32);
  tensorflow::Status status = session.Run({int64_caster_output}, &int_outputs);
  if (!status.ok()) {
    std::cerr << "Casting failed" << std::endl;
    return 1;
  }
  std::cout << int_outputs[0].DebugString() << std::endl;
```

**Comment by naserpiltan** [comment]
@annarev Thank you so much. Yes this is the correct answer. 
But when i add and run this piece of code in my project , it takes 100 ms to run and i havn't realtime process.
Do you have another idea how to convert int64 tensor to an other int32 tensor ?

**Comment by annarev** [comment]
Probably a faster way is to add Cast to the original GraphDef. Do you have the code that generated original GraphDef you were loading? Can you add a cast there instead?

You can also create a script that reads original GraphDef, adds Cast to it and outputs it in serialized format. Then, you can load this serialized GraphDef in the code you have above. It would already output a casted tensor.
Using C API, that script could do something like:
```cpp
#include "tensorflow/c/c_api.h"
#include "tensorflow/c/c_api_experimental.h"
#include "tensorflow/c/tf_status.h"
...

// Read original graph from input_graph_file
std::ifstream input_stream(input_graph_file);
std::stringstream buffer;
buffer << input_stream.rdbuf();
std::string graph_proto = buffer.str();

// Load GraphDef
TF_Graph* graph = TF_NewGraph();
TF_Buffer* serialized_graph_def =
      TF_NewBufferFromString(graph_proto.c_str(), graph_proto.size());
TF_Status* status = TF_NewStatus();
TF_ImportGraphDefOptions* options = TF_NewImportGraphDefOptions();
TF_GraphImportGraphDef(graph, serialized_graph_def, options, status);
TF_DeleteBuffer(serialized_graph_def);
CHECK(TF_GetCode(status) == TF_OK);

// Add Cast
TF_Operation* operation = TF_GraphOperationByName(graph, "SemanticPredictions:0");
CHECK(operation != nullptr);
TF_Output input = {operation, 0};
TF_OperationDescription* op = TF_NewOperation(graph, "Cast", "SemanticPredictionsInt64Cast");
TF_AddInput(op, input);
// DstT comes from here: https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/ops/math_ops.cc;l=169;drc=02327c53328aa04e590b21adc55142778b1e90da
TF_SetAttrType(op, "DstT", TF_INT64);
TF_FinishOperation(op, status);
CHECK(TF_GetCode(status) == TF_OK);

// Output updated graph to output_graph_file
TF_Buffer* output_graph_def = TF_NewBuffer();
TF_GraphToGraphDef(graph, output_graph_def, status);
CHECK(TF_GetCode(status) == TF_OK);
std::ofstream output;
output.open(output_graph_file);
std::string output_graph_def_str(static_cast<const char*>(output_graph_def->data), output_graph_def->length);
output << output_graph_def_str;
output.close();

TF_DeleteBuffer(output_graph_def);
TF_DeleteGraph(graph);
TF_DeleteImportGraphDefOptions(options);
TF_DeleteStatus(status);
```

**Comment by annarev** [comment]
One note though. Seems like you are using `Session` which doesn't seem to be a part of our public API. A better way to load a graph is using a saved model: https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/cc/saved_model/loader.h

Adding @bmzhao who is working on new saved model implementation in case he has a better suggestion for your usecase.

**Comment by naserpiltan** [comment]
@annarev  Hi , Im so sorry for delay in my answer , I did not have internet access for a few days.
If I understood correctly your mean by original GraphDef is **frozen_inference_graph.pb** ? I downloaded it from tensorflow deeplab modelzoo. you can see that In this link : **http://download.tensorflow.org/models/deeplabv3_cityscapes_train_2018_02_06.tar.gz**.
Do i have to make some modifications in deeplab project source code ? I think its some hard for a noob like me :).
I wanna try your second solution. hope @bmzhao help me too.
Thank you.

**Comment by annarev** [comment]
Sorry for the long delay. Yep, I mean the GraphDef you are using, which seems to be frozen_inference_graph.pb. That suggestion would only work if you could modify the code that generates it.
I don't have any better idea, so I am assigning this bug someone who works on saved model.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
