### ISSUE TITLE
Support for batch to single element conversion

### ISSUE THREAD

**Issue by surelynottrue** [tensorflow/tensorflow#42595]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.3.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
The current implementation of batch data requires a batch output, however, I made a model that converts batch data into a single element. So the first dimensions need not be the same. 

**Will this change the current api? How?**
The current implementation gives me an error "the first dimensions do not match". That might change

**Who will benefit with this feature?**
Anyone who is making STGCNNs

**Any Other info.**
Though convoluted, here's the model summary for reference:
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param      Connected to                     

input_1 (InputLayer)            [(150, 640, 3)]      0                                            
__________________________________________________________________________________________________
tf_op_layer_ExpandDims (TensorF [(1, 150, 640, 3)]   0           input_1[0][0]                    
__________________________________________________________________________________________________
tf_op_layer_Transpose (TensorFl [(1, 640, 150, 3)]   0           tf_op_layer_ExpandDims[0][0]     
__________________________________________________________________________________________________
glu (GLU)                       (1, 640, 148, 2)     40          tf_op_layer_Transpose[0][0]      
__________________________________________________________________________________________________
tf_op_layer_Transpose_1 (Tensor [(1, 148, 640, 2)]   0           glu[0][0]                        
__________________________________________________________________________________________________
input_3 (InputLayer)            [(150, 640, 640)]    0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            [(150, 640, 640, 1)] 0                                            
__________________________________________________________________________________________________
tf_op_layer_Squeeze (TensorFlow [(148, 640, 2)]      0           tf_op_layer_Transpose_1[0][0]    
__________________________________________________________________________________________________
tf_op_layer_strided_slice_1 (Te [(148, 640, 640)]    0           input_3[0][0]                    
__________________________________________________________________________________________________
tf_op_layer_strided_slice (Tens [(148, 640, 640, 1)] 0           input_2[0][0]                    
__________________________________________________________________________________________________
graph_conv (GraphConv)          (148, 640, 3)        9           tf_op_layer_Squeeze[0][0]        
                                                                 tf_op_layer_strided_slice_1[0][0]
                                                                 tf_op_layer_strided_slice[0][0]  
__________________________________________________________________________________________________
tf_op_layer_Transpose_2 (Tensor [(640, 148, 3)]      0           graph_conv[0][0]                 
__________________________________________________________________________________________________
tf_op_layer_ExpandDims_1 (Tenso [(1, 640, 148, 3)]   0           tf_op_layer_Transpose_2[0][0]    
__________________________________________________________________________________________________
glu_1 (GLU)                     (1, 640, 146, 2)     40          tf_op_layer_ExpandDims_1[0][0]   
__________________________________________________________________________________________________
glu_2 (GLU)                     (1, 640, 144, 2)     28          glu_1[0][0]                      
__________________________________________________________________________________________________
tf_op_layer_Transpose_3 (Tensor [(1, 144, 640, 2)]   0           glu_2[0][0]                      
__________________________________________________________________________________________________
tf_op_layer_Squeeze_1 (TensorFl [(144, 640, 2)]      0           tf_op_layer_Transpose_3[0][0]    
__________________________________________________________________________________________________
tf_op_layer_strided_slice_3 (Te [(144, 640, 640)]    0           input_3[0][0]                    
__________________________________________________________________________________________________
tf_op_layer_strided_slice_2 (Te [(144, 640, 640, 1)] 0           input_2[0][0]                    
__________________________________________________________________________________________________
graph_conv_1 (GraphConv)        (144, 640, 3)        9           tf_op_layer_Squeeze_1[0][0]      
                                                                 tf_op_layer_strided_slice_3[0][0]
                                                                 tf_op_layer_strided_slice_2[0][0]
__________________________________________________________________________________________________
tf_op_layer_Transpose_4 (Tensor [(640, 144, 3)]      0           graph_conv_1[0][0]               
__________________________________________________________________________________________________
tf_op_layer_ExpandDims_2 (Tenso [(1, 640, 144, 3)]   0           tf_op_layer_Transpose_4[0][0]    
__________________________________________________________________________________________________
glu_3 (GLU)                     (1, 640, 142, 2)     40          tf_op_layer_ExpandDims_2[0][0]   
__________________________________________________________________________________________________
glu_4 (GLU)                     (1, 640, 1, 3)       1710        glu_3[0][0]                      
__________________________________________________________________________________________________
tf_op_layer_Transpose_5 (Tensor [(1, 1, 640, 3)]     0           glu_4[0][0]                      
__________________________________________________________________________________________________
tf_op_layer_Squeeze_2 (TensorFl [(640, 3)]           0           tf_op_layer_Transpose_5[0][0]    
__________________________________________________________________________________________________
dense (Dense)                   (640, 3)             12          tf_op_layer_Squeeze_2[0][0]      

Total params: 1,888
Trainable params: 1,888
Non-trainable params: 0
__________________________________________________________________________________________________

**Comment by jvishnuvardhan** [comment]
@spandananupam Can you please share little more details on the feature you are requesting and what are the possible use-cases that the new feature will support? Thanks!

**Comment by spandananupam** [comment]
> @spandananupam Can you please share little more details on the feature you are requesting and what are the possible use-cases that the new feature will support? Thanks! 

Yes sure.

The model which I am making compresses a batch of graphs to a single graph. So the first dimensions do not match. This throws an error, because tensorflow expects a model that converts batch to batch.

The use case: for stuff like spatial temporal graph neural networks, where M graphs are compressed to predict the t+1th graph

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
