### ISSUE TITLE
Command line processor fails silently on mistyped args

### ISSUE THREAD

**Issue by mkolod** [tensorflow/tensorflow#4259]
### Problem:

The command line processor doesn't raise exceptions when the existing flags that are in common use throughout TensorFlow (at the very least by convention) are mistyped. For example, let's take

    --num_gpus

which is frequently encountered, e.g. in Inception v3, CIFAR-10, etc. If I type a single dash instead of two, the CLI arg processor just picks up whatever the default value is defined in my app and silently ignores the misformed CLI argument. I realize that one can't restrict the args that are supported because they are pulled from sys.argv and there may be other args passed on to the user's app code, so it's not the same level of strictness as say in processing CLI switches for Unix apps which have a fixed set of options. However, perhaps the solution is to look for small typos such as Damerau-Levenshtein distance of 1 (one deletion, insertion, substitution or transposition, with 1 transposition still treated as edit distance of 1) from the arg specified as recognizable in FLAGS that should raise an exception unless the users forces literal interpretation of the args?

### Affected versions:

latest 0.10, probably master top of tree and others as well

**Comment by vrv** [comment]
My personal suggestion is to not use tf.flags and to just use argparse / your own solution.  As far as I know, it was provided for convenience, but it's more of a maintenance burden for us than it's worth, and we might remove it.  We don't want to be in the flags library business ;)
