### ISSUE TITLE
[Bug] apply_gradients core dump when variable shape is [0] on GPU

### ISSUE THREAD

**Issue by mavenlin** [tensorflow/tensorflow#42606]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.3.0-rc2-23-gb36436b087 2.3.0
- Python version: 3.7.5
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 10.1/7.6.5
- GPU model and memory: GeForce RTX 2080

**Describe the current behavior**
Variable with empty shape **core dumps** on GPU but works fine on CPU.

**Describe the expected behavior**
Work on both CPU / GPU or fail gracefully.

**Standalone code to reproduce the issue**
```python
import tensorflow as tf
a = tf.Variable(tf.random.normal([3]))
b = tf.Variable(tf.random.normal([0]))
Adam = tf.optimizers.Adam
optimizer = Adam()
with tf.GradientTape() as t:
    c = tf.concat([a, b], axis=0)
grad = t.gradient(c, b)
optimizer.apply_gradients(zip([grad], [b]))
```
core dumped with: `F ./tensorflow/core/util/gpu_launch_config.h:129] Check failed: work_element_count > 0 (0 vs. 0)`

**Comment by gowthamkpr** [comment]
@mavenlin  Yes This bug exists in Tensorflow 2.3.0 and the session is crashing even on [colab](https://colab.research.google.com/gist/gowthamkpr/b6271cf33375aa4f025215baf62d631d/untitled310.ipynb) but has been fixed in tf-nightly. Please find the gist [here](https://colab.research.google.com/gist/gowthamkpr/35ddba3e3edd6ad54cc651e5d0a8cea0/untitled.ipynb)

**Comment by mavenlin** [comment]
@gowthamkpr Thanks, I'll try that.

**Comment by mavenlin** [comment]
The gist provided on colab works because there's no GPU device loaded.
tested with 
```python
import tensorflow as tf
print(tf.__version__)
print(tf.config.list_physical_devices())
a = tf.Variable(tf.random.normal([3]))
b = tf.Variable(tf.random.normal([0]))
Adam = tf.optimizers.Adam
optimizer = Adam()
with tf.GradientTape() as t:
    c = tf.concat([a, b], axis=0)
grad = t.gradient(c, b)
optimizer.apply_gradients(zip([grad], [b]))
```

Get 
```
2.4.0-dev20200908
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
<tf.Variable 'UnreadVariable' shape=() dtype=int64, numpy=1>
```

**Comment by hoondy** [comment]
I have a similar issue in 2.4.1. I have custom layers bundled as a dict. Works fine on CPU but crashes on GPU.

./tensorflow/core/util/gpu_launch_config.h:129] Check failed: work_element_count > 0 (0 vs. 0)

Any workaround?

**Comment by sanjoy** [comment]
It looks there is a missing early exit here: https://github.com/tensorflow/tensorflow/blob/9f594b848ac12c98518a544198fc1c0571f68ce1/tensorflow/core/kernels/training_ops_gpu.cu.cc#L812

@sgpyc can you PTAL?

**Comment by sgpyc** [comment]
If the variable shape is [0], the optimizer should be an no op and early exit should work.
Having an empty gradient seems strange to me, not sure whether it's an issue that should be caught earlier.

**Comment by mavenlin** [comment]
I don't remember what was the exact scenario that I encounter this bug since it's been a long time.
Seems to be some dynamically shaped variable whose shape is determined dynamically, in my case it is the newly allocated weights, which could be zero if no capacity increase is necessary.

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/c560a9c361ffd130be44b438db1675ec/untitled264.ipynb) ..Thanks !

**Comment by sushreebarsa** [comment]
@mavenlin Could you please have a look at this [gist](https://colab.research.google.com/gist/sushreebarsa/247d0f013a5f9ed6db79b19c01df7dd1/untitled382.ipynb) and confirm if this issue has been fixed in the latest TF version.
Thank you!

**Comment by mavenlin** [comment]
It seems fixed in the latest tf, closing this issue.
