### ISSUE TITLE
Difference in batchnorm outputs when converting from TF model to Pytorch

### ISSUE THREAD

**Issue by slala2121** [tensorflow/tensorflow#42605]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.2.2
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

I described the issue here. https://discuss.pytorch.org/t/difference-in-batchnorm-outputs-when-converting-from-tf-model-to-pytorch/93811

**Comment by jvishnuvardhan** [comment]
@slala2121 Can you please share a simple standalone code to reproduce the issue? I tried running your code, it throws the following error. GitHub gist is [here](https://colab.research.google.com/gist/jvishnuvardhan/1d3328e4cfe84dae668b4f2ebefb498e/untitled13.ipynb) for a reference.

> OSError: File model-1.meta does not exist.

**Comment by slala2121** [comment]
The relevant model file is available at this link (from the post): https://figshare.com/articles/Trained_neural_network_models/8312183

**Comment by jvishnuvardhan** [comment]
@slala2121 Can you please create a simple standalone code to reproduce the issue? You could use simple public datasets to demonstrate the issue. Thanks!

**Comment by slala2121** [comment]
@jvishnuvardhan The model in the above link is public. Could you please try with that?

**Comment by nikitamaia** [comment]
Hi @slala2121, can you share more about the TF inceptionv3 model you're using? Is that a keras model?
