### ISSUE TITLE
TF 2.3 Saved model | Experimental features not working properly

### ISSUE THREAD

**Issue by rafiqhasan** [tensorflow/tensorflow#42613]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.7
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**:
While serving a TF 2.3 trained saved model created with tf.keras.layers.experimental.preprocessing features, TMS(Tensorflow model server ) gives error on prediction. However predict method on the model runs absolutely fine without any error, seems to be something specific to TMS. Does TMS currently not support the new experimental pre-processing features that were added in TF 2.3.

I also noticed that saved_model_cli also throws error that Op type not registered 'DenseBincount' in binary but that could be related to saved_model_cli not yet updated in Colab with TF 2.3 support.

Bug has also been opened on TMS but it seems that the bug is not in serving but in TF runtime: https://github.com/tensorflow/serving/issues/1720#issuecomment-678842670 ( FYI: @christisg  )

**Describe the expected behavior**:
Saved model should work properly in Tensorflow serving and also show up properly in saved_model_cli

**Standalone code to reproduce the issue**
Run GIST - https://gist.github.com/rafiqhasan/6f00aecf1feafd83ba9dfefef8907ee8#file-dl-e2e-taxi-dataset-tf2-keras-ipynb

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
import json
import requests

#Create payload
data_py = {"instances":[{'dropoff_latitude': [41.920452],
                         'dropoff_longitude': [-87.679955],
                         'pickup_latitude': [41.952823],
                         'pickup_longitude': [-87.653244],
                         'trip_start_day': ["1"],
                         'trip_start_hour': ["5"],
                         'trip_start_month': ["6"]}]}

data = json.dumps(data_py)
print("payload: ", data)

#Run request on TMS
headers = {"content-type": "application/json"}
json_response = requests.post('http://localhost:8507/v1/models/model:predict', data=data, headers=headers)
json_response.text
```

Error message:

```
{
    "error": "Missing 0-th output from {{node functional_3/category_encoding_13/bincount/DenseBincount}}"
}
```

But model prediction standalone code works:
```
# ##Prediction on model
# ## BUT HERE ALL FEATURES HAVE TO BE PASSED, EVEN THE Calculated ones
data = tf.data.Dataset.from_tensor_slices({'dropoff_latitude': [[41.920452]],
                         'dropoff_longitude': [[-87.679955]],
                         'pickup_latitude': [[41.952823]],
                         'pickup_longitude': [[-87.653244]],
                         'trip_start_day': [["1"]],
                         'trip_start_hour': [["5"]],
                         'trip_start_month': [["6"]],
                         'distance':[[0.02]]})

m_.predict(data)
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/2449c4a116ca8306a754bcf9f700df07/42613.ipynb). Thanks!

**Comment by rafiqhasan** [comment]
Not able to open the GIST, request you to please make the link public.

**Comment by rafiqhasan** [comment]
do we know the root cause now ?

**Comment by rafiqhasan** [comment]
Team, any response ? Can't deploy an experimental saved model to TMS.

**Comment by rafiqhasan** [comment]
Infact, upon careful investigation of the error message from saved_model_cli - it says. Which is inline with the error that TMS is raising for the saved model.

```
c_api.TF_GraphGetOpDef(self._c_graph, compat.as_bytes(type), buf)
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'DenseBincount' in binary running on 5e1999aea28d. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
```

**Comment by rafiqhasan** [comment]
Open since 25 days , no response !

**Comment by rafiqhasan** [comment]
Wow team, there's no response whatsoever ?

**Comment by S0013507316** [comment]
@k-w-w : Should we stop expecting a resolution on this ? This is a production issue and is escalating more than ever as we are not able to deploy models using these feature engineering options.

**Comment by rafiqhasan** [comment]
@k-w-w : Should we stop expecting a resolution on this ? This is a production issue and is escalating more than ever as we are not able to deploy models using these feature engineering options.

**Comment by rafiqhasan** [comment]
TF 2.4 has fixed this problem specifically for the in-model inferencing, however tensorflow_model_server based inferencing issue still persists and is open here - tensorflow/serving#1720
