### ISSUE TITLE
I've got a build error for "Build a handwritten digit classifier app with TensorFlow Lite"

### ISSUE THREAD

**Issue by ihmon** [tensorflow/tensorflow#42610]
**System information**
- OS Platform: WIndows10
- Mobile device: AVD (Android 10.0(Google Play) API:29)
- TensorFlow installed from (source or binary): Google Colabo
- TensorFlow version: 2.3.0
- Python version: 3.7
- Installed using virtualenv? pip? conda?: Preinstalled in Google Colabo
- Bazel version (if compiling from source): 
> Android Studio 4.0
> Build #AI-193.6911.18.40.6514223, built on May 21, 2020
> Runtime version: 1.8.0_242-release-1644-b01 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0
> GC: ParNew, ConcurrentMarkSweep
> Memory: 1237M
> Cores: 8
> Registry: ide.new.welcome.screen.force=true
> Non-Bundled Plugins: org.jetbrains.kotlin

**Describe the problem**
I followed TF lite trial site and at step 5(https://codelabs.developers.google.com/codelabs/digit-classifier-tflite/#5), 
after pressing a "Run 'app'" button on Android Studio, I got the following error in Android Studio.

Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type interpreter?
Following **interpreter** the right side of val inputShape = is highlighted.

private fun initializeInterpreter() {

    // TODO: Read the model input shape from model file.
    // Read input shape from model file
    val inputShape = interpreter.getInputTensor(0).shape()
    inputImageWidth = inputShape[1]
    inputImageHeight = inputShape[2]

I'm a newbie of Android Studio, thus I have not been able to find any wrong configuration in it.
Could you give me any clue?
Thank you.

**Any other info / logs**
At the very first try, when I press the "Run 'app'" button, Android Studio attempted to install something version 28.0.3(maybe SDK?). However, it was not able to fetch the version.
I have never seen the same message, even if I delete all "example_master" folder and change the location and try again.

One more info.
Although I don't know the difference b/w 'start' project and 'finish' project, I tried 'finish' project w/ same "mnist.tflite" too.
Then, Android studio spitted **"Compatible side by side NDK version was not found. Default is 21.0.6113669."** error.

My build.gradle is below by the way.
> apply plugin: 'com.android.application'
> apply plugin: 'kotlin-android'
> apply plugin: 'kotlin-android-extensions'
> 
> android {
>     compileSdkVersion 29
>     defaultConfig {
>         applicationId "org.tensorflow.lite.codelabs.digitclassifier"
>         minSdkVersion 21
>         targetSdkVersion 29
>         versionCode 1
>         versionName "1.0"
>         testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
>     }
> 
>     // TODO: Add an option to avoid compressing TF Lite model file
>     aaptOptions {
>         noCompress "tflite"
>     }
> 
>     buildTypes {
>         release {
>             minifyEnabled false
>             proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
>         }
>     }
> }
> 
> // Sanity check if you have trained and downloaded TF Lite model.
> preBuild.doFirst {
>     assert file("./src/main/assets/mnist.tflite").exists() :
>             "mnist.tflite not found. Make sure you have trained and " +
>                     "downloaded your TensorFlow Lite model to assets/ folder"
> }
> 
> dependencies {
>     implementation fileTree(dir: 'libs', include: ['*.jar'])
>     implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
> 
>     // Support Libraries
>     implementation 'androidx.appcompat:appcompat:1.1.0'
>     implementation 'androidx.core:core-ktx:1.1.0'
>     implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
> 
>     // AndroidDraw Library
>     implementation 'com.github.divyanshub024:AndroidDraw:v0.1'
> 
>     // Task API
>     implementation "com.google.android.gms:play-services-tasks:17.0.0"
> 
>     //TODO: Add TF Lite
>     implementation 'org.tensorflow:tensorflow-lite:2.0.0'
> 
>     testImplementation 'junit:junit:4.12'
>     androidTestImplementation 'androidx.test:runner:1.2.0'
>     androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
> }
I changed TF version, but each of them ended up w/ same error.
    implementation 'org.tensorflow:tensorflow-lite:2.3.0'
    implementation 'org.tensorflow:tensorflow-lite:2.2.0'

**Comment by ymodak** [comment]
Is this still an issue?
Also see https://stackoverflow.com/questions/61157024/compatible-side-by-side-ndk-version-was-not-found-default-is-20-0-5594570
