### ISSUE TITLE
how to change the specific value of tensor?

### ISSUE THREAD

**Issue by SlowMonk** [tensorflow/tensorflow#42611]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.0
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

I want to change the 
`D.object_for_each_prior-> tf.Tensor([0 0 0 ... 0 0 0], shape=(8732,), dtype=int64)
`want to change the position 8700 and 8701 to the 1 value 
since the assign value is no longer available how should I assign spicific value to the specific location?

**Comment by saikumarchalla** [comment]
@SlowMonk Please provide a standalone code to reproduce the issue at our end. Thanks!

**Comment by ymodak** [comment]
Perhaps you can use [`assign`](https://www.tensorflow.org/api_docs/python/tf/Variable?version=nightly#assign) method from `tf.Variable`.
```python
v = tf.Variable(1.)
print(v)
v.assign(2.)
print(v)
#Output 
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>
```

**Comment by ravikyram** [comment]
@SlowMonk 

Can you please confirm if @ymodak 's workaround is working for you.Thanks!
