### ISSUE TITLE
Request for Prebuilt C++ Library libtensorflow_cc.so (probably from CI artifacts)

### ISSUE THREAD

**Issue by jinay1991** [tensorflow/tensorflow#42614]
**System information**
- TensorFlow v2.3.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
It has been lot of demand and lot of time consumption in building the TensorFlow C++ Library (monolithic), which could be saved if TensorFlow provides official `libtensorflow_cc` (C++ lib) as well along with `libtensorflow.so` (C lib) as there are lots of functionality which one would want from C++ lib and due to the fact that it is not available anywhere, one has to built it himself for this, which I believe Tensorflow official CI is already building (cache) so if we have CI package available for download and use for all various OS, this could reduce the deployment efforts for anyone to great extend. 

I have built the lib manually for various systems by following steps provided below as I wanted to have single lib + headers to deploy with other projects.

```bash
bazel build -c opt --config=monolithic //tensorflow:libtensorflow_cc.so //tensorflow:install_headers
```

In addition to that, if TensorFlow can provide complete package which includes `libtensorflow_cc.so`, `libtensorflow_lite.so`, `libtensorflow.so`, headers and `tools` along with Bazel BUILDs (i.e. package) then one could speed up his own CI compilation time and lot more as all he has to do is to fetch package and link the binaries against it. 

Package for each OS (i.e. `linux, windows, macOS`)

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Almost everyone who wants to use C++ APIs for deployment

**Any Other info.**
none

**Comment by byronyi** [comment]
C++ libraries have no stable ABIs. That means any client code that uses `libtensorflow_cc.so` will need to use the exact same toolchains (C++ compiler, libstdc++/libc++) along with the pre-built C++ libraries.

**Comment by jinay1991** [comment]
I don't know exactly these ABI issues but what I know is that for most dev environments will have x86_64 platform with either GCC or CLANG as toolchain (versions would be based on latest OS support package - i.e. in case of Ubuntu 20.04 this will be 8.3 and 10.0 respectively) so I believe this is still very useful and important for Developers. I have already tried generating `monolithic` packages for `libtensorflow_cc.so` with headers (with GCC and CLANG) manually and works fine so far with my DEV environment in efficient and portable way. If Team can integrate similar to CI that would be great help to community in my opinion.

Another reason why I do want pre-compiled TF Library is that building TF on the fly (with Bazel/CMake as dependencies) is going to really time-consuming even for very simple `hello-tf.cpp` project. This is not OK for small project CI Pipeline as well and requires easy and quick build which can only be achieved if we have precompiled TF binary.

**Alternative**: Provide all OS Package (i.e. for ubuntu/Debian - *.deb, for RedHat - *.rpm etc.) into Official/Unofficial OS Package repository so that every single dev environment can avail these pre-compiled packages out-of-the-box and easily develop projects without worrying about setting up TF environment for C++ which is a big head-ache now.

**Comment by av8ramit** [comment]
> > C++ libraries have no stable ABIs. That means any client code that uses libtensorflow_cc.so will need to build with the exact same toolchain (a particular version of C++ compiler and libstdc++/libc++) as those were used to build the pre-built C++ libraries.
> > So the pre-built libraries may not be so useful as you expect if the TF team only provides them built with a particular toolchain.
> 
> I don't know exactly these ABI issues but what I know is that for most dev environments will have x86_64 platform with either GCC or CLANG as toolchain (versions would be based on the latest OS support package - i.e. in the case of Ubuntu 20.04 this will be 8.3 and 10.0 respectively) so I believe this is still very useful and important for Developers. I have already tried generating `monolithic` packages for `libtensorflow_cc.so` with headers (with GCC and CLANG) manually and works fine so far with my DEV environment efficient and portable way. If Team can integrate similar to CI that would be a great help to the community in my opinion.
> 

The plan is to have `libtensorlow_cc` releases the same way we currently have `libtensorflow` releases in Q4 this year. Sorry for the delay.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
