### ISSUE TITLE
Tensorflow lite: Failed to run on the given Interpreter

### ISSUE THREAD

**Issue by william970** [tensorflow/tensorflow#42622]
I am using tflite for semantic segmentation. I have a model trained to segment objects from background, this model is trained on deeplab.
I have converted this model(frozen inference graph) into tflite format using the below code:
```
tflite_convert \
  --output_file=test.lite \
  --graph_def_file=frozen_inference_graph.pb \
  --input_arrays=ImageTensor \
  --output_arrays=SemanticPredictions \
  --input_shapes=1,513,513,3 \
  --inference_input_type=QUANTIZED_UINT8 \
  --inference_type=FLOAT \
  --mean_values=128 \
  --std_dev_values=128 
```
The model loads on android, but when I try to run inference it gives me this error:
```
Caused by:java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: tensorflow/lite/kernels/unpack.cc:71 output->type != input->type (FLOAT32 != INT32)
Node number 22 (UNPACK) failed to prepare.
```
How do I resove this error? Is there anyone who can solve my problem？
here is my model
[deeplabv3_513_mv2_gpu.zip](https://github.com/tensorflow/tensorflow/files/5118434/deeplabv3_257_mv_gpu.zip)

**Comment by rmothukuru** [comment]
@1095560081,
Can you please let us know what is the version of Tensorflow that you are using? Thanks!

**Comment by 1095560081** [comment]
@rmothukuru Hi , I am using the version of 1.14

**Comment by 1095560081** [comment]
@rmothukuru You may be able to reproduce it with this Android project

[android.zip](https://github.com/tensorflow/tensorflow/files/5124793/android.zip)

**Comment by jvishnuvardhan** [comment]
@1095560081 Did you try with recent TF1.x version (TF1.15.3)? Did you try `tf-nightly` for the conversion? Thanks!
