### ISSUE TITLE
Size 1 must be non-negative error when using boolean mask tensorflow

### ISSUE THREAD

**Issue by MMKrell** [tensorflow/tensorflow#42629]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Maybe?
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.4 LTS
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6.8
- CUDA/cuDNN version: N/A using IPU, poplar version 1.2.100
- GPU model and memory: MK1 IPU

**Describe the current behavior**

When working with too big arrays, boolean crashes probably because of using int32 internally for indexing.
If I change the first dimension in the example below to 20000, processing is not an issue.

**Describe the expected behavior**

The input arrays for the boolean mask function have the same size as the expected output of the boolean mask.
Hence, I would expect that either the inputs objects get not created with an error that their size exceeds the limits or that it just works. Also, it would be better to have an internal size check to provide more meaningful output.

**Standalone code to reproduce the issue**

```
import tensorflow as tf
t_vector = tf.ones([8,35583,100000], dtype=tf.float32)
acceptance_vector = tf.cast(tf.ones([35583, 100000]), tf.bool)
eval_vector = tf.boolean_mask(t_vector, acceptance_vector, axis=1)
```

**Other info / logs**

[boolean_mask_error.log](https://github.com/tensorflow/tensorflow/files/5119308/boolean_mask_error.log)

**Comment by mihaimaruseac** [comment]
Does the issue reproduce against `tf-nightly`. I tried to do that myself and I got an OOM error, as expected.

**Comment by gowthamkpr** [comment]
@mihaimaruseac Its crashing even in tf-nightly. Please find my [gist](https://colab.research.google.com/gist/gowthamkpr/e7820465446677c256945271c45c179f/untitled309.ipynb)

**Comment by mihaimaruseac** [comment]
If you separate the lines, the crash happens on the first line, when trying to allocate memory that clearly gets outside of the interpreter's available memory.
![yH0qjPS7gNn](https://user-images.githubusercontent.com/323199/91485313-88083d80-e85f-11ea-889d-578922c490ee.png)

**Comment by gowthamkpr** [comment]
@MMKrell Can you please resond to the above comment so that we can take the discussion forward. Thanks!

**Comment by MMKrell** [comment]
I did two tests. I tried to reproduce my error in the collab notebook but its memory is too limited and it will always create an OOM error. It needs at least 110GB, probably more around 220GB, given that the boolean mask probably also needs some space. I installed the nightly (2.4.0-dev20201020) on my own machine with 739GB RAM and it crashed with the error related to the boolean mask. The trace looked the same, but I can upload it again if that helps.

**Comment by MMKrell** [comment]
Do you need any other information from my side?

**Comment by jvishnuvardhan** [comment]
@MMKrell Looks like crash is not due to `tf.boolean_mask` but the huge memory. When I tried smaller input size (like [8,35583,1000]), everything worked as expected. Is there any data pipeline you can use to avoid memory issue? Thanks!

**Comment by MMKrell** [comment]
@jvishnuvardhan This issue cannot be tested/reproduced on gist because the gist server has too little memory and will result in a crash due to memory. I am getting the following error, when I use a sufficient amount of RAM:

`In [4]: eval_param_vector = tf.boolean_mask(t_vector, acceptance_vector, axis=1)
2020-08-24 09:03:43.882188: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at reshape_op.h:53 : Invalid argument: Size 1 must be non-negative, not -736667296`
`InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-4-1d3d606238ed> in <module>
----> 1 eval_param_vector = tf.boolean_mask(t_vector, acceptance_vector, axis=1)`

You can see the full logging in the main issue description. This is not an out of memory error but an error that indicates an integer overflow or something else.

As a workaround, I iterated over the data and produced small chunks that do not give the index error. However, figuring out why I get the "Size 1 must be non-negative, not -736667296" error took me quite a while and from a usability perspective, it would be good to avoid this for other users. If there is an intended size limit for arrays, it should be resulting in a respective error when creating the array. In fact, negative sizes should not be possible at all.

Maybe, the easiest approach would be to add a message to the provided error that says: "You might have to reduce your tensor size."?

**Comment by wangpengmit** [comment]
This seems to be an integer overflow caused by a tensor too large.  TF uses int32 for shapes. A tensor of shape [8,35583,100000] has 28,466,400,000 elements, larger than 2^31=2,147,483,648, so when this tensor is flattened (probably by some ops internally), the resulting dimension size is too large for an int32. This behavior seems to be WAI. We may add a check to disallow any tensor with more than 2^31 elements, but that may be too restrictive since creating such a tensor is OK as long as you don't flatten it.

**Comment by MMKrell** [comment]
Maybe, it is possible to check internally before flattening what the size is? Or maybe give a warning, when a data structure gets too big?

**Comment by jvishnuvardhan** [comment]
@MMKrell As mentioned by @wangpengmit tensor is too large. With the most recent `tf-nightly`, code is not crashing. It is throwing `ResourceExhaustedError` as shown below.


---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
<ipython-input-2-17d1ab0502a4> in <module>()
      1 import tensorflow as tf
----> 2 t_vector = tf.ones([8,35583,100000], dtype=tf.float32)
      3 # 8,35583,100000

6 frames
/usr/local/lib/python3.7/dist-packages/six.py in raise_from(value, from_value)

ResourceExhaustedError: OOM when allocating tensor with shape[8,35583,100000] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:Fill]

I am closing this issue as this was resolved. Please feel free to reopen if I am mistaken. Thanks!
