### ISSUE TITLE
Retrain a TensorFlow model from a .pb file

### ISSUE THREAD

**Issue by kaustav-aarish** [tensorflow/tensorflow#42623]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: MacOS Catalina
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 1.15.0 
- Python version: 3.6

**I was trying to retrain a TensorFlow model from a .pb file**. I'm using the following function to retrieve it and load the graph in Python:

```
# Load protobuf as graph, given filepath
def load_pb(path_to_pb):
    with tf.gfile.GFile(path_to_pb, 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
    with tf.Graph().as_default() as graph:
        tf.import_graph_def(graph_def, name='')
        return graph
```
From here, I try to list its trainable variables and operations:
```
with tf.Session(graph=tf_graph) as sess:
    print("Trainable variables: {}".format(tf.trainable_variables())) 
    variables = [op for op in tf_graph.get_operations()]
    for var in variables:
        print("{}".format(var.name), end = ' ,')
```
This is the output from the above code:
[Code output][1]

As shown above, it says that there are no variables that can be trained, and when I try the following code to train the graph:

```
with tf.Session() as sess:
    random_input  = tf.convert_to_tensor(np.random.rand(1, 3, 2848, 4256)) # Input dimensions
    random_output = sess.run(random_input) 

    random_y0 = tf.convert_to_tensor(np.random.rand(1, 3, 2848, 4256))

    loss = tf.reduce_sum(tf.square(random_y0 - random_output))
    train = tf.train.GradientDescentOptimizer(1e-4).minimize(loss)

    sess.run(tf.global_variables_initializer())

    print("Training")

    for step in range(1):
        sess.run(train)

```

It gives me the error: 

```
train = tf.train.GradientDescentOptimizer(1e-4).minimize(loss)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow_core/python/training/optimizer.py", line 410, in minimize
    ([str(v) for _, v in grads_and_vars], loss))
ValueError: No gradients provided for any variable, check your graph for ops that do not support gradients, between variables
```

I believe there is an issue with the conversion such that it is failing to find the training variables, could someone please clarify this? I can also provide the exact .pb file if needed. Thanks a lot!

  [1]: https://i.stack.imgur.com/SNkBk.png

**Comment by Saduf2019** [comment]
@kaustav-aarish 
Is there any particular reason for using 1.15, can you try in later versions and see if you still face the issue.
Also, the code is incomplete for us to replicate, if possible share a colab gist with the issue reported for us to analyse.

with respect to the error reported, please refer to: #23621 #28792 [link](https://github.com/tensorflow/tensorflow/issues/1511) [link1](https://github.com/tensorflow/tensorflow/issues/14894) [link2](https://stackoverflow.com/questions/41689451/valueerror-no-gradients-provided-for-any-variable) [link](https://stackoverflow.com/questions/42498876/tensorflow-no-gradients-provided-for-any-variable-and-partial-run/42504176)

**Comment by kaustav-aarish** [comment]
@Saduf2019 ,

Thanks for your reply! I upgraded to TensorFlow 2.x (still using v1 functions) and I get the same problems.

The colab file with the complete code is here: 

https://colab.research.google.com/drive/1Lo4ycD7tp5GrD1jYvXNbPEyZEHlG01-h?usp=sharing

You also will need a sample .pb file, which is located here (you would need to upload it to the colab server, since it deletes the file everytime a new runtime is created):

https://drive.google.com/file/d/14A9Z0F4t15pbyHXGx2BB9ztz7CHcVvfi/view?usp=sharing

**Comment by Saduf2019** [comment]
@kaustav-aarish 
I ran the code shared on 2.3 and face a different error, please find the[ gist here](https://colab.research.google.com/gist/Saduf2019/99d4aeea8a5acfb8270f351e4374b385/untitled400.ipynb) and gist on [tf 2.2](https://colab.research.google.com/gist/Saduf2019/acd6e7e9dc0904df9fb48e60644857f7/untitled400.ipynb)
Are you trying to optimise a loss function with out any variables, please refer to this link and let us know if it helps [[link](https://stackoverflow.com/questions/46246556/valueerror-no-variables-to-optimize)]

**Comment by kaustav-aarish** [comment]
@Saduf2019,

I added to [here](https://colab.research.google.com/drive/1Lo4ycD7tp5GrD1jYvXNbPEyZEHlG01-h?usp=sharing) to show that the loaded graph does have trainable variables, but they are not being recognised? The StackOverflow link you provided says:

     To solve the problem, you have to think again about the graph you are trying to construct. You have to define 
     variables...

The issue is that the variables were defined elsewhere, then saved, and now need to be read and recongised which I believe TensorFlow is not able to do.

**Comment by ccrusius** [comment]
Our recommended way of retraining models is to use saved models. As far as I understand, we do not support going directly through protobufs as persistence mechanisms. I'll close this bug, feel free to open another one if the saved model approach does not work.
