### ISSUE TITLE
tf.keras.activations.deserialize document refers `x` as a parameter

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#42627]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/keras/activations/deserialize

### Clear description

The document of `tf.keras.activations.deserialize` refers `x` as a parameter in the **Argument** section. But it is not in the signature and not accepted by the function.

![image](https://user-images.githubusercontent.com/24580222/91073972-e6d47980-e609-11ea-835d-4a1c17ead171.png)

### Usage example

~~~python
import tensorflow as tf
tf.keras.activations.deserialize(x='softmax')
~~~

Running the code above gives exception:

~~~
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: deserialize() got an unexpected keyword argument 'x'
~~~

## System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Mojave 10.14
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 2.0.0
- **Python version**: 3.6.9

**Comment by ymodak** [comment]
This is now fixed with the above commit. Thanks!
