### ISSUE TITLE
Embedding layer doesn't follow mixed_precision policy by default

### ISSUE THREAD

**Issue by brand17** [tensorflow/tensorflow#42631]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro 1909 OS build 18363.1016
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
Embedding layer's output is float32 despite mixed_bfloat16 policy

**Describe the expected behavior**
Embedding layer's output should tie to mixed_bfloat16 policy

**Standalone code to reproduce the issue**
```
import tensorflow as tf
from tensorflow.keras.mixed_precision import experimental as mixed_precision
policy = mixed_precision.Policy('mixed_bfloat16')
mixed_precision.set_policy(policy)
inputs = tf.keras.Input(shape=(100,), name='digits')
emb = tf.keras.layers.Embedding(100, 100)
dense = tf.keras.layers.Dense(100)

outputs = emb(inputs) + dense(inputs) # <= the error is here (adding two different types)

model = tf.keras.Model(inputs=inputs, outputs=outputs)
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=tf.keras.optimizers.Adam(),
              metrics=['accuracy'])
input = tf.random.uniform(shape=[1,25], maxval=100, dtype=tf.int32)
hist = model.fit(input, input, epochs=1, steps_per_epoch=1,verbose=0)

```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

> ValueError: Tensor conversion requested dtype float32 for Tensor with dtype bfloat16: <tf.Tensor 'dense/Identity:0' shape=(None, 100) dtype=bfloat16>

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/8bcbf72e06fa014e1a2b1970fd2bb2ef/42631.ipynb#scrollTo=sfr6zmv_ELEj). Thanks!

**Comment by gowthamkpr** [comment]
@brand17 In` tf.keras.layers.Embedding()`, auto casting is set to false as shown [here](https://github.com/tensorflow/tensorflow/blob/b36436b087bd8e8701ef51718179037cccdfc26e/tensorflow/python/keras/layers/embeddings.py#L108) and that is the cause of the error.

**Comment by brand17** [comment]
Not clear for me - is it impossible to fix ? I don't understand - why casting embedding matrix to float16 before casting input to int32 might cause the int32 values to be different due to a loss of precision
