### ISSUE TITLE
Running the Smart Replies Model in TFLite Python

### ISSUE THREAD

**Issue by videetparekh** [tensorflow/tensorflow#42637]
I'm experimenting with the [Smart Reply][1] Lite model in Python. I used Bazel to compile TFLite with the custom ops  needed to run this model (normalize.cc, predict.cc, extract_features.cc) with the help of this [fantastic tutorial][2] and now I'm trying to run inference. 

Here's the code I use:
```python
    import tensorflow as tf
    import numpy as np
    tflite_interpreter = tf.lite.Interpreter(model_path='smartreply.tflite')
    
    tflite_interpreter.allocate_tensors()
    input_details = tflite_interpreter.get_input_details()
    output_details = tflite_interpreter.get_output_details()
    
    # print(input_details)
    # print(output_details)
    
    tflite_interpreter.set_tensor(input_details[0]['index'], 'Where are you?')
    # Run inference
    tflite_interpreter.invoke()
    # Get prediction results
    tflite_model_predictions = tflite_interpreter.get_tensor(output_details[0])
    print("Prediction results shape:", tflite_model_predictions)
```

In doing so I got the following error:
```bash
Traceback (most recent call last):
  File "run.py", line 12, in <module>
    tflite_interpreter.set_tensor(input_details[0]['index'], 'Where are you?')
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/lite/python/interpreter.py", line 175, in set_tensor
    self._interpreter.SetTensor(tensor_index, value)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/lite/python/interpreter_wrapper/tensorflow_wrap_interpreter_wrapper.py", line 136, in SetTensor
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_SetTensor(self, i, value)
ValueError: numpy array had 56 bytes but expected 0 bytes.
```
I tried resizing the tensor with this line of code before calling `tflite_interpreter.allocate_tensors()`:
```python
tflite_interpreter.resize_tensor_input(0, [56])
```
But that raised `ValueError: Cannot set tensor: Dimension mismatch`. Similarly, if I try to change tensor shape to [1,56] it still fails with the same error. 

My understanding is, the string is converted to a numpy array(based on the model description, the input type is int32 - 4 bytes per character).
What changes do I need to make to this input method to run this model?

  [1]: https://www.tensorflow.org/lite/models/smart_reply/overview
  [2]: https://medium.com/@bsramasubramanian/running-a-tensorflow-lite-model-in-python-with-custom-ops-9b2b46efd355

**Comment by videetparekh** [comment]
I noticed a similar issue with the [BERT_qa](https://www.tensorflow.org/lite/models/bert_qa/overview) model where the two inputs and output have a fixed shape of (1,384) and type int32.
INPUTS:
1. Passage about a topic
2. Question on topic

OUTPUT:
1. Predicted Answer

```
[{'name': 'input_ids', 'index': 5422, 'shape': array([  1, 384], dtype=int32), 'dtype': <class 'numpy.int32'>, 'quantization': (0.0, 0)}, {'name': 'input_mask', 'index': 5423, 'shape': array([  1, 384], dtype=int32), 'dtype': <class 'numpy.int32'>, 'quantization': (0.0, 0)}, {'name': 'segment_ids', 'index': 5424, 'shape': array([  1, 384], dtype=int32), 'dtype': <class 'numpy.int32'>, 'quantization': (0.0, 0)}]

[{'name': 'end_logits', 'index': 5421, 'shape': array([  1, 384], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}, {'name': 'start_logits', 'index': 5425, 'shape': array([  1, 384], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]
```

**Comment by videetparekh** [comment]
Hi, I'd love to hear if there's been any progress on this front?

**Comment by chiranshu14** [comment]
@videetparekh Were you able to get it to work in python?

**Comment by videetparekh** [comment]
No, sorry. Received no support from the Google team.

**Comment by chiranshu14** [comment]
@videetparekh  How did you implement this feature in js/python? 
I saw an unofficial port, but didn't work for me. Building from scratch isn't going to be very efficient.

**Comment by mohantym** [comment]
Yeah! I could replicate this issue in the [2.8 ](https://colab.sandbox.google.com/gist/mohantym/dc06b7051441919b4a677a61a485145b/tensorflow-ranking.ipynb#scrollTo=2Wr1rC6nqWKf)version . Thanks!

**Comment by pkgoogle** [comment]
Currently it appears there is an issue with the model's metadata (at least), [gist](https://colab.sandbox.google.com/gist/pkgoogle/e0c195ccbcb25363932d9b7ec01ce94c/tensorflow-ranking.ipynb) (tried with both 2.8 and 2.12)

**Comment by pjpratik** [comment]
Hi,
Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.
The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.
Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
