### ISSUE TITLE
Calculation of effective scale differs from TFLite implementation in quantize kernel

### ISSUE THREAD

**Issue by patriklaurell** [tensorflow/tensorflow#42648]
@tensorflow/micro

**Describe the problem**

In the quantize kernel the calculation of the effective scale differs slightly between TFLite and TFLu. We found that in some cases this results in single bit differences in output. Is this difference in implementation intentional?

https://github.com/tensorflow/tensorflow/blob/de1a269b21cbad035faa095d8ce88fc2d680cf4a/tensorflow/lite/kernels/quantize.cc#L129-L133

https://github.com/tensorflow/tensorflow/blob/de1a269b21cbad035faa095d8ce88fc2d680cf4a/tensorflow/lite/micro/kernels/quantize.cc#L75-L79

**Comment by advaitjain** [comment]
Thanks for catching this. This is oversight on our part. I have created a PR to fix this.
