### ISSUE TITLE
Tensorflow lite arm64 cross/native build issue

### ISSUE THREAD

**Issue by clsdmgtk** [tensorflow/tensorflow#42640]
Hi,

I am trying to build tensorflow-lite with edgetpu on Coral development board and following the instructions from the link below
https://www.tensorflow.org/lite/guide/build_arm64#compile_natively_on_arm64

I am checked out to d855adfc5a0195788bf5f92c3c7352e638aa1109(https://github.com/google-coral/edgetpu/blob/c48c88871fd3d2e10d298126cd6a08b88d22496c/WORKSPACE#L5 as per the instructions on step 3 of the link - https://coral.ai/docs/edgetpu/tflite-cpp/#build-your-project

I am running into build issues with native as well as cross compilation with this SHA(master builds fine). Below is the log snippet of build failure

```
In file included from /home/mg/workspace/nxpdemo/tensorflow/tensorflow/lite/tools/make/downloads/absl/absl/base/internal/periodic_sampler.h:22:0,
                 from tensorflow/lite/tools/make/downloads/absl/absl/base/internal/periodic_sampler.cc:15:
/home/mg/workspace/nxpdemo/tensorflow/tensorflow/lite/tools/make/downloads/absl/absl/base/internal/exponential_biased.h:24:1: error: ‘ABSL_NAMESPACE_BEGIN’ does not name a type
 ABSL_NAMESPACE_BEGIN
 ^~~~~~~~~~~~~~~~~~~~
tensorflow/lite/tools/make/downloads/absl/absl/base/internal/exponential_biased.cc:28:1: error: ‘ABSL_NAMESPACE_BEGIN’ does not name a type
 ABSL_NAMESPACE_BEGIN
 ^~~~~~~~~~~~~~~~~~~~
/home/mg/workspace/nxpdemo/tensorflow/tensorflow/lite/tools/make/downloads/absl/absl/base/internal/exponential_biased.h:127:1: error: ‘ABSL_NAMESPACE_END’ does not name a type; did you mean ‘ABSL_BASE_PORT_H_’?
 ABSL_NAMESPACE_END
 ^~~~~~~~~~~~~~~~~~

```
**Steps to build tensorflow-lite**

1. git clone https://github.com/tensorflow/tensorflow and checkout to  d855adfc5a0195788bf5f92c3c7352e638aa1109
2. cd tensorflow 
3. ./tensorflow/lite/tools/make/download_dependencies.sh
4. ./tensorflow/lite/tools/make/build_aarch64_lib.sh

I also tried to use master of tensorflow-lite with released version of libedgetup.so.1.0 with a sample test and ran into problems which I suspect are related to mismatch of versions between tensorflow-lite and libedgetpu

> mendel@neat-jet:~/coral-demo/tflite/cpp/examples/classification$ ./minimal 
>  model: /edgetpu/test_data/mobilenet_v1_1.0_224_quant_edgetpu.tflite
>  data: /edgetpu/test_data/resized_cat.bmp
> ERROR: Internal: Unsupported data type in custom op handler: -591183536
> ERROR: Node number 0 (edgetpu-custom-op) failed to prep

Thanks,

**Comment by Saduf2019** [comment]
@clsdmgtk 
Could you please fill in the issue template, i am unable to find details as the tf version and system information.

**Comment by clsdmgtk** [comment]
@Saduf2019 

**System information for cross compile **
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source):   https://github.com/tensorflow/tensorflow and checkout to d855adf
- TensorFlow version: -
- GCC/Compiler version (if compiling from source): aarch64-linux-gnu-g++ (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0

**Native compile on Coral dev board**
- OS Platform and Distribution: mendel 5.0
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source):   https://github.com/tensorflow/tensorflow and checkout to d855adf
- TensorFlow version: -
- GCC/Compiler version (if compiling from source): aarch64-linux-gnu-g++ (Debian 8.3.0-6) 8.3.0

Please let me know if I need to provide any other information.

**Comment by clsdmgtk** [comment]
For some reason I was able to build both native and cross compile version today. However, I had to address the issue in https://github.com/google-coral/edgetpu/issues/201 which is not related to the original issue I saw yesterday.

Thanks for your attention on this issue.

**Comment by songshan0321** [comment]
> For some reason I was able to build both native and cross compile version today. However, I had to address the issue in [google-coral/edgetpu#201](https://github.com/google-coral/edgetpu/issues/201) which is not related to the original issue I saw yesterday.
> 
> Thanks for your attention on this issue.

May I know how did you solve this issue?
