### ISSUE TITLE
what  updates have been made in TF2.0 vs TF1.0 for c++ layer  such as  communication?

### ISSUE THREAD

**Issue by xingkong1994** [tensorflow/tensorflow#42644]
Recently  I  have been doing my model training  based on TF2.2(**without  eager**) and  TF1.10。The result shows the TF2.2 have better performance than  TF1.10,  such as the training speed。
so，I wanna know  what updates have been made in TF2.2(without eager) to make  my model train faster，such  as  communication in c++ layer  or  GPU driver?  
Hope to hear from you soon! Thanks!

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
