### ISSUE TITLE
How to print Quantization Aware Training Model Int8 weights without TFLite

### ISSUE THREAD

**Issue by wptkddms** [tensorflow/tensorflow#42659]
Hi, I I've been trying to [Quantization aware training in Keras example](https://www.tensorflow.org/model_optimization/guide/quantization/training_example)

I thought QAT Model weight data type is FP32, but it's real value represents fixed-point number.
I want to know how to print fixed-point number of weights without converting TFLite.

Thank you.

**Comment by ymodak** [comment]
After `model.fit` cell in the colab, save the quantization aware model in `h5` format using `model.save` method.
Further use [netron web browser](https://github.com/lutzroeder/netron) application to view the weights of the saved model.

**Comment by Ruomei** [comment]
> After `model.fit` cell in the colab, save the quantization aware model in `h5` format using `model.save` method.
> Further use [netron web browser](https://github.com/lutzroeder/netron) application to view the weights of the saved model.
> You may also use TensorBoard to visualize the op-level graph and inspect weights.

It is a good idea to visualize the weights in the output model this way. However, after QAT, what we can see are not INT8 weights but FP32 ones in a wrapper.
