### ISSUE TITLE
Data shape mismatch in custom training with 'train_step'  and `__get_item__`

### ISSUE THREAD

**Issue by Hamidreza3252** [tensorflow/tensorflow#42658]
- TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"` : `unknown 2.2.0`

## Problem description 
I am developing a custom model training by overriding `train_step` inherited from `tf.keras.Model` and `__getitem__` of my data generator inherited from `tf.keras.utils.Sequence`. The `__get_item__` method returns the following data:

`return [train_data, observed_data]`
where `train_data` and `observed_data` are numpy arrays with shape (20, 92)

However, when I receive them in `train_step` function, the shapes of these variables are not correct: 
In `train_step` method, I extract the data as follows: 
`train_data, observed_data = data[0]` 

and here is what I get: 

- `train_data Tensor("IteratorGetNext:0", shape=(None, None), dtype=float32)`
- `observed_data Tensor("IteratorGetNext:1", shape=(None, None), dtype=float32)`

## The expected behavior
I am not sure if this is a bug or not, but the expected shape of these tensors should be as good as what is specified in `__get_item__` method.

**Comment by Saduf2019** [comment]
@Hamidreza3252 
Please provide complete indented stand alone code for us to replicate the issue faced or if possible share a colab gist with the issue reported for us to analyse. Thanks!

**Comment by Hamidreza3252** [comment]
@Saduf2019 
I invited you to my repo, https://github.com/Hamidreza3252/HI-VAE . Please accept and you will get access to my code. 
The code is under development, so in order to see the issue, please follow these steps:
1. After clone, run `main_scripts.py` in debug mode
2. The code works up to line 117, `vae_model.fit`, so suggest to put a break-point there.
3. The `__get_item__` method is implemented in `hicae_data_generator.py`. Please look for the method and watch what it returns, (the numpy arrays)
4. The `train_step` function is overridden in `vae_base_model.py`. In lines between 205 and 214 you can watch the data passed to `train_step` method, as described in the issue above.

**Comment by Hamidreza3252** [comment]
@Saduf2019  and @gowthamkpr   Please let me know if you could reproduce my problem

**Comment by nikitamaia** [comment]
Hi @Hamidreza3252, are you still facing this issue? If so, please provide a minimal reproducible example.
