### ISSUE TITLE
TFLite C++ API docs seems broken

### ISSUE THREAD

**Issue by katherlee** [tensorflow/tensorflow#42654]
## URL(s) with the issue:

https://www.tensorflow.org/lite/api_docs/cc

## Description of issue (what needs changing):

The C++ API references for TFLite are missing many important components on tensorflow.org. For example, the docs for `tflite::FlatBufferModel` and `tflite::InterpreterBuilder` are completely gone, which used to be there the last time I checked, about two months ago.

**Comment by jvishnuvardhan** [comment]
@katherlee Looks like this was resolved. I have checked all the links on the TF page https://www.tensorflow.org/lite/api_docs/cc . All the links are working.

Please verify once and close the issue. Thanks!

**Comment by katherlee** [comment]
Indeed, thanks!
