### ISSUE TITLE
Cannot see per operator profiling in android studio with tensorflow lite models

### ISSUE THREAD

**Issue by anidh** [tensorflow/tensorflow#42655]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:

https://www.tensorflow.org/lite/performance/measurement#adding_trace_events_in_java_code

https://www.tensorflow.org/lite/performance/images/as_traces.png

## Description of issue (what needs changing):

I've added the trace sections to the code around the ``` interpreter.run() ``` command. When I start to profile the app I cannot see 
the per operator profiling as we can see in the second link.

### Clear description

This will help us in seeing how much time is being taken by each layer in the tflite model and we can change our models
according to that.

### My Code

``` 
Trace.beginSection("runInference");
 tflite_sr.run(ybuffer,sr_y_channel);
 Trace.endSection(); 
```

**Comment by amahendrakar** [comment]
@anidh,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by anidh** [comment]
Hi @amahendrakar ,
Thanks for replying. 
The code which i'm using to do the inference is 
``` public ByteBuffer sr_exec(byte[] inp)  {

    //gpuDelegate = new GpuDelegate();
    //tfliteOptions_sr.addDelegate((gpuDelegate));
    //tfliteOptions_sr.setNumThreads(numThreads);

    ByteBuffer ybuffer = ByteBuffer.allocateDirect(i_prod).order(ByteOrder.nativeOrder());
    ybuffer.rewind();
    ybuffer.put(y_channel_inp);

    ByteBuffer out_channel = ByteBuffer.allocateDirect(o_prod).order(ByteOrder.nativeOrder());

    try {
      Trace.beginSection("recognizeImage");
      //long startTime = System.currentTimeMillis();
      Trace.beginSection("runInference");
      tflite_sr.run(inp,out_channel);
      Trace.endSection();

      //long stopTime = System.currentTimeMillis();
      //long elapsedTime = stopTime - startTime;
      //System.out.println("&&&&&&&&&&&&&&&&&&&&&&"+elapsedTime);
      Trace.endSection();

    }
    catch (Exception e) {
      Log.d(TAG, "Error in Inference: "+e);
    }
    return out_channel;
  } ```

This is the code which is used for the inference, the ip buffer is of int type. When i do the profiling on the mobile device I am not able to see the layer wise timing as what has been mentioned in the documentation.

Thanks,
Anidh

**Comment by renjie-liu** [comment]
Hi Xunkai & Lu, can you guys take a look?

thanks

**Comment by lu-wang-g** [comment]
Hi Juho, could you please take a look at this issue?

**Comment by hajuho** [comment]
Hi Anidh,
I'd like to ask some details about the running environment.

- Can you see 'runInference' trace while you cannot see per-operator profiling result?

- Did you use org.tensorflow:tensorflow-lite:0.0.0-nightly for dependency? tensorflow-lite:2.3.0 or older stable aar libraries don't have this feature.

- Is the nightly library is up-to-date version? In your app's build.gradle file add 'changing = true', to make sure the library is automatically refreshed.
  implementation('org.tensorflow:tensorflow-lite:0.0.0-nightly') { changing = true }

- Did you run the command 'adb shell setprop debug.tflite.trace 1' before you started profiler?
  FYI, this property value is removed if you reboot the device.

- If everything is configured correctly, can you try with https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android or other tensorflow lite examples? When I tested with the examples, it worked well.

**Comment by anidh** [comment]
> * adb shell setprop debug.tflite.trace 1
Hi @hajuho ,

Thanks a lot for the quick reply.

**Comment by anidh** [comment]
Hi @hajuho ,

Thanks a lot for the quick reply.

> Can you see 'runInference' trace while you cannot see per-operator profiling result?
Yes I'm able to see the "runInference" trace when I'm doing a systrace.

>Did you use org.tensorflow:tensorflow-lite:0.0.0-nightly for dependency? tensorflow-lite:2.3.0 or older stable aar libraries don't have this feature.
I was using a stable build of the aar file. I changed it to ``` implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly' ```  

> Is the nightly library is up-to-date version? In your app's build.gradle file add 'changing = true', to make sure the library is automatically refreshed.
implementation('org.tensorflow:tensorflow-lite:0.0.0-nightly') { changing = true }

I was not using the nightly library and thus never used this flag. I have now included the flag.

> Did you run the command 'adb shell setprop debug.tflite.trace 1' before you started profiler?
FYI, this property value is removed if you reboot the device.

No, I was not using any such command and I have used this command now and it's now **showing** me all of the layers and timing of each and every layer.

I still have some doubt. The inference I did was for some 100 frames or such and continuously is the timing which is reported is cumulative or it is average over all of the runs. Moreover if I want to see the timing for only one of the frames is there nay method to do it for only one run?

Sorry I closed the issue by mistake and thus reopening the issue. Thanks a lot for your help.

**Comment by hajuho** [comment]
Hi Anidh,
I guess you may see a result like https://www.tensorflow.org/lite/performance/images/as_traces.png
The result windows of CPU profile consists of two panes. The left one is timeline view of traces and the right one is analysis report.
If you see the 'All threads' tab of analysis report, it shows the cumulative timing values.
You can click each section of running in the left pane. For example, if you click one frame of the 'runInference' sections, there will be a 'runInference' tab on the right pane and it will show the report for only that frame including children sections such as tflite op invocations. Moreover, if you click another frame of 'runInference' sections, the analysis report will show the value for the new frame.

**Comment by anidh** [comment]
> Hi Anidh,
> I guess you may see a result like https://www.tensorflow.org/lite/performance/images/as_traces.png
> The result windows of CPU profile consists of two panes. The left one is timeline view of traces and the right one is analysis report.
> If you see the 'All threads' tab of analysis report, it shows the cumulative timing values.
> You can click each section of running in the left pane. For example, if you click one frame of the 'runInference' sections, there will be a 'runInference' tab on the right pane and it will show the report for only that frame including children sections such as tflite op invocations. Moreover, if you click another frame of 'runInference' sections, the analysis report will show the value for the new frame.

@hajuho 

Thanks a lot. The steps you mentioned worked perfectly.
