### ISSUE TITLE
Problems with custom learning rate schedules and it's not clear why

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#42662]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: Yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Colab
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:
-   **TensorFlow installed from (source or binary)**:
-   **TensorFlow version (use command below)**: 2.3.0
-   **Python version**:
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:
-   **GPU model and memory**:
-   **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with:

```bash
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
```

### Describe the problem

I referred to [this example](https://www.tensorflow.org/tutorials/text/transformer) and especially the callback presented here. So, I decided to write out a callback inspired by [this one](https://github.com/facebookresearch/swav/blob/master/main_swav.py#L175). Basically it combines warm-ups and cosine decays. 

Here's how I coded it up - 

```python
class CustomSchedule(tf.keras.optimizers.schedules.LearningRateSchedule):
    def __init__(self, base_lr=0.1, end_lr=0.001, warmup_steps=390*5):
        super(CustomSchedule, self).__init__()

        self.base_lr = base_lr
        self.end_lr = end_lr
        self.warmup_steps = warmup_steps
    
    def __call__(self, step=390*35):
        warmup_lr_schedule = tf.linspace(0., self.base_lr, self.warmup_steps)
        iters = tf.range(step, dtype=tf.float32) 
        cosine_lr_schedule = tf.convert_to_tensor([self.end_lr + 0.5 * (self.base_lr - self.end_lr) * (1 + \
                        tf.math.cos(tf.constant(math.pi) * t / (step))) for t in iters])
        lr_schedule = tf.concat([warmup_lr_schedule, cosine_lr_schedule], axis=0)
        
        return lr_schedule
```

I verified if this is the one I wanted and indeed it is - 

![image](https://user-images.githubusercontent.com/22957388/91200950-761e8180-e71d-11ea-93aa-abee10df7f2b.png)

But when I pass this callback inside an optimizer I run into weird stuff - 

```
OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.
```

What am I missing out on?

### Source code / logs

[Colab Notebook](https://colab.research.google.com/gist/sayakpaul/0f75d0177cf6824f80fcc62cd49dc78f/scratchpad.ipynb)

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/b8ab5045ae609f60d75e430479f3d868/42662.ipynb). Thanks!

**Comment by sayakpaul** [comment]
Any updates?

**Comment by HarrisDePerceptron** [comment]
Similar issue:
```
class CustomSchedule(tf.keras.optimizers.schedules.LearningRateSchedule):
  def __init__(self, warmup_steps=1e4):
    super().__init__()

    self.warmup_steps = tf.cast(warmup_steps, tf.float32)
    
  def __call__(self, step):
    step = tf.cast(step, tf.float32)
    m = tf.maximum(self.warmup_steps, step)
    m = tf.cast(m, tf.float32)
    lr = tf.math.rsqrt(m)
    
    return lr

```

```
learning_rate_fn = CustomSchedule()
optimizer = tf.keras.optimizer.Adam(learning_rate_fn)

model.compile(optimizer=optimizer, ...)
model.fit(dataset, epochs=1)
```

### Error:
**TypeError: To be compatible with tf.eager.defun, Python functions must return zero or more Tensors; in compilation of <function Model.make_train_function.<locals>.train_function at 0x7fdf2c2b9c80>, found return value of type <class '__main__.CustomSchedule'>, which is not a Tensor.**

**Comment by omalleyt12** [comment]
@sayakpaul Thanks for the issue! The `LearningRateSchedule.__call__` method should accept a `Tensor` `step` argument and output a `Tensor` that represents the learning rate to use for that particular step. It looks like your subclass is outputting an entire schedule every step rather than the learning rate for that particular step.

**Comment by HarrisDePerceptron** [comment]
@omalleyt12 any hints to my issue?

**Comment by sayakpaul** [comment]
@omalleyt12 okay. So, how should I approach it if I were to use the schedule I mentioned in the first place?
