### ISSUE TITLE
Slow training speed of  tensorflow.keras.layers.SeparableConv2D and tensorflow.keras.layers.DepthwiseConv2D

### ISSUE THREAD

**Issue by ashish-221b** [tensorflow/tensorflow#42664]
I am trying to train a Fully Convolutional Model with fast inference
So instead of **tensorflow.keras.layers.Conv2d**, I tried using **tensorflow.keras.layers.SeparableConv2D**.

The SeparableConv2D model, when benchmarked using [TensorFlow.js Model Benchmark](https://tensorflow.github.io/tfjs/e2e/benchmarks/local-benchmark/index.html), performs better than Conv2D model.

But while training on GPU, the SeparableConv2D is extremely slow when compared to the Conv2D model.

**System information**
- Google Colab
- TensorFlow version 2.3.0 :
- Python version: 3.6.9

I have created a simple experiment to illustrate the issue. [Colab Notebook](https://colab.research.google.com/drive/1gZTZcj6VJfMEJS_5e2Lc3kGJKdbgnER5?usp=sharing)

The difference in the training time is very large. I also tried DepthwiseConv2D followed by pointwise Conv2d (kernel size 1)

It has come to my knowledge that slow speed of DepthwiseConv2D is a known issue. I was wondering if there is any fix or work around.

**Comment by cscribano** [comment]
### Describe the problem

I'm experiencing the very same issue, standard Conv2d trains >2x slower than Depthwise + Pointwise Conv (wich are the building blocks of SeparableConv2D), [HERE](https://gist.github.com/cscribano/d4c8480167cb53a25245ed6197b8ad7b) a minimal reproducible example (requires [profiler](https://blog.tensorflow.org/2020/04/introducing-new-tensorflow-profiler.html)).

### Source code / logs

Results obtained by running the above example:
Device Computing Time: 18.1ms (**Conv2D**), 43.9ms (**Depthwise + Pointwise**)

### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: YES
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Red Hat Enterprise 7.6 (Server)
-   **TensorFlow installed from (source or binary)**: both tested with no changes
-   **TensorFlow version**: 2.2.1
-   **Python version**: 3.7.9
-   **CUDA/cuDNN version**: CUDA 10.1, CuDNN 7.6.5
-   **GPU model and memory**: Nvidia Tesla V100 (16GB)

**Comment by sachinprasadhs** [comment]
The Colab link which you have provided is expired, could you please share the code again to reproduce the reported behavior and there is a possibility of improvement in performance in the latest Tensorflow version. Thanks!
