### ISSUE TITLE
ValueError in tf.data.Dataset.from_tensor_slices when array contains a mixture of integers and strings

### ISSUE THREAD

**Issue by KieranLitschel** [tensorflow/tensorflow#42677]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes (variation of Load a pandas.DataFrame tutorial)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS (Bionic Beaver)
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.6.9

**Describe the current behavior**

When a DataFrame ```df``` contains a mixture of integers and strings, calling ```tf.data.Dataset.from_tensor_slices(df.values)``` results in the error ```ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type int).```.

**Describe the expected behavior**

I don't think this should crash. I think it should produce a TensorSliceDataset object.

**Standalone code to reproduce the issue**

Reproduced the issue here: https://colab.research.google.com/drive/15qben_czJvRS80pVZyiltDO4FDzmHryg?usp=sharing

The code is loosely based on the "Load a pandas.DataFrame" tutorial, except I don't one-hot encode the "thal" column, as I have a similar use-case where I have a combination of sentences and numbers as features.

**Comment by KieranLitschel** [comment]
I did discover that using ```tf.data.Dataset.from_tensor_slices(df.to_dict('list'))``` seems to have the desired effect, but I don't understand why the other way does not work

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3, nightly version (`2.4.0-dev20200826`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/93aa47b5f037d0bfcbe20a64078cb3df/untitled271.ipynb#scrollTo=7D9CJeWslVpz).Thanks!

**Comment by aaudiber** [comment]
@KieranLitschel, the inputs to `from_tensor_slices` need to be tensors or something convertible to tensors. A tensor has a single dtype (e.g. float64) -- tensors containing mixed types (e.g. strings and floats) are not allowed.

The guide at https://www.tensorflow.org/tutorials/load_data/pandas_dataframe converts the `thal` column to be numerical instead of a string:

>df['thal'] = pd.Categorical(df['thal'])
df['thal'] = df.thal.cat.codes

**Comment by nikitamaia** [comment]
@KieranLitschel one additional resource you might find helpful -- You can see a similar example in the [guides here](https://www.tensorflow.org/tutorials/structured_data/feature_columns) that creates a dataset from a pandas df with `tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))` and then uses feature columns.

**Comment by KieranLitschel** [comment]
Thank you for getting back to me, I've now realized `tf.data.Dataset.from_tensor_slices(df.to_dict('list'))` does do exactly what I wanted. But also I realized if I'm having a mixture of numeric and string input, using the Functional API would make more sense, which also means I can separate features of different types into different datasets, so that also solves the problem.
