### ISSUE TITLE
tf.contrib.crf.crf_decode ValueError: Input size (depth of inputs) must be accessible via shape inference, but saw value None.

### ISSUE THREAD

**Issue by yjiangling** [tensorflow/tensorflow#42672]
When I use the tf.contrib.crf.crf_decode function to find the most probably path in CTC. **The Code is:**

`import numpy as np
import tensorflow as tf

xs=tf.constant(np.random.rand(3,10,5),dtype=tf.float32)
xlen=tf.constant([8,10,9],dtype=tf.int32)
ys=tf.constant([[4,1,0,0],[2,4,3,3],[3,1,2,0]],dtype=tf.int32)
ylen=tf.constant([2,4,3],dtype=tf.int32)

> def viterbi_search(yt,xlen,ys,ylen):
>     
>     pad=tf.zeros_like(ys)
>     yb=tf.reshape(tf.stack([ys,pad],axis=-1),[tf.shape(ys)[0],-1])
>     yb=tf.concat([tf.zeros([tf.shape(ys)[0],1],dtype=tf.int32),yb],axis=-1) #插入blank之后的标签
> 
>     def search_best_path(yt,xlen,ys,ylen,yb):
>         # 构建概率发射矩阵 potentials
>         yt=tf.gather(yt,yb,axis=-1)
>         blen=tf.shape(yb)[0]
>         m=tf.reshape(tf.concat([yt[0,:2],tf.zeros(blen-2)],axis=0),(1,-1))
>         n=tf.reshape(tf.concat([tf.zeros(blen-2),yt[-1,-2:]],axis=0),(1,-1))
>         yt=tf.concat([m,yt[1:-1,:],n],axis=0)
> 
>         # 构建状态转移矩阵 transition_params
>         const=tf.constant([[2,3],[2,2]],dtype=tf.int32)
>         k=tf.cast(tf.math.equal(ys[:-1]-ys[1:],0),tf.int32)
>         tlen=tf.reshape(tf.gather(const,k),(-1,))
>         tlen=tf.concat([tlen,[2,2,1]],axis=0)+tf.range(blen)
> 
>         trans=tf.map_fn(lambda k:tf.concat([tf.ones(k,dtype=tf.int32),tf.zeros(blen-k,dtype=tf.int32)],axis=0),tlen)
>         trans=tf.math.log(tf.linalg.band_part(tf.cast(trans,dtype=tf.float32),0,-1))
> 
>         yt=tf.math.log(tf.expand_dims(yt,axis=0))
>         xlen=tf.reshape(xlen,shape=[-1])
>         yl,_=tf.contrib.crf.crf_decode(potentials=yt,transition_params=trans,sequence_length=xlen)
>         yf=tf.gather(yb,yl[0]) #每一帧的实际对齐结果 CTC sequence
>         ref=tf.concat([[0],yf[:-1]],axis=0)
>         yr=tf.where(tf.equal(yf,ref),tf.subtract(yf,ref),yf) #去重以后的帧级别对齐结果 trigger sequence
>         return tf.squeeze(tf.where(yr>0))
>     pad_len=tf.reduce_max(ylen)-ylen
>     def loop_align(i,zs):
>         k=search_best_path(yt[i][:xlen[i]],xlen[i],ys[i][:ylen[i]],ylen[i],yb[i][:ylen[i]*2+1])
>         zi=tf.concat([k,tf.zeros(pad_len[i],dtype=tf.int64)],axis=0)
>         zs=zs.write(i,zi) 
>         return i+1,zs
>     zs=tf.TensorArray(dtype=tf.int64,size=0,dynamic_size=True)
>     _,zs=tf.while_loop(lambda i,zs:i<tf.shape(yt)[0],loop_align,[0,zs])
>     zs=tf.cast(zs.stack(),dtype=tf.int32) #triggered sequence
>     return zs

zs=viterbi_search(xs,xlen,ys,ylen)`

**It gives the following error:**
  File "/media/huaxin/tcl1/asr/yujiangling/Stream_Transformer/model.py", line 135, in search_best_path
    yl,_=tf.contrib.crf.crf_decode(potentials=yt,transition_params=trans,sequence_length=xlen)
  File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/tensorflow/contrib/crf/python/ops/crf.py", line 589, in crf_decode
    false_fn=_multi_seq_fn)
  File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/tensorflow/python/layers/utils.py", line 202, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/tensorflow/python/framework/smart_cond.py", line 59, in smart_cond
    name=name)
  File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2097, in cond
    orig_res_f, res_f = context_f.BuildCondBranch(false_fn)
  File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1930, in BuildCondBranch
    original_result = fn()
  File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/tensorflow/contrib/crf/python/ops/crf.py", line 560, in _multi_seq_fn
    dtype=dtypes.int32)
  File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 664, in dynamic_rnn
    dtype=dtype)
  File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 738, in _dynamic_rnn_loop
    "Input size (depth of inputs) must be accessible via shape inference,"
ValueError: Input size (depth of inputs) must be accessible via shape inference, but saw value None.

It seems that when the tensor was send to the TensorFlow loop (tf.while_loop), the dimension of the tensor become None? Then the function tf.contrib.crf.crf_decode can not work? So, how can I solve it?

**Comment by ravikyram** [comment]
@yjiangling 

Which tensorflow version you are using?

tensorflow.contrib is being removed in version TF 2.x and it works in only TF 1.x. 
For more info see this https://www.tensorflow.org/guide/migrate#a_note_on_slim_contriblayers.

**Comment by yjiangling** [comment]
> @yjiangling
> 
> Which tensorflow version you are using?
> 
> tensorflow.contrib is being removed in version TF 2.x and it works in only TF 1.x.
> For more info see this https://www.tensorflow.org/guide/migrate#a_note_on_slim_contriblayers.
> For TF 2.X you may try following:
> A subset of contrib functions are not part of TF Addons(https://github.com/tensorflow/addons).
> You have to install addons package separately.
> You can also raise a PR on the addons to repo to add feature not already available.
> 
> Also, request you to share colab link or simple standalone code with proper indentation to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

Thanks a lot for the reply. I use the TensorFlow 1.12. Ok, I will try it. BTW, the code give before is the whole codes, it can be run in any environment as long as the package of numpy and tensorflow are installed. You may try it. Thanks again for your patience.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 1.12, 1.15 and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/55d14d41d001a31960118cc183db47ee/untitled291.ipynb).Thanks!

**Comment by yjiangling** [comment]
> I have tried in colab with TF version 1.12, 1.15 and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/55d14d41d001a31960118cc183db47ee/untitled291.ipynb).Thanks!

Thank you for the reply. I finally find out the reasons. It turns out that the function of tf.contrib.crf.crf_decode in TensorFlow implemented with dynamic_rnn, in source code of dynamic_rnn function in TensorFlow (tf.nn.dynamic_rnn function is assigned in tensorflow/python/ops/rnn.py), it assume that the output shape of the RNN net could not be None, so I rewrite a new function "crf_decode" refer to the source code and finally solved it.

**Comment by yjiangling** [comment]
Since the problem has been solved, I will close this issue. Thanks a agin for everyone.
