### ISSUE TITLE
[docs] `nbfmt` removes output cells but does not clear "execution count"

### ISSUE THREAD

**Issue by mpharrigan** [tensorflow/tensorflow#42687]
Using `python -m tensorflow_docs.tools.nbfmt` on an executed notebook clears the output cells but leaves the "execution count" filled in, which can result in unnecessary diff noise and only really makes sense in the context of a filled-out notebook. For reference, the "all output -> clear" jupyter menu option sets all the execution counts to `null`.

**Comment by lamberta** [comment]
Thanks for the report, @mpharrigan 
Hopefully this fixed it: https://github.com/tensorflow/docs/commit/3dca32f59ff76a1fed82f5e799a4dc38e498b7c6

**Comment by mpharrigan** [comment]
Thanks!
