### ISSUE TITLE
Timing Discrepency betweeen Tflite Benchmarking Tool and Android Studio Inference Time

### ISSUE THREAD

**Issue by dhruv-arcot** [tensorflow/tensorflow#42684]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 1.15
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
While Benchmarking the model using the benchmarking tool the timing reported did not match that as viewed while running inference on the model on an APK. In almost all instances, the timing reported was almost twice as that seen on the Benchmarking tool. The GPU delegate is used to run inference on this model. 
To measure timing on the APK we employed both the methods. 
i) Using the getLastNativeInferenceDurationNanoseconds() function provided by Tflite
ii) Using the SystemClock.uptimeMillis() function provided in the os.SystemClock library. 
   The code for the same is:
            long str_time = SystemClock.uptimeMillis();
            tflite_intep.run(inp,out);
            System.out.println("Inference Time :"+(SystemClock.uptimeMillis()-str_time)); 

In this instance the output from both the getLastNativeInferenceDurationNanoseconds() as well as the Benchmarking tool is 35.421 ms while that shown in the logcat from the SystemClock function is 70.33 ms. 

**Describe the expected behavior**

The timing shown in all 3 scenarios need to match or at least be within a reasonable amount from each other. 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Please do let me know if any furthur information is needed.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
