### ISSUE TITLE
ImageDataGenerator should have a verbosity argument

### ISSUE THREAD

**Issue by jondo** [tensorflow/tensorflow#42681]
**System information**
- TensorFlow version (you are using): 2.3.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
When calling [`tensorflow.keras.preprocessing.image.ImageDataGenerator.flow_from_directory`](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/ImageDataGenerator#flow_from_directory), currently a message like `Found 1437 images belonging to 2 classes.` is printed.

I suggest adding an optional keyword argument `verbose` with default setting `verbose=1` to this function, such that `verbose=0` suppresses this printed message. See e.g. the `verbose` keywords of [`tf.keras.Model.fit`](https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit), or of the [`EarlyStopping`](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/EarlyStopping) or [`ModelCheckpoint`](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/ModelCheckpoint) callbacks.

**Will this change the current api? How?**
This will add an optional keyword argument.

**Who will benefit with this feature?**

* Everyone who needs to call this function repeatedly in order to loop over different `batch_size` values during hyperparameter tuning. In this case, the repeated message is uninteresting and distracts from the interesting output and should therefore be omittable.
* Everyone who upgraded from standalone Keras (which did not show this message, e.g. version 2.2.4), who wants to get the same output as before.

**Comment by jondo** [comment]
Btw., standalone Keras (at least 2.2.4) did not print this message.

**Comment by anuragcp** [comment]
I am a new contributor to tensorflow, and changed and added feature. But i can't push branch. shows error like this

`remote:` Permission to tensorflow/tensorflow.git denied to anuragcp.

**Comment by ashwin-phadke** [comment]
Try this :

`git pull upstream master`
`git push`
This will update your fork to the latest commit from the upstream tensorflow.
I hope you have created a different branch for whatever your change is.
Now push your change to your fork's branch and not the tensorflow branch.
Once you push your changes you can then automatically see created the PR for you to finish from the Github website.

**Comment by jondo** [comment]
@anuragcp, you have to push it to your own fork, then create a pull request.

**Comment by anuragcp** [comment]
Okey thanks. Let me check.

**Comment by jondo** [comment]
I now found the relevant code location: It's [in directory_iterator.py](https://github.com/keras-team/keras-preprocessing/blob/f69929ff67518d89274ae4790d9517dc4f1e5ec1/keras_preprocessing/image/directory_iterator.py#L144) of the project keras_preprocessing!

Here is the corresponding issue: https://github.com/keras-team/keras-preprocessing/issues/304 .

**Comment by ashwin-phadke** [comment]
Hi @jondo , is this what you are looking for to implement, I don't know how correct this https://www.tensorflow.org/api_docs/python/tf/compat/v1/logging is as it is still in version 1 and there seem to be no ports to 2 and the only reference to it I found was for `tf.autograph.set_verbosity`. I hope this helps.
An simple high-level call I found was in `keras.callbacks`

`
if self.verbose > 0:
print('\nEpoch %05d: saving model to %s' % (epoch + 1, filepath))
` 

in `tf./python./keras./callbacks` using `progbar`

**Comment by jondo** [comment]
According to the [release notes](https://github.com/tensorflow/tensorflow/releases/tag/v2.3.0), current Tensorflow 2.3.0 introduced a new Keras dataset generation utility (emphasis added):

> [`image_dataset_from_directory`](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image_dataset_from_directory) is a utility based on `tf.data.Dataset`, meant to replace the **legacy `ImageDataGenerator`**. It takes you from a structured directory of images to a labeled dataset, in one function call. Note that it doesn't perform image data augmentation (which is meant to be done using preprocessing layers).

This means that I'll simply comment out the annoying `print` command locally for now.

**Comment by sachinprasadhs** [comment]
[tf.keras.preprocessing.image.ImageDataGenerator](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/ImageDataGenerator) will be deprecated in upcoming Tensorflow version and  is not recommended for new code. Prefer loading images with [tf.keras.utils.image_dataset_from_directory](https://www.tensorflow.org/api_docs/python/tf/keras/utils/image_dataset_from_directory) and transforming the output [tf.data.Dataset](https://www.tensorflow.org/api_docs/python/tf/data/Dataset) with preprocessing layers.
