### ISSUE TITLE
Cannot build network with a dict input_spec

### ISSUE THREAD

**Issue by banerjs** [tensorflow/tensorflow#42691]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04 (in docker container)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.6.9
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.2, N/A
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Cannot build a model with a `dict` input_spec (`model.build`)

**Describe the expected behavior**

The model should be able to build the graph with a `dict` input_spec:

1. We can call a model with dictionary inputs, so specifying that spec as dictionary seems natural
2. I believe this is what the developers intended too, given [this line](https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/keras/engine/network.py#L650) in the current master branch. 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
In [33]: class TestModel(keras.Model):
    ...:     def __init__(self, *args, **kwargs):
    ...:         super(TestModel, self).__init__(*args, **kwargs)
    ...:         self.layer = keras.layers.Dense(10)
    ...:     def call(self, inputs):
    ...:         return {'b': self.layer(inputs['a'])}
    ...: 

In [34]: model = TestModel()

In [35]: model.build({ 'a': (None, 5) })
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-35-f5e425698cd1> in <module>
----> 1 model.build({ 'a': (None, 5) })

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py in build(self, input_shape)
    633                        'Please specify a batch input shape of type tuple or '
    634                        'list of input shapes. User provided '
--> 635                        'input type: {}'.format(type(input_shape)))
    636
    637     if input_shape and not self.inputs:

ValueError: Specified input shape is not one of the valid types. Please specify a batch input shape of type tuple or list of input shapes. User provided input type: <class 'dict'>

In [36]: model({'a': np.random.random((3,5)).astype(np.float32)})
Out[36]: 
{'b': <tf.Tensor: shape=(3, 10), dtype=float32, numpy=
 array([[ 0.57159793, -0.54181933, -0.05867613, -0.13133162,  0.33426586,
          0.88725936,  0.6102787 ,  0.25660542, -0.32508045,  0.18882477],
        [ 0.5146243 , -0.07790124, -0.13295858,  0.33439606,  0.6062204 ,
          0.67318   ,  0.7965131 , -0.09740189, -0.49425927, -0.3331495 ],
        [ 0.828179  , -0.3307852 , -0.49201646, -0.16802055,  0.44089833,
          0.8766354 ,  0.92791915,  0.28562796, -0.8893677 , -0.428018  ]],
       dtype=float32)>}
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@banerjs 
I am able to replicate the issue reported, please find [gist here](https://colab.research.google.com/gist/Saduf2019/332a52117a258cdab41d5502b51654c9/untitled389.ipynb).
Please refer to [this link](https://stackoverflow.com/questions/33684657/issue-feeding-a-list-into-feed-dict-in-tensorflow) and let us know if it helps.

**Comment by banerjs** [comment]
Yeah, I get that and I do have a work-around for the problem of building with a dictionary (so it's not a critical bug for me).

However, it is strange behaviour because:

1. The `ValueError` is raised on [line 632](https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/keras/engine/network.py#L632) where the `input_shape` can only be of types `tuple, list, TensorShape`; and yet later in the same function in [line 650](https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/keras/engine/network.py#L650) the function checks to see if the variable is a dictionary and handles that condition.
1. The fact that we can pass inputs as a dictionary to the model seems to suggest that when we want to build the model with placeholder shapes specified as a dictionary, the API should allow that too.

**Comment by yongtang** [comment]
Added a PR #42969 for the fix.

**Comment by jvishnuvardhan** [comment]
@banerjs Looks like this was resolved in recent `tf-nightly` and stable `TF2.4.1`. I don't see any error when I ran your code with `tf-nightly`. Please check a gist [here](https://colab.research.google.com/gist/jvishnuvardhan/720245bfc87ccff286f09b725a447f59/untitled389.ipynb).

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by banerjs** [comment]
Sorry, I no longer have access to the codebase or machines that I tested this on initially. I'm happy to have you close this if this does indeed work (running the colab was fine for me)
