### ISSUE TITLE
warning: 404 not found

### ISSUE THREAD

**Issue by electricSamarth** [tensorflow/tensorflow#42690]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution : SMP Debian 4.19.118-2 (2020-04-29)
- TensorFlow installed from : source
- TensorFlow version: 2.3
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 3.3
- GCC/Compiler version (if compiling from source):8.3
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the problem**
while building I get the following warning what does it mean?
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/642cb7865f35ad7dbac78d716fcddaff561e8639.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build --config=mkl  //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gowthamkpr** [comment]
This might be a network error. Please take a look at this [issue](https://github.com/google/mediapipe/issues/533) and let me know if it helps.

**Comment by electricSamarth** [comment]
Nope, It happens repeatedly

**Comment by melrobin** [comment]
I am experiencing the same problem.

**Comment by mihaimaruseac** [comment]
It is a warning, the compilation process continues from the other mirror.

**Comment by melrobin** [comment]
The compilation fails with these types of error messages:
ERROR:
/home/melrobin/.cache/bazel/_bazel_melrobin/f2116cf848eff0a1d187a7773c1fea53/external/com_google_protobuf/BUILD:301:11:
C++ compilation of rule '@com_google_protobuf//:protoc_lib' failed (Exit
1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc
-MD -MF
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/code_generator.d
... (remaining 49 argument(s) skipped)

Are they not related?

**Comment by mihaimaruseac** [comment]
No, the error you pointed is from protobuf, whereas the warning is from llvm.

**Comment by electricSamarth** [comment]
Thanks @mihaimaruseac!

**Comment by ichisadashioko** [comment]
Hi @electricSamarth . Did you find the work-around?

**Comment by jml1996jsonhost** [comment]
Does anyone here have any insight about the problem described at the bottom of this stackoverflow post: https://stackoverflow.com/questions/65402617/tensorflow-automl-model-in-react
