### ISSUE TITLE
Post Quantization with TensorFlow in Python

### ISSUE THREAD

**Issue by giahi** [tensorflow/tensorflow#42707]
I am totally beginner in Python and I have a Convolutional Neural Network which consists of some conv1D maxpooling1D and dense layers

I need to Quantize this model to integer for running on FPGA

I follow post-Quantization trough this link: https://www.tensorflow.org/lite/performance/post_training_integer_quant

But I got a strange error which is:

RuntimeError: tensorflow/lite/kernels/conv.cc:316 input->dims->data[3] != filter->dims->data[3] (4 != 3)Node number 1 (CONV_2D) failed to prepare

But I don’t have any conv2D at all.

I would be very grateful if anyone can help me.

**Comment by amahendrakar** [comment]
@giahi,
In order to expedite the trouble-shooting process, could you please provide the TensorFlow version, the complete code to reproduce the issue and the dataset you are using. Thanks!
