### ISSUE TITLE
error: undefined reference to '__umoddi3'

### ISSUE THREAD

**Issue by zhangqiang-hf** [tensorflow/tensorflow#42700]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Loongnix OS(based on Fedora) with kernel:Linux localhost.localdomain 3.10.84-22.fc21.loongson.7.mips64el
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version: 2.4.0
- Python version: Python：2.7.9      Python3：3.4.1
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):3.4.1
- GCC/Compiler version (if compiling from source):gcc version 7.3.1 20180303 (Red Hat 7.3.1-6) (GCC)
- CUDA/cuDNN version:no cuda
- GPU model and memory: no gpu mode 

**Describe the problem**
when I build the tensorflow 2.4.0 source code on loongson platform（arch：mips64）use bazel 3.4.1.
[loongson@localhost tensorflow-206]$ ./configure 
You have bazel 3.4.1- (@non-git) installed.
Please specify the location of python. [Default is /usr/bin/python3]: 
Found possible Python library paths:
  /usr/lib64/python3.4/site-packages
  /usr/lib/python3.4/site-packages
Please input the desired Python library path to use.  Default is [/usr/lib64/python3.4/site-packages]
Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.
Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.
Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.
Do you wish to download a fresh release of clang? (Experimental) [y/N]: n
Clang will not be downloaded.
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 
Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.
Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=ngraph      	# Build with Intel nGraph support.
	--config=numa        	# Build with NUMA support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
	--config=v2          	# Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=noaws       	# Disable AWS S3 filesystem support.
	--config=nogcp       	# Disable GCP support.
	--config=nohdfs      	# Disable HDFS support.
	--config=nonccl      	# Disable NVIDIA NCCL support.
Configuration finished

and then build:    bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
build  failed! log as below:
Repository rule git_repository defined at:
  /home/loongson/.cache/bazel/_bazel_loongson/f0c20e6eab3cd4f95dcf1e27683765aa/external/bazel_tools/tools/build_defs/repo/git.bzl:195:33: in <toplevel>
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (161 packages loaded, 27000 targets configured).
INFO: Found 1 target...
ERROR: /home/loongson/.cache/bazel/_bazel_loongson/f0c20e6eab3cd4f95dcf1e27683765aa/external/com_google_protobuf/BUILD:412:10: Linking of rule '@com_google_protobuf//:protoc' failed (Exit 1)
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/command_line_interface.o:command_line_interface.cc:function std::_Hashtable<std::string, std::pair<std::string const, google::protobuf::compiler::CommandLineInterface::GeneratorContextImpl*>, std::allocator<std::pair<std::string const, google::protobuf::compiler::CommandLineInterface::GeneratorContextImpl*> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_rehash(unsigned long, unsigned long const&): error: undefined reference to '__umoddi3'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/command_line_interface.o:command_line_interface.cc:function std::_Hashtable<std::string, std::pair<std::string const, google::protobuf::compiler::CommandLineInterface::GeneratorContextImpl*>, std::allocator<std::pair<std::string const, google::protobuf::compiler::CommandLineInterface::GeneratorContextImpl*> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_rehash(unsigned long, unsigned long const&): error: undefined reference to '__umoddi3'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/command_line_interface.o:command_line_interface.cc:function std::__detail::_Map_base<std::string, std::pair<std::string const, google::protobuf::compiler::CommandLineInterface::GeneratorContextImpl*>, std::allocator<std::pair<std::string const, google::protobuf::compiler::CommandLineInterface::GeneratorContextImpl*> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>, true>::operator[](std::string const&): error: undefined reference to '__umoddi3'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/command_line_interface.o:command_line_interface.cc:function std::__detail::_Map_base<std::string, std::pair<std::string const, google::protobuf::compiler::CommandLineInterface::GeneratorContextImpl*>, std::allocator<std::pair<std::string const, google::protobuf::compiler::CommandLineInterface::GeneratorContextImpl*> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>, true>::operator[](std::string const&): error: undefined reference to '__umoddi3'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/cpp_padding_optimizer.o:cpp_padding_optimizer.cc:function __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > > std::_V2::__rotate<__gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > > >(__gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, std::random_access_iterator_tag) [clone .isra.94]: error: undefined reference to '__moddi3'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/cpp_padding_optimizer.o:cpp_padding_optimizer.cc:function __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > > std::_V2::__rotate<__gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > > >(__gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, std::random_access_iterator_tag) [clone .isra.94]: error: undefined reference to '__moddi3'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/cpp_padding_optimizer.o:cpp_padding_optimizer.cc:function __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > > std::_V2::__rotate<__gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > > >(__gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, std::random_access_iterator_tag) [clone .isra.94]: error: undefined reference to '__moddi3'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/cpp_padding_optimizer.o:cpp_padding_optimizer.cc:function __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > > std::_V2::__rotate<__gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > > >(__gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, std::random_access_iterator_tag) [clone .isra.94]: error: undefined reference to '__moddi3'
bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/tokenizer.o:tokenizer.cc:function google::protobuf::io::Tokenizer::ParseInteger(std::string const&, unsigned long, unsigned long*): error: undefined reference to '__udivdi3'
bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/tokenizer.o:tokenizer.cc:function google::protobuf::io::Tokenizer::ParseInteger(std::string const&, unsigned long, unsigned long*): error: undefined reference to '__udivdi3'
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 452.104s, Critical Path: 44.81s
INFO: 307 processes: 307 local.
FAILED: Build did NOT complete successfully

**Provide the exact sequence of commands / steps that you executed before running into the problem**
./configure
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by zhangqiang-hf** [comment]
could you please help me to resolve this build error? 
Thank you!

**Comment by ravikyram** [comment]
@zhangqiang-hf 

Looking the error log it seems you are using python 3.4 .As per the tested build configurations Tensorflow supports python 3.5-3.8.
Please, see tested build configurations from [here](https://www.tensorflow.org/install/source#tested_build_configurations) and make sure you have installed all compatible dependencies.Thanks!

**Comment by zhangqiang-hf** [comment]
> @zhangqiang-hf
> 
> Looking the error log it seems you are using python 3.4 .As per the tested build configurations Tensorflow supports python 3.5-3.8.
> Please, see tested build configurations from [here](https://www.tensorflow.org/install/source#tested_build_configurations) and make sure you have installed all compatible dependencies.Thanks!

Dear sir,
  Thank you for your reply! The build failed "undefined reference to '__moddi3'" and so on, is caused by python version?
 I searched the same issue"undefined reference to '__moddi3'" from the internet, it said add "-fno-tree-scev-cprop" 
   http://www.voidcn.com/article/p-vphyzuwg-py.html

**Comment by zhangqiang-hf** [comment]
but it is still built fail

> > @zhangqiang-hf
> > Looking the error log it seems you are using python 3.4 .As per the tested build configurations Tensorflow supports python 3.5-3.8.
> > Please, see tested build configurations from [here](https://www.tensorflow.org/install/source#tested_build_configurations) and make sure you have installed all compatible dependencies.Thanks!
> 
> Dear sir,
> Thank you for your reply! The build failed "undefined reference to '__moddi3'" and so on, is caused by python version?
> I searched the same issue"undefined reference to '__moddi3'" from the internet, it said add "-fno-tree-scev-cprop"
> http://www.voidcn.com/article/p-vphyzuwg-py.html  
but it is still built fail

**Comment by zhangqiang-hf** [comment]
Dear Sir，
I have used the python3.7.9, but still failed! log as bellow:
[loongson@localhost tensorflow]$ bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=171
INFO: Reading rc options for 'build' from /home/loongson/tensorflow/tensorflow-206/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/loongson/tensorflow/tensorflow-206/tensorflow/.bazelrc:
  'build' options: --action_env=BAZEL_LINKLIBS=-l%:///opt/rh/devtoolset-7/root/usr/lib/gcc/mips64el-redhat-linux/7/libstdc++.a --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from /home/loongson/tensorflow/tensorflow-206/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/opt/python/python-3.7.9/lib/python3.7/site-packages --python_path=/usr/bin/python3 --config=xla --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file /home/loongson/tensorflow/tensorflow-206/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/loongson/tensorflow/tensorflow-206/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /home/loongson/tensorflow/tensorflow-206/tensorflow/.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:opt in file /home/loongson/tensorflow/tensorflow-206/tensorflow/.tf_configure.bazelrc: --copt=-march=native --copt=-Wno-sign-compare --host_copt=-march=native --define with_default_optimizations=true
INFO: Found applicable config definition build:linux in file /home/loongson/tensorflow/tensorflow-206/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/loongson/tensorflow/tensorflow-206/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule git_repository defined at:
  /home/loongson/.cache/bazel/_bazel_loongson/f0c20e6eab3cd4f95dcf1e27683765aa/external/bazel_tools/tools/build_defs/repo/git.bzl:195:33: in <toplevel>
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (387 packages loaded, 30985 targets configured).
INFO: Found 1 target...
ERROR: /home/loongson/.cache/bazel/_bazel_loongson/f0c20e6eab3cd4f95dcf1e27683765aa/external/com_google_protobuf/BUILD:412:10: Linking of rule '@com_google_protobuf//:protoc' failed (Exit 1)
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/command_line_interface.o:command_line_interface.cc:function std::_Hashtable<std::string, std::pair<std::string const, google::protobuf::compiler::CommandLineInterface::GeneratorContextImpl*>, std::allocator<std::pair<std::string const, google::protobuf::compiler::CommandLineInterface::GeneratorContextImpl*> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_rehash(unsigned long, unsigned long const&): error: undefined reference to '__umoddi3'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/command_line_interface.o:command_line_interface.cc:function std::_Hashtable<std::string, std::pair<std::string const, google::protobuf::compiler::CommandLineInterface::GeneratorContextImpl*>, std::allocator<std::pair<std::string const, google::protobuf::compiler::CommandLineInterface::GeneratorContextImpl*> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_rehash(unsigned long, unsigned long const&): error: undefined reference to '__umoddi3'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/command_line_interface.o:command_line_interface.cc:function std::__detail::_Map_base<std::string, std::pair<std::string const, google::protobuf::compiler::CommandLineInterface::GeneratorContextImpl*>, std::allocator<std::pair<std::string const, google::protobuf::compiler::CommandLineInterface::GeneratorContextImpl*> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>, true>::operator[](std::string const&): error: undefined reference to '__umoddi3'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/command_line_interface.o:command_line_interface.cc:function std::__detail::_Map_base<std::string, std::pair<std::string const, google::protobuf::compiler::CommandLineInterface::GeneratorContextImpl*>, std::allocator<std::pair<std::string const, google::protobuf::compiler::CommandLineInterface::GeneratorContextImpl*> >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>, true>::operator[](std::string const&): error: undefined reference to '__umoddi3'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/cpp_padding_optimizer.o:cpp_padding_optimizer.cc:function __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > > std::_V2::__rotate<__gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > > >(__gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, std::random_access_iterator_tag) [clone .isra.94]: error: undefined reference to '__moddi3'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/cpp_padding_optimizer.o:cpp_padding_optimizer.cc:function __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > > std::_V2::__rotate<__gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > > >(__gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, std::random_access_iterator_tag) [clone .isra.94]: error: undefined reference to '__moddi3'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/cpp_padding_optimizer.o:cpp_padding_optimizer.cc:function __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > > std::_V2::__rotate<__gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > > >(__gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, std::random_access_iterator_tag) [clone .isra.94]: error: undefined reference to '__moddi3'
bazel-out/host/bin/external/com_google_protobuf/_objs/protoc_lib/cpp_padding_optimizer.o:cpp_padding_optimizer.cc:function __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > > std::_V2::__rotate<__gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > > >(__gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, __gnu_cxx::__normal_iterator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup*, std::vector<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup, std::allocator<google::protobuf::compiler::cpp::(anonymous namespace)::FieldGroup> > >, std::random_access_iterator_tag) [clone .isra.94]: error: undefined reference to '__moddi3'
bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/tokenizer.o:tokenizer.cc:function google::protobuf::io::Tokenizer::ParseInteger(std::string const&, unsigned long, unsigned long*): error: undefined reference to '__udivdi3'
bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/tokenizer.o:tokenizer.cc:function google::protobuf::io::Tokenizer::ParseInteger(std::string const&, unsigned long, unsigned long*): error: undefined reference to '__udivdi3'
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 401.100s, Critical Path: 43.80s
INFO: 242 processes: 242 local.
FAILED: Build did NOT complete successfully


Please give me some suggestion, thanks a lot！

**Comment by zhangqiang-hf** [comment]
Dear Sir，
from the website "https://www.tensorflow.org/install/source", it tells "您可以从源代码构建 TensorFlow pip 软件包并将其安装在 Ubuntu Linux 和 macOS 上。尽管这些说明可能适用于其他系统，但仅针对 Ubuntu 和 macOS 进行了测试并在这两种平台上受支持。"
 
it means the tensorflow only can be build on Ubuntu or macOS? our OS is loongnix OS,it is based on Fedora OS

**Comment by gunan** [comment]
looks like a protobuf issue? @jvishnuvardhan do we have a contact in protobuf team to look into this?

**Comment by gunan** [comment]
Actually, this looks like it is being built on mips64el architecture. We do not have support for this system yet, and have no experience. We welcome any patches, but I am afraid I do not have experience with this architecture. I will mark this as "community support" You may want to reach out to build@tensorflow.org

**Comment by zhangqiang-hf** [comment]
Dear Sirs，
  Please help me to resolve this build fail issue, it cost us a few days...
The build failed logs  is as above!

**Comment by bhack** [comment]
I think that you need to link `-lgcc` in the receipts.

**Comment by sanatmpa1** [comment]
@zhangqiang-hf,

Can you take a look at this above [comment](https://github.com/tensorflow/tensorflow/issues/42700#issuecomment-685935063) and let us know if it helps? Thanks!
