### ISSUE TITLE
Memory leak when using tensorflow c++ api

### ISSUE THREAD

**Issue by tz301** [tensorflow/tensorflow#42706]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.15.0
- Python version:
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): 5.5.0/c++11
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Our project using bazel and tensorflow c++ api for inference. 

In our workspace, we using "https://github.com/tensorflow/tensorflow/archive/v1.15.0.tar.gz".

When inference on features repeatedly, memory keeps rising.

Our model is an old style pb file, not saved model. It is generated from onnx to tensorflow project.  Our graph has two inputs and one output. Here is some key code.

```
class TfModel {
 public:
  /**
   * @brief Construct.
   */
  TfModel() : pb_path_(xxx), input_names_{"input1:0", "input2:0"}, output_names_{"output:0"}) {
    sess_options_.config.set_use_per_session_threads(true);
    sess_options_.config.set_intra_op_parallelism_threads(0);
    sess_options_.config.set_inter_op_parallelism_threads(0);

    sess_.reset(tensorflow::NewSession(sess_options_));
    tensorflow::GraphDef graph_def;
    auto default_env = tensorflow::Env::Default();
    auto status = tensorflow::ReadBinaryProto(default_env, pb_path, &graph_def);
    if (!status.ok()) {
      throw std::invalid_argument("Error!");
    }
    sess_->Create(graph_def);
  }

  /**
   * @brief Compute.
   */
  void Compute(const tensorflow::Tensor &tensor1,
               const tensorflow::Tensor &tensor2) const {
    std::vector<std::pair<std::string, tensorflow::Tensor>> tf_input;
    tf_input.emplace_back(input_names_[0], tensor1);
    tf_input.emplace_back(input_names_[1], tensor2);
    std::vector<tensorflow::Tensor> output;
    auto status = sess_->Run(tf_input, output_names_, {}, &output);
  }

 private:
  const std::string pb_path_;
  const std::vector<std::string> input_names_;
  const std::vector<std::string> output_names_;
  std::unique_ptr<tensorflow::Session> sess_;
  tensorflow::SessionOptions sess_options_;
};

int main() {
  model = TfModel();
  while (true) {
    model.Compute(tensor1, tensor2);
    PrintRssMemory();
  }
}
```

I have searched some solutions and try tcmalloc. The memory leak seems negligible, but is ~25% slower than before, which is not acceptable.

The memory leak problem seems very severe if I set inter_thead and intra_thead to 0. If set to 1, the problem seems disappear. But we must use larger inter_thead and intra_thead for multi-thead.

I don't attach model since it's a little large. Hope anyone can help, Thanks.

**Describe the expected behavior**

No memory leak.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by GaussRieman** [comment]
I'm being troubled by the same problem, and the memory still keeps growing even when I set the intra and inter multi thread num to 1. After trying lots of solutions supplied by others, nothing gets better.
Any useful suggestion will be appreciated.
THX!

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
