### ISSUE TITLE
fatal error: tensorflow/core/protobuf/error_codes.pb.h: No such file or directory

### ISSUE THREAD

**Issue by AngeloMascaro** [tensorflow/tensorflow#42721]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Linux Drax 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- TensorFlow source: v2.3.0
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

compile any program that includes tensorflow/core/public/session.h

gcc -I/home/amascaro/Programming/src/tensorflow -I/home/amascaro/.local/lib/python3.6/site-packages/tensorflow_core/include/ loader.cc 
In file included from /home/amascaro/Programming/src/tensorflow/tensorflow/core/platform/errors.h:22:0,
                 from /home/amascaro/Programming/src/tensorflow/tensorflow/core/lib/core/errors.h:19,
                 from /home/amascaro/Programming/src/tensorflow/tensorflow/core/framework/tensor_shape.h:23,
                 from /home/amascaro/Programming/src/tensorflow/tensorflow/core/framework/tensor.h:24,
                 from /home/amascaro/Programming/src/tensorflow/tensorflow/core/public/session.h:24,
                 from loader.cc:1:
/home/amascaro/Programming/src/tensorflow/tensorflow/core/platform/status.h:28:10: fatal error: tensorflow/core/protobuf/error_codes.pb.h: No such file or directory
 #include "tensorflow/core/protobuf/error_codes.pb.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

The missing file is under another path: /home/amascaro/.local/lib/python3.6/site-packages/tensorflow_core/include/tensorflow/core/lib/core/error_codes.pb.h

**Comment by amahendrakar** [comment]
@AngeloMascaro,
Could you please provide the complete code or the commands you have executed before running into this issue. 

Also, take a look at [this comment](https://github.com/FloopCZ/tensorflow_cc/issues/16#issuecomment-325797963) from a similar issue and let us know if it helps. Thanks!

**Comment by fisakhan** [comment]
I experience a similar problem. While running the following command on Ubuntu 18.04 after compiling TensorFlow 2.3 C++ API (using Bazel). g++ -std=c++11 -I/usr/local/include/tf -I/usr/local/include/tf/third_party/eigen3 -L/usr/local/lib hello.cc -o hello
I searched for the file "error_codes.pb.h" on my computer but its not there. Although, I have installed protoc 3.5.
 ```
#include "tensorflow/cc/client/client_session.h"
#include "tensorflow/cc/ops/standard_ops.h"
#include "tensorflow/core/framework/tensor.h"

int main() {
  using namespace tensorflow;
  using namespace tensorflow::ops;
  Scope root = Scope::NewRootScope();
  // Matrix A = [3 2; -1 0]
  auto A = Const(root, { {3.f, 2.f}, {-1.f, 0.f} });
  // Vector b = [3 5]
  auto b = Const(root, { {3.f, 5.f} });
  // v = Ab^T
  auto v = MatMul(root.WithOpName("v"), A, b, MatMul::TransposeB(true));
  std::vector<Tensor> outputs;
  ClientSession session(root);
  // Run and fetch v
  TF_CHECK_OK(session.Run({v}, &outputs));
  // Expect outputs[0] == [19; -3]
  LOG(INFO) << outputs[0].matrix<float>();
  return 0;
}
```

**Comment by amahendrakar** [comment]
> Also, take a look at [this comment](https://github.com/FloopCZ/tensorflow_cc/issues/16#issuecomment-325797963) from a similar issue and let us know if it helps. Thanks!

@AngeloMascaro,
Is this still an issue? Please feel free to close the issue if resolved. Thanks!

**Comment by amahendrakar** [comment]
> I experience a similar problem. 

@fisakhan,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by AngeloMascaro** [comment]
I check it today afternoon or tomorrow morning and I let you know. I suppose yes: it happens with any code that includes that header file. Even an empty main 

Inviato da iPhone

**Comment by amahendrakar** [comment]
> I check it today afternoon or tomorrow morning and I let you know.

@AngeloMascaro,
Any updates regarding this issue? Did you get a chance to look into this? Thanks!

**Comment by danielkaifeng** [comment]
in some tensorflow version, the related xxxx.pb.h should change to  .proto
just make change in your `#include `
