### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by TheNightBaron** [tensorflow/tensorflow#42725]
I'm relatively new to programming so please forgive me if some details mentioned before are not detailed enough. 
I downloaded tensorflow today and after looking at the documentation, downloaded/updated CUDA and cuDNN as well. But I'm getting this error:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-d6579f534729> in <module>()
----> 1 import tensorflow

~\AppData\Roaming\Python\Python35\site-packages\tensorflow\__init__.py in <module>()
     39 import sys as _sys
     40 
---> 41 from tensorflow.python.tools import module_util as _module_util
     42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
     43 

~\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\__init__.py in <module>()
     38 # pylint: disable=wildcard-import,g-bad-import-order,g-import-not-at-top
     39 
---> 40 from tensorflow.python.eager import context
     41 
     42 # pylint: enable=wildcard-import

~\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\eager\context.py in <module>()
     33 from tensorflow.core.protobuf import config_pb2
     34 from tensorflow.core.protobuf import rewriter_config_pb2
---> 35 from tensorflow.python import pywrap_tfe
     36 from tensorflow.python import tf2
     37 from tensorflow.python.client import pywrap_tf_session

~\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\pywrap_tfe.py in <module>()
     27 # pylint: disable=invalid-import-order,g-bad-import-order, wildcard-import, unused-import
     28 from tensorflow.python import pywrap_tensorflow
---> 29 from tensorflow.python._pywrap_tfe import *

ImportError: DLL load failed: The specified module could not be found.

I tried the solutions mentioned in older posts having the same error, but none worked.
I'm using:
Windows 10 64-bit
Mobile Device: N/A
TensorFlow downloaded through Anaconda prompt -pip install tensorflow
Version: 2.3.0
Python version 3.5.5
Bazel version (if compiling from source) - N/A
GCC/Compiler version (if compiling from source) - N/A
CUDA/cuDNN version - 10.2
GPU model and memory - NVIDIA GeForce 940MX; 4GB dedicated memory
Exact command to reproduce - import tensorflow
Tensorflow version - 2.3.0

**Comment by ravikyram** [comment]
@TheNightBaron 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.Please, refer similar issues #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
Thanks!

**Comment by TheNightBaron** [comment]
AVX is supported in intel i series of CPUs. Mine is Intel i7 7th Generation CPU. 
Python is 64 bit.
I just updated visual C++ version in my laptop and it worked! Thanks a lot!
