### ISSUE TITLE
Android - Drawback of Fixing Error (Regular TensorFlow ops) is increasing the app size to 195MB! 

### ISSUE THREAD

**Issue by hahmad2008** [tensorflow/tensorflow#42735]
### Object detection Android TF LITE EXAMPLE
I am running the example of [object detection Android version](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android), which need about 14MB storage on the physical phone.

### My trained Object detection Android TF LITE
However, when I used my object detection trained model, (which is [converted to TF LITE using this link](https://github.com/tensorflow/tensorflow/issues/42114#issuecomment-671593386)), I got the following exception when the app started: 

```
org.tensorflow.lite.examples.detection E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.lite.examples.detection, PID: 5086
    java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
    Node number 223 (FlexSize) failed to prepare.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:158)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:347)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:196)
        at org.tensorflow.lite.examples.detection.DetectorActivity$2.run(DetectorActivity.java:181)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

* My tf-Lite model size: 5MB
* The app size on the mobile is about 15 MB

### To Solve This Error:
- I include the following dependency on the **build.gradle (Modle app)**:

```
    // This dependency adds the necessary TF op support.
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly'
```

<img width="1019" alt="Screen Shot 2020-08-28 at 3 23 41 PM" src="https://user-images.githubusercontent.com/68266028/91560386-764b9680-e942-11ea-827e-28e2680d866c.png">

That solves the problem and my object detection app is working very well. 

### However, The app is now 195MB size (storage) on the physical mobile! Does this (-tf-ops) dependency has this large size! If so how can I fix the previous exception without including this dependency in the android app?

<img width="305" alt="Screen Shot 2020-08-28 at 3 21 26 PM" src="https://user-images.githubusercontent.com/68266028/91560234-266ccf80-e942-11ea-8b08-9ecb6aa2bb5d.png">

**Comment by srjoglekar246** [comment]
Which model are you using from the TF2 detection zoo? I am working on a script to convert SSD models to a more TFLite-friendly format, which should make the usage of TF-Select ops unnecessary.

**Comment by hahmad2008** [comment]
@srjoglekar246 
I follow [this tutorial ](https://github.com/abdelrahman-gaber/tf2-object-detection-api-tutorial)to train object detection on a custom dataset. 

* In the tutorial, the following model is used as a backbone model.

`wget http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_320x320_coco17_tpu-8.tar.gz`

* Then convert it to TF LITE using [this script](https://github.com/tensorflow/tensorflow/issues/42114#issuecomment-671593386)

**Comment by hahmad2008** [comment]
@srjoglekar246 
This is TF-Select ops converting [script](https://github.com/tensorflow/tensorflow/issues/42114#issuecomment-671593386) I used to convert the model to the lite.

**Comment by abattery** [comment]
How about using the selective build? https://www.tensorflow.org/lite/guide/reduce_binary_size

**Comment by srjoglekar246** [comment]
@hahmad2008 That unfortunately isn't the best way to convert SSD models to TFLite, since it includes parts of the graph not intended for on-device inference. I have an upcoming script to do this for TF2 models, please refer to this: https://github.com/tensorflow/models/issues/9033

**Comment by hahmad2008** [comment]
Thanks @srjoglekar246 
But where can I see that script?

**Comment by srjoglekar246** [comment]
In internal review, hopefully will land soon :-)

**Comment by hahmad2008** [comment]
Then, I have to follow the thread.

**Comment by hahmad2008** [comment]
@srjoglekar246 I used the same [script](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md). 

```
# From the tensorflow/models/research/ directory
python object_detection/export_tflite_graph_tf2.py \
    --pipeline_config_path path/to/ssd_model/pipeline.config \
    --trained_checkpoint_dir path/to/ssd_model/checkpoint \
    --output_directory path/to/exported_model_directory
```

I got a _544 byte_ lite model, but when I tried to test the lite model, I got the error:

```
interpreter = tf.lite.Interpreter(model_content=tflite_quant_model)
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test the model on random input data.
input_shape = input_details[0]['shape']
print(input_shape)
```

- Error for this line `interpreter = tf.lite.Interpreter(model_content=tflite_quant_model)`

```
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter.py in __init__(self, model_path, model_content, experimental_delegates, num_threads)
    206               custom_op_registerers_by_func))
    207       if not self._interpreter:
--> 208         raise ValueError('Failed to open {}'.format(model_path))
    209     elif model_content and not model_path:
    210       custom_op_registerers_by_name = [

ValueError: Did not get operators, tensors, or buffers in subgraph 0.
```

Any idea? how to solve this?

**Comment by hahmad2008** [comment]
@srjoglekar246 

I have successfully converted the tf model, but now the output detection was 100 now is only 10! the performance is so bad now! I had converted the model previously using supported_ops and the performance was really good but now is very bad :(

**Comment by srjoglekar246** [comment]
@hahmad2008 Please use the latest nightly for tflite_convert. Otherwise you won't get the latest convertor changes. Looks like you got it converting now, how big is the model?

`export_tflite_graph_tf2.py` has some parameters that you can use to fine-tune how many results it provides, and the accuracy.

See `ssd_use_regular_nms` & `ssd_max_detections` [here](https://github.com/tensorflow/models/blob/master/research/object_detection/export_tflite_graph_tf2.py#L98). provide a higher value to ssd>max_detections and/or set ssd_use_regular_nms to True.

*But* note that these changes will increase latency.

**Comment by hahmad2008** [comment]
@srjoglekar246 Thank you so much. it works now. the app is now 15 MB size 👍

**Comment by hahmad2008** [comment]
@srjoglekar246 but why the performance of the model is not natural, I mean the percentage of scores + when there is no object is trained on is visible it then detect the view as on of the trained objects with a high score :( -_-

**Comment by srjoglekar246** [comment]
Did you try [these params](https://github.com/tensorflow/models/blob/master/research/object_detection/export_tflite_graph_tf2.py#L98)? `--ssd_use_regular_nms=true` while exporting will make your model more accurate, so will increasing `ssd_max_detections`.
