### ISSUE TITLE
Crashing when parsing names with special character [] in saver.restore(): bug or expected behavior ?

### ISSUE THREAD

**Issue by jeandut** [tensorflow/tensorflow#4273]
Disclaimer: I have tensorflow 0.7.0 (a bit outdated I suppose). I have not tested it on more recent versions.
When I try:
```python
import tensorflow as tf
x=tf.placeholder(tf.float32,[])
w=tf.Variable(2.)
y=tf.mul(x,w)
saver=tf.train.Saver()
init=tf.initialize_all_variables()
sess1=tf.Session()
sess1.run(init)
name_model="./"+"model"
saver.save(sess,name_model)
sess1.close()
sess2=tf.Session()
path_meta=name_model+".meta"
path_model=name_model
new_saver=tf.train.import_meta_graph(path_meta)
new_saver.restore(sess2,path_model)
print sess2.run(y, feed_dict={x: 1.})==2
```
It runs perfectly fine but if I change name_model to "./model[1]" for example it crashes with message: `Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./model[1].`
I was wondering if this is expected or if it is a bug. If this is buggy what would be aworkaround ?

**Comment by tatatodd** [comment]
@jeandut each filesystem has differing behavior wrt special characters.  I'd recommend the best thing is to avoid special characters in your filenames.  Hope this helps!  If you have any other follow-up questions, just add them here.

**Comment by jeandut** [comment]
Ok I had no idea ! Thanks !
