### ISSUE TITLE
TPU - Probable memory leak in TF 2.3 on data augmentation using tf.keras.layers.experimental.preprocessing.*

### ISSUE THREAD

**Issue by bduclaux** [tensorflow/tensorflow#42737]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Debian Buster
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Install from pip
- TensorFlow version (use command below): 2.3.0
- Python version: 3.8.0
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: Cloud TPU v2-8

**Describe the current behavior**

The recent Random augmentations added in TF 2.3.0 generate a memory leak on TPU leading to a crash and GRPC Socket 14 error message.
TPU memory usage grows up to 315GB, then a crash occurs.
The problem does not appear when augmentations in the code below are disabled, or tf.image augmentations are applied.

**Standalone code to reproduce the issue**

Create a standard data loading pipeline, and insert a map call to a Sequential model containing tf.keras.layers.experimental.preprocessing transformations.

```
augmentations = tf.keras.Sequential([
    tf.keras.layers.experimental.preprocessing.RandomFlip(mode='horizontal',dtype=tf.float32),
    tf.keras.layers.experimental.preprocessing.RandomContrast(0.1,dtype=tf.float32),
    tf.keras.layers.experimental.preprocessing.RandomRotation(0.25/4,dtype=tf.float32), #0.25=pi/2
    tf.keras.layers.experimental.preprocessing.RandomTranslation(width_factor=0.1,height_factor=0.1,dtype=tf.float32),
    tf.keras.layers.experimental.preprocessing.RandomZoom(0.1,dtype=tf.float32)
])

def data_augment(image, label):
      image = augmentations(image, training=True)
    return image, label   

def get_training_dataset():
    dataset = load_dataset(TRAINING_FILENAMES)
    dataset = dataset.shuffle(8192)
    dataset = dataset.repeat()
    dataset = dataset.batch(BATCH_SIZE)
    dataset = dataset.map(data_augment, num_parallel_calls=AUTO) # Memory Leak here
    dataset = dataset.prefetch(AUTO)
    return dataset

```
The addition of dtype=tf.float32 in the augmentation code does not change anything.
The use of a single augmentation (instead of 5 in the example above) does not change the problem.

Also, if I replace the use of the augmentation layer by a simple lambda function such as the following, the problem disappears:

```
def data_augment_ok(image, label):
    max_angle = 30*math.pi/180
    rotation = tf.random.uniform(shape=[], minval=-max_angle, maxval=max_angle, dtype=tf.float32)
    image = tf.image.random_flip_left_right(image)
    image = tf.image.random_contrast(image, 0.7, 1)
    image = tfa.image.rotate(image,rotation)
    return image, label   

def get_training_dataset():
    dataset = load_dataset(TRAINING_FILENAMES)
    dataset = dataset.map(data_augment_ok, num_parallel_calls=AUTO) # Notice the call earlier in the pipeline
  
    dataset = dataset.shuffle(8192)
    dataset = dataset.repeat()
    dataset = dataset.batch(BATCH_SIZE)
    dataset = dataset.prefetch(AUTO) # prefetch next batch while training (autotune prefetch buffer size)
    return dataset
```

Thanks!

**Comment by Saduf2019** [comment]
@bduclaux 
Please provide with complete indented stand alone code to replicate the issue faced or if possible share a colab gist with the error reported.
