### ISSUE TITLE
Problem with creating a tf.data.Dataset iterator from numpy array

### ISSUE THREAD

**Issue by BoyuanJackChen** [tensorflow/tensorflow#42733]
I am trying to create a tensorflow data iterator from a numpy array, placed on a certain device. I expected it to be of type tf.data.Dataset..., but what I got were something else. I wonder how to create an iterator based on this target_data. Or is there a better way to convert numpy to tf.data? 
```
target_data = tf.data.Dataset.from_tensor_slices(target_batched)
# <class 'tensorflow.python.data.ops.dataset_ops.TensorSliceDataset'>
target_data= target_data.apply(tf.data.experimental.prefetch_to_device("/cpu:0", 12))
# <class 'tensorflow.python.data.ops.dataset_ops.PrefetchDataset'>
```
(here, target_data.make_initializable_iterator() doesn't work)

**Comment by nikitamaia** [comment]
Hi @BoyuanJackChen your `target_data` is a `tf.data.Dataset`. If you look [here in the source code](https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/python/data/ops/dataset_ops.py#L4286) at the `PrefetchDataset` class, and then look up the inheritance hierarchy, the root is class `DatasetV2` which has the tf export symbol `@tf_export("data.Dataset", v1=[])`

As for `make_initializable_iterator()` this method is no longer available in TF2. You import it from the compat module, but I don't this it will work with eager execution. If you want to iterate over your data, you can do that easily with your `tf.data.Dataset`. The examples [here in the docs](https://www.tensorflow.org/api_docs/python/tf/data/Iterator) on how to iterate over your dataset might be of use. Happy to provide more help if needed, if you share the version of TF you are using as well as the specific error you saw when calling `make_initializable_iterator()`
