### ISSUE TITLE
ModelCheckpoint behavior doesn't change when changing save_weights_only from True to False for custom tf.keras.Model

### ISSUE THREAD

**Issue by marwan116** [tensorflow/tensorflow#42741]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- Python version: 3.6.9
- Tensorflow version: 2.3.0 ('v2.3.0-0-gb36436b087')

**Describe the current behavior**
I am migrating from TF1 to TF2 and I am trying to understand best practices when it comes to model saving/checkpointing during training.

I would like to checkpoint the model training so as to be able to resume training later.

Quoting from the documentation (https://www.tensorflow.org/guide/keras/save_and_serialize#saving_loading_only_the_models_weights_values)
```
You can choose to only save & load a model's weights. This can be useful if:
* You only need the model for inference: in this case you won't need to restart training, so you don't need the compilation information or optimizer state.
* You are doing transfer learning: in this case you will be training a new model reusing the state of a prior model, so you don't need the compilation information of the prior model.
```

So it seems to me given my use-case of resuming training that I would want to checkpoint the full model and not just the weights correct ? More specifically I would like the following to be saved at each epoch.

```
* The model's architecture/config
* The model's weight values (which were learned during training)
* The model's compilation information (if compile()) was called
* The optimizer and its state, if any (this enables you to restart training where you left)
```

The following code snippet shown in the documentation (https://www.tensorflow.org/tutorials/keras/save_and_load#checkpoint_callback_usage) only saves the weights:
```
checkpoint_path = "training_1/cp.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_path)

# Create a callback that saves the model's weights
cp_callback = tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path,
                                                 save_weights_only=True,
                                                 verbose=1)

# Train the model with the new callback
model.fit(train_images, 
          train_labels,  
          epochs=10,
          validation_data=(test_images,test_labels),
          callbacks=[cp_callback])  # Pass callback to training
```

So I made a single change to the above code changing `save_weights_only` from False to True
```
checkpoint_path = "training_1/cp.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_path)

# Create a callback that saves the model's weights
cp_callback = tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path,
                                                 save_weights_only=False,   # <- this is the change I made 
                                                 verbose=1)

# Train the model with the new callback
model.fit(train_images, 
          train_labels,  
          epochs=10,
          validation_data=(test_images,test_labels),
          callbacks=[cp_callback])  # Pass callback to training
```
and now I see a cp.ckpt file instead of the `.data` and `.index` file - all good so far.

However the example in the documentation is using a `tf.keras.Sequential` model - and I would like to subclass `tf.keras.Model` instead. So I replicate the example's model using a very simple tf.keras.Model

```
class SimpleModel(tf.keras.Model):
  def __init__(self, **kwargs):
    super().__init__(**kwargs)
    self.layer_1 = keras.layers.Dense(512, activation='relu', input_shape=(784,))
    self.layer_2 = keras.layers.Dropout(0.2)
    self.layer_3 = keras.layers.Dense(10)
  
  def call(self, inputs):
    x = self.layer_1(inputs)
    x = self.layer_2(x)
    return self.layer_3(x)
```
and now I no longer see cp.ckpt files being created by the callback but I see `.data` and `.index` files (indicating just the weights are being saved)

It would be great if someone can explain how to go about checkpointing the full model in a SavedModel (.tf) format for the purpose of resuming training specifically for models implemented by subclassing tf.keras.Model.

**Comment by marwan116** [comment]
After some digging into the code it seems - the `set_model` call in `ModelCheckpoint` reverts back the `save_weights_only` to True 

```
  def set_model(self, model):
    self.model = model
    # Use name matching rather than `isinstance` to avoid circular dependencies.
    if (not self.save_weights_only and
        not model._is_graph_network and  # pylint: disable=protected-access
        model.__class__.__name__ != 'Sequential'):
      self.save_weights_only = True
```
given `self._is_graph_network` is False - is there a reason for this behavior ? I see two other issues that seem to be duplicates (https://github.com/tensorflow/tensorflow/issues/39679  and https://github.com/tensorflow/tensorflow/issues/37620)

**Comment by marwan116** [comment]
Just to test things out - I created my own checkpointing callback - which just removes this behavior from `set_model` 

```
class CustomCheckpoint(tf.keras.callbacks.ModelCheckpoint):
    def set_model(self, model):
        self.model = model
```
and now the `save_weights_only` doesnt get overriden.

I still dont understand why `save_weights_only` has to be False when `model. _is_graph_network` is False, given that clearly if `model.is_graph_network` is False, this doesnt mean a model cant call model.save ...

**Comment by marwan116** [comment]
here is the commit that created this piece https://github.com/tensorflow/tensorflow/commit/ec5e355a1df575b85f9d0114e0522b64e1b9c6ff by @fchollet 

reading the commit message - it seems the intended behavior was to make the checkpointer default `save_weights_only` to False when using a subclassed model but not to override `save_weights_only`.

**Comment by Saduf2019** [comment]
@marwan116 
The code is not complete for us to replicate the issue, can you please share a colab gist with the issue reported, have you tried on tf-nightly if you are facing the issue.

**Comment by marwan116** [comment]
@Saduf2019  - please find the colab gist
https://colab.research.google.com/gist/marwan116/ab3ac395d0dfe111eb0ec0853bb8e3f8/untitled1.ipynb

**Comment by bhack** [comment]
@marwan116 In theory that `if` it is request only for the `h5` `model.save` format.
Check https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/saving/save.py#L118-L132

**Comment by bhack** [comment]
But also in the `SaveModel` format it is still not totally safe to recover the training: https://github.com/tensorflow/tensorflow/pull/42846

**Comment by marwan116** [comment]
@bhack  - sorry to respond back late - sure if you are saying this check should apply when using an h5 format, that's understandable - but currently the if statement used in `set_model` doesn't take the saving format into account. It seems to me the fix here is to add an `if (save_format == 'h5')` check to the statement to prevent it from reverting`self.save_weights_only` to True - as for the save format is `SavedModel` throwing the warning about slot variables as you mention in https://github.com/tensorflow/tensorflow/pull/42749 when loaded should suffice in my opinion

**Comment by chengjianhong** [comment]
@marwan116 Have you solved the problem yet? I also use 'save_best_only=True' to save the model, but when I use 'tf.keras.models.load_model' to load the model file, It happens the error: "ValueError: No model found in config file."

**Comment by marwan116** [comment]
@chengjianhong  - my current workaround is to implement my own ModelCheckpoint - that overrides `set_model`  ... 

```
class CustomCheckpoint(tf.keras.callbacks.ModelCheckpoint):
    def set_model(self, model):
        self.model = model
```

**Comment by Jordy-VL** [comment]
Wow, such an easy fix! Thanks @marwan116

**Comment by jvishnuvardhan** [comment]
@marwan116 Looks like this was resolved in recent `tf-nightly`. I couldn't reproduce the issue. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/52ab320e11923cc3badd101cb6ead32b/untitled1.ipynb).

Please verify once and close the issue if this was resolved for you. Thanks!
