### ISSUE TITLE
AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TENSOR_LIKE_TYPES'

### ISSUE THREAD

**Issue by ClearLens** [tensorflow/tensorflow#42740]
I installed the latest version of keras and tensorflow on anaconda.
The problem looks like the same as the following and it is still awaiting a response
https://github.com/tensorflow/tensorflow/issues/38589

```

from keras.datasets import mnist
from keras.utils import np_utils
from keras.models import Sequential, Model
from keras.layers import Input, Dense, Dropout, Activation, Flatten
from keras.layers.advanced_activations import LeakyReLU
from keras.optimizers import Adam, RMSprop
import numpy as np
import matplotlib.pyplot as plt
import random
from tqdm import notebook

# Dataset of 60,000 28x28 grayscale images of the 10 digits, along with a test set of 10,000 images.
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

# Preprocessing

X_train = X_train.reshape(60000, 784)
X_test = X_test.reshape(10000, 784)
X_train = X_train.astype('float32')/255
X_test = X_test.astype('float32')/255


# Set the dimensions of the noise
z_dim = 100

# Optimizer
adam = Adam(lr=0.0002, beta_1=0.5)

g = Sequential()
g.add(Dense(256, input_dim=z_dim, activation=LeakyReLU(alpha=0.2)))
g.add(Dense(512, activation=LeakyReLU(alpha=0.2)))
g.add(Dense(1024, activation=LeakyReLU(alpha=0.2)))
g.add(Dense(784, activation='sigmoid'))  # Values between 0 and 1
g.compile(loss='binary_crossentropy', optimizer=adam, metrics=['accuracy'])

d = Sequential()
d.add(Dense(1024, input_dim=784, activation=LeakyReLU(alpha=0.2)))
d.add(Dropout(0.3))
d.add(Dense(512, activation=LeakyReLU(alpha=0.2)))
d.add(Dropout(0.3))
d.add(Dense(256, activation=LeakyReLU(alpha=0.2)))
d.add(Dropout(0.3))
d.add(Dense(1, activation='sigmoid'))  # Values between 0 and 1
d.compile(loss='binary_crossentropy', optimizer=adam, metrics=['accuracy'])

d.trainable = False
inputs = Input(shape=(z_dim, ))
hidden = g(inputs)
output = d(hidden)
gan = Model(inputs, output)
gan.compile(loss='binary_crossentropy', optimizer=adam, metrics=['accuracy'])

```

AttributeError                            Traceback (most recent call last)
<ipython-input-4-fc09a4f0e640> in <module>
      3 
      4 g = Sequential()
----> 5 g.add(Dense(256, input_dim=z_dim, activation=LeakyReLU(alpha=0.2)))
      6 g.add(Dense(512, activation=LeakyReLU(alpha=0.2)))
      7 g.add(Dense(1024, activation=LeakyReLU(alpha=0.2)))

~\anaconda3\envs\tf\lib\site-packages\keras\engine\sequential.py in add(self, layer)
    164                     # and create the node connecting the current layer
    165                     # to the input layer we just created.
--> 166                     layer(x)
    167                     set_inputs = True
    168             else:

~\anaconda3\envs\tf\lib\site-packages\keras\backend\tensorflow_backend.py in symbolic_fn_wrapper(*args, **kwargs)
     73         if _SYMBOLIC_SCOPE.value:
     74             with get_graph().as_default():
---> 75                 return func(*args, **kwargs)
     76         else:
     77             return func(*args, **kwargs)

~\anaconda3\envs\tf\lib\site-packages\keras\engine\base_layer.py in __call__(self, inputs, **kwargs)
    444                 # Raise exceptions in case the input is not compatible
    445                 # with the input_spec specified in the layer constructor.
--> 446                 self.assert_input_compatibility(inputs)
    447 
    448                 # Collect input shapes to build layer.

~\anaconda3\envs\tf\lib\site-packages\keras\engine\base_layer.py in assert_input_compatibility(self, inputs)
    308         for x in inputs:
    309             try:
--> 310                 K.is_keras_tensor(x)
    311             except ValueError:
    312                 raise ValueError('Layer ' + self.name + ' was called with '

~\anaconda3\envs\tf\lib\site-packages\keras\backend\tensorflow_backend.py in is_keras_tensor(x)
    693     ```
    694     """
--> 695     if not is_tensor(x):
    696         raise ValueError('Unexpectedly found an instance of type `' +
    697                          str(type(x)) + '`. '

~\anaconda3\envs\tf\lib\site-packages\keras\backend\tensorflow_backend.py in is_tensor(x)
    701 
    702 def is_tensor(x):
--> 703     return isinstance(x, tf_ops._TENSOR_LIKE_TYPES) or tf_ops.is_dense_tensor_like(x)
    704 
    705 

AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TENSOR_LIKE_TYPES'

**Comment by ravikyram** [comment]
@ClearLens 

There seems to be some weird compatibility issues between keras and tensorflow.keras. So please try with tensorflow.keras instead.

```
from tensorflow.keras.datasets import mnist
from tensorflow.python.keras.utils import np_utils
from tensorflow.keras import Sequential
from tensorflow.keras import model
from tensorflow.keras.layers import Input, Dense, Dropout, Activation, Flatten
from tensorflow.keras.optimizers import Adam, RMSprop
```
Thanks!

**Comment by SalihACan** [comment]
I got same error. After I tried with tensorflow it worked.
Tensorflow version : '2.3.1' 
Tensorflow.keras version : '2.4.0'
Thanks.

**Comment by alexandrerays** [comment]
> @ClearLens
> 
> There seems to be some weird compatibility issues between keras and tensorflow.keras. So please try with tensorflow.keras instead.Also, please let us know Tensorflow version you are using?
> 
> ```
> from tensorflow.keras.datasets import mnist
> from tensorflow.python.keras.utils import np_utils
> from tensorflow.keras import Sequential
> from tensorflow.keras import model
> from tensorflow.keras.layers import Input, Dense, Dropout, Activation, Flatten
> from tensorflow.keras.optimizers import Adam, RMSprop
> ```
> 
> Thanks!

Replace 'keras' by 'tensorflow.keras' worked for me today.

**Comment by soumyasoumya** [comment]
it is giving following error 
tensorflow.python.keras.engine.base_layer_v1
