### ISSUE TITLE
Unable to find the tf.raw_ops.mfcc python code in tensorflow

### ISSUE THREAD

**Issue by marjanemd** [tensorflow/tensorflow#42755]
Hello,

I would like to see the procedure of calculating the mfcc and filterbank values in tensorflow package using tf.raw_ops.mfcc, but I could not find it.
The closest code that I found was:
https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/python/ops/signal/mfcc_ops.py 

Is there anywhere I can find the exact  tf.raw_ops.mfcc function code?

**Comment by marjanemd** [comment]
I haven't received any answer yet! Is there amy Github repo for tf.raw_ops package?

**Comment by rmothukuru** [comment]
@marjanemd,
Sorry for the delayed response. [This is the path of the source code for tf.raw_ops.Mfcc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/api_def/base_api/api_def_Mfcc.pbtxt). Hope this helps. Thanks!
