### ISSUE TITLE
libtensorflowlite XNNPACK support beyond f32

### ISSUE THREAD

**Issue by honglh** [tensorflow/tensorflow#42759]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information** march=armhf mfpu=neon
- TensorFlow version (you are using): v2.3.0
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**
In both `master` and `v2.3.0` where xnnpack config is available, it seems that only f32 ops are supported
```
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/xnnpack/BUILD#L35
cc_library(
    name = "xnnpack_delegate",
    ...
    deps = [
        ...
        "@XNNPACK//:xnnpack_f32",
    ],
```

Can this be expanded to support quantized models as well? For example, xnnpack already supports `QS8MobileNetV1` 

**Will this change the current api? How?**
No
**Who will benefit with this feature?**

**Any Other info.**

**Comment by teijeong** [comment]
Hi @multiverse-tf , can you take a look or triage?

**Comment by mohantym** [comment]
Hi @teijeong ! I think the range has been expanded for [XNNPACK builds](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/xnnpack/BUILD#L118) now in 2.8 version. Thanks!
