### ISSUE TITLE
STM32F407G Build Error - AddBuiltin() mismatch in arguments

### ISSUE THREAD

**Issue by Pradeepiit** [tensorflow/tensorflow#42756]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution: Ubuntu 18.04.5 LTS
- TensorFlow installed from : source
- Tensorflow version : 2.3.0
- Target platform : STM32F407G - Discovery Board
- Tool chain: STM32 Cube IDE Tool chain

**Problem**

Mismatch in number of arguments between the function definition and the calling function in `AddBuiltin()` function.

Function Definition: `tensorflow/lite/micro/micro_mutable_op_resolver.h` (Line 473)

**Code Snippet:  (Number of arguments - 3)**
`TfLiteStatus AddBuiltin(tflite::BuiltinOperator op, const TfLiteRegistration& registration,                           MicroOpResolver::BuiltinParseFunction parser)`

Calling Function: main.cpp (generated using STM Toolchain)

Code Snippet: (Number of arguments - 2)
`tflite_status = micro_op_resolver.AddBuiltin( tflite::BuiltinOperator_FULLY_CONNECTED, tflite::ops::micro::Register_FULLY_CONNECTED());`

**Sequence of Steps Followed:**

We built all the examples for various compilers using this command.  

`$make -f tensorflow/lite/micro/tools/make/Makefile TAGS="portable_optimized" generate_non_kernel_projects`

hello_world project is created using STM32 Cube IDE.

The tensorflow and third party folders generated inside hello_world project workspace are copied. 

`main.cpp` is created for hello_world

The project is built in the STM32 Cube IDE. During the build process, we have the following error.
`
'g++' -std=c++11 -DTF_LITE_STATIC_MEMORY -DNDEBUG -O3 -DTF_LITE_DISABLE_X86_NEON -I. -I./third_party/gemmlowp -I./third_party/flatbuffers/include -I./third_party/ruy  -c tensorflow/lite/micro/examples/hello_world/main_functions.cc -o tensorflow/lite/micro/examples/hello_world/main_functions.o
tensorflow/lite/micro/examples/hello_world/main_functions.cc: In function ‘void setup()’:
tensorflow/lite/micro/examples/hello_world/main_functions.cc:81:53: error: no matching function for call to ‘tflite::MicroMutableOpResolver<1>::AddBuiltin(tflite::BuiltinOperator, TfLiteRegistration*)’
   	tflite::ops::micro::Register_FULLY_CONNECTED());
                                                 	^
In file included from ./tensorflow/lite/micro/all_ops_resolver.h:16:0,
             	from tensorflow/lite/micro/examples/hello_world/main_functions.cc:18:
./tensorflow/lite/micro/micro_mutable_op_resolver.h:473:16: note: candidate: TfLiteStatus tflite::MicroMutableOpResolver<tOpCount>::AddBuiltin(tflite::BuiltinOperator, const TfLiteRegistration&, tflite::MicroOpResolver::BuiltinParseFunction) [with unsigned int tOpCount = 1; TfLiteStatus = TfLiteStatus; TfLiteRegistration = TfLiteRegistration; tflite::MicroOpResolver::BuiltinParseFunction = TfLiteStatus (*)(const tflite::Operator*, tflite::BuiltinOperator, tflite::ErrorReporter*, tflite::BuiltinDataAllocator*, void**)]
   TfLiteStatus AddBuiltin(tflite::BuiltinOperator op,
            	^~~~~~~~~~
./tensorflow/lite/micro/micro_mutable_op_resolver.h:473:16: note:   candidate expects 3 arguments, 2 provided
Makefile:36: recipe for target 'tensorflow/lite/micro/examples/hello_world/main_functions.o' failed
`
 

Please suggest the code changes

The above steps are executed as suggested in [youtube](https://www.youtube.com/watch?v=gDFWCxrJruQ)

**Comment by Lucy20211** [comment]
Hi all, 
I solved it by modifying the following code portion of main.cpp:

static tflite::MicroMutableOpResolver<1> micro_op_resolver;
// Add dense neural network layer operation
  tflite_status = micro_op_resolver.AddBuiltin(
  tflite::BuiltinOperator_FULLY_CONNECTED,
  tflite::ops::micro::Register_FULLY_CONNECTED());

in this way:
static tflite::MicroMutableOpResolver<1> micro_op_resolver;
tflite_status = micro_op_resolver.AddFullyConnected();


The fact is that AddFullyConnected() function (tensorflow/lite/micro/micro_mutable_op_resolver.h) is defined as follows:

TfLiteStatus AddFullyConnected() {
    return AddBuiltin(BuiltinOperator_FULLY_CONNECTED,
                               *tflite::ops::micro::Register_FULLY_CONNECTED(),
                                ParseFullyConnected);
  }

which avoids the mismatch above.

Hope this can be helpful.

**Comment by kumariko** [comment]
@Pradeepiit Could you please let us know if this issue resolved or not? please check https://github.com/tensorflow/tensorflow/issues/42756#issuecomment-770443361
