### ISSUE TITLE
Tensorflow 2.0 killed during training (opened graph)

### ISSUE THREAD

**Issue by kaen2891** [tensorflow/tensorflow#42768]
Hello, I followed the Seq2seq Attention mechanisms to make Tacotron. I modified (https://www.tensorflow.org/tutorials/text/nmt_with_attention) this webpage but my code doesn't work.

Here is the difference things from upper pages.

- Model: same as Tacotron
- Dataset
Each of my dataset are bigger than text dataset because my decoder input is spectrogram (batch_size, 161, 400). 

So when I followed this:
```
@tf.function
def train_step(inp, targ, enc_hidden):
  loss = 0

  with tf.GradientTape() as tape:
    enc_output, enc_hidden = encoder(inp, enc_hidden)

    dec_hidden = enc_hidden

    dec_input = tf.expand_dims([targ_lang.word_index['<start>']] * BATCH_SIZE, 1)

    # Teacher forcing - feeding the target as the next input
    for t in range(1, targ.shape[1]):
      # passing enc_output to the decoder
      predictions, dec_hidden, _ = decoder(dec_input, dec_hidden, enc_output)

      loss += loss_function(targ[:, t], predictions)

      # using teacher forcing
      dec_input = tf.expand_dims(targ[:, t], 1)
```

as 

```
@tf.function(input_signature=train_step_signature)
def train_step(txt_inp, mel_inp, mag_inp, emo_inp):
    
    with tf.GradientTape() as tape:
        # text_inp = [Batch, 200]
        # mel_inp = [Batch, 160, 400]
        # mag_inp = [Batch, 160, 1025]
        # emo_inp = [Batch, 7]
        
        enc_outputs, _ = encoderNetwork(txt_inp)
        
        go_frames = tf.tile([[0.0]], [args.batch_size, args.n_mels * args.r_factor]) #[batch_size, 400]
        go_frames = tf.expand_dims(go_frames, axis=1)
        mel_input = tf.concat((go_frames, mel_inp), axis=1) #[batch_size, 161, 400]
        hidden1 = None
        hidden2 = None
        hidden3 = None
        prev_context = None
        target = mel_input[:, :, -args.n_mels:] #[batch_size, 161, 80]
        
        for i in range(mel_input.shape[1]): # 161
            
            t_mel_hats, t_alignments, hidden1, hidden2, hidden3, prev_context = decoderNetwork(tf.expand_dims(target[:, i, :], axis=1), emo_inp, enc_outputs, _, hidden1, hidden2, hidden3, prev_context, i)
            
            if i == 0:
                mel_hats = t_mel_hats
                alignments = t_alignments
            else:
                mel_hats = tf.concat((mel_hats, t_mel_hats), axis=1)
                alignments = tf.concat((alignments, t_alignments), axis=0)
            print('{}th finished, mel_hats {} alignments {} next input {}'.format(i, mel_hats.shape, alignments.shape, target.shape))
        
        print('vocoder starts, dec output', mel_hats.shape)
        mag_outputs = vocoderNetwork(mel_hats) 
        
        
        loss1 = loss_function(mel_inp, mel_hats[:, 1:, :])
        loss2 = loss_function(mag_inp, mag_outputs[:, 1*args.r_factor:, :])
        
        loss = loss1 + loss2

    variables = encoderNetwork.trainable_variables + decoderNetwork.trainable_variables + vocoderNetwork.trainable_variables
    gradients = tape.gradient(loss, variables)
    optimizer.apply_gradients(zip(gradients, variables))
    train_loss(loss)

    return mag_outputs, mel_outputs, alignments
```

Firstly, my code is work because when I change to not using iteration, I checked that it worked. And when construct graph, (before getting higher of GPU memory) it doesn't occured problem.

Actually it have to work after construct graphs. But after ```loss = loss1 + loss 2 ``` in my code, it doesn't work.  So I just waited, and 1 more graphs try to construct after 1 hour. Finally, the message come to me: ```Killed```.

I want to use (https://www.tensorflow.org/tutorials/text/nmt_with_attention) this tutorial because I want to use teacher forcing and decoder hidden state each outputs on iteration. In pytorch framework, I checked this seq2seq type model could work but I wonder why it doesn't work on tensorflow.

More information about my server
- GPUS: NVIDIA Quadro GV 100
- Mem: 503G
- Swp: 29.8G
- number of CPU processors: 32
- each CPU: Intel (R) Xeon(R) Silver 4108 CPU @ 1.80GHz

**Comment by Saduf2019** [comment]
@kaen2891 
I ran the code shared and face a different issue on tf 2.3 and tf 2.0, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/7d2e37d36005f6c1f955ba949424475d/untitled402.ipynb)

**Comment by kaen2891** [comment]
No. The reason why I open issue is not ```train_signature```. But the problem which you mentioned is about ```train_signature``` For example
``` @tf.function(input_signature=(tf.TensorSpec(shape=[None], dtype=tf.int32),)) ```

Anyway, maybe I found the reason about my issue. That's using:
```mel_hats = tf.concat((mel_hats, t_mel_hats), axis=1)
alignments = tf.concat((alignments, t_alignments), axis=0)
```
because when the tensorflow going to make graph, this ```concat``` seems to put a lot of pressure. 
Secondly, when I use ```tf.keras.layers.RNN(tf.keras.layers.GRUCell(num_units, recurrent_initializer='glorot_uniform'), return_sequences=True, return_state=True)``` , it also failed to make graph. I think this have some issue.

**Comment by Saduf2019** [comment]
@kaen2891 
Can you please try with later version or nightly and let us know if it helps resolve the issue.
