### ISSUE TITLE
C++ compilation of rule '//tensorflow/core/kernels/batching_util:batch_resource_base' failed

### ISSUE THREAD

**Issue by ipetel** [tensorflow/tensorflow#42766]
**System information**
- OS Platform and Distribution: Ubuntu 18.04.5 LTS
- TensorFlow installed from: source
- TensorFlow version: master
- Installed using: Bazel
- Bazel version (if compiling from source): 3.4.1
- GCC/Compiler version: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- CUDA/cuDNN version: N/A
- Machine info: AWS EC2 t2.2xlarge - 8 vCPU & 32GiB

**Describe the problem**
When trying to Cross build TensorFlow Lite Standalone Pip with Bazel for aarch64 (Python3.5 and Python3.7)
using the next tutorial: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package
I'm getting the next error: "C++ compilation of rule '//tensorflow/core/kernels/batching_util:batch_resource_base' failed"

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1) git clone https://github.com/tensorflow/tensorflow.git tf-github-master
2) cd /tf-github-master/tensorflow/tensorflow/lite/tools/pip_package/
3) tried both of the next commands and got the same issue:
3.1) sudo CI_DOCKER_EXTRA_PARAMS="-e CUSTOM_BAZEL_FLAGS=--define=tflite_pip_with_flex=true" \
../../../tools/ci_build/ci_build.sh PI-PYTHON3 \
tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh aarch64
3.2) sudo CI_DOCKER_EXTRA_PARAMS="-e CUSTOM_BAZEL_FLAGS=--define=tflite_pip_with_flex=true" \
../../../tools/ci_build/ci_build.sh PI-PYTHON37 \
tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh aarch64

**Any other info / logs**
ERROR: /workspace/tensorflow/core/kernels/batching_util/BUILD:236:1: C++ compilation of rule '//tensorflow/core/kernels/batching_util:batch_resource_base' failed (Exit 1): aarch64-linux-gnu-gcc failed: error executing command
  (cd /home/ubuntu/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH='' \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/local/bin/python3.7 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    TF2_BEHAVIOR=1 \
    TF_CONFIGURE_IOS=0 \
  /home/ubuntu/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/aarch64_linux_toolchain/bin/aarch64-linux-gnu-gcc -fstack-protector -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -isystem /home/ubuntu/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/aarch64_linux_toolchain/lib/gcc/aarch64-linux-gnu/8.3.0/include -isystem /home/ubuntu/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/aarch64_linux_toolchain/lib/gcc/aarch64-linux-gnu/8.3.0/include-fixed -isystem /home/ubuntu/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/aarch64_linux_toolchain/aarch64-linux-gnu/include/c++/8.3.0/ -isystem /home/ubuntu/tensorflow/bazel-ci_build-cache/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/aarch64_linux_toolchain/aarch64-linux-gnu/libc/usr/include/ -isystem /usr/include/python3.7 -isystem /usr/include/ -MD -MF bazel-out/aarch64-opt/bin/tensorflow/core/kernels/batching_util/_objs/batch_resource_base/batch_resource_base.pic.d '-frandom-seed=bazel-out/aarch64-opt/bin/tensorflow/core/kernels/batching_util/_objs/batch_resource_base/batch_resource_base.pic.o' -fPIC -DTF_USE_SNAPPY -DHAVE_SYS_UIO_H -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DEIGEN_HAS_TYPE_TRAITS=0' -D__CLANG_SUPPORT_DYN_ANNOTATION__ -iquote . -iquote bazel-out/aarch64-opt/bin -iquote external/com_google_absl -iquote bazel-out/aarch64-opt/bin/external/com_google_absl -iquote external/nsync -iquote bazel-out/aarch64-opt/bin/external/nsync -iquote external/eigen_archive -iquote bazel-out/aarch64-opt/bin/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/aarch64-opt/bin/external/local_config_sycl -iquote external/gif -iquote bazel-out/aarch64-opt/bin/external/gif -iquote external/libjpeg_turbo -iquote bazel-out/aarch64-opt/bin/external/libjpeg_turbo -iquote external/com_google_protobuf -iquote bazel-out/aarch64-opt/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/aarch64-opt/bin/external/zlib -iquote external/com_googlesource_code_re2 -iquote bazel-out/aarch64-opt/bin/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/aarch64-opt/bin/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/aarch64-opt/bin/external/fft2d -iquote external/highwayhash -iquote bazel-out/aarch64-opt/bin/external/highwayhash -iquote external/double_conversion -iquote bazel-out/aarch64-opt/bin/external/double_conversion -iquote external/snappy -iquote bazel-out/aarch64-opt/bin/external/snappy -isystem external/nsync/public -isystem bazel-out/aarch64-opt/bin/external/nsync/public -isystem external/eigen_archive -isystem bazel-out/aarch64-opt/bin/external/eigen_archive -isystem external/gif -isystem bazel-out/aarch64-opt/bin/external/gif -isystem external/com_google_protobuf/src -isystem bazel-out/aarch64-opt/bin/external/com_google_protobuf/src -isystem external/zlib -isystem bazel-out/aarch64-opt/bin/external/zlib -isystem external/farmhash_archive/src -isystem bazel-out/aarch64-opt/bin/external/farmhash_archive/src -isystem external/double_conversion -isystem bazel-out/aarch64-opt/bin/external/double_conversion -w -DAUTOLOAD_DYNAMIC_KERNELS -O3 '-std=c++14' -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -no-canonical-prefixes -fno-canonical-system-headers -c tensorflow/core/kernels/batching_util/batch_resource_base.cc -o bazel-out/aarch64-opt/bin/tensorflow/core/kernels/batching_util/_objs/batch_resource_base/batch_resource_base.pic.o)
Execution platform: @local_execution_config_platform//:platform
In file included from ./tensorflow/core/lib/monitoring/percentile_sampler.h:27,
                 from tensorflow/core/kernels/batching_util/batch_resource_base.cc:22:
./tensorflow/core/lib/monitoring/mobile_percentile_sampler.h: In instantiation of 'static tensorflow::monitoring::PercentileSampler<NumLabels>* tensorflow::monitoring::PercentileSampler<NumLabels>::New(const tensorflow::monitoring::MetricDef<(tensorflow::monitoring::MetricKind)1, tensorflow::monitoring::Percentiles, NumLabels>&, std::vector<double>, size_t, tensorflow::monitoring::UnitOfMeasure) [with int NumLabels = 2; size_t = long unsigned int]':
tensorflow/core/kernels/batching_util/batch_resource_base.cc:31:69:   required from here
./tensorflow/core/lib/monitoring/mobile_percentile_sampler.h:63:10: error: no matching function for call to 'tensorflow::monitoring::PercentileSampler<2>::PercentileSampler()'
   return new PercentileSampler<NumLabels>();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./tensorflow/core/platform/default/logging.h:29,
                 from ./tensorflow/core/platform/logging.h:27,
                 from ./tensorflow/core/framework/allocator.h:28,
                 from ./tensorflow/core/framework/op_kernel.h:24,
                 from ./tensorflow/core/kernels/batching_util/batch_resource_base.h:21,
                 from tensorflow/core/kernels/batching_util/batch_resource_base.cc:16:
./tensorflow/core/lib/monitoring/mobile_percentile_sampler.h:54:31: note: candidate: 'tensorflow::monitoring::PercentileSampler<NumLabels>::PercentileSampler(const tensorflow::monitoring::PercentileSampler<NumLabels>&) [with int NumLabels = 2]' <deleted>
   TF_DISALLOW_COPY_AND_ASSIGN(PercentileSampler);
                               ^~~~~~~~~~~~~~~~~
./tensorflow/core/platform/macros.h:112:3: note: in definition of macro 'TF_DISALLOW_COPY_AND_ASSIGN'
   TypeName(const TypeName&) = delete;         \
   ^~~~~~~~
./tensorflow/core/lib/monitoring/mobile_percentile_sampler.h:54:31: note:   candidate expects 1 argument, 0 provided
   TF_DISALLOW_COPY_AND_ASSIGN(PercentileSampler);
                               ^~~~~~~~~~~~~~~~~
./tensorflow/core/platform/macros.h:112:3: note: in definition of macro 'TF_DISALLOW_COPY_AND_ASSIGN'
   TypeName(const TypeName&) = delete;         \
   ^~~~~~~~
In file included from ./tensorflow/core/lib/monitoring/percentile_sampler.h:27,
                 from tensorflow/core/kernels/batching_util/batch_resource_base.cc:22:
./tensorflow/core/lib/monitoring/mobile_percentile_sampler.h: In instantiation of 'static tensorflow::monitoring::PercentileSampler<NumLabels>* tensorflow::monitoring::PercentileSampler<NumLabels>::New(const tensorflow::monitoring::MetricDef<(tensorflow::monitoring::MetricKind)1, tensorflow::monitoring::Percentiles, NumLabels>&, std::vector<double>, size_t, tensorflow::monitoring::UnitOfMeasure) [with int NumLabels = 1; size_t = long unsigned int]':
tensorflow/core/kernels/batching_util/batch_resource_base.cc:43:69:   required from here
./tensorflow/core/lib/monitoring/mobile_percentile_sampler.h:63:10: error: no matching function for call to 'tensorflow::monitoring::PercentileSampler<1>::PercentileSampler()'
   return new PercentileSampler<NumLabels>();
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./tensorflow/core/platform/default/logging.h:29,
                 from ./tensorflow/core/platform/logging.h:27,
                 from ./tensorflow/core/framework/allocator.h:28,
                 from ./tensorflow/core/framework/op_kernel.h:24,
                 from ./tensorflow/core/kernels/batching_util/batch_resource_base.h:21,
                 from tensorflow/core/kernels/batching_util/batch_resource_base.cc:16:
./tensorflow/core/lib/monitoring/mobile_percentile_sampler.h:54:31: note: candidate: 'tensorflow::monitoring::PercentileSampler<NumLabels>::PercentileSampler(const tensorflow::monitoring::PercentileSampler<NumLabels>&) [with int NumLabels = 1]' <deleted>
   TF_DISALLOW_COPY_AND_ASSIGN(PercentileSampler);
                               ^~~~~~~~~~~~~~~~~
./tensorflow/core/platform/macros.h:112:3: note: in definition of macro 'TF_DISALLOW_COPY_AND_ASSIGN'
   TypeName(const TypeName&) = delete;         \
   ^~~~~~~~
./tensorflow/core/lib/monitoring/mobile_percentile_sampler.h:54:31: note:   candidate expects 1 argument, 0 provided
   TF_DISALLOW_COPY_AND_ASSIGN(PercentileSampler);
                               ^~~~~~~~~~~~~~~~~
./tensorflow/core/platform/macros.h:112:3: note: in definition of macro 'TF_DISALLOW_COPY_AND_ASSIGN'
   TypeName(const TypeName&) = delete;         \
   ^~~~~~~~
Target //tensorflow/lite/python/interpreter_wrapper:_pywrap_tensorflow_interpreter_wrapper failed to build
INFO: Elapsed time: 1460.329s, Critical Path: 93.08s
INFO: 4912 processes: 4912 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by ipetel** [comment]
Architecture: x86_64

**Comment by ipetel** [comment]
I have tried again with Ubuntu 20.04.1 LTS (AWS EC2 t2.2xlarge)
and got the same issue

**Comment by cfRod** [comment]
We had similar issues here: https://github.com/tensorflow/tensorflow/pull/42461#event-3713295848
for which a fix was updated two days ago. The error logs on OpenLab's CI: https://logs.openlabtesting.org/logs/periodic-18/github.com/tensorflow/tensorflow/master/tensorflow-arm64-build-daily-master/5b04a0e/job-output.txt.gz captured the same error.

**Comment by ipetel** [comment]
Hey @ymodak, I have managed to build from source successfully! 
@cfRod thanks again for the update.

**Comment by ravikyram** [comment]
@ipetel 

Please, close this thread if your issue was resolved. Thanks!
