### ISSUE TITLE
tfp.distributions works on TF vrsn 2.1 but not in 2.2 or 2.3......why?

### ISSUE THREAD

**Issue by mdJawad006** [tensorflow/tensorflow#42771]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mdJawad006** [comment]
Why do I have to downgrade my TF to use probability distribution?? why cant I use it in 2.2 or 2.3.....changing versions back and forth is painful

**Comment by ravikyram** [comment]
@mdJawad006 

I was able to import tensorflow probability without any issues in TF version 2.3.Please, find the gist [here](https://colab.research.google.com/gist/amahendrakar/0ba562a15ba0f1c02ca26cd97500d519/42771.ipynb).Could you please check you are running the latest version of tensorflow probability 0.11.0. Thanks!
