### ISSUE TITLE
Minor documentation / code mismatch in Optimizer

### ISSUE THREAD

**Issue by gibiansky** [tensorflow/tensorflow#4278]
The `Optimizer` class has the [following method](https://github.com/tensorflow/tensorflow/blob/7e7dff529fd35edea443580d58e95f5de39b5356/tensorflow/python/training/optimizer.py#L388):

```python
  def _valid_dtypes(self):
    """Valid types for loss, variables and gradients.
    Defaults to `float32`. Subclasses should override to allow other types.
    Returns:
      Valid types for loss, variables and gradients.
    """
    return set([dtypes.float16, dtypes.float32, dtypes.float64])
```

The docstring says that `_valid_dtypes` defaults only to `float32`, but the code also allows `float16` and `float64`. The docstring should be updated to reflect that the default allowed set includes these other float types.

**Comment by tatatodd** [comment]
@gibiansky Thanks for the comment!  Would you like to send a PR?

**Comment by AnishShah** [comment]
I can send a PR. If it is okay with @gibiansky ?

**Comment by gibiansky** [comment]
Go ahead!

**Comment by haosdent** [comment]
Hi, @tatatodd Are you still working on this? If you are not available, I would like to fix this.

**Comment by agrawalnishant** [comment]
Hi @haosdent , please go ahead. Thank you!

**Comment by haosdent** [comment]
Oh, I saw it fixed at https://github.com/tensorflow/tensorflow/pull/4351/files cc @aselle

**Comment by gibiansky** [comment]
It looks like this was fixed in [this PR](https://github.com/tensorflow/tensorflow/pull/4351/files) so I'm going to go ahead and close this to avoid cluttering the issue tracker.
