### ISSUE TITLE
Community feedback for translated landing pages

### ISSUE THREAD

**Issue by jaketae** [tensorflow/tensorflow#42781]
Hello, I was wondering if the TensorFlow tutorial [landing page](https://www.tensorflow.org/tutorials?hl=ko) should be translated by the community. Though I cannot be certain, the page seems to be built from [this source](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/_index.yaml), which is in yaml format. After checking out the TensorFlow website under different language options, namely Korean, Chinese, and Japanese, I found out that none of the languages had a translated landing page. Should this be included in the to-do list of things, or is it somehow handled differently or internally? Thank you.

--------------------

On a similar note, [`_toc.yaml`](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/_toc.yaml) is currently not being translated under any language. It seems like the website is internally/automatically translating it, but some of the translated words remain inconsistent with those used in the actual translated documents.

**Comment by hibamtol1** [comment]
Hi Can I contribute by translate in korean? If there's any task, I think I can do that! Please answer back.

**Comment by lamberta** [comment]
Hi @hibamtol1 , thanks for volunteering.
Community contributions can be made to this repo: https://github.com/tensorflow/docs-l10n
Please use the GitLocalize project to make sure your contribution is reviewed: https://gitlocalize.com/tensorflow/docs-l10n
Thanks
