### ISSUE TITLE
//tensorflow:libtensorflow.so target won't build

### ISSUE THREAD

**Issue by hillegass** [tensorflow/tensorflow#4279]
Trying to build libtensorflow.so from source on a Mac using Bazel 3.1, I get an error. Log is attached below.

### Environment info
Operating System: MacOS X 10.11.6, Xcode 7.3.1

Installed version of CUDA and cuDNN: 
No CUDA

If installed from source, provide 
1. The commit hash (`git rev-parse HEAD`)

    2a6d7511f13a0387857081f1cf64d282d2816a62

2. The output of `bazel version`

    Build label: 0.3.1
    Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
    Build time: Fri Jul 29 09:05:18 2016 (1469783118)
    Build timestamp: 1469783118
    Build timestamp as int: 1469783118

### Build log

    $ bazel build //tensorflow:libtensorflow.so
    Extracting Bazel installation...
    Sending SIGTERM to previous Bazel server (pid=8488)... done.
    .
    ERROR: /Users/Projects/tensorflow/tensorflow/core/BUILD:942:1: no such target '//tensorflow/tools/git:gen/spec.json': target 'gen/spec.json' not declared in package 'tensorflow/tools/git' defined by /Users/Projects/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
    ERROR: /Users/Projects/tensorflow/tensorflow/core/BUILD:942:1: no such target '//tensorflow/tools/git:gen/head': target 'gen/head' not declared in package 'tensorflow/tools/git' defined by /Users/Projects/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
    ERROR: /Users/Projects/tensorflow/tensorflow/core/BUILD:942:1: no such target '//tensorflow/tools/git:gen/branch_ref': target 'gen/branch_ref' not declared in package 'tensorflow/tools/git' defined by /Users/Projects/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
    ERROR: Analysis of target '//tensorflow:libtensorflow.so' failed; build aborted.
    INFO: Elapsed time: 5.724s

**Comment by aselle** [comment]
It looks like you haven't run ./configure.

**Comment by hillegass** [comment]
Ugh. I'm an idiot. (I had run configure, but then I did pull to update my copy of the repository.)  I'm so sorry.

**Comment by petewarden** [comment]
@aselle Any chance we can add an error message mentioning ./configure here? We used to have a helpful prompt for idiots like me who forgot to run it, but I'm not sure where it went. I'm betting that would save quite a few engineer-hours for all our users. :)

**Comment by aselle** [comment]
Do you know of an easy way to accomplish this in Bazel? We could always make a dependent filename "please_rerun_configure" but that is unintuitive to the uninitiated (and smells of the pre C++11 template static_assert  technique). Filed bug for that #4386.

**Comment by DimanNe** [comment]
Can anybody add that I have to run `./configure` [here](https://www.tensorflow.org/api_guides/cc/guide)?

**Comment by aselle** [comment]
I'll do that.

**Comment by RohitDulam** [comment]
I'm having the same issue, (gen/spec.json not declared in package) but I'm using Windows 10, so how do I run ./configure on windows? Or is there any other solution for the issue?

**Comment by mozi22** [comment]
Hi, I am using Ubuntu 14.04. I tried to follow the instructions from [here](https://github.com/cjweeks/tensorflow-cmake) but i get an error saying 

`ERROR: no such target '//tensorflow:libtensorflow_all.so': target 'libtensorflow_all.so' not declared in package 'tensorflow' (did you mean 'libtensorflow_cc.so'?) defined by /home/muazzam/mywork/python/tensorflow/tensorflow/BUILD.
INFO: Elapsed time: 0.047s`

This error occurs when I use the following command from the cjweeks/tensorflow repository documentation `bazel build tensorflow:libtensorflow_all.so`

**Comment by qiaohaijun** [comment]
I forgot exec `./configure`

**Comment by Tomhouxin** [comment]
@mozi22 I ran into the same problem as you, and I executed./configure, how do you solve it, thank you

**Comment by Htiango** [comment]
@Tomhouxin did you solve it? I did the execution and still met the problem
