### ISSUE TITLE
Support more image formats

### ISSUE THREAD

**Issue by vade** [tensorflow/tensorflow#428]
Hello

Forgive me if Ive missed something obvious - new to Tensorflow / machine learning.

I notice there are image creation functions which deal with JPG and PNG image creation via parsing those formats.

Is it planned to support uncompressed images? Client applications may want to decompress video frames and use them for analysis.

Perhaps I am missing a way to construct a tensor from an uncompressed byte array? How would one handle some video optimization for byte alignment / stride etc? 

If there is a more appropriate place to ask beginner questions I am happy to take the conversation there. Thank you!

**Comment by martinwicke** [comment]
This is a perfectly reasonable feature request. I've change the title to be more general.

For uncompressed images in particular the workaround is rather easy: If you can load your image into a [width, height, channels] shaped numpy array, you can pass that to any TensorFlow function. That doesn't solve the reading from file question for ppm/bmp files or the like, but there are solutions for that in python, see for instance the pillow module: https://python-pillow.github.io/

**Comment by ebrevdo** [comment]
You can also do some small amount of decoding using [decode_raw](https://www.tensorflow.org/versions/master/api_docs/python/io_ops.html#decode_raw) and [string_to_number](https://www.tensorflow.org/versions/master/api_docs/python/array_ops.html#string_to_number).

It would be easy to add python wrappers around these for specific formats, assuming the image format encodes exactly as a raw byte grid.

**Comment by vade** [comment]
Thanks for the link and info - very glad this seems reasonable!

I suppose my only additional 'concern' so to speak, is how many video codecs and engines bytesPerRow is aligned for memory access optimization and not tightly aligned on actual pixel data. If not taken into account in a tensor I imagine would *seriously* throw off any learned models.

For example, I work with Apples Core Video which is quite fast, and their CPU pixel buffer may have padding - this would require either clients to strip the padding and do memory copies into TF, or for TF to have some sort of knowledge about this sort of format and handle it internally somehow.

Totally get this is a vastly different prospect for a machine learning tool to inherit the prospect of images not being 'tightly packed' and convoluting what a tensor might be. Just throwing out a concern from a video nerd.

Anyway, speaking aloud. I'm the kind of 'glue libraries together' programmer that prefers when API's are as simple as possible and I can just pass in my byte array and the right thing happens :) 

Thanks again for listening / considering.

**Comment by ebrevdo** [comment]
TensorFlow uses Eigen Tensor::Map to map memory internally.  Tensors are always assumed dense, row-major, and memory-aligned; for example, [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor_types.h#L80) is the definition of a Matrix.  Working with external memory directly may be possible, but would require a lot of additional consideration; copying is really much easier.  And anyway for most image stuff you'd want to work on the GPU anyway, so you'll want to copy. Anyway, @keveman or @vrv could say more about working with existing memory directly.  You'd have to create an op that's either similar to a [VariableOp](https://github.com/tensorflow/tensorflow/blob/9c3043ff3bf31a6a81810b4ce9e87ef936f1f529/tensorflow/core/kernels/variable_ops.cc) or that subclasses / is similar to [InitializableLookupTable](https://github.com/tensorflow/tensorflow/blob/9c3043ff3bf31a6a81810b4ce9e87ef936f1f529/tensorflow/core/kernels/initializable_lookup_table.h#L25) and returns the frames wrapped as Tensors.  Again, there'll be some memory management considerations.

**Comment by vade** [comment]
Thanks for the information. Seems like a copy is lowest cost of entry and having things just work™ is good. Looking forward to this feature.

**Comment by alialerwi** [comment]
How do i convert from ImageFileTensor back to Array[byte] ? thank you in advance!
