### ISSUE TITLE
Create data generator with tf.data.dataset for sequence models

### ISSUE THREAD

**Issue by RaminNateghi** [tensorflow/tensorflow#42808]
I have an image dataset including RGB images: img1.png, img2.png ... img250.png. I have extracted 100 small patches with size [64,64,3] from each image. So, I have now dataset like img1_1.png, img1_2.png ...img1_100.png, img2_1.png, img2_2.png, ... img2_100.png, img3_1, .....

I want to create a data generator with tf.data.dataset.from_tensor_slices to pass all patches of each image to an RNN model. So, I wanna the generator creates output like this : [batch_size, 100, 64, 64, 3]

How can I do that?

**Comment by ymodak** [comment]
Did you see [Simple Batching](https://www.tensorflow.org/guide/data#simple_batching) for this transformation?
`Dataset.batch()` takes `batch_size` arg. https://www.tensorflow.org/api_docs/python/tf/data/Dataset?version=nightly#batch
