### ISSUE TITLE
A problem about the install of tensorflow

### ISSUE THREAD

**Issue by momohina** [tensorflow/tensorflow#42810]
Even though I installed tensorflow, I failed to import it. It seems that the module tensorflow could not be found.
Here, I insert my coding.

Here, I am going to tell the history which has led to this problem.

I installed "tensorflow (ver 2.0)" to python with "pip (ver 20.0.2)" code.
As an environment, I am using "jupyter lab" in Anaconda 64 bit.

First, I executed the following code several times.
**pip install tensorflow** 

Then, I executed the following code mistakenly, which might have caused the problem.
**pip install tensorflow as tf**

At this time, the packages administered by pip have included **tensorflow and tf (ver 1.0.0)**.

As a result, now I have the trouble as I have told.

In addition, I tried to uninstall both tensorflow and tf, only to fail. Here is codes I executed.
**pip uninstall tensorflow**
**pip uninstall tf**

Could you please tell me how to solve this problem?
(Here, I attached the image of my coding.)
<img width="601" alt="imag1" src="https://user-images.githubusercontent.com/70477660/91662272-41933700-eb1c-11ea-98a0-346fe6f67ce1.png">
<img width="430" alt="imag2" src="https://user-images.githubusercontent.com/70477660/91662275-4821ae80-eb1c-11ea-9a07-bde0c18801de.png">

**Comment by Halix267** [comment]
Try to run this on your anaconda prompt. Hope this will solve your issue.

conda create -n tf-2 tensorflow python=3.7                     #this command will create the environment with tensorflow 2
conda activate tf-2                                                             #this willl activate your environment

Hope this sol will resolve your issue :)
For more information visit  https://docs.anaconda.com/anaconda/user-guide/tasks/tensorflow/

**Comment by ravikyram** [comment]
@momohina 

Create a vitrual environment.

```
conda create -n xxx python=3.7 # xxx you can give any name to your environment.
conda activate xxx
```

And now install tensorflow from

```
pip install tensorflow
import tensorflow as tf
```
Hope you should not get any problem if you follow above steps. Thanks!

**Comment by momohina** [comment]
Thank you for giving me advice!

I seem to have successfully created a virtual environment.
However, in this environment, I failed to activate **jupyter lab**.
According to the answer to my command  _(base) C: ... > jupyter lab_  (on the second attached image), it seems that "jupyter" is either internal or external command, and that "jupyter" is not regarded as an operable program or batch file.
Could you please tell me how to activate jupyter lab in a virtutal environment?

I am sorry for asking a question again.

Here, I attached images of anaconda prompt.
<img width="560" alt="imag3" src="https://user-images.githubusercontent.com/70477660/91690519-10107f00-eba1-11ea-9928-d0e93c792036.png">
<img width="560" alt="imag4" src="https://user-images.githubusercontent.com/70477660/91690523-1141ac00-eba1-11ea-9130-e0004df566f6.png">

**Comment by ravikyram** [comment]
@momohina 

This looks like issue with Jupyter and anaconda but not with Tensorflow bug or feature request.Please, post the issue in Anaconda repo from [here](https://github.com/ContinuumIO/anaconda-issues/issues/new). Thanks!
