### ISSUE TITLE
Summary in TF2.3 wraps unexpected name_scope

### ISSUE THREAD

**Issue by BlueFisher** [tensorflow/tensorflow#42816]
When `tf.summary` is in a condition scope, the tag in tensorboard will wrap unexpected 'cond/'.

For example, when executed the following code, the tag in tensorboard is `cond/foo`, not `foo`.

```python
import tensorflow as tf

writer = tf.summary.create_file_writer('log')
step = tf.Variable(0, dtype=tf.int64)


@tf.function
def test():
    if step % 5 == 0:
        with writer.as_default():
            tf.summary.scalar('foo', 0.5, step=step)
            writer.flush()

    step.assign_add(1)


for _ in range(100):
    test()
```

This bug only shows in TF2.3. Tags are correct in tf below 2.3.

**Comment by Saduf2019** [comment]
@BlueFisher 
I ran the code on tf 2.3 and on tf 2.2 and see that there is no error, please refer tot he [gist here](https://colab.research.google.com/gist/Saduf2019/16640d978f4761d9882e545fe7de87ec/untitled400.ipynb).

**Comment by BlueFisher** [comment]
@Saduf2019 
The code has no error, but the tag in tensorboard is `cond/foo`, not `foo`. Please refer to this [gist](https://colab.research.google.com/gist/BlueFisher/230a620b8c13fb29bd9e989710c6c596/untitled400.ipynb)

**Comment by jvishnuvardhan** [comment]
@BlueFisher I think this is intended behavior. The `name` argument for `tf.summary.scalar` clearly explains `name` is prefixed by any active name scopes. Please [check here](https://www.tensorflow.org/api_docs/python/tf/summary/scalar) for more details on `tf.summary.scalar`. Thanks!

>   name: A name for this summary. The summary tag used for TensorBoard will  
>     be this name prefixed by any active name scopes.

**Comment by BlueFisher** [comment]
@jvishnuvardhan Thanks a lot
