### ISSUE TITLE
Seq2Seq example - shape error while decoding

### ISSUE THREAD

**Issue by modrymar** [tensorflow/tensorflow#4281]
When I try to run the tutorial available at [https://www.tensorflow.org/versions/r0.10/tutorials/seq2seq/index.html](https://www.tensorflow.org/versions/r0.10/tutorials/seq2seq/index.html) it works great. The model is training and the proximity is decreasing. 

For training I used the default data and default command:
`python translate.py  --data_dir [your_data_directory] --train_dir [checkpoints_directory]  --en_vocab_size=40000 --fr_vocab_size=40000` (substituting directory paths of course)

However when I try using the model by running `python translate.py --decode
  --data_dir [your_data_directory] --train_dir [checkpoints_directory]` I get the following error:

```
Traceback (most recent call last):
  File "translate.py", line 290, in <module>
    tf.app.run()
  File "/home/user/venv/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "translate.py", line 285, in main
    decode()
  File "translate.py", line 248, in decode
    target_weights, bucket_id, True)
  File "/www/data/user/tensorflow/tensorflow/models/rnn/translate/seq2seq_model.py", line 244, in step
    outputs = session.run(output_feed, input_feed)
  File "/home/user/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 382, in run
    run_metadata_ptr)
  File "/home/user/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 640, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1,) for Tensor 'weight5:0', which has shape '(64,)'
```

It looks like the script is expecting the whole batch (which is set to 64 by default) but when I type any input, it creates only 1 sample of data.

Version of tensorflow: `tensorflow==0.10.0rc0` (git commit I use `f71cc62282bf2e066f9ebd08cf3f605fc98c6e41`)

Thank you for any ideas

**Comment by modrymar** [comment]
I managed to fix the problem. However, I believe that there has to be a better way how to do it.

I changed the following rows of the `decode` method in `translate.py`.
```
# model.batch_size = 1 -> Changed the size of the batch to 64 (expected size)
model.batch_size = 64

# ...

# encoder_inputs, decoder_inputs, target_weights = model.get_batch(
#         {bucket_id: [(token_ids, [])]}, bucket_id)  -> Extended the data list to 64 items
encoder_inputs, decoder_inputs, target_weights = model.get_batch(
          {bucket_id: [(token_ids, [])]*64}, bucket_id)

# ...

# outputs = [int(np.argmax(logit, axis=1)) for logit in output_logits] -> Get only the first batch from the output
outputs = [int(np.argmax(logit[:1,:], axis=1)) for logit in output_logits] 
```

As I have mentioned, it is not effective and I believe there is a better way how to fix the problem. My changes work as a hot fix, though.

Thanks for any additional advices, tips or ideas

**Comment by tatatodd** [comment]
@lukaszkaiser might have some ideas.

**Comment by lukaszkaiser** [comment]
I tracked it down to the shape of placeholders in seq2seq_model (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/translate/seq2seq_model.py) being set to [batch_size] statically on init. It should be [None] so it can be changed dynamically. Corrected a day ago -- should all work ok now on head, no need for your tweak :).
