### ISSUE TITLE
tflite suppport for LSTM / RNN

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#42827]
Per [tflite roadmap](https://www.tensorflow.org/lite/guide/roadmap#usability) there is upcomming support forLSTM / RNN - when we can expect this for tflite?

**Comment by abattery** [comment]
Please take a look at the following guide document for RNN model support:

https://www.tensorflow.org/lite/convert/rnn

**Comment by ravikyram** [comment]
@peter197321 

Please, refer the below link and see if it helps you.

https://groups.google.com/a/tensorflow.org/g/tflite/c/Ub4apUvblN8

Thanks!
