### ISSUE TITLE
tflite delagte to nn accelerator

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#42826]
I'm looking to create or contribute to NN delegator which is applicable to NPU, is there any open-source project for delegator which can be (re)used with tflite? I'm not so much interested in GPU, Hexagon DSP etc...

**Comment by ymodak** [comment]
Did you get a chance to see [TensorFlow Lite NNAPI delegate](https://www.tensorflow.org/lite/performance/nnapi) for NPU?

**Comment by peter197321** [comment]
yes, somehow - but NNAPI seems to be not enough since HW I used has more capabilities, and seems there some problems with Ops versioning not reflected with NNAPI ...

**Comment by srjoglekar246** [comment]
@multiverse-tf for custom delegates.
@peter197321 which NPU is this? Or is it your own custom hardware you want to target?

**Comment by peter197321** [comment]
NNAPI specification has subset of TFLite operators and uses its versioning scheme for operators. If there is a mismatch on operators versioning then the operator is refused to delegate to NNAPI.
Why the operator (e.g. RELU) is refused to be delegated to NNAPI.

**Comment by peter197321** [comment]
@multiverse-tf for custom delegates. :) multiverse-tf doesn’t have any public repositories yet.

**Comment by srjoglekar246** [comment]
> NNAPI specification has subset of TFLite operators and uses its versioning scheme for operators. If there is a mismatch on operators versioning then the operator is refused to delegate to NNAPI.
> Why the operator (e.g. RELU) is refused to be delegated to NNAPI.

Because operator version changes mean some change in behavior, and each delegate chooses which version they support. Delegating a newer version might provide an output different from CPU inference.

Could you specify which ops have this issue, and the version in the model?
(or share the model, even if untrained, for me to inspect myself)

**Comment by peter197321** [comment]
Here are some ops in different versions: BuiltinOperator_RELU, BuiltinOperator_RELU6, BuiltinOperator_LOGISTIC, BuiltinOperator_FULLY_CONNECTED, ...

**Comment by peter197321** [comment]
One of the problems is that if the operator version does not match then the operator is refused to be delegated over NNAPI and the part of the graph is computed on CPU instead of acceleration.

**Comment by srjoglekar246** [comment]
@peter197321 That is expected, since the delegate may not perform the same operation as the newest version of the op. Can you specify which version of these ops is present in the model?

**Comment by peter197321** [comment]
Due to NN-API limitation (versioning problems) so is there some full sample delegate for NPU?

**Comment by srjoglekar246** [comment]
Not that I know of. @multiverse-tf can point to documentation for you to write your own delegate.

**Comment by peter197321** [comment]
Is there a way to write your own delegate the most efficient way to utilize the Hardware NPU (so NN-API might not be a good fit)?

**Comment by mohantym** [comment]
Hi @peter197321 !

We are checking to see whether you still need help in this issue . 
Have you tested "[create your own delegate](https://www.tensorflow.org/lite/performance/implementing_delegate#implementing_your_own_custom_delegate)" section from 2.11 yet.  

Thank you!
