### ISSUE TITLE
Better Instruction/Insight as to how models.load_model() custom objects are loaded (doc/feature request/bug?)

### ISSUE THREAD

**Issue by EnderWiggin14** [tensorflow/tensorflow#42830]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
[https://www.tensorflow.org/api_docs/python/tf/keras/models/load_model?hl=no]()

It may be better to have a separate URL for new documentation.

## Description of issue (what needs changing):
This could be treated potentially as a feature request and/or bug as the issues encountered may or may not be a result of things out of my control. Better documentation is requested regardless.

The documentation on how to load models that contain custom objects is lacking as to prerequisites to make them loadable.

The only thing that is clear is that a dict of the objects of interest must be provided. It isn't clear what they keys are supposed to be. It is also unclear as to how the objects are loaded and what happens at load time.

When running this code

```
    def load_model(self, model_name, model_path):
        """Reload tensorflow session for saved model. Called by djinn.load,

        Args: 
            model_path (str, optional): Location of model if different than 
                       location set during training.
            model_name (str, optional): Name of model if different than 
                       name set during training.
        
        Returns: 
            Object: djinn regressor model.
            
        """
        # self.__sess = {}
        self.__models={}
        for p in range(0, self.__n_trees):
            tf.keras.backend.clear_session()
            # tf.reset_default_graph()
            # new_saver = \
            # tf.train.import_meta_graph('%s%s_tree%s.ckpt.meta'%(model_path,model_name,p))
            # self.__sess[p] = tf.Session()
            # new_saver.restore(self.__sess[p], '%s%s_tree%s.ckpt'%(model_path,model_name,p))
            self.__models[p] = tf.keras.models.load_model('%s%s_tree%s.ckpt'%(model_path,model_name,p),custom_objects={'WB_Init': WB_Init})
            # self.__models[p] = tf.keras.models.load_model('%s%s_tree%s.ckpt'%(model_path,model_name,p))
            print("Model %s restored"%p)
```

where WB_Init is defined in another file as

```
class WB_Init(tf.keras.initializers.Initializer):
    def __init__(self,dat=None,name=None):
        self.dat = dat
        self.name = name
        # print(type(dat))
        # print(dat)
                
    def __call__(self,shape,dtype):
        
        if not isinstance(self.dat,tf.Tensor):
            a = tf.convert_to_tensor(self.dat,dtype=tf.float32,name=self.name)
        else:
            # a = self.dat.value()
            a = self.dat
                    
        return a
```

and the file doing the calling is indeed loading the object with
```
try:
    from djinn_fns import tree_to_nn_weights, tf_dropout_regression, \
                    get_hyperparams, tf_continue_training, WB_Init
except:
    from djinn.djinn_fns import tree_to_nn_weights, tf_dropout_regression, \
                    get_hyperparams, tf_continue_training, WB_Init
```

WB_Init is used to initialize weights and biases that have been predefined by other functions and need to be trainable. I have avoided the constant initializer because there is no immediate documentation to suggest the values produced by it are capable of being trained (another documentation clarification maybe).

When trying load in an already trained model I'm greeted with the error traceback:

```
Traceback (most recent call last):

  File "C:\Users\Michael\Desktop\Code Projects\DJINN TF2\tests\djinn_regression_example.py", line 81, in <module>
    m=model.predict(x_test) #returns the median prediction if more than one tree

  File "..\djinn\djinn.py", line 383, in predict
    return self.bayesian_predict(x_test, None, random_state)

  File "..\djinn\djinn.py", line 341, in bayesian_predict
    if(self.__models == None): self.load_model(self.modelname, self.modelpath)

  File "..\djinn\djinn.py", line 294, in load_model
    self.__models[p] = tf.keras.models.load_model('%s%s_tree%s.ckpt'%(model_path,model_name,p),custom_objects={'WB_Init': WB_Init})

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\keras\saving\save.py", line 182, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 178, in load_model_from_hdf5
    custom_objects=custom_objects)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\keras\saving\model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 175, in deserialize
    printable_module_name='layer')

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 358, in deserialize_keras_object
    list(custom_objects.items())))

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 617, in from_config
    config, custom_objects)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 1214, in reconstruct_from_config
    process_node(layer, node_data)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 1162, in process_node
    output_tensors = layer(input_tensors, **kwargs)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 757, in __call__
    self._maybe_build(inputs)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 2098, in _maybe_build
    self.build(input_shapes)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\keras\layers\core.py", line 1178, in build
    trainable=True)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py", line 448, in add_weight
    caching_device=caching_device)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\training\tracking\base.py", line 750, in _add_variable_with_custom_getter
    **kwargs_for_getter)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer_utils.py", line 145, in make_variable
    shape=variable_shape if variable_shape else None)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 260, in __call__
    return cls._variable_v1_call(*args, **kwargs)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 221, in _variable_v1_call
    shape=shape)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 199, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2597, in default_variable_creator
    shape=shape)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1518, in __init__
    distribute_strategy=distribute_strategy)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1651, in _init_from_args
    initial_value() if init_from_fn else initial_value,

  File "..\djinn\djinn_fns.py", line 873, in __call__
    a = tf.convert_to_tensor(self.dat,dtype=tf.float32,name=self.name)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1382, in convert_to_tensor_v2
    as_ref=False)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1499, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 338, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 264, in constant
    allow_broadcast=True)

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 282, in _constant_impl
    allow_broadcast=allow_broadcast))

  File "C:\Users\Michael\anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 444, in make_tensor_proto
    raise ValueError("None values not supported.")

ValueError: None values not supported.
```
where it is clear as to the "precise reason" why load is failing. That reason is because the WB_Init.__init__ has a default `dat=None`
which when WB_Init.__call__ is used returns a None value which isn't a support return type for the initialization process. This is what happens when saved to HDF5 format. The tensorflow format breaks in a different manner at save time with the final error being `FailedPreconditionError: ./reg_djinn_test_tree0.ckpt is not a directory`. 

However, it clearly demonstrates that a fresh call of a WB_Init object is made at load time which doesn't make sense to me because the model has already been trained. It should have weights to load. The initializer shouldn't be run as far as I know. Setting `compile=False` doesn't fix this problem. If I just wanted to load the model for inference, I could potentially try to completely reconstruct the model from some other pickled custom object that hold the layer topology and then just use load_weights, but this is a horribly dirty solution. Using this workaround also doesn't let me save the optimizer state so that the model training can be picked-up at the most recent optimizer state.

There is another hypothetical fix where WB_Init is fed the saved weights at load time, but I would have no idea of how to make this happen.

There is also the highly non-preferred way of initializing the network at construction by filling it the models with random numbers and loading the pre-calculated weights after construction (and compilation?) of the model. This defeats the purpose of providing an initializer option at construction time though.

### Clear description

Please provide more a more clear description about how to make custom intializers (or any custom object ) and, more importantly, how to load custom objects (dict keys?) and the prerequisites for making the model and/or object loadable.

This problem and problems like this have been recurring. Some of them don't make sense to me, some are TF1 and don't apply, and some simply don't fix my issue. Some have simply been bugs.

[https://github.com/tensorflow/tensorflow/issues/39752]() ( this is the one that actually demonstrated how to use the 'custom_object' option )
[https://github.com/tensorflow/tensorflow/issues/42778]()
[https://github.com/qqwweee/keras-yolo3/issues/48]()  (referenced in the link above)
[https://github.com/tensorflow/tensorflow/issues/33646]()
[https://github.com/titu1994/keras-efficientnets/issues/3]()
[https://github.com/tensorflow/tensorflow/issues/26061]()

It clearly could use better documentation.

I will provide a full script upon request, and if it is possible, I'd prefer to supply it privately. I'm currently trying to convert a TF1/(TF2 with compatibility) model to a TF2 model that uses Keras. It will (almost certainly) break even if this problem is fixed because the conversion is in progress. The break should be different in nature though if this problem is fixed.

### Correct links

N/A

### Parameters defined

N/A

### Returns defined

N/A

### Raises listed and defined

N/A

### Usage example

See above, but it isn't usable without the rest of the files.

### Submit a pull request?
No

**Comment by Saduf2019** [comment]
@EnderWiggin14 
Could you please let us know the tf version on which this issue is faced and share a  colab gist with the error reported.

**Comment by EnderWiggin14** [comment]
I'm using TF==2.30.

Oddly, the code broke where is wasn't breaking before because of something to do with metrics as I had passed "callbacks=tf.keras.callbacks.BaseLogger()" and it was choking on metrics. This doesn't happen with Spyder IDE.

Here is colab gist. I couldn't figure out how to use regular .py files without giving access to my whole google drive, so this will have to do.

https://colab.research.google.com/drive/1f-eQ22tKMc4o8j3gV81mS2ZIlk-_x34T?usp=sharing

**Comment by Saduf2019** [comment]
@EnderWiggin14 
I do not see the error "None values not supported." in the gist shared, as reported in the issue. I ran the code on nightly as well and do not face any error.

**Comment by EnderWiggin14** [comment]
@Saduf2019
Are you referencing the possibility of using tf.TensorShape? I have added a bypass statement such that

`
def __call__(self,shape,dtype):
        
    if self.dat is None:
        a = tf.TensorShape(shape)            
    else:
        a = tf.convert_to_tensor(self.dat,dtype=tf.float32,name=self.name)
                    
    return a
`
It didn't work. I'm met with the error `TypeError: Cannot convert a TensorShape to dtype: <dtype: 'float32'>` which, from what I read about TensorShape, this is more or less what I expected.
 
Otherwise, I think you have misunderstood the problem. I'm aware of the reason as to why `convert_to_tensor` is failing. I'm well aware that `None` type isn't supported. The problem is that I'm trying to use a custom a initializer which because it tries to run the initializer at load time which fails. I have tried to default to a 2x2 array, but that causes an incompatibility with the first layer. 

The two ways I can think of how to fix this are

1. Somehow give a fully valid Tensor of correct shape and dtype without overwriting the existing weights
2. Feed the correct weights as the input at load time.

Neither of these things appear to be easily accomplished in Python (i.e. without messing with source code)

I'm looking for how a person is supposed to be able to create a custom initializer, save the model that uses it, and re-load the model without having a problem.

I'm not looking initialize with a supplied initializer and then overwriting the weights with the correct weights. This defeats the purpose of being able to

**Comment by EnderWiggin14** [comment]
@Saduf2019 

What Tensorflow version does colab currently default to?

Attached is a screen shot of the error I got from colab. It might be worded a bit differently, but it is the same error.

![colab error](https://user-images.githubusercontent.com/18318520/91885267-7fe04180-ec55-11ea-832b-9eef73bd002d.PNG)

**Comment by gowthamkpr** [comment]
@EnderWiggin14 It defaults to tensorflow 2.3.0 now

**Comment by MarkDaoust** [comment]
Hi @EnderWiggin14 ,

The problem is here:

```
 def __init__(self,dat=None,...):
```

To make a non-trivial object keras-serializable it should define `get_config` and `from_config` methods, [as described here](https://www.tensorflow.org/guide/keras/save_and_serialize#custom_objects)

Since you haven't defined those methods, when keras reconstructs your objects it calls `WB_Init` with no arguments, so `dat` takes the default value of `None`.

Also note in this case instead of defining an initializer, you should consider just setting the variable value after creating the layer (otherwise the initializer needs to remember the initial value, which seems unnecessary).
