### ISSUE TITLE
tflite(micro) resize_nearest_neightbour_test fails for BUILD_TYPE=debug

### ISSUE THREAD

**Issue by andrewstevens-infineon** [tensorflow/tensorflow#42832]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (SHA-1 source): 44dbace063796ea99c5b3d27a3a5810048d5096c

**Describe the current behavior**
Test fails assertions in kernel implementation for BUILD_TYPE=debug build due to size tensor being provided as 2D non-constant tensor.

**Describe the expected behavior**

Test should pass.

**Standalone code to reproduce the issue**

make -f tensorflow/lite/micro/tools/make/Makefile BUILD_TYPE=debug test_kernel_resize_nearest_neighbor_test

Small unified diff patch to correctly setup the size input tensor as 1D constant to correct the issue is attached.

[resize_nearest_neighbor_test.patch.txt](https://github.com/tensorflow/tensorflow/files/5151701/resize_nearest_neighbor_test.patch.txt)

**Comment by advaitjain** [comment]
Thanks, created a PR based on your patch.
