### ISSUE TITLE
Flags For activating AVX Bazel Build CPP Windows

### ISSUE THREAD

**Issue by amitpandey2194** [tensorflow/tensorflow#42838]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.12.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

I successfully managed to build a TensorFlow library for CPP, Windows, but that was without AVX instructions. I want to enable the AVX instructions.  I want to take advantage of it and improve my inference speed.

**Provide the exact sequence of commands/steps that you executed before running into the problem**
I tried the following flags, but during the build, it doesn't recognize it. Looks like that is only valid for Python package.
- bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 

**Any other info / logs**: Error/Warning on the build
cl : Command line warning D9002 : ignoring unknown option '-mavx'
cl : Command line warning D9002 : ignoring unknown option '-mavx2'
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@amitpandey2194 

Just verify, did you the follow the instructions mentioned in this [link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/lib_package/README.md).
Please take a look at the [tested build configuration ](https://www.tensorflow.org/install/source_windows#cpu)of Tensorflow 1.12. Thanks!

**Comment by amitpandey2194** [comment]
Yeah I verify I that I used above mentioned build steps. 
I have already build tensor flow library, but that is without avx avx2 instructions. I want to know how to build one for cpp with avx instructions enabled using bazel build. Which flags to use?

**Comment by ravikyram** [comment]
@amitpandey2194 

Does your cpu support AVX instructions?
Please, see [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements).Thanks!

**Comment by amitpandey2194** [comment]
Yeah, it does. Its intel core i5

**Comment by mihaimaruseac** [comment]
Afaik, windows compiler flags are with `/`, not with `-`. You should consult the flag documentation for the Windows compiler you are using. `-copt` options get passed verbatim to the compiler.

**Comment by amitpandey2194** [comment]
@mihaimaruseac I am using bazel for building the library. Then what flags should I use for incorporating the avx and avx2 build?
Can you please also point me to the documentation you are referring to?

**Comment by bhack** [comment]
Please track also https://github.com/tensorflow/tensorflow/issues/42960

**Comment by ahtik** [comment]
@amitpandey2194 To confirm, initial issue description mentions `conda`, although it's an issue about building from source. Is `conda` involved here to any capacity?

Is the TF `1.12.0` version number correct, trying to build from a ~2 years old source? Doing this requires a rather old bazel (0.15) and MSVC (v2015). Might be worth considering the option of migrating to TF2.2 or 2.3 :) I've built successfully with AVX2 enabled under Windows since TF2.0 release, for every point release.

Unless the `conda` is part of the build recipe, normally the configuration parameters are passed using `python configure.py`. For Windows, `/arch:AVX2` optimization flag enables AVX2.

**Comment by mihaimaruseac** [comment]
You should be able to use `--config` flags: https://cs.opensource.google/tensorflow/tensorflow/+/master:.bazelrc;l=368-369
