### ISSUE TITLE
Add Transformer Layers to tf.keras.layers

### ISSUE THREAD

**Issue by limapedro** [tensorflow/tensorflow#42848]
Nowadays most of NLP researchers/practitioners uses Transformers instead of LSTMs for NLP, it would make sense to add some of the layers used in the transformer architecture to the Keras API to avoid third-party libs or a lot of rewriting of code, The API could be similar to this tutorial: https://medium.com/tensorflow/a-transformer-chatbot-tutorial-with-tensorflow-2-0-88bf59e66fe2

So the layers being EncoderLayer, DecoderLayer, Encoder, Decoder, MultiHeadAttention(which is already in beta), PositionalEncoding, LookAheadMask,  ScaledDotProduct, FeedForward and Transformer.

Thanks in advance.

**Comment by qlzh727** [comment]
cc @tanzhenyu who works on Keras NLP.

**Comment by tanzhenyu** [comment]
1) We already have `tf.keras.layers.MultiHeadAttention`
2) We have PositionEmbedding in [keras_nlp](https://github.com/tensorflow/models/tree/master/official/nlp/keras_nlp)
3) We are not gonna have FeedForward given this can be easily done with Keras.
4) I am working on LookAheadMask
5) ScaledDotProduct and PositionalEncoding can be supported

Most importantly, please comment on keras_nlp [scoping doc](https://github.com/keras-team/governance/pull/22) if you're interested or wanted to contribute

**Comment by limapedro** [comment]
@tanzhenyu Thanks for the reply, I wasn't aware of the keras_nlp layer, but I'll look into it, thanks again.

**Comment by claverru** [comment]
@tanzhenyu Hello, your answer helped me too. I've been using [this](https://www.tensorflow.org/tutorials/text/transformer) implementation until now that we already have MultiHeadAttention in a stable version (I'm looking for something more robust).

However I have checked keras_nlp out and missed a DecoderBlock. Is there any plan on this? Also, seems like keras_nlp installation still requires tf-nightly even though MultiHeadAttention is stable.

I wonder why Pytorch team has already these implementations for like over a year and TF is still missing this key pieces.

**Comment by tanzhenyu** [comment]
> @tanzhenyu Hello, your answer helped me too. I've been using [this](https://www.tensorflow.org/tutorials/text/transformer) implementation until now that we already have MultiHeadAttention in a stable version (I'm looking for something more robust).
> 
> However I have checked keras_nlp out and missed a DecoderBlock. Is there any plan on this? Also, seems like keras_nlp installation still requires tf-nightly even though MultiHeadAttention is stable.
> 
> I wonder why Pytorch team has already these implementations for like over a year and TF is still missing this key pieces.

Yes DecoderBlock is still on the way. If you want to contribute, that'd be great as well!

**Comment by claverru** [comment]
> > @tanzhenyu Hello, your answer helped me too. I've been using [this](https://www.tensorflow.org/tutorials/text/transformer) implementation until now that we already have MultiHeadAttention in a stable version (I'm looking for something more robust).
> > However I have checked keras_nlp out and missed a DecoderBlock. Is there any plan on this? Also, seems like keras_nlp installation still requires tf-nightly even though MultiHeadAttention is stable.
> > I wonder why Pytorch team has already these implementations for like over a year and TF is still missing this key pieces.
> 
> Yes DecoderBlock is still on the way. If you want to contribute, that'd be great as well!

What about [this](https://github.com/tensorflow/models/blob/master/official/nlp/modeling/layers/transformer.py)?
