### ISSUE TITLE
org.tensorflow:tensorflow:jar:2.3.0 not found via Maven

### ISSUE THREAD

**Issue by trsudarshan** [tensorflow/tensorflow#42841]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OSX 10.15.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.15.0 (current), 2.3.0 (future)
- Python version: N/A
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
Unable to resolve `tensorflow` Java artifact via Maven at version 2.3.0, as per official [documentation](https://www.tensorflow.org/install/lang_java#tensorflow_with_apache_maven).

**Provide the exact sequence of commands / steps that you executed before running into the problem**
In my project's pom.xml file, modified `${tensorflow.version}` value in following snippet from 1.15.0 to 2.3.0 as per official [documentation](https://www.tensorflow.org/install/lang_java#tensorflow_with_apache_maven) and re-ran my project's build (which works with 1.15.0, as expected):

```
    <dependency>
      <groupId>org.tensorflow</groupId>
      <artifactId>tensorflow</artifactId>
      <version>${tensorflow.version}</version>
    </dependency>
```

**Any other info / logs**

```
Could not find artifact org.tensorflow:tensorflow:jar:2.3.0 in maven-central (https://repo1.maven.org/maven2)
```

**Comment by pluradj** [comment]
https://github.com/tensorflow/tensorflow/issues/32943#issuecomment-684061320

**Comment by frreiss** [comment]
To expand on @pluradj 's response, it appears that:
* The Java APIs of [tensorflow/tensorflow/java/](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java) are deprecated, unsupported, and incompatible with versions of TensorFlow later than 1.15.
* There is a replacement Java API being developed by the SIG-Java community, which is **not** the same team that maintains the main TensorFlow project. None of the main contributors work for Google. The replacement Java API is under https://github.com/tensorflow/java
* The replacement API has not yet had a stable release.
* Instructions for compiling Java programs directly against an unstable nightly build of the new Java API can be found at https://github.com/tensorflow/java#using-maven-artifacts
* The correct unstable version of the new Java API to use with TensorFlow 2.3.0 is `0.2.0-SNAPSHOT`
* The Java/Maven installation documentation at https://www.tensorflow.org/install/lang_java is completely wrong.
* The Java API documentation at https://www.tensorflow.org/api_docs/java is completely wrong.

@angerson is this correct?

**Comment by angerson** [comment]
To my limited knowledge, I believe you are correct. Thank you for your helpful summary.

@lamberta @martinwicke If this is intentionally true, we'll need to remove or update these misleading documentation pages. What's the right step forward for that?

**Comment by lamberta** [comment]
@MarkDaoust was working on some javadocs recently, ideas?

**Comment by trsudarshan** [comment]
@chunduriv thank you, that reference helps.
