### ISSUE TITLE
Is it possible to adjust available GPU during training?

### ISSUE THREAD

**Issue by pokerfaceSad** [tensorflow/tensorflow#42851]
Is it possible to adjust available GPU during training?

Think about this scenario, during traing, the user think one GPU card is too slow to training, and want to add another card to speed up the training. So Is it possible to adjust available GPU without breaking the training？

**Comment by gowthamkpr** [comment]
@pokerfaceSad NO you can't, but you can use [distributed training](https://www.tensorflow.org/guide/distributed_training) to train on multiple GPUs but you can't add a gpu in between the training.

**Comment by pokerfaceSad** [comment]
> @pokerfaceSad NO you can't, but you can use [distributed training](https://www.tensorflow.org/guide/distributed_training) to train on multiple GPUs but you can't add a gpu in between the training.

Thx for your reply.
