### ISSUE TITLE
imdb.load_data() is not returning meaningful sentences as I have given print like x_train[0], x_train[1] after loading the data!

### ISSUE THREAD

**Issue by tawsifsazid** [tensorflow/tensorflow#42859]
**code example for review** 

(x_train, y_train), (x_test, y_test) = imdb.load_data()
word_to_ix = imdb.get_word_index()

ix_to_word = dict( (value, key) for key, value in word_to_ix.items() )

for i in range(len(x_train[0])):
  print(ix_to_word[x_train[0][i]])

**Comment by Saduf2019** [comment]
@tawsifsazid 
Please fill in the issue template, if possible share colab gist with complete code and error faced.
