### ISSUE TITLE
How to start JupyterLab in a virtual environment

### ISSUE THREAD

**Issue by momohina** [tensorflow/tensorflow#42861]
Could you please tell me how to start JupyterLab in a virtual environment?

I use Windows 10 and have already installed Anaconda 64 bit.

I failed to install tensorflow in the base environment. Therefore, I created a virtual environment where tensorflow was  installed, by writing the following command on Anaconda prompt.
`conda create -n tf2 tensorflow python=3.7`

With this command, I created the virtual environment succesfully.

Then, I wrote the following command on the activated virtual environment:
`(tf2) conda install -c conda-forge jupyter lab`

Finally, I wrote this command:
`jupyter lab`

However, JupyterLab did not start.
Could you please teach me what I should do?

**Comment by amahendrakar** [comment]
@momohina,
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by momohina** [comment]
Thank you very much for advice!

I am going to ask the question on StackOverflow.
