### ISSUE TITLE
Inference only works if using same batch size as in training

### ISSUE THREAD

**Issue by ow4g18** [tensorflow/tensorflow#42864]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.14.6
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.7.2

**Describe the current behavior**
I have trained a model using the functional api and exported it to a saved_model.  I trained it using a batch_size of 32 but would like to do inference using only one sample (64ms of streaming audio).  For troubleshooting purposes I am evaluating a subset of the training data.  I read the serialised data into a tf.data.dataset for both training and inference, using the dataset.batch() method to set the batch size. Setting batch_size=1 gives the following result.

```
loss: 2.6619 - accuracy: 0.5155 - precision: 0.5155 - recall: 1.0000 - true_positives: 183.0000 - true_negatives: 0.0000e+00 - false_positives: 172.0000 - false_negatives: 0.0000e+00
```
This is a binary problem so the accuracy is only as good as random.

**Describe the expected behavior**
Setting the batch size to 32 (same as training) gives results consistent with the training metrics:
```
loss: 0.1208 - accuracy: 0.9549 - precision: 0.9665 - recall: 0.9454 - true_positives: 173.0000 - true_negatives: 166.0000 - false_positives: 6.0000 - false_negatives: 10.0000
```

I would expect the results to at least be similar to this when using a batch size of 1.  I have checked the input size at each layer of my model and the batch size dimension is unchanging.

**Standalone code to reproduce the issue**
I use the following code to generate the dataset 
```
def get_test_dataset(tfrecords,
                batch_size,
                input_size=1024,
                n_classes=1,
                shuffle=False,
                fake_input=False):
    """ Read and preprocess tfrecords into a tf.data.Dataset """

    def parse_func(example_proto):
        """ Parse tfrecords into tf.Feature, to be made into a dataset """

        feature_dict = {
            'signal/id': tf.io.FixedLenFeature([], tf.string),
            'segment/start': tf.io.FixedLenFeature([], tf.int64),
            'segment/end': tf.io.FixedLenFeature([], tf.int64),
            'subsegment/id': tf.io.FixedLenFeature([], tf.int64),
            'subsegment/length': tf.io.FixedLenFeature([], tf.int64),
            'subsegment/signal': tf.io.FixedLenFeature([input_size],
                                                       tf.float32),
            'subsegment/features': tf.io.FixedLenFeature(
                [FEAT_SIZE[0] * FEAT_SIZE[1]], tf.float32),
            'subsegment/label': tf.io.FixedLenFeature([], tf.int64)
        }

        parsed_feature = tf.io.parse_single_example(serialized=example_proto,
                                                    features=feature_dict)

        signal = parsed_feature['subsegment/signal']
        signal = tf.cast(signal, dtype=tf.float32)
        signal = tf.expand_dims(signal, 0)

        labels = parsed_feature['subsegment/label']
        labels = tf.expand_dims(labels, axis=-1)
        labels = tf.cast(labels, dtype=tf.float32)

        return signal, labels

    files = tf.data.Dataset.list_files(tfrecords)
    dataset = tf.data.TFRecordDataset(files)
    dataset = dataset.map(parse_func, num_parallel_calls=8)
    dataset = dataset.batch(batch_size)
    dataset = dataset.prefetch(buffer_size=256)

    return dataset

test_audio = get_test_dataset(tfrecords, batch_size)
```
and evaluate using:
```
print(model.evaluate(test_audio, batch_size))
```
Perhaps something is wrong in my model but since I have checked the dimensions at each stage I'm wondering whether it could be a bug.  Thanks!

**Comment by amahendrakar** [comment]
@ow4g18,
On running the given code, I am facing an error stating `NameError: name 'tfrecords' is not defined`.

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by ow4g18** [comment]
@amahendrakar Hi, I've created a repo at https://github.com/ow4g18/troubleshooting containing the python script, saved_model and tfrecord data.  batch_size is a variable in the code and running the script from the base directory will evaluate accordingly.  Hope this will do, thanks!

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/52eaa7f313f759e8e08cbdd2dfc0f815/42864.ipynb). Thanks!

**Comment by gowthamkpr** [comment]
@ow4g18 Please take a look at the input and output shapes of the model and see if the batch size is fixed or unknown?
