### ISSUE TITLE
Unable to convert h5model file to tflite file

### ISSUE THREAD

**Issue by SaiBalaji22** [tensorflow/tensorflow#42865]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 2.2.0

# Put link here or attach to the issue.

https://gist.github.com/SaiBalaji22/e3815c47970416c37328e9f69a43c958

**Failure details**

I have made a rps classifier using tensor flow python.The problem is i was able to convert it to h5 file.But while converting to tflite file it takes long time.So if I interrupt and restart the kernel it still gives me  error.

**Any other info / logs**

`UnavailableError                          Traceback (most recent call last)
<ipython-input-6-217c00d782f4> in <module>
      1 model = tf.keras.models.load_model('RPSKeras22.h5')
      2 converter = tf.lite.TFLiteConverter.from_keras_model(model)
----> 3 tflite_models = converter.convert()
      4 open("RPS22.tflite", "wb").write(tflite_model)

~\.conda\envs\tensorflow_env\lib\site-packages\tensorflow_core\lite\python\lite.py in convert(self)
    421 
    422     frozen_func = _convert_to_constants.convert_variables_to_constants_v2(
--> 423         self._funcs[0], lower_control_flow=False)
    424     input_tensors = [
    425         tensor for tensor in frozen_func.inputs

~\.conda\envs\tensorflow_env\lib\site-packages\tensorflow_core\python\framework\convert_to_constants.py in convert_variables_to_constants_v2(func, lower_control_flow)
    426   """
    427   # Inline the graph in order to remove functions when possible.
--> 428   graph_def = _run_inline_graph_optimization(func, lower_control_flow)
    429 
    430   # Gets list of all node defs include those in the library.

~\.conda\envs\tensorflow_env\lib\site-packages\tensorflow_core\python\framework\convert_to_constants.py in _run_inline_graph_optimization(func, lower_control_flow)
    125   rewrite_options.min_graph_nodes = -1  # do not skip small graphs
    126   rewrite_options.optimizers.append("function")
--> 127   return tf_optimizer.OptimizeGraph(config, meta_graph)
    128 
    129 

~\.conda\envs\tensorflow_env\lib\site-packages\tensorflow_core\python\grappler\tf_optimizer.py in OptimizeGraph(config_proto, metagraph, verbose, graph_id, cluster, strip_default_attributes)
     52                     type(config_proto))
     53   if cluster is None:
---> 54     cluster = gcluster.Cluster()
     55   ret_from_swig = tf_opt.TF_OptimizeGraph(cluster.tf_cluster,
     56                                           config_proto.SerializeToString(),

~\.conda\envs\tensorflow_env\lib\site-packages\tensorflow_core\python\grappler\cluster.py in __init__(self, allow_soft_placement, disable_detailed_stats, disable_timeline, devices)
     52     if devices is None:
     53       self._tf_cluster = tf_cluster.TF_NewCluster(allow_soft_placement,
---> 54                                                   disable_detailed_stats)
     55     else:
     56       devices_serialized = [device.SerializeToString() for device in devices]

UnavailableError: Can't provision more than one single cluster at a time`

**Comment by ravikyram** [comment]
@SaiBalaji22 

Can you add the below  lines of code before converting and see if the issue still persists.
```
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter=True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
```
You can refer similar issues #42857,,#35615, #35590 and see if it helps you. Thanks!

**Comment by SaiBalaji22** [comment]
I resolved it by reducing the number of neurons in last convolutional layer.Is this problem related to GPU.My machine has no seperate GPU

**Comment by ravikyram** [comment]
@SaiBalaji22 

Glad to know the issue was resolved. Please, close this thread as your issue was resolved. Thanks!
