### ISSUE TITLE
Keras model.predict on large datasets throws OOM

### ISSUE THREAD

**Issue by digital-thinking** [tensorflow/tensorflow#42862]
I am using ImageDataGenerator and a Keras model (tf.keras.applications.EfficientNetB5). While training I also use the ImageDataGenerator and everything works as expected. But if I use the predict function from the keras model on large data sets, it throws an OOM error, even if it worked in previous versions (e.g. 2.1).

The allocator also tries to allocate a weird shape, it seems like the GPU tries to allocate the memory for all the predictions in GPU memory and not into RAM. If I divide the data in chunks and process them in separate predict calls the error does not occur.

Plattform: Windows 10
GPU: RTX 2080 Ti (11GB)
Python Version: 3.7.7
CUDA Version: 11.0
Tensorflow version:  v2.3.0-rc2-23-gb36436b087 2.3.0

**Comment by ravikyram** [comment]
@digital-thinking 

Request you to share colab link or simple stand alone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by digital-thinking** [comment]
Sorry, I don't have a colab or stand alone code right now.

**Comment by gowthamkpr** [comment]
@digital-thinking Please provide standalone code for us to reproduce this issue. Thanks!
