### ISSUE TITLE
tf.keras.Model.compile unexpectedly recovered old optimizer iterations

### ISSUE THREAD

**Issue by edwardyehuang** [tensorflow/tensorflow#42877]
**System information**
- TensorFlow version (use command below):2.4 nightly
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11
- GPU model and memory: Titan RTX

After I set a new optimizer in tf.keras.Model.compile. The "iterations" become previous trained iterations

**Comment by edwardyehuang** [comment]
Currently I am using `model.optimizer.iterations.assign(0)` to fix this isuse after compiled

**Comment by amahendrakar** [comment]
@edwardyehuang,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!
