### ISSUE TITLE
Uninitialized memory access of per-channel params

### ISSUE THREAD

**Issue by felix-johnny** [tensorflow/tensorflow#42883]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): 5a16264ba6f12883726d12d484d4cd61405ddab7
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Host

**Describe the problem**
Function in question:  tflite::PopulateConvolutionQuantizationParams() in tensorflow/lite/kernels/kernel_util.cc (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/kernel_util.cc#L138)
Operators in question: conv and depthwise_conv

Pointer arguments 'per_channel_multiplier' and 'per_channel_shift' are accessed and written to in all cases. 
In the non-int<8,16> case, these arguments can be NULL pointers or uninitialized pointers. The reason it doesn't
crash now for reference kernels is because memory is allocated for per-channel quant parameters irrespective
of the quantization type. This ticket is for protecting accesses of per-channel params in PopulateConvolutionQuantizationParams().

Once that is done, memory usage for non per-channel cases can be reduced for TFLu(and TFL) as an improvement.

**Please provide the exact sequence of commands/steps when you ran into the problem**
_Simple Step:_
Simplest way is to run the unit test for conv or depthwise_conv and see that per-channel arguments are accessed and 
updated in the non-per channel case. 

./tensorflow/lite/micro/tools/make/gen/linux_x86_64/bin/kernel_depthwise_conv_test

_How it was discovered:_
Since it is now possible to dynamically allocate per-channel params in cmsis-nn/<op>.cc (Thanks to https://github.com/tensorflow/tensorflow/commit/59d177d9acabe8e70bc33e554a364d2620bc6999)
the conv.cc and depthwise_conv.cc in cmsis-nn folder was updated based on PR https://github.com/tensorflow/tensorflow/pull/42770 with some additional
correction to not allocate per-channel params for uint8 operators. This led to a crash.

**Comment by felix-johnny** [comment]
Affects PR https://github.com/tensorflow/tensorflow/pull/43486

**Comment by felix-johnny** [comment]
With changes coming in, I realize linking the line number for the function start wasn't a smart idea!
It is PopulateConvolutionQuantizationParams()

// Per-axis & per-tensor
TfLiteStatus PopulateConvolutionQuantizationParams(
    TfLiteContext* context, const TfLiteTensor* input,
    const TfLiteTensor* filter, const TfLiteTensor* bias, TfLiteTensor* output,
    const TfLiteFusedActivation& activation, int32_t* multiplier, int* shift,
    int32_t* output_activation_min, int32_t* output_activation_max,
    int32_t* per_channel_multiplier, int* per_channel_shift, int num_channels) {

**Comment by advaitjain** [comment]
Adding a permalink to the function:
https://github.com/tensorflow/tensorflow/blob/195369c5a0c63fb51f1deea1e05bd78e23e90cc2/tensorflow/lite/kernels/kernel_util.cc#L201-L217
