### ISSUE TITLE
undefined reference to `aws_mutex_init'

### ISSUE THREAD

**Issue by zhangqiang-hf** [tensorflow/tensorflow#42887]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Loongnix OS(based on Fedora) with kernel:Linux localhost.localdomain 3.10.84-22.fc21.loongson.7.mips64el
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:2.4.0
- Python version:Python：2.7.9 Python3：3.7.9
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):3.4.1
- GCC/Compiler version (if compiling from source):gcc version 7.3.1 20180303 (Red Hat 7.3.1-6) (GCC)
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
when I build the tensorflow 2.4.0 source code on loongson platform（arch：mips64）use bazel 3.4.1.， 
**use ld：ld.bfd,    not ld.gold**

**the build failed log is as below:**
ERROR: /home/loongson/tensorflow/tensorflow-206/tensorflow/tensorflow/compiler/tf2xla/cc/BUILD:30:21: Linking of rule '//tensorflow/compiler/tf2xla/cc:ops/xla_jit_ops_gen_cc' failed (Exit 1): gcc failed: error executing command
   (cd /home/loongson/.cache/bazel/_bazel_loongson/f0c20e6eab3cd4f95dcf1e27683765aa/execroot/org_tensorflow && \
   exec env - \
     LD_LIBRARY_PATH=/opt/protobuf-3.9.2/lib:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/devtoolset-7/root/usr/lib64/dyninst:/opt/rh/devtoolset-7/root/usr/lib/dyninst:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib \
     PATH=/opt/protobuf-3.9.2/bin:/opt/rh/devtoolset-7/root/usr/bin:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/loongson/.local/bin:/home/loongson/bin \
     PWD=/proc/self/cwd \
   /opt/rh/devtoolset-7/root/usr/bin/gcc @bazel-out/mips64-opt-exec-50AE0418/bin/tensorflow/compiler/tf2xla/cc/ops/xla_jit_ops_gen_cc-2.params)
 Execution platform: @local_execution_config_platform//:platform
 bazel-out/mips64-opt-exec-50AE0418/bin/_solib_mips64/_U_S_Stensorflow_Scompiler_Stf2xla_Scc_Cops_Sxla_Ujit_Uops_Ugen_Ucc___Utensorflow/libtensorflow_framework.so.2: undefined reference to `aws_mutex_init'
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Then, I set  .bazelrc file:     build:xla --define=with_xla_support=true to false**

**then the above failed log is disapear! !!**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by zhangqiang-hf** [comment]
**but the new build failed accured! build failed log as below:**
ERROR: /home/loongson/tensorflow/tensorflow-206/tensorflow/tensorflow/python/BUILD:2944:29: Linking of rule '//tensorflow/python:gen_data_flow_ops_py_wrappers_cc' failed (Exit 1): gcc failed: error executing command 
  (cd /home/loongson/.cache/bazel/_bazel_loongson/f0c20e6eab3cd4f95dcf1e27683765aa/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/opt/protobuf-3.9.2/lib:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/devtoolset-7/root/usr/lib64/dyninst:/opt/rh/devtoolset-7/root/usr/lib/dyninst:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib \
    PATH=/opt/protobuf-3.9.2/bin:/opt/rh/devtoolset-7/root/usr/bin:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/loongson/.local/bin:/home/loongson/bin \
    PWD=/proc/self/cwd \
  /opt/rh/devtoolset-7/root/usr/bin/gcc @bazel-out/mips64-opt-exec-50AE0418/bin/tensorflow/python/gen_data_flow_ops_py_wrappers_cc-2.params)
Execution platform: @local_execution_config_platform//:platform
bazel-out/mips64-opt-exec-50AE0418/bin/_solib_mips64/_U_S_Stensorflow_Spython_Cgen_Udata_Uflow_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.2: undefined reference to `aws_mutex_init'
bazel-out/mips64-opt-exec-50AE0418/bin/_solib_mips64/_U_S_Stensorflow_Spython_Cgen_Udata_Uflow_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.2: undefined reference to `aws_thread_launch'
bazel-out/mips64-opt-exec-50AE0418/bin/_solib_mips64/_U_S_Stensorflow_Spython_Cgen_Udata_Uflow_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.2: undefined reference to `Aws::Time::LocalTime(tm*, long)'
bazel-out/mips64-opt-exec-50AE0418/bin/_solib_mips64/_U_S_Stensorflow_Spython_Cgen_Udata_Uflow_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.2: undefined reference to `Aws::FileSystem::CreateTempFilePath()'
bazel-out/mips64-opt-exec-50AE0418/bin/_solib_mips64/_U_S_Stensorflow_Spython_Cgen_Udata_Uflow_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.2: undefined reference to `aws_debug_break'
bazel-out/mips64-opt-exec-50AE0418/bin/_solib_mips64/_U_S_Stensorflow_Spython_Cgen_Udata_Uflow_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.2: undefined reference to `aws_gmtime'
bazel-out/mips64-opt-exec-50AE0418/bin/_solib_mips64/_U_S_Stensorflow_Spython_Cgen_Udata_Uflow_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so.2: undefined reference to `aws_timegm'


**why? please help me  for this issue! Thanks very much!**

**Comment by zhangqiang-hf** [comment]
Is this issue because aws is diabled？I see  .bazelrc file:  build:noaws --define=no_aws_support=true.
How can I enable aws?

**Comment by zhangqiang-hf** [comment]
could anyone help me to resolve this build fail？ Thank you！

**Comment by gunan** [comment]
@mihaimaruseac @samikama may know

**Comment by gunan** [comment]
This is also for mips architecture. TF has no official support for this architecture.

**Comment by zhangqiang-hf** [comment]
I have resolved this issue！
Can I push code  for supporting mips platform ？

**Comment by mihaimaruseac** [comment]
The code to support mips landed. I think we can close this.

Please reopen if there's something else left to do

**Comment by chen-cvresearch** [comment]
> I have resolved this issue！ Can I push code for supporting mips platform ？

how you solve the issue, I am now building tensorflow on riscv64 platform, same Error I meet.
