### ISSUE TITLE
scaling issue by using multiworkerstrategy for CPU

### ISSUE THREAD

**Issue by rajeev921** [tensorflow/tensorflow#42888]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): NA
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): conda 
- TensorFlow version (use command below): 2.3.0
- Python version: 3.8
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I have written code that need to scale to multiple host having 20 cpu cores each. I have used multiworkerstrategy. We are basically focusing on distributed training on CPU "NOT ON GPU" in tensorflow 2.3. I am able to successfully run the code on the cluster in all the node. 

Now the problem -

I see scaling issue. I have run it on single host and 5 different host. I doesn't see any performance gain on increasing the number of host. The time it take for each epochs and whole training is same in 1 machine vs 2 , 4 or 5 machine. There is no performance gain.

Than I have left my code and used the example in tensorflow docs with the same setup.
https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras  
I see the same behavior, not scaling on the increasing host.

Could someone please help me that 
1. Is multiworkerstrategy doesnot support scaling for distributed CPU in the different hosts?

**Describe the expected behavior**

Expected behaviour is that by using multiworkerstrategy it will scale by increasing the no of hosts.
[workers.log](https://github.com/tensorflow/tensorflow/files/5161305/workers.log)

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Attaching the logs of the worker. Each worker having the same logs as explained above time consumed for using 5 host or 1 host is same. So attaching 1 logs.

**Comment by nikitamaia** [comment]
Hi @rajeev921, yes `MultiWorkerMirroredStrategy` can be used to scale training jobs across CPU only machines. If I understand correctly, when you trained the model from the Multi-worker training with Keras tutorial on one machine it took `14s/step` and then when you added more machines, it was still `14s/step` ? To help debug this performance issue, can you provide the exact code you used to train? I know you linked to the tutorial but would be great if you could provide the exact code you used in a colab, just to make I'm using the same batch size, steps_per_epoch, etc. I can run some tests on my end and want to make sure I'm running the exact same code you are.

Can you also provide the full logs? The logs you've provided only show the results of the training steps, but it would be useful to see what was output prior to the training epochs.

**Comment by rajeev921** [comment]
Hi @nikitamaia 

I am adding the same code from the link that , I have used.

def mnist_dataset(batch_size):
  (x_train, y_train), _ = tf.keras.datasets.mnist.load_data()
  # The `x` arrays are in uint8 and have values in the range [0, 255].
  # You need to convert them to float32 with values in the range [0, 1]
  x_train = x_train / np.float32(255)
  y_train = y_train.astype(np.int64)
  train_dataset = tf.data.Dataset.from_tensor_slices(
      (x_train, y_train)).shuffle(60000).repeat().batch(batch_size)
  return train_dataset

def build_and_compile_cnn_model():
  model = tf.keras.Sequential([
      tf.keras.Input(shape=(28, 28)),
      tf.keras.layers.Reshape(target_shape=(28, 28, 1)),
      tf.keras.layers.Conv2D(32, 3, activation='relu'),
      tf.keras.layers.Flatten(),
      tf.keras.layers.Dense(128, activation='relu'),
      tf.keras.layers.Dense(10)
  ])
  model.compile(
      loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
      optimizer=tf.keras.optimizers.SGD(learning_rate=0.001),
      metrics=['accuracy'])
  return model


os.environ['TF_CONFIG'] = json.dumps({
    'cluster': {
        'worker': ["localhost:12001", "localhost:12002", localhost:12003, localhost:12004]
    },
    'task': {'type': 'worker', 'index': 0}
})

 # I have used same tfconfig in all different machine only changing the index value to 0, 1 2 , 3
 
strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()

num_workers = 4
per_worker_batch_size = 64

# Here the batch size scales up by number of workers since 
# `tf.data.Dataset.batch` expects the global batch size. Previously, you used 64, 
# and now this becomes 128.
global_batch_size = per_worker_batch_size * num_workers
multi_worker_dataset = mnist_dataset(global_batch_size)

with strategy.scope():
  # Model building/compiling need to be within `strategy.scope()`.
  multi_worker_model = build_and_compile_cnn_model()

# Keras' `model.fit()` trains the model with specified number of epochs and
# number of steps per epoch. Note that the numbers here are for demonstration
# purposes only and may not sufficiently produce a model with good quality.

multi_worker_model.fit(multi_worker_dataset, epochs=3,

**Comment by rajeev921** [comment]
[workers.log](https://github.com/tensorflow/tensorflow/files/5165737/workers.log)
Hi @nikitamaia. 

Attaching a full log. As I mentioned logs are the same across all the 5 hosts( Epoch time, per step).

import os
import tensorflow as tf
import numpy as np
import json

def mnist_dataset(batch_size):
  (x_train, y_train), _ = tf.keras.datasets.mnist.load_data()
  x_train = x_train / np.float32(255)
  y_train = y_train.astype(np.int64)
  train_dataset = tf.data.Dataset.from_tensor_slices(
      (x_train, y_train)).shuffle(60000).repeat().batch(batch_size)
  return train_dataset

def build_and_compile_cnn_model():
  model = tf.keras.Sequential([
      tf.keras.Input(shape=(28, 28)),
      tf.keras.layers.Reshape(target_shape=(28, 28, 1)),
      tf.keras.layers.Conv2D(32, 3, activation='relu'),
      tf.keras.layers.Flatten(),
      tf.keras.layers.Dense(128, activation='relu'),
      tf.keras.layers.Dense(256, activation='relu'),
      tf.keras.layers.Dense(512, activation='relu'),
      tf.keras.layers.Dense(1024, activation='relu'),
      tf.keras.layers.Dense(2048, activation='relu'),
      tf.keras.layers.Dense(128, activation='relu'),
      tf.keras.layers.Dense(10)
  ])
  model.compile(
      loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
      optimizer=tf.keras.optimizers.SGD(learning_rate=0.001),
      metrics=['accuracy'])
  return model

with open('./tf_config', 'r') as fp:
    tf_config = json.load(fp)

strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()

num_workers = 5
per_worker_batch_size = 64

global_batch_size = per_worker_batch_size * num_workers
multi_worker_dataset = mnist_dataset(global_batch_size)

with strategy.scope():
  multi_worker_model = build_and_compile_cnn_model()

multi_worker_model.fit(multi_worker_dataset, epochs=150, steps_per_epoch=70)

'''
Json file content for tfconfig 
{
    "cluster": {
        "worker": [
            "host1:12000",
            "host2:12001",
            "host3:12002",
            "host4:12003",
            "host5:12004"
        ]
    },
    "task": {
        "type": "worker",
        "index": 0
    }

I have just changed index value to 0, 1, 2, 3, 4 in all the different host, rest is same.
'''

**Comment by rajeev921** [comment]
@nikitamaia 

Colab link - https://colab.research.google.com/drive/1cttMaBOJ7ZrveJH2Inek7jvIq0FLwye6#scrollTo=4h4bTT_FvuFH

[workers.log](https://github.com/tensorflow/tensorflow/files/5168227/workers.log)

I have attached the log of the mnist.

Please ignore the above comment logs. As that log is our private repo code. I cannot share private repo code. 
But from the logs have the same behaviour as mnist. No scaling.

**Comment by nikitamaia** [comment]
I can't access the Colab, can you share it with me?

**Comment by rajeev921** [comment]
@nikitamaia. 
Please check now.
 
https://colab.research.google.com/drive/1cttMaBOJ7ZrveJH2Inek7jvIq0FLwye6?usp=sharing

**Comment by nikitamaia** [comment]
I suspect the issue here is that you're scaling up the batch size by the number of workers, but you're always keeping your `steps_per_epoch` the same. In tf-nightly, you are not required to pass in `steps_per_epoch` to `model.fit`. Can you try running your code in tf-nightly? You'll want to remove the `.repeat()` operation from your dataset, and also remove the `steps_per_epoch` from `model.fit`. You should keep the `global_batch_size = batch_size * mirrored_strategy.num_replicas_in_sync`

When you do this, you should see that the number of steps per epoch will decrease as you add more machines. Ideally this will mean that each epoch will take less time, however, for a small model and dataset like MNIST you might not see much benefit because the overhead of synchronizing the gradients from the two machines might not be worth it since MNIST trains pretty quickly on a single machine anyway. 

I'm assuming the model and dataset from your private repo code is larger than MNSIT, so try running that code in tf-nightly as well without passing in `steps_per_epoch` and let me know what you see. I would suggest starting by scaling to two machines first and making sure there's a performance gain before adding another machine.

**Comment by rajeev921** [comment]
Hi @nikitamaia,

As you suggested I tried to run it on tf_nightly build.
I have tried removing  steps_per_epoch,  .repeat(), and keeping global_batch_size = batch_size * mirrored_strategy.num_replicas_in_sync.

I see the difference in behaviour in 1st Epoch it is running of 1/unknown number of steps per epoch. after that, all other epochs have 4 steps per epoch. And it is same for using 1 host to scaling up to 1 to 5 different hosts and also the runtime is the same.


For detail Please see the logs. I am attaching logs of 3 host only.
[workers_3.log](https://github.com/tensorflow/tensorflow/files/5178796/workers_3.log)

[workers_1.log](https://github.com/tensorflow/tensorflow/files/5178785/workers_1.log)
[workers_2.log](https://github.com/tensorflow/tensorflow/files/5178786/workers_2.log)

**Comment by rajeev921** [comment]
@nikitamaia 

Do you have any working examples that you have tested on nigtly_build that is scaling for multi cpus for multi hosts? 

If you have please share, So I can try and see what is wrong in my situation.

**Comment by rajeev921** [comment]
Hi @nikitamaia 

I thought to test the same setting on a bigger dataset. So did took a bigger dataset. apply local_batch_size of 512 then used
lobal_batch_size = local_batch_size * mirrored_strategy.num_replicas_in_sync

I removed .repeat and steps per epoch. and ran with a single host and 5 different hosts.
 
Outcome - 
1. with one host I see steps per epochs as 45 and Epochs time 470 avg and 10s/step. Please check log of worker_single_host.log

2. I have taken 5 different hosts and  I see multiple problems here.
    a.  I see the same 45 steps_per_epochs.
    b.  Time for Epochs and per step increased drastically and it is different in the different hosts (like in some 683 15s/step and in some 745 17 sec/step).
    c. I see the same time different hosts execting different steps and different epochs. So I have captured the initial logs.
    please wee worker 1 - 5 logs.

Please help, now I am going out of my mind, without having any clue.

[workers_single_host.log](https://github.com/tensorflow/tensorflow/files/5191144/workers_single_host.log)

[workers_1.log](https://github.com/tensorflow/tensorflow/files/5191139/workers_1.log)
[workers_2.log](https://github.com/tensorflow/tensorflow/files/5191140/workers_2.log)
[workers_3.log](https://github.com/tensorflow/tensorflow/files/5191141/workers_3.log)
[workers_4.log](https://github.com/tensorflow/tensorflow/files/5191142/workers_4.log)
[workers_5.log](https://github.com/tensorflow/tensorflow/files/5191143/workers_5.log)

**Comment by nikitamaia** [comment]
This is difficult to debug since I can't see the actual code you're running, so let's try something simple as a sanity check.
Please see this [gist](https://colab.research.google.com/drive/1uimh_CcczehHmRkONHohPnmeAUprHoZ2?usp=sharing) here for running multi worker training with MNIST

Run this code in nightly, first with one machine. Then with two. The only thing in the code you will need to change is the TF Config.

When I run that code with one machine, I see 469 steps per epoch
When I switch to two machines, I see 235 steps per epoch on each machine.

Please try this in tf-nightly and let me know what you see.

**Comment by rajeev921** [comment]
I have run the gist and it is scaling as you have suggested, I am getting the same result.
"""
When I run that code with one machine, I see 469 steps per epoch
When I switch to two machines, I see 235 steps per epoch on each machine.
"""
only this error I get before execting epochs on both the host.
2020-09-09 05:03:22.600791: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:591] In AUTO-mode, and switching to DATA-based sharding, instead of FILE-based sharding as we cannot find appropriate reader dataset op(s) to shard. Error: Found an unshardable source dataset: name: "TensorSliceDataset/_2"
op: "TensorSliceDataset"
input: "Placeholder/_0"
input: "Placeholder/_1"
attr {
  key: "Toutput_types"
  value {
    list {
      type: DT_FLOAT
      type: DT_INT64
    }
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: 28
        }
        dim {
          size: 28
        }
      }
      shape {
      }
    }
  }
}

====================
Now experiment on my code. 
I have custom layer defined like defined in the code.log.
[code.log](https://github.com/tensorflow/tensorflow/files/5195156/code.log)

This code is working fine till tf2.3 but raising an error on tf_nightly build

ValueError: The name "conv2d" is used 3 times in the model. All layer names should be unique.

So, I have replaced my custom keras layer with 

def get_uncompiled_model():
    logging.debug(f"Network specification")
    temp_layer = img_inputs
    for sym_mode, kernel_shape in process.layer_cfg.genKernShape():
	    logging.debug(f"Creating CNN layer. kernel_shape={kernel_shape}")
	    temp_layer = tf.keras.layers.Conv2D(
		filters=kernel_shape[-1],
		kernel_size=kernel_shape[0:2],
		padding='valid',
		kernel_initializer='random_normal',
		bias_initializer='zeros',
		activation='sigmoid'
	    )(temp_layer)

    deform = Model(inputs=img_inputs, outputs=temp_layer)
    return deform
 
Now I am able to run the code. 
for  1 host with a smaller  dataset (4 steps per epochs) and a bigger dataset (45 steps_per_epochs), it runs successfully. 

For 2 hosts with a smaller dataset(2 steps_per_epochs) and a bigger dataset(22 steps_per_epochs), it runs and then crashes with this error in logs - host_1.log and host_2.log.

[host_1.log](https://github.com/tensorflow/tensorflow/files/5195228/host_1.log)
[host_2.log](https://github.com/tensorflow/tensorflow/files/5195239/host_2.log)

**Comment by nikitamaia** [comment]
The `Error: Found an unshardable source dataset: name: "TensorSliceDataset/_2` can be ignored. It's slightly misleading but it's just a warning and not an error that will affect your code.

From the logs it looks like it's crashing on the validation step, as it appears to make it through the training step before the error message. You can try removing the validation step for now since the goal is first to make sure that the training code scales as you add more machines.

**Comment by rajeev921** [comment]
I also thought the same, I have removed validation data but still, it's failing the same way. no changes.

**Comment by rajeev921** [comment]
@nikitamaia 

Any update about how to solve the crashing issue ?

**Comment by nikitamaia** [comment]
Have you tried setting the `tf.data.experimental.AutoShardPolicy` to `DATA` ?

[From the docs](https://www.tensorflow.org/tutorials/distribute/input#tfdistributestrategyexperimental_distribute_dataset), the policy is by default `AUTO`:
`AUTO: This is the default option which means an attempt will be made to shard by FILE. The attempt to shard by FILE fails if a file-based dataset is not detected. tf.distribute will then fall back to sharding by DATA. Note that if the input dataset is file-based but the number of files is less than the number of workers, an error will be raised.`
If you have more machines than number of files, then this might be causing the problem.

For the conv2d problem, yes I think opening a new issue is probably best.

**Comment by rajeev921** [comment]
I have tried tf.data.experimental.AutoShardPolicy to DATA  and FILE but still it is failing with the same error. 

I am now using a bigger dataset running for 1 host with 45 steps_per_epochs. 
But fail for 2 hosts with 23 steps_per_epochs.

Below is the code I have used. I tried to remove prefetch also no change same error.

```
 train_ds = train_input_ds \
        .batch(BATCH_SIZE)  \
        .prefetch(tf.data.experimental.AUTOTUNE)

    options = tf.data.Options()
    options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.DATA
    train_ds = train_ds.with_options(options)

```

Attaching the error log.

[error.log](https://github.com/tensorflow/tensorflow/files/5213540/error.log)

**Comment by nikitamaia** [comment]
It's difficult to debug the issue here without being able to see a minimal version of the code that reproduces the error. If you can provide that I'd be happy to take a deeper look, but otherwise I think I'm out of ideas unfortunately.
As a side note, removing prefetch won't make a difference, as using a distribution strategy with the Keras API will automatically leverage prefetch under the hood anyway.

**Comment by rajeev921** [comment]
I see the behaviour of the code follows on nightly-build.

For 1 machine it is working as expected.
for multiple machine with using .repeat() and steps_per_epochs() it is working as expected.
After removing .repeat() and steps_per_epochs()  on multi machine, It is showing problem.
[Adjust_GPUs.txt](https://github.com/tensorflow/tensorflow/files/5292717/Adjust_GPUs.txt)

**Comment by nikitamaia** [comment]
What problem are you referring to when you remove `.repeat` and `steps_per_epoch`?

**Comment by ASHWIN2605** [comment]
@rajeev921 Did you find solution for the issue. If so, can you please share your final code. I am writing a similar code and any input will be really great.

Thanks,
Ashwin
