### ISSUE TITLE
Documentation is becoming too undecipherable for a meaningful practical work

### ISSUE THREAD

**Issue by summa-code** [tensorflow/tensorflow#42896]
The documentation is becoming too undecipherable for any practical applications using Tensorflow.

Look at this one, https://www.tensorflow.org/guide/data

How would anyone learn anything for a streaming data from Disk ? Not many how-tos for data that don't fit into memory. And that page.. just like a man-page for API. We end up wasting many man hours without good documentation.

**Comment by bhack** [comment]
Is this a duplicate of https://github.com/tensorflow/tensorflow/issues/32938?

**Comment by mihaimaruseac** [comment]
Can you send PRs to fix documentation? This is an evolving process, we try to get documentation that is as useful as possible to as many people as possible.
