### ISSUE TITLE
How to reduce the size of the tflite model below 200mb while converting h5 to tflite

### ISSUE THREAD

**Issue by SaiBalaji22** [tensorflow/tensorflow#42898]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 2.2.0

If possible, please share a link to Colab/Jupyter/any notebook.

https://gist.github.com/SaiBalaji22/e3815c47970416c37328e9f69a43c958

`

**Failure details**

I have made an image classifier model to classifiy rock,paper,scissor images.But the problem is i was able to convert it to tflite model but the size of the model exceeds 200mb.I want to use it in android studio.When i add the model it give me error.How can i reduce the tflite model size while conversion.
![image](https://user-images.githubusercontent.com/51410810/92009720-8ca08a80-ed66-11ea-8f3b-7a2affb455ba.png)

**Comment by bhack** [comment]
You could try post_training_quantiziation https://www.tensorflow.org/lite/performance/post_training_quantization

**Comment by ymodak** [comment]
Also see [weight quantization](https://www.tensorflow.org/model_optimization/guide/quantization/post_training#quantizing_weights)
Setting `OPTIMIZE_FOR_SIZE` flag can help reduce the model weights. Thanks!

**Comment by SaiBalaji22** [comment]
Thanks it worked but accuracy has been reduced.

**Comment by bhack** [comment]
For Better performance you could explore https://www.tensorflow.org/model_optimization/guide/quantization/training
