### ISSUE TITLE
Keras load_model breaks for hdf5 files on Google Cloud Storage bucket

### ISSUE THREAD

**Issue by andreasfragner** [tensorflow/tensorflow#42894]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 9 (TensorFlow:2.3 image on GCP) 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.7.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 11.0
- GPU model and memory: N/A

**Describe the current behavior**

Calling `tensorflow.keras.model.load_model` with hdf5 serialized models on GCS breaks
```
from tensorflow.keras.models import load_model

path = 'gs://mybucket/foo.hdf5'  # anonymized
load_model(path)
```
gives
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-7-33783c76cb4e> in <module>
      1 if config.model['build']['middle_ear'] is not None:
----> 2     config.model['build']['middle_ear'] = load_model(config.model['build']['middle_ear']['path'])

~/.venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py in load_model(filepath, custom_objects, compile, options)
    184     filepath = path_to_string(filepath)
    185     if isinstance(filepath, six.string_types):
--> 186       loader_impl.parse_saved_model(filepath)
    187       return saved_model_load.load(filepath, compile, options)
    188 

~/.venv/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py in parse_saved_model(export_dir)
    111                   (export_dir,
    112                    constants.SAVED_MODEL_FILENAME_PBTXT,
--> 113                    constants.SAVED_MODEL_FILENAME_PB, path_to_pbtxt, path_to_pb))
    114 
    115 

OSError: SavedModel file does not exist at: gs://mybucket/foo.hdf5/{saved_model.pbtxt|saved_model.pb}.
```
while loading the same file locally works fine
```
load_model('/tmp/081.hdf5')
<tensorflow.python.keras.engine.functional.Functional at 0x7f49f0276250>
```
I've tracked it down to the h5py check [here](https://github.com/tensorflow/tensorflow/blob/963e2693da908b0fa3d0174ac16c821d5bcc66fb/tensorflow/python/keras/saving/save.py#L182), which seems to always evaluate to false for `gs://` filepaths
```
>>> import h5py
>>> h5py.is_hdf5('gs://mybucket/foo.hdf5')
False
>>> h5py.is_hdf5('/tmp/foo.hdf5')
True
```
which is why it falsely ends up [here](https://github.com/tensorflow/tensorflow/blob/963e2693da908b0fa3d0174ac16c821d5bcc66fb/tensorflow/python/keras/saving/save.py#L188) in the case analysis.

**Describe the expected behavior**

hdf5 serialized models should be loadable from GCS buckets

**Comment by ymodak** [comment]
We already have a tracker for this issue. See https://github.com/tensorflow/tensorflow/issues/36453
Closing this issue since it's a duplicate. Thanks!
