### ISSUE TITLE
“No dashboards are active for the current dataset” despite the event file is created correctly

### ISSUE THREAD

**Issue by chriuxenman1** [tensorflow/tensorflow#42893]
**System information**
- OS Platform and Distribution: Win 10
- TensorFlow installed from (source or binary): conda
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.9
- tensorboard 2.2.1
- jupyter notebook 6.1.6
- same problem with spyder 4.1.4
- GPU model and memory: None

**Describe the current behavior**
I trained a CNN and created log files for tensorboard successfully. Now I want to optimize the model with tensorboard. For that I called "cmd" in Windows 10, activated the correct environment and typed:
`tensorboard --logdir=C:\Users\bauerch\Documents\Py_DL_Env\DL_Sentdex\logs`

When I go to http://localhost:6006/ in my browser I get the following result:
![grafik](https://user-images.githubusercontent.com/67313472/91977423-f39c5000-ed22-11ea-8696-0f6053a719de.png)

**As you can see at the bottom of the picture there is written "Data location: /tmp/MNIST_data". But I created the event file in the directory named above.**

What I tried so far without success:
- https://github.com/tensorflow/tensorboard/blob/master/README.md#my-tensorboard-isnt-showing-any-data-whats-wrong.
- https://stackoverflow.com/questions/47113472/tensorboard-error-no-dashboards-are-active-for-current-data-set
- https://github.com/tensorflow/tensorflow/issues/7856

**Describe the expected behavior**
TensorBoard should be opened without a problem via http://localhost:6006/

**Standalone code to reproduce the issue**

```
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D
import pickle
import numpy as np
from tensorflow.keras.callbacks import TensorBoard 
import time

# Tensorboard
NAME = "Cats-vs-dog-cnn-64x2-{}".format(int(time.time())) 
tensorboard = TensorBoard(log_dir="logs\\{}".format(NAME))

# Data import
X = pickle.load(open("X.pickle","rb")) 
y = pickle.load(open("y.pickle","rb"))

# Model
model = Sequential()
### 1.Layer
model.add(Conv2D(64, (3, 3), input_shape=X.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
### 2.Layer
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu')) 
model.add(MaxPooling2D(pool_size=(2, 2)))
### 3.Layer
model.add(Flatten()) 
model.add(Dense(64))
model.add(Activation('relu')) # Activation function muss man stets hinzufügen, da man sonst
# einen sinnlosen linearen Output aus den Neuronen bekommt
### 4.Output Layer
model.add(Dense(1))
model.add(Activation('sigmoid'))

# Compile
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Training
model.fit(X, y, batch_size=32, epochs=2, validation_split=0.3, callbacks=[tensorboard])
```

**Comment by ravikyram** [comment]
@chriuxenman1 

Can you please go through [link1](https://github.com/tensorflow/tensorboard/issues/1306), [link2](https://stackoverflow.com/questions/47113472/tensorboard-error-no-dashboards-are-active-for-current-data-set?rq=1) and see if it helps you.

This issue is more suitable for Tensorboard repo. Please post it on tensorboard  repo from [here.](https://github.com/tensorflow/tensorboard/issues/new/choose) Thanks!

**Comment by bhack** [comment]
Is your `log_dir` really `C:\Users\bauerch\Documents\Py_DL_Env\DL_Sentdex\logs`?

**Comment by chriuxenman1** [comment]
@ravikyram I tried both links already but it did not work. I will post it on the tensorboard repo, thank you.

@bhack Yes my `log_dir `is really `C:\Users\bauerch\Documents\Py_DL_Env\DL_Sentdex\logs`

**Comment by bhack** [comment]
@chriuxenman1 If you can see the logs in that folder have you tried double quoting this path when running the tensorboard?

**Comment by chriuxenman1** [comment]
@bhack How do I double quote?

**Comment by bhack** [comment]
Just to be sure:
cd {your_logdir}
dir (to verify that you have logs inside current dir" 
tensorboard --logdir ./
