### ISSUE TITLE
How preprocess image from tf.io.decode_raw ?

### ISSUE THREAD

**Issue by smallworld-network-wupeng** [tensorflow/tensorflow#42899]
I want to use tf.keras.preprocessing.image.random_rotation and other function to get more dataset , but these image from 
```
tf.io.decode_raw(features['image'], out_type=tf.uint8)
```
so it's tensor image , tf.keras.preprocessing.image.random_rotation must be numpy array ,anyone know how can I do?

**Comment by bhack** [comment]
I think that you can use something like https://colab.research.google.com/gist/jvishnuvardhan/4698ae014a3960ce271a700de419200a/39237-tf-nightly.ipynb
