### ISSUE TITLE
experimental_steps_per_execution option discarded when loading a model from checkpoint

### ISSUE THREAD

**Issue by aurelio-amerio** [tensorflow/tensorflow#42900]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Google Colab, TPU
- TensorFlow version: 2.3
- Python version: 3

**Describe the current behavior**
I have created and trained a model compiled with the `experimental_steps_per_execution` option. 
When I load the model through `tf.keras.models.load_model` to resume the training the option `experimental_steps_per_execution' is not taken in consideration and keras perform `on_step...` actions after every step and not after n steps as specified in `experimental_steps_per_execution` when the model was first compiled.

**Describe the expected behavior**
The model should load the `experimental_steps_per_execution' option or there should be an option to specify `experimental_steps_per_execution` when loading the model.

If necessary I can modify an MNIST example on Colab, but to reproduce this bug it is just needed to:

- create a model
- compile it with the `experimental_steps_per_execution` option enabled
- train it for a few epoch to verify the correct behaviour of `experimental_steps_per_execution`
- save the model
- load the model through `tf.keras.models.load_model`
- train the model for a few epoch to verify that `experimental_steps_per_execution` is being disregarded

**Other info / logs** 
One possible workaroud (which I am testing right now) is to set manually the steps per execution with `model._configure_steps_per_execution(experimental_steps_per_execution)` once it is loaded.

Thank you for your help!

**Comment by ravikyram** [comment]
@aurelio-amerio 

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by aurelio-amerio** [comment]
Here is a notebook to reproduce the issue as well as the "workaround" implemented:
https://colab.research.google.com/drive/1qeleit1tIzRY_1AmF0r_SQ4XtbaWoLNl?usp=sharing

Thank you

**Comment by bhack** [comment]
I think it is in the ignored properties https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training.py#L204

**Comment by ravikyram** [comment]
@aurelio-amerio 

I tried in colab with TF nightly version and i am not seeing any issue .Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/2d0207d4eba4b8ce09f8f00ce8462f91/untitled315.ipynb).

Also, The argument `steps_per_execution` is no longer experimental. Pass `steps_per_execution` instead of `experimental_steps_per_execution`.

Please, verify once and close the issue. Thanks!

**Comment by aurelio-amerio** [comment]
Thank you for your time, everything seems to be working properly in the nightly version, I'm looking forward to the 2.4 release!

@ravikyram Have a nice day!
