### ISSUE TITLE
Deprecated function setdiff1d still used in the tf source code

### ISSUE THREAD

**Issue by prasanthcakewalk** [tensorflow/tensorflow#42909]
**System information**
- I have written custom code
- Linux Ubuntu 20.04
- TensorFlow 2.3 installed using pip
- Python 3.8.2

**Current (unexpected) behavior**
Calculating the gradient of the `reduce_prod` function raises this warning.
> WARNING:tensorflow:From /home/prasanth/.local/pythonuserbase/lib/python3.8/site-packages/tensorflow/python/ops/math_grad.py:297: setdiff1d (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2018-11-30.
Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.sets.difference().

**Standalone code to reproduce the issue**
(The warning will only be displayed once in a session)
```
import tensorflow as tf

x = tf.ones(5)
with tf.GradientTape() as g:
    g.watch(x)
    y = tf.math.reduce_prod(x)

grad = g.gradient(y, x)
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/9d4cbcc58a6b57b56c107d0ea30419ca/42909-tf-nightly.ipynb). Thanks!

**Comment by prasanthcakewalk** [comment]
Note sure if this is the best approach, but modifying [/tensorflow/tensorflow/python/ops/math_grad.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/math_grad.py) as follows could fix it.

1. Add the following import statements:
    ```
    from tensorflow.python.ops import sparse_ops
    from tensorflow.python.ops import sets_impl
    ```
2. In the definition of `_ProdGrad(op, grad)`, replace
    ```
      other, _ = array_ops.setdiff1d(idx, reduced)
    ```
    with
    ```
      other = sparse_ops.sparse_tensor_to_dense(sets_impl.set_difference([idx], [reduced]))[0]
    ```

**Comment by yongtang** [comment]
The issue could be fixed by using the internal non-deprecated version of `gen_array_ops.list_diff` (instead of the deprecated `setdiff1d` API endpoint). Created a PR #42935 for the fix.
