### ISSUE TITLE
Please release TFLite wheels for Beaglebone

### ISSUE THREAD

**Issue by rgov** [tensorflow/tensorflow#42906]
The [prebuilt wheels](https://www.tensorflow.org/lite/guide/python) of the Tensorflow Lite interpreter for armv7l do not run on the [Beaglebone](https://beagleboard.org/black/), triggering an "invalid instruction" error. They seem to have been built for the Raspberry Pi using the `-mfpu=neon-vfpv4` build option which is appropriate for that hardware, but not all armv7l devices.

Pull request #28724 added a `bbb` make target which produces a usable library on the Beaglebone, but when building the wheel, the code still assumes `rpi`:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/pip_package/build_pip_package.sh#L42-L45
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/pip_package/build_pip_package.sh#L85-L87
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/pip_package/setup.py#L54-L56

Since it is rather complicated to build, it would be great if official releases could be made. And in the interim, it would be helpful to note on the releases page what hardware features the builds require, to avoid confusion and frustration over incompatible wheels.

**Comment by terryheo** [comment]
I don't have a Beaglebone device.
Could you share the result of the following command?
 ```
$ cat /proc/cpuinfo 
```

**Comment by rgov** [comment]
This is from a Beaglebone Blue. I think it is the same CPU as the Beaglebone Black. Note that `vfpv4` is not supported by the processor.

```
root@arm:~# cat /proc/cpuinfo
processor	: 0
model name	: ARMv7 Processor rev 2 (v7l)
BogoMIPS	: 597.19
Features	: half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpd32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x3
CPU part	: 0xc08
CPU revision	: 2

Hardware	: Generic AM33XX (Flattened Device Tree)
Revision	: 0000
Serial		: 0000000000000000
```

**Comment by bobharris** [comment]
I am trying to track this down as well. 

I'd like to get the associated wheels.
https://www.tensorflow.org/lite/guide/python
build for Beagle Bone Black. 

Illegal Instruction upon invoking models which invoke fine on an RPI. 

I've solved this before with the C intepreter. However I'd like to use Python this time.

**Comment by rgov** [comment]
Use the `bbb` target where available. The lines I linked to in the top post are where you need to hack the code to use `bbb` where it says `rpi`. Good luck.

**Comment by linuxmaster0312** [comment]
Does anyone have a tflite wheel that they already compiled for the beaglebone black?

**Comment by linuxmaster0312** [comment]
Nevermind, I compiled using @bobharris instructions and got it working. [Here is the wheel](https://drive.google.com/file/d/1Pjf_ML35IzesaGlnz4lANW_bu37nQXYU/view?usp=sharing)

**Comment by ZIFENG278** [comment]
hopefully someone who have been successfully build the python wheel for bbb can share the wheel here, thank

**Comment by mzakharo** [comment]
You can find my wheel here: [tflite_runtime-2.16.0-cp39-cp39-linux_armv7l.whl](https://github.com/mzakharo/birdnetapp/blob/main/beaglebone/tflite_runtime-2.16.0-cp39-cp39-linux_armv7l.whl).  Build instructions: [here](https://www.tensorflow.org/lite/guide/build_cmake_pip).

**Comment by yavrohatgi** [comment]
Just a big shoutout to [bobharris](https://github.com/bobharris) for saving my project and getting it to run on BBB.
