### ISSUE TITLE
Tensor slice is too large to serialize

### ISSUE THREAD

**Issue by jinhou** [tensorflow/tensorflow#4291]
Hi,
I met a issue said that "**Tensor slice is too large to serialize** (conservative estimate: 2268204567 bytes)". And i am wondered that why there is a limitation to prevents the TensorSliceWriter from attempting to serialize variables that are larger than 2GB. How can I to skip this limitation if I want to use a variable large than 2GB? 

Thanks
Jinlong

**Comment by aselle** [comment]
There is a hard limit of 2GB for serializing individual tensors because of the 32bit signed size in protobuf.

See #3766, #2648, etc.
http://stackoverflow.com/questions/34128872/google-protobuf-maximum-size

You need to find a way to break things up into smaller tensors/variables.

**Comment by jinhou** [comment]
@aselle Thanks for your quick response. Are you planning to provide some operations to break big tensors/variables into smaller ones, since it is very easy to exceed 2 GB limitation for some big models.

**Comment by aselle** [comment]
@concretevitamin can comment further if need be, but the plan is to make tensors be  checkpointed in a format that does not use protobufs, sidestepping this limitation.

**Comment by concretevitamin** [comment]
Agreed with @aselle.  @jinhou, a quick workaround is to use, for variables, `tf.get_variable(..., partitioner=..)`, and for non-ref tensors, `tf.split()`.

**Comment by formidable255** [comment]
@concretevitamin Are you able to provide an example on how to use tf.split(). Currently my code is something like:
`dataset = tf.data.Dataset.from_tensor_slices((x,y)).map(parse)`
`dataset = dataset.shuffle(buffer_size).repeat().batch(batch_size)`
`return dataset.make_one_shot_iterator().get_next()`

**Comment by paulzhangh** [comment]
finally, how to solve that problem?
