### ISSUE TITLE
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, EXPAND_DIMS, FILL, FLOOR, GATHER, GATHER_ND, LEAKY_RELU, MAXIMUM, MEAN, MINIMUM, MUL, PACK, PAD, RANGE, RESHAPE, RESIZE_BILINEAR, RESIZE_NEAREST_NEIGHBOR, SHAPE, STRIDED_SLICE, SUB, TRANSPOSE_CONV, UNPACK. Here is a list of operators for which you will need custom implementations: MaxPoolWithArgmax, Size.

### ISSUE THREAD

**Issue by rajaihimdiat** [tensorflow/tensorflow#42912]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CAST, CONCATENATION, CONV_2D, DIV, EXPAND_DIMS, FILL, FLOOR, GATHER, GATHER_ND, LEAKY_RELU, MAXIMUM, MEAN, MINIMUM, MUL, PACK, PAD, RANGE, RESHAPE, RESIZE_BILINEAR, RESIZE_NEAREST_NEIGHBOR, SHAPE, STRIDED_SLICE, SUB, TRANSPOSE_CONV, UNPACK. Here is a list of operators for which you will need custom implementations: MaxPoolWithArgmax, Size.

```
# Copy and paste here
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by abattery** [comment]
You can convert your model with Select TF operator set. Please take a look:
https://www.tensorflow.org/lite/guide/ops_select
https://www.tensorflow.org/lite/guide/reduce_binary_size

**Comment by Saduf2019** [comment]
@rajaihimdiat 
Please update the issue template with all details tf version, sample code or colab gist with issue reported.
Please refer to above comment as update.
