### ISSUE TITLE
tf.string_split() cannot speedup with num_parallel_calls increased in Dataset.map()

### ISSUE THREAD

**Issue by wstian** [tensorflow/tensorflow#42917]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):   ``Ubuntu 18.04.4 LTS``
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): ``tensorflow 1.14, tensorflow 1.15, tensorflow 2.3``
- Python version:  ``3.6.9``
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:
use the official docker image: ``tensorflow 1.14.0 cpu``, ``tensorflow 2.3.0 cpu``

testing code:
```
import time, sys
import tensorflow as tf
import numpy as np
def benchmark(dataset, num_epochs=1):
    for epoch_num in range(num_epochs):
        _iter = tf.compat.v1.data.make_initializable_iterator(dataset)
        _next = _iter.get_next()
        with tf.compat.v1.Session() as sess:
            sess.run(_iter.initializer)
            start_time = time.time()
            for i in range(1000):
                sess.run(_next)
            seconds = time.time() - start_time
    return seconds

def mapped_function(s):
    return tf.compat.v1.string_split([s], sep=',').values

num_calls = int(sys.argv[1])
csv_datas = [ ','.join(['1' for i in range(8000)]) ] * 1000
ds = tf.data.Dataset.from_tensor_slices(np.array(csv_datas))
ds = ds.map(mapped_function, num_parallel_calls=num_calls).prefetch(10)
print(benchmark(ds))
```

**Describe the current behavior**
run this code on a machine with 56 cores, cost 

*  tf1.14:  ``1.748 ``seconds, which means each ``tf.string_split()`` cost around ``1.7`` ms
*  tf2.3:   ``1.428 ``seconds, which means each ``tf.string_split()`` cost around ``1.4`` ms
*  tf2.3(eager mode):  
     * ``0.34`` seconds when num_calls=1
     * ``0.17`` seconds when num_calls=2 
     * ``0.17`` seconds when num_calls > 2 (cannot decreased any more)

the cost seconds not descrease, when ``num_calls`` increased. 

I also tried ``tf.config.threading.set_inter_op_parallelism_threads()``, not work

**Describe the expected behavior**
cost seconds should descreased when num_calls increased

benchmark for tf2 eager mode :
```
def benchmark2(dataset, num_epochs=1):
    start_time = time.time()
    for epoch in range(num_epochs):
        for ele in dataset:
            pass
    seconds = time.time() - start_time
    return seconds
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue, please find the gist below

- [TF v1.15](https://colab.research.google.com/gist/amahendrakar/95fe5973b2f7a13ba35aa6daeb54510e/42917-1-15.ipynb) - 1.3446729183197021s,
- [TF v2.3 graph mode](https://colab.research.google.com/gist/amahendrakar/9de9ac235ea8dfa4c9e2606e1aff7b42/42917-2-3-graph.ipynb) - 1.4894318580627441s and 
- [TF v2.3 eager mode](https://colab.research.google.com/gist/amahendrakar/cf3ba9f43b49515ad680ba1b2b3c57eb/42917-2-3-eager.ipynb)
  - when n=1 0.5180261135101318
  - when n=2 0.40242767333984375
  - when n=3 0.37236595153808594
  - when n=4 0.3709437847137451 

Thanks!

**Comment by bhack** [comment]
@amahendrakar I think that it is hard to declare that you can reproduce this over colab gist cause:
```
import multiprocessing
multiprocessing.cpu_count()
```
Gives 2 cores.

Also you need to recover the `map` overhead on a small function. You could try wtih vectorized mapping: 
https://www.tensorflow.org/guide/data_performance#vectorizing_mapping

You can also try to experiment with `tf.data.experimental.AUTOTUNE` instead of hardcoding many values (e.g. prefetching, num_calls etc..)

**Comment by wstian** [comment]
try with ``AUTOTUNE``,  it doesn't improve anything, no change.

try with  ``batch before map``, the total time doesn't decrease. The code as below: 
```
def mapped_function(s):
    return tf.compat.v1.string_split(s, sep=',').values
num_calls = int(sys.argv[1])
if num_calls <= 0:
    num_calls = tf.data.experimental.AUTOTUNE
batch_size = int(sys.argv[2])
ds = tf.data.Dataset.from_tensor_slices(np.array(csv_datas))
ds = ds.batch(batch_size).map(mapped_function, num_parallel_calls=num_calls).prefetch(10)
print(benchmark(ds))
```
benchmark result as below：

* bs=1:  ``total ms: 1657.7699184417725,  each ms: 1.6577699184417725, iterations=1000``
* bs=2:  ``total ms: 1671.933889389038,  each ms: 3.343867778778076, iterations=500``
* bs=4:  ``total ms: 1770.486831665039,  each ms: 7.081947326660156,  iterations=250``

all above tests, tried on both tf1.14 and tf2.3(disable eager).

on tf2.3(eager), ``batch before map``, will have some improvement,  but AUTOTUNE  don't. 

* bs=1:  ``total ms: 189.85533714294434, each ms: 0.18985533714294434, iterations: 1000``
* bs=2:  ``total ms: 177.9470443725586, each ms: 0.3558940887451172, iterations: 500``
* bs=3:  ``total ms: 167.3729419708252, each ms: 0.6694917678833008, iterations: 250``
* bs=4:   ``total ms: 151.60536766052246, each ms: 1.2128429412841797, iterations: 125``

**Comment by nikitamaia** [comment]
Hi @wstian 

I'm running the TF 2.3 code you've provided on a machine with 8 cores. Here's what I see:

batch size 3:
num_calls = 1, cost: 0.20
num_calls = 2, cost: 0.11
num_calls = 3, cost: 0.09
So the cost does go down as you increase the num_calls. Increasing the num_calls beyond 3 doesn't make a difference but I don't think that's surprising that the returns should level off at some point, especially given the small batch size.

I am also curious as to why you're not seeing an improvement when using `AUTOTUNE`
I ran two simple experiments:

batch size 32:
num_calls = None, cost: 0.22
num_calls = AUTOTUNE, cost: 0.12

batch size 8:
num_calls = None, cost: 0.20
num_calls = AUTOTUNE, cost: 0.10

So I'm seeing that when you use `AUTOTUNE`, it does decrease the time. 

Perhaps I am misunderstanding the question here. Can you run your benchmark code and compare num_calls = None and num_calls = AUTOTUNE and confirm that you do see a decrease in time?

**Comment by wstian** [comment]
> Hi @wstian
> 
> I'm running the TF 2.3 code you've provided on a machine with 8 cores. Here's what I see:
> 
> batch size 3:
> num_calls = 1, cost: 0.20
> num_calls = 2, cost: 0.11
> num_calls = 3, cost: 0.09
> So the cost does go down as you increase the num_calls. Increasing the num_calls beyond 3 doesn't make a difference but I don't think that's surprising that the returns should level off at some point, especially given the small batch size.
> 
> I am also curious as to why you're not seeing an improvement when using `AUTOTUNE`
> I ran two simple experiments:
> 
> batch size 32:
> num_calls = None, cost: 0.22
> num_calls = AUTOTUNE, cost: 0.12
> 
> batch size 8:
> num_calls = None, cost: 0.20
> num_calls = AUTOTUNE, cost: 0.10
> 
> So I'm seeing that when you use `AUTOTUNE`, it does decrease the time.
> 
> Perhaps I am misunderstanding the question here. Can you run your benchmark code and compare num_calls = None and num_calls = AUTOTUNE and confirm that you do see a decrease in time?

num_calls = ``AUTOTUNE`` can decrease but no more than 50%, which is the question.
why the time cannot be decreased with num_calls linearly?

by the way,  as I understood, ``AUTOTUNE`` is a chosen value, which will be constant when the ``map`` work constant, so it should not be better than a manual config value.

From the source code, ``num_calls`` is the concurrent number of map fn calls, put into the ``queue``, isn't the number of threads. So I suspect there maybe some problem with the working threads.

**Comment by nikitamaia** [comment]
In general the speedup scales with the number of threads, but there are lots of factors which can complicate things. To identify the root issue in your case, can you use the [TF Profiler](https://www.tensorflow.org/guide/profiler) to provide a profile of the dataset execution?
