### ISSUE TITLE
bug when using "num_parallel_calls" when mapping dataset to tfa function

### ISSUE THREAD

**Issue by FalsoMoralista** [tensorflow/tensorflow#42911]
As mentioned over the issue [here](https://github.com/tensorflow/addons/issues/2139) and advised from other contributors, i'm creating this issue cause using "num_parallel_calls=tf.data.experimental.AUTOTUNE" inside the .map call from my dataset, appeared to generate a deadlock.

I've tested with tensorflow versions 2.2 and 2.3, and tensorflow addons 0.11.1 and 0.10.0
On Google Colab Pro gpu env, python3.8

Link to example TFRecord: https://drive.google.com/drive/folders/1dc6ehBGL_mwGTuSy71VhUYVp0eMdHADP?usp=sharing

### Code to Reproduce the issue:
```python
test_dataset = tf.data.TFRecordDataset(num_parallel_reads=tf.data.experimental.AUTOTUNE,filenames=DRIVE_DIR+'/tf_issue/test_0.tfrecord').map(parsing_fn,num_parallel_calls=tf.data.experimental.AUTOTUNE)
test_dataset = test_dataset.map(translate,num_parallel_calls=tf.data.experimental.AUTOTUNE).prefetch(tf.data.experimental.AUTOTUNE) 
test_dataset = test_dataset.unbatch()
iterator = tf.compat.v1.data.make_one_shot_iterator(test_dataset)
for i in range(5):
  image,label = iterator.get_next()
```
###  Auxiliary functions
```python

def parsing_fn(serialized):
    features = \
        {
            'image': tf.io.FixedLenFeature([], tf.string),
            'label': tf.io.FixedLenFeature([], tf.int64)            
        }
    parsed_example = tf.io.parse_single_example(serialized=serialized,
                                             features=features)
    image_raw = parsed_example['image']
    image = tf.io.decode_jpeg(image_raw)    
    image = tf.image.resize(image,size=[224,224])    
    label = parsed_example['label']    
    return image, label

translate = lambda image,label: tf.py_function(func=translate_pipeline,inp=[image,label],Tout=[tf.float32,tf.int64])
def translate_pipeline(original_image,label):
  print(1)
  height = tf.shape(original_image)[0].numpy()    
  width = tf.shape(original_image)[1].numpy()
  y_fraction  = tf.convert_to_tensor(height * 0.2, dtype=tf.float32)
  x_fraction = tf.convert_to_tensor(width * 0.2,dtype=tf.float32)
  print(2)
  batched_image = tf.tile(tf.expand_dims(original_image,axis=0),[4,1,1,1]) # Create 4 copied versions from the original image and add to a batch
  translated_images = tfa.image.translate_ops.translate(images=batched_image,translations=[[x_fraction,-y_fraction],[-x_fraction,y_fraction],[-x_fraction,-y_fraction],[x_fraction,y_fraction]])
  augmented_images = tf.concat([tf.expand_dims(original_image,axis=0),translated_images],axis=0)
  print(3)
  label = tf.reshape(label,[1,1])
  labels = tf.tile(label,[5,1])
  print(4)
  return augmented_images, labels

```
### Output
>1
>1
>2
>2

**Comment by ravikyram** [comment]
@FalsoMoralista 

I am seeing the error message as below.
`NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow_addons/custom_ops/image/_image_ops.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl11string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS8_EE`.

Request you to share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps in localizing the issue faster. Thanks!

**Comment by bhack** [comment]
@ravikyram Have you tried to `pip install --upgrade tensorflow-addons` in your colab gist?

**Comment by ravikyram** [comment]
@bhack 

Sorry, i did not notice that i have not installed TF addons. Thanks for your help

@FalsoMoralista 
I tried in colab with TF version 2.3 and i am seeing below output. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/6d18dd03ea18e3b123d76dce75bc1793/untitled308.ipynb). Thanks!
```
1
2
1
2
```

**Comment by bhack** [comment]
@ravikyram It was installed by default in colab cause if not you fail on import. 

The problem was that It Is not updated.

**Comment by bhack** [comment]
@ravikyram If you scope is just the reproducibility you can claim that it is reproducible and pass to the next level of the triaging protocol. As you can see It never print `3` and `4` in the `translate_pipeline`

**Comment by bhack** [comment]
@ravikyram I think you need to add a label for the bit.

**Comment by jsimsa** [comment]
How many cores are there on the machine?

Can you recreate the issue when setting `num_parallel_calls` to the number of cores instead of `AUTOTUNE`? 

Does the issue go away when you [configure](https://www.tensorflow.org/api_docs/python/tf/config/threading/set_inter_op_parallelism_threads) the inter-op parallelism threads to be greater than the number of available cores?

I suspect that what's going on is that your machine has a small number of cores which is used as the default number of the inter-op thread threads and executing `tf.data.Dataset.map` call will need two threads in the inter-op threadpool -- one of the tf.data map function and one for the py_func. If there is only one thread left, this will deadlock.

Setting the inter-op parallelism threads to a higher value should work around this problem. There is not much else that can be done to avoid this problem, short of reimplement chunks of TF runtime and py_func support, which is out of the scope of the tf.data team's charter.

**Comment by FalsoMoralista** [comment]
> How many cores are there on the machine?
> 
> Can you recreate the issue when setting `num_parallel_calls` to the number of cores instead of `AUTOTUNE`?
> 
> Does the issue go away when you [configure](https://www.tensorflow.org/api_docs/python/tf/config/threading/set_inter_op_parallelism_threads) the inter-op parallelism threads to be greater than the number of available cores?
> 
> I suspect that what's going on is that your machine has a small number of cores which is used as the default number of the inter-op thread threads and executing `tf.data.Dataset.map` call will need two threads in the inter-op threadpool -- one of the tf.data map function and one for the py_func. If there is only one thread left, this will deadlock.
> 
> Setting the inter-op parallelism threads to a higher value should work around this problem. There is not much else that can be done to avoid this problem, short of reimplement chunks of TF runtime and py_func support, which is out of the scope of the tf.data team's charter.

```
lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) CPU @ 2.00GHz
Stepping:            3
CPU MHz:             2000.180
BogoMIPS:            4000.36
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            39424K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat md_clear arch_capabilities ```

**Comment by bhack** [comment]
@jsimsa It is not the `AUTOTUNE` cause it deadlocks also with `multiprocessing.cpu_count()` 

The deadlock  is in the inter-op parallelism resources pool cause I've unlocked it with
```
tf.config.threading.set_inter_op_parallelism_threads(
    multiprocessing.cpu_count()+1
)
```

**Comment by bhack** [comment]
@jsimsa I don't know if a solution similar to https://github.com/tensorflow/tensorflow/commit/f5fcd1fdcf896f46aed03c7e61525b48b75d1acc could be valid

**Comment by sachinprasadhs** [comment]
Was able to run your code in Tf Nightly 2.6, please confirm if your issue is fixed by checking the result in the gist [here](https://colab.research.google.com/gist/sachinprasadhs/2e6ef952359db914c2841bffbecd6bbb/42911.ipynb).

**Comment by FalsoMoralista** [comment]
> Was able to run your code in Tf Nightly 2.6, please confirm if your issue is fixed by checking the result in the gist [here](https://colab.research.google.com/gist/sachinprasadhs/2e6ef952359db914c2841bffbecd6bbb/42911.ipynb).

Fixed, thank you!
