### ISSUE TITLE
TensorFlow Lite Micro: Make it possible to specify optimization level when building with the Makefile

### ISSUE THREAD

**Issue by jenselofsson** [tensorflow/tensorflow#42924]
@tensorflow/micro

It would be useful to be able to manually set the optimization levels for different BUILD_TYPE:s from the make-command.

My idea is that the default optimization flags should be as it is now, none for BUILD_TYPE=debug, -O3 for BUILD_TYPE=release. If the user want to use different optimization levels, that should be configurable.

My proposed fix for this is to change tensorflow/lite/micro/tools/make/Makefile as can be seen in [makefile.txt](https://github.com/tensorflow/tensorflow/files/5168744/makefile.txt) , if it looks OK I can submit a pull request.

**Comment by advaitjain** [comment]
Making the optimization levels configurable from the command line sounds good to me.

We are not particular about the optimization level for the debug build so if it works for you I would suggest making it common for all builds to reduce the number of options and make it easier to switch between debug and non-debug builds with the same optimization level.

Something like
```
OPTIMIZATION_LEVEL := -O3
CXXFLAGS := -std=c++11 -Wstrict-aliasing -DTF_LITE_STATIC_MEMORY $(CC_WARNINGS) $(OPTIMIZATION_LEVEL)
CCFLAGS := -DTF_LITE_STATIC_MEMORY $(CC_WARNINGS) $(OPTIMIZATION_LEVEL)
```

A pull request for this would be welcome.

**Comment by jenselofsson** [comment]
A common optimization level works for us, I'll submit a pull request right away.
