### ISSUE TITLE
libhexagon_nn_skel.so: error adding symbols

### ISSUE THREAD

**Issue by orangesomethingorange** [tensorflow/tensorflow#42929]
**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- Mobile device: Samsung Galaxy S10
- TensorFlow version: 2.3
- Installed using: virtualenv, pip
- Bazel version: 3.1.0

**Describe the problem**

I'm trying to add the Hexagon Delegate to a Native (C++) Android app in Android Studio, but build fails with error:
`libhexagon_nn_skel.so: error adding symbols: File in wrong format`

**Provide the exact sequence of commands / steps that you executed before running into the problem**

- Created `libtensorflowlite_hexagon_jni.so` and `libhexagon_interface.so` from Tensorflow Docker container using: `bazel build -c opt --config=android_arm64 [HEXAGON_TARGET_PATH]` (the hexagon repo header included [this link](https://storage.googleapis.com/mirror.tensorflow.org/storage.cloud.google.com/download.tensorflow.org/tflite/hexagon_nn_headers_v1.20.0.0.tgz) to `v1.20.0.0.tgz` so I used `v1.20` interface)
- Created `libhexagon_nn_skel.so`, `libhexagon_nn_skel_v65.so` and `libhexagon_nn_skel_v66.so` from the [v1.20](https://storage.cloud.google.com/download.tensorflow.org/tflite/hexagon_nn_skel_v1.20.0.0.run) link
- Put all shared libraries into the proper ABI folder (`arm64-v8a`) in a JNI folder in the Android Studio project
- Configured `CMakeLists.txt` to include all shared libraries like so:

```
add_library(tflite-hexagon-lib SHARED IMPORTED)
set_target_properties(tflite-hexagon-lib PROPERTIES IMPORTED_LOCATION
        ${JNI_DIR}/${ANDROID_ABI}/libtensorflowlite_hexagon_jni.so)
include_directories(
        ${JNI_LIBS_DIR}/${ANDROID_ABI}/tensorflow/lite/delegates/hexagon)

# The same for libhexagon_interface.so

# The same for libhexagon_nn_skel.so

# The same for libhexagon_nn_skel_v65.so

# The same for libhexagon_nn_skel_v66.so

...

target_link_libraries(
        native-lib
        ...
        tflite-hexagon-lib
        tflite-hexagon-interface-lib
        tflite-hexagon-nn-skel-lib
        tflite-hexagon-nn-skel-v65-lib
        tflite-hexagon-nn-skel-v66-lib)
```

The build runs OK excluding the `nn_skel*` libraries -
Meaning the Tensorflow-Lite shared library itself, and the `libtensorflowlite_hexagon_jni.so` and `libhexagon_interface.so` build just fine.
When adding the `nn_skel*` libraries and trying to build, it fails with `libhexagon_nn_skel.so: error adding symbols: File in wrong format`.

I've checked that they are the same version as the `hexagon-interface` library (which included `--config=android_arm64` in the Bazel command), and they shouldn't be ABI dependent (current build is for `arm64-v8a` only).

**Any other info / logs**

```
[4/4] Linking CXX shared library /path/to/app/build/intermediates/cmake/debug/obj/arm64-v8a/libnative-lib.so
FAILED: /path/to/app/build/intermediates/cmake/debug/obj/arm64-v8a/libnative-lib.so 
: && /path/to/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android29 --gcc-toolchain=/path/to/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/path/to/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -std=c++11 -frtti -fexceptions -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libnative-lib.so -o /path/to/app/build/intermediates/cmake/debug/obj/arm64-v8a/libnative-lib.so /path/to/app/src/main/cpp/../jni/arm64-v8a/libtensorflowlite.so /path/to/app/src/main/cpp/../jni/arm64-v8a/libtensorflowlite_hexagon_jni.so /path/to/app/src/main/cpp/../jni/arm64-v8a/libhexagon_interface.so /path/to/app/src/main/cpp/../jni/arm64-v8a/libhexagon_nn_skel.so /path/to/app/src/main/cpp/../jni/arm64-v8a/libhexagon_nn_skel_v65.so /path/to/app/src/main/cpp/../jni/arm64-v8a/libhexagon_nn_skel_v66.so /path/to/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/29/liblog.so -latomic -lm && :
/path/to/app/src/main/cpp/../jni/arm64-v8a/libhexagon_nn_skel.so: error adding symbols: File in wrong format
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by Saduf2019** [comment]
@orangesomethingorange 
Please refer to [this issue](https://stackoverflow.com/questions/52760801/cmake-building-for-windows-clang-cl-using-ninja-generator) and let us know if it helps.
Is this issue related to #42519 issue created by you.

**Comment by orangesomethingorange** [comment]
Hi @Saduf2019 ,

Thanks for the link :)

> @orangesomethingorange
> Please refer to [this issue](https://stackoverflow.com/questions/52760801/cmake-building-for-windows-clang-cl-using-ninja-generator) and let us know if it helps.

This, unfortunately, is not relevant - it concerns `cmake` on Windows machines / Visual Studio.
The setup described in this issue has Linux Ubuntu 16.04 platform, and calls `cmake` via Android Studio.

> Is this issue related to #42519 issue created by you.

I'm not sure - both issues did occur on the same setup, and concern issues with external libraries, but I can't be sure.
For the Tensorflow-Lite library I wrote the code I needed myself - but I can't do that for a Qualcomm library, it's proprietary code.

**Comment by orangesomethingorange** [comment]
It seems like the shared object does not match the linker.

Just in case I've tried [v1.14 and v1.17](https://www.tensorflow.org/lite/performance/hexagon_delegate#step_2_add_hexagon_libraries_to_your_android_app_2) but got similar results.

These libraries are not meant for the ARM processor, so I expect to get the same results for any ABI, but I tried to link them for the `armeabi-v7a` ABI, and got this error:

`/path/to/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: fatal error: /path/to/app/src/main/cpp/../jni/armeabi-v7a/libhexagon_nn_skel.so: unsupported ELF machine number 164
`

**Comment by orangesomethingorange** [comment]
I installed the [Hexagon SDK v3.5.2 - Linux](https://developer.qualcomm.com/downloads/hexagon-sdk-v352-linux?referrer=node/6116) (from [here](https://developer.qualcomm.com/software/hexagon-dsp-sdk/tools)) and cloned the [nnlib repository](https://source.codeaurora.org/quic/hexagon_nn/nnlib) (from [CodeAurora](https://source.codeaurora.org/quic/hexagon_nn/nnlib)) to build the libraries.
Build the `v66` and `v65` Hexagon NN dynamic libraries, and I get (both cases):
- `libhexagon_nn_skel.a`
- `libhexagon_nn_skel.so`
- `hexagon_nn_ops.h`
- `ops.def`

(*) Note that the `soname` for shared object in both cases is `libhexagon_nn_skel.so` (as noted in `libhexagon_nn_skel_so_link.txt`)

Using the shared object resulted in the same error:
`error adding symbols: File in wrong format`

But when I add `libhexagon_nn_skel.a` instead of the shared one, it seems to build and compile OK, but I get an error when I call `ModifyGraphWithDelegate`:
```
W: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/apps_std_imp.c:750: Warning: apps_std_fopen_with_env failed with 0xd for libhexagon_nn_skel_v66.so (Permission denied)
E: Error 0x80000406: remote_handle_open_domain: dynamic loading failed for file:///libhexagon_nn_skel_v66.so?hexagon_nn_domains_skel_handle_invoke&_modver=1.0&_dom=cdsp on domain 3 (dlerror cannot open libhexagon_nn_skel_v66.so)
E: Error 0x80000406: remote_handle64_open failed for file:///libhexagon_nn_skel_v66.so?hexagon_nn_domains_skel_handle_invoke&_modver=1.0&_dom=cdsp
W/tflite: Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.
I/tflite: Hexagon Delegate is not supported.
```
So Tensflow-Lite is looking for the `v66` shared one.

Prior to calling `ModifyGraphWithDelegate` I have the following code:

In Java:
`System.loadLibrary("tensorflowlite_hexagon_jni");`

In C++:
```
TfLiteHexagonInit();
TfLiteHexagonDelegateOptions hexagon_opts = {0};
TfLiteDelegate * hexagon_delegate = TfLiteHexagonDelegateCreate(& hexagon_opts);
```

and I notice that `TfLiteHexagonDelegateCreate` always returns `NULL`.

1. Is this behavior (`TfLiteHexagonDelegateCreate` returns `NULL`) expected? Is that normal?
2. My HW uses the `v66`, and looks for it, but static version doesn't seem to match - can I explicitly call it from the static library?
3. Where does Tensorflow-Lite call / uses the Hexagon ops?
4. `soname` is always `libhexagon_nn_skel.so`, so what does Tensorflow-Lite is looking for when calling `v66`? What changes are expected for Tensorflow-Lite to address the `v66` library (and not `v65` for example)?

**Comment by karimnosseir** [comment]
Sorry for the late reply.
libhexagon_nn_skel are not ARM compiled, you should package them with your AAR. 
See instructions
https://www.tensorflow.org/lite/performance/hexagon_delegate

Thanks

**Comment by St190706025** [comment]
Is it necessary to add libhexagon_nn_skel for aarch64?

**Comment by karimnosseir** [comment]
@St190706025 It depends on your application, if the app will run on aarch64 then yes, if not then you don't need to.
