### ISSUE TITLE
I got error

### ISSUE THREAD

**Issue by sandipuncc** [tensorflow/tensorflow#42926]
![1](https://user-images.githubusercontent.com/7116366/92135241-22e8b500-ee28-11ea-8039-191a6b92f3ce.PNG)
![2](https://user-images.githubusercontent.com/7116366/92135268-2bd98680-ee28-11ea-8c6f-de4bcf107110.PNG)
 I used the code and got the problem , so please suggest me the solution, please remember I am naive in tensorflow.

**Comment by amahendrakar** [comment]
@sandipuncc,
Please fill in the issue template while submitting the issue. Looks like you are running code meant for TF 1.x on TF 2.x. In this case, you can tweak your code a bit as shown [this gist](https://colab.research.google.com/gist/amahendrakar/a2eed230ada70b1800d01b2f6c77edee/42926.ipynb).

However TF 1.x is not actively support, I'd suggest you to migrate your code to 2.x as shown in [this guide](https://www.tensorflow.org/guide/migrate). Thanks!

**Comment by mihaimaruseac** [comment]
`tf.placeholder` does not exist in TF 2.x
