### ISSUE TITLE
Does the framework support IPv6 networks?

### ISSUE THREAD

**Issue by lusterr** [tensorflow/tensorflow#42921]
Is this framework suitable for IPv6 network environment?

**Comment by ravikyram** [comment]
@lusterr 

Can you please elaborate about the issue & the context.
Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Thanks!

**Comment by gowthamkpr** [comment]
@ Can you please follow the template [here](https://github.com/tensorflow/tensorflow/issues/new/choose) to create the issue. Thanks!
