### ISSUE TITLE
How to save tf.data.Dataset object?

### ISSUE THREAD

**Issue by fjp** [tensorflow/tensorflow#42934]
**System information**
- TensorFlow version (you are using): 2.3.0
- Are you willing to contribute it (Yes/No): If possible

**Describe the feature and the current behavior/state.**

Hi, I am using `tf.data.Dataset` to prepare a streaming dataset which is used to train a tf.kears model. To use a python pipeline package like [Luigi](https://luigi.readthedocs.io/en/stable/index.html#) or [kedro](https://kedro.readthedocs.io/en/stable/) it is required to pickle the object. According to quantumblacklabs/kedro#91 the problem is that the `tf.data.Dataset` object ...

> can't be deep copied because somewhere deep inside it contains a `threading.RLock` object (which is quite unusual).

> The reference to pickle is somewhat misleading and comes up due to how deepcopy is implemented. See here for more detail: https://stackoverflow.com/questions/22388854/relationship-between-pickle-and-deepcopy/22618214
> 
> The best fix here would be to talk to the developers of keras about having adam optimizers [and tf.data.Dataset] implement the __getstate__ and __setstate__ functions so that they can be copied (and also pickled).

Would it be possible to add the feature which allows picklable `tf.data.Dataset` objects?

Issue #38483 is similar to this one but got closed because the idiomatic solution seems to be `tfrecords` and the implemented `tf.data.experimental.save` method. However, as far as I know, these approaches will save the complete dataset to disk which can be a huge waste of disk resources and the time it takes to save the complete dataset. 

Is there a way to save just the created `tf.data.Dataset` **object** to disk or are there any plans to implement this? And what would have to be done to achieve this?

Are there alternative suggestions to `tf.data.Dataset` when we want to use reproducible pipelines? 

- tfx
- tf.transform
- Apache beam pipelines (seem to be picklable)

I would welcome some more information about the differences between `tf.data.Dataset` and tfx releated packages (`tf.transform and apache beam). When should we use which?

**Will this change the current api? How?**

**Who will benefit with this feature?**

Everyone who wants to create reproducible pipelines with packages like `kedro` in combination with `tf.data.Dataset`.

**Comment by denisvorotyntsevunity** [comment]
Hello! I found these guides useful: 
1 - [TFRecord and tf.train.Example](https://www.tensorflow.org/api_docs/python/tf/train/Example)
2 - [tf.data.experimental.TFRecordWriter](https://www.tensorflow.org/api_docs/python/tf/data/experimental/TFRecordWriter)

**Comment by mohantym** [comment]
@fjp ! Beside TFRecord , I also found an article on [kafka](https://github.com/tensorflow/tensorflow/issues/42934#issuecomment-803314776) for streaming data.

**Comment by NEGU93** [comment]
I used [tf.data.experimental.save](https://www.tensorflow.org/api_docs/python/tf/data/experimental/save) and [tf.data.experimental.load](https://www.tensorflow.org/api_docs/python/tf/data/experimental/load) like this
```
tf.data.experimental.save(dataset=tf_dataset, path=full_path)
[...]
tensor_data = tf.data.experimental.load(full_path, element_spec=(tf.TensorSpec(shape=(128, 128, 3), dtype=tf.complex128 if complex_mode else tf.float64), tf.TensorSpec(shape=(classes,), dtype=tf.float64))
```
It bothered me a lot I had to use `element_spec` param. You can find it as an attribute of `tf.data.Dataset` named `element_spec`. You may be able to pickle that element as well not have to hardcode it.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
