### ISSUE TITLE
TF 1.15+ mutating sys.modules

### ISSUE THREAD

**Issue by mikeyshulman** [tensorflow/tensorflow#42930]
**System information**
- No custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 20.04.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.15.2-30-g4386a66 1.15.3
- Python version: 3.6.12
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
Can't iterate though sys.modules.values after importing tensorflow. Raises `RuntimeError` of `dictionary changed size during iteration`

**Describe the expected behavior**
Should not raise error

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```python
import sys
for v in sys.modules.values():
    print(v)
```
raises no error
```python
import sys
import tensorflow as tf
for v in sys.modules.values():
    print(v)
```
raises `RuntimeError: dictionary changed size during iteration`

Calling `list` on `sys.modules.values()` makes the problem go away, but sadly is not a viable solution. Lots of code currently depends on iterating through `sys.modules.values`, e.g. `unittest.TestCase.assertWarns`

Confirmed this behavior on tf1.15.3, tf2.0. 
Confirmed this behavior is not present in tf1.14 or 1.13

**Comment by amahendrakar** [comment]
@mikeyshulman,
As per [this comment](https://github.com/tensorflow/tensorflow/issues/33183#issuecomment-543931248) from a similar issue and [this](https://stackoverflow.com/a/33679686) StackOverflow answer, I was able to run the code by making a copy of the dictionary. 

Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/f7d4043416e85b95090b169b71aa03c2/42930.ipynb). Thanks!

**Comment by mikeyshulman** [comment]
Thanks @amahendrakar! That would definitely fix the issue for the snippet I pasted into the issue. The problem is there lots of existing code from third parties libraries do exactly this behavior. Notably, `unittest.TestCase.assertWarns`.

Is this known/desired behavior in tensorflow? Is it known why simply importing tensorflow causes this issue?

**Comment by mikeyshulman** [comment]
Just for the sake of being concrete: Any existing code that uses tensorflow, right now won't be able to adequately test their code. Consider:

```python
import unittest

from my_module import MyCoolThing  # this imports tensorflow

class TestMyAwesomeModel(unittest.TestCase):
    def test_cool_thing_warns(self):
        my_cool_thing = MyCoolThing()
        with self.assertWarns(UserWarning):
            my_cool_thing.do_somthing_naughty()
```

I'd expect to raise a `UserWaring`, but this will now raise a `RuntimeException` instead because `assertWarns` accesses `sys.modules`. 

This seems a bit restrictive. I think it would be tough to modify every third-party piece of code that touches `sys.modules`, and in some cases, we may actually need to access the modules themselves, and not a copy. Also, importing tensorflow broke a completely unrelated test. This behavior can be very difficult to debug. 

Thanks in advance for the help!

**Comment by mihaimaruseac** [comment]
I think this has been fixed in TF2.2 / TF2.3 with the removal of the virtual pip package.
