### ISSUE TITLE
Tensorflow GPU Support Installation instructions do not work due to missing cuBLAS

### ISSUE THREAD

**Issue by cdjameson** [tensorflow/tensorflow#42936]
### System information

-   **OS**: Linux Ubuntu 16.04
-   **TensorFlow installed from (source or binary)**: PyPI binary
-   **TensorFlow version**: 2.3.0
-   **Python version**: 3.7.7
-   **CUDA/cuDNN version**: CUDA 10.1 _installed as suggested using_ `apt-get --no-install-recommends cuda-10-1`, cuDNN 7.6
-   **GPU model and memory**: GeForce GTX 1080 Ti 10.92GiB
-   **Exact command to reproduce**: `tf.config.experimental.list_physical_devices('GPU')`

### Describe the problem
Installing/upgrading CUDA using verbatim instructions for Ubuntu 16.04 from [TF Install GPU Support](https://www.tensorflow.org/install/gpu) results in CUDA _without_ cuBLAS, which does not work for TensorFlow.

It appears there is an issue with the `cuda-10-1` package on APT, because installing from the [Nvidia-provided CUDA 10.1 update 2 runfile](https://developer.nvidia.com/cuda-10.1-download-archive-update2) resulted in the expected cuBLAS files. My workaround was to sloppily extract the raw cuda-toolkit lib directory from the aforementioned runfile and copy the libcublas files into `/usr/local/cuda-10.1/targets/x86_64-linux/lib`. I didn't have to mess with any `include` headers or `/usr/lib` symlinks to get Tensorflow to work. But that's clearly not a good solution, and that shouldn't be the only way to get the "tested" configuration to work using the install instructions from TensorFlow's own website.

**To reproduce:**
On an Ubuntu 16.04 machine, uninstall all CUDA drivers and toolkits. Install CUDA using the exact commands listed under _Install CUDA with apt_ on the above page. Install tensorflow in a new virtualenv using pip: `python3 -m pip install tensorflow`. Any GPU code will produce the following error.

### Source code / logs
`Could not load dynamic library 'libcublas.so.10'; dlerror: libcublas.so.10: cannot open shared object file: No such file or directory`

**Comment by Saduf2019** [comment]
@cdjameson 
Can you please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/26182#issuecomment-684993950) on same error and let us know if it helps.
similar issues to refer to:
#34759 [link](https://stackoverflow.com/questions/55224016/importerror-libcublas-so-10-0-cannot-open-shared-object-file-no-such-file-or)

**Comment by cdjameson** [comment]
@Saduf2019 Thanks for your quick response! This certainly is the correct solution to the problem, _and should be documented as such_. I hope to see this fixed in the [installation documentation](https://www.tensorflow.org/install/gpu).

**Comment by antortjim** [comment]
**OS**: Linux Ubuntu 18.04
**TensorFlow installed from (source or binary)**: PyPI binary
**TensorFlow version**: 2.1.0
**Python version**: 3.6.12
**CUDA/cuDNN version**: CUDA 10.1 installed as suggested using apt-get --no-install-recommends cuda-10-1, cuDNN 7.6
**GPU model and memory**: GeForce GTX 980 Ti 6075MiB

Dear Tensorflow developers

I found @cdjameson 's thread here https://forums.developer.nvidia.com/t/cublas-for-10-1-is-missing/71015/19 because I am encountering the same problem today October 17th. I had to follow the solution he and fellow user phillip3m commented on the forum. I just wanted to post a reminder for you to please update the documentation. Thanks!
