### ISSUE TITLE
Tflite ops: BatchMatMul, TensorListReserve, TensorListSetItem, TensorListStack

### ISSUE THREAD

**Issue by whiteRa2bit** [tensorflow/tensorflow#42937]
**System information**
- Linux Ubuntu 18.04
- TensorFlow installed from source 
- TensorFlow version 2.1.0

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, COS, DIV, EXPAND_DIMS, FULLY_CONNECTED, MAX_POOL_2D, MEAN, MUL, NEG, PACK, PAD, RESHAPE, SIN, SQRT, SQUEEZE, STRIDED_SLICE, SUB, SUM. Here is a list of operators for which you will need custom implementations: BatchMatMul, TensorListReserve, TensorListSetItem, TensorListStack.
```

I try to convert generator model from here: https://github.com/russoale/hmr2.0/blob/master/src/main/generator.py

Can you please give me an estimate when such operations as 
BatchMatMul, TensorListReserve, TensorListSetItem, TensorListStack will be transferred to tflite?

Looking forward to hearing from you!

**Comment by abattery** [comment]
TensorListReserve, TensorListSetItem, TensorListStack ops will be disappeared when you have a fixed size in your model, for example, batch size.

BatchMatMul can be supported via Select TF ops and we offer a selective build mechanism for Select TF ops for slim binary size deployment.

https://www.tensorflow.org/lite/guide/ops_select
https://www.tensorflow.org/lite/guide/reduce_binary_size

**Comment by whiteRa2bit** [comment]
Thanks a lot for your help Jae!

I have set up the input shape for my model via the attached code, nevertheless, I still get the error that TensorList operations are used. Can you please explain the proper way to set a fixed size in the model.
`
import sys
sys.path.append("hmr2.0/src/")

import tensorflow as tf

from main.model import Model
from notebooks.vis_util import preprocess_image
from main.config import Config


def main():
    model = Model()
    config = Config()
    generator = model.generator   
    
    original_img, input_img, params = preprocess_image('hmr2.0/src/notebooks/images/coco4.png', \
                                                        config.ENCODER_INPUT_SHAPE[0])
    
    if len(tf.shape(input_img)) is not 4:
        # [224, 224, 3] -> [1, 224, 224, 3]
        input_img = tf.expand_dims(input_img, 0) 
    generator._set_inputs(input_img)

    converter = tf.lite.TFLiteConverter.from_keras_model(generator)
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
        tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
    ]
    tflite_model = converter.convert()


if __name__ == '__main__':
    main()
`

**Comment by whiteRa2bit** [comment]
It happens when I try to transfer the following model:

```
class Regressor(tf.keras.Model):
    def __init__(self):
        super(Regressor, self).__init__(name='regressor')
        self.config = Config()

        self.mean_theta = tf.Variable(model_util.load_mean_theta(), name='mean_theta', trainable=True)

        self.fc_one = layers.Dense(1024, name='fc_0')
        self.dropout_one = layers.Dropout(0.5)
        self.fc_two = layers.Dense(1024, name='fc_1')
        self.dropout_two = layers.Dropout(0.5)
        variance_scaling = tf.initializers.VarianceScaling(.01, mode='fan_avg', distribution='uniform')
        self.fc_out = layers.Dense(85, kernel_initializer=variance_scaling, name='fc_out')

    def call(self, inputs, **kwargs):
        batch_size = inputs.shape[0] or self.config.BATCH_SIZE
        shape = (batch_size, 2048)
        assert inputs.shape[1:] == shape[1:], 'shape mismatch: should be {} but is {}'.format(shape, inputs.shape)

        batch_theta = tf.tile(self.mean_theta, [batch_size, 1])
        thetas = tf.TensorArray(tf.float32, self.config.ITERATIONS)
        for i in range(self.config.ITERATIONS):
            # [batch x 2133] <- [batch x 2048] + [batch x 85]
            total_inputs = tf.concat([inputs, batch_theta], axis=1)
            batch_theta = batch_theta + self._fc_blocks(total_inputs, **kwargs)
            thetas = thetas.write(i, batch_theta)

        return thetas.stack()

    def _fc_blocks(self, inputs, **kwargs):
        x = self.fc_one(inputs, **kwargs)
        x = tf.nn.relu(x)
        x = self.dropout_one(x, **kwargs)
        x = self.fc_two(x, **kwargs)
        x = tf.nn.relu(x)
        x = self.dropout_two(x, **kwargs)
        x = self.fc_out(x, **kwargs)
        return x

```

**Comment by whiteRa2bit** [comment]
I managed to convert the model using the following code: 
```
def get_tflite_model(model, model_name):
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.experimental_new_converter = False
    converter.allow_custom_ops=True
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
        tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
    ]
    tflite_model = converter.convert()
```

Can you please let me know whether it is a proper solution?

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/bc2bbf611b03c4bfbddc09d2bc215d9b/42937.ipynb#scrollTo=KMKC7J3mtevN). Thanks!

**Comment by whiteRa2bit** [comment]
@amahendrakar Thanks for your reply! 
Yes, I got the same error when I run my model using tf 2.3, I was rather wondering whether it is possible to fix the current error in tf2.1 the way @abattery mentioned

**Comment by whiteRa2bit** [comment]
As I found it [here](https://github.com/tensorflow/tensorflow/issues/37134) the reason of this error is the same: all shapes have to be fixed, but I have already set up the input shapes.

**Comment by whiteRa2bit** [comment]
@amahendrakar looking forward to hear from you! Thanks in advance!

**Comment by abattery** [comment]
@whiteRa2bit have you set a fixed batch size as well? Usually keras models have non-fixed size if you have not set it explicitly.
