### ISSUE TITLE
The train and test data of wide and deep example is broken

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/tensorflow#4293]
Wide and deep example code will download train and test data from `https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data` and `https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test`. But those files are broken now and you can `wget` to read the raw data.

```
|1x3 Cross validator
25, Private, 226802, 11th, 7, Never-married, Machine-op-inspct, Own-child, Black, Male, 0, 0, 40, United-States, <=50K.
38, Private, 89814, HS-grad, 9, Married-civ-spouse, Farming-fishing, Husband, White, Male, 0, 0, 50, United-States, <=50K.
28, Local-gov, 336951, Assoc-acdm, 12, Married-civ-spouse, Protective-serv, Husband, White, Male, 0, 0, 40, United-States, >50K.
44, Private, 160323, Some-college, 10, Married-civ-spouse, Machine-op-inspct, Husband, Black, Male, 7688, 0, 40, United-States, >50K.
```

If I modify the file and run with this command, it works. Maybe we should fix the raw dataset or change to other valid files.

```
python ./wide_n_deep_tutorial.py --train_data /home/data/train_data --test_data /home/data/test_data
```
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

Someone has asked the similar question in stackoverflow, http://stackoverflow.com/questions/38558976/tensorflow-wide-deep-example-not-working .
### Environment info

Operating System: Ubuntu 14.04
TensorFlow: 0.9.0
### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

Clone the tensorflow project and run `python wide_n_deep_tutorial.py` directly.
### Logs or other output that would be helpful

```
# python ./wide_n_deep_tutorial.py
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Training data is downloaded to /tmp/tmpUs2und
Test data is downloaded to /tmp/tmp1aH4KY
Traceback (most recent call last):
  File "./wide_n_deep_tutorial.py", line 213, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "./wide_n_deep_tutorial.py", line 209, in main
    train_and_eval()
  File "./wide_n_deep_tutorial.py", line 194, in train_and_eval
    df_train["income_bracket"].apply(lambda x: ">50K" in x)).astype(int)
  File "/usr/lib/python2.7/dist-packages/pandas/core/series.py", line 2023, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "inference.pyx", line 920, in pandas.lib.map_infer (pandas/lib.c:44780)
  File "./wide_n_deep_tutorial.py", line 194, in <lambda>
    df_train["income_bracket"].apply(lambda x: ">50K" in x)).astype(int)
TypeError: argument of type 'float' is not iterable
```

**Comment by tatatodd** [comment]
@tobegit3hub Thanks for filing this issue!

I see that the `|1x3 Cross validator` line in `adult.test` is unexpected.  Did you find any other issues in the two files?

We welcome pull requests to fix these kinds of problems!

**Comment by tobegit3hub** [comment]
Thanks @tatatodd .

These two files have unexpected empty line at the end of the files. After removing the first line of `|1x3 Cross validator` and the empty lines at the end, it will work.

I'm not sure who maintains these datasets. How can we create the pull-request and contribute for this?

**Comment by terrytangyuan** [comment]
You can fork the repo, work on your own branch to make the changes, and then submit a pull request.

**Comment by tobegit3hub** [comment]
Thanks @terrytangyuan and I knew how to send pull-request. I mean how to fix this issue. The dataset is from `https://archive.ics.uci.edu` which may be beyond the scope of TensorFlow.

Would you like to maintain the dataset by yourselves? Or contact someone who can fix this.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
