### ISSUE TITLE
New tf.image.resize method: Maximum Value

### ISSUE THREAD

**Issue by dominikj2** [tensorflow/tensorflow#42943]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.2.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
The tf.image.resize method does not include a Maximum Value method. 

**Will this change the current api? How?**
No, I don't think so.

**Who will benefit with this feature?**
tf.image.resize may be a useful function for Region of Interest (RoI) MaxPooling if it allowed for a method that extracts the maximum value for each pooled areas.

In my situation, 3D voxelised data (i.e. XYZ regular point cloud) needs to be unstacked  from 3D into 2D, and then  each 2D stack resized into a new dimension.  Using tf.image.resize with maximum voxel value that falls within each resized element could be useful. 

**Any Other info.**

**Comment by hyeygit** [comment]
Could [tf.nn.max_pool](https://www.tensorflow.org/api_docs/python/tf/nn/max_pool) be the functionality you're looking for?

**Comment by jvishnuvardhan** [comment]
@dominikj2 Can you please follow the suggestion mentioned above and let us know whether the issue resolved for you. If not, can you please add more details about your use-case and the feature you are looking. Thanks!
