### ISSUE TITLE
TFLite TransposeConvV2 Operator Slow on x86 CPU Ubuntu

### ISSUE THREAD

**Issue by CoreyCole** [tensorflow/tensorflow#42941]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): tf-nightly 2.4.0.dev20200902
- Python version: 3.6.9
- Bazel version (if compiling from source): 3.5.0
- GCC/Compiler version (if compiling from source): gcc 7.5.0
- CUDA/cuDNN version: CUDA 10.1
- GPU model and memory: Using CPU (Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz)

**Describe the current behavior**
The `TRANSPOSE_CONV` operator takes up >80% of total computation time when using the TFLite benchmarking tool.
```
============================ Top by Computation Time ==============================
	             [node type]	          [start]	  [first]	 [avg ms]	     [%]	  [cdf%]	  [mem KB]	[times called]	[Name]
	          TRANSPOSE_CONV	          235.882	  487.948	  482.097	 26.927%	 26.927%	     0.000	        1	[device_0/g_ae/dec_0/conv2d_transpose1]:102
	          TRANSPOSE_CONV	          719.253	  163.323	  162.187	  9.059%	 35.986%	     0.000	        1	[device_0/g_ae/dec_1/conv2d_transpose1]:113
	          TRANSPOSE_CONV	         1634.919	  108.162	  111.988	  6.255%	 42.241%	     0.000	        1	[device_0/g_ae/dec_9/conv2d_transpose1]:201
	          TRANSPOSE_CONV	         1501.813	  116.089	  109.471	  6.114%	 48.355%	     0.000	        1	[device_0/g_ae/dec_8/conv2d_transpose1]:190
	          TRANSPOSE_CONV	          882.714	  111.952	  108.459	  6.058%	 54.413%	     0.000	        1	[device_0/g_ae/dec_2/conv2d_transpose1]:124
	          TRANSPOSE_CONV	          993.583	  103.796	   97.807	  5.463%	 59.876%	     0.000	        1	[device_0/g_ae/dec_3/conv2d_transpose1]:135
	          TRANSPOSE_CONV	         1287.885	   92.329	   95.829	  5.352%	 65.229%	     0.000	        1	[device_0/g_ae/dec_6/conv2d_transpose1]:168
	          TRANSPOSE_CONV	         1394.631	  109.527	   95.786	  5.350%	 70.579%	     0.000	        1	[device_0/g_ae/dec_7/conv2d_transpose1]:179
	          TRANSPOSE_CONV	         1093.908	   92.043	   93.959	  5.248%	 75.827%	     0.000	        1	[device_0/g_ae/dec_4/conv2d_transpose1]:146
	          TRANSPOSE_CONV	         1193.164	   88.003	   89.509	  4.999%	 80.826%	     0.000	        1	[device_0/g_ae/dec_5/conv2d_transpose1]:157

Number of nodes executed: 216
============================== Summary by node type ==============================
	             [Node type]	  [count]	  [avg ms]	    [avg %]	    [cdf %]	  [mem KB]	[times called]
	          TRANSPOSE_CONV	       11	  1466.204	    81.898%	    81.898%	     0.000	       11
	                 CONV_2D	       11	   159.086	     8.886%	    90.785%	     0.000	       11
	                     ABS	       21	   111.310	     6.217%	    97.002%	     0.000	       21
	                     ADD	       32	    11.551	     0.645%	    97.647%	     0.000	       32
	                     MUL	       42	    10.792	     0.603%	    98.250%	     0.000	       42
	                 RESHAPE	       44	     9.645	     0.539%	    98.789%	     0.000	       44
	                     SUB	       21	     9.366	     0.523%	    99.312%	     0.000	       21
	                    RELU	       21	     6.514	     0.364%	    99.676%	     0.000	       21
	           CONCATENATION	       11	     5.129	     0.286%	    99.962%	     0.000	       11
	      TfLiteFlexDelegate	        1	     0.430	     0.024%	    99.986%	     0.000	        1
	                    TANH	        1	     0.245	     0.014%	   100.000%	     0.000	        1

Timings (microseconds): count=50 first=1811076 curr=1775110 min=1738229 max=1895058 avg=1.79038e+06 std=32080
```

**Describe the expected behavior**
Faster execution of this operator. I expected my model to run inference faster once I converted to TFLite, but currently it is running more slowly than regular tensorflow on the same hardware.

**Standalone code to reproduce the issue**
```
bazel-bin/tensorflow/lite/tools/benchmark/benchmark_model_plus_flex \
  --graph=.../converted_model_float32.tflite --num_threads=4 --enable_op_profiling=true > .../float32_benchmark.txt
```
(The benchmarking tool was built from tf master source commit 86db5756535f70f1b1fab61c6f3f0483141510e8)

**Other info / logs**
[Full TFLite benchmark output](https://github.com/tensorflow/tensorflow/files/5171974/float32_benchmark.txt)

I'd appreciate any tips for how I could profile this operator. How can I find out why it is taking so much time in my network? Can I use C++ profiling tools to find the computation time sinks in the [transpose_conv.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/optimized/optimized_ops.h#L5804)?

**Comment by renjie-liu** [comment]
Hi, can you try adding 

```--define=tflite_with_ruy=true``` when building the benchmark tool?

thanks!

**Comment by CoreyCole** [comment]
Hey @renjie-liu, I added that ruy flag when building the benchmarking tool (from master 86db5756535f70f1b1fab61c6f3f0483141510e8)
```
bazel build -c opt \
  --config=monolithic --define=tflite_with_ruy=true \
  tensorflow/lite/tools/benchmark:benchmark_model_plus_flex
```
And then I ran the benchmarking tool on my float32 TFLite model
```
bazel-bin/tensorflow/lite/tools/benchmark/benchmark_model_plus_flex \
  --graph=.../converted_model_float32.tflite --num_threads=4 --enable_op_profiling=true > ~/Desktop/float32_ruy_benchmark.txt
```
It seems it is running even more slowly and there is no additional information in the output (comparing to my original benchmark output linked in my original post). Do I need to run the benchmarking tool a different way to see the results of the ruy profiler?

[float32_ruy_benchmark.txt](https://github.com/tensorflow/tensorflow/files/5190234/float32_ruy_benchmark.txt)

**Comment by CoreyCole** [comment]
I did some profiling of the [TransposeConvV2](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/optimized/optimized_ops.h#L5804) while running the benchmarking.

[transpose_conv_profiling.txt](https://github.com/tensorflow/tensorflow/files/5191661/transpose_conv_profiling.txt)

Evidently, the largest time sink in the function is the `cpu_backend_gemm::Gemm` that is called in the `batch_size` for loop.

I stepped through the [cpu_backend_gemm.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/cpu_backend_gemm.h#L117) code with gdb to check what this `cpu_backend_gemm::Gemm` function was doing. I noticed `must_use_ruy` and `try_custom_gemv` are both false, whether I build the benchmark tool with `--define=tflite_with_ruy=true` or not.

**Comment by renjie-liu** [comment]
I see, this is really strange, can you add 
`--define=ruy_profiler=true` as well when building the benchmark_tool, we should be able to see the detailed profiling,

**Comment by CoreyCole** [comment]
That flag seemed to work! It put out more output about `cpu_backend_gemm::Gemm`

[float32_ruy_benchmark.txt](https://github.com/tensorflow/tensorflow/files/5191838/float32_ruy_benchmark.txt)

**Comment by renjie-liu** [comment]
Thanks for sharing! Will take a look!

**Comment by CoreyCole** [comment]
I wanted to see if this problem was specific to x86, so I built the benchmark tool on an AWS A1 arm instance. I did two benchmarks of the same model, one with `--define=ruy_profiler=true` and one without.

```
bazel-bin/tensorflow/lite/tools/benchmark/benchmark_model_plus_flex \
  --graph=.../converted_model_float32.tflite --num_threads=4 --enable_op_profiling=true --verbose=true > ~/float32_arm_benchmark.txt
```

[float32_arm_ruy_benchmark.txt](https://github.com/tensorflow/tensorflow/files/5198671/float32_arm_ruy_benchmark.txt)
[float32_arm_benchmark.txt](https://github.com/tensorflow/tensorflow/files/5198670/float32_arm_benchmark.txt)

**Comment by renjie-liu** [comment]
ruy is enabled by default for arm devices, so the numbers should be similar

**Comment by CoreyCole** [comment]
From comparing these two architectures, the model seems to perform about 80% faster on arm while my clock speed on x86 is  2x faster.

x86 avg time = 1.1e+07
arm avg time = 1.9+06

x86 max gHz = 5.0
[arm max gHz = 2.3](https://www.extremetech.com/computing/281338-amazon-launches-new-arm-based-custom-graviton-cpu#:~:text=The%20Graviton%20CPU,clock%20speed%20of%202.3GHz.)

```
x86 timings:
Timings (microseconds): count=15 first=10617766 curr=10610651 min=10610651 max=10833023 avg=1.06631e+07 std=73060

arm timings:
Timings (microseconds): count=50 first=1849736 curr=1847769 min=1844926 max=1857462 avg=1.85012e+06 std=2777

( 1.1e7 - 1.8e6 ) / (1.1e7) ~~ 80% time reduction
```

**Comment by bjacob** [comment]
@talumbau is already the right assignee :-)

**Comment by CoreyCole** [comment]
how can I disable ruy on arm so I can get a comparable benchmark to the x86 without ruy?

**Comment by bjacob** [comment]
`bazel build --define=tflite_with_ruy=false`

**Comment by CoreyCole** [comment]
@bjacob setting ruy to false on arm throws a compile error, but that is likely out of the scope of this issue.

I did an additional x86 benchmark compiling with some different flags and managed to eek out a bit more performance, but still `TRANSPOSE_CONV` operator takes up the vast majority of compute time:
```
bazel build -c opt \
  --config=mkl --copt=-mavx --copt=-msse4.1 --copt=-msse4.2 \
  tensorflow/lite/tools/benchmark:benchmark_model_plus_flex
```
```
============================== Top by Computation Time ==============================
	             [node type]	          [start]	  [first]	 [avg ms]	     [%]	  [cdf%]	  [mem KB]	[times called]	[Name]
	          TRANSPOSE_CONV	          145.739	  334.845	  327.682	 30.711%	 30.711%	     0.000	        1	[device_0/g_ae/dec_0/conv2d_transpose1]:102
	          TRANSPOSE_CONV	          474.519	   98.657	   98.284	  9.211%	 39.922%	     0.000	        1	[device_0/g_ae/dec_1/conv2d_transpose1]:113
	          TRANSPOSE_CONV	          573.890	   68.139	   67.579	  6.334%	 46.255%	     0.000	        1	[device_0/g_ae/dec_2/conv2d_transpose1]:124
	          TRANSPOSE_CONV	          975.095	   56.976	   57.059	  5.348%	 51.603%	     0.000	        1	[device_0/g_ae/dec_9/conv2d_transpose1]:201
	          TRANSPOSE_CONV	          902.487	   52.394	   53.175	  4.984%	 56.587%	     0.000	        1	[device_0/g_ae/dec_8/conv2d_transpose1]:190
	          TRANSPOSE_CONV	          643.654	   51.886	   51.722	  4.847%	 61.434%	     0.000	        1	[device_0/g_ae/dec_3/conv2d_transpose1]:135
	          TRANSPOSE_CONV	          848.040	   44.327	   45.076	  4.225%	 65.659%	     0.000	        1	[device_0/g_ae/dec_7/conv2d_transpose1]:179
	          TRANSPOSE_CONV	          794.084	   43.691	   44.680	  4.187%	 69.846%	     0.000	        1	[device_0/g_ae/dec_6/conv2d_transpose1]:168
	          TRANSPOSE_CONV	          697.544	   47.731	   44.555	  4.176%	 74.022%	     0.000	        1	[device_0/g_ae/dec_4/conv2d_transpose1]:146
	          TRANSPOSE_CONV	          746.798	   42.475	   42.731	  4.005%	 78.027%	     0.000	        1	[device_0/g_ae/dec_5/conv2d_transpose1]:157

Number of nodes executed: 216
============================== Summary by node type ==============================
	             [Node type]	  [count]	  [avg ms]	    [avg %]	    [cdf %]	  [mem KB]	[times called]
	          TRANSPOSE_CONV	       11	   847.637	    79.448%	    79.448%	     0.000	       11
	                     ABS	       21	   106.461	     9.978%	    89.426%	     0.000	       21
	                 CONV_2D	       11	    79.186	     7.422%	    96.848%	     0.000	       11
	                     ADD	       32	     6.867	     0.644%	    97.492%	     0.000	       32
	                 RESHAPE	       44	     6.518	     0.611%	    98.103%	     0.000	       44
	                     MUL	       42	     6.445	     0.604%	    98.707%	     0.000	       42
	                     SUB	       21	     5.671	     0.532%	    99.239%	     0.000	       21
	                    RELU	       21	     4.125	     0.387%	    99.625%	     0.000	       21
	           CONCATENATION	       11	     3.426	     0.321%	    99.946%	     0.000	       11
	      TfLiteFlexDelegate	        1	     0.461	     0.043%	    99.990%	     0.000	        1
	                    TANH	        1	     0.111	     0.010%	   100.000%	     0.000	        1

Timings (microseconds): count=50 first=1067538 curr=1117788 min=1041534 max=1142071 avg=1.067e+06 std=24935
```
[float32_mavx_msse4.1_msse4.2_benchmark.txt](https://github.com/tensorflow/tensorflow/files/5211910/float32_mavx_msse4.1_msse4.2_benchmark.txt)

**Comment by talumbau** [comment]
Hi,

Unfortunately I don't have a full answer but I can provide some info. First, can you say what the run time is for TF vs. TFL on x86 with this model built/run in a standard way (basically just `-c opt` for the build line)? If TFL is 2-3x slower than TF, it is likely something bad is happening. If TFL is on the order of 10-20% slower than TF for this float model, it might just mean that deeper work is required on the TFL side to optimize transpose conv (so no easy fix available). For certain kinds of TF Ops, or TF Ops with certain options (like certain stride values) the transformation from TF -> TFL can result in a correct but unoptimized graph. So, the main thing to say is that there might be no magic bullet on the performance side.

Regarding the runs with Ruy, I am able to see something that is going wrong. When you add the `--define=ruy_profiler=true` the resulting output is really helpful to figure out performance issues. Please use it by default as we keep debugging this issue. In this case, the output:

```
       * 12.38% TrMul (Path=0x1, max_num_threads=4, is_prepacked=(0,0))
          * 12.38% TrMulImpl, general case
            * 11.42% Kernel (Standard Cpp)
```

shows that you are getting the "standard Cpp" path, which is unoptimized naive code only used for debugging purposes or if no optimized code path could be found. On x86, Ruy has optimized kernels for AVX, AVX2, and AVX512. From the CPU you indicated, it appears that you do have AVX2 on your machine, at least according to [this](https://ark.intel.com/content/www/us/en/ark/products/148263/intel-core-i7-8086k-processor-12m-cache-up-to-5-00-ghz.html)

Ruy should autodetect the platform and choose the most performance path (AVX2 in this case), but for some reason it is not doing that. You can manually set the path with the env variable `RUY_PATHS`, so as an experiment you can do:

````
RUY_PATHS=0x20  <rest of  execution line here>
```

Although if you hit an illegal instruction for your path the code will crash. Please give it a try and let me know the result.

**Comment by talumbau** [comment]
It is worth pointing out that this model is quite large (peak memory footprint > 800 MB) and 1.8 seconds inference time on ARM when actually getting optimized code. ~90% of the execution time is in GEMM in ARM case, so I think if we are able to get the AVX2 path going on your machine, that's probably the low hanging fruit here.
