### ISSUE TITLE
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by HiImAri** [tensorflow/tensorflow#42947]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64 bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Surface Pro
- TensorFlow installed from (source or binary):
- TensorFlow version:2
- Python version:3.7.9
- Installed using virtualenv? pip? conda?:PIP

Can't import

>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\rache\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rache\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\rache\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\rache\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\rache\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\rache\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\rache\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ravikyram** [comment]
@HiImAri 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here.](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).

Please, check Your CPU/Python is on 32 bits?Please, refer #42751 and see if it helps you.Please, refer similar issues #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
Thanks!

**Comment by HiImAri** [comment]
Running on 64 bits and im running Intel(R) Atom(TM) x7-Z8700 CPU@160GHz and i already downloaded the Microsoft visual c++ while following the instructions through Tensorflow website

**Comment by ravikyram** [comment]
@HiImAri 

Looking at specification of your cpu seems like avx is not supported.Please, refer the [link here](https://ark.intel.com/content/www/us/en/ark/products/85475/intel-atom-x7-z8700-processor-2m-cache-up-to-2-40-ghz.html).
In this case you can build Tensorflow from source or use Google colab as an alternative. Thanks!

**Comment by akashAD98** [comment]
I faced the same issue with tensorflow-1.12.0 what i did was :

`Install anaconda
open anaconda prompt
conda create -n tf20 python=3.6
activate tf20
conda install tensorflow
python`
Now check by importing tensorflow
the version i used was 3.6, but you can also try with 3.7 Hope it helps!
