### ISSUE TITLE
Tensorflow and RTX 3000 (TF 1.X or 2.X required)

### ISSUE THREAD

**Issue by kiflowb777** [tensorflow/tensorflow#42958]
1. Will tensorflow support new cards?
2. Which version of TF is required?
3. Will I run the program on version tf.1.x with RTX3000?

**Comment by bhack** [comment]
I think yes. If you can see there are also some specific feature in nightly for the Ampere arch in  https://github.com/tensorflow/community/pull/287.
Also if currently the CI is not running on this card GEN:
https://github.com/tensorflow/community/pull/287/files#diff-0f47247f8a899bec07e8ab8b8fa219d4R34

I don't think it will officially support new CUDA releases in TF 1.x as you can see in https://github.com/tensorflow/tensorflow/issues/42895#issuecomment-685874736

/cc @reedwm

**Comment by reedwm** [comment]
@bhack is correct, TensorFlow will support RTX 3000 cards. I don't think TF 2.3 will work on the upcoming cards, but TF 2.4 will. Unfortunately TF 2.4 will be released after the cards are released, but tf-nightly will work as well.

As @bhack mentioned, TF 1.x does not support RTX 3000, as it only supports older versions of CUDA. But [you can TF1 programs](https://www.tensorflow.org/guide/migrate) that don't depend on `tf.contrib` in TF 2 (including TF 2.4) with

```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```

**Comment by iperov** [comment]
RTX 3080 TI does not work with TF 1.12 CUDA 9.2

Seems like no backward compatibility provided by TF.

So what reason to make applications using TF which is not future-proof ?

**Comment by thesigmaguy** [comment]
What is an RTX 3080Ti, there is only a 3080 and 3090 right?
