### ISSUE TITLE
CMSIS-NN: Incorrect flags for non-DSP/MVE processors (convolution op only)

### ISSUE THREAD

**Issue by felix-johnny** [tensorflow/tensorflow#42951]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): Source
- Tensorflow version (commit SHA if source): 5a16264ba6f12883726d12d484d4cd61405ddab7
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Arm internal testing using models for Cortex-M3

**Describe the problem**
CalculateOpData() in cmsis-nn/conv.cc is inside a '#if defined(__ARM_FEATURE_DSP) || defined(__ARM_FEATURE_MVE)' flag which is not set for a Cortex-M3 or similar that do not have DSP or MVE extensions. This results in uninitialized quantization parameters being passed on to the convolution API in the Eval() procedure. This could result in an assert in debug builds or atleast an incorrect output from convolution.

**Please provide the exact sequence of commands/steps when you ran into the problem** 
Just a visual code check.

**Comment by freddan80** [comment]
We'll have a look at this issue.
