### ISSUE TITLE
tf.io.gfile.glob hangs if gcs directory contains a directory named '/'.

### ISSUE THREAD

**Issue by Mistobaan** [tensorflow/tensorflow#42955]
**Describe the current behavior**
```
mkdir -p .//
gsutil -m rsync -r .//  gs://remote-folder//
```
```
import tensorflow as tf
tf.io.gfile.glob('gs://remote-folder//*')
```
program hangs forever. The remote folder in google cloud storage has to contain a folder named '/'.  
The directory was created using `gsutil rsync`.

This was on Tensorflow 1.15.3 enterprise, and had the same behavior on 1.15.2 from pip.

edit: just happened again. I am not sure what generates that directory. Tensorboard's 1.15 TPU profiler maybe?

![image](https://user-images.githubusercontent.com/112599/92290815-6267dd80-eeca-11ea-875c-ebf6eac7b804.png)

~~seems this line does the trick of creating that spurious directory:~~
~~tensorboard --logdir=gs://$BUCKET/models/$MODEL/$EXPERIMENT/ --reload_multifile=true --master_tpu_unsecure_channel=$TPU_NAME~~
~notice the trailing `/`~

This is the culprit:

```python
from tensorflow.contrib import summary
with summary.create_file_writer(os.path.join(self._log_dir, 'scalars')).as_default():
    offset = 0
     with summary.record_summaries_every_n_global_steps(
```
if self.log_dir ends with '/' summary writer will create that '/' directory. 
The problem though is most likely in the logic of `gfile.glob`

**Comment by mihaimaruseac** [comment]
Can you fill in issue template, please? Curious which version of TF are you using. Can you try with 2.3 and nightly please? I recall fixing a similar issue a few months ago.

**Comment by Mistobaan** [comment]
@mihaimaruseac updated with the tensorflow info. I use only version `1.15.x`. I deleted that abnormal directory on GCS so I can't reproduce.

**Comment by mihaimaruseac** [comment]
Yeah, we did not backport that fix since we only do patch releases for security issues.

**Comment by rmothukuru** [comment]
@Mistobaan,
Since [it is fixed](https://github.com/tensorflow/tensorflow/issues/42955#issuecomment-687287334) in **`Tensorflow Version 2.3`**, as it is recommended to switch to **`Tensorflow Version 2.x`**, from **`1.x`**,  can you please let us know if we can close this issue? Thanks!

**Comment by mihaimaruseac** [comment]
I'd close this issue as it was fixed.
