### ISSUE TITLE
benchmark  error  cannot run in phone

### ISSUE THREAD

**Issue by mathpopo** [tensorflow/tensorflow#42956]
use  benchmark

HWBKK-Q:/data/local/tmp $ ls
benchmark_model         libhexagon_nn_skel_v65.so     
libhexagon_interface.so libhexagon_nn_skel_v66.so     
libhexagon_nn_skel.so   mobilenet_quant_v1_224.tflite 
/benchmark_model --graph=./mobilenet_quant_v1_224.tflite --num_threads=4      <
/system/bin/sh: ./benchmark_model: not executable: 64-bit ELF file
1|HWBKK-Q:/data/local/tmp $ uname -a
Linux localhost 4.9.82+ #1 SMP PREEMPT Mon Jul 20 02:03:26 CST 2020 aarch64
HWBKK-Q:/data/local/tmp $

**Comment by mathpopo** [comment]
bazel build -c opt --fat_apk_cpu=arm64-v8a tensorflow/lite/tools/benchmark:benchmark_model

**Comment by mathpopo** [comment]
(base) chenxin@Nitro-AN515:~/Downloads/tensorflow/bazel-bin/tensorflow/lite/tools/benchmark$ ./benchmark_model --graph=/home/chenxin/Downloads/tensorflow/mobilenet_quant_v1_224.tflite --num_threads=4
STARTING!
Log parameter values verbosely: [0]
Num threads: [4]
Graph: [/home/chenxin/Downloads/tensorflow/mobilenet_quant_v1_224.tflite]
#threads used for CPU inference: [4]
Loaded model /home/chenxin/Downloads/tensorflow/mobilenet_quant_v1_224.tflite
The input model file size (MB): 4.2761
Initialized session in 0.384ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=8 first=65650 curr=71055 min=64394 max=73197 avg=68889.1 std=3197

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=50 first=71198 curr=72666 min=69611 max=78963 avg=70973 std=1487

Inference timings in us: Init: 384, First inference: 65650, Warmup (avg): 68889.1, Inference (avg): 70973
Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
Peak memory footprint (MB): init=3.90234 overall=10.8125

**Comment by bhack** [comment]
Are you using the Android build section to compile `benchmark_model` to run in the phone? 
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/benchmark#to-buildinstallrun

**Comment by bhack** [comment]
You can also find pre-compiled android binary at https://www.tensorflow.org/lite/performance/measurement?hl=en

**Comment by freedomtan** [comment]
@mathpopo   In short, what you have is not an arm64-v8a binary. The  `--fat_apk_cpu` is for building transient dependencies only, See https://docs.bazel.build/versions/master/user-manual.html#flag--fat_apk_cpu.

Easy way to build `benchmark_model` for android as stated in benchmark_model's [README.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/benchmark/README.md) is something like
```
bazel build -c opt \
  --config=android_arm64 \
  tensorflow/lite/tools/benchmark:benchmark_model
```
To see what `android_arm64`  does, check TF's [.bazelrc](https://github.com/tensorflow/tensorflow/blob/master/.bazelrc#L105-L115)

**Comment by mathpopo** [comment]
@bhack 
(base) chenxin@Nitro-AN515:~/Downloads/tensorflow$ bazel build -c opt \
>   --crosstool_top=//external:android/crosstool \
>   --cpu=armeabi-v7a \
>   --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
>   --config monolithic \
>   tensorflow/tools/benchmark:benchmark_model
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'build' from /home/chenxin/Downloads/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/chenxin/Downloads/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Found applicable config definition build:short_logs in file /home/chenxin/Downloads/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/chenxin/Downloads/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:monolithic in file /home/chenxin/Downloads/tensorflow/.bazelrc: --define framework_shared_object=false
INFO: Found applicable config definition build:linux in file /home/chenxin/Downloads/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/chenxin/Downloads/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Analyzed target //tensorflow/tools/benchmark:benchmark_model (101 packages loaded, 4440 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /home/chenxin/.cache/bazel/_bazel_chenxin/f2be0bb8460d7bf102965465c62801f2/sandbox
ERROR: /home/chenxin/.cache/bazel/_bazel_chenxin/f2be0bb8460d7bf102965465c62801f2/external/com_google_absl/absl/base/BUILD.bazel:83:1: C++ compilation of rule '@com_google_absl//absl/base:spinlock_wait' failed (Exit 1)
Target //tensorflow/tools/benchmark:benchmark_model failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 97.375s, Critical Path: 0.32s
INFO: 5 processes: 5 local.
FAILED: Build did NOT complete successfully

**Comment by mathpopo** [comment]
@freedomtan 
(base) chenxin@Nitro-AN515:~/Downloads/tensorflow$ bazel build -c opt \
>   --config=android_arm64 \
>   tensorflow/lite/tools/benchmark:benchmark_model
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=204
INFO: Reading rc options for 'build' from /home/chenxin/Downloads/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/chenxin/Downloads/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Found applicable config definition build:short_logs in file /home/chenxin/Downloads/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/chenxin/Downloads/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:android_arm64 in file /home/chenxin/Downloads/tensorflow/.bazelrc: --config=android --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a
INFO: Found applicable config definition build:android in file /home/chenxin/Downloads/tensorflow/.bazelrc: --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --noenable_platform_specific_config --copt=-w --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
INFO: Build options --copt, --cpu, --define, and 1 more have changed, discarding analysis cache.
ERROR: /home/chenxin/.cache/bazel/_bazel_chenxin/f2be0bb8460d7bf102965465c62801f2/external/local_config_cc/BUILD:47:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'arm64-v8a'
ERROR: Analysis of target '//tensorflow/lite/tools/benchmark:benchmark_model' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed
INFO: Elapsed time: 0.491s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 67 targets configured)


(base) chenxin@Nitro-AN515:~/Downloads/tensorflow$ echo $NDK
/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b
(base) chenxin@Nitro-AN515:~/Downloads/tensorflow$

**Comment by freedomtan** [comment]
it seems you didn't configure Android SDK and NDK, in the [README.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/benchmark/README.md)
```
(0) Refer to https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android to edit the WORKSPACE to configure the android NDK/SDK.
.....
```

**Comment by mathpopo** [comment]
@freedomtan   no where can see how set my ndk path?

workspace(name = "org_tensorflow")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "5b00383d08dd71f28503736db0500b6fb4dda47489ff5fc6bed42557c07c6ba9",
    strip_prefix = "rules_closure-308b05b2419edb5c8ee0471b67a40403df940149",
    urls = [
        "https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz",
        "https://github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz",  # 2019-06-13
    ],
)

# Load tf_repositories() before loading dependencies for other repository so
# that dependencies like com_google_protobuf won't be overridden.
load("//tensorflow:workspace.bzl", "tf_repositories")
# Please add all new TensorFlow dependencies in workspace.bzl.
tf_repositories()

register_toolchains("@local_config_python//:py_toolchain")

load("@io_bazel_rules_closure//closure:defs.bzl", "closure_repositories")

closure_repositories()

load("//third_party/toolchains/preconfig/generate:archives.bzl",
     "bazel_toolchains_archive")

bazel_toolchains_archive()

load(
    "@bazel_toolchains//repositories:repositories.bzl",
    bazel_toolchains_repositories = "repositories",
)

bazel_toolchains_repositories()

# Use `swift_rules_dependencies` to fetch the toolchains. With the
# `git_repository` rules above, the following call will skip redefining them.
load("@build_bazel_rules_swift//swift:repositories.bzl", "swift_rules_dependencies")
swift_rules_dependencies()

# We must check the bazel version before trying to parse any other BUILD
# files, in case the parsing of those build files depends on the bazel
# version we require here.
load("//tensorflow:version_check.bzl", "check_bazel_version_at_least")
check_bazel_version_at_least("1.0.0")

load("//third_party/android:android_configure.bzl", "android_configure")
android_configure(name="local_config_android")
load("@local_config_android//:android.bzl", "android_workspace")
android_workspace()

# If a target is bound twice, the later one wins, so we have to do tf bindings
# at the end of the WORKSPACE file.
load("//tensorflow:workspace.bzl", "tf_bind")
tf_bind()

http_archive(
    name = "inception_v1",
    build_file = "//:models.BUILD",
    sha256 = "7efe12a8363f09bc24d7b7a450304a15655a57a7751929b2c1593a71183bb105",
    urls = [
        "https://storage.googleapis.com/download.tensorflow.org/models/inception_v1.zip",
    ],
)

http_archive(
    name = "mobile_ssd",
    build_file = "//:models.BUILD",
    sha256 = "bddd81ea5c80a97adfac1c9f770e6f55cbafd7cce4d3bbe15fbeb041e6b8f3e8",
    urls = [
        "https://storage.googleapis.com/download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_android_export.zip",
    ],
)

http_archive(
    name = "mobile_multibox",
    build_file = "//:models.BUILD",
    sha256 = "859edcddf84dddb974c36c36cfc1f74555148e9c9213dedacf1d6b613ad52b96",
    urls = [
        "https://storage.googleapis.com/download.tensorflow.org/models/mobile_multibox_v1a.zip",
    ],
)

http_archive(
    name = "stylize",
    build_file = "//:models.BUILD",
    sha256 = "3d374a730aef330424a356a8d4f04d8a54277c425e274ecb7d9c83aa912c6bfa",
    urls = [
        "https://storage.googleapis.com/download.tensorflow.org/models/stylize_v1.zip",
    ],
)

http_archive(
    name = "speech_commands",
    build_file = "//:models.BUILD",
    sha256 = "c3ec4fea3158eb111f1d932336351edfe8bd515bb6e87aad4f25dbad0a600d0c",
    urls = [
        "https://storage.googleapis.com/download.tensorflow.org/models/speech_commands_v0.01.zip",
    ],
)

http_archive(
    name = "person_detect_data",
    sha256 = "170542270da256994ce24d1e357f6e84a54fdaf7d28ff2b74725a40b70b082cf",
    urls = [
        "https://storage.googleapis.com/download.tensorflow.org/data/tf_lite_micro_person_data_grayscale_2020_05_24.zip",
    ],
)

# Required for dependency @com_github_grpc_grpc

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load(
    "@build_bazel_rules_apple//apple:repositories.bzl",
    "apple_rules_dependencies",
)

apple_rules_dependencies()

load(
    "@build_bazel_apple_support//lib:repositories.bzl",
    "apple_support_dependencies",
)

apple_support_dependencies()

load("@upb//bazel:repository_defs.bzl", "bazel_version_repository")

bazel_version_repository(name = "bazel_version")

load("//third_party/googleapis:repository_rules.bzl", "config_googleapis")

config_googleapis()

**Comment by Saduf2019** [comment]
@mathpopo 
Please update if this is still an issue.

**Comment by freedomtan** [comment]
@mathpopo in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android, you can find the following message, 

```
NOTE: As long as you have the SDK and NDK installed, the ./configure script will create these rules for you. 
Answer "Yes" when the script asks to automatically configure the ./WORKSPACE.
```
