### ISSUE TITLE
savermodel quantization arrive TFlite model,on the windows+python Test times are slow

### ISSUE THREAD

**Issue by huafeihuayu** [tensorflow/tensorflow#42954]
quantization: 
import tensorflow as tf
saved_model_dir="D:/tf_ocr/tf_resnet10/"
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_quantized_model=converter.convert()
open("D:/sfz/tf_sfz/model.tflite","wb").write(tflite_quantized_model)

test:
 inputImg=(img/255).astype(np.float32)
        interpreter = tf.lite.Interpreter(model_path=model)
        interpreter.allocate_tensors()
        input_details = interpreter.get_input_details()
        output_details = interpreter.get_output_details()
        interpreter.set_tensor(input_details[0]['index'], [inputImg])
        a = time.time()
        # print(a)
        interpreter.invoke()
        b = time.time()
        # print(b)
        print((b - a) * 1000)

tensorflow 1.15.0 + python3.5 + windows10

The size of the model is reduced to its original size 1/4,but the savermodel test time about is 17.16ms,After the quantitative lite test time about is 55.62ms,
The speed was slowed down three times

**Comment by amahendrakar** [comment]
@huafeihuayu,
In order to reproduce the issue reported here, could you please share the contents of the `tf_resnet10` folder with us?

Also TensorFlow 1.x is not actively supported, please update TensorFlow to v2.3 and check if you are facing the same issue. Thanks!

**Comment by huafeihuayu** [comment]
sorry，Due to the company's confidentiality, I cannot provide it for the time being.This is still the case after I tried it with TensorFlow2.3.
The file model in our TF_resnet10 consists of CKPT converted into Savermodel. pb and variables after tensorFlow training. We directly converted into TF_lite and the quantified TF_LITE.During the training, the data is float32, the quantized TF_lite, the incoming data must also be float32, otherwise an error will be reported, and the quantized data is UINT8 according to the official website, whether the time is slow is related to this.

**Comment by huafeihuayu** [comment]
> @huafeihuayu,
> In order to reproduce the issue reported here, could you please share the contents of the `tf_resnet10` folder with us?
> 
> Also TensorFlow 1.x is not actively supported, please update TensorFlow to v2.3 and check if you are facing the same issue. Thanks!

sorry，Due to the company's confidentiality, I cannot provide it for the time being.This is still the case after I tried it with TensorFlow2.3.
The file model in our TF_resnet10 consists of CKPT converted into Savermodel. pb and variables after tensorFlow training. We directly converted into TF_lite and the quantified TF_LITE.During the training, the data is float32, the quantized TF_lite, the incoming data must also be float32, otherwise an error will be reported, and the quantized data is UINT8 according to the official website, whether the time is slow is related to this.

**Comment by huafeihuayu** [comment]
> @amahendrakar ,


sorry，Due to the company's confidentiality, I cannot provide it for the time being.This is still the case after I tried it with TensorFlow2.3.
The file model in our TF_resnet10 consists of CKPT converted into Savermodel. pb and variables after tensorFlow training. We directly converted into TF_lite and the quantified TF_LITE.During the training, the data is float32, the quantized TF_lite, the incoming data must also be float32, otherwise an error will be reported, and the quantized data is UINT8 according to the official website, whether the time is slow is related to this.

**Comment by amahendrakar** [comment]
> sorry，Due to the company's confidentiality, I cannot provide it for the time being.This is still the case after I tried it with TensorFlow2.3.

@huafeihuayu,
Without a reproducible code, it'd be difficult for us to debug the issue. In this case, is it possible for you to provide a dummy model to replicate the issue reported here? Thanks!
