### ISSUE TITLE
Regarding the operation of arbitrary scale access to the network

### ISSUE THREAD

**Issue by wangwenchao-job** [tensorflow/tensorflow#42950]
When using vgg for migration learning, the specific layer of the network will be used here. I hope that the network can accept pictures of any size as input. I found some information on the Internet. One way is to use lambda as the input layer to replace the original vgg The input layer, but I don’t know how to operate this, is there a better way.

**Comment by amahendrakar** [comment]
@wangwenchao-job,
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!
