### ISSUE TITLE
GPU devices not detected in tf-nightly in latest releases (Google Colaboratory)

### ISSUE THREAD

**Issue by drajsel** [tensorflow/tensorflow#42957]
Hello, 

I installed `tf-nightly` in a Google Colaboratory notebook and noticed that the model training time is significantly longer than when I was training it at the beginning of August. Then I ran 

```
print(tf.test.gpu_device_name())
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
```

and no GPU devices were detected, even though the accelerator was set to 'GPU'. 

But after uninstalling the latest release and installing `tf-nightly-2.4.0-dev20200815` the GPU was successfully detected. 
Trying out different releases, seems like it doesn't work as of `2.4.0-dev20200819` release.

**Comment by bhack** [comment]
I confirm this. The c++ wrapper return only the CPU device:
```
from tensorflow.python import pywrap_tfe
print(pywrap_tfe.TF_ListPhysicalDevices())
```

**Comment by bhack** [comment]
/cc @martinwicke this could create some false negative to your first stage triagers when the protocol require them to test on Colab gists with nightly about reproducibility. This is limited to GPU only ticket that require GPU runtimes.

E.g. See https://github.com/tensorflow/tensorflow/issues/42885

**Comment by bhack** [comment]
P.s. I can also confirm that it start with:
`pip install tf-nightly==2.4.0.dev20200819`

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with latest TF-nightly i.e. v2.4.0-dev20200904, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/25b8598fea215239f22d406a387c1735/42957.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment]
@drajsel Is this happening only in colab or it also happened in the local with GPU? Thanks!

**Comment by sanjoy** [comment]
`2.4.0-dev20200819` is the first release with CUDA 11, so it is very likely that that's the root issue.  Colab needs to be adjusted to use CUDA 11 instead of CUDA 10.1.

**Comment by jvishnuvardhan** [comment]
@drajsel As mentioned by @sanjoy this is related to colab. Can you please open an issue in colab repository [here](https://github.com/googlecolab/colabtools). Thanks!

**Comment by sanjoy** [comment]
CC @fischman

**Comment by drajsel** [comment]
@jvishnuvardhan I opened the issue [there](https://github.com/googlecolab/colabtools/issues/1574). Thank you for your time!
