### ISSUE TITLE
Misleading error message on keras.Model initialization

### ISSUE THREAD

**Issue by tornikeo** [tensorflow/tensorflow#42966]
### System information
---
 Ubuntu linux 20.04
From pip, tf version 2.3.0

### Describe the current behavior
---
Consider this simple code from [this tutorial](https://www.tensorflow.org/guide/keras/sequential_model#feature_extraction_with_a_sequential_model)

```python
import tensorflow as tf
from tensorflow import keras

assert tf.__version__ == '2.3.0'

initial_model = keras.Sequential(
    [
        keras.Input(shape=(250, 250, 3)),
        keras.layers.Conv2D(32, 5, strides=2, activation="relu"),
        keras.layers.Conv2D(32, 3, activation="relu"),
        keras.layers.Conv2D(32, 3, activation="relu"),
    ]
)


feature_extractor = keras.Model(
    inputs=initial_model.inputs,
    #Note the error!
    blah=[layer.output for layer in initial_model.layers], 
)

```
And the error is:
> TypeError: ('Keyword argument not understood:', 'inputs')  

### Describe the expected behavior
---
I expect the error to contain a meaningful message, and at least to mention the incorrectly specified keyword `blah`. Just mentioning the one argument that is correctly written does not help. Maybe the error could be like 
> TypeError: ('Keyword argument not understood:', 'blah')  

or   

> TypeError: Invalid keyword arguments

**Comment by AnimeshMaheshwari22** [comment]
I tried running the code you have mentioned and got this error message: TypeError: ('Keyword argument not understood:', 'blah')

**Comment by AnimeshMaheshwari22** [comment]
I suggest **replace** from tensorflow.keras import layers **with** from keras import layers

**Comment by tornikeo** [comment]
@AnimeshMaheshwari22 Could you explain why? I have other keras backends and importing just keras would risk importing the wrong keras type.

**Comment by amahendrakar** [comment]
@tornikeo,
I was able to reproduce the error with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/914cd3beedc2d86332c8b4c66ceff3c7/42966.ipynb). However, the issue seems to be fixed with the latest [TF-nightly](https://colab.research.google.com/gist/amahendrakar/3bd91481518d8b4c4e21161396be59f1/42966-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by tornikeo** [comment]
That resolves this issue. Thanks @amahendrakar!
