### ISSUE TITLE
Tensorflow build with AVX2 without warnings of ignoring it. But after the installation it is not using it anymore.

### ISSUE THREAD

**Issue by Ch33s3Burger** [tensorflow/tensorflow#42960]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
-Windows 10 Pro
-GTX 1060 3gb
-compute capabilities 6.1
-Python 3.6
-Tensorflow 2.3
-bazel 3.1.0
-TensorRT 6.0
-using AVX2

**Describe the problem**
I build tensorflow 2.3 with all the infos at the top. In the python ./configure.py part in the installation i choosed "Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]: /arch:AVX2". While building there was no Error or Warning that it would be ignored. 
After the installation of the package i ran a deepspeech command to test it and it printed out this : "I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2". So my CPU supports AVX2 but my build wasnt compile to use that.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

C:\TenserFlow\tensorflow>python ./configure.py
You have bazel 3.1.0 installed.
Please specify the location of python. [Default is C:\Python38-32\python.exe]:

Found possible Python library paths:
  C:\Python38-32\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Python38-32\lib\site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]: /arch:AVX2

Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: y
Eigen strong inline overridden.

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v2             # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=nonccl         # Disable NVIDIA NCCL support.

C:\TenserFlow\tensorflow>bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

C:\TenserFlow\tensorflow>bazel-bin\tensorflow\tools\pip_package\build_pip_package C:/tmp/tensorflow_pkg

C:/tmp/tensorflow_pkg>pip3 install C:/tmp/tensorflow_pkg/tensorflow-version-cp36-cp36m-win_amd64.whl

Then i ran DeepSpeech that used my installed Tensorflow Version.
deepspeech --model deepspeech-0.8.1-models.pbmm --scorer deepspeech-0.8.1-models.scorer --audio audio/2830-3980-0043.wav

The output works fine but it also gives the Info that AVX2 isnt used.

**Comment by bhack** [comment]
Can you past the content of your `.tf_configure.bazelrc`?

**Comment by Ch33s3Burger** [comment]
build --action_env PYTHON_BIN_PATH="C:/Python38-32/python.exe"
build --action_env PYTHON_LIB_PATH="C:/Python38-32/lib/site-packages"
build --python_path="C:/Python38-32/python.exe"
build --config=xla
build:opt --copt=/arch:AVX2
build:opt --define with_default_optimizations=true
build --define=override_eigen_strong_inline=true
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test:v1 --test_tag_filters=-benchmark-test,-no_oss,-no_windows,-gpu,-oss_serial
test:v1 --build_tag_filters=-benchmark-test,-no_oss,-no_windows,-gpu
test:v2 --test_tag_filters=-benchmark-test,-no_oss,-no_windows,-gpu,-oss_serial,-v1only
test:v2 --build_tag_filters=-benchmark-test,-no_oss,-no_windows,-gpu,-v1only
build --action_env TF_CONFIGURE_IOS="0"

**Comment by bhack** [comment]
Do you had any `cl : Command line warning` on build?

**Comment by Ch33s3Burger** [comment]
no

**Comment by bhack** [comment]
What is your MSVC version?

**Comment by Ch33s3Burger** [comment]
Newest Version so Visual Studio 2019

**Comment by bhack** [comment]
It seems all ok. I don't only understand why we have this `--copt` difference with https://github.com/tensorflow/tensorflow/blob/master/.bazelrc#L365
Sorry but I don't have a windows machine to debug it more. Waiting for @Saduf2019

**Comment by ahtik** [comment]
@Ch33s3Burger What looks a bit suspcious is the `C:/Python38-32/python.exe` part, initial "System information" section mentions "Python 3.6". Would you mind running `C:\Python38-32\python.exe -VV` and make sure it's a 64bit python build, not 
32bit? TF requires 64bit. Worth double checking if the freshly built wheel is really the one that is being installed and gives the AVX2 warning.

I do have a Windows machine and could try to reproduce.

**Comment by bhack** [comment]
@ahtik Nice catch. Yes python 64 Is required.

**Comment by Saduf2019** [comment]
@Ch33s3Burger 
You could be facing this issue because of the following reasons

You you running 32-bit Python or 32-bit OS
[Your CPU does not support AVX instructions, please provide the make and model of your CPU in this case.]
Please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) and check if you have the correct dependencies installed.

Also, check these similar duplicate issues: #42058 #41596 #40459 #39007 #38916 #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 .

Thanks!

**Comment by Ch33s3Burger** [comment]
Thx for the catch with python 32-bit i fixed it. I also looked over the system requirements and i have all. And as above metioned my CPU can use AVX2. I am trying it now with python 3.6 64-bit.

**Comment by Ch33s3Burger** [comment]
This is my .tf_configure.bazelrc

build --action_env PYTHON_BIN_PATH="C:/Python36/python.exe"
build --action_env PYTHON_LIB_PATH="C:/Python36/lib/site-packages"
build --python_path="C:/Python36/python.exe"
build --config=xla
build:opt --copt=/arch:AVX2
build:opt --define with_default_optimizations=true
build --define=override_eigen_strong_inline=true
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test:v1 --test_tag_filters=-benchmark-test,-no_oss,-no_windows,-gpu,-oss_serial
test:v1 --build_tag_filters=-benchmark-test,-no_oss,-no_windows,-gpu
test:v2 --test_tag_filters=-benchmark-test,-no_oss,-no_windows,-gpu,-oss_serial,-v1only
test:v2 --build_tag_filters=-benchmark-test,-no_oss,-no_windows,-gpu,-v1only
build --action_env TF_CONFIGURE_IOS="0"

But still after building and installing its still not compiled to AVX2

**Comment by ahtik** [comment]
@Ch33s3Burger Could you post the output from `C:/Python36/python.exe -VV`?

One other "moving part" is the MS VS Built Tools path, hopefully the build is picking up a good version. It's cl.exe compiler is what is eventually getting the AVX2 flag. Mine is at `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe`. To set/override it for the TF build, use smth like `SET BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC`.

**Comment by Ch33s3Burger** [comment]
C:\tmp\tensorflow_pkg>python -VV
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]

**Comment by Ch33s3Burger** [comment]
Where should i put this "SET BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC" command?

**Comment by ahtik** [comment]
`SET BAZ....=....` goes to the same command prompt used for building, before running the TF configure and build commands. To set the env variables. Run `set` to see all current ones. But in your case it's likely not going to help/TF build should pick up the latest installed compiler anyway and BAZEL_VC is about more precise control about the build env.

Not sure if it helps right now but I posted some notes on building with Windows at https://github.com/tensorflow/tensorflow/issues/38174#issuecomment-613722488.

To pinpoint the issue, let's reduce the surface area, try running `python -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([10000, 10000])));print(tf.random.__file__)"` instead of deepsearch.

**Comment by Saduf2019** [comment]
@Ch33s3Burger 
You may also refer to #38712

**Comment by Ch33s3Burger** [comment]
>>> import tensorflow as tf
>>> print(tf.reduce_sum(tf.random.normal([10000, 10000])))
2020-09-11 11:57:43.047859: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2463f500370 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-11 11:57:43.048081: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
tf.Tensor(-6465.927, shape=(), dtype=float32)
>>> print(tf.random.__file__)
C:\Python36\lib\site-packages\tensorflow\_api\v2\random\__init__.py

**Comment by ahtik** [comment]
@Ch33s3Burger Looks like the AVX2 warning does not appear here and your wheel is fine, right? If the AVX2 were missing, it would have been reported already.

**Maybe** it's a deepspeech build, bundling or runtime env topic after all?

**Comment by Ch33s3Burger** [comment]
OK thx for your help. I am gonna take a look on deepspeech then.
