### ISSUE TITLE
Where is the source code for keras v2.4.3?

### ISSUE THREAD

**Issue by SmartManoj** [tensorflow/tensorflow#42961]
Not found in both tensorflow and keras github repo?

It is released before tensorflow 2.3.0. Why it is not integrated into this?

**Comment by bhack** [comment]
Keras was redirected to `tf.keras` in https://github.com/keras-team/keras/pull/14121/files.
Just a few commit later the version was bump to v2.4.3 https://github.com/keras-team/keras/commit/1a3ee8441933fc007be6b2beb47af67998d50737

**Comment by amahendrakar** [comment]
@SmartManoj,
Adding to @bhack's comment, you can read more about this from the [release notes](https://github.com/keras-team/keras/releases) of Keras 2.4.0.

Link to source code of [Keras v2.4.3](https://github.com/keras-team/keras/blob/master/keras/__init__.py#L32) for reference. Thanks!

**Comment by SmartManoj** [comment]
So every release is not mentioned [here](https://github.com/keras-team/keras/releases)?

Used [this](https://github.com/keras-team/keras/search?q=%272.4.3%27&unscoped_q=%272.4.3%27&type=Commits) search but found '.' is not supported [yet](https://github.com/isaacs/github/issues/402) in search
