### ISSUE TITLE
MicroInterpreter::tensors_size() always returns zero

### ISSUE THREAD

**Issue by keithm-xmos** [tensorflow/tensorflow#42964]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Fedora 32
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): 238981a91a9b780ab4449829469a71c5d668a273
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): x86

**Describe the problem**

The tensors_size() method of the MicroInterpreter class always returns zero.  

**Please provide the exact sequence of commands/steps when you ran into the problem**

To demonstrate, insert the following line:

`TF_LITE_MICRO_EXPECT_GT(static_cast<size_t>(0), interpreter.tensors_size());`

here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/micro_interpreter_test.cc#L87

And run:

`$ make -f tensorflow/lite/micro/tools/make/Makefile TARGET="x86" test_micro_interpreter_test`

**Comment by thaink** [comment]
@advaitjain Could you take a look at this issue?

**Comment by nkreeger** [comment]
@keithm-xmos I think you are using a bad TARGET="x86". Can you try and remove that?

`make -f tensorflow/lite/micro/tools/make/Makefile test_micro_interpreter_test`

That passes for me on Darwin x86_64.

**Comment by keithm-xmos** [comment]
@nkreeger Did you make the modification to micro_interpreter_test.cc before rebuilding and running your suggestion?  It fails on x86 and xcore for me.  I think your find that it will fail on any platform.

**Comment by nkreeger** [comment]
@keithm-xmos ah sorry i missed that - our macro is a little confusing and the test code isn't the cleanest at the moment.

Try this:
TF_LITE_MICRO_EXPECT_GT(interpreter.tensors_size(), static_cast<size_t>(0));

That works for me - the macro is checking that |0 > tensors_size| which is always false.

**Comment by keithm-xmos** [comment]
I applied your suggestion and I get the following: 

```
Testing TestInterpreter
interpreter.tensors_size() > static_cast<size_t>(0) failed at tensorflow/lite/micro/micro_interpreter_test.cc:87
Output tensors not at index 0 are allocated from the persistent memory arena. Repeat calls will cause excess allocation!
Testing TestMultiTenantInterpreter
Testing TestKernelMemoryPlanning
Output tensors not at index 0 are allocated from the persistent memory arena. Repeat calls will cause excess allocation!
Output tensors not at index 0 are allocated from the persistent memory arena. Repeat calls will cause excess allocation!
Output tensors not at index 0 are allocated from the persistent memory arena. Repeat calls will cause excess allocation!
Output tensors not at index 0 are allocated from the persistent memory arena. Repeat calls will cause excess allocation!
Output tensors not at index 0 are allocated from the persistent memory arena. Repeat calls will cause excess allocation!
Output tensors not at index 0 are allocated from the persistent memory arena. Repeat calls will cause excess allocation!
Testing TestVariableTensorReset
Testing TestIncompleteInitialization
Testing InterpreterWithProfilerShouldProfileOps
Testing TestIncompleteInitializationAllocationsWithSmallArena
Failed to allocate tail memory. Requested: 240, available 208, missing: 32
Failed to allocate memory for context->eval_tensors, 240 bytes required
Failed starting model allocation.

Testing TestInterpreterDoesNotAllocateUntilInvoke
[RecordingMicroAllocator] Arena allocation total 768 bytes
[RecordingMicroAllocator] Arena allocation head 32 bytes
[RecordingMicroAllocator] Arena allocation tail 736 bytes
[RecordingMicroAllocator] 'TfLiteEvalTensor data' used 240 bytes with alignment overhead (requested 240 bytes for 10 allocations)
[RecordingMicroAllocator] 'Persistent TfLiteTensor data' used 0 bytes with alignment overhead (requested 0 bytes for 0 tensors)
[RecordingMicroAllocator] 'Persistent TfLiteTensor quantization data' used 0 bytes with alignment overhead (requested 0 bytes for 0 allocations)
[RecordingMicroAllocator] 'TfLiteTensor variable buffer data' used 40 bytes with alignment overhead (requested 12 bytes for 3 allocations)
[RecordingMicroAllocator] 'NodeAndRegistration struct' used 168 bytes with alignment overhead (requested 168 bytes for 3 NodeAndRegistration structs)
[RecordingMicroAllocator] 'Operator runtime data' used 0 bytes with alignment overhead (requested 0 bytes for 0 OpData structs)
7/8 tests passed
~~~SOME TESTS FAILED~~~

Interpreter has 0 tensors and 2 nodes
Inputs: 0
Outputs: 2 3


Node   0 Operator Custom Name mock_custom
  Inputs: 0 1
  Outputs: 2
Node   1 Operator Custom Name mock_custom
  Inputs: 0 1
  Outputs: 3
make: *** [tensorflow/lite/micro/tools/make/Makefile:368: test_micro_interpreter_test] Error 1
```

**Comment by keithm-xmos** [comment]
I ran with

> make -f tensorflow/lite/micro/tools/make/Makefile test_micro_interpreter_test

Here's my diff

```
diff --git a/tensorflow/lite/micro/micro_interpreter_test.cc b/tensorflow/lite/micro/micro_interpreter_test.cc
index a4a4143a2a..c5a13af8da 100644
--- a/tensorflow/lite/micro/micro_interpreter_test.cc
+++ b/tensorflow/lite/micro/micro_interpreter_test.cc
@@ -84,6 +84,7 @@ TF_LITE_MICRO_TEST(TestInterpreter) {
     TF_LITE_MICRO_EXPECT_LE(interpreter.arena_used_bytes(), 928 + 100);
     TF_LITE_MICRO_EXPECT_EQ(static_cast<size_t>(1), interpreter.inputs_size());
     TF_LITE_MICRO_EXPECT_EQ(static_cast<size_t>(2), interpreter.outputs_size());
+    TF_LITE_MICRO_EXPECT_GT(interpreter.tensors_size(), static_cast<size_t>(0));
 
     TfLiteTensor* input = interpreter.input(0);
     TF_LITE_MICRO_EXPECT_NE(nullptr, input);

```

**Comment by nkreeger** [comment]
@keithm-xmos sorry I had a bad vim buffer - yes this was accidentally regressed. I just opened https://github.com/tensorflow/tensorflow/pull/43109 to fix this -

Hopefully this isn't breaking you on anything right now - this API is mostly around for unit tests and inspecting of a model. I'd advise against looping through the graph on that API. Those values are now allocated from the "persistent" memory area of the arena. I have some documentation coming on those changes.

**Comment by nkreeger** [comment]
Should be fixed with this change: https://github.com/tensorflow/tensorflow/commit/ba071d416fc3d00b79021658c8d666b40b3fcb77
