### ISSUE TITLE
Grid RNN Cell does not support dynamic batch sizes

### ISSUE THREAD

**Issue by StefOe** [tensorflow/tensorflow#4296]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

http://stackoverflow.com/questions/38442025/tensorflow-grid-lstm-rnn-typeerror
### Environment info

Operating System: 
Ubuntu 16.04 LTS (GNU/Linux 4.4.0-31-generic x86_64)

Installed version of CUDA and cuDNN: 
-rw-r--r-- 1 root root   322936 Sep 19  2015 /usr/lib/x86_64-linux-gnu/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Mär 30 14:25 /usr/lib/x86_64-linux-gnu/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root       19 Mär 30 14:25 /usr/lib/x86_64-linux-gnu/libcudart.so.7.5 -> libcudart.so.7.5.18
-rw-r--r-- 1 root root   383336 Sep 19  2015 /usr/lib/x86_64-linux-gnu/libcudart.so.7.5.18
-rw-r--r-- 1 root root   720192 Sep 19  2015 /usr/lib/x86_64-linux-gnu/libcudart_static.a
lrwxrwxrwx 1 root root       12 Apr 14 17:53 /usr/lib/x86_64-linux-gnu/libcuda.so -> libcuda.so.1
lrwxrwxrwx 1 root root       17 Apr 14 17:53 /usr/lib/x86_64-linux-gnu/libcuda.so.1 -> libcuda.so.361.42
-rw-r--r-- 1 root root 16881416 Mär 23 01:42 /usr/lib/x86_64-linux-gnu/libcuda.so.361.42
lrwxrwxrwx 1 root root       13 Aug 31 13:32 /usr/lib/x86_64-linux-gnu/libcudnn.so -> libcudnn.so.4
lrwxrwxrwx 1 root root       17 Aug 31 13:32 /usr/lib/x86_64-linux-gnu/libcudnn.so.4 -> libcudnn.so.4.0.7
-rwxr-xr-x 1 root root 61453024 Aug 31 13:32 /usr/lib/x86_64-linux-gnu/libcudnn.so.4.0.7
-rw-r--r-- 1 root root 62025862 Aug 31 13:32 /usr/lib/x86_64-linux-gnu/libcudnn_static.a

If installed from binary pip package, provide:
1. A link to the pip package you installed:
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0rc0-cp35-cp35m-linux_x86_64.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`: '0.10.0rc0'
### What other attempted solutions have you tried?

changed file tensorflow/tensorflow/contrib/grid_rnn/python/ops/grid_rnn_cell.py:

```
  # project input
  if inputs is not None and sum(inputs.get_shape().as_list()) > 0 and len(
      conf.inputs) > 0:
```

to:

```
  # project input
  if inputs is not None and inputs.get_shape()[1] > 0 and len(
      conf.inputs) > 0:
```

fixed the issue, but I'm not sure if it is the intended behavior
### Logs or other output that would be helpful

if not changed the following error occurs:

**\* TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

-> probably because of sum(inputs.get_shape().as_list())

**Comment by tatatodd** [comment]
Thanks for filing the issue @StefOe 

You might also be interested in the comments in #1665 (toward the bottom), which is also linked in the comments of the SO post you provided.

Note that we have limited resources for maintaining contrib code.  We do welcome pull requests with tests to fix things!

**Comment by phvu** [comment]
FYI, I am working on a fix for this. Will also fix all the warnings related to `state_is_tuple` and `input_size`.

**Comment by StefOe** [comment]
Thank you! Sadly I was lacking the time to do it properly.

**Comment by phvu** [comment]
PR is submitted: https://github.com/tensorflow/tensorflow/pull/4631
Comments and suggestions will be appreciated.

**Comment by StefOe** [comment]
PR #4631 fixes the issue. Thank you!
Should I close this, or wait untill the PR is reviewed?

**Comment by phvu** [comment]
I guess we should wait until the PR is reviewed.
