### ISSUE TITLE
Muliple conventions 

### ISSUE THREAD

**Issue by SmartManoj** [tensorflow/tensorflow#42963]
## URL(s) with the issue:
https://www.tensorflow.org/tutorials/quickstart/beginner
https://www.tensorflow.org/tutorials/keras/classification?hl=en,https://keras.io/api/models/sequential/
https://keras.io/guides/sequential_model/

## Description of issue (what needs changing):
tf.keras.layers.Dense
keras.layers.Dense
layers.Dense

Muliple conventions are followed. Which is the preferred way?

**Comment by akashAD98** [comment]
basically tensorflow uses keras as backend ,so its  basically depends upon which one your using either keras or tennsorflow.
if your using keras ,then you can use
 `import keras
from keras.layers import Dense`

if you want to use tensorflow  you  can  use tensorflow

 `import tensorflow as tf
model.add(tf.keras.layers.Dense(128,activation=tf.nn.relu)) ' 
basically both codes working same.
Keras is a neural network library while TensorFlow is the open-source library for a number of various tasks in machine learning. TensorFlow provides both high-level and low-level APIs while Keras provides only high-level APIs. **Keras is built in Python which makes it way more user-friendly than TensorFlow**

**Comment by fchollet** [comment]
The answer is: `layers.Dense` is preferred (over `tf.keras.layers.Dense`, which is too long, or over `Dense`, which tends to involve importing many individual symbols).
