### ISSUE TITLE
bazel-bin does not contain full API

### ISSUE THREAD

**Issue by Aksh-kumar** [tensorflow/tensorflow#42979]
I a trying to use C++ API of tensorflow 2.x after run "bazel build //tensorflow:libtensorflow_cc.so" command build was succeeded but some of the API are missing in bazel-bin\tensorflow like "tensorflow\tensorflow\core\public" is I am doing anything wrong?
**System information**
- OS Platform and Distribution (Window 10):
- TensorFlow installed from (source): yes
- TensorFlow version: 2.3.0 (latest)
- Python version: 3.7
- Bazel version (if compiling from source): 3.4.1
- CUDA/cuDNN version: No GPU support 

**exact sequence of commands**
I follow [this](https://www.tensorflow.org/install/source_windows) but change build option as bazel build //tensorflow:libtensorflow_cc.so

**logs**
this is the following output I am getting after running "bazel build //tensorflow:libtensorflow_cc.so" command
```
C:\Users\username\Documents\TF\tensorflow>bazel build //tensorflow:libtensorflow_cc.so
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'build' from c:\users\username\documents\tf\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/python/python.exe
INFO: Reading rc options for 'build' from c:\users\username\documents\tf\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from c:\users\...\documents\tf\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/python/python.exe --action_env PYTHON_LIB_PATH=C:/python/lib/site-packages --python_path=C:/python/python.exe --config=xla --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file c:\users\username\documents\tf\tensorflow\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file c:\users\username\documents\tf\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file c:\users\username\documents\tf\tensorflow\.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:windows in file c:\users\username\documents\tf\tensorflow\.bazelrc: --copt=/w --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\users\username\documents\tf\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Analyzed target //tensorflow:libtensorflow_cc.so (202 packages loaded, 19125 targets configured).
INFO: Found 1 target...
Target //tensorflow:libtensorflow_cc.so up-to-date:
  bazel-bin/tensorflow/libtensorflow_cc.so
INFO: Elapsed time: 37794.951s, Critical Path: 1324.20s
INFO: 8556 processes: 8556 local.
INFO: Build completed successfully, 10656 total actions

```

**Comment by gunan** [comment]
it may be an oversight. Would you like to send a Pull request adding the dependency to libtensorflow_cc ?

**Comment by Aksh-kumar** [comment]
Thanks for responding back to me.I don' have anything to check in since I didn't change any code what I did just follow the build instruction and all I got is bazel build folder in /tensorflow i.e
/tensorflow/bazel-bin/
/tensorflow/bazel-out/
/tensorflow/bazel-tensorflow/
/tensorflow/bazel-testlogs/
In total all of size near 38.2 GBs 
All I want is to use c++ API of tensorflow.

**Comment by gunan** [comment]
bazel-* directory sizes are expected, because they include all intermediate files created by bazel. Sometimes multiple times!
What you need is only this file: `bazel-bin/tensorflow/libtensorflow_cc.so` and the headers, which are less than 1GB.
@av8ramit do we have the C++ packages built and uploaded to GCS?
Could you share which script our user should use to get the C++ distributable for TF?

@Aksh-kumar if we provided a prebuilt tar package, would you be able to use that instead?

**Comment by Aksh-kumar** [comment]
for tar package It need to contain all header file and libtensorflow_cc.dll, and libtensorflow_cc.lib beacause I want to use in c++ project and I want to use all [c++APIs](https://www.tensorflow.org/api_docs/cc)  which present in
tensorflow/c
tensorflow/cc
tensorflow/core
.....

**Comment by av8ramit** [comment]
@gunan unfortunately we only have the C API uploaded to [GCS](https://storage.googleapis.com/libtensorflow-nightly) via our libtensorflow distributable. Libtensorflow_cc is being planned for Q4 of this year.

**Comment by gunan** [comment]
@Aksh-kumar all of those libraries should already be linked into `bazel-bin/tensorflow/libtensorflow_cc.so`
For the headers, you can simply copy the headers from the source tree, you do not need to look for them under bazel-* folders.

**Comment by Aksh-kumar** [comment]
ok @gunan I will try that one.

**Comment by Aksh-kumar** [comment]
It works for me I added the tensorflow/tensorflow path in include directory.

**Comment by Aksh-kumar** [comment]
I just want to know Is there is any easier way to use tensorflow c++ API, since I am facing lot of difficulties, I google this thing but I could not found any reliable solution, I even try to build by using bazel, build was succeeded but the problem I am facing. It does not contain full header file, for example array_ops.h present in "bazel-bin/tensorflow/cc/ops/array_ops.h" location an standerd_ops.h present in "tensorflow/cc/ops/standard_ops.h" location, even I include both of these I am getting conflicting declaration  while using them like while declaring  tensorflow::GraphDef graph_def I am getting conflicting declaration since it is present in multiple places i.e. tensorflow/cc/framework/scope.h and tensorflow/core/graph/graph.h and one more place so ultimately build is failing, can you please suggest me any simpler way to use it.

**Comment by av8ramit** [comment]
Unfortunately, there is no simpler way that I know of at this time until we start `libtensorflow_cc` distributed builds.

**Comment by Aksh-kumar** [comment]
thanks for responding back to me, can you please tell me when we will expect c++ API .. any rough estimation?

**Comment by av8ramit** [comment]
We are trying our best to deliver them in Q4, but we also welcome community support.

**Comment by Aksh-kumar** [comment]
Thanks I will definitely try to give my best in community support.
