### ISSUE TITLE
How to fix "AttributeError: module 'tensorflow.keras.backend' has no attribute 'get_session'"

### ISSUE THREAD

**Issue by faniiiiii** [tensorflow/tensorflow#42981]
Hello i'm trying to make a deepfake without coding (because i dont know how lmao) and i have a issue , here my code 

fd = MTCNNFaceDetector(sess=K.get_session(), model_path="./mtcnn_weights/")
save_interval = 5 # perform face detection every {save_interval} frames
save_path = "./faceA/"
preprocess_video(fn_source_video, fd, save_interval, save_path)
save_path = "./faceB/"
preprocess_video(fn_target_video, fd, save_interval, save_path)

thank you and sorry if i seem dumb

**Comment by ymodak** [comment]
Looks like you are using TF2 where `get_session()` is deprecated.
For workarounds see https://stackoverflow.com/a/58442121/11127923

**Comment by Saduf2019** [comment]
@faniiiiii 
Can you please fill in the issue template with system details, complete code for us to replicate and tf version used so we could help you resolve the issue reported. [you may refer to [this link](https://stackoverflow.com/questions/56646940/how-to-properly-saving-loaded-h5-model-to-pb-with-tf2)] #40869

Please try : [try to replace tf.keras.backend.get_session() with tf.compat.v1.keras.backend.get_session()]

For tensorflow prior to version 2, do:
from tensorflow.compat.v1.keras import backend as K
K.set_session()
