### ISSUE TITLE
it allocates on all specified devices (GPU Memory usage is high on Nvidia-smi), but does not do computations (no memory utilization from Nvidia-smi while the program is running)

### ISSUE THREAD

**Issue by gao8954** [tensorflow/tensorflow#4298]
Tensorflow it allocates on all specified devices (GPU Memory usage is high on Nvidia-smi), but does not do computations (no memory utilization from Nvidia-smi while the program is running),what's wrong

**Comment by tatatodd** [comment]
@gao8954 we primarily use github issues for tracking bugs and installation issues.  For general debugging and help, please ask your question on StackOverflow, and tag it with the `tensorflow` tag.

I'd suggest you start on the tensorflow.org site and run some of the simple tutorials and examples, and confirm that your installation is correct.  Perhaps take a look here:
https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#optional-install-cuda-gpus-on-linux

Thanks!
