### ISSUE TITLE
tf.GradientTape().gradient() returns None

### ISSUE THREAD

**Issue by 26345211** [tensorflow/tensorflow#42984]
I am using a training loop with GradientTape, however, it returns a list of Nones : [None, None, None, None, None, None, None, None]

Colab Code : https://colab.research.google.com/gist/26345211/3fa3d06165d1ffa0ddf66b3847933e11/untitled1.ipynb

**Comment by bhack** [comment]
Please, can you compile the ISSUE template and post a very minimal but complete code snippet or Colab to reproduce this?

**Comment by 26345211** [comment]
Colab code to reproduce problem https://colab.research.google.com/gist/26345211/3fa3d06165d1ffa0ddf66b3847933e11/untitled1.ipynb

Thanks

**Comment by bhack** [comment]
Are you sure about how you have organized your code?
If you want to customize `fit` please thake a look at https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit

**Comment by 26345211** [comment]
i was using the method suggested by https://keras.io/guides/writing_a_training_loop_from_scratch/ because i need to control the batches, having different sizes for each train step, may i ask should the tape.gradient function return a list of Nones when passing a <class 'tensorflow.python.framework.ops.EagerTensor'> loss and the trainable weights, thanks

**Comment by bhack** [comment]
Try to print `tf.trainable_variables()`.

**Comment by 26345211** [comment]
[<tf.Variable 'dense_170/kernel:0' shape=(2, 200) dtype=float32, numpy=
array([[-0.11934789, -0.1352001 ,  0.15143515, -0.1664248 ,  0.08370231,
        -0.0574129 ,  0.04057987, -0.11563553,  0.08567913,  0.01829536,
        -0.12126006, -0.15800497, -0.02911088,  0.16553976,  0.09800433,
         0.149087  , -0.09987754,  0.11516781, -0.11730537,  0.14414169,
        -0.16216229,  0.0759239 , -0.0246084 ,  0.09173761,  0.14502476,
        -0.16168769, -0.17053609, -0.10016961, -0.1682262 ,  0.06890272,
         0.12712629,  0.09973384,  0.15260048, -0.14766552,  0.07615718,
         0.03655802, -0.00600314, -0.11907463, -0.04321401, -0.00364923,
        -0.02990401, -0.04188004,  0.04240695, -0.00858107, -0.03533657,
         0.08475854, -0.06375738, -0.14394803,  0.11829166,  0.13027205,
         0.03562872,  0.11894961,  0.13421594,  0.14814965,  0.07457224,
         0.09998365,  0.17004092, -0.11659545,  0.12831531, -0.04100744,
        -0.1044281 , -0.03507359, -0.12602231,  0.14934869, -0.01369838,
        -0.07268311,  0.00377378,  0.02297716, -0.03628358, -0.08242856,
        -0.07548593,  0.16678096,  0.10422631, -0.12451006,  0.09573375,
         0.1058668 , -0.01345657,  0.08683477, -0.07413413, -0.05021814,
         0.13835119,  0.13127823,  0.05542783,  0.09895901, -0.08051584,
         0.12203635,  0.10648994, -0.07792949, -0.14885972,  0.11363418,
         0.09021987,  0.03759827, -0.11419782, -0.14595217, -0.00871478,
        -0.0214756 , -0.01005411,  0.10152201,  0.0363231 , -0.05391209,
         0.14047246, -0.01496807, -0.03499922,  0.14476655, -0.0228022 ,
         0.0288797 ,  0.16593175,  0.12221389, -0.01039183, -0.06863403,
         0.15217276,  0.12026028,  0.07615587,  0.08128609, -0.04791162,
        -0.03509092, -0.04989045,  0.0875421 ,  0.05429304,  0.08238496,
        -0.13811164,  0.1360908 ,  0.03587066, -0.02798456,  0.08433725,
         0.05121964, -0.09319008, -0.02171211, -0.05205952,  0.04770884,
         0.01676673,  0.08286162,  0.11017866,  0.11852576,  0.14665104,
        -0.12999156, -0.14146811, -0.12743834, -0.00377761, -0.01454405,
        -0.11586215,  0.09552155, -0.06755261,  0.08772294, -0.17160678,
         0.16554986, -0.0599165 ,  0.16171281, -0.10038833, -0.1163206 ,
        -0.05406104,  0.02886513, -0.00667229, -0.06307232,  0.15343834,
        -0.12317878, -0.1617271 , -0.0965053 , -0.08161932,  0.06251732,
        -0.02203311, -0.01277681, -0.11201872,  0.04478924,  0.1330178 ,
         0.07984813,  0.06214549, -0.0318653 ,  0.01621217, -0.15752117,
         0.01456334, -0.05896328,  0.16608708, -0.10469592,  0.01082632,
         0.09841321,  0.07566023, -0.11623213, -0.16790162, -0.07444404,
         0.07748966,  0.0717774 , -0.03526573,  0.09977408, -0.1127055 ,
        -0.08577759, -0.15779656, -0.09698769, -0.01308313, -0.03118102,
        -0.0938562 ,  0.16747855,  0.1589102 , -0.04588754,  0.05656254,
         0.08696176, -0.08806266, -0.04132643,  0.06806661,  0.14456044],
       [-0.10428564, -0.15791386,  0.02120054,  0.11033089, -0.06676511,
         0.14481051, -0.0815791 , -0.11019517,  0.16783284,  0.07278715,
         0.01204659,  0.10498835, -0.03229962, -0.03176318, -0.06429406,
         0.13343503,  0.17106526, -0.0557727 ,  0.0828505 , -0.14933793,
         0.01169305, -0.0319875 ,  0.07549353, -0.01127364,  0.1226825 ,
         0.09658615,  0.06953707, -0.1346741 ,  0.16969268, -0.14627716,
         0.0014288 , -0.08763614, -0.16144164,  0.16214313,  0.17176618,
         0.01518376, -0.05609345, -0.05498549,  0.06774706,  0.07839967,
        -0.04208188, -0.10734637,  0.08433898,  0.09654813, -0.03963901,
         0.13249324,  0.08987449, -0.11276677,  0.02028385, -0.07729493,
        -0.00311604,  0.00111803, -0.09860735,  0.14777292, -0.14840819,
        -0.16552101, -0.01740001,  0.07162577,  0.05117765,  0.12964584,
         0.13930185, -0.16431916, -0.11170466, -0.0405774 , -0.01645522,
        -0.0211271 , -0.11903223, -0.08359186,  0.13136448, -0.1012122 ,
        -0.10399726,  0.15069433, -0.15947321,  0.07663617,  0.08661167,
        -0.06397992, -0.15692128,  0.16765158,  0.04610191,  0.14699821,
        -0.05399698,  0.00597455, -0.05686578,  0.06058389,  0.16753374,
         0.06940012, -0.13194956, -0.00995463,  0.004189  , -0.0857358 ,
         0.1268064 ,  0.0496822 ,  0.11057   ,  0.02427693, -0.08382649,
         0.03264667, -0.10066491,  0.09526803,  0.00589877,  0.1444508 ,
         0.04751974, -0.0185039 , -0.07235246, -0.15569532, -0.13325973,
         0.11971502, -0.12895551,  0.14561369, -0.04767046, -0.05738258,
        -0.03600778, -0.03899279, -0.11869541, -0.09502641,  0.07849739,
         0.07425387, -0.06586947, -0.12955034,  0.14531638,  0.15874003,
         0.08980124, -0.05513218, -0.04856721, -0.14975086, -0.15261206,
         0.03739762, -0.07880352,  0.08073036,  0.00023076,  0.08112435,
        -0.01473074, -0.05158723, -0.02684282, -0.00161324, -0.11474515,
        -0.06409728,  0.00597031,  0.02635483, -0.15490544, -0.00992393,
        -0.11707377,  0.10534434, -0.01435816, -0.13151708,  0.09501757,
         0.15055238,  0.01165627,  0.00938176, -0.11095423, -0.1229444 ,
        -0.05359643,  0.03379017, -0.15393159, -0.06208837, -0.03671506,
        -0.10619913, -0.12907328, -0.03056993, -0.06976721, -0.08462089,
         0.09103395,  0.05432582, -0.12622164,  0.1626849 , -0.08785553,
        -0.05476701,  0.06668425,  0.05976455, -0.14520708, -0.10134706,
        -0.09647678,  0.0860929 , -0.1499141 , -0.03556553,  0.1309581 ,
        -0.15902199, -0.10812031,  0.11185198,  0.05879991, -0.02932681,
         0.02434954,  0.13393985, -0.06720367, -0.1347403 ,  0.17149551,
         0.1492532 ,  0.01755236, -0.01293883,  0.05481164, -0.1531047 ,
         0.01992184,  0.06466942,  0.06392187,  0.10336344,  0.07975443,
         0.15884219, -0.16851538,  0.13306163, -0.01791409,  0.08858497]],
      dtype=float32)>, <tf.Variable 'dense_170/bias:0' shape=(200,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>, <tf.Variable 'dense_171/kernel:0' shape=(200, 160) dtype=float32, numpy=
array([[-0.01449096,  0.11891404,  0.08263467, ..., -0.08579256,
        -0.08509979, -0.00434957],
       [-0.04339363, -0.05501469,  0.09409983, ...,  0.04408891,
         0.02022919, -0.12373063],
       [-0.06650787,  0.04460543, -0.07150993, ...,  0.00240223,
         0.03154723, -0.05291989],
       ...,
       [-0.09521142,  0.00500374,  0.10540338, ..., -0.10856126,
        -0.09479183,  0.07833758],
       [ 0.05737944, -0.02785622,  0.10655414, ...,  0.12198822,
         0.01530035,  0.12406929],
       [-0.01402406,  0.01471251,  0.02110964, ...,  0.04371321,
        -0.01435061, -0.11811783]], dtype=float32)>, <tf.Variable 'dense_171/bias:0' shape=(160,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.], dtype=float32)>, <tf.Variable 'dense_172/kernel:0' shape=(160, 128) dtype=float32, numpy=
array([[ 0.04160011,  0.14410284, -0.07255455, ...,  0.06120677,
        -0.04498374,  0.05597709],
       [-0.06058273,  0.080964  , -0.00544643, ...,  0.027395  ,
         0.10751486,  0.13421553],
       [-0.02582756,  0.02726382, -0.07045017, ...,  0.08898853,
         0.08676286,  0.13659385],
       ...,
       [-0.0703565 , -0.08782355, -0.06662799, ...,  0.07700838,
        -0.0908928 ,  0.01814529],
       [-0.03862739,  0.01946414, -0.00362122, ..., -0.02184659,
         0.06519993,  0.09575835],
       [ 0.12136286,  0.12789068, -0.01524675, ...,  0.10884467,
        -0.10154472, -0.05638957]], dtype=float32)>, <tf.Variable 'dense_172/bias:0' shape=(128,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>, <tf.Variable 'dense_173/kernel:0' shape=(128, 102) dtype=float32, numpy=
array([[ 0.11994411, -0.08830806,  0.09730266, ..., -0.02735101,
        -0.11835159, -0.1292572 ],
       [-0.04823325, -0.10645641, -0.06589925, ..., -0.09688081,
         0.05347882,  0.14744021],
       [ 0.00104479,  0.00565375, -0.05909484, ...,  0.09337248,
        -0.03811433, -0.04787574],
       ...,
       [ 0.08004022, -0.00987501, -0.00712064, ...,  0.1572399 ,
        -0.12534381, -0.05836434],
       [ 0.1083601 ,  0.02383608, -0.13886343, ...,  0.08544815,
        -0.10386243,  0.06986031],
       [ 0.13212802, -0.08592711, -0.09173632, ..., -0.00902449,
         0.02533138,  0.09833591]], dtype=float32)>, <tf.Variable 'dense_173/bias:0' shape=(102,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>, <tf.Variable 'dense_174/kernel:0' shape=(102, 81) dtype=float32, numpy=
array([[-0.13250442, -0.11466676,  0.09851864, ..., -0.15670484,
         0.16924924, -0.17573619],
       [-0.08160742,  0.002113  ,  0.14913452, ..., -0.00202712,
        -0.07034627, -0.1408208 ],
       [-0.10016426,  0.1475001 , -0.08389228, ...,  0.10627356,
         0.00324109, -0.11617346],
       ...,
       [-0.00065637, -0.09371959, -0.06874178, ...,  0.12663746,
         0.06000863, -0.00193936],
       [ 0.04684326,  0.10960776, -0.02201189, ..., -0.1663261 ,
        -0.02349019, -0.08495095],
       [-0.15987751, -0.05693918,  0.03338403, ..., -0.14821112,
         0.0755958 ,  0.12068567]], dtype=float32)>, <tf.Variable 'dense_174/bias:0' shape=(81,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>, <tf.Variable 'dense_175/kernel:0' shape=(81, 65) dtype=float32, numpy=
array([[-0.02078907, -0.0187443 ,  0.14361703, ..., -0.08362422,
        -0.10623015, -0.11473078],
       [-0.01310347,  0.04681331, -0.18914118, ...,  0.03470579,
        -0.09747564, -0.05477503],
       [ 0.1440683 , -0.0049884 , -0.10156316, ...,  0.1902642 ,
        -0.06114322,  0.11446577],
       ...,
       [-0.10218544, -0.1603615 ,  0.01736538, ..., -0.09153688,
        -0.19702204,  0.02647094],
       [-0.03277858, -0.01679772, -0.10808269, ...,  0.00512141,
         0.18170598, -0.1633698 ],
       [-0.04154885,  0.11578539,  0.09879005, ..., -0.07965922,
        -0.20085736,  0.0203298 ]], dtype=float32)>, <tf.Variable 'dense_175/bias:0' shape=(65,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>, <tf.Variable 'dense_176/kernel:0' shape=(65, 52) dtype=float32, numpy=
array([[-0.06344108, -0.11232378, -0.20549749, ..., -0.15604648,
         0.02152152,  0.09581529],
       [-0.14496394,  0.0125726 , -0.06720552, ..., -0.09541251,
         0.12769593, -0.14659809],
       [-0.1349557 ,  0.02857833, -0.05722477, ..., -0.17551786,
         0.13835962,  0.10340054],
       ...,
       [ 0.07086708, -0.17986119,  0.05870135, ..., -0.05127212,
         0.04822843,  0.01309113],
       [-0.10938089, -0.05535942,  0.17507245, ...,  0.05741088,
         0.10420044, -0.05306868],
       [ 0.0470479 ,  0.02511998, -0.08551997, ..., -0.13162914,
        -0.17675096, -0.00280182]], dtype=float32)>, <tf.Variable 'dense_176/bias:0' shape=(52,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.], dtype=float32)>, <tf.Variable 'dense_177/kernel:0' shape=(52, 41) dtype=float32, numpy=
array([[ 0.24056605,  0.13016745,  0.24860209, ..., -0.10263579,
        -0.22992235,  0.23266497],
       [ 0.0291594 , -0.14026415, -0.02536179, ...,  0.17263454,
         0.09796062, -0.11340095],
       [ 0.04632729,  0.12658027,  0.02941811, ...,  0.24071139,
        -0.07859647, -0.1329661 ],
       ...,
       [-0.16441944, -0.23054132,  0.01691437, ..., -0.07269198,
        -0.02200401, -0.11094089],
       [ 0.08670676, -0.1425199 ,  0.18649909, ...,  0.10516405,
        -0.12943657, -0.08731034],
       [-0.06016003,  0.01989737, -0.00507528, ..., -0.21756603,
        -0.21989025, -0.05852264]], dtype=float32)>, <tf.Variable 'dense_177/bias:0' shape=(41,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.], dtype=float32)>, <tf.Variable 'dense_178/kernel:0' shape=(41, 33) dtype=float32, numpy=
array([[ 0.2551451 , -0.08163103,  0.09458616, ...,  0.01688999,
         0.0630509 , -0.20163739],
       [-0.2597019 , -0.04386258, -0.25949702, ...,  0.10323077,
        -0.280416  ,  0.19154406],
       [ 0.1360192 ,  0.13865757,  0.02848551, ...,  0.05804026,
         0.04214838, -0.23099662],
       ...,
       [ 0.22179797, -0.01286918,  0.00865653, ...,  0.16882607,
        -0.21707624,  0.2337515 ],
       [-0.25272235,  0.16974998, -0.12176448, ..., -0.2271406 ,
        -0.21278402, -0.23659456],
       [ 0.27495125,  0.14714894, -0.20009963, ...,  0.20196095,
         0.23976043,  0.05757129]], dtype=float32)>, <tf.Variable 'dense_178/bias:0' shape=(33,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>, <tf.Variable 'dense_179/kernel:0' shape=(33, 1) dtype=float32, numpy=
array([[ 0.36110505],
       [-0.31218484],
       [-0.07384148],
       [ 0.04206073],
       [-0.24719031],
       [ 0.351539  ],
       [ 0.06218505],
       [-0.07741374],
       [ 0.09920397],
       [-0.14365393],
       [ 0.14466831],
       [-0.3287453 ],
       [-0.06388441],
       [ 0.11404553],
       [ 0.07901695],
       [-0.40070096],
       [-0.01842627],
       [ 0.30787864],
       [ 0.3694426 ],
       [ 0.00287768],
       [-0.3958364 ],
       [ 0.24366245],
       [ 0.26944283],
       [-0.26299012],
       [ 0.16940388],
       [-0.16430134],
       [-0.16894057],
       [-0.40945658],
       [ 0.35159257],
       [-0.02541405],
       [-0.3427515 ],
       [ 0.14129457],
       [-0.1145269 ]], dtype=float32)>, <tf.Variable 'dense_179/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

The obj above is the model.trainable_variables
passing it to grads = tape.gradient(loss_value, model.trainable_variables) also results in Nones, thanks

**Comment by bhack** [comment]
I think It Is better that you post your model on stackoverflow.
In the meantime you can also try ti fix in your custom loss:
```
/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:966: SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame. Try using .loc[row_indexer,col_indexer] = value instead See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy self.obj[item] = s
```

**Comment by aryanchugh816** [comment]
Were you able to figure out the solution ??
