### ISSUE TITLE
Inference time almost 5x SLOWER than Pytorch Same Model

### ISSUE THREAD

**Issue by charlielito** [tensorflow/tensorflow#42989]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian GNU/Linux 9.12 (stretch)
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.7.6
- CUDA/cuDNN version: 10.1.243/7.6.5
- GPU model and memory: 1 x NVIDIA Tesla P4
- Pytorch version: 1.5.0

**Describe the current behavior**
I am implementing this [paper](https://arxiv.org/pdf/2004.02147.pdf) and found an existing implementation in Pytorch. So I ported the exact model to tensorflow with the keras api. Nonetheless, the inference time is almost 5x slower when running inference on GPU for the tensorflow version. I tested with the tesla P4 but also on a NVIDIA Xavier AGX and got same results (5 times slower). What am I missing? :s

I got the following results:
pytorch: 82.5 FPS 12.11 ms
tensorflow: 20 FPS 49.9 ms

**Describe the expected behavior**
If you check the code, it refers to the same architecture and number of parameters, one would expect similar running times.

**Standalone code to reproduce the issue**
You can check both pytorch and tensorflow implementation in this repo https://github.com/charlielito/test, and test the speed with:
```
python bisenetv2_tensorflow.py
```
```
python bisenetv2_torch.py
```

**Comment by bhack** [comment]
Have you tried to profilo your model: https://www.tensorflow.org/guide/profiler ?

**Comment by charlielito** [comment]
**Update**: I was calling the model with `model(image)`, but when wrapped with a tf.function (`mode=tf.function(model)` ) it runs now way faster (around 69 FPS), but still slower than pytorch

**Comment by bhack** [comment]
I suggest you to profile your model with the Tensorflow tool and with the Pytorch one with https://pytorch.org/tutorials/recipes/recipes/profiler.html.

**Comment by charlielito** [comment]
I notice that `grouped` convolutions are new in tensorflow 2.3.0. I used that because the original pytorch implementation uses that for implementing depthwise separable convolutions. Nonetheless, I replaced all grouped convolution with the corresponding ` tf.keras.layers.DepthwiseConv2D` and with that I got comparable results, even faster than pytorch! I you want to check in the mentioned repo the implementation is in `bisenetv2_tensorflow_depthconv.py`.
**Recap**
Pytorch: 82.5 FPS
Tensorflow: 57 FPS
Tensorflow with DepthwiseConv2D: 92 FPS

Is the new grouped convolution implementation somehow not optimal?

**Comment by Leslie-Fang** [comment]
How about the accuracy? Did you need to fine-tune the model?

**Comment by lyonguyen8697** [comment]
I think you should call `model.predict(image)` for inference instead of `model(image)` that returns a `Tensor` causing some overheat

**Comment by charlielito** [comment]
@Leslie-Fang I haven't trained it yet, so I don't know. Nonetheless, because it is exactly the same model I expect comparable accuracy results. No need of fine tuning.

@lyonguyen8697 I think I forgot to mention it, but I am testing with batch_size=1, and as the [docs](https://www.tensorflow.org/api_docs/python/tf/keras/Model#predict) says: "using __call__ is recommended for faster execution"

**Comment by bhack** [comment]
@charlielito Can you test the performance with  `pip install tf_nighlty`?

**Comment by bhack** [comment]
Cause on nightly on your model we have a more explicit:

>UnimplementedError:  Fused conv implementation does not support grouped convolutions for now.
	 [[node BiSeNetV2/segment_branch_2/sequential_78/ge_layer_s2_6/sequential_75/batch_normalization_132/FusedBatchNormV3 (defined at <ipython-input-2-ffb1581d5ded>:206) ]] [Op:__inference_function_21059]

**Comment by charlielito** [comment]
@bhack  just tested the latest version of `tf_nightly` and it runs way faster. Now the same implementation matches pytorch with ~83 FPS (grouped convolutions). I had to use CUDA 11 though, and couldn't test pytorch because there are not pre-built packages for that version of CUDA. So my guess is that in  `tf_nightly` the grouped convolutions performance was improved?
I think the issue is resolved

**Comment by bhack** [comment]
If your code was quite the same yes. I think you can close this and eventually reopen or just comment when you have a new run with pytorch/CUDA 11
