### ISSUE TITLE
Loading a TF1 Protocol buffer does not work in TF versions 2.2.0 and above

### ISSUE THREAD

**Issue by VSZM** [tensorflow/tensorflow#42980]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux 4.19.112+** and **Windows 10**
- TensorFlow version (use command below): **v2.2.0-rc4-8-g2b96f3662b 2.2.0** and **v2.3.0-0-gb36436b087 2.3.0**
- Python version: **3.6.9**
- CUDA/cuDNN version: **CUDA disabled**
- GPU model and memory: **GPU disabled**

**Describe the current behavior**

Model trained with Tensorflow 1 and saved with the [tf.saved_model.simple_save](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/saved_model/simple_save) can't be loaded with Tensorflow 2.2.0 and above using [tf.saved_model.load](https://www.tensorflow.org/api_docs/python/tf/saved_model/load). The same code works perfectly well with Tensorflow 2.1.1. 

The error I get in TF 2.2.0 and above:

```
<ipython-input-3-fa86b40288e8> in <module>()
----> 1 model_loaded = tf.saved_model.load('tensorflow_model/')
      2 model_loaded = model_loaded.signatures['serving_default']

/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load.py in load(export_dir, tags, options)
    601     ValueError: If `tags` don't match a MetaGraph in the SavedModel.
    602   """
--> 603   return load_internal(export_dir, tags, options)
    604 
    605 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load.py in load_internal(export_dir, tags, options, loader_cls)
    647   else:
    648     with ops.init_scope():
--> 649       root = load_v1_in_v2.load(export_dir, tags)
    650       root.graph_debug_info = debug_info
    651   return root

/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load_v1_in_v2.py in load(export_dir, tags)
    261   """Load a v1-style SavedModel as an object."""
    262   loader = _EagerSavedModelLoader(export_dir)
--> 263   return loader.load(tags=tags)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load_v1_in_v2.py in load(self, tags)
    207     wrapped = wrap_function.wrap_function(
    208         functools.partial(self.load_graph, load_graph_returns, meta_graph_def),
--> 209         signature=[])
    210     saver, = load_graph_returns
    211     restore_from_saver = self._extract_saver_restore(wrapped, saver)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/wrap_function.py in wrap_function(fn, signature, name)
    626           signature=signature,
    627           add_control_dependencies=False,
--> 628           collections={}),
    629       variable_holder=holder,
    630       signature=signature)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    984         _, original_func = tf_decorator.unwrap(python_func)
    985 
--> 986       func_outputs = python_func(*func_args, **func_kwargs)
    987 
    988       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/wrap_function.py in __call__(self, *args, **kwargs)
     85 
     86   def __call__(self, *args, **kwargs):
---> 87     return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
     88 
     89   def call_with_variable_creator_scope(self, fn):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/wrap_function.py in wrapped(*args, **kwargs)
     91     def wrapped(*args, **kwargs):
     92       with variable_scope.variable_creator_scope(self.variable_creator_scope):
---> 93         return fn(*args, **kwargs)
     94 
     95     return wrapped

/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load_v1_in_v2.py in load_graph(self, returns, meta_graph_def)
     88     # pylint: disable=protected-access
     89     saver, _ = tf_saver._import_meta_graph_with_return_elements(
---> 90         meta_graph_def)
     91     # pylint: enable=protected-access
     92     returns[0] = saver

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py in _import_meta_graph_with_return_elements(meta_graph_or_file, clear_devices, import_scope, return_elements, **kwargs)
   1484           import_scope=import_scope,
   1485           return_elements=return_elements,
-> 1486           **kwargs))
   1487 
   1488   saver = _create_saver_from_imported_meta_graph(meta_graph_def, import_scope,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/meta_graph.py in import_scoped_meta_graph_with_return_elements(meta_graph_or_file, clear_devices, graph, import_scope, input_map, unbound_inputs_col_name, restore_collections_predicate, return_elements)
    797         input_map=input_map,
    798         producer_op_list=producer_op_list,
--> 799         return_elements=return_elements)
    800 
    801     # TensorFlow versions before 1.9 (not inclusive) exported SavedModels

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py in new_func(*args, **kwargs)
    505                 'in a future version' if date is None else ('after %s' % date),
    506                 instructions)
--> 507       return func(*args, **kwargs)
    508 
    509     doc = _add_deprecated_arg_notice_to_docstring(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py in import_graph_def(***failed resolving arguments***)
    403       return_elements=return_elements,
    404       name=name,
--> 405       producer_op_list=producer_op_list)
    406 
    407 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py in _import_graph_def_internal(graph_def, input_map, return_elements, validate_colocation_constraints, name, producer_op_list)
    499       except errors.InvalidArgumentError as e:
    500         # Convert to ValueError for backwards compatibility.
--> 501         raise ValueError(str(e))
    502 
    503     # Create _DefinedFunctions for any imported functions.

ValueError: Node 'loss/gradients/model/batch_normalization_3/FusedBatchNormV3_1_grad/FusedBatchNormGradV3' has an _output_shapes attribute inconsistent with the GraphDef for output #3: Dimension 0 in both shapes must be equal, but are 0 and 64. Shapes are [0] and [64].
```

**Describe the expected behavior**

Models should be loaded regardless of TF2 version. 

**Standalone code to reproduce the issue**

[Colab notebook to reproduce issue](https://colab.research.google.com/drive/18IWxx-eppX2Sjoo2h1hGe0TzCHNiykF1?usp=sharing)

**Other info / logs** 

Although this should be enough information to reproduce the issue there are even more details in the [Stackoverflow question](https://stackoverflow.com/questions/63656778/how-to-load-a-trained-tf1-protobuf-model-into-tf2) I created.

**Please provide a workaround in the latest Tensorflow version if possible as I have to use this model in an environment where I am constrained to the latest Tensorflow version.**

**Comment by ravikyram** [comment]
I have tried in colab with TF 2.1.1 and i am not able to see any issue. I could reproduce the issue with TF 2.3, nightly versions(`2.4.0-dev20200906`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/26b939ddd8c497c148479478fca3e23e/untitled312.ipynb). Thanks!

**Comment by dellis23** [comment]
@VSZM 

I believe [this](https://github.com/tensorflow/tensorflow/commit/84f2ec1d60b5bb14a59ccef8f8fa7eb5a1096e8f) commit broke backwards compatibility with the op in question.  I've passed the bug along to the relevant maintainers, though I don't have a estimate on when they might be able to take a look.

In the meantime, you mention you mostly just need a workaround.  My reading of the code is that the outputs in question are actually just reserved placeholders that aren't really in use.  As such, I tried modifying your model directly to make the output size compatible, and it seems to load.  I will reach out to you privately to send you the fixed model.

If you'd like to make the modification yourself, I modified the fourth output (`3` when zero indexing) of the failing node (`"loss/gradients/model/batch_normalization_3/FusedBatchNormV3_1_grad/FusedBatchNormGradV3"`) to change the shape dimension size from `64` to `0` (the exact path on the node is `attr["_output_shapes'][3].shape.dim.size`).

If this doesn't work, we'll unfortunately have to wait for a proper fix.

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tensorflow 2.5, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/40f53ec0075665274660838b8886f444/42980.ipynb). Thanks!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by dellis23** [comment]
I did a great job on this one.
