### ISSUE TITLE
ValueError: Tensor-typed variable initializers must either be wrapped in an init_scope or callable In TPU stragegy

### ISSUE THREAD

**Issue by weichen456** [tensorflow/tensorflow#42997]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version: No
- GPU model and memory: No

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I use add_weight function to add variable to model In TPU strategy but it shows that /usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    256       except Exception as e:  # pylint:disable=broad-except
    257         if hasattr(e, 'ag_error_metadata'):
--> 258           raise e.ag_error_metadata.to_exception(e)
    259         else:
    260           raise

ValueError: in user code:

    <ipython-input-6-cf880f69ac70>:38 call  *
        target_feat = self.build_(parents)
    <ipython-input-6-cf880f69ac70>:26 build_  *
        parent_weights = [tf.nn.relu(tf.cast(self.add_weight(initializer = tf.ones_initializer(), name='block{}_fusion{}'.format(1, j)), dtype=dtype)) for j in range(len(parents))]
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py:614 add_weight  **
        caching_device=caching_device)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/base.py:750 _add_variable_with_custom_getter
        **kwargs_for_getter)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_utils.py:145 make_variable
        shape=variable_shape if variable_shape else None)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py:260 __call__
        return cls._variable_v1_call(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py:221 _variable_v1_call
        shape=shape)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py:67 getter
        return captured_getter(captured_previous, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2024 creator_with_resource_vars
        created = self._create_variable(next_creator, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/tpu_strategy.py:870 _create_variable
        **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_utils.py:291 create_mirrored_variable
        value_list = real_mirrored_creator(**kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/tpu_strategy.py:861 _real_mirrored_creator
        v = next_creator(**kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py:199 <lambda>
        previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py:2597 default_variable_creator
        shape=shape)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py:264 __call__
        return super(VariableMetaclass, cls).__call__(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py:1518 __init__
        distribute_strategy=distribute_strategy)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py:1601 _init_from_args
        raise ValueError("Tensor-typed variable initializers must either be "

    ValueError: Tensor-typed variable initializers must either be wrapped in an init_scope or callable (e.g., `tf.Variable(lambda : tf.truncated_normal([10, 40]))`) when building functions. Please file a feature request if this restriction inconveniences you.
**Describe the expected behavior**
Can successful add new variable to model.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
The standalone code can be see here https://colab.research.google.com/drive/1GB_kujPR2Mu8iayBuglmbB8ylfGh_YYk?usp=sharing, this code can sucessful run in GPU, CPU, but get error in TPU.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@weichen456 
Please provide with simple stand alone code for us to replicate the issue faced or if possible share a colab gist with the error reported.
With respect to error shared, please refer to:
#36436 #41306

**Comment by weichen456** [comment]
> @weichen456
> Please provide with simple stand alone code for us to replicate the issue faced or if possible share a colab gist with the error reported.
> With respect to error shared, please refer to:
> #36436 #41306 [link](https://stackoverflow.com/questions/59229898/tensor-typed-variable-initializers-must-either-be-wrapped-in-an-init-scope-or-ca)

The stand alone code can be seen [here ](https://colab.research.google.com/drive/1GB_kujPR2Mu8iayBuglmbB8ylfGh_YYk?usp=sharing)

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/f6f09a6da1c88c3b582e849bfd694462/untitled407.ipynb)

**Comment by nikitamaia** [comment]
Hi @weichen456, in the gist you provided the second cell executes without error. Is that a suitable workaround for you?

**Comment by weichen456** [comment]
> Hi @weichen456, in the gist you provided the second cell executes without error. Is that a suitable workaround for you?
Yes,  it is a suitable workaround. Thank you!

**Comment by nikitamaia** [comment]
Great, closing this issue now since you found a workaround. Feel free to reopen if you still feel this is unresolved.
