### ISSUE TITLE
Micro speech example not working on Sparkfun Edge

### ISSUE THREAD

**Issue by PHANzgz** [tensorflow/tensorflow#42995]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution: Windows 10 Home 64-bit
- Console: Git Bash
- GNU Make 4.3
- TensorFlow installed from (source or binary): (Doesn't apply)
- Tensorflow version: (Doesn't apply)
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Sparkfun Edge

**Describe the problem**
I'm trying to deploy the [micro speech example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/micro_speech) to my Sparkfun edge, and although it compiles, links and flashes correctly, the behavior is wrong. It does not recognize any commands and just flashes the "unknown" word LED and sometimes the "no" word LED, regardless of what you say. I've done exactly as the wiki explains. I've tried deploying to Arduino and I've had no problem.

**Please provide the exact sequence of commands/steps when you ran into the problem**
I've carefully followed the steps on [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/micro_speech#deploy-to-sparkfun-edge) but I'll try everything one more time as I write this issue:

Clone trensorflow repo
`$ git clone https://github.com/tensorflow/tensorflow.git`
`$ cd tensorflow`

Compile the binary
`$ make -f tensorflow/lite/micro/tools/make/Makefile TARGET=sparkfun_edge TAGS="cmsis-nn" micro_speech_bin`

Sign the binary
```
$ cp tensorflow/lite/micro/tools/make/downloads/AmbiqSuite-Rel2.2.0/tools/apollo3_scripts/keys_info0.py \
tensorflow/lite/micro/tools/make/downloads/AmbiqSuite-Rel2.2.0/tools/apollo3_scripts/keys_info.py
```

```
$ python3 tensorflow/lite/micro/tools/make/downloads/AmbiqSuite-Rel2.2.0/tools/apollo3_scripts/create_cust_image_blob.py \
--bin tensorflow/lite/micro/tools/make/gen/sparkfun_edge_cortex-m4/bin/micro_speech.bin \
--load-address 0xC000 \
--magic-num 0xCB \
-o main_nonsecure_ota \
--version 0x0
```

```
$ python3 tensorflow/lite/micro/tools/make/downloads/AmbiqSuite-Rel2.2.0/tools/apollo3_scripts/create_cust_wireupdate_blob.py \
--load-address 0x20000 \
--bin main_nonsecure_ota.bin \
-i 6 \
-o main_nonsecure_wire \
--options 0x1
```
Flash the binary
`export DEVICENAME=COM11`
`export BAUD_RATE=921600`

Now, with the board on boot mode(holding button `14` and press reset, and still holding `14`)
```
python3 tensorflow/lite/micro/tools/make/downloads/AmbiqSuite-Rel2.2.0/tools/apollo3_scripts/uart_wired_update.py \
-b ${BAUD_RATE} ${DEVICENAME} \
-r 1 \
-f main_nonsecure_wire.bin \
-i 6
```
It flashes correctly(output from the console):
```
...
Sending Data Packet of length  1468
Sending Reset Command.
Done.
```
When I try the program, saying some commands, the board just keeps flashing the blue LED("unknown word") and sometimes the red LED("no" word), no matter what I say. The room is quiet and I've tried different tones and volumes, no luck. At first I thought I had faulty hardware but I actually bought two boards and both show the same behavior. The Arduino version works fine for me on the Nano 33 BLE board, so I guess it has to be related to the Sparkfun Edge implementation, but I could not find the issue. Here is some output from the serial port when I'm issuing the commands:

```
Apollo3 Burst Mode is Available

Apollo3 operating in Burst Mode (96MHz)

Heard no (231) @256ms
Heard unknown (203) @5568ms
Heard unknown (202) @9472ms
Heard unknown (201) @14208ms
Heard unknown (201) @16128ms
Heard unknown (224) @17664ms
Heard no (208) @23424ms
Heard unknown (201) @26688ms
Heard unknown (207) @44800ms
```

**Comment by wangtz** [comment]
Hi Enrique,

>  The Arduino version works fine for me on the Nano 33 BLE board

It's expected that the speech command demo works much better on Arduino board which has a better (Digital) mic. 

On SparkFunEdge board, to make it easier for the board to recognize your sound, maybe try to repeat "yes" several times like "yes yes yes".
