### ISSUE TITLE
Go implementation does not provide SummaryImage/SummaryAudio

### ISSUE THREAD

**Issue by mattn** [tensorflow/tensorflow#42998]
**System information**
- Master branch of tensorflow/tensorflow latest. bb49eafc080caf205d5ba4478d9c93552ce46d57
- Windows 10

**Describe the current behavior**

I can not decode bitmap to tensor on Go.

```go
func decodeBitmapGraph() (*tf.Graph, tf.Output, tf.Output, error) {
	s := op.NewScope()
	input := op.Placeholder(s, tf.String)
	output := op.ExpandDims(
		s,
		op.DecodeBmp(s, input, op.DecodeBmpChannels(3)),
		op.Const(s.SubScope("make_batch"), int32(0)))
	graph, err := s.Finalize()
	return graph, input, output, err
}
```

**Describe the expected behavior**

This code did work correctly in Go 1.5 or later. But latest tensorflow does not. Probably, you provide SummaryImage to manipulate images for TF_STRING. But Go does not provide APIs for that.

*EDIT*

Current implementation return

>error making input tensor: Malformed TF_STRING tensor; element 0 out of range

**Comment by Saduf2019** [comment]
@mattn 
Could you please verify this on latest version of tf and let us know.

**Comment by mattn** [comment]
I confirmed latest version fix this issue.
