### ISSUE TITLE
tensorflow-0.8.0-cp27-none-linux_86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by KeithYin** [tensorflow/tensorflow#4299]
I encounted this issue when trying to install the tensorflow on mine Ubuntu system. here is the details of my system.
Linux ... 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by aselle** [comment]
"tensorflow-0.8.0-cp27-none-linux_86_64.whl"
in your title implies the file is missing an x. Post the whl filename that you downloaded. Also, 0.8 is an old version try 0.10rc1 or 0.9.
