### ISSUE TITLE
tflite(micro) pointer-arithmetic overflow left unhandled in TfLiteStatus SimpleMemoryAllocator::EnsureHeadSize

### ISSUE THREAD

**Issue by andrewstevens-infineon** [tensorflow/tensorflow#42999]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (SHA-1): 44dbace063796ea99c5b3d27a3a5810048d5096c

**Describe the current behavior**

The current implementation the check for an already-sufficient Head area in `SimpleMemoryAllocator::EnsureHeadSize` will fail due to a pointer-arithmetic overflow if the arena is allocated close to highest address and a large head size is requested resulting.

```
  if (aligned_result + size < head_) {
    // Size is below the current head size, just return.
    return kTfLiteOk;
  }
```

The overflowed pointer aligned_result + size will be below head_ causing a false kTfliteOk return rather than failing.
The Bug showed compiling tflite(u) test  for RISCV 32-bit using gcc-9 with default settings using the [RISCV GNU toolchain](https://github.com/riscv/riscv-gnu-toolchain) and executing on a semi-hosting simulator (whisper).    The test fails as in target environment a small arena is allocated on the stack very high in memory with a size large enough to overflow aligned_result + size.

**Describe the expected behavior**

The overflow case has to be handled.   The fix in our local fork is

 ```
 ptrdiff_t aligned_head_head_diff = head_-aligned_result;
 if (aligned_head_head_diff >=0 && size < static_cast<size_t>(aligned_head_head_diff)) {
    // Size is below the current head size, just return.
    return kTfLiteOk;
  }
```

**Standalone code to reproduce the issue**

Add to recording_simple_memory_allocator_test

```
TF_LITE_MICRO_TEST(DemonstrateOverflow) {
  constexpr size_t arena_size = 1024;
  uint8_t *arena = reinterpret_cast<uint8_t *>(-arena_size);
  tflite::RecordingSimpleMemoryAllocator allocator(micro_test::reporter, arena,
                                                   arena_size);

  TF_LITE_MICRO_EXPECT_EQ(
      kTfLiteError, allocator.EnsureHeadSize(/*size=*/2048, /*alignment=*/1));
}
```

**Comment by advaitjain** [comment]
Thanks for the bug report.

For future reference, if you make a [TensorFlow Lite for Microcontrollers Issue](https://github.com/tensorflow/tensorflow/issues/new?labels=comp%3Amicro&template=70-tflite-micro-issue.md) from the different available templates, it will get routed to the micro team much faster.

@nkreeger what do you think of the proposed fix?

**Comment by sushreebarsa** [comment]
@andrewstevens-infineon Could you try with the latest TF version as older versions are not actively supported and refer to [this](https://www.tensorflow.org/lite/microcontrollers) guide.  Please let us know if it helps? Thank you!

**Comment by andrewstevens-infineon** [comment]
World has moved on since 2021 ;-).    Test seem to work fine on on our current local tflite-micro (based on 2022-10-18 nightly) the patch was discarded during rebasing (EnsureHeadSize no longer exists).
