### ISSUE TITLE
Cuda Library not found

### ISSUE THREAD

**Issue by vaibhav-75007** [tensorflow/tensorflow#42992]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 8.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Installed using PIP in a Conda environment
- TensorFlow version: 2.3.0
- Python version:- Installed using virtualenv? pip? conda?: Installed using PIP in a Conda environment
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the problem**
I don't have a GPU in my Laptop. I installed tensorflow using Pip inside a Conda Environment.
The command that I used to install it was -
```bash
pip install tensorflow
```
And I opened a Python Shell inside the CMD by typing
```bash
python
```
and I typed
```python
>>> import tensorflow
```
and I got this error -
![image](https://user-images.githubusercontent.com/52103891/92318272-3d3cb180-f027-11ea-8f4b-d4b26079db98.png)

But when I tried to print out the version, using
```python
print(tensorflow.__version__)
```
the output was -
![image](https://user-images.githubusercontent.com/52103891/92318285-8987f180-f027-11ea-89c7-8477f295ca87.png)

Please tell me whether I should Ignore this,
I know that the error is telling to Ignore if you don't have a GPU in you PC.
But whenever I import it it is throwing this Error

This is the Exact sequence of command that I used
![image](https://user-images.githubusercontent.com/52103891/92318320-1f238100-f028-11ea-8034-7a12d307ce3d.png)

I also tried the same in Pycharm, By setting the same above used python interpreter. But it is also showing the same error
```
E:\Anaconda3\envs\tensorflow\pythonw.exe E:/Robotics/python/ML(techwithtim)/tensorflowEnv/test.py
2020-09-05 23:13:00.132025: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-09-05 23:13:00.132610: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

Process finished with exit code 0
```

![image](https://user-images.githubusercontent.com/52103891/92318380-4038a180-f029-11ea-8706-cf931586c50a.png)

And I followed this Tutorial for the Installation and Setup -
https://www.youtube.com/watch?v=ujTCoH21GlA

**Comment by vaibhav-75007** [comment]
> _Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template_
> 
> **System information**
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 8.1
> * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
> * TensorFlow installed from (source or binary): Installed using PIP in a Conda environment
> * TensorFlow version: 2.3.0
> * Python version:- Installed using virtualenv? pip? conda?: Installed using PIP in a Conda environment
> * Bazel version (if compiling from source): None
> * GCC/Compiler version (if compiling from source): None
> * CUDA/cuDNN version: None
> * GPU model and memory: None
> 
> **Describe the problem**
> I don't have a GPU in my Laptop. I installed tensorflow using Pip inside a Conda Environment.
> The command that I used to install it was -
> 
> ```shell
> pip install tensorflow
> ```
> 
> And I opened a Python Shell inside the CMD by typing
> 
> ```shell
> python
> ```
> 
> and I typed
> 
> ```python
> >>> import tensorflow
> ```
> 
> and I got this error -
> ![image](https://user-images.githubusercontent.com/52103891/92318272-3d3cb180-f027-11ea-8f4b-d4b26079db98.png)
> 
> But when I tried to print out the version, using
> 
> ```python
> print(tensorflow.__version__)
> ```
> 
> the output was -
> ![image](https://user-images.githubusercontent.com/52103891/92318285-8987f180-f027-11ea-89c7-8477f295ca87.png)
> 
> Please tell me whether I should Ignore this,
> I know that the error is telling to Ignore if you don't have a GPU in you PC.
> But whenever I import it it is throwing this Error
> 
> This is the Exact sequence of command that I used
> ![image](https://user-images.githubusercontent.com/52103891/92318320-1f238100-f028-11ea-8034-7a12d307ce3d.png)
> 
> I also tried the same in Pycharm, By setting the same above used python interpreter. But it is also showing the same error
> 
> ```
> E:\Anaconda3\envs\tensorflow\pythonw.exe E:/Robotics/python/ML(techwithtim)/tensorflowEnv/test.py
> 2020-09-05 23:13:00.132025: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
> 2020-09-05 23:13:00.132610: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
> 
> Process finished with exit code 0
> ```
> 
> ![image](https://user-images.githubusercontent.com/52103891/92318380-4038a180-f029-11ea-8706-cf931586c50a.png)
> 
> And I followed this Tutorial for the Installation and Setup -
> https://www.youtube.com/watch?v=ujTCoH21GlA

**Comment by amahendrakar** [comment]
@vaibhav-75007,
Yes, you can safely ignore these GPU related logs. 

If you want to disable these logs, please change the log level using the below code. 
```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 
import tensorflow as tf
```
Thanks!

**Comment by vaibhav-75007** [comment]
Should i add that Lines of code in all of my Projects, or just once

**Comment by vaibhav-75007** [comment]
> @vaibhav-75007,
> Yes, you can safely ignore these GPU related logs.
> 
> If you want to disable these logs, please change the log level using the below code.
> 
> ```
> import os
> os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 
> import tensorflow as tf
> ```
> 
> Thanks!

Should I include that line of code in all of my projects??
Kindly reply

**Comment by vaibhav-75007** [comment]
But should I add this line of code I. My every project with tensorflow??

**Comment by vaibhav-75007** [comment]
> @vaibhav-75007,
> Yes, you can safely ignore these GPU related logs.
> 
> If you want to disable these logs, please change the log level using the below code.
> 
> ```
> import os
> os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 
> import tensorflow as tf
> ```
> 
> Thanks!

should i add this line off code in all my projects?? @amahendrakar .
Please reply

**Comment by vaibhav-75007** [comment]
`i am iron man`

**Comment by amahendrakar** [comment]
@vaibhav-75007,
Yes, you'll have to add the code snippet to your projects. Alternatively, you can install the TensorFlow CPU package using the below command. 

`pip install tensorflow-cpu`

Thanks!
