### ISSUE TITLE
Error when build the pip package for Tensorflow 1.8

### ISSUE THREAD

**Issue by YuyangLeng** [tensorflow/tensorflow#43004]
Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow):No
    OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 18.04
    TensorFlow installed from (source or binary):Source
    TensorFlow version (use command below):1.8
    Python version:2.7.17/3.6.9
    Bazel version (if compiling from source):0.10.0
    GCC/Compiler version (if compiling from source):Tried 6.5, 5.5
    CUDA/cuDNN version: 9.0/7.6.5
    GPU model and memory:GTX 1080

ERROR: /home/yuyangleng/tensorflow/tensorflow/contrib/framework/BUILD:101:1: output 'tensorflow/contrib/framework/_objs/python/ops/_variable_ops_gpu/tensorflow/contrib/framework/kernels/zero_initializer_op_gpu.cu.pic.o' was not created

ERROR: /home/yuyangleng/tensorflow/tensorflow/contrib/framework/BUILD:101:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 79.510s, Critical Path: 9.19s
FAILED: Build did NOT complete successfully

**Comment by amahendrakar** [comment]
@YuyangLeng,
TensorFlow 1.x is not actively supported. Could you please try building TensorFlow 2.x and check if you are facing the same issue. 

Also, make sure you have all the required dependencies installed as per the [tested build configurations](https://www.tensorflow.org/install/source#cpu). Thanks!
