### ISSUE TITLE
Tensorflow problem in Python 3.6

### ISSUE THREAD

**Issue by chipxx** [tensorflow/tensorflow#43000]
Hi, I have installed these packages, pip list,
but python 3.6 tells me it takes tensorflow 2.2 or higher, but here it is installed!
I don't know what's wrong...
In the Python 3.6 shell when I enter "import keras" or "import tensorflow" it gives me an error.
Thanks for your help.
ric

- C:\>pip list
Package                Version
---------------------- ---------
absl-py                0.10.0
astunparse             1.6.3
cachetools             4.1.1
certifi                2020.6.20
chardet                3.0.4
cycler                 0.10.0
gast                   0.3.3
google-auth            1.21.1
google-auth-oauthlib   0.4.1
google-pasta           0.2.0
grpcio                 1.31.0
h5py                   2.10.0
idna                   2.10
importlib-metadata     1.7.0
joblib                 0.16.0
Keras                  2.4.3
Keras-Preprocessing    1.1.2
kiwisolver             1.2.0
Markdown               3.2.2
matplotlib             3.3.1
numpy                  1.18.5
oauthlib               3.1.0
opt-einsum             3.3.0
pandas                 0.25.3
Pillow                 7.2.0
pip                    20.2.2
protobuf               3.13.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pyparsing              2.4.7
python-dateutil        2.8.1
pytz                   2020.1
PyYAML                 5.3.1
requests               2.24.0
requests-oauthlib      1.3.0
rsa                    4.6
scikit-learn           0.23.2
scipy                  1.4.1
setuptools             50.3.0
six                    1.15.0
sklearn                0.0
tensorboard            2.3.0
tensorboard-plugin-wit 1.7.0
tensorflow             2.3.0
tensorflow-estimator   2.3.0
termcolor              1.1.0
threadpoolctl          2.1.0
urllib3                1.25.10
Werkzeug               1.0.1
wheel                  0.35.1
wrapt                  1.12.1
zipp                   3.1.0

**Comment by Saduf2019** [comment]
@chipxx 
Can you please share the error logs.
Please verify if your CPU/Python is on 32 bits, please refer to these issues  #42751 ##36167.

**Comment by chipxx** [comment]
Hi, my CPU is 64 bits python I don't no.

**Comment by bhack** [comment]
What Is the output of:

```
!python --version
!python -m pip list
```

**Comment by chipxx** [comment]
C:\>python --version
Python 3.6.0

C:\>python -m pip list
Package                Version
---------------------- ---------
absl-py                0.10.0
astunparse             1.6.3
backcall               0.2.0
cachetools             4.1.1
certifi                2020.6.20
chardet                3.0.4
colorama               0.4.3
cycler                 0.10.0
decorator              4.4.2
gast                   0.3.3
google-auth            1.21.1
google-auth-oauthlib   0.4.1
google-pasta           0.2.0
grpcio                 1.31.0
h5py                   2.10.0
idna                   2.10
importlib-metadata     1.7.0
ipykernel              5.3.4
ipython                7.16.1
ipython-genutils       0.2.0
jedi                   0.17.2
joblib                 0.16.0
jupyter-client         6.1.7
jupyter-core           4.6.3
Keras                  2.4.3
Keras-Preprocessing    1.1.2
kiwisolver             1.2.0
Markdown               3.2.2
matplotlib             3.3.1
numpy                  1.18.5
oauthlib               3.1.0
opt-einsum             3.3.0
pandas                 0.25.3
parso                  0.7.1
pickleshare            0.7.5
Pillow                 7.2.0
pip                    20.2.2
prompt-toolkit         3.0.3
protobuf               3.13.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
Pygments               2.6.1
pyparsing              2.4.7
python-dateutil        2.8.1
pytz                   2020.1
pywin32                228
PyYAML                 5.3.1
pyzmq                  19.0.2
requests               2.24.0
requests-oauthlib      1.3.0
rsa                    4.6
scikit-learn           0.23.2
scipy                  1.4.1
setuptools             50.3.0
six                    1.15.0
sklearn                0.0
tensorboard            2.3.0
tensorboard-plugin-wit 1.7.0
tensorflow             2.3.0
tensorflow-estimator   2.3.0
termcolor              1.1.0
threadpoolctl          2.1.0
tornado                6.0.4
traitlets              4.3.3
urllib3                1.25.10
wcwidth                0.2.5
Werkzeug               1.0.1
wheel                  0.35.1
wrapt                  1.12.1
zipp                   3.1.0

**Comment by bhack** [comment]
What is the failed command?

**Comment by bhack** [comment]
Is this working?
```
import tensorflow as tf
from tensorflow import keras
```

**Comment by chipxx** [comment]
I wrote it on top. 
"**import keras**" then gives me

**Comment by bhack** [comment]
You need to import Keras from Tensorflow as in my example.

See also https://github.com/tensorflow/tensorflow/issues/42961

**Comment by chipxx** [comment]
`Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> **import tensorflow as tf**
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import tensorflow as tf
  File "C:\Python36\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Python36\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Python36\lib\site-packages\tensorflow\python\eager\context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\Python36\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Python36\lib\site-packages\google\protobuf\descriptor.py", line 48, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: Impossibile trovare la procedura specificata.
>>> from tensorflow import keras
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    **from tensorflow import keras**
  File "C:\Python36\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Python36\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Python36\lib\site-packages\tensorflow\python\eager\context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\Python36\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Python36\lib\site-packages\google\protobuf\descriptor.py", line 48, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: Impossibile trovare la procedura specificata.
>>> `

**Comment by bhack** [comment]
This is a different issue. Can you try with python 3.6.1?

**Comment by chipxx** [comment]
I will now try

**Comment by chipxx** [comment]
I upgraded to python 3.6.1 but the error is always there.
`Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: Impossibile trovare il modulo specificato.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import tensorflow as tf
  File "C:\Python36\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Python36\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Python36\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Python36\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: Impossibile trovare il modulo specificato.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.`

**Comment by bhack** [comment]
Can you check if you are compliat with Windows requirements at https://www.tensorflow.org/install/pip?hl=en#windows

**Comment by Saduf2019** [comment]
@chipxx 
Please refer to [this link](https://github.com/tensorflow/tensorflow/issues/43003#issuecomment-688073182), and verify all dependencies.

**Comment by bhack** [comment]
Check also https://github.com/tensorflow/tensorflow/issues/43003

**Comment by chipxx** [comment]
Hi, okay solved. I put  vc++ 140_1.dll in python dll folder.  Than

**Comment by bhack** [comment]
@chipxx Can you close this?
