### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by kukuquack** [tensorflow/tensorflow#43003]
### System information

-   **just written import tensorflow**
-   **Windows 10**
-   **TensorFlow installed from pip**
-   **TensorFlow version: Latest**
-   **Python version**: 3.7.3
-   **GPU model and memory**: I am using cpu version

### Describe the problem
I have been stuck on this problem forever: https://pastebin.com/n7y5cmEQ

I have downloaded tensorflow on an i7-5600u, 16 gb ram device.

If I am missing any info please tell me

Thanks

**Comment by bhack** [comment]
Can you check if you are compliat with Windows requirements at https://www.tensorflow.org/install/pip?hl=en#windows

**Comment by kukuquack** [comment]
I don't have the c++ thing, but I am using python,
also i don't know what is the manylinux2010 support

**Comment by bhack** [comment]
Can you try to install TF following the guide steps?

**Comment by Saduf2019** [comment]
@kukuquack 
What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the latest [microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.
Please, refer similar issue #42724 #42440 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204

**Comment by kukuquack** [comment]
So I need to install all 2015,2017,2019 versions of the redistributable?

**Comment by bhack** [comment]
@kukuquack Yes it is one of the requirements.

Also:
> Requires Python 3.5–3.8, pip and venv >= 19.0
> Make sure long paths are enabled on Windows.
> Install the 64-bit Python 3 release for Windows (select pip as an optional feature).

**Comment by kukuquack** [comment]
For some reason I can't find gpedit.msc on run.

**Comment by bhack** [comment]
You can check this https://www.itechtics.com/enable-gpedit-windows-10-home/

**Comment by kukuquack** [comment]
>>> import tensorflow
2020-09-07 14:26:43.159687: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-09-07 14:26:43.181952: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

**Comment by kukuquack** [comment]
It works now thanks!

**Comment by Saduf2019** [comment]
@kukuquack 
Thank you for your update, please feel free to move the ticket to closed status if resolved.
