### ISSUE TITLE
Issues while installing for raspberry pi through pip command

### ISSUE THREAD

**Issue by shreekantgosavi** [tensorflow/tensorflow#43006]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- Tensorflow version (commit SHA if source):
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):

**Describe the problem**
When did pip install TensorFlow lite for raspberry pi it started installation but meanwhile showing error and couldn't install the whole package 
**Please provide the exact sequence of commands/steps when you ran into the problem**

**Comment by shreekantgosavi** [comment]
Please resolve this

**Comment by ravikyram** [comment]
@shreekantgosavi 

Can you please refer this [link](https://www.tensorflow.org/lite/guide/build_rpi) to build tensorflow Lite for Raspberry Pi.Hope this helps. Thanks!
