### ISSUE TITLE
Wrong licenses / license breach in TensorFlow

### ISSUE THREAD

**Issue by PetrProkopNXP** [tensorflow/tensorflow#43015]
Hi TensorFlow authors,
My name is Petr Prokop, I serve in NXP as a Trusted Advisor – person in charge of SW licenses compliance.
NXP adapts TensorFlow for its i.MX processors. Such releases are subject of license-compliance check.

Unfortunately, our scanning tool (Black Duck Protex by Synopsis) has reported following license breach:
TensorFlow file https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/io/cache.cc is very similar to
LevelDB file https://github.com/google/leveldb/blob/master/util/cache.cc.

Likewise, files
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/io/cache.h
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/io/cache_test.cc
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/io/table.cc
are reported to be similar to 
https://github.com/google/leveldb/blob/master/include/leveldb/cache.h
https://github.com/google/leveldb/blob/master/util/cache_test.cc
https://github.com/google/leveldb/blob/master/table/table.cc.

As many SW tools, Black Duck Protex has only limited efficiency, so I’ve found some further files in core/lib/io directory during my investigation manually. 

My understanding is, that TensorFlow reuses LevelDB files, that is pretty fine according original LevelDB license (BSD-3-Clause). However, changing both copyright and license breaches claim#1 of BSD. I wouldn’t dare to advise you anything, but described state is an obstacle for using TensorFlow by NXP. Simultaneously, our internal policy prohibits to change 3rd party copyrights, even if they were wrong.

Can I ask you to allow update of *.h, *.cc and addition of Authors/License_LevelDB.txt files in your repository?
My modification are prepared in https://github.com/PetrProkopNXP/tensorflow, based on original TensorFlow master branch.

Feel free change exact wording of “Modification” clause and/or formatting.

Regards,
Petr

**Comment by yongtang** [comment]
@PetrProkopNXP I think the right way might be to vendor leveldb as a third party package through bazel, and then tensorflow's core code will use vendor'ed leveldb package.

That will resolve any license issues. It will also be easier in the future to update leveldb in case there are any bug fixes (from leveldb side).

/cc @martinwicke

**Comment by PetrProkopNXP** [comment]
Sorry @yongtang , I don’t understand your answer (verb “to vendor”, “bazel”)

If you suggest I should take original LevelDB sources and refactor them for Tensorflow purposes, it is exactly what I really has done, as it depends on point of view: Consider the change, as I took original LevelDB sources with LevelDB copyright headers and moved there all TensorFlow changes that have been already done. Then I renamed original LevelDB LICENSE and AUTHORS files, both in directory and in license header reference, because in TensorFlow environment they don’t express outgoing license and whole-project authors, but relates to only one component.

Regardless any need of NXP, through breaching license to one particular SW component, TensorFlow project now violates copyright law. Proposed change heals the issue.

Regards,
Petr

**Comment by bhack** [comment]
I think that @yongtang's solution it is correct.

**Comment by martinwicke** [comment]
When including the code from leveldb, we did relicensed the original code, which was created by Google, under Apache2 for TensorFlow. 

Hence, the license headers are correct. 

I understand that it is confusing to automated systems to find similar code under a different license.

**Comment by PetrProkopNXP** [comment]
Hi @martinwicke,
Sorry for my insisting. I can imagine code licensed once under BSD may be relicensed by its copyright owner.
Similarly, BSD licensed component might be _used_ in Apache licensed project by anyone.
But I have no idea what legal title could empower a user to relicense someone else’s BSD code, not giving attribution to original author, in environment of open-source.

You are right, that finding similar code is tricky issue. However, I checked the tensorflow vs. levelDb code manually: in modified (_similar_) code remained very same comments. Weird, isn’t it?

I don't stick on form of solution I've offered initially - more complex solution was offered by @yongtang in PR [43204](https://github.com/tensorflow/tensorflow/pull/43204). But the PR was closed after close of this issue.

**Comment by martinwicke** [comment]
LevelDB is composed either entirely of a) contributions Google received under CLA, or b) Google-employee authored code. a) gives us a "sublicense right", which means we can apply any license we choose to the code.

**Comment by ewilderj** [comment]
@PetrProkopNXP if you need any attorney communication about this please drop me an email at ewj at google.com

**Comment by PetrProkopNXP** [comment]
Hi Edd,
Thank you for your offer of explanation.

A notice at beginning: our release is already done. We removed files in question, as developers have said that LevelDB component is not necessary for them.

But I’m still curious how the legal things work in this case (and I’d like to be ready when developers say the LevelDB component become necessary): it seems to me that @martinwicke thinks Google CLA overcomes license of particular project (LevelDB here).
I can’t oppose to this (although seems to me that adding an individual license to project on GitHub.com would make lesser sense than I thought sooner). However Google CLA does contain not only clause 2 (right to … sublicense…), but clause 5 (declaration of original creation, indication of 3rd party code), 6 (no warranty of title and non-infringement -> this would make US responsible!) and 8 (commitment to notify Google).
From this perspective, I’m still persuaded there is not everything OK  in the way how LevelDB was reused in this particular case.

Please, let me know your point of view to the github licensing, or some link to explanation. For example, I wonder what happens if GPL licensed code, containing 3rd party GPL components, is distributed on GitHub.

Best Regards,
Petr Prokop
Software Engineer, Trusted Advisor
NXP Semiconductors
Sochorova 3232/36
616 00 Brno - Zabovresky
Czech Republic
Phone: +420 511 152 414
Email: petr.prokop@nxp.com<mailto:petr.prokop@nxp.com>
[cid:image005.png@01D1328E.35DBD800]
