### ISSUE TITLE
TF_lite inference error

### ISSUE THREAD

**Issue by huafeihuayu** [tensorflow/tensorflow#43010]
RuntimeError: tensorflow/lite/kernels/pad.cc:205 op_context.output->params.zero_point != op_context.constant_values->params.zero_point (0 != 255)Node number 2 (PADV2) failed to invoke.

tensorflow 1.5.0gpu + windows10 +python3.5

**Comment by abattery** [comment]
@huafeihuayu Could you try conversion with tf-nightly? You can export your model to a saved model directory under TF 1.5 and you can try conversion with the recent TF version and run the converted model.

**Comment by ANSHUMAN87** [comment]
This issue still exist in TF 2.3.1. 
@jdduke , @abattery , please help check it. Thanks!
