### ISSUE TITLE
action_env ignored in some cc_library calls

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#43019]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL 7.5
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3.0
- Python version: 3.7.4
- Bazel version (if compiling from source): 3.4.1
- GCC/Compiler version (if compiling from source): 8.3

**Describe the problem**

I'm trying to build TensorFlow with TF_SYSTEM_LIBS and need to set `$CPATH` via `--action_env`. However for some instances of `cc_library` this env variable is not passed through to the compiler invocation.   
I observed the issue for tensorflow/python/tools/BUILD:226:10 C++ compilation of rule '//tensorflow/core/platform/default:mutex'. The definition for that is at https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/core/platform/default/BUILD#L206

Log output:

```
  (cd /tmp/easybuild-tmp/eb-tHWBp_/tmphugHLy-bazel-build/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=<redacted> \
    PATH=<redacted> \
    PWD=/proc/self/cwd \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/ppc-opt-exec-50AE0418/bin/tensorflow/core/platform/default/_objs/mutex/mutex.d '-frandom-seed=bazel-out/ppc-opt-exec-50AE0418/bin/tensorflow/core/platform/default/_objs/mutex/mutex.o' -D__CLANG_SUPPORT_DYN_ANNOTATION__ -iquote . -iquote bazel-out/ppc-opt-exec-50AE0418/bin -iquote external/com_google_absl -iquote bazel-out/ppc-opt-exec-50AE0418/bin/external/com_google_absl -iquote external/nsync -iquote bazel-out/ppc-opt-exec-50AE0418/bin/external/nsync -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIE -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -fno-canonical-system-headers -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -g0 -g0 '-std=c++14' -c tensorflow/core/platform/default/mutex.cc -o bazel-out/ppc-opt-exec-50AE0418/bin/tensorflow/core/platform/default/_objs/mutex/mutex.o)
Execution platform: @local_execution_config_platform//:platform
```

However it doesn't always occur:  E.g. for `SUBCOMMAND: # @com_google_absl//absl/strings:strings [action 'Compiling external/com_google_absl/absl/strings/internal/memutil.cc', configuration: cab848d308c51b34c791977a9ba0d73e541cabe37f3e6da7b163b34d8bf29b6b, execution platform: @local_execution_config_platform//:platform]` I see all my action_env variables being passed and that is also added with cc_library: https://github.com/abseil/abseil-cpp/blob/df3ea785d8c30a9503321a3d35ee7d35808f190d/absl/strings/BUILD.bazel#L30

Cross-posting this from https://github.com/bazelbuild/bazel/issues/12059 as I'm not sure this is a Bazel or TF issue as it seems to only happens sometimes I'd guess it is on the TF side.

Same issue (I guess) reported at https://github.com/tensorflow/tensorflow/issues/37861#issuecomment-686418236

**Provide the exact sequence of commands / steps that you executed before running into the problem**

- `TF_SYSTEM_LIBS=icu,jsoncpp_git,lmdb,nasm,pcre,org_sqlite,swig,curl,double_conversion,flatbuffers,gif,hwloc,libjpeg_turbo,png,nsync,com_google_protobuf,pybind11,snappy,zlib,absl_py,astor_archive,astunparse_archive,cython,enum34_archive,functools32_archive,gast_archive,opt_einsum_archive,pasta,six_archive,termcolor_archive,wrapt" ./configure`
- `bazel --output_base=<...> --install_base=/<...> --output_user_root=<...> build --compilation_mode=opt --config=opt --subcommands --verbose_failures --config=noaws --jobs=64 --copt="-fPIC" --action_env=CPATH='<...>' --action_env=LIBRARY_PATH='<...>' --action_env=PYTHONPATH --action_env=PYTHONNOUSERSITE=1 --distinct_host_configuration=false  //tensorflow/tools/pip_package:build_pip_package`

**Comment by angerson** [comment]
Tagging @perfinion

**Comment by bhack** [comment]
It is probably upstream as it seems connected also to https://github.com/bazelbuild/bazel/issues/12049.
We could evaluate to close this.

**Comment by Flamefire** [comment]
I'm not fully convinced it is an upstream (Bazel) issue because many actions (is this the right term?) do use the action_env. All use the (seemingly) same cc_library macro(?) but some don't get my variables. I don't really understand the Bazel architecture (and frankly I don't like the "clean env" decision at all) so I'm asking if there is anything in TF that might change the behavior of those cc_library invocations? Is there something like a "toolchain" or so which gets set for certain folders which makes subsequent rules ignore action_env? Some override of cc_library?

**Comment by Flamefire** [comment]
I just patched the TF sources to allow Bazel 2.0.0 and tried that again (worked for 2.2.0) and it still fails. So that makes it very much look like something in TF changed which causes the new behavior

**Comment by Flamefire** [comment]
I bisected the the TF changes between 2.2 and 2.3 and found the commit which introduced the failure: https://github.com/tensorflow/tensorflow/commit/f827c023906e7d30f0e5f2992b111ab34153310a

Looks like exec_tools is worse than tools. Could that be reverted? From https://docs.bazel.build/versions/master/be/general.html#genrule.exec_tools it sounds like a good idea anyway:

> Note that eventually the host configuration will be replaced by the execution configuration. When that happens, this attribute will be deprecated in favor of tools. Until then, this attribute allows users to selectively migrate dependencies to the execution configuration.

**Comment by bhack** [comment]
@gunan This commit was hidden by @tensorflower-gardener proxy. Do you know the internal author?

**Comment by gunan** [comment]
@Flamefire Thank you very much for going through the trouble of bisecting!
This was unfortunately an internal cleanup done by other teams.
Since it was submitted a long time ago, I suspect reverting it may break things.
@av8ramit could you look into this? Maybe we can reach out to bazel team for help with understanding and resolving this?

**Comment by Flamefire** [comment]
FWIW: I created a patch which does revert this and it seems to work: https://github.com/easybuilders/easybuild-easyconfigs/blob/8b7342cb08b1e44f91241655ccd58cd3ec4f3687/easybuild/easyconfigs/t/TensorFlow/TensorFlow-2.3.0_revert-tools-to-exectools-renaming.patch

I could open a PR with that so you can run it through CI, if that helps

**Comment by av8ramit** [comment]
Taking a look now, and will triage it to bazel. I second @gunan, thank you @Flamefire for bisecting. @Flamefire I think opening a PR is not a bad idea, I don't know if we will decide to merge it though.
