### ISSUE TITLE
TF_TensorToPyArray is hard coded for equality, limits performance enhancements 

### ISSUE THREAD

**Issue by avinashcpandey** [tensorflow/tensorflow#43021]
Hi,

I am running one CNN model which has convolution and FC layers. 
For getting optimal performance i am using buffers allocated with allocate_persistent() API and I am reusing these buffers multiple times as Network is pretty sequential. 
For achieving this i pre-allocate big chunks with allocate_persistent() API and for every Op execution i use the same buffers by setting with different shape. 

With convolutions it worked fine and i see some performance gains. However once FC layer gets executed it throws below exception. Because of this exception, I am not able to run my network. 

_INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InternalError'>, ndarray was 1921920 bytes but TF_Tensor was 12331253760 bytes
I0907 13:07:13.556839 140574226294592 coordinator.py:224] Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InternalError'>, ndarray was 1921920 bytes but TF_Tensor was 12331253760 bytes_

After looking into code, I found function **TF_TensorToPyArray()** gets called, which compare the ndarray bytes with TF_tensor bytes, which is fine, But why does it need to be exact match?
It should have been below comparison for throwing error, instead of exact match.  
_PyArray_NBYTES(py_array)) >
             TF_TensorByteSize(tensor.get()_

This way same buffers can be used for Op execution, just we need to change the shape.

For experiment i changed 
set_shape(const TensorShape& shape)  to Public scope, looking for some alternate-native for this too.

**Comment by ravikyram** [comment]
@avinashcpandey 

Request you to fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

Please, share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by avinashcpandey** [comment]
I created new issue with right template and shared detailed info.
https://github.com/tensorflow/tensorflow/issues/43044

We can close this and work on that.

**Comment by ravikyram** [comment]
@avinashcpandey 

As per your comments i am closing this issue. We can track the issue in #43044. Thanks!
