### ISSUE TITLE
Building and testing CPU Ops, 

### ISSUE THREAD

**Issue by Patrikvs94** [tensorflow/tensorflow#43022]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 2.3
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 3.5
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the problem**
In Custom Ops, I'm trying to build the example files. When I run the build commands I just get an error saying:

"Executing genrule @local_config_tf//:tf_header_include failed (Exit 35584)"

**Provide the exact sequence of commands / steps that you executed before running into the problem**

$ ./configure.sh
Do you want to build ops again TensorFlow CPU pip package? Y or enter for CPU (tensorflow), N for GPU (tensorflow-gpu). [Y/n] y
Build with CPU pip package.
On windows, skipping toolchain flags..
Are you building against TensorFlow 2.1(including RCs) or newer?[Y/n] y
Build against TensorFlow 2.1 or newer.
Using installed tensorflow
2020-09-07 15:46:38.915193: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-09-07 15:46:38.915211: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-09-07 15:46:40.468711: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-09-07 15:46:40.468729: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

$ bazel build tensorflow_zero_out:python/ops/_zero_out_ops.so
Loading:
Loading: 0 packages loaded
Analyzing: target //tensorflow_zero_out:python/ops/_zero_out_ops.so (0 packages loaded, 0 targets configured)
INFO: Analyzed target //tensorflow_zero_out:python/ops/_zero_out_ops.so (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 5] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: C:/users/patrik.veges/_bazel_patrik.veges/gdil2b47/external/local_config_tf/BUILD:17:8: Executing genrule @local_config_tf//:tf_header_include failed (Exit 35584)
      0 [] bash 287 cygwin_exception::open_stackdumpfile: Dumping stack trace to bash.exe.stackdump
Target //tensorflow_zero_out:python/ops/_zero_out_ops.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: C:/users/patrik.veges/_bazel_patrik.veges/gdil2b47/external/local_config_tf/BUILD:3:11 Executing genrule @local_config_tf//:tf_header_include failed (Exit 35584)
INFO: Elapsed time: 0.899s, Critical Path: 0.80s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

-

**Comment by Saduf2019** [comment]
@Patrikvs94 
Please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/29831#issuecomment-504704980) and let us know if it helps.
verify with existing issues:
#40804 #36111 #31018 [for cuda version] #42436 [without gpu]

**Comment by Patrikvs94** [comment]
I'm not following why the cudart64.dll files would cause my issues. Why would that affect it? It feels like there's something off about the include stuff. I'm trying to do this with CPU only.

**Comment by bhack** [comment]
@Patrikvs94 are your Nvidia and CUDA requirements satisfied? https://www.tensorflow.org/install/gpu#software_requirements

**Comment by Patrikvs94** [comment]
Do they need to be satisfied if I'm only doing CPU only stuff?

**Comment by bhack** [comment]
How did you install Tensorflow?

**Comment by Patrikvs94** [comment]
I just did a "$pip install tensorflow" and it installed tensorflow 2.3

**Comment by bhack** [comment]
Can you try instead with `pip install tensorflow-cpu`?

**Comment by Patrikvs94** [comment]
I did, but the configure file from the "Custom Ops" repository actually installs tensorflow for me. (Aka Tensorflow 2.3)

**Comment by bhack** [comment]
Yes there is a bug with new package naming  at https://github.com/tensorflow/custom-op/blob/master/configure.sh#L89.

Can you close this ticket and open a new one on that repository?

Thanks.

**Comment by bhack** [comment]
Please close this it is already handled in https://github.com/tensorflow/custom-op/issues/74
