### ISSUE TITLE
TensorFlow2 tutorials Actor-Critic method

### ISSUE THREAD

**Issue by hyiche** [tensorflow/tensorflow#43029]
## URL(s) with the issue:

https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/reinforcement_learning/actor_critic.ipynb

### Clear description
At the second cell, we want to install additional packages for visualization.
Maybe should be added "sudo apt-get update" before the line "sudo apt-get install -y xvfb python-opengl > /dev/null 2>&1".
Let the xvfb package can be installed normally.

### Usage example
Correct the second cell as below:
%%bash

sudo apt-get update
sudo apt-get install -y xvfb python-opengl > /dev/null 2>&1
pip install pyvirtualdisplay > /dev/null 2>&1
pip install git+https://github.com/tensorflow/docs > /dev/null 2>&1

**Comment by ymodak** [comment]
Closing this issue now since the colab executes successfully end-to-end.
For more info see the the associated PR thread. Thank you.
