### ISSUE TITLE
Arduino tensorflow

### ISSUE THREAD

**Issue by LiamRandall** [tensorflow/tensorflow#43020]
- Mac OS Catalina Version 10.15.6
- Arduino 1.8.13
- Tensorflow Library "Arduino_TensorFlowLite" version 2.1.0-ALPHA-precompiled
- Arduino Nano BLE 33

Following the Arduino instructions as listed on the [tensorflow github](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/person_detection#running-on-arduino
) the default person detection demonstration fails on compilation looking for `cmsis_compiler.h`

I was able to simply copy v5.01 of the `cmsis_compiler_h` to the `../Arduino_TensorFlowLite/src/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/DSP/Include` directory and the demonstration compiled successfully and worked.

**Comment by sushreebarsa** [comment]
@LiamRandall It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest  stable Version of TF 2.5 and let us know if the issue still persists? Thanks!

**Comment by LiamRandall** [comment]
Yes, I will try to complete this with the latest version and confirm that this works as expected.

**Comment by sushreebarsa** [comment]
@LiamRandall Could you please let us know if you have tried in the latest stable version of TF 2.6.0 and if the issue still persists ? Thanks!
