### ISSUE TITLE
Generate sparse tensor in tflite

### ISSUE THREAD

**Issue by mhs4670go** [tensorflow/tensorflow#43035]
I'm trying to understand the `SparsityParameters` in tflite schema. But, AFAIK, there is only one example that contains this parameters(`tensorflow/lite/testdata/sparse_tensor.json`).

So, I've got trouble generating a network which has tensors whose contents include `SparsityParameters`.

As `tensorflow/core/util/sparse/README.md` said, it sounds like, even if I try to generate a sparse tensor, it will generate just two dense tensors with a shape.
> Sparse Tensors are stored as two dense tensors and a shape

And actually, when I write a code like below and convert it to tflite file,

```python
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
lhs_ = tf.compat.v1.placeholder(dtype=tf.float32, shape=(2), name="Hole")
rhs_ = tf.compat.v1.placeholder(dtype=tf.float32, shape=(2), name="Hole")

st1 = tf.compat.v1.sparse.SparseTensor(
    indices=[[0, 0], [1, 2]], values=lhs_, dense_shape=[3, 4])
st2 = tf.compat.v1.sparse.SparseTensor(
    indices=[[0, 0], [1, 2]], values=rhs_, dense_shape=[3, 4])

# op_ = tf.compat.v1.sparse_add(st1, st2)
# op_ = tf.compat.v1.matmul(st1, st2)
```
It doesn't generate a sparse tensor.

**How can I generate the network that contains sparse tensors?**

p.s. I can manually force it to be generated with json file. But it doesn't seem natural.

<details>

```json
{
  version: 3,
  operator_codes: [
    {
      builtin_code: "FULLY_CONNECTED"
    }
  ],
  subgraphs: [
    {
      tensors: [
        {
          shape: [
            1,
            8
          ],
          buffer: 2,
          name: "input",
          quantization: {
          }
        },
        {
          shape: [
            1,
            4
          ],
          buffer: 3,
          name: "output",
          quantization: {
          }
        },
        {
          shape: [
            4,
            8
          ],
          buffer: 1,
          name: "weight",
          quantization: {
          },
          sparsity: {
            traversal_order: [
              0,
              1
            ],
            dim_metadata: [
              {
                dense_size: 4
              },
              {
                format: "SPARSE_CSR",
                array_segments_type: "Uint16Vector",
                array_segments: {
                  values: [
                    0,
                    1,
                    3,
                    6,
                    10
                  ]
                },
                array_indices_type: "Uint16Vector",
                array_indices: {
                  values: [
                    1,
                    1,
                    4,
                    0,
                    4,
                    5,
                    0,
                    2,
                    6,
                    7
                  ]
                }
              }
            ]
          }
        }
      ],
      inputs: [
        0
      ],
      outputs: [
        1
      ],
      operators: [
        {
          inputs: [
            0,
            2,
            -1
          ],
          outputs: [
            1
          ],
          builtin_options_type: "FullyConnectedOptions",
          builtin_options: {
          }
        }
      ]
    }
  ],
  description: "TOCO Converted.",
  buffers: [
    {
    },
    {
      data: [
        0,
        0,
        128,
        63,
        0,
        0,
        128,
        63,
        0,
        0,
        0,
        64,
        0,
        0,
        128,
        63,
        0,
        0,
        0,
        64,
        0,
        0,
        64,
        64,
        0,
        0,
        128,
        63,
        0,
        0,
        0,
        64,
        0,
        0,
        0,
        64,
        0,
        0,
        128,
        63
      ]
    },
    {
    },
    {
    }
  ]
}
```

</details>

**Comment by bhack** [comment]
Have you seen the reply in https://stackoverflow.com/questions/63719424/understanding-of-sparsityparameters-in-tensorflow-lite-schema?

**Comment by mhs4670go** [comment]
@bhack Yes. Actually, the author of that question is me:) After posting that question, I've understood the TACO format and thanks to the answer to that question, I also noticed that tensorflow and lite format are different.

> How can I generate the network that contains sparse tensors?

But then, doesn't the tflite converter ever create a sparse tensor in taco format? Maybe `tensorflow/lite/tools/optimize/sparsity/format_converter.cc` is a library that does what I think but it's just be used to verify the file(`tensorflow/lite/testdata/sparse_tensor.json`) that is manually generated not to generate a file that contains tensors that has `SparsityParameters`.

**Comment by gowthamkpr** [comment]
@mhs4670go As the solution has already been posted [here ](https://stackoverflow.com/questions/63719424/understanding-of-sparsityparameters-in-tensorflow-lite-schema), can you please go ahead and close the issue. Thanks!
