### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'Dimension'

### ISSUE THREAD

**Issue by dmitryponv** [tensorflow/tensorflow#43031]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

My list of packages:

c:\Dev\Projects\TooGAN\stylegan>pip list
Package                  Version
------------------------ ------------
absl-py                  0.9.0
appdirs                  1.4.4
asgiref                  3.2.5
astor                    0.8.1
astroid                  2.3.3
attrs                    19.3.0
audioread                2.1.8
backcall                 0.1.0
bleach                   3.1.3
cachetools               4.0.0
certifi                  2019.11.28
cffi                     1.14.0
chardet                  3.0.4
colorama                 0.4.3
cv                       1.0.0
cycler                   0.10.0
decorator                4.4.2
defusedxml               0.6.0
distlib                  0.3.1
Django                   3.0.4
django-crispy-forms      1.9.0
dnspython                1.16.0
dtw                      1.4.0
entrypoints              0.3
fake-useragent           0.1.11
ffmpeg                   1.4
filelock                 3.0.12
gast                     0.2.2
google-auth              1.11.3
google-auth-oauthlib     0.4.1
google-images-download   2.8.0
google-pasta             0.2.0
grpcio                   1.27.2
h5py                     2.10.0
idna                     2.9
imageio                  2.8.0
importlib-metadata       1.5.0
imutils                  0.5.3
ipykernel                5.1.4
ipython                  7.13.0
ipython-genutils         0.2.0
ipywidgets               7.5.1
isort                    4.3.21
jedi                     0.16.0
Jinja2                   2.11.1
joblib                   0.14.1
jsonschema               3.2.0
jupyter                  1.0.0
jupyter-client           6.1.0
jupyter-console          6.1.0
jupyter-core             4.6.3
Keras-Applications       1.0.8
Keras-Preprocessing      1.1.0
kiwisolver               1.1.0
lazy-object-proxy        1.4.3
librosa                  0.7.2
llvmlite                 0.31.0
Markdown                 3.2.1
MarkupSafe               1.1.1
matplotlib               3.2.1
mccabe                   0.6.1
mido                     1.2.9
mistune                  0.8.4
mysql-connector-python   8.0.19
mysqlclient              1.4.6
nbconvert                5.6.1
nbformat                 5.0.4
notebook                 6.0.3
numba                    0.48.0
numpy                    1.18.2
oauthlib                 3.1.0
opencv-python            4.4.0.42
opt-einsum               3.2.0
pandocfilters            1.4.2
parso                    0.6.2
pickleshare              0.7.5
Pillow                   7.1.1
pip                      20.2.2
progressbar              2.5
prometheus-client        0.7.1
prompt-toolkit           3.0.4
protobuf                 3.11.3
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycparser                2.20
pydub                    0.23.1
Pygments                 2.6.1
pylint                   2.4.4
pyparsing                2.4.6
pyrsistent               0.15.7
python-dateutil          2.8.1
pytz                     2019.3
pywin32                  227
pywinpty                 0.5.7
PyYAML                   5.3.1
pyzmq                    19.0.0
qtconsole                4.7.1
QtPy                     1.9.0
requests                 2.23.0
requests-oauthlib        1.3.0
resampy                  0.2.2
rsa                      4.0
scikit-learn             0.22.2.post1
scipy                    1.4.1
selenium                 3.141.0
Send2Trash               1.5.0
setuptools               41.2.0
six                      1.14.0
SoundFile                0.10.3.post1
SpeechRecognition        3.8.1
sqlparse                 0.3.1
tensorboard              2.1.1
tensorflow-estimator     2.1.0
tensorflow-gpu           2.1.0
tensorflow-gpu-estimator 2.1.0
termcolor                1.1.0
terminado                0.8.3
testpath                 0.4.4
tornado                  6.0.4
traitlets                4.3.3
typed-ast                1.4.1
urllib3                  1.25.8
virtualenv               20.0.31
wcwidth                  0.1.8
webencodings             0.5.1
Werkzeug                 1.0.0
wheel                    0.34.2
widgetsnbextension       3.5.1
wrapt                    1.11.2
zipp                     3.1.0

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I am trying to run StyleGan library

https://github.com/NVlabs/stylegan

Running "python pretrained_example.py"

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by bhack** [comment]
Cause `tf.Dimension` is deprecated and is `tf.compat.v1.Dimension`

**Comment by bhack** [comment]
Also generally Stylegan and Stylegan2 require `TensorFlow 1.14 or 1.15 with GPU support.`
