### ISSUE TITLE
Cannot use TensorArray with tf.scan

### ISSUE THREAD

**Issue by jeanm** [tensorflow/tensorflow#4303]
I seem to be unable to use `TensorArray`s with `tf.scan`. I am running 0.10.0rc0 on Ubuntu 14.04 with Cuda Toolkit 7.5 and cuDNN v4.

Here is a minimal example:

```python
import tensorflow as tf

array = tf.TensorArray(tf.float32, size=10)
elements = list(range(10))

def step(state, current_input):
    return state.write(current_input, tf.zeros(shape=[100]))

out = tf.scan(step, elements, initializer=array)

with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    print(sess.run(out))
```

And the output is:

```
Traceback (most recent call last):
  File "array_test.py", line 9, in <module>
    out = tf.scan(step, elements, initializer=array)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/functional_ops.py", line 521, in scan
    a_flat = [ops.convert_to_tensor(init) for init in initializer_flat]
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/functional_ops.py", line 521, in <listcomp>
    a_flat = [ops.convert_to_tensor(init) for init in initializer_flat]
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 628, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/constant_op.py", line 180, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/constant_op.py", line 163, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/tensor_util.py", line 422, in make_tensor_proto
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/tensor_util.py", line 422, in <listcomp>
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/util/compat.py", line 45, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got <tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x7ff0db9309e8>
```

**Comment by tatatodd** [comment]
@ebrevdo can correct / expand as necessary

Thanks @jeanm for filing this issue!  I can indeed reproduce the output.

I believe the purpose of `TensorArray` is to implement dynamic iteration primitives - e.g. `scan` is implemented using `TensorArray`:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/functional_ops.py#L506

I'm not sure whether `TensorArray` is itself meant to be used as you are doing.  For the simple example program above, obviously a regular tensor should be sufficient.

Can you expand a bit on what problem you're actually trying to solve?  Or were you just playing around with things?

**Comment by jeanm** [comment]
Thanks for the quick response @tatatodd 

> Can you expand a bit on what problem you're actually trying to solve? Or were you just playing around with things?

I am implementing an RNN which, at time `t`, may need to access not just the output at `t-1` but also outputs from earlier time steps. That's why I'd like to pass around a `TensorArray` and update it as I go along. In #2237 there are several examples of RNNs of this kind, such as [this simple Tree-RNN](https://github.com/tensorflow/tensorflow/issues/2237#issuecomment-233439285) by @lukasr0.

I can emulate a scan by using `tf.while_loop` instead, like in the linked Tree-RNN example, but it's a bit cumbersome and it doesn't seem to be very efficient.

**Comment by ebrevdo** [comment]
Please see the new `tf.nn.raw_rnn`, which allows you to keep an arbitrary list of tensors and TensorArrays in the loop_state, as passed through loop_fn.

You can write the rnn output state to your loop state.

**Comment by jeanm** [comment]
Thanks, that seems like a better solution.
