### ISSUE TITLE
Error "failed to connect to all addresses" when training on TPU with Colab

### ISSUE THREAD

**Issue by jplu** [tensorflow/tensorflow#43037]
Hello!

**Describe the current behavior**
When running the my Colab I get the following error:
```
UnavailableError: failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1599555147.064735819","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3948,"referenced_errors":[{"created":"@1599555147.064732799","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]]
```
When I try to iterator over my dataset:
```
<ipython-input-5-9732b6b5faf1> in train(self)
     42 
     43             for epoch_iter in range(1, 5):
---> 44                 for step, batch in enumerate(train_ds):
     45                     self.global_step = iterations.numpy()
     46 
```

**Describe the expected behavior**
Being able to iterate over the dataset.

**Standalone code to reproduce the issue**
The full Colab can be found here https://colab.research.google.com/drive/1jZaFmrDmBGbGkg8oKEJ78cL2PgIB7UF5?usp=sharing

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/23e04d7ef7e70a5ee6eaf93b0b57e0e8/untitled408.ipynb)

**Comment by bhack** [comment]
@jplu Can you check https://github.com/tensorflow/tensorflow/issues/40035#issuecomment-663173209?

**Comment by jplu** [comment]
I get the exact same error also when loading data from a Google Storage bucket.

**Comment by jplu** [comment]
You can replace:
```
ds, info = tfds.load("glue/mrpc", split="train", with_info=True, try_gcs=True)
```
By
```
ds, info = tfds.load("glue/mrpc", split="train", with_info=True, try_gcs=True, data_dir=<gs bucket>)
```
In your [gist ](https://colab.research.google.com/gist/Saduf2019/23e04d7ef7e70a5ee6eaf93b0b57e0e8/untitled408.ipynb) and you will get the exact same error.

**Comment by bhack** [comment]
It seems to me that on @Saduf2019 tf-nightly gist there is another issue about Graphdef versioning:

> InvalidArgumentError: Converting GraphDef to Graph has failed. The binary trying to import the GraphDef was built when GraphDef version was 440. The GraphDef was produced by a binary built when GraphDef version was 517. The difference between these versions is larger than TensorFlow's forward compatibility guarantee. The following error might be due to the binary trying to import the GraphDef being too old: NodeDef mentions attr 'ram_budget' not in Op<name=ModelDataset; signature=input_dataset:variant -> handle:variant; attr=algorithm:int,default=0; attr=cpu_budget:int,default=0; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1>; NodeDef: {{node ModelDataset/_21}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.). [Op:OptimizeDatasetV2]

/cc @jhseu

**Comment by jplu** [comment]
Indeed the difference comes from the fact to use `tf-nightly version 2.4.0-dev20200908` instead of the 2.3 version.

**Comment by bhack** [comment]
@jplu Yes there is no visibility about your issue reproducibility in the @Saduf2019 gist cause this new issue could be the only one (in this case your issue It Is alteady solved in nightly) or just an early issue that doesn't let to trigger your own.

The only thing to "quickly" disambiguate the status on nightly Is to resolve this new Graphdef incompatibilty.

**Comment by nikitamaia** [comment]
Hi @jplu were you able to try the suggestion from @bhack?

**Comment by jplu** [comment]
What was the suggestion? What I understood is that we have to find out if in nightly is issue comes after because the issue in 2.3 has been solved or if it comes before and the nightly brings another issue. I don't know what to do to know that.

**Comment by bhack** [comment]
@nikitamaia The problem is that @jplu is using in the submitted example an external library (https://huggingface.co/transformers/) that probably is using something pretrained that is incompatible to test with `tf-nightly`

**Comment by Smankusors** [comment]
unfortunately I stumbled upon this issue when trying with generator. I tried an example from [docs here](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#from_generator) and it returns same error. This happens when I initialize the TPU first, and then dataset later.

```
import tensorflow as tf
try:
  tpu = tf.distribute.cluster_resolver.TPUClusterResolver()  # TPU detection
  print('Running on TPU ', tpu.cluster_spec().as_dict()['worker'])
  tf.config.experimental_connect_to_cluster(tpu)
  tf.tpu.experimental.initialize_tpu_system(tpu)
  strategy = tf.distribute.TPUStrategy(tpu)
except ValueError:
  print('WARNING: TPU not available!')
  strategy = tf.distribute.get_strategy()

import itertools

def gen():
  for i in itertools.count(1):
    yield (i, [1] * i)

dataset = tf.data.Dataset.from_generator(
     gen,
     (tf.int64, tf.int64),
     (tf.TensorShape([]), tf.TensorShape([None])))

list(dataset.take(3).as_numpy_iterator())
```

error:

```
UnavailableError: failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1606047177.389355931","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3948,"referenced_errors":[{"created":"@1606047176.622134062","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}
```

It's on Google Colab btw

**Comment by hongjunChoi** [comment]
@Smankusors: I believe the root cause for the error you are encountering is different from that of this initial bug report. 

As for your case, could you instead materialize the dataset (instead of using `from_generator` API) ?
tf.data.Dataset.from_generator() API is not yet supported on TPU's and I believe this is the reason for the failure.

**Comment by Smankusors** [comment]
> As for your case, could you instead materialize the dataset (instead of using `from_generator` API) ?

no, my Google Colab session crashes when doing this 😆 

probably protobuf hard limit I guess

> tf.data.Dataset.from_generator() API is not yet supported on TPU's and I believe this is the reason for the failure.

huh... I see... then the documentation needs to be updated about this?

**Comment by sushreebarsa** [comment]
@jplu It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest  stable Version of TF 2.5 and let us know if the issue still persists? Thanks!

**Comment by jplu** [comment]
@sushreebarsa  Still the case with TF 2.5. Error from the same place:
```
<ipython-input-4-9732b6b5faf1> in train(self)
     42 
     43             for epoch_iter in range(1, 5):
---> 44                 for step, batch in enumerate(train_ds):
     45                     self.global_step = iterations.numpy()
```
With the same error:
```
UnavailableError: failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1628525695.735776411","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":5420,"referenced_errors":[{"created":"@1628525695.735773104","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]
	 [[RemoteCall]]
```

**Comment by bhack** [comment]
@jplu Do you have the same error with `pip install tensorflow==2.6.0rc2` ?

**Comment by jplu** [comment]
I now get a new error, the same than https://github.com/keras-team/keras/issues/15044 . The piece of code that raises this issue is located before the one that raises the previous error. Then I cannot say if the error is still here or not because now this piece of code is not anymore reached.

**Comment by bfontain** [comment]
FYI, if you are using tf-nightly with TPUs you may need to make the TPU runtime version match with the currently installed TF version. To do this:

!pip install cloud_tpu_client
from cloud_tpu_client import Client
c = Client(tpu='')
c.configure_tpu_version(tf.__version__, restart_type='ifNeeded')

**Comment by bhack** [comment]
@bfontain We really need to find a better place to expose this tip.

**Comment by bfontain** [comment]
Ideally a colab user should not need to do this. We could detect a tf version change after running a !pip or %pip or something similar and automatically make the runtime match if possible. An alternative would be to enhance %tensorflow_version (which does support TPU runtime version changing) to support more than just a handful of versions. In particular it doesn't support nightly.

**Comment by jplu** [comment]
I was not using tf-nightly but tensorflow==2.6.0rc2. But thanks for the tip it is always good to know!

**Comment by bfontain** [comment]
IIRC, we don't have 2.6.0 runtime for TPUs available yet. If you need something feature added beyond 2.5.0 you should try the nightly.

**Comment by bhack** [comment]
2.6.0 was just released

**Comment by bfontain** [comment]
The TensorFlow release may be done, but it may be a few days before the TPU runtime release is available. You can check the runtime version your associated TPU is on via the Client() object above,

```
!pip install cloud_tpu_client
from cloud_tpu_client import Client
c = Client(tpu='')
print(c.run_time_version())
```

**Comment by bfontain** [comment]
I think as well, the default TPU runtime will match the default version of TensorFlow installed in colab, if you change this version (even to non-nightly) it is advised to configure the version as mentioned above. The caveat for non-nightly versions is that we generally only have TPU runtimes for non rc releases. In some cases (e.g. 2.5.1), we don't have a TPU runtime release, and it is most likely safe to use TensorFlow 2.5.1 with TPU runtime 2.5.0 as most point release don't require any TPU runtime side changes.

**Comment by bhack** [comment]
I think with the current TF release policy patch releases are just for security fixes.

For bug triaging it is important to work with nightly as we often test on Colab nightly versions to check if It something the is fixed in master.

**Comment by jplu** [comment]
Awesome!! The @bfontain's tip made it works!! I had to adapt my code to take into account some new changes and now it works like a charm with TF 2.6.0 and the TPU client set to this same version.

BTW when I run `print(c.run_time_version())` I get the error `AttributeError: 'Client' object has no attribute 'run_time_version'` with `cloud_tpu_client==0.10`.

**Comment by bfontain** [comment]
Great to hear! With regards to `cloud_tpu_client`, I made a typo (now corrected), the correct call would be `print(c.runtime_version())` with `runtime` as one word.

**Comment by bfontain** [comment]
Also, I believe the 2.6.0 runtime may now be available on Cloud TPU as well if you don't want to use nightly, but you may still need the `cloud_tpu_client` code until default TF and TPU runtime version for colab is updated.
