### ISSUE TITLE
I want to minimize 'cost' with variable 'h0'

### ISSUE THREAD

**Issue by MaarHybrid** [tensorflow/tensorflow#43036]
M=np.array([[1,0],[0,0]])
M=np.kron(M,np.identity(32))
M=tf.constant(M,dtype=tf.float32)
M=tf.complex(M,tf.zeros([64,64],tf.float32))
h0=tf.Variable(tf.random.normal([64,64],0,1,tf.float32),dtype=tf.float32,shape=[64,64])
h0_T=tf.transpose(h0)
ih = tf.complex(h0 - h0_T, h0 + h0_T)
u = tf.linalg.expm(ih)
u_dagger=tf.linalg.expm(-ih)
ro=tf.constant(ro[0],dtype=tf.float32)
ro=tf.complex(ro,tf.zeros([64,64],tf.float32))
cost= lambda: tf.math.real(tf.linalg.trace(u*ro*u_dagger*M))
opt = tf.keras.optimizers.SGD(learning_rate=0.001)
train=opt.minimize(cost, var_list=[h0]).numpy()

This is my code, and i error occurs like below

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-0f648ef2f92b> in <module>
     12 cost= lambda: tf.math.real(tf.linalg.trace(u*ro*u_dagger*M))
     13 opt = tf.keras.optimizers.SGD(learning_rate=0.001)
---> 14 train=opt.minimize(cost, var_list=[h0]).numpy()
     15 with tf.Session() as sess:
     16     sess.run(tf.global_variables_initializer())

~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py in minimize(self, loss, var_list, grad_loss, name)
    375         loss, var_list=var_list, grad_loss=grad_loss)
    376 
--> 377     return self.apply_gradients(grads_and_vars, name=name)
    378 
    379   def _clip_gradients(self, grads):

~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py in apply_gradients(self, grads_and_vars, name, experimental_aggregate_gradients)
    511       ValueError: If none of the variables have gradients.
    512     """
--> 513     grads_and_vars = _filter_grads(grads_and_vars)
    514     var_list = [v for (_, v) in grads_and_vars]
    515 

~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\optimizer_v2\optimizer_v2.py in _filter_grads(grads_and_vars)
   1268   filtered = tuple(filtered)
   1269   if not filtered:
-> 1270     raise ValueError("No gradients provided for any variable: %s." %
   1271                      ([v.name for _, v in grads_and_vars],))
   1272   if vars_with_empty_grads:

ValueError: No gradients provided for any variable: ['Variable:0'].

What is problem? Thank you very much

**Comment by ravikyram** [comment]
@MaarHybrid 

I tried reproducing the issue in colab with TF 2.3 and i am seeing the error message(`NameError: name 'ro' is not defined`).
Please, share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by mihaimaruseac** [comment]
This is better asked on StackOverflow as it has no issue with TF code

**Comment by MaarHybrid** [comment]
import tensorflow as tf
import numpy as np
from scipy.linalg import expm, sinm, cosm
import matplotlib.pyplot as plt
import tensorflow_addons as tfa
tfa.options.TF_ADDONS_PY_OPS = True

#Load MNIST datasets from Keras
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

#Rescale the images from [0, 255] to the [0.0, 1.0] range.
x_train, x_test = x_train[..., np.newaxis]*np.pi/255.0, x_test[..., np.newaxis]*np.pi/255.0

#Filter out specific type of images
train_filter = np.where((y_train == 0 ))
test_filter = np.where((y_test == 0))

#Put filters
x_train, y_train = x_train[train_filter], y_train[train_filter]
x_test, y_test = x_test[test_filter], y_test[test_filter]


# In[4]:


#Downscale loaded MNIST images to n*n images
x_train_downscale = tf.image.resize(x_train, (8,8)).numpy()
x_test_downscale = tf.image.resize(x_test, (8,8)).numpy()

flat = []
for i in range (0,39):
    flat.append(x_train_downscale[i].flatten().reshape(1,64))
ro=[]
for i in range (0,39):
    ro.append(np.matmul(flat[i].transpose(),flat[i]))

M=np.array([[1,0],[0,0]])
M=np.kron(M,np.identity(32))
M=tf.constant(M,dtype=tf.float32)
M=tf.complex(M,tf.zeros([64,64],tf.float32))
h0=tf.Variable(tf.random.normal([64,64],0,1,tf.float32),dtype=tf.float32,shape=[64,64])
h0_T=tf.transpose(h0)
ih = tf.complex(h0 - h0_T, h0 + h0_T)
u = tf.linalg.expm(ih)
u_dagger=tf.linalg.expm(-1*ih)
ro=tf.constant(ro[0],dtype=tf.float32)
ro=tf.complex(ro,tf.zeros([64,64],tf.float32))
cost= lambda: tf.math.real(tf.linalg.trace(u*ro*u_dagger*M))
opt = tf.keras.optimizers.SGD(learning_rate=0.001)
train=opt.minimize(cost, var_list=[h0]).numpy()
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        _, cost_val,h_val = sess.run([train, cost, h])
        if step % 20 == 0:
            print(step, cost_val, h_val)

This is whole code
