### ISSUE TITLE
Pylint incorrectly identifies tensorflow public API functions in tensorflow 2.2+

### ISSUE THREAD

**Issue by ScaleRunner** [tensorflow/tensorflow#43038]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Apart from the example below, no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04/OSX 10.15.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: :x:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2+
- Python version: 3.7.4
- Bazel version (if compiling from source): :x:
- GCC/Compiler version (if compiling from source): :x:
- CUDA/cuDNN version: :x:
- GPU model and memory: :x:

**Describe the current behavior**
When using pylint, a lot of functions from the public API are misidentified.
For example, the public api function `tf.split`, which is publicly defined as `tensorflow/python/ops/array_ops.split` is misidentified (I think as `tensorflow/python/ops/gen_array_ops.split`).

Other examples include `tf.random.uniform`, `tf.concat` and the list goes on.

Let's take the code snipped below:

`example.py`:
```python
import tensorflow as tf

tensor = tf.random.uniform((2, 4), minval=0, maxval=256)
tf.split(tensor, num_or_size_splits=2, axis=-1)
```

This is perfectly fine code, it runs as expected.

However, when running pylint both functions are misidentified and lots of linting errors are raised.
Running pylint on the module (`pylint -E example.py`) gives:
```
example.py:3:9: E1123: Unexpected keyword argument 'minval' in function call (unexpected-keyword-arg)
example.py:3:9: E1123: Unexpected keyword argument 'maxval' in function call (unexpected-keyword-arg)
example.py:3:9: E1120: No value for argument 'dtype' in function call (no-value-for-parameter)
example.py:4:0: E1123: Unexpected keyword argument 'num_or_size_splits' in function call (unexpected-keyword-arg)
example.py:4:0: E1124: Argument 'axis' passed by position and keyword in function call (redundant-keyword-arg)
example.py:4:0: E1120: No value for argument 'value' in function call (no-value-for-parameter)
example.py:4:0: E1120: No value for argument 'num_split' in function call (no-value-for-parameter)
```

**Describe the expected behavior**
Running `pylint -E example.py` should not give any errors.

**Standalone code to reproduce the issue**
```python
import tensorflow as tf

tensor = tf.random.uniform((2, 4), minval=0, maxval=256)
tf.split(tensor, num_or_size_splits=2, axis=-1)
```

**Other info / logs**
This occurs with `tensorflow>=2.2.0`.
Previous versions of tensorflow `2.X` (e.g. tensorflow `2.1.X` and tensorflow `2.0.X`) do not have these problems.

I have used `pylint==2.6.0` for the example, but previous versions have the same behaviour.

One of the things that might have caused this (just a guess) is the upgrade to a new version of `gast` that occurred in tensorflow `2.2`, where they went from `gast==0.2.2` to `gast==0.3.3`.

Now, I know that this issue is not a code breaking issue, but it is a workflow breaking issue when using tensorflow in a professional setting. For example, one of the requirements for passing all steps in the CI may be running pylint, which now fails. Pylint allow disabling errors for specific third-party packages, so really the only solution is to add a `pylint: disable=...` comment every time you use a tensorflow function which is misidentified or to disable pylint for the project all together. Both options aren't desirable.

This issue was also raised in the `pylint` repo (https://github.com/PyCQA/pylint/issues/3613) and probably also related to https://github.com/PyCQA/pylint/issues/3596. But I don't think these issues belong in the `pylint` repo` (or `astroid` for that matter), but here in the tensorflow repo as it's probably caused by the import structure of tensorflow.

One lead might be that a wildstar import overwrites functions. An examples might be the wildstar import in https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/python/ops/array_ops.py#L40 which overwrites `tensorflow/python/ops/array_ops.split` with the starred import `tensorflow/python/ops/gen_array_ops.split`. I'm not sure, but not performing wildstar imports might solve this linter problem.

**Comment by bhack** [comment]
This is true with newer pylint versions. As you see currently in master we are on `1.6.4`:
```
tensorflow/tools/ci_build/rel/ubuntu/sanity.sh:sudo python2 -m pip install pylint==1.6.4
tensorflow/tools/ci_build/rel/ubuntu/sanity.sh:sudo python3 -m pip install pylint==1.6.4
tensorflow/tools/ci_build/presubmit/ubuntu_16/sanity/build.sh:  sudo python3 -m pip install pylint==1.6.4
tensorflow/tools/ci_build/install/install_centos_pip_packages.sh:pip2 install pylint==1.6.4
tensorflow/tools/ci_build/install/install_centos_pip_packages.sh:pip3 install pylint==1.6.4
tensorflow/tools/ci_build/install/install_pip_packages.sh:# pylint==1.6.4 requires python-astroid (>= 1.4.5) requires lazy-object-proxy
tensorflow/tools/ci_build/install/install_pip_packages.sh:pip2 install pylint==1.6.4
tensorflow/tools/ci_build/install/install_pip_packages.sh:pip3 install pylint==1.6.4
tensorflow/tools/ci_build/release/ubuntu_16/sanity/build.sh:sudo python2 -m pip install pylint==1.6.4
tensorflow/tools/ci_build/release/ubuntu_16/sanity/build.sh:sudo python3 -m pip install pylint==1.6.4
```

**Comment by ScaleRunner** [comment]
Ahh, I see. I can indeed verify that when using `pylint==1.6.4`, there are no linting errors in the `example.py` I mentioned.

Are there plans to support newer versions of pylint? `pylint==1.6.4` was released on July 19th 2016 and numerous improvements have been made since.

**Comment by bhack** [comment]
I don't know just let see what kind sanity checks will fails with https://github.com/tensorflow/tensorflow/pull/43040.

**Comment by ScaleRunner** [comment]
I did some more digging with older versions of pylint.

No errors on `example.py`:
* last `1.x` release (`1.9.5`): ✅  
* `2.0.1` up until `2.2.3` gave an error that probably has something to do with the astroid dependency https://github.com/PyCQA/astroid/issues/649
* `2.3.3`: ✅ 
* `2.4.4`: ✅ 
* `2.5.3`: ❌ 
* `2.6.0`: ❌ 

Now these only check the minimal example above, but might give an indication of what might still work.

I saw that 69a975e6a35279a91035f601b36f6771331d6619 upgrades to `2.6.0` and the CI failed. Maybe we could try upgrading to one of the versions above?

**Comment by bhack** [comment]
With `2.6.0` the list of things to fix or ignore it is quite long:

https://source.cloud.google.com/results/invocations/65c2a3ec-39f8-4d43-823d-ba791a96cbb2/targets/%2F%2Ftensorflow%2Ftools%2Fci_build:gen_ci_sanity_out/log

**Comment by ScaleRunner** [comment]
I can imagine that the list is quite large. There are a lot of new error code introductions along the way to newer versions.

Would you (or the tensorflow team) be interested in bumping one minor pylint version at a time and fixing/disabling issues along the way? I can image that fixing (at least some of them) would require backwards-compatibility breaking changes.

**Comment by bhack** [comment]
@ScaleRunner Yes let's see what they want to do after having an overview on the LOG.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/2e2f2330c3a3c9786a9994e4c4d0b5a4/43038.ipynb). Thanks!

**Comment by zyberg2091** [comment]
can i solve this issue?

**Comment by bhack** [comment]
@mihaimaruseac Please reopen this.

**Comment by bhack** [comment]
@mihaimaruseac I've maintained the related PR branch so let know if we want to handle this with another PR or do you want to push this internally.

**Comment by mihaimaruseac** [comment]
If you want to work on it that should be good, I'll handle off on fixing this internally.

Do you want the full list of error messages?

**Comment by bhack** [comment]
@mihaimaruseac I think the problem Is more on the policy point of view and I don't know where we want to discuss this cause we need some feedbacks from the internal team. Also with the current pylint versiin we are in a mix of accepted pylint error that we ignore and things that we care. 
On what we want to expand the allowed-list and what instrad we need to fix? So we Need to collect an  internal feedback somewhere.

**Comment by mihaimaruseac** [comment]
The ignored list was seeds with errors that the internal python linting and formatting tools would allow but fail in OSS. Then stuff got added to the ignored list to fix breakages but these would need to be removed in time.

We also have inline annotations that at some point will have to be cleared if not relevant anymore but there's no timeline on that.

**Comment by bhack** [comment]
> The ignored list was seeds with errors that the internal python linting and formatting tools would allow but fail in OSS. Then stuff got added to the ignored list to fix breakages but these would need to be removed in time.
> 
> We also have inline annotations that at some point will have to be cleared if not relevant anymore but there's no timeline on that.

I think that the currently it is a little bit different cause we have  a specific error list to fail:
https://github.com/offscale/tensorflow/blob/master/tensorflow/tools/ci_build/ci_sanity.sh#L203-L213

And a general allow list:
https://github.com/offscale/tensorflow/blob/626a13aafa15d2a0d51c1cf9251a074a6b65ae3b/tensorflow/tools/ci_build/ci_sanity.sh#L100-L121

Plus inlines.
