### ISSUE TITLE
 Neural machine translation with attention issue :Translate function give Keyerror with Tunisian dialect

### ISSUE THREAD

**Issue by zeyneb-chiha** [tensorflow/tensorflow#43032]
i 'm working with attention model for Tunisian dialect _Standard arabic translation , with google colab ,

![image](https://user-images.githubusercontent.com/53334878/92415130-6b1d1580-f14f-11ea-8ffd-c56e417a2901.png)

**Comment by ravikyram** [comment]
@zeyneb-chiha 

Please, let us know which TF version you are using.
Please,fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

Please, share colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by linoqui14** [comment]
I have the same issue, and I'm stuck at it!
