### ISSUE TITLE
TF_TensorToPyArray is hard coded for equality, limits performance enhancements

### ISSUE THREAD

**Issue by avinashcpandey** [tensorflow/tensorflow#43044]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  Yes, modified TF code with overriding existing Op 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 18.04):  4.15.0-115-generic
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:  x86_64 24 core processor
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 1.15
- Python version: Python 3.7.6
- Bazel version (if compiling from source): Build label: 0.26.1
- GCC/Compiler version (if compiling from source): gcc version 7.5.0
- CUDA/cuDNN version: Not using
- GPU model and memory: Not using

**Describe the current behavior**
I am running one CNN model(which is sequential and similar to VGGNET) which has convolution and FC layers. 
For getting optimal performance, I am using o/p buffers which are allocated with allocate_persistent() API and I am reusing these buffers multiple times as next layer i/p ans new o/p as Network is pretty sequential.
Basically i am having two buffer, using it like ping pong model (keep switching b/w those in alternate way). This way making sure that buffer will always be cached in memory. 
For achieving this i am pre-allocating big chunks with allocate_persistent() API and for every Op execution i use the same buffers by setting with different shape.

With convolutions it worked fine and i see some performance gains too . However once FC layer gets executed it throws below exception. Because of this exception, I am not able to run my network.

_INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InternalError'>, ndarray was 1921920 bytes but TF_Tensor was 12331253760 bytes
I0907 13:07:13.556839 140574226294592 coordinator.py:224] Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InternalError'>, ndarray was 1921920 bytes but TF_Tensor was 12331253760 bytes_

After looking into code, I found function TF_TensorToPyArray() gets called, _line 471 in tensorflow/python/lib/core/ndarray_tensor.cc_, which compare the ndarray bytes with TF_tensor bytes, which is fine, But why does it need to be exact match?
It should have been below comparison, instead of exact match. If i do below change it works fine and i get the right results too.
PyArray_NBYTES(py_array)) >
TF_TensorByteSize(tensor.get()

This way same buffers can be used for different Op execution(in sequential case), just we need to change the shape every time.

**My pseudo code:**
// below global variables will be allocated with allocate_persistent() API
//allocated with max buffer shape
TensorOut1
TensorOut2 

//Overrided compute() kernel for these Ops
convolutionOp1(input1, TensorOut1)   //with set_shape(which is public now) i am changing to required shape for this conv o/p     
convolutionOp2(TensorOut1, TensorOut2) // same as above comment
convolutionOp3(TensorOut2, TensorOut1) // same as above comment
convolutionOp4(TensorOut1, TensorOut2) //same as above comment
.
.
fullyConnected(TensorOut1, TensorOut2)  

Once n/w is fully executed, I get below error. 
Reason is Output of FC is 2D shape(changed from set_shape). But no. of bytes allocated is more, as we are working with pre allocated buffers. 

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InternalError'>, ndarray was 1921920 bytes but TF_Tensor was 12331253760 bytes
I0907 13:07:13.556839 140574226294592 coordinator.py:224] Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InternalError'>, ndarray was 1921920 bytes but TF_Tensor was 12331253760 bytes

**Describe the expected behavior**
_I had to do two below changes in existing code_
1. Make set_shape(const TensorShape& shape) to public in tensorflow/core/framework/tensor.h
2. Change below line in tensorflow/python/lib/core/ndarray_tensor.cc ate line 471
existing:  } else if (static_cast<size_t>(PyArray_NBYTES(py_array)) !=
new:  } else if (static_cast<size_t>(PyArray_NBYTES(py_array)) >
 
With these i see expected gain in performance and correctness too. I am looking for some alternative to #1 
while #2 limits my use case, why are we comparing for equality? above suggested alternative will give this kind of flexibility to TF users

**Standalone code to reproduce the issue**

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@avinashcpandey 
Please share simple stand alone code for us to replicate issue faced, or if possible share a colab gist with the error reported.
Can you please try with 2.x versions and let us know if you still face any performance issue.

**Comment by avinashcpandey** [comment]
Hi @Saduf2019 

Its difficult for me to share the code. As I described my logic above in **current behavior and pseudo code** section, what we are trying to achieve. I need below information, so that i can do cleaner implementation.

Basically i am doing below two things for 
_1. Making set_shape(const TensorShape& shape) to **public** scope  in tensorflow/core/framework/tensor.h
2. Change below line in tensorflow/python/lib/core/ndarray_tensor.cc ate line 471
existing: } else if (static_cast<size_t>(PyArray_NBYTES(py_array)) !=
new: } else if (static_cast<size_t>(PyArray_NBYTES(py_array)) >_

I am looking for some alternative to #1 (so that i can modify the shape as per my need)
while #2 limits my use case, 
Question is why are we comparing for equality of bytes? why not just shape? 
Above suggested alternative will give this kind of flexibility to TF users to work with PerAllocated buffer coming from application and compare only the shape not the actual underlying bytes.  Bytes should not less than the use case, greater should be fine. 

Thanks in Advance.

**Comment by avinashcpandey** [comment]
Hi,
Do we have any update on this issue?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
