### ISSUE TITLE
GradientTape.batch_jacobian returns the wrong type in case of constant functions

### ISSUE THREAD

**Issue by SimonWeitzhofer** [tensorflow/tensorflow#43043]
**System information**
Google Colaboratory with TF 2.3.0, git version v2.3.0-0-gb36436b087

**Describe the current behavior**
tf.GradientTape.batch_jacobian of a constant function with return type float64 returns a zero matrix of type float32

**Describe the expected behavior**
return a zero matrix of type float64

**Standalone code to reproduce the issue**
```
@tf.function
def foo(val):
  return tf.constant([[3.0],[4.0]],dtype=tf.dtypes.float64)

c = tf.constant([[1.],[2.]],dtype=tf.dtypes.float64)
with tf.GradientTape() as g:
			g.watch(c)
			f = foo(c)

print(g.batch_jacobian(f,c)) 
```

**Other info / logs**

Workaround: setting the option unconnected_gradients to 'zero'
```
@tf.function
def foo(val):
  return tf.constant([[3.0],[4.0]],dtype=tf.dtypes.float64)

c = tf.constant([[1.],[2.]],dtype=tf.dtypes.float64)
with tf.GradientTape() as g:
			g.watch(c)
			f = foo(c)

print(g.batch_jacobian(f,c,unconnected_gradients='zero'))
```

**Comment by ravikyram** [comment]
I have tried in colab with TF versions 2.3, nightly versions(`2.4.0-dev20200908`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/35d2bc5bc15e34e22c1ce942dbb92918/untitled324.ipynb). Thanks!

**Comment by bhack** [comment]
If let interact the watched `c` with `f` it will return the correct dtype:

```
with tf.GradientTape() as g:
      c = tf.constant([[3.],[2.]],dtype=tf.dtypes.float64)
      g.watch(c)
      f = foo()*c
      print(f)
print(c)
print(g.batch_jacobian(f,c))
```

**Comment by jvishnuvardhan** [comment]
@SimonWeitzhofer Can you please check @bhack suggestion and let us know whether the issue resolved for you. Thanks!

**Comment by SimonWeitzhofer** [comment]
The function f in @bhack suggestion is not constant anymore. So, no, if the suggestion is not to use constant functions, then I don't think this is a proper solution.

Actually there is a workaround, namely setting `unconnected_gradients='zero'` as described in the bug-report.

I would be ok with tensorflow returning None or throwing an exception. Returning a float32 tensor, however, seems wrong to me.

**Comment by bhack** [comment]
Mine was not a solution it was just to check that when it is not constant anymore the dtype is working correctly.
You problem is related that in the default case `unconnect_gradients='null'` we are not handling any specific `dtype` on the source.

https://github.com/tensorflow/tensorflow/blob/31f0b2159751642a146d70561ac5095a3c4722ff/tensorflow/python/eager/pywrap_tfe_src.cc#L2804-L2814

/cc @edloper
