### ISSUE TITLE
tensorflow converter.convert() failure

### ISSUE THREAD

**Issue by yananchen1989** [tensorflow/tensorflow#43042]
I built model in tf==2.3.0 and I saved my model in SavedModel format.

Here is my conversion operation:
```
converter = tf.lite.TFLiteConverter.from_saved_model('./binary_bert_model')
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
tflite_quant_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_quant_model)
```
Here is my model summary, which is a typical text classification model.
```
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
input_3 (InputLayer)            [(None, 1)]          0
__________________________________________________________________________________________________
text_vectorization_7 (TextVecto (None, 128)          0           input_3[0][0]
__________________________________________________________________________________________________
token_and_position_embedding_2  (None, 128, 128)     1252608     text_vectorization_7[0][0]
__________________________________________________________________________________________________
transformer_block_2 (Transforme (None, 128, 128)     99584       token_and_position_embedding_2[0]
__________________________________________________________________________________________________
embedding_4 (Embedding)         (None, 128, 128)     1236224     text_vectorization_7[0][0]
__________________________________________________________________________________________________
global_average_pooling1d_10 (Gl (None, 128)          0           transformer_block_2[0][0]
__________________________________________________________________________________________________
conv1d_8 (Conv1D)               (None, 125, 128)     65664       embedding_4[0][0]
__________________________________________________________________________________________________
conv1d_9 (Conv1D)               (None, 126, 128)     49280       embedding_4[0][0]
__________________________________________________________________________________________________
conv1d_10 (Conv1D)              (None, 127, 128)     32896       embedding_4[0][0]
__________________________________________________________________________________________________
conv1d_11 (Conv1D)              (None, 128, 128)     16512       embedding_4[0][0]
__________________________________________________________________________________________________
dropout_10 (Dropout)            (None, 128)          0           global_average_pooling1d_10[0][0]
__________________________________________________________________________________________________
global_average_pooling1d_11 (Gl (None, 128)          0           conv1d_8[0][0]
__________________________________________________________________________________________________
global_max_pooling1d_8 (GlobalM (None, 128)          0           conv1d_8[0][0]
__________________________________________________________________________________________________
global_average_pooling1d_12 (Gl (None, 128)          0           conv1d_9[0][0]
__________________________________________________________________________________________________
global_max_pooling1d_9 (GlobalM (None, 128)          0           conv1d_9[0][0]
__________________________________________________________________________________________________
global_average_pooling1d_13 (Gl (None, 128)          0           conv1d_10[0][0]
__________________________________________________________________________________________________
global_max_pooling1d_10 (Global (None, 128)          0           conv1d_10[0][0]
__________________________________________________________________________________________________
global_average_pooling1d_14 (Gl (None, 128)          0           conv1d_11[0][0]
__________________________________________________________________________________________________
global_max_pooling1d_11 (Global (None, 128)          0           conv1d_11[0][0]
__________________________________________________________________________________________________
dense_20 (Dense)                (None, 64)           8256        dropout_10[0][0]
__________________________________________________________________________________________________
concatenate_4 (Concatenate)     (None, 1024)         0           global_average_pooling1d_11[0][0]
                                                                 global_max_pooling1d_8[0][0]
                                                                 global_average_pooling1d_12[0][0]
                                                                 global_max_pooling1d_9[0][0]
                                                                 global_average_pooling1d_13[0][0]
                                                                 global_max_pooling1d_10[0][0]
                                                                 global_average_pooling1d_14[0][0]
                                                                 global_max_pooling1d_11[0][0]
__________________________________________________________________________________________________
dropout_11 (Dropout)            (None, 64)           0           dense_20[0][0]
__________________________________________________________________________________________________
concatenate_5 (Concatenate)     (None, 1088)         0           concatenate_4[0][0]
                                                                 dropout_11[0][0]
__________________________________________________________________________________________________
mlp1 (Dense)                    (None, 512)          557568      concatenate_5[0][0]
__________________________________________________________________________________________________
mlp2 (Dense)                    (None, 1)            513         mlp1[0][0]
==================================================================================================
Total params: 2,082,881
Trainable params: 2,082,881
Non-trainable params: 0
__________________________________________________________________________________________________
```

Here is the failure errors:

> ---------------------------------------------------------------------------
> InvalidArgumentError                      Traceback (most recent call last)
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py in _import_graph_def_internal(graph_def, input_map, return_elements, validate_colocation_constraints, name, producer_op_list)
>     496         results = c_api.TF_GraphImportGraphDefWithResults(
> --> 497             graph._c_graph, serialized, options)  # pylint: disable=protected-access
>     498         results = c_api_util.ScopedTFImportGraphDefResults(results)
> 
> InvalidArgumentError: Input 3 of node StatefulPartitionedCall/functional_3/keras_layer_1/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/transformer_encoder/StatefulPartitionedCall was passed float from Func/StatefulPartitionedCall/functional_3/keras_layer_1/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/input/_622:0 incompatible with expected resource.
> 
> During handling of the above exception, another exception occurred:
> 
> ValueError                                Traceback (most recent call last)
> <ipython-input-7-ec5379be901e> in <module>
> ----> 1 converter.convert()
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py in convert(self)
>    1074         Invalid quantization parameters.
>    1075     """
> -> 1076     return super(TFLiteConverterV2, self).convert()
>    1077
>    1078
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py in convert(self)
>     876     frozen_func, graph_def = (
>     877         _convert_to_constants.convert_variables_to_constants_v2_as_graph(
> --> 878             self._funcs[0], lower_control_flow=False))
>     879
>     880     input_tensors = [
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/convert_to_constants.py in convert_variables_to_constants_v2_as_graph(func, lower_control_flow, aggressive_inlining)
>    1107
>    1108   frozen_func = _construct_concrete_function(func, output_graph_def,
> -> 1109                                              converted_input_indices)
>    1110   return frozen_func, output_graph_def
>    1111
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/convert_to_constants.py in _construct_concrete_function(func, output_graph_def, converted_input_indices)
>     999   new_func = wrap_function.function_from_graph_def(output_graph_def,
>    1000                                                    new_input_names,
> -> 1001                                                    new_output_names)
>    1002
>    1003   # Manually propagate shape for input tensors where the shape is not correctly
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/wrap_function.py in function_from_graph_def(graph_def, inputs, outputs)
>     648     importer.import_graph_def(graph_def, name="")
>     649
> --> 650   wrapped_import = wrap_function(_imports_graph_def, [])
>     651   import_graph = wrapped_import.graph
>     652   return wrapped_import.prune(
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/wrap_function.py in wrap_function(fn, signature, name)
>     626           signature=signature,
>     627           add_control_dependencies=False,
> --> 628           collections={}),
>     629       variable_holder=holder,
>     630       signature=signature)
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
>     984         _, original_func = tf_decorator.unwrap(python_func)
>     985
> --> 986       func_outputs = python_func(*func_args, **func_kwargs)
>     987
>     988       # invariant: `func_outputs` contains only Tensors, CompositeTensors,
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/wrap_function.py in __call__(self, *args, **kwargs)
>      85
>      86   def __call__(self, *args, **kwargs):
> ---> 87     return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
>      88
>      89   def call_with_variable_creator_scope(self, fn):
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/wrap_function.py in wrapped(*args, **kwargs)
>      91     def wrapped(*args, **kwargs):
>      92       with variable_scope.variable_creator_scope(self.variable_creator_scope):
> ---> 93         return fn(*args, **kwargs)
>      94
>      95     return wrapped
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/wrap_function.py in _imports_graph_def()
>     646
>     647   def _imports_graph_def():
> --> 648     importer.import_graph_def(graph_def, name="")
>     649
>     650   wrapped_import = wrap_function(_imports_graph_def, [])
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py in new_func(*args, **kwargs)
>     505                 'in a future version' if date is None else ('after %s' % date),
>     506                 instructions)
> --> 507       return func(*args, **kwargs)
>     508
>     509     doc = _add_deprecated_arg_notice_to_docstring(
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py in import_graph_def(***failed resolving arguments***)
>     403       return_elements=return_elements,
>     404       name=name,
> --> 405       producer_op_list=producer_op_list)
>     406
>     407
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py in _import_graph_def_internal(graph_def, input_map, return_elements, validate_colocation_constraints, name, producer_op_list)
>     499       except errors.InvalidArgumentError as e:
>     500         # Convert to ValueError for backwards compatibility.
> --> 501         raise ValueError(str(e))
>     502
>     503     # Create _DefinedFunctions for any imported functions.
> 
> ValueError: Input 3 of node StatefulPartitionedCall/functional_3/keras_layer_1/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/transformer_encoder/StatefulPartitionedCall was passed float from Func/StatefulPartitionedCall/functional_3/keras_layer_1/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/input/_622:0 incompatible with expected resource.

**Comment by bhack** [comment]
Can you shere `./binary_bert_model`?

**Comment by abattery** [comment]
Sorry. TextVectorization layer is not supported by TFLite yet. The layer requires MutableHashtable support. TFLite currently is not able to support it.

**Comment by bhack** [comment]
@abettery Do you think that it can fail with a more "readable" exception? 
If not I suppose that other tickets like this will be opened again.

**Comment by abattery** [comment]
@bhack Thanks for your suggestion. We are working on having more readability in the conversion errors. TextVectorization is kind of a new thing, which is under experimental phase. Sorry for that :-)

**Comment by bhack** [comment]
@abattery Thanks it is just to not overload triaging activities :wink:

**Comment by yananchen1989** [comment]
Yes, I use TextVectorization which adapts to the corpus and convert the text of string into word ids. 
```
maxlen = 128
vectorizer = TextVectorization(max_tokens=10000, output_sequence_length=maxlen)
text_ds = tf.data.Dataset.from_tensor_slices(df_all['content'].tolist() + df_val['content'].tolist()).batch(128)
vectorizer.adapt(text_ds)
```

**Comment by yananchen1989** [comment]
I replace the textvectorization process with the traditional tokenizer,

however, there is still errors when I try to use tf.lite convert:
[---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py in _import_graph_def_internal(graph_def, input_map, return_elements, validate_colocation_constraints, name, producer_op_list)
    496         results = c_api.TF_GraphImportGraphDefWithResults(
--> 497             graph._c_graph, serialized, options)  # pylint: disable=protected-access
    498         results = c_api_util.ScopedTFImportGraphDefResults(results)

InvalidArgumentError: Input 1 of node StatefulPartitionedCall was passed float from unknown:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-56-6718a11fca73> in <module>
      1 converter = tf.lite.TFLiteConverter.from_saved_model('./trans_model')
      2 converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
----> 3 tflite_quant_model = converter.convert()

/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py in convert(self)
   1074         Invalid quantization parameters.
   1075     """
-> 1076     return super(TFLiteConverterV2, self).convert()
   1077
   1078

/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py in convert(self)
    876     frozen_func, graph_def = (
    877         _convert_to_constants.convert_variables_to_constants_v2_as_graph(
--> 878             self._funcs[0], lower_control_flow=False))
    879
    880     input_tensors = [

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/convert_to_constants.py in convert_variables_to_constants_v2_as_graph(func, lower_control_flow, aggressive_inlining)
   1107
   1108   frozen_func = _construct_concrete_function(func, output_graph_def,
-> 1109                                              converted_input_indices)
   1110   return frozen_func, output_graph_def
   1111

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/convert_to_constants.py in _construct_concrete_function(func, output_graph_def, converted_input_indices)
    999   new_func = wrap_function.function_from_graph_def(output_graph_def,
   1000                                                    new_input_names,
-> 1001                                                    new_output_names)
   1002
   1003   # Manually propagate shape for input tensors where the shape is not correctly

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/wrap_function.py in function_from_graph_def(graph_def, inputs, outputs)
    648     importer.import_graph_def(graph_def, name="")
    649
--> 650   wrapped_import = wrap_function(_imports_graph_def, [])
    651   import_graph = wrapped_import.graph
    652   return wrapped_import.prune(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/wrap_function.py in wrap_function(fn, signature, name)
    626           signature=signature,
    627           add_control_dependencies=False,
--> 628           collections={}),
    629       variable_holder=holder,
    630       signature=signature)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    984         _, original_func = tf_decorator.unwrap(python_func)
    985
--> 986       func_outputs = python_func(*func_args, **func_kwargs)
    987
    988       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/wrap_function.py in __call__(self, *args, **kwargs)
     85
     86   def __call__(self, *args, **kwargs):
---> 87     return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
     88
     89   def call_with_variable_creator_scope(self, fn):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/wrap_function.py in wrapped(*args, **kwargs)
     91     def wrapped(*args, **kwargs):
     92       with variable_scope.variable_creator_scope(self.variable_creator_scope):
---> 93         return fn(*args, **kwargs)
     94
     95     return wrapped

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/wrap_function.py in _imports_graph_def()
    646
    647   def _imports_graph_def():
--> 648     importer.import_graph_def(graph_def, name="")
    649
    650   wrapped_import = wrap_function(_imports_graph_def, [])

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py in new_func(*args, **kwargs)
    505                 'in a future version' if date is None else ('after %s' % date),
    506                 instructions)
--> 507       return func(*args, **kwargs)
    508
    509     doc = _add_deprecated_arg_notice_to_docstring(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py in import_graph_def(***failed resolving arguments***)
    403       return_elements=return_elements,
    404       name=name,
--> 405       producer_op_list=producer_op_list)
    406
    407

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py in _import_graph_def_internal(graph_def, input_map, return_elements, validate_colocation_constraints, name, producer_op_list)
    499       except errors.InvalidArgumentError as e:
    500         # Convert to ValueError for backwards compatibility.
--> 501         raise ValueError(str(e))
    502
    503     # Create _DefinedFunctions for any imported functions.

ValueError: Input 1 of node StatefulPartitionedCall was passed float from unknown:0 incompatible with expected resource.](url)

**Comment by yananchen1989** [comment]
Here is the data preparation step:

```
maxlen = 100
def get_keras_data(df): 
    content_ids_list = tok.texts_to_sequences(df['content'].tolist())
    content_pad_array = tf.keras.preprocessing.sequence.pad_sequences(content_ids_list, maxlen=maxlen, padding='post', truncating='post',value=0)
    return [content_pad_array], df['label'].values


x_train, y_train = get_keras_data(df_all)
x_val, y_val = get_keras_data(df_val)

```

**Comment by yananchen1989** [comment]
For the tokenize version, I try to use the command line method to convert.
It seems fine.

```
tflite_convert \
  --saved_model_dir=trans_model \
  --output_file=trans_model_tflite
```

![image](https://user-images.githubusercontent.com/26405281/92549512-03b8b000-f28c-11ea-97f5-54b3f1cff09d.png)
