### ISSUE TITLE
How to use unified memory in TF2.1

### ISSUE THREAD

**Issue by JF-D** [tensorflow/tensorflow#43049]
Hi, I am trying to test unified memory performance. But I cannot find any introduction about how to use unified memory in tf2.1. Could you please offer some help? Thanks a lot!

**Comment by bhack** [comment]
Can you check https://github.com/tensorflow/tensorflow/issues/29840? /cc @jaingaurav @aaroey

**Comment by JF-D** [comment]
Yes. But I still have some problem about multi-gpu training with unified memory, and I put some new information in that issue. You can check it. @bhack

**Comment by JF-D** [comment]
Hi, For this https://github.com/tensorflow/tensorflow/issues/29840#issuecomment-689284948 , do you have any idea? Where can I find more information about UVM in tensorflow? @ravikyram @bhack

**Comment by sanjoy** [comment]
Can you try setting the env var `TF_FORCE_UNIFIED_MEMORY` to `true`?

**Comment by JF-D** [comment]
@mohantym I am sorry. I didn't continue to try unified memory with tf, and I am working on something else. So, I think this issue can be closed.

**Comment by mohantym** [comment]
Ok @JF-D !Closing issue then. Feel free to open a new issue if you face any problem.
