### ISSUE TITLE
DLL load fail _pywrap_tensorflow_internal during CPU-only installation

### ISSUE THREAD

**Issue by sRassmann** [tensorflow/tensorflow#43052]
I am trying to install the CPU-only version of tf.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64bit (v.1912)
- TensorFlow installed from (source or binary): pip (v.2.3.0), conda (v.2.1.0)
- TensorFlow version: 2.3.0
- Python version: 3.7.0 and 3.8.3
- Installed using virtualenv? conda and without using an environment
- CUDA/cuDNN version: I didn't install as my GPU doesn't support tf
- GPU model and memory: Intel HD 520
- CPU Model: Intel® Core™ Prozessor i5-6200U (based on issue #39007 I checked for AVX support, the [datasheet](https://ark.intel.com/content/www/us/en/ark/products/88193/intel-core-i5-6200u-processor-3m-cache-up-to-2-80-ghz.html) says it supports Intel® AVX2)

I tried to install tensorflow to an existing environment, which already didn't work. Trying to the fix the issue, I uninstalled anaconda (incl. caches, pip, and conda) and installed miniconda. Running the following commands:
```
$ conda create --name tf_test
$ activate tf_test
$ pip install tensorflow
$ python
>>>import tensorflow
```
I am getting the same error as before, which stays the same also without activating the conda environment:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sebas\miniconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\sebas\miniconda3\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\sebas\miniconda3\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\sebas\miniconda3\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\sebas\miniconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\sebas\miniconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: Das angegebene Modul wurde nicht gefunden. 
(*The specified module could not be found.*) 


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

Thanks for your help!

**Comment by bhack** [comment]
Tensorflow doesn't directly support conda setup but you can follow https://docs.anaconda.com/anaconda/user-guide/tasks/tensorflow/

**Comment by Saduf2019** [comment]
@sRassmann 
You could be facing this issue because of the following reasons

You you running 32-bit Python or 32-bit OS
Please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) and check if you have the correct dependencies installed.

Also, check these similar duplicate issues: #42058 #41596 #40459 #39007 #38916 #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 .

In case you still face issues after verifying the above, please create a issue on  [Anaconda repo.](https://github.com/ContinuumIO/anaconda-issues/issues), and move this to closed status.
Thanks!

**Comment by sRassmann** [comment]
@Saduf2019 & @bhack Thank you for your help!!

I performed the following steps:
- Completely uninstalled everything (ana-/miniconda and related folders)
- Installed vanilla python 3.7.0
- run ```$ pip install tensorflow``` 
- Now ```$ python``` and ```>>> import tensorflow``` worked seamlessly (besides the warning for not using GPU)

Interestingly, after I reinstalled miniconda, tensorflow also worked within conda environments.

**Comment by Saduf2019** [comment]
@sRassmann
Glad to hear we could help you resolve the issue, thanks for the update.
