### ISSUE TITLE
Tensorflow Bazel Build 

### ISSUE THREAD

**Issue by XOR0831** [tensorflow/tensorflow#43054]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3
- Python version: 3.8.5
- Installed using virtualenv? pip? conda?: No
- Bazel version (if compiling from source): 3.5.0
- CUDA/cuDNN version: 11/8.0.3
- GPU model and memory: GTX 1650

ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "C:/users/soria/downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 1377, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "C:/users/soria/downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 1162, column 17, in _create_local_cuda_repository
                cc = find_cc(repository_ctx)
        File "C:/users/soria/downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 216, column 34, in find_cc
                return _get_msvc_compiler(repository_ctx)
        File "C:/users/soria/downloads/tensorflow/third_party/gpus/cuda_configure.bzl", line 133, column 26, in _get_msvc_compiler
                return find_msvc_tool(repository_ctx, vc_path, "cl.exe").replace("\\", "/")
        File "C:/users/soria/_bazel_soria/s7y7zhp3/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 404, column 27, in find_msvc_tool
                if _is_vs_2017_or_2019(vc_path) or _is_msbuildtools(vc_path):
        File "C:/users/soria/_bazel_soria/s7y7zhp3/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 261, column 19, in _is_vs_2017_or_2019
                return vc_path.find("2017") != -1 or vc_path.find("2019") != -1
Error: 'NoneType' value has no field or method 'find'
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': 'NoneType' value has no field or method 'find'
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': 'NoneType' value has no field or method 'find'
INFO: Elapsed time: 7.514s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package

**Comment by bhack** [comment]
Can you check https://github.com/tensorflow/tensorflow/issues/43048#issuecomment-688966840?

**Comment by bhack** [comment]
And also https://www.tensorflow.org/install/source_windows?hl=en#install_visual_c_build_tools_2019

**Comment by XOR0831** [comment]
I tried installling both and it works now, but i encountered a new error.

ERROR: C:/users/soria/downloads/tensorflow/tensorflow/core/util/BUILD:823:17: ProtoCompile tensorflow/core/util/event_pb2.py failed (Exit -1073741795): protoc.exe failed: error executing command
  cd C:/users/soria/_bazel_soria/s7y7zhp3/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0
    SET PATH=C:\msys64\usr\bin;C:\msys64\bin;C:\WINDOWS;C:\WINDOWS\System32;C:\WINDOWS\System32\WindowsPowerShell\v1.0
    SET PYTHON_BIN_PATH=C:/Users/soria/AppData/Local/Programs/Python/Python38/python.exe
    SET PYTHON_LIB_PATH=C:/Users/soria/AppData/Local/Programs/Python/Python38/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TF2_BEHAVIOR=1
    SET TF_CONFIGURE_IOS=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=7.5
    SET TF_NEED_CUDA=1
  bazel-out/x64_windows-opt/bin/external/com_google_protobuf/protoc.exe --python_out=bazel-out/x64_windows-opt/bin -I. -Iexternal/com_google_protobuf/python -Ibazel-out/x64_windows-opt/bin/external/com_google_protobuf/python tensorflow/core/util/event.proto
Execution platform: @local_execution_config_platform//:platform
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 811.126s, Critical Path: 24.10s
INFO: 167 processes: 167 local.
FAILED: Build did NOT complete successfully

**Comment by bhack** [comment]
What version are you trying to compile?

**Comment by XOR0831** [comment]
HEAD (master)

**Comment by bhack** [comment]
Master or 2.3.0?

**Comment by XOR0831** [comment]
Master sorry for confusion

**Comment by bhack** [comment]
Can you check if you are compliant with others requirements at https://www.tensorflow.org/install/source_windows?

**Comment by bhack** [comment]
Also check if the current master is building sucessful in the CI for windows: https://github.com/tensorflow/tensorflow#continuous-build-status

**Comment by XOR0831** [comment]
I double checked all the requirements and make sure that i completed it. I looked at https://github.com/tensorflow/tensorflow#continuous-build-status and it says Windows GPU failing. What should i do? checkout to r2.3? and build from there?

**Comment by bhack** [comment]
> What should i do? checkout to r2.3? and build from there?
Yes It is what is suggested to check if it is master or you environment but please note that r2.3 doesn't support CUDA 11

**Comment by XOR0831** [comment]
I see so i should be downgrading my CUDA to 10.1?

**Comment by bhack** [comment]
If you want to try r2.3 yes.

**Comment by XOR0831** [comment]
Thank you
