### ISSUE TITLE
How does conv2d_transpose exactly space out inputs in tensorflow?

### ISSUE THREAD

**Issue by wgmao** [tensorflow/tensorflow#4306]
This may not be the best place to ask this question but I don't get any help from stackoverflow. Sorry if I ask this question in the wrong place.

I understand how transpose convolution works dealing with 2-D images. I just wonder how conv2d_transpose() function in tensorflow exactly adds zeros to the inputs.

Does it only pad zeros along the border, or does it insert zeros to space out inputs in a certain way?

**Comment by wgmao** [comment]
I just figure this out by running a tinny example. If you have the same question, please let me know.

**Comment by enrigalmig** [comment]
Hey @wgmao could you please share your thoughts? :)

**Comment by wgmao** [comment]
Suppose we start from a 2 by 2 matrix and apply a 2 by 2 filter in order to get a 4 by 4 matrix after the deconvolution operation.

This the starting point of the operation. (left: matrix; right: filter, no bias term)
![1](https://cloud.githubusercontent.com/assets/5178826/22154385/4cc7a076-def9-11e6-85e9-0583b5227c5e.PNG)

You can tell the way how tensorflow add zeros and do the convolution afterwards by the following figure. Basically it pads zeros after each column and row of the starting matrix. I don't try all the conv2d_transpose configuration and I think this is how the default works. 
![2](https://cloud.githubusercontent.com/assets/5178826/22154423/794786fc-def9-11e6-97d3-96e715990e99.PNG)

**Comment by karimhasebou** [comment]
@wgmao Are you sure that conv2d_transpose wraps around instead of applying more zeros ?
