### ISSUE TITLE
TF_lite Convert using integer-only quantization

### ISSUE THREAD

**Issue by huafeihuayu** [tensorflow/tensorflow#43062]
import tensorflow as tf
saved_model_dir='D:/sfz/tf_sfz'
def representative_data_gen():
  for input_value in tf.data.Dataset.from_tensor_slices(**train_images**).batch(1).take(100):
      yield [input_value]

converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
tflite_model_quant = converter.convert()
open("D:/sfz/tf_sfz/model25.tflite","wb").write(tflite_model_quant)

the **train_images** don't know what it is,I only know to select a part of the representative data, I don't know what to do next?The training data is JPG file and TXT file，They are in a folder, how do I make **train_images**?What type of **train_images** is it?Can you fix the code a little bit

**Comment by amahendrakar** [comment]
@huafeihuayu,
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!
