### ISSUE TITLE
16 bit integer quantization

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#43064]
Is there a way to use the TensorFlow Lite Converter for 16-bit quantization? If so, how should it be done?

**Comment by Saduf2019** [comment]
@peter197321 
Please refer to [this link](https://www.tensorflow.org/lite/performance/post_training_float16_quant) and let us know.

**Comment by peter197321** [comment]
The link you share is about a float 16-bit quantization (Post-training float16 quantization) but I'm looking for integer 16-bit quantization...

**Comment by Saduf2019** [comment]
@peter197321 
Refer to [this link](https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only_16-bit_activations_with_8-bit_weights_experimental), it is 16 bit int.

**Comment by peter197321** [comment]
it seems the missing ops implementation e.g.: RESIZE_NEAREST_NEIGHBOR

**Comment by Saduf2019** [comment]
@peter197321 
We see that the issue template has not been filled, can you please let us know the tf version used.
We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!
Please refer to this issue #33893 with same error.

**Comment by peter197321** [comment]
used the latest tf-nighlty build (supposed it's 2.4) and not working - the issue is about int8 ... ?

**Comment by Saduf2019** [comment]
@peter197321 
Please move this issue to closed status as the code error you reported above is tracked at #43080.
Also please refer to [this link](https://github.com/tensorflow/tensorflow/issues/42024#issuecomment-668744454) and let us know if it helps.
