### ISSUE TITLE
Training of a simple model with KerasLayer hangs on macOSX with tf 2.3.0

### ISSUE THREAD

**Issue by andreyryabov** [tensorflow/tensorflow#43060]
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
custom code

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
macOS X 10.15.4 (19E287)

- TensorFlow installed from (source or binary):
binary

- TensorFlow version (use command below):
v2.3.0-rc2-23-gb36436b087 2.3.0

- Python version:
Python 3.7.3

**Describe the current behavior**
Simple model training hangs on macOS X with tf 2.3.0, but works in Colab and on macOS X with tf 2.2.0

**Describe the expected behavior**
should wourk

**Standalone code to reproduce the issue**

```

import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as tf_text


print(tf.__version__)
print(tf.keras.__version__)

EMBEDDING = "https://tfhub.dev/google/universal-sentence-encoder-multilingual/3"

embed = hub.KerasLayer(EMBEDDING, dtype=tf.string, trainable=True)

s1 = tf.keras.Input(shape=[], dtype=tf.string)
s2 = tf.keras.Input(shape=[], dtype=tf.string)

v1 = embed(s1)
v2 = embed(s2)

cd = tf.reduce_sum(tf.multiply(v1, v2), axis=-1)

train_model = tf.keras.Model(inputs=[s1, s2], outputs=[cd])
optimizer = tf.optimizers.SGD(learning_rate=0.001)

i1 = tf.constant(["x", "y", "z"])
i2 = tf.constant(["a", "b", "c"])
c0 = tf.constant([1.0, 1.0, 1.0])

train_model.compile(optimizer=optimizer, loss="mse", metrics=["mse"])
train_model.fit(x=[i1, i2], y=c0, batch_size=1, epochs=5, verbose=2)


```

**Comment by ravikyram** [comment]
@andreyryabov 

I have tried in colab with TF version 2.3 and i am not seeing any issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/eca6c8c8564c33f6d0dd2f9b5248ca6b/untitled325.ipynb).Can you please share error log you are getting. Thanks!

**Comment by andreyryabov** [comment]
I does work in colab, as I mentioned in the description.  It freezes only when launched macOS. I traced it's a deadlock on some conditional variable deep in C++ code. There are no errors in the log since the code just hangs on .fit()

**Comment by bhack** [comment]
@andreyryabov In the ticket I see `v2.3.0-rc2-23-gb36436b087`. What Is your version?

**Comment by andreyryabov** [comment]
My version of TF:  2.3.0,   GIT: v2.3.0-rc2-23-gb36436b087
returned by command:
 `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Comment by bhack** [comment]
Can you reproduce this on your machine with tf-nightly?

**Comment by andreyryabov** [comment]
The problem reproduces with tf-nightly.

**Comment by bhack** [comment]
What is your installed version of `tensorflow-hub`?

**Comment by andreyryabov** [comment]
tensorflow-hub: 0.9.0

**Comment by bhack** [comment]
Can you just try to temp change your TFHUB cache dir on a new one with:
```
import os
os.environ["TFHUB_CACHE_DIR"] =<you_new_selected_cache_dir>
```
