### ISSUE TITLE
No gradients provided for any variable

### ISSUE THREAD

**Issue by godanyitamas** [tensorflow/tensorflow#43065]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.3.0
- Python version: 3.7.7
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

The problem is in the learn function, and more specifically the actor network's update with tape gradient.

I am trying to calculate the gradients with respect to the model's trainable variables. I use tf.reduce_mean() to calculate loss that i am going to use. I have tried to define a @tf.function to calculate the reduced mean, but that doesn't help either. 
There are trainable variables, the loss value is not zero. The buffer and network files are not included here, i know, but maybe there could be a fix found with just looking at the code.

What's interesting to me is that before the problem, i also calculate gradients for the other networks without a problem.

**Describe the expected behavior**

**Standalone code to reproduce the issue**
""" Twin delayed deep deterministic policy gradient agent: """
import tensorflow as tf
import matplotlib.pyplot as plt
import os
import datetime
import numpy as np
from tensorflow.keras.optimizers import Adam
from Networks import ActorNetwork, CriticNetwork
from Buffer import Buffer

class Agent:
    def __init__(self,
                 lr_actor,
                 lr_critic,
                 num_actions,
                 num_states,
                 gamma,
                 tau,
                 batch_size,
                 b_size,
                 fc1_actor,
                 fc2_actor,
                 fc1_critic,
                 fc2_critic
                 ):
        # Saving variables:
        self.num_actions = num_actions
        self.num_states = num_states
        self.gamma = gamma
        self.tau = tau
        self.batch_size = batch_size
        self.buffer = Buffer(buffer_size=b_size, batch_size=batch_size, num_states=num_states, num_action=num_actions)

        # Networks:
        self.actor = ActorNetwork(n_actions=num_actions, fc1_dims=fc1_actor, fc2_dims=fc2_actor, name='Actor')
        self.target_actor = ActorNetwork(n_actions=num_actions, fc1_dims=fc1_actor, fc2_dims=fc2_actor,
                                         name='ActorTarget')
        self.critic1 = CriticNetwork(n_actions=num_actions, fc1_dims=fc1_critic, fc2_dims=fc2_critic, name="Critic1")
        self.critic2 = CriticNetwork(n_actions=num_actions, fc1_dims=fc1_critic, fc2_dims=fc2_critic, name="Critic2")
        self.target_critic1 = CriticNetwork(n_actions=num_actions, fc1_dims=fc1_critic, fc2_dims=fc2_critic,
                                            name="CriticTarget1")
        self.target_critic2 = CriticNetwork(n_actions=num_actions, fc1_dims=fc1_critic, fc2_dims=fc2_critic,
                                            name="CriticTarget2")

        # Compiling the networks:
        self.actor.compile(optimizer=Adam(learning_rate=lr_actor))
        self.target_actor.compile(optimizer=Adam(learning_rate=lr_actor))
        self.critic1.compile(optimizer=Adam(learning_rate=lr_critic))
        self.critic2.compile(optimizer=Adam(learning_rate=lr_critic))
        self.target_critic1.compile(optimizer=Adam(learning_rate=lr_critic))
        self.target_critic2.compile(optimizer=Adam(learning_rate=lr_critic))

        self.update_target_networks()

    def learn(self, timestep):
        # If there is not enough data, just return, don't learn from zeroes
        if self.buffer.counter < self.batch_size:
            return
        """ 
        Learning comes after: 
        - choosing action
        - implementing that action
        - storing new variables in buffer
        """
        s_batch, a_batch, r_batch, ns_batch = self.buffer.batch_sample()
        s_batch = tf.convert_to_tensor(s_batch, dtype=tf.float64)
        a_batch = tf.convert_to_tensor(a_batch, dtype=tf.float64)
        r_batch = tf.convert_to_tensor(r_batch, dtype=tf.float32)
        ns_batch = tf.convert_to_tensor(ns_batch, dtype=tf.float64)

        next_action = self.actor(ns_batch)
        noise = tf.random.normal(shape=(1, self.num_actions), mean=0.0, stddev=0.2)
        noise = np.clip(noise, -0.5, 0.5)
        next_action += noise
        next_action = np.clip(next_action, -1, 1)

        # next_action = tf.convert_to_tensor(next_action)
        """ Update of the critic networks with gradient """
        with tf.GradientTape(persistent=True) as tape:
            # Target Q values via target critic networks (next state, next action)
            q1_ = tf.squeeze(self.target_critic1(ns_batch, next_action))
            q2_ = tf.squeeze(self.target_critic2(ns_batch, next_action))

            # Choose minimum from these two values for the double Q update rule
            q_ = tf.math.minimum(q1_, q2_)
            # Calculate actual Q value:
            y = r_batch + (self.gamma * q_)

            # Current Q values via critic networks (state, action)
            q1 = self.critic1(s_batch, a_batch)
            q2 = self.critic2(s_batch, a_batch)

            # Loss is calculated as the sum of the MSE loss between target Q value and q1, q2
            q1_loss = tf.keras.losses.MSE(y, q1)
            q2_loss = tf.keras.losses.MSE(y, q2)
            q_loss = q1_loss + q2_loss

            # Optimize critic networks:
        critic_gradient = tape.gradient(q_loss, self.critic1.trainable_variables)
        self.critic1.optimizer.apply_gradients(
            zip(critic_gradient, self.critic1.trainable_variables))

        critic_gradient = tape.gradient(q_loss, self.critic2.trainable_variables)
        self.critic2.optimizer.apply_gradients(
            zip(critic_gradient, self.critic2.trainable_variables))
        del tape

        if timestep % 2:
            # Update actor with gradient
            with tf.GradientTape() as tape:
                actions = tf.convert_to_tensor(self.actor(s_batch))
                critic_value = tf.squeeze(-self.critic1(s_batch, actions))
                actor_loss = tf.math.reduce_mean(critic_value)

            actor_grad = tape.gradient(actor_loss, self.actor.trainable_variables)
            self.actor.optimizer.apply_gradients(
                zip(actor_grad, self.actor.trainable_variables))

            self.update_target_networks()

    def update_target_networks(self):

        # Update target critics: - soft update with tau

        new_weights_1 = []
        target_variables_1 = self.target_critic1.weights
        for i, variable in enumerate(self.critic1.weights):
            new_weights_1.append(variable * self.tau + target_variables_1[i] * (1 - self.tau))
        self.target_critic1.set_weights(new_weights_1)

        new_weights_2 = []
        target_variables_2 = self.target_critic2.weights
        for i, variable in enumerate(self.critic2.weights):
            new_weights_2.append(variable * self.tau + target_variables_2[i] * (1 - self.tau))
        self.target_critic2.set_weights(new_weights_2)

        # Update target actor:
        new_weights_3 = []
        target_variables_3 = self.target_actor.weights
        for i, variable in enumerate(self.actor.weights):
            new_weights_3.append(variable * self.tau + target_variables_3[i] * (1 - self.tau))
        self.target_actor.set_weights(new_weights_3)

**Comment by amahendrakar** [comment]
@godanyitamas,
On running the given code, I am facing an error stating `ModuleNotFoundError: No module named 'Networks'`. 

Also the code provided is fairly complex, hence it would be difficult for us to pinpoint the issue. Can you remove the dependencies and get the example down to the simplest possible repro? That will allow us to debug the issue easily. Thanks!

**Comment by amahendrakar** [comment]
@godanyitamas,
Please go through the comments from this similar issue [#1511](https://github.com/tensorflow/tensorflow/issues/1511) and let us know if it helps. Thanks!
