### ISSUE TITLE
Model Predict problem when used one data at a time

### ISSUE THREAD

**Issue by aumombelli** [tensorflow/tensorflow#43068]
**System information**
- Have I written custom code **Yes**
- OS Platform and Distribution : **docker tensorflow/tensorflow:2.2.0-gpu**
- TensorFlow version (use command below): **2.2.0**
- Python version: **3.6.9**
- CUDA/cuDNN version: **V10.1.243**
- GPU model and memory: **TITAN X (Pascal) 12Go**

**Describe the current behavior**

I am currently trying to learn the sum of 2 digits thanks to Keras.
My input is an array of 2 ints and output is one value.

The problem is in the predict function :
When using << model.predict >> with a batch, it works perfectly !
However, when trying to predict one data at a time, << model.predict >> doesn't work as it should and return a warning :

> WARNING:tensorflow:Model was constructed with shape (None, 2) for input Tensor("input_1:0", shape=(None, 2), dtype=float32), but it was called on an input with incompatible shape (None, 1).

**Describe the expected behavior**

Using the exact same code in docker tensorflow/tensorflow:1.9.0-py3, both method (batch or one data at a time) gives the same results.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1kkXVQAKHlztpqjn1XaBPNdbwJz21JOWa?usp=sharing

**Comment by ravikyram** [comment]
I have tried in colab with TF versions 2.3, nightly versions(`2.4.0-dev20200908`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/930e5b200a6aa3939fdad7b1eef7b928/untitled326.ipynb). Thanks!

**Comment by bhack** [comment]
@aumombelli Can you try:
```
#anormal
for i in range(5):
    print("Index: {0} X_data: {1} - Predict on X_data: {2}".format(i, x_data[i], model.predict([[x_data[i]]])))
```

**Comment by aumombelli** [comment]
> @aumombelli Can you try:
> 
> ```
> #anormal
> for i in range(5):
>     print("Index: {0} X_data: {1} - Predict on X_data: {2}".format(i, x_data[i], model.predict([[x_data[i]]])))
> ```

Here is the result :

> Index: 0 X_data: [2 2] - Predict on X_data: [[2.0177724]
>  [2.0177724]]
> Index: 1 X_data: [0 5] - Predict on X_data: [[0.01705379]
>  [5.016993  ]]
> Index: 2 X_data: [3 8] - Predict on X_data: [[3.0168335]
>  [8.016044 ]]
> Index: 3 X_data: [0 1] - Predict on X_data: [[0.01705379]
>  [1.0175974 ]]
> Index: 4 X_data: [0 5] - Predict on X_data: [[0.01705379]
>  [5.016993  ]]

The notebook has been modified accordingly.

**Comment by bhack** [comment]
I've tested in @ravikyram Colab. You need to try with `pip install tensorflow-gpu==2.3.0`

**Comment by aumombelli** [comment]
> I've tested in @ravikyram Colab. You need to try with `pip install tensorflow-gpu==2.3.0`

I added `!pip install tensorflow-gpu==2.3.0` to my notebook but I get the same result as earlier.

**Comment by bhack** [comment]
Yes sorry it was that on the second run of that cell the warning disappeared.
On the single predict your shape is (2,) so you could test with:

```
#anormal
for i in range(5):
    x= tf.expand_dims(x_data[i], axis=0)
    print(x.shape)
    print("Index: {0} X_data: {1} - Predict on X_data: {2}".format(i, x_data[i], model.predict(x)))
```

**Comment by aumombelli** [comment]
It worked as expected ! Thanks @bhack 
If I understand correctly it seems that numpy array does not transform correctly into a tf.Tensor, is that right ?

**Comment by bhack** [comment]
@aumombelli Using indexing It is like:
```
#anormal
for i in range(5):
    x = x_data[None,i,:]
    x_pred = model(x, training=False)
    print("Index: {0} x: {1} - Predict on y: {2}".format(i, x, x_pred))
    y = tf.expand_dims(x_data[i],axis=0)
    y_pred = model(x,training=False)
    print("Index: {0} x: {1} - Predict on y: {2}".format(i, y, y_pred))
    assert x_pred == y_pred
```

**Comment by aumombelli** [comment]
Ok I understand ! Thanks a lot !
