### ISSUE TITLE
imx8 tflite opencl 

### ISSUE THREAD

**Issue by wangqiang624731186** [tensorflow/tensorflow#43063]
platform:imx8
tensorflow:2.3
 
tflite support **Vivante** OpenCL device **gc7000l** ???
i can not found **Vivante** in code   tensorflow/tensorflow/lite/delegates/gpu/cl/cl_device.h
**enum class Vendor { QUALCOMM, MALI, POWERVR, NVIDIA, AMD, INTEL, UNKNOWN }**

**Comment by terryheo** [comment]
The current OpenCL implementation still relies on libEGL and libGLESv2 which are available on Android.
Are these libraries available on your iMX8m device?

@impjdi correct me if I'm wrong.

**Comment by impjdi** [comment]
libGLESv3.a and libEGL.a are required for OpenGL; libOpenCL-pixel.so is required for OpenCL.  However, the way our delegate is set up, you will need both (with the latter being optional).

OpenCL is linked in dynamically; the delegate will try a dlopen("libOpenCL-pixel.so") and decide OpenCL's availability.  I don't know what imx8 is and what Vivante is, but you may have to navigate around that.

**Comment by terryheo** [comment]
BTW, I've found a way to use OpenCL with non Android devices.
You can build the TFLite benchmark tool which supports OpenCL GPU delegate as following.

$ bazel build --config=elinux_aarch64 -c opt --copt=-DCL_DELEGATE_NO_GL --copt=-DEGL_NO_X11 tensorflow/lite/tools/benchmark:benchmark_model
