### ISSUE TITLE
[tflite] Processing time is high in Windows 10 but better in Ubuntu 16.0

### ISSUE THREAD

**Issue by Sreerag-ibtl** [tensorflow/tensorflow#43061]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): From binary
- TensorFlow version (use command below): 2.3
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I am running [this](https://github.com/metalwhale/hand_tracking) project. When run on an Ubuntu 16.04 machine it takes delay of ~0.2 S. The processor is I3, and RAM 4GB. But when I ran this on a Windows 10 machine having I7 processor and RAM 4GB, the delay is increased. It varies in the range of 0.4-0.6 S. I tried the TFLite runtime also. But delay is increased. 
**Describe the expected behavior**
Running on a processor with high spec should be giving a better performance.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
https://github.com/metalwhale/hand_tracking

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@Sreerag-ibtl 
Is it possible for you to share a simple stand alone code to replicate the issue reported or share a colab gist.

**Comment by thaink** [comment]
@Sreerag-ibtl Please provide performance profiling using following tool with --enable_op_profiling=true. https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark

From there we can see which op is not performing well.
