### ISSUE TITLE
 tf.data.experimental.make_csv_dataset seems to fail on this dataset; https://archive.ics.uci.edu/ml/datasets/Parkinsons+Telemonitoring

### ISSUE THREAD

**Issue by harica** [tensorflow/tensorflow#43074]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Used sample code using api given in tensorflow 2.0 (as opposed to using a stock example script provided in TensorFlow):
- colab:
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow present in the colab, version 2.3.0:

**Standalone code to reproduce the issue**

The data set was downloaded from https://archive.ics.uci.edu/ml/datasets/Parkinsons+Telemonitoring and the following was used to read the dataset, that resulted in an error:
Sample data:
subject#,age,sex,test_time,motor_UPDRS,total_UPDRS,Jitter(%),Jitter(Abs),Jitter:RAP,Jitter:PPQ5,Jitter:DDP,Shimmer,Shimmer(dB),Shimmer:APQ3,Shimmer:APQ5,Shimmer:APQ11,Shimmer:DDA,NHR,HNR,RPDE,DFA,PPE
1,72,0,5.6431,28.199,34.398,0.00662,3.38e-005,0.00401,0.00317,0.01204,0.02565,0.23,0.01438,0.01309,0.01662,0.04314,0.01429,21.64,0.41888,0.54842,0.16006
1,72,0,12.666,28.447,34.894,0.003,1.68e-005,0.00132,0.0015,0.00395,0.02024,0.179,0.00994,0.01072,0.01689,0.02982,0.011112,27.183,0.43493,0.56477,0.1081
1,72,0,19.681,28.695,35.389,0.00481,2.462e-005,0.00205,0.00208,0.00616,0.01675,0.181,0.00734,0.00844,0.01458,0.02202,0.02022,23.047,0.46222,0.54405,0.21014
1,72,0,25.647,28.905,35.81,0.00528,2.657e-005,0.00191,0.00264,0.00573,0.02309,0.327,0.01106,0.01265,0.01963,0.03317,0.027837,24.445,0.4873,0.57794,0.33277
1,72,0,33.642,29.187,36.375,0.00335,2.014e-005,0.00093,0.0013,0.00278,0.01703,0.176,0.00679,0.00929,0.01819,0.02036,0.011625,26.126,0.47188,0.56122,0.19361
1,72,0,40.652,29.435,36.87,0.00353,2.29e-005,0.00119,0.00159,0.00357,0.02227,0.214,0.01006,0.01337,0.02263,0.03019,0.009438,22.946,0.53949,0.57243,0.195
1,72,0,47.649,29.682,37.363,0.00422,2.404e-005,0.00212,0.00221,0.00637,0.04352,0.445,0.02376,0.02621,0.03488,0.07128,0.01326,22.506,0.4925,0.54779,0.17563
1,72,0,54.64,29.928,37.857,0.00476,2.471e-005,0.00226,0.00259,0.00678,0.02191,0.212,0.00979,0.01462,0.01911,0.02937,0.027969,22.929,0.47712,0.54234,0.23844
1,72,0,61.669,30.177,38.353,0.00432,2.854e-005,0.00156,0.00207,0.00468,0.04296,0.371,0.01774,0.02134,0.03451,0.05323,0.013381,22.078,0.51563,0.61864,0.20037

The date was sucessfuly read into data set using:
types=[tf.int32,tf.int32,tf.int32,tf.float64,tf.float64,tf.float64,tf.float64,tf.float64,tf.float64,tf.float64,tf.float64,tf.float64,tf.float64,tf.float64,tf.float64,tf.float64,tf.float64,tf.float64,tf.float64,tf.float64,tf.float64,tf.float64]
adataset = tf.data.experimental.CsvDataset(data, types, header=True)

However, when attempted to read from the following, it generates error:
column_names=['subject#','age','sex','test_time','motor_UPDRS','total_UPDRS','Jitter(%)','Jitter(Abs)',
              'Jitter:RAP','Jitter:PPQ5','Jitter:DDP','Shimmer','Shimmer(dB)','Shimmer:APQ3','Shimmer:APQ5',
              'Shimmer:APQ11','Shimmer:DDA','NHR','HNR','RPDE','DFA','PPE']
labels=column_names.pop(4)
labels=[labels,column_names.pop(4)]
print(labels)
print(column_names)
batch_size = 32

train_dataset = tf.data.experimental.make_csv_dataset(
    data,
    batch_size,
    column_names=column_names,
    label_name=labels,
    num_epochs=1)

**Other info / logs** Include any logs or source code that would be helpful to

Generates error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-a43b43d3b38b> in <module>()
      6     column_names=column_names,
      7     label_name=labels,
----> 8     num_epochs=1)

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/experimental/ops/readers.py in _next_csv_row(filenames, num_cols, field_delim, use_quote_delim, header, file_io_fn)
    123         if len(csv_row) != num_cols:
    124           raise ValueError(
--> 125               "Problem inferring types: CSV row has different number of fields "
    126               "than expected.")
    127         yield csv_row

ValueError: Problem inferring types: CSV row has different number of fields than expected.
**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1JM1iQk5ZXWo9O9JwKpab58aQyYYERty0?usp=sharing

**Comment by bhack** [comment]
Please unlock you colab example cause it requires authentication.

**Comment by Saduf2019** [comment]
@harica 
Error reported does not seem like a bug or feature request for tensorflow, which can be seen only after you share complete stand alone code for us to analyse.
As per the error reported:
You may refer to [this link](https://stackoverflow.com/questions/59843548/python-valueerror-csv-row-has-different-number-of-fields-with-csv-and-tensorf) and let us know if it helps.

**Comment by harica** [comment]
Can you let me know how to unlock the notebook?
Sorry, I do not know how to do it...


Hari Kunamneni
(408) 910-5384
hkunamneni@hotmail.com<mailto:hkunamneni@hotmail.com>
This electronic message transmission contains information from Hari P. Kunamneni, Patent Agent,  that may be confidential or privileged. The information in this message is only for the use of the intended recipient. If you are not the intended recipient, be aware that any disclosure, copying, distribution or other use of the contents of this electronic message is strictly prohibited. If you have received this electronic transmission in error, please notify the sender immediately.

________________________________

**Comment by harica** [comment]
Okay, I have updated the link, so that any one with access to link can access the notebook.

...



Hari Kunamneni
(408) 910-5384
hkunamneni@hotmail.com<mailto:hkunamneni@hotmail.com>
This electronic message transmission contains information from Hari P. Kunamneni, Patent Agent,  that may be confidential or privileged. The information in this message is only for the use of the intended recipient. If you are not the intended recipient, be aware that any disclosure, copying, distribution or other use of the contents of this electronic message is strictly prohibited. If you have received this electronic transmission in error, please notify the sender immediately.

________________________________

**Comment by harica** [comment]
To be concise, currently the api used does not support more than one label *multiple outputs) for the dataset as it takes only one string. If I am wrong, please let me know. Below is the API, description:

label_name | A optional string corresponding to the label column. If provided, the data for this column is returned as a separate Tensor from the features dictionary, so that the dataset complies with the format expected by a tf.Estimator.train or tf.Estimator.evaluate input function.
-- | --

**Comment by harica** [comment]
By the way, label when provided as string, the API, does create the dataset.

**Comment by bhack** [comment]
> ValueError: Problem inferring types: CSV row has different number of fields than expected.

@harica I don't think it is a bug you problem is that you have removed `column_names` elements with `pop` so it is mismatching csv row elements.
```
train_dataset = tf.data.experimental.make_csv_dataset(
    data,
    batch_size,
    column_names=column_names,
    field_delim=',',
    label_name=labels[0],
    num_epochs=1)
```

**Comment by harica** [comment]
Okay, I agree, it is not a bug as the API defined right now.
However, the API, lacks capability to have multiple labels(multiple outputs) for the network. Therefore, the API may need to be enhanced to provide a way to pass more than one label column ...



Hari Kunamneni
(408) 910-5384
hkunamneni@hotmail.com<mailto:hkunamneni@hotmail.com>
This electronic message transmission contains information from Hari P. Kunamneni, Patent Agent,  that may be confidential or privileged. The information in this message is only for the use of the intended recipient. If you are not the intended recipient, be aware that any disclosure, copying, distribution or other use of the contents of this electronic message is strictly prohibited. If you have received this electronic transmission in error, please notify the sender immediately.

________________________________

**Comment by bhack** [comment]
@harica I think that you can close this and open a new feature request issue just for that proposal API change.

**Comment by harica** [comment]
As per request, this issue is closed. And feature enhancement request has been opened: #43083
