### ISSUE TITLE
Duplicate code in `tf.python.keras.engine.training.Model.evaluate()`, `train_on_batch()` and `test_on_batch()`

### ISSUE THREAD

**Issue by alexandrehuat** [tensorflow/tensorflow#43072]
There is some duplicate code in methods ``tf.python.keras.engine.training.Model.evaluate()``, ``train_on_batch()`` and ``test_on_batch()``. I am not sure to have time to make a clean pull request so I report the duplicate and a solution here and someone may be able to fix it sooner.

The duplicate code is at the end of each method:
```python
    logs = tf_utils.to_numpy_or_python_type(logs)
    if return_dict:
      return logs
    else:
      results = [logs.get(name, None) for name in self.metrics_names]
      if len(results) == 1:
        return results[0]
      return results
```

I propose to factorize this code into a new private method ``_format_logs_results(self, logs, return_dict)``. Very easy fix, it seems, but not useless. It would allow to operate on the logs just before the return statement all in one.

**Comment by rishabhvarshney14** [comment]
If this is not done already can I work on it? Thanks.

**Comment by sachinprasadhs** [comment]
The code has been moved from `tf.python.keras.engine.training.Model.evaluate()` to `[tf.keras.Model.evaluate()](https://www.tensorflow.org/api_docs/python/tf/keras/Model?version=nightly#evaluate)`, and I can see the changes in code as well in the file [here](https://github.com/keras-team/keras/blob/master/keras/engine/training.py#L1567-L1733). 
Let us know if you still need any changes in the above linked code. Thanks!

**Comment by alexandrehuat** [comment]
It looks okay to me. There are a few differences with the original code but I suppose there have been other updates that I haven't followed. Good job. I'm closing the issue.

**Comment by sachinprasadhs** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
