### ISSUE TITLE
 TF 2.3 ImportError: DLL load failed: The specified module could not be found. 

### ISSUE THREAD

**Issue by profzamorra** [tensorflow/tensorflow#43085]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source?
- TensorFlow version: 2.3
- Python version: 3.6
- Installed using virtualenv? pip? conda? pip
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): na
- CUDA/cuDNN version: 10.1
- GPU model and memory: cpu

I run this code 

import tensorflow as tf
print(tf.__version__)

and this error log appears

Traceback (most recent call last):
  File "D:\Christian\ML\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Christian/ML/main.py", line 1, in <module>
    import tensorflow as tf
  File "D:\Christian\ML\venv\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "D:\Christian\ML\venv\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "D:\Christian\ML\venv\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "D:\Christian\ML\venv\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "D:\Christian\ML\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "D:\Christian\ML\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

Failed to load the native TensorFlow runtime.

**Comment by bhack** [comment]
Do you have installed  C++ redistributable? https://support.microsoft.com/it-it/help/2977003/the-latest-supported-visual-c-downloads

**Comment by ravikyram** [comment]
@profzamorra 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website.](https://www.tensorflow.org/install/source_windows)

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.Please, refer similar issues #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
Thanks!

**Comment by profzamorra** [comment]
My cpu model is Intel Core i7-4771 3,5Ghz and the latest version of C++ Redistributable is 2017 14.11.23325, installed 13.6.2020.

**Comment by ravikyram** [comment]
@profzamorra 

Anaconda by default has a Python environment of its own, which comes with TensorFlow preinstalled.TensorFlow is tested and supported on 64-bit systems.So you'll need Anaconda 64 bit for this.

Alternatively,if you want to install TensorFlow on Python (ie. without Anaconda), please check if you have all the compatible hardware and software requirements mentioned [here](https://www.tensorflow.org/install/pip?lang=python3#system-requirements).Thanks!
