### ISSUE TITLE
List of tensor names in graph in Tensorflow

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#43082]
I got a snippet of code for [List of tensor names in graph in Tensorflow](https://stackoverflow.com/questions/35336648/list-of-tensor-names-in-graph-in-tensorflow)

```
import tensorflow as tf
a = tf.Variable(5)
b = tf.Variable(6)
c = tf.Variable(7)
d = (a + b) * c

for i in tf.get_default_graph().get_operations():
    print (i.name)
```

but under tf2.x this ends with error:

```
2020-09-09 18:24:25.626596: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Traceback (most recent call last):
  File "c:/DATA/Projects/AITEC/unet/ops.py", line 7, in <module>
    for i in tf.get_default_graph().get_operations():
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

```

can you advise on this?

**Comment by ravikyram** [comment]
@peter197321 

Can you please replace `tf.get_default_graph().get_operations()` with `tf.compat.v1.get_default_graph().get_operations()` in your code.I am not seeing any issue after replacing with `tf.compat.v1.get_default_graph().get_operations()`.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/2e53b15819b940d4be07158c7945784a/untitled327.ipynb).Thanks!

**Comment by peter197321** [comment]
under tf1.x, I see the output

Variable/initial_value
Variable
Variable/Assign
Variable/read
Variable_1/initial_value
Variable_1
Variable_1/Assign
Variable_1/read
Variable_2/initial_value
Variable_2
Variable_2/Assign
Variable_2/read
add
mul

but under your modification under tf2.x, I see nothing ...

**Comment by bhack** [comment]
TF2 Is in eager mode by default.
Add `tf.compat.v1.disable_eager_execution()` after your import.

**Comment by peter197321** [comment]
Now, it works :)

![image](https://user-images.githubusercontent.com/46971586/92636129-28864500-f2d7-11ea-88a2-d5bd0cbda138.png)

Thank you.
