### ISSUE TITLE
Link doesn't work.

### ISSUE THREAD

**Issue by yash-2209** [tensorflow/tensorflow#43089]
Link for _TensorFlow graph optimization with Grappler_ from url https://www.tensorflow.org/guide/tf_numpy#performance_comparisons does not exist.
The link points to page https://www.tensorflow.org/guide/guide/graph_optimization which give Page not found error

**Comment by guptadhaval18** [comment]
Can I create a pull request to fix this issue?

**Comment by bhack** [comment]
https://github.com/tensorflow/docs/pull/1667

**Comment by MarkDaoust** [comment]
This is fixed.
