### ISSUE TITLE
Issue on Load Trax

### ISSUE THREAD

**Issue by kujaomega** [tensorflow/tensorflow#43086]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution: Linux Ubuntu 18.04
- Docker container: tensorflow/tensorflow:latest-devel-gpu (sha256:81b1629c567b638dbc197aa24aa7aaa22b84ae88d1bb6c963fa7e3d970cbe77e)
- CUDA/cuDNN version: Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0
- GPU model and memory: nvidia gtx 1060 6gb

**Describe the current behavior**
I have installed jupyter in the tensorflow/tensorflow:latest-devel-gpu  docker image, I'm running the following files:

```
!pip install --upgrade jax
!pip install --upgrade jaxlib
!pip install --upgrade trax

!pip install --upgrade 'https://storage.googleapis.com/jax-releases/cuda110/jaxlib-0.1.51-cp36-none-manylinux2010_x86_64.whl'

!pip install --upgrade jax
```

```
from jax.lib import xla_bridge
print(xla_bridge.get_backend().platform)
```
But when I run this code, I'm getting the following error (The GPU is not loading):
`E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: UNKNOWN ERROR (-1)`

**Describe the expected behavior**
When I run the code with the docker image tensorflow/tensorflow:nightly-gpu-jupyter everything is working as expected.

**Comment by bhack** [comment]
Is `tensorflow/tensorflow:latest-devel-gpu` updated?

**Comment by Saduf2019** [comment]
@kujaomega 
Please update as per above comment.
please refer to existing issues and let us know: #7653 #32623 [link](https://stackoverflow.com/questions/48658204/tensorflow-failed-call-to-cuinit-cuda-error-no-device)

**Comment by kujaomega** [comment]
> Is `tensorflow/tensorflow:latest-devel-gpu` updated?

Yes, I have already test it today 2020-9-23 using `tensorflow/tensorflow:latest-devel-gpu` image updated today without using cache.

**Comment by Saduf2019** [comment]
@kujaomega 
Is this still an issue.
