### ISSUE TITLE
[BodyPix] Improve body segmentation(flickering edges) updates for a video stream 

### ISSUE THREAD

**Issue by mchandrra** [tensorflow/tensorflow#43081]
This is related to body segmentation using body-pix.
body segmentation has a flickering effect around the edges for a video stream.
Even setting edgeBlurAmount to maximum for the bokeh effect still had flickering effect around the edges since we are continuously trying to predict, segment and update frames from a video. 
Had similar flickering around the edges when i get image data from the segmentation and write it to a canvas. Is there any way to minimize/reduce the flickering around the edges?

**System information**
- TensorFlow version (you are using): tfjs@2.1.0, body-pix@2.0.5

- Are you willing to contribute it (Yes/No): 
Yes, I'm willing to help with whatever i can. But,  I'm not familiar with tensorflow models though.

**Describe the feature and the current behavior/state.**
This is related to body segmentation using body-pix.
body segmentation has a flickering effect around the edges for a video stream.
Even setting edgeBlurAmount to maximum for the bokeh effect still had flickering effect around the edges since we are continuously trying to predict, segment and update frames from a video. 
Had similar flickering around the edges when i get image data from the segmentation and write it to a canvas. Is there any way to minimize/reduce the flickering around the edges?

**Will this change the current api? How?**
Not sure. Might change current api if additional masks are added.

**Who will benefit with this feature?**
Everyone in the community who uses body-pix model.

**Any Other info.**

**Comment by bhack** [comment]
I think you need to open this at https://github.com/tensorflow/tfjs

**Comment by amahendrakar** [comment]
@mchandrra,
As mentioned by @bhack, TensorFlow.js issues are tracked in tensorflow/tfjs repo. Could you please submit a new issue from [this link](https://github.com/tensorflow/tfjs/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by mchandrra** [comment]
Thank you @bhack and @amahendrakar. Submitted a new ticket at https://github.com/tensorflow/tfjs/issues/3902

**Comment by mchandrra** [comment]
Since this issue will be tracked at https://github.com/tensorflow/tfjs/issues/3902, closing this ticket.
