### ISSUE TITLE
tflite_runtime Interpreter import error

### ISSUE THREAD

**Issue by Bocharick** [tensorflow/tensorflow#43087]
OS: Ubuntu 16.04

Hi, there. I'm trying to use tflite_runtime Interpreter from [this docs](https://www.tensorflow.org/lite/guide/python) , but unfortunately I have an import error, when trying to use this package after installation.
I have tested all "supported" versions of python from this doc, and installed tflite_runtime package for each versions of pythons from 3.5 to 3.8.
My code is:
```python
import tflite_runtime.interpreter as tflite
model = tflite.Interpreter(model_path="/path/to/model/my_model.tflite")
model.get_input_details()
```
It only works at python 3.5. But it's unacceptable for me, because I need python 3.7 version.
All other versions of python, except 3.5 give me the same error.
For example:
Python 3.7.4 error:
```bash
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tflite_runtime.interpreter as tflite
Traceback (most recent call last):
  File "/home/bocharick/anaconda3/lib/python3.7/site-packages/tflite_runtime/interpreter_wrapper.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/bocharick/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/bocharick/anaconda3/lib/python3.7/site-packages/tflite_runtime/_interpreter_wrapper.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bocharick/anaconda3/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 46, in <module>
    from tflite_runtime import interpreter_wrapper as _interpreter_wrapper
  File "/home/bocharick/anaconda3/lib/python3.7/site-packages/tflite_runtime/interpreter_wrapper.py", line 17, in <module>
    _interpreter_wrapper = swig_import_helper()
  File "/home/bocharick/anaconda3/lib/python3.7/site-packages/tflite_runtime/interpreter_wrapper.py", line 16, in swig_import_helper
    return importlib.import_module('_interpreter_wrapper')
  File "/home/bocharick/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_interpreter_wrapper'
>>> 
```

Python 3.6.12 error:
```python
Python 3.6.12 (default, Sep 10 2020, 03:15:05) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tflite_runtime.interpreter as tflite
Traceback (most recent call last):
  File "/home/bocharick/.local/lib/python3.6/site-packages/tflite_runtime/interpreter_wrapper.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/bocharick/Downloads/Python-3.6.12/Lib/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/bocharick/.local/lib/python3.6/site-packages/tflite_runtime/_interpreter_wrapper.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bocharick/.local/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 46, in <module>
    from tflite_runtime import interpreter_wrapper as _interpreter_wrapper
  File "/home/bocharick/.local/lib/python3.6/site-packages/tflite_runtime/interpreter_wrapper.py", line 17, in <module>
    _interpreter_wrapper = swig_import_helper()
  File "/home/bocharick/.local/lib/python3.6/site-packages/tflite_runtime/interpreter_wrapper.py", line 16, in swig_import_helper
    return importlib.import_module('_interpreter_wrapper')
  File "/home/bocharick/Downloads/Python-3.6.12/Lib/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_interpreter_wrapper'
>>>
```

So as I see, it's `GLIBC_2.27`  problem. And what I must to do, if I have Ubuntu 16.04 with `GLIBC_2.23`, but I need to use python3.6+???

**Comment by amahendrakar** [comment]
@Bocharick,
To resolve the `/lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.27 not found` error, please take a look at [this](https://stackoverflow.com/a/20560664) StackOverflow comment and let us know if it helps. Thanks!

**Comment by Bocharick** [comment]
first of all those stackoverflow topic about older version of glibc (2.17).
And my question is -  why different versions of python needs different versions of glibc?
Could you make it with lowest glibc version, like at python3.5 version package of tflite_runtime?

**Comment by Bocharick** [comment]
I have found this instruction: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package
And built tflite_runtime package .whl.
It works now. BUT! It's very slow.

1) Tensorflow 2.3.0 from pip
2) tflite_runtime my build from tensorflow 2.3.0 sources

So
```python
import tensorflow as tf
mdl = tf.lite.Interpreter(model_path="/path/to/model.tflite")

-->cycle of invokes()
```

is ~2.3 faster then
```python
import tflite_runtime.interpreter as tflite
model = tflite.Interpreter(model_path="/path/to/model.tflite")

--> SAME cycle of invokes()
```

Why? tensorflow pip package which have no native optimizations are fast, but tflite_runtime built with my own machine with -O3 optimization much slower?

**Comment by jdduke** [comment]
@terryheo would you mind taking a look at this one? It could be that we're not using a consistent set of build flags (or toolchains) between the PIP build and the source build.

**Comment by terryheo** [comment]
@Bocharick what's the build command you used to build tflite_runtime package wheel ?

**Comment by Bocharick** [comment]
I tried two variants:
1) tensorflow/lite/tools/pip_package/build_pip_package.sh (with preinstalled dependencies of course)
2) make BASE_IMAGE=ubuntu:16.04 PYTHON=python3 TENSORFLOW_TARGET=native docker-build
both packages have same performance in my case.

**Comment by Bocharick** [comment]
> @Bocharick what's the build command you used to build tflite_runtime package wheel ?

I tried two variants:

tensorflow/lite/tools/pip_package/build_pip_package.sh (with preinstalled dependencies of course)
make BASE_IMAGE=ubuntu:16.04 PYTHON=python3 TENSORFLOW_TARGET=native docker-build
both packages have same performance in my case.

**Comment by terryheo** [comment]
build_pip_package.sh is using Makefile to build TFLite which doesn't support full features.
Could you try build_pip_package_with_bazel.sh?
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package#alternative-build-with-bazel-experimental

**Comment by Bocharick** [comment]
> build_pip_package.sh is using Makefile to build TFLite which doesn't support full features.
> Could you try build_pip_package_with_bazel.sh?
> https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package#alternative-build-with-bazel-experimental

Ok. I have built pip whl package with build_pip_package_with_bazel.sh. It was made from clean unzipped tf 2.3.0 sources.
Now I have two different whl files:
- **make built tflite_runtime**
- **bazel built tflite_runtime**
And I make several tests.
First of all I would like to tell, **tf2.2.0** and **tf2.3.0** has different tflite converted output models from same Keras model. Theese models has different indexes count, but same prediction (if it works) result. It was checked by me.
So I made four models from original Keras model:
- **tf2.2.0.NoOptimizations.tflite**
- **tf2.2.0.Optimize.DEFAULT.tflite**
- **tf2.3.0.NoOptimizations.tflite**
- **tf2.3.0.Optimize.DEFAULT.tflite**
All of them were made with Python API, absolutely without errors.
**BUT** tf2.3.0.Optimize.DEFAULT.tflite don't work at all.

My speed tests results (it pure only predict time, without import/etc/...):
**Predictions count**: 10000

**Original Keras model**:
	tensorflow==2.3.0 - 135.380 seconds

**TFLite converted from original Keras model with tensorflow==2.2.0, No Optimizations**:
	tensorflow==2.3.0 tf.lite.Interpreter - 126.382 seconds
	make built tflite_runtime from tf 2.3.0 sources - 133.498 seconds
	bazel built tflite_runtime from tf 2.3.0 sources - 137.244 seconds

**TFLite converted from original Keras model with tensorflow==2.2.0, Optimize.DEFAULT**:
	tensorflow==2.3.0 tf.lite.Interpreter - 100.528 seconds
	make built tflite_runtime from tf 2.3.0 sources - 193.405 seconds (yes, it's not and error, has checked several times)
	bazel built tflite_runtime from tf 2.3.0 sources - 193.204 seconds (yes, it's not and error, has checked several times)

**TFLite converted from original Keras model with tensorflow==2.3.0, No Optimizations**:
	tensorflow==2.3.0 tf.lite.Interpreter - 125.875 seconds
	make built tflite_runtime from tf 2.3.0 sources - 135.651 seconds
	bazel built tflite_runtime from tf 2.3.0 sources - 140.317 seconds

**TFLite converted from original Keras model with tensorflow==2.3.0, Optimize.DEFAULT**:
	tensorflow==2.3.0 tf.lite.Interpreter - FAIL (error*)
	make built tflite_runtime from tf 2.3.0 sources - FAIL (same error*)
	bazel built tflite_runtime from tf 2.3.0 sources - FAIL (same error*)

As you can see, make built and bazel built versions of tflite_runtime whl pip package has same (with a small error) performance

**Comment by terryheo** [comment]
Thanks for the detailed information.
Could you try the following?

```
$ BAZEL_FLAGS="--copt=-O3 --copt=-march=native" tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh
```

**Comment by Bocharick** [comment]
> Thanks for the detailed information.
> Could you try the following?
> 
> ```
> $ BAZEL_FLAGS="--copt=-O3 --copt=-march=native" tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh
> ```

Yes. Finally it works as I expected. Thank you.
You need to add this to the docs, I think.

**TFLite converted from original Keras model with tensorflow==2.2.0, No Optimizations:**  

- bazel built with opts tflite_runtime from tensorflow 2.3.0 sources - 108.857 seconds

**TFLite converted from original Keras model with tensorflow==2.2.0, Optimize.DEFAULT:**  

- bazel built with opts tflite_runtime from tensorflow 2.3.0 sources - 94.416 seconds

**TFLite converted from original Keras model with tensorflow==2.3.0, No Optimizations:**  

- bazel built with opts tflite_runtime from tensorflow 2.3.0 sources - 106.098 seconds

**TFLite converted from original Keras model with tensorflow==2.3.0, Optimize.DEFAULT:**  

- bazel built with opts tflite_runtime from tensorflow 2.3.0 sources - FAIL (same error*)

**Comment by terryheo** [comment]
Thanks for the verification!
Let me close this with script and doc update.

**Comment by Bocharick** [comment]
> Thanks for the verification!
> Let me close this with script and doc update.

Thanks. It's good for me.
