### ISSUE TITLE
No module named ptb

### ISSUE THREAD

**Issue by pannous** [tensorflow/tensorflow#431]
When running the ptb example/model/tutorial:
https://www.tensorflow.org/versions/master/tutorials/recurrent/index.html
` ~/ai/tensorflow/tensorflow/models/rnn/ptb$ python ptb_word_lm.py `
Traceback (most recent call last):
  File "./ptb_word_lm.py", line 72, in <module>
    from tensorflow.models.rnn.ptb import reader
ImportError: No module named ptb

Trying to fix it via
 export PYTHONPATH=$PYTHONPATH:/Users/me/ai/tensorflow
yields the other common error:
ImportError: No module named core.framework.graph_pb2

**Comment by pannous** [comment]
Update: 


Found the solution in the code 

To compile on CPU:
  bazel build -c opt tensorflow/models/rnn/ptb:ptb_word_lm
  bazel build -c opt //tensorflow/models/rnn/ptb:ptb_word_lm
To compile on GPU:
  bazel build -c opt tensorflow --config=cuda \
    tensorflow/models/rnn/ptb:ptb_word_lm
To run:
  ./bazel-bin/.../ptb_word_lm --data_path=/tmp/simple-examples/data/

**Comment by vrv** [comment]
We're fixing this in the next release so you can just type 'python ptb_word_lm.py', but thanks for the report.

**Comment by LAMike310** [comment]
Is there a way to fix this without using Bazel?

**Comment by vrv** [comment]
The pip install for 0.6.0 should have fixed this

**Comment by amrabed** [comment]
You still need to update the website tutorials to match this fix: https://www.tensorflow.org/versions/0.6.0/get_started/os_setup.html#download-and-setup
(0.5.0 -> 0.6.0)
and 
https://www.tensorflow.org/versions/0.6.0/tutorials/recurrent/index.html#run-the-code
(remove hint about bazel build)
I didn't realize I was using version 0.5.0 until I came across this issue

**Comment by martinwicke** [comment]
Updating the website now.
