### ISSUE TITLE
Several visual studio  editions and error of  LLVM requires at least MSVC 2017.

### ISSUE THREAD

**Issue by github2016-yuan** [tensorflow/tensorflow#43108]
I want to build tf-2.2.0 with bazel in win10.After some preparations， I follow cmds like below:
**First:**
python ./configure.py

.... **everything ok**

**Then:**
bazel build --config=opt //tensorflow:tensorflow_cc.dll

I get **some errors:** 
 D:/softwares/tensorflow-2.2.0/tensorflow/core/framework/BUILD:582:1: C++ compilation of rule '//tensorflow/core/framework:bfloat16' failed (Exit 2)

注意: 包含文件:                C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\corecrt_wstring.h
注意: 包含文件:              C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\stdexcept
注意: 包含文件:               C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\exception
注意: 包含文件:                C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\type_traits
注意: 包含文件:                 C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xstddef
注意: 包含文件:                  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\cstddef
注意: 包含文件:                  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\initializer_list
注意: 包含文件:                C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\malloc.h
注意: 包含文件:                C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\vcruntime_exception.h
注意: 包含文件:                 C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\eh.h
注意: 包含文件:                  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\corecrt_terminate.h

external/llvm-project/llvm/include\llvm/Support/Compiler.h(88): fatal error C1189: #error:  LLVM requires at least MSVC 2017.

**I know** it means that I need at least vs 2017 but I already have vs2019 (vs2019 is set up at D:\Softwares\vs2019).

It seems that bazel will serach vs in default path, e.g. C:\Program Files (x86)\Microsoft Visual Studio 14.0 instead of my costume path. 
So I want to know where to **change** the default visual stuio path that bazel uses with my costume path?

os : win10
vs: vs2013/vs2015/vs2019
Need help please.

**Comment by ravikyram** [comment]
@github2016-yuan 

Can you please refer this [link](https://docs.bazel.build/versions/master/install-windows.html#bazel-does-not-find-visual-studio-or-visual-c) and see if it helps you. Thanks!

**Comment by github2016-yuan** [comment]
@ravikyram 
Thanks for your solution and I do as what you suggest.
**BAZEL_VC:** C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC
**BAZEL_VS:** C:\Program Files (x86)\Microsoft Visual Studio\2019

Then I  bazel build --config=opt //tensorflow:tensorflow_cc.dll again.

but I **still** get the same error:
ERROR: F:/tf4/as7vs55w/external/llvm-project/llvm/BUILD:399:1: C++ compilation of rule '@llvm-project//llvm:llvm-tblgen' failed (Exit 2)
注意: 包含文件:                 C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\vadefs.h
注意: 包含文件:                C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\corecrt.h
注意: 包含文件:                 C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\vcruntime.h
注意: 包含文件:               C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\use_ansi.h
注意: 包含文件:              C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\stddef.h
注意: 包含文件:             C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\cstdlib
注意: 包含文件:              C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\stdlib.h
注意: 包含文件:               C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\corecrt_malloc.h
注意: 包含文件:               C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\corecrt_search.h
注意: 包含文件:               C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\corecrt_wstdlib.h

external/llvm-project/llvm/include\llvm/Support/Compiler.h(88): fatal error C1189: #error:  LLVM requires **at least MSVC 2017**.
Target //tensorflow:tensorflow_cc.dll failed to build
INFO: Elapsed time: 84.207s, Critical Path: 47.55s
INFO: 20 processes: 20 local.
FAILED: Build did NOT complete successfully

So how to do please?

**Comment by angerson** [comment]
We're not able to provide support for Bazel configuration issues that are not bugs in TF. Please check out [Bazel's Support Page](https://bazel.build/support.html).

**Comment by github2016-yuan** [comment]
Finally I solve it and build c++ tf2.2.0-gpu library. Here are my some try:
(1)set  system enviromnet-variable and reboot pc
(2)set up BuildTools for vs2019
(3)delete everything that created by former building
(4)build again 

In face, I do not konw what step solves the issue exactly but luckily it works at last.
Now I get dll,lib and header file.

**Comment by nigue3025** [comment]
Thanks for sharing the solution.
I got the same issue.
After setting the environment-variable and reboot PC, 
it starts compiling :)
