### ISSUE TITLE
Huge size difference of GPU delegate library between static and dynamic

### ISSUE THREAD

**Issue by rxiang040** [tensorflow/tensorflow#43102]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: RK3399
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3
- Python version: 3.6
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version: 10.4
- GPU model and memory: GTX 1050
**Describe the current behavior**
So I tried to use bazel to build the gpu delegate library as written in https://www.tensorflow.org/lite/performance/gpu_advanced
`bazel build -c opt --config android_arm64 tensorflow/lite/delegates/gpu:delegate                           # for static library`
`bazel build -c opt --config android_arm64 tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so  # for dynamic library`

The resulting dynamic library .so is 106 MB and static library .a is 1.1 MB. Why their size are so different? I need to use the dynamic library, however, 106 MB RAM will be used only for loading this dynamic library. Is there any way to reduce the size of the dynamic library?

Thanks!

**Comment by teijeong** [comment]
Hi @terryheo, have you seen similar issues?

**Comment by terryheo** [comment]
You'd better provide "--strip always" option to the bazel command.

```
$ bazel build -c opt --config android_arm64 --strip always tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so
```
