### ISSUE TITLE
tf .function gives different output than standard function

### ISSUE THREAD

**Issue by ben-arnao** [tensorflow/tensorflow#43111]
No custom code. TF 2.3

I am trying to make a "backtest" differentiable so i decide to use tf.function's auto differentiation capability.

Despite taking a very long time to compile the function, finally it gets converted into TF ops. However the "loss" i get when running a TF version of the function and the python version are completely different.

```
@tf.function
def get_loss(h_actions, nh_actions, prices):
    entry_point = 0.0
    exit_point = 0.0
    holding = False
    profit = 0.0
    index = 0
    fee = 0.001
    keep_perc = 1 - fee
    final_index = len(prices) - 1

    while index < final_index:
        curr_price = prices[index]

        if holding:
            act_value = h_actions[index]
        else:
            act_value = nh_actions[index]

        if act_value > 0.5:
            if holding is False:  # BUY
                holding = True
                entry_point = curr_price

            else:  # SELL
                holding = False
                exit_point = curr_price
                profit += (pow(keep_perc, 2) * exit_point / entry_point) - 1

        index += 1
    return profit
```

The inputs for this function are precomputed predictions and price history is supplied.

I don't believe the values for these specifically are very important. I was able to produce the same behavior with a dummy set

```
samples = np.random.normal(size=(1000, 10))
prices = [random.uniform(1, 1000) for _ in range(1000)]
samples[:, -1] = 1
holding_preds = model.predict(samples)
samples[:, -1] = -1
not_holding_preds = model.predict(samples)
```

The only thing i see is that a warning in thrown saying that there's a large unroll loop. Other than that why would i get getting a different output?

**Comment by bhack** [comment]
Can you share a dummy, minimal, but runnable model definition to run the dummy set?

**Comment by ben-arnao** [comment]
@bhack https://colab.research.google.com/drive/1uy8kr4efsRWB759M9avlpCOsWD3rQMpC#scrollTo=vDXjYZ43tbPI&line=95&uniqifier=1

**Comment by bhack** [comment]
Please remove authentication from the colab example.

**Comment by ben-arnao** [comment]
My bad. Hopefully this is better https://colab.research.google.com/drive/1uy8kr4efsRWB759M9avlpCOsWD3rQMpC?usp=sharing

**Comment by bhack** [comment]
I don't see the warning in the colab. Can you add something to show the wrong behavior?

**Comment by ben-arnao** [comment]
The losses don't match up. I added a line to show that they produce different values despite they are same function, one is just converted to TF

https://colab.research.google.com/drive/1uy8kr4efsRWB759M9avlpCOsWD3rQMpC?usp=sharing

**Comment by bhack** [comment]
@ben-arnao Your autograph tracing on the control flow over `holding` will not work as you expect: 
See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/control_flow.md#all-python-code-paths-are-executed-during-tracing

See also autograph tracing limits:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md

**Comment by ben-arnao** [comment]
> @ben-arnao Your autograph tracing on the control flow over `holding` will not work as you expect:
> See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/control_flow.md#all-python-code-paths-are-executed-during-tracing
> 
> See also autograph tracing limits:
> https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md

Thank you for this. I will look into these and see if there is a way to modify the code.
