### ISSUE TITLE
Problem saving and loading Keras Model that was built with StellarGraph library

### ISSUE THREAD

**Issue by kwanchet** [tensorflow/tensorflow#43114]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
I am using StellarGraph package which uses Keras for building graph neural networks. 
 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Catalina
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NIL

- TensorFlow installed from (source or binary): binary 
- TensorFlow version (use command below): pip install tensorflow 2.3.0
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory: 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I have used the following code to save and load the Keras model:

```
json_file = open(os.path.join("./outputs/model_new/", 'model.json'), 'r')
model_json = json_file.read()
json_file.close()
model = model_from_json(model_json, custom_objects=sg.custom_keras_layers)
# load weights into new model
model.load_weights(os.path.join("./outputs/model_new/", "model.h5"))   
model.compile(
            optimizer=optimizers.Adam(lr=0.002),
            loss=keras.losses.binary_crossentropy,
            metrics=METRICS,
        )
```

However, it returns the following error:

```
ValueError: Dimension 1 in both shapes must be equal, but are 2 and 1. Shapes are [?,2] and [?,1]. for '{{node mean_hin_aggregator_3/concat_5}} = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32](mean_hin_aggregator_3/Reshape_35, mean_hin_aggregator_3/truediv_5, mean_hin_aggregator_3/concat_5/axis)' with input shapes: [?,2,18], [?,1,18], [] and with computed input tensors: input[2] = <2>.
```

Please note that I am using StellarGraph to build the graph model. There are some custom layers involved such as Mean_hin_aggregator. I suspect this is the cause of the problem. A similar problem was mentioned in StellarGraph issues before: https://github.com/stellargraph/stellargraph/issues/201

**Describe the expected behavior**

It should return the trained model.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@kwanchet 

Can you please share colab link or simple standalone code with supporting files ( `model.json`) to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by benste** [comment]
A brilliant feature of HinSage is that it can do inductive representation learning. Not being able to save and load the model makes this much less useful. 

Is this being looked at so we can use this awesome algorithm in all its glory?

**Comment by enjieli** [comment]
@ravikyram I am encountering similar issues. Here is the colab [link](https://colab.research.google.com/github/stellargraph/stellargraph/blob/master/demos/link-prediction/hinsage-link-prediction.ipynb#scrollTo=AUcv_Osglmxf) . 

After training the model, i used `model.save('model/traits_only.h5')` to save the model. However, I am having issues loading the model using ` models.load_model("model/movie_rec.h5")`. 

Could you please advise what's the proper way of saving and loading graph models? Thank you!

**Comment by kwanchet** [comment]
@enjieli @benste  seems like saving the weight and neural network architecture via `model.save` might be a problem.  Not too sure why it happens. 

But a workaround might be to use `save_weights` to save the weights and `load_weights` to load the weights/checkpoints. 
That being said, to make sure you can do proper inference, you may need to re-use model training steps in your google colab to re-setup the neural network architecture and use 'load_weights'.

**Comment by enjieli** [comment]
@kwanchet thank you so much for your input!
