### ISSUE TITLE
Configure takes a lot of time and resources 

### ISSUE THREAD

**Issue by Mistobaan** [tensorflow/tensorflow#4311]
in the last few weeks I notice that while developing operations for tensorflow I find myself doing ./configure many more times and each time takes few minutes on a good internet connection.

Can we cache some of the artifacts ? Do we have to remove all the time the complete protobuf repository ? How is this handled internally at google ?

**Comment by ibab** [comment]
I wonder whether simply commenting out the `bazel clean --expunge` at the end of the `configure` script would lead to problems.
I assume there must be a reason it's there, but I haven't figured out what it might be (assuming that bazel can correctly pick up the changes in all files touched by `configure`).

**Comment by martinwicke** [comment]
We have the clean --expunge there for safety. You can try removing it, which should speed this up considerably, and most of the time it should be fine. Why are you running configure so often?

**Comment by martinwicke** [comment]
I'll close this issue. Please comment to reope if there something that we can/should do to our configure script. 

The `--expunge` is net beneficial in terms of issue load, I fear, so that'll stay for now.
