### ISSUE TITLE
model_main_tf2.py "module tensorflow.compat.v2 has no attribute app"

### ISSUE THREAD

**Issue by turowicz** [tensorflow/tensorflow#43122]
### System informatio

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: model_main_tf2.py 
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04.5
-   **TensorFlow installed from (source or binary)**: 2.3.0
-   **TensorFlow version (use command below)**: v2.3.0-rc2-23-gb36436b087 2.3.0
-   **Python version**: Python 3.6.9
-   **GPU model and memory**: V100
-   **Exact command to reproduce**: python3 ../../models/research/object_detection/model_main_tf2.py --pipeline_config_path=model/pipe.config --model_dir=training --logtostderr

### Describe the problem
I'm just trying to run a basic training job through the provided script in the object_detection samples. I used to run the model_main.py with TF 1.x.

### Source code / logs
```
2020-09-10 20:33:44.263700: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "../../models/research/object_detection/model_main_tf2.py", line 112, in <module>
    tf.app.run()
AttributeError: module 'tensorflow.compat.v2' has no attribute 'app'
```

**Comment by turowicz** [comment]
My Dockerfile:

```
FROM tensorflow/tensorflow:2.3.0-gpu

WORKDIR /

# Settings
ENV TZ=Etc/UTC
ENV DEBIAN_FRONTEND=noninteractive

# Add Project Files
WORKDIR /tmp
ADD ./models models
ADD ./configs configs
ADD ./scripts scripts
ADD ./workspace workspace

# Main Script
WORKDIR /
RUN apt-get update && apt-get upgrade -y && \
    # Apply Timezone
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    # Install Dependencies
    apt-get install -y software-properties-common build-essential git cmake libprotobuf-dev protobuf-compiler curl wget zip unzip vim gnupg2 bash-completion && \
    # Install packages
    pip3 install tf-slim && \
    pip3 install cython && \
    pip3 install pycocotools && \
    pip3 install git+https://github.com/microsoft/onnxconverter-common && \
    pip3 install git+https://github.com/onnx/tensorflow-onnx && \
    pip3 install git+https://github.com/onnx/keras-onnx && \
    # Build Research
    cd /tmp/models/research && protoc object_detection/protos/*.proto --python_out=. && \
    cd /tmp/models/research && python3 setup.py build && python3 setup.py install && \
    # Clean up
    ldconfig && \
    apt-get autoremove -y && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

# Configure Entry
WORKDIR /tmp/workspace

ENTRYPOINT ["/bin/bash"]
```

**Comment by bhack** [comment]
You need to update your model for TF2. Has you see It Is changed:
https://github.com/tensorflow/models/blob/master/research/object_detection/model_main_tf2.py#L113

**Comment by ravikyram** [comment]
@turowicz 

In this tensorflow 2 guide,https://www.tensorflow.org/guide/effective_tf2, it says tf.app is removed.So in TF 1.x your code is running fine.
To resolve this error, modify the code so that it uses 2.x API 
You can refer similar issues #37128,#34431.Thanks!

**Comment by turowicz** [comment]
Thanks, it works when I check out `master` branch of this repository.

**Comment by exeptionerror** [comment]
[[Solved] module ‘tensorflow.compat.v2.__internal__’ has no attribute ‘tf2’
](https://exerror.com/module-tensorflow-compat-v2-internal-has-no-attribute-tf2/)
