### ISSUE TITLE
Models for TensorFlow Lite which are quantized according to the post-training quantization does not run on NPU of some devices.

### ISSUE THREAD

**Issue by y-ich** [tensorflow/tensorflow#43128]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Y es
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):macOS 10.13.6, Android 10.1.0
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: MatePad Pro
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.15.3
- Python version:3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I am trying int8 quantization of my model on TensorFlow Lite.
Conversion itself worked using tensorflow 1.15.3 but the converted model ran extremely slowly on Kirin 990. logcat indicates that it runs on CPU, not NPU.
(Conversion using tensorflow 2.3.0 did not work.)

mobilenet_v1_1.0_224_quant.tflite in tensorflow/examples runs fast on Kirin 990. logcat indicates that it runs on NPU.

So I checked the differences between them.

1. My model is int8(tf.lite.OpsSet.TFLITE_BUILTINS_INT8) quantization but mobilenet_v1_1.0_224_quant.tflite seems uint8 quantization.

2. The "filter" property of Conv2D has a "quantization" attribute in mobilenet_v1_1.0_224_quant.tflite, but The "filter" property of Conv2D has no "quantization" attribute in my converted model.

How can I convert my model like mobilenet_v1_1.0_224_quant.tflite?
Please disclose the conversion script for mobilenet_v1_1.0_224_quant.tflite.

I asked [the question](https://stackoverflow.com/questions/63700590/how-can-i-convert-my-model-like-mobilenet-v1-1-0-224-quant-tflite-in-tensorflow) on stackoverflow, but have not gotten relevant answers, so I ask the question here again.

Thanks.

[Edit]
In my current understanding, some NNAPI drivers have not supported per-channel quantized model yet. But the post-training quantization in TensorFlow supports only er-channel quantization.
I will appreciate if you provide solutions to resolve this situation.

**Describe the expected behavior**

I will get a fast, quantized model.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@y-ich 
Please share simple stand alone code or if possible share a colab gist with error reported, if possible can you try in later versions of tf [2.x] and see if it helps resolve your issue.

**Comment by y-ich** [comment]
@Saduf2019 san, thank you for your response!

Do you need my conversion script or converted model?

**Comment by y-ich** [comment]
@Saduf2019 san, I prepared the model.

https://github.com/y-ich/reproduction_43128

BTW, if you provide the conversion script for mobilenet_v1_1.0_224_quant.tflite, I can investigate this issue.
You do not need to use your time.

About  tf [2.x], I could not convert the model by tf 2.3.0.

**Comment by Leslie-Fang** [comment]
I have met a similar issue. The int8 tflite model is slower comparing with Fp32.
I only use the default convert options.
```
def representative_dataset_gen():
  for input_value in dataset:
    yield [input_value[0]]
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen
```

**Comment by Saduf2019** [comment]
@y-ich 
Please update a s per above comment.

**Comment by y-ich** [comment]
@Saduf2019 san,

Maybe "update a s per above comment" is kind of typo? I am sorry that I cannot understand it.

Currently what I want to know is how to quantize weights as uint8 instead of int8.
Please let me know it.

**Comment by vito-filo** [comment]
I have the same issue, i need to quantize a ssd_mobilenet_v1_fpn to use it on Android for object detection. 
From what I understood there are 3 types of quantizations,  as explained here: [https://www.tensorflow.org/lite/performance/post_training_quantization](url)

I managed to perform dynamic range quantization, so now my model has uint8 filter weights. but it's still slow and too heavy!
In order to reduce futher latency i should perform full integer quantization to have both weights and inputs in uint8 format.

So i guess your model is dynamic range quantized and the example model is fully integer quantized.

I tried this guide to fully quanized my model: https://neuralet.com/article/quantization-of-tensorflow-object-detection-api-models/

i wrote this code:
```python

import tensorflow as tf
import cv2
import numpy as np
from imutils import paths
		
def dataset_gen():
	images_path =  # path to represantative dataset
	if images_path is None:
		raise Exception(
			"Image directory is None, full integer quantization requires images directory!"
		)
	imagePaths = list(paths.list_images(images_path))
	for p in imagePaths:
		image = cv2.imread(p)
		image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
		image = cv2.resize(image, (640, 480))
		image = image.astype("float")
		image = np.expand_dims(image, axis=1)
		image = image.reshape(1, 640, 480, 3)
		yield [image.astype("float32")]

frozen_graph_file = # path to frozen graph (.pb file)
input_arrays = ["normalized_input_image_tensor"]
output_arrays = ['TFLite_Detection_PostProcess',
		  'TFLite_Detection_PostProcess:1',
		  'TFLite_Detection_PostProcess:2',
		  'TFLite_Detection_PostProcess:3']
input_shapes = {"normalized_input_image_tensor" : [1, 640, 480, 3]}
converter = tf.lite.TFLiteConverter.from_frozen_graph(frozen_graph_file,
						input_arrays=input_arrays,
						output_arrays=output_arrays,
						input_shapes=input_shapes)
											
											 
converter.allow_custom_ops = True
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
converter.representative_dataset = tf.lite.RepresentativeDataset(dataset_gen())
tflite_quant_model = converter.convert()

with open("detect.tflite", "wb") as tflite_file:
	tflite_file.write(tflite_quant_model)

```

but it runs without producing any output models.

**Comment by y-ich** [comment]
@vito-filo san,

Could tell me how to get uint8 filter weights?
In my experience, TensorFlow v1.15.3 generates only int8 weights, not uint8.

**Comment by y-ich** [comment]
uint8 or int8 may not matter.
"per channel quantization" or not may matter.
Huawei's NNAPI driver seems not support per channel quantization yet.
I guess that some old version of TensorFlow quantizes as uint8 and per-tensor, but the last TensorFlow 1 and the latest TensorFlow 2 quantize as in8 and per-channel.

I want to know how to quantize models as per-tensor (and uint8).

**Comment by vito-filo** [comment]
Now that I'm paying attention in my model i have int8 weights, not uint8.
However i think this is not the main problem, as @Leslie-Fang said the overhead is on the float32 parameters you may have in the layers.

I think you can get the best optimization with full integer quantization. unfortunately I am not yet able do it on my model. I wonder if @ Leslie-Fang did it.

Check if you have some float32 parameters in your conv layers (as input, output or bias).
I am not well versed in these things, but I think we have the same problem and a possible solution to improve speed on mobile devices is to convert all float32 parameters to int8 (or uint8).

**Comment by y-ich** [comment]
@vito-filo san,

Thank you for your advice!
I tried "Integer only" in [Post-training quantization](https://www.tensorflow.org/lite/performance/post_training_quantization), but the result was same.

"adb logcat" say,
    09-15 20:38:55.971   886   886 E AndroidNN: AnnOpConvParser::isSupport1_1(278)::"Conv input type per channel not support"

I think that tensorflow had changed conv quantization from per-tensor to per-channel in some version.
I want to know what version is the last version using per-tensor.

**Comment by y-ich** [comment]
I found the same issue and it has no answers.
https://github.com/tensorflow/tensorflow/issues/39944

**Comment by y-ich** [comment]
I found the statement “UInt8 models trained with the legacy quantization-aware training path are also supported” in the document [“ TensorFlow Lite Hexagon delegate”](https://www.tensorflow.org/lite/performance/hexagon_delegate).
It is a part of the answer which I want to know.

Now my question is, how can I disable per-channel(per-axis) quantization for post-training quantization.

**Comment by y-ich** [comment]
I summarized my understanding and close this issue.

1. Android 10 introduced NNAPI 1.2, which supports per-channel quantization. And TensorFlow Lite moved from per-tensor quantization-aware training to per-channel post-training quantization as main line.
2. Huawei did not implement NNAPI 1.2 for NPU on Android 10, so per-channel quantized model falls back to CPU.
3. TensorFlow Lite seems on the way to support “disable_per_channel” with low priority.

I hope that EMUI 11 supports NNAPI 1.2 or implementation of “disable_per_channel” on TensorFlow Lite will finish soon.

**Comment by lilinxiong** [comment]
@y-ich I encountered the same problem. On Huawei phones(OS: Android 10), the NNAPI delegate failed to open.
So, do you have a solution now?
Below is a screenshot of my error log.
![](https://user-images.githubusercontent.com/24367027/117395743-22f70280-af2b-11eb-8fb3-777a9a985f00.png)

**Comment by yahuuu** [comment]
@y-ich  Meet same problem，do you get a solution now ?
Whether tensorflow  < 1.15 work?
