### ISSUE TITLE
Generating ICU normalization_data.c and icu_conversion_data.c on s390x architecture

### ISSUE THREAD

**Issue by rposts** [tensorflow/tensorflow#43124]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 2.2.0
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): bazel 2.0.0- (@non-git)
- GCC/Compiler version (if compiling from source): gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
ICU data provided [here ](https://github.com/tensorflow/tensorflow/tree/master/third_party/icu/data) appears to be generated on x86 platform.  I am trying to generate this data on s390x but running into some issues.

Firstly, filters.json as per [instructions ](https://github.com/tensorflow/tensorflow/blob/master/third_party/icu/data/BUILD.bazel) is not compatible with `icu` `release-64-2`. It seems that TF 2.2.0 expects `release-64-2`.  I can make it work with `release-65-1` but unsure of generating `icu_conversion_data.c.gz.*`   I could see that `conversion_data.c` is generated by concatenating `*.gz` unzipped contents.  Can someone please provide some pointers here on how to generate the `*.gz` files?

Secondly, [instructions ](https://github.com/tensorflow/text/blob/master/third_party/icu/data/BUILD) on generating `normalization_data.c`  are almost identical to the `icu_conversion_data.c`.  Are these two same files or am I missing something?

Thanks again for your time.

**Comment by gunan** [comment]
Please redirect to owners of the ICU code in TF.

**Comment by gowthamkpr** [comment]
@hamatake Please take a look at this issue. Thanks!

**Comment by amahendrakar** [comment]
@rposts,
Could you please update TensorFlow to the latest stable version v2.4 and check if you are facing the same issue. Thanks!

**Comment by rposts** [comment]
@amahendrakar I checked TF 2.4.1 code and the problem persists on s390x.

[Bazel](https://github.com/tensorflow/tensorflow/blob/v2.4.1/third_party/icu/data/BUILD.bazel) build file seem to indicate that data is pre-processed for little-endian platforms and I have little reason to think it is fixed in latest TF release on s390x (BE) arch. 

Let me know whether this is a limitation on big-endian platforms or we could publish BE `icu_conversion_data` as well.  If latter then I still need clarifications on the earlier two questions raised on filters.json and generating `normalization_data.c`.

Thanks.

**Comment by rposts** [comment]
@sushreebarsa Hi there - any updates on this issue? Generated data continues to be little-endian specific.

**Comment by broken** [comment]
@rposts Hi, I'll try to help out here.

> filters.json as per [instructions ](https://github.com/tensorflow/tensorflow/blob/master/third_party/icu/data/BUILD.bazel)is not compatible with icu release-64-2. It seems that TF 2.2.0 expects release-64-2.

You can view [this change](https://github.com/tensorflow/tensorflow/commit/93323537ac0581a88af827af2f9232b77a13619b#diff-99f728c9d7db33e4570f3eb21183e31aa87c059a0c1d5f23b4e585af8c175c5c) to see the edits that were made when bumping up the version from 64-2.

> unsure of generating icu_conversion_data.c.gz.* I could see that conversion_data.c is generated by concatenating *.gz unzipped contents. Can someone please provide some pointers here on how to generate the *.gz files?

Those are created by splitting a gzipped file. Original instruction are [here](https://github.com/tensorflow/tensorflow/blob/master/third_party/icu/data/BUILD.bazel).

```
cp icudt70l_dat.c icu_conversion_data.c
gzip icu_conversion_data.c
split -a 3 -b 100000 icu_conversion_data.c.gz icu_conversion_data.c.gz.
```

> Secondly, [instructions ](https://github.com/tensorflow/text/blob/master/third_party/icu/data/BUILD)on generating normalization_data.c are almost identical to the icu_conversion_data.c. Are these two same files or am I missing something?

The instructions are almost identical, because generating the files is the same. However, what is different are the filters used which selects what data is generating. Thus, the result is not the same.

> [Bazel](https://github.com/tensorflow/tensorflow/blob/v2.4.1/third_party/icu/data/BUILD.bazel) build file seem to indicate that data is pre-processed for little-endian platforms and I have little reason to think it is fixed in latest TF release on s390x (BE) arch.

> Let me know whether this is a limitation on big-endian platforms or we could publish BE icu_conversion_data as well. If latter then I still need clarifications on the earlier two questions raised on filters.json and generating normalization_data.c.

From [the ICU documentation](https://unicode-org.github.io/icu/userguide/icu_data/#sharing-icu-data-between-platforms), it looks like the data should be able to be created as BE.

I'm not familiar with the s390x release process, but issue https://github.com/tensorflow/tensorflow/issues/46181 seems to point to it being a separate SIG project. Perhaps working with those owners to make this update is the best course of action?

**Comment by rposts** [comment]
@broken - Thanks for the clarification. I will close this issue and investigate SIG route.
