### ISSUE TITLE
Integer quantization error

### ISSUE THREAD

**Issue by huafeihuayu** [tensorflow/tensorflow#43129]
Traceback (most recent call last):
  File "D:/hua_work/tf_lite/lite_test.py", line 32, in <module>
    interpreter.allocate_tensors()
  File "E:\Anaconda3\envs\tensorflow23\lib\site-packages\tensorflow\lite\python\interpreter.py", line 243, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: tensorflow/lite/kernels/pad.cc:118 op_context.input->type != op_context.constant_values->type (INT8 != FLOAT32)Node number 3 (PADV2) failed to prepare.

There is pad layer in the model, error after full quantization

**Comment by amahendrakar** [comment]
@huafeihuayu,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!

**Comment by huafeihuayu** [comment]
@amahendrakar 
Quantization code
import numpy as np
import tensorflow as tf
import cv2

def representative_dataset_gen():
    img=cv2.imread('C:/sfz/00/all/10cn000000000.jpg')
    img=np.array(img,dtype='float32')
    image_paths_tensor = tf.convert_to_tensor(img,dtype=tf.float32)
    dataset = tf.data.Dataset.from_tensor_slices(image_paths_tensor)
    for input_value in dataset.batch(1).take(100):
        print(input_value)
        yield [input_value]
saved_model_dir='D:/sfz/tf_sfz'
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen
# Ensure that if any ops can't be quantized, the converter throws an error
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.allow_custom_ops=True
# Set the input and output tensors to uint8 (APIs added in r2.3)
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
tflite_model_quant = converter.convert()
open("D:/sfz/tf_sfz/model26.tflite","wb").write(tflite_model_quant)

tensorflow-gpu2.3.0       C:/sfz/00/all/10cn000000000.jpg it is 32*416*33

**Comment by amahendrakar** [comment]
@huafeihuayu,
Could you please share the saved_model files as well (i.e. contents of the folder `D:/sfz/tf_sfz`), so that we can reproduce the issue on our end. Thanks!

**Comment by mschreil** [comment]
Has this problem been solved or is there any workaround? 
I am facing the same issue when converting a Resnet18 (onnx --> tf --> tflite) to tflite with full int8 quantization.

**Comment by amahendrakar** [comment]
@mschreil,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
