### ISSUE TITLE
[TFLu] int8 ops slower than f32

### ISSUE THREAD

**Issue by Abhipray** [tensorflow/tensorflow#43121]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip install tf-nightly
- Tensorflow version (commit SHA if source): 2.4.0-dev20200908
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Cortex M4f

**Describe the problem**
I compared the time spent by `MicroInterpreter::Invoke()` to perform different ops on the same model with with int8 quantization and without. I also tried the CMSIS-NN kernels for some of the ops. The problem is that besides the fully connected op, every other op is the same or slower with the int8 ops. 

Here is a table showing the average time in ticks spent by each op's `Eval()`. The first column shows model with int8 quantization using cmsis-nn kernels for mul, add, fullyconnected. The second column uses the reference kernels and third is floating point.

  | q7cmsis | q7 ref | f32
-- | -- | -- | --
fullyconnected | 5990 | 8611 | 6639
tanh | 15114 | 15122 | 1101
add | 2686 | 2887 | 971
mul | 2202 | 1834 | 1261
sub | 3301 | 3299 | 1380
split_v | 898 | 915 | 836
split | 794 | 817 | 814
reshape | 441 | 443 | 918

The tanh kernel performs the worst with 13x slower than the floating point equivalent. Is this expected or known behavior?

**Please provide the exact sequence of commands/steps when you ran into the problem**
I have attached the models that I used for profiling. 
[profiling_models.zip](https://github.com/tensorflow/tensorflow/files/5204489/profiling_models.zip)

**Comment by renjie-liu** [comment]
We have optimized for neon on arm, but for micro, unfortunately those simd instructions are not available.

Hi Pete, do you have any suggestions?

Thanks

**Comment by Leslie-Fang** [comment]
@renjie-liu What's about X86 case? Did these int8 ops optimized?

**Comment by yair-ehrenwald** [comment]
The Cortex M4f has an FPU so this shouldn't be too surprising.
On a platform without an FPU the quantized ops should be considerably faster.

 The split operations and reshape are basically memcpy ops so they probably take similar amounts of cycles, but for the mathematical ops consider that while 'sub' for example might take one cycle for fp32 (assuming you have an FPU) when using int8 you have scaling, zero point etc to handle.

**Comment by Abhipray** [comment]
@yair-ehrenwald I am not sure all of it can be attributed to the presence of an FPU. For instance, the MUL CMSIS-NN implementation is slower than the reference op even though the CMSIS-NN kernel uses SIMD instructions.

**Comment by mohantym** [comment]
Hi @Abhipray !

Have you tested again in 2.8/2.10 version with [post-training integer quantization](https://www.tensorflow.org/lite/performance/post_training_integer_quant) yet.

Thank you!
