### ISSUE TITLE
Just Qustion: In Android JAVA, keras model is ok?

### ISSUE THREAD

**Issue by SungmanHong** [tensorflow/tensorflow#43131]
Hi, I'm developing android app

and my NN in python is keras(Tf.keras) with LSTM, conv2d, resnet, attention (very deep)

I want to use this NN in JAVA.android

1) can I use TF-lite for my keras of python?? 

I heard TF.lite only support some TF model so I'm worried

2) and can I convert keras to tensorflow? and just use tensorflow in JAVA?

3) and can I convert keras to tensorflow? and just use tensorflow lite or tensorflow.mobile in JAVA?

Thx.

**Comment by Rishit-dagli** [comment]
@SungmanHong As I understand you are talking about converting the Keras model to a TF Lite Model and then using that in your Android app. Tp convert your model to a `.tflite` format I would recommend you to use the [TensorFlow Lite converter](https://www.tensorflow.org/lite/convert#convert_a_keras_model_). To then use this model in your Android app you could very easily make use of [ML Model Binding plugin](https://developer.android.com/studio/preview/features#tensor-flow-lite-models) with Android Studio (4.1 or above) which makes it easy for you to directly import `.tflite model` files and also generate easy-to-use classes.

**Comment by SungmanHong** [comment]
@Rishit-dagli  Thanks a lot, In my case, I was actually trying pytorch.mobile 
but now, very latest pytorch and pytorch mobile are not compatible...;; https://github.com/pytorch/vision/issues/1943
I downgraded pytorch and seems its good and is compatible to pytorch mobile yet.
I hope TF and TFmobile is more stable and compatible than pytorch and pytorch mobile

**Comment by Rishit-dagli** [comment]
> @Rishit-dagli Thanks a lot, In fact, so far, I've been trying to port the neural network on the Android app through Pythorch Mobile.
> but now, latest pytorch and pytorch mobile are not compatible each other...;; [pytorch/vision#1943](https://github.com/pytorch/vision/issues/1943)
> The App is just CRUSHED WHEN THE MODEL IS LOADED and others have experienced similar things.
> I downgraded pytorch and seems its good and is compatible to pytorch.android module yet.
> I hope TF and TFmobile is more stable and compatible than pytorch_mobile and pytorch android module.

I personally have not worked with PyTorch Mobile so I wouldn't be able to compare them, but I have noticed that the TF Lite Android Support Library is pretty stable
