### ISSUE TITLE
Mac c++ tensorflow_cpu segmentation fault

### ISSUE THREAD

**Issue by woshildh** [tensorflow/tensorflow#43135]
I build tensorflow 1.12 c++ on Mac without gpu. I can load .meta and .ckpt of model. When I run session->run() ，program raise segmentation error. I can get some node output results in middle but I could not get   the last outputs results.  Thank you very much for your help.
My environment is:
   
 MacOS 10.15.4, tensorflow 1.12, cuda(None), bazel 0.15.2, clang version 11.0.3

`
    MetaGraphDef graphdef; //Graph Definition for current model

    string checkpointPath = "../static/model_ldh";
    Status status_load = ReadBinaryProto(Env::Default(), "../static/model_ldh.meta", &graphdef);
    if (!status_load.ok()) {
        std::cout << "ERROR: Loading model failed..."<< std::endl;
        std::cout << status_load.ToString() << "\n";
        return -1;
    }
    //create session
    SessionOptions options;
    auto session = NewSession(options);
    if (session == nullptr) {
        std::cout << "ERROR: Creating graph in session failed..." << std::endl;
        return -1;
    }
    //add graph into session
    Status status = session->Create(graphdef.graph_def());
    if (!status.ok()) {
        throw runtime_error("Error creating graph: " + status.ToString());
    }
    // load weights
    Tensor checkpointPathTensor(DT_STRING, TensorShape());
    checkpointPathTensor.scalar<std::string>()() = checkpointPath;
    status = session->Run(
            {{ graphdef.saver_def().filename_tensor_name(), checkpointPathTensor },},
            {},
            {graphdef.saver_def().restore_op_name()},
            nullptr);
    if (!status.ok()) {
        throw runtime_error("Error loading checkpoint from " + checkpointPath + ": " + status.ToString());
    }

    string image_path = "../static/test.jpg";
    int input_height = 112;
    int input_width = 96;
    int input_mean = 127;
    int input_std = 128;
    std::vector<Tensor> resized_tensors;
    Status read_tensor_status =
            ReadTensorFromImageFile(image_path, input_height, input_width, input_mean,
                                    input_std, &resized_tensors); // load image . shape is [1, 112, 96, 3]
    if (!read_tensor_status.ok()) {
        LOG(ERROR) << read_tensor_status;
        cout<<"resing error"<<endl;
        return -1;
    }

    const Tensor& resized_tensor = resized_tensors[0];
    std::cout << resized_tensor.DebugString()<<endl;

    vector<tensorflow::Tensor> outputs;
    tensorflow::string output_node1 = "outputs_A:0" , output_node2 = "outputs_B:0";
    tensorflow::Tensor phase_train(DT_BOOL, {1});
    tensorflow::Tensor switch_all(DT_BOOL, {1});
    tensorflow::Tensor keep_prob(DT_FLOAT,{1});
    auto phase_train_data = phase_train.tensor<bool, 1>(); phase_train_data(0) = false;
    auto switch_all_data = switch_all.tensor<bool, 1>(); switch_all_data(0) = false;
    auto keep_prob_data = keep_prob.tensor<float, 1>(); keep_prob_data(0) = 1.0;
    vector<pair<string, tensorflow::Tensor>> need_inputs = {{"inputs:0", resized_tensor},
         {"switch:0", switch_all}, {"keep_prob:0", keep_prob}, {"phase_train:0", phase_train}};

    outputs.clear();
    tensorflow::string  debug = "FaceResNet/NetA_3/conv4/layer_0/Conv/p_re_lu/Relu:0";
    Status status_run = session->Run(need_inputs, {debug}, {}, &outputs); // **I can get this results**
    status_run = session->Run(need_inputs, {output_node1}, {}, &outputs); // **this line will occur to segmentation fault**
    `
the error statcks are as following :
`Eigen::internal::gemm_pack_rhs<float, long, Eigen::internal::TensorContractionSubMapper<float, long, 0, Eigen::TensorEvaluator<Eigen::TensorReshapingOp<Eigen::DSizes<long, 2> const, Eigen::TensorImagePatchOp<-1l, -1l, Eigen::TensorMap<Eigen::Tensor<float const, 4, 1, long>, 16, Eigen::MakePointer> const> const> const, Eigen::ThreadPoolDevice>, Eigen::array<long, 1ul>, Eigen::array<long, 1ul>, 16, true, false, 0, Eigen::MakePointer>, 4, 0, false, false>::operator()(float*, Eigen::internal::TensorContractionSubMapper<float, long, 0, Eigen::TensorEvaluator<Eigen::TensorReshapingOp<Eigen::DSizes<long, 2> const, Eigen::TensorImagePatchOp<-1l, -1l, Eigen::TensorMap<Eigen::Tensor<float const, 4, 1, long>, 16, Eigen::MakePointer> const> const> const, Eigen::ThreadPoolDevice>, Eigen::array<long, 1ul>, Eigen::array<long, 1ul>, 16, true, false, 0, Eigen::MakePointer> const&, long, long, long, long) const 0x0000000105f7e75c
Eigen::TensorEvaluator<Eigen::TensorContractionOp<Eigen::array<Eigen::IndexPair<long>, 1ul> const, Eigen::TensorReshapingOp<Eigen::DSizes<long, 2> const, Eigen::TensorImagePatchOp<-1l, -1l, Eigen::TensorMap<Eigen::Tensor<float const, 4, 1, long>, 16, Eigen::MakePointer> const> const> const, Eigen::TensorReshapingOp<Eigen::DSizes<long, 2> const, Eigen::TensorMap<Eigen::Tensor<float const, 4, 1, long>, 16, Eigen::MakePointer> const> const> const, Eigen::ThreadPoolDevice>::Context<Eigen::internal::gemm_pack_lhs<float, long, Eigen::internal::TensorContractionSubMapper<float, long, 1, Eigen::TensorEvaluator<Eigen::TensorReshapingOp<Eigen::DSizes<long, 2> const, Eigen::TensorMap<Eigen::Tensor<float const, 4, 1, long>, 16, Eigen::MakePointer> const> const, Eigen::ThreadPoolDevice>, Eigen::array<long, 1ul>, Eigen::array<long, 1ul>, 16, true, false, 0, Eigen::MakePointer>, 48, 16, 0, false, false>, Eigen::internal::gemm_pack_rhs<float, long, Eigen::internal::TensorContractionSubMapper<float, long, 0, Eigen::TensorEvaluator<Eigen::TensorReshapingOp<Eigen::DSizes<long, 2> const, Eigen::TensorImagePatchOp<-1l, -1l, Eigen::TensorMap<Eigen::Tensor<float const, 4, 1, long>, 16, Eigen::MakePointer> const> const> const, Eigen::ThreadPoolDevice>, Eigen::array<long, 1ul>, Eigen::array<long, 1ul>, 16, true, false, 0, Eigen::MakePointer>, 4, 0, false, false>, Eigen::internal::gebp_kernel<float, float, long, Eigen::internal::blas_data_mapper<float, long, 0, 0>, 48, 4, false, false>, Eigen::internal::TensorContractionInputMapper<float, long, 1, Eigen::TensorEvaluator<Eigen::TensorReshapingOp<Eigen::DSizes<long, 2> const, Eigen::TensorMap<Eigen::Tensor<float const, 4, 1, long>, 16, Eigen::MakePointer> const> const, Eigen::ThreadPoolDevice>, Eigen::array<long, 1ul>, Eigen::array<long, 1ul>, 16, true, false, 0, Eigen::MakePointer>, Eigen::internal::TensorContractionInputMapper<float, long, 0, Eigen::TensorEvaluator<Eigen::TensorReshapingOp<Eigen::DSizes<long, 2> const, Eigen::TensorImagePatchOp<-1l, -1l, Eigen::TensorMap<Eigen::Tensor<float const, 4, 1, long>, 16, Eigen::MakePointer> const> const> const, Eigen::ThreadPoolDevice>, Eigen::array<long, 1ul>, Eigen::array<long, 1ul>, 16, true, false, 0, Eigen::MakePointer>, Eigen::internal::blas_data_mapper<float, long, 0, 0> >::pack_rhs(long, long) 0x0000000105f80aa8
Eigen::NonBlockingThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int) 0x000000010def1e7e
std::__1::__function::__func<tensorflow::thread::EigenEnvironment::CreateThread(std::__1::function<void ()>)::'lambda'(), std::__1::allocator<tensorflow::thread::EigenEnvironment::CreateThread(std::__1::function<void ()>)::'lambda'()>, void ()>::operator()() 0x000000010def17df
void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::function<void ()> > >(void*) 0x000000010df15200
_pthread_start 0x00007fff6f560109
thread_start 0x00007fff6f55bb8b`

This model is work in python environment with tf 1.12. I am so puzzled.

`

def load_ckpt():

    sess = tf.Session()
    saver = tf.train.import_meta_graph("./log/model_ldh.meta", clear_devices = True)
    saver.restore(sess, "./log/model_ldh")
    phase_train_ = sess.graph.get_tensor_by_name('phase_train:0')
    keep_prob_ = sess.graph.get_tensor_by_name('keep_prob:0')
    inputs_ = sess.graph.get_tensor_by_name('inputs:0')
    switch_ = sess.graph.get_tensor_by_name('switch:0')
    outputs_B_ = sess.graph.get_tensor_by_name('outputs_B:0')
    outputs_A_ = sess.graph.get_tensor_by_name('outputs_A:0')
    images = np.random.randint(0, 255, size = (1, 112, 96, 3))
    switch = np.array([False])
    #debug = sess.graph.get_tensor_by_name("FaceResNet/NetA_3/conv4/layer_0/Conv/p_re_lu/Relu:0")

    feed_dict = {
        inputs_: images,
        switch_: switch, 
        phase_train_: np.array(False),
        keep_prob_: np.array(1.0)
    }

    ret = sess.run(outputs_A_, feed_dict) # This program could work
    print(ret.shape)
`

**Comment by woshildh** [comment]
need help

**Comment by Saduf2019** [comment]
@woshildh 
Is there any particular reason for using 1.13 version as its quite old and we have support for 1.5 and 2.x versions, would you want to upgrade the latest version and let us know if you are still facing any issue.
With respect to the error reported: #9638 [[link](https://www.tensorflow.org/install/source])

**Comment by woshildh** [comment]
@Saduf2019 Thanks, I will try a new version.

**Comment by woshildh** [comment]
@Saduf2019 , Thanks, I solved this problem after I compile tf 1.13

**Comment by Saduf2019** [comment]
Thanks for the update, glad the issue is resolved.
