### ISSUE TITLE
Tensorflow 2.3: No gradients provided for any variable

### ISSUE THREAD

**Issue by partha117** [tensorflow/tensorflow#43132]
**System information**
- Used Functional API
- OS: Ubuntu 20.04 and Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from source
- TensorFlow version: 2.3
- Python version:3.6.7

Hi I have built a model using functional API but when I start to train the model it says "**No gradients provided for any variable:**"
 A minimalistic [gist](https://gist.github.com/partha117/1c20da6252ef43f429c30fafe17cc93f)  is attached to recreate the error

**Comment by amahendrakar** [comment]
@partha117,
I was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/0b38b676fda3c7fa42d86f89ea4eec87/43132.ipynb). 

However with [TF-nightly](https://colab.research.google.com/gist/amahendrakar/fafb742ce2a2fb43467c6d3defb93144/43132-tf-nightly.ipynb#scrollTo=GVJ3l3ZtwSmg), I am facing a different error stating `ValueError: Input 1 is incompatible with layer Full_Model: expected shape=(None, 183), found shape=(None, 15)`. Please find the attached gist.

Could you please check if you are still facing the same issue with the latest TF-nightly? Thanks!

**Comment by partha117** [comment]
The problem is solved. It was caused by the shape of the dataset output. Previously the shape was (in1,in2,in3) after changing it to ((in1,in2,in3),None) the problem solved.
