### ISSUE TITLE
Data augmentation on TfRecords for multichannel images 

### ISSUE THREAD

**Issue by quartermaine** [tensorflow/tensorflow#43145]
I am working with multichannel medical Nifti images which I convert to TfRecords and create a tf.dataset to pass later on a multichannel 3D CNN.  The shape of the images is (61,73,61,2) which means the image has 2 channels,  is there a way to do data augmentation on the fly when I read the TfRecords and increase the dataset size?  How can I apply the augmentation across all channels?

**Comment by bhack** [comment]
Two years ago we had an official blog post about a biomedical toolkit:
https://blog.tensorflow.org/2018/07/an-introduction-to-biomedical-image-analysis-tensorflow-dltk.html

**Comment by Saduf2019** [comment]
@quartermaine 
Please update as per above comment.

**Comment by quartermaine** [comment]
Thank you for the suggestion @bhack  somehow  I missed the DLTK toolkit. From my understanding the augmentation according to 04_input_normalisation_and_augmentation.ipynb notebook on tutorials has to be done when writing the TfRecords?

**Comment by bhack** [comment]
I don't think It is maintained anymore.

New image augmentation pipelines will be landing from the TF gsoc at https://github.com/tanzhenyu/image_augmentation.
You can try to ask there for you specific use case needs.

**Comment by quartermaine** [comment]
I see.
 Thanks again @bhack I will ask there then.

**Comment by Saduf2019** [comment]
@quartermaine 
Please feel free to move the issue to closed status.
