### ISSUE TITLE
Error while using ModelCheckpoint callback in tf.keras when creating checkpoints.

### ISSUE THREAD

**Issue by Gokul-S-Kumar** [tensorflow/tensorflow#43149]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 20.04 LTS (GNU/Linux 4.4.0-18362-Microsoft x86_64)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):Source
- TensorFlow version (use command below):2.3.0
- Python version:3.8.2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
I am trying to create checkpoints while training the model using ModelCheckpoint callback. It is giving the following error
`TypeError: get_config() missing 1 required positional argument: 'self'`

**Describe the expected behavior**
I tried saving the model using save_model func. It works fine. I think there is some issue with the callback. 

**Standalone code to reproduce the issue**
Link to the gist:
[https://gist.github.com/Gokul-S-Kumar/0a355ca70e44953f3af40693e38bc2b1](url)

**Other info / logs** 
Link to full description of the error, in case useful:
[https://gist.github.com/Gokul-S-Kumar/b478a8fba470626aca51d4e09331388b](url)

PS:- I may be committing a simple mistake, if yes please help in pointing it out so that I can rectify it.

**Comment by bhack** [comment]
Can you try changing the init with `kernel_initializer = keras.initializers.he_normal()`?

**Comment by Gokul-S-Kumar** [comment]
> Can you try changing the init with `kernel_initializer = keras.initializers.he_normal()`?

Thanks @bhack !! It works :). 
I have been initializing weights in the previous way all the time. Is it wrong to do so?

**Comment by Saduf2019** [comment]
@Gokul-S-Kumar 
Please feel free to move the issue to closed status if resolved.

**Comment by thusinh1969** [comment]
TF is not longer backward compatible and posed so much irritations !!!!
