### ISSUE TITLE
tensorflow:AutoGraph could not transform <function Model.make_train_function.<locals>.train_function at 0x0000018DDF556708> and will run it as-is.

### ISSUE THREAD

**Issue by JoshPattman** [tensorflow/tensorflow#43154]
WARNING:tensorflow:AutoGraph could not transform <function Model.make_train_function.<locals>.train_function at 0x0000018DDF556708> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <function Model.make_train_function.<locals>.train_function at 0x0000018DDF556708> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert

**Comment by bhack** [comment]
Do you have a very minimal but runnable standalone example/colab to reproduce this?

**Comment by GTK-ARJUN** [comment]
I am getting the same error. What can be done tor resolve this?

**Comment by amahendrakar** [comment]
> I am getting the same error. What can be done tor resolve this?

@GTK-ARJUN,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by shuchitajain** [comment]
I am facing the same issue. Does anyone know how to fix it??
It's really urgent.
