### ISSUE TITLE
`validation_split` support for RaggedTensors

### ISSUE THREAD

**Issue by dcpatton** [tensorflow/tensorflow#43157]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.3.0
- Are you willing to contribute it (Yes/No):No

**Describe the feature and the current behavior/state.**
Call to tf.keras.Model.fit with validation_split=0.2 produces:

ValueError: `validation_split` is only supported for Tensors or NumPy arrays, found following types in the input: [<class 'tensorflow.python.ops.ragged.ragged_tensor.RaggedTensor'>]

**Will this change the current api? How?**
No.
**Who will benefit with this feature?**
Users of RaggedTensor
**Any Other info.**
This only occurs when validation_split parameter is being used.

**Comment by ravikyram** [comment]
@dcpatton 

 Do you have any use case that requires the feature you are interested in? Are you interested to submit a PR ?
Thanks!

**Comment by dcpatton** [comment]
I do not have a PR to submit. Is there a template for the Use Case?
