### ISSUE TITLE
ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

### ISSUE THREAD

**Issue by pratikshambharkar** [tensorflow/tensorflow#43152]
ImportError: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-0f2507b3ca9f> in <module>
     16 
     17 
---> 18 from keras.models import Sequential
     19 from keras.layers import Dense, Dropout, BatchNormalization, Activation
     20 from keras import regularizers

C:\ProgramData\Anaconda3\lib\site-packages\keras\__init__.py in <module>
      4 except ImportError:
      5     raise ImportError(
----> 6         'Keras requires TensorFlow 2.2 or higher. '
      7         'Install TensorFlow via `pip install tensorflow`')
      8 

ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

**Comment by bhack** [comment]
Please import keras from tensorflow '`from tensorflow import keras`.

See https://github.com/keras-team/keras/releases/tag/2.4.0

**Comment by Saduf2019** [comment]
@pratikshambharkar 
Can you please share the complete stand alone indented code for us to replicate the issue faced or if possible share a colab gist with the error reported.
please refer to [this link ](https://stackoverflow.com/questions/63006475/how-to-solve-importerror-keras-requires-tensorflow-2-2-or-higher-install-tenso)as per the error reported.
You may also verify with existing issues containing "ImportError: DLL load failed": #42495 #43026 #43003

**Comment by lamberta** [comment]
Correct, Conda is not officially supported and often lags behind the current release.

As @bhack noted, there's a mention here: https://www.tensorflow.org/install/pip#conda —but little appetite for further visibility of an out-of-date package. But you're welcome to add a an entry to the [errors.md](https://github.com/tensorflow/docs/blob/master/site/en/install/errors.md) page, if you think that is useful. Thanks

**Comment by pratikshambharkar** [comment]
@Saduf2019 

i have tried this also :- https://docs.anaconda.com/anaconda/user-guide/tasks/tensorflow/
< conda create -n tf tensorflow
   conda activate tf

    conda create -n tf-gpu tensorflow-gpu 
    conda activate tf-gpu
>

`import tensorflow`
