### ISSUE TITLE
Make failed with C++ API used like external library. Error: static assertion failed: std::string is no longer a scalar type, use tensorflow::tstring

### ISSUE THREAD

**Issue by NAEE09** [tensorflow/tensorflow#43150]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3
- Python version: 3.6.9
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 7.5.0
- GPU model and memory:
 
I'm trying to use TensorFlow c++ like external library with cmake to load a model trained in python, I use the example of label image https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/label_image. I did it with past version of tensorflow v1.14.0, bazel 0.24.1, protobuf 3.7.x, Eigen 3.3.7, but when I updated the version of Tensorflow 2.3.0 with its dependencies (bazel 3.1.0, protobuf 3.9.2, Eigen 3.3.x (according to workspace.bzl)) there is the next error:

`[ 50%] Building CXX object CMakeFiles/main.dir/main.cc.o
In file included from /usr/local/include/tensorflow/cc/framework/ops.h:21:0,
                 from /usr/local/include/tensorflow/cc/ops/const_op.h:19,
                 from /home/nae/ML/LoadModel/src/main.cc:41:
/usr/local/include/tensorflow/core/framework/tensor.h: In instantiation of ‘typename tensorflow::TTypes<T>::Scalar tensorflow::Tensor::scalar() [with T = std::__cxx11::basic_string<char>; typename tensorflow::TTypes<T>::Scalar = Eigen::TensorMap<Eigen::TensorFixedSize<std::__cxx11::basic_string<char>, Eigen::Sizes<>, 1, long int>, 16, Eigen::MakePointer>]’:
/home/nae/ML/LoadModel/src/main.cc:109:26:   required from here
/usr/local/include/tensorflow/core/framework/tensor.h:878:3: error: static assertion failed: std::string is no longer a scalar type, use tensorflow::tstring
   static_assert(
`

**Any other info / logs**
CMakeLists.txt:

cmake_minimum_required(VERSION 3.10)

project(LoadModel)
find_package(Tensorflow REQUIRED)
find_package(Protobuf REQUIRED)
find_package(Eigen3 REQUIRED)

set(INCLUDE_DIRS ${Tensorflow_INCLUDE_DIRS}
		 ${EIGEN3_INCLUDE_DIRS}
                 ${Protobuf_INCLUDE_DIRS}
)
set(MODULE_LIBS ${Tensorflow_LIBRARIES}
		${EIGEN3_LIBRARIES}
                ${Protobuf_LIBRARIES}
)

add_executable(main ./main.cc)
target_include_directories(main PUBLIC ${INCLUDE_DIRS})
target_link_libraries(main ${MODULE_LIBS})

Example label images

 https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/label_image

**Comment by bhack** [comment]
They have started to use `tensorflow::tstring` as you can see from https://github.com/tensorflow/tensorflow/commit/f05a57eefe9f03c9fae83d0fcb727ee07949d963 /cc @gharibian

**Comment by NAEE09** [comment]
Solved! thanks.
