### ISSUE TITLE
Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2

### ISSUE THREAD

**Issue by Chenpuh** [tensorflow/tensorflow#43168]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary: `libtensorflow_jni-cpu-windows-x86_64-1.14.0/tensorflow_jni.dll`
- TensorFlow version: 1.14.0

**Describe the problem**
2020-09-12 01:46:00.374893: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Model load took 21ms, TensorFlow version: 1.14.0
Successfully loaded model from the input stream

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. Go to: https://www.tensorflow.org/install/lang_java and download libtensorflow.jar and Java Native Interface (JNI) file, save it to project root;
2. Load tensorflow through `System.load ("./tensorflow_jni.dll")`

**Comment by bhack** [comment]
It is ok. It is just an info that the default binary it is not compiled with AVX2 but you have an AVX2 CPU available.

**Comment by bhack** [comment]
See also https://github.com/tensorflow/tensorflow/issues/15450#issuecomment-352882680

**Comment by Chenpuh** [comment]
Thanks

**Comment by lucio-cyber** [comment]
Hello,
I am using tensorflow for deepsignal and I have the same problem and that is: "Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA".
I installed tensorflow in a virtual environment along with tombo and python3 as they themselves suggest. The tensorflow version I have is 1.8.0.
How can I solve this problem ?

**Comment by bhack** [comment]
https://github.com/tensorflow/tensorflow/issues/43168#issuecomment-691523272.
