### ISSUE TITLE
SyncBatchNormalization has NaN losses with channels-first format

### ISSUE THREAD

**Issue by MinasTyuru** [tensorflow/tensorflow#43165]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 14.04 running in Docker container (host is 18.04)
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.0 and 2.3.0
- Python version: 3.6.8
- Bazel version (if compiling from source): 0.29.1-1.0
- GCC/Compiler version (if compiling from source): 4.8.5
- CUDA/cuDNN version: 10.0
- GPU model and memory: Various, e.g. Nvidia TITAN X

**Describe the current behavior**
When using the experimental SyncBatchNormalization layer with the channels-first (NCHW or batch-channel-height-width) format, the output of the layer is NaN.

**Describe the expected behavior**
The output of the layer should be valid, as occurs with the default channels-last format, or with regular BatchNormalization.

**Standalone code to reproduce the issue**
This [Colab notebook](https://colab.research.google.com/drive/1zeLVlrWwohsmGJnEOQaFsb_gzH6xOFo1?usp=sharing) contains several models that demonstrate the issue. A Keras model with NCHW format, and a Keras model with SyncBatchNorm, both train correctly. However, a Keras model with _both_ NCHW format and SyncBatchNorm immediately fails with NaN loss. Similarly, an Estimator model with NCHW and SyncBatchNorm fails with NaN loss.

**Other info / logs**
I think the input tensor size seems to be related to the error. I tried a smaller tensor (10x10x10) before and it didn't cause the issue. And a medium-size tensor (I think 30x30x30) trained for a few steps and then encountered this issue. I'd have to double-check on the current code, but I think there's something there.

In the example, the loss is NaN. I believe that the output of the layer is already NaN (I'm not sure if every single value is NaN or just some of the values). I had some tests where I printed out the sum of the layer outputs etc., and if I recall correctly, immediately after the first SyncBatchNorm layer they were already NaN. This happened on the second and later iterations, but not the first iteration, so I suspect there may be some issue with backpropagation rather than with the forward step. For example, hypothetically if it happened that backpropagation in the first step caused the moving variance to go to 0 (or infinity), I think we would see behavior like this.

You should be able to replicate all these tests fairly easily with some simple print functions etc., but if you need any more information please let me know and I can provide it.

The loss function doesn't seem to matter - I can use various loss functions and still trigger the NaN - but the Conv2D at the beginning may matter; it seems like it works fine if I remove that layer or if I change it to channels-last.

If I run on Colab without a GPU, I get the following error:

```
InvalidArgumentError:  Conv2DCustomBackpropFilterOp only supports NHWC.
	 [[node gradient_tape/sequential/conv2d/Conv2D/Conv2DBackpropFilter (defined at <ipython-input-3-11fc99b50ff4>:18) ]] [Op:__inference_train_function_654]
```

I wonder if this might be related to the problem?

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3 and was able to reproduce the issue. Please, find the gist [here.](https://colab.research.google.com/gist/ravikyram/baf51cdacf5192432098f321e1e3bfb2/untitled341.ipynb) Thanks!

**Comment by MinasTyuru** [comment]
@yhliang2018 Have you been able to take a look at this?

**Comment by yhliang2018** [comment]
Add @anj-s to look into the problem, as she knows more about SyncBatchNormalization layer.

**Comment by MinasTyuru** [comment]
@anj-s Have you had a chance to take a look at this?

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tensorflow-gpu 2.5, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/eed7bcac822d0d53daea74d517eca509/43165.ipynb). Thanks!

**Comment by lifeiteng** [comment]
same problem

**Comment by chunduriv** [comment]
@MinasTyuru, 

Closing this issue as it is fixed in latest version of TensorFlow. Please refer attached [gist](https://colab.research.google.com/gist/chunduriv/4f59b004ccd37d5e8e55fcffa7d36703/43165.ipynb) and feel free to reopen the issue if you still have a concern. Thanks!
