### ISSUE TITLE
DLL load failed: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by ITAC85v2** [tensorflow/tensorflow#43169]
**System information**
I am using Tensorflow on Windows 10 2004
Tensorflow installed from PIP (I don't know if that's what you are asking for, sorry)
Tensorflow version is 1.15
Python version is 3.7 (64-bit)

**Describe the problem**
It says _"DLL load failed: A dynamic link library (DLL) initialization routine failed."_

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I spent many hours installing necessary packages for [this repository](https://github.com/CorentinJ/Real-Time-Voice-Cloning), plus any extra packages that it asked for.

**Any other info / logs**
> Traceback (most recent call last):
>   File "E:\Python\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "E:\Python\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "E:\Python\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "E:\Python\lib\imp.py", line 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "E:\Python\lib\imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "E:\a\b\Real-Time-Voice-Cloning-master\demo_cli.py", line 4, in <module>
>     from synthesizer.inference import Synthesizer
>   File "E:\a\b\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 1, in <module>
>     from synthesizer.tacotron2 import Tacotron2
>   File "E:\a\b\Real-Time-Voice-Cloning-master\synthesizer\tacotron2.py", line 3, in <module>
>     from synthesizer.models import create_model
>   File "E:\a\b\Real-Time-Voice-Cloning-master\synthesizer\models\__init__.py", line 1, in <module>
>     from .tacotron import Tacotron
>   File "E:\a\b\Real-Time-Voice-Cloning-master\synthesizer\models\tacotron.py", line 1, in <module>
>     import tensorflow as tf
>   File "E:\Python\lib\site-packages\tensorflow\__init__.py", line 99, in <module>
>     from tensorflow_core import *
>   File "E:\Python\lib\site-packages\tensorflow_core\__init__.py", line 28, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
>   File "E:\Python\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
>     module = self._load()
>   File "E:\Python\lib\site-packages\tensorflow\__init__.py", line 44, in _load
>     module = _importlib.import_module(self.__name__)
>   File "E:\Python\lib\importlib\__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "E:\Python\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "E:\Python\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "E:\Python\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "E:\Python\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "E:\Python\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "E:\Python\lib\imp.py", line 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "E:\Python\lib\imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
> 
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/errors
> 
> for some common reasons and solutions.  Include the entire stack trace
> above this error message when asking for help.

**Comment by amahendrakar** [comment]
@ITAC85v2,
You might be facing this issue because of the following reasons

- You are running 32-bit Python or 32-bit OS
- You have not installed the [Microsoft Visual C++ Redistributable](https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads) package
- Your CPU does not support AVX instructions. 

Please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) and check if you have the correct dependencies installed.

Also, check these similar duplicate issues: #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204.

Thanks!

**Comment by ITAC85v2** [comment]
Do you possibly know away to install Microsoft Visual C++ Redistributable to a removable drive instead of a local hard drive? I've tried to create a symlink but it did not work. Do you have any ideas?

**Comment by ITAC85v2** [comment]
I have done the same steps on a different computer and with Microsoft VC++ and I have received this:

> Traceback (most recent call last):
>   File "C:\Users\Betty Faye\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Users\Betty Faye\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Users\Betty Faye\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "C:\Users\Betty Faye\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "C:\Users\Betty Faye\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "demo_cli.py", line 4, in <module>
>     from synthesizer.inference import Synthesizer
>   File "G:\a\b\Real-Time-Voice-Cloning-master\synthesizer\inference.py", line 1, in <module>
>     from synthesizer.tacotron2 import Tacotron2
>   File "G:\a\b\Real-Time-Voice-Cloning-master\synthesizer\tacotron2.py", line 3, in <module>
>     from synthesizer.models import create_model
>   File "G:\a\b\Real-Time-Voice-Cloning-master\synthesizer\models\__init__.py", line 1, in <module>
>     from .tacotron import Tacotron
>   File "G:\a\b\Real-Time-Voice-Cloning-master\synthesizer\models\tacotron.py", line 1, in <module>
>     import tensorflow as tf
>   File "C:\Users\Betty Faye\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 99, in <module>
>     from tensorflow_core import *
>   File "C:\Users\Betty Faye\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\__init__.py", line 28, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
>   File "C:\Users\Betty Faye\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
>     module = self._load()
>   File "C:\Users\Betty Faye\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 44, in _load
>     module = _importlib.import_module(self.__name__)
>   File "C:\Users\Betty Faye\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "C:\Users\Betty Faye\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "C:\Users\Betty Faye\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "C:\Users\Betty Faye\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Users\Betty Faye\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Users\Betty Faye\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "C:\Users\Betty Faye\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "C:\Users\Betty Faye\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
> 
> 
> Failed to load the native TensorFlow runtime.

I do not know if this is the same or not as I did not bother checking.

**Comment by amahendrakar** [comment]
> I have done the same steps on a different computer and with Microsoft VC++ and I have received this:

@ITAC85v2,
Could you please provide the make and model of the CPU on this machine? Thanks!
