### ISSUE TITLE
OpenCL

### ISSUE THREAD

**Issue by akashakara** [tensorflow/tensorflow#43171]
I understand TensorFlow only supports CUDA. What would need to be done to add in OpenCL support?

**Comment by bhack** [comment]
It doesn't support CUDA only but also ROCM for AMD, Onednn for Intel, delagates GPU/NPU on android etc..
Also the new in progress [runtime](https://github.com/tensorflow/runtime) probably will expand the support over new hw ecosystem targets.

**Comment by Degerz** [comment]
> What would need to be done to add in OpenCL support?

OpenCL would need to improve it's standards to become a viable option ... 

It'd have to change into a single source programming model where host and device code can lie in the same source file. This ties into the previous statement but OpenCL kernels would also need to be able to support templates too ...

**Comment by gowthamkpr** [comment]
@akashakara There is OpenCL support via SYCL on Tensorflow. Please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/22#issuecomment-266050835).
