### ISSUE TITLE
Segfault with tf.linalg.cholesky

### ISSUE THREAD

**Issue by chrism0dwk** [tensorflow/tensorflow#43170]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Mint 20
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary (PyPI)
- TensorFlow version (use command below): 2.4.0-dev20200911
- Python version: 3.7.6 (Anaconda)
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: CUDA 11.0, cuDNN 8.0.3.33 (NVIDIA Ubuntu 20.04 repo)
- GPU model and memory: GeForce GTX 1650 3.82GiB

**Describe the current behavior**
Calling `tf.linalg.cholesky` results in Python aborting (SIGABRT). 

**Describe the expected behavior**
The Cholesky decomposition succeeds.

**Standalone code to reproduce the issue**

```Python
python -c "import tensorflow as tf; tf.linalg.cholesky(tf.eye(6))"
```

**Other info / logs**
Log attached: [tf_error_log.txt](https://github.com/tensorflow/tensorflow/files/5212288/tf_error_log.txt)

**Comment by ravikyram** [comment]
@chrism0dwk 

I have tried in colab with TF nightly version(`2.4.0-dev20200912`) and i am not seeing any issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/835b6b031991af76988c9252b902289c/untitled340.ipynb).Please, verify once and close the issue. Thanks!

**Comment by chrism0dwk** [comment]
Shucks, looks like it's my CUDA 11 stack, then.  Thanks for verifying.

**Comment by chrism0dwk** [comment]
Re-opening, I'm afraid.  Colab appears to be using CUDA-10.1 still (and runs error-free as above:

```python
!/usr/local/cuda/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```
whereas the tf-nightly packages from PyPI appear to demand CUDA-11.0.   Does this mean that the Colab tf-nightly build is against a different CUDA version to that available more widely?

Chris

**Comment by chrism0dwk** [comment]
A quick update: I tried installing tf-nightly via the Docker container, and I get the same error.  So, either this is a problem with my NVIDIA driver version (455.23.05), or there is an underlying bug in TF.  Terminal log from the interactive container attached.

[tf_docker_abrt.txt](https://github.com/tensorflow/tensorflow/files/5321758/tf_docker_abrt.txt)

**Comment by chrism0dwk** [comment]
I found out how to use TF_CPP_MIN_LOG_LEVEL and TF_CPP_MIN_VLOG_LEVEL.  Debug information attached.
[chol_log.txt](https://github.com/tensorflow/tensorflow/files/5678190/chol_log.txt)

**Comment by sachinprasadhs** [comment]
Was able to run your code without any error in Tensorflow 2.5 and it's using Cuda 11, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/a8f029cd2884887e0894383bcbefc2bf/43170.ipynb) and confirm of the issue is good to close. Thanks!

**Comment by chrism0dwk** [comment]
Yes, looks good with TF2.5 and CUDA 11.2.  Many thanks!
