### ISSUE TITLE
unable to install tensorflow 

### ISSUE THREAD

**Issue by hunk3749** [tensorflow/tensorflow#4317]
i am using ubuntu 12.04. i was following instructions from tensorflow.org for installing the tensor flow but getting the following error after downloading the the tensor flow-
ownloading tensorflow-0.10.0-cp27-none-linux_x86_64.whl (36.6Mb): 36.6Mb downloaded
  Running setup.py egg_info for package from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0-cp27-none-linux_x86_64.whl
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-uIJFE4-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/tmp/pip-uIJFE4-build/setup.py'

---

Command python setup.py egg_info failed with error code 1
Storing complete log in /home/dhanpal/.pip/pip.log

**Comment by martinwicke** [comment]
I don't know if TensorFlow works with Ubuntu 12. Anybody have experience with that?

What is your version of setuptools and pip?

**Comment by ppwwyyxx** [comment]
#56 looks related.

**Comment by martinwicke** [comment]
In fact, looks like a duplicate. Thanks @ppwwyyxx! Closing. 

@hunk3749, try upgrading pip.

**Comment by git-sohib** [comment]
I tried each and every upgrading packages but didn't help.
I tried 
```
pip install --upgrade pip
pip install --upgrade setuptools
pip install unroll
easy_install -U setuptools
pip install ez_setup
```
Any updates on that so far?
