### ISSUE TITLE
Tensorflow 2.3 not detecting gpu (cuda 10.0)

### ISSUE THREAD

**Issue by offset-null1** [tensorflow/tensorflow#43189]
**System information**
- OS Platform and Distribution:Linux Ubuntu 18.04
- TensorFlow installed from (source or binary):
- TensorFlow version:2.3
- Python version:3.6.9
- Installed using:pip
- CUDA/cuDNN version:10.0/ 7.6.5
- GPU model and memory: gtx 1050 ti, 4GB

I'm not able to figure out why tensorflow is not detecting gpu.
As soon as I import tf in cmd it shows this warning. 

_**>>> import tensorflow as tf**_
2020-09-13 19:49:51.205462: W tensorflow/stream_executor/platform/default/dso_lo
ader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcuda
rt.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRAR
Y_PATH: /usr/local/cuda-10.2/lib64
2020-09-13 19:49:51.205488: I tensorflow/stream_executor/cuda/cudart_stub.cc:29]
 Ignore above cudart dlerror if you do not have a GPU set up on your machine.

I tried checking with 
**_>>> tf.test.gpu_device_name()_**
but it gives an empty string ' '

Its not a dependency issue as tf 2 supports cuda 10

And one more weird stuff, when I run **_'nvidia-smi'_** on cmd prompt it shows cuda version as 11 but when I run **_'cat /usr/local/cuda/version.txt'_** it shows version as 10.0.130

**Comment by bhack** [comment]
I think this more a question for Stackoverflow or Ubuntu support channels then a bug.
If you really have CUDA 11 try to install `pip install tf-nightly`

**Comment by offset-null1** [comment]
@bhack  but I have cuda 10 installed, I'll try installing tf-nightly

**Comment by amahendrakar** [comment]
@offset-null1,
TensorFlow v2.3 is compatible with CUDA 10.1 and cuDNN 7.6. For more information regarding this please take a look at the [tested build configurations](https://www.tensorflow.org/install/source#gpu).


And the CUDA version mismatch query has been explained in [this](https://stackoverflow.com/a/53504578) StackOverflow comment. Thanks!

**Comment by offset-null1** [comment]
@amahendrakar thanks, I have these cuda runtime api support in my system

/usr/local/cuda-10.0/doc/man/man7/libcudart.so.7
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart.so.10.0
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart.so.10.0.130

But still tf shows:

>>> import tensorflow as tf
2020-09-14 14:32:03.792992: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.11.0'; dlerror: **_libcudart.so.11.0_**: cannot open shared object file: No such file or directory; **_LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64:_**
2020-09-14 14:32:03.793013: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

Still tf searching for libcudart.so.11.0 version even though I have runtime version as 10.0 maybe because my driver version is 11.0 ?

**Comment by bhack** [comment]
If `nvidia-smi` still gives you CUDA 11.0 and you have also CUDA 10 file It seems to me that your CUDA installation on your system is not in a good state.

**Comment by offset-null1** [comment]
@bhack as per [https://stackoverflow.com/questions/53422407/different-cuda-versions-shown-by-nvcc-and-nvidia-smi/53504578#53504578](this) its not an issue and my cuda runtime api support (libcudart.so) is 10.0 which tensorflow asks for and supports too, but idkw is searching for libcudart.so.11.0 eventho my machine doesn't have it.

**Comment by bhack** [comment]
Can you paste the output of `nvida-smi`?

**Comment by offset-null1** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.06    Driver Version: 450.51.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   66C    P0    N/A /  N/A |    632MiB /  4040MiB |     15%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2372      G   /usr/lib/xorg/Xorg                192MiB |
|    0   N/A  N/A      3214      G   /usr/bin/kwin_x11                  66MiB |
|    0   N/A  N/A      3220      G   /usr/bin/krunner                    1MiB |
|    0   N/A  N/A      3222      G   /usr/bin/plasmashell               46MiB |
|    0   N/A  N/A      3300      G   /usr/bin/latte-dock                10MiB |
|    0   N/A  N/A      3878      G   ...AAAAAAAAA= --shared-files      216MiB |
|    0   N/A  N/A     13705      G   ...oken=14238599874549303426       44MiB |
|    0   N/A  N/A     13926      C   /usr/bin/python3                   43MiB |
+-----------------------------------------------------------------------------+


Ik it shows 11.0 but thats driver version.

Runtime api version is:
>  cat /usr/local/cuda/version.txt
CUDA Version 10.0.130

**Comment by bhack** [comment]
Please ask support to Ubuntu support channels on how to fix your CUDA setup. 
It seems to me not clean cause you have mixed CUDA 11 and CUDA 10 elements.

**Comment by keszegrobert** [comment]
I am having the same issue on Jetson Nano SD image v42, Cuda 10.0, and Tensorflow 2.3.1 is trying to load libcudart.so.10.2

**Comment by max0x7ba** [comment]
On Ubuntu 18.04 you need to install NVidia repo from https://developer.nvidia.com/cuda-downloads (choose installer type "deb (network)"). Uninstall all nvidia and cuda packages and then install packages xserver-xorg-video-nvidia-460, nvidia-driver-460, cuda-toolkit-11-2 from NVidia repo.

```
I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
```
