### ISSUE TITLE
Adding HDFS connection cache on tensorflow side can improve performance by 20+ times

### ISSUE THREAD

**Issue by yuanbopeng** [tensorflow/tensorflow#43187]
This is a issue from TaiJi AI platform in Tencent.

**System information**
- OS Platform and Distribution : Linux version 4.14.105-1-tlinux3-0010
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.13.1（we use）and the latest version also has this problem
- Python version: 3.6
- C++ version: 11
- hadoop version: 2.8

**test conclusion**
After testing, it is found that adding hdfs connection cache on the tensorflow side can improve performance by 20+ times.

All HDFS APIs that rely on [HDFS Connect](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/hadoop/hadoop_file_system.cc#L160) have this performance problem. Here is the test result of [the HDFS stat API](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/hadoop/hadoop_file_system.cc#L553). [The HDFS stat](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/hadoop/hadoop_file_system.cc#L553) with connection cache takes about 458 microseconds, but [The HDFS stat](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/hadoop/hadoop_file_system.cc#L553) without connection cache takes about 12114 microseconds, so it can be concluded that adding hdfs connection cache on the tensorflow side can improve performance by **20+ Times**. For details, please refer to the test results below.

**solution**: [patch-1](https://github.com/tensorflow/tensorflow/pull/43188)

**test code**
```
#include <sys/time.h>
#include <iostream>

int64_t getCurrentTime() {
  struct timeval tv;
  gettimeofday(&tv, NULL);
  return tv.tv_sec * 1000000 + tv.tv_usec;
}

Status HadoopFileSystem::Stat(const string& fname, TransactionToken* token,
                              FileStatistics* stats) {
  int64_t start = getCurrentTime();
  .......................
  int64_t end = getCurrentTime();
  std::cout << "HadoopFileSystem::Stat use time " << (end - start) << " µs" << std::endl;
  return Status::OK();
}
```

**logs** 
[stat](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/hadoop/hadoop_file_system.cc#L553) without connection cache
![image](https://user-images.githubusercontent.com/70072713/93019627-bed5a600-f60a-11ea-8dc6-1c9b83c4d18f.png)

[stat](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/hadoop/hadoop_file_system.cc#L553) with connection cache
![image](https://user-images.githubusercontent.com/70072713/93019596-98b00600-f60a-11ea-8e17-b919a250c386.png)

**Comment by Saduf2019** [comment]
@yuanbopeng 
Is there any particular reason to be using tf 1.13, support is available from 1.15 and 2.x versions.
Would you want to upgrade and let us know if you still face the issue.

**Comment by yuanbopeng** [comment]
@Saduf2019 1.15 and 2.x versions still have this performance  problem

**Comment by yuanbopeng** [comment]
@vnvo2409

I noticed that this performance problem also exists in [the new HDFS filesystem plugin](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/experimental/filesystem/plugins/hadoop/hadoop_filesystem.cc). You may need to pay attention to the progress of this issue.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/experimental/filesystem/plugins/hadoop/hadoop_filesystem.cc#L207

**Comment by vnvo2409** [comment]
Don't worry. I will keep track of the change in all 3 cloud filesystems and I will merge them into the plugins soon.

**Comment by yuanbopeng** [comment]
This has been solved by https://github.com/tensorflow/tensorflow/pull/43188
