### ISSUE TITLE
tf.keras.applications.ResNet50 does not work properly 

### ISSUE THREAD

**Issue by nick-nikzad** [tensorflow/tensorflow#43194]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): "Red Hat Enterprise Linux Server" v7.6
- TensorFlow version (use command below): 2.2
- Python version: 3.8
- CUDA/cuDNN version: 10.1
- GPU model and memory: Tesla v100 32G

Hello everyone,
I have just tried to use pre-trained ResNet50 with tf.keras.applications.ResNet50(**args). The thing is happening for me is that after downloading weights, nothing else happens!! even after a couple of hours it does not go any further!! Any idea? what may be the casue of this? Any solution?

Many thanks for your help in advance.

I use as follow:

ENCODER_BASE = tf.keras.applications.ResNet50(include_top=False,input_shape=(None,None,3), weights='imagenet')

![image](https://user-images.githubusercontent.com/54047164/93038849-62659b80-f689-11ea-8d8e-b634407469a7.png)

**Comment by ravikyram** [comment]
@nick-nikzad 

Request you to share colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster.Thanks!

**Comment by nick-nikzad** [comment]
Thanks for your reply.

I get the issue just with running of below simple code:

import tensorflow as tf
ENCODER_BASE = tf.keras.applications.ResNet50(include_top=False,input_shape=(None,None,3),weights='imagenet')

Note: once I run the above line on my laptop ( it is only cpu), it is fine and works. But as I run on our GPU cluster the issue raises. It also uses the almost full capacity of the GPU 32GB.

Thanks.

**Comment by ravikyram** [comment]
@nick-nikzad 

I have tried in colab with TF-GPU version 2.3.0 and i am not seeing any issue. Please, find the gist [here.](https://colab.research.google.com/gist/ravikyram/7e9c0cd69f0b5527ed6f1717d4faa62c/untitled346.ipynb).Thanks!

**Comment by nick-nikzad** [comment]
Thanks but once I tried for TF-GPU version 2.2.0 which is mine it fails.  Would you please take a look [here](https://colab.research.google.com/drive/1o6s4aWBtV3O4RzmD5i7fPWfUvgZid90v#scrollTo=u76PSye_TOdD). Thanks.

**Comment by ravikyram** [comment]
@nick-nikzad 

Please, grant me the access for the colab link you have provided.Also, please check you are facing the same issue with the latest version of Tensorflow ie. 2.3. Thanks!

**Comment by nick-nikzad** [comment]
https://colab.research.google.com/drive/1o6s4aWBtV3O4RzmD5i7fPWfUvgZid90v?usp=sharing

**Comment by bhack** [comment]
@nickdesaulniers Change your colab with `!pip install tensorflow==2.2.0`
