### ISSUE TITLE
W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found

### ISSUE THREAD

**Issue by CalendulaED** [tensorflow/tensorflow#43193]
I got this issue when I run import tensorflow as tf in command line

>>> import tensorflow as tf
2020-09-13 17:53:34.644899: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-09-13 17:53:34.649089: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

I use win10 and install the CUDA and cuDNN
But I don't understand why this still happened.
![image](https://user-images.githubusercontent.com/68514251/93029699-06e4d080-f5eb-11ea-9948-a0133f0f8603.png)
![image](https://user-images.githubusercontent.com/68514251/93029705-19f7a080-f5eb-11ea-9dc2-3087ff1379fe.png)

**Comment by bhack** [comment]
Please `pip install tf-nightly` for CUDA 11

**Comment by CalendulaED** [comment]
After I tried pip install tf-nightly, it still shows the same error I think
![image](https://user-images.githubusercontent.com/68514251/93029816-22041000-f5ec-11ea-82c3-ecbc5dafbe05.png)

**Comment by bhack** [comment]
Is not the same error cause now it is looking for `110`.

Are you compilant with these steps?
> Install the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017, and 2019. Starting with the TensorFlow 2.1.0 version, the msvcp140_1.dll file is required from this package (which may not be provided from older redistributable packages). The redistributable comes with Visual Studio 2019 but can be installed separately:

> - Go to the Microsoft Visual C++ downloads,
> - Scroll down the page to the Visual Studio 2015, 2017 and 2019 section.
> - Download and install the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019 for your platform.
> - Make sure long paths are enabled on Windows.
> - Install the 64-bit Python 3 release for Windows (select pip as an optional feature).

**Comment by bhack** [comment]
You will find more on Windows tabs at https://www.tensorflow.org/install/pip#windows

**Comment by CalendulaED** [comment]
> Is not the same error cause now it is looking for `110`.
> 
> Are you compilant with these steps?
> 
> > Install the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017, and 2019. Starting with the TensorFlow 2.1.0 version, the msvcp140_1.dll file is required from this package (which may not be provided from older redistributable packages). The redistributable comes with Visual Studio 2019 but can be installed separately:
> 
> > * Go to the Microsoft Visual C++ downloads,
> > * Scroll down the page to the Visual Studio 2015, 2017 and 2019 section.
> > * Download and install the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019 for your platform.
> > * Make sure long paths are enabled on Windows.
> > * Install the 64-bit Python 3 release for Windows (select pip as an optional feature).

I think the problem is solved after I Download and install the Microsoft Visual C++ Redistributable.
Thank you so much !

**Comment by bhack** [comment]
You need also to rely on `tf-nightly` for CUDA 11 untill TF 2.4 is released.

**Comment by CalendulaED** [comment]
I tried to use the example given by https://github.com/tensorflow/tensorflow
after I run the tf.add(1, 2).numpy()
it still shows some errors but evenlty output the 3
will this be a problem?
![image](https://user-images.githubusercontent.com/68514251/93030111-963fb300-f5ee-11ea-9da7-d99c22056cfc.png)

**Comment by bhack** [comment]
Check that your software requirements are ok https://www.tensorflow.org/install/gpu#windows_setup

**Comment by CalendulaED** [comment]
> Check that your software requirements are ok https://www.tensorflow.org/install/gpu#windows_setup

I think I have everything it required.
And after I update my GPU driver, it shows the same error as the beginning.
![image](https://user-images.githubusercontent.com/68514251/93030924-de61d400-f5f4-11ea-9b65-5c38f8f99066.png)

**Comment by bhack** [comment]
Have you double checked the `%PATH%`

**Comment by CalendulaED** [comment]
> Have you double checked the `%PATH%`?

I run all four Path in https://www.tensorflow.org/install/gpu#windows_setup.
But it still missing for 110

**Comment by bhack** [comment]
Have you changed the documentation PATH strings for your CUDA 11 (doc has CUDA 10)? 
Have you checked that these paths exist on your system?

**Comment by CalendulaED** [comment]
> Have you changed the documentation PATH strings for your CUDA 11 (doc has CUDA 10)?
> Have you checked that these paths exist on your system?

Yes, I manually added it for the first three, but the last one "C:\tools\cuda\bin", I don't think I have this folder

![image](https://user-images.githubusercontent.com/68514251/93032144-ba56c080-f5fd-11ea-8f1d-a22e5f4be87c.png)
![image](https://user-images.githubusercontent.com/68514251/93032149-bdea4780-f5fd-11ea-9a9b-765b82a64ce9.png)

**Comment by CalendulaED** [comment]
At the beginning, I copy the cuDNN's file to bin include and lib respectively, I tried to add a Path directly to cuDNN and it is still having this error

**Comment by bhack** [comment]
Have you set in PATH
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11\bin;%PATH%

Do you have this dir in your system?

**Comment by CalendulaED** [comment]
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11\bin

Yes, and I already added to the path, but it still shows the error

**Comment by CalendulaED** [comment]
This is all the PATH I have, I think I already include all that required
![image](https://user-images.githubusercontent.com/68514251/93033777-b169ed00-f605-11ea-8bfa-3f6206411067.png)
![image](https://user-images.githubusercontent.com/68514251/93033781-b62ea100-f605-11ea-90b5-cc4ead6d14f6.png)

**Comment by bhack** [comment]
Open `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11\bin`.
What file di you have there?
Can you see the `cudart64_100.dll`?

**Comment by CalendulaED** [comment]
I think I only have cudart64_110.dll
(The one that I highlighted)
![image](https://user-images.githubusercontent.com/68514251/93034064-d0b54a00-f606-11ea-991e-429bb7713d58.png)

**Comment by bhack** [comment]
Yes was a typo is corrent. On the same terminal where you are trying to launch Tensorflow can you verify that you have the new path with `echo %PATH:;=&echo.%`?

**Comment by CalendulaED** [comment]
Yes, I believe I have this path in PATH
![image](https://user-images.githubusercontent.com/68514251/93034880-84b7d480-f609-11ea-9b45-ca1f04f4dec3.png)

**Comment by bhack** [comment]
I see a typo there:
`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11\bin\bin`

**Comment by CalendulaED** [comment]
> I see a typo there:
> `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11\bin\bin`

Yes, It is the path to cuDNN, After I download the cuDNN, I copy the bin in cuDNN to here. 
I have both:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11\bin\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11\bin

Before I add the 
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11\bin\bin
it still doesn't work, so I tired to add it

**Comment by CalendulaED** [comment]
And I delete it from PATH, it still has the same error

**Comment by bhack** [comment]
Do you meant v11.0 or v11?

**Comment by CalendulaED** [comment]
> Do you meant v11.0 or v11?

I mean v11.0, I delete the one ~/bin/bin
but it is still not working

**Comment by bhack** [comment]
Is a python 64bit installation?

**Comment by CalendulaED** [comment]
Yes, I think I install the 64bit version?
And the version I have is 3.8.5
![image](https://user-images.githubusercontent.com/68514251/93036314-8edbd200-f60d-11ea-91c5-0f1b0081d37f.png)

**Comment by bhack** [comment]
`python -c "import sys; print(sys.maxsize > 2**32)"`

**Comment by CalendulaED** [comment]
![image](https://user-images.githubusercontent.com/68514251/93036825-f0507080-f60e-11ea-9250-4f68b0acabf1.png)

**Comment by bhack** [comment]
Ok It is 64bit.

So if you have `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin` in the PATH  and you have `cudart64_119.dll` there It is strange that It gives you not found on this file.

**Comment by CalendulaED** [comment]
> Ok It is 64bit.
> 
> So if you have `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin` in the PATH and you have `cudart64_119.dll` there It is strange that It gives you not found on this file.

yeahhh.....very strange, I am not sure what to do in this case....

**Comment by bhack** [comment]
Can you try to close and open the terminal with python and try again?

**Comment by CalendulaED** [comment]
> Can you try to close and open the terminal with python and try again?

So I close the old terminal and reopen it, this is what I got after try to import it
![image](https://user-images.githubusercontent.com/68514251/93037684-fd6e5f00-f610-11ea-8c3b-56f7357d0c31.png)
I think it is still the same error

**Comment by bhack** [comment]
Yes Is the same. 
If the PATH Is currect I only see this old  case that required a reboot https://stackoverflow.com/questions/51111954/tensorflow-cant-find-cudart64-90-dll-even-though-it-is-installed-with-path-va/51112550#51112550

**Comment by CalendulaED** [comment]
> Yes Is the same.
> If the PATH Is currect I only see this old case that required a reboot https://stackoverflow.com/questions/51111954/tensorflow-cant-find-cudart64-90-dll-even-though-it-is-installed-with-path-va/51112550#51112550

Just come back from the reboot, it still shows not find the 110

**Comment by bhack** [comment]
Have you installed python from the Microsoft storie?

**Comment by CalendulaED** [comment]
I believe I install it from offcial website, I don't even know they have it in the Microsoft store

**Comment by bhack** [comment]
Mhh.. Cause if It was the Microsoft one it Is sandboxed: https://github.com/tensorflow/tensorflow/issues/36111#issuecomment-614933000

You can try Is to reinstall tf-nightly in a new fresh venv https://www.tensorflow.org/install/pip#windows_1

**Comment by 8rax** [comment]
Hello, 
I had the same problem but my tensorflow was asking for the 101 DLL which is found in version 10.1. Maybe try with version the version advised here : https://www.tensorflow.org/install/gpu#windows_setup ?

**Comment by adamx97** [comment]
I have the exact same thing: tf-nightly, cudart64_110.dll on the path, yet the message is that it isn't found.
This is in a venv, if that matters.
```python
import tensorflow as tf
2020-09-21 18:02:24.223511: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2020-09-21 18:02:24.223673: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
tf.__version__
'2.4.0-dev20200917'
```
Path includes C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin
```
(.venv) C:\>dir "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\cudart64_110.dll"
 Volume in drive C is Windows
 Volume Serial Number is xxxxxxxxx

 Directory of C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin

07/23/2020  06:59 AM           401,408 cudart64_110.dll
```

**Comment by bhack** [comment]
Can you try to print from python `os.environ["PATH"]` and check that you see the correct cuda paths?

**Comment by adamx97** [comment]
```python
>>> os.environ["PATH"]
'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.0\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.0\\extras\\CPUTI\\lib64;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.0\\include;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.0\\libnvvp;C:\\Program Files (x86)\\RSA SecurID Token Common;C:\\Program Files\\RSA SecurID Token Common;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\wbin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\CrashPlan\\jre\\bin\\server\\;C:\\Program Files\\CrashPlan\\jre\\bin\\;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Program Files (x86)\\PuTTY\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\Git\\cmd;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2020.1.2\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Program Files\\RSA SecurID Token Common\\;'
```

**Comment by adamx97** [comment]
I should mention, I have the cudnn64_8.dll which seems to correspond to the cudart64_110.dll.  The docs only mention the cudnn64_7.dll

**Comment by bhack** [comment]
@adamx97 It is ok for nightly.

**Comment by amahendrakar** [comment]
@CalendulaED,
Any updates regarding? Is this still an issue? Thanks!

**Comment by CalendulaED** [comment]
> @CalendulaED,
> Any updates regarding? Is this still an issue? Thanks!

I believe I still have the problem of missing 110
![image](https://user-images.githubusercontent.com/68514251/94458263-b68d7700-0183-11eb-944b-cbf2346bbe84.png)

**Comment by CalendulaED** [comment]
And I do have 110 in the folder I believe
![image](https://user-images.githubusercontent.com/68514251/94458463-fa807c00-0183-11eb-82d9-04d134f7785e.png)

**Comment by bhack** [comment]
@CalendulaED can you try with a fresh venv https://www.tensorflow.org/install/pip#2.-create-a-virtual-environment-recommended?

**Comment by CalendulaED** [comment]
> @CalendulaED can you try with a fresh `venv` https://www.tensorflow.org/install/pip#2.-create-a-virtual-environment-recommended?

I try the venv, but It give me an error about environment error 
![image](https://user-images.githubusercontent.com/68514251/94460475-ca86a800-0186-11eb-8cda-af80ee68a6f5.png)

**Comment by CalendulaED** [comment]
![image](https://user-images.githubusercontent.com/68514251/94461223-d9ba2580-0187-11eb-8cbe-4a3096697e88.png)
![image](https://user-images.githubusercontent.com/68514251/94461243-dfb00680-0187-11eb-9349-abf8f146fd41.png)
![image](https://user-images.githubusercontent.com/68514251/94461251-e3438d80-0187-11eb-877a-44baebfd8224.png)
After I add --user to it, I belive it still not working

**Comment by bhack** [comment]
The idea was:
 > deactivate  # don't exit until you're done using TensorFlow` 

so to install and try to use TF inside the venv.

**Comment by CalendulaED** [comment]
![image](https://user-images.githubusercontent.com/68514251/94466288-38cf6880-018f-11eb-8c6e-0cf6643ee9cb.png)
I think this is inside the venv, but I still show the same errors

**Comment by bhack** [comment]
Now yes.
Can you try to see if you can access to `cudart64_110.dll`
```
import os
os.access('<fill_with_your_path>cudart64_110.dll', os.R_OK)
```

**Comment by CalendulaED** [comment]
I think import is not supported here
![image](https://user-images.githubusercontent.com/68514251/94469065-7209d780-0193-11eb-835d-c1df00635210.png)

**Comment by bhack** [comment]
It is python code

**Comment by bhack** [comment]
Also <fill_with_your_path> it means "you need to manually change it with your real cudart64 path"

**Comment by CalendulaED** [comment]
It says false
![image](https://user-images.githubusercontent.com/68514251/94470837-36244180-0196-11eb-8538-86f02538823d.png)

**Comment by bhack** [comment]
Ok so with false it seems that you have read permission problem with that folder. Are you sure that you have not installed python from the Windows store? Like in https://installpython3.com/windows/

**Comment by CalendulaED** [comment]
I believe I download it from **https://www.python.org/downloads/**
should I download this again?

**Comment by bhack** [comment]
Can you try from command line to run `type <fill_with_your_path>cudart64_110.dll`?

**Comment by CalendulaED** [comment]
I am sorry, it said True, it misses a symbol in the line
![image](https://user-images.githubusercontent.com/68514251/94473414-2ad31500-019a-11eb-848c-96c5877de246.png)

**Comment by bhack** [comment]
Ok can you run `python -c 'import tensorflow as tf; print(tf.__version__)'`

**Comment by CalendulaED** [comment]
I can't directly type it, so I run it in python, I think it said 2.4.0
![image](https://user-images.githubusercontent.com/68514251/94474134-3541de80-019b-11eb-8440-130a06446b94.png)

**Comment by bhack** [comment]
Ok.. the last thing.
Inside the venv can you execute:
```
import os
print(os.environ['PATH'])
```

**Comment by CalendulaED** [comment]
Yes.
![image](https://user-images.githubusercontent.com/68514251/94482238-f7e34e00-01a6-11eb-88c9-1e69d3c76dae.png)

**Comment by bhack** [comment]
The path seems ok to find cudart. Yes you try to be sure to install and use python 64bit from https://www.python.org/downloads/

**Comment by CalendulaED** [comment]
![image](https://user-images.githubusercontent.com/68514251/94486076-e309b900-01ac-11eb-94ef-8283962be9fc.png)
I reinstall the python, but I don't think it makes a difference.
![image](https://user-images.githubusercontent.com/68514251/94486201-0d5b7680-01ad-11eb-9bec-5a2540b62dda.png)

**Comment by bhack** [comment]
Can you execute:
```python
import sys
print(sys.executable)
```

**Comment by CalendulaED** [comment]
Yes,
![image](https://user-images.githubusercontent.com/68514251/94487092-65df4380-01ae-11eb-87bb-cf989496b25e.png)

**Comment by bhack** [comment]
Please re-run outside the venv

**Comment by CalendulaED** [comment]
![image](https://user-images.githubusercontent.com/68514251/94487722-6f1ce000-01af-11eb-9ede-716ef0417bcd.png)
yeh, it saids Microsoft windows apps?
But I never download it from there, and I just download it from the official web site, why this happens...

**Comment by CalendulaED** [comment]
I delete it from the Microsoft windows app and reinstall the one on the official website, but whenever I type python, it will automatically open the Microsoft store,,

**Comment by bhack** [comment]
I understand but we cannot support you at this level cause it is not a Tensorflow bug. 
You can try to find support for python installation at: https://www.python.org/about/help/

Or you can use Tensorflow with our Docker images https://www.tensorflow.org/install/docker

**Comment by CalendulaED** [comment]
I think I have the correct path now
![image](https://user-images.githubusercontent.com/68514251/94489999-8fe73480-01b3-11eb-8bfd-18d399dab17a.png)

**Comment by CalendulaED** [comment]
I think it give another different error when I tried to import tensorflow
![image](https://user-images.githubusercontent.com/68514251/94490135-d9378400-01b3-11eb-9de6-b11fda3bac06.png)

**Comment by bhack** [comment]
Prepare again venv with this version and install tensorflow with pip inside the venv

**Comment by CalendulaED** [comment]
Inside the venv it also shows the same error 
![image](https://user-images.githubusercontent.com/68514251/94490537-70044080-01b4-11eb-837c-ea479f9bfbe6.png)

**Comment by bhack** [comment]
You need  `pip install --upgrade tensorflow` inside the venv

**Comment by CalendulaED** [comment]
after install it, it shows missing 101
![image](https://user-images.githubusercontent.com/68514251/94492342-1867d400-01b8-11eb-886c-3daf09578ea0.png)

**Comment by bhack** [comment]
if you are still with CUDA 11 you need nightly `pip install tf-nightly`

**Comment by CalendulaED** [comment]
O, I think I can import tensorflow, but why do I need to run it in venv? So I can't run it without venv?

**Comment by CalendulaED** [comment]
When I tried to import tensorflow outside the venv, it will missing module, and I tried to upgrade pip, it shows the error
![image](https://user-images.githubusercontent.com/68514251/94493564-f0c63b00-01ba-11eb-8099-57549e853145.png)

**Comment by bhack** [comment]
This are windows permission issues of your shell. Please ask support to stackoverflow or other python support channels
https://stackoverflow.com/questions/51115744/access-is-denied-when-trying-to-pip-install-a-package-on-windows/55100713

**Comment by CalendulaED** [comment]
> This are windows permission issues of your shell. Please ask support to stackoverflow or other python support channels
> https://stackoverflow.com/questions/51115744/access-is-denied-when-trying-to-pip-install-a-package-on-windows/55100713

Thank you, I think I can run it without the venv, but what is the difference?

**Comment by bhack** [comment]
Nothing specific is to maintain a clean separate environment.

**Comment by CalendulaED** [comment]
> Nothing specific is to maintain a clean separate environment.

Ok, thank you so much!!!! really help me a lots

**Comment by caxelrud** [comment]
I have to renamed these files in the bin folder to make it work:
cudart64_101.dll -> cudart64_110.dll
cusparse64_10.dll->cusparse64_11.dll
cudnn64_7.dll->cudnn64_8.dll
cublas64_10.dll->cublas64_11.dll

**Comment by caxelrud** [comment]
The reality is that each version of Tensorflow uses an specific Cuda and Cudnn. In my case, for TF 2.3 it is Cuda 11.0. Installing this one solves the problem.

**Comment by magpayang** [comment]
> I have to renamed these files in the bin folder to make it work:
> cudart64_101.dll -> cudart64_110.dll
> cusparse64_10.dll->cusparse64_11.dll
> cudnn64_7.dll->cudnn64_8.dll
> cublas64_10.dll->cublas64_11.dll

also encountered cusolver64_10.dll not found. when I checked the bin folder, it is named to cusolver64_11.dll

**Comment by aparico** [comment]
I was able to solve this by following the software requirements here: https://www.tensorflow.org/install/gpu#software_requirements

Here's my system:
NVIDIA Driver 460.89
CUDA 11.0.3
CuDNN 8.0.5.39
Python 3.7.2

I also made sure that the CUDA was compatible with the CuDNN version by checking it here: https://developer.nvidia.com/rdp/cudnn-download

![image](https://user-images.githubusercontent.com/47623790/102877187-b30b4280-4489-11eb-9db0-5d5f75667511.png)

Finally, don't forget to set the installation directories to the PATH environment variable. https://www.tensorflow.org/install/gpu#windows_setup

**Comment by vanc** [comment]
The key is to install Python from python.org. All versions from Microsoft App Store don't work. Tried both 3.7, 3.8. Once installed the official version 3.8.7 downloaded from python.org, everything is fine now.

This is my current system:

NVIDIA Driver 460.89
CUDA 11.0.3
CuDNN 8.0.5.39
Python 3.8.7 (from python.org)


I also tried with CUDA 11.1.1. It also worked after renaming cusolver64_11.dll to cusolver64_10.dll. It's a known issue tracked in issue #44291.

**Comment by GPlaying** [comment]
I got a way to solve this problem, you can download cudart64_101.dll to C:\Users\hp and C:\Windows\System32  from 
 https://www.ijinshan.com/filerepair/cudart64_101.dll.shtml.

**Comment by Rob192** [comment]
Hello, 
Thanks @aparico for the tip ! It did work with this configuration and `pip install tensorflow`. However, the software versions in the software requirements section of the https://www.tensorflow.org/install/gpu#software_requirements are not correct as they recommand CUDA 10.1 and CuDNN 7.6 and the install works with CUDA 11.0 and CuDNN 8.0. 
Maybe this page needs update ?

**Comment by Aporbel** [comment]
**CUDA 11.2
cuDNN 8.1
tensorflow 2.5**
in virtual env write `"where cudart64_110.dll"` and get path.
when taping  `"import tensorflow as tf"` get:
`"W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found"`

**Comment by OmarJay1** [comment]
Thank you for posting the os.add_dll_directory tip.  I believe the behavior is by design for newer versions of Python on Windows.  The Windows Path environment variable no longer works.  That's what I'm guessing is going on.

https://docs.python.org/3/whatsnew/3.8.html#bpo-36085-whatsnew

>  Specifically, PATH and the current working directory are no longer used, and modifications to these will no longer have any effect on normal DLL resolution.

**Comment by nuramzan** [comment]
I do an easy way to deal with this problem like below :
1. Install anaconda with python 3.8.8
2. Install tensor flow : pip install tensorflow -> got an error like above 
"W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found"
3. Install package -> pip install tf-nightly
4. Install the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017, and 2019 -> https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0
5. Verify the system has a CUDA-capable GPU -> http://developer.nvidia.com/cuda-gpus. 
![image](https://user-images.githubusercontent.com/84208988/133694728-c11fa576-9a93-4aa3-bc41-7292960d33e8.png)
6. Using Conda to Install the CUDA Software (https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/) -> conda install cuda -c nvidia
7. Verify the Installation of CUDA toolkit ->  nvcc -v
![image](https://user-images.githubusercontent.com/84208988/133694963-1c69d01e-9bf5-40b1-9bad-c7cc7c53a361.png)
8. import tensorflow as tf is succeed, and you are ready to implement deep learning using jupyter notebook
Hope this information is helpful....

**Comment by GrimmGringo** [comment]
I had this error, as well as:
Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found

Here's what worked for me, with Python 3.9.6 running on my Windows 10 laptop with a mobile RTX 3080.

Upgrade to the latest NVidia drivers:
-- https://www.nvidia.com/drivers

Install CUDA 11.4:
-- https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exe_local

Install cuDNN 8.2.4 for CUDA 11.4:
-- https://developer.nvidia.com/rdp/cudnn-download 
-- choose cuDNN Library for Windows (x64), extract to C:\tools so you have C:\tools\cuda\bin\cudnn64_8.dll

Update your Windows %PATH%:
  SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin;%PATH%
  SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\extras\CUPTI\lib64;%PATH%
  SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\include;%PATH%
  SET PATH=C:\tools\cuda\bin;%PATH%

Download and install the x64 C++ Redistributable:
-- https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

Download and install the x86 C++ Redistributable:
-- https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

pip install tensorflow
pip install tf-nightly

Reboot your computer.

Works perfectly now.

**Comment by lbiemans** [comment]
What fixed it for us:

import os
os.add_dll_directory("C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2/bin") # (Where v11.2 is your version)

**Comment by twinssbc** [comment]
> 

add_dll_directory also works for me. This is due to since Python 3.8, %PATH% is not longer in the dll search path.
https://docs.python.org/3/library/os.html#os.add_dll_directory

**Comment by RajdeepBorgohain** [comment]
> 

this works like a gem :)

**Comment by brechtdecock** [comment]
Hi, i have a similar issue. Made a post about it <https://stackoverflow.com/questions/73886668/tensorflow-gpu-could-not-load-dynamic-library-cudart64-110-dll>, tried some suggentions from here but things are still not working
