### ISSUE TITLE
tf.keras SparseCategoricalCrossentropy with sample_weight on TPU: Error DenseToDenseSetOperation (No registered 'DenseToDenseSetOperation)

### ISSUE THREAD

**Issue by Ankur3107** [tensorflow/tensorflow#43195]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04(Colab)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): 
- TensorFlow version (use command below): TF-2.3.0
- Colab TPU: Yes

Objective: I am trying to using SparseCategoricalCrossentropy with *sample_weight* argument on **TPU** to train Mask Language Model.

Note: Connecting TPU with tf.distribute.cluster_resolver.TPUClusterResolver()

Loss function Looks like this:

```
def masked_sparse_categorical_crossentropy(y_true, y_pred, sample_weight):

  loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(
    reduction=tf.keras.losses.Reduction.NONE,
      from_logits=True
  )
  return loss_fn(y_true, y_pred, sample_weight=sample_weight)

```

When I'm running on CPU and GPU the code runs fine. But when I am running on TPU, I am getting an error **on XLA_TPU_JIT: DenseToDenseSetOperation (No registered 'DenseToDenseSetOperation'**

```
(0) Invalid argument: {{function_node __inference_train_function_196061}} Compilation failure: Detected unsupported operations when trying to compile graph broadcast_weights_assert_broadcastable_is_valid_shape_has_valid_nonscalar_shape_true_195924_const_0[] on XLA_TPU_JIT: DenseToDenseSetOperation (No registered 'DenseToDenseSetOperation' OpKernel for XLA_TPU_JIT devices compatible with node {{node broadcast_weights/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/DenseToDenseSetOperation}}){{node broadcast_weights/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/DenseToDenseSetOperation}}
	 [[broadcast_weights/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape]]
	 [[broadcast_weights/assert_broadcastable/is_valid_shape]]
	TPU compilation failed
	 [[tpu_compile_succeeded_assert/_18335038187613310273/_6]]
	 [[tpu_compile_succeeded_assert/_18335038187613310273/_6/_265]]
  (1) Invalid argument: {{function_node __inference_train_function_196061}} Compilation failure: Detected unsupported operations when trying to compile graph broadcast_weights_assert_broadcastable_is_valid_shape_has_valid_nonscalar_shape_true_195924_const_0[] on XLA_TPU_JIT: DenseToDenseSetOperation (No registered 'DenseToDenseSetOperation' OpKernel for XLA_TPU_JIT devices compatible with node {{node broadcast_weights/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/DenseToDenseSetOperation}}){{node broadcast_weights/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/DenseToDenseSetOperation}}
	 [[broadcast_weights/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape]]
	 [[broadcast_weights/assert_broadcastable/is_valid_shape]]
	TPU compilation failed
	 [[tpu_compile_succeeded_assert/_18335038187613310273/_6]]
	 [[tpu_compile_succeeded_assert/_18335038187613310273/_6/_237]]
  (2) Invalid argument: {{function_node __inference_train_function_196061}} Compilation failure: Detected unsupported operations when trying to compile graph broadcast_weights_assert_broadcastable_is_valid_shape_has_valid_nonscalar_shape_true_195924_const_0[] on XLA_TPU_JIT: DenseToDenseSetOperation (No registered 'DenseToDenseSetOperation' OpKernel for XLA_TPU_JIT devices compatible with node {{node broadcast_weights/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/DenseToDenseSetOperation}}){{node broadcast_weights/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/DenseToDenseSetOperation}}
	 [[broadcast_weights/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape]]
	 [[broadcast_weights/assert_broadcastable/is_valid_shape]]
	TPU compilation failed
	 [[tpu_compile_succeeded_assert/_18335038187613310273/_6]]
	 [[tpu_compile_succeeded_assert/_18335038187613310273/_6/_251]]
  (3) Invalid argument: {{function_node __inference_train_function_196061}} Compilation failure: Detected unsupported operations when trying to compile graph broadcast_weights_assert_broa ... [truncated]
```

Please help me to resolve this.

Regards,
Ankur

**Comment by Saduf2019** [comment]
@Ankur3107 
I ran the code on colab tf 2.3 and nighly TPU and do not face any error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/22f0831140dbd35a13137b2df06961ec/untitled410.ipynb).
Is the code provided complete to replicate issue reported or please share complete code or colab link with error reported.

**Comment by Ankur3107** [comment]
@Saduf2019 
Thank you for your immediate reply. My complete code with an error is on https://colab.research.google.com/drive/1HYASbm7hqrL-bYZxXE7FPiWNNeOon48z?usp=sharing . 
Please find the link.

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/fb39c12e4c56d1b18f7ff894935d8a89/untitled413.ipynb)

**Comment by kechan** [comment]
I also hit the same issue. My model has 2 outputs and each has its own sample_weights. I am using the sample_weights as masks (i.e. they are 0 or 1). The setup ran fine on GPU. 

Does it look like there's a workaround?

**Comment by nikitamaia** [comment]
Seems that class weights are not supported with TPUs this way. I am linking to two Kaggle threads that could help with finding a workaround. 
[Flower Classification with TPUs](https://www.kaggle.com/c/flower-classification-with-tpus/discussion/130272)
[ALASKA2 Image Steganalysis](https://www.kaggle.com/c/alaska2-image-steganalysis/discussion/149689)

**Comment by rxsang** [comment]
It may be related to an issue @tf-marissaw is working on.

Meanwhile, can you check if the problem goes away if you set `drop_remainder=True` when calling `dataset.batch`?

**Comment by tf-marissaw** [comment]
I have merged a [fix](https://github.com/tensorflow/tensorflow/commit/e0d555fd3270570b8e7e143eba6017f7ff9ba987) into TensorFlow nightly and it should appear in the TensorFlow 2.5 release. 

Can you try running your model with TF nightly to see if the fix resolved this issue for you?

**Comment by rmothukuru** [comment]
@tf-marissaw,
I ran the above model with `Tensorflow Nightly (2.5.0-dev20201211)` and it is resulting in the error, 

`NotFoundError: 'ComputeBatchSize' is neither a type of a primitive operation nor a name of a function registered in binary running on n-dda18766-w-0. Make sure the operation or function is registered in the binary running in this process.`

Please find the [Gist](https://colab.research.google.com/gist/rmothukuru/742e79d8ef58dd469c273324c8997938/untitled413.ipynb#scrollTo=I6mSleQBK1oh). Thanks!

**Comment by sachinprasadhs** [comment]
I'm able to run your code in Tensorflow 2.7 and the latest transformers version without any error. 
[Here](https://colab.research.google.com/gist/sachinprasadhs/8c76f9e7d7293dcf6657d6627c984ee6/untitled413.ipynb) is the gist for reference.
Feel free to reopen the issue if you still face an error. Thanks!
