### ISSUE TITLE
Tensorflow hub USE model issue

### ISSUE THREAD

**Issue by jaytimbadia** [tensorflow/tensorflow#43190]
This is worse. What documentation they have is also failing? Tensorflow, please help.

import tensorflow as tf
import tensorflow_hub as hub

# Create graph and finalize (finalizing optional but recommended).
g = tf.Graph()
with g.as_default():
  # We will be feeding 1D tensors of text into the graph.
  text_input = tf.placeholder(dtype=tf.string, shape=[None])
  embed = hub.Module("use_model")
  embedded_text = embed(text_input)
  init_op = tf.group([tf.global_variables_initializer(), tf.tables_initializer()])
g.finalize()

# Create session and initialize.
session = tf.Session(graph=g)
session.run(init_op)

result = session.run(embedded_text, feed_dict={text_input: ["Hello world"]})
print(result.shape)

2020-09-13 19:57:18.597868: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-09-13 19:57:18.605416: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:From C:\Users\jay.timbadia\black\lib\site-packages\tensorflow_hub\native_module.py:55: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From C:\Users\jay.timbadia\black\lib\site-packages\tensorflow_hub\saved_model_module.py:44: The name tf.saved_model.constants.LEGACY_INIT_OP_KEY is deprecated. Please use tf.compat.v1.saved_model.constants.LEGACY_INIT_OP_KEY instead.

WARNING:tensorflow:From C:\Users\jay.timbadia\black\lib\site-packages\tensorflow_hub\saved_model_module.py:45: The name tf.saved_model.constants.MAIN_OP_KEY is deprecated. Please use tf.compat.v1.saved_model.constants.MAIN_OP_KEY instead.

WARNING:tensorflow:From endpoints.py:33: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From C:\Users\jay.timbadia\black\lib\site-packages\tensorflow_hub\module.py:143: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From C:\Users\jay.timbadia\black\lib\site-packages\tensorflow_hub\resolver.py:458: The name tf.gfile.Exists is deprecated. Please use tf.io.gfile.exists instead.

WARNING:tensorflow:From C:\Users\jay.timbadia\black\lib\site-packages\tensorflow_hub\native_module.py:92: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.

WARNING:tensorflow:From C:\Users\jay.timbadia\black\lib\site-packages\tensorflow_hub\saved_model_lib.py:80: The name tf.saved_model.constants.SAVED_MODEL_FILENAME_PB is deprecated. Please use tf.saved_model.SAVED_MODEL_FILENAME_PB instead.

WARNING:tensorflow:From C:\Users\jay.timbadia\black\lib\site-packages\tensorflow_hub\saved_model_lib.py:221: The name tf.saved_model.constants.ASSETS_KEY is deprecated. Please use tf.saved_model.ASSETS_KEY instead.

WARNING:tensorflow:From C:\Users\jay.timbadia\black\lib\site-packages\tensorflow_hub\saved_model_lib.py:55: The name tf.saved_model.constants.VARIABLES_DIRECTORY is deprecated. Please use tf.saved_model.VARIABLES_DIRECTORY instead.

WARNING:tensorflow:From C:\Users\jay.timbadia\black\lib\site-packages\tensorflow_hub\saved_model_lib.py:56: The name tf.saved_model.constants.VARIABLES_FILENAME is deprecated. Please use tf.saved_model.VARIABLES_FILENAME instead.

Traceback (most recent call last):
  File "endpoints.py", line 34, in <module>
    embed = hub.Module("use_model")
  File "C:\Users\jay.timbadia\black\lib\site-packages\tensorflow_hub\module.py", line 144, in __init__
    self._spec = as_module_spec(spec)
  File "C:\Users\jay.timbadia\black\lib\site-packages\tensorflow_hub\module.py", line 33, in as_module_spec
    return load_module_spec(spec)
  File "C:\Users\jay.timbadia\black\lib\site-packages\tensorflow_hub\module.py", line 58, in load_module_spec
    return registry.loader(path)
  File "C:\Users\jay.timbadia\black\lib\site-packages\tensorflow_hub\registry.py", line 42, in __call__
    return impl(*args, **kwargs)
  File "C:\Users\jay.timbadia\black\lib\site-packages\tensorflow_hub\native_module.py", line 115, in __call__
    return _ModuleSpec(saved_model_handler, checkpoint_filename)
  File "C:\Users\jay.timbadia\black\lib\site-packages\tensorflow_hub\native_module.py", line 296, in __init__
    saved_model_handler, _SUPPORTED_COLLECTIONS)
  File "C:\Users\jay.timbadia\black\lib\site-packages\tensorflow_hub\native_module.py", line 708, in check_collections_are_supported
    " as appropriate." % list(unsupported))
ValueError: Unsupported collections in graph: ['saved_model_main_op']
Use hub.create_module_spec(..., drop_collections=[...]) as appropriate.

**Comment by bhack** [comment]
Please fill the ISSUE template.
Can you share a very, very minimal but runnable standalone example or colab to reproduce this?

**Comment by jaytimbadia** [comment]
This is the minimal application code @bhack 
I have tried with both version of tensorflow, still giving same issue.

import tensorflow_hub as hub
import tensorflow as tf

g = tf.Graph()
with g.as_default():

  text_input = tf.placeholder(dtype=tf.string, shape=[None])
  embed = hub.Module("use_model")
  embedded_text = embed(text_input)
  init_op = tf.group([tf.global_variables_initializer(), tf.tables_initializer()])
g.finalize()


session = tf.Session(graph=g)
session.run(init_op)

result = session.run(embedded_text, feed_dict={text_input: ["Hello world"]})
print(result.shape)



Error:
Issues is when hub.Module runs, 
I have downloaded https://tfhub.dev/google/universal-sentence-encoder-large/5 and extracted it in use_model folder.

so hub.Module('use_model') should load it, but giving ValueError mentioned above.

**Comment by ravikyram** [comment]
@jaytimbadia 

This issue is more suitable for TensorFlow Hub repo. Please post it on hub repo from [here.](https://github.com/tensorflow/hub/issues) Thanks!

**Comment by jaytimbadia** [comment]
I have raised a new issue at hub but will take time again, but @bhack might solve this issue, so will close this one as soon as I get something from him. Thanks.

**Comment by arnoegw** [comment]
https://tfhub.dev/google/universal-sentence-encoder-large/5 is a [TF2 SavedModel](https://www.tensorflow.org/hub/tf2_saved_model) and cannot be loaded with the `hub.Module` API. Please follow the usage instructions on the model documentation page.

**Comment by arnoegw** [comment]
You'll also need to update your version of tensorflow_hub (and maybe even tensorflow). The error message reads as if you're using 0.2; current is 0.9.

**Comment by jaytimbadia** [comment]
Ok, so do they have to be loaded using URL in hub.load?
If we need to load it using URL, why they have provided download option?
I mean how to load a folder downloaded model?

Also I tried using both version of hub 0.9 as well? gave same error.

**Comment by jaytimbadia** [comment]
I have downloaded the model, and want to load it from there?> How should I do that?

**Comment by bhack** [comment]
You can see the logic at https://www.tensorflow.org/hub/tf2_saved_model?hl=en#using_a_savedmodel_in_low-level_tensorflow
