### ISSUE TITLE
tf.keras.callbacks.TensorBoard histogram summary breaks on tf.bool layer weights

### ISSUE THREAD

**Issue by unsatcore** [tensorflow/tensorflow#43200]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): NixOS 20.03 (irrelevant, as tensorflow is installed over pip)
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.3.0-rc2-23-gb36436b087 2.3.0 (applies to HEAD as well)
- Python version: 3.7.7
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
Tensorboard callback crashes with InvalidArgumentError in an attempt to save a histogram for tf.bool layer variable.

**Describe the expected behavior**
The most simple fix would be to skip over non-trainable weights / not-supported types in [_log_weights](https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/python/keras/callbacks.py#L2227).

**Standalone code to reproduce the issue**

```
import tensorflow as tf
import tensorflow_addons as tfa
import numpy as np

themodel = tf.keras.Sequential([
    tfa.layers.WeightNormalization(tf.keras.layers.Dense(1)) # breaks due to tf.bool [_initialzed](https://github.com/tensorflow/addons/blob/v0.11.2/tensorflow_addons/layers/wrappers.py#L105) layer weight
    #tf.keras.layers.Dense(1) # works fine
])

batch_size=1
x = np.zeros([batch_size, 10])
y = np.zeros([batch_size, 1])

themodel.compile(optimizer='sgd', loss='binary_crossentropy')
themodel.fit(x, y, batch_size=batch_size, epochs=1, callbacks=[tf.keras.callbacks.TensorBoard(log_dir='/tmp',histogram_freq=1,update_freq='epoch')])

```

**Other info / logs**

```
  File ".../.venv/lib/python3.7
/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute              
    inputs, attrs, num_outputs)                                                            tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of bool is
 not in the list of allowed values: float, double, int32, uint8, int16, int8, int64, bfloat
16, uint16, half, uint32, uint64
        ; NodeDef: {{node WriteHistogramSummary}}; Op<name=WriteHistogramSummary; signature
=writer:resource, step:int64, tag:string, values:T -> ; attr=T:type,default=DT_FLOAT,allowe
d=[DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, DT_INT8, DT_INT64, DT_BFLOAT16, DT_UI
NT16, DT_HALF, DT_UINT32, DT_UINT64]; is_stateful=true> [Op:WriteHistogramSummary]
```

**Comment by bhack** [comment]
Can you close this and open a ticket in https://github.com/tensorflow/addons

**Comment by unsatcore** [comment]
To be honest, I don't think this has anything to do with tf addons.
I've just used WeightNormalization as a practical example of layer having bool weights.
The root cause is Tensorboard callback I believe.

**Comment by bhack** [comment]
I think that there two different issues:
-  If your case is specific to `WeightNormalization` we could try to workaround in TF-addons.
- Instead if you are interested in generic tf.bool then is a known constrain:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/compat/ops_history_v2/WriteHistogramSummary.pbtxt

**Comment by unsatcore** [comment]
Neither

The point is TensorBoard callback crashes where it could actually do something more reasonable.
Instead of sending unsupported type into summary writer it could just skip over or cast to tf.int8 or...

**Comment by unsatcore** [comment]
To clarify, I'm thinking of something like this
```
def _log_weights(self, epoch):
    """Logs the weights of the Model to TensorBoard."""
    with self._train_writer.as_default():
      with summary_ops_v2.always_record_summaries():
        for layer in self.model.layers:
          for weight in layer.weights:
--------------
            # either (trivial, but may break stuff)
            if not weight.trainable:
              <perhaps emit a warning>
              continue

            # or (more convoluted, but can't break anything as it is broken anyways)
            if weight.dtype not in <supported types>:
              <perhaps emit a warning>
              continue
--------------
            weight_name = weight.name.replace(':', '_')
            summary_ops_v2.histogram(weight_name, weight, step=epoch)
            if self.write_images:
              self._log_weight_as_image(weight, weight_name, epoch)
        self._train_writer.flush()
```

**Comment by bhack** [comment]
Ok you can  try to propose this extra condition to `_log_weights` with a PR 
/cc @dnguyen28061  @annarev (for c++) @omalleyt12 (for python)

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/0072c1bae1cf5704f47ef1de10518399/43200.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/c31bc03e5a46953f4194581a104b8fa7/43200-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by annarev** [comment]
I am not really familiar with WriteHistogramSummary op. Adding +@alextp who might know more about that op.

**Comment by bhack** [comment]
@annarev I've seen that you have recently review some change in the underline c++ `summary` ops https://github.com/tensorflow/tensorflow/pull/41209. 
The mention was just to know if we have any interest in `bool` `dtype`.

**Comment by alextp** [comment]
@manivaradarajan can you take a look at this issue?

**Comment by unsatcore** [comment]
> you can try to propose this extra condition to `_log_weights` with a PR
Could give it a try. Any pointers re which of the proposed fixes would be preferred?

**Comment by manivaradarajan** [comment]
cc: @omalleyt12 

@unsatcore Thank you for considering fixing this. I suggest starting with your second option -- as you state, it should be innocuous and can only help. Once that's through, we can also look at pursuing the first one, though I think it will be harder to get right.

**Comment by sachinprasadhs** [comment]
This is working fine without breaking in `Tensorflow 2.7` and `Tensorflow Addons 0.15.0 `version, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/720d071e3b6950bb79d6d8a97effb7aa/43200.ipynb) for reference. 
Feel free to  reopen the issue if you still face an issue. Thanks!
