### ISSUE TITLE
micro speech example not working with STM32F769

### ISSUE THREAD

**Issue by lucalazzaroni** [tensorflow/tensorflow#43201]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Source
- Tensorflow version (commit SHA if source): f2c9a930a3f9f8dc0b7904f1d490b2665979d768
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Mbed OS (STM32F769)

**Describe the problem**
I'm trying to build the micro_speech application for STM32F769, following the readme file (which refers instead to STM32F746), but each iteration of the program has the same final scores for each word possible: `[64 64 64 64]`, so the `is_new_command` variable remains always false and there's no prediction.

**Please provide the exact sequence of commands/steps when you ran into the problem**
I followed the same identical steps listed on the readme, but changing the target:
`make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mbed TAGS="CMSIS disco_f769ni" generate_micro_speech_mbed_project`

`tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4/prj/micro_speech/mbed`

`mbed config root .`

`mbed deploy`

`python -c 'import fileinput, glob;
for filename in glob.glob("mbed-os/tools/profiles/*.json"):
  for line in fileinput.input(filename, inplace=True):
    print line.replace("\"-std=gnu++98\"","\"-std=c++11\", \"-fpermissive\"")'`

`mbed compile -m DISCO_F769NI -t GCC_ARM`

In order to compile fine I also had to:
- Modify `tensorflow/lite/micro/examples/micro_speech/CMSIS/Makefile.inc` as explained [here](https://github.com/tensorflow/tensorflow/pull/36444/files)
- Manually copy `arm_math_f16.h` inside `tensorflow\lite\micro\tools\make\gen\mbed_cortex-m4\prj\micro_speech\mbed\third_party\cmsis\CMSIS\DSP\Include` since it wasn't there 
- Add `BSP_DISCO_F769NI` and `LCD_DISCO_F769NI`

The last thing I tried was following the steps explained [here](https://github.com/tensorflow/tensorflow/issues/42918), then use the cmsis-nn flag, but with my board the proposed solution seems not to work.

Thanks in advance for your help and suggestions.

**Comment by lucalazzaroni** [comment]
I think a possible problem: there is no dedicated `audio_provider.cc` file for the STM32F769 board, and the standard one doesn't work. Can anyone confirm me that this is the problem? Also, if there were solutions to this class' implementation for my board they would be really appreciated.

**Comment by jenselofsson** [comment]
Could you try running the micro_speech_test in the same way and see if that passes or fails, with the cmsis-nn tag and the fix in #43110?

Simply swap out **generate_micro_speech_mbed_project** for **generate_micro_speech_test_mbed_project** in the make-command.

**Comment by lucalazzaroni** [comment]
@jenselofsson  I tried your suggestion and the test passes, here is the result:

```
!b^WÍ ëÍt"Õe¢½ X+¹µ•¹Ñ¹ To avoid this loss, please make sure the tensor_arena is 16 bytes aligned.
Ran successfully

1/1 tests passed
~~~ALL TESTS PASSED~~~

```

**Comment by jenselofsson** [comment]
I think you're correct regarding the audio_provider.cc.

I'm using the DISCO F746NG board, and I'm seeing the same result (same score in every category) when I swap out the disco_f746ng/audio_provider.cc for the default one.

While if I use the audio provider for the disco_f746ng the scores are different for the different categories (ie. as expected).

I also got the same result when using the reference kernels.

**Comment by lucalazzaroni** [comment]
Ok, thank you so much for the check!
It seems that the only option I have is to create my own audio provider for the DISCO F769NI.

**Comment by lucalazzaroni** [comment]
I tried to recreate the `audio_provider.cc` for DISCO_F769NI following the [demo ](https://os.mbed.com/teams/ST/code/DISCO-F769NI_AUDIO_demo//file/db1aee306f50/main.cpp/)on the mbed site. Here is the code I wrote:
```
#include "tensorflow/lite/micro/examples/micro_speech/audio_provider.h"
#include "mbed.h"
#include "stm32f769i_discovery_audio.h"
#include "stm32f769i_discovery_sdram.h"
#include "tensorflow/lite/micro/examples/micro_speech/micro_features/micro_model_settings.h"

namespace {

  bool g_is_audio_initialized = false;
  constexpr int kAudioCaptureBufferSize = kAudioSampleFrequency * 0.5;
  int16_t g_audio_capture_buffer[kAudioCaptureBufferSize];
  int16_t g_audio_output_buffer[kMaxAudioSampleSize];
  int32_t g_latest_audio_timestamp = 0;

  uint8_t audioRecorder = BSP_AUDIO_IN_Init(BSP_AUDIO_FREQUENCY_44K, DEFAULT_AUDIO_IN_BIT_RESOLUTION, 2 * DEFAULT_AUDIO_IN_CHANNEL_NBR);
  uint8_t sdramState = BSP_SDRAM_Init();

  typedef enum {
    BUFFER_OFFSET_NONE = 0,
    BUFFER_OFFSET_HALF = 1,
    BUFFER_OFFSET_FULL = 2,
  } BUFFER_StateTypeDef;

  #define SCRATCH_BUFF_SIZE  1024
  #define RECORD_BUFFER_SIZE  4096
  #define AUDIO_BLOCK_SIZE ((uint32_t)2048)
  #define AUDIO_BUFFER_IN SDRAM_DEVICE_ADDR /* In SDRAM */
  #define AUDIO_BUFFER_OUT \
  (SDRAM_DEVICE_ADDR + (AUDIO_BLOCK_SIZE * 2)) /* In SDRAM */ 

  volatile uint32_t audio_rec_buffer_state = BUFFER_OFFSET_NONE;

  int32_t Scratch[SCRATCH_BUFF_SIZE];
 
  /* Buffer containing the PCM samples coming from the microphone */
  int16_t RecordBuffer[RECORD_BUFFER_SIZE];
  
  /* Buffer used to stream the recorded PCM samples towards the audio codec. */
  int16_t PlaybackBuffer[RECORD_BUFFER_SIZE];

  uint8_t SetSysClock_PLL_HSE_200MHz() {
  RCC_ClkInitTypeDef RCC_ClkInitStruct;
  RCC_OscInitTypeDef RCC_OscInitStruct;

  // Enable power clock
  __PWR_CLK_ENABLE();

  // Enable HSE oscillator and activate PLL with HSE as source
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON; /* External xtal on OSC_IN/OSC_OUT */

  // Warning: this configuration is for a 25 MHz xtal clock only
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLM = 25;   // VCO input clock = 1 MHz (25 MHz / 25)
  RCC_OscInitStruct.PLL.PLLN = 400;  // VCO output clock = 400 MHz (1 MHz * 400)
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;  // PLLCLK = 200 MHz (400 MHz / 2)
  RCC_OscInitStruct.PLL.PLLQ = 8;  // USB clock = 50 MHz (400 MHz / 8)

  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
    return 0;  // FAIL
  }

  // Activate the OverDrive to reach the 216 MHz Frequency
  if (HAL_PWREx_EnableOverDrive() != HAL_OK) {
    return 0;  // FAIL
  }

  // Select PLL as system clock source and configure the HCLK, PCLK1 and PCLK2
  // clocks dividers
  RCC_ClkInitStruct.ClockType = (RCC_CLOCKTYPE_SYSCLK | RCC_CLOCKTYPE_HCLK |
                                 RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2);
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;  // 200 MHz
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;         // 200 MHz
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV4;          //  50 MHz
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV2;          // 100 MHz

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_7) != HAL_OK) {
    return 0;  // FAIL
  }
  HAL_RCC_MCOConfig(RCC_MCO1, RCC_MCO1SOURCE_HSE, RCC_MCODIV_4);
  return 1;  // OK
}

  TfLiteStatus InitAudioRecording(tflite::ErrorReporter* error_reporter) {
    SetSysClock_PLL_HSE_200MHz();

    /* Initialize Audio Recorder with 4 channels to be used */
    if (audioRecorder == AUDIO_ERROR) {
        printf("BSP_AUDIO_IN_Init error\n");
    }
 
    /* Allocate scratch buffers */
    if (BSP_AUDIO_IN_AllocScratch (Scratch, SCRATCH_BUFF_SIZE) == AUDIO_ERROR) {
        printf("BSP_AUDIO_IN_AllocScratch error\n");
    }

    // // Initialize SDRAM buffers.
    // memset((uint16_t*)AUDIO_BUFFER_IN, 0, AUDIO_BLOCK_SIZE * 2);
    // memset((uint16_t*)AUDIO_BUFFER_OUT, 0, AUDIO_BLOCK_SIZE * 2);
    // audio_rec_buffer_state = BUFFER_OFFSET_NONE;

    /* Start Recording */
    if (BSP_AUDIO_IN_Record((uint16_t*)&RecordBuffer[0], RECORD_BUFFER_SIZE) == AUDIO_ERROR) {
        printf("BSP_AUDIO_IN_Record error\n");
    }
    uint8_t ChannelNumber = BSP_AUDIO_IN_GetChannelNumber();
 
    audio_rec_buffer_state = BUFFER_OFFSET_NONE;

    return kTfLiteOk;
  }

  void CaptureSamples(const int16_t* sample_data) {
    const int sample_size = AUDIO_BLOCK_SIZE / (sizeof(int16_t) * 2);
    const int32_t time_in_ms =
      g_latest_audio_timestamp + (sample_size / (kAudioSampleFrequency / 1000));
    const int32_t start_sample_offset =
      g_latest_audio_timestamp * (kAudioSampleFrequency / 1000);

    for (int i = 0; i < sample_size; ++i) {
    const int capture_index =
        (start_sample_offset + i) % kAudioCaptureBufferSize;
    g_audio_capture_buffer[capture_index] =
        (sample_data[(i * 2) + 0] / 2) + (sample_data[(i * 2) + 1] / 2);
    }
    // This is how we let the outside world know that new audio data has arrived.
    g_latest_audio_timestamp = time_in_ms;
  }
} // namespace

// These callbacks need to be linkable symbols, because they override weak
// default versions.
void BSP_AUDIO_IN_TransferComplete_CallBack(void) {
  audio_rec_buffer_state = BUFFER_OFFSET_FULL;
  /* Copy recorded 1st half block */
  memcpy((uint16_t*)(AUDIO_BUFFER_OUT), (uint16_t*)(AUDIO_BUFFER_IN),
         AUDIO_BLOCK_SIZE);
  CaptureSamples(reinterpret_cast<int16_t*>(AUDIO_BUFFER_IN));
  return;
}

// Another weak symbol override.
void BSP_AUDIO_IN_HalfTransfer_CallBack(void) {
  audio_rec_buffer_state = BUFFER_OFFSET_HALF;
  /* Copy recorded 2nd half block */
  memcpy((uint16_t*)(AUDIO_BUFFER_OUT + (AUDIO_BLOCK_SIZE)),
         (uint16_t*)(AUDIO_BUFFER_IN + (AUDIO_BLOCK_SIZE)), AUDIO_BLOCK_SIZE);
  CaptureSamples(
      reinterpret_cast<int16_t*>(AUDIO_BUFFER_IN + AUDIO_BLOCK_SIZE));
  return;
}

// Main entry point for getting audio data.
TfLiteStatus GetAudioSamples(tflite::ErrorReporter* error_reporter,
                             int start_ms, int duration_ms,
                             int* audio_samples_size, int16_t** audio_samples) {
  
  if (!g_is_audio_initialized) {
    TfLiteStatus init_status = InitAudioRecording(error_reporter);
    if (init_status != kTfLiteOk) {
      return init_status;
    }
    g_is_audio_initialized = true;
  }
  // This should only be called when the main thread notices that the latest
  // audio sample data timestamp has changed, so that there's new data in the
  // capture ring buffer. The ring buffer will eventually wrap around and
  // overwrite the data, but the assumption is that the main thread is checking
  // often enough and the buffer is large enough that this call will be made
  // before that happens.
  const int start_offset = start_ms * (kAudioSampleFrequency / 1000);
  const int duration_sample_count =
      duration_ms * (kAudioSampleFrequency / 1000);
  for (int i = 0; i < duration_sample_count; ++i) {
    const int capture_index = (start_offset + i) % kAudioCaptureBufferSize;
    g_audio_output_buffer[i] = g_audio_capture_buffer[capture_index];
  }

  *audio_samples_size = kMaxAudioSampleSize;
  *audio_samples = g_audio_output_buffer;
  return kTfLiteOk;
}

int32_t LatestAudioTimestamp() { return g_latest_audio_timestamp; }
```
Regarding this, the SDRAM buffers initialization and the use of `SetSysClock_PLL_HSE_200MHz()` inside of the 
 `InitAudioRecording` function, seem not to alterate the final result (I copied them from the DISCO F746NG's `audio_provider.cc`).
I tried to develope the project both with cmsis and cmsis-nn tags, but apparently the issue is not solved. The strange thing is that if I build in release mode, the final scores for each word are `[64, 64, 64, 64]`, but, if I choose the normal mode the command recognizer returns at line 88 of `recognize_commands.cc` (ie. "If there are too few results, assume the result will be unreliable and bail.") because the if statement at line 83 is satisfied. Obviously, in both cases, `is_new_command` stays false, so there's no prediction.
If anyone could help me solving this issue it would be really appreciated. Thanks in advance.

**Comment by mohantym** [comment]
Hi @lucalazzaroni !
We are checking to see whether you still need help in this issue . 
Could you test with example from [tflite-micro](https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/examples) repo and let us know.

Thank you!
