### ISSUE TITLE
Architecture of Tensorflow model Zoo 

### ISSUE THREAD

**Issue by krn-sharma** [tensorflow/tensorflow#43206]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://github.com/tensorflow/models/tree/master/official

## Description of issue:
Where i can find full architecture of all the pre-trained model of Tensorflow object detection api. And also the difference between different version. For example: Difference between SSD MobileNet V2 FPNLite 640x640 and SSD MobileNet v2 320x320???

**Comment by bhack** [comment]
Please close this this ticket and open a new one at https://github.com/tensorflow/models/ directly.
