### ISSUE TITLE
Sparse tensor error message when applying constraint to dense variable

### ISSUE THREAD

**Issue by matthias-wright** [tensorflow/tensorflow#43205]
**System information**
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from (source or binary): Conda
- TensorFlow version: I tried versions 2.2.0, 2.3.0, 1.15, and 1.14
- Python version: 3.6 and 3.8.3
- CUDA/cuDNN version: CUDA 10.1 and cuDNN 7.6 for TF 2.3.0 and 2.2.0, CUDA 10.0 and cuDNN 7.4 for TF 1.15 and 1.14
- GPU model and memory: GeForce GTX TITAN X (12 GB)

**Describe the current behavior**

I am trying to impose a constraint on a trainable variable. 
However, at some point in my pipeline, I am applying a tf.gather operation to the variable that I am constraining, which is causing a runtime error.
The error message (see below) says that a constraint function cannot be used on a sparse variable.
However, my variable is not sparse.
When I am excluding the tf.gather operation, it works without any errors.

**Describe the expected behavior**

The variable should be constrained to a specific range without any errors.

**Standalone code to reproduce the issue**

Colab: https://colab.research.google.com/drive/1Cv-ftL1E0tpC7-1sqO3AMNQ9kSto8m4_?usp=sharing#scrollTo=RY1T16oqz9yo

This is not working:
```python
import tensorflow as tf
import numpy as np

tf.compat.v1.disable_v2_behavior()

y = tf.Variable(name='y',
                initial_value=np.random.rand(5, 2) * 2,
                dtype=tf.float32,
                constraint=lambda x: tf.clip_by_value(x, clip_value_min=-1.0, clip_value_max=1.0), 
                )

yy = tf.gather(y, axis=0, indices=[0, 1, 2])
loss = tf.reduce_sum(yy)
step = tf.compat.v1.train.AdamOptimizer(learning_rate=0.1).minimize(loss=loss, var_list=[y])

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    y_, _ = sess.run(fetches=[y, step])
    print(y_)
```

This is working (just removed the tf.gather operation):
```python
import tensorflow as tf
import numpy as np

tf.compat.v1.disable_v2_behavior()

y = tf.Variable(name='y',
                initial_value=np.random.rand(5, 2) * 2,
                dtype=tf.float32,
                constraint=lambda x: tf.clip_by_value(x, clip_value_min=-1.0, clip_value_max=1.0), 
                )

loss = tf.reduce_sum(y)
step = tf.compat.v1.train.AdamOptimizer(learning_rate=0.1).minimize(loss=loss, var_list=[y])

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    y_, _ = sess.run(fetches=[y, step])
    print(y_)`
```

**Other info / logs** 
```python
RuntimeError                              Traceback (most recent call last)
<ipython-input-13-1e1802616fbe> in <module>()
loss = tf.reduce_sum(yy)
step = tf.compat.v1.train.AdamOptimizer(learning_rate=0.1).minimize(loss=loss, var_list=[y])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/optimizer.py in update_op(self, optimizer, g)
if self._v.constraint is not None:
 raise RuntimeError(
"Cannot use a constraint function on a sparse variable.")
return optimizer._resource_apply_sparse_duplicate_indices(
g.values, self._v, g.indices)
RuntimeError: Cannot use a constraint function on a sparse variable.
```

**Comment by bhack** [comment]
@matthias-wright Probably we in the same class of problems as #33755 as you can check yourself with these two lines:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/optimizer_v2/optimizer_v2.py#L640
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/array_grad.py#L588

**Comment by matthias-wright** [comment]
@bhack Thank you for the response! 
From the documentation of [tf.IndexedSlices](https://www.tensorflow.org/api_docs/python/tf/IndexedSlices): _The IndexedSlices class is used principally in the definition of gradients for operations that have sparse gradients (e.g. tf.gather)._ That means that even though the variable is dense, the gradient is sparse. That makes sense then. 
I do think that the error message is a little confusing, because the constraint is applied to the variable and not the gradient.

**Comment by ravikyram** [comment]
I tried in colab with TF 2.3, nightly versions and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/950eaf955e33b0cd3530da791ea56bcf/untitled393.ipynb). Thanks!

**Comment by gowthamkpr** [comment]
@matthias-wright Can we go ahead and close this issue as it is not bug. Thanks!

**Comment by matthias-wright** [comment]
Yes, we can close it.
