### ISSUE TITLE
tf-mlir-translate is not coming in binaries

### ISSUE THREAD

**Issue by ArunaKote** [tensorflow/tensorflow#43203]
I built mlir using : bazel build --config opt tensorflow/compiler/mlir/...

But tf-mlir-translate is not there in the tensorflow/bazel-bin/tensorflow/compiler/mlir/tensorflow/

Thank You

**Comment by amahendrakar** [comment]
@ArunaKote,
Could you please fill in the below details

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:



and also provide the exact sequence of commands / steps that you executed before running into the problem? Thanks!

**Comment by ArunaKote** [comment]
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):https://github.com/tensorflow/tensorflow.git
TensorFlow version:2.0
Python version:3.8
Installed using virtualenv? pip? conda?:pip
Bazel version (if compiling from source):3.1.0
GCC/Compiler version (if compiling from source):9.3.0
I am installing only for CPU.

Thank You

**Comment by gowthamkpr** [comment]
@ArunaKote `translate` is present in `tensorflow/tensorflow/compiler/mlir/tensorflow/` Please take a look at [here](https://github.com/tensorflow/tensorflow/tree/r2.0/tensorflow/compiler/mlir/tensorflow) in tensorflow 2.0
