### ISSUE TITLE
Question about TFLite GPU delegate

### ISSUE THREAD

**Issue by again4you** [tensorflow/tensorflow#43208]
I was trying to build TFLite GPU delegate on ARM device such as Raspberry pi 4.
After reading the guide document, I found that GPU delegate only uses Bazel build system and it only supports Android and iOS.

My question is that:
1) Is there any plan to support Makefile or CMake to build TFLite GPU delegate?

2) If I'd like to use TFLite GPU delegate on other Linux dist such as Ubuntu ARM, can I do that? If possible, how?

3) Is there any roadmap or plan when Raspberry pi 4 GPU will be a supported TFLite GPU delegate?

Thank you in advance.

**System information**
- OS Platform and Distribution: Linux dist instead of Android.
- Mobile device: Raspberry pi 4 or other ARM device.
- TensorFlow build from source
- TensorFlow version: latest

**Comment by bhack** [comment]
There was some activity in https://github.com/tensorflow/tensorflow/pull/38806 for Linux and for Cmake https://github.com/tensorflow/tensorflow/pull/36180
For raspberry 4 the last update was https://github.com/tensorflow/tensorflow/issues/27320#issuecomment-657820659. You can ask there if there is a new update.

**Comment by BenjaminWegener** [comment]
maybe a hint in the right direction
https://github.com/BenjaminWegener/tensorflow_lite_gpu_python/commit/b1fcd1b51c039fca0408eccf49cea77d3bbee2c5
https://github.com/BenjaminWegener/tensorflow_lite_gpu_python/commit/9721986c8289c3fce9642526ef7bb799ade5466e
