### ISSUE TITLE
Converter Error : for converting saved-model to tflite 

### ISSUE THREAD

**Issue by dikshantjn** [tensorflow/tensorflow#43211]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version (or github SHA if from source): 2.3.0 , also installed tf-nightly

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
# Copy and paste here the exact command
```
import tensorflow as tf

saved_model_dir = 'C:\\Users\\diksh\\Desktop\\Fine_Tuned_Model\\saved_model'

model = tf.saved_model.load(saved_model_dir)
model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY].inputs[0].set_shape([1, 256, 256, 3])
tf.saved_model.save(model, "saved_model_updated", signatures=model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY])
# Convert
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir='saved_model_updated', signature_keys=['serving_default'])
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()

## TFLite Interpreter to check input shape
interpreter = tf.lite.Interpreter(model_content=tflite_model)
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test the model on random input data.
input_shape = input_details[0]['shape']
print(input_shape)

**The output from the converter invocation**
Exception                                 Traceback (most recent call last)
~\AppData\Roaming\Python\Python37\site-packages\tensorflow\lite\python\convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    198                                                  debug_info_str,
--> 199                                                  enable_mlir_converter)
    200       return model_str

~\AppData\Roaming\Python\Python37\site-packages\tensorflow\lite\python\wrap_toco.py in wrapped_toco_convert(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
     37       debug_info_str,
---> 38       enable_mlir_converter)
     39 

Exception: <unknown>:0: error: loc("Func/StatefulPartitionedCall/input/_0"): requires all operands and results to have compatible element types
<unknown>:0: note: loc("Func/StatefulPartitionedCall/input/_0"): see current operation: %1 = "tf.Identity"(%arg0) {_class = ["loc:@Func/StatefulPartitionedCall/StatefulPartitionedCall/input/_702"], device = ""} : (tensor<1x256x256x3x!tf.quint8>) -> tensor<1x256x256x3xui8>

During handling of the above exception, another exception occurred:

ConverterError                            Traceback (most recent call last)
<ipython-input-4-b50eec57af9d> in <module>
     11 converter.optimizations = [tf.lite.Optimize.DEFAULT]
     12 converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
---> 13 tflite_model = converter.convert()
     14 
     15 ## TFLite Interpreter to check input shape

~\AppData\Roaming\Python\Python37\site-packages\tensorflow\lite\python\lite.py in convert(self)
   1074         Invalid quantization parameters.
   1075     """
-> 1076     return super(TFLiteConverterV2, self).convert()
   1077 
   1078 

~\AppData\Roaming\Python\Python37\site-packages\tensorflow\lite\python\lite.py in convert(self)
    898 
    899     return super(TFLiteFrozenGraphConverterV2,
--> 900                  self).convert(graph_def, input_tensors, output_tensors)
    901 
    902 

~\AppData\Roaming\Python\Python37\site-packages\tensorflow\lite\python\lite.py in convert(self, graph_def, input_tensors, output_tensors)
    631         input_tensors=input_tensors,
    632         output_tensors=output_tensors,
--> 633         **converter_kwargs)
    634 
    635     calibrate_and_quantize, flags = quant_mode.quantizer_flags(

~\AppData\Roaming\Python\Python37\site-packages\tensorflow\lite\python\convert.py in toco_convert_impl(input_data, input_tensors, output_tensors, enable_mlir_converter, *args, **kwargs)
    572       input_data.SerializeToString(),
    573       debug_info_str=debug_info_str,
--> 574       enable_mlir_converter=enable_mlir_converter)
    575   return data
    576 

~\AppData\Roaming\Python\Python37\site-packages\tensorflow\lite\python\convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    200       return model_str
    201     except Exception as e:
--> 202       raise ConverterError(str(e))
    203 
    204   if distutils.spawn.find_executable(_toco_from_proto_bin) is None:

ConverterError: <unknown>:0: error: loc("Func/StatefulPartitionedCall/input/_0"): requires all operands and results to have compatible element types
<unknown>:0: note: loc("Func/StatefulPartitionedCall/input/_0"): see current operation: %1 = "tf.Identity"(%arg0) {_class = ["loc:@Func/StatefulPartitionedCall/StatefulPartitionedCall/input/_702"], device = ""} : (tensor<1x256x256x3x!tf.quint8>) -> tensor<1x256x256x3xui8>

```
# Copy and paste the output here.
```

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by bhack** [comment]
Please could you share a very, very minimal but complete standalone or colab example that we could copy, past and run to reproduce your issue?

**Comment by dikshantjn** [comment]
Here is the link with the jupyter notebooks and saved model data
https://drive.google.com/drive/folders/1MCvDti2ygukqw6fGE18WpnFOSzR_AanF?usp=sharing
Im working on a team where i have been requested to convert the saved_model to a tflite.
The "FLIR_retraining.ipynb" is the file to retrain the model.
and the "TFLite_converter.ipynb" is a shorter version that I have been trying to use for the conversion.

Thank you.

**Comment by amahendrakar** [comment]
@dikshantjn,
I was able to reproduce the error with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/ced1f50c56218d3da7c401a91bb5acbc/43211.ipynb).

However, with the latest [TF-nightly](https://colab.research.google.com/gist/amahendrakar/3c9f9d7540e521fa298398a6e5538bee/43211-tf-nightly.ipynb) I was able to run the code without any issues. Please find the attached gist. Thanks!

**Comment by dikshantjn** [comment]
I'm still getting the same error:
"<unknown>:0: error: loc("Func/StatefulPartitionedCall/input/_0"): requires all operands and results to have compatible element types
<unknown>:0: note: loc("Func/StatefulPartitionedCall/input/_0"): see current operation: %1 = "tf.Identity"(%arg0) {_class = ["loc:@Func/StatefulPartitionedCall/StatefulPartitionedCall/input/_702"], device = ""} : (tensor<1x256x256x3x!tf.quint8>) -> tensor<1x256x256x3xui8>"

**Comment by dikshantjn** [comment]
@amahendrakar 
Thank you .... I was able to convert the model to tflite in colab, previously I was trying it on my windows PC
I am now trying to save it on my drive using :
tflite_file = 'Fine_Tuned_Model/head_detector.tflite'
open(tflite_file, "wb").write(tflite_model)

But it is not generating any files
Please help

**Comment by amahendrakar** [comment]
@dikshantjn,
I was able to write the `head_detector.tflite` file to disk without any issues, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/663e2e6ff73d70a4822fd6ff35b83424/43211-tf-nightly.ipynb#scrollTo=BGc4GpLOEO7J&line=1&uniqifier=1).

Could you please share the gist of the Colab notebook you are running? Thanks!

**Comment by dikshantjn** [comment]
@amahendrakar here is the colab
https://colab.research.google.com/drive/1_9l_DcyNuVV1NxU3PsmSMjWeI9nTEwNS?usp=sharing

**Comment by dikshantjn** [comment]
@amahendrakar .... with the latest version of tf-nightly, the  order of output tensors changes. If you could help me understand that and what is the meaning of each of them

**Comment by amahendrakar** [comment]
@dikshantjn,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by dhavids** [comment]
> @amahendrakar .... with the latest version of tf-nightly, the order of output tensors changes. If you could help me understand that and what is the meaning of each of them


I faced this issue too. Had to debug the shape of each output to get it to work. 

Regardless, it worked. Not with the current tf-nightly build but with the one used in the gist posted by @amahendrakar [https://colab.research.google.com/gist/amahendrakar/3c9f9d7540e521fa298398a6e5538bee/43211-tf-nightly.ipynb](here)
