### ISSUE TITLE
"Function call stack: _dist_train_step" error on tensorflow2 object detection api

### ISSUE THREAD

**Issue by mobinity-yoom** [tensorflow/tensorflow#43227]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

Every time I try to train the object detection models (any model, I tried ssd, faster rcnn, efficientdet..) by tf2 model train script (which is model_main_tf2.py), I got this error message every 1500~2000 steps.

![image](https://user-images.githubusercontent.com/70259589/93154006-87b3e180-f73d-11ea-90c7-ddc11707d7f2.png)

I ran the notebook in google colab, and I got the colab pro upgrade either. (I thought this issue might be the memory issue on GPU or TPU)

I just followed the object detection api todo ..
Anyone can help..?
I also put a link to my colab notebook too. 

https://colab.research.google.com/drive/1Xg5NKpipLTUCCyTFDYYCC_xAkPRTUyCc?usp=sharing

**Comment by Saduf2019** [comment]
@mobinity-yoom 
Please close this ticket and open a new one at https://github.com/tensorflow/models/ directly.

**Comment by A-Ayesha-Abbasi** [comment]
I also had same issue, This error occurs when VRAM on Colab become full thus program halts, So either reduce your input image size or reduce batch size. I used to resolve this issue by reducing batch size to 1 in config file, located at TensorFlow/workspace/training_demo/models/ YOUR-MODEL-NAME/pipeline.config

**Comment by Her0Mark** [comment]
> 
> 
> I also had same issue, This error occurs when VRAM on Colab become full thus program halts, So either reduce your input image size or reduce batch size. I used to resolve this issue by reducing batch size to 1 in config file, located at TensorFlow/workspace/training_demo/models/ YOUR-MODEL-NAME/pipeline.config

I also have the same issue. I modified TensorFlow/workspace/training_demo/models/ YOUR-MODEL-NAME/pipeline.config to batch_size: 1 (on line 135). Im still getting this error. Please can anyone help

**Comment by MaryamBibiRcs** [comment]
@Her0Mark I am getting the same error on google colab while I run tensorflow faster rcnn object detection api. I reduced batch size=1 but didn't passed through it. Have you solved your's?

**Comment by joy-hr** [comment]
> > I also had same issue, This error occurs when VRAM on Colab become full thus program halts, So either reduce your input image size or reduce batch size. I used to resolve this issue by reducing batch size to 1 in config file, located at TensorFlow/workspace/training_demo/models/ YOUR-MODEL-NAME/pipeline.config
> 
> I also have the same issue. I modified TensorFlow/workspace/training_demo/models/ YOUR-MODEL-NAME/pipeline.config to batch_size: 1 (on line 135). Im still getting this error. Please can anyone help
> 
> ```
>   File "C:\Users\preto\anaconda3\envs\tensorflow\lib\site-packages\object_detection\model_lib_v2.py", line 169, in _ensure_model_is_built
>     strategy.run(
>   File "C:\Users\preto\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 1259, in run
>     return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
>   File "C:\Users\preto\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 2730, in call_for_each_replica
>     return self._call_for_each_replica(fn, args, kwargs)
>   File "C:\Users\preto\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\distribute\mirrored_strategy.py", line 628, in _call_for_each_replica
>     return mirrored_run.call_for_each_replica(
>   File "C:\Users\preto\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\distribute\mirrored_run.py", line 75, in call_for_each_replica
>     return wrapped(args, kwargs)
>   File "C:\Users\preto\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
>     result = self._call(*args, **kwds)
>   File "C:\Users\preto\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\eager\def_function.py", line 888, in _call
>     return self._stateless_fn(*args, **kwds)
>   File "C:\Users\preto\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\eager\function.py", line 2942, in __call__
>     return graph_function._call_flat(
>   File "C:\Users\preto\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\eager\function.py", line 1918, in _call_flat
>     return self._build_call_outputs(self._inference_function.call(
>   File "C:\Users\preto\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\eager\function.py", line 555, in call
>     outputs = execute.execute(
>   File "C:\Users\preto\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
>     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
> tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
>          [[node ssd_mobile_net_v2fpn_keras_feature_extractor/model/Conv1/Conv2D (defined at C:\Users\preto\anaconda3\envs\tensorflow\lib\site-packages\object_detection\models\ssd_mobilenet_v2_fpn_keras_feature_extractor.py:219) ]] [Op:__inference__dummy_computation_fn_13690]
> 
> Errors may have originated from an input operation.
> Input Source operations connected to node ssd_mobile_net_v2fpn_keras_feature_extractor/model/Conv1/Conv2D:
>  args_1 (defined at C:\Users\preto\anaconda3\envs\tensorflow\lib\site-packages\object_detection\model_lib_v2.py:169)
> 
> Function call stack:
> _dummy_computation_fn
> 
> 
> (tensorflow) C:\TensorFlow\workspace\training_demo>```
> ```

Hi, did you manage to fix this? I'm having the same issue right now..

**Comment by aysebyz5942** [comment]
İ hade the same issue did you solv it?

**Comment by MMB019** [comment]
I have the same issue did you solv it

**Comment by Prayoga2882** [comment]
just replace the batch size =1 and make sure you're use CPU/GPU at `use_bfloat16 :`

-
