### ISSUE TITLE
keras layers API documentation not sorted properly

### ISSUE THREAD

**Issue by PaulPauls** [tensorflow/tensorflow#43224]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/keras/layers

## Description of issue (what needs changing):

Very minor issue, but the overview list of all layer classes is not consistently sorted alphabetically, though it very much feels like it is intended to (e.g. the GRU layer is listed above the GaussianDropout layer). In the sidebar it is sorted correctly alphabetically. I personally nearly overlooked the presence of the GRU layer because they are differently sorted in the sidebar and overview.

Unfortunately could I not find the API documentation in the tensorflow/docs repository, which is why I am opening the issue instead of offering a pull request. If you point me to the API documentation source can I gladly take care of that.

**Comment by bhack** [comment]
I think that the error is in the gen/sorting graph logic at https://github.com/tensorflow/docs/blob/master/tools/tensorflow_docs/api_generator/generate_lib.py. 

E.g. `GaussiaDropout` is at `n` as it is in `noise.py` https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/noise.py

/cc @yashk2810

**Comment by yashk2810** [comment]
I think this is the offending line: https://github.com/tensorflow/docs/blob/master/tools/tensorflow_docs/api_generator/generate_lib.py#L170

Technically, `GRU` should come before `GausionDropout` according to python's sorting rules.

```
In [1]: l = ['GRU', 'GaussianDropout', 'GRU']

In [2]: sorted(l)
Out[2]: ['GRU', 'GRU', 'GaussianDropout']
```

Let me know if you need any help in fixing this :)

**Comment by bhack** [comment]
@yashk2810 I think that your example is not the same:
```python
l = ['GRU', 'GaussianDropout', 'GRU']
l_sorted = sorted(l, key=lambda x: (x.upper(), x))
print(l_sorted)
```

```shell
['GaussianDropout', 'GRU', 'GRU']
```

**Comment by yashk2810** [comment]
Right, that's what I am saying. The TOC sorting is wrong because of the .upper(). If that's removed the TOC sorting should match the sorting on the Classes section of this page: https://www.tensorflow.org/api_docs/python/tf/keras/layers

**Comment by bhack** [comment]
Ok so do you prefer `lower` for all?

**Comment by PaulPauls** [comment]
Thank you very much for fixing this so quickly and providing a pull request. Especially to you @bhack as you were also addressing the random NaN issue I was opening 2 days ago and to which you already proposed a solution that I still need to process.

As this issue therefore seems addressed will I close it in order not to take time away from any other TF contributor. Thanks!
