### ISSUE TITLE
"Function call stack: _dist_train_step" error on tensorflow2 object detection api

### ISSUE THREAD

**Issue by dingjiaweiww** [tensorflow/tensorflow#43228]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to StackOverflow.

If you are reporting a vulnerability, please use the dedicated reporting process.

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

Every time I try to train the object detection models (any model, I tried ssd, faster rcnn, efficientdet..) by tf2 model train script (which is model_main_tf2.py), I got this error message every 1500~2000 steps.

image

I ran the notebook in google colab, and I got the colab pro upgrade either. (I thought this issue might be the memory issue on GPU or TPU)

I just followed the object detection api todo ..
Anyone can help..?
I also put a link to my colab notebook too.

https://colab.research.google.com/drive/1Xg5NKpipLTUCCyTFDYYCC_xAkPRTUyCc?usp=sharing

**Comment by Saduf2019** [comment]
@dingjiaweiww 
This is aduplicate of #43227, please move this to close status.
