### ISSUE TITLE
Confused which version TensorfFlow CPU supports

### ISSUE THREAD

**Issue by trystbinx** [tensorflow/tensorflow#43229]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10/Ubuntu 18.04/Linux Mint
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/a
- TensorFlow installed from (source or binary): Source
- TensorFlow version: v 1.x to  2.3.0
- Python version: 3.6 to 3.8
- Installed using virtualenv? pip? conda?: virtualenv, pip & conda
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- CUDA/cuDNN version: N/a
- GPU model and memory: N/a

**Describe the problem**

In terms of the OS Platform, I have used 3 different OS such as Windows 10, Ubuntu 18.04 and Linux Mint.

I am having a persistent problem in installing TensorFlow GPU before because the NVIDIA Driver cannot be installed/continued due to incompatible versions. Thus, I gave up on it, and now am only interested in installing TensorFlow CPU.

I used to having problems when installing TensorFlow GPU when it always says 'DLL failed to load when ......' and 'Importerror no name image_preprocessing'.

**My issue** is whatever I issue 'import tensorflow as tf' in Python 3.6 to Python 3.8 with TF 1.1+ to 2.3, respectively, the following message always appears (see logs).

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Python = 3.6 to 3.8
Tensorflow = 1.1+ to 2.3.0

**Any other info / logs**

```
(tensor0) root@opwrd:/home/user# python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Illegal instruction (core dumped)
```

**Is there any simpler way of installing TensorFlow CPU without concerning about its version/getting errors?** I have been working on this for days.

I seriously look forward to hearing from the TensorFlow team about this issue. I am needing to install TensorFlow to perform performance benchmarks on my object detection models, but this cannot be done without having TensorFlow in my machine.

Highly appreciated your answers/advice.

**Comment by ravikyram** [comment]
@trystbinx 

Please, follow the instructions as mentioned [here](https://www.tensorflow.org/install/gpu).
Please, see tested build configurations for [linux/mac](https://www.tensorflow.org/install/source#tested_build_configurations),[windows](https://www.tensorflow.org/install/source_windows#tested_build_configurations).
Please, see steps for installing through[ pip](https://www.tensorflow.org/install/pip),[hardware requirements](https://www.tensorflow.org/install/pip#hardware-requirements).

In case of windows please make sure  to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
Also, please follow the instructions from to install from [Tensorflow website.](https://www.tensorflow.org/install/source_windows).
Please, check Your CPU/Python is on 32 bits?
Regarding DLL errors please see similar issues.
.Please, refer similar issue #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204

Thanks!

**Comment by trystbinx** [comment]
@ravikyram 
> 
> Please, follow the instructions as mentioned [here](https://www.tensorflow.org/install/gpu).
> Please, see tested build configurations for [linux/mac](https://www.tensorflow.org/install/source#tested_build_configurations),[windows](https://www.tensorflow.org/install/source_windows#tested_build_configurations).
> Please, see steps for installing through[ pip](https://www.tensorflow.org/install/pip),[hardware requirements](https://www.tensorflow.org/install/pip#hardware-requirements).
> 
> In case of windows please make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
> Also, please follow the instructions from to install from [Tensorflow website.](https://www.tensorflow.org/install/source_windows).
> Please, check Your CPU/Python is on 32 bits?
> Regarding DLL errors please see similar issues.
> .Please, refer similar issue #36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
> 
> Thanks!

Should I install GPU as instructed if I decide to only use the CPU for TensorFlow? What I mean is that I dismiss the GPU installations. I have been dealing with this GPU issue since a week ago and still cannot be installed properly. I find it extremely difficult/complicated. Thus, my main focus is just to install TensorFlow CPU even it is much slower and better than keeping installing for hours/days.

My Python is between 3.6 to 3.8. For Python 3.6, my TF is 1.1x till 2.20 and for Python  3.7, my TF is 2.1+.0.

```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
```

Actually I had been installing  a number of versions of NVIDIA drivers (like 30 GB). I kept having 'NVIDIA Driver cannot continue' even though I could install the CUDA toolkit and cudnn smoothly. Due to this reason, if I cannot keep up with the installation by today, I would have to drop my Tensorflow task as a part of my project.

Thank you.

**Comment by ravikyram** [comment]
@trystbinx 

Can you install from source following this [guide](https://www.tensorflow.org/install/source).

 TensorFlow is only [tested and supported for 64-bit, x86 systems.](https://www.tensorflow.org/install).I don't believe you can install TensorFlow through pip or conda normally from a 32-bit system

**Comment by trystbinx** [comment]
> @trystbinx
> 
> Can you install from source following this [guide](https://www.tensorflow.org/install/source).

Well, I will do it now and see if I can do it properly.

> TensorFlow is only [tested and supported for 64-bit, x86 systems.](https://www.tensorflow.org/install).I don't believe you can install TensorFlow through pip or conda normally from a 32-bit system

Thanks for the clarification. Yes, I installed everything in my virtualenv or through pip/conda. That's what I followed on YouTube.

I have unsuccessfully installed TensorFlow GPU on Windows 10. Now, I have to use my Ubuntu with no nvidia yet. The end project would be to use Raspberry Pi to perform object detection. Installing TF is a headache for now because it is the base of my project development. I have to find which object detection models are the best to perform object detection on a very slow embedded device.

I just confirmed somewhere that my CPU does not support AVX and that I am required to build from source.

**Comment by bhack** [comment]
@trystbinx What is the output of `grep -o 'avx[^ ]*' /proc/cpuinfo` on your linux machine?

**Comment by ahtik** [comment]
@trystbinx What is your CPU? If your CPU does not support AVX then I would **not** recommend going for the **build from source** route. Better find a setup where AVX is available and everything would go much smoother (including the NVIDIA GPU drivers and CUDA installation). You can always install the latest NVIDIA drivers but make sure CUDA is 10.1, for TF 2.2, 2.3 and do not try to install other CUDA versions in parallel.

Raspberry Pi has an ARM CPU, so AVX is not relevant there and setup is somewhat different, more likely going to need the TensorFlow Lite and convert the object detection model for it. If you need better performance than the CPU on a Raspberry Pi can provide, have a look at the Coral Edge TPU line-up. Either an USB Accelerator that plugs into the Raspberry Pi and supports the TF Lite models, or the whole dev board without the Raspberry board.
