### ISSUE TITLE
Usage of MethodNameUpdater() function

### ISSUE THREAD

**Issue by florence27** [tensorflow/tensorflow#43233]
@florence27 can you please report a new issue along with the complete  code to reproduce the error that is not working and cc me on it as well. 
Thanks, 
Goldie

_Originally posted by @goldiegadde in https://github.com/tensorflow/tensorflow/issues/34968#issuecomment-692168824_

As already mentioned in issue #34968 I'd like to use the `MethodNameUpdater()` function in order to change the method name in the signature from predict to classify. Unfortunately, the following code is not running, due to an `AttributeError`:

```
import tensorflow as tf

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(4, input_shape=(FEATURE_SIZE,)))
model.add(tf.keras.layers.Dense(1))
optim = tf.keras.optimizers.Adam()
model.compile(loss='mean_squared_error', optimizer=optim, metrics=['mae'])

x, y = load_features(train_files, scaler)
model.fit(x, y, epochs=num_epochs, callbacks=callbacks)

job_dir = '/path/to/job/'
version = '00000123'
export_path = os.path.join(job_dir, version)

tf.keras.models.save_model(
                model,
                export_path,
                overwrite=True,
                include_optimizer=True,
                save_format=None,
                options=None,
            )

updater = tf.compat.v1.saved_model.builder.MethodNameUpdater(export_path)
updater.replace_method_name(signature_key="bar", method_name="classify", tags="serve")
updater.save(export_path)
```

This is the exact error I'm getting: `AttributeError: module 'tensorflow._api.v2.compat.v1.saved_model.builder' has no attribute 'MethodNameUpdater'`. The `load_features()` function takes the training files and a `MinMaxScaler()` as inputs and returns `np.arrays` with input features and corresponding labels. My setup is the following: 

OS Platform: macOS Catalina, Version 10.15.5
Tensorflow Version: 2.3.0
Python Version: 3.7.9

Any help with this would be appreciated!

**Comment by bhack** [comment]
Can you share a minimal but fully runnable example that we can copy, paste and run to reproduce your error? Also a runnable colab is ok.

Thanks.

**Comment by florence27** [comment]
Sure, here you go: 

```
import tensorflow as tf 
import numpy as np
import os 

FEATURE_SIZE = 3
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(4, input_shape=(FEATURE_SIZE,)))
model.add(tf.keras.layers.Dense(1))
optim = tf.keras.optimizers.Adam()
model.compile(loss='mean_squared_error', optimizer=optim, metrics=['mae'])

x = tf.ones((3, 3))
y = tf.zeros(3)
print(x.shape, y.shape)

num_epochs = 3
model.fit(x, y, epochs=num_epochs)

job_dir = os.getcwd()
print(job_dir)
version = '1'
export_path = os.path.join(job_dir, version)

tf.keras.models.save_model(
                model,
                export_path,
                overwrite=True,
                include_optimizer=True,
                save_format=None,
                options=None,
            )

updater = tf.compat.v1.saved_model.builder.MethodNameUpdater(export_path)
updater.replace_method_name(signature_key="bar", method_name="classify", tags="serve")
updater.save(export_path)
```

**Comment by bhack** [comment]
You can use:
`updater = tf.compat.v1.saved_model.signature_def_utils.MethodNameUpdater(export_path)`

But your saved model is missing signatures so you example is incomplete.

**Comment by florence27** [comment]
@bhack thanks that was the help I needed! I omitted the signatures in this example, but I'm using some in my current project, so that should be fine. Thank you so much!

**Comment by ravikyram** [comment]
@florence27 

Please, close this thread if your issue was resolved. Thanks!
