### ISSUE TITLE
tf2.3 c++库编译失败

### ISSUE THREAD

**Issue by passion765** [tensorflow/tensorflow#43234]
cenots 8
gcc 8.3.1

is_not_gcc failed: error executing command 
  (cd /home/docker_data/.bazel_cache_2_3/7a9fafc24832c7560e0a6e1a434658e0/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda-10.2 \
    CUDNN_INSTALL_PATH=/usr/local/cuda-10.2 \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda-10.2/lib64:/usr/local/cuda-10.2/targets/x86_64-linux/lib:/usr/local/cuda-10.2/extras/CUPTI/lib64: \
    NCCL_INSTALL_PATH=/usr \
    PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/cuda-10.2/bin:/usr/local/cuda-10.2/targets/x86_64-linux/lib:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/local/lib/python3.6/site-packages \
    TENSORRT_INSTALL_PATH=/usr/local/cuda-10.2 \
    TF2_BEHAVIOR=1 \
    TF_CONFIGURE_IOS=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=6.1 \
    TF_CUDA_PATHS=/usr/local/cuda-10.2 \
    TF_CUDA_VERSION=10.2 \
    TF_CUDNN_VERSION=7 \
    TF_ENABLE_XLA=1 \
    TF_NCCL_VERSION=2 \
    TF_NEED_CUDA=1 \
    TF_TENSORRT_VERSION=7 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc @bazel-out/k8-opt/bin/tensorflow/libtensorflow_cc.so.2.3.0-2.params)
Execution platform: @local_execution_config_platform//:platform
bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/libkernels.pic.lo(mat_mul_op.pic.o): In function `tensorflow::CSRMatMulGPUOp<float>::Compute(tensorflow::OpKernelContext*)':
mat_mul_op.cc:(.text._ZN10tensorflow14CSRMatMulGPUOpIfE7ComputeEPNS_15OpKernelContextE[_ZN10tensorflow14CSRMatMulGPUOpIfE7ComputeEPNS_15OpKernelContextE]+0x14ba): undefined reference to `tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, float>::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
bazel-out/k8-opt/bin/tensorflow/core/kernels/sparse/libkernels.pic.lo(sparse_mat_mul_op.pic.o): In function `tensorflow::CSRSparseMatMulGPUOp<Eigen::GpuDevice, float>::Compute(tensorflow::OpKernelContext*)':
sparse_mat_mul_op.cc:(.text._ZN10tensorflow20CSRSparseMatMulGPUOpIN5Eigen9GpuDeviceEfE7ComputeEPNS_15OpKernelContextE[_ZN10tensorflow20CSRSparseMatMulGPUOpIN5Eigen9GpuDeviceEfE7ComputeEPNS_15OpKernelContextE]+0x8ee): undefined reference to `tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, float>::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
sparse_mat_mul_op.cc:(.text._ZN10tensorflow20CSRSparseMatMulGPUOpIN5Eigen9GpuDeviceEfE7ComputeEPNS_15OpKernelContextE[_ZN10tensorflow20CSRSparseMatMulGPUOpIN5Eigen9GpuDeviceEfE7ComputeEPNS_15OpKernelContextE]+0x97e): undefined reference to `tensorflow::functor::CSRSparseMatrixTranspose<Eigen::GpuDevice, float>::operator()(tensorflow::OpKernelContext*, bool, tensorflow::CSRSparseMatrix const&, tensorflow::CSRSparseMatrix*)'
collect2: error: ld returned 1 exit status
Target //tensorflow:libtensorflow_cc.so failed to build
INFO: Elapsed time: 37.074s, Critical Path: 36.43s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by Saduf2019** [comment]
@passion765 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error,complete error log]

Your may verify with [this link](https://github.com/tensorflow/tensorflow/issues/762#issuecomment-173002842), and let us know if it helps. [[link](https://github.com/tensorflow/tensorflow/issues/32775#issuecomment-542337360), [link1](https://stackoverflow.com/questions/35290945/compiling-tensorflow-from-source-undefined-reference-to-tensorflowfunctorfi).]

you may also please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) and check if you have the correct dependencies installed.

**Comment by passion765** [comment]
my command is bazel build -c opt --copt="-O3" --copt="-fpic" --cxxopt="-fpic" --cxxopt="-O3" --cxxopt="-std=c++14" --config=cuda --verbose_failures //tensorflow:libtensorflow_cc.so

and you can see much infomation from output above.    
I can build sucessfully tf2.2  ,   but tf2.3  always be error at "tensorflow::functor::CSRSparseMatrixTranspose" , could you help me?

**Comment by passion765** [comment]
> my command is bazel build -c opt --copt="-O3" --copt="-fpic" --cxxopt="-fpic" --cxxopt="-O3" --cxxopt="-std=c++14" --config=cuda --verbose_failures //tensorflow:libtensorflow_cc.so
> 
> and you can see much infomation from output above.
> I can build sucessfully tf2.2 , but tf2.3 always be error at "tensorflow::functor::CSRSparseMatrixTranspose" , could you help me?

@Saduf2019

**Comment by passion765** [comment]
I can build py tf2.3 sucessfully , but libtensorflow_cc.so tf2.3 always failed .

**Comment by Saduf2019** [comment]
@passion765 
Please refer to below links and let us know if it helps.
[link](https://github.com/tensorflow/tensorflow/issues/22240#issuecomment-420782646) [link1](https://stackoverflow.com/questions/62460560/tf2-2-build-libtensorflow-cc-so-for-c-apis), [link2](https://github.com/tensorflow/tensorflow/issues/4279)
#40004 #35623

**Comment by passion765** [comment]
> @passion765
> Please refer to below links and let us know if it helps.
> [link](https://github.com/tensorflow/tensorflow/issues/22240#issuecomment-420782646) [link1](https://stackoverflow.com/questions/62460560/tf2-2-build-libtensorflow-cc-so-for-c-apis), [link2](https://github.com/tensorflow/tensorflow/issues/4279)
> #40004 #35623

the links you provide could not solve my question , I can build tf2.2 sucessfully , but tf2.3 libtensorflow_cc.so always link error, and i build tf2.3 //tensorflow/core:core //tensorflow/core:all_kernels_impl   //tensorflow/core:tensorflow_opensource ,they are sucessful, but target libtensorflow_cc.so links errror ，i do not kown how to solve it , it is maybe  a bug .

**Comment by passion765** [comment]
@Saduf2019 

> @passion765
> Please refer to below links and let us know if it helps.
> [link](https://github.com/tensorflow/tensorflow/issues/22240#issuecomment-420782646) [link1](https://stackoverflow.com/questions/62460560/tf2-2-build-libtensorflow-cc-so-for-c-apis), [link2](https://github.com/tensorflow/tensorflow/issues/4279)
> #40004 #35623

the links you provide could not solve my question , I can build tf2.2 sucessfully , but tf2.3 libtensorflow_cc.so always link error, and i build tf2.3 //tensorflow/core:core //tensorflow/core:all_kernels_impl //tensorflow/core:tensorflow_opensource ,they are sucessful, but target libtensorflow_cc.so links errror ，i do not kown how to solve it , it is maybe a bug .

**Comment by passion765** [comment]
> @Saduf2019
> 
> > @passion765
> > Please refer to below links and let us know if it helps.
> > [link](https://github.com/tensorflow/tensorflow/issues/22240#issuecomment-420782646) [link1](https://stackoverflow.com/questions/62460560/tf2-2-build-libtensorflow-cc-so-for-c-apis), [link2](https://github.com/tensorflow/tensorflow/issues/4279)
> > #40004 #35623
> 
> the links you provide could not solve my question , I can build tf2.2 sucessfully , but tf2.3 libtensorflow_cc.so always link error, and i build tf2.3 //tensorflow/core:core //tensorflow/core:all_kernels_impl //tensorflow/core:tensorflow_opensource ,they are sucessful, but target libtensorflow_cc.so links errror ，i do not kown how to solve it , it is maybe a bug .

i build //tensorflow/cc:tutorials_example_trainer  meet a same question .    and i search it , meet a similar link https://stackoverflow.com/questions/35290945/compiling-tensorflow-from-source-undefined-reference-to-tensorflowfunctorfi

, can this help you analise question ?
