### ISSUE TITLE
Didn't find op for builtin opcode 'CONV_2D' version '5'

### ISSUE THREAD

**Issue by juanpbotero98** [tensorflow/tensorflow#43232]
Hi, I'm trying to run inference of a custom trained mobilenet_v2_coco17_320x320_tpu-8 model on a Raspberry pi. I have succesfully trained, saved and converted the model to tf.lite. However, when trying to run the inttepreter on a Raspberry pi 4, I'm getting the following error: ValueError: Didn't find op for builtin opcode 'CONV_2D' version '5' Registration failed.
But when running the interpreter on google colab notebook it works just fine.    

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google colab
- TensorFlow installed from (source or binary): tf-nightly on colab. tf-2.2 on Rapsberry pi

**Provide the text output from tflite_convert**

```
converter = tf.lite.TFLiteConverter.from_saved_model('/content/drive/My Drive/Deteccion_escaleras/models/research/Mobilenet_entrenada/saved_model',signature_keys=['serving_default'])
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS]
tflite_model = converter.convert()

with tf.io.gfile.GFile('/content/drive/My Drive/training_mobilenet/model_3.tflite', 'wb') as f:
  f.write(tflite_model)
  print("Model saved")
```
Code use for training,evaluation,conversion:
https://colab.research.google.com/drive/1M7SBWcA_gRe4xEww3q8QYdyblV8Ic2Te?usp=sharing

**Any other info / logs**

Generated model files (saved_model.pb & model.tflite): https://drive.google.com/drive/folders/1-JHyeg268jQWyXF_AO348SNN8fgU1TCT?usp=sharing

**Comment by bhack** [comment]
The saved model is incomplete. Can you share a saved model dir that we can load directly?

**Comment by juanpbotero98** [comment]
@bhack Sorry what do you mean when you say the model is incomplete? That folder attached contains a saved_model.pb file that I've loaded directly using the tf.saved_model.load() command. Did you get a problem when loading the model?
However here is the complete directory containning the saved model folder and  the checkpoints folder:
https://drive.google.com/drive/folders/1-JHyeg268jQWyXF_AO348SNN8fgU1TCT?usp=sharing

**Comment by bhack** [comment]
Ok.. what TF version are you using on Raspberry?

**Comment by juanpbotero98** [comment]
I'm running tf 2.2

**Comment by bhack** [comment]
Can you try to align the exporting version and the one running on Raspberry?

**Comment by juanpbotero98** [comment]
When I try to do that I run in to a problem with the exporter beacuse of the dynamic input tensor in model. ValueError: None is only supported in the 1st dimension. Tensor 'input_tensor' has invalid shape '[1, None, None, 3]'.

And when I try to export using concretefunc I run into another error: Exception: <unknown>:0: error: loc("Func/StatefulPartitionedCall/input/_1"): requires all operands to be either same as or ref type of results
Here(https://colab.research.google.com/drive/1Uwj0Boede08W0e7gpb3evQp3RSQysqtr?usp=sharing) I attach a notebook where I downgraded TF to 2.2 and try to run an export job by the 2 different means mentioned.

**Comment by bhack** [comment]
I think It Is hard to get a precomp nightly for Raspberry to quickly test the exported model cause we don't have a new link for nightly: https://github.com/tensorflow/tensorflow/issues/21469

Can you try to build https://www.tensorflow.org/install/source_rpi

**Comment by abattery** [comment]
@juanpbotero98 It looks like TF 2.2 version does not have the CONV_2D version '5'. You need to use a recent version of TF runtime or at least the same TF version, used for conversion in Raspberry.

**Comment by juanpbotero98** [comment]
@bhack I managed to upgrade tf on my Raspberry pi to the latest available version (2.3) however i couldn't find any data for installing tf-nightly and when running the interpreter I still get the same error.

**Comment by juanpbotero98** [comment]
@abattery Thanks I will now try to convert using tf 2.3 since now i have that version running in my raspberry pi.

**Comment by bhack** [comment]
If 2.3 will not convert your model (if it requires ft-nightly) you will need to build the PI with the same instructions but from the master branch.

**Comment by juanpbotero98** [comment]
When trying to convert using tf 2.3 I ran into the following error:
<unknown>:0: error: loc("Func/StatefulPartitionedCall/input/_0"): requires all operands and results to have compatible element types
<unknown>:0: note: loc("Func/StatefulPartitionedCall/input/_0"): see current operation: %1 = "tf.Identity"(%arg0) {_class = ["loc:@Func/StatefulPartitionedCall/StatefulPartitionedCall/input/_335"], device = ""} : (tensor<1x?x?x3x!tf.quint8>) -> tensor<1x?x?x3xui8>

**Comment by juanpbotero98** [comment]
@bhack Could you please elaborate? what do you mean by building the Pi from the master branch?

**Comment by bhack** [comment]
Yes, same instruction but from the master branch:
https://www.tensorflow.org/install/source_rpi

**Comment by juanpbotero98** [comment]
@bhack I tried to run the instruction for the master branch but after all the compiling was done I wasn't able to find the .whl file. I don't really know what went wrong. 
the only thing is that when I run the commad: git checkout branch_name I get an error saying: git checkout branch name did not match any file known to git.

**Comment by bhack** [comment]
<branch_name> is e.g. `master`

The wheel is in the outputdir defined at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/pi/build_raspberry_pi.sh#L128

**Comment by juanpbotero98** [comment]
@bhack I'm running the commands listed in https://www.tensorflow.org/install/source_rpi, and it seems to run without any problem however the out-artifacts directory doesn't get created. Hence no .whl file gets created either. I don't know what might be the problem.

**Comment by juanpbotero98** [comment]
I found the error i was running out of memory before the .whl file could be generated. I'm going trough the buil once again using a digital ocean virtual machine.

**Comment by bhack** [comment]
@juanpbotero98 You can also add some option to limit the RAM https://www.tensorflow.org/install/source#bazel_build_options

**Comment by juanpbotero98** [comment]
@bhack Now I'm getting a really strange error. 
Execution platform: @local_execution_config_platform//:platform arm-rpi-linux-gnueabihf-gcc: internal compiler error: Killed (program cc1plus)
and after that the console prints: FAILED: Build did NOT complete successfully

**Comment by bhack** [comment]
@juanpbotero98 Sorry I don't have currently enought free resources to rebuild It locally.
In the meantime can I suggest you to open a ticket mentioning this one in https://github.com/tensorflow/build? That one is to request if they can publish again regularly Raspberry tf-nightly wheels.
Cause at some point we lost It as you can see from #21469

It think that could useful for other devs that need to tf-nightly to convert their model to be aligned at inference time on the device.

**Comment by juanpbotero98** [comment]
@bhack Thanks for all the help, I really appriciate it! . I will definitely post a ticket requesting the tf-nigthly wheels for Raspberry pi. However I was wondering if in the meantime there is anything I can do, like  train the model from scratch using a certain TF version or something like that.

**Comment by bhack** [comment]
I think in the meantime you have also two other actions:

- open a new ticket here about the error you got building Rasberry wheel on master
- try to find a TF version for the model training and conversion that works with your model but that is also compatible with an already available precompiled Raspberry wheel (<= 2.3)

**Comment by aryan461** [comment]
I have the same problem with tflite_runtime 2.5.0 on Raspberry pi 4. Is there any new solution?

**Comment by mohantym** [comment]
Hi @HMellor  !
We are checking to see whether you still need help in this issue .
Have you  checked from 2.10/2.11 tensorflow lite run time. I can see Conv2D in built in[ ops allow list ](https://www.tensorflow.org/mlir/tfl_ops#tflconv_2d_mlirtflconv2dop )now .

If issue still persists, Please check with work around in below similar issues or post in [TFlite-micro](https://github.com/tensorflow/tflite-micro) repo for further assistance.

Attached similar issues for reference.

[1]( https://github.com/tensorflow/tensorflow/issues/48720#issuecomment-1259281326), [2](https://github.com/tensorflow/tensorflow/issues/49603#issuecomment-1259289638)

Thank you!

**Comment by gptshubham595** [comment]
try this it solved my issue

check 

`!pip show tensorflow`

now try to add  implementation of same version if i have tf 2.12.0 then use below

eg: `implementation 'org.tensorflow:tensorflow-lite:2.12.0'`
