### ISSUE TITLE
I am not able to install tensorflow

### ISSUE THREAD

**Issue by MadMaxINDIAN** [tensorflow/tensorflow#43244]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): command prompt
- TensorFlow version: 2.0
- Python version:3.7.3
- Installed using virtualenv? pip? conda?: pip

**Describe the problem**
I am unable to install tensorflow from my command prompt using pip

**Provide the exact sequence of commands / steps that you executed before running into the problem**
pip install tensorflow==2.2.0rc4
pip install tensorflow

 **ERROR**
`ERROR: Could not find a version that satisfies the requirement tensorflow==2.2.0rc4 (from versions: none)
ERROR: No matching distribution found for tensorflow==2.2.0rc4`

**Comment by mihaimaruseac** [comment]
Is your Python on 32 bits? Why do you want to install an rc? What is the output of `pip debug verbose`?

**Comment by MadMaxINDIAN** [comment]
My python is on 64 bits and output for that command is 
`pip version: pip 20.2.3 from c:\users\naman\appdata\local\programs\python\python37-32\lib\site-packages\pip (python 3.7)
sys.version: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)]
sys.executable: c:\users\naman\appdata\local\programs\python\python37-32\python.exe
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: cp1252
sys.platform: win32
sys.implementation:
  name: cpython
'cert' config value: Not specified
REQUESTS_CA_BUNDLE: None
CURL_CA_BUNDLE: None
pip._vendor.certifi.where(): c:\users\naman\appdata\local\programs\python\python37-32\lib\site-packages\pip\_vendor\certifi\cacert.pem
pip._vendor.DEBUNDLED: False
vendored library versions:
  appdirs==1.4.4
  CacheControl==0.12.6
  colorama==0.4.3
  contextlib2==0.6.0.post1 (Unable to locate actual module version, using vendor.txt specified version)
  distlib==0.3.1
  distro==1.5.0 (Unable to locate actual module version, using vendor.txt specified version)
  html5lib==1.1
  ipaddress==1.0.23
  msgpack==1.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  packaging==20.4
  pep517==0.8.2
  progress==1.5
  pyparsing==2.4.7
  requests==2.24.0
  certifi==2020.06.20
  chardet==3.0.4
  idna==2.10
  urllib3==1.25.9
  resolvelib==0.4.0
  retrying==1.3.3 (Unable to locate actual module version, using vendor.txt specified version)
  setuptools==44.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  six==1.15.0
  toml==0.10.1
  webencodings==0.5.1 (Unable to locate actual module version, using vendor.txt specified version)
Compatible tags: 27
  cp37-cp37m-win32
  cp37-abi3-win32
  cp37-none-win32
  cp36-abi3-win32
  cp35-abi3-win32
  cp34-abi3-win32
  cp33-abi3-win32
  cp32-abi3-win32
  py37-none-win32
  py3-none-win32
  py36-none-win32
  py35-none-win32
  py34-none-win32
  py33-none-win32
  py32-none-win32
  py31-none-win32
  py30-none-win32
  cp37-none-any
  py37-none-any
  py3-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any`

**Comment by mihaimaruseac** [comment]
`sys.platform: win32` and all the `-win32` tags mean you Python is on 32 bits

**Comment by MadMaxINDIAN** [comment]
Thanks for the help I have upgraded my python to 64 bit
and now I am able to install tensorflow
