### ISSUE TITLE
when i am running the sample tutorial code of basic text classification i just cannot download a file named imdb_word_index.json  

### ISSUE THREAD

**Issue by aLLLiyyy** [tensorflow/tensorflow#43245]
when Downloading the url "https://storage.googleapis.com/tensorflow/tf-keras-datasets/imdb_word_index.json" the program run into the method of "self._sslobj.do_handshake()" in file of ssl.py and raise an exception of "TimeoutError: [WinError 10060]" . yet i dont know how to solve this problem ,so please help me to out ,thanks

**Comment by bhack** [comment]
Can you try:
```
import tensorflow as tf
index = tf.keras.datasets.imdb.get_word_index(
    path='imdb_word_index.json'
)
print(index)
```

**Comment by aLLLiyyy** [comment]
> Can you try:
> 
> ```
> import tensorflow as tf
> index = tf.keras.datasets.imdb.get_word_index(
>     path='imdb_word_index.json'
> )
> print(index)
> ```



> Can you try:
> 
> ```
> import tensorflow as tf
> index = tf.keras.datasets.imdb.get_word_index(
>     path='imdb_word_index.json'
> )
> print(index)
> ```

I tried ,but it still failed to download that file,here is the error msg below:
Exception: URL fetch failure on https://storage.googleapis.com/tensorflow/tf-keras-datasets/imdb_word_index.json: None -- [WinError 10060]

**Comment by bhack** [comment]
What Is your TF version?

**Comment by aLLLiyyy** [comment]
version 2.3.0

**Comment by bhack** [comment]
Do you have a proxy?

**Comment by aLLLiyyy** [comment]
@bhack  i dont use a proxy ,i can connect to the internet normally ,when i use my chrome web browser it seems okay to get that file,but in python code it cannot ,i dont know what went wrong,

**Comment by bhack** [comment]
Can you check if you have the same errore with a code snippet without TF.

```
import urllib.request
url = '<your_url_here>' 
response = urllib.request.urlopen(url)
data = response.read()
```

**Comment by aLLLiyyy** [comment]
@bhack yes, i meet the same error, what am i supposed do next

**Comment by bhack** [comment]
Using this code, do you have problems putting another URL as well?

**Comment by aLLLiyyy** [comment]
@bhack no ,i v changed another url but it runs well i can get the response text but use that url address i posted above not

**Comment by bhack** [comment]
What Is your python version?

**Comment by aLLLiyyy** [comment]
@bhack  python version is Python 3.6.6

**Comment by bhack** [comment]
If you can I suggest you to give a try with an updated python version (64bit).

**Comment by aLLLiyyy** [comment]
@bhack i will try it, thanks anyway
