### ISSUE TITLE
can't find module tensorflow after building 'quantize_graph'

### ISSUE THREAD

**Issue by yossibiton** [tensorflow/tensorflow#4324]
Hi,

I followed this [blog post](https://petewarden.com/2016/05/03/how-to-quantize-neural-networks-with-tensorflow/) in order build the tool for quantizing graph (tensorflow/contrib/quantization/tools/quantize_graph).
I had a clean working version of tensorflow installed properly.

I used this command in order to build the quantization tool :
**bazel build tensorflow/contrib/quantization/tools:quantize_graph**

It seems that the build went ok :
**INFO: Found 1 target...
Target //tensorflow/contrib/quantization/tools:quantize_graph up-to-date:
  bazel-bin/tensorflow/contrib/quantization/tools/quantize_graph
INFO: Elapsed time: 20.105s, Critical Path: 16.60s**

However after that finished when i open python and try to import tensorflow i get an error message :
**ImportError: No module named tensorflow**
### Environment info

Operating System: Ubuntu 16.04

Installed from source, without GPU support :
1. commit hash = 37256f4857cdadefa09e0505f4acc91ffbf626e2
2. bazel version = 
Build label: 0.3.1
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 29 09:09:52 2016 (1469783392)
Build timestamp: 1469783392
Build timestamp as int: 1469783392

**Comment by yossibiton** [comment]
i get the same behaviour when trying to build the freeze_graph tool :
bazel build tensorflow/python/tools:freeze_graph

**Comment by drpngx** [comment]
It looks like you need to follow the install steps again. Feel free to reopen the issue if you still have the problem.
