### ISSUE TITLE
mAP drops crazily when replacing Conv with Depthwise_Conv

### ISSUE THREAD

**Issue by neesetifa** [tensorflow/tensorflow#43256]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- TensorFlow installed from (source or binary): package manager
- TensorFlow version (or github SHA if from source): 2.3.0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
    converter = tf.lite.TFLiteConverter.from_keras_model(model_yolo)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_data_gen
    
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    
    tflite_model_quant = converter.convert()
```

**The output from the converter invocation**

```
# Nothing. Successfully converted to tflite model.
```

**Also, please include a link to the saved model or GraphDef**

```
# Model Definition file see attachment
[mobilenet_v2_yolo_v3.zip](https://github.com/tensorflow/tensorflow/files/5229629/mobilenet_v2_yolo_v3.zip)

```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing huge decrease in accuracy

**Any other info / logs**
I am doing object detection using MoblieNet Yolo v3.
For backbone I use mobilenet v2. I almost copy and paste from official keras implementation. The problem seems happens in YOLO head (I called it "_make_last_layers" in my code).
For the first time, I use  
`_make_last_layers_1()`
as my YOLO head.  After converted to tflite model, mAP only drops around 1~4% compared to original model.

For the second time, I use
`_make_last_layers_2()`
as my YOLO head.  After converted to tflite model, mAP drops around **15~19%** compared to original model.

So the difference between _make_last_layers_1() and  _make_last_layers_2() is I try to use the combination of Depthwise_Conv+Conv to replace pure Conv so that I can reduce tons of parameters(23M -> 6.8M)

So...any idea why this structure causes such great drops in accuracy?

**Comment by amahendrakar** [comment]
@neesetifa,
On running the code I am facing an error stating `NameError: name 'representative_data_gen' is not defined`.




> as my YOLO head. After converted to tflite model, mAP drops around **15~19%** compared to original model.

Could you please provide the complete code and the dataset to reproduce reported here. Thanks!

**Comment by neesetifa** [comment]
@amahendrakar   Thank you for the reply. I put all the necessary code and the model in a zip file and upload it to google drive. You can find it here:
https://drive.google.com/file/d/13lsXf79RaWy11SQ5yuERyp0pT2Lc68Nr/view?usp=drivesdk
And I also put a ReadMe file for all the details of the code in the zip file.

**Comment by amahendrakar** [comment]
@neesetifa,
Thank you for the update. The code you've provided is fairly complex hence it would be difficult for us to pinpoint the issue. Can you remove the dependencies and get the example down to the simplest possible repro? That will allow us to debug the issue easily. Thanks!

**Comment by neesetifa** [comment]
Hi, @amahendrakar Sorry for the mess of my repo. 
Following are the files that I provided:
Model -->
1  Original keras model (.h5)
2  TFlite model  (.tflite)
Code -->
1  Complete definition of my model 
2  Script for converting original keras model to tflite model
3  Script for testing original keras model on test dataset
4  Script for testing tflite model on the same test dataset  
5  Script for calculating mAP based on the test dataset result

With above files, I can reproduce

> After converted to tflite model, mAP drops around 15~19% compared to original model.

I don't have much experience for debugging this kind of issue. Could you let me know which part(s) you need for debugging this, so that I can remove all the unnecessary parts and update the repo.   

Thank you

**Comment by amahendrakar** [comment]
@neesetifa,
On running the given code, I am facing an error stating `AttributeError: 'NoneType' object has no attribute 'shape'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/4f2a37f3d94d9adbe47d5432a7e0db4a/43256.ipynb). 

> Could you let me know which part(s) you need for debugging this, so that I can remove all the unnecessary parts and update the repo.

Please provide a simple standalone code snippet which we can run at out end and reproduce the issue. Thanks!

**Comment by neesetifa** [comment]
@amahendrakar  It seems that you might put the image files in the wrong directory. In representative_data_gen(), cv2.imread() didn't get any image so it returns 'None'.  
I understand that the codes need to be as simple as possible.  In order to reproduce the issue, I think at least the conversion code and mAP code are needed.  Let me see if I can upload all the codes with training/test data in correct directory and put a the process in a single script.

**Comment by amahendrakar** [comment]
> Let me see if I can upload all the codes with training/test data in correct directory and put a the process in a single script.

@neesetifa,
Any updates regarding this? Thanks!
