### ISSUE TITLE
setting verbosity to 0 does not suppress keras debug messages, no way to turn them off

### ISSUE THREAD

**Issue by prismspecs** [tensorflow/tensorflow#43253]
Using latest version(s) from Colab

Impossible to suppress the "Found X images belonging to N classes." that results from Keras flow_from_directory method

**Comment by amahendrakar** [comment]
@prismspecs,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!
