### ISSUE TITLE
Self-attention on word embeddings using half-precision with mask_zero set to True crashes training

### ISSUE THREAD

**Issue by KieranLitschel** [tensorflow/tensorflow#43261]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.5 LTS
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.1-41557-gae0a324182 2.4.0-dev20200915
- Python version: 3.6.9
- CUDA/cuDNN version: Bug reproducible without GPU (but the same bug occurs on GPU)
- GPU model and memory: Bug reproducible without GPU (but the same bug occurs on GPU)

**Describe the current behavior**

When applying self-attention to word embeddings with half-precision, if mask_zero is set to True, then training crashes. If it is set to False, then training completes without crashing.

**Describe the expected behavior**

Train with mask_zero set to True without crashing.

**Standalone code to reproduce the issue**

Reproduced bug in tf-nightly here:
https://colab.research.google.com/drive/1lzG0SonIWiqrnCLxzxQO-s2e-fYNoG1c?usp=sharing

**Other info / logs**

When mask_zero is set to True, the error is:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py in binary_op_wrapper(x, y)
   1135 
-> 1136   def binary_op_wrapper(x, y):
   1137     with ops.name_scope(None, op_name, [x, y]) as name:

13 frames
ValueError: Tensor conversion requested dtype float32 for Tensor with dtype float16: <tf.Tensor 'attention_19/MatMul:0' shape=(None, None, None) dtype=float16>

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py in _apply_op_helper(op_type_name, name, **keywords)
    504 
    505             # If we did not match an allowed dtype, try again with the default
--> 506             # dtype. This could be because we have an empty tensor and thus we
    507             # picked the wrong type.
    508             if inferred is not None and inferred.dtype in allowed_list:

TypeError: Input 'y' of 'Sub' Op has type float32 that does not match type float16 of argument 'x'.

**Comment by ravikyram** [comment]
I have tried in colab with TF nightly version and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/121ceaf5b03c83fe457988833d7bead5/untitled366.ipynb). Thanks!

**Comment by yongtang** [comment]
I think this issue will be fixed with PR #46321
