### ISSUE TITLE
Helm chart for TF2+GPU

### ISSUE THREAD

**Issue by joehoeller** [tensorflow/tensorflow#43264]
Would like to see a helm chart for TF2 w/ GPUs be made avail.

**Comment by bhack** [comment]
There are already some TF helm charts in https://github.com/helm/charts/. 
If you need something alse please close this and open a new thicked on that repository directly.

**Comment by joehoeller** [comment]
There must be some confusion, I am not looking for the helm chart repo. I
searched that and all I found was TF v1.16.

I am looking for a Helm chart for TF2+GPU.

**Comment by bhack** [comment]
Yes but I meant that we don't maintain Helm chart directly. 
It is a Helm community initiative in the Helm repository.
So if you have any request (e.g. like having something updated for TF2 + Gpu) open an issue or a PR directly there.
Thanks

**Comment by joehoeller** [comment]
Thank you.

**Comment by ryantimjohn** [comment]
Seems like this one can be closed out then, @joehoeller ?

**Comment by joehoeller** [comment]
Yes plz.
