### ISSUE TITLE
[RNN]Cannot get saved .tflite model

### ISSUE THREAD

**Issue by le8888e** [tensorflow/tensorflow#43270]
**System information**
- OS Platform and Distribution: Ubuntu 16.04
- TensorFlow installed from: binary
- TensorFlow version: tf-nightly 2.2.0

**Command used to run the converter or code if you’re using the Python API**

[convert_pb2_tflite.txt](https://github.com/tensorflow/tensorflow/files/5233664/convert_pb2_tflite.txt)

**The output  log from the converter invocation**
[log.txt](https://github.com/tensorflow/tensorflow/files/5233693/log.txt)

**Failure details**
My .pb model is trained and saved in tensorflow 1.15.0 and I want to convert it to .tflite to deploy on CPU for better performance. When I run the uploaded file convert_pb2_tflite.txt(.py actually), the log attached above seems to include no warning and errors. But there is no tflite file in my save path. What's probably going wrong? 
Thank you.

**Comment by abattery** [comment]
tf.Sign op is currently supported by the TFLite builtin operator set. You can use the Select TF op set for covering tf.Sign op. Please refer to the following guide pages.

https://www.tensorflow.org/lite/guide/ops_select
https://www.tensorflow.org/lite/guide/reduce_binary_size

**Comment by le8888e** [comment]
Hi @abattery,

Thank you, I successfully convert following your instruction. But the .pb file before convert is 131MB, and converted .tflite file is 73MB, is this normal?

 Thank you.

**Comment by abattery** [comment]
TFLite converter can trim the given graph based on input/output tensors for inference use cases. Often it can reduce overall binary size and the reduction rate can be varied depending on the given graph internal structure.

**Comment by le8888e** [comment]
Hi @abattery,

I tried to do inference with .tflite model. 
interpreter.allocate_tensors()   gives this error:
'RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. Node number 3 (FlexSign) failed to prepare.'

According to https://github.com/tensorflow/tensorflow/issues/40157#issuecomment-680798660, seems like SELECT_TF_OPS is not supported by tflite_runtime. There is LSTM layer in my model, do I have to reimplement it with keras?https://github.com/tensorflow/tensorflow/issues/40157#issuecomment-691650953

Thank you

**Comment by abattery** [comment]
To run Select TF ops in android, the android application project requires additional dependency on org.tensorflow:tensorflow-lite-select-tf-ops.

https://www.tensorflow.org/lite/guide/ops_select#android_aar

If you want a trimmed aar, you can follow the below page:
https://www.tensorflow.org/lite/guide/reduce_binary_size

**Comment by le8888e** [comment]
Hi @abattery ，

I'm running on Linux PC.

**Comment by abattery** [comment]
Great. TensorFlow Lite with select TensorFlow ops will be installed automatically with the [TensorFlow pip package](https://www.tensorflow.org/install/pip). You can also choose to only install the [TensorFlow Lite Interpreter pip package](https://www.tensorflow.org/lite/guide/python#install_just_the_tensorflow_lite_interpreter).

**Comment by le8888e** [comment]
Hi @abattery ,
Error
'RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. Node number 3 (FlexSign) failed to prepare.'

seems to caused by tf.sign op in my model since I remove that op, the error is gone.
So do I have to implement this op myself or are there other solutions?

Thank you

**Comment by abattery** [comment]
How did you build your TFLite inference code? Are you using the PIP installer or building natively?

There are two ways to enable tf.Sign op by 1) implementing your own custom op 2) linking Flex delegate.

**Comment by le8888e** [comment]
Hi @abattery ,

I build with pip installer. Could you please offer an instruction on how to Link Flex delegate?

Thank you

**Comment by abattery** [comment]
Flex delegate will be automatically enabled on Linux when you use tf 2.3.0 or later versions only.

**Comment by le8888e** [comment]
OK, I will try tf-nightly 2.4.0. Thank you for your help and patience @abattery

**Comment by le8888e** [comment]
Hi, @abattery,

I update to tf-nightly2.4 try to run inference on .tflitemodel, but  error occurs. Here is the log:

*******************
INFO: TfLiteFlexDelegate delegate: 11 nodes delegated out of 129 nodes with 3 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 3 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 3 nodes delegated out of 24 nodes with 3 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 3 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 3 nodes delegated out of 24 nodes with 3 partitions.

[{'name': 'input_x', 'index': 0, 'shape': array([ 1, 50], dtype=int32), 'shape_signature': array([-1, 50], dtype=int32), 'dtype': <class 'numpy.int32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
[{'name': 'output/y_hat', 'index': 225, 'shape': array([   1, 2363], dtype=int32), 'shape_signature': array([  -1, 2363], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
2020-09-18 18:37:52.699048: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at tensor_array_ops.cc:1035 : Not found: Container __per_step_0 does not exist. (Could not find resource: __per_step_0/_tensor_arraysrnn/bidirectional_rnn/bw/bw/dynamic_rnn/input_0_1)
Traceback (most recent call last):
  File "run_tflite.py", line 60, in <module>
    interpreter.invoke()
  File "/home/ai/anaconda5/envs/tf-nightly2.4/lib/python3.6/site-packages/tensorflow/lite/python/interpreter.py", line 539, in invoke
    self._interpreter.Invoke()
RuntimeError: Container __per_step_0 does not exist. (Could not find resource: __per_step_0/_tensor_arraysrnn/bidirectional_rnn/bw/bw/dynamic_rnn/input_0_1)
	 (while executing 'TensorArrayScatterV3' via Eager)Node number 129 (TfLiteFlexDelegate) failed to invoke.

*******************
Seems like it's the problem with BiLSTM Layer.
The code I define BiLSTM layer is: 

from tensorflow.contrib import rnn

with tf.variable_scope("rnn", reuse=reuse):
    lstm_fw_cell = rnn.BasicLSTMCell(hidden_size)
    lstm_bw_cell = rnn.BasicLSTMCell(hidden_size)

    if self.dropout_keep_prob is not None:
        lstm_fw_cell = rnn.DropoutWrapper(lstm_fw_cell, output_keep_prob=self.dropout_keep_prob)
        lstm_bw_cell = rnn.DropoutWrapper(lstm_bw_cell, output_keep_prob=self.dropout_keep_prob)
    
    outputs, _ = tf.nn.bidirectional_dynamic_rnn(lstm_fw_cell, lstm_bw_cell, embedded_chars, dtype=tf.float32)

*******************

But I refer to info in https://www.tensorflow.org/lite/convert/rnn, bidirectional_dynamic_rnn() is available.

Refer to https://github.com/tensorflow/tensorflow/issues/40157#issuecomment-691650953, if lstm layer was created by keras, this error was solved. So do I have to implement BiLSTM layer in eras?

Thank you

**Comment by abattery** [comment]
Hi @le8888e 

Sorry for encountering the issue.

TensorArrayScatterV3 op is currently not supported by either TensorFlow Lite builtin op set or Flex delegate. Unfortunately, the above TF graph should be rewritten by replacing the TensorArray with a 1-D TensorList through V2 control flow ops or concatenation operators if possible instead.

When you are creating a TF graph, could you invoke the following call before the TF graph creation part?

https://www.tensorflow.org/api_docs/python/tf/compat/v1/enable_control_flow_v2

Best regards,

**Comment by le8888e** [comment]
Hi @abattery ,

I have tried to invoke 'tf.enable_control_flow_v2()'  before I create my TF graph. But I cannot converted trained .pb to .tflite. Here is the log:
![log](https://user-images.githubusercontent.com/34771253/93551389-4bcc8680-f9a0-11ea-8057-9e521f031c30.jpeg)
Without 'tf.enable_control_flow_v2()', I can finish converting but collapse in inference like I mentioned before.

I will try to replace tf.nn.bidirectional_dynamic_rnn() by tf.lite.experimental.nn.bidirectional_dynamic_rnn() and let you know the result.

Thank you

**Comment by le8888e** [comment]
Hi @abattery,

I try to replace tf.contirb.cnn.BasicLSTMCell() with tf.lite.experimental.nn.TfLiteLSTMCell()
and
tf.nn.bidirectional_dynamic_rnn() with tf.lite.experimental.nn.bidirectional_dynamic_rnn()
Then retrain my model. My tf version to train is tf 1.15.0

Error occurs:
AttributeError: module 'tensorflow._api.v1.lite.experimental.nn' has no attribute 'TfLiteLSTMCell'

Seems like tf.lite.experimental  is not supported by tf 1.* 
Maybe I have to transfer my code to tf 2.* or keras : )

**Comment by le8888e** [comment]
Hi @abattery ,

I implement my BiLSTM layer by Keras and FINALLY convert to .tflite model and successfully do inference. 

NEW ISSUE:
The output logits of .pb and .tflite model is different, but both of they get the same classification category. Should the output of .pb and .tflite be exactly the same? Below are my codes for conversion and inference
[convert.txt](https://github.com/tensorflow/tensorflow/files/5253215/convert.txt)
[inference.txt](https://github.com/tensorflow/tensorflow/files/5253216/inference.txt)

Thank you

**Comment by le8888e** [comment]
hi @abattery ,

After implementing BiLSTM by Keras, I successfully convert and inference .tflite model.
I want to serve .tflite model by tf-serving  on PC  with python api. Is  this feasible and is there any guidance for this?

THANK YOU

**Comment by abattery** [comment]
As you already asked the question to the tf-serving project, let's see their answers at https://github.com/tensorflow/serving/issues/1736.

**Comment by le8888e** [comment]
Hi @abattery ,

I was building tf-nightly viac pip. Would XNNPACK built by default? And how can I check it?

Thank you

**Comment by Saduf2019** [comment]
@le8888e 
serving requires model asset to be a saved model, please create a new issue for any new questions. If tgis resolves your issue please move this to closed status.

**Comment by abattery** [comment]
@multiverse-tf Chao, could you answer @le8888e 's comment at https://github.com/tensorflow/tensorflow/issues/43270#issuecomment-696582237?

**Comment by multiverse-tf** [comment]
> Hi @abattery ,
> 
> I was building tf-nightly viac pip. Would XNNPACK built by default? And how can I check it?
As for "XNNPACK built by default", do you mean by "applying XNNPACK by default" in the interpreter itself? If yes, this hasn't been enabled yet in tf-nightly build. So use XNNPACK delegate, pls follow this guide: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/xnnpack/README.md#using-xnnpack-engine-with-tensorflow-lite-interpreter

> Thank you

**Comment by Saduf2019** [comment]
@le8888e
Please update, if this issue can be moved to closed status.

**Comment by le8888e** [comment]
@Saduf2019 ,
This issue can be closed, thank you.

**Comment by Saduf2019** [comment]
Moving the issue to closed status with confirmation
