### ISSUE TITLE
My doc build is picking up methods not in the advertised API

### ISSUE THREAD

**Issue by joelberkeley-secondmind** [tensorflow/tensorflow#43278]
## Description of issue (what needs changing):

This is a bit of a difficult issue to pin down. I have a class that extends `tf.Module`, and I'm trying to build the documentation for that class using sphinx (with a couple of extensions). When I build it, I'm seeing a large number of methods in my doc build that aren't advertised in the [`tf.Module` docs](https://www.tensorflow.org/api_docs/python/tf/Module). (These are mostly inherited from the superclasses of `tf.Module`: `Autotrackable` and `Trackable`, but that might not be too important here.)

I'd like to be able to show those parts of the `tf.Module` API that are intended for use by client code (including those with leading underscores that are intended for use in subclasses, i.e. 'protected' methods), and to omit those that aren't. It's not clear to me what parts of these tensorflow classes are indeed part of the public/protected API. It's also not clear to me, if the public API only includes what is shown on the website, how I can omit the rest from my doc build.

The simplest suggestion for me would be for tensorflow to remove the docstrings for all fully private functionality, but that's a lot of work, and I assume you use those docstrings.

You may be wondering why I'm raising this as an issue with tensorflow. The reason is that with the current structure of docstrings in tensorflow, I'm finding it difficult to manage my downstream doc build. Does the tensorflow team have a clear and consistent way of delineating fully private functionality, and if not, is there anything that can be done to improve docstring usability in this regard?

**Comment by MarkDaoust** [comment]
> what parts of these tensorflow classes are indeed part of the public/protected API.

The rule is, if it's on tensorflow.org it's public. otherwise it's not.

The code that hides many of those methods is here:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docs/generate2.py#L177
