### ISSUE TITLE
 Failed to run on the given Interpreter: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.     Node number 62011 (FlexSize) failed to prepare.

### ISSUE THREAD

**Issue by dikshantjn** [tensorflow/tensorflow#43277]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip install tf-nightly
- TensorFlow version (or github SHA if from source):
2.4.0-dev20200916

**Provide the text output from tflite_convert**
For **Android Studio project** that gives the following error:

java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
    Node number 62011 (FlexSize) failed to prepare.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:163)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:360)
        at edu.ilab.covid_id.localize.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:202)
        at edu.ilab.covid_id.ir.ConnectFlirActivity$7.run(ConnectFlirActivity.java:673)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```
# Copy and paste here
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Here is the colab used to convert the saved model to tflite**
https://colab.research.google.com/drive/1_9l_DcyNuVV1NxU3PsmSMjWeI9nTEwNS?usp=sharing

**Here is the drive with the saved model to tflite**
https://drive.google.com/drive/folders/1MCvDti2ygukqw6fGE18WpnFOSzR_AanF?usp=sharing

**Here is the java code which uses the tflite model**
[ConnectFlirActivity.zip](https://github.com/tensorflow/tensorflow/files/5234536/ConnectFlirActivity.zip)

**Comment by abattery** [comment]
I think the above android application does not have Select TF ops. You can follow the below guides to add the Select TF ops:

https://www.tensorflow.org/lite/guide/ops_select#android_aar
https://www.tensorflow.org/lite/guide/reduce_binary_size

**Comment by shivali06** [comment]
No, it has TF ops
