### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tensorflow==1.14.0

### ISSUE THREAD

**Issue by ChrisDongWooKim** [tensorflow/tensorflow#43289]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Catalina version 10.15.5, Windows 10 64bit
- TensorFlow installed from (source or binary): pip install tensorflow==1.14.0
- TensorFlow version: 1.14.0
- Python version: 3.7.* (64bit)
- Installed using virtualenv? pip? conda?: pip and conda
- pip version: I have used 19.1.1 and 20.2.3

**Describe the problem**
I have created virtual environments using Anaconda on both OS(mac and windows). Then I tried to install all the modules on that. but I have faced problems that install specific tensorflow version 1.14.0. My pip only supports those version below:
(from versions: 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)

I also tried to install tensorflow using commands below:
conda install tensorflow==1.14.0

but it wasn't worked. my source can not import tensorflow module.

how can I install that version?

**Provide the exact sequence of commands / steps that you executed before running into the problem**
pip install tensorflow==1.14.0
pip install tensorflow-gpu==1.14.0

**Any other info / logs**
above commands always occurs this error below:
ERROR: Could not find a version that satisfies the requirement tensorflow==1.14.0 (from versions: 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow==1.14.0

**Comment by Saduf2019** [comment]
@ChrisDongWooKim 
Could you please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/42724#issuecomment-683311743) and let us know.
You may also refer to similar issues:
#34302 [upgrade pip] [link](https://stackoverflow.com/questions/63059979/cannot-install-tensorflow-1-x) [link](https://forum.rasa.com/t/could-not-find-a-version-that-satisfies-the-requirement-tensorflow-1-15-0/21509) [please verify these packages in case the error still persist]


Also is ther any particular reason to be using 1.14 as its an older version and later versions are available, would you want to try with tf 1.15 or 2.x and let us know.

**Comment by ChrisDongWooKim** [comment]
@Saduf2019 
Thx for answer :D
I already tried those things before posting this question.
I have used several pip versions to install TensorFlow 1.14.0 but it didn't work at all. I guess it isn't related to pip version.
And also my pip only supports version 2.2.0 to 2.3.0.

I should use a specific TensorFlow version. cuz I deployed this ML model using the newest TensorFlow version before but it didn't work as same as on tensorflow 1.14.0.

**Comment by Saduf2019** [comment]
@ChrisDongWooKim 
We have support for tf 1.15 and 2.x,please upgrade and let us know if you still face any issues.

**Comment by ChrisDongWooKim** [comment]
@Saduf2019 
Very thx to helping me out :)

Actually, I have already tried to install various versions of tf such as 1.1.3, 1.1.5, and everything on Mac OS but it didn't work at all.
However, I solved the problem that I faced on Windows OS. I re-created my virtual environments based python version 3.7.* and then It worked to install tf 1.14.0 version. 
but the thing is that My Mac doesn't support installing tf 1.14.0 even on the same python version.
I guess I should use my windows computer instead of.

**Comment by gowthamkpr** [comment]
@ChrisDongWooKim As mentioned above, by switching to python 3.7, tensorflow 1.14 installation was possible on Windows 10. 
Now that you are facing a different problem, please create a new issue as we can track these issues separately. Thanks!
