### ISSUE TITLE
There is a bug about tf/keras/Sequential#fit()

### ISSUE THREAD

**Issue by zjzh** [tensorflow/tensorflow#43298]
For "tf.keras.Sequential.fit" API, in TF2.1, documentation said that "fit_generator" is deprecated and "fit" support generator. But actually, in TF2.0, I find that "fit" also support generator. So it means that the deprecated information mislead to users that TF2.0 "fit" API cannot support the function of "fit_generator" API.

**Comment by bhack** [comment]
Yes but the meaning is the `fit_generator` is deprecated starting from TF >=2.1. 
It is just a warning to port your code cause at some point it will be removed.

**Comment by ymodak** [comment]
The warnings are removed from the nightly version of documentation.
See https://www.tensorflow.org/api_docs/python/tf/keras/Sequential?version=nightly#fit_generator

**Comment by bhack** [comment]
@ymodak But still deprecated right? https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training.py#L1795-L1798

**Comment by ymodak** [comment]
@bhack That's correct. 
https://www.tensorflow.org/api_docs/python/tf/keras/Sequential#deprecated_5
