### ISSUE TITLE
How to evluate a Model accuracy

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#43294]
Since there is mentioned to evaluate [Model accuracy](https://www.tensorflow.org/lite/performance/post_training_quantization#model_accuracy) I wonder how to use it for a evaluation, please do you have an example (sample) how to evaluate it?

Thank you.

**Comment by bhack** [comment]
It seems to me a valid Documentation/Tutorial request.

**Comment by amahendrakar** [comment]
@peter197321,
Could you please take a look at these evaluation examples and let us know if it helps. 
 - [Object Detection evaluation](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/evaluation/tasks/coco_object_detection)
- [Image Classification evaluation](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/evaluation/tasks/imagenet_image_classification)

Thanks!

**Comment by peter197321** [comment]
Is there anything to eval accuracy for Segmentation purposes?

**Comment by bhack** [comment]
@amahendrakar Also what I meant is that users are pointed directly to https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/evaluation/tasks from the docs. 
I suppose that we need a main Readme in the root or a similar solution.

**Comment by peter197321** [comment]
that would be helpful ...

**Comment by Harsh188** [comment]
Hey! I'd like to contribute to this. I'm gonna get started on creating a README.md for [`tools/evaluation/tasks/`](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/evaluation/tasks). I'm a little busy at the moment but I'll make sure to have an active PR open by this weekend.

**Comment by Harsh188** [comment]
@bhack should I create the `README.me` under `tools/evaulation` or `tools/evaluation/tasks/`?

**Comment by bhack** [comment]
I think It Is ok

**Comment by Harsh188** [comment]
> I think It Is ok

Sorry, what do you mean?

**Comment by bhack** [comment]
> @bhack should I create the `README.me` under `tools/evaulation` or `tools/evaluation/tasks/`?

**Comment by bhack** [comment]
Currently the documentation link is `https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/evaluation/tasks` so it would be nice to have a general `Readme.md` there

**Comment by Harsh188** [comment]
@peter197321 [Tools for Evaluation](https://www.tensorflow.org/lite/performance/delegates#tools_for_evaluation) was added recently which provides a great explanation of the evaluation tools.

**Comment by peter197321** [comment]
Thank you @Harsh188

**Comment by Harsh188** [comment]
I think this issue can be closed.

**Comment by ymodak** [comment]
Closing this issue in the light of Tools for Evaluation doc update. Feel free to reopen if necessary. Thanks!
> @peter197321 [Tools for Evaluation](https://www.tensorflow.org/lite/performance/delegates#tools_for_evaluation) was added recently which provides a great explanation of the evaluation tools.
