### ISSUE TITLE
Arguments to max_pool are missing correspondance

### ISSUE THREAD

**Issue by adam-dziedzic** [tensorflow/tensorflow#43295]
https://github.com/tensorflow/tensorflow/blob/590d6eef7e91a6a7392c8ffffb7b58f2e0c8bc6b/tensorflow/python/ops/nn_ops.py#L3820

I have a tensor with shape (N,W,C). When I want to do max_pool1d with stride 2 for W, and then the strides with shape [1,2,1] throws an error and it indicates that the W dimension in the strides parameter is on the first position, so the strides parameter in this case must be [2,1,1]. This should be either changed so that it reflects the shape (N,W,C), or at  least described in the documentation.

```
import tensorflow as tf
import unittest

class TestMethods(unittest.TestCase):

    def test_max_pool(self):
        num_classes = 10
        print('num_classes: ', num_classes)
        batch_size = 2
        y_output = tf.constant(value=[[.1, .3, .2, .0, .8, .4, .1, .1, .1, .2],
                                      [.1, .9, .2, .0, .1, .4, .1, .1, .1, .2]])
        input = tf.reshape(tensor=y_output, shape=[batch_size, num_classes, 1])
        print('input shape: ', input.shape)
        y_max = tf.nn.max_pool1d(input=input, ksize=[num_classes, 1, 1], strides=[1, 1, 1], padding='VALID', data_format='NWC')
        print('y_max: ', y_max)
        y_max = tf.reshape(tensor=y_max, shape=[batch_size])
        print('y_max: ', y_max)


if __name__ == "__main__":
    tf.compat.v1.enable_eager_execution()
    unittest.main()
```

Results:
```
Testing started ...

Process finished with exit code 0
num_classes:  10
input shape:  (2, 10, 1)

Ran 1 test in 0.031s

OK
y_max:  tf.Tensor(
[[[0.8]]

 [[0.9]]], shape=(2, 1, 1), dtype=float32)
y_max:  tf.Tensor([0.8 0.9], shape=(2,), dtype=float32)
```

**Comment by ravikyram** [comment]
@adam-dziedzic 

I tried reproducing the issue in colab with TF version 2.3,nightly version and i am seeing the error (`AttributeError: module '__main__' has no attribute '/root/'`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/4d746b19e567397f62880b731df7b689/untitled380.ipynb).Thanks!
