### ISSUE TITLE
Kernel crash with complex matrices on Windows

### ISSUE THREAD

**Issue by liuhenry** [tensorflow/tensorflow#43297]
Hello, I'd like to raise this issue again as I am encountering the same problem on TF 2.3.0.

The original issue at https://github.com/tensorflow/tensorflow/issues/40414 attempts to replicate using Colab, which isn't running Windows.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10.0.18362**
- TensorFlow installed from (source or binary): **Binary (pip)**
- TensorFlow version (use command below): **2.3.0 (v2.3.0-rc2-23-gb36436b087)**
- Python version: **3.8.5**
- CUDA/cuDNN version: **10.1.120/7.6.5 (also tried 10.1.243/7.6.5)**
- GPU model and memory: **GeForce RTX 2080 Ti, 11265 MB**

**Describe the current behavior**

Multiplying two matrices of complex type (values themselves can be real) with either `adjoint_a=True` or `adjoint_b=True` results in the following crash. It also seems to crash when running `eig`. This was reproduced on both TF 2.3.0 and 2.2.0, but works on 2.1.0. It also seems to be working on Linux.

I tried doing a fresh install of CUDA with CUDA 10.1.120 and 10.1.243. In both cases the [MNIST tutorial example](https://www.tensorflow.org/tutorials/quickstart/beginner) runs with no problems.

**Standalone code to reproduce the issue**
```
import tensorflow as tf
a = tf.constant([[1, 0], [0, 1]], dtype=tf.complex64)
tf.linalg.matmul(a, a)  # No issues
tf.linalg.matmul(a, a, adjoint_a=True)  # Crash
```

**Other info / logs**:

```
>>> tf.linalg.matmul(a, a)
2020-08-25 18:30:03.799456: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
<tf.Tensor: shape=(2, 2), dtype=complex64, numpy=
array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]], dtype=complex64)>
>>> tf.linalg.matmul(a, a, adjoint_a=True)
2020-08-25 18:30:07.982835: E tensorflow/stream_executor/cuda/cuda_driver.cc:951] could not synchronize on CUDA context: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure :: 0x00007FF991B9B115     tensorflow::CurrentStackTrace
0x00007FF9918E989E      tensorflow::CostGraphDef_Node::set_is_final
0x00007FF991A91D7E      stream_executor::StreamExecutor::SetDeviceSharedMemoryConfig
0x00007FF98F622C16      tensorflow::StepStats::internal_default_instance
0x00007FF98F634444      google::protobuf::RepeatedPtrField<tensorflow::InterconnectLink>::Add
0x00007FF9774EF867      std::vector<tensorflow::DtypeAndPartialTensorShape,std::allocator<tensorflow::DtypeAndPartialTensorShape> >::operator=
0x00007FF9774CA7AB      absl::lts_2020_02_25::Span<tensorflow::Tensor const >::end
0x00007FF9774431BF      TFE_TensorHandleResolve
0x00007FF9773E0A33      TFE_Py_TensorShapeSlice
0x00007FF9773DE29A      std::_Tree<std::_Tmap_traits<std::array<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,0>,tensorflow::monitoring::CounterCell,std::less<std::array<std::basic_string<char,std::char_traits<char>,std::allocator<char>
0x00007FF9A51CA3D6      PyList_New
0x00007FF9A51F5626      Py_CheckFunctionResult
0x00007FF9A51F7954      PyEval_EvalFrameDefault
0x00007FF9A51F596E      Py_CheckFunctionResult
0x00007FF9A51F7954      PyEval_EvalFrameDefault
0x00007FF9A51F2EF8      PyEval_EvalCodeWithName
0x00007FF9A51F5C66      Py_CheckFunctionResult
0x00007FF9A51F801E      PyEval_EvalFrameDefault
0x00007FF9A51F3D7D      PyFunction_Vectorcall
0x00007FF9A525FAF9      PyEval_GetFuncDesc
0x00007FF9A525F8DD      PyEval_GetFuncDesc
0x00007FF9A51E7DE4      PyObject_Repr
0x00007FF9A5181E2F      PyFile_WriteObject
0x00007FF9A5181B1B      PyFile_WriteString
0x00007FF9A51EB200      PyFloat_AsDouble
0x00007FF9A51E401E      PyObject_CallFunctionObjArgs
0x00007FF9A51F9E70      PyEval_EvalFrameDefault
0x00007FF9A51F2EF8      PyEval_EvalCodeWithName
0x00007FF9A52038DF      PyEval_EvalCodeEx
0x00007FF9A520383D      PyEval_EvalCode
0x00007FF9A5203526      PyArena_New
0x00007FF9A52034B5      PyArena_New
0x00007FF9A5365760      PyRun_InteractiveOneObject
0x00007FF9A5365373      PyRun_InteractiveLoopFlags
0x00007FF9A53651B1      PyRun_AnyFileExFlags
0x00007FF9A52F917D      Py_FatalError
0x00007FF9A526428F      Py_RunMain
0x00007FF9A5264141      Py_RunMain
0x00007FF9A5264126      Py_Main
0x00007FF9A52640DD      Py_Main
0x00007FF7C5F41268      (unknown)
0x00007FF9F1B57BD4      BaseThreadInitThunk
0x00007FF9F324CE51      RtlUserThreadStart

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\qulab\Anaconda3\envs\tf2-3\lib\site-packages\tensorflow\python\framework\ops.py", line 1009, in __repr__
    self.shape, self.dtype.name, numpy_text(self, is_repr=True))
  File "C:\Users\qulab\Anaconda3\envs\tf2-3\lib\site-packages\tensorflow\python\framework\ops.py", line 225, in numpy_text
    text = repr(tensor._numpy()) if is_repr else str(tensor._numpy())
  File "C:\Users\qulab\Anaconda3\envs\tf2-3\lib\site-packages\tensorflow\python\framework\ops.py", line 1031, in _numpy
    six.raise_from(core._status_to_exception(e.code, e.message), None)  # pylint: disable=protected-access
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: GPU sync failed
```

**Comment by ahtik** [comment]
I can reproduce. What's interesting is that it's crashing when trying to print the variable (like the python console does by default).
So
```
python -c "import tensorflow as tf; print('00000'); a = tf.constant([[1, 0], [0, 1]], dtype=tf.complex64); print('AAAAA'); tf.linalg.matmul(a, a); print('BBBBB'); tf.linalg.matmul(a, a, adjoint_a=True); print('DONE')"
``` does not crash/prints "DONE" (but still hangs, does not exit...) but
```
python -c "import tensorflow as tf; print('00000'); a = tf.constant([[1, 0], [0, 1]], dtype=tf.complex64); print('AAAAA'); print(tf.linalg.matmul(a, a)); print('BBBBB'); print(tf.linalg.matmul(a, a, adjoint_a=True)); print('DONE')"
``` does crash with `GPU sync failed`.

RTX 2070 SUPER, Windows 10, CUDA 10.1, python 3.8.5, TF 2.3.0.

**Comment by ahtik** [comment]
I tried now with tf_nightly-2.4.0.dev20200915 and there it works fine. Requires CUDA 11.0 though.

**Comment by Saduf2019** [comment]
@liuhenry 
I ran your code on tf 2.3 and nightly and do not face the error reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/68d0865435a9a2a101f70594094c814b/untitled416.ipynb).
Please refer to below issues for the error log shared above:
[link](https://stackoverflow.com/questions/51112126/gpu-sync-failed-while-using-tensorflow), [link2](https://github.com/tensorflow/tensorflow/issues/1450) [try to reduce gpu memory], #37942

**Comment by liuhenry** [comment]
@ahtik Thanks for the note! I will install CUDA 11 later and try that out.

@Saduf2019 Thanks for your response as well! Do you mean that you tested this on Colab or did it also work on a Windows machine? The issue will not reproduce in Colab since it seems to specifically be related to the interaction of TF and CUDA on windows, but is working fine in linux. RE: memory limitations, I've tried with enabling memory growth, but I don't think this is relevant given that the problem shows up on a single 2x2 matrix.

**Comment by jvishnuvardhan** [comment]
@liuhenry Is this still an issue? I don't have access to GPU on Windows. But, i tested on cpu and kernel didn't crash. Please test it on GPU and let us know whether this still an issue for you. Thanks!
