### ISSUE TITLE
Should we remove deprecated and ignored field 'version' in graph.proto

### ISSUE THREAD

**Issue by rfan-debug** [tensorflow/tensorflow#43301]
We noticed that the `version` field in `graph.proto` has been deprecated (since 5 years ago). When we tried to generate `GraphDef` scala code by `sbt-protoc` from this proto file, it produced annoying "deprecation" warnings during the compilation stage. 

Should we remove it from tensorflow's codebase?

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/graph.proto#L24-L27

According to the description in the codebase:
>  // Deprecated single version field; use versions above instead.  Since all
    // GraphDef changes before "versions" was introduced were forward
    // compatible, this field is entirely ignored.

This field seems to be completely not used, no matter old or new versions. 

We appreciate any feedbacks. Thanks!

**Comment by rfan-debug** [comment]
Hey, @ymodak thanks for assigning correct tags on this issue. Is there any update? 

I think we just need to remove the deprecated `version` field since it is not used at all.

**Comment by mihaimaruseac** [comment]
I don't think we can remove it until we are sure there is no client that expects to see it in the proto. Otherwise, said client will get a bad parse, segfault or exhibit other unwanted behavior.

**Comment by ymodak** [comment]
Closing this issue for now. Feel free to revisit if necessary. Thanks!
