### ISSUE TITLE
changes its APIs quite often

### ISSUE THREAD

**Issue by francogrex** [tensorflow/tensorflow#43302]
There are a lot of very good projects by top international experts (think Google) that are dropping Tensorflow because it changes its APIs quite often we shouldn't expect users to have always a GPU. Please consider this failure.

**Comment by ymodak** [comment]
Thanks for your feedback. For users interested in using TF with gpu, tpu can try using [Google Colab](https://colab.sandbox.google.com/notebooks/intro.ipynb#recent=true). The google colab also hosts latest TensorFlow version thus saves the user from the hassle of setting up the environment, All you need is a good internet connection.

**Comment by mihaimaruseac** [comment]
Closing as there is no real issue to solve.

Our API keeps evolving based on user studies and always improving. If there is actionable feedback, please open new issue.
