### ISSUE TITLE
tf.nn.softmax_cross_entropy_with_logits output on multichannel continuous targets

### ISSUE THREAD

**Issue by sri9s** [tensorflow/tensorflow#43309]
Hi,

How does the tf.nn.softmax_cross_entropy_with_logits work for a target that is continuous with C channels,
eg - HxWxC, they are not soft targets (values across channels dont add up to 1) with values ranging between 0 and 1.

Thanks in advance

**Comment by bhack** [comment]
This is a support question for https://stackoverflow.com/questions/tagged/tensorflow
Please close this ticket and submit your question there.

Thanks
