### ISSUE TITLE
Building Tensorflow using non-default GCC fails with /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found and further errors

### ISSUE THREAD

**Issue by jakublipinski** [tensorflow/tensorflow#43311]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
**SLURM cluster node: Linux gnode028 3.10.0-1062.12.1.el7.x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux**

- TensorFlow version:
**TensorFlow v2.3.0**

- Python version:
**Python 3.8.0 complied from source**

- Bazel version (if compiling from source):
**bazel 3.1.0 compiled from source**

- GCC/Compiler version (if compiling from source):
**gcc (GCC) 7.3.0 compiled from source**

- CUDA/cuDNN version:
**CUDA 10.2**

- GPU model and memory:
**Tesla K20m**

**Describe the problem**
I'm trying to compile Tensorflow on a SLURM cluster machine where the default version of GCC is outdated (`4.8.5`) and cannot be upgraded. The only solution is to use newer version of GCC (in my case `7.3.0`)  installed as user. However, when using non-default GCC the compilation procedure ends up with the following error:

`bazel-out/host/bin/external/flatbuffers/flatc: /lib64/libstdc++.so.6: version GLIBCXX_3.4.20 not found (required by bazel-out/host/bin/external/flatbuffers/flatc)`

From what I understand the root of the problem is the fact that `Bazel` links to the default libraries from hardcoded `/lib64/libstdc++` instead of using the libraries from non-default gcc. The problem has been reported frequently by many different users. I tried all the solutions provided in multiple issues (https://github.com/bazelbuild/bazel/issues/4510, https://github.com/tensorflow/tensorflow/issues/38718, https://github.com/tensorflow/tensorflow/issues/26826), implemented many of them but eventually failed to finish compilation successfully. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
My goal is to create a comprehensive instructions for all the people facing this issue. I created a gist file listing all the steps I followed (including compiling `Bazel` from source): https://gist.github.com/jakublipinski/40ba68994fe0092600a05b0060e7d445

After all the steps my setup consists of `Python 3.8`, `GCC 7.3.0`, `Bazel 3.1.0` and `Binutils 2.34`. All these packages are installed locally as user.

**Any other info / logs**
`Bazel 3.1.0` is compiled from source using the following command:
```
export GCC_HOST_COMPILER_PATH=$HOME/gcc/bin/gcc
export GCC_HOST_COMPILER_PREFIX=$HOME/gcc/bin
export CXX=$HOME/gcc/bin/gcc
export CC=$HOME/gcc/bin/gcc
export LD_LIBRARY_PATH=$HOME/gcc/lib64
export LDFLAGS="-L$HOME/gcc/lib -L$HOME/gcc/lib64"
export CXXFLAGS="-L$HOME/gcc/lib -L$HOME/gcc/lib64"

env BAZEL_LINKOPTS=-static-libstdc++:-static-libgcc BAZEL_LINKLIBS=-l%:libstdc++.a:-lm bash ./compile.sh
mkdir $HOME/bin && cp output/bazel $HOME/bin
```

The TensorFlow build process initiated by:
```
export PATH=~/bin:$PATH
export GCC_HOST_COMPILER_PATH=$HOME/gcc/bin/gcc
export GCC_HOST_COMPILER_PREFIX=$HOME/gcc/bin
export CXX=$HOME/gcc/bin/gcc
export CC=$HOME/gcc/bin/gcc
export LD_LIBRARY_PATH=$HOME/gcc/lib64
export LDFLAGS="-L$HOME/gcc/lib -L$HOME/gcc/lib64"
export CXXFLAGS="-L$HOME/gcc/lib -L$HOME/gcc/lib64"

env BAZEL_LINKOPTS=-static-libstdc++:-static-libgcc BAZEL_LINKLIBS=-l%:libstdc++.a:-lm BAZEL_CXXOPTS=-std=gnu++0x bazel build //tensorflow/tools/pip_package:build_pip_package --action_env="LD_LIBRARY_PATH=${LD_LIBRARY_PATH}" --verbose_failures
```

fails with:

```
ERROR: /home/users/user/tensorflow/tensorflow/lite/toco/BUILD:439:1: Linking of rule '//tensorflow/lite/toco:toco' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/users/user/.cache/bazel/_bazel_user/77a387926d2bc2a010179601b7d63fc2/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/home/users/user/gcc/lib64 \
    PATH=/home/users/user/bin:/home/users/user/tensorflow/venv/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/slurm/bin:/bin:/opt/slurm/bin:/bin \
    PWD=/proc/self/cwd \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc @bazel-out/host/bin/tensorflow/lite/toco/toco-2.params)
Execution platform: @local_execution_config_platform//:platform
bazel-out/host/bin/_solib_local/_U_S_Stensorflow_Slite_Stoco_Ctoco___Utensorflow/libtensorflow_framework.so.2: undefined reference to `std::allocator<long long>::allocator()'
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 10.872s, Critical Path: 1.07s
INFO: 5 processes: 5 local.
FAILED: Build did NOT complete successfully
```

I allow myself to cc @krafczyk and @soporteCluster as they were reporting similar issues and may provide some insight.

I'm ready to try different solutions and provide more info. I really want this issue to be solved once and for all. I understand that the root cause may be related to how Bazel operates. Anyway, the issue affects many TensorFlow users. Let's provide some workaround for them. Thanks in advance for all suggestions. I promise to test them all.

**Comment by bhack** [comment]
I don't think that modern TF versions (like your 2.3.0) could be built with gcc<5.
This is the official list of the tested configurations:
https://www.tensorflow.org/install/source#tested_build_configurations

**Comment by jakublipinski** [comment]
@bhack thanks for your comment. I updated the issue to clarify that I use `GCC 7.3.0` installed as user and that causes the problem.

**Comment by bhack** [comment]
Just to be sure:
Have you already  run `bazel clean --expunge` before you final configuration build?

**Comment by jakublipinski** [comment]
@bhack Yes. I do `bazel clean --expunge` before testing any new build settings

**Comment by soporteCluster** [comment]
Hi,
I compiled it following the steps that i have commented below:
https://github.com/tensorflow/tensorflow/issues/38718#issuecomment-624681019

I had to install bazel again with that configuration and then build Tensorflow.
I made the compilation using the following environment variables:
PATH=/share/apps/curl/bin/curl:$PATH
LD_LIBRARY_PATH=/share/apps/curl/lib/:$LD_LIBRARY_PATH 
PATH=/share/apps/git/bin/:$PATH
PATH=/share/apps/binutils/binutils-2.34/bin/:$PATH
LD_LIBRARY_PATH=/share/apps/binutils/binutils-2.34/lib/:$LD_LIBRARY_PATH
I have all the programs installed in /share/apps because it is a Cluster HPC.

**Comment by jakublipinski** [comment]
@soporteCluster Your comment (https://github.com/tensorflow/tensorflow/issues/38718#issuecomment-624681019) was very helpful for me. I followed all your steps. Unfortunately, they don't work for me. What TF and CUDA version did you use?

**Comment by jakublipinski** [comment]
I finally solved this issue. The detailed build instruction is available at: https://gist.github.com/jakublipinski/40ba68994fe0092600a05b0060e7d445

**Comment by AIWintermuteAI** [comment]
@jakublipinski Legend!
Thank you so much for leaving the solution to the issue.
This helped me to compile tensorflowlite_flex delegate 2.16.1 with GCC 11 and non-default glibc / libstdc++.

**Comment by jakublipinski** [comment]
@AIWintermuteAI haha, I spent many days figuring it out. I'm glad it helped someone. Thanks for the note.

**Comment by aiwithhamza** [comment]
Helloi friends, I am facing incompatibility between the version of the C++ standard library (libstdc++) required by  TensorFlow installation==1.13.1, GCC version 7.5.0 installed. Looking for help thanks

**Comment by AIWintermuteAI** [comment]
@aiwithhamza I think you are better off opening a new issue, this one is marked as solved.
