### ISSUE TITLE
Undocumented NotFoundError occurs when using tf.io.gfile.glob() to retrieve files in a non-existent directory

### ISSUE THREAD

**Issue by 18jeffreyma** [tensorflow/tensorflow#43319]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Chrome OS Linux 5.4.40-04224-g891a6cce2d44
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/a
- TensorFlow installed from (source or binary): Installed from source (pip3 install tensoflow)
- TensorFlow version (use command below): v2.3.0-rc2-23-gb36436b087 2.3.0
- Python version: 3.7
- Bazel version (if compiling from source): N/a
- GCC/Compiler version (if compiling from source): N/a
- CUDA/cuDNN version: N/a
- GPU model and memory: N/a

**Describe the current behavior**
When globbing files in a directory that does not exist, a non-documented tf.errors.NotFoundError is thrown if we try to wildcard glob files in a non-existent directory. This is not currently documented [here](https://www.tensorflow.org/api_docs/python/tf/io/gfile/glob).

**Describe the expected behavior**
We expect that either a ValueError should be thrown, or the an empty list returned (since no files were matched).

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```
import tensorflow as tf
files = tf.io.gfile.glob("non_existent_dir/*")
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Issue was first discovered through [this PR](https://github.com/tensorflow/tfx/pull/2339#discussion_r490576170) for TFX, where we are expecting a ValueError instead of a NotFoundError.

**Comment by bhack** [comment]
I think that you can open this in https://github.com/tensorflow/io

**Comment by 18jeffreyma** [comment]
@bhack seems like this is the correct place to put this, as previous issues about tf.io.gfile.glob were also opened here

https://github.com/tensorflow/tensorflow/issues/37758

**Comment by bhack** [comment]
Yes sorry the code is in this repo. I have quickly read tfio instead of tf.io

**Comment by 18jeffreyma** [comment]
specifically, looking at stack traces, the tf.errors.NotFoundError is thrown at this line:

https://github.com/tensorflow/tensorflow/blob/4f3a8d84cf74f4f276bfd378e60efe5a18a6c30a/tensorflow/python/lib/io/file_io.py#L409

**Comment by ravikyram** [comment]
I have tried in colab with TF version [2.3](https://colab.research.google.com/gist/ravikyram/16fd1051c7c8131f7f859fd67f02d036/untitled376.ipynb),[nightly ](https://colab.research.google.com/gist/ravikyram/6cd3e6a5984c26da393079210fb8ef88/untitled378.ipynb) versions and was able to reproduce the issue.Thanks!

**Comment by 18jeffreyma** [comment]
Opened a PR with a fix for this ([PR#43333](https://github.com/tensorflow/tensorflow/pull/43333)), not sure if this is an error we could be fixing at a deeper level, but proposed changes are linked.

**Comment by mihaimaruseac** [comment]
I would say that the error should be returned instead of silently failing

```
[test] λ mkdir a b c
[test] λ ls
a  b  c
[test] λ ls d/*
ls: cannot access 'd/*': No such file or directory
```

**Comment by 18jeffreyma** [comment]
PR to fix this issue has been merged, thanks again!
