### ISSUE TITLE
vectorized_map fails if function contains an abs of a complex128

### ISSUE THREAD

**Issue by charmasaur** [tensorflow/tensorflow#43322]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.15.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.7.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
`vectorized_map` throws an `AssertionError` if the body contains a `tf.abs` of a `complex128` tensor.

**Describe the expected behavior**
No exception should be thrown.

**Standalone code to reproduce the issue**
```
import tensorflow as tf
tf.vectorized_map(tf.abs, tf.cast([0, 1], dtype=tf.complex128))
```
(also see https://colab.research.google.com/drive/1ExIw0N92bHpgWxwRONmeP24BWCzWG3QL?usp=sharing)

**Other info / logs**
I think the issue is that the `ComplexAbs` gets converted to a straight call to `math_ops.complex_abs` (https://github.com/tensorflow/tensorflow/blame/master/tensorflow/python/ops/parallel_for/pfor.py#L2731), which by default returns a `float32` (instead of deciding the dtype based on the dtype of the argument). I believe it could be fixed just by changing that call to `math_ops.abs`.

**Comment by Saduf2019** [comment]
@charmasaur 
I ran the code shared on tf nightly and do not face any issues, please refer to [gist here](https://colab.research.google.com/gist/Saduf2019/7cfac81f581cfde17c1feaf3c0629a9c/untitled416.ipynb) and let us know.

**Comment by charmasaur** [comment]
Sorry, I didn't think to check nightly.

In any case, while the original code I gave does indeed work on nightly, the issue is still there: changing `[0]` to `[0, 1]` causes the same failure as before.

I think https://github.com/tensorflow/tensorflow/commit/c2e594440e1d9839546b93a93d8646b06891d7de#diff-a99b0652aa0a4be5b8fd65a0c02bea64 fixed the `[0]` case as a side-effect, since after that change the parameter gets treated as a loop invariant, so isn't converted by pfor.

**Comment by Saduf2019** [comment]
@charmasaur 
I ran the code on tf 2.5, please verify the [gist here](https://colab.research.google.com/gist/Saduf2019/26078dc9d4b45cd2e471e971b7bdb858/untitled597.ipynb) and confirm if we may move this to closed status.

**Comment by charmasaur** [comment]
Hi @Saduf2019 , unfortunately it's still not fixed in the case where the tensor has more than one element (see my comment https://github.com/tensorflow/tensorflow/issues/43322#issuecomment-695864353). Changing `[0]` to `[0, 1]` in that gist still causes a failure.
