### ISSUE TITLE
AttributeError: '_TfDeviceCaptureOp' object has no attribute 'node_def'

### ISSUE THREAD

**Issue by haiqinzhong** [tensorflow/tensorflow#43323]
Hi, i'm sorry to bother you, but i was meet a error when I use keras. my envs as follow: tensorflow-gpu==1.12, keras==2.2.4 , tensorpack==0.9.0.1
the error is:
![1](https://user-images.githubusercontent.com/56585970/93546332-26864b00-f995-11ea-9391-93b2373ec165.png)
and i use functions of keras by follow way:
![2](https://user-images.githubusercontent.com/56585970/93546361-30a84980-f995-11ea-908a-aa1242ceb4eb.png)
of course, it has the same error when i use ConvLSTM2D have get while i use the function "BatchNormalization()", which belong to keras. but the function 'Reshape()' and 'concatenate()' are run well . 

By the way, I used the keras function directly instead of modeling with keras.

Could you help me slove this error? I'd appreciate it if you could help me with this error.

**Comment by amahendrakar** [comment]
@haiqinzhong,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to v2.3 and check if you are facing the same issue?

Also, in order to expedite the trouble-shooting process, could you please provide the complete code/script you are running to reproduce the issue reported here. Thanks!

**Comment by haiqinzhong** [comment]
Thanks for your reply. But I'm sorry, in order to run another function well, I have delete these functions and change to others function which I use. and the main purpose I use the function ConvLSTM2D( ), which I can't find in TensorFlow1.x , even some functions with similar functions.
And for your first proposed, maybe its OK, but the codes I use is using TensorFlow1.12, and as a rookie, I'm not able to change all code into TensorFlow2.3, and it use tensorpack to get the model and train which is base your TensorFlow.
All right, if TensorFlow 1.x is not actively supported, I'll not try the function. 
Last, could you tell me if TensorFlow1.x have the similar function like ConvLSTM2D( )?

**Comment by haiqinzhong** [comment]
Also, I can write it again if nescessly.

**Comment by amahendrakar** [comment]
@haiqinzhong,
Sorry for the delayed response. 

ConvLSTM2D does exist for TensorFlow 1.x. Please take a look at the [documentation](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/keras/layers/ConvLSTM2D) for more information regarding this. Thanks!

**Comment by haiqinzhong** [comment]
Thank you, I'll try again. And I'll tell you what happen soon

**Comment by haiqinzhong** [comment]
Hi, @amahendrakar ,I have tried it by use tf.keras.layers.ConvLSTM2D, but it told a new error about 
AttributeError: '_TfDeviceCaptureOp' object has no attribute 'type'
the Traceback as follow:
![1](https://user-images.githubusercontent.com/56585970/94634333-596bff80-0302-11eb-8403-53d77f8ebc25.png)
![2](https://user-images.githubusercontent.com/56585970/94634339-5e30b380-0302-11eb-8e9e-34b3c69cb8b4.png)

and my code is 
![3](https://user-images.githubusercontent.com/56585970/94634413-8fa97f00-0302-11eb-8ae4-acadc0ac3eb8.png)
I only use it once

**Comment by amahendrakar** [comment]
@haiqinzhong,
Could you please provide the Python script/notebook you are running along with the dataset you are using, so that we can reproduce the issue on our end? Thanks!

**Comment by haiqinzhong** [comment]
Yeah, but how can i give you? Can you give me a email so that i can give it to you solely. @amahendrakar

**Comment by amahendrakar** [comment]
@haiqinzhong,
You can send the code to amahendrakar@google.com. However please note that to resolve the issue, I will have to share the code with other members of the TensorFlow repo.

Alternatively you can also send a minimal working example with a dummy dataset, so that users from the TensorFlow community can also take a look at the issue. Thanks!
