### ISSUE TITLE
InternalError:cudnn poolforward launch failed

### ISSUE THREAD

**Issue by weihua04** [tensorflow/tensorflow#43331]
information:
     centos 7
     tensorflow-gpu: 12.0
     tensorflow-compression: 10.0
     cuda:  9.0

when i doing a forward test code,the wrong information as belows:
![5074244104368395475](https://user-images.githubusercontent.com/37282247/93563200-fef5a980-f9b9-11ea-9913-7a29191d1c3d.jpg)

and if i use tensorflow: 12.0 it's ok ,but using cpu runnig  is too slow.

Does anyone has anygood idea to solve it?

**Comment by amahendrakar** [comment]
@weihua04,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to v2.3 and check if you are facing the same issue?

Also, please take a look at the [tested build configurations](https://github.com/tensorflow/tensorflow/issues/43307) and make sure you have all the compatible dependencies installed. Thanks!
