### ISSUE TITLE
dynamic_rnn() cannot receive an input of dynamic shape during training

### ISSUE THREAD

**Issue by lan2720** [tensorflow/tensorflow#4333]
Hi all, I met some problem when using dynamic_rnn() and wonder if there is any solution.

Firstly I sort all examples according to its length(variable length input). Then I use "batch padding" in my code. So in each step during training, data generator generates a padded minibatch, whose shape differ from the last batch. And I feed the minibatch data to the graph. Since the placeholder "inputs" in graph has an uncertain shape, it raised an error when tensor flows to `dynamic_rnn()` node. If I specify the placeholder's shape, everything is ok.

Now `dynamic_rnn()` can only receive inputs with a fixed shape. How can I combine it with "batch padding"?

Thanks!

**Comment by ebrevdo** [comment]
The batch and time dimensions in your placeholder may be None, but the last dimension must be statically known.

**Comment by lan2720** [comment]
Thanks for your clear answer! It works as you said.
