### ISSUE TITLE
How does TF decide to add examples for one API?

### ISSUE THREAD

**Issue by zjzh** [tensorflow/tensorflow#43330]
I find that TF add examples for [tf.keras.backend.clear_session()](https://www.tensorflow.org/api_docs/python/tf/keras/backend/clear_session), concatenate and etc., but not for [tf.keras.backend.batch_normalization](https://www.tensorflow.org/api_docs/python/tf/keras/backend/batch_normalization) or tf.keras.backend.binary_crossentropy. 

Does it freely for API developers to write examples? If that, does it seems chaotic?

**Comment by Saduf2019** [comment]
@zjzh 
Please refer to below links and let us know if it helps.
[link](https://www.programcreek.com/python/example/93701/keras.backend.binary_crossentropy) for "binary_crossentropy" and[ link](https://docs.w3cub.com/tensorflow~python/tf/keras/backend/batch_normalization/) for "tf.keras.backend.batch_normalization" [[also link](https://www.programcreek.com/python/example/93723/keras.backend.batch_normalization])]

**Comment by zjzh** [comment]
Yes, it is useful. But these codes can not directly run.

**Comment by Saduf2019** [comment]
@zjzh 
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by zjzh** [comment]
Yes, but I think that whether people should think that the reasonability of adding some examples. Because it seems possess randomness. For example, the users want to add examples for random_uniform, random_normal, https://github.com/tensorflow/tensorflow/issues/31277. But it is strange to add the example , and the added example is a little meaningless. Because the result does not give something.

**Comment by ymodak** [comment]
@zjzh Thanks for your issue. I agree that there is some degree of randomness when it comes to examples for certain API's. But again most of those examples are added by the community chosen by them independently. Some of the examples by themselves may not mean much but helps new users to familiarize themselves with its usages. For in depth understanding we also point out the tutorials, guides, colabs where those functions are used and why. [For example](https://www.tensorflow.org/api_docs/python/tf/keras/backend/clear_session#used-in-the-notebooks)
However such efforts are still limited and are WIP. We do appreciate community helping out and creating Pull Requests to add more such example usages and wherever they feel there is a scope of doc improvement. Having said that we are constantly working to improve documentation and add more example usages as well.

**Comment by mihaimaruseac** [comment]
The API surface of TF is huge and documentation is still lacking. Since OSS users using the APIs know better what are relevant usage patterns and can point to the most important APIs, we rely on community to provide documentation.

We have internal documentation fix-its to also documenting popular APIs and bring all documentation to a similar standard. But it's a matter of numbers: a few people at Google versus thousand of OSS contributors.
