### ISSUE TITLE
Using Tensorflow-2.3.0 with GPU

### ISSUE THREAD

**Issue by meSajied** [tensorflow/tensorflow#43337]
I downloaded **tensorflow-gpu** using pip. I set `Ld_PATH_LIBRARY` to:
```
Ld_PATH_LIBRARY="/usr/local/cuda/lib64"
Ld_PATH_LIBRARY="/usr/local/cuda-10.1/lib64"
Ld_PATH_LIBRARY="/usr/local/cuda/extras/CUPTI/lib64"
```
for all path tensorflow shows a problem:
```
2020-09-18 17:37:06.179293: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcublas.so.10'; dlerror: libcublas.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64
```
I am using **Ubuntu 20.04** and **python-3.8**

**Comment by Saduf2019** [comment]
@meSajied 
We see that you have not filled the issue template, please let us know the tf version used as pythong 3.8 is compatible from tf 2.2
#43236 #26182 [link](https://stackoverflow.com/questions/55224016/importerror-libcublas-so-10-0-cannot-open-shared-object-file-no-such-file-or) #30638

**Comment by Saduf2019** [comment]
I see the title has the tf version. Please refer to the issues shared and let us know if it helps.

**Comment by meSajied** [comment]
I asked a question in [stackoverflow](https://stackoverflow.com/questions/63871922/tensorflow-2-3-0-does-not-detect-gpu/63872640?noredirect=1#comment112960769_63872640). You will find all information there.
These answer was not helpful for me.

**Comment by Saduf2019** [comment]
@meSajied 
As the question is asked in SO please move this to closed status, as it is tracked there. Kindly have the issue on one platform.

**Comment by meSajied** [comment]
@Saduf2019
Okay.. thank you...
