### ISSUE TITLE
Documentation about tensorflow 

### ISSUE THREAD

**Issue by lucio-cyber** [tensorflow/tensorflow#43347]
Hello,
I would like some information about tensorflow:

1- if I build tensorflow from the source how much RAM does it take? ;

2- If I install tensorflow from here https://www.tensorflow.org/install/source and use the instructions to install the tensorflow package with pip is it necessary to use Bazel too or can I do without it? Also will I have instructions for AVX, AVX2 and FMA?

3- what is the difference between tensorflow 1x and 2x V 

Best Regards,
Lucio

**Comment by Saduf2019** [comment]
@lucio-cyber 
1- please refer to #30047, [link](https://www.reddit.com/r/tensorflow/comments/b8utg9/how_to_determine_the_amount_of_ram_required_to/)
2- refer to [link](https://github.com/tensorflow/tensorflow/issues/8037), [link1](https://medium.com/@sometimescasey/building-tensorflow-from-source-for-sse-avx-fma-instructions-worth-the-effort-fbda4e30eec3), [link2](https://syslog.ravelin.com/compiling-tensorflow-to-use-all-available-cpu-instructions-607945795b5c).
3- please refer to [link](https://www.datasciencecentral.com/profiles/blogs/tensorflow-1-x-vs-2-x-summary-of-changes)

**Comment by lucio-cyber** [comment]
Thank you so muche for helping me.
Best Regards

**Comment by Saduf2019** [comment]
@lucio-cyber 
Happy to help.
