### ISSUE TITLE
r1.15 Eigen download link is dead

### ISSUE THREAD

**Issue by CRoed** [tensorflow/tensorflow#43348]
version r1.15

The download link for Eigen is dead  (https://bitbucket.org/eigen/eigen/get/49177915a14a.tar.gz)

This patch switches the link to use the google storage bucket

```
From 765a2b04268d030d247a45d600686f3bac5e5d38 Mon Sep 17 00:00:00 2001
From: Chris Roed <chris.roed@omcare.com>
Date: Tue, 1 Sep 2020 11:36:49 -0500
Subject: [PATCH 3/3] use the google repo for eigen

---
 tensorflow/lite/tools/make/download_dependencies.sh | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/tensorflow/lite/tools/make/download_dependencies.sh b/tensorflow/lite/tools/make/download_dependencies.sh
index ef4a7777e6..678e35d987 100755
--- a/tensorflow/lite/tools/make/download_dependencies.sh
+++ b/tensorflow/lite/tools/make/download_dependencies.sh
@@ -29,7 +29,7 @@ if [ ! -f $BZL_FILE_PATH ]; then
   exit 1;
 fi
 
-EIGEN_URL="$(grep -o 'http.*bitbucket.org/eigen/eigen/get/.*tar\.gz' "${BZL_FILE_PATH}" | grep -v mirror.tensorflow | head -n1)"
+EIGEN_URL="$(grep -o 'http.*bitbucket.org/eigen/eigen/get/.*tar\.gz' "${BZL_FILE_PATH}" | grep mirror.tensorflow | head -n1)"
 GEMMLOWP_URL="$(grep -o 'https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/gemmlowp/.*zip' "${BZL_FILE_PATH}" | head -n1)"
 GOOGLETEST_URL="https://github.com/google/googletest/archive/release-1.8.0.tar.gz"
 ABSL_URL="$(grep -o 'https://github.com/abseil/abseil-cpp/.*tar.gz' "${BZL_FILE_PATH}" | head -n1)"
-- 
2.20.1

```

**Comment by bhack** [comment]
I don't know ok what TF version you have but on master the download URL is ok.

**Comment by jdduke** [comment]
There's nothing we can do for 1.15. Can you upgrade to the latest release version of TFLite (2.3)? Alternatively, we're working on a CMake-based build system for the upcoming 2.4 release.

**Comment by jdduke** [comment]
That said, if we end up doing some kind of patched release for 1.15, we can keep this in mind (and feel free to create a PR with your patch), but until then the branch is effectively frozen.

**Comment by CRoed** [comment]
Sounds good.  I'm stuck on 1.15 for now, but hopefully anyone else running into the issue is able to find this :-)

**Comment by mihaimaruseac** [comment]
It's too late now, but we are planning some patch releases to come out today/tomorrow.

If you can make a PR to update, on the next patch releases it will be merged
