### ISSUE TITLE
micro_speech.bin file creation fails even if compiling is successful

### ISSUE THREAD

**Issue by piisku78** [tensorflow/tensorflow#43359]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac 10.15.2
- TensorFlow installed from: source 
- Tensorflow version (commit SHA if source): 19 September 2020
- Target platform: Sparkfun Edge

**Describe the problem**

I build micro_speech project:
gmake -f tensorflow/lite/micro/tools/make/Makefile TARGET=sparkfun_edge  micro_speech_bin

last line of the build:
tensorflow/lite/micro/tools/make/downloads/gcc_embedded/bin/arm-none-eabi-objcopy tensorflow/lite/micro/tools/make/gen/sparkfun_edge_cortex-m4/bin/micro_speech tensorflow/lite/micro/tools/make/gen/sparkfun_edge_cortex-m4/bin/micro_speech.bin -O binary

The result bin file in tensorflow-master/tensorflow/lite/micro/tools/make/gen/sparkfun_edge_cortex-m4/bin/micro_speech.bin file is only 64 bytes which cannot correct. It should be about 250KB.

I have GNU Make 4.2.1

**Comment by advaitjain** [comment]
This was a regression that slipped through our CI system.

b3bacdc0f4f784769e7d8d196cbe3c654cf40b7a fixed this issue and ff9f5aab8b03ed3e36b4512b4c3fbd3e3bb29cd0 makes sure that a similar regression will be caught before it is merged.

I'm closing the current issue but please reopen this or make a new issue if things do not work for you from tip of tree.
