### ISSUE TITLE
tf.contrib.lookup.string_to_index_table_from_file optimization  

### ISSUE THREAD

**Issue by 17patelumang** [tensorflow/tensorflow#43351]
**System information** 

- OS Platform and Distribution : macOS Catalina 10.15.3

- TensorFlow installed from : binary

- TensorFlow version : 1.15.x
- Python version: 3.7.3

**Describe the current behavior**

Hi ,

If there any way we can make reading of vocab faster esp for api "tf.contrib.lookup.string_to_index_table_from_file" ?
For token size more than few thousand it take close to 500ms , how can we optimize it ?

**Comment by amahendrakar** [comment]
@17patelumang,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to v2.3 and check if you are still facing the same issue. Thanks!

**Comment by 17patelumang** [comment]
@amahendrakar  thank you for reply , for TF 2.x api is there any way we can optimize it ?

**Comment by jvishnuvardhan** [comment]
@17patelumang Can you please share a simple standalone code to reproduce any performance related issue? Can you please share as many details as possible about use-case and what you had tried and what is your goal of those optimizations. Thanks!
