### ISSUE TITLE
Module 'tensorflow' has no attribute 'get_default_session' 

### ISSUE THREAD

**Issue by lxin618** [tensorflow/tensorflow#43363]
Hi there,
i got the error: if tf.get_default_session() is not None:
AttributeError: module 'tensorflow' has no attribute 'get_default_session' 

searched similar issues online, it was all related to the versions of the packages or python i have installed, but i have tried all the suggestions with no luck, just posted here, wondering if i can please get some help.. 

python version  3.7.8, 
tensorflow             2.2.0
tensorflow-estimator   2.2.0
Keras: 2.1.4 

Thank you so much

**Comment by bhack** [comment]
https://www.tensorflow.org/api_docs/python/tf/compat/v1/get_default_session

**Comment by amahendrakar** [comment]
@lxin618,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and the dataset you are using. 

Also, please check @bhack's comment and let us know if it helps. Thanks!
