### ISSUE TITLE
tensorflow import error

### ISSUE THREAD

**Issue by Aparajithashri** [tensorflow/tensorflow#43361]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): anaconda
- TensorFlow version: 2.2.0
- Python version: 3.8.5
- Installed using virtualenv? pip? conda?: conda
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: No
- GPU model and memory: No

**Describe the problem**

I am getting this error when importing tensorflow. I don't have gpu. And my system is not gpu enabled. But still I am getting this error. It says " Ignore above cudart dlerror if you do not have a GPU set up on your machine." Please help to get rid of this and tell me how ignore this.

2020-09-19 12:27:43.405252: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-09-19 12:27:43.413500: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

Any help is appreciated :)

**Comment by bhack** [comment]
If you are on a CPU only on machine you could use `tensorflow-cpu`

**Comment by Aparajithashri** [comment]
Thanks!
