### ISSUE TITLE
different initial states for different data

### ISSUE THREAD

**Issue by soshiant1992** [tensorflow/tensorflow#4336]
i'm working with bidirectional rnn and it would be nice that it had an option to have two different initial states for different data to be trained.
thnx

**Comment by andydavis1** [comment]
Do you mean two different initial states, one for each direction?

**Comment by ebrevdo** [comment]
This already exists; see the arguments `initial_state_fw` and `initial_state_bw` for both `bidirectional_rnn` and `bidirectional_dynamic_rnn`.

**Comment by soshiant1992** [comment]
no i dont mean two initial states for different directions i mean two initial states for each direction so in total 4 initial state
thnx

**Comment by ebrevdo** [comment]
You can pass tuples for the initial states for, e.g., lstm cells.
