### ISSUE TITLE
whats the equivalent of torch.nn.Parameter() in TF ?

### ISSUE THREAD

**Issue by turmeric-blend** [tensorflow/tensorflow#43371]
from my understanding `torch.tensor(5.5, requires_grad=True)` is equivalent to `tf.Variable(5.5, trainable=True)`

how about `torch.nn.Parameter(torch.zeros([1,1,1]))` ?

**Comment by amahendrakar** [comment]
@turmeric-blend,
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!
