### ISSUE TITLE
google colab crashed after run tensofrflow code which is upgraded from 1.8 to 2.2

### ISSUE THREAD

**Issue by RokiaAbdeen** [tensorflow/tensorflow#43378]
I subscribed in colab pro and I have enough RAM but the code crashes the colab after upgrade it from TF1.8 to TF 2.2, how to solve this problem
![colab](https://user-images.githubusercontent.com/26867350/93712611-952bfa00-fb89-11ea-9e6f-eb4df272bd9a.png)

**Comment by ravikyram** [comment]
@RokiaAbdeen 

Can you please share the colab link you are referring to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!
