### ISSUE TITLE
Extract Graph in TensorFlow 2

### ISSUE THREAD

**Issue by BracketMaster** [tensorflow/tensorflow#43377]
I'm wondering how one might extract a graph in Tensorflow2.
Something like [this](https://github.com/tensorflow/tensorflow/blob/ae3c8479f88da1cd5636b974f653f27755cb0034/tensorflow/tensorboard/components/tf-tensorboard/test/data/graph_run_run2.pbtxt) in the pbtxt format: 
```
node {
  name: "a"
  op: "matmul"
}
node {
  name: "b"
  op: "matmul"
  input: "a:0"
}
node {
  name: "c"
  op: "matmul"
  input: "a:0"
  input: "b:0"
}
```

It was pretty straightforward in TF1.

**Comment by bhack** [comment]
https://www.tensorflow.org/api_docs/python/tf/io/write_graph

**Comment by BracketMaster** [comment]
I've seen that. I guess a better way to ask this question is
how to i convert an MNIST model into a graph object for the
argument ``graph_or_graph_def`` in 

```python3
tf.io.write_graph(
    graph_or_graph_def, logdir, name, as_text=True
)
```

**Comment by bhack** [comment]
I don't know why you need this but check https://stackoverflow.com/questions/63181951/how-to-get-graph-or-graphdef-from-a-given-model

**Comment by BracketMaster** [comment]
I designed a custom silicon accelerator.
Now I'm trying to write a TF compiler for it.
Was playing around with MLIR, but MLIR is missing
some basic documentation...

**Comment by bhack** [comment]
Please use the MLIR channels usually they are very available:
https://groups.google.com/a/tensorflow.org/g/mlir
https://llvm.discourse.group/c/mlir/31
https://discord.com/invite/xS7Z362
