### ISSUE TITLE
Build from source for the Raspberry Pi: Bazel binary wasn't found

### ISSUE THREAD

**Issue by brian-j-cao** [tensorflow/tensorflow#43372]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspbian Buster 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Raspberry Pi 4 8Gb 
- TensorFlow installed from (source or binary): source 
- TensorFlow version: 2.3
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 3.5.0
- GCC/Compiler version (if compiling from source): 8.3
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
I had a similar issue as #43232, when I am trying to deploy a TF2 Mask RCNN model to the Pi. Hence, I am trying to follow https://www.tensorflow.org/install/source_rpi#python-3.7 to get the TF nightly to the Pi. 

When I am trying to run: 
`tensorflow/tools/ci_build/ci_build.sh PI-PYTHON37 \
    tensorflow/tools/ci_build/pi/build_raspberry_pi.sh`

The following error appears:
`/usr/local/bin/bazel: line 163: /usr/local/lib/bazel/bin/bazel-real: cannot execute binary file: Exec format error
TF_BUILD_INFO = {container_type: "pi-python37", command: "tensorflow/tools/ci_build/pi/build_raspberry_pi.sh", source_HEAD: "da8558533d925694483d2c136a9220d6d49d843c", source_remote_origin: "https://github.com/tensorflow/tensorflow.git", OS: "Linux", kernel: "5.4.51-v7l+", architecture: "armv7l", processor: "ARMv7 Processor rev 3 (v7l)", processor_count: "4", memory_total: "7882804 kB", swap_total: "102396 kB", Bazel_version: "ERROR: The project you're trying to build requires Bazel 3.5.0 (specified in /workspace/.bazelversion), but it wasn't found in /usr/local/lib/bazel/bin.", Java_version: "1.8.0_265", Python_version: "2.7.12", gpp_version: "g++ (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609", swig_version: "", NVIDIA_driver_version: "", CUDA_device_count: "0", CUDA_device_names: "", CUDA_toolkit_version: ""}
WARNING: current bazel installation is not a release version.

...

Building for the Pi Two/Three, with NEON acceleration
/usr/local/bin/bazel: line 163: /usr/local/lib/bazel/bin/bazel-real: cannot execute binary file: Exec format error
ERROR: The project you're trying to build requires Bazel 3.5.0 (specified in /workspace/.bazelversion), but it wasn't found in /usr/local/lib/bazel/bin.

Bazel binaries for all official releases can be downloaded from here:
  https://github.com/bazelbuild/bazel/releases

Please put the downloaded Bazel binary into this location:
  /usr/local/lib/bazel/bin/bazel-3.5.0-linux-armv7l`

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I have built the Bazel binary and copy it to both: /usr/local/lib/bazel/bin/bazel-3.5.0-linux-armv7l and  /usr/local/bin

/tf_workspace ./configure gives:

You have bazel 3.5.0- (@non-git) installed.
Please specify the location of python. [Default is /usr/bin/python3]: 

However, when I tried to run 
'tensorflow/tools/ci_build/ci_build.sh PI-PYTHON37 \
    tensorflow/tools/ci_build/pi/build_raspberry_pi.sh'

The above error happens. 

Any help would be highly appreciated. 

KInd regards,
Brian

**Comment by terryheo** [comment]
You're building ARM binary on x86_64 machine. So the Bazel should be x86_64 version not armv7.

**Comment by terryheo** [comment]
For cross compiling for ARM, you can also use CMake.
https://www.tensorflow.org/lite/guide/build_cmake_arm
