### ISSUE TITLE
So frustrating with this error: Failed to load the native TensorFlow runtime

### ISSUE THREAD

**Issue by wggbullet** [tensorflow/tensorflow#43387]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OS X
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version: 2.0.1
- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
It is so frustrating that when i google this error, so many webpages are found but no (working) solutions are provided. If this is such a common error, can you guys provide a fix or an official solution for fixing the problem? 
Basically, i am trying to install tensorflow on my Mac. So what i did is:
pip install tensorflow
It was finished without any error.
But when I try:
 import tensorflow as tf

The common import error came up: Failed to load the native TensorFlow runtime.

I couldn't figure out what is the exact issue, is it because Python 3.7 does not work with tensorflow 2.0.1? I tried:
pip install tensorflow==1.15.0. 
But it says no 1.15.0 found in 2.0.1, not sure what does that mean.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
pip install tensorflow
import tensorflow as tf

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@wggbullet,
Could you please provide the complete log of the error you are facing? 

Also, please check if you are facing the same issue with TensorFlow v2.3 as well? Make sure you have all the required dependencies as mentioned [here](https://www.tensorflow.org/install/pip#system-requirements). Thanks!

**Comment by wggbullet** [comment]
> Closing as stale. Please reopen if you'd like to work on this further.

How can i reopen this issue? 
I am still unable to get tensorflow working on my computer.

**Comment by wggbullet** [comment]
the full log/trace:
(base) [deeplearning]$ python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
Traceback (most recent call last):
  File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
  Referenced from: /Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
  Referenced from: /Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Users/username/anaconda3/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
(base) [deeplearning]$

**Comment by rohan100jain** [comment]
Take a look at https://stackoverflow.com/questions/51765519/error-importing-tensorflow-in-anaconda-on-mac-osx .

what version of OSX are you using? We require macOS 10.12.6 (Sierra) or later (64-bit) (no GPU support) [https://www.tensorflow.org/install/pip]

**Comment by amahendrakar** [comment]
> Take a look at https://stackoverflow.com/questions/51765519/error-importing-tensorflow-in-anaconda-on-mac-osx .
> 
> what version of OSX are you using? We require macOS 10.12.6 (Sierra) or later (64-bit) (no GPU support) [https://www.tensorflow.org/install/pip]

@wggbullet,
Please take a look at @rohan100jain's comment and let us know if you are still facing the same issue. Thanks!

**Comment by sarusso** [comment]
Tensorflow 1.9.0 was the last version to be supported on OSX El Capitan.
