### ISSUE TITLE
tf.lite.Optimize.DEFAULT - Hybrid models are not supported on TFLite Micro.

### ISSUE THREAD

**Issue by cgreening** [tensorflow/tensorflow#43386]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Catalina 10.15.6
- TensorFlow installed from (source or binary): 2.3.0
- Tensorflow version (commit SHA if source):
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): ESP32

**Describe the problem**

I'm trying to convert a model for tflite, but keep hitting:

"Hybrid models are not supported on TFLite Micro."

**Please provide the exact sequence of commands/steps when you ran into the problem**

Here is my model:

```
model = Sequential([
    Conv2D(4, 3, 
           padding='same',
           activation='relu',
           input_shape=(IMG_WIDTH, IMG_HEIGHT, 1),
           name='conv_layer1'),
    MaxPooling2D(name='max_pooling1'),
    Conv2D(4, 3, 
           padding='same',
           activation='relu',
           name='conv_layer2'),
    MaxPooling2D(name='max_pooling2', pool_size=(2,2)),
    Flatten(),
    Dense(
        20,
        activation='relu',
        name='hidden_layer'
    ),
    Dense(1, activation='sigmoid', name='output')
])
```

And here is the code I am using to convert the mode:

```
converter = tf.lite.TFLiteConverter.from_saved_model("checkpoint.model")
converter.optimizations = [tf.lite.Optimize.DEFAULT]
model = converter.convert()
open("converted_model.tflite", "wb").write(model)
```

I have also tried `tf.lite.Optimize.OPTIMIZE_FOR_SIZE` which has the same issue. Removing all optimisations lets me 

Is there any way to avoid triggering this error with my model? Ideally, I would like to optimize my model to make it smaller.

**Comment by yair-ehrenwald** [comment]
See here:
https://www.tensorflow.org/lite/performance/post_training_quantization

Go for full integer quantization. The default optimization leaves part of the operations as floating point (hence hybrid) and mixing isn't supported in micro.

**Comment by cgreening** [comment]
@yair-ehrenwald 

Great! Setting a value for the representative_dataset seems to fix it.

Thanks for the quick response.

**Comment by AdamMiltonBarker** [comment]
> See here:
> https://www.tensorflow.org/lite/performance/post_training_quantization
> 
> Go for full integer quantization. The default optimization leaves part of the operations as floating point (hence hybrid) and mixing isn't supported in micro.

Thanks for this you answered a question that I had been scratching my head about. Do you know why full integer quantization would be failing with Zero Padding ? https://github.com/tensorflow/tensorflow/issues/50725

**Comment by ahmed123-sys** [comment]
any update for this bug. I need a fix as soon as possible
