### ISSUE TITLE
Hexagon delegate performance

### ISSUE THREAD

**Issue by aki65** [tensorflow/tensorflow#43397]
Looking at http://ai-benchmark.com/ranking_detailed.html I note that hexagon delegate performance is practically identical on snapdragon 855 und snapdragon 865, even though the DSP on SD 865 is much more powerful according to specs. Why is that ?

**Comment by multiverse-tf** [comment]
Hi @aki65,

I'm not familiar with the details about sd865 vs. sd855 w.r.t. DSP. Does such performance similarity also shows with larger models?

Based on my limited knowledge about DSP, I guess it is possible that not all processing units on the sd865 DSP are utilized to run the inference, and therefore the theoretical computing capability isn't showcased here.

Note, tflite hexagon delegate uses Qualcomm's the Hexagon NNlib to utilize the DSP. So, I think we might need to optimize this library to improve the inference latency. But to improve the throughput, it might be achieved by running with a pool of TFLite interpreters to do model inference simultaneously on the sd865 dsp.

**Comment by karimnosseir** [comment]
Not everything is more optimized on 865, so it comes down to the model. If it can be using any of the more optimized paths on the 865, otherwise can be the same.
