### ISSUE TITLE
In load_model method: Input 'values' passed int64 expected int32

### ISSUE THREAD

**Issue by partha117** [tensorflow/tensorflow#43409]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution:  Linux Ubuntu 20.04 and kaggle

- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.3.0
- Python version:3.7

**Describe the current behavior**
I have trained a model with custom loss and after save, I tried to load it but got this error

**2 errors while building NodeDef 'tf_op_layer_stack_2/stack_2' using Op<name=Pack; signature=values:N*T -> output:T; attr=N:int,min=1; attr=T:type; attr=axis:int,default=0>:
Input 'values' passed int64 expected int32
Inconsistent values for attr 'T' DT_INT32 vs. DT_INT64**

**Describe the expected behavior**
It should be loaded without any error

**Standalone code to reproduce the issue**
A minimalistic gist is [attached](https://gist.github.com/partha117/bbcd22f096c71d6f30858c4e560e9684).

**Comment by amahendrakar** [comment]
@partha117,
I was able to reproduce the error with TF v2.3.

However, the error seems to be resolved with the latest TF-nightly. I was able to run the code without any issues, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/de5cf5d0b19a87f2f79b61642fec4ad0/43409-tf-nightly.ipynb). Thanks!

**Comment by partha117** [comment]
Yes, It has been solved thanks
