### ISSUE TITLE
invalid syntax error while importing tensorflow and keras

### ISSUE THREAD

**Issue by mjvithesh** [tensorflow/tensorflow#43419]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows 10
- TensorFlow installed from (source or binary):source
- TensorFlow version:1.8.0
- Python version:3.8.5
- Installed using virtualenv? pip? conda?:virtualenv

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Traceback (most recent call last):
  File "c:/Users/win10/Desktop/python projects/try.py", line 5, in <module>
    import keras
  File "C:\Users\win10\tensor\lib\site-packages\keras\__init__.py", line 3, in <module>
    from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
  File "C:\Users\win10\tensor\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\win10\tensor\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\win10\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\win10\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 124
    def TFE_ContextOptionsSetAsync(arg1, async):
                                         ^
SyntaxError: invalid syntax
![Capture](https://user-images.githubusercontent.com/47914144/93744112-eaf6b580-fc0e-11ea-9add-ba65b39da2e3.JPG)
![Capture](https://user-images.githubusercontent.com/47914144/93744138-f8ac3b00-fc0e-11ea-8af4-3fc8dae1565a.JPG)
![Capture](https://user-images.githubusercontent.com/47914144/93744171-082b8400-fc0f-11ea-8ab4-f743631a702a.JPG)

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@mjvithesh 
Is there any particular reason for using such an old tf version when there are latest available, we have support for tf 1.15 and 2.x.
I see you are using python 3.8 which is compatible from tf 2.2 version only.
need be you may follow [installation at this link.](https://www.tensorflow.org/install).

**Comment by mjvithesh** [comment]
I couldn't install the latest version

**Comment by mjvithesh** [comment]
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow

**Comment by Saduf2019** [comment]
@mjvithesh 
Please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/43289#issuecomment-694093326) and let us know.
you may also refer to: #42977 #43244 [can you please verify if your python/cpu is 64 bits] #33838 , also please upgrade your pip version if you are unable to upgrade to 2.2, or try to down grade your python 64 bit and tf to 2.x version or 1.15

**Comment by guilt** [comment]
Let me add some activity here. Before 2.3.1, keras used to autodetect backends and play nicely. Now this explicit badly importing line in 2.4.x onwards adds this:

```
    from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
```

What is that supposed to even mean? That keras always requires this variable? This is terrible, and import guards must be added, this library is hardly useful anymore with this sort of tight coupling.
