### ISSUE TITLE
I encountered the following problems when installing the Go version of TensorFlow in the windows environment

### ISSUE THREAD

**Issue by qinjinze** [tensorflow/tensorflow#43420]
I encountered the following problems when installing the Go version of TensorFlow in the windows environment：

go run tensorflow.go
result：
..\..\..\github.com\tensorflow\tensorflow\tensorflow\go\saved_model.go:25:2: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto" in any
of:
        C:\Go\src\github.com\tensorflow\tensorflow\tensorflow\go\core\protobuf\for_core_protos_go_proto (from $GOROOT)
        H:\project\src\github.com\tensorflow\tensorflow\tensorflow\go\core\protobuf\for_core_protos_go_proto (from $GOPATH)

------------------------
I installed tensorflow(CPU) of C , the installation location is: C:\Program Files\tensorflow\lib

**Comment by qinjinze** [comment]
https://tensorflow.google.cn/install/lang_go
The content of tensorflow.go is：
package main

import (
    tf "github.com/tensorflow/tensorflow/tensorflow/go"
    "github.com/tensorflow/tensorflow/tensorflow/go/op"
    "fmt"
)

func main() {
    // Construct a graph with an operation that produces a string constant.
    s := op.NewScope()
    c := op.Const(s, "Hello from TensorFlow version " + tf.Version())
    graph, err := s.Finalize()
    if err != nil {
        panic(err)
    }

    // Execute the graph in a session.
    sess, err := tf.NewSession(graph, nil)
    if err != nil {
        panic(err)
    }
    output, err := sess.Run(nil, []tf.Output{c}, nil)
    if err != nil {
        panic(err)
    }
    fmt.Println(output[0].Value())
}

**Comment by amahendrakar** [comment]
@qinjinze,
As per the [documentation](https://www.tensorflow.org/install/lang_go#supported_platforms), TensorFlow for Go is supported on Linux and macOS.

Could you please check if you are facing the same issue in a Linux machine? Thanks!
