### ISSUE TITLE
Negate Kernel for int8 is yet to be implemented

### ISSUE THREAD

**Issue by lamarrr** [tensorflow/tensorflow#43425]
There's a TODO to implement the negate kernel for the int8 data type of TFLite Micro: https://github.com/tensorflow/tensorflow/blob/b253e82d5360c83db0d2c4e958f7822b38a06660/tensorflow/lite/micro/kernels/neg.cc#L36
I already have the code written in a PR earlier, however, I have to restart due to the present guidelines, should I proceed or leave this as it seems it's not a high-priority concern at the moment.

**Comment by lamarrr** [comment]
@wangtz

**Comment by lamarrr** [comment]
@bhack @ymodak

**Comment by wangtz** [comment]
Hi Basit,

If you already have the PR plz feel free to send a PR. I would be good to have quantized neg support for some model.

I think Advait just meant to prefer small, well scoped PR, instead of large PR. 

Also cc Advait.

Thanks,
Tiezhen

**Comment by advaitjain** [comment]
Let's hold off on this for now. I'm in the process of putting together a porting guide and would like to have PRs follow that -- ETA is a week or two.

Once we have the guide, and if the missing functionality is blocking @lamarrr then a PR would be very welcome. @lamarrr, please add some context on what you're trying to do that needs an int8 negate support in TFLM.

**Comment by lamarrr** [comment]
> Let's hold off on this for now. I'm in the process of putting together a porting guide and would like to have PRs follow that -- ETA is a week or two.
> 
> Once we have the guide, and if the missing functionality is blocking @lamarrr then a PR would be very welcome. @lamarrr, please add some context on what you're trying to do that needs an int8 negate support in TFLM.

No, It’s not blocking me. It’s marked as TODO and I wanted to help solve the technical debt.

**Comment by sachinprasadhs** [comment]
This filed to moved under `tensorflow/tflite-micro` repo, below is the updated path for the file.
https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/kernels/neg.cc

**Comment by mohantym** [comment]
Hi @lamarrr !

Please share the detailed justification  for requirement of negative kernel for int8 quantization in [tflite-micro](https://github.com/tensorflow/tflite-micro) repo as suggested in this [comment](https://github.com/tensorflow/tensorflow/issues/43425#issuecomment-708712170).  

Thank you!

**Comment by lamarrr** [comment]
We already agreed it wasn’t blocking.
I also don’t see any use for it but I don’t know who could use it and what for but it’s easily solvable by subtracting from 0 with broadcast

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
