### ISSUE TITLE
ValueError: Can only save/restore ResourceVariables when executing eagerly

### ISSUE THREAD

**Issue by unlimition** [tensorflow/tensorflow#43422]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
-   **TensorFlow installed from (source or binary)**:
-   **TensorFlow version (use command below)**:v2.3.0-rc2-23-gb36436b087 
-   **Python version**:3.7.9
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:10.1/7.6.5
-   **GPU model and memory**:2080 Ti 
-   **Exact command to reproduce**:

### Describe the problem
When I run, prog run till base.save
While run tf.compat.v1.train.Saver(), it hint
`

    Traceback (most recent call last):    
      File "main.py", line 131, in <module>
           main()
      File "main.py", line 113, in main
           T.train()
      File "/home/yang/Documents/paper/refer/MGNN-SPred-master/Train.py", line 40, in train
           self.model.save()
      File "/home/yang/Documents/paper/refer/MGNN-SPred-master/models/base.py", line 116, in save
           self.saver.save(self.sess, name)
      File "/home/yang/anaconda3/envs/tsorflw/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1180, in save
           checkpoint_file, build_save=True, build_restore=False)
      File "/home/yang/anaconda3/envs/tsorflw/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 852, in _build_eager
           checkpoint_path, build_save=build_save, build_restore=build_restore)
      File "/home/yang/anaconda3/envs/tsorflw/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 886, in _build
            build_restore=build_restore)
      File "/home/yang/anaconda3/envs/tsorflw/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 490, in _build_internal
            names_to_saveables)
      File "/home/yang/anaconda3/envs/tsorflw/lib/python3.7/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 360, in validate_and_slice_inputs
            for converted_saveable_object in saveable_objects_for_op(op, name):
       File "/home/yang/anaconda3/envs/tsorflw/lib/python3.7/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 209, in saveable_objects_for_op
           "executing eagerly, got type: %s." % type(op))
       ValueError: Can only save/restore ResourceVariables when executing eagerly, got type: <class'tensorflow.python.framework.ops.Tensor'>.
`
### Source code / logs
I run this model 
https://github.com/Autumn945/MGNN-SPred
and  change some tf1 code to tf2

`    
    
    def make_model(self):
        with tf.compat.v1.variable_scope('Graph', reuse=tf.compat.v1.AUTO_REUSE, regularizer=self.l2_loss('all')) as self.graph_scope:
            n = args.nb_nodes
            k = args.dim_k
            self.embedding_matrix = tf.compat.v1.get_variable(name='emb_w', shape=[n, k])
            with tf.compat.v1.variable_scope('graph_agg', reuse=tf.compat.v1.AUTO_REUSE) as self.graph_agg_scope:
                pass

        with tf.compat.v1.variable_scope('Network', reuse=tf.compat.v1.AUTO_REUSE, regularizer=self.l2_loss('all')):
            score, label = self.forward(*self.inputs)
            seq_loss = tf.compat.v1.losses.softmax_cross_entropy(label, score)
            tf.summary.scalar('seq_loss', seq_loss)

        self.loss = seq_loss
        self.loss += tf.compat.v1.losses.get_regularization_loss()

        opt = tf.compat.v1.train.AdamOptimizer(learning_rate=args.lr)
        self.minimizer = opt.minimize(self.loss)
        tf.summary.scalar('loss', self.loss)

        graph_var_list = tf.compat.v1.trainable_variables(scope='^Graph/')
        network_var_list = tf.compat.v1.trainable_variables(scope='^Network/')
        for v in graph_var_list:
            print('graph', v)
        for v in network_var_list:
            print('network', v)

        self.saver = tf.compat.v1.train.Saver()
        self.sess = self.get_session()
        self.sess.run(tf.compat.v1.global_variables_initializer())
    def save(self):
        name = f'{self.save_dir}/model.ckpt'
        self.saver.save(self.sess, name)
`

and 

` 

     for ep in range(args.epochs):
            pbar = tqdm(total=args.nb_vali_step, desc='training', leave=False)
            loss = []
            t0 = time.time()
            for _ in range(args.nb_vali_step):
                data = next(data_generator)
                _loss = self.model.fit(data)

                loss.append(_loss)
                pbar.update(1)
            pbar.close()
            train_time = time.time() - t0

            vali_v, vali_str = self.metric('vali')
            if vali_v > best_vali:
                brk = 0
                best_vali = vali_v
                self.model.save()
            else:
                brk += 1
            red = (brk == 0)`

Is it wrong ? Where? I need help

**Comment by Saduf2019** [comment]
@unlimition 
Code provided is incomplete for us to replicate the issue faced, please share a colab gist with error reported.

**Comment by zhr-1024** [comment]
我也这样，不知道为啥

**Comment by duang33** [comment]
> 
> 
> 我也这样，不知道为啥

你现在解决了吗

**Comment by dongmingli-Ben** [comment]
I meet this issue when running codes in [this notebook](https://github.com/magenta/magenta-demos/blob/master/jupyter-notebooks/RL_Tuner.ipynb). I am able to resolve this by adding this line in the front.
```python
tf.disable_v2_behavior()
```

**Comment by 1214083397** [comment]
> 没有成功的可以试试
tf.compat.v1.disable_v2_behavior()
之后可能会出现use closed sess错误
需要将saver函数往后缩进，放入with里边

**Comment by otuva** [comment]
@dongmingli-Ben Thanks a lot, mate. It worked
