### ISSUE TITLE
ValueError: Failed to convert value into readable tensor.

### ISSUE THREAD

**Issue by ivs-pychen** [tensorflow/tensorflow#43430]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source): 1.15

# Describe the problem
I am trying to convert the model to TFLite format using representative dataset. But I got the error : ValueError: Failed to convert value into readable tensor.

**Command used to run the converter or code if you’re using the Python API**

def rep_data_gen():
    f = '/home/pychen/traffic_3class/creDa_test_public/ImageSets/test_less.txt'
    f_name = np.loadtxt(f, dtype = np.str).reshape(-1)
    # print('Here', type(f_name))
    # print(f_name)
    NORM_H = 300
    NORM_W = 600
    for i in range(5):
        image = next(iter(f_name))
        image = tf.io.read_file(img_dir + image + '.jpg')
        image = tf.io.decode_jpeg(image, channels=3)
        image = tf.image.resize(image, [NORM_H, NORM_W])
        image = tf.cast(image / 255., tf.float32)
        image = tf.expand_dims(image, 0)
        yield [image]

frozen_graph='./tflite_graph.pb'
input_arrays=["normalized_input_image_tensor"]
output_arrays=['TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3']
input_shapes={"normalized_input_image_tensor":[1,300,600,3]}
converter = tf.lite.TFLiteConverter.from_frozen_graph(frozen_graph,input_arrays,output_arrays,input_shapes=input_shapes)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset=rep_data_gen
converter.allow_custom_ops=True

tflite_quant_model = converter.convert()

with open('quantized_model.tflite', 'wb') as f:
    f.write(tflite_quant_model)

# Copy and paste the output here.

Traceback (most recent call last):
  File "convert_tflite.py", line 79, in <module>
    tflite_quant_model = converter.convert()
  File "/home/pychen/anaconda3/envs/tf_v115/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py", line 993, in convert
    inference_output_type)
  File "/home/pychen/anaconda3/envs/tf_v115/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py", line 239, in _calibrate_quantize_model
    inference_output_type, allow_float)
  File "/home/pychen/anaconda3/envs/tf_v115/lib/python3.7/site-packages/tensorflow_core/lite/python/optimize/calibrator.py", line 75, in calibrate_and_quantize
    self._calibrator.FeedTensor(calibration_sample)
  File "/home/pychen/anaconda3/envs/tf_v115/lib/python3.7/site-packages/tensorflow_core/lite/python/optimize/tensorflow_lite_wrap_calibration_wrapper.py", line 112, in FeedTensor
    return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_FeedTensor(self, input_value)
ValueError: Failed to convert value into readable tensor.

**Comment by bhack** [comment]
Do you really need to work with an old TF version like `1.15`?

**Comment by abattery** [comment]
The TFLite converter from the recent TF 2.x versions also is able to convert the TF 1.x models. Please try conversion with the recent version.

**Comment by JanderHungrige** [comment]
Hi,

I have the same problem using TF2.2.0
The problem appears when using image data generator. If I just use a single image and yield this, no problem.

I created a stack post with more info here: https://stackoverflow.com/questions/64795017/when-using-generator-for-representative-dataset-in-quantization-it-failed-to-co

**Comment by amahendrakar** [comment]
@JanderHungrige,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by fmbao** [comment]
same question.

**Comment by JanderHungrige** [comment]
> 
> 
> same question.

Hi @fmbao, please check out the stackoverflow post I made. This could be your answer. Cheers 
 https://stackoverflow.com/questions/64795017/when-using-generator-for-representative-dataset-in-quantization-it-failed-to-co

**Comment by fmbao** [comment]
> > same question.
> 
> Hi @fmbao, please check out the stackoverflow post I made. This could be your answer. Cheers
> https://stackoverflow.com/questions/64795017/when-using-generator-for-representative-dataset-in-quantization-it-failed-to-co

I slove the question. I convert model to tflite by Tf2.Howeve,interpret on TF 1.15. So the error happen. I change the envs to TF2, the question sovled
