### ISSUE TITLE
nan is clipped to the upper

### ISSUE THREAD

**Issue by PwnerHarry** [tensorflow/tensorflow#43433]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.3
- Python version: 3.8
- CUDA/cuDNN version: 10.1/7.6
- GPU model and memory: TITAN RTX

**Describe the current behavior**
tf.clip_by_value(tf.constant(np.nan), -1, 1) == 1

**Describe the expected behavior**
tf.clip_by_value(tf.constant(np.nan), -1, 1) == NaN

**Comment by bhack** [comment]
It is similar to the `Relu` case https://github.com/tensorflow/tensorflow/issues/42885#issuecomment-687151509.
This happens on GPU if you try on CPU it returns `nan`

**Comment by PwnerHarry** [comment]
> It is similar to the `Relu` case [#42885 (comment)](https://github.com/tensorflow/tensorflow/issues/42885#issuecomment-687151509).
> This happens on GPU if you try on CPU it returns `nan`

Please fix this on GPU.

**Comment by Saduf2019** [comment]
@PwnerHarry 
Could you please check on the latest tf version and let us know if this is still an issue.

**Comment by bhack** [comment]
With nightly is 
```
<tf.Tensor: shape=(), dtype=float32, numpy=nan>
```
so we could close this.

**Comment by PwnerHarry** [comment]
@Saduf2019 I tested it on Windows with tf 2.4.1, its NaN (good).

**Comment by Saduf2019** [comment]
@PwnerHarry 
Thank you for the Update, glad it works fine.
