### ISSUE TITLE
import error -> tensorflow

### ISSUE THREAD

**Issue by Blue-Squid** [tensorflow/tensorflow#43431]
<em></em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 home edition 
- TensorFlow installed from (source or binary): Installed from conda using (pip install tensorflow) 
- TensorFlow version: 2.3.0
- Python version: 3.8.3
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA 
- CUDA/cuDNN version: NA 
- GPU model and memory: 940mx 

**Describe the problem**
Tensorflow installed successfully but unable to import it using "import tensorflow as tf" 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Installation Commands: pip install tensorflow

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by bhack** [comment]
We don't support anaconda directly. Please follow the official guide: https://www.tensorflow.org/install/pip

**Comment by ravikyram** [comment]
@Blue-Squid 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.Thanks!

**Comment by Blue-Squid** [comment]
@ravikyram 
I am using a Kaby Lake - I5 8250u processor, (listed on the compatible processors as well) 
GPU is Nvidea 940mx. 


The requirements that you have mentioned are completely met. (i,e C++ Redist and so on) 
I have used tensorflow on this machine before, I have reinstalled Windows and I am trying to set up same environment as before.

**Comment by ravikyram** [comment]
@Blue-Squid 

Sorry, but we don't provide support for issues with the conda environment.Please try using pip from [here]( https://www.tensorflow.org/install/pipl).
