### ISSUE TITLE
how to save weights without optimizer weights by using checkpoint file format in tensorflow keras model?

### ISSUE THREAD

**Issue by xiongma** [tensorflow/tensorflow#43451]

**Comment by Saduf2019** [comment]
@xiongma 
Let us know if this helps: [link](https://www.tensorflow.org/api_docs/python/tf/keras/models/save_model#expandable-1), you may use include_optimizer=False.

**Comment by xiongma** [comment]
thx your quick answer.
1. in your first answer, it saves the model, I just want to save the model weights. I want to save the weights just like this.
```
model.save_weights()
```
2. in your second answer, I don't think this related to this topic, maybe is my misunderstanding. thx very much
do u have any idea about this?

**Comment by Saduf2019** [comment]
@xiongma 
Model.save.weights will save only the model weights and model.save saves the architecture,weights and configs, please feel free to move this to closed status if it answers the question.

**Comment by xiongma** [comment]
I mean, is there a way to use `model.save_weights` that it won't save optimizer weights?

**Comment by Saduf2019** [comment]
@xiongma 
Model.save.weights will save only the model weights, the optimizer details (state) gets saved as configuration as explained above with "model.save".
