### ISSUE TITLE
Feature request: Test in cl_build for the esp32

### ISSUE THREAD

**Issue by hpssjellis** [tensorflow/tensorflow#43450]
Please make a test for the esp32 in the folder 

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/tools/ci_build

![image](https://user-images.githubusercontent.com/5605614/93850427-ec51cd80-fc62-11ea-93cf-850023ba26ad.png)

Many other builds have tests and the esp32 has a makefile here https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/tools/make/targets

**Comment by petewarden** [comment]
Thanks for the request! It would be great to have this support for continuous integration builds, so we can make sure that changes don't break the ESP32 version of the library. Unfortunately we don't have anybody internal working on this yet, but I will also ping Espressif to see if this is something they can help with.

**Comment by hpssjellis** [comment]
I am able to compile for esp32 the library as long as I delete both person_detection examples. They are causing an error in the build with a camera include file that is missing. This is what is working for me so far:

From the main tensorflow folder

```
make -f tensorflow/lite/micro/tools/make/Makefile clean

make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp TAGS="cmsis-nn" generate_arduino_zip

```

It builds and generates the zip files for each example and the main library. Unfortunately it does not seem to include relevant esp files. So presently will not compile. Still looking into it.


P.S. If I can find out how the esp32  reports errors (My board is the NodeMCU-32s). I might be able to just use the Arduino_TensorflowLite library. Not having much luck with debug_log.cc. Any suggestions @petewarden ?

**Comment by vikramdattu** [comment]
@hpssjellis @petewarden I am planning to bring CI support soon. 

Maybe in couple of weeks.

**Comment by hpssjellis** [comment]
That would be great @vikramdattu .  I am really good at finding mistakes so if you want anything tested touch base. I sent you a DM on twitter.

**Comment by vikramdattu** [comment]
Example build test is added here: https://github.com/tensorflow/tensorflow/pull/44588

**Comment by ymodak** [comment]
Closing this issue since the feature has been added with the PR tagged above. 
Feel free to reopen if required. Thanks!
