### ISSUE TITLE
A commit message should be "unit64"

### ISSUE THREAD

**Issue by zjzh** [tensorflow/tensorflow#43455]
In the commit message: https://github.com/tensorflow/tensorflow/commit/4be466a87efc152a8581febe7c1deaae562465af#diff-f0675f2568ff9470bcfc1f2bc79c5386, 

I find that it said "int64". But when I check the API documentation, it seems that it should be "unit64". Please look at parameter description: TF2.3:https://www.tensorflow.org/api_docs/python/tf/Variable#__mod__
TF2.2:  https://www.tensorflow.org/versions/r2.2/api_docs/python/tf/Variable#__mod__

**Comment by Harsh188** [comment]
Hi @zjzh, I'm having trouble trying to figure out what exactly you are talking about. Are you trying to say that `bincount` should not support non-negative ints?

**Comment by zjzh** [comment]
Hi  @Harsh188,  thanks for your reply. 
Yes, it should support. But the commit message say: "and support int64.", which seems that it does not support the int64 in past. But if we check the documentation changes: TF2.3:https://www.tensorflow.org/api_docs/python/tf/Variable#__mod__
TF2.2: https://www.tensorflow.org/versions/r2.2/api_docs/python/tf/Variable#__mod__. We can see that the "x" parameter description add " uint64". The information is inconsistent with API documentation. If the information of commit message is wrongly writes "and support int64", it should be "and support uint64".

**Comment by Harsh188** [comment]
@zjzh Sorry for my delayed response. 

Don't worry too much about the details of a commit message. I just checked `bincount`, it still raises an error if you input an array which contains negative elements.

The message does not try to indicate that arrays with negative values will be supported. I think this issue can be closed.

**Comment by lamberta** [comment]
Thanks. If the docs are accurate then we can close this.

**Comment by zjzh** [comment]
@Harsh188, Thanks for your explanation. It makes understand that developers could make it support more data types but does not mean that it support negative elements.

However, I am a little confused about whether there is the  inconsistency between commits and documentation. Specifically, you know, the documentation of ["tf.Variable.__mod__"](https://www.tensorflow.org/versions/r2.2/api_docs/python/tf/Variable#__mod__) is linked to the
