### ISSUE TITLE
InaccessibleTensorError: The tensor cannot be accessed here: it is defined in another function or code block.

### ISSUE THREAD

**Issue by Gokul-S-Kumar** [tensorflow/tensorflow#43453]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 20.04 LTS (GNU/Linux 4.4.0-18362-Microsoft x86_64)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.3.0
- Python version: 3.8.2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
I was trying to create a custom model using the Subclassing API by subclassing the tf.keras.models.Model class. After creating the model and compiling, while training the model the following issue was raised
`InaccessibleTensorError: The tensor 'Tensor("mul:0", shape=(), dtype=float32)' cannot be accessed here: it is defined in another function or code block. Use return values, explicit Python locals or TensorFlow collections to access it. Defined in: FuncGraph(name=build_graph, id=139645200248064); accessed from: FuncGraph(name=train_function, id=139645180620608).`

**Describe the expected behavior**
I have tried using the Subclassing API before but i haven't seen such an error raised. Maybe some new updates in TF.

**Standalone code to reproduce the issue**
Link to the gist
[https://gist.github.com/Gokul-S-Kumar/4834f19e78a3415caf8612327812b599](url)

**Other info/logs** 
Link to the error description, in case useful:
[https://gist.github.com/Gokul-S-Kumar/8d36b7fd40aded0fbc7a7a3c3a3a1baa](url)

PS:- I may be committing a simple mistake, if yes please help in pointing it out so that I can rectify it.

**Comment by ravikyram** [comment]
@Gokul-S-Kumar 

Please, refer #32477 and see if it helps you.Thanks!

**Comment by bhack** [comment]
@Gokul-S-Kumar You code example it is not runnable:
`NameError: name 'train_test_split' is not defined`

We need a very minimal standalone or colab example that we could copy, paste and run (so please prefer "dummy inputs" that doesn't rely on filesystem) to reproduce your issue.

**Comment by Gokul-S-Kumar** [comment]
> @Gokul-S-Kumar You code example it is not runnable:
> `NameError: name 'train_test_split' is not defined`
> 
> We need a very minimal standalone or colab example that we could copy, paste and run (so please prefer "dummy inputs" that doesn't rely on filesystem) to reproduce your issue.

@bhack Sorry for the error as some of the imports were missing. I have updated the gist (link given below):
[https://gist.github.com/Gokul-S-Kumar/4834f19e78a3415caf8612327812b599](url)

**Comment by Gokul-S-Kumar** [comment]
> @Gokul-S-Kumar
> 
> Please, refer #32477 and see if it helps you.Thanks!

@ravikyram Thanks for the response but this reference isn't of much help as I couldn't figure out any solution to my case from it. Maybe because the said issue revolves around BatchNormalization( ) being used in custom layers whereas mine doesn't employ BN layers at all.

**Comment by bhack** [comment]
@Gokul-S-Kumar Who is calling your build?
Remember that:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training.py#L325-L328

**Comment by Gokul-S-Kumar** [comment]
> @Gokul-S-Kumar Who is calling your build?
> Remember that:
> https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training.py#L325-L328

@bhack That works!! Thanks a lot for letting me know the details as I am a beginner whos finding his way around the framework :)

**Comment by Crispy13** [comment]
I am facing the same issue, so what is the solution? Could you explain it?
