### ISSUE TITLE
Is there any user data that is either being collected or Tracked by the tensorflow

### ISSUE THREAD

**Issue by m-venkata** [tensorflow/tensorflow#43465]
As part of the iOS 14 /AppTracking Transparency framework, would like to know if any kind of the user data is collected or Tracked by the tensorflow.

As mentioned in the Apple (Ref: https://developer.apple.com/support/app-privacy-on-the-app-store/),
below were some of the examples for Tracking:

- Sharing device location data or email lists with a data broker.
- Placing a third-party SDK in our app that combines user data from the app with user data from other developers’ apps to target advertising or measure advertising efficiency, even if we don’t use the SDK for these purposes. For example, using a login SDK that repurposes the data it collects from the app to enable targeted advertising in other developers’ apps.

The following situations are not considered tracking:

- When the data is linked solely on the end-user’s device and is not sent off the device in a way that can identify the end-user or device.
- When the data broker uses the data shared with them solely for fraud detection or prevention or security purposes, and solely on our behalf.

**Comment by MarkDaoust** [comment]
> Is there any user data that is either being collected or Tracked by the tensorflow?

No. Absolutely not.
