### ISSUE TITLE
Tensorflow developer certificate

### ISSUE THREAD

**Issue by gharshini** [tensorflow/tensorflow#43462]
Can we refer some resources like stackover flow(for any errors) or our noted material while taking the exam?

**Comment by Saduf2019** [comment]
@gharshini 
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by gharshini** [comment]
I have seen a similar question in github and it was answered. Can you please answer this
