### ISSUE TITLE
Flower_Classification_with_TFLite_Model_Maker: missing labels.txt

### ISSUE THREAD

**Issue by natowi** [tensorflow/tensorflow#43463]
The Tutorial and the Notebook state that I need a labels.txt file that should be generated along with the model.tflite but is not:

> After this simple 4 steps, we can now download the model and label files

https://github.com/tensorflow/examples/blob/master/lite/codelabs/flower_classification/ml/Flower_Classification_with_TFLite_Model_Maker.ipynb

>Copy the TensorFlow Lite model model.tflite and label.txt that you trained earlier to assets

https://codelabs.developers.google.com/codelabs/recognize-flowers-with-tensorflow-on-android

I tried

`model.export(export_dir='/content/export/tflite_quant', label_filename='labels.txt', tflite_filename='model_quant.tflite', quantization_config=config)`

and it says `INFO:tensorflow:Label file is inside the TFLite model with metadata.` in the log.

So is this a new feature? Is the labels.txt no longer required? What changes need to be made?

I manually created the labels.txt for the app and it worked, but I am not sure if it works without.

---

Also

lite/codelabs/flower_classification/start/app/src/main/assets/

changed to

lite/codelabs/flower_classification/android/start/app/src/main/assets

in https://codelabs.developers.google.com/codelabs/recognize-flowers-with-tensorflow-on-android/#4

**Comment by ymodak** [comment]
Perhaps this can help https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android/models/src/main/assets

**Comment by ymodak** [comment]
Perhaps this can help with the codelab approach https://github.com/tensorflow/examples/blob/master/lite/codelabs/flower_classification/android/finish/app/src/main/assets/labels.txt
I see there are multiple examples for implementing flowers recognition problem such as using [codelab](https://codelabs.developers.google.com/codelabs/recognize-flowers-with-tensorflow-on-android/#2) or [ModelMaker](https://www.tensorflow.org/lite/tutorials/model_maker_image_classification) approach.

**Comment by natowi** [comment]
@ymodak I know it is not difficult to write a labels.txt . I just would like to have a clarification if TF no longer creates this file when saving a tflite model. In this case the tutorial should be adjusted.

**Comment by ymodak** [comment]
Thanks for the report I see it fails to generate labels file along with the tflite file.

**Comment by freedomtan** [comment]
labels are embedded in tflite metadata.
use `model.export(export_dir='.', with_metadata=False)` instead of `model.export(export_dir='.')` to get `labels.txt`
Check the source code for why, https://github.com/tensorflow/examples/blob/master/tensorflow_examples/lite/model_maker/core/task/custom_model.py#L130-L177

**Comment by natowi** [comment]
@freedomtan Thanks, in this case, the Colab notebook should be adjusted accordingly.

**Comment by freedomtan** [comment]
@natowi I think original the Jupyter notebook was correct. The behavior or model maker changed.

**Comment by natowi** [comment]
@freedomtan Thanks
