### ISSUE TITLE
"Cadence processor cores only" license restriction

### ISSUE THREAD

**Issue by swinslow** [tensorflow/tensorflow#43467]
There are 29 files in the repo which look like they have an MIT license header, but upon closer inspection it actually contains a restricted license. For example, from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/testing/test_xtensa_hifi_binary.sh:

> Permission is hereby granted, free of charge, to any person obtaining
> a copy of this software and associated documentation files (the
> "Software"), **to use this Software with Cadence processor cores only and
> not with any other processors and platforms**, subject to
> the following conditions:

The files with this license notice can be seen at https://github.com/tensorflow/tensorflow/search?q=cadence+processor+cores+only

The project may want to consider removing these files, or perhaps moving them to a different repository, as content with a use restriction like this might not be seen by the community as compatible with Apache-2.0. (I gather this code will be received by anyone who checks out the source code repo, whether or not they're using this xtensa section of it.)

**Comment by jdduke** [comment]
@petewarden or @advaitjain can you comment?

**Comment by sushreebarsa** [comment]
@swinslow Could you please let us know if this is still an issue?
The URLs provided in the issue description seem to not be working. 
In order to reproduce the issue reported here, could you please provide more details on this issue. Thank you!

**Comment by swinslow** [comment]
Thanks @sushreebarsa! Looking at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro, it looks like the relevant code was moved to [a separate repo](https://github.com/tensorflow/tflite-micro).

And over in that repo, from a quick search I'm not seeing reference to the old license that was problematic. (I haven't done a deeper dive, so anyone who is concerned might want to do so, but this is not relevant for me any longer.)

So I'll go ahead and close this issue. Thanks again!
