### ISSUE TITLE
Android version of TensorFlow is missing dequantize operation

### ISSUE THREAD

**Issue by steverichey** [tensorflow/tensorflow#4346]
### Environment info

Operating System: macOS Sierra, building for Android API 19

### Minimal reproducible example

Any graph that uses either of these operations. Using the quantization tool at `tensorflow/contrib/quantization/tools:quantize_graph` will add quantize and dequantize ops to a graph, which will subsequently not work on Android.

### What other attempted solutions have you tried?

Building with the `makefile` module.

**Comment by andrewharp** [comment]
To unblock while we figure out a cleaner solution, can you try adding `"//third_party/tensorflow/contrib/quantization/kernels:android_ops" ` to the srcs for //tensorflow/core:android_tensorflow_lib?

**Comment by steverichey** [comment]
I added `"//tensorflow/contrib/quantization/kernels:android_ops"` to the list of sources for `android_tensorflow_lib` but I got an error `public/gemmlowp.h: No such file or directory` on an `#include`. I'm looking into a fix.

**Comment by steverichey** [comment]
Not sure how to ensure that the `gemmlowp` library is included. Any help is appreciated.

**Comment by andrewharp** [comment]
If you also add `//third_party/gemmlowp:eight_bit_int_gemm_sources` to the srcs list it should be able to find the missing files.

**Comment by steverichey** [comment]
I tried that but Bazel wasn't able to find that package. I did add `//tensorflow/contrib/quantization:cc_ops` to the `deps` for `android_tensorflow_lib` but then I get `external/highwayhash/BUILD:17:1: C++ compilation of rule '@highwayhash//:sip_hash' failed`. There are some other errors related to that module as well. I'm not sure if I'm including the wrong thing, or if there's some other dependency I'm missing.

**Comment by andrewharp** [comment]
Only TF targets that start with "android_" will build for Android, so `//tensorflow/contrib/quantization:cc_ops` is not expected to work here.

Did you clone with `--recurse-submodules`? Alternatively try `tensorflow/contrib/makefile/download_dependencies.sh`

**Comment by steverichey** [comment]
Okay, I had been using a downloaded ZIP, or `git clone` to get TensorFlow, but using clone with `recurse-submodules` seemed to do the trick, so maybe that was the problem all along. Thanks!

**Comment by andrewharp** [comment]
Ah, sorry; just to make this more fun, I think you may also need to add `tensorflow/contrib/quantization:android_ops` to your srcs, which should actually register the op.

**Comment by steverichey** [comment]
With this changeset in `tensorflow/core/BUILD`, I'm still having the same issue.

```
@@ -712,7 +712,9 @@ cc_library(
 # binary size (by packaging a reduced operator set) is a concern.
 cc_library(
     name = "android_tensorflow_lib",
-    srcs = if_android([":android_op_registrations_and_gradients"]),
+    srcs = if_android([":android_op_registrations_and_gradients",
+    "//tensorflow/contrib/quantization:android_ops",
+    "//tensorflow/contrib/quantization/kernels:android_ops"]),
     copts = tf_copts(),
     linkopts = ["-lz"],
     tags = [
@@ -725,6 +727,7 @@ cc_library(
         ":protos_cc",
         "//tensorflow/core/kernels:android_tensorflow_kernels",
         "//third_party/eigen3",
+        "//tensorflow/contrib/makefile/downloads/gemmlowp",
     ],
     alwayslink = 1,
 )
```

**Comment by andrewharp** [comment]
@steverichey I think you need to add `//third_party/gemmlowp:eight_bit_int_gemm_sources` to the srcs and remove `//tensorflow/contrib/makefile/downloads/gemmlowp` from the deps.

**Comment by andrewharp** [comment]
Sorry, my mistake -- that should have been `@gemmlowp//:eight_bit_int_gemm_sources` instead.

**Comment by steverichey** [comment]
```
In file included from tensorflow/contrib/quantization/kernels/quantized_bias_add_op.cc:18:0:
./tensorflow/contrib/quantization/kernels/quantization_utils.h:28:29: fatal error: public/gemmlowp.h: No such file or directory
 #include "public/gemmlowp.h"
```

😭

**Comment by andrewharp** [comment]
Ok, looks like we just need to add an extra include dir. I just tested by changing copts to:
    `copts = tf_copts() + ["-Iexternal/gemmlowp"],`
and can confirm it builds. Let's just hope it works for you at runtime :)

**Comment by steverichey** [comment]
This does indeed fix the problem at build and runtime. This reduces the size of my frozen graph definition file to 25% of its previous value, but I'm not seeing the performance improvement I would expect at runtime. Running on a Nexus 6 with Nougat, running a session with the same input takes twice as long. Is this expected?

**Comment by shisu250** [comment]
Hi @steverichey @andrewharp , I need your help,Thx. I follow these steps, but Still Error.

ERROR: /home/wx/Downloads/tensorflow/tensorflow/core/BUILD:722:12: in deps attribute of cc_library rule //tensorflow/core:android_tensorflow_lib: filegroup rule '@gemmlowp//:eight_bit_int_gemm_sources' is misplaced here (expected cc_inc_library, cc_library or objc_library).
ERROR: Analysis of target '//tensorflow/examples/android:tensorflow_demo' failed; build aborted.

My BUILD File:
`cc_library(
    name = "android_tensorflow_lib",
    srcs = if_android([":android_op_registrations_and_gradients",
    "//tensorflow/contrib/quantization:android_ops",
    "//tensorflow/contrib/quantization/kernels:android_ops"]),
    copts = tf_copts() + ["-Iexternal/gemmlowp"],
    linkopts = ["-lz"],
    tags = [
        "manual",
        "notap",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":android_tensorflow_lib_lite",
	":protos_cc",
        "//tensorflow/core/kernels:android_tensorflow_kernels",
        "//third_party/eigen3",
	"@gemmlowp//:eight_bit_int_gemm_sources",
    ],
    alwayslink = 1,
)`

**Comment by andrewharp** [comment]
@shisu250 "@gemmlowp//:eight_bit_int_gemm_sources" is a source filegroup, not a cc_library target, so it needs to go in the srcs list instead.

**Comment by andrewharp** [comment]
@steverichey QuantizedConv2D is probably the culprit -- I believe the fast pathways may not be enabled yet due to padding or range issues. You can find similar reports in #2807.

**Comment by steverichey** [comment]
@andrewharp I'll keep an eye on that issue then. Should I close this? Should I open a pull request with the required changes, or will the TensorFlow team address them in another way?

**Comment by andrewharp** [comment]
@steverichey We'll be moving the quantization code into core/ sometime soon, at which point these changes will no longer be necessary.

**Comment by steverichey** [comment]
@andrewharp Thanks for all your help!

**Comment by shisu250** [comment]
@andrewharp Thanks for your help, It worked.

My BUILD (tensorflow/tensorflow/core/BUILD) File is:
```
cc_library(
    name = "android_tensorflow_lib",
    srcs = if_android([":android_op_registrations_and_gradients",
    "//tensorflow/contrib/quantization:android_ops",
    "//tensorflow/contrib/quantization/kernels:android_ops",
    "@gemmlowp//:eight_bit_int_gemm_sources"]),
    copts = tf_copts() + ["-Iexternal/gemmlowp"],
    linkopts = ["-lz"],
    tags = [
        "manual",
        "notap",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":android_tensorflow_lib_lite",
        ":protos_cc",
        "//tensorflow/core/kernels:android_tensorflow_kernels",
        "//third_party/eigen3",
    ],
    alwayslink = 1,
)
```

Now,It worked.

**Comment by shisu250** [comment]
Hi. @andrewharp   After dequantize. Android become very slow. You mean We haven't solve this problem In Android ?  But in I0S is very fast when I do after dequantize. the IOS issue is #3619 . what can i do in android.  don't use dequantize until  wait for performance problem be solve? Please give me a suggestion, thanks.

**Comment by andrewharp** [comment]
@petewarden Do we know why exactly dequantize is fast on iOS but not on Android?

**Comment by petewarden** [comment]
No, I'm afraid I haven't been able to look into it. @cwhipkey did some vectorization using Eigen that might be related? It's a high priority to get this sorted out, since it comes up a lot!

**Comment by shisu250** [comment]
Hi. @andrewharp @petewarden   What time can solve android dequantize performance problem ? If solved, can you inform me ? Thx.
