### ISSUE TITLE
TFLiteCCoreML Delegate Runtime Crash (Espresso::ANERuntimeEngine overflow error)

### ISSUE THREAD

**Issue by raryanpur** [tensorflow/tensorflow#43473]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):

Yes

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

iOS 13.5.1

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:

iPhone 11 Max Pro

- TensorFlow installed from (source or binary):

Binary

- TensorFlow version (use command below):

TensorFlowLiteCCoreML v0.0.1 (via CocoaPods)

**Describe the current behavior**

When creating a CoreML delegate using the TensorFlowLiteC API, creating an interpreter using the delegate, then invoking the interpreter, iOS crashes because of a memory error upon invocation of the interpreter.

**Describe the expected behavior**

For the app not to crash when invoking the interpreter.

**Standalone code to reproduce the issue**

The code used to create the CoreML delegate is as follows (this all runs fine without error)

```
TfLiteCoreMlDelegateOptions coremldelegate_opts;                            
coremldelegate_opts.enabled_devices =  TfLiteCoreMlDelegateDevicesWithNeuralEngine;                            
coremldelegate_opts.coreml_version = 3; // have tried switching this to 2 but doesn't fix the crash                                 
coremldelegate_opts.max_delegated_partitions = 200;                           
                                                                              
TfLiteDelegate *delegate = TfLiteCoreMlDelegateCreate(&coremldelegate_opts);

TfLiteInterpreterOptions *options = TfLiteInterpreterOptionsCreate();       
                                                                             
if (delegate)                                                               
    TfLiteInterpreterOptionsAddDelegate(options, delegate);                 
                                                                               
TfLiteInterpreterOptionsSetNumThreads(options, 2);                          
interpreter = TfLiteInterpreterCreate(model, options); 

```

**Other info / logs**

Without the CoreML delegate the app doesn't crash when invoking the interpreter. The app also doesn't crash when creating and using an XNNPackDelegate with the interpreter.

The model being used is a non-quantized yolov4 tflite model. The interpreter runs the model fine (although with large latency) without the CoreML delegate. Here is a link to the model: https://www.dropbox.com/s/zqq1mooq3icepvk/yolov4-coco.tflite?dl=0

XCode console log upon crash is below

2020-09-23 01:51:38.095470-0400 testapp[5212:1077669] [espresso] [Espresso::ANERuntimeEngine::__forward_segment 0] evaluate[RealTime]WithModel returned 0; code=5 err=Error Domain=com.apple.appleneuralengine Code=5 "processRequest:qos:qIndex:error:: 0x1: Program Inference overflow" UserInfo={NSLocalizedDescription=processRequest:qos:qIndex:error:: 0x1: Program Inference overflow}

2020-09-23 01:51:38.095507-0400 testapp[5212:1077669] [espresso] [Espresso::overflow_error] /private/var/mobile/Containers/Data/Application/93F932CB-0799-4691-874F-B8DF78E67F5B/tmp/(A Document Being Saved By testapp 180)/A8A4CB7A-68E3-4352-B9C8-840119ACDA73-5212-0000030A34678314.mlmodelc/model.espresso.net:0

2020-09-23 01:51:38.126818-0400 testapp[5212:1077669] [espresso] [Espresso::ANERuntimeEngine::__forward_segment 0] evaluate[RealTime]WithModel returned 0; code=5 err=Error Domain=com.apple.appleneuralengine Code=5 "processRequest:qos:qIndex:error:: 0x1: Program Inference overflow" UserInfo={NSLocalizedDescription=processRequest:qos:qIndex:error:: 0x1: Program Inference overflow}

2020-09-23 01:51:38.126847-0400 testapp[5212:1077669] [espresso] [Espresso::overflow_error] /private/var/mobile/Containers/Data/Application/93F932CB-0799-4691-874F-B8DF78E67F5B/tmp/(A Document Being Saved By testapp 181)/2B38A561-4343-4868-8BF1-7AE106179D5D-5212-0000030A347917A7.mlmodelc/model.espresso.net:0
Message from debugger: Terminated due to memory issue

**Comment by raryanpur** [comment]
Hi, is there any update on this?

Thanks!

**Comment by raryanpur** [comment]
Hi TF team, following up on the above. Thanks!

**Comment by teijeong** [comment]
Hi @raryanpur,

Sorry for late reply. I was on leave :( will take a look!

From my experience, I saw program inference overflow message when the graph gets fragmented. If this is true, lowering down `max_delegate_partitions` might make the error go.

When looking at the model, there are some not supported ops, such as `EXP`, `LOG`, and `LEAKY_RELU`. https://www.tensorflow.org/lite/performance/coreml_delegate#supported_ops

So even if the graph runs fine with the Core ML delegate, the performance might be much slower than expected. I'll add support for them in the foreseeable future.

**Comment by raryanpur** [comment]
Thanks @teijeong

**Comment by sushreebarsa** [comment]
@raryanpur Could you please let us know if the issue still persists ?Thanks!

**Comment by raryanpur** [comment]
@sushreebarsa I don't currently have the bandwidth to test this for you. If it's helpful for you and the team to test, please see my notes in the original ticket that include standalone code to reproduce the issue and a link to the model being used.

**Comment by w3sip** [comment]
Seeing the same problem with TFLite, and model where only some layers support CoreML delegate. What's interesting, the model works if used in 32-bit float mode; but exhibits the behavior above when quantized to 16-bit floats.

This is with TFLite 2.5.0 on iOS 14.8.

**Comment by korkland** [comment]
im facing the same problem, 
the models are mediapipe pose and hands models tflite.
tflite version is 2.6.0 C api.
code:

`
  m_model = TfLiteModelCreateFromFile(modelFile.c_str());
  if (m_model == nullptr)
  {
    LOG_ERROR("Failed to build tflite model. Got null object from BuildFromFile() for model: {}", modelFile);
    return false;
  }
  TfLiteInterpreterOptions* options = TfLiteInterpreterOptionsCreate();
  TfLiteCoreMlDelegateOptions optionsCoreML;
  optionsCoreML.enabled_devices = TfLiteCoreMlDelegateAllDevices;
  m_delegateCoreML = TfLiteCoreMlDelegateCreate(&optionsCoreML);
  TfLiteInterpreterOptionsAddDelegate(options, m_delegateCoreML);
  if(!m_delegateCoreML)
  {
    TfLiteXNNPackDelegateOptions optionsXNNPACK = TfLiteXNNPackDelegateOptionsDefault();
    m_delegateXNNPACK = TfLiteXNNPackDelegateCreate(&optionsXNNPACK);
    TfLiteInterpreterOptionsAddDelegate(options, m_delegateXNNPACK);
  }
  
  m_interpreter = (TfLiteInterpreter*)TfLiteInterpreterCreate(m_model, options);
  if (m_interpreter == nullptr)
  {
    LOG_ERROR("Failed to build tflite interpreter. Got null object from InterpreterBuilder() for model: {}", modelFile);
    return false;
  }
  
  // Allocate tensor buffers
  if (TfLiteInterpreterAllocateTensors(m_interpreter) != kTfLiteOk)
  {
    LOG_ERROR("Failed to allocate. interpreter TfLiteInterpreterAllocateTensors != kTfLiteOk for model: {}", modelFile);
    return false;
  }
`

**Comment by w3sip** [comment]
Any updates on this? Seems like it is still an issue with 2.9.1

**Comment by sushreebarsa** [comment]
@raryanpur Could you please provide the standalone code to replicate this issue reported here as the link is not working which was attached in the thread?
Thank you!
