### ISSUE TITLE
bazel can not compile Tensorflow with GCC 6.2.1

### ISSUE THREAD

**Issue by MaeThird** [tensorflow/tensorflow#4348]
**When I launch** 
"bazel build  -c opt --jobs=10 tensorflow/tools/pip_package:build_pip_package"
**to compile tensorflow from source ,it crashed at:**
"external/com_googlesource_code_re2/BUILD:11:1: C++ compilation of rule '@com_googlesource_code_re2//:re2' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-canonical-system-headers ... (remaining 32 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
external/com_googlesource_code_re2/re2/dfa.cc: In constructor 're2::DFA::State::State()':
external/com_googlesource_code_re2/re2/dfa.cc:95:10: error: unknown array size in delete...
"
**Here are some relative infos**:
 1)bazel label: 0.3.1- (@non-git)
 2)gcc (GCC) 6.2.1 20160830
 3)tensorflow is the latest master branch
Can you tell me how to configure bazel with clang(not cross compile) ? Thanks.

**Comment by MaeThird** [comment]
https://github.com/google/re2/issues/102  or https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70932

**Comment by andydavis1** [comment]
Looks related to a gcc bug. Assigning an owner from our side to track this until the gcc bug is fixed.

**Comment by jart** [comment]
This was fixed in https://github.com/tensorflow/tensorflow/commit/7ea4e2f
