### ISSUE TITLE
Reusing Keras.Model errors

### ISSUE THREAD

**Issue by tzachar** [tensorflow/tensorflow#43483]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.3.0-rc2-23-gb36436b087 2.3.0
- Python version: 3.6.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the current behavior**
The code below throws an exception on training.

**Describe the expected behavior**
No exception expected.

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1KYTl8T_8_dZgqFcdSd6QIn9lEB9d7CPU?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to

See in the colab notebook. The exception thrown is:
InvalidArgumentError: You must feed a value for placeholder tensor 'ftrs' with dtype float and shape [?,10]
	 [[{{node ftrs}}]]

**Comment by ravikyram** [comment]
@tzachar 

I have tried in colab with TF version 2.3, nightly version(`2.4.0-dev20200924`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/5e084d1356f05a99e253a4016262261d/untitled393.ipynb).Thanks!

**Comment by nikitamaia** [comment]
Hi @tzachar, because you have provided custom code, can you give some more context/information on your use case? This helps expedite the debugging process. Additionally, is there a specific reason you are disabling eager execution?

**Comment by tzachar** [comment]
Hi @nikitamaia . 

I am disabling eager execution as it is causing errors in some of my code.
Which other context do you require?

**Comment by nikitamaia** [comment]
Disabling eager execution in TF2 is not recommended. It's best to try and fix the errors without resorting to`disable_eager_execution()`, as this will likely just cause more errors and problems in your program.

**Comment by tzachar** [comment]
I used to had various problems with Keras when eager execution was enabled.
I'll file specific bugs if I can recreate them.
