### ISSUE TITLE
ValueError: Unknown layer when i am loading of the model using tf.keras.models.load_model

### ISSUE THREAD

**Issue by Ankur3107** [tensorflow/tensorflow#43498]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): True
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow version (use command below): Latest

Hi,

I am facing a model loading issue using  `tf.keras.models.load_model`.

I saved custom keras model name- CustomModel

`model.save('model.h5')`

and then I try to load
1. 
`new_model = keras.models.load_model('model.h5', custom_objects={'CustomModel': CustomModel})`

**Error**

> usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py in class_and_config_for_serialized_keras_object(config, module_objects, custom_objects, printable_module_name)
> 294 cls = get_registered_object(class_name, custom_objects, module_objects)
> 295 if cls is None:
> --> 296 raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
> 297
> 298 cls_config = config['config']
> 
> ValueError: Unknown layer: Mean

2. 
`new_model = keras.models.load_model('model.h5', custom_objects={'CustomModel': CustomModel, 'Mean':keras.metrics.Mean})`

> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py in load_weights_from_hdf5_group(f, layers)
> 684 'containing ' + str(len(layer_names)) +
> 685 ' layers into a model with ' + str(len(filtered_layers)) +
> --> 686 ' layers.')
> 687
> 688 # We batch weight value assignments in a single backend call
> 
> ValueError: You are trying to load a weight file containing 2 layers into a model with 3 layers.

I made a dummy notebook. https://colab.research.google.com/drive/1GH-WxghmkhgLSO2vVcSKgQ4UI3WX6GKC?usp=sharing

It looks like a bug in tf.keras.models.load_model.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/ab99e61f56c7aa3e0c182a2c40e2d20d/43498.ipynb). Thanks!

**Comment by ymodak** [comment]
@Ankur3107 It can be a good idea to save and load model using `tf` format since you have custom objects in your model. 
```python
model.save('model.tf')
new_model = tf.keras.models.load_model('model.tf')#, custom_objects={'CustomModel': CustomModel})
```
In `tf` format you need not pass a `custom_objects` arg as well (TF:23).

**Comment by Ankur3107** [comment]
Hi @ymodak 

Yes I have tried .tf format and it worked. I have shared because it was not working with .h5 because I feel this is a bug. 

Now is this working with h5 or this is not a bug?

**Comment by ymodak** [comment]
To save custom objects to HDF5 you need to define `get_config` method.
See https://www.tensorflow.org/tutorials/keras/save_and_load#saving_custom_objects

**Comment by XXZhou25** [comment]
> To save custom objects to HDF5 you need to define `get_config` method.
> See https://www.tensorflow.org/tutorials/keras/save_and_load#saving_custom_objects

Hi, I have get_config in my custom layer, but still get the same error.

**Comment by ImenMasmoudiEm** [comment]
Hello, 
I had a similar issue, and this is how I resolved it:
I defined the model's architecture using the same code,
Then I used the 
model.load_weights('model.h5')
You can find the full code here on my github: https://github.com/ImenMasmoudiEm/LeukemiaDetection/tree/main
I hope it helps!
