### ISSUE TITLE
Bug in tf.math.rsqrt

### ISSUE THREAD

**Issue by jplu** [tensorflow/tensorflow#43494]
Hello!

On TF 2.3, about the function `tf.math.rsqrt(x, name=None)` the documentation says:

>x | A tf.Tensor. Must be one of the following types: bfloat16, half, float32, float64. int32

When run with `int32` type:

```
import tensorflow as tf

x = tf.constant([2, 0, -2])
tf.math.rsqrt(x)
```

I get the following error:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
        ; NodeDef: {{node Rsqrt}}; Op<name=Rsqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Rsqrt]
```

The list raised by the error and the list given in the documentation are not the same. Then either it is an error in the documentation or a bug in the implementation of the function.

Thanks.

**Comment by av8ramit** [comment]
@yashk2810 any idea on why this is happening?

**Comment by bhack** [comment]
@av8ramit It is currently: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/compat/ops_history_v2/Rsqrt.pbtxt 

What was the origin of your `int32` comment in the mentioned commit?

**Comment by av8ramit** [comment]
If I recall correctly it was autogenerated following a process outlined by @yashk2810 . It appears to me to be a one-off typo, but regardless I wanted to loop him in in case this is a larger issue. 

@jplu thanks for pointing this out, I have a fix landing shortly that will remove the extraneous int32.

**Comment by av8ramit** [comment]
https://github.com/tensorflow/tensorflow/commit/ccb76501431551f269083d78969097f9dabc8789 with the fix to the documentation.
