### ISSUE TITLE
tf.dynamic_stitch gives wrong shape and outputs raw memory

### ISSUE THREAD

**Issue by shlapfish** [tensorflow/tensorflow#43491]
**System information**
- Linux Ubuntu 20.04
- TensorFlow 2.3.0 installed from binary
- Python version 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
- no GPU available

**Describe the current behavior**
When stitching empty partitions, the output shape is wrong.
```python
>>> tf.dynamic_stitch([1], [1.2])
<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.4e-44, 1.2e+00], dtype=float32)>
```
The `2.4e-44` is from uninitialized memory and will typically vary per execution. There is nothing special about 1.2

**Describe the expected behavior**
From documentation: `merged[indices[m], ...] = data[m][...]` so we would expect:
```python
>>> tf.dynamic_stitch([1], [1.2])
<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.2], dtype=float32)>
```

**Extra**
I don't know if it's a security concern, but the amount of data read can be arbitrarily large:
```python
size = 8
>>> tf.dynamic_stitch([1], [tf.zeros([1, size])])[0]
<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([-2.8330522e-19,  4.5886920e-41, -2.8330522e-19,  4.5886920e-41,
        6.6383240e-07,  1.6802996e-04,  1.7299214e-04,  4.3915941e-05],
      dtype=float32)>
```
Edit: simplified the code

**Comment by Saduf2019** [comment]
@shlapfish 
I ran the code shared, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/fc1c1931e6dfb74a5f49117b369b89d4/untitled418.ipynb), and let us know if it confirms your issue.

**Comment by shlapfish** [comment]
> @shlapfish
> I ran the code shared, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/fc1c1931e6dfb74a5f49117b369b89d4/untitled418.ipynb), and let us know if it confirms your issue.

That does confirm my issue.

**Comment by shlapfish** [comment]
It took me a while to figure out a workaround. If it's any help:
```python
def my_stitch(indices, data):
    shapes = [tf.shape(idx) for idx in indices]
    tmp = tf.concat([tf.reshape(idx, [-1]) for idx in indices], axis=0)
    args = tf.argsort(tmp, direction='ASCENDING')
    tmp = tf.scatter_nd(tf.expand_dims(args, axis=-1), tf.range(tmp.shape[0]), shape=[tmp.shape[0]])
    
    indices = tf.split(tmp, [prod(s) for s in shapes])
    indices = [tf.reshape(idx, s) for idx, s in zip(indices, shapes)]
    return tf.dynamic_stitch(indices, data)
```

**Comment by shlapfish** [comment]
I'm so sorry. I misread the documentation :facepalm:
