### ISSUE TITLE
TensorFlow build is failing on Bazel CI (Release Bazel) for MacOS and Windows

### ISSUE THREAD

**Issue by c-parsons** [tensorflow/tensorflow#43493]
https://buildkite.com/bazel/tensorflow/builds/5772#d0cb252a-2fab-4c9c-aea3-a1b9e914ea15

Windows seems to have been failing since Sep 18 2020
MacOS seems to have been failing since Sep 19 2020

**Comment by angerson** [comment]
Sorry, those aren't our builds -- the Bazel team maintains them. Can you replicate the failure in our build-from-source instructions?

**Comment by mihaimaruseac** [comment]
I think this would be fixed by #43474

**Comment by mihaimaruseac** [comment]
Fixed in 74027b89402720e598d5512dddf3ea7737df7ffe
