### ISSUE TITLE
[Keras] Loading a model with custom layers in savedmodel format is very slow

### ISSUE THREAD

**Issue by tanguycdls** [tensorflow/tensorflow#43496]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary pip
- TensorFlow version (use command below): 2.3.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
I'm saving a keras model in savedmodel and in h5. While in H5 the loading takes 3 seconds it can take up to 15 seconds in savedmodel format. I also noticed that reloading the keras model as a savedmodel instead of keras is faster (in our private use case 6seconds against 15 seconds with keras).

We also noticed that the loading time depends on the platform and can vary given the number of cores available. 

**Describe the expected behavior**
I would expect a faster loading for both tf.keras.models.load_model('tf') and tf.saved_model.load. 

**Standalone code to reproduce the issue**
https://colab.research.google.com/gist/tanguycdls/4ef12115456f788c61771ab4fef5fdbb/untitled.ipynb
The model is:

````
inps = []
for name in range(30):
  inps.append(Input(ragged=True, shape=(None,), name=str(name)))
class SumRagged(tf.keras.layers.Layer):
    def call(self, input):
        return tf.reduce_sum(input, axis=1)
out_summed = [SumRagged()(Embedding(10, 2)(inp)) for inp in inps]
concat = Dense(1)(Concatenate()(out_summed))
model = tf.keras.models.Model(inps, concat)
````
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
In the current benchmarks:

### saving:

- savedmodel : 9.98 s per loop
- H5: 55.7 ms per loop

### Loading:
- savedmodel (keras api): 5 seconds
- savedmodel: 3 seconds
- H5: 56ms.

**Comment by ravikyram** [comment]
I have tried in colab with TF versions 2.3, nightly version(`2.4.0-dev20200923`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/41c2b484af80e33880a96faefd8625e4/untitled389.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment]
@tanguycdls Agree with you that save_format=`tf` is slower than `h5` format. However, there are some key differences between these two formats. You can check [save_and_load_model]() for more details.

One of the key difference is listed in the above resource as 

> The key difference between HDF5 and SavedModel is that HDF5 uses object configs to save the model architecture, while SavedModel saves the execution graph. Thus, SavedModels are able to save custom objects like subclassed models and custom layers without requiring the original code.

As far as my personal experience, `tf` format has better functionality over `h5` format. Thanks!

**Comment by tanguycdls** [comment]
Hi ! Thanks a lot for the details @jvishnuvardhan ! 

I agree with you the usage of the tf saved model is way better than the h5 features especially with custom layers for Keras: we actually changed our code base for that specific feature (no code requirements while reloading the model) ! 

However we're trying to optimize our timings and the cost of reloading the model in Savedmodel seems really high so I wanted to know if we can hope to have it faster in the next Tensorflow releases ? 

I especially find odd the differences between reloading a savedmodel keras with the keras api (tf.keras.models.load_model) and tf.savedmodel format directly: in the example above it took two additional seconds (3 (saved_model)-> 5 seconds (tf.keras.load_model)) but in my (private) model use case the diff is 5 seconds --> 15 seconds. 

Thanks again !

**Comment by jvishnuvardhan** [comment]
@tanguycdls `tf.saved_model.load` and `tf.keras.model.load_model` sound similar but has one critical difference. 

The object returned by tf.saved_model.load is not a Keras object (i.e. doesn't have .fit, .predict, .summary, etc. methods) whereas the object returned by `tf.keras.model.load_model` is a Keras object. 

```
loaded_model_keras = tf.keras.models.load_model('/tmp/test', compile=False)
loaded_model_keras.summary()
```

You can take `loaded_model_keras` and keep training it by running .fit. I didn't go through the source code but looks like saving this Keras object that has additional functionality takes little more time. Hope it helps. Thanks!

**Comment by tanguycdls** [comment]
Hi Thank you for the precision ! I think my issue might be related to https://github.com/tensorflow/tensorflow/issues/43263
