### ISSUE TITLE
Cross products?

### ISSUE THREAD

**Issue by fxsuper** [tensorflow/tensorflow#435]
Can we get support for cross products? This is a fundamental / elementary mathematical operation and I suspect it can be more efficiently implemented in C++, for example as in [this example](http://fastcpp.blogspot.com/2011/04/vector-cross-product-using-sse-code.html). A function that would take two tensors of 3D vectors and return the cross products of the 3D vectors would be nice. This would be done element wise, so for two tensors x and y, the returned tensor would be [x1 x y1, x2 x y2, ...].

**Comment by girving** [comment]
Thanks, that's a good feature request.  Not sure if it'll fly, but in past computational geometry work I also like defining cross product for 2D by 2D to 1D, 1D by 2D to 1D, and 2D by 1D to 1D (treating 1D as vertical).

**Comment by martinwicke** [comment]
I also want an operator that makes a vector v into the matrix V for which
Vw = v x w. Just for completeness, and we'll likely use it quickly if we
ever compute gradients rotations.

**Comment by tingnan** [comment]
The cross product of two vector W x V  can be implemented as a matrix multiplication using skew-symmetric matrix. 

https://en.wikipedia.org/wiki/Cross_product#Conversion_to_matrix_multiplication

**Comment by girving** [comment]
Yes, and we should have the star operator that converts a vector to that matrix as well, but we should still have the normal cross product operator for efficiency.

**Comment by fxsuper** [comment]
Any updates on this? Is the (core) functionality coming anytime soon or no?

**Comment by girving** [comment]
I don't think anyone is working on it internally, but patches are welcome if you want to give it a try!  If anyone does so, it's fine to ignore my 2-D desires in the first pass; they have somewhat ambiguous shape semantics anyways.

**Comment by fxsuper** [comment]
Do you have a sense of the likely performance improvement if I were to implement it as a native op in C++ vs. just python TF code? I already have a python implementation that's very simple, basically just this:

    def cross(u, v, name=None):
        with tf.op_scope([u, v], name, 'cross') as scope:
            u = tf.convert_to_tensor(u, name='u')
            v = tf.convert_to_tensor(v, name='v')

            u1, u2, u3 = tf.split(1, 3, u)
            v1, v2, v3 = tf.split(1, 3, v)

            return tf.concat(1, [(u2 * v3) - (u3 * v2),
                                 (u3 * v1) - (u1 * v3),
                                 (u1 * v2) - (u2 * v1)], name=scope)

And I'm wondering if it would be worth the extra investment. A speed up of 30% wouldn't be for me, but something like >3x would. Interestingly the above implementation is about 5x faster on CPUs than GPUs (Titan X).

**Comment by girving** [comment]
It would be well over 3x faster if native, but that's > 3x for just this op, not necessarily for your whole graph.

**Comment by sesse** [comment]
Fixed in 3c13ae058ea45d855d8029b3d19f6567b86430b5.

**Comment by girving** [comment]
Thanks!

**Comment by fxsuper** [comment]
Great, thank you!

**Comment by fxsuper** [comment]
I benchmarked the new `tf.cross` function against my own implementation written in python TensorFlow (see my earlier comment on Jan 12). The performance is actually worse on the CPU, which is rather surprising. Using this snippet of code:

```
NUM_DIMENSIONS = 3
BATCH_SIZE = 128
NUM_STEPS = 900

npr.seed(1)
mats = npr.rand(NUM_STEPS, BATCH_SIZE, NUM_DIMENSIONS).astype('float32')
base = npr.rand(BATCH_SIZE, NUM_DIMENSIONS).astype('float32')

crosses = [base]
for mat in mats:
    with tf.device('/cpu:0'):
        new_cross = tf.cross(mat, crosses[-1])
    crosses.append(new_cross)
```

And evaluating the last element of `crosses`, i.e. `crosses[-1].eval()`, takes about 0.1 seconds on a Xeon E5-2643 v3 with 4 threads enabled. In comparison my own implementation runs in 0.06 seconds despite being written in high-level TF. This is benchmarked on multiple runs and averaged, with very small standard error.

On the GPU (Titan X) the situation is different. The new `tf.cross` runs in 0.025 seconds, while my implementation runs in 0.22 seconds.

The poor CPU performance seems surprising. Any thoughts on why and if it may be improved?

**Comment by sesse** [comment]
Just a guess: I would believe your version can parallelize since all the ops are independent. What happens if you run on only one thread?

**Comment by fxsuper** [comment]
Hmmm I'm getting some very strange results. So just to be sure, the way I'm controlling threads is by invoking a session this way:

```
num_threads = 4
sess = tf.Session(config=tf.ConfigProto(inter_op_parallelism_threads=num_threads,
                                                   intra_op_parallelism_threads=num_threads,
                                                   log_device_placement=False,
                                                   allow_soft_placement=False))
```

Strangely, when I set `num_threads` to 1, _both_ implementations speed up, contrary to your expectation. My implementation goes from 0.06 secs to 0.03 secs, and `tf.cross` goes from 0.1 secs to 0.05 secs. Not sure why this is happening. The tests are very minimal, just basically what I wrote earlier.

**Comment by sesse** [comment]
There's a fair amount of per-op overhead, so for small data sets, you could be seeing contention on the thread pool. You could try going the other way, of course; splitting the tf.cross input in four, one for each CPU, and seeing if it matches your expectations.

The cross op right now has the unfortunate effect of starting three CUDA kernels (since it does three operator= statement on device); it should really have been one for better GPU efficiency, but I didn't think of it at the time.

**Comment by fxsuper** [comment]
But that still doesn't explain why my TF-based implementation gets 0.03 secs on a single CPU thread, while `tf.cross` gets 0.05 secs, right? The numbers are very repeatable so the difference is real, and is nearly 2x. Why would that be the case?

**Comment by sesse** [comment]
It's hard to say off-hand; you'd need to look at a profile for what takes up the CPU time.

**Comment by NicolayP** [comment]
Hi, is there any update on having a Skew-symmetric operation? I've done a naive implementation in python by it's the bottle-neck of my model atm.
