### ISSUE TITLE
keras.layers.experimental.preprocessing.Discretization fails for mixed precision training

### ISSUE THREAD

**Issue by jeisinge** [tensorflow/tensorflow#43502]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Databricks Runtime 7.3
- TensorFlow installed from (source or binary):  binary
- TensorFlow version (use command below): 2.3
- Python version: 3
- CUDA/cuDNN version: 10.1
- GPU model and memory: AWS p3.xlarge

**Describe the current behavior**
keras.layers.experimental.preprocessing.Discretization fails when mixed precision is enabled

Errors:
```
TypeError: Value passed to parameter 'input' has DataType float16 not in list of allowed values: int32, int64, float32, float64
tensorflow/python/keras/layers/preprocessing/discretization.py in call(self, inputs)
     99           dense_shape=array_ops.identity(inputs.dense_shape))
    100     else:
--> 101       return math_ops._bucketize(inputs, boundaries=self.bins)  # pylint: disable=protected-access
````

```python
raw_input = keras.Input(shape=1, name="raw_input")
boundaries = [0, 1, 2, 3]
discretization = keras.layers.experimental.preprocessing.Discretization(bins=boundaries)(raw_input)
```

This appears to come from tf.math.bucketize()

**Describe the expected behavior**
The replacement for TF Feature Columns should support mixed-precision training out of the box.

**Standalone code to reproduce the issue**
See above.

**Other info / logs** Include any logs or source code that would be helpful to
Work around:
```
raw_input = keras.Input(shape=1, name="raw_input")
boundaries = [0, 1, 2, 3]
discretization = keras.layers.experimental.preprocessing.Discretization(bins=boundaries, autocast=False)(raw_input)
```

However, I am having issues with serialization.

**Comment by jeisinge** [comment]
autocast doesn't appear to be serialized:

discretization.get_config()

Out[281]: {'name': 'discretization_5',
 'trainable': True,
 'dtype': {'class_name': 'Policy', 'config': {'name': 'mixed_float16'}},
 'bins': ListWrapper([0, 1, 2, 3])}

**Comment by jeisinge** [comment]
To fix serialization, I just changed the code to:
```python
  def call(self, floatx_inputs):
    import tensorflow.keras.backend as K
    
    inputs = K.cast(floatx_inputs, "float32")
 ....
```

**Comment by amahendrakar** [comment]
@jeisinge,
Could you please install the latest TF-nightly version and check if you are facing the same issue. Thanks!

**Comment by bhack** [comment]
@amahendrakar It was reproducible I think you can route this forward

**Comment by Saduf2019** [comment]
@jeisinge 
Could you please try on latest version of tf and let us know if you still face the same issue.

**Comment by jeisinge** [comment]
I apologize for the delay.  I can confirm that this is no longer an issue with TF 2.4!  Thank you!
