### ISSUE TITLE
Need use cases to guide tensorflow installation

### ISSUE THREAD

**Issue by omatai** [tensorflow/tensorflow#43519]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://www.tensorflow.org/install

## Description of issue (what needs changing):

People want tensorflow for different reasons - to play, to learn from, to deploy in this/that/other environment, to integrate into legacy systems, etc. Not all installations are appropriate to all use cases. So far I can find zero guidance on integrating tensorflow inference module that works in python laboratory environment into Windows .exe desktop application built from C++ source. That is: "Install on Windows" is simply too coarse a description that applies to some use cases, but not to others. I've definitely installed something on Windows, and I can definitely use it for python-based explorations... but it is completely unclear to me if I can deploy it in production in the environment I need to, or what exactly the installation contains. I suggest that there needs to be a comprehensive (and growing) list of use cases that lay out how tensorflow can be used in conjunction with various requirements.

Sadly, the modern trend is to offer 2 sentences of introduction, and then say "sign up and get started". That's not helpful if it takes 6 months to realise there is either a dead end to the preferred development path, or a prohibitively expensive redeployment  to a new platform required for a legacy product :-( Right now, I simply cannot tell if either of those is a possibility... or something else.

### Correct links

Is the link to the source code correct? n/a

### Parameters defined

Are all parameters defined and formatted correctly? n/a

### Returns defined

Are return values defined? n/a

### Raises listed and defined

Are the errors defined?  n/a

### Usage example

Is there a usage example? n/a

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content? n/a

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? I have no idea what a pull request is, so that would be a no.

**Comment by Saduf2019** [comment]
@omatai 
Please follow instructions here: [link](https://www.tensorflow.org/install/pip), #42367, #36167 [these should guide you]

- Ensure you have 64 bit cpu and python [python 3.8 works from tf version 2.2].
- check if your[ AVX is supported (cpu supports AVX instruction sets.)](https://www.tensorflow.org/install/pip#hardware-requirements)
- You have not installed the [Microsoft Visual C++ Redistributable package](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).

Thanks!

**Comment by omatai** [comment]
> Please follow instructions here: [link](https://www.tensorflow.org/install/pip), #42367, #36167 [these should guide you]

2 of those 3 suggestions are an admission that the documentation is insufficient - if the documentation were sufficient, there would be no need for external links. The 3rd link (to the pip install page) makes no mention of "windows" or "C++" or other elements I mentioned in the use case I am interested in. And nor should it - the guidance on what to install depending on the use case that interests you should exist at the top level to guide you towards the lower levels.

The guidance I see as missing is something to answer the question "should I...?" rather than "can I..."? Can I install tensorflow with pip. Yes. From source? Probably. But which SHOULD I do according to my intended use of tensorflow? I think I should probably do both... maybe. But there's a good chance someone will decide that a precompiled tensorflow DLL for Windows would be a good idea, issue that on some future release (or maybe it's already there?) and I shouldn't install and build from source at all because that would be a waste of time. In that utopia, I would only have to include a single header file, link to that DLL, and in literally 5 minutes I would be using tensorflow. (In contrast, see [here](https://stackoverflow.com/questions/49348987/what-is-the-best-way-to-deploy-a-tensorflow-trained-graph-into-production) for an example of what is more likely: a question that was only answered to the asker's satisfaction after 18 months.)

Am I wasting my time currently? I don't know, because there is no guidance to tell me how to install/build/configure tensorflow that is directed towards particular use cases. Only when I get to the end of the install/build/configure mission will I be able to tell if I have done the right thing.

It's not about Windows or C++ or anything so specific - it's about the intended use of tensorflow, and which path(s) one should take to install/build/configure so that (a) one does not waste time exploring non-productive paths and instead (b) choose the correct path confidently from the outset.

**Comment by mihaimaruseac** [comment]
There's an uncountable number of possible use scenarios. There's a finite number of developers. We cannot simply document everything.

In general, if you use the Python API and the pip package works for you, you install that. Otherwise, you build from source.

If you need C++ or other language bindings, you build from source again and then use the provided libraries (shared objects)

**Comment by omatai** [comment]
If I could encourage you to take that last sentence and incorporate it into the "Build from source" documentation under Tensorflow Install instructions, that would be a very useful start. Why? Because essentially the documentation currently says:
* Don't build from source (you idiot) - use the pre-compiled binaries
* If you (are stupid enough to) build from source, you'll just build an installer for python anyway, so don't bother.

But what you are saying (that the documentation currently does not say) is that building from source produces libraries. Great! That is guidance that is missing: please document it. And also document where to find what else is built. And what it is useful for.

As it stands, the implicit guidance provided by the documentation ("don't bother") is distinctly unhelpful. And ok: so use cases might be far too fine-grained to be practical. But it would take very little to say things like:
* If you need to do any of the following, you will need to build from source:
  - this platform/application/context
  - that platform/application/context
  - other platform/application/context
* When you build from source, you will create:
  - this in this folder
  - that in that folder
  -other in other folder

Reading the "build from source" documentation as it stands, there appears to be no point whatsoever building from source. Similar applies to the API for various languages - there is no hint as to how to access it. Do I go outside and shout tensorflow::ops::fingerprint at the universe? I hope not. But from the documentation, I cannot be 100% certain this is not the case because the documentation fails to tell me what IS the case.

**Comment by omatai** [comment]
Sorry - I have given up using Tensorflow directly since it is too poorly documented. For a simple network, I have found that coding it from scratch by hand (a) took less time than trying to get TF to build and (b) ran fast enough for my needs. For more complex networks, I am hopeful that I can adapt the Windows [DirectML Samples](https://github.com/microsoft/DirectML) to my needs. I'm not in a position to contribute to the docs because I cannot make anything work where I need it to - integrated into a legacy C++ application on Windows :-(
