### ISSUE TITLE
Getting a “RuntimeError: Expected bias tensor to be a vector” while trying to do full integer quantization on a keras model

### ISSUE THREAD

**Issue by An-Shank** [tensorflow/tensorflow#43517]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): Installed via pip
- TensorFlow version (or github SHA if from source): [2.4.0.dev20200923]

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
# Copy and paste here the exact command
model = load_model('path_to_model/model_v1.h5', custom_objects = {'ScaleLayer': ScaleLayer, 'ReshapeLayer': ReshapeLayer})

for i,layer in enumerate(model.layers):
    print (layer.trainable, layer.name)

def representative_dataset_gen():
    i = 0
    for i in range(1000, 3190):
        img_crop = cv2.imread('path_to_img/Frame_'
                                + str(i) + '.jpg')
        img_crop = img_crop.astype(np.float32)
        img_cropped = cv2.resize(img_crop, (150, 150))
        print (img_cropped.shape)
        oImage = np.reshape(img_cropped, (1, 150, 150, 3))
        yield [oImage]

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

tflite_quant_model = converter.convert()
open('./converted/full_int_quant.tflite', "wb").write(tflite_quant_model)
```

**The output from the converter invocation**

```
# Copy and paste the output here.
File "main.py", line 77, in <module>
    main(parse_arg(sys.argv[1:]))
  File "main.py", line 46, in main
    tflite_quant_model = converter.convert()
  File "/home/anand/virtual_environs/env_16.04_py3.6/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 892, in convert
    self).convert(graph_def, input_tensors, output_tensors)
  File "/home/anand/virtual_environs/env_16.04_py3.6/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 650, in convert
    result = self._calibrate_quantize_model(result, **flags)
  File "/home/anand/virtual_environs/env_16.04_py3.6/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 478, in _calibrate_quantize_model
    inference_output_type, allow_float, activations_type)
  File "/home/anand/virtual_environs/env_16.04_py3.6/lib/python3.6/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 98, in calibrate_and_quantize
    np.dtype(activations_type.as_numpy_dtype()).num)
RuntimeError: Expected bias tensor to be a vector.

```

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.

[model_v1.txt](https://github.com/tensorflow/tensorflow/files/5273123/model_v1.txt)

```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by bhack** [comment]
https://stackoverflow.com/questions/64019538/getting-a-runtimeerror-expected-bias-tensor-to-be-a-vector-while-trying-to-do

**Comment by amahendrakar** [comment]
@An-Shank,
On running the given code, I am facing an error stating `NameError: name 'ScaleLayer' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/a8d413a53e2475481040479ea3de8ebb/43517.ipynb ).

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by An-Shank** [comment]
> @An-Shank,
> On running the given code, I am facing an error stating `NameError: name 'ScaleLayer' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/a8d413a53e2475481040479ea3de8ebb/43517.ipynb).
> 
> In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

Here is the code:

import tensorflow as tf
from tensorflow import keras
import cv2
from keras import backend as K
import numpy as np
from converter.model import ScaleLayer, ReshapeLayer

class ScaleLayer(KL.Layer):
    def __init__(self, **kwargs):
        super(ScaleLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        assert len(input_shape) >= 2

        if K.image_data_format() == 'channels_last':
            ndim = int(input_shape[-1])
        else:
            ndim = int(input_shape[1])

        self.gamma = self.add_weight(name='gamma', shape=(ndim, ))
        self.beta = self.add_weight(name='beta', shape=(ndim, ))

        super(ScaleLayer, self).build(input_shape)

    def call(self, x):
        input_shape = K.int_shape(x)

        bn_axis = 3 if K.image_data_format() == 'channels_last' else 1

        broadcast_shape = [1] * len(input_shape)
        broadcast_shape[bn_axis] = input_shape[bn_axis]

        broadcast_gamma = K.reshape(self.gamma, broadcast_shape)
        broadcast_beta = K.reshape(self.beta, broadcast_shape)

        output = tf.math.multiply(x, broadcast_gamma)
        output = tf.math.add(output, broadcast_beta)
        return output

    def compute_output_shape(self, input_shape):
        return input_shape


class ReshapeLayer(KL.Layer):
    def __init__(self, **kwargs):
        super(ReshapeLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        assert len(input_shape) >= 2
        super(ReshapeLayer, self).build(input_shape)

    def call(self, x):
        s = K.shape(x)
        zeros_w = tf.zeros((s[0], 1, s[2], s[3]), tf.float32)
        r = K.concatenate([x, zeros_w], 1)

        s = K.shape(r)
        zeros_h = tf.zeros((s[0], s[1], 1, s[3]), tf.float32)
        r = K.concatenate([r, zeros_h], 2)
        return r    

    def compute_output_shape(self, input_shape):
        shape = tf.TensorShape(input_shape).as_list()
        if K.image_data_format() == 'channels_last':
            shape[1] = shape[1] + 1
            shape[2] = shape[2] + 1
        else:
            shape[2] = shape[2] + 1
            shape[3] = shape[3] + 1
        return tf.TensorShape(shape)

NUM_OF_SAMPLES = 1000
DIR_PATH = '/storage/DataSetCleanedCropped/training/001/'

model = load_model('/home/anand/model_v1.h5', custom_objects = {'ScaleLayer': ScaleLayer, 'ReshapeLayer': ReshapeLayer})

for i,layer in enumerate(model.layers):
    print (layer.trainable, layer.name)

def representative_dataset_gen():
    i = 0
    for i in range(1000, 3190):
        img_crop = cv2.imread('/storage/DataSetCleanedCropped/training/001/Frame_'
                                + str(i) + '.jpg')
        img_crop = img_crop.astype(np.float32)
        img_cropped = cv2.resize(img_crop, (150, 150))
        print (img_cropped.shape)
        oImage = np.reshape(img_cropped, (1, 150, 150, 3))
        yield [oImage]

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

tflite_quant_model = converter.convert()
open('./converted/full_int_quant.tflite', "wb").write(tflite_quant_model)

**Comment by An-Shank** [comment]
> @An-Shank,
> On running the given code, I am facing an error stating `NameError: name 'ScaleLayer' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/a8d413a53e2475481040479ea3de8ebb/43517.ipynb).
> 
> In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

Apologies for the formatting errors in previous comment. Please find the code below

    import tensorflow as tf
    from tensorflow import keras
    import cv2
    from keras import backend as K
    import numpy as np
    from converter.model import ScaleLayer, ReshapeLayer

    class ScaleLayer(KL.Layer):
        def init(self, **kwargs):
            super(ScaleLayer, self).init(**kwargs)

        def build(self, input_shape):
            assert len(input_shape) >= 2

            if K.image_data_format() == 'channels_last':
                ndim = int(input_shape[-1])
            else:
                ndim = int(input_shape[1])

            self.gamma = self.add_weight(name='gamma', shape=(ndim, ))
            self.beta = self.add_weight(name='beta', shape=(ndim, ))

            super(ScaleLayer, self).build(input_shape)

        def call(self, x):
            input_shape = K.int_shape(x)

            bn_axis = 3 if K.image_data_format() == 'channels_last' else 1

            broadcast_shape = [1] * len(input_shape)
            broadcast_shape[bn_axis] = input_shape[bn_axis]

            broadcast_gamma = K.reshape(self.gamma, broadcast_shape)
            broadcast_beta = K.reshape(self.beta, broadcast_shape)

            output = tf.math.multiply(x, broadcast_gamma)
            output = tf.math.add(output, broadcast_beta)
            return output

        def compute_output_shape(self, input_shape):
            return input_shape

    class ReshapeLayer(KL.Layer):
        def init(self, **kwargs):
            super(ReshapeLayer, self).init(**kwargs)

        def build(self, input_shape):
            assert len(input_shape) >= 2
            super(ReshapeLayer, self).build(input_shape)

        def call(self, x):
            s = K.shape(x)
            zeros_w = tf.zeros((s[0], 1, s[2], s[3]), tf.float32)
            r = K.concatenate([x, zeros_w], 1)

            s = K.shape(r)
            zeros_h = tf.zeros((s[0], s[1], 1, s[3]), tf.float32)
            r = K.concatenate([r, zeros_h], 2)
            return r    

        def compute_output_shape(self, input_shape):
            shape = tf.TensorShape(input_shape).as_list()
            if K.image_data_format() == 'channels_last':
                shape[1] = shape[1] + 1
                shape[2] = shape[2] + 1
            else:
                shape[2] = shape[2] + 1
                shape[3] = shape[3] + 1
            return tf.TensorShape(shape)

    NUM_OF_SAMPLES = 1000
    DIR_PATH = '/storage/DataSetCleanedCropped/training/001/'

    model = load_model('/home/anand/model_v1.h5', custom_objects = {'ScaleLayer': ScaleLayer, 'ReshapeLayer': ReshapeLayer})

    for i,layer in enumerate(model.layers):
        print (layer.trainable, layer.name)

    def representative_dataset_gen():
        i = 0
        for i in range(1000, 3190):
            img_crop = cv2.imread('/storage/DataSetCleanedCropped/training/001/Frame_'
            + str(i) + '.jpg')
            img_crop = img_crop.astype(np.float32)
            img_cropped = cv2.resize(img_crop, (150, 150))
            print (img_cropped.shape)
            oImage = np.reshape(img_cropped, (1, 150, 150, 3))
            yield [oImage]

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset_gen
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.uint8
    converter.inference_output_type = tf.uint8

    tflite_quant_model = converter.convert()
    open('./converted/full_int_quant.tflite', "wb").write(tflite_quant_model)

**Comment by amahendrakar** [comment]
@An-Shank,
On running the code I am facing an error stating `AttributeError: 'NoneType' object has no attribute 'astype'`.

Could you please share the dataset (i.e. the contents of `DIR_PATH`) you are using in the code, so that we can reproduce the issue on our end. Thanks!

**Comment by ntreepoint** [comment]
Hi,
I am facing the same error when trying to perform full integer quantization with mixed 16 bits activations and 8 bits weights ( tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8). In fact I have the same issue if i use classic method (tf.lite.OpsSet.TFLITE_BUILTINS).
I did several tests. First it is working if i convert a MobileNet V1 network, so the error depends on the network architecture.
By dichotomy, i have found the layer which causes the error. I guess the error is raised when there is a ADD (AddV2 in my case) operation right after a Conv2D operation. The converter try to merge Add operation as a bias in Conv2D. In my case, the tensor dimension of the data to be added is [1,1,1,64]. Maybe the converter is expecting [1,64] which could explain the error raised.
Here is my code used for conversion:
```
import tensorflow as tf
#import cv2
import tensorflow_datasets as tfds

import os

def representative_dataset_gen():
  #tf.enable_eager_execution()
  ds = tfds.load("flic",shuffle_files=True, split='train')
  assert isinstance(ds, tf.data.Dataset)
  print(ds)
  num_calibration_steps = 10;
  for _ in range(num_calibration_steps):
    #image, = data.take(1)
    example = ds.take(1)
    for i in example:
        image = i["image"]
        name = i["moviename"]
        print(name)
        print("type: " + str(type(image)))
        image = tf.image.resize(image,size=[256,256])
        image = tf.expand_dims(image, axis=0)
        #image = tf.transpose(image, [0, 3, 1, 2])
        yield [image]


# Convert onnx model to tflite format

# convert it first in tensorflow frozen graph
if not os.path.exists("./convertedModels/tensorflow"):
    os.makedirs("./convertedModels/tensorflow")

#Then convert it in tflite format
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph('pretrained/model_frozen.pb', #TensorFlow freezegraph .pb model file
                                                      input_arrays=['FCN_1/AlexNet/mul'], # name of input arrays as defined in torch.onnx.export function before.
                                                      output_arrays=['FCN_1/Sum'],  # name of output arrays defined in torch.onnx.export function before.
                                                      input_shapes={ 'FCN_1/AlexNet/mul': [1,256,256,3]}
                                                      )

converter.optimizations = [tf.lite.Optimize.DEFAULT]

converter.target_spec.supported_ops = [tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8]

converter.inference_input_type = tf.int16  # or tf.uint8
converter.inference_output_type = tf.int16  # or tf.uint8


converter.representative_dataset = tf.lite.RepresentativeDataset(
    representative_dataset_gen)

tf_lite_model = converter.convert()
# save the converted model
open('fc4_quant.tflite', 'wb').write(tf_lite_model)

```
Here is the frozen graph of my network:

[model_frozen.zip](https://github.com/tensorflow/tensorflow/files/5326664/model_frozen.zip)

**Comment by amahendrakar** [comment]
@ntreepoint,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by ntreepoint** [comment]
@amahendrakar , i have logged a new issue available here: https://github.com/tensorflow/tensorflow/issues/43877

**Comment by amahendrakar** [comment]
> Could you please share the dataset (i.e. the contents of `DIR_PATH`) you are using in the code, so that we can reproduce the issue on our end. Thanks!

@An-Shank,
Any updates regarding this? Is this still an issue? Thanks!
