### ISSUE TITLE
Is there a tf-serving document updated for tf2 ?

### ISSUE THREAD

**Issue by DachuanZhao** [tensorflow/tensorflow#43514]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
[https://www.tensorflow.org/tfx/serving/serving_advanced](https://www.tensorflow.org/tfx/serving/serving_advanced)

## Description of issue (what needs changing):

This documment use tf1 function , Is there a new version for tf2 ?

**Comment by gowthamkpr** [comment]
@DachuanZhao Please post this issue [here](https://github.com/tensorflow/serving/issues) as this issue is more suited to Tensorflow serving not here. Thanks!

**Comment by DachuanZhao** [comment]
> @DachuanZhao Please post this issue [here](https://github.com/tensorflow/serving/issues) as this issue is more suited to Tensorflow serving not here. Thanks!

ok ，I will close this issue .
