### ISSUE TITLE
Pybadge error compiling example sketch micro_speech_arcarda

### ISSUE THREAD

**Issue by sgroombr** [tensorflow/tensorflow#43515]
@tensorflow/micro

**System information**
Windows 10 laptop
- TensorFlow installed from (source or binary): Both Arduino_TensorflowLite 2.1.0-ALPHA and Adafruit Tensorflow Lite 1.2.1 fronm the Arduino IDE libraries
- Tensorflow version (commit SHA if source): dont know 
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Pybadge M4 with external microphone

**Describe the problem**
got the following compile error:
Arduino: 1.8.13 (Windows 10), Board: "Adafruit pyBadge M4 Express (SAMD51), Enabled, 180 MHz (overclock), Fastest (-Ofast), 50 MHz (standard), TinyUSB, Off"
Multiple libraries were found for "Adafruit_ZeroDMA.h"
Used: C:\Users\Joanna\AppData\Local\Arduino15\packages\adafruit\hardware\samd\1.6.2\libraries\Adafruit_ZeroDMA
In file included from C:\Users\Joanna\Documents\Arduino\libraries\Adafruit_TensorFlow_Lite\examples\micro_speech_arcada\micro_speech_arcada.ino:22:
Not used: C:\Users\Joanna\Documents\Arduino\libraries\Adafruit_Zero_DMA_Library
audio_provider.h:19:10: fatal error: tensorflow/lite/c/c_api_internal.h: No such file or directory
19 | #include "tensorflow/lite/c/c_api_internal.h"
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
tensorflow/lite/c/c_api_internal.h: No such file or directory

**Please provide the exact steps when you ran into the problem**
Setup new Arduino IDE
Added Adafruit https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
to boards manager url in preferences
Added Adafruit SAMD Boards 1.6.2
Added all Adafruit arcada libraries 2.5.0
Loaded Examples > Adafruit Tensorflow Lite > micro_speech_arcarda.

Got the attached error

**Comment by ymodak** [comment]
This issue is more suitable on [AdaFruit TF Lite repository](https://github.com/adafruit/Adafruit_TFLite/issues) since the example is hosted on that repo.
See https://github.com/adafruit/Adafruit_TFLite/tree/master/examples/micro_speech_arcada
Please can try posting it [there](https://github.com/adafruit/Adafruit_TFLite/issues) for quicker response.
Thank you.

**Comment by sgroombr** [comment]
Thank you - I have posted it there.

**Comment by sgroombr** [comment]
Hi Can I ask why you think it should go in the Adafruit TF Lite repository? 
The example requires both the Adafruit and Arduino TF Lite libraries/
Could it be an Arduino Library issue as that is where header file structure is i,e, src/tensorflow/lite/c/?

**Comment by ymodak** [comment]
> See https://github.com/adafruit/Adafruit_TFLite/tree/master/examples/micro_speech_arcada
The above example resides in AdaFruit library therefore future edits should be made in that repo.
