### ISSUE TITLE
keyword benchmark broken for bluepill with TAGS=cmsis-nn

### ISSUE THREAD

**Issue by advaitjain** [tensorflow/tensorflow#43510]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): c8109b89a2bf7fce60680682794f6ff4ca25de1b
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): bluepill

Command:
```
make -f tensorflow/lite/micro/tools/make/Makefile -j8 TARGET=bluepill TAGS=cmsis-nn keyword_benchmark
```

Error:
```
tensorflow/lite/micro/tools/make/downloads/cmsis//CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.c: In function 'arm_elementwise_mul_s8':
tensorflow/lite/micro/tools/make/downloads/cmsis//CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.c:178:21: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   while (loop_count > 0U)
                     ^
cc1: all warnings being treated as errors
```

This was not caught by our CI system because we do not build the benchmarks. PR #43509 should allow us to catch these issues before they are merged.

**Comment by dmpiergiacomo** [comment]
Hi, I've just faced this same issue after cloning the master [f1cef23](https://github.com/tensorflow/tensorflow/commit/f1cef2358b2979c42b524b08fc61ab9922502c99). 

I used the command:
`make -f tensorflow/lite/micro/tools/make/Makefile \
    TARGET=cortex_m_generic \
    TARGET_ARCH=cortex-m4+fp \
    TARGET_TOOLCHAIN_ROOT=/opt/gcc-arm-none-eabi-9-2020-q2-update/bin/ \
    OPTIMIZED_KERNEL_DIR=cmsis_nn microlite`

And returned the error (shortened for simplicity):
`tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.c: In function 'arm_elementwise_mul_s8':
tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.c:114:21: error: comparison of integer expressions of different signedness: 'int32_t' {aka 'long int'} and 'unsigned int' [-Werror=sign-compare]
  114 |   while (loop_count > 0U)
      |                     ^
tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.c:178:21: error: comparison of integer expressions of different signedness: 'int32_t' {aka 'long int'} and 'unsigned int' [-Werror=sign-compare]
  178 |   while (loop_count > 0U)
      |                     ^
tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.c: At top level:
cc1: error: unrecognized command line option '-Wno-unused-private-field' [-Werror]
cc1: all warnings being treated as errors
tensorflow/lite/micro/tools/make/Makefile:676: recipe for target 'tensorflow/lite/micro/tools/make/gen/cortex_m_generic_cortex-m4+fp_default/obj/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.o' failed
make: *** [tensorflow/lite/micro/tools/make/gen/cortex_m_generic_cortex-m4+fp_default/obj/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.o] Error 1
`

Which branch or tag would you suggest to use to avoid this issue?

Thank you!

**Comment by dmpiergiacomo** [comment]
After a quick look, it seems like `tensorflow/lite/micro/tools/make/Makefile` pulls a "broken" version of CMSIS. I really did not investigate how and which version it is pulled, but I can see in my localhost that the pulled version specifies `int32_t loop_count;` while the [current master](https://github.com/ARM-software/CMSIS_5/blob/master/CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.c#L65) specifies [`uint32_t loop_count;`](https://github.com/ARM-software/CMSIS_5/blob/20285262657d1b482d132d20d755c8c330d55c1f/CMSIS/NN/Source/BasicMathFunctions/arm_elementwise_mul_s8.c#L65).

I think I should be able to overcome this by building my own version of CMSIS from master and providing the `CMSIS_PATH` parameter to make. It would be nice if your CI could cross-check the compatibility though.

Thanks!

**Comment by dmpiergiacomo** [comment]
I can confirm that changing `int32_t loop_count` to `uint32_t loop_count` solves the problem.

**Comment by gowthamkpr** [comment]
@dmpiergiacomo Can you please close the issue as changing the [pulled version](https://github.com/tensorflow/tensorflow/issues/43510#issuecomment-802221145) has solved your problem. Thanks!
