### ISSUE TITLE
 ./configure command generates  warnings

### ISSUE THREAD

**Issue by szsongyj** [tensorflow/tensorflow#4352]
Hi ,
When i execute ./configure in tensorflow directory  the output contains the following warnings:
( Environment is  ubuntu16.04+cuda8+cudnnV5.1+bazel-0.3.0) 

WARNING: /home/syj/.cache/bazel/_bazel_syj/47b860f752d3ee48e8d208f528a56395/external/protobuf/WORKSPACE:1: Workspace name in /home/syj/.cache/bazel/_bazel_syj/47b860f752d3ee48e8d208f528a56395/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.

Is this warning serious? How to avoid this ?

Thanks

**Comment by szsongyj** [comment]
ERROR: /home/syj/tensorflow/tensorflow/contrib/session_bundle/BUILD:237:1: no such target '//tensorflow/core:meta_graph_portable_proto': target 'meta_graph_portable_proto' not declared in package 'tensorflow/core' defined by /home/syj/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/contrib/session_bundle:signature_lite'.

**Comment by Mazecreator** [comment]
I have some similar configuration errors that don't seem to prevent compilation.  I assume they are Android or some other operating system what is bleeding through on the configuration:

Linux: Ubuntu 16.04
Compiling with GPU support
Commit: 91a70cbf1c627117b70a3d2dd4c612779369e293

Here is the full set of errors during ./configure:

> INFO: Waiting for response from Bazel server (pid 4080)...
ERROR: /home/greg/tensorflow/tensorflow/core/kernels/BUILD:2207:1: no such target '//tensorflow/core:android_proto_lib_no_rtti_lite_runtime': target 'android_proto_lib_no_rtti_lite_runtime' not declared in package 'tensorflow/core' defined by /home/greg/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/core/kernels:android_tensorflow_kernels_no_rtti_lite_runtime'.
ERROR: /home/greg/tensorflow/tensorflow/contrib/session_bundle/BUILD:213:1: no such target '//tensorflow/core:android_lib_lite': target 'android_lib_lite' not declared in package 'tensorflow/core' defined by /home/greg/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/contrib/session_bundle:signature'.
ERROR: /home/greg/tensorflow/tensorflow/contrib/session_bundle/BUILD:107:1: no such target '//tensorflow/core:meta_graph_portable_proto': target 'meta_graph_portable_proto' not declared in package 'tensorflow/core' defined by /home/greg/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/contrib/session_bundle:session_bundle'.
ERROR: /home/greg/tensorflow/tensorflow/contrib/session_bundle/BUILD:107:1: no such target '//tensorflow/core:meta_graph_portable_proto': target 'meta_graph_portable_proto' not declared in package 'tensorflow/core' defined by /home/greg/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/contrib/session_bundle:session_bundle'.
ERROR: /home/greg/tensorflow/tensorflow/contrib/session_bundle/BUILD:213:1: no such target '//tensorflow/core:meta_graph_portable_proto': target 'meta_graph_portable_proto' not declared in package 'tensorflow/core' defined by /home/greg/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/contrib/session_bundle:signature'.
ERROR: /home/greg/tensorflow/tensorflow/contrib/session_bundle/BUILD:213:1: no such target '//tensorflow/core:meta_graph_portable_proto': target 'meta_graph_portable_proto' not declared in package 'tensorflow/core' defined by /home/greg/tensorflow/tensorflow/core/BUILD and referenced by '//tensorflow/contrib/session_bundle:signature'.
ERROR: Evaluation of query "deps((//... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.
Configuration finished

I did compile the PIP package with no problems after getting these configuration errors.

**Comment by szsongyj** [comment]
I updated the bazel and confirmed the current version is 0.3.1(using command: "which bazel" and "bazel version"respectively )
and I run the configure process as @gustavla suggested:

git clone https://github.com/tensorflow/tensorflow
cd tensorflow
git show -R 7bcdcbb | git apply
./configure
But the following errors appeared and configured process failed

/home/syj/tensorflow/tensorflow/contrib/session_bundle/BUILD:107:1no such target '//tensorflow/core:android_lib_lite':target 'android_lib_lite'not declared in package.....

/home/syj/tensorflow/tensorflow/core/BUILD:899:1no such package '@zlib_archive//':Error downloading from http://zlib.net/zlib-1.2.8.tar.gz to ......

configuration of query "deps((//...union @bazel_tools//tools/jdk:toolchain))"failed:errors were encountered while computing transitive closure.

I am appreciated if anyone can tell me how to solve this problem.

Thank you

**Comment by andrewharp** [comment]
The errors regarding android_lib_lite and meta_graph_portable_proto should be fixed by f66b491, which was pushed today in #4360.

**Comment by andydavis1** [comment]
@szsongyj Given @andrewharp comment, is this still an issue?

**Comment by aselle** [comment]
Closing automatically due to lack of recent activity. Please reopen when further information becomes available. Thank you.
