### ISSUE TITLE
 'tf.TensorScatterUpdate' Conversion to tflite

### ISSUE THREAD

**Issue by shlomi-amitai** [tensorflow/tensorflow#43529]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
windows 10
- TensorFlow installed from (source or binary):
python binary 
- TensorFlow version (or github SHA if from source):
2.3

**Provide the text output from tflite_convert**
error: 'tf.TensorScatterUpdate' op is neither a custom op nor a flex op
(im already using TF ops)
```
# Copy and paste here
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by bhack** [comment]
> Standalone code to reproduce the issue
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Comment by Saduf2019** [comment]
@shlomi-amitai 
Please share simple stand alone code to replicate the issue along with error log for us to analyse.

**Comment by abattery** [comment]
I will add tf.TensorScatterUpdate op and related ops to the Select TF ops option. Please stay tuned.

**Comment by abattery** [comment]
I added tf.TensorScatterUpdate op support in the Select TF ops option. Please try the conversion again with the tomorrow's tf-nightly version.

**Comment by shlomi-amitai** [comment]
Hi @abattery , 
Thank you so much, I tried, and don't see any error regarding the tf.TensorScatterUpdate op, 
though I get now a new error related to tf.concat op.
Maybe something is broken there? 
saved_model attached.
[saved_model.zip](https://github.com/tensorflow/tensorflow/files/5298930/saved_model.zip)
(problem in concat_415)

**Comment by shlomi-amitai** [comment]
<unknown>:0: error: loc("Concat_415"): operand type 'tensor<1x32x112x20xf32>' is not compatible with preceding operands; expected dimension at index 3: 160
<unknown>:0: note: loc("Concat_415"): see current operation: %1202 = "tf.ConcatV2"(%525, %652, %1201, %1197, %1189, %1185, %24) {device = ""} : (tensor<1x64x112x160xf32>, tensor<1x128x112x160xf32>, tensor<1x32x112x20xf32>, tensor<1x32x112x10xf32>, tensor<1x32x112x5xf32>, tensor<1x32x112x2xf32>, tensor<i32>) -> tensor<1x?x112x160xf32>
