### ISSUE TITLE
Cannot install tensorflow-gpu==2.0.0 by pip

### ISSUE THREAD

**Issue by jusonn** [tensorflow/tensorflow#43526]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac
- TensorFlow installed from (source or binary):pip
- TensorFlow version: 2.0.0
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: 10.0
- GPU model and memory: p40

**Describe the problem**

I got this error.
```bash
root@dc45fa59c9f0:/workspace# pip install tensorflow-gpu==2.0.0
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==2.0.0 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow-gpu==2.0.0
```

**Comment by Saduf2019** [comment]
@jusonn 
Please refer this guide 
https://www.tensorflow.org/install
commands
# Requires the latest pip
pip install --upgrade pip

# Current stable release for CPU and GPU
pip install tensorflow

**Comment by jusonn** [comment]
@Saduf2019 
Thanks, 
but it still not work.

**Comment by Saduf2019** [comment]
@jusonn 
Please verify if the python installed is 64 bits, please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/26578#issuecomment-471589989).

**Comment by Saduf2019** [comment]
Also refer to [comment](https://github.com/tensorflow/tensorflow/issues/26578#issuecomment-617275081), you can use google colab>change runtime>GPU

**Comment by jusonn** [comment]
python is installed with 64bit and I upgraded pip.
but i got same error
```
root@dc45fa59c9f0:/workspace# pip install tensorflow-gpu==2.0.0
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==2.0.0 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1)
ERROR: No matching distribution found for tensorflow-gpu==2.0.0
```

Can you install tensorflow-gpu==2.0.0??

**Comment by jusonn** [comment]
@Saduf2019 
It was due to my python version.
tensorflow 2.0.0 does not support python 3.8

**Comment by RylanSchaeffer** [comment]
I'm getting this error with Python 3.7.5., not Python 8:

```
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==2.0.0rc2 (from versions: 1.13.1, 1.13.2, 1.14.0, 1.15.0, 1.15.2, 1.15.3, 1.15.4, 1.15.5, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.2, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.8.0rc0)
ERROR: No matching distribution found for tensorflow-gpu==2.0.0rc2
```

**Comment by CRYPTEWORLD** [comment]
TRYED all rebuilds and i can't find tensorflow 2.0 or 2.10.0  get a by pass flash ( fond newer updating ) i'm locked out of the GPU's ?
