### ISSUE TITLE
Tensorflow 2.3.0 can't detect CUDA on Python 3.7.9

### ISSUE THREAD

**Issue by ArsenicBismuth** [tensorflow/tensorflow#43528]
**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version: 2.3.0
- Python version: 3.7.9
- CUDA/cuDNN version: 10.1/7.6
- GPU model and memory: Nvidia GTX 960m

I just discovered compatibility problem between Tensorflow 2.3.0 and Python 3.7.9. So, as you might have noticed, there're A LOT of "cudart64_X.dll not found" problems floating around, with standard fixes here and there.

But I just couldn't find any single solution that can fix it. I even did everything cleanly, the CUDA/cuDNN install process. I also make sure my environment vars & PATH are as complete as possible.

Until I downgraded to Python 3.7.1, and the problem magically gone, that's all. This is my steps:

1. Have CUDA/cuDNN installed complete with path & environment.
2. Conda create environment python 3.7 (so I get Python 3.7.9).
3. Activate that new env.
4. pip install tensorflow (so I get v2.3.0).
5. try to import tensorflow, get "cudart64_101.dll not found".
6. Conda install python=3.7.1 (so, downgrade).
7. try to import tensorflow, get "Successfully opened dynamic library cudart64_101.dll"

**Comment by bhack** [comment]
We don't officially support conda here.

You have two solutions:
- Use the default install guide without Miniconda/Anaconda: https://www.tensorflow.org/install/pip
- Continue to use conda. But you need to ask support to the Conda project https://docs.anaconda.com/anaconda/user-guide/tasks/tensorflow/

Can you verify that this problem (3.7.9) exist with the official installation guide.
