### ISSUE TITLE
Difference between keras and tf.keras

### ISSUE THREAD

**Issue by DeligientSloth** [tensorflow/tensorflow#43520]
I found tf.keras is quite different with keras, in keras, bug occur when you use normal function instead Lambda wrapper function, bug is "AttributeError: 'NoneType' object has no attribute '_inbound_nodes'", while in tf.keras, it is allowed use normal function and tf.keras.layers. funtion simultaneously.
keras seems use different data structure, create innode between layers.

**Comment by bhack** [comment]
Please read this https://github.com/keras-team/keras/releases/tag/2.4.0
