### ISSUE TITLE
help!!!!! tensorflow error

### ISSUE THREAD

**Issue by quangta2017** [tensorflow/tensorflow#43536]
![image](https://user-images.githubusercontent.com/27395455/94133874-72505d00-fe8b-11ea-9cb8-dae6a43a7926.png)

**Comment by bhack** [comment]
It is not a bug you need python 64 bit

**Comment by quangta2017** [comment]
> It is not a bug you need python 64 bit

Thanks!

**Comment by amahendrakar** [comment]
@quangta2017,
Is this still an issue? Please feel free to close the issue if resolved. Thanks!

**Comment by ymodak** [comment]
* You may try Google Colab to use TensorFlow.
    * The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true). You get pre-installed latest stable TF version. Also you can use ```pip``` to install any other preferred TF version.
    * It has an added advantage since you can you easily switch to different hardware accelerators     
      (cpu, gpu, tpu) as per the task. 
    * All you need is a good internet connection and you are all set.
