### ISSUE TITLE
Problem with custom grad with multiple external variables

### ISSUE THREAD

**Issue by RochMollero** [tensorflow/tensorflow#43535]
**Describe the current behavior**

The "variables" argument in custom grad seems to be buggy. For example this code, which is a complexified version of the "custom_grad" example in the doc:

```
import tensorflow as tf
import numpy as np
import time

m=1000

varr=tf.Variable(200.0)
varr3=tf.Variable(200.0)
varr2=tf.constant(1.0)

@tf.function
@tf.custom_gradient
def log1pexp(x1, x2):
  #some basic function fluff 
  e=tf.exp(x1)
  e=tf.math.log(1 + e)
  for i in range(m):
  	e += 0.0*tf.exp(x1) + 1.0

  #here comes the problem
  print("tracing")
  def grad(dy, dz, variables=[varr, varr3]):
    return [dy * (1 - 1 / (1 + e)) + 0 * varr2, tf.constant(0.0)], [0.0 * varr, 0.0*varr3]

  return [e+varr, varr3], grad#

x = tf.constant(1.0)
with tf.GradientTape() as g:
  g.watch(x)
  y=log1pexp(x,0.0)

dy_dx = g.gradient(y, x)
print (dy_dx)
```

Leads to the error:
``ValueError: Must return gradient for each variable from @custom_gradient grad_fn.``

Which i seem to be doing (log1pexp has 2 inputs, outputs and two external variables, so the return size should be  list of size 2 each ?)

However if I change line 23 to 
```    return [dy * (1 - 1 / (1 + e)) + 0 * varr2, tf.constant(0.0)], [0.0 * varr] ```

Then it doesn't give an error, which doesn't make sense to me since in that case, grad_vars only contain gradient info for ONE of the external variables I have registered in the variables parameters.

Also it doesn't care about varr2 at all ...

**Describe the expected behavior**

The code above should not give error?

**Standalone code to reproduce the issue**

See above

**Other info / logs** 

Basic ubuntu 20. error with tf 2.2 and 2.3

**Comment by bhack** [comment]
The issue is that `actual_grad_fn` receive only 1 `variable` (in this case `e+varr`) but two `variable_grads`:

https://github.com/tensorflow/tensorflow/blob/e798106686903c077d6f082d637f0971da31f20c/tensorflow/python/ops/custom_gradient.py#L507-L508

**Comment by RochMollero** [comment]
Are you telling me it's a tf problem or a problem in my code ?

I'm not sure what I should read in the two lines: it seems good. except that the  the two "variables" receives should be **varr** and **varr3**, i'm not sure why you said it only receive "e+varr" since it's an output of fn

**Comment by bhack** [comment]
Yes It was just a type meant `varr`. 
Edit this file locally and try to add `print(variables)` before the mentioned condition

**Comment by RochMollero** [comment]
OK so I've inspected with the code:
```
  variables_in_tape = frozenset([
    v.ref() for v in variable_watcher.watched_variables()
  ])
```
and I found something:

In the above code, varr3 **is not registered in variables_in_tape** seemingly because **it's used as an "identity function" and there's no operation involving it**

For example if I change my function to return this (just adding 0.0 to varr3 so the function is essentially the same) :
```return [e+varr, 0.0+varr3], grad ```

Then tensorflow will register varr3, and as expected will require me to provide gradient for both varr and varr3.

I'm pretty sure this is not expected behavior from the tensorflow team ... not sure how to escalate but you guys should check this out.

**Comment by Saduf2019** [comment]
@RochMollero 
I ran your code on tf 2.3 and nightly, i do not face the error reported above, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/b5bdc253d11a598e40dd13c8ab36a8bf/untitled418.ipynb).

**Comment by bhack** [comment]
@Saduf2019 The user is asking something different.

 /cc @jaingaurav @wangpengmit can you give a feedback here?

**Comment by RochMollero** [comment]
> @RochMollero
> I ran your code on tf 2.3 and nightly, i do not face the error reported above, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/b5bdc253d11a598e40dd13c8ab36a8bf/untitled418.ipynb).

precisely because you ran the working version only. the not working version is when you set 

 return [e+varr, varr3],

(without the 0.0*)

**Comment by rohan100jain** [comment]
You're right here. We have some logic that detects what variables are used within a custom_gradient function and that only works when there is actual variable read (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/eager/pywrap_tfe_src.cc#L3294) and not when a variable is simply passed through to the output. Right now we don't have plans to fix this immediately, so I'd recommend just doing 1.0*varr or something so that a read is triggered. 

On the other hand, contributions are welcome to fix this! One suggestion would be to look at the outputs from running the function (https://github.com/tensorflow/tensorflow/blob/679988320d2f11211cd24ee5a2b18ff52bc04ad7/tensorflow/python/ops/custom_gradient.py#L330) and see if there are any variables we missed and add those to the list.

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210528, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/3e0b70f9f97ab6ecb097c263851f8a59/43535.ipynb). Thanks!
