### ISSUE TITLE
Installation via Miniconda fails

### ISSUE THREAD

**Issue by update-freak** [tensorflow/tensorflow#43531]
**System information**
- OS Platform and Distribution: Windows 10 Version 2004 (Build 19041.508)
- TensorFlow installed from: with the code `conda install -c conda-forge tensorflow` 
- Python version: 3.8.5
- Installed using virtualenv? pip? conda?: yes, with conda
- GPU model and memory: NVIDIA GeForce GTX 860M 

**Describe the problem**
When trying to install the software, the following message appears:

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - tensorflow -> python[version='3.5.*|3.6.*|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|3.7.*']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/win-64::__cuda==8.0=0
  - feature:|@/win-64::__cuda==8.0=0

Your installed version is: 8.0

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. Install Miniconda3 Windows 64-bit (SHA 1f4ff67f051c815b6008f144fdc4c3092af2805301d248b56281c36c1f4333e5)
2. Install Spyder: `conda install -c anaconda spyder`
3. Install matplotlib: `conda install -c conda-forge matplotlib`
4. Install scipy: `conda install -c anaconda scipy`
5. Install sympy: `conda install -c anaconda sympy`
6. Install tensorflow: `conda install -c conda-forge tensorflow`

**Comment by bhack** [comment]
Win don't officially support conda here.
You have two solutions:
- Use the default install guide without Miniconda/Anaconda: https://www.tensorflow.org/install/pip
- Continue to use conda. But you need to ask support to the Conda project https://docs.anaconda.com/anaconda/user-guide/tasks/tensorflow/

**Comment by update-freak** [comment]
Thanks!
