### ISSUE TITLE
Import error | from pip | At ubuntu 18.04

### ISSUE THREAD

**Issue by Midhlaj2006** [tensorflow/tensorflow#43530]
System information
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from (source or binary):pypi
- TensorFlow version:2.0.0a0
- Python version:3.6.9
- Installed using virtualenv? pip? conda?:pip
- CUDA/cuDNN version:I don't have a cuda
- GPU model and memory: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller [1.9G]

### **Describe the problem**
I tried the code below
and I got the output something like this:

>Illegal instruction

 in my bash terminal

###**Provide the exact sequence of commands / steps that you executed before running into the problem**
**I created a new python3 virtual environment and ran the command:**

> $ pip install tensorflow==2.0.0a0

> $ pip install protobuf==3.10 #installed protobuf 

**Then I tested the code using:**

> $ python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"

**Comment by amahendrakar** [comment]
@Midhlaj2006,
Is there any specific reason you are installing an order release of TensorFlow? Please try installing TensorFlow v2.3 using the below commands and let us know if it works.
```
pip install --upgrade pip

pip install tensorflow
```

Thanks!

**Comment by amahendrakar** [comment]
Also, please go through similar issue [#40978](https://github.com/tensorflow/tensorflow/issues/40978) and let us know if it helps. Thanks!

**Comment by bhack** [comment]
You CPU `Processor x5-E8000` doesn't support AVX (but you can still build from source). See https://github.com/tensorflow/tensorflow/issues/19584

**Comment by Midhlaj2006** [comment]
> @Midhlaj2006,
> Is there any specific reason you are installing an order release of TensorFlow? Please try installing TensorFlow v2.3 using the below commands and let us know if it works.
> 
> ```
> pip install --upgrade pip
> 
> pip install tensorflow
> ```
> 
> Thanks!

It was brilliant but this don't help me

**Comment by amahendrakar** [comment]
@Midhlaj2006,
As per Intel's [product specification](https://ark.intel.com/content/www/us/en/ark/products/92124/intel-atom-x5-e8000-processor-2m-cache-up-to-2-00-ghz.html), your CPU doesn't support AVX. For more information, please take a look at the [hardware requirements](https://www.tensorflow.org/install/pip#hardware-requirements) to install TensorFlow with pip. 

Alternatively, you can [build TensorFlow from source](https://www.tensorflow.org/install/source) or use [Google Colab](https://colab.research.google.com/). Thanks!

**Comment by Midhlaj2006** [comment]
> @Midhlaj2006,
> As per Intel's [product specification](https://ark.intel.com/content/www/us/en/ark/products/92124/intel-atom-x5-e8000-processor-2m-cache-up-to-2-00-ghz.html), your CPU doesn't support AVX. For more information, please take a look at the [hardware requirements](https://www.tensorflow.org/install/pip#hardware-requirements) to install TensorFlow with pip.
> 
> Alternatively, you can [build TensorFlow from source](https://www.tensorflow.org/install/source) or use [Google Colab](https://colab.research.google.com/). Thanks!

Thanks brother, it works!👏
But I has some connection issues by now days 📡
Can I use colab offline?

**Comment by Midhlaj2006** [comment]
> @Midhlaj2006,
> As per Intel's [product specification](https://ark.intel.com/content/www/us/en/ark/products/92124/intel-atom-x5-e8000-processor-2m-cache-up-to-2-00-ghz.html), your CPU doesn't support AVX. For more information, please take a look at the [hardware requirements](https://www.tensorflow.org/install/pip#hardware-requirements) to install TensorFlow with pip.
> 
> Alternatively, you can [build TensorFlow from source](https://www.tensorflow.org/install/source) or use [Google Colab](https://colab.research.google.com/). Thanks!

I failed building from source too
but it worked with colab

Are there any offline version for colab, the network is too slow over here

**Comment by amahendrakar** [comment]
@Midhlaj2006,
Colab is not available offline. You need to be connected to the internet to access Google Colab. For more information please take a look at the [FAQs](https://research.google.com/colaboratory/faq.html). Thanks!

**Comment by Midhlaj2006** [comment]
Thanks for your responses
