### ISSUE TITLE
Ethos-U scratch tensors not allocated

### ISSUE THREAD

**Issue by mansnils** [tensorflow/tensorflow#43537]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
- TensorFlow installed from (source or binary):
- Tensorflow version (commit SHA if source): b023b033299a2e88a8f25980e234144657df5fc2
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Ethos-U

**Describe the problem**
Ethos-u relies on differentiating between having operator input tensors as subgraph inputs or not. It is depending on the offline planner and is using one or two additional operator input tensors (similar to scratch tensors, but part of the tflite file). We want these to remain as input tensors to the operator, but not as inputs to the subgraph. There has been a workaround for this, see PR: https://github.com/tensorflow/tensorflow/pull/42697
However it does not work if there is any CPU operator before the Ethos-U operator. Also a more general solution is wanted.

**Please provide the exact sequence of commands/steps when you ran into the problem**

**Comment by freddan80** [comment]
This can be closed now.

**Comment by mansnils** [comment]
Fixed
