### ISSUE TITLE
Tensorboard should Update Browser Location on Tab Changes

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#4354]
![image](https://cloud.githubusercontent.com/assets/51059/18482024/88fb96e0-79ac-11e6-838e-3b2a6094b16a.png)

Right now changing tabs does not change the location which means browser refresh, etc loses the current tab.

**Comment by drpngx** [comment]
Is this still current?

**Comment by cancan101** [comment]
Yes, the location still does not change on navigation.

**Comment by drpngx** [comment]
Sorry to be petulant, but you tried with the latest version? Which browser/architecture?

**Comment by cancan101** [comment]
i am using the newest docker image: `gcr.io/tensorflow/tensorflow:latest-devel-gpu` and Chrome.

**Comment by dandelionmane** [comment]
Yeah, this is a regression in the pip package. It still works inside Google.

**Comment by dandelionmane** [comment]
This should be fixed now. Please reopen on our new repo at tensorflow/tensorboard if it reoccurs.
