### ISSUE TITLE
[MLIR / MHLO ]: tf_to_gpu_binary  Internal: Lowering to GPU kernels failed.

### ISSUE THREAD

**Issue by powderluv** [tensorflow/tensorflow#43556]
I am using **tf_to_gpu_binary** to convert the following mlir file to a gpu kernel 

```
func @abs(%arg0: tensor<*xf32>) -> tensor<*xf32> {
 %0 = "tf.Abs"(%arg0) { }
 : (tensor<*xf32>) -> tensor<*xf32>
 return %0 : tensor<*xf32>
}
```

On TF top of master (SHA 7f5b8ad3708d0e2cd98e63714352df60b772db36)  it fails with:
(tf_env) foo@bar:$ MLIR_CRASH_REPRODUCER_DIRECTORY=. ./build/install/bin/tf_to_gpu_binary --input=tf_abs.mlir --output=abs_kernel.o
loc("-":2:7): error: failed to legalize operation 'mhlo.abs' that was explicitly marked illegal
loc("-":0:0): error: A failure has been detected while processing the MLIR module, a reproducer has been generated in './mlir_reproducer_ironman-725e3dc1-43003-5b01dc8776cbc.mlir'
2020-09-24 23:54:07.367852: E tensorflow/compiler/mlir/tools/kernel_gen/tf_to_gpu_binary.cc:95] Internal: Lowering to GPU kernels failed.

**MLIR CRASH Repro:**

```

// configuration: -pass-pipeline='func(xla-legalize-tf{allow-partial-conversion=false device-type=INVALID_DEVICE_TYPE legalize-chlo=true use-tf2xla-fallback=false}, materialize-broadcast, unfuse-batch-norm), unknown<mlir::mhlo::{anonymous}::HloLegalizeToLhlo>{results-escape-function=true}, func(buffer-placement, unknown<{anonymous}::CopyRemovalPass>), shape-to-descriptors, canonicalize, func(unknown<mlir::{anonymous}::LhloLegalizeToLinalgPass>, unknown<mlir::lmhlo::{anonymous}::LhloFuseLinalgPass>{tile-sizes= use-parallel-loops=true}, convert-linalg-to-parallel-loops, canonicalize, cse, unknown<xla::mlir_gpu::{anonymous}::FuseInnerParallelLoopsPass>, cse, unknown<xla::mlir_gpu::{anonymous}::StoreForwardingPass>, unknown<xla::mlir_gpu::{anonymous}::DeadTempBufferRemovalPass>, canonicalize, cse, unknown<xla::mlir_gpu::{anonymous}::MapParallelLoopsPass>), convert-parallel-loops-to-gpu, func(canonicalize, cse, unknown<mlir::mhlo::{anonymous}::LegalizeTrigonometricToApproximationPass>, unknown<xla::mlir_gpu::{anonymous}::MoveScalarComputationsIntoGpuLaunchPass>), gpu-kernel-outlining, func(unknown<xla::mlir_gpu::{anonymous}::RewriteKernelSignaturePass>), lower-affine, convert-scf-to-std'
// note: verifyPasses=true


module {
  func @abs(%arg0: tensor<*xf32>) -> tensor<*xf32> {
    %0 = "tf.Abs"(%arg0) : (tensor<*xf32>) -> tensor<*xf32>
    return %0 : tensor<*xf32>
  }
}

```

**Comment by sherhut** [comment]
`tf_to_gpu_binary` does not support unranked code generation, it requires a ranked input. For the unranked case, you can generate a version for a 1d vector and use that with some host-side glue code to transform the unranked tensor into a 1d vector and the inverse for the result.

If you want to have that glue code also be generated, you need to use `tf_to_kernel`, which will produce a library file that contains both host and device code. Your input is also one of the examples.

Likely, this had not landed when you tried.
