### ISSUE TITLE
Decoding error during vocabulary loading from TextVectorization layer

### ISSUE THREAD

**Issue by mikolajkania** [tensorflow/tensorflow#43559]
**Intro**
Error occurs within get_vocabulary() method from TextVectorization when one of tokens can't be decoded. The exact place in a code is string_lookup's get_vocabulary() method:

`return [x.decode(self.encoding) for _, x in sorted(zip(values, keys))]`

**How to reproduce?**
```
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

text = 'Był to świetny pomysł, bo punktował Prawo i Sprawiedliwość tam, gdzie jest ono najsłabsze, mimo że udaje najsilniejsze. Uderzał w wizerunek państwa dobrobytu, które nikogo nie zostawia z tyłu i wyrównuje szanse. Tutaj mamy pewnego rodzaju déjà vu.'

vectorize_layer = TextVectorization()
vectorize_layer.adapt([text])
print(vectorize_layer.get_vocabulary())
```

Simpler code:

```
values = [1]
keys = [b'warszawie\xc2']
[x.decode('utf-8') for _, x in sorted(zip(values, keys))]
```

> Error: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 9: unexpected end of data

**Fix**

I was able to fix it simply by writing my own _get_vocabulary() method, just by ignoring decoding errors which are rare but frustrating:

```
def _get_vocabulary():
    keys, values = vectorize_layer._index_lookup_layer._table_handler.data()
    return [x.decode('utf-8', errors='ignore') for _, x in sorted(zip(values, keys))]
```

***Can option to ignore decoding errors be passed to string_lookup?***

- Windows 10 
- TensorFlow 2.2
- Python 3.8

**Comment by amahendrakar** [comment]
@mikolajkania,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by mikolajkania** [comment]
@amahendrakar I updated *how to reproduce* part - you can run it easily now as script/

**Comment by amahendrakar** [comment]
@mikolajkania,
Thank you for the update. I was able to run the code without any issues with TF v2.3. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/8ba8ae4260d781f55361850b76100b32/43559.ipynb#scrollTo=CsRQcxJcgi2B).

Could you please update TensorFlow to v2.3 and check if you are still facing the same error. Thanks!

**Comment by mikolajkania** [comment]
@amahendrakar I tried again running this script:

```
import tensorflow as tf
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

print(tf.__version__)

text = 'Był to świetny pomysł, bo punktował Prawo i Sprawiedliwość tam, gdzie jest ono najsłabsze, mimo że udaje najsilniejsze. Uderzał w wizerunek państwa dobrobytu, które nikogo nie zostawia z tyłu i wyrównuje szanse. Tutaj mamy pewnego rodzaju déjà vu.'

vectorize_layer = TextVectorization()
vectorize_layer.adapt([text])
print(vectorize_layer.get_vocabulary())
```

Response is:

2.3.0
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 4: unexpected end of data

on Python 3.8.5. But I tested it on Python 3.6.9 that you used and it worked. So it looks that the problem is with combination:

*Python 3.8.X and Tensorflow 2.3*

Can you test it that why on Collab or your local machine?

**Comment by amahendrakar** [comment]
> Can you test it that why on Collab or your local machine?

@mikolajkania,
I was able to run the script without any issues with Python v3.8.5 and TensorFlow v2.3.1. Please check the attached screenshot for reference. 
![Screenshot 2020-10-10 at 9 11 59 PM](https://user-images.githubusercontent.com/57165142/95659269-7c39b780-0b3d-11eb-97f2-1e77287e3735.png)

Thanks!

**Comment by mikolajkania** [comment]
@amahendrakar can you test it on Windows? It works for me on Ubuntu from WSL2 (Windows Subsystem For Linux):

![obraz](https://user-images.githubusercontent.com/14984193/95675567-7fbe5480-0bb8-11eb-8662-f90335b51f5f.png)

But not on Windows itself (Python 3.8.5):

![obraz](https://user-images.githubusercontent.com/14984193/95675610-d7f55680-0bb8-11eb-997e-b8352d4a2faa.png)

It also worked on Windows on version 3.6.9 (as pasted above).

**Comment by mikolajkania** [comment]
@amahendrakar hi, any news?

**Comment by amahendrakar** [comment]
@mikolajkania,
Sorry for the delayed response. I do not have a Windows machine to test the code. Could you please try running the code in a virtual environment and check if you are facing the same issue? Thanks!

**Comment by yaniv256** [comment]
It's a Windows issue. The same code runs on Colab without generating the error.

**Comment by MahdiNicoo** [comment]
This happens in:
    os: Windows
    python: >= 3.7
    tf: >= 2.3



Installing `python == 3.6`  worked in my case.

**Comment by princyok** [comment]
I'm currently running into this problem as well with `TextVectorization.get_vocabulary`. 

OS: Windows 10
Python: 3.8.5
TensorFlow: 2.3.0

**Comment by amahendrakar** [comment]
@princyok,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by ClementViricel** [comment]
Hi, 
I'm currently running into this problem too as well with TextVectorization.get_vocabulary.

OS: Windows 10
Python: 3.8.8
TensorFlow: 2.4.2

**Comment by princyok** [comment]
@ClementViricel I believe the cause of the issue is tensorflow being unable to handle certain characters when working on Windows. A crappy temporary solution is to find such characters and omit them if possible. I reported [the issue here](https://github.com/tensorflow/tensorflow/issues/47022).

**Comment by tusharvickey1999** [comment]
Solved this problem by changing default encoding for windows to utf-8. To change, go to `Language Settings -> Administrative Language settings -> change system locale -> select beta: Use Unicode UTF-8 for worldwide language support`. Restart. Done

Thanks.

**Comment by tilakrayal** [comment]
I was able to reproduce the issue on tf-nightly 2.10.0-dev20220719. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/8d7a7e75568d4d5e517b55441669bff4/untitled524.ipynb). Thank you!

**Comment by hafedh-hichri** [comment]
**FINALLY AFTER 2 HOURS OF DEBUGGING**
I won't go into much details in here because i am building my own tokenizer for a transformer application

PS : this worked for me 
* just add your own `get_vocabulary` function based on what i have written below 

```
class OutputTextProcessor(TextVectorization):
    def __init__(self):
        super(OutputTextProcessor, self).__init__(standardize=self.tf_lower_and_split_punct)

    def tf_lower_and_split_punct(self, text): # name of the function is from example on https://www.tensorflow.org/text/tutorials/nmt_with_attention#the_encoderdecoder_model
        # Strip whitespace.
        text = tf.strings.strip(text)

        text = tf.strings.join(['[START]', text, '[END]'], separator=' ')
        return text
    def get_vocabulary(self):
        # _layer.get_vocabulary
        keys, values = self._lookup_layer.lookup_table.export()
        # print(self._lookup_layer.lookup_table.export())
        vocab = []
        for i in keys : 
            try :
                vocab.append(i.numpy().decode('utf-8'))
            except :
                vocab.append(i.numpy().decode('ISO-8859-1'))
        return vocab
```

Hope this helps
