### ISSUE TITLE
Clicking on Image in Tensorboard Should Open in New Window

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#4355]
Right now the image may be squashed and hard to read:
![image](https://cloud.githubusercontent.com/assets/51059/18482149/0324d058-79ad-11e6-83a4-d782b523065d.png)

The current solution is to copy the image URL and manually open in a new tab.

**Comment by drpngx** [comment]
Is this still current?

**Comment by cancan101** [comment]
there is an inline maximization option (which causes a reflow) but no open in new tab

**Comment by drpngx** [comment]
What browser?

**Comment by cancan101** [comment]
Chrome.

**Comment by dandelionmane** [comment]
@cancan101 Why do you need open in new tab? Why not just use the "true size" and "maximize image" buttons?

**Comment by dandelionmane** [comment]
Closing since we didn't hear a response. Feel free to reopen at https://github.com/tensorflow/tensorboard/issues
