### ISSUE TITLE
Test code for tensorflow source code

### ISSUE THREAD

**Issue by meSajied** [tensorflow/tensorflow#43567]
Sometimes, it is hard to debug the code without testing, or it is needed to write test for code.
In this case, if we create tests manually, then it will be needed to delete the test code directory or create a new branch without tests to send pull request.
Is it possible to take into account?

**Comment by mihaimaruseac** [comment]
`git add` (with the `-p` flag too) allows you to control which files/patches to add to a commit. You can push only a few commits to a branch for pull requests.

In general, we recommend each PR to also contain tests. There are multiple benefits to having tests in the same PR: we can see that the test fails without the fix and passes with it, we can see usage pattern, we can prevent future regression when a new change might break similar functionality.

**Comment by meSajied** [comment]
@mihaimaruseac 
Thank you, actually I know that. But I found some library has code for testing. Tht  is why I asked.

**Comment by meSajied** [comment]
@mihaimaruseac 
Thank you...
