### ISSUE TITLE
Missing 1.15.4 release on Docker Hub

### ISSUE THREAD

**Issue by lissyx** [tensorflow/tensorflow#43564]
I'm sorry if this is not the proper place to file that kind of issue, but I could not find a better place to report that issue. If such a place exist, please advise me of the details, I'll happily forward my request.

So, 1.15.4 has been released yesterday, containing a fix for CuDNN usage. While working on upgrading our codebase to refer that new version, I stumbled upon the fact that the TensorFlow Docker Hub does not offer any image after 1.15.2: as you can see on that link https://hub.docker.com/r/tensorflow/tensorflow/tags?page=1&name=1.15 there is no 1.15.3 nor 1.15.4.

I obviously don't know the details of your release process, but I don't think this is expected, and the lack of 1.15.3 makes me thinking this is not just a delay in building / uploading.

So, it would really be nice if the 1.15.4 images could be built and pushed to Docker Hub :).

**Comment by mihaimaruseac** [comment]
It seems we were missing this from the release process. 1.15.3 docker images have just been updated (we were testing if things work) and 1.15.4 and the other tags for the recent patch releases are currently building.

**Comment by lissyx** [comment]
@mihaimaruseac Thanks for the quick handling, it looks like it is working as expected, this looks fixed to me :)

**Comment by bhack** [comment]
@lissyx Thanks, please close the ticket if it is ok for you.
