### ISSUE TITLE
Playground is not in https

### ISSUE THREAD

**Issue by LouisCAD** [tensorflow/tensorflow#4356]
It should be as the rest of tensorflow website is in https

**Comment by xmbrst** [comment]
@LouisCAD , how did you get to the playground?

**Comment by LouisCAD** [comment]
@xmbrst By following the link advertised in [this I/O 16 talk](https://www.youtube.com/watch?v=3dXQxSI3XDY), which points to [playground.tensorflow.org](http://playground.tensorflow.org/)

**Comment by drpngx** [comment]
Closing, and looping internally. Thanks for reporting!
