### ISSUE TITLE
FileIO.read signature differs from Python stdlib File.read interface

### ISSUE THREAD

**Issue by cooijmanstim** [tensorflow/tensorflow#4357]
`FileIO` does not quack quite like a File object; its `read` method should take an optional `size` argument. This discrepancy makes `GFile` not a drop-in replacement for `File`, which makes it hard to port code between Google and the outside world.

`File.read` API doc: https://docs.python.org/2/library/stdtypes.html#file.read
Current `FileIO.read`: https://github.com/tensorflow/tensorflow/blob/915b02917db21de5a0ae304a067aedb0b5dd759d/tensorflow/python/lib/io/file_io.py#L98

**Comment by rohan100jain** [comment]
FileIO.read() now supports a size argument. Closing bug now.

**Comment by vrv** [comment]
I added tell() and seek() and read(n) in the following commits:
https://github.com/tensorflow/tensorflow/commit/63a7a30e6bd091f87be1de2305c6d882d68ba6a8
https://github.com/tensorflow/tensorflow/commit/cb07991bd77490055eea4139230743f4573a8318

I have not yet tested that this satisfies all of the python File API, but we're slowly getting there.
