### ISSUE TITLE
tensorflow.keras.wrappers.scikit_learn KerasClassifier using 1% of GPU

### ISSUE THREAD

**Issue by hanzigs** [tensorflow/tensorflow#43575]
Hi,
Having tf 2.3.0 and keras 2.4.3
GridSearchCV not using full GPU
```
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
BatchSize = [100,200,300,400,500,600,700,800,900,1000]
Epochs = [100,200,300,400,500,600,700,800,900,1000]

    def create_model():
    	model = Sequential()
    	model.add(Dense(int(num_cols/2), input_dim=num_cols, activation='relu'))
    	model.add(Dense(1, activation='sigmoid'))
    	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    	return model
    model = KerasClassifier(build_fn=create_model, verbose=0)
    param_grid = dict(batch_size=BatchSize , epochs=Epochs )
    grid = GridSearchCV(model, cv = 3, param_grid=param_grid,n_jobs=-1)
    grid_result = grid.fit(X_train, y_train)         
    best_hyperparameters = grid_result.best_params_
```
i have set
```
from tensorflow.python.client import device_lib
assert 'GPU' in str(device_lib.list_local_devices())
```
![image](https://user-images.githubusercontent.com/30790120/94322155-0712a200-ffd5-11ea-83bf-c057628c71cf.png)

Is this correct?

**Comment by amahendrakar** [comment]
@hanzigs,
Could you please run the below code and share the output with us
```
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
```

By default, TensorFlow maps nearly all of the GPU memory of all GPUs (subject to CUDA_VISIBLE_DEVICES) visible to the process. Please take a look at [this](https://www.tensorflow.org/guide/profiler#gpu_kernel_stats) memory profile tool and let us know if you are facing the same issue. Thanks!

**Comment by hanzigs** [comment]
![image](https://user-images.githubusercontent.com/30790120/94626641-db5a2980-02fe-11eb-992b-66e1f107f054.png)

Does this mean there is no GPU or GPU is not configured?

**Comment by hanzigs** [comment]
In Spyder, i get following error

![image](https://user-images.githubusercontent.com/30790120/94745881-ef656000-03be-11eb-8c33-897b4c986a07.png)

i'm using

![image](https://user-images.githubusercontent.com/30790120/94745889-f3917d80-03be-11eb-8cac-97f4c3eac234.png)

![image](https://user-images.githubusercontent.com/30790120/94745913-0015d600-03bf-11eb-8ce6-15824708f4ac.png)

As per here
https://www.tensorflow.org/install/source_windows#tested_build_configurations

Do i have to change to cuDNN 7.4?

**Comment by hanzigs** [comment]
Thanks, Above error happened first time, in second run it was not there. Not sure why?
