### ISSUE TITLE
Problem loading model trained with EfficientNetB0 

### ISSUE THREAD

**Issue by mesquita** [tensorflow/tensorflow#43576]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.6.9
- CUDA/cuDNN version: 10.2
- GPU model and memory: GeForce GTX 1660 Ti with Max-Q Design 6 GB

**Describe the current behavior**
Error using tensorflow.keras.applications EfficientNetB0.

When I load my trained model, I have the following warnings (I only copied part of them here, you can check the rest in the colab link that is below:

```
WARNING:tensorflow:Importing a function (__inference_block2a_activation_layer_call_and_return_conditional_losses_344566) with ops with custom gradients. Will likely fail if a gradient is requested.
WARNING:tensorflow:Importing a function (__inference_block2a_activation_layer_call_and_return_conditional_losses_344566) with ops with custom gradients. Will likely fail if a gradient is requested.
```
I basically save the model and load it again in the colab link below and I get this message.

Because of this I cannot continue training my model if I wish to do so. Am I missing something here?

**Standalone code to reproduce the issue**
Link to COLAB:
https://colab.research.google.com/drive/1Vjb65Y7E_FDbVZm_ZDs6ZP3yjjAN-rr5?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

I am basically using the same code from here: https://keras.io/examples/vision/image_classification_efficientnet_fine_tuning/
for the colab example. Am I doing something wrong?

**Comment by mesquita** [comment]
I switched from activation="swish" (default) to activation="relu" and the problem was gone. Now I don't know why this happens while using swish.

**Comment by ravikyram** [comment]
I was able to reproduce the issue in colab. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/e060bc6ed459d44c31121d0a1684e962/untitled398.ipynb).Thanks!

**Comment by gowthamkpr** [comment]
This might be related to this issue #40166 Please take a look at it and let me know if it helps. Thanks!

**Comment by mesquita** [comment]
> This might be related to this issue #40166 Please take a look at it and let me know if it helps. Thanks!

Yes, I think it is related to that. 
So there's no solution right now for this problem? 

Thank you!

**Comment by gowthamkpr** [comment]
@mesquita You can close this issue as this is a duplicate of this [issue](https://github.com/tensorflow/tensorflow/issues/40166) and we can track it there. Thanks!

**Comment by mesquita** [comment]
Sure
