### ISSUE TITLE
tf-nightly fails to initialize TPUs

### ISSUE THREAD

**Issue by tsc2017** [tensorflow/tensorflow#43581]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):  2.4.0-dev20200925
- Python version: 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**

Everything was fine 1.5 days ago,
 until I created a TPU node half a day ago with TPU software version "nightly":
```
gcloud compute tpus create node-123 \
	--zone=us-central1-f \
	--network=default \
    --accelerator-type=v2-8 \
    --range=10.123.0.0 \
	--preemptible \
    --version=nightly
```
and tried to initialize it:
```
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

TPU_NAME='node-123'
ZONE='us-central1-f'

resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu=TPU_NAME, zone=ZONE)
tf.tpu.experimental.initialize_tpu_system(resolver)
```
The output was
```
INFO:tensorflow:Initializing the TPU system: node-123
```
and I was stuck with the initialization.

I believe this is a new bug in `2.4.0-dev20200925`.
I also suggest that there should be more tf-nightly versions to choose from when creating TPUs.

**Comment by tsc2017** [comment]
A temporary fix I found is to change the software version of the TPU back to `2.4.0.dev20200924` before initializaiton:
```
from cloud_tpu_client import Client
c = Client(tpu=TPU_NAME, zone=ZONE)
c.configure_tpu_version('2.4.0.dev20200924', restart_type='ifNeeded')
```

**Comment by mkuchnik** [comment]
I am also facing this issue. The temporary fix worked.

**Comment by Saduf2019** [comment]
@tsc2017 
Please update as per above comment.

**Comment by tsc2017** [comment]
I believe this bug has been fixed in the latest `tf-nightly`. Closing Issue.
