### ISSUE TITLE
Slow training with tfRecords and tf.functions

### ISSUE THREAD

**Issue by quartermaine** [tensorflow/tensorflow#43585]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): conda
- TensorFlow version (use command below): 2.2
- Python version: 3.7
- Bazel version (if compiling from source): unknown
- GCC/Compiler version (if compiling from source): unknown
- CUDA/cuDNN version: 11.0
- GPU model and memory: 2 Nvidia RTX 2080 Ti graphics cards

**Describe the current behavior**
I have been trying to train a 3D CNN with tfRecords and also do augmentation on the fly when reading the records using @tf.function decorator and tf.numpy_function but the training is horribly slow.

**Standalone code to reproduce the issue**

This is the function for reading the tfRecords and make the augmentation on the fly
```
def input_fn(filenames, subset, batch_size, buffer_size=512, data_augmentation=True):
    # Args:
    # filenames:   Filenames for the TFRecords files.
    # subset:      Subset to make either train, valid, test.
    # batch_size:  Return batches of this size.
    # buffer_size: Read buffers of this size. The random shuffling
    #              is done on the buffer, so it must be big enough.

    # Create a TensorFlow Dataset-object which has functionality
    # for reading and shuffling data from TFRecords files.
    dataset = tf.data.TFRecordDataset(filenames=filenames)

    # Parse the serialized data in the TFRecords files.
    # This returns TensorFlow tensors for the image and labels.
    dataset = dataset.map(parse_example, num_parallel_calls=8)

    if subset == 'train' or subset =='valid':
        # Allow infinite reading of the data.
        dataset = dataset.repeat()
    else :
        dataset = dataset.repeat(1)

    if subset == 'train':
        dataset = dataset.shuffle(buffer_size=buffer_size)

    ''' DATA AUGMENTATION '''
    if (subset != 'test' and data_augmentation == True):
        dataset = dataset.map(elastic3D)
        dataset = dataset.map(flip3D)
        dataset = dataset.map(rotation3D)
        dataset = dataset.map(blur3D)


    # Get a batch of data with the given size.
    dataset = dataset.batch(batch_size)

    if subset == 'train':
        dataset = dataset.prefetch(16)

    return dataset

```

This is one function that I use in the map for augmentation
```
@tf.function
def flip3D(volume, label):

    def flip(volume):
        choice = np.random.randint(3)
        if choice == 0: # flip on x
            volume_flip = volume[::-1, :, :, :]
        if choice == 1: # flip on y
            volume_flip = volume[:, ::-1, :, :]
        if choice == 2: # flip on z
            volume_flip = volume[:, :, ::-1, :]

        return volume_flip

    augmented_volume = tf.numpy_function(flip, [volume], tf.float32)

    return augmented_volume, label
```

**Other info / logs** Include any logs or source code that would be helpful to

**Comment by amahendrakar** [comment]
@quartermaine,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and the dataset you are using. 

Also, could you please update TensorFlow to v2.3 and check if you are facing the same issue. Thanks!

**Comment by quartermaine** [comment]
@amahendrakar 
I have attach the code that I use to train the CNN 
[scripts.zip](https://github.com/tensorflow/tensorflow/files/5294832/scripts.zip)

**Comment by amahendrakar** [comment]
@quartermaine,
Could you please upload it to your Google Drive and share the link of the folder with us. Thanks!

**Comment by quartermaine** [comment]
@amahendrakar ,

I am trying to upload because its quite big file.

**Comment by quartermaine** [comment]
@amahendrakar 
this is the link to the [data](https://drive.google.com/file/d/1FVg2Ku5U3eS5MpiELYxMeEKM6AVwiCbw/view?usp=sharing)

**Comment by quartermaine** [comment]
@amahendrakar ,

I am trying to upload because its quite big file.

**Comment by amahendrakar** [comment]
@quartermaine,
Thank you for the update. I am unable to view the files from the given link. Could you please provide the required permissions to access the files as well? Thanks!

**Comment by quartermaine** [comment]
@amahendrakar,

Can you try this [link](https://drive.google.com/file/d/1FVg2Ku5U3eS5MpiELYxMeEKM6AVwiCbw/view?usp=sharingl).

**Comment by amahendrakar** [comment]
@quartermaine,
On running the code, I am facing a different error stating `Invalid argument:  Input to reshape is a tensor with 5975926 values, but the requested shape has 2987963`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/f8d38dfd91bc67fe466bb5f8c9566ff8/43585.ipynb). Thanks!
