### ISSUE TITLE
tf.summary.create_file_writer does not write any event file and tensorboard show nothing

### ISSUE THREAD

**Issue by JosepLeder** [tensorflow/tensorflow#43584]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution : Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.8.3
- CUDA/cuDNN version: 10.1/7.6
- GPU model and memory: RTX 2070super 8GB

**Describe the current behavior**
I have tried the example of https://www.tensorflow.org/api_docs/python/tf/summary
```python
import tensorflow as tf

writer = tf.summary.create_file_writer("/tmp/mylogs")
with writer.as_default():
  for step in range(100):
    # other model code would go here
    tf.summary.scalar("my_metric", 0.5, step=step)
    writer.flush()
```
and it works fine. However, when I migrate some codes from tf 1.X to tf 2.2 using tf_upgrade_v2 script, and add some codes to store some data in files, the summary_writer doesn't create any folder or event files.
``` python
#!/usr/bin/env python
import tensorflow as tf

tf.compat.v1.disable_eager_execution()
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        # Currently, memory growth needs to be the same across GPUs
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = tf.config.experimental.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        # Memory growth must be set before GPUs have been initialized
        print(e)

def start_experiment():
    file_writer = tf.summary.create_file_writer("/tmp/{}_{}".format('none', 0))

    trainer = Trainer(file_writer=file_writer)
    trainer.train()
    file_writer.close()


class Trainer(object):
    def __init__(self, file_writer):
        self.file_writer = file_writer

    def train(self):
        info = {'tcount': 0, 'int_rew': 1, 'eprew':1, 'opt_tot':1}
        while True:
            # record data to tensorboard
            with self.file_writer.as_default():
                x = int(info['tcount'])
                tf.summary.scalar("int_reward", info['int_rew'], step=x)
                tf.summary.scalar("ext_reward", info['eprew'], step=x)
                tf.summary.scalar("total_loss", info['opt_tot'], step=x)
                self.file_writer.flush()
            info['tcount'] += 1
            if info['tcount'] > 100:
                break


if __name__ == '__main__':
    start_experiment()
```
I removed some detail codes to make it more clear. The training part of codes works fine, and it just doesn't record anything. 
**Describe the expected behavior**
It should create a folder in /tmp/none_0 and write some event file, but it did nothing.

**Comment by bhack** [comment]
Can you minimize the code/imports? 
It will make easy for us to copy, paste and run your code example to reproduce your issue.

**Comment by JosepLeder** [comment]
> Can you minimize the code/imports?
> It will make easy for us to copy, paste and run your code example to reproduce your issue.

I updated my code to remove all the unnecessary codes and imports as above. It still records nothing. The folder "/tmp/none_0" is not created. And there are no event files. If you would like to run my code and help me find the problem, that would be really helpful. Thanks.

**Comment by bhack** [comment]
@JesepLeder I think that there is a note in the documentation for running in the graph:

> Default writers do not (yet) propagate across the @tf.function execution boundary - they are only detected when the function is traced - so best practice is to call writer.as_default() within the function body, and to ensure that the writer object continues to exist as long as the @tf.function is being used

As you see in the graph function execution case is still inside `tf.function` perimeter. So please be aware about `tf.compat.v1.disable_eager_execution()`:

```
writer = tf.summary.create_file_writer("/tmp/mylogs/tf_function")

@tf.function
def my_func(step):
  with writer.as_default():
    # other model code would go here
    tf.summary.scalar("my_metric", 0.5, step=step)

for step in tf.range(100, dtype=tf.int64):
  my_func(step)
  writer.flush()
```

**Comment by Saduf2019** [comment]
@Joseph-Rance 
Please update as per above comment, if possible could you try on tf-nightly and let us know if the issue exist, please share a colab gist with the issue reported.

**Comment by Joseph-Rance** [comment]
@Saduf2019 Not sure you meant to @ me in that last comment?

**Comment by Saduf2019** [comment]
@JosepLeder 
Is this still an issue, can you follow bhack comment and let us know.

**Comment by JosepLeder** [comment]
> @JosepLeder I think that there is a note in the documentation for running in the graph:
> 
> > Default writers do not (yet) propagate across the @tf.function execution boundary - they are only detected when the function is traced - so best practice is to call writer.as_default() within the function body, and to ensure that the writer object continues to exist as long as the @tf.function is being used
> 
> As you see in the graph function execution case is still inside `tf.function` perimeter. So please be aware about `tf.compat.v1.disable_eager_execution()`:
> 
> ```
> writer = tf.summary.create_file_writer("/tmp/mylogs/tf_function")
> 
> @tf.function
> def my_func(step):
>   with writer.as_default():
>     # other model code would go here
>     tf.summary.scalar("my_metric", 0.5, step=step)
> 
> for step in tf.range(100, dtype=tf.int64):
>   my_func(step)
>   writer.flush()
> ```

I add `@tf.function` to my functions as follows:
``` python
#!/usr/bin/env python
import tensorflow as tf

tf.compat.v1.disable_eager_execution()
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        # Currently, memory growth needs to be the same across GPUs
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = tf.config.experimental.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        # Memory growth must be set before GPUs have been initialized
        print(e)

@tf.function
def start_experiment():
    trainer = Trainer()
    trainer.train()


class Trainer(object):

    def __init__(self):
        pass

    @tf.function
    def train(self):
        file_writer = tf.summary.create_file_writer("/tmp/{}_{}".format('none', 0))
        info = {'tcount': 0, 'int_rew': 1, 'eprew':1, 'opt_tot':1}
        while True:
            # record data to tensorboard
            with file_writer.as_default():
                x = int(info['tcount'])
                tf.summary.scalar("int_reward", info['int_rew'], step=x)
                tf.summary.scalar("ext_reward", info['eprew'], step=x)
                tf.summary.scalar("total_loss", info['opt_tot'], step=x)
                file_writer.flush()
            info['tcount'] += 1
            if info['tcount'] > 100:
                break
        file_writer.close()


if __name__ == '__main__':
    start_experiment()
```
But it still doesn't work. If I remove `tf.compat.v1.disable_eager_execution()`, it works as the document said. However, I have to change lots of code using placeholder after using tf_upgrade_v2 if I remove `tf.compat.v1.disable_eager_execution()`. I am not sure if there is a way  I can use the writer without remove that code.

**Comment by bhack** [comment]
You can try to take a look at https://www.tensorflow.org/tensorboard/migrate
