### ISSUE TITLE
tensorflow returns error 132 on macbook pro 2009

### ISSUE THREAD

**Issue by fabiogeraci** [tensorflow/tensorflow#43599]
Hello, i am trying to run tensorflow, with the following setup:
macbook mid 2009
Ubuntu 20.04
Pycharm latest version
python 3.7.9, installed with pycharm

now if i use tensorflow 2.3.1 i get an error 132
as suggested in others posts i down grade to tensorflow 1.5 but i get a different error; ModuleNotFoundError: No module named 'tensorflow.python.platform' but it is install on the virtual environment.

is there a fix or a work around?

**Comment by Saduf2019** [comment]
@fabiogeraci 
Please refer to these issues and let us know if it helps: #42438 [link](https://stackoverflow.com/questions/33977273/no-module-named-tensorflow-python-platform), [link1](https://github.com/tensorflow/tensorflow/issues/374), [this comment](https://github.com/tensorflow/tensorflow/issues/40556#issuecomment-647536055).
You can try: conda install tensorflow

Can you please share the error log of both the errors, as you have not filled the issue template which makes it difficult to analyse.

**Comment by fabiogeraci** [comment]
i have attached the log file.

when you say conda install tensorflow, do you mean on a terminal or inside pycharm?

[idea.log](https://github.com/tensorflow/tensorflow/files/5288734/idea.log)

**Comment by Saduf2019** [comment]
@fabiogeraci 
We have support for 2.x, please try on 2.x and let us know if you face any issues.

**Comment by fabiogeraci** [comment]
> @fabiogeraci
> We have support for 2.x, please try on 2.x and let us know if you face any issues.

I have tried all the version from and i get the same result, also tried to run anaconda and tensorflow crashes that too.

i added cpus info

> processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Core(TM)2 Duo CPU     P7550  @ 2.26GHz
stepping	: 10
microcode	: 0xa0b
cpu MHz		: 2255.338
cache size	: 3072 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm pti tpr_shadow vnmi flexpriority dtherm
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 4510.67
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual

**Comment by fabiogeraci** [comment]
any news, please?

**Comment by ymodak** [comment]
Apologies for the delay in response. Were you able to install TF 2.3 in virtual env successfully?
