### ISSUE TITLE
RuntimeError: Fill only currently supports int32, int64, float32, bool, string for input 1, got 9.Node number 412 (FILL) failed to invoke.

### ISSUE THREAD

**Issue by le8888e** [tensorflow/tensorflow#43596]
Hi,
I tried to run tflite model with INT8 post training. There is  no error converting .pb to .tflite. But error occurs when run inference on INT8 tflite model. BTW, there is no error when run inference on FP32 tflite model.

**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from : bianry
- TensorFlow version : tf-nightly 2.4.0-dev20200917

**Provide the text output from tflite_convert**

[{'name': 'input_x', 'index': 0, 'shape': array([ 1, 50], dtype=int32), 'shape_signature': array([-1, 50], dtype=int32), 'dtype': <class 'numpy.int32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
[{'name': 'output/y_hat', 'index': 3339, 'shape': array([   1, 2363], dtype=int32), 'shape_signature': array([  -1, 2363], dtype=int32), 'dtype': <class 'numpy.int8'>, 'quantization': (0.00390625, -128), 'quantization_parameters': {'scales': array([0.00390625], dtype=float32), 'zero_points': array([-128], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
Traceback (most recent call last):
  File "run_tflite.py", line 67, in <module>
    interpreter.invoke()
  File "/home/ai/anaconda5/envs/tf-nightly2.4/lib/python3.6/site-packages/tensorflow/lite/python/interpreter.py", line 539, in invoke
    self._interpreter.Invoke()
RuntimeError: Fill only currently supports int32, int64, float32, bool, string for input 1, got 9.Node number 412 (FILL) failed to invoke.

**Standalone code to reproduce the issue** 
Convert:

##INT8
converter.optimizations = [tf.lite.Optimize.DEFAULT]
def representive_dataset_gen():
    num_calibration_steps = 10
    for i in range(num_calibration_steps):
        random_num = np.random.random_integers(0,10000, size=[50]).astype('int32')
        random_input = np.expand_dims(random_num, 0)
        yield [random_input]

converter.representative_dataset = representive_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS, tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8
    
converter.experimental_new_converter = True
tflite_model = converter.convert()

Inference:
import tensorflow as tf

model_path = './model_int8.tflite'

interpreter = tf.lite.Interpreter(model_path=model_path)

interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
print(str(input_details))

output_details = interpreter.get_output_details()
print(str(output_details))

input_arr = np.random.random_integers(0,10000, size=[50])
input_arr_expanded = np.expand_dims(input_arr, 0)

input_arr_expanded = input_arr_expanded.astype('int32')

interpreter.set_tensor(input_details[0]['index'], input_arr_expanded)
interpreter.invoke()

**Comment by amahendrakar** [comment]
@le8888e,
In order to expedite the trouble-shooting process, could you please provide the complete code to build the model, the SavedModel file itself and `model_int8.tflite` file as well. Thanks!

**Comment by abattery** [comment]
I managed to exclude TFLite fill op from quantizable op set. Could you try the conversion with the tomorrow's TF nightly version?

**Comment by le8888e** [comment]
Hi @abattery ,

Thank you. But I tried both my model and ResNet50 with INT8 on x86 CPU, they both run much slower than FP32. Given the discuss in https://github.com/tensorflow/tensorflow/issues/40183, I think there is no speed up with INT8 on x86 CPUs.

**Comment by sushreebarsa** [comment]
@le8888e It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest  stable Version of TF 2.5 and let us know if the issue still persists? Thanks!
