### ISSUE TITLE
How add two pre defined keras models in keras tensorflow

### ISSUE THREAD

**Issue by aligoglos** [tensorflow/tensorflow#43597]
I've wanted to define network that has two input and use EfficientNetB1 to extract features and fine-tune on new layers so I've tried below code:

    def createNet(self,shape):
        FE1 = K.applications.EfficientNetB1(include_top=False, input_shape=shape)
        FE2 = K.applications.EfficientNetB1(include_top=False, input_shape=shape)
        inp1 = FE1.input
        out1 = FE1.layers[-1].output
        inp2 = FE2.input
        out2 = FE2.layers[-1].output

        merged_out = K.layers.concatenate((out1, out2))
        # .... other layers
        self.model = K.models.Model(inputs=[inp1, inp2], outputs=[merged_out])
        
        self.model.summary()

But I got this error :

    ValueError: The name "stem_conv_pad" is used 2 times in the model. All layer names should be unique.

So how can I define such a this network ?

**Comment by ravikyram** [comment]
@aligoglos 

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Please, help us with the reproducible code to localize the issue faster.Thanks!

**Comment by ymodak** [comment]
You may want to rename all the layers of either FE1 or FE2 in your example.
For instance;
```python
for layer in FE2.layers:
    layer._name = 'new ' + str(layer._name)
    print(layer.name)
```

**Comment by aligoglos** [comment]
Thanks it work.

**Comment by ChrisLMills** [comment]
@ymodak thanks for the solution.
One thing to add, there shouldn't be a space in the new name, so rather:
`layer._name = 'new_' + str(layer._name)`
