### ISSUE TITLE
Possible GPU memory leak at tf.vectorized_map

### ISSUE THREAD

**Issue by edwardyehuang** [tensorflow/tensorflow#43593]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):ubuntu 18.04
- TensorFlow installed from (source or binary):pip
- TensorFlow version (use command below): 2.4.0-dev20200821
- Python version:3.7
- GPU model and memory:v100 / titan rtx

When using tf.vectorized_map, GPU memory is continually increased, and finaly caused OOM after many training iterations. tf.map_fn works fine.

**Comment by vishsangale** [comment]
Looking at the code and documentation, looks like `vectorized_map` stacking the output for each iteration, which is causing increase in GPU memory after each iteration. The [documentation](https://www.tensorflow.org/api_docs/python/tf/vectorized_map) also says that  the function is `optimized to run much faster, possibly with a much larger memory footprint` as compared to `map_fn`, also the function `vectorized_map` is experimental.

**Comment by edwardyehuang** [comment]
> 
> 
> Looking at the code and documentation, looks like `vectorized_map` stacking the output for each iteration, which is causing increase in GPU memory after each iteration. The [documentation](https://www.tensorflow.org/api_docs/python/tf/vectorized_map) also says that the function is `optimized to run much faster, possibly with a much larger memory footprint` as compared to `map_fn`, also the function `vectorized_map` is experimental.

I think a much larger memory footprint is acceptable. However, increasing in GPU memory after each iteration should be a bug? What do you think?

**Comment by ravikyram** [comment]
@edwardyehuang 

I tried in colab with nightly version(2.4.0-dev20200927) and i am not seeing any OOM error.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/e670809edde31664fabb04f4e9be6092/untitled396.ipynb).Please, verify once.Thanks!

**Comment by edwardyehuang** [comment]
I found this issue is not caused by tf.vectorized_map. Close this issue

**Comment by edwardyehuang** [comment]
I don't know why, but some commits in recent days solve my GPU memory leak issue
