### ISSUE TITLE
The format of the table is wrong.

### ISSUE THREAD

**Issue by gowthamnatarajan** [tensorflow/tensorflow#43609]
## URL(s) with the issue:

https://www.tensorflow.org/agents/api_docs/python/tf_agents/agents/PPOAgent#

## Description of issue (what needs changing):
Table format is wrong. HTML code like table, tr, td etc is visible.

### Clear description
Table format is wrong. HTML code like table, tr, td etc is visible in the 2nd half of the page This makes it hard to read.

### Parameters defined

Are all parameters defined and formatted correctly?
No

**Comment by gowthamnatarajan** [comment]
Looks like someone fixed this 1 month ago.
https://github.com/tensorflow/agents/commit/bf10ec26f1552d7ebb7672cf7cc3fa85a05c933e
But, in the website, the bug is still visible.

**Comment by amahendrakar** [comment]
@gowthamnatarajan,
Could you please submit a new issue in the tensorflow/agents repo from [this link](https://github.com/tensorflow/agents/issues/new) and fill in the template, so that we can track the issue there. Thanks!
