### ISSUE TITLE
i can't  find tutorials. Examples. 

### ISSUE THREAD

**Issue by YahboomTechnology** [tensorflow/tensorflow#43602]

**Comment by Saduf2019** [comment]
@YahboomTechnology 
Please specify what information are you looking for.
Please refer to below tensorflow tutorial links and let us know if it helps:
[link](https://www.tensorflow.org/tutorials/quickstart/beginner), [link1](https://www.tutorialspoint.com/tensorflow/index.htm), [link2](https://www.datacamp.com/community/tutorials/tensorflow-tutorial), [link3](https://www.guru99.com/tensorflow-tutorial.html).

**Comment by florianmarcher** [comment]
I have the same example. I found this commit 
https://github.com/tensorflow/tensorflow/commit/42e122e6a0acaa7bee32ce88e2423ed99b3a0d84
where the examples were moved into a seperate repo 3 days ago. I havent found the new repo

for now, you can see the file contents in the commit diff

**Comment by Dolphinzzx** [comment]
i also can't find new repo.

**Comment by Saduf2019** [comment]
@florianmarcher  @Dolphinzzx @YahboomTechnology 
Can you please be specific which tutorials are you talking about
