### ISSUE TITLE
Some times  ,interpreter_->Invoke() doesn't return

### ISSUE THREAD

**Issue by lovehuanhuan** [tensorflow/tensorflow#43600]
**System information**
RK3399 
Linux localhost 4.4.126 #1070 SMP PREEMPT Fri Sep 18 16:41:27 HKT 2020 aarch64

In mediapipe project, this function interpreter_->Invoke()  was called but don't return,so the program got stucked.

**Comment by amahendrakar** [comment]
@lovehuanhuan,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!
