### ISSUE TITLE
Example of inferencing a Tensorflow lite model with parsing_serving_input_receiver_fn using C++ API

### ISSUE THREAD

**Issue by alirezazd** [tensorflow/tensorflow#43607]
I have followed the Tensorflow2 documentation to convert my trained  tf.estimator model to tflite model; in order to convert my model, first I had to save my model in saved_model format with a input_receiver_fn and then convert it with SELECT_OPS flag:

```
classifier = tf.estimator.LinearClassifier(n_classes=2, model_dir = classifier_dir, feature_columns=features)
classifier.train(input_fn = lambda: trian_fn(features = train_datas, labels = trian_labels))

serving_input_fn = tf.estimator.export.build_parsing_serving_input_receiver_fn(tf.feature_column.make_parse_example_spec(features))

classifier.export_saved_model(classifier_dir+"\saved_model", serving_input_fn)

converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir = saved_model_dir , signature_keys=['serving_default']) 
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
with open('model.tflite', 'wb') as f:
  f.write(tflite_model)
```
I wanted to run my tflite model on an ARM device without python support so I built the C++ interpreter shared libs with Bazel as it is explained in the documentation :
 [Cross-compile for armhf with Bazel](https://www.tensorflow.org/lite/guide/build_rpi#cross-compile_for_armhf_with_bazel)
[Select TensorFlow operators C++
](https://www.tensorflow.org/lite/guide/ops_select#c)

My model has 3 input features but when I try to use the following [guide](https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_c) for inferencing I get a segmentation fault.

I used the following code to extract my model details:
```
interpreter = tf.lite.Interpreter(model_path="./model.tflite")
interpreter.allocate_tensors()
print("all ok")
# Print input shape and type
inputs = interpreter.get_input_details()
print('{} input(s):'.format(len(inputs)))
for i in range(0, len(inputs)):
    print('{} {}'.format(inputs[i]['shape'], inputs[i]['dtype']))

# Print output shape and type
outputs = interpreter.get_output_details()
print('\n{} output(s):'.format(len(outputs)))
for i in range(0, len(outputs)):
    print('{} {}'.format(outputs[i]['shape'], outputs[i]['dtype']))
```
I got the following output:

```
all ok
1 input(s):
[1] <class 'numpy.bytes_'>

2 output(s):
[1 2] <class 'numpy.bytes_'>
[1 2] <class 'numpy.float32'>
```
first few lines of the output of   `tflite::PrintInterpreterState(interpreter.get())`  are:
```
INFO: Created TensorFlow Lite delegate for select TF ops.
INFO: TfLiteFlexDelegate delegate: 1 nodes delegated out of 25 nodes with 1 partitions.

Interpreter has 54 tensors and 26 nodes
Inputs: 0
Outputs: 38 34

Tensor   0 input_example_tensor kTfLiteString  kTfLiteDynamic          0 bytes ( 0.0 MB)  1
```

The output illustrates that the input shape is not the same as the original model, also the input type is <class 'numpy.bytes_'> but the Tensorflow 2 model inputs are [numpy.float32, numpy.float32, numpy.float32].
my input dictionary for prediction in TF2 model is something like : {'feature0' : data0, 'feature1' : data1, 'feature2' : data2}
[here is the Google Colab link to the project](https://colab.research.google.com/drive/1fkj8zM2FM-xd6cajWkStcasmzliZWF9s?usp=sharing)

I tried to fill the input buffer with a vector of zeros but it was without success. Here is my C++ code to load a tflite model and feed it inputs for prediction. can someone please point me to the right direction since I could not find any examples or related documentation for feeding inputs to converted tf.estimator with a serving_input_fn.

```
#include <cstdio>
#include "tensorflow/lite/interpreter.h"
#include "tensorflow/lite/kernels/register.h"
#include "tensorflow/lite/model.h"
#include "tensorflow/lite/optional_debug_tools.h"

int main()
{
  // Load model
      std::unique_ptr<tflite::FlatBufferModel> model = tflite::FlatBufferModel::BuildFromFile("model.tflite");
      
  // Build the interpreter with the InterpreterBuilder.
  tflite::ops::builtin::BuiltinOpResolver resolver;
  tflite::InterpreterBuilder builder(*model, resolver);
  std::unique_ptr<tflite::Interpreter> interpreter;
  builder(&interpreter);
  tflite::PrintInterpreterState(interpreter.get());
  
  // Allocate tensor buffers.
  interpreter->AllocateTensors();
  printf("=== Pre-invoke Interpreter State ===\n");
  tflite::PrintInterpreterState(interpreter.get());

  // Fill input buffers
  std::vector<float> tensor(3, 0);	//Vector of zeros
  int input = interpreter->inputs()[0];
  float* input_data_ptr = interpreter->typed_input_tensor<float>(input);
  for(int i = 0; i < 3; ++i)
  {
  	*(input_data_ptr) = (float)tensor[i];
  	input_data_ptr++;
  }
  // Run inference
  interpreter->Invoke();
  printf("\n\n=== Post-invoke Interpreter State ===\n");
  
  return 0;
}
```

**Comment by abattery** [comment]
The original model uses an example proto as input internally, which is used by the TF estimator API. So, the converted TFLite model needs one input, example proto as a byte array. Could you create an example proto, in a form of byte array, with three features in your inference code?

**Comment by alirezazd** [comment]
@abattery  Thank you for the comment, I have no previous knowledge about example photos if is there any documentation references, or can you provide a simple example for just one feature?

**Comment by abattery** [comment]
Here is the possible code in Python to generate an example protobuf byte.


```
    features = collections.OrderedDict()
    features["feature_one"] = ...
    features["feature_two"] = ...
    features["feature_third"] = ...

    tf_example = tf.train.Example(features=tf.train.Features(feature=features))
    input_tensor = tf_example.SerializeToString()
```

**Comment by alirezazd** [comment]
@abattery Thanks, are the methods for generating  Example protobuf bytes available in C++ API, or should I implement my own?

**Comment by abattery** [comment]
The example proto is a part of Tensorflow core project. If you can link to Tensorflow core project, you may use the following methods for example protobuf object creation. Or it is possible to create an example proto based on protobuf library.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/example/feature_util.h

**Comment by alirezazd** [comment]
@abattery I will try to feed an example proto to my model using C++ and I will post the results. thank you.

**Comment by alirezazd** [comment]
@abattery I read about proto buffers and example protos in Tensorflow, I decided to first verify my model in python and then write the C++ interpreter, I created my own example protobuf:
```
def _float_feature(value):
  """Returns a float_list from a float / double."""
  return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))
def serialize_example(feature0, feature1, feature2):
  feature={'feature0': _float_feature(feature0),
            'feature1': _float_feature(feature1),
            'feature2' : _float_feature(feature2)}
  example_proto = tf.train.Example(features=tf.train.Features(feature=feature))
  return example_proto.SerializeToString()
serialized_example = serialize_example(0,0,0)
serialized_example
```
the output is : b'\nB\n\x14\n\x08feature0\x12\x08\x12\x06\n\x04\x00\x00\x00\x00\n\x14\n\x08feature1\x12\x08\x12\x06\n\x04\x00\x00\x00\x00\n\x14\n\x08feature2\x12\x08\x12\x06\n\x04\x00\x00\x00\x00'
I tried to feed the example to model as you mentioned:

```
interpreter = tf.lite.Interpreter(model_path="model.tflite")
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
interpreter.set_tensor(input_details[0]['index'], serialized_example)

```
but I get the following error:
`ValueError: Cannot set tensor: Dimension mismatch. Got 0 but expected 1 for input 0.
`

**Comment by abattery** [comment]
Could you try `interpreter.resize_tensor_input` before assigning the value?

**Comment by alirezazd** [comment]
@abattery Sorry for the late feedback, Tested it and got a runtime reset; is there a way to change the input function so it accepts three feature inputs as an array with shape [1 1 1]? it saves a lot of trouble.

**Comment by sachinprasadhs** [comment]
Hi, Estimator will be deprecated from Tensorflow 2.12 since it uses Tensorflow V1 behavior.
Could you please migrate from Estimator to Keras API which will enable you to perform the aforementioned tasks, such as [model building](https://www.tensorflow.org/guide/keras/custom_layers_and_models), gradient application, [training](https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit), evaluation, and prediction.
Refer Migration guide here https://www.tensorflow.org/guide/migrate/migrating_estimator for more details. Thanks!
