### ISSUE TITLE
Dynamic Library loading failed 'cudart64_101.dll' & AttributeError: module 'tensorflow' has no attribute 'Session'

### ISSUE THREAD

**Issue by alinasahoo** [tensorflow/tensorflow#43601]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10, 64 config
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip3 install upgrade --tensorflow
- TensorFlow version: 2.3.1
- Python version: 3.8.3
- Installed using virtualenv? pip? conda?: Created a virtual environment. Used this command: conda create -n tfp3.8 python= 3.8
- Bazel version (if compiling from source): No, not compliling from source.
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 10.0
- GPU model and memory: NVIDIA GeForce MX250 

**Problem Description:**

Firstly it shows this after the installation of tensorflow:

2020-09-27 13:11:39.558775:
W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-09-27 13:11:39.563129:
I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

And secondly, 

AttributeError                            Traceback (most recent call last)
<ipython-input-3-f75057d1d95f> in <module>
----> 1 sess = tf.Session()

AttributeError: module 'tensorflow' has no attribute 'Session'

**Steps Performed:**

For the first problem, I executed the following steps:
Step 1: conda activate tfp3.8
This logs into the environment for the created tensorflow.

Step 2: python
Logs into the python terminal

>>import tensorflow as tf
This resulted in the above error enlisted as the first.

For the second problem, I executed the following steps in the jupyter notebook:
Step 1:  import tensorflow as tf //Success
Step 2:  hello = tf.constant("Hello, Tensorflow!") //Success
Step 3: sess = tf.Session() //Oops! Attribute Error

**Comment by ravikyram** [comment]
@alinasahoo 

Can you please refer this [SO link](https://stackoverflow.com/questions/55142951/tensorflow-2-0-attributeerror-module-tensorflow-has-no-attribute-session/59179238#59179238) and see if it helps you. Thanks!

**Comment by alinasahoo** [comment]
This works fine for me:

>> import tensorflow as tf  // Success
>> msg = tf.constant('Hello, TensorFlow!') // Success along with some opened dynamic libraries CUDA and some failed cuDNN libraries
>> tf.print(msg) // Hello, Tensorflow!

Absolutely fine. However another approach can work too.
>> import tensorflow as tf // Success
>> tf.compat.v1.disable_eager_execution() // Success
>> hello = tf.constant('Hello, TensorFlow!') // Success
>> sess = tf.compat.v1.Session() // Success along with some opened dynamic libraries CUDA and some failed cuDNN libraries
>> print(sess.run(hello)) // b'Hello, TensorFlow!'

This too works absolutely fine. Thank you @ravikyram .

**Comment by ravikyram** [comment]
@alinasahoo 

Please, close this thread if your issue was resolved. Thanks!

**Comment by Thanossrs** [comment]
I have the same problem.
I try to run my codes to GPU and I have this error.

could anyone help me?
thank you

**Comment by alinasahoo** [comment]
@Thanossrs Please make sure that you have a higher version of CUDA, i.e more than 10.00 as TF 2.3 and Python 3.8 are more of the latest versions I downloaded and asked the same thing. Also, make sure that the tensorflow version that you download is compatible with your python environment. You can also download tf below 2 so that your code runs successfully. However, some files have been deprecated so I switched to higher versions.
