### ISSUE TITLE
from tensorflow.contrib.seq2seq import Helper

### ISSUE THREAD

**Issue by luis-vera** [tensorflow/tensorflow#43612]
HI.

I am developing a system but in Tensorflow 2 don't exist this:

from tensorflow.contrib.seq2seq import Helper

How can migrate to a similar solution in Tensorflow 2? Thank's a lot

**Comment by bhack** [comment]
Check https://github.com/tensorflow/addons/blob/master/tensorflow_addons/seq2seq/README.md

**Comment by ymodak** [comment]
Also make sure you are familiar with [python-op-compatibility-matrix](https://github.com/tensorflow/addons#). Thanks!
