### ISSUE TITLE
Error converting Tensorflow saved model to TFLite

### ISSUE THREAD

**Issue by kmassa23** [tensorflow/tensorflow#43619]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Catalina 10.15.6
- TensorFlow installed from (source or binary): pip install tensorflow (command line)
- TensorFlow version (or github SHA if from source): 2.3.0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
# Copy and paste here the exact command
converter = tf.lite.TFLiteConverter.from_saved_model("tf_proximity_saved_model")  # "tf_proximity_saved_model" is the name of my model

**The output from the converter invocation**

```
# Copy and paste the output here.
error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
tf.Cast {Truncate = false, device = ""}
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 199, in toco_convert_protos
enable_mlir_converter)
File "/usr/local/lib/python3.6/site-packages/tensorflow/lite/python/wrap_toco.py", line 38, in wrapped_toco_convert
enable_mlir_converter)
Exception: <unknown>:0: error: loc(fused["sequential/Cast@__inference__wrapped_model_40145", "StatefulPartitionedCall/sequential/Cast"]): 'tf.Cast' op is neither a custom op nor a flex op
<unknown>:0: note: loc(fused["sequential/Cast@__inference__wrapped_model_40145", "StatefulPartitionedCall/sequential/Cast"]): see current operation: %0 = "tf.Cast"(%arg0) {Truncate = false, device = ""} : (tensor<?x1xf64>) -> tensor<?x1xf32>
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
tf.Cast {Truncate = false, device = ""}
<unknown>:0: note: see current operation: "func"() ( {
^bb0(%arg0: tensor<?x1xf64>): // no predecessors
%cst = "std.constant"() {value = dense<[0.136683047, 0.000000e+00, -1.8840152, 0.000000e+00, 0.000000e+00, 0.000000e+00, 3.257740e-01, 0.000000e+00, 0.000000e+00, 0.000000e+00]> : tensor<10xf32>} : () -> tensor<10xf32>
%cst_0 = "std.constant"() {value = dense<[0.000000e+00, 1.69775057, 0.000000e+00, 0.000000e+00, -0.638654768, -1.93405676, -1.95157754, -0.0406359173, 1.72332501, -1.7537955]> : tensor<10xf32>} : () -> tensor<10xf32>
%cst_1 = "std.constant"() {value = dense<1.7260325> : tensor<1xf32>} : () -> tensor<1xf32>
%cst_2 = "std.constant"() {value = dense<[[0.00675311219], [0.341173232], [-0.481861204], [0.701621353], [0.0275682211], [0.0613476038], [-0.44652465], [0.166085422], [0.189539731], [0.020105958]]> : tensor<10x1xf32>} : () -> tensor<10x1xf32>
%cst_3 = "std.constant"() {value = dense<[[0.29277724, 0.295953631, 0.205961823, 0.338899374, 0.49851656, -0.437764347, -0.505791903, 0.403120697, 0.0529763699, -0.417837113], [-0.445695817, -0.361287892, 0.101978905, -0.418562263, 0.0107798576, 0.0221389532, 0.220730424, 4.990560e-02, -0.208217949, -0.172240525], [0.0161076784, -0.396935463, -0.530536652, -0.379159153, -0.44315511, 0.213063776, -0.0682218968, -0.221574157, -0.0774391591, -0.472134769], [0.288429618, -0.0110605955, -0.490244329, 0.494588017, 0.330006599, 0.54180479, -0.499053359, 0.0791082978, -0.524112284, -0.0557569563], [-0.546745062, -4.394100e-01, 0.459474474, -0.248545527, 0.0341958404, -0.320446074, -0.368350893, 0.00832664966, -0.0379120708, -0.451237142], [-0.266778737, 0.49375844, -1.604300e-01, -0.315872908, 0.163485587, 0.116762996, 0.266193658, -0.30224967, 0.105117381, -0.534985602], [-0.263971537, -0.0919606983, -0.281746626, -0.310481608, -0.222500026, -0.0813589692, 0.382073581, 0.154834032, -0.285841495, -0.547358394], [0.459437639, 0.0883420109, -0.0378421694, 0.256017208, 0.206906617, -0.461118042, -0.0286277644, -0.377283901, 0.478136897, -0.519345164], [0.513453424, -0.12144509, -0.134186059, -0.39923197, -0.395939708, -0.34776777, 0.461619705, -0.185738802, -0.495007396, -0.359370708], [0.33326897, -0.100557774, 0.382778198, 0.0325809717, 0.231879592, -0.251019359, 0.165992916, -0.542559922, 0.0710098147, -0.00225681067]]> : tensor<10x10xf32>} : () -> tensor<10x10xf32>
%cst_4 = "std.constant"() {value = dense<[[-6.715610e-01, 0.230374008, -0.0477389693, 0.28339678, -0.580778599, -1.10261536, -0.777723848, -0.451123297, 0.602046907, -0.688027441]]> : tensor<1x10xf32>} : () -> tensor<1x10xf32>
%0 = "tf.Cast"(%arg0) {Truncate = false, device = ""} : (tensor<?x1xf64>) -> tensor<?x1xf32>
%1 = "tfl.fully_connected"(%0, %cst_2, %cst) {fused_activation_function = "RELU", keep_num_dims = false, weights_format = "DEFAULT"} : (tensor<?x1xf32>, tensor<10x1xf32>, tensor<10xf32>) -> tensor<?x10xf32>
%2 = "tfl.fully_connected"(%1, %cst_3, %cst_0) {fused_activation_function = "RELU", keep_num_dims = false, weights_format = "DEFAULT"} : (tensor<?x10xf32>, tensor<10x10xf32>, tensor<10xf32>) -> tensor<?x10xf32>
%3 = "tfl.fully_connected"(%2, %cst_4, %cst_1) {fused_activation_function = "NONE", keep_num_dims = false, weights_format = "DEFAULT"} : (tensor<?x10xf32>, tensor<1x10xf32>, tensor<1xf32>) -> tensor<?x1xf32>
"std.return"(%3) : (tensor<?x1xf32>) -> ()
}) {sym_name = "main", tf.entry_function = {control_outputs = "", inputs = "dense_input", outputs = "Identity"}, type = (tensor<?x1xf64>) -> tensor<?x1xf32>} : () -> ()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "prox_data_learn.py", line 156, in <module>
tflite_model = converter.convert()
File "/usr/local/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 1076, in convert
return super(TFLiteConverterV2, self).convert()
File "/usr/local/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 900, in convert
self).convert(graph_def, input_tensors, output_tensors)
File "/usr/local/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 633, in convert
**converter_kwargs)
File "/usr/local/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 574, in toco_convert_impl
enable_mlir_converter=enable_mlir_converter)
File "/usr/local/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 202, in toco_convert_protos
raise ConverterError(str(e))
tensorflow.lite.python.convert.ConverterError: <unknown>:0: error: loc(fused["sequential/Cast@__inference__wrapped_model_40145", "StatefulPartitionedCall/sequential/Cast"]): 'tf.Cast' op is neither a custom op nor a flex op
<unknown>:0: note: loc(fused["sequential/Cast@__inference__wrapped_model_40145", "StatefulPartitionedCall/sequential/Cast"]): see current operation: %0 = "tf.Cast"(%arg0) {Truncate = false, device = ""} : (tensor<?x1xf64>) -> tensor<?x1xf32>
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
tf.Cast {Truncate = false, device = ""}
<unknown>:0: note: see current operation: "func"() ( {
^bb0(%arg0: tensor<?x1xf64>): // no predecessors
%cst = "std.constant"() {value = dense<[0.136683047, 0.000000e+00, -1.8840152, 0.000000e+00, 0.000000e+00, 0.000000e+00, 3.257740e-01, 0.000000e+00, 0.000000e+00, 0.000000e+00]> : tensor<10xf32>} : () -> tensor<10xf32>
%cst_0 = "std.constant"() {value = dense<[0.000000e+00, 1.69775057, 0.000000e+00, 0.000000e+00, -0.638654768, -1.93405676, -1.95157754, -0.0406359173, 1.72332501, -1.7537955]> : tensor<10xf32>} : () -> tensor<10xf32>
%cst_1 = "std.constant"() {value = dense<1.7260325> : tensor<1xf32>} : () -> tensor<1xf32>
%cst_2 = "std.constant"() {value = dense<[[0.00675311219], [0.341173232], [-0.481861204], [0.701621353], [0.0275682211], [0.0613476038], [-0.44652465], [0.166085422], [0.189539731], [0.020105958]]> : tensor<10x1xf32>} : () -> tensor<10x1xf32>
%cst_3 = "std.constant"() {value = dense<[[0.29277724, 0.295953631, 0.205961823, 0.338899374, 0.49851656, -0.437764347, -0.505791903, 0.403120697, 0.0529763699, -0.417837113], [-0.445695817, -0.361287892, 0.101978905, -0.418562263, 0.0107798576, 0.0221389532, 0.220730424, 4.990560e-02, -0.208217949, -0.172240525], [0.0161076784, -0.396935463, -0.530536652, -0.379159153, -0.44315511, 0.213063776, -0.0682218968, -0.221574157, -0.0774391591, -0.472134769], [0.288429618, -0.0110605955, -0.490244329, 0.494588017, 0.330006599, 0.54180479, -0.499053359, 0.0791082978, -0.524112284, -0.0557569563], [-0.546745062, -4.394100e-01, 0.459474474, -0.248545527, 0.0341958404, -0.320446074, -0.368350893, 0.00832664966, -0.0379120708, -0.451237142], [-0.266778737, 0.49375844, -1.604300e-01, -0.315872908, 0.163485587, 0.116762996, 0.266193658, -0.30224967, 0.105117381, -0.534985602], [-0.263971537, -0.0919606983, -0.281746626, -0.310481608, -0.222500026, -0.0813589692, 0.382073581, 0.154834032, -0.285841495, -0.547358394], [0.459437639, 0.0883420109, -0.0378421694, 0.256017208, 0.206906617, -0.461118042, -0.0286277644, -0.377283901, 0.478136897, -0.519345164], [0.513453424, -0.12144509, -0.134186059, -0.39923197, -0.395939708, -0.34776777, 0.461619705, -0.185738802, -0.495007396, -0.359370708], [0.33326897, -0.100557774, 0.382778198, 0.0325809717, 0.231879592, -0.251019359, 0.165992916, -0.542559922, 0.0710098147, -0.00225681067]]> : tensor<10x10xf32>} : () -> tensor<10x10xf32>
%cst_4 = "std.constant"() {value = dense<[[-6.715610e-01, 0.230374008, -0.0477389693, 0.28339678, -0.580778599, -1.10261536, -0.777723848, -0.451123297, 0.602046907, -0.688027441]]> : tensor<1x10xf32>} : () -> tensor<1x10xf32>
%0 = "tf.Cast"(%arg0) {Truncate = false, device = ""} : (tensor<?x1xf64>) -> tensor<?x1xf32>
%1 = "tfl.fully_connected"(%0, %cst_2, %cst) {fused_activation_function = "RELU", keep_num_dims = false, weights_format = "DEFAULT"} : (tensor<?x1xf32>, tensor<10x1xf32>, tensor<10xf32>) -> tensor<?x10xf32>
%2 = "tfl.fully_connected"(%1, %cst_3, %cst_0) {fused_activation_function = "RELU", keep_num_dims = false, weights_format = "DEFAULT"} : (tensor<?x10xf32>, tensor<10x10xf32>, tensor<10xf32>) -> tensor<?x10xf32>
%3 = "tfl.fully_connected"(%2, %cst_4, %cst_1) {fused_activation_function = "NONE", keep_num_dims = false, weights_format = "DEFAULT"} : (tensor<?x10xf32>, tensor<1x10xf32>, tensor<1xf32>) -> tensor<?x1xf32>
"std.return"(%3) : (tensor<?x1xf32>) -> ()
}) {sym_name = "main", tf.entry_function = {control_outputs = "", inputs = "dense_input", outputs = "Identity"}, type = (tensor<?x1xf64>) -> tensor<?x1xf32>} : () -> ()

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
https://drive.google.com/file/d/1U59Z_Z4ZH4tGn2dTpvB5tm4t0NujUfTz/view?usp=sharing 

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)


**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@kmassa23 

Can you please try adding the following code and and let us know if the issue still persists. 
```
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter.allow_custom_ops=True
converter.experimental_new_converter =True
tflite_model = converter.convert()
```
Please, try with nightly version as well. Thanks!
