### ISSUE TITLE
Compiling Person Detection Model for zephyr_riscv

### ISSUE THREAD

**Issue by Darshcg** [tensorflow/tensorflow#43616]
Hi,
I was able to compile both the example applications(Hello World and Magic wand) for zephyr_riscv. 

How to compile the other TFLite Models(Person detection and Image Recognition) for zephyr_riscv? What are the changes that need to be made in order to compile it for zephyr_riscv?

Note: **make -f tensorflow/lite/micro/tools/make/Makefile TARGET=zephyr_vexriscv person_detection_bin** I used this command for Person Detection and I am getting the output as: **make: Nothing to be done for 'person_detection_bin'**.

Best Regards,
Darshan

**Comment by pjpratik** [comment]
Hi @Darshcg 

The TFLite Micro provides a person detection [example](https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/examples/person_detection#person-detection-example) which can be compiled by

```
make -f tensorflow/lite/micro/tools/make/Makefile third_party_downloads
make -f tensorflow/lite/micro/tools/make/Makefile test_person_detection_test
```

You should see a series of files get compiled, followed by some logging output from a test, which should conclude with ~~~ALL TESTS PASSED~~~

Thanks.
