### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by akmal1994** [tensorflow/tensorflow#43614]
System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): window 10
![Capture1](https://user-images.githubusercontent.com/63404689/94395515-8642da00-017d-11eb-984a-0a23d1c0b19c.JPG)
![Capture2](https://user-images.githubusercontent.com/63404689/94395523-880c9d80-017d-11eb-82e2-9dfbad52761c.JPG)

- TensorFlow installed from (source or binary): jupyter notebook
- TensorFlow version: 2.3.1
- Python version: 3.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

Unable to import keras and tensorflow in jupyter notebook

Installing tensorflow through pip install tensorflow but unable to install.

**Comment by ravikyram** [comment]
@akmal1994 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here.](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.

Also, you can change the code to `from tensorflow import keras`

Thanks!

**Comment by akmal1994** [comment]
Thanks for the support. The issue is resolved.

**Comment by ravikyram** [comment]
@akmal1994 

Please, close this thread if your issue was resolved. Thanks!
