### ISSUE TITLE
Feature request: STM32CubeIDE integration

### ISSUE THREAD

**Issue by fkromer** [tensorflow/tensorflow#43625]
The [STM32CubeIDE](https://www.st.com/en/development-tools/stm32cubeide.html) is probably the most widely used development environment for STM32 micro-controllers. It is free to use and available for Linux, macOS and Windows. It seems like there is no support for it in *TensorFlow Lite for Microcontrollers* yet. Would be great to have support for it.

**Comment by mohantym** [comment]
Hi @fkromer !
I found a documentation on STM32Cube on using TFlite model[ here](https://mirzafahad.github.io/2020-06-26-tflite-stm32-part3/).

Standard procedure is almost same as Arduiono's one. 
1. Train and Test your model then convert to Tflite .
2.  Use XXD converter to convert the lite model to a character buffer.
3.  import it in STM32CubeIDE.

Please test the examples from[ Tflite-example-arduino](https://github.com/tensorflow/tflite-micro-arduino-examples) as a starting point and let us know.

Thank you!
