### ISSUE TITLE
tf.feature_column.embedding_column: wrong dtype in lookup variable

### ISSUE THREAD

**Issue by dennisjay** [tensorflow/tensorflow#43628]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**:

Yes

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 18.10

-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:

No

-   **TensorFlow installed from (source or binary)**:

pip install -U --force-reinstall tf-nightly

-   **TensorFlow version (use command below)**:

'2.4.0-dev20200712'

-   **Python version**:

python --version
Python 3.7.7

-   **Bazel version (if compiling from source)**:

NO

-   **GCC/Compiler version (if compiling from source)**:

NO

-   **CUDA/cuDNN version**:

Reproducable on CPU

-   **GPU model and memory**:

Reproducable on CPU

-   **Exact command to reproduce**:

https://gist.github.com/dennisjay/9482041ba5e037b0cc8fd12dcd2292c8

### Describe the problem
The tf.feature_column.embedding_column of my tensorflow Version is internally working with int32 instead of int64 and thus there are errors when exporting the model to saved model and compiling it with i.e. triton server.

![image](https://user-images.githubusercontent.com/1181660/94471941-481fd780-01ca-11eb-9693-8b7b8537bf0d.png)

The strided slice operation outputs a int64 but the following operation is accepting int32 only. Reproducable is the error with the use of the jupyter notebook above.

### Source code / logs

InferenceServerException: [_Derived_]{{function_node __inference_signature_wrapper_3345}} {{function_node __inference_signature_wrapper_3345}} input segment_ids[0] expected type int32 != int64, the type of sequential_1/dense_features_1/test_col_embedding/test_col_embedding_weights/embedding_lookup_sparse/strided_slice:output:0[0]
	In {{node sequential_1/dense_features_1/test_col_embedding/test_col_embedding_weights/embedding_lookup_sparse}}
	 [[StatefulPartitionedCall]]
	 [[StatefulPartitionedCall_1]]

**Comment by ravikyram** [comment]
@dennisjay 

Looks like you are using a custom module named "tritonhttpclient" in your code. In order to reproduce the issue, could you please provide the complete reproducible code including all the dependencies? Thanks!

**Comment by dennisjay** [comment]
@ravikyram the full code for installation and running is provided in the gist. The third party module for nvidia triton server can be downloaded here: https://github.com/triton-inference-server/server/releases/tag/v2.2.0 .

Thanks for looking at this.

**Comment by ravikyram** [comment]
@dennisjay 

I tried in colab and seeing the error message as `ConnectionRefusedError: [Errno 111] Connection refused`.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/c8b0d56d7b13f632b5aa67f8c0e56186/untitled402.ipynb). Thanks!

**Comment by dennisjay** [comment]
The notebook requires the nvidia triton docker container to be running. With this command from cell 17:

docker run --rm -p8030:8000 -p8031:8001 -p8032:8002 -v`pwd`/test_repo:/models nvcr.io/nvidia/tritonserver:20.08-py3 tritonserver --model-repository=/models

Please be shure to execute it from within the notebook path.
Sorry for the little bit complicated reproduction.

**Comment by dennisjay** [comment]
@ravikyram were you able to reproduce the error?

**Comment by tanzhenyu** [comment]
I see you're already using TF 2.4. Please try to use [Keras Preprocessing Layer](https://github.com/tensorflow/community/blob/master/rfcs/20191212-keras-categorical-inputs.md) which gives you much more flexible control for dtypes.

**Comment by dennisjay** [comment]
We fixed the error with the Keras preprocessing layer. Ty for your help.

**Comment by zhaohb** [comment]
@dennisjay  now I encounter the same problem, can you tell me how to solve it specifically？

thank you very much
