### ISSUE TITLE
CUDA 8.0 Failed to configure

### ISSUE THREAD

**Issue by DennisBang** [tensorflow/tensorflow#4362]
Dear everyone, I recently met this problem when I try to configure this problem, I am using CUDA8.0, Bazel 0.3 and Ubuntu 14.04.
ERROR: /home/haixi/tensorflow-master/tensorflow/tensorflow.bzl:568:26: Traceback (most recent call last):
	File "/home/haixi/tensorflow-master/tensorflow/tensorflow.bzl", line 562
		rule(attrs = {"srcs": attr.label_list..."), <3 more arguments>)}, <2 more arguments>)
	File "/home/haixi/tensorflow-master/tensorflow/tensorflow.bzl", line 568, in rule
		attr.label_list(cfg = "data", allow_files = True)
expected ConfigurationTransition or NoneType for 'cfg' while calling label_list but got string instead: data.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file 'tensorflow/tensorflow.bzl' has errors.

Hope that you can help me !

**Comment by DennisBang** [comment]
I tried to update the bazel and the mistake still happened....

**Comment by israelg99** [comment]
Can you post how you configured tensorflow?

**Comment by jart** [comment]
This error was caused by https://github.com/tensorflow/tensorflow/commit/7bcdcbbf60fc08346fd8016270a0563f4b51362b which broke old versions of Bazel. The simple fix is to just upgrade to the latest Bazel release.

**Comment by achiber** [comment]
I also encountered this problem, could you tell me how to solve it ?

**Comment by jart** [comment]
Try upgrading to Bazel 0.3.1.
