### ISSUE TITLE
Tensorflow session.run command 20% slower in tf2.3 compared to tf1.15 

### ISSUE THREAD

**Issue by rickstaa** [tensorflow/tensorflow#43620]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow):** Yea but an extremely simple one.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04):** Ubuntu 18.04
- **TensorFlow installed from (source or binary):**  Binary
- **TensorFlow version (use command below):** tf1.15.0 and tf2.3.0
- **Python version:** python v3.6.12 and python 3.8
- **CUDA/cuDNN version:** CUDA  v11.0/ cuDNN V9.1.85
- **GPU model and memory:** GPU: NVIDIA Quadro P1000 / Intel UHD Graphics 630 - Memory: 2x Samsung M471A4G43MB1-CTD

**tf_env_collect tool output:**

[tf_env.txt](https://github.com/tensorflow/tensorflow/files/5292801/tf_env.txt)

### Describe the current behaviour

I'm currently converting my tf1.15 scripts to tf2.3 eager execution scripts. I did this according to the [original migration documentation](https://www.tensorflow.org/guide/migrate). After running the automatic conversion script, however, I noticed that the converted `tf2.3` version is considerably slower than the `tf1.15` version. I used to profiler to find the cause of this increased execution time and found out that although the script is exactly the same the `sess.run` method takes longer to execute in `tf2.3`. As can be seen from the results below when `tf2.3` is used the script takes 20% longer to execute. For this simple script, the difference is not much but for my original script which runs for about 1 hour, this difference really starts to add up.

#### Tf1.15 result

**Script execution time:** 125.98906636238098

**Cprofiler file:**

[tf_115_cprof.zip](https://github.com/tensorflow/tensorflow/files/5293014/tf_115.zip)

**Spyder profiler file:**

[tf115.zip](https://github.com/tensorflow/tensorflow/files/5293107/tf115.zip)

#### tf2.3 result

**Script execution time:** 157.48224687576294

**Cprofiler file:**

[tf_23_cprof.zip](https://github.com/tensorflow/tensorflow/files/5293016/tf_23.zip)

**Spyder profiler file**

[tf23.zip](https://github.com/tensorflow/tensorflow/files/5293104/tf23.zip)

#### Spyder profiler difference screenshot

As can be seen from the screenshot below. It looks like the biggest difference can be found in the [flatten_dict_items](https://github.com/tensorflow/tensorflow/blob/02159bbe1f87638bb6cde6a6f4aaa2fc0362e53b/tensorflow/python/util/nest.py#L414) and [FetchHandler.__init__](https://github.com/tensorflow/tensorflow/blob/02159bbe1f87638bb6cde6a6f4aaa2fc0362e53b/tensorflow/python/client/session.py#L474) methods (Left is `tf2.3` and right `tf1.15`).

![image](https://user-images.githubusercontent.com/17570430/94447852-8e653e80-01aa-11eb-86f9-bc4d79d1aadf.png)

When we dive deeper we can see these methods take longer since the [__hash__](https://github.com/tensorflow/tensorflow/blob/02159bbe1f87638bb6cde6a6f4aaa2fc0362e53b/tensorflow/python/framework/ops.py#L826) method takes longer. In the [__hash__](https://github.com/tensorflow/tensorflow/blob/02159bbe1f87638bb6cde6a6f4aaa2fc0362e53b/tensorflow/python/framework/ops.py#L826) method of `tf2.3` python spends a long time executing the [executing_eagerly_outside_functions](https://github.com/tensorflow/tensorflow/blob/02159bbe1f87638bb6cde6a6f4aaa2fc0362e53b/tensorflow/python/framework/ops.py#L5741) method.

![image](https://user-images.githubusercontent.com/17570430/94450330-6e834a00-01ad-11eb-9b54-3c53b7f69db4.png)

These methods take longer since they are executed using the `executing_eagerly_outside_functions`.

### Describe the expected behaviour

I expected the execution time to be equal in both `tf1.15` and `tf2.3`.

### Standalone code to reproduce the issue

The performance difference can be seen when running the following script in both tf1.15 and tf2.3:

```python
"""Script used to compare the execution time difference when running similar code in
tensorflow 1.15 and tf2.3.
"""

import time
import os

from packaging import version
import tensorflow as tf

# Script settings
USE_GPU = False
N_STEPS = 1e5

# Disable GPU if requested
if not USE_GPU:  # NOTE: This works in both TF115 and tf2
    # tf.config.set_visible_devices([], "GPU")
    if version.parse(tf.__version__) > version.parse("1.15.4"):
        tf.config.set_visible_devices([], "GPU")
    else:
        os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
    print("Tensorflow is using CPU")
else:
    print("Tensorflow is using GPU")

# Disable eager execution
tf.compat.v1.disable_eager_execution()

# Create session
sess = tf.compat.v1.Session()

# Setup placeholders
t = 0  # Time
x = tf.compat.v1.placeholder(tf.float32, [None, 1], "x")
y = tf.math.sin(x, name=None)

# Run session in loop
print("===TF115 speed test script===")
print(f"Running a tf session {int(N_STEPS)} times to test the execution speed.")
print("Starting sess run loop.")
t1 = time.time()
for i in range(0, int(N_STEPS)):

    # Run result in session
    y_val = sess.run(y, feed_dict={x: [[t]]})

    # Increment time
    t += 1

    # print current step
    if i % 10000 == 0:
        print(f"Performed {i} steps.")

# Print end result
print("sess run loop stopped.")
print("Running time: ", time.time() - t1)
```

I also created a simple [test repository](https://github.com/rickstaa/tf2_3_sess_run_performance_slowdown) that includes this script and a guide on how to run it.

## Other info and logs

**Is this fixed in tf_nightly:** No the script also takes 160 seconds in tf_nightly.

**Comment by rickstaa** [comment]
I'm sorry. I accidentally clicked the post button. Give me a moment to fill in the bug report.

**Comment by karmel** [comment]
The performance characteristics of "compat.v1" APIs, especially those related to sessions, in 2.x releases is liable to change. We would recommend that you upgrade to the new 2.x APIs, including using eager execution and tf.function: https://www.tensorflow.org/guide/migrate#1_replace_v1sessionrun_calls

**Comment by rickstaa** [comment]
@karmel Thanks for the clarification! I opened this issue as a performance bug report while I already translated my code to tf2 eager mode. I noticed that the new version with tf.function is faster than the original TF1 version.
