### ISSUE TITLE
divide_no_nan logic

### ISSUE THREAD

**Issue by Nika-St** [tensorflow/tensorflow#43622]
The [divide_no_nan()](https://www.tensorflow.org/api_docs/python/tf/math/divide_no_nan) function by definition "Computes a safe divide which returns 0 if the y is zero".

My question is, wouldn't it make more sense to return the maximum value of dtype of the passed tensors? When dividing by very small positive numbers we get very large positive numbers, after all.
It is, of course, possible to apply `clip_by_value()` to the denominator first, and then simply use `divide()`, but that's probably less efficient and straightforward?

**Comment by mihaimaruseac** [comment]
The answer you suggest to return is only valid if you divide a positive number to a positive number going towards 0 (or a negative number divided to a negative number that is close to 0).

However, there is also the case where the operands have different signs. In this case, you have to return the minimum value of the type of the result (akin to -infinity).

Finally, there is the case where both numbers are very small. Kind of 0/0. This is the only operation which would produce a nan, actually

**Comment by Nika-St** [comment]
Fair! So maybe it makes sense to cover these cases - maybe not within this function actually (otherwise, its name would be misleading), but as a separate one - say, `safe_divide()`?

**Comment by mihaimaruseac** [comment]
We also don't want to blow up the API surface. It's better for the callers to just use `tf.where` to filter out these cases beforehand.

**Comment by ymodak** [comment]
Closing this issue for now Feel free to revisit if necessary. Thank you.
