### ISSUE TITLE
libhexagon_interface.so for non Android - eLinux platform

### ISSUE THREAD

**Issue by Hozzu** [tensorflow/tensorflow#43637]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Automotive Grade Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: SA8195P
- TensorFlow installed from (source or binary): source
- TensorFlow version: r2.3
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): aarch64-linux-gnu 8.3.0

**Describe the problem**
Hello.
I'm trying to get hexagon delgate to work on Qualcomm's SA8195P platform. This platform is based on Snapdragon 8xx series. But the problem is that this platform works on Automotive Grade Linux. The currently available libhexagon_interface.so doesn't work as it has Android dependencies. I cannot find the source code of libhexagon_interface.so in tensorflow git. Is it possible to get source code of libhexagon_interface.so or a complied binary of libhexagon_interface.so for aarch64 Linux without Android dependencies?

I noticed that the binary of libhexagon_interface.so for openwrt is provided to hardiksd.
https://github.com/tensorflow/tensorflow/issues/39736

Thank you.

**Comment by Saduf2019** [comment]
@Hozzu 
Please refer to these issues and let us know if it helps: #35506 #39736 #38302

**Comment by Hozzu** [comment]
> @Hozzu
> Please refer to these issues and let us know if it helps: #35506 #39736 #38302

I understand that the source code cannot be shared because of license.
Then, I want to get the binary of libhexagon_interface.so for aarch64 Linux without Android dependencies.
It seems that karimnosseir sent this binary to some people.
How can I get it?

**Comment by Saduf2019** [comment]
@karimnosseir  could you please share the requested binary.

**Comment by Hozzu** [comment]
> @karimnosseir could you please share the requested binary.
> 
> @Hozzu please share your email id as done in the above issues.

pkshin@redwood.snu.ac.kr

Thank you!

**Comment by karimnosseir** [comment]
@Hozzu Thanks, i will reach out directly shortly

Thanks

**Comment by Saduf2019** [comment]
@karimnosseir 
Thank you for your update.
@Hozzu 
Please move this issue to closed status once resolved.

**Comment by Hozzu** [comment]
Thank you @karimnosseir @Saduf2019

**Comment by r-wheeler** [comment]
@karimnosseir I have the same request, Could you please share?

**Comment by karimnosseir** [comment]
@r-wheeler Can you please reach out directly to me ? email same as my name here.

Thanks
