### ISSUE TITLE
CMake issues when building TFLite

### ISSUE THREAD

**Issue by G4V** [tensorflow/tensorflow#43646]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.5 LTS
- TensorFlow installed from (source or binary): source
- TensorFlow version: 8a643858ce174b8b (master)
- Bazel version (if compiling from source): CMake 3.18.2
- GCC/Compiler version (if compiling from source): GCC 7.5.0 / LLVM 6.0

**Describe the problem**

I'm seeing various issues whilst trying to build `libtensorflow-lite.a`. I have a fix for the first but not sure what the remedy is for the others.

1] Missing dependency on `sparsity` required by `lite/kernels/density.cc` and `lite/kernels/fully_connected.cc`

This fixes

```
diff --git a/tensorflow/lite/CMakeLists.txt b/tensorflow/lite/CMakeLists.txt
index ac7e373f18..b731401fc1 100644
--- a/tensorflow/lite/CMakeLists.txt
+++ b/tensorflow/lite/CMakeLists.txt
@@ -264,6 +264,10 @@ populate_tflite_source_vars("kernels/internal/reference/integer_ops"
 populate_tflite_source_vars("kernels/internal/reference/sparse_ops"
   TFLITE_KERNEL_INTERNAL_REF_SPARSE_OPS_SRCS
 )
+populate_tflite_source_vars("tools/optimize/sparsity"
+  TFLITE_TOOLS_OPTIMIZE_SPARSITY_SRCS
+)
+
 
 # Common include directories
 include_directories(
@@ -294,6 +298,7 @@ add_library(tensorflow-lite
   ${TFLITE_KERNEL_SRCS}
   ${TFLITE_NNAPI_SRCS}
   ${TFLITE_SRCS}
+  ${TFLITE_TOOLS_OPTIMIZE_SPARSITY_SRCS}
 )
 target_link_libraries(tensorflow-lite
   PUBLIC

```

2] The built library `libtensorflow-lite.a` doesn't itself include all the dependencies it needs as build in `[build dir]/_deps`

3] Enabling `TFLITE_ENABLE_XNNPACK` gives the following error when built with GCC (build's OK with LLVM)

```
/home/gavin/CK-TOOLS/lib-tflite-src-static-gcc-7.5.0-v2.3.91-with.xnnpack-linux-64/build/xnnpack/src/f16-clamp/gen/neonfp16arith-x16.c: In function ‘xnn_f16_clamp_ukernel__neonfp16arith_x16’:
/home/gavin/CK-TOOLS/lib-tflite-src-static-gcc-7.5.0-v2.3.91-with.xnnpack-linux-64/build/xnnpack/src/f16-clamp/gen/neonfp16arith-x16.c:32:44: warning: passing argument 1 of ‘vld1q_dup_f16’ from incompatible pointer type [-Wincompatible-pointer-types]
   const float16x8_t vy_min = vld1q_dup_f16(&params->min);
                                            ^
In file included from /home/gavin/CK-TOOLS/lib-tflite-src-static-gcc-7.5.0-v2.3.91-with.xnnpack-linux-64/build/xnnpack/src/f16-clamp/gen/neonfp16arith-x16.c:12:0:
/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:17359:1: note: expected ‘const float16_t * {aka const __fp16 *}’ but argument is of type ‘const uint16_t * {aka const short unsigned int *}’
 vld1q_dup_f16 (const float16_t* __a)
 ^~~~~~~~~~~~~
```

4] Building `TFLITE_ENABLE_XNNPACK` with LLVM looks like it builds all the right things but doesn't affect performance.

**Comment by ymodak** [comment]
Did you get a chance to refer [Build TensorFlow Lite with CMake](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/cmake#build-tensorflow-lite-with-cmake) guide?

**Comment by G4V** [comment]
Hi @ymodak, yes as per the instructions. Bit tricky to read, but it's wrapped up in this script -

https://github.com/ctuning/ck-tensorflow/blob/master/package/lib-tflite-cmake/scripts.linux/install.sh

**Comment by terryheo** [comment]
Could you make a PR on 1 & 2?
Regarding 4, you need to enable xxnpack delegate to get the performance improvement.
https://blog.tensorflow.org/2020/07/accelerating-tensorflow-lite-xnnpack-integration.html

**Comment by terryheo** [comment]
CMake build should be fine now.

https://www.tensorflow.org/lite/guide/build_cmake
