### ISSUE TITLE
Keras EarlyStopping callback on val_auc running mysteriously

### ISSUE THREAD

**Issue by innovativeC** [tensorflow/tensorflow#43645]
**System information**
- OS : Windows 10
- Python version : 3.6.5
- Tensorflow : 2.3.0
### Simple DL GridsearchCV modelling using Keras

```
epochs = [1, 6, 11, 16, 21, 26, 31, 36, 41, 46]
batch_size = [2,4]

 stopper = EarlyStopping(monitor='val_auc', patience= 10, mode = 'max', min_delta = 1, restore_best_weights=True)
 save_mod = ModelCheckpoint(r'C:\......................\best_model.h5', monitor='val_acc', mode='max', save_best_only=True, save_freq 
 = 'epoch')

 param_grid = dict(epochs = epochs, batch_size = batch_size)

 def create_classify_model(learn_rate = 0.01, momentum = 0):
            # create model
            network = Sequential()
            #input layer and 1st hidden layer
            network.add(Dense(units = data_seg.x_tr.shape[1], activation="relu", input_shape = 
            (data_seg.x_tr.shape[1],)))

            #dropout layer for input layer
            network.add(Dropout(0.2, input_shape = (data_seg.x_tr.shape[1],)))

            #second hidden layer
            network.add(Dense(units = math.trunc(data_seg.x_tr.shape[1]*0.8), activation = "relu"))

            #dropout layer for hidden layer
            network.add(Dropout(0.5))

            #output layer
            network.add(Dense(units = len(np.unique(data_seg.y_tr)), activation = "softmax"))

            optimizer = SGD(lr=learn_rate, momentum=momentum)

            #compiling neural network
            network.compile(loss = "categorical_crossentropy", optimizer = optimizer, metrics = 
['acc',auc_metric()])

            return network

neural_network = KerasClassifier(build_fn=create_classify_model, workers = -1, use_multiprocessing = 
True, verbose=2)
grid = GridSearchCV(estimator=neural_network, param_grid=param_grid)

fit_params = dict(callbacks=[stopper, save_mod], validation_split = 0.05)

grid_model = grid.fit(data_seg.x_tr, data_seg.y_tr, **fit_params)
```

### Output
`471/471 - 1s - loss: 0.7568 - acc: 0.6019 - auc: 0.6357 - val_loss: 0.4909 - val_acc: 0.7600 - 
val_auc: 0.8676
125/125 - 0s - loss: 0.5264 - acc: 0.7751 - auc: 0.8459
WARNING:tensorflow:Early stopping conditioned on metric `val_auc` which is not available. Available 
metrics are: loss,acc,auc_1,val_loss,val_acc,val_auc_1
472/472 - 1s - loss: 0.7242 - acc: 0.6288 - auc_1: 0.6494 - val_loss: 0.5680 - val_acc: 0.7000 - 
val_auc_1: 0.7896
124/124 - 0s - loss: 0.6316 - acc: 0.6250 - auc_1: 0.6942
WARNING:tensorflow:Early stopping conditioned on metric `val_auc` which is not available. Available 
metrics are: loss,acc,auc_2,val_loss,val_acc,val_auc_2
472/472 - 1s - loss: 0.7193 - acc: 0.6182 - auc_2: 0.6563 - val_loss: 0.5279 - val_acc: 0.7400 - 
val_auc_2: 0.8544
124/124 - 0s - loss: 0.5929 - acc: 0.7863 - auc_2: 0.7995
WARNING:tensorflow:Early stopping conditioned on metric `val_auc` which is not available. Available 
metrics are: loss,acc,auc_3,val_loss,val_acc,val_auc_3
472/472 - 1s - loss: 0.7060 - acc: 0.6299 - auc_3: 0.6649 - val_loss: 0.5369 - val_acc: 0.8000 - 
val_auc_3: 0.8400
124/124 - 0s - loss: 0.5564 - acc: 0.7661 - auc_3: 0.8305
WARNING:tensorflow:Early stopping conditioned on metric `val_auc` which is not available. Available 
metrics are: loss,acc,auc_4,val_loss,val_acc,val_auc_4
472/472 - 1s - loss: 0.7258 - acc: 0.6161 - auc_4: 0.6398 - val_loss: 0.5676 - val_acc: 0.7400 - 
val_auc_4: 0.7936`

The ouput here, showcases that the val_auc metric which has been used to monitor EarlyStopping has been given an integer value, which increases with every epoch end I suppose. Hence, can someone help me understand about how can I monitor the val_auc in this case ?

**Comment by amahendrakar** [comment]
@innovativeC,
On running the given code, I am facing an error stating `NameError: name 'data_seg' is not defined`. 

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by innovativeC** [comment]
@amahendrakar , data_seg.x_tr and data_seg.y_tr are actually the X and Y_true datasets used here. You can insert any classification dataset here, the result I am getting is constant across any classifcation dataset I have used whenever I've utilized auc as stopping metric.

PS - Can't share the complete code, since its proprietary. That being said, only preprocessing of the dataset was done prior to the code shared above..

**Comment by amahendrakar** [comment]
@innovativeC,
In this case, could you please share a dummy dataset with similar shape and size, so that we can reproduce the issue on our end. Thanks!

**Comment by innovativeC** [comment]
@amahendrakar, Sure I am sharing the URL of the dataset I used, [https://www.kaggle.com/vetrirah/av-healthcare2?select=train.csv](url). The data_seg.x_tr and data_seg.y_tr here would be the X and Y sets.

**Comment by amahendrakar** [comment]
@innovativeC,
I am still facing the same error. The dataset you have provided does not seem to have X and Y sets. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/ab52c7d029f2d9531faad4a96a90b557/43645.ipynb#scrollTo=IIaoaolomr55). 

Could you please provide a minimal working code sample, which we can use to reproduce the issue on our end? Thanks!

**Comment by innovativeC** [comment]
@amahendrakar  This is the link to the dataset [https://drive.google.com/file/d/18ZOZ_tiRAXZGCdqaFzHyHYA0J44qytx-/view?usp=sharing](url). Also I have made some changes to the collab notebook which you had shared. You can find it here - [https://colab.research.google.com/gist/innovativeC/7f9df6ab55653628074a3d898cf044c6/43645.ipynb](url)

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/835ee579feee64a865689e2764960d07/43645.ipynb). Thanks!

**Comment by innovativeC** [comment]
@amahendrakar @ymodak Any insights on why this is happening ? Thanks!

**Comment by innovativeC** [comment]
Hi guys, any update on this bug ?

**Comment by shiyu1994** [comment]
Just encountered the same problem when tuning keras model with nni. I observed that the `val_auc[_number]` comes from creating the same model multiple times in one script. The first time we create the model, `val_auc` has no suffix. And each time after the first creation, `val_auc` becomes `val_auc_1`, `val_auc_2`, and so on.

**Comment by cranedroesch** [comment]
Same issue.  Here is a MWE

`import numpy as np
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
import tensorflow as tf

def make_and_fit():
    inp = Input(shape=(1,))
    out = Dense(1, activation='sigmoid')(inp)
    model = Model(inputs=inp, outputs=out)
    auc = tf.keras.metrics.AUC()
    model.compile(loss='binary_crossentropy',
                  metrics=[auc])
    x = np.random.normal(size=10)
    y = np.random.normal(size=10) > 0
    xv = np.random.normal(size=10)
    yv = np.random.normal(size=10) > 0
    earlystopping = tf.keras.callbacks.EarlyStopping(monitor='val_auc',
                                                     patience=2)
    model.fit(x=x,
              y=y,
              validation_data=(xv, yv),
              epochs=2,
              verbose=1,
              callbacks=earlystopping)

for i in range(2):
    make_and_fit()`

**Comment by jvishnuvardhan** [comment]
@innovativeC Is this still an issue for you? Can you please test with recent `TF2.7` and `tf-nightly`?

@cranedroesch i tested your code by adding [`clear_session`](https://www.tensorflow.org/api_docs/python/tf/keras/backend/clear_session)  as shown below. As Keras tracks its inputs/outputs, i think we cannot use same metric name if they are in memory. Clearing them from memory, results in better memory management also as listed [here](https://www.tensorflow.org/api_docs/python/tf/keras/backend/clear_session)


```
for i in range(2):
  tf.keras.backend.clear_session()
  make_and_fit()
```

**Comment by sina-ss** [comment]
I have same issue too:
WARNING:tensorflow:Early stopping conditioned on metric `auc` which is not available. Available metrics are: loss,auc_1
WARNING:tensorflow:Early stopping conditioned on metric `auc` which is not available. Available metrics are: loss,auc_2
WARNING:tensorflow:Early stopping conditioned on metric `auc` which is not available. Available metrics are: loss,auc_3
and ...

**Comment by da-the-dev** [comment]
UserWarning: Early stopping conditioned on metric `val_auc` which is not available. Available metrics are: auc_8,f1_score,loss
