### ISSUE TITLE
Custom loss function is not working

### ISSUE THREAD

**Issue by dhyeythumar** [tensorflow/tensorflow#43650]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 20H2
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.3.0
- Python version: 3.8.3

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1wa93OGIfXVY66GHO6wI1O9PnZyxXB-KJ

**Describe the behavior**
I am implementing the PPO algorithm using Keras but encountered the following issue related to the custom loss function in Keras.

**Error message:**
```bash
Traceback (most recent call last):
  File "C:\Users\dhyey\Desktop\Train-ml-agents\python-envs\offline_training\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  u/tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: old_prediction_input:0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 426, in <module>
    agent.train()
  File "train.py", line 370, in train
    actor_loss = self.actor.fit(
  File "C:\Users\dhyey\Desktop\Train-ml-agents\python-envs\offline_training\lib\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\dhyey\Desktop\Train-ml-agents\python-envs\offline_training\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "C:\Users\dhyey\Desktop\Train-ml-agents\python-envs\offline_training\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\dhyey\Desktop\Train-ml-agents\python-envs\offline_training\lib\site-packages\tensorflow\python\eager\def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "C:\Users\dhyey\Desktop\Train-ml-agents\python-envs\offline_training\lib\site-packages\tensorflow\python\eager\function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "C:\Users\dhyey\Desktop\Train-ml-agents\python-envs\offline_training\lib\site-packages\tensorflow\python\eager\function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "C:\Users\dhyey\Desktop\Train-ml-agents\python-envs\offline_training\lib\site-packages\tensorflow\python\eager\function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\dhyey\Desktop\Train-ml-agents\python-envs\offline_training\lib\site-packages\tensorflow\python\eager\function.py", line 545, in call
    outputs = execute.execute(
  File "C:\Users\dhyey\Desktop\Train-ml-agents\python-envs\offline_training\lib\site-packages\tensorflow\python\eager\execute.py", line 72, in quick_execute
    raise core._SymbolicException(
tensorflow.python.eager.core._SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'old_prediction_input:0' shape=(None, 2) dtype=float32>, <tf.Tensor 'advantage_input:0' shape=(None, 1) dtype=float32>, <tf.Tensor 'reward_input:0' shape=(None, 1) dtype=float32>, <tf.Tensor 'value_input:0' shape=(None, 1) dtype=float32>]
```

**Check the custom loss function [here on Colab](https://colab.research.google.com/drive/1wa93OGIfXVY66GHO6wI1O9PnZyxXB-KJ#scrollTo=DIoqurd3uDb1)**

**Check the actor model [here on Colab](https://colab.research.google.com/drive/1wa93OGIfXVY66GHO6wI1O9PnZyxXB-KJ#scrollTo=rTrPW6F50TbY)**

So after searching I found one work around i.e to add `run_eagerly=True` to the model.compile() method as: `actor_model.compile(... , run_eagerly=True)`

But after applying run_eagerly to true, I am getting 0 loss value from `actor.history['loss']` and to debug this I am not able to print the total_loss value in the ppo_loss(...) function because it gives the `AttributeError: 'Tensor' object has no attribute 'numpy'`.

**Comment by ravikyram** [comment]
@Dhyeythumar 

I have tried in colab with TF version 2.3 and i am seeing different error message( `AttributeError: 'Tensor' object has no attribute 'numpy`').Please, find the gist [here.](https://colab.research.google.com/gist/ravikyram/096aceb3b1dce841a22508c3691af553/untitled404.ipynb). Thanks!

**Comment by Dhyeythumar** [comment]
Yes, I have also mentioned this in the above issue. So when I try to get the value from a tensor in ppo_loss() function I am getting `AttributeError: 'Tensor' object has no attribute 'numpy'` error. Basically, I am doing this to check why I am getting 0 in that ppo_loss function.

**Comment by nikitamaia** [comment]
Hi @Dhyeythumar, this is a lot of custom code to look through. But often a cause of this error message is trying to use numpy ops in graph mode, or relying on python side effects (like appending to lists) instead of using TensorArrays in graph mode. I am not very familiar with gym so I can't point to the exact issue in your code. However, I would suggest taking a look at the [tf.function guide](https://www.tensorflow.org/guide/function) to get a sense of common pitfalls in graph mode. To isolate where the issue is, you might want to try running your code with a standard loss and see if it runs without this error. 

Setting `run_eagerly=True` will get rid of the error message, but it's not a great solution as it can really affect the performance of your code. This should really only be used for debugging purposes.

Additionally, you should update your import statements so you're using `tf.keras` instead of `keras`
eg `from tensorflow.keras.layers import Input, Dense` etc

**Comment by Dhyeythumar** [comment]
Hi @nikitamaia, I did apply the standard loss function and, it works. So I think the problem occurs when I pass extra inputs to the loss function with the help of the Input layer (these values are not included in the Dense layers, but to use these values while calculating losses, I am passing them through Input layers).
I think eager execution is enabled by default from TensorFlow 2.0. So should I disable it?
And sure, I will update the code according to your suggestions and mention the progress here.

**Comment by Dhyeythumar** [comment]
Hi @nikitamaia, I did apply the standard loss function and, it works. So I think the problem occurs when I pass extra inputs to the loss function with the help of the Input layer (these values are not included in the Dense layers, but to use these values while calculating losses, I am passing them through Input layers).

And sure, I will update the code according to your suggestions and mention the progress here.

**Comment by rmothukuru** [comment]
@Dhyeythumar,
Can you please let us know if you have updated the code according to @nikitamaia's suggestions? Thanks!

**Comment by Dhyeythumar** [comment]
Yes, I have updated the colab notebook with a standard loss function and, it works, so definitely, there is a problem with the custom loss function. I have also updated imports like `keras` to `tensorflow.python.keras`. Still, the error remains.

**Comment by sachinprasadhs** [comment]
While trying to reproduce the issue, I'm facing different error in Tf Nightly 2.6, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/06f288fe16749ef985eb85e63ca26c33/43650.ipynb), Thanks!

**Comment by dhyeythumar** [comment]
The custom loss functions works when eager execution is disabled. Check the below notebook.

#### ✅ Works with TensorFlow 2.5.0 (with disabled eager execution)
https://colab.research.google.com/drive/1dqVHrnqUmD5ZipzMwAJa0XcnZE1fh-HG

**Comment by dhyeythumar** [comment]
The main problem is in the custom loss function itself. Some of the data is in **KerasTensor form** and others in **Tensor form**.

```python
def ppo_loss(oldpolicy_probs, advantage, reward, value):
    def loss(y_true, y_pred):
        print(oldpolicy_probs)  # KerasTensor(type_spec=TensorSpec(shape=(None, 2), dtype=tf.float32, name='old_prediction_input'), name='old_prediction_input', description="created by layer 'old_prediction_input'")
        print(advantage)  # KerasTensor(type_spec=TensorSpec(shape=(None, 1), dtype=tf.float32, name='advantage_input'), name='advantage_input', description="created by layer 'advantage_input'")
        print(reward)  # KerasTensor(type_spec=TensorSpec(shape=(None, 1), dtype=tf.float32, name='reward_input'), name='reward_input', description="created by layer 'reward_input'")
        print(value)  # KerasTensor(type_spec=TensorSpec(shape=(None, 1), dtype=tf.float32, name='value_input'), name='value_input', description="created by layer 'value_input'")

        print(y_true)  # Tensor("IteratorGetNext:5", shape=(128, 2), dtype=float32)
        print(y_pred)  # Tensor("model/policy/Tanh:0", shape=(128, 2), dtype=float32)
        
        # ... Other Code ...
    return loss
```

**So what to do in this case? How to pass the values to the custom loss functions so they are also in the Tensor form?**

**Comment by dhyeythumar** [comment]
## Complete Report on Causes

### From TensorFlow 2.3.0:
```python
def ppo_loss(oldpolicy_probs, advantage, reward, value):
    def loss(y_true, y_pred):
        print(oldpolicy_probs) # Tensor("old_prediction_input:0", shape=(None, 2), dtype=float32)
        print(advantage)       # Tensor("advantage_input:0", shape=(None, 1), dtype=float32)
        print(reward)          # Tensor("reward_input:0", shape=(None, 1), dtype=float32)
        print(value)           # Tensor("value_input:0", shape=(None, 1), dtype=float32)

        print(y_true)     # Tensor("IteratorGetNext:5", shape=(128, 2), dtype=float32)
        print(y_pred)     # Tensor("functional_1/policy/Tanh:0", shape=(128, 2), dtype=float32)
        
        # ... Other Code ...
    return loss
```

---

### From TensorFlow 2.5.0:
In custom loss function some of the data is in **KerasTensor form** and others in **Tensor form**.
```python
def ppo_loss(oldpolicy_probs, advantage, reward, value):
    def loss(y_true, y_pred):
        # print(oldpolicy_probs) # KerasTensor(type_spec=TensorSpec(shape=(None, 2), dtype=tf.float32, name='old_prediction_input'), name='old_prediction_input', description="created by layer 'old_prediction_input'")
        # print(advantage)       # KerasTensor(type_spec=TensorSpec(shape=(None, 1), dtype=tf.float32, name='advantage_input'), name='advantage_input', description="created by layer 'advantage_input'")
        # print(reward)          # KerasTensor(type_spec=TensorSpec(shape=(None, 1), dtype=tf.float32, name='reward_input'), name='reward_input', description="created by layer 'reward_input'")
        # print(value)           # KerasTensor(type_spec=TensorSpec(shape=(None, 1), dtype=tf.float32, name='value_input'), name='value_input', description="created by layer 'value_input'")

        # print(y_true)     # Tensor("IteratorGetNext:5", shape=(128, 2), dtype=float32)
        # print(y_pred)     # Tensor("model/policy/Tanh:0", shape=(128, 2), dtype=float32)
        
        # ... Other Code ...
    return loss
```

**So what to do in this case? How to pass the values to the custom loss functions so they are also in the Tensor form?**

**Comment by dhyeythumar** [comment]
**I think a custom loss function only works when a `Tensor` is returned.**

And the main issue here is that custom loss function is returning a `KerasTensor` and not a `Tensor`. **So how to convert a `KerasTensor` to a `Tensor`?**

I have tested this with TensorFlow v2.5.0 and it works when a `Tensor` is returned from a custom loss function.

**Comment by dhyeythumar** [comment]
**I think a custom loss function only works when a `Tensor` is returned. Because I have tested this with TensorFlow v2.5 and it works when a `Tensor` is returned from a custom loss function.**

So the main issue here is that custom loss function is returning a `Symbolic KerasTensor` and not a `Tensor`. And this is happening because inputs to the custom loss function are `Symbolic KerasTensor`. 

**So how to pass the extra parameters in `Tensor` form instead of `Symbolic KerasTensor` to the custom loss function?**

**Comment by dhyeythumar** [comment]
> Can anyone confirm that the below workaround will do the job or not?

I think this workaround might sound silly, but this option can work for the time being until we are able to pass extra parameters to the custom loss function.

**I have tested this workaround and it works (check the colab notebook at the end of this comment) but right now I haven't used this it to train any network/model. (I will update this comment once I do the test the performance)**

---

**Step 1: Use a global variable for the extra parameters required in the custom loss function**
```python
# Extra Data required for loss calculations
BUFFER_DATA = {
    "example_parameter": 0,
    # ...  # other extra parameters required for loss function
}
```

**Step 2: Create a class with a batch extract method which will extract the batches from the above `BUFFER_DATA`**
```python
class BufferHandler:
    buffer_start = 0
    buffer_end = 0
    new_batch_call = 0
    extracted_batch = {
        "example_parameter": 0,
    }
    @classmethod
    def extractBatch(cls): # extract batch out of the buffer data
        cls.new_batch_call += 1
        if cls.new_batch_call == 1:
            cls.buffer_start = 0
        else:
            cls.buffer_start += BATCH_SIZE
        cls.buffer_end = cls.buffer_start + BATCH_SIZE

        if BUFFER_SIZE / BATCH_SIZE == cls.new_batch_call:
            cls.new_batch_call = 0

        print("Buffer start :: ", cls.buffer_start, "\tBuffer end :: ", cls.buffer_end)
        cls.extracted_batch["example_parameter"] = BUFFER_DATA["example_parameter"][cls.buffer_start : cls.buffer_end, :],
```

**Step 3: Use the callback to monitor the batch_begin trigger so we can extract a new batch from our `BUFFER_DATA`**
```python
class MonitorBatches(Callback):
    def on_batch_begin(self, batch, logs=None):
        print("\n >> Starting with a new batch index :: ", batch)
        BufferHandler.extractBatch()
```

**Step 4: Use the `extracted_batch` data from `BufferHandler` class in your custom loss function**
```python
def ppo_loss(y_true, y_pred):
    print("--- Starting with the loss calculations ---")
    # print(BufferHandler.extracted_batch["example_parameter"])
    print("--- Ending the loss calculations ---")
    return loss
```

**Step 5: Once you collect the date store them to `BUFFER_DATA` before calling the .fit() method**
```python
BUFFER_DATA["example_parameter"] = tf.convert_to_tensor(example_parameter, dtype=tf.float32)
print("Updated the Global Buffer Data")
```

**Step 6: Call the .fit() method as shown below**
```python
model_loss_history = your_model.fit(
    x=[input],
    y=[output],
    shuffle=False,
    batch_size=BATCH_SIZE,
    epochs=NUM_EPOCH,
    verbose=0,
    callbacks=[MonitorBatches()]
)
```

**Here if I consider the following configs:**
```python
BATCH_SIZE = 128
NUM_EPOCH = 3
BUFFER_SIZE = 512 # this means that input & output have shape = (512, x)
```
Now for each epoch, the input & output is divided into 4 batches, so our `BufferHandler` class will also divide the extra parameters into 4 batches and I can use them in the loss functions.

**Standalone code to reproduce this workaround with Tensorflow 2.5.0:**
https://colab.research.google.com/drive/1spQZv_rTHcoOCMWnUom2KKWy12BThVnE

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0 , please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/036c354539585bd24414891688686dd6/43650.ipynb). Thanks!

**Comment by Mastiff37** [comment]
I'm struggling with this too (passing extra arguments to loss function, which are keras inputs).  Code that used to work no longer does with TF 2.5.

**Comment by SuryanarayanaY** [comment]
Hi @dhyeythumar ,

To define custom loss function which takes additional arguments other than  y_true and y_pred you have to do in the below mentioned way as per documentation.
```

If you need a loss function that takes in parameters beside y_true and y_pred, you can subclass the [tf.keras.losses.Loss](https://www.tensorflow.org/api_docs/python/tf/keras/losses/Loss) class and implement the following two methods:

__init__(self): accept parameters to pass during the call of your loss function
call(self, y_true, y_pred): use the targets (y_true) and the model predictions (y_pred) to compute the model's loss
```
I have gone through your code and iam unable to find the implementation of loss function as mentioned above.
Please go through the documentation link attached [here] (https://www.tensorflow.org/guide/keras/train_and_evaluate#custom_losses) for more details and a demo example.

Please let us know if the provided information from documentation helps to resolve your issue.

Thankyou!

**Comment by Mastiff37** [comment]
> Please let us know if the provided information from documentation helps to resolve your issue.
> 
> Thankyou!

I may be misunderstanding, but it looks like the documented approach only allows fixed constant parameters, defined when the loss is created.  For the OP and myself, we need the loss to be a function of things that change with each training example.  An example would be if the loss wanted the model input in addition to y_true and y_pred.
