### ISSUE TITLE
A new feature in tf.roll

### ISSUE THREAD

**Issue by yiliu9090** [tensorflow/tensorflow#43655]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
Tensorflow 2.1.0
- Are you willing to contribute it (Yes/No):
Yes

**Describe the feature and the current behavior/state.**
Currently, tensorflow only allows for same shift in the same dimension. I want different shift ability

[[1,2,3,4],
[1,2,3,4],
[1,2,3,4]] 
can be only turned into 
[[2,3,4,1],
[2,3,4,1],
[2,3,4,1]] in the current iteration. 
I need a roll function that can get this without using any for loop, I also need it for any dimension tensor , i.e. 4 dimension that I work on. 
[[2,3,4,1],
[3,4,1,2],
[4,1,2,3]]

**Will this change the current api? How?**

Yes by adding a property. 

**Who will benefit with this feature?**

People who work on system biology using tensorflow for transcription data. A great deal of this will be used in this paper which I authored. I want to expand it to make it more flexible. 

https://academic.oup.com/bioinformatics/article/36/Supplement_1/i499/5870526?itm_content=bioinformatics&itm_source=trendmd-widget&itm_campaign=trendmd-pilot&itm_medium=sidebar

**Any Other info.**
Last time, it was closed using a replace method but it only solve the example problem I give, not the full problem.

**Comment by rmothukuru** [comment]
@yiliu9090,
[tf.roll](https://www.tensorflow.org/api_docs/python/tf/roll) now provides a facility to specify **`Multiple Axes`**. Can you PTAL? Thanks!

**Comment by yiliu9090** [comment]
Sorry about the delay. 
This is not what I really wanted for tf.roll. What I mean is that if there are multiple 
Currently, tensorflow only allows for same shift in the same dimension. I want different shift for the same axis just different roll. 
For Example 
[[1,2,3,4],
[1,2,3,4],
[1,2,3,4]]
can be only turned into
[[2,3,4,1],
[2,3,4,1],
[2,3,4,1]] in the current iteration.
I need a roll function that can get this without using any for loop, I also need it for any dimension tensor , i.e. 4 dimension that I work on.
[[2,3,4,1],
[3,4,1,2],
[4,1,2,3]]
Here note that shift all happens at dimension 1, but the shift is 1,2,3 for different rows.  
So this works a little differently from the what I initial thought. 

What you have is still same axis same level, so it is impossible to do this. (If I am wrong please tell me how to do this in current iteration)

Thanks so much.

**Comment by LeeAaronHarris** [comment]
I could use this feature too, and I am happy to contribute to it.

Given a tensor of shape (n, y, x) 

My current solution is to break the matrix into a list:
`list = [list[item] for item in range(n)]`

and then use another loop to pad/roll each list tensor:
`for iter in range(len(list)):
            xShift = (iter % xShift)
            yShift = int(iter / yShift)
            list[iter] = tf.roll(list[iter], shift= [yShift, xShift], axis= [0, 1])`

the list can then be converted back to a tensor using:
`list = tf.convert_to_tensor(list)`

This is inefficient, but it works for my usecase.

**Comment by lampuiho** [comment]
if you don't want to loop, use map_fn as follows:
```
test=tf.repeat(tf.expand_dims(tf.range(5),0),4,0);
out = tf.map_fn(lambda arr: tf.roll(arr, tf.random.uniform( [1], 0, 6, dtype=tf.int32 ), 0), test);
```

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
