### ISSUE TITLE
Error "Cannot iterate over a tensor with unknown first dimension" when using TF Keras Attention Layer.

### ISSUE THREAD

**Issue by BlueLobster413** [tensorflow/tensorflow#43651]
Hello,
I'm trying to implement a Text Summarizing model Seq2Seq model with Attention layer, while building the layer, I'm getting the above error exactly at Attention Layer which is imported from TF Keras Layer.

Code Section:
`# Decoder
decoder_input = Input(shape=(None,))
decoder_embed = Embedding(y_vocab_size, embedding_dim, trainable=True)(decoder_input)

decoder_lstm1 = LSTM(300, return_state=True, return_sequences=True, dropout=0.4)
decoder_lstm_output, decoder_h, decoder_c = decoder_lstm1(decoder_embed, initial_state=[encoder_h, encoder_c])

att_output, att_state = Attention()([encoder_output, decoder_lstm_output])
decoder_concat_output = Concatenate(axis=-1)([decoder_lstm_output, attn_out])

Error:
TypeError                                 Traceback (most recent call last)
<ipython-input-13-a3d0f9f7e616> in <module>()
     25 decoder_lstm_output, decoder_h, decoder_c = decoder_lstm1(decoder_embed, initial_state=[encoder_h, encoder_c])
     26 
---> 27 att_output, att_state = Attention()([encoder_output, decoder_lstm_output])
     28 decoder_concat_output = Concatenate(axis=-1)([decoder_lstm_output, attn_out])
     29 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in __iter__(self)
    510     if shape[0] is None:
    511       raise TypeError(
--> 512           "Cannot iterate over a tensor with unknown first dimension.")
    513     return _TensorIterator(self, shape[0])
    514 

TypeError: Cannot iterate over a tensor with unknown first dimension.`

Can anyone please help me on this? I'm sharing the link to Colab notebook as well. Thanks!

Google Colab Notebook Link:
https://colab.research.google.com/drive/1EvxOwIH8yeqS7pRJh9aNF-XXoj0N0uQw?usp=sharing

**Comment by Saduf2019** [comment]
@BlueLobster413 
please refer to [this link](https://stackoverflow.com/questions/56351377/tensorflow-2-0-input-being-creating-with-first-shape-element-as-none) and let us know if it helps. [also [link](https://www.xspdf.com/resolution/50082506.html) ]

**Comment by dineshy98** [comment]
> @BlueLobster413
> please refer to [this link](https://stackoverflow.com/questions/56351377/tensorflow-2-0-input-being-creating-with-first-shape-element-as-none) and let us know if it helps. [also [link](https://www.xspdf.com/resolution/50082506.html) ]

I tried above solutions but didnt worked for me, Did you find any alternate solutions

**Comment by Saduf2019** [comment]
@dineshy98 
Could you please open a new issue with all the required information for us to analyse.
