### ISSUE TITLE
Build tensorflow from source with CUDA failed

### ISSUE THREAD

**Issue by apollos** [tensorflow/tensorflow#4365]
I am trying to build tensorflow in Ubuntu 14.04 but failed. My steps:

1. git rev-parse HEAD
c715c3102df1556fc0ce88fc987440a3c80e5380

2. bazel version
Warning: ignoring _JAVA_OPTIONS in environment.
Another command is running (pid = 13101).  Waiting for it to complete...
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 01 00:00:00 1970 (0)
Build timestamp: Thu Jan 01 00:00:00 1970 (0)
Build timestamp as int: 0

3. ./configure 
Please specify the location of python. [Default is /usr/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 7.5
Please specify the location where CUDA 7.5 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5
Please specify the location where cuDNN 5 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 
Warning: ignoring _JAVA_OPTIONS in environment.
..
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
Warning: ignoring _JAVA_OPTIONS in environment.
.
WARNING: /home/yu/.cache/bazel/_bazel_yu/520915e94204a8ab6d3b139e9ec5cf67/external/boringssl_git/WORKSPACE:1: Workspace name in /home/yu/.cache/bazel/_bazel_yu/520915e94204a8ab6d3b139e9ec5cf67/external/boringssl_git/WORKSPACE (@boringssl) does not match the name given in the repository's definition (@boringssl_git); this will cause a build error in future versions.
INFO: All external dependencies fetched successfully.
Configuration finished

4. bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
external/zlib_archive/zlib-1.2.8/gzread.c:591:5: warning: implicit declaration of function 'close' [-Wimplicit-function-declaration]
     ret = close(state->fd);
     ^
ERROR: missing input file '@local_config_cuda//cuda:lib64/libcudnn.so.5':/home/yu/.cache/bazel/_bazel_yu/520915e94204a8ab6d3b139e9ec5cf67/external/local_config_cuda/cuda/lib64/libcudnn.so.5 (Permission denied).
ERROR: /home/yu/.cache/bazel/_bazel_yu/520915e94204a8ab6d3b139e9ec5cf67/external/re2/BUILD:9:1: C++ compilation of rule '@re2//:re2' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter ... (remaining 37 argument(s) skipped): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 15.
ERROR: /home/yu/workspace/tensorflow/tensorflow/cc/BUILD:199:1: //tensorflow/cc:tutorials_example_trainer: missing input file '@local_config_cuda//cuda:lib64/libcudnn.so.5'.
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/yu/workspace/tensorflow/tensorflow/cc/BUILD:199:1 1 input file(s) do not exist.

The libcudnn.so.5 exist and I can build and run other cudnn code. How can I fix the error?

**Comment by MatthiasWinkelmann** [comment]
Try actually repeating the default ```/usr/local/cuda``` when it asks you for the library path during configure.

**Comment by gunan** [comment]
I was able to reproduce this problem locally with cuda8.0, cudnn5.1 on ubuntu 16.04
For me, it actually also complained about my header files not being there (permission denied)
Until we get to the bottom of this, I was able to create a workaround by making my /usr/local/cuda world read/writeable
$ sudo chmod 777 -R /usr/local/cuda
With this, compilation was OK with my cuda libraries.
I suspect this is a bazel issue?
@damienmg Why does bazel want my cuda headers and .so files to be writeable.

**Comment by damienmg** [comment]
Sorry just realized I haven't answered that bug. It should definitely not require it.

Maybe @davidzchen has some clues about that. I have no idea what is going wrong there.

**Comment by damienmg** [comment]
Wait is that on OS X ? With Bazel HEAD?

**Comment by damienmg** [comment]
Disregard last message, it is not with OS X. Though know the Bazel version would be great.

**Comment by damienmg** [comment]
For completeness to repro:
- A full repro to get the environment (I still haven't installed cudnn on my machine, sorry for that). Maybe a docker container?
- What does `ls -l $(bazel info output_base)/external/local_config_cuda/cuda/lib64/libcudnn.so.5` returns after the failure?

**Comment by gunan** [comment]
I ran into the problem with bazel 0.3.1
Unfortunately, we completely missed this with docker, because in a docker container we log in as root, and everything is read/writable for us.

I will uninstall and reinstall cuda8 and cudnn5 to see if I can go back to the broken state of things for me.

**Comment by damienmg** [comment]
Ok I need to try it out I guess on latest ubuntu? Will do as soon as I can free some bandwidth.

**Comment by gunan** [comment]
Saw this issue on 14.04
Trying to reproduce by breaking my environment, will try to come up with detailed instructions.

**Comment by gunan** [comment]
@apollos I ran into this issue before, but now I cannot reproduce it on my machine.
If you sync to head, can you still see the problem?

If not, can we close this issue?

**Comment by apollos** [comment]
Sorry for my late. I update the bazel and then the issue fixed.
