### ISSUE TITLE
tf.keras.layers.experimental.preprocessing.CategoryEncoding: is it possible to apply it to a nD tensor?

### ISSUE THREAD

**Issue by scd75** [tensorflow/tensorflow#43667]
**System information**
- TensorFlow version (you are using): 2.4.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**: currently, tf.keras.layers.experimental.preprocessing.CategoryEncoding layers can only be called with a 2D tensor of shape (samples, "timesteps"). It would be very useful to allow calling with a nD tensor, for example when working with sequences.. As for "Normalization" Layer, an "axis" parameter could be added to the layer parameters.
For instance, I would like to use a CategoryEncoding Layer on sequence-input data with the following shape (samples, timesteps, nb_features).
When nb_features= 1 Application of CategoryEncoding Layer to such tensor would return a tensor of shape  (samples, timesteps, nb_classes_in_the_first_feature).

**Will this change the current api? How?**

**Who will benefit with this feature?**
Anyone who wishes to apply Categorical preprocessing such as one-hot encoding to categorical features of sequence / Timeserie data

**Any Other info.**

**Comment by tanzhenyu** [comment]
Contributions welcome!

**Comment by TDHTTTT** [comment]
Can I work on this? Or maybe @scd75 is already working on it?

**Comment by scd75** [comment]
Hi, I was planning to take a look but did not start yet, so please go ahead.
Plus I am not a coding expert per se, so I guess you would produce a better result!

**Comment by hfahrudin** [comment]
Is there anyone still working on this feature? i would like to take on the challange.

**Comment by tanzhenyu** [comment]
Sounds good

**Comment by hfahrudin** [comment]
Is this already implemented? There are an explaination about multi-hot encoding with this API on this [docs ](https://www.tensorflow.org/api_docs/python/tf/keras/layers/experimental/preprocessing/CategoryEncoding?version=nightly). Maybe someone already working on this.

**Comment by shrikumaran** [comment]
Hey can I work on this seems interesting
@scd75 can you post any sample data in the type you mentioned

**Comment by Aditya-Komaravolu** [comment]
Hello!
I am newbie to open source contribution and really interested to contribute to this project!! . But I have very very less knowledge about it @tanzhenyu . Can you help me please?

**Comment by superp0tat0** [comment]
@hfahrudin @scd75 
I think the documentation is talking different things. Also the documentation is out of date.
Document says:
```
>>>layer = tf.keras.layers.experimental.preprocessing.CategoryEncoding(max_tokens=4)
>>>layer([[0, 1], [0, 0], [1, 2], [3, 1]])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.]], dtype=float32)>
```

Issues want
```
>>>layer = tf.keras.layers.experimental.preprocessing.CategoryEncoding(max_tokens=2, axis = 2)
>>>new_data = np.array([[[1], [3]],
                     [[2], [3]],
                     [[1], [2]]])
>>>print(new_data.shape)
(3, 2, 1)
>>>print(layer(new_data))
<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[1., 0.], [1., 1.]],
           [[0., 1.], [1., 1.]],
           [[1., 0.], [0., 1.]]], dtype=float32)>
```
But now it gave

```
InvalidArgumentError: Shape must be at most rank 2 but is rank 3 [Op:DenseBincount]
```

So If I understand it correctly. I could contribute on this question. But need to check with your current progress.

**Comment by reid-sutherland** [comment]
@superp0tat0 @scd75 @hfahrudin Is there any update on this issue? This is something I would very much like to see implemented. Am I the only one that is surprised this is not already the default behavior?

I could contribute if needed but it seems I am not the only one interested.
