### ISSUE TITLE
Compiling client code with -mavx2 leads to Eigen errors

### ISSUE THREAD

**Issue by themightyoarfish** [tensorflow/tensorflow#43666]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **macOS 10.14**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **n/a**
- TensorFlow installed from (source or binary): **binary** (compiled in CI, transferred to client system)
- TensorFlow version (use command below): **v2.3.0**
- Python version: **n/a**
- Bazel version (if compiling from source): **3.1.0**
- GCC/Compiler version (if compiling from source): Apple Clang 11.0.0 for the client code (not sure which compiler did the tf build, but likely the same or 10.0.0)
- CUDA/cuDNN version: **n/a**
- GPU model and memory: **n/a**

**Describe the current behavior**

We have compiled the C++ library from 2.3.0 and are now using it from our Code. A line such as 
```
#include <tensorflow/cc/saved_model/loader.h>
```
Leads to a compilation failure when `-mavx2` is used:

```
In file included from /build/<ycode>.hpp:20:
In file included from /build/libs/tensorflow/include/tensorflow/cc/saved_model/loader.h:27:
In file included from /build/libs/tensorflow/include/tensorflow/core/public/session.h:24:
In file included from /build/libs/tensorflow/include/tensorflow/core/framework/tensor.h:23:
In file included from /build/libs/tensorflow/include/tensorflow/core/framework/allocator.h:26:
In file included from /build/libs/tensorflow/include/tensorflow/core/framework/numeric_types.h:24:
In file included from /build/libs/tensorflow/include/third_party/eigen3/unsupported/Eigen/CXX11/FixedPoint:41:
/build/libs/tensorflow/include/third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX2.h:30:9: error: no template named 'eigen_packet_wrapper'
typedef eigen_packet_wrapper<__m256i, 20> Packet32q8i;
```

Inspecting that file shows that the template is indeed not defined. Other Eigen headers for Neon or SSE (consider `/usr/local/include/eigen3/Eigen/src/Core/arch/SSE/PacketMath.h` in Eigen 3.3.7) do include this template.

**Describe the expected behavior**

Client C++ program compiles against TF 2.3.0 when `-mavx2` or-march=native` are enabled.

**Standalone code to reproduce the issue**

```
# test.cpp
#include <tensorflow/cc/saved_model/loader.h>

int main(int argc, char *argv[])
{
    return 0;
}
```
This works:
```
clang -std=c++14 -L libs/tensorflow/lib/ -isystem /usr/local/include/eigen3/ -isystem libs/tensorflow/include/third_party/eigen3/ -isystem libs/tensorflow/include/ -ltensorflow_cc -lstdc++ test.cpp
```
This does not work:
```
clang -mavx2 -std=c++14 -L libs/tensorflow/lib/ -isystem /usr/local/include/eigen3/ -isystem libs/tensorflow/include/third_party/eigen3/ -isystem libs/tensorflow/include/ -ltensorflow_cc -lstdc++ test.cpp
```

Tensorflow directory:
```
tree -L 2 libs/tensorflow/
libs/tensorflow/
├── include
│   ├── absl
│   ├── external
│   ├── tensorflow
│   └── third_party
└── lib
    ├── libtensorflow_cc.so
    └── libtensorflow_cc.so.2 -> libtensorflow_cc.so
```

This problem for instance prevents me from using some libraries who's CMake configuration brings the `march=native` or `mavx2` flags into the build.

**Comment by themightyoarfish** [comment]
I have confirmed that upgrading the system eigen to current master (30960d485ec7e45b095d3ad206b2dbcc8bc835ba) resolves this problem.

**Comment by bhack** [comment]
Tensorflow is currently on this hash https://github.com/tensorflow/tensorflow/blob/ed63e8a52c49702e06fc5c4f87dc240dd638f627/tensorflow/workspace.bzl#L234-L244

/cc @ezhulenev

**Comment by themightyoarfish** [comment]
Maybe there should be a mention of the required Eigen version in some piece of the documentation (which is sparse anyway for C++).

**Comment by bhack** [comment]
Can you close this and open an new Doc type issue?

**Comment by rmlarsen** [comment]
TensorFlow tracks the head of the dev branch of Eigen quite closely, and
has not been tested with the stable 3.3.x branch for several years.

**Comment by themightyoarfish** [comment]
Solution: Use the same/newer Eigen version as the one TF uses.
