### ISSUE TITLE
Error converting from TensorFlow frozen graph to TFLite using TF1.15

### ISSUE THREAD

**Issue by yousef-xailient** [tensorflow/tensorflow#43660]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 20.04**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (or github SHA if from source): **1.15.0**

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.
```
input_name = 'import/first_graph_input'
output_name = 'import_1/second_graph_output/Mean'
converter = tf.lite.TFLiteConverter.from_frozen_graph('minimal_093010.pb', input_arrays=[input_name], output_arrays=[output_name])

converter.optimizations = [tf.lite.Optimize.DEFAULT]

def representative_dataset_gen():
  image = np.random.randint(low=0, high=255, size=(480, 640, 3))
  image = image.astype(np.float32)
  yield [image]

converter.representative_dataset = representative_dataset_gen
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

model = converter.convert()
```

**Link to Colab Notebook**

```
https://colab.research.google.com/drive/1CN8iIlznqCMK7hRBwHw8kP2RLamwGZeQ?usp=sharing
```

**The output from the converter invocation**

```
RuntimeError: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.Failed to create calibrator, context already registered.
```

**Also, please include a link to the saved model or GraphDef**

```
https://drive.google.com/file/d/1dkc3-tYwviEyFJg2Y0IZEyRdTbKj5piF/view?usp=sharing
```

**Failure details**
```
Conversion fails. It is successful for non-quantized tflite graphs, but fails when doing full-integer quantization.
```

**Traceback**
```
Traceback (most recent call last):
  File "src/convert_pb_to_tflite.py", line 60, in <module>
    main()
  File "src/convert_pb_to_tflite.py", line 48, in main
    convert_pb_to_tflite_with_quantization(args.pb_graph_path, args.tflite_graph_path)
  File "src/convert_pb_to_tflite.py", line 41, in convert_pb_to_tflite_with_quantization
    model = converter.convert()
  File "/home/yousef/miniconda3/envs/tf15/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py", line 993, in convert
    inference_output_type)
  File "/home/yousef/miniconda3/envs/tf15/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py", line 239, in _calibrate_quantize_model
    inference_output_type, allow_float)
  File "/home/yousef/miniconda3/envs/tf15/lib/python3.7/site-packages/tensorflow_core/lite/python/optimize/calibrator.py", line 75, in calibrate_and_quantize
    self._calibrator.FeedTensor(calibration_sample)
  File "/home/yousef/miniconda3/envs/tf15/lib/python3.7/site-packages/tensorflow_core/lite/python/optimize/tensorflow_lite_wrap_calibration_wrapper.py", line 112, in FeedTensor
    return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_FeedTensor(self, input_value)
RuntimeError: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.No calibrator found for context.Node number 0 (CONV_2D) failed to invoke.
```

**Comment by Saduf2019** [comment]
@yousef-xailient 
I ran the code shared but got a different error as "minimal_093010.pb" is missing, you can share a colab gist with the error reported, please note we would be supporting 2.x issues only, there is no support for 1.x
With respect to the error shared it shows that the model you are trying to convert does not implicitly support dynamic shaped inputs, you could fix the input tensor size, and refer to [this link](https://medium.com/google-developer-experts/selfie2anime-with-tflite-part-2-tflite-model-84002cf521dc).
Please upgrade to 2.x and let us know if you face any issues.

**Comment by yousef-xailient** [comment]
@Saduf2019 

I've included the link to the pb graph here https://drive.google.com/file/d/1dkc3-tYwviEyFJg2Y0IZEyRdTbKj5piF/view?usp=sharing

I tried with the latest version of TF (tf-nightly 2.4.0) and the issues I faced are here https://github.com/tensorflow/tensorflow/issues/43661

**Comment by Saduf2019** [comment]
@yousef-xailient 
As we have the issue tracked at #43661, please move this to closed status, please refer to the points and link shared and update.

**Comment by yousef-xailient** [comment]
@Saduf2019 could you run the Colab shared in that issue and report back? The points above do not apply to the other issue as the graph converted successfully.

**Comment by Saduf2019** [comment]
@yousef-xailient 
Please share the colab with access to view it.
