### ISSUE TITLE
Strange internal error after switching from python 3 to python 2

### ISSUE THREAD

**Issue by vladfi1** [tensorflow/tensorflow#4367]
I'm trying to port my code from python 3 to 2. However, I'm getting a strange error when running with python 2: `InternalError: Unsupported feed type`. This happens after trying to `sess.run` with a particular feed dict. What's odd is that I can run the following just fine:

    for k, v in feed_dict.items():
        sess.run(k, {k:v})

That is, the individual arrays and tensors in the feed dict are all fine. I apologize for not being able to come up with a short example that reproduces the error, but perhaps someone might have some idea of what's going on?

**Comment by andydavis1** [comment]
We need a reproducible test case (and other information requested in the template) that demonstrate the issue. Short of that, you might try asking this question on StackOverflow using tag 'tensorflow' to see if others might have a quick answer for you.
