### ISSUE TITLE
Issue in installing the package using pip

### ISSUE THREAD

**Issue by Yuvraj15101999** [tensorflow/tensorflow#43672]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10 64 bit 
- TensorFlow installed from (source or binary): pip
- TensorFlow version:
- Python version:3.8.2
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Tried to install tensorflow using pip but showed, **Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
pip install tensorflow

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@Yuvraj15101999 
As you are using python version 3.8, ensure the tf version is 2.2 or higher and python is 64 bits.
Please post the output of pip3 --version?
Please refer to #43048, #43244, #42977 and let us know.

**Comment by Yuvraj15101999** [comment]
the output of pip3 --version
pip 20.2.3

**Comment by bhack** [comment]
Can you run in python:
```
import sys
print(sys.maxsize > 2**32)
```

**Comment by Yuvraj15101999** [comment]
Yes I'm currently running python 32 bit, I am trying to run 64 bit

**Comment by Saduf2019** [comment]
@Yuvraj15101999 
Please update if the issue is resolved, with the correct python.

**Comment by Yuvraj15101999** [comment]
Done happy to close this issue with TensorFlow installed

**Comment by Saduf2019** [comment]
@Yuvraj15101999 
Glad it worked for you, thanks for the update.
