### ISSUE TITLE
[TransformGraph & TF2 SavedModel] - Missing API

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorflow/tensorflow#43688]
### Issue

When using the latest TF2 release and latest available container (`2.3.1` at the time of writing), it appears that the following API is missing:

```python
from tensorflow.tools.graph_transforms import TransformGraph  # ModuleNotFoundError: No module named 'tensorflow.tools.graph_transforms'
from tensorflow.compat.v1.tools.graph_transforms import TransformGraph  # ModuleNotFoundError: No module named 'tensorflow.compat.v1.tools'
```

Which used to be available in TF1 (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/graph_transforms).

Though it doesn't make much of a sense since Tensorflow 2 ship with the C++ library associated:
```bash
ls -al /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_transform_graph.so 
-rwxr-xr-x 1 root staff 1274144 Sep 29 00:25 /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_transform_graph.so
```

### Motivation

This function is very useful to pre-process and "clean" the graph before inference when using a SavedModel (namely for TF-TRT, could also maybe concerns TF Serving or TF Lite, I didn't check).

Any chance to have this API (or a replacement) back in the TF API ? I understand that TF2 is eager mode oriented, though the SavedModel format is a graph format ... So, would makes sense to keep this API in the mix since the SavedModel format is still actively used and supported in TF2.

CC: @sanjoy @reedwm

**Comment by reedwm** [comment]
@av8ramit do you know why the `TransformGraph` class is not in the pip package anymore? The class is defined [here](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/tools/graph_transforms/__init__.py;l=26;drc=00983e6b0700f9a34e0df980669172b6ea85dad0).

**Comment by av8ramit** [comment]
Thanks for filing the issue @DEKHTIARJonathan. Taking a look and will get back to you.

**Comment by av8ramit** [comment]
So I believe that API was removed from the 2.0 pip package. It appears you can [build it from source](https://github.com/tensorflow/tensorflow/issues/30865#issuecomment-662528252) using bazel. @annarev do you perhaps have more context into alternatives?

**Comment by DEKHTIARJonathan** [comment]
@av8ramit  Building from source might be an issue. In principle, I have nothing against it. However in this case we would it in one of the core APIs of Tensorflow.

We would like to use it in the TF-TRT APIs (`tensorflow/python/compiler/tensorrt`), so we would need to have this available by default in Tensorflow2.

**Comment by annarev** [comment]
Graph transforms were removed and meant to be replaced by Grappler according to this RFC:
https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md

@petewarden, @rmlarsen do you know if there is an alternative for this usecase (pre-process graph before inference with SavedModel)?

**Comment by av8ramit** [comment]
Sorry @DEKHTIARJonathan I am not the best person to answer this (I was looped in in the event this was a pybind export issue), but I'll leave it to Pete and Rasmus to hopefully shed some more light.

**Comment by DEKHTIARJonathan** [comment]
@annarev let me give you a crude of what I could be interested in doing if that could help:

```python
transforms = [
        "remove_nodes(op=Identity, op=CheckNumerics, op=StopGradient, op=Placeholder)",
        "sort_by_execution_order",
        "remove_attribute(attribute_name=_XlaSeparateCompiledGradients)",
        "remove_attribute(attribute_name=_XlaCompile)",
        "remove_attribute(attribute_name=_XlaScope)",
        "sort_by_execution_order",
        'merge_duplicate_nodes',
        "sort_by_execution_order",
        'strip_unused_nodes',
        "sort_by_execution_order",
        'fold_constants(ignore_errors=true)',
        "sort_by_execution_order",
        'fold_batch_norms',
        "sort_by_execution_order",
    ]

    print("Applying Graph Transformations ...")
    return TransformGraph(
        graph_def,
        input_node_names,  # an array of the input node(s)
        output_node_names,  # an array of output nodes
        transforms
    )
```

**Comment by Howave** [comment]
then how to use the transforms in grappler optimization?

**Comment by iaverypadberg** [comment]
Has any progress been made on this? Anybody find a fix?

**Comment by DEKHTIARJonathan** [comment]
@av8ramit @reedwm any update ?

**Comment by av8ramit** [comment]
@DEKHTIARJonathan I no longer work on this project, unfortunately. Good luck!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
