### ISSUE TITLE
kernel changes will break arc

### ISSUE THREAD

**Issue by advaitjain** [tensorflow/tensorflow#43686]
@tensorflow/micro

Once #43682 is merged, the building with TARGET=`arc` and `TAGS=arc_mli` will fail. This is mostly as a result of namespace changes.

Tagging @dzakhar  and @JaccovG.

**Comment by dzakhar** [comment]
Hi @advaitjain, 
Thank you for warning us. We're looking at it. Hopefully we'll make changes soon
