### ISSUE TITLE
No library found under: /usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudart.so.11.1

### ISSUE THREAD

**Issue by summa-code** [tensorflow/tensorflow#43689]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 
- Python version: 3.8.0
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.1
- GPU model and memory:

```bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package```

```Repository command failed
No library found under: /usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudart.so.11.1
INFO: Elapsed time: 0.344s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package```

**Comment by pmeckoni** [comment]
I may be wrong, but won't you need to use `bazel build --config=cuda` for cuda support?

**Comment by amahendrakar** [comment]
@summa-code,
Could you please provide the exact sequence of commands / steps that you executed before running into the problem?

Also, instead of CUDA 11.1 could you please try building TensorFlow using CUDA 11.0 and cuDNN 8, and check if it works. Thanks!

**Comment by summa-code** [comment]
That is the command that i listed above, it works with 11.0 but Nvidia recently released 11.1 and also does a symblink to 11.0, but Bazel script is looking for 11.1. So this is a bug in Bazel script.

**Comment by jacobaustin123** [comment]
This seems to be blocking Jax builds on CUDA 11.1 as well (by way of the TF Bazel config).

**Comment by angerson** [comment]
AFAIK, we don't currently officially support building with CUDA 11.1. @sanjoy is that right?

**Comment by sanjoy** [comment]
Yes, CUDA 11.1 is not supported yet.

**Comment by summa-code** [comment]
Closing, i think the project moved on and we have 11.2 and i dont see any issues
