### ISSUE TITLE
Add Ubuntu 20.04 installation instructions

### ISSUE THREAD

**Issue by pmeckoni** [tensorflow/tensorflow#43693]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://www.tensorflow.org/install/gpu#ubuntu_1804_cuda_101

## Description of issue (what needs changing):

Tensorflow installation instructions for Ubuntu 20.04 with GPU support is needed

### Clear description

With Ubuntu 20.04 around for 6 months, please provide installation instructions for Tensorflow with GPU support. It makes sense to have new development environments set up on Ubuntu 20.04

**Comment by mihaimaruseac** [comment]
What is missing from https://www.tensorflow.org/install/pip ?

**Comment by pmeckoni** [comment]
GPU support seems to be specific for Ubuntu 18.04 and Ubuntu 16.04 as seen on https://www.tensorflow.org/install/gpu#install_cuda_with_apt

**Comment by mihaimaruseac** [comment]
@lamberta / @yashk2810 can we add the Ubuntu 20.04 instructions? Or they don't differ significantly from the existing ones to need additional edits?

**Comment by yashk2810** [comment]
> they don't differ significantly from the existing ones to need additional edits?

I have no idea. Someone needs to try those instructions out on a 20.04 VM and then edit the page.

**Comment by lamberta** [comment]
Currently the [install](https://www.tensorflow.org/install) page lists the requirements as "Ubuntu 16.04 or later" so should make this part f the official support.

cc: @sanjoy @pkanwar23 for GPU support

**Comment by jxu** [comment]
> Under the [Nvidia CUDA Toolkit 10.1 Archive](https://developer.nvidia.com/cuda-10.1-download-archive-base?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu) page there is no official supported version for Ubuntu 20.04. With the release of the new RTX GPUs and soon TF 2.4 I think it would be better to update the [GPU support](https://www.tensorflow.org/install/gpu) page to include instructions for installation of CUDA 11.1 for Ubuntu 20.04. #45308 currently is in the process of addressing this issue.

CUDA is officially supported for Ubuntu 20.04 here https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/

I think the packages in apt are named similarly but idk if named exactly the same

**Comment by sushreebarsa** [comment]
@pmeckoni Could you please refer to the above [comment](https://github.com/tensorflow/tensorflow/issues/43693#issuecomment-964606622) and let us know if it helps?Thanks!

**Comment by pmeckoni** [comment]
No response. I have moved on and no longer have access to the computer which had nvidia. So there is no way I can use this now.

**Comment by Young-Picasso** [comment]
I'm getting a Document Not Found error when trying to train a gradient boosted machine. It says the URI does not point to a valid page. Any help?

**Comment by Indira-kumar** [comment]
Is this issue still open? If yes could you please assign this issue to me @pmeckoni

**Comment by pmeckoni** [comment]
I am no longer trying to use Tensorflow on Ubuntu 20.04. I wanted to use it 2 years back. The owner(s) of this repo may decide to close this comment if they want to.

**Comment by Indira-kumar** [comment]
Thanks for the info
Have a nice day💛

**Comment by SuryanarayanaY** [comment]
The instructions are up to date upto Ubuntu 22.04 and Iam able to install Tensorflow with GPU support for Ubuntu 22.04 also.

Please refer the documentation source [here](https://www.tensorflow.org/install/pip). 

If anybody feel still something is missing please let us know. Thanks!
