### ISSUE TITLE
Project Gutenberg: make printing on TPUs easy!

### ISSUE THREAD

**Issue by amorisot** [tensorflow/tensorflow#43705]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.2
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
I would like to easily print the value of a tensor within a function decorated by `@tf.function`, on TPUs. It is currently only possible through various unpleasant, time-consuming, and error-prone hacks. 
**Will this change the current api? How?**
I don't think so, `tf.print` should cover it.
**Who will benefit with this feature?**
Anyone who uses TensorFlow on TPUs.
**Any Other info.**

**Comment by kenfranko** [comment]
tf.print will work on TPUs if the config option set_soft_device_placement is true (see https://www.tensorflow.org/api_docs/python/tf/config/set_soft_device_placement).  This option is by default false because it can lead to a decrease in performance and should be disabled once debugging with tf.print is complete.

**Comment by idavidrein** [comment]
> tf.print will work on TPUs if the config option set_soft_device_placement is true (see https://www.tensorflow.org/api_docs/python/tf/config/set_soft_device_placement). This option is by default false because it can lead to a decrease in performance and should be disabled once debugging with tf.print is complete.

this didn't work for me. Here's a minimal example in colab: https://colab.research.google.com/drive/1kFdR9tpj7zJjwHIbWRVjVSiA9zwviErK?usp=sharing

I wasn't sure where the config statement should be, so I tried placing it the three obvious scopes (the tf.function, normal python, and the TPU strategy) to no avail.
