### ISSUE TITLE
RTX3080 install RuntimeError: CUDA runtime implicit initialization on GPU:0 failed. Status: device kernel image is invalid

### ISSUE THREAD

**Issue by PureHing** [tensorflow/tensorflow#43701]
**System information**
ubuntu18.04.5 LTS
GeForce RTX 3080 
NVIDIA driver 455.23.04 + CUDA10.1 + Cudnn7.6.5
Anaconda3
envs: tensorflow-gpu==2.3.1
**Describe the problem**
```
import tensorflow as tf
tf.test.is_gpu_available()
```

>...
 2020-10-01 17:18:08.728031: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0, 1
2020-10-01 17:18:08.728126: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/librazxc/.conda/envs/tf23/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/librazxc/.conda/envs/tf23/lib/python3.7/site-packages/tensorflow/python/framework/test_util.py", line 1563, in is_gpu_available
    for local_device in device_lib.list_local_devices():
  File "/home/librazxc/.conda/envs/tf23/lib/python3.7/site-packages/tensorflow/python/client/device_lib.py", line 43, in list_local_devices
    _convert(s) for s in _pywrap_device_lib.list_devices(serialized_config)
RuntimeError: CUDA runtime implicit initialization on GPU:0 failed. Status: device kernel image is invalid

**Any other info / logs**
tensorflow-gpu==2.2 or 2.1 is work well

**Comment by Saduf2019** [comment]
@PureHing 
Please refer this issue and let us know if it helps: #43588

**Comment by PureHing** [comment]
@Saduf2019 it cannot help me.

**Comment by Saduf2019** [comment]
@PureHing 
Could you please try this once and let us know : [link](https://github.com/tensorflow/tensorflow/issues/41990#issuecomment-686853339)

**Comment by frank-qcd-qk** [comment]
Have same issue with 3090

**Comment by frank-qcd-qk** [comment]
> @PureHing
> Could you please try this once and let us know : [link](https://github.com/tensorflow/tensorflow/issues/41990#issuecomment-686853339) and this [link1](https://github.com/tensorflow/tensorflow/issues/43174#issuecomment-702236129)

are you suggesting we should go with cuda 11 and give it a try?

**Comment by frank-qcd-qk** [comment]
Same issue for 3090: issue here: https://github.com/tensorflow/tensorflow/issues/43718

**Comment by Saduf2019** [comment]
@PureHing
Could you Please update.

**Comment by jaentrouble** [comment]
3080 and 3090 does not work with CUDA 10.
You have to use CUDA 11.0 or higher.
Right now, the only way to do so is by installing tf-nightly or building yourself.

**Comment by Saduf2019** [comment]
Please refer to [this link](https://github.com/tensorflow/tensorflow/issues/43629#issuecomment-702851560) and move the issue to closed status if resolved.

**Comment by PureHing** [comment]
@Saduf2019 Tensorflow can be used depending on the following environment:
ubuntu18.04.5 LTS
GeForce RTX 3080*2
NVIDIA driver 455.23.04 + CUDA11.1 + Cudnn8.0.4
Anaconda3
envs: tf-nightly-gpu==2.4.0-dev20201008

**Comment by jvishnuvardhan** [comment]
@PureHing Looks like this is a know issue with GeForce RTX. Similar issues was reported in [this issue](https://github.com/tensorflow/tensorflow/issues/41990). Please check some of the workarounds and root-causes that could help you resolve your issue. Thanks!

**Comment by otakenz** [comment]
I also have this issue and I am using RTX 3070.
I followed @jaentrouble instruction to use tf.nightly builds and it works perfectly after that.

**Comment by IMYin** [comment]
I am using RTX 3080, ubuntu 20.04, kernel 5.4.0.58
I find something ...

```
if CUDA ==11.0:
    if tensorflow < 2.3:
        if cudnn == 8.x:
            tensorflow error: can't find so.7
        elif cudnn == 7.x:
            tensorflow raise: Your CUDA software stack is old.(GPU not working for DL job.)
```
Now, I am trying to change the Nvidia driver version to 11.2.

**Comment by IMYin** [comment]
@IMYin 
Please change TensorFlow to version 2.5.0-dev. it works for me!
