### ISSUE TITLE
Docs: provide CUDA/CuDNN/TensorRT version information for PyPI packages

### ISSUE THREAD

**Issue by bersbersbers** [tensorflow/tensorflow#43712]
The title says it all, but I'll explain nonetheless.

I have CUDA 10.1 Update 2, CuDNN 7.6.5 for CUDA 10.1, TensorRT 6.0.1.5 installed and run `tensorflow==2.3.1` from PyPI.

Today I tried `tf-nightly`, which suddenly does not support my GPU. The error message implies that some CUDA 11 is missing, but now I am at a loss what to ask my server admin to install. Obviously, I have to install what the PyPI packages were compiled against.

- CUDA 11.0? 11.1? 2 possibilities.
- CuDNN 7.6? 8.0? For CUDA 10.1? 11.0? 11.1? 6 possibilities.
- TensorRT 6? 7.0? 7.1? 7.2? 4 possibilities.

I would like to be able to find this out without going through several (up to 50?) iterations with my server admin, and without having to ask to install *everything*.

I understand that maybe this information is not available yet for 2.4.0, but 

- it should be available for current `tf-nightly`, and
- it should *definitely* be available for `tensorflow==2.3.1` (it may be that this is what https://www.tensorflow.org/install/gpu has, but that wording is awkward: "TensorFlow supports" should probably be "TensorFlow requires", and I don't think TensorRT is optional: I remember having had to install it; also, the top says "See the pip install guide for available packages, *systems requirements*, and instructions", and then that page does not say anything about CUDA/CuDNN/etc., but instead refers back to the first page for CUDA),
- it should be available for older versions, too.

**Comment by jvishnuvardhan** [comment]
@bersbersbers In the most recent versions (`TF2.4`), CUDA package is listed. 
@mihaimaruseac Any plans of listing CuDNN, TensorRT versions? Thanks!

**Comment by bersbersbers** [comment]
Thanks! Also, release notes now say

> TensorFlow pip packages are now built with CUDA11.2 and cuDNN 8.1.0

https://github.com/tensorflow/tensorflow/releases/tag/v2.5.0-rc1

**Comment by bersbersbers** [comment]
This issue is not solved, unfortunately.

- v2.6 release notes don't mention any CUDA/CuDNN information at all:
https://github.com/tensorflow/tensorflow/releases/tag/v2.6.0

- of note, v2.5 relase notes lists "CUDA11.2 and cuDNN 8.1.0":
https://github.com/tensorflow/tensorflow/releases/tag/v2.5.0

- PyPI lists "GPU :: NVIDIA CUDA :: 11.2" for tf-nightly, but "GPU :: NVIDIA CUDA :: 11.0" for tensorflow:
https://pypi.org/project/tf-nightly/2.7.0.dev20210815/
https://pypi.org/project/tensorflow/2.6.0/

**Comment by jvishnuvardhan** [comment]
@bersbersbers Thanks for finding this issue. Please create a new issue so that we can track the progress. Ping me in that issue. Thanks!
