### ISSUE TITLE
"HOST_CFG" is not defined on bazel clean

### ISSUE THREAD

**Issue by kamal94** [tensorflow/tensorflow#4371]
During the ./configure step of my build from source, I encounter a bazel error when trying to download 

**The main error seems to be**
```

ERROR: /home/kamal/.cache/bazel/_bazel_kamal/f9ae4eca457b390bb2ebe780caca64e0/external/protobuf/protobuf.bzl:91:19: name 'HOST_CFG' is not defined.

``` 

Building with CUDA 8.0, cuDNN 5.1.5, GTX 1060

Full stack:

```
~/tensorflow ~/tensorflow
Please specify the location of python. [Default is /usr/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

/usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: /usr/local/cuda-8.0
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5.1.5
Please specify the location where cuDNN 5.1.5 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda-8.0]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 6.1
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
.
ERROR: /home/kamal/.cache/bazel/_bazel_kamal/f9ae4eca457b390bb2ebe780caca64e0/external/protobuf/protobuf.bzl:91:19: name 'HOST_CFG' is not defined.
ERROR: package contains errors: tensorflow/contrib/metrics.
ERROR: error loading package 'tensorflow/contrib/metrics': Extension 'protobuf.bzl' has errors.
Configuration finished
```

**Comment by xpe** [comment]
I'm getting a similar error:

```
$ ./configure
~/src/tensorflow ~/src/tensorflow
Please specify the location of python. [Default is /home/xpe/anaconda3/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Found possible Python library paths:
  /home/xpe/anaconda3/lib/python3.5/site-packages
Please input the desired Python library path to use.  Default is [/home/xpe/anaconda3/lib/python3.5/site-packages]

/home/xpe/anaconda3/lib/python3.5/site-packages
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 
Please specify the location where CUDA  toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 
Please specify the location where cuDNN  library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Invalid path to cuDNN  toolkit. Neither of the following two files can be found:
/usr/local/cuda-8.0/lib64/libcudnn.so
/usr/local/cuda-8.0/libcudnn.so

Please specify the Cudnn version you want to use. [Leave empty to use system default]:  
Please specify the location where cuDNN  library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 6.1
Extracting Bazel installation...
.
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
.
ERROR: /home/xpe/.cache/bazel/_bazel_xpe/641dfc594d651643762f515addd22118/external/protobuf/protobuf.bzl:91:19: name 'HOST_CFG' is not defined.
ERROR: package contains errors: tensorflow/tools/proto_text.
ERROR: error loading package 'tensorflow/tools/proto_text': Extension 'protobuf.bzl' has errors.
Configuration finished
```

**Comment by xpe** [comment]
I build bazel from source. @kamal94 I would expect that you did as well.

As an early guess, I think I may have built from master of bazel and it may have a few bugs. (For example, if you look at https://www.bazel.io/versions/master/docs/skylark/lib/globals.html, you'll see that HOST_CFG is not listed as a global, but it was before: https://webcache.googleusercontent.com/search?q=cache:0KuaX69EkvcJ:https://www.bazel.io/versions/master/docs/skylark/lib/globals.html+&cd=3&hl=en&ct=clnk&gl=us)

Here is what may be the source of the line 91 protobuf error:

https://github.com/bazelbuild/bazel/blob/8d9fc9aef82d82076cfea2db010a3036d871027e/third_party/protobuf/3.0.0/protobuf.bzl#L91

**Comment by xpe** [comment]
I see in the google-cache version of the docs I linked above that HOST_CFG got deprecated:

> ConfigurationTransition

>Deprecated. Use string "host" instead. Specifies a transition to the host configuration.

**Comment by xpe** [comment]
I made a PR for Bazel to change HOST_CFG to "host", here: https://github.com/bazelbuild/bazel/pull/1769

**Comment by andydavis1** [comment]
Closing this out as it appears resolved. Please re-open if the PR for Bazel mentioned by @xpe does not address this issue.

**Comment by kamal94** [comment]
@xpe I tried installing bazel from source from your repository and it still didn't work, same error. I think it might have something to do with bazel fetching protobuf from github.

However, this is really confusing because protobuf [fixed their cfg flags](https://github.com/google/protobuf/pull/2100), and they don't have any HOST_CFG in their code base anymore. So I don't see why bazel would get a version of protobuf.bzl that has HOST_CFG in it. Maybe it's not pulling from the most recent github version?

To make this clearer, look at the file where the error occurs, for me it is:
 /home/kamal/.cache/bazel/_bazel_kamal/f9ae4eca457b390bb2ebe780caca64e0/external/protobuf/protobuf.bzl
for you it seems to be (at least in your most recent posted error message):
/home/xpe/.cache/bazel/_bazel_xpe/641dfc594d651643762f515addd22118/external/protobuf/protobuf.bzl

This file contains the cfg = HOST_CFG, while the [protobuf.bzl](https://github.com/google/protobuf/blob/master/protobuf.bzl) in the head of protobuf contains "host"

Am i getting something wrong? Why isn't bazel downloading from master/head? if it says it's cloning it.

**Comment by ic** [comment]
@kamal94 @xpe I had the same problem as Kamal about 10 hours ago, even with a Bazel patch similar to @xpe's PR.

I have just pulled TF (02a8d07) and, with the Bazel patch, everything is fine now.

**Comment by kamal94** [comment]
@ic  I still couldn't get it to work. 
What i did:
1. git clone this repository 
2. git clone bazel
3. replace all "HOST_CFG" with "host" in the entire directory
4. ./compile the bazel directory
5.removed the old bazel binary from /usr/bin
6. copied the new bazel binary in output/ to /usr/bin

I still get the error, and bazel still attempts to clone the protobuf github repository and install from there. 

Am I missing something?

While compiling bazel, it seemed to also have compiled protobuf, but I don't see any other binary output in /output. Perhaps there are some binaries for protobuf that I could also copy to bin?

**Comment by ic** [comment]
> 3. replace all "HOST_CFG" with "host" in the entire directory
My changes are basically the same as the PR by @xpe. Have you changed anything else?

Perhaps need for a `bazel clean` before trying to recompile.

In the compilation log, protobuf` is also cloned and built from source here. Note I have succeeded on Darwin only---not tried yet on Linux.

Just to be sure: Do you use the exact same commits as the ones I suggested, both for Bazel and TensorFlow?

**Comment by kamal94** [comment]
@andydavis1 This is still an issue. Even the bazel fix didn't do it for me. For some reason, it is till cloning an old version of Bazel evertyime it runs ``` bazel fetch //...``` in the .config file.

it **should** be pulling [this file](https://github.com/google/protobuf/blob/master/protobuf.bzl) but it is not! It is pulling a similar (older) file with flag set to HOST_CFG.

Is there a way to change this so that bazel clones the most recent (and therefore non-deprecated) version of protobuf?

The only manual solution I could come up with was running the config file, and when bazel crashed because of the above error, i manually changed the file at the specified cache location (for me this was /home/*myname*/.cache/bazel/_bazel_kamal/f9ae4eca457b390bb2ebe780caca64e0/external/protobuf/protobuf.bzl) and replaced all occurrences of HOST_CFG to "host".

The installation runs well after that until I run into #4312

**Comment by xpe** [comment]
@kamal94 Thanks for your feedback and updates. I'm hopeful that László Csomor's changes move it in the right direction. I'll be doing another installation soon, also, and will keep an eye on it.

**Comment by kamal94** [comment]
@xpe I was able to trace the error.
It was in the [bazel workplace installation file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl#L101) and it pulled an older archive of protobuf. This old version had HOST_CFG instead of "host".

To fix this, I replaced the lines
```
native.http_archive(
    name = "protobuf",
    url = "http://github.com/google/protobuf/archive/v3.0.2.tar.gz",
    sha256 = "b700647e11556b643ccddffd1f41d8cb7704ed02090af54cc517d44d912d11c1",
    strip_prefix = "protobuf-3.0.2",
  )
```

with 

```
  native.git_repository(
      name = "protobuf",
      remote = "https://github.com/google/protobuf/",
      commit = "a289d43"
  )
```

**Comment by xpe** [comment]
@kamal94 Good find. 

My quick, general commentary: Looking at the file, it would appear that the convention is to pin specific versions for reproducibility. Keeping them up-to-date sounds like classic dependency management pain. I don't know bazel well, but I hope it would have tooling to automatically check for newer versions.

A recommendation, if possible: In this kind of situation, pointing to a particular artifact or git hash works. However, if possible, using a human-readable tag name with a version is probably more maintainable. Perhaps others more [learned](https://en.oxforddictionaries.com/usage/learnt-vs-learned) with bazel could weigh in.

**Comment by guotong1988** [comment]
same problem , thank you @kamal94

**Comment by eraoul** [comment]
I installed Bazel from the macOS installer 

`./bazel-0.5.2-installer-darwin-x86_64.sh --user`

and I have the same problem when trying to build something (a fork of the Magenta repo, in my case): 

`ERROR: /private/var/tmp/_bazel_epnichols/3e6515dd3746b8d7b7b2bef4294514b6/external/protobuf/protobuf.bzl:91:19: name 'HOST_CFG' is not defined.`

A bit more info:
```
bash bazel version

Build label: 0.5.2
Build target: bazel-out/darwin_x86_64-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 27 13:17:02 2017 (1498569422)
Build timestamp: 1498569422
Build timestamp as int: 1498569422
```

Is this actually broken in the prebuilt installer, or is it just me?
