### ISSUE TITLE
There is no way to build Cortex-M55

### ISSUE THREAD

**Issue by mansnils** [tensorflow/tensorflow#43725]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- Tensorflow version (commit SHA if source): 1f9328f3a4662085b2cb948b9ed2b03d7259f78b
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):

**Describe the problem**

**Please provide the exact sequence of commands/steps when you ran into the problem**
There is a need to build for generic Cortex-M devices. There has been some PRs in the right directions lately, e.g. this one, which has good debug support: https://github.com/tensorflow/tensorflow/pull/41860
But it does not support, e.g. Cortex-M55.

**Comment by ml-0** [comment]
Cortex-M55 support could easily be added to the generic Cortex-M Makefile. However, to my understanding the M55 is only supported by GCC version 10. TFLM currently downloads GCC version 7.
I spent some effort in compiling for M55 using the GCC 10 preview without success. Best result I got with

    -mcpu=cortex-m55 \
    -mfpu=auto \
    -mfloat-abi=hard

where it compiles a couple of files and then terminates
Error: instruction not allowed in IT block -- `vmullt.f32 s15,s15,s14'
when compiling
./tensorflow/lite/micro/kernels/comparisons.cc

Anyone who could help?

**Comment by mansnils** [comment]
GCC support for Cortex-M55 is perhaps a bit experimental still but there is a PR for this issue: https://github.com/tensorflow/tensorflow/pull/43726

**Comment by mansnils** [comment]
@ml-0 How about we merge your PR with the new PR, basically replace cortex_m_gcc_generic_makefile.inc with cortex_m_generic_makefile.inc? 
We have a need to build other Cortex-M, other than Cortex-M4 and Cortex-M55 and with both Armclang and GCC as well.

**Comment by ml-0** [comment]
I am open to add other Cortex-M targets based on the gcc toolchain. Adding other toolchains to the same Makefile (and renaming it accordingly) is ok, too, as long as it integrates well and doesn't make its use too complicated. My concerns are:
- armcc/armclang are proprietary and will not be downloadable by an entry in third_party_downloads.inc.
- armcc/armclang require a license to operate
- armcc/armclang require different CFLAGS/CXXFLAGS

I am not sure how this translates into a makefile. @mansnils Can you make a suggestion?

@advaitjain you will probably have the final speak on this.

**Comment by mansnils** [comment]
That sounds good. Idea is that it should support both GCC and Armclang so anyone without a license can always use GCC. I am working at Arm and we are working on getting a License for TFLM CI. I propose that I update the PR (https://github.com/tensorflow/tensorflow/pull/43726) to reflect this.

**Comment by advaitjain** [comment]
Having a single cortex_m_generic_makefile.inc sounds good to me.

I would propose that we continue to use the callback registration that @ml-0 has implemented:
https://github.com/tensorflow/tensorflow/blob/d7bb5785ced563f113bdbbb3e7ecb1d5f06e187f/tensorflow/lite/micro/cortex_m_gcc_generic/debug_log_callback.h#L18-L33

@mansnils if you could update PR #43726 then I can take a look.

**Comment by ml-0** [comment]
@mansnils can you comment why TFLM does not compile for M55 with GCC 10.1.1 toolchain? Is it a problem located in TFLM or on the GCC side?

**Comment by avieira-arm** [comment]
Hi,

This is an issue with the GNU assembler that has been fixed with https://sourceware.org/pipermail/binutils/2020-April/110799.html

This fix should be picked up by the December major release of the GNU Arm Embedded toolchain, which will be made available at: https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm

Hope that helps.

**Comment by felix-johnny** [comment]
@ml-0 Till then, you can use [Arm Compiler](https://developer.arm.com/tools-and-software/embedded/arm-compiler/downloads/version-6) 6.14 and upwards.
