### ISSUE TITLE
How it is done convolution calculation order in conv2d?

### ISSUE THREAD

**Issue by hrktngc** [tensorflow/tensorflow#43724]
I'm worried about cancellation of significant digits by convolution calculation order in conv2d.
I tried coding on my own on Python(using tf.math.add etc.), could not be reproduced Tensorflow API conv2d output.
Do you know detailed internal processing or original source code in API conv2d?

Development environment:
    Python 3.6
    TensorFlow 2.1.0
    JupyterNotebook

**Comment by Saduf2019** [comment]
@hrktngc 
We see that you have not filled in the issue template, please share with simple indented stand alone code to replicate the issue faced or if possible share a colab gist with the issue reported.
Can you try on tf nightly and see if the issue exist.
