### ISSUE TITLE
compatibility issue with cuda 11.1

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#43720]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): N/A
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.0 master
- Python version: 3.8.6
- Bazel version (if compiling from source): 3.5.1
- GCC/Compiler version (if compiling from source):  visual studio 2019
- CUDA/cuDNN version: 11.1/ 8.0.4
- GPU model and memory: RTX2070 super 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
cudart library not loaded
**Describe the expected behavior**
cudart dll should be loaded properly
**Standalone code to reproduce the issue**
```
python
import tensorflow as tf
```
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

cudart64 library name for cuda 11.1 is cudart64_110.dll,  not cudart64_111.dll

**Comment by alanpurple** [comment]
also emit error in ubuntu

**Comment by Saduf2019** [comment]
@alanpurple 
Please share complete error log for us to analyse, also could you try with cuda 11.0 and not cuda 11.1 and let us know.Thank!

**Comment by sanjoy** [comment]
@nluehr has a fix for this which should land soon.

**Comment by alanpurple** [comment]
@sanjoy 
thank you

**Comment by geeheim** [comment]
Did the fix already land? Where can I find it?
Regards Geert

**Comment by nluehr** [comment]
@geeheim It landed in the master branch on Oct 7th. https://github.com/tensorflow/tensorflow/commit/68a6fe0d984377b625b421d34f8c607d6ed73597
