### ISSUE TITLE
'@grpc//:gpr_base' failed (Exit 1)

### ISSUE THREAD

**Issue by Int37** [tensorflow/tensorflow#43734]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): linux ubuntu 20.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14 and 1.13
- Python version: 3.8
- Installed using virtualenv? pip? conda?: pip 
- Bazel version (if compiling from source): 0.24.1 
- GCC/Compiler version (if compiling from source): gcc-4.8.5 for bazel and gcc-8 for cuda libary
- CUDA/cuDNN version: 10.1 / 7
- GPU model and memory: 1070 ti 8gb

**Describe the problem**
I can't compile from tensorflow 1.14-1.13 source code (haven't tried other 1 tensorflow branches) and 2.4 has been successfully compiled with and without GPU. Originally the error was with newer versions of basel and gcc-8, but after reading the https://www.tensorflow.org/install/source table, I installed gcc-4.8, but the error persisted.

I have read the solutions
https://github.com/tensorflow/serving/issues/928 but adding the --cxxopt = -std = c ++ 11 flag didn't work for me
I also read that installing libc-ares-dev library might help, but that didn't help either

I thought the problem might be related to the fact that I am using cuda-10.1 and not 10.0 as in the table. I tried to set up the file without cuda, but I got exactly the same error, so I think this is not the problem
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**writte config file**
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.24.1 installed.
Please specify the location of python. [Default is /usr/bin/python3]: 

Found possible Python library paths:
  /usr/local/lib/python3.8/dist-packages
  /usr/lib/python3/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python3.8/dist-packages]

Do you wish to build TensorFlow with XLA JIT support? [Y/n]: n
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: n
No TensorRT support will be enabled for TensorFlow.

Found CUDA 10.1 in:
    /usr/local/cuda/lib64
    /usr/local/cuda/include
Found cuDNN 7 in:
    /usr/lib/x86_64-linux-gnu
    /usr/include

Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 6.1]: 

Do you want to use clang as CUDA compiler? [y/N]: n
nvcc will be used as CUDA compiler.

Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: /usr/bin/gcc-8

Do you wish to build TensorFlow with MPI support? [y/N]: n
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: -march=native -mno-avx

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=gdr            # Build with GDR support.
        --config=verbs          # Build with libverbs support.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=noignite       # Disable Apache Ignite support.
        --config=nokafka        # Disable Apache Kafka support.
        --config=nonccl         # Disable NVIDIA NCCL support.
Configuration finished

**build command**
bazel build --cxxopt=-std=c++11 --config=cuda  //tensorflow/tools/pip_package:build_pip_package

**output error**
INFO: From ProtoCompile external/com_github_googleapis_googleapis/google/api/http.pb.h:
bazel-out/k8-opt/genfiles/external/protobuf_archive/src: warning: directory does not exist.
INFO: From ProtoCompile external/com_github_googleapis_googleapis/google/rpc/status.pb.h:
bazel-out/k8-opt/genfiles/external/protobuf_archive/src: warning: directory does not exist.
INFO: From Compiling external/mkl_dnn/src/cpu/simple_concat.cpp:
external/mkl_dnn/src/cpu/simple_concat.cpp:98: warning: ignoring #pragma omp simd [-Wunknown-pragmas]
             PRAGMA_OMP_SIMD()
 
INFO: From Compiling external/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.cc:
external/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.cc: In function 'grpc_error* try_http_parsing(grpc_chttp2_transport*)':
external/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.cc:2466:40: warning: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'grpc_http_response' {aka 'struct grpc_http_response'}; use assignment or value-initialization instead [-Wclass-memaccess]
   memset(&response, 0, sizeof(response));
                                        ^
In file included from external/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.cc:44:
external/grpc/src/core/lib/http/parser.h:71:16: note: 'grpc_http_response' {aka 'struct grpc_http_response'} declared here
 typedef struct grpc_http_response {
                ^~~~~~~~~~~~~~~~~~
ERROR: /home/dmitry/.cache/bazel/_bazel_dmitry/1319b3f3ad6252a51422db144992f79d/external/grpc/BUILD:507:1: C++ compilation of rule '@grpc//:gpr_base' failed (Exit 1)
external/grpc/src/core/lib/gpr/log_linux.cc:43:13: error: ambiguating new declaration of 'long int gettid()'
 static long gettid(void) { return syscall(__NR_gettid); }
             ^~~~~~
In file included from /usr/include/unistd.h:1170,
                 from external/grpc/src/core/lib/gpr/log_linux.cc:41:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: old declaration '__pid_t gettid()'
 extern __pid_t gettid (void) __THROW;
                ^~~~~~
external/grpc/src/core/lib/gpr/log_linux.cc:43:13: warning: 'long int gettid()' defined but not used [-Wunused-function]
 static long gettid(void) { return syscall(__NR_gettid); }
             ^~~~~~
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 281.090s, Critical Path: 57.54s
INFO: 1539 processes: 1539 local.
FAILED: Build did NOT complete successfully

(there was even more INFO output, but I did not copy everything, there really is a lot)

**Comment by amahendrakar** [comment]
@Int37,
Is there any specific reason you are using TensorFlow 1.x? TensorFlow 1.x is not actively supported, could you please update TensorFlow to v2.3? 

Also, please go through similar issues [#34291](https://github.com/tensorflow/tensorflow/issues/34291#issuecomment-624767789
) and [#33758](https://github.com/tensorflow/tensorflow/issues/33758#issuecomment-547143723) and let us know if it helps. Thanks!

**Comment by Int37** [comment]
@amahendrakar I need tf.contrib elements to use the code: https://github.com/vlomme/Multi-Tacotron-Voice-Cloning, also most github projects still require version 1.14 or less. I could just download via pip, but my processor does not support avx instructions, without which tensorflow does not work even on gpu. i did what is written here  https://github.com/tensorflow/tensorflow/issues/33758#issuecomment-547143723 I  , it gave the same error, but in a different place, after a while
**output bazel**
   ^~~~~
INFO: From Compiling tensorflow/cc/training/queue_runner.cc:
In file included from ./tensorflow/core/platform/default/logging.h:24,
                 from ./tensorflow/core/platform/logging.h:25,
                 from ./tensorflow/core/lib/core/status.h:25,
                 from ./tensorflow/cc/training/coordinator.h:26,
                 from ./tensorflow/cc/training/queue_runner.h:24,
                 from tensorflow/cc/training/queue_runner.cc:16:
./tensorflow/core/util/tensor_format.h: In instantiation of 'T tensorflow::GetFilterDim(tensorflow::gtl::ArraySlice<T>, tensorflow::FilterTensorFormat, char) [with T = long long int; tensorflow::gtl::ArraySlice<T> = absl::Span<const long long int>]':
./tensorflow/core/util/tensor_format.h:470:54:   required from here
./tensorflow/core/util/tensor_format.h:444:29: warning: comparison of integer expressions of different signedness: 'int' and 'absl::Span<const long long int>::size_type' {aka 'long unsigned int'} [-Wsign-compare]
   CHECK(index >= 0 && index < dimension_attribute.size())
./tensorflow/core/platform/macros.h:87:47: note: in definition of macro 'TF_PREDICT_FALSE'
 #define TF_PREDICT_FALSE(x) (__builtin_expect(x, 0))
                                               ^
./tensorflow/core/util/tensor_format.h:444:3: note: in expansion of macro 'CHECK'
   CHECK(index >= 0 && index < dimension_attribute.size())
   ^~~~~
INFO: From Compiling tensorflow/core/kernels/nth_element_op.cc:
In file included from ./tensorflow/core/framework/register_types.h:22,
                 from tensorflow/core/kernels/nth_element_op.cc:23:
./tensorflow/core/framework/variant.h: In member function 'void tensorflow::Variant::HeapOrInline::ResetMemory()':
./tensorflow/core/framework/variant.h:653:45: warning: 'void* memset(void*, int, size_t)' clearing an object of type 'union tensorflow::Variant::HeapOrInline' with no trivial copy-assignment; use value-initialization instead [-Wclass-memaccess]
       this, 0, sizeof(Variant::HeapOrInline));
                                             ^
./tensorflow/core/framework/variant.h:496:9: note: 'union tensorflow::Variant::HeapOrInline' declared here
   union HeapOrInline {
         ^~~~~~~~~~~~
INFO: From Compiling tensorflow/core/grappler/clusters/virtual_cluster.cc:
In file included from ./tensorflow/core/platform/default/logging.h:24,
                 from ./tensorflow/core/platform/logging.h:25,
                 from ./tensorflow/core/framework/allocator.h:28,
                 from ./tensorflow/core/common_runtime/device.h:35,
                 from ./tensorflow/core/common_runtime/device_set.h:23,
                 from ./tensorflow/core/grappler/clusters/virtual_cluster.h:21,
                 from tensorflow/core/grappler/clusters/virtual_cluster.cc:16:
./tensorflow/core/util/tensor_format.h: In instantiation of 'T tensorflow::GetFilterDim(tensorflow::gtl::ArraySlice<T>, tensorflow::FilterTensorFormat, char) [with T = long long int; tensorflow::gtl::ArraySlice<T> = absl::Span<const long long int>]':
./tensorflow/core/util/tensor_format.h:470:54:   required from here
./tensorflow/core/util/tensor_format.h:444:29: warning: comparison of integer expressions of different signedness: 'int' and 'absl::Span<const long long int>::size_type' {aka 'long unsigned int'} [-Wsign-compare]
   CHECK(index >= 0 && index < dimension_attribute.size())
./tensorflow/core/platform/macros.h:87:47: note: in definition of macro 'TF_PREDICT_FALSE'
 #define TF_PREDICT_FALSE(x) (__builtin_expect(x, 0))
                                               ^
./tensorflow/core/util/tensor_format.h:444:3: note: in expansion of macro 'CHECK'
   CHECK(index >= 0 && index < dimension_attribute.size())
   ^~~~~
ERROR: /home/dmitry/.cache/bazel/_bazel_dmitry/1319b3f3ad6252a51422db144992f79d/external/grpc/BUILD:507:1: C++ compilation of rule '@grpc//:gpr_base' failed (Exit 1)
external/grpc/src/core/lib/gpr/log_linux.cc:43:13: error: ambiguating new declaration of 'long int gettid()'
 static long gettid(void) { return syscall(__NR_gettid); }
             ^~~~~~
In file included from /usr/include/unistd.h:1170,
                 from external/grpc/src/core/lib/gpr/log_linux.cc:41:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: old declaration '__pid_t gettid()'
 extern __pid_t gettid (void) __THROW;
                ^~~~~~
external/grpc/src/core/lib/gpr/log_linux.cc:43:13: warning: 'long int gettid()' defined but not used [-Wunused-function]
 static long gettid(void) { return syscall(__NR_gettid); }
             ^~~~~~
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2558.765s, Critical Path: 296.59s
INFO: 2613 processes: 2613 local.
FAILED: Build did NOT complete successfully

**Comment by amahendrakar** [comment]
> /usr/local/lib/python3.8/dist-packages

@Int37,
Looks like you are using Python 3.8. As per the [tested build configurations](https://www.tensorflow.org/install/source#gpu), TensorFlow 1.x is compatible with Python 3.3 - 3.7, please take a look at the below table for reference.  



Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow_gpu-1.15.0 | 2.7, 3.3-3.7 | GCC 7.3.1 | Bazel 0.26.1 | 7.4 | 10.0
tensorflow_gpu-1.14.0 | 2.7, 3.3-3.7 | GCC 4.8 | Bazel 0.24.1 | 7.4 | 10.0
tensorflow_gpu-1.13.1 | 2.7, 3.3-3.7 | GCC 4.8 | Bazel 0.19.2 | 7.4 | 10.0

Could you please check if you are facing the same issue with Python 3.7 as well? Thanks!
