### ISSUE TITLE
CUDA 10.1

### ISSUE THREAD

**Issue by geeheim** [tensorflow/tensorflow#43733]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Linux CentOS 7.8
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n.a.
- TensorFlow installed from (source or binary): source
- TensorFlow version: v2.3.1
- Python version:3.6
- Installed using virtualenv? pip? conda?: n.a.
- Bazel version (if compiling from source): 3.1.0 (bazelisk)
- GCC/Compiler version (if compiling from source):7.3.1
- CUDA/cuDNN version:10.1/7.6
- GPU model and memory:n.a.

**Describe the problem**
Compilation error when compiling tensorflow 2.3.1. with CUDA 10.1:

ERROR: /build/tensorflow/tensorflow/stream_executor/cuda/BUILD:457:1: C++ compilation of rule '//tensorflow/stream_executor/cuda:cusparse_stub' failed (Exit 1)
In file included from tensorflow/stream_executor/cuda/cusparse_stub.cc:59:0:

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Tried to follow the build instructions from source with the recommend/tested configuration:
https://www.tensorflow.org/install/source#tested_build_configurations

Here is my configure log:
[configure.txt](https://github.com/tensorflow/tensorflow/files/5318180/configure.txt)

Here is a minimal build command to reproduce the issue:
BAZEL_LINKLIBS=-l%:libstdc++.a bazel build --config=nohdfs --config=noaws --config=nogcp --config=nonccl  --config=monolithic --config=cuda --config=v2 --config=opt  //tensorflow/stream_executor/cuda:cusparse_stub

Note: I had to add BAZEL_LINKLIBS=-l%:libstdc++.a for CentOS, see 
https://github.com/tensorflow/tensorflow/issues/35867

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

As you can see in the build log, the error occurs in tensorflow/stream_executor/cuda/cusparse_stub.cc:59:0. I assume this is because of wrong version of tensorflow/stream_executor/cuda/cusparse_10_1.inc.
The file is identical to cusparse_10_2.inc and it works with CUDA 10.2

[build.txt](https://github.com/tensorflow/tensorflow/files/5318181/build.txt)

**Comment by Saduf2019** [comment]
@geeheim 
Please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/43720#issuecomment-703869823) and let us know if it helps.
