### ISSUE TITLE
Evaluation produces OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by thephet** [tensorflow/tensorflow#43738]
I have a dataset of around 40,000 images. I load them into memory using opencv and I put them in a long python list. Then I use a TimeseriesGenerator, like this:

``
generator = TimeseriesGenerator(allframes, allframes, length=75, sampling_rate=5, stride=2, batch_size=8)
``

Where allframes is just a python list where each entry is an image as loaded with opencv.

I then have a custom generator:
```
def customGenerator(generator, indexes):

    while True:
        np.random.shuffle(indexes)
        for i in indexes:
            x,y = generator[i]
            yield (x, y)
```

and then my train function, im removing some non important lines:
```
def trainRNNmodel(model, generator):

    randomize = np.arange( len(generator) - 1 )
    np.random.shuffle(randomize)
    trainLimit = int( 0.9*len(randomize) )
    valsteps = int( 0.1*len(randomize) ) 

    workers = int(multiprocessing.cpu_count()/2)

    model.fit( x= customGenerator(generator, randomize[:trainLimit]), y=None, 
            validation_data = customGenerator(generator, randomize[trainLimit:]), 
            epochs=1000, steps_per_epoch=trainLimit, validation_steps=valsteps,
            use_multiprocessing = False, callbacks=callbacks_list)
```

it works ok, but around epoch 50 I get the same error 24 as the user says. and this happens during validation too.

I can increase ulimit but this only delays the error.

No idea why is it happening because I reckon it's not loading any files during training.

**Comment by Saduf2019** [comment]
@thephet 
Please share complete stand alone indented code and data-set for us to replicate the issue.
