### ISSUE TITLE
Cannot import tensorflow

### ISSUE THREAD

**Issue by DJJD17** [tensorflow/tensorflow#43747]
First time post on github.  trying to import tensorflow on local machine.  keep getting a runtime error.  please advise.

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): pip install tensorflow on miniconda3
- TensorFlow version (use command below): 2.2.0
- Python version: 3.8.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cudnn-11.0-windows-x64-v8.0.3.33.zip   cuDNN8.0.4
- GPU model and memory: NVIDIA Quadro K1100M.  This has compute capability 3.0 which is less than the minimum required... see https://www.tensorflow.org/install/gpu#hardware_requirements 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

tensorflow is not imported.  instead i get a runtime warning... see warning below in Other info / logs

**Describe the expected behavior**

**Standalone code to reproduce the issue**

import tensorflow as tf

**Other info / logs** 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\miniconda3\envs\quant\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59 

~\miniconda3\envs\quant\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

~\miniconda3\envs\quant\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

~\miniconda3\envs\quant\lib\imp.py in load_module(name, file, filename, details)
    241         else:
--> 242             return load_dynamic(name, filename, file)
    243     elif type_ == PKG_DIRECTORY:

~\miniconda3\envs\quant\lib\imp.py in load_dynamic(name, path, file)
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343 

ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-43-64156d691fe5> in <module>
----> 1 import tensorflow as tf

~\miniconda3\envs\quant\lib\site-packages\tensorflow\__init__.py in <module>
     39 import sys as _sys
     40 
---> 41 from tensorflow.python.tools import module_util as _module_util
     42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
     43 

~\miniconda3\envs\quant\lib\site-packages\tensorflow\python\__init__.py in <module>
     48 import numpy as np
     49 
---> 50 from tensorflow.python import pywrap_tensorflow
     51 
     52 # Protocol buffers

~\miniconda3\envs\quant\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     67 for some common reasons and solutions.  Include the entire stack trace
     68 above this error message when asking for help.""" % traceback.format_exc()
---> 69   raise ImportError(msg)
     70 
     71 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\Users\Jeff\miniconda3\envs\quant\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Jeff\miniconda3\envs\quant\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Jeff\miniconda3\envs\quant\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\Jeff\miniconda3\envs\quant\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\Jeff\miniconda3\envs\quant\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by DJJD17** [comment]
> First time post on github. trying to import tensorflow on local machine. keep getting a runtime error. please advise.
> 
> **System information**
> 
> * Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
> * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
> * TensorFlow installed from (source or binary): pip install tensorflow on miniconda3
> * TensorFlow version (use command below): 2.2.0
> * Python version: 3.8.5
> * Bazel version (if compiling from source):
> * GCC/Compiler version (if compiling from source):
> * CUDA/cuDNN version: cudnn-11.0-windows-x64-v8.0.3.33.zip   cuDNN8.0.4
> * GPU model and memory: NVIDIA Quadro K1100M.  This has compute capability 3.0 which is less than the minimum required... see https://www.tensorflow.org/install/gpu#hardware_requirements
> 
> You can collect some of this information using our environment capture
> [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
> You can also obtain the TensorFlow version with:
> 
> 1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
> 2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
> 
> **Describe the current behavior**
> 
> tensorflow is not imported. instead i get a runtime warning... see warning below in Other info / logs
> 
> **Describe the expected behavior**
> 
> **Standalone code to reproduce the issue**
> 
> import tensorflow as tf
> 
> ## **Other info / logs**
> ImportError Traceback (most recent call last)
> ~\miniconda3\envs\quant\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in
> 57
> ---> 58 from tensorflow.python.pywrap_tensorflow_internal import *
> 59
> 
> ~\miniconda3\envs\quant\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in
> 27 return _mod
> ---> 28 _pywrap_tensorflow_internal = swig_import_helper()
> 29 del swig_import_helper
> 
> ~\miniconda3\envs\quant\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
> 23 try:
> ---> 24 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
> 25 finally:
> 
> ~\miniconda3\envs\quant\lib\imp.py in load_module(name, file, filename, details)
> 241 else:
> --> 242 return load_dynamic(name, filename, file)
> 243 elif type_ == PKG_DIRECTORY:
> 
> ~\miniconda3\envs\quant\lib\imp.py in load_dynamic(name, path, file)
> 341 name=name, loader=loader, origin=path)
> --> 342 return _load(spec)
> 343
> 
> ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.
> 
> During handling of the above exception, another exception occurred:
> 
> ImportError Traceback (most recent call last)
> in
> ----> 1 import tensorflow as tf
> 
> ~\miniconda3\envs\quant\lib\site-packages\tensorflow__init__.py in
> 39 import sys as _sys
> 40
> ---> 41 from tensorflow.python.tools import module_util as _module_util
> 42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
> 43
> 
> ~\miniconda3\envs\quant\lib\site-packages\tensorflow\python__init__.py in
> 48 import numpy as np
> 49
> ---> 50 from tensorflow.python import pywrap_tensorflow
> 51
> 52 # Protocol buffers
> 
> ~\miniconda3\envs\quant\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in
> 67 for some common reasons and solutions. Include the entire stack trace
> 68 above this error message when asking for help.""" % traceback.format_exc()
> ---> 69 raise ImportError(msg)
> 70
> 71 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long
> 
> ImportError: Traceback (most recent call last):
> File "C:\Users\Jeff\miniconda3\envs\quant\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in
> from tensorflow.python.pywrap_tensorflow_internal import *
> File "C:\Users\Jeff\miniconda3\envs\quant\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in
> _pywrap_tensorflow_internal = swig_import_helper()
> File "C:\Users\Jeff\miniconda3\envs\quant\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
> _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
> File "C:\Users\Jeff\miniconda3\envs\quant\lib\imp.py", line 242, in load_module
> return load_dynamic(name, filename, file)
> File "C:\Users\Jeff\miniconda3\envs\quant\lib\imp.py", line 342, in load_dynamic
> return _load(spec)
> ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/errors
> 
> for some common reasons and solutions. Include the entire stack trace
> above this error message when asking for help.

**Comment by ravikyram** [comment]
@DJJD17 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download [the latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.Thanks!
