### ISSUE TITLE
Memory blowup converting from TFLite to C

### ISSUE THREAD

**Issue by Rakeshpavan333** [tensorflow/tensorflow#43749]
I am observig a blowup of around 6-7x in memory size when converting a model from tflite flatBuffer to C source. 

For easier reproducibility, I am reporting with the TFLite models obtained from the MNIST tutorial [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/performance/post_training_integer_quant.ipynb)

I use the following method for converting from tflite model to C source:

`

	from tensorflow.lite.python.util import convert_bytes_to_c_source
	
	def convert_to_c(tflite_model,file_name):
	
	    source_text, header_text = convert_bytes_to_c_source(tflite_model,  file_name)
	
	    with  open(file_name + '.h',  'w')  as  file:
	
	        file.write(header_text)
	
	    with  open(file_name + '.cc',  'w')  as  file:
	
	        file.write(source_text)
 `
 
Here is a summary of the sizes before ('.tflite' file) and after converting to C source ('.cc' file):
1. Integer-only quantized model: before - 24.7 KB, after - 156.6 KB, blowup ~ 6.340x
2. Float fallback quantized model: before - 24.6 KB, after - 156.1 KB, blowup ~ 6.346x 
3. Dynamic range quantized model: before - 23.8 KB, after - 151.1 KB, blowup ~ 6.349x
4. Normal model: before - 84.5 KB, after - 533.4 KB, blowup ~ 6.312x
   
This blowup seems independent of the model architecture and parameters because I have tested with few other models and observed a similar trend there as well. 

I wanted to know what is possibly causing this blowup in memory size. In case of a small model (with initial flatbuffer size in kB) it is not a big issue, but for bigger models (with initial flatbuffer size in the order of MB) the final C source size is quite large and often exceeds the flash memory size of micro-controllers.

**Comment by yair-ehrenwald** [comment]
Try compiling the .cc file, I think you'll find the object file is pretty similar to the tfilte one.

**Comment by Saduf2019** [comment]
@Rakeshpavan333 
Can you please let us know the tf version on which the issue is faced as you have not filled the issue template.

**Comment by Saduf2019** [comment]
@Rakeshpavan333 
Please update the tf version on which the issue is faced as you have not filled the issue template.

**Comment by Rakeshpavan333** [comment]
@Saduf2019  
Apologies, I didn't mention the TF version, as the tutorial I shared above ( [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/performance/post_training_integer_quant.ipynb) ) is using TF 2.3.0. So I am using the same. (the code in the first cell automatically asserts tf version >= 2.3 )

@yair-ehrenwald  
The documentation for TFLite [here](https://www.tensorflow.org/lite/microcontrollers) specified in the 'Workflow' section to convert to C byte array and store it in the read-only memory of the micro-controller. Also, most of the microcontroller IDEs available don't compile if the size exceeds the micro-controller flash. 

For now, I am more interested in learning the cause for this size blowup (instead of fixing/hacking it). I also tried using MicroTensor ( [uTensor](https://utensor.github.io/website/) ) library, which actually makes use of TFLite in the backend. The blowup in this case is around 4.5X, which is slightly less than the 6X blowup using the TFLite  `convert_bytes_to_c_source` method. So, probably, the reason lies partly in the `convert_bytes_to_c_source` method, and partly in how the model information is represented in flatbuffers implementation.

**Comment by Saduf2019** [comment]
@Rakeshpavan333 
Please share a colab gist with the issue reported for us to analyse.

**Comment by Rakeshpavan333** [comment]
Hi, 
Here is the colab link: 
https://colab.research.google.com/drive/1DAMoBlLijzRorc7HSwOOYDUZPm0ZBQ83?usp=sharing

**Comment by Saduf2019** [comment]
@Rakeshpavan333 
Please confirm if the [gist here](https://colab.research.google.com/gist/Saduf2019/6f686504cca6be37ec050184b6df225e/untitled431.ipynb) replicates the issue reported.

**Comment by Rakeshpavan333** [comment]
Hi, I think I've understood why the source file size is larger. Each hex value would take around 5-6 characters to write in the source. Hence the source would be around 6x larger. So this is not any performance issue.

 The final compiled executable can be smaller depending on the deployment pipeline and IDE used. 

I will close the issue. Thank you for the help.
