### ISSUE TITLE
person_detection benchmarks do not build for STM32F4

### ISSUE THREAD

**Issue by advaitjain** [tensorflow/tensorflow#43743]
@tensorflow/micro

**System information**
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): #43509 
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): STM32F4

After #43509 is merged, remove the exclusion for the person_detection and person_deteciton_experimental benchmarks and then:

```
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=stm32f4 TAGS=cmsis-nn person_detection_benchmark
```
will give the following error:
```
/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: tensorflow/lite/micro/tools/make/gen/stm32f4_cortex-m4/bin/person_detection_benchmark section `.rodata' will not fit in region `FLASH'
/home/advaitjain/github/tensorflow/tensorflow/lite/micro/tools/make/downloads/gcc_embedded/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: tensorflow/lite/micro/tools/make/gen/stm32f4_cortex-m4/bin/person_detection_benchmark section `.bss' will not fit in region `RAM'
/home/advaitjain/github/tensorflow/tensorflow/lite/micro/tools/make/downloads/gcc_embedded/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: region `RAM' overflowed by 72568 bytes
/home/advaitjain/github/tensorflow/tensorflow/lite/micro/tools/make/downloads/gcc_embedded/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: region `FLASH' overflowed by 158376 bytes
collect2: error: ld returned 1 exit status
make: *** [tensorflow/lite/micro/benchmarks/Makefile.inc:31: tensorflow/lite/micro/tools/make/gen/stm32f4_cortex-m4/bin/person_detection_benchmark] Error 1
```

The easy fix is to increase the numbers here https://github.com/tensorflow/tensorflow/blob/27d26a8d86bceda282ad9ba3e3116a00759d4ebc/tensorflow/lite/micro/tools/make/targets/stm32f4/stm32f4.lds#L34-L37 but will let the CMSIS-NN team weigh in on this.

**Comment by advaitjain** [comment]
@mansnils @freddan80  what do you think?

**Comment by freddan80** [comment]
@advaitjain sounds like a good idea. I think the numbers were derived from the Bluepill target originally. The STM32M4 seem to support a wide range of memory configs: https://www.st.com/en/microcontrollers-microprocessors/stm32f4-series.html

**Comment by freddan80** [comment]
I think the .ld should map the settings here:
https://github.com/renode/renode/blob/master/platforms/cpus/stm32f4.repl

**Comment by freddan80** [comment]
@mansnils can look at this next week. I think the only change needed is:

```
MEMORY { 
 RAM (xrw) : ORIGIN = 0x20000000, LENGTH = 256K 
 FLASH (rx) : ORIGIN = 0x8000000, LENGTH =  2048K
 } 

```
And perhaps remove the outdated comments in the top of the file:

```
/* Copied and modified from: tensorflow/lite/micro/tools/make/targets/bluepill/bluepill.lds

*/

/*
 * 0x00000000 - 0x07ffffff - aliased to flash or sys memory depending on BOOT jumpers.
 * 0x08000000 - 0x0801ffff - Flash.
 * 0x1ffff000 - 0x1ffff7ff - Boot firmware in system memory.
 * 0x1ffff800 - 0x1fffffff - Option bytes.
 * 0x20000000 - 0x20004fff - SRAM.
 * 0x40000000 - 0x40023400 - Peripherals
 */
```

@advaitjain let us know if you prefer us to fix this.

**Comment by advaitjain** [comment]
yes, a PR from you guys would be excellent.
