### ISSUE TITLE
Variable and Slow InfeedEnqueueTuple on TPUv3-8

### ISSUE THREAD

**Issue by mkuchnik** [tensorflow/tensorflow#43744]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): GCP VM with tf-version nightly
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): nightly
- Python version: 3.7
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: TPUv3-8

**Describe the current behavior**
[InfeedEnqueueTuple](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/tpu/kernels/infeed_ops.h) has variable performance and 33% slowdown. Infeed cannot keep TPUv3-8 saturated even with heavy caching due to stragglers in infeed operator. All input processing time is reported spent in "while/body/_1/InfeedQueue/enqueue/*".
I am attaching profiler results with infeed greater than 45ms. Note that each thread has variable time per Enqueue.
![slow_step](https://user-images.githubusercontent.com/12423239/94967869-ee6f2400-04cd-11eb-8c1c-e0a1c2df1a5e.png)
![infeed_slow](https://user-images.githubusercontent.com/12423239/94967461-232eab80-04cd-11eb-8e30-c291098dff33.png)

**Describe the expected behavior**
InfeedEnqueueTuple has consistent and fast performance (less than 45ms per step). I sometimes am able to observe periods of fast operation, where each infeed is consistently 45ms (image attached). However, infeed eventually regresses to ~60ms per step, as above.
![infeed_fast](https://user-images.githubusercontent.com/12423239/94967617-6be66480-04cd-11eb-828f-035298cd4fb0.png)

**Standalone code to reproduce the issue**
I am using MLPerfv0.7 ResNet [code](https://github.com/mlperf/training_results_v0.7/tree/master/Google/benchmarks/resnet/implementations/resnet-research-TF-tpu-v4-16) with ResNet-18. Issue persists even if dataset cache() (e.g., take(1).cache().repeat()) is placed right before prefetch().

**Comment by mkuchnik** [comment]
Same issue with [tpu repository](https://github.com/tensorflow/tpu/tree/master/models/official/resnet)

**Comment by rxsang** [comment]
Hi Micheal,

Thanks for reporting. When you mention "infeed eventually regresses to ~60ms per step, as above.", is the 60ms consistent and never reduces later? Have you tried if the issue is reproducible on fake data?

**Comment by mkuchnik** [comment]
Hi @rxsang,
The issue persists and the 60ms delays are the normal behavior. I have been unable to get 45ms consistently---it's something that appears at the beginning of training epochs. It might have to do with infeed queueing and the possibility that the queue can get prefetched in during eval time or the start of training (e.g., initialization code), giving an appearance of no bottleneck while the queue is draining.

You can reduce the infeed delay by lowering the resolution of the input size e.g., reduce from 224x224 to 112x112 (this reduces the infeed volume), though I still see jitter in the new step time (which is overall reduced by a factor of ~2-3x due to lower image resolution).

For fake data: in short, yes it should be easily reproducible. I believe you can just run the tpu repository with the flags `python3 resnet_main.py --tpu=$TPU_NAME --resnet_depth=18 --use_cache=False --model_dir=$MODEL_DIR`. You will also need to add `dataset = dataset.take(1).cache().repeat()` [before the final prefetch](https://github.com/tensorflow/tpu/blob/5144289ba9c9e5b1e55cc118b69fe62dd868657c/models/official/resnet/imagenet_input.py#L217).

Long answer: I have tried two implementations of synthetic tensors, and they have the same step time issue as above. I see the same issue on MLPerf when I materialize fake tensors of batch_sizex224x224x3 data in the input pipeline (before prefetch). Likewise, on TPU repository, I have tried using empty data_dir, which has the same logical effect, though the step time is ~115ms due to subsequent computational operations (batching). When I `dataset = dataset.take(1).cache().repeat()` before prefetch on this pipeline, the compute goes away and I am left with the 60-70ms step time (as above).  I haven't tried making on-TPU tensors.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
