### ISSUE TITLE
Hi, am trying to visualize the loss function using tensorboard 

### ISSUE THREAD

**Issue by Rimehdaoudi** [tensorflow/tensorflow#43756]
Hi am trying to view loss function using tensorboard , am using google colab, i edit my code as following:
`import tensorflow as tf
import datetime
%load_ext tensorboard

sess = tf.Session()

file_writer = tf.summary.FileWriter('/path/to/logs', sess.graph)
logdir = os.path.join(
    "logs", datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))
tensorboard_callback = tf.keras.callbacks.TensorBoard(logdir, histogram_freq=1)`

and while calling train() i added 

`custom_callbacks=[tensorboard_callback]`

it gives me the following error

`
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py in _SatisfiesTypeConstraint(dtype, attr_def, param_name)
     59           "allowed values: %s" %
     60           (param_name, dtypes.as_dtype(dtype).name,
---> 61            ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
     62 
     63 

TypeError: Value passed to parameter 'values' has DataType bool not in list of allowed values: float32, float64, int32, uint8, int16, int8, int64, bfloat16, uint16, float16, uint32, uint64
`

**Comment by Saduf2019** [comment]
@Rimehdaoudi 
Please refer to [this comment](https://github.com/tensorflow/tensorboard/issues/1340#issuecomment-529612368) as per which this error does not exist in 2.x version, could you please upgrade your tf version as there is no support for 1.x and let us know if the issue exist.
you may also refer to issues with siilar error: [link](https://stackoverflow.com/questions/44417133/typeerror-value-passed-to-parameter-a-has-datatype-not-in-list-of-allowed-val/63300437#63300437), [link1](https://stackoverflow.com/questions/44822999/tensorflow-typeerror-value-passed-to-parameter-input-has-datatype-uint8-not-in).
