### ISSUE TITLE
training.tracking.data_structures.List is not properly serialized / deserialized

### ISSUE THREAD

**Issue by sehoffmann** [tensorflow/tensorflow#43755]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.1
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.3.0-54-gfcc4b966f1 2.3.1
- Python version: 3.6.9
- CUDA/cuDNN version: 10.1
- GPU model and memory: GTX 2080 Ti

**Describe the current behavior**
Weights loaded from a layer containing sublayers in a `tracking.data_structures.List` are not properly listed in the `.weights` attributes. This will not only cause confusion but will also sabotage any further optimization or modification of weights. They are properly restored though.

The issue is not present when `ListWrapper` is used.

**Describe the expected behavior**
Variables of sublayers contained in a `List` should be contained in `.weights` when the model is loaded again

**Standalone code to reproduce the issue**
```
import tensorflow as tf

class TestLayer(tf.keras.layers.Layer):

    def __init__(self, **kwargs):
        super(TestLayer, self).__init__(**kwargs)

        self.static_layer = tf.keras.layers.Dense(128)
        self.my_layers = tf.python.training.tracking.data_structures.List()
        for i in range(4):
            layer = tf.keras.layers.Dense(128)
            self.my_layers.append(layer)


    def call(self, x):
        x = self.static_layer(x)

        for layer in self.my_layers:
            x = layer(x)

        return x


    def get_config(self):
        return super(TestLayer, self).get_config()


model = tf.keras.Sequential([TestLayer()])

x = tf.constant(42.0, shape=[1,1])
y1 = model(x)

model.save('my_test_model', save_format='tf')

model_loaded = tf.keras.models.load_model('my_test_model')
y2 = model_loaded(x)

# output
model.summary()
model_loaded.summary()
print('n vars: ', len(model.weights), ' ', len(model_loaded.weights))
print('diff: ', tf.norm(y1-y2))   
```

**Output**
```
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
test_layer (TestLayer)       (None, 128)               66304     
=================================================================
Total params: 66,304
Trainable params: 66,304
Non-trainable params: 0
_________________________________________________________________
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
test_layer (TestLayer)       (None, 128)               256       
=================================================================
Total params: 256
Trainable params: 256
Non-trainable params: 0
_________________________________________________________________
n vars:  10   2
diff:  tf.Tensor(0.0, shape=(), dtype=float32)
```

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3 and was able to reproduce the issue.Please, find the gist [here.](https://colab.research.google.com/gist/ravikyram/edd95a5ea2b8e20653c85f4f7562e4cf/untitled418.ipynb). However i am seeing the below error message in TF nightly version(`AttributeError: module 'tensorflow' has no attribute 'python'`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/9656de67353c9853fb48a58c0aaeb151/untitled419.ipynb).Thanks!

**Comment by jvishnuvardhan** [comment]
I am able to reproduce the issue with `tf-nightly`. [here](https://colab.research.google.com/gist/jvishnuvardhan/adf87ee193ca261778bd1ce9050814ad/untitled419.ipynb) is a gist for our reference. Thanks!

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210528, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/e68f8be30386637f23f47bb79ace6bd0/43755.ipynb). Thanks!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
