### ISSUE TITLE
Creating a "Books" section under Resources

### ISSUE THREAD

**Issue by packtpartner** [tensorflow/tensorflow#4375]
Packt is proud to publish a new book on TensorFlow
 [Getting Started with TensorFlow](https://www.packtpub.com/big-data-and-business-intelligence/getting-started-tensorflow)

We would appreciate if you could create a "Books" section under Resources to feature books written on TensorFlow. 

Let me know if this can be done.

Thanks

**Comment by yaroslavvb** [comment]
BTW, there's a list of TensorFlow books on
https://github.com/jtoy/awesome-tensorflow

You could do a pull request to add your book there

**Comment by packtpartner** [comment]
Thanks for the link @yaroslavvb 
But I feel it will help alot more people if it is featured on tensorflow.org
@andrewharp could you help me with this?

**Comment by packtpartner** [comment]
@andydavis1 could you help me?

**Comment by martinwicke** [comment]
We have not made such a books section since we would have trouble
maintaining it, and making sure that it's reasonably up to date.

There are many books on TensorFlow already and we haven't read any so we
think it would be somewhat inappropriate to endorse some of them.

**Comment by martinwicke** [comment]
We don't have the bandwidth to review books. However, we are thinking about redoing our community page, so stay tuned.

**Comment by packtpartner** [comment]
Sure @martinwicke . Keep me updated :)
