### ISSUE TITLE
Wrong paragraph ordering in tutorial

### ISSUE THREAD

**Issue by momohatt** [tensorflow/tensorflow#43770]
## URL(s) with the issue:

https://www.tensorflow.org/tutorials/keras/classification

## Description of issue (what needs changing):

When you open the above tutorial, the description of the dataset (Fashion MNIST) is placed at the bottom of the page.
However, in [the original .ipynb file](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/keras/classification.ipynb), it is in the first section "Import the Fashion MNIST dataset".
It seems that the order of the paragraph is wrongly rearranged when building the web page.

**Comment by yashk2810** [comment]
This is now fixed.

**Comment by momohatt** [comment]
Thanks!
