### ISSUE TITLE
tensorflow.contrib.learn.TensorFlowEstimator fails under sklearn.base.clone()

### ISSUE THREAD

**Issue by zeromeaning** [tensorflow/tensorflow#4377]
tensorflow.contrib.learn.TensorFlowEstimator fails under sklearn.base.clone()

This prevents the possibility to perform CV using sklearn.cross_validation.cross_val_Score over this estimator.
The clone fails due to the fact the TensorFlowEstimator.get_params() returns a key named "params" that is not part of the constructor input parameters.
This causes sklearn.base.clone to fail when trying to clone the estimator using it's constructor:
TensorFlowEstimator(**params)

**Comment by ilblackdragon** [comment]
`TensorFlowEstimator` is deprecated and is removed in future version. Please use `Estimator`.

That said, the issue probably will persist with `Estimator` so we are going to address it there.

**Comment by skye** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
