### ISSUE TITLE
Saving and loading Keras model with RNN layer that uses both multiple input and constants will result in ValueError when using model.predict()

### ISSUE THREAD

**Issue by juulie** [tensorflow/tensorflow#43773]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):2.3.0
- Python version:3.8.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
When using a RNN layer that has multiple inputs, as well as contants input, saving and loading it to disk using the H5 file format will produce the following when using model.predict:

`tensorflow\python\keras\engine\input_spec.py:155 assert_input_compatibility
        raise ValueError('Layer ' + layer_name + ' expects ' +

    ValueError: Layer rnn expects 3 inputs, but it received 2 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, 5, 5) dtype=float32>, <tf.Tensor 'IteratorGetNext:1' shape=(None, 5, 5) dtype=float32>]`

**Describe the expected behavior**
I expect equal results (and thus no ValueError) when calling model.predict() on a certain set of inputs, and doing it again but after saving and loading the model

**Standalone code to reproduce the issue**
```
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers


class RNNCellWithConstants(keras.layers.Layer):

  def __init__(self, units, constant_size, **kwargs):
    self.units = units
    self.state_size = units
    self.constant_size = constant_size
    super(RNNCellWithConstants, self).__init__(**kwargs)

  def build(self, input_shape):
    self.input_kernel = self.add_weight(
        shape=(input_shape[0][1], self.units),
        initializer='uniform',
        name='kernel')
    self.recurrent_kernel = self.add_weight(
        shape=(self.units, self.units),
        initializer='uniform',
        name='recurrent_kernel')
    self.constant_kernel = self.add_weight(
        shape=(self.constant_size, self.units),
        initializer='uniform',
        name='constant_kernel')
    self.built = True

  def call(self, inputs, states, constants):
    [x1, _] = inputs
    [prev_output] = states
    [constant] = constants
    h_input = keras.backend.dot(x1, self.input_kernel)
    h_state = keras.backend.dot(prev_output, self.recurrent_kernel)
    h_const = keras.backend.dot(constant, self.constant_kernel)
    output = h_input + h_state + h_const
    return output, [output]

  def get_config(self):
    config = {'units': self.units, 'constant_size': self.constant_size}
    base_config = super(RNNCellWithConstants, self).get_config()
    return dict(list(base_config.items()) + list(config.items()))


x1 = keras.Input((None, 5))
x2 = keras.Input((None, 5))
c = keras.Input((3,))
cell = RNNCellWithConstants(32, constant_size=3)
layer = keras.layers.RNN(cell)
y = layer((x1,x2), constants=c)

model = keras.models.Model([x1, x2, c], y)
model.compile(
    optimizer='rmsprop',
    loss='mse')
model.train_on_batch(
    [np.zeros((6, 5, 5)), np.zeros((6, 5, 5)), np.zeros((6, 3))],
    np.zeros((6, 32))
)

# Test basic case 
x1_np = np.random.random((6, 5, 5))
x2_np = np.random.random((6, 5, 5))
c_np = np.random.random((6, 3))
y_np = model.predict([x1_np, x2_np, c_np]) 

model.save("test.h5")
loaded_model = keras.models.load_model("test.h5", custom_objects={"RNNCellWithConstants":RNNCellWithConstants})
loaded_y_np = loaded_model.predict([x1_np, x2_np, c_np]) 
assert np.array_equal(y_np, loaded_y_np)
```

**Other info / logs**
I also figured out why this happens: Python's standard json encoder converts list and tuples into array, and the decoder always turns array's into list. When the RNN __call__ function gets called with a list instead of tuple, the following line
````
        full_input_spec = generic_utils.to_list(
            nest.map_structure(lambda _: None, inputs)) + additional_specs
````
Will map that input differently than if it were a tuple.

I will be submitting a pr to fix this

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3 [gist ](https://colab.research.google.com/gist/ravikyram/c9faf64717b07cdfcea9f94a58656de3/untitled414.ipynb), nightly version [gist](https://colab.research.google.com/gist/ravikyram/cb845f973d39417bf741a1549ee57f01/untitled415.ipynb) and was able to reproduce the issue.Thanks!

**Comment by Saduf2019** [comment]
I am able to replicate the issue on tf 2.5, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/f0494cbaca40f524522c55b8d8506726/untitled597.ipynb).

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210528, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/4ee2d78e2e1e900d0330a9ee3bb01faa/43773.ipynb). Thanks!

**Comment by SuryanarayanaY** [comment]
Iam able to reproduce the issue in [2.10v](https://colab.research.google.com/gist/SuryanarayanaY/0ef59652a9f38e3ad4cae819de11e503/43773-2-10v.ipynb) and tf-[nightly](https://colab.research.google.com/gist/SuryanarayanaY/360d31c5427831b4774ed9395085213a/43773-nightly.ipynb) versions.
Thankyou!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
