### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found even when following documentation

### ISSUE THREAD

**Issue by leofrio** [tensorflow/tensorflow#43776]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- windows 10 home single language 
- TensorFlow installed from :cmd
- TensorFlow version:1.14
- Python version:3.7.9
- Installed using virtualenv? pip? conda?:pip

**Describe the problem**
i was following the guide to install the imageai documentation  and did this 
pip3 install tensorflow==1.14
pip3 install opencv-python
pip3 install keras==2.2.4
pip3 install numpy==1.18.5
pip3 install imageai --upgrade 
i changed from 1.13.1 to 1.14 because it wasnt working before, same thing with numpy from 1.16.1 to 1.18.5(the lasted accepted according to the cmd) 
but i cant run the image ai because every time i try to do something it says 
OSError: [WinError 126] The specified module could not be found 
heres the full error 
**
C:\Users\Leoga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Leoga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Leoga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Leoga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\Leoga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\Leoga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Leoga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Leoga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow\python\__init__.py", line 83, in <module>
    from tensorflow.python import keras
  File "C:\Users\Leoga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow\python\keras\__init__.py", line 26, in <module>
    from tensorflow.python.keras import activations
  File "C:\Users\Leoga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow\python\keras\activations.py", line 24, in <module>
    from tensorflow.python.keras.utils.generic_utils import deserialize_keras_object
  File "C:\Users\Leoga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow\python\keras\utils\__init__.py", line 39, in <module>
    from tensorflow.python.keras.utils.multi_gpu_utils import multi_gpu_model
  File "C:\Users\Leoga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow\python\keras\utils\multi_gpu_utils.py", line 22, in <module>
    from tensorflow.python.keras.engine.training import Model
  File "C:\Users\Leoga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow\python\keras\engine\training.py", line 41, in <module>
    from tensorflow.python.keras.engine import training_arrays
  File "C:\Users\Leoga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 40, in <module>
    from scipy.sparse import issparse  # pylint: disable=g-import-not-at-top
  File "C:\Users\Leoga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\__init__.py", line 136, in <module>
    from . import _distributor_init
  File "C:\Users\Leoga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\_distributor_init.py", line 61, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found 
** 
ive put 
C:\Users\Leoga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\Scripts 
to path as well and it still does not work 
everytime i import tensorflow or imageai or even keras this error happens
and ive tried following some people with similar problems but none of them worked for me, like downloading a wheel a user found and so on 
ive been trying to slove this for 2 days please help me

**Comment by amahendrakar** [comment]
@leofrio,
To resolve the `FutureWarning`, please run the below commands
```
!pip install numpy==1.16.4
!pip install tensorflow==1.14
```

Regarding the `OSError`, please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) and check if you have all the compatible software installed. Also, make sure that you have installed Python from [python.org](https://www.python.org/downloads/windows/) and not from the Microsoft Store. Thanks!

**Comment by leofrio** [comment]
i tried downloading using !pip commands but it said its not recognizable as a command in the cmd, also ive tried using a python download from python.org but everytime i type python on the cmd even if i have a python.org version installed it takes me to the windows store version

**Comment by leofrio** [comment]
!pip install numpy 1.16.4
'!pip' is not recognized as an internal or external command,
operable program or batch file.

**Comment by leofrio** [comment]
> @leofrio,
> To resolve the `FutureWarning`, please run the below commands
> 
> ```
> !pip install numpy==1.16.4
> !pip install tensorflow==1.14
> ```
> 
> Regarding the `OSError`, please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) and check if you have all the compatible software installed. Also, make sure that you have installed Python from [python.org](https://www.python.org/downloads/windows/) and not from the Microsoft Store. Thanks!

also,relating to system requirements i do fullfil them

**Comment by amahendrakar** [comment]
@leofrio,
Sorry, my bad. The exclamation mark is not required while running the command. Please run the below commands and let us know if it helps. 
```
pip install numpy==1.16.4
pip install tensorflow==1.14
```
Thanks!

**Comment by leofrio** [comment]
thank you so much, i realized i was using the windows store version of python , so i just uninstalled that, when i downloaded the the one from python.org i checked the option to put python to path, and it appeared on the cmd, now everything is working as it should even the tensorflow-gpu, thanks!
