### ISSUE TITLE
third_party/gpus/find_cuda_config.py is unable to detect cudnn version and causing `./configure` to fail

### ISSUE THREAD

**Issue by emados** [tensorflow/tensorflow#43772]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: v2.1.2 (checked out at this release tag)
- Python version: Python 3.8.3
- Installed using virtualenv? pip? conda?: Conda (conda 4.8.5)
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
- CUDA/cuDNN version: CUDA 11.1, cuDNN 8
- GPU model and memory: RTX 3080, 10G

**Describe the problem**
When I was trying to configure TensorFlow to build from source, I got the following error:

```
Traceback (most recent call last):
  File "./configure.py", line 1554, in <module>
    main()
  File "./configure.py", line 1437, in main
    if validate_cuda_config(environ_cp):
  File "./configure.py", line 1318, in validate_cuda_config
    config = dict(
ValueError: dictionary update sequence element #9 has length 1; 2 is required
```

and after debugging I noticed that the issue is that the cuDNN version isn't detected, and thus `./configure` fails.

third_party/gpus/find_cuda_config.py
cudnn_version.h

**Provide the exact sequence of commands / steps that you executed before running into the problem**

My `./configure` sequence:

```
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.29.1 installed.
Please specify the location of python. [Default is /home/madz/anaconda3/envs/tensorflow/bin/python]: 


Found possible Python library paths:
  /home/madz/anaconda3/envs/tensorflow/lib/python3.8/site-packages
Please input the desired Python library path to use.  Default is [/home/madz/anaconda3/envs/tensorflow/lib/python3.8/site-packages]

Do you wish to build TensorFlow with XLA JIT support? [Y/n]: 
XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: 
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: 
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: Y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: 
No TensorRT support will be enabled for TensorFlow.

Traceback (most recent call last):
  File "./configure.py", line 1554, in <module>
    main()
  File "./configure.py", line 1437, in main
    if validate_cuda_config(environ_cp):
  File "./configure.py", line 1318, in validate_cuda_config
    config = dict(
ValueError: dictionary update sequence element #9 has length 1; 2 is required
```

**Any other info / logs**

Then when I tried to run `python third_party/gpus/find_cuda_config.py cuda cudnn`, I got the following output:

```
cublas_include_dir: /usr/local/cuda/include
cublas_library_dir: /usr/local/cuda/lib64
cuda_binary_dir: /usr/local/cuda/bin
cuda_include_dir: /usr/local/cuda/include
cuda_library_dir: /usr/local/cuda/lib64
cuda_toolkit_path: /usr/local/cuda
cuda_version: 11.1
cudnn_include_dir: /usr/local/cuda/include
cudnn_library_dir: /usr/local/cuda/lib64
cudnn_version: 
cupti_include_dir: /usr/local/cuda/include
cupti_library_dir: /usr/local/cuda/lib64
nvvm_library_dir: /usr/local/cuda/nvvm/libdevice
```

It turns out for my cuDNN installation, the header file that should be checked is `cudnn_version.h` and not `cudnn.h`. I wanted to make a pull request, but I'm not really sure how to adjust this so that it can use either header file.

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gattia** [comment]
For whomever is following/fixing this. The issue is at this line: 

https://github.com/tensorflow/tensorflow/blob/cdf2c541c3dd3fb6d03cce4d23fc6c548bc9017c/third_party/gpus/find_cuda_config.py#L347

"cudnn.h" needs to be changed to "cudnn_version.h" as @emados says

However, simply doing this as a blank change is likely to break things for other versions. So, more might need to be done. A bit beyond my scope, but figured I'd help out so maybe this can be closed.

**Comment by sanjoy** [comment]
This is fixed at head.  We typically don't backport bugfixes to older releases.
