### ISSUE TITLE
Interpreter takes too much time to  return results while similar iOS app makes it 10 times faster

### ISSUE THREAD

**Issue by damian-adamski** [tensorflow/tensorflow#43787]
I use following code to create Interpreter, prepare image and execute task to get proper results:

    private var imageData: ByteBuffer
    private var outputBuffer = Array(1) { Array(256) { Array(256) { FloatArray(NUM_CLASSES) } } }
    private var gpuDelegate: GpuDelegate? = null
    private val interpreter: Interpreter
    private var intValues: IntArray

    init {
        interpreter = getInterpreter(context, tfLiteModel)
        interpreter.allocateTensors()
        imageData = ByteBuffer.allocateDirect(1 * inputWidth * inputHeight * 3 * 4)
        imageData.order(ByteOrder.nativeOrder())
        intValues = IntArray(inputWidth * inputHeight)

    }

    private fun getInterpreter(
        context: Context,
        tfLiteModel: String
    ): Interpreter {

        val compatList = CompatibilityList()
        val tfLiteOptions = Interpreter.Options().apply {
            if (compatList.isDelegateSupportedOnThisDevice) {
                val delegateOptions = compatList.bestOptionsForThisDevice
                delegateOptions.setPrecisionLossAllowed(true)
                this.addDelegate(GpuDelegate(delegateOptions))
            } else {
                setNumThreads(NUM_THREADS)
            }
        }
        return Interpreter(loadModelFile(context, tfLiteModel), tfLiteOptions)
    }

    @Throws(IOException::class)
    private fun loadModelFile(context: Context, modelFile: String): MappedByteBuffer {
        val fileDescriptor = context.assets.openFd(modelFile)
        val inputStream = FileInputStream(fileDescriptor.fileDescriptor)
        val fileChannel = inputStream.channel
        val startOffset = fileDescriptor.startOffset
        val declaredLength = fileDescriptor.declaredLength
        val retFile = fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength)
        fileDescriptor.close()
        return retFile
    }

    fun close() {
        interpreter?.close()
        gpuDelegate?.close()
    }

    fun prepareImage() {
        imageData.rewind()
        for (i in 0 until intValues.size) {
            val pixelValue = intValues[i]
            imageData.putFloat((((pixelValue shr 16) and 0xFF) - IMAGE_MEAN) / IMAGE_STD)
            imageData.putFloat((((pixelValue shr 8) and 0xFF) - IMAGE_MEAN) / IMAGE_STD)
            imageData.putFloat(((pixelValue and 0xFF) - IMAGE_MEAN) / IMAGE_STD)
        }
        imageData.rewind()
    }

    fun execute(bitmap: Bitmap): Array<Array<Array<FloatArray>>> {

        bitmap.getPixels(intValues, 0, bitmap.width, 0, 0, bitmap.width, bitmap.height)
        prepareImage()
        val timing = System.currentTimeMillis()
        interpreter.run(imageData, outputBuffer)
        Log.d("executetiming", "run() - ${System.currentTimeMillis() - timing}")
        return outputBuffer

    }

    companion object {
        private const val NUM_CLASSES: Int = 2
        private const val IMAGE_MEAN = 127.5f
        private const val IMAGE_STD = 127.5f
        private const val NUM_THREADS = 4
    }
}
The app is something between object recognition and image segmentation. I recognize certain objects with my camera and put colors on them pixel by pixel using Canvas.
The problem is that I am getting following timings:

> 2020-10-05 10:02:34.134 27093-27278/com.example.sampleappkt D/executetiming: run() - 550
2020-10-05 10:02:34.841 27093-27278/com.example.sampleappkt D/executetiming: run() - 625
2020-10-05 10:02:35.603 27093-27278/com.example.sampleappkt D/executetiming: run() - 645
2020-10-05 10:02:36.345 27093-27278/com.example.sampleappkt D/executetiming: run() - 608
2020-10-05 10:02:37.068 27093-27278/com.example.sampleappkt D/executetiming: run() - 628
2020-10-05 10:02:37.804 27093-27278/com.example.sampleappkt D/executetiming: run() - 640
2020-10-05 10:02:38.462 27093-27278/com.example.sampleappkt D/executetiming: run() - 591
2020-10-05 10:02:39.187 27093-27278/com.example.sampleappkt D/executetiming: run() - 632
2020-10-05 10:02:39.921 27093-27278/com.example.sampleappkt D/executetiming: run() - 650
2020-10-05 10:02:40.669 27093-27278/com.example.sampleappkt D/executetiming: run() - 627
2020-10-05 10:02:41.387 27093-27278/com.example.sampleappkt D/executetiming: run() - 621
2020-10-05 10:02:42.126 27093-27278/com.example.sampleappkt D/executetiming: run() - 648
2020-10-05 10:02:42.825 27093-27278/com.example.sampleappkt D/executetiming: run() - 635
2020-10-05 10:02:43.527 27093-27278/com.example.sampleappkt D/executetiming: run() - 636
2020-10-05 10:02:44.203 27093-27278/com.example.sampleappkt D/executetiming: run() - 576
2020-10-05 10:02:44.952 27093-27278/com.example.sampleappkt D/executetiming: run() - 654
2020-10-05 10:02:45.670 27093-27278/com.example.sampleappkt D/executetiming: run() - 649
2020-10-05 10:02:46.399 27093-27278/com.example.sampleappkt D/executetiming: run() - 667
2020-10-05 10:02:47.001 27093-27278/com.example.sampleappkt D/executetiming: run() - 509
2020-10-05 10:02:47.579 27093-27278/com.example.sampleappkt D/executetiming: run() - 495
2020-10-05 10:02:48.321 27093-27278/com.example.sampleappkt D/executetiming: run() - 660
2020-10-05 10:02:49.053 27093-27278/com.example.sampleappkt D/executetiming: run() - 624
2020-10-05 10:02:49.764 27093-27278/com.example.sampleappkt D/executetiming: run() - 617
2020-10-05 10:02:50.520 27093-27278/com.example.sampleappkt D/executetiming: run() - 659
2020-10-05 10:02:51.317 27093-27278/com.example.sampleappkt D/executetiming: run() - 694
2020-10-05 10:02:52.099 27093-27278/com.example.sampleappkt D/executetiming: run() - 658

I've checked performance using app from here: https://www.tensorflow.org/lite/performance/measurement
And I got this:
![deeplab_float32_converted](https://user-images.githubusercontent.com/55881948/95068369-81de6a00-0705-11eb-9933-34d46d9188e9.png)

I use Samsung Galaxy S7 Edge for my tests, but I think even if it isn't newest phone those timings shouldn't be that high.
Model used is Mobilenet.
Same model needs 80ms overal when used on iPhone 8 with 2 threads.
How can I get rid of "Warmup" process launched everytime?

**Comment by Saduf2019** [comment]
@wiggy
What version of tf are you using, i see that you have nit filled in the issue template.

**Comment by wiggy90210** [comment]
I'm sorry, I forgot about that.
I tested this with 2 versions:
0.0.0-nightly - those results you can see on my first post
2.3.0 - there was even worse because i got timings between 750-850ms

**Comment by renjie-liu** [comment]
this is strange, can you try use the bench tool to just benchmark the model?

https://www.tensorflow.org/lite/performance/measurement#native_benchmark_binary

**Comment by wiggy90210** [comment]
I don't really know how to work with bazel :/ that's why I've made steps included in https://www.tensorflow.org/lite/performance/measurement only

**Comment by renjie-liu** [comment]
Hi Chao, can you help take a look?

thanks!

**Comment by wiggy90210** [comment]
It may help, but that doesn't completely resolve my problem, but I've tested the app on **Xiaomi POCO F2 Pro** and times had shortened to ~130ms but it is still 2 times longer than iPhone8.  POCO F2 Pro is slightly better that iPhone 11 Max in benchmarks, so it has to be much much better than iPhone 8 but still slower. Probably it is about platforms. Apple makes libraries for their and only their hardware and ofc software (iOS) but could it be that much faster?

**Comment by renjie-liu** [comment]
it's possible the benchmark is running on the small core in Xiaomi but big core in the iPhone

**Comment by wiggy90210** [comment]
Actually I am talking about logs from my app because Xiaomi blocked benchmark somehow (actually logcat) even if I disabled all security options on the device. My interpreter initialization looks like this:
 ```
val compatList = CompatibilityList()
        val tfLiteOptions = Interpreter.Options().apply {
            if (compatList.isDelegateSupportedOnThisDevice) {
                val delegateOptions = compatList.bestOptionsForThisDevice
                delegateOptions.setPrecisionLossAllowed(true)
                this.addDelegate(GpuDelegate(delegateOptions))
            } else {
                setNumThreads(NUM_THREADS) // 4 threads
            }
        }
        return Interpreter(loadModelFile(context, tfLiteModel), tfLiteOptions)
```

**Comment by pkgoogle** [comment]
Hello, @damian-adamski, there has been numerous improvements since this was opened, can you check to see if this is still an issue?

**Comment by damian-adamski** [comment]
Thanks for response @pkgoogle but it's been long time. I'm no longer working on tfLite projects. In a mean time I had several calls with people that had been struggling with same issue and also with representatives from company that has experience with this topic and they also had similar issues. For Android they had to go with recognizing patterns using images instead of realtime. Big chunk of problems comes also from rendering colors on the screen while recognizing stuff. It's just beauty of the Android; works on most of devices and it's not tailored for only one like an iOS.
