### ISSUE TITLE
bitwise op with 1 msb throws in tf.function

### ISSUE THREAD

**Issue by amitport** [tensorflow/tensorflow#43783]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
tf 2.2, windows 10 (can't install tf 2.3 because various open issues)
cuda 10.1

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
v2.2.0-57-g25fba035f3 2.2.1

**Describe the current behavior**

```
@tf.function(input_signature=[tf.TensorSpec(shape=[], dtype=tf.int32)])
def f(t):
    return tf.bitwise.bitwise_and(t, 0b10000000000000000000000000000000)

f(tf.constant(2, dtype=tf.int32))
```
throws `OverflowError: Python int too large to convert to C long`

(Works fine without `tf.function`)

**Describe the expected behavior**
should not throw (return 0 in this case)

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
Traceback (most recent call last):
  File "<root>/t.py", line 8, in <module>
    f(tf.constant(2, dtype=tf.int32))
  File "<site-packages>\tensorflow\python\eager\def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "<site-packages>\tensorflow\python\eager\def_function.py", line 627, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "<site-packages>\tensorflow\python\eager\def_function.py", line 506, in _initialize
    *args, **kwds))
  File "<site-packages>\tensorflow\python\eager\function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "<site-packages>\tensorflow\python\eager\function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "<site-packages>\tensorflow\python\eager\function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "<site-packages>\tensorflow\python\framework\func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "<site-packages>\tensorflow\python\eager\def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "<site-packages>\tensorflow\python\framework\func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.autograph.impl.api.StagingError: in user code:

    <root>/t.py:6 f  *
        return tf.bitwise.bitwise_and(t, 0b10000000000000000000000000000000)
    <site-packages>\tensorflow\python\ops\gen_bitwise_ops.py:81 bitwise_and  **
        "BitwiseAnd", x=x, y=y, name=name)
    <site-packages>\tensorflow\python\framework\op_def_library.py:470 _apply_op_helper
        preferred_dtype=default_dtype)
    <site-packages>\tensorflow\python\framework\ops.py:1341 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    <site-packages>\tensorflow\python\framework\tensor_conversion_registry.py:52 _default_conversion_function
        return constant_op.constant(value, dtype, name=name)
    <site-packages>\tensorflow\python\framework\constant_op.py:262 constant
        allow_broadcast=True)
    <site-packages>\tensorflow\python\framework\constant_op.py:300 _constant_impl
        allow_broadcast=allow_broadcast))
    <site-packages>\tensorflow\python\framework\tensor_util.py:452 make_tensor_proto
        nparray = np.array(values, dtype=np_dt)

    OverflowError: Python int too large to convert to C long


Process finished with exit code 1
```

**Comment by Saduf2019** [comment]
@amitport 
I ran the code shared on tf nightly and do not face any issues, please try on nightly and update.
Please find the gist for the [same here](https://colab.research.google.com/gist/Saduf2019/512b0732a1f3fd88eea53391ec3ca52a/untitled418.ipynb).

With respect to the error faced, please refer to [this link](https://stackoverflow.com/questions/38314118/overflowerror-python-int-too-large-to-convert-to-c-long-on-windows-but-not-ma) and let us know, as i can see the error does not occur on [tf 2.2](https://colab.research.google.com/gist/Saduf2019/f43012a89326ebf68b5cf83178aa114a/untitled424.ipynb)

**Comment by amitport** [comment]
@Saduf2019 the problem is on windows and tf@2.2 and the number is not bigger than `sys.maxsize`.

(I think it is important to note again tf@2.3 and nightly have many issues on windows, I, and many others can upgrade or verify this on those versions)

**Comment by chunduriv** [comment]
I am able to replicate this issue using `TF2.9.1` on Windows.

**Comment by tilakrayal** [comment]
@amitport,
I tried to execute the mentioned code on tensorflow v2.14 on colab and also on the Windows environment with and without tf.function and it was executed without any issue/error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/f03aac91f596a5a15ed5af6f09248780/untitled1620.ipynb).

Also TensorFlow 2.10 was the last TensorFlow release that supported GPU on native-Windows. Starting with TensorFlow 2.11, you will need to install [TensorFlow in WSL2](https://tensorflow.org/install/pip#windows-%5Bwsl2%5D), or install tensorflow-cpu and, optionally, try the [TensorFlow-DirectML-Plugin](https://github.com/microsoft/tensorflow-directml-plugin#tensorflow-directml-plugin-)
https://www.tensorflow.org/install/pip#windows-native_1

Thank you!
