### ISSUE TITLE
[MLIR] TFlite contains unused file

### ISSUE THREAD

**Issue by yashi21** [tensorflow/tensorflow#43781]
**tensorflow/compiler/mlir/lite/transforms/load_quantization_recipe.cc** is called via 
`tf-opt -allow-unregistered-dialect -tfl-load-recipe %s | FileCheck %s`

However, according to [this commit](https://github.com/tensorflow/tensorflow/commit/36167cb04c890f55f8abf1df1d79bf4bf6361d08), "-allow-unregistered-dialect" is disabled (the only way to call the file is deprecated).
Hence, in **tensorflow/compiler/mlir/lite/transforms/load_quantization_recipe.cc** can be removed as it is not involved in any mlir::tfl passes.

**Comment by abattery** [comment]
Thanks for reporting this! Will remove the unused dependency.
