### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: OpenCL library not loaded - dlopen failed: library "libOpenCL-pixel.so" not found

### ISSUE THREAD

**Issue by archie94** [tensorflow/tensorflow#43793]
**System information**

Mobile Device - Android - across multiple Android version (6, 7, 8)

**Describe the current behavior**

Invoking `org.tensorflow.lite.Interpreter` causes crash on some cases

**Describe the expected behavior**

Should not crash

**Standalone code to reproduce the issue**

I am getting this on crash analysis tool. Since this is not reproducible on my devices I am not able to produce a standalone code.

**Other info / logs** 

```

Fatal Exception: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: OpenCL library not loaded - dlopen failed: library "libOpenCL-pixel.so" not found
Falling back to OpenGL
TfLiteGpuDelegate Init: No EGL error, but eglChooseConfig failed.
TfLiteGpuDelegate Prepare: delegate is not initialized
Node number 31 (TfLiteGpuDelegateV2) failed to prepare.

Restored previous execution plan after delegate application failure.
       at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegate(NativeInterpreterWrapper.java)
       at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:85)
       at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:61)
       at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:224)
       at a.b.c..data.Posenet.getInterpreter(Posenet.java:184)
       at a.b.c..data.Posenet.estimateSinglePose(Posenet.java:293)
       at a.b.c..call.ImageAnalyser.processImage(ImageAnalyser.java:157)
       at a.b.c..call.ImageAnalyser.access$processImage(ImageAnalyser.java:26)
       at a.b.c..call.ImageAnalyser$processImageForAnalysis$2.invokeSuspend(ImageAnalyser.java:127)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:56)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

```

**Comment by archie94** [comment]
Hello @jvishnuvardhan any update on this? Anything more I can help with here?

**Comment by srjoglekar246** [comment]
@archie94 Can you provide a snippet of your inference code in Java? It might help us dig into whats happening.

Also adding @impjdi who might know more about the specific errors.

**Comment by archie94** [comment]
Hi @srjoglekar246 

It is pretty much same as this sample https://github.com/tensorflow/examples/blob/master/lite/examples/posenet/android/posenet/src/main/java/org/tensorflow/lite/examples/posenet/lib/Posenet.kt

**Comment by impjdi** [comment]
@srjoglekar246 If it wasn't able to load the delegate with that error message, it should safely fallback to OpenGL, but I've never seen that "No EGL error, but eglChooseConfig failed." in my last 3 years working on this project.  But then when that fails, we should safely fallback to CPU mode.

@archie94 Rather than "Mobile Device - Android - across multiple Android version (6, 7, 8)", can you specifically name devices?  We'll see whether we can repro if we have the device...

**Comment by srjoglekar246** [comment]
Hmm I agree. "Restored previous execution plan after delegate application failure." indicates we did recover to CPU on the native side,  but we might be treating that as an error in the JNI layer.

**Comment by archie94** [comment]
Thank you for your response! 

Sure here are some devices on which we are facing this issue.

Samsung
- Galaxy J3(2016)
- Galaxy J3(2016)
- Galaxy Tab E 9.6

LGE
- LG Phoenix 4
- LG K8(2018)
- LG K8(2018)

Cherry_Mobile
- Flare_S7_Prime

The one area where we differ from the above sample is we select `GpuDelegate` if the device supports OpenGL ES 2.0 API.

**Comment by impjdi** [comment]
Oh, our GPU delegate only support OpenGL ES 3.1 and above, as we employ compute shaders which are not available in 3.0 or below.

**Comment by archie94** [comment]
Oh! I thought they 3.x was backwards compatible!

That may have been the case? Allow me some time to make the change and get back to you on this.

**Comment by archie94** [comment]
One week after the OpenGL ES 3.1 check there are no issues on the new release. I think this issue is resolved.

Thank you @impjdi @srjoglekar246 for you help :)
