### ISSUE TITLE
Google Collab error for TPU - UnavailableError: {{function_node __inference_train_function_99378}} failed to connect to all addresses 

### ISSUE THREAD

**Issue by ScruffySilky** [tensorflow/tensorflow#43790]
No longer able to train model using google cloud TPU on my [gist](https://colab.research.google.com/gist/ScruffySilky/f681aca8130f40555b41f98323887c15/42038.ipynb?authuser=1&pli=1), it was training fine 2 months ago and now I get the following error:

```
UnavailableError: {{function_node __inference_train_function_99378}} failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1601903304.230958587","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3948,"referenced_errors":[{"created":"@1601903304.089639211","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}
	 [[{{node IteratorGetNext}}]]
```

Seems related to this issue: https://github.com/tensorflow/tensorflow/issues/43037

**Comment by Saduf2019** [comment]
@ScruffySilky 
Please refer to these issues and let us know if the issue exist: [link](https://stackoverflow.com/questions/63523682/error-training-keras-model-on-google-colab-using-tpu-runtime) #39099 #43125 #42038

**Comment by ScruffySilky** [comment]
> @ScruffySilky
> Please refer to these issues and let us know if the issue exist: [link](https://stackoverflow.com/questions/63523682/error-training-keras-model-on-google-colab-using-tpu-runtime) #39099 #43125 #42038

Of the solutions provided, this one https://github.com/tensorflow/tensorflow/issues/39099 is the only one that removes the error: using !pip install tf-nightly==2.2.0-dev20200505, however it outputs a different error and I still cannot proceed, [Gist](https://colab.research.google.com/gist/ScruffySilky/f681aca8130f40555b41f98323887c15/42038.ipynb#scrollTo=BCcpB-9_Pni4): 

```
Epoch 1/10
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-7-6ac9763b188d> in <module>()
    129 
    130 generator = data_generator(texts, train_features, 1, max_sequence)
--> 131 model.fit_generator(generator, steps_per_epoch=steps, epochs=10, callbacks=callbacks_list, verbose=1)
    132 model.save(mydrive + '/output/weights.hdf5')

7 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

NotFoundError: 'OptimizeDatasetV2' is neither a type of a primitive operation nor a name of a function registered in binary running on n-dde0e0b9-w-0. Make sure the operation or function is registered in the binary running in this process. [Op:__inference_train_function_40349]
```

**Comment by Saduf2019** [comment]
@ScruffySilky 
Please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/40622#issuecomment-654488935), try with tf 2.3 and let us know.

**Comment by ScruffySilky** [comment]
Have just tried, using tf 2.3.0 reverts to the same error: 

```
UnavailableError                          Traceback (most recent call last)
<ipython-input-8-6ac9763b188d> in <module>()
    129 
    130 generator = data_generator(texts, train_features, 1, max_sequence)
--> 131 model.fit_generator(generator, steps_per_epoch=steps, epochs=10, callbacks=callbacks_list, verbose=1)
    132 model.save(mydrive + '/output/weights.hdf5')

16 frames
/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

UnavailableError: {{function_node __inference_train_function_56800}} failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
:{"created":"@1602080688.607997979","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3948,"referenced_errors":[{"created":"@1602080688.315542576","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}
	 [[{{node IteratorGetNext}}]]
```

**Comment by nikitamaia** [comment]
In the past this error message has indicated a version mismatch. Can you first try and import from tensorflow.keras instead of native keras?

**Comment by ScruffySilky** [comment]
> In the past this error message has indicated a version mismatch. Can you first try and import from tensorflow.keras instead of native keras?

Have done so, receive the same error, [GIST](https://colab.research.google.com/gist/ScruffySilky/1db7bf789b92f9d6523b72cc8ccedb75/42038.ipynb?authuser=1)

**Comment by m0bi5** [comment]
Facing the same issue with tf 2.3.0

**Comment by pratapnarra** [comment]
Did anyone find solution to this? Facing the same issue on colab

**Comment by Capiru** [comment]
This is still a persistent issue

**Comment by acul3** [comment]
same here... just encounter similar error

Tensorflow 2.4.0

**Comment by sachinprasadhs** [comment]
Was able to reproduce the error in Tensorflow 2.5 using colab TPU, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/5bf64a99404d6d04ccb73ec2b3f5469d/43790.ipynb). Thanks!

**Comment by pn12** [comment]
Anybody able to solve this error. My code is stuck at this.

**Comment by Kaveh8** [comment]
Still no solution? Should we consider this to not using generators on TPU?

**Comment by Dimiftb** [comment]
Has anybody been able to solve this? 

I'm trying to run BERT on Google Colab TPU, however I'm getting a similar error. 
Tensorflow version 2.8.0
Code I'm using for loading the TPU is vastly based on the original code for pre-training T5 by Google taken from [here:](https://colab.research.google.com/github/google-research/text-to-text-transfer-transformer/blob/master/notebooks/t5-trivia.ipynb#scrollTo=Set_Up) 
```
print("Installing dependencies...")
%tensorflow_version 2.x

import functools
import os
import time
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

import tensorflow.compat.v1 as tf
import tensorflow_datasets as tfds

BASE_DIR = "gs://bucket-xx" #@param { type: "string" }
if not BASE_DIR or BASE_DIR == "gs://":
  raise ValueError("You must enter a BASE_DIR.")
DATA_DIR = os.path.join(BASE_DIR, "data/text.csv")
MODELS_DIR = os.path.join(BASE_DIR, "models/bert")
ON_CLOUD = True


if ON_CLOUD:
  print("Setting up GCS access...")
  import tensorflow_gcs_config
  from google.colab import auth
  # Set credentials for GCS reading/writing from Colab and TPU.
  TPU_TOPOLOGY = "v2-8"
  try:
    tpu = tf.distribute.cluster_resolver.TPUClusterResolver()  # TPU detection
    TPU_ADDRESS = tpu.get_master()
    print('Running on TPU:', TPU_ADDRESS)
  except ValueError:
    raise BaseException('ERROR: Not connected to a TPU runtime; please see the previous cell in this notebook for instructions!')
  auth.authenticate_user()
  tf.enable_eager_execution()
  tf.config.experimental_connect_to_host(TPU_ADDRESS)
  tensorflow_gcs_config.configure_gcs_from_colab_auth()

tf.disable_v2_behavior()

# Improve logging.
from contextlib import contextmanager
import logging as py_logging

if ON_CLOUD:
  tf.get_logger().propagate = False
  py_logging.root.setLevel('INFO')

@contextmanager
def tf_verbosity_level(level):
  og_level = tf.logging.get_verbosity()
  tf.logging.set_verbosity(level)
  yield
  tf.logging.set_verbosity(og_level)
```

Full error message can be seen [here](https://pastebin.com/93EW1GuV).

Any help is much appreciated thanks.

**Comment by JessicaLopezEspejel** [comment]
@[Dimiftb](https://github.com/Dimiftb)  I have the same issue, did you achieve to resolve it?

**Comment by Dimiftb** [comment]
@JessicaLopezEspejel Unfortunately not. I had to resort to using GPU. Please let me know if you find a solution.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
