### ISSUE TITLE
build error - target names may not contain ' '.

### ISSUE THREAD

**Issue by MikalaiDrabovich** [tensorflow/tensorflow#438]
bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
ERROR: /tensorflow/BUILD:27:1: //tensorflow:all_files: invalid label 'TensorFlow-Examples/examples/1 - Introduction/basic_operations.py' in element 4 of attribute 'srcs' in 'filegroup' rule: invalid target name 'TensorFlow-Examples/examples/1 - Introduction/basic_operations.py': target names may not contain ' '.

**Comment by vrv** [comment]
Hm, I can't find basic_operations.py in our repo. I suspect you might have some local changes, possibly intermingled from https://github.com/aymericdamien/TensorFlow-Examples

**Comment by MikalaiDrabovich** [comment]
thanks! rm -rf TensorFlow-Examples solved the issue.
