### ISSUE TITLE
Correct way to cast a RaggeredTensor to list of strings?

### ISSUE THREAD

**Issue by mralexisw** [tensorflow/tensorflow#43805]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: Titan V

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I am trying to incorporate a customized function into tensorflow via `tf.py_function`, which is something like the following

```
    def run(x):
        return tf.py_function(my_func, x, tf.float32, name=None)
    out = tf.keras.layers.Lambda(run)(raggedtensor)
```

The desired input of `my_func` is a list of strings, while the `raggedtensor` is `tf.RaggedTensor(values=Tensor("StringSplit/StringSplitV2:1", shape=(None,), dtype=string), row_splits=Tensor("StringSplit/RaggedFromValueRowIds/concat:0", shape=(None,), dtype=int64)).`

The current code will throw an error of `TypeError: Expected list for 'input' argument to 'EagerPyFunc' Op, not tf.RaggedTensor(values=Tensor...`, while if I changed it to the following

```
    def run(x):
        return tf.py_function(my_func, x.to_list(), tf.float32, name=None)
    out = tf.keras.layers.Lambda(run)(raggedtensor)
```

The error will change to `ValueError: RaggedTensor.to_list() is only supported in eager mode; in graph mode, evaluate the RaggedTensor first and then use RaggedTensorValue.to_list().`

Is there a way I could cast the tensor to my desired input?

**Comment by Saduf2019** [comment]
@mralexisw 
I ran the code on tf nightly and do not face any errors, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/c45ab30f3e1631c8e9b58f29abced508/untitled418.ipynb).

**Comment by mralexisw** [comment]
@Saduf2019 The gist only runs the definition of the function, which will definitely return no error. Could you see what will happen if you pass a tensor into it? Thanks!

**Comment by Saduf2019** [comment]
@mralexisw 
Please provide with complete code to replicate or if possible share a colab gist with the error reported.
