### ISSUE TITLE
ValueError: You are trying to load a weight file containing 0 layers into a model with 19 layers.

### ISSUE THREAD

**Issue by elmahdy27** [tensorflow/tensorflow#43802]
hey this is my code i still have the same error 
from __future__ import absolute_import
from __future__ import print_function
import os
import numpy as np
from keras.layers import Input
from keras.layers.core import Activation, Flatten, Reshape
from keras.layers.convolutional import Convolution2D, MaxPooling2D, UpSampling2D, Conv2D
from keras.layers.normalization import BatchNormalization
from keras.models import Model
from keras.utils import np_utils
from keras.applications import imagenet_utils
from .Architecture import Architecture

class Ronneberger(Architecture):
    @staticmethod
    def get_model(config, crossval_id=None) :
        assert config.arch.num_dimensions is 2
        assert config.arch.patch_shape[0] % 16 == 0, "Invalid patch shape"

        num_modalities = len(config.dataset.modalities)
        input_layer_shape = (num_modalities, ) + config.arch.patch_shape[:config.arch.num_dimensions]
        output_layer_shape = (config.train.num_classes, np.prod(config.arch.patch_shape[:config.arch.num_dimensions]))
        model = generate_unet_model(
            config.arch.num_dimensions,
            config.train.num_classes,
            input_layer_shape,
            output_layer_shape,
            config.train.activation,
            downsize_factor=2)

        return model

def generate_net_model(
    dimension, num_classes, input_shape, output_shape, activation, downsize_factor=2):
    img_input = Input(shape=input_shape)
    x = img_input
    # Encoder
    x = Conv2D(64, 3, 3, border_mode="same")(img_input)
    x = BatchNormalization()(x)
    x = Activation("relu")(x)
    x = MaxPooling2D(pool_size=(2, 2))(x)
    
    x = Convolution2D(128, 3, 3, border_mode="same")(x)
    x = BatchNormalization()(x)
    x = Activation("relu")(x)
    x = MaxPooling2D(pool_size=(2, 2))(x)
    
    x = Convolution2D(256, 3, 3, border_mode="same")(x)
    x = BatchNormalization()(x)
    x = Activation("relu")(x)
    x = MaxPooling2D(pool_size=(2, 2))(x)
    
    x = Convolution2D(512, 3, 3, border_mode="same")(x)
    x = BatchNormalization()(x)
    x = Activation("relu")(x)
    
    x = Convolution2D(1024, 3, 3, border_mode="same")(x)
    x = BatchNormalization()(x)
    x = Activation("relu")(x)
    
    # Decoder
    x = Convolution2D(512, 2, 2, border_mode="same")(x)
    x = BatchNormalization()(x)
    x = Activation("relu")(x)
    
    x = UpSampling2D(size=(2, 2))(x)
    x = Convolution2D(256, 2, 2, border_mode="same")(x)
    x = BatchNormalization()(x)
    x = Activation("relu")(x)
    
    x = UpSampling2D(size=(2, 2))(x)
    x = Convolution2D(128, 2, 2, border_mode="same")(x)
    x = BatchNormalization()(x)
    x = Activation("relu")(x)
    
    x = UpSampling2D(size=(2, 2))(x)
    x = Convolution2D(64, 2, 2, border_mode="same")(x)
    x = BatchNormalization()(x)
    x = Activation("relu")(x)
    
    x = Convolution2D(num_classes, 1, 1, border_mode="valid")(x)
    print(img_input.shape )
    x = Reshape((48*48, num_classes))(x)
    x = Activation("softmax")(x)
    model = Model(img_input, x)

    return model

and the error is 

load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')

ValueError: You are trying to load a weight file containing 0 layers into a model with 19 layers.

**Comment by ravikyram** [comment]
@elmahdy27 

Please, fill [issue template.](https://github.com/tensorflow/tensorflow/issues/new/choose).Please, let us know which TF version you are using.

Request you to share colab link or simple standalone code with proper indentation and supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by elmahdy27** [comment]
tensorboard==1.8.0
tensorflow==1.8.0
tensorflow-gpu==1.8.0
tensorflow-tensorboard==1.5.0

**Comment by ravikyram** [comment]
@elmahdy27 

TF 1.x is not actively supported. Can you please switch to TF 2.x latest versions for better performance.Please, try with TF 2.3 latest released version and let us know if the problem still persists. Thanks!

**Comment by elmahdy27** [comment]
same problem

**Comment by ravikyram** [comment]
@elmahdy27 

Can you share colab link or standalone code with proper indentation to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by elmahdy27** [comment]
https://github.com/NIC-VICOROB/SUNet-architecture this is the code i just changed the Ronneberger file, sorry upload internet in my country sucks i can't upload the dataset nor the h5 files

**Comment by elmahdy27** [comment]
it is related to the h5 file
