### ISSUE TITLE
is it possible tensorflow-gpu  on RK3399 mali t-860?

### ISSUE THREAD

**Issue by xgate1** [tensorflow/tensorflow#43807]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): LUbuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: RK3399 
- TensorFlow installed from (source or binary): pip3
- TensorFlow version: tensorflow 1.14(cpu)
- Python version: python3.5
- Installed using virtualenv? pip? conda?: pip3
- Bazel version (if compiling from source): none
- GCC/Compiler version (if compiling from source): gcc 5.5
- CUDA/cuDNN version: none
- GPU model and memory: mali t-860

hi.

My problem is running time is too long tensorflow(cpu version)
so, i try to install tensorflow-gpu on RK3399  GPU- mali t-860 (ARM)

but i can't install yet. 
is it possible? 

if possible how to install it?

Thank you

**Comment by terryheo** [comment]
https://www.tensorflow.org/install/source#tested_build_configurations these versions are for x86_64 devices.
For ARM build, you might need to build it by yourself.

If you want to try TFLite, check followings.
- https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package#alternative-build-with-bazel-experimental
- https://www.tensorflow.org/lite/guide/build_arm64
