### ISSUE TITLE
TypeError in "Bidirectional.compute_output_shape"

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [tensorflow/tensorflow#43816]
Hello,

While analyzing Tensorflow on SonarCloud I saw what looks like an error in [`tensorflow/python/keras/layers/wrappers.py`](https://github.com/tensorflow/tensorflow/blob/d6426459bca2971b611ca9773858e55f6cc1a9af/tensorflow/python/keras/layers/wrappers.py#L522):

<img width="1899" alt="Screenshot 2020-10-06 at 14 11 27" src="https://user-images.githubusercontent.com/40498978/95199955-eb31ac00-07dd-11eb-8bee-2a0c006ed40f.png">

You can see the issue in SonarCloud [here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_tensorflow&issues=AXT60Og4BMD9OHnI8p_E&open=AXT60Og4BMD9OHnI8p_E).

After reviewing the code myself I can indeed see that `state_shape` will have the type `tuple`, and using the operator `+` on a `list` and a `tuple` will fail with the exception:
> TypeError: can only concatenate list (not "tuple") to list

Here is the flow which leads to this issue:
```
output_shape = tuple(output_shape.as_list())  # output_shape is a tuple
...
if self.return_state:
      state_shape = output_shape[1:]  # state_shape is a tuple
...
return [output_shape] + state_shape + copy.copy(state_shape)  # the expression "[output_shape] + state_shape" will fail
```

In case you have any question, suggestion or if you see a False Positive on SonarCloud you can reach out on [SonarSource community forum](https://community.sonarsource.com/).

A few notes in case you want to use SonarCloud:
* I am currently testing the python analyzer so [the project on SonarCloud](https://sonarcloud.io/dashboard?id=nicolas-harraudeau-sonarsource_tensorflow) will only show python issues, but SonarCloud can also analyze C/C++ code and other languages.
* SonarCloud can also import pylint issues in case you want to use a rule SonarCloud does not already provide. Note however that pylint rules and SonarCloud rules are implemented differently. You might see new issues with SonarCloud, or less issues in some cases (we try to avoid False Positives as much as possible).
* It is free for open-source projects.

**Comment by Saduf2019** [comment]
@nicholasbutlin 
Please share your tf version as you have not filled in the issue template.

**Comment by nicholasbutlin** [comment]
> @nicholasbutlin
> Please share your tf version as you have not filled in the issue template.

Hi - Not me this time! Think this is for someone else...

**Comment by nicolas-harraudeau-sonarsource** [comment]
Hi @Saduf2019. The bug I am describing here is directly in the master branch. I didn't check if it was released in a specific version of tensorflow.

I read the template but it doesn't seem to apply in this case. I am not describing a runtime issue but rather a bug visible in the code itself.

**Comment by mihaimaruseac** [comment]
I think this might be a leftover from Py2. Let's try to convert both sides of `+` to list?

**Comment by bhack** [comment]
A list of tuples?

**Comment by Saduf2019** [comment]
@nicolas-harraudeau-sonarsource 
Is this still an issue.

**Comment by nicolas-harraudeau-sonarsource** [comment]
Hi @Saduf2019,
As far as I can see the code remained the same, so [the bug is still there](https://github.com/tensorflow/tensorflow/blob/574463afb8581ca65988aee0ce1c956b4614e061/tensorflow/python/keras/layers/wrappers.py#L525). The same pattern I described earlier is visible:

```
output_shape = tuple(output_shape.as_list())  # output_shape is a tuple
...
if self.return_state:
      state_shape = output_shape[1:]  # state_shape is a tuple
...
return [output_shape] + state_shape + copy.copy(state_shape)  # the expression "[output_shape] + state_shape" will fail
```
