### ISSUE TITLE
Failed to load the native TensorFlow runtime

### ISSUE THREAD

**Issue by Marouaneghoulami** [tensorflow/tensorflow#43815]
Im on Windows10
Python 3.7.7
Tensorflow 2.2
Keras 2.4.3

when i run
`from tensorflow.keras.datasets import mnist`

i get 

![image](https://user-images.githubusercontent.com/28235664/95198114-98062c00-07d2-11eb-887b-4a787dafaf19.png)
![image](https://user-images.githubusercontent.com/28235664/95198139-a3f1ee00-07d2-11eb-9ab7-578ab22b99dc.png)

**Comment by ravikyram** [comment]
@Marouaneghoulami 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).

Please, check Your CPU/Python is on 32 bits?Please, refer #36167 and see if it helps you.Thanks!

**Comment by Marouaneghoulami** [comment]
@ravikyram 

I will see and let you know.
Thanks.

**Comment by Marouaneghoulami** [comment]
@ravikyram 

Hi,
i installed :
**Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019**

and downgraded Numpy

> tensorflow 2.3.1 requires numpy<1.19.0,>=1.16.0

Now its all good, thanks
