### ISSUE TITLE
Duplicate condition in "is_square"

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [tensorflow/tensorflow#43817]
Hello,

While analyzing Tensorflow on SonarCloud I saw what looks like an error in [`tensorflow/python/ops/linalg/registrations_util.py`](https://github.com/tensorflow/tensorflow/blob/9648531c0bf5163de26e8688c017d58b3eb80405/tensorflow/python/ops/linalg/registrations_util.py#L59):

<img width="1863" alt="Screenshot 2020-10-06 at 14 23 29" src="https://user-images.githubusercontent.com/40498978/95201004-9a22b780-07df-11eb-919e-180242560a57.png">

You can see the issue in SonarCloud [here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_tensorflow&issues=AXT60PaoBMD9OHnI8qUK&open=AXT60PaoBMD9OHnI8qUK).

The condition `operator_a.is_square is not None and operator_a.is_square is not None` doesn't make sense as it checks twice the same thing. I guess what the developer intended was `operator_a.is_square is not None and operator_b.is_square is not None` but I can't be sure as I don't know this code base.

In case you have any question, suggestion or if you see a False Positive on SonarCloud you can reach out on [SonarSource community forum](https://community.sonarsource.com/).

A few notes in case you want to use SonarCloud:
* I am currently testing the python analyzer so [the project on SonarCloud](https://sonarcloud.io/dashboard?id=nicolas-harraudeau-sonarsource_tensorflow) will only show python issues, but SonarCloud can also analyze C/C++ code and other languages.
* SonarCloud can also import pylint issues in case you want to use a rule SonarCloud does not already provide. Note however that pylint rules and SonarCloud rules are implemented differently. You might see new issues with SonarCloud, or less issues in some cases (we try to avoid False Positives as much as possible).
* It is free for open-source projects.

**Comment by bhack** [comment]
Thanks but I think that it is hard to auto identify the "real" issue :wink: https://github.com/tensorflow/tensorflow/pull/43819

**Comment by nicolas-harraudeau-sonarsource** [comment]
Thanks for your rapid answer @bhack.
I'm not sure to understand. Do you mean that the message provided by SonarCloud was not describing the problem properly? Or that I shouldn't have suggested a fix? I hesitated before doing it as I didn't want to introduce a bug with my suggestion.

**Comment by bhack** [comment]
@nicolas-harraudeau-sonarsource No I just meant that it is a little bit more hard to automatically check that the required operation was on the 2nd arg (as hint).

**Comment by nicolas-harraudeau-sonarsource** [comment]
@bhack Yes you are totally right. That's why the message says "Correct **one of** the identical sub-expressions". Sadly static code analyzers cannot provide fixes in many cases, developers will not be out of jobs soon ;)

Did you find the highlight on the second value confusing? We could highlight the whole `and` expression but it would create some confusions in cases such as `(a and b) and (a and b)`. Developers would not understand right away which `and` operand we are talking about. I'm open to any suggestion.

**Comment by bhack** [comment]
I think it is ok, we will need advanced NLP models for this :wink: At some point Tensorflow models could generate this type of hints on its own code.
