### ISSUE TITLE
Exceptions not raised because the "raise" keyword is missing in a few places

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [tensorflow/tensorflow#43818]
Hello,

While analyzing Tensorflow on SonarCloud I saw what looks like two errors in [`tensorflow/python/tpu/tpu_embedding.py`](https://github.com/tensorflow/tensorflow/blob/c6c6d90b29d4f9ccf501520ae691ccd58f0bbd85/tensorflow/python/tpu/tpu_embedding.py#L1639) and [`tensorflow/python/keras/losses.py`](https://github.com/tensorflow/tensorflow/blob/090f260aab3dab00bcdf0232962e753bb9fab696/tensorflow/python/keras/losses.py#L183):

<img width="1846" alt="Screenshot 2020-10-06 at 14 44 31" src="https://user-images.githubusercontent.com/40498978/95203471-18cd2400-07e3-11eb-98f2-288b909ffe28.png">

<img width="1834" alt="Screenshot 2020-10-06 at 14 44 48" src="https://user-images.githubusercontent.com/40498978/95203495-1ff43200-07e3-11eb-9d15-b7830b794c7f.png">

You can see both issues in SonarCloud [here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_tensorflow&issues=AXT60QzlBMD9OHnI8rBe&open=AXT60QzlBMD9OHnI8rBe) and [here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_tensorflow&issues=AXT60O-aBMD9OHnI8qI7&open=AXT60O-aBMD9OHnI8qI7).

The problem is pretty simple: exceptions are created but not raised because the `raise` keyword is missing. This is a pretty common mistake in python ;)

In case you have any question, suggestion or if you see a False Positive on SonarCloud you can reach out on [SonarSource community forum](https://community.sonarsource.com/).

A few notes in case you want to use SonarCloud:
* I am currently testing the python analyzer so [the project on SonarCloud](https://sonarcloud.io/dashboard?id=nicolas-harraudeau-sonarsource_tensorflow) will only show python issues, but SonarCloud can also analyze C/C++ code and other languages.
* SonarCloud can also import pylint issues in case you want to use a rule SonarCloud does not already provide. Note however that pylint rules and SonarCloud rules are implemented differently. You might see new issues with SonarCloud, or less issues in some cases (we try to avoid False Positives as much as possible).
* It is free for open-source projects.

**Comment by mihaimaruseac** [comment]
That's a good find. Please tag me in all similar issues from SonarSource.

**Comment by nicolas-harraudeau-sonarsource** [comment]
Hi @mihaimaruseac and thank you.
Do you mean any issue found by SonarCloud? I recently reported #43817, #43813 and #43816.
I didn't report every issue our analyzer categorized as a bug because I didn't have time. You can take a look at the list of bugs [here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_tensorflow&languages=py&open=AXT60OurBMD9OHnI8qEG&resolved=false&types=BUG). It's quite short.

You might also be interested in some code smell issues such as:
* [this one](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_tensorflow&issues=AXT60RJRBMD9OHnI8rFL&open=AXT60RJRBMD9OHnI8rFL), it looks to me like a classic modification of a default argument which could lead to a bug one day.
* [or this one](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_tensorflow&issues=AXT60Q4FBMD9OHnI8rCo&open=AXT60Q4FBMD9OHnI8rCo). I think that this is actually a bug. `len` cannot be called on an integer, so `len(len(...))` will fail.
We design our code analyzers to be quite conservative and avoid categorizing as bug things which might be code smells. That way developers are not disturbed with False Positives and trust our tools.

At SonarSource we validate our static code analyzers using popular open source projects, such as Tensorflow, to make sure that we raise valuable issues and have not False Positives. This is how I saw these bugs.

As mentioned above, if you see any False Positives or if you have a question or feedback don't hesitate to share it [on the community forum](https://community.sonarsource.com/).

**Comment by bhack** [comment]
@mihaimaruseac Let me know. I can pick some of these.

**Comment by mihaimaruseac** [comment]
Thank you @nicolas-harraudeau-sonarsource 

@bhack sure, thank you. I have so many things to do and team is severly downsized, so any help is great
