### ISSUE TITLE
Support tf.keras.metrics.MeanIoU on TPU

### ISSUE THREAD

**Issue by edwardyehuang** [tensorflow/tensorflow#43810]
Please add support for tf.keras.metrics.MeanIoU on TPU

**Comment by sachinprasadhs** [comment]
Please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/f4a2ee991f57f67f240e881034d26870/github_54125.ipynb) with a working example of `tf.keras.metrics.MeanIoU` on colab TPU. Thanks!

**Comment by edwardyehuang** [comment]
> 

lol, I totally forgot this issue, since I solved this issue immediately (by motified some TensorFlow codes) after I reported it.

Close this isuss, and thx for your reply :)  @sachinprasadhs
