### ISSUE TITLE
Unable to build tflite for aarch64

### ISSUE THREAD

**Issue by nicesj** [tensorflow/tensorflow#43811]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): N/A
- TensorFlow version: master branch (latest)
- Python version: 3.8
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): Android NDK toolchain 21.1.6352462 and GCC aarch64 toolchain 8.3 (2019.3)
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
build_aarch64_lib.sh failed because it tries to build x86 cpuid source files

**Provide the exact sequence of commands / steps that you executed before running into the problem**
./build_aarch64_lib.sh

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

https://github.com/tensorflow/tensorflow/commit/81ddb09077702debafd61e8ef4312f5806348266

After the above patch is merged, aarch64 build failed.
if you need any further information please let me know.

**Comment by poperson1205** [comment]
I have the same issue

**Comment by terryheo** [comment]
Confirmed. Preparing a fix.

**Comment by nicesj** [comment]
I confirmed that the build is successfully done.
