### ISSUE TITLE
why does tensorflow import_pb_to_tensorboard.py tool require the pb file to be a fixed name "saved_model.pb"?

### ISSUE THREAD

**Issue by cuixiaom** [tensorflow/tensorflow#43825]
I tried to use import_pb_to_tensorboard.py tool come with Tensorflow, but when I used the tool to process my pb file, it always failed, after check the source code of the tool, I found the name of pb file has to be "saved_model.pb". I am wondering why the tool requires a fixed .pb file instead of any name users preferred?

**Comment by bhack** [comment]
I think it process a model_dir not the pb file right? See https://github.com/tensorflow/tensorflow/issues/37814

**Comment by cuixiaom** [comment]
yes, you can give path of the dir or the saved_model.pb file as input, but my question is why the name of pb file has to be "saved_model.pb"? if you give a path of a dir, which doesn't have a pb file named "saved_model.pb", then the tool will pop up an error. Just wonder why the tool requires the name of pb file to be "saved_model.pb", and which is not mentioned in help of the tool.

**Comment by bhack** [comment]
What I see Is that it support only model_dir args

**Comment by cuixiaom** [comment]
yes, but it implicitly requires there is pb file named "saved_model.pb" in the model_dir.

**Comment by bhack** [comment]
It was generally the automatic name with save and load with model_dir for Savedmodel format.

**Comment by cuixiaom** [comment]
why not remove this limit so that the tool can use "saved_model.pb" as default name if users don't specify a pb file name, but if users specify a pb file, the tool should accept the pb file users specified instead of popping an error information? I think in this way, the tool is more robust and easier to use.

**Comment by bhack** [comment]
@cuixiaom I think you can propose a PR so we could collect some feedbacks.

**Comment by cuixiaom** [comment]
sounds good! thanks!

**Comment by Saduf2019** [comment]
@cuixiaom 
Please move the issue to closed status if resolved.

**Comment by cuixiaom** [comment]
will propose a PR for this issue.
