### ISSUE TITLE
Enable multiple input pipelines with a single machine, MultiWorkerMirroredStrategy's experimental_distribute_datasets_from_function

### ISSUE THREAD

**Issue by jeisinge** [tensorflow/tensorflow#43832]
**System information**
- TensorFlow version (you are using): TF 2.3
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
`tf.distribute.experimental.MultiWorkerMirroredStrategy` provides an easy way to perform multi-GPU training on a single instance.  `tf.distribute.experimental.MultiWorkerMirroredStrategy.experimental_distribute_datasets_from_function()` allows for manually sharding the input dataset.  This function gets passed a `tf.distribute.InputContext`.

On a single-machine, 8 GPU setup, the function gets called exactly once with the following `input_context`:
```python3
tf.distribute.InputContext(
    num_input_pipelines=1, input_pipeline_id=0, num_replicas_in_sync=8
)
```
The result is that on a single machine, we cannot shard the dataset manually.

Instead, it would be great if TensorFlow saw a single machine as having 8 differnet input pipelines --- one for each GPU.  The result would enable sharding differently for each GPU.

**Will this change the current api? How?**
Either the default behavior would change or a flag might need to be added to `MultiWorkerMirroredStrategy` or `experimental_distribute_datasets_from_function` to specify this new behavior.

**Who will benefit with this feature?**
Anyone who requires multiple GPUs to train their models, but doesn't want the extra sophistication of running on multiple machines.

**Any Other info.**
It would be great if each input pipeline ran as a seperate python application.  That would enable multi-CPU out of the box if the dataset was designed for single CPU initially.

**Comment by nikitamaia** [comment]
Hi @jeisinge, `MultiWorkerMirroredStrategy` actually is designed for training on multiple machines, and not a single instance.
`MirroredStrategy` is the strategy for the scenario of a single machine with multiple GPUs.

Can you provide a little more information about this feature? Specifically, why are you interested in sharding the data differently for each GPU? `MirroredStrategy` is a synchronous training strategy, so I am not clear on why you would want to do a different sharding of the dataset for each GPU. More context here on your use case would be helpful.

Additionally, I'm confused about the benefit here, as `MirroredStrategy` already allows for training on multiple GPUs without the extra sophistication of running on multiple machines. Additionally, TF runs on multiple CPU cores out of the box, and `MultiWorkerMirroedStrategy` can be used to distribute training across multiple machines that are CPU only.

**Comment by jeisinge** [comment]
Howdy @nikitamaia, great questions.  I should have provided additional context.  First, I am working through Python/TF 2 as quickly as I possibly can --- if I say something incorrectly, please correct my understanding!

### Why `MultiWorkerMirroredStrategy`?
We first started with `MirroredStrategy`, but ran into the warning ` WARNING:tensorflow:Efficient allreduce is not supported for 23 IndexedSlices`.  After reviewing https://github.com/tensorflow/tensorflow/issues/41898 and additional documentation/YouTubes, it appears that `MultiWorkerMirroredStrategy` has additional optimizations.  When we run, `MultiWorkerMirroredStrategy` outputs information about being optimized for one machine.   And, these optimizations appear to work better for us than `MirroredStrategy`.  Of course, if things change in TF 2.4, than we will have to change with them!

### Why control the sharding?
Our dataset is comes from parquet files that are partioned by day.  In each file, we might have a couple million examples.  And, the number of files are just a couple per GPU.  Due to this, we cannot shard by file --- or else some GPUs might get one file and other might get four files.  Instead, we shard by batches within the parquet file's row groups.  This enables each GPU to get an equal amount of examples from each day of data --- with no repeats.

The additional issue we run into with just having one Input Pipeline is that our Input Pipeline is too slow to feed all of the GPUs.  We have CPU operations like WordPiece that, to my knowledge, cannot be parallelized on the GPU easily.  The result is that on our trains, one CPU is pegged at 100% while the other 30 are doing nothing.  Again, this is fine when we run with one GPU --- the CPU operations can feed one GPU just fine with one CPU.

**Comment by nikitamaia** [comment]
Thanks for the extra context. Just to clarify my understanding a bit more, is the central issue here that with your current set up, the input pipeline is a bottleneck? The CPU takes too much time to prepare a batch and send it to the GPUs for training and hence the GPUs sit idle at the end of each training step while the CPU is busy prepping the next batch?

**Comment by jeisinge** [comment]
The situation is that we would like to be able to train faster on a relatively simple setup of a single machine, multi-GPU.  There are two complications.  First, `MirroredStrategy` has issues with our preprocessing that utilizes `SparseTensor.`  The second issue is the one you described - ensuring the GPUs are fully utilized.

The first issue is solved by utilizing `MultiWorkerMirroredStrategy`.

However, `MultiWorkerMirroredStrategy` does not appear to support `experimental_distribute_datasets_from_function`.  The result is that we are required to have _one_ data input pipeline that has enough throughput to support multiple GPUs.  This second, additional requirement is complicated by Python's GIL.

Make sense?  And, of course, if I am looking at the solution space wrong, please let me know --- I am all ears!

**Comment by nikitamaia** [comment]
`MultiWorkerMirroredStrategy` does support [experimental_distribute_datasets_from_function](https://www.tensorflow.org/api_docs/python/tf/distribute/experimental/MultiWorkerMirroredStrategy#experimental_distribute_datasets_from_function). Did you run into problems with this?

As for GPU utilization, have you had a chance to look at any of the performance guides? There is one for [optimizing input pipeline performance](https://www.tensorflow.org/guide/data_performance) and [analyzing input pipeline performance](https://www.tensorflow.org/guide/data_performance_analysis). There is also a guide for [debugging GPU performance in general](https://www.tensorflow.org/guide/gpu_performance_analysis). The guides for input pipelines also show how to parallelize data extraction and data transformations, and how to use the TF Profiler to get a more precise sense of what part of the pipeline is the bottleneck. Let me know if these are helpful.

**Comment by jeisinge** [comment]
I agree that `MultiWorkerMirroredStrategy` works with `experimental_distribute_datasets_from_function` on a multi-GPU system.  It just doesn't work as I expected.  In particular, it doesn't appear to do anything different than processing a regular dataset.

During processing of a regular Dataset via `experimental_distribute_dataset`, one input pipeline is created.  The output of this dataset is distributed to multiple GPUs.

`experimental_distribute_datasets_from_function` appears to have the exact same behavior.

It is my understanding that `experimental_distribute_datasets_from_function` was designed to allow manually sharding of the dataset.  My expectation was that I would have this behavior on a multi-GPU system.  Specifically, I expected `experimental_distribute_datasets_from_function` to call the `dataset_fn` once per GPU.  This would allow me to manually shard my dataset.  However, my `dataset_fn` is only called once.

I do not believe this is a defect because the documentation states,

> `dataset_fn` will be called once for each worker in the strategy.

My understanding is that on a Multi-GPU system, TF views it as a one worker with 8 GPUs, not eight workers with one GPU.  So, I believe this to be working as designed.

My feature request is to enable being able to manually shard per GPU on a multi-GPU system.

Make sense?

And, thank you for the links.  I completely get the reason why my data pipeline is slow --- Python's GIL doesn't allow for my Python/CPU-based transform to parallelize over multiple CPUs.  There are a number of solutions to this.

**Comment by yuefengz** [comment]
Hello @jeisinge , the API doc says `Each replica on that worker will dequeue one batch of inputs from the local Dataset (i.e. if a worker has two replicas, two batches will be dequeued from the Dataset every step).` So `tf.distribute` will distribute your dataset across different GPUs. Our dataset pipeline has been optimized for multi-GPUs and it will try to utilize your machine resources to not bottleneck the training. So if you see performance issues, it would be useful if you can show us a profile. As for the GIL overhead, I am wondering whether the GIL overhead comes from?

**Comment by jeisinge** [comment]
Correct - I believe TensorFlow is working as documented.  However, this design does not work for our needs.  The profiler won't be useful because the operations that limit our throughput are performed before the TF data pipeline.

Specifically, we have operations that cannot _easily_ be optimized for TensorFlow.  These operations run in Python where the GIL is used and, thus, run on a single CPU.  The result is that our data pipeline works well for the situation of 1 GPU:1 CPU, but, we still only use one CPU when we scale up to 8 GPUs on a single system --- effectively 8 GPU:1 CPU.  Ideally, as we scale up GPUs, we also scale up python's CPU usage.

Does that GIL restriction make sense? Is there another work around?

One example of transformations that are not ideal for TensorFlow text processing --- https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/sequence.py , BERT tokenization, etc.

To work around these, we have attempted a couple of workarounds: rewriting preprocessed data, utilizing newer TF Text functionality, and only running on one GPU.  None of these are ideal because they limit batch size, iteration speed, increase storage management requirements, do not fully utilize underlying hardware, or are slower.

This feature request is to be able to take a data pipeline (pre-`tf.data` and `tf.data`) that runs well for 1 GPU:1 CPU and ensure it also runs well on an 8-GPU by enabling the pre-`tf.data` pipeline to utilize at least 8 CPUs.  This can be accomplished by running one data pipeline per GPU in separate processes.

**Comment by OwlWisdom** [comment]
> Hi @jeisinge, `MultiWorkerMirroredStrategy` actually is designed for training on multiple machines, and not a single instance.
> `MirroredStrategy` is the strategy for the scenario of a single machine with multiple GPUs.
> 
> Can you provide a little more information about this feature? Specifically, why are you interested in sharding the data differently for each GPU? `MirroredStrategy` is a synchronous training strategy, so I am not clear on why you would want to do a different sharding of the dataset for each GPU. More context here on your use case would be helpful.
> 
> Additionally, I'm confused about the benefit here, as `MirroredStrategy` already allows for training on multiple GPUs without the extra sophistication of running on multiple machines. Additionally, TF runs on multiple CPU cores out of the box, and `MultiWorkerMirroedStrategy` can be used to distribute training across multiple machines that are CPU only.

Please help! My Question:  "The MultiWorkerMirroredStrategy can only be uesd to distribute training across machines that are CPU only"?   Why the startegy does not support multi machines with multi GPUs ?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by jacob-talroo** [comment]
We can close.  We have moved on to Keras 3 / JAX.
