### ISSUE TITLE
RPC retries do not work on Istio

### ISSUE THREAD

**Issue by porridge** [tensorflow/tensorflow#43838]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes, but it fits on one screen
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): stock `tensorflow/tensorflow:2.2.0` docker image on k8s
- TensorFlow installed from (source or binary): binary (docker image)
- TensorFlow version (use command below): `v2.2.0-rc4-8-g2b96f3662b 2.2.0`
- Python version: `Python 3.6.9`

**Describe the current behavior**

When running a two-worker job *in an istio-enabled namespace* on kubernetes, tensorflow will crash in `tf.keras.layers.Dense()` with `tensorflow.python.framework.errors_impl.UnavailableError` with a very high probability *if worker `0` is not available yet at the moment where worker `1` sends an RPC to it*. Note that in a distributed environment perfect synchronization of tasks is impossible to achieve due to scheduling contraints, network issues, etc. In my experiments the crashed happend when worker `0` started executing more than a second later than worker `1`. The example code injects an artificial 10 second delay when running on task `1`.

**Describe the expected behavior**

Worker 1 should retry for a reasonable amount of time (a minute or so?) until worker 0 comes up. This is indeed what happens when *not* running on Istio (e.g. when istio sidecar injection is disabled for the pods by changing the `sidecar.istio.io/inject` annotation in attached manifest to `"false"`) then this example job succeeds every time.

My suspicion is that the retry code (either in gRPC layer or in tensorflow itself) gets confused in case there is an envoy transparent proxy in between the workers:
- when there is no istio, the process gets a `-ECONNREFUSED`, and knows how to retry this,
- where there is istio, the process establishes a connection (to the local transparent proxy) just fine, but then the proxy reports back a connection error in a higher layer, e.g.:
```
':status', '200'
'content-type', 'application/grpc'
'grpc-status', '14'
'grpc-message', 'upstream connect error or disconnect/reset before headers. reset reason: connection failure'
'server', 'envoy'
'x-envoy-upstream-service-time', '36'
```
and the resulting exception looks different enough for the retry code to not kick in, causing an immediate crash.

**Standalone code to reproduce the issue**

Here is a kubernetes manifest sufficient to reproduce the issue. This includes the code, which just creates a model and attempts to compile it.

**Note:** this needs to be applied against a namespace in which istio sidecar injection is enabled (with `kubectl apply -n YOUR_NS -f` or similar).

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: script
data:
  mnist-tensorflow.py: |
    from __future__ import absolute_import, division, print_function, unicode_literals

    import logging
    import time
    import sys

    import tensorflow as tf


    def main(pod_name):
        logging.info("Started!")
        tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.DEBUG)

        logging.info("pod name: [%s]", pod_name)
        if pod_name.endswith('0'):
            logging.warning("sleeping 10 seconds")
            time.sleep(10)

        logging.warning("proceeding")
        strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()
        logging.warning("strategy created")

        with strategy.scope():
            model = tf.keras.Sequential(
                [
                    tf.keras.layers.Conv2D(32, 3, activation="relu", input_shape=(28, 28, 1)),
                    tf.keras.layers.MaxPooling2D(),
                    tf.keras.layers.Flatten(),
                    tf.keras.layers.Dense(64, activation="relu"),
                    tf.keras.layers.Dense(10),
                ]
            )
            model.compile(
                loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                optimizer=tf.keras.optimizers.SGD(learning_rate=0.5, momentum=0.1),
                metrics=["accuracy"])

        logging.info("Success!")


    if __name__ == "__main__":
        logging.basicConfig(format='%(asctime)s.%(msecs)03d %(levelname)-8s %(message)s', level=logging.INFO,
                            datefmt='%Y-%m-%d %H:%M:%S')
        main(sys.argv[1])
---
apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: tf-job-mnist
spec:
  cleanPodPolicy: None  # For easy debugging
  tfReplicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/logLevel: "debug"
            sidecar.istio.io/inject: "true"
        spec:
          containers:
          - name: tensorflow
            image: tensorflow/tensorflow:2.2.0
            command: ["python", "-u", "/tmp/script/mnist-tensorflow.py", "$(POD_NAME)"]
            env:
            - name: TF_CPP_MIN_LOG_LEVEL
              value: "0"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            volumeMounts:
            - name: script
              mountPath: /tmp/script
          volumes:
          - name: script
            configMap:
              name: script
```

**Other info / logs**

Here is the python stack trace that I encounter. Sometimes the error message varies slightly.
```
Traceback (most recent call last):
  File "/tmp/tests/jobs/mnist-tensorflow.py", line 44, in <module>
    main(sys.argv[1])
  File "/tmp/tests/jobs/mnist-tensorflow.py", line 30, in main
    tf.keras.layers.Dense(10),
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 456, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py", line 129, in __init__
    self.add(layer)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 456, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py", line 198, in add
    layer(x)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 897, in __call__
    self._maybe_build(inputs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2416, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/layers/convolutional.py", line 163, in build
    dtype=self.dtype)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 577, in add_weight
    caching_device=caching_device)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 743, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 141, in make_variable
    shape=variable_shape if variable_shape else None)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 259, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 220, in _variable_v1_call
    shape=shape)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 66, in getter
    return captured_getter(captured_previous, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1767, in creator_with_resource_vars
    return self._create_variable(next_creator, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 610, in _create_variable
    values.SyncOnReadVariable, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/values.py", line 694, in create_mirrored_variable
    value_list = real_mirrored_creator(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 602, in _real_mirrored_creator
    v = next_creator(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 198, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 2598, in default_variable_creator
    shape=shape)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 263, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1434, in __init__
    distribute_strategy=distribute_strategy)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1567, in _init_from_args
    initial_value() if init_from_fn else initial_value,
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/collective_all_reduce_strategy.py", line 386, in initial_value_fn
    collective_instance_key)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/collective_ops.py", line 176, in broadcast_recv
    communication_hint=communication_hint.lower())
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/gen_collective_ops.py", line 57, in collective_bcast_recv
    _ops.raise_from_not_ok_status(e, name)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6653, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnavailableError: upstream connect error or disconnect/reset before headers. reset reason: connection failure
Additional GRPC error information:
{"created":"@1601905369.391893191","description":"Error received from peer ipv4:192.168.197.248:2222","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"upstream connect error or disconnect/reset before headers. reset reason: connection failure","grpc_status":14} [Op:CollectiveBcastRecv]
```

The interesting pieces of envoy logs are between `2020-10-05T13:42:49.336` (when TF makes the call) and `2020-10-05T13:42:49.391` (where it crashes):
- [fail-log-pod.tf-job-mnist-worker-1.istio-proxy.txt](https://github.com/tensorflow/tensorflow/files/5338766/fail-log-pod.tf-job-mnist-worker-1.istio-proxy.txt) lines 30923-31015
- [fail-log-pod.tf-job-mnist-worker-0.istio-proxy.txt](https://github.com/tensorflow/tensorflow/files/5338769/fail-log-pod.tf-job-mnist-worker-0.istio-proxy.txt) lines 31080-31423

TF logs are short:
- [fail-log-pod.tf-job-mnist-worker-1.tensorflow.txt](https://github.com/tensorflow/tensorflow/files/5338764/fail-log-pod.tf-job-mnist-worker-1.tensorflow.txt)
- [fail-log-pod.tf-job-mnist-worker-0.tensorflow.txt](https://github.com/tensorflow/tensorflow/files/5338767/fail-log-pod.tf-job-mnist-worker-0.tensorflow.txt)

For completeness, mostly irrelevant:
- [fail-log-pod.tf-job-mnist-worker-1.istio-validation.txt](https://github.com/tensorflow/tensorflow/files/5338765/fail-log-pod.tf-job-mnist-worker-1.istio-validation.txt)
- [fail-log-pod.tf-job-mnist-worker-0.istio-validation.txt](https://github.com/tensorflow/tensorflow/files/5338768/fail-log-pod.tf-job-mnist-worker-0.istio-validation.txt)

**Comment by nikitamaia** [comment]
Hi @porridge this might be related to #42498. Can you take a look at the [last comment](https://github.com/tensorflow/tensorflow/issues/42498#issuecomment-702416224) in that thread and let me know if it's helpful?

**Comment by porridge** [comment]
It's related, but the comment it not very useful. I don't think doing the retries in high-level user code is a proper fix.
Also please note that TF does attempt to retry (as proven by my repro case not failing in non-istio environment), it's just that the retry code is not kicking in when an envoy proxy is involved.

I already have a dirty workaround of using a `retryPolicy: OnFailure`, but the point of this ticket is to fix this properly.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
