### ISSUE TITLE
tf_record issue while following tutorial 

### ISSUE THREAD

**Issue by abhishekbalu** [tensorflow/tensorflow#43835]
ValueError: Shape must be rank 0 but is rank 1 for '{{node DecodeJpeg}} = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false](ParseSingleExample/ParseExample/ParseExampleV2)' with input shapes: [?].

using this tutorial: https://keras.io/examples/keras_recipes/tfrecord/

**Comment by amahendrakar** [comment]
@abhishekbalu,
On running the Colab Notebook, I am facing a different error due to the invalid `GCS_PATH`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/82868d75e0f6e51d380ec48bc5242e7b/43835.ipynb#scrollTo=YLvGnlUzw8gM). 

Could you please provide the Python script/notebook you are running along with the dataset, so that we can reproduce the issue on our end. Thanks!

**Comment by abhishekbalu** [comment]
the following is my [gist](https://colab.research.google.com/drive/1RIwxIM0lroyhUmGe_HWeqFq0dq7ZS_cn?usp=sharing). The link to [DATASET](https://drive.google.com/file/d/1gBSp2mhX4p6jlAoxBR55pGX0zeb4dg0q/view?usp=sharing). I am using the [nuscene](https://nuscenes.org/) DATASET

**Comment by abhishekbalu** [comment]
Hi any updates on this i am kind of stuck here for a week. Please help me out.

**Comment by amahendrakar** [comment]
@abhishekbalu,
Sorry for the delayed response. I do not have access to the drive link, could you please grant the required permissions to view the files. Thanks!

**Comment by abhishekbalu** [comment]
sorry for the delay. [dataset](https://drive.google.com/file/d/1gBSp2mhX4p6jlAoxBR55pGX0zeb4dg0q/view?usp=sharing) and [gist](https://colab.research.google.com/drive/1RIwxIM0lroyhUmGe_HWeqFq0dq7ZS_cn?usp=sharing)  these are sharable link

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/a43bdce0d63f4d7c0050fc82f8388a30/43835.ipynb). Thanks!

**Comment by amahendrakar** [comment]
@abhishekbalu,
Please check [this comment](https://stackoverflow.com/a/47707733) from a similar StackOverflow query and let us know if it helps. Thanks!

**Comment by rmothukuru** [comment]
@abhishekbalu,
Can you please respond to the @amahendrakar's comment. Thanks!

**Comment by abhishekbalu** [comment]
I am passing a tensor and not a scalar but still getting this error

**Comment by jvishnuvardhan** [comment]
@abhishekbalu Can you please share simple dataset. Current dataset is too big (7 GB). Thanks!
