### ISSUE TITLE
"No gradients provided" with GradientDescentOptimizer if not using float variable

### ISSUE THREAD

**Issue by NikhilBartwal** [tensorflow/tensorflow#43845]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): pip
- Python version: 3.7.6
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version:  10.1
- GPU model and memory: Nvidia Geforce 940MX

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
The gradient descent optimizer gives "No gradients provided" error when minimizing it, if the variables used in the custom loss function are not explicitly defined as float

**Describe the expected behavior**
It should optimize the variable as expected.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
import numpy as np
import tensorflow as tf
from tensorflow.python.training import gradient_descent
x = tf.Variable(np.array([[1,1],[2,2]]), trainable=True)
def my_loss():
    square = tf.math.square(x)
    return square
opt = gradient_descent.GradientDescentOptimizer(0.1)
for i in range(20):
    print([x.numpy(), my_loss().numpy()])
    train = opt.minimize(my_loss, var_list=[x])
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-165-a3994377e283> in <module>
      1 for i in range(20):
      2     print([x.numpy(), y.numpy(), my_loss().numpy()])
----> 3     train = opt.minimize(my_loss, var_list=[x,y])

/opt/conda/lib/python3.7/site-packages/tensorflow/python/training/optimizer.py in minimize(self, loss, global_step, var_list, gate_gradients, aggregation_method, colocate_gradients_with_ops, name, grad_loss)
    408           "No gradients provided for any variable, check your graph for ops"
    409           " that do not support gradients, between variables %s and loss %s." %
--> 410           ([str(v) for _, v in grads_and_vars], loss))
    411 
    412     return self.apply_gradients(grads_and_vars, global_step=global_step,

ValueError: No gradients provided for any variable, check your graph for ops that do not support gradients, between variables ["<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=\narray([[1, 1],\n       [2, 2]])>", "<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=\narray([[9.000003, 9.000003],\n       [9.000003, 9.000003]], dtype=float32)>"] and loss <function my_loss at 0x7f5f1c381680>.
```

**Comment by bhack** [comment]
Can you share a very minimal but complete example that we could copy, past and run to reproduce this?

**Comment by NikhilBartwal** [comment]
@bhack I've shared the reproducible code in the issue

**Comment by bhack** [comment]
`NameError: name 'y' is not defined`

**Comment by NikhilBartwal** [comment]
@bhack Sorry, my bad! I've updated the code. Thank You for looking into it!

**Comment by bhack** [comment]
I think the warning is more clear on tf-nightly:
```
WARNING:tensorflow:The dtype of the watched tensor must be floating (e.g. tf.float32), got tf.int64
WARNING:tensorflow:The dtype of the target tensor must be floating (e.g. tf.float32) when calling GradientTape.gradient, got tf.int64
WARNING:tensorflow:The dtype of the source tensor must be floating (e.g. tf.float32) when calling GradientTape.gradient, got tf.int64
````

**Comment by NikhilBartwal** [comment]
@bhack Thanks, that explains it i guess. One more thing, the watched tensor is `x` but what are the target and source tensors here?

**Comment by bhack** [comment]
They are the source and target of the gradient function
https://github.com/tensorflow/tensorflow/blob/917882bfa26c5f19275346e6c4b0a9fb845f6300/tensorflow/python/eager/backprop.py#L993-L1013
That is called in your minimize step:
https://github.com/tensorflow/tensorflow/blob/917882bfa26c5f19275346e6c4b0a9fb845f6300/tensorflow/python/training/optimizer.py#L475

**Comment by NikhilBartwal** [comment]
@bhack Thanks for the help, man! I will be closing the issue as it's resolved now.
