### ISSUE TITLE
Access to GPU memory usage

### ISSUE THREAD

**Issue by klicperajo** [tensorflow/tensorflow#43846]
**System information**
- TensorFlow version (you are using): TensorFlow 2.3.1
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
I would like an easy way to access current/peak GPU memory usage. The TF profiler only allows detailed analysis of a single run, while accessing (and saving) the memory usage would allow users to track and compare the resource consumption of multiple different runs and models. Both PyTorch (`torch.cuda.max_memory_allocated()`) and TensorFlow 1 (`tf.contrib.memory_stats.MaxBytesInUse()`) allow easy access to this, only TensorFlow 2 doesn't.

**Will this change the current api? How?**
Yes, it would add a method that returns current/peak GPU memory consumption.

**Who will benefit with this feature?**
Anyone caring about memory consumption differences (which are probably a lot of people).

**Any Other info.**
This has been discussed in the past, e.g. in https://github.com/tensorflow/serving/issues/1407 or https://stackoverflow.com/questions/59652889/how-to-get-the-exact-gpu-memory-usage-for-keras.

**Comment by mohantym** [comment]
Hi @klicperajo ! Have you checked [get_memory_usage](https://www.tensorflow.org/api_docs/python/tf/config/experimental/get_memory_usage) feature  from TF 2.7 ?

**Comment by klicperajo** [comment]
Indeed, this seems to have been added already in [TensorFlow 2.4](https://www.tensorflow.org/versions/r2.4/api_docs/python/tf/config/experimental/get_memory_usage)!

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
