### ISSUE TITLE
MatMul operation would cost 4ms

### ISSUE THREAD

**Issue by zengfancy** [tensorflow/tensorflow#4385]
By stats the time costs using stats_collector_ in Executor class, I found that a matrix multiply operation of 150*150 matrix with a 150 vector would cost 4ms on CPU, And a 3 layers of DNN would cost 20ms, is that expected?

**Comment by andydavis1** [comment]
4ms for such a small Matrix-Vector product sounds high. Can you include more information about your environment, a reproducible test case, and a timeline?

**Comment by zengfancy** [comment]
Thanks for you reply. I just want a answer for question "is 4ms expected". if not, I will try more investigation on it.

**Comment by zengfancy** [comment]
Hi andydavis1,
Thanks for you reply. I can give more details, I can give the stack by gdb, It's like:

26 template <typename T>
 27 struct MatMulTypes {
 28   typedef Eigen::TensorMap<Eigen::Tensor<T, 2, Eigen::RowMajor>, Eigen::Aligned>
 29       out_type;
 30   typedef Eigen::TensorMap<Eigen::Tensor<const T, 2, Eigen::RowMajor>,
 31                            Eigen::Aligned> in_type;
 32 };    
 33 
 34 template <typename Device, typename In0, typename In1, typename Out,
 35           typename DimPair>
 36 void MatMul(const Device& d, Out out, In0 in0, In1 in1,
 37             const DimPair& dim_pair) {
 38   out.device(d) = in0.contract(in1, dim_pair);
 39 }

248 template <typename T>
249 struct MatMulFunctor<CPUDevice, T> {
250   void operator()(
251       const CPUDevice& d, typename MatMulTypes<T>::out_type out,
252       typename MatMulTypes<T>::in_type in0,
253       typename MatMulTypes<T>::in_type in1,
254       const Eigen::array<Eigen::IndexPair<Eigen::DenseIndex>, 1>& dim_pair) {
255     MatMul<CPUDevice>(d, out, in0, in1, dim_pair);
256   }
257 };

And a 150*150 matrix with a 150 vector would cost 4ms here.
Can you give any points for this?

**Comment by zengfancy** [comment]
sorry, this is is misleading. it's a Matrix-Matrix multiplication. 150*150  Mul 150*100. I think it's reasonable to cost 4ms.
