### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute '_lazy_read' inside tf.while_loop containing tf.scatter_nd_update

### ISSUE THREAD

**Issue by eypros** [tensorflow/tensorflow#43851]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
--
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
v1.15.0-rc3-22-g590d6ee 1.15.0
- Python version:
Python 3.6.10
- Bazel version (if compiling from source): --
- GCC/Compiler version (if compiling from source): --
- CUDA/cuDNN version:
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 0
Cuda compilation tools, release 10.0, V10.0.130
- GPU model and memory:
Asus Cerberus GTX-1070TI-A8G 8GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Implementing a simple `tf.while_loop` which contains a `tf.scatter_nd_update` function throws an error:

> AttributeError: 'Tensor' object has no attribute '_lazy_read'

The behaviour is present only in lazy mode (non-eagar execution). Also, it is not appearing when used outside of `tf.while_loop` with a fixed `j`.

**Describe the expected behavior**
I should be able to implement this fixed iteration loop without an error. In a [similar issue](https://github.com/tensorflow/tensorflow/issues/21957) the solution suggested converting Tensor to Variable which does not work in my case though.

**Standalone code to reproduce the issue**
```
import tensorflow as tf

ref = tf.Variable([[0, 1, 0, 2],
                   [0, 1, 2, 2],
                   [1, 2, 1, 3]], dtype=tf.int32)
true_array = tf.Variable([[1, 1, 1, 1]])
false_array = tf.Variable([[1, 0, 1, 0]])
num_iters = tf.Variable(3, dtype=tf.int32)  # 3


def body(ref, true_array, false_array, j, num_iters):
    samples = tf.cond(tf.equal(tf.reduce_sum(ref[j, :], axis=0), 1), lambda: true_array, lambda: false_array)
    ref = tf.scatter_nd_update(ref, [[j]], samples)
     j = tf.add(j, 1)
    return ref, true_array, false_array, j, num_iters


cond = lambda ref, true_array, false_array, j, num_iters: tf.less(j, num_iters)
j = tf.Variable(0, dtype=tf.int32)  # tf.constant(0)
ref, true_array, false_array, j, num_iters = tf.while_loop(cond, body, [ref, true_array, false_array, j, num_iters])
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print('ref', sess.run(ref))
    print('j', sess.run(j))
```
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@eypros 
Please refer to [this comment](https://stackoverflow.com/questions/54096360/how-to-properly-use-tf-scatter-update-for-n-dimensional-updating) and let us know it helps resolve the issue.

**Comment by eypros** [comment]
@Saduf2019 no, the approach mentioned in the stackoverflow comment did not help, since my `ref` was already `tf.Variable`.

**Comment by Saduf2019** [comment]
@eypros 
Can you please upgrade to 2.x and let us know if you face any issues.

**Comment by eypros** [comment]
I have tried tf 2.0 which but in non eager mode (basically in compatibility v1 mode) using either:
```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```
or even
```
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
```
but did not solve my problem.

Instead a working solution for me was to use `tf.tensor_scatter_nd_update()` in place of `tf.scatter_nd_update()` and it seems to work as expected now.

**Comment by Saduf2019** [comment]
i am able to replicate this issue, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/3fea8044ff5df31d50d76247bf99388b/untitled436.ipynb).

**Comment by saikumarchalla** [comment]
@eypros  Currently we are not making any improvements  for TF 1.x and hence we suggest users to use TF 2.x  version. 

Closing this issue since it was resolved for you.Thanks!
