### ISSUE TITLE
CUDA driver is not load in docker container

### ISSUE THREAD

**Issue by kimyoungjin06** [tensorflow/tensorflow#43860]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**:
-   **Linuix Ubuntu 20.04 LTS**:
-   **TensorFlow installed from tensorflow/tensorflow:latest-devel-gpu**:
-   **TensorFlow version (use command below)**:
-   **Python version**:
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:
-   **GPU model and memory**:
-   **Exact command to reproduce**:

### Describe the problem
CUDA ERROR

### Source code / logs

in my docker container
root@jupyter:/# nvidia-smi
Thu Oct  8 01:46:15 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.66       Driver Version: 450.66       CUDA Version: ERR!     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:65:00.0  On |                  N/A |
|  0%   46C    P8    16W / 250W |   2082MiB / 11177MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

in my PC
adminn@adminn-System-Product-Name:~$ nvidia-smi
Thu Oct  8 10:54:08 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.66       Driver Version: 450.66       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:65:00.0  On |                  N/A |
|  0%   51C    P0    64W / 250W |   2089MiB / 11177MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1449      G   /usr/lib/xorg/Xorg                102MiB |
|    0   N/A  N/A      2786      G   /usr/lib/xorg/Xorg               1073MiB |
|    0   N/A  N/A      2916      G   /usr/bin/gnome-shell              301MiB |
|    0   N/A  N/A      4045      G   ...AAAAAAAAA= --shared-files      166MiB |
|    0   N/A  N/A      4172      G   ...AAAAAAAAA= --shared-files      429MiB |
+-----------------------------------------------------------------------------+

**Comment by Saduf2019** [comment]
@kimyoungjin06 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]
Please share the error log for us to analyse.

**Comment by kimyoungjin06** [comment]
@Saduf2019
It is an error about docker container, not about the tensorflow itself.
This is `container` information 

IMAGE: latest-devel-gpu
Last updated16 hours agobytensorflowpackages
DIGEST: 0513e3814d9c
OS/ARCH: linux/amd64
COMPRESSED SIZE: 3.52 GB

**Comment by angerson** [comment]
Can you post a full reproduction example, including the docker invocation, please?

**Comment by kimyoungjin06** [comment]
```bash
$ sudo docker --version
[sudo] password for adminn: 
Docker version 19.03.13, build 4484c46d9d

$ sudo nvidia-docker run -it -p 8889:8888 -p 6007:6006 -h jupyter -v /home/adminn/Jupyter/Workspace:/home/Workspace --name jupyter2 tensorflow/tensorflow:latest-devel-gpu
$ sudo docker start jupyter2
$ sudo docker attach jupyter2

root@jupyter:/# nvidia-smi
Thu Oct 8 01:46:15 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.66 Driver Version: 450.66 CUDA Version: ERR! |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
| | | MIG M. |
|===============================+======================+======================|
| 0 GeForce GTX 108... Off | 00000000:65:00.0 On | N/A |
| 0% 46C P8 16W / 250W | 2082MiB / 11177MiB | 2% Default |
| | | N/A |
+-------------------------------+----------------------+----------------------+
```
`container info`
```bash
IMAGE: latest-devel-gpu
Last updated16 hours agobytensorflowpackages
DIGEST: 0513e3814d9c
OS/ARCH: linux/amd64
COMPRESSED SIZE: 3.52 GB
```
@angerson Do you need any other information?

**Comment by angerson** [comment]
Based on your running `nvidia-docker` instead of `--gpu=all`, It looks like you're using nvidia-docker 1.0. Can you try [after migrating to 2.0](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#migration-from-nvidia-docker-1-0) instead?

**Comment by kimyoungjin06** [comment]
I do not remember the version of nvidia-docker, but I try migrating to 2.0
It is my log
```
$ sudo docker volume ls -q -f driver=nvidia-docker | xargs -r -I{} -n1 docker ps -q -a -f volume={} | xargs -r docker rm -f
$ sudo apt-get purge nvidia-docker
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'nvidia-docker' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 37 not upgraded.
```
after that,
```
$ sudo docker run -it --gpus=all -p 8889:8888 -p 6007:6006 -h jupyter -v /home/adminn/Jupyter/Workspace:/home/Workspace --name jupyter2 tensorflow/tensorflow:latest-devel-gpu
```
But, it comes same result. How can I check nvidia-docker version?

**Comment by kimyoungjin06** [comment]
```
$ nvidia-docker version
NVIDIA Docker: 2.5.0
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by angerson** [comment]
Can you run and paste the log of `sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi`, please?

**Comment by kimyoungjin06** [comment]
```bash
sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi
[sudo] password for adminn: 
Mon Oct 19 06:31:01 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:65:00.0  On |                  N/A |
|  0%   40C    P8    14W / 250W |    607MiB / 11177MiB |      9%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```
