### ISSUE TITLE
No zero values inside callback functions

### ISSUE THREAD

**Issue by mohamedzayan19** [tensorflow/tensorflow#43869]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macos
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Jupyter macos
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):v2.3.0-54-gfcc4b966f1 2.3.1
- Python version: 3.7.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
Inside tensorflow callback function on_epoch_end. Trying to use 0 value inside a str function like this str(0)
**Describe the expected behavior**
Should be able to capture it. print(str(0.0) does not print anything
**Standalone code to reproduce the issue**
    def on_epoch_end(self, epoch, logs=None):
        print(str(0.0))

**Comment by Saduf2019** [comment]
@mohamedzayan19 
Please share simple stand alone code to replicate issue reported or if possible share a colab gist with error reported.
