### ISSUE TITLE
Reading cuda array in c++ as tensor and reading that tensor in python

### ISSUE THREAD

**Issue by govindamagrawal** [tensorflow/tensorflow#43862]
I am getting frames from camera feed, which is basically a cuda array/vector (not OpenCV mat). I want to read this array periodically in tensoflow python for further operations. To do that, first step is to read this cuda array in the form of GPU tensor in tensoflow, without transferring the array from GPU->CPU->GPU, which is basically an overhead. SInce it is cuda array is already present in the GPU, it can be done GPU->GPU. 
The issue here is which function in tensorflow api supports this GPU->GPU operation? I could not find one, if any.

The second issue is, reading this array in array in python side of code. I have gone the https://www.tensorflow.org/guide/create_op, which tells how to create the custom operations in python. But, the template is you send some array, do the operation in cuda, and receive it back in tf. Here, I am trying to read the cuda array in c++ periodically, 
Please help what should be the next step forward. 

Basically my code looks like this:
``

    #include    <unistd.h>   
    #include    <iostream>
    #include    "VideoReader.h"
    #include <cuda_profiler_api.h>

    int main (int argc, char *argv[])
    {
     void    *fReader = NULL;
 
    //// Starting the frameReader to read the camera feed 1. 
    fReader = frameReader ::Init (  "rtsp://admin:........",  //camera feed url
                                                    ......................);  //some more options to read the frame
    
       do 
       {
        pOutData        = 0;
     
        // get frame from camera feed 1
        fResult = fReader::GetVideoFrame (fReader1, &pOutData);
       
       ///// pOutData is the cuda array containing the cuda vector . This vector, I need in tensorflow python for further processing.
      ///// How can I get this vector?     
    
        }
   
    } while (1);
    return 0;
    }

``

**Comment by govindamagrawal** [comment]
Hi @gowthamkpr @ravikyram . Please let me know if you need more clarity about the issue or you want me to go through some resources.

**Comment by gowthamkpr** [comment]
@govindamagrawal Please give us more clarity about the issue. Thanks!
