### ISSUE TITLE
Getting tensorflow.python.framework.errors_impl.NotFoundError

### ISSUE THREAD

**Issue by bkrishna2006** [tensorflow/tensorflow#43863]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):  No 
- OS Platform and Distribution (e.g., Windows 10):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:  Not Applicable
- TensorFlow installed from (source or binary):  PyPI
- TensorFlow version (use command below): 2.3.1 (v2.3.0-54-gfcc4b966f1 2.3.1)
- Python version: 3.8.3
- Bazel version (if compiling from source): Not Applicable
- GCC/Compiler version (if compiling from source): Not Applicable
- CUDA/cuDNN version: Not applicable
- GPU model and memory: Not applicable

**Describe the current behavior**
When I try to save a tensorflow model to disk, it has recently started giving this error - "tensorflow.python.framework.errors_impl.NotFoundError". It used to work for over a month without issues, and nothing has changed as far as I know; but now, giving the error. I tried saving the model as a pickle file like this --> dnn_classifier.save("/path/m.pkl") and also without the .pkl extension like dnn_classifier.save("/path/m").    I observe that the "assets" folder and the "saved_model.pb" files are not getting created.

**Describe the expected behavior**
The "assets" folder and the "saved_model.pb" files should get created.

** Log **
.venvnew\lib\site-packages\tensorflow\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     57   try:
     58     ctx.ensure_initialized()
---> 59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:

NotFoundError: Failed to create a NewWriteableFile: <modelName>\variables\variables_temp_85e1300e45534129922b22ad101f5b87/part-00000-of-00001.data-00000-of-00001.tempstate8682566087768856168 : The system cannot find the path specified.
; No such process [Op:SaveV2]

**Comment by Saduf2019** [comment]
@bkrishna2006 
For the error "tensorflow.python.framework.errors_impl.NotFoundError" please refer to this links and let us know : [link](https://github.com/tensorflow/models/issues/3762), [link1](https://stackoverflow.com/questions/42928822/tensorflow-python-framework-errors-impl-notfounderror-while-creating-a-custom-in), [link2](https://github.com/tensorflow/models/issues/6595).

For the error "NotFoundError: Failed to create a NewWriteableFile:" : please verify the solutions and enable memory to run your code : [link](https://stackoverflow.com/questions/45076911/tensorflow-failed-to-create-a-newwriteablefile-when-retraining-inception), [link1](https://github.com/tensorflow/tensor2tensor/issues/253)
