### ISSUE TITLE
[Encountered unresolved custom op: ResizeNearestNeighbor] when running tflite model 

### ISSUE THREAD

**Issue by sieme97** [tensorflow/tensorflow#43872]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (or github SHA if from source): 2.2.3

**Run Code**
interpreter = tf.lite.Interpreter(model_path="model.tflite")
interpreter.allocate_tensors()

**Error**
RuntimeError: Encountered unresolved custom op: ResizeNearestNeighbor.Node number 33 (ResizeNearestNeighbor) failed to prepare.

I looked into many things but could not find the solution.

**Comment by Saduf2019** [comment]
@sieme97 
Please refer to [this link](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/resize-nearest-neighbor) and let us know if it helps. [also #37003]
Please provide with simple stand alone indented code to replicate the issue or a colab gist with the error reported, also try on tf-nightly and let us know if the issue exists.

**Comment by sieme97** [comment]
I already looked into the issues section but could not get it resolved. I also tried on tf-nightly but no success. The model and code is from https://github.com/foamliu/Deep-Image-Matting
The model is converted to tflite successfully.

**Comment by sieme97** [comment]
sess = tf.keras.backend.get_session()
    converter = tf.contrib.lite.TocoConverter.from_session(sess,final.inputs,final.outputs)
    converter.allow_custom_ops = True
    converter.experimental_new_converter = True
    converter=converter.convert()
    interpreter=tf.contrib.lite.Interpreter(model_content=converter)
    open('model.tflite', 'wb').write(converter)

I am converting the model from the session as it has custom layer. For conversion, I am using tf 1.9.0 version. I also tried the conversion with tf 2.2.0 but could not convert it because of custom layer.

**Comment by Saduf2019** [comment]
@sieme97
Please share complete indented stand alone code such that we can replicate the issue faced or if possible share a colab gist with the error faced.
