### ISSUE TITLE
Unable to load Cats vs Dogs dataset

### ISSUE THREAD

**Issue by TheNightBaron** [tensorflow/tensorflow#43875]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No. I used the same code as is given in https://www.tensorflow.org/datasets/overview, but changed the dataset from mnist to cats_vs_dogs
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10.0.18362, 64-bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
No. Using a PC
- TensorFlow installed from (source or binary):
Binary
- TensorFlow version (use command below):
Tensorflow 2.3.0
Tensorflow datasets 3.2.1
- Python version:
Python 3.5
- Bazel version (if compiling from source):
NA
- GCC/Compiler version (if compiling from source):
NA
- CUDA/cuDNN version:
CUDA driver version   : 10020
- GPU model and memory:
NVIDIA GeForce 940MX 4GB

**Describe the current behavior**
I am unable to download the cats_vs_dogs dataset through the tensorflow datasets.

**Describe the expected behavior**
I should be able to load a variable with the dataset.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

ds = tfds.load('cats_vs_dogs', split = 'train', shuffle_files = True)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-45c82e970652> in <module>()
----> 1 ds, train = tfds.load('cats_vs_dogs', split = 'train', shuffle_files = True) #download cats vs dogs file for this projectb

~\AppData\Roaming\Python\Python35\site-packages\wrapt\wrappers.py in __call__(self, *args, **kwargs)
    565 
    566         return self._self_wrapper(self.__wrapped__, self._self_instance,
--> 567                 args, kwargs)
    568 
    569 class BoundFunctionWrapper(_FunctionWrapperBase):

C:\Anaconda\lib\site-packages\tensorflow_datasets\core\api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
     67     _check_no_positional(fn, args, ismethod, allowed=allowed)
     68     _check_required(fn, kwargs)
---> 69     return fn(*args, **kwargs)
     70 
     71   return disallow_positional_args_dec(wrapped)  # pylint: disable=no-value-for-parameter

C:\Anaconda\lib\site-packages\tensorflow_datasets\core\registered.py in load(name, split, data_dir, batch_size, shuffle_files, download, as_supervised, decoders, read_config, with_info, builder_kwargs, download_and_prepare_kwargs, as_dataset_kwargs, try_gcs)
    369   if download:
    370     download_and_prepare_kwargs = download_and_prepare_kwargs or {}
--> 371     dbuilder.download_and_prepare(**download_and_prepare_kwargs)
    372 
    373   if as_dataset_kwargs is None:

~\AppData\Roaming\Python\Python35\site-packages\wrapt\wrappers.py in __call__(self, *args, **kwargs)
    604 
    605             return self._self_wrapper(self.__wrapped__, self._self_instance,
--> 606                     args, kwargs)
    607 
    608         else:

C:\Anaconda\lib\site-packages\tensorflow_datasets\core\api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
     67     _check_no_positional(fn, args, ismethod, allowed=allowed)
     68     _check_required(fn, kwargs)
---> 69     return fn(*args, **kwargs)
     70 
     71   return disallow_positional_args_dec(wrapped)  # pylint: disable=no-value-for-parameter

C:\Anaconda\lib\site-packages\tensorflow_datasets\core\dataset_builder.py in download_and_prepare(self, download_dir, download_config)
    374           self._download_and_prepare(
    375               dl_manager=dl_manager,
--> 376               download_config=download_config)
    377 
    378           # NOTE: If modifying the lines below to put additional information in

C:\Anaconda\lib\site-packages\tensorflow_datasets\core\dataset_builder.py in _download_and_prepare(self, dl_manager, download_config)
   1017     super(GeneratorBasedBuilder, self)._download_and_prepare(
   1018         dl_manager=dl_manager,
-> 1019         max_examples_per_split=download_config.max_examples_per_split,
   1020     )
   1021 

C:\Anaconda\lib\site-packages\tensorflow_datasets\core\dataset_builder.py in _download_and_prepare(self, dl_manager, **prepare_split_kwargs)
    949 
    950       # Prepare split will record examples associated to the split
--> 951       self._prepare_split(split_generator, **prepare_split_kwargs)
    952 
    953     # Update the info object with the splits.

C:\Anaconda\lib\site-packages\tensorflow_datasets\core\dataset_builder.py in _prepare_split(self, split_generator, max_examples_per_split)
   1032                                      hash_salt=split_generator.name)
   1033     for key, record in utils.tqdm(generator, unit=" examples",
-> 1034                                   total=split_info.num_examples, leave=False):
   1035       example = self.info.features.encode_example(record)
   1036       writer.write(key, example)

C:\Anaconda\lib\site-packages\tqdm\notebook.py in __iter__(self, *args, **kwargs)
    232     def __iter__(self, *args, **kwargs):
    233         try:
--> 234             for obj in super(tqdm_notebook, self).__iter__(*args, **kwargs):
    235                 # return super(tqdm...) will not catch exception
    236                 yield obj

C:\Anaconda\lib\site-packages\tqdm\std.py in __iter__(self)
   1163 
   1164         try:
-> 1165             for obj in iterable:
   1166                 yield obj
   1167                 # Update and possibly print the progressbar.

C:\Anaconda\lib\site-packages\tensorflow_datasets\image_classification\cats_vs_dogs.py in _generate_examples(self, archive)
     87     """Generate Cats vs Dogs images and labels given a directory path."""
     88     num_skipped = 0
---> 89     for fname, fobj in archive:
     90       res = _NAME_RE.match(fname)
     91       if not res:  # README file, ...

C:\Anaconda\lib\site-packages\tensorflow_datasets\core\download\extractor.py in iter_zip(arch_f)
    197     for member in z.infolist():
    198       extract_file = z.open(member)
--> 199       if member.is_dir():  # Filter directories  # pytype: disable=attribute-error
    200         continue
    201       path = _normpath(member.filename)

AttributeError: 'ZipInfo' object has no attribute 'is_dir'

**Comment by bhack** [comment]
I cannot reproduce this. 
We don't officially support anaconda here. Can you try again installing TF with official installation guide?

**Comment by TheNightBaron** [comment]
Its working fine for the mnist dataset. Its seems the problem is only with the cats vs dogs dataset. I'll do as you ask tonight and let you know.

**Comment by amahendrakar** [comment]
@TheNightBaron,
I was able to run the code without any issues, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/a1786e6ecb898dce2419f7a25721d219/43875.ipynb). 

Could you please check if you're facing the same issue in a Python virtual environment? Thanks!

**Comment by TheNightBaron** [comment]
I have python only on Anaconda. Do I need to install python separately for trying this?

**Comment by bhack** [comment]
We don't directly support Anaconda and I cannot reproduce this in TF with the official install guide
