### ISSUE TITLE
Significant performance overhead with gpu kernel launches in a while_loop

### ISSUE THREAD

**Issue by kbrems** [tensorflow/tensorflow#4387]
### Environment info
Operating System:
ubuntu 14.04
GeForce GTX TITAN  Driver Version: 367.44

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
-rw-r--r-- 1 root root   322936 Aug 15  2015 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root       19 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root   383336 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root   720192 Aug 15  2015 /usr/local/cuda/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 61453024 Feb 23  2016 /usr/local/cuda/lib64/libcudnn.so
-rwxr-xr-x 1 root root 61453024 Feb 23  2016 /usr/local/cuda/lib64/libcudnn.so.4
-rwxr-xr-x 1 root root 61453024 Feb 23  2016 /usr/local/cuda/lib64/libcudnn.so.4.0.7
-rw-r--r-- 1 root root 62025862 Feb 23  2016 /usr/local/cuda/lib64/libcudnn_static.a

1. A link to the pip package you installed:
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.10.0rc0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

import tensorflow as tf
from tensorflow.python.client import timeline

start = tf.constant(0, dtype=tf.float64)
end = tf.constant(100, dtype=tf.float64)
init = tf.ones([100], dtype=tf.float64)
b = tf.ones([100], dtype=tf.float64)

def condForWhile(i, a):
    return tf.less(i, end)

def bodyForWhile(i, a):
    i = i + 1
    a = tf.mul(a, b)
    return [i, a]

_, prod = tf.while_loop(condForWhile, bodyForWhile, [start, init])

with tf.Session() as sess:
    tf.initialize_all_variables().run()
    # run once to eliminate start-up costs
    sess.run(prod)
    # now run with tracing
    run_metadata = tf.RunMetadata()
    result = sess.run(prod,
        options=tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE),
        run_metadata=run_metadata)

trace = timeline.Timeline(step_stats=run_metadata.step_stats)
trace_file = open('/tmp/timeline.tfwhile.json', 'w')
trace_file.write(trace.generate_chrome_trace_format(show_dataflow=False, show_memory=False))

This is a simple app that does a = a * b 100 times in a while_loop using the tf.mul() operator. I am using the timeline feature to profile it. Inspecting the timeline shows that for each iteration, the time in the gpu stream for the multiply is about .003ms, but the time between launches is .3ms-.5ms. This seems like a lot - is that expected? 

Note that my while condition uses floats in the less function. I see the less operation happening on the gpu stream and a memcpyDtoH time for each loop iteration presumably to copy the loop counter back and forth to the gpu, which seems kind of inefficient. If instead I use  type int64 in the loop conditions (start and end), then the gap between kernels goes down to .11 - .17ms and I no longer see the less on the gpu stream or the memcpy. 

Note that in the original case where we discovered this, our gpu operator was much more complicated (and uses floats in the condition) and the time between kernel launches was still relatively constant at around .4ms. In contrast, if I write this same app in straight cuda, and launch the kernel 100 times in cuda, the gap between launches is about .007ms (about 50x improvement). I would expect some overhead in the tensorflow conditional operators, but this really seems like a lot. 

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
Attaching the timeline traces for the above code for both floats and ints in the conditional. 

[timelines.zip](https://github.com/tensorflow/tensorflow/files/473495/timelines.zip)

**Comment by prb12** [comment]
@yuanbyu can probably clarify- but it does seem like you are executing the loop condition on the GPU. This is always going to be very inefficient since the host needs to know the output of the condition before it can dispatch the loop body for the next iteration.

By making the condition function use integers you are effectively causing it to be executed on the CPU - there is a special case for integer ops assigned to /gpu:0 to compute on tensors kept in host memory.  This avoids the memcpyD2H and having to sync against the GPU stream each iteration.

**Comment by yuanbyu** [comment]
I modified your code to compare it with static unrolling in TF:

```
import google3
import tensorflow.google as tf
import numpy as np
import time

cfg = tf.ConfigProto(graph_options=tf.GraphOptions(
    optimizer_options=tf.OptimizerOptions(
        opt_level=tf.OptimizerOptions.L0)))

dim = 100
start = tf.constant(0)
end = tf.placeholder(tf.int32)
init = tf.ones([dim], dtype=tf.float64)
b = tf.ones([dim], dtype=tf.float64)

def while_run():
  def condForWhile(i, a):
    return tf.less(i, end)

  def bodyForWhile(i, a):
    i = i + 1
    a = tf.mul(a, b)
    return [i, a]

  _, prod = tf.while_loop(condForWhile, bodyForWhile, [start, init])
  with tf.control_dependencies([prod]):
    result = tf.no_op()

  with tf.Session(config=cfg) as sess:
    # warm up to eliminate start-up costs
    sess.run(result, feed_dict={end: 100})

    # time it.
    t0 = time.time()
    sess.run(result, feed_dict={end: 10000})
    print("Iterations/second (dynamic):", 10000.0 / (time.time() - t0))

def for_run():
  prod = init
  for i in xrange(10000):
    prod = tf.mul(prod, b)
  with tf.control_dependencies([prod]):
    result = tf.no_op()

  with tf.Session(config=cfg) as sess:
    # warm up to eliminate start-up costs
    sess.run(result)

    # time it.
    t0 = time.time()
    sess.run(result)
    print("Iterations/second (static):", 10000.0 / (time.time() - t0))

def main(_):
  for_run()
  while_run()

if __name__ == '__main__':
  tf.app.run() 
```

Here are the results. When the loop body is tiny, the run time is dominated by the book keeping overhead of while loop. (We need to run a lot more ops such as tf.add, tf.less, ...) When the loop body has a bit non-trivial computation, they are roughly equal.

dim = 100:
Iterations/second (static): 183921.174835
Iterations/second (dynamic): 79751.9009581

dim = 100000:
Iterations/second (static): 69104.7188479
Iterations/second (dynamic): 69447.4082463

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when additional information becomes available.
