### ISSUE TITLE
Embedding Projector - Unable to load different data set

### ISSUE THREAD

**Issue by sinan-demirhan** [tensorflow/tensorflow#43883]
We want to use dimension reduction and clustering app of tensorflow. However we are unable to load data set to http://projector.tensorflow.org/ 
It gives us errors like Number of tensors (10000) do not match the number of lines in metadata (3492) or
it does not give any error and does not load the file

**Comment by amahendrakar** [comment]
@sinan-demirhan,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!
