### ISSUE TITLE
all_ops_resolver.h:4:10: fatal error: tensorflow/lite/micro/compatibility.h: No such file or directory

### ISSUE THREAD

**Issue by Zuu97** [tensorflow/tensorflow#43881]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution : Windows 10
- Tensorflow version : 2.1.0
- Target platform : Arduino Nano 33

Header are missing in hello_world sketches. So fails to build the deployment

Following contains the headers I used.
```

#include "tensorflow/lite/micro/all_ops_resolver.h"
#include "tensorflow/lite/micro/examples/hello_world/model.h"
#include "tensorflow/lite/micro/micro_error_reporter.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/testing/micro_test.h"
#include "tensorflow/lite/schema/schema_generated.h"
#include "tensorflow/lite/version.h"
```

**Comment by wangtz** [comment]
Hi Alagiyawanna,

I'm sorry that you hit this problem. This file seems to be in the github repo: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/compatibility.h

Could you try sync to the latest head and see if it solves your problem?

Thanks,
Tiezhen

**Comment by Zuu97** [comment]
Thank you @wangtz. Now its work fine.
