### ISSUE TITLE
Error while building tensorflow from source, need it for C++ inference.

### ISSUE THREAD

**Issue by devang1397** [tensorflow/tensorflow#43894]
no such package '@icu//': java.io.IOException: **Error downloading [https://mirror.bazel.build/github.com/unicode-org/icu/archive/release-62-1.tar.gz**

**System information**
- Windows 10
- TensorFlow installed from source
- TensorFlow version: 1.13
- Python version: 3.7
- Bazel version 0.21
- GCC/Compiler version VS2015
- CUDA/cuDNN version: 10, 7.4.1
- GPU model and memory: Titan XP, 10Gb

**While building tensorflow for windows based on tensoflow website directed steps I got this error below after configur.py was ran successfully**

ERROR: C:/tensorflow/tensorflow/tools/pip_package/BUILD:149:1: no such package '@icu//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/unicode-org/icu/archive/release-62-1.tar.gz, https://github.com/unicode-org/icu/archive/release-62-1.tar.gz] to C:/users/dsavaliya/_bazel_dsavaliya/xv6zejqw/external/icu/release-62-1.tar.gz: Checksum was 86b85fbf1b251d7a658de86ce5a0c8f34151027cc60b01e1b76f167379acf181 but wanted e15ffd84606323cbad5515bf9ecdf8061cc3bf80fb883b9e6aa162e485aa9761 and referenced by '//tensorflow/tools/pip_package:licenses'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@icu//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/unicode-org/icu/archive/release-62-1.tar.gz, https://github.com/unicode-org/icu/archive/release-62-1.tar.gz] to C:/users/dsavaliya/_bazel_dsavaliya/xv6zejqw/external/icu/release-62-1.tar.gz: Checksum was 86b85fbf1b251d7a658de86ce5a0c8f34151027cc60b01e1b76f167379acf181 but wanted e15ffd84606323cbad5515bf9ecdf8061cc3bf80fb883b9e6aa162e485aa9761

**Provide the exact sequence of commands / steps that you executed before running into the problem**

(base) **c:\>python tensorflow\configure.py**
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
nul
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: d6710a42-59b5-4bbb-9174-8bc67a08a8c7
You have bazel 0.21.0 installed.
Please specify the location of python. [Default is C:\ProgramData\Anaconda3\python.exe]:

Found possible Python library paths:
  \Users\dsavaliya\Repos\Pytools
  C:\ProgramData\Anaconda3\lib\site-packages
Please input the desired Python library path to use.  Default is [\Users\dsavaliya\Repos\Pytools]

Do you wish to build TensorFlow with XLA JIT support? [y/N]:
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]:
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]:
No CUDA support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:

Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]:
Eigen strong inline overridden.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=gdr            # Build with GDR support.
        --config=verbs          # Build with libverbs support.
        --config=ngraph         # Build with Intel nGraph support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=noignite       # Disable Apacha Ignite support.
        --config=nokafka        # Disable Apache Kafka support.
        --config=nonccl         # Disable NVIDIA NCCL support.

(base) c:\>cd c:\tensorflow
(base) **c:\tensorflow>bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package**
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
c:\tensorflow/.bazelrc
Starting local Bazel server and connecting to it...
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
INFO: Invocation ID: 27545a6e-c366-4264-9cb3-eea8d0762600
**ERROR: C:/tensorflow/tensorflow/tools/pip_package/BUILD:149:1: no such package '@icu//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/unicode-org/icu/archive/release-62-1.tar.gz, https://github.com/unicode-org/icu/archive/release-62-1.tar.gz] to C:/users/dsavaliya/_bazel_dsavaliya/xv6zejqw/external/icu/release-62-1.tar.gz: Checksum was 86b85fbf1b251d7a658de86ce5a0c8f34151027cc60b01e1b76f167379acf181 but wanted e15ffd84606323cbad5515bf9ecdf8061cc3bf80fb883b9e6aa162e485aa9761 and referenced by '//tensorflow/tools/pip_package:licenses'**
**ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@icu//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/unicode-org/icu/archive/release-62-1.tar.gz, https://github.com/unicode-org/icu/archive/release-62-1.tar.gz] to C:/users/dsavaliya/_bazel_dsavaliya/xv6zejqw/external/icu/release-62-1.tar.gz: Checksum was 86b85fbf1b251d7a658de86ce5a0c8f34151027cc60b01e1b76f167379acf181 but wanted e15ffd84606323cbad5515bf9ecdf8061cc3bf80fb883b9e6aa162e485aa9761**
INFO: Elapsed time: 22.941s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (316 packages loaded, 11908 targets configured)
    Fetching @icu; fetching 14s

**Also tried GPU supported virion with command as below, but do the same error as above.** 
(base) **c:\tensorflow>bazel build --config=monolithic --config=opt --config=cuda //tensorflow/tools/lib_package:libtensorflow**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@devang1397 
Currently there is support for 2.x only, can you please upgrade to 2.x and let us know if you face any problem.
