### ISSUE TITLE
Model size reduction in set_weights()

### ISSUE THREAD

**Issue by OriAlpha** [tensorflow/tensorflow#43892]
I have used tf.Keras for training and then transferred weights to another model with the help of get_weights() and set_weights(). After saving the weights from the original to another model I have seen that there is the model size reduction of 3 times smaller. 
Any idea why this is happening.

**Comment by amahendrakar** [comment]
@OriAlpha,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!
