### ISSUE TITLE
Say that we need gcc >= 4.8 (was "Need help on compilation error on Mac")

### ISSUE THREAD

**Issue by tcct** [tensorflow/tensorflow#439]
Having met the following compilation errors:

tensorflow/core/kernels/fifo_queue.cc:247:46: error: expected body of lambda expression
          [callback, this](Attempt* attempt) EXCLUSIVE_LOCKS_REQUIRED(mu_) {
                                                               ^

Please let me know if you have any ideas. Thanks!

**Comment by girving** [comment]
Please include the entire error message.

**Comment by tcct** [comment]
It seems my problem is how to configure things right to use non-system default GCC. I upgraded to gcc47. And now I got the following errors. thx.

| => bazel build -c opt --copt='-fabi-version=6' --linkopt='-lrt'  //tensorflow/tools/pip_package:build_pip_package --verbose_failures
INFO: Found 1 target...
INFO: From Compiling tensorflow/core/lib/histogram/histogram.cc:
In file included from ./tensorflow/core/lib/gtl/array_slice.h:101:0,
                 from ./tensorflow/core/lib/histogram/histogram.h:20,
                 from tensorflow/core/lib/histogram/histogram.cc:16:
./tensorflow/core/lib/gtl/array_slice_internal.h:231:38: error: 'tensorflow::gtl::array_slice_internal::ArraySliceImplBase<const T>::ArraySliceImplBase' names constructor
./tensorflow/core/lib/gtl/array_slice_internal.h:251:32: error: 'tensorflow::gtl::array_slice_internal::ArraySliceImplBase<T>::ArraySliceImplBase' names constructor
In file included from ./tensorflow/core/lib/histogram/histogram.h:20:0,
                 from tensorflow/core/lib/histogram/histogram.cc:16:
./tensorflow/core/lib/gtl/array_slice.h: In instantiation of 'tensorflow::gtl::ArraySlice<T>::ArraySlice(const std::vector<_RealType>&) [with T = double]':
tensorflow/core/lib/histogram/histogram.cc:48:11:   required from here
./tensorflow/core/lib/gtl/array_slice.h:132:33: error: no matching function for call to 'tensorflow::gtl::array_slice_internal::ArraySliceImpl<double>::ArraySliceImpl(const double*, std::vector<double>::size_type)'
./tensorflow/core/lib/gtl/array_slice.h:132:33: note: candidates are:
In file included from ./tensorflow/core/lib/gtl/array_slice.h:101:0,
                 from ./tensorflow/core/lib/histogram/histogram.h:20,
                 from tensorflow/core/lib/histogram/histogram.cc:16:
./tensorflow/core/lib/gtl/array_slice_internal.h:243:12: note: template<class C> tensorflow::gtl::array_slice_internal::ArraySliceImpl::ArraySliceImpl(const C&)
./tensorflow/core/lib/gtl/array_slice_internal.h:243:12: note:   template argument deduction/substitution failed:
In file included from ./tensorflow/core/lib/histogram/histogram.h:20:0,
                 from tensorflow/core/lib/histogram/histogram.cc:16:
./tensorflow/core/lib/gtl/array_slice.h:132:33: note:   candidate expects 1 argument, 2 provided
In file included from ./tensorflow/core/lib/gtl/array_slice.h:101:0,
                 from ./tensorflow/core/lib/histogram/histogram.h:20,
                 from tensorflow/core/lib/histogram/histogram.cc:16:
./tensorflow/core/lib/gtl/array_slice_internal.h:229:7: note: constexpr tensorflow::gtl::array_slice_internal::ArraySliceImpl<double>::ArraySliceImpl(const tensorflow::gtl::array_slice_internal::ArraySliceImpl<double>&)
./tensorflow/core/lib/gtl/array_slice_internal.h:229:7: note:   candidate expects 1 argument, 2 provided
./tensorflow/core/lib/gtl/array_slice_internal.h:229:7: note: constexpr tensorflow::gtl::array_slice_internal::ArraySliceImpl<double>::ArraySliceImpl(tensorflow::gtl::array_slice_internal::ArraySliceImpl<double>&&)
./tensorflow/core/lib/gtl/array_slice_internal.h:229:7: note:   candidate expects 1 argument, 2 provided

**Comment by girving** [comment]
@vrv: What's our range of supported compilers?  Should gcc 4.7 be fine?

**Comment by vrv** [comment]
I'm not sure, 4.8+ is the safe assumption (the earliest we've tried successfully).

**Comment by martinwicke** [comment]
We certainly haven't tested with it, so if it doesn't work, that may be a
sign that it isn't presently supported.

**Comment by philwo** [comment]
From the error messages I've seen on our Bazel issue tracker, I'd say tensorflow definitely requires at least gcc 4.8 due to certain C++11 features being used.

**Comment by girving** [comment]
We should give the compiler range in the README.

**Comment by tcct** [comment]
Ok, I upgraded to gcc4.8.5, and now I am having issue to compile protobuf:

INFO: From Compiling google/protobuf/src/google/protobuf/map_field.cc [for host]:
In file included from /opt/local/include/gcc48/c++/unordered_map:47:0,
                 from google/protobuf/src/google/protobuf/stubs/hash.h:139,
                 from google/protobuf/src/google/protobuf/map.h:35,
                 from google/protobuf/src/google/protobuf/map_field_lite.h:34,
                 from google/protobuf/src/google/protobuf/map_field.h:40,
                 from google/protobuf/src/google/protobuf/map_field.cc:31:
/opt/local/include/gcc48/c++/bits/hashtable.h: In instantiation of 'std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::__node_type* std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::_M_allocate_node(_Args&& ...) [with _Args = {const std::piecewise_construct_t&, std::tuple<const google::protobuf::MapKey&>, std::tuple<>}; _Key = google::protobuf::MapKey; _Value = std::pair<const google::protobuf::MapKey, google::protobuf::MapPair<google::protobuf::MapKey, google::protobuf::MapValueRef>*>; _Alloc = google::protobuf::Map<google::protobuf::MapKey, google::protobuf::MapValueRef>::MapAllocator<std::pair<const google::protobuf::MapKey, google::protobuf::MapPair<google::protobuf::MapKey, google::protobuf::MapValueRef>*> >; _ExtractKey = std::__detail::_Select1st; _Equal = std::equal_to<google::protobuf::MapKey>; _H1 = google::protobuf::hash<google::protobuf::MapKey>; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<true, false, true>; std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::__node_type = std::__detail::_Hash_node<std::pair<const google::protobuf::MapKey, google::protobuf::MapPair<google::protobuf::MapKey, google::protobuf::MapValueRef>*>, true>]':
/opt/local/include/gcc48/c++/bits/hashtable_policy.h:493:8:   required from 'std::__detail::_Map_base<_Key, _Pair, _Alloc, std::__detail::_Select1st, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits, true>::mapped_type& std::__detail::_Map_base<_Key, _Pair, _Alloc, std::__detail::_Select1st, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits, true>::operator[](const key_type&) [with _Key = google::protobuf::MapKey; _Pair = std::pair<const google::protobuf::MapKey, google::protobuf::MapPair<google::protobuf::MapKey, google::protobuf::MapValueRef>*>; _Alloc = google::protobuf::Map<google::protobuf::MapKey, google::protobuf::MapValueRef>::MapAllocator<std::pair<const google::protobuf::MapKey, google::protobuf::MapPair<google::protobuf::MapKey, google::protobuf::MapValueRef>*> >; _Equal = std::equal_to<google::protobuf::MapKey>; _H1 = google::protobuf::hash<google::protobuf::MapKey>; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<true, false, true>; std::__detail::_Map_base<_Key, _Pair, _Alloc, std::__detail::_Select1st, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits, true>::mapped_type = google::protobuf::MapPair<google::protobuf::MapKey, google::protobuf::MapValueRef>*; std::__detail::_Map_base<_Key, _Pair, _Alloc, std::__detail::_Select1st, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits, true>::key_type = google::protobuf::MapKey]'
/opt/local/include/gcc48/c++/bits/unordered_map.h:596:20:   required from 'std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::mapped_type& std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::operator[](const key_type&) [with _Key = google::protobuf::MapKey; _Tp = google::protobuf::MapPair<google::protobuf::MapKey, google::protobuf::MapValueRef>*; _Hash = google::protobuf::hash<google::protobuf::MapKey>; _Pred = std::equal_to<google::protobuf::MapKey>; _Alloc = google::protobuf::Map<google::protobuf::MapKey, google::protobuf::MapValueRef>::MapAllocator<std::pair<const google::protobuf::MapKey, google::protobuf::MapPair<google::protobuf::MapKey, google::protobuf::MapValueRef>*> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::mapped_type = google::protobuf::MapPair<google::protobuf::MapKey, google::protobuf::MapValueRef>*; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_type = google::protobuf::MapKey]'
google/protobuf/src/google/protobuf/map.h:674:36:   required from 'T& google::protobuf::Map<Key, T>::operator[](const key_type&) [with Key = google::protobuf::MapKey; T = google::protobuf::MapValueRef; google::protobuf::Map<Key, T>::key_type = google::protobuf::MapKey]'
google/protobuf/src/google/protobuf/map_field.cc:185:49:   required from here
/opt/local/include/gcc48/c++/bits/hashtable.h:727:6: error: no matching function for call to 'google::protobuf::Map<google::protobuf::MapKey, google::protobuf::MapValueRef>::MapAllocator<std::__detail::_Hash_node<std::pair<const google::protobuf::MapKey, google::protobuf::MapPair<google::protobuf::MapKey, google::protobuf::MapValueRef>*>, true> >::construct(std::_Hashtable<google::protobuf::MapKey, std::pair<const google::protobuf::MapKey, google::protobuf::MapPair<google::protobuf::MapKey, google::protobuf::MapValueRef>*>, google::protobuf::Map<google::protobuf::MapKey, google::protobuf::MapValueRef>::MapAllocator<std::pair<const google::protobuf::MapKey, google::protobuf::MapPair<google::protobuf::MapKey, google::protobuf::MapValueRef>*> >, std::__detail::_Select1st, std::equal_to<google::protobuf::MapKey>, google::protobuf::hash<google::protobuf::MapKey>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::__node_type*&, const std::piecewise_construct_t&, std::tuple<const google::protobuf::MapKey&>, std::tuple<>)'
      _M_node_allocator().construct(__n, std::forward<_Args>(__args)...);
      ^
/opt/local/include/gcc48/c++/bits/hashtable.h:727:6: note: candidate is:
In file included from google/protobuf/src/google/protobuf/map_field_lite.h:34:0,
                 from google/protobuf/src/google/protobuf/map_field.h:40,
                 from google/protobuf/src/google/protobuf/map_field.cc:31:
google/protobuf/src/google/protobuf/map.h:562:10: note: void google::protobuf::Map<Key, T>::MapAllocator<U>::construct(google::protobuf::Map<Key, T>::MapAllocator<U>::pointer, google::protobuf::Map<Key, T>::MapAllocator<U>::const_reference) [with U = std::__detail::_Hash_node<std::pair<const google::protobuf::MapKey, google::protobuf::MapPair<google::protobuf::MapKey, google::protobuf::MapValueRef>*>, true>; Key = google::protobuf::MapKey; T = google::protobuf::MapValueRef; google::protobuf::Map<Key, T>::MapAllocator<U>::pointer = std::__detail::_Hash_node<std::pair<const google::protobuf::MapKey, google::protobuf::MapPair<google::protobuf::MapKey, google::protobuf::MapValueRef>*>, true>*; google::protobuf::Map<Key, T>::MapAllocator<U>::value_type = std::__detail::_Hash_node<std::pair<const google::protobuf::MapKey, google::protobuf::MapPair<google::protobuf::MapKey, google::protobuf::MapValueRef>*>, true>; google::protobuf::Map<Key, T>::MapAllocator<U>::const_reference = const std::__detail::_Hash_node<std::pair<const google::protobuf::MapKey, google::protobuf::MapPair<google::protobuf::MapKey, google::protobuf::MapValueRef>*>, true>&]
     void construct(pointer p, const_reference t) { new (p) value_type(t); }
          ^
google/protobuf/src/google/protobuf/map.h:562:10: note:   candidate expects 2 arguments, 4 provided
ERROR: /Users/chaotan/Workspace/deep_learning/tensorflow/tensorflow1/google/protobuf/BUILD:64:1: C++ compilation of rule '//google/protobuf:protobuf' failed: osx_gcc_wrapper.sh failed: error executing command 
  (cd /private/var/tmp/_bazel_chaotan/58945d877128dff569ec8b54b7c14ab6/tensorflow1 && \
  exec env - \
    INTERCEPT_LOCALLY_EXECUTABLE=1 \
    PATH=/opt/local/bin:/usr/local/git/bin:/sw/bin/:/usr/local/bin:/usr/local/:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:/usr/local/bin/ \
    TMPDIR=/var/folders/4r/gpk5b_zn30qf4f5z7xc33k0w002l2g/T/ \
  tools/cpp/osx_gcc_wrapper.sh '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -g0 '-std=c++0x' -iquote . -iquote bazel-out/host/genfiles -isystem google/protobuf/src -isystem bazel-out/host/genfiles/google/protobuf/src -isystem tools/cpp/gcc3 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare '-Wno-error=unused-function' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/host/bin/google/protobuf/_objs/protobuf/google/protobuf/src/google/protobuf/map_field.o' -MD -MF bazel-out/host/bin/google/protobuf/_objs/protobuf/google/protobuf/src/google/protobuf/map_field.d -c google/protobuf/src/google/protobuf/map_field.cc -o bazel-out/host/bin/google/protobuf/_objs/protobuf/google/protobuf/src/google/protobuf/map_field.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: osx_gcc_wrapper.sh failed: error executing command 
  (cd /private/var/tmp/_bazel_chaotan/58945d877128dff569ec8b54b7c14ab6/tensorflow1 && \
  exec env - \
    INTERCEPT_LOCALLY_EXECUTABLE=1 \
    PATH=/opt/local/bin:/usr/local/git/bin:/sw/bin/:/usr/local/bin:/usr/local/:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:/usr/local/bin/ \
    TMPDIR=/var/folders/4r/gpk5b_zn30qf4f5z7xc33k0w002l2g/T/ \
  tools/cpp/osx_gcc_wrapper.sh '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -g0 '-std=c++0x' -iquote . -iquote bazel-out/host/genfiles -isystem google/protobuf/src -isystem bazel-out/host/genfiles/google/protobuf/src -isystem tools/cpp/gcc3 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare '-Wno-error=unused-function' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/host/bin/google/protobuf/_objs/protobuf/google/protobuf/src/google/protobuf/map_field.o' -MD -MF bazel-out/host/bin/google/protobuf/_objs/protobuf/google/protobuf/src/google/protobuf/map_field.d -c google/protobuf/src/google/protobuf/map_field.cc -o bazel-out/host/bin/google/protobuf/_objs/protobuf/google/protobuf/src/google/protobuf/map_field.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 3.012s, Critical Path: 2.06s

**Comment by girving** [comment]
Wow, that's fairly unpleasant.  Unfortunate I have no idea what's going wrong, and it seems to be fairly deep inside protobuf.  Would you mind filing a bug over at https://github.com/google/protobuf?  This seems like an issue on their end (apologies for the side stepping).

**Comment by tcct** [comment]
Will do. I am mainly referring to g3doc/get_started/os_setup.md to set up my stuff. It will be great things can be made more clear in terms of the version dependencies of all the required components. Especially since a section is dedicated to MacOS, I suppose someone is actively working on this platform. :)

Thanks!

**Comment by vrv** [comment]
(You're definitely helping us to figure out what those dependencies are, so thanks :)

**Comment by girving** [comment]
Incidentally, if you want to get unblocked, you might try clang.  I think we haven't found all these issues yet because most people on OS X compile with clang.  Though I suppose I'm not sure what bazel uses by default.

**Comment by tcct** [comment]
How do you use clang to compile? thx.

**Comment by vrv** [comment]
https://groups.google.com/forum/#!topic/bazel-discuss/m2y2ZEB7zJE seems like a helpful thread on this topic

**Comment by liuguangyuan** [comment]
I solve this question simply and roughly.EXCLUSIVE_LOCKS_REQUIRED(mu_)  is used about GPU. Because Mac doesn't support GPU, we can delete EXCLUSIVE_LOCKS_REQUIRED(mu_). so correspond syntax of lambda and compile successfully.

**Comment by lilac** [comment]
I encountered the same error 
```
expected body of lambda expression
          [tuple, this](Attempt* attempt) EXCLUSIVE_LOCKS_REQUIRED(mu_)
```
My build host is
```clang++ -v
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.2.0
```
Though I am using cmake instead of bazel, I think it probably uses the default clang compiler.
Thus I think this issue is not related to compiler, but compiler features flags. The compiler seems to detect that is a lambda expression, but do not expect that macro, thus the error?

**Comment by girving** [comment]
@martinwicke Do you want to triage this further, or should we just close?

**Comment by martinwicke** [comment]
We can close this. It's hard to see what we can do about it. It may actually be fixed now that we made the GPU code work on Mac.
