### ISSUE TITLE
Link error occurs due to MetaGraphDef

### ISSUE THREAD

**Issue by yangjonghyeon** [tensorflow/tensorflow#43903]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4.0(master branch)
- Python version: 3.7
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0/8.0
- GPU model and memory:

**Describe the problem**
I am building tensorflow 2.4.0(master branch / lastest commit : 68a6fe0d984377b625b421d34f8c607d6ed73597) from source with additional link symbols

You have bazel 3.1.0 installed.
Please specify the location of python. [Default is C:\Anaconda3\envs\py37\python.exe]:

Found possible Python library paths:
  C:\Anaconda3\envs\py37\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Anaconda3\envs\py37\lib\site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]:
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Found CUDA 11.0 in:
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0/lib/x64
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0/include
Found cuDNN 8 in:
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0/lib/x64
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.0/include

Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus. Each capability can be specified as "x.y" or "compute_xy" to include both virtual and binary GPU code, or as "sm_xy" to only include the binary code.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 3.5,7.0]: 3.5, 5.0, 5.2, 6.1, 7.0, 7.5, 8.0

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:

Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]:
Eigen strong inline overridden.

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]:
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v2             # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=nonccl         # Disable NVIDIA NCCL support.

bazel build -c opt --config=opt --config=cuda --config=v1 //tensorflow:libtensorflow_cc.so
(or bazel build -c opt --config=opt --config=cuda --config=v1 //tensorflow:tensorflow_cc.dll)

both way occurs same error messages.

I think this line causes error in c++
		MetaGraphDef graphDef;
                std::istream istream
		bool stat = graphDef.ParseFromIstream(istream);
 and the error message is 
libtensorflow_cc.so.2.4.0.if.exp : error LNK2001: 확인할 수 없는 외부 기호(maybe this phrase is same as 'unresolved external symbols') "public: bool __cdecl google::protobuf::Message::ParseFromIstream(class std::basic_istream<char,struct std::char_traits<char> > *)" (?ParseFromIstream@Message@protobuf@google@@QEAA_NPEAV?$basic_istream@DU?$char_traits@D@std@@@std@@@Z)

when i'm building tf 1.13 from source(CUDA10.0/cudnn7) using tf_exported_symbols_msvc.lds following this(https://github.com/tensorflow/tensorflow/issues/23542) i could successfully import additional symbols
However, when i'm building tf2.4.0, i could not import additional symbols via tf_exported_symbols_msvc.lds.
As described in (https://github.com/tensorflow/tensorflow/issues/23542), i think that tf do not support the way to add symbols by tf_exported_symbols_msvc.lds. So it tried to add symbols by explicitly add symbols on tensorflow/tools/def_file_filter/def_file_filter.py.tpl like following lines

      if DATA_EXCLUDE_RE.search(line):
        def_fp.write("\t" + decorated + "\n")
      else:
        def_fp.write("\t" + decorated + " DATA\n")
      taken.add(decorated)

    for sym in symbols_pybind:
      def_fp.write("\t{}\n".format(sym))
      taken.add(sym)
    # write additional symbols
    def_fp.write("\t??$CreateMaybeMessage@VTensorShapeProto@tensorflow@@$$V@Arena@protobuf@google@@CAPEAVTensorShapeProto@tensorflow@@PEAV012@@Z\n")
    def_fp.write("\t?AppendToString@MessageLite@protobuf@google@@QEBA_NPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z\n")
    def_fp.write("\t?SerializePartialAsString@MessageLite@protobuf@google@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ\n")

By this way, i think i could add additional symbols to tensorflow_cc.lib. and the log messsage says that lnk2001 unresolved symbols on these four symbols
    def_fp.write("\t??0?$TensorShapeBase@VTensorShape@tensorflow@@@tensorflow@@QEAA@V?$Span@$$CB_J@absl@@@Z\n")
    def_fp.write("\t?ParseFromIstream@Message@protobuf@google@@QEAA_NPEAV?$basic_istream@DU?$char_traits@D@std@@@std@@@Z\n")
    def_fp.write("\t?find@string_view@absl@@QEBA_KD_K@Z\n")
    def_fp.write("\t?tensor_data@Tensor@tensorflow@@QEBA?AVstring_view@absl@@XZ\n")
and when i erase these symbols from def_file_filter.py.tpl i could successfully add extra symbols on tensorflow_cc.lib(or libtensorflow_cc_.lib) by writing on def_file_filter.py.tpl

PROBLEMS
- I couldn't add above four extra symbols(Also, I couldn't find MetaGraphDef class.. that i couold found on tf1.13)

The question is, that i want to use those functions on c++, and i could use it when i build tensorflow on tf 1.13(cuda10.0, cudnn 7.0, bazel build -c opt --config=opt --config=cuda --config=noignite --config=nokafka //tensorflow:libtensorflow_cc.so)  by adding extra symbols from  tf_exported_symbols_msvc.lds. BUT when it comes to tf 2.4.0, i couldn't add some of the extra symbols that i could add in tf 1.13(above four symbols). It tooks almost 10 days to figure out that tf2.4.0 do not support extra symbols by tf_exported_mscvc.lds.... 
I think it's because while building tf1.13 they contains the codes from tensorflow/python/framework/meta_graph.py in c++ dll and lib. but tf2.4.0 does not..
[build logs.txt](https://github.com/tensorflow/tensorflow/files/5352426/build.logs.txt)

Therefore i think this problem does not related with exporting extra symbols(https://github.com/tensorflow/tensorflow/issues/23542), but it is related with how to build c++ with additional libraries...(I could find metagraphdef it tf.compat.v1.MetaGraphDef in tf2.3.0 python documentation. So i think they do support metagraphdef.. but i couldn't use it on c++ 2.4.0)

If anyone knows how to figure out this problems, i would appreciate your advice.

[log and def_file_filter.zip](https://github.com/tensorflow/tensorflow/files/5352429/log.and.def_file_filter.zip)

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
> Please input the desired Python library path to use. Default is [C:\Anaconda3\envs\py37\lib\site-packages]

@yangjonghyeon,
Could you please try building TensorFlow using Python (outside of Anaconda environment) and check if it works?

Also, make sure you are following the steps mentioned as per the [build from source](https://www.tensorflow.org/install/source_windows) guide. Thanks!
