### ISSUE TITLE
Per Example Gradients fail with LSTM

### ISSUE THREAD

**Issue by n2cholas** [tensorflow/tensorflow#43904]
**System information**
Colab with `tf-nightly-gpu==2.4.0-dev20201007`

**Issue**
Per example gradients via `tf.vectorized_map` with an LSTM model fails. It works if you set `unroll=True` for the LSTM.

**Standalone code to reproduce the issue**
[Here](https://colab.research.google.com/gist/n2cholas/4bf3e70aa2ec310f69fe90bb21cb1747/lstm-per-eg-grads.ipynb) is a colab gist with the error.

**Comment by ravikyram** [comment]
I tried in colab with TF nightly version(`2.4.0-dev20201007`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/e19a7904bbdd99b4260df14e6fa39ab8/untitled437.ipynb).Thanks!

**Comment by Saduf2019** [comment]
I am able to replicate this issue on tf 2.5 , please find the [gist here](
https://colab.research.google.com/gist/Saduf2019/ff2ac41c5a428e86d6e834c44767599c/untitled589.ipynb)

**Comment by SuryanarayanaY** [comment]
With 2.4V the error is `ValueError: No pfor vectorization defined for StatelessCase`.

With 2.10V the issue replicated but with different error: `TypeError: dtype <dtype: 'variant'> is not compatible with 0 of dtype int64.`It seems now the StatelessCase gone that mentioned in above [comment](https://github.com/tensorflow/tensorflow/issues/43904#issuecomment-707227192).

With tf-nightly(2.12.0-dev20221113) error is `TypeError: dtype <dtype: 'variant'> is not compatible with 0 of dtype int64.` same as 2.10v.However in nightly for single batch also showing error which is not the observed behaviour in 2.4v and 2.10v. Please refer the attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/981fc9632784211a1bb9f226b9d0a3c6/43904-r1.ipynb).
```
one_loss, one_grad = compute_per_eg_grad((x[0], y[0]))  # not working
one_loss, one_grad = graph_compute_per_eg_grad((x[0], y[0]))   # not working
```
Moreover limitations of tf.vectorized_map() as per Documentation as follows.
https://github.com/tensorflow/tensorflow/blob/v2.10.0/tensorflow/python/ops/parallel_for/control_flow_ops.py#L452-L466
```
  Because `tf.vectorized_map` fully parallelizes the batch, this method will
  generally be significantly faster than using `tf.map_fn`, especially in eager
  mode. However this is an experimental feature and currently has a lot of
  limitations:

    - There should be no data dependency between the different semantic
      invocations of `fn`, i.e. it should be safe to map the elements of the
      inputs in any order.
    - Stateful kernels may mostly not be supported since these often imply a
      data dependency. We do support a limited set of such stateful kernels
      though (like RandomFoo, Variable operations like reads, etc).
    - `fn` has limited support for control flow operations.
    - `fn` should return nested structure of Tensors or Operations. However
      if an Operation is returned, it should have zero outputs.
    - The shape and dtype of any intermediate or output tensors in the
      computation of `fn` should not depend on the input to `fn`.
```

**Comment by SuryanarayanaY** [comment]
@n2cholas ,
Could you please check and confirm the changes in observed behaviours wrt 2.4V ,2.10V & nightly versions ?

**Comment by n2cholas** [comment]
@SuryanarayanaY confirming this is still an issue in the latest nightly `2.12.0-dev20221114`, reproducible with the original colab attached. https://colab.research.google.com/gist/n2cholas/4bf3e70aa2ec310f69fe90bb21cb1747/lstm-per-eg-grads.ipynb

**Comment by tilakrayal** [comment]
@n2cholas,
I tried to execute the mentioned code on tensorflow v2.15 with the Keras3.0 version and the code was executed without any issue/error & also observed that Per example gradients are not failing with LSTM. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/5be4fec82fd8d592d6bd32753bd8fd19/untitled1639.ipynb) and let us know the required changes happen? Thank you!

**Comment by n2cholas** [comment]
Yes looks like it works, thanks!
