### ISSUE TITLE
Docker cuda:10.0-cudnn7-devel-ubuntu16.04 - 3 out of 4 GPUs not utilized

### ISSUE THREAD

**Issue by suresh-s** [tensorflow/tensorflow#43919]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Docker Image : cuda:10.0-cudnn7-devel-ubuntu16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary):  binary
- TensorFlow version (use command below): tensorflow-gpu ==1.15.0
- Python version: python 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.2
- GPU model and memory: 4 GPU - Model : V100 Memory: 16160 MB

Environment:
Docker Image : cuda:10.0-cudnn7-devel-ubuntu16.04
Total GPUs : 4 nos Tesla V100 - GPU Memory 16.2 GB
CUDA: 10.2
Tensorflow-gpu - 1.15
keras: 2.2.5

**Describe the current behavior**

I have started the training. Logs shows all 4 GPU devices are prepared and allocated. but nvidia-smi command shows as below

![3 GPUs is not Utilized at all](https://user-images.githubusercontent.com/2168986/95613566-c90c8800-0a82-11eb-9b45-348bb7a144a3.png)

Please refer the screenshot, One GPU is 63% utilization and other three GPUs are 0 % Utilization. But There is no process id list.

What is the issue here? Why three GPUs are not utilized and empty process list?

**Comment by ravikyram** [comment]
@suresh-s 

Please, refer tested build configurations from [here](https://www.tensorflow.org/install/source#gpu)..Can you please upgrade to TF 2.3 and check for GPU devices. Thanks!
