### ISSUE TITLE
keras.utils.Sequence instance can't be deleted from memory after training

### ISSUE THREAD

**Issue by Moldoteck** [tensorflow/tensorflow#43913]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10 x64
- TensorFlow version (use command below):2.3.1
- Python version: 3.8
- CUDA/cuDNN : 10.1, 7.6.5
- GPU model and memory:

**Describe the current behavior**
I have created a custom class that inherits from keras.utils.Sequence
This class is reading some images with opencv into memory when constructed
If i just instantiate this class and after this i call 
```
import gc

myObj = Myclass(imgpaths)
del myObj
gc.colect()
```

everything is ok, but, if i am creating an instance + performing training:
```
import gc

train= Myclass(imgpaths)
validation= Myclass(imgpaths)

model = MyCustomModel()#i just used the pretrained Xception with 2 custom layers at the top for my case
model.fit(train, validation,...)
del train
del validation
gc.collect()
#...
#here i am doing other things
#...

```
then i can see that memory is not freed when calling gc.collect() and is freed only when the process is stopped
**Describe the expected behavior**

model should free the Sequence class passed to it when training is finished

**Standalone code to reproduce the issue**

#create a simple Sequence instance that is reading some images when constructed
#create an Xception model and call fit() with that sequence
#import gc, call del train_sequence, call gc.collect()
#create a for loop so that you will be able to see that memory is not freed (for i in range(1,999999999999999999): a=5)
#inspect RAM consumption and observe that RAM use is not decreasing after gc.collect(), meaning that keras model stores internally a reference of the Sequence object and it is not allowing to free the memory

**Comment by bhack** [comment]
Please can you share a very minimal buy runnable standalone example or Colab?

**Comment by Moldoteck** [comment]
ill share it tomorrow

**Comment by Saduf2019** [comment]
@Moldoteck 
Is this still an issue.

**Comment by Moldoteck** [comment]
@Saduf2019 , yes, but i don't have time to provide an (minimal) example now. So, i'll close this issue and will re-open when i'll have time for an example in Colab
