### ISSUE TITLE
Docker Image : cuda:10.0-cudnn7-devel-ubuntu16.04 -Training performance low - GPU Util% keep changing - Process Id section empty

### ISSUE THREAD

**Issue by suresh-s** [tensorflow/tensorflow#43927]
**System information**
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Docker Image : cuda:10.0-cudnn7-devel-ubuntu16.04
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): tensorflow-gpu ==1.15.0
Python version: python 3.6
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version: 10.2
GPU model and memory: 4 GPU - Model : V100 Memory: 16160 MB

collected some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)

[tf_env.txt](https://github.com/tensorflow/tensorflow/files/5359214/tf_env.txt)

Environment:
Docker Image : cuda:10.0-cudnn7-devel-ubuntu16.04
Total GPUs : 4 nos Tesla V100 - GPU Memory 16.2 GB
CUDA: 10.2
Tensorflow-gpu - 1.15
keras: 2.1.3

**Describe the current behavior**

nvidia-smi shows as below - that is all GPUs Utilisation is above 90% for few seconds 

![gpu all above 90 %](https://user-images.githubusercontent.com/2168986/95658306-00d50780-0b37-11eb-833b-a45d9214e6db.png)

Then nvidia-smi window shows as follows, that is all GPUs Utilisation is 0% for few seconds
![Gpu 0%](https://user-images.githubusercontent.com/2168986/95658335-472a6680-0b37-11eb-80ee-a817391f3d58.png)

Then nvidia-smi window shows as follows, that is  Utilisation% is random in all GPUs Utilisation for few seconds
![gpu random %](https://user-images.githubusercontent.com/2168986/95658620-6c1fd900-0b39-11eb-9d21-c6a5e43b9afd.png)

I have noticed Training performance is low and taking longer duration in Docker container mentioned here. Same code is working fine in Tesla K80 2 GPUs with CUDA 10.0 on a Dedicated server as shown below.

![Screen Shot 2020-10-10 at 9 34 06 PM](https://user-images.githubusercontent.com/2168986/95659895-d177c800-0b41-11eb-8c72-91dc83ef8d8a.png)

But in Docker container, Why GPU utilization% is keep changing unusually and why process list section is empty? Why CUDA version is shown a 10.2 in the cuda:10.0-cudnn7-devel-ubuntu16.04 Image refer first three nvidia-smi schreen shots? I have not installed CUDA 10.2 toolkit and CuDNN libraries in the Image. How can i solve this issue?

ps aux command shows processids but nvidia-smi doesn’t show

**Comment by Saduf2019** [comment]
@suresh-s 
Please note we do not have support for 1.x, could you please upgrade to 2.x and let us know in case you face any issues.
