### ISSUE TITLE
Using Orthogonal initializer in dense layer with backend set to fp16 gets stuck

### ISSUE THREAD

**Issue by Idokorro** [tensorflow/tensorflow#43928]
**System information**
- OS Platform and Distribution: Windows 10 64 bit
- TensorFlow installed from binary
- TensorFlow version (use command below): 2.3.1
- Python version: 3.7.6
- CUDA/cuDNN version: 10.1 / 7.6.5
- GPU model and memory: 2060 super, 8GB

**Describe the current behavior**

Using Orthogonal kernel initializer in dense layer with backend set to fp16 execution gets stuck during initialization. CPU runs at 100% and nothing happens. Changing initializer to Zeros fixes this. The same Orthogonal initializer in convolutional layer works fine.

**Standalone code to reproduce the issue**

```
import tensorflow as tf
import numpy as np

class SNetwork(tf.keras.Model):
    def __init__(self):
        super(SNetwork, self).__init__()

        self.conv1 = tf.keras.layers.Conv2D(filters=32,
                                            kernel_size=(8, 8),
                                            strides=(4, 4),
                                            padding="same",
                                            input_shape=(96, 96, 3),
                                            kernel_initializer=tf.keras.initializers.Orthogonal(np.sqrt(2)),
                                            bias_initializer=tf.keras.initializers.Zeros(),
                                            activation="linear")

        self.flatten = tf.keras.layers.Flatten()

        self.a_dense = tf.keras.layers.Dense(512,
                                             kernel_initializer=tf.keras.initializers.Orthogonal(np.sqrt(2)),
                                             bias_initializer=tf.keras.initializers.Zeros(),
                                             activation="relu")

        self.a_out = tf.keras.layers.Dense(9,
                                           bias_initializer=tf.keras.initializers.Zeros(),
                                           activation="softmax")

    def call(self, inputs):
        x = self.conv1(inputs)
        x = tf.keras.layers.LeakyReLU()(x)
        x = self.flatten(x)
        x = self.a_dense(x)
        x = self.a_out(x)
        return x

tf.keras.backend.set_floatx("float16")
tmp = np.zeros((1, 96, 96, 3), dtype="float16")
net = SNetwork()
print(net(tmp))
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue. With [TF v2.3](https://colab.research.google.com/gist/amahendrakar/8a6989ea636f62bdd78f1589db82cbde/43928.ipynb), code runs indefinitely. 

Whereas with [TF-nightly](https://colab.research.google.com/gist/amahendrakar/eeb7fa71b0c69bab167eb1dc1e310baf/43928-tf-nightly.ipynb), it throws an error stating `NotFoundError: Could not find device for node: {{node Qr}} = Qr[T=DT_HALF, full_matrices=false]`. Please find the attached gist. Thanks!

**Comment by sachinprasadhs** [comment]
Facing some error in both [Tf Nightly](https://colab.research.google.com/gist/sachinprasadhs/0f3578b6267419585defd81441e304ed/43928.ipynb) and [Tensorflow 2.5](https://colab.research.google.com/gist/sachinprasadhs/a8cb8bc968de2127bca02d8c834cfceb/43928.ipynb) version while trying to reproduce your issue, please find the attached gist. Thanks!

**Comment by Idokorro** [comment]
> Facing some error in both [Tf Nightly](https://colab.research.google.com/gist/sachinprasadhs/0f3578b6267419585defd81441e304ed/43928.ipynb) and [Tensorflow 2.5](https://colab.research.google.com/gist/sachinprasadhs/a8cb8bc968de2127bca02d8c834cfceb/43928.ipynb) version while trying to reproduce your issue, please find the attached gist. Thanks!

I think that is the expected behavior. You get the exception saying that you can’t use orthogonal initializer with half precision computation. Because there is no HALF kernel for QR decomposition. The problem with TF version 2.3 was that there was no exception. It would just get stuck in an infinite loop.

**Comment by sachinprasadhs** [comment]
If it is the expected behavior, can we close this issue then. Thanks!

**Comment by Idokorro** [comment]
I don't know who is responsible for writing kernels. It would be nice to be able to use orthogonal with half precision. But I'm guessing this is not a bug any more. So yes. You can close this issue.
