### ISSUE TITLE
LMDB Reading Feature

### ISSUE THREAD

**Issue by TimZaman** [tensorflow/tensorflow#4392]
I would like to see a native feature where LMDB files are read by tensorflow inside the graph. I know it can be done with placeholders but that's suboptimal.

In general, there are three ways of approaching this in TF.
(1) Native Implementation / Custom Data Reader
[https://www.tensorflow.org/versions/r0.10/how_tos/new_data_formats/index.html](https://www.tensorflow.org/versions/r0.10/how_tos/new_data_formats/index.html)
(2) Python Function Wrapping
[https://www.tensorflow.org/versions/r0.9/api_docs/python/script_ops.html](https://www.tensorflow.org/versions/r0.9/api_docs/python/script_ops.html)
(3) Placeholders
The functionality is neat but I require better performance..

If I were to do this myself, what are from a performance standpoint be the main differences between (1) and (2). In any case, it would be great if (1) ended up in the master branch.

**Comment by andydavis1** [comment]
thanks for posting. I think that it would be best to post your questions about relative performance differences between options (1) and (2) to stackoverflow first (tag 'tensorflow').

**Comment by TimZaman** [comment]
Thanks Andy.
But the feature request is 'LMDB reading feature', so the question can be considered an extra. Can you open this feature request up again, or are you excluding this from ever being implemented? That would make me sad.

**Comment by andydavis1** [comment]
My thinking was that you could first ask the question portion of this issue on StackOverflow (sometimes people may have a solution for you). If nothing useful turns up there, then feel free to enter another feature request (or we can reopen this one).

**Comment by bowang** [comment]
An open PR implementing the requested feature.
https://github.com/tensorflow/tensorflow/pull/9950
