### ISSUE TITLE
Avoiding data copy when using tf.py_func in Python

### ISSUE THREAD

**Issue by zhm9484** [tensorflow/tensorflow#43925]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): b'v1.13.0-rc2-5-g6612da8' 1.13.1
- Python version: 3.7.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: Tesla V100 32GB

**Describe the current behavior**
There may exists data copy from numpy array to tensorflow tensor when using ``tf.py_func``, and it costs extra time.

**Describe the expected behavior**
Avoid the data copy.

**Standalone code to reproduce the issue**
```python
import time
import tensorflow as tf
import numpy as np

arr = np.random.rand(100000000)


def get_arr():
    return arr


get = tf.py_func(get_arr, [], arr.dtype)

sess = tf.Session()

while 1:
    t = time.time()
    sess.run(get)
    print(time.time() - t)  # it outputs ~0.5s in my case
```

As it is mentioned [here](https://github.com/tensorflow/docs/blob/r1.13/site/en/api_docs/python/tf/py_func.md#args), 

> Important Note: Input and output numpy ndarrays of func are not guaranteed to be copies. In some cases their underlying memory will be shared with the corresponding TensorFlow tensors.

so in what cases do the numpy arrays share memory with tensors?

Or how to avoid the data copy?

Thanks for help!!

**Comment by amahendrakar** [comment]
@zhm9484,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to v2.3 and check if you are facing the same issue? Thanks!
