### ISSUE TITLE
To compile the code need portpicker. What for? is it safe?

### ISSUE THREAD

**Issue by Expert73** [tensorflow/tensorflow#43926]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): no
- TensorFlow version: master branch
- Python version: 3.8.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): bazelisk
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11/8
- GPU model and memory: 1070 ti 8 Gb

**Describe the problem**
To compile the code,  need portpicker. What for? is it safe?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@Expert73 

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by mihaimaruseac** [comment]
We are using it internally for building.

**Comment by Expert73** [comment]
thanks for answer!!!
