### ISSUE TITLE
AttributeError: 'GFile' object has no attribute 'Size'

### ISSUE THREAD

**Issue by tsumana** [tensorflow/tensorflow#4393]
Getting above error when running mnist_softmax.py

(tensorflow) :~/softwares/tensorflow/tensorflow/examples/tutorials/mnist$  python mnist_softmax.py 

Temporary work around would be to do following edit in the "tensorflow/tensorflow/contrib/learn/python/learn/datasets/base.py"

Replace  Line # 160    '    size = f.Size()  '        with       '   size = f.size()  '

As 'tensorflow/tensorflow/python/lib/io/file_io.py' has the function define for **size** not **Size**.

  def size(self):
    """Returns the size of the file."""
    return stat(self.__name).length

Failure is seen on running the tensorflow for the first time or cleaning up /tmp/data

**Comment by andydavis1** [comment]
Thanks for reporting, this but it looks like its already been fixed:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/datasets/base.py

**Comment by StrangeTcy** [comment]
The same error occured on tensorflow r0.10 with `/models/image/mnist/convolutional.py`. Changing `f.Size()` to `f.size()` solved it for me.

**Comment by codercotton** [comment]
I can confirm that f.size() works, where f.Size() was throwing this error.

**Comment by newwhitecheng** [comment]
yep Chage `f.Size()` to` f.size()` then it works.
