### ISSUE TITLE
support Quantization Aware Training for Conv2dTranspose->BathcNorm->Activation

### ISSUE THREAD

**Issue by eladc4** [tensorflow/tensorflow#43939]
**System information**
- TensorFlow version (you are using): 2.3.1

**Describe the feature and the current behavior/state.**
the sequence "Conv2dTranspose->BathcNorm->Activation" is not defined in
tensorflow_model_optimization/python/core/quantization/keras/default_8bit/default_8bit_quantize_layout_transform.py

**Who will benefit with this feature?**
anyone with this sequence in the network

**Comment by limbtio** [comment]
Is there any update on this feature?
QAT Conv2dTranspose support would really help my Unet training.

**Comment by eladc4** [comment]
@limbtio , my temporary solution is to train float with batch norm, and before retraining fold the the batch norm params into the conv2dtranspose (through editing the h5 file before load_weights

**Comment by limbtio** [comment]
@eladc4 thanks, but as far as I understand, the conv2dtranspose itself is not supported for quantization aware training. When I use tfmot.quantization.keras.quantize_model, I get the following error:
RuntimeError: Layer decoder_stage0a_transpose:<class 'tensorflow.python.keras.layers.convolutional.Conv2DTranspose'> is not supported. You can quantize this layer by passing a `tfmot.quantization.keras.QuantizeConfig` instance to the `quantize_annotate_layer` API.

**Comment by eladc4** [comment]
@limbtio you're correct of course, i quantize the network by cloning it and quantizing supported layers. it works because the ReLU following the conv2dtranspose is quantized, and quantization params can be inferred back to the conv2dtranspose, which works for my framework

**Comment by pjpratik** [comment]
@eladc4 I was checking if this issue still persists with TF 2.11 and tfmot 0.7.3. As mentioned [here](https://github.com/keras-team/keras/issues/16152#issuecomment-1111027984), the Conv2D transpose is supported in quantization aware training. I did try with latest version and found no errors. Could you please check this [gist](https://colab.research.google.com/gist/pjpratik/2f2266b58281262642ba1c5ca8dda496/43939.ipynb) and let us know if it helps. Thank you.
