### ISSUE TITLE
GPU support Software requirements links to incompatible CUDA Toolkit, cuDNN version

### ISSUE THREAD

**Issue by madhavij** [tensorflow/tensorflow#43933]
The various links provided by the https://www.tensorflow.org/install/gpu#software_requirements section leads to the newest version of CUDA Toolkit, cuDNN, whereas, Tensorflow  is only compatible with Toolkit 10.1 and cuDNN 7.6

This leads to a lot of errors when finding certain .dll files, GPU devices, and even running Models. 

If the links can be updated to point to the Archival download section ( to the last version, compatible with TF), it would save a lot of troubleshooting for new users who are setting up GPU support.

**Comment by ymodak** [comment]
![Screen Shot 2020-10-12 at 11 46 55 AM](https://user-images.githubusercontent.com/42785357/95780375-aba50d00-0c80-11eb-9e65-226a9a8eebc7.png)

@madhavij Thanks for your issue in the past we recognized this issue and implemented the same suggestion given by you. The `CUDA Toolkit` link given in the [software requirements ](https://www.tensorflow.org/install/gpu#software_requirements)points to the [cuda toolkit archive](https://developer.nvidia.com/cuda-toolkit-archive). Let me know if I am missing something here.

**Comment by madhavij** [comment]
I suppose similar linking can not be done with cuDNN due to the way it is downloaded from the NVIDIA page. I suppose that is not in the domain on tf how the cuDNN page displays its drivers for download. I think this suffices for now!

**Comment by ymodak** [comment]
Are you suggesting to include cuDNN archive to page ?
https://developer.nvidia.com/rdp/cudnn-archive

**Comment by madhavij** [comment]
An additional sentence mentioning the compatible versions of cuDNN and CUDA with this link. That would be helpful during the installation process!
