### ISSUE TITLE
Cannot load data from imdb_reviews datasets.

### ISSUE THREAD

**Issue by MAMOMIMOMU** [tensorflow/tensorflow#43943]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
- TensorFlow installed from (source or binary): conda
- TensorFlow version (use command below): 2.2.0
- Python version: 3.8.3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1, 7.6.5
- GPU model and memory: RTX2060, VRAM6GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When I run 
```python
import tensorflow as tf
import tensorflow_datasets as tfds

imdb, info = tfds.load('imdb_reviews', with_info=True, as_supervised=True)

```

the only output is 

```
Downloading and preparing dataset imdb_reviews (80.23 MiB) to /root/tensorflow_datasets/imdb_reviews/plain_text/0.1.0...
HBox(children=(FloatProgress(value=1.0, bar_style='info', description='Dl Completed...', max=1.0, style=Progre…
HBox(children=(FloatProgress(value=1.0, bar_style='info', description='Dl Size...', max=1.0, style=ProgressSty…
```
and loading takes forever to end(won't end).
Note: There are no errors or warnings shown, I just see these three lines, and the process never goes on.

The process succeeded once for some reason after many times of trials, and the output came with a warning. I forgot the contents but it ended with '...migrate to tensorflow_text'.
Of course this is the only time when I successfully got the loaded data so that's why I am here.

I tried to import data from keras.datasets and there seems no problems with it(was able to get the data imported with no warning and error).

I just want to know what this import problem is. Also I am wondering why there are no people facing the same problems.

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@MAMOMIMOMU 
I ran the code shared on tf 2.2 and 2.3 and do not face any error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/59e15dfe6b854dd88c55d1e0e4e2113f/untitled429.ipynb).

**Comment by PrattJena** [comment]
I ran the following code on tf 2.3 and didnt face any error too. You can find the code [here](https://colab.research.google.com/drive/13ZvPs_oVnKD9O4KefEpMulGHTv6SJUTe?usp=sharing)

**Comment by MAMOMIMOMU** [comment]
@Saduf2019 
@PrattJena 
Thank you two for running the code and sorry for not replying for some time.
I understand you ran the code without any problems, and I think the only difference in the environment is that I'm using docker. 
But it doesn't make any sense if tensorflow goes crazy on docker.

Where do you think there is a problem?

**Comment by MAMOMIMOMU** [comment]
Could you run the code on a container created by the docket file below please?

'''

FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
RUN apt-get update && apt-get install -y\
    sudo\
    wget\
    vim
WORKDIR /opt
RUN wget https://repo.continuum.io/archive/Anaconda3-2020.07-Linux-x86_64.sh &&\
    sh Anaconda3-2020.07-Linux-x86_64.sh -b -p /opt/anaconda3 &&\
    rm -f Anaconda3-2020.07-Linux-x86_64.sh

ENV PATH /opt/anaconda3/bin:$PATH

RUN conda update conda && conda install \
    keras\
    scipy\
    tensorflow-gpu

WORKDIR /

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--LabApp.tokenh=''"]

'''

**Comment by gowthamkpr** [comment]
@MAMOMIMOMU We dont support anaconda. Can you please post this issue in stackoverflow. Thanks!
