### ISSUE TITLE
Connecting to invalid output 1 of source node PartitionedCall_7 which has 1 outputs

### ISSUE THREAD

**Issue by moha23** [tensorflow/tensorflow#43942]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): tf-gpu-1.15
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0,7.4
- GPU model and memory: Nvidia GTX 1080 Ti, 11GB

I am training a slightly complicated network (tf-gpu1.15,keras), and it was running fine till I used a new function. This function is a modification of an addon available for tf2 ([dense_image_warp](https://github.com/tensorflow/addons/blob/v0.11.2/tensorflow_addons/image/dense_image_warp.py)) and I am trying to get it working with Tf-gpu1.15. Everything seems to work fine except while training I get this Invalid argument error. The error occurs at `model.train_on_batch` line, and has something to do with Adam optimiser, so a wild guess is the problem is with optimisation/finding gradients part. Since everything was running fine earlier, I wonder if there is something in the addon function which doesn't work in tf1, but everything seems to be compatible.`PartitionedCall_7` seems to be one of the outputs of using the addon function, why is it invalid? The function returns a tensor. Any clue with what the error is trying to say will be of great help, I just cannot figure out what is causing this.

I will try to get a minimal code to reproduce the error as soon as possible, putting this here just in case some one has a clue.

Error:

    ---------------------------------------------------------------------------
    InvalidArgumentError                      Traceback (most recent call last)
    ~/anaconda3/envs/myenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
       1364     try:
    -> 1365       return fn(*args)
       1366     except errors.OpError as e:

    ~/anaconda3/envs/myenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
       1347       # Ensure any changes to the graph are reflected in the runtime.
    -> 1348       self._extend_graph()
       1349       return self._call_tf_sessionrun(options, feed_dict, fetch_list,

    ~/anaconda3/envs/myenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py in _extend_graph(self)
       1387     with self._graph._session_run_lock():  # pylint: disable=protected-access
    -> 1388       tf_session.ExtendSession(self._session)
       1389 

    InvalidArgumentError: Node 'training/Adam/gradients/gradients/PartitionedCall_7_grad/PartitionedCall': Connecting to invalid output 1 of source node PartitionedCall_7 which has 1 outputs.

    During handling of the above exception, another exception occurred:

    InvalidArgumentError                      Traceback (most recent call last)
   

    ~/anaconda3/envs/myenv/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py in train_on_batch(self, x, y, sample_weight, class_weight, reset_metrics)
       1015       self._update_sample_weight_modes(sample_weights=sample_weights)
       1016       self._make_train_function()
    -> 1017       outputs = self.train_function(ins)  # pylint: disable=not-callable
       1018 
       1019     if reset_metrics:

    ~/anaconda3/envs/myenv/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py in __call__(self, inputs)
       3439     inputs = nest.flatten(inputs, expand_composites=True)
       3440 
    -> 3441     session = get_session(inputs)
       3442     feed_arrays = []
       3443     array_vals = []

    ~/anaconda3/envs/myenv/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py in get_session(op_input_list)
        484   if not _MANUAL_VAR_INIT:
        485     with session.graph.as_default():
    --> 486       _initialize_variables(session)
        487   return session
        488 

    ~/anaconda3/envs/myenv/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py in _initialize_variables(session)
        901     # marked as initialized.
        902     is_initialized = session.run(
    --> 903         [variables_module.is_variable_initialized(v) for v in candidate_vars])
        904     uninitialized_vars = []
        905     for flag, v in zip(is_initialized, candidate_vars):

    ~/anaconda3/envs/myenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
        954     try:
        955       result = self._run(None, fetches, feed_dict, options_ptr,
    --> 956                          run_metadata_ptr)
        957       if run_metadata:
        958         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

    ~/anaconda3/envs/myenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
       1178     if final_fetches or final_targets or (handle and feed_dict_tensor):
       1179       results = self._do_run(handle, final_targets, final_fetches,
    -> 1180                              feed_dict_tensor, options, run_metadata)
       1181     else:
       1182       results = []

    ~/anaconda3/envs/myenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
       1357     if handle is None:
       1358       return self._do_call(_run_fn, feeds, fetches, targets, options,
    -> 1359                            run_metadata)
       1360     else:
       1361       return self._do_call(_prun_fn, handle, feeds, fetches)

    ~/anaconda3/envs/myenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
       1382                     '\nsession_config.graph_options.rewrite_options.'
       1383                     'disable_meta_optimizer = True')
    -> 1384       raise type(e)(node_def, op, message)
       1385 
       1386   def _extend_graph(self):

    InvalidArgumentError: Node 'training/Adam/gradients/gradients/PartitionedCall_7_grad/PartitionedCall': Connecting to invalid output 1 of source node PartitionedCall_7 which has 1 outputs.

​
Same thing with SGD:

    InvalidArgumentError: Node 'training/SGD/gradients/gradients/PartitionedCall_7_grad/PartitionedCall': Connecting to invalid output 1 of source node PartitionedCall_7 which has 1 outputs.

**Comment by moha23** [comment]
works fine in tensorflow2.3.

**Comment by ravikyram** [comment]
@moha23 

TF 1.x is not actively supported.It is advisable to use latest 2.x versions for better performance . Is there any specific reason for using TF 1.15 only.Thanks!

**Comment by moha23** [comment]
So the tensorflow compression library currently has tf1.15 release only, though I hope tf2 release will come out sometime in future. I need my code to be compatible with that library, hence. Sigh.

**Comment by moha23** [comment]
I tried a simple training model, and it seems to work without these errors. [colab](https://colab.research.google.com/drive/1Zbe7jqdRbrEsZU3LG322GBBaFPZAcCSB?usp=sharing)

**Comment by ravikyram** [comment]
@moha23 

Please, grant me access for colab link. Thanks!

**Comment by moha23** [comment]
Sorry, made it public. Thanks @ravikyram

**Comment by ravikyram** [comment]
@moha23 

I am seeing no error messages in colab you shared. Please, help me with reproducible code to localize the issue faster.Thanks!

**Comment by moha23** [comment]
it seems the error comes for the complicated n/w so I am unable to reproduce it. Have moved to Tf2 for now.

**Comment by moha23** [comment]
@ravikyram I am able to reproduce the issue when using conv3D instead of conv2D. ([https://colab.research.google.com/drive/1Zbe7jqdRbrEsZU3LG322GBBaFPZAcCSB?usp=sharing](collab notebook)) I can't seem to figure out what is causing this?

**Comment by moha23** [comment]
The error doesn't occur for conv2D layers keeping everything else same, there is something in conv3D which is causing this.

**Comment by jvishnuvardhan** [comment]
@moha23 Looks like there is some shape incompatibility some where in the user code. Can you please share a simple standalone code (current code is too long to debug).

Please note that GitHub is only for Bug and performance related issues. If your issue is not related to bug/performance, then please open a stackoverflow issue where there is a large community to support each other. Thanks!

**Comment by moha23** [comment]
@jvishnuvardhan The code is at as minimum as I could bring it to, and it seems like a bug [(SO post).](https://stackoverflow.com/questions/64888204/connecting-to-invalid-output-1-of-source-node-partitionedcall-which-has-1-output) The extra code is for the tf-addon function which is not written by me and though I am not sure how to minimise it any further, I will try to.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
