### ISSUE TITLE
Keras: removing layers by creating new model not working

### ISSUE THREAD

**Issue by aditya-sarkar441** [tensorflow/tensorflow#43944]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Colab
- TensorFlow version (use command below):2.4.2
- Python version:3.8
- Bazel version (if compiling from source): Colab
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: Google Colab
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
**Problem facing**
Unable to remove batch normalization layers from Keras DenseNet121 model
**Describe the expected behavior**
I am trying to remove batch normalization layer from DenseNet121 model by creating a new model and transferring layers, except Batch normalization layer, from DenseNet121 model to the new one. 
[code provided below]
**Describe the current behavior**
Error was "ValueError: Input 0 of layer conv1/bn is incompatible with the layer: expected axis 3 of input shape to have value 64 but received input with shape [None, 512, 512, 3]"

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
https://colab.research.google.com/drive/1Efi-rVRZRzVWCJuPy06rm4doK_C2J2J_?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
//code
model1=Sequential()
for layer in model.layers:
    if(layer.name.find('bn')!=-1):
      model1.add(layer)
    
input_shape = (None,512,512,3)
model1.build(input_shape)

**Comment by amahendrakar** [comment]
@aditya-sarkar441,
On running the Colab notebook, I am facing an error stating `FileNotFoundError: [Errno 2] No such file or directory: 'drive/My Drive/sscheat/train/normal'`.

Could you please share all the supporting files necessary to run the notebook? Thanks!

**Comment by aditya-sarkar441** [comment]
Yeah, the link of the file is written below:
https://drive.google.com/drive/folders/1_mCr8xjjDXM7Myk95Fa1nxGxt7AWDIry?usp=sharing

Data will not be used in the model as I have not fitted the model on the data. I'm just trying to compile model with removed batchnormalisation layers from original keras Densenet121 model.

You can try running from second block after importing all the python modules.

**Comment by amahendrakar** [comment]
@aditya-sarkar441,
On running the code I am facing an error stating `OSError: Unable to open file (unable to open file: name = 'drive/My Drive/densenet.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)`

Could you please share the `densenet.h5` file and the contents of `filepath = 'dn_1.{accuracy:.4f}-{val_accuracy:.4f}.h5'` as well? Thanks!

**Comment by aditya-sarkar441** [comment]
https://drive.google.com/file/d/1CoUDfv62Wbr3F64x2b3cEPOG5hVAjSDZ/view?usp=sharing

Here are the weights.

You will not be requiring dn_1.{accuracy:.4f}-{val_accuracy:.4f}.h5. I've removed that section from the code. I've issue only in building model. You can download the weights, and then use it for running my code.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/5b25715f1d9ac708b14649d934453a6c/43944.ipynb). Thanks!

**Comment by aditya-sarkar441** [comment]
@amahendrakar It's still showing some error.

**Comment by jvishnuvardhan** [comment]
@aditya-sarkar441 Looks like your `model1` has BatchNorm layers. When I tried to print(model1.layers[3].name) --> it prints `conv2_block2_0_bn`.

AFAIK The root-cause of the issue is Sequential model cannot be used for concatenation. Sequential model is for single-input and single-output. Thanks!

**Comment by aditya-sarkar441** [comment]
Ok, so @jvishnuvardhan how can I remove batch normalization layers from Densenet121 model ? Is there a way ?

**Comment by aditya-sarkar441** [comment]
@jvishnuvardhan have you got any solution?

**Comment by aditya-sarkar441** [comment]
Poor solutions from Google Tensorflow. Thanks !!
