### ISSUE TITLE
Proper mesage for new contributor

### ISSUE THREAD

**Issue by aj07** [tensorflow/tensorflow#4394]
On page CONTRIBUTING.md there is a link for new contributor.
There is a need of space between how and to which i missing. But, it will look good if we change the message to getting started.

**Comment by aselle** [comment]
If I am interpreting your issue correctly, I assume you mean the [howto]. Howto is actually now a word!
https://www.google.com/search?q=howto%20definition
It's pretty similar to how electronic mail became email.
