### ISSUE TITLE
tf.function and PerReplica tf.Variable does not work together.

### ISSUE THREAD

**Issue by cloudhan** [tensorflow/tensorflow#43948]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution: Ubuntu 16.04 
- TensorFlow installed from (source or binary): binary from pip
- TensorFlow version (use command below): v2.3.0-rc2-23-gb36436b087 2.3.0
- Python version: 3.7.9
- GPU model and memory: 2080Ti

**Describe the current behavior**
```python
import tensorflow as tf
from tensorflow.python.distribute import values as value_lib

strategy = tf.distribute.MirroredStrategy()

shape = (3, 3)

def create_value(ctx):
    return tf.Variable(tf.random.normal(shape=shape))
    # return tf.random.normal(shape=shape)

v = strategy.experimental_distribute_values_from_function(create_value)
assert isinstance(v, value_lib.PerReplica)

@tf.function
def my_print(v):
    tf.print(v)

strategy.run(my_print, args=(v,))
```
results:
```
Traceback (most recent call last):
  File "4_tape_and_distribute/issue_report.py", line 19, in <module>
    strategy.run(my_print, args=(v,))
  File "/home/cloudhan/miniconda3/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1211, in run
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/home/cloudhan/miniconda3/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 2585, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/home/cloudhan/miniconda3/lib/python3.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 585, in _call_for_each_replica
    self._container_strategy(), fn, args, kwargs)
  File "/home/cloudhan/miniconda3/lib/python3.7/site-packages/tensorflow/python/distribute/mirrored_run.py", line 78, in call_for_each_replica
    return wrapped(args, kwargs)
  File "/home/cloudhan/miniconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/cloudhan/miniconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 846, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/home/cloudhan/miniconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/home/cloudhan/miniconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/cloudhan/miniconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/home/cloudhan/miniconda3/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run __inference_my_print_79: Can't copy Tensor with type resource to device /job:localhost/replica:0/task:0/device:GPU:0. [Op:__inference_my_print_79]
```

**Describe the expected behavior**
The above code should work. Currently, the only way to make it work is that:

in `create_value`, I create Tensor instead of Variable.

or
 
comment out `@tf.function` decorator of `my_print`

**Standalone code to reproduce the issue**
Colab notebook for additional information:
https://colab.research.google.com/drive/1YfbT43chs_whz2iPQOCLzqLsreJQvV8D?usp=sharing

**Comment by ravikyram** [comment]
I have tried in colab with TF version [2.3 gist](https://colab.research.google.com/gist/ravikyram/f2b5a442c8c2baebe235a8ed41c79e50/untitled441.ipynb) and was able to reproduce the issue.
In tf nightly version(`2.4.0-dev20201011`) [gist here](https://colab.research.google.com/gist/ravikyram/a3e08b008d388eb93cb1e59b5e13b5a6/untitled442.ipynb) I am seeing different error message(`InvalidArgumentError: cannot compute __inference_my_print_20 as input #0(zero-based) was expected to be a float tensor but is a resource tensor [Op:__inference_my_print_20]`). Thanks!

**Comment by bhack** [comment]
Probably the error It is a little bit cryptic in this case but still related to the use of tf.variable in tf.function.

See  https://github.com/tensorflow/tensorflow/blob/fcc4b966f1265f466e82617020af93670141b009/tensorflow/python/distribute/distribute_lib.py#L1148:L1155

**Comment by mdanatg** [comment]
@guptapriya what is the recommended way to use variables inside distributed functions?

**Comment by guptapriya** [comment]
assigning to @anj-s for this week

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tensorflow 2.5, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/2fcde8440166346db4df102301116b23/43948.ipynb). Thanks!

**Comment by crccw** [comment]
Please do not use experimental_distribute_values_from_function to create variables. Do this instead:

```
with strategy.scope():
  v = tf.Variable()
```

Under `strategy.scope()` variables are replicated among devices.  `experimental_distribute_values_from_function` should only to be used to create tensors.
