### ISSUE TITLE
Enable profiling in release builds

### ISSUE THREAD

**Issue by jenselofsson** [tensorflow/tensorflow#43958]
@tensorflow/micro

Profiler is turned on/off depending on if BUILD_TYPE is debug or any of the release builds.
It would be useful to be able to decouple profiling from the NDEBUG-define, so that it's possible to enable profiling for a release build. The reason for this is that the reference kernels runs slower in debug mode in release mode, so the measurements are not really representative 

One idea is to add a build type "release_with_profiling", which works in a similar way as "release_with_logs".

**Comment by mohantym** [comment]
Hi @jenselofsson !
Details of Concerned PR has copied to [tflite-micro](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/micro_profiler.h#:~:text=%7D%3B-,%23if%20defined(TF_LITE_STRIP_ERROR_STRINGS),//,-//%20This%20is) repo now. Please post in [TFLite-micro](https://github.com/tensorflow/tflite-micro) repo for  further assistance.
Thank you!
