### ISSUE TITLE
Could not find any cudnn.h matching version '8.0.4' in any subdirectory

### ISSUE THREAD

**Issue by tea321000** [tensorflow/tensorflow#43956]
**System information**
- OS Platform and Distribution: Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):source
- TensorFlow version:1.15.4
- Python version:3.7.9
- Installed using virtualenv? pip? conda?:conda
- Bazel version (if compiling from source):0.26.1
- GCC/Compiler version (if compiling from source):8.4.0
- CUDA/cuDNN version:CUDA:10.2 cuDNN:8.0.4
- GPU model and memory:Tesla P100

**Describe the problem**
I've installed cuDNN 8.0.4 in `/usr/local/cuda10-2`, and` libcudnn.so.8 libcudnn.so.8.0.4 `can be found in` /usr/local/cuda-10.2/lib64`. But after running `. /configure` command, I get the error "Could not find any cudnn.h matching version '8.0.4' in any subdirectory", and I don't know how to handle this error.

**Any other info / logs**
Terminal output:
```
**(base) atr1506@atr1506-PR1763GYW:~/tensorflow$ ./configure
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.26.1 installed.
Please specify the location of python. [Default is /home/atr1506/anaconda3/bin/python]:


Found possible Python library paths:
  /home/atr1506/anaconda3/lib/python3.8/site-packages
Please input the desired Python library path to use.  Default is [/home/atr1506/anaconda3/lib/python3.8/site-packages]

Do you wish to build TensorFlow with XLA JIT support? [Y/n]:
XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]:
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]:
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: y
TensorRT support will be enabled for TensorFlow.

Could not find any NvInferVersion.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/lib'
        '/lib/x86_64-linux-gnu'
        '/usr'
        '/usr/lib/x86_64-linux-gnu/libfakeroot'
        '/usr/local/cuda'
Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10.2]:


Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 8]: 8.0.4


Please specify the TensorRT version you want to use. [Leave empty to  default to TensorRT 5]:


Please specify the locally installed NCCL version you want to use. [Leave empty to use http://github.com/nvidia/nccl]:


Please specify the comma-separated list of base paths to look for CUDA libraries and headers. [Leave empty to use the default]:


Could not find any cudnn.h matching version '8.0.4' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/lib'
        '/lib/x86_64-linux-gnu'
        '/usr'
        '/usr/lib/x86_64-linux-gnu/libfakeroot'
        '/usr/local/cuda'
        '/usr/local/cuda-10.2'
Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10.2]:
```

**Comment by amahendrakar** [comment]
@tea321000,
TensorFlow 1.x is not actively supported. Could you please update TesnorFlow to v2.3 or TF-nightly. 

Every TensorFlow release is compatible with a certain CUDA/cuDNN version. Please take a look at the [tested build configurations](https://www.tensorflow.org/install/source#gpu) for more information. 

Also, please check similar issue [#42895](https://github.com/tensorflow/tensorflow/issues/42895) for reference. Thanks!

**Comment by tea321000** [comment]
Okay, I finally managed to deploy tf1.15 version on docker, and your advice helped me avoid wasting time compiling from source.

**Comment by humayunah** [comment]
> Okay, I finally managed to deploy tf1.15 version on docker, and your advice helped me avoid wasting time compiling from source.

Hey,

**Comment by humayunah** [comment]
> Okay, I finally managed to deploy tf1.15 version on docker, and your advice helped me avoid wasting time compiling from source.

Hey @tea321000. I have the same issue that I am not able to build it from docker directly, which is why I jumped to build it from source and got the same problem. Kindly explained how you deploy TF1.15 version in Docker-File?
Thanks!
