### ISSUE TITLE
How to build tflite C++ library for ios from tf 2.3 onwards?

### ISSUE THREAD

**Issue by rishabhrishu** [tensorflow/tensorflow#43955]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macos 10.15.3 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source
- TensorFlow version: v2.3.1
- Python version: 3.8.5
- Installed using virtualenv? pip? conda?: NA
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): Apple clang version 11.0.0 (clang-1100.0.33.17)
- CUDA/cuDNN version: NA
- GPU model and memory: NA

My workflow involved building tflite C++ library and using it on my app.

Steps that I used to take earlier:
```
> cd $TENSORFLOW_ROOT/tensorflow/lite/tools/make/
> ./build_ios_universal_lib.sh
```
This gives me a fat static library that I linked with my app. This was with tensorflow 2.0.0

Now I want to upgrade to tf 2.3.1, and when I use the same method, I get this warning:
```
=========================================================================
WARNING: This build script is deprecated and no longer maintained. Please
         refer to the iOS build guide to learn how to build the latest   
         version of TFLite static framework for iOS using bazel.         
         https://www.tensorflow.org/lite/guide/build_ios                 
=========================================================================
```
But on https://www.tensorflow.org/lite/guide/build_ios, there is no mention on how to build tflite C++ library. It only mentions about C library.

How do I continue to build tflite ios C++ library for future tf releases?
Or is this use-case deprecated, and I need to use C API instead?

**Comment by terryheo** [comment]
@yyoon, could you take a look?

**Comment by yyoon** [comment]
The recommended path is to either use the Swift API or the Obj-C API. Is there any particular reason you'd like to use C++ API instead? Would be nice to understand your use case.

**Comment by rishabhrishu** [comment]
I am a mobile developer, using C++ to build portable ML library, that work on both Android and iOS.
Here is my workflow:
- I code a cross-platform library on macOS, build/unit-test it on macOS
- then, build/test it on Linux (ec2)
- create android and ios builds of the library using the respective toolchains, and publish it for app developers.

Till now, I was using C++ APIs, as corresponding tflite libraries were present for all the platforms I build for. 

For future tflite releases, I will have to use C APIs instead.

**Comment by yyoon** [comment]
Thanks for sharing your workflow. I think there are two possibilities here.
1) Build the static library (the equivalent of `libtensorflow-lite.a`) for iOS using bazel.
2) Investigate ways to build for iOS using the recently added CMake support for TFLite.

I'll see if there's an easy way to produce the static library with existing build rules and get back to you.

**Comment by rishabhrishu** [comment]
Thanks for your help.
Looks like CMake support is very recent. I will have a look at it, and I will be happy to contribute if I find my way around it for generating Xcode build rules from it. 
If we are able to generate build rules for Xcode, then it will be very trivial to build for arm64-iphonesimulator for upcoming Apple silicon too.

**Comment by shariq-audiofocus** [comment]
I have a similar use case, I'm developing a portable ML library that works on iOS, linux, and possibly Android. Is there any way to build the tflite c++ api library and run it on iOS?

**Comment by shariq-audiofocus** [comment]
@rishabhrishu - I tried your method of adding libtensorflow-lite.a  (built on TF 2.1) to my XCode Project(via Targets > General > Frameworks, Libraries, and Embedded Content) but I'm still getting errors:
```
#include <tensorflow/lite/interpreter.h>  // ERROR: tensorflow/lite/interpreter.h file not found
```

Do you know what I might be missing? Did you do anything else?

**Comment by rishabhrishu** [comment]
@shariq-audiofocus You will have to add paths`tensorflow/tensorflow` and `tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers` to your header search paths. If you don't have flatbuffers, you need to run `tensorflow/tensorflow/lite/tools/make/download_dependencies.sh`

**Comment by shariq-audiofocus** [comment]
Thanks, I added those and it compiled. For others: I did have to correct the flatbuffers path to tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/**include** 

@rishabhkabra  How did you specify the path to the tflite binary? I tried putting the binary in Assets and getting the path this way:
```NSBundle *b = [NSBundle mainBundle];
NSString *dir = [b resourcePath];
NSArray *parts = [NSArray arrayWithObjects:
                  dir, @"assets", @"model.FS=8000.HS=32.BITS=32.tflite", (void *)nil];
NSString *path = [NSString pathWithComponents:parts];
const char *cpath = [path fileSystemRepresentation];
```


But got an error opening the file. Guessing it might be a permission thing.
```
    std::unique_ptr<tflite::FlatBufferModel> model;
    model = tflite::FlatBufferModel::BuildFromFile(tflitePath);
    if (!model) {
        LOGE("%s Failed to mmap model.", TAG);
        return;
    }
```

Error:
```
2021-01-11 15:20:26.616255-0800 AudioFocus[11506:2324920] Could not open '/Users/.../Library/Developer/CoreSimulator/Devices/C1B314F7-905E-415F-A03C-9E0BF8704DFE/data/Containers/Bundle/Application/FE50FA06-F535-4B0F-95E9-2881852287AD/AudioFocus.app/Assets/model.FS=8000.HS=32.BITS=32.tflite'.
```

**Comment by shariq-audiofocus** [comment]
For anyone else trying to do this - I was able to do this on tf-r2.5. You can follow these steps on a OSX machine to build libtensorflowlite.so

1) Git clone tensorflow
2) Git checkout r2.5
3) ./tensorflow/tflite/tools/make/download_dependencies.sh
* This may fail if you're using BSD grep which doesn't have the `-P` option. Install GNU grep and add it to your path to fix this
4) bazel build -c opt --config=v2 --verbose_failures --config=ios_arm64  //tensorflow/lite:libtensorflowlite.so 
* This may crash with an error "-z Unknown option" and/or "--version-script Unknown option" because the default ld on OSX doesn't have these options. You can fix this by editing tensorflow/lite/BUILD, comment out the two lines:
```
         ],
         "//tensorflow:windows": [],
         "//conditions:default": [
-            "-Wl,-z,defs",
-            "-Wl,--version-script,$(location //tensorflow/lite:tflite_version_script.lds)",
+            # "-Wl,-z,defs",
+            # "-Wl,--version-script,$(location //tensorflow/lite:tflite_version_script.lds)",
         ],
     }),
     per_os_targets = True,
```
5) Copy bazel-bin/tensorflow/lite/libtensorflowlite.so to your XCode project. Add it to your XCode project and include header paths as described in above comments
6) Build your app
* You may encounter an error about BITCODE in XCode. You can disable the BITCODE check under Build Settings > Build Options > Enable Bitcode. If you don't see this option, make sure you have "All" selected in the view tab.

**Comment by marcuseckert** [comment]
Thanks for your comments, I got everything working but the weird thing is the app store now complains when I want to submit my app using that tflite library. IMTS-90426 Invalid Swift Support - the Swift Support folder is missing. Any ideas why that is?
