### ISSUE TITLE
tf.keras.models.model_load outputs random evaluation values 

### ISSUE THREAD

**Issue by hamidkhb** [tensorflow/tensorflow#43954]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Custom
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11
- GPU model and memory: Nvidia Tesla v100 32 Gb

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

After loading a model the evaluation outputs random values:

```
model.evaluate(source_gen)
model.evaluate(target_gen)
```

> 2984/2984 [==============================] - 5s 2ms/step - loss: 0.1515 - accuracy: 0.9811
>4634/4634 [==============================] - 8s 2ms/step - loss: 1.4460 - accuracy: 0.7262

```
model.save_weights("models/weights.h5")
model.save("models/test.h5")

model_2 = tf.keras.models.load_model("models/test.h5")
model_2.load_weights("models/weights.h5")
model_2.evaluate(source_gen)
model_2.evaluate(target_gen)
```
>2984/2984 [==============================] - 5s 2ms/step - loss: 0.1515 - accuracy: 0.2070
>4634/4634 [==============================] - 8s 2ms/step - loss: 1.4460 - accuracy: 0.2473

also tried:

```
model.save("models/test.h5")
model_2 = tf.keras.models.load_model("models/test.h5")
model_2.evaluate(source_gen)
model_2.evaluate(target_gen)
```
>2984/2984 [==============================] - 5s 2ms/step - loss: 0.1515 - accuracy: 0.2070
>4634/4634 [==============================] - 8s 2ms/step - loss: 1.4460 - accuracy: 0.2473

**Comment by ravikyram** [comment]
@hamidkhb 

Can you please share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by hamidkhb** [comment]
Unfortunately not. I'm using a cluster I can give you full details of my conda environment. this is obviously a bug. There are many other people having the same problem in other forums.

**Comment by Hhessling** [comment]
We do have the same issue with a CNN using only Conv2D/Pooling2D/Dense layers. The model performance is 10% worse in accuracy when running evaluate on the model saved by the keras callback. Only 2.3.0/2.3.1 are affected versions. By using Version 2.2.0, the saved model archives the same performance as reported during training.

**Comment by jvishnuvardhan** [comment]
@hamidkhb Without standalone code it is difficult to support but lets try. Can you please save the model in `tf` format and then load and verify performance. May be you have a `custom_object` in your model that may not be loaded when you load a model saved in `h5` format. However, `tf` format can save `custom_objects`, so loading them should give you identical performance before saving and after loading.

@Hhessling Can you please share a simple standalone code to reproduce the issue? Thanks!

**Comment by hamidkhb** [comment]
```
model.save("models/test", save_format="tf")
model_2 = tf.keras.models.load_model("models/test")
model_2.evaluate(source_gen)
model_2.evaluate(target_gen)
```
>2984/2984 [==============================] - 5s 2ms/step - loss: 0.1847 - accuracy: 0.2045
>4634/4634 [==============================] - 8s 2ms/step - loss: 1.1504 - accuracy: 0.1744



Extra information:

- The problem doesn't exist in tf 2.1. but there are other problems and that was the reason why I needed to upgrade
- I don't have any `cusom_objekt`
- my model looks like this:
```
input_range = Input(input_shape_range, name="input_range")
input_doppler = Input(input_shape_doppler, name="input_doppler")

r = Conv2D(filters=8, kernel_size=(3, 3), padding="same", activation="relu", name="c1_r",
               data_format="channels_first")(input_range)
r = Conv2D(filters=16, kernel_size=(3, 3), padding="same", activation="relu", name="c2_r",
               data_format="channels_first")(r)
r = MaxPool2D(pool_size=(2, 2), strides=(2, 2), padding="Valid", name="m1_r",
                  data_format="channels_first")(r)
r = Conv2D(filters=16, kernel_size=(3, 3), padding="same", activation="relu", name="c3_r",
               data_format="channels_first")(r)
r = Conv2D(filters=32, kernel_size=(3, 3), padding="same", activation="relu", name="c4_r",
               data_format="channels_first")(r)
r = MaxPool2D(pool_size=(2, 2), strides=(2, 2), padding="Valid", name="m2_r",
                  data_format="channels_first")(r)

features_range = Flatten(name="flatten_r")(r)

d = Conv2D(filters=8, kernel_size=(3, 3), padding="same", activation="relu", name="c1_d",
               data_format="channels_first")(input_doppler)
d = Conv2D(filters=16, kernel_size=(3, 3), padding="same", activation="relu", name="c2_d",
               data_format="channels_first")(d)
d = MaxPool2D(pool_size=(2, 2), strides=(2, 2), padding="Valid", name="m1_d",
                  data_format="channels_first")(d)
d = Conv2D(filters=16, kernel_size=(3, 3), padding="same", activation="relu", name="c3_d",
               data_format="channels_first")(d)
d = Conv2D(filters=32, kernel_size=(3, 3), padding="same", activation="relu", name="c4_d",
               data_format="channels_first")(d)
d = MaxPool2D(pool_size=(2, 2), strides=(2, 2), padding="Valid", name="m2_d",
                  data_format="channels_first")(d)

features_doppler = Flatten(name="flatten_d")(d)

features = tf.keras.layers.concatenate([features_range, features_doppler], name="features" ,axis=1)

fc_2 = Dense(128, activation="relu", use_bias=True, name="fc_2",
                 kernel_regularizer= tf.keras.regularizers.l2(0.01))(features)
drop_2 = Dropout(0.2)(fc_2)
fc_3 = Dense(64, activation="relu", use_bias=True, name="fc_3",
                 kernel_regularizer= tf.keras.regularizers.l2(0.01))(drop_2)
drop_3 = Dropout(0.2)(fc_3)
out = Dense(5, use_bias=True, name="out")(drop_3)

model = tf.keras.Model(inputs=[input_range, input_doppler], outputs=out)
```

**Comment by jvishnuvardhan** [comment]
@hamidkhb Can you please share a simple standalone code with any publicly available data? Thanks!

**Comment by hamidkhb** [comment]
***Update for whom, that have the same issue***:

 I downgraded `tensorflow` to 2.1 and still had a problem with loading the model:
``` 
Traceback (most recent call last):
  File "/home/fe/khodabakhshandeh/anaconda3/envs/test_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-42e59c51e926>", line 1, in <module>
    tf.keras.models.load_model("models/model_source_F_test.h5")
  File "/home/fe/khodabakhshandeh/anaconda3/envs/test_env/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/fe/khodabakhshandeh/anaconda3/envs/test_env/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 168, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/home/fe/khodabakhshandeh/anaconda3/envs/test_env/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/fe/khodabakhshandeh/anaconda3/envs/test_env/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 106, in deserialize
    printable_module_name='layer')
  File "/home/fe/khodabakhshandeh/anaconda3/envs/test_env/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 292, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "/home/fe/khodabakhshandeh/anaconda3/envs/test_env/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 250, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: Functional

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fe/khodabakhshandeh/anaconda3/envs/test_env/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'ValueError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fe/khodabakhshandeh/anaconda3/envs/test_env/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1148, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/home/fe/khodabakhshandeh/anaconda3/envs/test_env/lib/python3.7/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/home/fe/khodabakhshandeh/anaconda3/envs/test_env/lib/python3.7/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/home/fe/khodabakhshandeh/anaconda3/envs/test_env/lib/python3.7/inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/home/fe/khodabakhshandeh/anaconda3/envs/test_env/lib/python3.7/inspect.py", line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/home/fe/khodabakhshandeh/anaconda3/envs/test_env/lib/python3.7/inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/home/fe/khodabakhshandeh/anaconda3/envs/test_env/lib/python3.7/inspect.py", line 733, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File "/home/fe/khodabakhshandeh/anaconda3/envs/test_env/lib/python3.7/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/home/fe/khodabakhshandeh/anaconda3/envs/test_env/lib/python3.7/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/home/fe/khodabakhshandeh/anaconda3/envs/test_env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tensorflow_core.estimator'
```

But I solved the problem by only saving the weights. so you have to **recreate the network, load the weights and then compile in this order** to avoid the error. I hope it works for you.

**Comment by jvishnuvardhan** [comment]
@hamidkhb I wouldn't suggest you to downgrade to `TF2.1` as newer versions have much better functionality and performance. Please provide full standalone code so that we will reproduce and resolve the issue. Thanks!

**Comment by sainttail** [comment]
@hamidkhb 

[This](https://github.com/sainttail/tensorflow-load-weights-problem) is the full standalone reproducible problem when `load_weights` each time get you a random evaluation loss and accuracy

**Comment by sainttail** [comment]
@jvishnuvardhan 

@hamidkhb 

[This](https://github.com/sainttail/tensorflow-load-weights-problem) is the full standalone reproducible problem when `load_weights` each time get you a random evaluation loss and accuracy

**Comment by jvishnuvardhan** [comment]
@sainttail I think there is no issue with `load_model`. I printed `model.weight` after loading weights, and they are exactly same. I think somewhere there is a randomness or shuffle implemented in your code. [Here](https://colab.research.google.com/gist/jvishnuvardhan/6900844bd0a9fb2b554c566cb501362b/untitled.ipynb) is gist for reference. 

Please verify once and close the issue. Thanks!

**Comment by jvishnuvardhan** [comment]
@sainttail [Here](https://colab.research.google.com/gist/jvishnuvardhan/52432d8d41d244ea7cd7596ef62a90ee/untitled62.ipynb) is a gist with another simple model. Loading weights doesn't affect the evaluation. Thanks!
