### ISSUE TITLE
 Error in tflite model deployment on android：Cannot copy to a TensorFlowLite tensor with 270000 bytes from a Java Buffer with 1228800 bytes.

### ISSUE THREAD

**Issue by QianZixi** [tensorflow/tensorflow#43965]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 20.04.1 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:OnePlus 5T
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):2.2.0
- Python version:3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

I downloaded the latest example project on github and used the object detection android project.
We have trained a detection model and want to transfer it to the object detection project.
Then when we run app, we encountered this error: java.lang.IllegalArgumentException: Cannot copy to a TensorFlowLite tensor (normalized_input_image_tensor) with 270000 bytes from a Java Buffer with 1228800 bytes.
The input of the original model is 300×300×3 int data, and the buffer length is 270000.
The input of our model is 320×320×3 float32 data, and the buffer length is 1228800.
We have tried our best to modify the parameters in the code, but still did not solve this problem.
Does anyone have the same problem? How do you solve similar problems.

**Comment by andrivm11** [comment]
Do you found the solution?

**Comment by andrivm11** [comment]
Did you find the solution?
