### ISSUE TITLE
could tf.feature_column.shared_embeddings support sequence_categorical_column_with_* in the future?

### ISSUE THREAD

**Issue by hazardwayne** [tensorflow/tensorflow#43967]

**Comment by ymodak** [comment]
@hazardwayne Perhaps you may want to raise a feature request for this issue. This will help to track the status and have a dedicated thread to discuss the functionality. Make sure to elaborate your proposal as well using this [feature template](https://github.com/tensorflow/tensorflow/issues/new?labels=type%3Afeature&template=30-feature-request.md). Thanks!

**Comment by hazardwayne** [comment]
Thanks for your help
