### ISSUE TITLE
Model Initialization take too much time

### ISSUE THREAD

**Issue by Zuu97** [tensorflow/tensorflow#43961]
**System information**
- OS Platform and Distribution : Linux Ubuntu 20.04 LTS
- TensorFlow installed from : Conda
- TensorFlow version : 2.2 GPU
- Python version: 3.7.8
- CUDA/cuDNN version: 10.1/7.6.5
- GPU model and memory: Geforce 940M & 4GB

I implemented simple feed forward NN for classfication task. which consists 5 dense layer. model weight size is 11.2 mb, but model initialization took almost 3 minutes. But training the model ( 50 epochs ) took almost 40 seconds. How can I fix this?

**Comment by ravikyram** [comment]
@Zuu97 

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by Zuu97** [comment]
`import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from matplotlib import cm
import os
import time
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input, Dropout, BatchNormalization
from tensorflow.keras.models import model_from_json, load_model
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

import tensorflow.keras.backend as K
K.clear_session()
import logging
logging.getLogger('tensorflow').disabled = True

from variables import*
from util import*

class DoggySymptom(object):
    def __init__(self):
        diseases, symtoms,encoder = get_chatbot_data()
        self.X = symtoms
        self.Y = diseases
        self.encoder = encoder
        print("Input Shape : {}".format(self.X.shape))
        print("Label Shape : {}".format(self.Y.shape))
        print("No: of Output classes : {}".format(len(set(self.Y))))

    def classifier(self):
        n_features = self.X.shape[1]
        num_classes = len(set(self.Y))
        inputs = Input(shape=(n_features,))
        x = Dense(dense1, activation='relu')(inputs)
        x = Dense(dense2, activation='relu')(x)
        x = Dense(dense2, activation='relu')(x)
        x = BatchNormalization()(x)
        x = Dense(dense3, activation='relu')(x)
        x = Dense(dense3, activation='relu')(x)
        x = Dense(dense4, activation='relu')(x)
        x = Dense(dense4, activation='relu')(x)
        x = Dropout(keep_prob)(x)
        outputs = Dense(num_classes, activation='softmax')(x)
        self.model = Model(inputs, outputs)

    def train(self):
        self.model.compile(
            loss='sparse_categorical_crossentropy',
            optimizer=Adam(learning_rate),
            metrics=['accuracy'],
        )
        self.history = self.model.fit(
                            self.X,
                            self.Y,
                            batch_size=64,
                            epochs=25,
                            validation_split=validation_split
                            )

    def load_model(self, model_weights):
        loaded_model = load_model(model_weights)
        loaded_model.compile(
                        loss='sparse_categorical_crossentropy',
                        optimizer=Adam(learning_rate),
                        metrics=['accuracy'],
                        )
        self.model = loaded_model

    def save_model(self):
        self.model.save(model_weights)

    def run(self):
        if os.path.exists(model_weights):
            print("Loading the model !!!")
            self.load_model(model_weights)
        else:
            print("Training the model !!!")
            t1_train = time.time()
            print(t1_train)

            self.classifier()
            t2_train = time.time()
            print(t2_train - t1_train)

            self.train()
            t3_train = time.time()
            print(t3_train - t2_train)`

Here is the code. At the end I compute the time it took for building the model and fit the model. 
To build the model it took 123 seconds this time and 20 seconds for training.

**Comment by ravikyram** [comment]
@Zuu97 

I tried in colab with TF version 2.3 and i am seeing the below error message(`ModuleNotFoundError: No module named 'variables'`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/bdeb035bdc7cf2b3914fb81584d4445d/untitled447.ipynb).Please, help us with reproducible code. Thanks!
