### ISSUE TITLE
Memory leak with tf.data.Dataset.map

### ISSUE THREAD

**Issue by jnd77** [tensorflow/tensorflow#43969]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18-04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf-nigthtly
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
Test is failing if line with dataset.map is not commented.
It shows the garbage collection is not working when using even a simple function with tf.data.Dataset.map

```
import tensorflow as tf
from tensorflow.python.framework.test_util import assert_no_garbage_created

class TestStandardTrainer(tf.test.TestCase):
  @assert_no_garbage_created
  def test_dataset_map(self):
      data_tensor = {'x': tf.constant([1, 2, 3], dtype=tf.float32),
                     'y': tf.constant([4, 5, 6], dtype=tf.float32)}
      dataset = tf.data.Dataset.from_tensor_slices(data_tensor)

      # We split the data in 2
      dataset = dataset.map(lambda x: (x, x))

import unittest
unittest.main(argv=['first-arg-is-ignored'], exit=False)

```

**Describe the expected behavior**

Test should pass

**Standalone code to reproduce the issue**
See above.

**Other info / logs**
None

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/f50501329b6b512e47b881216493fb4d/untitled436.ipynb)

**Comment by evonbevern** [comment]
I will be attempting to fix the issue in the next two weeks

**Comment by sachinprasadhs** [comment]
Was able to replicate your issue in Tensorflow 2.5, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/4fa68a3a37efccd1235514576d9f45b7/43969.ipynb). Thanks!

**Comment by LukeWood** [comment]
I am impacted by this.

**Comment by bhack** [comment]
Can we extend the test we have to cover this case?

https://github.com/tensorflow/tensorflow/blob/a07eb63a319efcc02c60f98c798453d2b21af785/tensorflow/python/data/kernel_tests/memory_cleanup_test.py#L161-L171

**Comment by LukeWood** [comment]
Perhaps we can also package inputs to a dictionary, run some operations on them, then unpackage as I have done in my test:

https://github.com/tensorflow/tensorflow/issues/43969#issuecomment-1170321569

**Comment by sushreebarsa** [comment]
@jnd77 This issue seems to be fixed using TF v2.13, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/fdf4d68cedebc4c5839496903992e100/43969.ipynb#scrollTo=2WVwdnrdS1TS) here. Thank you!

**Comment by jnd77** [comment]
I ran the gist, but the test still seems to be failing with 2.13.0 ...

**Comment by tilakrayal** [comment]
@jnd77,
I tried to execute the mentioned code on tensorflow v2.14 on both CPU and GPU & observed that the code was not failing with the Assertion error which happened on tensorflow v2.13. Kindly find the gist of [here](https://colab.research.google.com/gist/tilakrayal/7780e95a03c098b5000afeaf05181394/untitled1623.ipynb) and let me provide the opinion on the same. Thank you!

**Comment by jnd77** [comment]
@tilakrayal looks good to me. Thanks.

**Comment by tilakrayal** [comment]
@jnd77,
Glad the issue got resolved. Could you please feel free to move this issue to closed status. Thank you!
