### ISSUE TITLE
the number of parameters of a GRU layer is different on keras and tensorflow 2.X

### ISSUE THREAD

**Issue by andy6804tw** [tensorflow/tensorflow#43960]
calculating the number of parameters of a GRU layer : 
- nums = 3 * [ dh * (dh + dx) + dh ]
- 150 = 3 * [5*(5+4)+5]

why the total of GRU params in  tensorflow 2.X is different?

## Keras GRU

```py
from keras import Model, Input
from keras.layers import GRU

input = Input(shape=[10, 4])
gru = GRU(5)(input)
model = Model(input, gru)
model.summary()
```

```
Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)        [(None, 10, 4)]           0         
_________________________________________________________________
gru_1 (GRU)                 (None, 5)                 150       
=================================================================
Total params: 150
Trainable params: 150
Non-trainable params: 0
_________________________________________________________________
```

## Tensorflow2.X GRU
```py
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import GRU
 
input = Input(shape=[10, 4])
gru = GRU(5)(input)
model = Model(input, gru)
model.summary()
```

```
Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_2 (InputLayer)        [(None, 10, 4)]           0         
_________________________________________________________________
gru_2 (GRU)                 (None, 5)                 165       
=================================================================
Total params: 165
Trainable params: 165
Non-trainable params: 0
_________________________________________________________________
```

> Modify on 2020/10/13 11:19 AM CST

**Comment by amahendrakar** [comment]
@andy6804tw,
The input layer for Keras GRU is `input = Input(shape=[10, 4])`, whereas for TensorFlow GRU it is `input = Input(shape=[None,7])`

The behavior was consistent with both Keras and TensorFlow on running the same code. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/6ff936e3b0399a0740df3b58c2e5448a/43960.ipynb). 

Please correct me if I am wrong. Thanks!

**Comment by andy6804tw** [comment]
@amahendrakar sorry! This is my typo. We can see this case `input = Input(shape=[10, 4])`

My question is. When keras using Tensorflow1.X backend. The total params of network are 150. But in Tensorflow2.X keras, the total params of network are 165. 

Here is my code.
- [Tensorflow1.X Keras GRU Colab](https://colab.research.google.com/drive/1nrmJQo7Z299Nhn1_evcb0hruXO0ZVb-5?usp=sharing)
- [Tensorflow2.X keras GRU Colab](https://colab.research.google.com/drive/19Am_nplaH_gITqOtGaOS9d39HxZn3kxA?usp=sharing)

Thanks for your reply.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue, please find the attached gist. 

- [TensorFlow 1.15 GRU](https://colab.research.google.com/gist/amahendrakar/e0c2d98d99ece710c718db44a06fecd7/43960-1-15.ipynb)
- [TensorFlow 2.3 GRU](https://colab.research.google.com/gist/amahendrakar/47280c4dbbbfa43146bb6bcc0616e533/43960-2-3.ipynb)
- [TensorFlow nightly GRU](https://colab.research.google.com/gist/amahendrakar/71107218f09d13110400188a22e3e987/43960-tf-nightly.ipynb)

Thanks!

**Comment by jvishnuvardhan** [comment]
@andy6804tw By default `reset_after=False` in `TF1.x` whereas in `TF2.x`, `reset_after=True` by default. If I set these parameters same, then the params are same number. [In](https://colab.research.google.com/gist/jvishnuvardhan/904b0c76eb4a68e2346246cb51ba48e3/43960-1-15.ipynb) this gist, i set `reset_after=True` in `TF1.x`, then the total parameters are `165` as you have seen in case of `TF2.x`. Thanks!

Please close the issue if this was resolved for you. Thanks!

**Comment by andy6804tw** [comment]
@jvishnuvardhan Thanks for your reply. The `reset_after=True` parameter solve my question. 
But why `reset_after` in `TF2.x` set True by default. Is there any reference for me?

I hope you will be able to provide the information. Thanks!

**Comment by jvishnuvardhan** [comment]
@andy6804tw I am closing this issue as this was resolved. 

Please check [this SO](https://stackoverflow.com/questions/57318930/calculating-the-number-of-parameters-of-a-gru-layer-keras#:~:text=As%20you%20can%20see%2C%20the,*%202%20%3D%209600%20in%20tensorflow2%20.) page for more details on GRU in TF1.x and TF2.x. Thanks!

**Comment by andy6804tw** [comment]
Thanks! [this SO](https://stackoverflow.com/questions/57318930/calculating-the-number-of-parameters-of-a-gru-layer-keras#:~:text=As%20you%20can%20see%2C%20the,*%202%20%3D%209600%20in%20tensorflow2%20.)  page explains very clearly. I appreciate your help very much. :+1:
