### ISSUE TITLE
about RuntimeError: Use `_distributed_apply()` instead of `apply_gradients()` in a cross-replica context.

### ISSUE THREAD

**Issue by xhjcxxl** [tensorflow/tensorflow#43974]
the tf version is 1.14
when i use mirrored_strategy = tf.distribute.MirroredStrategy(), there are a error:
    self.opt_op = self.optimizer.minimize(self.loss)
  File "miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 413, in minimize
    name=name)
  File "miniconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 564, in apply_gradients
    raise RuntimeError("Use `_distributed_apply()` instead of "
RuntimeError: Use `_distributed_apply()` instead of `apply_gradients()` in a cross-replica context.

how can i fix it?

**Comment by ravikyram** [comment]
@xhjcxxl 

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by NNDEV1** [comment]
Has anyone found the solution to this error? Trying to use a TPU.
