### ISSUE TITLE
Cannot save mixed precision model when using activity regularizer

### ISSUE THREAD

**Issue by ManuelWiese** [tensorflow/tensorflow#43978]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.5 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.1
- Python version: Python 3.6.9
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 10.1/7.6.5.32-1+cuda10.1
- GPU model and memory: RTX 2080Ti 11Gb

**Describe the current behavior**
When using activity_regularizer in a subclassed keras model, it is not possible to save the model if mixed_float16 policy is set.
If mixed_float16 is not set, the example below does work.

**Describe the expected behavior**
The example below should save model.

**Standalone code to reproduce the issue**

``` python:
import numpy as np

import tensorflow as tf
from tensorflow.keras.mixed_precision import experimental as mixed_precision


policy = mixed_precision.Policy('mixed_float16')
mixed_precision.set_policy(policy)


class TestModel(tf.keras.models.Model):
    def __init__(self, **kwargs):
        super(TestModel, self).__init__(**kwargs)
        self.conv_0 = tf.keras.layers.Conv2D(1, (1, 1), activity_regularizer='l1')
    
    def call(self, x):
        return self.conv_0(x)
    
    def get_config(self):
        return {}


model = TestModel()
_ = model(np.zeros((1, 16, 16, 3)))
model.save("test_model")
```

**Other info / logs** 
```
ValueError: Python inputs incompatible with input_signature:
  inputs: (
    Tensor("StatefulPartitionedCall:0", shape=(None, 16, 16, 1), dtype=float16))
  input_signature: (
    TensorSpec(shape=<unknown>, dtype=tf.float32, name=None))
```

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3, nightly version(`2.4.0-dev20201012`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/82a4883ec95afede05843ed9ed627a8e/untitled453.ipynb).Thanks!

**Comment by ravikyram** [comment]
@ManuelWiese 

I have made small changes to your code and i am not seeing any issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/1754042ea2ebf9446f560cc6254d5945/untitled454.ipynb).Please, verify once and let us know if it solves your question.. Thanks!

**Comment by ManuelWiese** [comment]
@ravikyram 
Thanks for your reply! I looked through your code and as far as i understand the mixed precision policy is not set. Without mixed precision the example works perfectly.

**Comment by jvishnuvardhan** [comment]
I can reproduce the issue when . [Here](https://colab.research.google.com/gist/jvishnuvardhan/d17691aa4682b20d939bf6e89521d816/untitled58.ipynb) is the gist for our reference. 

Note: There is no error when `activity_regularizer='l1'` is removed from the following line
`self.conv_0 = tf.keras.layers.Conv2D(1, (1, 1), activity_regularizer='l1')`

**Comment by reedwm** [comment]
Thank you for the very short and clean example to reproduce! I will have a fix soon.

**Comment by ManuelWiese** [comment]
Thank you for the fix. It does work in tf-nightly now!
