### ISSUE TITLE
run-time error

### ISSUE THREAD

**Issue by X-swordx** [tensorflow/tensorflow#43976]
internal/modules/cjs/loader.js:1122
  return process.dlopen(module, path.toNamespacedPath(filename));

**Comment by Saduf2019** [comment]
@X-swordx 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced], if possible share a colab gist with the error reported.
