### ISSUE TITLE
ERROR: An error occurred during the fetch of repository 'local_config_cc':

### ISSUE THREAD

**Issue by li744831579** [tensorflow/tensorflow#43979]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  windows 10 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):     source 
- TensorFlow version:   2.3
- Python version: 3.8.5
- Bazel version (if compiling from source):    3.6.0
- GCC/Compiler version (if compiling from source):   MSVC
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Repository rule cc_autoconf defined at:
  C:/users/10184590/_bazel_10184590/z5zmmi7q/external/bazel_tools/tools/cpp/cc_configure.bzl:143:30: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cc':
   Traceback (most recent call last):
        File "C:/users/10184590/_bazel_10184590/z5zmmi7q/external/bazel_tools/tools/cpp/cc_configure.bzl", line 120, column 36, in cc_autoconf_impl
                configure_windows_toolchain(repository_ctx)
        File "C:/users/10184590/_bazel_10184590/z5zmmi7q/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 783, column 35, in configure_windows_toolchain
                msvc_vars_x64 = _get_msvc_vars(repository_ctx, paths, "x64")
        File "C:/users/10184590/_bazel_10184590/z5zmmi7q/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 631, column 32, in _get_msvc_vars
                env = setup_vc_env_vars(repository_ctx, vc_path)
        File "C:/users/10184590/_bazel_10184590/z5zmmi7q/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 387, column 24, in setup_vc_env_vars
                _check_env_vars(env_map, cmd, expected = envvars)
        File "C:/users/10184590/_bazel_10184590/z5zmmi7q/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 393, column 32, in _check_env_vars
                auto_configure_fail(
        File "C:/users/10184590/_bazel_10184590/z5zmmi7q/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
                fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail:
Auto-Configuration Error: Setting up VC environment variables failed, WINDOWSSDKDIR is not set by the following command:
    "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\VCVARSALL.BAT" amd64  -vcvars_ver=14.27.29110
INFO: Repository icu instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule third_party_http_archive defined at:
  F:/git/tensorflow/tensorflow/third_party/repo.bzl:216:43: in <toplevel>
INFO: Repository 'icu' used the following cache hits instead of downloading the corresponding file.
 * Hash 'dfc62618aa4bd3ca14a3df548cd65fe393155edd213e49c39f3a30ccd618fc27' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/unicode-org/icu/archive/release-64-2.zip
If the definition of 'icu' was updated, verify that the hashes were also updated.
ERROR: F:/git/tensorflow/tensorflow/tensorflow/tools/build_info/BUILD:9:10: //tensorflow/tools/build_info:gen_build_info depends on @local_config_cc//:cc-compiler-x64_windows in repository @local_config_cc which failed to fetch. no such package '@local_config_cc//':
Auto-Configuration Error: Setting up VC environment variables failed, WINDOWSSDKDIR is not set by the following command:
    "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\VCVARSALL.BAT" amd64  -vcvars_ver=14.27.29110
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed
INFO: Elapsed time: 31.340s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (201 packages loaded, 3847 targets configured)
    Fetching C:/users/10184590/_bazel_10184590/z5zmmi7q/external/icu; Extracting C:/users/10184590/_bazel_10184590/z5zmmi7q/external/icu/release-64-2.zip 24s
    Fetching @llvm-project; fetching 15s
    Fetching @boringssl; fetching 14s
    Fetching .../_bazel_10184590/z5zmmi7q/external/llvm-project; Extracting C:/users/10184590/_bazel_10184590/z5zmmi7q/external/llvm-project/a2291a58bf1c860d026581fee6fe96019dc25440.tar.gz 14s
    Fetching ...184590/_bazel_10184590/z5zmmi7q/external/boringssl; Extracting C:/users/10184590/_bazel_10184590/z5zmmi7q/external/boringssl/80ca9f9f6ece29ab132cce4cf807a9465a18cfac.tar.gz 14s

**Comment by Saduf2019** [comment]
@li744831579 
Please refer to the bazel build related [issue](https://github.com/tensorflow/tensorflow/issues/23719) with same error and let us know if it helps.
