### ISSUE TITLE
Docker build devel-gpu build fails with 8.0-cudnn5-devel (Cannot find cudnn.h under .../lib)

### ISSUE THREAD

**Issue by pwaller** [tensorflow/tensorflow#4397]
**Summary**: Why is it looking for the header file under the lib directory?

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

* https://github.com/tensorflow/tensorflow/issues/3989 (and references within)

### Environment info

Operating System: Ubuntu 16.04. Docker 1.12.1.

### If possible, provide a minimal reproducible example

1. Modify [devel-gpu](https://github.com/tensorflow/tensorflow/blob/4addf4b5806cd731949c6582a83f5824599cd1ef/tensorflow/tools/docker/Dockerfile.devel-gpu) to read "`FROM nvidia/cuda:8.0-cudnn5-devel`".

1. Run `docker build -f Dockerfile.devel-gpu -t tf` from the `/tensorflow/tools/docker` directory. (HEAD @ 4addf4b5806cd731949c6582a83f5824599cd1ef at time of posting)

### What other attempted solutions have you tried?

None yet, I'm not sure how to poke Bazel. I will continue poking around after filing the issue.

### Logs or other output that would be helpful

```
$ docker build -f Dockerfile.devel-gpu -t tf .

[snip]

Step 23 : RUN ./configure &&     bazel build -c opt --config=cuda tensorflow/tools/pip_package:build_pip_package &&     bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/pip &&     pip install --upgrade /tmp/pip/tensorflow-*.whl
 ---> Running in 1f99527c7748
No Google Cloud Platform support will be enabled for TensorFlow
INFO: Reading 'startup' options from /root/.bazelrc: --batch
Extracting Bazel installation...
____Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
INFO: Reading 'startup' options from /root/.bazelrc: --batch
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/tensorflow/third_party/gpus/cuda_configure.bzl", line 412
		_create_cuda_repository(repository_ctx)
	File "/tensorflow/third_party/gpus/cuda_configure.bzl", line 344, in _create_cuda_repository
		_find_cudnn_header_dir(repository_ctx, cudnn_install_base...)
	File "/tensorflow/third_party/gpus/cuda_configure.bzl", line 233, in _find_cudnn_header_dir
		fail("Cannot find cudnn.h under %s" %...)
Cannot find cudnn.h under /usr/local/cuda-8.0/targets/x86_64-linux/lib.
Configuration finished
INFO: Reading 'startup' options from /root/.bazelrc: --batch
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/tensorflow/third_party/gpus/cuda_configure.bzl", line 412
		_create_cuda_repository(repository_ctx)
	File "/tensorflow/third_party/gpus/cuda_configure.bzl", line 344, in _create_cuda_repository
		_find_cudnn_header_dir(repository_ctx, cudnn_install_base...)
	File "/tensorflow/third_party/gpus/cuda_configure.bzl", line 233, in _find_cudnn_header_dir
		fail("Cannot find cudnn.h under %s" %...)
Cannot find cudnn.h under /usr/lib/x86_64-linux-gnu.
____Elapsed time: 0.391s
The command '/bin/sh -c ./configure &&     bazel build -c opt --config=cuda tensorflow/tools/pip_package:build_pip_package &&     bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/pip &&     pip install --upgrade /tmp/pip/tensorflow-*.whl' returned a non-zero code: 1
```

**Comment by pwaller** [comment]
I pieced together that I could make it work by modifying `CUDNN_INSTALL_PATH` to `/usr/local/cuda` in the Dockerfile.

**Comment by pwaller** [comment]
The error message is confusing, because it looks like it almost finds the file since it looks in `/usr/local/cuda-8.0/targets/x86_64-linux/lib` but the header file is in fact in `/usr/local/cuda-8.0/targets/x86_64-linux/include`.

**Comment by gunan** [comment]
This is expected.
Cuda8 still does not have APT packages we can install.
APT packages deploy all cuda libraries/headers to different locations than nvidia's installer.
Thus our cuda7.5 images wont work out of the box with cuda 8 images.

@flx42, could you verify the above information?

**Comment by flx42** [comment]
Correct, we don't have deb packages of cuDNN v5 on CUDA 8.0 since CUDA 8.0 is not final yet. But, as I said [here](https://github.com/tensorflow/tensorflow/issues/3989#issuecomment-241933622), ideally the configure script should look in both `/usr/local/cuda` and `/usr`.

**Comment by gunan** [comment]
@davidzchen @martinwicke

**Comment by gunan** [comment]
Would this be as simple as including both possible directories here (and lines below and above, all the environment variables we use to point to cuda library locations)
https://github.com/tensorflow/tensorflow/blob/4addf4b5806cd731949c6582a83f5824599cd1ef/tensorflow/tools/docker/Dockerfile.devel-gpu#L91

**Comment by flx42** [comment]
@gunan well, there is already a `CUDNN_INSTALL_PATH` line here, simply removing it also work.
Ideally, the Dockerfile should not have to specify `CUDNN_INSTALL_PATH`, `CUDA_PATH` or `CUDA_TOOLKIT_PATH`, if the configure steps use sensible default values when looking for CUDA/cuDNN. Those variables should only be needed when you have a truly unusual CUDA install path like `/home/felix/cuda`.

Also, the `LD_LIBRARY_PATH` line you mentioned is bogus, see #4363

**Comment by gunan** [comment]
Just tried removing those, and but it looks like we need the path:
/usr/local/cuda/extras/CUPTI/lib64
As without it my tests are failing with:
 tensorflow/stream_executor/dso_loader.cc:105] Couldn't open CUDA library libcupti.so. LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:
F tensorflow/core/platform/default/gpu/cupti_wrapper.cc:59] Check failed: ::tensorflow::Status::OK() == (::tensorflow::Env::Default()->GetSymbolFromLibrary( GetDsoHandle(), kName, &f)) (OK vs. Not found: /workspace/pip_test/venv/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: cuptiActivityRegisterCallbacks)could not find cuptiActivityRegisterCallbacksin libcupti DSO

Should we fix the dso_loader.cc instead?

**Comment by flx42** [comment]
Don't remove the CUPTI path, just don't erase the previous value of `LD_LIBRARY_PATH` ;)

My fix:
```
-ENV LD_LIBRARY_PATH /usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64                                                                                                                                                                                                  
+ENV LD_LIBRARY_PATH /usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH  
```

**Comment by gunan** [comment]
@flx42 This is also fixed, right?

**Comment by flx42** [comment]
@gunan: yes, I think it is.

**Comment by pwaller** [comment]
My minimum reproduce (running docker build) still fails when I run on the master branch.

**Comment by pwaller** [comment]
This patch makes it work (updating the `CUDNN_INSTALL_PATH` to `/usr/local/cuda` as before).

<details>
```diff
--- a/tensorflow/tools/docker/Dockerfile.devel-gpu
+++ b/tensorflow/tools/docker/Dockerfile.devel-gpu
@@ -89,7 +89,7 @@ WORKDIR /tensorflow
 
 # Configure the build for our CUDA configuration.
 ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH
-ENV CUDNN_INSTALL_PATH /usr/lib/x86_64-linux-gnu
+ENV CUDNN_INSTALL_PATH /usr/local/cuda
 ENV TF_NEED_CUDA 1
 ENV TF_CUDA_COMPUTE_CAPABILITIES=3.0,3.5,5.2
 
@@ -108,4 +108,13 @@ EXPOSE 6006
```
</details>

**Comment by flx42** [comment]
@pwaller: you are not using the right Dockerfile.
In master, there is no more `CUDNN_INSTALL_PATH`.

**Comment by pwaller** [comment]
@flx42, I mis-spoke. I have to re-add it in order to make it work. If it is absent, I get the above error.

**Comment by pwaller** [comment]
Sorry, one moment while I understand what has happened, clearly this is at odds with the diff I posted.

**Comment by pwaller** [comment]
I had a dirty worktree from trying a few things. Here is the correct diff which makes it work for me:

```diff
--- a/tensorflow/tools/docker/Dockerfile.devel-gpu
+++ b/tensorflow/tools/docker/Dockerfile.devel-gpu
@@ -89,6 +89,7 @@ WORKDIR /tensorflow
 
 # Configure the build for our CUDA configuration.
 ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH
+ENV CUDNN_INSTALL_PATH /usr/local/cuda
 ENV TF_NEED_CUDA 1
 ENV TF_CUDA_COMPUTE_CAPABILITIES=3.0,3.5,5.2
 
@@ -107,4 +108,13 @@ EXPOSE 6006
```

**Comment by gunan** [comment]
I am sorry, however I cannot reproduce the problem you are seeing.
Here is what I did:

$ git clone git@github.com:tensorflow/tensorflow
$ cd tensorflow
$ nvidia-docker build  -f tensorflow/tools/docker/Dockerfile.devel-gpu -t tf tensorflow/tools/docker

Outcome:
Successfully built c8163ce55259

Then:
$ nvidia-docker run -it c8163ce55259 bash
$ python -c "import tensorflow as tf; print tf.test.is_gpu_available()"
....
True

Maybe you are not using nvidia docker?
As I cannot reproduce the problem, I am inclined to leave the issue as closed.

**Comment by flx42** [comment]
@gunan: same for me, it works. 
Also, `nvidia-docker` is actually passthrough to `docker` when doing a `build`. Using nvidia-docker is only important for `run`.

**Comment by pwaller** [comment]
In the minimal reproduce in the original post, it says:

> 1. Modify devel-gpu to read "FROM nvidia/cuda:8.0-cudnn5-devel".

Did you guys do that?

**Comment by gunan** [comment]
Master is already changed to use that image, you do not need to edit
anymore.

**Comment by pwaller** [comment]
A key part of the minimal reproduce example is to modify the dockerfile to be based off cudnn8. Did you spot that? Apols for terse phone reply.

On 20 October 2016 23:16:03 BST, gunan <notifications@github.com> wrote:
>I am sorry, however I cannot reproduce the problem you are seeing.
>Here is what I did:
>
>$ git clone git@github.com:tensorflow/tensorflow
>$ cd tensorflow
>$ nvidia-docker build  -f tensorflow/tools/docker/Dockerfile.devel-gpu
>-t tf tensorflow/tools/docker
>
>Outcome:
>Successfully built c8163ce55259
>
>Then:
>$ nvidia-docker run -it c8163ce55259 bash
>$ python -c "import tensorflow as tf; print tf.test.is_gpu_available()"
>....
>True
>
>Maybe you are not using nvidia docker?
>As I cannot reproduce the problem, I am inclined to leave the issue as
>closed.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tensorflow/tensorflow/issues/4397#issuecomment-255243145

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gunan** [comment]
All tensorflow dockerfiles should be upgraded to use nvidia/cuda:8.0-cudnn5-devel.
And our CI is able to build fine with all of these dockerfiles.
Maybe your repository is outdated?
Since I cannot reproduce the problem, I am sorry but I have no idea how to help.

**Comment by pwaller** [comment]
Thanks very much @gunan et al for taking the time to try and reproduce and reply.

The r0.11 branch now works, where it was not before. (Even though I had an uptodate repository and an uptodate docker base image pulled before, but doing it this time it worked).

As an aside, the master branch @ 446b1cb fails with the below error message. It's not stopping me from getting anything working though because r0.11 appears to be building fine.

```
Step 20 : RUN tensorflow/tools/ci_build/builds/configured GPU     bazel build -c opt --config=cuda tensorflow/tools/pip_package:build_pip_package &&     bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/pip &&     pip install --upgrade /tmp/pip/tensorflow-*.whl &&     rm -rf /tmp/pip &&     rm -rf /root/.cache
 ---> Running in fe048e7cdc07
/tensorflow /tensorflow
/tensorflow /tensorflow
Can't find swig.  Ensure swig is in $PATH or set $SWIG_PATH.
The command '/bin/sh -c tensorflow/tools/ci_build/builds/configured GPU     bazel build -c opt --config=cuda tensorflow/tools/pip_package:build_pip_package &&     bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/pip &&     pip install --upgrade /tmp/pip/tensorflow-*.whl &&     rm -rf /tmp/pip &&     rm -rf /root/.cache' returned a non-zero code: 1
```

**Comment by gunan** [comment]
@jart I think you were working on a fix for the above issue, right?
Or am I confusing this with another change?

**Comment by jart** [comment]
I commented on a CL internally regarding this. I'm not sure why that error message is being displayed in the docker environment. The "Can't find swig" error message was in our configure file and it was deleted by my SWIG change. Somehow that old code is lingering around, and failing, because we no longer apt-get swig in the Dockerfile.

**Comment by pwaller** [comment]
@jart: note that the dockerfile checks out the r0.11 branch, rather than running the repository at the revision you have checked out, so this could be some weird interaction there. When I do a docker build with `r0.11` as the repository-outside-of-docker, it's fine, but not with 446b1cb, even though inside docker it should be building exactly the same thing (r0.11).

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.devel-gpu#L86

**Comment by gunan** [comment]
Ah, that is the problem.
We have recently changed swig to be built by bazel rather than using it as a system dependency.
r0.11 needs it as a system dependency, but master branch does not download it anymore. That is the root cause of that error message.
Looks like @jart already found the problem and sent a cherrypick request to r0.11

**Comment by cancan101** [comment]
Can you link to that PR? I am still seeing this issue.
