### ISSUE TITLE
AttributeError: module 'tensorflow._api.v2.sets' has no attribute 'set_intersection'

### ISSUE THREAD

**Issue by SalahRahimi** [tensorflow/tensorflow#43982]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Hello there,
I must admit that I am quite new to this, so please excuse me if I raise a trivial problem.
I have installed tensorflow and tried to implement Mask R-CNN just to make sure that everything runs smoothly before I try it on my own images. The programme and all necessary modules appears run without a problem until it is confronted by an error. I have copied all the commands and the error below. I would be appreciated if you could help.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

import os
import sys
import random
import math
import numpy as np
import skimage.io
import matplotlib
import matplotlib.pyplot as plt

# Root directory of the project
ROOT_DIR = os.path.abspath("../")

import warnings
warnings.filterwarnings("ignore")

# Import Mask RCNN
sys.path.append(ROOT_DIR)  # To find local version of the library
from mrcnn import utils
import mrcnn.model as modellib
from mrcnn import visualize
# Import COCO config
sys.path.append(os.path.join(ROOT_DIR, "samples/coco/"))  # To find local version
import coco

%matplotlib inline

# Directory to save logs and trained model
MODEL_DIR = os.path.join(ROOT_DIR, "logs")

# Local path to trained weights file
COCO_MODEL_PATH = os.path.join('', "mask_rcnn_coco.h5")

# Download COCO trained weights from Releases if needed
if not os.path.exists(COCO_MODEL_PATH):
    utils.download_trained_weights(COCO_MODEL_PATH)

# Directory of images to run detection on
IMAGE_DIR = os.path.join(ROOT_DIR, "images")

class InferenceConfig(coco.CocoConfig):
    # Set batch size to 1 since we'll be running inference on
    # one image at a time. Batch size = GPU_COUNT * IMAGES_PER_GPU
    GPU_COUNT = 1
    IMAGES_PER_GPU = 1

config = InferenceConfig()
config.display()

# Create model object in inference mode.
model = modellib.MaskRCNN(mode="inference", model_dir='mask_rcnn_coco.hy', config=config)

# Load weights trained on MS-COCO
model.load_weights('mask_rcnn_coco.h5', by_name=True)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-a2b43923c698> in <module>
     48 
     49 # Create model object in inference mode.
---> 50 model = modellib.MaskRCNN(mode="inference", model_dir='mask_rcnn_coco.hy', config=config)
     51 
     52 # Load weights trained on MS-COCO

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mask_rcnn-2.1-py3.8.egg/mrcnn/model.py in __init__(self, mode, config, model_dir)
   1835         self.model_dir = model_dir
   1836         self.set_log_dir()
-> 1837         self.keras_model = self.build(mode=mode, config=config)
   1838 
   1839     def build(self, mode, config):

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mask_rcnn-2.1-py3.8.egg/mrcnn/model.py in build(self, mode, config)
   2041             # output is [batch, num_detections, (y1, x1, y2, x2, class_id, score)] in
   2042             # normalized coordinates
-> 2043             detections = DetectionLayer(config, name="mrcnn_detection")(
   2044                 [rpn_rois, mrcnn_class, mrcnn_bbox, input_image_meta])
   2045 

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/backend/tensorflow_backend.py in symbolic_fn_wrapper(*args, **kwargs)
     73         if _SYMBOLIC_SCOPE.value:
     74             with get_graph().as_default():
---> 75                 return func(*args, **kwargs)
     76         else:
     77             return func(*args, **kwargs)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keras/engine/base_layer.py in __call__(self, inputs, **kwargs)
    487             # Actually call the layer,
    488             # collecting output(s), mask(s), and shape(s).
--> 489             output = self.call(inputs, **kwargs)
    490             output_mask = self.compute_mask(inputs, previous_mask)
    491 

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mask_rcnn-2.1-py3.8.egg/mrcnn/model.py in call(self, inputs)
    808 
    809         # Run detection refinement graph on each item in the batch
--> 810         detections_batch = utils.batch_slice(
    811             [rois, mrcnn_class, mrcnn_bbox, window],
    812             lambda x, y, w, z: refine_detections_graph(x, y, w, z, self.config),

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mask_rcnn-2.1-py3.8.egg/mrcnn/utils.py in batch_slice(inputs, graph_fn, batch_size, names)
    818     for i in range(batch_size):
    819         inputs_slice = [x[i] for x in inputs]
--> 820         output_slice = graph_fn(*inputs_slice)
    821         if not isinstance(output_slice, (tuple, list)):
    822             output_slice = [output_slice]

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mask_rcnn-2.1-py3.8.egg/mrcnn/model.py in <lambda>(x, y, w, z)
    810         detections_batch = utils.batch_slice(
    811             [rois, mrcnn_class, mrcnn_bbox, window],
--> 812             lambda x, y, w, z: refine_detections_graph(x, y, w, z, self.config),
    813             self.config.IMAGES_PER_GPU)
    814 

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mask_rcnn-2.1-py3.8.egg/mrcnn/model.py in refine_detections_graph(rois, probs, deltas, window, config)
    718     if config.DETECTION_MIN_CONFIDENCE:
    719         conf_keep = tf.where(class_scores >= config.DETECTION_MIN_CONFIDENCE)[:, 0]
--> 720         keep = tf.sets.set_intersection(tf.expand_dims(keep, 0),
    721                                         tf.expand_dims(conf_keep, 0))
    722         keep = tf.sparse_tensor_to_dense(keep)[0]

AttributeError: module 'tensorflow._api.v2.sets' has no attribute 'set_intersection' 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@SalahRahimi 
Please refer to these to issues and let us know if it helps resolve:#30092 [link](https://stackoverflow.com/questions/60581677/attributeerror-module-tensorflow-core-api-v2-config-has-no-attribute-expe)

**Comment by SalahRahimi** [comment]
@Saduf2019 
thank you for your response. I couldn't find any solution in the links you have provided. Would you please mind to provide me with more details? just in case if I am missing something.

**Comment by amahendrakar** [comment]
@SalahRahimi,
In order to expedite the trouble-shooting process, could you please provide the following details

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by amahendrakar** [comment]
Also, on running the code snippet you have provided, I am facing an error stating `ModuleNotFoundError: No module named 'mrcnn'`.

Could you please provide the complete code to reproduce the issue reported here along with the dataset you are using? Thanks!

**Comment by SalahRahimi** [comment]
@amahendrakar 
The main issue here was the tensor flow version. mrcnn doesn't work with tensorflow.2.0, therefore I had to remove this version and re-install version 1.15. Note that it is not possible to install version 1.15 in Python3.8, so I switched to Python 3.7, which allowed me to install tensorflow 1.15. Now, this problem is resolved and I have been able to run the programme.

**Comment by amahendrakar** [comment]
@SalahRahimi,
Thank you for the update. Closing the issue as it is resolved, please feel free to re-open if necessary.

**Comment by dariemihai95** [comment]
In case anyone encounters this issue and has tensorflow 2.0 but doesn't want to change the versions of tensorflow and python, there is another easier solution:

You can either change from:
**tf.sets.set_intersection(...)**
to:
**tf.compat.v1.sets.set_intersection(...)**

and anywhere else necessary when receiving these kind of errors, or:

simply when importing tensorflow you can change:
**import tensorflow as tf**
to:
**import tensorflow.compat.v1 as tf**
