### ISSUE TITLE
remote devices in cluster not visible in TF 2

### ISSUE THREAD

**Issue by grananqvist** [tensorflow/tensorflow#43983]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Catalina 10.15.7
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3
- Python version: 3.6.12
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**
I am not able to simply put a tensor on a specific device in a TF cluster.

This example works for TF1.14:
```python
# try_worker_tensor_tf1.py
import json
import os
import time
import sys

import tensorflow as tf
from tensorflow.distribute.cluster_resolver import TFConfigClusterResolver

id_ = int(sys.argv[1])

os.environ['TF_CONFIG'] = json.dumps({
    'cluster': {
        'worker': ['localhost:8081', 'localhost:8082']
    },
    'task': {
        'type': 'worker',
        'index': id_
    }
})
resolver = TFConfigClusterResolver()
cluster = resolver.cluster_spec()

with tf.device("/job:worker/task:0"):
    v1 = tf.constant(1)

experimental_config = tf.ConfigProto.Experimental(
    share_cluster_devices_in_session=False,
    share_session_state_in_clusterspec_propagation=False)
config = tf.ConfigProto(experimental=experimental_config)
server = tf.train.Server(
    cluster, job_name="worker", task_index=id_, config=config)
sess = tf.Session(target=server.target, config=config)
print(sess.run(v1))
time.sleep(5)
```
```console
> python try_worker_tensor_tf1.py 0&
> python try_worker_tensor_tf1.py 1&
```
outputs
```console
1
1
```

But this example in TF2.3 does not work:
```python
import json
import os
import time
import sys

import tensorflow as tf

id_ = int(sys.argv[1])

os.environ['TF_CONFIG'] = json.dumps({
    'cluster': {
        'worker': ['localhost:8081', 'localhost:8082']
    },
    'task': {
        'type': 'worker',
        'index': id_
    }
})
# Initializes tf server internally.
dist = tf.distribute.experimental.MultiWorkerMirroredStrategy()

print('Devices', tf.config.list_logical_devices())

with tf.device("/job:worker/task:0"):
    v1 = tf.constant(1)

print(v1.numpy())
time.sleep(5)
```

```console
python try_worker_tensor_tf2.py 0
```
outputs:
```console
2020-10-13 16:56:49.658744: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> localhost:8081, 1 -> localhost:8082}
2020-10-13 16:56:49.658987: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:405] Started server with target: grpc://localhost:8081
Devices [LogicalDevice(name='/job:worker/replica:0/task:0/device:CPU:0', device_type='CPU'), LogicalDevice(name='/job:worker/replica:0/task:0/device:XLA_CPU:0', device_type='XLA_CPU')]
1
```
without blocking on the other server to start. In a separate terminal in parallel:
```console
python try_worker_tensor_tf2.py 1
```
outputs:
```console
2020-10-13 17:00:11.617132: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:405] Started server with target: grpc://localhost:8082
Devices [LogicalDevice(name='/job:worker/replica:0/task:1/device:CPU:0', device_type='CPU'), LogicalDevice(name='/job:worker/replica:0/task:1/device:XLA_CPU:0', device_type='XLA_CPU')]
Traceback (most recent call last):
  File "try_worker_tensor_tf2.py", line 25, in <module>
    v1 = tf.constant(1)
  File "/Users/fgranqvist/opt/anaconda3/envs/py36-tf2/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 264, in constant
    allow_broadcast=True)
  File "/Users/fgranqvist/opt/anaconda3/envs/py36-tf2/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 275, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "/Users/fgranqvist/opt/anaconda3/envs/py36-tf2/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 300, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/Users/fgranqvist/opt/anaconda3/envs/py36-tf2/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 98, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
tensorflow.python.framework.errors_impl.InvalidArgumentError: /job:worker/replica:0/task:0/device:CPU:0 unknown device.
```

**Describe the expected behavior**
I am expecting the TF2 example to also output `1` for both processes.

The reason why I am trying to do this is because I need to use `tf.queue.FIFOQueue` in the same way as `v1` above (as a distributed queue). One worker in the cluster enqueues items and all workers dequeues items and processes it.

**Comment by nikitamaia** [comment]
Hi @grananqvist the examples don't look exactly equivalent to me. I'm wondering if in TF1 were you also using `MultiWorkerMirroredStrategy`? Also, have you tried an if/else block like the example under the `task_id` attribute in the `TFConfigClusterResolver` [docs](https://www.tensorflow.org/api_docs/python/tf/distribute/cluster_resolver/TFConfigClusterResolver)?

```
if cluster_resolver.task_type == 'worker' and cluster_resolver.task_id == 0:
    # do something
```

**Comment by grananqvist** [comment]
I am using `MultiWorkerMirroredStrategy` in tf2 because the TF servers are initialized internally, and done so when initializing a distribution strategy (from here it seems https://github.com/tensorflow/tensorflow/blob/28a88cc4f7aef7ec2efe75b1ea2d0a7bdfae3a17/tensorflow/python/eager/context.py#L665 ). I can't initialize like in TF1 because there is no session.

> ```
> if cluster_resolver.task_type == 'worker' and cluster_resolver.task_id == 0:
>    # do something
> ```

This is a better example which works in TF1. As you can see, the problem is initializing a variable on one device, and reach it from all.

```python
# This example works in TF1. How to reproduce it to TF2?
import json
import os
import time
import sys

import numpy as np
import tensorflow as tf
from tensorflow.distribute.cluster_resolver import TFConfigClusterResolver

id_ = int(sys.argv[1])

os.environ['TF_CONFIG'] = json.dumps({
    'cluster': {
        'worker': ['localhost:8081', 'localhost:8082']
    },
    'task': {
        'type': 'worker',
        'index': id_
    }
})
resolver = TFConfigClusterResolver()
cluster = resolver.cluster_spec()

experimental_config = tf.ConfigProto.Experimental(
    share_cluster_devices_in_session=False,
    share_session_state_in_clusterspec_propagation=False)
config = tf.ConfigProto(experimental=experimental_config)
server = tf.train.Server(cluster,
                         job_name="worker",
                         task_index=id_, config=config)
sess = tf.Session(target=server.target, config=config)

with tf.device("/job:worker/task:0"):
    queue = tf.queue.FIFOQueue(10, dtypes=(tf.int32,), shared_name='my_queue')
if id_ == 0:
    sess.run(queue.enqueue_many(np.arange(10)))
    sess.run(queue.close())
    time.sleep(10)
else:
    while True:
        try:
            # Should print 1..10
            print(sess.run(queue.dequeue()))
        except tf.errors.OutOfRangeError:
            print('done')
            break
```

```
#terminal 1: puts 10 numbers in the queue
python try_fed_queue_tf1.py 0
#terminal 2: pulls 10 numbers from the queue
python try_fed_queue_tf1.py 1

**Comment by grananqvist** [comment]
If a distribution strategy is indeed required to initialize the server in the backend, and it is a feature that distribution strategies hide remote logical devices by default, how do I prevent this?

**Comment by nikitamaia** [comment]
Just to clarify, your use of `MultiWorkerMirroredStrategy` is not because you want to use the strategy to do synchronous training, but rather, you're using `MultiWorkerMirroredStrategy` to initialize the cluster of workers?

**Comment by grananqvist** [comment]
In this example yes. 
(In production we still use MultiWorkerMirroredStrategy to train with the cluster and tf.queue for other asynchronous pulling mechanisms in TF1.)

**Comment by nikitamaia** [comment]
Hi @grananqvist, sorry for the late response here. But did you try my suggestion in an earlier comment to use

```
if cluster_resolver.task_type == 'worker' and cluster_resolver.task_id == 0:
    # do something
```

Did that work for you?

**Comment by grananqvist** [comment]
> Hi @grananqvist, sorry for the late response here. But did you try my suggestion in an earlier comment to use
> 
> ```
> if cluster_resolver.task_type == 'worker' and cluster_resolver.task_id == 0:
>     # do something
> ```
> 
> Did that work for you?

I'm not sure how that is supposed to work. 

```python
if cluster_resolver.task_type == 'worker' and cluster_resolver.task_id == 0:
    v1 = tf.constant(1)

# On all workers, get value of v1 variable from worker 0. worker != 0 also needs a reference to this. Will not work.
print(v1.numpy())
```

If this is not  possible in TF2, i.e. reach a variable placed on another worker in the cluster, then how is `tf.queue.FIFOQueue` supposed to be used in TF2 with multiple workers?

**Comment by Fabien-Couthouis** [comment]
Hello, I want to do the same thing as @grananqvist, i.e.: put a variable on a device and read it from another device in tensorflow 2.4. Any clue on how to do this?
Thanks!

**Comment by crccw** [comment]
`tf.queue.FIFOQueue` doesn't work across workers with `MultiWorkerMirroredStrategy`. Note that it's not TF2 specific.  `MultiWorkerMirroredStrategy` is designed that each worker only sees its local devices. 

It is still possible to do what you describe in #1 with TF2. You can start a `tf.distribute.Server` on each worker, and connects to the cluster from a client by `tf.config.experimental_connect_to_cluster`. But you cannot use `MultiWorkerMirroredStrategy` together with it, and you need to handle distributed training on your own.

**Comment by grananqvist** [comment]
Ok, thanks for the clarification! Then I will assume everything is working as intended and will close this for now.
