### ISSUE TITLE
Passing structs by value makes C API hard to wrap

### ISSUE THREAD

**Issue by mxk** [tensorflow/tensorflow#43992]
The API has a number of functions that pass `TF_Output` argument by value. For example:

```c
TF_CAPI_EXPORT extern int TF_GraphGetTensorNumDims(TF_Graph* graph, TF_Output output, TF_Status* status);
```

This creates problems with different calling conventions. In my case, I'm trying to call these functions from Go through the syscall API instead of cgo and have no idea how to pass the struct correctly. I realize that existing functions cannot be changed, but would suggest deprecating them and adding new ones that only use struct pointers.

**Comment by saxenasaurabh** [comment]
Thanks for the suggestion. As you mentioned, it is not possible to change these APIs now but we are working on new APIs for building `tf.function` in TF2 which will have pointers for tensors.
