### ISSUE TITLE
How to print the tensor values in tensorflow 2.x version?

### ISSUE THREAD

**Issue by laurence-lin** [tensorflow/tensorflow#43993]
I have a small issue, in tensorflow 2.x version, we don't need session to run the graph.

Currently I have a tensor object, calculated by tf.image.ssim(), but I have no way to print the value in the tensor. 

Most of the tutorials I found is about keras models, but what is the way to print tensor values in simple tensor?

**Comment by PrattJena** [comment]
Refer to the documentation of tf.print [here](https://www.tensorflow.org/api_docs/python/tf/print)

**Comment by laurence-lin** [comment]
> Refer to the documentation of tf.print [here](https://www.tensorflow.org/api_docs/python/tf/print)

Thanks, it helps. However, do you know how to convert tensor to array in tensorflow 2.x version?

**Comment by PrattJena** [comment]
You can use .numpy() method of tensorflow to convert into a numpy array . [Here](https://stackoverflow.com/questions/34097281/how-can-i-convert-a-tensor-into-a-numpy-array-in-tensorflow) is stackoverlfow link to your question

**Comment by laurence-lin** [comment]
> You can use .numpy() method of tensorflow to convert into a numpy array . [Here](https://stackoverflow.com/questions/34097281/how-can-i-convert-a-tensor-into-a-numpy-array-in-tensorflow) is stackoverlfow link to your question

Thank you! I'd tried this function before, but encounter some error. Now it's solved!
