### ISSUE TITLE
Why is loading resnet50 keras model in TF 1.15 on TPU does not work?

### ISSUE THREAD

**Issue by usama-ahmedkhan** [tensorflow/tensorflow#43999]
### System information

-   **Have I written custom code ( No , I am using tf.keras.application.resnet50 ):
-   **OS Platform and Distribution (e.g., Linux Ubuntu 20.04)**:
-   **TensorFlow version (1.15)**:
-   **Python version**: (3.7)
-   **TPU *: V2 using TPU estimator API

###
         I am trying to initialize resnet50 as backbone for a model in TF 1.15, and the model is run on google TPU V2. My code is this:

### Source code 

import tensorflow.keras as keras
from MBCONV import MBConvBlock
import yaml
import tensorflow.keras.backend as K
import tensorflow as tf

print(tf.__version__)
tf.compat.v1.enable_eager_execution()

def model():

    
    mode=resnet_backbone() // error is in this fuction 

    // adding some more layers etc 

    return tf.contrib.tpu.TPUEstimatorSpec(mode, loss=loss, train_op=train_op, host_call=host_call,
                                           predictions={"emb": embeddings_layer})
    

def resent_backbone():
 
    backbone_model=tf.keras.applications.ResNet50(include_top=False, weights='imagenet',pooling=None)
    return backbone_model

def main(unused_argv):

    tpu_cluster_resolver = tf.contrib.cluster_resolver.TPUClusterResolver(FLAGS.tpu)

    run_config = tf.contrib.tpu.RunConfig(
        model_dir=FLAGS.model_dir,
        cluster=tpu_cluster_resolver,
        session_config=tf.ConfigProto(
            allow_soft_placement=True, log_device_placement=True),
        tpu_config=tf.contrib.tpu.TPUConfig(FLAGS.iterations),
    )

    classifier = tf.contrib.tpu.TPUEstimator(
        model_fn=model,
        use_tpu=FLAGS.use_tpu,
        train_batch_size=FLAGS.batch_size,
        eval_batch_size=FLAGS.batch_size,
        predict_batch_size=FLAGS.batch_size,
        config=run_config,
        params={

            "use_tpu": FLAGS.use_tpu,
        })

    classifier.train(
        input_fn=lambda params: train_input_fn(params["batch_size"]),
        # input_fn=lambda params: train_input_fn(params["batch_size"]),
        max_steps=FLAGS.train_steps)

def build_prediction_network():
    tpu_cluster_resolver = tf.contrib.cluster_resolver.TPUClusterResolver(
        FLAGS.tpu)

    run_config = tf.contrib.tpu.RunConfig(
        model_dir=FLAGS.model_dir,
        cluster=tpu_cluster_resolver,
        session_config=tf.ConfigProto(
            allow_soft_placement=True, log_device_placement=True),
        tpu_config=tf.contrib.tpu.TPUConfig(FLAGS.iterations),
    )
    classifier = tf.contrib.tpu.TPUEstimator(
        model_fn=model,
        use_tpu=FLAGS.use_tpu,
        train_batch_size=FLAGS.batch_size,
        eval_batch_size=FLAGS.batch_size,
        predict_batch_size=FLAGS.batch_size,
        config=run_config,
        params={

            "use_tpu": FLAGS.use_tpu, })
    return classifier

### I get the following errors

Operation of type Placeholder (input_1) is not supported on the TPU. Execution will fail if this op is used in the graph. 

tensorflow.python.framework.errors_impl.InaccessibleTensorError: Operation 'VarIsInitializedOp' has been marked as not fetchable. Typically this happens when it is defined in another function or code block. Use return values,explicit Python locals or TensorFlow collections to access it.

**Comment by Saduf2019** [comment]
@usama-ahmedkhan 
Please provide with complete stand alone indented code to replicate the issue faced or if possible share a colab gist with the error reported.
Please note there is no official support for 1.x tf, could you try on 2.x and let us know if you face any issues.

**Comment by usama-ahmedkhan** [comment]
yes , I have edited , not possible to work in tf 2.x right now , because of most code is written in the tf 1.x. If i put @tf.function on top of def resent_backbone: , then this error goes away and following error comes:


 ValueError: Cannot use 'conv1_conv/kernel/Initializer/random_uniform' as input to 'conv1_conv/kernel/Assign' because 'conv1_conv/kernel/Initializer/random_uniform' is in a while loop. See info log for more details.

**Comment by Saduf2019** [comment]
@usama-ahmedkhan
Please provide with complete stand alone indented code to replicate the issue faced or if possible share a colab gist with the error reported.

**Comment by usama-ahmedkhan** [comment]
I updated it , can you give a guess to what could be the issue , it's just a simple 1 line of code initialization with no input to it .

From what I have searched , following is the closest guess to the error I am getting , it is not possible to fetch the result of an op created inside the while loop's body, because the body might execute 0 or more times, based on the loop condition. To get a value out of the loop, you need to return it from the body function (as one of the loop variables), and its final value after all the iterations will be returned from tf.while_loop(). But this happens inside tf code , not externally , because i am only running a single line code for initialization of a model.

**Comment by allenwang28** [comment]
In TF 1.x, there are subtle differences between the graph representation of models implemented in Keras (e.g. tf.keras.applications...)  and models implemented in standard TensorFlow.

If you must stick with TF 1, I would highly suggest starting from the [reference ResNet model](https://github.com/tensorflow/tpu/blob/master/models/official/resnet/resnet_main.py) that works well on TPUs, but I would highly suggest moving to TF 2.x + Keras which is a lot easier to use. [Here](https://github.com/tensorflow/models/tree/master/official/vision/image_classification) is an equivalent reference ResNet model that works well on CPU, GPU and TPUs.

**Comment by usama-ahmedkhan** [comment]
thanks for your reply , and yes I am now using reference ResNet model you suggested , it is easy  and flexible to use that resnet model.

**Comment by Saduf2019** [comment]
@usama-ahmedkhan 
Please move the issue to closed status if resolved.
