### ISSUE TITLE
Will TensorFlow run on an AMD FX processor?

### ISSUE THREAD

**Issue by roschler** [tensorflow/tensorflow#440]
I'm looking at buying a new PC to run TensorFlow on.  The system I'm looking at has an AMD FX processor and a GTX 960 with 2GB of memory.  Will TensorFlow run fine on that processor and be able to take advantage of the GTX 960 for CUDA processing?  The O/S I'm planning on is Ubuntu Linux.

**Comment by vrv** [comment]
It's an x86 processor so it should be fine on CPU, and I believe we support the GTX960 (It's a Maxwell GPU with cuda compute capability 5).

**Comment by gujunli** [comment]
I don't think AMD FX CPU is a problem. But GTX 960 with 2 GB might be an
issue.
Thanks.

Junli

On Mon, Dec 7, 2015 at 9:03 PM, roschler <notifications@github.com> wrote:

> I'm looking at buying a new PC to run TensorFlow on. The system I'm
> looking at has an AMD FX processor and a GTX 960 with 2GB of memory. Will
> TensorFlow run fine on that processor and be able to take advantage of the
> GTX 960 for CUDA processing? The O/S I'm planning on is Ubuntu Linux.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tensorflow/tensorflow/issues/440>.
>



-- 
************************************************
Junli Gu--谷俊丽
Coordinated Science Lab
University of Illinois at Urbana-Champaign
************************************************

**Comment by vrv** [comment]
Yeah, it would be supported by TensorFlow, but is definitely on the low-side compared to most compute GPUs.

**Comment by roschler** [comment]
Thanks everyone.  Would it be enough of an improvement to get a GTX 960 with 4GB, or is anything less than something like a GTX TitanX going to be underpowered?

**Comment by LeavesBreathe** [comment]
@roschler , I would get at least a 980TI, but if I had to do it all over again, I would definitely get the titanx

**Comment by roschler** [comment]
@LeavesBreathe - Ok, that's what I'll do.  Thanks.

**Comment by arisliang** [comment]
Does GTX 960 work on pip installation or must it be installed from sources? I have a GTX 960 build, but doesn't seem to get recognized by tensorflow.
