### ISSUE TITLE
How to serve a model containing ```tensorflow.keras.layers.experimental.preprocessing``` layers ?

### ISSUE THREAD

**Issue by DachuanZhao** [tensorflow/tensorflow#44002]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
[https://www.tensorflow.org/tutorials/structured_data/preprocessing_layers](https://www.tensorflow.org/tutorials/structured_data/preprocessing_layers)

### Clear description

How to serve the model in that document by tf_serving ? Is there any example ?  I have read the document [https://www.tensorflow.org/guide/keras/preprocessing_layers#benefits_of_doing_preprocessing_inside_the_model_at_inference_time](https://www.tensorflow.org/guide/keras/preprocessing_layers#benefits_of_doing_preprocessing_inside_the_model_at_inference_time) , but it doesn't give an example , either .

**Comment by bhack** [comment]
Check https://github.com/tensorflow/tensorflow/issues/31055

**Comment by DachuanZhao** [comment]
> Check #31055

@bhack  Hi , I have read it , but I have no idea about how to solve my problem bacause there are many input layers in my model but the #31055 only has one input layer .

**Comment by Saduf2019** [comment]
@DachuanZhao 
Refer to [these docs](https://tensorflow.google.cn/api_docs/python/tf/keras/layers/experimental/preprocessing/CategoryEncoding) and [this link](https://keras.io/guides/transfer_learning/) let us know.

**Comment by DachuanZhao** [comment]
I have solved it and I will give an example here :
```Python
x_input_list_dict = {"Age":[1,2,3]}
channel = grpc.insecure_channel("url")
stub = prediction_service_pb2_grpc.PredictionServiceStub(channel)

grpc_request = predict_pb2.PredictRequest()
grpc_request.model_spec.name = "model_name"
grpc_request.model_spec.signature_name = ""

for key,v_list in x_input_list_dict.items():
    grpc_request.inputs[key].CopyFrom(
        tf.make_tensor_proto(
            tf.convert_to_tensor([[v] for v in v_list]),
        )
    )

# Call the TFServing Predict API
predict_response = stub.Predict(grpc_request)

probability_list = predict_response.outputs['dense_14'].float_val[:]

```
