### ISSUE TITLE
tf.keras.utils.Generator doesn't get called after first batch.

### ISSUE THREAD

**Issue by kareemamrr** [tensorflow/tensorflow#44006]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution : Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.8.5
- CUDA/cuDNN version: 10.1 / 7.6.5
- GPU model and memory: GTX 1060 (6gb)

**Describe the current behavior**
I've created a generator class which inherits from `tf.keras.utils.Sequence` that reads from directory and returns a tuple of `X, y`. I use it with a custom model and pass it to the fit method. After using logging to debug, I found out that it returns the very first batch, passes it to the model and trains, but after that it doesn't get called again, I have a logging statement in its `__getitem__` method which should get called each batch but only gets called in the first one, and so the model then gets an array of shape `(None, None, None)`.

**Describe the expected behavior**
The `__getitem__` should get called after each epoch.

**Standalone code to reproduce the issue**
Colab: https://colab.research.google.com/drive/14Pz5z65Cb5V8J_IsOJQ1Kk7SCU-ubwfy#scrollTo=iZm4LeXuUfja

**Other info / logs**
This is the logfile I used
```
2020-10-14 10:42:01,329:train.DataGenerator:Preparing batch #0
2020-10-14 10:42:04,687:train.CustomLSTM:Epoch #1
2020-10-14 10:42:04,688:train.CustomLSTM:Xe shape: (32, 1, 160, 40)
2020-10-14 10:42:05,851:train.CustomLSTM:Epoch #2
2020-10-14 10:42:06,333:train.CustomLSTM:Xe shape: (None, None, None, None)
```
As you can see the generator the first batch before logging the first epoch and passes it to the model, and then doesn't return the second batch and the model doesn't find anything to train on.

**Comment by bhack** [comment]
Please unlock the access to your colab.

**Comment by kareemamrr** [comment]
@bhack I did so.

**Comment by bhack** [comment]
I think they you can minimize the code sample and use dummy data inputs if It Is not totally mandatory to use files to reproduce your issue.
As we are trying to cover as many ISSUES as possible here please help us minimizing the code that reproduce your issue with the very minimal code lines set that are required.

**Comment by kareemamrr** [comment]
@bhack Okay I just did.

**Comment by bhack** [comment]
Ok but now It fails with a different error

**Comment by kareemamrr** [comment]
Is the error  `TypeError: Failed to convert object of type <class 'tuple'> to Tensor. Contents: (None, None, None). Consider casting elements to a supported type.`? That's the error that I get yes, because it doesn't get the second batch from the generator it recieves `Xe` and `Xs` as all `None`.

**Comment by kareemamrr** [comment]
@bhack 
2020-10-14 14:36:00,730:train.DataGenerator:Preparing batch #0
2020-10-14 14:36:05,436:train.CustomLSTM:Epoch #1
2020-10-14 14:36:05,440:train.CustomLSTM:Xe shape: (32, 1, 160, 40)
2020-10-14 14:36:05,442:train.CustomLSTM:Xs shape: (32, 3, 160, 40)
2020-10-14 14:36:06,700:train.CustomLSTM:Epoch #2
2020-10-14 14:36:07,193:train.CustomLSTM:Xe shape: (None, None, None, None)
2020-10-14 14:36:07,197:train.CustomLSTM:Xs shape: (None, None, None, None)

**Comment by bhack** [comment]
I think that if you want to use with that modality you could try with 
`model.compile(optimizer="rmsprop", loss="binary_crossentropy", metrics=["accuracy"],run_eagerly=True)`

**Comment by kareemamrr** [comment]
@bhack I tried it and it worked, thank you. I have two questions though:
1. What "modality" are you referring to? What could I have done differently that I wouldn't need that flag? Isn't eager execution on by defaulty in TF2+?
2. In my logs, the `index` (of the batch) that gets passed to the `__getitem__` method is an arbitrary number i.e: 0, 31, 32, 51, etc. Isn't supposed to be normally incremented i.e: 0, 1, 2, 3, etc?

**Comment by amahendrakar** [comment]
@kareemamrr,
Is this still an issue? Please feel free to close the issue if resolved. Thanks!
