### ISSUE TITLE
Output of Regression Quantized Aware Training Model is always restricted between 0 and 6

### ISSUE THREAD

**Issue by dtlam26** [tensorflow/tensorflow#44007]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 1.15

I have successfully QAT a regression model for company purposes. However, when I run it on edge_tpu model, the output inference is limited between 0 and 6. This is ridiculous when my output should be in a bigger range: From the label data, the output is from (0-95) and (0-2pi).

![min-max limit between 0-6](https://user-images.githubusercontent.com/27914179/95973523-bd3c0f80-0e4e-11eb-9fc7-a8e2a2b0a761.png)

I have also tried normalize the output to prevent the outcome exceed 0-255 for unit8 model. However, it still be the same range (0-6) no matter what

I have also tried with a different structure but always get the same result. Because this is private code so I cant share out, but I attached some frozen file for people viewing.

Any recommendation? 

In addition, this problem does not happen if I post quantize my model with a representative dataset.

```
https://drive.google.com/drive/folders/14L4Yrsk_9rB6UOgJn8La7n1epanAFI0B?usp=sharing
```

**Comment by ravikyram** [comment]
@dtlam26 

Can you please share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by dtlam26** [comment]
> @dtlam26
> 
> Can you please share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

I have uploaded the train code and export frozen graph to the attached drive above

**Comment by dtlam26** [comment]
I have figured out the problem. It is the problem when that part of the model is not really trained QAT. This happens for the output node that somehow forgets to QAT when training. To overcome the problem, we should provide some op to trigger the QAT for the output nodes. In my regression case, I add a dummy op: tf.maximum(output,0) in the model to make the node QAT. If your output is strictly between 0-1, applying "sigmoid" activation at output instead of relu can also solve the problems.

![image](https://user-images.githubusercontent.com/27914179/96995343-03892100-1569-11eb-9180-679aabfcbd60.png)
