### ISSUE TITLE
segmentation fault using detection postprocess for ssd_mobilenet_v3     

### ISSUE THREAD

**Issue by skingle** [tensorflow/tensorflow#44003]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18
- TensorFlow installed from (source or binary): binary
- Tensorflow version (commit SHA if source):  tf 1.15
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Arm Mbed OS

**Describe the problem**
I have to run the object detection model on Mbed OS. Currently while testing directly on Linux, we ran into a custom op unsupported issue. following is the error:  

     ` Failed to get registration from op code CUSTOM`

So, we tried to use [detection_postprocess](https://github.com/mansnils/tensorflow/tree/detection_postprocess). we ran into a segmentation fault.

`Error Stack :: SIGSEGV,
#0  0x000000000807a31c in tflite::ops::micro::custom::detection_postprocess::ComputeIntersectionOverUnion(float const*, int, int) ()
#1  0x000000000807a6a6 in tflite::ops::micro::custom::detection_postprocess::NonMaxSuppressionSingleClassHelper(TfLiteContext*, TfLiteNode*, tflite::ops::micro::custom::detection_postprocess::OpData*, float const*, int*, int*, int) ()
#2  0x000000000807b062 in tflite::ops::micro::custom::detection_postprocess::NonMaxSuppressionMultiClassFastHelper(TfLiteContext*, TfLiteNode*, tflite::ops::micro::custom::detection_postprocess::OpData*, float const*) ()
#3  0x000000000800f4e6 in tflite::MicroInterpreter::Invoke() ()
#4  0x0000000008007da1 in main ()`

When can we expect  [detection_postprocess](https://github.com/mansnils/tensorflow/tree/detection_postprocess) to be merged?.
 

**Steps to reproduce the issue**

1.Transfer Learning 
Trained the model with a custom dataset using the following weights-
[ssd_mobilenet_v3](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v3_small_coco_2020_01_14.tar.gz)

2.Freeze graph::

python /content/models/research/object_detection/export_tflite_ssd_graph.py \
--pipeline_config_path 'exported-model/ssd_mobilenet_v3_small_coco_2020_01_14/output_inference_graph_v1.pb/pipeline.config' \
--trained_checkpoint_prefix 'exported-model/ssd_mobilenet_v3_small_coco_2020_01_14/output_inference_graph_v1.pb/model.ckpt'  \
--output_directory 'exported-model/ssd_mobilenet_v3_small_coco_2020_01_14/tflite' 

3.Conversion to tflite ::

```
input_arrays = ["normalized_input_image_tensor"]
output_arrays = ['TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3']
input_shapes = {'normalized_input_image_tensor': [1, 320, 320, 3]}

image_list = glob.glob('/content/drive/My Drive/Colab Notebooks/colddrink/tf1/ssd_mobilenet_v3/images/train/*.bmp')
def representative_dataset_gen():
    for i in image_list:
        img = cv2.imread(i)
        img = img.astype(np.float32)
        img = cv2.resize( img,(320,320), interpolation = cv2.INTER_NEAREST)
        img = img
        img = img.reshape(1,320,320,3)
        # Get sample input data as a numpy array in a method of your choosing.
        yield [img]


graph_def_file = PATH_TO_CKPT
converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays, input_shapes)
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
converter.representative_dataset = representative_dataset_gen
converter.allow_custom_ops = True
converter.experimental_new_converter = True
tflite_model = converter.convert()
open("exported-model/ssd_mobilenet_v3_small_coco_2020_01_14/tflite/ssd_mobilenet_v3_small_int8.tflite", "wb").write(tflite_model)

```

4. Converting the model and image to cc and header files

```
xxd -i ssd.tflite object_detection.cc
xxd -s 54 -i img.bmp > img.h
```

5.  Test
[image_recognition_test.txt](https://github.com/tensorflow/tensorflow/files/5376363/image_recognition_test.txt)
[original](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/image_recognition_experimental/image_recognition_test.cc)

command
`make -f tensorflow/lite/micro/tools/make/Makefile image_recognition_test`

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
