### ISSUE TITLE
ImportError: cannot import name 'MomentumParameters'

### ISSUE THREAD

**Issue by maheshksingh** [tensorflow/tensorflow#44010]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Its on COLAB

**Describe the problem**
I find your beautiful code and run the very second line of code and was thrilled to get the error and wasted my one full day to figure out the issue

Line of Code - [from tflite_model_maker import configs]
Error  - ImportError: cannot import name 'MomentumParameters'

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I just ran your code from this - https://www.tensorflow.org/lite/tutorials/model_maker_text_classification, and it fails at second line of code

**Any other info / logs**
Following imports fail as well
from tflite_model_maker import ExportFormat
from tflite_model_maker import model_spec
from tflite_model_maker import text_classifier
from tflite_model_maker import TextClassifierDataLoader

Thanks So much
Happy Coding

**Comment by thhart** [comment]
Same with: https://www.tensorflow.org/lite/tutorials/model_maker_image_classification
Opened in Colab but fails:

`
!pip install tflite-model-maker
[...]
`

```
import numpy as np

import tensorflow as tf
assert tf.__version__.startswith('2')

from tflite_model_maker import configs
from tflite_model_maker import ExportFormat
from tflite_model_maker import image_classifier
from tflite_model_maker import ImageClassifierDataLoader
from tflite_model_maker import model_spec

import matplotlib.pyplot as plt
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-09786bbd7d5a> in <module>()
      4 assert tf.__version__.startswith('2')
      5 
----> 6 from tflite_model_maker import configs
      7 from tflite_model_maker import ExportFormat
      8 from tflite_model_maker import image_classifier

15 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/_tpu_estimator_embedding.py in <module>()
     33 from tensorflow.python.tpu.tpu_embedding import AdamParameters
     34 from tensorflow.python.tpu.tpu_embedding import FtrlParameters
---> 35 from tensorflow.python.tpu.tpu_embedding import MomentumParameters
     36 from tensorflow.python.tpu.tpu_embedding import RMSPropParameters
     37 from tensorflow.python.tpu.tpu_embedding import StochasticGradientDescentParameters

ImportError: cannot import name 'MomentumParameters'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by maheshksingh** [comment]
I am from VOLVO, and I have a live project where I need a tflite model for Android device, and I am stuck with this issue, I really repent on this on why I chose TF.

**Comment by realgt** [comment]
also having a bug, even tried tflite-model-maker-nightly to no avail
Hope someone can chime in with a workaround/fix

**Comment by matthias-vogt** [comment]
This seems to be connected to https://github.com/tensorflow/estimator/commit/1d460d1009dd2de36803f887a21384fe0d54d7c6
As a workaround, try using an estimator nightly version from before the commit instead:

```
pip uninstall tf-estimator-nightly tensorflow-estimator && pip install tf-estimator-nightly==2.4.0.dev2020101001
```

**Comment by ziyeqinghan** [comment]
We have fixed this.  Could you please try it again?

**Comment by harsh204016** [comment]
**I am running a text sentiment classifier** 
`logdir = os.path.join("/tmp/logs",datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))
tensorboard_callback = tf.keras.callbacks.TensorBoard(logdir,histogram_freq=1)
checkpointer = tf.keras.callbacks.ModelCheckpoint(filepath='/tmp/sentiment_analysis.hdf5',verbose=1,save_best_only=True)
earlystopping = tf.keras.callbacks.EarlyStopping('val_loss',patience=2)

model.compile(optimizer='adam',
              loss = tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

history = model.fit(train_data , epochs=5 , validation_data=test_data,callbacks=[tensorboard_callback,checkpointer,earlystopping])
%reload_ext tensorboard
%tensorboard --logdir /tmp/logs


**I got error after this** 

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
2020-10-24 04:53:36.358387: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 5, in <module>
    from tensorboard.main import run_main
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/main.py", line 43, in <module>
    from tensorboard import default
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/default.py", line 40, in <module>
    from tensorboard.plugins.beholder import beholder_plugin_loader
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/plugins/beholder/__init__.py", line 22, in <module>
    from tensorboard.plugins.beholder.beholder import Beholder
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/plugins/beholder/beholder.py", line 225, in <module>
    class BeholderHook(tf.estimator.SessionRunHook):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 13, in <module>
    from tensorflow_estimator._api.v1.estimator import tpu
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/_api/v1/estimator/tpu/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1.estimator.tpu import experimental
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/_api/v1/estimator/tpu/experimental/__init__.py", line 10, in <module>
    from tensorflow_estimator.python.estimator.tpu._tpu_estimator_embedding import EmbeddingConfigSpec
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/tpu/_tpu_estimator_embedding.py", line 35, in <module>
    from tensorflow.python.tpu.tpu_embedding import MomentumParameters
ImportError: cannot import name 'MomentumParameters'`

**Comment by bharathwajan** [comment]
> This seems to be connected to [tensorflow/estimator@1d460d1](https://github.com/tensorflow/estimator/commit/1d460d1009dd2de36803f887a21384fe0d54d7c6) As a workaround, try using an estimator nightly version from before the commit instead:
> 
> ```
> pip uninstall tf-estimator-nightly tensorflow-estimator && pip install tf-estimator-nightly==2.4.0.dev2020101001
> ```

thanks for this , it works : )
