### ISSUE TITLE
Unable to build TensorFlow targeting Raspberry Pi

### ISSUE THREAD

**Issue by TylerADavis** [tensorflow/tensorflow#44028]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.15.7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version: v2.3.0
- Python version: N/A
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
I am following the instructions on https://www.tensorflow.org/install/source_rpi to build a `.whl` package that I can install on a Raspberry Pi 3B, but the build process is failing. I can clone TensorFlow, check out a revision, and begin the build in the Docker container without issue, but the build fails with the following output at the end:

```
Removing intermediate container 8f1ac04cb8a3
 ---> 9c723ba9afae
Step 14/14 : COPY install/.bazelrc /etc/bazel.bazelrc
 ---> 8dba22ce896f
Successfully built 8dba22ce896f
Successfully tagged tf_ci.pi-python37:latest
Running 'tensorflow/tools/ci_build/pi/build_raspberry_pi.sh' inside tf_ci.pi-python37...
Reading package lists...
Building dependency tree...
Reading state information...
sudo is already the newest version (1.8.16-0ubuntu1.9).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
addgroup: Please enter a username matching the regular expression configured
via the NAME_REGEX[_SYSTEM] configuration variable.  Use the `--force-badname'
option to relax this check or reconfigure NAME_REGEX.
```

If I instead try to build `v2.3.1`, I get the following output:
```
Step 15/15 : ENV TF_ENABLE_XLA=0
 ---> Using cache
 ---> e7647e308801
Successfully built e7647e308801
Successfully tagged tf_ci.pi-python37:latest
Running 'tensorflow/tools/ci_build/pi/build_raspberry_pi.sh' inside tf_ci.pi-python37...
Reading package lists...
Building dependency tree...
Reading state information...
sudo is already the newest version (1.8.16-0ubuntu1.9).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
addgroup: To avoid problems, the username should consist only of
letters, digits, underscores, periods, at signs and dashes, and not start with
a dash (as defined by IEEE Std 1003.1-2001). For compatibility with Samba
machine accounts $ is also supported at the end of the username
```

This happens well before the 30 minutes the documentation suggests the process should take, and there is no `.whl` in the `tensorflow/output-artifacts` directory.

I am experiencing this issue when trying to compile v2.3.0, but I have encountered when trying to build v1.15.0 as well. I would expect the use of containers and Bazel to make the build reproducible, but it would seem that something has changed that broke the build process. Please let me know if there are any additional logs I could provide to help diagnose this.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

> Note: you must have docker installed for the following steps

```shell
$ git clone https://github.com/tensorflow/tensorflow.git
$ cd tensorflow
$ git checkout v2.3.0
$ tensorflow/tools/ci_build/ci_build.sh PI-PYTHON37 \
    tensorflow/tools/ci_build/pi/build_raspberry_pi.sh
```

At this point the build will fail, with no output `.whl` generated.

**Comment by TylerADavis** [comment]
This seems to be related to the [`with_the_same_user` script](https://github.com/tensorflow/tensorflow/blob/9d558ddba177859ebd7e4018a405f68dcc5e1836/tensorflow/tools/ci_build/builds/with_the_same_user) and the environment variable [`CI_BUILD_USER_FORCE_BADNAME`](https://github.com/tensorflow/tensorflow/blob/054738d5340879f638c0261fe998d864d0e20a48/tensorflow/tools/ci_build/ci_build.sh#L155), but these don't appear to be well documented, and it's not clear to an end user that a workaround might exist.

**Comment by mohantym** [comment]
Hi @TylerADavis ! Could you try with instructions in this [repo](https://github.com/PINTO0309/Tensorflow-bin)? Thanks!

**Comment by TylerADavis** [comment]
I don't have an rpi to test on at the moment, but it does look like that repo would allow for one to get a prebuilt wheel of full (non-lite) tensorflow for an aarch64 linux system.

https://github.com/PINTO0309/Tensorflow-bin#usage

**Comment by mohantym** [comment]
Ok @TylerADavis ! Is this issue good to close then?

**Comment by TylerADavis** [comment]
Sounds good to me. Thank you for referring me to that repo @mohantym !
