### ISSUE TITLE
Problem to import keras from tensorflow 2.3.1

### ISSUE THREAD

**Issue by JDE65** [tensorflow/tensorflow#44020]
I succesfully upgraded my python files to tensorflow 2. with tf_upgrade_2.0
**System information**
- I have written custom code 
- OS Platform : windows 10
- TensorFlow : 2.3.1
- TensorFlow-gpu 2.3.1
- Keras version : 2.3.1
- Python version: 3.7.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0.130 / 7.6.5
- GPU model and memory: NVIDIA 1060 6GB

When I start importing various libriaries, the python file bugs rapidly. I used to run the following imports :
```
import os
import warnings
import numpy as np
import numpy_financial as npf
import pandas as pd
import sqlite3 as sq
import time
from itertools import chain
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import Dropout, Activation, Dense, LSTM, Flatten
from tensorflow.keras.layers import Concatenate
from tensorflow.keras.layers import CuDNNLSTM, CuDNNGRU
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import confusion_matrix

from util_data import *
from util_prepa import *
from util_model import *
from util_invest import *
from util_RESNET import *
```

I automaticaly get an error message  : 
`ModuleNotFoundError: No module named 'tensorflow.python.keras.activations'`
preceeded with 
```
File "D:\GD Navagne\AI\tf2\ResNet1D3D_list.py", line 27, in <module>
    from tensorflow import keras

  File "D:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\keras\__init__.py", line 14, in <module>
    from . import activations

  File "D:\Anaconda3\envs\tf2\lib\site-packages\tensorflow\keras\activations\__init__.py", line 10, in <module>
    from tensorflow.python.keras.activations import deserialize
```
I don't know what to do... Thanks in advance for the help.

**Comment by PrattJena** [comment]
Please check to see if u have latest tensorflow version running by writing` tf.__version__`. Also there was a small error in code and I corrected it and ran the following code and found no errors. You can find the google colab gist [here](https://colab.research.google.com/drive/1g4cDJzvdHFbQGOF07NpfuDW0h8jO3qd0?usp=sharing).

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3 and i am not seeing any issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/18da0d26cc065f374bf073c6470c2dfc/untitled466.ipynb).Thanks!
