### ISSUE TITLE
How to pass mutable tensors to a Custom Op in Python?

### ISSUE THREAD

**Issue by golden0080** [tensorflow/tensorflow#44037]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes, I've written custom ops and import it on Python side.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1
- Python version: 3.5

**Describe the current behavior**
I'm trying custom op with mutable inputs. Therefore I got my own custom op with:
```
REGISTER_OP("MyCustomOp").Input("input1: Ref(float)") ....
```

I was able to call this custom ops from my Python keras layer:
```
class MyKerasLayer(Layer):
...
 def build(self, input_shape):
    ...
    self.moving_mean = self.add_weight(shape=(5,), trainable=False, name="moving_mean")

 def call(self, inputs):
    return self.custom_op.MyCustomOp(input1=self.moving_mean, ...)
```

However, when running the custom layer in graph mode, I got errors like:
```
TypeError: 'MyCustomOp' Op requires that input 'input1' be a mutable tensor (e.g.: a tf.Variable)
```

**I'm trying to find a way you could feed a layer's weights into custom ops, in a way these inputs are mutable.**

**Describe the expected behavior**

By passing `self.moving_mean` to my `MyCustomOp`, the Op accept it as a valid mutable tensor.

**Comment by Saduf2019** [comment]
@golden0080 
Please share complete stand alone indented code or is possible share a colab gist with the error reported.

**Comment by golden0080** [comment]
I was able to work around this error, with the `getter` parameter to `Layer.add_weight`.
I basically copied `base_layer_utils.make_variable` to create a RefVariable instead.

**Comment by golden0080** [comment]
But I think to make this not an issue for anyone else, probably we should update TF doc to showcase how to use that `getter` parameter?

**Comment by jvishnuvardhan** [comment]
@golden0080 Are you interested in updating the docs by raising a PR? Thanks!

**Comment by golden0080** [comment]
@jvishnuvardhan Yes, I think I could contribute to an updated doc.
Could you direct me to what I need to do for doc updates?

**Comment by Frank1993** [comment]
> But I think to make this not an issue for anyone else, probably we should update TF doc to showcase how to use that `getter` parameter?

Hi golden0080, I also encountered this problem, may I know how you solved it? Thanks

**Comment by golden0080** [comment]
@Frank1993 Check out the code at: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/base_layer.py#L615
It basically means `getter` could be the variable builder, which the default one is only making normal `Variable`.
By providing a custom builder, it's totally possible to construct `RefVariable` instead of default ones.

**Comment by golden0080** [comment]
In addition, `RefVariable` class could be your friend.

**Comment by rmothukuru** [comment]
> @jvishnuvardhan Yes, I think I could contribute to a doc update.
> Could you direct me to what I need to do for doc updates?

@golden0080,
Sorry for the delayed response. Please refer the links mentioned below for Contributing to Tensorflow Documentation:

Contributor guide: https://www.tensorflow.org/community/contribute/docs,
Docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
Docs style guide: https://www.tensorflow.org/community/contribute/docs_style

Thanks!
