### ISSUE TITLE
tflite_convert fails from keras model

### ISSUE THREAD

**Issue by tschul** [tensorflow/tensorflow#44045]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac 10.15
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 2.3

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CAST, CONCATENATION, CONV_2D, ELU, FILL, FULLY_CONNECTED, GATHER, LOGISTIC, MAX_POOL_2D, PACK, RESHAPE, REVERSE_V2, SHAPE, STRIDED_SLICE, TRANSPOSE. Here is a list of operators for which you will need custom implementations: StatelessWhile, TensorListFromTensor, TensorListReserve, TensorListStack.
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Standard text classification with Keras sequential model using embeddings, stacked CONV1D and stacked Bidirectional GRUs.
Switching to experimental converter does not help, --allow_custom_ops neither.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by amahendrakar** [comment]
@tschul,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and the Keras model you are using. 

Also, please take a looks issues [#42912](https://github.com/tensorflow/tensorflow/issues/42912#issuecomment-686185561) and [#33490](https://github.com/tensorflow/tensorflow/issues/33490#issuecomment-544351257) with a similar error and let us know it it helps. Thanks!
