### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'matrix_determinant'

### ISSUE THREAD

**Issue by StudentUsingGithup** [tensorflow/tensorflow#44041]
when i write in jupyter

```
import tensorflow as tf
matrix_det = tf.matrix_determinant(matrix_3)
```

the error will be:```

AttributeError                            Traceback (most recent call last)
<ipython-input-16-b52dc5929b23> in <module>
----> 1 matrix_det = tf.matrix_determinant(matrix_3)

AttributeError: module 'tensorflow' has no attribute 'matrix_determinant'
```

**Comment by Saduf2019** [comment]
I am able to replicate this issue, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/4a15a2dad484fc852a66e8165d95b945/untitled441.ipynb).

**Comment by ymodak** [comment]
`tf.matrix_determinant` is deprecated and revived as `tf.linalg.det`.
You may try using [`tf.linalg.det`](https://www.tensorflow.org/api_docs/python/tf/linalg/det) function in TF 2.X
