### ISSUE TITLE
Incompatible Layer Error in TF Sequential When Adding a Layer Stored in a Variable

### ISSUE THREAD

**Issue by GlorianY** [tensorflow/tensorflow#44048]
**System information**
- I write my own custom code 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): from pip
- TensorFlow version: 2.3.0
- Python version: 3.6.9

**How to Reproduce the Error**
>>> model = tf.keras.Sequential()
>>> model.add(tf.keras.layers.InputLayer(input_shape=[7]))
>>> layer = tf.keras.layers.Dense(units=20, activation='relu')
>>> model.add(layer)
>>> model.add(layer)

Attempting the second "model.add(layer)" will yield an error as follows:
``
ValueError: Input 0 of layer dense_7 is incompatible with the layer: expected axis -1 of input shape to have value 7 but received input with shape [None, 20]
``

It looks like this is a bug. 

The code will work if I do model.add(tf.keras.layers.Dense(units=20, activation='relu')) instead of model.add(layer). However, I can't do this since due to some project requirements, I need to assign tf.keras.layers.Dense(units=20, activation='relu') to a variable.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/ca1d87ab8843a70da58c69dffca99cb5/44048.ipynb). 

With [TF-nightly](https://colab.research.google.com/gist/amahendrakar/e68066ea1491ff966a99a328fc68186f/44048.ipynb#scrollTo=TDiTG9qgkM8O), the error changes to `ValueError: Dimensions must be equal, but are 20 and 7 for '{{node dense/MatMul}} = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false](Placeholder, dense/MatMul/ReadVariableOp)' with input shapes: [?,20], [7,20].`. Please find the attached gist. Thanks!

**Comment by ymodak** [comment]
A Sequential model is not appropriate when you need to do layer sharing.
See https://www.tensorflow.org/guide/keras/sequential_model#when_to_use_a_sequential_model

For this you can use Functional API which supports sharing layer instances that get reused multiple times in a same model.
See https://www.tensorflow.org/guide/keras/functional#shared_layers

Or - you can create unique layer instance for using it in Sequential model.
```python
model = tf.keras.Sequential()
model.add(tf.keras.layers.InputLayer(input_shape=[7]))
layer = tf.keras.layers.Dense(units=20, activation='relu')
layer1 = tf.keras.layers.Dense(units=20, activation='relu')
model.add(layer)
model.add(layer1)
```

**Comment by GlorianY** [comment]
@ymodak : Thanks for sharing the links. I guess the right way to reuse the layer instance is through the Functional API.

Regarding your proposed solution, to me, "layer" and "layer1" look redundant. Ideally, we don't need to make "layer1" which exactly similar to "layer".
But then, as we know, the error occurs if we don't make "layer1", and just do model.add(layer).

**Comment by ymodak** [comment]
Yes `Functional API` is the right approach to use here.
Usage `layer1` and `layer` creates a unique layer instance even though they appear to be redundant.
I will close this issue now. Feel free to reopen or create new issue if required.
Thanks!
