### ISSUE TITLE
There is no defined version as defined in Tensorflow website

### ISSUE THREAD

**Issue by yashrajjain726** [tensorflow/tensorflow#44051]
![Screenshot (130)_LI](https://user-images.githubusercontent.com/53373012/96131702-28e9af80-0f17-11eb-8791-d915f4c3d1c1.jpg)
![Screenshot (131)](https://user-images.githubusercontent.com/53373012/96131712-2b4c0980-0f17-11eb-83ae-33c159b83228.png)

Ohk, So as defined in the tensorflow gpu documentation, the tensorflow 2.3 can have a cuda version of 10.1 and cuDNN version of 7.4. But there isn't any cuDNN v7.4 for CUDA 10.1, according to the nvidia cuDNN archives. So, please update the version of cuDNN in your documentation, to the specified CUDA and Tensorflow version.

## URL(s) with the issue:

Link to the tensorflow gpu section:
https://www.tensorflow.org/install/source_windows#gpu

**Comment by mihaimaruseac** [comment]
It should be 7.6, not 7.4. Will fix the typo

**Comment by mihaimaruseac** [comment]
Edit: Note that Linux is properly updated: https://www.tensorflow.org/install/source#ubuntu

**Comment by mihaimaruseac** [comment]
Should be fixed by above PR
