### ISSUE TITLE
Segmentation fault (core dumped) error when using representative_dataset_gen()

### ISSUE THREAD

**Issue by tu1258** [tensorflow/tensorflow#44056]
I used tf 2.3 and met segmentation fault (core dumped) error when using `representative_dataset_gen()`.
**Code**
```
    def representative_dataset_gen():
      for audio in validation_fingerprints:
        yield [audio]
    converter = tf.lite.TFLiteConverter.from_saved_model(flags.train_dir + '/last_model')
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS]
    converter.allow_custom_ops = True
    converter.inference_input_type = tf.uint8
    converter.inference_output_type = tf.uint8
    # converter.representative_dataset = representative_dataset_gen
    quant_model = converter.convert()
    with open(flags.train_dir + '/quant_last_model.tflite', 'wb') as w:
      w.write(quant_model)
```
Above code can run without error but if I use `converter.representative_dataset = representative_dataset_gen`, it fail.

The type and shape of data are at below. The input layer size is `[Batch, 16384]`
```
type(validation_fingerprints): <class 'numpy.ndarray'>
shape(validation_fingerprints): (3093, 16384)
```

Any advice? Thanks!

**Comment by tu1258** [comment]
Any suggestion please? @amahendrakar

**Comment by amahendrakar** [comment]
@tu1258,
On running the code, I am facing an error stating `NameError: name 'flags' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/f265cceae1f37434f5d281850b53d799/44056.ipynb).

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by tu1258** [comment]
@amahendrakar 
Thanks for the reply. The code is just a demonstration. To reproduce the code you would have to import some custom file and the full process may be too complex. The `flags.train_dir + '/last_model'` is the model I saved after training. Could you find or guess the solution by the code above? I attach the model_summary below.
[model_summary.txt](https://github.com/tensorflow/tensorflow/files/5393551/model_summary.txt)

**Comment by amahendrakar** [comment]
@tu1258,
Without a reproducible code sample, it would be difficult for us to debug the issue. 

> To reproduce the result you would have to import some custom file and the full process may be too complex.

In this case, could you please provide a minimal code snippet to mimic the error so that we can reproduce the issue on our end. Thanks!
