### ISSUE TITLE
 go get github.com/tensorflow/tensorflow/tensorflow/go throwing an error

### ISSUE THREAD

**Issue by shrikantkeni** [tensorflow/tensorflow#44058]
Getting below error while installing tensorflow go module

```
-bash-4.2$ export LIBRARY_PATH=$LIBRARY_PATH:/home/gouser/lib/
-bash-4.2$ go get github.com/tensorflow/tensorflow/tensorflow/go
# github.com/tensorflow/tensorflow/tensorflow/go
/home/gouser/lib/libtensorflow.so: undefined reference to `std::length_error::length_error(char const*)@GLIBCXX_3.4.21'
/home/gouser/lib/libtensorflow.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
/home/gouser/lib/libtensorflow.so: undefined reference to `std::logic_error::logic_error(char const*)@GLIBCXX_3.4.21'
/home/gouser/lib/libtensorflow.so: undefined reference to `std::domain_error::domain_error(char const*)@GLIBCXX_3.4.21'
/home/gouser/lib/libtensorflow.so: undefined reference to `typeinfo for std::_V2::error_category@GLIBCXX_3.4.21'
/home/gouser/lib/libtensorflow.so: undefined reference to `std::__atomic_futex_unsigned_base::_M_futex_notify_all(unsigned int*)@GLIBCXX_3.4.21'
/home/gouser/lib/libtensorflow.so: undefined reference to `lgammaf@GLIBC_2.23'
/home/gouser/lib/libtensorflow.so: undefined reference to `std::_V2::error_category::default_error_condition(int) const@GLIBCXX_3.4.21'
/home/gouser/lib/libtensorflow.so: undefined reference to `std::_V2::error_category::equivalent(int, std::error_condition const&) const@GLIBCXX_3.4.21'
/home/gouser/lib/libtensorflow.so: undefined reference to `std::_V2::error_category::~error_category()@GLIBCXX_3.4.21'
/home/gouser/lib/libtensorflow.so: undefined reference to `std::_V2::generic_category()@GLIBCXX_3.4.21'
/home/gouser/lib/libtensorflow.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
/home/gouser/lib/libtensorflow.so: undefined reference to `std::invalid_argument::invalid_argument(char const*)@GLIBCXX_3.4.21'
/home/gouser/lib/libtensorflow.so: undefined reference to `std::_V2::error_category::equivalent(std::error_code const&, int) const@GLIBCXX_3.4.21'
/home/gouser/lib/libtensorflow.so: undefined reference to `std::runtime_error::runtime_error(char const*)@GLIBCXX_3.4.21'
/home/gouser/lib/libtensorflow.so: undefined reference to `std::_V2::system_category()@GLIBCXX_3.4.21'
/home/gouser/lib/libtensorflow.so: undefined reference to `std::out_of_range::out_of_range(char const*)@GLIBCXX_3.4.21'
/home/gouser/lib/libtensorflow.so: undefined reference to `std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >)@GLIBCXX_3.4.21'
/home/gouser/lib/libtensorflow.so: undefined reference to `std::underflow_error::underflow_error(char const*)@GLIBCXX_3.4.21'
/home/gouser/lib/libtensorflow.so: undefined reference to `std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>, void (*)())@GLIBCXX_3.4.21'
/home/gouser/lib/libtensorflow.so: undefined reference to `std::range_error::range_error(char const*)@GLIBCXX_3.4.21'
/home/gouser/lib/libtensorflow.so: undefined reference to `std::overflow_error::overflow_error(char const*)@GLIBCXX_3.4.21'
/home/gouser/lib/libtensorflow.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
/home/gouser/lib/libtensorflow.so: undefined reference to `std::__future_base::_State_baseV2::_Make_ready::_M_set()@GLIBCXX_3.4.21'
/home/gouser/lib/libtensorflow.so: undefined reference to `lgamma@GLIBC_2.23'
/home/gouser/lib/libtensorflow.so: undefined reference to `operator delete[](void*, unsigned long)@CXXABI_1.3.9'
/home/gouser/lib/libtensorflow.so: undefined reference to `std::_V2::error_category::_M_message(int) const@GLIBCXX_3.4.21'
```

**System information**
- CentOS Linux release 7.6.1810 (Core):
- Python version:
-bash-4.2$ python --version
Python 2.7.6
-bash-4.2$ python3 --version
Python 3.6.8

**Comment by Saduf2019** [comment]
@shrikantkeni 
please refer to this issue with same error reported #30111 [link](https://github.com/google/tink/issues/186), [link1](https://www.gitmemory.com/issue/tensorflow/tensorflow/30111/505720326)

**Comment by shrikantkeni** [comment]
I have executed the steps mentioned in 30111 by cloning source from git. but compilation of tensorflow using bazel failed with beow exception 

bazel test --config opt //tensorflow/tools/lib_package:libtensorflow_test



uild_tag_filters=-benchmark-test,-no_oss,-gpu,-v1only
INFO: Found applicable config definition build:opt in file /root/tensorflow/.tf_configure.bazelrc: --copt=-march=native --copt=-Wno-sign-compare --host_copt=-march=native --define with_default_optimizations=true
INFO: Found applicable config definition build:linux in file /root/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /root/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Analyzed target //tensorflow/tools/lib_package:libtensorflow_test (215 packages loaded, 20060 targets configured).
INFO: Found 1 test target...
INFO: Deleting stale sandbox base /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/sandbox
ERROR: /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/com_google_protobuf/BUILD:412:1: C++ compilation of rule '@com_google_protobuf//:protoc' failed (Exit 1)
gcc: error: unrecognized command line option '-std=c++14'
Target //tensorflow/tools/lib_package:libtensorflow_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 504.836s, Critical Path: 17.26s
INFO: 20 processes: 20 local.
FAILED: Build did NOT complete successfully
//tensorflow/tools/lib_package:libtensorflow_test               FAILED TO BUILD

**Comment by shrikantkeni** [comment]
@Saduf2019  
https://www.tensorflow.org/install/lang_go
I have also followed the steps mentioned in this link to install go packages, but that also throwing an error
I just want to understand whether the steps mentioned in this link is up to date?

**Comment by Saduf2019** [comment]
@shrikantkeni 
Please let us know the tf version you are referring to.

**Comment by shrikantkeni** [comment]
I just cloned latest version 

go get github.com/tensorflow/tensorflow/tensorflow/go

and 

git clone https://github.com/tensorflow/tensorflow.git

**Comment by shrikantkeni** [comment]
https://www.tensorflow.org/install/lang_c

I have also downloaded the library from above link and  tried compiling sample C code 


[root@localhost ~]# gcc hello_tf.c -I /usr/local/include/tensorflow/c/ -L /usr/local/lib/ -ltensorflow -o hello_tf
/usr/local/lib//libtensorflow.so: undefined reference to `std::length_error::length_error(char const*)@GLIBCXX_3.4.21'
/usr/local/lib//libtensorflow.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
/usr/local/lib//libtensorflow.so: undefined reference to `std::logic_error::logic_error(char const*)@GLIBCXX_3.4.21'
/usr/local/lib//libtensorflow.so: undefined reference to `std::domain_error::domain_error(char const*)@GLIBCXX_3.4.21'
/usr/local/lib//libtensorflow.so: undefined reference to `typeinfo for std::_V2::error_category@GLIBCXX_3.4.21'
/usr/local/lib//libtensorflow.so: undefined reference to `std::__atomic_futex_unsigned_base::_M_futex_notify_all(unsigned int*)@GLIBCXX_3.4.21'
/usr/local/lib//libtensorflow.so: undefined reference to `lgammaf@GLIBC_2.23'
/usr/local/lib//libtensorflow.so: undefined reference to `std::_V2::error_category::default_error_condition(int) const@GLIBCXX_3.4.21'
/usr/local/lib//libtensorflow.so: undefined reference to `std::_V2::error_category::equivalent(int, std::error_condition const&) const@GLIBCXX_3.4.21'
/usr/local/lib//libtensorflow.so: undefined reference to `std::_V2::error_category::~error_category()@GLIBCXX_3.4.21'
/usr/local/lib//libtensorflow.so: undefined reference to `std::_V2::generic_category()@GLIBCXX_3.4.21'
/usr/local/lib//libtensorflow.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
/usr/local/lib//libtensorflow.so: undefined reference to `std::invalid_argument::invalid_argument(char const*)@GLIBCXX_3.4.21'
/usr/local/lib//libtensorflow.so: undefined reference to `std::_V2::error_category::equivalent(std::error_code const&, int) const@GLIBCXX_3.4.21'
/usr/local/lib//libtensorflow.so: undefined reference to `std::runtime_error::runtime_error(char const*)@GLIBCXX_3.4.21'
/usr/local/lib//libtensorflow.so: undefined reference to `std::_V2::system_category()@GLIBCXX_3.4.21'
/usr/local/lib//libtensorflow.so: undefined reference to `std::out_of_range::out_of_range(char const*)@GLIBCXX_3.4.21'
/usr/local/lib//libtensorflow.so: undefined reference to `std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >)@GLIBCXX_3.4.21'
/usr/local/lib//libtensorflow.so: undefined reference to `std::underflow_error::underflow_error(char const*)@GLIBCXX_3.4.21'
/usr/local/lib//libtensorflow.so: undefined reference to `std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>, void (*)())@GLIBCXX_3.4.21'
/usr/local/lib//libtensorflow.so: undefined reference to `std::range_error::range_error(char const*)@GLIBCXX_3.4.21'
/usr/local/lib//libtensorflow.so: undefined reference to `std::overflow_error::overflow_error(char const*)@GLIBCXX_3.4.21'
/usr/local/lib//libtensorflow.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
/usr/local/lib//libtensorflow.so: undefined reference to `std::__future_base::_State_baseV2::_Make_ready::_M_set()@GLIBCXX_3.4.21'
/usr/local/lib//libtensorflow.so: undefined reference to `lgamma@GLIBC_2.23'
/usr/local/lib//libtensorflow.so: undefined reference to `operator delete[](void*, unsigned long)@CXXABI_1.3.9'
/usr/local/lib//libtensorflow.so: undefined reference to `std::_V2::error_category::_M_message(int) const@GLIBCXX_3.4.21'
collect2: error: ld returned 1 exit status

**Comment by shrikantkeni** [comment]
Please let me know if any specific linux version which I have to use to make this work.

**Comment by angerson** [comment]
@jhseu Do you know who should be notified about golang issues like this?

**Comment by jhseu** [comment]
My guess is this is caused by an old libstdc++, probably from an older Linux distribution. For Ubuntu, I think 16.04 or later should have the right version.

**Comment by chunduriv** [comment]
@shrikantkeni,

Sorry for the late response. Please can you take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/44058#issuecomment-725043648).

Please follow [this](https://github.com/tensorflow/build/tree/master/golang_install_guide) latest documentation for installing the Go bindings for TensorFlow. Thank you.
