### ISSUE TITLE
Training pipeline significantly slower for epoch > 1 with caching to disk

### ISSUE THREAD

**Issue by sadeel** [tensorflow/tensorflow#44050]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Cloud AI platform
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
From PyPi
- TensorFlow version (use command below):
2.2
- Python version:
3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: 
NVIDIA P100 

**Describe the current behavior**
My training pipeline is significantly slower for epoch > 1

```
Epoch 1/100
3198/3198 - 2287s - loss: 2.7595 - binary_accuracy: 0.8080
Epoch 2/100
3198/3198 - 3974s - loss: 0.9275 - binary_accuracy: 0.8086
Epoch 3/100
3198/3198 - 3562s - loss: 0.5781 - binary_accuracy: 0.8124
Epoch 4/100
3198/3198 - 3572s - loss: 0.5227 - binary_accuracy: 0.8064
```

**Describe the expected behavior**
The TFRecords originate in GCS. I am using caching to disk, so I expect epoch > 1 to be faster than epoch=1

**Standalone code to reproduce the issue**
```
  train_data = tf.data.TFRecordDataset(train_files)
  train_data = train_data.cache(os.path.join(FLAGS.cache_dir, 'train'))
  train_data = train_data.map(training_parser)
  train_data = train_data.prefetch(4)

  val_data = None
  if val_files:
    val_data = tf.data.TFRecordDataset(val_files)
    val_data = val_data.cache(os.path.join(FLAGS.cache_dir, 'val'))
    val_data = val_data.map(validation_parser)
    val_data = val_data.prefetch(4)

  model.fit(
      x=train_data,
      validation_data=val_data,
      epochs=FLAGS.epochs,
      callbacks=[tensorboard_callback,
                 _HyperparmeterTuningCallback()],
      verbose=2)

```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@sadeel 

Please, share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!
