### ISSUE TITLE
[TfLite] gpu gl delegate: reduce_mean([1,2]) returns average of first row only 

### ISSUE THREAD

**Issue by natario1** [tensorflow/tensorflow#44060]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Nexus 5X
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.2.0
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

Given a simple model that computes the average intensity of a square, grayscale image:

```python
input = Input(shape=(16,16), batch_size=1, dtype=tf.float32)
output = tf.math.reduce_mean(input, axis = [1, 2])
model = Model(inputs=input, outputs=output, name='mean')
```

when no delegate is used, the average is correct, but when the GPU delegate is used with a SSBO,
the returned value is the average of the first row only, not that of the whole image as it should be. 
I have tested thoroughly that the SSBO values are correct by reading them with glMapBufferRange.
The SSBO array has exactly 16x16 values and the result is always the average of pixels [0, 16, 32, ...].

I can't see issues with lite/delegates/gpu/gl/kernels/mean.h , so I think the wrong dimension is being picked for some reason.

**Describe the expected behavior**

`reduce_mean` should return the average along the two dimensions.

**Other info / logs** 

To enable SSBOs I am using a slightly modified version of TFLite 2.2.0 (https://github.com/natario1/tensorflow/commit/7401fbb4fa0c94004865c089d8c89bdd566ad747) and passing in this object def:

```cpp
tflite::gpu::ObjectDef get_gpu_object_def() {
    tflite::gpu::ObjectDef object_def;
    object_def.data_type = tflite::gpu::DataType::FLOAT32;
    object_def.data_layout = tflite::gpu::DataLayout::BHWC;
    object_def.object_type = tflite::gpu::ObjectType::OPENGL_SSBO;
    object_def.user_provided = true;
    return object_def;
}
```

Note that I use this same logic to run much more complex models (like MediaPipe models) and it works well, so I'm tempted to say that this is an issue with reduce_mean or with my test model.

[simple_model_16x16b.tflite.zip](https://github.com/tensorflow/tensorflow/files/5387188/simple_model_16x16b.tflite.zip)

**More info after investigation**

I found out that the issue is fixed if I explicitly add the channel dimension to the model, so 1x16x16x1 instead of 1x16x16.
This is not consistent with the CPU behavior (delegate off, no SSBOs, only CPU data), where a 1x16x16 model works just fine.

Also it's not clear why, if the last 1 is absent, the dimensions are misinterpreted in such a way that leads `reduce_mean` to only average the first row. I could understand this if we were *adding* an extra dimension equal to 1 in the wrong place (which could be taken as width or height), but in this case we are actually *removing* it.

**Comment by sushreebarsa** [comment]
@natario1 It looks like you are using an older Version of Tensorflow . Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.5 and let us know if the issue still persists? Thanks!
