### ISSUE TITLE
tflite model maker export error, attribute ModelMetadataT not found

### ISSUE THREAD

**Issue by shilan** [tensorflow/tensorflow#44062]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Following exactly the stock example https://www.tensorflow.org/lite/tutorials/model_maker_image_classification
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.3.1
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Trying to run the example, everything goes fine and the model trains successfully, however when trying to finally export
the model
model.export(export_dir='.')
I get this error
AttributeError: module 'tensorflow_lite_support.metadata.metadata_schema_py_generated' has no attribute 'ModelMetadataT'

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
AttributeError                            Traceback (most recent call last)
<ipython-input-3-4c3d25dac6cc> in <module>
----> 1 model.export(export_dir='.')

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tensorflow_examples\lite\model_maker\core\task\image_classifier.py in export(self, export_dir, tflite_filename, label_filename, saved_model_filename, export_format, **kwargs)
    305       **kwargs: Other parameters like `quantized` for TFLITE model.
    306     """
--> 307     super(ImageClassifier, self).export(
    308         export_dir,
    309         tflite_filename=tflite_filename,

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tensorflow_examples\lite\model_maker\core\task\custom_model.py in export(self, export_dir, tflite_filename, label_filename, vocab_filename, saved_model_filename, export_format, **kwargs)
    161       with_metadata = kwargs.get('with_metadata', True)
    162       tflite_filepath = os.path.join(export_dir, tflite_filename)
--> 163       self._export_tflite(tflite_filepath, **kwargs)
    164     else:
    165       with_metadata = False

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tensorflow_examples\lite\model_maker\core\task\image_classifier.py in _export_tflite(self, tflite_filepath, quantization_config, with_metadata, export_metadata_json_file)
    344         populator = metadata_writer.MetadataPopulatorForImageClassifier(
    345             tflite_filepath, model_info, label_filepath)
--> 346         populator.populate()
    347 
    348       # Validate the output model file by reading the metadata and produce

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tensorflow_examples\lite\model_maker\core\task\metadata_writer_for_image_classifier.py in populate(self)
     87   def populate(self):
     88     """Creates metadata and then populates it for an image classifier."""
---> 89     self._create_metadata()
     90     self._populate_metadata()
     91 

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tensorflow_examples\lite\model_maker\core\task\metadata_writer_for_image_classifier.py in _create_metadata(self)
     94 
     95     # Creates model info.
---> 96     model_meta = _metadata_fb.ModelMetadataT()
     97     model_meta.name = self.model_info.name
     98     model_meta.description = ("Identify the most prominent object in the "

AttributeError: module 'tensorflow_lite_support.metadata.metadata_schema_py_generated' has no attribute 'ModelMetadataT'

**Comment by amahendrakar** [comment]
@shilan,
I was able to run the code without any issues, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/5d01785804ac2082a277421e3e421184/44062.ipynb).

Could you please try running the code in a virtual environment and check if you are facing the same issue? Thanks!

**Comment by amahendrakar** [comment]
Also, could you please let us know if you have installed Python from the Microsoft store or from [python.org](https://www.python.org/downloads/windows/)? Thanks!

**Comment by ziyeqinghan** [comment]
I have tested and It works for python3.8.5 using conda virtual environment. Could you please check whether the version of `tflite-support` pip package is 0.1.0rc3.dev2 by `pip list | grep tflite-support`? 

Meanwhile, as for [PR](https://github.com/tensorflow/tensorflow/issues/43986), we should have fixed it. 

BTW, if you didn't use metadata when deploying the tflite model, you could set `with_metadata=False` like:
```
model.export(export_dir='.', with_metadata=False)
```
This could  also avoid this bug.

**Comment by ziyeqinghan** [comment]
Hi, could you please uninstall tflite-support and install `0.1.0rc3.dev3` instead? There was a bug in tflite-support on Windows for previous version.
```
pip install tflite-support==0.1.0rc3.dev3
```

**Comment by shilan** [comment]
I will try to install tflite-support version you mentioned. Soon I will let you know.

**Comment by shilan** [comment]
many thanks :) updating the tflite-support version worked like a charm :)
However I don't understand now, where is my tflite file now? Why do I get warnings?

WARNING:tensorflow:From C:\Users\Chingool\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tensorflow\python\training\tracking\tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
WARNING:tensorflow:From C:\Users\Chingool\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tensorflow\python\training\tracking\tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
WARNING:tensorflow:From C:\Users\Chingool\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tensorflow\python\training\tracking\tracking.py:111: Layer.updates (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
WARNING:tensorflow:From C:\Users\Chingool\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\tensorflow\python\training\tracking\tracking.py:111: Layer.updates (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: C:\Users\Chingool\AppData\Local\Temp\tmpa90j264d\assets
INFO:tensorflow:Assets written to: C:\Users\Chingool\AppData\Local\Temp\tmpa90j264d\assets
INFO:tensorflow:Label file is inside the TFLite model with metadata.
INFO:tensorflow:Label file is inside the TFLite model with metadata.
INFO:tensorflow:Saving labels in C:\Users\Chingool\AppData\Local\Temp\tmpswhd3rra\labels.txt.
INFO:tensorflow:Saving labels in C:\Users\Chingool\AppData\Local\Temp\tmpswhd3rra\labels.txt.

**Comment by shilan** [comment]
I found the model here, pretty weird place though:
C:\Users\Chingool\_bazel_Chingool\gmciwitk\external\org_tensorflow\bazel-machine-learning\tensorflow
I assume I can give it a better directory if I change the argument of this method model.export(export_dir='.'), right?

**Comment by Fresh-Broccoli** [comment]
> Hi, could you please uninstall tflite-support and install `0.1.0rc3.dev3` instead? There was a bug in tflite-support on Windows for previous version.
> 
> ```
> pip install tflite-support==0.1.0rc3.dev3
> ```

I tried to update, but I got this error:

ERROR: Could not find a version that satisfies the requirement tflite-support==0.1.0rc3.dev3 (from versions: 0.1.0a0.dev3, 0.1.0a0.dev4, 0.1.0a0.dev5, 0.1.0a0, 0.1.0a1, 0.1.0rc3.dev2)
ERROR: No matching distribution found for tflite-support==0.1.0rc3.dev3

**Comment by amahendrakar** [comment]
@Fresh-Broccoli,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
