### ISSUE TITLE
tf.keras.layers.experimental.preprocessing.TextVectorization doesn't raise error when  len(vocabulary_list)<=max_tokens<len(vocabulary_list) + 2

### ISSUE THREAD

**Issue by DachuanZhao** [tensorflow/tensorflow#44069]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win10
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): tf2.3
- Python version: 3.7

**Describe the current behavior**
It doesn't raise error :
```
vocabulary_list = ["a", "b", "c"]
text_dataset = tf.data.Dataset.from_tensor_slices(vocabulary_list)
max_features = 3 # Maximum vocab size.

# Create the layer.
vectorize_layer = tf.keras.layers.experimental.preprocessing.TextVectorization(
 max_tokens=max_features)

# Now that the vocab layer has been created, call `adapt` on the text-only
# dataset to create the vocabulary. You don't have to batch, but for large
# datasets this means we're not keeping spare copies of the dataset.
vectorize_layer.adapt(text_dataset.batch(64))
```
This will lead to wrong result : 
```
vectorize_layer(["a b c d e"])
# output :
# <tf.Tensor: shape=(1, 5), dtype=int64, numpy=array([[1, 1, 2, 1, 1]])>
```

**Describe the expected behavior**
Raise error :
```
ValueError: Attempted to set a vocabulary larger than the maximum vocab size. Passed vocab size is 5, max vocab size is 3.
```

**Comment by DachuanZhao** [comment]
When ```output_model = "binary"``` , It doen't raise error since  ```max_features = 2```

**Describe the current behavior**
It doesn't raise error :
```
vocabulary_list = ["a", "b", "c"]
text_dataset = tf.data.Dataset.from_tensor_slices(vocabulary_list)
max_features = 2 # Maximum vocab size.

# Create the layer.
vectorize_layer = tf.keras.layers.experimental.preprocessing.TextVectorization(
 max_tokens=max_features,output_model = "binary")

# Now that the vocab layer has been created, call `adapt` on the text-only
# dataset to create the vocabulary. You don't have to batch, but for large
# datasets this means we're not keeping spare copies of the dataset.
vectorize_layer.adapt(text_dataset.batch(64))
```

**Describe the expected behavior**
Raise error :
```
ValueError: Attempted to set a vocabulary larger than the maximum vocab size. Passed vocab size is 5, max vocab size is 2.
```

**Comment by DachuanZhao** [comment]
Maybe [https://github.com/tensorflow/tensorflow/issues/41552](https://github.com/tensorflow/tensorflow/issues/41552) is the same problem .

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tensorflow 2.5, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/7987a78a23fa3801df1d15207ad244cb/44069.ipynb). Thanks!

**Comment by mohantym** [comment]
Hi @DachuanZhao! I was able to resolve the issue by using `tf.keras.layers.TextVectorization` instead of `tf.keras.layers.experimental.preprocessing.TextVectorization` in TF 2.7 . Attaching [Gist ](https://colab.research.google.com/gist/mohantym/92eedc0747b3af556493a73aa1e6c35c/44069.ipynb#scrollTo=pyKTWxg-7yRC)for reference . Thank you!
