### ISSUE TITLE
How do we know the compatibility of flatbuffers version in SchemaGenerated.h 

### ISSUE THREAD

**Issue by tsindhuja** [tensorflow/tensorflow#44075]
After building the flatbuffers latest release and combining with the latest SchemaGenerated.h, there's an error as below

> Error	1	error LNK2001: unresolved external symbol "private: static class flatbuffers::ClassicLocale flatbuffers::ClassicLocale::instance_" (?instance_@ClassicLocale@flatbuffers@@0V12@A)

This error is mostly due to incompatibility between flatbuffers version in my system and version used for SchemaGenerated.h
FLatbuffers version used: 1.12.0

**Comment by ravikyram** [comment]
@tsindhuja 

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by tsindhuja** [comment]
1. Downloaded flatbuffers source code from https://github.com/google/flatbuffers/releases
2. Built using CMAKE GUI on windows 10[By using configuration-x64]
3. Opened the project in Visual Studio 13 and ran 'Build' for 'ALL BUILD' project for both Debug and Release
4. Extracted SchemaGenerated.h from [https://github.com/tensorflow/tensorflow/tree/ec59a624ac3c20c800ef7dfb759daf1e5bd11efa/tensorflow/lite/schema]
5. While trying to build my cpp project in Visual Studio 13 the above error occurred. 

Note: The respective libraries and include files were mentioned in the Project Properties

**Comment by jdduke** [comment]
Generally you can find the appropriate flatbuffer version in the [TensorFlow deps spec](https://github.com/tensorflow/tensorflow/blob/master/third_party/flatbuffers/workspace.bzl#L10). In this case, it should be 1.12. This is more likely an issue with your compiler and/or the CMake configuration.

Have you looked at the experimental [CMake support](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/CMakeLists.txt) for TensorFlow Lite? Is there a reason you're downloading and building the Flatbuffers library manually?
