### ISSUE TITLE
The weights data in tflite model is still in float32 format

### ISSUE THREAD

**Issue by Harleytu** [tensorflow/tensorflow#44070]
**System information**
- Windows 10
- wheel
- 1.14.0 CPU

 **I convert the tflite from a saved_model as the follow API, and got a tflite model, then I use Netron to open it, why the weights
data in the tflite model is still float32, shouldn't it be int8?**

```
# tf.lite.TFLiteConverter.from_saved_model(model_path)
```

**Comment by Harleytu** [comment]
It seems like that the model is converted to tflite, but the weights is not quantified.

**Comment by Saduf2019** [comment]
@Harleytu 
Can you please let us know if it is saved as keras model.save or saved in Savedmodel format, also verify if you have specified the optimization option correctly.

**Comment by Harleytu** [comment]
@Saduf2019 Thank you, your answer helped me a lot.
