### ISSUE TITLE
Tensorflow lite application execution on CPU only

### ISSUE THREAD

**Issue by Ankita-020696** [tensorflow/tensorflow#44071]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

Hello,
We are trying to execute TFLite application (label_image) on RPi CPU only. We tried cross compilation for aarch64(RaspberryPi). Here are the steps
1. Installed bazel
2. git clone https://github.com/tensorflow/tensorflow.git
    cd tensorflow
3. ./configure

> You have bazel 3.1.0 installed.
> Please specify the location of python. [Default is /usr/bin/python3]: 
> Found possible Python library paths:
>   /usr/local/lib/python3.6/dist-packages
>   /usr/lib/python3/dist-packages
> Please input the desired Python library path to use.  Default is [/usr/local/lib/python3.6/dist-packages]
> 
> Do you wish to build TensorFlow with ROCm support? [y/N]: n
> No ROCm support will be enabled for TensorFlow.
> 
> Do you wish to build TensorFlow with CUDA support? [y/N]: n
> No CUDA support will be enabled for TensorFlow.
> 
> Do you wish to download a fresh release of clang? (Experimental) [y/N]: n
> Clang will not be downloaded.
> 
> Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 
> 
> 
> Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
> Not configuring the WORKSPACE for Android builds.
> 
> Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
> 	--config=mkl         	# Build with MKL support.
> 	--config=monolithic  	# Config for mostly static monolithic build.
> 	--config=ngraph      	# Build with Intel nGraph support.
> 	--config=numa        	# Build with NUMA support.
> 	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
> 	--config=v2          	# Build TensorFlow 2.x instead of 1.x.
> Preconfigured Bazel build configs to DISABLE default on features:
> 	--config=noaws       	# Disable AWS S3 filesystem support.
> 	--config=nogcp       	# Disable GCP support.
> 	--config=nohdfs      	# Disable HDFS support.
> 	--config=nonccl      	# Disable NVIDIA NCCL support.
> Configuration finished

4.  bazel build --config=elinux_aarch64 //tensorflow/lite/examples/label_image:label_image

Build was successful, but not sure that application executed on CPU only or it is using GPU as well.
1. Can you please help us with running tensorflow_lite application on CPU only(disable GPU)?
2. How to check whether application using both CPU & GPU or only CPU?

Thanks

**Comment by terryheo** [comment]
That's actually configuration for TensorFlow not TensorFlow Lite.
TensorFlow Lite is using different GPU path which is enabled with GPU delegate.
https://www.tensorflow.org/lite/performance/gpu
You'll use CPU only execution until you enabled GPU delegate.

BTW, GPU delegate on RPI isn't available for now.

**Comment by lixin679** [comment]
> That's actually configuration for TensorFlow not TensorFlow Lite.
> TensorFlow Lite is using different GPU path which is enabled with GPU delegate.
> https://www.tensorflow.org/lite/performance/gpu
> You'll use CPU only execution until you enabled GPU delegate.
> 
> BTW, GPU delegate on RPI isn't available for now.



> That's actually configuration for TensorFlow not TensorFlow Lite.
> TensorFlow Lite is using different GPU path which is enabled with GPU delegate.
> https://www.tensorflow.org/lite/performance/gpu
> You'll use CPU only execution until you enabled GPU delegate.
> 
> BTW, GPU delegate on RPI isn't available for now.

Excuse me, is GPU delegate available on the server for TFLite?

My server is:

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

I've tried to compile TFLite with --copt=-DCL_DELEGATE_NO_GL (bazel build -c opt --copt=-DCL_DELEGATE_NO_GL --copt=-DEGL_NO_X11 tensorflow/lite/tools/evaluation/tasks/imagenet_image_classification:run_eval)

But it still tell me like this:

The GPU delegate compile options are only supported on Android or iOS platforms or when the tool was built with -DCL_DELEGATE_NO_GL.
GPU acceleration is unsupported on this platform.

Thanks a lot!
