### ISSUE TITLE
Error with my own model trained in android demo 

### ISSUE THREAD

**Issue by jthoth** [tensorflow/tensorflow#4407]
SETTING CODE ANDROID 

  private static final int NUM_CLASSES = 26;
  private static final int INPUT_SIZE = 299;
  private static final int IMAGE_MEAN = 128;
  private static final float IMAGE_STD = 128;
  private static final String INPUT_NAME = "Mul:0";
  private static final String OUTPUT_NAME = "final_result:0";

ERROR ADB LOGCAT 

tensorflow_jni.cc:304 Error during inference: Invalid argument: No OpKernel was registered to support Op 'DecodeJpeg' with these attrs.  Registered kernels:

<no registered kernels>

 [[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, fancy_upscaling=true, ratio=1, try_recover_truncated=false](DecodeJpeg/contents)]]

09-16 01:01:02.882 3006-3029/org.tensorflow.demo A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 3029 (InferenceThread)
09-16 01:01:02.989 257-257/? A/DEBUG: pid: 3006, tid: 3029, name: InferenceThread  >>> org.tensorflow.demo <<<
09-16 01:01:03.060 257-257/? A/DEBUG:     #05 pc 00610a98  /data/app/org.tensorflow.demo-2/lib/arm/libtensorflow_demo.so
09-16 01:01:03.061 257-257/? A/DEBUG:     #06 pc 00610c1c  /data/app/org.tensorflow.demo-2/lib/arm/libtensorflow_demo.so
09-16 01:01:03.061 257-257/? A/DEBUG:     #07 pc 00610c38  /data/app/org.tensorflow.demo-2/lib/arm/libtensorflow_demo.so
09-16 01:01:03.061 257-257/? A/DEBUG:     #08 pc 00083f40  /data/app/org.tensorflow.demo-2/lib/arm/libtensorflow_demo.so
09-16 01:01:03.061 257-257/? A/DEBUG:     #09 pc 0008415c  /data/app/org.tensorflow.demo-2/lib/arm/libtensorflow_demo.so

**Comment by jthoth** [comment]
I found the solution

https://github.com/tensorflow/tensorflow/issues/1269

**Comment by andydavis1** [comment]
Closing, since it looks like you found a solution.

**Comment by turbopape** [comment]
Hey,

Mind please explain how do you compute INPUT_SIZE etc?
Thank you!
