### ISSUE TITLE
Tensorflow lite object detection  andriod examples app run on my phone but nothing detection 

### ISSUE THREAD

**Issue by mingx9527** [tensorflow/tensorflow#44078]
[GitHub Policy](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android),

**System information**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: xiaomi mi 6x

**Describe the current behavior**
build is OK
run is OK 
but  can not detection erverthing object : 
![WeChat Image_20201016154631](https://user-images.githubusercontent.com/36255328/96235722-b8ea3080-0fcd-11eb-96e6-d8a11b6bf88f.jpg)

**Comment by Saduf2019** [comment]
@mingx9527 
Please open this issue in models repo.

**Comment by mingx9527** [comment]
@Saduf2019  thank you response! 
I add the question in model repo:https://github.com/tensorflow/models/issues/9389 
waiting response!

**Comment by Saduf2019** [comment]
@mingx9527 
Please move this issue to closed status as it is tracked at the models repo.
