### ISSUE TITLE
Getting errors when converting a simple convs model to INT8 TFLite

### ISSUE THREAD

**Issue by car1hsiung** [tensorflow/tensorflow#44079]
**System information**
- OS Platform and Distribution: **Ubuntu 18.04**
- TensorFlow installed from binary
- TensorFlow version: **tf-nightly (2.4.0-dev20201015)** and **tf-2.3.0**
- TensorFlow Model Optimization version: **0.5.0**

**Command used to run the converter or code if you’re using the Python API**

FP32 TFLite is work, but INT8 TFLite is not work with tf-nightly.

Please check the [gist](https://colab.research.google.com/drive/14glMvUN1H2PZHB2VPOwX9sZX9E2RNu0J?usp=sharing) \(tf-nightly\).

1. Can not convert quantization aware model to INT8 TFLite.

2. `converter.inference_input_type = tf.int8` and `converter.inference_output_type = tf.int8` are not work.

3. FP32 TFLite is work.

Item 2 has been fixed in 2.3.0 \(#36024\), but still has another error.

Please check the [gist](https://colab.research.google.com/drive/1ejLyom6qeGJlxkk0jL62OF7ybrzzX3Wu?usp=sharing) \(tf-2.3.0\)

**The output from the converter invocation**

Item 1:

```
RuntimeError: tensorflow/lite/kernels/quantize.cc:113 affine_quantization->scale->size == 1 was not true.Node number 0 (QUANTIZE) failed to prepare.
```

Item 2:

```
ValueError: The inference_input_type and inference_output_type must be tf.float32.
```

**Failure details**

Get errors in tensorflow

Thanks in advance.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/c9fe5970e900520fadff7c515c18a13e/44079_2.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/26edd3e78722dfa86b4bccf93d21a8fc/44079_2-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by car1hsiung** [comment]
**System information**
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from binary
- TensorFlow version: tf-nightly (2.5.0.dev20201029)
- TensorFlow Model Optimization version: 0.5.0.dev20201103 (installed from github)

**Command used to run the converter or code**

It can convert model to INT8 TFLite successfully with latest tf-nightly,

but fail to convert quantized model with tensorflow_model_optimization.

Please check the [gist](https://colab.research.google.com/drive/1UeEnd2Hh3Xc2fLxuBEsy2G_qBRrP0hdN?usp=sharing).

**The output from the converter invocation**

```
RuntimeError: Quantization not yet supported for op: 'DEQUANTIZE'.
```

Might be similar to issue #42082

Thanks in advance.

**Comment by hhass** [comment]
**System information**
- OS Platform and Distribution: Windows 10 64bit
- TensorFlow version: tf-nightly (2.5.0.dev20201103) (installed from github)
- TensorFlow Model Optimization version: 0.5.0 (installed from github)

When running the gist of previous comment locally, the following error occurs already for 'Convert normal model to INT8 TFLite':

```
Exception has occurred: AttributeError
module 'tensorflow.lite.python.schema_py_generated' has no attribute 'Model'
```

**Comment by YANxu-666** [comment]
module 'tensorflow.lite.python.schema_py_generated' has no attribute 'Model'

**Comment by hhass** [comment]
#42082

**Comment by hhass** [comment]
Issue of the last comments was solved in #44882 
@MeghnaNatraj , is there a rough estimate at which point `converter.inference_output_type = tf.int8` will work for quantization-aware models?

**Comment by MeghnaNatraj** [comment]
@hhass It is supported in all 2.4 versions. For details refer to this [comment](https://github.com/tensorflow/tensorflow/issues/42082#issue-673921045)

The changes were made in this [commit](https://github.com/tensorflow/tensorflow/commit/5832fa2)

**Comment by car1hsiung** [comment]
> **System information**
> 
>     * OS Platform and Distribution: Ubuntu 18.04
> 
>     * TensorFlow installed from binary
> 
>     * TensorFlow version: tf-nightly (2.5.0.dev20201029)
> 
>     * TensorFlow Model Optimization version: 0.5.0.dev20201103 (installed from github)
> 
> 
> **Command used to run the converter or code**
> 
> It can convert model to INT8 TFLite successfully with latest tf-nightly,
> 
> but fail to convert quantized model with tensorflow_model_optimization.
> 
> Please check the [gist](https://colab.research.google.com/drive/1UeEnd2Hh3Xc2fLxuBEsy2G_qBRrP0hdN?usp=sharing).
> 
> **The output from the converter invocation**
> 
> ```
> RuntimeError: Quantization not yet supported for op: 'DEQUANTIZE'.
> ```
> 
> Might be similar to issue #42082
> 
> Thanks in advance.

Close the issue, because the error is duplicate of 42082.

**Comment by car1hsiung** [comment]
Thanks for  MeghnaNatraj's [example](https://github.com/tensorflow/tensorflow/issues/42082#issuecomment-745541910).

I can convert QAT models successfully. My [gist](https://colab.research.google.com/drive/1P4tnoZ4Sb9Q_uwRr2CxwcAtCM8rtzlFo?usp=sharing)
