### ISSUE TITLE
`size` argument of TensorArray works only when specified by pythonic int but tf.Tensor doesn't

### ISSUE THREAD

**Issue by Harrypotterrrr** [tensorflow/tensorflow#44073]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Linux lz 5.4.0-48-generic #52~18.04.1-Ubuntu`
- TensorFlow installed from (source or binary):  `(in conda env) pip install tensorflow-gpu -i https://pypi.tuna.tsinghua.edu.cn/simple`
- TensorFlow version (use command below): `v2.3.0-rc2-23-gb36436b087 2.3.0`
- Python version: `3.8`
- CUDA/cuDNN version: `conda install cudatoolkit=10.1 cudnn=7.6.5`
- GPU model and memory:  ` 4 x Titan xp 12GB`

**Describe the current behavior**

Reference issue: #43698 
Thanks for @saxenasaurabh 's answer. I could initialized the `TensorArray` with a fixed size. However, when I tried to specify the size of the `TensorArray` with tf.Tensor from `tf.shape`, the length of the tensor after stacked together will be None:
```
emb.shape: TensorShape([2, 3, 180, 320, 32])
cor_l.shape: TensorShape([None, 2, 180, 320])
cor_prob1.shape: TensorShape([2, None, 180, 320])
cor_prob2.shape: TensorShape([2, None, 180, 320, 1])
cor_prob3.shape: TensorShape([2, None, 180, 320, 32])
cor_prob4.shape: TensorShape([2, 180, 320, None, 32])
cor_prob5.shape: TensorShape([2, 180, 320, None])
aligned_fea.shape: TensorShape([2, 180, 320, 3, 32])
aligned_fea.shape: TensorShape([2, 180, 320, 96])
```
Parts of the code are as following shows:
``` python
aligned_fea_shape = tf.shape(aligned_fea) # B, N, H, W, C
B = aligned_fea_shape[0]
N = aligned_fea_shape[1]
H = aligned_fea_shape[2]
W = aligned_fea_shape[3]
C = aligned_fea_shape[4]

####
some other codes omit here
####

emb = tf.reshape(emb, [B, N, H, W, -1])
tf.print("emb.shape:", emb.shape)

cor_l = tf.TensorArray(dtype=tf.float32, size=N) # TENSORFLOW BUG HERE !
def cond(i, N, input, arr):
    return tf.less(i, N)
def body(i, N, input, arr):
    emb_nbr = input[:, i, :, :, :]
    cor_tmp = tf.reduce_sum(emb_nbr * emb_ref, axis=3) # B, H, W
    arr = arr.write(i, cor_tmp)
    i = tf.add(i, 1)
    return i, N, input, arr
_, _, _, cor_l = tf.while_loop(cond, body, [0, N, emb, cor_l]) # N * (B, H, W)
cor_l = cor_l.stack() # N, B, H, W
tf.print("cor_l.shape:", cor_l.shape)

cor_l = tf.transpose(cor_l, [1, 0, 2, 3]) # B, N, H, W

cor_prob = tf.sigmoid(cor_l)  # B, N, H, W
tf.print("cor_prob1.shape:", cor_prob.shape)

cor_prob = tf.expand_dims(cor_prob, axis=4) # B, N, H, W, 1
tf.print("cor_prob2.shape:", cor_prob.shape)

cor_prob = tf.tile(cor_prob, [1, 1, 1, 1, C]) # B, N, H, W, C

cor_prob = tf.transpose(cor_prob, [0, 2, 3, 1, 4]) # B, H, W, N, C
cor_prob = tf.reshape(cor_prob, [B, H, W, -1]) # B, H, W, NC

aligned_fea = tf.transpose(aligned_fea, [0, 2, 3, 1, 4])  # [B, H, W, N, C]
tf.print("aligned_fea.shape:", aligned_fea.shape)

aligned_fea = tf.reshape(aligned_fea, [B, H, W, -1]) * cor_prob
tf.print("aligned_fea.shape:", aligned_fea.shape)
```
Look into the comment where `TENSORFLOW BUG` points out:
If `size` is specified by N, which is tf.Tensor, the output will be None. Otherwise, the size is designated by python int, eg. `cor_l = tf.TensorArray(dtype=tf.float32, size=self.nframe)` where self.nframe is pythonic int, everything is fine and the first size of the tensor will be fixed. The output is as follows:
```
emb.shape: TensorShape([2, 3, 180, 320, 32])
cor_l.shape: TensorShape([3, 2, 180, 320])
cor_prob1.shape: TensorShape([2, 3, 180, 320])
cor_prob2.shape: TensorShape([2, 3, 180, 320, 1])
cor_prob3.shape: TensorShape([2, 3, 180, 320, 32])
cor_prob4.shape: TensorShape([2, 180, 320, 3, 32])
cor_prob5.shape: TensorShape([2, 180, 320, 96])
aligned_fea.shape: TensorShape([2, 180, 320, 3, 32])
aligned_fea.shape: TensorShape([2, 180, 320, 96])
```

Thus I am wondering if this is a bug of TensorFlow since the documentation says:
```
size: (optional) int32 scalar `Tensor`: the size of the TensorArray. Required if handle is not provided.
```

Please feel free to contact me if more testing code is required.

**Comment by Saduf2019** [comment]
@Harrypotterrrr 
Please provide with stand alone indented code to replicate the issue or if possible share a colab gist with the error reported.

**Comment by Harrypotterrrr** [comment]
@Saduf2019 I have created sample code to reproduce this bug, and I found the bug occurs only when deploying the model to multi GPUs: 
``` python
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
os.environ['CUDA_VISIBLE_DEVICES'] = '0, 1'
import tensorflow as tf

class TestModel(tf.keras.Model):

    def __init__(self, N):
        super(TestModel, self).__init__()
        self.tAtt_1 = tf.keras.layers.Conv2D(4, (3, 3), (1, 1), "same")
        self.tAtt_2 = tf.keras.layers.Conv2D(4, (3, 3), (1, 1), "same")
        self.nframes = N
        self.center = self.nframes // 2

    def __call__(self, aligned_fea):

        aligned_fea_shape = tf.shape(aligned_fea) # B, N, H, W, C
        B = aligned_fea_shape[0]
        N = aligned_fea_shape[1]
        H = aligned_fea_shape[2]
        W = aligned_fea_shape[3]
        C = aligned_fea_shape[4]

        # for i in range(self.nframe):
        #     aligned_fea = aligned_fea.write(i, x)
        #     tf.print("alienged_fea:", aligned_fea.size())

        emb_ref = self.tAtt_1(aligned_fea[:, self.center, :, :, :])  # B, H, W, C
        emb = tf.reshape(aligned_fea, [-1, H, W, C])  # BN, H, W, C
        emb = self.tAtt_2(emb)
        emb = tf.reshape(emb, [B, N, H, W, -1])

        cor_l = tf.TensorArray(dtype=tf.float32, size=N) # TENSORFLOW BUG HERE. REPLACE N with self.nframes, everything will be OK

        def cond(i, N, input, arr):
            return tf.less(i, N)

        def body(i, N, input, arr):
            emb_nbr = input[:, i, :, :, :]
            cor_tmp = tf.reduce_sum(emb_nbr * emb_ref, axis=3)  # B, H, W
            arr = arr.write(i, cor_tmp)
            i = tf.add(i, 1)
            return i, N, input, arr

        _, _, _, cor_l = tf.while_loop(cond, body, [0, N, emb, cor_l])  # N * (B, H, W)

        tf.print("aliged_fea shape:", cor_l.size())

        t = cor_l.stack()
        tf.print("Stack tensor shape:", t.shape)

        return t


gpu_list = [f"/gpu:{i}" for i in range(2)]
mirrored_strategy = tf.distribute.MirroredStrategy(devices=gpu_list, cross_device_ops=tf.distribute.NcclAllReduce())
nframes = 5

def train_step(model, x):
    output = model(x)

@tf.function
def multigpu_train_step(model, x):
    mirrored_strategy.run(train_step, args=(model, x))

values = tf.random.normal([16,5,32,32,3])
sample_dataset = tf.data.Dataset.from_tensor_slices(values)
sample_dataset = sample_dataset.batch(4)
with mirrored_strategy.scope():
    model = TestModel(nframes)
    sample_dataset = mirrored_strategy.experimental_distribute_dataset(sample_dataset)
    for x in sample_dataset:
        multigpu_train_step(model, x)
```
This is part of the attention implementation, so just ignore the meaning of the code.

**Comment by nikitamaia** [comment]
Hi @Harrypotterrrr, you mentioned that you were only able to repro this with multiple GPUs? I'm seeing the the following output even with a CPU runtime in colab.

```
aliged_fea shape: 5
Stack tensor shape: TensorShape([None, 4, 32, 32])
aliged_fea shape: 5
Stack tensor shape: TensorShape([None, 4, 32, 32])
aliged_fea shape: 5
Stack tensor shape: TensorShape([None, 4, 32, 32])
aliged_fea shape: 5
Stack tensor shape: TensorShape([None, 4, 32, 32])
```

If I comment out tf.function then I see the correct size and not `None`. Without `tf.function`, N is an `EagerTensor` so I think that's why it works okay to pass in as the size. However, with tf.function in graph mode, N is a graph tensor, resulting in a None shape.

**Comment by Harrypotterrrr** [comment]
@nikitamaia Hi, Appreciate your reply! I use the same code as above mentioned and just set a environment variable as`os.environ['CUDA_VISIBLE_DEVICES'] = '-1'`, which I think tensorflow will only use CPU. The output could identify the first dimension of the tensor:
```
aliged_fea shape: 5
Stack tensor shape: TensorShape([5, 2, 32, 32])
aliged_fea shape: 5
Stack tensor shape: TensorShape([5, 2, 32, 32])
WARNING:tensorflow:From /home/lz/anaconda3/envs/tf2/lib/python3.8/site-packages/tensorflow/python/ops/summary_ops_v2.py:1277: stop (from tensorflow.python.eager.profiler) is deprecated and will be removed after 2020-07-01.
Instructions for updating:
use `tf.profiler.experimental.stop` instead.
```
My version of TensorFlow 2 and other settings of the system is shown in the first block of this issue.
Could you please refer to another issue #43698 I put forward one month ago. It is still a problem related to `TensorArray`

**Comment by Harrypotterrrr** [comment]
Moreover, I am always looking for a good way to dynamically stack or concatenate some tensors together in an efficient way. (The intuition of this kind of operation is to combine several temporal features together to fid to the next layer of the network). I use Tensorboard Profiler to analyze the runtime of each step during the network forwarding, and it points out that the step such as `tf.stack` consumes extremely large amount of time compared to convolution. So could you give me some suggestions on this kind of operations so that I could do it more efficiently?

**Comment by nikitamaia** [comment]
Just trying to make sure we isolate where the issue is first. Please [see this gist](https://colab.research.google.com/gist/nikitamaia/544c15416abf576acce59d95fd8abd14/untitled14.ipynb), I am using the default CPU runtime and also the default distribution strategy. Given these setting I'm still seeing the None first dimension. Please let me know if I'm missing something.

**Comment by Harrypotterrrr** [comment]
There is no missing. The gist is complete

**Comment by mdanatg** [comment]
This is expected, partly due to a known and admittedly surprising behavior of `tf.shape`. `tf.shape` always returns a `Tensor`, even when the shape is statically known.

Note that passing a Tensor as `size` argument to `TensorArray` indicates that the size is dynamic and not statically known. Since the shape of the stacked result represents the statically known value, it is unknown when the original `size` was a Tensor.

The simplest workaround is to use `N = aligned_fea.shape[1].value`. That will only work if the shape of `aligned_fea` is known, but I believe that's the case? At any rate, you could also handle dynamic shapes with something like this:

```
N = aligned_fea.shape[1]
if N is None:
  # Dynamc shape, revert to tf.shape; N will be a Tensor
  N = tf.shape(aligned_fea)[1]
# Static shape, N is a Python int
```

**Comment by Harrypotterrrr** [comment]
@mdanatg Thanks for your suggestion. I knew it could be solved by recording the shape of the tensor before the `TensorArray` loop, and after performing the `stack` operation, `reshape` could deal with the `None` problem well. However, it is very confusing for the user to get such kind of Tensor with `None` at the first dimension.
Moreover, what I want to do is more `pythonic` using TF2. Look at the following code:
```
cor_l = []
for i in range(self.nframes):
    emb_nbr = emb[:, i, :, :, :]
    cor_tmp = tf.reduce_sum(emb_nbr * emb_ref, axis=3)  # B, H, W
    cor_l.append(cor_tmp)
cor_l = tf.stack(cor_l)  # N, B, H, W
```
In Autograph mode, which means the training loop is in the decorator of `@tf.function`, the user can not iteratively operates the tensor in the above way, which is much more intuitive and pythonic and Pytorch supports.
I am also using TF Profiler to test if `TensorArray` is the best way to deal with such loop operations in an efficient way, while the result shows that the running time is exactly right limited by this `TensorArray stack` step. The reference issue has been pushed to [here](https://github.com/tensorflow/tensorflow/issues/44118)
This problem has troubled me for a long time. I could make my total repository public to you if you are interested in the bug/tricky problem I pointed out. The coding work is with another Googler working in Mountain View.

**Comment by mdanatg** [comment]
@Harrypotterrrr I agree, and your input helps push toward resolving these issues sooner.

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tensorflow 2.5, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/6ddec09e2911381c8e8f04c7659bf56b/44073.ipynb). Thanks!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
