### ISSUE TITLE
CUDNN_STATUS_INTERNAL_ERROR with MirroredStrategy under graph mode when using tf.summary

### ISSUE THREAD

**Issue by ZhixinLai** [tensorflow/tensorflow#44072]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian GNU/Linux 9
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):2.3.1
- Python version:3.7.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):6.3.0
- CUDA/cuDNN version: CUDA Version: 10.1 
- GPU model and memory: Tesla T4 * 2

**Describe the current behavior**
**When I remove the “tf.summary.write(tag="prediction_" + key, tensor=prediction_concat, step=batch)”, it works well without error.**

**But With “tf.summary.write(tag="prediction_" + key, tensor=prediction_concat, step=batch)”.** It has the error: 
tensorflow.python.framework.errors_impl.UnknownError: 3 root error(s) found.
  (0) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node while/body/_17/while/StatefulPartitionedCall/replica_1/conv2d_1/Conv2D}}]]
         [[DeleteIterator/_102]]
  (1) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node while/body/_17/while/StatefulPartitionedCall/replica_1/conv2d_1/Conv2D}}]]
  (2) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node while/body/_17/while/StatefulPartitionedCall/replica_1/conv2d_1/Conv2D}}]]
         [[while/body/_17/while/StatefulPartitionedCall/replica_1/conv2d_1/BiasAdd/_109]]
0 successful operations.

**Describe the expected behavior**
in the infer() function, the result from serving func will be written as tfevents by tf.summary.

**Standalone code to reproduce the issue**

```
import tensorflow as tf  
from tensorflow.keras import layers  

class Evaluation:

    def __init__(self, strategy=None):  
        self.strategy = strategy
        H, W, C = 10, 10, 3
        imgs = tf.zeros([8, H, W, C])
        self.dataset = tf.data.Dataset.from_tensor_slices(imgs)
        self.dataset = self.dataset.batch(4)
        self.dataset = self.strategy.experimental_distribute_dataset(self.dataset)
        with self.strategy.scope():
            self.conv1 = layers.Conv2D(32, (4, 4), strides=(2, 2), padding='same')
            self.conv2 = layers.Conv2D(32, (4, 4), strides=(2, 2), padding='same')

    @tf.function
    def serving(self, img):
        prediction1 = self.conv1(img)
        prediction2 = self.conv2(img)
        return {
            'pre1': prediction1,
            'pre2': prediction2,
        }

    @tf.function
    def infer(self, serve_summary_writer, key_list):
        with serve_summary_writer.as_default():
            batch = tf.cast(0, tf.int64)
            for img in self.dataset:
                prediction_perReplica = strategy.run(self.serving, args=(img,))
                tf.print("prediction_perReplica:", prediction_perReplica)
                for key in key_list:
                    prediction_tensor = prediction_perReplica[key].values
                    prediction_concat = tf.concat(prediction_tensor, axis = 0)
                    tf.summary.write(tag="prediction_" + key, tensor=prediction_concat, step=batch)
                batch += 1
                
    def eval(self):
        serve_summary_writer = tf.summary.create_file_writer('tmp', max_queue=100000, flush_millis=100000)
        key_list = ["pre1", "pre2"]
        self.infer(serve_summary_writer, key_list)
        serve_summary_writer.close()
        tf.io.gfile.rmtree('tmp')  

if __name__ == "__main__":

    strategy = tf.distribute.MirroredStrategy()
    e = Evaluation(strategy)   
    e.eval()
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
2020-10-16 04:24:03.428115: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-10-16 04:24:04.441402: E tensorflow/stream_executor/cuda/cuda_dnn.cc:328] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-10-16 04:24:05.457372: E tensorflow/stream_executor/cuda/cuda_dnn.cc:328] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-10-16 04:24:05.476782: E tensorflow/stream_executor/cuda/cuda_dnn.cc:328] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-10-16 04:24:05.489398: E tensorflow/stream_executor/cuda/cuda_dnn.cc:328] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-10-16 04:24:05.491341: E tensorflow/stream_executor/cuda/cuda_dnn.cc:328] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-10-16 04:24:05.495273: E tensorflow/stream_executor/cuda/cuda_dnn.cc:328] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-10-16 04:24:05.497372: E tensorflow/stream_executor/cuda/cuda_dnn.cc:328] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-10-16 04:24:05.501205: E tensorflow/stream_executor/cuda/cuda_dnn.cc:328] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "test.py", line 53, in <module>
    e.eval()
  File "test.py", line 41, in eval
    self.infer(serve_summary_writer, key_list)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 846, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError: 3 root error(s) found.
  (0) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node while/body/_17/while/StatefulPartitionedCall/replica_1/conv2d_1/Conv2D}}]]
         [[DeleteIterator/_102]]
  (1) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node while/body/_17/while/StatefulPartitionedCall/replica_1/conv2d_1/Conv2D}}]]
  (2) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node while/body/_17/while/StatefulPartitionedCall/replica_1/conv2d_1/Conv2D}}]]
         [[while/body/_17/while/StatefulPartitionedCall/replica_1/conv2d_1/BiasAdd/_109]]
0 successful operations.
0 derived errors ignored. [Op:__inference_infer_436]

Function call stack:
infer -> infer -> infer

**Comment by ethanyanjiali** [comment]
@ymodak any insights for this issue? ran into a same issue.

**Comment by nikitamaia** [comment]
Hi @ZhixinLai, I was able to reproduce this issue on GCP with two T4 GPUs. While I'm not quite sure what the problem here is, it's always a good idea to make sure your code works first without distribution before adding MirroredStrategy. I replaced the line `strategy = tf.distribute.MirroredStrategy()` with `strategy = tf.distribute.get_strategy()`, which will run your code with the default strategy (ie no distribution). I'm seeing a different error now:

```
prediction_tensor = prediction_perReplica[key].values
AttributeError: 'Tensor' object has no attribute 'values'
```

Try this out and let me know if this helps you debug.

**Comment by ZhixinLai** [comment]
> Hi @ZhixinLai, I was able to reproduce this issue on GCP with two T4 GPUs. While I'm not quite sure what the problem here is, it's always a good idea to make sure your code works first without distribution before adding MirroredStrategy. I replaced the line `strategy = tf.distribute.MirroredStrategy()` with `strategy = tf.distribute.get_strategy()`, which will run your code with the default strategy (ie no distribution). I'm seeing a different error now:
> 
> ```
> prediction_tensor = prediction_perReplica[key].values
> AttributeError: 'Tensor' object has no attribute 'values'
> ```
> 
> Try this out and let me know if this helps you debug.

Thanks for your help. With tf.distribute.MirroredStrategy(), I want to get the result from different devices, and the return result is perReplica tensor type, which is similar to a dict. In order to get the values, I use the .values. I got the idea from the discussion:
https://stackoverflow.com/questions/57549448/how-to-convert-perreplica-to-tensor

You are right, in order to make it run successfully with single GPU, we'd better write like:
if strategy.num_replicas_in_sync > 1:
    predicition_tensors = prediction_perReplica[key].values
else:
    predicition_tensors = prediction_perReplica[key]

But the code needs to be run with multi GPUs eventually, and thus we still need tf.distribute.MirroredStrategy() and get value from perReplica tensor with .values.

**Comment by nikitamaia** [comment]
Ah okay. It sounds like what you're looking for is `gather` ? This has been added to nightly. Please [have a look at the nightly docs](https://www.tensorflow.org/api_docs/python/tf/distribute/Strategy?version=nightly#gather) and examples for `tf.distribute.Strategy.gather` and let me know if this achieves the desired functionally.

**Comment by nikitamaia** [comment]
Hi @ZhixinLai, I'm taking a second look at this code and I am able to run it without error. I ran it with 2.3 using two T4s, and also tried running in nightly. Are you still facing problems? Have you tried running in nightly?
