### ISSUE TITLE
<tf.Operation 'PrintV2_2' type=PrintV2>

### ISSUE THREAD

**Issue by StudentUsingGithup** [tensorflow/tensorflow#44087]
i can NOT run this code!
what is the solution?
```
@tf.function
def squaredDiff(x,y):
    linearRegressionModel(x)
    return tf.square(LinearRegressionModel -y )

@tf.function
def totalLoss(x,y):
    return tf.reduce_sum(squaredDiff(x,y))

tf.print(totalLoss([0,1,2,3,4,5] , [9,7,5,3,1,-1]))
```
the output:
`<tf.Operation 'PrintV2_2' type=PrintV2>`

**Comment by maximus12793** [comment]
You need to enable eager execution. This is printing the tensor op.

https://www.tensorflow.org/guide/eager

**Comment by ravikyram** [comment]
@StudentUsingGithup 

I have tried in colab with TF version 2.3 and i am seeing the error message (`NameError: name 'linearRegressionModel' is not defined`).
Please, share the complete code snippet with supporting files to reproduce the issue in our environment.

As @maximus12793  suggested, please enable eager execution and see if the issue still persists. Thanks!
