### ISSUE TITLE
ValueError: Failed to parse the model: pybind11::init(): factory function returned nullptr

### ISSUE THREAD

**Issue by Rariusz** [tensorflow/tensorflow#44091]
### System information
-   **OS Platform and Distribution  - Linux Ubuntu 20.04 LTS, 64bit**:
-   **TensorFlow installed from conda**:
-   **TensorFlow version 2.2.0**:
-   **Python version 3.8.5**:
-   **GCC/Compiler version 9.3.0**:
-   **CUDA/cuDNN version 11.0**:
-   **GPU model and memory GTX 1080, 12GB**:

**Command to export model**
```
python export_tflite_graph_tf2.py --pipeline_config_path trening_demo/pre-trained-models/ssd_resnet50_v1_fpn_1024x1024_coco17_tpu-8/pipeline.config \ 
--trained_checkpoint_dir trening_demo/models/my_ssd_resnet50_v1_fpn_1024x1024_coco17_tpu-8/ \
--output_directory trening_demo/exported-models-tflite/ex_my_ssd_resnet50_v1_fpn_1024x1024_coco17_tpu-8
```

**Command used to run the converter**

```
import tensorflow as tf
import importlib.util
import multiprocessing

def representative_data_gen():
  dataset_list = tf.data.Dataset.list_files ('/content/model_temp/ed/*')
  for i in range(100):
    image = next(iter(dataset_list))
    image = tf.io.read_file(image)
    image = tf.io.decode_jpeg(image, channels=3)
    image = tf.image.resize(image, [1024, 1024])
    image = tf.cast(image / 255., tf.float32)
    image = tf.expand_dims(image, 0)
    yield [image]

converter = tf.lite.TFLiteConverter.from_saved_model('/content/model_temp/exported-models-tflite/ex_my_ssd_resnet50_v1_fpn_1024x1024_coco17_tpu-8/saved_model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
converter.representative_dataset = representative_data_gen


tflite_model = converter.convert()
with open('/content/model_temp/c-tflite/model.tflite', 'wb') as f:
  f.write(tflite_model)

len(tflite_model)
```
In the above function I am using **decode_jpeg** however, my photos have the extension *** .jpg.** I assume it doesn't matter

**The output from the converter invocation**

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/optimize/calibrator.py in __init__(self, model_content)
     51       self._calibrator = (
---> 52           _calibration_wrapper.CalibrationWrapper(model_content))
     53     except Exception as e:

TypeError: pybind11::init(): factory function returned nullptr

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
4 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/optimize/calibrator.py in __init__(self, model_content)
     52           _calibration_wrapper.CalibrationWrapper(model_content))
     53     except Exception as e:
---> 54       raise ValueError("Failed to parse the model: %s." % e)
     55     if not self._calibrator:
     56       raise ValueError("Failed to parse the model.")

ValueError: Failed to parse the model: pybind11::init(): factory function returned nullptr.
```

**Link to the saved model** -- ex_my_ssd_resnet50_v1_fpn_1024x1024_coco17_tpu-8
[https://drive.google.com/drive/folders/1Hz4BdMw2xg5t1rRMhl0smiz17GnL-Pz5?usp=sharing](url)

I read that this may be a problem with the TensorRT version. Right? I use google colab.

**Comment by amahendrakar** [comment]
@Rariusz,
I do not have access to the link you have provided. Could you please provide the required permissions to view the files. 

Also in order to reproduce the issue reported here, please provide the contents of the directory `/content/model_temp/ed/`. Thanks!

**Comment by Rariusz** [comment]
@amahendrakar Thank you for your answers !
Link for model (ex_my_ssd_resnet50_v1_fpn_1024x1024_coco17_tpu-8) that I need to convert to TFLite:
https://drive.google.com/drive/folders/1Hz4BdMw2xg5t1rRMhl0smiz17GnL-Pz5?usp=sharing

Contents of the directory ```/content/model_temp/ed/ ``` 
https://drive.google.com/drive/folders/1y5AIh86wdA8ZoVxQBuOSh8ZbGGdAmIXl?usp=sharing

These are sample photos. Currently, I am mainly interested in solving the problem of converting the model to tflite.

Thank you for your help and time !!!

**Comment by amahendrakar** [comment]
@Rariusz,
I was able to run the code without any issues using TF v2.2, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/cba1317f936aafe5590119f410dd6791/44091-2-2.ipynb). Thanks!

**Comment by amahendrakar** [comment]
Was able to reproduce the error with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/c00131d159d591ade4e8290c7ae5fee8/44091.ipynb#scrollTo=IVtxr4FUI5vo).

However, on running the code with [TF-nightly](https://colab.research.google.com/gist/amahendrakar/394d9b7ba2fb7d04b55deb0d99e405da/44091-tf-nightly.ipynb#scrollTo=IVtxr4FUI5vo), the error changes to `ValueError: Model input is not quantized`. Please find the attached gist. Thanks!

**Comment by Rariusz** [comment]
@amahendrakar 
Thank you for your help and time !!!. I run code with and the solution was to install tensorflow==2.2 **but, now I'm back to my starting point.** Please see this issue: https://github.com/tensorflow/tensorflow/issues/43959

As You will see the problem is that model is reduced to 432 bytes and that creates a problem. Thanks!

**Comment by Rariusz** [comment]
@amahendrakar 
Following my previous comment, if you have an idea of how to solve my problem or a suggestion that I can use, I will be very grateful!.

**Comment by ymodak** [comment]
@Rariusz What happens if you don't perform any optimizations on the model and convert without quantization?

**Comment by Rariusz** [comment]
@ymodak Following this issue https://github.com/tensorflow/tensorflow/issues/44561  without quantization everything work. If I run the detector for ```ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8``` the result is 
![prediction](https://user-images.githubusercontent.com/28406311/98166790-44c5ed00-1ee8-11eb-9565-b16ddef58339.jpg)

After running this command:
````
!python object_detection/export_tflite_graph_tf2.py \
    --pipeline_config_path "/content/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8/pipeline.config" \
    --trained_checkpoint_dir "/content/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8/checkpoint"\
    --output_directory "/content/tflite_graph"
``` 
The results is the same.  Now I will try to run this model on google coral. Then I will try to run this model for my data set. But there will be problems for sure... 
I wonder so far why the image has a different color in the result ..
