### ISSUE TITLE
How to remove unused operators from tensorflowlite_c.so to reduce it's size?

### ISSUE THREAD

**Issue by MrSherish** [tensorflow/tensorflow#44090]
As in the title. How can one remove unused operators (automatically or manually) in the build of C API library? There's nice process regarding Select Ops, where one has to pass models during the build, but there isn't anything similar present for .so. There is section about .aar (https://www.tensorflow.org/lite/guide/reduce_binary_size), but it's not my use case.

**Comment by yyoon** [comment]
@MrSherish If you're comfortable writing your own `BUILD` files, you could use the `tflite_custom_cc_library` rule to create a library with only the op kernels used for your provided model file.

See: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/build_def.bzl#L772

@thaink Would there be a more convenient way?

**Comment by thaink** [comment]
If you want to use the C++ API then extracting the aar file you will have .so file inside it.

For C API, I am afraid the rule is not working for the C api yet.
For C api, currently you need to create a new custom TfLiteInterpreter using TfLiteInterpreterCreateWithSelectedOps in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/c/c_api_experimental.h

**Comment by MrSherish** [comment]
Right now my model is not using Select Ops at all, so I do not need C++ API at all, or experimental API from C. What I am trying to achieve is reducing size of library in C, removing unused built-in ops.

**Comment by thaink** [comment]
I am working on a script to do so.
At the moment you can try removing unused op in tensorflow/lite/kernels/register.cc
and rebuild the tensorflow/lite/experimental/ios:TensorFlowLiteC_framework

**Comment by jdduke** [comment]
This should be possible now, @thaink can you provide a link to the docs/guidance?

**Comment by thaink** [comment]
You can follow the guide in https://www.tensorflow.org/lite/guide/reduce_binary_size#advanced_usages_build_custom_cc_shared_libraries
to reduce the binary size.

**Comment by mohantym** [comment]
Hi @MrSherish !

We are checking to see whether you still need help in this issue . Have you tried the Selective build through bazel as suggested in the above[ thread.](https://github.com/tensorflow/tensorflow/issues/44090#issuecomment-909721081)

Thank you!

**Comment by MrSherish** [comment]
Reopening the issue, would the above be possible within CMake? I'm not able to utilize Bazel.
