### ISSUE TITLE
max_images defaults to 3 images instead of batch_size in tf.image_summary

### ISSUE THREAD

**Issue by dan-silver** [tensorflow/tensorflow#441]
Even though the default value for the max_images parameter in tf.image_summary is None, a maximum of 3 images are displayed by default.

It looks like this is [by design](https://github.com/tensorflow/tensorflow/blob/a5d8217c4ed90041bea2616c14a8ddcf11ec8c03/tensorflow/core/ops/ops.pbtxt#L2993), but I can't find it mentioned in the documentation.  Should a note be added to the docs, or possibly the default value changed to 3 instead of None?

```python
import tensorflow as tf

images = tf.Variable(tf.truncated_normal([10, 48, 48, 1]))

tf.image_summary("max_images_bug_no_param", images) # 3 images displayed

tf.image_summary("max_images_bug_none_param", images, max_images=None) # 3 images displayed

tf.image_summary("max_images_bug_100_param", images, max_images=100) # 10 images displayed

with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    summary_op = tf.merge_all_summaries()
    writer = tf.train.SummaryWriter('max_images_bug')
    summary_str = sess.run(summary_op)
    writer.add_summary(summary_str, 0)
```

**Comment by girving** [comment]
Fixed.  You're correct that the default in Python should be `3` instead of `None` so that it shows up in the docs.  Thanks!
