### ISSUE TITLE
Add tflite_runtime 2.3.1 wheels to Python quickstart

### ISSUE THREAD

**Issue by TylerADavis** [tensorflow/tensorflow#44100]
## URL(s) with the issue: 
https://www.tensorflow.org/lite/guide/python

## Description of issue (what needs changing): 
The [TensorFlow Lite Python quickstart guide](https://www.tensorflow.org/lite/guide/python) currently only contains links to prebuilt wheels for tflite_runtime 2.1.0. TensorFlow 2.1.0 is missing several new features and key [security fixes](https://github.com/tensorflow/tensorflow/releases/tag/v2.3.1) that would be valuable for developers. As such, would it be possible to update this page with download links for a fresh (>= 2.3.1) version of TensorFlow? Updating the wheels to a newer version should not require any other changes to the quickstart guide.

The source for this page is located at https://github.com/tensorflow/tensorflow/blob/1e87951747af11b61206dd19f9363b309fc8e6f5/tensorflow/lite/g3doc/guide/python.md .

### Submit a pull request?

I don't have the ability to host wheels at https://dl.google.com, so I believe a TensorFlower will need to build all the wheels and then upload them. Public instructions for building the wheels are hosted at https://github.com/tensorflow/tensorflow/blob/f1a3160b04dda71d50130d6a03727486bed2f5e1/tensorflow/lite/tools/pip_package/README.md

**Comment by TylerADavis** [comment]
As TensorFlow has [announced](https://groups.google.com/a/tensorflow.org/forum/#!topic/announce/Up9cjJY_KYw) it is dropping future support for Python 3.5, updating this page will likely also entail dropping the Python 3.5 wheels.

**Comment by terryheo** [comment]
There is a team who is working on this. It'll take some time.

BTW, can't you just use tf.lite package in TF PIP?
https://www.tensorflow.org/api_docs/python/tf/lite

What's the reason you need tflite_runtime package?

**Comment by TylerADavis** [comment]
Hi Terry,

It's great to hear that the team is working on this. I worked around my issue by compiling copies of both the tflite_runtime and full TensorFlow from source, but a prebuilt `.whl` is definitely more convenient.

As for your question, there were two main reasons I was looking for a `tflite_runtime` package.

1. I was looking to do inference on a Raspberry Pi 4B running 64-bit Ubuntu, and while there isn't a [prebuilt TensorFlow wheel for AArch64](https://www.tensorflow.org/install/pip#package-location), there is a prebuilt (2.1.0) tflite_runtime wheel
2. I was interested in minimizing memory consumption, and I was under the (potentially flawed) assumption that accessing TF Lite as part of the full package would incur higher memory usage than using the stripped down runtime package.

The reason I wanted a 2.3.X version of TF Lite was so that I could configure the number of threads the interpreter is using via the Python API (https://github.com/tensorflow/tensorflow/pull/25748).

Thank you for your help, I really appreciate it.

**Comment by ymodak** [comment]
tflite_runtime 2.5 wheels are available https://github.com/google-coral/pycoral/releases
