### ISSUE TITLE
TFLite Interpreter returns different results when in Python on desktop and when in Java on Android mobile device

### ISSUE THREAD

**Issue by peidaqi** [tensorflow/tensorflow#44108]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04, Android 9 PKQ1.190118.0 01
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Xiaomi MIX 2
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.8.5
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
Loading the same TFLite model on my desktop using the following command:

```interpreter = tf.lite.Interpreter(model_path='./model.tflite') 
interpreter.allocate_tensors() 
input_details = interpreter.get_input_details() 
output_details = interpreter.get_output_details() 
interpreter.set_tensor(input_details[0]['index'], img_data.reshape(1, 28, 28, 1).astype(np.float32)) 
interpreter.invoke() 
output_data = interpreter.get_tensor(output_details[0]['index'])
```

Returns the correct results in Float32 in output_data, something like [0.345, 0.655]. However, if I load the same model on my device using:

```MappedByteBuffer tfliteModel = FileUtil.loadMappedFile(this, "model.tflite");
Interpreter tflite = new Interpreter(tfliteModel);
TensorBuffer probabilityBuffer = TensorBuffer.createFixedSize(new int[]{1, 2}, DataType.FLOAT32);
tflite.run(img_data, probabilityBuffer.getBuffer());
float[] results = probabilityBuffer.getFloatArray();
```

Always returns a very strange result of [1.0, 0.0]

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@peidaqi,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!
