### ISSUE TITLE
Dealing with `from tensorflow.contrib import ...` in  tf_upgrade_v2 

### ISSUE THREAD

**Issue by camelia-c** [tensorflow/tensorflow#44103]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):2.3.0
- Are you willing to contribute it (Yes/No):No

**Describe the feature and the current behavior/state.**
I ran into cases not covered by the `tf_upgrade_v2` tool yet, namely certain TF1 models in the zoo (https://github.com/tensorflow/models/tree/master/research)  that import from `tensorflow.contrib` - which was deprecated in TF2

I created a small example to illustrate the current behaviour of  the `tf_upgrade_v2` tool on these:

```
%%bash

cat > /tmp/example.py << EOL
try:
    from tensorflow.contrib import quantize as contrib_quantize
    from tensorflow.contrib import framework as contrib_framework
    from tensorflow.contrib import slim as contrib_slim
    from tensorflow.contrib.slim.nets import resnet_utils
    from tensorflow.contrib import layers as contrib_layers
    from tensorflow.contrib import tfprof as contrib_tfprof
    from tensorflow.contrib import training as contrib_training
    from tensorflow.contrib import metrics as contrib_metrics
except Exception as e:
    print(type(e).__name__, ":", e)

from tensorflow_addons import metrics as addons_metrics

def demo_deprecated():
    print(dir(contrib_metrics))

def demo_ok():
    print(dir(addons_metrics))


if __name__ == '__main__':
    demo_ok()
    print("===========================")
    demo_deprecated()
EOL
```

Then, according to https://www.tensorflow.org/guide/upgrade, we do:

```
!tf_upgrade_v2 \
  --infile /tmp/example.py \
  --outfile /tmp/example_v2.py
```

The report file doesn't contain any warning about the deprecated modules:

```!cat report.txt```

```
TensorFlow 2.0 Upgrade Script
-----------------------------
Converted 1 files
Detected 0 issues that require attention
--------------------------------------------------------------------------------
================================================================================
Detailed log follows:

================================================================================
--------------------------------------------------------------------------------
Processing file '/tmp/example.py'
 outputting to '/tmp/example_v2.py'
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
```

The two files are identical:

```!diff -u /tmp/example.py /tmp/example_v2.py```

However, unsurprisingly, the ModuleNotFoundError is thrown when we execute:

```!python /tmp/example_v2.py```

```
2020-10-16 19:52:37.022043: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
ModuleNotFoundError : No module named 'tensorflow.contrib'
['CohenKappa', 'F1Score', 'FBetaScore', 'HammingLoss', 'MatthewsCorrelationCoefficient',  ... , 'utils']
===========================
Traceback (most recent call last):
  File "/tmp/example_v2.py", line 25, in <module>
    demo_deprecated()
  File "/tmp/example_v2.py", line 16, in demo_deprecated
    print(dir(contrib_metrics))
NameError: name 'contrib_metrics' is not defined
```

It would be nice to see the `tf_upgrade_v2` tool (more precisely: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/compatibility/tf_upgrade_v2_main.py) updated to treat these cases `from tensorflow.contrib import ...` .  

Moreover, it would be great to have the `tf_upgrade_v2` tool extended so that it incorporates in the migration process (or at least as guidance in the report.txt) the successors of the modules in TF1 `tensorflow.contrib` , such as the `tensorflow_addons` (https://github.com/tensorflow/addons), `tf_slim` (https://github.com/tensorflow/models/tree/master/research/slim), etc.  

**Will this change the current api? How?**
No API changes are necessary.

**Who will benefit with this feature?**
Everyone who tries to migrate TF1 models to TF2, when the files contain imports from `tensorflow.contrib`

**Any Other info.**
-

Many thanks in advance,
Camelia

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/ddd1f9f2ccafdedac21965c7ca314be5/44103.ipynb). Thanks!

**Comment by annarev** [comment]
Thank you for filing the issue and sorry for delay!
We should print an error/warning on `from tensorflow.contrib ...` import is used.
Note that the upgrade documentation (https://www.tensorflow.org/guide/upgrade) has a note saying that `tf.contrib` references need to be updated manually and proposes to check https://github.com/tensorflow/addons.

**Comment by jvishnuvardhan** [comment]
I think this is resolved.  As mentioned above, we need to update `contrib` manually.

> Because of TensorFlow 2.x module deprecations (for example, tf.flags and tf.contrib), some changes can not be worked around by switching to compat.v1. Upgrading this code may require using an additional library (for example, absl.flags) or switching to a package in tensorflow/addons.

Please check the updated guide here https://www.tensorflow.org/guide/upgrade

I am closing this issue as this was resolved. Thanks!

**Comment by Wuxinxiaoshifu** [comment]
> I think this is resolved. As mentioned above, we need to update `contrib` manually.
> 
> > Because of TensorFlow 2.x module deprecations (for example, tf.flags and tf.contrib), some changes can not be worked around by switching to compat.v1. Upgrading this code may require using an additional library (for example, absl.flags) or switching to a package in tensorflow/addons.
> 
> Please check the updated guide here https://www.tensorflow.org/guide/upgrade
> 
> I am closing this issue as this was resolved. Thanks!

i don't think this sloved!
can you tell me how to solve tf.contrib,the update guide can't explain how to solve it

**Comment by Wuxinxiaoshifu** [comment]
i don't think this sloved!
can you tell me how to solve tf.contrib,the update guide can't explain how to solve it
