### ISSUE TITLE
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by aradox** [tensorflow/tensorflow#44110]
**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow installed from: binary
- TensorFlow version: 2.2.0
- Python version: 3.8.6
- Installed using: pip
- CUDA/cuDNN version: 10.1/ 7.6.5
- GPU model and memory: Nvidia Geforce GTX 1050i TI

**Describe the problem**
When i import tensorflow like normal it throw an error, i have done the same thing on my laptop and there it all works fine, ik have the exact same code and followed the exact same steps, but on my computer it just fails. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
- open a python file;
- import tensorflow as tf
- error occurs

Traceback (most recent call last):
  File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 29, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 25, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_main_tf2.py", line 31, in <module>
    import tensorflow.compat.v2 as tf
  File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 29, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 25, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

**Comment by aradox** [comment]
I have seen this auto response on other issues, I think it has to do with the CPU bot being compatible, why is that? because I have a gpu shouldn't it just run on my CPU?

**Comment by ravikyram** [comment]
@aradox 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).

Please, check Your CPU/Python is on 32 bits?

Please, refer duplicate issue #43130
Thanks!

**Comment by aradox** [comment]
Vendor ID         : GenuineIntel
CPU name          : Intel(R) Core(TM) i5 CPU         660  @ 3.33GHz
Microarchitecture : westmere
Vector instructions supported:
SSE       : Yes
SSE2      : Yes
SSE3      : Yes
SSSE3     : Yes
SSE4.1    : Yes
SSE4.2    : Yes
SSE4a     : --
AVX       : --
AVX2      : --
BMI1      : --
BMI2      : --

The system is a 64bit system. 
I see that my CPU does not allow for AVX instructions. so what can i do now? I already tried to compile from source but this failed after 67 minutes of compiling.

**Comment by ravikyram** [comment]
@aradox 

TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets.
Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.

Apparently, your CPU model does not support AVX instruction sets. You can still use TensorFlow with the alternatives given below:

Try Google Colab to use TensorFlow.
The easiest way to use TF will be to switch to google colab. You get pre-installed latest stable TF version. Also you can use pip install to install any other preferred TF version.
It has an added advantage since you can you easily switch to different hardware accelerators
(cpu, gpu, tpu) as per the task.
All you need is a good internet connection and you are all set.
or else try to build TF from sources by changing CPU optimization flags.

Thanks!

**Comment by sac-ux** [comment]
> **System information**
> 
> * OS Platform and Distribution: Windows 10
> * TensorFlow installed from: binary
> * TensorFlow version: 2.2.0
> * Python version: 3.8.6
> * Installed using: pip
> * CUDA/cuDNN version: 10.1/ 7.6.5
> * GPU model and memory: Nvidia Geforce GTX 1050i TI
> 
> **Describe the problem** When i import tensorflow like normal it throw an error, i have done the same thing on my laptop and there it all works fine, ik have the exact same code and followed the exact same steps, but on my computer it just fails.
> 
> **Provide the exact sequence of commands / steps that you executed before running into the problem**
> 
> * open a python file;
> * import tensorflow as tf
> * error occurs
> 
> Traceback (most recent call last): File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in from tensorflow.python.pywrap_tensorflow_internal import * File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 29, in _pywrap_tensorflow_internal = swig_import_helper() File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 25, in swig_import_helper _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description) File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\imp.py", line 242, in load_module return load_dynamic(name, filename, file) File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\imp.py", line 342, in load_dynamic return _load(spec) ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "model_main_tf2.py", line 31, in import tensorflow.compat.v2 as tf File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow__init__.py", line 41, in from tensorflow.python.tools import module_util as _module_util File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python__init__.py", line 52, in from tensorflow.python import pywrap_tensorflow File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in raise ImportError(msg) ImportError: Traceback (most recent call last): File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in from tensorflow.python.pywrap_tensorflow_internal import * File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 29, in _pywrap_tensorflow_internal = swig_import_helper() File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 25, in swig_import_helper _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description) File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\imp.py", line 242, in load_module return load_dynamic(name, filename, file) File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\imp.py", line 342, in load_dynamic return _load(spec) ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.
> 
> Failed to load the native TensorFlow runtime.

only need for !pip install tensorflow==2.7.0  tensorflow-gpu==2.7.0 --upgrade
to solve hole problem

**Comment by thierryntoh24** [comment]
> **System information**
> 
> * OS Platform and Distribution: Windows 10
> * TensorFlow installed from: binary
> * TensorFlow version: 2.2.0
> * Python version: 3.8.6
> * Installed using: pip
> * CUDA/cuDNN version: 10.1/ 7.6.5
> * GPU model and memory: Nvidia Geforce GTX 1050i TI
> 
> **Describe the problem** When i import tensorflow like normal it throw an error, i have done the same thing on my laptop and there it all works fine, ik have the exact same code and followed the exact same steps, but on my computer it just fails.
> 
> **Provide the exact sequence of commands / steps that you executed before running into the problem**
> 
> * open a python file;
> * import tensorflow as tf
> * error occurs
> 
> Traceback (most recent call last): File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in from tensorflow.python.pywrap_tensorflow_internal import * File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 29, in _pywrap_tensorflow_internal = swig_import_helper() File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 25, in swig_import_helper _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description) File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\imp.py", line 242, in load_module return load_dynamic(name, filename, file) File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\imp.py", line 342, in load_dynamic return _load(spec) ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "model_main_tf2.py", line 31, in import tensorflow.compat.v2 as tf File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow__init__.py", line 41, in from tensorflow.python.tools import module_util as _module_util File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python__init__.py", line 52, in from tensorflow.python import pywrap_tensorflow File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in raise ImportError(msg) ImportError: Traceback (most recent call last): File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in from tensorflow.python.pywrap_tensorflow_internal import * File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 29, in _pywrap_tensorflow_internal = swig_import_helper() File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 25, in swig_import_helper _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description) File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\imp.py", line 242, in load_module return load_dynamic(name, filename, file) File "C:\Users\TastDesktop\AppData\Local\Programs\Python\Python38\lib\imp.py", line 342, in load_dynamic return _load(spec) ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.
> 
> Failed to load the native TensorFlow runtime.

Hey, did you finally get your TF up and running?
I have a similar architecture as you, and running into the same problem.

**Comment by MadamEllaMalala** [comment]
@sac-ux It's 2024 and that line gives: 
"ERROR: Could not find a version that satisfies the requirement tensorflow==2.7.0 (from versions: 2.16.0rc0, 2.16.1)
ERROR: No matching distribution found for tensorflow==2.7.0"

**Comment by SISRO7** [comment]
dll load failed while importing _pywrap_tf2:

**Comment by Fahadxx** [comment]
> @sac-ux It's 2024 and that line gives: "ERROR: Could not find a version that satisfies the requirement tensorflow==2.7.0 (from versions: 2.16.0rc0, 2.16.1) ERROR: No matching distribution found for tensorflow==2.7.0"

same here,,, still looking, please reply to me if you managed to make it work :(
