### ISSUE TITLE
3080 & 3090 coumpute capability 86 degraded performance after some updates

### ISSUE THREAD

**Issue by ibmua** [tensorflow/tensorflow#44116]
This issue is apparent from the difference in performance in NGC containers https://ngc.nvidia.com/catalog/containers/nvidia:tensorflow . For 20.08 se-resnext101 example training performance
```
python nvidia-examples/resnet50v1.5/main.py --arch=se-resnext101-32x4d --batch_size=64  --warmup_steps 200 --data_dir=/hdd/datasets/imagenet/tf/train/ --gpu_memory_fraction 0.95  --precision fp32  --results_dir=/toy/tmp/results_dir/   --mode=training_benchmark   --use_tf_amp --use_xla
```
(have to adapt directories)
on 3080 is around 370-400 img/sec. While on 20.09 container it's more like 115 img/sec. This is also similar for resnet-50 and most likely all other CNN benchmarks. This is not an issue with my setup, it's the same for other folks - you can view discussion at https://www.pugetsystems.com/labs/hpc/RTX3090-TensorFlow-NAMD-and-HPCG-Performance-on-Linux-Preliminary-1902/

**Comment by sanjoy** [comment]
Can you please report this on the [NVIDIA developer forum](https://forums.developer.nvidia.com/c/ai-deep-learning/deep-learning-framework/tensorflow/101)?

CC @nluehr 

We can circle back here if/when this is triaged down to an issue with the TF nightly and/or TF release builds.

**Comment by ibmua** [comment]
3090's performance on 20.10 tf1 ngc container is even 15-20% better than on 20.08, so I guess we can just agree that we should never use 20.08 container because it sucks. I'll later also try to run some tests on 20.10 tf2 and report back.

**Comment by ibmua** [comment]
Ran extensive benchmarks https://fsymbols.com/3080-3090-benchmarks/

**Comment by ibmua** [comment]
(And the performance was pretty inconsistent, you better take a look.)

**Comment by ibmua** [comment]
Retested on 20.11 container. 3080 performance still effed up https://fsymbols.com/3080-3090-benchmarks/

**Comment by sachinprasadhs** [comment]
Could you please test in the latest  `22.01-tf1` https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorflow container and let us know if you are getting good performance. Thanks
