### ISSUE TITLE
TFlite RuntimeError: Model resulted in Nan value during calibration. Please make sure model results in all real-values during inference with provided dataset.Node number 37 (CONV_2D) failed to invoke.

### ISSUE THREAD

**Issue by tu1258** [tensorflow/tensorflow#44114]
I use tf 2.3 and this error occurs when doing full integer quantization.
`RuntimeError: Model resulted in Nan value during calibration. Please make sure model results in all real-values during inference with provided dataset.Node number 37 (CONV_2D) failed to invoke.`

**Code (just a demo how I do quantize and it can't reproduce error)**
```
def representative_dataset_gen():
    for x in validation_fingerprints:
      x = x[np.newaxis,:]
      yield [x]

converter = tf.lite.TFLiteConverter.from_saved_model(flags.train_dir + '/last_model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
# converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS]
converter.allow_custom_ops = True
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
converter.representative_dataset = representative_dataset_gen
last_quant_model = converter.convert()
with open(flags.train_dir + '/quant_last_model.tflite', 'wb') as w:
  w.write(last_quant_model)
```
**Some config**
type(validation_fingerprints): <class 'numpy.ndarray'>
shape(validation_fingerprints): (3093, 16384)
type(x): <class 'numpy.ndarray'>
shape(x): (1,16384)
The model_summary
[model_summary.txt](https://github.com/tensorflow/tensorflow/files/5395787/model_summary.txt)

Can anyone help? Thanks.

**Comment by tu1258** [comment]
@Saduf2019 Do you know how to solve it?

**Comment by Saduf2019** [comment]
@tu1258 
I ran the code shared and face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/8dbdd46c8119ff67d2f7dd0e878a45b8/untitled446.ipynb).

**Comment by tu1258** [comment]
@Saduf2019 I check the gist and don't find it relative to my issue. Could you explain it a bit?

**Comment by Saduf2019** [comment]
@tu1258 
Apologies for the incorrect gist, please find the correct [gist here](https://colab.research.google.com/gist/Saduf2019/5fa92c1e15e768f29a8851a5e2279ef4/untitled446.ipynb).

**Comment by tu1258** [comment]
@Saduf2019 bruh 

> just a demo how I do quantize and it can't reproduce error

I completely understand your workflow(reproduce the error and find another expert to solve it I guess?) and I appreciate that. But reproducing the error may be complicated and the code would be a little hard to trace. Could you just route this issue to that expert?

**Comment by Saduf2019** [comment]
@tu1258 
We will not be able to replicate the issue without stand alone or if possible share a colab gist with the  error reported.

**Comment by tu1258** [comment]
@Saduf2019 
Alright, I finally minimize the code and please take a look! You have to read model and data I attach below tho.

### **Code**
```
import os
import sys
import absl.logging as logging
import numpy as np
import tensorflow.compat.v1 as tf

np.set_printoptions(threshold=sys.maxsize)
tf.reset_default_graph()
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)
tf.keras.backend.set_session(sess)

read_fingerprints = np.loadtxt('./testbench/best/testset_raw.csv.gz', delimiter=',')
# logging.info(type(read_fingerprints))
# logging.info(read_fingerprints.shape)
test_fingerprints = read_fingerprints.reshape(-1,16384).astype(np.float32)
print('type(test_fingerprints):', type(test_fingerprints))
print('shape(test_fingerprints):', test_fingerprints.shape)
# logging.info(type(test_fingerprints))
# logging.info(test_fingerprints.shape)
def representative_dataset_gen():
  for x in test_fingerprints:
    x = x[np.newaxis,:]
    yield [x]

train_dir = 'tcn/kws_7x36_1'

converter = tf.lite.TFLiteConverter.from_saved_model(train_dir + '/best_model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
# converter.target_spec.supported_ops = [tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8]
# converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS]
converter.allow_custom_ops = True
# converter.inference_type = tf.lite.constants.FLOAT
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
converter.representative_dataset = representative_dataset_gen
quant_best_model = converter.convert()
with open(train_dir + '/quant_best_model.tflite', 'wb') as w:
  w.write(quant_best_model)
 
```
The data (correspond to `np.loadtxt('./testbench/best/testset_raw.csv.gz', delimiter=',')`)

The model (correspond to `tf.lite.TFLiteConverter.from_saved_model(train_dir + '/best_model'`)
[best_model.zip](https://github.com/tensorflow/tensorflow/files/5413570/best_model.zip)

It should be able to reproduce now, please take a look ASAP.

**Comment by tu1258** [comment]
In addition, I encounter error `Skipping quantization of tensor because it has fewer than 1024 elements` when just using
```
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS]
converter.allow_custom_ops = True
converter.inference_type = tf.lite.constants.FLOAT
quant_best_model = converter.convert()
```
I have no idea if this is relatable but this may give some clue for you.

**Comment by tu1258** [comment]
@Saduf2019 Please let me know if there is any question?

**Comment by tu1258** [comment]
I think I should quit and close issue and move on due to the late response since this is not my first priority and I wasted too much on it. Thanks for your reply tho.

**Comment by Saduf2019** [comment]
@tu1258 
I ran the code shared and faced a different error which was been analysed, hence the delay, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/4041c638b0bf4484f2aed4377e30c843/untitled450.ipynb).
