### ISSUE TITLE
Tensorflow model inference different than loading weights from checkpoint into equivalent model in keras

### ISSUE THREAD

**Issue by alecda573** [tensorflow/tensorflow#44123]
Python version 3.8.3
Tensorflow 1.14 and 2.0 used
Windows 10
CUDA 10, Cudnn 7.6.5

I can send the variable or checkpoint file if this would be helpful.

I am trying to convert the following tensorflow model to keras so I can upload the weights directly, but I am not getting the correct predictions after I do this can someone tell me if I am making an obvious mistake? 

    class LinearModel(object):
      """ A simple Linear+RELU model """
    
      def __init__(self,
                   linear_size,
                   num_layers,
                   residual,
                   batch_norm,
                   max_norm,
                   batch_size,
                   learning_rate,
                   summaries_dir,
                   predict_14=False,
                   dtype=tf.float32):
        
   
        self.HUMAN_2D_SIZE = 16 * 2
    
        self.HUMAN_3D_SIZE = 14 * 3 if predict_14 else 16 * 3
    
        self.input_size  = self.HUMAN_2D_SIZE
        self.output_size = self.HUMAN_3D_SIZE
    
        self.isTraining = tf.placeholder(tf.bool,name="isTrainingflag")
        self.dropout_keep_prob = tf.placeholder(tf.float32, name="dropout_keep_prob")
    
        # Summary writers for train and test runs
        self.train_writer = tf.summary.FileWriter( os.path.join(summaries_dir, 'train' ))
        self.test_writer  = tf.summary.FileWriter( os.path.join(summaries_dir, 'test' ))
    
        self.linear_size   = linear_size
        self.batch_size    = batch_size
        self.learning_rate = tf.Variable( float(learning_rate), trainable=False, dtype=dtype, name="learning_rate")
        self.global_step   = tf.Variable(0, trainable=False, name="global_step")
        decay_steps = 100000  # empirical
        decay_rate = 0.96     # empirical
        self.learning_rate = tf.train.exponential_decay(self.learning_rate, self.global_step, decay_steps, decay_rate)
    
        # === Transform the inputs ===
        with vs.variable_scope("inputs"):
    
          # in=2d poses, out=3d poses
          enc_in  = tf.placeholder(dtype, shape=[None, self.input_size], name="enc_in")
          dec_out = tf.placeholder(dtype, shape=[None, self.output_size], name="dec_out")
    
          self.encoder_inputs  = enc_in
          self.decoder_outputs = dec_out
    
        # === Create the linear + relu combos ===
        with vs.variable_scope( "linear_model" ):
    
          # === First layer, brings dimensionality up to linear_size ===
          w1 = tf.get_variable( name="w1", initializer=kaiming, shape=[self.HUMAN_2D_SIZE, linear_size], dtype=dtype )
          b1 = tf.get_variable( name="b1", initializer=kaiming, shape=[linear_size], dtype=dtype )
          w1 = tf.clip_by_norm(w1,1) if max_norm else w1
          y3 = tf.matmul( enc_in, w1 ) + b1
    
          if batch_norm:
            y3 = tf.layers.batch_normalization(y3,training=self.isTraining, name="batch_normalization")
          y3 = tf.nn.relu( y3 )
          y3 = tf.nn.dropout( y3, self.dropout_keep_prob )
    
          # === Create multiple bi-linear layers ===
          for idx in range( num_layers ):
            y3 = self.two_linear( y3, linear_size, residual, self.dropout_keep_prob, max_norm, batch_norm, dtype, idx )
    
          # === Last linear layer has HUMAN_3D_SIZE in output ===
          w4 = tf.get_variable( name="w4", initializer=kaiming, shape=[linear_size, self.HUMAN_3D_SIZE], dtype=dtype )
          b4 = tf.get_variable( name="b4", initializer=kaiming, shape=[self.HUMAN_3D_SIZE], dtype=dtype )
          w4 = tf.clip_by_norm(w4,1) if max_norm else w4
          y = tf.matmul(y3, w4) + b4
          # === End linear model ===
    
        # Store the outputs here
        self.outputs = y
        self.loss = tf.reduce_mean(tf.square(y - dec_out))
        self.loss_summary = tf.summary.scalar('loss/loss', self.loss)
    
        # To keep track of the loss in mm
        self.err_mm = tf.placeholder( tf.float32, name="error_mm" )
        self.err_mm_summary = tf.summary.scalar( "loss/error_mm", self.err_mm )
    
        # Gradients and update operation for training the model.
        opt = tf.train.AdamOptimizer( self.learning_rate )
        update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
    
        with tf.control_dependencies(update_ops):
    
          # Update all the trainable parameters
          gradients = opt.compute_gradients(self.loss)
          self.gradients = [[] if i==None else i for i in gradients]
          self.updates = opt.apply_gradients(gradients, global_step=self.global_step)
    
        # Keep track of the learning rate
        self.learning_rate_summary = tf.summary.scalar('learning_rate/learning_rate', self.learning_rate)
    
        # To save the model
        self.saver = tf.train.Saver( tf.global_variables(), max_to_keep=10 )
    
    
      def two_linear( self, xin, linear_size, residual, dropout_keep_prob, max_norm, batch_norm, dtype, idx ):
        """
        Make a bi-linear block with optional residual connection
    
        Returns
          y: the batch after it leaves the block
        """
    
        with vs.variable_scope( "two_linear_"+str(idx) ) as scope:
    
          input_size = int(xin.get_shape()[1])
    
          # Linear 1
          w2 = tf.get_variable( name="w2_"+str(idx), initializer=kaiming, shape=[input_size, linear_size], dtype=dtype)
          b2 = tf.get_variable( name="b2_"+str(idx), initializer=kaiming, shape=[linear_size], dtype=dtype)
          w2 = tf.clip_by_norm(w2,1) if max_norm else w2
          y = tf.matmul(xin, w2) + b2
          if  batch_norm:
            y = tf.layers.batch_normalization(y,training=self.isTraining,name="batch_normalization1"+str(idx))
    
          y = tf.nn.relu( y )
          y = tf.nn.dropout( y, dropout_keep_prob )
    
          # Linear 2
          w3 = tf.get_variable( name="w3_"+str(idx), initializer=kaiming, shape=[linear_size, linear_size], dtype=dtype)
          b3 = tf.get_variable( name="b3_"+str(idx), initializer=kaiming, shape=[linear_size], dtype=dtype)
          w3 = tf.clip_by_norm(w3,1) if max_norm else w3
          y = tf.matmul(y, w3) + b3
    
          if  batch_norm:
            y = tf.layers.batch_normalization(y,training=self.isTraining,name="batch_normalization2"+str(idx))
    
          y = tf.nn.relu( y )
          y = tf.nn.dropout( y, dropout_keep_prob )
    
          # Residual every 2 blocks
          y = (xin + y) if residual else y
    
        return y

The pretrained weights for this model are stored in a checkpoint file which I extract using the following code:

    PATH_REL_META= #insert file path to checkpoint
    
    with tf.Session() as sess:
            
        #import graph
        saver=tf.train.import_meta_graph(PATH_REL_META)
        
        #load weights for graph
        saver.restore(sess,PATH_REL_META[:-5])
        
        #get all global variables 
        vars_global=tf.global_variables()
        
        #get their name and value and puth them into a dictionary
        sess.as_default()
        model_vars={}
        for var in vars_global:
            try:
                model_vars[var.name]=var.eval()
            except:
                print("For var={}, an exception occurred".format.name)

Then I define the keras model with the following code and load the weights from the dictionary:

    def two_linear(xin,linear_size,dropout_keep_prob,idx):
       # Args
       # xin: the batch that enters the block
       # linear_size: integer. The size of the linear units
       # residual: boolean. Whether to add a residual connection
       # dropout_keep_prob: float [0,1]. Probability of dropping something out
       # max_norm: boolean. Whether to clip weights to 1-norm
       # batch_norm: boolean. Whether to do batch normalization
       # Returns
       # y: batch after it leaves the block
       
       # Linear 1
       # he_uniform is the Kainming initilization in Keras
       
       
    
       y=tf.keras.layers.Dense(linear_size,kernel_initializer="he_uniform",
                               bias_initializer="he_uniform",
                               kernel_constraint=max_norm(1),
                               name="two_linear/w2_"+str(idx))(xin)
       y=tf.keras.layers.BatchNormalization(name="two_linear/batch_normalization1"+str(idx))(y,training=False)
       y=tf.keras.layers.Activation('relu')(y)
       y=tf.keras.layers.Dropout(dropout_keep_prob)(y,training=False)
       
       
       y=tf.keras.layers.Dense(linear_size,kernel_initializer="he_uniform",
                               bias_initializer="he_uniform",
                               kernel_constraint=max_norm(1),
                               name="two_linear/w3_"+str(idx))(y)
       y=tf.keras.layers.BatchNormalization(name="two_linear/batch_normalization2"+str(idx))(y,training=False)
       y=tf.keras.layers.Activation('relu')(y)
       y=tf.keras.layers.Dropout(dropout_keep_prob)(y,training=False)  
       
       
       y=tf.keras.layers.Add()([xin,y])
       
       
       return y
      
    def ModelDef(linear_size,dropout_keep_prob,num_layers):
        input_shape=(32,)
        xin=tf.keras.layers.Input(input_shape)
        #y_1=tf.keras.layers.Reshape((32,))(xin)
        
        y_1=tf.keras.layers.Dense(linear_size,kernel_initializer='he_uniform',
                                bias_initializer='he_uniform',
                                kernel_constraint=max_norm(1),
                                name="linear_model/w1")(xin)
        y_1=tf.keras.layers.BatchNormalization(name="batch_norm/0")(y_1,training=False)
        y_1=tf.keras.layers.Activation('relu')(y_1)
        y=tf.keras.layers.Dropout(dropout_keep_prob)(y_1,training=False)
        
        for idx in range(num_layers):
            y=two_linear(y,linear_size,dropout_keep_prob,idx)
            
        
        y=tf.keras.layers.Dense(16*3,kernel_initializer='he_uniform',
                            bias_initializer='he_uniform',
                            kernel_constraint=max_norm(1),
                            name="linear_model/w4")(y)
        
        model=tf.keras.Model(inputs=xin,outputs=y)
        
        return model
    
    #Create model and load weights
    
    weight_path=''
    with open(weight_path,"rb") as pf:
        weights=pickle.load(pf)
        
    model=ModelDef(1024,.1,2)
    
    print(model.weights[0])
        model.get_layer("linear_model/w1").set_weights([tf.clip_by_norm(weights["linear_model/w1:0"],1),weights["linear_model/b1:0"]])
    model.get_layer("batch_norm/0").set_weights([weights['linear_model/batch_normalization/gamma:0']
                                                  ,weights['linear_model/batch_normalization/beta:0']
                                                ,weights['linear_model/batch_normalization/moving_mean:0'] 
                                                ,weights['linear_model/batch_normalization/moving_variance:0']])
    
    model.get_layer("two_linear/w2_0").set_weights([tf.clip_by_norm(weights["linear_model/two_linear_0/w2_0:0"],1),
                                                    weights["linear_model/two_linear_0/b2_0:0"]])
    model.get_layer("two_linear/batch_normalization10").set_weights([weights["linear_model/two_linear_0/batch_normalization10/gamma:0"],
                                                            weights["linear_model/two_linear_0/batch_normalization10/beta:0"],
                                                            weights["linear_model/two_linear_0/batch_normalization10/moving_mean:0"],
                                                            weights["linear_model/two_linear_0/batch_normalization10/moving_variance:0"]])
    
    model.get_layer("two_linear/w3_0").set_weights([tf.clip_by_norm(weights["linear_model/two_linear_0/w3_0:0"],1),
                                                   weights["linear_model/two_linear_0/b3_0:0"]])
    
    model.get_layer("two_linear/batch_normalization20").set_weights([weights["linear_model/two_linear_0/batch_normalization20/gamma:0"],
                                                            weights["linear_model/two_linear_0/batch_normalization20/beta:0"],
                                                            weights["linear_model/two_linear_0/batch_normalization20/moving_mean:0"],
                                                            weights["linear_model/two_linear_0/batch_normalization20/moving_variance:0"]])
    
    
    model.get_layer("two_linear/w2_1").set_weights([tf.clip_by_norm(weights["linear_model/two_linear_1/w2_1:0"],1),
                                                    weights["linear_model/two_linear_1/b2_1:0"]])
    model.get_layer("two_linear/batch_normalization11").set_weights([weights["linear_model/two_linear_1/batch_normalization11/gamma:0"],
                                                            weights["linear_model/two_linear_1/batch_normalization11/beta:0"],
                                                            weights["linear_model/two_linear_1/batch_normalization11/moving_mean:0"],
                                                            weights["linear_model/two_linear_1/batch_normalization11/moving_variance:0"]])
    
    model.get_layer("two_linear/w3_1").set_weights([tf.clip_by_norm(weights["linear_model/two_linear_1/w3_1:0"],1),
                                                   weights["linear_model/two_linear_1/b3_1:0"]])
    
    model.get_layer("two_linear/batch_normalization21").set_weights([weights["linear_model/two_linear_1/batch_normalization21/gamma:0"],
                                                            weights["linear_model/two_linear_1/batch_normalization21/beta:0"],
                                                            weights["linear_model/two_linear_1/batch_normalization21/moving_mean:0"],
                                                            weights["linear_model/two_linear_1/batch_normalization21/moving_variance:0"]])    
    
    model.get_layer("linear_model/w4").set_weights([tf.clip_by_norm(weights["linear_model/w4:0"],1)
                                                    ,weights["linear_model/b4:0"]])    

 

weights contains the dictionary created from the middle block of code. Inside the dictionary I have the following keys: 

    learning_rate:0
    global_step:0
    linear_model/w1:0
    linear_model/b1:0
    linear_model/batch_normalization/beta:0
    linear_model/batch_normalization/gamma:0
    linear_model/batch_normalization/moving_mean:0
    linear_model/batch_normalization/moving_variance:0
    linear_model/two_linear_0/w2_0:0
    linear_model/two_linear_0/b2_0:0
    linear_model/two_linear_0/batch_normalization10/beta:0
    linear_model/two_linear_0/batch_normalization10/gamma:0
    linear_model/two_linear_0/batch_normalization10/moving_mean:0
    linear_model/two_linear_0/batch_normalization10/moving_variance:0
    linear_model/two_linear_0/w3_0:0
    linear_model/two_linear_0/b3_0:0
    linear_model/two_linear_0/batch_normalization20/beta:0
    linear_model/two_linear_0/batch_normalization20/gamma:0
    linear_model/two_linear_0/batch_normalization20/moving_mean:0
    linear_model/two_linear_0/batch_normalization20/moving_variance:0
    linear_model/two_linear_1/w2_1:0
    linear_model/two_linear_1/b2_1:0
    linear_model/two_linear_1/batch_normalization11/beta:0
    linear_model/two_linear_1/batch_normalization11/gamma:0
    linear_model/two_linear_1/batch_normalization11/moving_mean:0
    linear_model/two_linear_1/batch_normalization11/moving_variance:0
    linear_model/two_linear_1/w3_1:0
    linear_model/two_linear_1/b3_1:0
    linear_model/two_linear_1/batch_normalization21/beta:0
    linear_model/two_linear_1/batch_normalization21/gamma:0
    linear_model/two_linear_1/batch_normalization21/moving_mean:0
    linear_model/two_linear_1/batch_normalization21/moving_variance:0
    linear_model/w4:0
    linear_model/b4:0
    beta1_power:0
    beta2_power:0
    linear_model/w1/Adam:0
    linear_model/w1/Adam_1:0
    linear_model/b1/Adam:0
    linear_model/b1/Adam_1:0
    linear_model/batch_normalization/beta/Adam:0
    linear_model/batch_normalization/beta/Adam_1:0
    linear_model/batch_normalization/gamma/Adam:0
    linear_model/batch_normalization/gamma/Adam_1:0
    linear_model/two_linear_0/w2_0/Adam:0
    linear_model/two_linear_0/w2_0/Adam_1:0
    linear_model/two_linear_0/b2_0/Adam:0
    linear_model/two_linear_0/b2_0/Adam_1:0
    linear_model/two_linear_0/batch_normalization10/beta/Adam:0
    linear_model/two_linear_0/batch_normalization10/beta/Adam_1:0
    linear_model/two_linear_0/batch_normalization10/gamma/Adam:0
    linear_model/two_linear_0/batch_normalization10/gamma/Adam_1:0
    linear_model/two_linear_0/w3_0/Adam:0
    linear_model/two_linear_0/w3_0/Adam_1:0
    linear_model/two_linear_0/b3_0/Adam:0
    linear_model/two_linear_0/b3_0/Adam_1:0
    linear_model/two_linear_0/batch_normalization20/beta/Adam:0
    linear_model/two_linear_0/batch_normalization20/beta/Adam_1:0
    linear_model/two_linear_0/batch_normalization20/gamma/Adam:0
    linear_model/two_linear_0/batch_normalization20/gamma/Adam_1:0
    linear_model/two_linear_1/w2_1/Adam:0
    linear_model/two_linear_1/w2_1/Adam_1:0
    linear_model/two_linear_1/b2_1/Adam:0
    linear_model/two_linear_1/b2_1/Adam_1:0
    linear_model/two_linear_1/batch_normalization11/beta/Adam:0
    linear_model/two_linear_1/batch_normalization11/beta/Adam_1:0
    linear_model/two_linear_1/batch_normalization11/gamma/Adam:0
    linear_model/two_linear_1/batch_normalization11/gamma/Adam_1:0
    linear_model/two_linear_1/w3_1/Adam:0
    linear_model/two_linear_1/w3_1/Adam_1:0
    linear_model/two_linear_1/b3_1/Adam:0
    linear_model/two_linear_1/b3_1/Adam_1:0
    linear_model/two_linear_1/batch_normalization21/beta/Adam:0
    linear_model/two_linear_1/batch_normalization21/beta/Adam_1:0
    linear_model/two_linear_1/batch_normalization21/gamma/Adam:0
    linear_model/two_linear_1/batch_normalization21/gamma/Adam_1:0
    linear_model/w4/Adam:0
    linear_model/w4/Adam_1:0
    linear_model/b4/Adam:0
    linear_model/b4/Adam_1:0

The predictions I am getting from the Keras model are way off from directly loading the tensorflow checkpoint data and making predictions. Is there something obvious I am missing that someone can point me in the right direction to correct?

Thanks in advance and sorry for the long post!

**Comment by amahendrakar** [comment]
@alecda573,
The code provided is fairly complex, and it is hard for us to pinpoint the issue. Can you please get the example down to the simplest possible repro? That will allow easily determine the source of the issue. 

Also, could you please update TensorFlow to v2.3 and check if you are facing the same issue. Thanks!

**Comment by alecda573** [comment]
@amahendrakar I understand it is a lot of code, but the error comes from the predictions, so one needs both models with their corresponding weights to see the difference. I can share the input and the expected output from the checkpoint file, but the error is either in the way the layers are defined in tf 1.14 vs the layers in tf2.0 or something with loading the weights.

**Comment by alecda573** [comment]
@amahendrakar 

Here is a test input

inputs=[ 1.20055843 , 9.5001441 , 1.28896216, 9.20799957, 1.02979768 ,14.61186754,
1.34260403 ,15.19059108 , 1.06410921 ,9.80336169 , 0.21302668, 16.85347291,
0.66403191 ,19.87040819 ,-0.91137277 , 5.88071359 ,-0.159872 , 5.91967813,
-2.33728939 , 5.72899468 ,-1.01297238, 6.04449154 , 0.23375924, 7.69306223,
-0.58144358, 7.37566207 ,-0.80297561, 5.55409911 , 0.0400928 , 7.04556159,
-0.24246983 , 6.69960958]

and expected output

-1.4627209 0.06322208 -1.5446033 -0.8570251 0.10563412 -1.7503448
-1.0881038 -0.21964559 -1.710271 1.4627217 -0.06322674 1.5446105
1.5793833 -0.23196149 -0.19457686 -0.09048957 -0.8984171 0.21485351
1.5640202 3.0261412 -2.4134905 2.2451577 4.6926637 -2.7548583
1.7437289 4.536124 -2.8321414 1.8803942 4.6508107 -2.988177
2.3924298 4.6636 -2.0411975 1.4061872 4.8059707 -1.3145562
0.7168709 4.5796676 -1.5989876 0.23200849 4.1992345 -2.8457897
-0.0461012 3.92069 -2.0317354 0.27443174 3.9237206 -2.2436898

https://www.dropbox.com/sh/1tmttjfcmebluil/AABAjy2ItvvZpUzdTYHWECy_a?dl=0 -- checkpoint that gives correct predictions
weight dictionary also in this folder
https://github.com/alecda573/Frozen_Graph-and-HDF5 -- frozen graph

**Comment by sainttail** [comment]
Don't know it is the same problem or not but, it is also occur to me and I create a repo that is reproducible on both my window and mac machine

@amahendrakar 

[This](https://github.com/sainttail/tensorflow-load-weights-problem) is the full standalone reproducible problem when `load_weights` each time get you a random evaluation loss and accuracy

**Comment by alecda573** [comment]
@sainttail did you ever find a solution to the problem?

**Comment by sainttail** [comment]
@alecda573 No I try both `load_weights()` and `tf.keras.models.load_model()` same problem. 

Since my model is fairly simple, if I can't find solution soon I will have to use other framework

**Comment by alecda573** [comment]
@sainttail it seems there are issues between weights generated in tensorflow and passing to keras and even reloading weights just within keras. I would love some explanation of this or suggested fixes from @amahendrakar

**Comment by amahendrakar** [comment]
@alecda573,
Sorry for the delayed response. I am facing an error stating `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 45: invalid start byte` on running the code. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/15607eccd17d1fc1bf540ecb0e0c3892/44123.ipynb#scrollTo=8qtzsBcF8fQe). 

Could you please provide a repo link as @sainttail has provided or a Colab notebook of the code, so that we can reproduce the issue on our end. Thanks!

**Comment by amahendrakar** [comment]
> @amahendrakar
> 
> [This](https://github.com/sainttail/tensorflow-load-weights-problem) is the full standalone reproducible problem when `load_weights` each time get you a random evaluation loss and accuracy

@sainttail,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
