### ISSUE TITLE
Tensorflow Lite with Nvidia GPU on Ubuntu happen coredump when creating delegate.

### ISSUE THREAD

**Issue by michaelnguyen11** [tensorflow/tensorflow#44129]
Hi Supporters,

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): master branch (2.3.1)
- Python version: 3.8
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: 10.1
- GPU model and memory: GeForce GTX 1050 Ti, 4Gb

**Describe the current behavior**
I tried to inference TF lite model with GPU, everything is normal with TF using CPU, but when create delagate, coredump happens immediately.

**Standalone code to reproduce the issue**
```
#include <iostream>
#include <memory>

#include <tensorflow/lite/interpreter.h>
#include <tensorflow/lite/kernels/register.h>
#include <tensorflow/lite/string_util.h>
#include <tensorflow/lite/model.h>
#include <tensorflow/lite/delegates/gpu/delegate.h>
#include <tensorflow/lite/delegates/gpu/gl_delegate.h>

int main()
{
    std::unique_ptr<tflite::FlatBufferModel> model = tflite::FlatBufferModel::BuildFromFile("superpoint_640x480.tflite");
    if (!model)
    {
        std::cerr << "Failed to mmap tflite model" << std::endl;
        return -1;
    }
    tflite::ops::builtin::BuiltinOpResolver resolver;
    std::unique_ptr<tflite::Interpreter> interpreter;
    if (tflite::InterpreterBuilder(*model.get(), resolver)(&interpreter) != kTfLiteOk)
    {
        std::cerr << "Failed to interpreter tflite model" << std::endl;
        return -1;
    }

    // auto* delegate = TfLiteGpuDelegateCreate(nullptr);
    // if (interpreter->ModifyGraphWithDelegate(delegate) == kTfLiteOk)
    // {
    //     std::cerr << "Failed to enable GPU." << std::endl;
    //     return -1;
    // }

    //  NEW: Prepare custom options with feature enabled.
    TfLiteGpuDelegateOptionsV2 options = TfLiteGpuDelegateOptionsV2Default();
    options.experimental_flags = TFLITE_GPU_EXPERIMENTAL_FLAGS_NONE;

    auto* delegate = TfLiteGpuDelegateV2Create(&options);
    if (interpreter->ModifyGraphWithDelegate(delegate) != kTfLiteOk){
        std::cerr << "Failed to register delegate" << std::endl;
        return -1;
    }

    return 0;
}
```
TF Lite model file : 
[superpoint_640x480.zip](https://github.com/tensorflow/tensorflow/files/5397657/superpoint_640x480.zip)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
[backtrace.txt](https://github.com/tensorflow/tensorflow/files/5397656/backtrace.txt)

As I know so far, TF Lite on GPU supported PAD ops, but don't know why the coredump happened here.
Have you seen this ? Could you help me overcome this kind of issue ?
Many thanks in advance.

**Comment by ymodak** [comment]
Are you trying TF Lite gpu delegate on desktop machine?
TensorFlow Lite delegate APIs are supported on Android and iOS platform as of now. Thanks!
See https://www.tensorflow.org/lite/performance/gpu

**Comment by michaelnguyen11** [comment]
Hi @ymodak,

Yes I'm using TF Lite GPU delegate on Desktop machine. So the TF Lite GPU supports only Android and iOS platforms, does it ?
I'm developing a TF Lite model and expecting to inference it on embedded device which included NPU. So could you please give me some hint that I can use the TF Lite GPU delegate to inference the model on the edge with NPU ?

Many thanks in advance.

**Comment by impjdi** [comment]
NPU has nothing in common with GPU, and I'm kinda confused why you would start with the GPU.

Having said that, I don't see anything in the code that could cause a segfault in the PadOperationParser.  Can you compile with -g to get more info from the debugger?

**Comment by michaelnguyen11** [comment]
Hi @impjdi,

Thank you for your response.

As so far I know, creating GPU and NNAPI delegate and register to Interpreter are pretty similar, so I would like to start with GPU first for easy to develop and test on laptop. 

Added CMAKE_BUILD_TYPE=Debug to cmake. Please see that attach file for back trace
[gdb.txt](https://github.com/tensorflow/tensorflow/files/5413234/gdb.txt)

**Comment by impjdi** [comment]
> No symbol table info available.

tells me that the delegate isn't built with `-g` =/

**Comment by michaelnguyen11** [comment]
Thanks for you help. I managed to run the Nvidia GPU with TF Lite version 2.3

Used this command to build TF Lite gpu delegate : bazel build -s -c opt --config=monolithic --config=noaws --config=nonccl --config=v2 --define=tflite_convert_with_select_tf_ops=true --define=with_select_tf_ops=true --copt="-DMESA_EGL_NO_X11_HEADERS" tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so

As well as the use this code to register gpu delegate:
```
const TfLiteGpuDelegateOptionsV2 options = {
    .is_precision_loss_allowed = 1, // FP16
    .inference_preference = TFLITE_GPU_INFERENCE_PREFERENCE_FAST_SINGLE_ANSWER,
    .inference_priority1 = TFLITE_GPU_INFERENCE_PRIORITY_MIN_LATENCY,
    .inference_priority2 = TFLITE_GPU_INFERENCE_PRIORITY_AUTO,
    .inference_priority3 = TFLITE_GPU_INFERENCE_PRIORITY_AUTO,
};

TfLiteDelegate *delegate = TfLiteGpuDelegateV2Create(&options);
if (interpreter->ModifyGraphWithDelegate(delegate) != kTfLiteOk)
{
    std::cerr << "Failed to modify graph with delegate" << std::endl;
    exit(0);
}
```

**Comment by FengMu1995** [comment]
@michaelnguyen11 Really? You could run tflite gpu delegates on Nvidia gpu,.
I tried it, but it failed.
