### ISSUE TITLE
Running TFlite on mobile device GPU fails  - Ops not supported

### ISSUE THREAD

**Issue by shlomi-amitai** [tensorflow/tensorflow#44124]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary): source 
- TensorFlow version (or github SHA if from source):
nightly

.
.
INFO: Created TensorFlow Lite delegate for GPU.
ERROR: Following operations are not supported by GPU delegate:
DELEGATE TfLiteFlexDelegate: Operation is not supported.
EQUAL: Operation is not supported.
SPLIT: Operation is not supported.
WHILE: Operation is not supported.
62 operations will run on the GPU, and the remaining 907 operations will run on the CPU.
ERROR: TfLiteGpuDelegate Prepare: No shader implementation for transpose
ERROR: Node number 1001 (TfLiteGpuDelegate) failed to prepare.

ERROR: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
ERROR: Node number 813 (FlexTensorScatterUpdate) failed to prepare.
.
.
unfortunately can't send the code.

**Comment by ravikyram** [comment]
@shlomi-amitai 
Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Please, let us know which TF version you are using?
Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by shlomi-amitai** [comment]
I'm working on tf nightly build.
attached is my model with a python tester.
c++ execution code is more problematic for me to send.
[modelWrapper.zip](https://github.com/tensorflow/tensorflow/files/5400662/modelWrapper.zip)

**Comment by impjdi** [comment]
> DELEGATE TfLiteFlexDelegate: Operation is not supported.
Of course, GPU cannot handle the flex delegate.  I'm not even sure why this is fed into the GPU delegate's prepare.  @srjoglekar246 

> EQUAL: Operation is not supported.
I think there's some plan to bring this in.  No ETAs though.

> SPLIT: Operation is not supported.
This is not difficult to implement, but not prioritized because there was no use case.  Can this be rewritten with `STRIDED_SLICE`?  @renjie-liu Is this applicable for tac?

> WHILE: Operation is not supported.
Control flows are not available on the GPU delegate.  This is gonna be quite difficult, and probably can't be easily supported.  It would have to fall back to the CPU when control flow comes into play.

**Comment by srjoglekar246** [comment]
> ERROR: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
ERROR: Node number 813 (FlexTensorScatterUpdate) failed to prepare

Using Select TF operators (aka Flex) requires some additional changes to your BUILD, to pull in TF dependencies. See [here](https://www.tensorflow.org/lite/guide/ops_select).

> ERROR: TfLiteGpuDelegate Prepare: No shader implementation for transpose

@impjdi Any idea why this would occur?

@shlomi-amitai In general, if performance is important, see if you can change your model authoring logic (in TensorFlow) to have ops that [TFLite supports](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/versioning/op_version.cc). Looks like the only op that requires Flex here is [scatter and update](https://www.tensorflow.org/api_docs/python/tf/tensor_scatter_nd_update).

**Comment by renjie-liu** [comment]
Yes, split can be unrolled into `slice` op.

**Comment by shlomi-amitai** [comment]
Thank you guys for your help.
@impjdi, regarding the split operation. 
I'm converting a model from pytorch so these split operations are automatically added when generating the protobuffer (.pb)  from .onnx. I have no way, I assume, to control these additions. if it helps, I can send you the .onnx model.

**Comment by shlomi-amitai** [comment]
Basically, all I care now is to make this pass and run (even partly) on the device's gpu. 
I would like that parts of the NN that can run on GPU would do that. but currently the run failes with the above errors. 

I'm compiling libtesnorflowlite.so this way:
1. in tensorflow/lite/BUILD -> under deps I add a flag  "//tensorflow/lite/delegates/flex:delegate"
2. bazel build -c opt --local_ram_resources 2048 --local_cpu_resources 1 --jobs 1 --config=android_arm64 --config=monolithic tensorflow/lite:libtensorflowlite.so
3. for GPU: bazel build -c opt --local_ram_resources 2048 --local_cpu_resources 1 --jobs 1 --config=android_arm64 --config=monolithic //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_gl.so

**Comment by srjoglekar246** [comment]
> in tensorflow/lite/BUILD -> under deps I add a flag "//tensorflow/lite/delegates/flex:delegate"

Does this remove the error "Make sure you apply/link the Flex delegate before inference."? Not sure if this matters, but I usually link the delegate to my client app (that is the BUILD rule of my binary that uses TFLite), rather than TFLite itself.

To debug further, can you check if the Flex error vanish *and* you can run the model successfully without the GPU? That would atleast confirm if the Flex part of this is running as intended, We can then debug the GPU part further.

**Comment by shlomi-amitai** [comment]
I use this flag also with libtensorflowlite.so  and there it runs smoothly on CPU

**Comment by srjoglekar246** [comment]
I see. The GPU delegate `.so` BUILDs from tensorflow/lite/delegates/gpu/BUILD, so you will have  to add the Flex rule there :-). Also use the latest TF nightly for this, since we only recently added support for Flex w/ GPU

**Comment by shlomi-amitai** [comment]
I compiled #3 with the flex rule and I get libtensorflowlite_gpu_gl.so of size 4GB (50MB without the flag).. I can't even test the solution since I don't have this amount of space free in my device.

**Comment by shlomi-amitai** [comment]
to be on the same page here, I added the flex rule in tensorflow/lite/delegates/gpu/BUILD under libtensorflowlite_gpu_gl.so deps list.

**Comment by srjoglekar246** [comment]
You can choose only the relevant ops to be added to the binary, since the current solution you implemented adds *all* supported TF ops to the binary. See [this](https://www.tensorflow.org/lite/guide/reduce_binary_size). Adding @abattery who has more context on this.

**Comment by abattery** [comment]
Hi @shlomi-amitai

You can create your selective build-enabled flex build target in the bazel as the following snippet:

```
tlite_flex_cc_library(
  name = "my_flex_delegate",
  models = ["model.tflite"],
)
```

The above special build target will trim the unused TF operators when linking. You can replace the //tensorflow/lite/delegates/flex:delegate with the above my_flex_delegate.

**Comment by shlomi-amitai** [comment]
Thanks for the support.
I added the above code to the BUILD file, replaced "//tensorflow/lite/delegates/flex:delegate" with  "my_flex_delegate" and copied my model.tflite to the BUILD directory.
the build ended with a size of 1.12GB, which is better but yet very big.
I will try and change the original model (in pytorch) to somehow reduce operator types but my questions are as follows:
1. Did my actions followed your instructions?
2.  Is there something more that can be done build wise to reduce the size of the SO?

**Comment by abattery** [comment]
Instead of adding the flex delegate dependency to the build targets in the tensorflow/lite/BUILD file, could you follow the document to generate the tensorflow-lite-select-tf-ops.aar based on your model?

**Comment by shlomi-amitai** [comment]
Thanks. 
I have tried this with nightly version of tensorflow and now getting this error during compilation:
ERROR: /tensorflow_src/WORKSPACE:53:1: //external:android/sdk depends on @androidsdk//:sdk in repository @androidsdk which failed to fetch. no such package '@androidsdk//': Bazel does not recognize Android build tools version debian: Invalid revision: debian
I will try to debug it.

**Comment by shlomi-amitai** [comment]
"Selective Build for C API and iOS version is not supported currently."

is this still valid?
I'm working with the C API.

**Comment by abattery** [comment]
@thaink could you answer the question at this thread?

**Comment by thaink** [comment]
> "Selective Build for C API and iOS version is not supported currently."
> 
> is this still valid?
> I'm working with the C API.

The selective build for C and iOS is not yet released.
For the build error when building with docker, What OS version are you using? did you enter "y" when the android license showed up?
