### ISSUE TITLE
Disable internal mkldnn_sgemm calls

### ISSUE THREAD

**Issue by electricSamarth** [tensorflow/tensorflow#44120]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian GNU/Linux 10
- TensorFlow installed from (source or binary): Source
- TensorFlow version:latest 
- Python version:3.7.3
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source):3.3.0
- GCC/Compiler version (if compiling from source): gcc 8.3
- I did **NOT** use the --config=mkl flag while building
- The image is a call graph of 1024X1024 Matmul done 100 times, if you look carefully mkldnn_sgemm is called internally by Eigen, this is what I want to disable.
 
![internal_eigen](https://user-images.githubusercontent.com/44555985/96214609-7444a200-0f99-11eb-988b-c4f9b32c6d2d.jpg)

After some amount of reading I found out that MKL/mkl_dnn can be called internally by Eigen and after reading the Bazel documentation and seeing how TensorFlow is strucured.I want to disable mkl/mkl_dnn completely if eigen is to be used.
The Eigen[ build files loads the ifmkl symbol](https://github.com/tensorflow/tensorflow/blob/bd35e19edbf55bf3f6b5d10545725d41a99aa9ba/third_party/eigen3/BUILD#L5) from the mkl directory.
My next step was to look at the [if_mkl function inside the build_defs.bzl](https://github.com/tensorflow/tensorflow/blob/c63b59ce648b525c4bbb2d85f04f5b71f1849ff2/third_party/mkl/build_defs.bzl#L17)   

I changed the [includes attribute in the cclibrary rule in the BUILD file of eigen](https://github.com/tensorflow/tensorflow/blob/44aace846df438bf55e88dad1e047b7c81f9efb9/third_party/eigen3/BUILD#L36) to ["//conditions:default"]

which game me an error saying `ModuleNotFoundError: No module named 'portpicker' `

So pip installed portpicker `pip install portpicker`
And the build completed sucessfully, but the profile literally shows no difference mkldnn_sgemm is still bieng called the same number of time by eigen internally

NOTE: **The Ultimate aim is to disable mkldnn which is bieng called from inside eigen**

**Comment by penpornk** [comment]
Hi @electricSamarth,

This `mkldnn_sgemm` call in vanilla TensorFlow (non-MKL) build through Eigen is intentional and not a bug. To disable it, you can just add `--define tensorflow_mkldnn_contraction_kernel=0` to your build command. No code modifications necessary.
https://github.com/tensorflow/tensorflow/blob/20ca86ca6622ba66b6c970b221729ff9b6f931c6/tensorflow/core/kernels/BUILD#L122-L132

May I ask why you would like to disable `mkldnn_sgemm`? Based on our experiments, it performs at least as well as Eigen contractions for AVX and AVX2, and is better than Eigen for AVX-512. It also has dynamic dispatch, which means it can utilize up to AVX-512 instructions even when TensorFlow is compiled with older flags (e.g., AVX) -- Eigen can only use the vector instructions TensorFlow is compiled with.

cc: @TensorFlow-MKL @ezhulenev

**Comment by electricSamarth** [comment]
Thanks a lot @penpornk 
I am a 3rd year undergraduate student working on a research project at [CCBD](http://research.pes.edu/cloud-computing-big-data/research-team/) under [Dr. Reetinder Sidhu](https://scholar.google.com/citations?user=CzPQAekAAAAJ&hl=en) and we are trying to accelerate TF as a framework on FPGAs. I needed to conduct some benchmarks and wanted to compare the difference b/w performance of MKL and the vanilla install and got a little confused with all the mkl-dnn calls. 

Furthermore, I have a few queries and I would be very very grateful if you can answer:

1) These MKL-DNN calls are not calling sgemm from MKL, the closed source library as I did not specify the `--config=mkl` flag, right?

2) What would be the best way to find out how much percentage of resources are being spent on doing sgemm (resources could be IR reads as in case of profilers like Callgrind or simply time as in case of the Tensor-board profiler that comes with TF)

3) I have in fact tried both the methods but the problem with callgrind is [cycles](https://valgrind.org/docs/manual/cl-manual.html#cl-manual.cycles) which makes inclusive costs senseless and in the case of Tensor-board profiler, I am getting confused as to which metric I should be looking at? `The Cumulative total-self time on Host (%)` **OR**  `Total self-time on Host (%)`

**Comment by penpornk** [comment]
@electricSamarth Thank you for the explanation!

1. Both vanilla TF and TF-MKL (`--config=mkl`) only depend on the open-source [oneDNN](https://github.com/oneapi-src/oneDNN) library (formerly-known as MKL-DNN) and not the closed-source MKL. Here is the source of [dnnl_sgemm](https://github.com/oneapi-src/oneDNN/blob/f57921d3b7f18c07d2c07168fccad13749cb647f/src/cpu/gemm/gemm.cpp#L262-L267) (new name of `mkldnn_sgemm`).

2. I'd recommend [Google Perf Tools + pprof](https://riptutorial.com/cplusplus/example/19179/profiling-cpu-usage-with-gcc-and-google-perf-tools). It can generate a call graph annotated with running time ([like this](https://gperftools.github.io/gperftools/pprof-test.gif)) and highlight the critical path. Or [perf](https://dev.to/etcwilde/perf---perfect-profiling-of-cc-on-linux-of) tool. If you're fine with op-level profiling (as opposed to c++ function call-level), TensorBoard/TensorFlow profiler is great too.

> in the case of Tensor-board profiler, I am getting confused as to which metric I should be looking at? The Cumulative total-self time on Host (%) OR Total self-time on Host (%)

3. I assume you're on the TensorFlow Stats page. According to qiuminxu@, `Cumulative total-self time on Host (%)` is just the sum of `Total self-time on Host (%)` from the rank 1 op (in row 1 of the table) to the op you're looking at. So the numbers in that column are monotonically increasing. I think you'd be more interested in `Total self-time on Host (%)`.

**Comment by electricSamarth** [comment]
@penpornk Thanks for all the information, this is by far the most informative interaction I've had on GitHub.

But I tried installing TF with `--config=mkl` and the build failed, to resolve this I installed mkl from [Intel's official website](https://software.intel.com/content/www/us/en/develop/tools/math-kernel-library/choose-download/linux.html) and it built successfully. What could be the reason for this and this happened on not one but two machines
1) My own machine: DELL G7-7588 running Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
2) Server at the Lab I work at running Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz

Also the following returns true if MKL(the closed source library is installed & TF is built with --config=mkl flag) and returns false in 'Vanilla' Install we have been talking about
`import tensorflow`
`print("Is MKL enabled?{}".format(tensorflow.pywrap_tensorflow.IsMklEnabled()))`

**Comment by claynerobison** [comment]
@agramesh1 ^this^

**Comment by electricSamarth** [comment]
@claynerobison Hi!
I am a little confused :)
I was about to close this as no response, but I shall keep it open for further discussion from you and @agramesh1

**Comment by penpornk** [comment]
Hi @electricSamarth,

> But I tried installing TF with --config=mkl and the build failed, to resolve this I installed mkl from Intel's official website and it built successfully. What could be the reason for this and this happened on not one but two machines

What was the error message? We'll need more information. Could you please start a new Build/Installation issue and fill all necessary details? Here a [quick link](https://github.com/tensorflow/tensorflow/issues/new?labels=type%3Abuild%2Finstall&template=10-build-installation-issue.md) to the form. Please state in the topic that this is TF-MKL build and tag me and the @TensorFlow-MKL team.

> Also the following returns true if MKL(the closed source library is installed & TF is built with --config=mkl flag) and returns false in 'Vanilla' Install we have been talking about
import tensorflow
print("Is MKL enabled?{}".format(tensorflow.pywrap_tensorflow.IsMklEnabled()))

`IsMKLEnabled` checks whether the build is TF-MKL build or not (returns true if the build is TF-MKL, and returns false with vanilla TF). The function name is a bit misleading now that both builds use oneDNN (a.k.a. MKL-DNN). I'll discuss with the @TensorFlow-MKL team on whether we should rename it.

The main difference between vanilla TF and TF-MKL is:
* Vanilla TF only uses `mkldnn_sgemm` routine as a basic building block (through Eigen) for all matmul/convolution ops in TF.
* TF-MKL replaces many TF ops with its custom ops that call DNN primitives from the oneDNN library. (See op list [here](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/common_runtime/mkl_layout_pass.cc;drc=b348ad40bcee666e11cefd0388fa78577f76df7b;l=243-375).)

**Comment by agramesh1** [comment]
Thanks @penpornk, we will look into it.
@electricSamarth if you are using the latest master or 2.4 branch, the build no longer uses the binary MKL. We made changes over the last 1 or 2 months to replace cblas sgemms with oneDNN sgemms. (oneDNN is newer name for MKL DNN). Please try one of these branches.

**Comment by electricSamarth** [comment]
Thanks a ton! @penpornk & @agramesh1 
And yes, I shall open a new issue with the install/build template. I will also take a look/try the new branches.
