### ISSUE TITLE
Hello World Ubuntu 16.04 with nvidia 1660 super

### ISSUE THREAD

**Issue by aloizo03** [tensorflow/tensorflow#44122]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version:0.4.0
- Python version:2.7.12
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)
- CUDA/cuDNN version:V7.5.17
- GPU model and memory: NVIDIA 1660 SUPER GIGABYTE 6GB

**Describe the problem**

I do the command make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test to run the hello_world_test and print me this :

tensorflow/lite/micro/tools/make/Makefile:413: warning: overriding recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
tensorflow/lite/micro/tools/make/Makefile:413: warning: ignoring old recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
g++ -std=c++11 -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-unwind-tables -ffunction-sections -fdata-sections -fmessage-length=0 -DTF_LITE_STATIC_MEMORY -DTF_LITE_DISABLE_X86_NEON -O3 -Werror -Wsign-compare -Wdouble-promotion -Wshadow -Wunused-variable -Wmissing-field-initializers -Wunused-function -Wswitch -Wvla -Wall -Wextra -Wstrict-aliasing -Wno-unused-parameter  -I. -Itensorflow/lite/micro/tools/make/downloads/ -Itensorflow/lite/micro/tools/make/downloads/gemmlowp -Itensorflow/lite/micro/tools/make/downloads/flatbuffers/include -Itensorflow/lite/micro/tools/make/downloads/ruy -Itensorflow/lite/micro/tools/make/downloads/kissfft -c tensorflow/lite/micro/kernels/fully_connected.cc -o tensorflow/lite/micro/tools/make/gen/linux_x86_64/obj/tensorflow/lite/micro/kernels/fully_connected.o
tensorflow/lite/micro/kernels/fully_connected.cc: In function ‘TfLiteStatus tflite::{anonymous}::EvalQuantized(TfLiteContext*, TfLiteNode*, const tflite::{anonymous}::OpData&, const TfLiteEvalTensor*, const TfLiteEvalTensor*, const TfLiteEvalTensor*, TfLiteEvalTensor*)’:
tensorflow/lite/micro/kernels/fully_connected.cc:135:14: error: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Werror=strict-overflow]
 TfLiteStatus EvalQuantized(TfLiteContext* context, TfLiteNode* node,
              ^
tensorflow/lite/micro/kernels/fully_connected.cc:135:14: error: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Werror=strict-overflow]
tensorflow/lite/micro/kernels/fully_connected.cc:135:14: error: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Werror=strict-overflow]
tensorflow/lite/micro/kernels/fully_connected.cc:135:14: error: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Werror=strict-overflow]
In file included from ./tensorflow/lite/kernels/internal/common.h:29:0,
                 from tensorflow/lite/micro/kernels/fully_connected.cc:20:
./tensorflow/lite/kernels/internal/types.h:197:31: error: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Werror=strict-overflow]
     TFLITE_DCHECK_LT(i, size_);
                               ^
./tensorflow/lite/kernels/internal/types.h:197:31: error: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Werror=strict-overflow]
     TFLITE_DCHECK_LT(i, size_);
                               ^
tensorflow/lite/micro/kernels/fully_connected.cc: In function ‘TfLiteStatus tflite::{anonymous}::Eval(TfLiteContext*, TfLiteNode*)’:
tensorflow/lite/micro/kernels/fully_connected.cc:203:14: error: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Werror=strict-overflow]
 TfLiteStatus Eval(TfLiteContext* context, TfLiteNode* node) {
              ^
tensorflow/lite/micro/kernels/fully_connected.cc:203:14: error: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Werror=strict-overflow]
tensorflow/lite/micro/kernels/fully_connected.cc:203:14: error: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Werror=strict-overflow]
In file included from ./tensorflow/lite/kernels/internal/common.h:29:0,
                 from tensorflow/lite/micro/kernels/fully_connected.cc:20:
./tensorflow/lite/kernels/internal/types.h:197:31: error: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Werror=strict-overflow]
     TFLITE_DCHECK_LT(i, size_);
                               ^
./tensorflow/lite/kernels/internal/types.h:197:31: error: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Werror=strict-overflow]
     TFLITE_DCHECK_LT(i, size_);
                               ^
cc1plus: all warnings being treated as errors
tensorflow/lite/micro/tools/make/Makefile:424: recipe for target 'tensorflow/lite/micro/tools/make/gen/linux_x86_64/obj/tensorflow/lite/micro/kernels/fully_connected.o' failed
make: *** [tensorflow/lite/micro/tools/make/gen/linux_x86_64/obj/tensorflow/lite/micro/kernels/fully_connected.o] Error 1
 
How can i fix it and run ?

**Any other info / logs**
I didn't change anything i run it like i get the source code from github.

**Comment by Saduf2019** [comment]
@aloizo03 
Please refer to [this link](https://github.com/tensorflow/tensorflow/issues/29524) for the location of the makefile and let us know.
