### ISSUE TITLE
keras.models.load_model() checking for keras configuration mismatch

### ISSUE THREAD

**Issue by m3h0w** [tensorflow/tensorflow#44126]
**System information**
- TensorFlow version (you are using): 2.3.1
- Are you willing to contribute it (Yes/No): No (depending on how time-consuming it ends up being)

**Describe the feature and the current behavior/state.**
Currently, if the model is saved with the `"image_data_format": "channels_first"` option configured in keras.json it produces a shapes mismatch when loaded in an environment with `"image_data_format": "channels_last"` option. It's really difficult to debug since all issues found in Google point to mistakes in how the network is put together and results in hours wasted in looking for possible culprits.

I suggest that relevant parameters from keras.json configuration can be saved together with the model's metadata and keras.models.load_model() function could check for mismatch that will prevent the model from being loaded or running correctly in the environment it is being loaded in.

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
The world

**Any Other info.**

**Comment by SuryanarayanaY** [comment]
hi @m3h0w ,
At present there is no default implementation to resolve this.

As `data_format` is defined attribute for Convolution layers mainly and it is not available by default to other layers such as Dense,Input etc. Hence we can declare `data_format` in the relevant layers and then models can be saved to json format using below method alternate to `model.save()`.
```
model_to_json_form = model.to_json()
```
Then using below method we can reload the model.
```
loaded_model = tf.keras.models.model_from_json(model_to_json_form)
```
then using `json.loads(model_to_json_form)` we can get the attribute value of `data_format` and play around with reshaping of the inputs based on `data_format` value.

This may not the most elegant way but i believe it works. Please try the above methods and let us know the outcome.
