### ISSUE TITLE
Invoke returns NaN values when performing on floating points

### ISSUE THREAD

**Issue by DominikStachura** [tensorflow/tensorflow#44134]
@tensorflow/micro

**System information**
- Host Platform: Ubuntu 18.04.4 LTS
- TensorFlow installed from source,
- Tensorflow version: 86726adc39a1
- Target platform: STM32H745 (ARM M7)

I have Keras model trained on host platform. I want to use this model on my target device, after conversion to .tflite format. Once I perform conversion with quantization and obtain INT8 weights values, model works fine and gives correct predictions.
But when I try to convert model without quantization and try to run it with floating points values, inout vector and output vector contain NaN values after calling Invoke(). 

Input vector after calling invoke on INT8 weights:
![int](https://user-images.githubusercontent.com/58625554/96422788-c5060600-11f8-11eb-8d23-6e7a12bd7c27.PNG)

Input vector after calling invoke on Floating Points weights:
![float](https://user-images.githubusercontent.com/58625554/96422840-d5b67c00-11f8-11eb-9cf6-13be10c915a2.PNG)

Code that I use to convert with quantization:

```python
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np
import pickle

model = keras.models.load_model('data/models/best_model.hdf5')

X_train = pickle.load(open("dataset_from_target.pickle", "rb"))['x_train']

converter = tf.lite.TFLiteConverter.from_keras_model(model)
model_quant_tflite = converter.convert()


def representative_dataset():
  for i in range(1000):
    yield([np.expand_dims(X_train[i].astype(np.float32), axis=0)])


converter.optimizations = [tf.lite.Optimize.DEFAULT]

converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]

converter.representative_dataset = representative_dataset
model_tflite = converter.convert()

open("model_target.tflite", "wb").write(model_tflite)
```

Code that I use to convert with no quantization:

```python
import tensorflow as tf
import tensorflow.keras as keras


model = keras.models.load_model('data/models/best_model.hdf5')

converter = tf.lite.TFLiteConverter.from_keras_model(model)
model_no_quant_tflite = converter.convert()

# Set the optimization flag.
converter.optimizations = [tf.lite.Optimize.DEFAULT]
model_tflite = converter.convert()

open("model_target_new_data_no_quant.tflite", "wb").write(model_tflite)
```

Problem is not with RAM memory, which I have already checked. NaN values in 'input->data.f' results in all NaN values in 'output->data.f' which makes predictions impossible. Before calling invoke, input vector contains correct values.

**Comment by DominikStachura** [comment]
I noticed that the prolem disappear when I get rid of optimization during conversion:

```
model = keras.models.load_model('data/models/best_model.hdf5')


converter = tf.lite.TFLiteConverter.from_keras_model(model)

model_tflite = converter.convert()

open("model_target_new_data_no_quant.tflite", "wb").write(model_tflite)
```

But then the model weight is twice as big as with the optimization.

**Comment by ymodak** [comment]
Can you try enforcing full integer quantization for all ops including the input and output?
See https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only
```python
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8
model_tflite = converter.convert()
```
