### ISSUE TITLE
TypeError: 'InputLayer' object is not iterable

### ISSUE THREAD

**Issue by PlasticLunatic** [tensorflow/tensorflow#44138]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Catalina 10.15.6
- TensorFlow installed from (source or binary): using pip3 install
- TensorFlow version (use command below): v2.3.0-54-gfcc4b966f1 2.3.1
- Python version: 3.8

**Describe the current behavior**
When I try to convert tensorflow model to CoreML model using coremltools I get this error: TypeError: 'InputLayer' object is not iterable

**Describe the expected behavior**
Tensorflow model should convert to CoreML model without any errors.

**Standalone code to reproduce the issue**
model.save(modelFolder)

coreMLModel = convert(modelFolder, input_names = ['input'], output_names = ['output'])
coreMLModel.save(folderManager.modelsFolder)

**Comment by Saduf2019** [comment]
@PlasticLunatic 
Please refer to these resolved issue with same error and let us know:
#30204 #35813 [link](https://github.com/tensorflow/tensorflow/issues/24622).
