### ISSUE TITLE
Being able to register custom DataAdapter that inherit from the base class

### ISSUE THREAD

**Issue by tanguycdls** [tensorflow/tensorflow#44133]
**System information**
- TensorFlow version (you are using): 2.3
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Currently the list of available data adapter are registered here:
https://github.com/tensorflow/tensorflow/blob/6f440e215d0b4dfa2952729d8592af28976e48ef/tensorflow/python/keras/engine/data_adapter.py#L946

To support new use case such as supporting Py arrow array or Listarray (that will be converted to ragged). It could be nice to be able to register a custom data adapter to call keras directly with a dict of List Array or even with a Pandas Dataframe. 

**Will this change the current api? How?**

no.
**Who will benefit with this feature?**
Users with custom data need. 

**Any Other info.**

**Comment by fchollet** [comment]
The `DataAdapter` class is a private API. If we made it a public API that users can extend, it would increase our maintenance burden (in an area that is not our core competency) and it would limit our ability to do internal refactors.

If you need dataset support for things like PyArrow and so on, I suggest instead to seek adding an add-on in https://github.com/tensorflow/io

Thank you
