### ISSUE TITLE
Unexpected behaviour for tf.InteractiveSession() in Jupyter Notebook

### ISSUE THREAD

**Issue by liviu-** [tensorflow/tensorflow#4413]
I'm not convinced this is a bug, but if I run `tf.InteractiveSession()` in a cell with no assignment (e.g. `sess = tf.InteractiveSession()`), the interactive session will work only as long as the call is the last operation in the notebook cell and the output is not suppressed with `; `. This tripped me over a few times, so I'm reporting it just in case this is not the intended behaviour.

FWIW I think this is because IPython/Jupyter stores the session automatically in the cases I highlighted, making the command alike `sess = tf.InteractiveSession()` which works as expected.

### Environment info
Operating System: Linux

Installed version of CUDA and cuDNN: Using CPU version

If installed from binary pip package, provide:

1. A link to the pip package you installed: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0-cp35-cp35m-linux_x86_64.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`. 0.10.0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

I open a Jupyter notebook, and this works:
```python
In [1]: import tensorflow as tf
In [2]: tf.InteractiveSession()
In [3]: tf.constant(0).eval()
```
This doesn't:
```python
In [1]: import tensorflow as tf
In [2]: tf.InteractiveSession();
In [3]: tf.constant(0).eval()
```
Neither does this one:
```python
In [1]: import tensorflow as tf
In [2]: tf.InteractiveSession()
        print()
In [3]: tf.constant(0).eval()
```

The both fail with:
```python
ValueError                                Traceback (most recent call last)
<ipython-input-3-b43e5df4f2f7> in <module>()
----> 1 tf.constant(0).eval()

/usr/lib/python3.5/site-packages/tensorflow/python/framework/ops.py in eval(self, feed_dict, session)
    557 
    558     """
--> 559     return _eval_using_default_session(self, feed_dict, self.graph, session)
    560 
    561 

/usr/lib/python3.5/site-packages/tensorflow/python/framework/ops.py in _eval_using_default_session(tensors, feed_dict, graph, session)
   3640     session = get_default_session()
   3641     if session is None:
-> 3642       raise ValueError("Cannot evaluate tensor using `eval()`: No default "
   3643                        "session is registered. Use `with "
   3644                        "sess.as_default()` or pass an explicit session to "

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`
```

**Comment by yaroslavvb** [comment]
what if you do
```
sess=tf.InteractiveSession()
sess.run(tf.constant(0))

```?

I'm wondering if the `InteractiveSession` line even gets executed

**Comment by hholst80** [comment]
@yaroslavvb that works. do you have any idea why? 

It certainly looks like its initializing a session but not setting the default session variable.

```
In [1]: import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally

In [2]: tf.InteractiveSession();
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties:
name: GeForce GTX 980
major: 5 minor: 2 memoryClockRate (GHz) 1.2155
pciBusID 0000:03:00.0
Total memory: 4.00GiB
Free memory: 2.75GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980, pci bus id: 0000:03:00.0)

In [3]: tf.constant(0).eval()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-b43e5df4f2f7> in <module>()
----> 1 tf.constant(0).eval()

/home/hholst/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py in eval(self, feed_dict, session)
    557
    558     """
--> 559     return _eval_using_default_session(self, feed_dict, self.graph, session)
    560
    561

/home/hholst/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py in _eval_using_default_session(tensors, feed_dict, graph, session)
   3640     session = get_default_session()
   3641     if session is None:
-> 3642       raise ValueError("Cannot evaluate tensor using `eval()`: No default "
   3643                        "session is registered. Use `with "
   3644                        "sess.as_default()` or pass an explicit session to "

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

In [4]:
```

**Comment by yaroslavvb** [comment]
You are not saving `tf.InteractiveSession()` into any variable, so it gets garbage collected. Jupyter has helper variable `_` which stores output of last expression, so in one of the cases this variable prevents your session from getting gc'ed

**Comment by liviu-** [comment]
@yaroslavvb I also think it may be something related to the GC, but perhaps Jupyter has a more complex variable persistence system?
If you run a cell with
```python
tf.InteractiveSession()
````
and then delete the contents of the cell, and run
```
1
```
Then `1` is stored in `_` (as verified by running `print(_)`), but the session still works (as verified by `tf.constant(0).eval()`). Could it be that Jupyter stores a history of outputs somewhere?

In any case, I understand that the best way to avoid all this is to assign the output of `tf.InteractiveSession()` to a variable, and I'm not sure if TensorFlow can do anything to avoid this confusion likely caused by Jupyter.

**Comment by hholst80** [comment]
If it was as simple as having the session variabel in the workspace, two evals in sequence would not work. The first one would overwrite _ and the session would be GC. I would say something is wrong with the internals of tf.InteractiveSession?

PS. The output is from  ipython.

**Comment by yaroslavvb** [comment]
there's Jupyter history  that saves output of previous evals

**Comment by aselle** [comment]
According to the documentation, you need to assign the result of `tf.InteractiveSession` to a variable:
https://www.tensorflow.org/versions/r0.11/api_docs/python/client.html#InteractiveSession

That being said, the behavior seems to be different between 0.10 and nightly build, so this may be working differently now. Could you try it in the nightly build?

**Comment by aselle** [comment]
Automatically closing due to lack of recent response. Please reopen when additional information becomes available. Thanks!

**Comment by Iamsmallz** [comment]
I noticed that the version you are using is 1.2.
Maybe you can try to add the one line in cc_library. 
>testonly = 1,

Such as

>cc_binary(
    name = "my_binary",
    testonly = 1,
