### ISSUE TITLE
import Error. used on ubuntu,apache

### ISSUE THREAD

**Issue by waretaflow** [tensorflow/tensorflow#44143]
## env
- ubuntu:16 or 18
- apache:2.4
- python:3.6.9
- tensorflow:2.x.x
- django:2.x

I don't have a clear reason.
This issue error message is not found in `/var/log/apache2/error.log`.

## Reproduction method.
1. `conda create -n django python==3.6.9` or `pyenv install python3.6.9`
2. `conda install tensorflow` or `pip install tensorflow`
3. make django simple project
```python:views.py
from django.shortcuts import render, redirect
import tensorflow as tf

def func(request):
    return redirect("https://www.google.com/")
```
4. deploy by Apache2.4 used with mod_wsgi
``` 
~/etc/apache2/sites-available/django.conf~
LoadModule wsgi_module /home/ubuntu/anaconda3/envs/django/lib/python3.6/site-packages/mod_wsgi/server/mod_wsgi-py36.cpython-36m-x86_64-linux-gnu.so
WSGIPythonHome /home/ubuntu/anaconda3/envs/django
WSGIPythonPath /home/ubuntu/django_project:/home/ubuntu/anaconda3/envs/django/lib/python3.6/site-packages
WSGIScriptAlias / /home/ubuntu/django_project/project/wsgi.py
<Directory /home/ubuntu/django_project/project>
  <Files wsgi.py>
    Require all granted
  </Files>
</Directory>
Alias /static/ /home/ubuntu/django_project/static/
<Directory /home/ubuntu/django_project/static>
  Require all granted
</Directory>
```
5. Access 
6. Maybe you will be kept waiting forever .

**Comment by amahendrakar** [comment]
@waretaflow,
Installation issues within the Anaconda environment are tracked in the Anaconda repo.

Could you please submit a new issue using [this link](https://github.com/ContinuumIO/anaconda-issues/issues) and fill in the template, so that the issue can be tracked there. Thanks!

**Comment by waretaflow** [comment]
Thanks  amahendrakar.
Bad mistake. The issue is occrus in used `pip`.

**Comment by amahendrakar** [comment]
@waretaflow,
Please try running the below code snippet to check if TensorFlow is successfully installed
```
import tensorflow as tf
print(tf.reduce_sum(tf.random.normal([1000, 1000])))
``` 

Also, please provide the complete logs if possible so that we can determine the source of the error. Thanks!
