### ISSUE TITLE
erfp1, erfm1 for more accurate results with single/half precision.

### ISSUE THREAD

**Issue by MSusik** [tensorflow/tensorflow#44142]
**System information**
- TensorFlow version (you are using): 2.4.0
- Are you willing to contribute it (Yes/No): Yes.

**Describe the feature and the current behavior/state.**

TF contains an implementation of `erf` function. Sometimes it is desirable to compute a probability of a small interval in a Gaussian, i.e. `P(x - eps < X < x)`. This can be done by using erf: `0.5 * (tf.math.erf(x) - tf.math.erf(x-eps))`. Unfortunately, in case of dealing with smaller precision of floating point numbers (single or half) this computation will often lead to zero, i.e:

```
Input: tf.math.erf(-4)
Output:  <tf.Tensor: shape=(), dtype=float32, numpy=-1.0>
Input: tf.math.erf(-4.1)
Output:  <tf.Tensor: shape=(), dtype=float32, numpy=-1.0>
```
One of the reasons why this happens is probably because of inability of floating point numbers to represent numbers around 1 with a sufficient resolution. I believe the behaviour could be improved if there were two additional functions provided:

`erfp1(x)` - that computes `erf(x) + 1` using an approximation that makes it numerically more accurate for negative x
`erfm1(x)`- that computes `erf(x) - 1` using an approximation that makes it numerically more accurate for positive x

**Will this change the current api? How?**

Just two new functions are added.

**Who will benefit with this feature?**

The developers who work with probabilistic models and need to create differentiable models with `log(P(x - eps < X < x))`

**Any Other info.**
One of the questions that I have is how the approximation is done currently, i.e. what kind of formula is used?

**Comment by TANMOYMAZUMDAR** [comment]
Assign me i want to resolve this issue

**Comment by MSusik** [comment]
So in the end I went with an own implementation of the approximation from Abramowitz and Stegun:

`1-(a_1 * t + a_2 * t^2 + a_3 * t^3) * e^(-x^2)`
where
`t=1/(1+px)`

The good thing is that when I want to compute `log(P(x - eps < X < x))` 1s cancel out, and `e` can be extracted outside of log. Only a special case of x-eps < 0, x>0 has to be handled in another way. From my experiments the computations are numerically stable and they give satisfactory accuracy.

The only disadvantage is that it increases my computational graph that has been already large and it takes a lot of time to compile with XLA. Still, I believe this can be a solution for other people looking to solve the same thing.

**Comment by rmlarsen** [comment]
This is essentially what erfc is for. These could be done through identities:

erf(x) - 1 = - (1 - erf(x)) = -erfc(x)
erf(x) + 1 = -erf(-x) + 1 = 1 - erf(-x) = erfc(-x)
