### ISSUE TITLE
[Q] Graph Transformer API

### ISSUE THREAD

**Issue by rakesh4real** [tensorflow/tensorflow#44147]
When will TFv2 support python graph transforms API so that we can use `from tensorflow.tools.graph_transforms import TransformGraph`

**Comment by ymodak** [comment]
Thanks for your issue. Unfortunately the `Graph Transform Tool` is deprecated intentionally since graphs are not central with TF 2.X way.

**Comment by rakesh4real** [comment]
Hey @ymodak so, is it like Graph Transform Tools will not be added back and if want to optimize models, should I go with other alternative? If yes, what are the best options?

**Comment by ymodak** [comment]
The alternative would be to use `tf.function` to convert your functions into TensorFlow graph.
See https://www.tensorflow.org/guide/function

**Comment by rakesh4real** [comment]
I think I could not convey what I meant exactly. I want to replicate [this noteook available in GCP repo](https://github.com/GoogleCloudPlatform/tf-estimator-tutorials/blob/master/00_Miscellaneous/model_optimisation/Tutorial%20-%20TensorFlow%20Model%20Optimisation%20for%20Serving%20-%20MNIST.ipynb). My doubts are

1. How can I do it with latest tensorflow release? 
2. Should I really consider using optimisations demostrated in the notebook? Are there any downsides to them (as graph transformer tool are deprecated)

**Comment by rakesh4real** [comment]
Hey @ymodak Is it recommended to use Graph Transformer Tool using

```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```

**Comment by ymodak** [comment]
For optimizations such as pruning and quantization you can try [TensorFlow Model Optimization Toolkit](https://www.tensorflow.org/model_optimization/guide).
See https://www.tensorflow.org/model_optimization/guide/pruning/comprehensive_guide
Also `tensorflow.compat.v1`  is the right way to use Graph Transform Tool in TF2. (Note that this feature is out of the support window)

**Comment by rakesh4real** [comment]
Thank you very much @ymodak. Closing the issue.
