### ISSUE TITLE
Report: AutoGraph could not transform, module 'gast' has no attribute 'Index'

### ISSUE THREAD

**Issue by AlexandrParkhomenko** [tensorflow/tensorflow#44146]
**System information**
- source: **https://www.tensorflow.org/tutorials/text/transformer**
- OS Platform: **ArchLinux 5.8.14 x86_64**
- TensorFlow installed from (source or binary): **binary** : https://www.archlinux.org/packages/community/x86_64/tensorflow-cuda/
- TensorFlow version (use command below): **2.3.1** -2
- Python version: **3.8.6**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: **11.1.0** -2 https://www.archlinux.org/packages/community/x86_64/cuda/
- GPU model and memory: GeForce GTX 1660 SUPER computeCapability: 7.5,  22 deviceMemorySize: 5.80GiB

**Describe the current behavior**
```
WARNING:tensorflow:AutoGraph could not transform 
<function train_step at 0x7f15c0790ee0> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, 
set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
```

**Describe the expected behavior**

**Standalone code to reproduce the issue**
python transformer.py

**Other info / logs** Include any logs or source code that would be helpful to
[transformer.zip](https://github.com/tensorflow/tensorflow/files/5402845/transformer.zip)

**Comment by amitport** [comment]
Simple repro:
```python
def temp(x):
  return tf.shape(x)[0]
tf.autograph.to_graph(temp)
```

**Comment by ravikyram** [comment]
I have tried in colab with TF nightly version(`2.4.0-dev20201019`) and was able to reproduce the issue. However i am not seeing any issue with TF version 2.3. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/350c57a4facc1801f0021845c10288b1/untitled472.ipynb#scrollTo=C2tuobhQlZjZ). Thanks!

**Comment by bhack** [comment]
Please check https://github.com/serge-sans-paille/gast/issues/53#issuecomment-712421906

**Comment by bhack** [comment]
In the meantime you can use `pip install gast==0.3.3` with tf-nightly.

**Comment by AlexandrParkhomenko** [comment]
The gast project is mainly used by tensorflow. The latest changes have changed the API.
[https://github.com/serge-sans-paille/gast/commit/ba88fcfd8e1d5962cbd509c03039d76f9d05279b](https://github.com/serge-sans-paille/gast/commit/ba88fcfd8e1d5962cbd509c03039d76f9d05279b)

 We need to put them in Tensorflow.

gast.Index in
tensorflow/python/autograph/converters/slices.py
tensorflow/python/autograph/pyct/qual_names.py
tensorflow/python/autograph/pyct/ast_util.py
tensorflow/python/autograph/pyct/transformer.py
tensorflow/python/eager/gradient_input_output_exclusions.py

Should I do pull request?

**Comment by bhack** [comment]
As I see It was a wrongly updated dependency

**Comment by mdanatg** [comment]
Yep, this should be fixed in tf-nightly. We do need to upgrade TF to gast 0.4, but that should probably be a separate issue.

**Comment by AlexandrParkhomenko** [comment]
https://docs.python.org/3/library/ast.html
Deprecated since version 3.9: Old classes **ast.Index** and **ast.ExtSlice** are still available, but they will be removed in future Python releases. In the meantime, instantiating them will return an instance of a different class.

**Comment by bhack** [comment]
> https://docs.python.org/3/library/ast.html
> Deprecated since version 3.9: Old classes **ast.Index** and **ast.ExtSlice** are still available, but they will be removed in future Python releases. In the meantime, instantiating them will return an instance of a different class.

I think this is a different ticket as the version was already reverted https://github.com/tensorflow/tensorflow/commit/710f3c83b4147eb76e748efcc218325c4978726c. /cc @mihaimaruseac

**Comment by AlexandrParkhomenko** [comment]
> I think this is a different ticket as the version was already reverted [710f3c8](https://github.com/tensorflow/tensorflow/commit/710f3c83b4147eb76e748efcc218325c4978726c). /cc @mihaimaruseac

That's cool. 
The problem is that gast is just a wrapper around the python library.
What will we do when this will not be supported in the next versions of python?

**Comment by AlexandrParkhomenko** [comment]
I dont know. Index is now deprecated: https://github.com/python/cpython/blob/3.9/Lib/ast.py
It's working now, but there should be a plan B

**Comment by mdanatg** [comment]
@AlexandrParkhomenko if I understand your point correctly - this is what gast does - it takes a Python AST and translates it into a format that's independent of the Python version. In a way you can say it backports all changes from older Python versions.

**Comment by AlexandrParkhomenko** [comment]
> @AlexandrParkhomenko if I understand your point correctly - this is what gast does - it takes a Python AST and translates it into a format that's independent of the Python version. In a way you can say it backports all changes from older Python versions.

I may have misunderstood. Can I read a tutorial about gast? With examples of tree construction.

**Comment by mdanatg** [comment]
> Can I read a tutorial about gast? With examples of tree construction.

There is some information and tests with examples on the project site: https://github.com/serge-sans-paille/gast

**Comment by mdanatg** [comment]
We believe this issue is resolved now - please reopen if you still see it in the latest version.

**Comment by AlexandrParkhomenko** [comment]
The problem will be in the future. It doesn't matter now.
