### ISSUE TITLE
Issue running test_hello_world_test on MAC

### ISSUE THREAD

**Issue by KejaPower** [tensorflow/tensorflow#44152]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MAC OS Catalina
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:na
- TensorFlow installed from (source or binary): source
- TensorFlow version:

**Describe the problem**
After cloning tensorflow.git , cd in tensorflow, I'm trying to run the hello_world_test on Mac and get the following error following the gmake command :

tensorflow/lite/micro/tools/make/Makefile:413: warning: overriding recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
tensorflow/lite/micro/tools/make/Makefile:413: warning: ignoring old recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
g++ -std=c++11 -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-unwind-tables -ffunction-sections -fdata-sections -fmessage-length=0 -DTF_LITE_STATIC_MEMORY -DTF_LITE_DISABLE_X86_NEON -O3 -Werror -Wsign-compare -Wdouble-promotion -Wshadow -Wunused-variable -Wmissing-field-initializers -Wunused-function -Wswitch -Wvla -Wall -Wextra -Wstrict-aliasing -Wno-unused-parameter  -I. -Itensorflow/lite/micro/tools/make/downloads/ -Itensorflow/lite/micro/tools/make/downloads/gemmlowp -Itensorflow/lite/micro/tools/make/downloads/flatbuffers/include -Itensorflow/lite/micro/tools/make/downloads/ruy -Itensorflow/lite/micro/tools/make/downloads/kissfft -o tensorflow/lite/micro/tools/make/gen/osx_x86_64/bin/hello_world_test tensorflow/lite/micro/tools/make/gen/osx_x86_64/obj/tensorflow/lite/micro/examples/hello_world/hello_world_test.o tensorflow/lite/micro/tools/make/gen/osx_x86_64/obj/tensorflow/lite/micro/examples/hello_world/model.o tensorflow/lite/micro/tools/make/gen/osx_x86_64/lib/libtensorflow-microlite.a -Wl,--fatal-warnings -Wl,--gc-sections -lm -framework Foundation -framework AudioToolbox
ld: unknown option: --fatal-warnings
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake: *** [tensorflow/lite/micro/examples//hello_world/Makefile.inc:34: tensorflow/lite/micro/tools/make/gen/osx_x86_64/bin/hello_world_test] Error 1

**Provide the exact sequence of commands / steps that you executed before running into the problem**

gmake -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test

**Any other info / logs**
gmake --version
GNU Make 4.3
Built for x86_64-apple-darwin19.2.0

using gmake as my make version is 3.81

**Comment by ymodak** [comment]
Can you please point me to example weblink you are trying? Thanks!

**Comment by KejaPower** [comment]
hello,

I'm following the book chapter 5 p84 , the corresponding github link is  : 

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/hello_world#run-the-tests-on-a-development-machine

on the readme.md file , section :
Run the tests on a development machine 

hope it helps
thanks

**Comment by KejaPower** [comment]
the issue was liked to a directory permission on my local machine which led to warnings with the gitclone command. Once fixed the gmake works just fine.

**Comment by Sehaba95** [comment]
Hello, I have got the same error, @KejaPower could you please share exactly how you solved this issue with some links.
Thank you.

**Comment by KejaPower** [comment]
Hello,
The issue was linked to my directory structure on my MAC so I started the git clone from a different clean directory and then it worked perfectly.
hope it helps
