### ISSUE TITLE
Incompatibility between versions of TF and CUDA dynamic libraries

### ISSUE THREAD

**Issue by gdrolet** [tensorflow/tensorflow#44159]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Enterprise 64 bit, version 10.0.17763
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip install tf-nightly-gpu 
- TensorFlow version: tf-nightly-gpu 2.4.0.dev20201019
- Python version: 3.8.6
- Installed using virtualenv? pip? conda?: Pip (in conda env)
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 11.1/cuDNN 8.4.0.30
- GPU model and memory: NVIDIA Quadro P5000 (16 GB)

**Describe the problem**
I installed MS Visual Studio Community 2019, CUDA (express installation) and, cuDNN, as per the respective instructions.
I created a new conda env with Python 3.8.6 and activated it. I installed tf-nightly-gpu using pip. 
I launched Python and imported tensorflow, then listed GPU devices: all DLLs were found but one (cusolver64). The version of the library looked for by TF is 10 while CUDA 11.1 installs version 11.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

`>>> import tensorflow as tf
2020-10-19 17:17:23.185914: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
>>> tf.config.list_physical_devices('GPU')
2020-10-19 17:17:44.311308: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-10-19 17:17:44.320150: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2020-10-19 17:17:44.361274: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: Quadro P5000 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 16.00GiB deviceMemoryBandwidth: 269.00GiB/s
2020-10-19 17:17:44.373653: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2020-10-19 17:17:44.392056: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2020-10-19 17:17:44.397830: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2020-10-19 17:17:44.407985: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2020-10-19 17:17:44.417194: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2020-10-19 17:17:44.424211: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found
2020-10-19 17:17:44.433236: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2020-10-19 17:17:44.440903: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2020-10-19 17:17:44.445862: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
[]`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gdrolet** [comment]
I installed CUDA 10.2 over 11.1 and the problem seems to be resolved:

```python      
Python 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 18:22:52) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2020-10-19 22:06:00.388483: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
>>> tf.config.list_physical_devices('GPU')
2020-10-19 22:06:07.953857: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-10-19 22:06:07.963030: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2020-10-19 22:06:07.998966: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: Quadro P5000 computeCapability: 6.1
coreClock: 1.7335GHz coreCount: 20 deviceMemorySize: 16.00GiB deviceMemoryBandwidth: 269.00GiB/s
2020-10-19 22:06:08.010311: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2020-10-19 22:06:08.029107: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2020-10-19 22:06:08.036516: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2020-10-19 22:06:08.049843: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2020-10-19 22:06:08.057249: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2020-10-19 22:06:08.068477: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2020-10-19 22:06:08.078004: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2020-10-19 22:06:08.084994: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2020-10-19 22:06:08.089183: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]     
```

**Comment by Saduf2019** [comment]
@gdrolet 
Please move the issue to closed status as it is resolved.

**Comment by mihaimaruseac** [comment]
Closed as resolved

**Comment by Akhilesh64** [comment]
@gdrolet Could you please provide the cusolver64_10.dll file. I have the same issue and will have to download the whole cuda toolkit but I have been facing some bandwidth issues lately. It would be a huge help.

**Comment by gdrolet** [comment]
@Akhilesh64 DLL is here until 11/12/2020:
https://transfert.mffp.gouv.qc.ca/?ShareToken=790B76CF0EBA6B094F39CF985247901B63D4AD19

**Comment by Akhilesh64** [comment]
@gdrolet You're a lifesaver thanks.

**Comment by king398** [comment]
@gdrolet you are a hero man

**Comment by fshofmann** [comment]
While I am thankful for @gdrolet for providing a "solution" I do not like it one bit, because I simply do not understand how this solves the issue, also this is not really a "solution" but an incredible dirty one at best. 

I am using a similar setup as the issue starter, however I am using a RTX 3090, which [*should* be incompatible with CUDA 10 and lower](https://medium.com/@dun.chwong/the-simple-guide-deep-learning-with-rtx-3090-cuda-cudnn-tensorflow-keras-pytorch-e88a2a8249bc). So I installed CUDA 11.1, the latest cuDnn version (all on Windows), switched to python 3.8 and the latest tf-nightly-gpu version. 

I encountered the same issue as the OP, and I thought about the different methods described in similar issues (renaming the \*_11.dll file that to the "10" version, downgrading although that should not work, etc), but then I simply decided to install 10.2 over the newer version. 

**This however WILL change the CUDA_PATH to the 10.2 version instead of the 11.1. The installation that does not have cudnn installed.** In essence, tensorflow should have problems (it is incompatible with the RTX 3000 series GPUs and cudnn is missing). But it still does work. But I tested it with a few simple GAN training loops and everything looks in order. 

So how is this the case? Am I overlooking something? Which of the two versions is actually used?

Also @Saduf2019 do you know when this is actually solved for real, meaning it looks for the correct cusolver64_11.dll instead of the 10 version? This solution is not a clean one and it might cause problems down the line. When you have [blog posts such as that one](https://dobromyslova.medium.com/making-work-tensorflow-with-nvidia-rtx-3090-on-windows-10-7a38e8e582bf) struggling with TF on RTX 3000, one gets worried that their models and computations are not 100% correct or might produce giberish.

**Comment by linuxmaster0312** [comment]
I noticed that the cusolver64_10.dll file transfer expired. Can you repost it @gdrolet?

**Comment by fshofmann** [comment]
@linuxmaster0312 here you go:

 https://drive.google.com/file/d/1-3Yk-QZ1eUta1T40BaxFpO4uyn7BPU4o

**Comment by jd1378** [comment]
for other people who may come across this and have v11 installed, I know it may not be a good solution but making a copy of cusolver64_11.dll and renaming it to cusolver64_10.dll seems to be working fine for me.

**Comment by linuxmaster0312** [comment]
@jd1378  are you able to use tensorflow normally with your gpu?

**Comment by jd1378** [comment]
no, it seems it was only working with a limited case, tried with another and it throws error. don't use it

**Comment by astrowonk** [comment]
Tried the cusolver64_10.dll  workaround which allowed me to import tensorflow nightly gpu and the system recognizes my GPu, but trying to run through the simple train_and_evaluate example notebook crashes with:

```InternalError:  Blas xGEMM launch failed : a.shape=[1,64,784], b.shape=[1,784,64], m=64, n=64, k=784
	 [[node model/dense_1/MatMul (defined at <ipython-input-6-69417c50baa2>:2) ]] [Op:__inference_train_function_706]

Function call stack:
train_function
```

and in the jupyter console:
``` Successfully opened dynamic library cublas64_11.dll
2020-11-26 11:02:59.365169: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2020-11-26 11:02:59.365208: W tensorflow/stream_executor/stream.cc:1455] attempting to perform BLAS operation using StreamExecutor without BLAS support
[I 11:03:15.022 NotebookApp] Saving file at /Tensorflow/train_and_evaluate.ipynb
```

This is a 3070 with cuda 11.1 and the tensorflow-nightly-gpu from pip (windows 10, python 3.8)

**Comment by king398** [comment]
@astrowonk add this after importing all the libraries in you code
`physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)`

**Comment by pkanwar23** [comment]
For folks trying to use cuda 11.1, we recommend sticking to CUDA 11.0. That's the version we've built & tested against.

**Comment by astrowonk** [comment]
> For folks trying to use cuda 11.1, we recommend sticking to CUDA 11.0. That's the version we've built & tested against.

 CUDA 10 is too old for the latest Ampere cards, no? I was trying to test running on a gpu with a 3070.

**Comment by king398** [comment]
@pkanwar23 that is not fully compatible  with rtx 30

**Comment by Saduf2019** [comment]
@gdrolet 
Please update if this is still an issue

**Comment by Kemmuli** [comment]
@Saduf2019 The issue still persists.

**Comment by carlosscmx** [comment]
I installed CUDA 11.2 and its respective cuDNN. When running:
`import tensorflow as tf
tf.config.list_physical_devices('GPU')`
The .dll that is missing is cusolver64_10.dll. The CUDA installation doesn't have that .dll, it only has the *_11.dll. What I did was install the CUDA 10.2, leaving my CUDA_PATH pointing to my 11.2 installation and copied the file 'cusolver64_10.dll' from my CUDA 10.2 installation path; Which on Windows could be "%USERPROFILE%/Program files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/bin/". 

I'm not sure this solution is optimal, in the sense that would break things in your programs or models.

I would like to know if this solves your problem and is a good solution that won't break things.

**Comment by fshofmann** [comment]
@carlosscmx This should work. I did it in a similar way. My models (using custom training loops / steps) worked fine as well, nothing of note was encountered.

**Comment by enzomarra** [comment]
Exactly the same issue, haven't been able to try @carlosscmx  workaround.
CUDA 11.2 
cuDNN 8.  (tried a few)
Tensorflow 2.4

**Comment by evgenynazarchuk** [comment]
I have  Windows 10 x64, CUDA 11.2, cuDNN 8, Tensorflow 2.4
I also have some problem
I solved it with copied file cusolver64_10.dll into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin

**Comment by rjghendrikx** [comment]
Thanks @fshofmann copying the cusolver64_10.dll into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin instantly solved it for me as well (without installing the dev version of tf-nightly gpu)

**Comment by mehrdadfazli** [comment]
> For folks trying to use cuda 11.1, we recommend sticking to CUDA 11.0. That's the version we've built & tested against.

I have a windows machine and tried to download CUDA 11.0 and CUDA 11.0-updated but the download links are broken (I could not download any of them). That is why I had to install CUDA 11.1 instead and I ran into the same issue as the others here.

**Comment by sanjoy** [comment]
> I have a windows machine and tried to download CUDA 11.0 and CUDA 11.0-updated but the download links are broken (I could not download any of them).

Can you reach out to NVIDIA about this?  CC @nluehr

**Comment by Soester10** [comment]
> @Akhilesh64 DLL is here until 11/12/2020:
> https://transfert.mffp.gouv.qc.ca/?ShareToken=790B76CF0EBA6B094F39CF985247901B63D4AD19

Hi, could you please share the dll?

**Comment by NoahCSHN** [comment]
> While I am thankful for @gdrolet for providing a "solution" I do not like it one bit, because I simply do not understand how this solves the issue, also this is not really a "solution" but an incredible dirty one at best.
> 
> I am using a similar setup as the issue starter, however I am using a RTX 3090, which [_should_ be incompatible with CUDA 10 and lower](https://medium.com/@dun.chwong/the-simple-guide-deep-learning-with-rtx-3090-cuda-cudnn-tensorflow-keras-pytorch-e88a2a8249bc). So I installed CUDA 11.1, the latest cuDnn version (all on Windows), switched to python 3.8 and the latest tf-nightly-gpu version (from today. November 10th).
> 
> I encountered the same issue as the OP, and I thought about the different methods described in similar issues (renaming the *_11.dll file that to the "10" version, downgrading although that should not work, etc), but then I simply decided to install 10.2 over the newer version.
> 
> **This however WILL change the CUDA_PATH to the 10.2 version instead of the 11.1. The installation that does not have cudnn installed.** In essence, tensorflow should have problems (it is incompatible with the RTX 3000 series GPUs and cudnn is missing). But it still does work. But I tested it with a few simple GAN training loops and everything looks in order. I did some testing (deleting the DLLs that need to be loaded, sometimes from cuda 11, sometimes from version 10), because I know nothing about how loads the necessary dlls and because I thought the CUDA_PATH matters. Interestingly it does not. My TF installation still loads the DLLs from CUDA 11.1 (CUDA_PATH_V11.1) and then automatically goes into the 10.2 folder (CUDA_PATH_V10.2) to load the solver DLL.
> 
> For my own sanity's sake, I set the (normal) CUDA_PATH to version 11.1 because I am afraid other tools I use might use the wrong version.
> 
> Also @Saduf2019 do you know when this is actually solved for real, meaning it looks for the correct cusolver64_11.dll instead of the 10 version? This solution is not a clean one and it might cause problems down the line. When you have [blog posts such as that one](https://dobromyslova.medium.com/making-work-tensorflow-with-nvidia-rtx-3090-on-windows-10-7a38e8e582bf) struggling with TF on RTX 3000, one gets worried that their models and computations are not 100% correct or might produce giberish.

Have you tried to train you model under this configuration? Does this works fine?

**Comment by SheshankJoshi** [comment]
@NoahCSHN I faced the same issue and my models are pretty good. I can testify for that. I came looking for the issue everywhere. Whatever works, if it works its fine. Thanks to everyone.

**Comment by fshofmann** [comment]
@NoahCSHN Sorry for the *very* late reply (github issue notifications get easily buried in the inbox), but for other readers sake I can very much confirm that is does work indeed fine [(as mentioned 4 months ago)](https://github.com/tensorflow/tensorflow/issues/44159#issuecomment-749482971). Since last year I've done extensive evaluations of some of my models that were build using the sequential and functional keras API (custom training loops, my subclassed custom models were a mess due to other reasons) and the results do match what I expected.

At the moment I am a bit out of the loop when it comes to this issue, but I sure hope that we will get a clean solution this year :)

**Comment by tfgstudios** [comment]
any updates? it's been 2 years after all. proposed solutions are better than nothing, but their hackiness level is not on par with the prestige TF+NVIDIA have in the ML world
