### ISSUE TITLE
bool disable_per_channel: per-channel vs. per-layer quantization

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#44153]
I want to switch the quantization scheme to either per-tensor or per-channel quantization e.g. [disable_per_channel](https://github.com/tensorflow/tensorflow/blob/762df3454fa85fa0b842fcf1a08429d093835bc5/tensorflow/compiler/mlir/lite/quantization/quantization_config.h#L53) set as true (no quantization per-channel) within from [quantization_config.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/lite/quantization/quantization_config.h)
```
  // When set to true, quantization will be done per-tensor. Currently, this
  // option is only valid when the quantization parameters need to be created by
  // scanning the constant content (post-training quantization or QAT without
  // weight FakeQuant).
  bool disable_per_channel = false;

```

Do you have any example to switch between either per-channel or per-layer quantization with [Python API](https://www.tensorflow.org/lite/convert#python_api) or [Command Line Tool](https://www.tensorflow.org/lite/convert#cmdline) call?

Is it possible somehow to use [`mlir_quantize`](https://github.com/tensorflow/tensorflow/blob/2396803aa12cff02dbc0aaad05c7614a4976843f/tensorflow/lite/python/convert.py#L126) function, if so, how?

**Comment by gowthamkpr** [comment]
@peter197321 Please take a look at this [doc](https://www.tensorflow.org/lite/performance/quantization_spec) which goes through [per tensor](https://www.tensorflow.org/lite/performance/quantization_spec#per-axis_vs_per-tensor) quantization as well as per layer quantization.
