### ISSUE TITLE
Can't allocate specific number of CPU threads when executing in graph mode

### ISSUE THREAD

**Issue by daniel-merrick** [tensorflow/tensorflow#44157]
I'm working on some benchmarking code to determine FPS depending on number of CPU cores. It seems like it isn't possible to select a certain number of CPU threads when running inference in graph mode. I can, however, select a specific number of threads when running inference with eager execution. I confirm this by running the script in the background and watching CPU allocation with 'htop' or 'top.'

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.5 LTS 
- TensorFlow installed from (source or binary): pip 20.2.3
- TensorFlow version (use command below): v2.3.0-54-gfcc4b966f1 2.3.1
- Python version: Python 3.6.9
- CUDA/cuDNN version: release 9.0, V9.0.176
- GPU model and memory: N/A
- CPU Model: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz, 

**Describe the current behavior**
When running in graph execution, only a single CPU core is being used (according to htop) regardless of how many threads I choose. I would expect a higher FPS when more threads are selected, however, I get the same FPS whenever eager mode is disabled. I believe graph execution is ignoring the thread variables. When running in eager execution, the correct number of threads are being used. I get different FPS for different numbers of threads.

**Describe the expected behavior**
When running in graph execution, I expect the script to use as many threads as I explicitly tell it to use. Further, I would expect to see a change in FPS when selecting a different number of threads.

**Standalone code to reproduce the issue**

<pre><code>import tensorflow as tf
import numpy as np
import time

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

ITERATIONS = 100
BATCH_SIZE = 1
INTER_THREADS = 1
INTRA_THREADS = 1

"Comment for eager execution (graph mode). Uncomment for Graph mode."
tf.compat.v1.disable_eager_execution()

tf.config.threading.set_inter_op_parallelism_threads(INTER_THREADS)
tf.config.threading.set_intra_op_parallelism_threads(INTRA_THREADS)

@tf.function
def inference(net, input_data):
    return net(input_data, training=False)

model = tf.keras.applications.ResNet50(weights=None, classes=10)
dummy_batch = tf.random.uniform([BATCH_SIZE,224,224,3], dtype=tf.dtypes.float32)

i = 0
time_spent = np.zeros(ITERATIONS)
while (i < ITERATIONS + 1):
  if i != 0:
       "clocking inference speeds"
       start_time = time.time()
       _ = inference(model, dummy_batch)
       time_spent[i-1] = time.time() - start_time
  else:
       "warm up cpu / gpu"
       while(i < 50):
           _ = inference(model, dummy_batch)
           i+=1
       i = 0
  i += 1

fps = (len(time_spent) * BATCH_SIZE) / np.sum(time_spent)
print("FPS: {}".format(fps))
</code></pre>

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Output with eager execution disabled 1 inter thread, 1 intra thread
FPS: 162.246247505461

**Output with eager execution disabled 1 inter thread, 2 intra thread
FPS: 162.3569705471583

**Output with eager execution enabled 1 inter thread, 1 intra thread
FPS: 10.065427737674705

**Output with eager execution enabled 1 inter thread, 2 intra thread
FPS: 17.2407394877956

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3 ,nightly version (`2.4.0-dev20201019`) and was able to reproduce the issue.Please, find the gist in [graph mode](https://colab.research.google.com/gist/ravikyram/8bbcf4a68ad40cdccbc5645ef2a2829c/untitled470.ipynb),[eager mode](https://colab.research.google.com/gist/ravikyram/ee983fe7b6605c41059d5f741a0e743e/untitled471.ipynb) here.
Thanks!

**Comment by nikitamaia** [comment]
Hi @daniel-merrick, in TF2 you leverage graph mode by enabling tf.function and not by disabling eager execution. `tf.compat.v1.disable_eager_execution()` enables legacy graph mode, which you should not do unless you are doing something very specific with TF1 compat code that requires legacy graph.

In the code sample you have provided, if you comment out `tf.compat.v1.disable_eager_execution()` then you are running in graph mode because you are making use of tf.function.

**Comment by daniel-merrick** [comment]
Ah, thank you for the clarification! I still have a few questions though.

What is the explanation for the FPS difference, then? When I don't have tf.compat.v1.disable_eager_execution() commented in the above code, is this similar to running in TF1 (in regard to performance)?

and

If I wanted to benchmark using legacy graph mode, the problem still exists that the threading isn't being properly respected, right?

**Comment by nikitamaia** [comment]
I'm not sure you would want to benchmark with the legacy graph mode, since using `@tf.function` is the recommended way to leverage graphs in TF2. So yes commenting out `tf.compat.v1.disable_eager_execution()` and then using `tf.function` is similar to running in TF1. Something else to keep in mind is that when using the Keras API, model.predict() manages `tf.function` for you automatically under the hood.
