### ISSUE TITLE
Ragged arange?

### ISSUE THREAD

**Issue by tgsmith61591** [tensorflow/tensorflow#44164]
I am sorry in advance if a solution for this exists. I am wondering if there is a way to create a ragged `arange` along the axis of an existing ragged tensor?

For instance, imagine I have an arbitrarily nested ragged tensor `x` I need to perform masking on. Something like:

```python
x = tf.ragged.constant([
    [[12, 9], [5]],
    [[10], [6, 8], [42]],
])
```

The easiest way for me to mask will be by index of an element. Is there a way to get a ragged arange with the same row lengths/splits like:

```python
x = tf.ragged.constant([
    [[0, 1], [2]],
    [[0], [1, 2], [3]],
])
```

It would be really cool to be able to do something like `tf.ragged.arange_along_axis(x, axis=2)` to get something like this.

**Comment by edloper** [comment]
For a rank-2 ragged tensor (like you have in your example), you can use:

```python
tf.ragged.range(x.row_lengths())
```

If you have a higher-rank ragged tensor and want to specify the axis, you could use something like this:

```python
tf.ragged.map_flat_values(tf.ragged.range, x.row_lengths(axis=2))
```

E.g., the following snippet:

```python
x = tf.ragged.constant([
    [ [[12, 9], [5]], 
      [[10], [20]]         ],
    [ [[10], [6, 8], [42]] ],
])

for axis in range(1, 4):
  print('axis', axis)
  print(tf.ragged.map_flat_values(tf.ragged.range, x.row_lengths(axis=axis)))
```

prints:

```
axis 1
<tf.RaggedTensor [[0, 1], [0]]>
axis 2
<tf.RaggedTensor [[[0, 1], [0, 1]], [[0, 1, 2]]]>
axis 3
<tf.RaggedTensor [[[[0, 1], [0]], [[0], [0]]], [[[0], [0, 1], [0]]]]>
```

**Comment by tgsmith61591** [comment]
Hey thanks for the response. This is helpful, although it doesn't _quite_ solve what I'm after. The desired output for rank 3 would be:

```python
<tf.RaggedTensor [[[[0, 1], [2]], [[3], [4]]], [[[0], [1, 2], [3]]]]>
```

So the arange would populate elements on axis 3, but would need to increment along axis 2, if that makes any sense. Again, I appreciate your response.

**Comment by tgsmith61591** [comment]
Actually I think I found a way to do this.

```python
x = tf.ragged.constant([
    [[12, 9], [5]],
    [[10], [6, 8], [42]],
])

x_2d = x.merge_dims(inner_axis=-1, outer_axis=1)
arange_2d = tf.ragged.range(x_2d.row_lengths())
arange_nd = tf.RaggedTensor.from_nested_row_lengths(
    arange_2d.flat_values,
    x.nested_row_lengths(),
)

>>> arange_nd
<tf.RaggedTensor [[[0, 1], [2]], [[0], [1, 2], [3]]]>
```

Although I have no idea how expensive the merge operation is if it's used solely for this masking purpose.

**Comment by edloper** [comment]
That should be possible to do as well, though it's a little trickier.  Here's some code to get you started:

```
x = tf.ragged.constant([
    [[[12, 9], [5]], 
     [[10], [20]]],
    [[[10], [6, 8], [42]]],
])

# Flatten all but the outermost dimension of x.
x_flat = x.merge_dims(1, -1)

# Get the number of scalar values in each row of x
x_row_sizes = x_flat.row_lengths()

# Build a list of indices, corresponding 1:1 with the flat_valeus of `x`.
indices = tf.ragged.range(x_flat.row_lengths()).values

# Replace x's values with the computed indices.
x.with_flat_values(indices)
```

**Comment by edloper** [comment]
Looks like we came up with near-identical solutions within ~15 seconds of one another.  Looks good to me. :)

**Comment by tgsmith61591** [comment]
Thanks again for all your help. Your solution exposed me to some interesting behaviors in the ragged API with which I was not familiar!
