### ISSUE TITLE
cpu cores not fully utilized causing gpu bottleneck

### ISSUE THREAD

**Issue by Vikas-kum** [tensorflow/tensorflow#44162]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Hi, I am finding that when running a step, only 3 out of 8 cpu cores are pegged at 100 percent and gpu is underutilized at 50 or 60 pct. other 5 cpu cores are at 0 pct. I am assuming that this may be causing cpu bottleneck in my model. 
I also see during backward process, one of compute process seems to run entire backward op (with tf profiler) but i see 3 cores getting utilized. 
I have tried setting these config but i don't see much benefit. Any pointers to if there is any config can utilize to provide more cpu parallelism.
num_threads = 8
tf.config.threading.set_inter_op_parallelism_threads(2*num_threads)
tf.config.threading.set_intra_op_parallelism_threads(2*num_threads)
As you see in below image there are lagger compute node where i see only 3 cores getting utilized and underutilized gpu. 

Also seems like lagger Execute::process correponds to backward pass as i see Adam operator running for timeframe.

<img width="1177" alt="Screen Shot 2020-10-19 at 5 32 24 PM" src="https://user-images.githubusercontent.com/1817689/96525925-1a5e0980-1231-11eb-980b-69fc66f12b17.png">

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@Vikas-kum 
Can you please let us know the tf version on which the issue is faced.

**Comment by Vikas-kum** [comment]
> @Vikas-kum
> Can you please let us know the tf version on which the issue is faced.

Tf 2.3 . 
I think the  operations especially tf.where calls are not using all cores and that is causing slowness. Is there a way to parralelize these calls?

**Comment by Vikas-kum** [comment]
> > @Vikas-kum
> > Can you please let us know the tf version on which the issue is faced.
> 
> Tf 2.3 .
> I think the operations especially tf.where calls seems to be not using all cores and that is causing cpu bottleneck. Is there a way to parallelize these calls over all cores?
@Saduf2019 my bad, actually its tf 2.2 . sorry for confusion.

**Comment by jvishnuvardhan** [comment]
@Vikas-kum Can you please try `tf-nightly` and let us know whether this is an issue even with latest `tf-nightly`? Thanks!

**Comment by chunduriv** [comment]
@Vikas-kum, Sorry for late response.

Is this still an issue? Could you please try with `TF v2.8.0` and let us know if it is resolved? Thanks!
