### ISSUE TITLE
Normalization.adapt() not working on tf.data.Dataset()

### ISSUE THREAD

**Issue by palatos** [tensorflow/tensorflow#44160]
- TensorFlow version: 2.3.0
- Python version: 3.7.6

I am trying to use Normalization within my image classification model [ 224x224x3 shaped images, 2 classes with categorical (one hot) labels]. I have built a tf.data.Dataset through the tf.keras.preprocessing.image_dataset_from_directory() function.
Calling the element_spec() method on the resulting dataset results in:

`(TensorSpec(shape=(None, 224, 224, 3), dtype=tf.float32, name=None),
 TensorSpec(shape=(None, 2), dtype=tf.float32, name=None))`

Which is consistent with what I want. However upon using Normalization.adapt() on this Dataset I get the following error:

`ValueError: as_list() is not defined on an unknown TensorShape.`

I couldn't find the solution to this anywhere. Any help is deeply appreciated. If I understand correctly from the documentation the adapt() method should be able to take tf.data.Datasets as inputs, right?

**Comment by bhack** [comment]
Do you have a very minimal but runnable (copy, paste and run) example to reproduce this?

**Comment by palatos** [comment]
Sure! Here you go. This code should reproduce the issue entirely. I just created a sample dataset of np.ones in the same shape of my data:

`import numpy as np
import tensorflow as tf
from tensorflow.keras.layers.experimental import preprocessing


sample_dataset = tf.data.Dataset.from_tensor_slices((np.ones((425, 224, 224, 3)), np.ones((425, 2))))
normalizer = preprocessing.Normalization()
normalizer.adapt(sample_dataset)`

**Comment by bhack** [comment]
I think that you need to use something like:
```
feature_ds = sample_dataset.map(lambda x, y: x)
normalizer = preprocessing.Normalization()
normalizer.adapt(feature_ds)
```

**Comment by palatos** [comment]
This solved the problem! Thank you so much.
Maybe this could be added to the documentation at https://www.tensorflow.org/api_docs/python/tf/keras/layers/experimental/preprocessing/Normalization ?
I'm not sure why the map step is necessary, but in either case it does solve the issue. Thanks once again!

**Comment by bhack** [comment]
> This solved the problem! Thank you so much.
> Maybe this could be added to the documentation at https://www.tensorflow.org/api_docs/python/tf/keras/layers/experimental/preprocessing/Normalization ?
> I'm not sure why the map step is necessary, but in either case it does solve the issue. Thanks once again!

Can you open a new documentation issue? I think that probably we could also raise an exception.

**Comment by MarkDaoust** [comment]
> I'm not sure why the map step is necessary,

Because you're passing a pair of tensors. The normalization layer doesn't want to guess which tensor's statistics you're trying to extract.

> Can you open a new documentation issue? I think that probably we could also raise an exception.
> /cc @MarkDaoust What do you think?

I think it should just throw a clearer error. I think I've got a fix.

**Comment by KaleabTessera** [comment]
If you data that is not 1d, i.e. image data, then this works:
```
x_shape = sample_dataset.element_spec[0].shape
feature_ds = sample_dataset.map(lambda x, y: tf.reshape(x, x_shape))
normalizer = preprocessing.Normalization()
normalizer.adapt(feature_ds)
```

**Comment by linWujl** [comment]
Preprocessing layers take long time to adapt the entire dataset, is there any solutions? thanks!
