### ISSUE TITLE
ctc_loss generate different value between sparse label and dense label

### ISSUE THREAD

**Issue by wb-finalking** [tensorflow/tensorflow#44177]
With tensorflow 1.15, I get different value when using sparse tensor and dense tensor as labels separately. Is there something wrong with my code? I also use tensorflow 2.x to verf this and get the same result. The two different usage would get different vaule.
```
import numpy as np
import tensorflow as tf

# params
batch_size = 3
seq_len = 15
label_len = 12
num_class = 20

# construct input
indices = np.array([[0, 0], [0, 4], [1, 9], [2, 5]], dtype=np.int64)
values = np.array([1, 1, 1, 1], dtype=np.int64)
shape = np.array([batch_size, label_len], dtype=np.int64) 
tensor = tf.SparseTensor(indices, values, shape)
tensor = tf.cast(tensor, tf.int32)
# generate label
logit = tf.random.uniform([seq_len,batch_size,num_class], dtype=tf.float32)

# two diffenret loss
loss_1 = tf.reduce_mean(
    tf.nn.ctc_loss(
        labels=tensor, inputs=logit,
        sequence_length=seq_len * np.ones(batch_size)
    ),
    name='ctc_loss1'
)
loss_2 = tf.reduce_mean(
    tf.nn.ctc_loss_v2(
        labels=tf.sparse_tensor_to_dense(tensor, default_value=num_class-1),
        logits=logit,
        logit_length=seq_len * np.ones(batch_size, dtype=np.int32),
        label_length=label_len * np.ones(batch_size, dtype=np.int32),
        blank_index=num_class-1
    ),
    name='ctc_loss2'
)

# run
sess = tf.compat.v1.Session()
print(sess.run([loss_1, loss_2]))
# output is : [39.27905, 740.8396]
```

**Comment by ravikyram** [comment]
I have tried in colab with with TF 1.15 and was able to reproduce the issue. I am getting the below error message with TF 2.x. (`TypeError: ctc_loss_v3() got an unexpected keyword argument 'inputs'`)Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/3c87880e9c8f2ad7eb7dbf045a548844/untitled.ipynb).Thanks!

**Comment by wb-finalking** [comment]
> I have tried in colab with with TF 1.15 and was able to reproduce the issue. I am getting the below error message with TF 2.x. (`TypeError: ctc_loss_v3() got an unexpected keyword argument 'inputs'`)Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/3c87880e9c8f2ad7eb7dbf045a548844/untitled.ipynb).Thanks!

The api has changed the inputs to logits. So you shuold make some changes correspondingly.

**Comment by Saduf2019** [comment]
@wb-finalking 
Please use 2.x and let us know if there are any issues as there is no support for 1.x.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by N-damo** [comment]
miss the same problem,exspecially in blank label=0
