### ISSUE TITLE
Missing compiler flags for some Cortex-M target architectures

### ISSUE THREAD

**Issue by advaitjain** [tensorflow/tensorflow#44170]
@tensorflow/micro

Exact reproduction steps can not be shared here since they rely on internal systems. However, it is very likely that the specific problem that I am seeing can be reproduced on a sparkfun edge as well.

High level steps:

 1. Generated a static lib for an M4F with:
     ```
     make -f tensorflow/lite/micro/tools/make/Makefile -j8 TARGET=cortex_m_generic TARGET_ARCH=cortex-m4+fp TAGS=cmsis-nn microlite
    ```
 1. Link into a binary and then attempt to run the binary (in my case via qemu)

 1. qemu gives an error like this:
    ```
    qemu: uncaught target signal 4 (Illegal instruction) - core dumped
    ```

In this case I isolated the problem to a missing

```TARGET_SPECIFIC_FLAGS += -D__FPU_PRESENT=1 -mfpu=fpv4-sp-d16```.

More generally, it seems like there might be such omissions for the other target architectures as well.

@mansnils @freddan80 would you be willing to set the correct flags for both arm-gcc and armclang for all the target architectures?

**Comment by freddan80** [comment]
@advaitjain thanks for looking into this. we're trying to clarify this with out compiler experts

**Comment by freddan80** [comment]
tagging @mansnils @felix-johnny

**Comment by mansnils** [comment]
@advaitjain It seems GCC7 does not add FP capabilities to CPU, not by default nor can you use extensions. Our goal is to update GCC to version x.y.z once we have verified it to be working.

**Comment by ml-0** [comment]
@advaitjain May I ask out of curiosity : Do you simulate TFLM on a Cortex-M4 + FPU in Qemu? If so, which version of Qemu and which machine model are you using?

**Comment by pkgoogle** [comment]
Hi @advaitjain, It seems like the PR Is merged is this issue complete?
