### ISSUE TITLE
Deprecation warnings Model.state_updates and layer.updates when saving model

### ISSUE THREAD

**Issue by Molkree** [tensorflow/tensorflow#44178]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): happens on 2.3.1 (v2.3.0-54-gfcc4b966f1) and 2.4.0-dev20201020 (v1.12.1-44160-g72c19e8880)
- Python version: 3.6.9

**Describe the current behavior**
Getting two deprecation warnings when saving a model (with default parameters).
```
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:2334: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`Model.state_updates` will be removed in a future version. '
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py:1397: UserWarning: `layer.updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`layer.updates` will be removed in a future version. '
```

**Describe the expected behavior**
No warnings!

**Standalone code to reproduce the issue**
```
import tensorflow as tf
from tensorflow import keras

model = keras.models.Sequential([
  keras.layers.Dense(1, input_shape=(1,)),
])

model.save('my_model')
```
[Colab](https://colab.research.google.com/drive/1tAx3zIJ9fKzpjitXmIhebxL_UkeFLidM?usp=sharing)

**Comment by Saduf2019** [comment]
@Molkree 
I ran the code shared, these are just depreciation warnings, nothing to worry about they will not affect your performance..
To hide the warnings please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/27023#issuecomment-475684266) and let us know.

**Comment by Molkree** [comment]
I know that they are "just" deprecation warnings, however calling non deprecated method `save` on model and getting these warnings is weird to say the least. It means that `save` calls deprecated functions somewhere, shouldn't it be corrected? These warnings are here exactly for this reason, to remind us to replace code with something else (or just remove calls as warnings suggest that it's called automatically now) instead of just silencing all warnings.

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/82be60a30e3631dff4a7dda8037626c6/untitled452.ipynb) on tf-nightly [2.4.0-dev20201022].

**Comment by jvishnuvardhan** [comment]
@Molkree Agree with you. Thanks for raising this issue. We will work on removing those warnings. Thanks again.

**Comment by goldiegadde** [comment]
@Molkree This issue has been fixed in the latest nightly and the fix has been cherrypicked into the r2.4 branch. I am goign to close this bug, feel free to re-open if you think this is not fixed.
