### ISSUE TITLE
File system scheme 'gs' not implemented

### ISSUE THREAD

**Issue by gante** [tensorflow/tensorflow#44179]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.4 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: --
- TensorFlow installed from (source or binary): source
- TensorFlow version: [2.3.1](https://github.com/tensorflow/tensorflow/releases/tag/v2.3.1)
- Python version: 3.7.5
- Installed using virtualenv? pip? conda?: pip (in virtualenv)
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: 10.2 / 7.6.5
- GPU model and memory: Tesla P100, 16GB

**Describe the problem**

Using `tensorflow.io.gfile.GFile` with the GCS filesystem results in `tensorflow.python.framework.errors_impl.UnimplementedError: File system scheme 'gs' not implemented`, but only if TF is compiled from source. Using the vanilla `pip install tensorflow==2.3.1` yields no errors.

To clarify how the TF wheel was built, in the `./configure` step I've used all default options except for CUDA support. When building the pip package, I ran `bazel build --config=cuda --config=monolithic --config=v2 //tensorflow/tools/pip_package:build_pip_package`.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Running
```
import tensorflow as tf

with tf.io.gfile.GFile('gs://foo', mode='w') as bar:
	bar.write('baz')
```

Yields
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/joao/py_3_7/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 101, in write
    self._prewrite_check()
  File "/home/joao/py_3_7/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 87, in _prewrite_check
    compat.as_bytes(self.__name), compat.as_bytes(self.__mode))
tensorflow.python.framework.errors_impl.UnimplementedError: File system scheme 'gs' not implemented (file: 'gs://foo')
```

**Any other info / logs**
1. It seems like this issue is related to [this](https://github.com/tensorflow/tensorflow/issues/38477#issuecomment-657929334) comment. A few comments below it was [suggested](https://github.com/tensorflow/tensorflow/issues/38477#issuecomment-659069010) to build the gcs plugin separately, but I was unable to complete that step (no `gcs_file_system.dll` found);
2. This issue was reproduced on a different machine, with everything equal except the GPUs (GTX1080 8GB and Titan X 12GB);
3. The example above is a dummy GCS path, but the error is the same when a previously working path is given.

Thanks :)

**Comment by vnvo2409** [comment]
I believe the option `--config=monolithic` is the issue here. I think this PR should fix the problem but it doesn't. However, this PR could give you more insight why the `--config=monolithic` failed. https://github.com/tensorflow/tensorflow/pull/43594

**Comment by gante** [comment]
> I believe the option `--config=monolithic` is the issue here. I think this PR should fix the problem but it doesn't. However, this PR could give you more insight why the `--config=monolithic` failed. #43594
> 
> I don't remember extractly but I think one of `tf.io` or `tf.io.gfile` should work with `--config=monolithic`. Could you try `tf.io.read_file` and tell me the result ?

Interesting! Can confirm that `tf.io.read_file()` works fine. Similarly, `tf.io.write_file()` can also write into GCS. So it seems like the problem is restricted to `tf.io.gfile` -- I'm building without `--config=monolithic`, and I'll post results here soon.

**Comment by gante** [comment]
@vnvo2409 just as you wrote, building without `--config=monolithic` makes everything work 👍 

Perhaps a noob question: what are the main advantages of using `--config=monolithic`?

**Comment by vnvo2409** [comment]
> what are the main advantages of using `--config=monolithic` ?

I am not sure about it but we have to use `--config=monolithic` on Windows because building and linking `dll` on Windows is not trivial. `--config=monolithic` will build everything into one lib. In other OS, we don't enable this option. So I think the main advantages of using `--config=monolithic` is the same as the advantages of static linking over dynamic linking ( easier to link,  easier to distribute the binary, faster because we only have to link once, etc )

**Comment by vnvo2409** [comment]
@gante 
Just to confirm. You built TF with #43594 was merged or not yet ?
And could you close the issue if everthing is ok, please ?

**Comment by gante** [comment]
> @gante
> Just to confirm. You built TF with #43594 was merged or not yet ?
> And could you close the issue if everthing is ok, please ?

A working solution can be obtained by building without `--config=monolithic` on release tag v2.3.1. I haven't tested building with #43594.
