### ISSUE TITLE
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by ShuojinHang** [tensorflow/tensorflow#44181]
hi, 
I was trying to run:

**_make -f tensorflow/lite/micro/tools/make/makefile test_hello_world_test_**

and had an error: **clang: error: linker command failed with exit code 1 (use -v to see invocation)**

Using make to build other source files gave me the same error. I'm using macOSX Catalina 10.15.7

Cheers

@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- Tensorflow version (commit SHA if source):
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):

**Describe the problem**

**Please provide the exact sequence of commands/steps when you ran into the problem**

**Comment by ravikyram** [comment]
@ShuojinHang 

Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by advaitjain** [comment]
https://github.com/tensorflow/tensorflow/pull/44196 should fix the issue, and will close this bug. Please reopen if that does not work.

**Comment by ShuojinHang** [comment]
Yes, it worked.
