### ISSUE TITLE
error occurred when i loaded a model contain TextVectorization layer

### ISSUE THREAD

**Issue by Clover0315** [tensorflow/tensorflow#44199]
**System information**
- TensorFlow version:  2.3.1

**error message**

**RuntimeError: Unable to restore a layer of class TextVectorization. Layers of class TextVectorization require that the class be provided to the model loading code, either by registering the class using @keras.utils.register_keras_serializable on the class def and including that file in your program, or by passing the class in a keras.utils.CustomObjectScope that wraps this load call.**

**Standalone code to reproduce the issue** 
i built a model like below:
```
model = tf.keras.Sequential([
   tf.keras.Input(shape=(1,), dtype=tf.string),
   vectorize_layer(a TextVectorization layer that has adapt),
   layers.Embedding(max_features + 1, embedding_dim),
   layers.Dropout(0.2),
   layers.GlobalAveragePooling1D(),
   layers.Dropout(0.2),
   layers.Dense(1),
  layers.Activation('sigmoid')
])
```

and i saved model like this:
`model.save('./model/basic-text-class-export', save_format='tf')`

but when i loaded model like below, i got a error as shown before
`model = tf.keras.models.load_model('./model/basic-text-class-export')`

how can i do next?
best wishes for you

**Comment by amahendrakar** [comment]
@Clover0315,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by Clover0315** [comment]
thanks for your answer！
i just copyed  the code from https://tensorflow.google.cn/tutorials/keras/text_classification, and added some code at the end and then got the error shown before: 
```
export_model.save('./model/test/basic-text-class-export', save_format='tf')

# load model
loaded_model = tf.keras.models.load_model('./model/test/basic-text-class-export')
print(loaded_model.summary())
```

The complete code can be downloaded in https://github.com/Clover0315/DeepLearning/blob/main/text_classification.py.
Looking forward to your reply.
best wishes for you!

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/8b65a688dc87ce9ca07ffb0ce50b84c7/44199.ipynb). Thanks!

**Comment by tyagihas** [comment]
Any update on this issue? I'm seeing the same error.

**Comment by tanzhenyu** [comment]
Why not just directly use this layer? `tf.keras.layers.experimental.preprocessing.TextVectorization` instead of direct import?

**Comment by JohanneSommer** [comment]
@Clover0315 It seems like the problem can be solved by adding the decorator `@tf.keras.utils.register_keras_serializable()` to the function `custom_standardization()`:

```python
@tf.keras.utils.register_keras_serializable()
def custom_standardization(input_data):
  lowercase = tf.strings.lower(input_data)
  stripped_html = tf.strings.regex_replace(lowercase, '<br />', ' ')
  return tf.strings.regex_replace(stripped_html,
                                  '[%s]' % re.escape(string.punctuation),
                                  '')
```

Try it out and let me know if it doesn't work

**Comment by tanzhenyu** [comment]
Oh I didn't realize there's a customized op -- yeah that should be the right fix

**Comment by alihasn92** [comment]
> @Clover0315 It seems like the problem can be solved by adding the decorator `@tf.keras.utils.register_keras_serializable()` to the function `custom_standardization()`:
> 
> ```python
> @tf.keras.utils.register_keras_serializable()
> def custom_standardization(input_data):
>   lowercase = tf.strings.lower(input_data)
>   stripped_html = tf.strings.regex_replace(lowercase, '<br />', ' ')
>   return tf.strings.regex_replace(stripped_html,
>                                   '[%s]' % re.escape(string.punctuation),
>                                   '')
> ```
> 
> Try it out and let me know if it doesn't work
I did this but for the error is still same.

@tf.keras.utils.register_keras_serializable()
def custom_standardization(input_data):
    lowercase = tf.strings.lower(input_data)
    stripped_html = tf.strings.regex_replace(lowercase, "<br />", " ")
    return tf.strings.regex_replace(
        stripped_html, "[%s]" % re.escape(string.punctuation), ""
    )
