### ISSUE TITLE
configure.py not working on r1.14 - aarch64 nivida jetson nano

### ISSUE THREAD

**Issue by JonasRSV** [tensorflow/tensorflow#44198]
**Describe the problem**

I am trying to build tensorflow c-library 1.14 from source on my jetson nano dev kit https://developer.nvidia.com/embedded/jetson-nano-developer-kit. I am running ubuntu 18.04 with aarch64, I have python3.6.9 installed.

I have cloned the tensorflow repo and checked out r1.14 branch, when I run

```bash
python3 configure.py
```

I get the following

```bash

python3 configure.py 
WARNING: ignoring LD_PRELOAD in environment.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.24.1- (@non-git) installed.
Please specify the location of python. [Default is /usr/bin/python3]: 


Found possible Python library paths:
  /usr/lib/python3.6/dist-packages
  /usr/lib/python3/dist-packages
  /usr/local/lib/python3.6/dist-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python3.6/dist-packages]

Do you wish to build TensorFlow with XLA JIT support? [Y/n]: n
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: y
TensorRT support will be enabled for TensorFlow.

Traceback (most recent call last):
  File "configure.py", line 1571, in <module>
    main()
  File "configure.py", line 1448, in main
    if validate_cuda_config(environ_cp):
  File "configure.py", line 1340, in validate_cuda_config
    tuple(line.decode('ascii').rstrip().split(': ')) for line in proc.stdout)
ValueError: dictionary update sequence element #9 has length 1; 2 is required

````

**Provide the exact sequence of commands / steps that you executed before running into the problem**

exact sequnce:

```bash
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
git checkout r1.14
python3 configure.py
```

**Comment by JonasRSV** [comment]
b'cublas_include_dir: /usr/include\n'
b'cublas_library_dir: /usr/lib/aarch64-linux-gnu\n'
b'cuda_binary_dir: /usr/local/cuda/bin\n'
b'cuda_include_dir: /usr/local/cuda/include\n'
b'cuda_library_dir: /usr/local/cuda/lib64\n'
b'cuda_toolkit_path: /usr/local/cuda\n'
b'cuda_version: 10.2\n'
b'cudnn_include_dir: /usr/include\n'
b'cudnn_library_dir: /usr/lib/aarch64-linux-gnu\n'
b'cudnn_version: \n'
b'cupti_include_dir: /usr/local/cuda/include\n'
b'cupti_library_dir: /usr/local/cuda/lib64\n'
b'nvvm_library_dir: /usr/local/cuda/nvvm/libdevice\n'
b'tensorrt_include_dir: /usr/include/aarch64-linux-gnu\n'
b'tensorrt_library_dir: /usr/lib/aarch64-linux-gnu\n'
b'tensorrt_version: 7\n'


I think it might be because cuda-nn seems to be empty

**Comment by JonasRSV** [comment]
But I have cudann on my compute under /usr/lib/aarch64-linux-gnu/libcudnn.so

**Comment by JonasRSV** [comment]
setting cuda version manully in third_part/gpus/finda_cuda_config.py at 348 made it work for me

```bash
cudnn_version = "8"
```

or well appears to work, not done building tensorflow yet.

**Comment by Saduf2019** [comment]
@JonasRSV 
Can you try with [tested build configuration](https://www.tensorflow.org/install/source#gpu) for TF required and see whether the problem still persists?.
Is there any particular reason for using 1.x as there is support for 2.x , please upgrade and let us know if the issue exists.
If you want CUDA 11 you can use nightly. If you want to keep 1.x APIs then you can only use CUDA 10.0

**Comment by JonasRSV** [comment]
Jetson Nano comes with these cuda version pre-installed so I'd prefer to to try to change.

Unfortunately the compilation now crashes with some obscure error:


```bash
INFO: From Compiling external/highwayhash/highwayhash/sip_hash.cc:
In file included from external/highwayhash/highwayhash/arch_specific.h:39:0,
                 from external/highwayhash/highwayhash/sip_hash.h:23,
                 from external/highwayhash/highwayhash/sip_hash.cc:15:
external/highwayhash/highwayhash/state_helpers.h: In function 'void highwayhash::PaddedUpdate(highwayhash::HH_U64, const char*, highwayhash::HH_U64, State*)':
external/highwayhash/highwayhash/compiler_specific.h:52:46: warning: requested alignment 32 is larger than 16 [-Wattributes]
 #define HH_ALIGNAS(multiple) alignas(multiple)  // C++11
                                              ^
external/highwayhash/highwayhash/state_helpers.h:49:41: note: in expansion of macro 'HH_ALIGNAS'
   char final_packet[State::kPacketSize] HH_ALIGNAS(32) = {0};
                                         ^~~~~~~~~~
ERROR: /home/jonasrsv/.cache/bazel/_bazel_jonasrsv/71718566c3609207e5a44599481f772c/external/nccl_archive/BUILD.bazel:67:1: fatbinary external/nccl_archive/device_dlink_hdrs.fatbin failed (Exit 1)
fatbinary fatal   : Unknown option '-bin2c-path'
Target //tensorflow/tools/lib_package:libtensorflow failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1732.677s, Critical Path: 143.12s
INFO: 2101 processes: 2101 local.
FAILED: Build did NOT complete successfully

```

Should I close this issue and re-open a new one for this compilation error? Since the original problem was with configuration, but by manually setting version that got resolved.

The reason why not using 2.x is simply because my code base is in 1.14 so I assume I need a 1.14 library file to run it.

**Comment by JonasRSV** [comment]
Seems to be related to this: https://github.com/tensorflow/tensorflow/issues/34429

**Comment by JonasRSV** [comment]
So essentially I have some code in tf 1.14 that creates a saved_model, I then have a c++ library that uses saved models.. in that issue it seems as if tf 1.14 will not ever get a fix for this error?

So would it be possible to load saved_models trained with tf 1.14 with a later tensorflow version that resolves this issue?

**Comment by Saduf2019** [comment]
@JonasRSV 
Yes please as the configuration issue is resolved, please create a new issue for the compilation error faced.
