### ISSUE TITLE
cannot find numpy/arrayobject.h

### ISSUE THREAD

**Issue by campuslifeceo** [tensorflow/tensorflow#442]
INFO: From Compiling tensorflow/python/client/tf_session_helper.cc:
In file included from tensorflow/python/client/tf_session_helper.cc:20:0:
./tensorflow/python/client/tf_session_helper.h:34:31: fatal error: numpy/                                                            arrayobject.h: No such file or directory
 #include "numpy/arrayobject.h"
                               ^
compilation terminated.
ERROR: /root/download/tensorflowgit/tensorflow/tensorflow/python/BUILD:70                                                            4:1: C++ compilation of rule '//tensorflow/python:tf_session_helper' fail                                                            ed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-                                                            D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parame                                                            ter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ff                                                            unction-sections ... (remaining 51 argument(s) skipped): com.google.devto                                                            ols.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by girving** [comment]
Just to make sure: did you run `configure`?

**Comment by ebrevdo** [comment]
What version of numpy do you have installed in the python interpreter you
have used with configure?

**Comment by vrv** [comment]
Comment if you'd still like help with this and we'll re-open.

**Comment by aahusarenko** [comment]
I am having this issue and I did run configure
