### ISSUE TITLE
Unable to Convert Faster RCNN to TF Lite model

### ISSUE THREAD

**Issue by shehroz010** [tensorflow/tensorflow#44205]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 10
- TensorFlow installed from (source or binary): pip package
- TensorFlow version (or github SHA if from source): 2.3.1

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
converter = tf.lite.TFLiteConverter.from_saved_model(model_path)
tflite_model = converter.convert()
```

**The output from the converter invocation**

```
Traceback (most recent call last):
  File "C:\Users\shehr\anaconda3\envs\nn_gpu\lib\site-packages\tensorflow\lite\python\convert.py", line 199, in toco_convert_protos
    enable_mlir_converter)
  File "C:\Users\shehr\anaconda3\envs\nn_gpu\lib\site-packages\tensorflow\lite\python\wrap_toco.py", line 38, in wrapped_toco_convert
    enable_mlir_converter)
Exception: <unknown>:0: error: loc("Func/StatefulPartitionedCall/input/_0"): requires all operands and results to have compatible element types
<unknown>:0: note: loc("Func/StatefulPartitionedCall/input/_0"): see current operation: %1 = "tf.Identity"(%arg0) {device = ""} : (tensor<1x?x?x3x!tf.quint8>) -> tensor<1x?x?x3xui8>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/TensorFlow/models/to_tflite.py", line 4, in <module>
    tflite_model = converter.convert()
  File "C:\Users\shehr\anaconda3\envs\nn_gpu\lib\site-packages\tensorflow\lite\python\lite.py", line 1076, in convert
    return super(TFLiteConverterV2, self).convert()
  File "C:\Users\shehr\anaconda3\envs\nn_gpu\lib\site-packages\tensorflow\lite\python\lite.py", line 900, in convert
    self).convert(graph_def, input_tensors, output_tensors)
  File "C:\Users\shehr\anaconda3\envs\nn_gpu\lib\site-packages\tensorflow\lite\python\lite.py", line 633, in convert
    **converter_kwargs)
  File "C:\Users\shehr\anaconda3\envs\nn_gpu\lib\site-packages\tensorflow\lite\python\convert.py", line 574, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "C:\Users\shehr\anaconda3\envs\nn_gpu\lib\site-packages\tensorflow\lite\python\convert.py", line 202, in toco_convert_protos
    raise ConverterError(str(e))
tensorflow.lite.python.convert.ConverterError: <unknown>:0: error: loc("Func/StatefulPartitionedCall/input/_0"): requires all operands and results to have compatible element types
<unknown>:0: note: loc("Func/StatefulPartitionedCall/input/_0"): see current operation: %1 = "tf.Identity"(%arg0) {device = ""} : (tensor<1x?x?x3x!tf.quint8>) -> tensor<1x?x?x3xui8>
```

M trying to convert my custom trained Faster RCNN model to TF Lite model. Does TF Lite supports RCNN models? If not can you guys please add a list to supported model's list to the website so that one easily identify which model to use from the start. Currently I trained a model but I dont have any info which models are supported and which are not. Adding a list of models will save lot of for people.

**Comment by ravikyram** [comment]
@shehroz010 

I tried in colab with TF nightly version(`2.4.0-dev20201021`) and was able to convert Faster RCNN model to TF lite. PLease, find the gist [here](https://colab.research.google.com/gist/ravikyram/2bc955491d4e4e426178164c23e737b4/untitled476.ipynb).Please,verify once and close the issue. Thanks!

**Comment by shehroz010** [comment]
I see this is done using a nightly build. But my main question is does it also have a support in current stable release too? And also m using a tensorflow gpu of same version 2.3.1. So do i need to install nightly build of tf gpu too to make it work? M training the models using Object detection model zoo for object detection.

**Comment by ravikyram** [comment]
@shehroz010 

You could use tf-nightly for now and in the next couple of months new stable version will be released. Please feel free to open the issue if it persists with the new version. Thanks!

**Comment by shehroz010** [comment]
@ravikyram ok thanks. It works fine with the nightly build.

**Comment by Kudo24** [comment]
hello everyone I have a question, is there a possibility that faster-rcnn model can apply in tf lite like in android devices for object detection?
