### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by codePerfectPlus** [tensorflow/tensorflow#44204]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Mint19.03
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.3
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I am getting an error while importing the TensorFlow.
```bash
>>> import tensorflow
Illegal instruction (core dumped)
```
I tried to downgrade the TensorFlow but still it's not working.

**Describe the expected behaviour**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by bhack** [comment]
> TensorFlow installed from (source or binary): source

Are you compiling TF from source?

**Comment by amahendrakar** [comment]
@codePerfectPlus,
Could you please provide the make and model of your CPU? Starting with v1.6, TensorFlow binaries use AVX instructions which may not run on older CPUs.

Also, please take a look at similar issues [#33038](https://github.com/tensorflow/tensorflow/issues/33038#issuecomment-538470776), [#29788](https://github.com/tensorflow/tensorflow/issues/29788#issuecomment-505571104) and let us know if it helps. Thanks!

**Comment by codePerfectPlus** [comment]
```
System:    Host: Inspiron Kernel: 5.4.0-52-generic x86_64 bits: 64 compiler: gcc v: 7.5.0 
           Desktop: Cinnamon 4.4.8 wm: muffin dm: LightDM Distro: Linux Mint 19.3 Tricia 
           base: Ubuntu 18.04 bionic 
Machine:   Type: Portable System: Dell product: Inspiron 3551 v: A00 serial: <filter> Chassis: 
           type: 8 serial: <filter> 
           Mobo: Dell model: 0CMF7W v: A00 serial: <filter> UEFI [Legacy]: Dell v: A00 
           date: 12/05/2014 
Battery:   ID-1: BAT0 charge: 24.2 Wh condition: 36.8/41.4 Wh (89%) volts: 15.6/14.8 
           model: PANASONIC DELL 78V9D7C serial: <filter> status: Discharging 
CPU:       Topology: Quad Core model: Intel Pentium N3540 bits: 64 type: MCP arch: Silvermont 
           rev: 8 L2 cache: 1024 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 17333 
           Speed: 1061 MHz min/max: 500/2666 MHz Core speeds (MHz): 1: 754 2: 853 3: 758 4: 581 
Graphics:  Device-1: Intel Atom Processor Z36xxx/Z37xxx Series Graphics & Display vendor: Dell 
           driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0f31 
           Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics (BYT) v: 4.2 Mesa 20.0.8 compat-v: 3.0 
           direct render: Yes 
Audio:     Device-1: Intel Atom Processor Z36xxx/Z37xxx Series High Definition Audio vendor: Dell 
           driver: snd_hda_intel v: kernel bus ID: 00:1b.0 chip ID: 8086:0f04 
           Sound Server: ALSA v: k5.4.0-52-generic 
Network:   Device-1: Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter vendor: Dell 
           driver: ath9k v: kernel port: f000 bus ID: 03:00.0 chip ID: 168c:0036 
           IF: wlp3s0 state: up mac: <filter> 
           Device-2: Atheros type: USB driver: btusb bus ID: 2-2.1:6 chip ID: 0cf3:e005 
           IF-ID-1: br-cb6c1f33c3f4 state: down mac: <filter> 
           IF-ID-2: docker0 state: down mac: <filter> 
Drives:    Local Storage: total: 111.79 GiB used: 95.80 GiB (85.7%) 
           ID-1: /dev/sda vendor: Kingston model: SA400S37120G size: 111.79 GiB speed: 3.0 Gb/s 
           serial: <filter> 
Partition: ID-1: / size: 109.53 GiB used: 95.80 GiB (87.5%) fs: ext4 dev: /dev/sda1 
Sensors:   System Temperatures: cpu: 45.0 C mobo: 45.0 C sodimm: 0.0 C 
           Fan Speeds (RPM): cpu: 2505 
Info:      Processes: 246 Uptime: 15m Memory: 3.73 GiB used: 1.44 GiB (38.6%) Init: systemd v: 237 
           runlevel: 5 Compilers: gcc: 7.5.0 alt: 7 Client: Unknown python3.6 client inxi: 3.0.32
```

**Comment by bhack** [comment]
Check https://github.com/tensorflow/tensorflow/issues/24548

**Comment by amahendrakar** [comment]
@codePerfectPlus,
Any updates regarding this? Please feel free to close the issue if resolved. Thanks!
