### ISSUE TITLE
TensorFlow on Dell XPS 9300

### ISSUE THREAD

**Issue by fabiogeraci** [tensorflow/tensorflow#44206]
I recently purchased a new laptop, and after setting up the environment on pycharm and running a test code i get several warning messages:

```
2020-10-21 16:03:00.527974: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Found 24958 images belonging to 2 classes.
Found 2600 images belonging to 2 classes.
2020-10-21 16:03:01.695574: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-10-21 16:03:03.773517: E tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-10-21 16:03:03.773567: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (fabio-XPS): /proc/driver/nvidia/version does not exist
2020-10-21 16:03:03.774077: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-21 16:03:03.802935: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 1497600000 Hz
2020-10-21 16:03:03.803743: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x6270580 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-21 16:03:03.803791: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
```
what am i missing?

this is the system configuration
>                           system         XPS 13 9300 (096D)
> /0                        bus            077Y9N
> /0/1                      memory         1MiB BIOS
> /0/400                    processor      Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
> /0/400/701                memory         128KiB L1 cache
> /0/400/702                memory         2MiB L2 cache
> /0/400/703                memory         8MiB L3 cache
> /0/700                    memory         192KiB L1 cache
> /0/1000                   memory         16GiB System Memory
> /0/1000/0                 memory         8GiB Row of chips LPDDR4 Synchronous 4267 MHz (0.2 ns)
> /0/1000/1                 memory         8GiB Row of chips LPDDR4 Synchronous 4267 MHz (0.2 ns)
> /0/100                    bridge         Intel Corporation
> /0/100/2       /dev/fb0   display        Iris Plus Graphics G7
> /0/100/4                  generic        Intel Corporation
> /0/100/7                  bridge         Ice Lake Thunderbolt 3 PCI Express Root Port #0
> /0/100/7.2                bridge         Ice Lake Thunderbolt 3 PCI Express Root Port #2
> /0/100/d                  bus            Ice Lake Thunderbolt 3 USB Controller
> /0/100/d/0     usb1       bus            xHCI Host Controller
> /0/100/d/1     usb2       bus            xHCI Host Controller
> /0/100/d.2                generic        Ice Lake Thunderbolt 3 NHI #0
> /0/100/d.3                generic        Ice Lake Thunderbolt 3 NHI #1
> /0/100/12                 communication  Intel Corporation
> /0/100/14                 bus            Ice Lake-LP USB 3.1 xHCI Host Controller
> /0/100/14/0    usb3       bus            xHCI Host Controller
> /0/100/14/0/4             input          USB Optical Mouse
> /0/100/14/0/5             generic        FingerPrint
> /0/100/14/0/9             multimedia     Integrated_Webcam_HD
> /0/100/14/0/a             communication  Bluetooth wireless interface
> /0/100/14/1    usb4       bus            xHCI Host Controller
> /0/100/14.2               memory         RAM memory
> /0/100/14.3    wlp0s20f3  network        Killer Wi-Fi 6 AX1650i 160MHz Wireless Network Adapter (201NGW)
> /0/100/15                 bus            Ice Lake-LP Serial IO I2C Controller #0
> /0/100/15.1               bus            Ice Lake-LP Serial IO I2C Controller #1
> /0/100/16                 communication  Management Engine Interface
> /0/100/1d                 bridge         Ice Lake-LP PCI Express Root Port #9
> /0/100/1d/0               storage        SK hynix
> /0/100/1d.7               bridge         Intel Corporation
> /0/100/1d.7/0             generic        RTS525A PCI Express Card Reader
> /0/100/1e                 communication  Ice Lake-LP Serial IO UART Controller #0
> /0/100/1f                 bridge         Ice Lake-LP LPC Controller
> /0/100/1f.3               multimedia     Smart Sound Technology Audio Controller
> /0/100/1f.4               bus            Ice Lake-LP SMBus Controller
> /0/100/1f.5               bus            Ice Lake-LP SPI Controller
> /0/0                      system         PnP device PNP0c02
> /0/2                      system         PnP device PNP0b00
> /0/3                      generic        PnP device INT3f0d
> /0/4                      input          PnP device PNP0303
> /0/5                      generic        PnP device DLL096d
> /0/6                      system         PnP device PNP0c02
> /0/7                      system         PnP device PNP0c02
> /0/8                      system         PnP device PNP0c02
> /0/9                      system         PnP device PNP0c02
> /1                        power          DELL 2XXFW05
> /2                        power          To Be Filled by O.E.M.

> device_lib.list_local_devices()
> [name: "/device:CPU:0"
> device_type: "CPU"
> memory_limit: 268435456
> locality {
> }
> incarnation: 322266644154681505
> , name: "/device:XLA_CPU:0"
> device_type: "XLA_CPU"

**Comment by Saduf2019** [comment]
@fabiogeraci 
Please refer to [this link](https://www.tensorflow.org/install/source#gpu), if you wants GPU.
if not GPU, ignore the errors.
