### ISSUE TITLE
Docker build tensorflow cannot detect gpu

### ISSUE THREAD

**Issue by YuhL6** [tensorflow/tensorflow#44208]
Hello:

I used docker to install tensorflow but GPU cannot be detected

**System information**
- OS Platform and Distribution: Ubuntu 20.04.1 LTS
- TensorFlow installed from (source or binary): docker
- Docker Image: 2.2.1-gpu-py3-jupyter
- Python version: Python 3.8.5
- GPU: GTX1650

**Describe the problem**

After running the command: **sudo docker run --gpus all -it --rm -p 8888:8888 tensorflow/tensorflow:2.2.1-gpu-py3-jupyter**, I use the jupyter on the browser to write python codes. But I find that gpu cannot be detected by tensorflow.

```import tensorflow as tf
import numpy as np
from tensorflow.python.client import device_lib

print(tf.__version__)
print(device_lib.list_local_devices())
```

result:

```
2.2.1
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 16222889058350606218
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 1739177089072959980
physical_device_desc: "device: XLA_CPU device"
]
```

There are no GPU.

**Any other info / logs**
Here is results of **sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi**:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1650    Off  | 00000000:01:00.0  On |                  N/A |
| N/A   44C    P8     3W /  N/A |    281MiB /  3911MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by ravikyram** [comment]
@YuhL6 

Please, refer this [SO link](https://stackoverflow.com/questions/63122486/the-tensorflow-docker-gpu-image-doesnt-detect-my-gpu) and see if it helps you. Thanks!
