### ISSUE TITLE
Cannot access a resource variable from a custom op on Mac and Windows

### ISSUE THREAD

**Issue by zhezherun** [tensorflow/tensorflow#44209]
I am facing an issue with accessing a resource variable from a custom op on Mac and on Windows (it works fine on Linux though). When running the attached reproducer on Mac, I get the following error:

```
Trying to access resource using the wrong type. Expected N10tensorflow3VarE got N10tensorflow3VarE [Op:CustomOp]
```

On Windows the error is similar:

```
Trying to access resource using the wrong type. Expected class tensorflow::Var got class tensorflow::Var [Op:CustomOp]
```

On Linux there is no error. The op works as expected and the attached test prints this output:

```
<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=([1., 2., 3.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=([2.22, 2.22, 2.22], dtype=float32)>
```

I think this issue is due to the use of an address of a static variable ```hash_bit``` in ```TypeIndex::Make<T>``` as a hash. When the shared library with the custom op is compiled, it will have its own copy of ```TypeIndex::Make<Var>::hash_bit```, so the hash codes for the same type (e.g. Var) will be different. I suspect this still works on Linux because a STB_GNU_UNIQUE symbol is generated for ```hash_bit```, so that there is only one definition of it (per type) in the whole process. Mac and Windows don't have this feature though.

Is it possible to rewrite TypeIndex in a way that will make it work across shared libraries on all platforms? Or perhaps various instantiations of ```TypeIndex::Make<T>``` could be exported from tensorflow framework library?

A standalone reproducer along with build scripts is attached.
[custom_op.zip](https://github.com/tensorflow/tensorflow/files/5417289/custom_op.zip)

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows, Mac
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary (pypi)
- TensorFlow version (use command below): 2.3.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by sushreebarsa** [comment]
@zhezherun It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.5 and let us know if the issue still persists? Thanks!
