### ISSUE TITLE
tf.contrib.layers.Conv2D and MaxPool2D in tf.keras.layers

### ISSUE THREAD

**Issue by teenazral** [tensorflow/tensorflow#44213]
I am trying to convert the following lines of code to TensorFlow 2.0. These are written in tf.contrib.layers and now I need to put them in tf.keras.layers. 

```python
net1_h = layers.conv2d(input, 32, 3, stride=1, scope="Enc_conv_1") 
net2 = layers.max_pool2d(input, kernel_size=2, stride=2, scope="Enc_maxpool_1")
```
The documentation for tf.keras.layers.Conv2D under TF2 states that input is not listed for Conv2D and MaxPool2D does not have input or kernel_size.

Any suggestions?

**Comment by Saduf2019** [comment]
@teenazral 
Please refer to this [migration link](https://www.tensorflow.org/guide/migrate) for the mentioned issue, you may try "pip --forceinstall tensorflow==1.15", also have you imported conv2f and other parameters with tf else you could run into error, please share error log if any and stand alone code if you face any errors.
