### ISSUE TITLE
How to calculate mixed partial derivatives w.r.t inputs?

### ISSUE THREAD

**Issue by uninstallit** [tensorflow/tensorflow#44219]
Assume I have the following neural network with two inputs:

`(x, t) ---> [neural network] ---> u(x,t)`

Is it possible to calculate the mixed partials i.e.: `d/dx[du(x,t)/dt]`?

**Comment by Saduf2019** [comment]
@uninstallit 
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
And move this to closed status.

**Comment by uninstallit** [comment]
I figured it out myself: https://stackoverflow.com/questions/64474239/how-to-calculate-d-dxdu-dt-in-nn-w-r-t-inputs-x-t-in-keras-tensorflow

**Comment by Saduf2019** [comment]
@uninstallit 
Thank you for your update,glad your issue is resolved.
