### ISSUE TITLE
Inlcude Ubuntu 20.04 in GPU Support Linux Setup

### ISSUE THREAD

**Issue by Harsh188** [tensorflow/tensorflow#44229]
## URL(s) with the issue:
[GPU Setup -- Linux setup](https://www.tensorflow.org/install/gpu#linux_setup)

### Clear description

The documentation for adding GPU support has descriptions for ubuntu 18.04 and 16.04 **but not ubuntu 20.04**. It's been a while since ubuntu 20.04 has been released and I think adding the instructions for ubuntu 20.04 will be helpful. I followed the article [Installing TensorFlow GPU in Ubuntu 20.04](https://towardsdatascience.com/installing-tensorflow-gpu-in-ubuntu-20-04-4ee3ca4cb75d) to set up GPU support on my system. Adding something along the lines would be great.

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue?

I'm willing to work on this.

**Comment by jvishnuvardhan** [comment]
@Harsh188 Are you planning to submit a PR to update the docs? Thanks!

**Comment by Harsh188** [comment]
@jvishnuvardhan Yep. I'll do this shortly. I'm not sure how this will change with TF 2.4 since CUDA 11 will be supported. I've been having trouble myself trying to get TF to use my RTX 3080.

**Comment by Harsh188** [comment]
On the official Nvidia CUDA toolkit 10.1 archive, there is no support for ubuntu 20.04 which makes me think that it's not recommended to install CUDA 10.1 for Ubuntu 20.04. However, certain articles exist that show you how to do it. I followed one of these articles hoping that it would work but when I ran `tf.config.list_physical_devices('GPU')` it resulted in an error. 

I was recommended to use tf-nightly, which works with CUDA 11.1 and is supported on ubuntu 20.04. I'm not too sure when TF 2.4 will be released and if we should bother including a GPU installation doc support for ubuntu 20.04 since this issue will be resolved with TF 2.4. 

@mihaimaruseac  could you comment on this topic?

**Comment by mihaimaruseac** [comment]
TF 2.4 is in the release phase now, we already cut the branch

**Comment by Harsh188** [comment]
In that case, I think it's best to wait.
