### ISSUE TITLE
does "shared_embedding_columns_v2" api need check executing_eagerly? 

### ISSUE THREAD

**Issue by osljw** [tensorflow/tensorflow#44224]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Does "shared_embedding_columns_v2" api need check executing_eagerly? 

```
@tf_export('feature_column.shared_embeddings', v1=[])
def shared_embedding_columns_v2(categorical_columns,
                                dimension,
                                combiner='mean',
                                initializer=None,
                                shared_embedding_collection_name=None,
                                ckpt_to_load_from=None,
                                tensor_name_in_ckpt=None,
                                max_norm=None,
                                trainable=True,
                                use_safe_embedding_lookup=True):
  **if context.executing_eagerly():
    raise RuntimeError('shared_embedding_columns are not supported when eager '
                       'execution is enabled.')**
```

error:
```
  File "~/models.py", line 92, in build_feature_columns
    group_embedding = tf.feature_column.shared_embeddings(group_encode, dimension=32)
  File "~/lib/python3.7/site-packages/tensorflow/python/feature_column/feature_column_v2.py", line 902, in shared_embedding_columns_v2
    raise RuntimeError('shared_embedding_columns are not supported when eager '
RuntimeError: shared_embedding_columns are not supported when eager execution is enabled.
```
**Describe the expected behavior**

Just comment the check code, seems all things normal. 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@osljw,
In order to expedite the trouble-shooting process, could you please provide following details 

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

and also the complete code with the dataset, to reproduce the issue reported here. Thanks!

**Comment by chenyanyin** [comment]
> _Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template_
> 
> **System information**
> 
> * Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
> * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
> * TensorFlow installed from (source or binary):
> * TensorFlow version (use command below):
> * Python version:
> * Bazel version (if compiling from source):
> * GCC/Compiler version (if compiling from source):
> * CUDA/cuDNN version:
> * GPU model and memory:
> 
> You can collect some of this information using our environment capture
> [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
> You can also obtain the TensorFlow version with:
> 
> 1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
> 2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
> 
> **Describe the current behavior**
> Does "shared_embedding_columns_v2" api need check executing_eagerly?
> 
> ```
> @tf_export('feature_column.shared_embeddings', v1=[])
> def shared_embedding_columns_v2(categorical_columns,
>                                 dimension,
>                                 combiner='mean',
>                                 initializer=None,
>                                 shared_embedding_collection_name=None,
>                                 ckpt_to_load_from=None,
>                                 tensor_name_in_ckpt=None,
>                                 max_norm=None,
>                                 trainable=True,
>                                 use_safe_embedding_lookup=True):
>   **if context.executing_eagerly():
>     raise RuntimeError('shared_embedding_columns are not supported when eager '
>                        'execution is enabled.')**
> ```
> 
> error:
> 
> ```
>   File "~/models.py", line 92, in build_feature_columns
>     group_embedding = tf.feature_column.shared_embeddings(group_encode, dimension=32)
>   File "~/lib/python3.7/site-packages/tensorflow/python/feature_column/feature_column_v2.py", line 902, in shared_embedding_columns_v2
>     raise RuntimeError('shared_embedding_columns are not supported when eager '
> RuntimeError: shared_embedding_columns are not supported when eager execution is enabled.
> ```
> 
> **Describe the expected behavior**
> 
> Just comment the check code, seems all things normal.
> 
> **Standalone code to reproduce the issue**
> Provide a reproducible test case that is the bare minimum necessary to generate
> the problem. If possible, please share a link to Colab/Jupyter/any notebook.
> 
> **Other info / logs** Include any logs or source code that would be helpful to
> diagnose the problem. If including tracebacks, please include the full
> traceback. Large logs and files should be attached.

hello, i have the same problem，do you have a solution？when i need eager execution enabled and must used tf.feature_column.shared_embeddings, i am very confused and I don't know how to do it.

**Comment by amahendrakar** [comment]
> hello, i have the same problem，do you have a solution？when i need eager execution enabled and must used tf.feature_column.shared_embeddings, i am very confused and I don't know how to do it.

@chenyanyin,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by panpan123456** [comment]
Has this problem been solved？ I have the same problem

**Comment by ZhangWeiguo** [comment]
same problem
