### ISSUE TITLE
[API] Tensorflow.Tensor.Tensor(byte[ ][ ], long[ ]) constructor not exist any more

### ISSUE THREAD

**Issue by frank-dong-ms** [tensorflow/tensorflow#44225]
We used to use version "1.14.0" of package "SciSharp.TensorFlow.Redist" and recently we upgrade to version "2.3.1" and seems the constructor for Tensor take byte[][] not exists any more, so I'm wondering is there any replacement for this API?

**Comment by jvishnuvardhan** [comment]
@mihaimaruseac Any idea of this package "SciSharp.TensorFlow.Redist" with TF2.3? Thanks!

**Comment by mihaimaruseac** [comment]
Best is to identify the commit that introduced the change and see if there is reasoning for it listed there.
