### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'numpy'

### ISSUE THREAD

**Issue by liangzelang** [tensorflow/tensorflow#44230]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.0
- Python version:  3.7.x

**Describe the current behavior**
 got errors

**Describe the expected behavior**
print out the tensor value

**Standalone code to reproduce the issue**
```
import tensorflow as tf

def f(x, y):
  output = 1.0
  for i in range(y):
    if i > 1 and i < 5:
      output = tf.multiply(output, x)
  return output

def grad(x, y):
  with tf.GradientTape() as t:
    t.watch(x)
    out = f(x, y)
  return t.gradient(out, x)

x = tf.convert_to_tensor(2.0)
print("result: ", grad(x, 6).numpy())
```

**Other info / logs**
```
Traceback (most recent call last):
  File "test_tf.py", line 17, in <module>
    print("result: ", grad(x, 6).numpy())
AttributeError: 'Tensor' object has no attribute 'numpy'
```

**Comment by fuhailin** [comment]
The bug you report doesn't exist, please check this gist :https://colab.research.google.com/drive/1kezUav5qkO3uY6AuvqUWLEx0iKrXYN3Q?usp=sharing

**Comment by Saduf2019** [comment]
@liangzelang 
I ran the code shared on tf 2.3 and on tf 2.0 as reported and do not face any errors, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/c30abd199b4e580ae5891b88c00e88b7/untitled450.ipynb).

As per the error reported: please refer to : [link](https://stackoverflow.com/questions/52357542/attributeerror-tensor-object-has-no-attribute-numpy), [link1](https://github.com/tensorflow/tensorflow/issues/27519).

If the issue still exist share a colab gist with the error reported, else please move the issue to closed status. Thanks!

**Comment by liangzelang** [comment]
thanks,  it works by adding  `tf.enable_eager_execution()` . 
And I found my tensorflow version in conda is 1.14.0, so maybe this issue does not exist in tf 2.0
thank you  @Saduf2019  @fuhailin

**Comment by Tarungarg98** [comment]
I am facing a similar issue. Attentions of Graph Convolution Transformer are in form of tensors, I am getting this error while converting them to numpy
