### ISSUE TITLE
set_shape cause gradient error in a condition case

### ISSUE THREAD

**Issue by thjashin** [tensorflow/tensorflow#4423]
### Environment info

Operating System: Ubuntu 16.04

If installed from binary pip package, provide:
1. A link to the pip package you installed: [https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl](https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl)
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`. 0.10.0rc0
### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

``` python
import tensorflow as tf
a = tf.ones((2, 1, 2))
a_ = tf.cond(tf.equal(tf.shape(a)[1], 1), lambda: tf.tile(a, (1, 5, 1)), lambda: a)
a_.set_shape([None, 5, None])
tf.gradients(a_, a)
# => ValueError: Shapes (2, 5, 2) and (2, 1, 2) are not compatible
```

If the set_shape line is removed, everything works fine

``` python
tf.gradients(a_, a)
# => [<tf.Tensor 'gradients_5/AddN:0' shape=(2, 1, 2) dtype=float32>]
```

**Comment by thjashin** [comment]
Hi,
Any reply for this problem?

**Comment by concretevitamin** [comment]
Hmm, I don't believe this is supported -- essentially what you're doing is to "hint" at TensorFlow to do a backward shape inference (which does not exist yet), and try to force the runtime to settle on the inferred branch.  

I might be wrong - so assigning to @yuanbyu to take a look.

**Comment by thjashin** [comment]
@concretevitamin thanks for reply. I think i'm not wanting tensorflow to do some backward shape inference or things like that. What I'm confused about is that how setting static shape can have an influence on gradients computing. Because without that line, the code works pretty well. What I only hope is that line can help me know more about the static shape of ```a_```

**Comment by yaroslavvb** [comment]
You can see from the stack trace that tf.gradients uses static shape
information

>>> tf.gradients(a_, a)
tf.gradients(a_, a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"/Users/yaroslav/anaconda2/envs/tensorflow_cpu/lib/python2.7/site-packages/tensorflow/python/ops/gradients.py",
line 498, in gradients
    in_grad.set_shape(t_in.get_shape())

**Comment by yuanbyu** [comment]
Your set_shape() line implicitly adds something (i.e., tf.equal(tf.shape(a)[1], 1) is True) that the current TensorFlow is not able to infer. So tf.gradients tries to generate the gradient code for the false branch of the code because it can't statically determine that it is infeasible. Obviously this would cause the shape inference to fail. In general, don't use set_shape to make shapes more concrete when you need to compute gradients.

**Comment by thjashin** [comment]
@yuanbyu get it. thx
