### ISSUE TITLE
Embedding layer with NaN input different behaviour on CPU vs GPU

### ISSUE THREAD

**Issue by mirkomiorelli** [tensorflow/tensorflow#44235]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.3.0-54-gfcc4b966f1 2.3.1
- Python version: 3.6
- CUDA/cuDNN version: CUDA Version 10.1.243

**Describe the current behavior**

Different behaviour of embedding layer on CPU vs GPU. When running on CPU and a `nan` value is passed as input to the embedding layer, the code throws a correct `InvalidArgumentError`. Running the same code on GPU silently converts the `nan` value to 0 and does not throw any warning/exception.

**Describe the expected behavior**

Maybe an exception should be thrown (or at least a warning) if a `nan` value is passed to the embedding layer on GPU?

**Standalone code to reproduce the issue**

This code breaks (as expected) running on CPU:
```python
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding
print(tf.__version__)

# Disable cuda devices
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1" 

# Make sure no cuda device is used
gpus = tf.config.experimental.list_physical_devices('GPU')
print(gpus)

# Simple toy model
n_inputs      = 10
embedding_dim = 2

input_tensor    = Input((1,))
embedded_tensor = Embedding(n_inputs, embedding_dim, name = 'embedding_layer')(input_tensor)

model = Model(inputs = input_tensor, outputs = embedded_tensor)

# Predict which should break (and does break on CPU)
model.predict([np.nan])
```
Output (`nan` gets converted to minimum value of int32 when cast to tf.int32, thus triggering the out of bound error):
```
InvalidArgumentError:  indices[0,0] = -2147483648 is not in [0, 10)
	 [[node functional_3/embedding_layer/embedding_lookup (defined at <ipython-input-7-7784f8517478>:25) ]] [Op:__inference_predict_function_295]

Errors may have originated from an input operation.
Input Source operations connected to node functional_3/embedding_layer/embedding_lookup:
 functional_3/embedding_layer/embedding_lookup/287 (defined at /usr/lib/python3.6/contextlib.py:81)

Function call stack:
predict_function
```
On the other hand, this piece of code does not break, nor throws a warning at me (running on GPU):
```python
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding
print(tf.__version__)

# Usa cuda device 0
gpus = tf.config.experimental.list_physical_devices('GPU')
tf.config.experimental.set_visible_devices(gpus[0], 'GPU')

# Simple toy model
n_inputs      = 10
embedding_dim = 2

input_tensor    = Input((1,))
embedded_tensor = Embedding(n_inputs, embedding_dim, name = 'embedding_layer')(input_tensor)

model = Model(inputs = input_tensor, outputs = embedded_tensor)

# Predict which should break (and does break on CPU)
print(model.predict([np.nan]))
print(model.predict([0]))
```
Output (`nan` output is same as 0th embedding):
```
2.3.1
[[[ 0.02256938 -0.02229818]]]
[[[ 0.02256938 -0.02229818]]]
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3.

Code throws an `InvalidArgumentError` when running on [CPU](https://colab.research.google.com/gist/amahendrakar/f80b8916c0b553ef60f1a08a75bd9172/44235-cpu.ipynb), whereas no error is thrown when running on [GPU](https://colab.research.google.com/gist/amahendrakar/91482d85fc0a5a435ed4b0d6a96a68cf/44235-gpu.ipynb). Please find the attached gist. Thanks!

**Comment by Saduf2019** [comment]
Was able to reproduce the issue with TF 2.5.0-dev20210114

Code throws an InvalidArgumentError when running on [CPU](https://colab.research.google.com/gist/Saduf2019/bd0e6d5de67539269898561f2a3f017a/untitled499.ipynb#scrollTo=_IpQoLNDHgyt), when running on GPU. Please find the attached [gist](https://colab.research.google.com/gist/Saduf2019/a571e4d483751ea92aa56c7e0b67e460/untitled499.ipynb). Thanks!

**Comment by sachinprasadhs** [comment]
There are many cases where the `CPU` version and `GPU` version will give different results. Sometimes this is because of different hardware capabilities, other times because of different efficiencies.
Considering the performance in measure, the same validation checks performed in `CPU` will not be included in the `GPU` as well. Thanks!
