### ISSUE TITLE
tf version 1.10.0 does not have MeanSqauredError()

### ISSUE THREAD

**Issue by NiranjanRavi1993** [tensorflow/tensorflow#44248]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- TensorFlow installed from (source or binary): Conda
- TensorFlow version:  1.10.1
- Python version: 3.6
- Installed using virtualenv? pip? conda?: conda
- GCC/Compiler version (if compiling from source): 5.4
- CUDA/cuDNN version: 9.0
- GPU model and memory: 1060

I am working on LSTM architecture using Keras (2.2.0) and tf (1.10.1). I have the below code:

model.compile(loss=tf.losses.MeanSquaredError(), optimizer = tf.optimizers.Adam(), metrics = [tf.metrics.MeanAbsoluteError()])

where AttributeError: module 'tensorflow.losses' has no attribute 'MeanSquaredError'. But tf version 1 is supposed to have this loss function. I checked the documentation part as well. https://www.tensorflow.org/api_docs/python/tf/keras/losses/MeanAbsoluteError

Still can't get rid of the error. I dont want to upgrade to tf version 2. Cause i have to upgrade my CUDA drivers as well!!

How do I fix this?
Thanks and Regards
Niranjan.

**Comment by Saduf2019** [comment]
@NiranjanRavi1993 
As tf 1.1 does not have support, and we have official support for 2.x, can you try on 1.15 and let us know if you still face the issue.

**Comment by mihaimaruseac** [comment]
TF 1.10 is extremely old and no longer updated.
