### ISSUE TITLE
ERROR: No matching distribution found for tensorflow

### ISSUE THREAD

**Issue by Zayn1101** [tensorflow/tensorflow#44245]
<em>Hello guys,
I am trying to install Tensorflow but its giving me this error.

![Capture](https://user-images.githubusercontent.com/63431339/96945131-3a721f00-14f6-11eb-8a52-42f81bb58eca.PNG)

I have Python V 3.9, Pip version 20.2
Python x64, Windows 10 x64
What I have already Tried:
I have tried creating Virtual environment using the following steps,
![Capture1](https://user-images.githubusercontent.com/63431339/96945257-ac4a6880-14f6-11eb-8c34-4e4fddf61966.PNG)
 which was successfully created... 
also tried these...
</em>

`pip install --upgrade `tensorflow``
and
`pip` install https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-2.3.0-cp38-cp38-win_amd64.whl`
 (This link was given @ Tensorflow web for Python v3.8, 3.9 not available)
I have already tried doing all these stuff with python v 3.8
My Paths are also set in Environment Variables

I have tried almost all suggestion provided on Stackoverflow and Github and even uninstalled and reinstalled Python, still
Any help will be highly appreciated!

**Comment by Saduf2019** [comment]
@Zayn1101 
please confirm if you have verified the compatibility issues and hardware requirements, please refer to this issue and let us know : #42367

**Comment by TheWiesmin** [comment]
same problem

**Comment by Saduf2019** [comment]
@TheWiesmin 
please conform if you have referred to the above comment.
