### ISSUE TITLE
`tf.count_up_to` returns the old value

### ISSUE THREAD

**Issue by daeyun** [tensorflow/tensorflow#4424]
Environment info: Ubuntu 16.04, IPython interactive session

Installed version of CUDA and cuDNN: 7.5.18, 5.1.3

Installed from the nightly pip package for python 3.4.

How to reproduce:

```python
import tensorflow as tf
with tf.Session().as_default():
  var = tf.Variable(0)
  count = var.count_up_to(3)
  tf.initialize_all_variables().run()
  print(var.eval())
  print(count.eval())
  print(var.eval())
```

Expected output:
```
0
1
1
```

What I see instead:
```
0
0
1
```

For some reason, the tensor from `tf.count_up_to` evaluates to the old value instead of the updated value.

**Comment by daeyun** [comment]
I noticed that the documentation says (current behavior):

> Returns: A Tensor. Has the same type as ref. A copy of the input before increment. If nothing else modifies the input, the values produced will all be distinct.

But it also says (similar to `tf.assign_add`)

> This operation outputs "ref" after the update is done. This makes it easier to chain operations that need to use the updated value.

**Comment by jmchen-g** [comment]
Thanks for reporting. @vrv Could you take a look at this? Thanks.

**Comment by vrv** [comment]
The documentation is wrong, I'll send a fix.
