### ISSUE TITLE
How can I obtain the output of an intermediate layer (feature extraction) in Model Subclassing ?

### ISSUE THREAD

**Issue by Rajatsharma07** [tensorflow/tensorflow#44252]
Please refer to the below link for more details on the issue.

https://stackoverflow.com/questions/64471742/skip-some-layers-in-keras-model-during-evaluation-validation-phase

My requirement is to override the Evaluation/Validation step after each epoch, with using the Existing Fit function.

Following below link does not work (when this code is written in test_step method)
https://keras.io/getting_started/faq/#how-can-i-obtain-the-output-of-an-intermediate-layer-feature-extraction

**Comment by Saduf2019** [comment]
@Rajatsharma07 
As the issue is not a bug or a feature request and is tracked on stackoverflow, and there is also a larger community that reads questions there please move it closed status on here.

**Comment by Rajatsharma07** [comment]
Not resolved, Will be tracking on the StackOverflow link.
