### ISSUE TITLE
How to use tf.keras.texts_to_sequences in tf.dataset

### ISSUE THREAD

**Issue by yananchen1989** [tensorflow/tensorflow#44259]
I have a text classification task whose feeding files are lines of text. Before, I use keras and generator to handle with massive dataset.
Now I want to use tf.dataset which can feed the data in a parallel way that is important to me as the bottleneck now is IO and text transformation.
I tried to implement my code below, like a protype, but is does not work, as it will not operate the get_keras_data function in parallel way.
I suppose that the core problem is that API such as `texts_to_sequences` `pad_sequences` can not be used for the tensor, while they just use for the numpy arrary.

So is there any other approaches to meet my expectation?

```
def get_keras_data(lines):
    random.shuffle(lines)
    infos_feat, infos_feat_sub, infos_label = [], [], []
    for line in lines:
        line = line.decode('UTF-8')
        label = line.strip().split(' ')[0].replace('__label__','')
        label_ix = app_id[label]
        feat = ' '.join(line.strip().split(' ')[1:])

        infos_feat.append(feat)
        infos_label.append(label_ix)
        infos_feat_sub.append(feat.replace('.',' '))

    content_ids_list = tok.texts_to_sequences(infos_feat)
    content_pad_array = tf.keras.preprocessing.sequence.pad_sequences(content_ids_list, maxlen=maxlen, padding='post', truncating='post',value=0)
    content_ids_list = tok_sub.texts_to_sequences(infos_feat_sub)
    content_pad_array_sub = tf.keras.preprocessing.sequence.pad_sequences(content_ids_list, maxlen=max_len_sub, padding='post', truncating='post',value=0)

    trunk = ([content_pad_array, content_pad_array_sub], \
            tf.keras.utils.to_categorical(np.array(infos_label), num_classes = 998, dtype='int' ))
    return trunk


def generator(path, batch_size):
    file_list = glob.glob("{}/part-*.csv".format(path))
    dataset = tf.data.TextLineDataset(file_list, num_parallel_reads=32 )
    for lines in dataset.shuffle(buffer_size=buffer_size).repeat().batch(batch_size).prefetch(20).as_numpy_iterator():
        trunk = get_keras_data(lines)
        yield trunk
```

**Comment by amahendrakar** [comment]
@yananchen1989,
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!
