### ISSUE TITLE
Different ABI between docker version and public version in tf 2.3.0

### ISSUE THREAD

**Issue by Ecclesiast** [tensorflow/tensorflow#44255]
Here is the link, where we first discussed issues with docker tensorflow:2.3.0 and tensorflow-text==2.3.0. https://github.com/tensorflow/text/issues/385
As pointed there - Docker image with tag 2.3.0 and tensorflow==2.3.0 have different ABIs.
Could it be fixed in future updates?

**Comment by angerson** [comment]
@mihaimaruseac @broken I'm not very familiar with the ABIs and how this could have happened, or if it could happen again.

Do either of you have any more insight on this? I'm wondering if it would be fixed if we just re-deployed the 2.3.0 containers.

**Comment by mihaimaruseac** [comment]
Let's try to redeploy the 2.3.0 container. It's possible we generated them using a different branch by mistake.

**Comment by angerson** [comment]
We redeployed the containers for `2.3.0` and `2.3.1`. Can you check and see if the issue persists?

**Comment by mihaimaruseac** [comment]
Closing. Please reopen if there is still an issue.
