### ISSUE TITLE
[FeatureRequest]Support tilde as alias for home directory in file paths

### ISSUE THREAD

**Issue by bitbeast18** [tensorflow/tensorflow#44264]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.2.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

I was trying to use `~/dir/file` style file-path to create `Dataset` using `tf.data.Dataset.list_files`, but it failed with `NotFoundError: No such file or directory`. With an expanded home directory path it works fine. Is it possible to add this feature to automatically resolve `tilde` as home directory.

**Will this change the current api? How?**

Not sure.

**Who will benefit with this feature?**
Maybe everyone (Or at least some lazy people like me)

**Any Other info.**

**Comment by aaudiber** [comment]
Typically Python APIs don't expand `~`, e.g. `open('~/file')` will not expand the `~`. `~` expansion is usually only done automatically by shells. To get the behavior of starting a path with `~`, users should call `os.path.expanduser("~")` directly. It is possible for a filename to start with the character `'~'`, so this change would technically break backwards compatibility. Closing for now, feel free to reopen if you think there are more good arguments for automatically expanding `~/`

**Comment by shelper** [comment]
This is annoying , and causes issues
for instance, i am running ` tensorflow_datasets.load('cats_vs_dogs')`, and it downloads the data, not to my home directory, but to something like `project_root/~/tensorflow_datasets/cats_vs_dogs`, this is definitely not desirable.....

**Comment by jhossbach** [comment]
To expand on this: Tensorflow itself tries to expand the `~` sign when datasets are downloaded and no `download_dir` is given. In the documentation for the `download_and_prepare` method this is even stated, see https://www.tensorflow.org/datasets/api_docs/python/tfds/core/DatasetBuilder#download_and_prepare. Either the `~` needs to be expanded or the default download dir should be relative to the CWD. Otherwise this poses a possibly severe risk of deleting the home directory by mistake.
