### ISSUE TITLE
Training is slow when using tf.keras.utils.Sequence with large Numpy arrays

### ISSUE THREAD

**Issue by daniel-pp** [tensorflow/tensorflow#44266]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux RHEL Server 7.6**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **2.3.1**
- Python version: **3.6**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: **10.1/7.6.4**
- GPU model and memory: **NVIDIA V100 32GB**

**Describe the current behavior**
I'm using `tf.keras.Model.fit()` on a GPU with input as `tf.keras.utils.Sequence` generating batches of `Numpy` arrays. When the generated input or target `Numpy` arrays are large I notice that the training slows down dramatically. Part of this is of course expected due to the host (CPU) to device (GPU) transfer, but the times I'm seeing suggest an additional overhead somewhere else.

Below is a minimal example reproducing the issue. To keep things simple, the `Numpy` arrays are created before `data_sequence` starts generating batches, so there is almost no work done by `data_sequence[idx]`. Also, the Model consists of a single linear activation, which should just translate to a NoOp.

On an NVIDIA Tesla V100 GPU I get ca. 900ms/step.
```
Epoch 1/10
100/100 [==============================] - 90s 899ms/step - loss: -3.4149e-04
Epoch 2/10
100/100 [==============================] - 91s 907ms/step - loss: -3.4149e-04
...
```
In TensorFlow Profiler trace_viewer one can see most of the time, namely 700ms, is spent in IteratorGetNextOp::DoCompute (or equally Iterator::Model and Iterator::Prefetch):
![tf_profiler](https://user-images.githubusercontent.com/35227976/97080852-c66f6e00-15fe-11eb-92f4-ea0fef54e98e.png)

**Describe the expected behavior**
The input and target `Numpy` arrays per batch combined have a size of `2*N*H*W*C*sizeof(np.float32) = 320 MB`. The CPU to GPU transfer bandwidth should be around `12.4 GB/s`, e.g. according to the [sample bandwidth test](https://github.com/NVIDIA/cuda-samples/tree/v10.1/Samples/bandwidthTest) from NVIDIA:
```
Host to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(GB/s)
   32000000                     12.4
```
so the CPU to GPU transfer cannot explain the almost 900ms per batch alone.

**Standalone code to reproduce the issue**
```python
import tqdm
import numpy as np
import tensorflow as tf
from tensorflow.keras.utils import Sequence

class NumpySequence(Sequence):
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]

workers = 1
steps_per_epoch, epochs = 100, 10
N, H, W, C = 4, 1000, 1000, 10

x_train = []
y_train = []
rng = np.random.default_rng()
for step in tqdm.tqdm(range(steps_per_epoch)):
    x_train.append(rng.standard_normal(size=(N, H, W, C), dtype=np.float32))
    y_train.append(rng.standard_normal(size=(N, H, W, C), dtype=np.float32))

data_sequence = NumpySequence(x_train, y_train)

model = tf.keras.models.Sequential([tf.keras.layers.Activation("linear")])
model.compile(optimizer='adam', loss=tf.keras.losses.CategoricalCrossentropy())
model.fit(data_sequence, epochs=epochs, workers=workers)
```

**Is `TensorFlow` doing some additional serialization or memory copies of the `Numpy` arrays? If so, is there any way to prevent them?**

I'm aware of `tf.data.Dataset` and the optimizations it applies. Unfortunately, my actual pre-processing pipeline, of which the above example is only a simple caricature, is too complex to port to `tf.data.Dataset`. Also, if I understand it correctly, `tf.keras.Model.fit()` internally transforms the `tf.keras.utils.Sequence` to `tf.data.Dataset` using the `from_generator` generator method.

**Comment by jvishnuvardhan** [comment]
@daniel-pp I can reproduce the issue. We will look into the root-cause of the issue. 

[Here](https://colab.research.google.com/gist/jvishnuvardhan/2cc2d1b50157feac339e4ba3d412a2e6/untitled.ipynb) is a gist for our reference. Thanks!

**Comment by axeldavy** [comment]
Hi, I have a very similar issue in a similar setting:

I train with model.fit and tf.keras.utils.Sequence on a RTX 2080TI. My batches are quite large (approx 250MB).
nvidia-smi reported by GPU wasn't reaching 100% usage, and I used tensorflow profiling tools to investigate.

The profiling tools showed that the batch data Host->GPU (_Recv, IteratorGetNext) upload is not interleaved with the computation of the previous batch. Instead when the processing of the batch starts, it performs the upload (and waits for it).
A fourth of the GPU time is wasted on this upload which could have been done during the processing of the previous batch.

I don't know if that is exactly the problem reported here, but it seems quite related.

**Comment by dakshvar22** [comment]
@jvishnuvardhan Is there any activity on this issue? We are facing the exact same problem on our side.
@daniel-pp Were you able to workaround the problem?

**Comment by daniel-pp** [comment]
@dakshvar22 I could not find a workaround, and I am also wondering if there has been any work on the issue.

**Comment by jvishnuvardhan** [comment]
Please note that I moved this issue to keras-team/keras repo where keras team focussed to resolved important bugs. Thanks
