### ISSUE TITLE
CMSIS repository always has to be downloaded an patched

### ISSUE THREAD

**Issue by mansnils** [tensorflow/tensorflow#44261]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- Tensorflow version (commit SHA if source): 392321a9a02f98baf7d9c0e34005d19568b38848
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):

**Describe the problem**
Some targets like Arduino need to patch the CMSIS repository when downloading it. Most other targets that don't need this, still always do it as default. It would be better if only those targets need patching, do that.
Also when supplying a path to an external CMSIS on the command line, the CMSIS repository is still downloaded. Actually a combination of the two different CMSIS repositories are then used. It would be better to not download when supplying an external CMSIS and only use that.

**Please provide the exact sequence of commands/steps when you ran into the problem**
For example this will still download a CMSIS repository and patch it:
make -f tensorflow/lite/micro/tools/make/Makefile CMSIS_PATH=/path/to/CMSIS_5/ TAGS=cmsis-nn TARGET=stm32f4  test

**Comment by advaitjain** [comment]
We are no longer patching CMSIS with #44406
