### ISSUE TITLE
How to force to run a function on GPU

### ISSUE THREAD

**Issue by vasilevskykv** [tensorflow/tensorflow#44260]
Hello:

I have the following code:

`config=tf.compat.v1.ConfigProto(log_device_placement=True)
config.gpu_options.visible_device_list='0'
config.gpu_options.allow_growth = True
config.gpu_options.per_process_gpu_memory_fraction = 0.9
tf.compat.v1.enable_eager_execution()
tf.compat.v1.reset_default_graph()`

`with tf.compat.v1.Session(config=config) as sess:
    x_train_multi, y_train_multi = multivariate_data(dataset, dataset[:, 1], 0,
                                                 TRAIN_SPLIT, past_history,
                                                 future_target, STEP)

    a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
    b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
    c = tf.matmul(a, b)
    #print(sess.run(x_train_multi, y_train_multi))
    print(sess.run(x_train_multi, y_train_multi))
    sess.close()`

The function, that makes 

`def multivariate_data(dataset, target, start_index, end_index, history_size,
                      target_size, step, single_step=False):
  #data = []
  #labels = []
  data = tf.TensorArray(tf.float32, size=0, dynamic_size=True, clear_after_read=False)
  labels = tf.TensorArray(tf.float32, size=0, dynamic_size=True, clear_after_read=False)
  #data = tf.placeholder(name="data", shape=[None, 720, 3], dtype=tf.float32)
  #labels = tf.placeholder(name= "labels", shape=[None, 36], dtype=tf.float32)
  start_index = start_index + history_size
  if end_index is None:
    end_index = len(dataset) - target_size
  #print(history_size)
  for i in range(start_index, end_index):
    indices = range(i-history_size, i, step)
    for j in indices:
     data = data.write(j, dataset[j])
    #data.append(dataset[indices])
    if single_step:
      labels = labels.write(i, target[i+target_size])
      #labels.append(target[i+target_size])
    else:
       for j in range(i, i+target_size):
          labels = labels.write(j, target[j])
      #labels.append(target[i:i+target_size])
  return data.stack(), labels.stack()
  #return np.array(data), np.array(labels)`

It runs on CPU, not on GPU:
CPU - 40%, Physical Memory - 97%, GPU - 2%

**Comment by ymodak** [comment]
You can try using `tf.device('GPU:0)`
See https://www.tensorflow.org/guide/gpu#manual_device_placement

**Comment by vasilevskykv** [comment]
I tried to use it, but mu function runs on CPU anyway:
CPU - 23%, GPU - 2%, PhysicalMemory - 86%

**Comment by ravikyram** [comment]
@vasilevskykv 

Please, fill [issue template.](https://github.com/tensorflow/tensorflow/issues/new/choose).Please, let us know which TF version you are using.Thanks!

**Comment by vasilevskykv** [comment]
I use TensorFlow 2.3.0 and TensorFlow-GPU 2.0.0

**Comment by vasilevskykv** [comment]
As I understood, I need to make all my operations using tf in the form tf.method() - every variable, indices should be transformed into tf.Variable, tf.Constant. And the only problems remains: how to transform method **append**, appliable to numpy.ndarray to TensorFlow and how to make slices in TensorFlow, that are equivalent to slices of numpy.ndarray such as **target[i:i+target_size]**

**Comment by vasilevskykv** [comment]
And in my session what should I write in method run
print(sess.run(data1, data2)), where data1 and data2 are tensors, obtained after splitting?

**Comment by ymodak** [comment]
What is your cuda/cudnn/nvidia driver version?
Typically you want to compute ops within the `tf.device` namescope to enforce manual device placement.

**Comment by vasilevskykv** [comment]
NVIDIA GeForce GTX 1050
Driver Version 441.87
CUDA Version 10.1
cuddn version: 7.6.4

**Comment by vasilevskykv** [comment]
Here is the piece of my code:
**def multivariate_data(dataset, target, start_index, end_index, history_size,
                      target_size, step, single_step=False):
  data = []
  labels = []
  start_index = start_index + history_size
  if end_index is None:
    end_index = len(dataset) - target_size
  #print(history_size)
  for i in range(start_index, end_index):
    indices = range(i-history_size, i, step)
    data.append(dataset[indices])
    if single_step:
      labels.append(target[i+target_size])
    else:
      labels.append(target[i:i+target_size])
  return np.array(data), np.array(labels)

features_considered = ['open', 'close', 'ema']
features = df[features_considered]
features.index = df['date']

dataset = features.values
data_mean = dataset[:TRAIN_SPLIT].mean(axis=0)
data_std = dataset[:TRAIN_SPLIT].std(axis=0)
dataset = (dataset-data_mean)/data_std

config=tf.compat.v1.ConfigProto(log_device_placement=True)
config.gpu_options.visible_device_list='0'
config.gpu_options.allow_growth = True
config.gpu_options.per_process_gpu_memory_fraction = 0.9

with tf.compat.v1.Session(config=config) as sess:

  with tf.device('/device:GPU:0'):
    x_train_multi, y_train_multi = multivariate_data(dataset, dataset[:, 1], 0,
                                                 TRAIN_SPLIT, past_history,
                                                 future_target, STEP)
    
  sess,run(x_train_multi, y_train_multi)
  sess.close()
**

**Comment by sanjoy** [comment]
Can you please attach the full logs?

**Comment by vasilevskykv** [comment]
2020-10-30 12:00:11.707090: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-10-30 12:00:11.769924: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-10-30 12:00:11.891164: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 1050 major: 6 minor: 1 memoryClockRate(GHz): 1.493
pciBusID: 0000:01:00.0
2020-10-30 12:00:11.916420: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-10-30 12:00:11.934542: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-30 12:00:25.256704: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-30 12:00:27.077890: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2020-10-30 12:00:27.090521: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2020-10-30 12:00:27.175818: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1843 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1
2020-10-30 12:00:27.261296: I tensorflow/core/common_runtime/direct_session.cc:359] Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1

And then I'm waiting for a long time finishing of calculations.

**Comment by vasilevskykv** [comment]
70% Physical Memory
30% CPU

**Comment by vasilevskykv** [comment]
And here is the end:
Traceback (most recent call last):
  File "D:\CryptoTrading\Prediction\BinanceNeuroPrediction\Pred4Year.py", line 81, in <module>
    print(sess.run(x_train_multi))
  File "I:\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "I:\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1105, in _run
    raise RuntimeError('The Session graph is empty.  Add operations to the '
RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().

**Comment by vasilevskykv** [comment]
I have already updated my Driver Version. Now it is 457.09

**Comment by vasilevskykv** [comment]
As I see the problem is absence of method **append** in Tensorflow with the following logic:
**v = tf.Variable([],tf.int32)
for i in range(3):
 tf.append(v, i)**

And after thet we should get something like that:
An array in **v** must be [0,1,2] instead []

**Comment by mohantym** [comment]
Hi @vasilevskykv ! you can use tf.device() to force a operation to either use GPU or CPU . You can use `tf.debugging.set_log_device_placement(True)`  to verify which devices you are using . Attaching [Gist](https://colab.sandbox.google.com/gist/mohantym/86eb5726fe00b97ae0f363b904aafbf9/github_44620.ipynb) for reference. Thanks!
