### ISSUE TITLE
Clarify math or paper reference behind AttentionCellWrapper

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#4427]
The documentation for `AttentionCellWrapper` in contrib states that it's based on this [paper](https://arxiv.org/abs/1601.06733). However, the attention mechanism in the paper appears to be distinct from that in `AttentionCellWrapper`. For example the TF implementation involves convolutions and requires a fixed attention window, neither of which are a feature of the referenced paper. I suggest that either the correct paper is referenced, or the description is updated to reflect the actual math being implemented. The biggest issue right now is that it's unclear what the various options really mean (`attn_length`, `attn_size`, `attn_vec_size`, etc) as their descriptions are very concise and without a paper reference to ground what the documentation is referring to, it's impossible to know what the attention mechanism is doing short of going through the code line-by-line.

**Comment by jmchen-g** [comment]
Thanks for the report. Notified the author.

**Comment by Monnoroch** [comment]
Hi @alquraishi, thanks for the report, indeed, [paper](https://arxiv.org/pdf/1409.0473v7.pdf) is a better fit to describe the model we've implemented.
We'll fix the docs as soon as possible.

**Comment by alquraishi** [comment]
@Monnoroch tbh I don't think that paper is a good description of the model either. I eventually went through the math and as far as I can tell it's not something that's from any paper I've come across before. At any rate, I ended up summarizing it (see below). If you think it would be useful to include the math directly feel free to use any part of this.

![image](https://cloud.githubusercontent.com/assets/5205204/18845519/002325a6-83f0-11e6-859e-db589cda985d.png)

**Comment by Monnoroch** [comment]
@alquraishi, here's the original Magenta post, that describes the cell at hand: https://magenta.tensorflow.org/2016/07/15/lookback-rnn-attention-rnn with all the math an examples.

**Comment by fxsuper** [comment]
@Monnoroch to the best of my understanding of the code, the math described in the Magenta post does _not_ match the math implemented in `AttentionCellWrapper`, though it does match the math in the paper you cited. Note that the original version of the Magenta code used its own version of attention, which has since changed to use `AttentionCellWrapper`. The math I wrote above should match the code of `AttentionCellWrapper`, unless I made a mistake somewhere.

**Comment by alquraishi** [comment]
@Monnoroch to the best of my understanding of the code, the math described in the Magenta post does _not_ match the math implemented in `AttentionCellWrapper`, though it does match the math in the paper you cited. Note that the original version of the Magenta code used its own version of attention, which has since changed to use `AttentionCellWrapper`. The math I wrote above should match the code of `AttentionCellWrapper`, unless I made a mistake somewhere.

**Comment by Monnoroch** [comment]
@alquraishi, that is very strange, as we have extensively tested that the original code and  ```AttentionCellWrapper``` behave exactly the same way.
But thanks, I will look into it again.

**Comment by alquraishi** [comment]
The original code and `AttentionCellWrapper` may well be identical. I was just saying that the prose description in the Magenta post is not identical to the code. The differences are not large, but there are some subtle discrepancies.

**Comment by dillonalaird** [comment]
I haven't checked all the math but this implementation slices off the first encoded hidden state and appends on the most recent decoded hidden state which is not what's done in Bahdanau. Attention is typically used for translation tasks, this looks like a good technique for music generation but I think the class name and the paper reference are misleading.

**Comment by jessedaniels** [comment]
[This post](https://theneuralperspective.com/2016/11/20/recurrent-neural-network-rnn-part-4-attentional-interfaces/) gives a comprehensive and easy-to-follow overview of the current TF attention implementation in an encoder-decoder context. According to the author the implementation is based on the details at the end of the Bahdanau paper (https://arxiv.org/pdf/1409.0473v7). The author provides a nice walk-through of the details of attention and then goes into depth on the implementation. The discussion includes some detail on the use and motivation of conv2d in the code, which isn't mentioned in any papers that I've seen. Some of the variable names are slightly different but overall it really helped me understand what's going on.

**Comment by dillonalaird** [comment]
@jessedaniels The author in that post gives an incorrect explanation of the conv2d operation. The conv2d is just a clever trick to calculate W*h_t over all time steps. You can see the original code where he got that from [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/seq2seq.py#L589). You can also verify it yourself by running:
```python
[tf.matmul(tf.squeeze(ai, [1]), tf.squeeze(k, [0,1])) for ai in tf.split(1, attn_length, attention_states)]
```
on some random matrices and seeing that you get the same values.

@Monnoroch The issue with AttentionCellWrapper is [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/rnn/python/ops/rnn_cell.py#L1129) and [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/rnn/python/ops/rnn_cell.py#L1101). This is slicing off the oldest encoded hidden state and appending the newest decoding hidden state and then passing those to the next time step. This means that for translation tasks, after you decode the first word you would never be able to run attention over the first encoded word again. Which is not what's done in Bahdanau.

**Comment by kho** [comment]
@Monnoroch Another problem with AttentionCellWrapper is that the conv2d operation, which in the cited paper can be precomputed because the hidden states (input context) remain unchanged throughout the recurrent steps, is now repeated each time, where (1-1/attn_length) of the computation is not necessary.

**Comment by aselle** [comment]
Closing due to lack of recent activity, please reopen if you have further. questions.

**Comment by classicCoder16** [comment]
Hello, apologies if this might be an obvious question, but I have a basic question regarding applying the AttentionCellWrapper in practice -- in particular it seems that we never specify the memory (e.g. the set of encoder hidden states) during the creation of the wrapper. 

How then does the module know where to attend? Does the memory get passed somehow through the initial state of the decoder? A basic example of how to use the wrapper in practice would definitely be much appreciated. Thanks!

**Comment by sfmin** [comment]
The paper use source sequence hidden state as attention values, but the code use dest hidden state pre?

**Comment by DaveYin** [comment]
It is very strange to have a fixed-sized window in the implementation of AttentionCellWrapper, because there is no description about it in the Bahdanau paper. Of course, the behave of the window is not clear, which makes me confused. Can anyone explain it?
