### ISSUE TITLE
Protobuf Installation Issue (?)

### ISSUE THREAD

**Issue by melrobin** [tensorflow/tensorflow#44279]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Fedora 32
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):  Source
- TensorFlow version:  Master
- Python version: 3.8
- Installed using virtualenv? pip? conda?:  N/A
- Bazel version (if compiling from source):3.7
- GCC/Compiler version (if compiling from source):  10.2.1
- CUDA/cuDNN version:8
- GPU model and memory: Titan XP 12 GB

**Describe the problem**
Build fails with the following error:
ERROR: /home/melrobin/.cache/bazel/_bazel_melrobin/f2116cf848eff0a1d187a7773c1fea53/external/com_google_protobuf/BUILD:155:11: C++ compilation of rule '@com_google_protobuf//:protobuf' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/descriptor_database.d ... (remaining 48 argument(s) skipped)
ccache: error: invalid size: D
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build --config=cuda  //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@melrobin,
Could you please provide all the commands that you executed before running into the problem and the complete error log.

Also, if you're building TensorFlow from the master branch make sure you have CUDA 11 and cuDNN 8 installed. Thanks!

**Comment by melrobin** [comment]
OK I have CUDA 11 and cuDNN 8 installed.  I am using Bazel 3.7.0.  He is the command:
bazel build --verbose_failures --config=cuda --config=opt //tensorflow/tools/pip_package:build_pip_package

Here is the latest error:
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (414 packages loaded, 35398 targets configured).
INFO: Found 1 target...
ERROR: /home/melrobin/.cache/bazel/_bazel_melrobin/f2116cf848eff0a1d187a7773c1fea53/external/com_google_protobuf/BUILD:110:11: C++ compilation of rule '@com_google_protobuf//:protobuf_lite' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /home/melrobin/.cache/bazel/_bazel_melrobin/f2116cf848eff0a1d187a7773c1fea53/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/lib:/usr/local/atlas/lib:/usr/local/lib:/opt/intel/lib/intel64_lin:/usr/local/protobuf/lib \
    PATH=/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/melrobin/.local/bin:/home/melrobin/bin:/usr/local/cuda/bin \
    PWD=/proc/self/cwd \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/generated_enum_util.d '-frandom-seed=bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/generated_enum_util.o' -iquote external/com_google_protobuf -iquote bazel-out/host/bin/external/com_google_protobuf -isystem external/com_google_protobuf/src -isystem bazel-out/host/bin/external/com_google_protobuf/src -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIE -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -fno-canonical-system-headers -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -g0 -w '-march=native' -g0 '-std=c++14' -DHAVE_PTHREAD -DHAVE_ZLIB -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -Wno-write-strings -c external/com_google_protobuf/src/google/protobuf/generated_enum_util.cc -o bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/generated_enum_util.o)
Execution platform: @local_execution_config_platform//:platform
ccache: error: invalid size: D
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 10.589s, Critical Path: 0.12s
INFO: 20 processes: 20 internal.
FAILED: Build did NOT complete successfully

**Comment by melrobin** [comment]
TF will build by not to include CUDA support  I can then use the bazel command for CUDA support and still have access to the GPU.

**Comment by angerson** [comment]
./configure has been run in this environment prior to the `bazel` call, correct?

**Comment by melrobin** [comment]
Yes I ran configure.  Not choosing CUDA allows a build. Choosing CUDA
fails.

**Comment by melrobin** [comment]
Changed the GCC_HOST_PREFIX from /usr/bin/ccache to /usr/bin/gcc and this has fixed the problem.
