### ISSUE TITLE
Tensorflow dataset is not faster with multiple cores

### ISSUE THREAD

**Issue by seankerman** [tensorflow/tensorflow#44274]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- Linux Ubuntu 18.04):
- TensorFlow installed from Colab / AWS Deep Learning AMI
- TensorFlow version 2.3.0
- Python version 3.6
- Bazel version N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
I am using tensorflow dataset to read multiple datasets in parallel. I am trying to use dataset.interleave(map_function, ...) with multiple cores to speed up reads. All of the example code I have seen uses time.sleep() to "emulate" a real workload in the map_function. When doing this the dataset runs faster with multiple cores. However, when the map_function has a real computational load (and not just a sleep function) using multiple cores has no improvement. 

**Describe the expected behavior**
I expect that when I use multiple cores I will get a performance improvement when using a real workload in the map_function.

**Standalone code to reproduce the issue**
```
import time
import tensorflow as tf
import numpy as np
from multiprocessing import cpu_count
        
def real_work():
    for i in range(1000000):
        2+2
    
def sleep_delay():
    time.sleep(.03)

def run_test(num_cores, delay):
    def test_gen(k):
        for i in range(10):
            delay()
            yield 0

    class TestDataset(tf.data.Dataset):

        def __new__(cls,k):
            return tf.data.Dataset.from_generator(
                test_gen,
                output_types=((tf.dtypes.float32)),
                output_shapes=((None)),
                args=(k,)
            )

    def get_test_dataset(num_cores):

        dataset = tf.data.Dataset.from_tensor_slices([str(f) for f in range(30)])
        dataset = dataset.interleave(lambda k: TestDataset(k),
                                cycle_length=num_cores,
                                num_parallel_calls=num_cores, #tf.data.experimental.AUTOTUNE,
                                block_length=1,
                                deterministic=False)
        dataset = dataset.prefetch(100)
        return dataset

    it = get_test_dataset(num_cores).as_numpy_iterator()

    for i in it:
        continue

n_cpus = cpu_count()

print('\n 1 core, sleep delay')
%time run_test(1,sleep_delay)

print(f'\n {n_cpus} core, sleep delay')
%time run_test(n_cpus,sleep_delay)

print('\n 1 core, real_work')
%time run_test(1,real_work)

print(f'\n {n_cpus} core, real_work')
%time run_test(n_cpus,real_work)
```

** OUTPUT **
 1 core, sleep delay
CPU times: user 259 ms, sys: 11 ms, total: 270 ms
Wall time: 6.55 s

 4 core, sleep delay
CPU times: user 276 ms, sys: 11.3 ms, total: 287 ms
Wall time: 1.94 s

 1 core, real_work
CPU times: user 7.55 s, sys: 4.67 ms, total: 7.55 s
Wall time: 7.42 s

 4 core, real_work
CPU times: user 7.87 s, sys: 1.8 ms, total: 7.87 s
Wall time: 7.61 s

As can be seen the sleep delay system works as intended but with a real workload multicore has no impact.

here is a colab link: 
https://colab.research.google.com/drive/1hqxHWK4cxD-ja8kV33LM56z6uxPthsjo?usp=sharing

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3, nightly version (`2.5.0-dev20201026`)and was able to reproduce the issue.Please,find the gist [here](https://colab.research.google.com/gist/ravikyram/c84c40dd216db48b3c7bbdb02c902b90/untitled87.ipynb?authuser=1). Thanks!

**Comment by aaudiber** [comment]
This is due to contention on the Python Global Interpreter Lock. `real_work` can't be run from multiple cores because it holds the lock. To avoid this, you can define your computation using TensorFlow ops. Then the computation will be executed in C++, where it can use multiple cores. [This colab](https://colab.research.google.com/drive/1cLk-G8P1dNOajKy0RKBHDVA50jf5qC8I) demonstrates some speedup from using multiple cores for a compute-intensive dataset.

**Comment by seankerman** [comment]
Thank you. This is helpful. Unfortunately the code that I am working with is not easily converted to tensorflow ops. What I would like is some sort of generator that works in parallel in python and takes advantage of multiple cores. Basically I want to be able to do something like:

preds = []
for b in generator:
    preds.append(model(b))

where the generator uses multiprocessing in python the use all cores. Does something like this exists in the tensorflow library or is there no way to parallelize python functions for input?

**Comment by aaudiber** [comment]
There isn't a way to use multiple processes to call a Python generator function faster. If performance is important, I suggest investing the effort into representing the preprocessing with TensorFlow ops, so that the preprocessing can be optimized and parallelized.

**Comment by mohantym** [comment]
Hi @seankerman ! Did you check with above [suggestion](https://github.com/tensorflow/tensorflow/issues/44274#issuecomment-719770863) yet?
