### ISSUE TITLE
DLL error importing python tensorflow library in pywrap_tensorflow.py

### ISSUE THREAD

**Issue by ajtorresd** [tensorflow/tensorflow#44272]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home, x64, version 18362.1139 in Spanish (ESPAÑOL)
- Mobile device: I will test in a mobile device after development.
- TensorFlow installed from (source or binary): binary, pip install.
- TensorFlow version:
C:\>pip list | findstr tensorflow
tensorflow             1.15.0
tensorflow-estimator   1.15.1
* i tried version 2
- Python version: Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): I dont know
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: no cuda
- GPU model and memory:  Intel UHD Graphics, 600. 4G memory
- AVX:
AVX             -       Supports AVX instruction extensions

**Describe the problem**
Im trying some code on python that includes tensorflow, when i do import tensorflow as tf it results into an DLL error 

i just installed Visual C++ downloads and i updraded to tensorflow 2,  it didnt work

*****Provide the exact sequence of commands / steps that you executed before running into the problem*****
python command line:
import numpy as np
import os
import six.moves.urllib as urllib
import sys
import tarfile
import tensorflow as tf
.... ERROR

****** Any other info / logs******

>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Error en una rutina de inicialización de biblioteca de vínculos dinámicos (DLL).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Error en una rutina de inicialización de biblioteca de vínculos dinámicos (DLL).

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by amahendrakar** [comment]
@ajtorresd,
Could you please share the make and model of the CPU on your machine. Make sure you have all the compatible softwares as per the [system requirements](https://www.tensorflow.org/install/pip#system-requirements).

Also, please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/42058#issuecomment-672240986) from a similar issue and let us know if it helps. Thanks!

**Comment by ajtorresd** [comment]
Hi Abhilash,

I installed Nvidia CUDA 10 as per your suggestion and my code is still
failing just importing... may you have any other suggestions?

my cpu details are:

Coreinfo v3.5 - Dump information on system CPU and memory topology
Copyright (C) 2008-2020 Mark Russinovich
Sysinternals - www.sysinternals.com


Intel(R) Celeron(R) N4000 CPU @ 1.10GHz
Intel64 Family 6 Model 122 Stepping 1, GenuineIntel
Microcode signature: 0000002C
HTT             *       Hyperthreading enabled
HYPERVISOR      -       Hypervisor is present
VMX             *       Supports Intel hardware-assisted virtualization
SVM             -       Supports AMD hardware-assisted virtualization
X64             *       Supports 64-bit mode

SMX             -       Supports Intel trusted execution
SKINIT          -       Supports AMD SKINIT

NX              *       Supports no-execute page protection
SMEP            *       Supports Supervisor Mode Execution Prevention
SMAP            *       Supports Supervisor Mode Access Prevention
PAGE1GB         *       Supports 1 GB large pages
PAE             *       Supports > 32-bit physical addresses
PAT             *       Supports Page Attribute Table
PSE             *       Supports 4 MB pages
PSE36           *       Supports > 32-bit address 4 MB pages
PGE             *       Supports global bit in page tables
SS              *       Supports bus snooping for cache operations
VME             *       Supports Virtual-8086 mode
RDWRFSGSBASE    *       Supports direct GS/FS base access

FPU             *       Implements i387 floating point instructions
MMX             *       Supports MMX instruction set
MMXEXT          -       Implements AMD MMX extensions
3DNOW           -       Supports 3DNow! instructions
3DNOWEXT        -       Supports 3DNow! extension instructions
SSE             *       Supports Streaming SIMD Extensions
SSE2            *       Supports Streaming SIMD Extensions 2
SSE3            *       Supports Streaming SIMD Extensions 3
SSSE3           *       Supports Supplemental SIMD Extensions 3
SSE4a           -       Supports Streaming SIMDR Extensions 4a
SSE4.1          *       Supports Streaming SIMD Extensions 4.1
SSE4.2          *       Supports Streaming SIMD Extensions 4.2

AES             *       Supports AES extensions
AVX             -       Supports AVX instruction extensions
FMA             -       Supports FMA extensions using YMM state
MSR             *       Implements RDMSR/WRMSR instructions
MTRR            *       Supports Memory Type Range Registers
XSAVE           *       Supports XSAVE/XRSTOR instructions
OSXSAVE         *       Supports XSETBV/XGETBV instructions
RDRAND          *       Supports RDRAND instruction
RDSEED          *       Supports RDSEED instruction

CMOV            *       Supports CMOVcc instruction
CLFSH           *       Supports CLFLUSH instruction
CX8             *       Supports compare and exchange 8-byte instructions
CX16            *       Supports CMPXCHG16B instruction
BMI1            -       Supports bit manipulation extensions 1
BMI2            -       Supports bit manipulation extensions 2
ADX             -       Supports ADCX/ADOX instructions
DCA             -       Supports prefetch from memory-mapped device
F16C            -       Supports half-precision instruction
FXSR            *       Supports FXSAVE/FXSTOR instructions
FFXSR           -       Supports optimized FXSAVE/FSRSTOR instruction
MONITOR         *       Supports MONITOR and MWAIT instructions
MOVBE           *       Supports MOVBE instruction
ERMSB           *       Supports Enhanced REP MOVSB/STOSB
PCLMULDQ        *       Supports PCLMULDQ instruction
POPCNT          *       Supports POPCNT instruction
LZCNT           -       Supports LZCNT instruction
SEP             *       Supports fast system call instructions
LAHF-SAHF       *       Supports LAHF/SAHF instructions in 64-bit mode
HLE             -       Supports Hardware Lock Elision instructions
RTM             -       Supports Restricted Transactional Memory
instructions

DE              *       Supports I/O breakpoints including CR4.DE
DTES64          *       Can write history of 64-bit branch addresses
DS              *       Implements memory-resident debug buffer
DS-CPL          *       Supports Debug Store feature with CPL
PCID            -       Supports PCIDs and settable CR4.PCIDE
INVPCID         -       Supports INVPCID instruction
PDCM            *       Supports Performance Capabilities MSR
RDTSCP          *       Supports RDTSCP instruction
TSC             *       Supports RDTSC instruction
TSC-DEADLINE    *       Local APIC supports one-shot deadline timer
TSC-INVARIANT   *       TSC runs at constant rate
xTPR            *       Supports disabling task priority messages

EIST            *       Supports Enhanced Intel Speedstep
ACPI            *       Implements MSR for power management
TM              *       Implements thermal monitor circuitry
TM2             *       Implements Thermal Monitor 2 control
APIC            *       Implements software-accessible local APIC
x2APIC          *       Supports x2APIC

CNXT-ID         -       L1 data cache mode adaptive or BIOS

MCE             *       Supports Machine Check, INT18 and CR4.MCE
MCA             *       Implements Machine Check Architecture
PBE             *       Supports use of FERR#/PBE# pin

PSN             -       Implements 96-bit processor serial number

PREFETCHW       *       Supports PREFETCHW instruction

Maximum implemented CPUID leaves: 00000018 (Basic), 80000008 (Extended).
Maximum implemented address width: 48 bits (virtual), 39 bits (physical).

Processor signature: 000706A1

Logical to Physical Processor Map:
*-  Physical Processor 0
-*  Physical Processor 1

Logical Processor to Socket Map:
**  Socket 0

Logical Processor to NUMA Node Map:
**  NUMA Node 0

No NUMA nodes.

Logical Processor to Cache Map:
*-  Data Cache          0, Level 1,   24 KB, Assoc   6, LineSize  64
*-  Instruction Cache   0, Level 1,   32 KB, Assoc   8, LineSize  64
**  Unified Cache       0, Level 2,    4 MB, Assoc  16, LineSize  64
-*  Data Cache          1, Level 1,   24 KB, Assoc   6, LineSize  64
-*  Instruction Cache   1, Level 1,   32 KB, Assoc   8, LineSize  64

Logical Processor to Group Map:
**  Group 0

**Comment by amahendrakar** [comment]
@ajtorresd,
As per Intel's [product specification](https://ark.intel.com/content/www/us/en/ark/products/128988/intel-celeron-processor-n4000-4m-cache-up-to-2-60-ghz.html), your CPU doesn't support AVX. For more information, please take a look at the [hardware requirements](https://www.tensorflow.org/install/pip#hardware-requirements) to install TensorFlow with pip. 

As an alternative in this case, you can [build TensorFlow from source](https://www.tensorflow.org/install/source) or use [Google Colab](https://colab.research.google.com/). Thanks!

**Comment by ajtorresd** [comment]
Hi Abhilash

*Sorry for the late answer i was trying to find out another laptop with
cpu's AVX enable... i failed...*

*Im going to try your suggestion this weekend... i really want to finish
this product.*

*Regards*

*Antonio.*

**Comment by ajtorresd** [comment]
An aditional question, can i compile tensorflow in windows????

**Comment by amahendrakar** [comment]
> An aditional question, can i compile tensorflow in windows????

@ajtorresd,
Yes, you can compile TensorFlow on Windows. Please follow [this guide](https://www.tensorflow.org/install/source_windows) for the instructions. Thanks!

**Comment by ajtorresd** [comment]
Im working on it friend!

**Comment by ajtorresd** [comment]
Hi abilash...

I have bee following your recomendations

the ones listed here: https://www.tensorflow.org/install/source_windows

but in the step:

bazel build //tensorflow/tools/pip_package:build_pip_package

it finished with an error (late in this email)  Visual C++ build tools not
found on your machine ... but i downloaded it and installed it previously...


  C:/tensorflow/tensorflow/workspace.bzl:109:30: in tf_repositories
Repository rule def_file_filter_configure defined at:

C:/tensorflow/tensorflow/tools/def_file_filter/def_file_filter_configure.bzl:55:44:
in <toplevel>
ERROR: An error occurred during the fetch of repository
'local_config_def_file_filter':
   Traceback (most recent call last):
        File
"C:/tensorflow/tensorflow/tools/def_file_filter/def_file_filter_configure.bzl",
line 33, column 28, in _def_file_filter_configure_impl
                auto_configure_fail("Visual C++ build tools not found on
your machine")
        File
"C:/users/lenovo/_bazel_lenovo/xv6zejqw/external/bazel_tools/tools/cpp/lib_cc_configure.bzl",
line 112, column 9, in auto_configure_fail
                fail("\n%sAuto-Configuration Error:%s %s\n" % (red,
no_color, msg))
Error in fail:
Auto-Configuration Error: Visual C++ build tools not found on your machine
ERROR: C:/tensorflow/tensorflow/python/BUILD:6295:8:
//tensorflow/python:pywrap_tensorflow_filtered_def_file depends on
@local_config_def_file_filter//:def_file_filter in repository
@local_config_def_file_filter which failed to fetch. no such package
'@local_config_def_file_filter//':
Auto-Configuration Error: Visual C++ build tools not found on your machine
ERROR: Analysis of target
'//tensorflow/tools/pip_package:build_pip_package' failed; build aborted:
Analysis failed
INFO: Elapsed time: 3172.774s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (364 packages loaded, 13711
targets configured)
    Fetching @llvm-project; fetching 1902s
    Fetching ...roject; Extracting
C:/users/lenovo/_bazel_lenovo/xv6zejqw/external/llvm-project/temp411294270894680330\
4/3c696a212ba4328e4f8f92136bc4d728a6490ef7.tar.gz 623s

**Comment by amahendrakar** [comment]
@ajtorresd,
Could you please provide the following details 

- TensorFlow version you are trying to install:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

And also, make sure you have all the compatible softwares installed as per the [tested build configurations](https://www.tensorflow.org/install/source_windows#cpu). Thanks!
