### ISSUE TITLE
Slim Tutorial and Script broken due to Commit 8d1b23d999a563c56236a3d250e18ef825e4e66e

### ISSUE THREAD

**Issue by PatrickChrist** [tensorflow/tensorflow#4428]
Hey TF Team,

Commit 8d1b23d999a563c56236a3d250e18ef825e4e66e broke the TF Slim Tutorial and TF Slim Script:
https://github.com/tensorflow/models/blob/master/slim/scripts/finetune_inception_v3_on_flowers.sh
Reverting this file to 4d241449aeb3707143c64e1be106cc6828a0d7b0 solves the issue https://github.com/tensorflow/tensorflow/commit/4d241449aeb3707143c64e1be106cc6828a0d7b0#diff-197163b98ebda1e22c3ff820582bf0d5

In the latest TF version as well as the TF rc10 the TF Slim Image Classification is not running.
Tested on Offical Tensorflow Docker GPU Image.

Best Wishes,
Patrick

**Comment by aselle** [comment]
@annarev, since this is your change, could you take a look

**Comment by aselle** [comment]
Closing due to lack of recent activity, please reopen if you have further. Please let us know if your issue is not resolved in the latest version. Thanks!

**Comment by annarev** [comment]
Sorry, I somehow missed this issue earlier. Patrick, let me know if you still see the issue.
