### ISSUE TITLE
I had tried this code in Xcode with objective c but I am getting the error "Explicit specialization of undeclared template struct 'NumTraits'

### ISSUE THREAD

**Issue by disha1112** [tensorflow/tensorflow#44288]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by disha1112** [comment]
I want to convert opencv mat object to tensors but I am getting below error : - 
 "Explicit specialization of undeclared template struct 'NumTraits'

I am using this code in objective c

**Comment by Saduf2019** [comment]
@disha1112 
Please share simple stand alone code such that we can replicate the issue or if possible share a colab gist with the error reported.

**Comment by disha1112** [comment]
![Screen Shot 2020-10-28 at 11 48 30 AM](https://user-images.githubusercontent.com/73386434/97402174-18263a00-1918-11eb-9b9e-53b3f259778f.png)


Above is the screenshot of the code.

**Comment by Saduf2019** [comment]
@disha1112 
Please paste the code/error message (using makrdown formatting around it) instead of screenshotting. Screenshots are not searchable so they don't help in looking for the issue and also don't help other people having the same error from finding about the issue.

**Comment by roshni1237** [comment]
Hello @Saduf2019 
here is the error which shown in ss
"Explicit specialization of undeclared template struct 'NumTraits'"
"No template named 'GenericNumTraits'"
