### ISSUE TITLE
Converted TFLite model accuracy drop

### ISSUE THREAD

**Issue by ivs-pychen** [tensorflow/tensorflow#44289]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source): 2.3

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
def rep_data_gen():
    f = "/home/pychen/Datasets/VOCdevkit/VOC0712_TRAIN/ImageSets/train.txt"
    f_name = np.loadtxt(f, dtype = np.str).reshape(-1)
    # print('Here', type(f_name))
    # print(f_name)
    NORM_H = 300
    NORM_W = 300
    for i in range(22136):
        image = next(iter(f_name))
        image = tf.io.read_file(img_dir + image + '.jpg')
        image = tf.io.decode_jpeg(image, channels=3)
        image = tf.image.resize(image, [NORM_H, NORM_W])
        image = tf.cast(image / 255., tf.float32)
        image = tf.expand_dims(image, 0)
        yield [image]

frozen_graph='./tflite_graph.pb'
input_arrays=["normalized_input_image_tensor"]
output_arrays=['TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3']
input_shapes={"normalized_input_image_tensor":[1,300,300,3]}
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(frozen_graph,input_arrays,output_arrays,input_shapes=input_shapes)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
# converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
# converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]

# Float 16
# converter.target_spec.supported_types = [tf.float16]

# Float 16 activations with int8 weights
# converter.target_spec.supported_ops = [tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8, tf.lite.OpsSet.TFLITE_BUILTINS]

converter.representative_dataset=rep_data_gen
converter.allow_custom_ops=True

tflite_quant_model = converter.convert()

# Save the model.
with open('ssd_mobilenet_v1_voc0712_int8.tflite', 'wb') as f:
    f.write(tflite_quant_model)
```

I trained a Mobilenet_ssd and converted it to a int8 quantized TFLite model by post-training quantization.
But the accuracy of int8 quantized TFLite model drop about 30% mAP for the Pascal VOC dataset.
Is there any method to fine-tune or retrain the TFLite model?
I tried the quantization-aware training, but quantization-aware training add FakeQuantWithMinMaxVars node unsupported by Arm NN.

And can I just quantize the weight to int8 and activation still remain FP32?

If I just use converter.optimizations = [tf.lite.Optimize.DEFAULT], the model will be converted to uint8 or int8?

What is the exact function of the following two commands?
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]

**Comment by amahendrakar** [comment]
@ivs-pychen,
On running the code, I am facing an error stating `OSError: File './tflite_graph.pb' does not exist.`. 

Could you please provide the complete code and all the supporting files necessary to reproduce the issue reported here. Thanks!

**Comment by ivs-pychen** [comment]
The following zip file is the code used to convert the pb to the tflite. But the dataset is too large to upload. The dataset is pascal voc.
[code_pb.zip](https://github.com/tensorflow/tensorflow/files/5444815/code_pb.zip)

**Comment by jvishnuvardhan** [comment]
@ivs-pychen This is a stale issue. Is this still an issue for you?

As there were lot of improvements since the issue opened, can you please try latest versions and let us know whether this is still an issue for you? As the accuracy dropped with `int8` model, did you try `float` model? Thanks!
