### ISSUE TITLE
training keras Sequential model with python generator raise error: AttributeError: 'tuple' object has no attribute 'rank'

### ISSUE THREAD

**Issue by over-shine** [tensorflow/tensorflow#44285]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.3
- Python version: 3.7.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cu101
- GPU model and memory: Quadro M6000 24G

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When training a Sequential model by fit function with python generator as inputs, it raise AttributeError: 'tuple' object has no attribute 'rank'. The python generator yield a tuple (x, y), which follows the tf document of fit function.

**Describe the expected behavior**
I want to know how to make it.

**Standalone code to reproduce the issue**
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np

train_time = pd.read_csv("./train.csv")
train = pd.read_csv("./train_v1.csv")
x_train = train[["year", 'month', 'day', 'hour', 'label']]
y_train = train['label']
test = pd.read_csv("./test_v1.csv")

def train_dataset(x):
    for i in range(0, len(x)):
        if i < 23:
            feature = x[["year", 'month', 'day', 'hour', 'label']][0:i + 1]
        else:
            feature = x[["year", 'month', 'day', 'hour', 'label']][i - 23:i + 1]
        feature = np.asarray(feature)
        feature[i, -1] = 0
        yield tf.expand_dims(feature, 0), x["label"][i]

def test_dataset(x):
    for i in range(0, len(x)):
        if i < 24:
            yield tf.expand_dims(x[["year", 'month', 'day', 'hour', 'label']][0:i], 0), 0
        else:
            yield tf.expand_dims(x[["year", 'month', 'day', 'hour', 'label']][1 - 24:i], 0), 0

model = keras.Sequential()
model.add(keras.layers.LSTM(200, input_shape=[None, 5]))
model.add(keras.layers.Dropout(0.3))
model.add(keras.layers.Dense(100))
model.add(keras.layers.Dense(1))

train_generator = train_dataset(train)
test_generator = test_dataset(test)
model.compile(loss=keras.losses.mean_absolute_error, metrics=keras.metrics.mean_absolute_error)

model.fit(x=train_generator, y=None, epochs=100)

pre = model.predict(test_generator)

**Other info / logs** 
Traceback (most recent call last):
  File "D:/code/competetion/railway station/model.py", line 43, in <module>
    model.fit(x=train_generator, y=None, epochs=100)
  File "C:\Anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1063, in fit
    steps_per_execution=self._steps_per_execution)
  File "C:\Anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 1117, in __init__
    model=model)
  File "C:\Anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 805, in __init__
    output_shapes = nest.map_structure(_get_dynamic_shape, peek)
  File "C:\Anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\util\nest.py", line 635, in map_structure
    structure[0], [func(*x) for x in entries],
  File "C:\Anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\util\nest.py", line 635, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "C:\Anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 801, in _get_dynamic_shape
    if shape.rank is None:
AttributeError: 'tuple' object has no attribute 'rank'

**Comment by Saduf2019** [comment]
@over-shine 
The code provided has indentation issues,please share indented code or is possible share a colab gist with the error reported.

**Comment by over-shine** [comment]
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np

train_time = pd.read_csv("./train.csv")
train = pd.read_csv("./train_v1.csv")
x_train = train[["year", 'month', 'day', 'hour', 'label']]
y_train = train['label']
test = pd.read_csv("./test_v1.csv")

def train_dataset(x):
    for i in range(0, len(x)):
        if i < 23:
            feature = x[["year", 'month', 'day', 'hour', 'label']][0:i + 1]
        else:
            feature = x[["year", 'month', 'day', 'hour', 'label']][i - 23:i + 1]
        feature = np.asarray(feature)
        feature[i, -1] = 0
        yield tf.expand_dims(feature, 0), x["label"][i]

def test_dataset(x):
    for i in range(0, len(x)):
        if i < 23:
            yield tf.expand_dims(x[["year", 'month', 'day', 'hour', 'label']][0:i], 0), 0
        else:
            yield tf.expand_dims(x[["year", 'month', 'day', 'hour', 'label']][1 - 24:i], 0), 0

model = keras.Sequential()
model.add(keras.layers.LSTM(200, input_shape=[None, 5]))
model.add(keras.layers.Dropout(0.3))
model.add(keras.layers.Dense(100))
model.add(keras.layers.Dense(1))

train_generator = train_dataset(train)
test_generator = test_dataset(test)
model.compile(loss=keras.losses.mean_absolute_error, metrics=keras.metrics.mean_absolute_error)

model.fit(x=train_generator, y=None, epochs=100)

pre = model.predict(test_generator)

**Comment by over-shine** [comment]
`import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np

train_time = pd.read_csv("./train.csv")
train = pd.read_csv("./train_v1.csv")
x_train = train[["year", 'month', 'day', 'hour', 'label']]
y_train = train['label']
test = pd.read_csv("./test_v1.csv")

def train_dataset(x):
    for i in range(0, len(x)):
        if i < 23:
            feature = x[["year", 'month', 'day', 'hour', 'label']][0:i + 1]
        else:
            feature = x[["year", 'month', 'day', 'hour', 'label']][i - 23:i + 1]
        feature = np.asarray(feature)
        feature[i, -1] = 0
        yield tf.expand_dims(feature, 0), x["label"][i]

def test_dataset(x):
    for i in range(0, len(x)):
        if i < 23:
            yield tf.expand_dims(x[["year", 'month', 'day', 'hour', 'label']][0:i], 0), 0
        else:
            yield tf.expand_dims(x[["year", 'month', 'day', 'hour', 'label']][1 - 24:i], 0), 0

model = keras.Sequential()
model.add(keras.layers.LSTM(200, input_shape=[None, 5]))
model.add(keras.layers.Dropout(0.3))
model.add(keras.layers.Dense(100))
model.add(keras.layers.Dense(1))

train_generator = train_dataset(train)
test_generator = test_dataset(test)
model.compile(loss=keras.losses.mean_absolute_error, metrics=keras.metrics.mean_absolute_error)

model.fit(x=train_generator, y=None, epochs=100)

pre = model.predict(test_generator)`

**Comment by over-shine** [comment]
```python
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np

train_time = pd.read_csv("./train.csv")
train = pd.read_csv("./train_v1.csv")
x_train = train[["year", 'month', 'day', 'hour', 'label']]
y_train = train['label']
test = pd.read_csv("./test_v1.csv")

def train_dataset(x):
    for i in range(0, len(x)):
        if i < 23:
            feature = x[["year", 'month', 'day', 'hour', 'label']][0:i + 1]
        else:
            feature = x[["year", 'month', 'day', 'hour', 'label']][i - 23:i + 1]
        feature = np.asarray(feature)
        feature[i, -1] = 0
        yield tf.expand_dims(feature, 0), x["label"][i]

def test_dataset(x):
    for i in range(0, len(x)):
        if i < 23:
            yield tf.expand_dims(x[["year", 'month', 'day', 'hour', 'label']][0:i], 0), 0
        else:
            yield tf.expand_dims(x[["year", 'month', 'day', 'hour', 'label']][1 - 24:i], 0), 0

model = keras.Sequential()
model.add(keras.layers.LSTM(200, input_shape=[None, 5]))
model.add(keras.layers.Dropout(0.3))
model.add(keras.layers.Dense(100))
model.add(keras.layers.Dense(1))

train_generator = train_dataset(train)
test_generator = test_dataset(test)
model.compile(loss=keras.losses.mean_absolute_error, metrics=keras.metrics.mean_absolute_error)

model.fit(train_generator, epochs=100)

pre = model.predict(test_generator)
```

**Comment by over-shine** [comment]
I am sorry, the tf version  is 2.1

**Comment by Saduf2019** [comment]
@over-shine 
Please share all dependencies to replicate the issue, i ran the code and  face "FileNotFoundError: [Errno 2] No such file or directory: './train.csv'" error

**Comment by over-shine** [comment]
This is a part of train_v1.csv
```csv
,year,month,day,hour,label
0,2012,8,25,0,8
1,2012,8,25,1,2
2,2012,8,25,2,6
3,2012,8,25,3,2
4,2012,8,25,4,2
5,2012,8,25,5,2
6,2012,8,25,6,2
7,2012,8,25,7,2
8,2012,8,25,8,6
9,2012,8,25,9,2
10,2012,8,25,10,2
11,2012,8,25,11,6
12,2012,8,25,12,4
13,2012,8,25,13,2
14,2012,8,25,14,6
15,2012,8,25,15,2
16,2012,8,25,16,2
17,2012,8,25,17,2
18,2012,8,25,18,2
19,2012,8,25,19,2
20,2012,8,25,20,2
21,2012,8,25,21,6
22,2012,8,25,22,2
23,2012,8,25,23,2
24,2012,8,26,0,4
```

This is  a part of test_v1.csv
```csv
,Unnamed: 0,year,month,day,hour,label
0,0,2014,6,25,0,0
1,1,2014,6,25,1,0
2,2,2014,6,25,2,0
3,3,2014,6,25,3,0
4,4,2014,6,25,4,0
5,5,2014,6,25,5,0
6,6,2014,6,25,6,0
7,7,2014,6,25,7,0
8,8,2014,6,25,8,0
9,9,2014,6,25,9,0
10,10,2014,6,25,10,0
11,11,2014,6,25,11,0
12,12,2014,6,26,12,0
13,13,2014,6,26,13,0
14,14,2014,6,26,14,0
15,15,2014,6,26,15,0
16,16,2014,6,26,16,0
17,17,2014,6,26,17,0
18,18,2014,6,26,18,0
19,19,2014,6,26,19,0
20,20,2014,6,26,20,0
21,21,2014,6,26,21,0
22,22,2014,6,26,22,0
23,23,2014,6,26,23,0
24,24,2014,6,27,12,0
25,25,2014,6,27,13,0
26,26,2014,6,27,14,0
27,27,2014,6,27,15,0
28,28,2014,6,27,16,0
29,29,2014,6,27,17,0
30,30,2014,6,27,18,0
31,31,2014,6,27,19,0
32,32,2014,6,27,20,0
33,33,2014,6,27,21,0
34,34,2014,6,27,22,0
35,35,2014,6,27,23,0
36,36,2014,6,28,0,0
37,37,2014,6,28,1,0
38,38,2014,6,28,2,0
39,39,2014,6,28,3,0
40,40,2014,6,28,4,0
41,41,2014,6,28,5,0
42,42,2014,6,28,6,0
```

**Comment by Saduf2019** [comment]
I m able to replicate the issue faced, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/2b25ebedc984251f6ac76021c122b59d/untitled458.ipynb)

**Comment by over-shine** [comment]
So, how to deal it?

**Comment by lizhaozhi** [comment]
> So, how to deal it?

Hi, I got the same error. Did you fix it?

**Comment by swight-prc** [comment]
In my case, the issue lay with passing Pandas dataframes. In this case, it might be 

See this:
https://github.com/tensorflow/tensorflow/blob/v2.3.1/tensorflow/python/keras/engine/data_adapter.py#L1011-L1019

At that point, it's going to try to convert things to tensors. But it only checks for ndarrays and sparse arrays.

For some reason I can't find `gen_array_ops` in the repo, so I can't confirm, but I don't think tf.expand_dims is meant to take anything but tensors, so it might be generating unexpected results when it receives a numpy array.

You might try using numpy to expand your dimensions instead of tensorflow, and yielding numpy arrays instead of tensors.

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210528, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/68ae40894a34760320c15a277723cc5f/44285.ipynb). Thanks!

**Comment by sachinprasadhs** [comment]
Could you please refer to the solutions provided in these [1](https://stackoverflow.com/questions/62744659/) & [2](https://github.com/tensorflow/agents/issues/363) links and let us know the outcome of it. Thanks!

**Comment by over-shine** [comment]
The solution may be https://github.com/tensorflow/tensorflow/issues/44285#issuecomment-742885714

**Comment by sachinprasadhs** [comment]
If the below solution worked, could you please close the issue, Thanks!
> The solution may be [#44285 (comment)](https://github.com/tensorflow/tensorflow/issues/44285#issuecomment-742885714)
