### ISSUE TITLE
Is padding also required in model.predict function?

### ISSUE THREAD

**Issue by Vignesh1-art** [tensorflow/tensorflow#44297]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by PrattJena** [comment]
The question does not mentions which padding are we talking about so I will answer wrt CNN . No padding is not required in model.predict function. Its only used in conv2D while making a CNN. You can find more about padding [here](https://stackoverflow.com/questions/37674306/what-is-the-difference-between-same-and-valid-padding-in-tf-nn-max-pool-of-t).

**Comment by Vignesh1-art** [comment]
> The question does not mentions which padding are we talking about so I will answer wrt CNN . No padding is not required in model.predict function. Its only used in conv2D while making a CNN. You can find more about padding [here](https://stackoverflow.com/questions/37674306/what-is-the-difference-between-same-and-valid-padding-in-tf-nn-max-pool-of-t).

I am talking about LSTM

**Comment by PrattJena** [comment]
I think this [link](https://github.com/keras-team/keras/issues/2375) is very helpful in answering your question .

**Comment by ravikyram** [comment]
@Vignesh1-art 

Padding is not required in model.predict function. As suggested by @PrattJena you can go through the [link](https://github.com/keras-team/keras/issues/2375) which explains clearly about padding.

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!
