### ISSUE TITLE
Building TF-2.2 OpenCL triSYCL-1.2 on macOS-10.15 with GCC-4.9 and Bazel-2.0.0 Failed

### ISSUE THREAD

**Issue by XDflight** [tensorflow/tensorflow#44292]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Catalina (macOS-10.15)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): source
- TensorFlow version: r2.2
- Python version: 3.6.1
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): GCC-4.9
- CUDA/cuDNN version: None (OpenCL-1.2 with triSYCL-1.2)
- GPU model and memory: Intel Iris Graphics 550 1536MB

**Describe the problem**
Errors occurred when I was trying to build TensorFlow-2.2 from source code. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
(venv) localhost:src daqirui$ ./configure
WARNING: Running Bazel server needs to be killed, because the startup options are different.
You have bazel 2.0.0 installed.
Please specify the location of python. [Default is /Users/daqirui/PycharmProjects/TF2-Mac/venv/bin/python]: 


Found possible Python library paths:
  /Users/daqirui/PycharmProjects/TF2-Mac/venv/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/Users/daqirui/PycharmProjects/TF2-Mac/venv/lib/python3.6/site-packages]

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: y
OpenCL SYCL support will be enabled for TensorFlow.

Please specify which C++ compiler should be used as the host C++ compiler. [Default is /usr/bin/g++]: /usr/local/bin/c++-4.9


Please specify which C compiler should be used as the host C compiler. [Default is /usr/bin/gcc]: /usr/local/bin/gcc-4.9


Do you wish to build TensorFlow with ComputeCPP support? [Y/n]: n
No ComputeCPP support will be enabled for TensorFlow.

Please specify the location of the triSYCL include directory. (Use --config=sycl_trisycl when building with Bazel) [Default is /usr/local/triSYCL/include]: 


Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: n
Clang will not be downloaded.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: -march=native -Wno-sign-compare -O0


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Do you wish to build TensorFlow with iOS support? [y/N]: n
No iOS support will be enabled for TensorFlow.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=ngraph         # Build with Intel nGraph support.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v2             # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=nonccl         # Disable NVIDIA NCCL support.
Configuration finished
```
```
(venv) localhost:src daqirui$ /usr/local/bin/bazel build //tensorflow/tools/pip_package:build_pip_package --config=sycl_trisycl --config=opt --config=v2 --local_ram_resources=2048
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=133
ERROR: Config value sycl_trisycl is not defined in any .rc file
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I tried to deleted `--config=sycl_trisycl` but it occurred another error `ERROR: Config value opt is not defined in any .rc file`. And I also found out that the configure file `.tf_configure.bazelrc` seemed not being detected by Bazel. So I renamed it into `.bazelrc` which I deleted the prefix. This time, Bazel detected it. But it did work either that `ERROR: Config value xla is not defined in any .rc file`. By the way, I need to clarify that the reason I used `/usr/local/bin/bazel` instead of `bazel` is that I've installed two versions of Bazel. One is 3.7.0, and one is 2.0.0 because TF-2.2 needs it. I don't know why Bazelisk cannot work properly since it can't download the right version automatically. And command `/usr/local/bin/bazel` refers to 2.0.0, which `bazel` refers to 3.7.0. But both of them can't work well (same error). I hope that someone could solve my issue. This is my `.tf_configure.bazelrc` file: 
```
build --action_env PYTHON_BIN_PATH="/Users/daqirui/PycharmProjects/TF2-Mac/venv/bin/python"
build --action_env PYTHON_LIB_PATH="/Users/daqirui/PycharmProjects/TF2-Mac/venv/lib/python3.6/site-packages"
build --python_path="/Users/daqirui/PycharmProjects/TF2-Mac/venv/bin/python"
build --config=xla
build --config=sycl
build --action_env HOST_CXX_COMPILER="/usr/local/bin/c++-4.9"
build --action_env HOST_C_COMPILER="/usr/local/bin/gcc-4.9"
build --action_env TF_NEED_COMPUTECPP="0"
build --action_env TRISYCL_INCLUDE_DIR="/usr/local/triSYCL/include"
build:opt --copt=-march=native
build:opt --copt=-Wno-sign-compare
build:opt --copt=-O0
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test:v1 --test_tag_filters=-benchmark-test,-no_oss,-gpu,-nomac,-no_mac,-oss_serial
test:v1 --build_tag_filters=-benchmark-test,-no_oss,-gpu,-nomac,-no_mac
test:v2 --test_tag_filters=-benchmark-test,-no_oss,-gpu,-nomac,-no_mac,-oss_serial,-v1only
test:v2 --build_tag_filters=-benchmark-test,-no_oss,-gpu,-nomac,-no_mac,-v1only
build --action_env TF_CONFIGURE_IOS="0"
```

**Comment by XDflight** [comment]
I've made some progress. But it's still not working. 
```
(venv) localhost:src daqirui$ bazel build //tensorflow/tools/pip_package:build_pip_package --config=sycl_trisycl --config=opt --config=v2 --config=noaws --config=nogcp --config=nohdfs --config=nonccl --local_ram_resources=2048
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [v2]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=133
INFO: Reading rc options for 'build' from /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from /Users/daqirui/PycharmProjects/TF2-Mac/src/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/Users/daqirui/PycharmProjects/TF2-Mac/venv/bin/python --action_env PYTHON_LIB_PATH=/Users/daqirui/PycharmProjects/TF2-Mac/venv/lib/python3.6/site-packages --python_path=/Users/daqirui/PycharmProjects/TF2-Mac/venv/bin/python --config=xla --config=sycl --action_env HOST_CXX_COMPILER=/usr/local/bin/c++-4.9 --action_env HOST_C_COMPILER=/usr/local/bin/gcc-4.9 --action_env TF_NEED_COMPUTECPP=0 --action_env TRISYCL_INCLUDE_DIR=/usr/local/triSYCL/include --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:sycl in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc: --crosstool_top=@local_config_sycl//crosstool:toolchain --define=using_sycl=true --action_env TF_NEED_OPENCL_SYCL=1
INFO: Found applicable config definition build:sycl_trisycl in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc: --define=using_trisycl=true
INFO: Found applicable config definition build:opt in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.tf_configure.bazelrc: --copt=-march=native --copt=-Wno-sign-compare --copt=-O0 --host_copt=-march=native --define with_default_optimizations=true
INFO: Found applicable config definition build:v2 in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:noaws in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc: --define=no_aws_support=true
INFO: Found applicable config definition build:nogcp in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc: --define=no_gcp_support=true
INFO: Found applicable config definition build:nohdfs in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc: --define=no_hdfs_support=true
INFO: Found applicable config definition build:nonccl in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc: --define=no_nccl_support=true
INFO: Found applicable config definition build:macos in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Call stack for the definition of repository 'io_bazel_rules_docker' which is a git_repository (rule definition at /private/var/tmp/_bazel_daqirui/c16b9230c8e6c6d13b7a65f321c3dea6/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - /private/var/tmp/_bazel_daqirui/c16b9230c8e6c6d13b7a65f321c3dea6/external/bazel_toolchains/repositories/repositories.bzl:37:9
 - /Users/daqirui/PycharmProjects/TF2-Mac/src/WORKSPACE:37:1
ERROR: /private/var/tmp/_bazel_daqirui/c16b9230c8e6c6d13b7a65f321c3dea6/external/local_config_sycl/crosstool/BUILD:12:1: @local_config_sycl//crosstool:cc-compiler-local: missing value for mandatory attribute 'toolchain_config' in 'cc_toolchain' rule
INFO: Call stack for the definition of repository 'com_google_absl' which is a tf_http_archive (rule definition at /Users/daqirui/PycharmProjects/TF2-Mac/src/third_party/repo.bzl:134:19):
 - /Users/daqirui/PycharmProjects/TF2-Mac/src/tensorflow/workspace.bzl:186:5
 - /Users/daqirui/PycharmProjects/TF2-Mac/src/WORKSPACE:19:1
INFO: Call stack for the definition of repository 'sobol_data' which is a third_party_http_archive (rule definition at /Users/daqirui/PycharmProjects/TF2-Mac/src/third_party/repo.bzl:219:28):
 - /Users/daqirui/PycharmProjects/TF2-Mac/src/third_party/sobol_data/workspace.bzl:6:5
 - /Users/daqirui/PycharmProjects/TF2-Mac/src/tensorflow/workspace.bzl:66:5
 - /Users/daqirui/PycharmProjects/TF2-Mac/src/tensorflow/workspace.bzl:101:5
 - /Users/daqirui/PycharmProjects/TF2-Mac/src/WORKSPACE:19:1
ERROR: /private/var/tmp/_bazel_daqirui/c16b9230c8e6c6d13b7a65f321c3dea6/external/local_config_sycl/crosstool/BUILD:12:1: Target '@local_config_sycl//crosstool:empty' contains an error and its package is in error and referenced by '@local_config_sycl//crosstool:cc-compiler-local'
ERROR: /private/var/tmp/_bazel_daqirui/c16b9230c8e6c6d13b7a65f321c3dea6/external/local_config_sycl/crosstool/BUILD:5:1: Target '@local_config_sycl//crosstool:cc-compiler-local' contains an error and its package is in error and referenced by '@local_config_sycl//crosstool:toolchain'
ERROR: /private/var/tmp/_bazel_daqirui/c16b9230c8e6c6d13b7a65f321c3dea6/external/bazel_tools/tools/cpp/BUILD:58:1: every rule of type cc_toolchain_alias implicitly depends upon the target '@local_config_sycl//crosstool:toolchain', but this target could not be found because of: Target '@local_config_sycl//crosstool:toolchain' contains an error and its package is in error
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed
INFO: Elapsed time: 542.845s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (161 packages loaded, 3609 targets configured)
    Fetching @local_config_python; fetching 6s
```

**Comment by XDflight** [comment]
I've also tried to rerun `./configure`. But it didn't work either.

**Comment by XDflight** [comment]
> I've made some progress. But it's still not working.
> 
> ```
> (venv) localhost:src daqirui$ bazel build //tensorflow/tools/pip_package:build_pip_package --config=sycl_trisycl --config=opt --config=v2 --config=noaws --config=nogcp --config=nohdfs --config=nonccl --local_ram_resources=2048
> Extracting Bazel installation...
> Starting local Bazel server and connecting to it...
> WARNING: The following configs were expanded more than once: [v2]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
> INFO: Options provided by the client:
>   Inherited 'common' options: --isatty=1 --terminal_columns=133
> INFO: Reading rc options for 'build' from /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc:
>   Inherited 'common' options: --experimental_repo_remote_exec
> INFO: Reading rc options for 'build' from /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc:
>   'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
> INFO: Reading rc options for 'build' from /Users/daqirui/PycharmProjects/TF2-Mac/src/.tf_configure.bazelrc:
>   'build' options: --action_env PYTHON_BIN_PATH=/Users/daqirui/PycharmProjects/TF2-Mac/venv/bin/python --action_env PYTHON_LIB_PATH=/Users/daqirui/PycharmProjects/TF2-Mac/venv/lib/python3.6/site-packages --python_path=/Users/daqirui/PycharmProjects/TF2-Mac/venv/bin/python --config=xla --config=sycl --action_env HOST_CXX_COMPILER=/usr/local/bin/c++-4.9 --action_env HOST_C_COMPILER=/usr/local/bin/gcc-4.9 --action_env TF_NEED_COMPUTECPP=0 --action_env TRISYCL_INCLUDE_DIR=/usr/local/triSYCL/include --action_env TF_CONFIGURE_IOS=0
> INFO: Found applicable config definition build:v2 in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
> INFO: Found applicable config definition build:xla in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
> INFO: Found applicable config definition build:sycl in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc: --crosstool_top=@local_config_sycl//crosstool:toolchain --define=using_sycl=true --action_env TF_NEED_OPENCL_SYCL=1
> INFO: Found applicable config definition build:sycl_trisycl in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc: --define=using_trisycl=true
> INFO: Found applicable config definition build:opt in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.tf_configure.bazelrc: --copt=-march=native --copt=-Wno-sign-compare --copt=-O0 --host_copt=-march=native --define with_default_optimizations=true
> INFO: Found applicable config definition build:v2 in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
> INFO: Found applicable config definition build:noaws in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc: --define=no_aws_support=true
> INFO: Found applicable config definition build:nogcp in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc: --define=no_gcp_support=true
> INFO: Found applicable config definition build:nohdfs in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc: --define=no_hdfs_support=true
> INFO: Found applicable config definition build:nonccl in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc: --define=no_nccl_support=true
> INFO: Found applicable config definition build:macos in file /Users/daqirui/PycharmProjects/TF2-Mac/src/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
> DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
> DEBUG: Call stack for the definition of repository 'io_bazel_rules_docker' which is a git_repository (rule definition at /private/var/tmp/_bazel_daqirui/c16b9230c8e6c6d13b7a65f321c3dea6/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
>  - /private/var/tmp/_bazel_daqirui/c16b9230c8e6c6d13b7a65f321c3dea6/external/bazel_toolchains/repositories/repositories.bzl:37:9
>  - /Users/daqirui/PycharmProjects/TF2-Mac/src/WORKSPACE:37:1
> ERROR: /private/var/tmp/_bazel_daqirui/c16b9230c8e6c6d13b7a65f321c3dea6/external/local_config_sycl/crosstool/BUILD:12:1: @local_config_sycl//crosstool:cc-compiler-local: missing value for mandatory attribute 'toolchain_config' in 'cc_toolchain' rule
> INFO: Call stack for the definition of repository 'com_google_absl' which is a tf_http_archive (rule definition at /Users/daqirui/PycharmProjects/TF2-Mac/src/third_party/repo.bzl:134:19):
>  - /Users/daqirui/PycharmProjects/TF2-Mac/src/tensorflow/workspace.bzl:186:5
>  - /Users/daqirui/PycharmProjects/TF2-Mac/src/WORKSPACE:19:1
> INFO: Call stack for the definition of repository 'sobol_data' which is a third_party_http_archive (rule definition at /Users/daqirui/PycharmProjects/TF2-Mac/src/third_party/repo.bzl:219:28):
>  - /Users/daqirui/PycharmProjects/TF2-Mac/src/third_party/sobol_data/workspace.bzl:6:5
>  - /Users/daqirui/PycharmProjects/TF2-Mac/src/tensorflow/workspace.bzl:66:5
>  - /Users/daqirui/PycharmProjects/TF2-Mac/src/tensorflow/workspace.bzl:101:5
>  - /Users/daqirui/PycharmProjects/TF2-Mac/src/WORKSPACE:19:1
> ERROR: /private/var/tmp/_bazel_daqirui/c16b9230c8e6c6d13b7a65f321c3dea6/external/local_config_sycl/crosstool/BUILD:12:1: Target '@local_config_sycl//crosstool:empty' contains an error and its package is in error and referenced by '@local_config_sycl//crosstool:cc-compiler-local'
> ERROR: /private/var/tmp/_bazel_daqirui/c16b9230c8e6c6d13b7a65f321c3dea6/external/local_config_sycl/crosstool/BUILD:5:1: Target '@local_config_sycl//crosstool:cc-compiler-local' contains an error and its package is in error and referenced by '@local_config_sycl//crosstool:toolchain'
> ERROR: /private/var/tmp/_bazel_daqirui/c16b9230c8e6c6d13b7a65f321c3dea6/external/bazel_tools/tools/cpp/BUILD:58:1: every rule of type cc_toolchain_alias implicitly depends upon the target '@local_config_sycl//crosstool:toolchain', but this target could not be found because of: Target '@local_config_sycl//crosstool:toolchain' contains an error and its package is in error
> ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed
> INFO: Elapsed time: 542.845s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (161 packages loaded, 3609 targets configured)
>     Fetching @local_config_python; fetching 6s
> ```

Sorry, I forgot to mention that this progress was made by recloning TensorFlow-2.2. I think the previous one was missing some important files.

**Comment by sanatmpa1** [comment]
@XDflight,

Can you try building the latest stable version of Tensorflow i.e `2.6.0` using this [guide](https://www.tensorflow.org/install/source) for MacOS and let us know if the issue still persists in the newer version? Thanks!
