### ISSUE TITLE
missing folder absl? 

### ISSUE THREAD

**Issue by CppProgrammer23** [tensorflow/tensorflow#44290]
As I see, there's a folder called absl which doesn't exist. For instance, this include won't work: #include "absl/strings/str_join.h" and a lot of missing file for C++

**Comment by ravikyram** [comment]
@CppProgrammer23 

Can you please fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Please, elaborate the issue. Please, let us know which link you are referring to. Thanks!

**Comment by CppProgrammer23** [comment]
in this link: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/bfc_allocator.cc
that file contains an #include"absl/strings/string_view.h" but there's no folder in the repos called absl

**Comment by kumariko** [comment]
@CppProgrammer23 Could you please refer to [**`link1`**](https://github.com/tensorflow/tensorflow/issues/22240) , [**`link2`**](https://github.com/lysukhin/tensorflow-object-detection-cpp/issues/5) and [**`comment`**](https://github.com/tensorflow/tensorflow/issues/22007#issuecomment-424553600) and let us know if it helps. Thanks!
