### ISSUE TITLE
Strange error when I try to use tf.roll in a custom loss function

### ISSUE THREAD

**Issue by TStein81** [tensorflow/tensorflow#44296]
Hello, I would love if anyoen could point me  in a good direction to find why I am getting the following error when I try to use a custom loss function like:

def lfunction(y_true, y_pred):
 
  mask = K.variable(np.array([1.0,0.0,0.0,0.0,0.0]))
  squared = (y_true - y_pred)**2
  
  mass_mal_to_bk = tf.roll(y_pred,1,axis=1)*mask
  
  add_mass_mal_to_bk = y_true * mass_mal_to_bk
 
  return squared + add_mass_mal_to_bk

The error I get is this:"

tensorflow.python.framework.errors_impl.FailedPreconditionError:  Error while reading resource variable _AnonymousVar84 from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/_AnonymousVar84/class tensorflow::Var does not exist.
         [[node loss/predictions_loss/batata/mul/ReadVariableOp (defined at C:\Users\tiago\Anaconda3\envs\Aqula36\lib\site-packages\keras\backend\tensorflow_backend.py:3009) ]] [Op:__inference_keras_scratch_graph_10394]

Sorry to bother with that, but the message  gives me no clue on what is going on.

**Comment by amahendrakar** [comment]
@TStein81,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. Thanks!
