### ISSUE TITLE
Quantized MobileBERT and ALBERT models performing very poorly

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#44306]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

The Model Maker tool provides an [easy to follow guide](https://www.tensorflow.org/lite/tutorials/model_maker_text_classification) to train a custom text classifier by fine-tuning the pre-trained MobileBERT weights. The guide uses [this MobileBERT model](https://tfhub.dev/google/mobilebert/uncased_L-24_H-128_B-512_A-4_F-4_OPT/1) from TensorFlow Hub. 

Now, once should be able to directly use this TF-Hub model as a part of a Keras model (which is exactly what Model Maker does) and train it. I tried doing the same and I have been successful but when I evaluated the TFLite variant of the model on the test set, the performance of the model significantly drops from 90% to 49%. The same happens with the [ALBERT model](https://tfhub.dev/tensorflow/albert_lite_base/1) as well. 

I DID use the proper tokenizers for the respective models as one can see in the notebooks mentioned below. I fine-tuning on the SST-2 dataset as used in the Model Maker Text Classification guide. 

What's wrong here?

**Describe the expected behavior**

The TFLite models should match the original model performance. 

**Standalone code to reproduce the issue**
* [ALBERT model training and conversion notebook](https://github.com/sayakpaul/BERT-for-Mobile/blob/master/ALBERT_Keras.ipynb)
* [TFLite ALBERT model evaluation](https://github.com/sayakpaul/BERT-for-Mobile/blob/master/Evaluation_SST_2_ALBERT.ipynb)
* [MobileBERT model training and conversion notebook](https://github.com/sayakpaul/BERT-for-Mobile/blob/master/MobileBERT_Keras.ipynb)
* [TFLite MobileBERT model evaluation](https://colab.research.google.com/gist/sayakpaul/27f97101ca06b80c14d29ecf1afdccc8/evaluation_sst-2_albert.ipynb)

**Comment by renjie-liu** [comment]
That's really strange since Model maker works properly (Yuqi probably can help with that).

BTW, wonder how the tf performs? I can see only training accuracy, have you tried the inference accuracy?

Thanks!

**Comment by sayakpaul** [comment]
The validation accuracy is already present in the training notebooks mentioned above.

**Comment by sayakpaul** [comment]
Any updates on this?

**Comment by sayakpaul** [comment]
I tried to follow the exact same workflow with Hugging Face's MobileBERT and the accuracy is still the same - https://colab.research.google.com/gist/sayakpaul/9fb955c973b8fbfcc94a557d27445044/albert_keras.ipynb. 

Pretty weird! :o

**Comment by sayakpaul** [comment]
@MeghnaNatraj would you be able to take a look at this issue or point me in the right direction?

**Comment by MeghnaNatraj** [comment]
Here's a [modified notebook](https://colab.research.google.com/gist/MeghnaNatraj/c03f6da6078a30929bf9a56de71f5192/albert_keras.ipynb#scrollTo=2qOcNEU7BFoH). Looks like the TF model and TFLite float model predictions are the same. Could you again compare this and verify if this is true? Could you print some of the TF model outputs, and compare them to ground truth. And finally compare this to the TFlite outputs? It also looks like the model’s last layer is (None, 128) - is it supposed to be (None, 1)?

**Comment by sayakpaul** [comment]
Thank you very much for looking into this @MeghnaNatraj. 

> It also looks like the model’s last layer is (None, 128) - is it supposed to be (None, 1)?

Yes, it happens with Hugging Face's MobileBERT version as we are taking the last hidden state from the pooled output. 

But when you see [my original notebook](https://github.com/sayakpaul/BERT-for-Mobile/blob/master/MobileBERT_Keras.ipynb) (that uses MobileBERT from Hub) it is `(None, 1)`. If you follow this notebook then it'd error out during the conversion step (TensorFlow 2.3.0) - `ValueError: Input 3 of node StatefulPartitionedCall/functional_1/hub_keras_layer_v1v2/StatefulPartitionedCall was passed float from Func/StatefulPartitionedCall/input/_3:0 incompatible with expected resource.`

Hence, I had used a nightly build to do the conversion but that exact version (`2.4.0-dev20200810`) isn't available anymore and subsequent ones aren't able to communicate with Colab GPU since the Colab CUDA version is 10.1 (refer to https://github.com/tensorflow/tensorflow/issues/42957).

So, the long story cut short is I couldn't verify your findings on the original MobileBERT notebook.

**Comment by sayakpaul** [comment]
Same drill with ALBERT - https://colab.research.google.com/gist/sayakpaul/fc63c91b1f6e38fc859a3e5c3d310e7d/albert_keras.ipynb.

**Comment by MeghnaNatraj** [comment]
Got it, if there is a way you can verify this with an older version of TF or until the issue is resolved - it would be helpful for us to figure out where the error originated and debug this. If this is not urgent, you can reply on this thread once you can verify.

**Comment by sayakpaul** [comment]
Sure. @MeghnaNatraj I will try. I am guessing TensorFlow 2.2 would produce the same error here.

**Comment by sayakpaul** [comment]
@MeghnaNatraj so here are some more findings. I had to spin up a notebook on AI Platform that supported CUDA 11.0. So, here's my setup - 

![image](https://user-images.githubusercontent.com/22957388/100964656-21c24380-354f-11eb-80e5-265e66779921.png)

I installed 2.5.0-dev20201202 of `tf-nightly`. As expected the conversion went seamlessly well. Now coming to your point on output mismatches here are some findings: 

## ALBERT

* Original model predictions 
  ```
  array([[0.45974356],
       [0.40282163],
       [0.50713634],
       [0.4738442 ],
       [0.39585397],
       [0.45194846],
       [0.432267  ],
       [0.4871237 ],
       [0.48969463],
       [0.48001567],
       [0.46036363],
       [0.49563286],
       [0.49220225],
       [0.46842712],
       [0.48277178],
       [0.45274204],
       [0.5044237 ],
       [0.4519858 ],
       [0.43670607],
       [0.4987168 ]], dtype=float32)
  ```

* TFLite (float model) predictions
  ```
  [array([0.9806177], dtype=float32),
	array([nan], dtype=float32),
	array([nan], dtype=float32),
	array([nan], dtype=float32),
	array([nan], dtype=float32),
	array([nan], dtype=float32),
	array([nan], dtype=float32),
	array([nan], dtype=float32),
	array([nan], dtype=float32),
	array([nan], dtype=float32),
	array([nan], dtype=float32),
	array([nan], dtype=float32),
	array([nan], dtype=float32),
	array([nan], dtype=float32),
	array([nan], dtype=float32),
	array([nan], dtype=float32),
	array([nan], dtype=float32),
	array([nan], dtype=float32),
	array([nan], dtype=float32),
	array([nan], dtype=float32)]
  ```

I have faced this `NaN` issue before (refer to https://github.com/tensorflow/tensorflow/issues/43719). When I tried to run inference with the dynamic-range quantized model the runtime crashed. 

Here's an interesting observation regarding the model training. The model training logs report a decent validation accuracy - 
```
2807/2807 [==============================] - 1758s 623ms/step - loss: 0.4047 - accuracy: 0.7907 - val_loss: 0.3459 - val_accuracy: 0.8830
```

But when I ran `model.evaluate()` separately I got surprised - 

```
model.evaluate(train_ds)
2807/2807 [==============================] - 610s 217ms/step - loss: 0.7304 - accuracy: 0.4458
[0.7303553223609924, 0.44579726457595825]
```

```
model.evaluate(valid_ds)
37/37 [==============================] - 8s 205ms/step - loss: 0.6962 - accuracy: 0.5149
[0.69621342420578, 0.5149082541465759]
```

## MobileBERT

* Original TF model predictions

  ```
  array([[9.9999523e-01],
       [3.5430368e-02],
       [9.9836868e-01],
       [9.9768424e-01],
       [1.5873680e-02],
       [9.9999309e-01],
       [8.2542878e-01],
       [9.6560270e-02],
       [9.9333352e-01],
       [1.7254837e-02],
       [9.9999368e-01],
       [5.3525418e-03],
       [8.6974440e-04],
       [4.6796936e-01],
       [2.7280839e-03],
       [9.9999714e-01],
       [5.9698451e-01],
       [9.9830139e-01],
       [3.1085087e-03],
       [9.9264004e-04]], dtype=float32)
  ```

* TFLite model predictions

  ```
   [array([0.7102443], dtype=float32),
	 array([0.57573587], dtype=float32),
	 array([0.70804507], dtype=float32),
	 array([0.60090107], dtype=float32),
	 array([0.45175412], dtype=float32),
	 array([0.7718483], dtype=float32),
	 array([0.655351], dtype=float32),
	 array([0.5626731], dtype=float32),
	 array([0.6212563], dtype=float32),
	 array([0.22457898], dtype=float32),
	 array([0.67261064], dtype=float32),
	 array([0.56146646], dtype=float32),
	 array([0.53055984], dtype=float32),
	 array([0.5748798], dtype=float32),
	 array([0.4939883], dtype=float32),
	 array([0.69004154], dtype=float32),
	 array([0.55181825], dtype=float32),
	 array([0.9738283], dtype=float32),
	 array([0.46502632], dtype=float32),
	 array([0.3641715], dtype=float32)]
  ```

When I tried running inference with the DR quantized model TFLite model, runtime crashed. You would see a bit of discrepancy in between the model training logs and `scores` from `model.evaluate()`. 

**Original model training log**:

```
2807/2807 [==============================] - 628s 210ms/step - loss: 0.4848 - accuracy: 0.7825 - val_loss: 0.2525 - val_accuracy: 0.9117
```

**model.evaluate()**:

```
model.evaluate(train_ds)
2807/2807 [==============================] - 217s 77ms/step - loss: 0.1372 - accuracy: 0.9493
[0.13716447353363037, 0.9492791295051575]
```

```
model.evaluate(valid_ds)
37/37 [==============================] - 3s 76ms/step - loss: 0.2525 - accuracy: 0.9117
[0.2524813711643219, 0.911697268486023]
```

To help you reproduce these I am attaching the notebooks and the `SavedModel` files. 

## Important files

* Notebooks
  [Notebooks.zip](https://github.com/tensorflow/tensorflow/files/5633734/Notebooks.zip)
* `SavedModel`
  * https://storage.googleapis.com/demo-experiments/albert.tar.gz
  * https://storage.googleapis.com/demo-experiments/mobilebert.tar.gz

Let me know if you need more details.

**Comment by pjpratik** [comment]
@sayakpaul I was trying to reproduce this in TF 2.11. I got data access forbidden error. Can you please check [this](https://colab.research.google.com/gist/pjpratik/49028e7ef71fb197678dcb4d7013b677/albert_keras.ipynb) gist and help me with this. Thank you.
