### ISSUE TITLE
Model.predict() subsequent predictions returning nan (tf-nightly TF 2.4.0-dev20201023, NVIDIA-SMI 456.71, CUDA 11.1, cuDNN 8.0.4, RTX 3090)

### ISSUE THREAD

**Issue by fussners** [tensorflow/tensorflow#44309]
This seems to be an interesting issue with serial predictions using RTX 3090 with updated version of tf-nightly and CUDA 11.1 (Windows 10, cuDNN 8.0.4). I tried submitting the issue on stackoverflow without any resolution. 

I'm passing a single image_array: (IMAGE_DATA TYPE <class 'numpy.ndarray'> IMAGE_DATA.SHAPE (1, 640, 640, 3)) to MODEL.predict(IMAGE_DATA). The first time the model is compiled, the predictions make sense (accurate bounding boxes, class type). However, the second time a new image or a copy of the first image is passed to MODEL.predict() it returns predictions that don't make any sense (see below). This is a YOLOv3 model.

PREDICTED_BOXES = model.predict(IMAGE_DATA)
LEN(PREDICTED_BOXES) = 25200
[[ nan nan nan nan nan nan]
[ nan nan nan nan nan nan]
[ nan nan nan nan nan nan]
...
[640. 640. inf inf 1. 1.]
[640. 640. inf inf 1. 1.]
[640. 640. inf inf 1. 1.]]

--> postprocessing of boxes returns [x1, y1, x2, y2, class_prob, class_num]:
[0.000e+00 0.000e+00 1.919e+03 1.079e+03 1.000e+00 0.000e+00]

If I run the same code/images using only my CPU on the same computer as the RTX 3090 it correctly predicts on all images. If I run the same code/images on a different computer with a GTX 1060 and TF 2.3.0, CUDA 10.1 NVIDIA-SMI 441.87 it correctly predicts on all images.

Has anyone else had a similar issue and are there any thoughts on what the problem might be or fixes/workarounds?

Thanks

**Comment by Saduf2019** [comment]
@fussners 
Please share simple stand alone code for us to replicate the issue faced or if possible share a colab gist with error reported.

**Comment by wwww666** [comment]
I have the same configuration as you, But I am stuck in the epoch and there is no error. Have you ever encountered this problem?

**Comment by ajaymaity** [comment]
Did you get resolution on this? I am facing the same issue, unfortunately!

**Comment by rafikg** [comment]
@ajaymaity I had the same error. Did you fix it?

**Comment by lucastan1996** [comment]
@rafikg @ajaymaity @fussners 
Yo guys, anyone got the issue solved? lol
I'm facing this exact same problem, tested on RTX3060, RTX3070 laptop, RTX2080
RTX3000 series can't run with CUDNN 7
On RTX2080 I tried tensorflow 2.3 or below, it is working perfectly. Tensorflow 2.4 & 2.5 is return all NAN except the first prediction
