### ISSUE TITLE
OperatorNotAllowedInGraphError in tf.debugging.Assert and tf.keras.Input

### ISSUE THREAD

**Issue by w-shimaya** [tensorflow/tensorflow#44313]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**:
    - Yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
    - Linux Ubuntu 18.04.4 LTS
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:
-   **TensorFlow installed from (source or binary)**:
    - `pip install tensorflow`
-   **TensorFlow version (use command below)**:
    - v2.3.0-54-gfcc4b966f1 2.3.1
-   **Python version**:
    - 3.6.9
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:
    - 10.1/7.6.5
-   **GPU model and memory**:
    - Geforce RTX 2080 SUPER (8GB)
-   **Exact command to reproduce**:
    - The minimal python script which can reproduce the issue is in the Source code / logs section below.

**Describe the current behavior**
I would like to check if inputs to a `Model` is valid or not by using the `tf.debugging.Assert()` function.
But the straightforward implementation results in an OperatorNotAllowedInGraphError:
```
Traceback (most recent call last):
  File "reproduce_tfbug.py", line 9, in <module>
    [inputs]
  File "/home/shimaya/venv/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/shimaya/venv/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py", line 247, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
  File "/home/shimaya/venv/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 151, in Assert
    if not condition:
  File "/home/shimaya/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 877, in __bool__
    self._disallow_bool_casting()
  File "/home/shimaya/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 490, in _disallow_bool_casting
    self._disallow_in_graph_mode("using a `tf.Tensor` as a Python `bool`")
  File "/home/shimaya/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 479, in _disallow_in_graph_mode
    " this function with @tf.function.".format(task))
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.
```
This seems to occur only when the argument of the `Assert()` is a `tf.keras.Input` tensor.

**Describe the expected behavior**
I expect this simple assertion works. I believe such simple syntax will be helpful to many TensorFlow users.

**Standalone code to reproduce the issue**
```
import tensorflow as tf
import tensorflow.keras as K

if __name__ == "__main__":
    inputs = K.Input(shape=(10, 10))

    tf.debugging.Assert(
        tf.reduce_all(inputs >= 0.), 
        [inputs]
    )

    # any operations or model definitions follow
    # ...
```

**Comment by Saduf2019** [comment]
@w-shimaya 
Please provide complete stand alone indented code such that we can replicate or if possible share a colab gist with the error reported.

**Comment by w-shimaya** [comment]
@Saduf2019 
Thank you for your response. 
I'd be glad if you could refer to this [gist](https://gist.github.com/w-shimaya/46c35998d8ed53a6cd03ca48d3ad1ad6) to reproduce the issue. 
Also, at least in my environment, the standalone code I attached can reproduce the issue.
```
import tensorflow as tf
import tensorflow.keras as K

if __name__ == "__main__":
    inputs = K.Input(shape=(10, 10))

    tf.debugging.Assert(
        tf.reduce_all(inputs >= 0.), 
        [inputs]
    )

    # any operations or model definitions follow
    # ...
```
Thanks!

**Comment by Saduf2019** [comment]
i ran the code shared and am able to replicate the issue reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/b920f5b78c9a4d9a9f9024adabb1c3ec/untitled456.ipynb). Thanks!

**Comment by ymodak** [comment]
`tf.debugging` API does not support Keras symbolic tensors.
Most of the `tf.debugging` ops expects a  numeric tensor for assertion which does not fall in line with keras inputs.
See https://github.com/tensorflow/tensorflow/issues/41627 to know more.

**Comment by w-shimaya** [comment]
@ymodak 
Thank you for your information!
I will put tf.debugging operations in a custom layer for now and there seems to be no problem.
I'd be happy if you are planning to add features such as assertion of Keras symbolic tensors officially.

**Comment by ymodak** [comment]
Thanks for confirming. I will close this issue now and update this thread when have more information.
