### ISSUE TITLE
Forward mode ad, directional derivatives

### ISSUE THREAD

**Issue by vladfi1** [tensorflow/tensorflow#4431]
Say I have `outputs = f(inputs)` and `g` of the same shape as `inputs`. I'd like to compute the directional derivative of `outputs` with respect to `inputs` in the direction `g` - in other words, the derivative of `f(inputs + alpha * g)` with respect to `alpha` at the point `alpha=0`.

This is a straightforward application of forward-mode automatic differentiation, which should be pretty easy to implement (much easier than the already-implemented reverse-mode ad). Are there any plans to add this feature?

**Comment by tatatodd** [comment]
@andydavis1 or @rmlarsen might know whether there are such plans.

**Comment by rmlarsen** [comment]
I don't think we have any near term plans for this.

**Comment by Sohl-Dickstein** [comment]
As a breadcrumb for future people trying to solve this problem, 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/nn/python/ops/fwd_gradients.py
performs forward mode differentiation.

**Comment by PyFormulae** [comment]
Has anyone figured this out? Id like to compute the nth order directional derivatives in the direction of the gradient. I'd like to make an optimizer using that.
