### ISSUE TITLE
wrong tf.control_dependencies using tf.case  and tf.cond

### ISSUE THREAD

**Issue by cherishlc** [tensorflow/tensorflow#4432]
add tf.control_dependencies in one branch of tf.case infulunce the other brach:
tf version: rc10

as we can see below, the tfvar is increasing no mather brach f1 or f2 is executed
change tf.case to tf.cond will get the same output.

`def testTF_case_with_control_dependencies():
    
    isTraining=tf.placeholder(tf.bool,shape=[])
    tfvar=tf.Variable(tf.constant(0),tf.int32);
    
    increase_tfvar_op=tf.assign_add(tfvar.ref(), 1);
    
    sess=tf.Session()
    sess.run(tf.initialize_all_variables())

    def f1():
        print ('f1')
        with tf.control_dependencies([increase_tfvar_op]):
            return -tfvar;  #if return tfvar directly, no control_dependencies is added
    
    def f2():
        print('f2')
        with tf.control_dependencies([]):
            return tfvar*10;
    caseResult = tf.case([(isTraining, f1)], default=f2)
    
    b=True;
    for t in range(4):
        b=not b;
        print('\n------')
        print('isTraining: ',end='')
        print(b)
        beforeCase=sess.run(tfvar)
        print('\ttfvar before run case: %d'%beforeCase)
        r=sess.run(caseResult,feed_dict={isTraining:b})
        print('case result:%d'%r)
        aftercase=sess.run(tfvar)
        print('\ttfvar after run case: %d'%aftercase)`

output:
f2
f2
f1

------
isTraining: False
	tfvar before run case: 0
case result:10
	tfvar after run case: 1

------
isTraining: True
	tfvar before run case: 1
case result:-2
	tfvar after run case: 2

------
isTraining: False
	tfvar before run case: 2
case result:30
	tfvar after run case: 3

------
isTraining: True
	tfvar before run case: 3
case result:-4
	tfvar after run case: 4

**Comment by jmchen-g** [comment]
I believe this is similar to the cond() and you can find the explanation here: https://www.tensorflow.org/versions/r0.10/api_docs/python/control_flow_ops.html#cond

Basically the increase op will always run in both cases.

**Comment by cherishlc** [comment]
@jmchen-g thanks,  but the document is not consistent with the actual behavier.

set b to False, and and tf.Print to f1() will get no output at all, which means f1 is not invoked when the condition is False.

the changed f1():

`    def f1():
        print ('f1')
        with tf.control_dependencies([increase_tfvar_op]):
            return tf.Print(-tfvar, data=[tfvar]) ;`

**Comment by yaroslavvb** [comment]
This is how cond works, here's some explanation -- http://stackoverflow.com/questions/37063952/confused-by-the-behavior-of-tf-cond/37064128#37064128

Basically it's how TensorFlow runtime works:
- increase_tfvar_op is a dependency of f1
- f1 and f2 are dependencies of cond
- therefore increase_tfvar_op is a dependency of cond

Dependencies must be computed before tf.cond is ready to execute. It's smart enough to figure out that f1 doesn't need to be executed, but not smart enough to figure out that increase_tfvar_op doesn't need to be.

**Comment by cherishlc** [comment]
@yaroslavvb thanks for you explanation~  
I follow the stackoverflow solution and it works.

**Just move the dependency into f1()!!!**  

For the convenience of other people, the correct version is :+1: 
`def testTF_case_with_control_dependencies():
    
    isTraining=tf.placeholder(tf.bool,shape=[])
    tfvar=tf.Variable(tf.constant(0),tf.int32);
    
    #increase_tfvar_op=tf.assign_add(tfvar.ref(), 1); #this line is moved to f1()
    
    sess=tf.Session()
    sess.run(tf.initialize_all_variables())

    def f1():
        print ('f1')
        increase_tfvar_op=tf.assign_add(tfvar.ref(), 1);
        with tf.control_dependencies([increase_tfvar_op]):
            return -tfvar;  #if return tfvar directly, no control_dependencies is added
    
    def f2():
        print('f2')
        with tf.control_dependencies([]):
            return tfvar*10;
    caseResult = tf.case([(isTraining, f1)], default=f2)
    
    b=True;
    for t in range(4):
        b=not b;
        print('\n------')
        print('isTraining: ',end='')
        print(b)
        beforeCase=sess.run(tfvar)
        print('\ttfvar before run case: %d'%beforeCase)
        r=sess.run(caseResult,feed_dict={isTraining:b})
        print('case result:%d'%r)
        aftercase=sess.run(tfvar)
        print('\ttfvar after run case: %d'%aftercase)`
