### ISSUE TITLE
Request for person_detect.tflite file used in micro vision demo of Tensorflow Lite

### ISSUE THREAD

**Issue by IlkayW** [tensorflow/tensorflow#44320]
Hello,

is it possible to get the Tensorflow Lite file for the person detection of the micro vision demo?
The original or unquantized model file would be helpful for my research as well.
Is there a way to get the person_detect.h5 file, if it exists?

Thank you in advance,

Ilkay

**Comment by Paryavi** [comment]
Hi @petewarden and Tensorflow people , I need the person_detect.tflite for my research too! I have ESP32-CAM and ESP-EYE.
// don't have a file system. It was created using the command:
// xxd -i person_detect.tflite > person_detect_model_data.cc

Where can we find the person_detect.tflite?
Thank You!
