### ISSUE TITLE
cannot see keras properly in tf-nightly-gpu install

### ISSUE THREAD

**Issue by apurvakalia** [tensorflow/tensorflow#44327]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: tf-nightly-gpu
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.1
- GPU model and memory: nVidia MX250, 4GB

**Describe the problem**
I installed tf-nightly-gpu in my environment and first ran into a missing dll issue (#44291) which was resolved. Now I can import keras but do not seem to see it or use anything inside it. See commands below

**Provide the exact sequence of commands / steps that you executed before running into the problem**

from tensorflow import keras
from keras import regularizers
Traceback (most recent call last):
File "", line 1, in
ModuleNotFoundError: No module named 'keras'
dir()
['annotations', 'builtins', 'doc', 'loader', 'name', 'package', 'spec', 'keras', 'tensorflow']

As you can see, keras is visible as a package after importing it, but does not seem to work properly.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@apurvakalia,
I was able to import the modules without any issues, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/88250876a6c9d55b367affcac8afb26b/44327.ipynb). Could you please check if you are facing the same issue in a virtual environment?

Also, try importing `tensorflow.keras` instead of `keras` and check if it works. Thanks!
