### ISSUE TITLE
why gradient of clip_by_value(x) is zero, when x is outside of range?

### ISSUE THREAD

**Issue by iperov** [tensorflow/tensorflow#44333]
I agree with derivative of mathematical notation,
because output value is not changing when x is outside of range

![xnviewmp_2020-10-26_22-02-22](https://user-images.githubusercontent.com/8076202/97212824-54538080-17da-11eb-9d23-d76828e3cbd5.jpg)

But let look at it from the ML perspective.

Let `x = -2`
we can just simply decide `x = x+1` 

thus `Clip(x, -1, 1) = x + 1 = -1`

gradient for `x+y` is `1` for both

Therefore gradient of clip(x) should be 1 for any value and range ?

**Comment by bhack** [comment]
If you want to preserve the gradient you could take a look at https://www.tensorflow.org/probability/api_docs/python/tfp/math/clip_by_value_preserve_gradient

**Comment by iperov** [comment]
thanks
