### ISSUE TITLE
Bug in CosineSimilarity 

### ISSUE THREAD

**Issue by abhinavsp0730** [tensorflow/tensorflow#44343]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Colab

while using ```CosineSimilarity``` loss  with the array,
```
    rng = jax.random.PRNGKey(42)

    y_true = jax.random.randint(rng, shape=(2, 3), minval=0, maxval=2)
    y_pred = jax.random.uniform(rng, shape=(2, 3))
```
I'm getting the following error:
``` 
TypeError: Cannot convert 1e-12 to EagerTensor of dtype int32
```
**Colab Notebook to reproduce error**
https://colab.research.google.com/drive/1diVmzp2V-jqsH8UamIDRSmbp5gLGRAtN?usp=sharing

**Do you want to contribute?**
Yes, I want to contribute please give me some more detail about the bug and I'll definetely raise a PR to fix the bug.

**Comment by bhack** [comment]
`cosine_loss(y_true.astype(dtype=np.float32), y_pred).numpy()`

**Comment by abhinavsp0730** [comment]
Thanks, @bhack  I'm closing this issue as it has been solved.
