### ISSUE TITLE
cmake support of 2.0.0-rc2

### ISSUE THREAD

**Issue by oldoldman** [tensorflow/tensorflow#44345]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0.0-rc2
- Python version: 3.5
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): 19.23.28105.4
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
## Please help!

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@oldoldman 

Bazel is the only supported way to build TensorFlow, sorry. Since contrib is being removed as a part of TF 2.0, the cmake files will go away at the same time.Thanks!

**Comment by oldoldman** [comment]
Ok. Thanks.
