### ISSUE TITLE
[Violation] 'requestAnimationFrame' handler took <N>ms tfjs hand model demo

### ISSUE THREAD

**Issue by delebash** [tensorflow/tensorflow#44356]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
Windows 10 x64
Chrome Version 86.0.4240.111 (Official Build) (64-bit)
tfjs version used in online demo at https://storage.googleapis.com/tfjs-models/demos/handpose/index.html

**Describe the current behavior**
1) In Chrome open https://storage.googleapis.com/tfjs-models/demos/handpose/index.html
2) Open DevTools
3) After the detection is running refresh the page
Error [Violation] 'requestAnimationFrame' handler took <N>ms is thrown after refresh

**Describe the expected behavior**
No error after refresh

**Comment by amahendrakar** [comment]
@delebash,
TensorFlow.js issues are tracked in tensorflow/tfjs repo. Could you please submit a new issue from [this link](https://github.com/tensorflow/tfjs/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by delebash** [comment]
Thanks sorry about that :)
