### ISSUE TITLE
InvalidArgumentError: In[0] is not a matrix. Instead it has shape [] [Op:MatMul]

### ISSUE THREAD

**Issue by akorneychuk** [tensorflow/tensorflow#44359]
# Tensorflow Custom Activation Func
There is a simple pure TensorFlow multi-layer perceptron with custom activation function and derivative for gradient descent
The built-in **tf.nn.relu** approach is works well and count the gradient properly

**System information**
- MAC OS Catalina 10.15.7
- Python v3.8.5
- TensorFlow v2.3.1

**Standalone code to reproduce the issue**
https://github.com/akorneychuk/tensorflow_custom_activation

**Stacktrace** 
`Traceback (most recent call last):
  File "/private/var/root/PycharmProjects/untitled_sec/venv/lib/python3.8/site-packages/tensorflow/python/eager/backprop.py", line 162, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "/private/var/root/PycharmProjects/untitled_sec/venv/lib/python3.8/site-packages/tensorflow/python/ops/math_grad.py", line 1694, in _MatMulGrad
    grad_a = gen_math_ops.mat_mul(grad, b, transpose_b=True)
  File "/private/var/root/PycharmProjects/untitled_sec/venv/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5624, in mat_mul
    _ops.raise_from_not_ok_status(e, name)
  File "/private/var/root/PycharmProjects/untitled_sec/venv/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: In[0] is not a matrix. Instead it has shape [] [Op:MatMul]`

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/98d2d829ee3eac8c1119e501e738c86a/44359.ipynb). Thanks!

**Comment by AndreyKorney** [comment]
Couple of screenshots with **custom activation** and **tf.nn.relu** implementation:
https://drive.google.com/drive/folders/1izkwRj7IaxXMs1Y7Uq6uZ7QRtEw1G8cL?usp=sharing

**Comment by gowthamkpr** [comment]
@akorneychuk Please go through the above comment where the implementation is shown clearly. Thanks!

**Comment by AndreyKorney** [comment]
@gowthamkpr 
Frankly speaking I didn't got your point. Which particular comment should I follow to check the clear implementation? 
Perhaps I have missed something. I you meant the original gist https://colab.research.google.com/gist/amahendrakar/98d2d829ee3eac8c1119e501e738c86a/44359.ipynb
it still fails with the same error.
Thanks in advance!

**Comment by AndreyKorney** [comment]
Could you please point me what exactly should I do? Thanks!

**Comment by AndreyKorney** [comment]
@gowthamkpr 
Could you please point me what exactly should I do regarding you last comment above.
Thanks in advance!

**Comment by AndreyKorney** [comment]
@gowthamkpr 
Any update on this issue?

**Comment by WindQAQ** [comment]
@AndreyKorney  The way you try to customize gradient is quite outdated. I suggest you do the following things. Though I think your customized gradient is doubtful.

```python
@tf.custom_gradient
def custom_tf_leaky_relu(x):
  y = tf.py_function(np_leaky_relu_32, [x], [tf.float32])
  def grad(g):
    r = tf.math.mod(x, 1)
    n_gr = tf.cast(tf.less_equal(r, 0.5), tf.float32)
    grad_res = g * n_gr
    return grad_res

  return y[0], grad

with tf.GradientTape() as tape:
    # do something

tape.gradient(xxx)
```

**Comment by ravikyram** [comment]
@akorneychuk 

Can you please check @WindQAQ  suggestion and see if it helps you.Thanks!
