### ISSUE TITLE
Tensorflow randomly crashes running multiple consecutive images through classifier model TF_SessionRun() in c api

### ISSUE THREAD

**Issue by starkdg** [tensorflow/tensorflow#44358]
Hi, 

I am hesitant to call this a bug, only because it seems like an obvious use case.  On the other hand, the c api looks pretty basic to me, so I can't figure how what I could be missing here.   Here's all the information I can think of.   Let me know if you need anything else.  I'll be more than happy to oblige.  Thank you.  

**System information**
== check os platform ===============================================
os: Linux
os kernel version: #1 SMP Debian 4.19.132-1 (2020-07-24)
os release version: 4.19.0-10-amd64
os platform: Linux-4.19.0-10-amd64-x86_64-with-debian-10.5
linux distribution: ('debian', '10.5', '')
linux os distribution: ('debian', '10.5', '')
mac version: ('', ('', '', ''), '')
uname: ('Linux', 'starkdg', '4.19.0-10-amd64', '#1 SMP Debian 4.19.132-1 (2020-07-24)', 'x86_64', '')
architecture: ('64bit', 'ELF')
machine: x86_64

== compiler ====================================================
gcc (Debian 8.3.0-6) 8.3.0

Tensorflow version: 2.3.1

**Describe the current behavior**
Performs as expected, except for random crashes on different files - oddly, never the same file. When the same
files are submitted individually, the graph session performs as expected.  There are no log messages to report from tensorflow, just a string of filesystem errors.  Like this:

```
EXT4-fs error (device sda1): ext4_find_entry:1456: inode #390913: common systemd-journal: reading directory lblock 0
```

When this occurs, the only thing possible is a hard reboot.  

A fsck on those file systems reports all fine.  

**Describe the expected behavior**

The program should read all the images in a given directory.  For each image, read the image data, run it through model 
classifier [mobilenetv2](https://storage.googleapis.com/mobilenet_v2/checkpoints/mobilenet_v2_1.4_224.tgz) (Use the frozen.pb model in the download archive), and obtain the feature vector for that image from the model.    

**Standalone code to reproduce the issue**

Here is a basic program to reproduce the issue.  I tried to minimize it as much as possible, but it requires
opencv (v3.4.7) and Boost filesystem and system libraries (v1.67.0)  in order to retrieve all files inside a directory and the
image data for each file.   The directory of images must contain all images  that opencv installation can read. 

OpenCV  v3.4.7
Boost  v1.67.0

```
Invoke program:  ./tftest /path/to/image/files/dir
```

Put the frozen .pb model file in the same directory as the example code.  or change the `model_file` variable in the code so it can read in the model graph.

```
/** 
	g++ -otftest tftest.cpp -g -O0 -Wall -lboost_filesystem -lboost_system 
                   -lopencv_core -lopencv_imgcodecs -lopencv_imgproc -ltensorflow
 **/
#include <iostream>
#include <cstdlib>
#include <string>
#include <cassert>
#include <boost/filesystem.hpp>
#include <opencv2/core/core_c.h>
#include <opencv2/imgproc/imgproc_c.h>
#include <opencv2/imgcodecs/imgcodecs_c.h>
#include <tensorflow/c/c_api.h>

using namespace std;
using namespace cv;

namespace fs=boost::filesystem;

static const string model_file = "mobilenet_v2_1.4_224_frozen.pb";       //location of frozen model file 
static const string input_layer = "input";                                                   // input output layers
static const string output_layer = "MobilenetV2/Logits/AvgPool";

static int Height = 224;   // target image size 
static int Width = 224;

void NoOpDeAlloc(void *data, size_t len, void *arg){}

void freebuffer(void *data, size_t len){
	free(data);
}

CvMat* load_image(const string &filename, const int height, const int width){

	CvMat *src = cvLoadImageM(filename.c_str(), CV_LOAD_IMAGE_COLOR);
	if (src == NULL) return NULL;

	CvMat *img_prime = cvCreateMat(src->rows, src->cols, CV_32FC3);
	CvMat *img_resized = cvCreateMat(height, width, CV_32FC3);
	CvMat *dst = cvCreateMat(height, width, CV_32FC3);
	CvMat *div = cvCreateMat(height, width, CV_32FC3);

	/* convert to float type */
	cvConvertScale(src, img_prime, 1, 0);

	/* resize to heightxwidth */
	cvResize(img_prime, img_resized, CV_INTER_CUBIC);

	/* normalize values */
	CvScalar norm_constant = {255, 255, 255};
	cvSet(div, norm_constant, NULL);
	cvDiv(img_resized, div, dst, 1);

	cvReleaseMat(&src);
	cvReleaseMat(&img_resized);
	cvReleaseMat(&img_prime);
	cvReleaseMat(&div);
	return dst;
}

TF_Buffer* readfromfile(const string &filename){
	FILE *file = fopen(filename.c_str(), "rb");
	if (file == NULL) return NULL;
	
	fseek(file, 0, SEEK_END);
	size_t file_size = ftell(file);
	fseek(file, 0, SEEK_SET);
	assert(file_size > 0);
	
	unsigned char *data = (unsigned char*)malloc(file_size);
	size_t n = fread(data, 1, file_size, file);
	assert(n == file_size);

	TF_Buffer *buf = TF_NewBuffer();
	buf->data = data;
	buf->length = file_size;
	buf->data_deallocator = freebuffer;
	fclose(file);
	return buf;
}


int ProcessFiles(const fs::path &dirname){
	fs::recursive_directory_iterator dir(dirname), end;

	int ndims = 4;
	int64_t dims[4] = { 1, Height, Width, 3};

	cout << "TF Model graph setup" << endl;
	TF_Graph *graph = TF_NewGraph();
	TF_Status *status = TF_NewStatus();

	TF_ImportGraphDefOptions *opts = TF_NewImportGraphDefOptions();
	TF_Buffer *graph_def = readfromfile(model_file);
	assert(graph_def != NULL);

	TF_GraphImportGraphDef(graph, graph_def, opts, status);
	assert(TF_GetCode(status) == TF_OK);
	
	TF_SessionOptions *sess_opts = TF_NewSessionOptions();
	TF_Session *sess = TF_NewSession(graph, sess_opts, status);
	TF_Tensor *img_tensor;
	TF_Tensor *output_tensor;
	TF_Output input = { TF_GraphOperationByName(graph, input_layer.c_str()), 0 };
	TF_Output output = { TF_GraphOperationByName(graph, output_layer.c_str()), 0 };
	assert(input.oper != NULL);
	assert(output.oper != NULL);
	
	cout << "Read files " << endl;
	
	int count = 0;
	for (;dir!=end;++dir){
		string filename = dir->path().string();
		if (fs::is_directory(dir->status())){
			cout << "directory: " << filename << endl;
		} else if (fs::is_regular_file(dir->status())){
			CvMat *img = load_image(filename, Height, Width);
			if (img != NULL){
				cout << dec << "(" << ++count << ") " << filename << endl;

				int total = Height*Width*3;
				img_tensor = TF_NewTensor(TF_FLOAT, dims, ndims, (void*)img->data.fl,
										  total*sizeof(float), NoOpDeAlloc, NULL);
				assert(img_tensor != NULL);
				
				TF_SessionRun(sess, NULL, &input, &img_tensor, 1,
							  &output, &output_tensor, 1,
							  NULL, 0, NULL, status);

				if (TF_GetCode(status) != TF_OK){
					cout << "unale to complete session: " << TF_Message(status) << endl;
					break;
				}

				TF_DeleteTensor(img_tensor);
				TF_DeleteTensor(output_tensor);
				img_tensor = NULL;
				output_tensor = NULL;
				cvReleaseMat(&img);
			}
		} else {
			cout << "special file: " << filename << endl;
		}
	}

	TF_DeleteBuffer(graph_def);
	TF_DeleteSessionOptions(sess_opts);
	TF_DeleteImportGraphDefOptions(opts);
	TF_DeleteGraph(graph);
	TF_DeleteSession(sess, status);
	TF_DeleteStatus(status);
	return count;
}

int main (int argc, char **argv){
	assert(argc == 2);
	string dir = argv[1];


	cout << "Tensorflow: " << TF_Version() << endl;
	
	cout << "directory: " << dir << endl;
	
	int n = ProcessFiles(dir);
	
	cout << "Processed files: " << n << endl;
	cout << "Done" << endl;
	return 0;
}
```

**Other info / logs** Include any logs or source code that would be helpful to

**Comment by Saduf2019** [comment]
@starkdg 
What is the tf version you are facing the issue on.

**Comment by starkdg** [comment]
@Sadaf2019    
Tensorflow version 2.3.0

**Comment by starkdg** [comment]
Just tried compiling from source from the master branch - version 2.5.0 , but same problem.  
Anyone have any ideas ?

**Comment by starkdg** [comment]
This has been waiting for over 2 weeks now.  Does anyone have any idea as to how to characterize this?

**Comment by tilakrayal** [comment]
@starkdg,
The error message which you are facing suggests that there may be an issue with reading a directory block (lblock 0) in the file system where the `systemd` journal is storedrelated to the systemd-journald service, which is responsible for handling system logs on Linux systems that use systemd.

Also please take a look at this [reference](https://askubuntu.com/questions/905710/ext4-fs-error-after-ubuntu-17-04-upgrade). Thank you!
