### ISSUE TITLE
Couldn't find a way to convert tflite to tensorflow graph

### ISSUE THREAD

**Issue by chenrubin** [tensorflow/tensorflow#44357]
Hello all,

I am new to this world so hopefully my question will be as clear as possible and related to this forum.
I want to be able to convert tflite file to tensorflow graph.
I have tried several ways:

tflite --> onnx : I used
tflite2onnx.convert(tflite_path, onnx_path)
Result:
NotImplementedError: Unsupported TFLite OP: 41
It seems there is an unsupported operations (maybe more) and I was unable to convert

tflite --> pb
I looked on the net and found that it is possible only up to tf 1.9 so I downgraded my tf to 1.9
and tried following the instructions (which included using bazel, couldn't even install bazel)

Anyway Is there a known way (either one of the above or any other you can think of)
that I can use and hopefully works?

Thanks in advance
Chen

**Comment by jdduke** [comment]
There is no way to do this currently. Do you not have access to the original source TensorFlow graph?
