### ISSUE TITLE
Looking for tf-nightly 2.4.0.dev20200817

### ISSUE THREAD

**Issue by jvahl** [tensorflow/tensorflow#44360]
Is there any way to get my hands on the tf-nightly 2.4.0.dev20200817 wheel for py36 / manylinux? I have a code that requires tensorflow >=2.4 but I cannot upgrade to CUDA 11, so the builds that are available on PyPI don't work for me anymore. 

Many thanks!

EDIT: looking for both tf-nightly and tf-nightly-gpu of the same version

**Comment by bhack** [comment]
I don't think so the old one is 2.4.0.dev20200902.

**Comment by ymodak** [comment]
That' correct we don't save nightly packages for longer period of time. Current archive collects nightly packages from the month of september 2020 till date.
See https://pypi.org/project/tf-nightly/#history to know more.

**Comment by jvahl** [comment]
Yup I know the history on PyPI doesn't include versions older than September, was unfortunately too slow to store a copy of the August version while it was up there. Had hoped that you guys would maybe keep it elsewhere. Anyways, thanks for checking.
