### ISSUE TITLE
tf.data.Dataset.from_tensor_slices requests same shape tensors

### ISSUE THREAD

**Issue by Charlestng** [tensorflow/tensorflow#44379]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.3.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
As of now, tf.data.Dataset.from_tensor_slices requests the input tensors to be of the same shape, which is not working very well with the new text preprocessing function tf.keras.preprocessing.text.Tokenizer

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
NLP practionners will benefit from this feature.

**Any Other info.**
Currently it is not possible to create a tensorflow dataset immidiately after using tf.keras.preprocessing.text.Tokenizer because the sequences of idexes generated are'nt all of the same length. This can be solved by using tf.keras.preprocessing.sequence.pad_sequences but it is not very memory friendly as many sequences will be padded with a great deal of unnecessary zeros.
Adding this feature will make it possible to preprocess text data, encode it, put it in a tensor dataset, split between train and test and then pad using .padded_batch method, which way more memory friendly and will make training the model faster as well.

**Comment by aaudiber** [comment]
To achieve this today, you need to use `Dataset.from_generator`.

```
list_of_uneven_length_tensors = [[1], [2, 3, 4], [5, 6]]

def gen():
  for tensor in list_of_uneven_length_tensors:
    yield tensor

ds = tf.data.Dataset.from_generator(gen, output_types=tf.int64)
for elem in ds:
  print(elem)
```

`from_tensor_slices` is named the way it is because it takes a single (rectangular) `Tensor` and iterates through the slices of the tensor. What we could potentially do is add a new `Dataset.from_tensor_list` method which takes a list of tensors and iterates over them. Would that work for your use case here?

**Comment by sanatmpa1** [comment]
@Charlestng,

Can you take a look on the above comment by @aaudiber to use `Dataset.from_generator`, and confirm if that helps? Thanks!
