### ISSUE TITLE
Tflite ops: TensorListReserve, TensorListSetItem, TensorListStack

### ISSUE THREAD

**Issue by Movisoto** [tensorflow/tensorflow#44378]
**System information**
Linux Ubuntu 18.04
TensorFlow installed from source
TensorFlow version 2.1.0

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, FULLY_CONNECTED. Here is a list of operators for which you will need custom implementations: TensorListReserve, TensorListSetItem, TensorListStack.
```

**Standalone code to reproduce the issue** 
https://colab.research.google.com/drive/1jEUZxqM4Olr3Hbiu9WoCpYiVyGGx1ko8?usp=sharing

**Comment by amahendrakar** [comment]
@Movisoto,
I was able to reproduce the issue with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/7fcc19838f87fbaa9f24c701299e50de/44378-2-1.ipynb). However, with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/55e1c38fb617128131ed380ab052bfa9/44378.ipynb#scrollTo=g32rWA9zCLbp) I am facing a different error stating `requires element_shape to be 1D tensor during TF Lite transformation pass`. Please find the attached gist. 

Could you please update TensorFlow to v2.3 and check if you are facing the same issue? Thanks!

**Comment by Movisoto** [comment]
@amahendrakar,
thanks a lot for your response! 
Yes, I got a different error stating `requires element_shape to be 1D tensor during TF Lite transformation pass` while I was using tf v2.3, as I understood the reason is that tf lite converter works only with fixed batch size, nevertheless as I understand I have already set all input shapes and batch size. Could you please help?

Thanks a lot in advance!

**Comment by Movisoto** [comment]
@amahendrakar looking forward to hearing from you! As I researched it should be connected with an unfixed batch size of the model, but I have set all the input shapes

**Comment by jvishnuvardhan** [comment]
@Movisoto Can you please share a standalone code? When I ran your gist, it is throwing an error as shown below. Thanks!

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-15-fee02e8da1f7> in <module>()
      1 config = Config()
----> 2 generator = model.generator
      3 discriminator = model.discriminator
      4 regressor = generator.regressor
      5 smpl = generator.smpl

NameError: name 'model' is not defined
```
