### ISSUE TITLE
why there are no documents about tf.nn.seq2seq   

### ISSUE THREAD

**Issue by sunbo5439** [tensorflow/tensorflow#4437]
the file tensorflow/python/ops/seq2seq contains models like tf.nn.seq2seq.embedding_attention_seq2seq, but there are not any documentation about these models in the online documentation (https://www.tensorflow.org/versions/r0.10/api_docs/python/nn.html#neural-network)

or there is but i didn't find it?

**Comment by jmchen-g** [comment]
@lukaszkaiser Could you take a look at this? Thanks.

**Comment by lukaszkaiser** [comment]
The seq2seq module does not use the dynamic unrolling functions. We need a new module that uses them, and it will probably have a new API and the current seq2seq will be deprecated. That's why we're not documenting it -- because we're not committing to this API and it might go away.
