### ISSUE TITLE
fatal error: fatbinary_section.h: No such file or directory

### ISSUE THREAD

**Issue by ElhamSol** [tensorflow/tensorflow#44389]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3
- Python version: 3.6, 3.7
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 7.5
- CUDA/cuDNN version: 11.1 , 8
- GPU model and memory: RTX 2080 Ti

**Describe the problem**

I am installing TF from the source following steps https://www.tensorflow.org/install/source.
and
https://towardsdatascience.com/how-to-compile-tensorflow-2-3-with-cuda-11-1-8cbecffcb8d3
The build ended up with the error in the following.

INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/nccl_archive/BUILD.bazel:53:1: C++ compilation of rule '@nccl_archive//:device_dlink' failed (Exit 1)
bazel-out/k8-opt/bin/external/nccl_archive/device_dlink.cc:69:10: fatal error: fatbinary_section.h: No such file or directory
 #include <fatbinary_section.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /root/tensorflow/tensorflow/lite/toco/python/BUILD:84:1 C++ compilation of rule '@nccl_archive//:device_dlink' failed (Exit 1)
INFO: Elapsed time: 120.484s, Critical Path: 45.36s
INFO: 989 processes: 989 local.

Please let me know how to fix it as google returns zero search results for it.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

 bazel build --config=cuda //tensorflow/tools/pip_package:build_pip_package

before this I had the following error and fixed it as shown:
Error:
ERROR: /root/tensorflow/tensorflow/stream_executor/cuda/BUILD:144:1: C++ compilation of rule '//tensorflow/stream_executor/cuda:cudart_stub' failed (Exit 1)
tensorflow/stream_executor/cuda/cudart_stub.cc:19:10: fatal error: third_party/gpus/cuda/include/cuda_runtime_api.h: No such file or directory
 #include "third_party/gpus/cuda/include/cuda_runtime_api.h"
 
compilation terminated.
 
Solution:
sudo apt-get install nvidia-cuda-toolkit
 
export CPATH=/usr/local/cuda-11.1/targets/x86_64-linux/include:$CPATH
export LD_LIBRARY_PATH=/usr/local/cuda-11.1/targets/x86_64-linux/lib:$LD_LIBRARY_PATH
export PATH=/usr/local/cuda-11.1/bin:$PATH

I also fixed other errors: 
Edit
third_party/gpus/cuda_configure.bzl
 
 "cudart": _check_cuda_lib_params(
            "cudart",
            cpu_value,
            cuda_config.config["cuda_library_dir"],
            # Comment this out since cudart is still on 11.0 instead of
            # the same as cuda 11.1
            # cuda_config.cuda_version,
            "11.0",
            static = False,
        ),
        "cudart_static": _check_cuda_lib_params(
            "cudart_static",
            cpu_value,
            cuda_config.config["cuda_library_dir"],
            # Comment this out since cudart is still on 11.0 instead of
            # the same as cuda 11.1
            # cuda_config.cuda_version,
            "11.0",
            static = True,
        ),
        "cublas": _check_cuda_lib_params(
            "cublas",
            cpu_value,
            cuda_config.config["cublas_library_dir"],
            # Comment this out since cudart is still on 11.0 instead of
            # the same as cuda 11.1
            # cuda_config.cuda_version,
            "11",
            static = False,
        ),

**Comment by ravikyram** [comment]
@ElhamSol 

Please, see tested build configurations from [here](https://www.tensorflow.org/install/source#gpu).please check if you are facing the same issue with CUDA 10.1 and cuDNN 7.4.

Also, please take a look at #42047 for more information regarding TensorFlow support for CUDA 11. Thanks!

**Comment by ElhamSol** [comment]
@ravikyram Thanks for reply. But, I wasn't able to install tensorflow 2.0.0+ with Cuda 10.1 and that's why I switched to 11.1.
(I'd like to use 2.3.0, so please don't ask me to go back to 2.0.0 as a solution)
I even tried going back to Cunda 10.1, but nvidia doesn't allow it anymore. 
`sudo apt-get -y install cuda-10.1` doesn't work anymore and it forces me to install 11.1.

#42047 doesn't help the issue I posted.
I've been reading on github and stackoverflow for the past week and I was able to solve other errors with them. 
For this one I found zero results in github and google search.

I appreciate it if you could spend some time going through the issue and let me know the solution.
This is for my work and I've been stuck with it for a week.

**Comment by ymodak** [comment]
TF 2.4.0-rc0  pre built pip package released today and it supports cuda 11.
https://github.com/tensorflow/tensorflow/releases/tag/v2.4.0-rc0
Do you still prefer to build from source?

**Comment by ElhamSol** [comment]
> @ravikyram Thanks for reply. But, I wasn't able to install tensorflow 2.0.0+ with Cuda 10.1 and that's why I switched to 11.1.
> (I'd like to use 2.3.0, so please don't ask me to go back to 2.0.0 as a solution)
> I even tried going back to Cuda 10.1, but nvidia doesn't allow it anymore.
> `sudo apt-get -y install cuda-10.1` doesn't work anymore and it forces me to install 11.1.
> 
> #42047 doesn't help the issue I posted.
> I've been reading on github and stackoverflow for the past week and I was able to solve other errors with them.
> For this one I found zero results in github and google search.
> 
> I appreciate it if you could spend some time going through the issue and let me know the solution.
> This is for my work and I've been stuck with it for a week.

I managed to install CUDA 10.1, but now get the following error building TF 2.3.1
ERROR: /root/tensorflow/tensorflow/python/tools/BUILD:314:1 C++ compilation of rule '//tensorflow/core/profiler/internal/gpu:cupti_wrapper' failed (Exit 1)

**Comment by ElhamSol** [comment]
> TF 2.4.0-rc0 pre built pip package released today and it supports cuda 11.0.
> https://github.com/tensorflow/tensorflow/releases/tag/v2.4.0-rc0
> You may have to fall back on cuda 11.0 to use the pre built pip package.
> Also do you still prefer to build TF from source for cuda 11.1?

I tried to use the pre built pip package version 2.3.1 and it ends up being CPU only.
I am not switching back to 11.0.

**Comment by ymodak** [comment]
> I managed to install CUDA 10.1, but now get the following error building TF 2.3.1
> ERROR: /root/tensorflow/tensorflow/python/tools/BUILD:314:1 C++ compilation of rule '//tensorflow/core/profiler/internal/gpu:cupti_wrapper' failed (Exit 1)

Did you add CUPTI to the `$LD_LIBRARY_PATH` environmental variable?
See [linux gpu setup](https://www.tensorflow.org/install/gpu#linux_setup).

**Comment by ElhamSol** [comment]
I did but for some reason it wasn't finding it anyway.

I reinstalled ubuntu, cuda 10.1 and everything and this time pip install tensorflow =2.3.0 worked.
I might have missed a step last time.

**Comment by ravikyram** [comment]
@ElhamSol 

Please, close this thread if your issue was resolved. Thanks!
