### ISSUE TITLE
tf.import_graph_def() requires a non-empty name

### ISSUE THREAD

**Issue by usmankha123** [tensorflow/tensorflow#4438]
After updating version of tenserflow  there is now an issue when loading with my old models. 

./importer.py", line 241, in import_graph_def
    raise ValueError('tf.import_graph_def() requires a non-empty `name` '
ValueError: tf.import_graph_def() requires a non-empty `name` if `input_map` is used.

The same is case when i try colorize model colorize-20160110

how to fix this. The code is given below
import tensorflow as tf
import skimage.transform
from skimage.io import imsave, imread

def load_image(path):
    img = imread(path)
    # crop image from center
    short_edge = min(img.shape[:2])
    yy = int((img.shape[0] - short_edge) / 2)
    xx = int((img.shape[1] - short_edge) / 2)
    crop_img = img[yy : yy + short_edge, xx : xx + short_edge]
    # resize to 224, 224
    img = skimage.transform.resize(crop_img, (224, 224))
    # desaturate image
    return (img[:,:,0] + img[:,:,1] + img[:,:,2]) / 3.0

shark_gray = load_image("shark.jpg").reshape(1, 224, 224, 1)

with open("colorize.tfmodel", mode='rb') as f:
    fileContent = f.read()

graph_def = tf.GraphDef()
graph_def.ParseFromString(fileContent)
grayscale = tf.placeholder("float", [1, 224, 224, 1])
tf.import_graph_def(graph_def, input_map={ "grayscale": grayscale }, name='')

with tf.Session() as sess:
    inferred_rgb = sess.graph.get_tensor_by_name("inferred_rgb:0")
    inferred_batch = sess.run(inferred_rgb, feed_dict={ grayscale: shark_gray })
    imsave("shark-color.jpg", inferred_batch[0])
    print ("saved shark-color.jpg")

**Comment by mrry** [comment]
The old version of `tf.import_graph_def()` was broken if you specified both `input_map` and `name=''`. It looks like the fix is quite easy for your case, though. Simply remove the explicit `name=''` (which is not recommended, since it can lead to unpredictable names for the imported nodes), and use `return_elements=["inferred_rgb:0"]` to get the `inferred_rgb` tensor as a return value from `tf.import_graph_def()`:

```python
# [...]
graph_def = tf.GraphDef()
graph_def.ParseFromString(fileContent)
grayscale = tf.placeholder(tf.float32, [1, 224, 224, 1])
inferred_rgb, = tf.import_graph_def(graph_def, input_map={"grayscale": grayscale },
                                    return_elements=["inferred_rgb:0"])

with tf.Session() as sess:
  inferred_batch = sess.run(inferred_rgb, feed_dict={grayscale: shark_gray})
  imsave("shark-color.jpg", inferred_batch[0])
  print ("saved shark-color.jpg")
```

**Comment by fenderrex** [comment]
>@mrry  Simply remove the explicit name='' (which is not recommended, since it can lead to unpredictable names for the imported nodes)

I was looking over the code i [think](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/importer.py)  trying to find out why my retrained graph is reporting a miss mach in labels and tensor objects, and saw that the name **karg was set default to None. If this variable is not encapsulated should its state ever be able to put it in a state of error? could we call it code cleanup to set the default name to a empty string or are we expecting unicode?

**Comment by mrry** [comment]
@fenderrex I'm not sure I understand your question. The default behavior when `name=None` is to add a prefix of `"import"` (perhaps with a suffix of `"_1"`, `"_2"`, etc. if that prefix has already been used). If there's a particular change you'd suggest, feel free to open a new issue describing it, and we'll take a look!
