### ISSUE TITLE
GPU kernel for SparseSegmentReduction ops.

### ISSUE THREAD

**Issue by Lifann** [tensorflow/tensorflow#44380]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): r.1.5.2
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Hi, I have noticed that the SparseSegmentReduction ops do not have GPU implementation. I was wondering is there any consideration for not implementing GPU version SparseSegmentReduction ops? And will the feature be supported in future version?

**Will this change the current api? How?**
It will not change the current API.

**Who will benefit with this feature?**
People who use GPU to train the sparse networks.

**Any Other info.**

**Comment by rmothukuru** [comment]
@Lifann,
Sorry for the delayed response. Can you please share the reproducible code which demonstrates these Ops doesn't work in GPU? Thanks!
