### ISSUE TITLE
Tensorflow release files missing from PyPi, fallback to local hashing 

### ISSUE THREAD

**Issue by dciborow** [tensorflow/tensorflow#44390]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.2
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip 20.2.4

**Describe the problem**
When using pip-compile to get recreate a requirements file with a hash pointer to tensorflow, the hash must be generated each time. It would be create it the required files/settings were included 

```md
tensorflow-gpu
  Missing release files on PyPI
  Couldn't get hashes from PyPI, fallback to hashing files
  Hashing tensorflow_gpu-2.2.0-cp38-win_amd64.whl
tensorflow-gpu
    Missing release files on PyPI
    Couldn't get hashes from PyPI, fallback to hashing files
    Hashing tensorflow_gpu-2.2.0-cp38-cp38-win_amd64.whl
    Hashing tensorflow_gpu-2.2.0-cp37-cp37m-win_amd64.whl
    Hashing tensorflow_gpu-2.2.0-cp38-cp38-manylinux2010_x86_64.whl
    Hashing tensorflow_gpu-2.2.0-cp35-cp35m-manylinux2010_x86_64.whl
    Hashing tensorflow_gpu-2.2.0-cp36-cp36m-manylinux2010_x86_64.whl
    Hashing tensorflow_gpu-2.2.0-cp35-cp35m-win_amd64.whl
    Hashing tensorflow_gpu-2.2.0-cp36-cp36m-win_amd64.whl
    Hashing tensorflow_gpu-2.2.0-cp37-cp37m-manylinux2010_x86_64.whl
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```shell-script
echo "tensorflow==2.2" > tensorflow.in
pip install pip-tools
pip-compile -v --allow-unsafe --generate-hashes tensorflow.in
```

**Any other info / logs**
Nice to have... not sure how simple it is? But every other package I am working with has this setup properly, so i only notice Tensorflow taking its time.

**Comment by Saduf2019** [comment]
@dciborow 

Please paste the error message (using makrdown formatting around it) instead of screenshotting. Screenshots are not searchable so they don't help in looking for the issue and also don't help other people having the same error from finding about the issue.

**Comment by dciborow** [comment]
@saberkun , done!

**Comment by mihaimaruseac** [comment]
This is likely related to how we're doing the combined pip package. Can you try with 2.3, nightly and (soon) 2.4rc0?
