### ISSUE TITLE
Python3 bug, filter has no len

### ISSUE THREAD

**Issue by phsmit** [tensorflow/tensorflow#444]
I have build the latest source (a5d8217c4ed) and I tried running the mnist tutorial. This fails with:

  File "/l/psmit/tensorflow/env_py3/lib/python3.4/site-packages/tensorflow/python/ops/gradients.py", line 447, in gradients
    if gate_gradients and len(filter(None, in_grads)) > 1:
TypeError: object of type 'filter' has no len()

A filter in py3 is not a list, so it has not length. This could be solved by changing 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/gradients.py#L447

to e.g. sum(1 for _ in filter())

**Comment by girving** [comment]
Good catch.  We should fix this and add a unit test.

**Comment by girving** [comment]
Fix in review.
