### ISSUE TITLE
GradientChecker file not found

### ISSUE THREAD

**Issue by shkr** [tensorflow/tensorflow#4440]
link - https://github.com/tensorflow/tensorflow/tree/r0.10/tensorflow/python/kernel_tests/gradient_checker.py

refered in -
https://www.tensorflow.org/versions/r0.9/how_tos/adding_an_op/index.html#define-the-ops-interface

**Comment by jmchen-g** [comment]
Thanks for reporting. @martinwicke could you take a look at this? Thanks.

**Comment by AndreasMadsen** [comment]
@jmchen-g @martinwicke what is the status? I'm interested in this too.

**Comment by aselle** [comment]
This appears to already be resolved. Thanks!
