### ISSUE TITLE
Keras Sequential Model Not taking IN the data due to Matrix size-incompatible

### ISSUE THREAD

**Issue by Kunal2341** [tensorflow/tensorflow#44404]
I am using the beginner template code from TensorFlow. 

https://www.tensorflow.org/tutorials/quickstart/beginner

The code is 

```


#x_train, y_train, x_test, y_test -- All defined before with images size 28 28 
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])
predictions = model(x_train[:1]).numpy()
predictions
```

When I run the following code I expect this 
array([[-0.2858531 , -0.37892324,  0.25575462, -0.16782898,  0.17269424,
        -0.4606699 , -0.15211505,  0.11725096,  0.58891714, -0.2277292 ]],
      dtype=float32)

The error I get is
InvalidArgumentError: Matrix size-incompatible: In[0]: [28,56], In[1]: [784,1] [Op:MatMul]

The partial code to create the images is --
```

x = img.crop([matrix[0][0]-2, matrix[0][1], matrix[2][0]+2, matrix[2][1]+2])
img = x.resize((28, 28))
display(img.convert('LA'))
lstOfArrays.append(numpy.array(img.convert('LA')))                        

```

---------------------------------------------------------------------------

WARNING:tensorflow:Model was constructed with shape Tensor("flatten_3_input:0", shape=(None, 28, 28), dtype=float32) for input (None, 28, 28), but it was re-called on a Tensor with incompatible shape (28, 28, 2).
WARNING:tensorflow:Layer flatten_3 is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-180-6c835adf6b59> in <module>
----> 1 predictions = model(x_train[:1]).numpy()
      2 predictions

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py in __call__(self, inputs, *args, **kwargs)
    820           with base_layer_utils.autocast_context_manager(
    821               self._compute_dtype):
--> 822             outputs = self.call(cast_inputs, *args, **kwargs)
    823           self._handle_activity_regularization(inputs, outputs)
    824           self._set_mask_metadata(inputs, outputs, input_masks)

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\sequential.py in call(self, inputs, training, mask)
    265       if not self.built:
    266         self._init_graph_network(self.inputs, self.outputs, name=self.name)
--> 267       return super(Sequential, self).call(inputs, training=training, mask=mask)
    268 
    269     outputs = inputs  # handle the corner case where self.layers is empty

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\network.py in call(self, inputs, training, mask)
    715     return self._run_internal_graph(
    716         inputs, training=training, mask=mask,
--> 717         convert_kwargs_to_constants=base_layer_utils.call_context().saving)
    718 
    719   def compute_output_shape(self, input_shape):

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\network.py in _run_internal_graph(self, inputs, training, mask, convert_kwargs_to_constants)
    889 
    890           # Compute outputs.
--> 891           output_tensors = layer(computed_tensors, **kwargs)
    892 
    893           # Update tensor_dict.

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py in __call__(self, inputs, *args, **kwargs)
    820           with base_layer_utils.autocast_context_manager(
    821               self._compute_dtype):
--> 822             outputs = self.call(cast_inputs, *args, **kwargs)
    823           self._handle_activity_regularization(inputs, outputs)
    824           self._set_mask_metadata(inputs, outputs, input_masks)

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\layers\core.py in call(self, inputs)
   1140         outputs = sparse_ops.sparse_tensor_dense_matmul(inputs, self.kernel)
   1141       else:
-> 1142         outputs = gen_math_ops.mat_mul(inputs, self.kernel)
   1143     if self.use_bias:
   1144       outputs = nn.bias_add(outputs, self.bias)

~\Anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_math_ops.py in mat_mul(a, b, transpose_a, transpose_b, name)
   5614         pass  # Add nodes to the TensorFlow graph.
   5615     except _core._NotOkStatusException as e:
-> 5616       _ops.raise_from_not_ok_status(e, name)
   5617   # Add nodes to the TensorFlow graph.
   5618   if transpose_a is None:

~\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py in raise_from_not_ok_status(e, name)
   6604   message = e.message + (" name: " + name if name is not None else "")
   6605   # pylint: disable=protected-access
-> 6606   six.raise_from(core._status_to_exception(e.code, message), None)
   6607   # pylint: enable=protected-access
   6608 

~\Anaconda3\lib\site-packages\six.py in raise_from(value, from_value)

InvalidArgumentError: Matrix size-incompatible: In[0]: [28,56], In[1]: [784,1] [Op:MatMul]

**Comment by amahendrakar** [comment]
@Kunal2341,
Could you please provide the Python script or notebook you are running, so that we can reproduce the issue on our end.

I was able to run the linked tutorial without any issues, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/b85040476f1c7ce097d1d5f204d1fb10/44404.ipynb). Thanks!
