### ISSUE TITLE
num_units in GRU and LSTM layers confuse meaning

### ISSUE THREAD

**Issue by ofiryaish** [tensorflow/tensorflow#44409]
In tf.keras.layers.LSTM tf.keras.layers.GRU layers there is a parameter called num_units. I saw a lot of questions over the internet about this parameter. and there is not clear answer for what this parameter mean expect for the obvious meaning which is the shape of the output. some say that its mean that in each layer there num_units of LSTM or GRU units, some say that it is only one unit of LSTM or GRU, but with num_units hidden units (num_units of tanh, and sigmoids for each  gate and so on..) inside the LSTM or GRU layer. 
I thought it might be propright that the developers of TF will answer one and for all what is the meaning of this parameter.

Thank You

**Comment by ofiryaish** [comment]
Any update with this question?

**Comment by ofiryaish** [comment]
Any update with this question?

**Comment by gowthamkpr** [comment]
@ofiryaish Did you post this question in stackoverflow? Thanks!

**Comment by ofiryaish** [comment]
@gowthamkpr Yes, I tried there also after day or two in in which I didn't get response here, but I wasn't lucky,

**Comment by rmothukuru** [comment]
@ofiryaish,
The argument, `num_units` in an `LSTM Layer` refers to number of `LSTM Units` in that `Layer`, with each `LSTM Unit` comprising the below `Architecture`.

![image](https://user-images.githubusercontent.com/48206667/99224254-fbd93700-280b-11eb-954d-b7f479a5b84c.png)

**Comment by rmothukuru** [comment]
@ofiryaish,
Can you please respond to the above comment. Thanks!

**Comment by ofiryaish** [comment]
@rmothukuru  sorry for not responding.  So if I understand well you are stacking 'num_units' of units in this layer without any connection between them, and you only concatenate their outputs together, right?

**Comment by rmothukuru** [comment]
@ofiryaish,
Yes, something like shown in the screenshot below:

![image](https://user-images.githubusercontent.com/48206667/100097657-db038800-2e82-11eb-8c30-c5ed8e22c55d.png)

The above analysis has been done with respect to the below data:

Number of Input Features => 3 => F1, F2 and F3

Number of Timesteps => 2 => 0 and 1

Number of Hidden Layers => 1

**Number of Units in each Hidden Layer => 5**

Hope this helps. Thanks!

**Comment by ofiryaish** [comment]
@rmothukuru 
Ok, Thank you very much.
