### ISSUE TITLE
pip install tensorflow fails on macOS and Python 3.9

### ISSUE THREAD

**Issue by lutzroeder** [tensorflow/tensorflow#44416]
**System information**
- OS Platform and Distribution: macOS 10.15.7 (19H2)
- TensorFlow version: tf-nightly
- Python version: 3.9.0
- Installed using virtualenv? pip? conda?: pip, venv

**Describe the problem**

```
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```

**Provide the exact sequence of commands that you executed before running into the problem**

```
python3 -m venv ./test
source ./test/bin/activate
python3 -m pip install --quiet --upgrade pip
python3 -m pip install --upgrade tensorflow
```

```
python3 -m venv ./test
source ./test/bin/activate
python3 -m pip install --quiet --upgrade pip
python3 -m pip install --upgrade nightly
```

**Any other info / logs**

Homebrew recently updated to Python 3.9.

@mihaimaruseac @goldiegadde @Saduf2019

**Comment by ravikyram** [comment]
@lutzroeder,
TensorFlow pip packages are compatible with Python 3.5–3.8.

From the below link we can see that the whl files are available upto Python v3.8.
https://pypi.org/project/tf-nightly/2.4.0.dev20201023/#files

Python3.9 is not yet supported. Thanks!

**Comment by mihaimaruseac** [comment]
We have not released anything for python3.9.

Release process is as follows:

1. Ensure all of our dependencies support python3.9 (not yet there)
2. Ensure our code works with all these dependencies on all supported versions of python (at the moment, at least `gast` needs additional support work).
3. Release nightly version supporting the new python version
4. Release a full release.

As we are already doing the 2.4 release, python3.9 support for TF will come in 2.5 release at the earliest.

@ravikyram let's deduplicate to this issue all py39 requests/issues. I'll monitor this one and provide updates as we start adding support.

**Comment by mihaimaruseac** [comment]
Actually, duplicating to #44485 since that one has a better title.

**Comment by emadboctorx** [comment]
@mihaimaruseac When is it expected the 2.5 release? I'm asking because I'm having an [issue](https://github.com/tensorflow/tensorflow/issues/45546) with tensorflow versions 2.2, 2.3, 2.4 in which the GPU usage is 0% during the training unless I disable eager execution using `tf.compat.v1.disable_eager_execution()` hopefully the new release fixes the issue.

**Comment by mihaimaruseac** [comment]
The plan we're having is to have one release per quarter.
