### ISSUE TITLE
Can tflite.interpreter.set_tensor set an inter tensor

### ISSUE THREAD

**Issue by Harleytu** [tensorflow/tensorflow#44418]
**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow installed from: binary
- TensorFlow version: 1.15.0

**Problem Description**
I have converted my model using float fallback quantization. The figure below is the input part of my float fallback model.

![image](https://user-images.githubusercontent.com/49788188/97520323-e7a4d580-19d5-11eb-8c2e-f9b790d69d55.png)

Firstly inference: I used tflite.interpreter.set_tensor to set my test_data to the input tensor "in_tensor", and stored the value of quantified input data (the output port of "quantize" in the figure). 

Secondly inference: I set the data stored above to the tensor which is the output of "quantize" in the figure( same as the tensor data stored). 

The result of the first reasoning is correct, and the result of the second reasoning is incorrect.

I think it might be tflite.interpreter.set_tensor can only set an input tensor but not an internal tensor. Hoping you giving me some guidance.

**Comment by amahendrakar** [comment]
@Harleytu,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and the dataset you are using. 

Also, TensorFlow 1.x is not actively supported, could you please update TensorFlow to v2.3 and check if you are facing the same issue. Thanks!

**Comment by Harleytu** [comment]
@amahendrakar, 
Thank you for your comment, but I'm sorry that I can't open my source code. 

And my layers in the CNN is built by tflearn. I still want to keep it in Tensorflow 1.x if possible.

**Comment by Harleytu** [comment]
Maybe `tflite.interpreter.set_tensor` can only set an input tensor.
