### ISSUE TITLE
predict function loads only the first batch from the input_fn

### ISSUE THREAD

**Issue by amirj** [tensorflow/tensorflow#4442]
I have a regular `input_fn_valid` function. 
When using `estimator.evaluate(input_fn=input_fn_valid)` everything is OK and the model is evaluated on the whole dataset. But calling `probs = estimator.predict(input_fn=input_fn_valid)` only returns the predicted values of the first batch (The size of `probs` is equal to `batch_size` parameter). 
I'm using TensorFlow 0.10 and test it on Ubuntu (GPU) and MAC OSX (CPU).
Is it a bug in the predict function?

**Comment by amirj** [comment]
setting `as_iterable=True`, solve the problem.

**Comment by dk67604** [comment]
@amirj Once I set to as_iterable=True, unable to iterate over prediction, could you suggest a way to do the same.
