### ISSUE TITLE
I have been trying to implement a custom tflite model on android studio. Example object detection works. But when I change the tflite file to my model, app gets installed. App closes as soon as it opens saying "app keeps stopping". Please help me. I am pretty new to this.

### ISSUE THREAD

**Issue by Bio-reactor** [tensorflow/tensorflow#44422]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@Bio-reactor 

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Please, let us know which TF version we are using?.

Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by lintian06** [comment]
Hi, please provide more information.

Most likely, you changed the model but didn't keep the consistent input and output.

**Comment by Bio-reactor** [comment]
Hi, 
I retrained the ssd_mobilenet for custom object recognition. I converted the frozen model into tflite file. I just replaced the tflite file in the assets folder and changed the labelmap.txt file. I checked with just the object detction model that is just using the detect.tflite and labelmap.txt. It works fine. When I change it to my model, the app keeps stopping

**Comment by Bio-reactor** [comment]
System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung a20
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:n/a
GPU model and memory:n/a

**Comment by ravikyram** [comment]
@Bio-reactor 

Just to verify did you follow the [tutorial](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android).Also, please see input and output are consistant in your model. Thanks!

**Comment by Bio-reactor** [comment]
@ravikyram yes I am following the same tutorial. I have placed my tflite file and labelmap under assests folder to get that working. I am attaching the same here. App is actually working now. But doesn't detect anything. It throws the following exception:

2020-11-05 20:35:21.492 30081-30081/org.tensorflow.lite.examples.detection E/tensorflow: CameraActivity: Exception!
    java.lang.IllegalStateException: This model does not contain associated files, and is not a Zip file.
        at org.tensorflow.lite.support.metadata.MetadataExtractor.assertZipFile(MetadataExtractor.java:325)
        at org.tensorflow.lite.support.metadata.MetadataExtractor.getAssociatedFile(MetadataExtractor.java:165)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:127)
        at org.tensorflow.lite.examples.detection.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:99)
        at org.tensorflow.lite.examples.detection.CameraActivity.onPreviewFrame(CameraActivity.java:200)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1221)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7860)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
Please save the detect1.txt as detect.tflite. Here the uploading of the .tflite is not supported. Please help me on this.


[labelmap.txt](https://github.com/tensorflow/tensorflow/files/5495188/labelmap.txt)
[detect1.txt](https://github.com/tensorflow/tensorflow/files/5495193/detect1.txt)

**Comment by Bio-reactor** [comment]
I got it fixed. My app is working. Thank you.

**Comment by ravikyram** [comment]
@Bio-reactor 

Please, close this thread if your issue was resolved.Thanks!

**Comment by ravikyram** [comment]
Closing the issue since it was resolved. Thanks!

**Comment by samaa** [comment]
please how  you solve it I am new too ans spent two weeks trying everything. pleaseeeee help

**Comment by samaa** [comment]
@Bio-reactor
please how you solve it I am new too ans spent two weeks trying everything. pleaseeeee help

**Comment by tunhnt2** [comment]
> I got it fixed. My app is working. Thank you.

How did you do?

**Comment by samaa** [comment]
it worked at the end it was a flag that I forget to make it true

**Comment by romnegrillo** [comment]
Hi. I'm doing the same thing for movenet. How did you resolve it? What flag?

**Comment by Anjitha5559** [comment]
Hey, I am working on a project, when I use a tflite model named ssd_v2_mobilenet.tflite it is working fine. Like both object detection and tracking is working fine. But when I replace the model with my custom trained model for detecting fire, it is not working. This is very important, how can I correct the issue. Please help
