### ISSUE TITLE
Questions about quantization aware trained tflite model

### ISSUE THREAD

**Issue by ivs-pychen** [tensorflow/tensorflow#44423]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source): 2.3

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
import tensorflow as tf

frozen_graph='./tflite_graph.pb'
input_arrays=["normalized_input_image_tensor"]
output_arrays=['TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3']
input_shapes={"normalized_input_image_tensor":[1,300,600,3]}
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(frozen_graph,input_arrays,output_arrays,input_shapes=input_shapes)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.allow_custom_ops=True

tflite_quant_model = converter.convert()

# Save the model.
with open('ssd_mobilenet_v2_traffic_quanaware_int8.tflite', 'wb') as f:
    f.write(tflite_quant_model)

```

**The output from the converter invocation**

[converted_model.zip](https://github.com/tensorflow/tensorflow/files/5456642/converted_model.zip)

**Also, please include a link to the saved model or GraphDef**

[model.zip](https://github.com/tensorflow/tensorflow/files/5456644/model.zip)

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

I trained a mobilenet v2 ssd using quantization aware training, and the pb file contains FakeQuantWithMinMaxVars nodes.

I have three questions:

1. The size of the tflite model I converted using Python API is bigger than the size of the pb file. Is this correct?
2. Is the quantized tflite model with int8 weights and uint8 activations?
3. If I use the TFLite converter(Python API), do the FakeQuantWithMinMaxVars nodes be replaced with the quantize and dequantize nodes?

**Comment by ymodak** [comment]
2. Currently your code performs dynamic range quantization which may leave some of the data in float format.
For enforcing `int8` quantization you want to try [integer-only_quantization ](https://www.tensorflow.org/lite/performance/post_training_integer_quant#convert_using_integer-only_quantization)
Note that this approach raises errors where the quantization fails and in such cases you can still move ahead with dynamic range quantization.
