### ISSUE TITLE
how to use tensorflow_docs after installed 

### ISSUE THREAD

**Issue by haiou90** [tensorflow/tensorflow#44420]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/MyMethod

### Clear description

For example, why should someone use this method? How is it useful?

### Correct links

Is the link to the source code correct?

### Parameters defined

Are all parameters defined and formatted correctly?

### Returns defined

Are return values defined?

### Raises listed and defined

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example?

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by bitbeast18** [comment]
Hi @haiou90, You didn't mention your use case. If it is just for building the API docs then you can follow the guide [here](https://www.tensorflow.org/community/contribute/docs#build_api_docs).

Also, it'd be great if you follow the [policies](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md) for raising issues.

**Comment by Saduf2019** [comment]
@haiou90 
Could you please clarify the information required, refer to [this link](https://stackoverflow.com/questions/55535518/modulenotfounderror-no-module-named-tensorflow-docs-when-creating-tensorflow) for the doc, and this for [build api doc](https://www.tensorflow.org/community/contribute/docs#build_api_docs).
