### ISSUE TITLE
In the codelab, "Build a handwritten digit classifier app with TensorFlow Lite" , At step number 4, the interpreter is not initialized with model, which is causing an NPE.

### ISSUE THREAD

**Issue by pradyum619** [tensorflow/tensorflow#44429]
https://codelabs.developers.google.com/codelabs/digit-classifier-tflite#3

Check the above link, In step number 4, The interpreter is not initialized using the model.
Which is why it is giving NPE on interpreter instance.

**Comment by ravikyram** [comment]
@pradyum619 

Please, fill issue template. Are you refering to this [tutorial](https://codelabs.developers.google.com/codelabs/digit-classifier-tflite#5) ?
Thanks!

**Comment by ymodak** [comment]
Also can you please help with the stacktrace? Thanks!

**Comment by pradyum619** [comment]
https://codelabs.developers.google.com/codelabs/digit-classifier-tflite#3

Check the above link, In step number 4, The interpreter is not initialized using the model.
Which is why it is giving NPE on interpreter instance.

**Comment by lintian06** [comment]
Thank you for reporting that!

The code block
```
private fun initializeInterpreter() {
    // TODO: Load the TF Lite model from file and initialize an interpreter.
    // ...
}
```
means that developers need to initialize Interpreter instance within this function.

**Comment by khanhlvg** [comment]
![image](https://user-images.githubusercontent.com/5379361/98897193-341c0500-24ee-11eb-8df2-12494a9c8e11.png)

You're right. There're 3 lines missing from the step 5. I'll update the codelab and republish it.
```
val assetManager = context.assets
val model = loadModelFile(assetManager, "mnist.tflite")

// These lines are missing from step 5
val options = Interpreter.Options()
options.setUseNNAPI(true)
val interpreter = Interpreter(model, options)
```

**Comment by khanhlvg** [comment]
The [codelab](https://developer.android.com/codelabs/digit-classifier-tflite#3) has been updated. Thanks for reporting the issue!

![image](https://user-images.githubusercontent.com/5379361/99206703-751e5d00-27ff-11eb-9071-48486e562f7a.png)
