### ISSUE TITLE
how to control the number of variables.data ?

### ISSUE THREAD

**Issue by kja815** [tensorflow/tensorflow#44421]
I use tensorflow 2.2.0 ,python 3.6.9

when I saved my model, how to control the number of files 'variables.data' ?

in my machine with titan Xp, saved my model has 2 variables.data files that variables.data-00000-of-00002, variables.data-00001-of-00002.

but in gcp machine with telsa T4, saved my model has 1 variables.data file that variables.data-00000-of-00001

it can be control by user?

**Comment by amahendrakar** [comment]
@kja815,
Please go through this [training checkpoints guide](https://www.tensorflow.org/guide/checkpoint#saving_from_tfkeras_training_apis) for more information regarding saving checkpoints and let us know if it helps. Thanks!

**Comment by kja815** [comment]
@amahendrakar 
guide is not helpful for me.
I just want to know how to control the number of files 'variables.data' like variables.data-00000-of-000001.
I want to control the number of files 'variables.data' to fixed number.
but when I use model.save(), tf make different number of files 'variables.data' for the same model with different machine.

**Comment by amahendrakar** [comment]
@kja815,
The `max_to_keep` argument of the `tf.train.CheckpointManager` function is used to control the number of checkpoints to be preserved. For more information please take a look at the documentation [here](https://www.tensorflow.org/api_docs/python/tf/train/CheckpointManager). 

Also check [this gist](https://colab.research.google.com/gist/amahendrakar/2e1ced95f05e058a9c021d671fee6321/44421.ipynb#scrollTo=_3Iud6GWESq2&line=1&uniqifier=1) which demonstrates the same. Thanks!
