### ISSUE TITLE
Why XLA need new kernels about op? 

### ISSUE THREAD

**Issue by YummyLee23** [tensorflow/tensorflow#44426]
In TensorFlow code about XLA, I see kernels about many OPs like `[compiler/tf2xla/kernels/concat_op](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2xla/kernels/concat_op.cc)`.  It seems like a repetition of `[core/kernels/concat_op](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/concat_op.cc)`.
Why Ops like `compiler/tf2xla/kernels/concat_op` are needed? And why not just replace it with `core/kernels/concat_op` to save code?

**Comment by YummyLee23** [comment]
hi

**Comment by sanjoy** [comment]
These kernels are very different.  The XLA kernel generates HLO that represents the TF operation while the non-XLA kernel implements the behavior for TF concat.
