### ISSUE TITLE
Cannot build TFLite flex:delegate package for armhf

### ISSUE THREAD

**Issue by trinitylundgren** [tensorflow/tensorflow#44437]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version: tensorflow-gpu 2.3.0
- Python version: 3.8
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): bazel 3.5.0
- GCC/Compiler version (if compiling from source):  gcc 9.3.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**

Cannot build TFLite flex:delegate package for armhf. 

Attempting to build TFLite flex:delegate for armhf results in the following error:

(base) trinity@trinity-blade:~/Documents/my-team/my-project/git/tensorflow$ bazel build -c opt --config=elinux_armhf --config=monolithic //tensorflow/lite/delegates/flex:delegate
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=211
INFO: Reading rc options for 'build' from /home/trinity/Documents/my-team/my-project/git/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/trinity/Documents/my-team/my-project/git/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from /home/trinity/Documents/my-team/my-project/git/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/trinity/miniconda3/bin/python3 --action_env PYTHON_LIB_PATH=/home/trinity/miniconda3/lib/python3.8/site-packages --python_path=/home/trinity/miniconda3/bin/python3 --config=xla
INFO: Found applicable config definition build:short_logs in file /home/trinity/Documents/my-team/my-project/git/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/trinity/Documents/my-team/my-project/git/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /home/trinity/Documents/my-team/my-project/git/tensorflow/.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:elinux_armhf in file /home/trinity/Documents/my-team/my-project/git/tensorflow/.bazelrc: --config=elinux --cpu=armhf
INFO: Found applicable config definition build:elinux in file /home/trinity/Documents/my-team/my-project/git/tensorflow/.bazelrc: --crosstool_top=@local_config_embedded_arm//:toolchain --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
INFO: Found applicable config definition build:monolithic in file /home/trinity/Documents/my-team/my-project/git/tensorflow/.bazelrc: --define framework_shared_object=false
INFO: Found applicable config definition build:linux in file /home/trinity/Documents/my-team/my-project/git/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr/arm-linux-gnueabihf --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/trinity/Documents/my-team/my-project/git/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Analyzed target //tensorflow/lite/delegates/flex:delegate (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/trinity/.cache/bazel/_bazel_trinity/ec49567c9bd407ca66e6e2b6d734da8f/external/icu/BUILD.bazel:33:1: C++ compilation of rule '@icu//:icuuc' failed (Exit 1)
In file included from external/icu/icu4c/source/common/usetiter.cpp:10:
external/icu/icu4c/source/common/unicode/uniset.h:504:29: error: invalid covariant return type for 'virtual icu_66::UnicodeFunctor* icu_66::UnicodeSet::clone() const'
     virtual UnicodeFunctor* clone() const;
                             ^~~~~
In file included from external/icu/icu4c/source/common/unicode/uniset.h:17,
                 from external/icu/icu4c/source/common/usetiter.cpp:10:
/usr/include/unicode/unifilt.h:80:28: note: overridden function is 'virtual icu_66::UnicodeFilter* icu_66::UnicodeFilter::clone() const'
     virtual UnicodeFilter* clone() const = 0;
                            ^~~~~
Target //tensorflow/lite/delegates/flex:delegate failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 12.828s, Critical Path: 12.51s
INFO: 31 processes: 31 local.
FAILED: Build did NOT complete successfully

**Provide the exact sequence of commands / steps that you executed before running into the problem**

From tensorflow repo root:

$ bazel build -c opt --config=elinux_armhf --config=monolithic //tensorflow/lite/delegates/flex:delegate

.bazelrc is attached. 
[bazelrc.txt](https://github.com/tensorflow/tensorflow/files/5459724/bazelrc.txt)

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by terryheo** [comment]
Please try it again on TF2.4 or higher. Please reopen this if you still have the issue.
