### ISSUE TITLE
Tensorflow: TFLiteConverter (Saved Model -> TFLite) in SSD_mobilenet_v2_2

### ISSUE THREAD

**Issue by ZuyongWu** [tensorflow/tensorflow#44438]
**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from (source or binary):  pip install
- TensorFlow version (or github SHA if from source): 2.3.1

I have installed tensorflow 2.3.1, my ssd_mobile_net_v2_2 was downloaded from https://tfhub.dev/tensorflow/ssd_mobilenet_v2/2. I want to convert this model to tf_lite version. My code is:
![image](https://user-images.githubusercontent.com/43801775/97602599-76513b00-1a46-11eb-84ea-680d8b6180fd.png)

But error occurs:

tensorflow.lite.python.convert.ConverterError: :0: error: loc("Func/StatefulPartitionedCall/input/_0"): requires all operands and results to have compatible element types :0: note: loc("Func/StatefulPartitionedCall/input/_0"): see current operation: %1 = "tf.Identity"(%arg0) {device = ""} : (tensor<1x320x320x3x!tf.quint8>) -> tensor<1x320x320x3xui8>
![image](https://user-images.githubusercontent.com/43801775/97602651-836e2a00-1a46-11eb-9764-cac65a8198ae.png)

it seems I need to set the input-data-type, but I don't know how to do that.

Thanks a lot for your replying.

**Comment by amahendrakar** [comment]
@ZuyongWu,
I was able to reproduce the error with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/e9142a6f50f070cae36d30274459984b/44438.ipynb).

However, looking [this comment](https://github.com/tensorflow/tensorflow/issues/42114#issuecomment-671593386) from a similar issue, I was able to convert the model with [TF-nightly](https://colab.research.google.com/gist/amahendrakar/aa52e271dabd6ce4e05fc6d49a18c34a/44438-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by ZuyongWu** [comment]
> @ZuyongWu,
> I was able to reproduce the error with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/e9142a6f50f070cae36d30274459984b/44438.ipynb).
> 
> However, looking [this comment](https://github.com/tensorflow/tensorflow/issues/42114#issuecomment-671593386) from a similar issue, I was able to convert the model with [TF-nightly](https://colab.research.google.com/gist/amahendrakar/aa52e271dabd6ce4e05fc6d49a18c34a/44438-tf-nightly.ipynb). Please find the attached gist. Thanks!

Hi, I have tried it in latest tf-nightly 2.5.0, however, the input_shape prints [1 1 1 3]
![image](https://user-images.githubusercontent.com/43801775/97690800-6eda7200-1ad8-11eb-97c9-0751a642aa9a.png)

**Comment by amahendrakar** [comment]
@ZuyongWu,
Please check [this](https://colab.research.google.com/gist/amahendrakar/aa52e271dabd6ce4e05fc6d49a18c34a/44438-tf-nightly.ipynb#scrollTo=WOJZqlLw1S8P&line=1&uniqifier=1) updated gist which lists the files after the conversion. Thanks!

**Comment by ricardoantonello** [comment]
Didn't work for me. Remains with [1 1 1 3] input size. :(

> @ZuyongWu,
> Please check [this](https://colab.research.google.com/gist/amahendrakar/aa52e271dabd6ce4e05fc6d49a18c34a/44438-tf-nightly.ipynb#scrollTo=WOJZqlLw1S8P&line=1&uniqifier=1) updated gist which lists the files after the conversion. Thanks!

**Comment by amahendrakar** [comment]
> Didn't work for me. Remains with [1 1 1 3] input size. :(

@ricardoantonello
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by ricardoantonello** [comment]
> > Didn't work for me. Remains with [1 1 1 3] input size. :(
> 
> @ricardoantonello
> Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

Hi,
I finally solve the issue using export_tflite_graph_tf2.py 
Thanks!

**Comment by alexdmiller** [comment]
@ricardoantonello we are seeing the same problem. Could you explain how you solved your problem? For example, what script are you using, how did you run it, and what version of TensorFlow are you using? That would be much appreciated!

**Comment by audere-yongshao** [comment]
@ricardoantonello Thanks! I've confirmed that using export_tflite_graph_tf2.py fixes the issue in TF 2.4.

**Comment by ricardoantonello** [comment]
> @ricardoantonello we are seeing the same problem. Could you explain how you solved your problem? For example, what script are you using, how did you run it, and what version of TensorFlow are you using? That would be much appreciated!

Hi, i used de checkpoints i have trainning before, and the instructions here:
python object_detection/export_tflite_graph_tf2.py \
    --pipeline_config_path path/to/ssd_model/pipeline.config \
    --trained_checkpoint_dir path/to/ssd_model/checkpoint \
    --output_directory path/to/exported_model_directory

pipeline_config_path is the same config file i used to trainning.
My version: TF 2.4 Gpu

Good luck!
