### ISSUE TITLE
[ssd mobileNet v2 model] ValueError: Failed to parse the model: pybind11::init(): factory function returned nullptr.

### ISSUE THREAD

**Issue by Aribido-Oluwaseun** [tensorflow/tensorflow#44435]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Catalina
- TensorFlow installed from (source or binary): Source
- TensorFlow version (or github SHA if from source): 2.3.1

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
python object_detection/export_tflite_graph_tf2.py \
    --pipeline_config_path ~/pretrained_models/ssd_mobilenet_v2_320x320_coco17_tpu-8/pipeline.config \
    --trained_checkpoint_dir~/pretrained_models/ssd_mobilenet_v2_320x320_coco17_tpu-8/checkpoint \
    --output_directory ~/output_dir
```

Traceback (most recent call last):
  File "/Users/jaribido/Library/Python/3.7/lib/python/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 52, in __init__
    _calibration_wrapper.CalibrationWrapper(model_content))
TypeError: pybind11::init(): factory function returned nullptr

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user_name/Desktop/Dev/models/convert_file.py", line 32, in <module>
    tflite_model = converter.convert()
  File "/Users/user_name/Library/Python/3.7/lib/python/site-packages/tensorflow/lite/python/lite.py", line 710, in convert
    output_tensors)
  File "/Users/user_name/Library/Python/3.7/lib/python/site-packages/tensorflow/lite/python/lite.py", line 638, in convert
    result = self._calibrate_quantize_model(result, **flags)
  File "/Users/user_name/Library/Python/3.7/lib/python/site-packages/tensorflow/lite/python/lite.py", line 440, in _calibrate_quantize_model
    calibrate_quantize = _calibrator.Calibrator(result)
  File "/Users/user_name/Library/Python/3.7/lib/python/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 54, in __init__
    raise ValueError("Failed to parse the model: %s." % e)
ValueError: Failed to parse the model: pybind11::init(): factory function returned nullptr.

```
# Copy and paste the output here.
```

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**
I downloaded ssd mobileNet v2 model from tensorflow zoo. Then I generated the TFLite inference graph savedModel. After which I downloaded coco dataset images and ran the code for TFlite conversion to Full integer quantization. Then I got the error documented above.

**Comment by ravikyram** [comment]
@Aribido-Oluwaseun 

I have tried in colab with TF nightly version(`2.5.0-dev20201029`) and i am not seeing any issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/35fb92d229e046cb28f82f207a547706/untitled101.ipynb?authuser=1). Please, verify once and close the issue. Thanks!

**Comment by Aribido-Oluwaseun** [comment]
@ ravikyram, thanks for your reply, using that method gives no issue. Have you tried the full integer quantization?

Please try the following rather:

saved_model_dir = '~/Dev/models/research/ssdmobilenet_dir/saved_model'
dir = '~/Desktop/Dev/dataset/test2017/'
tflite_dir = '~/Desktop/Dev/models/research/ssdmobilenet_dir/quantized_model/'

train_images = tf.keras.preprocessing.image_dataset_from_directory(
        directory=dir, labels='inferred', label_mode='int', class_names=None,
        color_mode='rgb', batch_size=1)

def representative_data_gen():
  for i in range(1000):
    image = train_images[i]
    image = tf.io.read_file(image)
    image = tf.io.decode_jpeg(image, channels=3)
    image = tf.image.resize(image, [320, 320])
    image = tf.cast(image / 255., tf.float64)
    image = tf.expand_dims(image, 0)
    yield [image]

converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
converter.representative_dataset = representative_data_gen
tflite_model = converter.convert()

with open(tflite_dir+'model.tflite', 'wb') as f:
  f.write(tflite_model)

Please try loading images for the full integer quantization and verify if it works. The dynamic quantization works for me as well and this bug is not related to that. Thanks..

**Comment by Rariusz** [comment]
@Aribido-Oluwaseun 
My problem was the same: https://github.com/tensorflow/tensorflow/issues/44091

**Comment by Aribido-Oluwaseun** [comment]
@Rariusz, thanks is it resolved for you?

**Comment by Rariusz** [comment]
@Aribido-Oluwaseun 
Yes, @amahendrakar help me to solve the problem however now I have still a problem with TFLite model. The model is reduced to 456 bytes !!!.  And so far I don't know why this is happening and how to solve it. I try different ways but the network is still so reduced.

**Comment by Aribido-Oluwaseun** [comment]
@Rariusz  Okay thanks, I will await on a comprehensive solution on this bug.

**Comment by Rariusz** [comment]
@Aribido-Oluwaseun You can install tensorflow 2.2. I know that install TensorFlow for object detection is very hard.
I use conda distribution of python with virtual env.

**Comment by srjoglekar246** [comment]
@Aribido-Oluwaseun You need to add TFLITE_BUILTINS to `supported_ops`:
```
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8, tf.lite.OpsSet.TFLITE_BUILTINS]
```

For the SSD model, the final op runs in float (with the rest of the graph in quantized). This, along with using the correct TF version should solve your issue (we started support for TF2 detection models in TFLite *after* TF2.3, so you might need to use the latest version/nightly for conversion).

**Comment by tilakrayal** [comment]
@Aribido-Oluwaseun ,
Can you please take a look at above [comment](https://github.com/tensorflow/tensorflow/issues/44435#issuecomment-736742158) and also please try to check in latest stable version v2.6 and let us know if the issue still persists.Thanks
