### ISSUE TITLE
tfl_quantizer

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#44440]
I want to use this [tfl_quantizer](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/compiler/mlir/lite/quantization/lite) application. How to build and use it?

**Comment by ymodak** [comment]
This issue is more suitable on [LLVM Discourse](https://llvm.discourse.group/c/mlir/31).
On a side note you may also try [tf.quantization.quantize](https://www.tensorflow.org/api_docs/python/tf/quantization/quantize)
Thanks!

**Comment by peter197321** [comment]
it's within TensorFlow repo - why other (llvm) to build and use?

**Comment by peter197321** [comment]
using [tf.quantization.quantize](https://www.tensorflow.org/api_docs/python/tf/quantization/quantize) how do I setup `disable_per_channel` bool option?

**Comment by mohantym** [comment]
Hi @peter197321 ! The command to run these C++ files is 

`g++ tfl_quantize.cc  libtensorflow-lite.a`

You can built  libtensorflow-lite.a using [Bazel](https://www.tensorflow.org/lite/android/lite_build#build_and_install). 
Please change the path of tflite model in tfl_quantizer.cc before using above command. Attaching relevant [thread](https://stackoverflow.com/questions/56837288/tensorflow-lite-c-api-example-for-inference) for reference. Thanks!
