### ISSUE TITLE
Possible memory leak in tf.keras.layers.experimental.preprocessing.TextVectorization

### ISSUE THREAD

**Issue by mmitsui** [tensorflow/tensorflow#44448]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.3.0-54-gfcc4b966f1 2.3.1
- Python version: Python 3.6.10 :: Anaconda, Inc.
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NVIDIA Driver 450.51.05
- GPU model and memory: Could not be determined (Deep Learning AMI (Ubuntu 18.04) Version 35.0 - ami-01aad86525617098d ; g3.8xlarge)

**Describe the current behavior**

A minimal TextVectorization builder works fine when run for the first time in a Jupyter notebook kernel. When the same minimal code is run in a parallel kernel, the below error is produced. The Jupyter notebook often needs to be restarted entirely (not just a kernel shutdown) in order for TextVectorization to work again.

**Describe the expected behavior**

Expected to work properly across multiple notebook instances without need for kernel shutdown or Jupyter notebook restart. I have tried `tf.keras.backend.clear_session()` and `gc.collect()` before and after calls to `TextVectorization` but this has not worked.

**Standalone code to reproduce the issue**

```
num_words = 100000
tag_processor = tf.keras.layers.experimental.preprocessing.TextVectorization(output_mode='int',
                                                                              max_tokens=num_words,
                                                                              name='tag_processor',
                                                                              standardize=None)
tag_processor.adapt(data['keywords_processed'].tolist())
vectorized_text = tag_processor(data['keywords_processed'].tolist()[:100])
print(vectorized_text)


# Example of data['keywords_processed'].tolist(): ['12 remove in disable\\how iphoneipad 14 disabled fix apple disable ios 2020 to how icloud iphone se',
# 'uruguayo san gana se york estados cuesta new en vs 2020 cuanto ca español nueva woker neuva california francisco unidos vivir',
# 'quero homem masculina namorado relacionamentos vono luiza comoconquistarumhomem que coach mente os serio pensam de pense gostam como do querem oqueoshomensquerem eles homens um meta buscam crush relacionamento coaching amor conquistar o',
# 'is hoa back tàu twin and runs sun hỏa double through tunnel rail beautiful goes meeting watch 2020 red disappeared black tau beautifully cross station train of the appeared rushed trains to monsters nice',
# 'សមីការរង្វង់ exercise for សិក្សាអនុគមន៏ ដេរីវេ\u200b and លំហាត់សិស្សពូកែគណិតវិទា លំហាត់ប្រតិបត្តិ អាំងតេក្រាល intergral grade វិញ្ញាសាបាក់ឌុប លីមីត\u200b\u200b\u200b\u200b studying បម្លែងឡាប្លាស វិញ្ញាសាសិស្សពូកែទូទាំងប្រទេស calculate math limite learning imo ចំនួនអសនិទាន answers brain ស្ថិតិ integral mathematics seamo algebra study of how tips ត្រីកោណមាត្រ សិស្សពូកែគណិតវិទ្យា សមីការឌីផេរ៉ង់ស្យែល 9 to',
# '2 depressão jesus da dia oração hoje liberta tarde madrugada 91 de edifica nosso barros cura deus salmo palavra do pai dulcineia noite libertação reis que',
# ...
# ]
#
# len(data.index) == 3907552

# Rest of code cannot be shared, but above example provides size of data frame and format of input to TextVectorization
```

**Other info / logs** 

jupyter core     : 4.6.1
jupyter-notebook : 6.0.3
qtconsole        : 4.6.0
ipython          : 7.12.0
ipykernel        : 5.1.4
jupyter client   : 5.3.4
jupyter lab      : 1.2.6
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.4
traitlets        : 4.3.3

---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
<ipython-input-21-cfaee3ea4157> in <module>
      5                                                                               name='tag_processor',
      6                                                                               standardize=None)
----> 7 tag_processor.adapt(data['keywords_processed'].tolist())
      8 vectorized_text = tag_processor(data['keywords_processed'].tolist()[:100])
      9 print(vectorized_text)

~/anaconda3/envs/tensorflow2_latest_p37/gpu/lib/python3.7/site-packages/tensorflow/python/keras/layers/preprocessing/text_vectorization.py in adapt(self, data, reset_state)
    373         data = array_ops.expand_dims(data, axis=-1)
    374       self.build(data.shape)
--> 375       preprocessed_inputs = self._preprocess(data)
    376     elif isinstance(data, dataset_ops.DatasetV2):
    377       # TODO(momernick): Replace this with a more V2-friendly API.

~/anaconda3/envs/tensorflow2_latest_p37/gpu/lib/python3.7/site-packages/tensorflow/python/keras/layers/preprocessing/text_vectorization.py in _preprocess(self, inputs)
    546         # This treats multiple whitespaces as one whitespace, and strips leading
    547         # and trailing whitespace.
--> 548         inputs = ragged_string_ops.string_split_v2(inputs)
    549       elif callable(self._split):
    550         inputs = self._split(inputs)

~/anaconda3/envs/tensorflow2_latest_p37/gpu/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a

~/anaconda3/envs/tensorflow2_latest_p37/gpu/lib/python3.7/site-packages/tensorflow/python/ops/ragged/ragged_string_ops.py in string_split_v2(input, sep, maxsplit, name)
    522       return ragged_tensor.RaggedTensor.from_value_rowids(
    523           values=sparse_result.values,
--> 524           value_rowids=sparse_result.indices[:, 0],
    525           nrows=sparse_result.dense_shape[0],
    526           validate=False)

~/anaconda3/envs/tensorflow2_latest_p37/gpu/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a

~/anaconda3/envs/tensorflow2_latest_p37/gpu/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py in _slice_helper(tensor, slice_spec, var)
   1022         ellipsis_mask=ellipsis_mask,
   1023         var=var,
-> 1024         name=name)
   1025 
   1026 

~/anaconda3/envs/tensorflow2_latest_p37/gpu/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a

~/anaconda3/envs/tensorflow2_latest_p37/gpu/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py in strided_slice(input_, begin, end, strides, begin_mask, end_mask, ellipsis_mask, new_axis_mask, shrink_axis_mask, var, name)
   1194       ellipsis_mask=ellipsis_mask,
   1195       new_axis_mask=new_axis_mask,
-> 1196       shrink_axis_mask=shrink_axis_mask)
   1197 
   1198   parent_name = name

~/anaconda3/envs/tensorflow2_latest_p37/gpu/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py in strided_slice(input, begin, end, strides, begin_mask, end_mask, ellipsis_mask, new_axis_mask, shrink_axis_mask, name)
  10318       return _result
  10319     except _core._NotOkStatusException as e:
> 10320       _ops.raise_from_not_ok_status(e, name)
  10321     except _core._FallbackException:
  10322       pass

~/anaconda3/envs/tensorflow2_latest_p37/gpu/lib/python3.7/site-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6841   message = e.message + (" name: " + name if name is not None else "")
   6842   # pylint: disable=protected-access
-> 6843   six.raise_from(core._status_to_exception(e.code, message), None)
   6844   # pylint: enable=protected-access
   6845 

~/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/six.py in raise_from(value, from_value)

InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run StridedSlice: Dst tensor is not initialized. [Op:StridedSlice] name: strided_slice/

**Comment by xanthan011** [comment]
Did u get that error resolved?

**Comment by sanilGh** [comment]
Facing the same issue.

**Comment by xanthan011** [comment]
Heyy @sanilGh , I don't know if this will fix your error but I tried on this nvidia jetson nano and it worked...
At the top of the script write this before importing tensorflow..
```
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '1'
```

**Comment by sanilGh** [comment]
@xanthan011 Nope that does not fix it.

**Comment by xanthan011** [comment]
then there is a possibility that you laptop is going out of memory, while running this program..

**Comment by jvishnuvardhan** [comment]
@mmitsui Can you please try new TF version like `tf-nighly` and let us know how it progresses. Also, Can you please share a simple standalone code to reproduce the issue? Thanks!

**Comment by SysuJayce** [comment]
Going through the same issue.
According to the tensorflow profile, I found that Standardize and Split Op both execute on CPU not GPU.

I just wonder how can we put the above ops to GPU? Maybe that's the cause of memory leak?

**Comment by raisularefin** [comment]
I am also having a similar issue. I was trying to adapt to 17M sentences and it was asking 835GB memory!

**Comment by jvishnuvardhan** [comment]
@raisularefin Please open a new issue with a simple standalone code to reproduce the issue. Thanks!
