### ISSUE TITLE
Printing on TPUs

### ISSUE THREAD

**Issue by idavidrein** [tensorflow/tensorflow#44449]
**System information**
- TensorFlow version (you are using): 2.3
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
I would like to be able to print on TPUs. Currently printing on TPUs in functions decorated with tf.function does not work (tf.print doesn't work). 

**Will this change the current api? How?**
I don't think the external api would need to be affected, as tf.print should work. 

**Who will benefit with this feature?**
Anyone who wants to debug their code running on TPUs easily!

**Any Other info.**
This issue https://github.com/tensorflow/tensorflow/issues/43705 raised the same concern, but the solution provided doesn't work. I've provided a minimal example here: 
https://colab.research.google.com/drive/1kFdR9tpj7zJjwHIbWRVjVSiA9zwviErK?usp=sharing

I wasn't sure where the config statement should be, so I tried placing it the three obvious scopes (the tf.function, normal python, and the TPU strategy) to no avail.

**Comment by amorisot** [comment]
I'd like to say that I am also encountering this issue, and would appreciate clarification!

**Comment by hongjunChoi** [comment]
Hello David, 

Thank for requesting this feature. tf.print unfortunately is unsupported on TPU's currently as TPU runs on separate cloud cluster than the python program. 

We'll be sure to update/highlight this if this feature is added to TPU's, however. :)
