### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by philp123** [tensorflow/tensorflow#44453]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.12.3
- Python version:3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
- CUDA/cuDNN version:cuda 9.0.176/cudnn 7
- GPU model and memory:Tesla K80/11GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
When I was training resnet50 model with some epochs,especially when the classification is reaching below 0.09, the following error appears. 
![1](https://user-images.githubusercontent.com/49138243/97657415-be9f4600-1aa4-11eb-8cfb-579b1a27427d.PNG)
![2](https://user-images.githubusercontent.com/49138243/97657426-c65eea80-1aa4-11eb-8814-a38052035dcb.PNG)

**Describe the expected behavior**
What's the error reason and how to solve this problem?

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@philp123 
As youhave mentioned you are using tf version 1.12 and 1.x is not supported, please upgrade to 2.x and let us know if you face any issues.

**Comment by philp123** [comment]
> @philp123
> As youhave mentioned you are using tf version 1.12 and 1.x is not supported, please upgrade to 2.x and let us know if you face any issues.

The resource for tf is on HPC, I have no right to update to 2.x.

**Comment by Saduf2019** [comment]
@philp123 
Please provide with simple stand alone code or if possible share a colab gist with error reported.
