### ISSUE TITLE
Error while running TF Lite Model Maker Text Classification Tutorial

### ISSUE THREAD

**Issue by rakeshmothukuru1** [tensorflow/tensorflow#44454]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/lite/tutorials/model_maker_text_classification#end-to-end_workflow

## Description of issue (what needs changing): 
The below code is resulting in error

```python
model = text_classifier.create(train_data, model_spec=spec)
```

Error Trace is shown below:

```python
INFO:tensorflow:Retraining the models...
INFO:tensorflow:Retraining the models...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-89009ac171ed> in <module>()
----> 1 model = text_classifier.create(train_data, model_spec=spec)

1 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_examples/lite/model_maker/core/task/text_classifier.py in train(self, train_data, validation_data, epochs, batch_size)
    132     """Feeds the training data for training."""
    133     if batch_size is None:
--> 134       batch_size = self.model_spec.default_batch_size
    135 
    136     if train_data.size < batch_size:

AttributeError: 'BertClassifierModelSpec' object has no attribute 'default_batch_size'
```

### Clear description:

This tutorial is useful to customize the `TF Lite Text Classification` project with our Dataset.

### Correct links

Is the link to the source code correct?  : NA

### Parameters defined

Are all parameters defined and formatted correctly? : NA

### Returns defined

Are return values defined? : NA

### Raises listed and defined : NA

Are the errors defined? For example,
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file#raises

### Usage example

Is there a usage example? : NA

See the API guide: https://www.tensorflow.org/community/contribute/docs_ref
on how to write testable usage examples.

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content? : NA

### Submit a pull request? : No

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/1ad549b981d453f0fb0f7a75b065390e/44454.ipynb). Thanks!

**Comment by lintian06** [comment]
@ziyeqinghan

**Comment by ziyeqinghan** [comment]
We have fixed it. Please try again.
