### ISSUE TITLE
cannot fin symbol method setUseNNAPI(boolean)

### ISSUE THREAD

**Issue by GustavoMSevero** [tensorflow/tensorflow#44461]
Hi!
I'm trying to run a model i have created on tensorflow lite for android and i got this  error
![Captura de Tela 2020-10-30 às 10 59 16](https://user-images.githubusercontent.com/2678092/97714896-7ed65f80-1aa0-11eb-91ce-3ade0e9d5c4b.png)

How can i solve this?

**Comment by ataftaf** [comment]
Hi, 
I encountered the same problem while trying to run my model.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
