### ISSUE TITLE
[RNN] TfLite conversion issue in LSTM models

### ISSUE THREAD

**Issue by pranathibl** [tensorflow/tensorflow#44460]
I have not found any pretrained lstm models to work with . 
Did tfLite provided any pretrained lstm models ? 
I tried to create tflite model but facing issues while conversion .
Could you provide exact script to create tfLite model ? 
Does tfLite has any script for creating tfLite LSTM models with latest version ?
This is my script to create tfLite model. But it has few issues 

```
import numpy as np
import tensorflow as tf



model = tf.keras.Sequential()
# Add an Embedding layer expecting input vocab of size 1000, and
# output embedding dimension of size 64.
model.add(tf.keras.layers.Embedding(input_dim=1000, output_dim=64))

# Add a LSTM layer with 128 internal units.
model.add(tf.keras.layers.LSTM(128))

# Add a Dense layer with 10 units.
model.add(tf.keras.layers.Dense(10))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['categorical_accuracy'])
model.summary()
#model.fit_generator(train_data_generator.generate(), len(train_data)//(batch_size*num_steps), num_epochs,
#                        validation_data=valid_data_generator.generate(),
#                        validation_steps=len(valid_data)//(batch_size*num_steps), callbacks=[checkpointer])
tf.saved_model.save(model, "saved_model_keras_dir")

model.save('my_lstm_model')
# x_train = 
#(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
#x_train, x_test = x_train / 255.0, x_test / 255.0

# Cast x_train & x_test to float32.
#x_train = x_train.astype(np.float32)
#x_test = x_test.astype(np.float32)

#model.fit(x_train, y_train, epochs=5)
#model.evaluate(x_test, y_test)

converter = tf.lite.TFLiteConverter.from_keras_model(model)

#tflite_model = converter.convert()

# Step 3: Convert the Keras model to TensorFlow Lite model.
sess = tf.compat.v1.keras.backend.get_session()
input_tensor = sess.graph.get_tensor_by_name('embedding_1:0')
output_tensor = sess.graph.get_tensor_by_name('dense_1:0')
converter = tf.lite.TFLiteConverter.from_session(
    sess, [input_tensor], [output_tensor])

tflite = converter.convert()
print('Model converted successfully!')


# Save the model.
with open('lstmmodel.tflite', 'wb') as f:
  f.write(tflite_model) 



```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/f89a67cbef070e7ee00280229af561ce/44460.ipynb#scrollTo=Q3Sv5ONa4z8y). Thanks!

**Comment by jvishnuvardhan** [comment]
@pranathibl Can you please check [this example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/keras_lstm.ipynb) and update your code to use with `tf-nightly`. Another very similar example is [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/Keras_LSTM_fusion_Codelab.ipynb). Thanks!

If you face any bug/performance related issue, please post them here. If there is any general support question, post it in Stackoverflow where there is a large community is there to help. Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing this issue as this was resolved. Please feel free to open a new issue if you face any bug/performance related issue. Thanks!

**Comment by pranathibl** [comment]
How to pass the seq length. Is there any option to pass variable seq length. If seq length has to be passed, what is the workflow ?
