### ISSUE TITLE
Can not enable XNNPack android as there is no setUseXNNPACK option. 

### ISSUE THREAD

**Issue by kafan1986** [tensorflow/tensorflow#44468]
System information

OS Platform and Distribution: Android v9.0
Mobile device: armv7 and v8

TensorFlow version: 2.3.0 or nightly

Installed using virtualenv?
    def tfl_version = "0.0.0-nightly";
    implementation ("org.tensorflow:tensorflow-lite:${tfl_version}") { changing = true }
    implementation ("org.tensorflow:tensorflow-lite-gpu:${tfl_version}") { changing = true }

Describe the problem

I am using tflite on android using below repos. I have tried both version 2.3.0 as well as nightly builds. According to https://blog.tensorflow.org/2020/07/accelerating-tensorflow-lite-xnnpack-integration.html I can enable XNNPack by setUseXNNPACK. But it can not find the symbol/option.

**Comment by amahendrakar** [comment]
@kafan1986,
Could you please provide the code / exact sequence of commands that you executed before running into the problem?

Also, please take a look at similar issue [#42056](https://github.com/tensorflow/tensorflow/issues/42056) and let us know if it helps. Thanks!

**Comment by kafan1986** [comment]
@amahendrakar I am not sure what else can I share. The example code is pretty standard one. I am attaching a image inside android studio and it shows no member function with setUseXNNPACK name.
![Screen Shot 2020-11-02 at 3 14 18 PM](https://user-images.githubusercontent.com/7953422/97853550-3fb54200-1d1e-11eb-91e1-92f5f5ad820a.png)

**Comment by kafan1986** [comment]
Android studio cached old version somehow. It is OK now. Closing issue.
