### ISSUE TITLE
tensorflow.contrib.image import transform as H_transform

### ISSUE THREAD

**Issue by gpsherry** [tensorflow/tensorflow#44476]
where is tensorflow.contrib.image import transform in tensorflow2.0?

**Comment by ravikyram** [comment]
@gpsherry 

tf.contrib.image.transform and tf.contrib.image.compose_transform are now part of the [tensorflow_addons.image](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/README.md) module.
Please, refer #33335, [SO link](https://stackoverflow.com/questions/58288465/the-equivalent-of-tf-contrib-image-transform-in-tensorflow-2-0) and see if it helps you. Thanks!
