### ISSUE TITLE
I can't use tensorflow very well by using RTX 3090,When will you updata your new version to support the new RTX3090?

### ISSUE THREAD

**Issue by lightlefter** [tensorflow/tensorflow#44478]
I can't use tensorflow very well by using RTX 3090,When will you updata your version to support the new RTX3090?
![666](https://user-images.githubusercontent.com/73739019/97775960-a5f26700-1b5c-11eb-8cdd-f54eae8ee9d4.png)

**Comment by SmileTM** [comment]
I have the same problem.

**Comment by Saduf2019** [comment]
@lightlefter 
please refer tot he issues in [this comment](https://github.com/tensorflow/tensorflow/issues/44490#issuecomment-720277302) regarding "RTX 3090" and let us know.

**Comment by lightlefter** [comment]
> 我也有同样的问题。



> I have the same problem.

I had deal with this problem,you need use tf2 command to restrain video memory

**Comment by Saduf2019** [comment]
@lightlefter 
Please move the issue to closed status if resolved.

**Comment by lightlefter** [comment]
> @lightlefter
> Please move the issue to closed status if resolved.

OK

**Comment by Hs-He** [comment]
fine
