### ISSUE TITLE
How can I clear GPU memory in tensorflow 2.2?

### ISSUE THREAD

**Issue by GF-Huang** [tensorflow/tensorflow#44473]

**Comment by amahendrakar** [comment]
@GF-Huang,
By default, TensorFlow maps nearly all of the GPU memory of all GPUs (subject to CUDA_VISIBLE_DEVICES) visible to the process. For more information, please take a look at this [guide](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth). 

To clear GPU memory, you'll have to restart the Python interpreter. Please check similar issue [#17048](https://github.com/tensorflow/tensorflow/issues/17048) for reference. Thanks!
