### ISSUE TITLE
TFlite Custom trained model Issue (IndexError: invalid index to scalar variable)

### ISSUE THREAD

**Issue by ReyCoPeruvit** [tensorflow/tensorflow#44481]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 and Raspbian
- TensorFlow installed from (source or binary): TF
- TensorFlow version (or github SHA if from source): 2.3.1

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
python /content/models/research/object_detection/exporter_main_v2.py \
    --trained_checkpoint_dir training \
    --output_directory inference_graph \
    --pipeline_config_path training/ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8.config
```

**The output from the converter invocation**

```
Output succeeded. (not sure what to put here)
```

**Also, please include a link to the saved model or GraphDef**

```
Model: https://drive.google.com/drive/folders/17iEVFzQjqhI6zP4zUJP0uTAnBy2TnWPR?usp=sharing
TFLiteModel :https://drive.google.com/drive/folders/1BCcWG-89OHts-510sev1VJepbDQkt9s0?usp=sharing
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:

I trained a SSD_MobilenetV2_FPN_680x680 to detect only black bears successfully and converted to tflite by following this guide: https://github.com/TannerGilbert/Tensorflow-Object-Detection-API-Train-Model.

I then followed EdjeElectronics' guide on how to run tflite on Raspberry Pi: https://github.com/EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi/blob/master/Raspberry_Pi_Guide.md.

But, when I try to run TFLite_detection_webcam.py It gives an error:

pi@raspberrypi:~ $ source tflite1-env/bin/activate
bash: tflite1-env/bin/activate: No such file or directory
pi@raspberrypi:~ $ cd tflite1
pi@raspberrypi:~/tflite1 $ source tflite1-env/bin/activate
(tflite1-env) pi@raspberrypi:~/tflite1 $ python3 TFLite_detection_webcam.py --modeldir=Bear_Detector_TFLite_model
Traceback (most recent call last):
  File "TFLite_detection_webcam.py", line 185, in <module>
    boxes = interpreter.get_tensor(output_details[0]['index'])[0] # Bounding box coordinates of detected objects
IndexError: invalid index to scalar variable.

I run his sample tflite model and it works.
I'm guessing my the SSD_MobilenetV2_fpn model isnt compatible for Raspberry PI?

Im sorry if this post is not in the correct place or if I'm missing key info for help. I'm pretty new to all this stuff.

**Any other info / logs**

**TFLite_detection_webcam.py**
https://github.com/EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi/blob/master/TFLite_detection_webcam.py

**Comment by srjoglekar246** [comment]
TF2 Detection models cannot be converted to TFLite directly. There is an intermediate step to generate a TFLite-friendly model, see [these instructions](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md). To see a Python example of inference with such a model, see [this Colab](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb).

**Comment by ReyCoPeruvit** [comment]
> TF2 Detection models cannot be converted to TFLite directly. There is an intermediate step to generate a TFLite-friendly model, see [these instructions](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md). To see a Python example of inference with such a model, see [this Colab](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb).

Yes, I used the recommended method. Im thinking maybe the problem is in how I exported the inference graph? Was this to be done while training? I stopped the training used checkpoint-0.

**Comment by srjoglekar246** [comment]
That should still work. Can you post the exact commands you used?

**Comment by sscast** [comment]
> > TF2 Detection models cannot be converted to TFLite directly. There is an intermediate step to generate a TFLite-friendly model, see [these instructions](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md). To see a Python example of inference with such a model, see [this Colab](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb).
> 
> Yes, I used the recommended method. Im thinking maybe the problem is in how I exported the inference graph? Was this to be done while training? I stopped the training used checkpoint-0.

I have the same error and I also followed the same colab. 
I have also tried on Python3.9 and Python3.8. The same error persists.  

I look at boxes, classes, and scores used for plot_detection(), and they have very different shapes: 
boxes [[0.68488944 0.06575927 0.0612663  0.03251293 0.0133186  0.01068375
  0.01012135 0.01006672 0.00997183 0.00978112]]
classes [[[ 5.3712845e-01  3.4228128e-01  8.4705698e-01  4.7190589e-01]
  [-7.0969015e-04  9.1059554e-01  1.6321224e-01  9.9637425e-01]
  [ 1.7573684e-04  7.2726512e-01  1.7673787e-01  8.2486808e-01]
  [ 7.1139622e-01  3.9257938e-01  8.1933236e-01  4.5051664e-01]
  [-1.8495396e-03  1.0394566e-01  1.5567529e-01  4.1947818e-01]
  [ 5.5734855e-01  3.3228156e-01  7.8419203e-01  4.5065954e-01]
  [ 2.4230778e-02  3.4894028e-01  8.3006464e-02  4.3349090e-01]
  [ 5.5638200e-01  3.4166583e-01  7.1462268e-01  5.3918886e-01]
  [ 9.8083839e-03  3.1147084e-01  9.2084132e-02  4.3107238e-01]
  [ 5.0306618e-03  4.6566434e-02  9.8932646e-02  1.9595167e-01]]]
scores [10.]

So I tried to modify the data type, but come to a point that "ValueError: too many values to unpack (expected 4)" - for boxes, where having 8 values in the array.

Any help?

**Comment by cRhettiarachchi** [comment]
Any update on this issue? I have the same issue after converting into tflite.

**_The command I used to convert the model to tflite friendly inference graph is,_**
`!python object_detection/export_tflite_graph_tf2.py \
    --pipeline_config_path object_detection/inference_graph/pipeline.config \
    --trained_checkpoint_dir object_detection/inference_graph/checkpoint \
    --output_directory tflite`

**_Then I used the tflite_convert,_**
`!tflite_convert --saved_model_dir=/output/tflite/saved_model --output_file=/output/indoor-model.tflite`

**_When converting to tflite the output logs are as follows,_** 

2021-09-17 05:06:53.045188: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-17 05:06:53.057318: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2021-09-17 05:06:53.058332: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1835] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-09-17 05:06:53.644501: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-09-17 05:07:08.670831: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:351] Ignored output_format.
2021-09-17 05:07:08.670892: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:354] Ignored drop_control_dependency.
2021-09-17 05:07:08.670914: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:360] Ignored change_concat_input_ranges.
2021-09-17 05:07:08.672066: I tensorflow/cc/saved_model/reader.cc:38] Reading SavedModel from: /output/tflite/saved_model
2021-09-17 05:07:08.773055: I tensorflow/cc/saved_model/reader.cc:90] Reading meta graph with tags { serve }
2021-09-17 05:07:08.773203: I tensorflow/cc/saved_model/reader.cc:132] Reading SavedModel debug info (if present) from: /output/tflite/saved_model
2021-09-17 05:07:09.104013: I tensorflow/cc/saved_model/loader.cc:211] Restoring SavedModel bundle.
2021-09-17 05:07:09.720913: I tensorflow/cc/saved_model/loader.cc:195] Running initialization op on SavedModel bundle at path: /output/tflite/saved_model
2021-09-17 05:07:09.998334: I tensorflow/cc/saved_model/loader.cc:283] SavedModel load for tags { serve }; Status: success: OK. Took 1326264 microseconds.
2021-09-17 05:07:10.801085: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:210] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2021-09-17 05:07:11.557933: I tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1899] Estimated count of arithmetic ops: 1.321 G  ops, equivalently 0.661 G  MACs

**_When inferencing on the .tflite model the error I get is as follows._**
/usr/local/lib/python3.7/dist-packages/object_detection/utils/visualization_utils.py in visualize_boxes_and_labels_on_image_array(image, boxes, classes, scores, category_index, instance_masks, instance_boundaries, keypoints, keypoint_scores, keypoint_edges, track_ids, use_normalized_coordinates, max_boxes_to_draw, min_score_thresh, agnostic_mode, line_thickness, mask_alpha, groundtruth_box_visualization_color, skip_boxes, skip_scores, skip_labels, skip_track_ids)

IndexError: invalid index to a scalar variable.

I trained several models about 4 months ago and converted them to tflite, and they worked without any issue. If there is any help regarding this issue I would much appreciate it. Thanks a lot!

**Comment by srjoglekar246** [comment]
With some recent converter changes, it looks like the order of outputs from the detection TFLite models has changed. Can you print `interpreter.get_output_details()` in your inference code & see what you get?

**Comment by Faiz-hmed** [comment]
> With some recent converter changes, it looks like the order of outputs from the detection TFLite models has changed. Can you print `interpreter.get_output_details()` in your inference code & see what you get?

**Upon**  `interpreter.get_output_details()`:

[{'name': 'StatefulPartitionedCall:1', 'index': 335, 'shape': array([ 1, 10], dtype=int32), 'shape_signature': array([ 1, 10], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, 

{'name': 'StatefulPartitionedCall:3', 'index': 333, 'shape': array([ 1, 10,  4], dtype=int32), 'shape_signature': array([ 1, 10,  4], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, 
 
{'name': 'StatefulPartitionedCall:0', 'index': 336, 'shape': array([1], dtype=int32), 'shape_signature': array([1], dtype=int32),    'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, 

{'name': 'StatefulPartitionedCall:2', 'index': 334, 'shape': array([ 1, 10], dtype=int32), 'shape_signature': array([ 1, 10], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]



### Inspecting model outputs:
code taken from [here](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb)
```
boxes = interpreter.get_tensor(output_details[0]['index'])
classes = interpreter.get_tensor(output_details[1]['index'])
scores = interpreter.get_tensor(output_details[2]['index'])
```

**Upon printing these after** `interpreter.invoke()`, in the same order:     

  [[0.23682949 0.07426468 0.06343907 0.03482482 0.03126174 0.0246169
    0.022504   0.01281145 0.01089162 0.01080516]]              **//Boxes**

  [[[ 5.42102814e-01  3.35466176e-01  8.34305406e-01  4.55916852e-01]
    [-7.09682703e-04  9.10595536e-01  1.63212255e-01  9.96374249e-01]
    [ 2.39851326e-03  7.29886234e-01  1.88307345e-01  8.24188054e-01]
    [ 8.10296059e-01  4.75230813e-03  9.96720552e-01  1.48132056e-01]
    [ 2.04751641e-03 -5.52492589e-03  1.29257411e-01  1.77513599e-01]
    [ 7.14018226e-01  1.12694576e-02  9.92248535e-01  1.80131346e-01]
    [ 8.67153883e-01  5.06623805e-01  9.98734474e-01  6.41331732e-01]
    [ 8.61540318e-01  4.15937781e-01  1.00139987e+00  5.49726427e-01]
    [-1.41584054e-02 -1.72429532e-02  1.37187302e-01  3.87391388e-01]
    [-4.36818972e-02 -8.47322345e-02  1.20016895e-01  2.35268712e-01]]]        **//Classes**

  [10.]     **//Scores**

### After changing the order:
But even after taking the correct outputs for boxes,classes and scores i.e. 
output_details[1]['index']        
output_details[0]['index']
output_details[3]['index']

The tflite model doesn't give the same inference as the regular tf mobilenet model.

**Comment by Faiz-hmed** [comment]
https://colab.research.google.com/drive/1lUOEUpbsAbjgz_P8hbv8bcolM-2VtUx7?usp=sharing

This notebook contains the code taken from [here](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb), and contains everything from Data preparation & visualization to inference using the base tf model, conversion to tflite and the failed inference from the tflite model; even after the above index changes to the output_details list.

As of Nov 19 '21, Everything works in the notebook till the last tflite inference section (which has no matching predictions with the base model). 
But before running through the cells in the notebook download cudnn 8.1 and upload it to my drive of your google drive (The notebook handles its installation from there), to avoid the dreaded 'failed to fetch convolutional algorithm ' error near the model building part(checkpoint creation).  See https://github.com/tensorflow/models/issues/10360#issuecomment-965560460

Also do run the upgrade pip code cell, to avoid tensorflow/models#10375 

If there's any help regarding this from the maintainers or anyone, i would greatly appreciate it. Thanks.

**Comment by srjoglekar246** [comment]
@Faiz-hmed When you say that the TFLite model doesn't provide the 'same' inference, are the detections completely off, or just not exactly equal to TF's outputs?

**Comment by Faiz-hmed** [comment]
They are completely off, absent in the case of the TFLite model on default test images provided in the 'models/research/object_detection/test_images/ducky/test/'  directory. The detections seen from the TF's model aren't seen at all in the TFLite model. 
While Running through the notebook, there was not a single detection on those images making up the gif.

**Comment by Faiz-hmed** [comment]
**FIX:** Rather than taking the classes at the 0th index of the output list, taking the 3rd one seemed to fix the issue.
```
boxes = interpreter.get_tensor(output_details[1]['index'])
classes = interpreter.get_tensor(output_details[3]['index'])
scores = interpreter.get_tensor(output_details[0]['index'])
```
At first, printing all the outputs after `interpreter.invoke()` seemed to give a zero array at the 3rd index of the list.
Then I did remember that we had a label_id_offset that was causing the values to go to zero.

**Comment by Faiz-hmed** [comment]
Thank you so much for those nudges in the right direction, @srjoglekar246

**Comment by Faiz-hmed** [comment]
Thank you so much for the nudges in the right direction, @srjoglekar246

**Comment by srjoglekar246** [comment]
Np! Glad you got things to work

**Comment by mohantym** [comment]
Hi @ReyCoPeruvit ! We are checking to see whether you still need help in this issue or not.  Have you checked the above [comment ](https://github.com/tensorflow/tensorflow/issues/44481#issuecomment-974325834)yet ? Thanks!

**Comment by marksking** [comment]
I am currently working on a project involving TensorFlow Lite for object detection tasks. While implementing a section of the code, I encountered an error similar to the one described below:

**classes = interpreter.get_tensor(output_details[classes_idx]['index'])[0] # Class index of detected objects
IndexError: list index out of range**
It seems that the error is related to accessing the class index of detected objects, but I'm unsure how to resolve it. I've searched through forums and documentation, but couldn't find a clear solution.

Could you please provide some guidance on how to address this issue? Additionally, if there are any common causes or best practices related to this error, I would greatly appreciate any insights you can offer.

Furthermore, if you have encountered similar issues in the past, I would like to know how they were resolved. Understanding the steps taken by others in similar situations would be immensely helpful in troubleshooting my own code.

Thank you very much for your assistance. I look forward to your response.
