### ISSUE TITLE
TPUStrategy.run fails on non-primary thread with "No OpKernel was registered", "TPUReplicatedInput"

### ISSUE THREAD

**Issue by chrisbutner** [tensorflow/tensorflow#44487]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, included here
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): (a) Google Collab, (b) Debian 10 (Buster), Google Cloud VM TF2.3.1 image
- TensorFlow installed from (source or binary): (a) Google Collab, (b) Google Cloud VM TF2.3.1 image
- TensorFlow version (use command below): (a) Google Collab, (b) v2.3.0-54-gfcc4b966f1 2.3.1
- Python version: (a) Google Collab, (b) 3.7.3 (Google Cloud VM TF2.3.1 image)
- GPU model and memory: (a) Google Collab TPU, (b) Google Cloud TPU, us-central1-f, v2-8, 2.3.1

**Describe the current behavior**

Running TPUStrategy.run on a secondary thread crashes

**Describe the expected behavior**

Running TPUStrategy.run on a secondary thread behaves the same as on the primary thread, succeeding.

This is breaking for applications like inference from AlphaZero-style MCTS self-play originating from C++, using TPUStrategy.experimental_distribute_dataset, where either the primary C++ thread is required to perform other housekeeping, or where multiple prediction threads help to keep the inference pipeline more full. However, this minimal Python-only example gives the same error. The error differs slightly when experimental_distribute_dataset is used, but the final "Op:__inference_tpu_function_177" is common.

**Standalone code to reproduce the issue**

This snippet runs in a Google Collab notebook:

```
import tensorflow as tf
import threading

resolver = tf.distribute.cluster_resolver.TPUClusterResolver()
tf.config.experimental_connect_to_cluster(resolver)
tf.tpu.experimental.initialize_tpu_system(resolver)
strategy = tf.distribute.TPUStrategy(resolver)

@tf.function
def double(x):
  return x * 2.0

def test():
  input = tf.range(5, dtype=tf.float32)
  strategy.run(double, args=(input,))

test()
print("TPUStrategy.run works on primary thread")

thread = threading.Thread(target=test)
thread.start()
thread.join()
```

**Other info / logs**

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-2-c35bbe6196e2>", line 15, in test
    strategy.run(double, args=(input,))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/tpu_strategy.py", line 279, in run
    return self.extended.tpu_run(fn, args, kwargs, options)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/tpu_strategy.py", line 1095, in tpu_run
    return func(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 814, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'TPUReplicatedInput' used by {{node input0}} with these attrs: [T=DT_INT32, index=0, is_mirrored_variable=false, N=8, is_packed=false]
Registered devices: [CPU, TPU, TPU_SYSTEM, XLA_CPU]
Registered kernels:
  <no registered kernels>

	 [[input0]] [Op:__inference_tpu_function_177]

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3 and nightly version(`2.5.0-dev20201029`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/b49a6c3ee54fd24f47f8ea0a3d44dc36/untitled482.ipynb). Thanks!

**Comment by saeta** [comment]
Unassigning self, as I'm no longer working on TF, thanks!

**Comment by rxsang** [comment]
If you change your test function to:

```
def test():
  with tf.device("/job:worker"):
     input = tf.range(5, dtype=tf.float32)
     strategy.run(double, args=(input,))
```

does that work? I think it is related to a new thread is losing the existing device stack information.

**Comment by chrisbutner** [comment]
That does work, thanks a lot. Are there any performance implications adding the "/job:worker" context there? Do you know why that's only required for TPUStrategy.run as opposed to strategy-less calls, either naked or 'with tf.device("/TPU:0")'? Would this be a bug to fix or would API guidance be given?

Workaround code for reference:
```
import tensorflow as tf
import threading

resolver = tf.distribute.cluster_resolver.TPUClusterResolver()
tf.config.experimental_connect_to_cluster(resolver)
tf.tpu.experimental.initialize_tpu_system(resolver)
strategy = tf.distribute.TPUStrategy(resolver)

@tf.function
def double(x):
  return x * 2.0

def test():
  with tf.device("/job:worker"):
     input = tf.range(5, dtype=tf.float32)
     output = strategy.run(double, args=(input,))
     print(input, output)

test()
print("TPUStrategy.run works on primary thread")

thread = threading.Thread(target=test)
thread.start()
thread.join()
print("TPUStrategy.run works on secondary thread with /job:worker context")
```

**Comment by rxsang** [comment]
It shouldn't have performance regressions.  The reason is TPUs are a 2VM setup, you run the python code on the coordinator, but the actual execution is on the TPU worker. To avoid all users need to manually set the device placement, we enter the TPU worker device scope automatically in `tf.config.experimental_connect_to_cluster(resolver)` API, and it can be configured by the `make_master_device_default` argument. The problem is the new thread doesn't inherit existing TF device stack, so the default device becomes the coordinator again. I guess this is more like an API issue. @allenlavoie Allen do you know if it is expected that a new thread should clear out all existing device stack?

**Comment by chrisbutner** [comment]
Got it. So it sounds like this would run on the CPU on a secondary thread, and on the TPU on the primary thread?

```
def test():
  input = tf.range(5, dtype=tf.float32)
  output = double(input)
```

And this would run successfully on a secondary thread on the first TPU device because you've given it context back?

```
def test():
  with tf.device("/TPU:0"):
    input = tf.range(5, dtype=tf.float32)
    output = double(input)
```

**Comment by allenlavoie** [comment]
The device stack is thread local so multiple threads can manage their device stacks independently. I don't think anyone has considered the inheritance behavior on launching a new thread; it does seem like inheriting the device stack from the parent context would be nice, but I don't know how feasible that would be. Sounds like a reasonable request at least.

**Comment by rxsang** [comment]
> And this would run successfully on a secondary thread on the first TPU device because you've given it context back?
Yes

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tensorflow 2.5, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/9b0f5aef5fa91c5ae61125296085f284/44487.ipynb). Thanks!

**Comment by rxsang** [comment]
Re @sachinprasadhs, yes you need to write your test function as

```
def test():
  with tf.device("/job:worker"):
    input = tf.range(5, dtype=tf.float32)
    strategy.run(double, args=(input,))
```

As when you run the function with a new thread, the previous device context is lost. So you need to manually express that when in multiple threads.

**Comment by sachinprasadhs** [comment]
By modifying the context for def test(): the code runs successfully in Tensorflow 2.8. Attaching gist [here](https://colab.sandbox.google.com/gist/sachinprasadhs/c3a6a7d99423350ccf59bf26ba0f5c87/44487.ipynb) for reference. Thanks

**Comment by chrisbutner** [comment]
I think there's been a misunderstanding here.

A change to the test function has been given as a workaround, but is not a fix to the bug. I'm not aware of any TF documentation that says, on a new thread, you need to run the magic line, `with tf.device("/job:worker"):`

Please see allenlavoie's response above:

> The device stack is thread local so multiple threads can manage their device stacks independently. I don't think anyone has considered the inheritance behavior on launching a new thread; it does seem like inheriting the device stack from the parent context would be nice, but I don't know how feasible that would be. Sounds like a reasonable request at least.

**Comment by mohantym** [comment]
Hi @chrisbutner !

We are checking to see whether you still need help in this issue . 
I could not replicate this  issue in [2.9 ](https://colab.sandbox.google.com/gist/mohantym/1b7d7b814850491785237756f6756f62/git_44487.ipynb)and [2.11](https://colab.sandbox.google.com/gist/mohantym/814ca2d1d6f4cdacb08dacca6262a9bf/git_44487.ipynb#scrollTo=hgV1kzrZ5BHH). Could you let us know from your side.

Thank you!

**Comment by chrisbutner** [comment]
Hi @mohantym - in your 2.9 and 2.11 gists you're actually pasting the **workaround**, not the **original repro**.

Please see my comment on April 23rd, above:

> I think there's been a misunderstanding here.
> 
> A change to the test function has been given as a workaround, but is not a fix to the bug. I'm not aware of any TF documentation that says, on a new thread, you need to run the magic line, `with tf.device("/job:worker"):`
> 
> Please see allenlavoie's response above:
> 
> > The device stack is thread local so multiple threads can manage their device stacks independently. I don't think anyone has considered the inheritance behavior on launching a new thread; it does seem like inheriting the device stack from the parent context would be nice, but I don't know how feasible that would be. Sounds like a reasonable request at least.

**Comment by mohantym** [comment]
Ok @chrisbutner !
Thanks for the clarification.
Thank you!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
