### ISSUE TITLE
tf.logging documentation leads to 404

### ISSUE THREAD

**Issue by jpodivin** [tensorflow/tensorflow#44482]
## URL(s) with the issue:
As far as I can tell all articles describing tf.logging namespace. Such as:
[https://www.tensorflow.org/api_docs/python/tf/logging/TaskLevelStatusMessage](https://www.tensorflow.org/api_docs/python/tf/logging/TaskLevelStatusMessage)
or
[https://www.tensorflow.org/api_docs/python/tf/logging](https://www.tensorflow.org/api_docs/python/tf/logging)

## Description of issue (what needs changing):
Despite showing up in search results these articles are not accessible. 

### Clear description
Search results for `logging` and related queries contain links to nonexistent articles. 
Leading to confusion and potentially avoidable issues. 

### Submit a pull request?

Not at this time.

**Comment by jvishnuvardhan** [comment]
@jpodivin tf.logging doesn't exist in TF2.x. Please check [this issue](https://github.com/tensorflow/tensorflow/issues/26662#issuecomment-505913656) for more info.

I think we need to update that page. 

If someone wants to use it then import it from `tf.compat.v1.logging`. Thanks!

We will check this and update webpage accordingly. Thanks!

**Comment by jpodivin** [comment]
@jvishnuvardhan I was looking into how logging works in Tensorflow. And if you search official docs it comes up among first results:
![image](https://user-images.githubusercontent.com/66251151/97800813-96e0e700-1c38-11eb-86e2-9fa00458186e.png)

I thought it might have been coincidence so I tried to find more about the module, only to run into more 404s and that's pretty much when I decided to post this issue.

**Comment by jvishnuvardhan** [comment]
@jpodivin Agree with you. I am seeing the same search results. I am not sure why those pages are picked up in the search.

@MarkDaoust Any idea why search results are picking "404" error pages? Thanks!

**Comment by MarkDaoust** [comment]
I'l often surprised how long 404s stick around in there. That's just google search.
I've submitted a request to clear out those URLs, IDK how long that will take to activate.
