### ISSUE TITLE
Error while setting serial port parameters: 9,600 N 8 1: when run the "tensorflow/tensorflow/lite/micro/examples/person_detection/" example on Arduino Nano 33 BLE sense

### ISSUE THREAD

**Issue by bhavikapanara** [tensorflow/tensorflow#44493]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: tensorflow/tensorflow/lite/micro/examples/person_detection/
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:
-   **TensorFlow installed from (source or binary)**: 
-   **TensorFlow version (use command below)**: 1.14
-   **Python version**:3.6
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:
-   **GPU model and memory**:
-   **Exact command to reproduce**:

### Describe the problem
When I load the person detection example code in Arduino IDE, it works perfectly. 
But, for my custom dog detection model, I re-implement all steps as defined in [this ](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/person_detection/training_a_model.md)article. This custom dog detection model trained successfully and also able to generate .cc model file. But, when I replace person_detect_model_data.cpp file with my dog_model, it throw the below error message when I click on serial monitor.

Can someone help me to solve my issue?

Thanks a lot,
Bhavika

### Source code / logs
Sketch uses 428728 bytes (43%) of program storage space. Maximum is 983040 bytes.
Global variables use 127600 bytes (48%) of dynamic memory, leaving 134544 bytes for local variables. Maximum is 262144 bytes.
Device       : nRF52840-QIAA
Version      : Arduino Bootloader (SAM-BA extended) 2.0 [Arduino:IKXYZ]
Address      : 0x0
Pages        : 256
Page Size    : 4096 bytes
Total Size   : 1024KB
Planes       : 1
Lock Regions : 0
Locked       : none
Security     : false
Erase flash

Done in 0.000 seconds
Write 428736 bytes to flash (105 pages)
[==============================] 100% (105/105 pages)
Done in 17.794 seconds
Error while setting serial port parameters: 9,600 N 8 1

**Comment by dipampatel18** [comment]
Hey @bhavikapanara, I'm getting compilation error just while trying out the person_detection example code. Any idea what would be causing that? I installed all the libraries and boards.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
