### ISSUE TITLE
TensorBoard say Launching TensorBoard..., but nothing show

### ISSUE THREAD

**Issue by GF-Huang** [tensorflow/tensorflow#44494]
![9DAroMg0xc](https://user-images.githubusercontent.com/4510984/97798399-a116db80-1c60-11eb-8f2f-05a6bb148e39.gif)

![image](https://user-images.githubusercontent.com/4510984/97798449-269a8b80-1c61-11eb-95d1-b4f872a6d570.png)

**Comment by Saduf2019** [comment]
@GF-Huang 
please open this issue in the tensorboard repo, and move this to closed status.
