### ISSUE TITLE
tf-nightly2.4  run error

### ISSUE THREAD

**Issue by wwww666** [tensorflow/tensorflow#44490]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu18.04
- TensorFlow version (use command below):tf-nightly2.4
- Python version:3.7.4
- CUDA/cuDNN version:CUDA11.1
- GPU model and memory:RTX3090

**Describe the current behavior**
In my current environment, I use tf-nightly2.4 to run the bert model. After I run an epoch, I reported an error.
  value error: layer model expects 3 input(s), but it received 4 input tensors.
It seems that the output layer of the model is also regarded as the input layer.
But there is no problem with my code, it can run completely on CUDA10.1, so what is going on?

**Comment by lightlefter** [comment]
I think the tf-nightly2.4 can't support RTX 3090 very well. we need to wait new version. I have the same question about that.

**Comment by Saduf2019** [comment]
@wwww666 
Please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/43947#issuecomment-715295153) and let us know, also[lease refer to this issue with respect to the configuration mentioned :#43718 #43588 #44251
