### ISSUE TITLE
deterministic `Dataset.map`s aren't

### ISSUE THREAD

**Issue by jackd** [tensorflow/tensorflow#44491]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution: default colab

**Describe the current behavior**
`tf.data.Dataset.map` has a `determinstic` argument which is documented as allowing performance to be traded for determinism. Behaviour is not deterministic when `num_parallel_calls != 1` if `map_func` uses `tf.random` ops or methods from `tf.random.Generator` instances, even when `deterministic=True`.

**Describe the expected behavior**
Datasets mapped with `deterministic=True` should be deterministic, even with `num_parallel_calls != 1`. If this is not possible, documentation should not say that it is.

**Standalone code to reproduce the issue**
See [colab](https://colab.research.google.com/drive/1u9N87y5BsFFGXvTO23pIjRTjheQekPEJ?usp=sharing) (code reproduced below).

```python
import tensorflow as tf
import numpy as np

import time
import numpy as np
import tensorflow as tf

seed = 0
tf.random.set_seed(seed)


def map_fn(x):
  return tf.random.uniform((100,),)


ds = tf.data.Dataset.range(10).map(
    map_fn, num_parallel_calls=2, deterministic=True)

tf.random.set_seed(seed)
vals0 = [el.numpy() for el in ds]
tf.random.set_seed(seed)
vals1 = [el.numpy() for el in ds]

np.testing.assert_equal(vals0, vals1)
print("Passed")
```

**Other info / logs** Include any logs or source code that would be helpful to
```txt
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-3-9c92a75ab4eb> in <module>()
     18 vals1 = [el.numpy() for el in ds]
     19 
---> 20 np.testing.assert_equal(vals0, vals1)
     21 print("Passed")
     22 

3 frames
/usr/local/lib/python3.6/dist-packages/numpy/testing/_private/utils.py in assert_array_compare(comparison, x, y, err_msg, verbose, header, precision, equal_nan, equal_inf)
    844                                 verbose=verbose, header=header,
    845                                 names=('x', 'y'), precision=precision)
--> 846             raise AssertionError(msg)
    847     except ValueError:
    848         import traceback

AssertionError: 
Arrays are not equal
item=3

Mismatched elements: 100 / 100 (100%)
Max absolute difference: 0.8390552
Max relative difference: 70.61441
 x: array([0.839809, 0.390264, 0.704193, 0.916514, 0.008297, 0.778485,
       0.316561, 0.052142, 0.876872, 0.176245, 0.275351, 0.204759,
       0.999374, 0.40232 , 0.895112, 0.604971, 0.688866, 0.333363,...
 y: array([0.595369, 0.867852, 0.033959, 0.962069, 0.560696, 0.772698,
       0.060957, 0.602406, 0.495115, 0.442416, 0.500883, 0.282592,
       0.324962, 0.593064, 0.731267, 0.349757, 0.635136, 0.251549,...
```

**Comment by amahendrakar** [comment]
@jackd,
On setting the `experimental_deterministic` to `True` as per the [tf.data.Options](https://www.tensorflow.org/api_docs/python/tf/data/Options) documentation, I was able to run the code without any issues. 

Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/91238870723615bd21222d4b07cd7552/44491-with-options.ipynb#scrollTo=JJetXPbVagy1). Thanks!

**Comment by jackd** [comment]
@amahendrakar So I opened my original colab, added `with_options` and it still failed. I then opened your colab, and it also failed. I re-opened my colab with the `with_options` changes and it passed. I've refreshed my colab and re-run the results a few times now, and sometimes it passes, sometimes it fails. I've also removed the `with_options` component and observe the same behaviour - sometimes it passes, sometimes it fails.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/e98e3ea465b600027e82e9a8ede43c0a/44491.ipynb#scrollTo=RTif7JClak4R) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/911a3f8c74182713ed033559ce2f5775/44491-tf-nightly.ipynb#scrollTo=JkGrJapiaSqf). Please find the attached gist. Thanks!

**Comment by jsimsa** [comment]
The documentation talks about the order in which the elements are produced, which is what the `deterministic` option controls. When `num_parallel_calls > 1` the order in which parallel map transformation access any state of stateful map transformations is not deterministic.

For code to be both performant and deterministic, map transformations should not be stateful (and you can for instance use stateless RNG instead of the stateful one).

I would be happy to review a PR with your suggestion for how to improve the documentation of tf.data.Dataset map.

**Comment by jackd** [comment]
@jsimsa in this context does  "produced" mean the same as "returned"? I read that part of the documentation but assumed any stateful operations would be called during production. Happy to put in a PR.

**Comment by jsimsa** [comment]
"returned" is indeed more accurate.

To be more precise: when `map` executes deterministically, then assuming its inputs are `x_1, ..., x_n`, it will produce as output `f(x_1), ..., f(x_n)`. If `num_parallel_calls > 1`, the application of `f` on different `x_i` can happen in parallel (and possibly out-of-order). As a consequence, if the output of `f` depends on external state that `f` modifies (such as RNG), the produced values `f(x_0), ..., f(x_n)` are not guaranteed to be identical across different executions (even though the "order" in which they are returned is).

**Comment by rmothukuru** [comment]
@jackd,
Can you please respond to @jsimsa's comment. Thanks!

**Comment by jackd** [comment]
Doc change merged.
