### ISSUE TITLE
Jacobian fails on gradient of tf.function with if-elif-else or nested tf.cond

### ISSUE THREAD

**Issue by swertz** [tensorflow/tensorflow#44502]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): binary (pip)
- TensorFlow version (use command below): v2.3.0-54-gfcc4b966f1 2.3.1
- Python version: 3.8.5
- CUDA/cuDNN version: executing on CPU
- GPU model and memory: executing on CPU

**Describe the current behavior**

Computing the `GradientTape.jacobian` of the gradient (i.e. the Hessian) of a `tf.function` with either an if-elif-else construct or nested `tf.cond` results in a crash:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Trying to add unsupported dtype 10
         [[node gradients/AddN_2 (defined at debug.py:44) ]] [Op:__inference___backward___backward_f_bad_373_1158_1489]
```
See full trace attached as [trace_without_pfor.txt](https://github.com/tensorflow/tensorflow/files/5471053/trace_without_pfor.txt).

The computation works fine when disabling  `tf.functions`.

First-order derivatives (gradient or jacobian) work fine too.

**Describe the expected behavior**

Hessian evaluates to `tf.Tensor([[2.]], shape=(1, 1), dtype=float32)`.

**Standalone code to reproduce the issue**

The following works if `use_function = False`, but fails for both `f_bad` and `f_bad_cond` when using `use_function = True`. Both `f_good` and `f_good_const` always work fine.

```
import tensorflow as tf

use_function = True
use_pfor = False

tf.config.run_functions_eagerly(not use_function)

@tf.function
def f_bad(x):
    if x < -1.:
        return tf.pow(x, 2)
    elif x <= 1.:
        return tf.pow(x, 2)
    else:
        return tf.pow(x, 2)

@tf.function
def f_bad_cond(x):
    return tf.cond(x < -1.,
                   lambda: tf.pow(x, 2),
                   lambda: tf.cond(x <= 1.,
                                   lambda: tf.pow(x, 2),
                                   lambda: tf.pow(x, 2)))

@tf.function
def f_good(x):
    if x < -1.:
        return tf.pow(x, 2)
    else:
        return tf.pow(x, 2)

@tf.function
def f_good_cond(x):
    return tf.cond(x < -1.,
                   lambda: tf.pow(x, 2),
                   lambda: tf.pow(x, 2))

f = f_bad

x = tf.Variable([0.])
with tf.GradientTape(persistent=not use_pfor) as t2:
    with tf.GradientTape() as t1:
        y = f(x)
    g_y = t1.gradient(y, x)
hess = t2.jacobian(g_y, x, experimental_use_pfor=use_pfor)
print(hess)
```

Note that using `use_pfor = True` with `use_function = True` crashes for all four functions (see the attached [trace_with_pfor.txt](https://github.com/tensorflow/tensorflow/files/5471052/trace_with_pfor.txt)), but that is probably an entirely different issue...

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.3.1, nightly version(`2.5.0-dev20201029`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/cf8df22c346976e418fde3edd82057b2/untitled481.ipynb). Thanks!

**Comment by nikitamaia** [comment]
In nightly, seems even before `hess` the code is failing. The error message is `LookupError: No gradient defined for operation 'gradients/cond_grad/gradients/cond/cond/StatefulPartitionedCall_grad/SymbolicGradient' (op type: SymbolicGradient)` Seems to be [from tf.gradient](https://www.tensorflow.org/api_docs/python/tf/gradients), which raises a lookup error 'if one of the operations between x and y does not have a registered gradient function.'

**Comment by allenlavoie** [comment]
The latest nightly is a bit out of date (it's from last Thursday). I verified that the non-pfor issues have been fixed, likely by https://github.com/tensorflow/tensorflow/commit/07b75ffa453b1ec9189371244d21b6684503340b.

I'll look into adding vectorization for optionals.

**Comment by allenlavoie** [comment]
That should handle the pfor case. Please let me know if anything related to this bug is still broken.

**Comment by swertz** [comment]
Should be fixed, thanks a lot!!

**Comment by allenlavoie** [comment]
The pfor part of the fix was rolled back. Should get back in soon. But the non-pfor bit will still work.
