### ISSUE TITLE
IOS: TensorFlow Lite Error: Didn't find op for builtin opcode 'RESIZE_BILINEAR' version '3'

### ISSUE THREAD

**Issue by kaublezw** [tensorflow/tensorflow#44503]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No - It's the TensorFlow Lite IOS Object Detection example...I just tried to use my own converted Darknet Tiny Yolo v4 to TFLite
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  NA
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: IOS 13.7
- TensorFlow installed from (source or binary): I ran the POD install command on my mac
- TensorFlow version (use command below): unknown...whatever POD install installed 
- Python version: NA
- Bazel version (if compiling from source) NA:
- GCC/Compiler version (if compiling from source) NA:
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
From XCODE -> Play the solution to deploy to my IOS IPhone device.  Fails on the following line:
 interpreter = try Interpretor(modelPath: modelPath, options: options)  

**Describe the expected behavior**
I expected it to run the normal TFLite IOS object detection example program on my phone but with my model

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@kaublezw 
Please share complete stand alone code for us to replicate the issue faced.

**Comment by kaublezw** [comment]
Here's the source code:  https://github.com/kaublezw/tflite_ios_example/tree/main/ObjectDetection
It is the tensorflow lite object detection ios example program. All I did was change the labels to be my own and added my own model, yolo4-tiny-416.tflite.  It fails on line 110 in ModelDataHandler.swift when it tries to load the Interpreter.

**Comment by srjoglekar246** [comment]
@kaublezw Can you provide some more details on what error you see? Also, how did you obtain the yolo model? The example app supports models with a specific input/output signature, and possibly requires edits based on the input size & quantization of the model.

**Comment by kaublezw** [comment]
I don't have any more details other than the error message that's in the title that was shown in xcode...  IOS: TensorFlow Lite Error: Didn't find op for builtin opcode 'RESIZE_BILINEAR' version '3'   The yolo v4 tiny model was trained via darknet installed on a Linux machine.  It was tested thoroughly.  I converted the yolo weights to tflite using this code: https://github.com/hunglc007/tensorflow-yolov4-tflite/blob/master/save_model.py  

I tested the tflite model and it worked nearly identical to the original yolo tiny model.   I would expect an input/output error to occur at the point when I actually call the model...not when I try to simply instantiate the model using the out-of-box tf lite sample program.

**Comment by srjoglekar246** [comment]
@yyoon Could you take a look at this? Looks like the YOLO model requires ResizeBilinear v3 which was added in a more recent TFLite version. Is there some issue with the pod installed?

**Comment by kaublezw** [comment]
would it work if I tried training a yolo tiny v3 model and use that instead?

**Comment by yyoon** [comment]
@kaublezw Based on the `Podfile.lock` file in your repository, seems like you are using TFLite version 2.1.0, which is not the most recent version. Can you try running `pod update` from your project directory and build the project again? This will update your TFLite dependency to 2.3.0.

@srjoglekar246 Do you know which exact stable version is this op available? If this was not available in 2.1.0, I think a simple version update above would probably solve the issue.

**Comment by kaublezw** [comment]
That did it.  Thanks!

**Comment by srjoglekar246** [comment]
Thanks for confirming @kaublezw !
