### ISSUE TITLE
Training with TPU Out of range ... end of sequence at beginning of secund epoch

### ISSUE THREAD

**Issue by datend3nker** [tensorflow/tensorflow#44506]
**System information**
- Have I written custom code : Yes
- Version of Tensorflow: 2.3
- OS Platform and Distribution : Kaggle TPU
- TPU model  :v3-8
- dataset: [Raven_center_single](https://www.kaggle.com/datendnker/raven-center-single)

**Describe the current behavior**
My model is training and evaluating the first epoch as expected. At the beginning of second epoch Error raises: OutOfRangeError 

**Describe the expected behavior**
It should train Without running out of data

Here you can find the [Kaggle Notebook](https://www.kaggle.com/datendnker/notebook045427c7cb)

**Complete error log** 
---------------------------------------------------------------------------
OutOfRangeError                           Traceback (most recent call last)
<ipython-input-11-c2c56d1c82d6> in <module>
      5           validation_data=val_dataset,
      6           validation_steps=(config.entrys * config.test_size)/ config.batch_size,
----> 7           callbacks=[WandbCallback()])
      8 
      9 model.save_weights('./RAVEN-center-single_large_model.h5', overwrite=True)

/opt/conda/lib/python3.7/site-packages/wandb/integration/keras/keras.py in new_v2(*args, **kwargs)
    118             for cbk in cbks:
    119                 set_wandb_attrs(cbk, val_data)
--> 120         return old_v2(*args, **kwargs)
    121 
    122     training_arrays.orig_fit_loop = old_arrays

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
    106   def _method_wrapper(self, *args, **kwargs):
    107     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
--> 108       return method(self, *args, **kwargs)
    109 
    110     # Running inside `run_distribute_coordinator` already.

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1135           epoch_logs.update(val_logs)
   1136 
-> 1137         callbacks.on_epoch_end(epoch, epoch_logs)
   1138         training_logs = epoch_logs
   1139         if self.stop_training:

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py in on_epoch_end(self, epoch, logs)
    413       else:
    414         if numpy_logs is None:  # Only convert once.
--> 415           numpy_logs = tf_utils.to_numpy_or_python_type(logs)
    416         callback.on_epoch_end(epoch, numpy_logs)
    417 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/utils/tf_utils.py in to_numpy_or_python_type(tensors)
    535     return t  # Don't turn ragged or sparse tensors to NumPy.
    536 
--> 537   return nest.map_structure(_to_single_numpy_or_python_type, tensors)
    538 
    539 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/util/nest.py in map_structure(func, *structure, **kwargs)
    633 
    634   return pack_sequence_as(
--> 635       structure[0], [func(*x) for x in entries],
    636       expand_composites=expand_composites)
    637 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/util/nest.py in <listcomp>(.0)
    633 
    634   return pack_sequence_as(
--> 635       structure[0], [func(*x) for x in entries],
    636       expand_composites=expand_composites)
    637 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/utils/tf_utils.py in _to_single_numpy_or_python_type(t)
    531   def _to_single_numpy_or_python_type(t):
    532     if isinstance(t, ops.Tensor):
--> 533       x = t.numpy()
    534       return x.item() if np.ndim(x) == 0 else x
    535     return t  # Don't turn ragged or sparse tensors to NumPy.

/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py in numpy(self)
   1061     """
   1062     # TODO(slebedev): Consider avoiding a copy for non-CPU or remote tensors.
-> 1063     maybe_arr = self._numpy()  # pylint: disable=protected-access
   1064     return maybe_arr.copy() if isinstance(maybe_arr, np.ndarray) else maybe_arr
   1065 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py in _numpy(self)
   1029       return self._numpy_internal()
   1030     except core._NotOkStatusException as e:  # pylint: disable=protected-access
-> 1031       six.raise_from(core._status_to_exception(e.code, e.message), None)  # pylint: disable=protected-access
   1032 
   1033   @property

/opt/conda/lib/python3.7/site-packages/six.py in raise_from(value, from_value)

OutOfRangeError: 9 root error(s) found.
  (0) Out of range: {{function_node __inference_train_function_5573}} End of sequence
	 [[{{node cond_8/else/_73/cond_8/IteratorGetNext}}]]
	 [[strided_slice_18/_202]]
  (1) Out of range: {{function_node __inference_train_function_5573}} End of sequence
	 [[{{node cond_8/else/_73/cond_8/IteratorGetNext}}]]
	 [[tpu_compile_succeeded_assert/_16956405043851590776/_5/_185]]
  (2) Out of range: {{function_node __inference_train_function_5573}} End of sequence
	 [[{{node cond_8/else/_73/cond_8/IteratorGetNext}}]]
  (3) Out of range: {{function_node __inference_train_function_5573}} End of sequence
	 [[{{node cond_8/else/_73/cond_8/IteratorGetNext}}]]
	 [[Const_4/_212]]
  (4) Out of range: {{function_node __inference_train_function_5573}} End of sequence
	 [[{{node cond_8/else/_73/cond_8/IteratorGetNext}}]]
	 [[cond_14/switch_pred/_140/_90]]
  (5) Out of range: {{function_node __inference_train_function_5573}} End of sequence
	 [[{{node cond_8/else/_73/cond_8/IteratorGetNext}}]]
	 [[Pad_11/paddings/_154]]
  (6) Out of range: {{function_node __inference_train_function_5573}} End of sequence
	 [[{{node cond_8/else/_73/cond_8/IteratorGetNext}}]]
	 [[cond_15/switch_pred/_151/_92]]
  (7) Out of range: {{function_node __inference_train_function_5573}} End of sequence
	 [[{{node cond_8/else/_73/cond_8/IteratorGetNext}}]]
	 [[strided_slice_15/_192]]
  (8) Out of range: {{function_node __inference_train_function_5573}} End of sequence
	 [[{{node cond_8/else/_73/cond_8/IteratorGetNext}}]]
	 [[Shape_22/_124]]
0 successful operations.
0 derived errors ignored.

**Comment by ravikyram** [comment]
@datend3nker 

I tried in colab and could not able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/b303727cf14babd875c76cff71f0dd95/untitled480.ipynb).Please, help with the reproducible code. Thanks!

**Comment by datend3nker** [comment]
Simplified the code [here](https://colab.research.google.com/gist/datend3nker/e0448ed4bf48edd52e35ed35177f94bb/untitled480.ipynb). Colab returns more information about the error. Apparently I made a mistake with the steps per epoch. So case closed

**Comment by kmcguigan1** [comment]
@datend3nker could I ask you how you managed to fix this error? I am experiencing this error on the kaggle TPUs aswell. I have my validation steps per epoch set to the ceiling of the number of validation steps / batchsize. This would be the number of batches sent through the system correct? or the erro in this code?

**Comment by datend3nker** [comment]
@kmcguigan1, since it has been a long time, I am not really into this topic. I can give you a [notebook ](https://www.kaggle.com/code/datendnker/raven-simple-mlp), which does train the same model and does not fail. Accuracy in this case is not relevant. Good luck in finding the parts, that unbreak  your code

**Comment by Nsingh321** [comment]
@kmcguigan1 Hello, I am also experiencing the same issue on Kaggle's TPU. Have you or anyone found the solution of the issue??
