### ISSUE TITLE
FAILED: Build did NOT complete successfully

### ISSUE THREAD

**Issue by project2501a** [tensorflow/tensorflow#44500]
Hello ,

- OS : pc windows 10
- CPU : i7-5820K
- RAM: 16G
- TensorFlow installed from (source or binary): source git master
- TensorFlow version: git Master
- Python version: 3.8.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): [bazel release 3.7.0]
- GCC/Compiler version (if compiling from source): Visual Studio Build Tools 2019 and Visual Studio Community 2019
- CUDA/cuDNN version: cuda_10.1.105_418.96_win10/ cudnn-10.1-windows10-x64-v7.6.5.32
- GPU model and memory: Nvidia getforce GTX1070Ti / 8192 MB

in build verbose :
`
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/9bb9b737c5573cf3850230bc4db8dac7be0e1e85.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
`
and

`ERROR: C:/tf/tensorflow/tensorflow/core/kernels/BUILD:1157:18: C++ compilation of rule '//tensorflow/core/kernels:reverse_op_gpu' failed (Exit 2): python.exe failed: error executing command`

[Full log.txt](https://github.com/tensorflow/tensorflow/files/5470759/Full.log.txt)

**Provide the exact sequence of commands / steps that you executed before running into the problem**

i search to build tensorflow-gpu with support AVX2
build command in MSYS :

 bazel build --define=no_tensorflow_py_deps=true --local_ram_resources=12288 //tensorflow/tools/pip_package:build_pip_package

**Comment by Saduf2019** [comment]
@project2501a 
Could you please try with CUDA 11 and cuDNN 8 and let us know if you still face issues.

**Comment by project2501a** [comment]
@Saduf2019 
Hello,
i have build with :
                          bazel-3.7.0-windows-x86_64
                          msys2-x86_64-20200903 (and update with : pacman -Syu
                                                                    pacman -Su)
                          python 3.8.6
                          cuda_11.1.1_win10_network
                          cudnn-11.1-windows-x64-v8.0.4.30
with this command :   bazel build --define=no_tensorflow_py_deps=true --local_ram_resources=12288 //tensorflow/tools
                                  /pip_package:build_pip_package

and have 2 other error : 
                                   1) ERROR: C:/tf/tensorflow/tensorflow/BUILD:1018:19: Executing genrule //tensorflow:tf_python_api_gen_v2 failed (Exit 1): bash.exe failed: error executing command

                                    2) RuntimeError: The current Numpy installation ('C:\\Users\\dinonornis\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
Target //tensorflow/tools/pip_package:build_pip_package failed to build


[Full log-2.txt](https://github.com/tensorflow/tensorflow/files/5482100/Full.log-2.txt)


Thx for your help :)

**Comment by Saduf2019** [comment]
@project2501a 
Please install all the dependencies listed ex numpy.

**Comment by tomweingarten** [comment]
I'm experiencing this same 404 error on Ubuntu with CUDA 11.1 and CUDNN 8.0.5

**Comment by Saduf2019** [comment]
@tomweingarten 
Can you please try with CUDA 11.0? TF 2.4 (and nightly) is built and tested against CUDA 11.0, not 11.1.

**Comment by tomweingarten** [comment]
This is now resolved, thank you!

**Comment by samfux84** [comment]
Same issue here. I am trying to build TF 2.4 with CUDA 11.0.3 and CUDNN 8.0.5. Some downloads are not working:

```
WARNING: Download from https://mirror.bazel.build/github.com/aws/aws-sdk-cpp/archive/1.7.336.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/f402e682d0ef5598eeffc9a21a691b03e602ff58.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
```

**Comment by smartbooks** [comment]
INFO: Found applicable config definition build:dynamic_kernels in file /home/hortor/Desktop/data1/work/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
DEBUG: Rule 'io_bazel_rules_go' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1557349968 -0400"
DEBUG: Repository io_bazel_rules_go instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule git_repository defined at:
  /home/hortor/.cache/bazel/_bazel_hortor/c4d98c77c9b8b7dcb6bae627296ef8a4/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18: in <toplevel>
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule git_repository defined at:
  /home/hortor/.cache/bazel/_bazel_hortor/c4d98c77c9b8b7dcb6bae627296ef8a4/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18: in <toplevel>
WARNING: Download from https://mirror.bazel.build/github.com/aws/aws-sdk-cpp/archive/1.7.336.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/f402e682d0ef5598eeffc9a21a691b03e602ff58.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Analyzed target //tensorflow/tools/lib_package:libtensorflow (190 packages loaded, 20055 targets configured).

**Comment by redradist** [comment]
> 
> 
> Same issue here. I am trying to build TF 2.4 with CUDA 11.0.3 and CUDNN 8.0.5. Some downloads are not working:
> 
> ```
> WARNING: Download from https://mirror.bazel.build/github.com/aws/aws-sdk-cpp/archive/1.7.336.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
> WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/f402e682d0ef5598eeffc9a21a691b03e602ff58.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
> ```

@samfux84 Have you found the solution for downloading llvm ?
I have the same issue with tensorflow 2.4.1

**Comment by samfux84** [comment]
@redradist : Please have a look at #45739
