### ISSUE TITLE
tensorflow.keras.callback.TensorflowCallback turns off recording for tf.summary, and stops other callbacks from recording summaries

### ISSUE THREAD

**Issue by ashahab** [tensorflow/tensorflow#44505]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary (colab)
- TensorFlow version (use command below): 2.3
- Python version: 3+
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: 
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
### Steps to reproduce
Any custom keras callback that writes using tf.summary at batch_start or batch_end methods will have their `tf.summary` writing methods such as `tf.summary.scalar` not write anything to the protobuf.
### Root cause
`tensorflow.keras.callback.TensorflowCallback` modifies the private summary field of tensorflow.python.ops.summary_ops_v2:

[summary_state = summary_ops_v2._summary_state  # pylint: disable=protected-access](https://github.com/tensorflow/tensorflow/blob/v2.3.1/tensorflow/python/keras/callbacks.py#L2059)

**Describe the expected behavior**
TensorflowCallback should not impact the recording of other callbacks. Instead of updating the global summary_state, it should locally guard the writing of summaries.
**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
https://colab.research.google.com/drive/1UPm1m3kNZCFaJZHHYT5rbx1Xcx0VZ7gR

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
Custom callback which can show the issue:
```python
class CustomCallback(tf.keras.callbacks.Callback):
    def __init__(self):
      self.step = 1
    
    def on_train_batch_end(self, batch, logs=None):
        if tf.summary.should_record_summaries():
          print(f"Warning!!!!!!!!!!!!: can only record summaries for step: {self.step}")
        self.step += 1

tensorboard_callback = tf.keras.callbacks.TensorBoard(logdir, update_freq=100)
custom_callback = CustomCallback()
model.fit(x=x_train, 
            y=y_train, 
            epochs=epochs, 
            validation_data=(x_test, y_test), 
            callbacks=[tensorboard_callback, custom_callback])

```
The above code segment outputs:

```bash
  95/1875 [>.............................] - ETA: 7s - loss: 0.9137 - accuracy: 0.6734
Warning!!!!!!!!!!!!: can record summaries for step: 100
 191/1875 [==>...........................] - ETA: 7s - loss: 0.7903 - accuracy: 0.7202
Warning!!!!!!!!!!!!: can record summaries for step: 200
 292/1875 [===>..........................] - ETA: 6s - loss: 0.7092 - accuracy: 0.7464
Warning!!!!!!!!!!!!: can record summaries for step: 300
 396/1875 [=====>........................] - ETA: 6s - loss: 0.6668 - accuracy: 0.7633
Warning!!!!!!!!!!!!: can record summaries for step: 400
 493/1875 [======>.......................] - ETA: 5s - loss: 0.6315 - accuracy: 0.7762
Warning!!!!!!!!!!!!: can record summaries for step: 500
 595/1875 [========>.....................] - ETA: 5s - loss: 0.6107 - accuracy: 0.7834
Warning!!!!!!!!!!!!: can record summaries for step: 600
 692/1875 [==========>...................] - ETA: 4s - loss: 0.5928 - accuracy: 0.7891
Warning!!!!!!!!!!!!: can record summaries for step: 700
 792/1875 [===========>..................] - ETA: 4s - loss: 0.5800 - accuracy: 0.7931
Warning!!!!!!!!!!!!: can record summaries for step: 800
 892/1875 [=============>................] - ETA: 4s - loss: 0.5656 - accuracy: 0.7972
Warning!!!!!!!!!!!!: can record summaries for step: 900
 995/1875 [==============>...............] - ETA: 3s - loss: 0.5549 - accuracy: 0.8015
Warning!!!!!!!!!!!!: can record summaries for step: 1000
1092/1875 [================>.............] - ETA: 3s - loss: 0.5439 - accuracy: 0.8059
Warning!!!!!!!!!!!!: can record summaries for step: 1100
1194/1875 [==================>...........] - ETA: 2s - loss: 0.5351 - accuracy: 0.8083
Warning!!!!!!!!!!!!: can record summaries for step: 1200
1293/1875 [===================>..........] - ETA: 2s - loss: 0.5289 - accuracy: 0.8101
Warning!!!!!!!!!!!!: can record summaries for step: 1300
1388/1875 [=====================>........] - ETA: 2s - loss: 0.5231 - accuracy: 0.8121
Warning!!!!!!!!!!!!: can record summaries for step: 1400
1490/1875 [======================>.......] - ETA: 1s - loss: 0.5148 - accuracy: 0.8151
Warning!!!!!!!!!!!!: can record summaries for step: 1500
1591/1875 [========================>.....] - ETA: 1s - loss: 0.5102 - accuracy: 0.8163
Warning!!!!!!!!!!!!: can record summaries for step: 1600
1686/1875 [=========================>....] - ETA: 0s - loss: 0.5060 - accuracy: 0.8174
Warning!!!!!!!!!!!!: can record summaries for step: 1700
1796/1875 [===========================>..] - ETA: 0s - loss: 0.5002 - accuracy: 0.8193
Warning!!!!!!!!!!!!: can record summaries for step: 1800
```

**Comment by amahendrakar** [comment]
@ashahab,
On running the given code snippet, I am facing an error stating `NameError: name 'model' is not defined`.

Also, I do not have access to the Colab notebook you have provided. Could you please provide the required permissions to view the files. Thanks!

**Comment by ashahab** [comment]
@amahendrakar  thanks for looking, I've fixed the access issue in the colab notebook. Please try to run it. It is a toy example created to demonstrate the issue.

**Comment by ashahab** [comment]
@amahendrakar Have you been able to reproduce the issue?

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/4b3d647a0cd6dfe8a8c64ccc6faa42ba/44505-tf-nightly.ipynb). Thanks!

**Comment by Saduf2019** [comment]
We see a 403 error on nightly [2.6.0-dev20210419], please find the [gist here](https://colab.research.google.com/gist/Saduf2019/3ec3ad6b49999b76ffc07a9a74a95ea4/untitled589.ipynb)

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210530, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/55f8fee139b555d5fc30f17de994736d/44505.ipynb). Thanks!

**Comment by mohantym** [comment]
Hi @ashahab! I could not replicate this issue in [TF 2.7](https://colab.sandbox.google.com/gist/mohantym/72530de7578e09655aa81aacde3f63ff/44505.ipynb#scrollTo=bjsyFTE6uTy0) . Thanks!
