### ISSUE TITLE
attr return values handled differently than dict by tf.distribute.Strategy.run

### ISSUE THREAD

**Issue by Qrox** [tensorflow/tensorflow#44515]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.3.1
- Python version: 3.7.4
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.2
- GPU model and memory: 1050 Ti 4GB

**Describe the current behavior**
If I run the following snippet,
```python
import attr
import tensorflow as tf

gpus = tf.config.list_physical_devices('GPU')
tf.config.set_logical_device_configuration(
    gpus[0],
    [tf.config.LogicalDeviceConfiguration(memory_limit=1024),
     tf.config.LogicalDeviceConfiguration(memory_limit=1024)])

@attr.s
class WrappedTensor(object):
    tensor = attr.ib()

@tf.function
def func_dict(x):
    def func_dict_per_replica(x):
        return x
    print('Result of Strategy.run(func_dict_per_replica):',
          tf.distribute.get_strategy().run(func_dict_per_replica, (x,)))

@tf.function
def func_attr(x):
    def func_attr_per_replica(x):
        return x
    print('Result of Strategy.run(func_attr_per_replica):',
          tf.distribute.get_strategy().run(func_attr_per_replica, (x,)))

with tf.distribute.MirroredStrategy().scope():
    data = tf.data.Dataset.from_tensors(tf.constant(0, shape=[2]))
    data = tf.distribute.get_strategy().experimental_distribute_dataset(data)
    v = next(iter(data))
    print()
    x = {'tensor': v}
    print('Input signature of func_dict:', func_dict.get_concrete_function(x).structured_input_signature)
    print()
    x = WrappedTensor(v)
    print('Input signature of func_attr:', func_attr.get_concrete_function(x).structured_input_signature)
```
I get the following output:
```
Result of Strategy.run(func_dict_per_replica): {'tensor': PerReplica:{
  0: <tf.Tensor 'x:0' shape=(1,) dtype=int32>,
  1: <tf.Tensor 'x_1:0' shape=(1,) dtype=int32>
}}
Input signature of func_dict: (({'tensor': PerReplicaSpec(TensorSpec(shape=(1,), dtype=tf.int32, name=None), TensorSpec(shape=(1,), dtype=tf.int32, name=None))},), {})

Result of Strategy.run(func_attr_per_replica): PerReplica:{
  0: WrappedTensor(tensor=<tf.Tensor 'x:0' shape=(1,) dtype=int32>),
  1: WrappedTensor(tensor=<tf.Tensor 'x_1:0' shape=(1,) dtype=int32>)
}
Input signature of func_attr: ((WrappedTensor(tensor=PerReplicaSpec(TensorSpec(shape=(1,), dtype=tf.int32, name=None), TensorSpec(shape=(1,), dtype=tf.int32, name=None))),), {})
```

**Describe the expected behavior**
As shown in the output, the input signatures of both functions are generated by replacing values in the structures with the respective `PerReplicaSpec`, so here `attr` objects are treated like a nested structure similar to a `dict`. One would then expect the result of the two functions follow a similar treatment. However, the result of `func_attr` is `WrappedTensor` objects stored inside `PerReplica` objects, as opposed to `PerReplica` objects wrapped inside `WrappedTensor` objects, so `attr` is again not treated like a nested structure here, inconsistent with the input signatures.

I personally think tensorflow should treat `attr` objects like a nested structure (that is, change the behavior of `func_attr` to match that of `func_dict`), because then you can write member functions that handle distributed computation automatically when the attributes of a `attr` object are `DistribtuedValue`s.

**Standalone code to reproduce the issue**
See the code snippet above.

**Other info / logs**
N/A

**Comment by ckkuang** [comment]
Thanks for filing the issue. I think it is a fair ask and `attrs` indeed should be treated as a nested structure across TF stack.

**Comment by sushreebarsa** [comment]
@Qrox It looks like you are using an older Version of Tensorflow . Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.5 and let us know if the issue still persists? Thanks!

**Comment by Qrox** [comment]
Tested with tensorflow 2.5.0 and the output is the same as before, so this hasn't been fixed.

**Comment by mohantym** [comment]
Hi @Qrox !

We are checking to see whether you still need help in this issue . 
I could not replicate this issue in [2.9](https://colab.sandbox.google.com/gist/mohantym/9942fbf515ea42f6fc4d1da1bafd6e4a/git_44515.ipynb#scrollTo=4EvATbSq16Cv) and [2.11](https://colab.sandbox.google.com/gist/mohantym/68ffc6cd6cf0d79c35548124386ae185/git_44515.ipynb#scrollTo=8dS9oYh7235W) .

Could you let us know from your side.

Thank you!

**Comment by mohantym** [comment]
Ok @Qrox !
Thanks for the clarification on replicating with two Gpu's.
Thank you!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
