### ISSUE TITLE
Custome loop distributed learning examples [proposed Label] comp:dist-start

### ISSUE THREAD

**Issue by sakh251** [tensorflow/tensorflow#44517]
Hello,
I saw you provide the latest strategies to write customer loop for distributed learning in [this video](https://www.youtube.com/watch?v=jKV53r9-H14).
However I am trying to find examples code in GitHub, but it seems these new style codes are not available.

Would you please let me know if you have published those codes or not? or any similar ones?

Thank you

**Comment by ravikyram** [comment]
@sakh251 

Please, refer this [tutorial](https://www.tensorflow.org/guide/distributed_training), [custom training](https://www.tensorflow.org/tutorials/distribute/custom_training) and see if it helps you.Thanks!
