### ISSUE TITLE
TypeError: call() missing 2 required positional arguments: 'features' and 'hidden'

### ISSUE THREAD

**Issue by DavidInWuhanChina** [tensorflow/tensorflow#44512]
**System information**
- OS Platform and Distribution :CentOS Linux release 7.7.1908
-TensorFlow version:2.3.0

I try to convert [the tensorflow offical image caption model ](https://www.tensorflow.org/tutorials/text/image_captioning?hl=en)to TFLite model.Here is the[ gist](https://colab.research.google.com/gist/DavidInWuhanChina/f83e3e11009211f3469436bbc069b18a/43753.ipynb).

I try to convert the `tf.keras.Model `'s encoder and decoder model as following:

```
encoder_converter = tf.lite.TFLiteConverter.from_keras_model(encoder)
decoder_converter = tf.lite.TFLiteConverter.from_keras_model(decoder)

encoder_model = encoder_converter.convert()
decoder_model = decoder_converter.convert()
```

but the eorror is 

```
INFO:tensorflow:Assets written to: /tmp/tmpgvx51gsa/assets

INFO:tensorflow:Assets written to: /tmp/tmpgvx51gsa/assets

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-55-9f0e9ba5bb99> in <module>()
      2 decoder_converter = tf.lite.TFLiteConverter.from_keras_model(decoder)
      3 encoder_model = encoder_converter.convert()
----> 4 decoder_model = decoder_converter.convert()

11 frames

/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    300   def wrapper(*args, **kwargs):
    301     with ag_ctx.ControlStatusCtx(status=ag_ctx.Status.DISABLED):
--> 302       return func(*args, **kwargs)
    303 
    304   if inspect.isfunction(func) or inspect.ismethod(func):

TypeError: call() missing 2 required positional arguments: 'features' and 'hidden'

```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/ae5ce7da04942b487419b8bf565977a1/44512.ipynb#scrollTo=1nVb-qLe0GBL&line=3&uniqifier=1). Thanks!

**Comment by smilingday** [comment]
@abattery @karimnosseir to help take a look? Thanks

**Comment by renjie-liu** [comment]
Hi Can you try export as saved model and try the saved_model conversion?

thanks

**Comment by DavidInWuhanChina** [comment]
> 
> 
> Hi Can you try export as saved model and try the saved_model conversion?
> 
> thanks
I have tried export as saved model.But the same problem came.[gist](https://colab.research.google.com/gist/DavidInWuhanChina/1d83802584a04e2f81ebebfbdfe763ba/44512.ipynb)

TypeError: call() missing 2 required positional arguments: 'features' and 'hidden'

**Comment by abattery** [comment]
This failure is happening at the the saved model exporter. @k-w-w @ scottzhu could you take a look at the keras model exporting failure?

**Comment by DavidInWuhanChina** [comment]
Is there anyone answer the question?

**Comment by Saduf2019** [comment]
@DavidInWuhanChina 
Is this still an issue
