### ISSUE TITLE
need some help building on windows

### ISSUE THREAD

**Issue by fuckfrancisco** [tensorflow/tensorflow#44519]
**System information**
- OS Platform and Distribution:Windows 7 x64
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.15.4
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.26
- GCC/Compiler version (if compiling from source): MSVC2017
- CUDA/cuDNN version: 10.0/7.4
- GPU model and memory: K40m 12G

im trying to compile TF using /LTCG but bazel's def_parser.exe crashes I guess he doesn't understand LTO data in the .lib files, I tried to build TF twice once with LTO and once without and copying the .def files manually but this doesn't prevent bazel from rerunning the def_parser.exe, if I delete def_parser.exe bazel gives an error saying that he is corrupt and will not build anything at all, same problem if I try to modify the def_parser.exe into other exe file :x

**Comment by fuckfrancisco** [comment]
I also tried to use def_parser.exe from the newest bazel it didn't work :x

**Comment by fuckfrancisco** [comment]
see also: https://stackoverflow.com/questions/57082617/building-tensorflow-with-ltcg

**Comment by amahendrakar** [comment]
@fuckfrancisco,
TensorFlow 1.x is not actively support. Could you please try building TensorFlow v2.3 and check if you are facing the same issue. Thanks!

**Comment by fuckfrancisco** [comment]
my python program don't work with 2 :x

**Comment by fuckfrancisco** [comment]
is it possible to build with cmake ?

**Comment by fuckfrancisco** [comment]
is it possible to build 2 with --config=v1 ?

**Comment by errord** [comment]
Bazel version is 0.26?

**Comment by fuckfrancisco** [comment]
is there a file in the build system can allow to add /GL- only to the contrib ?

**Comment by fuckfrancisco** [comment]
cl.exe stucks on infinite loop when compiling file segment_reduction_ops in tensorflow/core/kernels with /arch:AVX or /arch:AVX2
I built a version without AVX and put the .o file in there but bazel overwrites it, is there any way to prevent that ?

**Comment by amahendrakar** [comment]
> is it possible to build 2 with --config=v1 ?

The ` --config=v1` is used to build TensorFlow 1.x.

> is it possible to build with cmake ?

You'll have to use Bazel to compile TensorFlow. For more information, please take a look at [this guide](https://www.tensorflow.org/install/source_windows). 

> my python program don't work with 2 :x

In this case, I'd suggest you to migrate your code to support TensorFlow 2.x as shown in [this guide](https://www.tensorflow.org/guide/migrate
). Thanks!

**Comment by fuckfrancisco** [comment]
realy ? you can convert from v1 to v2 automatic with tf_upgrade_v2 ? that's nice... thank I will try this :)

**Comment by amahendrakar** [comment]
> realy ? you can convert from v1 to v2 automatic with tf_upgrade_v2 ? that's nice... thank I will try this :)

@fuckfrancisco,
Any updates regarding this? Is this still an issue? Thanks!
