### ISSUE TITLE
crashed at TfLiteInterpreterCreate 

### ISSUE THREAD

**Issue by jucysoft** [tensorflow/tensorflow#44513]
- iPhone11 pro
- Podfile
pod 'TensorFlowLiteSelectTfOps', '~> 0.0.1-nightly'
pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly', :subspecs => ['Metal']

- crashed at TfLiteInterpreterCreate.
My custom model is used at StyleTranfer demo project.

guard let cInterpreter = TfLiteInterpreterCreate(model.cModel, cInterpreterOptions) else {
--> Thread 8: EXC_BAD_ACCESS (code=1, address=0x0)

Thread 8 Queue : org.tensorflow.examples.lite.style_transfer (serial)
#0	0x00000001f0bce618 in _platform_memmove ()
#1	0x00000001007d406c in ___lldb_unnamed_symbol7040$$TFL Style Transfer ()
#2	0x00000001007c82e4 in ___lldb_unnamed_symbol6806$$TFL Style Transfer ()
#3	0x00000001007d0f90 in ___lldb_unnamed_symbol6968$$TFL Style Transfer ()
#4	0x00000001007c3744 in ___lldb_unnamed_symbol6746$$TFL Style Transfer ()
#5	0x00000001007c4304 in ___lldb_unnamed_symbol6748$$TFL Style Transfer ()
#6	0x00000001007b94bc in ___lldb_unnamed_symbol6574$$TFL Style Transfer ()
#7	0x0000000100429cfc in ___lldb_unnamed_symbol129$$TFL Style Transfer ()
#8	0x0000000100429924 in ___lldb_unnamed_symbol128$$TFL Style Transfer ()
#9	0x0000000100429678 in ___lldb_unnamed_symbol127$$TFL Style Transfer ()
#10	0x00000001007b9420 in ___lldb_unnamed_symbol6573$$TFL Style Transfer ()
#11	0x000000010042cc80 in ___lldb_unnamed_symbol169$$TFL Style Transfer ()
#12	0x00000001005638fc in ___lldb_unnamed_symbol2108$$TFL Style Transfer ()
#13	0x0000000100524554 in ___lldb_unnamed_symbol1773$$TFL Style Transfer ()
#14	0x000000010052431c in TfLiteInterpreterCreate ()
#15	0x000000010040e854 in Interpreter.init(modelPath:options:delegates:) at /Users/user/git/examples-master/lite/examples/style_transfer/ios/Pods/TensorFlowLiteSwift/tensorflow/lite/experimental/swift/Sources/Interpreter.swift:98
#16	0x000000010040e144 in Interpreter.__allocating_init(modelPath:options:delegates:) ()
#17	0x00000001003fe3a0 in closure #1 in static Inpainting.newInstance(inpaintingModel:useMetalDelegate:completion:) at /Users/user/git/examples-master/lite/examples/style_transfer/ios/StyleTransfer/Inpainting.swift:97
#18	0x00000001003fee34 in thunk for @escaping @callee_guaranteed () -> () ()
#19	0x000000010096bb68 in _dispatch_call_block_and_release ()
#20	0x000000010096d5f0 in _dispatch_client_callout ()
#21	0x0000000100974fa8 in _dispatch_lane_serial_drain ()
#22	0x0000000100975cb4 in _dispatch_lane_invoke ()
#23	0x0000000100981e38 in _dispatch_workloop_worker_thread ()
#24	0x00000001f0bd4908 in _pthread_wqthread ()

**Comment by jvishnuvardhan** [comment]
@jucysoft Can you please create a simple standalone code to reproduce the issue? Thanks!

**Comment by sdgbraincraft** [comment]
this issue still persists. please see this project [Link](https://github.com/sdgbraincraft/Tensorflow-Image-Segmentation). I cloned the project from examples.

**Comment by jucysoft** [comment]
When  a tflite model includes a TransposeConv node, this issue happens. Could you test it?

**Comment by jucysoft** [comment]
This issue was resolved at nightly build version by khanh.

**Comment by nimishpatel19** [comment]
Still it is crashing at my end. @jucysoft can you guide me how to resolve this?

**Comment by jucysoft** [comment]
I just used the nightly build version of at that time. no other resolution.

Thank you,

**Comment by nimishpatel19** [comment]
`pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly'`

I have used this. Is it fine?

**Comment by nimishpatel19** [comment]
> this issue still persists. please see this project [Link](https://github.com/sdgbraincraft/Tensorflow-Image-Segmentation). I cloned the project from examples.

Did you solve this issue?

**Comment by jucysoft** [comment]
I ran the my old project with nightly version, but current nightly version reproduced this error. so, I changed pod file like following. It resolved this error.

pod 'TensorFlowLiteSwift', '~> 2.3.0', :subspecs => ['Metal']

**Comment by nimishpatel19** [comment]
> I ran the my old project with nightly version, but current nightly version reproduced this error. so, I changed pod file like following. It resolved this error. pod 'TensorFlowLiteSwift', '~> 2.3.0', :subspecs => ['Metal']
> […](#)
> 2021. 5. 22. 오후 3:20, Nimish Patel ***@***.***> 작성: ﻿ this issue still persists. please see this project Link. I cloned the project from examples. Did you solve this issue? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks. Let me try it right now.

**Comment by araii** [comment]
> I ran the my old project with nightly version, but current nightly version reproduced this error. so, I changed pod file like following. It resolved this error. pod 'TensorFlowLiteSwift', '~> 2.3.0', :subspecs => ['Metal']
> […](#)
> 2021. 5. 22. 오후 3:20, Nimish Patel ***@***.***> 작성: ﻿ this issue still persists. please see this project Link. I cloned the project from examples. Did you solve this issue? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

....
hi, I'm facing the same [EXC_BAD_ACCESS error](https://github.com/tensorflow/tensorflow/issues/44513#issue-734202410)

and I tried changing the pod file, but there is new error. Lines of 
" TensorFlow Lite Error: Unsupported data type 13 in tensor"  followed by 
"Failed to create the interpreter with error: Failed to create the interpreter."

**Comment by nimishpatel19** [comment]
> > I ran the my old project with nightly version, but current nightly version reproduced this error. so, I changed pod file like following. It resolved this error. pod 'TensorFlowLiteSwift', '~> 2.3.0', :subspecs => ['Metal']
> > […](#)
> > 2021. 5. 22. 오후 3:20, Nimish Patel _**@**_.***> 작성: ﻿ this issue still persists. please see this project Link. I cloned the project from examples. Did you solve this issue? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> ....
> hi, I'm facing the same [EXC_BAD_ACCESS error](https://github.com/tensorflow/tensorflow/issues/44513#issue-734202410)
> 
> and I tried changing the pod file, but there is new error. Lines of
> " TensorFlow Lite Error: Unsupported data type 13 in tensor" followed by
> "Failed to create the interpreter with error: Failed to create the interpreter."
> 
> <img alt="Screenshot 2021-05-31 at 6 28 59 PM" width="483" src="https://user-images.githubusercontent.com/1277150/120180227-1621b200-c23e-11eb-8fb0-b09d7f285722.png">
> 
> any help? did changing the pod file work you?

Nope. But I changed the approch of implementation. I was using custom code to classify. But now I am using TensorFlowLiteTaskText for Text classification in project like this,

```
pod 'TensorFlowLiteSwift'
pod 'TensorFlowLiteTaskText', '~> 0.0.1-nightly'
```

Tensorflow released TensorFlowLiteTaskText prereleased version.
Check this examples here
[https://github.com/tensorflow/examples/tree/master/lite/examples](url)
I hope this might be useful for you. 
Thanks

**Comment by hieu-le-ts** [comment]
same issue, any solution for this one
