### ISSUE TITLE
TFLite memory not released

### ISSUE THREAD

**Issue by yunchaogong** [tensorflow/tensorflow#44511]
**Describe the current behavior**

I am running a TFLite model on a edge device, and what we have observed is that when we invoke the first time, the RAM usage went up 30-40MB which is correct and that is the right amount of RAM needed to do inference. However, the memory does not get released after that. The second and many more times I run invoke, the overall RAM usage stays the same and there is no leak, but the overall RAM usage never goes down. Is there anything I need to do to release the RAM?

**Comment by yunchaogong** [comment]
Do I need to call `ReleaseNonPersistentMemory` or something like that?

**Comment by Saduf2019** [comment]
@yunchaogong 
Please share simple stand alone code to replicate the issue reported along with the tf version.

**Comment by yunchaogong** [comment]
It is not really an issue. I suspect I might need to explicitly call something to release the memory? Or is it suppose to be like when I execute AllocateTensors() or Invoke(), it just allocates RAM and does not free it and reuse next time?

**Comment by yunchaogong** [comment]
In particular, if I have a stream of infinity number of images coming in, should I have 
```
        std::unique_ptr<tflite::FlatBufferModel> mModel;
        std::unique_ptr<tflite::Interpreter> mInterpreter;
```
These two always allocated as global var, or should I allocate a new Interpreter each time when I see a new image?

**Comment by yunchaogong** [comment]
Updates?

**Comment by jdduke** [comment]
> These two always allocated as global var, or should I allocate a new Interpreter each time when I see a new image?

It depends on how frequently you need to run inference, and how sensitive you are to startup latency. There is a cost to constructing a new interpreter for each inference (often depending on the model size), which you should try measuring. If you destroy the model and interpreter, that will free up the memory, but if loading the model and interpreter is expensive, that may not be a desirable tradeoff, and it's better to keep those objects resident in memory for faster inference.

**Comment by jdduke** [comment]
> ReleaseNonPersistentMemory

This can free up memory, but you'll need to call AllocateTensors() again before you run inference, which again could have a non-trivial cost (which you'll want to measure).

**Comment by NALanhnt2** [comment]
@yunchaogong  i have same problem. did you release memory, how can you do that

**Comment by espbee** [comment]
@NALanhnt2 @yunchaogong did you solve this? I'm encountering it now--
