### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [tensorflow/tensorflow#44525]
The README file in this repo has a bad link - [404:NotFound]

Status code [404:NotFound] - Link: https://chat.stackoverflow.com/rooms/216694/tensorflow

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by mihaimaruseac** [comment]
Let's create a PR to remove the link.

**Comment by Sainithin-bit** [comment]
I removed the dead link but I am not able to merge 
#44757

**Comment by mihaimaruseac** [comment]
It first needs to be approved by a person working at Google. Then there is some CI and if all is green it gets imported inside Google were it waits for a new review round and more CI. If all is good then there is automation that merges it.

Looking at the Pr now.
