### ISSUE TITLE
Tflite model inference bug

### ISSUE THREAD

**Issue by Movisoto** [tensorflow/tensorflow#44529]
**System information**
- Linux Ubuntu 18.04
- TensorFlow installed from source
- TensorFlow version 2.3.0

**Describe the current behavior**
I use the following code to test the model after tflite conversion
```
def test_conversion(model_path):
    # Load TFLite model and allocate tensors.
    interpreter = tf.lite.Interpreter(model_path=model_path)
    interpreter.allocate_tensors()

    # Get input and output tensors.
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    input_shape = input_details[0]['shape']
    input_data = np.array(np.random.random_sample(input_shape), dtype=np.float64)
    interpreter.set_tensor(input_details[0]['index'], input_data)  # <- ValueError: Cannot set tensor: Got value of type NOTYPE but expected type FLOAT64 for input 0, name: input_1 

    interpreter.invoke()

    output_data = interpreter.get_tensor(output_details[0]['index'])
    print(output_data)
```

While I print input_details I get the following:
`[{'name': 'input_1', 'index': 0, 'shape': array([ 64, 224, 224,   3], dtype=int32), 'shape_signature': array([ 64, 224, 224,   3], dtype=int32), 'dtype': <class 'numpy.float64'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]`

Despite the fact, that the input_data dtype matches with expected type (np.float64) I still get the following error:
```
Traceback (most recent call last):
  File "test_tflite.py", line 55, in <module>
    main()
  File "test_tflite.py", line 51, in main
    test_conversion(input_data)
  File "test_tflite.py", line 30, in test_conversion
    interpreter.set_tensor(input_details[0]['index'], input_data)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter.py", line 407, in set_tensor
    self._interpreter.SetTensor(tensor_index, value)
ValueError: Cannot set tensor: Got value of type NOTYPE but expected type FLOAT64 for input 0, name: input_1 
```

**Comment by Saduf2019** [comment]
@Movisoto 
I ran the code shared and do not see any errors or output on tf-nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/0de7372b3b45b17b2f1363698b98f1da/untitled458.ipynb).

**Comment by pearcemc** [comment]
I ran into a very similar issue under tf 2.4.1. Workflow is fine for float32, but float64 raises this error described:

https://colab.research.google.com/drive/1yS1bSIG_ygL4_vhXhjnMyqrvJf57cxYU?usp=sharing
