### ISSUE TITLE
LocallyConnected1D layer description

### ISSUE THREAD

**Issue by rschumi0** [tensorflow/tensorflow#44528]
The documentation of the [LocallyConnected1D layer](https://www.tensorflow.org/api_docs/python/tf/keras/layers/LocallyConnected1D) mentions the following for the strides argument: "Specifying any stride value != 1 is incompatible with specifying any dilation_rate value != 1." 

I assume this sentence was just copied from the Conv1D layer and should be removed since there is no dilation_rate argument for the LocallyConnected1D layer?

**Comment by ravikyram** [comment]
I am closing this issue as the associated PR got merged. Thanks!
