### ISSUE TITLE
Remove state_ops.variable_op()?

### ISSUE THREAD

**Issue by DjangoPeng** [tensorflow/tensorflow#4453]
I'm reading the source code, and I find there is a comment saying that 
`# TODO(mrry): Move this to where it is used, so we can get rid of this op wrapper?`
in the [state_ops.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/state_ops.py#L151)

So, I searched and found that only `variables.py` calls it twice times [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/variables.py#L305), and [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/variables.py#L322).

BTW, some `xx_test.py` also call it, but I think it's easy to change. 
In a word, could I handle the issue and update all the files?@mrry 

I output the file list which call the `variable_op()`:

```
Variables.py
Variables_test.py
Variable_ops_test.py
Tensor_util_test.py
Moving_averages_test.py
Learning_rate_decay_test.py
Graph_util_test.py
Control_flow_ops_py_test.py
```

**Comment by mrry** [comment]
I think the problem with this particular function is that it's used at various places in the internal Google codebase, which makes it difficult to remove in the open-source version.

@drpngx is currently working on tightening our Python API, so I'll assign this issue to him.

**Comment by drpngx** [comment]
Thanks for volunteering!
Yes, there is some internal usage. I don't think it's too bad but it will require manual work. Give me a few days to assess the damage.

**Comment by DjangoPeng** [comment]
@drpngx Sounds good~

**Comment by drpngx** [comment]
Sorry for the delay. I have verified that it's possible to do these changes internally, but some might be higher risk. Feel free to remove use to that interface within the code, but leave out the definition.

**Comment by DjangoPeng** [comment]
@drpngx Ok, I'm on it.

**Comment by DjangoPeng** [comment]
Fixed, close.
