### ISSUE TITLE
Can't reproduce the same result: tensorflow/tensorflow/lite/micro/examples/person_detection_experimental/ model.

### ISSUE THREAD

**Issue by bhavikapanara** [tensorflow/tensorflow#44536]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18
- TensorFlow installed from (source or binary): binary
- Tensorflow version (commit SHA if source): 1.14
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Arduino Nano 33

**Describe the problem**
I am trying to reproduce the same result for a [person detection](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/person_detection_experimental) by following all instruction in this [readme](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/person_detection_experimental/training_a_model.md) doc successfully. But, I can't get the expected result. 

Here is the output of the serial monitor:

```
Starting capture
Image captured
Reading 3080 bytes from ArduCAM
Finished reading
Decoding JPEG and converting to greyscale
Image decoded and processed
Person score: -1 No person score: 1

```
For all capture frame, the model gives the same output` Person score: -1 No person score: 1` even there is a person on a frame.

Please help to resolve this issue.

Thanks
Bhavika

**Please provide the exact sequence of commands/steps when you ran into the problem**

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
