### ISSUE TITLE
Colab feature_columns.ipynb cannot save and reload Keras model

### ISSUE THREAD

**Issue by Silb78dg** [tensorflow/tensorflow#44533]
[Gist issue](https://colab.research.google.com/gist/Silb78dg/ec40d3472e6b67ad399c24320d671973/feature_columns.ipynb#scrollTo=RHNfDYLRv8o_) from [Colab feature_columns.ipynb](https://www.tensorflow.org/tutorials/structured_data/feature_columns)

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
```
2020-11-03 01:52:53.863478: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
v2.3.0-0-gb36436b087 2.3.0
```

**Describe the current behavior**
Cannot reload a model saved in keras format
```
ValueError: You are trying to load a weight file containing 4 layers into a model with 0 layers.
```

**Describe the expected behavior**
Being able to reload the previously saved model

**Standalone code to reproduce the issue**
[gist](https://colab.research.google.com/gist/Silb78dg/ec40d3472e6b67ad399c24320d671973/feature_columns.ipynb#scrollTo=RHNfDYLRv8o_)
Steps:

1. Run [Colab feature_columns.ipynb](https://www.tensorflow.org/tutorials/structured_data/feature_columns)
2. Add one cell
```
model.save('pet_finder.h5', include_optimizer=False)
reload_keras_model = tf.keras.models.load_model('pet_finder.h5')
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-75-876b76fb8d70> in <module>()
      1 model.save('pet_finder.h5', include_optimizer=False)
----> 2 reload_keras_model = tf.keras.models.load_model('pet_finder.h5')
      3 loss, accuracy = reload_keras_model.evaluate(test_ds)
      4 print("Accuracy", accuracy)

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py in load_weights_from_hdf5_group(f, layers)
    684                      'containing ' + str(len(layer_names)) +
    685                      ' layers into a model with ' + str(len(filtered_layers)) +
--> 686                      ' layers.')
    687 
    688   # We batch weight value assignments in a single backend call

ValueError: You are trying to load a weight file containing 4 layers into a model with 0 layers.
```

Thank you.

**Comment by Saduf2019** [comment]
@Silb78dg 
Please share the tf version used

**Comment by Silb78dg** [comment]
It's in the description 
```
2020-11-03 01:52:53.863478: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
v2.3.0-0-gb36436b087 2.3.0
```
tf `2.3.0`. That the version in Colab.
I can also reproduce locally with tf version `2.3.1`.

Thank you.

**Comment by Saduf2019** [comment]
@Silb78dg 
Please share a simple stand alone code such that we can replicate the issue faced or if possible share a colab gist with the issue reported.

**Comment by Silb78dg** [comment]
@Saduf2019 Don't you have access to the gist I already shared?

**Comment by Saduf2019** [comment]
@Silb78dg
We ask for simple stand alone code such that we can replicate the issue faced, or if possible share a gist with the code and the error reported.

**Comment by Silb78dg** [comment]
@Saduf2019 I don't understand.
Have you ever read the description? 
I have provided the gist link **twice**!
Can you please tell me if you have access to the link I provided in the first line of the description (the gist's link not the colab's link)?

Just in case, I can provided again: [https://colab.research.google.com/gist/Silb78dg/ec40d3472e6b67ad399c24320d671973/feature_columns.ipynb](https://colab.research.google.com/gist/Silb78dg/ec40d3472e6b67ad399c24320d671973/feature_columns.ipynb)

What can be better than a bug reproduced using a tutorial? If we don't make the tutorial working properly, that is a really poor user experience.

**Comment by Saduf2019** [comment]
@ymodak 
I am able to replicate the error reported, Please find the [gist here](https://colab.research.google.com/gist/Saduf2019/9b5180b668f786b8ae929bf88d897154/untitled477.ipynb).

**Comment by ymodak** [comment]
Saving your model in default `tf` format  and loading is successful.
```python
model.save('pet_finder', include_optimizer=False)
reload_keras_model = tf.keras.models.load_model('pet_finder')
```
