### ISSUE TITLE
tensorflow/go@v2.3.1: but does not contain package go/core/protobuf/for_core_protos_go_proto

### ISSUE THREAD

**Issue by bool64-llc** [tensorflow/tensorflow#44539]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```sh
Step 21/27 : RUN $go test github.com/tensorflow/tensorflow/tensorflow/go
 ---> Running in b85702eb3116
go: finding github.com/tensorflow/tensorflow v2.3.1+incompatible
go: downloading github.com/tensorflow/tensorflow v2.3.1+incompatible
go: extracting github.com/tensorflow/tensorflow v2.3.1+incompatible
/go/go/packages/pkg/mod/github.com/tensorflow/tensorflow@v2.3.1+incompatible/tensorflow/go/saved_model.go:24:2: cannot find package
/go/go/packages/pkg/mod/github.com/tensorflow/tensorflow@v2.3.1+incompatible/tensorflow/go/saved_model.go:25:2: module github.com/tensorflow/tensorflow@latest found (v2.3.1+incompatible), but does not contain package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto
```

**Comment by rts-rob** [comment]
Also v2.4.0+incompatible

```
/go/pkg/mod/github.com/tensorflow/tensorflow@v2.4.0+incompatible/tensorflow/go/saved_model.go:25:2: module github.com/tensorflow/tensorflow@latest found (v2.4.0+incompatible), but does not contain package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto
```

**Comment by Virgil-N** [comment]
I also have this problem.

**Comment by nickjwhite** [comment]
This looks like a duplicate of #43847.

Issue is still present with v2.5.0-rc0+incompatible.

  ../../../go/pkg/mod/github.com/tensorflow/tensorflow@v2.5.0-rc0+incompatible/tensorflow/go/saved_model.go:25:2: module github.com/tensorflow/tensorflow@latest found (v2.4.1+incompatible), but does not contain package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto

I'm trying to find some version that does work. Between this bug and bugs #35133 and #34580 it's really hard to find any actually working combination of versions. Not a great first impression.

**Comment by kevin2018pg** [comment]
Having the same problem

**Comment by mihaimaruseac** [comment]
Also, we currently don't have any person with Go expertise left in the team, so we'd probably need to separate the go bindings to a separate repository and give full control to community to fix these.

**Comment by sidingli** [comment]
I also have this problem on version 2.7.0

**Comment by juancrescente** [comment]
> Also, we currently don't have any person with Go expertise left in the team, so we'd probably need to separate the go bindings to a separate repository and give full control to community to fix these.

are you going to do this soon? @mihaimaruseac

**Comment by mihaimaruseac** [comment]
This stalled at the moment as we;re trying to find a best way for steering non-python language bindings.

**Comment by SuryanarayanaY** [comment]
Hi,

The TensorFlow team is not currently maintaning the Documentation for installing the Go bindings for TensorFlow.

The instructions has been maintained by the third party contributor: @wamuir

Please follow this [source](https://github.com/tensorflow/build/tree/master/golang_install_guide) by @wamuir for the installation of Golang with Tensorflow.

Thanks!
