### ISSUE TITLE
tfp.stats.histogram does not print out that it has no gradients

### ISSUE THREAD

**Issue by isaacgerg** [tensorflow/tensorflow#44535]
tfp.stats.histogram does not print out that it has no gradients.  I would expect there would be a message indicating gradients aren't flowing like when you use tf.round().

Verified no gradients via

```
x = tf.Variable([1,2,3,4,5,6,7,8])
with tf.GradientTape() as tape:
    tmp = tfp.stats.histogram(x, [0,10])
grad = tape.gradient(tmp, x)
grad is None
```

**Comment by amahendrakar** [comment]
@isaacgerg,
On running the code with TF v2.3 and TF-nightly, `grad is None` returns `True`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/2dcf867b0e18a620d001b6c3b0f5c179/44535.ipynb#scrollTo=gzgSd3M5szzo). 

Could you please confirm if this is the issue you're facing? Thanks!

**Comment by isaacgerg** [comment]
@amahendrakar   Yes that is what i also see.  When you do the same thing with tf.round, it prints a warning saying that none of the gradients are flowing down to earlier layers. I would think histogram should do the same thing.

**Comment by ccrusius** [comment]
This seems to be the wrong repository for this bug - could you file it in TFP? (https://github.com/tensorflow/probability/issues)
