### ISSUE TITLE
Keras: custom data validation callback on training data always returns validation data results

### ISSUE THREAD

**Issue by oXwvdrbbj8S4wo9k8lSN** [tensorflow/tensorflow#44545]
Just for information: I already asked for help regarding this problem on [stackoverflow](https://stackoverflow.com/questions/64645579/keras-custom-data-validation-callback-on-training-data-always-returns-validatio). Since I did not get an answer yet, I assume that this is a non-trivial problem and therefore open an issue here.

**System information**
`python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"` returned
v2.3.0-54-gfcc4b966f1 2.3.1

**Describe the current behavior**
When calling model.evaluate on training data (or any other data set) within a callback, always the results of the validation data set are returned. 

**Describe the expected behavior**
I expected to get results for the data set passed to model.evaluate - no matter if called from within a callback or not.

**Standalone code to reproduce the issue**
I created a notebook that shows the problem:
https://colab.research.google.com/drive/1H-3ULqyRZCpaasXpU1foLkEg12fYNkYK?usp=sharing

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported,please find the [gist here](https://colab.research.google.com/gist/Saduf2019/34c1ed837a6ba2a1e704799f4fe146a9/untitled458.ipynb).

**Comment by jvishnuvardhan** [comment]
@oXwvdrbbj8S4wo9k8lSN May be I am missing something. I checked your colab. Data looks different and the results (losses) are also different as expected. Can you please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/cdb65957379a264c3121b2543595a5da/untitled458.ipynb) where I printed different datasets and results. Thanks!

**Comment by oXwvdrbbj8S4wo9k8lSN** [comment]
@jvishnuvardhan I do not totally get the concept of gists. Therefore, please excuse if I state the obvious. 
Between the colab notebook and the gist, something in the behavior of Keras/Tensorflow changed. In my notebook (with tensorflow version 2.3.0), the output of the history is 
```
{'custom_loss': [0.7624925374984741, 0.5331208109855652],
 'loss': [0.9665887951850891, 0.6637843251228333],
 'val_loss': [0.7624925374984741, 0.5331208109855652]}
```
Here, the results for *custom_loss* and *val_loss* are the same although they should differ since the inputs differ. In the gist (currently tensorflow version 2.5.0-dev20201104), however, the output is 
```
{'custom_loss': [0.7694963216781616, 0.541864812374115],
 'loss': [0.9665887951850891, 0.6637843251228333],
 'val_loss': [0.7624925374984741, 0.5331208109855652]}
```
Here, the outputs differ, which is the behavior I expected. I tested different versions of tensorflow and it seems that the change happened between version 2.3.1 and version 2.4.0rc0. Therefore, I guess that it is actually a bug but you already fixed it at least in the development versions.

**Comment by oXwvdrbbj8S4wo9k8lSN** [comment]
@jvishnuvardhan I tested version 2.2.1 and also with this version, the outputs differ (as expected). It seems that the problem exists only in versions 2.3.0 and 2.3.1.

**Comment by jvishnuvardhan** [comment]
@oXwvdrbbj8S4wo9k8lSN May be there was a bug in `TF2.3` but I just checked with most recent `tf-nightly` and `!pip install tensorflow==2.4.0rc0` and both showed different results for `custom_loss` and `val_loss`.

Please use recent TF versions. In near future there will be stable `TF2.4` which works better than `TF2.3`.

I am closing this issue as this was resolved in recent versions. If you see the same issue with recent version, feel free to reopen the issue. Thanks!
