### ISSUE TITLE
RuntimeError: tensorflow/lite/kernels/conv.cc:238 input->dims->data[3] != filter->dims->data[3] (32 != 1)Node number 1 (CONV_2D) failed to prepare.

### ISSUE THREAD

**Issue by SangbumChoi** [tensorflow/tensorflow#44548]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):
Ubuntu 16.04
TensorFlow version 2.3.1

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
# Copy and paste here the exact command
```

**The output from the converter invocation**

```
# Copy and paste the output here.
```

**Also, please include a link to the saved model or GraphDef**

model
https://drive.google.com/file/d/1KKDE7RwQ8qVXm4AdFnoYCadcQuI1x4O2/view?usp=sharing

tflite
https://drive.google.com/file/d/1mB557Fg5eh86Hhr8GSxWzVe7rufuNq87/view?usp=sharing

h5 file
https://drive.google.com/file/d/1xvMLkTO6jlsBIHEj8LSMOIHI51FuNyqI/view?usp=sharing

```
# Put link here or attach to the issue.
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

2020-11-03 20:43:17.312502: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-11-03 20:43:17.312653: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "C:/Users/daniel/PycharmProjects/MobileNeXt-3DMPPE-Extra-Experiment/tflite/check_tflite.py", line 5, in <module>
    interpreter.allocate_tensors()
  File "C:\Users\daniel\Anaconda3\envs\3DMPPE_POSENET_RELEASE-master\lib\site-packages\tensorflow_core\lite\python\interpreter.py", line 244, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "C:\Users\daniel\Anaconda3\envs\3DMPPE_POSENET_RELEASE-master\lib\site-packages\tensorflow_core\lite\python\interpreter_wrapper\tensorflow_wrap_interpreter_wrapper.py", line 106, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: tensorflow/lite/kernels/conv.cc:238 input->dims->data[3] != filter->dims->data[3] (32 != 1)Node number 1 (CONV_2D) failed to prepare.

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by SangbumChoi** [comment]
It happens when I try to convert Pytorch model -> Keras model -> TFlite model

**Comment by SangbumChoi** [comment]
I'm not sure it might help but converting into onnx and tensorflow succeed

**Comment by amahendrakar** [comment]
@SangbumChoi,
I am unable to untar the `exp2_mobilenext_headnet_24.pth.tar` file you have shared. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/a30db81e07a49b17d4c0aa6348fceae7/44548.ipynb). 

Could you please share the contents of the file in another format. Also, please share the complete code you have executed to build the model itself. Thanks!

**Comment by SangbumChoi** [comment]
> @SangbumChoi,
> I am unable to untar the `exp2_mobilenext_headnet_24.pth.tar` file you have shared. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/a30db81e07a49b17d4c0aa6348fceae7/44548.ipynb).
> 
> Could you please share the contents of the file in another format. Also, please share the complete code you have executed to build the model itself. Thanks!

another pth.tar
https://drive.google.com/file/d/1Dl5zC29g03UWc_Pb5alO1SgVgz25fUf7/view?usp=sharing

basline
https://drive.google.com/drive/folders/1HP-_4ggQDjmoRnIYj4msonVWRWwsJJGE?usp=sharing

two models are slightly different but i think it might regenerate the error

I'm not sure if this might can extract properly.

**Comment by SangbumChoi** [comment]
Also this model is generated with torch.nn.parallel.DataParallel so i load with 
this kind of step

args = parse_args()

print("load keras model for MobileNeXt")
keras_model = ResPoseNet_Tensorflow((256, 256, 3), args.joint)

#Lucky for us, PyTorch includes a predefined Squeezenet
print("load pytorch model for MobileNeXt")
pytorch_model = get_pose_net(args.backbone, args.frontbone, False, args.joint)
pytorch_model = DataParallel(pytorch_model).cuda()

#Load the pretrained model
pytorch_model.load_state_dict(torch.load(args.modelpath)['network'])

#Time to transfer weights
single_pytorch_model = pytorch_model.module
converter = PytorchToKeras(pytorch_model, keras_model)
converter.convert((3,256,256))

#Save the weights of the converted keras model for later use
converter.save_weights("../output/baseline.h5")
converter.save_model("../output/baseline")

**Comment by SangbumChoi** [comment]
However by using onnx @amahendrakar it succeed but still have problem with 

java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference

Node number 3 (FlexAddV2) failed to prepare.

FlexAddV2

**Comment by amahendrakar** [comment]
> java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference

@SangbumChoi,
Looking at issue [#41558](https://github.com/tensorflow/tensorflow/issues/41558) with a similar error, seems like the issue was resolved with the latest TF-nightly. 

Could you please check if you are facing the same issue with the latest TF-nightly as well? Thanks!

**Comment by SangbumChoi** [comment]
> > java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference
> 
> @SangbumChoi,
> Looking at issue [#41558](https://github.com/tensorflow/tensorflow/issues/41558) with a similar error, seems like the issue was resolved with the latest TF-nightly.
> 
> Could you please check if you are facing the same issue with the latest TF-nightly as well? Thanks!

I will try it but can you explain how to enable using TF-nightly in Android Studio? (because it is built for mobile devices)

**Comment by SangbumChoi** [comment]
> > java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference
> 
> @SangbumChoi,
> Looking at issue [#41558](https://github.com/tensorflow/tensorflow/issues/41558) with a similar error, seems like the issue was resolved with the latest TF-nightly.
> 
> Could you please check if you are facing the same issue with the latest TF-nightly as well? Thanks!

Hi, when I use tf.version with 2.5.0-dev20201116
it successfully build with

INFO: Created TensorFlow Lite delegate for select TF ops.
2020-11-17 22:53:40.493786: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-11-17 22:53:40.496937: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-11-17 22:53:40.497171: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2020-11-17 22:53:40.505254: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-4DSFS8C
2020-11-17 22:53:40.505730: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-4DSFS8C
2020-11-17 22:53:40.505847: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
INFO: TfLiteFlexDelegate delegate: 2 nodes delegated out of 17443 nodes with 1 partitions.

input_details :  [{'name': 'input', 'index': 0, 'shape': array([  1,   3, 256, 256]), 'shape_signature': array([  1,   3, 256, 256]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
output_details :  [{'name': 'Identity', 'index': 51481, 'shape': array([ 1, 18,  3]), 'shape_signature': array([ 1, 18,  3]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
(1, 18, 3)

However, as I mentioned how to use tf-nightly in android studio?

**Comment by SangbumChoi** [comment]
@amahendrakar just adding     
implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly'
successfully build I will close this! Thanks
