### ISSUE TITLE
unable to trace dense layer in GNN

### ISSUE THREAD

**Issue by junhyk** [tensorflow/tensorflow#44541]
**Describe the current behavior**
Hi,
I'm trying to implement GNN using tensorflow and export it to TFlite.
My implementation is largely inspired from pytorch_geometric.

After training my model I found tensorflow is not tracing my model's execution appropriately
The message was below.
```
WARNING:absl:Found untraced functions such as dense_layer_call_and_return_conditional_losses, dense_layer_call_fn, dense_1_layer_call_and_return_conditional_losses, dense_1_layer_call_fn, dense_layer_call_fn while saving (showing 5 of 10). These functions will not be directly callable after loading.
WARNING:absl:Found untraced functions such as dense_layer_call_and_return_conditional_losses, dense_layer_call_fn, dense_1_layer_call_and_return_conditional_losses, dense_1_layer_call_fn, dense_layer_call_fn while saving (showing 5 of 10). These functions will not be directly callable after loading.
```

My model consists of 2 graph convolutional layers and each layer computes dense layer and then some kind of scatter & gather operation.
**Describe the expected behavior**
I want tensorflow to trace my model's execution properly, so that I can painlessly export my model to tflite and execute it.

**Standalone code to reproduce the issue**
Below gist is simplified version of my code.
It is a bit long but I couldn't simplify it more to reproduce my error. sorry
https://colab.research.google.com/gist/junhyk/3744c6f54074a20b4972eada113aa76d/untitled1.ipynb

**Comment by amahendrakar** [comment]
@junhyk,
In spite of the warnings, I was able to convert the model to tflite format without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/8cde728ac94bc76eaa70ef802132a397/44541-tf-nightly.ipynb). Thanks!

**Comment by Liu-Da** [comment]
Same problem in tf2.4. tf2.3 is fine.

**Comment by amahendrakar** [comment]
@Liu-Da,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by arthurserres** [comment]
Same issue with tf24, I can't test on tf23 cause I'm on arm apple chips

**Comment by amahendrakar** [comment]
@arthurserres,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by zndr27** [comment]
I have a similar issue. I was trying to save a custom model using tensorflow nighty 2.4 because I have an rtx 3080 (can't use the stable version). Tried saving the custom model on another computer with tensorflow 2.2 and I did not get these warnings when I saved. I agree that the issue is likely with tensorflow 2.4.

**Comment by hoondy** [comment]
I have the same issue after upgrading tf 2.4 from tf 2.2.

**Comment by amahendrakar** [comment]
@hoondy, @zndr27,
Could y'all please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by DanBmh** [comment]
Have the same issue with tf2.4.
Inheriting from `Model` instead of `Layer` for custom layer subclassing did greatly reduce the warnings. Now I only have the warnings for LSTM, like in https://github.com/tensorflow/tensorflow/issues/47554
