### ISSUE TITLE
Second derivative of reduce_prod returns NaN

### ISSUE THREAD

**Issue by swertz** [tensorflow/tensorflow#44556]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): binary (pip)
- TensorFlow version (use command below): v2.3.0-54-gfcc4b966f1 2.3.1
- Python version: 3.8.5
- CUDA/cuDNN version: executing on CPU
- GPU model and memory: executing on CPU

**Describe the current behavior**

Computing the second derivative of a function containing `tf.reduce_prod`, where one of the arguments is zero, returns NaN.

**Describe the expected behavior**

The second derivative should be finite in those cases.

**Standalone code to reproduce the issue**

```
def grad(f):
    x = tf.Variable([0.])
    with tf.GradientTape() as t:
        y = f(x)
    g = t.gradient(y, x)
    return g

def grad2(f): 
    x = tf.Variable([0.])
    with tf.GradientTape() as t2:
        with tf.GradientTape() as t1:
             y = f(x)
        g = t1.gradient(y, x)
    g2 = t2.jacobian(g, x)
    return g2

grad(lambda x: tf.reduce_prod(tf.constant([2.,0.])*x*x)) # returns 0 as expected
grad2(lambda x: tf.reduce_prod(tf.constant([2.,0.])*x*x)) # returns NaN
grad2(lambda x: 2.*x*x) # returns 4 as expected
```

**Comment by Saduf2019** [comment]
@swertz 
I ran the code shared and face a different issue, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/c7429b868d443d188c6d029122e8ca89/untitled458.ipynb). Please share a colab gist with the error reported.

**Comment by swertz** [comment]
I could reproduce in colab with v2.3.0, please find it [here](https://colab.research.google.com/drive/1Nm-KoLV1ZDRTS6NarXgMNjcEQJumjMbH?usp=sharing).

**Comment by Saduf2019** [comment]
@swertz 
I do not have access to the above link.

**Comment by swertz** [comment]
> @swertz
> I do not have access to the above link.

Sorry! Should be fine now...

**Comment by Saduf2019** [comment]
@swertz 
I ran the code and this had been fixed in nightly version, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/7a30d232977727a555780404b15d0d4c/untitled458.ipynb).

**Comment by swertz** [comment]
Great, thanks!
