### ISSUE TITLE
tf.keras.model fit() CUDA crash when using generator inputs

### ISSUE THREAD

**Issue by raymanfx** [tensorflow/tensorflow#44553]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: Yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Fedora 33
-   **TensorFlow installed from (source or binary)**: pip3.7 (binary)
-   **TensorFlow version (use command below)**: v2.3.0-54-gfcc4b966f1 2.3.1
-   **Python version**: 3.7
-   **CUDA/cuDNN version**: 10.1
-   **GPU model and memory**: NVIDIA RTX 2070 Max-Q 8GB
-   **Exact command to reproduce**: See below

### Describe the problem
For academic purposes, I'm trying to preprocess CIFAR10 images before training a keras sequential model. CIFAR10 training/test images are 32x32x3 by default, I want to resize them to 244x244x3. This is not possible with a single `tf.image.resize(..)` call, as it quickly crashes due to OOM. Thus, I am using a generator function to feed the input data to the `model.fit(..)` `x` parameter.

### Source code / logs
Here is my generator function:
```python
def data_generator(images, labels, w, h):
    batch_size = 10

    i = 0
    while i < len(images):
        remaining = len(images) - i
        batch = batch_size
        if batch >= remaining:
            batch = remaining
        print("### generator {}-{} of {}".format(i, i+batch, len(images)))
        image_batch = tf.image.resize(images[i:i+batch], (w, h))
        #image_batch = images[i:i+batch]
        label_batch = labels[i:i+batch]
        i += batch

        yield image_batch, label_batch
```

This is how I load the images:
```python
    # get the CIFAR10 dataset
    (train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()

    # normalize pixel values to be between 0 and 1
    train_images, test_images = train_images / 255.0, test_images / 255.0
```

This is how I train the model:
```python
    train_generator = data_generator(train_images, train_labels, input_shape[0], input_shape[1])
    validation_generator = data_generator(test_images, test_labels, input_shape[0], input_shape[1])
    history = model.fit(x=train_generator, epochs=10,
                        validation_data=validation_generator,
                        use_multiprocessing=True)
```

... and finally, this is the crash message:
```
2020-11-03 14:26:31.048556: F tensorflow/stream_executor/cuda/cuda_driver.cc:219] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error
```

**Comment by raymanfx** [comment]
Update: this is happening because of the `use_multiprocessing=True` parameter. Once that is removed, training starts. Should this still be considered a bug?

**Comment by ymodak** [comment]
For using multiple gpu using [tf.distribute.MirroredStrategy](https://www.tensorflow.org/api_docs/python/tf/distribute/MirroredStrategy) is recommended.

**Comment by raymanfx** [comment]
This is not about using multiple GPUs. My system only has a single CUDA compute executor (the RTX 2070 Max-Q).

**Comment by Saduf2019** [comment]
@raymanfx 
Can you not resize to 224, as the image resolution of 32 is too low for that, and try tf.data instead of generator and let us know.
You may refer to this [example](https://sayak.dev/tf.keras/data_augmentation/image/2020/05/10/augmemtation-recipes.html).

**Comment by raymanfx** [comment]
Initially I tried `tf.image.resize`, but that quickly crashed due to OOM (50.000 images in the dataset). This is why I'm trying to use a generator in the first place - I'd very much like to avoid that.

**Comment by ymodak** [comment]
You may want to try with latest TF version. Similar issue https://github.com/tensorflow/tensorflow/issues/44137 with latest TF version seems to be fixed. Thanks!
