### ISSUE TITLE
Does TensorFlow Micro support self define output type for each layer?

### ISSUE THREAD

**Issue by tiancaitzp** [tensorflow/tensorflow#44551]
@tensorflow/micro

**Describe the problem**
In our project, we want to deploy a CNN model in QualComm sensorhub. We quantize the model firstly, the input of the model is int8 data. But in order to improve inference accuracy, we want to use uint8 data to receive the first convolution layer output and input float data to FullyConnected layer. Therefore, the data type change process is as follow: int8 input -> first conv -> uint8 output -> second conv -> ... last conv -> float output -> fullyconnected. Dose TensorFlow Micro support this?

**Comment by pkgoogle** [comment]
Hi @tiancaitzp, that level of granularity is not yet supported by TFLite, please review the available quantization methods here: https://www.tensorflow.org/lite/performance/model_optimization to see what is supported.
