### ISSUE TITLE
fatal error: tensorflow/core/framework/types.pb.h: No such file or directory

### ISSUE THREAD

**Issue by sairmreddy** [tensorflow/tensorflow#44550]
when i compiling file with CMakeLists.txt file it giving error.
[CMakeLists.txt](https://github.com/tensorflow/tensorflow/files/5481075/CMakeLists.txt)
compiling file : tensorflow/tensorflow/examples/speech_commands/label_wav.cc
tensor flow version is r2.2
my machine is Ubuntu 18.04.5 LTS

error:
[ 50%] Building CXX object CMakeFiles/speech_recog.dir/label_wav.cc.o
In file included from /home/sbojja/Qual-sdm/TF/tensorflow/tensorflow/core/framework/tensor.h:23:0,
                 from /home/sbojja/Qual-sdm/TF/tensorflow/tensorflow/examples/speech_commands/label_wav.cc:19:
/home/sbojja/Qual-sdm/TF/tensorflow/tensorflow/core/framework/tensor_shape.h:22:10: fatal error: tensorflow/core/framework/types.pb.h: No such file or directory
 #include "tensorflow/core/framework/types.pb.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/speech_recog.dir/build.make:62: recipe for target 'CMakeFiles/speech_recog.dir/label_wav.cc.o' failed
make[2]: *** [CMakeFiles/speech_recog.dir/label_wav.cc.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/speech_recog.dir/all' failed
make[1]: *** [CMakeFiles/speech_recog.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Saduf2019** [comment]
@sairmreddy 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

**Comment by sairmreddy** [comment]
steps:
-> sudo apt install python3-dev python3-pip
-> pip install -U --user pip numpy wheel
-> pip install -U --user keras_preprocessing --no-deps
-> git clone https://github.com/tensorflow/tensorflow.git
-> cd tensorflow
-> git checkout r2.2
-> ./configure

You have bazel 2.0.0 installed.
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python3


Found possible Python library paths:
  /usr/lib/python3/dist-packages
  /usr/local/lib/python3.6/dist-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python3/dist-packages]

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: n
Clang will not be downloaded.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]:  


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=ngraph      	# Build with Intel nGraph support.
	--config=numa        	# Build with NUMA support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
	--config=v2          	# Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=noaws       	# Disable AWS S3 filesystem support.
	--config=nogcp       	# Disable GCP support.
	--config=nohdfs      	# Disable HDFS support.
	--config=nonccl      	# Disable NVIDIA NCCL support.
Configuration finished

-> bazel build -c opt tensorflow:libtensorflow_cc.so
-> after this i am run the cmake file.
->cmake .. and make
