### ISSUE TITLE
Enforce single optimized kernel implementation

### ISSUE THREAD

**Issue by advaitjain** [tensorflow/tensorflow#44566]
Currently we can provide potentially multiple optimized kernel implementations via the `TAGS` parameter to the TFLM Makefile.

While this was originally supported, we don't have any use-case for it and are moving towards enforcing a single optimized kernel implementation. This will also reduce some complexity in the makefile and allow for improved debugging.

Corresponding internal issue: http://b/170501366

**Comment by mohantym** [comment]
Hi @advaitjain !
It seems that it has been updated to fixed status in the above buganizer ticket.  Can it be considered as resolved then.
Thank you!
