### ISSUE TITLE
tf-nightly-gpu looking for cusolver64_10.dll on a Cuda 11.1 / cuDNN 8.0.4 RTX3080 Build

### ISSUE THREAD

**Issue by anisoulk** [tensorflow/tensorflow#44567]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution : Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.5.0-dev20201103
- Python version: 3.8.5
- Installed using: pip
- CUDA/cuDNN version: Cuda 11.1 cuDNN 8.0.4
- GPU model and memory: Nvidia RTX 3080

**Describe the problem**
After installing Cuda 11.1 / cuDNN 8.0.4 and tf-nightly-gpu (today's 1132020), I tried to test that tensorflow sees my gpu, but it throws an error saying it 'Could not load dynamic library 'cusolver64_10.dll''

I do have cusolver64_11.dll in my Nvidia bin folder, but for some reason TF is looking for the Cuda 10 version of that one specific file (it found and opened all the other Cuda11 dlls) 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
python
import tensorflow as tf
assert tf.test.is_gpu_available()

**Comment by Saduf2019** [comment]
@anisoulk 
Please refer to these existing issues with same error and let us know:
#44291 #44128 # 44381

**Comment by anisoulk** [comment]
@Saduf2019 Thanks for getting back to me. I did look at the issues you mentioned, the applicable temporary fixes suggested there are: 

1. Revert to Cuda 10.x : I can't do that since I have an RTX3080 GPU card, which is only compatible with Cuda 11.x 
2. The other suggestion floating around is to "rename" the cusolver64_11.dll in my current Cuda11.1/bin folder to cusolver64_10.dll... Are you saying this is the only workaround for this issue?

**Comment by Saduf2019** [comment]
@anisoulk 
Please try them and let us know.

**Comment by anisoulk** [comment]
I did try them, here are the results: 
1. Revert to Cuda 10.x : Not Compatible with my GPU (Nvidia RTX 3080)
2. Changed cusolver64_11.dll to cusolver64_10,dll : This indeed removed the error, however it broke every thing for me, I have all kinds of errors every time I try to train models (models that I know work fine from running them before on tf-cpu)

**Comment by anisoulk** [comment]
@Saduf2019 Any feedback on this ?

**Comment by Ber1** [comment]
I have exactly the same problem, with exactly the same specs:

- OS Platform and Distribution : Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.5.0.dev20201110
- Python version: 3.8.6
- Installed using: pip
- CUDA/cuDNN version: Cuda 11.1 cuDNN 8.0.4
- GPU model and memory: Nvidia RTX 3080

**Comment by aulosea** [comment]
exactly the same problem,with almost the same specs:

tensorflow version: 2.4.0rc1

**Comment by ZekiFayes** [comment]
After changing cusolver64_11.dll to cusolver64_10,dll, some **errors** are thrown as follows.

 ```
 File "C:/Users/User/Desktop/deep-spatial-temporal/deep-spatial-temporal/test_gpu.py", line 67, in <module>
    validation_data=(x_test, y_test))
  File "C:\software\python37\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1103, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\software\python37\lib\site-packages\tensorflow\python\eager\def_function.py", line 784, in __call__
    result = self._call(*args, **kwds)
  File "C:\software\python37\lib\site-packages\tensorflow\python\eager\def_function.py", line 844, in _call
    return self._stateless_fn(*args, **kwds)
  File "C:\software\python37\lib\site-packages\tensorflow\python\eager\function.py", line 2972, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "C:\software\python37\lib\site-packages\tensorflow\python\eager\function.py", line 1948, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "C:\software\python37\lib\site-packages\tensorflow\python\eager\function.py", line 561, in call
    ctx=ctx)
  File "C:\software\python37\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InternalError:  Blas xGEMM launch failed : a.shape=[1,128,4608], b.shape=[1,4608,128], m=128, n=128, k=4608
	 [[node sequential/dense/MatMul (defined at /Users/User/Desktop/deep-spatial-temporal/deep-spatial-temporal/test_gpu.py:67) ]] [Op:__inference_train_function_790]
```

Then I added the following commands, it worked well.

```
gpus = tf.config.experimental.list_physical_devices(device_type='GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
```

### System information

> OS Platform and Distribution : Windows 10
> Tensorflow: tf-nightly-gpu 2.5.0dev20201117
> Python version: 3.7.8
> Installed using: pip
> CUDA/cuDNN version: Cuda 11.1 cuDNN 8.0.5
> GPU model and memory: Nvidia RTX 3080

**Comment by mihaimaruseac** [comment]
@sanjoy @pkanwar23

**Comment by sanjoy** [comment]
Can you please try with CUDA 11.0?  TF 2.4 (and nightly) is built and tested against CUDA 11.0, not 11.1.

**Comment by aulosea** [comment]
> After changing cusolver64_11.dll to cusolver64_10,dll, some **errors** are thrown as follows.
> 
> ```
> File "C:/Users/User/Desktop/deep-spatial-temporal/deep-spatial-temporal/test_gpu.py", line 67, in <module>
>    validation_data=(x_test, y_test))
>  File "C:\software\python37\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1103, in fit
>    tmp_logs = self.train_function(iterator)
>  File "C:\software\python37\lib\site-packages\tensorflow\python\eager\def_function.py", line 784, in __call__
>    result = self._call(*args, **kwds)
>  File "C:\software\python37\lib\site-packages\tensorflow\python\eager\def_function.py", line 844, in _call
>    return self._stateless_fn(*args, **kwds)
>  File "C:\software\python37\lib\site-packages\tensorflow\python\eager\function.py", line 2972, in __call__
>    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
>  File "C:\software\python37\lib\site-packages\tensorflow\python\eager\function.py", line 1948, in _call_flat
>    ctx, args, cancellation_manager=cancellation_manager))
>  File "C:\software\python37\lib\site-packages\tensorflow\python\eager\function.py", line 561, in call
>    ctx=ctx)
>  File "C:\software\python37\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
>    inputs, attrs, num_outputs)
> tensorflow.python.framework.errors_impl.InternalError:  Blas xGEMM launch failed : a.shape=[1,128,4608], b.shape=[1,4608,128], m=128, n=128, k=4608
>     [[node sequential/dense/MatMul (defined at /Users/User/Desktop/deep-spatial-temporal/deep-spatial-temporal/test_gpu.py:67) ]] [Op:__inference_train_function_790]
> ```
> 
> Then I added the following commands, it worked well.
> 
> ```
> gpus = tf.config.experimental.list_physical_devices(device_type='GPU')
> for gpu in gpus:
>     tf.config.experimental.set_memory_growth(gpu, True)
> ```
> 
> ### System information
> > OS Platform and Distribution : Windows 10
> > Tensorflow: tf-nightly-gpu 2.5.0dev20201117
> > Python version: 3.7.8
> > Installed using: pip
> > CUDA/cuDNN version: Cuda 11.1 cuDNN 8.0.5
> > GPU model and memory: Nvidia RTX 3080

Thank u! It works!

**Comment by anisoulk** [comment]
> Can you please try with CUDA 11.0? TF 2.4 (and nightly) is built and tested against CUDA 11.0, not 11.1.

@sanjoy Thanks for the feedback, reverting back to CUDA 11.0 removed the error and GPU is now working. However something weird caught my eye: Training on GPU is considerably slower (3x slower) than on CPU, granted I'm not training a big network (5 layers NN) but still 3 times slower is odd, is this normal ? or is this some incompatibility issue ?

**Comment by pkanwar23** [comment]
3x slower is odd. We haven't seen this in our internal tests. You might want to use the profiling tools to see where the bottleneck lies.  (https://www.tensorflow.org/guide/profiler).

I'm going to close the issue for now. If you're able identify specific Ops that are slower, or some other bottleneck, you can open another issue.  We'll be happy to look at it.

**Comment by AlexRodis** [comment]
@anisoulk 
I had the exact same issue and the fix worked. In regards to the performance drop, I also had the same problem. I tried increasing the complexity of the model as follows: 150, 300, 2000, 6600. I noticed the GPU began outperforming the CPU and remained roughly constant despite the increasing units. It's possible the bottleneck is in the transfer to the GPU, in which case for smaller models the CPU would outperform it as you described.

**Comment by HAvOcLiu** [comment]
Same issue with tf 2.4 and CUDA11.1 CuDNN8.0.5 on GTX1660Ti. I download that cusolver64_10.dll from [https://drive.google.com/uc?id=1-3Yk-QZ1eUta1T40BaxFpO4uyn7BPU4o&export=download](url) and put it in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin. Then it works well.
