### ISSUE TITLE
Dataset.from_tensor_slices regression?

### ISSUE THREAD

**Issue by OmriShiv** [tensorflow/tensorflow#44573]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS 10.15.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0, 2.2, and 2.3.0
- Python version: 3.6, 3.7, 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

v2.2.0-rc4-8-g2b96f3662b 2.2.0

**Describe the current behavior**
I'm supporting someone trying to build a model. In Tensorflow 2.1.0, the code below works correctly. In version 2.2.0+, the last line fails. I am wondering if there is a regression or if there is a fix and 2.1.0 shouldn't have worked. 
**Describe the expected behavior**
I expect the dataset to be created correctly. 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
import tensorflow as tf
import pandas as pd
import numpy as np


data = [
    [
        np.array(['k1', '', '']), np.array(['t1', 't2', 't3']), np.array([.03, .02, .03])
    ],
    [
        np.array(['k1', 'k2', 'k3']), np.array(['t4', 't5', 't6']), np.array([.03, .02, .03])
    ]
]
train = pd.DataFrame(data, columns=['kwd', 'title', 'labels'])
feature_cols = ['kwd', 'title']
labels = train.pop('labels')
features = {
    col: train[col] for col in feature_cols
}
batch = tf.data.Dataset.from_tensor_slices((features, labels))

```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
Traceback (most recent call last):
  File "/array_example.py", line 17, in <module>
    batch = tf.data.Dataset.from_tensor_slices((train, labels))
  File "/Users/oshiv/miniconda3/envs/py37tf22/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 640, in from_tensor_slices
    return TensorSliceDataset(tensors)
  File "/Users/oshiv/miniconda3/envs/py37tf22/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2858, in __init__
    element = structure.normalize_element(element)
  File "/Users/oshiv/miniconda3/envs/py37tf22/lib/python3.7/site-packages/tensorflow/python/data/util/structure.py", line 98, in normalize_element
    ops.convert_to_tensor(t, name="component_%d" % i))
  File "/Users/oshiv/miniconda3/envs/py37tf22/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1341, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/oshiv/miniconda3/envs/py37tf22/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 321, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/oshiv/miniconda3/envs/py37tf22/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 262, in constant
    allow_broadcast=True)
  File "/Users/oshiv/miniconda3/envs/py37tf22/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 270, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/Users/oshiv/miniconda3/envs/py37tf22/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 96, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type numpy.ndarray).
```

**Comment by Saduf2019** [comment]
@ymodak 
I am able to replicate the issue reported on tf 2.3 and nightly,please find the [gist here](https://colab.research.google.com/gist/Saduf2019/7f891dd203cffa4b613465fc055ec349/untitled458.ipynb#scrollTo=EV_xdzblRs5F).

**Comment by aaudiber** [comment]
Hi @OmriShiv,

`Dataset.from_tensor_slices` uses generic TensorFlow machinery to convert its inputs into tensors. It should be able to convert anything that can be passed to `tf.constant`. 

To make `from_tensor_slices` work with DataFrames, convert the DataFrames to lists first:
```python
batch = tf.data.Dataset.from_tensor_slices((list(features), list(labels)))
```

**Comment by OmriShiv** [comment]
@aaudiber Let me take a look and see if I can make this work. I'm getting some dimension issues right now.

My question is more: why this works in 2.1, but not in 2.2+

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210530, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/b3678f4c3f0837d74791e0e20fc53fb2/44573.ipynb). Thanks!

**Comment by aaudiber** [comment]
This issue isn't specific to `from_tensor_slices` -- the same error will be raised by trying to create a TF constant using a `pandas.core.series.Series`.
