### ISSUE TITLE
tf.data.dataset.batch returns different shape depending on drop_remainder parameter

### ISSUE THREAD

**Issue by botasb** [tensorflow/tensorflow#44578]
Hi,
I notice that when drop_reminder is not set in tf.data.dataset.batch , the dataset returned as None shape, but if drop_reminder is set, the batch_size is set as the shape of the returned dataset:

**With drop_remainder=False:**

`train_ds = train_ds.batch(32) 

print(train_ds) 

_<BatchDataset shapes: ({age: (None,), sex: (None,), cp: (None,), trestbps: (None,), chol: (None,), fbs: (None,), restecg: (None,), thalach: (None,), exang: (None,), oldpeak: (None,), slope: (None,), ca: (None,), thal: (None,)}, (None,)), types: ({age: tf.int64, sex: tf.int64, cp: tf.int64, trestbps: tf.int64, chol: tf.int64, fbs: tf.int64, restecg: tf.int64, thalach: tf.int64, exang: tf.int64, oldpeak: tf.float64, slope: tf.int64, ca: tf.int64, thal: tf.string}, tf.int64)>_`

**With drop_remainder=True,** 

`train_ds = train_ds.batch(32, drop_remainder=True)

print(train_ds)

<BatchDataset shapes: ({age: (32,), sex: (32,), cp: (32,), trestbps: (32,), chol: (32,), fbs: (32,), restecg: (32,), thalach: (32,), exang: (32,), oldpeak: (32,), slope: (32,), ca: (32,), thal: (32,)}, (32,)), types: ({age: tf.int64, sex: tf.int64, cp: tf.int64, trestbps: tf.int64, chol: tf.int64, fbs: tf.int64, restecg: tf.int64, thalach: tf.int64, exang: tf.int64, oldpeak: tf.float64, slope: tf.int64, ca: tf.int64, thal: tf.string}, tf.int64)>`

Is this the expected behaviour?

**Comment by mkuchnik** [comment]
`dropped remainder` forces the batch size to be constant. If it is not enabled, then the last minibatch will possibly be smaller than the batch size, thus the batch size is not a constant, and thus the shape cannot be determined statically (what you are seeing).

Imagine a dataset with 33 elements. If you batch with batch_size 32, then the minibatch sizes are 32 and 1. Drop remainder simply discards the smaller minibatch to fix this edge case, which only leaves the first minibatch of size 32.

**Comment by ravikyram** [comment]
@botasb 

Please, go through this [tutorial](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#batch) and see if it helps you. Thanks!
