### ISSUE TITLE
Can't get custom output name from tfserving

### ISSUE THREAD

**Issue by xyangk** [tensorflow/tensorflow#44572]
I want the outputs from tfserving is:  `{"outputs":{"scores":[0.936071157,0.0527787767]}}`
but I got : `{ "outputs": [ 0.936071038, 0.0527787916 ] }`

Environment:
python 3.6
tensorflow 2.3.0

save model code:
```
class MyModel(tf.keras.Model):
    def __init__(self):
        super(MyModel, self).__init__()
        self.pmodel = model.model
        self.out = keras.layers.Lambda(lambda x:x[:,1])
        
    @tf.function(input_signature=[[tf.TensorSpec(shape=[None,1], dtype=tf.string, name='input_q'), tf.TensorSpec(shape=[None,1], dtype=tf.string, name='input_a')]])
    def call(self, inputs):
        output = self.pmodel(inputs)
        out = self.out(output)
        return {"scores": out} 

NM = MyModel()

# test
# print(NM([qi, ai]))
# {'scores': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.93607116, 0.05277878], dtype=float32)>}

# save model
tf.saved_model.save(NM, 'saved_model/202011032114')
```
By the way, model.model is tf.keras.Model :
![image](https://user-images.githubusercontent.com/9495054/97988975-d108df00-1e18-11eb-8915-d3d1fc35a8ed.png)

SignatureDefs:
![image](https://user-images.githubusercontent.com/9495054/97989755-f34f2c80-1e19-11eb-8edd-b624bdf2d0cd.png)

Start tfserving
![image](https://user-images.githubusercontent.com/9495054/97989821-0c57dd80-1e1a-11eb-87ec-ab4f9a59aa2b.png)

What I got :(
![image](https://user-images.githubusercontent.com/9495054/97990261-a1f36d00-1e1a-11eb-8708-8673f0422c96.png)

**But!**, If model output two keys like `{"scores": out, "give_up":out}`, it works well.
```
class MyModel(tf.keras.Model):
    def __init__(self):
        super(MyModel, self).__init__()
        self.pmodel = model.model
        self.out = keras.layers.Lambda(lambda x:x[:,1])
        
    @tf.function(input_signature=[[tf.TensorSpec(shape=[None,1], dtype=tf.string, name='input_q'), tf.TensorSpec(shape=[None,1], dtype=tf.string, name='input_a')]])
    def call(self, inputs):
        output = self.pmodel(inputs)
        out = self.out(output)
        return {"scores": out, "give_up":out}

NM = MyModel()

# test
# print(NM([qi, ai]))
# {'scores': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.93607116, 0.05277878], dtype=float32)>, 'give_up': <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.93607116, 0.05277878], dtype=float32)>}

# save model
tf.saved_model.save(NM, 'saved_model/202011032126')
```
![image](https://user-images.githubusercontent.com/9495054/97990853-83da3c80-1e1b-11eb-94c9-30e83dcf9c3a.png)

![image](https://user-images.githubusercontent.com/9495054/97990822-74f38a00-1e1b-11eb-8928-51d1d77747bb.png)

And the result:
![image](https://user-images.githubusercontent.com/9495054/97990916-9a809380-1e1b-11eb-9cee-05e8924455b6.png)

I don't know why and didn't find any solution, Is there any kind person to help me ? Many thanks !

**Comment by amahendrakar** [comment]
@xyangk,
TensorFlow Serving issues are tracked in tensorflow/serving repo. Could you please submit a new issue from [this link](https://github.com/tensorflow/serving/issues/new) and fill in the template, so that we can track the issue there. Thanks!

**Comment by xyangk** [comment]
tfserving response: https://github.com/tensorflow/serving/issues/1766#issuecomment-724481376
