### ISSUE TITLE
Floating-point models

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#44579]
Can tensorflow Lite for Microcontrollers run fp models or just quantized ones? if so, are there examples to run fp models?

**Comment by Saduf2019** [comment]
@peter197321 
tensorflow Lite for Microcontrollers run just quantized, as this is not a bug or feature request please open this issue at [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) for any further queries.
