### ISSUE TITLE
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by parthshahengg** [tensorflow/tensorflow#44586]
![image](https://user-images.githubusercontent.com/19899607/98122360-7b930780-1ed6-11eb-8def-ae981ef57dcb.png)

Getting this error while importing TensorFlow.

It installed successfully.

CPU : Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz
OS : Windows server 2016
python: 3.7.6
TensorwFlow : 2.3.0 and 2.2.0 both gives same error

Checked parameters : 
-Installed Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019
-msvcp140_1.dll present
-AVX is enabled

TensorFlow 2.0.0 already working on this system.
This server doesn't have internet access so to upgrade Tensorflow I have tried 2 ways.
-Create conda environment pack in local machine and copy and run environment.
-Download .whl files using pip in local machine and installed it on a remote server

In both these ways, I am able to install tensorflow successfully but while importing it gives this error.
So, Please suggest how can I upgrade TensorFlow 2.0.0 to 2.3.0

**Comment by amahendrakar** [comment]
@parthshahengg,
Installation issues within the Anaconda environment are tracked in the Anaconda repo.

Could you please submit a new issue using [this link](https://github.com/ContinuumIO/anaconda-issues/issues) and fill in the template, so that the issue can be tracked there. Thanks!

**Comment by parthshahengg** [comment]
I can do this.
But I don't think this is related to anaconda. 
Because I already tried this without anaconda with pip only. But getting the same error.

**Comment by morell5** [comment]
A

**Comment by parthshahengg** [comment]
Issue still not fixed

**Comment by amahendrakar** [comment]
@parthshahengg,
Could you please uninstall TensorFlow and Python, restart the machine and check if a fresh install works? 

And make sure you have all the required dependencies as mentioned [here](https://www.tensorflow.org/install/pip#system-requirements). Thanks!
