### ISSUE TITLE
bazel build tensorflow/python/tools:strip_unused throws linker error

### ISSUE THREAD

**Issue by shrnjad** [tensorflow/tensorflow#4458]
I am trying to solve the problem of running a retrained model on iOS described in issue [2883](https://github.com/tensorflow/tensorflow/issues/2883). However when I call this command I run into linker error:

> bazel build tensorflow/python/tools:strip_unused

The linker error says:

> bazel-out/local-fastbuild/bin/tensorflow/core/libversion_lib.a(version_info.pic.o): In function `tf_git_version()':
version_info.cc:(.text+0x0): multiple definition of `tf_git_version()'
bazel-out/local-fastbuild/bin/tensorflow/core/libframework_internal.lo(version_info.pic.o):version_info.cc:(.text+0x0): first defined here
bazel-out/local-fastbuild/bin/tensorflow/core/libversion_lib.a(version_info.pic.o): In function `tf_compiler_version()':
version_info.cc:(.text+0xd): multiple definition of `tf_compiler_version()'
bazel-out/local-fastbuild/bin/tensorflow/core/libframework_internal.lo(version_info.pic.o):version_info.cc:(.text+0xd): first defined here
collect2: error: ld returned 1 exit status
Target //tensorflow/python/tools:strip_unused failed to build

I tried it on both Mac and Ubuntu Linux with the same error. I am operating on git commit a6c5f8e. Can someone help me how to build this tool?

**Comment by shrnjad** [comment]
I tried building with an earlier build and it worked. I chose commit 5b265ff. So I suppose in between those commits something was broken.

**Comment by jmchen-g** [comment]
@jart Could you take a look at this? Thanks.

**Comment by ic** [comment]
Later commits 8fdb974 and its successor 5563229 do build properly (caveat: the `giflib` link seems broken). The master I have used on this "dichotomy" breaks (f6e0f64f).

I picked 8fdb974 for testing due to modification related to the duplicate symbols in the next commit (5563229). Unfortunately this did not pin-point the issue.

It seems the problem is "indirect". Perhaps some wildcard somewhere includes twice the same file (there was a similar issue in the `Makefile` in `tensorflow/contrib/makefile`), or an issue with how the `extern` declaration is used by the build system (e.g. in `tensorflow/core/public/version.h`). Just a guess. Hope this serves.

**Comment by jart** [comment]
I tried to reproduce this error. I compiled Bazel from HEAD. I fetched TensorFlow at HEAD. I ran `./configure` and `bazel build tensorflow/python/tools:strip_unused` and I ended up with this:

```
INFO: From ProtoCompile tensorflow/python/training/checkpoint_state_pb2.py:
external/protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile tensorflow/contrib/session_bundle/manifest_pb2.py:
external/protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile tensorflow/contrib/tensorboard/plugins/projector/projector_config_pb2.py:
external/protobuf/python: warning: directory does not exist.
ERROR: /usr/local/google/home/jart/code/tensorflow-clean/tensorflow/contrib/tfprof/tools/tfprof/BUILD:42:1: null failed: linux-sandbox failed: error executing command 
  (cd /usr/local/google/home/jart/.cache/bazel/_bazel_jart/534cc9069a4bd39f8bace6b1039c6506/bazel-sandbox/978fc997-2a45-4494-836a-df35eb0b4705-842/execroot/tensorflow-clean && \
  exec env - \
  /usr/local/google/home/jart/.cache/bazel/_bazel_jart/534cc9069a4bd39f8bace6b1039c6506/execroot/tensorflow-clean/_bin/linux-sandbox @/usr/local/google/home/jart/.cache/bazel/_bazel_jart/534cc9069a4bd39f8bace6b1039c6506/bazel-sandbox/978fc997-2a45-4494-836a-df35eb0b4705-842/linux-sandbox.params -- bazel-out/host/bin/external/protobuf/protoc '--python_out=bazel-out/local-fastbuild/genfiles/' -I. -Iexternal/protobuf/python -Ibazel-out/local-fastbuild/genfiles/external/protobuf/python tensorflow/contrib/tfprof/tools/tfprof/tfprof_log.proto tensorflow/contrib/tfprof/tools/tfprof/tfprof_output.proto).
external/protobuf/python: warning: directory does not exist.
tensorflow/core/framework/tensor_shape.proto: File not found.
tensorflow/core/framework/types.proto: File not found.
tensorflow/contrib/tfprof/tools/tfprof/tfprof_output.proto: Import "tensorflow/core/framework/tensor_shape.proto" was not found or had errors.
tensorflow/contrib/tfprof/tools/tfprof/tfprof_output.proto: Import "tensorflow/core/framework/types.proto" was not found or had errors.
tensorflow/contrib/tfprof/tools/tfprof/tfprof_output.proto:9:12: "DataType" is not defined.
tensorflow/contrib/tfprof/tools/tfprof/tfprof_output.proto:45:12: "TensorShapeProto" is not defined.
Target //tensorflow/python/tools:strip_unused failed to build
INFO: Elapsed time: 53.186s, Critical Path: 40.69s
```

I'm putting it here for anyone who might search this error. I'm still  investigating a solution.

**Comment by jart** [comment]
I turned off Bazel sandboxing and `//tensorflow/python/tools:strip_unused` builds, so I'm unable to reproduce this error. Try updating to HEAD, updating Bazel, and then running ./configure again. It should work. I'm not sure what happened before. But I can tell you that we're planning on doing significant cleanup to the way we generate that version_info.cc file.

**Comment by ic** [comment]
Would `configure` checking for the exact required Bazel version help too?

**Comment by jart** [comment]
Good idea @ic. It's something we definitely need. So I filed #4975.
