### ISSUE TITLE
BUG!! tf.keras.model.summary() output is wrong

### ISSUE THREAD

**Issue by nityansuman** [tensorflow/tensorflow#44591]
**System information**

- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow version: 2.3.0
- Python version: 3.8.5
- GPU model and memory: Nvidia GeForce RTX 2080 Ti

**Describe the current behavior**
```
class DenseNormLayer(tf.keras.layers.Layer):
    def __init__(self, units, activation, name=None):
        super(DenseNormLayer, self).__init__(name=name)
        self.dense_layer = tf.keras.layers.Dense(units=units, activation=activation)
        self.batch_norm = tf.keras.layers.BatchNormalization()
    
    def call(self, x):
        x = self.batch_norm(x)
        x = self.dense_layer(x)
        return x
```

```
class BaselineModel(tf.keras.Model):
    def __init__(self, targets, name="BaselineModel"):
        super(BaselineModel, self).__init__(name=name)
        self.block1 = DenseNormLayer(units=1024, activation="relu", name="block1")
        self.block2 = DenseNormLayer(units=1024, activation="relu", name="block2")
        self.d1 = tf.keras.layers.Dense(units=512, activation="relu", name="d1")
        self.d2 = tf.keras.layers.Dense(units=1024, activation="relu", name="d2")
        self.dp = tf.keras.layers.Dropout(rate=0.2, name="dropout_layer")
        self.sigmoid_layer = tf.keras.layers.Dense(units=targets, activation="sigmoid", name="sigmoid_layer")
    
    def call(self, X):
        x = self.block1(X)
        x = self.block2(x)
        x = self.d1(x)
        x = self.dp(x)
        x = self.d2(x)
        x = self.sigmoid_layer(x)
        return x
    
    def build_graph(self, dim):
        x = tf.keras.Input(shape=dim)
        return tf.keras.Model(inputs=[x], outputs=self.call(x))
```

Output summary:
```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
block1 (DenseNormLayer)      multiple                  103824    
_________________________________________________________________
block2 (DenseNormLayer)      multiple                  1053696   
_________________________________________________________________
d1 (Dense)                   multiple                  524800    
_________________________________________________________________
d2 (Dense)                   multiple                  525312    
_________________________________________________________________
dropout_layer (Dropout)      multiple                  0         
_________________________________________________________________
sigmoid_layer (Dense)        multiple                  10250     
=================================================================
Total params: 2,217,882
Trainable params: 2,215,634
Non-trainable params: 2,248
_________________________________________________________________
```

Run this to get summary:
```
test_model = BaselineModel(targets=100)
test_model.build(input_shape=(None, 100))
test_model.summary()
```
As one can see in above summary, the `dropout_layer` is present below `d2` layer which is incorrect. It should be in between of `d1` and `d2` layers.
I tried cleaning python cache and also tried in Jupyter Notebook but no luck.

**Describe the expected behavior**

When plotting with the code below, output is correct.
```
import os
tf.keras.utils.plot_model(
    test_model.build_graph(dim=100), to_file=os.path.join(".", "model.png"),
    dpi=96, show_shapes=True, show_layer_names=True, expand_nested=False
)
````
![image](https://user-images.githubusercontent.com/23133817/98150766-303c2180-1ef5-11eb-8c73-2d5cdbf38ebf.png)

**Comment by amahendrakar** [comment]
@nityansuman,
On subclassing the Model, I am facing an error stating `TypeError: __init__() missing 1 required positional argument: 'targets'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/595a785eec860a3211cf1b1d8c56112e/44591.ipynb).

Could you please provide the complete code to reproduce the issue reported here? Thanks!

**Comment by nityansuman** [comment]
@amahendrakar https://colab.research.google.com/gist/amahendrakar/595a785eec860a3211cf1b1d8c56112e/44591.ipynb
Updated the notebook. Please have a look.

_Note: The above error is because summary is only available after model is build. Made changes._

**Comment by nityansuman** [comment]
@amahendrakar Updated the code snippet to successfully build model and get summary.

**Comment by nityansuman** [comment]
@amahendrakar Any updates on this ?

**Comment by amahendrakar** [comment]
@nityansuman,
Sorry for the delayed response. 

>         self.d2 = tf.keras.layers.Dense(units=1024, activation="relu", name="d2")
>         self.dp = tf.keras.layers.Dropout(rate=0.2, name="dropout_layer")

Interchanging the above two layers gives the expected output. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/03578c94918d33230da3b570437d14c5/44591-v2.ipynb). Thanks!

**Comment by nityansuman** [comment]
@amahendrakar Interchanging the above layers would mean we are replicating the layers based on the summary. Summary should show layer configuration.

That's the bug!!! With current configuration the summary is wrong. Layers can be configured in any manner.

**Comment by nityansuman** [comment]
@amahendrakar Why is model summary taking information from constructor rather than the call() method? Behaviour is wrong. Model summary displays the layer configuration and layer connection happens in call() method and not constructor.

**Comment by fchollet** [comment]
This is normal behavior. Your model is a subclassed model; such models don't have a graph structure (they're a blob of bytecode). As a result the layer ordering in `summary()` just reflects creation order.

If you want your model to have an inspectable graph structure (and hence an order-respecting summary), use the Functional API (e.g. `Model(inputs, outputs)`) to define your model.

**Comment by nityansuman** [comment]
@fchollet Interesting!! Thanks for the response.

> This is normal behavior. Your model is a subclassed model; such models don't have a graph structure (they're a blob of bytecode). As a result the layer ordering in `summary()` just reflects creation order.
> 
> If you want your model to have an inspectable graph structure (and hence an order-respecting summary), use the Functional API (e.g. `Model(inputs, outputs)`) to define your model.

@fchollet Interesting!! Thanks for the response.
