### ISSUE TITLE
AssertionError t.graph == cond_graph using tf.GradientTape

### ISSUE THREAD

**Issue by prokotg** [tensorflow/tensorflow#44598]
Hi, 

I posted a [similar question](https://stackoverflow.com/questions/64661822/what-is-the-meaning-of-assertion-error-assert-t-graph-cond-grap-using-tf-gra) on SO, but I am not sure anymore if the problem is on my side or somewhere in TF (hence no MRE).  Similar problem [here ](https://stackoverflow.com/questions/62911595/assertionerror-assert-t-graph-cond-graph-when-generating-heatmap-for-locally). I have been succesfully using `keras.backend.gradients` as for now but I have recently made a switch to `tensorflow.keras`  and since `tf.gradient` is not allowed in eager execution mode, I had to use `tf.GradientTape()`. 

So basically I changed all calls from this:

```python
grads = keras.backend.gradients(loss=target_tensor, variables=[var1, var2, var3])
```
to:
```python
with tf.GradientTape(persistent=True) as tape:
   # any calulations involving target_tensor, and var1, var2, ...
grads = tape.gradient(target=target_tensor, sources=[var1, var2, var3])
``` 

and I am getting this on any call (even if target and source is the same):

```console
c:\users\tomas\miniconda3\envs\tftest\lib\site-packages\tensorflow\python\ops\cond_v2.py in _resolve_grad_inputs(cond_graph, grad_graph)
    411     # `cond_graph`.
    412     if t.graph != grad_graph.outer_graph:
--> 413       assert t.graph == cond_graph
    414       # `internal_captures` are not treated as intermediates and hence not added
    415       # to If op outputs. So we get the outer tensor corresponding to those

AssertionError: 
```

I tried to dig into the TF code but I cannot really tell what is it that I am doing wrong.  There are no problems with toy-examples from docs but I cannot calculate any gradient in my graph. What does this assertion check exactly? How I can resolve this? 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- TensorFlow installed from (source or binary): pip 
- TensorFlow version (use command below): 2.3.1, but also 2.2.0
- Python version: 3.8

**Comment by amahendrakar** [comment]
@prokotg,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!
