### ISSUE TITLE
Graph disconnected when using transfer learning

### ISSUE THREAD

**Issue by e-dzia** [tensorflow/tensorflow#44608]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.3.0-54-gfcc4b966f1 2.3.1
- Python version: Python 3.8.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: (nvcc) 10.1, V10.1.243; 
- GPU model and memory: Nvidia 2080 Ti

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

When trying to obtain values for intermediete layers of a pre-trained model, I get a "Graph disconnected" error, even though it is connected. I can train it, evaluate it, predict images, etc.

Fragment of code (the whole code is in a Colab - below):

```
img_size = (299, 299)
IMG_SHAPE = (*img_size, 3)
base_model = tf.keras.applications.InceptionResNetV2(input_shape=IMG_SHAPE,
                                                    include_top=False,
                                                    weights='imagenet')
base_model.trainable = False
preprocess_input = tf.keras.applications.inception_resnet_v2.preprocess_input

data_augmentation = [
  tf.keras.layers.experimental.preprocessing.RandomFlip('horizontal_and_vertical'),
  tf.keras.layers.experimental.preprocessing.RandomRotation(0.2, fill_mode="constant")  
]

data_augmentation = tf.keras.Sequential(data_augmentation)

global_average_layer = tf.keras.layers.GlobalAveragePooling2D()

top_layers = []
top_layers.extend([
    tf.keras.layers.Dense(512, activation="relu", 
                          kernel_initializer="glorot_normal", 
                          bias_initializer="glorot_uniform"),
    tf.keras.layers.Dropout(0.2)
])

prediction_layer = tf.keras.layers.Dense(1, activation="sigmoid", 
                                         kernel_initializer="glorot_normal", 
                                         bias_initializer="glorot_uniform")

inputs = tf.keras.Input(shape=(*img_size, 3))
x = data_augmentation(inputs)
x = preprocess_input(x)
x = base_model(x, training=False)
x = global_average_layer(x)
x = tf.keras.layers.Dropout(0.2)(x)
for layer in top_layers:
    x = layer(x)
outputs = prediction_layer(x)
model = tf.keras.Model(inputs, outputs)

(...)

model2 = tf.keras.Model(inputs=model.input, 
                        outputs=model.get_layer('inception_resnet_v2').output)
```

**Describe the expected behavior**

Possibility to obtain values of intermediete layers of a pre-trained model - maybe possibility to see all intermediate layers in model.summary(), because currently it looks like this:

```
Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_2 (InputLayer)         [(None, 299, 299, 3)]     0         
_________________________________________________________________
sequential (Sequential)      (None, 299, 299, 3)       0         
_________________________________________________________________
tf_op_layer_RealDiv (TensorF [(None, 299, 299, 3)]     0         
_________________________________________________________________
tf_op_layer_Sub (TensorFlowO [(None, 299, 299, 3)]     0         
_________________________________________________________________
inception_resnet_v2 (Functio (None, 8, 8, 1536)        54336736  
_________________________________________________________________
global_average_pooling2d (Gl (None, 1536)              0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 1536)              0         
_________________________________________________________________
dense (Dense)                (None, 512)               786944    
_________________________________________________________________
dropout (Dropout)            (None, 512)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 513       
=================================================================
Total params: 55,124,193
Trainable params: 787,457
Non-trainable params: 54,336,736
_________________________________________________________________
```

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

https://colab.research.google.com/drive/1cgwJho63-QtQYS3Tdk4O5jioDu_szYjl?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-a7165f00310b> in <module>()
      1 model2 = tf.keras.Model(inputs=model.input, 
----> 2                         outputs=model.get_layer('inception_resnet_v2').output)

5 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in __new__(cls, *args, **kwargs)
    240       # Functional model
    241       from tensorflow.python.keras.engine import functional  # pylint: disable=g-import-not-at-top
--> 242       return functional.Functional(*args, **kwargs)
    243     else:
    244       return super(Model, cls).__new__(cls, *args, **kwargs)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/base.py in _method_wrapper(self, *args, **kwargs)
    455     self._self_setattr_tracking = False  # pylint: disable=protected-access
    456     try:
--> 457       result = method(self, *args, **kwargs)
    458     finally:
    459       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py in __init__(self, inputs, outputs, name, trainable)
    113     #     'arguments during initialization. Got an unexpected argument:')
    114     super(Functional, self).__init__(name=name, trainable=trainable)
--> 115     self._init_graph_network(inputs, outputs)
    116 
    117   @trackable.no_automatic_dependency_tracking

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/base.py in _method_wrapper(self, *args, **kwargs)
    455     self._self_setattr_tracking = False  # pylint: disable=protected-access
    456     try:
--> 457       result = method(self, *args, **kwargs)
    458     finally:
    459       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py in _init_graph_network(self, inputs, outputs)
    189     # Keep track of the network's nodes and layers.
    190     nodes, nodes_by_depth, layers, _ = _map_graph_network(
--> 191         self.inputs, self.outputs)
    192     self._network_nodes = nodes
    193     self._nodes_by_depth = nodes_by_depth

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py in _map_graph_network(inputs, outputs)
    929                              'The following previous layers '
    930                              'were accessed without issue: ' +
--> 931                              str(layers_with_complete_input))
    932         for x in nest.flatten(node.outputs):
    933           computable_tensors.add(id(x))

ValueError: Graph disconnected: cannot obtain value for tensor Tensor("input_1:0", shape=(None, 299, 299, 3), dtype=float32) at layer "conv2d". The following previous layers were accessed without issue: []

**Comment by e-dzia** [comment]
UPDATE

So, when instead of
```
model2 = tf.keras.Model(inputs=model.input, 
                        outputs=model.get_layer('inception_resnet_v2').output)
```

I use

```
model2 = tf.keras.Model(inputs=model.input, 
                        outputs=model.get_layer('inception_resnet_v2').get_output_at(0))
```

Then it works! So I believe this issue can be closed now, but I think you should include it in the documentation (it is not included right now) - for this purpose, I am leaving this issue open.

All credit should go to [Mitiku](https://stackoverflow.com/users/5825953/mitiku) from [this Stackoveflow thread](https://stackoverflow.com/questions/55073785/disconnected-graph-when-concatenating-two-models). This is his answear:

> The layer you are trying to use as output has two output nodes. The first connects the input of model2 to the output of the model2. The second output node connects the output of the model1 and the first layer of model2. By default, the layer output returns only the first output node. So what is happening is you are tying to connect the input of the model_merge(input of model1) with the first output node.
> 
> To following code shows this. Individual output nodes of the layer can be accessed using the get_output_at() method of the layer.
> 
> `layer_output = model_merge.layers[-2].output # The first output node`
> `layer_output_1 = model_merge.layers[-2].get_output_at(0) # The first output node`
> `layer_output_2 = model_merge.layers[-2].get_output_at(1) # The second output node`
> Now the following two codes throws error because the graph is disconnected.
> 
> `test2 = Model(inputs=model_merge.input, outputs=layer_output)`
> and
> 
> `test2 = Model(inputs=model_merge.input, outputs=layer_output_1)`
> But the code below doesnot throw error, because the graph is connected.
> 
> `test2 = Model(inputs=model_merge.input, outputs=layer_output_2)`

**Comment by ymodak** [comment]
Thanks for the issue. The docs are now updated.
