### ISSUE TITLE
keras epsilon doesn't change 

### ISSUE THREAD

**Issue by je-santos** [tensorflow/tensorflow#44604]
Windows, TF 2.3.1

I'm trying to change the epsilon so my MAPE doesn't blow up. When I do:

$tensorflow.keras.backend.set_epsilon = 1e-3
and then:
$tensorflow.keras.backend.epsilon()
I get:
>>>> 1e-07

**Comment by ravikyram** [comment]
@je-santos 

I have tried in colab with TF 2.3.1 version and i am not seeing any issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/3dd9f318dd195976dbdda087e7f4d2b9/untitled486.ipynb).Please, verify once and close the issue. Thanks!

**Comment by je-santos** [comment]
Hi @ravikyram . I re-installed my TF and now it works. Thanks for the quick response to the issue.
