### ISSUE TITLE
fatal error: tensorflow/core/framework/types.pb.h: No such file or directory

### ISSUE THREAD

**Issue by sairmreddy** [tensorflow/tensorflow#44602]
**System information**
- OS Platform and Distribution : Linux Ubuntu 18.04.5 LTS
- TensorFlow installed from source
- TensorFlow version : r2.2
- Python version : py3.6
- Bazel version : 2.0.0
- GCC/Compiler version : 7.5.0

 
steps to produce error:

- sudo apt install python3-dev python3-pip
- pip install -U --user pip numpy wheel
- pip install -U --user keras_preprocessing --no-deps
- git clone https://github.com/tensorflow/tensorflow.git
- cd tensorflow
- git checkout r2.2
- ./configure

You have bazel 2.0.0 installed.
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python3

Found possible Python library paths:
/usr/lib/python3/dist-packages
/usr/local/lib/python3.6/dist-packages
Please input the desired Python library path to use. Default is [/usr/lib/python3/dist-packages]

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: n
Clang will not be downloaded.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]:

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
--config=mkl # Build with MKL support.
--config=monolithic # Config for mostly static monolithic build.
--config=ngraph # Build with Intel nGraph support.
--config=numa # Build with NUMA support.
--config=dynamic_kernels # (Experimental) Build kernels into separate shared objects.
--config=v2 # Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
--config=noaws # Disable AWS S3 filesystem support.
--config=nogcp # Disable GCP support.
--config=nohdfs # Disable HDFS support.
--config=nonccl # Disable NVIDIA NCCL support.
Configuration finished

-> bazel build -c opt tensorflow:libtensorflow_cc.so
-> then i created CMakeLists.txt file in tensorflow/tensorflow/examples/speech_commands/ 
-> cd /tensorflow/examples/speech_commands/
-> mkdir build
-> cd build
-> cmake ..
-> make
Then i am facing this issue.
ERROR:
[ 50%] Building CXX object CMakeFiles/speech_recog.dir/label_wav.cc.o
In file included from /home/sbojja/Qual-sdm/TF/tensorflow/tensorflow/core/framework/tensor.h:23:0,
from /home/sbojja/Qual-sdm/TF/tensorflow/tensorflow/examples/speech_commands/label_wav.cc:19:
/home/sbojja/Qual-sdm/TF/tensorflow/tensorflow/core/framework/tensor_shape.h:22:10: fatal error: tensorflow/core/framework/types.pb.h: No such file or directory
#include "tensorflow/core/framework/types.pb.h"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/speech_recog.dir/build.make:62: recipe for target 'CMakeFiles/speech_recog.dir/label_wav.cc.o' failed
make[2]: *** [CMakeFiles/speech_recog.dir/label_wav.cc.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/speech_recog.dir/all' failed
make[1]: *** [CMakeFiles/speech_recog.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

This is the cmake file
[CMakeLists.txt](https://github.com/tensorflow/tensorflow/files/5491688/CMakeLists.txt)

**Comment by amahendrakar** [comment]
@sairmreddy,
Could you please specify if you're trying to build the [Python TensorFlow package](https://www.tensorflow.org/install/source) or the [TensorFlow C API](https://www.tensorflow.org/install/lang_c)?

Please check the linked guides for the respective instructions and let us know if you are still facing the same error. Thanks!

**Comment by sairmreddy** [comment]
@amahendrakar 
For Tensorflow C++ API

**Comment by amahendrakar** [comment]
@sairmreddy,
Following the instructions mentioned in the [guide](https://www.tensorflow.org/install/lang_c), I was able to build the API without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/5d60664ec79b5fd06130dad057ed1b23/44602.ipynb).

Could you please try building the API using TF v2.3 (instead of TF v2.2) and let us know if you are facing the same issue. Thanks!

**Comment by sairmreddy** [comment]
@amahendrakar,
can you please compile this
[label_wav (copy).txt](https://github.com/tensorflow/tensorflow/files/5587239/label_wav.copy.txt)
.cc file same as above.

**Comment by amahendrakar** [comment]
@sairmreddy,
On running the `label_wav.cc` file, I am facing an error stating `fatal error: tensorflow/core/framework/tensor.h: No such file or directory`. 

Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/87a86001d2e147286dc2d15f2659379b/44602.ipynb#scrollTo=Gpr_pve3rzNG). Thanks!

**Comment by sairmreddy** [comment]
Then how can i compile this file, if any one tried this  please help. Thanks.

**Comment by sairmreddy** [comment]
Hi @rmothukuru 

now i am getting these errors

CMakeFiles/speech_recog.dir/label_wav.cc.o: In function `tensorflow::Status tensorflow::errors::NotFound<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*>(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*)':
label_wav.cc:(.text._ZN10tensorflow6errors8NotFoundIJPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES3_EEENS_6StatusEDpT_[_ZN10tensorflow6errors8NotFoundIJPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES3_EEENS_6StatusEDpT_]+0xe5): undefined reference to `tensorflow::Status::Status(tensorflow::error::Code, absl::string_view, std::vector<tensorflow::StackFrame, std::allocator<tensorflow::StackFrame> >&&)'
CMakeFiles/speech_recog.dir/label_wav.cc.o: In function `main':
label_wav.cc:(.text.startup+0x1219): undefined reference to `tensorflow::TensorShapeBase<tensorflow::TensorShape>::TensorShapeBase(absl::Span<long long const>)'
label_wav.cc:(.text.startup+0x1f55): undefined reference to `tensorflow::TensorShapeBase<tensorflow::TensorShape>::TensorShapeBase(absl::Span<long long const>)'
label_wav.cc:(.text.startup+0x1fa8): undefined reference to `tensorflow::TensorShapeBase<tensorflow::TensorShape>::TensorShapeBase(absl::Span<long long const>)'
collect2: error: ld returned 1 exit status
CMakeFiles/speech_recog.dir/build.make:114: recipe for target 'speech_recog' failed
make[2]: *** [speech_recog] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/speech_recog.dir/all' failed
make[1]: *** [CMakeFiles/speech_recog.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

This is the CmakeLists.txt
[CMakeLists.txt](https://github.com/tensorflow/tensorflow/files/5616823/CMakeLists.txt)

**Comment by sairmreddy** [comment]
sbojja@sbojja-Latitude-E5450:~/TF-speech/tensorflow$ git checkout r2.3
M	tensorflow/tools/ci_build/install/install_proto3.sh
M	tensorflow/tools/ci_build/protobuf/protobuf_optimized_pip.sh
Switched to branch 'r2.3'
Your branch is up-to-date with 'origin/r2.3'.
sbojja@sbojja-Latitude-E5450:~/TF-speech/tensorflow$ ./configure 
You have bazel 3.1.0 installed.
Please specify the location of python. [Default is /usr/bin/python3]: 


Found possible Python library paths:
  /usr/local/lib/python3.5/dist-packages
  /usr/lib/python3/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python3.5/dist-packages]

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: 
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: 
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: 
Clang will not be downloaded.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: 
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=ngraph      	# Build with Intel nGraph support.
	--config=numa        	# Build with NUMA support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
	--config=v2          	# Build TensorFlow 2.x instead of 1.x.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=noaws       	# Disable AWS S3 filesystem support.
	--config=nogcp       	# Disable GCP support.
	--config=nohdfs      	# Disable HDFS support.
	--config=nonccl      	# Disable NVIDIA NCCL support.
Configuration finished
sbojja@sbojja-Latitude-E5450:~/TF-speech/tensorflow$ history | grep bazel
  436  bazel build tensorflow/examples/label_image/...
  440  bazel build tensorflow/examples/label_image/...
  816  history | grep bazel build
  817  history | grep "bazel build"
  819  bazel build -c opt --copt=-w --output_filter=DONT_MATCH_ANYTHING tensorflow:libtensorflow_cc.so
  827  bazel build -c opt --copt=-w --output_filter=DONT_MATCH_ANYTHING tensorflow:libtensorflow_cc.so
 1318  history | grep bazel
sbojja@sbojja-Latitude-E5450:~/TF-speech/tensorflow$ bazel build -c opt --copt=-w --output_filter=DONT_MATCH_ANYTHING tensorflow:libtensorflow_cc.so
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=143
INFO: Reading rc options for 'build' from /home/sbojja/TF-speech/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/sbojja/TF-speech/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from /home/sbojja/TF-speech/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/local/lib/python3.5/dist-packages --python_path=/usr/bin/python3 --config=xla --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file /home/sbojja/TF-speech/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /home/sbojja/TF-speech/tensorflow/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:linux in file /home/sbojja/TF-speech/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/sbojja/TF-speech/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Build options --action_env, --define, and --host_copt have changed, discarding analysis cache.
INFO: Analyzed target //tensorflow:libtensorflow_cc.so (196 packages loaded, 19181 targets configured).
INFO: Found 1 target...
Target //tensorflow:libtensorflow_cc.so up-to-date:
  bazel-bin/tensorflow/libtensorflow_cc.so
INFO: Elapsed time: 12399.091s, Critical Path: 316.60s
INFO: 8489 processes: 8489 local.
INFO: Build completed successfully, 8759 total actions

and moved .so to /usr/local/lib/

then 
mkdir build
cd build
cmake ..
make
then i am getting above error

**Comment by leochan2009** [comment]
same issue with my ubuntu 18.04 with tensorflow 2.3.1. The tensorflow build was successful. though the same error happened:
: tensorflow/core/framework/types.pb.h: No such file or directory
 #include "tensorflow/core/framework/types.pb.h"

**Comment by shashank2710** [comment]
@tensorflowbutler @rmothukuru , 
Any updates? I am getting the same errors on my Ubuntu 18.04 with tensorflow 2.3.0 install?

**Comment by aswath8** [comment]
@shashank2710 Did you manage to solve the error?

**Comment by shashank2710** [comment]
@aswath8 refer #46837.

**Comment by aswath8** [comment]
@shashank2710 I did refer to the issue you posted, unfortunately, it ends by saying Errors 1 and 2 still exist and then you performed a fresh installation of Ubuntu and Updated Bazel flags. May I know what changes did you exactly make to the Bazel flags?

**Comment by Saduf2019** [comment]
@sairmreddy 
Is this still an issue can you please try with latest stable version and let us know.

**Comment by aswathselvam** [comment]
It works with the same configuration I initially built the library with. Just that include directory was wrong in cmakelists.txt, I fixed it now.

**Comment by sanatmpa1** [comment]
@sairmreddy,

Can you try to build latest version of TF `2.6.0` using this [guide](https://www.tensorflow.org/install/lang_c)? You can take a look the similar issues #46837,#43307 and #40538 for your reference. Thanks!

**Comment by NiuKeke** [comment]
> @tensorflowbutler @rmothukuru , Any updates? I am getting the same errors on my Ubuntu 18.04 with tensorflow 2.3.0 install?

I got the same errors on my Ubuntu 20.04 with tensorflow 2.9.0 install.

**Comment by NiuKeke** [comment]
> @sairmreddy Is this still an issue can you please try with latest stable version and let us know.

I got the same errors on my Ubuntu 20.04 with tensorflow 2.9.0 install.

**Comment by moeiscool** [comment]
still happens on 2.9.0 :(
