### ISSUE TITLE
Make TensorFlow Lite available as Swift Package Manager package

### ISSUE THREAD

**Issue by lothrop** [tensorflow/tensorflow#44609]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): Lite 2.3.0
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.**
Right now, TensorFlow Lite is available as a CocoaPod or as source for iOS developers. CocoaPods cannot be used from inside a Swift Package Manager (SPM) package. Since SPM is the official package manager from Apple and the way forward, it would be nice to have TensorFlow Lite available as an SPM package or an XCFramwork, in addition to the current CocoaPods distribution.

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
iOS developers who are using SPM for module manager or who are not using CocoaPods anymore.

**Any Other info.**
I have tried creating my own SPM package or XCFramework from the source but could not get it to work because of the native code. But I'm confident it should be possible.

**Comment by mrosales** [comment]
This isn't a solution, but I spent a fair amount of time digging into this trying to find a workaround. This is a little brain dump of my progress.

I was able to get a custom build of TFLite built and packaged as an XCFramework in a private SPM module, but it required a handful of hacks to get working properly. I'm not really comfortable with bazel though, so I did all of this with writing a bash script over a handful of bazel operations.

My workflow is:

1. Build a device static framework with 

```
bazel build --config=ios --ios_multi_cpus="armv7,arm64" //tensorflow/lite/experimental/ios:TensorFlowLiteC_framework
# copy output file to temporary build dir
```

2. Build a simulator static framework with 

```
bazel build --config=ios --ios_multi_cpus="i386,x86_64" //tensorflow/lite/experimental/ios:TensorFlowLiteC_framework
# copy output file to temporary build dir
```

3. Write some `Info.plist` files into the framework folders since bazel seems to omit them and Xcode will silently fail to install your app on a device if they are missing.

4. Create an xcframework with something like

```
xcodebuild -create-xcframework \
   -output "${OUTPUT}" \
   -framework "${BUILD_DIR}/dev/TensorFlowLiteC.framework" \
   -framework "${BUILD_DIR}/sim/TensorFlowLiteC.framework
```

5. At this point, I made a sample private git repo that vendored the swift code and the `TensorFlowLiteC.xcframework` file and then added a `Package.swift` file to make it work as a source for SPM.  The [instructions on the apple developer site](https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages) give some helpful instructions for shipping a binary framework with SPM.

One limitation is that the xcframeworks will require you to manually disable the iOS simulator for `arm64` architecture because tensorflow (rooted in a problem in bazel-core) assumes that `arm64` is always an ios device, not a simulator. See the bug I filed here for details: https://github.com/bazelbuild/rules_apple/issues/980

To "disable the iOS simulator for `arm64`", you need to set the following Xcode build setting:

```
EXCLUDED_ARCHS[sdk=iphonesimulator*] = i386 arm64
```

**Comment by jdduke** [comment]
@yyoon and @teijeong have we done any investigation into supporting the Swift Package Manager?

**Comment by yyoon** [comment]
We haven't done any investigation, and I'll need to learn more about Swift Package Manager to understand how much effort it would be required to support it.

cc/ @morganchen12 who might have some experience about this.

**Comment by morganchen12** [comment]
Probably the most challenging part of adding SPM support is you will need to add SPM support for all of your dependencies. SPM packages are also defined per-repository, so one Package.swift file at the root of the tensorflow repo would be responsible for representing Tensorflow, TensorFlowLiteSwift, TensorFlowLiteObjC, TensorFlowLiteC, and any other modules that are buildable in a Swift target.

It looks like TensorFlowLiteSwift and TensorFlowLiteObjC have [very shallow dependency graphs](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/lite/experimental/ios/TensorFlowLiteC.podspec?q=TensorFlowLiteC.podspec), so adding SPM support should be straightforward.

**Comment by greenzeal** [comment]
Today I hit the error building the framework with Xcode 12.3 `Building for iOS Simulator, but the linked and embedded framework 'ITLogin.framework' was built for iOS + iOS Simulator.` Which was working with Xcode 12.2 With Xcode 12.3 it is not a feature anymore, it is a bugfix.
It is time to move to XCFrameworks. Lots of big and small companies are already doing this.

https://gist.github.com/evnik introduced conversion script as a temporary solution: https://gist.github.com/evnik/6762d5c3a4b21f61f13b100e03b62c38

**Comment by yyoon** [comment]
Yeah, I think XCFramework makes more sense than Swift Package Manager approach, as XCFramework supports packaging compiled binaries as we currently do today.

As far as I can tell, CocoaPods supports XCFrameworks already, but bazel still doesn't support building for iOS arm64 simulator (for M1-based macs) nor building XCFrameworks natively. We might need to do some manual work in the interim, with something like the script @greenzeal linked.

@greenzeal In what exact situation were you seeing that specific error? Can you be a bit more specific and help me reproduce that issue? What does your project structure look like?

**Comment by greenzeal** [comment]
@yyoon 
I am trying to create my framework, but have a dependency on TensorFlowLiteC.framework.
to reproduce:
- Xcode 12.3 
- Having a TensorFlowLiteC.framework embedded
- Build for iOS Simulator with release configuration

The compiler will complain like this: `Building for iOS Simulator, but the linked and embedded framework 'ITLogin.framework' was built for iOS + iOS Simulator.`

Another simple way to reproduce:
- Xcode 12.3
- create dummy Xcode project
- `pod init`
- add to pods `pod 'TensorFlowLiteObjC'` (it will download its dependency TensorFlowLiteC.framework)
- `pod install`
- Build for iOS Simulator with release configuration

I tried different ways to find a solution like building the Bazel and then TensorFlowLiteC from the source, but all lead to that error.
Besides tried to build TensorFlowLiteC normally and then using the patch mentioned [here](https://gist.github.com/indragiek/e14162c0098d97ee976bceae9441f04d) after with lipo added third architecture to simulator build in the XCFramework.

I would really appreciate if anyone has a workaround. Or maybe it's possible to build TensorFlowLiteC.framework using Xcode (xcodebuild)?

**Comment by greenzeal** [comment]
btw also I will be happy if there is a way, even a manual one. And will be happy to try to automate it and share it here.

**Comment by yyoon** [comment]
@greenzeal I could create a dummy project as you described and confirmed that I could reproduce.

Do you really need to build your framework for arm64 simulator?
If not, you could go to the target build settings, and add `arm64` as an excluded architecture for `Any iOS Simulator SDK` for both debug and release configs.

![image](https://user-images.githubusercontent.com/1309817/104322969-eab95780-5528-11eb-8b76-d73767dfcb5b.png)

If you have a pressing need to build for arm64 simulator, you might want to try this:
https://github.com/bazelbuild/rules_apple/issues/980#issuecomment-738645357

This would let you build a TensorFlowLiteC slice for arm64 simulator (haven't had a chance to try it myself). Then, you could add the build output to the "Frameworks and Libraries" list of your framework project.

**Comment by greenzeal** [comment]
Excluding arm64 is a temporary option indeed. 

I had tried with a patch, but had no luck yet to make it work. Will try again definitely.

**Comment by ebraraktas** [comment]
What is the current situation of the issue? @yyoon @teijeong @jdduke 

I have tried to create `TensorFlowLiteC.xcframework` following the gist shared by @greenzeal ([message](https://github.com/tensorflow/tensorflow/issues/44609#issuecomment-757868653)) and [steps](https://github.com/tensorflow/tensorflow/issues/44609#issuecomment-724346317) described by @mrosales . I have created `TensorFlowLiteC` Swift Package and `TensorFlowLite` Swift Package (which depends on the former, `TensorFlowLiteC`) and successfully built, run and archived my app. However, it has failed at `Upload to App Store` stage (you can find error logs at the end). It would be nice to have official `TensorFlowLiteC.xcframework` to depend on. Most of the popular packages such as `firebase` have SPM support for their `binaryTarget`s.

I have used official `TensofFlowLiteC.framework` distributed in `Cocoapods` and `lipo` to create `simulator` and `ios` frameworks, and added an `Info.plist` having relevant fields for a framework. Note that I had to separate `TensorFlowLiteC.xcframework` to its own package to work around some build issues on Xcode. 

## Errors

I have tried several workarounds to eliminate some errors like first two below.

I applied the [solution in swift forums](https://forums.swift.org/t/swift-package-binary-framework-issue/41922/3) to eliminate:

```
ERROR ITMS-90680: "Invalid directory. The bundle Payload/MyApp.app/PlugIns/TensorFlowLiteC.framework is not contained in a correctly named directory. It should be under "Frameworks"."
```
 and it seems worked out.

And, I am not sure if it is relevant but I tried to set `ENABLE_BITCODE=NO` for my project to get rid of the error below:

```
ERROR ITMS-90635: "Invalid Mach-O Format. The Mach-O in bundle "MyApp.app/Frameworks/TensorFlowLiteC.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains arm64(bitcode), while the nested bundle Mach-O contains arm64(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting."
```

But as you can see below, __now__ I have something similar and several others:

```
ERROR ITMS-90635: "Invalid Mach-O Format. The Mach-O in bundle "MyApp.app/Frameworks/TensorFlowLiteC.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains arm64(machine code), while the nested bundle Mach-O contains arm64(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting."
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'MyApp.app/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
ERROR ITMS-90124: "The binary is invalid. The executable 'MyApp.app/Frameworks/TensorFlowLiteC.framework/TensorFlowLiteC' has type 'OBJECT' that is not valid. Only 'EXECUTE' is permitted."
ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."
ERROR ITMS-90210: "Missing load commands. The executable at 'MyApp.app/Frameworks/TensorFlowLiteC.framework' does not have the necessary load commands. Try rebuilding the app with the latest Xcode version. If you are using third party development tools, contact the provider."```

**Comment by jdduke** [comment]
Also looping in @miaout17

**Comment by Edgarchuk** [comment]
Is there any progress?

**Comment by iantimmis** [comment]
Please?

**Comment by yishuangP** [comment]
Hi, we start distributing XCFrameworks through Cocoapods for nightly builds https://github.com/CocoaPods/Specs/tree/master/Specs/1/6/0/TensorFlowLiteC/0.0.1-nightly.20220513
https://github.com/CocoaPods/Specs/tree/master/Specs/3/f/8/TensorFlowLiteSelectTfOps/0.0.1-nightly.20220513. Will release 2.9.0 with XCFrameworks soon.

**Comment by snyuryev** [comment]
@yishuangP thank you!

**Comment by yishuangP** [comment]
We've already released 2.9.0 with XCFrameworks (https://github.com/CocoaPods/Specs/tree/master/Specs/1/6/0/TensorFlowLiteC/2.9.0, https://github.com/CocoaPods/Specs/tree/master/Specs/3/f/8/TensorFlowLiteSelectTfOps/2.9.0, https://cocoapods.org/pods/TensorFlowLiteSwift, https://cocoapods.org/pods/TensorFlowLiteObjC). Note that this version doesn't have a ios-sim-arm64 slice yet but the nightly releases already have it.

**Comment by crcunningham** [comment]
Should this be closed given that the request was for a Swift package and there isn't a Swift package yet? It sounds like you're planning to add one which is great, I'm just wondering what issue is tracking that work?

**Comment by dfed** [comment]
From the original title ("Swift Package Manager package **or** XCFramework", emphasis mine), my guess is there is currently no issue tracking adding Swift Package Manager support.

[It is possible for SPM to declare a dependency on a remotely hosted xcframework zip file](https://developer.apple.com/documentation/xcode/distributing-binary-frameworks-as-swift-packages) (see the `Declare a Binary Target in the Package Manifest` section of that document), but we'd need someone who owns this repo to specify where the built XCFramework is hosted. That information is not currently documented – I recommend re-opening this issue until that documentation has been created @yishuangP

**Comment by yishuangP** [comment]
Hi sorry for the late reply, we do have plan to support SPM but it is deprioritized recently. We'll work on it asap. I'll reopen this issue to track this work

> [It is possible for SPM to declare a dependency on a remotely hosted xcframework zip file](https://developer.apple.com/documentation/xcode/distributing-binary-frameworks-as-swift-packages) (see the Declare a Binary Target in the Package Manifest section of that document), but we'd need someone who owns this repo to specify where the built XCFramework is hosted. That information is not currently documented

Yes we do have a remotely hosted xcframework zip file and it is public, you can see it in the cocoapods podspec. For example, in https://github.com/CocoaPods/Specs/blob/master/Specs/1/6/0/TensorFlowLiteC/2.9.0/TensorFlowLiteC.podspec.json, the link is https://dl.google.com/tflite-release/ios/prod/tensorflow/lite/release/ios/release/15/20220517-175828/TensorFlowLiteC/2.9.0/c88775ef9b845ba7/TensorFlowLiteC-2.9.0.tar.gz. Let me know if it doesn't work.

**Comment by dfed** [comment]
Hi @yishuangP! Thank you for your work on this, and I appreciate your re-opening this issue.

I tried adding the following `binaryTarget` to a `Package.swift` file as a `target`:
```
.binaryTarget(
    name: "TensorFlowLiteC",
    url: "https://dl.google.com/tflite-release/ios/prod/tensorflow/lite/release/ios/release/15/20220517-175828/TensorFlowLiteC/2.9.0/c88775ef9b845ba7/TensorFlowLiteC-2.9.0.tar.gz",
    checksum: "03acd48ec2a40b90b8572b3725e7c3cded2d402c")
```

I generated the checksum by running `shasum` on the downloaded `tar.gz` file (if this is the intended distribution mechanism, the checksum should likely be added to documentation somewhere).

However, when I tried to build the project I got the following error:
> unsupported extension for binary target 'TensorFlowLiteC'; valid extensions are: 'zip'

I'm also curious: is there a plan to release the `TensorFlowLiteSwift` package as an XCFramework (or Swift Package)?

**Comment by dfed** [comment]
I've created a sample Swift Package repo you can play with here:
[TensorFlowLitePackageTest.zip](https://github.com/tensorflow/tensorflow/files/9550660/TensorFlowLitePackageTest.zip)

Once you unzip it, you'll need to put the unarchived `TensorFlowLiteC-2.9.0` folder in the same directory as the `Package.swift`

**Comment by yishuangP** [comment]
Hi Dan, really sorry that you have to download the `tar.gz` file and unpack it to use it in Swift package. Hopefully we'll release it as Swift package soon. For `TensorFlowLiteSwift`, we just publish the sources and it depends on other XCFrameworks (like `TensorFlowLiteC`). Eventually we'll release it as Swift package.

**Comment by dfed** [comment]
Makes sense to me! Looking forward to the `TensorFlowLiteSwift` Swift Package, but can start playing with building-from-source and utilizing an XCFramework in the meantime. Thank you for the explanation – again, I appreciate your work on this!

**Comment by arctop-sk** [comment]
Hi. I was wondering if there is any progress on this? specifically, an official URL that we can add as a depndency that holds the latest stable release in XCFramework form? or perhaps any updats on where you stand as far as adding SPM support?

**Comment by mcmurrym** [comment]
Can we get an update on this? As more time passes the need for this library to be available as Swift Package grows.

**Comment by aniketinfocusp** [comment]
+ 1

**Comment by arctop-sk** [comment]
+10000

**Comment by coolioxlr** [comment]
+1

**Comment by arctop-sk** [comment]
> I've created a sample Swift Package repo you can play with here: [TensorFlowLitePackageTest.zip](https://github.com/tensorflow/tensorflow/files/9550660/TensorFlowLitePackageTest.zip)
> 
> Once you unzip it, you'll need to put the unarchived `TensorFlowLiteC-2.9.0` folder in the same directory as the `Package.swift`

I'm trying to create something like this for an app I'm working on. I can import this properly, and get it to build, but it seems to have an issue with installation. I'm not sure if this is a signing issue or what not. Have you managed to actually get this working in an app and not just as a package?

**Comment by dfed** [comment]
> > I've created a sample Swift Package repo you can play with here: [TensorFlowLitePackageTest.zip](https://github.com/tensorflow/tensorflow/files/9550660/TensorFlowLitePackageTest.zip)
> > Once you unzip it, you'll need to put the unarchived `TensorFlowLiteC-2.9.0` folder in the same directory as the `Package.swift`
> 
> @dfed
> 
> I'm trying to create something like this for an app I'm working on. I can import this properly, and get it to build, but it seems to have an issue with installation. I'm not sure if this is a signing issue or what not. Have you managed to actually get this working in an app and not just as a package?

I've only tried this in a package – I'm still using Cocoapods for this part of my app.

**Comment by arctop-sk** [comment]
> > > I've created a sample Swift Package repo you can play with here: [TensorFlowLitePackageTest.zip](https://github.com/tensorflow/tensorflow/files/9550660/TensorFlowLitePackageTest.zip)
> > > Once you unzip it, you'll need to put the unarchived `TensorFlowLiteC-2.9.0` folder in the same directory as the `Package.swift`
> > 
> > 
> > @dfed
> > I'm trying to create something like this for an app I'm working on. I can import this properly, and get it to build, but it seems to have an issue with installation. I'm not sure if this is a signing issue or what not. Have you managed to actually get this working in an app and not just as a package?
> 
> I've only tried this in a package – I'm still using Cocoapods for this part of my app.

Ok Thanks.

@yishuangP and the rest of the team. There seems to be overwhelming need to allow users to pull these packages via SPM. What can we do to get this up and running? all we really need is a way to declare this as a dependancy so we can distribute our own packages.

Unfotunately trying to add the xcframeworks as binaryTargets will compile, but fails to install on device, with obscure errors.

**Comment by mmaetzler** [comment]
+1

All our other dependencies are handled via SPMs packages and tflite is our last cocoapods link. Is there anything the community here can do to support? As previous posters already said: there is an overwhelming need to pull in those packages via SPM. This ticket was opened 895 days ago and has lots of reactions, upvotes, and community members that have offered their help. It would be great to find a solution for this.

**Comment by arctop-sk** [comment]
@mmaetzler and others. I have put together a package, which builds but won't install onto a device for some obscure reason. If anyone wants to try and tackle this, so that we might have a community workaround for now:

https://github.com/arctop/TensorFlowLiteSwiftPackage

Right now, I've just copied over the files from TF that are needed. If we can get it to run, we can add some automation to pull the latest releases and what not.

**Comment by iuriipleskach** [comment]
@arctop-sk, did you manage to fix the issue? Tried your approach and got the code signing issue.
I plan to try to codesign tensorflow xcframeworks manually, have you tried this approach?

**Comment by arctop-sk** [comment]
> @arctop-sk, did you manage to fix the issue? Tried your approach and got the code signing issue.
> I plan to try to codesign tensorflow xcframeworks manually, have you tried this approach?

Nope. I haven't continued down this path due to time restrictions. 

If you manage to properly sign and run that, please let us know. Might also have an issue getting this archived and validated for the store, so I would test that. 

Good luck!

**Comment by iuriipleskach** [comment]
Unfortunately, no luck with signing the xcframework manually. 
As far as I understood, the issue is that frameworks for a particular architecture are missing Info.plist. I've tried adding those and got another code-sign validation error.

**Comment by adammasyk** [comment]
+1

**Comment by wcappel** [comment]
+1

**Comment by arctop-sk** [comment]
@pkgoogle @yishuangP  This is absolutly nonsensical. 

A feature request that has been open for 3 years, isn't even a big feature or a development of any sort of core functionality, but rather just a bit of putting together an automated script and a wrapper, uploading it here, and releasing us all from these workarounds.

There are a dozen of engineers here, that with the proper access and support will HAPPILY do the work and contribute. In fact some of us have already spent hours trying to work this for the good of the community.

Furthermore, the lack of communication of something that is trivial, with anyone from the team not having updated or participated in this thread for almost a full year, is downright unacceptable.

**Comment by teonicel** [comment]
Maybe this can help you https://github.com/kewlbear/TensorFlowLiteC

**Comment by yomw** [comment]
@pkgoogle @yishuangP Is there a way to get an official response from the team? Even just to say "Sorry we won't do anything for the time being" (though an ETA would be much appreciated). This issue has been tagged with "Awaiting tensorflower" for 4 months now...

**Comment by imyrvold** [comment]
+1

**Comment by teonicel** [comment]
If you manage to export the current pod as .xcframework making it a SPM is very easy

**Comment by arctop-sk** [comment]
> If you manage to export the current pod as .xcframework making it a SPM is very easy

It is very easy to roll out your own SPM. 

Problem is that won't correctly sign and you cannot deploy that to the App Store. 

Works great in debug but useless in actual apps.

**Comment by jnelle** [comment]
+1

**Comment by mariomastrandrea-poli** [comment]
+1

**Comment by tareksabry1337** [comment]
Is there any hope to have SPM anytime in the future?

**Comment by tareksabry1337** [comment]
I gave up on TensorFlow creating SPM, I created my own SPM repo that passes code signing issues in App Store and uploads just fine https://github.com/tareksabry1337/TensorFlowLiteC

**Comment by yomw** [comment]
@tareksabry1337 Could you elaborate on how you did it? Maybe the guys here will try and implement it if they have the solution (if anyone at tensorflow actually still reads this thread - cc @yishuangP)

**Comment by arcslash** [comment]
+1

**Comment by Bryanlin920616** [comment]
+1

**Comment by wannafedor4** [comment]
+54

**Comment by vijaytholpadi** [comment]
+1

Can we get an update on this please? 

It's been quite a while since SPM has been out.

**Comment by r-a-o** [comment]
Can we please add SPM support to at least Tensorflow Lite Swift [https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/swift]

Since everyone is now starting to use SPM and dropping cocoapods, this will really help all iOS devs. 

(Its been 4years since the issue was opened and I am willing to help)

Thanks!

Attn: @yyoon @yishuangP @pkgoogle

**Comment by vijaytholpadi** [comment]
Literally having to choose CoreML because of this limitation. 

SPM support is more critical to iOS ecosystem than it might seem. 

CocoaPods has gone into maintenance mode earlier this year and we will only see more people move to SPM from here on as that's the only option around with an actual feature and maintenance roadmap.

**Comment by mmaetzler** [comment]
I wonder if [this SPM issue](https://forums.swift.org/t/swiftpm-with-git-lfs/42396/) is part of the reason why there is no SPM yet? I think it would be impossible at the moment to bundle the binary frameworks inside the SPM because of that issue.

**Comment by tareksabry1337** [comment]
@mmaetzler I literally packaged TensorFlow under SPM and it's currently in app that's on the AppStore, I can't fathom why such simple request is being completely ignored.

**Comment by mmaetzler** [comment]
@tareksabry1337 I did the same. I have an app submitted to the store with my own (internal) tflite SPM. But I was not able to create an SPM with `TensorFlowLiteSelectOps` because the binary size requires us to use git lfs and SPM does not support git lfs files. So if your model requires a good chunk of the select ops, then you are out of luck.

**Comment by r-a-o** [comment]
@pkgoogle Continuing the conversation here as you suggested, https://github.com/tensorflow/tensorflow/issues/78787#issuecomment-2448261271

Could you please tell us if we can expect this to be resolved in the next 6 months? Its crazy that after 4 years and so many developers requesting & waiting for so long, there is no clarity. There must be some valid reason for this, right? 
If there is a reason, please let us know so we don't waste each other's time.
Thanks.

**Comment by pkgoogle** [comment]
HI @lothrop,

Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress [here](https://github.com/google-ai-edge/LiteRT/issues/125).

Let us know if you have any questions. Thanks.

**Comment by nmn28** [comment]
> [@pkgoogle](https://github.com/pkgoogle) Continuing the conversation here as you suggested, [#78787 (comment)](https://github.com/tensorflow/tensorflow/issues/78787#issuecomment-2448261271)
> 
> Could you please tell us if we can expect this to be resolved in the next 6 months? Its crazy that after 4 years and so many developers requesting & waiting for so long, there is no clarity. There must be some valid reason for this, right? If there is a reason, please let us know so we don't waste each other's time. Thanks.

my guess is because google doesnt want to help people build on ios.

**Comment by FaceAISDK** [comment]
[叹气]
