### ISSUE TITLE
Could not find a version that satisfies the requirement tensorflow (from versions: none)

### ISSUE THREAD

**Issue by H-111-di** [tensorflow/tensorflow#44615]
System information

* OS Platform and Distribution: masOS Big Sur
* TensorFlow installed from (source or binary): binary
* TensorFlow version: none
* Python version: 3.8.2
* Installed using virtualenv? pip? conda?: virtualenv + pip

Describe the problem
Could not find a version that satisfies the requirement tensorflow (from versions: none)

Provide the exact sequence of commands / steps that you executed before running into the problem
```bash
➜  ~ python -m pip install --upgrade tensorflow
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensor flow
```
```bash
➜  ~ python3 -m pip install --upgrade tensorflow==2.3.0                                        
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement tensorflow==2.3.0 (from versions: none)
ERROR: No matching distribution found for tensorflow==2.3.0
```

**Comment by H-111-di** [comment]
I was able to install and run Tensorflow before I upgrade to Big Sur.
Then I installed the beta version, the environment still exist but it just can't run any thing so I tried reinstalled the whole thing again.(Though later I noticed the installation renewed the PATH setting, I had already uninstalled Tensorflow.)
Then this error occurred.

**Comment by ravikyram** [comment]
@H-111-di 

Please, refer similar issue #39130
Please, uninstall everything and then install in new environment.

```
Step 1: pip install -U pip
Step 2: pip install -U setuptools
Step 3: pip install tensorflow
```

TensorFlow 2 packages require a pip version >19.0. Could you please upgrade pip using the below command and let us know if it works.

pip install --upgrade pip.

For more information please check this [TensorFlow guide](https://www.tensorflow.org/install#download-a-package). Thanks!

**Comment by H-111-di** [comment]
Well, It didn't make any changes.

```bash
➜  ~ python -m pip install -U setuptools             
Defaulting to user installation because normal site-packages is not writeable
Requirement already up-to-date: setuptools in ./Library/Python/3.8/lib/python/site-packages (50.3.2)
```
```bash
➜  ~ python -m pip install -U pip          
Defaulting to user installation because normal site-packages is not writeable
Requirement already up-to-date: pip in ./Library/Python/3.8/lib/python/site-packages (20.2.4)
```

And I'm not running on a 32bit python
```bash
➜  ~ python3 -c "import platform; print(platform.architecture())"                              
('64bit', '')
```

Also I can't install it through wheel files.
```bash
➜  ~ python -m pip install ~/Downloads/tensorflow-2.3.1-cp38-cp38-macosx_10_14_x86_64.whl
Defaulting to user installation because normal site-packages is not writeable
ERROR: tensorflow-2.3.1-cp38-cp38-macosx_10_14_x86_64.whl is not a supported wheel on this platform.
```

**Comment by H-111-di** [comment]
Ummm, I tried the homebrew install version(both 3.7.9 and 3.8.6) and it works fine... But the requirements system in the homebrew seems to be something hardcoded and you can't upgrade anything it included... 
So it seems like Apple had done something to their new system or the preinstalled python3.8 and that didn't meet the requirements of Tensorflow.

**Comment by ravikyram** [comment]
@H-111-di 

Could you please install python 3.8 from https://www.python.org/downloads/mac-osx/ and see if the issue still persists.Thanks!

**Comment by ShadyAbuKalam** [comment]
@ravikyram,
I have the same problem with system python 3.8.2 and pyenv. 

I tried your suggestion to install Python 3.8.6 from the python.org website and it worked.

I think pyenv may need specialized instructions to work with TF.

**Comment by H-111-di** [comment]
> @H-111-di
> 
> Could you please install python 3.8 from https://www.python.org/downloads/mac-osx/ and see if the issue still persists.Thanks!

sorry for late reply. That works fine for me and I think the issue get solved and I can get pretty much everything work now.
Thanks a lot for your suggestions.

**Comment by Hossamfathi050** [comment]
pip install tensorflow

**Comment by jsoneaday** [comment]
I have this issue with python 3.10.10 on m1

**Comment by RAQEEB212** [comment]
also I have same issue in mcbook m2

**Comment by kuziechambers** [comment]
also have this issue with python3.10.11 on M1. have tried all of the resolutions

**Comment by A-Singh15** [comment]
issue resolved 

pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl

**Comment by riza-m** [comment]
> issue resolved
> 
> pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl

makasih bang
