### ISSUE TITLE
Convert Tensorflow model to TFLite model - problem with boxes after quantization

### ISSUE THREAD

**Issue by Rariusz** [tensorflow/tensorflow#44610]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google colab
- TensorFlow installed from (source or binary): source 
- TensorFlow version (or github SHA if from source): tf-nightly==2.5.0.dev20201104

I am currently working on converting a tensorflow model to a TFLite model. By helping people from the Tensorflow community, in particular @amahendrakar.  Currently, after many attempts, I am able to convert the tensorflow model to the TFLite model
However, there was another problem with my work. Description of the problem:

**STEP 1**
In the first step, I download the ```ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8``` model and I run object detector for test image. Result (Everything is OK  but colors on the image are different than in original image):
![p1](https://user-images.githubusercontent.com/28406311/98230792-dcb0ee80-1f5b-11eb-954c-ee48938fe982.jpg)

**STEP 2**
Export model to tflite graph using
```
!python object_detection/export_tflite_graph_tf2.py \
    --pipeline_config_path "/content/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8/pipeline.config" \
    --trained_checkpoint_dir "/content/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8/checkpoint"\
    --output_directory "/content/tflite_graph"
```
and convert tflite graph to tflite file using
```
converter = tf.lite.TFLiteConverter.from_saved_model('/content/tflite_graph/saved_model')
tflite_model = converter.convert()

with open('/content/tflite_model/model.tflite', 'wb') as f:
  f.write(tflite_model)
```
Run object detector. Result (Everything is OK):
![p2](https://user-images.githubusercontent.com/28406311/98231056-35808700-1f5c-11eb-8114-425909f24bfe.jpg)

**STEP 3**
Convert tflite graph to tflite file with ```tf.lite.Optimize.DEFAULT```:
```
converter = tf.lite.TFLiteConverter.from_saved_model('/content/tflite_graph/saved_model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
model_quantization_1 = converter.convert()

with open('/content/tflite_model/model_quantization_1.tflite', 'wb') as f:
  f.write(model_quantization_1)
```
Run object detector. Result (Everything is OK):
![p3](https://user-images.githubusercontent.com/28406311/98231389-a758d080-1f5c-11eb-86b9-8d3ef85fbd51.jpg)

**STEP 4**
Convert tflite graph to tflite file with quantization:
```
converter = tf.lite.TFLiteConverter.from_saved_model('/content/tflite_graph/saved_model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
converter.representative_dataset = representative_data_gen
model_quantization_2 = converter.convert()

with open('/content/tflite_model/model_quantization_2.tflite', 'wb') as f:
  f.write(model_quantization_2)
```
Run object detector. Result:
![p4](https://user-images.githubusercontent.com/28406311/98231549-d707d880-1f5c-11eb-9e1a-2862bd6deb46.jpg)

As we can see the is a problem with boxes. The size od model is the same after run ```converter.convert()``` but there is a problem with boxes. Nest step will be run final TFLite model in google coral but now I would like to solve the current problem. 

Full code to reproduce the problem: 
[ssd_modilenet_to_google_coral_step_1](https://colab.research.google.com/drive/1UBikIZmoJTuxWMXhyggBugM6dF7AWK4c?usp=sharing)

I'm not sure, but it seems to me that the problem lies in the ````representative_data_gen()``` function and in the preprocessing of the imege in the object detector.

But, there is one but. If i run model from step 2 the calculation are very fast unlike of step 3 and 4.

**Comment by Saduf2019** [comment]
@Rariusz 
Could you please share the colab link mentioned in the issue.

**Comment by Rariusz** [comment]
@Saduf2019  [ssd_modilenet_to_google_coral_step_1](https://colab.research.google.com/drive/1UBikIZmoJTuxWMXhyggBugM6dF7AWK4c?usp=sharing)

**Comment by Saduf2019** [comment]
I ran the code and able to replicate the issue, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/938d85ea70a041e963dd37209398d222/untitled465.ipynb).

**Comment by Rariusz** [comment]
@Saduf2019 Thanks!!!. Any idea why there is a problem with boxes after full discretization? In addition, I believe that the model is not fully discretized because there are warnings after discretization.

**Comment by srjoglekar246** [comment]
@Rariusz You need to set this to get the full benefits of quantization:

```
  converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8,
                                                                  tf.lite.OpsSet.TFLITE_BUILTINS]
```

And indeed, there might be issues between the preprocessing done in your representative dataset, and your inference code. To be safest, you can use [this function](https://github.com/tensorflow/models/blob/master/research/slim/preprocessing/inception_preprocessing.py#L258) for both the representative dataset & during inference.
