### ISSUE TITLE
Tutorials documentation spelling mistake

### ISSUE THREAD

**Issue by tusharsoni08** [tensorflow/tensorflow#4461]
At url: https://www.tensorflow.org/versions/r0.10/tutorials/image_recognition/index.html

I've found that In following paragraph '299 pixel **high**' is written, which I think should be '299 pixel **hight**'

The whole paragraph is following in 'Usage with the C++ API' section:

"This gives us a vector of Tensor objects, which in this case we know will only be a single object long. You can think of a Tensor as a multi-dimensional array in this context, and it holds a 299 pixel **high**, 299 pixel width, 3 channel image as float values. If you have your own image-processing framework in your product already, you should be able to use that instead, as long as you apply the same transformations before you feed images into the main graph."

**Comment by jmchen-g** [comment]
Thanks. I guess you mean height but feel free to send over a PR for this.

**Comment by tusharsoni08** [comment]
I've applied for Google CLA, after approving I'll make PR for this. thanks.
