### ISSUE TITLE
Where is the TRTEngine saved? 

### ISSUE THREAD

**Issue by ysyyork** [tensorflow/tensorflow#44611]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
source
- TensorFlow version (use command below):
2.3.0
- Python version:
3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
11.1
- GPU model and memory:

I followed this answer https://stackoverflow.com/a/60744486/3265888 on stackoverflow and expect to see TRTEngine being serialized into the assets folder. I followed the doc here: https://www.tensorflow.org/api_docs/python/tf/experimental/tensorrt/Converter and used the `convert.build(input_fn)` method and everything execute without error. But when I check the savedmodel, assets folder is empty. Also when I try to run that model on jetson, the loading takes really long so I'm guessing it's generating TRTEngine on the fly? Is it a bug? or what's the correct expectation should be? 

Apart from the above, I also don't know if the `maximum_cached_engines` option takes effect or not cus when I loaded the model and do inference, when I dynamically change the input shape (the batch_size), it seems it cached more than 1 even I'm using 1 for that option cus the second inference with that batch size is much faster than the first one. I'm not sure if batch size is counted as different shape? or only the actual shape counts as that? 

This is how I load the model and do inference:
```
  saved_model_loaded = tf.saved_model.load(
      trt_model_dir, tags=[tag_constants.SERVING])
  graph_func = saved_model_loaded.signatures[
      signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
  graph_func = convert_to_constants.convert_variables_to_constants_v2(graph_func)

  graph_func(input)
```

**Comment by amahendrakar** [comment]
@ysyyork,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!
