### ISSUE TITLE
Slow Interpreter creation with GpuDelegate option

### ISSUE THREAD

**Issue by Demin92** [tensorflow/tensorflow#44612]
I use TFLite 2.3.0 on Android device

**System information**
- Mobile device Xiaomi Redmi 5, GPU: Adreno(TM) 506

TensorFlow libraries imported in standard way: 
```
    implementation 'org.tensorflow:tensorflow-lite:2.3.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.3.0'
```
Instance creation:

```
    init {
        val options = Interpreter.Options().apply {
            if (compatList.isDelegateSupportedOnThisDevice) {
                addDelegate(GpuDelegate(compatList.bestOptionsForThisDevice))
            } else {
                setNumThreads(DEFAULT_THREADS_COUNT)
                setUseNNAPI(DEFAULT_USE_NNAPI_OPTIONS)
            }
        }
        interpreter = Interpreter(loadModelFile(model), options)
    }

    private fun loadModelFile(data: ByteArray): ByteBuffer {
        return ByteBuffer.allocateDirect(data.size).put(data).order(ByteOrder.nativeOrder())
    }
```

**Describe the current behavior**
`Interpreter(loadModelFile(model), options)` takes 2400ms with GpuDelegate instead of several hundreds ms without it. I have measured `loadModelFile(model)` separately and this fun did not takes significant time.

**Describe the expected behavior**
I do not know, may be it is normal but it is not so convenient that instance creation takes so much time, all performance improvement that get from gpu using leveled by this delay.

**Comment by teijeong** [comment]
Hi @Demin92,

The delay is expected to compile GPU shader, especially when your model is big. :( Preparing the interpreter while the app starts, and using it later would make the delay much less visible to the user.

@srjoglekar246 can you add some points?

**Comment by srjoglekar246** [comment]
+1 to what @teijeong  said.

Ensure that you are initializing the interpreter only once during init, since the shader compiling unfortunately does take some time.

For this reason, the GPU delegate is appropriate when the number of inferences are more than a few, to offset the extended compilation time :-). If this isn't true for your case, maybe increasing the number of threads to the CPU kernels (using `SetNumThreads`) might be more useful.

**Comment by Demin92** [comment]
Ok, thanks for your advices, I will try it)
