### ISSUE TITLE
Plans to release 2.4.0 as a stable release?

### ISSUE THREAD

**Issue by hsheimbuch** [tensorflow/tensorflow#44616]
Hello, I was just wondering if a date when 2.4.0 will be released as a stable version is currently available?

**Comment by mihaimaruseac** [comment]
As in every other release, we try to have at least 2 RCs before the final release. Each RC is triggered at least a week from the previous one.

**Comment by mihaimaruseac** [comment]
RC1 was just released. Depending on amount of cherrypicks and issues discovered, there might be a 2.4 final release around Thanksgiving.

**Comment by mihaimaruseac** [comment]
Due to some delays, RC2 will be released this week (likely tomorrow) and final release will come after Thanksgiving.

**Comment by mihaimaruseac** [comment]
RC3 was released yesterday. Final release will happen next week if testing does not reveal more issues.

**Comment by mihaimaruseac** [comment]
Final release should come this week or the next.

**Comment by mihaimaruseac** [comment]
TF 2.4 has been released (forgot to notify the thread at the time). Closing this
