### ISSUE TITLE
cuDNN LSTMs not utilized after loading a model using `tf.saved_model.load`

### ISSUE THREAD

**Issue by TobiasGruening** [tensorflow/tensorflow#44624]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Ubuntu 16.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **2.3.1**
- Python version: **3.7**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: **10.1/7.6.2**
- GPU model and memory: **GeForce GTX 1080 Ti computeCapability: 6.1 coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 10.92GiB deviceMemoryBandwidth: 451.17GiB/s**

**Describe the current behavior**

Training a (keras) LSTM model on GPU utilizes (as expected) the cuDNN version of the LSTM cells.
After saving this model using `tf.saved_model.save` and reloading it using `tf.saved_model.load`, it utilizes the 
NON cuda optimized LSTM cells in inference. (loading it using `tf.keras.models.load_model` it is utillizing the cuDNN cells)

**Describe the expected behavior**

The save/load process shouldn't change the graph. The model should use the same cells as in training after save/load.  I know that I can't expect the same functionality as if I use the higher level keras load/save methods. Consequently, it is acceptable if the automatic device detection does not work. However, it is highly not expected that the used cells change after save/load. If the automatic device detection is not supported, the cells, which were active at the moment of saving, should be loaded by default. Like it is now, it is not possible to create a saved_model in a straightforward way which utilizes the cuDNN cells, if NOT loaded using keras (which is not possible in other APIs: cc, java, ...)

**Standalone code to reproduce the issue**

```python
import os
import time
import shutil

import tensorflow as tf
from tensorflow import keras

assert len(tf.config.list_physical_devices('GPU'))>0, "You have to run this on a GPU machine, otherwise you do not see the effect."
print(tf.config.list_physical_devices('GPU'))

model_save_path='tmp'

lstm_layer = keras.layers.LSTM(64, input_shape=(None, 28))
model = keras.models.Sequential([lstm_layer, keras.layers.Dense(10)])

mnist = keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model.compile(loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
        optimizer="sgd", metrics=["accuracy"])
model.fit(x_train[0:128], y_train[0:128], validation_data=(x_test, y_test), batch_size=64, epochs=1)
tf.saved_model.save(model, model_save_path)

# Keras load + inference
model_reload_keras = tf.keras.models.load_model(model_save_path)
inp = tf.ones(shape=[8, 512, 28])
for i in range(501):
    # Avoid load offset.
    if i == 1:
        startT = int(round(time.time() * 1000))
    model_reload_keras.predict_on_batch(inp)
endT = int(round(time.time() * 1000))
print('Keras load -- inference time: ' + str(endT-startT) + 'ms')

# TF load + inference
model_reload_tf = tf.saved_model.load(str(model_save_path))
infer = model_reload_tf.signatures['serving_default']
for i in range(501):
    # Avoid load offset.
    if i == 1:
        startT = int(round(time.time() * 1000))
    infer(inp)
endT = int(round(time.time() * 1000))
print('TF load -- inference time (should be as fast as previous run [on GPU]): ' + str(endT - startT) + 'ms')

shutil.rmtree(model_save_path)
```

Kind regards & Thanks
Tobias

**Comment by Saduf2019** [comment]
@TobiasGruening 
I ran the code shared, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/6595185b4ca9dab658afb14d74b09eb9/untitled458.ipynb) as i see a different issue

**Comment by TobiasGruening** [comment]
> @TobiasGruening
> I ran the code shared, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/6595185b4ca9dab658afb14d74b09eb9/untitled458.ipynb) as i see a different issue

Thanks for your time. I have fixed a little error in the code above. 
Additionally, I added an assertion, because it is mandatory to run the test on a GPU machine to reproduce the effect.

**Comment by TobiasGruening** [comment]
We also reproduced the behaviour in the nightly build:
```
Keras load -- inference time: 7024ms (seems to use cuDNN cells)
TF load -- inference time (should be as fast as previous run [on GPU]): 46187ms (seems NOT to use cuDNN cells)
```
Kind regards,
Tobias

**Comment by jvishnuvardhan** [comment]
@TobiasGruening I updated two lines in your code to save and load a Keras model (instead of saving and loading Tensorflow model).

```
# tf.saved_model.save(model, model_save_path)
model.save(model_save_path)

# Keras load + inference
# model_reload_keras = tf.saved_model.load(model_save_path)
model_reload_keras = tf.keras.models.load_model(model_save_path)

```

With the above modification, I see the following results. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/d7560fc947a810fc048584b2c6f57b8c/untitled458.ipynb)

```
Keras load -- inference time: 4891ms
TF load -- inference time: 3440ms
```

Please let me know what you think. Please close the issue if this was resolved for you. Thanks!

**Comment by TobiasGruening** [comment]
@jvishnuvardhan Thanks for your time. Please have a look at the code in my initial post. I already updated these lines of code there. But this is NOT my issue. My issue is the time discrepancy, if running this test on a GPU machine!
If you copy my code to your gist you will get an assertion if not running on a GPU. If running the test on a GPU you will get significantly DIFFERENT inference times. This is because the cuDNN LSTM cells are not used if loading the model using TensorFlow load, which is not as expected. Furthermore, the solution is NOT (as described in my initial post) to load the model using Keras. It is about the behavior of the TensorFlow save and load which is CHANGING the graph!

Kind regards,
Tobias

**Comment by TobiasGruening** [comment]
Any news on this?

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tensorflow GPU 2.5, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/ba7a1fb127f74876b0773426929f7a28/44624.ipynb). Thanks!

**Comment by sachinprasadhs** [comment]
After Tensorflow 2.5 version, loading and saving model is not suggested using `saved_model`. Instead use `model.save(model_save_path)` & `tf.keras.models.load_model(model_save_path)`.
Please go though the warning message in the gist [here](https://colab.sandbox.google.com/gist/sachinprasadhs/ba7a1fb127f74876b0773426929f7a28/44624.ipynb#scrollTo=bN89NfaLnlr-) for more details, also you can notice the improved inference time in the Tensorflow version 2.9.
