### ISSUE TITLE
Tensorflow 2.3.1 is not compatible with cuda 10.2 on Windows

### ISSUE THREAD

**Issue by spindensity** [tensorflow/tensorflow#44622]
**System information**

- OS Platform: Windows 20H2 19042.572 64bit;
- TensorFlow installed from (source or binary): source;
- TensorFlow version: 2.3.1;
- Python version: 3.8.6 64bit;
- Bazel version (if compiling from source): 3.1.0;
- Compiler version: MSVC 2019 16.7.7
- CUDA/cuDNN version: CUDA 10.2 with cuDNN 7.6.5.

**Describe the problem**

Build failed with cuda support:

**Any other info / logs**

```
.\tensorflow/core/kernels/cuda_sparse.h(39): error: identifier "cusparseDnMatDescr_t" is undefined

.\tensorflow/core/kernels/cuda_sparse.h(40): error: identifier "cusparseSpMatDescr_t" is undefined

.\tensorflow/core/kernels/cuda_sparse.h(41): error: identifier "cusparseSpMMAlg_t" is undefined

tensorflow/core/kernels/tridiagonal_solve_op_gpu.cu.cc(98): warning: extra ";" ignored

3 errors detected in the compilation of "C:/Users/SPINDE~1/AppData/Local/Temp/nvcc_inter_files_tmp_dir/tmp3nb_ygoq/tridiagonal_solve_op_gpu.cu.cpp1.ii".
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 6783.098s, Critical Path: 4048.81s
INFO: 5532 processes: 5532 local.
FAILED: Build did NOT complete successfully
```

**Analysis**

These problematic symbols are used in `tensorflow/core/kernels/cuda_sparse.h` (line 38-42): 

```cpp {.line-numbers}
#if CUDA_VERSION >= 10020
using gpusparseDnMatDescr_t = cusparseDnMatDescr_t;
using gpusparseSpMatDescr_t = cusparseSpMatDescr_t;
using gpusparseSpMMAlg_t = cusparseSpMMAlg_t;
#endif
```

But in cuda 10.2 `cusparse.h` (`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include\cusparse.h`), these symbols are defined in a `#if !defined(_WIN32) ... #endif` block (line 7341-7386, 7700):

```cpp
//##############################################################################
//# SpMM APIs
//##############################################################################

#if !defined(_WIN32)

typedef enum {
    CUSPARSE_MM_ALG_DEFAULT = 0,
    CUSPARSE_COOMM_ALG1 = 1, // non-deterministc results
    CUSPARSE_COOMM_ALG2 = 2, // deterministic results
    CUSPARSE_COOMM_ALG3 = 3, // non-deterministc results, for large matrices
    CUSPARSE_CSRMM_ALG1 = 4
} cusparseSpMMAlg_t;

typedef struct cusparseSpMatDescr* cusparseSpMatDescr_t;
typedef struct cusparseDnMatDescr* cusparseDnMatDescr_t;

#endif // !defined(_WIN32)
```

According to the [Microsoft documentation](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-160):

```
_WIN32 Defined as 1 when the compilation target is 32-bit ARM, 64-bit ARM, x86, or x64. Otherwise, undefined.
```

So these symbols are not defined when the compilation target is x64 on Windows and the build always fails.

By the way, the latest version in `master` branch has the same problem.

**Comment by amahendrakar** [comment]
@spindensity,
Could you please provide the exact sequence of commands / steps that you executed before running into the problem.

Also, check if you are facing the same issue with CUDA 10.1 as well? Thanks!

**Comment by spindensity** [comment]
> @spindensity,
> Could you please provide the exact sequence of commands / steps that you executed before running into the problem.
> 
> Also, check if you are facing the same issue with CUDA 10.1 as well? Thanks!

@amahendrakar 

Thanks.

As the above source code referred (`tensorflow/core/kernels/cuda_sparse.h`, line 38-42), TensorFlow does NOT use these symbols at all when building with CUDA 10.1: 

```cpp
#if CUDA_VERSION >= 10020
using gpusparseDnMatDescr_t = cusparseDnMatDescr_t;
using gpusparseSpMatDescr_t = cusparseSpMatDescr_t;
using gpusparseSpMMAlg_t = cusparseSpMMAlg_t;
#endif
```

So CUDA 10.1 is OK and I have built TensorFlow 2.3.1 with it (CUDA 10.1) successfully:

The problem is these symbols are NEVER defined in CUDA 10.2 `cusparse.h` when the compilation target is x64 on Windows as my first post said, I think it's a bug of TensorFlow.

The commands I used are exactly the same as the instructions of the [official documentation](https://www.tensorflow.org/install/source_windows) and here is the `.tf_configure.bazelrc`:

```
build --action_env PYTHON_BIN_PATH="C:/Dev/BasicTools/python/virtualenvs/tf_build/Scripts/python.exe"
build --action_env PYTHON_LIB_PATH="C:/Dev/BasicTools/python/virtualenvs/tf_build/lib/site-packages"
build --python_path="C:/Dev/BasicTools/python/virtualenvs/tf_build/Scripts/python.exe"
build --config=xla
build --action_env CUDA_TOOLKIT_PATH="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="6.1"
build --config=cuda
build:opt --copt=/arch:AVX2
build:opt --define with_default_optimizations=true
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test:v1 --test_tag_filters=-benchmark-test,-no_oss,-no_windows,-no_windows_gpu,-no_gpu,-oss_serial
test:v1 --build_tag_filters=-benchmark-test,-no_oss,-no_windows,-no_windows_gpu,-no_gpu
test:v2 --test_tag_filters=-benchmark-test,-no_oss,-no_windows,-no_windows_gpu,-no_gpu,-oss_serial,-v1only
test:v2 --build_tag_filters=-benchmark-test,-no_oss,-no_windows,-no_windows_gpu,-no_gpu,-v1only
build --action_env TF_CONFIGURE_IOS="0"
```

**Comment by mihaimaruseac** [comment]
Can you send a patch to master please and then a cherrypick to r2.3?

CC @sanjoy

**Comment by sathibault** [comment]
This is still an issue on Windows 10 with versions 2.3.1 and 2.4.0-RC4 and CUDA 10.2.

**Comment by torqueNoFriction** [comment]
> This is still an issue on Windows 10 with versions 2.3.1 and 2.4.0-RC4 and CUDA 10.2.

Same over here, I even get multiple other errors as well. Any patch or recommendation for this yet ?

**Comment by sanjoy** [comment]
We don't support 10.2 (we moved directly to 11.0 from 10.1).  But I will approve minor PRs to make TF buildable against 10.2.

**Comment by ymodak** [comment]
Please refer TF and cuda compatibility chart https://www.tensorflow.org/install/source#gpu
Thanks!
