### ISSUE TITLE
TensorFlow 2.4 & roadmap

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#44623]
Hello,

It's been released ver. 2.4-rc0 of TensorFlow, can we expect ver.2.4.x this year?

Thank you.

**Comment by mihaimaruseac** [comment]
Most likely yes.

**Comment by ravikyram** [comment]
@peter197321 

Please, close this thread as your question has been answered. Thanks!

**Comment by mihaimaruseac** [comment]
RC1 was just released. Depending on amount of cherrypicks and issues discovered, there might be a 2.4 final release around Thanksgiving.

**Comment by mihaimaruseac** [comment]
Due to some delays, RC2 will be released this week (likely tomorrow) and final release will come after Thanksgiving.

**Comment by mihaimaruseac** [comment]
RC3 was released yesterday. Final release will happen next week if testing does not reveal more issues.

**Comment by peter197321** [comment]
Thank you for your support.

**Comment by mihaimaruseac** [comment]
Final release should come this week or the next.

**Comment by mihaimaruseac** [comment]
TF 2.4 has been released (forgot to notify the thread at the time). Closing this

**Comment by peter197321** [comment]
yes, thank you.
