### ISSUE TITLE
Move EthosU custom op out of AllOpsResolver

### ISSUE THREAD

**Issue by advaitjain** [tensorflow/tensorflow#44628]
@tensorflow/micro

The EthosU custom op https://github.com/tensorflow/tensorflow/blob/33dbf934d3758dfee07c0b5f6f4a6a00939b1b42/tensorflow/lite/micro/all_ops_resolver.cc#L86-L92

should ideally only be used for EthosU applications and not be part of the AllOpsResolver.

Creating this issue to figure out how we might achieve that.

**Comment by advaitjain** [comment]
This came up during the review of #43566 

tagging @mansnils @freddan80

**Comment by freddan80** [comment]
Thx, we'll have a look at this.

**Comment by advaitjain** [comment]
Based on https://github.com/tensorflow/tensorflow/pull/44968#pullrequestreview-533759643 my original intent of not having any mention of Ethos-U from AllOpsResolver was overkill given the current status (only a single target-specific op). We will revisit this in the future, but the refactor of #44968 is still good to have.

**Comment by freddan80** [comment]
It makes sense. I think we should revisit the idea of externalizing ethosu.cc. Should we keep this ticket open for the purpose?

**Comment by advaitjain** [comment]
sounds good, let's keep this ticket open.

**Comment by Saduf2019** [comment]
@advaitjain 
Is this still an issue.
