### ISSUE TITLE
TFLite quantization aware converter - 'std.constant' op requires attribute's type ('tensor<1x64xf32>') to match op's return type

### ISSUE THREAD

**Issue by somyamohanty** [tensorflow/tensorflow#44625]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): Source
- TensorFlow version (or github SHA if from source): 2.3.0

**Command used to run the converter or code if you’re using the Python API**
https://github.com/UNCG-DAISY/TinyDuneCollision/blob/master/src/TinyML_End_to_End.ipynb

See Quantization aware training

```
converter = tf.lite.TFLiteConverter.from_keras_model(quant_aware_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
```

**The output from the converter invocation**

```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
~/.virtualenvs/python3deep/lib/python3.5/site-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    198                                                  debug_info_str,
--> 199                                                  enable_mlir_converter)
    200       return model_str

~/.virtualenvs/python3deep/lib/python3.5/site-packages/tensorflow/lite/python/wrap_toco.py in wrapped_toco_convert(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
     37       debug_info_str,
---> 38       enable_mlir_converter)
     39 

Exception: /home/sdmohant/.virtualenvs/python3deep/lib/python3.5/site-packages/tensorflow/python/keras/layers/ops/core.py:53:0: error: 'std.constant' op requires attribute's type ('tensor<1x64xf32>') to match op's return type ('tensor<*xf32>')
/home/sdmohant/.virtualenvs/python3deep/lib/python3.5/site-packages/tensorflow/python/keras/layers/core.py:1198:0: note: called from
/home/sdmohant/.virtualenvs/python3deep/lib/python3.5/site-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize_wrapper.py:162:0: note: called from
/home/sdmohant/.virtualenvs/python3deep/lib/python3.5/site-packages/tensorflow/python/autograph/impl/api.py:302:0: note: called from
/home/sdmohant/.virtualenvs/python3deep/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py:985:0: note: called from
/home/sdmohant/.virtualenvs/python3deep/lib/python3.5/site-packages/tensorflow/python/keras/engine/functional.py:508:0: note: called from
/home/sdmohant/.virtualenvs/python3deep/lib/python3.5/site-packages/tensorflow/python/keras/engine/functional.py:386:0: note: called from
/home/sdmohant/.virtualenvs/python3deep/lib/python3.5/site-packages/tensorflow/python/keras/engine/sequential.py:372:0: note: called from
/home/sdmohant/.virtualenvs/python3deep/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py:985:0: note: called from
/home/sdmohant/.virtualenvs/python3deep/lib/python3.5/site-packages/tensorflow/python/keras/saving/saving_utils.py:134:0: note: called from
/home/sdmohant/.virtualenvs/python3deep/lib/python3.5/site-packages/tensorflow/python/keras/layers/ops/core.py:53:0: note: see current operation: %cst_13 = "std.constant"() {value = dense<[[0.000000e+00, -0.330023378, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, -0.330023378, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, -0.330023378, 0.000000e+00, 0.000000e+00, 0.330023378, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.282877177, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.282877177, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00]]> : tensor<1x64xf32>} : () -> tensor<*xf32>
```

**Model Summary**

![Screen Shot 2020-11-05 at 11 03 24 AM](https://user-images.githubusercontent.com/2720456/98265106-afae0d00-1f56-11eb-95ca-2d9f2126ff8b.png)

**Failure details**
Converter is not able to create TFLite model

**Comment by amahendrakar** [comment]
@somyamohanty,
On running the code, I am facing an error stating `FileNotFoundError: [Errno 2] No such file or directory: '../data/CollisionData/'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/be7f7ad79baad2a33e7f290349ecae5b/44625.ipynb). 

In order to expedite the trouble-shooting process, could you please provide all the supporting files required to run the code. Thanks!

**Comment by somyamohanty** [comment]
> @somyamohanty,
> On running the code, I am facing an error stating `FileNotFoundError: [Errno 2] No such file or directory: '../data/CollisionData/'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/be7f7ad79baad2a33e7f290349ecae5b/44625.ipynb).
> 
> In order to expedite the trouble-shooting process, could you please provide all the supporting files required to run the code. Thanks!

The data is a set of large images which cannot be uploaded to Github. Do you suggest some other way of providing it.

**Comment by somyamohanty** [comment]
Sorry for the inability to provide the raw data. I have changed the repository and the code to utilize publicly available dataset instead. Should be able to run now. But the issue still persists.

**Comment by amahendrakar** [comment]
@somyamohanty,
Sorry for the delayed response. I was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/5809cf01689e3e8c6de823c385f04af5/44625.ipynb#scrollTo=XICaRtaaYaaD).

However with the latest [TF-nightly](https://colab.research.google.com/gist/amahendrakar/0bf05f99df3a019a650a135697e67739/44625-tf-nightly.ipynb), I was able to convert the model without any issues. Please find attached gist. Thanks!

**Comment by somyamohanty** [comment]
> @somyamohanty,
> Sorry for the delayed response. I was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/5809cf01689e3e8c6de823c385f04af5/44625.ipynb#scrollTo=XICaRtaaYaaD).
> 
> However with the latest [TF-nightly](https://colab.research.google.com/gist/amahendrakar/0bf05f99df3a019a650a135697e67739/44625-tf-nightly.ipynb), I was able to convert the model without any issues. Please find attached gist. Thanks!

Thanks, will try it out.

**Comment by LucasStromberg** [comment]
I'm having the same problem. I also must use tf-gpu and can't just switch to tf-nightly due to cudnn/cuda dependencies.
