### ISSUE TITLE
Installation links in README.md is wrong

### ISSUE THREAD

**Issue by hholst80** [tensorflow/tensorflow#4463]
https://github.com/tensorflow/tensorflow#installation

The links to the nightly images are invalid and returns 404.

**Comment by hholst80** [comment]
https://github.com/tensorflow/tensorflow/issues/4416

**Comment by aselle** [comment]
@caisq. The GPU ones seem to still be broken and it has been 3 days since #4416 comment. Any thoughts?

**Comment by caisq** [comment]
The build is blocked by a single failing test that's taken a little long to fix. I'll tag it for now to let the build pass.

**Comment by caisq** [comment]
The GPU whl links should be working now.

**Comment by aselle** [comment]
@hholst80  please let us know if this resolves your problem so we can close the issue.

**Comment by MarkDaoust** [comment]
All the links except "Linux CPU-only" and "Android" are broken again.
The links are to 0.11.0rc0 while the actual most recent build from the history is 0.10.0

It looks like it's the same sort of issue, where there has been no passing build since the version number change.

**Comment by aselle** [comment]
@gunan, @caisq, was this related to the jenkins upgrade that caused breakage in our jenkins jobs?

**Comment by gunan** [comment]
No, this is a different issue.

This is due to the breakage in nightly builds.
Today CPU only nightly builds passed, so the links should now work.
Once the GPU builds also pass, we will update nightly links to be independent of release versions.

**Comment by gunan** [comment]
#4783 should fix mac-cpu links
