### ISSUE TITLE
tf-nightly container has CUDA error on 'docker run'

### ISSUE THREAD

**Issue by tjdurant** [tensorflow/tensorflow#44630]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04.6 LTS
- TensorFlow installed from (source or binary): Docker
- Docker image: tensorflow/tensorflow:nightly-gpu-jupyter
- GPU model and memory: GeForce GTX 108 / 261MiB / 11178MiB

**Describe the problem**
Error regarding CUDA>=11.0 when running most recent nightly container

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Dockerfile
```
FROM tensorflow/tensorflow:nightly-gpu-jupyter

RUN pip install -U pip

# install packages
RUN apt-get update -qq && apt-get install --no-install-recommends -y \    
    libsm6 \
    libxext6 \
    libxrender-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /tmp/
RUN pip install --requirement /tmp/requirements.txt
COPY . /tmp/

WORKDIR /tf/

CMD jupyter lab --ip=0.0.0.0 --notebook-dir=/tf --allow-root
```

requirements.txt
```
tensorflow-hub
imbalanced-learn==0.7.0
jupyterlab==2.1.2
opencv-python==4.2.0.34
pandas==1.0.3
Pillow==7.1.2
ptvsd==4.3.2
scikit-learn==0.23.2
scipy==1.4.1
seaborn==0.11.0
sklearn==0.0
xlrd==1.2.0
```

Build image
```
$ docker build --no-cache=true -t tf:tf-nightly .
```

Run container:
```
$ nvidia-docker run --rm -d -v /home:/tf -p 9896:8888 tf:tf-nightly
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Error:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"process_linux.go:413: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: requirement error: unsatisfied condition: cuda>=11.0\\\\n\\\"\"": unknown.
```

**Comment by amahendrakar** [comment]
@tjdurant,
The latest TF-nightly release required CUDA 11 and cuDNN 8. 

Could you please specify the CUDA and cuDNN version installed on your machine and check if you are facing the same error with CUDA 11 and cuDNN 8 as well? Thanks!

**Comment by tjdurant** [comment]
@amahendrakar , i'm sorry because I may have had a knowledge gap on this one. Is the CUDA version you're looking for the version on the local machine or in the Docker container? Or both?
