### ISSUE TITLE
False out of resource error for multi-gpu machine

### ISSUE THREAD

**Issue by devtronslab** [tensorflow/tensorflow#44637]
Tensorflow 2.3.1 on Nvidia Docker image `tensorflow/tensorflow:latest-gpu-jupyter` 

I can train an LSTM in a Jupyter notebook using 2-out-of-4 of my GPUs, but when I increase to 4 I get the following NCCL error:

```
InternalError: 4 root error(s) found.
  (0) Internal:  NCCL: unhandled system error. Set NCCL_DEBUG=WARN for detail.
	 [[node NcclAllReduce (defined at <ipython-input-17-7105c4ec4d5e>:2) ]]
  (1) Internal:  NCCL: unhandled system error. Set NCCL_DEBUG=WARN for detail.
	 [[node NcclAllReduce (defined at <ipython-input-17-7105c4ec4d5e>:2) ]]
	 [[GroupCrossDeviceControlEdges_1/Nadam/Nadam/update_0/Const/_529]]
  (2) Internal:  NCCL: unhandled system error. Set NCCL_DEBUG=WARN for detail.
	 [[node NcclAllReduce (defined at <ipython-input-17-7105c4ec4d5e>:2) ]]
	 [[GroupCrossDeviceControlEdges_2/Nadam/Nadam/update_0/Const/_509]]
  (3) Internal:  NCCL: unhandled system error. Set NCCL_DEBUG=WARN for detail.
	 [[node NcclAllReduce (defined at <ipython-input-17-7105c4ec4d5e>:2) ]]
	 [[GroupCrossDeviceControlEdges_0/Nadam/Nadam/update_0/Const/_493]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_44874]
```

Looking at the NCCL_DEBUG logs, I find an out of memory error:

![image](https://user-images.githubusercontent.com/3875113/98307202-17298400-1f7a-11eb-9e2d-0bcbf88aa36f.png)

But this is wrong, I have plenty on space left on all my devices, as shown here with nvidia-smi and TF_FORCE_GPU_ALLOW_GROWTH

![image](https://user-images.githubusercontent.com/3875113/98307003-bc902800-1f79-11eb-9d2e-19365d22c3b7.png)

Dummy code:
```python3
def get_compiled_model():
    
    the_input = keras.layers.Input(shape=(window_length, input_length))
    embeddings = keras.layers.Embedding(num_addresses, embedding_dim)(the_input)

    encoded = keras.layers.Bidirectional(keras.layers.LSTM(NUM_HIDDEN))(embeddings)

    reconstr = keras.layers.RepeatVector(window_length)(encoded)
    reconstr = keras.layers.Bidirectional(keras.layers.LSTM(NUM_HIDDEN, return_sequences=True))(reconstr)
    
    reconstr = keras.layers.TimeDistributed(keras.layers.Dense(output_dim, activation='relu'), 
                                                    name="the_output")(reconstr)
    
    losses = {
        "the_output": keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    }
    lossWeights = LOSS_WEIGHTS
        
    model = keras.Model([
        the_input, 
    ], [
        reconstr
    ])

    model.compile(optimizer=tf.keras.optimizers.Nadam(learning_rate=LEARNING_RATE),
                  loss=losses)
    
    return model

gpu_devices = [device for device in tf.config.list_physical_devices() if device.device_type=='GPU']
if len(gpu_devices):
    strategy = tf.distribute.MirroredStrategy(devices=['/gpu:0', '/gpu:1', '/gpu:2', '/gpu:3'])
#     strategy = tf.distribute.MirroredStrategy()
    with strategy.scope():
        model = get_compiled_model()
else:
    model = get_compiled_model()

# train_generator is a custom keras.utils.Sequence 
model.fit(x=train_generator, epochs=200)
```

**Comment by nikitamaia** [comment]
Hi @devtronslab, can you provide reproducible code so I can run this on my end? Your code looks fairly standard to me so I suspect I won't actually be able to reproduce this error, but always good to try.

Additionally, can you try:
-training with just GPUs 2 and 3
-in the 4 GPU case set `tf.distribute.ReductionToOneDevice` so NCCL won't be used.

Also this sounds like it could be an issue you would want to post on the NCCL repo. I found the following two threads that might help here [#290](https://github.com/NVIDIA/nccl/issues/290) [#342](https://github.com/NVIDIA/nccl/issues/342)

**Comment by devtronslab** [comment]
@nikitamaia This is the best I can do regarding code since I won't be able to provide you with a dataset. The only difference between what I've provided and what I use is the `embeddings` vector gets concatenated with 2 other single float inputs and there is a second output of a single float. This is supposed to be an autoencoder, so the second output is a recreation of one of the float inputs, and its loss is a simple MSE.

As I wrote originally I have tried with 2 GPUs, and this do not yield any of the errors. 3 throws NCCL errors.

Adding `tf.distribute.ReductionToOneDevice` seems to work with 4 GPUs

**Comment by devtronslab** [comment]
@nikitamaia Following one of the links you've provided, I increased the shared memory size of the docker container with the `--shm-size=256m` flag, and the errors have gone away. Closing this issue. Thanks for the help!

**Comment by snamjoshi** [comment]
For anyone running into this issue on AWS Batch: The shared memory size is an available parameter you can customize when setting job parameters: https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html

Setting the shared memory size at 256 solved this issue on AWS Batch.
