### ISSUE TITLE
A listing of API symbols exported and supported in a machine readable form

### ISSUE THREAD

**Issue by fridex** [tensorflow/tensorflow#44650]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs

### Clear description

I would like to know if there is a listing of API symbols available and exported in a release (public API), I'm interested in Python code specifically. I see docs on the main page, but I would like to access symbols exported per release in a machine-readable form (for example in a JSON format). I couldn't find any related documentation, sorry if there are already such files. Do you plan to provide/support such a listing to the community?

I hope the issue is addressed correctly in this repo and thanks for any advice in advance.

**Comment by mihaimaruseac** [comment]
When you install the pip package, the public API is under the `api/` directory of the unpacked wheel.

**Comment by fridex** [comment]
Thanks, this will work.
