### ISSUE TITLE
Tensorflow lite Makefile: add support of gpu 

### ISSUE THREAD

**Issue by justeph** [tensorflow/tensorflow#44651]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):  2.3
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Currently we cannot use GPU delegate when compiling tensorflow lite using the Makefile

**Will this change the current api? How?** No

**Who will benefit with this feature?** 

**Any Other info.**

**Comment by ravikyram** [comment]
@justeph 

Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!

**Comment by justeph** [comment]
I am currently trying to build a yocto recipe for tensorflow-lite using Makefile, and I need the GPU delegate. I am trying to modify the Makefile right now, and I will open a merge request when this will be ready

**Comment by terryheo** [comment]
You can use OpenCL delegate with CMake.
https://www.tensorflow.org/lite/guide/build_cmake#available_options_to_build_tensorflow_lite
