### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tensorflow==2.3 (from versions: none)

### ISSUE THREAD

**Issue by Harshit-Kesar** [tensorflow/tensorflow#44656]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Harshit-Kesar** [comment]
![image](https://user-images.githubusercontent.com/42645864/98389553-38719980-207a-11eb-9106-f28b68a41531.png)

Getting error on installing TENSORFLOW

**Comment by djduncan585** [comment]
Having an identical issue with installing Tensorflow on a clean Python reinstallation using pip. 64 bit Win10 Pro, CPU only. Looking for a workaround if an immediate solution is not possible.
![Screenshot 2020-11-07 154507](https://user-images.githubusercontent.com/30355572/98451231-d5334600-2111-11eb-9654-ba77c1d0ea16.png)

**Comment by djduncan585** [comment]
Workaround found: current version of Tensorflow is not compatible with Python 3.9; I was able to get it to install by first installing Python 3.8.

**Comment by amahendrakar** [comment]
> Getting error on installing TENSORFLOW

@Harshit-Kesar,
From the error log, it seems like you have installed 32-bit Python. TensorFlow is tested and supported on 64-bit systems. For more information, please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements). 

Could you please install 64-bit Python and check if you are facing the same issue. Thanks!
