### ISSUE TITLE
InvalidArgumentError: Cannot convert a Tensor of dtype resource to a NumPy array.

### ISSUE THREAD

**Issue by MaxHeuillet** [tensorflow/tensorflow#44657]
**System information**

- Linux Ubuntu 16.04
- TensorFlow 2.2
- Python 3

**Describe the current behavior**
```

user_input = Input( shape=(None, 1), dtype=tf.int32 )
# same error with: user_input = Input( shape=(1,), dtype=tf.int32 )

MF_Embedding_User = tf.Variable(tf.random.normal([8176, 20], stddev=0.05), dtype=tf.float32, name='user_embedding')

user_embedding = tf.nn.embedding_lookup(MF_Embedding_User, user_input)
#same error with: tf.gather

user_input = [0,1,2,3,4,5]
model = Model( user_input, user_embedding )
```

**Describe the expected behavior**

I would like to define an Input vector of indices that I can use whether in a tf.ebedding_lookup or a tf.gather
It used to work in TF1 with placeholders and not anymore.

I don't know how i can Input my index vectors in my model
I know it is possible to define a @tf.function but idk how to do this and still be abble to train my model
I am really stuck.

Thank you for your help :)

**Comment by ravikyram** [comment]
@MaxHeuillet 
Please, refer similar issue #37441 and see if it helps you.
If the issue still persists, request you to share colab link or simple standalone code with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster.Thanks!
