### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: OpenCL library not loaded - dlopen failed: library "libOpenCL-pixel.so" not found

### ISSUE THREAD

**Issue by archie94** [tensorflow/tensorflow#44659]
**System information**

- Mobile device (vivo 1904, Pixel 2, etc),
- tenserflow lite
- build.gradle

```
'lite'    : 'org.tensorflow:tensorflow-lite:2.0.0',
'liteGpu': 'org.tensorflow:tensorflow-lite-gpu:2.0.0'
```

**Describe the current behavior**
Exception is thrown on invoking `Interpreter.runForMultipleInputsOutputs()` on the model collected from https://storage.googleapis.com/download.tensorflow.org/models/tflite/posenet_mobilenet_v1_100_257x257_multi_kpt_stripped.tflite

**Describe the expected behavior**

Successful recognition of posture.

**Standalone code to reproduce the issue**
I am getting this on crash analysis tool. Since this is not reproducible on my devices I am not able to produce a standalone code.

**Other info / logs** 

```
Fatal Exception: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: OpenCL library not loaded - dlopen failed: library "libOpenCL-pixel.so" not found
Falling back to OpenGL
TfLiteGpuDelegate Invoke: Write to buffer failed. Source data is larger than buffer.
Node number 31 (TfLiteGpuDelegateV2) failed to invoke.

       at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java)
       at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:171)
       at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
       at a.b.c.e.Posenet.estimateSinglePose(Posenet.java:296)
       at a.b.c.d.ImageAnalyser.processImage(ImageAnalyser.java:176)
       at a.b.c.d.ImageAnalyser.access$processImage(ImageAnalyser.java:26)
       at a.b.c.d.ImageAnalyser$processImageForAnalysis$2.invokeSuspend(ImageAnalyser.java:141)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:56)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

I am following this sample https://github.com/tensorflow/examples/blob/master/lite/examples/posenet/android/posenet/src/main/java/org/tensorflow/lite/examples/posenet/lib/Posenet.kt

**Comment by archie94** [comment]
Hello @amahendrakar 
Please let me know if there are any other info I can help you with.

**Comment by multiverse-tf** [comment]
Hi,

As the log mentions the following, it means the missing OpenCL lib isn't a issue here, and OpenGL is used instead for the GPU delegate. However, there's some memory related issue. 
"
Falling back to OpenGL
TfLiteGpuDelegate Invoke: Write to buffer failed. Source data is larger than buffer.
",

Considering you are running the example w/ tflite 2.0 and tflite-gpu-delegate 2.0, I'm wondering does this same issue show up with more recent builds (such as tflite 2.3.0, tflite 2.4.0rc1, or tflite nightly)? We have fixed several memory related bugs in our gpu delegate code base since then.

**Comment by archie94** [comment]
Thank you for your response @multiverse-tf 

I will update to `2.3.0` and revert on this.

**Comment by iamjitendrasinh** [comment]
I am gettingsame issue in realme and lenovo devices, I am using nightly build

```
Fatal Exception: java.lang.RuntimeException: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Following operations are not supported by GPU delegate:
SPLIT: Operation is not supported.
SPLIT_V: Operation is not supported.
94 operations will run on the GPU, and the remaining 58 operations will run on the CPU.
Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found
Falling back to OpenGL
TfLiteGpuDelegate Init: Add does not support HWC constant tensor
TfLiteGpuDelegate Prepare: delegate is not initialized
```

**Comment by iamjitendrasinh** [comment]
Here is log from other device ("lenovo")


   ```
 SPLIT: Operation is not supported.
    SPLIT_V: Operation is not supported.
    94 operations will run on the GPU, and the remaining 58 operations will run on the CPU.
    Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found
    Falling back to OpenGL
    TfLiteGpuDelegate Init: Add does not support HWC constant tensor
    TfLiteGpuDelegate Prepare: delegate is not initialized
    Node number 152
```

**Comment by archie94** [comment]
Hello!

After update to `2.3.0` there is no "source data larger than the buffer" issues. But I am getting these two with the same stacktrace.

```
Fatal Exception: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found
Falling back to OpenGL
TfLiteGpuDelegate Invoke: GpuDelegate must run on the same thread where it was initialized.
Node number 31 (TfLiteGpuDelegateV2) failed to invoke.
```

```
Fatal Exception: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: TfLiteGpuDelegate Invoke: Failed to read data from GPU (clEnqueueReadBuffer) - Execution status error for events in wait list
Node number 31 (TfLiteGpuDelegateV2) failed to invoke.

```

The first one seems to imply there is some threading issues however I am running the estimation on a single threaded executor.
Not sure of the second one. 

Please let me know if you would like to have a separate ticket for these though.

Thanks!

**Comment by multiverse-tf** [comment]
> Here is log from other device ("lenovo")
> 
> ```
> SPLIT: Operation is not supported.
>  SPLIT_V: Operation is not supported.
>  94 operations will run on the GPU, and the remaining 58 operations will run on the CPU.
>  Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found
>  Falling back to OpenGL
>  TfLiteGpuDelegate Init: Add does not support HWC constant tensor
>  TfLiteGpuDelegate Prepare: delegate is not initialized
Such error messages indicate that the model isn't well supported by the OpenGL backend of the TFLite gpu delegate yet.

>  Node number 152
> ```

**Comment by multiverse-tf** [comment]
> Hello!
> 
> After update to `2.3.0` there is no "source data larger than the buffer" issues. But I am getting these two with the same stacktrace.

Good to know such issues are gone now.

> 
> ```
> Fatal Exception: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found
> Falling back to OpenGL
> TfLiteGpuDelegate Invoke: GpuDelegate must run on the same thread where it was initialized.
As the error msg indicates, pls call invoke on the same thread where the GPU delegate is created as noted here (https://www.tensorflow.org/lite/performance/gpu#android). 

For more discussions about this requirement, pls check out https://github.com/tensorflow/tensorflow/issues/25657#issuecomment-462498449 and follow-ups.

> Node number 31 (TfLiteGpuDelegateV2) failed to invoke.
> ```
> 
> ```
> Fatal Exception: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: TfLiteGpuDelegate Invoke: Failed to read data from GPU (clEnqueueReadBuffer) - Execution status error for events in wait list
> Node number 31 (TfLiteGpuDelegateV2) failed to invoke.
> ```
> 
> The first one seems to imply there is some threading issues however I am running the estimation on a single threaded executor.
> Not sure of the second one.
> 
> Please let me know if you would like to have a separate ticket for these though.
> 
> Thanks!

**Comment by multiverse-tf** [comment]
As the issue has turned to others based on https://github.com/tensorflow/tensorflow/issues/44659#issuecomment-727843592 and https://github.com/tensorflow/tensorflow/issues/44659#issuecomment-727848537, I'll close this issue then. Feel free to file separate tickets to track these new issues.

**Comment by WillLiGitHub** [comment]
i have same error:
    TfLiteGpuDelegate Prepare: Add does not support HWC constant tensor
but there is not add ops for 3 dims.
![image](https://user-images.githubusercontent.com/26035529/131635786-9269f24c-929e-47a9-94fb-e26815125f26.png)

**Comment by impjdi** [comment]
@WillLiGitHub you're posting a completely irrelevant issue to a closed bug...

Anyway, your ADD operation below LOGISTIC has only 1 input, which means the other input is a constant.  And I assume that's a 3D tensor.
