### ISSUE TITLE
Android: Why is RandomShuffleQueue needed for testing?

### ISSUE THREAD

**Issue by catherineHR** [tensorflow/tensorflow#4466]
Hello, 

I want to test a learnt model under Python on android, I'm on Tensorflow 0.9.
To do so, I freezed my graph to have a single pb file with the graph and weight. I used Queues to manage my learning batches.

When running my session on Android, I specify the input tensor by its name "input_node", which is the data layer as input in my network. 
X = tf.reshape(X, [-1, W, H, 1], name="input_node")
and call the "output_node" layer : 
output = tf.reshape(h_fc11, shape=[-1, 8], name="output_node")

The batch generation is done before, so it should not been used when testing.
But I have the following error:
tensorflow_jni.cc:312 Error during inference: Invalid argument: No OpKernel was registered to support Op 'RandomShuffleQueue' with these attrs
[[Node: shuffle_batch/random_shuffle_queue = RandomShuffleQueue[capacity=10750, component_types=[DT_FLOAT, DT_FLOAT], container="", min_after_dequeue=10000, seed=0, seed2=0, shapes=[[10000], [8]], shared_name=""]()]]

It seems that the batch generation layer is called (my images are 100x100 and I have 8 outputs), but I don't know why.

When testing the same model with the same input/output layers though the image_labelling.cc directly on Mac (building with Bazel), I don't have the error.

I do not understand why the RandomShuffleQueue is needed when testing. Am I missing something to specify the part of the graph I want to use? Are all the layers of the graph verified even if not used?

Thanks.

**Comment by jmchen-g** [comment]
@petewarden Could you take a look at this? Thanks.

**Comment by andrewharp** [comment]
@catherineHR All nodes are verified when loading on Android, but you can use the [strip_unused](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/strip_unused.py) script to remove the unused and unsupported nodes from your graph.

**Comment by andrewharp** [comment]
Closing; please reopen with details if the problem persists.
