### ISSUE TITLE
Unable to "import tensorflow" using 2.4.0rc0 from within conda environment

### ISSUE THREAD

**Issue by psalveson** [tensorflow/tensorflow#44668]
**System information**
- OS: Ubuntu 20.04
- TensorFlow binary installed using pip
- TensorFlow version 2.4.0rc0
- Python version 3.8.6
- CUDA/cuDNN version: 11.0/8.0.4
- GPU model: GTX 1070

**Describe the current behavior**

Attempting to import tensorflow produces an "Illegal instruction" error.

**Describe the expected behavior**

Import tensorflow without error.

**Standalone code to reproduce the issue**
I created new conda environment and then installed tensorflow using pip from within the new environment:

```
conda create -n tf24 -c conda-forge python=3.8 pip
conda activate tf24
pip install tensorflow==2.4.0rc0
```
The following command exits with an "Illegal instruction" error:
```
python -c "import tensorflow as tf"
```
Note that this is not an issue with the last development version of 2.4.0 (2.4.0.dev20201023) from tf-nightly, installed with:

```
pip install tf-nightly==2.4.0.dev20201023
```

**Comment by Saduf2019** [comment]
@psalveson 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

Please refer to these resolved issues with same error : #44204, #40978, #43229.

**Comment by tallamjr** [comment]
> @psalveson
> We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]
> 
> Please refer to these resolved issues with same error : #44204, #40978, #43229.

Whilst #44204, #40978, #43229 report the same error, they seem to all discuss the transition to AVX compiled binaries and suggest to use older version than 1.6, i.e. `tensorflow<=1.5` 

I am experiencing a similar situation to @psalveson where I was previously able to import and run tensorflow up to version `2.3.1` in my case, but the latest `tf-nightly` and it seems all other builds now throw the `Illegal instruction` error.

Further discussion would bee greatly appreciated.

**Comment by Saduf2019** [comment]
@psalveson 
Is this still an issue

**Comment by psalveson** [comment]
@Saduf2019
I just installed 2.4.0rc2 and I am still receiving an "Illegal instruction" error.

**Comment by Saduf2019** [comment]
@psalveson 
Could you please update us on which os are you trying to install, and is there a tf version already there on it.

**Comment by psalveson** [comment]
@Saduf2019 
Please see my original post for details. I am attempting to install tf into a conda environment. There is no other tf version currently installed. I am using Ubuntu 20.04.

**Comment by Saduf2019** [comment]
@psalveson 
Please refer to this issue and let us know if it helps: #41315

This issue is more suitable on [Continuum Anaconda](https://github.com/ContinuumIO/anaconda-issues/issues) repo since its related to TF installation with Anaconda.
Please post it on Continuum [Anaconda.](https://github.com/ContinuumIO/anaconda-issues/issues)
Thanks!

**Comment by psalveson** [comment]
@Saduf2019 

As stated in my original ticket, this is a typical installation using pip. It is not installed from an anaconda repository. I am installing into a conda environment, however. I have just attempted to install the most recent RC (rc4), and the problem persists. What changed between the final version of 2.4 on tf-nightly (which worked) and rc0 on tensorflow (which doesn't work)? That seems like a more useful area of inquiry.
