### ISSUE TITLE
Separate TF 1.x from 2.x in PyPi

### ISSUE THREAD

**Issue by mirekphd** [tensorflow/tensorflow#44673]
Let's separate TF 1.x from 2.x package names and PyPI repos  to enable auto-updates to latest versions of TF 1.x. (without the need to manually monitor the latest available 1.x version).

Possibly just rename it to `tensorflow1==tensorflow` and `tensorflow2`, like with python 2.x and 3.x. These major versions of TF of equally incompatible, so they should not have the same package name IMHO.

The automatic code converter `tf_upgrade_v2` does not always work for Github data science projects and converting Kaggle Kernels and other Jupyter notebooks to `.py` format is an additional manual step required in practice (only to find that conversion did not work).

Many thanks!

**Comment by mihaimaruseac** [comment]
There are no more TF 1.x versions. TF 1.15 is the latest and won't get any more patches unless security issues discovered on Cloud VMs.

TensorFlow uses SemVer, not PVP versioning. Hence, there is only one major version number, not 2 (the second being in the name).

**Comment by mirekphd** [comment]
Ok, if TF 1.x has reached its release cycle, then the issue is Indeed irrelevant, and I will close the issue for now. 

Assuming we cannot stay with python 3.7, we can either:
a) switch to python 3.8 and upgrade to Tensorflow latest (2.x.y), or
b) stay with python 3.7 and pin Tensorflow at 1.15.4, or even
c) switch to another DL framework that does not tie it's major versions to historical python versions.

**Comment by mihaimaruseac** [comment]
We don't pin TF versions to Py versions willingly. It's just a matter of controlling the support matrix size. As soon as a python version is out of life, we will drop support for it. When a new python version is released we pick it up by at most 1 additional TF release, depending on how/when our dependencies pick it up.
