### ISSUE TITLE
How to install tensorflow gpu on rtx 3070

### ISSUE THREAD

**Issue by king398** [tensorflow/tensorflow#44678]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):both
- TensorFlow version:2.3.0
- Python version:3.7
- Installed using virtualenv? pip? conda?:conda
- Bazel version (if compiling from source):3.1.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:11.1;8.0
- GPU model and memory:rtx 3070 8gb

**Describe the problem**
 I have brought a rtx 3070 and I want to use tensorflow gpu on it. To use it I need to use cuda 11.1
**Provide the exact sequence of commands / steps that you executed before running into the problem**
So tried building from source but that did not work , issue is here https://github.com/tensorflow/tensorflow/issues/44671. And I also tried using tf nightly but that has a bug in it of numpy falling sanity check.

**Comment by shliujing** [comment]
I solved the problem using the following command:
```shell
  pip install tf-nightly-gpu
```
