### ISSUE TITLE
Fail for tf.image.flip_left_right(img_input) where im_input is Input(shape=(None, None, 3), name='image')

### ISSUE THREAD

**Issue by chenghuige** [tensorflow/tensorflow#44677]
I want to dump graph of tta for model.h5. But seems tf.image.flip_left_right not support dynamic input size. (tf version 2.3)

    import tensorflow as tf 
    from tensorflow.keras.layers import Input
    img_input = Input(shape=(None, None, 3), name='image')  
    tf.image.flip_left_right(img_input)    

OperatorNotAllowedInGraphError            Traceback (most recent call last)
<ipython-input-4-6faed2643326> in <module>()
----> 1 tf.image.flip_left_right(img_input)

/home/gezi/env/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a

/home/gezi/env/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/image_ops_impl.py in flip_left_right(image)
    489     ValueError: if the shape of `image` not supported.
    490   """
--> 491   return _flip(image, 1, 'flip_left_right')
    492
    493

/home/gezi/env/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/image_ops_impl.py in _flip(image, flip_index, scope_name)
    548   with ops.name_scope(None, scope_name, [image]):
    549     image = ops.convert_to_tensor(image, name='image')
--> 550     image = _AssertAtLeast3DImage(image)
    551     shape = image.get_shape()
    552     if shape.ndims == 3 or shape.ndims is None:

/home/gezi/env/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/image_ops_impl.py in _AssertAtLeast3DImage(image)
    195   """
    196   return control_flow_ops.with_dependencies(
--> 197       _CheckAtLeast3DImage(image, require_static=False), image)
    198
    199

/home/gezi/env/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/image_ops_impl.py in _CheckAtLeast3DImage(image, require_static)
    230         check_ops.assert_positive(
    231             array_ops.shape(image)[-3:],
--> 232             ["inner 3 dims of 'image.shape' "
    233              'must be > 0.']),
    234         check_ops.assert_greater_equal(

/home/gezi/env/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a

/home/gezi/env/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/check_ops.py in assert_positive(x, data, summarize, message, name)
    510           'x (%s) = ' % name, x]
    511     zero = ops.convert_to_tensor(0, dtype=x.dtype)
--> 512     return assert_less(zero, x, data=data, summarize=summarize)
    513
    514

/home/gezi/env/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    199     """Call target, and fall back on dispatchers if there is a TypeError."""
    200     try:
--> 201       return target(*args, **kwargs)
    202     except (TypeError, ValueError):
    203       # Note: convert_to_eager_tensor currently raises a ValueError, not a

/home/gezi/env/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/check_ops.py in assert_less(x, y, data, summarize, message, name)
    899 def assert_less(x, y, data=None, summarize=None, message=None, name=None):
    900   return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,
--> 901                         summarize, message, name)
    902
    903

/home/gezi/env/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/ops/check_ops.py in _binary_assert(sym, opname, op_func, static_func, x, y, data, summarize, message, name)
    333       test_op = op_func(x, y)
    334       condition = math_ops.reduce_all(test_op)
--> 335       if condition:
    336         return
    337

/home/gezi/env/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in __bool__(self)
    875       `TypeError`.
    876     """
--> 877     self._disallow_bool_casting()
    878
    879   def __nonzero__(self):

/home/gezi/env/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in _disallow_bool_casting(self)
    488     else:
    489       # Default: V1-style Graph execution.
--> 490       self._disallow_in_graph_mode("using a `tf.Tensor` as a Python `bool`")
    491
    492   def _disallow_iteration(self):

/home/gezi/env/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in _disallow_in_graph_mode(self, task)
    477     raise errors.OperatorNotAllowedInGraphError(
    478         "{} is not allowed in Graph execution. Use Eager execution or decorate"
--> 479         " this function with @tf.function.".format(task))
    480
    481   def _disallow_bool_casting(self):

OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

**Comment by ravikyram** [comment]
I have tried in colab in TF 2.3 and was able to reproduce the issue. However the issue was resolved in TF nightly version(`2.5.0-dev20201108`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/250011705ca0a25c9059cd62117c129c/untitled495.ipynb).Please, verify once and close the issue.Thanks!

**Comment by chenghuige** [comment]
@ravikyram  Great! Since it is solved closing this issue.
