### ISSUE TITLE
Arguments have an HTML format issue

### ISSUE THREAD

**Issue by houseofai** [tensorflow/tensorflow#44685]
## URL(s) with the issue: https://www.tensorflow.org/api_docs/python/tf/image/extract_patches

The arguments need to be reformatted:

![Screen Shot 2020-11-08 at 17 28 21](https://user-images.githubusercontent.com/8287111/98470714-dafb5b00-21e7-11eb-8221-96eb105b5e52.png)

**Comment by mihaimaruseac** [comment]
Can you send a PR?

**Comment by houseofai** [comment]
Sure, I just learned how to do that. But it looks like it's fixed on the latest version. Should I fixed it for that specific doc version (2.3.0)?

**Comment by mihaimaruseac** [comment]
If it is fixed in master/2.4 then there is nothing left to do. Since we only update old versions only for security issues.

**Comment by ravikyram** [comment]
@houseofai 

Please, close this thread as the issue is fixed in latest version. Thanks!
