### ISSUE TITLE
[Docs should enhance] The docs not tell me: How does a TPU cluster allocate memory for the model?

### ISSUE THREAD

**Issue by GF-Huang** [tensorflow/tensorflow#44689]
My issue in short words, I'm creating a model just a single LSTM layer (`layers.LSTM(units=16298, input_shape=(1, 16298))`), and my google cloud vm connect to the `v3-8` tpu which has total 128GB RAM, why I still got `ResourceExhaustedError` exception? It seems only use one TPU core (16GB RAM) to create model, not the total (16 * 8 = 128GB).

Can some one tell me: How does a TPU cluster allocate memory for the model?

This is my issue details: https://stackoverflow.com/questions/64737657/how-much-memory-do-i-need-for-my-lstm-model

**Comment by GF-Huang** [comment]
up

**Comment by nikitamaia** [comment]
Hi @GF-Huang, you can see [here in the docs for tf.distribute.TPUStrategy](https://www.tensorflow.org/api_docs/python/tf/distribute/TPUStrategy) that when "using distribution strategies, the variables created within the strategy's scope will be replicated across all the replicas."

You can determine the number of replicas with `strategy.num_replicas_in_sync` (I think this should return 8 in your case). With a distribution strategy, the model is not split up across the cores. The tf.distribute.Strategy API currently supports data parallelism, which means that there is a copy of the model on each replica. And it is the data in each batch that gets split up across replicas. TPUs provide an implementation of efficient all-reduce and other collective operations to keep the variables in sync across multiple TPU cores. The[ Distributed Training with TensorFlow guide](https://www.tensorflow.org/guide/distributed_training#tpustrategy) provides some more information on how strategies work. For reference, in terms of distributed training architecture, TPUStrategy is the same [MirroredStrategy](https://www.tensorflow.org/api_docs/python/tf/distribute/MirroredStrategy). Hope this clears things up.

**Comment by GF-Huang** [comment]
> Hi @GF-Huang, you can see [here in the docs for tf.distribute.TPUStrategy](https://www.tensorflow.org/api_docs/python/tf/distribute/TPUStrategy) that when "using distribution strategies, the variables created within the strategy's scope will be replicated across all the replicas."
> 
> You can determine the number of replicas with `strategy.num_replicas_in_sync` (I think this should return 8 in your case). With a distribution strategy, the model is not split up across the cores. The tf.distribute.Strategy API currently supports data parallelism, which means that there is a copy of the model on each replica. And it is the data in each batch that gets split up across replicas. TPUs provide an implementation of efficient all-reduce and other collective operations to keep the variables in sync across multiple TPU cores. The[ Distributed Training with TensorFlow guide](https://www.tensorflow.org/guide/distributed_training#tpustrategy) provides some more information on how strategies work. For reference, in terms of distributed training architecture, TPUStrategy is the same [MirroredStrategy](https://www.tensorflow.org/api_docs/python/tf/distribute/MirroredStrategy). Hope this clears things up.

Thanks for your detailed reply. So tensorflow doesn't supports model parallelism?

**Comment by nikitamaia** [comment]
Currently, the tf.distribute.Strategy API only supports data parallelism. If you want to try out model parallelism, you can take a look at [mesh tensorflow](https://github.com/tensorflow/mesh).
