### ISSUE TITLE
How can I use micro_mutable_op_resolver.h instead of all_ops_resolver.h to run TensorFlow Lite for Microcontrollers exapmle?

### ISSUE THREAD

**Issue by Dueschen** [tensorflow/tensorflow#44687]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows subsystem for Linux, Ubuntu 18.04
- TensorFlow installed from (source or binary): 
- Tensorflow version (commit SHA if source): 
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): My own PC

**Describe the problem**

I'm running test on the hello_world example in TensorFlow Lite for Microcontrollers, on my own develop machine.
In [https://www.tensorflow.org/lite/microcontrollers/library](https://www.tensorflow.org/lite/microcontrollers/library) I found an option to use **micro_mutable_op_resolver.h** instead of **all_ops_resolver.h**, so that I can only pull in the ops I need.
I've tried to change some lines in hello_world_test.cc, but still can't get it right.

**Please provide the exact sequence of commands/steps when you ran into the problem**

I've change these lines in tensorflow\lite\micro\examples\hello_world\hello_world_test.cc:
line 16: 
`#include "tensorflow/lite/micro/all_ops_resolver.h"`
to : 
`#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"`
line 41: 
`tflite::AllOpsResolver resolver;`
to: 
```
const unsigned int tOpCount = 5;
tflite::MicroMutableOpResolver<tOpCount> resolver;
```

then I run the command: 
`sudo make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test `
But It seems to pull in and compile all ops. Also, after printing out"~~~ALL TESTS PASSED~~~'", the process doesn't end.

Could anyone help me please?

**Comment by Dueschen** [comment]
Hi, it's me again.
I referred to another task--micro_speech, which uses micro_op_resolver.h in both main_functions.cc and micro_speech_test.cc.
It seems like I should make a list of all ops I need, so in `hello_world_test.cc`, I modify the following lines:
line 18:
`#include "tensorflow/lite/micro/all_ops_resolver.h"`
to
`#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"`
line 47:
`tflite::AllOpsResolver resolver;`
to
```
  tflite::MicroMutableOpResolver<5> resolver;
  resolver.AddDequantize();
  resolver.AddFullyConnected();
  resolver.AddQuantize();
  resolver.AddRelu();
  resolver.AddReshape();
```

In `hello_world/main_functions.cc` I modifiy:
line 18:
`#include "tensorflow/lite/micro/all_ops_resolver.h"`
to
`#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"`
line 67:
`static tflite::AllOpsResolver resolver;`
to
```
  static tflite::MicroMutableOpResolver<5> resolver(error_reporter);
  if (resolver.AddDequantize() != kTfLiteOk) {
    return;
  }
  if (resolver.AddFullyConnected() != kTfLiteOk) {
    return;
  }
  if (resolver.AddQuantize() != kTfLiteOk) {
    return;
  }
  if (resolver.AddRelu() != kTfLiteOk) {
    return;
  }
  if (resolver.AddReshape() != kTfLiteOk) {
    return;
  }
```

Actually I'm not sure how many ops should I use. When I was testing, I found that I can pass the test using only AddFullyConnected().
At least it works better than 3 days ago. If anyone knows how to check the ops used in a model, or spots some problem in my code, please leave a comment.
Thank you for helping.

**Comment by mohantym** [comment]
Hi @Dueschen!
Could you post this issue in Stackoverflow /[TF forum ](https://discuss.tensorflow.org/)as there is a larger community to help you out .Thanks!
