### ISSUE TITLE
Install tf-nightly 2.0

### ISSUE THREAD

**Issue by Rariusz** [tensorflow/tensorflow#44680]
I need install ```tf-nightly 2.0```.  Where can I find older versions of the library?. On this site https://pypi.org/project/tf-nightly/#history the oldest is 2.4.0

**Comment by amahendrakar** [comment]
@Rariusz,
We don't save nightly packages for longer period of time. Current archive collects nightly packages from the month of September 2020 till date.

For more information, please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/37317#issuecomment-595382300) from a similar issue. Thanks!

**Comment by Rariusz** [comment]
@amahendrakar Thanks for the answer!!! I wanted to compile yolo to tflite model based on this repository  [YOLO](https://github.com/guichristmann/edge-tpu-tiny-yolo?fbclid=IwAR0-OrnFUL-k9xXbTieLb4sJr3YS3xIdeLyfxGlaYWJu1rheyQoCUaM5iD4) and it is required there tf-nightly 2.0.

Now I am working on compiling a tensorflow model to tflite or yolo to tflite for my own data 
https://github.com/tensorflow/tensorflow/issues/44435 
https://github.com/google-coral/edgetpu/issues/248 
https://github.com/tensorflow/tensorflow/issues/44610 
and that was the reason why I asked about this particular version
