### ISSUE TITLE
crosstool_wrapper_driver_is_not_gcc failed: error executing command

### ISSUE THREAD

**Issue by bleedingfight** [tensorflow/tensorflow#44692]
<em>
</em>

**System information**
- Ubuntu20.04.1

- tensorflow source (master branch):
- TensorFlow version:
- Python version:3.8.5

- 3.1.0n (if compiling from source):
- GCC/Compiler version (if compiling from source):9.2
- CUDA/cuDNN version:8
- GPU model and memory:24GB
- Graph Card Diver:455.23.04
- NVIDIA Card:RTX3090
- TensorRT:TensorRT-7.2.1.6

**bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --verbose_failures
**

**/home/liushuai/tensorflow/tensorflow/core/grappler/costs/BUILD:146:1: C++ compilation of rule '//tensorflow/core/grappler/costs:robust_stats' failed (Exit 127): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/liushuai/.cache/bazel/_bazel_liushuai/aa8adcb58cbbd827a6e521843f232b82/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda-11.0 \
    GCC_HOST_COMPILER_PATH=/usr/bin/x86_64-linux-gnu-gcc-9 \
    PATH=/usr/local/cuda-11.0/bin:/usr/local/python-3.7.9/bin:/usr/local/cuda-11.0/bin:/usr/local/cuda-11.0/bin:/usr/local/cuda-11.0/bin:/home/liushuai/miniconda3/bin:/home/liushuai/miniconda3/condabin:/usr/local/cuda-11.0/bin:/home/liushuai/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/liushuai/.fzf/bin:/usr/local/go/bin:/usr/local/python-3.7.9/bin:/usr/local/go/bin:/usr/local/python-3.7.9/bin:/usr/local/go/bin:/usr/local/python-3.7.9/bin:/usr/local/go/bin:/usr/local/go/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    TF2_BEHAVIOR=1 \
    TF_CONFIGURE_IOS=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=8.6 \
    TF_CUDA_PATHS=/usr/local/cuda-11.0,/usr/local/cuda-11.0/targets/x86_64-linux,/usr/local/TensorRT-7.2.1.6 \
    TF_CUDA_VERSION=11 \
    TF_CUDNN_VERSION=8 \
    TF_NCCL_VERSION='' \
    TF_NEED_CUDA=1 \
    TF_NEED_TENSORRT=1 \
    TF_TENSORRT_VERSION=7 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/tensorflow/core/grappler/costs/_objs/robust_stats/robust_stats.pic.d '-frandom-seed=bazel-out/k8-opt/bin/tensorflow/core/grappler/costs/_objs/robust_stats/robust_stats.pic.o' -iquote . -iquote bazel-out/k8-opt/bin -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIC -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -fno-canonical-system-headers -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -w -DAUTOLOAD_DYNAMIC_KERNELS '-march=native' -Wno-sign-compare '-std=c++14' -c tensorflow/core/grappler/costs/robust_stats.cc -o bazel-out/k8-opt/bin/tensorflow/core/grappler/costs/_objs/robust_stats/robust_stats.pic.o)
Execution platform: @local_execution_config_platform//:platform
/usr/bin/env: 'python': No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: /home/liushuai/tensorflow/tensorflow/lite/toco/python/BUILD:88:1 C++ compilation of rule '//tensorflow/core/grappler/costs:robust_stats' failed (Exit 127): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/liushuai/.cache/bazel/_bazel_liushuai/aa8adcb58cbbd827a6e521843f232b82/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda-11.0 \
    GCC_HOST_COMPILER_PATH=/usr/bin/x86_64-linux-gnu-gcc-9 \
    PATH=/usr/local/cuda-11.0/bin:/usr/local/python-3.7.9/bin:/usr/local/cuda-11.0/bin:/usr/local/cuda-11.0/bin:/usr/local/cuda-11.0/bin:/home/liushuai/miniconda3/bin:/home/liushuai/miniconda3/condabin:/usr/local/cuda-11.0/bin:/home/liushuai/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/liushuai/.fzf/bin:/usr/local/go/bin:/usr/local/python-3.7.9/bin:/usr/local/go/bin:/usr/local/python-3.7.9/bin:/usr/local/go/bin:/usr/local/python-3.7.9/bin:/usr/local/go/bin:/usr/local/go/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    TF2_BEHAVIOR=1 \
    TF_CONFIGURE_IOS=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=8.6 \
    TF_CUDA_PATHS=/usr/local/cuda-11.0,/usr/local/cuda-11.0/targets/x86_64-linux,/usr/local/TensorRT-7.2.1.6 \
    TF_CUDA_VERSION=11 \
    TF_CUDNN_VERSION=8 \
    TF_NCCL_VERSION='' \
    TF_NEED_CUDA=1 \
    TF_NEED_TENSORRT=1 \
    TF_TENSORRT_VERSION=7 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/tensorflow/core/grappler/costs/_objs/robust_stats/robust_stats.pic.d '-frandom-seed=bazel-out/k8-opt/bin/tensorflow/core/grappler/costs/_objs/robust_stats/robust_stats.pic.o' -iquote . -iquote bazel-out/k8-opt/bin -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIC -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -fno-canonical-system-headers -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -w -DAUTOLOAD_DYNAMIC_KERNELS '-march=native' -Wno-sign-compare '-std=c++14' -c tensorflow/core/grappler/costs/robust_stats.cc -o bazel-out/k8-opt/bin/tensorflow/core/grappler/costs/_objs/robust_stats/robust_stats.pic.o)**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@bleedingfight 

Please, see tested build configurations from [here](https://www.tensorflow.org/install/source#gpu).

Please, refer similar issues #22372, #13481 and see if it helps you. Thanks!

**Comment by bleedingfight** [comment]
@ravikyram thanks for your reply.I've browsed the  build page，You mean I need to downgrade my software？gcc9.2-->GCC 7.3.1 and bazel 3.1->Bazel 0.27.1? In fact, I have successfully compiled software on the same type of platform。In my desktop：
OS：5.8.16-2-MANJARO
NVIDIA Graphic Card：GTX980m
Driver：450.80.02
gcc：10.1
TensorRT：TensorRT-7.2.0.14
CUDA：11.0
bazel:3.1
CUDNN:8.0
In this env,I compile tensorflow's master branch and success generator tensorflow2.4.whl.

**Comment by bleedingfight** [comment]
> @bleedingfight
> 
> Please, see tested build configurations from [here](https://www.tensorflow.org/install/source#gpu).
> 
> Please, refer similar issues #22372, #13481 and see if it helps you. Thanks!
@ravikyram thanks for your reply.I've browsed the build page，You mean I need to downgrade my software？gcc9.2-->GCC 7.3.1 and bazel 3.1->Bazel 0.27.1? In fact, I have successfully compiled software on the same type of platform。In my desktop：
OS：5.8.16-2-MANJARO
NVIDIA Graphic Card：GTX980m
Driver：450.80.02
gcc：10.1
TensorRT：TensorRT-7.2.0.14
CUDA：11.0
bazel:3.1
CUDNN:8.0
In this env,I compile tensorflow's master branch and success generator tensorflow2.4.whl.

**Comment by bleedingfight** [comment]
Maybe I had found the problem.because tensorflow unsupport cc8.6(RTX3090 support 8.6),I changed the cc to 7.5(volta),and compile it again,it successed,if someone need it ,you can download it from [here:](https://pan.baidu.com/s/1aWFV3AtmcQjM1BZomALReg)  提取码: aytj

**Comment by tanzhenyu** [comment]
For me, the command that works is:
`bazel build --config=opt --per_file_copt=//tensorflow/.*\.cc@-g,-O0 tensorflow/tools/pip_package:build_pip_package`

**Comment by bleedingfight** [comment]
> For me, the command that works is: `bazel build --config=opt --per_file_copt=//tensorflow/.*\.cc@-g,-O0 tensorflow/tools/pip_package:build_pip_package`

Thanks for you replay,it's workded when I use this:
`bazel build  --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" -s -c dbg //tensorflow/tools/pip_package:build_pip_package`
