### ISSUE TITLE
Performance regression when MKL is enabled

### ISSUE THREAD

**Issue by YijinLiu** [tensorflow/tensorflow#44691]
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No.

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04.5

- TensorFlow installed from (source or binary):
Binary

- TensorFlow version (use command below):
1.13.2 and 1.14.0

**Describe the current behavior**
Train a ssdlite_mobilenet_v2 model with 1.13.2 and 1.14.0, the inference speed is very different. 1.14.0 one is about 50% to 100% slow with MKL enabled. When MKL is disabled, there is no obvious difference.

benchmark_model shows:
1.13.2
<pre>
             _MklFusedConv2D           55       13.732      43.384%     43.384%  45625.535         55
         NonMaxSuppressionV3           27        5.386      17.016%     60.401%     10.800         27
    _MklDepthwiseConv2dNative          33        3.161       9.987%     70.387%  20275.297         33
                    _MklToTf           72        2.027       6.404%     76.791%  23987.072         72
                         Mul           51        1.783       5.633%     82.424%     15.336         51
                         Add           81        1.772       5.598%     88.023%      0.016         81
                   _MklRelu6           33        0.731       2.309%     90.332%     30.096         33
                        NoOp            1        0.462       1.460%     91.792%      0.000          1
                        Cast            6        0.383       1.210%     93.002%   1104.316          6
                       Slice           33        0.272       0.859%     93.861%    414.072         33
                    GatherV2           69        0.227       0.717%     94.579%    253.200         69
                       Const          614        0.180       0.569%     95.147%      0.000        688
                _MklConcatV2            6        0.168       0.531%     95.678%    358.848          6
        TensorArrayScatterV3            5        0.151       0.477%     96.155%   1317.728          5
                         Sub           44        0.133       0.420%     96.575%     15.336         44
                     Sigmoid            1        0.132       0.417%     96.992%      0.000          1
                      TopKV2            2        0.117       0.370%     97.362%     43.200          2
                StridedSlice           54        0.076       0.240%     97.602%      0.088         54
                       Shape           50        0.058       0.183%     97.785%      0.344         50
         TensorArrayGatherV3            6        0.057       0.180%     97.965%   1082.416          6
               TensorArrayV3           11        0.051       0.161%     98.127%      2.596         11
                        Pack           24        0.046       0.145%     98.272%     30.956         24
              ResizeBilinear            1        0.045       0.142%     98.414%   1080.000          1
                    ConcatV2           27        0.039       0.123%     98.537%     10.800         27
                      Select           33        0.038       0.120%     98.657%      0.000         33
                        Less           31        0.038       0.120%     98.777%      2.704         35
                       Enter           26        0.036       0.114%     98.891%      0.000         26
                       Merge           10        0.035       0.111%     99.002%      0.040         20
                        Fill           30        0.031       0.098%     99.100%     11.204         30
                   ZerosLike           29        0.030       0.095%     99.194%     10.808         29
                     Reshape           74        0.028       0.088%     99.283%      0.000         74
                       Split            3        0.026       0.082%     99.365%    129.600          3
                      Unpack            5        0.023       0.073%     99.438%     92.044          5
               _MklTranspose            3        0.020       0.063%     99.501%     92.016          3
                      Switch           10        0.019       0.060%     99.561%      0.000         20
                       Range           14        0.018       0.057%     99.618%      1.244         14
               NextIteration           10        0.014       0.044%     99.662%      0.000         10
                     Squeeze            4        0.010       0.032%     99.694%      0.000          4
          TensorArrayWriteV3            6        0.009       0.028%     99.722%      0.000          6
                     Minimum            6        0.009       0.028%     99.750%      0.000          6
                     Greater            6        0.009       0.028%     99.779%      2.705          6
                  ExpandDims            7        0.009       0.028%     99.807%      0.000          7
                     _Retval            4        0.007       0.022%     99.829%      0.000          4
                         Exp            2        0.007       0.022%     99.852%      0.000          2
           TensorArraySizeV3            6        0.006       0.019%     99.870%      0.024          6
                     Maximum            4        0.006       0.019%     99.889%      0.000          4
                       Where            1        0.005       0.016%     99.905%     21.600          1
           TensorArrayReadV3            5        0.005       0.016%     99.921%      0.000          5
                         Sum            1        0.004       0.013%     99.934%      0.004          1
                  LogicalAnd            2        0.004       0.013%     99.946%      0.000          4
                         Pad            3        0.003       0.009%     99.956%      0.000          3
                GreaterEqual            1        0.003       0.009%     99.965%      2.700          1
                       Equal            2        0.003       0.009%     99.975%      0.002          2
                        Size            2        0.002       0.006%     99.981%      0.008          2
                    LoopCond            2        0.002       0.006%     99.987%      0.000          4
                      Assert            3        0.002       0.006%     99.994%      0.000          3
                        _Arg            1        0.001       0.003%     99.997%      0.000          1
                        Tile            1        0.001       0.003%    100.000%      0.000          1
                    Identity            4        0.000       0.000%    100.000%      0.000          4           
                        Exit            6        0.000       0.000%    100.000%      0.000          6
Timings (microseconds): count=283 first=29518 curr=32211 min=29448 max=39857 avg=32586.2 std=1784
</pre>

1.14.0
<pre>
                  _MklConv2D           43       12.516      28.381%     28.381%  43239.328         43
    _MklDepthwiseConv2dNative          33        7.580      17.188%     45.569%  20275.297         33
         NonMaxSuppressionV3           27        5.294      12.005%     57.574%     10.800         27  
                         Add          114        5.088      11.537%     69.111%      0.016        114 
                    _MklToTf          100        4.871      11.045%     80.156%  52036.352        100 
                   _MklRelu6           59        2.116       4.798%     84.955%     53.808         59  
                         Mul           51        1.774       4.023%     88.977%     15.336         51  
             _MklFusedConv2D           12        1.282       2.907%     91.884%   2386.208         12  
                        NoOp            1        0.563       1.277%     93.161%      0.000          1   
                        Cast            6        0.374       0.848%     94.009%   1104.316          6   
                       Slice           33        0.294       0.667%     94.676%    414.072         33  
                       Const          601        0.293       0.664%     95.340%      0.000        677 
                    GatherV2           69        0.232       0.526%     95.866%    253.200         69  
                _MklConcatV2            6        0.174       0.395%     96.261%    358.848          6   
        TensorArrayScatterV3            5        0.173       0.392%     96.653%   1317.728          5   
                        AddN           10        0.142       0.322%     96.975%      0.000         10  
                         Sub           44        0.138       0.313%     97.288%     15.336         44  
                     Sigmoid            1        0.132       0.299%     97.587%      0.000          1   
                      TopKV2            2        0.121       0.274%     97.862%     43.200          2   
                StridedSlice           54        0.085       0.193%     98.054%      0.088         54  
                     Reshape           74        0.063       0.143%     98.197%      0.000         74  
         TensorArrayGatherV3            6        0.060       0.136%     98.333%   1082.416          6   
                       Shape           50        0.056       0.127%     98.460%      0.344         50  
              ResizeBilinear            1        0.055       0.125%     98.585%   1080.000          1   
                    ConcatV2           27        0.053       0.120%     98.705%     10.800         27  
               TensorArrayV3           11        0.052       0.118%     98.823%      2.596         11  
                        Pack           24        0.051       0.116%     98.939%     30.956         24  
                      Select           33        0.043       0.098%     99.036%      0.000         33  
                       Enter           26        0.042       0.095%     99.132%      0.000         26  
                        Less           31        0.040       0.091%     99.222%      2.704         35  
                       Merge           10        0.037       0.084%     99.306%      0.040         20  
                        Fill           30        0.032       0.073%     99.379%     11.204         30  
                   ZerosLike           29        0.031       0.070%     99.449%     10.808         29  
                       Split            3        0.027       0.061%     99.510%    129.600          3   
                      Unpack            5        0.025       0.057%     99.567%     92.044          5   
                      Switch           10        0.022       0.050%     99.617%      0.000         20  
               _MklTranspose            3        0.020       0.045%     99.662%     92.016          3   
                       Range           14        0.017       0.039%     99.701%      1.244         14  
               NextIteration           10        0.017       0.039%     99.739%      0.000         10  
          TensorArrayWriteV3            6        0.012       0.027%     99.766%      0.000          6   
                     Squeeze            4        0.010       0.023%     99.789%      0.000          4   
                     Minimum            6        0.009       0.020%     99.810%      0.000          6   
                     Greater            6        0.009       0.020%     99.830%      2.705          6   
                  ExpandDims            7        0.009       0.020%     99.850%      0.000          7   
                     _Retval            4        0.008       0.018%     99.868%      0.000          4   
           TensorArrayReadV3            5        0.007       0.016%     99.884%      0.000          5   
                         Exp            2        0.007       0.016%     99.900%      0.000          2   
           TensorArraySizeV3            6        0.006       0.014%     99.914%      0.024          6   
                  LogicalAnd            2        0.006       0.014%     99.927%      0.000          4   
                       Where            1        0.005       0.011%     99.939%     21.600          1   
                     Maximum            4        0.005       0.011%     99.950%      0.000          4   
                         Sum            1        0.004       0.009%     99.959%      0.004          1   
                         Pad            3        0.003       0.007%     99.966%      0.000          3   
                GreaterEqual            1        0.003       0.007%     99.973%      2.700          1   
                       Equal            2        0.003       0.007%     99.980%      0.002          2   
                        Size            2        0.002       0.005%     99.984%      0.008          2   
                    LoopCond            2        0.002       0.005%     99.989%      0.000          4   
                      Assert            2        0.002       0.005%     99.993%      0.000          2   
                        _Arg            1        0.001       0.002%     99.995%      0.000          1   
                        Tile            1        0.001       0.002%     99.998%      0.000          1   

Timings (microseconds): count=207 first=39464 curr=48545 min=38998 max=65787 avg=45005.9 std=4312
</pre>

**Comment by Saduf2019** [comment]
@YijinLiu 
As there is support for 2.x only now,could you please upgrade ad let us know if you still face any issues in 2.x.

**Comment by YijinLiu** [comment]
Unfortunately, tf2 doesn't fully support the model I am using. I am stuck in tf1 for now.
I use the C++ interface. I assume there is no much difference between tf1 and tf2?
I tried tf1.5, which has the exact same issue. I guess it's related to some mkl C++ code that cannot handle conv2d for models trained with tf1.4+. Is it possible that you have some guy from Intel (whoever contributed https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/mkl_layout_pass.cc) take a look?

**Comment by NeoZhangJianyu** [comment]
@YijinLiu 
There is Intel optimized Tensorflow 1.15.0up1.
It includes many bug and performance fix.
We have got good performance improvement feedback from customers.

Could you try with it?

Installation:
`pip install https://storage.googleapis.com/intel-optimized-tensorflow/intel_tensorflow-1.15.0up1-cp36-cp36m-manylinux2010_x86_64.whl 
`

**Comment by NeoZhangJianyu** [comment]
@YijinLiu 
Is there any feedback?

**Comment by YijinLiu** [comment]
I just tried it. Got illegal instruction...
My CPU is i7-10700. I hope running inside docker won't be a problem.

**Comment by NeoZhangJianyu** [comment]
@YijinLiu 
Oh, could you share your log for the issue?

It's Tensorflow 1.15 base, so the script need to be changed from some API of Tensorflow 1.13 or 1.14 to 1.15.
Is there same issue when run your script with stack/official TF 1.15?

What's the guest OS in docker?

**Comment by NeoZhangJianyu** [comment]
@YijinLiu 
Could you share the log?

**Comment by NeoZhangJianyu** [comment]
@YijinLiu 
Is your issue present?
If yes, could you answer above questions?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
