### ISSUE TITLE
bazel build libtensorflowlite has issue during compiling

### ISSUE THREAD

**Issue by anglerbug123** [tensorflow/tensorflow#44695]
tizen5.0_cross_toolchain_vd_kant_target_armv7l_host_x86-64/bin/armv7l-tizen-linux-gnueabi-gcc -MD -MF bazel-out/armv7-opt/bin/external/mkl_dnn/_objs/mkldnn_single_threaded/simple_concat.d '-frandom-seed=bazel-out/armv7-opt/bin/external/mkl_dnn/_objs/mkldnn_single_threaded/simple_concat.o' -iquote external/mkl_dnn -iquote bazel-out/armv7-opt/bin/external/mkl_dnn -isystem external/mkl_dnn/include -isystem bazel-out/armv7-opt/bin/external/mkl_dnn/include -isystem external/mkl_dnn/src -isystem bazel-out/armv7-opt/bin/external/mkl_dnn/src -isystem external/mkl_dnn/src/common -isystem bazel-out/armv7-opt/bin/external/mkl_dnn/src/common -isystem external/mkl_dnn/src/cpu -isystem bazel-out/armv7-opt/bin/external/mkl_dnn/src/cpu -isystem external/mkl_dnn/src/cpu/gemm -isystem bazel-out/armv7-opt/bin/external/mkl_dnn/src/cpu/gemm -isystem external/mkl_dnn/src/cpu/xbyak -isystem bazel-out/armv7-opt/bin/external/mkl_dnn/src/cpu/xbyak -w -DAUTOLOAD_DYNAMIC_KERNELS -fPIC '-std=c++14' -fexceptions '-DMKLDNN_THR=MKLDNN_THR_SEQ' -c external/mkl_dnn/src/cpu/simple_concat.cpp -o bazel-out/armv7-opt/bin/external/mkl_dnn/_objs/mkldnn_single_threaded/simple_concat.o)
Execution platform: @local_execution_config_platform//:platform
In file included from external/mkl_dnn/src/common/mkldnn_thread.hpp:20:0,
                 from external/mkl_dnn/src/cpu/simple_concat.cpp:17:
external/mkl_dnn/src/common/utils.hpp:45:1: error: static assertion failed: Intel(R) MKL-DNN supports 64 bit only
 static_assert(sizeof(void*) == 8, "Intel(R) MKL-DNN supports 64 bit only");
 ^~~~~~~~~~~~~
Target //tensorflow/lite:libtensorflowlite.so failed to build

**Comment by ravikyram** [comment]
@anglerbug123 

Request you to fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!
