### ISSUE TITLE
module 'tensorflow_lite_support.metadata.metadata_schema_py_generated' has no attribute 'ModelMetadataT' error

### ISSUE THREAD

**Issue by hiroki-oist** [tensorflow/tensorflow#44693]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not used
- TensorFlow installed from (source or binary): Spyder in Anagonda Navigator (It was preinstalled)
- TensorFlow version (use command below): Tensorflow 2
- Python version: 3.8
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: None
- GPU model and memory: Not using GPU

**Describe the current behavior**
I have tried to run the sample code from https://www.tensorflow.org/lite/convert/metadata in anaconda prompt, which is

python ./metadata_writer_for_image_classifier.py \
    --model_file=./model_without_metadata/mobilenet_v1_0.75_160_quantized.tflite \
    --label_file=./model_without_metadata/labels.txt \
    --export_directory=model_with_metadata

I have downloaded "mobilenet_v1_0.75_160_quantized.tflite" file and placed it in Desktop/model_without_metadata, downloaded this file (https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/metadata/metadata_writer_for_image_classifier.py) and placed it in Desktop as well.  By running this code, it gives me
module 'tensorflow_lite_support.metadata.metadata_schema_py_generated' has no attribute 'ModelMetadataT'
error.
How can I solve this?

**Describe the expected behavior**
Metadata should be added to mobilenet_v1_0.75_160_quantized.tflite in order to use it in MLkit for object classification.

**Comment by Saduf2019** [comment]
@hiroki-oist 
Please provide with simple stand alone code to replicate the issue or a colab gist with the error reported.

**Comment by hiroki-oist** [comment]
Sorry, since I am absolute beginner for python and machine learning, this might not exactly what you need, but anyway,
mobilenet_v1_0.75_160_quantized.tflite : tffile I want to add metadata to. Path is Desktop/model_without_metadata/
metadata_writer_for_image_classifier.py : code for adding metadata (not customized. Totally copied). Path is Desktop/
Code run in Anaconda Prompt : python ./metadata_writer_for_image_classifier.py --model_file=./model_without_metadata/mobilenet_v1_0.75_160_quantized_1_default_1.tflite --label_file=./model_without_metadata/labels.txt --export_directory=model_with_metadata
Current directory : /Desktop


[mobilenet_v1_0.75_160_quantized_1_default_1.txt](https://github.com/tensorflow/tensorflow/files/5508515/mobilenet_v1_0.75_160_quantized_1_default_1.txt)
[metadata_writer_for_image_classifier.txt](https://github.com/tensorflow/tensorflow/files/5508520/metadata_writer_for_image_classifier.txt)

**Comment by lu-wang-g** [comment]
@hiroki-oist I followed exactly what you did, and it seems working on my end. See:
```
$python ./metadata_writer_for_image_classifier.py --model_file=./mobilenet_v1_0.75_160_quantized_1_default_1.tflite --label_file=labels.txt --export_directory=model_with_metadata
Finished populating metadata and associated file to the model:
./mobilenet_v1_0.75_160_quantized_1_default_1.tflite
The metadata json file has been saved to:
model_with_metadata/mobilenet_v1_0.75_160_quantized_1_default_1.json
The associated file that has been been packed to the model is:
['labels.txt']
```

From the error message, seems like the tflite_support package is not installed successfully. Can you please reinstall the package again? Such as:
```
pip install tflite-support --upgrade
```
