### ISSUE TITLE
tf concatination layers compatible with tfp

### ISSUE THREAD

**Issue by maxkaustav** [tensorflow/tensorflow#44706]
Since tfp does not have `tf.keras.layers.Concatenate` does tf2.x support Concatenation of tfp layers?

If some changes are required then what?

**Comment by ymodak** [comment]
If you can attach a toy example depicting the behavior that will be great addition for the completeness of this issue. Thanks!

**Comment by maxkaustav** [comment]
```
x1=tfp.layers.DenseFlipout(x)
x2=tfp.layers.DenseFlipout(x_)
x4=tf.keras.layers.Concatenate(x1,x)
```
with tf_2.3 is it possible
if tfp=tensorflow probability

**Comment by tomerk** [comment]
Are you saying that this is working with TF 2.4 or are you running into issues when trying it?

**Comment by maxkaustav** [comment]
I have not tested yet.
