### ISSUE TITLE
 3760 illegal hardware instruction  python3

### ISSUE THREAD

**Issue by arun4ss** [tensorflow/tensorflow#44701]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): KALI LINUX
- TensorFlow installed from (source or binary): PIP3 INSTALL TENSORFLOW
- TensorFlow version: 
tensorflow             2.3.1
tensorflow-estimator   2.3.0

- Python version:  Python 3.8
- Installed using virtualenv? pip? conda?:  pip3

- GPU model and memory: HP pavillion g4 intel i5 m480 6gb ram

**Describe the problem**
when ever i try to import tensorflow in my python program as tf

i got this in output as error  :-  ' 3760 illegal hardware instruction  python3 '

**Provide the exact sequence of commands / steps that you executed before running into the problem**

>>> import tensorflow as tf
[1]    3760 illegal hardware instruction  python3

**Comment by ravikyram** [comment]
@arun4ss 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements).

Also, refer this [SO link](https://stackoverflow.com/questions/49327879/illegal-hardware-instruction-when-trying-to-import-tensorflow) and see if it helps you. Thanks!

**Comment by arun4ss** [comment]
> @arun4ss 
> 
> What is make/model of your cpu?
> I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements).
> 
> Also, refer this [SO link](https://stackoverflow.com/questions/49327879/illegal-hardware-instruction-when-trying-to-import-tensorflow) and see if it helps you. Thanks!
> 
> 
> 

    Cpu model is :- Intel Core i5-480M
How to cheak if my cpu support AVX or not?

I have checked the [SO link](https://stackoverflow.com/questions/49327879/illegal-hardware-instruction-when-trying-to-import-tensorflow)
But  it's code is different from my issue 
It is **4492 illegal hardware instruction (core dumped)  python**

And 

My issue is **3760 illegal hardware instruction python3**

**Comment by ravikyram** [comment]
@arun4ss 

As per Intel's [product specification](https://ark.intel.com/content/www/us/en/ark/products/52952/intel-core-i5-480m-processor-3m-cache-2-66-ghz.html), your CPU doesn't support AVX. For more information, please take a look at the [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements) to install TensorFlow with pip.
Alternatively, you can build [TensorFlow from source](https://www.tensorflow.org/install/source) or use [Google Colab](https://colab.research.google.com/). Thanks!

**Comment by notduckduckcode** [comment]
According to the hardware requirements, my CPU does support AVX but Tensorflow refuses to run. I have a `Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz` and I'm running Ubuntu 20.4 LTS with Python 3.8.5.
```
Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
[1]    54557 illegal hardware instruction (core dumped)  python
```

**Comment by mihaimaruseac** [comment]
See #45744 and #45866

**Comment by mihaimaruseac** [comment]
Deduplicating to #45744 (randomly chosen among multiple duplicates)
