### ISSUE TITLE
SegmentSum GPU OP has no incremental detection on segment_ids

### ISSUE THREAD

**Issue by Lifann** [tensorflow/tensorflow#44700]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 8
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): r1.15
- Python version: 3.6.8
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 4.8.5
- CUDA/cuDNN version: 10.1
- GPU model and memory: Telsa V100

**Describe the current behavior**
In `tf.segment_sum` GPU version, there is no incremental check on segment_ids. I tried an unsorted segment_ids, and get a wrong result without any exception or warning.

**Describe the expected behavior**
If the segment_ids is required in an incremental sequence,  I think there should be an exception or warning in the implementation.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```python3
import tensorflow as tf

with tf.device('/GPU:0'):
  data = tf.constant([[1,2], [3,4], [5,6], [7,8]], dtype=tf.float32)

  seg_ids = tf.constant([0,0,1,0], dtype=tf.int32)

  gpu_op = tf.segment_sum(data, seg_ids)
  #Got [[16. 20.]].
  #But an exception or warning is expected.
```

**Comment by Saduf2019** [comment]
@Lifann 
There is support for 2.x only, Can you please upgrade your tf version and let us know if you face any issues on 2.x
