### ISSUE TITLE
sequences_to_texts on character level tf.keras.preprocessing.text.Tokenizer adds spaces between characters

### ISSUE THREAD

**Issue by SteveGdvs** [tensorflow/tensorflow#44709]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10 2004**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **v2.3.0-54-gfcc4b966f1 2.3.1** and **v2.3.0-0-gb36436b087 2.3.0**
- Python version: **3.7.9** and **3.6.9**

**Describe the current behavior**
The `tf.keras.preprocessing.text.Tokenizer` with `char_level=True` adds spaces between characters when the `sequences_to_texts` is called. For example if our data is `["Hi"]` and we convert them to sequence and then back to text the output will be `["h i"]`

**Describe the expected behavior**
Spaces should not be added.
For example if our data is `["Hi"]` -> sequence -> ["hi"].

**Standalone code to reproduce the issue**
```
from tensorflow.keras.preprocessing.text import Tokenizer

text_data=["Hello","Run"]
print(text_data)

tok = Tokenizer(char_level=True)
tok.fit_on_texts(text_data)
sequences = tok.texts_to_sequences(text_data)
print(sequences)

reconstructed_text = tok.sequences_to_texts(sequences)
print(reconstructed_text)
```

**Comment by Saduf2019** [comment]
@SteveGdvs 
This is a character level sequencer, hence the result, you may join it afterwards.

**Comment by SteveGdvs** [comment]
@Saduf2019 
Maybe I didn't explain it correctly or I am mistaken, but I will try again.

If it was a word level sequencer and we give it as input `["hello world my name is Steve"]` it would convert it to a sequence of integers (for example) `[1,2,3,4,5,6]` and by calling `sequences_to_texts` we can convert the numbers back to the original string `["hello world my name is Steve"]`.

But in a character level sequencer if we give as input `["hello"]` it will be converted to a sequence `[1,2,3,3,4]` but by calling the `sequences_to_texts` we don't get the same input back but we get this `["h e l l o"]`.

Maybe I don't understand how to use the `sequences_to_texts` in a character level sequencer but I think the output should be `["hello"]` and not `["h e l l o"]`.

With the following code I demonstrate what I say above

```
from tensorflow.keras.preprocessing.text import Tokenizer

text_data=["Hello world","Run as fast as you can!"]
print(text_data)

print("char level Tokenizer")

char_tok = Tokenizer(char_level=True)
char_tok.fit_on_texts(text_data)
char_sequences = char_tok.texts_to_sequences(text_data)
print(char_sequences)

char_reconstructed_text = char_tok.sequences_to_texts(char_sequences)
print(char_reconstructed_text)

print("word level Tokenizer")

word_tok = Tokenizer(char_level=False)
word_tok.fit_on_texts(text_data)
word_sequences = word_tok.texts_to_sequences(text_data)
print(word_sequences)

word_reconstructed_text = word_tok.sequences_to_texts(word_sequences)
print(word_reconstructed_text)
```

**Comment by Saduf2019** [comment]
i am able to replicate the issue faced, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/87427fe212c2935cf9b5d0bbc617b537/untitled462.ipynb).

**Comment by ymodak** [comment]
I think this is by design an intended behavior. The document says,
> By default, all punctuation is removed, turning the texts into space-separated sequences of words (words maybe include the ' character)

https://github.com/keras-team/keras-preprocessing/blob/58df11e1145b2088092252c4dba02168c6da2b13/keras_preprocessing/text.py#L363

**Comment by SteveGdvs** [comment]
Sorry for the late response.

If this is intended then how can I convert a sequence to the original string?
If the problem is only on the line you mentioned then can this be the solution?

```
if self.char_level:
    vect = ''.join(vect)
else:
    vect = ' '.join(vect)
```

**Comment by ymodak** [comment]
You may try with 
```python
from tensorflow.keras.preprocessing.text import Tokenizer

text_data=["Hello","Run"]
print(text_data)

tok = Tokenizer(char_level=True)
tok.fit_on_texts(text_data)
sequences = tok.texts_to_sequences(text_data)
print(sequences)

reconstructed_text = tok.sequences_to_texts(sequences)
print(reconstructed_text)

# Generating text from sequence (mapping back)
word_index = tok.word_index
reverse_map = {v: k for k, v in word_index.items()} # map back
print(reverse_map) 
#{1: 'l', 2: 'h', 3: 'e', 4: 'o', 5: 'r', 6: 'u', 7: 'n'}
retext = ''
for seq in sequences:
    for q in seq:
       retext += reverse_map[q]
    retext += ' ' 
print(retext)
#hello run
