### ISSUE TITLE
Actor-critic model with LSTM layers runs out of GPU memory eventhough it shouldn't.

### ISSUE THREAD

**Issue by mbalazs98** [tensorflow/tensorflow#44705]
- Custom code
- Windows 10
- TensorFlow version: 2.3.1
- Python version: 3.7.9
- CUDA/cuDNN version: 10.1 / 7.6.5
- GPU model and memory: GTX 1660 6GB

Networks with LSTM layers run out of memory, using only batch at a time. Creating smaller layers don't help.By my calculations they should easily fit into the memory.

Source code to recreate the issue is the following (in a few places it uses bogus values, it was only created to test if there are issues with the fit function):

`
import os
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers     import LSTM, Dense, Dropout, Input, concatenate, Lambda
from tensorflow.keras            import activations
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models     import Model
import tensorflow.keras.backend as K

physical_devices = tf.config.experimental.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], enable=True)

delta = Input(shape=[1])

input_vision = Input(shape=(2* 5+1,2* 5+1))
first_branch = LSTM(1024)(input_vision)#Input layer of the 1. branch
first_branch = Dropout(0.2)(first_branch)       #Dropout for the input layer

first_branch = Dense(512, activation=activations.relu)(first_branch)       #First layer of the 1. branch
first_branch = Dropout(0.2)(first_branch)

first_branch = Dense(256, activation=activations.relu)(first_branch)       #Second layer of the 1. branch
first_branch = Dropout(0.2)(first_branch)

first_branch = Model(inputs=input_vision, outputs=first_branch)      #The output of the first branch

input_memory  = Input(shape=(100,3))
second_branch = LSTM(1024)(input_memory)       #Input layer of the 2. branch
second_branch = Dropout(0.2)(second_branch)     #Dropout for the input layer

second_branch = Dense(512, activation=activations.relu)(second_branch)     #Second layer of the 2. branch
second_branch = Dropout(0.2)(second_branch)     #Dropout for the first layer

second_branch = Dense(256, activation=activations.relu)(second_branch)     #Third layer of the 2. branch
second_branch = Dropout(0.2)(second_branch)     #Dropout for the first layer

second_branch = Model(inputs=input_memory, outputs=second_branch)    #The output of the first branch

input_task   = Input(shape=(5, 6) )
third_branch = LSTM(1024)(input_task)    #Input layer of the 3. branch
third_branch = Dropout(0.2)(third_branch)       #Dropout for the input layer

third_branch = Dense(512, activation=activations.relu)(third_branch) #Second layer of the 3. branch
third_branch = Dropout(0.2)(third_branch)       #Dropout for the first layer

third_branch = Dense(256, activation=activations.relu)(third_branch) #Third layer of the 3. branch
third_branch = Dropout(0.2)(third_branch)       #Dropout for the first layer

third_branch = Model(inputs=input_task, outputs=third_branch)#The output of the first branch

#Combine all 3 branches into one:
#combined = tf.keras.backend.expand_dims(combined, axis=-1)
combined = concatenate([first_branch.output, second_branch.output, third_branch.output])
combined = Lambda(lambda x: tf.keras.backend.expand_dims(x, axis=-1))(combined)

#Main branch:

main = LSTM(1024)(combined)       #The 1. layer of the main branch
main = Dropout(0.2)(main)

main = Dense(512, activation=activations.relu)(main)  #The 2. layer of the main branch
main = Dropout(0.2)(main)

main = Dense(256, activation=activations.relu)(main)  #The 3. layer of the main branch
main = Dropout(0.2)(main)

#------------------------------------------------These are the outputs of the  models------------------------------------------------
#This is the output of the critic model. The input is one because we just want the value of 1 action, which was taken by the actor.
values = Dense(1, activation=activations.linear)(main)

#This is the output of the actor model. We get the probabilities of each action, that is why softmax needed.
probabilities = Dense(32, activation=activations.softmax)(main)

#This is the policy network needed to connect the actor and the critic:
#y_true is an action that the actor took, and y_pred the probability of that action
def custom_logLikelihood(y_true, y_pred):
     out     = K.clip(y_pred, 1e-8, 1-1e-8) #Clip the prediction so it can not be 0 or 1.
     log_lik = y_true * K.log(out)

     return K.sum(-log_lik * delta)

#------------------------------------------------These are the  models------------------------------------------------
actor = Model(inputs=[first_branch.input, second_branch.input, third_branch.input, delta], outputs=probabilities)
actor.compile(loss=custom_logLikelihood, optimizer=Adam(lr=0.0001), experimental_run_tf_function=False)
tf.config.experimental_run_functions_eagerly(True)  

critic = Model(inputs=[first_branch.input, second_branch.input, third_branch.input], outputs=values)
critic.compile(loss="mse", optimizer=Adam(lr=0.0005))

prev_state_vis=np.random.randint(0, 20, size=(11,11))
prev_state_mem=np.random.randint(0, 20, size=(100,3))
prev_state_task=np.random.randint(0, 20, size=(5,6))
curr_state_vis=np.random.randint(0, 20, size=(11,11))
curr_state_mem=np.random.randint(0, 20, size=(100,3))
curr_state_task=np.random.randint(0, 20, size=(5,6))  

prev_state_v = prev_state_vis[np.newaxis, :]
prev_state_m = prev_state_mem[np.newaxis, :]
prev_state_t = prev_state_task[np.newaxis, :]
curr_state_v = curr_state_vis[np.newaxis, :]
curr_state_m = curr_state_mem[np.newaxis, :]
curr_state_t = curr_state_task[np.newaxis, :]

critic_value_prev = critic.predict_on_batch([prev_state_v,
                                                          prev_state_m, 
                                                          prev_state_t])
critic_value_curr = critic.predict_on_batch([curr_state_v,
                                                          curr_state_m, 
                                                          curr_state_t])
target  = 10 + 0.99 * critic_value_curr * (1-int(0))
d   = target - critic_value_prev
actions = np.zeros([1, 32])
actions[np.arange(1), 0] = 1.0

for i in range(0,500*100):
    print(i)
    actor.fit(x=[prev_state_v, prev_state_m, prev_state_t, d], y=actions, verbose=0)
    critic.fit(x=[prev_state_v, prev_state_m, prev_state_t], y=target, verbose=0)
`

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/df90560119494e74b2e26d6090f7033c/untitled504.ipynb).You are also seeing the same behavior?

Thanks!

**Comment by mbalazs98** [comment]
The fit of the actor and critic is in the for loop, and for me fails after about 30 iterations.

**Comment by mbalazs98** [comment]
> I have tried in colab with TF version 2.3. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/df90560119494e74b2e26d6090f7033c/untitled504.ipynb).You are also seeing the same behavior?
> 
> Thanks!

![image](https://user-images.githubusercontent.com/49280623/98678649-30a64380-235f-11eb-9983-93f9d92415b7.png)

**Comment by mbalazs98** [comment]
> I have tried in colab with TF version 2.3. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/df90560119494e74b2e26d6090f7033c/untitled504.ipynb).You are also seeing the same behavior?
> 
> Thanks!

The fit of the actor and critic is in the for loop and for me fails after about 30 iterations.

**Comment by ravikyram** [comment]
@mbalazs98 

Please, share the log of the error if any.Also, try setting hard limit on GPU as shown in this [guide](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth).Thanks!

**Comment by mbalazs98** [comment]
> @mbalazs98
> 
> Please, share the log of the error if any.Also, try setting hard limit on GPU as shown in this [guide](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth).Thanks!

I forgot to mention that I already tried hard limiting the memory usage, it didn't help. The error message is the following:
InternalError: Failed to call ThenRnnBackward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 1, 1024, 1, 768, 1, 1024]  [Op:CudnnRNNBackprop]

**Comment by ravikyram** [comment]
@mbalazs98 

Can you please refer similar issue #41444, #37942 and see if it helps you. Thanks!

**Comment by mbalazs98** [comment]
> @mbalazs98
> 
> Can you please refer similar issue #41444, #37942 and see if it helps you. Thanks!

#41444 doesn't seem to be the issue, since that is windows related and this code fails on colab also. I tried every suggestion already given in #37942 but the results didn't change. Also, I think that it is not related to the batches since these networks are given only one batch in an iteration.

**Comment by jvishnuvardhan** [comment]
@mbalazs98 `model.fit` manages its own tf.function and runs training in graph mode for faster computations. When you run `model.fit` in a for-loop and provide numpy inputs (which is considered as different input signature each iteration in for-loop), each graph is traced separately and there will be `n` number of models in the memory and consume lot of memory. You can garbage collect and clear the memory or provide tensor inputs which is considered same input signature (in your-case) and the same graph model is used for all those iterations.

So, I converted inputs to Tensors and provided as inputs. The code runs upto 130 iterations and throws different error. Can you please check whether there is any issue in data or in `critic.fit(x=[prev_state_v, prev_state_m, prev_state_t], y=target, verbose=0)`. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/f13df62639197a6d651015b194b008bd/untitled504.ipynb). Thanks!

**Comment by mbalazs98** [comment]
> @mbalazs98 `model.fit` manages its own tf.function and runs training in graph mode for faster computations. When you run `model.fit` in a for-loop and provide numpy inputs (which is considered as different input signature each iteration in for-loop), each graph is traced separately and there will be `n` number of models in the memory and consume lot of memory. You can garbage collect and clear the memory or provide tensor inputs which is considered same input signature (in your-case) and the same graph model is used for all those iterations.
> 
> So, I converted inputs to Tensors and provided as inputs. The code runs upto 130 iterations and throws different error. Can you please check whether there is any issue in data or in `critic.fit(x=[prev_state_v, prev_state_m, prev_state_t], y=target, verbose=0)`. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/f13df62639197a6d651015b194b008bd/untitled504.ipynb). Thanks!

The error is slightly different, but as I see it is still related to memory, and it is definitely not expected. It fails the same way without fitting the critic network, so it shouldn't be related to that either.

**Comment by fchollet** [comment]
Could you provide us with a memory profile?

Cf https://github.com/tensorflow/profiler
https://www.tensorflow.org/guide/profiler

What's the minimum batch size that you can run this model with?

**Comment by mbalazs98** [comment]
> Could you provide us with a memory profile?
> 
> Cf https://github.com/tensorflow/profiler
> https://www.tensorflow.org/guide/profiler
> 
> What's the minimum batch size that you can run this model with?

Unfortunately the model crashes before it can log anything. It fails with a batch size of 1, so that can't be decreased.

**Comment by mbalazs98** [comment]
I realised that the error is probably related to the custom likelihood function. When compiling the actor network 'experimental_run_tf_function' was set as false and 'tf.config.experimental_run_functions_eagerly' was set as true, otherwise tf gives the following error:

TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: input_7:0

Could I be right about this? If yes, how could this be solved?

**Comment by connors2015** [comment]
> @mbalazs98 `model.fit` manages its own tf.function and runs training in graph mode for faster computations. When you run `model.fit` in a for-loop and provide numpy inputs (which is considered as different input signature each iteration in for-loop), each graph is traced separately and there will be `n` number of models in the memory and consume lot of memory. You can garbage collect and clear the memory or provide tensor inputs which is considered same input signature (in your-case) and the same graph model is used for all those iterations.
> 
> So, I converted inputs to Tensors and provided as inputs. The code runs upto 130 iterations and throws different error. Can you please check whether there is any issue in data or in `critic.fit(x=[prev_state_v, prev_state_m, prev_state_t], y=target, verbose=0)`. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/f13df62639197a6d651015b194b008bd/untitled504.ipynb). Thanks!

Hi folks, sorry if this is out of protocol but what @jvishnuvardhan is talking about happens to me constantly and seems to cover 90% of the problems with running a model in a loop bugs (since before TF2.0). The pandas Series and Dataframe objects, along with the numpy arrays seem to get 'stuck' in memory during a loop. Even deleting the model object from my loop or creating it in my loop causes the same memory growth.

The only known solution that's completely solved it has been disabling eager execution, which, and someone please correct me if I'm wrong, forces tensorflow to treat everything as a tensor instead? 

Hopefully someone who knows what they're talking about can look into this but disabling eager execution pretty much solves all memory accumulation errors in a TF loop.

**Comment by jvishnuvardhan** [comment]
@mbalazs98 Is this still an issue for you? Can you please check with recent TF versions (`TF2.7 and `tf-nightly`) and let us know whether issue is still persisting. 

Please note that Keras development moved to another repository to focus entirely on only keras. Could you please repost this issue on [keras-team/keras repo](https://github.com/keras-team/keras/issues). Thanks!
