### ISSUE TITLE
On-disk cache for compiled functions

### ISSUE THREAD

**Issue by bdch1234** [tensorflow/tensorflow#44710]
Is there a way to cache compiled tf.functions in between sessions with auto-load? As a reference, numba has the option cache=True:
https://numba.readthedocs.io/en/stable/user/jit.html?highlight=cache#cache

**System information**
- TensorFlow version (you are using):
2.3.1

**Comment by nikitamaia** [comment]
Hi @bdch1234l, can you provide some more information on your use case? Specifically, is there a use case you have where this is causing performance issues? Additionally, are you referring to caching JIT compilation of concrete functions?
Also linking to the ["Better Performance with tf.function"](https://www.tensorflow.org/guide/function#setup) guide in case you haven't seen it yet.

**Comment by bdch1234** [comment]
Hi @nikitamaia, thanks for looking into this.

My use case is that I have a fairly complex code-base which is very performance-critical, and this is currently using numba to accelerate it. Given the simpler syntax which came with TF 2.0, I am looking into if I can migrate the numba-code to instead be accelerated by TF (along the lines of [this](https://github.com/google/tf-quant-finance) project e.g.), but I was hoping to avoid incurring any warm-up overhead in the process. The cache-functionality of numba basically saves down a compiled function to disk, to avoid re-compiling the next session. I guess the TF-equivalent would be to save down the compiled and optimized graph which comes from the decoration with tf.function.

**Comment by bhack** [comment]
@bdch1234 You can check about what happens with concrete functions at https://www.tensorflow.org/guide/saved_model?hl=en

**Comment by bdch1234** [comment]
Got it, thanks @bhack. So if I understand it correctly, when saving a Module or so any functions etc this depends on will also be saved. But I would still always need to manually save and restore the "outer" object then?

**Comment by bhack** [comment]
Python code wrapperd by `@tf.function` It Is not saved  you're really saving the tf.function's cache of ConcreteFunctions

**Comment by bdch1234** [comment]
Right, ok. But what I mean is that when saving/loading the cache of ConcreteFunctions, there is no way to have that done automatically? I would always need to save/restore manually?

**Comment by bhack** [comment]
Can you share a very, very minimal but runnable coden example with save and load of what you want?

**Comment by bdch1234** [comment]
Sure, please see below:
```python
@tf.function
def my_complex_operation(x):
  # This would then be some very complex operation, so 
  # TF could take a while to produce the final optimized DAG.
   return x+1 
```
So assume the above function is defined in a library. I load the library and call it, the DAG is compiled and optimized. Every subsequent call to `my_complex_operation` will be super-fast, but the next time I re-run my program I will have to recompile the graph again, unless I manually save and restore the ConcreteFunction (to my understanding).

Corresponding solution when accelerated using numba, would be to use `cache=True`:
```python
@njit(cache=True)
def my_complex_operation(x):
   return x+1 
```
Same as for tensorflow, when I load the library and call it the first time, the function is compiled and optimized. But when the cache-flag is set to True, the compiled specialized function gets saved to a specified directory on disk. So the next time I re-run the program it will not need to recompile, it just loads the compiled version from the cache.

**Comment by bhack** [comment]
Yes I meant a runnable (copy, paste, run) minimal example with a save model and load.

**Comment by bdch1234** [comment]
The question I had in this thread was if something similar to the numba's cache=True exists for TensorFlow (and if not make a feature-request for it). I don't see how this will be answered by writing code to save and restore models manually just to show you what, the complexity of the operations?
If it is useful, the runnable versions of my previous examples are given below.
```python
# TensorFlow version

import tensorflow as tf
import numpy as np

@tf.function
def my_complex_operation(x):
    return x+1

my_complex_operation(np.random.rand(10))
```

```python
# Numba version

from numba import njit
import numpy as np

@njit(cache=True)
def my_complex_operation(x):
    return x+1

my_complex_operation(np.random.rand(10))
```
The difference is that the compile-overhead for numba only happens once, even if I close down the python-session and start over again. Is that possible to achieve with TensorFlow?

**Comment by bhack** [comment]
From the early comment I was talking about load and saved model. I don't think you have an helper to directly save and load single function cache.

**Comment by bdch1234** [comment]
Well, then you just answered my question. Thank you.

@nikitamaia, might it then be a good idea to bring back the "type:feature"-label? Or is this something you can directly say that TensorFlow will not support?

**Comment by bhack** [comment]
I meant there is code to save concrete function  but I think not in single public API  call. You can check https://github.com/tensorflow/tensorflow/blob/v2.3.1/tensorflow/python/saved_model/save.py

I suggest you to check the in-memory map cache flow at https://pgaleone.eu/tensorflow/tf.function/2019/03/21/dissecting-tf-function-part-1/#tffunction-layman-explanation

**Comment by nikitamaia** [comment]
@bdch1234 have you seen the resources shared in the above post?

**Comment by bdch1234** [comment]
@nikitamaia, I have but it still not addressing the question I had. 

We have established that a concrete function can be saved manually if needed, but there is no functionality for automatic saving and loading of it (like numba's cache), hence my feature-request. Also, the second link is just a general high-level description of how tf.function works. The closest thing to being useful for this thread in there is that the compiled and optimized graphs are stored in an in-memory map (i.e. the cache), but to make use of that I would need to manually save and load stuff again.

**Comment by bhack** [comment]
Yes this was just a little bit of support info if you want to try to prepare a PR.
@bdch1234 I don't know if you are interested but I think for something like this you need to prepare a design RFC PR at https://github.com/tensorflow/community/

**Comment by bdch1234** [comment]
Got it. Well then thanks for providing the additional info @bhack.

**Comment by nikitamaia** [comment]
Different end use case, but #43800 seems like it would result in a similar feature. Specifically [this comment.](https://github.com/tensorflow/tensorflow/issues/43800#issuecomment-704411480)

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
