### ISSUE TITLE
Add `tf.write_file` op

### ISSUE THREAD

**Issue by gibiansky** [tensorflow/tensorflow#4471]
Tensorflow currently has a `tf.read_file` op, as documented [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/shard1/tf.read_file.md).

Can we have a `tf.write_file` as well?

It could be defined as something like:

``` python
def write_file(tensor, filename, name=None):
    def write_data(data):
        with open(filename, "wb") as handle:
            handle.write(data)

    with tf.name_scope("WriteFile" or name):
        tensor = tf.convert_to_tensor(tensor, name="Values")
        return tf.py_func(write_data, tensor)
```

There are some usecases where this would be helpful, such as generating images and audio and then writing them to disk. Presumably, this would be done after an op such as `encode_jpeg` or `encode_audio`.

If this already exists in some form, please close this – my apologies, but some googling as well as searching on Github did not find it.

**Comment by concretevitamin** [comment]
Contributions welcome!  As a first cut I think the above will work (albeit might not be the most efficient), and we need to use TensorFlow's `file_io` instead of the raw `with open(...) as ...` -- this is to support many platform and file systems.

**Comment by malzantot** [comment]
I am currently working on this.
Thanks,
Moustafa

**Comment by gibiansky** [comment]
@malzantot I believe the op is implemented [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/whole_file_read_ops.cc#L100), using helper function [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/whole_file_read_ops.cc#L30).

You'll probably want to use [NewWritableFile](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/env.h#L103) in place of NewRandomAccessFile and use the resulting file's [Append](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/file_system.h#L248) member function.
