### ISSUE TITLE
TimeDistributed layer and Nested Modules

### ISSUE THREAD

**Issue by marziehoghbaie** [tensorflow/tensorflow#44722]
Hi there,
I am using time distributed layer to apply another model on each frame and processing the final features by conv 3D. the model is trained properly. but when I want to load the model and use it for test, the model acc on the same val dataset is not reproducible.
When I looked the model summary I saw that if I use TimeDistributed layer with a model I can see that model parameters in the summary, but if I use a layer combined with Lambda layer, the number of parameters for that TimeDistributed layer is zero.

- tf version '1.15.0'

- keras version '2.2.3'

```
def feature_extractor_model():
    feature_extractor = keras.applications.mobilenet.MobileNet(
        include_top=False,
        input_shape=(100, 100, 1),
        weights=None)
    for layer in feature_extractor.layers:
        layer.trainable = True
    output_layer = feature_extractor.get_layer(name='conv_pw_1_relu').output
    feature_extractor = Model(inputs=feature_extractor.inputs, outputs=output_layer, name='Feature_Extractor') 
    return feature_extractor
def base_model(inputs, N_classes,
               growth_rate=32, num_features=64,
               bn_size=4, drop_rate=0.5,
               feature_size=256, reg_type='l1'):
    feature_extractor = feature_extractor_model()
    shape = inputs.get_shape().as_list()[2:]
    init_features = TimeDistributed(feature_extractor, input_shape=shape)(inputs)
```
this code works well and I can reproduce the results, but the following code does not work and the number of parameters for the second TimeDistributed layer is Zero:

```
def Squeeze_Att_(features):
    conv_feature_att = Conv2D(filters=1, kernel_size=(1, 1), strides=(1, 1))(features)
    emphasized_features = Multiply()([features, conv_feature_att])
    emphasized_features = Activation('relu')(emphasized_features)
    return emphasized_features

def base_model(inputs, N_classes,
               growth_rate=32, num_features=64,
               bn_size=4, drop_rate=0.5,
               feature_size=256, reg_type='l1'):
    feature_extractor = feature_extractor_model()
    shape = inputs.get_shape().as_list()[2:]
    print(shape)
    init_features = TimeDistributed(feature_extractor, input_shape=shape)(inputs)
    Squeeze_Att__ = Lambda(Squeeze_Att_, name="attention_layer_1")
    init_features = TimeDistributed(Squeeze_Att__, input_shape=shape)(init_features)
```

it seems that TimeDistributed layer only works when the input is a model. Any Suggestion??

**Comment by ravikyram** [comment]
@marziehoghbaie 

Can you please fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Please, let us know the TF version you are using.

Please, share colab link or simple standalone code with proper indentation to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by marziehoghbaie** [comment]
@ravikyram 
TNX, I edited my issue and submitted it in **Issue: Other Issues** template.

**Comment by ravikyram** [comment]
@marziehoghbaie 

In the given code you have defined the function but not calling the function anywhere. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/d90c60779afb5b428dc3014adf073a6a/untitled510.ipynb) with TF version 2.4-rc0. 
Please share the Python script/notebook you are running, so that we can reproduce the issue on our end.
Also, check if you facing the same issue with TF v2.3 as well. Thanks!

**Comment by marziehoghbaie** [comment]
@ravikyram 
thanks for your reply, 
this is my colab link:
[https://colab.research.google.com/drive/1uTWfdp4IQP80Ke9xZekP3KGDff_fmudp?usp=sharing](url)
the problem still remains, however the model is trained successfully but in inference time I get different results even on the same dataset, and to answer the last question about the tensorflow version, because of hardware limitations I can not install tensorflow 2, So I have to use tensorflow 1.x. 
I'd be happy if you could help.

**Comment by marziehoghbaie** [comment]
I should admit that the MobileNet part in the above code works well, and if I train a model with the MobileNet layer it works fine.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
