### ISSUE TITLE
C++ inference with tensorflow1.15

### ISSUE THREAD

**Issue by ZhaoyangLi-nju** [tensorflow/tensorflow#44720]
when I do inference with c++, this problem arised,
"2020-11-10 13:41:29.363429: F tensorflow/core/framework/op.cc:200] Non-OK-status: RegisterAlreadyLocked(deferred_[i]) status: Already exists: Op with name _Arg Aborted (core dumped)
"
tensorflow1.15 python 3.6

**Comment by Saduf2019** [comment]
@ZhaoyangLi-nju 
Tf 1.15 is not supported, please upgrade to 2.x and let us know if you still face any issues.

**Comment by ZhaoyangLi-nju** [comment]
> @ZhaoyangLi-nju
> Tf 1.15 is not supported, please upgrade to 2.x and let us know if you still face any issues.

how about Tf1.14?

**Comment by Saduf2019** [comment]
Tf 2.x only is supported. Please upgrade and let us know.
