### ISSUE TITLE
TFLite TensorArrayScatterV3 failed (not found)

### ISSUE THREAD

**Issue by iBug** [tensorflow/tensorflow#44721]
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04 (work) / Android 9.0 (inference)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Motorola Nexus 6
- TensorFlow installed from (source or binary): Source (master branch at 4625f1d87f17537a8d50dc68a213d2da875c12ce)
- TensorFlow version (use command below): 4625f1d87f17537a8d50dc68a213d2da875c12ce
- Python version: 3.8.2
- Bazel version (if compiling from source): 3.7.0
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: No GPU
- GPU model and memory: N/A

- Android SDK 30.0.2 and NDK r21d

**Describe the current behavior**

I compiled `benchmark_model_plus_flex` and ran into the same issue. I was trying to benchmark the following model:

<http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz>

with it converted into TFLite format with the following code:

```python
def do_convert(saved_model, output_file):
    converter = tf.lite.TFLiteConverter.from_saved_model(saved_model)
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS,
        tf.lite.OpsSet.SELECT_TF_OPS,
    ]
    model = converter.convert()
    with open(output_file, "wb") as f:
        f.write(model)
```

The exact error is

```text
native : op_kernel.cc:1763 OP_REQUIRES failed at tensor_array_ops.cc:1035 : Not found: Container __per_step_0 does not exist. (Could not find resource: __per_step_0/_tensor_arraysTensorArrayV3_774)
ERROR: Container __per_step_0 does not exist. (Could not find resource: __per_step_0/_tensor_arraysTensorArrayV3_774)
         (while executing 'TensorArrayScatterV3' via Eager)
ERROR: Node number 276 (TfLiteFlexDelegate) failed to invoke.
```

and the command line in `adb shell` is

```shell
./benchmark_model_plus_flex --graph=ssd_mobilenet_v1_coco_2018_01_28.tflite
```

**Describe the expected behavior**

The benchmark should proceed successfully.

**Standalone code to reproduce the issue**

**Comment by Saduf2019** [comment]
@iBug 
I ran the code shared on tf nightly and did not see any error, can you please share a colab gist with the code and error reported.
Could you please refer to these resolved issues with the same error and let us know: #42214 , #43270

**Comment by iBug** [comment]
Hi @Saduf2019, thanks for your quick response.

In case I wasn't clear enough, here's everything I've done from scratch to reach that error:
ssd_mobilenet_v1_coco_2018_01_28

- Spin up a new Ubuntu 20.04.1 LTS system in LXD container and install basic requirements (Git, `build-essential` etc.)
- Install Bazel 3.7.0 following [the documentation](https://docs.bazel.build/versions/master/install-ubuntu.html) and Android SDK 30.0.2 and NDK r21d using [sdkmanager CLI tool](https://developer.android.com/studio/command-line/sdkmanager)
- Clone this repository somewhere, and `git checkout 4625f1d87f17537a8d50dc68a213d2da875c12ce`
- Using the configure script, produce the following `.tf_configure.bazelrc`:

    ```
    build --action_env PYTHON_BIN_PATH="/usr/bin/python3"
	build --action_env PYTHON_LIB_PATH="/usr/local/lib/python3.8/dist-packages"
	build --python_path="/usr/bin/python3"
	build --config=xla
	build:opt --copt=-march=native
	build:opt --copt=-Wno-sign-compare
	build:opt --host_copt=-march=native
	build:opt --define with_default_optimizations=true
	build --action_env ANDROID_NDK_HOME="/home/ubuntu/Android/Sdk/ndk-bundle"
	build --action_env ANDROID_NDK_API_LEVEL="23"
	build --action_env ANDROID_BUILD_TOOLS_VERSION="29.0.3"
	build --action_env ANDROID_SDK_API_LEVEL="30"
	build --action_env ANDROID_SDK_HOME="/home/ubuntu/Android/Sdk"
	test --flaky_test_attempts=3
	test --test_size_filters=small,medium
	test:v1 --test_tag_filters=-benchmark-test,-no_oss,-gpu,-oss_serial
	test:v1 --build_tag_filters=-benchmark-test,-no_oss,-gpu
	test:v2 --test_tag_filters=-benchmark-test,-no_oss,-gpu,-oss_serial,-v1only
	test:v2 --build_tag_filters=-benchmark-test,-no_oss,-gpu,-v1only
	build --action_env TF_CONFIGURE_IOS="0"
	```

- Compile TFLite benchmark tool with Flex support:

    ```shell
    bazel build -c opt \
      --config=android_arm \
      --config=monolithic \
      tensorflow/lite/tools/benchmark:benchmark_model_plus_flex
    ```

    Here I used `android_arm` because Nexus 6 is a 32-bit device. I also tried `android_arm64` with another phone (OnePlus 3T) with the same outcome.

- Transfer `bazel-bin/tensorflow/lite/tools/benchmark/benchmark_model_plus_flex` to the Android device, enter `adb shell` and `chmod 755` on the binary

- Grab the model tarball from <http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz> (using Wget or cURL) and extract it (`tar zxf`)
- Convert to TFLite:

    ```python
    import tensorflow as tf

    converter = tf.lite.TFLiteConverter.from_saved_model("ssd_mobilenet_v1_coco_2018_01_28/saved_model")
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS,
        tf.lite.OpsSet.SELECT_TF_OPS,
    ]
    model = converter.convert()
    with open("ssd_mobilenet_v1_coco_2018_01_28.tflite", "wb") as f:
        f.write(model)
    ```

- Transfer `ssd_mobilenet_v1_coco_2018_01_28.tflite` file to the Android device
- Run benchmark:

    ```shell
    ./benchmark_model_plus_flex --graph=ssd_mobilenet_v1_coco_2018_01_28.tflite
    ```

- The error message comes from the above command.

May I know how you managed to run the benchmark successfully?

**Comment by iBug** [comment]
Hi @Saduf2019, thank you for your references.

The first linked issue (#42214) was easy to find from Google and I've already seen it a dozen times. I couldn't extract anything helpful to me. However one of the comments (<https://github.com/tensorflow/tensorflow/issues/43270#issuecomment-694619122>) from your second linked issue said:

> TensorArrayScatterV3 op is currently not supported by either TensorFlow Lite builtin op set or Flex delegate.

Do I have to manipulate the SSD MobileNet V1 model somehow before I could run it with TFLite?

**Comment by abattery** [comment]
Sorry for encountering this issue on your side. We are working on TensorArrayScatterV3 support in TFLite. Will update this thread once the TensorArray related issues in TFLite have been resolved.

**Comment by FishWoWater** [comment]
@abattery any progress on this?

**Comment by abattery** [comment]
Please try out the recent TF version. We delivered a better story for supporting tensor list ops.
