### ISSUE TITLE
Make the gradient computation available in the C api

### ISSUE THREAD

**Issue by LaurentMazare** [tensorflow/tensorflow#4473]
When writing TensorFlow bindings for other languages, a major difficulty is that the C api does not give a simple way to add gradient computations to a graph. In the case of the [tensorflow-ocaml](https://github.com/LaurentMazare/tensorflow-ocaml) bindings, we ended up re-implementing back-propagation and having to register gradients for many operators. Providing support for this in the C api would allow us to remove all this code.

There is already a [todo](https://github.com/tensorflow/tensorflow/blob/r0.10/tensorflow/c/c_api.h#L505) for this in the code but having a proper issue would make this easier to track.

**Comment by jmchen-g** [comment]
We are actually already working on this and will have it included in the release notes when it is public (no eta yet though). So I will close this for now.
