### ISSUE TITLE
Dependencies for BERT-QA android not clear

### ISSUE THREAD

**Issue by itsmemuthu** [tensorflow/tensorflow#44734]
**System information**
- OS Platform and Distribution - (Linux Ubuntu 16.04)

Gradle and android SDK version not specified in the README of Android bert-qa for Question Answering
https://github.com/tensorflow/examples/tree/master/lite/examples/bert_qa/android

It would be helpful if you could add those details.

**Comment by ymodak** [comment]
Gradle 5.4.1
SDK Build Tools 28.0.3 or higher.
https://developer.android.com/studio/releases/gradle-plugin#3-5-0
