### ISSUE TITLE
run out of heap space when compiling kernel bias_op.cc

### ISSUE THREAD

**Issue by oldoldman** [tensorflow/tensorflow#44749]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3.1
- Python version: 2.7
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 3.7.0
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA / 16GB

**Describe the problem**
### please help!
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by oldoldman** [comment]
sorry . the complete error message is 
### unsupported\Eigen\CXX11\src\Tensor\TensorBroadcasting.h(653) : fatal error C1002: compiler is out of heap space in pass 2

**Comment by ravikyram** [comment]
@oldoldman 

Please, see tested build configuration from [here](https://www.tensorflow.org/install/source_windows#cpu). Can you try with python 3.5-3.8 and verify once. Thanks!

**Comment by oldoldman** [comment]
> @oldoldman
> 
> Please, see tested build configuration from [here](https://www.tensorflow.org/install/source_windows#cpu). Can you try with python 3.5-3.8 and verify once. Thanks!

passed after changed compiler to clang. thanks!
