### ISSUE TITLE
tf.nn.depth_to_space is not support

### ISSUE THREAD

**Issue by goldflower** [tensorflow/tensorflow#44759]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10 enterprise
- TensorFlow installed from (source or binary): binary (pip install tensorflow==1.14)
- TensorFlow version (or github SHA if from source): 1.14

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, BATCH_TO_SPACE_ND, CONV_2D, DEPTHWISE_CONV_2D, SPACE_TO_BATCH_ND, SPACE_TO_DEPTH. Here is a list of operators for which you will need custom implementations: DEPTH_TO_SPACE.
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

https://gist.github.com/goldflower/dec52a344de461413ae10de84a555b44

**Any other info / logs**

The code above create the pb file and reproduce the issue.

https://www.tensorflow.org/mlir/tfl_ops

Here says tfl.depth_to_space (TFL::DepthToSpaceOp) can be support but actually not?

**Comment by ravikyram** [comment]
@goldflower 

Can you try with TF 2.x recent stable version like 2.3 and see if the issue still persists. Thanks!

**Comment by goldflower** [comment]
> @goldflower
> 
> Can you try with TF 2.x recent stable version like 2.3 and see if the issue still persists. Thanks!

I can convert pb to tflite with TFLiteConverter.from_frozen_graph with TF 2.3.

I also noticed that I can use tflite_convert.exe with TF1.14 to convert without any problem.

**Comment by karimnosseir** [comment]
@goldflower So everything is working fine with TF 2.3 but you had issues with TF 1.14 only ?
We had a lot of fixes and supported many features in new TF versions. So it is better to stick with new versions.

**Comment by goldflower** [comment]
@karimnosseir 
I can use the binary (both taco and tflite_convert under 1.14) to convert it without problem.
I'll use those binaries, thanks.
