### ISSUE TITLE
Add support for CUDA 11.1 on Windows 10 for the 8.6 compute capability

### ISSUE THREAD

**Issue by dobromyslova** [tensorflow/tensorflow#44750]
**System information**
- System: Windows 10
- TensorFlow version (you are using): 2.5.0.dev20201108
- Are you willing to contribute it (Yes/No): Yes. I can do the testing of the new build and provide any additional information.

- TensorFlow version (you are using): 2.5.0.dev20201108
- Python version: 3.8.6-amd64
- Compiler: MSVC 2019
- cuDNN: 8.0.4.30
- CUDA: 11.0.3_451.82
- ptxas: from CUDA 11.1
- NVIDIA Drivers: 456.71

Hello TensorFlow team. I recently got working on my RTX 3090 on the Windows 10 machine and decided to share my investigations with you.

Right now I got TensorFlow 2.5.0.dev20201108 work with CUDA 11.0 and ptxas.exe (PTX compiler) from CUDA 11.1, because ptxas from 11.1 supports 8.6 compute capability and on 11.0 - I'm getting error `ptxas fatal : Value 'sm_86' is not defined for option 'gpu-name'` - which is mean that 11.0 doesn't support 8.6 yet (at least I think so).

So, I don't know if it's planned, but would be great to add support of the CUDA 11.1 for the Win build (I don't know if people having the same issue on the Linux). Because my current solution is kind of hacky (using the compiler from a different version) and even though I don't see any errors right now, it could potentially cause some in the future.

Here is also detailed info on my finding: [https://dobromyslova.medium.com/making-work-tensorflow-with-nvidia-rtx-3090-on-windows-10-7a38e8e582bf](https://dobromyslova.medium.com/making-work-tensorflow-with-nvidia-rtx-3090-on-windows-10-7a38e8e582bf)

Please feel free to contact me for any additional information.

**Comment by mihaimaruseac** [comment]
@sanjoy @pkanwar23 can you take it from here?

**Comment by WeiChihChern** [comment]
Been using tensorflow/tensorflow:nightly-gpu-jupyter, even the latest nightly images (2.5.0-dev20201112) have the issue still with RTX 3090. Any insights?

**Comment by dobromyslova** [comment]
> Been using tensorflow/tensorflow:nightly-gpu-jupyter, even the latest nightly images (2.5.0-dev20201112) have the issue still with RTX 3090. Any insights?

My insides - I got some performance issues (too slow learning) until I applied temporary fix for the PTX compilations. You can read more in the article that I posted in the description: [https://dobromyslova.medium.com/making-work-tensorflow-with-nvidia-rtx-3090-on-windows-10-7a38e8e582bf](https://dobromyslova.medium.com/making-work-tensorflow-with-nvidia-rtx-3090-on-windows-10-7a38e8e582bf)

**Comment by WeiChihChern** [comment]
@dobromyslova Thanks for the info.  Just tried with images provided by [Nvidia](https://ngc.nvidia.com/catalog/containers/nvidia:tensorflow/tags) which works with my RTX 3090, and the performance did improve.  If you used docker, definitely check it out.

**Comment by dobromyslova** [comment]
Thank you for the information, I will try this as well

**Comment by sanjoy** [comment]
> because ptxas from 11.1 supports 8.6 compute capability and on 11.0 - I'm getting error ptxas fatal : Value 'sm_86' is not defined for option 'gpu-name' - which is mean that 11.0 doesn't support 8.6 yet (at least I think so).

Is this when building TensorFlow from source?

If yes, you can try to explicitly select compute capability 8.0 (and not 8.6) when `configure` asks you about it.  TF built with CC 8.0 should work on 3090, though perhaps not with peak performance, and CUDA 11.0 supports 8.0.

**Comment by dobromyslova** [comment]
>Is this when building TensorFlow from source?

No, I used already prebuilt TensorFlow from pip, the one that currently works for me is the `2.5.0.dev20201108` one.

Right now I don't have any issues with this version, but if you want I can try to build it from source with compute capability 8.0, just let me know if you want me to try.

**Comment by bayesrule** [comment]
exactly the same issue on Linux

**Comment by dou3516** [comment]
the same issue

**Comment by gadagashwini** [comment]
@dobromyslova, This issue is fixed in latest Tensorflow version.
Build Tensorflow version with Bazel 5.0.0/4.2.1. Follow the instructions mentioned [here](https://www.tensorflow.org/install/source_windows). Thanks!

**Comment by dobromyslova** [comment]
Thank you, I will try and let you know.

**Comment by dobromyslova** [comment]
Okay, I can confirm that latest build of TensorFlow is now working without an issues on RTX 3090 (8.6 compute capability)!

Thank you for the hard work!

Here is also some profile data from my runs:
### With tf-nightly-gpu
Install TF:
```commandline
pip install tf-nightly-gpu
pip install tensorflow-hub
pip install matplotlib
```

Results of run:
```commandline
$ python validate_build.py

TensorFlow version: 2.8.0-dev20211030
Eager mode enabled: True
GPU available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
CUDA version: 64_112
cuDNN version: 64_8

2022-03-28 22:06:45.962369: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-03-28 22:06:46.344298: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21674 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:01:00.0, compute capability: 8.6
2022-03-28 22:07:00.136319: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101

Elapsed time: 21.45432949066162 sec
```

### With tensorflow-gpu
Install TF:
```commandline
python -m pip install -U pip

pip install tensorflow-gpu==2.8.0
pip install tensorflow-hub
pip install matplotlib
```

Results of run:
```commandline
$ python validate_build.py

TensorFlow version: 2.8.0
Eager mode enabled: True
GPU available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
CUDA version: 64_112
cuDNN version: 64_8

2022-03-28 22:17:11.289526: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-03-28 22:17:11.657375: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21676 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:01:00.0, compute capability: 8.6
2022-03-28 22:17:15.023230: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101

Elapsed time: 6.308921813964844 sec
```
