### ISSUE TITLE
Cannot execute ./configure

### ISSUE THREAD

**Issue by rxng8** [tensorflow/tensorflow#44755]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Not Applicable
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20 window subsystem.
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not Applicable
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): master branch
- Python version: 3.8.2
- Bazel version (if compiling from source): Not Applicable
- GCC/Compiler version (if compiling from source): Not Applicable
- CUDA/cuDNN version: Not Applicable
- GPU model and memory: Not Applicable

**Describe the current behavior**

./configure does not execute

**Describe the expected behavior**

./configure should execute

**Standalone code to reproduce the issue**

Please clone and do `./configure` on ubuntu on window subsystem. It will not work!

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
./configure: line 2: $'\r': command not found  : invalid optione 3: set: -                                                                                             set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]   : invalid option nameset: pipefail                                                                                      ./configure: line 5: $'\r': command not found
./configure: line 16: syntax error: unexpected end of file
```

**Comment by ravikyram** [comment]
@rxng8 

Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!

**Comment by mihaimaruseac** [comment]
Does `python configure.py` work?

It is very likely the issue is on your system, we cannot know without additional checks.

**Comment by rxng8** [comment]
Yes, `python configure.py` does work, thank you!

**Comment by rxng8** [comment]
I think we should still make a note that the command `./configure` does not work with Linux in Windows subsystem.

**Comment by mihaimaruseac** [comment]
I think the issue is on your system, it was looking for the wrong end of line marker (`\r\n` instead of `\n`).

We are building our pip wheels on Windows using WSL, afaik
