### ISSUE TITLE
ImportError: cannot import name 'np_utils' in ImageDataGenerator

### ISSUE THREAD

**Issue by rakeshmothukuru1** [tensorflow/tensorflow#44765]
The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/ImageDataGenerator#examples_2

### Clear description: `np_utils` is no longer available. It should be replaced with `utils`. Reproducible code is mentioned in [this Colab](https://colab.research.google.com/gist/rmothukuru/ebaf4d013cfaaba3816353cb5b8e3604/bug_fix_imagedatagen_flow.ipynb).

For example, why should someone use this method? How is it useful? : Developers using `ImageDataGenerator.flow` use this code.

### Correct links

Is the link to the source code correct? : Yes

### Parameters defined

Are all parameters defined and formatted correctly? : Yes

### Returns defined

Are return values defined? : Yes

### Raises listed and defined

Are the errors defined? No

### Usage example

Is there a usage example? : Yes

### Request visuals, if applicable

Are there currently visuals? If not, will it clarify the content?

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs,
docs API guide: https://www.tensorflow.org/community/contribute/docs_ref and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/31e386806706356954977ff2f431015e/44765.ipynb). Thanks!
