### ISSUE TITLE
Could not compute output tensor even when correct inputs are being passed to keras model

### ISSUE THREAD

**Issue by Pratibha2007** [tensorflow/tensorflow#44766]
I was trying to create frozen graph for the below mentioned model but when I call get_concrete_function i always get assertion error:

  **AssertionError: Could not compute output Tensor("alpha_beta/add:0", shape=(None, 2), dtype=float32)**
Not sure what am I missing here, I have verified the number of inputs are correct and model gives no errors while training with same inputs.
TensorFlow version- 2.3
Any help here would be much appreciated!

def get_model(features:List[F.BaseInputFeature], **kwargs) -> keras.Model:
    inputs, concats = zip(*[feature.get_input() for feature in features])

    def model_block(size, postfix):
        """
        Helper function for creating a dense block.
        Use a fully connected layer followed by Batch Norm and Dropout for 
        Regularization and faster training.
        """
        def result(input):
            model = keras.layers.Dense(size, activation=tf.nn.relu, name='inner_Dense-%s' % postfix)(input)
            model = keras.layers.BatchNormalization(name='inner_BatchNorm-%s' % postfix)(model)
            return keras.layers.Dropout(0.2, name='inner_Dropout-%s' % postfix)(model)
        return result
    print(inputs)
    output = keras.layers.Concatenate(name='inner_concat')(list(concats))
    for i, size in enumerate([256, 256, 256, 128, 128, 128, 64, 64, 64]):
        output = model_block(size, str(i))(output)

    dist = keras.layers.Dense(2, name='alpha_beta', activation=custom_activation)(output)
    print('dist-', dist)
    from keras.utils.generic_utils import get_custom_objects
    from keras.layers import Activation
    from tensorflow.python.tools import freeze_graph
    from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2

    get_custom_objects().update({'custom_activation': Activation(custom_activation)})
    model = tf.keras.Model(inputs=list(inputs), outputs=[dist])

    model.compile(optimizer=keras.optimizers.Adam(lr=1e-2), loss=[loss], metrics=[metric])

    # Convert Keras model to ConcreteFunction
    full_model = tf.function(lambda x: model(x))
    print(full_model)
    full_model = full_model.get_concrete_function(
        tf.TensorSpec(model.inputs[0].shape, model.inputs[0].dtype))
    # Get frozen ConcreteFunction
    frozen_func = convert_variables_to_constants_v2(full_model)
    frozen_func.graph.as_graph_def()
    layers = [op.name for op in frozen_func.graph.get_operations()]
    print("-" * 50)
    print("Frozen model layers: ")
    for layer in layers:
        print(layer)
    print("-" * 50)
    print("Frozen model inputs: ")
    print(frozen_func.inputs)
    print("Frozen model outputs: ")
    print(frozen_func.outputs)
    # Save frozen graph from frozen ConcreteFunction to hard drive
    tf.io.write_graph(graph_or_graph_def=frozen_func.graph,
                      logdir="./frozen_models",
                      name="frozen_graph.pb",
                      as_text=False)

    return model

**Comment by ravikyram** [comment]
@Pratibha2007 

Please, share colab link or simple standalone code with proper indentation and supporting files to reproduce the issue in our environment. It helps us in localizing the issue folder. Thanks!
