### ISSUE TITLE
in nocopts attribute of cc_library rule @jpeg//:simd_none: This attribute was removed.

### ISSUE THREAD

**Issue by mrgloom** [tensorflow/tensorflow#44762]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Catalina 10.15.7 (19H2)
- TensorFlow installed from (source or binary): source
- TensorFlow version: r1.14
- Python version: 
python -V
Python 2.7.16
python3 -V
Python 3.7.7
- Installed using virtualenv? pip? conda?: -
- Bazel version (if compiling from source):
bazel --version
bazel 3.7.0-homebrew
- GCC/Compiler version (if compiling from source):
clang -v
Apple clang version 11.0.3 (clang-1103.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
- CUDA/cuDNN version: -
- GPU model and memory: -

```
git clone --single-branch --branch r1.14 git@github.com:tensorflow/tensorflow.git
cd tensorflow
bazel build tensorflow/tools/graph_transforms:summarize_graph
```

```
ERROR: /private/var/tmp/_bazel_my_user/839731be594c2770db7eceb921cc3596/external/jpeg/BUILD.bazel:488:11: in nocopts attribute of cc_library rule @jpeg//:simd_none: This attribute was removed. See https://github.com/bazelbuild/bazel/issues/8706 for details.
ERROR: /private/var/tmp/_bazel_my_user/839731be594c2770db7eceb921cc3596/external/jpeg/BUILD.bazel:488:11: in nocopts attribute of cc_library rule @jpeg//:simd_none: This attribute was removed. See https://github.com/bazelbuild/bazel/issues/8706 for details.
ERROR: Analysis of target '//tensorflow/tools/graph_transforms:summarize_graph' failed; build aborted: Analysis of target '@jpeg//:simd_none' failed
FAILED: Build did NOT complete successfully (82 packages loaded, 2745 targets configured)
```

**Comment by ravikyram** [comment]
@mrgloom 

TF 1.x is not supported..Can you try with Latest stable releases TF version 2.3 and let us know if you are facing the issue. Thanks!
