### ISSUE TITLE
**kwargs weights - Initialization Layer

### ISSUE THREAD

**Issue by msqueo** [tensorflow/tensorflow#44767]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

When a Layer is initialized, or a subclassed layer as Dense, with 'weights' among the **kwargs, no weights are stored apparently. I believe the bug is in line 2658 in the base_layer.py file.

**Describe the expected behavior**

I would expect to have weights set as per initialization, when calling Layer.get_weights()

**Standalone code to reproduce the issue**

import tensorflow as tf

weights = tf.random.uniform(shape = [20,10]), tf.random.uniform(shape = [10,])

layer = tf.keras.layers.Layer(weights = weights)
dense = tf.keras.layers.Dense(10, weights = weights)

layer.get_weights()
dense.get_weights()

Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@msqueo 

We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]
I ran the code shared on tf 2.3, please refer to [this gist](https://colab.research.google.com/gist/Saduf2019/ed8b3f6db002f57cf0a4b5c7f70cd6af/untitled460.ipynb) and confirm.

**Comment by bhack** [comment]
```
import tensorflow as tf
import numpy as np
weights = np.ones((10, 11))
dense = tf.keras.layers.Dense(units=11, input_shape=(10,),
                          weights=[weights],
                          use_bias=False)
model = tf.keras.models.Sequential()
model.add(dense)
dense_init_weights = model.layers[0].get_weights()
np.allclose(weights,dense_init_weights)
```

**Comment by msqueo** [comment]
@Saduf2019 thanks for taking care of this issue. Yes, I am using it on TensorFlow 2.3.0.
@bhack thanks for your solution. I assume that you are able to retrieve custom weights, initialized at layer inception, only if the layer is assigned to a model. Correct?

**Comment by bhack** [comment]
> thanks for your solution. I assume that you are able to retrieve custom weights, initialized at layer inception, only if the layer is assigned to a model. Correct?

Check layers methods e.g. `build` at https://keras.io/guides/making_new_layers_and_models_via_subclassing/
