### ISSUE TITLE
Missing Windows binaries

### ISSUE THREAD

**Issue by eaplatanios** [tensorflow/tensorflow#44772]
I was wondering why `tensorflow_framework.dll` and `tensorflow_framework.lib` are missing from the released binaries for windows [here](https://www.tensorflow.org/install/lang_c). They are included for the other platforms. I'm not sure what to change to include them in a PR, but can investigate if needed. cc @alextp

**Comment by alextp** [comment]
I'm no longer working on TF.

@aselle can you take a look?

**Comment by Saduf2019** [comment]
@eaplatanios 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

**Comment by eaplatanios** [comment]
@Saduf2019 I selected "Other Issues" for which there was no template. Also, the relevant TF version is the latest release version, 2.3.1, and I linked to the releases page where the binaries are missing in my original post. There are no steps to reproduce because there is not really an error I ran into, but rather just missing binaries from the released zip files.

**Comment by aselle** [comment]
@eaplatanios, are you seeing a concrete error of missing symbols. I'm not sure if the windows build process is different and coalesces everything into tensorflow.dll.

**Comment by eaplatanios** [comment]
@aselle you are right. I'm sorry I missed this because in my CMake config I was explicitly looking for the tensorflow_framework lib in addition to tensorflow. It turns out that `tensorflow.dll` does seem to include all symbols. Thank you! I'll close the issue.

**Comment by aselle** [comment]
@eaplatanios glad you got it working. Thanks for asking!
