### ISSUE TITLE
unable to install 2.4.0rc1 from pip

### ISSUE THREAD

**Issue by iperov** [tensorflow/tensorflow#44775]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows
- TensorFlow installed from (source or binary): pip
- TensorFlow version: 2.4.0rc1
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: pip

```
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu-estimator<2.5.0,>=2.4.0rc0 (from tensorflow-gpu==2.4.0rc1) (from versions: 2.1.0,2.2.0, 2.3.0)
ERROR: No matching distribution found for tensorflow-gpu-estimator<2.5.0,>=2.4.0rc0 (from tensorflow-gpu==2.4.0rc1)
```

**Comment by ymodak** [comment]
You are missing `-` in your command.
Try `pip install==2.4.0-rc1`

**Comment by Saduf2019** [comment]
@iperov 
It is not necessary for you to install tensorflow-estimator first. You may try Installing tensorflow-gpu, which internally will install all the dependencies like tensorflow-estimator, tensorboard. Please check the attached [gist](https://colab.research.google.com/gist/Saduf2019/922280a616618fbe0473e43c66df07e1/untitled460.ipynb) for more. Thanks!

**Comment by iperov** [comment]
pip is last

`pip install tensorflow-gpu==2.4.0-rc1` produces the same error with estimator

`pip install tensorflow-gpu` installs 2.3.1, but I need 2.4.0rc1

**Comment by iperov** [comment]
```
pip install tensorflow-gpu
pip install tensorflow-gpu==2.4.0-rc1
```
same error.

**Comment by iperov** [comment]
did you even read the error?

tensorflow-gpu==2.4.0-rc1
REQUIRES
tensorflow-gpu-estimator<2.5.0,>=2.4.0rc0

but
last version of `tensorflow-gpu-estimator` in pip is 2.3.0

**Comment by mihaimaruseac** [comment]
This is a bug in the release process due to the single pip package renaming. I'll make a new `tensorflow-gpu-estimator` release and then this should be fixed.

**Comment by mihaimaruseac** [comment]
The `tensorflow-gpu-estimator` wheel should be up now.

**Comment by mihaimaruseac** [comment]
This should be solved now. Closing, but please reopen if this is not the case.
