### ISSUE TITLE
Efficient Ragged Tensor support on TFlite

### ISSUE THREAD

**Issue by junhyk** [tensorflow/tensorflow#44776]
**System information**
- TensorFlow version (you are using): 2.5.0.dev20201106
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
![image](https://user-images.githubusercontent.com/26551254/98852580-36a13f00-249b-11eb-8fb6-1c8147ed8fda.png)
While tf.RaggedTensor use int64 tensor as its row_splilts, TFLite does not support int64 indexing or slicing.
Therefore the model using RaggedTensor as input is converted like the figure above, using unnecessary flexStridedSlices.
Further, I don't understand why RaggedTensor operation should be converted into whole lot of StridedSlices.
It should be fused into single operation for efficiency.
So I argue that RaggedTensor support on TFLite should be revised.

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
The one who use RaggedTensor for their TFLite model. For example, the one who are developing natural language processing models.

**Any Other info.**

**Comment by thunderfyc** [comment]
Can you share an example how RaggedTensor is used in your case?

There's no concept of RaggedTensor in execution graph, they are represented as a tensor of values and a tensor with indices.

We have made some effort to make a good support on NLP models when using ragged tensors, but may not be enough.
It would be good to collect more use cases to have a better understanding on what should be covered.

Meanwhile, you can use flex delegate to make it run just like in tensorflow, when complete tflite support is missing.

**Comment by junhyk** [comment]
Hi, I want implement GNN and convert it into TFLite for quantization.
The reason why I chose raggedtensor is that it is useful to represent adjacency lists.
And my implementation requires some raggedtensor indexing, which I think it is quite different with conventional NLP models.

**Comment by junhyk** [comment]
I use some ragged tensor indexing and slicing 
because each layer in my model only require subset of hidden features from the previous layer

**Comment by tilakrayal** [comment]
@jdduke,
The TensorFlow Lite builtin operator library only supports a limited number of TensorFlow operators, not every model is convertible. Please refer to the [operator compatibility](https://www.tensorflow.org/lite/guide/ops_compatibility).

To allow conversion, users can enable the usage of [certain TensorFlow ops](https://www.tensorflow.org/lite/guide/op_select_allowlist) in their TensorFlow Lite model. However, running TensorFlow Lite models with TensorFlow ops requires pulling in the core TensorFlow runtime, which increases the TensorFlow Lite interpreter binary size. For Android, you can avoid this by selectively building only required Tensorflow ops. For the details, refer to [reduce binary size](https://www.tensorflow.org/lite/guide/reduce_binary_size). Please take a look at the official doc link for the [reference](https://www.tensorflow.org/lite/guide/ops_select#convert_a_model).

Also as mentioned you can use flex delegate to make it run just like in tensorflow, when complete tflite support is missing. Thank you!
