### ISSUE TITLE
boringssl: cc1plus: error: command line option '-Wmissing-prototypes' is valid for C/ObjC but not for C++ [-Werror]

### ISSUE THREAD

**Issue by plopresti** [tensorflow/tensorflow#44783]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 8
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: r2.4
- Python version: 3.6
- Installed using virtualenv? pip? conda?: venv
- Bazel version (if compiling from source): 3.5.0
- GCC/Compiler version (if compiling from source): 9.1
- CUDA/cuDNN version: 7
- GPU model and memory: N/A (build issue)

**Describe the problem**

Compiling the r2.4 branch from source on CentOS 8 using gcc-toolset-9, the build fails like so:

```
/opt/rh/gcc-toolset-9/root/usr/bin/g++ -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -MD -MF bazel-out/k8-opt/bin/external/boringssl/_objs/crypto/socket.pic.d '-frandom-seed=bazel-out/k8-opt/bin/external/boringssl/_objs/crypto/socket.pic.o' -fPIC -iquote external/boringssl -iquote bazel-out/k8-opt/bin/external/boringssl -isystem external/boringssl/src/include -isystem bazel-out/k8-opt/bin/external/boringssl/src/include -w -DAUTOLOAD_DYNAMIC_KERNELS '-march=broadwell' -Wno-sign-compare -fpermissive -Wa,--noexecstack '-D_XOPEN_SOURCE=700' -Wall -Werror '-Wformat=2' -Wsign-compare -Wmissing-field-initializers -Wwrite-strings -Wshadow -fno-common '-std=c11' -Wmissing-prototypes -Wold-style-definition -Wstrict-prototypes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/boringssl/src/crypto/bio/socket.c -o bazel-out/k8-opt/bin/external/boringssl/_objs/crypto/socket.pic.o)
Execution platform: @local_execution_config_platform//:platform
cc1plus: error: command line option '-Wmissing-prototypes' is valid for C/ObjC but not for C++ [-Werror]
cc1plus: error: command line option '-Wold-style-definition' is valid for C/ObjC but not for C++ [-Werror]
cc1plus: error: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [-Werror]
cc1plus: all warnings being treated as errors
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

scl enable gcc-toolset-9 -- bash
bazel build --action_env=CC=$(which g++) //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**

The third-party boringssl compilation passes options that are not valid for C++, and GCC 9 calls them out with a warning. Since the compilation also passes -Werror, it fails.

**Comment by amahendrakar** [comment]
@plopresti,
Could you please provide all the command which you have executed before running into this issue.

Also, please follow the instructions as per the [official guide](https://www.tensorflow.org/install/source#tested_build_configurations) while building TensorFlow from source. Thanks!
