### ISSUE TITLE
Issue in building tensorflow r2.3 from source

### ISSUE THREAD

**Issue by kunalvshah** [tensorflow/tensorflow#44796]
Hi, I am having issue compiling tensorflow r2.3 for CPU from the source on ubuntu I am using following flags 

```--config=opt --copt=-march=native --copt=-Wno-sign-compare --copt=-mfpmath=both --copt=-mavx --copt=-mavx2 --copt=-mfma
 --copt=-msse4.1 --copt=-msse4.2 //tensorflow/tools/pip_package:build_pip_package --verbose_failures
```
------------------------

### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: No - I git clone the code
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 20.04 docker image
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: No
-   **TensorFlow installed from (source or binary)**:  Source
-   **TensorFlow version (use command below)**: 2.3
-   **Python version**: 3.8.5
-   **Bazel version (if compiling from source)**: 3.1.0
-   **GCC/Compiler version (if compiling from source)**: 9.3.0
-   **CUDA/cuDNN version**: Not applicable
-   **GPU model and memory**: Not applicable
-   **Exact command to reproduce**:

`bazel build --config=opt --copt=-march=native --copt=-Wno-sign-compare --copt=-mfpmath=both --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-msse4.1 --copt=-msse4.2 //tensorflow/tools/pip_package:build_pip_package --verbose_failures`

Attaching tf_env.txt for the reference.

### Describe the problem
While building the tensorflow from the source, build fails with error
ERROR: /tensorflow_src/tensorflow/python/BUILD:501:1: C++ compilation of rule '//tensorflow/python:bfloat16_lib' failed (Exit 1): gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/.local/bin \
    PWD=/proc/self/cwd \

<long string>

ERROR: /tensorflow_src/tensorflow/python/tools/BUILD:99:1 C++ compilation of rule '//tensorflow/python:bfloat16_lib' failed (Exit 1): gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/43801f1e35f242fb634ebbc6079cf6c5/execroot/org_tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/.local/bin \
    PWD=/proc/self/cwd \

<long string>
INFO: Elapsed time: 2497.566s, Critical Path: 187.54s
INFO: 10577 processes: 10577 local.
FAILED: Build did NOT complete successfully

Attaching error.txt for detailed error log

### Source code / logs
attaching error.txt for detailed error log
[error.txt](https://github.com/tensorflow/tensorflow/files/5529073/error.txt)
[tf_env.txt](https://github.com/tensorflow/tensorflow/files/5529075/tf_env.txt)

**Comment by amahendrakar** [comment]
@kunalvshah,
Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/40688#issuecomment-647846011) from a similar issue and let us know if it helps. Thanks!

**Comment by kunalvshah** [comment]
Yes, it was success. Dropping numpy to 1.19.0 fixes the issue. Now I am able to compile it successfully.

**Comment by kunalvshah** [comment]
Yes, it was success. Dropping numpy to 1.19.0 fixes the issue. Now I am able to compile it successfully.
