### ISSUE TITLE
How to fastly convert numpy array into TensorFlow tensor in TF 2.x

### ISSUE THREAD

**Issue by Jianbing-D** [tensorflow/tensorflow#44792]
**Describe the current behavior**

I want to train TF DNN model, and the input data is from numpy array.

When inputting data from numpy to TensorFlow, converting to tensor will be triggered no matter which ways I used.
Specifically, I tried these 4 methods:
1) tf.constant(numpy_value)
2) tf.convert_to_tensor(numpy_value)
3) create a tf.Variable, then Variable.assign
4) tf.keras.backend.set_value(variable, numpy_value)

when profiling, there will be `TF_NewTensor` triggered, which might convert numpy value into tensor format. And it is too slow.
![image](https://user-images.githubusercontent.com/69858819/98893834-602f8a00-24de-11eb-807d-ae5b07aa4ca2.png)

**Describe the expected behavior**
1) how to fastly converting numpy array to TF tensor?
2) Or how can I convert numpy array to TF tensor in advance, then I just need give that tensor to TF ops rather than waiting for converting is done then begin forward propagation.

BTW, because batchsize is too large, so `tf.data.TFRecordDataset` is not fast enough to do the profiling, therefore I need to directly input binary value to TF ops.

**Comment by ravikyram** [comment]
@Jianbing-D 

Please, refer this [tutorial](https://www.tensorflow.org/guide/tf_numpy)  and see if it helps you.Thanks!

**Comment by Jianbing-D** [comment]
> @Jianbing-D
> 
> Please, refer this [tutorial](https://www.tensorflow.org/guide/tf_numpy) and see if it helps you.Thanks!

Thanks for your reply. I will try it.
