### ISSUE TITLE
ambiguity of data type of weight

### ISSUE THREAD

**Issue by liyuenan2333** [tensorflow/tensorflow#44798]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04.4 LTS
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):v2.3.1
- Bazel version (if compiling from source):3.1.0

**Current and expected  behavior**
I am supporting our delegete for tensorflow Lite. when I do the uint test, I found some cases(e.g.,SimpleTestHybridUint8) in
tensorflow/lite/kernel/conv_test.cc. they describe their weight type as Uint8, but quantize and calculate as Int8. This kind of behavior doesn't make sense. we can't handle this behavior because it makes ambiguity to our delegate.
So I hope you guys to delete this kind of cases or unify their data type.

**Comment by liyuenan2333** [comment]
Hi!@multiverse-tf, I want to know the state of this issue. Do you fix it now or is it in progress？

**Comment by sushreebarsa** [comment]
@liyuenan2333  
Could you please try on latest stable version of tf 2.5  and let us know if this is still an issue.Thanks!
