### ISSUE TITLE
Image bug fix for tf.gather documentation

### ISSUE THREAD

**Issue by zfrenchee** [tensorflow/tensorflow#448]
<img width="791" alt="screen shot 2015-12-08 at 2 21 45 pm" src="https://cloud.githubusercontent.com/assets/2761597/11665778/1fc3de48-9db7-11e5-9fb3-c086aa9aaa3c.png">

**Comment by vrv** [comment]
Yeah, @colah needs to update the arrow

**Comment by martinwicke** [comment]
And make sure to make a new image, not overwrite the old one!
