### ISSUE TITLE
Undefined symbols for architecture arm64 _TFE_*

### ISSUE THREAD

**Issue by SestoAle** [tensorflow/tensorflow#44800]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Catilina 10.15.7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iOS 14
- TensorFlow installed from (source or binary): source
- TensorFlow version: TF 2.0.0
- Python version: 3.8
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
Hi,

I am not used to build tensorflow from source for iOS so I'm probably doing something wrong. I used the instructions in tensorflow/contrib/makefile to build a static library for iOS architectures. But when I import it into Xcode I get link errors like:

`Undefined symbols for architecture arm64: _TFE_TensorHandleResolve`

What am I missing?

Moreover, I saw that for newer versions of tensorflow there is no contrib folder: how can I build a static library with newer tensorflow, for example 2.3, for iOS?

**Comment by yyoon** [comment]
Hi @SestoAle. As you've noticed, the `contrib` directory is deprecated as of TF 2, and no longer being actively maintained.
The latest instruction on how to build TensorFlow Lite iOS static framework can be accessed here:
https://www.tensorflow.org/lite/guide/build_ios

I'm closing the issue for now, but feel free to reopen if you have more specific questions or having trouble following the guide.

**Comment by SestoAle** [comment]
Hi @yyoon, thanks for the reply. I tried to build static library with tf lite but it doesn't work. When I import it to XCode it doesn't recognize any of the TF operations. I also tried to use `tensorflow/lite/tools/make/build_ios_universal_lib.sh` but with the same result.

Anyway, I think I am fine also with TF 2.0 that still has the `contrib` directory and it recognizes most of the TF operations, expect the TFE ones. How can I include the TFE operations in the static library with TF 2.0?

**Comment by yyoon** [comment]
Sounds like you're trying to call regular TensorFlow ops from an iOS app side, correct? This is not a supported use case, as far as I can tell. Is there any specific reason to use regular TF ops on iOS side? What does your sample code look like that you wrote in Xcode?

Normally, you'd train your model outside of the mobile environment, export the trained TF model into one of the supported format (e.g., TF 2.0 saved model), convert it to TFLite's flatbuffer format, and import it into the app to do inference on device.

**Comment by SestoAle** [comment]
I'm trying to use Tensorflow.NET (TF binding library for C#) into a Unity project. I compile the Tensorflow.NET library as Unity docs say: https://docs.unity3d.com/2019.3/Documentation/Manual/NativePlugins.html 

but when I compile the Unity project for iOS, Unity requires that ` all extern static methods be resolved a link time. If they are not found by the native linker, errors will occur.`

I previously used TensorFlowSharp with TF 1.x (similar to Tensorflow.Net) in the same way I try to use TensorFow.Net (I compiled the C# library and Tensorflow 1.x with `contrib` folder) and it worked fine. However, TensorflowSharp is not maintained anymore and it does not support TF 2.X

**Comment by yyoon** [comment]
Are there established ways to build a static library for TensorFlow.NET for platforms other than iOS? This doesn't seem to be related to TensorFlow Lite at all, and it probably requires a static library of regular TensorFlow, which I'm not too familiar with.

**Comment by SestoAle** [comment]
Yes, I built static libraries for TensorFlow.NET for MacOS and Ubuntu and they work correctly. However I don't have any other platform to test it right now (I think should be useful trying it with Android).

**Comment by yyoon** [comment]
When building for those platforms, did you use the contrib directory as mentioned above?

Anyways, this issue is definitely not related to TFLite, and I'd also suggest asking the TF.NET community to see if other people had successfully built for iOS. This [README from the TF.NET site](https://github.com/SciSharp/TensorFlow.NET/blob/master/tensorflowlib/README.md) might also help.

@mihaimaruseac do you happen to know any ways to build TF static library for iOS, not TFLite?

**Comment by mihaimaruseac** [comment]
There is the `--config=monolithic` flag which might help.

**Comment by sushreebarsa** [comment]
@SestoAle Can you please refer to the [comment ](https://github.com/tensorflow/tensorflow/issues/44800#issuecomment-730502054) and try using latest TF v2.6.0 ? Please let us know if it helps? Thank you!
