### ISSUE TITLE
TFLite: GPU delegate (OpenCL) not copying output data from GPU to CPU.

### ISSUE THREAD

**Issue by Gohan1989** [tensorflow/tensorflow#44802]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.3
- Python version: -
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**
I have a problem with GPU delegate (OpenCL) not copying output data from GPU to CPU.
In my model I have two outputs. One of them is consumed by the other but I need to know both both results.
The problem is that `std::vector<Value*> GraphFloat32::outputs() const` https://github.com/tensorflow/tensorflow/blob/5681c179eff80bce00e526303950b67b23cad14c/tensorflow/lite/delegates/gpu/common/model.cc#L35 returns nodes that do not have any consumers. This is how outputs are defined by this function which means one of my outputs is not recgonized.
What follows from that is (in order):
- InferenceBuilderImpl having only one output in outputs_ variable https://github.com/tensorflow/tensorflow/blob/5681c179eff80bce00e526303950b67b23cad14c/tensorflow/lite/delegates/gpu/gl/api2.cc#L478
- InitializeGraph placing only one output in output_refs https://github.com/tensorflow/tensorflow/blob/5681c179eff80bce00e526303950b67b23cad14c/tensorflow/lite/delegates/gpu/delegate.cc#L274
- Prepare creating only one output object definition https://github.com/tensorflow/tensorflow/blob/5681c179eff80bce00e526303950b67b23cad14c/tensorflow/lite/delegates/gpu/delegate.cc#L170
- InferenceRunner having only one output https://github.com/tensorflow/tensorflow/blob/5681c179eff80bce00e526303950b67b23cad14c/tensorflow/lite/delegates/gpu/gl/api2.cc#L425
- InferenceRunner copying only one (out of two) outputs from the GPU to CPU-accessible memory https://github.com/tensorflow/tensorflow/blob/5681c179eff80bce00e526303950b67b23cad14c/tensorflow/lite/delegates/gpu/cl/api.cc#L475
Note: I have tested it without the GPU delegate and I have both outputs available so the inference itself works well apparently.

**Describe the expected behavior**
Memory is copied from GPU to CPU memory.

**Comment by impjdi** [comment]
Your analysis of GraphFloat32's output handling is correct.  This comes from a wrong assumption at early stages of when we thought output tensors are those without any consumers, and this apparently was wrong.  There's quite a bit of logic of matching graph input / output tensors as defined in the schema with GraphFloat32, and IIRC, this is the 3rd iteration, but there's still a chance that this is still broken.  I think it's easiest if you can provide the TFLite model (doesn't have to be trained, we only need the architecture).

**Comment by Gohan1989** [comment]
@impjdi 
Thanks for your quick reply.
I'd rather avoid sharing it publicly, please find the model file in this repository (I've granted access to your account): TFLite44802ReproModel

**Comment by impjdi** [comment]
Thanks, I grabbed the model.  So you have a model which defines 2 output tensors; the first one is an intermediate tensor and the second one is a final tensor.

**Comment by impjdi** [comment]
While we're fixing to make this work, one quick hack you could do to unblock yourself is adding an almost no-op `ADD` operation (+ eps like 1e-12) to the `output/BiasAdd` tensor and use the output of that `ADD` as the final output.  That way, you have now created a non-intermediate tensor as the graph's output.

**Comment by Gohan1989** [comment]
Thanks, I'm happy this will be addressed 😄.
I'm will try this workaround for now.

**Comment by menchunlei** [comment]
> While we're fixing to make this work, one quick hack you could do to unblock yourself is adding an almost no-op `ADD` operation (+ eps like 1e-12) to the `output/BiasAdd` tensor and use the output of that `ADD` as the final output. That way, you have now created a non-intermediate tensor as the graph's output.
hi @impjdi 
Thanks, i have workaround with Add.

**Comment by tilakrayal** [comment]
@Gohan1989,
Could you please check this [comment](https://github.com/tensorflow/tensorflow/issues/44802#issuecomment-731299217) from the developer and let us know if the issue still persists. Thank you!

**Comment by MarcinHulist** [comment]
This [comment](https://github.com/tensorflow/tensorflow/issues/44802#issuecomment-731299217) helped.
