### ISSUE TITLE
`UnimplementedError: File system scheme` in sess.restore() with the path including colons.

### ISSUE THREAD

**Issue by mecab** [tensorflow/tensorflow#4480]
I found that we get

```
tensorflow.python.framework.errors.UnimplementedError: File system scheme {{ part of path }} not implemented
```

When we try to restore the model from the directory which has colons in its path.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

 - https://github.com/ibab/tensorflow-wavenet/pull/28
 - https://github.com/carpedm20/variational-text-tensorflow/commit/4dee0ce68814f212d2ece7a9b289c41cc4c35cd6

 - I have searched here tensorflow's issues with the words such as "colon", "File system scheme", or "UnimplementedError" but I couldn't find someone note this.

### Environment info
 - Mac OS X 10.11.6
 - Python 3.5.2
 - Tensorflow 0.10.0 (from pip, https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.10.0-py3-none-any.whl )
 - Installed version of CUDA and cuDNN: None

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

```python
import tensorflow as tf

s = tf.Session()
saver = tf.train.Saver()
saver.restore(sess, "path/to/somewhere/with:colon/model.ckpt-0") # where the path is exist with valid checkpoint.
```

### What other attempted solutions have you tried?

 - Renamed the directory containing the checkpoint => fixed.

### Logs or other output that would be helpful
```
Traceback (most recent call last):
  File "./generate.py", line 94, in <module>
    main()
  File "./generate.py", line 57, in main
    saver.restore(sess, args.checkpoint)
  File "/Users/***/.virtualenvs/***/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1126, in restore
    if not file_io.get_matching_files(save_path):
  File "/Users/***/.virtualenvs/***/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 53, in get_matching_files
    return pywrap_tensorflow.GetMatchingFiles(compat.as_bytes(filename), status)
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/Users/***/.virtualenvs/***/lib/python3.5/site-packages/tensorflow/python/framework/errors.py", line 450, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.UnimplementedError: File system scheme {{ path/to/somewhere/with }} not implemented
```

Note `.generate.py` is the user code and {{ path/to/somewhere/with }} was actual path of the model, but terminated before the colon.

**Comment by jhseu** [comment]
You can specify your path as "file://path/to/somewhere/with:colon/model.ckpt-0" instead of "path/to/somewhere/with:colon/model.ckpt-0".

**Comment by mecab** [comment]
I see. Thank you!
