### ISSUE TITLE
eager execution and gradients

### ISSUE THREAD

**Issue by helper228-pro** [tensorflow/tensorflow#44813]
I tried to visualize CNN activations but faced with the next error:

`RuntimeError: tf.gradients is not supported when eager execution is enabled. Use tf.GradientTape instead.
<img width="588" alt="zi80a" src="https://user-images.githubusercontent.com/74381598/98996923-835f3700-24e8-11eb-866e-cfc9e1e5780e.png">
`

```
layer_dict = dict([(layer.name,layer) for layer in baseline_model.layers[1:]])
img_input = baseline_model.input
neuron_index = 1
layer_output = layer_dict['co[enter image description here][1]nv2d_171'].output
loss = keras.backend.mean(layer_output[:,neuron_index,:,:])
gradients = keras.backend.gradients(loss,img_input)[0]
gradients = tf.linalg.normalize(gradients)
iterate = keras.function([img_input],[loss,gradents])
```

**Comment by helper228-pro** [comment]
how can I solve it? thank u

**Comment by bhack** [comment]
If you want to visualize filters please check https://keras.io/examples/vision/visualizing_what_convnets_learn/
