### ISSUE TITLE
How to pass the seq length in the LSTMs in tfLite

### ISSUE THREAD

**Issue by pranathibl** [tensorflow/tensorflow#44819]
Is there an option to pass seq length in LSTM tfLite ?
Is batch size option suffice seq length ?
Does seq length required during training ?
Can we pass variable seq length during inference ? If we can , How we can do that ?

**Comment by amahendrakar** [comment]
@pranathibl,
Could you please provide a minimal code sample of the use case you are trying to implement? Thanks!

**Comment by pranathibl** [comment]
I a trying support of variable sequences in tfLite.
This is the script i created.
Getting issues while i was trying variable sequences.


[lstminput_var_sequencemode.txt](https://github.com/tensorflow/tensorflow/files/5557342/lstminput_var_sequencemode.txt)

**Comment by renjie-liu** [comment]
Currently we don't support seq_len, by default lstm will consume all your sequences

**Comment by pranathibl** [comment]
Then why its working in this particular case,
When i created model with just lstm layer its working,
Could you explain the difference and why its not working in above case and working when i used lstm layer just ?

[lstminput_var_sequencemode_layer.txt](https://github.com/tensorflow/tensorflow/files/5561846/lstminput_var_sequencemode_layer.txt)

**Comment by renjie-liu** [comment]
our current [kernel](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/unidirectional_sequence_lstm.cc) does not support seq_len yet. (we will process all sequences)

also since you're using `return_sequences=True` which means you're consuming all the sequences (which caused dynamic shapes and it's hard for the following dense layer to figure out the dims)

If you disable `return_sequences` it should be fine.

**Comment by pranathibl** [comment]
Is there any thing to check for support ? Which will work and which does not work ?
Will you add support in future ?

**Comment by renjie-liu** [comment]
We will support this in future, but it's unlikely to happen in the near term.

**Comment by Saduf2019** [comment]
@pranathibl 
Could you please let us know if this is still an issue in latest stable TF v2.6.0 ?Thank you!
