### ISSUE TITLE
what is the difference between tf.nn.fixed_unigram_candidate_sampler and  tf.random.log_uniform_candidate_sampler

### ISSUE THREAD

**Issue by MokkeMeguru** [tensorflow/tensorflow#44814]
# Problem
There are two functions for the same problem, negative sampling.

# detail
In many examples without your official documentation, we use tf.nn.fixed_unigram_candidate_sampler for negative sampling.
refs:
- https://github.com/carpedm20/practice-tensorflow/blob/master/embedding/word2vec.py#L226-L234
- https://github.com/chao-ji/tf-word2vec/blob/master/word2vec.py#L146-L153

but you want to use tf.random.log_uniform_candidate_sampler for its problem.

So, users confused about which is the better one.
and also, tf.rando.log_uniform_candidate_sampler may not serve correct negative sampling #44758

We need the correct documentation and tutorial for beginners and researchers.

**Comment by wangpengmit** [comment]
Hi @MokkeMeguru, `tf.random.log_uniform_candidate_sampler` is deprecated in favor of `tf.nn.fixed_unigram_candidate_sampler` (as shown by the former's signature: https://github.com/tensorflow/tensorflow/blob/fcc4b966f1265f466e82617020af93670141b009/tensorflow/python/ops/candidate_sampling_ops.py#L98).

**Comment by rmothukuru** [comment]
@MokkeMeguru,
The API, [tf.nn.fixed_unigram_candidate_sampler](https://www.tensorflow.org/s/results?q=tf.nn.fixed_unigram_candidate_sampler) is no longer present and the only API available is [tf.random.log_uniform_candidate_sampler](https://www.tensorflow.org/api_docs/python/tf/random/log_uniform_candidate_sampler). 

Hope there is no ambiguity now. Thanks!

**Comment by bhack** [comment]
@rmothukuru `tf.random.fixed_unigram_candidate_sampler`

**Comment by wangpengmit** [comment]
According to the docs for `tf.random.fixed_unigram_candidate_sampler` ([doc](https://www.tensorflow.org/api_docs/python/tf/random/fixed_unigram_candidate_sampler)) and `tf.random.log_uniform_candidate_sampler` ([doc](https://www.tensorflow.org/api_docs/python/tf/random/log_uniform_candidate_sampler)), the former uses a discrete distribution defined by the `vocab_file` or the `unigrams` argument, while the latter uses a log-uniform (or Zipfian) distribution defined by the formula `P(class) = (log(class + 2) - log(class + 1)) / log(range_max + 1)`.
