### ISSUE TITLE
postnet  android

### ISSUE THREAD

**Issue by carterinchina** [tensorflow/tensorflow#44821]
How to detect the actions of multiple people in android, there is only one person's behavior detection in the current demo

**Comment by Saduf2019** [comment]
@carterinchina 
Please share the link of the demo you are referring to.

**Comment by carterinchina** [comment]
https://github.com/tensorflow/examples/tree/master/lite/examples/posenet/android

i used this posenet, How to detect the pose of multiple people

**Comment by wangtz** [comment]
Any thoughts on this Tian? TFJS postnet seems to support multiple people.

**Comment by carterinchina** [comment]
> Any thoughts on this Tian? TFJS postnet seems to support multiple people.

so how to use it on tflite (Tensor lite)

**Comment by stevelaclasse** [comment]
Hi, you could this this repository where i have used the Tensorflow lite android example code and the Tensorflow lite flutter plugin code to integrate the multi person pose detection on image and videos.

[https://github.com/stevelaclasse/posenet](https://github.com/stevelaclasse/posenet)

**Comment by khanhlvg** [comment]
For multi-person pose estimation, please use the MoveNet MultiPose model here.
https://github.com/tensorflow/examples/tree/master/lite/examples/pose_estimation/android
