### ISSUE TITLE
Strange behavior for tf.keras.backend.function in tf 2.3.1 for intermediate values

### ISSUE THREAD

**Issue by Moldoteck** [tensorflow/tensorflow#44838]
I was training an Xception model with custom output layers. So, clasic Xception model + dropout layer + dense layer alpha + dropout layer alpha + softmax dense layer for output.
After training, my goal is to split the model in half: Xception+dropout and dense layer alpha...softmax output.
For this, i am doing>
```
model = load_model(path)
base_model= Model(inputs=model.input, outputs=model.get_layer('base_drop').output) - Works fine
second_half = K.function([model.get_layer('dense_alpha').input, K.learning_phase()],
                            [model.get_layer('dense_out').output]) - Error
```
The error is:
```
WARNING:tensorflow:Functional inputs must come from `tf.keras.Input` (thus holding past layer metadata), they cannot be the output of a previous non-Input layer. Here, a tensor specified as input to "functional_4" was not an Input tensor, it was generated by layer base_drop.
Note that input tensors are instantiated via `tensor = tf.keras.Input(shape)`.
The tensor that caused the issue was: base_drop/cond/Identity:0

ValueError: Input tensors to a Functional must come from `tf.keras.Input`. Received: 0 (missing previous layer metadata).

```
Also, if i am doing
```
second_half  = Model(inputs=model.get_layer('dense_alpha').input,
                            outputs=model.get_layer('dense_out').output)
```
I get the following error

`Graph disconnected: cannot obtain value for tensor Tensor("input_1:0", shape=(None, 300, 480, 3), dtype=float32) at layer "xception". The following previous layers were accessed without issue: []`

I didn't got these errors with tf 2.2.0 + i have read that the behavior of tf.keras.backend.function has changed in the 2.3.0
Is this a bug or it's something expected. In the second case, what should i change in order to achieve previous functionality?

I need this split in order to run base_model only one time with my test dataset and pass the results through the function multiple times with active second dropout

**Comment by bhack** [comment]
Do you have a very, very minimal standalone code (or Colab) code snippet that we could just copy and run to reproduce this?

**Comment by Moldoteck** [comment]
> 
> 
> Do you have a very, very minimal standalone code (or Colab) code snippet that we could just copy and run to reproduce this?

Is this ok?>>>

```

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.applications.xception import Xception
from tensorflow.keras.layers import Input, Dense, Dropout, Flatten, Conv2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import backend as K

inp = Input((300,480,3))
base_model = Xception(include_top=False,
                              weights='imagenet',
                              input_tensor=inp,
                              pooling='avg')

for layer in base_model.layers[:65]:
	layer.trainable = False
for layer in base_model.layers[65:]:
	layer.trainable = True
	
	
x = base_model(inp)

x = Dropout(0.5, name='base_drop')(x)
dense_alpha = Dense(1024, activation='relu', name='dense_alpha')(x)
dense_alpha = Dropout(0.5, name='dense_alpha_drop')(dense_alpha)
dense_alpha = Dense(2, activation='softmax', name='dense_out')(dense_alpha)

losses = [tf.keras.losses.BinaryCrossentropy()]

model = Model(inputs=inp, outputs=[dense_alpha])
model.compile(optimizer=Adam(lr=0.0001),
			  loss=losses,
			  metrics=['accuracy'])

model_base = Model(inputs=model.input, outputs=model.get_layer('base_drop').output)
                
second_part = K.function([model.get_layer('dense_alpha').input, K.learning_phase()],
                            [model.get_layer('dense_out').output])
```

**Comment by bhack** [comment]
The example it is enough thanks. It seems similar to https://stackoverflow.com/questions/63238203/how-to-get-intermediate-outputs-in-tf-2-3-eager-with-learning-phase

**Comment by Moldoteck** [comment]
> 
> 
> The example it is enough thanks. It seems similar to https://stackoverflow.com/questions/63238203/how-to-get-intermediate-outputs-in-tf-2-3-eager-with-learning-phase

Yes. The thing is that if i will replace last line with 

```
second_part = Model([model.get_layer('dense_alpha').input],
                            [model.get_layer('dense_out').output])
```
I'll get this error:
`
ValueError: Graph disconnected: cannot obtain value for tensor Tensor("input_1:0", shape=(None, 300, 480, 3), dtype=float32) at layer "xception". The following previous layers were accessed without issue: []`

So, the question is: is this a bug, or it is expected behavior. If it is expected, why it worked with previous tf versions?

P.S. from tensorflow.python.keras.backend import eager_learning_phase_scope will solve/hide the error, but still, it looks like a workaround instead of an explanation why it doesn't work now

**Comment by Moldoteck** [comment]
EDIT: from tensorflow.python.keras.backend import eager_learning_phase_scope is not helping, since the error is happening in this part: 
second_part = K.function([model.get_layer('dense_alpha').input, K.learning_phase()],
                            [model.get_layer('dense_out').output])
In other words, solution from stackoverflow doesn't work

**Comment by bhack** [comment]
When you use
```
second_part = Model([model.get_layer('dense_alpha').input],
                            [model.get_layer('dense_out').output])
```
You are in the same case as
https://github.com/tensorflow/tensorflow/issues/43025

**Comment by Moldoteck** [comment]
> 
> 
> When you use
> 
> ```
> second_part = Model([model.get_layer('dense_alpha').input],
>                             [model.get_layer('dense_out').output])
> ```
> 
> You are in the same case as
> #43025

Well, as i understand, in current implementation, the method with Model is a bit harder to use if i have branches in the network(which is my case) and at the same time, the Backend.function will not behave as it was in the past, so i will not be able to use it. In other words, in my case the best method would be to downgrade the tf version OR disable the eager execution and use backend.function, since it will go to another branch

**Comment by bhack** [comment]
You can explore to reorganize with subclassed as suggested in https://github.com/tensorflow/tensorflow/issues/43025#issuecomment-688957850
