### ISSUE TITLE
Blas xGEMM launch failed: RTX3080 with CUDA 10.0

### ISSUE THREAD

**Issue by AZadora** [tensorflow/tensorflow#44832]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04 LTS, used within a Docker container 
- TensorFlow installed from (source or binary): from Docker image tensorflow/tensorflow:1.14.0-gpu-py3
- TensorFlow version (use command below): 1.14.0-gpu
- Python version: 3.7
- CUDA/cuDNN version: 10.0/7.6.0.64
- GPU model and memory: 2xRTX 3080

**Describe the current behavior**
While loading a PointCNN model I got the following error (snippet): 
`(0) Internal: Blas xGEMM launch failed : a.shape=[1,20000,3], b.shape=[1,3,20000], m=20000, n=20000, k=3`

Tensorflow is run with the following config options:
`  config.gpu_options.allow_growth = True`
`  config.allow_soft_placement = True`

I also tried setting them to false.

**Describe the expected behavior**
The same model is successfully loaded on another machine with Ubuntu 20.04 LTS within the same Docker container but with Nvidia 970GTX.

I think this may be related to CUDA 10.0 support on RTX 3080? 

Full error log:

`Exception has occurred: InternalError`
`2 root error(s) found.`
`  (0) Internal: Blas xGEMM launch failed : a.shape=[1,20000,3], b.shape=[1,3,20000], m=20000, n=20000, k=3`
`	 [[node while/generator_ops/PointCNN/MatMul (defined at src/src/tf_utils/pointfly.py:572) ]]`
`  (1) Internal: Blas xGEMM launch failed : a.shape=[1,20000,3], b.shape=[1,3,20000], m=20000, n=20000, k=3`
`	 [[node while/generator_ops/PointCNN/MatMul (defined at src/src/tf_utils/pointfly.py:572) ]]`
`	 [[while/preprocessing_ops/batch_nonuniform_sample/while/concat_1/_807]]`
`0 successful operations.`
`0 derived errors ignored.`

`Errors may have originated from an input operation.`
`Input Source operations connected to node while/generator_ops/PointCNN/MatMul:`
` while/preprocessing_ops/batch_nonuniform_sample/Reshape (defined at src/src/tf_utils/pointfly.py:370)`

`Input Source operations connected to node while/generator_ops/PointCNN/MatMul:`
` while/preprocessing_ops/batch_nonuniform_sample/Reshape (defined at src/src/tf_utils/pointfly.py:370)`

**Comment by bhack** [comment]
I think that `Docker image tensorflow/tensorflow:1.14.0-gpu-py3` doesn't support RTX3080. Can you try `tensorflow/tensorflow:2.4.0rc1-gpu`?

**Comment by AZadora** [comment]
> I think that `Docker image tensorflow/tensorflow:1.14.0-gpu-py3` doesn't support RTX3080. Can you try `tensorflow/tensorflow:2.4.0rc1-gpu`?

Yes, it seems to be working with 2.4.0rc1. Thank you!

**Comment by amahendrakar** [comment]
@AZadora,
Thank you for the update. Marking this issue as closed, as it is resolved. Please feel free to re-open if necessary.
