### ISSUE TITLE
source install transorflow  configure  error

### ISSUE THREAD

**Issue by f8281113** [tensorflow/tensorflow#4483]
i install Tensorflow on Ubuntu16.04 GTX1080  CUDA 8.0 CUDNN 5.0
when git Tensorflow configure occure this issue:

chenl@FS-S07:~/tensorflow$ ./configure 
~/tensorflow ~/tensorflow
Please specify the location of python. [Default is /usr/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

/usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5
Please specify the location where cuDNN 5 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 
.
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
.
ERROR: /home/chenl/tensorflow/tensorflow/tensorflow.bzl:571:26: Traceback (most recent call last):
	File "/home/chenl/tensorflow/tensorflow/tensorflow.bzl", line 565
		rule(attrs = {"srcs": attr.label_list..."), <3 more arguments>)}, <2 more arguments>)
	File "/home/chenl/tensorflow/tensorflow/tensorflow.bzl", line 571, in rule
		attr.label_list(cfg = "data", allow_files = True)
expected ConfigurationTransition or NoneType for 'cfg' while calling label_list but got string instead: data.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file 'tensorflow/tensorflow.bzl' has errors.

who can help me > Thank you very much

**Comment by f8281113** [comment]
# **## configure again the same issue**

chenl@FS-S07:~/tensorflow$ ./configure 
~/tensorflow ~/tensorflow
Please specify the location of python. [Default is /usr/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] N
No Google Cloud Platform support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

/usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with GPU support? [y/N] Y
GPU support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5.0
Please specify the location where cuDNN 5.0 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Invalid path to cuDNN  toolkit. Neither of the following two files can be found:
/usr/local/cuda-8.0/lib64/libcudnn.so.5.0
/usr/local/cuda-8.0/libcudnn.so.5.0
.5.0
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5.0.5
Please specify the location where cuDNN 5.0.5 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 3.0
Sending SIGTERM to previous Bazel server (pid=18929)... done.
.
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
.
ERROR: /home/chenl/tensorflow/tensorflow/tensorflow.bzl:571:26: Traceback (most recent call last):
	File "/home/chenl/tensorflow/tensorflow/tensorflow.bzl", line 565
		rule(attrs = {"srcs": attr.label_list..."), <3 more arguments>)}, <2 more arguments>)
	File "/home/chenl/tensorflow/tensorflow/tensorflow.bzl", line 571, in rule
		attr.label_list(cfg = "data", allow_files = True)
expected ConfigurationTransition or NoneType for 'cfg' while calling label_list but got string instead: data.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file 'tensorflow/tensorflow.bzl' has errors.
Configuration finished

**Comment by hholst80** [comment]
Work-around: Try the r0.10 branch. `git checkout r0.10` and retry compile.

**Comment by darinc** [comment]
thanks @hholst80  I had the same issue and switching to the the r0.10 branch worked for me.

**Comment by kkjh0723** [comment]
I also had the same issue. But when I swtiched to the r0.10 branch, other warnings and errors come...

    WARNING: /home/jinhyung/.cache/bazel/_bazel_jinhyung/24f731f36d8cecf427d437d0326fcc3c/external/protobuf/WORKSPACE:1: Workspace name in /home/jinhyung/.cache/bazel/_bazel_jinhyung/24f731f36d8cecf427d437d0326fcc3c/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
    WARNING: /home/jinhyung/.cache/bazel/_bazel_jinhyung/24f731f36d8cecf427d437d0326fcc3c/external/highwayhash/WORKSPACE:1: Workspace name in /home/jinhyung/.cache/bazel/_bazel_jinhyung/24f731f36d8cecf427d437d0326fcc3c/external/highwayhash/WORKSPACE (@__main__) does not match the name given in the repository's definition (@highwayhash); this will cause a build error in future versions.
    WARNING: /home/jinhyung/.cache/bazel/_bazel_jinhyung/24f731f36d8cecf427d437d0326fcc3c/external/gemmlowp/WORKSPACE:1: Workspace name in /home/jinhyung/.cache/bazel/_bazel_jinhyung/24f731f36d8cecf427d437d0326fcc3c/external/gemmlowp/WORKSPACE (@__main__) does not match the name given in the repository's definition (@gemmlowp); this will cause a build error in future versions.
    WARNING: /home/jinhyung/.cache/bazel/_bazel_jinhyung/24f731f36d8cecf427d437d0326fcc3c/external/re2/WORKSPACE:1: Workspace name in /home/jinhyung/.cache/bazel/_bazel_jinhyung/24f731f36d8cecf427d437d0326fcc3c/external/re2/WORKSPACE (@__main__) does not match the name given in the repository's definition (@re2); this will cause a build error in future versions.
    WARNING: /home/jinhyung/.cache/bazel/_bazel_jinhyung/24f731f36d8cecf427d437d0326fcc3c/external/boringssl_git/WORKSPACE:1: Workspace name in /home/jinhyung/.cache/bazel/_bazel_jinhyung/24f731f36d8cecf427d437d0326fcc3c/external/boringssl_git/WORKSPACE (@boringssl) does not match the name given in the repository's definition (@boringssl_git); this will cause a build error in future versions.
    ERROR: /home/jinhyung/tensorflow/tensorflow/core/platform/default/build_config/BUILD:56:1: no such package '@jpeg_archive//': Error downloading from http://www.ijg.org/files/jpegsrc.v9a.tar.gz to /home/jinhyung/.cache/bazel/_bazel_jinhyung/24f731f36d8cecf427d437d0326fcc3c/external/jpeg_archive: Error downloading http://www.ijg.org/files/jpegsrc.v9a.tar.gz to /home/jinhyung/.cache/bazel/_bazel_jinhyung/24f731f36d8cecf427d437d0326fcc3c/external/jpeg_archive/jpegsrc.v9a.tar.gz: www.ijg.org and referenced by '//tensorflow/core/platform/default/build_config:platformlib'.
    ERROR: /home/jinhyung/tensorflow/tensorflow/core/platform/default/build_config/BUILD:56:1: no such package '@jpeg_archive//': Error downloading from http://www.ijg.org/files/jpegsrc.v9a.tar.gz to /home/jinhyung/.cache/bazel/_bazel_jinhyung/24f731f36d8cecf427d437d0326fcc3c/external/jpeg_archive: Error downloading http://www.ijg.org/files/jpegsrc.v9a.tar.gz to /home/jinhyung/.cache/bazel/_bazel_jinhyung/24f731f36d8cecf427d437d0326fcc3c/external/jpeg_archive/jpegsrc.v9a.tar.gz: www.ijg.org and referenced by '//tensorflow/core/platform/default/build_config:platformlib'.
    ERROR: Evaluation of query "deps((//... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.
    Configuration finished

**Comment by kkjh0723** [comment]
@f8281113 I solve this problem by updating bazel to the latest version. I could install master branch after the updating.

**Comment by f8281113** [comment]
@all Thank you replay .. I  slove this problem too.  I just update nvidia-cuda-toolkit and  nvidia-cuda-dev; **command:**  sudo apt-get install nvidia-cuda-toolkit nvidia-cuda-dev

**Comment by f8281113** [comment]
Beaause when i install torach also happed an  error: (https://github.com/torch/distro/issues/130) ,just update: sudo apt-get install nvidia-cuda-toolkit nvidia-cuda-dev
this issue slove too ;But i don't know why..maybe is my nvidvi-card is GTX1080 ......

**Comment by mf0hka** [comment]
In Linux, I found the solution was that the config script looks in "/usr/local/cuda"
but the files were in /usr/local/cuda-8.0 (The version I just installed). 

Perhaps something could be added to the config script that incorporates the idea that new cuda versions might have default installations at places like "/usr/local/cuda-*" 

Heck, I would even take a side note in the script, "The default tensorflow location for cuda might vary from what ever the hack NVIDIA is doing now"
