### ISSUE TITLE
How to accelerate tensor transferring from host to device (GPU) in TF 2.x?

### ISSUE THREAD

**Issue by Jianbing-D** [tensorflow/tensorflow#44836]
**Describe the current behavior**
Hi, I want to train my DNN model with TF. And now the input is from `tf.data.Dataset.from_tensor_slices`, which will prefetch the numpy value into TF tensors. 

Because the training is on GPU, therefore tensor transferring from CPU to GPU is triggerd automatically, which results in bad performance in my training process.

Specifically, one iteration is about 205 ms, while data transfering from CPU to GPU will spend 136 ms.
![image](https://user-images.githubusercontent.com/69858819/99072211-8cd2c700-25ee-11eb-946d-e017575b586f.png)

**Describe the expected behavior**
Is there any way to change the memory used by `tf.data.Dataset` to CPU pinned memory rather than pageable? So that tensor transferring from CPU to GPU will be much faster.

Or any other methods I can try to accelerate data reading from numpy to TF tensors on GPU?

**Comment by bhack** [comment]
Have you already read this to optimize your data pipeline for GPU: https://www.tensorflow.org/guide/data_performance?

**Comment by Jianbing-D** [comment]
> Have you already read this to optimize your data pipeline for GPU: https://www.tensorflow.org/guide/data_performance?

Yes, I did. 
Currently, my data pipeline is: reading data from numpy values, then prefetch it. No other operations (such as map, interleave).

**Comment by bhack** [comment]
If you want to control the prefect to GPU device you could try `prefetch_to_device`. Check if it is not currently broken for your use case https://github.com/tensorflow/tensorflow/issues/43905

**Comment by Jianbing-D** [comment]
> If you want to control the prefect to GPU device you could try `prefetch_to_device`. Check if it is not currently broken for your use case #43905

Thanks for the link.

I changed the last line of my dataset to `dataset = dataset.apply(tf.data.experimental.prefetch_to_device(device='/gpu:0', buffer_size=16))`, and iteration elapsed time is less than before (`dataset.prefetch(buffer_size=16)`).

And now, the timeline is:
![image](https://user-images.githubusercontent.com/69858819/99096582-6a05da00-2611-11eb-9260-90953b5a7d86.png)

There are **still memcyp H2D**, although it is faster than before.

Seems like `prefetch` does not work?

**Comment by bhack** [comment]
I think that you can comment after https://github.com/tensorflow/tensorflow/issues/43905#issuecomment-720453284

**Comment by bhack** [comment]
I think we can close this as It Is tracked in the other ticket.
