### ISSUE TITLE
"An op outside of the function building code is being passed a "Graph" tensor" when using custom loss

### ISSUE THREAD

**Issue by Crispy13** [tensorflow/tensorflow#44840]
Hi, i made a code with subclass api(https://www.tensorflow.org/guide/keras/custom_layers_and_models#putting_it_all_together_an_end-to-end_example) and custom loss for a model.

The problem is when using custom loss in addition to main loss, this error is raised:
```
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: add_1:0
```

If i comment `self.add_loss(lambda: tf.reduce_mean(VAE_loss))` the error is not raised.

Colab notebook : https://colab.research.google.com/drive/17zKRFQsPCpKjHkmMJqMC4EuDDhOLvuVy?usp=sharing

**Comment by bhack** [comment]
@Crispy13 Can you minimize you colab example to reproduce this?

**Comment by Crispy13** [comment]
> @Crispy13 Can you minimize you colab example to reproduce this?

I'm sorry but this was the best I can. I already minimized once.
I can't minimize the model part.

**Comment by Crispy13** [comment]
I solved it.

First, I comment the build function of the custom model.
```
    def build(self, batch_input_shape):
        n_inputs = batch_input_shape[-1]
        
        
        ### super build
        super().build(batch_input_shape)
```

And `run_eagerly = True` when compiling or use a custom layer calculating the custom loss.
For example, write a custom layer code:
```
class LossVAE(keras.layers.Layer):
    def __init__(self, weight_L2, weight_KL, n, **kwargs):
        super().__init__(**kwargs)
        
        self.weight_L2 = weight_L2
        self.weight_KL = weight_KL
        self.n = n
        
    def call(self, inputs):
        x, out_VAE, z_mean, z_var = inputs
        loss_L2 = tf.reduce_mean(tf.square(x - out_VAE), axis=(1, 2, 3, 4)) # original axis value is (1,2,3,4).
        loss_KL = (1 / self.n) * tf.reduce_sum(
            tf.exp(z_var) + tf.square(z_mean) - 1. - z_var,
            axis=-1
        )
        
        VAE_loss = tf.reduce_mean(tf.add(self.weight_L2 * loss_L2, self.weight_KL * loss_KL, name = "add_L2_KL"), name = "mean_VAELoss")
        self.add_loss(VAE_loss)
        
        return         
```
and assign an instance of it in __init__ of the custom model, insert `self.LossVAE([Z, out_VAE, z_mean, z_var])` into call method of the custom model.

But i don't understand still why the error was raised when using the initial code.

**Comment by bhack** [comment]
@Crispy13 See https://github.com/tensorflow/tensorflow/issues/44861#issuecomment-727202741
