### ISSUE TITLE
No rule to make target 'hello_world_bin'.  Stop

### ISSUE THREAD

**Issue by YANxu-666** [tensorflow/tensorflow#44841]
ake: *** No rule to make target 'third_party_download'.  Stop.
lenovo :: F:\tensorflow <master> » make -f tensorflow/lite/micro/tools/make/Makefile TARGET=sparkfun_edge hello_world_bin
FIND: 参数格式不正确
FIND: 参数格式不正确
make: *** No rule to make target 'hello_world_bin'.  Stop.

why？
I am a novice and can't solve this problem

**Comment by Saduf2019** [comment]
@YANxu-666 
Please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/42049#issuecomment-669376969) and let us know if it helps.

**Comment by wangtz** [comment]
Adding Advait and Pete, in case you have experienced similar failure on Windows.

**Comment by YANxu-666** [comment]
> Adding Advait and Pete, in case you have experienced similar failure on Windows.

Advait and Pete? I'm sorry i don't know
Could you make it clearer?

**Comment by YANxu-666** [comment]
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/hello_world#compile-the-binary
I am compiling a binary file and an error occurs：

lenovo :: F:\tensorflow <master> » make -f tensorflow/lite/micro/tools/make/Makefile TARGET=sparkfun_edge hello_world_bin
FIND: 参数格式不正确
FIND: 参数格式不正确
make: *** No rule to make target 'hello_world_bin'.  Stop.
I use Windows terminal

**Comment by wangtz** [comment]
Any chance that you could try Linux?

**Comment by Saduf2019** [comment]
@YANxu-666
Please update

**Comment by Dark-Chao** [comment]
It might be the make command doesn't work well on Window.. I install a virtual machine Obuntu and run the command lines.
