### ISSUE TITLE
Confusing results from tf.math.mod. An issue with precision?

### ISSUE THREAD

**Issue by Cyberface** [tensorflow/tensorflow#44844]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MACOS 10.14.5
- TensorFlow installed from (source or binary): installed using pip
- TensorFlow version (use command below): 2.2.0
- Python version: 3.7.7

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:

2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

```
v2.2.0-rc4-8-g2b96f3662b 2.2.0
```

**Describe the current behavior**

I am attempting to use tensorflow to compute the modulus of two numbers and seeing some strange behaviour that seems to be related to the precision being used.

I have attached an example block of code and two example outputs below.
The example code simply computes the modulus of the two input numbers (x, y) and as you can see, depending on the precision that the inputs are cast to the output can be quite different.

As a cross check the code example also computes the modulus using numpy (and casts to the equivalent? dtypes).
I find that the higher precision numpy results are much closer to the true answer.

Interestingly, we find that the results for
 numpy.float16 and tf.float16 agree
 numpy.float32 and tf.float32 agree

but
numpy.float64 and tf.float64 *disagree*

Instead tf.float32 and tf.float64 actually agree with each other though. Does this point to a bug with the tf.float64?

Thanks in advance!

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
import numpy as np
import tensorflow as tf

def example_for_git(x, y):
    print("tensorflow\n")
    print(f"tf fl16: {tf.math.mod(tf.cast(x, tf.float16), tf.cast(y, tf.float16)).numpy()}")
    print(f"tf fl32: {tf.math.mod(tf.cast(x, tf.float32), tf.cast(y, tf.float32)).numpy()}")
    print(f"tf fl64: {tf.math.mod(tf.cast(x, tf.float64), tf.cast(y, tf.float64)).numpy()}")
    print("\nnumpy\n")
    print(f"np fl16: {np.mod(np.float16(x), np.float16(y))}")
    print(f"np fl32: {np.mod(np.float32(x), np.float32(y))}")
    print(f"np fl64: {np.mod(np.float64(x), np.float64(y))}")
    print(f"np fl128: {np.mod(np.float128(x), np.float128(y))}")

example_for_git(80002.2, 1)
""" output: the expected result of mod(80002.2, 1) is 0.2
tensorflow

tf fl16: nan
tf fl32: 0.203125
tf fl64: 0.203125

numpy

np fl16: nan
np fl32: 0.203125
np fl64: 0.19999999999708962
np fl128: 0.19999999999708962
"""


example_for_git(851839.8270638183, 2*np.pi)
""" output
tensorflow

tf fl16: nan
tf fl32: 3.2239599227905273
tf fl64: 3.2239599227905273

numpy

np fl16: nan
np fl32: 3.2239599227905273
np fl64: 3.262228253121961
np fl128: 3.262228253121961
"""
```

**Comment by bhack** [comment]
See the difference with `example_for_git(851839.8270638183, 2*np.pi)`
```
    print(tf.cast(x, tf.float64))
    print(tf.convert_to_tensor(x, tf.float64))
    print(np.float64(x))
```

**Comment by Cyberface** [comment]
Hi @bhack, thanks for replying to me!

I tested this and using `tf.convert_to_tensor(x, tf.float64)` worked!!

I guess I will just always use `tf.convert_to_tensor` for everything instead of `tf.cast` then...

Is this the desired behaviour for tf.cast or is it a bug?

Thanks again!

**Comment by bhack** [comment]
There was a related thread about convert/cast at https://github.com/tensorflow/tensorflow/issues/35938
https://github.com/GPflow/GPflow/pull/1213

**Comment by bhack** [comment]
See the specific @josh11b TODO in `tf.cast` at:

https://github.com/tensorflow/tensorflow/blob/fcc4b966f1265f466e82617020af93670141b009/tensorflow/python/ops/math_ops.py#L916-L919

@Cyberface Do you want to try to open a PR for this TODO?

**Comment by Cyberface** [comment]
@bhack I have a first attempt at solving this issue here https://github.com/Cyberface/tensorflow/pull/1

Is there an easy way to install my fork of tensorflow to test the code?

**Comment by bhack** [comment]
See https://stackoverflow.com/questions/34204551/run-tensorflow-unit-tests

If you don't want to compile probably the fast way is to open a PR so that It will be tested by TF CI

**Comment by Cyberface** [comment]
OK thanks! I've opened a PR and will look into compiling from source

**Comment by ravikyram** [comment]
@Cyberface 

Any update on the issue please. Thanks!

**Comment by bhack** [comment]
The PR was at https://github.com/tensorflow/tensorflow/pull/44902

**Comment by Cyberface** [comment]
Sorry, I am unable to help on this anymore!

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tensorflow 2.5, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/8af6098353550dc46b03596625e069ee/44844.ipynb). Thanks!

**Comment by cantonios** [comment]
As hinted above, this is unrelated to `tf.math.mod`, and is more an issue of converting numpy arrays to tensors.

Ensuring the input tensors are of the correct type (e.g. `tf.constant(x, tf.float64)`) resolves the issue.

**Comment by sachinprasadhs** [comment]
Could you please move this issue to closed as per the comment above. Thanks!
