### ISSUE TITLE
Unable to retrieve flower_photos.tgz using curl command

### ISSUE THREAD

**Issue by mayukhg** [tensorflow/tensorflow#4485]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:Ubuntu 12.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

I have installed TensorFlow using docker by running the following command $ docker run -it -p 8888:8888 gcr.io/tensorflow/tensorflow

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
I am trying to retrieve the set of images for TensorFlow for Poets using the following command curl -O http://download.tensorflow.org/example_images/flower_photos.tgz but the below mentioned error is being thrown

~/tf_files$ curl http://download.tensorflow.org/example_images/flower_photo.tgz
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message></Error>

**Comment by hholst80** [comment]
Is it "photo" or "photos"?

**Comment by hholst80** [comment]
```
hholst@fb-hholst3:/tmp$ curl -O http://download.tensorflow.org/example_images/flower_photos.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  218M  100  218M    0     0  66.2M      0  0:00:03  0:00:03 --:--:-- 66.3M
hholst@fb-hholst3:/tmp$ file flower_photos.tgz 
flower_photos.tgz: gzip compressed data, last modified: Wed Feb 10 20:53:41 2016, from Unix
hholst@fb-hholst3:/tmp$ curl -O http://download.tensorflow.org/example_images/flower_photo.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   127  100   127    0     0    476      0 --:--:-- --:--:-- --:--:--   481
hholst@fb-hholst3:/tmp$ file flower_photo.tgz 
flower_photo.tgz: XML 1.0 document text
hholst@fb-hholst3:/tmp$ cat flower_photo.tgz 
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message></Error>hholst@fb-hholst3:/tmp$ 
hholst@fb-hholst3:/tmp$
```
