### ISSUE TITLE
No Operation named [input] in the Graph running in React-Native

### ISSUE THREAD

**Issue by GustavoMSevero** [tensorflow/tensorflow#44856]
**System information**
- Environment:
  OS: macOS High Sierra 10.13.6
  Node: 14.12.0
  Yarn: 1.22.5
  npm: 6.14.8
  Watchman: 4.9.0
  Xcode: Not Found
  Android Studio: 4.0 AI-193.6911.18.40.6626763

- Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

- TensorFlow installed from (source or binary): danjarvis/tensorflow-android:1.0.0
- TensorFlow version (or github SHA if from source): danjarvis/tensorflow-android:1.0.0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.
```
# Copy and paste here the exact command
```
python /tensorflow/tensorflow/examples/image_retraining/retrain.py \
--bottleneck_dir=/tf_files/bottlenecks \
--how_many_training_steps 500 \
--model_dir=/tf_files_inception  \
--output_graph=/tf_files/star_wars_graph.pb \
--output_labels=/tf_files/star_wars_labels.txt \
--image_dir /tf_files/star_wars

This command will generate the .pb and txt using inception-v3, but and the tutorial said i have to do the following to "convert" to inception-v1.

python /tensorflow/tensorflow/python/tools/optimize_for_inference.py \
--input=/tf_files/star_wars_graph.pb \
--output=/tf_files/star_wars_graph_optimized.pb \
--frozen_graph=True \
--input_names=Mul \
--output_names=final_result

and then

python /tensorflow/tensorflow/tools/quantization/quantize_graph.py \
--input=/tf_files/star_wars_graph_optimized.pb \
--output=/tf_files/star_wars_rounded_graph.pb \
--output_node_names=final_result \
--mode=weights_rounded

**The output from the converter invocation**

```
# Copy and paste the output here.
```
No out put is showen

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
```
The link is this, but is in portuguese [http://www.davifelipe.com.br/tensorflow-gerando-model-para-dispositivo-movel](url)

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Everythings runs fine, but an alert saying the error is showed
![Captura de Tela 2020-11-13 às 16 27 59](https://user-images.githubusercontent.com/2678092/99112982-4620a500-25cd-11eb-908f-f3641c97fa08.png)

**Comment by Saduf2019** [comment]
@GustavoMSevero 
Could you please let us know if this is still an issue in latest stable TF v2.6.0 ?Thank you!

**Comment by GustavoMSevero** [comment]
Sorry @Saduf2019, have been a long time I don't use it and don't remember what project is this kkkkkk But I remember I have this issue.
Thank you for your attention.

**Comment by Saduf2019** [comment]
@GustavoMSevero 
In that case would you want to move this to closed status, and open an issue when your face the issue.

**Comment by GustavoMSevero** [comment]
Sorry @Saduf2019
