### ISSUE TITLE
TypeError: An op outside of the function building code is being passed a "Graph" tensor

### ISSUE THREAD

**Issue by ion-elgreco** [tensorflow/tensorflow#44861]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: Windows 10
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.4-RC0
- Python version: 3.8
- CUDA/cuDNN version: 11/8.0.4
- GPU model and memory: RTX 3080, 10GB 

**Describe the current behavior**
I am trying to build a custom RNN cell, based on this paper:

> Using Fast Weights to Attend to the Recent Past
> Jimmy Ba, Geoffrey Hinton, Volodymyr Mnih, Joel Z. Leibo, Catalin Ionescu
> NIPS 2016, https://arxiv.org/abs/1610.06258

However, my implementation returns this error, but I have no clue what this means:

```
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: FW-RNN/while/fw_rnn_cell_2/add_2:0

```

**Describe the expected behavior**
The model should simply start training.

**Standalone code to reproduce the issue**
Code:  https://gist.github.com/ion-elgreco/cc6fed29a4f6fb6813b71d5e7e8f2c87#file-fw_rnn-py

**Other info / logs** 
Error log: https://gist.github.com/ion-elgreco/cc6fed29a4f6fb6813b71d5e7e8f2c87#file-fw_rnn_error-txt

**Comment by ion-elgreco** [comment]
If I comment out self.A:

```
 # Fast weights update rule: A(t) = λ*A(t-1) + η*h(t) ⋅ h(t)^T
 self.A = (self.l * self.A) + K.dot((self.e * prev_output),K.transpose(prev_output))    
```

The TypeError does not show up, so it seems to be related to that. Still not sure how I can update an attribute of the cell with the custom update rule within tensorflow.

**Comment by bhack** [comment]
@MarkDaoust I think that like https://github.com/tensorflow/tensorflow/issues/44840 this kind of Error message it is intercepted at too low-level so it is going to create confusion.  We need to look for a solution to emit a more "Developer friendly" error earlier in the stack.

**Comment by bhack** [comment]
@ion-elgreco Why the downvote? I suppose that if the error was `self-explainable` you wouldn't have opened the ticket. Right?

**Comment by ion-elgreco** [comment]
> @ion-elgreco Why the downvote? I suppose that if the error was `self-explainable` you wouldn't have opened the ticket. Right?

Missclicked, but the error can still not be explained.  I wouldn't have opened the ticket indeed if it was self-explainable. It's really difficult to debug TensorFlow with such cryptic errors :)

**Comment by ion-elgreco** [comment]
@bhack Do you perhaps know how I can update weights with a custom update rule?

**Comment by bhack** [comment]
I can take a look at your specific issue but you really need to minimize your code and share something that I could simply copy, paste and run (or a Colab minimal example).

**Comment by ion-elgreco** [comment]
> I can take a look at your specific issue but you really need to minimize your code and share something that I could simply copy, paste and run (or a Colab minimal example).

Alright, thank you! I will create it now on colab

**Comment by ion-elgreco** [comment]
> I can take a look at your specific issue but you really need to minimize your code and share something that I could simply copy, paste and run (or a Colab minimal example).

@bhack Here is the google collab link: 
https://colab.research.google.com/drive/1SaC_Fd9ZXGcscE-G63opAat8k5ElQMXd?usp=sharing

I put it on commenter, but do I need to give you editor access?

**Comment by bhack** [comment]
Is your clam at https://github.com/tensorflow/tensorflow/issues#issuecomment-727202047 still valid with the Colab?

**Comment by ion-elgreco** [comment]
> Is your claim at [#44861 (comment)](https://github.com/tensorflow/tensorflow/issues/44861#issuecomment-727202047) still valid with the Colab?

Yes, sadly the error still occurs.

**Comment by bhack** [comment]
Did you tried with `self.A.assign_add`?

**Comment by ion-elgreco** [comment]
> assign_add

This seems to work, but `assign_add` does addition right? I need to replace the variable's value, so then I should use `assign`?  Sorry, for these noob questions, I am fairly new to tensorflow.

**Comment by bhack** [comment]
Yes if you need only to assign.

**Comment by ion-elgreco** [comment]
> Yes if you need only to assign.

Thank you so much! 👍 Now I just need to simply fix the last error: `Matrix size-incompatible: In[0]: [1,64], In[1]: [128,64] [Op:MatMul]` 

Which seems to be related to my fast weights matrix initialization, however, if I choose [batch_size, units] as shape to initialize the fast weights matrix, my output shape of the RNN layer will be `[batch_size, sequence_length, features]`, while it has to be `[None, sequence_length, features]`, and it will return this error:

`Matrix size-incompatible: In[0]: [128,64], In[1]: [128,64] [Op:MatMul]`

**Comment by bhack** [comment]
For other general support question you need to use https://stackoverflow.com/questions/tagged/tensorflow

**Comment by ion-elgreco** [comment]
> For other general support questions you need to use https://stackoverflow.com/questions/tagged/tensorflow

Will do! Thanks for the help :)
