### ISSUE TITLE
Error while import tensorflow module

### ISSUE THREAD

**Issue by raffibaihaqy02** [tensorflow/tensorflow#44877]
I've installed TensorFlow by command (in power shell). It works
`python -m pip install --upgrade tensorflow`

then
`import tensorflow as tf`

I get this errors
`Traceback (most recent call last): File "C:\Users\Asus\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(file)]) File "C:\Users\Asus\AppData\Local\Programs\Python\Python36\lib\imp.py", line 296, in find_module raise ImportError(_ERR_MSG.format(name), name=name) ImportError: No module named '_pywrap_tensorflow'`

**Comment by Daved-byte** [comment]
for me, the problem was the cuDNN Library

**Comment by ravikyram** [comment]
@raffibaihaqy02 

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

.Also, please follow the instructions from to install from [Tensorflow website.](https://www.tensorflow.org/install/).
Please, check Your CPU/Python is on 32 bits?

Thanks!

**Comment by Xavier-pix** [comment]
> for me, the problem was the cuDNN Library

for whatever reason cudnn-8.0-windows10-x64-v8.0 was NOT working - I used cudnn-8.0-windows10-x64-v6 - ALL GOOD!
