### ISSUE TITLE
"FAILED: Build did NOT complete successfully (1 packages loaded)"

### ISSUE THREAD

**Issue by cray12399** [tensorflow/tensorflow#44876]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Source
- TensorFlow version: I am not sure. I cloned it from the Github repository so it should be the latest version
- Python version: 3.7
- Installed using virtualenv? pip? conda?: Trying to install with Pip, but I am getting an error when I try to build a pip package via Bazel.
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: NA
- GPU model and memory: Radeon RX 5700XT, G.Skill Trident-Z 2x16GB

**Describe the problem**
I am trying to build Tensorflow from the source since my training sessions are performing really slow and barely utilizing my hardware. I read that I can get better performance by building it from the source for my machine. However, I am getting an error when I tried to build a pip package via Bazel as according to the steps from the link:
https://www.tensorflow.org/install/source

This is the output I am getting when I try to build the package with Bazel:
```
root@weapon-of-mass-instruction:/home/chris/tensorflow# bazel build [--config=option] //tensorflow/tools/pip_package:build_pip_package
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=140
INFO: Reading rc options for 'build' from /home/chris/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/chris/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from /home/chris/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/lib/python3/dist-packages --python_path=/usr/bin/python3 --config=xla --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file /home/chris/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/chris/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /home/chris/tensorflow/.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:linux in file /home/chris/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/chris/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
DEBUG: Rule 'io_bazel_rules_go' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1557349968 -0400"
DEBUG: Repository io_bazel_rules_go instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule git_repository defined at:
  /root/.cache/bazel/_bazel_root/a819f6789d392dd47d3107e5934b6ad1/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18: in <toplevel>
ERROR: Skipping '[--config=option]': no such target '//:[--config=option]': target '[--config=option]' not declared in package '' defined by /home/chris/tensorflow/BUILD
ERROR: no such target '//:[--config=option]': target '[--config=option]' not declared in package '' defined by /home/chris/tensorflow/BUILD
INFO: Elapsed time: 8.402s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
    currently loading: tensorflow/tools/pip_package
    Fetching @local_config_cuda; Restarting.
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
1. git clone https://github.com/tensorflow/tensorflow.git
2. cd tensorflow
3. ./configure
4. Left everything default and chose no for ROCM/CUDA/Clang/etc.
5. bazel build [--config=option] //tensorflow/tools/pip_package:build_pip_package
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I do not have an ROCM compatible GPU (at least as far as I am aware. If I am wrong, I would definitely appreciate some advice on making Tensorflow work with my card) so I am trying to optimize Tensorflow to run on my CPU, which is a Ryzen R9 3900X. When I run Tensorflow, it appears to barely utilize my CPU as according to my process monitor, so I am looking to build Tensorflow for my machine in hopes that it will make a difference in performance.

All advice and help with issue will be greatly appreciated!

**Comment by bhack** [comment]
See https://github.com/RadeonOpenCompute/ROCm#supported-gpus
I suggest you also to profile your code with https://www.tensorflow.org/guide/profiler

Tensorflow ROCM is available at https://pypi.org/project/tensorflow-rocm/

**Comment by JRF63** [comment]
You're not supposed to input `[--config=option]` as is. Brackets usually means "you can supply something in here in this format."

Try:
```sh
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
```
or
```sh
bazel build --config=opt --config=mkl //tensorflow/tools/pip_package:build_pip_package
```

**Comment by cray12399** [comment]
Damn, I feel really dumb now haha. Removing the brackets worked. Also, I will check out RoCM since I see that it supports Ryzen CPUs. I thought it only supported GPUs.

Thanks a ton for your help!

**Comment by amahendrakar** [comment]
@cray12399,
Thank you for the update. Marking this issue as closed, as it is resolved. Please feel free to re-open if necessary.
