### ISSUE TITLE
Tensor flow: append tensor operation

### ISSUE THREAD

**Issue by vasilevskykv** [tensorflow/tensorflow#44875]
Hello. 
I have the following operation with **numpy** array:
`data.append(dataset[indices])`
**dataset[indices]** -  numpy.ndarray array with data [0.0345, 0.0522, -0.234, 0.118, -0.568, 0.772,...]
The number of data is big, so it takes a long time for calculation on CPU. To make calculations faster I used TensorFlow.
I found out that only tensor operations can be performed on GPU. 
That's why I needed such operation as `tf.append(...)` that could be add an element to an array inside of the tensor, declared by the following way: `tf.Variable([],tf.float32)` And after certain number of these operations an inside array of the tensor should be changed from empty to [0.0345, 0.0522, -0.234, 0.118, -0.568, 0.772,...]. After reading of documentation I didn't find such operation in TensorFlow

And the question is following: What is the way to make what I want, using Tensor operations?

**Comment by bhack** [comment]
If you are working with numpy code you could explore (with tf-nightly) https://www.tensorflow.org/api_docs/python/tf/experimental/numpy/append.

See also 
https://youtu.be/DpOq0PJ0H38

**Comment by vasilevskykv** [comment]
I was trying to install tf-nightly and I've got an error:

ERROR: Could not install packages due to an EnvironmentError: [WinError 32] The process cannot access the file because it is being used by another process: 'I:\\Python\\Python37\\Lib\\site-packages\\tensorflow\\python\\keras\\layers\\core.py'
Consider using the `--user` option or check the permissions.

**Comment by bhack** [comment]
Cause Tensorflow Is running

**Comment by vasilevskykv** [comment]
So I have to delete Tensorflow?

**Comment by vasilevskykv** [comment]
How can I stop TensorFlow? I tried to install tf-nightly and no one of my programs, that uses TensorFlow, was running

**Comment by bhack** [comment]
Check https://gallery.technet.microsoft.com/How-to-find-out-which-c0d4e60e

**Comment by vasilevskykv** [comment]
I installed another version of Python (3.7.6). Then I installed tf-nightly and tf-nightly-gpu (version 2.5), CUDA 11.0 and cuddn v8.0.5
And I got an error:
W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
This DLL has written in the Environment Variable PATH

**Comment by vasilevskykv** [comment]
What else should I install?

**Comment by bhack** [comment]
TF by next version (2.4.1) requires CUDA 11

**Comment by vasilevskykv** [comment]
I have already installed CUDA 11.
But TF 2.4.1 don't want to install because of installed tf-nightly

**Comment by vasilevskykv** [comment]
May be my GPU is not compatible with tf-nightly 2.5? That's why an error "W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found" appears?

**Comment by bhack** [comment]
It seems that doesn't find that CUDA file in your system paths. Check https://www.tensorflow.org/install/gpu?hl=en
