### ISSUE TITLE
TensorFlowLiteSelectTfOps: Interpreter creation fails on iOS when scheme is set to Release

### ISSUE THREAD

**Issue by clo-dan** [tensorflow/tensorflow#44879]
**System information**

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
iOS 14.1. Development environment is Xcode 12.2 (12B45b), macOS Big Sur 11.0.1.

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
iPhone SE 2016

- TensorFlow installed from (source or binary) / TensorFlow version (use command below):
pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly.20201107', :subspecs => ['CoreML', 'Metal']
pod 'TensorFlowLiteSelectTfOps', '0.0.1-nightly.20201031'

**Describe the current behavior**

Interpreter is created successfully when target scheme's build configuration is set to Debug. When build configuration is set to Release, it fails with:

> TensorFlow Lite Error: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
> TensorFlow Lite Error: Node number 6 (FlexRFFT) failed to prepare.

**Describe the expected behavior**

Interpreter should be created successfully in Release builds.

**Standalone code to reproduce the issue**
```
import TensorFlowLite
...
let modelPath = Bundle.main.bundleURL.appendingPathComponent("model.tflite").path
do {
    let interpreter = try Interpreter(modelPath: modelPath)
    try interpreter.allocateTensors()
} catch {
    NSLog("\(error)")
}
```

**Other info / logs**

**Can work around by going to target > Build Settings and changing Dead Code Stripping to No.**

**Comment by yyoon** [comment]
@thaink Can you please take a look?

**Comment by thaink** [comment]
I was able to reproduce this issue. let me investigate more.

**Comment by rapuckett** [comment]
@clo-dan 's work-around works when running from XCode, but this issue seems to persist (even with work-around) when building/deploying to TestFlight.

**Comment by thaink** [comment]
> @clo-dan 's work-around works when running from XCode, but this issue seems to persist (even with work-around) when building/deploying to TestFlight.

What work-around is that?

**Comment by rapuckett** [comment]
From original post: "Can work around by going to target > Build Settings and changing Dead Code Stripping to No."

This allows app to run on device with Release config. Otherwise will get the error described. But even with this, TestFlight builds still don't work.

**Comment by clo-dan** [comment]
Can confirm, our TestFlight builds also produce the error even with the workaround. We have bitcode disabled but symbolicated reports are enabled.

**Comment by clo-dan** [comment]
Also reproducible by doing an ad hoc build and sideloading the IPA to phone via Xcode Devices and Simulators window, which is easier to test than uploading to TestFlight. Even tried setting Archive build config to Debug instead of Release, same result.

Something about Xcode's packaging process is ignoring the Dead Code Stripping setting. Xcode forces stripSwiftSymbols in all archive builds now with no option to disable so possibly it's that.

**Comment by thaink** [comment]
I found that the problem can be fixed when adding "-u _TF_AcquireFlexDelegate" to Build Settings -> Other Linker Flags.
@clo-dan @rapuckett  Could you give it a try?

**Comment by clo-dan** [comment]
This lets me run from Xcode without dead stripping but ad hoc builds still fail. Have not tried TestFlight yet but assume it will fail given ad hoc does.

**Comment by rapuckett** [comment]
Same here. Also tried on TestFlight and it unfortunately did not work there
either.

**Comment by thaink** [comment]
> This lets me run from Xcode without dead stripping but ad hoc builds still fail. Have not tried TestFlight yet but assume it will fail given ad hoc does.

Do you mean it is OK with dead_stripping=yes or not?
Can you guide me how to build for ad hoc and TestFight? I haven't done that before.

**Comment by clo-dan** [comment]
Sorry, meant I can run it without _disabling_ dead stripping now.

For ad hoc: Product > Archive, once complete select the archive in Organizer > Distribute App > Ad Hoc > Next > Auto manage signing > Export. Then, with phone connected, Window > Devices and Simulators > select your phone > click + under Installed Apps > select IPA file that was exported.

For TestFlight, same initial steps but instead of Ad Hoc distribution, choose App Store Connect > Upload.

**Comment by arlins** [comment]
Same issuse.
Adding "-u _TF_AcquireFlexDelegate" to Build Settings -> Other Linker Flags does work when using Xcode, but still not work on TestFlight

**Comment by arlins** [comment]
In Debug, "TF_AcquireFlexDelegate" will be called by  "TfLiteInterpreterCreate"   to create TensorFlow Lite delegate for select TF ops, but "TF_AcquireFlexDelegate" was not called in Release.

This issuse can be easily reproduced and should be able to locate the problem

**Comment by clo-dan** [comment]
I was able to get ad hoc and TestFlight builds working by going to target > Build Settings > **changing Strip Linked Product to No.**

**Comment by arlins** [comment]
@clo-dan TestFlight builds still not working for me, are there other configurations?

**Comment by arlins** [comment]
1.  Build Settings > changing Strip Linked Product
2. -u _TF_AcquireFlexDelegate

with these two configurations, it works on TestFlight.

**Comment by thaink** [comment]
As @clo-dan suggested, when set Build Settings > changing Strip Linked Product to No, it will work.
Besides, I submitted another fix, you can try it in tomorrow's nightly build.

**Comment by thaink** [comment]
This is fixed in master.
