### ISSUE TITLE
golang tensorflow issue

### ISSUE THREAD

**Issue by fishercray** [tensorflow/tensorflow#44871]
go: finding module for package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto
../../go/pkg/mod/github.com/tensorflow/tensorflow@v2.3.1+incompatible/tensorflow/go/saved_model.go:25:2: module github.com/tensorflow/tensorflow@latest found (v2.3.1+incompatible), but does not contain package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto

**Comment by bhack** [comment]
It is a duplicate of https://github.com/tensorflow/tensorflow/issues/41808. Can you close this and upvote/subscribe that one?
Thanks

**Comment by raffibaihaqy02** [comment]
> It is a duplicate of #41808. Can you close this and upvote/subscribe that one?
> Thanks

yo nice :) 👍

**Comment by fishercray** [comment]
It is a duplicate of #41808. Can you close this and upvote/subscribe that one?
Thanks
