### ISSUE TITLE
config parameter in tf.contrib.learn.Estimator is not working!

### ISSUE THREAD

**Issue by amirj** [tensorflow/tensorflow#4487]
I'm using TensorFlow 0.10 on Ubuntu (GPU). I have an estimator as follow:
```
  estimator = tf.contrib.learn.Estimator(
      model_fn=model_fn,
      model_dir=MODEL_DIR,
      config=tf.contrib.learn.RunConfig(
          save_checkpoints_secs=1))
```
I want to save checkpoints in every second. 
The problem is that after running, checkpoints are saved every 300 iterations and `config` parameter does not work!

**Comment by concretevitamin** [comment]
@martinwicke Martin - can you take a look at this?  Thanks.

**Comment by martinwicke** [comment]
This should work better in 0.11. It was a bug. I'll close this, hopefully this is fixed.
