### ISSUE TITLE
Bazel Build Issue

### ISSUE THREAD

**Issue by parayamelo** [tensorflow/tensorflow#44886]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Kubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 2.3.1
- Python version: 3.8
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 8.4
- CUDA/cuDNN version: 11.1/8
- GPU model and memory: 2070 / 8GB

**Describe the problem**
Trying to install tensorflow from source, I get the following error

ERROR: /home/pablo/.cache/bazel/_bazel_pablo/73a3c430b087017173c0bbcfb3b9758b/external/llvm-project/llvm/BUILD:1852:1: C++ compilation of rule '@llvm-project//llvm:Core' failed (Exit 1)
external/llvm-project/llvm/lib/IR/Function.cpp:46:10: fatal error: llvm/IR/IntrinsicsVE.h: No such file or directory
 #include "llvm/IR/IntrinsicsVE.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 64.162s, Critical Path: 26.84s
INFO: 593 processes: 593 local.
FAILED: Build did NOT complete successfully

**Provide the exact sequence of commands / steps that you executed before running into the problem**

Tensorflow configuration went ok, no problems. I compile with Bazel, and I get the error: bazel build --config=cuda //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mihaimaruseac** [comment]
Can you clone again please? It is likely you have cloned at a time when LLVM dependency (coming via MLIR) broke us.

**Comment by parayamelo** [comment]
Yes, it works now, thank you!

**Comment by amahendrakar** [comment]
@parayamelo,
Thank you for the update. Marking the issue as closed, as it it resolved. Please feel free to re-open the issue if necessary.
