### ISSUE TITLE
Can you please provide Nvidia Driver version for all tensorflow version? Is tensorflow 1.15.0 compatible with 410 Driver version?

### ISSUE THREAD

**Issue by WrathofBhuvan11** [tensorflow/tensorflow#44883]
Reusing code across different machines is difficult. The problem is that even if one could install a compatible tensorflow version, it's challenging to run code due to, `RuntimeError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version` error.
The driver update is not accessible if one is using a remote server and I cant run the code in the server. Wastage of resources.
In my case, `nvidia-smi` says the driver version is 410 and has tensorflow version 1.12.0 which is an older version compared to my code developed. Unfortunately, I can't run my code developed in my local drive belonging to tensorflow version 1.14.0 or above.

**Comment by amahendrakar** [comment]
@WrathofBhuvan11,
TensorFlow v1.15 is compatible with CUDA 10.0 and cuDNN 7.4. Please take a look at the [tested build configurations](https://www.tensorflow.org/install/source#gpu) for more information. 

And please check 'Table 2' from [this link](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#title-new-features) for the respective CUDA toolkit and compatible driver versions. Thanks!

**Comment by ymodak** [comment]
TF pre built binaries follows [Nvidia cudnn documentation](https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html).

**Comment by Zavrie** [comment]
Try to install focal fossa it give's great updates.
My pc runs on intel from mainboard :-)
For Nvidia for Ubuntu the way to go ;-)
