### ISSUE TITLE
Could not create cudnn handle TF2 GPU

### ISSUE THREAD

**Issue by BestSithInEU** [tensorflow/tensorflow#44885]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cudart64_101.dll / 7.6.0.64
- GPU model and memory: RTX 2080

**Describe the current behavior**
2020-11-15 16:46:03.303728: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2020-11-15 16:46:03.307912: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2020-11-15 16:46:03.308022: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

I checked some "Could not create cudnn handle" errors but I couldn't find any solutions yet. And I installed also exactly same edition as tf mentioned in their sites.
-NVIDIA® GPU drivers —CUDA® 10.1 requires 418.x or higher.
-CUDA® Toolkit —TensorFlow supports CUDA® 10.1 (TensorFlow >= 2.1.0)
-CUPTI ships with the CUDA® Toolkit.
-cuDNN SDK 7.6 (see cuDNN versions).
-(Optional) TensorRT 6.0 to improve latency and throughput for inference on some models.

I'm trying to use my simple CNN code;

```
# Convolutional Neural Network

# Importing Libraries

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Part 1 - Data Preprocessing

train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

training_set = train_datagen.flow_from_directory('C:/Users/batuh/OneDrive/Masaüstü/Udemy Courses/Deep Learning A-Z/Volume 1 - Supervised Deep Learning/Part 2 - Convolutional Neural Networks (CNN)/dataset/training_set',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'binary')

## Preprocessing the Test set

test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory('C:/Users/batuh/OneDrive/Masaüstü/Udemy Courses/Deep Learning A-Z/Volume 1 - Supervised Deep Learning/Part 2 - Convolutional Neural Networks (CNN)/dataset/test_set',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'binary')

# Part 2 - Building the CNN
## Initializing the CNN

cnn = tf.keras.models.Sequential()

## Step 1 - Convolution

cnn.add(tf.keras.layers.Conv2D(filters = 32, kernel_size = 3, activation = 'relu', 
                               input_shape = [64, 64, 3]))

## Step 2 - Pooling

cnn.add(tf.keras.layers.MaxPooling2D(pool_size = 2, strides = 2))

### Adding Second Conv. Layer

cnn.add(tf.keras.layers.Conv2D(filters = 32, kernel_size = 3, activation = 'relu'))
cnn.add(tf.keras.layers.MaxPooling2D(pool_size = 2, strides = 2))

## Step 3 - Flattening

cnn.add(tf.keras.layers.Flatten())

## Step 4 - Full Connection

cnn.add(tf.keras.layers.Dense(units = 128, activation = 'relu'))

## Step 5 - Output Layer

cnn.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

# Part 3 - Training the CNN
## Compiling the CNN
#with tf.device('/GPU:0'):
cnn.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

## Training the CNN
cnn.fit(x = training_set, validation_data = test_set, epochs = 50)
```

**Comment by king398** [comment]
I am having the same problem. Setting the kernel size to 2 instead of of 3 makes it work.

**Comment by BestSithInEU** [comment]
> I am having the same problem. Setting the kernel size to 2 instead of of 3 makes it work.
This time I've got that one;
```
E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2020-11-15 18:53:39.858320: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node sequential/conv2d/Conv2D}}]]
```

**Comment by king398** [comment]
I think you should upgrade your tensorflow version to 2.3.0 or 2.4.0rc1

**Comment by jnd77** [comment]
That reminds me of a common error with RTX cards.
Did you try to set the env variable TF_FORCE_GPU_ALLOW_GROWTH to "true" ?

**Comment by king398** [comment]
Also try adding this to the start of this projects just after upgrading your tensorflow  version and importing it 
`physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)`

**Comment by BestSithInEU** [comment]
Thanks for your help. I would like to summarize the solution briefly in case others have problems and investigate that problem.
`physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)`
This section must be added right after the import section. However, for usage of this code, people who face that issue, should use tensorflow 2.3 at least. I've double checked from [here](https://www.tensorflow.org/api_docs/python/tf/config), config added on Tensorflow 2.3.0. Again I really appreciated you both @king398 and @jnd77 . Have a nice day you all, <3 Cheers!

**Comment by king398** [comment]
@BestSithInEU Glad that you found it useful

**Comment by RohanRatwani** [comment]
Hey I'm using TF 2.2.0 with CUDA 10.1 I think it is compatible 
I'm getting the same error even after performing the function to limit memory growth

> Also try adding this to the start of this projects just after upgrading your tensorflow version and importing it
> `physical_devices = tf.config.list_physical_devices('GPU') tf.config.experimental.set_memory_growth(physical_devices[0], True)`

**Comment by king398** [comment]
@RohanRatwani which gpu you are using and please show your code in the issue and the full log file. Also try upgrading your tensorflow version to 2.3.0

`pip install —upgrade tensorflow=2.3.0`
