### ISSUE TITLE
yolov3-tiny tflite model of shape [1, 2535, 85] representation

### ISSUE THREAD

**Issue by agh372** [tensorflow/tensorflow#44890]
I found a tflite model of shape [1, 2535, 85] with 80 classes.

I am aware that each item in the array represents each bounding box information.

So yolo-v3 tiny model uses two scales `13 x 13` and` 26 x 26`

3 * (13 * 13) = 507
3 * (26 * 26)  = 2028 +
                       = 2535

Each cell has 3 bounding box information.

I'm not sure how are this information arranged in the array of 2535. 

If the 0th index represents the first cell (0,0) of 13 scale for the first bounding box

what does the 1st index represent then?

**Does it represent the second bounding box information for the first cell (0,0) of 13 scale**

or

**Does it represent the first bounding box information for the second cell (0,1) of 13 scale?**

**Comment by srjoglekar246** [comment]
TBH, its difficult to gauge what the model tensors mean without looking at the TF code that generated the model :-).
What is the source of the model? Is it from some TF repo?

**Comment by Saduf2019** [comment]
Could you please update as per above comment
