### ISSUE TITLE
tf-gpu 1.14 - Enabling eager execution not working.

### ISSUE THREAD

**Issue by YashRunwal** [tensorflow/tensorflow#44898]
Hello guys,

I am using tf-gpu 1.14 version.

I want to apply the following loss [BinaryCrossentropy](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/keras/losses/BinaryCrossentropy) . But I am getting the error called "**Tensor object cannot be converted to numpy**".

When I searched this error on stackoverflow, I found out that I have to enable eager_execution. So I tried doing that but I get the error " **AttributeError: module 'tensorflow._api.v1.config' has no attribute 'run_functions_eagerly'**".

Note that I cannot upgrade tensorflow and I want to convert the tensor to numpy array. Is there a way around this? or is this a bug? 

I appreciate your help.

**Comment by ravikyram** [comment]
@YashRunwal 

Please, share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster. 
Also, TF 1.x is not actively supported.It will be good idea to switchover to TF 2.x for better performance.
Thanks!
