### ISSUE TITLE
TF code crashes python kernel

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#449]
The following piece of code:

    import tensorflow as tf
    a = tf.placeholder(tf.float32, shape=(-1, 10))
    sess = tf.Session()
    sess.run(tf.array_ops.shape(a))

crashes the Python kernel. I realize it's not right (for one thing I'm not feeding it a `feed_dict`), but it should give an error and not crash the kernel.

**Comment by girving** [comment]
Nice catch!  Yes, that is a bad bug.

**Comment by girving** [comment]
I have this fixed at the kernel level, so it won't crash anymore.  However, I could also fix it at the shape inference level so it throws a Python exception at graph construction time.  To do this, I'd need to make `tf.Dimension` insist on nonnegative input.

@vrv: Do you think that's wise?  I'd be a bit worried that negative dimensions are used somewhere, but it's currently a bit inconsistent that C++ `TensorShape` requires nonnegative but Python `TensorShape` does not.

**Comment by girving** [comment]
C++ part in review.

**Comment by vrv** [comment]
I'm not sure yet if its wise -- the C++ TensorShape class thinks about shapes more concretely: it doesn't support unspecified dimensions / -1 / shape inference, etc.

I think when we push shape inference down into the C++ code, we'll likely have a C++ class that more closely represents what the python TensorShape class does.

**Comment by girving** [comment]
Cool, I'm happy to leave it the way it is now that the C++ is fixed.

**Comment by bdevyansh** [comment]
try using numpy befor importing tensorflow or keras
