### ISSUE TITLE
RecursionError with `dynamic=True` when using a `Lambda` layer 

### ISSUE THREAD

**Issue by Lescurel** [tensorflow/tensorflow#44906]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): binary 
- TensorFlow version (use command below): v2.3.0-rc2-23-gb36436b087 2.3.0
- Python version: 3.8.5

**Describe the current behavior**

When running a `Lambda` layer with `dynamic=True`, the code crashes with a `RecursionError`.

**Describe the expected behavior**

No crash. 

**Standalone code to reproduce the issue**

```python
import tensorflow as tf
inp = tf.keras.Input(shape=(10,))
out = tf.keras.layers.Lambda(
        lambda x_input: x_input,
        dynamic=True,
)(inp)
model = tf.keras.Model(inputs=inp, outputs=out)
```

**Other info / logs** 

[traceback_recursion_error.log](https://github.com/tensorflow/tensorflow/files/5546954/traceback_recursion_error.log)

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2, 2.3 and nightly version(`2.5.0-dev20201116`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/08c4a080d0ab6b9451e0ec9536747bfb/untitled519.ipynb). Thanks!

**Comment by bhack** [comment]
@Lescurel Do you like a better error message?

Extracted from the doc https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer?version=nightly
>dynamic: Set this to True if your layer should only be run eagerly, and should not be used to generate a static computation graph. This would be the case for a Tree-RNN or a recursive network, for example, or generally for any layer that manipulates tensors using Python control flow. If False, we assume that the layer can safely be used to generate a static computation graph. 

If you run a similar example you can check:
```
import tensorflow as tf
inp = tf.keras.Input(shape=(10,))
def my_lambda_func(x):
    print(tf.executing_eagerly())
x = tf.keras.layers.Lambda(my_lambda_func)(inp)
```

**Comment by Lescurel** [comment]
If passing `dynamic=True` to a Lambda layer is indeed impossible, then yes, I would have expected a better error message. 

But I don't really see why it would be impossible. It feels to me that it is more likely to end up  writing Python control flow code in a Lambda layer than in any other layer.

**Comment by bhack** [comment]
It Is ok to me to keep this open for a better error message.
As you can see with my print in lambda you are no more in eager mode this match with documentation.

**Comment by Lescurel** [comment]
To add a bit of context, I ended finding that bug in a more complex program that ended up throwing that Traceback : 

[traceback.log](https://github.com/tensorflow/tensorflow/files/5560933/traceback.log)

In that Traceback, the first error I see is : 

>     OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did not convert this function. Try decorating it directly with @tf.function.

Which I ignore, given that the function was already decorated with `@tf.function`. (This is also a strange behaviour, but I can't reproduce it)

The second error is: 

>   TypeError: You are attempting to use Python control flow in a layer that was not declared to be dynamic. Pass `dynamic=True` to the class constructor.

The problem is that apparently, those two suggestions are incompatible with each other, if I believe your example.

**Comment by bhack** [comment]
I cannot see your context with the current code.

**Comment by Lescurel** [comment]
Sorry, I forgot to add that the error was caused by a Lambda layer. Basically something like the example below caused the error. However, I have been unable to reproduce with a minimal example, so the example below is completely functional. 

```python
import tensorflow as tf

@tf.function
def python_control_flow_fn(tensor):
    return tf.concat([t for t in tensor],axis=0)

inp = tf.keras.Input(shape=(10,))
layer = tf.keras.layers.Lambda(python_control_flow_fn)(inp)
```

The traceback seems to suggest that I can either add `@tf.function` to my Python control flow function, or add `dynamic=True` to the layer.

**Comment by bhack** [comment]
> OperatorNotAllowedInGraphError: iterating over tf.Tensor is not allowed: AutoGraph did not convert this function. Try decorating it directly with @tf.function.

This is not related to lambda:
````python
@tf.function
def python_control_flow_fn(tensor):
    return tf.concat([t for t in tensor],axis=0)

inp = tf.keras.Input(shape=(10,))
python_control_flow_fn(inp)

**Comment by nikitamaia** [comment]
Adding the contributions welcome label to this issue for further investigation by the community. If you are interested in working on this issue, please leave a comment and I will assign it to you. Thanks!

**Comment by nicolaspi** [comment]
Hi,
this error happens even in eager mode (tf 2.4.1):

```python

import tensorflow as tf

tf.config.run_functions_eagerly(True)

input = tf.keras.Input(shape=())

@tf.function
def fn(x):
    return x

output = tf.keras.layers.Lambda(fn, dynamic=True)(input)
tf.keras.Model(inputs=input, outputs=output)
```
throws:

`RecursionError: maximum recursion depth exceeded while calling a Python object`

**Comment by bhack** [comment]
@nikitamaia Can you assign this to @fsx950223 he has already a submitted PR.

**Comment by nikitamaia** [comment]
Thanks for the heads up @bhack!

@fsx950223 can you leave a comment on this thread requesting to be assigned? Github settings won't let me assign someone unless they have commented on the thread :)

**Comment by fsx950223** [comment]
Please assign the issue to me.

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210602, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/4b23f0c1e384137b1666c3a22a4c4ddf/44906.ipynb). Thanks!

**Comment by oawxkw** [comment]
I also observed the following alternative names of the API have the same behavior that causes the `RecursionError` Exception:

- `(tf.keras.layers.Lambda)`, `tf.compat.v1.keras.layers.Lambda`

This behavior still exists in tensorflow nightly (2.15.0-dev20230920), and users should be cautious when using them on both CPU and GPU.

<details>
  <summary>Code to reproduce the issue in <code>tf.compat.v1.keras.layers.Lambda</code></summary>

```python
import tensorflow as tf
print(tf.version.GIT_VERSION, tf.version.VERSION, flush=True)
print(tf.config.list_physical_devices(), flush=True)


inp = tf.keras.Input(shape=(10,))
out = tf.compat.v1.keras.layers.Lambda(
        lambda x_input: x_input,
        dynamic=True,
)(inp)
model = tf.keras.Model(inputs=inp, outputs=out)
```

On my GPU machine, the above code produces the following output, and the `RecursionError` Exception is raised.

```text
v2.14.0-rc0-34-gdd01672d9a9 2.14.0-rc1
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Traceback (most recent call last):
  File "/tmp/analyze/44906-4-s/tf.compat.v1.keras.layers.Lambda.py", line 7, in <module>
    out = tf.compat.v1.keras.layers.Lambda(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/lib/python3.11/inspect.py", line 3272, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/inspect.py", line 3020, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/inspect.py", line 2457, in _signature_from_callable
    obj = unwrap(obj, stop=(lambda f: hasattr(f, "__signature__")))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/inspect.py", line 760, in unwrap
    memo = {id(f): f}
            ^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object
```

This behavior is also reproducible on my CPU machine:

```text
v2.14.0-rc0-34-gdd01672d9a9 2.14.0-rc1
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
Traceback (most recent call last):
  File "/tmp/analyze/44906-4-s/tf.compat.v1.keras.layers.Lambda.py", line 7, in <module>
    out = tf.compat.v1.keras.layers.Lambda(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/lib/python3.11/inspect.py", line 3272, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/inspect.py", line 3020, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/inspect.py", line 2457, in _signature_from_callable
    obj = unwrap(obj, stop=(lambda f: hasattr(f, "__signature__")))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/inspect.py", line 760, in unwrap
    memo = {id(f): f}
            ^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object
```
</details>
