### ISSUE TITLE
Use correctly shuffle=False in fit_generator() function

### ISSUE THREAD

**Issue by victor-robotic-24** [tensorflow/tensorflow#44900]
Shuffle parameter in fit_generator function can take two boolean values: True or False. I want to execute fit_generator without altering the order of the batches at each epoch of the training, so I have to assign 'shuffle=False'. Also, I want to specify the number of steps per epoch, but shuffle parameter has effect when 'steps_per_epoch=None'.

- Is there any way to solve that?
- How can I use correctly shuffle parameter in fit_generator function?
- Is there any way to check batches at each epoch are not being shuffling?

**Comment by rmothukuru** [comment]
@victor-robotic-24, 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by rmothukuru** [comment]
@victor-robotic-24,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
