### ISSUE TITLE
Conv2dTranspose layer creates additional operators on tflite conversion (Shape, Pack and Strided Slice)

### ISSUE THREAD

**Issue by anilsathyan7** [tensorflow/tensorflow#44905]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary):  Binary
- TensorFlow version (or github SHA if from source):  TF 2..3.0, TF Nightly

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
model=tf.keras.models.load_model('amnv3seg.h5')

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open("mnv3_seg_mew_2.3.tflite", "wb").write(tflite_model)
```

**The output from the converter invocation**

```
# Copy and paste the output here.

# In Tf 2.3.0
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/tracking.py:111: Layer.updates (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: /tmp/tmpc0xpp5l1/assets
10776624



# In TF-Nightly
INFO:tensorflow:Assets written to: /tmp/tmpqt986x_h/assets
INFO:tensorflow:Assets written to: /tmp/tmpqt986x_h/assets
10775140
```

**Failure details**
 The converted tflite model creates additonal **shape , pack and strided slice** operators and they are not supported by **gpu delegate** in android. The issue persists in TF 2.3 and TF Nightly.  The issue happens with or without bias parameter in Conv2dTranspose layer.

**Any other info / logs**

The original tf model is based on mobilenetv3 pretrained model and is available only in tf-nightly
[conv2dmodels.zip](https://github.com/tensorflow/tensorflow/files/5546200/conv2dmodels.zip)

**Comment by wangtz** [comment]
Hi Ashwin, 

Could you have a look on this converter related issue? Feel free to reassign.

Thanks,

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/e40b2d73d45566455a3ae21d1fdda398/44905.ipynb). Thanks!

**Comment by anilsathyan7** [comment]
The issue is similar to https://github.com/tensorflow/tensorflow/issues/45090#issuecomment-732389188.
It seems to be a problem associated with dynamic sizes in keras and the new convereter requires you to fix the batch size of input layer before tflite conversion
