### ISSUE TITLE
undefined reference in tensorflow-lite shared library generated by cmake

### ISSUE THREAD

**Issue by pkorodiTM** [tensorflow/tensorflow#44916]
**System information**
- OS Platform and Distribution: macOS
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.5.0 (from git clone latest)
- Python version: Python 3.8.6
- Installed using virtualenv? pip? conda?: 
- CMake version (if compiling from source): 3.18.0
- GCC/Compiler version (if compiling from source): Android ndk r21
- CUDA/cuDNN version:
- GPU model and memory: Radeon Pro 555X 4 GB

**Describe the problem**
I compiled tensorflow-lite with cmake on android. I created an android JNI project. In this application I tried to link together all .a files (compiled by tensorflow-lite) into an .so shared library. In the cpp code I just get the version of the tensorflow-lite lib.
I got this linker error:
```
libtensorflow-lite.a(platform_profiler.cc.o): In function `tflite::profiling::MaybeCreatePlatformProfiler()':
tensorflow/tensorflow/lite/profiling/platform_profiler.cc:30: undefined reference to
`tflite::profiling::MaybeCreateATraceProfiler()'
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
git clone --recursive git@github.com:tensorflow/tensorflow.git
cd tensorflow
mkdir tf_build
cd tf_build
cmake -DCMAKE_TOOLCHAIN_FILE=~/Library/Android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a ../tensorflow/lite
cmake --build . -j
```

In the cpp source I just get the version of the lib:
```
#include <tensorflow/lite/c/c_api.h>
```
```
printf("TensorFlow C library version %s\n", TfLiteVersion());
```

**Any other info / logs**
I think the problem is in the `tensorflow/tensorflow/lite/CMakeLists.txt`:
```
# TFLite library
add_library(tensorflow-lite
  ${TFLITE_CORE_API_SRCS}
  ${TFLITE_CORE_SRCS}
  ${TFLITE_C_SRCS}
  ${TFLITE_DELEGATES_FLEX_SRCS}
  ${TFLITE_DELEGATES_GPU_SRCS}
  ${TFLITE_DELEGATES_NNAPI_SRCS}
  ${TFLITE_DELEGATES_SRCS}
  ${TFLITE_DELEGATES_XNNPACK_SRCS}
  ${TFLITE_EXPERIMENTAL_RESOURCE_SRCS}
  ${TFLITE_EXPERIMENTAL_RUY_PROFILER_SRCS}
  ${TFLITE_EXPERIMENTAL_RUY_SRCS}
  ${TFLITE_KERNEL_INTERNAL_OPT_INTEGER_OPS_SRCS}
  ${TFLITE_KERNEL_INTERNAL_OPT_SPARSE_OPS_SRCS}
  ${TFLITE_KERNEL_INTERNAL_OPT_SRCS}
  ${TFLITE_KERNEL_INTERNAL_REF_INTEGER_OPS_SRCS}
  ${TFLITE_KERNEL_INTERNAL_REF_SPARSE_OPS_SRCS}
  ${TFLITE_KERNEL_INTERNAL_REF_SRCS}
  ${TFLITE_KERNEL_INTERNAL_SRCS}
  ${TFLITE_KERNEL_SRCS}
  ${TFLITE_NNAPI_SRCS}
  ${TFLITE_SRCS}
  ${TFLITE_SOURCE_DIR}/profiling/platform_profiler.cc
  ${TFLITE_SOURCE_DIR}/schema/schema_utils.cc
  ${TFLITE_SOURCE_DIR}/tools/optimize/sparsity/format_converter.cc
)
```

It includes `${TFLITE_SOURCE_DIR}/profiling/platform_profiler.cc` and this file uses `MaybeCreateATraceProfiler` function. But the implementation of this function is not added to the tensorflow-lite library.
I think a solution can be adding  `${TFLITE_SOURCE_DIR}/profiling/atrace_profiler.cc` to the tensorflow-lite library.

**Comment by terryheo** [comment]
Just verified. I'm working on this.

**Comment by terryheo** [comment]
It's fixed now.

**Comment by KarlKulator** [comment]
Same problem happens with the Makefile build (``tensorflow/lite/tools/make/Makefile). `profiling/atrace_profiler.cc` is not being built when building for android. But I guess the Makefile build should not support android builds?

**Comment by mmarouen** [comment]
same thing could/should be added to the "iOS" macro, in the tflite CMake Line 444 under:
`if(CMAKE_SYSTEM_NAME MATCHES "Android")
  list(APPEND TFLITE_PROFILER_SRCS
    ${TFLITE_SOURCE_DIR}/profiling/atrace_profiler.cc
  )`
Similarly a "iOS" loop needs to be added
`elseif(CMAKE_SYSTEM_NAME MATCHES "iOS")
  list(APPEND TFLITE_PROFILER_SRCS
    ${TFLITE_SOURCE_DIR}/profiling/atrace_profiler.cc
  )`
