### ISSUE TITLE
Problems to convert a tensorflow model to TFLite

### ISSUE THREAD

**Issue by edgarbc** [tensorflow/tensorflow#44918]
HI there, 
I am having problems when I transformed my trained model into a TFLite model:

**System information**
- OS Platform and Distribution: CentOS Linux 7 (Core)
- TensorFlow installed from (source or binary): binary

**Command used to run the converter or code if you’re using the Python API**

```
import numpy as np
#from google.colab import files
import tensorflow as tf
from tensorflow import keras
from keras.preprocessing import image
import glob
import pickle

model_path = '/home/mymodel.h5'

# convert the model
model = keras.models.load_model(model_path)
print('model loaded!')
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
print('model converted!')

print('saving model...')
# save the lite model
with open('mymodel.tflite','wb') as f:
    f.write(tflite_model)

# done
print('convertion finished!')

```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
The model is transformed successfully but the converted model does not have the same input dimensions (instead the dimensions are transposed):

**Any other info / logs**
I am running the converted model using the interpreter (https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp35-cp35m-linux_armv7l.whl) in a Raspberry Pi B+

'''
from tflite_runtime.interpreter import Interpreter

  self.input_details = self.interpreter.get_input_details()
  self.output_details = self.interpreter.get_output_details()
  # check the type of the input tensor
  self.floating_model = self.input_details[0]['dtype'] == np.float32
  # details about the input image
  self.height = self.input_details[0]['shape'][1]
  self.width = self.input_details[0]['shape'][2]
  self.interpreter.set_tensor(self.input_details[0]['index'],input_data)  
  img = Image.open(path)
  print(img.size)
  input_data = np.expand_dims(img, axis=0)
  print(input_data.shape)
  if self.floating_model:
      input_data = (np.float32(input_data) - input_mean) / input_std

  self.interpreter.set_tensor(self.input_details[0]['index'], input_data)
  print('tensor set!')
  self.interpreter.invoke()
'''

This is the output:

'''
INFO: Initialized TensorFlow Lite runtime.
model loaded!
allocating tensors...
[{'quantization': (0.0, 0), 'shape': array([  1, 640, 480,   3]), 'index': 0, 'name': 'conv2d_input', 'dtype': <class 'numpy.float32'>}]
(640, 480)
(480, 640, 3)
image expanded shape:
(1, 480, 640, 3)
'''

and I get this error
'''
ValueError: Cannot set tensor: Dimension mismatch. Got 480 but expected 640 for dimension 1 of input 0.
'''
This error is not present if I run the same code using the original model.

- If I transpose the image to meet the input expectations of the converted model (480x640 instead of the 640x480 in the original), I can run the model but the output of the model is always [0 1. 0 0 0] regardless of the input (the original model works 
well).

Many thanks in advance for any idea about how to solve this.

Best,
Edgar

**Comment by ravikyram** [comment]
@edgarbc 

Will it be possible to share `mymodel.h5`. So it helps us in localizing the issue faster.I believe all image inputs are fixed size.Thanks!

**Comment by edgarbc** [comment]
Hi ravikyram,

You can have a look at mymodel.h5 [here](https://www.dropbox.com/s/gb78ssrnv94puk9/mymodel.h5?dl=0). I am using TF 2.2.

Thank you for your help.

**Comment by jvishnuvardhan** [comment]
@edgarbc I tried reproducing the issue. I can see that the image sizes are swapped but that is not related to tensorflow. This size swapping is related to PIL module. Please check [this Stackoverflow example](https://stackoverflow.com/questions/26561800/pil-image-size-returns-the-opposite-width-height). 

[Here](https://colab.research.google.com/gist/jvishnuvardhan/638301c522c4e095b6bb5b7bfb2c7368/untitled.ipynb) is the gist for our reference. Thanks!

**Comment by edgarbc** [comment]
Hi  jvishnuvardhan,
Thanks for looking into this. 

I know that the dimensions when you do img.size (from PIL Image) is transposed compared to a numpy array when you do x.shape when you do input_data = np.expand_dims(img, axis=0) but that is not the issue. The dimensions are correctly handled by the original model.

I know this because when I run the same code but instead of using the TFLite converted model, I use the original h5 model, I can run it no problem. That is why I think there is something with the converted model. If it helps, [this](https://www.dropbox.com/s/w03lb9g8dujd018/mymodel.tflite?dl=0) is the converted model.

Thanks again,
Edgar

**Comment by jvishnuvardhan** [comment]
@edgarbc Can you please share entire code so that I can check before and after model conversion to tflite? Thanks!

**Comment by edgarbc** [comment]
This is the code that I use without converting the model:
'''
import numpy as np
from tensorflow import keras
from PIL import Image
from numpy import asarray
import glob

model_path = 'mymodel.h5'
datadir = '/datapath/'

# load model
model = keras.models.load_model(model_path)
print('model loaded!')

fnames = glob.glob(datadir+'*.jpg')

i=0
for fn in fnames:
    path = fn
    print(path)
    img = Image.open(path)
    print(img.size)

    x = asarray(img)
    print(x.shape)

    x = np.expand_dims(x, axis=0)
    print(x.shape)

    pred = model.predict(x)
    print(i,pred)
    i = i + 1
'''

This is the code I use on the raspberry pi when I try to use the converted model (mymodel.tflite):

'''
from tflite_runtime.interpreter import Interpreter
import numpy as np
from PIL import Image
from numpy import asarray
import glob

interpreter = Interpreter(model_path='mymodel.tflite')
print('model loaded!')
print('allocating tensors...')
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
datadir = 'datapath'
fnames = glob.glob(datadir+'*.jpg')
i=0

        for fn in fnames:
            path = fn
            print(path)

            img = Image.open(path)
            print(img.size)
            x = asarray(img)
            print(x.shape)
            
            input_data = np.expand_dims(x, axis=0)
            print(input_data.shape)
            
            interpreter.set_tensor(input_details[0]['index'], input_data)
            print('tensor set!')
            
            interpreter.invoke()            
            print('interpreter invoked!')
            
            output_data = interpreter.get_tensor(output_details[0]['index'])
            print('output data calculated!')
            
            result = np.squeeze(output_data)
            print(result)
            print(i)
            i = i + 1
'''
I hope this helps to clarify this further.
Thanks,
Edgar

**Comment by jvishnuvardhan** [comment]
@edgarbc Looking at the `input_details[0]['index']`, model is expecting an array of shape `[ 1, 640, 480, 3]`. However, `input_data` is of different size (`[ 1, 480, 640, 3]`. Because of this shape incompatibility it is throwing an error at this line
`interpreter.set_tensor(input_details[0]['index'], input_data)`

I am not sure why the output always is [0 1. 0 0 0]. Any Idea @karimnosseir . Thanks!

**Comment by karimnosseir** [comment]
The model shapes looks fine to me, i don't see differences between the .h5 and the tflite.
As for the output, @jvishnuvardhan do you have gist with data used that reproduce the problem.

**Comment by jvishnuvardhan** [comment]
@karimnosseir [Here](https://colab.research.google.com/gist/jvishnuvardhan/2bad760e2893d2a63ef8f4aa70d9a99a/untitled67.ipynb) is the gist for reference. I downloaded the tflite model from [above](https://github.com/tensorflow/tensorflow/issues/44918#issuecomment-729850629), and downloaded images with (640, 480,   3) shape to run the gist. Thanks!

**Comment by edgarbc** [comment]
> 
> 
> @edgarbc Looking at the `input_details[0]['index']`, model is expecting an array of shape `[ 1, 640, 480, 3]`. However, `input_data` is of different size (`[ 1, 480, 640, 3]`. Because of this shape incompatibility it is throwing an error at this line
> `interpreter.set_tensor(input_details[0]['index'], input_data)`
> 
> I am not sure why the output always is [0 1. 0 0 0]. Any Idea @karimnosseir . Thanks!

@jvishnuvardhan thanks for checking. Can you please try to run this code:

```
import numpy as np
from tensorflow import keras
from PIL import Image
from numpy import asarray
import glob

model_path = 'mymodel.h5'
datadir = '/datapath/'

# load model
model = keras.models.load_model(model_path)
print('model loaded!')

fnames = glob.glob(datadir+'*.jpg')

i=0
for fn in fnames:
    path = fn
    print(path)
    img = Image.open(path)
    print(img.size)

    x = asarray(img)
    print(x.shape)

    x = np.expand_dims(x, axis=0)
    print(x.shape)

    pred = model.predict(x)
    print(i,pred)
    i = i + 1
```
In this case (the original h5 model), I do not need to transpose the np array to match the (640, 480, 3) as you did in the gist (and I did when I got [0, 1., 0, 0, 0] as well). In this version, the model runs and predicts correctly. This is the output:

```
/frames738.jpg
(640, 480)
(480, 640, 3)
(1, 480, 640, 3)
0 [[0. 1. 0. 0. 0.]]
1
/frames794.jpg
(640, 480)
(480, 640, 3)
(1, 480, 640, 3)
1 [[1. 0. 0. 0. 0.]]
2
/frames650.jpg
(640, 480)
(480, 640, 3)
(1, 480, 640, 3)
2 [[0. 1. 0. 0. 0.]]

...

/frames791.jpg
(640, 480)
(480, 640, 3)
(1, 480, 640, 3)
21 [[0. 0. 0. 0. 1.]]
22

```
Maybe the predict() function takes into account the image vs array dimension convention in keras but not when I use an interpreter from tflite_runtime?

**Comment by edgarbc** [comment]
Hi there, just wondering if you have further suggestions about how to solve this problem?
