### ISSUE TITLE
[Question] Adding More Outputs in tflite Interpreter.get_output_details()

### ISSUE THREAD

**Issue by Rocksus** [tensorflow/tensorflow#44910]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10, Python 3.7.7, 
- TensorFlow installed from (source or binary):
Source
- TensorFlow version (or github SHA if from source):
Tensorflow 2.3.0-rc0

Hello, this is more of a question rather than an issue report.
I am trying to convert a yolov4 model into a tflite to no avail.

After reading through:
- https://www.tensorflow.org/lite/convert
- https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter
- https://www.tensorflow.org/lite/inference_with_metadata/lite_support
- https://www.tensorflow.org/api_docs/python/tf/lite/Interpreter

I am unable to find any details regarding appending data in the `interpreter.get_output_details()`.
There are guides that require more than 1 output details, [here's an example](https://github.com/vardanagarwal/Proctoring-AI/blob/master/coco%20models/tflite%20mobnetv1%20ssd/seg_tflite.py#L64-L69); which then can be translated into bbox, classes, scores, and number of detections respectively.

Are there any documentations that can give me a lead on this question?

**Comment by jvishnuvardhan** [comment]
@Rocksus Are you looking for some guides on TF lite converter to convert object detection model? [Here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md) is the guide you can use. Thanks!
