### ISSUE TITLE
Inconsistent code logic for Model.build

### ISSUE THREAD

**Issue by zicofish** [tensorflow/tensorflow#44931]
In this function [`Model.build`](https://github.com/tensorflow/tensorflow/blob/b858de3779cab56d9788b0e87ff437d5dffbd942/tensorflow/python/keras/engine/training.py#L324), the code logic seems buggy. It says that it does not accept `dict` as the type of `input_shape`, and reject the `dict` type [here](https://github.com/tensorflow/tensorflow/blob/b858de3779cab56d9788b0e87ff437d5dffbd942/tensorflow/python/keras/engine/training.py#L359).

But then it has [further code](https://github.com/tensorflow/tensorflow/blob/fcc4b966f1265f466e82617020af93670141b009/tensorflow/python/keras/engine/training.py#L397) to check for the `dict` type, which makes me wonder that the purpose is to actually allow the usage of `dict` type...

I post this issue because I want to use `dict` type for the `input_shape` in my project. Right now, I have to override this function in my subclassed model and transform `dict` to `list` in a hard-coded order.

**Comment by bhack** [comment]
>  It says that it does not accept dict as the type of input_shape, and reject the dict type here.

It seems to me that `dict` is in `valid_types`
https://github.com/tensorflow/tensorflow/blob/d02bdf70273341cb41adc6f6f177b045dca1e470/tensorflow/python/keras/engine/training.py#L358-L359

**Comment by zicofish** [comment]
Sorry, as @bhack pointed out, the problem has been fixed in the newest version.
I actually encountered this problem in version 2.3.0 here:

https://github.com/tensorflow/tensorflow/blob/5681c179eff80bce00e526303950b67b23cad14c/tensorflow/python/keras/engine/training.py#L377-L378
