### ISSUE TITLE
Tensorflow Bazel build error

### ISSUE THREAD

**Issue by KjerG** [tensorflow/tensorflow#4493]
Hello,

I was pointed here from StackOverflow, hopefully I am in the right place.

I have been trying to setup tensorflow on my Raspberry Pi 3B using the guide [here](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/GUIDE.md). However I run into an error when executing the command:

`bazel build -c opt --copt="-mfpu=neon" --local_resources 1024,1.0,1.0 --verbose_failures tensorflow/tools/pip_package:build_pip_package`

Below is the error:

```
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: /home/pi/makevoicedemo/tf/tensorflow/tensorflow/tensorflow.bzl:571:26: Traceback (most recent call last):
        File "/home/pi/makevoicedemo/tf/tensorflow/tensorflow/tensorflow.bzl", line 565
                rule(attrs = {"srcs": attr.label_list..."), <3 more arguments>)}, <2 more arguments>)
        File "/home/pi/makevoicedemo/tf/tensorflow/tensorflow/tensorflow.bzl", line 571, in rule
                attr.label_list(cfg = "data", allow_files = True)
expected ConfigurationTransition or NoneType for 'cfg' while calling label_list but got string instead: data.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file 'tensorflow/tensorflow.bzl' has errors.
INFO: Elapsed time: 0.337s
```
I was told that this is possibly due to a bug.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
Error report #4319 however the thread seemed to stray from the original topic and I wasn't able to pick out if a fix had been found for the initial issue.  

### Environment info
Operating System:
Raspbian Jessie

Installed version of CUDA and cuDNN: 
N/A
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
`ls: cannot access /path/to/cuda/lib/libcud*: No such file or directory`

Commit hash (`git rev-parse HEAD`):
7df9c6860e00b91eda0e550b11d9be52d9341d85

Output of `bazel version`:
```
Build label: 0.2.1-2016-09-15 (@e7a95e5)
Build target: bazel-out/local_linux-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Sep 16 00:46:39 2016 (1473986799)
Build timestamp: 1473986799
Build timestamp as int: 1473986799

```

### What other attempted solutions have you tried?
Attempted to install from pip, both attempts (python 2.7, and 3.3+) failed.

**Comment by caisq** [comment]
Just to cover the basics. Did you run "./configure" before running "bazel build..."?

**Comment by KjerG** [comment]
Yes, I had to cancel the first time because I entered the wrong file path, I did run `./configure` using the default file paths and with "Google Cloud Platform" and GPU support disabled.

**Comment by vrv** [comment]
Try upgrading bazel to 0.3.1 ?

I wish I knew why https://github.com/tensorflow/tensorflow/blob/master/WORKSPACE#L23 is no longer working...

**Comment by KjerG** [comment]
I used `git checkout 0.2.1` to get bazel, should I upgrade using `git checkout 0.3.1` or is there a different method you'd recommend. 

Using `git checkout 0.3.1` gives me:
```
 error: Your local changes to the following files would be overwritten by checkout:
        scripts/bootstrap/compile.sh
Please, commit your changes or stash them before you can switch branches.
Aborting

```

**Comment by vrv** [comment]
I would check out bazel.io or github.com/bazelbuild/bazelbuild for upgrading

**Comment by ic** [comment]
Related to #4531

**Comment by ic** [comment]
I have just tried with both Bazel @0.3.1 and the present master. Both lead to the same errors reported by @KjerG, trying to build Tensorflow on the present master, too.

Interestingly, building 95ddc4e (just before the possibly breaking 7bcdcbbf) seems to work (I just need to build `//tensorflow/cc:cc_ops`, though).

**Comment by tomrunia** [comment]
I had the same error after trying to `./configure` the latest master. After upgrading Bazel it works again.

**Comment by KjerG** [comment]
Sorry for taking so long to respond, I haven't had access to my project for a bit so I had no way of testing.

Anyway, upgrading to 0.3.1 (`git checkout 0.3.1`) and running `./compile.sh` leaves me with: 
`gRPC Java plugin not found in`
followed by nothing (I know there's supposed to be an error message here usually).

As said, I haven't touched the system since the last post so Java should still be where I left it. I'll try to fix this and see if upgrading to 0.3.1 helped.

**Comment by ic** [comment]
You are not missing Java, but the gRPC plugin. It may also be that your are trying to build on a broken commit.

**Comment by aselle** [comment]
@KjerG, Closing due to lack of recent activity. Please reopen when additional information becomes available.

**Comment by KjerG** [comment]
I am attempting a clean install using the guide [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile#raspberry-pi) in the hopes of circumventing this issue. 

I have kept my old Tensorflow build as an (inactive) backup. If I make any more headway on this issue I will post it here.
