### ISSUE TITLE
ValueError: Shapes (None, 1) and (None, 10) are incompatible

### ISSUE THREAD

**Issue by connect2robiul** [tensorflow/tensorflow#44946]
I have 40 rows and 15000 columns 
EEG data with attaching lebel  
```
Epoch 1/10
WARNING:tensorflow:Layer dense_2 is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because its dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-33-601f7224d647> in <module>()
----> 1 model.fit(X_train, y_train, epochs=10, batch_size=32)

10 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    971           except Exception as e:  # pylint:disable=broad-except
    972             if hasattr(e, "ag_error_metadata"):
--> 973               raise e.ag_error_metadata.to_exception(e)
    974             else:
    975               raise

ValueError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:806 train_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:789 run_step  **
        outputs = model.train_step(data)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:749 train_step
        y, y_pred, sample_weight, regularization_losses=self.losses)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/compile_utils.py:204 __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/losses.py:149 __call__
        losses = ag_call(y_true, y_pred)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/losses.py:253 call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/losses.py:1535 categorical_crossentropy
        return K.categorical_crossentropy(y_true, y_pred, from_logits=from_logits)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py:4687 categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py:1134 assert_is_compatible_with
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))

    ValueError: Shapes (None, 1) and (None, 10) are incompatible
```

**Comment by ravikyram** [comment]
@connect2robiul 

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by connect2robiul** [comment]
> @connect2robiul
> 
> Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
> 
> Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

https://colab.research.google.com/drive/1nLY9ucV9UV6Avp7k4obKaGRZL21i7wLI?usp=sharing

**Comment by ravikyram** [comment]
@connect2robiul 

Can you help us with sample data to reproduce the issue in our environment.Which TF version you are using?
Thanks!

**Comment by connect2robiul** [comment]
> @connect2robiul
> 
> Can you help us with sample data to reproduce the issue in our environment.Which TF version you are using?
> Thanks!

I can not share my dataset. I am using default colab TF which is 2.3.0

**Comment by ymodak** [comment]
I see you are using `tf.data.Dataset.from_tensor_slices()` to convert the `pandas.Dataframe` into a `tf.data` dataset which is the correct approach. 
https://www.tensorflow.org/tutorials/load_data/pandas_dataframe
`model.fit` accepts input data types such as numpy array, tensor or tf dataset.

**Comment by connect2robiul** [comment]
> Looks like you were successful in finding a workaround for this.
> I see you are using `tf.data.Dataset.from_tensor_slices()` to convert the `pandas.Dataframe` into a `tf.data` dataset which is the correct approach.
> https://www.tensorflow.org/tutorials/load_data/pandas_dataframe
> `model.fit` accepts input data types such as numpy array, tensor or tf dataset.

same error through I change to to `model.fit(X_train.to_numpy(), y_train.to_numpy(), epochs=10, batch_size=32)`

**Comment by bhack** [comment]
@connect2robiul Can you share a minimal example to reproduce this with minimal dummy data?

**Comment by connect2robiul** [comment]
> @connect2robiul Can you share a minimal example to reproduce this with minimal dummy data?

I got a different error on the same line; code link <<https://colab.research.google.com/drive/1UAiDGFQ14EhEzYDnb7yIsJPD0SVL58Rn?usp=sharing>>
And it's editable

**Comment by connect2robiul** [comment]
> @connect2robiul
> 
> Can you help us with sample data to reproduce the issue in our environment.Which TF version you are using?
> Thanks!

I got a different error on the same line; code link <https://colab.research.google.com/drive/1UAiDGFQ14EhEzYDnb7yIsJPD0SVL58Rn?usp=sharing>
And it's editable

**Comment by ymodak** [comment]
The colab you shared is different from the previously shared where we were dealing with csv data frame and converting it into `tf.data.Datasets`.
However in the current colab we may want to change `loss=binary_crossentropy` since the label is in binary and set correct input data and target shapes.

**Comment by connect2robiul** [comment]
> The colab you shared is different from the previously shared where we were dealing with csv data frame and converting it into `tf.data.Datasets`.
> However in the current colab we may want to change `loss=binary_crossentropy` since the label is in binary and set correct input data (47, 120000) and target data (47,) shapes.

I run the same code here `https://colab.research.google.com/drive/1pYOmiNKCOA4LkIr2MbQlqfHbyvvcWb-U?usp=sharing`. But still has an error on the fit function

**Comment by bhack** [comment]
> > The colab you shared is different from the previously shared where we were dealing with csv data frame and converting it into `tf.data.Datasets`.
> > However in the current colab we may want to change `loss=binary_crossentropy` since the label is in binary and set correct input data (47, 120000) and target data (47,) shapes.
> 
> I run the same code here < [https://colab.research.google.com/drive/1pYOmiNKCOA4LkIr2MbQlqfHbyvvcWb-U?usp=sharing>](https://colab.research.google.com/drive/1pYOmiNKCOA4LkIr2MbQlqfHbyvvcWb-U?usp=sharing%3E). But still has an error on the fit function

For your last colab example:
```
model.add(Dense(11, activation='softmax'))
```
