### ISSUE TITLE
TF 2.3.1. Custom Metrics are not shown

### ISSUE THREAD

**Issue by jonyvp** [tensorflow/tensorflow#44940]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary):Docker tag 2.3.1
- TensorFlow version (use command below): 2.3.1
- Python version: 3.7
- Bazel version (if compiling from source):x
- GCC/Compiler version (if compiling from source):x
- CUDA/cuDNN version:
- GPU model and memory: K80

**Describe the current behavior**
I used to be able _(TF 2.0.0)_ to log custom metrics using a Callback, putting the calculated logs into the `logs` variable. Now _(using TF 2.3.1)_ it seems these are not displayed anymore. Is this adjusted? It seems all that is visualized now is: 
```
I 2020-11-17T12:47:08.315319004Z master-replica-0 Epoch 1/150
 master-replica-0 
I 2020-11-17T12:47:08.315363796Z master-replica-0 160/160 - 532s - loss: 29.2287 - val_loss: 15.1582
 master-replica-0 
I 2020-11-17T12:55:48.016732616Z master-replica-0 Epoch 2/150
 master-replica-0 
I 2020-11-17T12:55:48.016795954Z master-replica-0 160/160 - 519s - loss: 10.9081 - val_loss: 18.8457
 master-replica-0 
I 2020-11-17T13:04:21.477356137Z master-replica-0 Epoch 3/150
 master-replica-0 
I 2020-11-17T13:04:21.477408088Z master-replica-0 160/160 - 513s - loss: 9.3685 - val_loss: 8.4681
 master-replica-0 
I 2020-11-17T13:12:53.997353683Z master-replica-0 Epoch 4/150
 master-replica-0 
I 2020-11-17T13:12:53.997419829Z master-replica-0 160/160 - 512s - loss: 10.4035 - val_loss: 8.9458
 master-replica-0 
I 2020-11-17T13:21:18.459229170Z master-replica-0 Epoch 5/150
 master-replica-0 
I 2020-11-17T13:21:18.459279180Z master-replica-0 160/160 - 504s - loss: 9.8809 - val_loss: 9.3682
 master-replica-0 
I 2020-11-17T13:29:43.330040354Z master-replica-0 Epoch 6/150
 master-replica-0 
I 2020-11-17T13:29:43.330108120Z master-replica-0 160/160 - 504s - loss: 9.5458 - val_loss: 8.8212
 master-replica-0 
```

**Comment by bhack** [comment]
Can you share a very minimal code example to reproduce this?

**Comment by jonyvp** [comment]
https://colab.research.google.com/drive/1lUCnZrgUzH77okiyDNdNkHRMU1pYkMNf?usp=sharing

iirc, this should yield the result:
```
4/4 [==============================] - 0s 22ms/step - loss: 232.9125 - val_loss: 7.3053 - test_val: 0.8
```

**Comment by bhack** [comment]
In your colab ` 'metric' is not defined`

**Comment by jonyvp** [comment]
Adjusted

**Comment by bhack** [comment]
Is this like https://github.com/tensorflow/tensorflow/issues/37187?

**Comment by jonyvp** [comment]
It seems so. I know that it has worked for me in the past.

**Comment by bhack** [comment]
I think you can close this, upvote and subscribe to that one

**Comment by jonyvp** [comment]
Duplicate of #37187
