### ISSUE TITLE
tflite_runtime got installed successfully, however getting error while importing interpreter.

### ISSUE THREAD

**Issue by Neel1994** [tensorflow/tensorflow#44944]
Environment:
Python 3.7
armv7l (ARM 32).
tflite_runtime (installed version) : 2.5.0

Issues:

Steps followed:
1. Followed steps from Python Quickstart document available on tensorflow site , below is the document.
      https://www.tensorflow.org/lite/guide/python

2. it was stated in the above document To quickly run TensorFlow Lite models with Python, you can install just the TensorFlow Lite interpreter, instead of all TensorFlow packages.

3. So I didn't install the whole tensorflow package , indeed just installed the wheel available for my armv7l (ARM 32) machine having Python 3.7.

Steps to reproduce the issue:

1. Have ARM 32 (armv7l) system with Python 3.7.
2. pip3 install --install-option="/mnt/persistent_data/tfinter" tflite_runtime-2.5.0-cp37-cp37m-linux_armv7l.whl
3. wheel package installed: https://github.com/google-coral/pycoral/releases/download/release-frogfish/tflite_runtime-2.5.0-cp37-cp37m-linux_armv7l.whl
3. Install tflite_rutime only (not the whole tensorflow) using above command.
4. tflite_runtime got installed correctly (no error while installation).
5. tflute_runtime version 2.5.0.

Expected Behaviour:

import tflite_runtime.interpreter as tflite
Above command should get executed without error.

Error:
However trying to import  tflite_runtime.interpreter returns following error:

>>> import tflite_runtime.interpreter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 36, in <module>
    from tflite_runtime import _pywrap_tensorflow_interpreter_wrapper as _interpreter_wrapper
ImportError: cannot import name '_pywrap_tensorflow_interpreter_wrapper' from 'tflite_runtime' (/usr/lib/python3.7/site-packages/tflite_runtime/__init__.py).

Note:
Doing ls in installed tflite_runtime folder returns following files:

[nilesh_kumar@localhost tflite_runtime]$ ls
__init__.py
__pycache
interpreter.py
_pywrap_tensorflow_interpreter_wrapper.cpython-37m-arm-linux-gnueabihf.so

**Comment by Saduf2019** [comment]
@Neel1994 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

**Comment by Neel1994** [comment]
> @Neel1994
> We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

Hi @Saduf2019 have updated the issue as per your requirement.

**Comment by Neel1994** [comment]
**Hi @Saduf2019 , still giving the same error.**

>>> from tflite_runtime.interpreter import Interpreter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 36, in <module>
    from tflite_runtime import _pywrap_tensorflow_interpreter_wrapper as _interpreter_wrapper
ImportError: cannot import name '_pywrap_tensorflow_interpreter_wrapper' from 'tflite_runtime' (/usr/lib/python3.7/site-packages/tflite_runtime/__init__.py)

Went through the chats and tried executing all posible commands still same error.

**Comment by jvishnuvardhan** [comment]
@Neel1994 Did you use correct wheel for the platform? I didn't dace any issues when I tried with Mac OS and Windows when I used correct wheels for my python and platform. Thanks!

**Comment by Neel1994** [comment]
@jvishnuvardhan , Yes I used the correct wheel my system is ARM32 (armv7l) and python version 3.7
It is a linux distrib and not Mac/Windows.
**Additional System details:**
Operating System: **Poky (Yocto Project Reference Distro) 3.0.1 (zeus)**
Kernel: **Linux 4.19.112.idrac**
Architecture: **arm**
model name      : **ARMv7 Processor rev 1 (v7l)**
Hardware        : NPCM7XX Chip family

/home/root# python3
Python 3.7.5 (default, Nov 17 2020, 09:50:47)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import tflite_runtime
>>> from tflite_runtime.interpreter import Interpreter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 36, in <module>
    from tflite_runtime import _pywrap_tensorflow_interpreter_wrapper as _interpreter_wrapper
ImportError: cannot import name '_pywrap_tensorflow_interpreter_wrapper' from 'tflite_runtime' (/usr/lib/python3.7/site-packages/tflite_runtime/__init__.py)

You can see above tflite_runtime is imported successfully, however importing Interpreter is throwing error.

Wheel used for install: https://github.com/google-coral/pycoral/releases/download/release-frogfish/tflite_runtime-2.5.0-cp37-cp37m-linux_armv7l.whl

Above is the correct wheel as trying to install with any other wheel throws (platform not compatible) error while installation.

**Comment by terryheo** [comment]
The PIP package was generated with arm-linux-gnueabihf-gcc toolchain. I guess your system has an ABI compatibility issue with it. If you have a cross compilation toolchain for your target, you'd better generate PIP package by yourself.

You might want to modify this
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/pip_package/setup.py#L55
and use the following document.
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package

**Comment by GarimaSarangal** [comment]
@Neel1994 - Was it solved? I am facing exact issue in Linux.

**Comment by iitaakash** [comment]
I solved this error by installing the tflite_tuntime 2.4 from [here ](https://github.com/iCorv/tflite-runtime). I installed the required pybind dependency from [here](https://pypi.org/project/pybind11/#files).
