### ISSUE TITLE
UnrecognizedFlagError: Unknown command line flag 'pdb_post_mortem'

### ISSUE THREAD

**Issue by wanzhixiao** [tensorflow/tensorflow#44943]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): https://pypi.tuna.tsinghua.edu.cn
- TensorFlow version (use command below):1.14.0
- Python version: 3.7.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:CUDA 10.0,cuDNN
- GPU model and memory: 6GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
i successfully installed tensorflow-gpu==1.14.0,when i import tensorflow as tf, raise the flowing exception,how can i sovle it?
my cuda version si 10.0, and cudnn  is cudnn64_7.dll

import tensorflow as tf
D:\ProgramFile\python\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\ProgramFile\python\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\ProgramFile\python\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\ProgramFile\python\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\ProgramFile\python\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\ProgramFile\python\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\ProgramFile\python\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "D:\ProgramFile\python\lib\site-packages\tensorflow\python\__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "D:\ProgramFile\python\lib\site-packages\tensorflow\python\framework\framework_lib.py", line 25, in <module>
    from tensorflow.python.framework.ops import Graph
  File "D:\ProgramFile\python\lib\site-packages\tensorflow\python\framework\ops.py", line 54, in <module>
    from tensorflow.python.platform import app
  File "D:\ProgramFile\python\lib\site-packages\tensorflow\python\platform\app.py", line 23, in <module>
    from absl.app import run as _run
  File "D:\ProgramFile\python\lib\site-packages\absl\app.py", line 54, in <module>
    flags.DEFINE_alias('pdb', 'pdb_post_mortem')
  File "D:\ProgramFile\python\lib\site-packages\absl\flags\_defines.py", line 754, in DEFINE_alias
    raise _exceptions.UnrecognizedFlagError(original_name)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'pdb_post_mortem'

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by bhack** [comment]
Honestly I don't think there will enough bandwidth here to support `1.14.0` tickets.

Can you try to use an updated TF version?

**Comment by wanzhixiao** [comment]
Thank you. No error was reported after upgrading to TF 2.0

**Comment by wanzhixiao** [comment]
> Honestly I don't think there will enough bandwidth here to support `1.14.0` tickets.
> 
> Can you try to use an updated TF version?
