### ISSUE TITLE
GeForce 3090 incompatibility with Nightly

### ISSUE THREAD

**Issue by 3DTOPO** [tensorflow/tensorflow#44959]
**System information**
- Using a stock example script provided in TensorFlow
- Linux Ubuntu 18.04
- TensorFlow installed from Nightly
- TensorFlow version v1.12.1-45908-g9af48cb079
- Python version 3.8
- CUDA 11.1 cuDNN 8.0.5.39
- GeForce RTX 3090 with 24265MiB

**Describe the current behavior**
Training does not run on the GPU, shows "warning":

`Your CUDA software stack is old. We fallback to the NVIDIA driver for some compilation. Update your CUDA version to get the best performance. The ptxas error was: ptxas fatal   : Value 'sm_86' is not defined for option 'gpu-name'`

**Describe the expected behavior**
Training should run on the GPU

**Standalone code to reproduce the issue**
Install GeForce 3090 then install nightly GPU:

```
conda create -n tf-n-gpu python=3.8
conda activate tf-n-gpu
pip install tf-nightly-gpu
pip install matplotlib
pip install IPython
```

Run:
https://www.tensorflow.org/tutorials/generative/pix2pix

**Comment by bhack** [comment]
We don't officially support conda here.

**Comment by 3DTOPO** [comment]
I thought that was the recommend method of installation.

What installation method is supported then?

**Comment by bhack** [comment]
https://www.tensorflow.org/install/pip

**Comment by Harsh188** [comment]
I'm having the same issue.
**System Info**
- RTX 3080
- Linux Ubuntu 20.04
- tensorflow 2.4.0rc1-gpu (Docker Image)

**Comment by amahendrakar** [comment]
@Harsh188,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by Harsh188** [comment]
Upgrading to tensorflow==2.4.0rc2 fixed this issue for me.

**Comment by amahendrakar** [comment]
@3DTOPO,
Any updates regarding this? Please feel free to close the issue if resolved. Thanks!

**Comment by 3DTOPO** [comment]
Sorry I haven't had time to go back and check. Looks like rc2 may address it so I will try that soon and report back.

**Comment by yhzq** [comment]
I have the same problem. 
RTX 3090
tensorflow-gpu 2.4.0rc3
cuda 11.1.105 (tried 11.0, same error)
cudnn 8.0.5.39
It showed `Your CUDA software stack is old. We fallback to the NVIDIA driver for some compilation. Update your CUDA version to get the best performance. The ptxas error was: ptxas fatal   : Value 'sm_86' is not defined for option 'gpu-name'` for a few hundred times and started training. The training seemed fine though.

**Comment by Harsh188** [comment]
I followed the directions in this article: [Install TensorFlow & PyTorch for the RTX 3090, 3080, 3070](https://lambdalabs.com/blog/install-tensorflow-and-pytorch-on-rtx-30-series/). So far it works pretty well and allows me to utilize my 3080 with TF 2.3.

**Comment by crutcher** [comment]
This is still a problem

**Comment by ChethanM-18** [comment]
I have the same problem.
RTX 3080
Ubuntu 18.04
tensorflow-gpu 2.4.0(official release)
cuda 11.0
cudnn 8.0.4.30
Have use the same packages mention by tensorflow [link](https://www.tensorflow.org/install/gpu#ubuntu_1804_cuda_110)
It showed Your CUDA software stack is old. We fallback to the NVIDIA driver for some compilation. Update your CUDA version to get the best performance. The ptxas error was: ptxas fatal : Value 'sm_86' is not defined for option 'gpu-name' for a few hundred times and started training. The training seemed fine though.

**Comment by mattlyon93** [comment]
This is still an issue for me.
RTX 3080
Ubuntu 20.04
NVIDIA driver 455.38
tensorflow-gpu 2.4.0
Tried with both cuda 11.0 and 11.1
cudnn 8.0.4.30

**Comment by bayesrule** [comment]
Same here,
GTX 3090 
TF 2.4.0
CUDA 11.0
cudnn 8.0.4

**Comment by albert-92** [comment]
Yeah also the same here.
GTX 3090
tensorflow/tensorflow:2.4.0-gpu docker image

**Comment by albert-92** [comment]
> Yeah also the same here.
> GTX 3090
> tensorflow/tensorflow:2.4.0-gpu docker image

It works with the latest nightly-gpu docker image (https://hub.docker.com/layers/tensorflow/tensorflow/nightly-gpu/images/sha256-f9c8333811c5426be605352f307d665a089343cd699e0b49da128dbde18008ad?context=explore) though.

**Comment by Doev** [comment]
I got the same error many times while running the notebook. But finally the training is running on the gpu:

I additional put this code at the beginning of the notebook:

```
import tensorflow as tf
gpu = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(gpu[0], True) #limits gpu memory

```
see: https://github.com/tensorflow/tensorflow/issues/45635#event-4131192988

GPU: RTX 3060 TI
Ubuntu-Server-20.04
Driver Version: 455.45.01
cuda_11.0.3_450.51.06
cudnn-11.0-linux-x64-v8.0.2.39
Tensorflow: 2.4.0

**Comment by drahmad89** [comment]
I am having the same issue and non of the above solutions worked for me

**Comment by amahendrakar** [comment]
@drahmad89,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
