### ISSUE TITLE
How does classifier predict a class?

### ISSUE THREAD

**Issue by tu1258** [tensorflow/tensorflow#44953]
I want to implement the model by myself and thus have to know how does it classify the data. I build a model for 12-class classifier and it predicts fine. But the last conv layer just outputs 12 floating point value and I don't know how it suddenly predicts the right class. Can someone explain for me? Like is it depend on some threshold or it chooses the max value or something? Thanks!

PS. I've searched in STACKOVERFLOW before but couldn't get any information. I've tried to choose the index with max value but it seemed that model just predicts randomly. So I guess it doesn't work like that. 

**The model**

> first_conv (Conv2D)          (None, 63, 1, 24)         984       
> _________________________________________________________________
> first_act (Activation)       (None, 63, 1, 24)         0         
> _________________________________________________________________
> dw0 (DepthwiseConv2D)        (None, 61, 1, 24)         96        
> _________________________________________________________________
> pw0 (Conv2D)                 (None, 61, 1, 24)         600       
> _________________________________________________________________
> act0 (Activation)            (None, 61, 1, 24)         0         
> _________________________________________________________________
> dw1 (DepthwiseConv2D)        (None, 59, 1, 24)         96        
> _________________________________________________________________
> pw1 (Conv2D)                 (None, 59, 1, 24)         600       
> _________________________________________________________________
> act1 (Activation)            (None, 59, 1, 24)         0         
> _________________________________________________________________
> dw2 (DepthwiseConv2D)        (None, 57, 1, 24)         96        
> _________________________________________________________________
> pw2 (Conv2D)                 (None, 57, 1, 24)         600       
> _________________________________________________________________
> act2 (Activation)            (None, 57, 1, 24)         0         
> _________________________________________________________________
> dw3 (DepthwiseConv2D)        (None, 55, 1, 24)         96        
> _________________________________________________________________
> pw3 (Conv2D)                 (None, 55, 1, 24)         600       
> _________________________________________________________________
> act3 (Activation)            (None, 55, 1, 24)         0         
> _________________________________________________________________
> pool (AveragePooling2D)      (None, 1, 1, 24)          0         
> _________________________________________________________________
> last_conv (Conv2D)           (None, 1, 1, 12)          300       
> _________________________________________________________________
> tf_op_layer_reshape_3 (Tenso [(None, 12)]              0

**Comment by bhack** [comment]
>  I've searched in STACKOVERFLOW before but couldn't get any information. 

This is a support request so please open a new StackOverflow question.

**Comment by tu1258** [comment]
I will post on stackoverflow at the same time. Thanks for suggestion.
