### ISSUE TITLE
Issue with tf.math.conj function

### ISSUE THREAD

**Issue by azhan137** [tensorflow/tensorflow#44952]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0 (also tried on 2.3.1)
- Python version: 3.7.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.1 / 7.6.5
- GPU model and memory: RTX2060 8GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I have been having problems with the tensorflow function tensorflow.math.conj, which is supposed to return the complex conjugate (1+1j -> 1-1j) of a tensor. The error that occurs is the following:

tensorflow/stream_executor/cuda/cuda_driver.cc:939] could not synchronize on CUDA context: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure :: 0x00007FFF94A28E85 tensorflow::CurrentStackTrace

However, it seems that tf.math.real and tf.math.imag work as expected.

**Describe the expected behavior**
I expect the function to output the the complex conjugate (1+1j -> 1-1j).

**Standalone code to reproduce the issue**
`import tensorflow as tf
a = tf.constant(1+1.j, dtype=tf.complex64)
b = tf.math.conj(a)'

**Other info / logs** Include any logs or source code that would be helpful to
I am able to perform every other tensorflow operation that I've tried, it's really only this issue that is giving me problems...

**Comment by bhack** [comment]
I can't reproduce this on Colab with TF 2.3.1. Can you try on your system with TF 2.3.1?

**Comment by azhan137** [comment]
hm this must be an issue with the way I installed TF on windows then...

**Comment by ravikyram** [comment]
@azhan137 
I have tried in colab with TF 2.3, nightly version(`2.5.0-dev20201117 `) and i am not seeing any issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/403a23a7985925249f82c5f63437e4ed/untitled522.ipynb). Thanks!
