### ISSUE TITLE
Why is the first inference Extremely Slow?

### ISSUE THREAD

**Issue by golden0080** [tensorflow/tensorflow#44967]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
YES, as custom ops in the network.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No.
- TensorFlow installed from (source or binary): Source, 2.3.1
- TensorFlow version (use command below): 2.3.1
- Python version: 3.5
- Bazel version (if compiling from source): Bazel 3.1
- GCC/Compiler version (if compiling from source): 7
- CUDA/cuDNN version: 10.2
- GPU model and memory: 2080 Ti

**Describe the current behavior**

So I'm using Tensorflow C++ APIs to do inference using `CallableHandle` with `Session`.
I used `RunMetadata` to dump the full trace for the first inference in C++. Part of the timeline showed in Chrome://tracing

I ran this model freezed using TF 1.15, and it ran in TF 2.3 without obvious issues.

![Screenshot from 2020-11-17 22-03-05](https://user-images.githubusercontent.com/2466188/99491865-65973500-2921-11eb-8f8e-533c12b1fa7d.png)

As you could see, every convolution layer here took EXTREMELY long to do, and it's showing they are also running on GPU.
After couple of inferences, the inference time for the model is super short. So this makes me wonder what's happening in the first inference.

**Describe the expected behavior**

I know the first inference is usually slower than following ones, but this is extremely slow compared to how long it usually take.
The first inference here took 200s, while it was expected to run around 0.1s.

As one more reference data point, the same model running with TF 1.15 inference stack, the first inference would take around 10s to finish. TF 2.3 seems to be super slow for the same model.

**Other info / logs**

RunMetadata dumped tracing json (had to change to txt suffix):
Truncated, only showing part of the entire timeline.
[github_2.3_profile.txt](https://github.com/tensorflow/tensorflow/files/5558191/github_2.3_profile.txt)

**Comment by ymodak** [comment]
@golden0080 Can you please attach a minimal code snippet to reproduce the behavior? Thanks!

**Comment by golden0080** [comment]
@ymodak Seems like this is exactly the issue in https://github.com/tensorflow/tensorflow/issues/40036 and I was able to resolve it after installing `ptxas`.
