### ISSUE TITLE
AttributeError: module 'tensorflow.keras.layers.experimental.preprocessing' has no attribute 'StringLookup'?

### ISSUE THREAD

**Issue by ibrahimLearning** [tensorflow/tensorflow#44963]
cannot import StringLookup?

Environment:
TF 2.1.0
keras 2.3.1
Windows 10

Is there any suggestion please?

**Comment by bhack** [comment]
Try TF 2.3.1

**Comment by ibrahimLearning** [comment]
> Try TF 2.3.1

what about keras version for TF 2.3.1?

**Comment by bhack** [comment]
Please see https://github.com/keras-team/keras/releases/tag/2.4.0

**Comment by xixilog** [comment]
fuck 2.3.1

**Comment by xixilog** [comment]
my cpu not suppot that!!!

**Comment by xixilog** [comment]
# Mapping characters to integers
def label_to_tensor(st):
    f_list = list(characters)
    f_list.sort()
    st_list = []
    for s in st:
        s_index = f_list.index(s)
        st_list.append(s_index)
    return tf.convert_to_tensor(st_list, dtype=tf.float32)

**Comment by xixilog** [comment]
for 
https://keras.io/examples/vision/captcha_ocr/

**Comment by ibrahimLearning** [comment]
I want to work at 1.x. (e.g., TF 1.4). How can I do that?
