### ISSUE TITLE
Avoid call to cuCtxSynchronize() when moving from graph execution to eager execution

### ISSUE THREAD

**Issue by pranavladkat** [tensorflow/tensorflow#44960]
Hi,

While running TF-2.x on nvidia gpu machine, tensorflow calls `cuCtxSynchronize()` API whenever programs enter eager execution. I.e. when program exits `@tf.function` code block. E.g. please take a look at code block [here](https://github.com/tensorflow/tensorflow/blob/642db2faf55e3ca7acd06ea236e9d47f63190718/tensorflow/stream_executor/cuda/cuda_gpu_executor.cc#L546-L548).

This essentially adds a device wide synchronization barrier and blocks until all gpu execution is complete even if some of the work is not related to TF library. I would like to use GPU to do some other work in parallel while TF is executing. Is there any way to achieve this without having to block TF due to this API call? If not, does it make sense to avoid device wide synchronization (which is bit hard restriction) and only synchronize on resources (such as cudaStream, etc.) created by TF?

**Comment by golden0080** [comment]
@pranavladkat I'm also curious if such behavior affects C++ inference. Do you happen to see slower inference in C++ or anywhere?

**Comment by ravikyram** [comment]
@pranavladkat 

Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
Request you to share simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by pranavladkat** [comment]
@golden0080 it does affect the overall performance since tf waits for cuda kernels not issued by it. 

@ravikyram sure, I'll create a small example which reproduces this issue and update it in a day or so. 

Thanks!

**Comment by golden0080** [comment]
I also tried to read some of the `gpu_executor` code, they now works with CUcontext and in 2.3.1's `GpuExecutor::Init`, every executor would create separate CUcontext.
But I'm still concerning about the synchronization in CUDA, since my upgrade from 1.15 to 2.3.1 comes with various performance issues.

**Comment by ravikyram** [comment]
@pranavladkat 

Any update on the issue please?
Thanks!

**Comment by pranavladkat** [comment]
@ravikyram sorry for the delay in response as I was away for past week. I spent some time to come up with a small example which reproduces this, however it seems it needs steep efforts to create such example since it requires custom cuda ops which simulates kernel execution in parallel to TF code.

What I'm looking for is to remove a call to `cuCtxSynchronize` API by tensorflow. Since this adds entire device wide synchronization which also impacts non-tf related code. E.g. please take a look at the snapshot of the nvidia profiler below. Here, tf is waiting for all kernels to be finished before continuing to next batch. The kernel being execute is running in parallel to tf code and is performing unrelated work. 

![image](https://user-images.githubusercontent.com/9426781/101099989-98286b00-357a-11eb-9a8f-510da1e13ace.png)

Please let me know if you would still need an example code to address this.

Thanks

**Comment by sanjoy** [comment]
Are you able to build TensorFlow locally?  If yes, can you check (by commenting it out) if [this](https://github.com/tensorflow/tensorflow/blob/50ea0bcb081f02d661964a0982f9b0024c55f3e0/tensorflow/core/common_runtime/executor.cc#L1306) is the source of the `cuCtxSynchronize` (this should be a `cudaStreamSynchronize` now).

We've been thinking of removing that sync point, but this is a tricky change and will take time.

**Comment by pranavladkat** [comment]
Hi Sanjoy,

Thanks for the response! I built tensorflow from source and commented out the lines from the code that you mentioned and I can confirm that the `cuCtxSynchronize` gets triggered from the same lines. After commenting out portion of the code, I do see expected behavior (overlapping cuda kernels) which I would like to have. E.g. please see the nvprof output of same section of the code below.

Is the `cuCtxSynchronize` has been replaced by `cudaStreamSynchronize` already in latest code or the change is pending so far? If it's not merged yet, do you have any estimates on how long will that could take?

Thanks,
Pranav

![tf_update1](https://user-images.githubusercontent.com/9426781/103822278-a3146680-5024-11eb-82c0-0f3598bcbb3a.png)

**Comment by sanjoy** [comment]
> Is the `cuCtxSynchronize` has been replaced by `cudaStreamSynchronize` already in latest code

Yes.

**Comment by pranavladkat** [comment]
That's Great! Then this resolves the issue which I raised. 

Thanks,
Pranav
