### ISSUE TITLE
What does TODO(b/XXX) mean?

### ISSUE THREAD

**Issue by tomfuture** [tensorflow/tensorflow#44964]
There are a lot of TODO comments in the code that include a reference to.... something.

Examples:
- https://github.com/tensorflow/tensorflow/blob/3061483034ce0196ca7ec0576668c41e5f4424c9/tensorflow/compiler/tests/BUILD#L81
- https://github.com/tensorflow/tensorflow/blob/0650101e05ef1ad56bfaadcd63ab775b25ecdd16/tensorflow/python/keras/saving/saved_model/metric_serialization.py#L44
- https://github.com/tensorflow/tensorflow/blob/1ba764b368daa5a6f34b556f2a44e2e222a18855/tensorflow/python/ops/risc/risc_grad.py#L27

What do these numbers mean?

**Comment by bhack** [comment]
https://stackoverflow.com/questions/49810177/what-does-b-xxxx-such-like-b-36865746-mean-in-tensorflow-code-comments

**Comment by tomfuture** [comment]
Got it, thank you!
