### ISSUE TITLE
What is the difference between two data generation methods？

### ISSUE THREAD

**Issue by lalalapotter** [tensorflow/tensorflow#44977]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14
- Python version: python3.6
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version: CUDA 10.2
- GPU model and memory: V100 32 GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I use two different methods to generate data in `input_fn` with `tf.estimator` API
~~~
def input_fn(batch_size, num_epochs):
    # Method1: generate one batch data and repeat
    #train_data = tf.truncated_normal((batch_size, 300, 150), 0.5, 0.1)
    #train_label = tf.random_uniform((batch_size,1),minval=0,maxval=1,dtype=tf.float32)
    #ds = tf.data.Dataset.from_tensors((train_data, train_label)).repeat(num_epochs)
    #Method2: generate data repeat then batch
    train_data = tf.truncated_normal([300, 150], 0.5, 0.1)
    train_label = tf.random_uniform([1],minval=0,maxval=1,dtype=tf.float32)
    ds = tf.data.Dataset.from_tensors((train_data, train_label)).repeat().batch(batch_size)
    ds = ds.prefetch(buffer_size=tf.contrib.data.AUTOTUNE)

    return ds
~~~
And I got two different performances. When I use Method1, the GPU utilization is not very stable, however, when I use Method2, the GPU utilization is very stable. Besides, when I use `tf.data.Dataset.from_tensors` API, the data generation time will be very long, however, if I use `tf.data.Dataset.from_tensor_slices` API, the generation time is very short.
**Describe the expected behavior**
I expect the performances should be same or similar when I use Methods 1 and 2. And it is also should be the same when I use different APIs `tf.data.Dataset.from_tensors` and `tf.data.Dataset.from_tensor_slices`.
**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@lalalapotter 

TF 1.14 is not actively supported. Please, switchover to latest stable TF version 2.3 and see if the issue still persists.There were lots of performance improvements in the latest versions

Request you to share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!
