### ISSUE TITLE
Error LNK2005 when linking in debug mode.

### ISSUE THREAD

**Issue by boussaffawalid** [tensorflow/tensorflow#44974]
**System information**
- OS Platform and Distribution : windows 10
- TensorFlow installed from: source and binary
- TensorFlow version: 2.3.0
- Python version: 3.7
- Installed using virtualenv: using c API
- Bazel version: 3.7.0
- GCC/Compiler version: msvc 2019
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the problem**
I have a c++ shared library that links both tensorflow and protobuf.
* In release everything works and as expected.
* In debug mode I got a linking issue:
```
libprotobufd.lib(common.obj) : error LNK2005: "public: __cdecl google::protobuf::internal::LogMessage::LogMessage(enum google::protobuf::LogLevel,char const *,int)" (??0LogMessage@internal@protobuf@google@@QEAA@W4LogLevel@23@PEBDH@Z) already defined in tensorflow.lib(tensorflow.dll)
```

I got this error when using precompiled binaries from: https://www.tensorflow.org/install/lang_c
I tried to compile tensorflow myself in both release and debug mode but still I get the same linking error.

**Any other info / logs**
```
00:23:39  libprotobufd.lib(common.obj) : error LNK2005: "public: __cdecl google::protobuf::internal::LogMessage::LogMessage(enum google::protobuf::LogLevel,char const *,int)" (??0LogMessage@internal@protobuf@google@@QEAA@W4LogLevel@23@PEBDH@Z) already defined in tensorflow.lib(tensorflow.dll)

00:23:39  libprotobufd.lib(common.obj) : error LNK2005: "public: __cdecl google::protobuf::internal::LogMessage::~LogMessage(void)" (??1LogMessage@internal@protobuf@google@@QEAA@XZ) already defined in tensorflow.lib(tensorflow.dll)

00:23:39  libprotobufd.lib(common.obj) : error LNK2005: "public: class google::protobuf::internal::LogMessage & __cdecl google::protobuf::internal::LogMessage::operator<<(char const *)" (??6LogMessage@internal@protobuf@google@@QEAAAEAV0123@PEBD@Z) already defined in tensorflow.lib(tensorflow.dll)

00:23:39  libprotobufd.lib(common.obj) : error LNK2005: "public: void __cdecl google::protobuf::internal::LogFinisher::operator=(class google::protobuf::internal::LogMessage &)" (??4LogFinisher@internal@protobuf@google@@QEAAXAEAVLogMessage@123@@Z) already defined in tensorflow.lib(tensorflow.dll)

00:23:39     Creating library lib\pmi_common_d.lib and object lib\pmi_common_d.exp
00:23:39  bin\pmi_common_d.dll : fatal error LNK1169: one or more multiply defined symbols found
```

**Comment by ymodak** [comment]
Did you try msvc docs on [linker error 2005](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2005?view=msvc-160) and [force file output](https://docs.microsoft.com/en-us/cpp/build/reference/force-force-file-output?view=msvc-160)?

**Comment by boussaffawalid** [comment]
Thanks!! That fixed the issue thanks. 
But still the multiple symbols are there, it is just the force flag ignore them. I'm wondering if there is a proper fix for this.
