### ISSUE TITLE
ValueError: Cannot feed value of shape (1, 384, 513, 3) for Tensor

### ISSUE THREAD

**Issue by sailokeshaithagoni** [tensorflow/tensorflow#44989]
I am new to tensorflow,
I have generated graph using colab.
For using the graph further, 
I am following this code snippet --[https://gist.github.com/averdones/b94e4eb335be356482f1bc1b7f7b15f3](url)

If I run this, I am getting following error:

**WARNING:tensorflow:From C:\Users\SRX9ZY1\.conda\envs\tf\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:88: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2020-11-18 19:31:03.098960: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Traceback (most recent call last):
  File "deeplab_demo_webcam_v2.py", line 171, in <module>
    resized_im, seg_map = model.run(pil_im)
  File "deeplab_demo_webcam_v2.py", line 152, in run
    feed_dict={self.INPUT_TENSOR_NAME: [np.asarray(resized_image)]})
  File "C:\Users\xxx\.conda\envs\tf\lib\site-packages\tensorflow_core\python\client\session.py", line 960, in run
    run_metadata_ptr)
  File "C:\Users\xxx\.conda\envs\tf\lib\site-packages\tensorflow_core\python\client\session.py", line 1159, in _run
    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 384, 513, 3) for Tensor 'train_step/Equal:0', which has shape '()'**

can't find fix to this!!!

Hope someone will help!!!

**Comment by amahendrakar** [comment]
@sailokeshaithagoni,
Please take a look at [this comment](https://stackoverflow.com/a/45966380) from a similar StackOverflow query and check if it works.

Also, this question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by sailokeshaithagoni** [comment]
Thanks for responding, 
Here is my stock overflow question link [https://stackoverflow.com/questions/64900628/valueerror-cannot-feed-value-of-shape-1-384-513-3-for-tensor](url)
