### ISSUE TITLE
Changing self properties does not trigger retracing

### ISSUE THREAD

**Issue by fachu000** [tensorflow/tensorflow#44980]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab and Mac
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0-dev20201118
- Python version: 3.6.9 (default, Oct  8 2020, 12:12:24) 

**Describe the current behavior**

Eager and graph mode give different results. This gives rise to bugs very difficult to detect: one just sees a different MSE when switching to graph mode!

**Describe the expected behavior**

Both eager and graph mode should give the same results or raise an error. If `tf.function` uses a variable through `self`, it should also be retraced using the same policy as with input arguments. Else, using properties of `self` should be disallowed in `tf.function`s.

**Standalone code to reproduce the issue**

Colab: [here](https://colab.research.google.com/drive/1SCcqXjBx8bivziz5592eW60UKTN9cWWX?usp=sharing).

````python

import tensorflow as tf

class Network:
    def call(self, x):
        self.weights = tf.zeros((4,5), dtype=tf.double)
        self.encoder_graph(x)
        self.weights = tf.zeros((2,3), dtype=tf.double)

        return (self.encoder_graph(x).shape == self.encoder_eager(x).shape)

    @tf.function
    def encoder_graph(self, x):
        return self.weights 
        
    def encoder_eager(self, x):
        return self.weights

N = Network()

tf.config.run_functions_eagerly(False)
print("Graph mode: ", N.call(tf.zeros((1,1))))
tf.config.run_functions_eagerly(True)
print("Eager mode: ", N.call(tf.zeros((1,1))))

````

**Other info / logs** 

Output:

````
Graph mode:  False
Eager mode:  True
````

**Comment by bhack** [comment]
> If you need to force retracing, create a new Function. Separate Function objects are guaranteed not to share traces.

**Comment by fachu000** [comment]
Thanks, but that does not solve the problem that the eager mode silently behaves differently from the graph mode.

**Comment by mdanatg** [comment]
I agree, this behavior is surprising, confusing and should be fixed. In general, it can be expensive to monitor all objects that the function may depend on. But `self` is a special type of object that should be treated specially.

Note that this isn't limited to `self`. Only the direct arguments are monitored, and everything else in the function's closure is ignored. For example:

```
x = tf.constant(1)

@tf.function
def f():
  return x

print(f())

x = tf.constant(2)

print(f())
```

```
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
```

Meanwhile, I recommend explicitly passing things as arguments as much as possible (so calling `self.encoder_graph(self.weights, x)`, is safer, as ugly as it looks).

Also note that this isn't a problem for `tf.Variable`s because those are changed using a TF op, rather than with a Python assignment (though they have other kinds of limitations):

```
x = tf.Variable(1)

@tf.function
def f():
  return x

print(f())

x.assign(2)

print(f())
```

```
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
```

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.4, nightly version(`2.5.0-dev20201118`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/5d41b5adc15e732d64b017bc8128b362/untitled523.ipynb). Thanks!

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210530, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/50e6ad46355e0ddd01594a6bbe1b94d1/44980.ipynb). Thanks!

**Comment by mohantym** [comment]
Hi @fachu000 ! I think the results will be the same if  eager execution is disabled or enabled during the process or by print both eager or graph mode values in the same block . Attaching [gist](https://colab.sandbox.google.com/gist/mohantym/814eb5bd340812636a13b87152db5d5d/44980.ipynb#scrollTo=2uGW9C6x2PTh) for reference. Thanks!
