### ISSUE TITLE
tf distributed mnist between graph sync example hang

### ISSUE THREAD

**Issue by guoying1030** [tensorflow/tensorflow#4499]
when i use distributed mnist between graph sync example hang

example code:
[distributed_between_sync.py.txt](https://github.com/tensorflow/tensorflow/files/484050/distributed_between_sync.py.txt)

who can tell me ,,why it hang???

use tensorflow 0.10 release version

1.start PS:
   nohup python distributed_between_sync.py --job_name="ps" --task_index=0 > ps_0.log &
  nohup python distributed_between_sync.py --job_name="ps" --task_index=1 > ps_1.log & 

2.start worker0:
  nohup python distributed_between_sync.py --job_name="worker" --task_index=0 --max_steps=10000 > worker_0.log &

3.start worker1:
  nohup python distributed_between_sync.py --job_name="worker" --task_index=1 --max_steps=10000 > worker_1.log &

worker log 
[worker_0.log.txt](https://github.com/tensorflow/tensorflow/files/484048/worker_0.log.txt)
[worker_1.log.txt](https://github.com/tensorflow/tensorflow/files/484049/worker_1.log.txt)

**Comment by guoying1030** [comment]
who can tell me ???why hang??

**Comment by jmchen-g** [comment]
The links are all empty.

**Comment by guoying1030** [comment]
the links can download ...not empty @jmchen-g

**Comment by drpngx** [comment]
could you try to whittle this down to a smaller example?

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity, we will reopen when further information becomes available.

**Comment by aselle** [comment]
See #5394
