### ISSUE TITLE
I tried installing tensor flow 2 on new MacBook Air (M1), but getting this error "zsh: illegal hardware instruction  python" when I import it

### ISSUE THREAD

**Issue by sumeshthakr** [tensorflow/tensorflow#44999]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by vnvo2409** [comment]
TF hasn't supported M1 yet. However, you could install TensorFlow from https://github.com/apple/tensorflow_macos

**Comment by Saduf2019** [comment]
@sumeshthakr 
The Apple TF on M1 chips is a private fork of TF owned by Apple. We don't have access to fixing code issues there, as per comment in#44751, hence please move this to closed status.

**Comment by nyanye** [comment]
Although the tensorflow for arm64 is only available at apple's private fork,
I think we need x86_64 package that works on top of the mac's rosetta2 emulation.

**Comment by mabidou** [comment]
Same issue happened even with using 

`pip install https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-2.3.0-cp38-cp38-macosx_10_14_x86_64.whl`

as mentioned in https://www.tensorflow.org/install/pip#package-location

tensorflow is shown on listing packages using pip list or conda list but you can't import in Python

**Comment by jpulmano** [comment]
none of the above worked for me, but I downgraded to tensorflow 1.5.0 and the errors went away.
