### ISSUE TITLE
tf-gpu 2.3.1 get initial low accuracy compare to tf-gpu 2.1

### ISSUE THREAD

**Issue by zzhulm** [tensorflow/tensorflow#44990]
I installed tf-gpu 2.3.1 and ran with gpu 1080ti , it get much lower accuracy 0.35 to begin with comparing 0.7 on my previous tf-gpu 2.1,   the loss value are similar to begin with around 1.4
in 2.3.1 reporting 
1670/1670 - 312s - loss: 1.3193 - accuracy: 0.3429
Epoch 2/12
1670/1670 - 295s - loss: 0.9801 - accuracy: 0.4468
Epoch 3/12
1670/1670 - 295s - loss: 0.9100 - accuracy: 0.4869
Epoch 4/12
1670/1670 - 295s - loss: 0.8578 - accuracy: 0.5113

in 2.1 reporting,
418830/418830 - 271s - loss: 1.4756 - accuracy: 0.6926
Epoch 2/12
418830/418830 - 229s - loss: 1.0229 - accuracy: 0.7290
Epoch 3/12
418830/418830 - 230s - loss: 0.9297 - accuracy: 0.7491
Epoch 4/12
418830/418830 - 229s - loss: 0.8621 - accuracy: 0.7627
Epoch 5/12

So anything like that was noticed? and anything is wrong ? or any explanation?

Thank you for any clues!

**Comment by ravikyram** [comment]
@zzhulm 

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by zzhulm** [comment]
Thanks for asking but right now it is hard to forward this real project, I can configure some simply one later.
here is some update,
I tried to run without GPU, the results is similar to 2.3.1 version, which means version 2.1 have some problem to count the accuracy? and in 2.3 it was fixed? the loss value seems similar, so the question is,
even if in tf-gpu 2.1 the accuracy may mis-calculated , the whole learning algorithm with the GPU is still  working  right?
I can conform in my case they are learning and the results make sense.
Thanks

**Comment by zzhulm** [comment]
Thank you for the response,
see my new post

**Comment by ravikyram** [comment]
@zzhulm 

Could you please share sample code to investigate further to find the root cause of the issue.Thanks!

**Comment by zzhulm** [comment]
As i said, my real project code can't be released, but i am trying to get some other code , but so far the simply example did'r show the problem yet, will try others. Thank you.

**Comment by taki0112** [comment]
me too.
So I have changed tf-version to 2.2.0.
Then, the performance is improved.
