### ISSUE TITLE
tf.placeholder API docs should mention possibility of None

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#450]
For `tf.placeholder`, it's possible to have `None` as one or more of the dimensions passed to the `shape` option. This is described in the MNIST tutorial, but is nowhere to be found in the API docs. The latter only mentions that the `shape` option itself may be `None`, but that is an entirely different thing.

**Comment by girving** [comment]
Thanks, that should be fixed.

**Comment by itsmeolivia** [comment]
This looks like it was fixed
