### ISSUE TITLE
Leak memory on ios

### ISSUE THREAD

**Issue by NALanhnt2** [tensorflow/tensorflow#45002]
I need virtual background on video call and I use image segmentation on frame by frame. 
I use Twilio to create video call and get frame video, opencv to edit Image and Tensorflow-lite to use model deeplabv3

But memory leak on some iPhone . To free up memory, I destroy the model and interpreter  after I add background to frame and  allocate a new Interpreter each time when I see a new frame. it’s bad ideal. How can I release memory??
*sorry about my english, it's bad*

**Comment by NALanhnt2** [comment]
@ravikyram please, help me

**Comment by ravikyram** [comment]
@NALanhnt2 

Please, fill [issue template.](https://github.com/tensorflow/tensorflow/issues/new/choose)
Provide the exact sequence of commands / steps that you executed before running into the problem.Thanks!
