### ISSUE TITLE
Error when trying to build from source on on CUDA 11 & Cudnn 8

### ISSUE THREAD

**Issue by Macaque2077** [tensorflow/tensorflow#45001]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubunutu 20.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3
- Python version: 3.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 3.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.1, 8.0.5
- GPU model and memory: RTX 3070 8gb

**Describe the problem**
Cannot build tensorflow 2.3 from source on with CUDA 11.1 and cudnn 8

**Provide the exact sequence of commands / steps that you executed before running into the problem**

followed the instructions from: https://www.tensorflow.org/install/source

./config options are all default except cuda which was enabled 

**Any other info / logs**
bazel build --config=cuda --config=v2 //tensorflow/tools/pip_package:build_pip_package
WARNING: The following configs were expanded more than once: [cuda, using_cuda, v2]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'build' from /home/michael/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/michael/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=v2
INFO: Reading rc options for 'build' from /home/michael/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/lib/python3/dist-packages --python_path=/usr/bin/python3 --config=xla --action_env CUDA_TOOLKIT_PATH=/usr/local/cuda-11.1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=8.6 --action_env LD_LIBRARY_PATH=/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64:/usr/lib/cuda/include:/usr/lib/cuda/lib64: --action_env GCC_HOST_COMPILER_PATH=/usr/bin/x86_64-linux-gnu-gcc-9 --config=cuda --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v2 in file /home/michael/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /home/michael/tensorflow/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:cuda in file /home/michael/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file /home/michael/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:cuda in file /home/michael/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file /home/michael/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:v2 in file /home/michael/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /home/michael/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/michael/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Repository local_config_cuda instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule cuda_configure defined at:
  /home/michael/tensorflow/third_party/gpus/cuda_configure.bzl:1399:18: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
	File "/home/michael/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
		_create_local_cuda_repository(<1 more arguments>)
	File "/home/michael/tensorflow/third_party/gpus/cuda_configure.bzl", line 1051, in _create_local_cuda_repository
		_find_libs(repository_ctx, <2 more arguments>)
	File "/home/michael/tensorflow/third_party/gpus/cuda_configure.bzl", line 598, in _find_libs
		_check_cuda_libs(repository_ctx, <2 more arguments>)
	File "/home/michael/tensorflow/third_party/gpus/cuda_configure.bzl", line 500, in _check_cuda_libs
		execute(repository_ctx, <1 more arguments>)
	File "/home/michael/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed
No library found under: /usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudart.so.11.1
INFO: Repository rules_cc instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule tf_http_archive defined at:
  /home/michael/tensorflow/third_party/repo.bzl:134:19: in <toplevel>
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/michael/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
		_create_local_cuda_repository(<1 more arguments>)
	File "/home/michael/tensorflow/third_party/gpus/cuda_configure.bzl", line 1051, in _create_local_cuda_repository
		_find_libs(repository_ctx, <2 more arguments>)
	File "/home/michael/tensorflow/third_party/gpus/cuda_configure.bzl", line 598, in _find_libs
		_check_cuda_libs(repository_ctx, <2 more arguments>)
	File "/home/michael/tensorflow/third_party/gpus/cuda_configure.bzl", line 500, in _check_cuda_libs
		execute(repository_ctx, <1 more arguments>)
	File "/home/michael/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed
No library found under: /usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudart.so.11.1
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/michael/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
		_create_local_cuda_repository(<1 more arguments>)
	File "/home/michael/tensorflow/third_party/gpus/cuda_configure.bzl", line 1051, in _create_local_cuda_repository
		_find_libs(repository_ctx, <2 more arguments>)
	File "/home/michael/tensorflow/third_party/gpus/cuda_configure.bzl", line 598, in _find_libs
		_check_cuda_libs(repository_ctx, <2 more arguments>)
	File "/home/michael/tensorflow/third_party/gpus/cuda_configure.bzl", line 500, in _check_cuda_libs
		execute(repository_ctx, <1 more arguments>)
	File "/home/michael/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed
No library found under: /usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudart.so.11.1
INFO: Elapsed time: 0.456s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package

**Comment by Harsh188** [comment]
I don't think there is support for CUDA 11 on version 2.3. Try using 2.4.0rc1

**Comment by amahendrakar** [comment]
@Macaque2077,
Every TensorFlow release is compatible with certain CUDA and cuDNN version. TensorFlow v2.3 is compatible with CUDA 10.1 and cuDNN 7.6.

As @Harsh188 said you'll have to use any of the TF v2.4 rc version or TF-nightly with CUDA 11 and cuDNN 8. Thanks!

**Comment by teja2002** [comment]
you have to use cuda 10.1

**Comment by Macaque2077** [comment]
> I don't think there is support for CUDA 11 on version 2.3. Try using 2.4.0rc1

Thanks, I installed TensorFlow==2.4.0rc2 and it appears to be recognising the GPU and opening all the CUDA and cuDNN libraries without error.

Using:
tf.test.is_gpu_available(
    cuda_only=False, min_cuda_compute_capability=None
)

**Comment by Harsh188** [comment]
@Macaque2077 if it's working for you could you kindly close this issue? Also if you have the time could you look into #45044. Thanks.

**Comment by amahendrakar** [comment]
> Thanks, I installed TensorFlow==2.4.0rc2 and it appears to be recognising the GPU and opening all the CUDA and cuDNN libraries without error.

@Macaque2077,
Thank you for the update. Marking this issue as closed, as it is resolved. Please feel free to re-open if necessary. Thanks!
