### ISSUE TITLE
Filling values when rotating an image using functions like tfa.image.rotate() and tfa.image.translate()

### ISSUE THREAD

**Issue by bjarrell15** [tensorflow/tensorflow#45017]
**System information**
- TensorFlow version (you are using): 2.3.0
- Are you willing to contribute it (Yes/No): Yes. I'm not a great programmer, but I'm willing to help in any way I can.

**Describe the feature and the current behavior/state.**

_This feature request stems from a separate issue that was described [here](https://github.com/tensorflow/tensorflow/issues/44059)._

When you use skimage to [rotate](https://scikit-image.org/docs/dev/api/skimage.transform.html#skimage.transform.rotate) or translate an image, you are given the option to fill in the values that the image loses by performing these operations with reflected values or symmetric values, for example. I used to have an augmentation function that used this functionality successfully, but then the functionality stopped. 

I updated the augmentation to use the functions from tensorflow_addons listed in the title. However, I've now lost this ability to fill in lost values to utilize some of the original information. I think it'd be a good idea to add this as an option to these functions in tfa.

**Will this change the current api? How?**

Not sure.

**Who will benefit with this feature?**

ML practitioners, remote sensing practitioners, geospatial professionals in general.

**Any Other info.**

The modes that skimage includes for these fill values are in line with the behavior of [numpy.pad](https://numpy.org/doc/stable/reference/generated/numpy.pad.html#numpy.pad).

**Comment by bhack** [comment]
Can you check https://github.com/tensorflow/addons/pull/2153 /cc @WindQAQ

**Comment by bjarrell15** [comment]
Yes, I've checked it. It seems similar to this issue. Should the issues be merged? Should this issue be closed?

**Comment by bhack** [comment]
That PR is already merged

**Comment by WindQAQ** [comment]
Tensorflow-Addons will support it after TF2.4 releases. Alternatively, you can use `tf.keras.layers.experimental.preprocessing.Random*` to achieve it.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/preprocessing/image_preprocessing.py#L818-L824

**Comment by WindQAQ** [comment]
@bjarrell15  Tensorflow-Addons will support it after TF2.4 releases. Alternatively, you can use `tf.keras.layers.experimental.preprocessing.Random*` in tf-nightly to achieve it.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/preprocessing/image_preprocessing.py#L818-L824
