### ISSUE TITLE
Test linking fails due to missing ldl

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#45013]
**System information**
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.4.0-rc2

**Describe the problem**

Building the tests `//tensorflow/python/...` fails with a link error on `//tensorflow/python/tools:aot_compiled_test` due to stacktrace.h using `dladdr` but nothing in the chain links against `-ldl`.

Chain: aot_compiled_test -> "//tensorflow/core:test_main" -> "//tensorflow/core/platform:test_main" -> ":stacktrace_handler"

**Any other info / logs**
Looks like the issue can simply be fixed by adding the ldl flag to the ls test_main rule

**Comment by rmothukuru** [comment]
@Flamefire, 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by Flamefire** [comment]
Just running `bazel test //tensorflow/python/...` should be enough, however I guess it depends on the system whether libdl.so is already linked transitively.

So I'd rather argue from a correctness/review way:
- `dladdr` is used: https://github.com/tensorflow/tensorflow/blob/602bac2ab8c7f995ce0a028121061568109b5b16/tensorflow/core/platform/default/stacktrace.h#L55
- That inline function calling `dladdr` is used: https://github.com/tensorflow/tensorflow/blob/dec8e0b11f4f87693b67e125e67dfbc68d26c205/tensorflow/core/platform/default/stacktrace_handler.cc#L88
- The `cc_library` rule for that does not link libdl: https://github.com/tensorflow/tensorflow/blob/602bac2ab8c7f995ce0a028121061568109b5b16/tensorflow/core/platform/BUILD#L633-L638
- `test_main` links against the stacktrace rule but but does not link libdl either: https://github.com/tensorflow/tensorflow/blob/602bac2ab8c7f995ce0a028121061568109b5b16/tensorflow/core/platform/BUILD#L959-L977
- And finally the test links against `test_main` but not libdl: https://github.com/tensorflow/tensorflow/blob/3c4b0fc75f07991c85b56eb8d7515f3cfb9b7fc8/tensorflow/python/tools/BUILD#L501-L519

Conclusion: A function (`dladdr`) which requires a library (`libdl`) is used but that library is never linked (explicitly).

It is used for other rules though, e.g. https://github.com/tensorflow/tensorflow/blob/f2846d35f44ae7a5cd0070381a5cff94f5ddb6fc/tensorflow/core/lib/gif/BUILD#L32

**Comment by Flamefire** [comment]
Yes the issue still persists

**Comment by Flamefire** [comment]
Yes this still persists but heavily depends on the system. See analysis in https://github.com/tensorflow/tensorflow/issues/45013#issuecomment-731981718 which still applies.
