### ISSUE TITLE
Reduce on MirroredVariable

### ISSUE THREAD

**Issue by cloudhan** [tensorflow/tensorflow#45026]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution: Ubuntu 16.04
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.4.0rc2
- Python version: 3.8.3
- CUDA/cuDNN version:  11.0
- GPU model and memory: 4*1080Ti

**Describe the current behavior**

Run the following code:
```python
import tensorflow as tf

s = tf.distribute.MirroredStrategy()

with s.scope():
    v = tf.Variable(tf.ones((5,)))
for x in v.values:
    print(x, x.device)

# @tf.function
def run():
    def fn(value):
        ctx = tf.distribute.get_replica_context()
        # value = 0.0 + value
        return ctx.all_reduce(tf.distribute.ReduceOp.SUM, value)
    return s.run(fn, args=(v,))

print(run())
```

Outputs:
```
PerReplica:{
  0: tf.Tensor([1. 1. 1. 1. 1.], shape=(5,), dtype=float32),
  1: tf.Tensor([1. 1. 1. 1. 1.], shape=(5,), dtype=float32),
  2: tf.Tensor([1. 1. 1. 1. 1.], shape=(5,), dtype=float32),
  3: tf.Tensor([1. 1. 1. 1. 1.], shape=(5,), dtype=float32)
}
```

Which is clearly wrong.

**Describe the expected behavior**

Expect output:
```
PerReplica:{
  0: tf.Tensor([4. 4. 4. 4. 4.], shape=(5,), dtype=float32),
  1: tf.Tensor([4. 4. 4. 4. 4.], shape=(5,), dtype=float32),
  2: tf.Tensor([4. 4. 4. 4. 4.], shape=(5,), dtype=float32),
  3: tf.Tensor([4. 4. 4. 4. 4.], shape=(5,), dtype=float32)
}
```

Uncomment the line `# value = 0.0 + value` will make the result correct.

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tensorflow 2.5, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/adf1514f5ae43210262ae4cac4467589/45026.ipynb), Thanks!

**Comment by tilakrayal** [comment]
@cloudhan,
I tried to execute the mentioned code on colab with GPU enabled and on the Ubuntu VM. Kindly find the [gist](https://colab.research.google.com/gist/tilakrayal/ba44a70cbd6d3302043032ea82e080ac/untitled1095.ipynb) and also the screen shot for the reference.

![Screenshot 2023-04-28 3 11 46 PM](https://user-images.githubusercontent.com/81610181/235115361-2bcbf1ee-1fd7-45de-a7ea-b48ab5f75c24.png)

There are 2 GPU's in the VM and the output of the VM was similar as expected.
```
PerReplica:{
  0: tf.Tensor([2. 2. 2. 2. 2.], shape=(5,), dtype=float32),
  1: tf.Tensor([2. 2. 2. 2. 2.], shape=(5,), dtype=float32)
} 
```
and the colab contains a single GPU and the output was as below.

```
<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([1., 1., 1., 1., 1.], dtype=float32)> /job:localhost/replica:0/task:0/device:GPU:0
<tf.Variable 'Variable/replica_1:0' shape=(5,) dtype=float32, numpy=array([1., 1., 1., 1., 1.], dtype=float32)> /job:localhost/replica:0/task:0/device:GPU:1
```
