### ISSUE TITLE
execution_profile_test_with_xla_hlo_profile_cpu fails on s390x

### ISSUE THREAD

**Issue by skribm9** [tensorflow/tensorflow#45021]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.3.1
- Python version: 3.6.9
- Bazel version (if compiling from source): 3.4.1
- GCC/Compiler version (if compiling from source): Ubuntu 7.5.0-3ubuntu1~18.04
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
When running test case  `//tensorflow/compiler/xla/tests:execution_profile_test_with_xla_hlo_profile_cpu` on s390x, the test case fails with following error:
```
[ RUN      ] ExecutionProfileTest.ExecuteWithExecutionProfile
2020-10-29 23:11:59.065069: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 1555500000 Hz
2020-10-29 23:11:59.065621: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2aa54027e20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-29 23:11:59.065633: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-29 23:11:59.077512: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2aa54028350 initialized for platform Interpreter (this does not guarantee that XLA will be used). Devices:
2020-10-29 23:11:59.077526: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Interpreter, <undefined>
tensorflow/compiler/xla/tests/execution_profile_test.cc:60: Failure
Expected: (execution_profile.compute_cycle_count()) > (0), actual: 0 vs 0
[  FAILED  ] ExecutionProfileTest.ExecuteWithExecutionProfile (36 ms)
[----------] 1 test from ExecutionProfileTest (36 ms total)
```

On debugging this test case a little, I found that the Test case is able to call `RecordCycleDelta` and registering values in `new_cycle_count` but on calling `compute_function_`, the `profile_counters` are not filled.
The compute function here is returning a valid value in `profile_counters` for x86 but returning 0 for s390x.
https://github.com/tensorflow/tensorflow/blob/21f5c12e3d9c5b0c2f4c45c70a3da08b4edf212d/tensorflow/compiler/xla/service/cpu/cpu_executable.cc#L188

**Describe the expected behavior**
The `profile_counters` should be populated with a valid value and test case should pass.

**Standalone code to reproduce the issue**
```bazel --host_jvm_args="-Xms1024m" --host_jvm_args="-Xmx2048m" test --host_javabase="@local_jdk//:jdk" --test_tag_filters=-gpu,-benchmark-test,-v1only,-no_oss,-oss_serial -k --test_timeout 300,450,1200,3600 --build_tests_only --test_output=errors --verbose_failures -- //tensorflow/compiler/xla/tests:execution_profile_test_with_xla_hlo_profile_cpu```

**Comment by skribm9** [comment]
Hi @r4nt , A very happy and safe new year to you! Could you find anything on this issue?

**Comment by sushreebarsa** [comment]
@skribm9 It looks like you are using an older Version of Tensorflow . Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.5 and let us know if the issue still persists? Thanks!

**Comment by rposts** [comment]
@sushreebarsa Problem still exists on TF 2.9.1 - is there something we can do to further assist with debugging?

**Comment by rposts** [comment]
@sushreebarsa @r4nt Feel free to close it - this may possibly be related to https://github.com/llvm/llvm-project/issues/50374

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
