### ISSUE TITLE
Could not create TensorFlow Graph: Not found: Op type not registered 'AddV2'  IOS

### ISSUE THREAD

**Issue by zhidk** [tensorflow/tensorflow#45024]
Using tensorFlow_gpu==1.15.0, ssD_mobilenet_V1 is trained through TensorFlow API. Then  
models-master\research\object_detection>python export_inference_graph.py
 --input_type image_tensor 
--pipeline_config_path  /data/pipeline.config 
--trained_checkpoint_prefix  /training/model.ckpt-200000 
--output_directory  convert_pb/
 Get frozen_inference_graph.pb,
This frozen_inference_graph.pb file is applied to IOS to report an error,
/Users/zhao/Desktop/tensorflow-1.15.0/tensorflow/examples/ios/camera/tensorflow_utils.mm:140] Could not create TensorFlow Graph: Not found: Op type not registered 'AddV2'

**Comment by Saduf2019** [comment]
@zhidk 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]
Please upgrade to 2.x and let us know if the issue exist as there is no support for 1.x

**Comment by zhidk** [comment]
yes.thankyou.
