### ISSUE TITLE
Building r2.3 branch fails on Windows 10 x64

### ISSUE THREAD

**Issue by Masterchef365** [tensorflow/tensorflow#45020]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64 build 19041.630
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.3 (commit 5681c179eff80bce00e526303950b67b23cad14c)
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 3.7.0
- GCC/Compiler version (if compiling from source): msvc 19.28.29333
- CUDA/cuDNN version: CUDA 10.1.243; cuDNN version 8
- GPU model and memory: GTX 1080 8GB

**Describe the problem**
TensorFlow branch r2.3 fails to compile on Windows 10 (see log section)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Setup as per https://www.tensorflow.org/install/source_windows. Every setting set to default, except for CUDA support which was enabled.
`bazel build //tensorflow/tools/pip_package:build_pip_package`

**Any other info / logs**
(Most of the log skipped as it is a normal build until around this point)
```
external/com_google_absl\absl/time/clock.h(70): error C2065: 'Duration': undeclared identifier
external/com_google_absl\absl/time/clock.h(70): error C2146: syntax error: missing ')' before identifier 'duration'
external/com_google_absl\absl/time/clock.h(70): error C2143: syntax error: missing ';' before '{'
external/com_google_absl\absl/time/clock.h(70): error C2447: '{': missing function header (old-style formal list?)
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 720.763s, Critical Path: 176.43s
INFO: 860 processes: 860 local.
FAILED: Build did NOT complete successfully
```

Bonus: I get an entirely different error in the current master as of this writing (6de8d69b23ebc26c7f364ce4bc775aa45a063937):
```
this rule is missing dependency declarations for the following files included by 'tensorflow/lite/tools/optimize/model_utils.cc':
  'external/com_google_absl/absl/strings/string_view.h'
  'external/com_google_absl/absl/base/internal/throw_delegate.h'
```

**Comment by ymodak** [comment]
Can you please try with bazel version 3.1.0 https://github.com/tensorflow/tensorflow/blob/r2.3/.bazelversion? Thanks!

**Comment by OliPhilip** [comment]
System information

-OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.1 LTS
-Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
-TensorFlow installed from (source or binary): source
-TensorFlow version: 2.3
-Python version: 3.8.5
-Installed using virtualenv? pip? conda?: N/A
-Bazel version (if compiling from source): 3.1.0
-GCC/Compiler version (if compiling from source): 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
-CUDA/cuDNN version: cuda_11.1.TC455_06.29190527_0; cuDNN version 8.0.5
-GPU model and memory: GTX-1080Ti

Describe the problem
TensorFlow branch r2.3 fails to compile

Provide the exact sequence of commands / steps that you executed before running into the problem

`./configure`

> 
> You have bazel 3.1.0 installed.
> Please specify the location of python. [Default is /usr/bin/python3]: 
> 
> 
> Found possible Python library paths:
>   /usr/local/lib/python3.8/dist-packages
>   /usr/lib/python3/dist-packages
> Please input the desired Python library path to use.  Default is [/usr/local/lib/python3.8/dist-packages]
> 
> Do you wish to build TensorFlow with ROCm support? [y/N]: n
> No ROCm support will be enabled for TensorFlow.
> 
> Do you wish to build TensorFlow with CUDA support? [y/N]: y
> CUDA support will be enabled for TensorFlow.
> 
> Do you wish to build TensorFlow with TensorRT support? [y/N]: y
> TensorRT support will be enabled for TensorFlow.
> 
> Found CUDA 11.1 in:
>     /usr/local/cuda-11.1/targets/x86_64-linux/lib
>     /usr/local/cuda-11.1/targets/x86_64-linux/include
> Found cuDNN 8 in:
>     /usr/lib/x86_64-linux-gnu
>     /usr/include
> Found TensorRT 7 in:
>     /usr/lib/x86_64-linux-gnu
>     /usr/include/x86_64-linux-gnu
> 
> 
> Please specify a list of comma-separated CUDA compute capabilities you want to build with.
> You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus. Each capability can be specified as "x.y" or "compute_xy" to include both virtual and binary GPU code, or as "sm_xy" to only include the binary code.
> Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 6.1]: 
> 
> 
> Do you want to use clang as CUDA compiler? [y/N]: n
> nvcc will be used as CUDA compiler.
> 
> Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
> 
> 
> Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native -Wno-sign-compare]: 
> 
> 
> Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
> Not configuring the WORKSPACE for Android builds.
> 

```
sudo rm -Rf ~/.cache/bazel
bazel build --copt="-fPIC" --config=opt --config=cuda --noincompatible_strict_action_env //tensorflow/tools/pip_package:build_pip_package --verbose_failures

```

> INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (416 packages loaded, 33269 targets configured).
> INFO: Found 1 target...
> ERROR: /home/olivier/tensorflow/tensorflow/lite/tools/optimize/BUILD:140:1: undeclared inclusion(s) in rule '//tensorflow/lite/tools/optimize:model_utils':
> this rule is missing dependency declarations for the following files included by 'tensorflow/lite/tools/optimize/model_utils.cc':
>   'external/com_google_absl/absl/strings/string_view.h'
>   'external/com_google_absl/absl/base/internal/throw_delegate.h'
> Target //tensorflow/tools/pip_package:build_pip_package failed to build
> INFO: Elapsed time: 5701.973s, Critical Path: 144.65s
> INFO: 10343 processes: 10343 local.
> FAILED: Build did NOT complete successfully

**Comment by Masterchef365** [comment]
> Can you please try with bazel version 3.1.0 https://github.com/tensorflow/tensorflow/blob/r2.3/.bazelversion?
> Also mentioned in the [tested build configurations](https://www.tensorflow.org/install/source#gpu). Thanks!

Just tried with bazel version 3.1.0, had a few different build errors so I decided to re-clone and build from scratch again with bazel 3.1.0; this resulted in the same error as the original issue.

**Comment by paleozogt** [comment]
I'm seeing this same problem with TF v2.3.1 / Bazel v3.10 / MSVC 2017 / CUDA 10.1.  It's happening when building `tensorflow/core/kernels/histogram_op_gpu.cu.cc`.

The problem is that nvcc is changing the input code in a way that is incompatible with MSVC 2017.  The original `external/com_google_absl\absl/time/clock.h` has this:
```
inline void absl::SleepFor(absl::Duration duration) {
  AbslInternalSleepFor(duration);
}
```

Then nvcc generates a temp `histogram_op_gpu.cu.cudafe1.cpp` and tries to build it with `cl`.  This file has already had the preprocessor run on it (presumably by nvcc?), so all its macros/includes have been expanded.  The section corresponding to the above `clock.h` code looks like this:
```
#line 70
inline void absl::SleepFor(Duration duration) { 
#line 71
AbslInternalSleepFor(duration); 
#line 72
} 
```

Note that `absl::Duration` has changed to `Duration`.  This is fine for gcc/clang, but is a bug with MSVC (see this [SO post.](https://stackoverflow.com/questions/55181616/using-type-from-inline-namespace-in-cpp-file-does-not-work-in-msvs))
