### ISSUE TITLE
AttributeError: 'TFLiteConverter' object has no attribute 'target_spec'

### ISSUE THREAD

**Issue by lxiao217** [tensorflow/tensorflow#45025]
URL(s) with the issue:

https://www.tensorflow.org/lite/performance/post_training_quantization

## Description of issue:

i want to quant my model with int8, my code like this:

import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_keras_model_file("./tf_keras_mnist_model/cifar10_vgg16.h5")
converter.optimizations = [tf.lite.Optimize.DEFAULT]
def representative_dataset_gen():
  for _ in range(10):
    # Get sample input data as a numpy array in a method of your choosing.
    yield [input]
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8
tflite_quant_model = converter.convert()
open("./tf_keras_mnist_model/cifar10_vgg16_quant8.tflite", "wb").write(tflite_quant_model)

this code is also in your example provided, but I get the error like the title.
 my tf is 1.14.
how can i solute this problem?

the second question is :
when i use   tf.lite.TFLiteConverter.from_keras_model,   i got the error TFLiteConverter has no attribute from_keras_model, i also encount the problem   TFLiteConverter has no attribute from_saved_model?

this two api need the tf version?

thanks 

appreciate to get your apply!

**Comment by amahendrakar** [comment]
@lxiao217,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to v2.3 and check if you are facing the same error?

> when i use tf.lite.TFLiteConverter.from_keras_model, i got the error TFLiteConverter has no attribute from_keras_model, i also encount the problem TFLiteConverter has no attribute from_saved_model?

Seems like you are running code meant for TF 2.x, on TF 1.x. `from_keras_model` and `from_saved_model` are APIs of TensorFlow 2.x. For more information please take a look at the [documentation](https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter#from_keras_model) for TFLiteConverter. Thanks!

**Comment by lxiao217** [comment]
> @lxiao217,
> TensorFlow 1.x is not actively supported. Could you please update TensorFlow to v2.3 and check if you are facing the same error?
> 
> > when i use tf.lite.TFLiteConverter.from_keras_model, i got the error TFLiteConverter has no attribute from_keras_model, i also encount the problem TFLiteConverter has no attribute from_saved_model?
> 
> Seems like you are running code meant for TF 2.x, on TF 1.x. `from_keras_model` and `from_saved_model` are APIs of TensorFlow 2.x. For more information please take a look at the [documentation](https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter#from_keras_model) for TFLiteConverter. Thanks!

thanks for your reply, i think the problem is I trained the model on 1.x while i use the 2.x apis to convert.
