### ISSUE TITLE
tf.keras.layers.LSTM don't check mask shape(tensorflow-gpu with cuda)

### ISSUE THREAD

**Issue by lieberman94** [tensorflow/tensorflow#45035]
use tensorflow-gpu with cuda, LSTM don't check mask shape。but it check in tensorflow-cpu. it cause the code below failed in cpu but work in GPU.
error information:  tensorflow.python.framework.errors_impl.OutOfRangeError: Tried to read from index 5 but array size is: 5
```
inputs = tf.random.normal([4, 6, 4])
lstm=tf.keras.layers.LSTM(4,return_sequences=True)
masks=tf.sequence_mask(
    [1,2,3,4],
    maxlen=5,
    dtype=tf.bool
)
# or 
# masks=tf.sequence_mask(
#     [1,2,3,4,4],
#     maxlen=5,
#     dtype=tf.bool
# )
output=lstm(inputs,mask=masks)
```

**Comment by ravikyram** [comment]
@lieberman94 

I tried in colab with TF version 2.4-rc1 and i am seeing the error message with [cpu](https://colab.research.google.com/gist/ravikyram/e0267a08df64b67f5ec315269da17cfa/untitled525.ipynb) and [gpu](https://colab.research.google.com/gist/ravikyram/a1b0be72e845cde8091c78ade83f2d78/untitled525.ipynb) also.Thanks!
