### ISSUE TITLE
setup.py is missing tblib dependency

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#45034]
As the title says: tblib is used at https://github.com/tensorflow/tensorflow/blob/5e48683fe0983d5f35f1305f426d1b06904329a4/tensorflow/python/distribute/multi_process_runner.py but not declared as a dependency in setup.py

This is for current master and 2.4rc2

**Comment by bhack** [comment]
Cause I see that it is only related to CI

**Comment by Flamefire** [comment]
I see it is seemingly optional.

Maybe @crccw can clarify why/how that dependency is required?

**Comment by crccw** [comment]
It's only needed in multi worker tests.

**Comment by Flamefire** [comment]
Shouldn't this then go to the `TEST_PACKAGES` in `setup.py`?
