### ISSUE TITLE
tensorflow/lite/micro/tools/make/Makefile:403: *** Something went wrong with the flatbuffers download: .  Stop.

### ISSUE THREAD

**Issue by YANxu-666** [tensorflow/tensorflow#45033]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:N
- TensorFlow installed from (source or binary):source
- TensorFlow version:2.3.1
- Python version:3.8.3
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
The code I entered is：
PS E:\tensorflow> make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test
The output result is：
process_begin: CreateProcess(NULL, uname -m, ...) failed.
process_begin: CreateProcess(NULL, bash E:\tensorflow\tensorflow\lite\micro\tools\make\flatbuffers_download.sh tensorflow/lite/micro/tools/make/downloads, ...) failed.
tensorflow/lite/micro/tools/make/Makefile:403: *** Something went wrong with the flatbuffers download: .  Stop.

What is the reason?

**Comment by bhack** [comment]
I see in your template `TensorFlow version:2.3.1` but in your log `E:\tensorflow\tensorflow\lite\micro\tools\make\flatbuffers_download.sh` and this file was not in `2.3.1` code base.

On what version are you working?

**Comment by YANxu-666** [comment]
> in your log and this file was not in code base

I'm very sorry.I can't understand what you mean, my tensorflow is version 2.3.1.

**Comment by bhack** [comment]
On master it was moved in a standalone script but I don't know if it was a bugfix or a feature request cause the ticket was internal (b/143904317) https://github.com/tensorflow/tensorflow/pull/44860  /cc @advaitjain

**Comment by YANxu-666** [comment]
> On master it was moved in a standalone script but I don't know if it was a bugfix or a feature request cause the ticket was internal (b/143904317) #44860 /cc @advaitjain

So which version should I use?

**Comment by YANxu-666** [comment]
process_begin: CreateProcess(NULL, bash E:\tensorflow\tensorflow\lite\micro\tools\make\flatbuffers_download.sh tensorflow/lite/micro/tools/make/downloads, ...) failed. 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/tools/make/flatbuffers_download.sh
This file failed，but i don't know why.
I am very anxious

**Comment by advaitjain** [comment]
With https://github.com/tensorflow/tensorflow/pull/44860 and a few related PRs, we are moving towards having the downloads take place via stand-alone scripts with the goal of making things more stable and easier to maintain.

So yes, using flatbuffer_download.sh is the way to go.

The Linux build is ok (you can check the badge here):
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro#continuous-build-status

@YANxu-666: we don't have any continuous integration for Windows so it is possible that something in the script is not Windows-compatible. Can you try running the following command and report any errors:
```
tensorflow/lite/micro/tools/make/flatbuffers_download.sh tensorflow/lite/micro/tools/make/downloads
```

**Comment by Bonolo-Maluleke** [comment]
There is a good solution to this from the TinyML Forum:

https://forums.tinyml.org/t/make-doesnt-work-on-hello-world-test-from-tinyml-book/344
