### ISSUE TITLE
tf2.3  keras model can't save  big embedding:  tensorflow.SavedModel exceeds maximum protobuf size of 2GB

### ISSUE THREAD

**Issue by BookChan** [tensorflow/tensorflow#45041]
# what
When we try to save a simple keras model with  embedding layer,which shape is (1e7,16),  we got error `ValueError: Message tensorflow.SavedModel exceeds maximum protobuf size of 2GB: 9789558077` .
We want to save it as SavedModel format ,so that we can use tf serving to serve the model. 

# related problems
[Tensorflow graph bigger than 2GB](https://stackoverflow.com/questions/59558170/tensorflow-graph-bigger-than-2gb)

# simple code that reproduce the error
```python

import tensorflow as tf
from tensorflow import keras

import numpy as np
vocab_size = 10**7
emb_dim = 16
global_emb_weights = np.random.random(size=(vocab_size,emb_dim))
emb = keras.layers.Embedding( mask_zero=True, input_dim=vocab_size, output_dim=emb_dim,
                                     embeddings_initializer=keras.initializers.Constant(
                                         global_emb_weights),trainable=True)

x = keras.Input((100,))
out = emb(x)
model = keras.Model(inputs=x,outputs=out)
model.save("/tmp/test_tf",save_format="tf",overwrite=True)

``` 
# error
>    File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/save.py", line 80, in save
>     save_lib.save(model, filepath, signatures, options)
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 1006, in save
>     path, saved_model.SerializeToString(deterministic=True))
> ValueError: Message tensorflow.SavedModel exceeds maximum protobuf size of 2GB: 9789558077

**Comment by bhack** [comment]
Please check https://github.com/tensorflow/hub/blob/master/examples/text_embeddings/export.py#L204-L219

**Comment by Saduf2019** [comment]
I ran the code shared and colab crashes, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/15e03498f196eda58d47f32f2a6c3572/untitled466.ipynb).

**Comment by BookChan** [comment]
> Please check https://github.com/tensorflow/hub/blob/master/examples/text_embeddings/export.py#L204-L219

It uses the tf1.x low level api.  How can we solve this  in keras's style.

**Comment by fchollet** [comment]
What I would suggest doing is simply:

```python
emb = keras.layers.Embedding( mask_zero=True, input_dim=vocab_size, output_dim=emb_dim, trainable=True)
emb.set_weights([global_emb_weights])
```

Basically, move the weight init outside of the model definition, so that the weights don't get saved as part of the model config (since the model config captures "model definition").

**Comment by bhack** [comment]
It was a quite frequent request on stackoverflow probably it needs to be documented.

**Comment by BookChan** [comment]
> What I would suggest doing is simply:
> 
> ```python
> emb = keras.layers.Embedding( mask_zero=True, input_dim=vocab_size, output_dim=emb_dim, trainable=True)
> emb.set_weights([global_emb_weights])
> ```
> 
> Basically, move the weight init outside of the model definition, so that the weights don't get saved as part of the model config (since the model config captures "model definition").

It works,  but `set_weights` should placed after  layer operation,for example `x = keras.Input((1,));out = emb(x)`.

Code that works:
```python
import tensorflow as tf
from tensorflow import keras
import numpy as np

vocab_size =  10**7
emb_dim = 16
np.random.seed(0)
global_emb_weights = np.random.random(size=(vocab_size,emb_dim))
emb = keras.layers.Embedding( mask_zero=True, input_dim=vocab_size, output_dim=emb_dim,
                                     trainable=True,input_length=10)
x = keras.Input((1,))
out = emb(x)
emb.set_weights([global_emb_weights]) #  move the weight init outside of the model definition,
model = keras.Model(inputs=x,outputs=out)
x1 = model.predict([list(range(10))])
 

model.save("/tmp/test_tf",save_format="tf",overwrite=True)
model2 = tf.keras.models.load_model("/tmp/test_tf")
x2 = model2.predict([list(range(10))])
print("x1=x2:{}".format((x1==x2).all()))
```
