### ISSUE TITLE
use hooks to fine_tune in Estimator

### ISSUE THREAD

**Issue by DaerTaeKook** [tensorflow/tensorflow#45043]
**System information**
- TensorFlow version (you are using):tf.1.14
- Are you willing to contribute it (Yes/No):yes

**1. Describe the feature and the current behavior/state.**

when I use hook to fine_tune in estimator, I got such a error:RuntimeError: Graph is finalized and cannot be modified.

My hooks is defined as follows:
class RestoreHook(tf.train.SessionRunHook):
    def __init__(self, checkpoint_path, include=None, exclude=None):
        self.checkpoint_path =  tf.train.latest_checkpoint(checkpoint_path)
        self.include = include
        self.exclude = exclude

    def after_create_session(self, session, coord=None):
        var_list = tf.contrib.framework.get_variables_to_restore(include=self.include, exclude=self.exclude)

        self.init_fn = tf.contrib.framework.assign_from_checkpoint_fn(
            self.checkpoint_path,
            var_list=var_list,
            ignore_missing_vars=True
        )
        if session.run(tf.train.get_or_create_global_step()) == 0:
            # suppress WARN
            log_level = tf.logging.get_verbosity()
            tf.logging.set_verbosity(tf.logging.ERROR)
            self.init_fn(session)
            tf.logging.set_verbosity(log_level)

2、My calling method：

init_checkpoint = './my_model/'
        from finetune import get_tvars
        assignment_map ,assignment_map_keys = get_tvars(init_checkpoint)
        for dict in assignment_map:
            if "global" in dict:
                assignment_map.pop(dict)
        include_var = list(assignment_map_keys)
        checkpoint_path = init_checkpoint
        restore_hook = RestoreHook(checkpoint_path, include=include_var)
    else:
        restore_hook = None
    train_spec = tf.estimator.TrainSpec(
        input_fn=input_fn
        max_steps=100000,
        hooks=[restore_hook]
)

**Comment by bhack** [comment]
Can you try to use a modern version of TF? Generally it is hard to receive support for tf.1.14 here.

**Comment by DaerTaeKook** [comment]
> Can you try to use a modern version of TF? Generally it is hard to receive support for tf.1.14 here.

But I don't think the upgrade will solve this problem.The evaluate will return a global_step parameter in the API of tf 2.3.0 ,as the same as tf1.14  ,I think it is the global step parameter returned by loading the old model that conflicts with the global step of the current model.So is there any method to solve this problem?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
