### ISSUE TITLE
 W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found

### ISSUE THREAD

**Issue by marshallia** [tensorflow/tensorflow#45055]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution Windows 10 x64
- TensorFlow installed using pip
- TensorFlow version 2.5.0-dev20201028
- Python version: Python  3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] on win32
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: cuda 11.1/cudnn 80.04
- GPU model and memory: NVIDIA RTX3080

Hi,
I got this issues when I am trying to import tensorflow from  command line.
Currently I am using NVIDIA RTX3080, with cuda 11.1, cudnn 8.04, python 64 bit, and nvidia driver 456.43. 
I follow the instruction on https://www.tensorflow.org/install, and install tf-nightly 2.5.0.dev and tf-nightly-gpu 2.5.0.dev. 
I also have try the solution on this discussion but it didn't work me https://github.com/tensorflow/tensorflow/issues/43193. 
But I am still getting this error
![error](https://user-images.githubusercontent.com/12694360/99868899-bea4e880-2c01-11eb-90d9-c8d1e80638f6.PNG)

![program_file](https://user-images.githubusercontent.com/12694360/99868905-d1b7b880-2c01-11eb-86c5-4ff7affa7886.PNG)
![path](https://user-images.githubusercontent.com/12694360/99868808-d465de00-2c00-11eb-82f8-4a1532bf2618.PNG)
![nvcc](https://user-images.githubusercontent.com/12694360/99868809-d7f96500-2c00-11eb-91db-1af79086e982.PNG)
![python](https://user-images.githubusercontent.com/12694360/99868829-0e36e480-2c01-11eb-81b1-8635d52a9790.PNG)

**Comment by marshallia** [comment]
Hi,
I got this issues when I am trying to import tensorflow from  command line.
Currently I am using NVIDIA RTX3080, with cuda 11.1, cudnn 8.04, python 64 bit, and nvidia dirver 456.43. 
I follow the instruction on https://www.tensorflow.org/install, and install tf-nightly 2.5.0.dev and tf-nightly-gpu 2.5.0.dev. 
I also have try the solution on this discussion but it didn't work me https://github.com/tensorflow/tensorflow/issues/43193. 
But I am still getting this error
` W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2020-11-21 05:32:58.478751: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-11-21 05:33:14.569565: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-11-21 05:35:17.184273: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2020-11-21 05:35:17.221677: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1724] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 3080 computeCapability: 8.6
coreClock: 1.71GHz coreCount: 68 deviceMemorySize: 10.00GiB deviceMemoryBandwidth: 707.88GiB/s
2020-11-21 05:35:17.224949: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found`

**Comment by king398** [comment]
I think You should check if you have added all the cuda enviroment path variable. Type this in you command prompt 
`PATH`

**Comment by Saduf2019** [comment]
@marshallia 
please refer to these issues with same error and let us know: [link](https://stackoverflow.com/questions/59823283/could-not-load-dynamic-library-cudart64-101-dll-on-tensorflow-cpu-only-install),

**Comment by marshallia** [comment]
> @marshallia
> please refer to these issues with same error and let us know: [link](https://stackoverflow.com/questions/59823283/could-not-load-dynamic-library-cudart64-101-dll-on-tensorflow-cpu-only-install), [link1](https://github.com/tensorflow/tensorflow/issues/45072#issuecomment-731783830), #43193
> 
> Have you set in PATH
> SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11\bin;%PATH%

Hi, Saduf. 
I have give up on installing tensorflow on windows. Instead of using Windows I use Ubuntu and install cuda 11.1 package that contains nvidia driver inside it. Then install tensorflow nightly. And it is work for me

Cuda 11.1
Nvidia driver 455.32
Tensorfl

**Comment by CostanzoPablo** [comment]
I have the same problem and the solution is:

1) Uninstall all drivers that says "nvidia" from Uninstall programs (ALL, Cuda and gpu driver)
2) Install last nvidia drivers for your GPU https://uk.download.nvidia.com/GFE/GFEClient/3.21.0.36/GeForce_Experience_v3.21.0.36.exe
3) Install cuda 11.2 https://developer.download.nvidia.com/compute/cuda/11.2.1/local_installers/cuda_11.2.1_461.09_win10.exe
2) Install Anaconda https://repo.anaconda.com/archive/Anaconda3-2020.11-Windows-x86_64.exe
3) conda create -n cudaenv python=3.6
4) conda activate cudaenv
5) pip install flask tensorflow python-dotenv
6) Create a.py with this: import tensorflow as tf
7) run it: python a.py 
Output:
xxx: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll

**Comment by pythonic2020** [comment]
@CostanzoPablo, thank you very much for the above post.  I finally got tf 2.4.1 to install in a conda-forge environment with GPU support (CUDA 11.3, Python 3.8.8)!  Where did you find out that "python-dotenv" should be installed?  I haven't seen that package mentioned anywhere on tf website, or anywhere else, with regard to tf install.

**Comment by sprash** [comment]
@CostanzoPablo  That worked for me! Thanks for posting this solution.
