### ISSUE TITLE
Concatenating sparse keras input layers results in None shape, preventing use in Dense layer

### ISSUE THREAD

**Issue by edend10** [tensorflow/tensorflow#45054]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Colab
- TensorFlow version (use command below): 2.3
- Python version: 3.6.9
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the current behavior**

Using the Keras functional API, when concatenating together multiple instances of `tensorflow.keras.layers.Input` with `sparse=True`, the resulting `SparseTensor` has a `None` shape (even when `batch_size` is specified). Feeding the merged layer with shape `None` into a dense layer results in an error:
```
ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.
```

**Describe the expected behavior**

Concatenating *non-sparse* instances of `tensorflow.keras.layers.Input` (i.e. `sparse=False`) results in a tensor which has a defined shape (if `batch_size` is specified) and can be fed into a dense layer successfully. Additionally a single sparse input layer has a shape and can be fed into a dense layer. I would expect concatenated sparse input layers to act similarly.

The dense shape of the merged sparse tensor should already be known as we set the shapes of the individual input layers.

**Standalone code to reproduce the issue**

```
sp_a = tf.keras.layers.Input(shape=(1,), batch_size=2, sparse=True)
sp_b = tf.keras.layers.Input(shape=(2,), batch_size=2, sparse=True)

sp_merged = tf.keras.layers.concatenate(inputs=[sp_a, sp_b], axis=1)

print(sp_merged.shape) # prints "(None, None)"

sp_result = tf.keras.layers.Dense(4, activation='relu', name='dense1')(sp_merged) # fails with above ValueError
```

Also tried concatenating with `tf.keras.layers.Concatenate` and `tf.sparse.concat` instead. Same result.

Reproduced success (non-sparse input) and failure (sparse input) cases in Colab:
https://colab.research.google.com/drive/1g9a9lzpw28NqIPI1Z3-fYLJke1fa10Af?usp=sharing

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3, nightly version(`2.5.0-dev20201122`) and was able to reproduce the issue.Please, find the gist [here.](https://colab.research.google.com/gist/ravikyram/d735c0ed788454efba238a30af594edb/untitled532.ipynb) Thanks!

**Comment by fchollet** [comment]
Thanks for the report; looks like a bug.
