### ISSUE TITLE
 Custom loop training of tacotron2 with MultiWorkerMirroredStrategy - Exceptions and failures when use MultiWorkerMirroredStrategy -

### ISSUE THREAD

**Issue by ma-siddiqui** [tensorflow/tensorflow#45056]
When I use tf.distribute.experimental.MultiWorkerMirroredStrategy to run training on multiple machines (custom loop) I face following errors. Please advise when other necessary changes are needed. I am trying to run the training for tacotron2 (https://github.com/TensorSpeech/TensorFlowTTS/blob/master/examples/tacotron2/train_tacotron2.py).

Errors and exceptions are:

2020-11-16 12:03:50,968 (cross_device_ops:1130) INFO: Collective batch_all_reduce for IndexedSlices: 1 all-reduces, group_size = 2
2020-11-16 12:03:56.443402: W tensorflow/core/grappler/optimizers/scoped_allocator_optimizer.cc:439] error: Internal: Complete shape not known for AdamWeightDecay/allreduce/CollectiveReduce_23
2020-11-16 12:03:56.443474: W tensorflow/core/grappler/optimizers/scoped_allocator_optimizer.cc:1121] error: Internal: Complete shape not known for AdamWeightDecay/allreduce/CollectiveReduce_23
2020-11-16 12:03:56.443606: E tensorflow/core/grappler/optimizers/scoped_allocator_optimizer.cc:1138] ScopedAllocatorOptimizer: Internal: Complete shape not known for AdamWeightDecay/allreduce/CollectiveReduce_23

**Comment by amahendrakar** [comment]
@ma-siddiqui,
On running the Python script you have linked, I am facing an error stating `ModuleNotFoundError: No module named 'examples.tacotron2'
`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/85225c4d31a51589c68711d13a45a20f/45056.ipynb). 

In order to expedite the trouble-shooting process, please provide a minimal code snippet to reproduce the issue reported here and the TensorFlow version you are using. Thanks!

**Comment by amahendrakar** [comment]
Also, please take a look at issue [#40277](https://github.com/tensorflow/tensorflow/issues/40277#issuecomment-657824045) which has a similar error log and let us know if it helps. Thanks!

**Comment by ma-siddiqui** [comment]
Hi, any update?

**Comment by amahendrakar** [comment]
> On running the Python script you have linked, I am facing an error stating `ModuleNotFoundError: No module named 'examples.tacotron2' `. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/85225c4d31a51589c68711d13a45a20f/45056.ipynb).
> 
> In order to expedite the trouble-shooting process, please provide a minimal code snippet to reproduce the issue reported here and the TensorFlow version you are using. Thanks!

@ma-siddiqui,
As mentioned earlier, I am facing an error while running the code. Could you please share the Python script/notebook you are running, so that we can reproduce the issue on our end. Thanks!

**Comment by ma-siddiqui** [comment]
Hi,

I am using TensorflowTTS code.


Thanks,

**Comment by amahendrakar** [comment]
> I am using TensorflowTTS code.

@ma-siddiqui,
Could you please share the Python script/notebook you are running, so that we can reproduce the issue on our end? Thanks!
