### ISSUE TITLE
Add support for ragged tensors to tf.keras.layers.experimental.preprocessing.Resizing

### ISSUE THREAD

**Issue by TylerADavis** [tensorflow/tensorflow#45053]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.4.0rc2
- Are you willing to contribute it (Yes/No): Yes, though I am not sure of the best way to implement this

**Describe the feature and the current behavior/state.** tf.keras includes [experimental layers](https://www.tensorflow.org/api_docs/python/tf/keras/layers/experimental/preprocessing) for bringing preprocessing operations, such as resizing, inside the model. Users may want to use this functionality in place of resizing in a `tf.data` pipeline, enabling them to bring in a batch of multiple differently sized images and make them a uniform size. However, `tf.keras.layers.experimental.preprocessing.Resizing` does not currently support RaggedTensors, and as such all inputs within a batch must be the same dimensions.

Attempting to pass in a ragged tensor (as shown below) gives an error. Adding support for ragged tensors would be helpful as it would allow for a batch to contain images of different sizes, thus reducing the need for external preprocessing code.

**Will this change the current api? How?**
Yes, API changes will be required as one or more functions will need to be updated with support for ragged tensors.

The API for `tf.keras.layers.experimental.preprocessing.Resizing` would change, though all existing code using it should continue to work.

Additionally, if the feature is implemented by updating `tf.image.resize` to accept `images` as a ragged tensor instead of only a 4-D Tensor of shape [batch, height, width, channels], this will result in an API change, though it shouldn't be breaking.

**Who will benefit with this feature?**
Users looking to move more of their preprocessing inside their model that want to resize multiple differently sized images in one batch.

**Any Other info.**

Ideal flow (currently failing):

```python
import tensorflow as tf
import numpy as np

a = np.random.rand(512, 512, 3)
b = np.random.rand(1080, 1920, 3)

values = tf.ragged.stack([a, b])
labels = np.asarray([0, 1])

print(values.shape)
# NHWC format
# TensorShape([2, None, None, 3])

print(labels.shape)
# (2,)

# Highly simplified image model
model = tf.keras.models.Sequential()
# The output of this layer will always be (Batch, 224, 224, 3), so adding support for
# ragged tensors shouldn't require updates for downstream ops
model.add(
  tf.keras.layers.experimental.preprocessing.Resizing(
    224,
    224,
    input_shape=(None, None, 3), 
    name="resize"))
model.add(tf.keras.layers.Conv2D(kernel_size=3, filters=24, name="kernel"))
model.add(tf.keras.layers.GlobalMaxPool2D(name="pool"))
model.add(tf.keras.layers.Dense(1, name="dense_second"))

model.compile()

model.fit(values, labels)
```

Error message available in [this gist](https://gist.github.com/TylerADavis/ab693b3d10d618612186f9553c919fbc).

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/27257bb7af0d50b9696000cf0228c5df/45053.ipynb). Thanks!

**Comment by rthadur** [comment]
cc @ymodak

**Comment by jvishnuvardhan** [comment]
@TylerADavis Looks like this was resolved in recent `tf-nightly`. [Here](https://colab.research.google.com/gist/jvishnuvardhan/7009ba0e1039aa3d3a36dbf6134de279/untitled1133.ipynb) is a gist for reference.

Can you please verify once and close the issue if this was resolved for you.

If this was not resolved, can you please open the issue in  [keras-team/keras repo](https://github.com/keras-team/keras/issues) repo as keras development moved to that repo to focus mainly on Keras. Thanks!

**Comment by TylerADavis** [comment]
Thanks! I'll take a look

**Comment by TylerADavis** [comment]
Looks like it works, thanks @jvishnuvardhan !
