### ISSUE TITLE
Model saving using the tf format uses the wrong TensorSpec for convolutions

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/tensorflow#45077]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Yes
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not on mobile device
- TensorFlow installed from (source or binary): Colab
- TensorFlow version (use command below): 2.3
- Python version: 3.6.9
- Bazel version (if compiling from source): Not compiling from source
- GCC/Compiler version (if compiling from source): Not compiling from source
- CUDA/cuDNN version: No GPU
- GPU model and memory: No GPU

**Describe the current behavior**

When saving a subclassed model, using the SavedModel format, the inputs specifications for a convolution layer are not correctly infered.

The error is the following:
```
ValueError: Python inputs incompatible with input_signature:
  inputs: (
    tf.Tensor(
[[[[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  ...

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]]], shape=(1, 32, 32, 1), dtype=float32))
  input_signature: (
    TensorSpec(shape=(None, 96, 96, 1), dtype=tf.float32, name='input_1'))
```

Using the solution from [the documentation on how to specify the signature during export](https://www.tensorflow.org/guide/saved_model#specifying_signatures_during_export) didn't work.

The error I got was the following:
```
AttributeError: 'function' object has no attribute 'get_concrete_function'
```

**Describe the expected behavior**

I would like to be able to save my convolutional model and be able to reuse it on inputs with arbitrary batch size (already the case), width and height (not the case).

**Standalone code to reproduce the issue**
This is [the colab](https://colab.research.google.com/drive/1YBSOmfNMFkmA_t1hyjCA0dG9vUiYxQNt?usp=sharing) I did to illustrate this bug.

**Other info / logs** 

The full stack trace for the inputs spec mismatch is the following:

```
ValueError                                Traceback (most recent call last)
<ipython-input-9-bba6984211c7> in <module>()
----> 1 other_model(tf.ones([1, 32, 32, 1]))

5 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    983 
    984         with ops.enable_auto_cast_variables(self._compute_dtype_object):
--> 985           outputs = call_fn(inputs, *args, **kwargs)
    986 
    987         if self._activity_regularizer:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/utils.py in return_outputs_and_add_losses(*args, **kwargs)
     69     inputs = args[inputs_arg_index]
     70     args = args[inputs_arg_index + 1:]
---> 71     outputs, losses = fn(inputs, *args, **kwargs)
     72     layer.add_loss(losses, inputs=inputs)
     73 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    778       else:
    779         compiler = "nonXla"
--> 780         result = self._call(*args, **kwds)
    781 
    782       new_tracing_count = self._get_tracing_count()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    842       canon_args, canon_kwds = \
    843           self._stateful_fn._function_spec.canonicalize_function_inputs(  # pylint: disable=protected-access
--> 844               *args, **kwds)
    845       # If we did not create any variables the trace we have is good enough.
    846       return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in canonicalize_function_inputs(self, *args, **kwargs)
   2620           inputs,
   2621           self._input_signature,
-> 2622           self._flat_input_signature)
   2623       return inputs, {}
   2624 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _convert_inputs_to_signature(inputs, input_signature, flat_input_signature)
   2711       flatten_inputs)):
   2712     raise ValueError("Python inputs incompatible with input_signature:\n%s" %
-> 2713                      format_error_message(inputs, input_signature))
   2714 
   2715   if need_packing:

ValueError: Python inputs incompatible with input_signature:
  inputs: (
    tf.Tensor(
[[[[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  ...

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   ...
   [1.]
   [1.]
   [1.]]]], shape=(1, 32, 32, 1), dtype=float32))
  input_signature: (
    TensorSpec(shape=(None, 96, 96, 1), dtype=tf.float32, name='input_1'))
```

The full stack trace for the signature specification error is the following:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-12-f5c9e67f3a76> in <module>()
----> 1 call = model.__call__.get_concrete_function(tf.TensorSpec([None, None, None, 1], tf.float32))

AttributeError: 'function' object has no attribute 'get_concrete_function'
```

**Comment by zaccharieramzi** [comment]
Small note, the same problem happens when using the `load` function from the `saved_model` module, i.e. `other_model = tf.saved_model.load('my_model')`.

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/91bff313ec70d32c6b691f4fdb1b0130/untitled471.ipynb)

**Comment by jvishnuvardhan** [comment]
@zaccharieramzi I loaded your model and checked signature as shown below.

```
loaded = tf.keras.models.load_model('my_model')
infer = loaded.signatures["serving_default"]
print(infer.structured_outputs)

# output
{'output_1': TensorSpec(shape=(None, 96, 96, 1), dtype=tf.float32, name='output_1')}
```

So, the loaded model was expecting a signature of (None, 96, 96, 1), while you are providing (None, 32, 32, 1), so the code was throwing an error `ValueError: Python inputs incompatible with input_signature:`.

When I changed inputs to (1, 96, 96, 1) or (2, 96, 96, 1) or any batch_size, it is working as expected. 

Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/149165f921c9a907f570b5555d7e060e/untitled471.ipynb).

Please let me know what you think. Thanks!

**Comment by zaccharieramzi** [comment]
Yes but that's exactly the problem : it shouldn't have this signature because it uses only convolutions.
I should be able to use convolutions on images of arbitrary width and height no matter what I used it on in an arbitrary run (first run or not).
To be explicit I should be able to use the saved model and on both 32×32 and 96×96 images. There is nothing in the convolution operation (both mathematically and in implémentation) preventing me from that and it works perfectly when not using the TF format to save the model.

**Comment by k-w-w** [comment]
Hi Zaccharie, subclassed models automatically save the inputs shapes the first time the model is called. For greater control over the shapes, you should make `call` a `tf.function` with an `input_signature`:

```
class MyModel(tf.keras.models.Model):
  def __init__(self, **kwargs):
    super().__init__(**kwargs)
    self.conv = tf.keras.layers.Conv2D(
        1,
        3,
        padding='same',
    )

  @tf.function(input_signature=[tf.TensorSpec([None, None, None, 1])])
  def call(self, inputs):
    return self.conv(inputs)
```

**Comment by zaccharieramzi** [comment]
@k-w-w hmm that seems like a weird behaviour, but fair enough. Also, your fix does work in this case, thanks!
What I don't understand though is why this error only happens once saved though? Because before I save it, the model works perfectly fine on different image sizes.
