### ISSUE TITLE
Physical devices not shown when I do have one

### ISSUE THREAD

**Issue by CalendulaED** [tensorflow/tensorflow#45072]
I first import TensorFlow and try to find a GPU configure but it shows nothing.
`physical_devices = tf.config.list_physical_devices("GPU")`
![image](https://user-images.githubusercontent.com/68514251/99892785-b91dc180-2c46-11eb-9ad1-0d2173704169.png)

**Comment by Saduf2019** [comment]
@CalendulaED 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

As per the screen shot, you need to find which directory these dlls are in, and then update your PATH to include that directory. Thanks!

Please refer to these issues with same error: #36111, #40804, [link](https://stackoverflow.com/questions/59823283/could-not-load-dynamic-library-cudart64-101-dll-on-tensorflow-cpu-only-install), [link2](https://github.com/tensorflow/tensorflow/issues/44885#issuecomment-727914704)
