### ISSUE TITLE
Missing DLL when importing (but which one?)

### ISSUE THREAD

**Issue by csanadpoda** [tensorflow/tensorflow#45071]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 10 20H2
- TensorFlow installed from (source or binary): pip
- TensorFlow version: 2 (latest as of Nov 22 2020)
- Python version: 3.8
- Installed using virtualenv? pip? conda?: Installed via pip in a conda env
- GPU model and memory: GeForce 1050Ti 4GB

**I run into an issue where I cannot import Tensorflow when using Jupyter from a Conda environment*

**Provide the exact sequence of commands / steps that you executed before running into the problem**
-Fresh Anaconda install
-Fresh C++ redist install
-Create new Conda environment with Python 3.8
-Activate said environment
-Install TF via pip (important, as I need 2.3.0+)
- Install Jupyter notebook
-Open Jupyter notebook
-Try to import TF with `import tensorflow as tf`
-Get error saying I'm missing a DLL, not sure which one

What I noticed and is curious that my _pywrap_tensorflow_internal.py file is completely empty even after multiple reinstalls, and it doesn't matter if I use a brand-new Conda environment or just install on Windows "manually" via pip. Both options make the file empty and I run into this issue.

Trace:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\.conda\envs\wtf\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     63   try:
---> 64     from tensorflow.python._pywrap_tensorflow_internal import *
     65   # This try catch logic is because there is no bazel equivalent for py_extension.

ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-3-6dadb603fc7c> in <module>
      2 import datetime
      3 
----> 4 import tensorflow as tf
      5 import IPython
      6 import IPython.display

~\.conda\envs\wtf\lib\site-packages\tensorflow\__init__.py in <module>
     39 import sys as _sys
     40 
---> 41 from tensorflow.python.tools import module_util as _module_util
     42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
     43 

~\.conda\envs\wtf\lib\site-packages\tensorflow\python\__init__.py in <module>
     38 # pylint: disable=wildcard-import,g-bad-import-order,g-import-not-at-top
     39 
---> 40 from tensorflow.python.eager import context
     41 
     42 # pylint: enable=wildcard-import

~\.conda\envs\wtf\lib\site-packages\tensorflow\python\eager\context.py in <module>
     33 from tensorflow.core.protobuf import config_pb2
     34 from tensorflow.core.protobuf import rewriter_config_pb2
---> 35 from tensorflow.python import pywrap_tfe
     36 from tensorflow.python import tf2
     37 from tensorflow.python.client import pywrap_tf_session

~\.conda\envs\wtf\lib\site-packages\tensorflow\python\pywrap_tfe.py in <module>
     26 
     27 # pylint: disable=invalid-import-order,g-bad-import-order, wildcard-import, unused-import
---> 28 from tensorflow.python import pywrap_tensorflow
     29 from tensorflow.python._pywrap_tfe import *

~\.conda\envs\wtf\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     81 for some common reasons and solutions.  Include the entire stack trace
     82 above this error message when asking for help.""" % traceback.format_exc()
---> 83   raise ImportError(msg)
     84 
     85 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\Users\csana\.conda\envs\wtf\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ravikyram** [comment]
@csanadpoda

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here.](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
.Also, please follow the instructions from to install from [Tensorflow website.](https://www.tensorflow.org/install/source_windows)
Please, check Your CPU/Python is on 32 bits?Please, refer #36167

If the issue still persists please post it on Anaconda repo as we do not support conda environment.
This issue is more suitable on Continuum [Anaconda repo](https://github.com/ContinuumIO/anaconda-issues/issues) since its related to TF installation with Anaconda.
Please post it on [Continuum Anaconda](https://github.com/ContinuumIO/anaconda-issues/issues).
Thanks!
