### ISSUE TITLE
Quantization differences from TensorFlow 1.9 to 2.3

### ISSUE THREAD

**Issue by krworks** [tensorflow/tensorflow#45073]
An issue I found is in regards to INT8 or UINT8 weights on Conv / Dense (trainable) layers during quantization.  Namely, there does not seem to be any way to support UINT8 weights on these layers.  With version 1.9 this was supported as I have implemented my own runtime.  Currently, it seems to only support INT8, Float32, and Float16.  My runtime has to change as a result of this, and it would be nice to know if I am correct in my findings so far on this issue.  I would prefer UINT8 weights on the Conv2D / Dense layers but as mentioned, I cannot see any feasible solution to this problem.  If I am wrong please point me to the correct API usage.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OS X
- TensorFlow installed from (source or binary): 2.3.0 GPU (Docker image)

```

# Example code taken from Post-Training Quantization documentation
# https://www.tensorflow.org/lite/performance/post_training_quantization

import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
def representative_dataset_gen():
  for _ in range(num_calibration_steps):
    # Get sample input data as a numpy array in a method of your choosing.
    yield [input]
converter.representative_dataset = representative_dataset_gen
# there is no such tf.lite.OpsSet.TFLITE_BUILTINS_UINT8
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8  # or tf.int8 ( note this has zero effect on the tensors produced for Conv2D operations -- all of which include signed int8 unless you were to output the model as float16/32 )
converter.inference_output_type = tf.uint8  # or tf.int8
tflite_quant_model = converter.convert()
```

**Comment by amahendrakar** [comment]
@krworks,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by krworks** [comment]
the dataset is simple images where the values range from -1.0 to 1.0 in shape [24, 32, 1]

**Comment by krworks** [comment]
Something that seems relevant here is TFLite implementation details, and the additional quantization capabilities related to INT8/16.  Currently, the quantization of INT8/INT16 supports N quantization parameters for each convolution op where N = filter depth.  The TFLite code states that this is not implemented on UINT8, and it doesn't get into saying if it's actually planned or not.  Since the quantization process is scaling and offsetting the products differently at each filter depth it would not be theoretically as accurate in UINT8 mode with singular set of scale and offset.

There must be reasons why it's not implemented in legacy mode. Perhaps just the existence of UINT8 weights could be used as a legacy switch to not utilize a newer data structure in-format.  At any rate, it would be nice if legacy output could be supported with TFLite export.  It's certainly looks as if it's parsed properly with TFLite library.  With my data I don't see any true performance benefit with the far more complicated quantization process, but perhaps for large models this is very beneficial.

I am implementing this none-the-less, and won't require UINT8.  Any possible way we could support the more simpleton UINT8 format [as well] here?  For the same of comparison, this would be great without rolling back to TF 1.9.

**source from kernel_util.cc:81 in TFLite / TensorFlow r2.3 branch**
```
  const float input_scale = input->params.scale;
  const float output_scale = output->params.scale;
  const float* filter_scales = affine_quantization->scale->data;
  for (int i = 0; i < num_channels; ++i) {
    // If per-tensor quantization parameter is specified, broadcast it along the
    // quantization dimension (channels_out).
    const float scale = is_per_channel ? filter_scales[i] : filter_scales[0];
    const double filter_scale = static_cast<double>(scale);
    const double effective_output_scale = static_cast<double>(input_scale) *
                                          filter_scale /
                                          static_cast<double>(output_scale);
    int32_t significand;
    int channel_shift;
    QuantizeMultiplier(effective_output_scale, &significand, &channel_shift);
    per_channel_multiplier[i] = significand;
    per_channel_shift[i] = channel_shift;
  }
```

**Comment by Saduf2019** [comment]
@krworks 
Could you please let us know if this is still an issue in latest stable TF v2.6.0 ?Thank you!
