### ISSUE TITLE
Management of Gpu memory by fit method to avoid memory errors

### ISSUE THREAD

**Issue by eaedk** [tensorflow/tensorflow#45081]
**System information**
- Colab GPU kernel (Tf : 2.3.0 , GPUs Available : 1)

**Describe the current behavior**
There are memory errors when:
- I fit models with huge value for batch size ;
- I fit CNN models with large images ;

**Describe the expected behavior**
Update the fit method so that the training of models can according to the memory available on the GPU and automatically define the best mini-batch size (split the batch into several parts) to avoid the memory errors so that users no longer have to reduce batch size or image size.
For large images, the fit method should be able to split the image into several parts to try to reduce the risk of memory errors.

**Comment by Saduf2019** [comment]
@eaedk 
Please share simple stand alone code for us to replicate the issue faced, or if possible share a colab gist with the error reported.

**Comment by eaedk** [comment]
https://colab.research.google.com/drive/13m4NSY5f5UUwIsvyTie_UejqNNmMXVrU?usp=sharing

**Comment by eaedk** [comment]
![Screenshot from 2020-11-27 16-40-25](https://user-images.githubusercontent.com/28601730/100470032-58233d00-30cf-11eb-98d6-5621f38d0432.png)
 above you can see the error when I try to apply transfer learning on Resnet50V2 with batch_size = 32 and input_size = (720, 720, 3) .

**Comment by eaedk** [comment]
when I reduce the batch size, there is no more this error. so I want an update of the fit method that will be able to find automatically the best mini-batch to split my inference by its . Then we'll no more have RessourceExhaustedError and we'll have more simplicity to train big architectures, architectures with large batch size, or architectures with large inputs. It will help us to have better models

**Comment by nikitamaia** [comment]
Hi @eaedk, trying to better understand the request here. Are you proposing a feature request to automatically determine the largest batch size that will fit in memory?

**Comment by eaedk** [comment]
Hi @nikitamaia, what I want is that whatever the bigger batch_size the Gpu could automatically compute the batch by many min-batch of a well-determined size to avoid memory error . 

I'm a french-speaking and sometimes I have some difficulties to explain idea... so I repeat, if it isn't clear yet.

what I want is that whatever the size of the batch that we set, the GPU can split it into several small batches to process so as to avoid memory errors due to the size of the batch being too large.

**Comment by eaedk** [comment]
## 🚀 Feature
Ensure that models can according to the memory available on the GPU during a feed-forward, automatically split the sent batch into several small mini_batches to avoid the memory errors. 

## Motivation
So that during the training, users no longer have to reduce batch_size (or image size in case of image). The training will just take time but any users could train models any batch_size without check manually the good size for mini_batch.
During inference also, user could just pass a big batch_size and the framework will automatically define the best number of sample to passe to don't have memory errors anymore.

## Pitch

what I want is that whatever the size of the batch that we set, the GPU can split it into several small batches to process so as to avoid memory errors due to the size of the batch being too large.

**Comment by jvishnuvardhan** [comment]
@eaedk Sorry for the late response. Can you please share a simple standalone code to reproduce the issue or share the data? 

When you run a model in a `for` loop, keras will take more memory to keep those models in the memory. Did you try releasing the memory https://www.tensorflow.org/api_docs/python/tf/keras/backend/clear_session. Thanks
