### ISSUE TITLE
Create makefile targets to expose file lists to enable separate scripting

### ISSUE THREAD

**Issue by petewarden** [tensorflow/tensorflow#45086]
As the first step in the project generation process described in https://docs.google.com/document/d/1gfbpBtiivYMenCDIvJb-m5RIV4rKAR5dvdAJC5LLv8o/edit?usp=sharing we need to expose the file lists held within the makefile through an API. This bug is to track the work involved in that process.

**Comment by advaitjain** [comment]
https://github.com/tensorflow/tensorflow/issues/44909 is a similar bug that we have closed in favor of the current bug.

**Comment by advaitjain** [comment]
closing the current bug in favor of https://github.com/tensorflow/tensorflow/issues/47413
