### ISSUE TITLE
worker go to endless loop when ps send a UnavailableError to worker.

### ISSUE THREAD

**Issue by zhaozheng09** [tensorflow/tensorflow#45088]
TF version: tf1.15 & master
I want to implement a small function that is worker blacklist in ps.
PS check worker-blacklist when worker create session on ps.
If PS find an unexpected worker, ps return a errors.UnavailableError to this worker, then refused worker go to endless loop(bug).

I check codes and logs, I find a while(True) when worker recv errors.UnavailableError.
**I think worker should have max retry time and sleep when worker recv errors.UnavailableError.(pr)**
of course, I will add retrun permission error when ps frequently recv new connection from refused worker .
pseudo code:https://github.com/zhaozheng09/tensorflow/pull/1/files

Should we change endless-loop to max_retry-loop when worker create session ?

**Comment by amahendrakar** [comment]
@zhaozheng09,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here along with the dataset you are using. Thanks!

**Comment by zhaozheng09** [comment]
@amahendrakar Ok.

**Comment by zhaozheng09** [comment]
It is not too easy for me to run v2.3, so first I want to ask :
What should the worker do when the worker keeps receiving retry requests?
1. Infinite retry.
2. max_retry_times.

**Comment by zhaozheng09** [comment]
I reproduced in v2.3
PS changed:
I add a line that `s = errors::Unavailable("Fake a UnavailableError when create session .");` for simulating Ps return a UnavailableError when worker try to create session in ps.

then worker in endless-loop, logs like:
`I1125 09:47:04.864392 140107344144192 monitored_session.py:246] Graph was finalized.
INFO:tensorflow:Restoring parameters from ./log_dir/202011101457/model.ckpt-0
I1125 09:47:04.865339 140107344144192 saver.py:1293] Restoring parameters from ./log_dir/202011101457/model.ckpt-0
INFO:tensorflow:An error was raised while a session was being created. This may be due to a preemption of a connected worker or parameter server. A new session will be created. This error may also occur due to a gRPC failure caused by high memory or network bandwidth usage in the parameter servers. If this error occurs repeatedly, try increasing the number of parameter servers assigned to the job. Error: **Fake a UnavailableError when create session .**
Additional GRPC error information from remote target /job:ps/replica:0/task:0:
:{"created":"@1606268824.888877822","description":"Error received from peer ipv4:127.0.0.1:9282","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Fake a UnavailableError when create session .","grpc_status":14}
I1125 09:47:04.896030 140107344144192 monitored_session.py:1246] An error was raised while a session was being created. This may be due to a preemption of a connected worker or parameter server. A new session will be created. This error may also occur due to a gRPC failure caused by high memory or network bandwidth usage in the parameter servers. If this error occurs repeatedly, try increasing the number of parameter servers assigned to the job. Error: Fake a UnavailableError when create session .
Additional GRPC error information from remote target /job:ps/replica:0/task:0:
:{"created":"@1606268824.888877822","description":"Error received from peer ipv4:127.0.0.1:9282","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Fake a UnavailableError when create session .","grpc_status":14}
INFO:tensorflow:Graph was finalized.
I1125 09:47:04.896190 140107344144192 monitored_session.py:246] Graph was finalized.
INFO:tensorflow:Restoring parameters from ./log_dir/202011101457/model.ckpt-0
I1125 09:47:04.897225 140107344144192 saver.py:1293] Restoring parameters from ./log_dir/202011101457/model.ckpt-0
INFO:tensorflow:An error was raised while a session was being created. This may be due to a preemption of a connected worker or parameter server. A new session will be created. This error may also occur due to a gRPC failure caused by high memory or network bandwidth usage in the parameter servers. If this error occurs repeatedly, try increasing the number of parameter servers assigned to the job. Error: **Fake a UnavailableError when create session .**`

**Comment by zhaozheng09** [comment]
Happy Thanksgiving~ @all

**Comment by amahendrakar** [comment]
> I add a line that `s = errors::Unavailable("Fake a UnavailableError when create session .");` for simulating Ps return a UnavailableError when worker try to create session in ps.

@zhaozheng09,
Could you please provide a minimal code snippet so that we can reproduce this error on our end? Thanks!

**Comment by zhaozheng09** [comment]
I try, thanks.

**Comment by amahendrakar** [comment]
@zhaozheng09,
Thank you for the update. Marking the issue as closed, please feel free to re-open if necessary.
