### ISSUE TITLE
Tensorflow 2. x not recognizing RTX 3090 GPU

### ISSUE THREAD

**Issue by Thunder003** [tensorflow/tensorflow#45089]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version: 2.2 / 2.3/ 2.5.0.dev20201028
- Python version: 3.8
- Installed using virtualenv? pip? conda?: Pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.1/8.0.4
- GPU model and memory: RTX 3090

I have installed T.F. 2.2 using conda install -C anaconda TensorFlow-gpu, it is installed properly but it is not able to recognize the GPU, I have checked using:-

from tensorflow.python.client import device_lib
device_lib.list_local_devices()

It gives output CPU only.

I have also checked by installing T.F. 2.3 and 2.5 nightly build using pip install but all of them are failed to recognize GPU. Does anyone know the cause and solution?

**Comment by houcze** [comment]
try cuda10.1 and cudnn7.6.5 or compiling from source

**Comment by Thunder003** [comment]
@houcze 3090 has Ampere architecture, CUDA 10.1 is incompatible.

**Comment by ravikyram** [comment]
@Thunder003 

Please, see tested build configurations from [here](https://www.tensorflow.org/install/source#gpu).

Current tf-nightly version supports cuda 11.0
If you are okay with unstable version (tf-nightly) you can give it a try or wait for upcoming stable TF 2.4 release.Thanks!

**Comment by Thunder003** [comment]
@ravikyram I have tried CUDA 11 on RTX 3090 but it throws sm_86 error with CUDA 11. I think only 11.1 works on it. 
And I tried 11.1 + TF 2.5.0.dev20201028, it hasn't detected the GPU

**Comment by king398** [comment]
Have you added the correct CUDA And CuDnn path in the console. I recommend you check that. 
`
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin;%PATH%
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\extras\CUPTI\lib64;%PATH%
SET PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include;%PATH%
SET PATH=C:\tools\cuda\bin;%PATH%`
this folder can be changes according to where you have installed cuda and CuDNN. Just make sure to include all the sub folders such as extras and bin

**Comment by Thunder003** [comment]
@king398 in your case does 

**from tensorflow.python.client import device_lib
device_lib.list_local_devices()**

gives the output a list having GPU also?

**Comment by king398** [comment]
Yes it does and also trains my own network.
Is the fix working

**Comment by Thunder003** [comment]
@king398 , Thanks for sharing the code output, I was just confirming if it was a code issue. 
I'll try to add a path and give an update here. 

I'm using Linux and will share the screenshot of PATH.

**Comment by king398** [comment]
It should be somewhat like this:
![image](https://user-images.githubusercontent.com/58468909/99967221-8cd88100-2dbd-11eb-8509-47b67ac5466c.png)

**Comment by ymodak** [comment]
Also see https://github.com/tensorflow/tensorflow/issues/43718#issuecomment-711057497

**Comment by Thunder003** [comment]
@king398 @ymodak thanks, ....my issue is resolved. It was a docker image problem, I was using docker which had drivers compatible with CUDA 10.

**Comment by MuhsinFatih** [comment]
`pip install tensorflow==2.5.0-rc1` worked for me
