### ISSUE TITLE
manylinux2010 compatible libtensorflow for TF 2.x

### ISSUE THREAD

**Issue by VivekPanyam** [tensorflow/tensorflow#45092]
The official TF 2.x libtensorflow binaries for linux are built in a manylinux2010 sysroot only when using CUDA.

https://github.com/tensorflow/tensorflow/blob/fcc4b966f1265f466e82617020af93670141b009/tensorflow/tools/ci_build/builds/libtensorflow.sh#L54-L59

Ideally CPU libtensorflow builds would be built in a manylinux2010 compatible way as well.

Happy to put up a PR if this makes sense.

**Comment by mihaimaruseac** [comment]
This is likely an oversight from our side. Happy to review the PR, thank you for the issue report.
