### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib.keras.python'

### ISSUE THREAD

**Issue by chens72** [tensorflow/tensorflow#45094]
When I run the following code, I met the error as written above
`from tensorflow.contrib.keras.python.keras.initializers import TruncatedNormal`  
Is this bug caused by the tensorflow version?

**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): tensorflow -gpu1.14.0
- Python version: 3.6

**Comment by amahendrakar** [comment]
@chens72,
Could you please share the output of the below code with us?

```
import tensorflow as tf
print(tf.__version__)
```

Also `tensorflow.contrib` exists only in TensorFlow 1.x, which is not actively supported anymore. We'd recommend you to update TensorFlow to the latest stable version v2.3. Thanks!

**Comment by chens72** [comment]
Thank you. But after I  update TensorFlow to the  version v2.3, I met the error：
ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by hfahrudin** [comment]
Hello @chens72, try to import it this way `from tensorflow.keras.initializers import TruncatedNormal`. As @amahendrakar  said, tf v2.+ remove `tensorflow.contrib` . Hope it can help!

**Comment by chens72** [comment]
Yes，it works. Thank you very much!
