### ISSUE TITLE
Failed to build wheel on MacOS Big Sur

### ISSUE THREAD

**Issue by markub3327** [tensorflow/tensorflow#45095]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Big Sur 11.0.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NONE
- TensorFlow installed from (source or binary): source
- TensorFlow version: latest from tensorflow:master
- Python version: 3.8.2
- Installed using virtualenv? pip? conda?: NONE
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): Apple clang version 12.0.0 (clang-1200.0.32.27)
- CUDA/cuDNN version: NONE
- GPU model and memory: NONE

Hello, 

after successfuly compiled tensorflow by the Bazel, I try to make a wheel file. I used './bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg', but the result folder /tmp/tensorflow_pkg didn't exist. I send screenshot with output from building wheel.

<img width="1074" alt="Snímka obrazovky 2020-11-23 o 10 04 34" src="https://user-images.githubusercontent.com/74611856/99944598-71488880-2d73-11eb-9d04-550bce91f38c.png">
<img width="1074" alt="Snímka obrazovky 2020-11-23 o 10 04 49" src="https://user-images.githubusercontent.com/74611856/99944607-74437900-2d73-11eb-81fe-48cc9d9f87dc.png">

**Comment by ymodak** [comment]
Did you try Apple released forked version of [TensorFlow optimized](https://github.com/apple/tensorflow_macos) for macOS Big Sur?

**Comment by markub3327** [comment]
No, I used your instructions to build it for MacOS: https://www.tensorflow.org/install/source

**Comment by ymodak** [comment]
Since issue title says building pip package failed and you are using instructions for building from source.
Were able to use `pip install` to build TF on your system?.
Also you may want to give it a try to build from apple released TF version, optimized for macOS Big Sur at the moment.

**Comment by markub3327** [comment]
Sorry my english is so bad. I have a trouble with building pip's wheel from source. And, I tried `pip install` too. The result was: 

> ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
> ERROR: No matching distribution found for tensorflow

<img width="918" alt="Snímka obrazovky 2020-11-25 o 8 58 50" src="https://user-images.githubusercontent.com/74611856/100198795-9ae0eb80-2efc-11eb-816f-d3612498a41d.png">

**Comment by mihaimaruseac** [comment]
#45120

**Comment by mihaimaruseac** [comment]
Also, please don't post screnshoots, post the actual error/code. Easier to search, easier to reference, easier for accessibility reasons too.

**Comment by markub3327** [comment]
I sent you only part of my screen that contains the error and nothing else. Okay, but when I didn't found a wheel, I intuitively a try to build my own wheel by instructions posted here: https://www.tensorflow.org/install/source .... Thanks.

**Comment by mizabrik** [comment]
I am having the same issue, here is the text version of logs:
```
Fri Nov 27 17:59:17 MSK 2020 : === Preparing sources in dir: /var/folders/j1/x3dxynqd187gm7w_lccw0h880000gn/T/tmp.XXXXXXXXXX.yybbrD8N
~/tensorflow ~/tensorflow
~/tensorflow
~/tensorflow/bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow ~/tensorflow
~/tensorflow
/var/folders/j1/x3dxynqd187gm7w_lccw0h880000gn/T/tmp.XXXXXXXXXX.yybbrD8N/tensorflow/include ~/tensorflow
~/tensorflow
sed: /var/folders/j1/x3dxynqd187gm7w_lccw0h880000gn/T/tmp.XXXXXXXXXX.yybbrD8N/tensorflow/__init__.py: in-place editing only works for regular files
```
The file, mentioned in logs, is a symlink into `bazel-out`; forcing `cp` to follow symbolic links solves the problem for me.

Here is a patch: [build_pip_package.txt](https://github.com/tensorflow/tensorflow/files/5608469/build_pip_package.txt).

**Comment by markub3327** [comment]
I have been trying Apple released forked version of TensorFlow optimized for macOS Big Sur with result:

`Successfully installed appnope-0.1.0 backcall-0.2.0 decorator-4.4.2 ipython-7.19.0 ipython-genutils-0.2.0 jedi-0.17.2 parso-0.7.1 pexpect-4.8.0 pickleshare-0.7.5 prompt-toolkit-3.0.8 ptyprocess-0.6.0 pygments-2.7.2 traitlets-5.0.5 wcwidth-0.2.5`
`Processing /var/folders/sl/sgly1pz10_517l3vv7x98l3w0000gn/T/tmp.kE3Qlunc/tensorflow_macos/x86_64/tensorflow_macos-0.1a0-cp38-cp38-macosx_11_0_x86_64.whl`
`Installing collected packages: tensorflow-macos`
`Successfully installed tensorflow-macos-0.1a0`

**Comment by mihaimaruseac** [comment]
We cannot support the private forks.

**Comment by mihaimaruseac** [comment]
#45404 will make this repo compile on the M1 chips. Until that lands, the support has to come from the Apple fork.

**Comment by markub3327** [comment]
I don't have MacBook with M1 chip, I'm using only MacBook Air Retina 2018 with Intel Core i5.

**Comment by mihaimaruseac** [comment]
But then you don't need to use the Apple fork. That one is for the M1/ARM chips.

**Comment by mihaimaruseac** [comment]
Finally managed to see the images (you should have really posted the error message as text, not as image).

The error is clear in the first screenshot:

```
in-place editing only works for regular files
```

This results in a crash during the pip package creation as `sed` crashes. This is why you don't have the wheel.

Do you have a symlink at that path?

**Comment by markub3327** [comment]
Sorry, I don't know I do nothing with `sed`. I only follow these steps:

0. 
1. pip3 install -U --user pip numpy wheel
    pip3 install -U --user keras_applications --no-deps
    pip3 install -U --user keras_preprocessing --no-deps
2. Install Bazel
3. git clone https://github.com/tensorflow/tensorflow.git
4. cd tensorflow
5. ./configure
6. bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-msse4.2 //tensorflow/tools/pip_package:build_pip_package
7. ./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg (only in this step was the trouble ....)

This was working on MacOS Mojave, but after the upgrade to newer MacOS Big Sur something is wrong or not compatible.

**Comment by mihaimaruseac** [comment]
The last step does a `sed` during build. `sed` on MacOS does not support in-place editing on symbolic links. Can you try passing a different argument, instead of `/tmp/tensorflow_pkg`? For example `./tf_pkg`?

**Comment by markub3327** [comment]
The error is same:

`tensorflow-2.4.0 % ./bazel-bin/tensorflow/tools/pip_package/build_pip_package ./tf_pkg                                                        
št 31. december 2020 14:01:37 CET : === Preparing sources in dir: /var/folders/hn/5hk6gn6s6gv4n54vh80rrzkw0000gn/T/tmp.XXXXXXXXXX.4nbX7Iod
~/Projects/tensorflow-2.4.0 ~/Projects/tensorflow-2.4.0
~/Projects/tensorflow-2.4.0
~/Projects/tensorflow-2.4.0/bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow ~/Projects/tensorflow-2.4.0
~/Projects/tensorflow-2.4.0
/var/folders/hn/5hk6gn6s6gv4n54vh80rrzkw0000gn/T/tmp.XXXXXXXXXX.4nbX7Iod/tensorflow/include ~/Projects/tensorflow-2.4.0
~/Projects/tensorflow-2.4.0
sed: /var/folders/hn/5hk6gn6s6gv4n54vh80rrzkw0000gn/T/tmp.XXXXXXXXXX.4nbX7Iod/tensorflow/__init__.py: in-place editing only works for regular files`

**Comment by mihaimaruseac** [comment]
It's weird that it's still looking for a path in `.../T/tmp...`.

**Comment by markub3327** [comment]
Yes I think too.

**Comment by mihaimaruseac** [comment]
Exists, but is a symbolic link. On macos, `sed` does not work on symbolic links.

**Comment by markub3327** [comment]
Oh, yes of course, but what with it can I do?

I compile my own variant of TF with enabled instruction sets for my CPU.

> 2021-01-03 22:05:28.862745: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

**Comment by mihaimaruseac** [comment]
[These are the `sed` commands that get executed](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/tools/pip_package/build_pip_package.sh;l=214-223;drc=71313bcb180f2220adee93d964bc4721ad6bf575).

You could remove them, it seems it is only for some autocomplete. Alternatively, you could change them to not do inplace replacement.

The person that wrote that code no longer works on TF, so it will take a while until we can get a proper fix.

**Comment by markub3327** [comment]
I have a proper solution .... Can I create PR?

In cp must be used '-L' option (always follow symbolic links in SOURCE).

[build_pip_package.sh](https://github.com/tensorflow/tensorflow/files/5762630/build_pip_package.sh.txt)

**Comment by mihaimaruseac** [comment]
That's awsome. Yes, please make a PR. Please tag me in the PR.
