### ISSUE TITLE
installation of any version on python 3.9 and installation of v1.x on python 3.8

### ISSUE THREAD

**Issue by muayyad-alsadi** [tensorflow/tensorflow#45097]
**System information**
- OS Platform and Distribution: Fedora 32 and Fedora 33
- TensorFlow installed from (source or binary): pip/wheel
- TensorFlow version: any
- Python version: python 3.9 on Fedora 33 and python 3.8 on Fedora 32

**Describe the problem**

No version at all available for python 3.9

```
$ python3 --version
Python 3.9.0
$ pip3 install --user tensorflow
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```

no 1.x available on python 3.8

```
$ python3 --version
Python 3.8.3
$ pip3 install --user tensorflow==1.15
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2)
ERROR: No matching distribution found for tensorflow==1.15

```

**Provide the exact sequence of commands / steps that you executed before running into the problem**

above

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

above

**Comment by amahendrakar** [comment]
@muayyad-alsadi,
> No version at all available for python 3.9

The request for TensorFlow support on Python 3.9 is already being tracked in [#44485](https://github.com/tensorflow/tensorflow/issues/44485).

> no 1.x available on python 3.8

And yes, TensorFlow 1.x is not supported on Python 3.8. The lastest Python version to support TensorFlow 1.x is Python v3.7. 


Version | Python version | Compiler | Build tools
-- | -- | -- | --
tensorflow-1.15.0 | 2.7, 3.3-3.7 | GCC 7.3.1 | Bazel 0.26.1
tensorflow-1.14.0 | 2.7, 3.3-3.7 | GCC 4.8 | Bazel 0.24.1

For more information, please take a look at the [tested build configuration](https://www.tensorflow.org/install/source#tested_build_configurations). Thanks!

**Comment by mihaimaruseac** [comment]
As mentioned in https://github.com/tensorflow/tensorflow/issues/44485#issuecomment-720675069, we cannot release an older version of TF with support for newer Python. The build system is too complex and any addition to the matrix is prone to create hard to debug bugs.

Py3.9 is tracked in #44485

**Comment by amahendrakar** [comment]
@muayyad-alsadi,
Any updates regarding this? Please feel free to close the issue if resolved. Thanks!
