### ISSUE TITLE
How to save a keras.Model with an embedded hub.KerasLayer ?

### ISSUE THREAD

**Issue by RobRomijnders** [tensorflow/tensorflow#45096]
**System information**
- Have I written custom code: No
- OS Platform and Distribution: [Google Colab](https://colab.research.google.com/drive/18VmYP7Q5GmdToZCX3mx5Msmby0WfEMRE?usp=sharing)
- TensorFlow installed from (source or binary): [Google Colab](https://colab.research.google.com/drive/18VmYP7Q5GmdToZCX3mx5Msmby0WfEMRE?usp=sharing)
- TensorFlow version (use command below): 2.3.0
- Python version: 3.7

**Describe the current behavior**
Method 1
```python
model = tf.keras.Sequential([
    hub.KerasLayer("https://tfhub.dev/google/bit/s-r50x1/1"),
])

model.build(input_shape=(None, 224, 224, 3))
model.save("/tmp")
# Success
```

Method 2
```python
class DummyModel(tf.keras.Model):

  def __init__(self):
    super(DummyModel, self).__init__()
    self.model = hub.KerasLayer("https://tfhub.dev/google/bit/s-r50x1/1")

  def call(self, inputs):
    return self.model(inputs)


model = DummyModel()
model.build((None, 224, 224, 3))
model.save("/tmp")
# Error
```

**Describe the expected behavior**
How can I properly build a Model with an embedded KerasLayer? 

Method 1 succeeds, but method 2 fails with `ValueError: Model cannot be saved because the input shapes have not been set.`

This is a minimized version. I explicitly need a design like method #2 for my more complicated problem.

**Standalone code to reproduce the issue**
[Google Colab](https://colab.research.google.com/drive/18VmYP7Q5GmdToZCX3mx5Msmby0WfEMRE?usp=sharing)

**Comment by Saduf2019** [comment]
@jvishnuvardhan 
I am able to replicate the issue on nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/b90bf04f9528bb76bf78946a3982d8df/untitled468.ipynb).

**Comment by RobRomijnders** [comment]
Update from my side:

`model._set_inputs(tf.keras.Input(shape=[None, None, 3]))` solves the issue for me.

This fix feels weird though. Python recommends using _method only for private purposes, and this issue feels like a common situation. So I wonder if there exists a proper solution?

**Comment by monicadsong** [comment]
Hi--

The message that you get "ValueError:DummyModel cannot be saved because the input shapes have not been set. Usually, input shapes are automatically determined from calling `.fit()` or `.predict()`. To manually set the shapes, call `model.build(input_shape)`." is confusing since `build` does not work.

If you follow the recommendation to `fit` or `predict`, then you can save successfully. Here I have "called" it before saving, which works:
```
model = DummyModel()
z = tf.zeros([1, 224, 224, 3])
model(z)
model.save("/tmp")
```

**Comment by jvishnuvardhan** [comment]
@RobRomijnders Agree with you @monicadsong. 
We need to call the model on some data to determine the shapes of different layers which is required for initializing model weights and biases before saving the model. This approach (calling the model) is specific to subclass model. Please check the example given in one of [the tutorial](https://www.tensorflow.org/guide/keras/save_and_serialize) on TF website.

```
class CustomModel(keras.Model):
    def __init__(self, hidden_units):
        super(CustomModel, self).__init__()
        self.dense_layers = [keras.layers.Dense(u) for u in hidden_units]

    def call(self, inputs):
        x = inputs
        for layer in self.dense_layers:
            x = layer(x)
        return x


model = CustomModel([16, 16, 10])
# Build the model by calling it
input_arr = tf.random.uniform((1, 5))
outputs = model(input_arr)
model.save("my_model") 
```

I am closing this issue as it was resolved. Please feel free to reopen if I am mistaken. thanks!

**Comment by RobRomijnders** [comment]
Thanks for answering!
