### ISSUE TITLE
MNIST tutorial data cant be downloaded (404)

### ISSUE THREAD

**Issue by AdrianLoer** [tensorflow/tensorflow#451]
Hey, tried to work my way through tf but the download link seems down

https://tensorflow.googlesource.com/tensorflow/+/master/tensorflow/g3doc/tutorials/mnist/input_data.py

404s

**Comment by vrv** [comment]
The file was moved to tensorflow/examples/tutorials/mnist/input-data.py -- I think our website hasn't updated yet.

You might want to consider just git cloning the repository instead of downloading files individually.
