### ISSUE TITLE
ValueError: Input tensors to a Functional must come from `tf.keras.Input`. Received: 0 (missing previous layer metadata).

### ISSUE THREAD

**Issue by MTeja1991** [tensorflow/tensorflow#45105]
from tensorflow.keras import backend as K
get_activations = K.function([model.layers[0].input,model.layers[1].input,model.layers[2].input,model.layers[3].input, K.learning_phase()],[model.layers[layer_idx].output,])

TF 2.3.1

Windows 10 in anaconda python 3.8 environment

Got error while executing(four stream architecture)
ValueError: Input tensors to a Functional must come from `tf.keras.Input`. Received: 0 (missing previous layer metadata).

**Comment by hfahrudin** [comment]
@MTeja1991 could you provide us more context so we can reproduce the error? I am curious about about this `model` object.

**Comment by Saduf2019** [comment]
@MTeja1991 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]
