### ISSUE TITLE
TFLiteConverter.from_saved_model runs on an error

### ISSUE THREAD

**Issue by SerQuicky** [tensorflow/tensorflow#45103]
**System information**
- using colab

**Command used to run the converter or code if you’re using the Python API**

Trained model:
https://colab.research.google.com/drive/1PRuBCtkp8WIQn66IbGjgvfr-kLMpA3P5?usp=sharing (just in case you want to see, that the model actually works)

Colab with the tfLite-Converter:
https://colab.research.google.com/drive/1up5goKZLY6rfTTt98mg7KRqZoUAeEaIO?usp=sharing

```
model_dir="./saved_model"
converter = tf.lite.TFLiteConverter.from_saved_model(model_dir)
tflite_model = converter.convert()
open('detect.tflite','wb').write(tflite_model)
```

**The output from the converter invocation**

```
ValueError: None is only supported in the 1st dimension. Tensor 'image_tensor' has invalid shape '[None, None, None, 3]'.
```

**Also, please include a link to the saved model or GraphDef**

```
https://github.com/SerQuicky/shoe-dataset/tree/master/models/stock_shoe_model
```

**Any other info / logs**

Hello guys, I actually trained a Mobilenet SSD v1 model and it works fine in Colab (test it through the first Colab link).
Now I am trying to convert the model to a tflite model so I can use it on my android phone.

I am using tensorflow version 1.15.0. The [documentation](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/lite/TFLiteConverter) has an example for the conversion from a saved model to tflite, sadly it does not work.   

Complete stacktrace

```
ValueError                                Traceback (most recent call last)
<ipython-input-10-40156df8e12f> in <module>()
      8 #converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
      9 
---> 10 tflite_model = converter.convert()
     11 open('detect.tflite','wb').write(tflite_model)

/tensorflow-1.15.2/python3.6/tensorflow_core/lite/python/lite.py in convert(self)
    894               "None is only supported in the 1st dimension. Tensor '{0}' has "
    895               "invalid shape '{1}'.".format(
--> 896                   _get_tensor_name(tensor), shape_list))
    897         elif shape_list and shape_list[0] is None:
    898           self._set_batch_size(batch_size=1)

ValueError: None is only supported in the 1st dimension. Tensor 'image_tensor' has invalid shape '[None, None, None, 3]'.
```

**Comment by amahendrakar** [comment]
@SerQuicky,
I do not have access to the links you have provided. Could you please provide the required permissions to view the files. 

Also, TensorFlow 1.x is not actively supported. Please update TensorFlow to v2.3 and check if you are facing the same issue. Thanks!

**Comment by SerQuicky** [comment]
@amahendrakar sorry for the mistake, I have updated the links. Can I convert a model that I trained with tf v1.x  with tf v2.3+ ? Or should I train it again, but with tf v2.3?

**Comment by SerQuicky** [comment]
I will close the issue, because I tried the process under tf 1.15.0. I am currently trying to run it under tf 2.3. Thanks for the information so far.
