### ISSUE TITLE
Tensorflow 2.x can't feed data with non-uniform shapes to a multi-input multi-output model

### ISSUE THREAD

**Issue by CXYCarson** [tensorflow/tensorflow#45112]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.3.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
There are currently no documentations on feeding data with non-uniform shape to a multi-input multi-output model with a tf.data.dataset.generator. When I tried to do so, I will receive such an error: `Data is expected to be in format x, (x,), (x, y), or (x, y, sample_weight)`.

Because each piece of data has the shape of (None,5), it is not possible to convert it to numpy arrays, which can be easily feed into the model. Moreover, tf.ragged_tensor can't be fed into the model, so I couldn't figure out a way to feed my data. I understand I can probably solve this with paddings, but that's going to be my last choice. Is there a way to feed data with non-uniform shape to a multi-input multi-output model regardless of what method being used?

Thanks to all in advance!

Here's the code to reproduce my issues:

```
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

dummy_1 = [[[1.1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]],
           [[1.2,2,3,4,5],[2,3,4,5,6.8]],
           [[1.3,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8.9]]]

dummy_2 = [[[1.1,2,3,4,5],[2,3,4,5,6]],
           [[1.1,2,3,4,5],[2,3,4,5,6]],[3,4,5,6,7],
           [[1.3,2,3,4,5],[2,3,4,5,6]]]

dummy_3 = [[[1.5,2,3,4,5],[2,3,4,5,6]],
           [[1.6,2,3,4,5],[2,3,4,5,6]],[3,4,5,6,7],
           [[1.7,2,3,4,5],[2,3,4,5,6]]]

def gen():
    for i in range(len(dummy_1)):
        yield(dummy_1[i],dummy_2[i],dummy_2[i],dummy_3[i])

def custom_loss(y_true, y_pred):
    return tf.reduce_mean(tf.abs(y_pred - y_true))

class network():
    def __init__(self):
        input_1 = keras.Input(shape=(None,5))
        input_2 = keras.Input(shape=(None,5))
        output_1 = layers.Conv1DTranspose(16, 3, padding='same', activation='relu')(input_1)
        output_2 = layers.Conv1DTranspose(16, 3, padding='same', activation='relu')(input_2)

        self.model = keras.Model(inputs=[input_1, input_2],
                                 outputs=[output_1, output_2])
        
        # compile model
        self.model.compile(optimizer=keras.optimizers.SGD(learning_rate=0.001),
                           loss={"mel_loss":custom_loss, "mag_loss":custom_loss})
    
    def train(self):
        self.dataset = tf.data.Dataset.from_generator(gen, 
                                                      (tf.float32, tf.float32, tf.float32, tf.float32))
        self.dataset.batch(32).repeat()
        self.model.fit(self.dataset,epochs=3)
        #self.model.fit([dummy_1, dummy_2],
        #               [dummy_2, dummy_3],
        #               epochs=3)

net = network()
net.train()
```

**Will this change the current api? How?**
Yes, if there are currently no support for feeding data with non-uniform shape to a multi-input multi-output model.

**Who will benefit with this feature?**
People who are working with time-series data that has an inconsistent dimension that represent the timesteps.

**Any Other info.**

**Comment by rmothukuru** [comment]
@CXYCarson,
Can you try building the `Dataset` using `tf.data.Dataset.from_tensor_slices` as shown in [Building Datasets with ragged tensors](https://www.tensorflow.org/guide/ragged_tensor#building_datasets_with_ragged_tensors) and see if it works. Thanks!

**Comment by CXYCarson** [comment]
I tried your method and I can create a `Dataset` with ragged tensors. But the model could not be fed with the ragged tensors. The error message is: `TypeError: object of type 'RaggedTensor' has no len()`
The code to reproduce the error is here:
```
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

class network():
    def __init__(self):
        input_1 = keras.Input(shape=(None,5))
        input_2 = keras.Input(shape=(None,5))
        output_1 = layers.Conv1DTranspose(16, 3, padding='same', activation='relu')(input_1)
        output_2 = layers.Conv1DTranspose(16, 3, padding='same', activation='relu')(input_2)

        self.model = keras.Model(inputs=[input_1, input_2],
                                 outputs=[output_1, output_2])
    
    def train(self):
        dummy_1 = tf.ragged.constant([[[1.1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]],
                   [[1.2,2,3,4,5],[2,3,4,5,6.8]],
                   [[1.3,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8.9]]])

        dummy_2 = tf.ragged.constant([[[1.1,2,3,4,5],[2,3,4,5,6]],
                   [[1.1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]],
                   [[1.3,2,3,4,5],[2,3,4,5,6]]])

        dummy_3 = tf.ragged.constant([[[1.5,2,3,4,5],[2,3,4,5,6]],
                   [[1.6,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]],
                   [[1.7,2,3,4,5],[2,3,4,5,6]]])
        self.dataset = tf.data.Dataset.from_tensor_slices((dummy_1, dummy_2, dummy_3))
        for dummy_1, dummy_2, dummy_3 in self.dataset.batch(2):
            x, y = self.model((dummy_1, dummy_2), training=True)

net = network()
net.train()
```

**Comment by edloper** [comment]
I took a look at the code for `Conv1DTranspose`, and it doesn't currently support RaggedTensors -- i.e., the current implementation assumes that the inputs are dense.  So I guess the feature request here is to have Conv1DTranspose (and possibly some other keras layers) be updated to support ragged tensors.

Also, in the second code example you posted, you need to specify `ragged=True` when creating the `keras.Input`s.  I.e.:
`input_1 = keras.Input(shape=(None,5), ragged=True)`.  But that just gives you an error further along (which indicates that Conv1DTranspose doesn't support RaggedTensors).

**Comment by CXYCarson** [comment]
> I took a look at the code for `Conv1DTranspose`, and it doesn't currently support RaggedTensors -- i.e., the current implementation assumes that the inputs are dense. So I guess the feature request here is to have Conv1DTranspose (and possibly some other keras layers) be updated to support ragged tensors.
> 
> Also, in the second code example you posted, you need to specify `ragged=True` when creating the `keras.Input`s. I.e.:
> `input_1 = keras.Input(shape=(None,5), ragged=True)`. But that just gives you an error further along (which indicates that Conv1DTranspose doesn't support RaggedTensors).

Thank you for pointing out the error in my code!
I'm not sure if TensorFlow has any other ways of handling time-series data with non-uniform shape, but if `RaggedTensor` is the only way, then you are correct that my feature request would be to have more layers be updated to support `RaggedTensor`

Also, as a way around, if I replace my `Conv1DTranspose` with other layers that support `RaggedTensor`, then is it fine to apply `Conv1DTranspose` afterwards? Or is it just not possible to use `Conv1DTranspose` anywhere in my model as long as the shape of my data is still non-uniform?

Lastly, do you happen to know what are the layer APIs that support `RaggedTensor` as input?

**Comment by edloper** [comment]
> I replace my Conv1DTranspose with other layers that support RaggedTensor, then is it fine to apply Conv1DTranspose afterwards

As long as the input to Conv1DTranspose is a dense tensor, Conv1DTranspose should work fine.  I.e., if you have an earlier layer that has a RaggedTensor input and a DenseTensor output, then you could use Conv1DTranspose.

I'm not an expert in Keras (I do most of my work at lower levels of the TensorFlow stack), but another thing that you might want to look into is Keras [masking](https://keras.io/guides/understanding_masking_and_padding/).  Though from a quick look at that guide plus the code for Conv1DTranspose, I'm *guessing* that this layer it won't support masking?  (In particular, I don't see any `compute_mask` method being defined.)

> Lastly, do you happen to know what are the layer APIs that support RaggedTensor as input?

I don't, but if anyone else does, please chime in.

**Comment by fchollet** [comment]
When you call `model.fit(list)`, you should make sure that each element in `list` is a NumPy array (or eager tensor). As explained by other folks in this thread, only arrays with uniform shapes are supported at this time. The way to encode tensors with non-uniform shapes in TF is RaggedTensor, but we don't have very good support for RaggedTensor at this time, so you won't be able to use that. Support will expand over time.

Closing as won't fix.
