### ISSUE TITLE
Perhaps TF graph connectivity issues in keras-based Model containing Masking layers

### ISSUE THREAD

**Issue by kk-55** [tensorflow/tensorflow#45110]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
[gist](https://gist.github.com/klausk55/b2a9117989d32b8f55ad6aeb99532728)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu-20.04 on a Windows Subsystem for Linux (WSL)
- TensorFlow version (use command below):
2.3.1 v2.3.0-54-gfcc4b966f1
- Python version:
3.8.2 64-bit using a venv
- Ray[rllib] version (RL framework):
1.0.1.post1
- Text editor (development environment):
Visual Studio Code

**Describe the current behavior**
Get `InvalidArgumentError: You must feed a value for placeholder tensor` if line 73 in _articleSchedulingModel.py_ is active, instead comment in line 74 and comment out line 73 then there is no error.
It seems to me that perhaps there might be an issue with connectivity of the TF graph similar to a former related issue mentioned in this [annotation](https://github.com/ray-project/ray/blob/084f03797b7a88e4ba491b329eb6e1634905fb72/rllib/examples/models/batch_norm_model.py#L81):

> IMPORTANT NOTE: This model will not work with PPO due to a bug in keras
    that surfaces when having more than one input placeholder (here: `inputs`
    and `is_training`) AND using the `make_tf_callable` helper (e.g. used by
    PPO), in which auto-placeholders are generated, then passed through the
    tf.keras. models.Model. In this last step, the connection between 1) the
    provided value in the auto-placeholder and 2) the keras `is_training`
    Input is broken and keras complains.

My assumption is that some connection gets lost in the tf.keras.Model caused by the masking layer defined in line 64 and further connected to the concatenate layer defined in line 73 (in _articleSchedulingModel.py_).

Is the assumption appropriate or what else might cause this error?

**Standalone code to reproduce the issue**
Link to [gist](https://gist.github.com/klausk55/b2a9117989d32b8f55ad6aeb99532728)

**Other info / logs**
Traceback also in [gist](https://gist.github.com/klausk55/b2a9117989d32b8f55ad6aeb99532728)

**Comment by klausk55** [comment]
Update: For now, I am quite sure that the masking is causing the issue, but I do not understand why.
The masking layer in line 58 works fine, but including further masking layers (e.g. in line 64) leads to the error above.

**Comment by Saduf2019** [comment]
@klausk55 
Please provide with "simple stand alone code" to replicate the issue or if possible share a colab gist with the error reported.

**Comment by klausk55** [comment]
@Saduf2019
Additional to the shared gist from above, I share a [colab gist](https://colab.research.google.com/gist/klausk55/7c5c1a87fee088e233bec7a0181620e8/invalidargerr.ipynb)

**Comment by klausk55** [comment]
A question regarding masking which might cause my reported issue:
First, can a TF keras model only have one mask or is it feasible to have more different masks? If so, must all present masks have at least the same shape and otherwise connections in TF graph gets broken?

**Comment by klausk55** [comment]
I think I know what triggers the error. For example, the computation graph of a keras model as depicted on the left-hand side works fine, but the example on the right-hand side raises the InvalidArgumentError from above.
The first concatenation of graph parts which contain connections to layers.Masking is, in my opinion, okay, but a later further concatenation of graph parts which again contain connections to layers.Masking seems to trigger the error.

I do not know the reason behind, but it seems to be not feasible or not supported yet. Any suggestions?

![Masking_concatenate](https://user-images.githubusercontent.com/63732956/100236695-49e9eb00-2f2e-11eb-9231-0b05f616ff93.png)

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/e13fd5583fb59e3ef896536fa51415ec/untitled473.ipynb).

**Comment by klausk55** [comment]
Any feedback or ideas?

**Comment by sachinprasadhs** [comment]
While trying to reproduce your issue in Tf Nightly 2.6 facing different error, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/fad1c0a7582c51a53214efcbb246f37c/45110.ipynb), Thanks!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
