### ISSUE TITLE
Documentation for using a private CocoaPod spec for TensorFlow Lite is not correct

### ISSUE THREAD

**Issue by alexdmiller** [tensorflow/tensorflow#45113]
## URL(s) with the issue:

https://www.tensorflow.org/lite/guide/build_ios#using_local_tensorflow_lite_core

### Clear description

The documentation linked above says to change the following line in the TensorFlowLiteC.podspec file:

```
  s.source       = { :http => "file://<path_to_TensorFlowLiteC_framework.zip>" }
```

It then asks you to follow the instructions on [creating a private CocoaPod repo](https://guides.cocoapods.org/making/private-cocoapods.html) to use this pod in your project.

That guide asks you to run the following:

```
pod repo push tfliteswift TensorFlowLiteC.podspec
```

But when you do this, you get an error message about the podspec line:

```
[!] Error installing TensorFlowLiteC
 -> TensorFlowLiteC (2.3.0)
    - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/local/anaconda3/bin/curl -f -L -o /var/folders/5j/wwtlv8lx0m5fmhc3hy5w5_000000gp/T/d20201123-17126-1ko7ol4/file.zip file://<redacted>/tensorflow/bazel-bin/tensorflow/lite/experimental/ios/TensorFlowLiteC_framework.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.0 cocoapods-downloader/1.4.0'

curl: (3) URL using bad/illegal format or missing URL
```
I don't believe the `:http => "file://<path_to_TensorFlowLiteC_framework.zip>"` line makes sense, because you're specifying a local file path for the `http` key. It's clearly not an http URL. Therefore I believe this documentation is incorrect / incomplete.

I have yet to get my app compiling with a custom build of TensorFlowLite, so I don't know the solution. Any help appreciated.

**Comment by MarkDaoust** [comment]
Everyone here says this works: https://github.com/CocoaPods/cocoapods-packager/issues/216#issuecomment-513514364

You just need a triple `/` like `file:///path`. `file://` is the protocol,  `/path` is the path

```
$ curl file://path

curl: (3) URL using bad/illegal format or missing URL
```

**Comment by MarkDaoust** [comment]
I'm sending a little fix to make this clearer.
