### ISSUE TITLE
Tflite Model gives same output for every input

### ISSUE THREAD

**Issue by p17bail** [tensorflow/tensorflow#45119]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow installed from (source or binary): Source
- TensorFlow version (or github SHA if from source): 2.3.0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook. [Link for my Google Colab Notebook](https://colab.research.google.com/drive/1f0394NZJ-Jjt1bJ6eILTS1qH6hamvkEr?usp=sharing)

```
# Convert the model.
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# Save the model.
with open('/content/drive/MyDrive/model.tflite', 'wb') as f:
  f.write(tflite_model)
```

My goal is to develop an app that does image classification. Keras model seems to work good but after i try to convert to Tensorflow Lite, output is always the same.

**Code that I use to use to feed the tflite model random data**
```
# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="/content/drive/MyDrive/my_model.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)
```
The output of the model is always something like this
```
[[ 1.5353261   0.5791437  -0.00934554 -1.5525526 ]]
```
Keras model seems to classify correct the images but I can't understand what is wrong after the conversion.

Many thanks in advance!

**Comment by amahendrakar** [comment]
@p17bail,
On running the Colab notebook you have linked I am facing an error stating `FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/final_dataset'`. 

In order to reproduce the issue, could you please share the contents of the `final_dataset` folder with us. Thanks!

**Comment by p17bail** [comment]
@amahendrakar  
This is the [Link](https://drive.google.com/drive/folders/1eW63OhZARj0I4YUAdmgUwfBdc67HgWR4?usp=sharing) for my dataset in google drive. Find the file in shared with me and then choose add shortcut to my drive so you can have access from Google Colab.

Thanks for your time.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/8e8eb6ad6c5c038b377bff044853d31d/45119.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/7994b4a31ae2ca59051888ad36d673d7/45119-tf-nightly.ipynb). Pleas find the attached gist. Thanks!

**Comment by ymodak** [comment]
You need to resize your input image size to be compatible with the model image sizes.
To know more see https://stackoverflow.com/a/63312051/11127923
