### ISSUE TITLE
Missing wheels tagged for macosx_11_x

### ISSUE THREAD

**Issue by dgladkov** [tensorflow/tensorflow#45120]
Current wheels are built for `macosx_10_9_*` .e.g `tensorflow-2.3.1-cp37-cp37m-macosx_10_9_x86_64.whl`. Pip attempts to build a list of compat tags that includes previous minor releases of macOS, however macOS Big Sur is a major release, which prevents those wheels from being installed:

```
$ pip install ~/Downloads/tensorflow-2.3.1-cp37-cp37m-macosx_10_9_x86_64.whl
ERROR: tensorflow-2.3.1-cp37-cp37m-macosx_10_9_x86_64.whl is not a supported wheel on this platform.
```

Solution: since the package itself is compatible for both macOS 10 and 11, the tagging needs to include both 10_x and 11_x major versions. Following installs without issues on Big Sur.
```
$ pip install ~/Downloads/tensorflow-2.3.1-cp37-cp37m-macosx_10_9_x86_64.macosx_11_0_x86_64.whl
```

List of wheels for TensorFlow 2.3.1: https://pypi.org/project/tensorflow/2.3.1/#files

**Comment by mihaimaruseac** [comment]
So this is just a wheel rename issue?

**Comment by dgladkov** [comment]
Ultimately yes, but we want to change how `bdist` is generated so we don't have to rename manually.
