### ISSUE TITLE
Implementations 2/3 of LocallyConnected1D layer don't work with saved_model.save()

### ISSUE THREAD

**Issue by sgdre217** [tensorflow/tensorflow#45121]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
2.3.0
- Python version:
3.6 
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
N/A
- CUDA/cuDNN version:
N/A
- GPU model and memory:
N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
ValueError: Tried to convert 'shape' to a tensor and failed. Error: None values not supported.

**Describe the expected behavior**
Successfully saving the model (as with implementation=1)

**Standalone code to reproduce the issue**
```
import tensorflow as tf
input = tf.keras.Input(
            shape=(10,1),
)
output = tf.keras.layers.LocallyConnected1D(
            1,
            5,
            5,
            implementation=3,  # implementation=1 does not cause error
)(input)
model = tf.keras.Model(
            inputs=input,
            outputs=output,
)
tf.saved_model.save(model, "tmp")
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@sgdre217 
I ran the code shared on tf nightly and [tf 2.3](https://colab.research.google.com/gist/Saduf2019/8b1e9b5d754980c48871eb7d6c6e190b/untitled469.ipynb), i do not see any error on nightly please find the [gist here](https://colab.research.google.com/drive/1KG_yIXTyrhEfH4ac6qYtPIZAysJ0Ekz-#scrollTo=vfeNnHPzvCJv).

**Comment by sgdre217** [comment]
While I don't have access to your gist, I have independently confirmed that the error does not occur on tf nightly. Thanks!

**Comment by Saduf2019** [comment]
@sgdre217 
Access has been granted to the gist, please move the issue to closed status as it is resolved.

**Comment by sgdre217** [comment]
I am reopening this issue as the bug has persisted through TF version 2.5.0. Additionally, it seems like the bug is now present in tf-nightly. Here is a collab (note that it seems like the one @Saduf2019 linked has since been edited): https://colab.research.google.com/drive/1YUrOJautQiBZASDNZ97jIHlxCIsd9NHV#scrollTo=NhL5OdF3tx4z

**Comment by Saduf2019** [comment]
I am able to replicate this issue please find the [gist here](https://colab.research.google.com/gist/Saduf2019/bb7cb39157ff14d9cbc33a51480c8ed2/untitled605.ipynb). Thanks!

**Comment by bhack** [comment]
We have already two tickets and a PR https://github.com/tensorflow/tensorflow/pull/49230

**Comment by ashutosh1919** [comment]
@Saduf2019 , you can close the issue because we have exact same 2 tickets as @bhack mentioned. You can subscribe to these 2 tickets although so that you can get updates.

Attaching the 2 tickets: #48584 and #47689 .
