### ISSUE TITLE
TextLineDataset stops after first segment of multiple gzip'ed files concatenated together

### ISSUE THREAD

**Issue by mrkeldon** [tensorflow/tensorflow#45137]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Debian sid
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):v1.12.1-38511-ge95a955af8 2.4.0
- Python version: 3.8.5
- Bazel version (if compiling from source): 3.7.0
- GCC/Compiler version (if compiling from source):  10.2.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
Creating a TextLineDataset with the 'GZIP' compression type stops returning lines if the datafile consists of multiple gzipped files concatenated together.  This method of concatenating compressed files is explicitly called out in the gzip manpage as supported behavior.  And indeed, zcat, gunzip, and others do return all the uncompressed data.  Even Python's gzip.decompress() method does so, so it is confusing that Tensorflow does not.  The alternative is to decompress the files, concatenate them, then recompress, but this is undesirable due to the time required.

**Standalone code to reproduce the issue**
```
#!/usr/bin/python3

import tensorflow as tf
import gzip

f = open('data.gz', 'wb')
for i in range(10):
        line = str(i) + '\n' + str(i + 100) + '\n'
        f.write(gzip.compress(line.encode('utf-8')))
f.close()

ds = tf.data.TextLineDataset('data.gz', compression_type='GZIP')
for i in ds:
        print(i)
```

tf.Tensor(b'0', shape=(), dtype=string)
tf.Tensor(b'100', shape=(), dtype=string)

This only returns 2 of the 20 expected items.

**Comment by ravikyram** [comment]
I have tried in colab with TF 2.4, nightly version (`2.5.0-dev20201123`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/1f64705325efcbd92eb88f177bea626d/untitled534.ipynb). Thanks!
