### ISSUE TITLE
label_image build fail on x86

### ISSUE THREAD

**Issue by vaibhavexleapsemi** [tensorflow/tensorflow#45139]
**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow installed from: source (Branch: Master, Commit Id: b0d40302ec4ce301e841eb58fc7e6937e4624ab7)
- TensorFlow version: 3.1.0

**Provide the text output from tflite_convert**

```
# Copy and paste here
```

**Standalone code to reproduce the issue** 
After cloning tensorflow sources:
$ cd tensorflow/tensorflow/lite/tools/make
$ ./download_dependencies.sh
$ ./build_lib.sh label_image

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**
ar: creating /home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/gen/linux_x86_64/lib/libtensorflow-lite.a
g++ -O3 -DNDEBUG -DCPU_SETSIZE=__CPU_SETSIZE -fPIC  --std=c++11  -DTFLITE_HAVE_CPUINFO -DTFLITE_WITHOUT_XNNPACK -fPIC -DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK -pthread -I. -I/home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/../../../../../ -I/home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/../../../../../../ -I/home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/downloads/ -I/home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/downloads/eigen -I/home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/downloads/absl -I/home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/downloads/gemmlowp -I/home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/downloads/ruy -I/home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/downloads/neon_2_sse -I/home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/downloads/farmhash/src -I/home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/include -I/home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/downloads/fp16/include -I/home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/downloads/cpuinfo -I/home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/downloads/cpuinfo/include -I/home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/downloads/cpuinfo/src -I/home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/downloads/cpuinfo/deps/clog/include -I -I/usr/local/include \
-o /home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/gen/linux_x86_64/bin/label_image /home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/gen/linux_x86_64/obj/tensorflow/lite/examples/label_image/bitmap_helpers.o /home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/gen/linux_x86_64/obj/tensorflow/lite/examples/label_image/label_image.o /home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/gen/linux_x86_64/obj/tensorflow/lite/tools/evaluation/utils.o \
 /home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/gen/linux_x86_64/lib/libtensorflow-lite.a  -lstdc++ -lpthread -lm -lz -ldl -ldl
/home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/gen/linux_x86_64/obj/tensorflow/lite/examples/label_image/label_image.o: In function `tflite::label_image::Main(int, char**)':
label_image.cc:(.text+0x907d): undefined reference to `tflite::tools::ToolParams::Merge(tflite::tools::ToolParams const&, bool)'
label_image.cc:(.text+0x921d): undefined reference to `tflite::Flags::Parse(int*, char const**, std::vector<tflite::Flag, std::allocator<tflite::Flag> > const&)'
label_image.cc:(.text+0x92a9): undefined reference to `tflite::Flags::Usage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<tflite::Flag, std::allocator<tflite::Flag> > const&)'
collect2: error: ld returned 1 exit status
tensorflow/lite/tools/make/Makefile:367: recipe for target '/home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/gen/linux_x86_64/bin/label_image' failed
make: *** [/home/khan/vaibhav/review/tensorflow/tensorflow/lite/tools/make/gen/linux_x86_64/bin/label_image] Error 1
make: Leaving directory '/home/khan/vaibhav/review/tensorflow'

**Comment by jvishnuvardhan** [comment]
@vaibhavexleapsemi Can you please describe the issue with little more details. Thanks!

**Comment by terryheo** [comment]
I've confirmed the issue. Let me handle it.

**Comment by vaibhavexleapsemi** [comment]
Hi @terryheo 
While building label_image following files are missing for linking i.e tensorflow/lite/tools/command_line_flags.cc tensorflow/lite/tools/tool_params.cc
So I had added the above files in ./tensorflow/lite/tools/make/Makefile as follows:
LABEL_IMAGE_SRCS := \
        tensorflow/lite/examples/label_image/bitmap_helpers.cc \
        tensorflow/lite/examples/label_image/label_image.cc \
        tensorflow/lite/tools/evaluation/utils.cc \
        tensorflow/lite/tools/command_line_flags.cc \
        tensorflow/lite/tools/tool_params.cc
and label_image got build.

**Comment by vaibhavexleapsemi** [comment]
Also If we check BUILD file at ./tensorflow/lite/examples/label_image, in target label_image the dependency for command_line_flags and tool_params are present. 
So by adding tensorflow/lite/tools/command_line_flags.cc and tensorflow/lite/tools/tool_params.cc to LABEL_IMAGE_SRCS in ./tensorflow/lite/tools/make/Makefile, will create same label_image as built by bazel.
As I am new to tensorflow please correct me if wrong.

**Comment by vaibhavexleapsemi** [comment]
@terryheo thanks for fixing the issue in Commit Id: 684cec69dbbd0ede4eaa59397750be265fac17b3
