### ISSUE TITLE
python3.6 Mac OS X 11.0.1  Could not find a version that satisfies the requirement tensorflow

### ISSUE THREAD

**Issue by DAJINZI01** [tensorflow/tensorflow#45147]
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow

**Comment by amahendrakar** [comment]
@DAJINZI01,
Could you please update pip using the below commands and check if you are still facing the same issue?

```
pip install --upgrade pip
pip install tensorflow
```

Thanks!

**Comment by DAJINZI01** [comment]
there is nothing to do with pip. i think it is the problem of Mac OS X 11.0.1 system

**Comment by amahendrakar** [comment]
@DAJINZI01,
Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/44615#issuecomment-727439589) from a similar issue and let us know if it helps. 

Also, could you please let us know which version of TensorFlow you are trying to install. Thanks!

**Comment by DAJINZI01** [comment]
thinks. I reboot my machine, and it works.
