### ISSUE TITLE
TFLITE Flower Classification codelab not working on own model it's always crashed

### ISSUE THREAD

**Issue by gabbygab1233** [tensorflow/tensorflow#45141]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (Ubuntu 20.04 ):
- Mobile device (OPPO A37fw) 
- TensorFlow installed from (source or binary):
- TensorFlow version (2.2.0):
- Python version:3.7

**Describe the current behavior**
I changed the model.tflite and label.txt on my own model and labels but it's not working. Using the default tflite model and label.txt work though.

**Describe the expected behavior**

**Comment by Saduf2019** [comment]
@gabbygab1233 
Please share a simple stand alone code to replicate the issue or share a colab gist.
