### ISSUE TITLE
tf-trained model not working after converting to tf-lite for raspi

### ISSUE THREAD

**Issue by johannesk94** [tensorflow/tensorflow#45148]
**System information**
Laptop: 
Linux Ubuntu
Tensorflow 1.15.0

Raspi:
Raspberry Pi 4
tflite-runtime 2.5.0
tensorflow-estimator 1.14.0
Coral Edge TPU

Hello everybody, I am stuck at getting my trained model running on raspi. I trained ssd_mobilenet_v2_coco model from tensorflow 1 modelzoo with my own custom dataset on google cloud with this config file where I did few changes:
[ssd_mobilenet_v2_coco_config.zip](https://github.com/tensorflow/tensorflow/files/5589151/ssd_mobilenet_v2_coco_config.zip)

After training I exported the frozen_inference_graph which worked pretty well on my laptop, so I exported the tflite graph (tflite_graph.pb and tflite_graph.pbtxt) with the following command:
`python export_tflite_ssd_graph.py \ 
--pipeline_config_path=gs://objects1119/ssd_mobilenet_v2_coco.config \ 
--trained_checkpoint_prefix=gs://objects1119/model.ckpt-189879 \ 
--output_directory=tflite \
--add_postprocessing_op=true`

after that I converted it to detect.tflite file with:
`tflite_convert --graph_def_file=tflite/tflite_graph.pb  --output_file=tflite/detect.tflite  --output_format=TFLITE --input_arrays=normalized_input_image_tensor --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'  --inference_type=QUANTIZED_UINT8 --mean_values=128 --std_dev_values=127 --change_concat_input_ranges=false --allow_custom_ops`

You can see the file here:
[detect_tflite.zip](https://github.com/tensorflow/tensorflow/files/5589264/detect_tflite.zip)

After that I converted it to edgetpu-file with this google colab: https://colab.research.google.com/drive/1o6cNNNgGhoT7_DR4jhpMKpq3mZZ6Of4N?usp=sharing 
while using the EdjeElectronics Tutorial: 
https://github.com/EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi/blob/master/Raspberry_Pi_Guide.md 
 everything worked without errors and I gut this file:
[detect_edgetpu.zip](https://github.com/tensorflow/tensorflow/files/5589397/detect_edgetpu.zip)

But when I finally try to run it on the raspi with this file
[TFLite_detection_webcam.zip](https://github.com/tensorflow/tensorflow/files/5589323/TFLite_detection_webcam.zip)
I am always facing the same output, no matter what input. There is always Class Zero predicted on the same areas of the image with prediction of 50%. What am I doing wrong? Is it because of the changed input shapes in the config file for training? In my case it would be really complicated to train again so I try to avoid this if its possible.
Thank you very much in advance.

**Comment by johannesk94** [comment]
Are there any suggestions or do you need more information about the issue?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
