### ISSUE TITLE
int32 instead of int32_t in  tensorflow/tensorflow/lite/kernels/internal/common.h 

### ISSUE THREAD

**Issue by dpollack** [tensorflow/tensorflow#45158]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Devuan Beowulf (Debian 10)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.5.0
- Python version: 3.7.3
- Bazel version (if compiling from source): 3.6.0
- GCC/Compiler version (if compiling from source): (Debian 8.3.0-6) 8.3.0
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**

Line 192 of  tensorflow/tensorflow/lite/kernels/internal/common.h  references int_32

     int32x4x4_t input_val, int32 quantized_multiplier, int shift) { 
                                              ^^^^^
compilation shows int32 is undefined 

**Describe the expected behavior**

It should use int32_t
    int32x4x4_t input_val, int32_t quantized_multiplier, int shift) {
                                             ^^^^^^
**Standalone code to reproduce the issue**

Any compilation attempt should fail

**Other info / logs** 

NA

**Comment by karimnosseir** [comment]
This should be fixed already. You might want to get the latest code version.
