### ISSUE TITLE
TFLite - Java - Executing models on JVM not Android

### ISSUE THREAD

**Issue by dibog** [tensorflow/tensorflow#45155]
**System information**
- Linux Ubuntu 16.04, Windows
- Not mobile device. JDK or JRE.

**Example application using maven to compile and run an tensorflow lite project on JVM**

In the examples I only find bindings for Android. Which jar files (with maven coordinates) would I need
to run / evaluate tensorflow models on a JVM.

Thanks,
Dieter

**Comment by sheh** [comment]
It would be great to have such an example. It would allow to test common ml code against a huge dataset without data copying and android as dependency.

**Comment by jdduke** [comment]
Thanks for the request. Are you planning to deploy your ML workload in a desktop Java environment? Or you primarily want to test it (but ultimately deploy on a mobile device)?

**Comment by sheh** [comment]
We are going to test on a not-Android host ml-code base then deploy full app on an Android device. We have several Gb test videos so one test takes too much time. We use tf with *.pb models for now but it is not 100% correct because the app uses tflite.

**Comment by jdduke** [comment]
I see, thanks. I'm assuming your test harness won't be using bazel for execution? If it were, this gets a lot easier.

Historically, we haven't hosted desktop-compatible targets on Maven, as there hasn't been strong demand. Would it be sufficient to provide bazel commands and/or a script which generates the necessary .jar + shared libraries?

**Comment by sheh** [comment]
Yes. For us, it would be sufficient to have a script or a list bazel commands.
Thanks!

**Comment by paulo-raca** [comment]
Same here.

I would like to have the same Java code running on both desktop and Android devices, and having tflite libraries working on regular JVM would be very helpful.

Also, the lower overhead of tflite is desirable anyway ;)

Having it as a just-works maven dependencies would be ideal, but the bazel commands you suggested would work too :)

**Comment by dibog** [comment]
I really would like to have them as maven dependency. That's the way how you share code in JVM, ain't it?

**Comment by jdduke** [comment]
@xunkai55 what are your thoughts on hosting desktop-specific TFLite builds on MavenCentral?

**Comment by xunkai55** [comment]
@jdduke I don't see any technical blocker to have a new project (maybe "tensorflow-lite-java" or "tensorflow-lite-jvm") on MavenCentral.

**Comment by paulo-raca** [comment]
Not really a problem, but it this necessary to have 2 distinct project names?
Most libraries just-work when used on either desktop or Android.

**Comment by paulo-raca** [comment]
Ah, good point :man_facepalming: 

Maybe you could take advantage on the fact that android uses the AAR artifact and desktop uses JAR? :thinking: 
But I really haven't seem this done anywhere :sweat_smile:

**Comment by xunkai55** [comment]
Hi there,

We're visiting this and we plan to provide something like "tensorflow-lite-java" in the future. But due to priority limits, it's unlikely to happen in the next 3 months.

**Comment by Saduf2019** [comment]
@dibog 
Is this still an issue,
Could you please let us know if this is still an issue in latest stable TF v2.6.0 ?Thank you!

**Comment by Volatile-Memory** [comment]
any update on when `tensorflow-lite-java` would be developed/released?

> Hi there,
> 
> We're visiting this and we plan to provide something like "tensorflow-lite-java" in the future. But due to priority limits, it's unlikely to happen in the next 3 months.

**Comment by spaced** [comment]
as a workaround, i extracted the aar package to grab the jars, build the jni binary by executing
```
bazel build -c opt --fat_apk_cpu=x86_64  //tensorflow/lite/java:libtensorflowlite_jni
```
and put this jni lib with `-Djava.library.path=yourPathOfLib`
but yes. this could be provided all in one dependency (see also various javacpp project for opencv/ffpmeg..)

my use case: Running inference on a x64 barebone with a coral tpu. You need `tflite` for, but cpu and memory must be more powerful to track multiple cams. Using a gpu to a barebone would be the alternative and run tensorflow. So tflite is not only good for embedded/small devices.

**Comment by ando0689** [comment]
I have the same issue as well, I try to test a small chatbot model I have created and it would be perfect to be able to test it on Desktop,  especially now when Jetpac Compose can be used to create desktop applications, I think many Android developers will find it exciting to build small tools on desktop environment and having TFLite for such situations will be great!

**Comment by zhuker** [comment]
i need this as well

**Comment by mohantym** [comment]
Hi @dibog !
Could you post this feature request on [Tensorflow/Java](https://github.com/tensorflow/java) repo as it is specific TFLite in Java.
Relevant [thread](https://github.com/tensorflow/java/issues/59). 
Thank you!

**Comment by spaced** [comment]
tflite/java (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/java) is not the same as tensorflow/java. please reopen

**Comment by mohantym** [comment]
@spaced !
Re-opening as requested .
Thank you!

**Comment by mohantym** [comment]
Hi@spaced !

I am aware that Tensorflow/java is same as Tensorflow/Lite/Java but was skeptical about the effort of  implementation of Tensorflow/Lite /Java in  Java Virtual machine. ( JVM) .

Re-opening as requested .
Thank you!

**Comment by wl-08** [comment]
I need this too, thanks

**Comment by BurgerSzilard** [comment]
Any news about this ? Is this in the pipeline ? 
Would be good to have this available.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

**Comment by xamde** [comment]
This issue certainly does NOT end with any explanation or link how to run TFLite Models in plain JVM, e.g. for testing with large test sets.
