### ISSUE TITLE
How to generate a Reshape TFLite model with the new shape as attributes?

### ISSUE THREAD

**Issue by jackwish** [tensorflow/tensorflow#45150]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): v2.3.0

**Command used to run the converter or code if you’re using the Python API**

```py
import tensorflow as tf  # tf 2.3.0
import numpy as np

ISHAPE = (1, 2, 3, 4)
OSHAPE = (int(np.product(ISHAPE)),)


def genWithKeras():
  data = tf.keras.Input(dtype='float32', name='input', batch_size=ISHAPE[0], shape=ISHAPE[1:])
  reshape = tf.keras.layers.Reshape(OSHAPE, name='reshaped')(data)
  model = tf.keras.Model(inputs=[data], outputs=[reshape])
  return tf.lite.TFLiteConverter.from_keras_model(model)


def genWithTFModel():
  class ReshapeModule(tf.Module):
    def __init__(self):
      super(ReshapeModule, self).__init__()

    @tf.function(input_signature=[tf.TensorSpec(ISHAPE, tf.float32)])
    def __call__(self, data):
      return tf.reshape(data, OSHAPE)

  module = ReshapeModule()
  tf.saved_model.save(module, 'reshape.saved_model')
  return tf.lite.TFLiteConverter.from_saved_model('reshape.saved_model')

converter = genWithKeras()
# converter = genWithTFModel()
tflite_model = converter.convert()
with open('model.tflite', 'wb') as f:
  f.write(tflite_model)
```

**The output from the converter invocation**

![](https://user-images.githubusercontent.com/4936589/99535868-78bf0900-29e4-11eb-86e9-8482d57e5a4b.png)

**Also, please include a link to the saved model or GraphDef**

```
None
```

**Failure details**
May I know the details of how the TFLite models are generated, in particular, the code path to produce the TFLite models? **Should be irrelevant to the model detail**.

We are working on [`tflite2onnx`](https://github.com/jackwish/tflite2onnx) which can convert TFLite models to ONNX. When converting the [palm_detection](https://github.com/google/mediapipe/blob/master/mediapipe/modules/palm_detection/palm_detection.tflite) model from [MediaPipe](https://github.com/google/mediapipe), we noticed that the `Reshape` of it accepts **only one input** - the output shape is as the attribute of `Reshape` as the figure below.

<img width="528" alt="palm-detect" src="https://user-images.githubusercontent.com/4936589/99535493-ee76a500-29e3-11eb-829f-30239911b9fd.png">

We tried to build a standalone case for `Reshape` (a model which contains `Reshape` only), but there are **always two inputs** in our model with either Keras API or TensorFlow API (as the repro code above). We are curious about how to generate a Reshape TFLite model with the new shape as attributes?

**RNN conversion support**
None

**Any other info / logs**

The source issue we have is: https://github.com/jackwish/tflite2onnx/issues/23#issuecomment-725070754 and we are moved from [this MediaPipe issue](https://github.com/google/mediapipe/issues/1310)

**Comment by SunAriesCN** [comment]
Hi, @renjie-liu Do you have any idea for that? And I'm just for some watermelons on this problem, please forget me.....

**Comment by abattery** [comment]
The TFLite Reshape op always have two inputs, data and shape. In my understanding, there are no ways currently to generate the shape as an attribute.

**Comment by jackwish** [comment]
@abattery Thanks for your reply! Yes, we have not found a way to generate such a model. But as described in the issue description, the [palm_detection](https://github.com/google/mediapipe/blob/master/mediapipe/modules/palm_detection/palm_detection.tflite) model from [MediaPipe](https://github.com/google/mediapipe) contains such a `Reshape` with shape as its attribute (as the figure below). 

![](https://user-images.githubusercontent.com/4936589/99535493-ee76a500-29e3-11eb-829f-30239911b9fd.png)

Maybe they are using some _special_ TensorFlow build?...

**Comment by abattery** [comment]
Maybe the old TensorFlow Lite TOCO converter was able to create this kind of Reshape node.

**Comment by renjie-liu** [comment]
Sorry for the late reply, just saw the thread.

- In tf, [reshape](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/array_ops.cc#L1368-L1376) op always have two inputs.
- In the mlir converter, the tflite [reshape](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/lite/ir/tfl_ops.td#L2575-L2593) op indeed will always have two inputs.
- In TOCO, we do not have such restriction, so during transformations, we may introduce `reshape` op without the shape tensor as inputs.
- And in the kernel, we can handle `reshape` without shape tensor as well (if the shape attribute is presented)

But it's good to ensure the `reshape` op has two inputs:

- It's good for us to do feature parity with tf and reduce fragmentations
- It's easier to handle dynamic shape case.

**Comment by jackwish** [comment]
@abattery @renjie-liu Yes, maybe they were using TOCO. I can try some legacy versions. Good to know the restriction in MLIR converter, Thanks!
