### ISSUE TITLE
Loading a Custom Model TFlite into Flutter 

### ISSUE THREAD

**Issue by mlopez0** [tensorflow/tensorflow#45152]
I follow along this [Colab](https://colab.research.google.com/drive/1qXn9q6m5ug7EWJsJov6mHaotHhCUY-wG?usp=sharing)  to  train a custom model.

[Conversion process Colab](https://colab.research.google.com/drive/1VRH4K_LPXlTv-YvobWjvxOAowxTYIli8?usp=sharing) 

After completing the training process I converted the .pb to .tflite and I got [these files](https://drive.google.com/drive/folders/1I8pU34M9gagLFdImmrpS8qUY6Wge0jds?usp=sharing). When I loaded the model into the [official Android demo](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android)  I got the following error:

```
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.sd_detect/com.example.sd_detect.MainActivity}: java.lang.IllegalStateException: This model does not contain associated files, and is not a Zip file.
```
The solution to that error is discussed in [this issue](https://github.com/tensorflow/tensorflow/issues/44431)

I followed the solution:

Installing the metadata library with:
```
pip install tflite-support

```
and then executing the following command into python
```
>>> from tflite_support import metadata as _metadata
>>> populator = _metadata.MetadataPopulator.with_model_file('final_model.tflite')
>>> populator.load_associated_files(["final_model.txt"])
>>> populator.populate() 
```

And I got the following warning:

    /home/username/.local/lib/python3.8/site-packages/tensorflow_lite_support/metadata/python/metadata.py:342: UserWarning: File, 'final_model.txt', does not exsit in the metadata. But packing it to tflite model is still allowed.
      warnings.warn(

Back to Android Studio example I was able to run the model successfully, by just modifying this information:

    private static final String TF_OD_API_MODEL_FILE = "final_model.tflite";  
    private static final String TF_OD_API_LABELS_FILE = "final_model.txt";  

But my main goal is to use this model into a Flutter application, but when I try to run into Flutter I got the following exeption:

    /// Throws a [StateError] if the given [expression] is `false`.
    
    void  checkState(bool expression, {message}) {
    
    if (!expression) {
    
    throw  StateError(_resolveMessage(message, 'failed precondition'));
    
    }
    
    }
The flutter [project](https://github.com/am15h/object_detection_flutter) is fully working with coco_ssd_mobilenet_v1_1.0_quant_2018_06_29

I also tried to re-run the metadata commands on my flutter application assets but still the same issue.

What am I missing?

**Comment by Saduf2019** [comment]
@mlopez0 
Please share a simple stand alone code to replicate the issue reported.

**Comment by mlopez0** [comment]
The Issue is flutting-plugin related! 

Thanks for the support.
