### ISSUE TITLE
Compile label_wav.cc file for speech recognition

### ISSUE THREAD

**Issue by sairmreddy** [tensorflow/tensorflow#45169]
This is the file location location: tensorflow/examples/speech_recognition/label_wav.cc

Can you please provide steps to compile this file and run for speech recognition.

**Comment by Saduf2019** [comment]
@sairmreddy 
This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
