### ISSUE TITLE
how to handle non-tail recursive in tf when using control flow

### ISSUE THREAD

**Issue by liangzelang** [tensorflow/tensorflow#45165]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

Hi,  I am learning tensorflow and I am curious whether there is non-tail recursion in tf when using control flow
The forward prop is generally loop, tail recursion, etc., but after the derivation, will there be non-tail recursion in the backprop?  How to deal with it？
Very much looking forward to your reply.

**Comment by Saduf2019** [comment]
@liangzelang 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

**Comment by liangzelang** [comment]
* tf verrsion:
lastest
* How to reproduce the issue:
I did not meet some issues， i just want to know if there will be  non_tail recursion after Automatic differentiation and  how to handle this situation in some contro_flow cases.

**Comment by Saduf2019** [comment]
@liangzelang
please create a ticket on stackoverflow as this is not a bug or a feature request.
