### ISSUE TITLE
Output of tflite is not correct

### ISSUE THREAD

**Issue by neesetifa** [tensorflow/tensorflow#45177]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Arch Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary):   package manager
- TensorFlow version (use command below): 2.3.0
- Python version: 3.8.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
The output of tflite is not correct.
**Describe the expected behavior**
The output should match the result of equation.

**Standalone code to reproduce the issue**
```
# Original model definition
"""
model = tf.keras.Sequential([
  tf.keras.layers.InputLayer(input_shape=(2, 2, 1)),
  tf.keras.layers.Conv2D(filters=1, kernel_size=(2, 2), use_bias = True, name = 'EX_Conv_1')
])
"""

# Run tflite model
import tensorflow as tf
import numpy as np

img = np.array([[-2,2],
                [3,1]],dtype = np.int8)

img = np.expand_dims(img, axis = -1)

interpreter = tf.lite.Interpreter(model_path = 'xx.tflite') # you may download the file in attachment

interpreter.allocate_tensors()

img = img / 255.
input_scale, input_zero_point = interpreter.get_tensor_details()[0]["quantization"]
resized_image = img / input_scale + input_zero_point
interpreter.set_tensor(0, np.expand_dims(resized_image, axis = 0).astype(interpreter.get_tensor_details()[0]["dtype"]))

interpreter.invoke()
```
[model.zip](https://github.com/tensorflow/tensorflow/files/5595639/model.zip)

**Other info / logs**
By using interpreter.get_tensor_details() and  interpreter.get_tensor(k), we should get following info:
Input:
array([[[[-86],
         [ 84]],
        [[126],
         [ 41]]]], dtype=int8)

Intput scale:   x_s = 9.22722028917633e-05
Input zero point: x_zp = -1

CNN weight:
array([[[[1],
         [3]],
        [[5],
         [7]]]], dtype=int8)

CNN weight scale: w_s = 0.0005354330642148852
CNN weight zero point: w_zp = 0

CNN bias:
array([3441], dtype=int32)
CNN bias scale: b_s = 2.906211049591434e-09
CNN bias zero point: b_zp = 0

Output scale: z_s = 2.7681662118084205e-07
Output zero point: z_zp =  -122

If I understand correctly, the quantized output should be calculated as:
output_quant =  {(x_s * w_s) \*[(-86 - x_zp)\*(1-w_zp) + (84-x_zp)\*(3-w_zp) +(126-x_zp)\*(5-w_zp) + (41-x_zp)\*(7-w_zp)] + b_s\*(3441-b_zp)} / z_s - z_zp 
= [(x_s*w_s)\*(-85\*1+85\*3+127\*5+42\*7)+b_s\*(3441)] / z_s-122 = 110.2729521400995 ->(int)-> 110

While the actual output of tflite shows 127.

**Comment by Saduf2019** [comment]
@neesetifa 
Can you please share a colab gist with the error reported as we are unable to access the .zip shared.
