### ISSUE TITLE
How can I build tensorflow C++ API on x86 platform

### ISSUE THREAD

**Issue by woshildh** [tensorflow/tensorflow#45176]
Thanks, I have compiled tensorflow C++ API on window10. But, the tensorflow_cc.dll is x64, it could not be used on my project. Is any methods to build a x86 version? I'm appreciating for your reply.

**Comment by MarcoGerdHerzog** [comment]
> Thanks, I have compiled tensorflow C++ API on window10. But, the tensorflow_cc.dll is x64, it could not be used on my project. Is any methods to build a x86 version? I'm appreciating for your reply.

I would also be interested in the x86 API, but how did you manage to build the x64 version in the first place ?
I haven't found any official tutorials on the subject and the methods in unofficial sources don't seem to work for me.

It would be greatly appreciated if you could be so kind to provide your method of compiling the sources.
Thx in advance !

**Comment by woshildh** [comment]
> > Thanks, I have compiled tensorflow C++ API on window10. But, the tensorflow_cc.dll is x64, it could not be used on my project. Is any methods to build a x86 version? I'm appreciating for your reply.
> 
> I would also be interested in the x86 API, but how did you manage to build the x64 version in the first place ?
> I haven't found any official tutorials on the subject and the methods in unofficial sources don't seem to work for me.
> 
> It would be greatly appreciated if you could be so kind to provide your method of compiling the sources.
> Thx in advance !

https://github.com/gulingfengze/tensorflow-windows-build-script  I compiled sucessfully by this project.

**Comment by mohantym** [comment]
Hi @woshildh ! I found instructions for  building Tensorflow in x86_64 architecture [with C](https://www.tensorflow.org/install/lang_c). Can you try once building f[rom source](https://www.tensorflow.org/install/source_windows) with Suitable compiler flags in latest version (2.8)? Thank you!
