### ISSUE TITLE
Lamda Layer seems to ignore output_shape parameter

### ISSUE THREAD

**Issue by pokecheater** [tensorflow/tensorflow#45179]
Hello Tensorflow/Keras - Team,

I noticed some strange behaviour when I tried to create a simple sequential model with a lambda layer in it. In my example below I tried to make the code as simple as possible to clearify the problem.

My Lambda function is as simple as the minimal example from keras page:

```
def square_it(x):
    return (x ** 2)
```

To calculate the output shape I defined the following function (please note that I tried to explicit set an output shape that is wrong in my example. But from my understanding this value should overwrite any shape calculation from the lambda layer and return the output shape I defined):

```
def output_of_lambda(input_shape):
    return (None, None, 10, 20)
```

Creating the lambda layer as follows:

`lambda_layer = layers.Lambda(square_it, output_shape=output_of_lambda)`

creating an example model:

```
model_2 = keras.Sequential(
    [
        layers.Input(shape=(784)),
        layers.Dense(2, activation="relu", name="layer1"),
        lambda_layer,
        layers.Dense(4, name="layer5"),
    ]
)
```

And finally call the summary

`model_2.summary()`

Now I would expect to find my customized shape inside the summary or at least an error that the shape is wrong but instead it gives me:

```

Layer (type)                 Output Shape              Param #   
=================================================================
layer1 (Dense)               (None, 2)                 1570      
_________________________________________________________________
lambda (Lambda)              (None, 2)                 0         
_________________________________________________________________
layer5 (Dense)               (None, 4)                 12        
=================================================================
```

But I would have expected something like this:

```

Layer (type)                 Output Shape              Param #   
=================================================================
layer1 (Dense)               (None, 2)                 1570      
_________________________________________________________________
lambda (Lambda)              (None, None, 10, 20)                 0         
_________________________________________________________________
layer5 (Dense)               (None, 4)                 12        
=================================================================
```

For me it seems that the output_shape parameter has no effect at all but instead the value will always be automatically calculated.

I am using POP OS 20.04 
Tensorflow: 2.3.1
Python: 3.8.2
No Cuda was used in this example.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3, 2.4, nightly version (`2.5.0-dev20201129`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/14f878fbec332ce3416a0f04ceb8b9e8/untitled552.ipynb).Thanks!

**Comment by saikumarchalla** [comment]
Issue still exist in TF 2.5 stable version and Nightly 2.6 as well. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/ba5c05c34cd98432fd4c622788801dbc/untitled552.ipynb#scrollTo=4DjxNEJh_euy).Thanks!

**Comment by gowthamkpr** [comment]
output_shape in the Lambda Layer is used to help Keras do shape inference when in eager execution (or otherwise when shape information is not available), but it does not override TF shape inference on tensors, so it does not affect the tensor.shape attribute of the outputs.

To set the shape of a symbolic tensor with partial shape information, you should use the set_shape method.

Also moving ahead, please post all the keras issues [here](https://github.com/keras-team/keras/issues). Thanks!
