### ISSUE TITLE
Google Colab with TPU Compilation failure: Dynamic Spatial Convolution is not supported

### ISSUE THREAD

**Issue by AIWintermuteAI** [tensorflow/tensorflow#45175]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.3.0-0-gb36436b087 2.3.0
- Python version: Python 3.6.9
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source):-
- CUDA/cuDNN version:-
- GPU model and memory:-

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Here is Colab notebook to reproduce the issue. I am trying to train MobileFaceNet model, which I modified to use MobileNet v1. It trains fine on my local computer with 1070 Ti, but the speed is too slow. I am using MSRA dataset, truncated to 1763749 entries. So, I wanted to try using TPU in Colab. I can run the code now, but on the beginning of the first epoch I get the following error:

  (6) Invalid argument: {{function_node __inference_train_function_230773}} Compilation failure: Dynamic Spatial Convolution is not supported: lhs shape is f32[32,<=114,<=114,<=3] 
	 [[{{node mobile_face_net/conv1/Conv2D}}]]
	TPU compilation failed
	 [[tpu_compile_succeeded_assert/_18136726471139321858/_5]]
	 [[tpu_compile_succeeded_assert/_18136726471139321858/_5/_185]]
  (7) Invalid argument: {{function_node __inference_train_function_230773}} Compilation failure: Dynamic Spatial Convolution is not supported: lhs shape is f32[32,<=114,<=114,<=3] 
	 [[{{node mobile_face_net/conv1/Conv2D}}]]
	TPU compilation failed
	 [[tpu_compile_succeeded_assert/_18136726471139321858/_5]]
	 [[tpu_compile_succeeded_assert/_18136726471139321858/_5/_199]]
  (8) Invalid argument: {{function_node __inference_train_function_2307 ... [truncated]

You can see the full output in the Colab notebook 
https://colab.research.google.com/drive/1mwWbgA__rHpnEJK82Ih5acAv4aM_nRKE?usp=sharing

**Describe the expected behavior**
Model training and evaluating properly with TPU in Colab,

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1mwWbgA__rHpnEJK82Ih5acAv4aM_nRKE?usp=sharing

**Comment by amahendrakar** [comment]
@AIWintermuteAI,
Could you please share the contents of the directory `gs://data_bukcet/msra_tf`, so that we can reproduce the issue on our end? Thanks!

**Comment by AIWintermuteAI** [comment]
Sure! I don't know how to share from Google Cloud bucket, but I shared this dataset on Google drive, here is the link
https://drive.google.com/drive/folders/1Ufm1uRFBT_xLLasj9kdXEaAGcn0aNyWp?usp=sharing

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/bdb41549778786b899cc1d8473ba64f8/45175.ipynb). Thanks!

**Comment by AIWintermuteAI** [comment]
From your Colab notebook, I think the issue you have encountered was different to mine
File system scheme '[local]' not implemented (file: '/content/msra_tf/6.tfrecord')
This is because Cloud TPU cannot use files stored on Colab file system(or Drive) for that matter, it needs files to be placed on google bucket.
https://cloud.google.com/tpu/docs/troubleshooting#cannot_use_local_filesystem
Actually this documentation also refers to the issue I mentioned:
https://cloud.google.com/tpu/docs/troubleshooting#dynamic_shapes_not_supported
Unfortunately I do not see dynamic shapes used anywhere in my model, I even set drop_remainder to True when batching.
Ideas?

**Comment by nikitamaia** [comment]
Hi @AIWintermuteAI, I printed `dataset_train`
`<PrefetchDataset shapes: ((256, None, None, None), (256, 35275)), types: (tf.float32, tf.float32)>`

and `dataset_val`
`<PrefetchDataset shapes: ((256, None, None, None), (256, 35275)), types: (tf.float32, tf.float32)>`

You can see that the dimensions are all None and so I suspect that's what is causing the problem here, similar to #40864. I see you are calling tf.reshape but it looks like the shape of `example['height']` etc are also None, so that doesn't solve the problem. Try passing explicit size.

**Comment by AIWintermuteAI** [comment]
Thank you, setting image dimensions explicitly worked. Would be nice to add it to documentation - since the training works fine on CPU/GPU, it might confuse people.
Closing the issue.
