### ISSUE TITLE
Documentation: add warning to GPU setup instructions that Intel not supported

### ISSUE THREAD

**Issue by tsvibt** [tensorflow/tensorflow#4517]
This is obvious in retrospect and isn't TF specific, but it might save some people some time to say something like "Tensorflow only supports CUDA, which is proprietary to NVIDIA, and not all Macs have an NVIDIA GPU".

**Comment by jmchen-g** [comment]
We expect people to know what cuda/openCL is (no need to be familiar) if they want to use GPU for computing. Other wise there will be a lot to explain in the docs.
