### ISSUE TITLE
how to modify the input shape of existing model file again？

### ISSUE THREAD

**Issue by SmileTM** [tensorflow/tensorflow#45184]
tensorflow version: 2.3.0

When there is an existing model file, how to modify its input shape again?
Sometimes an existing pre-trained language model has a fixed input final dimension, but changing the final dimension has no effect.
an example in this link：
https://colab.research.google.com/drive/1BtOSLKYbElZ2EUEtLW3ahTZWeGN8QC3r?usp=sharing

**Comment by ravikyram** [comment]
@SmileTM 

Please, have a look at similar [SO query](https://datascience.stackexchange.com/a/27391) and see if it helps you.Thanks!

**Comment by SmileTM** [comment]
> @SmileTM
> 
> Please, have a look at similar [SO query](https://datascience.stackexchange.com/a/27391) and see if it helps you.Thanks!

I read the SO, there are probably two solutions in SO:
1.  delete input_layer then add a new input_layer , but there is no input_layer in my model.
2.  By rebuilding the model, and then importing the weights from the old model. This is feasible. 
     **But I don't have the model source code, only the saved model file, what should I do?**

**Comment by Saduf2019** [comment]
@SmileTM 
Could you please let us know if this is still an issue in latest stable TF v2.6.0 ?Thank you!
