### ISSUE TITLE
GPU kernel for MatrixTriangularSolve 

### ISSUE THREAD

**Issue by alexggmatthews** [tensorflow/tensorflow#4518]
A feature request. This should be possible without too much disruption because it relies on a CUBLAS call and therefore would not require changes to stream_executor, see section 3.4.6 of the linked document. 

https://developer.nvidia.com/sites/default/files/akamai/cuda/files/Misc/mygpu.pdf

The requisite blas function is called _cublasStrsm_ and seems to be already in stream executor in this file

https://github.com/tensorflow/tensorflow/blob/6d04d601e9e8758ec4642fa9d548b7321d804d63/tensorflow/stream_executor/cuda/cuda_blas.cc

I know that @rmlarsen has been interested in this sort of area in the past. 

I don't think it is possible to do this as a user op added at run time because stream executor is not part of the tf includes in the binary, but I'd be happy to be wrong.

**Comment by concretevitamin** [comment]
I forwarded this feature request to the team.  In the mean time, marking this as contributions welcome in case someone wants to take a stab.

**Comment by c0g** [comment]
I've got this in my [fork](https://github.com/c0g/tensorflow/blob/master/tensorflow/core/kernels/matrix_triangular_solve_op.cc), happy for @alexggmatthews to PR it or I'll try get to it later in the month.

**Comment by c0g** [comment]
This is a PR in #5010 . Hopefully it'll make sense!

**Comment by rmlarsen** [comment]
It looks like the PR was merged. Thanks! Closing.
