### ISSUE TITLE
Tflite pod lint error

### ISSUE THREAD

**Issue by brucechou1983** [tensorflow/tensorflow#45198]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOs 10.15.7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.0 rc3
- Python version: 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): Apple clang version 12.0.0
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Execute:
1. git checkout v2.4.0-rc3
2. pod lib lint tensorflow/lite/experimental/ios/TensorFlowLiteC.podspec

Error Message:
    - ERROR | [TensorFlowLiteC/Core, TensorFlowLiteC/CoreML, TensorFlowLiteC/Metal, and more...] file patterns: The `vendored_frameworks` pattern did not match any file.

**Describe the expected behavior**
Linter should not have any errors. 

When working on my private podspec, I saw the same error and went back to check the original source code and found this issues. 

I also downloaded the source file `TensorFlowLiteC.tar.gz` specified in the podspec. The root folder of the unzipped data is not `Frameworks` but `TensorFlowLiteC-2.3.0`.

The document [here](https://www.tensorflow.org/lite/guide/build_ios) is outdated. The process of combining `TensorFlowLiteC.framework`, `TensorFlowLiteCCoreML.framework` and `TensorflowLiteCMetal.framework` is not documented. Definitely need some help.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

1. git checkout v2.4.0-rc3
2. pod lib lint tensorflow/lite/experimental/ios/TensorFlowLiteC.podspec

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by brucechou1983** [comment]
I found that this issue actually happens in 2.3.0 as well.

**Comment by terryheo** [comment]
@yyoon could you check the pod lint error?

**Comment by yyoon** [comment]
Sorry for the late reply. As of e8b6278a88939b5f2004dd7ebc2f8eb150f9841b, you should be able to run `pod spec lint TensorFlowLiteC.podspec --allow-warnings` and see it pass. There are a few things to note.

First, when a new TF stable release is published (e.g., `v2.4.0` tag which just got released), we update the `.podspec` files on `master` branch *after* the release branch is published. It's unfortunate and confusing, but the main reason for doing this is that we need to build the static framework from the release branch, host the prebuilt binary on our download server, and then use the new URL in the `.podspec` file to be used as the source of the `TensorFlowLiteC` pod.

In that sense, I guess it would be awkward to use `pod lib lint` command in a release tag checkout as is. You might want to copy over the `.podspec` files from the following master version and run `pod lib lint` if you need to.

Second, there is a known issue with Xcode 12 and CocoaPod CLI's lint feature. Our default Xcode version used for these prebuilts is currently 11, which is confirmed to work, but with Xcode 12 you might be hitting issues like (e.g., https://github.com/CocoaPods/CocoaPods/issues/10104). In that case, you could either use the `--skip-import-validation` or, add the `s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }` line in the `.podspec` and run the lint again.

**Comment by brucechou1983** [comment]
No luck. I did the following steps:

1. checkout `e8b6278`
2. run `pod lib lint TensorFlowLiteC.podspec --allow-warnings`

> - ERROR | [TensorFlowLiteC/Core, TensorFlowLiteC/CoreML, TensorFlowLiteC/Metal, and more...] file patterns: The `vendored_frameworks` pattern did not match any file.

It seems to me that the option `--allow-warnings` doesn't help with errors. I also tried the other two solutions you mentioned, but still got the same error message complaining about the file patterns. 

xcode: Version 12.2 (12B45b)
pod version: 1.10.0

**Comment by yyoon** [comment]
For `TensorFlowLiteC` and its subspecs, we rely on prebuilt static framework archives hosted on Google's download server, as you can see in the `.podspec` files.

I was referring to `pod spec lint` command, which downloads these prebuilt files and runs verification steps for the downloaded prebuilt archive, and this should work, as I mentioned above.

On the other hand, `pod lib lint` is expected to not work AFAIK, because it ignores all the download URLs, etc. and uses the current local directory as the source. The tensorflow checkout directory does not contain the prebuilt binaries (as it only contains source files), and thus it is failing as expected.

Can you share what you actually want to achieve? What makes you want to run `pod lib lint` command?
