### ISSUE TITLE
raw_rnn

### ISSUE THREAD

**Issue by alrojo** [tensorflow/tensorflow#4519]
For @ebrevdo on his new [raw_rnn implementation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/rnn.py#L1018).

In your [example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/rnn.py#L1064)

When you define `next_input` as the following:
```python
elements_finished = (time >= sequence_length)
...
next_input = tf.cond(
    finished,
    lambda: tf.zeros([batch_size, input_depth], dtype=tf.float32),
    lambda: inputs_ta.read(time))
```

Why make it return an zero input? Will this not cause the last state to be computed incorrectly (with zeros as input)?

Alternatively the zero input can be removed, by rewriting it the following way
```python
elements_finished = (time >= (sequence_length-1))
...
next_input = inputs_ta.read(time)
```

Thanks

**Comment by alrojo** [comment]
Or wait ... the zero state won't actually be used because `(next_output, cell_state) = cell(current_input, state)` happens before ...

**Comment by ebrevdo** [comment]
Yeah it's an unfortunate consequence of every calculation needing some
value to be provided. Nevertheless there's no slowdown from this extra cond.
