### ISSUE TITLE
tf.data.experimental.make_csv_dataset changes list of column names if it is not hard coded

### ISSUE THREAD

**Issue by hosseinece** [tensorflow/tensorflow#45194]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS release 6.10
- TensorFlow version (use command below): Version: 2.2.0
- Python version: Python 3.8.3 (default, Jul  2 2020, 16:21:59)
- GPU model and memory: NVIDIA, 64 GB RAM

**Describe the current behavior**
I am trying to use tf.data.experimental.make_csv_dataset to read data from a very large csv file (million rows and million columns). If I hard code select_columns in the following sample code with select_columns=['col1','col2','col3']) then tf.data.experimental.make_csv_dataset works fine. But, when I extract column names and put them in a python list, My_Variables in the following line of code, then tf.data.experimental.make_csv_dataset changes My_Variables python list and it can not find label_name anymore:

    def get_dataset(file_path):
      dataset = tf.data.experimental.make_csv_dataset(
          file_path,
          batch_size=64, # Artificially small to make examples easier to show.
          select_columns=My_Variables,
          label_name= 'outcome',
          na_value="?",
          num_epochs=1,
          num_rows_for_inference=64,
         ignore_errors=True)
      return dataset

**Describe the expected behavior**

Expected behavior after running tf.data.experimental.make_csv_dataset: 

    My_Variables=['col1','col2','col3',...,'outcome']

current behavior after running tf.data.experimental.make_csv_dataset: 

    My_Variables=[1,2,3,4,5,6,7,...,10345]

Error message:

    raise ValueError("`label_name` provided must be one of the columns.")
    ValueError: `label_name` provided must be one of the columns.

I can not hard code variables in tf.data.experimental.make_csv_dataset function. I need to extract column names, put them in a python list and then used it inside tf.data.experimental.make_csv_dataset but this method breaks tf.data.experimental.make_csv_dataset

**Comment by Saduf2019** [comment]
@hosseinece 
Please share complete code to replicate the issue faced or if possible share a colab gist with the issue reported.

**Comment by hosseinece** [comment]
The fact that variables changes after the call to make_csv_dataset seems indeed like an unwanted border effect. For the border effect, I used a simple workaround by copying the variable before making the call to make_csv_dataset and it solved my issue.

**Comment by Saduf2019** [comment]
@hosseinece 
Please move this issue to closed status if resolved.
