### ISSUE TITLE
Didn't find op for builtin opcode 'GATHER' version '1'

### ISSUE THREAD

**Issue by crumpf-sdsu** [tensorflow/tensorflow#45196]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu Linux 20.04
- TensorFlow installed from (source or binary): binary python3 pip3
- Tensorflow version (commit SHA if source): 2.4-rc3
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): arm mbed-os disco_f746ng 

**Describe the problem**
```
  TfLiteStatus allocate_status = interpreter->AllocateTensors();
```
fails with
```
Didn't find op for builtin opcode 'GATHER' version '1'                                                
Failed to get registration from op code GATHER                                               
Failed starting model allocation.
AllocateTensors() failed
```
**Please provide the exact sequence of commands/steps when you ran into the problem**

All attachments can be found at: [https://github.com/crumpf-sdsu/gath-op-bug-report](https://github.com/crumpf-sdsu/gath-op-bug-report)
Basically, I used https://github.com/tensorflow/docs/blob/master/site/en/tutorials/structured_data/time_series.ipynb to create a split window single step (+1hr predictive) linear model using the NOAA dataset (a weather data localized to my zip code).  The model performs adequately for my needs in Jupyter.  The model is successfully converted to tflite (no quant).   Standard tflite micro interpreter setup() (from hello world) fails to AllocateTensors with  missing GATHER op using AllOpsResolver.  

```
void setup() {
...
  // This pulls in all the operation implementations we need.
  // NOLINTNEXTLINE(runtime-global-variables)
  static tflite::AllOpsResolver resolver;

  // Build an interpreter to run the model with.
  static tflite::MicroInterpreter static_interpreter(
      model, resolver, tensor_arena, kTensorArenaSize, error_reporter);
  interpreter = &static_interpreter;

  // Allocate memory from the tensor_arena for the model's tensors.
  TfLiteStatus allocate_status = interpreter->AllocateTensors();
  if (allocate_status != kTfLiteOk) {
    TF_LITE_REPORT_ERROR(error_reporter, "AllocateTensors() failed");
    return;
  }
```
Aside from AllOpsResolver documentation/customizations, I didn't find much information about missing ops such as this and figured I'd ask to triple check my approach and get some advice here.

**Comment by rsun-bdti** [comment]
I will start porting the GATHER operator from TFLite to TFLite Micro now.

**Comment by rsun-bdti** [comment]
The merging of PR #49495 should solve the issue.
