### ISSUE TITLE
Tensorflow 2.3.0 Bazel 3.1.0 compile ERROR

### ISSUE THREAD

**Issue by iamweiweishi** [tensorflow/tensorflow#45205]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform: Ubuntu 16.04:
- TensorFlow installed from (source or binary):source
- TensorFlow version:2.3.0
- Python version:3.5
- Bazel version (if compiling from source):3.1.0
- GCC/Compiler version (if compiling from source):5.4.0 / 7.3.0 / 7.5.0
- CUDA/cuDNN version:10.1
- GPU model and memory:V100
- cudnn version:7.6.5

Compile Config:
build --action_env PYTHON_BIN_PATH="/home/anaconda3/bin/python3"
build --action_env PYTHON_LIB_PATH="/home/anaconda3/lib/python3.5/site-packages"
build --python_path="/home/anaconda3/bin/python3"
build --config=xla
build --action_env CUDA_TOOLKIT_PATH="/usr/local/cuda-10.1"
build --action_env TF_CUDA_COMPUTE_CAPABILITIES="3.5,7.0"
build --action_env LD_LIBRARY_PATH="/home/install/gcc-7.3.0/lib
build --action_env GCC_HOST_COMPILER_PATH="/home/install/gcc-7.3.0/bin/gcc"
build --config=cuda
build:opt --copt=-march=native
build:opt --copt=-Wno-sign-compare
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test --test_env=LD_LIBRARY_PATH
test:v1 --test_tag_filters=-benchmark-test,-no_oss,-no_gpu,-oss_serial
test:v1 --build_tag_filters=-benchmark-test,-no_oss,-no_gpu
test:v2 --test_tag_filters=-benchmark-test,-no_oss,-no_gpu,-oss_serial,-v1only
test:v2 --build_tag_filters=-benchmark-test,-no_oss,-no_gpu,-v1only
build --action_env TF_CONFIGURE_IOS="0"

**Describe the problem**
I tried to build tensorflow 2.3.0 from source using bazel. I also checked the requirements of GCC, CUDA, and CUDNN. 
But the error still occured:

ERROR: /home/code/release/tensorflow-2.3.0/tensorflow/stream_executor/cuda/BUILD:457:1: C++ compilation of rule '//tensorflow/stream_executor/cuda:cusparse_stub' failed (Exit 1)
In file included from tensorflow/stream_executor/cuda/cusparse_stub.cc:59:0:
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7786:21: error: 'cusparseSpVecDescr_t' was not declared in this scope
 cusparseCreateSpVec(cusparseSpVecDescr_t *spVecDescr, int64_t size, int64_t nnz,
                     ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7786:43: error: 'spVecDescr' was not declared in this scope
 cusparseCreateSpVec(cusparseSpVecDescr_t *spVecDescr, int64_t size, int64_t nnz,
                                           ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7786:63: error: expected primary-expression before 'size'
 cusparseCreateSpVec(cusparseSpVecDescr_t *spVecDescr, int64_t size, int64_t nnz,
                                                               ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7786:77: error: expected primary-expression before 'nnz'
 cusparseCreateSpVec(cusparseSpVecDescr_t *spVecDescr, int64_t size, int64_t nnz,
                                                                             ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7787:21: error: expected primary-expression before 'void'
                     void *indices, void *values, cusparseIndexType_t idxType,
                     ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7787:36: error: expected primary-expression before 'void'
                     void *indices, void *values, cusparseIndexType_t idxType,
                                    ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7787:70: error: expected primary-expression before 'idxType'
                     void *indices, void *values, cusparseIndexType_t idxType,
                                                                      ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7788:41: error: expected primary-expression before 'idxBase'
                     cusparseIndexBase_t idxBase, cudaDataType valueType) {
                                         ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7788:63: error: expected primary-expression before 'valueType'
                     cusparseIndexBase_t idxBase, cudaDataType valueType) {
                                                               ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7788:72: error: expression list treated as compound expression in initializer [-fpermissive]
                     cusparseIndexBase_t idxBase, cudaDataType valueType) {
                                                                        ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7788:74: error: expected ',' or ';' before '{' token
                     cusparseIndexBase_t idxBase, cudaDataType valueType) {
                                                                          ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7799:22: error: 'cusparseSpVecDescr_t' was not declared in this scope
 cusparseDestroySpVec(cusparseSpVecDescr_t spVecDescr) {
                      ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7799:55: error: expected ',' or ';' before '{' token
 cusparseDestroySpVec(cusparseSpVecDescr_t spVecDescr) {
                                                       ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7807:11: error: 'cusparseSpVecDescr_t' does not name a type
     const cusparseSpVecDescr_t spVecDescr, int64_t *size, int64_t *nnz,
           ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: In function 'cusparseStatus_t cusparseSpVecGet(int, int64_t*, int64_t*, void**, void**, cusparseIndexType_t*, cusparseIndexBase_t*, cudaDataType*)':
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7811:13: error: 'cusparseSpVecDescr_t' does not name a type
       const cusparseSpVecDescr_t, int64_t *, int64_t *, void **, void **,
             ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: At global scope:
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7820:11: error: 'cusparseSpVecDescr_t' does not name a type
     const cusparseSpVecDescr_t spVecDescr, cusparseIndexBase_t *idxBase) {
           ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: In function 'cusparseStatus_t cusparseSpVecGetIndexBase(int, cusparseIndexBase_t*)':
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7821:57: error: 'cusparseSpVecDescr_t' does not name a type
   using FuncPtr = cusparseStatus_t(CUSPARSEAPI *)(const cusparseSpVecDescr_t,
                                                         ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: At global scope:
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7829:30: error: 'cusparseSpVecDescr_t' does not name a type
 cusparseSpVecGetValues(const cusparseSpVecDescr_t spVecDescr, void **values) {
                              ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: In function 'cusparseStatus_t cusparseSpVecGetValues(int, void**)':
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7831:45: error: 'cusparseSpVecDescr_t' does not name a type
       cusparseStatus_t(CUSPARSEAPI *)(const cusparseSpVecDescr_t, void **);
                                             ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: At global scope:
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7838:24: error: 'cusparseSpVecDescr_t' was not declared in this scope
 cusparseSpVecSetValues(cusparseSpVecDescr_t spVecDescr, void *values) {
                        ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7838:57: error: expected primary-expression before 'void'
 cusparseSpVecSetValues(cusparseSpVecDescr_t spVecDescr, void *values) {
                                                         ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7838:69: error: expression list treated as compound expression in initializer [-fpermissive]
 cusparseSpVecSetValues(cusparseSpVecDescr_t spVecDescr, void *values) {
                                                                     ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7838:71: error: expected ',' or ';' before '{' token
 cusparseSpVecSetValues(cusparseSpVecDescr_t spVecDescr, void *values) {
                                                                       ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7846:21: error: 'cusparseDnVecDescr_t' was not declared in this scope
 cusparseCreateDnVec(cusparseDnVecDescr_t *dnVecDescr, int64_t size,
                     ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7846:43: error: 'dnVecDescr' was not declared in this scope
 cusparseCreateDnVec(cusparseDnVecDescr_t *dnVecDescr, int64_t size,
                                           ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7846:63: error: expected primary-expression before 'size'
 cusparseCreateDnVec(cusparseDnVecDescr_t *dnVecDescr, int64_t size,
                                                               ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7847:21: error: expected primary-expression before 'void'
                     void *values, cudaDataType valueType) {
                     ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7847:48: error: expected primary-expression before 'valueType'
                     void *values, cudaDataType valueType) {
                                                ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7847:57: error: expression list treated as compound expression in initializer [-fpermissive]
                     void *values, cudaDataType valueType) {
                                                         ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7847:59: error: expected ',' or ';' before '{' token
                     void *values, cudaDataType valueType) {
                                                           ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7856:22: error: 'cusparseDnVecDescr_t' was not declared in this scope
 cusparseDestroyDnVec(cusparseDnVecDescr_t dnVecDescr) {
                      ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7856:55: error: expected ',' or ';' before '{' token
 cusparseDestroyDnVec(cusparseDnVecDescr_t dnVecDescr) {
                                                       ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7864:24: error: 'cusparseDnVecDescr_t' does not name a type
 cusparseDnVecGet(const cusparseDnVecDescr_t dnVecDescr, int64_t *size,
                        ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: In function 'cusparseStatus_t cusparseDnVecGet(int, int64_t*, void**, cudaDataType*)':
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7867:13: error: 'cusparseDnVecDescr_t' does not name a type
       const cusparseDnVecDescr_t, int64_t *, void **, cudaDataType *);
             ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: At global scope:
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7874:30: error: 'cusparseDnVecDescr_t' does not name a type
 cusparseDnVecGetValues(const cusparseDnVecDescr_t dnVecDescr, void **values) {
                              ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: In function 'cusparseStatus_t cusparseDnVecGetValues(int, void**)':
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7876:45: error: 'cusparseDnVecDescr_t' does not name a type
       cusparseStatus_t(CUSPARSEAPI *)(const cusparseDnVecDescr_t, void **);
                                             ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: At global scope:
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7883:24: error: 'cusparseDnVecDescr_t' was not declared in this scope
 cusparseDnVecSetValues(cusparseDnVecDescr_t dnVecDescr, void *values) {
                        ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7883:57: error: expected primary-expression before 'void'
 cusparseDnVecSetValues(cusparseDnVecDescr_t dnVecDescr, void *values) {
                                                         ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7883:69: error: expression list treated as compound expression in initializer [-fpermissive]
 cusparseDnVecSetValues(cusparseDnVecDescr_t dnVecDescr, void *values) {
                                                                     ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7883:71: error: expected ',' or ';' before '{' token
 cusparseDnVecSetValues(cusparseDnVecDescr_t dnVecDescr, void *values) {
                                                                       ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: In function 'cusparseStatus_t cusparseCreateCoo(cusparseSpMatDescr**, int64_t, int64_t, int64_t, void*, void*, void*, cusparseIndexType_t, cusparseIndexBase_t, cudaDataType)':
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7896:70: error: conflicting declaration of C function 'cusparseStatus_t cusparseCreateCoo(cusparseSpMatDescr**, int64_t, int64_t, int64_t, void*, void*, void*, cusparseIndexType_t, cusparseIndexBase_t, cudaDataType)'
                                                cudaDataType valueType) {
                                                                      ^
In file included from tensorflow/stream_executor/cuda/cusparse_stub.cc:16:0:
bazel-out/host/bin/external/local_config_cuda/cuda/_virtual_includes/cuda_headers_virtual/third_party/gpus/cuda/include/cusparse.h:6971:1: note: previous declaration 'cusparseStatus_t cusparseCreateCoo(cusparseSpMatDescr**, int, int, int, void*, void*, void*, cusparseIndexType_t, cusparseIndexBase_t, cudaDataType)'
 cusparseCreateCoo(cusparseSpMatDescr_t* spMatDescr,
 ^
In file included from tensorflow/stream_executor/cuda/cusparse_stub.cc:59:0:
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: In function 'cusparseStatus_t cusparseCooGet(cusparseSpMatDescr_t, int64_t*, int64_t*, int64_t*, void**, void**, void**, cusparseIndexType_t*, cusparseIndexBase_t*, cudaDataType*)':
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:7950:39: error: conflicting declaration of C function 'cusparseStatus_t cusparseCooGet(cusparseSpMatDescr_t, int64_t*, int64_t*, int64_t*, void**, void**, void**, cusparseIndexType_t*, cusparseIndexBase_t*, cudaDataType*)'
                cudaDataType *valueType) {
                                       ^
In file included from tensorflow/stream_executor/cuda/cusparse_stub.cc:16:0:
bazel-out/host/bin/external/local_config_cuda/cuda/_virtual_includes/cuda_headers_virtual/third_party/gpus/cuda/include/cusparse.h:6986:1: note: previous declaration 'cusparseStatus_t cusparseCooGet(cusparseSpMatDescr_t, int*, int*, int*, void**, void**, void**, cusparseIndexType_t*, cusparseIndexBase_t*, cudaDataType*)'
 cusparseCooGet(const cusparseSpMatDescr_t spMatDescr,
 ^
In file included from tensorflow/stream_executor/cuda/cusparse_stub.cc:59:0:
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: In function 'cusparseStatus_t cusparseCreateDnMat(cusparseDnMatDescr**, int64_t, int64_t, int64_t, void*, cudaDataType, cusparseOrder_t)':
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8047:64: error: conflicting declaration of C function 'cusparseStatus_t cusparseCreateDnMat(cusparseDnMatDescr**, int64_t, int64_t, int64_t, void*, cudaDataType, cusparseOrder_t)'
     void *values, cudaDataType valueType, cusparseOrder_t order) {
                                                                ^
In file included from tensorflow/stream_executor/cuda/cusparse_stub.cc:16:0:
bazel-out/host/bin/external/local_config_cuda/cuda/_virtual_includes/cuda_headers_virtual/third_party/gpus/cuda/include/cusparse.h:7017:1: note: previous declaration 'cusparseStatus_t cusparseCreateDnMat(cusparseDnMatDescr**, size_t, size_t, int64_t, void*, cudaDataType, cusparseOrder_t)'
 cusparseCreateDnMat(cusparseDnMatDescr_t* dnMatDescr,
 ^
In file included from tensorflow/stream_executor/cuda/cusparse_stub.cc:59:0:
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: In function 'cusparseStatus_t cusparseDnMatGet(cusparseDnMatDescr_t, int64_t*, int64_t*, int64_t*, void**, cudaDataType*, cusparseOrder_t*)':
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8066:75: error: conflicting declaration of C function 'cusparseStatus_t cusparseDnMatGet(cusparseDnMatDescr_t, int64_t*, int64_t*, int64_t*, void**, cudaDataType*, cusparseOrder_t*)'
     int64_t *ld, void **values, cudaDataType *type, cusparseOrder_t *order) {
                                                                           ^
In file included from tensorflow/stream_executor/cuda/cusparse_stub.cc:16:0:
bazel-out/host/bin/external/local_config_cuda/cuda/_virtual_includes/cuda_headers_virtual/third_party/gpus/cuda/include/cusparse.h:7029:1: note: previous declaration 'cusparseStatus_t cusparseDnMatGet(cusparseDnMatDescr_t, size_t*, size_t*, int64_t*, void**, cudaDataType*, cusparseOrder_t*)'
 cusparseDnMatGet(const cusparseDnMatDescr_t dnMatDescr,
 ^
In file included from tensorflow/stream_executor/cuda/cusparse_stub.cc:59:0:
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: In function 'cusparseStatus_t cusparseDnMatSetStridedBatch(cusparseDnMatDescr_t, int, int64_t)':
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8093:73: error: conflicting declaration of C function 'cusparseStatus_t cusparseDnMatSetStridedBatch(cusparseDnMatDescr_t, int, int64_t)'
     cusparseDnMatDescr_t dnMatDescr, int batchCount, int64_t batchStride) {
                                                                         ^
In file included from tensorflow/stream_executor/cuda/cusparse_stub.cc:16:0:
bazel-out/host/bin/external/local_config_cuda/cuda/_virtual_includes/cuda_headers_virtual/third_party/gpus/cuda/include/cusparse.h:7038:1: note: previous declaration 'cusparseStatus_t cusparseDnMatSetStridedBatch(cusparseDnMatDescr_t, int, size_t)'
 cusparseDnMatSetStridedBatch(cusparseDnMatDescr_t dnMatDescr,
 ^
In file included from tensorflow/stream_executor/cuda/cusparse_stub.cc:59:0:
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: In function 'cusparseStatus_t cusparseDnMatGetStridedBatch(cusparseDnMatDescr_t, int*, int64_t*)':
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8103:67: error: conflicting declaration of C function 'cusparseStatus_t cusparseDnMatGetStridedBatch(cusparseDnMatDescr_t, int*, int64_t*)'
                              int *batchCount, int64_t *batchStride) {
                                                                   ^
In file included from tensorflow/stream_executor/cuda/cusparse_stub.cc:16:0:
bazel-out/host/bin/external/local_config_cuda/cuda/_virtual_includes/cuda_headers_virtual/third_party/gpus/cuda/include/cusparse.h:7043:1: note: previous declaration 'cusparseStatus_t cusparseDnMatGetStridedBatch(cusparseDnMatDescr_t, int*, size_t*)'
 cusparseDnMatGetStridedBatch(const cusparseDnMatDescr_t dnMatDescr,
 ^
In file included from tensorflow/stream_executor/cuda/cusparse_stub.cc:59:0:
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: At global scope:
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8113:20: error: 'cusparseSpVecDescr_t' does not name a type
              const cusparseSpVecDescr_t vecX, const cusparseDnVecDescr_t vecY,
                    ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8113:53: error: 'cusparseDnVecDescr_t' does not name a type
              const cusparseSpVecDescr_t vecX, const cusparseDnVecDescr_t vecY,
                                                     ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: In function 'cusparseStatus_t cusparseSpVV(cusparseHandle_t, cusparseOperation_t, int, int, void*, cudaDataType, void*)':
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8116:52: error: 'cusparseSpVecDescr_t' does not name a type
       cusparseHandle_t, cusparseOperation_t, const cusparseSpVecDescr_t,
                                                    ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8117:13: error: 'cusparseDnVecDescr_t' does not name a type
       const cusparseDnVecDescr_t, void *, cudaDataType, void *);
             ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: At global scope:
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8125:11: error: 'cusparseSpVecDescr_t' does not name a type
     const cusparseSpVecDescr_t vecX, const cusparseDnVecDescr_t vecY,
           ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8125:44: error: 'cusparseDnVecDescr_t' does not name a type
     const cusparseSpVecDescr_t vecX, const cusparseDnVecDescr_t vecY,
                                            ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: In function 'cusparseStatus_t cusparseSpVV_bufferSize(cusparseHandle_t, cusparseOperation_t, int, int, const void*, cudaDataType, size_t*)':
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8128:52: error: 'cusparseSpVecDescr_t' does not name a type
       cusparseHandle_t, cusparseOperation_t, const cusparseSpVecDescr_t,
                                                    ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8129:13: error: 'cusparseDnVecDescr_t' does not name a type
       const cusparseDnVecDescr_t, const void *, cudaDataType, size_t *);
             ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: At global scope:
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8137:44: error: 'cusparseDnVecDescr_t' does not name a type
     const cusparseSpMatDescr_t matA, const cusparseDnVecDescr_t vecX,
                                            ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8138:29: error: 'cusparseDnVecDescr_t' does not name a type
     const void *beta, const cusparseDnVecDescr_t vecY, cudaDataType computeType,
                             ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8139:5: error: 'cusparseSpMVAlg_t' has not been declared
     cusparseSpMVAlg_t alg, void *externalBuffer) {
     ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: In function 'cusparseStatus_t cusparseSpMV(cusparseHandle_t, cusparseOperation_t, const void*, cusparseSpMatDescr_t, int, const void*, int, cudaDataType, int, void*)':
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8142:41: error: 'cusparseDnVecDescr_t' does not name a type
       const cusparseSpMatDescr_t, const cusparseDnVecDescr_t, const void *,
                                         ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8143:13: error: 'cusparseDnVecDescr_t' does not name a type
       const cusparseDnVecDescr_t, cudaDataType, cusparseSpMVAlg_t, void *);
             ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8143:49: error: 'cusparseSpMVAlg_t' has not been declared
       const cusparseDnVecDescr_t, cudaDataType, cusparseSpMVAlg_t, void *);
                                                 ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: At global scope:
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8152:44: error: 'cusparseDnVecDescr_t' does not name a type
     const cusparseSpMatDescr_t matA, const cusparseDnVecDescr_t vecX,
                                            ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8153:29: error: 'cusparseDnVecDescr_t' does not name a type
     const void *beta, const cusparseDnVecDescr_t vecY, cudaDataType computeType,
                             ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8154:5: error: 'cusparseSpMVAlg_t' has not been declared
     cusparseSpMVAlg_t alg, size_t *bufferSize) {
     ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc: In function 'cusparseStatus_t cusparseSpMV_bufferSize(cusparseHandle_t, cusparseOperation_t, const void*, cusparseSpMatDescr_t, int, const void*, int, cudaDataType, int, size_t*)':
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8157:41: error: 'cusparseDnVecDescr_t' does not name a type
       const cusparseSpMatDescr_t, const cusparseDnVecDescr_t, const void *,
                                         ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8158:13: error: 'cusparseDnVecDescr_t' does not name a type
       const cusparseDnVecDescr_t, cudaDataType, cusparseSpMVAlg_t, size_t *);
             ^
./tensorflow/stream_executor/cuda/cusparse_10_1.inc:8158:49: error: 'cusparseSpMVAlg_t' has not been declared
       const cusparseDnVecDescr_t, cudaDataType, cusparseSpMVAlg_t, size_t *);
                                                 ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/code/release/tensorflow-2.3.0/tensorflow/tools/pip_package/BUILD:66:1 C++ compilation of rule '//tensorflow/stream_executor/cuda:cusparse_stub' failed (Exit 1)
INFO: Elapsed time: 678.697s, Critical Path: 218.52s
INFO: 11196 processes: 11196 local.
FAILED: Build did NOT complete successfully

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel build --config=opt --config=cuda --copt=-fstack-protector-strong --copt=-fPIC --copt=-U_FORTIFY_SOURCE --copt=-D_FORTIFY_SOURCE=2 --copt=-O3 --linkopt=-Wl,-z,relro --linkopt=-Wl,-z,now --linkopt=-Wl,-z,noexecstack --linkopt=-Wl,--strip-all --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package

And I also tried:
bazel build --config=opt --config=cuda --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package

Thank you.

**Comment by amahendrakar** [comment]
@iamweiweishi,
Please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/40260#issuecomment-644477690) from a similar issue and let us know if you are still facing the same issue. Thanks!

**Comment by iamweiweishi** [comment]
I added the '--action_env PATH --action_env LD_LIBRARY_PATH --action_env DYLD_LIBRARY_PATH' cmd, but the error is still the same. 

Then I upgrade the gcc to 7.3.0.
The Error changed:
ERROR: /home/code/release/tensorflow-2.3.0/tensorflow/compiler/tf2xla/cc/BUILD:30:1: Linking of rule '//tensorflow/compiler/tf2xla/cc:ops/xla_jit_ops_gen_cc' failed (Exit 1)
bazel-out/k8-opt-exec-50AE0418/bin/_solib_local/_U_S_Stensorflow_Scompiler_Stf2xla_Scc_Cops_Sxla_Ujit_Uops_Ugen_Ucc___Utensorflow/libtensorflow_framework.so.2: undefined reference to `std::allocator<long long>::allocator()'
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 883.963s, Critical Path: 256.13s
INFO: 13660 processes: 13660 local.
FAILED: Build did NOT complete successfully

Thank you.

**Comment by aaronmondal** [comment]
I would suggest using the [Docker build process](https://www.tensorflow.org/install/source#docker_linux_builds), which is a lot less error-prone. Builds often fail because of unlucky combinations of build-tool versions. The docker images handle that for you.

**Comment by smistad** [comment]
I experienced the same errors with tensorflow 2.3.0 on Ubuntu 20.04, GCC 8 and cuda 10.1. Note however that I am building the C++ library and not the pip package: //tensorflow:libtensorflow_cc.so, still the errors I get are the same. I had installed cuda using the open source nvidia-cuda-toolkit package (sudo apt install nvidia-cuda-toolkit). I read somewhere on github (can't find the source now), that building TF from source was not compatible with this package. Thus, I removed this package, and instead installed cuda version 10.1 243 for Ubuntu 18.04: 
```bash
sudo apt remove --purge nvidia-cuda-toolkit
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.1.243-1_amd64.deb
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
sudo dpkg -i cuda-repo-ubuntu1804_10.1.243-1_amd64.deb
sudo apt-get update
sudo apt install cuda
```

Then I installed cudnn 7.6.5 for cuda 10.1 from the deb packages on nvidia's webpage.

If you try to rebuild now, you will get the same error, this is because bazel has a cache. Delete this cache:
```bash
rm -Rf /home/<your username>/.cache/bazel/
```
I also deleted the whole build folder and started all over.
These errors where then gone.

Hope this helps others, and I hope that someday nvidia will clean up their software distribution methodology which currently, in my opinion, is a complete mess.

**Comment by sanatmpa1** [comment]
@iamweiweishi,

Can you try installing the latest stable version of tensorflow i.e `2.6.0` using this [guide](https://www.tensorflow.org/install/source#tested_build_configurations) to build from source. Also make sure that you have the supported version of CUDA,CUDNN,compiler as per the [tested build configurations](https://www.tensorflow.org/install/source#gpu) section. Thanks!
