### ISSUE TITLE
ResizeBilinear op with half_pixel_centers true not support by nnapi

### ISSUE THREAD

**Issue by sunzhe09** [tensorflow/tensorflow#45207]
**System information**android 11
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):16.04
- TensorFlow installed from (source or binary):pip
- TensorFlow version (or github SHA if from source):2.3-2.4

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
   kerasmodel=tf.keras.models.load_model('./log',compile=False)
    input_name = kerasmodel.input_names[0]
    index = kerasmodel.input_names.index(input_name)
    kerasmodel.inputs[index].set_shape([1, 320, 320,1])
    ind =0
    for layer in kerasmodel.layers:
        print(layer.name)
        if layer.name=="up_p3" or layer.name=="up_p4":
            print("###############################")
            
            kerasmodel.layers[ind].half_pixel_centers=False
            print(kerasmodel.layers[ind].half_pixel_centers)
         
        ind+=1
    
  
#     kerasmodel.summary()
#     exit()
    
    converter = tf.lite.TFLiteConverter.from_keras_model(kerasmodel)   
    #converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir="./log")
    converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]#tf.lite.OpsSet.SELECT_TF_OPS]
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = tf.lite.RepresentativeDataset(representative_dataset_gen) 
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    converter.experimental_new_converter = True
    tflite_model_quant = converter.convert()
    import pathlib
    tflite_model_quant_file = pathlib.Path("./")/"test2.4.tflite"
    tflite_model_quant_file.write_bytes(tflite_model_quant)
```

**The output from the converter invocation**

```
# Copy and paste the output here.
![image](https://user-images.githubusercontent.com/30410113/100355529-e692b280-302c-11eb-8f54-1f49c3646d90.png)
when i test it with benchmark abort occur!so i find the log with:
11-26 19:53:25.830  1061 27513 E hta-unnhal: {PAD, TENSOR_QUANT8} is not supported.
11-26 19:53:25.830  1061 27513 E hta-unnhal: Doesn't support half pixel centers for RESIZE_BILINEAR
11-26 19:53:25.830  1061 27513 E hta-unnhal: {RESIZE_BILINEAR, TENSOR_QUANT8} is not supported.
11-26 19:53:25.830  1061 27513 E hta-unnhal: Doesn't support half pixel centers for RESIZE_BILINEAR
11-26 19:53:25.830  1061 27513 E hta-unnhal: {RESIZE_BILINEAR, TENSOR_QUANT8} is not supported.
![image](https://user-images.githubusercontent.com/30410113/100355495-d7136980-302c-11eb-88cf-5002c60428f9.png)
I set the half_pixel_centers with False before convert but when i get tflite it is still true
```

**Also, please include a link to the saved model or GraphDef**
![image](https://user-images.githubusercontent.com/30410113/100355786-5143ee00-302d-11eb-88ae-c1804ddabf10.png)

```
# Put link here or attach to the issue.
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@sunzhe09 
Code shared is not indented and incomplete,please share a colab gist with the error reported.

**Comment by sunzhe09** [comment]
@Saduf2019 I just want to edit the attribute half_pixel_centers to false,is there any way to do this?you can compare my model,the left is tf1.15 converted,the right is tf2.3 converted
![image](https://user-images.githubusercontent.com/30410113/100400119-49696580-3090-11eb-9352-c15308066ae3.png)

**Comment by sunzhe09** [comment]
@Saduf2019 I‘m sorry，I have test the model crash is not about with half_pixel_centers attrbute。I just test the model with android_aarch64_benchmark_model but after initialized  it crashed。there is the  log：
01-26 07:15:10.172 32429 32429 I tflite  : Initialized TensorFlow Lite runtime.
01-26 07:15:10.172 32429 32429 I tflite  : Created TensorFlow Lite delegate for NNAPI.
01-26 07:15:10.173 32429 32429 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 32429 (android_aarch64), pid 32429 (android_aarch64)
01-26 07:15:10.195 32433 32433 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
01-26 07:15:10.196   609   609 I tombstoned: received crash request for pid 32429
01-26 07:15:10.197 32433 32433 I crash_dump64: performing dump of process 32429 (target tid = 32429)
01-26 07:15:10.200 32433 32433 F DEBUG   : Process name is ./android_aarch64_benchmark_model, not key_process
01-26 07:15:10.200 32433 32433 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-26 07:15:10.200 32433 32433 F DEBUG   : Build fingerprint: 'OPPO/CPH2125/OP4C51L1:11/RP1A.200709.001/1600212156653:user/release-keys'
01-26 07:15:10.200 32433 32433 F DEBUG   : Revision: '0'
01-26 07:15:10.200 32433 32433 F DEBUG   : ABI: 'arm64'
01-26 07:15:10.200 32433 32433 F DEBUG   : Timestamp: 2010-01-26 07:15:10+0800
01-26 07:15:10.200 32433 32433 F DEBUG   : pid: 32429, tid: 32429, name: android_aarch64  >>> ./android_aarch64_benchmark_model <<<
01-26 07:15:10.200 32433 32433 F DEBUG   : uid: 0
01-26 07:15:10.200 32433 32433 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
01-26 07:15:10.200 32433 32433 F DEBUG   :     x0  0000000000000000  x1  0000000000007ead  x2  0000000000000006  x3  0000007fe0631a60
01-26 07:15:10.200 32433 32433 F DEBUG   :     x4  0000000000000001  x5  0000000000000001  x6  0000000000000001  x7  0000000000000001
01-26 07:15:10.200 32433 32433 F DEBUG   :     x8  00000000000000f0  x9  00000070a9f6c898  x10 ffffff80ffffffdf  x11 0000000000000001
01-26 07:15:10.200 32433 32433 F DEBUG   :     x12 0000000000000001  x13 0000000000000091  x14 000000000000000d  x15 0000000000000000
01-26 07:15:10.200 32433 32433 F DEBUG   :     x16 00000070aa02b7e0  x17 00000070aa00b330  x18 0000000000000028  x19 0000000000007ead
01-26 07:15:10.201 32433 32433 F DEBUG   :     x20 0000000000007ead  x21 00000000ffffffff  x22 0000000000000001  x23 b4000070a92fe3d0
01-26 07:15:10.201 32433 32433 F DEBUG   :     x24 b4000070a924d0ac  x25 b4000070a92fc610  x26 b4000070a92fb5e0  x27 00000070aa892008
01-26 07:15:10.201 32433 32433 F DEBUG   :     x28 b4000070a922b8f0  x29 0000007fe0631ae0
01-26 07:15:10.201 32433 32433 F DEBUG   :     lr  00000070a9fbf088  sp  0000007fe0631a40  pc  00000070a9fbf0b8  pst 0000000000000000
01-26 07:15:10.201 32433 32433 F DEBUG   : backtrace:
01-26 07:15:10.201 32433 32433 F DEBUG   :       #00 pc 00000000000780b8  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: ca36996e33db72a01a11b53184a66bac)
01-26 07:15:10.201 32433 32433 F DEBUG   :       #01 pc 0000000000367b58  /data/local/tmp/android_aarch64_benchmark_model
01-26 07:15:10.201 32433 32433 F DEBUG   :       #02 pc 00000000003670b4  /data/local/tmp/android_aarch64_benchmark_model
01-26 07:15:10.201 32433 32433 F DEBUG   :       #03 pc 00000000000b1ebc  /data/local/tmp/android_aarch64_benchmark_model
01-26 07:15:10.201 32433 32433 F DEBUG   :       #04 pc 00000000001bb5f8  /data/local/tmp/android_aarch64_benchmark_model
01-26 07:15:10.201 32433 32433 F DEBUG   :       #05 pc 00000000001bc708  /data/local/tmp/android_aarch64_benchmark_model
01-26 07:15:10.201 32433 32433 F DEBUG   :       #06 pc 00000000001bf9f0  /data/local/tmp/android_aarch64_benchmark_model
01-26 07:15:10.201 32433 32433 F DEBUG   :       #07 pc 0000000000048e94  /data/local/tmp/android_aarch64_benchmark_model
01-26 07:15:10.201 32433 32433 F DEBUG   :       #08 pc 0000000000054a94  /data/local/tmp/android_aarch64_benchmark_model
01-26 07:15:10.201 32433 32433 F DEBUG   :       #09 pc 00000000000549e4  /data/local/tmp/android_aarch64_benchmark_model
01-26 07:15:10.201 32433 32433 F DEBUG   :       #10 pc 000000000003fe64  /data/local/tmp/android_aarch64_benchmark_model
01-26 07:15:10.201 32433 32433 F DEBUG   :       #11 pc 0000000000073658  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+108) (BuildId: ca36996e33db72a01a11b53184a66bac)
01-26 07:15:10.833   518   518 D AEE_AED : $===AEE===AEE===AEE===$
01-26 07:15:10.833   518   518 D AEE_AED : p 2 poll events 1 revents 1
01-26 07:15:10.833   518   518 D AEE_AED : PPM cpu cores:8, online:8
01-26 07:15:10.835   518   518 D AEE_AED : aed_main_fork_worker: generator 0xb400007ca82380a0, worker 0x7ff146d040, recv_fd 11
01-26 07:15:10.838 32440 32440 D AEE_AED : u:r:su:s0
01-26 07:15:10.838 32440 32440 V AEE_AED : dashboard_record_update() : rec->module = ./android_aarch64_benchmark_model 
01-26 07:15:10.838 32440 32440 D AEE_AED : Skip duplicated exception ! 
01-26 07:15:10.838 32440 32440 D AEE_AED : Exception Class: 3 
01-26 07:15:10.838 32440 32440 D AEE_AED : Module: ./android_aarch64_benchmark_model 
01-26 07:15:10.838 32440 32440 D AEE_AED : Count: 5 
01-26 07:15:10.838 32440 32440 D AEE_AED : Last exception time: 1264461296 
01-26 07:15:10.838 32440 32440 D AEE_AED :  
01-26 07:15:10.838 32440 32440 V AEE_AED : aed_crash_dump_session - skipped 
01-26 07:15:10.839 32433 32433 I crash_dump: crash_mini_dump_notify exit
01-26 07:15:10.840   518   518 D AEE_AED : clear ppm settings
01-26 07:15:10.841   750  2002 W NativeCrashListener: Couldn't find ProcessRecord for pid 32429
01-26 07:15:10.841   518   518 D AEE_AED : $===AEE===AEE===AEE===$
01-26 07:15:10.842   609   609 E tombstoned: Tombstone written to: /data/tombstones/tombstone_45
01-26 07:15:10.850   750  1329 I BootReceiver: Copying /data/tombstones/tombstone_45 to DropBox (SYSTEM_TOMBSTONE)
01-26 07:15:10.857 32441 32441 I aee_core_forwarder: Core forwarder(0) executable pid 32429 signo 6
01-26 07:15:10.862   750  1329 I DropBoxManagerService: add tag=SYSTEM_TOMBSTONE isTagEnabled=true flags=0x2
01-26 07:15:10.863 32441 32441 E aee_core_forwarder: Acquire(32429) wake lock in core forwarder failed(0)
01-26 07:15:10.863 32441 32441 E aee_core_forwarder: Cannot connect to aed coredump receiver, Connection refused
01-26 07:15:10.866 32441 32441 D aee_core_forwarder: process_coredump: process:32429 is 64 bit preread:1048576
01-26 07:15:10.866 32441 32441 I aee_core_forwarder: Parser thread for aarch64 case
01-26 07:15:10.866 32441 32441 I aee_core_forwarder: Parser result thread id: 32429
01-26 07:15:10.867   518   518 D AEE_AED : $===AEE===AEE===AEE===$
01-26 07:15:10.867   518   518 D AEE_AED : p 2 poll events 1 revents 1
01-26 07:15:10.867   518   518 D AEE_AED : PPM cpu cores:8, online:8
01-26 07:15:10.868   518   518 D AEE_AED : aed_main_fork_worker: generator 0xb400007ca82380a0, worker 0x7ff146d040, recv_fd 11
01-26 07:15:10.870 32442 32442 I AEE_AED : pid: 32429, tid: 32429, >>> ./android_aarch64_benchmark_model <<<
01-26 07:15:10.870  3810 32330 E CrashBox: failed to get version code, 
01-26 07:15:10.870  3810 32330 E CrashBox: android.content.pm.PackageManager$NameNotFoundException: ./android_aarch64_benchmark_model
01-26 07:15:10.870  3810 32330 E CrashBox: 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:238)
01-26 07:15:10.870  3810 32330 E CrashBox: 	at com.oplus.crashbox.e.f.b(SourceFile:91)
01-26 07:15:10.870  3810 32330 E CrashBox: 	at com.oplus.crashbox.collector.a.c.b(SourceFile:75)
01-26 07:15:10.870  3810 32330 E CrashBox: 	at com.oplus.crashbox.collector.a.d.c(SourceFile:79)
01-26 07:15:10.870  3810 32330 E CrashBox: 	at com.oplus.crashbox.collector.b.c(SourceFile:120)
01-26 07:15:10.870  3810 32330 E CrashBox: 	at com.oplus.crashbox.collector.b.a(SourceFile:93)
01-26 07:15:10.870  3810 32330 E CrashBox: 	at com.oplus.crashbox.collector.b.call(SourceFile:42)
01-26 07:15:10.870  3810 32330 E CrashBox: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-26 07:15:10.870  3810 32330 E CrashBox: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-26 07:15:10.870  3810 32330 E CrashBox: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-26 07:15:10.870  3810 32330 E CrashBox: 	at java.lang.Thread.run(Thread.java:923)
01-26 07:15:10.870 32442 32442 D AEE_AED : u:r:su:s0
01-26 07:15:10.870 32442 32442 V AEE_AED : dashboard_record_update() : rec->module = ./android_aarch64_benchmark_model 
01-26 07:15:10.870 32442 32442 D AEE_AED : Skip duplicated exception ! 
01-26 07:15:10.870 32442 32442 D AEE_AED : Exception Class: 3 
01-26 07:15:10.870 32442 32442 D AEE_AED : Module: ./android_aarch64_benchmark_model 
01-26 07:15:10.870 32442 32442 D AEE_AED : Count: 6 
01-26 07:15:10.870 32442 32442 D AEE_AED : Last exception time: 1264461310 
01-26 07:15:10.870 32442 32442 D AEE_AED :  
01-26 07:15:10.870 32442 32442 I AEE_AED : aed_ne_core_session: skip duplicated exception 
01-26 07:15:10.870 32441 32441 I aee_core_forwarder: process_coredump: skip process NE
01-26 07:15:10.870 32441 32441 I aee_core_forwarder: process_coredump: exit
01-26 07:15:10.871   750  2528 E Process : get_ion_cache_memory: Unable to open /d/ion/system_stats
01-26 07:15:10.871   518   518 D AEE_AED : clear ppm settings
01-26 07:15:10.872   518   518 D AEE_AED : $===AEE===AEE===AEE===$
01-26 07:15:10.883   750  1181 V ActivityManager: Broadcast: Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } ordered=false userid=0 resultTo null
01-26 07:15:10.883   750  1181 V ActivityManager: broadcastIntentLocked callingPid: 750 callingUid=1000
01-26 07:15:10.885   750  1329 D DropBoxManagerService: file :: /data/system/dropbox/SYSTEM_TOMBSTONE@1264461310882.txt.gz
01-26 07:15:10.885   750  1330 D ColorAppStartupManager:  callingUid: 1000 topUid: 10243
01-26 07:15:10.885   750  1330 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
01-26 07:15:10.885   750  1329 V java.lang.ASSERT: in copyTombstone
01-26 07:15:10.885   750  1330 D ColorAppStartupManager:  callingUid: 1000 topUid: 10243
01-26 07:15:10.885   750  1330 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
01-26 07:15:10.888   750  2528 D ColorAppStartupManager:  callingUid: 10181 topUid: 10243
01-26 07:15:10.889   750  2528 D ActivityManager: Set 3077 com.google.android.gms.persistent adj 0: service
01-26 07:15:10.894   750  2528 D ActivityManager: Set 3077 com.google.android.gms.persistent adj 100: service
01-26 07:15:10.901   750  2528 D ActivityManager: Set 4531 com.google.android.gms adj 0: service
01-26 07:15:10.900   750  2528 D ColorAppStartupManager:  callingUid: 10181 topUid: 10243
01-26 07:15:10.903   750  2216 D ColorAppStartupManager:  callingUid: 10181 topUid: 10243
01-26 07:15:10.904   750  2216 D ActivityManager: Set 3077 com.google.android.gms.persistent adj 0: service
01-26 07:15:10.905   750  3450 D ActivityManager: Set 4531 com.google.android.gms adj 100: service
01-26 07:15:10.905   750  3450 D ColorAppStartupManager:  callingUid: 10181 topUid: 10243
01-26 07:15:10.906   750  3450 D ActivityManager: Set 4531 com.google.android.gms adj 0: service
01-26 07:15:10.907   750  2216 D ColorAppStartupManager:  callingUid: 10181 topUid: 10243
01-26 07:15:10.909   750  2216 D ActivityManager: Set 4531 com.google.android.gms adj 100: service
01-26 07:15:10.911   750  3450 D ActivityManager: Set 3077 com.google.android.gms.persistent adj 100: service
01-26 07:15:10.913   750  2528 D ActivityManager: Set 3077 com.google.android.gms.persistent adj 0: service
01-26 07:15:10.913   750  3962 D ColorAppStartupManager:  callingUid: 10181 topUid: 10243
01-26 07:15:10.915   750  3962 D ActivityManager: Set 3077 com.google.android.gms.persistent adj 100: service
01-26 07:15:11.461   750  2683 D BatteryLed: getLightInColorState, oppoLightMgr empty!
01-26 07:15:11.462   750   750 V ActivityManager: Broadcast sticky: Intent { act=android.intent.action.BATTERY_CHANGED flg=0x60000010 (has extras) } ordered=false userid=-1 resultTo null
01-26 07:15:11.462   750   750 V ActivityManager: broadcastIntentLocked callingPid: 750 callingUid=1000
01-26 07:15:11.465   750   750 D OppoPowerMonitor_Utils: getBatteryFcc readLine :4000
01-26 07:15:11.465  2325  2325 D DCS-BatteryData: onReceive()--action=android.intent.action.BATTERY_CHANGED
01-26 07:15:11.465   750   750 D OppoPowerMonitor_Utils: getBatteryLevel readLine :80
01-26 07:15:11.465   750   750 V UiModeManager: updateLocked: null action, mDockState=0, category=null
01-26 07:15:11.465   750   750 D UiModeManager: updateConfigurationLocked: mDockState=0; mCarMode=false; mNightMode=1; uiMode=17

**Comment by sunzhe09** [comment]
@jvishnuvardhan   can you help me？I don‘t know why it carshed when  it init the nnapidelegate

**Comment by sunzhe09** [comment]
I converted compat v1 successfully，so I will close it
