### ISSUE TITLE
model.inputs and model.outputs are None when creating a sub-classed model

### ISSUE THREAD

**Issue by noamgot** [tensorflow/tensorflow#45202]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: no
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux 4.19.112+ x86_64 - running in Google Colab
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: N/A
-   **TensorFlow installed from (source or binary)**: binary (pip)
-   **TensorFlow version (use command below)**: v2.3.0-0-gb36436b087 2.3.0
-   **Python version**: 3.6.9
-   **Bazel version (if compiling from source)**: N/A
-   **GCC/Compiler version (if compiling from source)**: N/A
-   **CUDA/cuDNN version**: N/A
-   **GPU model and memory**: N/A

### Describe the problem
I created a model using the [sub-classing method](https://www.tensorflow.org/guide/keras/custom_layers_and_models). As I wanted to examine the model inputs and outputs (using `model.inputs` and `model.outputs`), I found them to be `None`. On the contrary, when I created the same model using the [Sequential API](https://www.tensorflow.org/guide/keras/sequential_model), I do manage to see the inputs and outputs (using the aforementioned `inputs/outputs` attributes). 
I also checked these attributes after predicting with the model, and calling to `model.compile` - nothing works, the outputs are still `None`. 

I'd like to know how (or if?) it's possible to examine a sub-classed model's inputs and outputs this way.

### Source code / logs
You can play with the code in this Colab notebook: 
https://colab.research.google.com/drive/1Oq0oF9aITXNGI9iI3mTsJkmDBoKacDB8?usp=sharing

The model creating code is taken from the official TF 2 quickstart guides (with some minor modifications):
https://www.tensorflow.org/tutorials/quickstart/beginner
https://www.tensorflow.org/tutorials/quickstart/advanced

#### example 1 - Sequential API:
```python
import TensorFlow as tf

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28, 1)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(10)
])

print(model.inputs)
print(model.outputs)
```
The output:
```
[<tf.Tensor 'flatten_5_input:0' shape=(None, 28, 28, 1) dtype=float32>]
[<tf.Tensor 'dense_11/BiasAdd:0' shape=(None, 10) dtype=float32>]
```

#### example 2 - Sub-Classed Model:
```python
from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model

class MyModel(Model):
  def __init__(self):
    super(MyModel, self).__init__()
    self.flatten = Flatten(input_shape=(28, 28, 1))
    self.d1 = Dense(128, activation='relu')
    self.d2 = Dense(10)

  def call(self, x):
    x = self.flatten(x)
    x = self.d1(x)
    return self.d2(x)

# Create an instance of the model
model = MyModel()
print(model.inputs)
print(model.outputs)
```
The output:
```
None
None
```

Note: 
I noticed that when I run this code locally, I get `[]` instead of `None`, but the principle still exists.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3,nightly version(`2.5.0-dev20201126`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/9e9bc1464748f43adb32be1135ce385a/untitled544.ipynb#scrollTo=aq5iXZRYiO4z). Thanks!

**Comment by saikumarchalla** [comment]
Issue still exists in TF-Nightly 2.6 as well. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/df9e145f02310b54f89aadf6112689ef/untitled95.ipynb).

**Comment by falk-stefan** [comment]
The issue seems still to be a thing (2.9.1)?

**Comment by jbischof** [comment]
Sorry this bug hasn't gotten attention earlier but subclassed Models behave differently than functional or sequential ones. They are more like a `keras.Layer` in that their input/output signature is not determined until they are built.

However, if you want explicit inputs and outputs for a subclassed model, there is a workaround! You can declare a functional model in the `__init__` and skip the `call` override:

```python
from tensorflow import keras

class MyModel(keras.Model):
  def __init__(self):
    input = keras.Input(shape=(28, 28, 1), dtype="float32")
    x = keras.layers.Flatten()(input)
    x = keras.layers.Dense(128, activation='relu')(x)
    x = keras.layers.Dense(10)(x)
    super(MyModel, self).__init__(inputs=input, outputs=x)
```

Now the inputs/outputs will be defined:
```python
# Create an instance of the model
model = MyModel()
print(model.inputs)
print(model.outputs)

>>> [<KerasTensor: shape=(None, 28, 28, 1) dtype=float32 (created by layer 'input_6')>]
    [<KerasTensor: shape=(None, 10) dtype=float32 (created by layer 'dense_16')>]
```
