### ISSUE TITLE
Is there a tool for XLA to convert XLA-HLO-IR to a graph (such as dot for graphviz, or html)?

### ISSUE THREAD

**Issue by NEWPLAN** [tensorflow/tensorflow#45201]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): TF-2.3rc2
- Are you willing to contribute it (Yes/No):Yes

**Describe the feature and the current behavior/state.**
I have noticed that in the path (tensorflow/compiler/xla/tools), many tools are available for debugging the system.
Is there a tool for XLA to convert XLA-HLO-IR to a graph (such as dot for graphviz, or html)? 

**What we have:** I have dumped a XLA-HLO, in the format of text;
**What We want:** I want to convert it to a visualized format, such as dot, and html.
It was noted that I have just found that there is an  interactive tool, namely "interactive_graphviz", but it can not convert the data to a dot or html format as we expected.

**Will this change the current api? How?**
No
**Who will benefit with this feature?**
helpful to profile the runtime feature of XLA optimizations
**Any Other info.**

**Comment by sayakpaul** [comment]
@NEWPLAN did you find a way around this?

**Comment by kushanam** [comment]
Not an elegant solution, but I got around this using something like:

```
  HloRenderOptions hlo_render_options;
  hlo_render_options.show_fusion_subcomputations = true;  
   StatusOr<std::string> rendered_graph = RenderGraph(*module->entry_computation(),
            /*label=*/"x.html", module->config().debug_options(), RenderedGraphFormat::kHtml, hlo_render_options);

<THE HTML CODE STRING> = rendered_graph.value()
```
 you would need the "xla/service/hlo_graph_dumper.h" header for this.
