### ISSUE TITLE
disable "Successfully opened dynamic library libcudart.so" logger

### ISSUE THREAD

**Issue by stas00** [tensorflow/tensorflow#45214]
**Describe the current behavior**

Please kindly turn off this logger:
```
$ python -c "import tensorflow"
2020-11-26 12:14:41.249276: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
```

**Describe the expected behavior**

Should not log by default unless requested to. 

If this log line is important in some situation please make it configurable with the default being silent.

Thank you!

Using tf-nightly-gpu-2.5.0.dev20201120

**Comment by sanjoy** [comment]
Thanks, this is a good feature request and we'll keep it in mind for TF 2.5.

Any chance you're willing to make a PR?

**Comment by stas00** [comment]
I don't know/use tf - it just gets loaded in `transformers` whether we want it or not along with pytorch. So please guide me if you'd like me to make a PR.

Using grep it seems to be coming from:

https://github.com/tensorflow/tensorflow/blob/1feb592358c3ab4dfe89ea7848993c8201b860c8/tensorflow/stream_executor/platform/default/dso_loader.cc#L49

But most likely the issue is that by default the log-level shouldn't be INFO, but rather WARNING or higher. But I don't know where you have that defined.

Thanks.

**Comment by janosh** [comment]
I agree with @stas00, the default log level should not be `INFO`.

**Comment by hashaaan** [comment]
I also agree with @stas00, INFO logs should be able to disable

**Comment by krivokuca** [comment]
Yeah, it's really annoying to work with.

**Comment by krivokuca** [comment]
Created PR #48723 to fix this issue

**Comment by rjpower** [comment]
This is fixed after https://github.com/tensorflow/tensorflow/commit/73f56e99958893bbe536e8282688cfc6080d4034.
