### ISSUE TITLE
need a  quantized model for posenet tensorflow lite

### ISSUE THREAD

**Issue by yangcheng** [tensorflow/tensorflow#45218]
System information

TensorFlow version (you are using): 2.3.1
Are you willing to contribute it (Yes/No): Yes
Describe the feature and the current behavior/state.
There is no quantized model for posenet

Will this change the current api? How?
No

Who will benefit with this feature?
People who need to run pose detection on edge IOT NPUs.

Any Other info.
tensorflow js has a quantized model already, https://github.com/tensorflow/tfjs-models/tree/master/posenet , can we get it in tensorflow lite?

**Comment by Saduf2019** [comment]
@yangcheng 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

**Comment by yangcheng** [comment]
Thanks, should I mark it as a feature reqeust?

**Comment by Saduf2019** [comment]
@yangcheng
please explain in details the issue faced and an example code if any.

**Comment by yangcheng** [comment]
@Saduf2019 the request is providing a new quantized model for posenet. there is no example code. What kind of detail should I provide here?

**Comment by gauravzero** [comment]
Was this solved? Did you find a quant posenet model?

**Comment by mohantym** [comment]
Hi @yangcheng !Have you checked INT8 and FP16 quantized models from [MoveNet](https://www.tensorflow.org/lite/examples/pose_estimation/overview#performance_benchmarks) for pose estimation?

**Comment by yangcheng** [comment]
I was using MLKit for now. 
Thanks for the information. I'll take a look at movenet now!

**Comment by mohantym** [comment]
@yangcheng ! Shall we move this feature request to closed status ?
