### ISSUE TITLE
tokenizer = tfds.features.text.Tokenizer(),error is has no attribute 'text'.

### ISSUE THREAD

**Issue by funny000** [tensorflow/tensorflow#45217]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windowns10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):tf.2.3
- Python version:3.7
- Bazel version (if compiling from source):none
- GCC/Compiler version (if compiling from source):none
- CUDA/cuDNN version:none
- GPU model and memory:CPU ,16G

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
AttributeError: module 'tensorflow_datasets.core.features' has no attribute 'text'
**Describe the expected behavior**
run program to use.
**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**the code is that, run it in the google colab, Can you tell me the reason?**

tokenizer = tfds.features.text.Tokenizer()

vocabulary_set = set()
for text_tensor, _ in all_labeled_data:
  some_tokens = tokenizer.tokenize(text_tensor.numpy())
  vocabulary_set.update(some_tokens)

vocab_size = len(vocabulary_set)
vocab_size

**Comment by ravikyram** [comment]
@funny000 

Please, refer the [link](https://github.com/tensorflow/datasets/issues/2647) and see if it helps you.
If the issue still persists please share colab link or simple standalone code with proper indentation to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by hming2048** [comment]
Yes, I met the same issue too!

**Comment by hming2048** [comment]
The method has been deprecated, instead of using tfds.features.text.Tokenizer(), you can try tfds.deprecated.text.Tokenizer()
