### ISSUE TITLE
Tensor data is stored in BE format on s390x in flatbuffer model in a certain scenario

### ISSUE THREAD

**Issue by skribm9** [tensorflow/tensorflow#45211]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.3.1
- Python version: 3.6.9
- Bazel version (if compiling from source): 3.4.1
- GCC/Compiler version (if compiling from source): Ubuntu 7.5.0-3ubuntu1~18.04
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
`tfl_while_op.mlir.test` test is failing on s390x.
On debugging a little, I found that during the building of flatbuffer model, the data is first represented in Big Endian format, then we flat it to a `absl::string_view` in [flatbuffer_export.cc](https://github.com/tensorflow/tensorflow/blob/d5b2156e4e5367cc336d26fbbac3a6e76781de05/tensorflow/compiler/mlir/lite/flatbuffer_export.cc#L638). 
This data , in some cases, is directly stored in a vector of bytes and inserted into a flatbuffer in `CreateVector`. As flatbuffer only support Little Endian format, this TC fails as FileCheck on mlir file expects the data in LE format.

The code that is causing the issue in `CreateVector` function is:
```
      if (sizeof(T) == 1) {
        PushBytes(reinterpret_cast<const uint8_t *>(v), len);
```

If the `sizeof(T)` is greater than 1, then the data is reversed before storing it into a vector of bytes, i.e., the data gets stored in LE format in flatbuffer model. 
```
      } else {
        for (auto i = len; i > 0; ) {
          PushElement(v[--i]);
        }
```

As the flatbuffer only support LE format, it seems that the data must be byte-swapped into LE format from BE before storing is into the vector of bytes. But, since I am not sure of the functionality being tested here, maybe we can update the expected result in mlir file from ```// CHECK-NEXT:     data: [ 1, 0, 0, 0 ]``` to ```// CHECK-NEXT:     data: [ 0, 0, 0, 1 ]```. 
Please suggest what would be the best way to proceed here. There are multiple compiler related test cases which have similar failure errors.

**Describe the expected behavior**
The tensor data must be stored in LE format in flatbuffer model.

**Standalone code to reproduce the issue**
To reproduce the issue, please use this command:
```bazel --host_jvm_args="-Xms1024m" --host_jvm_args="-Xmx2048m" test --host_javabase="@local_jdk//:jdk" --test_tag_filters=-gpu,-benchmark-test,-v1only,-no_oss,-oss_serial -k --test_timeout 300,450,1200,3600 --build_tests_only  -c dbg --copt=-O -c opt --copt=-g --strip never --color=yes --curses=yes --test_output=errors --verbose_failures -- //tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer:tfl_while_op.mlir.test```

**Other info / logs**

**Comment by Saduf2019** [comment]
@skribm9 
Please share a simple stand alone code or if possible share a colab gist with error reported.

**Comment by skribm9** [comment]
Hi @Saduf2019 There is no separate code change done. The issue can be reproduced by compiling Tensorflow 2.3.1 code on s390x.
The function causing the issue is in ```bazel-bin/external/flatbuffers/_virtual_includes/flatbuffers/flatbuffers/flatbuffers.h``` file: 

```
  /// @brief Serialize an array into a FlatBuffer `vector`.
  /// @tparam T The data type of the array elements.
  /// @param[in] v A pointer to the array of type `T` to serialize into the
  /// buffer as a `vector`.
  /// @param[in] len The number of elements to serialize.
  /// @return Returns a typed `Offset` into the serialized data indicating
  /// where the vector is stored.
  template<typename T> Offset<Vector<T>> CreateVector(const T *v, size_t len) {
    // If this assert hits, you're specifying a template argument that is
    // causing the wrong overload to be selected, remove it.
    AssertScalarT<T>();
    StartVector(len, sizeof(T));
    // clang-format off
    #if FLATBUFFERS_LITTLEENDIAN
      PushBytes(reinterpret_cast<const uint8_t *>(v), len * sizeof(T));
    #else
      if (sizeof(T) == 1) {
        PushBytes(reinterpret_cast<const uint8_t *>(v), len);
       } else {
        for (auto i = len; i > 0; ) {
          PushElement(v[--i]);
        }

      }
    #endif
    // clang-format on
    return Offset<Vector<T>>(EndVector(len));
  }
```
 I came across this issue on running bazel test for ```//tensorflow/compiler/mlir/lite/tests/mlir2flatbuffer:tfl_while_op.mlir.test```. On running this test,  I found that this is where issue is introduced:
` if (sizeof(T) == 1) {` condition of `CreateVector` function(mentioned above).

**Comment by skribm9** [comment]
Please find the log file attached for reference. I have deleted additional logs that I added for debugging purpose.
[tfl_while_op.log](https://github.com/tensorflow/tensorflow/files/5608225/tfl_while_op.log)

**Comment by skribm9** [comment]
Issue is a duplicate to #https://github.com/tensorflow/tensorflow/issues/45009. It seems that `buffers` in general are not converted to LE format while storing in flatbuffer vector and this is affecting multiple Test cases.
