### ISSUE TITLE
A hierarchical model for device placement.

### ISSUE THREAD

**Issue by wjykl22** [tensorflow/tensorflow#45225]
Whether the technology mentioned in the paper—A hierarchical model for device placement is open source？and what are the related APIs

**Comment by ravikyram** [comment]
@wjykl22 

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at Stackoverflow. There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by kkkwqy** [comment]
hello, i am interested in this paper  too. do you have any info about the source code of this paper ? thanks for your help
