### ISSUE TITLE
Building tests fails on POWER

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#45228]
Very short: There is an issue in the currently used abseil (as of TF 2.4-rc3 and master) which prevents abseil being built but which is required for running the tests (using `bazel test`)

This is happening on POWER only and fixed in https://github.com/abseil/abseil-cpp/commit/ea8a689cf5e71f31f96af78859eccc11161fa36a, see the error message there.

So I'd like TF to increase the currently used abseil version or add that commit as a patch please.

**Comment by sanatmpa1** [comment]
@Flamefire,

As per the latest stable version of Tensorflow which is `2.6.0`, I see that abseil 0.13.0 is used, which is the recent python implementation of [absl-py](https://pypi.org/project/absl-py/#history). Can you confirm if this resolves your issue? Thanks!

**Comment by Flamefire** [comment]
I can confirm this has been fixed in TF 2.5+
