### ISSUE TITLE
Trying to deploy hello_world on KW41Z (M0) device

### ISSUE THREAD

**Issue by bmorcos** [tensorflow/tensorflow#45233]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): `pip install tensorflow`
- Tensorflow version (commit SHA if source): 2.1.0 (py2.7) 2.3.1 (py3.7)
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): mbed

- gcc-arm-none-eabi v9.3.1
- mbed-cli v1.10.5

**Describe the problem**

Trying to deploy the hello_world example project to the [KW41Z](https://os.mbed.com/platforms/FRDM-KW41Z/) device using mbed and cannot get the project to compile for various reasons.

I have a hunch that mbed is not configured correctly, but I'm unsure how to fix the issues properly. I'll continue working on this but any advice is appreciated!

**Please provide the exact sequence of commands/steps when you ran into the problem**
Under Python 2.7 as recommended, but I also tried under Python 3.7 with similar results.

```
# setup env
conda create -n tflm-2.7 "python=2.7"
conda activate tflm-2.7
pip install tensorflow mbed-cli

# setup project
make -f tensorflow/lite/micro/tools/make/Makefile TARGET_ARCH=cortex-m0plus TARGET=mbed TAGS="CMSIS" generate_hello_world_mbed_project
cd tensorflow/lite/micro/tools/make/gen/mbed_cortex-m0plus/prj/hello_world/mbed
mbed config root .
mbed deploy

# Note all the json files have -std=gnu++14 so I omitted the 98 -> 11 update
mbed compile -m KW41Z -t GCC_ARM -v
```
(partial) output:
```
[Fatal Error] NanostackRfPhyKw41z.cpp@17,10: common_functions.h: No such file or directory 
[DEBUG] Return: 1 
[DEBUG] Output: ./mbed-os/features/nanostack/targets/TARGET_NXP/TARGET_KW41Z/NanostackRfPhyKw41z.cpp:17:10: fatal error: common_functions.h: No such file or directory 
[DEBUG] Output:    17 | #include "common_functions.h" 
[DEBUG] Output:       |          ^~~~~~~~~~~~~~~~~~~~ 
[DEBUG] Output: compilation terminated. 
Traceback (most recent call last): 
  File "/home/ben/git/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m0plus/prj/hello_world/mbed/mbed-os/tools/make.py", line 78, in wrapped_build_project 
    *args, **kwargs 
  File "/home/ben/git/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m0plus/prj/hello_world/mbed/mbed-os/tools/build_api.py", line 607, in build_project 
    objects = toolchain.compile_sources(resources, sorted(resources.get_file_paths(FileType.INC_DIR))) 
  File "/home/ben/git/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m0plus/prj/hello_world/mbed/mbed-os/tools/toolchains/mbed_toolchain.py", line 418, in compile_sources 
    return self._compile_sources(resources, inc_dirs=inc_dirs) 
  File "/home/ben/git/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m0plus/prj/hello_world/mbed/mbed-os/tools/toolchains/mbed_toolchain.py", line 495, in _compile_sources 
    return self.compile_queue(queue, objects) 
  File "/home/ben/git/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m0plus/prj/hello_world/mbed/mbed-os/tools/toolchains/mbed_toolchain.py", line 566, in compile_queue 
    raise ToolException(err) 
ToolException: ./mbed-os/features/nanostack/targets/TARGET_NXP/TARGET_KW41Z/NanostackRfPhyKw41z.cpp:17:10: fatal error: common_functions.h: No such file or directory 
   17 | #include "common_functions.h" 
      |          ^~~~~~~~~~~~~~~~~~~~ 
compilation terminated. 
```
I located this file: `find . -name "common_functions.h"` and tried again:
```
mbed compile -m KW41Z -t GCC_ARM -v \
  --source ./mbed-os/features/frameworks/nanostack-libservice/mbed-client-libservice
```
(partial) output:
```
Could not compile for KW41Z: No Linker Script found 
```
I located the KW41Z linker script: `find . -name "*KW41Z*.ld"`
```
mbed compile -m KW41Z -t GCC_ARM -v \
  --source ./mbed-os/features/frameworks/nanostack-libservice/mbed-client-libservice \
  --source ./mbed-os/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/device/TOOLCHAIN_GCC_ARM 
```
(partial) output:
```
[DEBUG] Errors: /usr/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: BUILD/KW41Z/GCC_ARM/mbed-os/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/device/TOOLCHAIN_GCC_ARM/startup_MKW41Z4.o: in function `Reset_Handler': 
[DEBUG] Errors: /home/ben/git/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m0plus/prj/hello_world/mbed/./mbed-os/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/device/TOOLCHAIN_GCC_ARM/startup_MKW41Z4.S:124: undefined reference to `SystemInit' 
[DEBUG] Errors: /usr/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: /usr/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/lib/thumb/v6-m/nofp/crt0.o: in function `_mainCRTStartup': 
[DEBUG] Errors: (.text+0x56): undefined reference to `__wrap_main' 
[DEBUG] Errors: /usr/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: (.text+0x5a): undefined reference to `__wrap_exit' 
[DEBUG] Errors: collect2: error: ld returned 1 exit status 
Traceback (most recent call last): 
  File "/home/ben/git/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m0plus/prj/hello_world/mbed/mbed-os/tools/make.py", line 78, in wrapped_build_project 
    *args, **kwargs 
  File "/home/ben/git/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m0plus/prj/hello_world/mbed/mbed-os/tools/build_api.py", line 610, in build_project 
    res = toolchain.link_program(resources, build_path, name) 
  File "/home/ben/git/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m0plus/prj/hello_world/mbed/mbed-os/tools/toolchains/mbed_toolchain.py", line 778, in link_program 
    self.link(elf, objects, libraries, lib_dirs, linker_script) 
  File "/home/ben/git/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m0plus/prj/hello_world/mbed/mbed-os/tools/toolchains/gcc.py", line 357, in link 
    self.default_cmd(cmd) 
  File "/home/ben/git/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m0plus/prj/hello_world/mbed/mbed-os/tools/toolchains/mbed_toolchain.py", line 830, in default_cmd 
    raise ToolException(stderr) 
ToolException: /usr/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: BUILD/KW41Z/GCC_ARM/mbed-os/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/device/TOOLCHAIN_GCC_ARM/startup_MKW41Z4.o: in function `Reset_Handler': 
/home/ben/git/tensorflow/tensorflow/lite/micro/tools/make/gen/mbed_cortex-m0plus/prj/hello_world/mbed/./mbed-os/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/device/TOOLCHAIN_GCC_ARM/startup_MKW41Z4.S:124: undefined reference to `SystemInit' 
/usr/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: /usr/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/lib/thumb/v6-m/nofp/crt0.o: in function `_mainCRTStartup': 
(.text+0x56): undefined reference to `__wrap_main' 
/usr/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: (.text+0x5a): undefined reference to `__wrap_exit' 
```

**Comment by bmorcos** [comment]
I finally got this to compile this morning.

I found some related mbed issues/PRs, specifically this one: ARMmbed/mbed-os#13119, which led me to a fix. By default TFMicro downloaded mbed-os at tag `mbed-os-6.0.0-alpha-3` and it looks like the fix from that PR was merged after that tag  (along with some other breaking changes noted below).


**Hacky workaround:**

Moving the `targets` dir into `nanostack-interface` as indicated by the mbed PR allows things to compile now:
```
make -f tensorflow/lite/micro/tools/make/Makefile TARGET_ARCH=cortex-m0plus TARGET=mbed TAGS="CMSIS" generate_hello_world_mbed_project
cd tensorflow/lite/micro/tools/make/gen/mbed_cortex-m0plus/prj/hello_world/mbed
mbed config root .
mbed deploy
# this is the fix
mv mbed-os/features/nanostack/targets mbed-os/features/nanostack/nanostack-interface
mbed compile -m KW41Z -t GCC_ARM
```

**Trying to update mbed-os as a better fix:**
- mbed-os versions `6.2.0`, `6.3.0`, `6.4.0`, and `6.5.0` (latest at the time of writing) have a different serial interface, so there are issues with print statements, which are resolvable but beyond the scope of this issue I think.
- mbed-os version `6.1.0` still has the same issue with `common_functions.h` as noted originally.

So this is working now and the issue and quick fix exist here for posterity, but it might be nice to update the demos to use a newer version of mbed-os :man_shrugging:

**Comment by sushreebarsa** [comment]
@bmorcos It looks like you are using an older Version of Tensorflow . Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.5 and let us know if the issue still persists? Thanks!

**Comment by bmorcos** [comment]
I tried again with the following:
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): pip install tensorflow
- Tensorflow version (commit SHA if source): a4dfb8d1a71 (v2.5.0)
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): mbed
- gcc-arm-none-eabi v10.2.1
- mbed-cli v1.10.5
- Python 3.7.9

I had to make two small adjustments from the original issue to accommodate the new version:
1. Update the `TAGS="cmsis"` argument to `OPTIMIZED_KERNEL_DIR=cmsis_nn`:
```bash
make -f tensorflow/lite/micro/tools/make/Makefile \
  TARGET_ARCH=cortex-m0plus \
  TARGET=mbed \
  OPTIMIZED_KERNEL_DIR=cmsis_nn \
  generate_hello_world_mbed_project
```
2. Add '_default' to the generated project dir name:
```bash
cd tensorflow/lite/micro/tools/make/gen/mbed_cortex-m0plus_default/prj/hello_world/mbed
```

I got identical results to the original issue posted and the same workaround allows the build to succeed.

I still believe this is an issue with the mbed-os version and not necessarily dependant on the TF version. TF 2.5.0 still grabs `mbed-os-6.0.0-alpha-3` when generating the mbed project.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
