### ISSUE TITLE
[TF-1.14] Batch Cholesky Decomposition No Parallelism ? 

### ISSUE THREAD

**Issue by ssydasheng** [tensorflow/tensorflow#45235]
Hi, I am profiling the batch Cholesky decompositions of tensorflow. 

**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04.4 LTS (Bionic Beaver)
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda-10.0; cudnn-10.0-v7.6.3.30
- GPU model and memory: Tesla P100-PCIE-12GB

I noticed that there seems no parallelism speedups for the batch operations. The running code is as in the following. When **B=1**, the printing time is **0.036327**, when **B=10**, the printing time is **0.2908551**. It seems there are basically no parallelisms for the batch operations. Is there a way to fix this issue?

```
import time
import tensorflow as tf

B, N, N = 1, 1024, 1024

a = tf.random_normal(shape=[B, N, N], dtype=tf.float64)
a = tf.matmul(a, a, transpose_b=True) + 1e-8 * tf.eye(N, dtype=a.dtype)
b = tf.linalg.cholesky(a)

sess = tf.Session(config=tf.ConfigProto(intra_op_parallelism_threads=10,
                                 inter_op_parallelism_threads=10))

for _ in range(20):
    sess.run(b)

start = time.time()
for _ in range(21, 30):
    sess.run(b)
print(time.time() - start)
```

**Comment by Saduf2019** [comment]
@ssydasheng 
The tf version used 1.14 is not supported, could you please upgrade to 2.x and let us know of the issue persist.

**Comment by ssydasheng** [comment]
Thanks for your suggestion. I tried using TF-2.3 + CUDA-10.1.  It seems to be faster, 

**B=1, N=1024: 0.02647** vs **B=10, N=1024: 0.117697**;
**B=1, N=128: 0.0054** vs **B=10, N=128: 0.0054**.

For small matrices, the parallelism is awesome. For larger matrices, there are still parallelisms to certain degree. Seems pretty good. Is this in accord to your expectation as well, or you expected more parallelisms for N=1024 ?  

```
import time
import tensorflow as tf

B, N, N = 1, 1024, 1024

@tf.function
def run():
    a = tf.random.normal(shape=[B, N, N], dtype=tf.float64)
    a = tf.matmul(a, a, transpose_b=True) + 1e-8 * tf.eye(N, dtype=a.dtype)
    b = tf.linalg.cholesky(a)
    return tf.reduce_mean(b)

for _ in range(20):
    run()

start = time.time()
for _ in range(21, 30):
    run()
print(time.time() - start)

```
