### ISSUE TITLE
tf.image.extract_patches argument description

### ISSUE THREAD

**Issue by Crispy13** [tensorflow/tensorflow#45239]
https://www.tensorflow.org/api_docs/python/tf/image/extract_patches

There is only one argument description for this function.

Maybe typo? some tags like `<tr>` are in the description.

**Comment by ymodak** [comment]
This is now fixed with TF 2.4.1 api docs. Thanks!
https://www.tensorflow.org/api_docs/python/tf/image/extract_patches#args
