### ISSUE TITLE
Enabling XNNPACK changes the output.

### ISSUE THREAD

**Issue by kafan1986** [tensorflow/tensorflow#45237]
**System information**
- OS Platform and Distribution: Android
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: All android
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v2.3
- Python version: N/A
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
Running a computer vision model for emotion detection. The output is as expected when XNN is disabled but if I enable **tfliteOptions.setUseXNNPACK(true)** then the output is incorrect and totally different.

**Describe the expected behavior**
Output should be same for both XNN enabled and non-XNN option.

I have attached inference class files and model files below.

[ClassFiles.zip](https://github.com/tensorflow/tensorflow/files/5609851/Archive.zip)
[emotion_fp16t.tflite.zip](https://github.com/tensorflow/tensorflow/files/5609852/emotion_fp16t.tflite.zip)

**Comment by Cospel** [comment]
Having the same issue with XNNPACK. If running delegate with XNNPACK the result is totally different from the disabled one.

**Comment by abattery** [comment]
@Maratyszcza could you take a look at this issue?

**Comment by Maratyszcza** [comment]
@kafan1986 Does it reproduce if you build TFLite from the master branch? There was a bug with asymetric padding a while ago that was fixed in google/XNNPACK@facecc526bf35d09ac3319f44072d640101b2b70

**Comment by kafan1986** [comment]
@Maratyszcza I have tested with 0.0.0-nightly build of tflite and the output is same for both version. But the performance seems to be remain same for both with XNN module true and false, whereas earlier the XNN true would significantly run the inference faster although the output was wrong.

**Comment by Maratyszcza** [comment]
AFAIK the master build of TFLite enables XNNPACK by default (@multiverse-tf to confirm), that is why you don't see any difference from explicitly enabling it. I checked that your model does get fully delegated to XNNPACK.

**Comment by kafan1986** [comment]
@Maratyszcza But I was explicitly disabling the XNNPACK by passing false to setXNNPACK.

**Comment by Maratyszcza** [comment]
It is possible that this is not sufficient to disable XNNPACK. You may profile the binary, and if it spends much time in `xnn_*` functions, XNNPACK is being used.

**Comment by kafan1986** [comment]
Works OK with tensorflow lite 2.4.0
