### ISSUE TITLE
WARNING: function Model.make_predict_function.<locals>.predict_function

### ISSUE THREAD

**Issue by innat** [tensorflow/tensorflow#45236]
I'm facing the following warning message in `tf 2.3` in my local machine. This error probably doesn't impact on the model performance (or do). 

> WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000002424DCD6678> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has an experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for more details.

The issue is, I can't reproduce it in **Colab** or **Kaggle** either with the same version of tensorflow `tf 2.3`. What makes it prevent to show this warning message logs on colab or kaggle? I tried to disable the warning on my local machine but didn't work. Below is the reproducible code. In short, I've tried to train a subclassed model and saved a few checkpoints, and ended up with inference iteratively. This is actually a mimic version of my original code. 

```python
import tensorflow as tf 
import numpy as np
from glob import glob
import gc

class Classifier(tf.keras.Model):
    def __init__(self, dim):
        super(Classifier, self).__init__()
        # define all layers in init
        # Layer of Block 1
        self.Base  = tf.keras.layers.Conv2D(32, 3, strides=2, activation="relu")

        self.GAP   = tf.keras.layers.GlobalAveragePooling2D()
        self.OUT   = tf.keras.layers.Dense(10, activation='softmax')
    
    def call(self, input_tensor, training=False):
        x  = self.Base(input_tensor)
        x  = self.GAP(x)
        return self.OUT(x)

# train set / data
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
x_train = np.expand_dims(x_train, axis=-1)
x_train = np.repeat(x_train, 3, axis=-1)
x_train = x_train.astype('float32') / 255
# train set / target 
y_train = tf.keras.utils.to_categorical(y_train, num_classes=10)

# compile 
print('Model Sub-Classing API')
sub_classing_model = Classifier((28,28,3))
sub_classing_model.compile(loss = tf.keras.losses.CategoricalCrossentropy(),
              metrics = tf.keras.metrics.CategoricalAccuracy(),
              optimizer = tf.keras.optimizers.Adam())
# fit 
sub_classing_model.fit(x_train, y_train,
         batch_size=128, epochs=1);

# few checkpoints
sub_classing_model.save_weights('sub1.h5')
sub_classing_model.save_weights('sub2.h5')
sub_classing_model.save_weights('sub3.h5')

for i in sorted(glob('./sub*.h5')):
    sub_classing_model = Classifier((28,28,3))
    sub_classing_model.build((None, *(28,28,3)))
    sub_classing_model.load_weights(i)
    z = sub_classing_model.predict(x_train) # <------ Perhaps something makes it happen 
    del sub_classing_model
    gc.collect()
```

**Comment by Saduf2019** [comment]
@innat 
I ran the code shared and face a different error, please refer to [gist here](https://colab.research.google.com/gist/Saduf2019/8e931005bb045dc727180f1eab514aee/untitled477.ipynb). if possible please a colab gist with the issue reported.

**Comment by innat** [comment]
@Saduf2019 Find it [here](https://colab.research.google.com/gist/Saduf2019/8e931005bb045dc727180f1eab514aee/untitled477.ipynb). 

However, As I told you earlier, it **can't be reproduced** in colab or kaggle, it's happening in the local machine, having the same version of packages. I just want to know, if this is a normal warning message, what makes a clean output log in those virtual environments?

**Comment by Saduf2019** [comment]
@innat 
Could you please check if you are facing the same issue in a virtual environment?

Alternatively, you can also try suppressing the warnings by running the below code before importing TensorFlow.

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 
import tensorflow as tf
Thanks!
