### ISSUE TITLE
[TF 2.3] Hessian of vector field in eager mode

### ISSUE THREAD

**Issue by Abdul-Moeed** [tensorflow/tensorflow#45234]
**System information**
- TensorFlow version: 2.3.0

**Describe the feature and the current behavior/state.**
Calculate hessians in eager mode.

**Will this change the current api? How?**
There should be `tf.batch_hessian()`, or something similar for eager mode; `tf.hessians()` does not work in eager mode.

**Additional info**
I am trying to compute the hessian of an embedding. Currently calling `tf.batch_jacobian()` twice, but this results in a tensor filled with 0s. 

**Code to reproduce issue.**
```python
  with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    y = model(x)
  grads = tape.batch_jacobian(y, x)
  hessian = tape.batch_jacobian(grads, x)
  hessian.numpy().any() > 0

Output: False

```

**Comment by ravikyram** [comment]
@Abdul-Moeed 

Are you interested to submit a PR that supports your feature. If so please submit a PR. Thanks!

**Comment by Abdul-Moeed** [comment]
For now I'm just looking for a workaround. Is there a hacky way to calculate hessian of a vector function in eager mode?

**Comment by Abdul-Moeed** [comment]
Yes, but I couldn't find a workaround for Hessian of a vector field in that thread. Instead, the following works for me:

```python
with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    with tf.GradientTape(persistent=True) as tape2:
        tape2.watch(x)
        y = model(x)
    grads = tape2.batch_jacobian(y, x)
hessian = tape.batch_jacobian(grads, x)
```

**Comment by nikitamaia** [comment]
Got it. Given that other thread is still open I think it makes sense to close this one so we can track progress on Hessians in one place. Your workaround will probably be helpful to other users as well searching for similar functionality.
