### ISSUE TITLE
Validation data generator yields 2 times, but should only 1

### ISSUE THREAD

**Issue by magnus250** [tensorflow/tensorflow#45249]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.3.1
- Python version: 3.8

**Describe the current behavior**
Train process yields validation_data more than I defined in `.fit` function in each epoch. I'm using `.fit` function with two generators for train and validation datasets, which length is the same. I defined learn process for 10 epochs, but after 5 I had warning about there is not more validation_data. You can see more details in colab link below.

**Describe the expected behavior**
Train process should yields `validation_data` only `validation_steps` times. 

**Standalone code to reproduce the issue**
https://colab.research.google.com/drive/1INO5UfPDr_7Jvx6xM4FVBYkGnLG6IFUf?usp=sharing

**Logs**
```
Epoch 1/10
train [0 1 2 3]
1/1 [==============================] - ETA: 0s - loss: 17.7931 - mae: 2.8934
val [4]
1/1 [==============================] - 0s 105ms/step - loss: 17.7931 - mae: 2.8934 - val_loss: 205.8619 - val_mae: 14.3479

Epoch 2/10
train [5 6 7 8]
1/1 [==============================] - ETA: 0s - loss: 1865.1838 - mae: 40.8180
val [9]
val [14]
1/1 [==============================] - 0s 37ms/step - loss: 1865.1838 - mae: 40.8180 - val_loss: 36154.7812 - val_mae: 190.1441

Epoch 3/10
train [10 11 12 13]
1/1 [==============================] - ETA: 0s - loss: 17199.1582 - mae: 128.6884
val [19]
val [24]
1/1 [==============================] - 0s 32ms/step - loss: 17199.1582 - mae: 128.6884 - val_loss: 320162.5000 - val_mae: 565.8290

Epoch 4/10
train [15 16 17 18]
1/1 [==============================] - ETA: 0s - loss: 72351.9141 - mae: 266.5040
val [29]
val [34]
1/1 [==============================] - 0s 40ms/step - loss: 72351.9141 - mae: 266.5040 - val_loss: 1302790.6250 - val_mae: 1141.3986

Epoch 5/10
train [20 21 22 23]
 1/1 [==============================] - ETA: 0s - loss: 208619.7188 - mae: 454.2613
val [39]
val [44]
1/1 [==============================] - 0s 36ms/step - loss: 208619.7188 - mae: 454.2613 - val_loss: 3674302.5000 - val_mae: 1916.8470

Epoch 6/10
train [25 26 27 28]
1/1 [==============================] - ETA: 0s - loss: 482259.9688 - mae: 691.9575
val [49]
WARNING:tensorflow:Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches (in this case, 1 batches). You may need to use the repeat() function when building your dataset.
1/1 [==============================] - 0s 44ms/step - loss: 482259.9688 - mae: 691.9575

Epoch 7/10
train [30 31 32 33]
1/1 [==============================] - 0s 18ms/step - loss: 964487.8750 - mae: 979.5891

Epoch 8/10
train [35 36 37 38]
1/1 [==============================] - 0s 25ms/step - loss: 1741474.2500 - mae: 1317.1534

Epoch 9/10
train [40 41 42 43]
1/1 [==============================] - 0s 16ms/step - loss: 2914341.0000 - mae: 1704.6472

Epoch 10/10
train [45 46 47 48]
1/1 [==============================] - 0s 16ms/step - loss: 4599159.5000 - mae: 2142.0679
```

**Comment by Saduf2019** [comment]
I am able to rpelicate th eissue reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/618dc7a808b6ad44707277454915ab9b/untitled476.ipynb).

**Comment by jvishnuvardhan** [comment]
This is similar to this issue https://github.com/tensorflow/tensorflow/issues/45459 (both uses generator object for training/validation). Thanks!

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue using TF 2.5 . Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/aa0a95c7a0bdfcc772278045d366ddd4/untitled87.ipynb).Thanks!

**Comment by sachinprasadhs** [comment]
Thanks for opening this issue. Development of keras moved to separate repository https://github.com/keras-team/keras/issues

Please post this issue on keras-team/keras repo.
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
