### ISSUE TITLE
Unable to provide constant input tensors to keras functional API for TF2.0+

### ISSUE THREAD

**Issue by fkong7** [tensorflow/tensorflow#45247]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.3.0
- Python version: 3.6
- CUDA/cuDNN version: 10.0

**Describe the current behavior**
Under eager execution, Keras cannot use an existing tensor as a constant input. It returns the following error:

> ValueError: You should not pass an EagerTensor to `Input`. For example, instead of creating an InputLayer, you should instantiate your model and directly call it on your input.

**Describe the expected behavior**
Keras should be able to wrap an optional existing tensor  into the Input layer, using `tf.keras.Input(tensor=existing_tensor)`

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np
const_np = np.random.rand(2,10,3)
const_tf = tf.convert_to_tensor(const_np, dtype=tf.float32)
const_k = tf.keras.Input(tensor=const_tf)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-ba2f0cbae65f> in <module>()
      4 const_np = np.random.rand(2,10,3)
      5 const_tf = tf.convert_to_tensor(const_np, dtype=tf.float32)
----> 6 const_k = tf.keras.Input(tensor=const_tf)

1 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/input_layer.py in Input(shape, batch_size, name, dtype, sparse, tensor, ragged, **kwargs)
    309     input_layer_config.update(
    310         {'batch_size': batch_size, 'input_shape': shape})
--> 311   input_layer = InputLayer(**input_layer_config)
    312 
    313   # Return tensor including `_keras_history`.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/input_layer.py in __init__(self, input_shape, batch_size, dtype, input_tensor, sparse, name, ragged, **kwargs)
    171           raise_eager_tensor_error = True
    172       if raise_eager_tensor_error:
--> 173         raise ValueError('You should not pass an EagerTensor to `Input`. '
    174                          'For example, instead of creating an '
    175                          'InputLayer, you should instantiate your model and '

ValueError: You should not pass an EagerTensor to `Input`. For example, instead of creating an InputLayer, you should instantiate your model and directly call it on your input.
```

**Comment by ravikyram** [comment]
@fkong7 

I have tried in TF nightly version(`2.5.0-dev20201129`) and i am not seeing any issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/adfc8c2a8c763d3ae1a974a2c9ef325d/untitled553.ipynb).Please, veriy once and close the issue.Thanks!
