### ISSUE TITLE
module 'tensorflow._api.v2.data' has no attribute 'dataset'

### ISSUE THREAD

**Issue by sjaddya** [tensorflow/tensorflow#45257]
Code written:
batch_size = 32
dataset = tf.data.dataset.from_tensor_slices(x_train).shuffle(1000)
dataset = dataset.batch(batch_size, drop_remainder=True).prefetch(1)

Error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-fba98a470002> in <module>
      1 batch_size = 32
----> 2 dataset = tf.data.dataset.from_tensor_slices(x_train).shuffle(1000)
      3 dataset = dataset.batch(batch_size, drop_remainder=True).prefetch(1)

AttributeError: module 'tensorflow._api.v2.data' has no attribute 'dataset'

Tensorflow version: 2.3.1

Solved

The code should be:
dataset = tf.data.Dataset.from_tensor_slices(x_train).shuffle(1000)

**Comment by ravikyram** [comment]
@sjaddya 

Please use `tf.data.Dataset.from_tensor_slices`.Please, refer this [tutorial](https://www.tensorflow.org/api_docs/python/tf/data/Dataset). Please, close this thread if your issue was resolved. Thanks!
