### ISSUE TITLE
Eager Gradients C api is C++, along with a few others

### ISSUE THREAD

**Issue by rnett** [tensorflow/tensorflow#45253]
A few files in `tensorflow/c/eager` expose C++ APIs instead of C.  [gradients.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/eager/gradients.h), [tape.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/eager/tape.h), and the `abstract_.h` files (i.e.  [abstract_context.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/eager/abstract_context.h))  do this, and possibly more.  There are no C apis exposed for most of these, either, just the C++.   Has the design changed or is this just an oversight?

cc @karllessard

**Comment by saxenasaurabh** [comment]
These are WIP C++ impls for a new set of APIs for eager execution, tf.function and tf.GradientTape. We will soon be publishing RFCs for these. The C APIs will come soon as well once the implementation is settled.
