### ISSUE TITLE
SeparableConv documention missing argument constraint

### ISSUE THREAD

**Issue by rschumi0** [tensorflow/tensorflow#45259]
The documentation of the SeparableConv layers does not mention that the strides must be equal length.

Trying to use different lengths produces an InvalidArgumentError: Current implementation only supports equal length strides in the row and column dimensions.

**Comment by ravikyram** [comment]
@rschumi0 

Can you please refer the documentation link you are referring to. Thanks!

**Comment by rschumi0** [comment]
It concerns both these layers:
[https://www.tensorflow.org/api_docs/python/tf/keras/layers/SeparableConv1D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/SeparableConv1D)
[https://www.tensorflow.org/api_docs/python/tf/keras/layers/SeparableConv2D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/SeparableConv2D)

**Comment by jvishnuvardhan** [comment]
@rschumi0 A PR raised to correct this documentation. Will closed the issue when the PR gets merged. thanks!

**Comment by jvishnuvardhan** [comment]
@rschumi0 I am closing this issue as the related PR https://github.com/tensorflow/tensorflow/pull/48250 got merged. Thanks!
