### ISSUE TITLE
Python Exceptions lead to CUDA Memory Leak

### ISSUE THREAD

**Issue by kuza55** [tensorflow/tensorflow#4525]
I've been using hyperopt in it's MondoTrials configuration to do a grid search of my hyperparameters and the process has been slow going since every time my python program crashes for whatever reason, my CUDA memory is not freed

Here is the output i see from nvidia-smi:

```
$ nvidia-smi
Wed Sep 21 20:09:42 2016       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.44                 Driver Version: 367.44                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 0000:03:00.0      On |                  N/A |
| 22%   32C    P8    15W / 250W |  11848MiB / 12198MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      3475    G   /usr/lib/xorg/Xorg                             207MiB |
|    0      4579    G   compiz                                          52MiB |
|    0      5258    G   /opt/google/chrom                               86MiB |
|    0      6144    G   ...s-passed-by-fd --v8-snapshot-passed-by-fd    37MiB |
+-----------------------------------------------------------------------------+
```

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

Lots of people asking questions, no-one with answers.

### Environment info
Operating System: Ubuntu 16.04

Installed version of CUDA and cuDNN: CUDA 7.5 cuDNN 5.1

If installed from binary pip package, provide:

1. https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0-cp27-none-linux_x86_64.whl
2. 0.10.0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
I don't have a minimal sample yet.

### What other attempted solutions have you tried?
Rebooting works, but is painful

### Logs or other output that would be helpful
Please let me know what logs would be useful.

**Comment by kuza55** [comment]
FWIW, hyperopt does some terrible things where it serializes a function that you define for running a trial, stores that (dill) pickle in mongodb and then deserializes that pickle from a module and runs it there.

I feel like there's a high likelihood that setup is what is causing issues.

**Comment by jmchen-g** [comment]
We don't really directly support those third party tools so please post this on stackoverflow. Thanks.
