### ISSUE TITLE
build from master branch with --config=v1 can not output tensorflow 1.x version

### ISSUE THREAD

**Issue by kaierlong** [tensorflow/tensorflow#45250]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version: master ( git clone from source)
- Python version: 3.8.5
- Installed using virtualenv? pip? conda?: pip3
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: 11.1, 8.0.5
- GPU model and memory: RTX 3090

**Describe the problem**
I tried to build tensorflow 1.x from source code with param`--config=v1`. But the output is always `tensorflow-2.5.0-xxx`.
So I wonder how to build tensorflow 1.x version from master branch of the source code? Is the `--cofing=v1` param not supposed to build tensorflow 1.x version? 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
`bazel build --config=v1 --config=cuda //tensorflow/tools/pip_package:build_pip_package`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by byronyi** [comment]
You need to use the v1 branch, e.g. `git checkout r1.15`.

**Comment by kaierlong** [comment]
> You need to use the v1 branch, e.g. `git checkout r1.15`.

But the officail documents say `on master branch`. That means there has error on the officail documents?

**Comment by ymodak** [comment]
See related [issue ](https://github.com/tensorflow/tensorflow/issues/40272#issuecomment-644270769)

**Comment by kaierlong** [comment]
> issue

Thanks! By the way, the official documents is a little vague and should be updated.
