### ISSUE TITLE
model.save fails to create directories on Windows

### ISSUE THREAD

**Issue by gqqnbig** [tensorflow/tensorflow#45254]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 2004
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7
- CUDA/cuDNN version: cudart64_101.dll
- GPU model and memory: GeForce GTX 1070

**Steps to reproduce**
First make sure the current directory doesn't have `saved_model` folder.

![dopus_fJLqMA2WiE](https://user-images.githubusercontent.com/614159/100533710-53cb6100-3242-11eb-992a-b78539462db1.png)

Then run the following code

```
import os

import tensorflow as tf
from tensorflow import keras

print(tf.version.VERSION)


(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.mnist.load_data()

train_labels = train_labels[:1000]
test_labels = test_labels[:1000]

train_images = train_images[:1000].reshape(-1, 28 * 28) / 255.0
test_images = test_images[:1000].reshape(-1, 28 * 28) / 255.0

def create_model():
	model = tf.keras.models.Sequential([
		keras.layers.Dense(512, activation='relu', input_shape=(train_images.shape[1],)),
		keras.layers.Dropout(0.2),
		keras.layers.Dense(10)
	])

	model.compile(optimizer='adam',
				  loss=tf.losses.SparseCategoricalCrossentropy(from_logits=True),
				  metrics=['accuracy'])

	return model


model = create_model()

model.summary()

# Create and train a new model instance.
model = create_model()
model.fit(train_images, train_labels, epochs=5)

# Save the entire model as a SavedModel.
model.save('saved_model/my_model')
```

**Describe the current behavior**

model.save throws exception:
> Traceback (most recent call last):
>   File "D:/renaming/neural network/tensorflow/6.save_and_load.py", line 124, in <module>
>     model.save('saved_model/my_model')
>   File "C:\ProgramData\Miniconda3\envs\tf\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1008, in save
>     signatures, options)
>   File "C:\ProgramData\Miniconda3\envs\tf\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 115, in save_model
>     signatures, options)
>   File "C:\ProgramData\Miniconda3\envs\tf\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\save.py", line 78, in save
>     save_lib.save(model, filepath, signatures, options)
>   File "C:\ProgramData\Miniconda3\envs\tf\lib\site-packages\tensorflow_core\python\saved_model\save.py", line 915, in save
>     utils_impl.get_or_create_variables_dir(export_dir)
>   File "C:\ProgramData\Miniconda3\envs\tf\lib\site-packages\tensorflow_core\python\saved_model\utils_impl.py", line 214, in get_or_create_variables_dir
>     file_io.recursive_create_dir(variables_dir)
>   File "C:\ProgramData\Miniconda3\envs\tf\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 440, in recursive_create_dir
>     recursive_create_dir_v2(dirname)
>   File "C:\ProgramData\Miniconda3\envs\tf\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 455, in recursive_create_dir_v2
>     pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path))
> tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: saved_model/my_model\variables; No such file or directory

Folder saved_model is created, but it contains nothing.

![dopus_K6JLvfsHQ7](https://user-images.githubusercontent.com/614159/100533801-54b0c280-3243-11eb-8600-0dc81f526fc6.png)

**Describe the expected behavior**

If model.save requires the presence of the path, the method should fail in  the first place, without creating the `saved_model` folder

If the method is able to create folders, why doesn't it create `my_model` subfolder as well?

**Comment by DavidKatz-il** [comment]
Change `model.save('saved_model/my_model')` to `model.save('saved_model\\my_model')`
And it should work.

**Comment by ravikyram** [comment]
@gqqnbig 

Please, create a folder `saved_model` before saving the model so `my_model` will be saved in that directory. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/dd43d94373a9ff4ba712729d4b85a5be/untitled548.ipynb).Please, verify once and close the issue. Thanks!
