### ISSUE TITLE
tf.saved_model.save does not work using uint8 Input-Layer

### ISSUE THREAD

**Issue by Hhessling** [tensorflow/tensorflow#45269]
System information:
- Testted on colab.research.google.com
- Tensorflow 2.3.1

The following minimal Model cannot be saved using `tf.saved_model.save`:
```
import tensorflow as tf
from tensorflow.keras import backend as K
from tensorflow.keras import layers
from tensorflow.keras.layers.experimental.preprocessing import Rescaling
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import Sequence
filters = (40, 60, 80)
p = dict(padding="same",
          activation="selu",
          kernel_size=(3, 3),
          kernel_initializer="lecun_normal",
          bias_initializer="zeros")
ALPHABET = "asdf4711"
i = layers.Input((None, None, 3), name='input', dtype='uint8')
x = layers.Permute((2, 1, 3))(i)
x = Rescaling(1. / 255.)(x)
x = layers.LayerNormalization(axis=1, center=False, scale=False)(x)
x = layers.Conv2D(filters[0], **p)(x)
x = layers.Conv2D(filters[0], **p)(x)
x = layers.Conv2D(filters[1], strides=(2, 3), **p)(x)
x = layers.Conv2D(filters[1], **p)(x)
x = layers.Conv2D(filters[1], **p)(x)
x = layers.Conv2D(filters[2], strides=(2, 3), **p)(x)
x = layers.Conv2D(filters[2], **p)(x)
x = layers.Conv2D(filters[2], **p)(x)

x = layers.Lambda(lambda t: tf.math.reduce_max(t, axis=2))(x)
x = layers.Bidirectional(layers.GRU(x.shape[-1], return_sequences=True), 'sum')(x)
x = layers.Bidirectional(layers.GRU(x.shape[-1], return_sequences=True), 'sum')(x)
x = layers.Conv1D(len(ALPHABET) + 1, 1, activation="softmax")(x)
m = Model(inputs=i, outputs=x)
```
Instead of saving the model, i get the following error:
`
ValueError: Python inputs incompatible with input_signature: inputs ((<tf.Tensor 'input:0' shape=(None, None, None, 3) dtype=uint8>,)), input_signature ((TensorSpec(shape=(None, None, None, None), dtype=tf.float32, name=None),))`

When I change the type of the input layer to `'float32'`,  the export works fine. However, when deployed in tensorflow-serving and calling it via grpc, using uint8 instead of float32 significantly reduces network io in this use case.

**Comment by Hhessling** [comment]
The following change has fixed the issue:
```
 i = layers.Input((None, None, 3), name='input', dtype='uint8')
 x = layers.Lambda(K.cast_to_floatx)(i)
```
My expectation is that `Rescaling ` does the type-conversion.

**Comment by amahendrakar** [comment]
> The following change has fixed the issue:

@Hhessling,
Is this still an issue? Please feel free to close the issue if resolved. Thanks!

**Comment by Hhessling** [comment]
I think this should be fixed in `tensorflow.keras.layers.experimental.preprocessing.Rescaling`. However, since this Layer is considered as experimental, I close this issue.
