### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tensorflow==1.2.1 ? pip cannot find tensroflow 1 versions

### ISSUE THREAD

**Issue by LusKrew** [tensorflow/tensorflow#45267]
I cannot install any tensorflow 1 version in my virtual env.. it is required by a project that I'm trying to run..

    pip install tensorflow==1.2.1
    ERROR: Could not find a version that satisfies the requirement tensorflow==1.2.1 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3)
    ERROR: No matching distribution found for tensorflow==1.2.1

Tried things suggested here :

https://stackoverflow.com/questions/42317075/tensorflow-r1-0-could-not-a-find-a-version-that-satisfies-the-requirement-tens

my python version is not old : 3.8.5

my pip version is OK : 20.0.2

i still CANNOT install tensorflow 1.2.1 ...

what i gotta do.. I am using ubuntu 20

**Comment by fridex** [comment]
There is no build for python 3.8 https://pypi.org/project/tensorflow/1.2.1/#files

**Comment by ravikyram** [comment]
@fridex 

Tensorflow 1.2 is very old. Please, upgrade to T 2.3 and make sure you have all the requiremnts as per the tested build configurations from [here](https://www.tensorflow.org/install/source#cpu).Thanks!

**Comment by fridex** [comment]
@LusKrew ^^

**Comment by mihaimaruseac** [comment]
If you want old versions, you should use the same version of Python that was in use at the time. PyPi page for the package lists which python versions are available.

Closing since this is not an issue with TF code and it refers to TF versions that are long out of the support window.
