### ISSUE TITLE
What is the difference between Keras Attention and “Scaled dot product attention” as in the TF Transformer tutorial

### ISSUE THREAD

**Issue by thephet** [tensorflow/tensorflow#45268]
I am going through the TF Transformer tutorial: https://www.tensorflow.org/tutorials/text/transformer#scaled_dot_product_attention

And I was comparing the output from their defined Attention to the one from Keras (https://www.tensorflow.org/api_docs/python/tf/keras/layers/Attention there you can also see the code).

Testing on basic examples, they produce slightly different results.

For example, given the following input x:

```
In [311]: x
Out[311]: 
<tf.Tensor: shape=(1, 2, 4), dtype=float32, numpy=
array([[[0.3020829 , 0.38190305, 0.48654556, 0.6720122 ],
        [0.04044473, 0.04240108, 0.19330955, 0.01818049]]], dtype=float32)>
```

Which was generated as

`x = tf.random.uniform((1, 2, 4))`

if I run this through the tutorial attention function, I get:

```
In [312]: scaled_dot_product_attention(x, x, x, None)
Out[312]: 
(<tf.Tensor: shape=(1, 2, 4), dtype=float32, numpy=
 array([[[0.19679338, 0.24527925, 0.36854032, 0.40889454],
         [0.17432278, 0.21612138, 0.34335595, 0.35274068]]], dtype=float32)>
```

But if I use keras attention function, everything default, I get:

```
In [309]: model.predict([x,x,x])
Out[309]: 
array([[[0.22044972, 0.27597573, 0.39505363, 0.46801156],
        [0.17737839, 0.22008634, 0.34678057, 0.3603766 ]]], dtype=float32)
```

where model is just

`model = tf.keras.models.Model(inputs=[query, value, key], outputs=tf.keras.layers.Attention()([value,value,value]))`

As you can see, the values are very similar, but not exactly the same.

I wonder where this difference is coming from. Checking through the keras github I don't see them doing a scaling factor, such as in the tutorial:

```
  # scale matmul_qk
  dk = tf.cast(tf.shape(k)[-1], tf.float32)
  scaled_attention_logits = matmul_qk / tf.math.sqrt(dk)
```

but if I define "use_scale" in keras attention, it doesnt make a difference:

```
In [313]: model = tf.keras.models.Model(inputs=[query, value, key], outputs=tf.keras.layers.Attention(use_scale=True)([value,value,value]))
In [315]: model.predict([x,x,x])
Out[315]: 
array([[[0.22044972, 0.27597573, 0.39505363, 0.46801156],
        [0.17737839, 0.22008634, 0.34678057, 0.3603766 ]]], dtype=float32)
```

I would really appreciate if someone could tell me what's the difference between keras attention and the attention from the tutorial. Thanks

**Comment by saberkun** [comment]
I would recommend checking out the new MultiHeadAttention layer which should match the transformer paper.
The Attention layer in keras has a learnable scale variable while the transformer paper uses 1/sqrt(query_dim).

**Comment by jvishnuvardhan** [comment]
@thephet Is this resolved for you? 

Please close the issue if this was resolved for you. thanks!
