### ISSUE TITLE
torch.nn.functional.grid_smaple tensorflow2.0 how to recurrence?

### ISSUE THREAD

**Issue by kgju** [tensorflow/tensorflow#45270]
torch.nn.functional.grid_smaple tensorflow2.0 how to recurrence?

**Comment by ravikyram** [comment]
@kgju 

Can you please refer this [SO link](https://stackoverflow.com/questions/52888146/what-is-the-equivalent-of-torch-nn-functional-grid-sample-in-tensorflow-numpy/52896615#52896615) and see if it helps you. Thanks!
