### ISSUE TITLE
load_model in tf>=2.3.0 raises TypeError when loading a model saved in tf 2.2.0

### ISSUE THREAD

**Issue by shengpu1126** [tensorflow/tensorflow#45288]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Google Colab
- TensorFlow version: 2.2.0 vs 2.3.1 or tf-nightly (2.5.0.dev20201130)
- Python version: 3.6.9
- GPU model and memory: None (Colab CPU)

**Describe the current behavior**
When I saved a model using `tf.keras.models.Model(...).save` in tf 2.2.0, I am unable to load the model back using `tf.keras.models.load_model` in tf 2.3.1 or the latest tf-nightly. See abbreviated error message below:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-8326baccad65> in <module>()
      1 # Restart the runtime, then run
      2 import tensorflow as tf
----> 3 model = tf.keras.models.load_model('hidden_net')

9 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py in reconstruct_from_config(config, custom_objects, created_layers)
   1234     layer = created_layers[layer_name]
   1235     node_index = get_node_index(layer, node_index)
-> 1236     layer_output_tensors = layer._inbound_nodes[node_index].output_tensors
   1237     output_tensors.append(nest.flatten(layer_output_tensors)[tensor_index])
   1238 

TypeError: list indices must be integers or slices, not NoneType
```

**Describe the expected behavior**
Should be able to load the model back

**Standalone code to reproduce the issue**
See [gist](https://colab.research.google.com/gist/shengpu1126/5d4674a9475590ef2fe46565f0641b12/untitled2.ipynb)

**Other info / logs**
- Maybe related to #42890. I could not find a newer issue related to this so I created a new one; please close it if it's a duplicate. 
- This may have to do with the way I defined my model, where I used a combination of Keras sequential and functional API. Could it be related to the recent Keras functional refactoring in 2.4.0?

**Comment by Saduf2019** [comment]
@shengpu1126 
I ran the gist and see a different response, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/919d03ee55b3f8cd2ad3e66dfbb40b79/untitled476.ipynb).

**Comment by shengpu1126** [comment]
@Saduf2019 You would need to restart the runtime after installing the 2.3.1 version and reimport it. I've updated the [gist](https://colab.research.google.com/gist/shengpu1126/5d4674a9475590ef2fe46565f0641b12/untitled2.ipynb) to print out the version number after reimporting, could you please try again?

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/c4d7b6ef2ccb6b2416bc8580e017ed7f/untitled483.ipynb).

**Comment by jvishnuvardhan** [comment]
@shengpu1126 There are some changes ("keras_metadata.pb" as mentioned in the warning) in model saving and loading before and after `TF2.4`. The following warning throws the following warning.

```
2.5.0-dev20201217
WARNING:tensorflow:SavedModel saved prior to TF 2.4 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-2b2d876fd0e5> in <module>()
      5 print(tf.__version__)
      6 
----> 7 loaded_model = tf.keras.models.load_model('hidden_net')

5 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py in reconstruct_from_config(config, custom_objects, created_layers)
   1308     layer = created_layers[layer_name]
   1309     node_index = get_node_index(layer, node_index)
-> 1310     layer_output_tensors = layer._inbound_nodes[node_index].output_tensors
   1311     output_tensors.append(nest.flatten(layer_output_tensors)[tensor_index])
   1312 

TypeError: list indices must be integers or slices, not NoneType
```

However, Looks like this is a bug or atleast need to update the following warning. Even when the model was created and saved in `TF2.4`, and later loaded in `tf-nightly`, it throws the warning as follows. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/fcb9ff5279139417b0a5174a640700dd/untitled483.ipynb). we will look into it.

```
2.5.0-dev20201217
WARNING:tensorflow:SavedModel saved prior to TF 2.4 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
```

**Comment by jvishnuvardhan** [comment]
I am closing this issue as the original issue is resolved. I will open another issue to track the progress on removing the warning when the model (tf format only) saved using `TF2.4` but later reloaded using `tf-nightly` throws a warning as mentioned in my earlier response. 

I noticed that there is no warning if the model was saved in `h5` format. Thanks!

**Comment by shengpu1126** [comment]
Hello, 

Thanks for creating the other issue for the incorrect warning message. 

Unfortunately I don't believe the original issue has been resolved. I have created a new [gist](https://colab.research.google.com/gist/shengpu1126/eec804b543ae8bd69bbab7bd3699cd61/untitled2.ipynb) that demonstrates the issue with the latest nightly version. 

> **IMPORTANT NOTE**: the code first saves a model in TF 2.2.0, and then you need to **restart the runtime** and reimport TF-nightly to load the saved model. 

This is crucial because I have models saved in TF 2.2.0 and I have updated my TF to the latest version, now I can no longer load those models.

**Comment by jvishnuvardhan** [comment]
@shengpu1126 Looks like there is some issue with your model. I tried running another [simple model](https://colab.research.google.com/gist/jvishnuvardhan/c79db173a23d9a941ed203d8b8f836f0/untitled74.ipynb), saved using `tf-nightly`, restarted runtime, and loaded it without any issue. But, when i tried your model, it throws an error as shown by you.

I will reopen the issue for deeper look. Thanks!

**Comment by jvishnuvardhan** [comment]
@shengpu1126 I updated one line in your code as follows (added `input_shape` to first layer of `Sequential`)

`tf.keras.layers.Dense(1000, activation="relu", input_shape=(d,)),`

After the above update, I cannot reproduce the error. [Here](https://colab.research.google.com/gist/jvishnuvardhan/ad305a6648a729e50cea08006e7d0a1d/untitled2.ipynb) is a gist for your reference. 

Can you please verify once and close the issue if this was resolved for you. Thanks!

**Comment by shengpu1126** [comment]
Yes that solved it. Thank you!
