### ISSUE TITLE
resnet50 inference is slower when use tensorflow with onednn

### ISSUE THREAD

**Issue by zhangqiang-hf** [tensorflow/tensorflow#45289]
> @zhangqiang-hf
> 
> I think your issue is new one for Resnet50 model.
> This issue topic is LSTM.
> 
> Is it possible to create a new github issue for your model?
> You could @me in the new issue, so I can continue following it.
> 
> Thank you!

ok！I will assign a new bug for you！when one pic, why it is slower when use onednn, this  still a issue? am I right?
also, I have checked when bs=100, it is quicker when onednn. but this 100 pictures is the same, when the100 pictures are different, how about?

_Originally posted by @zhangqiang-hf in https://github.com/tensorflow/tensorflow/issues/33138#issuecomment-736168560_

**Comment by NeoZhangJianyu** [comment]
@zhangqiang-hf 
1. Could you copy the detailed info about your case from the #33138 ?
So, the reader could know whole problem and answer of your case.

2. Answer about your question
a. BS=1 case, we are checking. I will feedback later.
b. Performance is better with more big BS.
I use Intel Xeon CPU, there is AVX512 to accelerate the Tensorflow by vector.
If you are using Intel Core CPU, AVX2/AVX512 in it will speed up the Tensorflow in same way.

AVX512 support 512 bits vector to execute the operation, like add, mul, addmul.
one 512 bits vector could load 16 FP32 float numbers in one time. 

V512 + V512 = (FP32+FP32), (FP32+FP32),..., (FP32+FP32)  (total 16 groups).

So, it's more quick than FP32 operation when add more float number.

But, there is additional cost: load the data to vector.
If the vector load 16 FP32 floats, the performance benefit is max.
If the vector only load 1 FP32 floats, the performance is bad: load to vector waste time. 

So, when BS is big, the vector could be full and get better performance.

c. For your case: Tensorflow with MKL get same performance when BS=100.
Do you use Intel Core CPU?
If yes, could refer to the optimization setting, like:

```
export TF_ENABLE_MKL_NATIVE_FORMAT=1  
export TF_NUM_INTEROP_THREADS=1
export TF_NUM_INTRAOP_THREADS=24
export OMP_NUM_THREADS=24
export KMP_BLOCKTIME=1
export KMP_AFFINITY=granularity=fine,compact,1,0
```

`TF_ENABLE_MKL_NATIVE_FORMAT` is key optimization, friendly to Keras model inference.
`TF_NUM_INTRAOP_THREADS` & `OMP_NUM_THREADS` are set as the number of cores in the CPU. You could change it for better performance.
`KMP_BLOCKTIME` are set 0, 1 or other number.  Depend on test result.

**Comment by NeoZhangJianyu** [comment]
@zhangqiang-hf @Zantares
As answer from Zantares: "Bad performance is expected if you only run session once because TF with oneDNN will take more time in warmup (1st iteration). You will get similar performance with different pics as long as you don't change pic shape. In same word, TF with oneDNN doesn't care about data, it only cares shape."

I just test to run 100 times for BS=1.
The performance of TF with MKL is better than stack TF.
```
    times = 100
    a = time.time()    
    for i in range(times):    
        preds = model.predict(x)
    b = time.time()
    seconds = (b - a)/times
    print("predict() cost time:",seconds)
```

**Comment by zhangqiang-hf** [comment]
Dear sir，
the format of resnet50 is keras HD5。ok， I will share my test code for this issue。
Tensorflow-2.4.0
oneDNN-1.5.0
CPU：mips64
OS：loongnix（fedora21）
python：3.7.9
the test code is as bellow：
[
[resnet50.zip](https://github.com/tensorflow/tensorflow/files/5621083/resnet50.zip)

](url)

the attach file include: 
1)resnet50-onepic.py(only one pic inference)
2) resnet50-100.py(100 pictures for inference,the dataset download from: http://www.robots.ox.ac.uk/~vgg/data/pets/        ),you can download the Dataset from this website.

Tensorflow build command：
use mkl
bazel build --verbose_failures --config=noaws --config=mkl --config=opt --host_copt=-march=loongson3a --action_env=BAZEL_LINKLIBS=-l%:libstdc++.a --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package

not use mkl：
bazel build --verbose_failures --config=noaws --config=opt --host_copt=-march=loongson3a --action_env=BAZEL_LINKLIBS=-l%:libstdc++.a --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package

**then I test ：python-3.7.9 resnet50-onepic.py  or resnet-100.py**
the result is:
resnet50 inference：tensorflow-2.4.0 that use mkl is slower than tensorflow-2.4.0 which not use mkl！

**than, I do the same test on x86 platform(delete  --host_copt=-march=loongson3a when build on x86), it is the same result. it is still slower when use mkl on x86 platform**

**Comment by amahendrakar** [comment]
@zhangqiang-hf,
Could you please go through [this similar issue](https://github.com/tensorflow/tensorflow/issues/33146) and let us know if it helps. Thanks!

**Comment by NeoZhangJianyu** [comment]
@zhangqiang-hf 

In your code, the function predict_result() including the code to load the dataset.
So, when you load more images, the time used by predict_result() will be more.
That's why the time is more when you load 100 different images.

To estimate the performance of TF inference, it's better to record the pure inference time.
Other codes should be excluded as possible.

**Comment by zhangqiang-hf** [comment]
> @zhangqiang-hf
> 
> In your code, the function predict_result() including the code to load the dataset.
> So, when you load more images, the time used by predict_result() will be more.
> That's why the time is more when you load 100 different images.
> 
> To estimate the performance of TF inference, it's better to record the pure inference time.
> Other codes should be excluded as possible.
> 
> I check your case, after I change the estimate code (I only record the inference time).

Dear sir，
  I test the same py file in two mode（tensorflow with onednn or no onednn），so it is the same test situation

**Comment by NeoZhangJianyu** [comment]
@zhangqiang-hf 
If you wan to to speed up loading the dataset, it maybe another topic.
Not in the scope of Tensorflow with MKL.

**Comment by zhangqiang-hf** [comment]
> @zhangqiang-hf
> If you wan to to speed up loading the dataset, it maybe another topic.
> Not in the scope of Tensorflow with MKL.
from now on， I find it is stll slower to test one pic 100 times when use onednn
OK， I will modify the test time only do the predict。
but， when one pic  why it is slower then not use mkl？

**Comment by zhangqiang-hf** [comment]
> @zhangqiang-hf
> If you wan to to speed up loading the dataset, it maybe another topic.
> Not in the scope of Tensorflow with MKL.

**Comment by zhangqiang-hf** [comment]
> @zhangqiang-hf
> If you wan to to speed up loading the dataset, it maybe another topic.
> Not in the scope of Tensorflow with MKL.

from now on， I find it is stll slower to test one pic 100 times when use onednn
OK， I will modify the test time only do the predict。
but， when one pic why it is slower then not use mkl？

**Comment by zhangqiang-hf** [comment]
> @zhangqiang-hf
> If you wan to to speed up loading the dataset, it maybe another topic.
> Not in the scope of Tensorflow with MKL.

Dear sir,
   I have modified my test py file. just as your opinion，only compute the cost time of predict, loading the data not included now.
**first， I use Intel Core CPU（i7-4790 cpu @ 3.6GHz，has 8 cores）**
the optimization setting, like:
export TF_ENABLE_MKL_NATIVE_FORMAT=1  
export TF_NUM_INTEROP_THREADS=1
export TF_NUM_INTRAOP_THREADS=8
export OMP_NUM_THREADS=8
export KMP_BLOCKTIME=1
export KMP_AFFINITY=granularity=fine,compact,1,0

**Then , I do the test as bellow:**
case1：bs=100: one pic reproduce 100 times and call predict once, 
case2：one pic do 100 predict
case3：100 different pics，one pic do once predict，so do 100 predicts in all
**Now，case1/2/3， resnet50 inference the result is the same：**
1）use tensorflow with onednn，do the optimize setting above is quicker than not do the optimize setting
2）but，use tensorflow with onednn do the optimize setting above is still slower than tensorflow not use onednn ！ 
3）the tensorflow not use onednn， resnet50 inference is the quickest in the  case1/2/3

**Comment by NeoZhangJianyu** [comment]
@zhangqiang-hf 
1.
I checked this i7-4790 , it includes 4 cores, 8 threads.
Please set with 4 in above setting.

2.
Could you share the build cmd for the TF with MKL on i7?
or the cmd to install it.

**Comment by zhangqiang-hf** [comment]
> @zhangqiang-hf
> 1.
> I checked this i7-4790 , it includes 4 cores, 8 threads.
> Please set with 4 in above setting.
> 
> 
> Could you share the build cmd for the TF with MKL on i7?
> or the cmd to install it.

cat /proc/cpuinfo， it displays 8 processor，but cpu cores =4， ok， I will set 
export TF_NUM_INTRAOP_THREADS=4
export OMP_NUM_THREADS=4


**2. build cmd（with onednn）：**
bazel build --verbose_failures --config=noaws --config=mkl --config=opt  --action_env=BAZEL_LINKLIBS=-l%:libstdc++.a --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package

**if no use onednn， omitted “--config=mkl”。**

**then generate whl：**bazel-bin/tensorflow/tools/pip_package/build_pip_package ~/tensorflow_pkg
**and last install cmd：**/opt/python/python-3.7.9/bin/pip3.7 install  ~/tensorflow_pkg/tensorflow-xxx.whl

> @zhangqiang-hf
> 1.
> I checked this i7-4790 , it includes 4 cores, 8 threads.
> Please set with 4 in above setting.
> 
> 
> Could you share the build cmd for the TF with MKL on i7?
> or the cmd to install it.

cat /proc/cpuinfo， it displays 8 processor，but cpu cores =4， ok， I will set 
export TF_NUM_INTRAOP_THREADS=4
export OMP_NUM_THREADS=4

**2. build cmd（with onednn）：**
bazel build --verbose_failures --config=noaws --config=mkl --config=opt  --action_env=BAZEL_LINKLIBS=-l%:libstdc++.a --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package

**if no use onednn， omitted “--config=mkl”。**

**then generate whl：**bazel-bin/tensorflow/tools/pip_package/build_pip_package ~/tensorflow_pkg
**and last install cmd：**/opt/python/python-3.7.9/bin/pip3.7 install  ~/tensorflow_pkg/tensorflow-xxx.whl

**Comment by NeoZhangJianyu** [comment]
@zhangqiang-hf 
Have you modified the scripts in resnet50.zip which detect the performance?
If yes, could you share your latest scripts?

I will reproduce your issue local.

**Comment by zhangqiang-hf** [comment]
> @zhangqiang-hf
> Have you modified the scripts in resnet50.zip which detect the performance?
> If yes, could you share your latest scripts?
> 
> I will reproduce your issue local.

Yes, I have modified the test file.  please see the attach file. 
when test, I have set
export TF_ENABLE_MKL_NATIVE_FORMAT=1
export TF_NUM_INTEROP_THREADS=1
export TF_NUM_INTRAOP_THREADS=4
export OMP_NUM_THREADS=4
export KMP_BLOCKTIME=1
export KMP_AFFINITY=granularity=fine,compact,1,0

and the test result is that:
case1:   resnet50-onepic.py,  do the predict for one picture
case2：resnet50-bs100.py,  one pic reproduce 100 times and call predict once,
case3：resnet50-one100.py,  one pic do 100 predict
case4：resnet50-100pic.py,  100 different pics，one pic do once predict，so do 100 predicts in all
Now，case2/3/4， resnet50 inference the result is the same：
1）use tensorflow with onednn，do the optimize setting above is quicker than not do the optimize setting for case2/3/4
2）but，use tensorflow with onednn do the optimize setting above is still a bit slower or nearby the tensorflow not use onednn， it is not better than not use mkl ！
3）case1， that is no effect when do the optimize setting when tensorflow use mkl. it is still slower!
[
[resnet50.zip](https://github.com/tensorflow/tensorflow/files/5656742/resnet50.zip)
](url)

**Comment by NeoZhangJianyu** [comment]
@zhangqiang-hf 
case1: resnet50-onepic.py
The problem you mentioned is present.
But, I repeat the predict() 100 times and got the average time, it's a little better than stack TF.

```
times = 100
    a = time.time()
    for i in range(times):
        preds = model.predict(x)
    b = time.time()
    seconds = (b - a)/times
```

The reason was explained in preview comment:
"
@zhangqiang-hf @Zantares
As answer from Zantares: "Bad performance is expected if you only run session once because TF with oneDNN will take more time in warmup (1st iteration). You will get similar performance with different pics as long as you don't change pic shape. In same word, TF with oneDNN doesn't care about data, it only cares shape."

I just test to run 100 times for BS=1.
The performance of TF with MKL is better than stack TF.
"

case2：resnet50-bs100.py
better 

Case 3: resnet50-one100.py, one pic do 100 predict
better

case4：resnet50-100pic.py
I have not such dataset, so not run it.
But the code is not good to test the performance as I said: 
The running time includes the image load process. That would be impacted by both IO and CPU.
So, this case can't be recommended to test the CPU performance load.

Could you run following cmd and paste the output?
```
lscpu
```
In my case, I use Intel(R) Xeon(R) Gold 6252 CPU @ 2.10GHz which including 24 cores.
I use numactrl to limit only 4 cores to be used:
```
numactl -C 1-4 -m 0 python resnet50-bs100.py

```

**Comment by zhangqiang-hf** [comment]
> @zhangqiang-hf
> case1: resnet50-onepic.py
> The problem you mentioned is present.
> But, I repeat the predict() 100 times and got the average time, it's a little better than stack TF.
> 
> ```
> times = 100
>     a = time.time()
>     for i in range(times):
>         preds = model.predict(x)
>     b = time.time()
>     seconds = (b - a)/times
> ```
> 
> The reason was explained in preview comment:
> "
> @zhangqiang-hf @Zantares
> As answer from Zantares: "Bad performance is expected if you only run session once because TF with oneDNN will take more time in warmup (1st iteration). You will get similar performance with different pics as long as you don't change pic shape. In same word, TF with oneDNN doesn't care about data, it only cares shape."
> 
> I just test to run 100 times for BS=1.
> The performance of TF with MKL is better than stack TF.
> "
> 
> case2：resnet50-bs100.py
> better
> 
> Case 3: resnet50-one100.py, one pic do 100 predict
> better
> 
> case4：resnet50-100pic.py
> I have not such dataset, so not run it.
> But the code is not good to test the performance as I said:
> The running time includes the image load process. That would be impacted by both IO and CPU.
> So, this case can't be recommended to test the CPU performance load.
> 
> Could you run following cmd and paste the output?
> 
> ```
> lscpu
> ```
> 
> In my case, I use Intel(R) Xeon(R) Gold 6252 CPU @ 2.10GHz which including 24 cores.
> I use numactrl to limit only 4 cores to be used:
> 
> ```
> numactl -C 1-4 -m 0 python resnet50-bs100.py
> ```

Dear sir,
my test result with cost time as bellow:
  case1:  onepic,  slower then not use onednn, you known.   (with onednn:1.3s,    not with onednn :0.6s)
  case2:  bs100,  nearby   (with onednn:4.7s,  not with onednn:4.5s)
  case3:  one100,  slower  (with onednn: 9.5s,   not with onednn:6.8s)
  case4: 100pic, a bit quicker (with onednn:24s,  not with onednn:27s)
for this four cases, I test the same test script with the two situation（tensorflow  with onednn or not with onednn），the optimize setting as said above。

lscpu infor as bellow:

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 60
Model name:            Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
Stepping:              3
CPU MHz:               900.140
CPU max MHz:           4000.0000
CPU min MHz:           800.0000
BogoMIPS:              7184.05
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              8192K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm invpcid_single kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm xsaveopt dtherm ida arat pln pts

**Comment by NeoZhangJianyu** [comment]
@zhangqiang-hf 
I use following cmd to build the TF with MKL:
```
bazel build --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 --copt=-O3 --copt=-Wformat --copt=-Wformat-security --copt=-fstack-protector --copt=-fPIC --copt=-fpic --linkopt=-znoexecstack --linkopt=-zrelro --linkopt=-znow --linkopt=-fstack-protector --config=mkl  --copt=-march=native //tensorflow/tools/pip_package:build_pip_package 
```

You can try it and test.

**Comment by zhangqiang-hf** [comment]
> @zhangqiang-hf
> I use following cmd to build the TF with MKL:
> 
> ```
> bazel build --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 --copt=-O3 --copt=-Wformat --copt=-Wformat-security --copt=-fstack-protector --copt=-fPIC --copt=-fpic --linkopt=-znoexecstack --linkopt=-zrelro --linkopt=-znow --linkopt=-fstack-protector --config=mkl  --copt=-march=native //tensorflow/tools/pip_package:build_pip_package 
> ```
> 
> You can try it and test.

ok， later ， I will try to build as you said. These build items will give good performance?

**Comment by NeoZhangJianyu** [comment]
@zhangqiang-hf 
It's working for me.
I'm not sure for your case. 

Let's check the result.

If it's not working for you, there is no more method.
Your CPU is a little old, so that I can't reproduce it in same HW.

My test approve that TF with MKL is better in Intel Xeon CPU.

I have shared you all of common optimization methods on Intel CPU.
If you use non-Intel CPU, you could choose the TF version which is better in your platform.
I guess your target is to get the best performance on your CPU platform by TF with MKL.
Even if the method is working in i7, it's not sure for you CPU platform.

**Comment by NeoZhangJianyu** [comment]
@zhangqiang-hf 
Could you send me an email for your target?

**Comment by zhangqiang-hf** [comment]
> @zhangqiang-hf
> It's working for me.
> I'm not sure for your case.
> 
> Let's check the result.
> 
> If it's not working for you, there is no more method.
> Your CPU is a little old, so that I can't reproduce it in same HW.
> 
> My test approve that TF with MKL is better in Intel Xeon CPU.
> 
> I have shared you all of common optimization methods on Intel CPU.
> If you use non-Intel CPU, you could choose the TF version which is better in your platform.
> I guess your target is to get the best performance on your CPU platform by TF with MKL.
> Even if the method is working in i7, it's not sure for you CPU platform.

Yes，  My target is to get the best performance on my CPU platform(mips64 cpu) by TF-2.4.0 with oneDNN
I do the same test on X86 intel cpu. the result is above that I said.

**Comment by zhangqiang-hf** [comment]
> @zhangqiang-hf
> Could you send me an email for your target?

Dear sir, you are chinese? Do you have weixin? share we make a friend? can I add your weixin?

**Comment by NeoZhangJianyu** [comment]
@zhangqiang-hf Yes, could you send me an email, instead of comment here.

**Comment by zhangqiang-hf** [comment]
> @zhangqiang-hf Yes, could you send me an email, instead of comment here.



> @zhangqiang-hf Yes, could you send me an email, instead of comment here.

I have sent a email to you, please check it, thank you!
