### ISSUE TITLE
How could wide_n_deep tutorial apply for muti-class categoring task?

### ISSUE THREAD

**Issue by TaurusD** [tensorflow/tensorflow#4528]
### Environment info
Operating System: Linux

### What other attempted solutions have you tried?
delete the lines: 

    df_train[LABEL_COLUMN] = (df_train["label"].apply(lambda x: '>50K' in x)).astype(int)
    df_test[LABEL_COLUMN] = (df_test["label"].apply(lambda x: '>50K' in x)).astype(int)

which caused 'tensorflow.contrib.learn.python.learn.monitors.NanLossDuringTrainingError: NaN loss during training'. 

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by jmchen-g** [comment]
This is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag.
