### ISSUE TITLE
Import Error DLL failed

### ISSUE THREAD

**Issue by ObeyedSky622** [tensorflow/tensorflow#45287]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 (64bit)
- TensorFlow installed from (source or binary): install using conda in command window as admin
- TensorFlow version: 2.3.1
- Python version: 3.8.5
- Installed using virtualenv? pip? conda?: installed using conda then created virtual env
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: RTX 2060 16GB

**Describe the problem**
I have installed tensorflow on my windows desktop with anaconda. As a result I followed the steps from a youtube video by Jeff Heaton. Now I would like to run Tensorflow in  VS code and it will not work. I get an import error that says the following ImportError: DLL load failed while importing _pywrap_tensorflow_internal: %1 is not a valid Win32 application. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
The only code I have is an import line "import tensorflow as tf" when I run the script by using ctl+F5, I get the error. When I type "python test.py" in the no errors are thrown. (test.py is the name of my file)

**Creating and install packages and tensorflow for environment steps**
1. Run CMD as admin
2. conda create -n tensorflow-cpu python=3.8
3. conda activate tensorflow-cpu 
4. conda install jupyter matplotlib numpy pandas scipy
5. pip install tensorflow 
     got lots of messages that the requirement was already met.
6. python 
7. import tensorflow as tf
8. tf.__version__
9. 2.3.1
10. quit()
11. code (opens VS code)
12. create new file
13. import tensorflow as tf (autofill in works)
14. run
15. no error
16. add other packages (import matplotlib, pandas etc...)
17. autofill no longer works
18. create new file
19. import tensorflow as tf (autofill doesn't work)
20. run (error outputted in terminal)
21. run python test.py in terminal (no error)

**Any other info / logs**
Jeff heaton video link: https://www.youtube.com/watch?v=RgO8BBNGB8w&t=474s

**Comment by ObeyedSky622** [comment]
When I go back to cmd and run "code" again and open a new VS code window, it works again. Can someone explain?

**Comment by ravikyram** [comment]
@ObeyedSky622 

Looks like this is not issue with Tensorflow installation as you are able to import without any issues. 
This seems to be issue with VS code. Thanks!

**Comment by ObeyedSky622** [comment]
@ravikyram Then why when I run the code by pressing F5 I get the error and run I run in terminal I don't get anything? I also ran the script in IDLE and got the same error.

**Comment by ravikyram** [comment]
@ObeyedSky622 

Could you please create a new virtual environment and try running the code and see if the issue still persists.If you facing the issue request you to share the error log. Thanks!

**Comment by ObeyedSky622** [comment]
Yes. I have created 2 new environments already. Here is the full error:
Traceback (most recent call last):
  File "C:\Users\bre13\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: %1 is not a valid Win32 application.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\VS_code_files\ml_files\functionLib.py", line 8, in <module>
    import tensorflow as tf
  File "C:\Users\bre13\AppData\Roaming\Python\Python38\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\bre13\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\bre13\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\bre13\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\bre13\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\bre13\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: %1 is not a valid Win32 application.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ravikyram** [comment]
@ObeyedSky622 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website.](https://www.tensorflow.org/install/source_windows)
Please, check Your CPU/Python is on 32 bits?Please, refer #36167

Thanks!

**Comment by ObeyedSky622** [comment]
Yes, I figured the issue out. When I clicked download for python it auto-downloaded the 32-bit version and not the 64-bit. I uninstalled python and installed the correct version.

**Comment by ravikyram** [comment]
@ObeyedSky622 

TF supports 64 bit only.

Please, close this thread if your issue was resolved. Thanks!
