### ISSUE TITLE
randomly discontinuation when model training with tf.keras in tf-gpu-2.1

### ISSUE THREAD

**Issue by jianku122** [tensorflow/tensorflow#45297]
When I use model.fit to train my model, I get the below errors randomly at the beginning of the steps, or the code and gpus suddenly shut down without any error. Even sometimes self-reset occurs. 

Python Version: 3.7
Tesorflow Version: 2.1
OS: Windows 10
GPU Card: RTX 2080Ti * 4
CUDA: 10.1
CUDNN: 7.6.5.32

errors as follows
 E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
 F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:273] Unexpected Event status: 1

**Comment by ravikyram** [comment]
@jianku122 

Provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by jianku122** [comment]
code like this
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Masking, TimeDistributed, LSTM, Bidirectional
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras import backend as K

DUMMY_VALUE = -1.0

model = Sequential()
model.add(Masking(mask_value=DUMMY_VALUE, input_shape=(None, 100)))
model.add(Bidirectional(LSTM(100, return_sequences=True, implementation=1)))
model.add(TimeDistributed(Dense(1, activation='sigmoid')))
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy', K_precision, K_recall],
              sample_weight_mode='temporal')
model.summary()

modelName = 'test'
checkpoint = ModelCheckpoint(filepath='./model_checkpoints/{epoch:02d}-{val_loss:.4f}_' + modelName + '.h5', verbose=1, save_best_only=True, mode='min')
es = EarlyStopping(monitor='val_loss', mode='min', patience=10, verbose=1)

histories = []
histories.append( model.fit(padding_x, padding_y, epochs=30, batch_size=2, validation_split=0.1, callbacks=[es, checkpoint], sample_weight=w) )
model.save(modelName + '.h5')

error occurs like this
......
  49/2000 [..............................] - ETA: 2:29:49 - loss: 0.0072 - accuracy: 0.8820
  50/2000 [..............................] - ETA: 2:27:52 - loss: 0.0071 - accuracy: 0.8822
  51/2000 [..............................] - ETA: 2:25:58 - loss: 0.0070 - accuracy: 0.8835
  52/2000 [..............................] - ETA: 2:24:08 - loss: 0.0069 - accuracy: 0.8853
2020-12-01 19:55:35.557321: E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2020-12-01 19:55:35.557718: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:273] Unexpected Event status: 1

**Comment by ravikyram** [comment]
@jianku122 

Please, share colab link or complete code snippet with supporting files to reproduce the issue in our environment.I am seeing the error messages (`NameError: name 'K_precision' is not defined`).Request you to share reproducible code and helps using localizing the issue faster. Thanks!
