### ISSUE TITLE
tflite 2.4 build benchmark_model error on ubuntu 16.04 (cmake)

### ISSUE THREAD

**Issue by lxiao217** [tensorflow/tensorflow#45290]
when i build tflite2.4 on Ubuntu, i encount the problem:
i can success build libtensorflow-lite.a with CMakeLists.txt use CMake, but when i buildbenchmark-model i got these errors:
my build command is : make benchmark-model
errors:

[ 98%] Linking CXX executable benchmark_model
_deps/xnnpack-build/libXNNPACK.a(4x16c8-minmax-avx512skx.c.o): In function `xnn_qs8_gemm_minmax_ukernel_4x16c8__avx512skx':
4x16c8-minmax-avx512skx.c:(.text+0x720): undefined reference to `_kshiftli_mask64'
4x16c8-minmax-avx512skx.c:(.text+0x753): undefined reference to `_kshiftli_mask64'
4x16c8-minmax-avx512skx.c:(.text+0x785): undefined reference to `_kshiftli_mask64'
_deps/xnnpack-build/libXNNPACK.a(4x16c8-minmax-avx512skx.c.o): In function `xnn_qs8_igemm_minmax_ukernel_4x16c8__avx512skx':
4x16c8-minmax-avx512skx.c:(.text+0x7a2): undefined reference to `_kshiftri_mask64'
4x16c8-minmax-avx512skx.c:(.text+0x7d4): undefined reference to `_kshiftri_mask64'
4x16c8-minmax-avx512skx.c:(.text+0x80d): undefined reference to `_kshiftri_mask64'
collect2: error: ld returned 1 exit status
CMakeFiles/benchmark_model.dir/build.make:382: recipe for target 'benchmark_model' failed
make[3]: *** [benchmark_model] Error 1
CMakeFiles/Makefile2:2012: recipe for target 'CMakeFiles/benchmark_model.dir/all' failed
make[2]: *** [CMakeFiles/benchmark_model.dir/all] Error 2
CMakeFiles/Makefile2:2019: recipe for target 'CMakeFiles/benchmark_model.dir/rule' failed
make[1]: *** [CMakeFiles/benchmark_model.dir/rule] Error 2
Makefile:199: recipe for target 'benchmark_model' failed
make: *** [benchmark_model] Error 2

this puzzled me for a long time , appreciate your reply!

the CMakeLists.txt help me much ,but also has some errors i think , for example the xnnpack delegate switch to control build with xnnpack delegate. i found use TFLITE_ENABLE_XNNPACK  to control xnnpack delegate will get errors when i build shared library in windows x64. so i change the source code.

email:   lxiao217@163.com

**Comment by terryheo** [comment]
It works well for me with r2.4 branch.
Could you check if you're using up-to-date r2.4 branch?

BTW, here is the official guide on CMake build
https://www.tensorflow.org/lite/guide/build_cmake

**Comment by lxiao217** [comment]
> It works well for me with r2.4 branch.
> Could you check if you're using up-to-date r2.4 branch?
> 
> BTW, here is the official guide on CMake build
> https://www.tensorflow.org/lite/guide/build_cmake


thanks for your reply, the reason for this problem is my gcc/g++ version too low, avx512 is supported after 6.x, but mine is 5.x, so i upgrade it to 9.0 and this problem solved.

but this build also has problem when i build dynamic libraries in ubuntu/windows et.
test_delegate_providers.cpp in line 29 and 40 throw errors with unrecognized reference of Merge and Parse.

**Comment by terryheo** [comment]
@lxiao217 could you share the command you used to build dynamic libraries?

**Comment by lxiao217** [comment]
> @lxiao217 could you share the command you used to build dynamic libraries?

i added "shared" in CMakeLists.txt like this:
# TFLite library
add_library(tensorflow-lite SHARED 
  ${TFLITE_CORE_API_SRCS}

and then" cmake ./ -B ./build  ", then errors up thrown. i annotated those code at last, i dont know if this action will have other bad influence. though this code in test file.

**Comment by terryheo** [comment]
Could you try if the patch https://github.com/tensorflow/tensorflow/commit/94550574cdc0b0c61181d10d1df87eed60f4d7fa helps?

**Comment by lxiao217** [comment]
> Could you try if the patch [9455057](https://github.com/tensorflow/tensorflow/commit/94550574cdc0b0c61181d10d1df87eed60f4d7fa) helps?

thanks very much! i  will try later.
 when i build so in ubuntu16.04, i get the dynamic library libtensorflow-lite.so, but when i use it  in my demo , errors were thrown  like this:

/tmp/cifar10-d10aa3.o: In function `cv::String::operator=(cv::String const&)':
/usr/include/opencv2/core/cvstd.hpp:656: undefined reference to `cv::String::deallocate()'
/home/xiaoling/tf_build/tflite_test/libs/x86_64/libtensorflow-lite.so: undefined reference to `TfLiteXNNPackDelegateOptionsDefault'
/home/xiaoling/tf_build/tflite_test/libs/x86_64/libtensorflow-lite.so: undefined reference to `TfLiteXNNPackDelegateCreate'
/home/xiaoling/tf_build/tflite_test/libs/x86_64/libtensorflow-lite.so: undefined reference to `TfLiteXNNPackDelegateDelete'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)


when i build so, i close the switch to build with xnnpack:

option(TFLITE_ENABLE_XNNPACK "Enable XNNPACK backend" OFF)

this option is set ON default.

otherwise, seek for some helps:
when i build tflite, many thirdparty  will be pull but the network speed  is limited here, so i want to copy those 3rdparty to new folder where i want to save my building files. but the build script will delete files in these folder like eigen, and pull it from remote server in gitlab. this will waste me much time. 
where i can set use local 3rdparty files, please give me some advise, i search in the build scripts will need much time. thanks for your help!

**Comment by banditopazzo** [comment]
> when i build so in ubuntu16.04, i get the dynamic library libtensorflow-lite.so, but when i use it in my demo

Hi, we had the same problem (undefined reference to TfLiteXNNPackDelegateCreate, `TfLiteXNNPackDelegateDelete, also Parse and Merge problem).

The patch [9455057](https://github.com/tensorflow/tensorflow/commit/94550574cdc0b0c61181d10d1df87eed60f4d7fa) seems to solve our issue, but it's not present in the r2.4 branch and we had to pull directly from the master

**Comment by sanatmpa1** [comment]
@lxiao217,

Can you update to the latest stable version i.e `2.6.0` and let us know if the issue still persists? Thanks!
