### ISSUE TITLE
[mbed] ERROR: Unable to write build ignore file 

### ISSUE THREAD

**Issue by 1248479912** [tensorflow/tensorflow#45292]
hi,guys, when I compile the example project "image_recognition_experimental", a mbed error occurs.
```
salt@ubuntu:/usr/local/project/tensorflow/tensorflow/lite/micro/tools/make/gen/linux_x86_64/prj/image_recognition/mbed$ sudo mbed compile -m auto -t GCC_ARM --profile release
[sudo] password for salt: 
[mbed] Working path "/usr/local/project/tensorflow/tensorflow/lite/micro/tools/make/gen/linux_x86_64/prj/image_recognition/mbed" (program)
[mbed] Detected "DISCO_F746NG" connected to "/media/salt/DIS_F746NG" and using com port "/dev/ttyACM0"
[mbed] ERROR: Unable to write build ignore file in "/usr/local/project/tensorflow/BUILD/.mbedignore"
---
But the "BUILD" is not a folder, and does have write permission, just as follows,

root@ubuntu:/usr/local/project/tensorflow# ll
total 580
drwxr-xr-x  8 root root   4096 Nov 30 17:08 ./
drwxr-xr-x  3 root root   4096 Nov 30 17:02 ../
-rw-r--r--  1 root root   2219 Nov 30 17:02 ACKNOWLEDGMENTS
-rw-r--r--  1 root root   1174 Nov 30 17:02 arm_compiler.BUILD
-rw-r--r--  1 root root    349 Nov 30 17:02 AUTHORS
-rw-r--r--  1 root root  32964 Nov 30 17:02 .bazelrc
-rw-r--r--  1 root root      6 Nov 30 17:02 .bazelversion
-rw-rw-rw-  1 root root    122 Nov 30 17:02 BUILD
-rw-r--r--  1 root root   5360 Nov 30 17:02 CODE_OF_CONDUCT.md
-rw-r--r--  1 root root    573 Nov 30 17:02 CODEOWNERS
-rwxr-xr-x  1 root root    285 Nov 30 17:02 configure*
-rw-r--r--  1 root root    782 Nov 30 17:02 configure.cmd
-rw-r--r--  1 root root  53321 Nov 30 17:02 configure.py
-rw-r--r--  1 root root   9906 Nov 30 17:02 CONTRIBUTING.md
drwxrwxrwx  8 root root   4096 Nov 30 17:08 .git/
drwxr-xr-x  4 root root   4096 Nov 30 17:02 .github/
-rw-r--r--  1 root root    896 Nov 30 17:02 .gitignore
-rw-r--r--  1 root root    606 Nov 30 17:02 ISSUES.md
-rw-r--r--  1 root root   2232 Nov 30 17:02 ISSUE_TEMPLATE.md
-rw-r--r--  1 root root  11419 Nov 30 17:02 LICENSE
-rw-r--r--  1 root root      7 Nov 30 17:10 .mbed
drwxr-xr-x 19 root root   4096 Nov 30 17:07 mbed-os/
-rw-r--r--  1 root root     77 Nov 30 17:07 mbed-os.lib
-rw-r--r--  1 root root   1339 Nov 30 17:08 mbed_settings.py
-rw-r--r--  1 root root    328 Nov 30 17:02 models.BUILD
-rw-r--r--  1 root root     34 Nov 30 17:02 .pylintrc
-rw-r--r--  1 root root  21169 Nov 30 17:02 README.md
-rw-r--r--  1 root root 319193 Nov 30 17:02 RELEASE.md
-rw-r--r--  1 root root  13158 Nov 30 17:02 SECURITY.md
drwxr-xr-x 16 root root   4096 Nov 30 17:02 tensorflow/
drwxr-xr-x 46 root root   4096 Nov 30 17:02 third_party/
drwxr-xr-x  2 root root   4096 Nov 30 17:02 tools/
-rw-r--r--  1 root root   4246 Nov 30 17:02 WORKSPACE
root@ubuntu:/usr/local/project/tensorflow# cd BUILD 
bash: cd: BUILD: Not a directory

The content of BUILD is 

exports_files(
    [
        "LICENSE",
        "ACKNOWLEDGEMENTS",
        "configure",
        "configure.py",
    ],
)
```
So I really don't know why this error occurs, and how to solve it. I hope someone of you have a good idea about this, 
                                                                                                                                                                               Thanks a lot!

**Comment by ymodak** [comment]
Did you install the [prerequisites](https://stackoverflow.com/a/63312051/11127923) as mentioned in the tutorial?

**Comment by 1248479912** [comment]
hi ymodak,
Thank you very much for your answering,
 I installed just as that, I can show you what I have installed.

salt@ubuntu:/usr$ python --version
Python 2.7.17 (Python 3.8.0) I tryed both;
salt@ubuntu:/usr/local3$ pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
salt@ubuntu:/usr/local$ mbed-cli --version
1.10.5

**mbed-os  and tensorflow  are same root addr.**

salt@ubuntu:/usr/local/project/tensorflow$ ls
ACKNOWLEDGMENTS     CODEOWNERS       ISSUE_TEMPLATE.md   __pycache__   tools
arm_compiler.BUILD  configure        LICENSE            README.md    WORKSPACE
AUTHORS             configure.cmd    **mbed-os**            RELEASE.md
BUILD               configure.py     mbed-os.lib        SECURITY.md       CONTRIBUTING.md  mbed_settings.py   **tensorflow**
CODE_OF_CONDUCT.md  ISSUES.md        models.BUILD       third_party

salt@ubuntu:/usr/local$ ls
bin  games    icetea_lib  lib  **project**  share
etc  **gcc-arm-none-eabi-9-2020-q2-update**  include     man  sbin     src

salt@ubuntu:/usr/local/project/tensorflow$ mbed config --list
[mbed] Global config:
GCC_ARM_PATH=/usr/local/gcc-arm-none-eabi-9-2020-q2-update/bin

[mbed] Local config (/usr/local/project/tensorflow):
No local configuration is set

**Building and Compiling**

salt@ubuntu:/usr/local/project/tensorflow$ _sudo make -f tensorflow/lite/micro/tools/make/Makefile TAGS=disco_f746ng generate_image_recognition_mbed_project_
tensorflow/lite/micro/tools/make/downloads/flatbuffers already exists, skipping the download.
tensorflow/lite/micro/tools/make/Makefile:476: warning: overriding recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
tensorflow/lite/micro/tools/make/Makefile:476: warning: ignoring old recipe for target 'tensorflow/lite/micro/tools/make/downloads/person_model_int8'
salt@ubuntu:/usr/local/project/tensorflow$ _cd tensorflow/lite/micro/tools/make/gen/linux_x86_64/prj/image_recognition/mbed/_
salt@ubuntu:/usr/local/project/tensorflow/tensorflow/lite/micro/tools/make/gen/linux_x86_64/prj/image_recognition/mbed$  _mbed config root ._
[mbed] WARNING: Unable to write config file /usr/local/project/tensorflow/.mbed
---
salt@ubuntu:/usr/local/project/tensorflow/tensorflow/lite/micro/tools/make/gen/linux_x86_64/prj/image_recognition/mbed$ _sudo  mbed config root ._
[mbed] . now set as default root in program "tensorflow"
salt@ubuntu:/usr/local/project/tensorflow/tensorflow/lite/micro/tools/make/gen/linux_x86_64/prj/image_recognition/mbed$ _sudo mbed deploy_
[mbed] Working path "/usr/local/project/tensorflow/tensorflow/lite/micro/tools/make/gen/linux_x86_64/prj/image_recognition/mbed" (program)
[mbed] Updating library "" to rev #4e0d07d50fdf
[mbed] Updating library "BSP_DISCO_F746NG" to rev #df2ea349c37a
[mbed] Updating library "mbed-os" to rev #4e0d07d50fdf
[mbed] Updating library "LCD_DISCO_F746NG" to rev #d44525b1de98 (tag: tip)
salt@ubuntu:/usr/local/project/tensorflow/tensorflow/lite/micro/tools/make/gen/linux_x86_64/prj/image_recognition/mbed$ _sudo mbed compile -m auto -t GCC_ARM --profile release_
[mbed] Working path "/usr/local/project/tensorflow/tensorflow/lite/micro/tools/make/gen/linux_x86_64/prj/image_recognition/mbed" (program)
[mbed] Detected "DISCO_F746NG" connected to "/media/salt/DIS_F746NG" and using com port "/dev/ttyACM0"
[mbed] ERROR: Unable to write build ignore file in "/usr/local/project/tensorflow/BUILD/.mbedignore"
---

**Comment by ymodak** [comment]
Can you try and compile with `DISCO_F746NG` flag?
`mbed compile -m DISCO_F746NG -t GCC_ARM --profile release`

**Comment by raymondsonhinton2** [comment]
ometimes git does not exclude files/folders added .gitignore especially if you had commited them before. Here is how to fix it. I am ignoring [node_modules](https://user-images.githubusercontent.com/17564080/51767305-ef21a700-20aa-11e9-98b2-01d7a76b403c.png) from Angular project as an example
 Update .gitignore with the folder/file name you want to ignore. You can use anyone of the formats mentioned below (prefer format1)
### Format1  ###
node_modules/
node/
### Format2  ###
**/frontend/node_modules/**
**/frontend/node/**
 Commit all the changes to git. Exclude the folder/files you don't want commit, in my case node_modules
Execute the following command to clear the cache
git rm -r --cached .
Execute git status command and [it](https://protrackinghub.com/) should output node_modules and sub directories marked for deletion
Now execute
git add .
git commit -m "fixed untracked files"
