### ISSUE TITLE
distribute tensorflow chief node OOM

### ISSUE THREAD

**Issue by haibarasiao** [tensorflow/tensorflow#4530]
sorry to trouble.
my model has 6 conv layer and a softmax layer. kernel size is 3*3, channel is 192, num class is 300.
I run a distribute model with 20 Tesla K40m.
when I run one ps job and 5 worker job, everything is fine. But when I run a ps job and 19 worker jobs in 20 PC, when the chief node Initialize for node 15, it gets the OOM error.
I don't know how to deal with it.
Anyone can help me?

**Comment by jmchen-g** [comment]
Using 1 ps for 19 workers is very likely to make PS the system's bottleneck. Can you use say 5 ps instead?

**Comment by haibarasiao** [comment]
Ok,I will try 5 ps job and response soon

**Comment by haibarasiao** [comment]
@jmchen-g sad ,it also out of memory:

Ran out of memory trying to allocate 33.84MiB.  See logs for memory state.
Resource exhausted: OOM when allocating tensor with shape[128,32,32,192]

**Comment by haibarasiao** [comment]
and I get the log here:
I tensorflow/core/common_runtime/bfc_allocator.cc:692] 1 Chunks of size 69745664 totalling 66.51MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:692] 1 Chunks of size 76568576 totalling 73.02MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:692] 1 Chunks of size 77224448 totalling 73.65MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:692] 1 Chunks of size 78678016 totalling 75.03MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:692] 2 Chunks of size 78839808 totalling 150.38MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] Sum Total of in-use chunks: 10.51GiB
I tensorflow/core/common_runtime/bfc_allocator.cc:698] Stats: 
Limit:                 11325259776
InUse:                 11284158720
MaxInUse:              11324800256
NumAllocs:                  843917
MaxAllocSize:           1049763840


My RAM is 128G,and what does the limit mean?

**Comment by haibarasiao** [comment]
and I tried : config.gpu_options.allocator_type='BFC'
but also OOM occured.

Limit:                 11325259776
InUse:                 11303057152
MaxInUse:              11324129024
NumAllocs:                  684755
MaxAllocSize:           1065501696

so, how could I fixed this problem in distribute tensorflow?

**Comment by jmchen-g** [comment]
when you say when the chief initialize node 15, what do you mean by that? The chief should not know the existence of other workers at all. All the workers only communicate with ps.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when additional information becomes available. Thanks!
